### ISSUE TITLE
Event Binding Syntax Error Not Caught by Compiler

### ISSUE THREAD

**Issue by rayenchtioui** [angular/angular#56885]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

When there is a space or an unintended newline in the event binding syntax within an Angular template, it results in a cryptic runtime error:

`ERROR DOMException: Failed to execute 'setAttribute' on 'Element': '(' is not a valid attribute name.`

This error message is not helpful in identifying the actual issue, which is a misplaced space or newline in the event binding syntax. The Angular compiler should ideally catch such syntax errors during the build process and provide a more descriptive error message to help developers quickly identify and fix the issue.
As this example shows:
`<div class="exercise">
        <app-exercise [editMode]="editMode" [exercise]="exerciseGroups[0]" [sets]="sets" (
            exerciseData)="handleExerciseData($event, 0)">
        </app-exercise>
    </div>
`
The Angular compiler should detect and flag the incorrect syntax for event binding during the build process. A more descriptive error message should be provided, such as:

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-zyuyay?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
core.mjs:11483 ERROR DOMException: Failed to execute 'setAttribute' on 'Element': '(' is not a valid attribute name.
    at EmulatedEncapsulationDomRenderer2.setAttribute (http://localhost:4200/vendor.js:134992:10)
    at BaseAnimationRenderer.setAttribute (http://localhost:4200/vendor.js:133970:19)
    at setUpAttributes (http://localhost:4200/vendor.js:53138:18)
    at setupStaticAttributes (http://localhost:4200/vendor.js:59586:5)
    at ɵɵelementStart (http://localhost:4200/vendor.js:67821:3)
    at Module.ɵɵelement (http://localhost:4200/vendor.js:67892:3)
    at TrisetComponent_ng_container_0_Template (http://localhost:4200/main.js:11206:60)
    at executeTemplate (http://localhost:4200/vendor.js:63689:9)
    at renderView (http://localhost:4200/vendor.js:64833:7)
    at createAndRenderEmbeddedLView (http://localhost:4200/vendor.js:75311:3)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.0.7
Node: 18.20.3
Package Manager: npm 10.2.3
OS: linux x64

Angular: 18.0.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.7
@angular-devkit/build-angular   18.0.7
@angular-devkit/core            18.0.7
@angular-devkit/schematics      18.0.7
@angular/cli                    18.0.7
@schematics/angular             18.0.7
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.7
```

### Anything else?

This error is particularly hard to debug, especially in large templates with lots of bindings. When working on a file that contains many HTML tags, identifying the misplaced space or newline requires reading through the HTML elements one by one, which is time-consuming and error-prone.

In scenarios where the component is being nested, it becomes even more challenging to see every child component and read through the HTML to find the error. A more descriptive error message would significantly improve the developer experience by making it easier to identify and fix the issue.

**Comment by JoostK** [comment]
Thanks for the report, this is being tracked in https://github.com/angular/angular/issues/39781
