### ISSUE TITLE
angular 18 signal set and update will not trigger change detection in some cases.

### ISSUE THREAD

**Issue by asanoic** [angular/angular#56884]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

following code create signal in template, but the signal change will not trigger change detection, the project uses `provideExperimentalZonelessChangeDetection()`

```typescript
import { ChangeDetectorRef, Component, signal, WritableSignal } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { firstValueFrom, timer } from 'rxjs';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet],
  template: `
<div>
  @if (newSignal({value: false}); as working) {
    <button (click)="btnClick(working)">
      @if (working().value) {
        <span> working ... </span>
      } @else {
        <span> click to work </span>
      }
      <i> {{ working().value }}</i>
    </button>
  }
</div>

<div>
  {{ abc() }}
</div>  
  `
})
export class AppComponent {

  abc = this.newSignal("asdf");

  constructor(
    private cd: ChangeDetectorRef,
  ) {
    //
  }

  async btnClick(working: WritableSignal<any>): Promise<void> {
    // use update or set wont work
    working.update(x => {
      x.value = true;
      return x;
    });

    await firstValueFrom(timer(1000));

    // use update or set wont work
    working.update(x => {
      x.value = false;
      return x;
    });

    // uncomment following line change detection happens
    // this.abc.set("changed"); 
  }

  newSignal(data: any): WritableSignal<any> {
    return signal(data, { equal: () => false });
  }
}
```

### Please provide a link to a minimal reproduction of the bug

N/A

### Please provide the exception or error you saw

```true
no error or exception output in browser console.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.0.7
Node: 22.4.0
Package Manager: npm 10.8.1
OS: linux x64

Angular: 18.0.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.7
@angular-devkit/build-angular   18.0.7
@angular-devkit/core            18.0.7
@angular-devkit/schematics      18.0.7
@angular/cli                    18.0.7
@schematics/angular             18.0.7
rxjs                            7.8.1
typescript                      5.4.5
```

**Comment by JeanMeche** [comment]
You're mutating a signal that doesn't have a custom equal function. 

By default signals will check their dirtyness by checking if the reference has changed. 

For example 
```
    working.update(x => {
      x.value = true;
      return x;
    });
```

should be 

```
    working.update(x => {
      return {...x, value: true};
    });
```

**Comment by asanoic** [comment]
I did it
```typescript
  newSignal(data: any): WritableSignal<any> {
    return signal(data, { equal: () => false });
  }
```

**Comment by asanoic** [comment]
could you reopen this? @JeanMeche

**Comment by JeanMeche** [comment]
Can you provide a stackblitz repro where this doesn't work ?

**Comment by JoostK** [comment]
Note that using `newSignal({value: false})` within the template creates a new signal during each change detection cycle, which is unlikely what you want to bed doing and likely the cause of the problem you're experiencing.

**Comment by asanoic** [comment]
@JeanMeche https://stackblitz.com/~/github.com/asanoic/test-angular-signal
after click button it should show "working..." and after 1 second the text should restore back

**Comment by asanoic** [comment]
I see, but how to explain when uncomment `this.abc.set("changed");` everything works as expected?

> Note that using `newSignal({value: false})` within the template creates a new signal during each change detection cycle, which is unlikely what you want to bed doing and likely the cause of the problem you're experiencing.
