### ISSUE TITLE
Angular 18 TS config Doc routing fails 

### ISSUE THREAD

**Issue by hzyniecki** [angular/angular#56897]
### Describe the problem that you experienced

When navigating to the new angular.dev route provided in the deprecation error for the Typescript Configuration page the link runs dead/ doesn't display content.
https://v17.angular.io/guide/typescript-configuration#tsconfig 

https://angular.dev/reference/configs/typescript-configuration

### Enter the URL of the topic with the problem

https://v17.angular.io/guide/typescript-configuration#tsconfig

**Comment by JeanMeche** [comment]
Duplicate of #56893
