### ISSUE TITLE
Missing @For page in a

### ISSUE THREAD

**Issue by PierGiulioMinetti** [angular/angular#56908]
### Describe the problem that you experienced

Missing @For page in Angular 18 documentation

### Describe what you were looking for in the documentation

The documentation for the new @For function in Angular 18 documentation

### Describe what you want to experience that would fix the problem

Find on that page the actual documentation for the @For feature in Angular 18 documentation

**Comment by JoostK** [comment]
`@for` is documented on the [Control Flow](https://angular.dev/guide/templates/control-flow#for-block---repeaters) page.
