### ISSUE TITLE
Web worker api changes not included in change log in alpha.48

### ISSUE THREAD

**Issue by thelgevold** [angular/angular#5690]
It looks like the most recent changes to the web worker api were omitted from the alpha.48 change log.

After alpha.48 the web worker bootstrapping api changed quite a bit, so I think it should go in the change log.

It changed from a simple bootstrapWebWorker() call to the slightly more verbose:

```
platform([WORKER_APP_PLATFORM])
    .asyncApplication(setupWebWorker)
    .then((ref) => ref.bootstrap(myComponent));
```

I have it working with the new api, but it feels awfully verbose compared to the original code. Can't we just wrap all this in a single method instead? Why not just use the original bootstrapWebWorker as a wrapper?
Anyway, just a thought.

**Comment by PascalPrecht** [comment]
@thelgevold Check out this issue: https://github.com/angular/angular/issues/4834 and the corresponding [design doc](https://docs.google.com/document/d/1rbVTKTYLz6p2smQNYI8h4-QN-m2PS6F3iQIDmSzn0Ww/edit#heading=h.6cxvr9awtf5r)

**Comment by thelgevold** [comment]
Ok, the design doc makes several good points. Decoupling the app from the runtime environment is a great approach. I guess I didn't think of it this as a step towards generic bootstrapping, but I fully support this now!
