### ISSUE TITLE
Pipes API Documentation Missing

### ISSUE THREAD

**Issue by kbajpai** [angular/angular#56918]
### Describe the problem that you experienced

Link to Pipes API Documentation leads to _Page Not Found_

### Enter the URL of the topic with the problem

https://angular.dev/guide/pipes

### Describe what you were looking for in the documentation

Complete list of built-in pipes in angular documentation

### Describe the actions that led you to experience the problem

Clicked on the link provided

### Describe what you want to experience that would fix the problem

Displays the list of all the built-in pipes

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/813554/e6474d8a-2c1f-4489-93e5-9024266047d8)

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
N/A
```

### Provide any additional information here in as much as detail as you can

```true
N/A
```

**Comment by JeanMeche** [comment]
Duplicate of https://github.com/angular/angular/issues/52968
