### ISSUE TITLE
`inject` function throws error when used in `HttpInterceptorFn`

### ISSUE THREAD

**Issue by shrezaaa** [angular/angular#56916]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

I encountered an issue while using the inject function inside an HttpInterceptorFn. According to the Angular documentation, interceptors are run in the injection context of the injector which registered them and can use Angular's inject API to retrieve dependencies. However, when I attempt to use the inject function, it throws the following error:
`Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`.`

**Steps to Reproduce:** 

1. Create an HttpInterceptorFn as shown below:
```typescript 
export const authInterceptor: HttpInterceptorFn = (
  req,
  next,
): Observable<HttpEvent<unknown>> =>
  next(req).pipe(
    tap({
      error: (err: any) => {
        if (err instanceof HttpErrorResponse) {
          if (err.status === 401) {
            navigateOut();
          }
          inject(ErrorHandler).handleError(err);
        }
      },
    }),
  );
 ```
2. Add this to appconfig`provideHttpClient(withInterceptors([authInterceptor]))`
3. Run the application and trigger an HTTP request that results in an error.

**Expected Behavior:** The inject function should be able to retrieve the ErrorHandler dependency without throwing an error.

**Actual Behavior:** The inject function throws an error indicating it must be called from an injection context.

**Additional Context:** 
Angular version: 18.0.5
nx version: 19.4

### Please provide the exception or error you saw

```true
Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular version: 18.0.5
Nx version: 19.4
```

**Comment by JoostK** [comment]
This is working as expected. While the interceptor logic itself is executed in an injection context, the error callback within the Observable pipeline is not: that's invoked asynchronously at which point the injection context is no longer available.

**Comment by alxhub** [comment]
This is working as intended.

Interceptor functions do have injection context, but if you look at the stack trace of the error, it'll show you're inside of a callback (the `tap(...)` operator), not the interceptor function.

A solution is to inject the `ErrorHandler` and save it in a variable to use from within `tap()`.
