### ISSUE TITLE
@Attribute does not work on Typescript 1.6.2

### ISSUE THREAD

**Issue by shadow999** [angular/angular#5692]
I tried to pass an attribute into the constructor of my component by using @Attribute. But I got this compile error: Unable to resolve signature of parameter decorator when called as an expression. And I am using Typescript 1.6.2.

**Comment by vicb** [comment]
related: http://stackoverflow.com/questions/32538316/angular-2-attribute-annotation-does-not-compile

**Comment by shadow999** [comment]
@vicb I tried using Typescript 1.5.3. And it complains about Error in angular2.d.ts and ArrayLike in es6-shim.d.ts cannot be found. I am using those d.ts file from DefinitelyTyped. I am wondering if I need some special d.ts file to make Typescript 1.5.3 working.

**Comment by pkozlowski-opensource** [comment]
Closing as it is an obsolete support question, very likely resolved by a user looong time ago.
