### ISSUE TITLE
support for signal-based outputs of components, e.g. outputFromSignal() [Feature Request]

### ISSUE THREAD

**Issue by ptandler** [angular/angular#56923]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Not sure if I missed something. When I have a signal inside my component and I want this to be exposed as output only - there is no way to archive this yet, right?

If I want to use it as both input and output, there is `model()`. But do we have an equivalent for outputs yet?

So currently I probably would do:

```typescript
import { outputFromObservable } from '@angular/core/rxjs-interop';
import { toObservable } from '@angular/core/rxjs-interop';

@Component({
  // ...
})
export class MyComponent {
  private count = signal(0);
  
  public readonly countChanged = outputFromObservable(toObservable(this.count));

  increment() {
    this.count.update(value => value + 1);
  }
}
```

### Proposed solution

What about simplifying this to:

```typescript
import { outputFromSignal } from '@angular/core/rxjs-interop';

@Component({
  // ...
})
export class MyComponent {
  private count = signal(0);
  
  public readonly countChanged = outputFromSignal(this.count);

  increment() {
    this.count.update(value => value + 1);
  }
}
```

And / or then also add `outputToSignal`.

To take this one step further: I would like to directly get a (read-only) signal inside a parent component that uses MyComponent.

Is it possible to bind an output (signal) directly to a signal of the parent?

### Alternatives considered

1. see above using `outputFromObservable(toObservable(this.count))`
2. `effect(() => { this.countChanged.emit(this.count()); });`

**Comment by JoostK** [comment]
Outputs are _events_, whereas signals capture _state_; propagating _state_ as if they are events is a bit unnatural to me.

**Comment by pkozlowski-opensource** [comment]
To add to @JoostK comment - conceptually we can't observe the exact timing of setting the signal value (which I guess is the timing you would expect to emit the event).

How about emitting when you set a signal?

**Comment by ptandler** [comment]
> Outputs are _events_, whereas signals capture _state_; propagating _state_ as if they are events is a bit unnatural to me.

I think there are cases where I would like to pass _state_ to the outside, not an event. In this case, timing is not critical IMO. And that's basically what `outputFromObservable(toObservable(...))` does, right?

Or is there any other way to pass state to outside components already?

**Comment by pkozlowski-opensource** [comment]
> Or is there any other way to pass state to outside components already?

You could always expose a signal as a public instance of a said component and have other components / directives query it or use a local #ref. 

But maybe it means that there is a shared state that belongs to a service rather than a particular component?

**Comment by ptandler** [comment]
In case someone is interested: I tried several ways how one can pass child state to a parent:

I implemented 4 versions so far:

1. Define a `countChange` output via `outputFromObservable(toObservable(this.count))`
    - This was my initial idea I proposed above
2. Define a `countChange` output and use an `effect` to emit whenever the count changes
3. Pass a signal to be used for the output as input to the child component
    - not sure if this is an approach one would recommend, feels a bit strange
5. Provide a public read-only signal in the child component and access this via reference to the child component from its parent
    - actually this approach is quite elegant, however, wiring things together could benefit from some syntactic sugar.

See https://github.com/ptandler/angular-state-output-playground
and  https://stackblitz.com/~/github.com/ptandler/angular-state-output-playground

I didn't implement the version with a shared service, which is definitively a good choice if the state is a bit more complex.

**Comment by ptandler** [comment]
Added version 5 to https://github.com/ptandler/angular-state-output-playground using a service to share state between child and parent. However, how would you ensure that the parent is not allowed to modify the shared state? Only the child should be able to do this.
