### ISSUE TITLE
Broken link https://angular.dev/api/core/for

### ISSUE THREAD

**Issue by akanduru** [angular/angular#56948]
### Describe the problem that you experienced

Followed the above link on the page at https://v17.angular.io/api/core/for.

### Enter the URL of the topic with the problem

https://angular.dev/api/core/for

### Describe what you were looking for in the documentation

Documentation on @for 

### Describe the actions that led you to experience the problem

Followed the above link on the page at https://v17.angular.io/api/core/for.

### If this problem caused an exception or error, please paste it here

```true
Page Not Found 🙃

If you think this is a mistake, please open an issue so we can fix it.
```

**Comment by JeanMeche** [comment]
Hi, we're aware of this issue and already have a pending PR #56947.

**Comment by thesmiler** [comment]
Till then you can use https://angular.dev/api/core/@for
