### ISSUE TITLE
Deprication flag system

### ISSUE THREAD

**Issue by PGTBoos** [angular/angular#56941]
### Description

New angular versions, create new deprecations, 

I'd love to see a flag system in Angular! As a developer, I've often struggled to maintain deprecated or experimental features that still work but might be removed in future versions. It's like navigating a catwalk without a clear exit route, leaving me uncertain about the best path forward. If you start with new skinny clothing all plays nice, but older larger clothing is a problem.

A flag system would empower me to explicitly opt out of these features and ensure my code remains maintainable and future-proof, allowing me to continue using established syntaxes while still having the option to adopt newer ones as I see fit.

This flexibility would greatly improve my development experience, enabling me to balance innovation with stability and reduce the risk of breaking changes.

What do you think, Angular team? Could a flag system be added to give developers more control over their project's evolution?

### Proposed solution

All current deprications will be removed 
though in cases this gives problems, have environment.ts settings that can keep allowing certain things like old style routeguards for example.

One might also then be able to opt in for a set of specific new language features
As this lives at the project level special attention should be put to imports, as external imports may involve different flag setups.

### Alternatives considered

Freeze the language, no more deprecations, but add extension modules to enrich the language.

**Comment by alxhub** [comment]
Can you elaborate on what you mean by a flag system? 

As an alternative, there are tslint/eslint rules that prevent depending on deprecated APIs.

**Comment by jdegand** [comment]
@PGTBoos what you need may be covered by [ngx-flagr](https://github.com/pBouillon/ngx-flagr).  Check it out.

**Comment by PGTBoos** [comment]
Well it's not that I'm looking to implement a flag system in my projects.
I'm talking of Angular itself here the language.
Various methods are deprecated some from even before angular 15.
Though they're still work be it not recommended.
Especially the huge mega projects one doesn't easily change.
And thus after having them so long deprecated just accept them keep them remove deprication. Where possible fix. But don't intend to remove it.

And when new language futures get developed put those behind a flag system.
It would allow for beta, working, ironed out code, and people can then upgrade angular with the futures they do or don't want,  and the language can get mature.
Ea older angular projects can upgrade van get fixes but stay with some limited future set.

As the problem with angular is you can build but building a future on it is a bit risky one never knows what becomes obselete and with such activities other peoples project also never can end. All dependency projects also need to work with it have an opensource lib that isn't updated your screwwed.

More thought should be in how can angular get a stable life cycle instead of fancy new dress codes. I have a background in industrial automation tell a nuclear plant that they have to update their software every 2 year that some parts of their code will be depeicated and so you will need to code forever for them. 
This simply won't work. And despite browsers change the language needs to get stability. 

This is not a rant, but an urgent call to rethink lifecycle and possible ways to solve it like extending import comment

**Comment by jdegand** [comment]
You have to mitigate issues with better design and by lagging to implement new features.  For big changes, Angular usually provides code migrations to have your code updated automatically.  `ngxtension` also has some migrations that can update your code for you.  

To make code more maintainable, you can employ a `facade` design pattern.  You create an intermediate service that calls the third party library's methods.  You are free to replace that with another third party library anytime.  The components that depend on the service don't have to be updated.

You can also look into splitting components into presentational and container components.  The container components have the logic and you use `input` and `output` to pass the data between the components.  The presentational components just render the received data and don't have to be touched when logic changes.

**Comment by PGTBoos** [comment]
The point is as a result this language isn't robust, in contrast the plc structured text coding is a NEN norm, its robust for decenia many  years. A language without guarantees isnt future proof of a new future is breaking then it should be put behind flags as the language itself should not cause problems when updating.

This may sound strange but coding projects should be able to finish.
And not require attention of dev every 2 years a new LTS version comes out.
There should be no trickery required to achieve this as there no rules of what brick will be marked outdated trickery is even impossible.

Make this a real future  proof language, so it can be used in future proof scenarios. If a new future brakes the past put it behind a flag so people can opt out of it. The benefit for modules would be a landmark changer.

Outlook voor Android downloaden<https://aka.ms/ghei36>
________________________________

**Comment by alxhub** [comment]
Ah, I understand where you're coming from, but after discussion we don't think there are any changes to our release/deprecation process which make sense at this point.

While there could be some benefit to having runtime "don't let me use deprecated APIs" flags, the equivalent is also possible via `tslint` at build time, with the ability to opt out specific usages. We feel this is a better way of managing usage of deprecated APIs in a project.

A related question is whether we should remove deprecated APIs at all, or merely put them behind a flag and keep them in perpetuity. We don't feel this is viable for a few reasons:

1. The web platform itself is a moving target, and APIs that made sense before may not be sensible or even possible in the future.
2. Code size is a fundamental concern on the web, and retaining code to support different APIs that do similar things is a cost we don't want to pay. Tree-shaking via compile-time flags can mitigate this somewhat, but it's not always possible to structure APIs this way _and_ it significantly increases our maintenance cost.
3. We already invest in migrations that aim to reduce the cost of moving off of deprecated APIs as much as possible.
4. There are companies which provide extended long-term support for Angular releases to customers who have legal/regulatory requirements to use supported versions and do not actively update their applications.

Based on that, I'm going to go ahead and close this issue as non-actionable for us.
