### ISSUE TITLE
Unable to catch failed dynamic component imports

### ISSUE THREAD

**Issue by ms-dosx86** [angular/angular#56958]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

The problem:

1. You have a `lazy` route. Let's call it `LazyComponent`.
2. After deploying that lazy route has a separate chunk with a unique id. Something like that `lazy-4XF37HCG.js`.
3. A user opens the deployed app at different (from lazy) route. Let it be `/dashboard` route. At this point browser downloads `index.html` which has our lazy `lazy-4XF37HCG.js` in its `scripts`.
4. The user stays there for a bit.
5. We deploy a new version. The lazy route's chunk has different id, so now it looks different `lazy-VLNJ76V74.js`.
6. Now user decides to open the lazy route and their attempt fails with the following error

```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

TypeError: Failed to fetch dynamically imported module: https://example.com/lazy-4XF37HCG.js
```

This happens since the id of the lazy chunks has changed and now the user has to reload the page to fetch new `index.html` with updated `scripts` to be up to date and make things work.

Here are things that I've tried (and didn't work):

- Interceptors - they catch only http requests
- Handling navigation errors with `withNavigationErrorHandler` - config loader [doesn't catch](https://github.com/angular/angular/blob/8f08d0491630d46ed6d0ba2cfe70ed0e7a0bf58e/packages/router/src/navigation_transition.ts#L715) errors during component loads, hence `withNavigationErrorHandler` doesn't fire any navigation errors.

I might be missing something but I was unable to find anything that would help me catch this error and reload the page automatically for the user. Or is there a different approach to handle such problems?

### Please provide a link to a minimal reproduction of the bug

It's hard to reproduce so I provided a detailed explanation

**Comment by ms-dosx86** [comment]
I completely forgot about `ErrorHandler`. I could provide a custom `ErrorHandler` to handle the error.  In every project I would have to use a custom error handler. But I'm still wondering: is this a recommended approach? For me it doesn't look nice and scalable.

**Comment by JeanMeche** [comment]
This is a very common pattern yes and this is what we use for the https://angular.dev docs : 

https://github.com/angular/angular/blob/8f08d0491630d46ed6d0ba2cfe70ed0e7a0bf58e/adev/src/app/core/services/errors-handling/error-handler.ts#L15-L59

**Comment by ms-dosx86** [comment]
@JeanMeche Thank you for the response! Now I feel more confident using a custom `ErrorHandler`. Closing this issue.
