### ISSUE TITLE
Angular 18 router wouldn't allow to have lazy loaded modules unless there's at least one lazy loaded component

### ISSUE THREAD

**Issue by ilyakonrad** [angular/angular#56950]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

The project is not new but we keep it up-to-date version-wise. That being said, we haven't switched to standalone components fully and only use them for shared components with one exception that I'll cover next.

The app is initialized via
```
platformBrowserDynamic()
  .bootstrapModule(AppModule)
  .catch((error: Error) => console.error(error))
```

Our routing looks like this:
```
export const ROUTES: Routes = [
  { path: '', redirectTo: 'login', pathMatch: 'full' },
  { path: 'activate/:token', component: Dummy, canActivate: [ActivateRedirectGuard] },
  {
    matcher: groupOnboardingPageMatch,
    component: Dummy,
    canActivate: [GroupRegistrationRedirectGuard]
  },
  {
    path: 'manage-membership/:groupId',
    canActivate: [BrowserGuard, ManageMembershipRedirectGuard],
    component: Dummy
  },
  { path: 'login', component: LoginComponent, canActivate: [BrowserGuard, LoginGuard] },
  {
    path: 'reset-password/:token',
    loadChildren: () => import('./module/reset-password/reset-password.module').then((m) => m.ResetPasswordModule)
  },
  {
    path: 'invited-organization/:registration_code',
    loadChildren: () =>
      import('./module/register-invited-organization/register-invited-organization.module').then(
        (m) => m.RegisterInvitedOrganizationModule
      )
  },
  {
    path: 'dashboard',
    component: DashboardComponent,
    canActivate: [BrowserGuard, DashboardAuthGuard],
    canActivateChild: [BrowserGuard, DashboardAuthGuard],
    children: [
      { path: '', redirectTo: 'membership', pathMatch: 'full' },
      ...
      {
        path: 'economy',
        loadChildren: () =>
          import('./module/dashboard/tabs/economy-tab/economy-tab.module').then((m) => m.EconomyTabModule)
      },
      // {
      //   path: 'accounting',
      //   loadComponent: () =>
      //     import('./module/dashboard/tabs/accounting-tab/accounting-dashboard/accounting-dashboard.component').then(
      //       (m) => m.AccountingDashboardComponent
      //     )
      // },
      {
        path: 'locations',
        loadChildren: () =>
          import('./module/dashboard/tabs/locations-tab/locations-tab.module').then((m) => m.LocationsTabModule)
      }
      ...
    ]
  },
  { path: '404', component: NothingFoundComponent },
  { path: 'not-supported-browser', component: NotSupportedBrowserComponent },
  { path: '**', component: NothingFoundComponent }
]
```

It's imported into `app.module.ts` via `RouterModule.forRoot(ROUTES)`.

As you can see, under the "dashboard" route we're using modules to combine multiple components together and lazy-load those child components all at once. So each of those modules (like economy, locations and many more that I've omitted) have `RouterModule.forChild()` with the inner routes for every child component.

Notice the commented out "accounting" route. It's the only route that directly lazy-loads a standalone component. It's done this way because the library it uses now requires it to be standalone.

Here's the issue though. While trying to expand the "accounting" route to become a module like every other module (to have more routes inside) and simply import the AccountingDashboardComponent into that new module, I noticed that the runtime is broken with a random error `Error: Invalid provider for the NgModule 'NgxsRootModule' - only instances of Provider and Type are allowed, got: [..., ..., ?undefined?, ?undefined?, ?undefined?, ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ...]`.

In fact it doesn't even work if I **remove** the lazy-loading and directly state `component: AccountingDashboardComponent` for that route. In fact, and that's the weirdest part, it will fail even if I remove the "accounting" route completely...

Days of digging into this have lead me to conclusion that it has been broken in the version 18, because I can easily remove the route in my old branch that uses Angular 17 and everything's fine.

More specifically I found that in Angular 18 _I basically have to have at least one standalone component in my router in order for it to stop erroring_. I turned `ResetPasswordModule` (which only represents one component) into a standalone component and imported it directly into the router via `loadComponent` and that eliminated the error. Now I can update my old "accounting" route without any errors.

That is certainly not the resolution I want, something's not right, I want to understand it and fix it. I don't have to be forced to use standalone components this way.

### Please provide the exception or error you saw

```true
Error: Invalid provider for the NgModule 'NgxsRootModule' - only instances of Provider and Type are allowed, got: [..., ..., ?undefined?, ?undefined?, ?undefined?, ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ...]
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.0.2
Node: 20.11.1
Package Manager: yarn 1.22.19
OS: win32 x64

Angular: 18.0.1
... animations, cdk, common, compiler, compiler-cli, core, forms    
... language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, platform-server     
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.2
@angular-devkit/build-angular   18.0.2
@angular-devkit/core            18.0.2
@angular-devkit/schematics      17.3.8
@angular/cli                    18.0.2
@angular/fire                   17.0.1
@schematics/angular             18.0.2
rxjs                            7.8.1
typescript                      5.4.5
webpack                         5.91.0
zone.js                         0.14.6
```

### Anything else?

Unfortunately I couldn't create a reproduction of the bug. I've spent so much time trying, that I found a bug in the Stackblitz itself: it doesn't handle Angular routing correctly anymore...

**Comment by alxhub** [comment]
Without a reproduction this won't be actionable for us. Very likely, there is an error in your provider setup (circular dependency?) that is being mitigated by the extra injector introduced by the standalone component.

**Comment by atscott** [comment]
I'm sorry but we can't reproduce the problem following the instructions you provided.

If the problem still exists in your application please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
