### ISSUE TITLE
Angular 18 migration issue: deprecated HTTP modules

### ISSUE THREAD

**Issue by szape89** [angular/angular#56964]
### Command

update

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When running `ng update` on an Angular 17 project with [ng-mocks](https://www.npmjs.com/package/ng-mocks), end result of the "Replace deprecated HTTP modules with provider functions" step is invalid.

Before:

```
import { HttpClientModule } from '@angular/common/http';
import { HttpClientTestingModule } from '@angular/common/http/testing';
```

After:

```
import {} from '@angular/common/http';
import {} from '@angular/common/http/testing';
```

Expected result would be to have a valid result and either:
- do the changes properly;
- display a warning in the output and add comments to the code explaining why changes were not performed.

### Minimal Reproduction

Commands:
- npx @angular/cli@17 new angular-18-migration-issues
- npm i ng-mocks
- ng update @angular/core@18 @angular/cli@18

Example commit: https://github.com/szape89/angular-18-migration-issues/commit/6a697e2f6845411de19f3048e44b6a3ae55eb30c

### Your Environment

```text
Angular CLI: 18.1.0
Node: 20.15.0
Package Manager: npm 10.7.0
OS: win32 x64

Angular: 18.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1801.0
@angular-devkit/build-angular   18.1.0
@angular-devkit/core            18.1.0
@angular-devkit/schematics      18.1.0
@schematics/angular             18.1.0
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.7
```

**Comment by JeanMeche** [comment]
Thanks so much for the report and the detailed repro, this is very valuable to us. 

#56972 should fix this issue.

**Comment by fcxS** [comment]
im having this problem , it just me or something bigger?

```
cannot find module '@angular/common/http/testing' or its corresponding type declarations.

    2 import { HttpClientTestingModule } from "@angular/common/http/testing";
```

**Comment by JeanMeche** [comment]
v18 is now in LTS, we probably won't be fixing this as this schematic is not part of v19 anymore.
