### ISSUE TITLE
*ng-for is not rendering DOM but the firebase data is being called

### ISSUE THREAD

**Issue by gondar00** [angular/angular#5696]
I am getting data from firebase by using the below code and i am able to create an array using the below code.

         fetchPeopleFromFirebase(){
       Firebase fbUsers = this.fbObject.child("posts");
       fbUsers.once("value", (snapshot) => {
      if(snapshot.exists()) {
      snapshot.forEach((object) => 
      { console.log("Current Post");
          console.log(object.val());
          Firebase fbUserDetails = this.fbObject.child("users");
          var createdById = object.child('createdBy/_id').val();
          console.log("Checking for : " + createdById)
          fbUserDetails.child(createdById).once("value", (snapshot) => {
            if(snapshot.exists()) {
              console.log(snapshot.val());
            }
          });
          this.posts.push(object.val());
        });
      }
      console.log("firebase Data",this.posts);
    }
  }
I am storing the data in this.posts and i am trying to use it in the view like :

*ng-for="#post of posts"
But it does not display anything while data is being printed on the console can anyone help me?

**Comment by robwormald** [comment]
you might check out this repo from AngularConnect https://github.com/sararob/angular2base/tree/master/src

**Comment by pkozlowski-opensource** [comment]
Closing as a support question.
