### ISSUE TITLE
Need a SBOM report for Infor (GRC Product)

### ISSUE THREAD

**Issue by AdityaBhinge** [angular/angular#56966]
### Which @angular/* package(s) are the source of the bug?

animations, common, compiler, core, forms, platform-browser-dynamic, platform-browser

### Is this a regression?

Yes

### Description

Hi,

Aditya here from the Infor GRC automation team. We have been using these packages for our product, GRC (Governance Risk and Compliance), for a while now. Infor GRC has been generating SBOM reports for vulnerability scanning. Recently, we have been asked to obtain SBOM reports from third-party resources we have been using. Therefore, I request you to provide me with the SBOM reports for the packages mentioned below, along with their versions. The reports are required for these versions only and in CycloneDX JSON format.

@angular/router 17.3.3
@angular/platform-browser-dynamic 17.3.3
@angular/platform-browser 17.3.3
@angular/http 7.2.16
@angular/forms 17.3.3
@angular/core 17.3.3
@angular/compiler 17.3.3
@angular/common 17.3.3
@angular/animations 17.3.3

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

The Angular team does deliver SBOM files. You can probably generate one using tooling built on top of the NPM ecosystem.
