### ISSUE TITLE
Bug loading CSS map Files

### ISSUE THREAD

**Issue by DevEyad94** [angular/angular#56982]
### Describe the problem that you experienced

When I browse to angular.dev website it shows me an empty areas that is not renders due to failed to load the CSS map files, this what I found in console of inspect mode

```
DevTools failed to load source map: Could not parse content for https://angular.dev/icon.component.css.map: Unexpected token < in JSON at position 0
DevTools failed to load source map: Could not parse content for https://angular.dev/breadcrumb.component.css.map: Unexpected token < in JSON at position 0
DevTools failed to load source map: Could not parse content for https://angular.dev/navigation-list.component.css.map: Unexpected token < in JSON at position 0
DevTools failed to load source map: Could not parse content for https://angular.dev/docs-viewer.component.css.map: Unexpected token < in JSON at position 0
DevTools failed to load source map: Could not parse content for https://angular.dev/table-of-contents.component.css.map: Unexpected token < in JSON at position 0
DevTools failed to load source map: Could not parse content for https://angular.dev/guide/signals/cookie-popup.component.css.map: Unexpected token < in JSON at position 0
DevTools failed to load source map: Could not load content for chrome-extension://gkkdmjjodidppndkbkhhknakbeflbomf/polyfills/browser-polyfill.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for chrome-extension://ienfalfjdbdpebioblfackkekamfmbnh/app/ng_validate_bundle.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
``` 

![image](https://github.com/user-attachments/assets/c05f4adc-f6ff-4f97-83ca-87e6b1f559a0)

### Enter the URL of the topic with the problem

https://angular.dev/overview

**Comment by JeanMeche** [comment]
It's look like your running an outdated version of Chrome that isn't supported by the website. 

The sourcemaps errors are independent from what you are (not) seeing afaik.

**Comment by DevEyad94** [comment]
The chrome was outdated for a long time and I didn't received any update notification, I reinstall google chrome and now it's works fine 😄 . Thank you very much!

<img width="1792" alt="image" src="https://github.com/user-attachments/assets/30dc2a02-4333-4b91-a715-10c52e12ae80">
