### ISSUE TITLE
Missing code snippet in Documentation of AfterViewInit

### ISSUE THREAD

**Issue by Farbfetzen** [angular/angular#56985]
### Describe the problem that you experienced

The tab "Usage Notes" for AfterViewInit says "The following snippet shows how a component can implement this interface to define its own view initialization method.", yet there is no snippet to be found.

### Enter the URL of the topic with the problem

https://angular.dev/api/core/AfterViewInit?tab=usage-notes

### Describe what you were looking for in the documentation

The mentioned snippet.

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/user-attachments/assets/a09eead7-6a3b-42ae-bacb-864a6913c13b)

**Comment by JeanMeche** [comment]
Hi, this has the same root cause as #56321. I'll clause as duplicate.
