### ISSUE TITLE
docs: complete list of built-in pipes missing

### ISSUE THREAD

**Issue by meneerdaan** [angular/angular#56984]
### Describe the problem that you experienced

https://angular.dev/api/common#pipes gives a 404

### Enter the URL of the topic with the problem

https://angular.dev/api/common#pipes

### Describe the actions that led you to experience the problem

Navigating from https://angular.dev/guide/pipes#what-is-a-pipe to the link mentioned in the 'Note block'.

**Comment by JeanMeche** [comment]
Duplicate of #52968
