### ISSUE TITLE
Passing url's as params won't be parsed

### ISSUE THREAD

**Issue by wwjhu** [angular/angular#5699]
Currently when passing a url like `http://example.com/some/path?url=http://another.example.com` the
RouteParams imported in the component will have a params object with a key `url` and as value `http:` instead of the full url passed as param.

The cause of this behaviour is the regex in url_parser.ts:
```typescript
var SEGMENT_RE = RegExpWrapper.create('^[^\\/\\(\\)\\?;=&#]+');
```
Is this limitation intended behaviour?

**Comment by vicb** [comment]
related to the old router
