### ISSUE TITLE
Hydration breaks with p tag

### ISSUE THREAD

**Issue by zip-fa** [angular/angular#56990]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

Was trying to reproduce another hydration-related bug, but found this gem:

```html
<p>
    @defer (on immediate) {
      <app-test-cmp />
    } @loading {
      <p>Loading....</p>
    } @placeholder {
      <p>Loading....</p>
    }
  </p>
  ```

It breaks hydration with an error below

### Please provide a link to a minimal reproduction of the bug

https://github.com/zip-fa/ng18-defer-p-bug

### Please provide the exception or error you saw

```true
Error: NG0500: During hydration Angular expected a comment node but found <p>.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.1.0
Node: 22.4.1
Package Manager: npm 10.8.1
OS: darwin arm64

Angular: 18.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1801.0
@angular-devkit/build-angular   18.1.0
@angular-devkit/core            18.1.0
@angular-devkit/schematics      18.1.0
@schematics/angular             18.1.0
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.7
```

**Comment by diesieben07** [comment]
p-Elements must not be nested, thus when you do, the browser will un-nest them in the DOM, causing a mismatch between what Angular expects and what the browser presents in the DOM.
See here for more info: https://angular.dev/guide/hydration#valid-html-structure

**Comment by JoostK** [comment]
As @diesieben07 points out. This is being tracked in https://github.com/angular/angular/issues/56392
