### ISSUE TITLE
Capture HTTP request which starts the application

### ISSUE THREAD

**Issue by JanStureNielsen** [angular/angular#57001]
### Which @angular/* package(s) are relevant/related to the feature request?

platform-browser, router

### Description

In browser-based Angular applications, there is an "initializing (HTTP) request" which triggers the start of the Angular application. In some (most?) distributed systems applications, the initializing request includes authorization information, e.g., one-time service token, which enable a single-sign-on (SSO) experience across the integrated distributed applications. Unfortunately, the initializing request is not available to Angular applications which forces a sign-in for protected resources/routes. If the initializing request was available to Angular applications, then the initializing request's authorization information could be used to create a SSO experience.

For example, imagine in a dedicated IAS application which authenticates the user and generates service authorization tokens:

    example.org/identity/authenticate

and a protected CRM application implemented in Angular with a deep-link to a customer:

    example.org/customers/1234/invoices/2345

Since `/customers/` is a protected resource, the Angular authentication guard redirects to `/identity/authenticate` unless the CRM application has access to the IAS generated service token. For a deep-link like `/customers/1234/invoices/2345` the initial request to the Angular application will start the application but the Angular application won't have access to the initializing request which means it will redirect to `/identiy/authenticate`.

URL parameters are available to the Angular application in the authentication guard, so it's possible to include a one-time service token in a parameter but this is not a nice user experience with the token in the browser's address history and is only reasonable/secure for one-time service tokens.

### Proposed solution

Capture the initializing request and provide an API for it.

### Alternatives considered

URL parameters are available to the Angular application in the authentication guard, so it's possible to include a one-time service token in a parameter but this is not a nice user experience with the token in the browser's address history and is only reasonable/secure for one-time service tokens.

**Comment by JeanMeche** [comment]
Hi, 

Isn't this something that could be achieve by this pattern : 

```
const INITIAL_URL_TOKEN = new InjectionToken('');

bootstrapApplication(App, {
  providers: [
    {
      provide: INITIAL_URL_TOKEN,
      useValue: window.location.href,
    },
  ],
});
```

**Comment by JanStureNielsen** [comment]
@JeanMeche -- I don't understand how that would work. Inbound it does not appear possible to see the headers associated with `window.location.href`; and, I don't think it's possible to set the headers in the outbound browser redirect triggered via `window.location.href`. Can you provide a bit more context about this might work?

**Comment by JoostK** [comment]
Angular, at least on the client side, does not have any insight into the request that hit the server (and returned the HTML response that ended up bootstrapping an Angular application). If Angular is used on the server as well then something like this may be possible if angular/angular-cli#26323 has been resolved (see also [the related RFC](https://github.com/angular/angular/discussions/56785))
