### ISSUE TITLE
 Support for Opening URLs in New Tab with State in Angular Router

### ISSUE THREAD

**Issue by hirebirhan** [angular/angular#57019]
### Which @angular/* package(s) are relevant/related to the feature request?

common

### Description

I would like to request a feature enhancement for Angular's Router to support opening URLs in a new tab while passing state data. Currently, the Angular Router allows navigation with state using the navigate method, but this does not support opening the URL in a new tab.
`this.router.navigate(['/order/create'], { state: { orderDetails } });`

### Proposed solution

Enhance the Angular Router to support opening URLs in a new tab with state. This could be implemented by adding a new option to the navigate method or providing a new method specifically for this purpose.
`this.router.navigate(['/order/create'], { state: { orderDetails }, openInNewTab: true });
`

### Alternatives considered

Currently, developers have to rely on workarounds such as using sessionStorage, localStorage, or query parameters to pass state data, which can be less secure and less convenient.

**Comment by atscott** [comment]
Right, the `state` is stored on `history` which isn't carried over when opening a link to a new tab. The mentioned "workarounds" (storage or queryParams) _are_ the options.
