### ISSUE TITLE
TypeError: Cannot set property 'nodeValue' of undefined 

### ISSUE THREAD

**Issue by ami1708** [angular/angular#57015]
### Which @angular/* package(s) are the source of the bug?

elements

### Is this a regression?

Yes

### Description

I am using Angular with webcomponents

getting following error on $apply 
/ajax/libs/angularjs/1.2.27/angular.min.js in Object.fn at line 62:268

Unminify Code
In App
/ajax/libs/angularjs/1.2.27/angular.min.js in h.$digest at line 110:373

Unminify Code
In App
/ajax/libs/angularjs/1.2.27/angular.min.js in h.$apply at line 113:362

Unminify Code
In App
/ajax/libs/angularjs/1.2.27/angular.min.js in m at line 72:454

Unminify Code
In App
/ajax/libs/angularjs/1.2.27/angular.min.js in w at line 77:463

Unminify Code
In App
/ajax/libs/angularjs/1.2.27/angular.min.js in B.onreadystatechange at line 79:24

### Please provide a link to a minimal reproduction of the bug

https://instahyre.sentry.io/issues/4798320953/?project=5230540&referrer=phabricator_plugin

### Please provide the exception or error you saw

```true
its happening on the android devices 10
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
angularjs/1.2.27/angular
```

### Anything else?

nope

**Comment by JoostK** [comment]
This is the repository for Angular, not [angular.js](https://github.com/angular/angular.js). angular.js is no longer supported.
