### ISSUE TITLE
Angular 1.X router  and Typescript

### ISSUE THREAD

**Issue by satish860** [angular/angular#5701]
I am trying to use angular router in my new project with the Typescript. I am not able to load it with the module(JSPM) .

Also is there any Typing file for the router  . If not I would like to contribute the same . 

1)  Angular 1_x router trying to load Angular 2
var angular2_1 = require('angular2/angular2');  in 1787 line . Is there any need for the same .

Also can we expect the router for 1.5.x release (Not Pushing) .

**Comment by tolemac** [comment]
+1

**Comment by vicb** [comment]
obsolete
