### ISSUE TITLE
API abort error occurs specifically when rendering the page in Mozilla Firefox

### ISSUE THREAD

**Issue by mikitashauchenka** [angular/angular#57013]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

![image](https://github.com/user-attachments/assets/befabbe1-95c8-40f9-a171-6416ce2eca9d)

We are experiencing API request abort errors in Mozilla Firefox. 
However, these errors do not appear in Google Chrome. 
What steps should we take to resolve this issue?

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.7
Node: 21.7.1
```

**Comment by JeanMeche** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).
