### ISSUE TITLE
The inherited component cannot be fully destroyed.

### ISSUE THREAD

**Issue by techlandicon** [angular/angular#57014]
### Which @angular/* package(s) are the source of the bug?

common, elements

### Is this a regression?

No

### Description

I have the following code, and I found that after DialogPage is destroyed, BaseDialogPage can still be seen in the memory viewer.

https://stackblitz.com/edit/stackblitz-starters-zwqcgk?file=src%2Fapp%2Fbasedialog.page.ts

My operation steps:
1. Refresh the page and record the first snapshot "Snapshot1" on Page1.
2. Click "Open Dialog", wait for the Dialog to disappear, and record the second snapshot "Snapshot2" after it disappears.
3. Switch to Page2. Record the third snapshot.
When comparing the third snapshot with the first snapshot "Snapshot3", it is found that BaseDialogPage is not destroyed. DialogPage is destroyed.
![image](https://github.com/user-attachments/assets/0fb2d844-31b9-404a-84ec-0d7ea08cf0c4)
![image](https://github.com/user-attachments/assets/ab6eace8-f7d2-46d6-b144-8f5bf3772f72)
![image](https://github.com/user-attachments/assets/bc1c199c-9863-407a-b831-f4956cdcc415)

**Comment by JeanMeche** [comment]
This is due to the way of how javascript classes work. 
When you declare 

```
class Foo {}
class Bar extends Foo {}
```

`Foo.prototype` is an instance of the parent class. 

This can be demoed with : 

```
class Foo {}
class Bar extends Foo {}
Bar.prototype instanceof Foo // true
```
