### ISSUE TITLE
The inherited component cannot be fully destroyed.

### ISSUE THREAD

**Issue by techlandicon** [angular/angular#57011]
### Which @angular/* package(s) are the source of the bug?

common, elements

### Is this a regression?

Yes

### Description

I have the following code, and I found that after DialogPage is destroyed, BaseDialogPage can still be seen in the memory viewer.

//baseDialog.ts
import { Component, OnInit, OnDestroy } from '@angular/core';

@Component({
  template: '',
  standalone: true
})
export class BaseDialogPage implements OnInit, OnDestroy {

  constructor() { }

  ngOnInit() {
    console.log("BaseDialogPage initialized");
  }

  ngOnDestroy() {
    console.log("BaseDialogPage destroyed");
  }

  showMsg() {
    console.log("show error");
  }
}

//dialog.page.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { BaseDialogPage } from 'src/app/base/basedialog';

@Component({
  template: '<p>Dialog Page Content</p>',
  standalone: true
})
export class DialogPage extends BaseDialogPage implements OnInit, OnDestroy {

  constructor() {
    super();
  }

  override ngOnInit() {
    super.ngOnInit();
    this.showMsg();
  }

  override ngOnDestroy() {
    super.ngOnDestroy();
    console.log("DialogPage destroyed");
  }
}

//page1.page.ts
import { Component, OnInit, ViewChild, ViewContainerRef, OnDestroy, ComponentRef } from '@angular/core';

@Component({
  template: `
    <button (click)="onClick()">Open Dialog</button>
    <ng-container #childrenanchor></ng-container>
  `,
  standalone: true
})
export class Page1Page implements OnInit, OnDestroy {
  @ViewChild('childrenanchor', { read: ViewContainerRef }) childrenanchor: ViewContainerRef | undefined;
  private timeoutId: any;
  private componentRef: ComponentRef<any> | undefined;

  constructor() { }

  ngOnInit() { }

  ngOnDestroy() {
    if (this.timeoutId) {
      clearTimeout(this.timeoutId);
    }
    if (this.componentRef) {
      this.componentRef.destroy();
    }
  }

  async onClick() {
    const { DialogPage } = await import('src/app/page/dialog/dialog.page');

    if (this.childrenanchor != undefined) {
      this.childrenanchor.clear();
      this.componentRef = this.childrenanchor.createComponent(DialogPage);

      if (this.childrenanchor != undefined) {
        this.timeoutId = setTimeout(() => {
         
          if (this.componentRef) {
            this.componentRef.destroy();
          }
          this.childrenanchor?.clear();
        }, 5000);
      }
    }
  }
}

![image](https://github.com/user-attachments/assets/f608623a-624d-44aa-b3de-9b86ca8b6fac)

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: @18.1.0
Node: 18.20.4
OS:Windows
```

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
