### ISSUE TITLE
numberAttribute transform is not working when passing null

### ISSUE THREAD

**Issue by dfernandez-elastic** [angular/angular#57017]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

When passing null to an `@Input` with **numberAttribute** transform, the value gets transformed to `NaN`, leading to unexpected behavior.

We have some use cases when we need to pass props conditionally. The most recommended way to pass props conditionally is [like this](https://stackoverflow.com/a/36745752) (passing null, basically)

So later, when using PrimeNG components, some conditions are failing. [This is the logic ](https://github.com/primefaces/primeng/blob/e142de683b9cbcf2342774e9390ee09b0934580f/src/app/components/utils/objectutils.ts#L156-L158)to validate that a value is empty in PrimeNG.

Below, I'm passing a link to a demo where I'm mimicking the PrimeNG behaviour and you will see that it's not behaving like expected.

The value should be empty when passing undefined or null.

### Please provide a link to a minimal reproduction of the bug

[CodeSanbox Reproduction](https://codesandbox.io/p/devbox/flamboyant-scooby-7dwpd6?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clypqot4e00062e6apmax8uv4%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clypqot4e00022e6aggcomn95%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clypqot4e00042e6az82cvu5o%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clypqot4e00052e6an6bimig8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clypqot4e00022e6aggcomn95%2522%253A%257B%2522id%2522%253A%2522clypqot4e00022e6aggcomn95%2522%252C%2522activeTabId%2522%253A%2522clypqqdek005v2e6a7qibjtkq%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clypqot4e00012e6asr4fm9z3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fapp%252Fapp.component.ts%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A5%252C%2522endLineNumber%2522%253A5%252C%2522startColumn%2522%253A16%252C%2522endColumn%2522%253A16%257D%255D%252C%2522id%2522%253A%2522clypqqdek005v2e6a7qibjtkq%2522%252C%2522mode%2522%253A%2522temporary%2522%257D%255D%257D%252C%2522clypqot4e00052e6an6bimig8%2522%253A%257B%2522id%2522%253A%2522clypqot4e00052e6an6bimig8%2522%252C%2522activeTabId%2522%253A%2522clypqt1zs00f02e6ai7aexlk9%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A4200%252C%2522id%2522%253A%2522clypqt1zs00f02e6ai7aexlk9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clypqot4e00042e6az82cvu5o%2522%253A%257B%2522id%2522%253A%2522clypqot4e00042e6az82cvu5o%2522%252C%2522activeTabId%2522%253A%2522clypqpmoy00332e6atb4hnhgp%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clypqot4e00032e6antbnhlpq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%252C%257B%2522id%2522%253A%2522clypqpmoy00332e6atb4hnhgp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clypqpmsd00c5dalxb7a2hbw6%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Please provide the exception or error you saw

```true
No exception
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.0
Node: 20.9.0
Package Manager: npm 9.8.1
OS: linux x64

Angular: 17.3.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.0
@angular-devkit/build-angular   17.3.0
@angular-devkit/core            17.3.0
@angular-devkit/schematics      17.3.0
@schematics/angular             17.3.0
rxjs                            7.8.1
typescript                      5.4.2
zone.js                         0.14.4
```

**Comment by JeanMeche** [comment]
This is the expected behavior. 

https://github.com/angular/angular/blob/982f1b125147e4292716f9524bef75423b70c71c/packages/core/test/util/coercion_spec.ts#L57-L66

**Comment by dfernandez-elastic** [comment]
Hi @JeanMeche so, how can I pass props conditionally when having this `numberAttribute` transform?

**Comment by JeanMeche** [comment]
You should write your own coerceNumber function that returns something else when null/undefined is returned.
