### ISSUE TITLE
Styles not being applied to custom component selectors

### ISSUE THREAD

**Issue by LanceEa** [angular/angular#5702]
I'm running into an issue with applying styles to custom elements. I'm not sure if it is a bug or my lack of understanding. I have a simple component called `<my-cmp></my-cmp>` which I want to apply styles to it as part of the component definition. 

Here is an example of my components and what I'm trying to do.
```typescript
import {Component, CORE_DIRECTIVES} from 'angular2/angular2'

@Component({
  selector: "my-cmp",
  template: `
    <ng-content></ng-content>
  `,
  styles: [`
    my-list {
      display: block;
      border: 1px solid black;
      min-height: 200px;
    }
  `]
})
export class MyCmp {}

@Component({
  selector: 'my-app',
  template: `
      <h2>Angular 2 Styles Issue?</h2>
      <my-cmp>
        <p>Why are style's not being applied to custom component selector "my-list"?</p>
      </my-cmp>
  `,
  directives: [CORE_DIRECTIVES, MyCmp]
})
export class App {}
```

I would expect the outputted html to look something like this with the styles applying directly to the my-cmp. MyComponent should have a border around it but nothing is applied to it.

```html
<my-app>
  <my-cmp>
        <p>Why are style's not being applied to custom component selector "my-list"?</p>
  </my-list>
</my-cmp>
```

Here is a plunker demonstrating this example.
http://plnkr.co/edit/w6EYcxLDsLaXXjhdHDh0

**Comment by zoechi** [comment]
I guess this is what you want:

```ts
@Component({
  selector: "my-cmp",
  template: `
    <ng-content></ng-content>
  `,
  styles: [`
    :host {
      display: block;
      border: 1px solid black;
      min-height: 200px;
    }
  `]
})
export class MyCmp {}
```

**Comment by LanceEa** [comment]
@zoechi - Thanks for the help. I figured I was missing something here and it probably had to do with my lack of understanding of the Shadow Dom. I was able to make the change as you suggested and it works as I would have expected.

@wardbell @PascalPrecht  - I know that the two of you are hard at work on documentation (Much appreciated btw). Is the above something that you guys have seen others challenged with and do you think it might be worth adding something to the documentation? I'm guessing there will be others like me that are new to Shadow Dom and might benefit from some guidance\best practices when starting out with styling Angular 2 Components. Thoughts?

**Comment by LanceEa** [comment]
Closing since this doesn't seem to be an issue and works as shadow dom is intended to work.
