### ISSUE TITLE
new Lifecycle hook ngOnServer

### ISSUE THREAD

**Issue by wiedenmannk** [angular/angular#57041]
### Description

I love SSR in Angular and ther is something nice with TransferState. But you have always inject PlatformID and if you fetch data from server in your service / component then your service runs async faster than your component starts. So what happen? You fetch your data twice. The Transferstate got your Key for the client to late. 

### Proposed solution

So may something like a hook ngOnServer would be nice to make calls only for server with no need for inject PlatformID. So you could use afterRender to catch the key for client. For the moment you have to split my transferService and first catchup an Observable which is waiting for the key.

### Alternatives considered

may the TransferState itself could already check himself and use a Observable and wait for JSON on client. The AfterContentInit lifecycle not register the JSON Data script id="ng-state" and StateKey. May a new hook for components like JSONDataready would be really nice.

**Comment by alan-agius4** [comment]
Closing as no further information has been provided.
