### ISSUE TITLE
ng-content Projection with e-columns Directives Not Working with our own Angular grid component

### ISSUE THREAD

**Issue by SathishKumarRajendran** [angular/angular#57055]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I'm facing an issue with our custom Angular grid library where ng-content projection with e-columns directives is not working as expected. Specifically, the child directives are not being fetched correctly when using ng-content in a separate component. I have getting undefined value from the childColumns and it doesn’t query the directives values.

**Grid Component Source:**

**// grid.component.ts**

```import { ColumnsDirective } from './columns.directive';

@Component({
  selector: 'ejs-grid',
  inputs: inputs,
  outputs: outputs,
  template: '',
  changeDetection: ChangeDetectionStrategy.OnPush,
  queries: {
    childColumns: new ContentChild(ColumnsDirective),
  }
})
@ComponentMixins([ComponentBase])
export class GridComponent extends Grid implements IComponentBase {
  public childColumns: QueryList<ColumnsDirective>;
  public childAggregates: QueryList<AggregatesDirective>;

public ngAfterContentChecked(): void {
        this.tagObjects[0].instance = this.childColumns;
        this.context.ngAfterContentChecked(this);
    }
}

**// columns.directive.ts**

@Directive({
  selector: 'ejs-grid>e-columns>e-column',
  inputs: input,
  outputs: outputs,
  queries: {
    childColumns: new ContentChild(StackedColumnsDirective)
  }
})
export class ColumnDirective extends ComplexBase<ColumnDirective> {
  // properties
}

@Directive({
  selector: 'ejs-grid>e-columns',
  queries: {
    children: new ContentChildren(ColumnDirective)
  }
})
export class ColumnsDirective extends ArrayBase<ColumnsDirective> {

}
```

**Sample Code to Reproduce:**
```
// parent.component.ts

import { Component, OnInit } from '@angular/core';
import { stringData } from './data'; // Assume data is imported from a data source
import { DataService } from './data.service';

@Component({
  selector: 'app-parent',
  template: `
    <app-reusable-grid [data]="data">
      <e-columns>
        <e-column field='OrderID' headerText='Order ID' textAlign='Right' width=90></e-column>
        <e-column field='EmployeeID' headerText='Employee ID' textAlign='Right' width=80></e-column>
        <e-column field='ShipCity' headerText='Ship City' width=100></e-column>
        <e-column field='ShipName' headerText='Ship Name' width=120 visible='false'></e-column>
      </e-columns>
    </app-reusable-grid>
  `
})
export class ParentComponent implements OnInit {
  public data?: any;
  
  constructor(private dataService: DataService) {}

  ngOnInit(): void {
    this.dataService.getData().subscribe({
      next: (response) => {
        this.data = response;
        console.log(this.data);
      },
      error: (err) => {
        console.error('Error fetching data', err);
      }
    });
  }
}

// reusable-grid.component.ts

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-reusable-grid',
  template: `
    <ejs-grid [dataSource]="data">
      <ng-content></ng-content>
    </ejs-grid>
  `
})
export class ReusableGridComponent {
  @Input() data?: any[];
}
```
**Issue:**

When using e-columns directives directly in the ejs-grid tag, the child directives are fetched correctly. However, when passing e-columns through a separate component using ng-content, the child directives are not fetched in the grid.component.ts file.

**Expected Behavior:**

The child directives should be fetched correctly in the grid.component.ts file, regardless of whether e-columns are used directly in the ejs-grid tag or passed through ng-content.

**Actual Behavior:**

The child directives are not being fetched when e-columns are passed through ng-content in a separate component.

**Possible Solution:**

If you have any ideas for a potential fix, you can suggest them here.

### Minimal Reproduction

**Steps to Reproduce:**

1. Run the attached [sample](https://drive.google.com/file/d/19yDSLzTxXf6OyvMghMkkyZGESzKshTIK/view),
2. Debugg the our angular grid component source,
3. In the grid component source, you can't get the childColumns value in the ngAfterContentChecked() hook.

### Your Environment

```text
Angular CLI: 16.0.6
Node: 16.14.1
Package Manager: npm 8.5.0
OS: win32 x64

Angular: 16.2.12
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.14
@angular-devkit/build-angular   16.2.14
@angular-devkit/core            16.2.14
@angular-devkit/schematics      16.0.6
@angular/cli                    16.0.6
@schematics/angular             16.0.6
rxjs                            7.8.1
typescript                      5.0.4
```

**Comment by garrettld** [comment]
This is a pretty complex example, but I think it boils down to nested content projection. In short, projected content can only be queried at the first level of projection, which is why your ContentChildren queries aren't finding anything when using your ReusableGridComponent.

see:
https://github.com/angular/angular/issues/16299
https://github.com/angular/angular/issues/49679

**Comment by JeanMeche** [comment]
Like Garrett explained this is a known limitation that is already tracked

**Comment by sergidt** [comment]
That is a common solution when dealing with very large enterprise applications, with many developers: encapsulating the common logic (pagination, sort, columns management, ...) in a component and use this component in every table view, only projecting required columns from the outside. 

Is basic to have good code (Don't Repeat Yourself principle), to be more productive and, the most important, reducing bugs, since the common behaviour is coded once in this common component. 

I have been using angular material for a long time and it is possible with this component kit, in my former project we were creating tables following this approach. 

Maybe another approaches are better that this one, (injectable services, host directives, ...), I only say this is possible.
