### ISSUE TITLE
Mechanism for control the CSS classes applied to its own selector

### ISSUE THREAD

**Issue by pcroc** [angular/angular#5705]
```typescript
@Component({
  selector: 'list-item'
})
export class ListItem {
}
```

I want a way for ListItem to control which CSS classes are applied to the `<list-item>` element itself. The list of classes to apply might be static or dynamic.

**Comment by ericmartinezr** [comment]
```
@Component({
  selector: 'list-item', 
  host : {
    '[class.myClass]' : 'myExpression'
  }
})
class MyClass {
   constructor() {
       this.myExpression = true;
   }
}
```

**Comment by ericmartinezr** [comment]
Hey @pcroc you can do it already using `host` and style (with the latter one is styling directly, not using classes)

```typescript
@Component({
  selector: 'list-item',
  // Option 1
  host : {
     '[class.my-class]' : 'myExpr'
  },
  // Option 2
  styles : [`
     :host {
        /* styles */
      }
  `]
})
export class ListItem {
   constructor() {
      this.myExpr = true;
   }
}
```

**Comment by LanceEa** [comment]
I actually just logged an issue for the same problem earlier this morning #5702. It appears to be just my personal lack of understanding of shadow-dom rather than a real issue. I think there might an opportunity for documentation to fill the gap/help provide people new to shadow-dom some guidance here.

**Comment by hokkaido** [comment]
I think this is a bit convoluted, or not? Doesn't a HostBinding actually register a listener?

**Comment by pkozlowski-opensource** [comment]
> Creating a private field just so that I can pre-define a css class isn't exactly elegant.

You don't have to create any fields for static values, this should do the trick:

```javascript
host : {
     '[class.my-class]' : 'true'
  },
```

Or this if you want to add multiple classes:

```javascript
host : {
     'class' : 'my-class other and-yet-another'
  },
```

Going to close this one as I think we are covered. If anyone has a specific use-case that you think is not covered, please open a separate issue with a reproduce scenario using plunker or similar.
