### ISSUE TITLE
Resolver function with SSR executed twice, on server and on client

### ISSUE THREAD

**Issue by mmart1n** [angular/angular#57068]
### Command

other

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

In an Angular project with SSR enabled and client hydration provided, I use a resolver function to fetch some data (titles, metadata, breadcrumbs, etc.). To show a progress indicator, I listen for the router events of type ResolverStart and ResolverEnd only on the client while this data is being fetched.

Scenario 1: When the page is requested from the app, everything works as expected -> ResolverStart is raised -> a request is sent to the backend and once completed -> ResolverEnd is raised.

Secenario 2: The problem occurs when the URL of the page is entered in the browser (or when refreshing the page) and the server has to render the page. The server actually manages to call the resolver function, fetch the data and send it to the client. However, as soon as the application starts, the entire chain repeats itself -> ResolverStart is raised -> Resolver function is executed -> ResolverEnd is raised. The only difference is that in this scenario the resolver function does not actually send a request to the Beckend, but uses the hydrated data.

This seems unnecessary as the users are already waiting while the server fetches the data from the backend, and I expect them to be shown the entire page and not the loading spinner for a fraction of a second that makes the page flicker.

I believe that the resolver function in scenario 2 should only be executed on the server and the ResolverStart and ResolverEnd should not be triggered on the client. What are your thoughts on this?

### Minimal Reproduction

1. Add resolver function to any route which calls an http get request.
2. Subscribe to the router events in order to show loading indicator between RosolverStart and ResolverEnd events only on the client
```
constructor() {
    afterNextRender(() => {
        this.isLoading$ = this.#router.events.pipe(
            filter((e) => e instanceof ResolveStart || e instanceof ResolveEnd),
            tap((e) => {
                console.log(e instanceof ResolveStart)
            }),
            map((e) => e instanceof ResolveStart)
        );
    });
}
```

### Your Environment

```text
18.0.6
```

**Comment by JeanMeche** [comment]
If you see the spinner, it is likely that server is sender HTML without the content. 
You reproduction steps aren't enough for us to investigate exactly what's happening. 

Could you please provide a working repro, either as a stackblitz or a github repo ? Thank you.

**Comment by mmart1n** [comment]
> If you see the spinner, it is likely that server is sender HTML without the content. You reproduction steps aren't enough for us to investigate exactly what's happening.
> 
> Could you please provide a working repro, either as a stackblitz or a github repo ? Thank you.

Hi, [here](https://github.com/mmart1n/ng-ssr-resolver) you can find a repo, which reproduces the issue. After further investigation, I managed to spot what was causing the spinner to be shown -> it is a delay operator, I've added in order to test something (you can check app.routes.ts). Still not sure if the resolver function should be called on the client, when it has been already called on the server.

PS. I noticed that if only <router-outlet> is placed within @if block, it would behave strange (check app.component.html). I couldn't find anything in the offical docs regarding @if blocks with router-outlet only

**Comment by JeanMeche** [comment]
Hydration caches request at the level of the HttpClient. An interceptor catches the request, checks the transfer cache to return the cached content. 

If you delay after the reponse is returned (what you are doing with this `delay(1000)`), they you have the issue your project is exhibiting.

**Comment by mmart1n** [comment]
> Hydration caches request at the level of the HttpClient. An interceptor catches the request, checks the transfer cache to return the cached content.
> 
> If you delay after the reponse is returned (what you are doing with this `delay(1000)`), they you have the issue your project is exhibiting.

Thank you very much for your feedback! I have changed the repo so that I now send a request to an endpoint that always throws an error. As you can see, there are 2 issues:
1. after the server tries to fetch the data and the error occurs (my logic is to navigate to the homepage), it correctly sends the HTML code of the homepage to the client, but the loading indicator became visible again for a while. It seems that when an error occurs, the error is not hydrated to the client and the request is sent again.
2. when trying to navigate to "/resolver" from the client via the link, the ResolveEnd event is never raised and the loading indicator remains visible forever.

PS. Is there any documentation regarding my question about <router-outlet> within @if block?

**Comment by JeanMeche** [comment]
Any particular reason why you're not using a guard to redirect ? 
Unsuccessful requests aren't stored in the cache, they will run again on the client. 

I'm not sure I understand the question the `@if`, why do you need a conditionnal `router-outlet` ?

**Comment by mmart1n** [comment]
> Any particular reason why you're not using a guard to redirect ? Unsuccessful requests aren't stored in the cache, they will run again on the client.
> 
> I'm not sure I understand the question the `@if`, why do you need a conditionnal `router-outlet` ?

I thought that one of the purposes of the resolver function is to resolve something before either rendering the page or doing something else, in my case navigating to different page. Even one of the Google Angular Developer Experts is showing [this approach](https://youtu.be/BLLO2x7_R5M?si=q14sKtQf_ODvrCkA) in one of his tutorials. 

In regards to the conditional <router-outlet> we have the requirement to display a custom spinner over the entire page, except for the navbar and the footer. When the router-outlet is placed within a div, everything works as expected. If this is not advisable approach, I can think of at least few workarounds, just I couldn't find anything in the documentation why not to put router-outlet in conditional blocks.

**Comment by JeanMeche** [comment]
Ideally, a resolver should not navigate itself but return a `RedirectCommand`, this is possible since v18.0.

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by mmart1n** [comment]
> Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.
> 
> If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

Nevertheless, I believe that if a possibility to redirect is provided by a resolver function (you can check this [issue](https://github.com/angular/angular/issues/29089)), it is redundant to run this resolver function on both the server and the client. For example, if the user requests a URL and the server decides to redirect to another page, it sends the code of the page it redirected to, the user sees everything as it should be, but in the background the logic of the resolver is executed again. And yes, I know I can take advantage of `isPlatformBrowser` and `isPlatformserver`, but if some logic depends on the resolver events, it would still be executed unnecessarily. At least it would be nice if we as developers could give the resolver functions a configuration option of where to run (server/client/both).

I just wanted to give you some feedback on this scenario and see if this is being considered as a way to improve the framework.
Anyway, thanks for the quick replays and nice job with the recent updates!
