### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by NabilNaou** [angular/angular#57067]
### Describe the problem that you experienced

https://angular.dev/guide/experimental/zoneless this page contains a dead link at the following part:

> One way to ensure that a component is using the correct notification mechanisms from above is to use [ChangeDetectionStrategy.OnPush](https://angular.dev/best-practices/skipping-subtrees#using-onpush).

Thats all :) very small issue.

### Enter the URL of the topic with the problem

https://angular.dev/guide/experimental/zoneless

### Describe what you were looking for in the documentation

onpush links.

### Describe the actions that led you to experience the problem

click link.

### Describe what you want to experience that would fix the problem

link works.

**Comment by adxdits** [comment]
Hello, I'd like to work on this issue.

**Comment by adxdits** [comment]
https://angular.dev/best-practices/skipping-subtrees#using-onpush  this is the link you should have when you click on it i don't have access to the angular website html file to fix i in the website.

**Comment by JeanMeche** [comment]
https://github.com/angular/angular/blob/38e4802c7f5f4bbb46d127dc7fb938aa7be429c6/adev/src/content/guide/zoneless.md?plain=1#L44

The url should be relative to the parent.
