### ISSUE TITLE
Template Syntax: support `+=`, `-=` 

### ISSUE THREAD

**Issue by wardbell** [angular/angular#5706]
These shorthand operators are especially useful in event binding template expressions. @vsavkin opines that they belong and should be easy to add.

**Comment by vicb** [comment]
`!=` is not an assignment operator and is already supported

**Comment by IgorMinar** [comment]
I'm not a fan. Imperative code should be in js/ts/dart not in templates.

In Angular 1 we allowed way too many things in the templates and then we saw people abuse it left and right.

If we allow this, we should have a proper discussion and I'd like to be part of it.

**Comment by wardbell** [comment]
I don't disagree. But we already support a lot of JS syntax ... including assignment. It's hard to explain why this one isn't OK but `a=..`, `!a`, `a || b`, `(a || b) && c`, etc ... are all legit.

In my case I just wanted to keep catenating to a string property when the user clicked: `clicks+='Click!'` in a demo.  If you deny me the pleasure of `+=`, I already have ...
```
(my-click)="clicked = (clicked || '') + ' Click!'"
```

but that's so ho-hum.

Is this bad form? Sure. But no worse than what we already support.

**Comment by wardbell** [comment]
@vicb  ... what can I say about `!=`? I'm an idiot? That's a C#-sim haunting me.

**Comment by IgorMinar** [comment]
I cringe at the fact that we already support assignment (`=`), all the other operators are idempotent, which in my view of the world makes them suitable for template bindings.

**Comment by wardbell** [comment]
I'd support removing assignment (which, btw, is only allowed in event bindings). Then we could put a stop to other mutators as welll (push, x++, ...)

It's a losing battle. Might as well forestall the inevitable questions about why this is OK but that isn't.

**Comment by thelgevold** [comment]
My experience from the field is that inlined script snippets in templates are abused way too often. I can't think of a scenario where you can't solve this with a backing model field/function. Maybe this is the time to lay down the law and remove support :-). It would be an automatic win for code quality!

**Comment by wardbell** [comment]
Not disagreeing. I just say "do it or don't". We're half pregnant at the moment

**Comment by vicb** [comment]
If we support `+=` et `-=` it would also probably makes sense to support other [assignment operators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Assignment_Operators). May be not all but at least `*=, \=, %=`

**Comment by pkozlowski-opensource** [comment]
Given the discussion above let's skip support for the mentioned operators for now. We can always revisit in the future if people got very strong arguments / use-cases.
