### ISSUE TITLE
Max Call Stack error with large template

### ISSUE THREAD

**Issue by Nabelops** [angular/angular#57066]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

When upgrading from v17 to v18, our components with large svg templates with template bindings failed to load with a `RangeError: Maximum call stack size exceeded`.  We were able to get rid of this error by reducing the size of the template.  I have created a stackblitz that shows this the same template (a random svg seating chart I found online) works on v17 and not on v18.

Working v17
https://stackblitz.com/edit/angular-17-starter-project-xnu5ts?file=src%2Fmain.ts

The link to the minimal reproduction of the bug will be the identical setup but with v18.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-by85ky?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
RangeError: Maximum call stack size exceeded
    at executeTemplate (core.mjs:11264:5)
    at renderView (core.mjs:12426:7)
    at renderComponent (core.mjs:12372:3)
    at renderChildComponents (core.mjs:12472:5)
    at renderView (core.mjs:12454:7)
    at createAndRenderEmbeddedLView (core.mjs:12493:5)
    at TemplateRef2.createEmbeddedViewImpl (core.mjs:13419:27)
    at ViewContainerRef2.createEmbeddedView (core.mjs:16880:33)
```

**Comment by JoostK** [comment]
The v18 StackBlitz works fine for me, using Chrome in StackBlitz.

**Comment by Nabelops** [comment]
> The v18 StackBlitz works fine for me, using Chrome in StackBlitz.

Yeah it is working for me too now.  I will work on a better reproduction.

**Comment by Nabelops** [comment]
I have updated the links to use.  They are using a more complex svg now.  https://commons.wikimedia.org/wiki/File:European_Parliament_Strasbourg_seating_chart.svg

**Comment by JoostK** [comment]
Interesting, that overflows TS's stack during emit.

You can break the cycle by inserting `<ng-container></ng-container>` halfway the SVG as a workaround.

**Comment by Nabelops** [comment]
> Interesting, that overflows TS's stack during emit.
> 
> You can reduce the stack depth by inserting `<ng-container></ng-container>` halfway the SVG as a workaround.

Interesting, if I remember correctly, ng container used to not work in svgs

**Comment by Nabelops** [comment]
> Interesting, that overflows TS's stack during emit.
> 
> You can reduce the stack depth by inserting `<ng-container></ng-container>` halfway the SVG as a workaround.

Just reporting back that this does indeed fix the issue we had.  Random `<ng-container></ng-container>` in the svg.

**Comment by JoostK** [comment]
I opened #57069 to limit the chaining depth. The diff is small so you may be able to patch it in locally to see if it resolves the issue without needing the `ng-container` elements.
