### ISSUE TITLE
Allow for router resolvers to block route matching

### ISSUE THREAD

**Issue by johnameyer** [angular/angular#57071]
### Which @angular/* package(s) are relevant/related to the feature request?

router

### Description

A very common paradigm in Angular is to expose a route taking an id and then using that route data to get additional data from some source inside the component. ([Even the old v17 Tour of Heroes application used this pattern](https://v17.angular.io/tutorial/tour-of-heroes/toh-pt6#herodetailcomponent).) The responsibility falls on the component to handle making this call and handling not found exceptions (which increases the responsibility of the component), e.g.

```
  details: Details | undefined;
  
  @Input()
  set slug(slug: string) {
    this.details = detailService.get(slug);
  }
```

Instead, it would be ideal to treat these all as resolvers executed by the router and push the resolution and not-found logic up a level - namely by only allowing the route to match if the value could be resolved and otherwise falling back on the not-found component.

The minor issue today is that the matchers and resolvers are fully divorced - `CanMatchFn`s take in the route configuration and the url segments (and cannot inject the activated route since the route has not been activated) while `ResolveFn`s have access to the full activated route but cannot influence the route being matched. As such, we have to write our logic twice - get the data and check if it is present as a match guard and get the data and set it as data field as a resolver. Especially for simple applications, it would be ideal to only need to do this in one place (e.g. to prevent needing to cache data between the two calls to a service).

### Proposed solution

The only solution I can wrap my head around with the current framework would be to allow resolvers to return some placeholder symbol `DenyMatch` that would indicate to the router to prevent matching (much like how redirect commands can be returned). However, this solution likely has some deeper implications as the route is already activated at this point.

```
  {
    path: ':slug',
    component: DetailViewComponent,
    resolve: {
      details: (route: ActivatedRouteSnapshot, state: RouterStateSnapshot) => 
        detailService.get(route.params['slug']) ?? DenyMatch,
    }
  },
  {
    path: '**',
    component: NotFoundComponent,
  }

### Alternatives considered

It may also be possible to resolve structure this use case by resolving data in a parent route, but this approach doesn't work currently as each (child) component would still need to have a path defined and the matcher still cannot inject the activated route.

**Comment by atscott** [comment]
Resolvers can return a `RedirectCommand` to redirect to the `NotFoundComponent` route. The options in the redirect allow for redirecting without changing the browser URL, so for this specific use-case, it can be accomplished with existing route. Resolvers can also return `EMPTY` to block the navigation or you can put the conditions in a CanMatch guard. 

Beyond that, realistically there will be no prioritization for a feature to treat all guards, including resolvers, as match conditions and moving on to the next route in the match results if any fail.
