### ISSUE TITLE
Links embedded inside docs sidebar popouts are not clickable

### ISSUE THREAD

**Issue by benelliott** [angular/angular#57078]
### Describe the problem that you experienced

Whenever you click on the sidebar popout elements on the new docs site, this has the effect of scrolling to the top of the sidebar menu's content.

This is problematic in two ways: it's unintuitive, as there is no obvious reason why clicking on an item half way down the list should revert the scroll, and it also seems to prevent default link behaviour on any anchor tags inside this panel.

### Enter the URL of the topic with the problem

https://angular.dev/cli/build#Arguments

### Describe what you were looking for in the documentation

Want to click links in the side menu

### Describe the actions that led you to experience the problem

Try clicking on the link in the documentation of the `source-map` argument:

> Output source maps for scripts and styles. For more information, see https://angular.dev/reference/configs/workspace-config#source-map-configuration.

### Describe what you want to experience that would fix the problem

Should be possible to navigate to the new page

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/user-attachments/assets/45ae82ee-413f-4387-90f0-d5b8738d0c9d)

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
Chrome 126 on Windows
```

**Comment by 9kubczas4** [comment]
I can take this issue.
