### ISSUE TITLE
"Content projection" guide does not mention fallback content

### ISSUE THREAD

**Issue by diesieben07** [angular/angular#57083]
### Describe the problem that you experienced

The guide about content projection does not talk about providing fallback content for `<ng-content>`, a feature which was added in version 18.

### Enter the URL of the topic with the problem

https://angular.dev/guide/components/content-projection

### Describe what you were looking for in the documentation

A section about how you can provide fallback content for `<ng-content>`:
```html
<ng-content><p>This is shown if no content is provided.</p></ng-content>
```

**Comment by ashishnd** [comment]
Hey @JeanMeche! Can I try to solve this issue?

**Comment by bencodezen** [comment]
Hey @ashishnd. PRs are always welcome!
