### ISSUE TITLE
Should stop bubbling event when event binding returns falsey

### ISSUE THREAD

**Issue by wardbell** [angular/angular#5708]
The following saves twice when I click the button
```
<!-- Should NOT save twice -->
<div (click)="onSave()">
  <button (click)="onSave() && false ">Save, no propagation</button>
</div>
```
This is so regardless of what  `onSave()` returns.

@vsavkin  responded:
>I think we just call preventDefault but do not stop the bubbling. I might have misled you previously.
I am actually surprised we do not stop bubbling there
Seems reasonable to do it

I think it is a matter of Angular honoring the `preventDefault` flag.

**Comment by vicb** [comment]
dup of https://github.com/angular/angular/issues/4782 ?

**Comment by vicb** [comment]
We do call `preventDefault` (at least in your case) but do not stop bubbling hence the observed behavior (`preventDefault` means that the browser will not do the default action like checking an input, navigating, ... it is normal that the event still bubbles).

**Comment by vicb** [comment]
@wardbell Can I close this one ?

**Comment by vicb** [comment]
This is the regular JS behavior. Should probably be documented better. I have created an issue on angular/angular.io
