### ISSUE TITLE
Rename validator `max` to `maxValue`

### ISSUE THREAD

**Issue by florestankorp** [angular/angular#57093]
### Description

I keep making the same mistake with the validators and always get confused by the naming between `max` (max value of the number in the input field) and `maxLength`, which speaks for itself :)

### Proposed solution

Rename `max` validator to `maxValue`

### Alternatives considered

Keep relying  on QA to catch my blunders...

**Comment by JeanMeche** [comment]
`max` is the native attribute of an `input[type=number]` to set the max, It is more reasonable to stay close to the native behavior.
