### ISSUE TITLE
Cannot read @let declaration before it has been defined

### ISSUE THREAD

**Issue by haigha106** [angular/angular#57095]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

using the new @let syntax with a signal, a build error occurs if the variable name is the same as the signal name, but is ok when defined in an @if block

`
  _### in component_ 
  user = signal('User');

    
    @if(user(); as user) {
      <p>{{user}}</p>
    }
    
    @let user = user();
    <p>{{user}}</p>
`

### Please provide the environment you discovered this bug in (run `ng version`)

```true
@angular-devkit/architect       0.1801.1
@angular-devkit/build-angular   18.1.1
@angular-devkit/core            18.1.1
@angular-devkit/schematics      18.1.1
@schematics/angular             18.1.1
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.8
```

**Comment by JoostK** [comment]
This is working as designed. Please see #56935 for relation discussions.
