### ISSUE TITLE
ErrorHandler don't works with async function 

### ISSUE THREAD

**Issue by cesco69** [angular/angular#57106]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

ErrorHandler don't works with async function, but works with normal method

```ts
import { Component, ErrorHandler, Injectable } from '@angular/core';
import { bootstrapApplication } from '@angular/platform-browser';
import 'zone.js';

@Injectable({ providedIn: 'root' })
export class CustomErrorHandler implements ErrorHandler {
  handleError(error: any) {
    alert(error.message);
  }
}

@Component({
  selector: 'app-root',
  standalone: true,
  template: `
    <button (click)="throwAsyncError()"> async errore (don't works) </button>
    <br /><br />
    <button (click)="throwSyncError()"> sync errore (works) </button>
  `,
})
export class App {
  async throwAsyncError() {
    throw new Error('async error');
  }

  throwSyncError() {
    throw new Error('sync error');
  }
}

bootstrapApplication(App, {
  providers: [{ provide: ErrorHandler, useClass: CustomErrorHandler }],
});
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-tkcpjs?file=src%2Fmain.ts

**Comment by JoostK** [comment]
Rejecting a promise (e.g. by throwing from an async function) is not handled by Angular's `ErrorHandler` because it happens outside of Angular's control, as the async nature of the rejection means that Angular doesn't know when it occurs, such that it can't catch it for you and pass it to its `ErrorHandler`.

You'll have to setup a listener for the [`unhandledrejection` event](https://developer.mozilla.org/en-US/docs/Web/API/Window/unhandledrejection_event) on `Window`.

Closing as working as expected.

**Comment by cesco69** [comment]
@JoostK in the Angular 16 it works... what is changed into Angular 18?

**Comment by JoostK** [comment]
I don't know; it could have been a bundling change (e.g. ES target version) or perhaps a zone.js update that may have affected this behavior.

**Comment by cesco69** [comment]
For everyone come here with the same problem, the workaround i have found is this:

```ts
import { Component, ErrorHandler, Injectable } from '@angular/core';
import { bootstrapApplication } from '@angular/platform-browser';
import 'zone.js';

@Injectable({ providedIn: 'root' })
export class CustomErrorHandler implements ErrorHandler {
  constructor() {
    window.addEventListener('unhandledrejection', (event) => {
      this.handleError(event.reason);
    });
  }

  handleError(error: any) {
    alert(error.message);
  }
}

@Component({
  selector: 'app-root',
  standalone: true,
  template: `
    <button (click)="throwAsyncError()"> async errore</button>
    <br /><br />
    <button (click)="throwSyncError()"> sync errore</button>
  `,
})
export class App {
  async throwAsyncError() {
    throw new Error('async error');
  }

  throwSyncError() {
    throw new Error('sync error');
  }
}
```
