### ISSUE TITLE
remove support for angular2/angular2 - the kitchen sink barrel

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#5710]
now that barrel reorg is done and bundle reorg is almost done, it is time to remove the `angular2/angular2` barrel (entry point) and force everyone to import from the correct location.

We are doing this because of the rule to export each symbol only via one public entry point to prevent confusion and code portability issues due to duplicate/platform-specific/bundle-specific imports.

This change will affect the following:

- [x] remove `angular2.ts`
- [ ] remove `angular2.dart` - requires fixing g3, so we should just fix ts side and leave this item open if we need more time to fix g3 #4027
- [x] update all internal imports that depend on `angular2/angular2`
- [x] update System.register bundle config
- [x] update UMD bundle config
- [x] update all api docs
- [ ] update all dev guide docs
- [x] update all dgeni (doc generation) entry points
- [x] update cli blueprints
- [x] update seed

// @pkozlowski-opensource @vsavkin @robwormald @wardbell @yjbanov @petebacondarwin

**Comment by pkozlowski-opensource** [comment]
There is one blocker that we should probably discuss: in our tests we've got a tests that checks for public API: https://github.com/angular/angular/blob/master/modules/angular2/test/symbol_inspector/symbol_inspector.ts 

The trouble is that this test uses `angular2/angular2` as an entry point for checks. I've discussed this yesterday with @vsavkin and the idea was to have per-barrel checks instead.

IMO we should resolve this one sooner than later as currently this is a blocking point for removal of `angular2/angular2` and bundles re-shaping.

**Comment by IgorMinar** [comment]
Yes - we should have per barel checks.

**Comment by petebacondarwin** [comment]
Looks like the dgeni side of things is sorted: https://github.com/angular/angular.io/blob/master/tools/api-builder/angular.io-package/index.js#L44-L54

**Comment by jeffbcross** [comment]
I'm working on the `public_api_spec` now, opened a separate issue for it before I knew this one existed https://github.com/angular/angular/pull/5820

**Comment by robwormald** [comment]
could we add 'main': 'core.js' and 'typings': 'core.d.ts' to this as well? makes `import {Component} from 'angular2'` work nicely

**Comment by jeffbcross** [comment]
I opened a PR for the barrel testing inside public_spec https://github.com/angular/angular/pull/5821

**Comment by jeffbcross** [comment]
Closing this one in favor of #4027 since removing angular2.dart is the only remaining task. I applied the same labels and milestone to that issue that @mhevery applied here. It seems like a good task for the caretaker on rotation.
