### ISSUE TITLE
`scrollPositionRestoration: 'enabled'` no longer works in Firefox since v18

### ISSUE THREAD

**Issue by BojanKogoj** [angular/angular#57109]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

When using `scrollPositionRestoration: 'enabled'` (or `top`) it is expected to scroll to the top when navigating. This worked in previous versions, but since v18 it only works _sometimes_.

This seems to be similar to https://github.com/nuxt/nuxt/pull/25817

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-acgd4y?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
When navigating between pages it does not scroll to the top.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.1.1
Node: 18.20.3
Package Manager: npm 10.2.3
OS: linux x64

Angular: 18.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1801.1
@angular-devkit/build-angular   18.1.1
@angular-devkit/core            18.1.1
@angular-devkit/schematics      18.1.1
@schematics/angular             18.1.1
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.8
```

### Anything else?

Adding `setTimeout` to `scrollToPosition` seems to fix the issue.

**Comment by surajchopra1234** [comment]
Previously, scrollPositionRestoration: "enabled" used a setTimeout function. However, this caused flickering and was removed (see issue #53985).

Using setTimeout to delay scrolling can cause a noticeable flicker because the scrolling happens in the next frame.

#55105 commit commit fixes this issue by scrolling as soon as the next rendering occurs.
