### ISSUE TITLE
Reapply pipe when an item is added to an array 

### ISSUE THREAD

**Issue by JurajMlich** [angular/angular#5711]
(Angular2) Imagine having a situation in which you need to filter some items from an array using a pipe. The HTML code can look like this:
`
<element *ng-for="#item of array | pipe">
`

Everything works perfectly until you add one item to the array which normally would be filtered and removed by the pipe. You would expect the pipe's transform function being called again. But that's not what happens. It just stays and nothing changes. 

I don't think it is an expected behaviour, I would expect that the pipe is recalled again. What do you think about that? Thanks :)

**Comment by pkozlowski-opensource** [comment]
In angular2 pipes are pure functions by default, see "Stateful Pipes" in: https://angular.io/docs/ts/latest/guide/pipes.html

**Comment by JurajMlich** [comment]
Well, that's right. But if I set the pipe to not pure, it calls the pipe's transform function very frequently what freezes the application. The pipe I want to use is very simple. Its function is to sort the array just like there was a filter orderBy in Angular1 which worked in the way I need. What do you suggest?

**Comment by pkozlowski-opensource** [comment]
Have a look at the `NgFor` directive to see how to efficiently react on array entry changes

**Comment by JurajMlich** [comment]
I'm not quite sure what you mean by that. I want to simply order the items of an array by some property the objects (which are in the array) have. Like for example imagine a class Text which has a property id. 

I have a list of texts in an array. This array is printed by NgFor and I want to the final list be sorted according to the ids of the texts (text with the id 1 will be first, with 10000 will be last). When the ID of any text changes, I want to reorder the list.

How can I achieve it?

**Comment by pkozlowski-opensource** [comment]
2 ways, both involving a stateful pipe:
* just mark a pipe as non-pure. such pipe would be easy to implement but would fire on each change detection turn, so not the most efficient
* if you want to re-sort an array only when a reference to the array changes or content of the array changes, you need to create a stateful pipe that would return a sorted array. You can use `IterableDiffer` (as NgFor does) to efficiently detect changes in the array itself.

If you need help with the implementations details please ask support questions on the dedicated support channel (https://gitter.im/angular/angular works best for now). We want to keep GitHub issues for bug reports and future requests. Thnx!
