### ISSUE TITLE
Allow Embed of Docs for Use in a Certification Exam from certificates.dev

### ISSUE THREAD

**Issue by danielkellyio** [angular/angular#57114]
### Describe the problem that you experienced

When attempting to iframe the Angular docs into our exam platform we get "angular.dev refused to connect".

We understand this is the desired Content-Security-Policy for most cases but would like to request an exception for the following domains:

* staging.certification.vuejs.org
* certification.vuejs.org
* certificates.dev
* staging.certificates.dev

This allows us to provide test takers access to documentation while attempting a couple of Angular coding challenges.

### Enter the URL of the topic with the problem

https://certificates.dev/angular

### Add a screenshot if that helps illustrate the problem

![Screenshot 2024-07-24 at 8 46 46 AM](https://github.com/user-attachments/assets/84d23c3a-31af-4eda-acdd-dc8c6159f026)

**Comment by josephperrott** [comment]
This is something the team will need to have a larger discussion about before we take any sort of action.

**Comment by danielkellyio** [comment]
thanks for considering @josephperrott! 🙏

**Comment by josephperrott** [comment]
After investigation of our internal policies and some discussion we have determined we will not be supporting embedding of our documentation. The primary reason for this is the risk of abuse and security concerns with a lack of control in the context in which the embedding occurs.
