### ISSUE TITLE
Add a merge function to be able to merge two signals into one output

### ISSUE THREAD

**Issue by jgerstle** [angular/angular#57112]
### Which @angular/* package(s) are relevant/related to the feature request?

@angular/core

### Description

I want to be able to merge two signals into one stream similar to the rxjs merge function. 
The context for us is to merge input and output signals into one stream. We can't use the model signal since in certain instances we might want to do things when the input changes and not the output. (If there is a way to separate the two it would be nice to know, but I think the request is still useful)

### Proposed solution

I managed to create a workaround using rxjs interop:
```typescript
function mergeSignals<GValue>(...signals: Signal<GValue>[]): Signal<GValue> {
  return toSignal(merge(...signals.map(s => toObservable(s))), {initialValue: null as GValue});
}
```
https://stackblitz.com/edit/stackblitz-starters-iqyqix?file=src%2Fmain.ts

### Alternatives considered

A better solution would be to handle internally since I assume it would be more efficient. I don't know enough about the internal structure at this point to suggest something better.

**Comment by JoostK** [comment]
There's a conceptual mismatch here; `merge` is for combining multiple _events_ into a single _event stream_, whereas signals are for representing _state_, which an event stream is not.

**Comment by jgerstle** [comment]
> There's a conceptual mismatch here; `merge` is for combining multiple _events_ into a single _event stream_, whereas signals are for representing _state_, which an event stream is not.

I'm not sure I agree with you. Input and output are both events and are both signals. In addition I want to combine these two events to create a state stream, so I'm not sure how what you said applies to the scenario I gave above.

**Comment by JeanMeche** [comment]
There is a fondamental misunderstanding here. Signal do notify on value change enventually.
Updating a signal twice in the same microtask will only fire an effect once for example. 

They are reactive because they notify on value change, but not for every value changes are stream do.

**Comment by jgerstle** [comment]
> There is a fondamental misunderstanding here. Signal do notify on value change enventually. Updating a signal twice in the same microtask will only fire an effect once for example.
> 
> They are reactive because they notify on value change, but not for every value changes are stream do.

Not sure I understand your point. If you are saying it is used for state, not events, as I replied to @JoostK I do need it for state, not events

**Comment by pkozlowski-opensource** [comment]
For the case described I would suggest creating a signal for payload emitted from an output and then use `computed`.
