### ISSUE TITLE
Rename the external-dependencies.js bundle to....

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#5714]
Sooo, we all love naming discussion, here is the one! Currently we've got the `external-dependencies.js` bundle that contains:
* zone.js
* reflect-metadata

The idea was to rename it to sth like `angular-polyfills.js` but this name might be confusing as:
* zone.js is not a polyffil 
* we don't include es6-shim here, which I would kind of expect from something that is named `angular-polyfills.js`

I guess there are 2 questions here:
* what should be the content of this bundle (that is, shell we add es6-shim?)
* what would be the best name for this thingy?

**Comment by IgorMinar** [comment]
let's call it `angular-polyfills.js` even though it contains zone. The hope is that zone will become a polyfill in the future. So while technically some things are polyfills and others are prolyfills, we need to put them into a single bundle and this bundle should be called with something that properly represents the content. `angular-polyfills.js` is the closest thing to that as far as I'm concerned.
