### ISSUE TITLE
Router Outlet adds component after the current component

### ISSUE THREAD

**Issue by bruno-lopes** [angular/angular#57151]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

I'm using standalone components, and a custom layout, so I have to router outlets, one in app.component.html and one on the custom layout component (core-ui-admin-layout.component.html).

When I enter on the app, it redirects to localhost:4200/dashboard, and the component is loaded correctly. If I click on the left menu to go to Graph, it loads the second component below the dashboard component.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/~/github.com/bruno-lopes/router-outlet-problem

### Please provide the exception or error you saw

```true
The second component is loaded below the first component.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.1.2
Node: 18.20.0
Package Manager: npm 10.5.0
OS: linux x64

Angular: 18.1.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1801.2
@angular-devkit/build-angular   18.1.2
@angular-devkit/core            18.1.2
@angular-devkit/schematics      18.1.2
@schematics/angular             18.1.2
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.8
```

### Anything else?

Also, in dashboard, if I click on the "child works!" text, it activates a IF on the child component, and show some info. If I click "child works!" again, it deactivates the if, but the info is not hidden. If I click a third time on "child works!" text, the info is showed below the first info.

**Comment by JeanMeche** [comment]
You're not supposed to import the animation provider outside the rootModule / your `ApplicationConfig`.

**Comment by bruno-lopes** [comment]
@JeanMeche very thanks! Now it works like a charm.
