### ISSUE TITLE
Validation `Required` is not working with radiobtn when using ngFor in Reactive forms

### ISSUE THREAD

**Issue by mohammadamgithub** [angular/angular#57167]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description
I have a dynamic reactive angular form which builds forms and populates questions inside it dynamically according to questions types retrieved from the database. the problem is the required validation (native HTML5 validation ngNativeValidate) is not working when I add it inside a *ngFor loop

in my form builder I have this part
```
       <div>
          <legend class="col-form-label col-sm-6 pt-0">
            {{ question.label }}
          </legend>
          <div class="col-sm-6">
            <div
              class="form-check"
              *ngFor="let opt of question.options; let i = index">
              <label
                class="form-check-label"
                [attr.for]="question.key + opt.key" >
                <input class="form-check-input"
                  type="radio"
                  [name]="question.key"
                  [formControlName]="question.key"
                  [id]="question.key + opt.key"
                  [value]="opt.key"
                  required
                />
                {{ opt.value }}
              </label>
            </div>
          </div>
        </div>
```
    
I have ngNativeValidate in the form tag and I have new FormControl(question.value || '', Validators.required) in the FormGroup builder.

This code is supposed to apply required validation check but it's not working. when I remove the for loop and make it static the validation works. what is the reason here.

Note: my Angular version is 10.

I have it here as well [Example](https://stackblitz.com/edit/angular-radio-buttons-demo-reactive-forms-i7g2c5?file=README.md)

### Please provide the exception or error you saw

```true
HTML5 native validation stops working
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Your global Angular CLI version (9.1.13) is greater than your local
version (8.3.29). The local Angular CLI version is used.
```

### Anything else?

no

**Comment by JeanMeche** [comment]
This is basically the same root case as #45719. 
Your `input[radio]` needs to have both `[name]` and `[attr.name]` to be set.
