### ISSUE TITLE
RouterPreloader Should Respect `canMatch`

### ISSUE THREAD

**Issue by Char2sGu** [angular/angular#57177]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

In RouterPreloader, loadChildren will not be invoked if `canLoad` is present:

https://github.com/angular/angular/blob/d108320ea394e827fc23011b54d12e168287bce4/packages/router/src/router_preloader.ts#L127-L140

Since `canLoad` is replaced by `canMatch`, this behavior should be updated as well: both canLoad and canMatch should prevent route preloading.

Additionally, `loadComponent` should also be prevented if `canMatch` is present.

**Comment by atscott** [comment]
Closing - this is not something we will do. If you want these conditions to apply, you can install a custom preloader that pays attention to them. But we do not want to carry over the behavior of `canLoad` where no preloading can ever be attempted. There is even a request in exact opposition to this one: #20994.

**Comment by Char2sGu** [comment]
Makes sense
