### ISSUE TITLE
NG template control flow migration script unnecessarily reformats HTML templates to replace whitespace

### ISSUE THREAD

**Issue by C7C8** [angular/angular#57188]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

When using `ng generate @angular/core:control-flow` to update control flow syntax from `*ngIf`-style to `@if` style, the migration script runs a generic reformat on HTML templates. This reformats the entire HTML file to use whatever style the formatter used chooses, instead of what the project uses. In my case, my HTML files are indented with tabs, and it reformatted every affected template with spaces. This introduces unwanted changes and causes commits from migrations to be unnecessarily large.

### Please provide a link to a minimal reproduction of the bug

N/A

### Please provide the exception or error you saw

```true
N/A
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.1.2
Node: 22.5.1
Package Manager: npm 10.8.2
OS: linux x64

Angular: 18.1.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... platform-server, router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1801.2
@angular-devkit/build-angular   18.1.2
@angular-devkit/core            18.1.2
@angular-devkit/schematics      18.1.2
@schematics/angular             18.1.2
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.8
```
```


### Anything else?

_No response_

**Comment by JoostK** [comment]
The intention is to postprocess files with a project-configured formatter, like prettier, after the migration has been executed.

You may be able to pass `--no-format` to not run any formatting at all.
