### ISSUE TITLE
Bundle order causes components to be undefined with `build-angular:application`

### ISSUE THREAD

**Issue by jeroen1602** [angular/angular#57180]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

I have created a circular dependency in my project. (I know it isn't best practice to do so.)

This circular dependency causes the `DefaultDashboardComponent` to be emitted after the `dashboard-modules:DASHBOARD_MODULES` array. Which then causes the component to be undefined in this initial array.

```mermaid
graph TD
  dashboard-modules:DASHBOARD_MODULES --> DefaultDashboardComponent;
  DefaultDashboardComponent --> DashboardEndpointsService;
  DashboardEndpointsService --> dashboard-modules:findDashboardNavByKey;
  dashboard-modules:findDashboardNavByKey --> dashboard-modules:DASHBOARD_MODULES;
```

Using the older `@angular-devkit/build-angular:browser` builder didn't suffer from this problem.

### Please provide a link to a minimal reproduction of the bug

https://github.com/jeroen1602/angular-bundle-order

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.8
Node: 22.5.1 (Unsupported)
Package Manager: npm 10.8.2
OS: darwin arm64

Angular: 17.3.12
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.8
@angular-devkit/build-angular   17.3.8
@angular-devkit/core            17.3.8
@angular-devkit/schematics      17.3.8
@angular/cli                    17.3.8
@schematics/angular             17.3.8
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.8
```

**Comment by JeanMeche** [comment]
This is quite common when you have a dependency cycle. You should fix the dependency cycle.

**Comment by jeroen1602** [comment]
So it is not seen as a regression since the previous build was able to cope with this?

**Comment by JeanMeche** [comment]
Angular doesn't control how the bundler behaves.

**Comment by jeroen1602** [comment]
Ok, thanks for the info.

Too bad there is nothing to be done.
