### ISSUE TITLE
Computed outputs

### ISSUE THREAD

**Issue by WingSMC** [angular/angular#57208]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

I find myself writing this pattern surprisingly often:

```ts
public readonly someComputedOutput = output<T>();
protected readonly valueForComputedOutput = computed<T>(() => ...);
  
constructor(...) {
    effect(() => {
        this.someComputedOutput.emit(this.valueForComputedOutput());
    });
}
```

### Proposed solution

We should have some computed output signal like
```ts
public readonly someComputedOutput = computedOutput<T>(() => ...);
```

It'd be great if it behaved similar to a regular computed in the sense that this could also be read from with `this.someComputedOutput()`

**Comment by wartab** [comment]
I think the point is that outputs aren't signals, but Event Emitters, which isn't strictly the same. Signals are meant to manage state, not events.

I think what you want can be done using:
```ts
public someComputedOutput = outputFromObservable(toObservable(this.valueForComputedOutput));
```

**Comment by pkozlowski-opensource** [comment]
Creating an effect is the right approach here as effects determine timing of events.

**Comment by JoostK** [comment]
Also see #56923 for prior discussion on this topic.
