### ISSUE TITLE
Angular v16 & v17 apps not working in iPhone 12 Mini v14.2

### ISSUE THREAD

**Issue by muruganklt** [angular/angular#57207]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

When I open the Angular 16 & 17 version app on iPhone 12 Mini v14.2 mobile I get a blank page even though the Angular official site for v16 & v17 application is also not working. 

[](https://v16.angular.io/)

[](https://v17.angular.io/docs
)

![bs_realios_Mobile_iPhone 12 Mini-14 0](https://github.com/user-attachments/assets/b6a4ddc3-133d-4959-958a-832c3c20a7c4)

I have tested with the Safari & Chrome browser

**Comment by muruganklt** [comment]
![image](https://github.com/user-attachments/assets/8c28f099-b3be-45c0-ba6b-7064d39b92b8)

**Comment by JoostK** [comment]
iOS 14 runs a version of Safari 14, which is not among the default-supported browsers in Angular 16+.

**Comment by JeanMeche** [comment]
To give some hints, 
Try including ios 14 in your `.browserslistrc` config and check in the console if you might need one or more polyfills to support this platform.
