### ISSUE TITLE
Typing of input.required() vs input()

### ISSUE THREAD

**Issue by andreialecu** [angular/angular#57225]
### Which @angular/* package(s) are relevant/related to the feature request?

common

### Description

`input.required()` returns the same typescript type as `input()` which makes it difficult to statically analyze which inputs are required and which are optional.

If `input.required()` returned some other branded type, for example `RequiredInputSignal<T>` we could then devise a type such as:

```ts
type ComponentInput<T> = ... // not shown here, see TS Playground link

function render<T>(component: Type<T>, inputs: ComponentInput<T>) {
}

class Component {
  name = input.required<string>();
  birthday = input<Date>();
}

// works
render(Component, { 
  name: 'hello',
  birthday: new Date()
})

// shows error because name is required
render(Component, { 
  birthday: new Date()
})

// works because birthday is optional
render(Component, { 
  name: 'hello',
})

// error because there's no foo
render(Component, { 
  name: 'hello',
  foo: 'bar'
})
```

[TS Playground link](https://www.typescriptlang.org/play/?ssl=39&ssc=1&pln=68&pc=3#code/CYUwxgNghgTiAEYD2A7AzgF3geQA4YEtUoIBJFXAVwwGUCBzFEmgTwFsAjJCALnkpQEAjpQRp2XCAG4AsAChQkWAmTosAJRAiCcYOSq0GTCK07c+A4aPjiz0+fMXQ48DC1wI8hYmQrU6jCQAPAAqAHzwALzwAN7wANpeRMb6-kbMEtwAunwYMNYAvrJyjuDOCG4e8JrauqmGgRChEdFx8TWUOiB6fg3GppI5rvkIBQ4KZcqu7gj1AcbNUTj4ySRz6U3h8AA+1Vqddb3zweHjTlMEKBggMABmUGCzvQBiAmDeKLHy8D-wzQAUAEo+EkfOtGqEdvwUKBbpdumFir94HBat0+DFvsjfgDgXs0T0DMdNoisT8ivIxiUJkoXKpMPBLgY+PVXih3sliqVaQhLtc7g8ECEZosQAAPa4wtDwNkc1BfOTIlAgADu8H+ADotbB6Gg+FAUCx4lk8SFilTueVplUAAoEMAAawAQixhR5QgAaeAANRIohaCp+8RtjM+DpALCQt3gIXgUGlIWDWXg4slwGlvog1l2Alh8OA8AA-PAQ3xlQA3G5DRM2rKUs6TFyVBAAYSQbFwqBAV1BKV6i0iWN2mMV2ODofg4cj0ZCWULfBrydT3fTyw+ayOGyCl1uN3gAFUIsX9-AF0mkb8LTSrc34G2O12rh0uoTqAOh4GxyHLpOI1GY9WSYphKK7Ss+hxEluO57oeRYHqeMbnmS8BXucTYzHe7adsqVz1AOmEPjhGC9huBhBHajoum6ICemuqy+JBEICA6KBICqKBhJx8AAGQEdh3YYOB3R4RRzquiKIRekJr59MEzGsexnFhOM8i3G8HwoiuNwAsghECQuElhF6TLUHqfGPhgeHhICCpXkoaDSve-FXJ+TBsAg0QmRgGqogc3RBJgMCXPQYRAheHA6BgAAWwBQCwSxeUEAAiUDXKFgLmuMAD0WXwCqSAwA6aDyHAMI3P8TkWV6cRYm5IB8AA5FFIAQBASANR6WIRTA0WxSwZaqvAKXXEClKAtluVoFFbHSjcMAFfAHDgFAlBoAgdWMtKvkviVWkwBVWFVbE8BdZFMVxQNarDSAo1yAU43UjleUFUVi3LatCDdb1cWbfASArD4u1lftlVEdVJ2jnVjXNa17WdXdD3yE9c0LUtYArWtrjNXADXSqx8C3EgSBA6AIOHWDx21VA7nQy1bUdVihNII1HCwA1Y3yEAA)

### Proposed solution

`input.required()` should return a different typescript branded type than `input()`.

See this playground: [demo](https://www.typescriptlang.org/play/?#code/CYUwxgNghgTiAEYD2A7AzgF3geQA4YEtUoIBJFXAVwwGUCBzFEmgTwFsAjJCALnkpQEAjpQRp2XCAG4AsAChQkWAmTosAJRAiCcYOSq0GTCK07c+A4aPjiz0+fMXQ48DC1wI8hYmQrU6jCQAPAAqAHzwALzwAN7wANpeRMb6-kbMEtwAunwYMNYAvrJyjuDOCG4e8JrauqmGgRChEdFx8TWUOiB6fg3GppI5rvkIBQ4KZcqu7gj1AcbNUTj4ySRz6U3h8AA+1Vqddb3zweHjTlMEKBggMABmUGCzvQBiAmDeKLHy8D-wzQAUAEo+EkfOtGqEdvwUKBbpdumFir94HBat0+DFvsjfgDgXs0T0DMdNoisT8ivIxiUJkoXKpMPBLgY+PVXih3sliqVaQhLtc7g8ECEZosQAAPa4wtDwNkc1BfOTIlAgADu8H+ADotbB6Gg+FAUCx4lk8SFilTueVplUAAoEMAAawAQixhR5QgAaeAANRIohaCp+8RtjM+DpALCQt3gIXgUGlIWDWXg4slwGlvog1l2Alh8OA8AA-PAQ3xlQA3G5DRM2rKUs6TFyVBAAYSQbFwqBAV1BKV6i0iWN2mMV2ODofg4cj0ZCWULfBrydT3fTyw+ayOGyCl1uN3gAFUIsX9-AF0mkb8LTSrc34G2O12rh0uoTqAOh4GxyHLpOI1GY9WSYphKK7Ss+hxEluO57oeRYHqeMbnmS8BXucTYzHe7adsqVz1AOmEPjhGC9huBhBHajoum6ICemuqy+JBEICA6KBICqKBhJx8AAGQEdh3YYOB3R4RRzquiKIRekJr59MEzGsexnFhOMlpTLcbwfCiK43ACyCEQJC4SWEXpMtQep8Y+GB4eEgIKleShoNK978Vcn5MGwCDRKZGAaqiBzdEEmAwJc9BhECF4cDoGAABbAFALBLN5QQACJQNcYWAua4wAPTZfAKpIDADpoPIcAwjc-zOZZXpxFi7kgHwADk0UgBAEBII1HpYpFMAxXFLBlqq8CpdcQKUoCOV5Wg0VsdKNwwIV8AcOAUCUGgCD1Yy0p+S+pXaTAlVYdVsTwN1UWxfFg1qiNIBjXIBQTdSuX5YVxVLSta0ID1fXxVt8BICsPh7eVB1VURNWnaO9VNS1bUdV192PfIz3zYty1gKt62uC1cCNdKrHwLcSBIMDoCg0d4MnXVUAeTDrXtZ1WJE0gTUcLAjXjfIQA)

### Alternatives considered

None exist

**Comment by andreialecu** [comment]
I think that's fine. It seems to me that decorator based inputs are on the way out and will be deprecated at some point.

**Comment by JeanMeche** [comment]
Sure that would be fine for (future) Signal Components but on regular ones, it can lead to surprising/inconsistant behavior. 

Imagine components implemented in a library, you wouldn't directly know if the inputs are implements via decorators or signals and those types wouldn't be consistant with the inputs you're using in the HTML for example.

**Comment by andreialecu** [comment]
That's true, but if this started small with just a different type, it would allow library authors to tap into this information.

It is useful for angular testing library, for example, to be able to hint at which inputs are mandatory. 

Not sure where else it could be useful, perhaps internally in the angular compiler? I see that there's currently a special case for `input.required()` written in the compiler which perhaps could be implemented directly by type checking instead. But I don't know much about the specifics there, so perhaps I'm missing something.

**Comment by devversion** [comment]
The compiler wouldn't benefit from a type-system distinction here IIRC. Not sure though, what particular code piece you were looking at for the "special case". A branded type may be nice, but in practice, this also doesn't work well for inputs marked as `protected`, which is not even discoverable via e.g. `keyof MyComp`.

**Comment by alxhub** [comment]
+1. This isn't something I see us adding to `input()`, as it gives incomplete information still and encourages a pattern of relying on the types of fields to work with inputs, which is something we expressly discourage.
