### ISSUE TITLE
a new function to retrieve local source entry  (for debugging)

### ISSUE THREAD

**Issue by PGTBoos** [angular/angular#57227]
### Description

I propose a function that would return from where it was called.
An output alike 'main.ts functionxy r43' where the row number refers to the start of the function or observable or class or ...'  

I think the request is simple, currently there is no way to tell from within a running application to tell where its from.
Sure one can do console.log ('main.ts my function', myMessage)  is a workaround.

However imagine yourself a large application in an angular upgrade.
And each function/method observable etc requires a handwritten line to tell the origin.
. ..Its the way how i currently do it.. and it's cumbersome.

I have created a public [debug library for Angular and RXJS ](https://github.com/PGTBoos/RxJs-Debug.ts)
in which one now might add  identification location string as a possible overload, for a group of debug functions.
But it's not elegant, i have tried to get such info in other ways as well, but none really worked in all cases, and most worked not at all. This information isn't available once the code is compiled, it becomes a java blob.

### Proposed solution

a string function that upon build
keeps track of function names and observable names, and generates a short identification with at least the filename and origin in that file preferably also with a row number of the function.

### Alternatives considered

use a const in every function that you want to log
This may sounds as sure why not.. till you do large application and try to debug rxjs within your app.

**Comment by JeanMeche** [comment]
JS doesn't allow proper introspection to retrieve function name. 
This isn't doable.
