### ISSUE TITLE
Only update controls when connecting signals and do not check the component and parent components

### ISSUE THREAD

**Issue by Hoschi1982** [angular/angular#57242]
### Description

Hi, 

I've been looking into signals and I think the introduction is very good. However, I initially thought that the controls that are bound to signals are updated directly and that the current component and its parent components are no longer checked separately when used zoneless. However, that doesn't seem to be the case, as binding two controls in a component to the same signal results in the component itself and its parent components being checked. And that twice, as the same signal is bound to 2 input controls. Are there any ideas or efforts to adapt the binding and change detection so that only and really only the controls bound to signals are updated without checking the current and its parent components?

Thanks :)

### Proposed solution

Question

### Alternatives considered

Question

**Comment by JeanMeche** [comment]
Hi, do you mind sharing an example ? 
What are you call controls here ? FormControls ?

**Comment by Hoschi1982** [comment]
Thank you for your answer. 

I was thinking of the concept of data binding, as used by Microsoft in WPF or WinForms, for example. The corresponding model, which is bound to the interface in general, must implement a certain interface (INotifyPropertyChanged and can thus inform the interface of a change if the model changes. Would a similar concept be conceivable in Angular? With Signals, I thought that this was already the case and therefore made the analysis of your own component and its parent components superfluous. This should lead to a significant improvement in performance or am I seeing this wrong? In my opinion, it would make sense if there was the possibility in the future to update only certain bound surface parts without analyzing the current component and its parent components. As "controls" I refer to the HTML elements that have a binding.

I hope my question is somewhat understandable? As far as I know, even in zonless mode there is currently no way to deactivate the check of your own component and its parent components and only update the corresponding bound HTML elements when the bound model changes. Or am I wrong?

thanks :)
