### ISSUE TITLE
Infinite loop in shared.ts

### ISSUE THREAD

**Issue by perceptron8** [angular/angular#57243]
### Which @angular/* package(s) are the source of the bug?

animations

### Is this a regression?

~No~
Yes

### Description

Due to an extremely unlikely  (but not too unlikely!) coincidence, the Angular animation module stucked in an infinite loop.

This occured inside `containsElement(elm1, elm2)`: https://github.com/angular/angular/blob/18.1.3/packages/animations/browser/src/render/shared.ts#L204
because of how `getParentElement(element)` is implemented: https://github.com/angular/angular/blob/18.1.3/packages/animations/browser/src/render/shared.ts#L159.

There are just [3 relevant files](https://github.com/perceptron8/quirk/tree/master/src/app) in the linked repository. The rest was generated with `ng new` using default settings (with the exception of routing, which I disabled). The most important part seems to be `AppComponent`'s template:

```html
@if (true) {
	<form>
		<input id="host" />
		<p-overlay></p-overlay>
	</form>
}
```

1. `p-overlay` is some meaningless component using `animations: []` (see [overlay.ts](https://github.com/perceptron8/quirk/blob/master/src/app/overlay.ts)),
2. It's sibling, `input` identified as `"host"`, is enclosed inside a `form`,
3. Initially `form` seems to have no `parentElement` because of `@if` (same would be true if `*ngIf` was used).

All of the above had to appear for this bug to occur: element using animations, `input` with id (or name) equal to 'host' and a `form` inside control flow block. Then, `getParentElement` gets no `element.parentNode` because of (3.) and falls back to `element.host`. Next, because of (2.), `element.host` refers to `input` instead of nothing (as form is not so much of a custom element). Finally, there is (1.), which makes `containsElement` being called in the first place.

---

It seems to me, that it may be sufficient to change `getParentElement` so it uses `.host` access more carefully (i.e. conditionally).

---

Please note, that the current implementation will also fail for `<a href='...'>` inside a control block as `a` also has `host` property (see https://developer.mozilla.org/en-US/docs/Web/API/Location/host).

```html
@if (true) {
	<a href="https://angular.dev/">
		<p-overlay></p-overlay>
	</a>
}
```

In this case however, there will be no infinite loop, as `a`'s `host`, being a `String` equal to`"angular.dev"`, has neither `parentNode` nor `host`. Still, parent element doesn't really seem to be determined correctly.

---

Some hopefully useful spec links:
- https://dom.spec.whatwg.org/#dom-shadowroot-host
- https://html.spec.whatwg.org/multipage/forms.html#dom-form-nameditem

### Please provide a link to a minimal reproduction of the bug

https://github.com/perceptron8/quirk

### Please provide the exception or error you saw

```true
Browser's tab freezes with 100% CPU usage.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.1.3
Node: 22.3.0
Package Manager: npm 10.8.1
OS: linux x64

Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1801.3 (cli-only)
@angular-devkit/core         18.1.3 (cli-only)
@angular-devkit/schematics   18.1.3 (cli-only)
@schematics/angular          18.1.3 (cli-only)
```

### Anything else?

If you disable animations (globally in `ApplicationConfig` or locally in `Overlay`) _or_ change `input`'s id to something else than `"host"` _or_ remove `@if` wrapper, this crazy bug dissapears.

**Comment by JoostK** [comment]
Wow, that is something indeed. It is _wild_ that `HTMLFormElement` provides access to its controls as properties on itself. I suppose this can be somewhat easily addressed using `instanceof ShadowRoot`.

For reference, this broke in #40134.

**Comment by perceptron8** [comment]
How about
```ts
export function getParentElement(element: any): unknown | null {
  const parent = element instanceof ShadowRoot ? element.host : element.parentNode;
  return parent !== documentElement ? parent : null;
}
```
?

BTW would it be a good idea to change the types to

```ts
function getParentElement(element: Node): Node | null
```
?

**Comment by perceptron8** [comment]
I know that this is just a tiny change, but I'll be happy to create PR.

**Comment by JoostK** [comment]
> How about
> 
> ```ts
> export function getParentElement(element: any): unknown | null {
>   const parent = element instanceof ShadowRoot ? element.host : element.parentNode;
>   return parent !== documentElement ? parent : null;
> }
> ```
> 
> ?

That seems reasonable, but it does incur an `instanceof` check for each element. I can't tell if that would make for a measurable difference though. Let's just go with that as it seems like the code you'd write without the prior logic in mind.

---

> BTW would it be a good idea to change / narrow the types to
> 
> ```ts
> function getParentElement(element: Node): Node | null
> ```
> 
> ?

Doing that would break the callers that currently pass in an argument of type `unknown`. The following is more conservative while still improving things:

```ts
export function getParentElement(element: unknown): unknown | null {
  const parent = element instanceof ShadowRoot ? element.host : (element as Node).parentNode;
  return parent !== documentElement ? parent : null;
}
```

**Comment by perceptron8** [comment]
> That seems reasonable, but it does incur an instanceof check for each element.

It seems to be unavoidable, but it's always possible to fix this later if we figure out better solution.

> Doing that would break the callers that currently pass in an argument of type `unknown`

How about casting / using type assertions at the callers site (contrary to `AnimationDriver`, `getParentElement` doesn't seem to be public)? This way, all assumptions about this function would be clearly visible in types and could be used to reason about possible outcome. If `element` is guaranteed to be a `Node` then it's also guaranteed for this function to return `Node | null`, as `ShadowRoot.host` is never `null` and `Node.parentNode` can't be `undefined` (it can be `null` however if node has no parent node).

**Comment by perceptron8** [comment]
> (contrary to AnimationDriver, getParentElement doesn't seem to be public)

In the sense not being a part of the API.

**Comment by JoostK** [comment]
It may not be public API, indeed, but it does introduce some additional changes that aren't really needed to address this bug. Landing a change with smaller scope is typically easier.

> It seems to be unavoidable, but it's always possible to fix this later if we figure out better solution.

It is easily avoided by preferring the read of `parentNode`:

```ts
export function getParentElement(element: unknown): unknown | null {
  const parent = (element as Node).parentNode ?? (element instanceof ShadowRoot ? element.host : null);
  return parent !== documentElement ? parent : null;
}
```

Under the assumption that most nodes will not be `ShadowRoot` this saves the `instanceof` check in most cases.

**Comment by perceptron8** [comment]
> Under the assumption that most nodes will not be `ShadowRoot` this saves the `instanceof` check in most cases.

At the cost of slightly reduced readability. I'd assume this kind of optimization is something that branch prediction is taking care of.

Give me some time, please, I may have another idea. :-)

**Comment by perceptron8** [comment]
> Landing a change with smaller scope is typically easier.

Fully agree.

At the same time I can't help but ask about:

```ts
export function containsElement(outer: any, inner: any): boolean {
	while (inner) {
		if (outer.contains(inner)) {
			return true;
		}
		const root = inner.getRootNode();
		inner = root.host;
	}
	return false;
}
```

It looks like it could be faster than going through nodes one by one. Is there any reason for not using `Node.contains`?

WDYT?

**Comment by JoostK** [comment]
> It looks like it could be faster than going through nodes one by one. Is there any reason for not using Node.contains?

I don't know, looking at its availability status on MDN I would think it could have been used from the start. The shadow root special-case might explain it, but your suggestion would avoid that. I doubt it's necessarily more efficient though, as it involves the same amount of work to be done.

**Comment by perceptron8** [comment]
> I doubt it's necessarily more efficient though, as it involves the same amount of work to be done.

It's at most the same work, as browsers may use some tricks to avoid node traversal whatsoever. Either way, it's not that important. My purpose was simplicity (and lack of `instanceof`).

What bothers me now is one thing I hadn't thought before: attribute nodes. Is it possible, that `containsElement` needs to support them?

**Comment by perceptron8** [comment]
> Landing a change with smaller scope is typically easier.

Well, I do agree again. It's getting too complicated. I'll be happy with what you proposed:

```ts
export function getParentElement(element: unknown): unknown | null {
  const parent = (element as Node).parentNode ?? (element instanceof ShadowRoot ? element.host : null);
  return parent !== documentElement ? parent : null;
}
```

`getParentElement` needs to be there anyway because of `AnimationDriver.getParentElement`.

**Comment by perceptron8** [comment]
Rewriting `containsElement` seems to be the only way to go:

```ts
export function containsElement(elm1: any, elm2: any): boolean {
	while (elm2) {
		if (elm1.contains(elm2)) {
			return true;
		}
		const root = elm2.getRootNode();
		elm2 = root.host;
	}
	return false;
}
```

Why? We both missed this marvel:
```html
<form>
	<input name="parentNode">
</form>
```

As for fixing `getParentElement`, I have no idea yet.

**Comment by perceptron8** [comment]
Here's something that appears to be working quite reliably:

```ts
// used to avoid https://html.spec.whatwg.org/multipage/forms.html#dom-form-nameditem
const parentNode = Object.getOwnPropertyDescriptor(Node.prototype, "parentNode").get;

export function getParentElement(element: unknown): unknown | null {
  const parent = parentNode.apply(element as Node) ?? (element instanceof ShadowRoot ? element.host : null);
  return parent !== documentElement ? parent : null;
}
```

**Comment by JoostK** [comment]
> Why? We both missed this marvel:
> 
> ```html
> <form>
> 	<input name="parentNode">
> </form>
> ```

I had considered this, but hadn't checked it as it seemed like the worst possible behavior if this were to shadow the native property. Yet it does...

---

> Here's something that appears to be working quite reliably:
> 
> ```ts
> // used to avoid https://html.spec.whatwg.org/multipage/forms.html#dom-form-nameditem
> const parentNode = Object.getOwnPropertyDescriptor(Node.prototype, "parentNode").get;
> 
> export function getParentElement(element: unknown): unknown | null {
>   const parent = parentNode.apply(element as Node) ?? (element instanceof ShadowRoot ? element.host : null);
>   return parent !== documentElement ? parent : null;
> }
> ```

Hmm, I wonder if the property descriptor is known to always have a getter like this, cross-browser and in DOM emulation libraries. Plus I'd probably read it lazily to avoid a side-effectful top-level statement (it isn't really side-effectful but optimizers are unlikely to assume this for a `Object.getOwnPropertyDescriptor` call, e.g. it may throw an exception).

To be honest, I don't think it's worth it, or at least not just for the logic here; there's probably more cases where such pattern would break assumptions; `HTMLFormElement` is wildly in violation of `HTMLElement`'s type declarations. Consequently this means that _all_ property reads off of DOM nodes need to be treated like this, which seems like madness.

**Comment by perceptron8** [comment]
> To be honest, I don't think it's worth it, or at least not just for the logic here; there's probably more cases where such pattern would break assumptions;

That's true. How about fixing just `containsElement` then?

**Comment by perceptron8** [comment]
Sorry for force-pushing so many times. I did it mostly before creating PR and wasn't aware those commits will be visible outside my fork.

@JoostK Thanks for discussion, tips and patience! :)

**Comment by perceptron8** [comment]
It seems that `AnimationDriver` has to support `RNode`s (defined in [renderer_dom.ts](https://github.com/angular/angular/blob/18.1.3/packages/core/src/render3/interfaces/renderer_dom.ts#L21)). Because of this it may be impossible to avoid hitting named form properties.

Two other "solutions" come to my mind:
1. detecting cycle,
2. throwing after 1M or so iterations.

First option involves way too much overhead. Second is cheap, but doesn't have to be correct, although I don't think DOM trees can ever be so deep in practice.

```ts
export function containsElement(elm1: any, elm2: any): boolean {
	let iters = 0;
	while (elm2) {
		if (iters === 1_000_000) {
			throw new Error("Cycle detected!");
		}
		if (elm2 === elm1) {
			return true;
		}
		elm2 = getParentElement(elm2);
		iters++;
	}
	return false;
}
```

It's not pretty and I'm not sure it's worth doing, but I'll wait for your opinion before giving up entirely.

**Comment by JoostK** [comment]
Given that there's more form field names that would result in issues, I doubt it's worth addressing it for this particular name (`host`). Moreover, there's potentially more cases where shadowing native property names may confuse Angular's DOM interaction logic, and as mentioned before I don't think it's worth it to address this problem.

**Comment by perceptron8** [comment]
So be it. Thanks again!

**Comment by JoostK** [comment]
Thank you for looking into this so thoroughly and extensively!
