### ISSUE TITLE
Duplicating the description

### ISSUE THREAD

**Issue by vladboisa** [angular/angular#57253]
### Describe the problem that you experienced

On [DoBootsrap tab](https://angular.dev/api/core/DoBootstrap?tab=api), the description tab almost the same, with the exception of line with text 
`Reference to the current application is provided as a parameter.
See ["Bootstrapping"](https://angular.dev/guide/ngmodules/bootstrapping).`

### Enter the URL of the topic with the problem

https://angular.dev/api/core/DoBootstrap?tab=api

### Describe what you want to experience that would fix the problem

In my opinion this is a little confusing, and it makes sense to add this line to the description without an additional tab

**Comment by JeanMeche** [comment]
This is the "expected" behavior. 

The description you're seeing is the first paragraph of the `@description` block. 

In some cases like `DoBootstrap`, the following paragraph is very short, which gives the impression of duplicated.
