### ISSUE TITLE
Solicitud para añadir un comando de renombrado de componentes en Angular CLI

### ISSUE THREAD

**Issue by rey9606** [angular/angular#57254]
### Description

Actualmente, Angular CLI no proporciona un comando específico para renombrar componentes, lo que puede ser una tarea engorrosa, especialmente en proyectos grandes. Renombrar un componente implica cambiar los nombres de archivos, actualizar las referencias en otros archivos, modificar las importaciones y, en general, realizar una serie de cambios manuales que pueden ser propensos a errores.

Para mejorar la eficiencia del desarrollo y reducir la posibilidad de errores durante el renombrado de componentes, solicito la implementación de un nuevo comando en Angular CLI que facilite este proceso. El comando debería realizar las siguientes acciones:

Renombrar Archivos: Cambiar los nombres de los archivos del componente (por ejemplo, old-name.component.ts a new-name.component.ts).

Actualizar Referencias: Modificar las importaciones y declaraciones del componente en los archivos de módulo (app.module.ts, otros módulos) y en las rutas (app-routing.module.ts, otros módulos de rutas).

Actualizar Selectores y Clases: Ajustar el nombre de la clase del componente y el selector en el archivo TypeScript del componente.

Actualizar Archivos de Prueba: Cambiar el nombre del componente en los archivos de prueba (*.spec.ts), si es necesario.

### Proposed solution

Comportamiento Esperado:

Un comando de Angular CLI como ng rename podría ser utilizado de la siguiente manera:

bash
Copiar código
ng rename component old-name new-name
Este comando debería:

Renombrar los archivos del componente.
Actualizar todas las referencias al componente en los archivos relevantes.
Ajustar el nombre de la clase y el selector en el archivo del componente.
Modificar las referencias en los archivos de prueba, si están presentes.

Ejemplo de Implementación:

Ejecutar el comando:

bash
Copiar código
ng rename component old-name new-name
Acciones realizadas por el comando:

Renombrar old-name.component.ts a new-name.component.ts
Actualizar old-name.component.html a new-name.component.html
Actualizar old-name.component.css a new-name.component.css
Cambiar todas las referencias en app.module.ts, app-routing.module.ts, y otros módulos o rutas que utilicen el componente old-name.
Actualizar el nombre de la clase y el selector en new-name.component.ts
Modificar los archivos de prueba, si existen.
Beneficios:

Reducción del riesgo de errores al renombrar componentes.
Ahorro de tiempo y esfuerzo en la gestión de cambios.
Mejora en la coherencia y mantenimiento del código en proyectos grandes.

### Alternatives considered

Notas Adicionales:

Este comando sería particularmente útil para equipos de desarrollo que trabajan en proyectos grandes o en mantenimiento de aplicaciones existentes, y que a menudo necesitan renombrar componentes como parte del proceso de refactorización.

Gracias por considerar esta solicitud. Espero que esta funcionalidad pueda ser incorporada en futuras versiones de Angular CLI para mejorar la experiencia del desarrollo.

**Comment by JeanMeche** [comment]
Hi, we only accept issues written in english. 
Feel free to open a new one in english.
