### ISSUE TITLE
upgrade typescript to 1.7.3

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#5725]
- [x] requires ts2dart to be upgraded: https://github.com/angular/ts2dart/issues/312
- [x] broccoli-typescript plugin needs a small tweak (config parsing)
- [x] hopefull dgeni will keep on working

// @alexeagle @petebacondarwin

**Comment by petebacondarwin** [comment]
I have upgrade the angular.io project to use 1.7.3 - see https://github.com/angular/angular.io/commit/326e1f73951e685ae0422749b3d2149afa88d64a

**Comment by IgorMinar** [comment]
Thanks!

**Comment by IgorMinar** [comment]
new type errors discovered during upgrade:

- [ ]  angular2/src/compiler/selector.ts (195, 9): Type 'SelectorMatcher' is not assignable to type 'this'.
- [ ]  angular2/src/compiler/selector.ts (206, 11): Type 'SelectorMatcher' is not assignable to type 'this'.
- [ ]  angular2/src/compiler/selector.ts (231, 11): Type 'SelectorMatcher' is not assignable to type 'this'.
- [ ]  angular2/src/core/di/injector.ts (941, 9): Type 'Injector' is not assignable to type 'this'.
- [ ]  angular2/src/core/di/injector.ts (952, 9): Type 'Injector' is not assignable to type 'this'.
- [ ]  angular2/src/core/di/injector.ts (972, 7): Type 'Injector' is not assignable to type 'this'.
- [ ]  angular2/src/core/di/injector.ts (980, 7): Type 'Injector' is not assignable to type 'this'.
- [ ]  angular2/src/core/linker/element_injector.ts (577, 7): Type 'ElementInjector' is not assignable to type 'this'.
- [ ]  angular2/src/facade/browser.ts (11, 22): Block-scoped variable 'Event' used before its declaration.
- [ ]  angular2/src/facade/browser.ts (12, 27): Block-scoped variable 'MouseEvent' used before its declaration.
- [ ]  angular2/src/facade/browser.ts (13, 30): Block-scoped variable 'KeyboardEvent' used before its declaration.
- [ ]  angular2/src/facade/browser.ts (14, 28): Block-scoped variable 'EventTarget' used before its declaration.
- [ ]  angular2/src/facade/browser.ts (15, 24): Block-scoped variable 'History' used before its declaration.
- [ ]  angular2/src/facade/browser.ts (16, 25): Block-scoped variable 'Location' used before its declaration.
- [ ]  angular2/src/facade/browser.ts (17, 30): Block-scoped variable 'EventListener' used before its declaration.
- [ ]  angular2/src/router/router.ts (121, 7): Type 'Router' is not assignable to type 'this'.
- [ ]  angular2/src/router/router.ts (388, 7): Type 'Router' is not assignable to type 'this'.

**Comment by IgorMinar** [comment]
fixed by #5758
