### ISSUE TITLE
[Zone.js] `it.failing` and `test.failing` seem to be not patched for `Jest`

### ISSUE THREAD

**Issue by ahnpnl** [angular/angular#57277]
### Which @angular/* package(s) are the source of the bug?

zone.js

### Is this a regression?

No

### Description

Original reported here https://github.com/thymikee/jest-preset-angular/issues/2672

Quoted by issue author:

> It looks like this issue is caused by [Zone.js](https://github.com/angular/angular/tree/main/packages/zone.js) not supporting the modifier. This is supported by the fact that the test suite runs as expected when commenting out require('zone.js/testing') in jest-preset-angular/setup-jest.js.

### Please provide a link to a minimal reproduction of the bug

https://github.com/marcelhohn/jest-playground

### Please provide the exception or error you saw

```true
TypeError: it.failing is not a function .
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.1.3
Node: 22.5.1
Package Manager: yarn 4.4.0
OS: darwin arm64

Angular: 18.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1801.3
@angular-devkit/build-angular   18.1.3
@angular-devkit/core            18.1.3
@angular-devkit/schematics      18.1.3
@schematics/angular             18.1.3
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10
```

### Anything else?

Please check full details at https://github.com/thymikee/jest-preset-angular/issues/2672

**Comment by JeanMeche** [comment]
#57280 contains the fix, before opening the PR for review I want to make sure there aren't other functions that don't work. 

Could you double check ? thanks !

**Comment by ahnpnl** [comment]
> #57280 contains the fix, before opening the PR for review I want to make sure there aren't other functions that don't work.
> 
> Could you double check ? thanks !

Thanks, that works for me 👍
