### ISSUE TITLE
the constructor and ngOnInit are not being invoked when navigating back from an external URL in case of deploying or serving the app on subdomain

### ISSUE THREAD

**Issue by EsmailElturky** [angular/angular#57289]
### Which @angular/* package(s) are the source of the bug?

common, core, forms, localize, router

### Is this a regression?

Yes

### Description

the constructor and ngOnInit are not being invoked when navigating back from an external URL in case of deploying or serving the app on subdomain

i have revisited this issue
https://github.com/angular/angular/issues/26829
i see it closed but didn't find the solution in comments

**Comment by thePunderWoman** [comment]
@EsmailElturky Can you create a minimal reproduction for us? Otherwise there's not much actionable here.

**Comment by tolgatopkara** [comment]
my current app has a route like
https://example.example.example.com/auth/login
i have no issue like this

**Comment by EsmailElturky** [comment]
to reproduce the issue ,
after serving the app in your localhost try to use ngrok run your port using this command
 ngrok http 4200 --host-header=rewrite
 and will give you a live url {with subdomain) to your local 
 like this
 https://bb24-41-40-92-229.ngrok-free.app/survey/submit/9Ypw0hPU/vPSjTnMwu4
 and now you can easily navigate out to your app and come back 
 check constructor function will not invoked or not 
 i use angular 13

**Comment by JoostK** [comment]
This is likely [bfcache](https://web.dev/articles/bfcache) at work, where a prior page is resumed instead of reopened entirely.

**Comment by EsmailElturky** [comment]
> This is likely [bfcache](https://web.dev/articles/bfcache) at work, where a prior page is resumed instead of reopened entirely.

@JoostK 
but the problem only appear in subdomain url and if there is no subdomain the angular reinitialize the component and execute constructor as usual

**Comment by EsmailElturky** [comment]
i finnaly find the solution depending on https://web.dev/articles/bfcache 
@JoostK 
thanks for your refer
here is the solution 
    this.initializeComponent();
    // Handle bfcache restores, The pageshow event is fired when the page is shown, including when it is restored from the bfcache
    this.pageShowListener = this.renderer.listen('window', 'pageshow', (event) => {
      if (event.persisted) {
        this.initializeComponent()
      }
    });
