### ISSUE TITLE
Force rendering deferred elements

### ISSUE THREAD

**Issue by csutorasr** [angular/angular#57290]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

During SSR sometimes the whole content is needed to be rendered. For scrapers it better to have the full content and for users it is better to use the `@defer`.

Some services also require the whole content like third-party SEO tools.

Tests may use this solution if the developer wants to test the component with every defer rendered. (It would make the tests simpler than writing showing all the deferred views.)

### Proposed solution

Add a new value `Force` to the `DeferBlockBehavior` to force loading all the deferred elements. Then providing the `DEFER_BLOCK_CONFIG` this value can be overridden by the SSR provider.

Update the logic in this file to handle the new values. The shouldRender would return true, and the render function is called instantly in every `ɵɵdefer*` function.

https://github.com/angular/angular/blob/7919982063e7638ffabe2127d4803bb930c791bc/packages/core/src/defer/instructions.ts#L1029-L1035

The SSR should wait until the views are loaded. I don't know if that needs any additional work.

### Alternatives considered

Rendering the page with a browser or write a component without `@defer`.

**Comment by alxhub** [comment]
Rendering defer blocks in the SSR context is tricky, because it forces the client to do an extra lazy loading step during the hydration process. The intent of defer is to move loading _out_ of the critical rendering path, so this would be directly against that intent.

Instead, we're building out support for _partial hydration_ of `@defer` blocks, where they would render on the server but remain dehydrated until a specific `hydrate` condition is met (which can be `hydrate on idle`).

**Comment by csutorasr** [comment]
What about resolving the issue in two steps? Initially resolve forcing the render, which will cause a mismatch during the hydration, and every element will be recreated (if it is used by only crawlers then this is not a problem). Then add a functionality for the hydration.

This way the function can be in developer preview until the hydration part is ready and then add hydration until the feature is fully ready.

If you agree I would start to work on a PR.

**Comment by thePunderWoman** [comment]
@csutorasr We just opened our [RFC on incremental / partial hydration](https://github.com/angular/angular/discussions/57664), which specifically discusses rendering defer blocks in SSR. Please go take a look and leave your feedback.
