### ISSUE TITLE
running ./scripts/ci/build_dart.sh fails locally

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#5729]
```
+ typed_data 1.1.1
+ utf 0.9.0+2
+ watcher 0.9.7
+ when 0.2.0
+ which 0.1.3
+ yaml 2.1.7
Creation failed, path = '/Users/iminar/homebrew/bin/dart' (OS Error: File exists, errno = 17)
[22:26:09] '!pubget.angular2_testing.dart' errored after 5.63 s
[22:26:09] Error: 1
```

both @matsko and me were hit by this and have no clue what's going on. it seems to be caused by `./scripts/env_dart.sh` doing something fishy, but that might be red herring.

**Comment by kevmoo** [comment]
Which version of Dart are you using?

**Comment by IgorMinar** [comment]
Dart VM version: 1.13.0 (Wed Nov 18 12:15:29 2015) on "macos_x64"

**Comment by yjbanov** [comment]
If I were to guess, I'd guess that your `DART_SDK` environment variable was busted. `env_dart.sh` does not redefine it if it's already defined.
