### ISSUE TITLE
Parameter "callback" in afterRender and afterNextRender has incomplete type

### ISSUE THREAD

**Issue by lukasmatta** [angular/angular#57305]
It's a bit confusing that in the documentation, `callback` parameter has type `VoidFunction`, but the function also accepts an object with phase properties. Not sure if the problem is in the docs generation mechanism, or in the declarations of those functions.

https://angular.dev/api/core/afterRender?tab=api
https://angular.dev/api/core/afterNextRender?tab=api

**Comment by JeanMeche** [comment]
This is a doc issue, we're not displaying the different overloads the function has. 
It's already addressed by #57255.
