### ISSUE TITLE
controlgroup.valueChange not firing anymore when input[text] is cleared by protractor

### ISSUE THREAD

**Issue by Sabartius** [angular/angular#5730]
Hey,

since the Merge of #5401 it's harder to test angular2-applications with protractor. Before you could clear an input-field[text] with webelement.clear() & webelement.sendKeys("") and form.valueChange would fire with the change. Since the PR the valueChange is not firing anymore.
Now the only way to clear an input[text] is to send BACKSPACEs, which isn't very convenient.

**Comment by DzmitryShylovich** [comment]
Is this still relevant after final?

**Comment by vikerman** [comment]
Obsolete
