### ISSUE TITLE
Raw Markdown visible instead of working links at guide/http

### ISSUE THREAD

**Issue by Nikovic** [angular/angular#57328]
### Describe the problem that you experienced

At https://angular.dev/guide/http#http-client-service-features, the raw markdown link syntax (`[display name](url)`) is shown instead of translated (html-ified) links

### Enter the URL of the topic with the problem

https://angular.dev/guide/http#http-client-service-features

**Comment by JeanMeche** [comment]
#57319 introduced regressions when updatating to marked v14. 
Those have been reported to the upstream repo already see : markedjs/marked#3389
