### ISSUE TITLE
Allow lazy initial value to signal input

### ISSUE THREAD

**Issue by Harpush** [angular/angular#57322]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Currently inputs can only accept default values up front. If for some reason the default value is heavier it still gets evaluated even if an input value was bound.

### Proposed solution

Allow passing a function as default value that will only get invoked when there is no bound input (cached later probably).
For example:
```ts
one = input(() => 2);
```

### Alternatives considered

Using a computed this can be achieved right now:
```ts
_one = input<number | undefined>(undefined, {alias: 'one'});
one = computed(() => this._one() ?? 2);
```

**Comment by pkozlowski-opensource** [comment]
It is an interesting case. My first thought is that it is relatively uncommon such that `computed` is sufficient answer. Will keep it open for a bit to see if there are other opinions.

**Comment by pkozlowski-opensource** [comment]
Discussing this more with the team - let's use computed for now.
