### ISSUE TITLE
angular.dev usage notes duplicated in signature cards

### ISSUE THREAD

**Issue by devversion** [angular/angular#57339]
### Describe the problem that you experienced

Previously, usage notes were only shown in the `Usage Notes` tab, but now they appear in the tab, plus in the reference signature card on the side— where this information shouldn't be exposed again; and be kept short.

### Enter the URL of the topic with the problem

https://angular.dev/api/core/output

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/user-attachments/assets/ce10cd8b-fe5f-48b1-9c54-cd782d9e510c)

**Comment by JeanMeche** [comment]
It's a side effect of implementing #55196. I'll make sure to only show usages for methods.
