### ISSUE TITLE
JS objects rendered incorrectly in docs

### ISSUE THREAD

**Issue by BigGillyStyle** [angular/angular#57333]
### Describe the problem that you experienced

I was reading the https://angular.dev/api/core/afterRender?tab=description page, and saw the text:

> Note that the callback will run
>
>     [object Object],[object Object],[object Object],[object Object]

### Enter the URL of the topic with the problem

https://angular.dev/api/core/afterRender?tab=description

### Describe what you were looking for in the documentation

I was looking for how to use the `afterRender` callback

**Comment by JeanMeche** [comment]
Hi, thanks for the report, I'll close this as a dupe of #57328, those are all regressions linked to a marked update.
