### ISSUE TITLE
Nested Control flow with targeted content projection

### ISSUE THREAD

**Issue by kreuzerk** [angular/angular#57345]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

There's an issue when using the new control flow syntax to nest content into a specific slot (one that utilizes `select`).

Let's say we have a simple component that displays `h1` elements.

```typescript
@Component({
  standalone: true,
  selector: 'container',
  template: `
   <ng-content select="h1"/>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ContainerComponent {}
```

Now le'ts project some h1 elements with different approaches:

1. Projecting elements using new @for control flow - ✅ Elements get rendered 
```html
@for(item of items; track $index){
  <h1>{{ item }}</h1>
}
```

2. Projecting elements using new @for control flow wrapped inside an @if - ❌ No Elements get rendered 
```html
@if(someCondition()){
 @for(item of items; track $index){
  <h1>{{ item }}</h1>
 }
}
```

3. Projecting elements using structural ngFor wrapped inside an @if - ✅ Elements get rendered 
```html
@if(someCondition()){
  <h1 *ngFor="let item of items">{{ item }}</h1>
}
```

I created the following stack blitz with a reprod: https://stackblitz.com/edit/stackblitz-starters-8ct4hs?file=src%2Fmain.ts

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-8ct4hs?file=src%2Fmain.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular: 18.1.4
```

**Comment by JoostK** [comment]
This is working as designed; more discussion in #54035.
