### ISSUE TITLE
Web Worker bundle size

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#5735]
As of today there are 2 WebWorker-related bundles in the System.register format with the respective size (gzipped): 
* ui.dev.js: 225 735 bytes
* worker.dev.js 317 560

From @jteplitz602 [comment](https://github.com/angular/angular/pull/5664#issuecomment-162699217):

> ui.dev.js is currently a script that is intended to run standalone on the ui thread (without also loading ng2). The idea is that ui.dev.js will contain only the parts of ng2 absolutely necessary to be loaded on the ui and that worker.dev.js will contain everything you need on the worker thread and nothing that can't be loaded in a worker.

Based on the above ui.dev.js should be quite minimal, but in practice its size is close to the entire angular2 bundle (245 729 bytes). 

@jteplitz602 could you please verify if we indeed add only a minimal part? Or maybe those bundles are optimized already?
cc: @IgorMinar to decide if we need this for beta.0

**Comment by jteplitz602** [comment]
In theory we should only need a minimal part of angular in the ui bundle,
but it looks like everything is getting pulled in. I haven't looked into
what's pulling in so much though. I can investigate later this week / early
next week.

**Comment by pkozlowski-opensource** [comment]
This should be covered by #6750
