### ISSUE TITLE
Trying to use Observable.from, exported from rxjs/observable, with no luck

### ISSUE THREAD

**Issue by vladimir-ivanov** [angular/angular#5736]
seems to be related to #5283?

this code used to work 

import from 'angular2/angular2';
Observable.from([
            new Response(new ResponseOptions({
                body: {
                    message: "color:red"
                }
            }))
]);

now after an upgrade to alpha-0.0.50, it stopped working (from 0.0.46).

Observable from angular2 seems to be trimmed down as in  #5283.
But would expect the code below still to work as it is not part of angular2:

import from 'rxjs/observable';
Observable.from([
            new Response(new ResponseOptions({
                body: {
                    message: "color:red"
                }
            }))
]);

**Comment by ericmartinezr** [comment]
```
import 'rxjs/add/observable/from';
```
Alpha 50 uses RxJS alpha 14. So you should map it to `rxjs/add/(observable|operator)/***`. Make sure to add the config necessary in your system.config.

**Comment by vladimir-ivanov** [comment]
thank you, makes sense now
