### ISSUE TITLE
Webworker Documentation crashes tab on Chromium browsers

### ISSUE THREAD

**Issue by Obstbeeren** [angular/angular#57361]
### Describe the problem that you experienced

When visiting https://angular.dev/ecosystem/web-workers directly, the tab crashes in Edge, Chrome and Brave with `STATUS_BREAKPOINT`. I have also tried it on my phone with Brave.

This does not occur on Firefox.

### Enter the URL of the topic with the problem

https://angular.dev/ecosystem/web-workers

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/user-attachments/assets/f9c9d247-be43-4cb2-a907-b18ad2500c5e)
![image](https://github.com/user-attachments/assets/bb6b3b64-11d0-4aa4-850a-e182b786bdd9)

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
Brave: Version 1.68.137 Chromium: 127.0.6533.100
Chrome: Version 127.0.6533.100 (Official Build) (64-bit)
```

**Comment by JeanMeche** [comment]
Hi, this is a chromium crash, this not actionable on our site.

**Comment by JeanMeche** [comment]
All the browsers you mentionned are based on the Chromium browser. 
I can confirm that I reproduce the issue too.
