### ISSUE TITLE
`HttpInterceptorFn` Usage Notes Not Working Without Modifications

### ISSUE THREAD

**Issue by xDivisionByZerox** [angular/angular#57370]
### Describe the problem that you experienced

The the first codeblock from the usage notes of the `HttpInterceptorFn` type do not work out of the box.

https://github.com/angular/angular/blob/d608b857c689d17a7ffa33bbb510301014d24a17/packages/common/http/src/interceptor.ts#L109-L115

The variable with the name `modifiedReq` is handed to the http handler function, but it doesn't exist in this context. 

### Enter the URL of the topic with the problem

https://angular.dev/api/common/http/HttpInterceptorFn?tab=usage-notes

### Describe what you were looking for in the documentation

The usage note should work without extra modification.

### Describe the actions that led you to experience the problem

The variable  `modifiedReq` should be changed to `req`, which is the function parameter in this context.

### Provide any additional information here in as much as detail as you can

```true
I would be willing to provide a PR to fix the issue, if that helps.
```

**Comment by JeanMeche** [comment]
Hi, this is a doc infra issue and is pending deployment on our side.
