### ISSUE TITLE
The links styles on the roadmap page are not being rendered correctly.

### ISSUE THREAD

**Issue by rafaelblink** [angular/angular#57378]
### Describe the problem that you experienced

Looks like links with dots are not being rendered correctly from markdown.

<img width="855" alt="image" src="https://github.com/user-attachments/assets/1260b515-19fd-4402-b1a8-ee3fcabcd335">

### Enter the URL of the topic with the problem

https://angular.dev/roadmap

**Comment by JeanMeche** [comment]
Thanks for reporting this issue, this is fixed and pending deployment on our side !
