### ISSUE TITLE
Issue with contentChild of reprojected content

### ISSUE THREAD

**Issue by PasNinii** [angular/angular#57373]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Trying to use content projection and content projection of content projection (reprojection) I stumble upon a question that I think is an issue when using `contentChild`

I created two components in which I project content using `ng-content` and associated directives to access them

## Reprojection component
```ts
@Component({
  standalone: true,
  selector: 'reprojection-component',
  imports: [ReprojectionDirective, JsonPipe],
  template: `
    <h2>Reprojection Component</h2>
    <p>{{ reprojectionContentChild() | json }}<p>
    <p><ng-content select="reprojection" /></p>
  `,
})
export class ReprojectionComponent {
  public readonly reprojectionContentChild = contentChild(
    ReprojectionDirective
  );
}
```

## Projection component
```ts
@Component({
  standalone: true,
  selector: `projection-component`,
  imports: [ProjectionDirective, ReprojectionDirective, ReprojectionComponent, JsonPipe],
  template: `
    <h2>Projection Component</h2>
    <p>{{ projectionContentChild() | json }}<p>
    <p>{{ reprojectionContentChild() | json }}<p>

    <ng-content select="projection" />

    <reprojection-component>
      <ng-content select="reprojection" ngProjectAs="reprojection" />
    </reprojection-component>
  `,
})
export class ProjectionComponent {
  projectionContentChild = contentChild(ProjectionDirective);
  reprojectionContentChild = contentChild(ReprojectionDirective);
}
```

## Directives projection and reprojection
```ts
@Directive({
  standalone: true,
  selector: `projection`,
})
export class ProjectionDirective {
  public readonly title = 'projection-directive';
}

@Directive({
  standalone: true,
  selector: `reprojection`,
})
export class ReprojectionDirective {
  public readonly title = 'reprojection-directive';
}
```

## Main component
```ts
@Component({
  selector: 'app-root',
  standalone: true,
  imports: [Projection, ProjectionDirective, ReprojectionDirective],
  template: `
    <projection-component>
      <projection>Projection</projection>
      <reprojection>ReprojectionComponent</reprojection>
    </projection-component>
  `,
})
export class App {}
```

## ts
My issue is that it seems that `contentChild` either for projected or reprojected content seems to be enable only in `ProjectionComponent`. But from my understanding 

- `<projection>...</projection>`, `contentChild` should work in `ProjectionComponent` for this
- `<reprojection>...</reprojection>`, `contentChild` should work in `ReprojectionComponent` for this

However as you can see on screen below, only `ProjectionComponent` has access to both projected content using `contentChild`

![image](https://github.com/user-attachments/assets/0b0dbaee-0c50-47a8-8b79-2acb9cbc87c5)

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-47lfxu?file=src%2Fmain.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular cli: ^18.0.1
Node: 18.20.3
Package manager: npm 10.2.3
OS: Ubuntu 20.04 LTS
```

**Comment by JoostK** [comment]
This is known limitation of content projection, but the current behavior is as designed. Please see #16299,
