### ISSUE TITLE
ADEV: incorrect rendering of lists in API symbol docs

### ISSUE THREAD

**Issue by AndrewKushnir** [angular/angular#57381]
### Describe the problem that you experienced

Lists of items in an API symbol description are not rendered correctly, for example:

<img width="898" alt="provide-client-hydration-doc-issue" src="https://github.com/user-attachments/assets/55f409f2-f7f8-4c86-9254-1ad236f6e2f2">

### Enter the URL of the topic with the problem

https://angular.dev/api/platform-browser/provideClientHydration

**Comment by JeanMeche** [comment]
This is already fixed and pending deployement with 18.2 release. 

https://next.angular.dev/api/platform-browser/provideClientHydration

**Comment by AndrewKushnir** [comment]
@JeanMeche thanks for the reply 👍 

Quick question: do we also have a fix for rendering of links (I see `{@link withHttpTransferCacheOptions} to configure some HTTP transfer cache options` on that page) or should I create a new ticket?

**Comment by JeanMeche** [comment]
Oh good catch, this is a separate issue. #57344 will take care of it.
