### ISSUE TITLE
Remove "upgrade" barrel from angular2/angular2 bundle

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#5739]
(Even putting aside the fact that angular2/angular2 goes away as a namespace we need to agree on content of the corresponding bundle)

As of today `angular2/angular2` exports the `upgrade` barrel but discussing with @IgorMinar it looks like it should go away from a corresponding System.register bundle. The only alternative for ngUpgrade users is to use UMD bundles (angular2.umd.js)

This would be a breaking change for people that tried to use ngUpgrade with SystemJS loader and the current System.register bundles.

cc:// @wardbell @teropa @PascalPrecht - from our previous chat it looked like you've been teaching upgrade with SystemJS loader and TypeScript and not with ES5. If this is the case please speak up :-)

**Comment by teropa** [comment]
Yes, this is the case. At least in the TypeScript edition we import upgrade from `angular2/upgrade`, after loading `angular2.dev.js`.

How is this going to change now?

**Comment by pkozlowski-opensource** [comment]
@teropa so if I resolve this issue it would go away from the `angular2.dev.js` bundle. And since we don't publish `upgrade` as part of any other System.register bundle you pretty much wouldn't be able to load it through SystemJS. Unless we create a separate bundle for it, of course!

I guess the main question here is this: do we want ngUpgrade users to use SystemJS + TypeScript? If so we need to either keep `angular2/upgrade` as part of the `angular2.dev.js` bundle (not big fan of this, as it adds bytes for everyone) or publish a separate `upgrade.dev.js` bundle.

**Comment by IgorMinar** [comment]
Upgrade should be also published as a separate system register bundle. That
should solve this

**Comment by PascalPrecht** [comment]
I'd vote for publishing a separate bundle

**Comment by teropa** [comment]
I like that idea too.

**Comment by pkozlowski-opensource** [comment]
OK, a separate bundle then! Will need to clean-up its dependencies first as from my quick look it seems like there are some imports from angular2/angular2 in there (cycles!)

**Comment by pkozlowski-opensource** [comment]
This is covered in #5854
