### ISSUE TITLE
Benchmarks should track app build times

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#574]
The implementation of transformers could affect the build time of an application, which influences developer productivity. We should track that.

**Comment by TedSander** [comment]
I have a request from the dart team to provide instrumentation for pub/transformers. They agreed so we should have something that we could leverage for angular2.

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.
