### ISSUE TITLE
apache server .htaccess configuration not working when setting sourceMap to true

### ISSUE THREAD

**Issue by JSmithOner** [angular/angular#57404]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

when I set `sourceMap`to true into my `angular.json`file the .htaccess configuration is not working on an apache server. This happen when I try to connect to any route except base route and happens on refresh.

### Please provide the exception or error you saw

```true
Not Found

The requested URL was not found on this server.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.1.2
Node: 18.19.0
Package Manager: npm 10.2.3
OS: darwin arm64

Angular: 18.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1801.2
@angular-devkit/build-angular   18.1.2
@angular-devkit/core            18.1.2
@angular-devkit/schematics      18.1.2
@schematics/angular             18.1.2
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.8
```

**Comment by JeanMeche** [comment]
Hi, may you give some more details, without them this isn't actionable to us.

**Comment by JSmithOner** [comment]
@JeanMeche I can't give more details, I have a pretty simple app with routes.
when setting the sourceMap to true here:

          "configurations": {
            "production": {
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "500kB",
                  "maximumError": "2MB"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "2kB",
                  "maximumError": "8kB"
                }
              ],
              "outputHashing": "all",
              "sourceMap": true
            },
            "development": {
              "optimization": false,
              "extractLicenses": false,
              "sourceMap": true
            }
          },

when I try to connect to a route let's say `mywebsite/login` directly I get an error saying 

> Not Found
> 
> The requested URL was not found on this server.

if I connect to `mywebsite.com` and add a route guard that redirects to `/login` then it works.
I can't access any url from my website except if it's the root `/`.
what would you like to know more, I've said pretty much all of what I've noticed and could help debug

**Comment by JSmithOner** [comment]
@JeanMeche Ho sorry I've added it to stackoverflow but not github.
I've tried many configurations but here is the current one

```
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.html$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.html [L]
</IfModule>
```

**Comment by alxhub** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`, or consider asking in the [Angular Community Discord](https://discord.com/invite/angular).

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).
