### ISSUE TITLE
Router recognition behaviour

### ISSUE THREAD

**Issue by tbragaf** [angular/angular#5740]
Hi all!

In the following resource, I have an App component (with router) and 2 other components (Home and Login). My problem is explained right after the link.
http://plnkr.co/edit/rPSR0fnPDreuT93LPyWz?p=preview

* Home and Login components can't recognize 'home' path.You can check the console, or simply the HTML rendered.
* BUT I can navigate from Home to Login using navigateByUrl method?

Why is the instance of the Router injected on Home and Login components a ``` ChildRouter ``` and not a ``` RootRouter ```, just like the App component?

Best regards,
tbragaf

**Comment by tbragaf** [comment]
Updated version to beta-0 but now it is also throwing an "-----async gap-----" error:
- http://plnkr.co/edit/OVnX7jyatDgnFodAO6HO?p=preview

**Comment by vsavkin** [comment]
We are no longer maintaining the deprecated router to focus our efforts on making the new router solid.

Could you reproduce the problem using the new router and submit a separate issue?

Closing this issue.
