### ISSUE TITLE
provideExperimentalZonelessChangeDetection not working

### ISSUE THREAD

**Issue by muhamedkarajic** [angular/angular#57412]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

Can someone help me configure the zoneless change detection. 

```ts
import { enableProdMode, isDevMode, provideExperimentalZonelessChangeDetection } from "@angular/core";
import { platformBrowserDynamic } from "@angular/platform-browser-dynamic";
import { AppModule } from './app/app.module';

const providers: any[] = [
  provideExperimentalZonelessChangeDetection(),
];

if (!isDevMode()) {
  enableProdMode();
}

platformBrowserDynamic(providers)
  .bootstrapModule(AppModule)
  .catch(err => console.error(err));
```

When I keep zone.js in polyfills then it works. I also have @angular/localize/init in polyfills.

### Please provide the exception or error you saw

```true
I have following error:
Error: NG0908: In this configuration Angular requires Zone.js
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.1.0
Node: 18.20.0
Package Manager: npm 10.5.0
OS: darwin arm64

Angular: 18.1.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, material
... platform-browser, platform-browser-dynamic, platform-server
... pwa, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1801.0
@angular-devkit/build-angular   18.1.0
@angular-devkit/core            18.1.0
@angular-devkit/schematics      18.1.0
@schematics/angular             18.0.5
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.4
```

### Anything else?

I believe the solution is to use standalone components. Then it worked but I commented out everything else in my code so I'm not 100% sure.

**Comment by atscott** [comment]
The providers in `platformBrowserDynamic` are platform providers. You need to add the provider to the providers of your app module, as documented here: https://angular.dev/guide/experimental/zoneless#enabling-zoneless-in-an-application

**Comment by muhamedkarajic** [comment]
> The providers in `platformBrowserDynamic` are platform providers. You need to add the provider to the providers of your app module, as documented here: https://angular.dev/guide/experimental/zoneless#enabling-zoneless-in-an-application

I tried that as well and got the same error.

**Comment by atscott** [comment]
prior to 18.2, you also need ngZone: ‘noop’ in the bootstrap options.

**Comment by muhamedkarajic** [comment]
FYI: The noop approach was not the solution, it was starnge when it runned. The right approach was to really update to 18.2. and to put the provideExperimentalZonelessChangeDetection inside the NgModule not inside the main.ts - to be fair as its writen in the documentation. Hope this helps someone.

**Comment by muhamedkarajic** [comment]
@spock123 I think you are interested in this as well.

**Comment by spock123** [comment]
> FYI: The noop approach was not the solution, it was starnge when it runned. The right approach was to really update to 18.2. and to put the provideExperimentalZonelessChangeDetection inside the NgModule not inside the main.ts - to be fair as its writen in the documentation. Hope this helps someone.

So if you don't use modules at all, then just upgrade to 18.2 ?
