### ISSUE TITLE
Page https://angular.dev/tutorials/first-app/10-routing/ is not loading.

### ISSUE THREAD

**Issue by DmitryAstapchik** [angular/angular#57426]
### Describe the problem that you experienced

Page https://angular.dev/tutorials/first-app/10-routing/ is not loading after refreshing in browser. The same problem is with other pages of the tutorial. I tried several browsers on different machines. 2 screenshots are made.
![2024-08-16 161214](https://github.com/user-attachments/assets/d6687e54-f7a8-41cf-9572-04c2dc39fad6)
![2024-08-16 161550](https://github.com/user-attachments/assets/b3ff7e0e-dfba-4b95-b9f8-03855eb160ee)

**Comment by JeanMeche** [comment]
This is a Chromium bug that only occurs on Chromium browsers, unfortunately there isn't much we can do here.
