### ISSUE TITLE
No error message for a named redirect in Router

### ISSUE THREAD

**Issue by tbragaf** [angular/angular#5742]
Hi all!

I think I found a problem with router navigation useAsDefault.
If I use a ``` ChildRouter ``` as a defaultRouter, the redirect inside the child router is not triggered.

You may confirm that with this plunkr: http://plnkr.co/edit/bgSlnKvMeoBJXu0LOon9?p=preview
And it only works if you hit the button.

Best regards,
tbragaf

**Comment by wardbell** [comment]
Confirmed by me as well.

**Comment by tbragaf** [comment]
Updated the plunkr to beta-0
* http://plnkr.co/edit/BWQNjxJOF5EU93Dw7Vny?p=preview

**Comment by wardbell** [comment]
Still not fixed as of beta.2

**Comment by tolemac** [comment]
True, not fixed.

**Comment by wardbell** [comment]
### Update 

I just traced the problem ***in my case*** to a redirect route. It seems that such a route (which does not raise an error) defeats `useAsDefault`.

I stripped down the original example, leaving only the matter of whether there is or is not a redirect route. 

Find it in `AppComponent` in http://plnkr.co/edit/a2AIlRJfMY9jn19txg06?p=preview

**Comment by IgorMinar** [comment]
this issue is now obsolete. please see: https://angularjs.blogspot.com/2016/06/improvements-coming-for-routing-in.html

if the latest version of the router is still affected please open a new issue.
