### ISSUE TITLE
Invalid link

### ISSUE THREAD

**Issue by vladboisa** [angular/angular#57439]
### Describe the problem that you experienced

When i was on the page [withHashLocation](https://angular.dev/api/router/withHashLocation), when i click on the `HashLocationStrategy` it gives 404

### Enter the URL of the topic with the problem

https://angular.dev/api/router/withHashLocation?tab=api

**Comment by JeevanMahesha** [comment]
@JeanMeche the issue has been fixed and the changes have been merged. Can we close this PR?
