### ISSUE TITLE
Malformed structure in component testing scenarios page

### ISSUE THREAD

**Issue by daiscog** [angular/angular#57433]
### Describe the problem that you experienced

Incorrect looking "Query for the" heading and page navigation entry:

<img width="1689" alt="image" src="https://github.com/user-attachments/assets/a0705845-ad0d-4aad-83e8-5651c9adb752">

### Enter the URL of the topic with the problem

https://angular.dev/guide/testing/components-scenarios#query-for-the-h1

**Comment by JeanMeche** [comment]
Hi, this is a dupe of #57384 !
