### ISSUE TITLE
docs: add doc for getters from NgForOfContext

### ISSUE THREAD

**Issue by NsdHSO** [angular/angular#57432]
### Describe the problem that you experienced

I want to have a little description of what return this getters.

### Enter the URL of the topic with the problem

https://github.com/angular/angular/blob/baa125480e10e05959f2041f90df3e1bbf540953/packages/common/src/directives/ng_for_of.ts#L38

**Comment by NsdHSO** [comment]
If it's ok with you, can I take this issue?

**Comment by nesjett** [comment]
It seems to be already documented a bit below the link you share: https://github.com/angular/angular/blob/baa125480e10e05959f2041f90df3e1bbf540953/packages/common/src/directives/ng_for_of.ts#L118

**Comment by JeevanMahesha** [comment]
seems like not only for first getter there's is document underneath the implementation but what @NsdHSO  refer here is to if we have the documentation on top of each getter will add much more value. even my thought is also same, @JeanMeche I will work on this and raise the PR and let you know.

**Comment by JeevanMahesha** [comment]
PR : https://github.com/angular/angular/pull/57619

**Comment by elgui1886** [comment]
Still valid?
