### ISSUE TITLE
ng.bootstrap ES5 application in Alpha 50

### ISSUE THREAD

**Issue by kylecordes** [angular/angular#5743]
I'm having trouble making an ES5 application start with Alpha 50. I see the reorganization of "ng", the information about SFX->UMD in the changelog. I found that ng.Component moved to ng.core.Component, and so on.

But where did ng.bootstrap() go? It does not appear to be published as bootstrap(), ng.bootstrap(), ng.core.bootstrap(), ng.common.bootstrap(), or anywhere else I could spot. I look through the test suite and didn't see any ES5 lists (maybe I missed them?) to see how they bootstrap. I didn't see anything relevant in the changelog.

**Comment by ericmartinezr** [comment]
@kylecordes try with `ng.platform.browser.bootstrap()`

**Comment by pkozlowski-opensource** [comment]
@ericmartinezr is spot on (as always!). Thnx so much for helping out with the issues and answerring all the questions on gitter @ericmartinezr - this is very, very much appreciated!

**Comment by kylecordes** [comment]
Thanks. This name seems rather verbose - is this intended as the final name? Or just temporary as the alpha issues are worked through?
