### ISSUE TITLE
Control flow @error for async pipe

### ISSUE THREAD

**Issue by Alextremeee** [angular/angular#57449]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

The async pipe provides a clean way to write reactive applications, until it comes to error handling with them. Although this can be handled by creating a separate stream it isn't necessarily very intuitive.

The new control flow has been excellent for creating more ergonomic templates with things like `@empty` for ng-for and `@else` for ng-if, and `@error` (or something similarly named such as `@catch`) could be a useful tool. 

### Proposed solution

Introducing `@error` as part of the normal control flow could be a useful tool for creating reactive applications. The full syntax might be something like:
```
@if ( user$ | async; as user ) {
    <app-user-component [user]="user"><app-user-component>
} @else {
    <app-loading-component></app-loading-component>
} @error {
    <app-error-component></app-error-component>
}
```

### Alternatives considered

Guidelines on async pipe error handling, although this could be end up being far too opinionated.

**Comment by JeanMeche** [comment]
Hi, this is something that has been discussard before, please have a look at #56862, #51941. It basically boils down to #18509.

**Comment by Alextremeee** [comment]
Apologies, I'd found that last one and deemed not sufficiently relevant, but the first one is pretty much a duplicate.
