### ISSUE TITLE
Chrome 127 can not open the "Service Workers / Getting Started" page

### ISSUE THREAD

**Issue by e-oz** [angular/angular#57457]
### Describe the problem that you experienced

<img width="681" alt="Screenshot 2024-08-20 at 09 28 24" src="https://github.com/user-attachments/assets/2b3df577-9385-4837-8617-f3eb82979821">

### Enter the URL of the topic with the problem

https://angular.dev/ecosystem/service-workers/getting-started

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
Chrome 127.0.6533.120 (arm64) macOS 15.0
```

### Provide any additional information here in as much as detail as you can

```true
Works ok in Firefox and Safari.
```

**Comment by JeanMeche** [comment]
The error 5 is a Chromium crash that affects all chromium based browsers, this isn't actionable to us.
