### ISSUE TITLE
ENVIRONMENT_INITIALIZER can resolve as async function

### ISSUE THREAD

**Issue by olegdunkan** [angular/angular#57463]
### Describe the problem that you experienced

[Docs states](https://angular.dev/api/core/ENVIRONMENT_INITIALIZER) that ENVIRONMENT_INITIALIZER can't be async function, but if I use it to execute like async [it does](https://stackblitz.com/edit/stackblitz-starters-87civx?file=src%2Fmain.ts).

### Enter the URL of the topic with the problem

https://angular.dev/api/core/ENVIRONMENT_INITIALIZER

**Comment by JeanMeche** [comment]
You're right, the docs doesn't mention explicitly that async function are support. This should be added. 

When you say 
> Docs states that ENVIRONMENT_INITIALIZER can't be async function

Were you expecting that the type would be someting like `readonly (() => void| readonly (() => Promise<void>` ?

**Comment by JoostK** [comment]
This is subtle, but environment initializers should not be async in the sense that any `Promise` return value **will not be awaited**. Sure they can be async functions; any function signature with `void` as return type can return anything it wants, `void` merely indicates that the caller shall not consume that value in any way, hence it can be anything at all.

**Comment by JeanMeche** [comment]
Per what Joost said.

**Comment by JoostK** [comment]
To add, the docs don't currently state anything about async vs non-async. It may be a good idea to include a note that environment initializers are not awaited and hence _shouldn't_ be async. Still, they can always be implemented as such.

**Comment by olegdunkan** [comment]
@JoostK 

> It may be a good idea to include a note that environment initializers are not awaited and hence shouldn't be async. 

As I understand environment initializers are awaited now, that is why I have written the issue.
In my example "I am init" are outputted after one second.

**Comment by JoostK** [comment]
> @JoostK 
> 
> 
> 
> > It may be a good idea to include a note that environment initializers are not awaited and hence shouldn't be async. 
> 
> 
> 
> As I understand environment initializers are awaited now, that is why I have written the issue.
> 
> In my example "I am init" are outputted after one second but expected no output.

The message being printed is independent from a promise being awaited, promise chains always execute. The important part is that the app will already have been initialized when the message is printed.

**Comment by olegdunkan** [comment]
@JoostK 

what is the purpose of 
> chains always execute

**Comment by olegdunkan** [comment]
@JoostK now I see, angular can't check type at compile time, and docs help us to know what we have to use.
And yes, angular can't prevent us from effects driven by executing async function without awaiting it. 
```
export declare interface ValueSansProvider {
    /**
     * The value to inject.
     */
    useValue: any;
}
```
Thank you!
