### ISSUE TITLE
Unable to generate guard in Angular 18

### ISSUE THREAD

**Issue by siva-kumar-alight** [angular/angular#57467]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

Create a new application in angular successfully and the angular version was 18, when I try to add auth guard using ng generate command throws error as follows.

Schematic input does not validate against the Schema: {"name":"auth","project":"sample-angular","implements":[]}
Errors:

  Data path "/implements" must NOT have fewer than 1 items.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.1.4
Node: 20.16.0
Package Manager: npm 10.8.1
OS: win32 x64

Angular: 18.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1801.4
@angular-devkit/build-angular   18.1.4
@angular-devkit/core            18.1.4
@angular-devkit/schematics      18.1.4
@schematics/angular             18.1.4
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10
```

**Comment by JoostK** [comment]
Hi there! This should have been resolved with 18.2 as this duplicates https://github.com/angular/angular-cli/issues/28189.
