### ISSUE TITLE
Angular compiler ignores tsconfig.json "references" field

### ISSUE THREAD

**Issue by JonathanCabezas** [angular/angular#57483]
### Which @angular/* package(s) are the source of the bug?

compiler-cli, compiler

### Is this a regression?

No

### Description

I have a monorepo repository following this structure:
```
| apps
  | web-app <- The Angular project
    | tsconfig.json <- contains: "references": { "path": "../../packages/shared"};
| packages
  | shared
    | src
      | product.ts <- contains: import { Unit } from "src/conditioning";
      | conditioning.ts
    | tsconfig.json <- contains: "baseUrl": "./"
    | package.json <- ESM module ("types": "module)
```

It seems like `packages/shared/tsconfig.json` is ignored by the Angular compiler although it is referenced in `apps/web-app/tsconfig.json`.

### Please provide the exception or error you saw

```true
`ng serve` and `ng build` fails with `✘ [ERROR] TS2307: Cannot find module 'src/conditioning' or its corresponding type declarations. [plugin angular-compiler]`.

If switching the absolute path to a relative path:
`import { Unit } from "src/conditioning";`

Why does the Angular compiler ignores the referenced `tsconfig.json` from by dependency ?
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.1.2
Node: 20.15.1
Package Manager: pnpm 9.5.0
OS: linux x64

Angular: undefined
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1801.2 (cli-only)
@angular-devkit/core         18.1.2 (cli-only)
@angular-devkit/schematics   18.1.2 (cli-only)
@schematics/angular          18.1.2 (cli-only)
```

**Comment by JoostK** [comment]
Angular doesn't support project references (#37276) so this isn't too surprising. It's not entirely clear what your setup is though, as `src/conditioning` is missing from the structure tree. A minimal reproduction would be helpful from that perspective, although as noted this isn't really supported.

**Comment by JonathanCabezas** [comment]
> Angular doesn't support project references (#37276) so this isn't too surprising. It's not entirely clear what your setup is though, as `src/conditioning` is missing from the structure tree. A minimal reproduction would be helpful from that perspective, although as noted this isn't really supported.

I don't quite have the time to produce an mvce, I expected the solution to my issue quite straight-forward, and it seems so as the feature is just non-existent as you mentioned.

Thanks for your answer, even though I'm very disappointed this isn't supported...
