### ISSUE TITLE
Reactive forms form builder type issue

### ISSUE THREAD

**Issue by Harpush** [angular/angular#57481]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

I created the following type:
```ts
interface TestForm {
  g: FormGroup<{k: FormGroup<{a: FormControl<number>}>}>;
}
```
And later used it in form builder:
```ts
const a = builder.group<TestForm>({
  g: builder.group({})
});
```
Now I would expect autocomplete for `g` inside the builder group function but I get:
![image](https://github.com/user-attachments/assets/b1b47632-daeb-4c12-a2dd-dbf053f1f135)

Using `new FormGroup` directly works as expected

### Please provide a link to a minimal reproduction of the bug

https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgMWiAwhAdjKEA2ANCmgOJ4CuYxqUIAQhcPgCYCmUcAvnAGZ4g4AcgACAQywBzCvjFQA9LzQBnIQG4AUBuA4OvMQGM2cACptlMWoIQa4cSQC4SdchCoAeBAGsnV1x4QxXzRMHDx8dywKEAAjDgA+LkT4zS4tA2wLOBimVg44AF44LDYAd2cGXPYoAAoASgA6LGwAORlZGPw2TQ0MrCyxQuyqjgbJSjB3MwsreJqbO0dh5mqxifmuOo1NtSA

### Please provide the exception or error you saw

```true
As provided in the image above
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Checked on Angular 17+
```

**Comment by JoostK** [comment]
I don't understand; the `g` group is already present so you get suggestions for the `k` group, as expected.

**Comment by Harpush** [comment]
> I don't understand; the `g` group is already present so you get suggestions for the `k` group, as expected.

`k` is a form group with control `a` but the suggestion is unknown. When trying to build the form group there is no autocomplete for `a`

**Comment by dylhunn** [comment]
I'm a bit confused by this report. You are *already* inside the value corresponding to key `g`, which should be an inner group with key `k`. Therefore, the completion of key `k` is correct. What am I missing?

**Comment by Harpush** [comment]
> I'm a bit confused by this report. You are _already_ inside the value corresponding to key `g`, which should be an inner group with key `k`. Therefore, the completion of key `k` is correct. What am I missing?

The type of `k` is unknown while it should be based on `FormGroup<{a: FormControl<number>}>`

**Comment by Harpush** [comment]
@JoostK @dylhunn For completeness here is how it looks with FormGroup:
![image](https://github.com/user-attachments/assets/069bfd37-0ad3-4b58-92e7-e0686243f0c9)
 Compared to form builder:
![image](https://github.com/user-attachments/assets/d34b4667-dc1d-4031-b4a7-382e280144d4)

**Comment by JoostK** [comment]
This might be an inference limitation in the TS language service. The important part is whether correct code compiles as desired, which I believe it does here. Language service behavior is something that's taken into consideration during API design, but various constraints (such as backwards compatibility in the case of the forms API) may complicate types to a point that the LS won't be as helpful anymore.

I am not saying this couldn't be improved as I haven't really looked into it, just sharing my thoughts for now.

**Comment by alxhub** [comment]
+1 - given the complexities of the `FormBuilder` API shape and the various signatures/call forms it allows, I wouldn't consider this a bug. I doubt there's a straightforward way to improve the autocompletion here,

**Comment by Harpush** [comment]
@JoostK @alxhub That's not always true that it compiles...
```ts
interface Tester {
  group: FormGroup<{name: FormControl<string>, aliases: FormArray<FormControl<string>>}>
}
const builder = new FormBuilder();
const form2 = builder.group<Tester>({
  group: builder.group({name: 'a', aliases: builder.array([])})
})
```
Won't compile while this will:
```ts
const form2 = builder.group<Tester>({
  group: builder.group({name: 'a', aliases: new FormArray([])})
})
```
The `FormArray` will infer any but it will compile and have the correct type for `form2`

**Comment by JoostK** [comment]
That's not the case in my testing:

```ts
import { FormControl, FormGroup, NonNullableFormBuilder, FormArray } from '@angular/forms';

interface Tester {
  group: FormGroup<{name: FormControl<string>, aliases: FormArray<FormControl<string>>}>
}
declare const builder: NonNullableFormBuilder;
builder.group<Tester>({
  group: builder.group({name: 'a', aliases: builder.array([])})
})

builder.group<Tester>({
  group: builder.group({name: 'a', aliases: new FormArray([])})
})
```

[(TS Playground)](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgMWiAwhAdjKEA2ANCmgOJ4CuYxActjRfvgIYBG+ApqlCAEIXB8AEw5Ri3EAEEoUZgE84AXzgAzPCDgByAALMsAc0bMoAehVoAzpoDcAKFvAcolcwDGHOABUOFmKMS2cHD6lGAAXCQ85BBUADwIWMwgHBESmDh4+LG+UI76AHzEzPjAzBY+qWjSsnKxadi4BNm4efn5ivm2irYirixQHq7YvnCsAsKiEXRYDExsnBL8giJQdmPLogB0ITFgsd6+ovkAFAiBwaER6xNQ26GnickRmsyaRSVlFaPjK5vGNccANoAXQAlIpQV1IbZrr8dnEDn4oCczkF4eFvhtbuiHkkUlpXu9SuULBEsBwAO6RKQyeRAsEQqFAA)

reports two identical errors:

```
Type 'FormGroup<{ name: FormControl<string | null>; aliases: FormArray<FormControl<unknown>>; }>' is not assignable to type 'FormGroup<{ name: FormControl<string>; aliases: FormArray<FormControl<string>>; }>'.
  Types of property 'controls' are incompatible.
    Type '{ name: FormControl<string | null>; aliases: FormArray<FormControl<unknown>>; }' is not assignable to type '{ name: FormControl<string>; aliases: FormArray<FormControl<string>>; }'.
Type 'FormGroup<{ name: FormControl<string | null>; aliases: FormArray<never>; }>' is not assignable to type 'FormGroup<{ name: FormControl<string>; aliases: FormArray<FormControl<string>>; }>'.
  Types of property 'controls' are incompatible.
    Type '{ name: FormControl<string | null>; aliases: FormArray<never>; }' is not assignable to type '{ name: FormControl<string>; aliases: FormArray<FormControl<string>>; }'.
```

Note that I switched to `NonNullableFormBuilder` to make the type of `name` align.

**Comment by Harpush** [comment]
@JoostK When you turn off strict null checks the `FormArray` compiles. With strict null checks both error indeed
