### ISSUE TITLE
alpha.50: HtmlParser does not check top level tag

### ISSUE THREAD

**Issue by todoubaba** [angular/angular#5748]
```typescript
@Component({
  selector: 'my-app',
  template: `<h1>Hello<h1>`
})
class MyApp {
}
```
will generate
```html
<h1>Hello<h1></h1></h1>

**Comment by vicb** [comment]
@tbosch what do you think ? (ie should we change the parser to error when els are not closed ?)

**Comment by martinmcwhorter** [comment]
+1 yes. Compile time errors are always better than bugs found in QA or Prod.

**Comment by tbosch** [comment]
Doing this will be a major effort though, as we have already a big internal code base.
I don't have a strong opinion for either not throwing or for throwing.
