### ISSUE TITLE
Field value in component class updates but does not revert back

### ISSUE THREAD

**Issue by HimanshuMahto** [angular/angular#57485]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

<nb-checkbox
    status="primary"
    class="select-checkbox"
    [indeterminate]="isIndeterminate"
    [(ngModel)]="isSelectAll"
    (checkedChange)="onSelectAllClicked($event)"
  ></nb-checkbox>
  
  
  the code above what I'm trying is that when I click on checkbox and if more than 0 check box are checked then show a button to cancel the process which I am going to perform on it. it work in case of indeterminate checkbox but in case when I select all the checkbox using selectall then in that case if I cancel the process still the checkbox are set to be check which should not happen and this issue is not coming in case of indeterminate checkboxes.

**Comment by JeanMeche** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).
