### ISSUE TITLE
Module Federation Host to Remote Routing - inject error

### ISSUE THREAD

**Issue by AlanGRutter** [angular/angular#57496]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

When attempting to navigate from a host app to a remote app using native federation, the navigation appears to succeed but then fails with NG0203 inject() error. Removing all instances and references to inject in application code does not resolve the issue.

![image](https://github.com/user-attachments/assets/2653616e-9e34-4c04-9f7f-54e01f662fae)

### Please provide a link to a minimal reproduction of the bug

N/A

### Please provide the exception or error you saw

```true
See image.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
This was discovered when I upgraded to 18.2.0 and also 18.2.1.
```

### Anything else?

Downgrading to 18.1.5 - the issue does not occur.

**Comment by Tweniee** [comment]
@AlanGRutter can you please provide a bit more info

**Comment by JoostK** [comment]
This a presumably an issue with your MF configuration, where `@angulat/core` isn't deduplicared.

---

Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by AlanGRutter** [comment]
I disagree with your assessment. Everything stopped working when I upgraded to v18.2.0.

By downgrading to v18.1.5, the error was gone. I changed nothing else in my code.
Hence it is not a configuration issue with MF but something else.

Sent from my phone.

On 23/08/2024, at 5:37 PM, Joost Koehoorn ***@***.***> wrote:

﻿

This a presumably an issue with your MF configuration, where @angulat/core isn't deduplicared.

________________________________

Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on StackOverflow<http://stackoverflow.com/> using tag angular.

If you are wondering why we don't resolve support issues via the issue tracker, please check out this explanation<https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem>.

**Comment by JoostK** [comment]
This is a typical error when there's multiple copies of `@angular/core` present in an app. Updates can introduce such copies, e.g. if libraries use `dependencies` instead of `peerDependencies` that can no longer be shared with the application itself, a lockfile that hasn't been optimized to deduplicate dependencies, MF configurations or various other reasons.

Building MF applications isn't supported from CLI's own builders, so you are presumably using a custom builder or a custom build pipeline, which made me decide to close this as a support request.

**Comment by AlanGRutter** [comment]
I am using angular architects native federation library and esbuild. All my libraries have only peerDependencies as per recommendations. No custom pipelines or builders. Simply out of the box ng cli workspace, generate, build and serve.

When using v18.2.1, I deleted the dist folder and node modules. Reinstalled all dependencies and rebuilt code libraries etc manually. Still got inject error.

Did the same with v18.1.5 - no error.
What else can I say.

Sent from my phone.

On 23/08/2024, at 7:30 PM, Joost Koehoorn ***@***.***> wrote:

﻿

This is a typical error when there's multiple copies of @angular/core present in an app. Updates can introduce such copies, e.g. if libraries use dependencies instead of peerDependencies that can no longer be shared with the application itself, a lockfile that hasn't been optimized to deduplicate dependencies, MF configurations or various other reasons.

Building MF applications isn't supported from CLI's own builders, so you are presumably using a custom builder or a custom build pipeline, which made me decide to close this as a support request.

**Comment by JoostK** [comment]
> I am using angular architects native federation library and esbuild

[@angular-architects/native-federation](https://www.npmjs.com/package/@angular-architects/native-federation) implements its own builders to build the application, so if this is being used then `ng build` and `ng serve`'s behavior follows that of the builder.

**Comment by JoostK** [comment]
What is the output of `npm ls @angular/core`?

**Comment by AlanGRutter** [comment]
Here's what I just did:
1) Made a copy of my workspace folder using v18.1.5 which works.
2) Ran ng update @angular/cli followed by ng update @angular/core
3) Deleted dist folder
4) Updated peerDependencies in all libraries to 18.2.1
5) Re-built all libraries 
6) ng serve host app  and ng serve remote app
7) Both apps are accessible via browser windows.
8) Change URL in host app to reference path on remote app - BOOM! Inject error

I can share the source with you privately

**Comment by AlanGRutter** [comment]
So I've just spent a couple of hours trimming down my code to the bare essentials.
Here's a link to [github repo](https://github.com/AlanGRutter/Angular-Inject-Error.git) which has a working and non-working version.
If I'm doing something stupid, I don't know what it is.

**Comment by JoostK** [comment]
Thanks! I can confirm that `@angular/core` is indeed present twice when using `ng serve`:

<img width="1093" alt="Screenshot 2024-08-25 at 10 34 00" src="https://github.com/user-attachments/assets/eabbc869-5a0f-4d79-ab98-034f86c44c14">

The lower copy is the shared one through MF, the other one is bundled by Vite.

Since this is using a custom builder it's not CLI-default behavior. This problem has since also been reported in https://github.com/angular-architects/module-federation-plugin/issues/628 which I believe is the correct place for this issue.

**Comment by AlanGRutter** [comment]
Thank you Joost. I guess it helps when you know what you are looking for. I will have to wait for a fix on the module federation plugin.

It is strange that upgrading the core broke an unrelated module(module federation) which worked with older version of core.

Sent from my phone.

On 25/08/2024, at 8:34 PM, Joost Koehoorn ***@***.***> wrote:

﻿

Thanks! I can confirm that @angular/core is indeed present twice when using ng serve:

Screenshot.2024-08-25.at.10.34.00.png (view on web)<https://github.com/user-attachments/assets/eabbc869-5a0f-4d79-ab98-034f86c44c14>

The lower copy is the shared one through MF, the other one is bundled by Vite.

Since this is using a custom builder it's not CLI-default behavior. This problem has since also been reported in angular-architects/module-federation-plugin#628<https://github.com/angular-architects/module-federation-plugin/issues/628> which I believe is the correct place for this issue.
