### ISSUE TITLE
map(), breaking changes, lossing hair, loss of sleep

### ISSUE THREAD

**Issue by tenowg** [angular/angular#5749]
No really, I love you guys. Angular is the best (even if it isn't done yet), but I have to vent somewhat after this morning :hankey: 

## Two letter changes should be put in a table somewhere and listed as breaking
~~this can cause an old man to cry, and have a heart attack at the same time. In this case I refer to exportAs: "form" to exportAs: "ngForm"~~ disregard this rant...

## Recommendations that don't seem to work right should be left out of Breaking Changes
Even after figuring out the typo (operation, not operations) I still can't figure this out, I have imported
it everywhere, where I use http.get().map and even where I don't, can someone please explain this to me? Also while you are at it, what is the purpose of .map()? seems kinda pointless to me when you can just do result.json() as IType (could even leave the IType out I guess) its really just a way to get rid of the red lines.

Thats it, all I noticed from the change in 2 numbers of 48 to 50. Keep up the amazing work (and please, in reference to point 1, change the documentation to match 2 letter changes)

**Comment by vicb** [comment]
> In this case I refer to exportAs: "form" to exportAs: "ngForm"

This is listed as a breaking change in the changelog (the formatting is being improved though)

**Comment by tenowg** [comment]
man, that wasn't there, honest!! I must have read right over that...

**Comment by todoubaba** [comment]
about map(), see https://github.com/angular/angular/issues/5632

**Comment by tenowg** [comment]
Unfortunately not so easy in VS it seems...

I have 2 options, I have to use webpack (or another bundler) to access node_modules as they have seen to it that you can't access node_modules directly anymore, or use a cdn. The last cdn (after a quick look) was very out dated, I will look again once I have sleep.

In my case, I use webpack to bundle, installed the dep, and imported with no error from wp... but still map is not found.

**Comment by matthewdenobrega** [comment]
@tenowg I was able to get map and filter working with webpack by doing:

    import {Observable} from 'rxjs/Observable'
    Observable.prototype.map = require('../node_modules/@reactivex/rxjs/dist/cjs/operator/map.js').map

Incidentally the same doesn't work for catch and I have had to commented out the catches on my http implementation.

I share your feelings on this one - great work in general but I don't see how importing individual operators from Rx makes sense - it's like importing .filter from underscore every time you need to use it. Especially if the way RX exports them makes it non-trivial to set up the imports. 

From the angular team - what's the long-term (ie production-ready / loader agnostic) plan for loading RX operators?

**Comment by splintercode** [comment]
Is there a issue open that people could keep an eye on about how importing extra operators will work in the long term? 
@robwormald

**Comment by robwormald** [comment]
not an issue precisely. the easiest way currently (as of alpha 50) to get them all is just `import 'rxjs/Rx'` - this is an ongoing discussion.

**Comment by robwormald** [comment]
> it's like importing .filter from underscore every time you need to use it

Incidentally, this is exactly what lodash is doing :)

**Comment by thelgevold** [comment]
Generally the change log contains most breaking changes. However, another good resource if you see breakage after a new release is the source code playground: https://github.com/angular/angular/tree/master/modules/playground/src

I also find that the unit tests serve as good documentation in certain cases.
