### ISSUE TITLE
defaultEncapsulation doesn't work

### ISSUE THREAD

**Issue by mscherer82** [angular/angular#57500]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

I set 
```
platformBrowserDynamic()
  .bootstrapModule(AppModule, {
    defaultEncapsulation: ViewEncapsulation.None,
  })
```
but it doesn't work. I also tried other ways described here: https://stackoverflow.com/questions/39452729/angular2-setting-view-encapsulation-globally 
I'm assuming it is supposed to work because defaultEncapsulation is an valid property in bootstrapModule?

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.1.4
Node: 18.20.4
Package Manager: npm 10.7.0
OS: win32 x64

Angular: 18.2.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, material-moment-adapter, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.1
@angular-devkit/build-angular   18.2.1
@angular-devkit/core            18.2.1
@angular-devkit/schematics      18.2.1
@angular/cli                    18.1.4
@schematics/angular             18.1.4
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10
```

**Comment by JoostK** [comment]
This option only works in combination with JIT compilation, which is highly discouraged. Please see #12251 for details, the tldr is that AOT compiled apps must have their view encapsulation configured per individal component.
