### ISSUE TITLE
Page broken after refresh

### ISSUE THREAD

**Issue by dmmishchenko** [angular/angular#57509]
### Describe the problem that you experienced

- try to open https://angular.dev/tools/cli/serve
- refresh page 
- get result pic 1
<img width="710" alt="Screenshot 2024-08-24 at 16 30 48" src="https://github.com/user-attachments/assets/eba75bbe-607e-4176-a892-8f7dec524041">

- go to proxy settings part route https://angular.dev/tools/cli/serve#proxying-to-a-backend-server
- refresh page
- ger result pic 2
<img width="720" alt="Screenshot 2024-08-24 at 16 30 52" src="https://github.com/user-attachments/assets/99b37920-7f47-48b9-ad9c-a24fa730ac01">

### Enter the URL of the topic with the problem

https://angular.dev/tools/cli/serve#proxying-to-a-backend-server

### Describe the actions that led you to experience the problem

open page and refresh page

### Provide any additional information here in as much as detail as you can

```true
url that I copied is:
https://angular.dev/tools/cli/serve#proxying-to-a-backend-server

after refresh it became:
https://angular.dev/tools/cli/serve/#proxying-to-a-backend-server

slash(/) appeared before hash(#) symbol
```

**Comment by JoostK** [comment]
I couldn't reproduce with Chrome 127, then updated to a newer (but still outdated) v127 that did reproduce, but after updating to Chrome 128 this doesn't reproduce anymore. So this may have been an issue in Chrome that has since been fixed?

**Comment by JeanMeche** [comment]
Error 5 is a Chrome crash, this isn't actionable to us. 

I can confirm that after updating to Chrome 128, I don't reproduce the issue anymore.

**Comment by dmmishchenko** [comment]
thank you for the quick response
