### ISSUE TITLE
UrlMatcher running twice when matching a url pattern

### ISSUE THREAD

**Issue by mattiLeBlanc** [angular/angular#57511]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

I am using a URL Matcher in my routing config and it runs twice when I add loggin to my matching function.
```
{
    matcher: (url: UrlSegment[]) => {
      const groupPaths = Object.keys(groups);
      console.log(groupPaths);
      console.log(url);
      return url.length > 0 && groupPaths.includes(url[0].path) ? ({ consumed: url }) : null;
    },
    loadComponent: () => import('./shared/components/authenticated-layout/authenticated-layout.component').then(m => m.AuthenticatedLayoutComponent),
  },
```
<img width="490" alt="image" src="https://github.com/user-attachments/assets/08880c2c-8d15-4da7-90c5-390c19550355">

I found a previous issue posted (https://github.com/angular/angular/issues/26081) which seems to address this but I am currently getting this in my A18 app.

This URL matcher is currently the only Route config for my app.
I am only loading my routes once in the `main.ts`

Check my stackblitz:
https://stackblitz.com/edit/stackblitz-starters-19lwxe?file=src%2Fmain.ts
If you navigate to url `/foo` or `/bar` you will notice the matcher executing twice.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-19lwxe?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
<img width="490" alt="image" src="https://github.com/user-attachments/assets/08880c2c-8d15-4da7-90c5-390c19550355">
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.1.4
Node: 20.14.0
Package Manager: npm 8.19.1
OS: darwin arm64

Angular: 18.1.4
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, material-moment-adapter, platform-browser
... platform-browser-dynamic, router, youtube-player

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1801.4
@angular-devkit/build-angular   18.1.4
@angular-devkit/core            18.1.4
@angular-devkit/schematics      18.1.4
@schematics/angular             18.1.4
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10
```

**Comment by atscott** [comment]
In this particular case, the duplicate call isn't necessary and can be fixed. But do note that the Router does not make any guarantees about the number of times the matcher is executed.

**Comment by mattiLeBlanc** [comment]
@atscott Okay, great. I am not experiencing any issues with the matcher running twice, other than that it is executing related logic twice which is wasteful.

But why would a matcher run tries, wouldn't on URL change, the URL Tree be traversed from top to bottom only once? What would make it traverse it again?

**Comment by atscott** [comment]
@mattiLeBlanc there may be some logic that wants to know about a potentially match ahead of actually running the match logic, or some other feature at some point that wants to rerun the matcher on a previously matched route. You can check out the PR that addresses this issue, which was the former. It does appear to be entirely wasteful this time, but I can’t guarantee that there would never be a need to run the marchers more than once.

**Comment by mattiLeBlanc** [comment]
@atscott I had a look at your PR. But I would be lying if I understand the routers internal workings :).
But I get the gist, I think.
Thank you for the update.
If this get's approved and merged, it would be available in a V18 minor update?

**Comment by mattiLeBlanc** [comment]
Thanks for picking this up. Much appreciated.
