### ISSUE TITLE
[angular2] TypeScript Guide Error

### ISSUE THREAD

**Issue by agjs** [angular/angular#5752]
In your TypeScript tutorial for Angular2 there is:

<img width="625" alt="screen shot 2015-12-09 at 20 23 50" src="https://cloud.githubusercontent.com/assets/7226555/11696085/d63dea1e-9eb2-11e5-9f32-a82a23f99d52.png">

Due to wrong markup, template is not parsed and error is thrown:
<img width="579" alt="screen shot 2015-12-09 at 20 21 50" src="https://cloud.githubusercontent.com/assets/7226555/11696021/86047090-9eb2-11e5-8475-280de943a2c6.png">
Anyway, just wanted to point this out in case it hasn't been opened yet :). Just remove </input> and its perfect. Cheers

**Comment by johnpapa** [comment]
i updated all the places i could find in ToH. not merged yet

**Comment by IgorMinar** [comment]
@johnpapa and @wardbell fixed most docs, the rest should be fixed in 5b63b6764f4c2bd6d4522308359ba4dd19a5a245
