### ISSUE TITLE
Memory leak via TRACKED_LVIEWS with SSR

### ISSUE THREAD

**Issue by amakhrov** [angular/angular#57529]
### Which @angular/* package(s) are the source of the bug?

core, platform-server

### Is this a regression?

I don't know

### Description

I'm investigating a Node.js memory leak in our Angular Universal app.
Looking at the heap snapshots, I see that over time, the global TRACKED_LVIEWS map keeps accumulating entries.

I don't have a clear repro at this point, but it seems that it happens when the server processes multiple requests (i.e renders multiple documents) at the same time

All retained LViews are root entries (`lview[1].type` is 0).

### Please provide the exception or error you saw

<img width="882" alt="Screenshot 2024-08-26 at 12 16 08 PM" src="https://github.com/user-attachments/assets/9ebf3be8-0752-4ffa-aa8c-edbba80373d0">

### Please provide the environment you discovered this bug in (run `ng version`)

```
Angular CLI: 18.1.2
Node: 20.14.0
Package Manager: yarn 3.5.0
OS: darwin arm64

Angular: 18.1.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, localize, material, platform-browser
... platform-browser-dynamic, platform-server, router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1801.2
@angular-devkit/build-angular   18.1.2
@angular-devkit/core            18.1.2
@angular-devkit/schematics      18.1.2
@schematics/angular             18.1.2
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.8
```

**Comment by amakhrov** [comment]
This one is a dev build.
However, I prod snapshots show a similar picture:
<img width="896" alt="Screenshot 2024-08-26 at 12 35 14 PM" src="https://github.com/user-attachments/assets/191721f7-b994-4d8c-9740-7d45dab6b946">

**Comment by JeanMeche** [comment]
Do you have a minimal repro of the issue so we could investigate it ?

**Comment by amakhrov** [comment]
I don't. I'll try to create one.
Also not sure it's related - we use the `@angular-devkit/build-angular:server` (and `@angular-devkit/build-angular:ssr-dev-server` for development)

**Comment by crisbeto** [comment]
I spent a bit of time looking at our own tests to see if we hit any cases where LViews aren't being cleaned up properly. We actually have a bunch of leaks in our tests as well, but they all seem to fall into two categories:
1. We were testing `createComponent`/`ViewContainerRef.createComponent` and weren't destroying the ref after the test.
2. Components that were throwing errors during creation weren't being cleaned up.

Not sure that this applies necessary to the case here, but it can be something to look out for.

**Comment by amakhrov** [comment]
We use `ViewContainerRef.createComponent` in a few places in the app to dynamically render components.
Do we need to explicitly destroy the ref?

**Comment by crisbeto** [comment]
I _think_ `ViewContainerRef.createComponent` should clean up automatically, but with the `createComponent` function you need to clean up manually.

**Comment by amakhrov** [comment]
I tried to upgrade to 18.2.2 with the fix related to throwing during creation of components. It didn't help in our case.

I was not able to create a minimal repro so far. I can consistently reproduce it with the full app. But when I start removing parts of the app, the reproduction becomes unreliable yet doesn't completely go away, so it's not really helpful.

**Comment by amakhrov** [comment]
I think I found it.
MatBadge calls `createComponent`, but never cleans up the component ref.
https://github.com/angular/components/blob/main/src/cdk/private/style-loader.ts#L66

When I remove MatBadge from our app, the memory leak goes away.

**Comment by crisbeto** [comment]
Oh that's an interesting finding! We can't backport the style loader into the patch branch because there's a slight chance to break something, but we can either make it handle the race condition or just disable the style loading on the server.

**Comment by amakhrov** [comment]
Would not disabling it on the server prevent the styles from being embedded in the HTML, which might impact the first render?

**Comment by crisbeto** [comment]
I think it would've been fine since the state doesn't transfer between the server and client so it would try to load the styles again. Anyways, I've sent out https://github.com/angular/components/pull/29676 to resolve it.

**Comment by crisbeto** [comment]
Fix is merged in for this week's 18.x release of Material.
