### ISSUE TITLE
ADEV: unnecessary new lines in API docs for fns with no arguments

### ISSUE THREAD

**Issue by AndrewKushnir** [angular/angular#57539]
### Describe the problem that you experienced

Functions that do not have arguments are displayed in API docs with an unnecessary extra newline:

<img width="621" alt="newline-in-api-docs" src="https://github.com/user-attachments/assets/c6449439-0966-434a-8f30-6a4cba4b0b51">

### Enter the URL of the topic with the problem

https://angular.dev/api/core/getPlatform

**Comment by JeanMeche** [comment]
This is being taken care of in #57492
