### ISSUE TITLE
The WebWorker docs seem to be crashing Chrome (Version 127.0.6533.122 (Official Build) (arm64))

### ISSUE THREAD

**Issue by iislucas** [angular/angular#57548]
### Describe the problem that you experienced

In Chrome (Version 127.0.6533.122 (Official Build) (arm64)) on a Mac M1, going to the webworker documentation [/ecosystem/web-workers/](https://angular.dev/ecosystem/web-workers/) results in the webpage crashing (Chrome Error code: 5). 

None of these make the page work for me: restarting chrome, clearing the cache, opening in an incognito mode.

### Enter the URL of the topic with the problem

https://angular.dev/ecosystem/web-workers/

### Describe what you were looking for in the documentation

I was wondering how to specify the URL of a webworker so that it loads correctly in karma-chrome-runner

### Describe the actions that led you to experience the problem

I just tried going to the webpage :) 

### Describe what you want to experience that would fix the problem

I'd like the webpage to load in Chrome. 

### Add a screenshot if that helps illustrate the problem

<img width="706" alt="Screenshot 2024-08-27 at 14 08 29" src="https://github.com/user-attachments/assets/ebed8e05-7c4c-4148-b060-e6e57c2b2595">

### If this problem caused an exception or error, please paste it here

```true
Chrome error: 


(Error code: 5). 
```
```


### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
MacOS: 14.6.1 (23G93)
Chip: Apple M1 Pro
Chrome (Version 127.0.6533.122 (Official Build) (arm64))
```

**Comment by JeanMeche** [comment]
This is a browser issue that was fixed with Chrome 128, please update your browser to the latest version.
