### ISSUE TITLE
Scroll is not triggered after click on ToC item or section header.

### ISSUE THREAD

**Issue by 9kubczas4** [angular/angular#57552]
### Describe the problem that you experienced

Scroll is not triggered after click on ToC item or section header.

### Describe what you were looking for in the documentation

Steps to reproduce:
1. Open https://angular.dev/guide/di/dependency-injection-providers
2. Click on Table of Contents item (top-right corner on laptop screens) i.e `[Factory providers: useFactory](https://angular.dev/guide/di/dependency-injection-providers#factory-providers-usefactory)`.

Current behavior: scroll to the top was happened.
Expected behavior: scroll to the clicked section should happen.

### Add a screenshot if that helps illustrate the problem

https://github.com/user-attachments/assets/cb728428-26b2-4d3d-88d8-a0f4fae7f14f

### If this problem caused an exception or error, please paste it here

```true
Following error in the console is visible:

chunk-ISM6Q3J7.js:7 Uncaught TypeError: Cannot read properties of undefined (reading 'unregister')
    at o.destroy [as cancelScroll] (chunk-ISM6Q3J7.js:7:89049)
    at Object.next (chunk-KGULDEHF.js:1:501)
    at o.subscribe.a (chunk-ISM6Q3J7.js:3:24735)
    at yi._next (chunk-ISM6Q3J7.js:3:7798)
    at yi.next (chunk-ISM6Q3J7.js:3:2511)
    at chunk-ISM6Q3J7.js:3:13456
    at yi._next (chunk-ISM6Q3J7.js:3:7798)
    at yi.next (chunk-ISM6Q3J7.js:3:2511)
    at chunk-ISM6Q3J7.js:3:5570
    at Pt (chunk-ISM6Q3J7.js:3:2204)
 ```

**Comment by 9kubczas4** [comment]
When I commented out following lines then it works as expected: https://github.com/angular/angular/blob/main/adev/src/app/app-scroller.ts#L66-L80.

Can it be related to deprecation of `AfterRenderPhase`?

**Comment by 9kubczas4** [comment]
After further investigation I discovered that an instance of `AfterRenderImpl` is undefined and an error is thrown in the instance of `AfterRenderSequence`, exactly in `destroy()` method:

```ts
  destroy(): void {
    this.impl.unregister(this); // impl is undefined
    this.unregisterOnDestroy();
  }
```

**Comment by JeanMeche** [comment]
What I observed, there is a `this` context issue. 

https://github.com/angular/angular/blob/969dadc8e2fad8ca9d892858bdadbe3abb13de95/adev/src/app/app-scroller.ts#L66-L80

Should be replaced by an arrow function. 

But more interestingly, the `afterNextRender` doesn't fire.
