### ISSUE TITLE
Angular signal input computed bug

### ISSUE THREAD

**Issue by oytntur** [angular/angular#57569]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

While trying to update a behaviour subject or a signal array the child component with `test =input() computedTest=computed(()=>this.test())`  does not update in the html

reporoduction is https://stackblitz.com/edit/stackblitz-starters-uxwgby?file=src%2Fmain.ts
change test.component.ts template to `<h1>Hello from {{ asdaas() | json }}!</h1>`

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-uxwgby?file=src%2Fmain.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.7
Node: 20.14.0
Package Manager: npm 10.8.2
OS: win32 x64

Angular: 17.3.5
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, pwa, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.5
@angular-devkit/build-angular   17.3.5
@angular-devkit/core            17.3.5
@angular-devkit/schematics      17.3.5
@angular/cli                    17.3.7
@angular/google-maps            17.3.9
@angular/ssr                    17.3.7
@schematics/angular             17.3.5
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.4
```

**Comment by oytntur** [comment]
[EDIT] Forgot to add you can recreate the issue in stackblitz by changing `<h1>Hello from {{ asdaas() | json }}!</h1>` template in test.component.ts to `<h1>Hello from {{ testInput() | json }}!</h1>`

**Comment by JoostK** [comment]
This is working as designed; the Observable emits the same array reference, hence the signal value doesn't actually change.

Please see https://github.com/angular/angular/issues/54111

**Comment by JeanMeche** [comment]
The exact issue is that you're mutating the array items, therefore the inputs are not made dirty.

**Comment by JoostK** [comment]
Or more precisely, the input binding expression doesn't change so it never even reaches the signal.
