### ISSUE TITLE
Date and time manipulations need to be built into the Angular native Library as this is HIGH priority, HIGHLY uses function

### ISSUE THREAD

**Issue by psmith30907** [angular/angular#57563]
### Which @angular/* package(s) are relevant/related to the feature request?

platform-server

### Description

Date and time manipulations are very difficult, heavy handed, and unavailable in the Angular native Library

### Proposed solution

Date and time manipulations need to be built into the Angular native Library as this is HIGH priority, HIGHLY uses function

### Alternatives considered

Using non-tree shakable MOMENT stinks

**Comment by JeanMeche** [comment]
Hi, 
This is not the goal of the framework to provide domain-specific support, like in this case date & time manipulations. 
You likely want to support the effort of landing the [Temporal API](https://tc39.es/proposal-temporal/docs/). 

Also note that moment is dated library, the team behind wrote luxon instead. You can also take a look at day.js or date-fns which are more lightweight.

**Comment by keatkeat87** [comment]
will Angular consider supporting Temporal API? 
for example DatePipe

**Comment by JeanMeche** [comment]
This probably something in the scope of external libraries as new APIs aren't supported by existing browsers when they land.
