### ISSUE TITLE
Angular docs first page StackBlitz broken

### ISSUE THREAD

**Issue by Brandon689** [angular/angular#57576]
### Describe the problem that you experienced

Try your first Angular app

The code editor contains a complete Angular app.

Importing from GitHub
angular/angular/tree/main/aio/content/demos/first-app
The url to this repository is invalid.

Please make sure the folder path in the URL exists within the repo.

If you think this is a bug, please [file an issue](https://github.com/stackblitz/core/issues/new) in our repo!

### Enter the URL of the topic with the problem
https://angular.io/quick-start

**Comment by JeanMeche** [comment]
Please have a look at the new tutorials on our new doc site: https://angular.dev/tutorials
