### ISSUE TITLE
docs: anchor scrolling is broken 

### ISSUE THREAD

**Issue by mvdluit** [angular/angular#57579]
### Describe the problem that you experienced

When visiting https://angular.dev/style-guide the anchor navigation via the right side-nav does not work. It always scrolls you to the top of the page. If you visit the style-guide directly via https://angular.dev/style-guide#directives it correctly scrolls to the anchor, but afterwards navigation to another anchor again scrolls to the top.

### Enter the URL of the topic with the problem

https://angular.dev/style-guide

### Describe the actions that led you to experience the problem

- visit https://angular.dev/style-guide
- click on any of the links in the right side-nav

### Describe what you want to experience that would fix the problem

Scroll to the correct anchor

### Provide any additional information here in as much as detail as you can

There is already an issue with style-guide content updates: https://github.com/angular/angular/issues/54284
and a comment that the style guide needs a comprehensive update: https://github.com/angular/angular/pull/54084#issuecomment-1922585365

Not sure if you want to make this issue part of a complete overhaul of the style-guide.

**Comment by JeanMeche** [comment]
This is a bit weird, this should have been fixed by #57554 (which was also merged into `18.2.x`) but the change isn't visible (attested by de source code of the deployed app).

**Comment by JeanMeche** [comment]
#57583 should fix it !

**Comment by JeanMeche** [comment]
This was fixed with the latest deployement ! Thanks @josephperrott for the help !
