### ISSUE TITLE
Your HttpProgressEvent interface lacks `partialText` field in angular 18+

### ISSUE THREAD

**Issue by eyoeldefare** [angular/angular#57586]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

As the title says, on angular versions 18+, the interface HttpProgressEvent doesn't have `partialText` field. I had to cast it to type any to access the http event api. 
Right now HttpProgressEvent interface only has this:
```
interface HttpProgressEvent {
  type: HttpEventType.UploadProgress | HttpEventType.DownloadProgress;
  loaded: number;
  total?: number;
  // You will need this --- > partialText?: string 
}

### Please provide a link to a minimal reproduction of the bug

_No response_

### Please provide the exception or error you saw

_No response_

### Please provide the environment you discovered this bug in (run `ng version`)

```true
"@angular/common": "^18.0.0",
```

**Comment by JeanMeche** [comment]
You need to refer to the `HttpDownloadProgressEvent` interface. `HttpUploadProgressEvent` which also extends `HttpProgressEvent` does not have a `partialText` entry.
