### ISSUE TITLE
https://angular.dev/api/core/Renderer2 page not found

### ISSUE THREAD

**Issue by ykou-clickup** [angular/angular#57587]
### Describe the problem that you experienced

![image](https://github.com/user-attachments/assets/255ba97f-eed5-4fd8-86f5-d2f6f6d1c907)

![image](https://github.com/user-attachments/assets/8dd7f99e-e5ca-4dd3-95ab-5b723711ef2d)

**Comment by JeanMeche** [comment]
It looks like #57365 introduced a change in the entries' urls, we'll fix this.  

In the mean time, you can access every symbol via the API list page : https://angular.dev/api
