### ISSUE TITLE
Missing documentation for HttpTestingController

### ISSUE THREAD

**Issue by daniela-borosova** [angular/angular#57599]
### Describe the problem that you experienced

I have searched HttpTestingController. The resulting page https://angular.dev/api/common/http/testing/HttpTestingController returns Page Not Found 🙃

**Comment by JeanMeche** [comment]
Thank for you reporting this issue, #57600 will address this. 

In the mean time, you can still acess the symbol via the API page : https://angular.dev/api?query=HttpTestingController
