### ISSUE TITLE
[docs] createComponent API | projectableNodes details

### ISSUE THREAD

**Issue by GeorgianStan** [angular/angular#57601]
### Describe the problem that you experienced

I tried to use `projectableNodes` from `createComponent` and I didn't find in the documentation an explanation for the different possible scenarios.

### Enter the URL of the topic with the problem

https://angular.dev/api/core/createComponent?tab=api

### Describe what you were looking for in the documentation

In the documentation it states that the interface for `projectableNodes` is `Node[][]`, but it doesn't mention or provide an example of usage when you want to project multiple different nodes in different `ng-content` tags, or if you want to project multiple but similar nodes in a single `ng-content` tag.

### Describe the actions that led you to experience the problem

Given this two examples:

**Example one** - different nodes

`my-component.html`
```html
<p> Hello from my component</p>
<ng-content select="child-one"/>
<hr/>
<ng-content select="child-two"/>
```

The the `projectableNodes` array should be like this:
```js
[[child-one],[child-two]]
```

**Example two** - similar nodes
`my-component.html`
```html
<p> Hello from my component</p>
<ng-content select="[child-one]"/>
```

The the `projectableNodes` array should be like this:
```js
[[child-one,child-one]]
```

### Describe what you want to experience that would fix the problem

It would be nice to have a usage example that would cover this scenario.

**Comment by vincent-agi** [comment]
Hi angular team, i will interresting to make PR for this issue. Are you agree ?

**Comment by vincent-agi** [comment]
i didn't find the right file to edit. Please somebody can helps me ?

**Comment by risqiromadhoni** [comment]
> i didn't find the right file to edit. Please somebody can helps me ?

I think you can find it in this file
https://github.com/angular/angular/blob/2b3e7f87b90b8007f13ef1d9f4445ebe82a21f00/packages/core/src/render3/component.ts#L83

**Comment by vincent-agi** [comment]
thank you so much @risqiromadhoni. I will do this task at the end of week

**Comment by vincent-inviseo** [comment]
Hi, i meet a little difficulty on this issue. I didn't found the documentation file to edit.
@risqiromadhoni advices to me look  this file `[angular/packages/core/src/render3/component.ts](https://github.com/angular/angular/blob/2b3e7f87b90b8007f13ef1d9f4445ebe82a21f00/packages/core/src/render3/component.ts#L83)`.

But where is documentation file to edit ?

Thanks for your helps

**Comment by JeanMeche** [comment]
The docs is extracted from the JSDoc that is located ahead of the function definition.

**Comment by elgui1886** [comment]
Still valid?
