### ISSUE TITLE
matchUrlQueryParamValue is only including first params

### ISSUE THREAD

**Issue by TdoubleG** [angular/angular#57630]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

I'm currently using "canActive" route guard, which is calling at some point following code                    

`return of(this.router.parseUrl('path?origin=' + state.url));`

state.url will be the redirect url which looks something like: /item/10037?query1=value&query2=value

The problem is, that in the `matchUrlQueryParamValue` function the second query isn't recognized due to the `regex` as it looks only till the first `&`

Alternatively the `createUrlTree` is working for my case. 
I wanted to clarify if this behavior is intended, before I create a pull request.

### Please provide the exception or error you saw
Screenshot from a regex tester

![Screenshot 2024-09-02 at 20 28 09](https://github.com/user-attachments/assets/89f1dbce-597e-4d96-800f-717597905d03)

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular v16.2.1
```

**Comment by JoostK** [comment]
I don't quite understand the problem being reported; `matchUrlQueryParamValue` is a method of the internal `UrlParser` class, which is driven by `UrlSerializer.parse` that attempts to consume all query parameters. `matchUrlQueryParamValue` is only parsing out a single query parameter value, the loop in `UrlParser.parseQueryParams` drives the parse of all query parameters.

This [StackBlitz](https://stackblitz.com/edit/stackblitz-starters-xb6jfx) shows all query parameters being parsed as expected.

**Comment by TdoubleG** [comment]
You used the wrong url.
Please read again my description and use follow url:
path?origin=/item/10037?query1=value&query2=value

**Comment by JoostK** [comment]
Ooooh, you are substituing an URL into a query parameter? That requires the URL to be URL-encoded, as otherwise its special characters become part of the "outer" URL, not the inner URL.

**Comment by TdoubleG** [comment]
What exactly did you mean by "URL-encoded"? 
Using your StackBlitz and have this code:

```
 const stateUrl = 'path?origin=/item/10037?query1=value&query2=value'
    const encoded = encodeURIComponent(stateUrl);
    console.log(encoded)
    const url = router.parseUrl(`path?origin=${encoded}`);
    console.log(url);
```

still returns wrong URLTree. This is what the URLTree `queryParams` property looks like:
```

{
    "origin": "path?origin=/item/10037?query1=value&query2=value"
}
```

**Comment by TdoubleG** [comment]
AH got it. Need to remove 'path?origin='

Thanks!
