### ISSUE TITLE
Error: NG0300: Multiple components match node with tagname button: ExcelCommandDirective and MatLegacyButton.

### ISSUE THREAD

**Issue by RanjanRavi2398** [angular/angular#57641]
### Which @angular/* package(s) are the source of the bug?

upgrade

### Is this a regression?

Yes

### Description

Hey Angular Team, 
I am getting error like **Error: NG0300: Multiple components match node with tagname button: ExcelCommandDirective and MatLegacyButton.** while upgrading angular from version 15 to 16. We are using kendoGridExcelCommand to export excel. This command using in two component of our application. 

### Please provide the exception or error you saw

Error: NG0300: Multiple components match node with tagname button: ExcelCommandDirective and MatLegacyButton.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.2.12
Node Version: 18.19.0
Typescript Version: 4.9.3
```

**Comment by JeanMeche** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).

**Comment by RanjanRavi2398** [comment]
thanks @JeanMeche ,I will check on stackoverflow.
