### ISSUE TITLE
Suggestion: Shorthand Control Flow

### ISSUE THREAD

**Issue by mmorgan4x** [angular/angular#57646]
### Description

The new control flow is great. There are some users, like myself that find it a little messier looking, specifically the extra indentation, and braces. It makes it look more of a jumble of html and JS. I think a lot of users liked the fact that the templates looked like plain html using the old *ng directives. I understand the old syntax is still available. A solution would add an alternate short hand control flow  that utilizes html's existing indentation and block scope ( open/close tag). This will be most useful for small control flow one liners. 

### Proposed solution

This proposal does not change existing control flow. It adds a shorthand alternative. It allows control flow @ syntax to be used in html tags, and scope is determined by the tags open/close tags. 
 
  ``` 
<div @if(person1)>{{person1.name}}, {{person1.name}}</div>
<div @if(person2)>{{person2.name}}, {{person2.name}}</div>
<div @if(person3)>{{person3.name}}, {{person3.name}}</div>
``` 

### Alternatives considered

Alternatively use the old syntax

```
@if (person1) {
  <div>{{person1.name}}, {{person1.name}}</div>
}
@if (person2) {
  <div>{{person2.name}}, {{person2.name}}</div>
}
@if (person3) {
  <div>{{person3.name}}, {{person3.name}}</div>
}
```

**Comment by pkozlowski-opensource** [comment]
While the new control flow `@if` might be a bit more verbose in certain cases, we prefer to have just one form of the built-in control flow. Thnx for the suggestion but we will pass on it.
