### ISSUE TITLE
Add a compiler option to disable Developer Preview and Experimental features

### ISSUE THREAD

**Issue by marleypowell** [angular/angular#57656]
### Which @angular/* package(s) are relevant/related to the feature request?

compiler

### Description

We don't want to accidentally use features that are in Developer Preview or Experimental. There doesn't seem to be a way to stop this other than through manual review.

### Proposed solution

Add some new angular compiler options to disable Developer Preview or Experimental features. 
https://angular.dev/reference/configs/angular-compiler-options

### Alternatives considered

Manual review

**Comment by YousefNabil8** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by marleypowell** [comment]
> It sounds like something that should be tackled by a linter, similar to `@deprecated`. Maybe it should be the feature request for https://github.com/angular-eslint/angular-eslint?
> 
> In any case we are not planning on adding similar features to the framework.

Is there an easy way to keep track of Developer Preview or Experimental features for the linting rules to be maintainable?

**Comment by JeanMeche** [comment]
The linter could check for JSDoc tags. We use `@developerPreview` and `@experimental`.

**Comment by marleypowell** [comment]
@JeanMeche I'm guessing this would be much harder for preview template features such at `@let`?
