### ISSUE TITLE
NavigationStart and NavigationEnd support browserUrl when router events change 

### ISSUE THREAD

**Issue by why520crazy** [angular/angular#57655]
### Which @angular/* package(s) are relevant/related to the feature request?

`@angular/router`

### Description

in 18.1.0, we can set a different browser URL from the one for route matching via Router's navigate & navigateByUrl methods, this is a very exciting feature. thank you to the NG team.

```
router.navigateByUrl('/404', {
    browserUrl: router.getCurrentNavigation()?.finalUrl,
});
``` 

We can subscribe router.events to receive various routing and navigation events
```
router.events.subscribe(event => {
  if (event instanceof NavigationStart) {
   // do somethings
 });
```

In the micro frontend architecture of multiple NG applications, it is necessary to subscribe to router events to synchronize the router of other applications, which can cause the browserURL to be modified by the router of other NG application and become invalid. therefore, it is necessary to determine whether the browserURL has been set in the event.

### Proposed solution

NavigationStart and NavigationEnd add `browserUrl?: string` 

### Alternatives considered

NavigationStart and NavigationEnd add `behaviorOptions?: NavigationBehaviorOptions`

**Comment by atscott** [comment]
You can also retrieve this information through `Router.getCurrentNavigation()` when those events happen. Given that, is there much reason for adding this information to the events themselves?
