### ISSUE TITLE
BehaviorSubject without initial value

### ISSUE THREAD

**Issue by guenhter** [angular/angular#57653]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Currently it is needed to provide an initial value to the `BehaviorSubject`.
This often means to provide default values which make not really sense just for the sake to create the `BehaviorSubject`.

### Proposed solution

The `BehaviorSubject` should get a second constructor which doesn't need a initial value e.g. like `new BehaviorSubject<MyClass>()`

**Comment by json-derulo** [comment]
`BehaviorSubject` is something offered by [RxJS](https://github.com/ReactiveX/rxjs) and not by Angular, so this is the wrong repository to request the feature. Have you considered to use `ReplaySubject`?

**Comment by guenhter** [comment]
`ReplaySubject` will solve my problem :) 

Thanks very much. I didn't have them on my radar.
