### ISSUE TITLE
declare hammerjs as our peerDependency in npm

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#5766]
our event plugin depends on hammer, but we currently don't officially declare the dependency. it should be an optional peer dependency declared in our `package.json` but not included in `angular2-polyfills.js`.

currently we are blocked on 2.0.5 release see: https://github.com/hammerjs/hammer.js/issues/886
- [ ] get hammer.js 2.0.5 to be released https://github.com/hammerjs/hammer.js/issues/879
- [ ] update `package.json`
- [ ] update `shrinkwrap files`
- [ ] add documentation
- [ ] update https://github.com/angular/angular/blob/01ba94ba56a1a44d1e6b877c38b6b59f6cd86c79/modules/playground/src/gestures/index.html#L19-L27 (remove inlined hammerjs build and pull in the file from node_modules)

// @vicb @pkozlowski-opensource @adamdbradley

**Comment by pkozlowski-opensource** [comment]
Oh, dear, we _really_ need optional peer dependencies from NPM as otherwise our list of deps will be growing and people not needed / carrying about gestures will be like "why do I need to npm-install all this stuff...."

**Comment by tsvetomir** [comment]
Any idea on when the relationship with Hammer will be documented? Currently, there's only a run-time error if you attempt to use `tap`, etc. and Hammer is not loaded.

**Comment by DzmitryShylovich** [comment]
@tsvetomir https://github.com/angular/material2/blob/master/guides/getting-started.md#if-you-want-to-include-hammerjs-from-npm-you-can-install-it

**Comment by tsvetomir** [comment]
Thanks! This solves it pretty well for Angular Material users.

The main Angular documentation on the other hand only mentions [Hammer gestures](https://angular.io/docs/ts/latest/api/platform-browser/index/HAMMER_GESTURE_CONFIG-let.html) in passing. It doesn't go into detail what these gestures are and how to use them.

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular/blob/master/modules/%40angular/platform-browser/src/dom/events/hammer_gestures.ts#L67 config is used to create a `Hammer` instance and also contains a list of supported events.

**Comment by tsvetomir** [comment]
Indeed it does. All I was asking is if it's going to be included in the documentation.

**Comment by gedclack** [comment]
@tsvetomir they said it somewhere, currently 3rd parties won't be included in angular's docs.

**Comment by IgorMinar** [comment]
Since npm has no optional peer deps, we should just improve the docs instead. I filed an issue: #21146
