### ISSUE TITLE
Error: NG0901 - When navigating to a component. 

### ISSUE THREAD

**Issue by Jagadeesh1987** [angular/angular#57663]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

The application I am working on has many components and no other component throws error. But whenever the user navigates to a particular component, we are getting the following error. There are no documentation that talks about Error: NG0901. 

The page is rendered properly and is working as expected. But component gives this error. The component has p-table and it has many form elements inside.

![image](https://github.com/user-attachments/assets/f9b1544d-7ca9-46f3-b42a-614ad84deb4d)
![image](https://github.com/user-attachments/assets/cbf565fa-b90e-4f81-b5c6-5162dd0ff2be)

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 14.0.7
Node: 16.15.1
Package Manager: npm 8.11.0
OS: win32 x64

Angular: 14.3.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1402.13
@angular-devkit/build-angular     14.2.13
@angular-devkit/build-optimizer   0.800.6
@angular-devkit/core              14.2.13
@angular-devkit/schematics        14.2.13
@angular/cdk                      14.2.7
@angular/cli                      14.0.7
@schematics/angular               14.0.7
rxjs                              7.5.7
typescript                        4.7.4
```

**Comment by JeanMeche** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).
