### ISSUE TITLE
Control Flow Schematics: Deletes entire contents of html files

### ISSUE THREAD

**Issue by desmondblue** [angular/angular#57670]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Upon running the command `ng generate @angular/core:control-flow` I observed that the entire content was deleted in multiple html files in my project. I have provided an example of one of the html files of which the entire content was deleted after migration.

```html
<ng-container *ngIf="errorMessage && showAlert">
  <p *ngFor="let err of errorMessage.errors" class="mt-3">
    <app-alert
      [alertMessageParams]="getParamsObject(err.arguments)"
      [alertMessage]="getErrorCodeOrFallbackMessage(err)"
      [alertType]="errorAlertType"
    >
    </app-alert>
  </p>
</ng-container>
```

### Please provide the exception or error you saw

```true
No error
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.8
Node: 18.20.4
Package Manager: npm 10.7.0
OS: win32 x64

Angular: 17.3.12
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.8
@angular-devkit/build-angular   17.3.8
@angular-devkit/core            17.3.8
@angular-devkit/schematics      17.3.8
@angular/cdk                    17.3.10
@angular/cli                    17.3.8
@angular/material               17.3.10
@schematics/angular             17.3.8
ng-packagr                      17.3.0
rxjs                            6.6.7
typescript                      5.4.5
zone.js                         0.14.10
```

**Comment by desmondblue** [comment]
One more example html file for which the code was deleted entirely by migration:

`<ng-container *ngFor="let item of iconsToDisplay | keyvalue">
  <ng-container *ngIf="item.value.defaultMapping">
    {{ item.value.usageName || item.value.usage.name }} (
    <fa-icon [icon]="item.value.agreed ? 'check' : 'minus'"></fa-icon>
    )
  </ng-container>
  <ng-container *ngIf="!item.value.defaultMapping && item.value.icon">
    <app-agreed-usage-icon [icon]="item.value.icon"></app-agreed-usage-icon>
  </ng-container>
</ng-container>
`

**Comment by json-derulo** [comment]
Cannot reproduce. In a fresh Angular 18 project, the control flow migration works as expected and produces the following results:

```html
@if (errorMessage && showAlert) {
  @for (err of errorMessage.errors; track err) {
    <p class="mt-3">
      <app-alert
        [alertMessageParams]="getParamsObject(err.arguments)"
        [alertMessage]="getErrorCodeOrFallbackMessage(err)"
        [alertType]="errorAlertType"
        >
      </app-alert>
    </p>
  }
}
```

```html
@for (item of iconsToDisplay | keyvalue; track item) {
  @if (item.value.defaultMapping) {
    {{ item.value.usageName || item.value.usage.name }} (
    <fa-icon [icon]="item.value.agreed ? 'check' : 'minus'"></fa-icon>
    )
  }
  @if (!item.value.defaultMapping && item.value.icon) {
    <app-agreed-usage-icon [icon]="item.value.icon"></app-agreed-usage-icon>
  }
}
```

**Comment by crisbeto** [comment]
It's worth noting that you're using an older version of Angular and the migration has gotten a bunch of fixes since then.

**Comment by desmondblue** [comment]
thanks for the quick responses. I saw this issue popping up that once I did the migration and thereafter I just did it manually so I am not sure if it was something related to the angular versioning or not. Closing the issue since the consensus is not reproducible.
