### ISSUE TITLE
The ng-submit() directive in Angular does not trigger submission when the "Enter" key is pressed in a text field

### ISSUE THREAD

**Issue by jsV8** [angular/angular#57687]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

I have created a basic form using Angular where I want the ng-click function (updateMsg({name: name,room: room})) to be triggered when the user enters a value and then presses enter key.

Unfortunately, the current code does not work as expected. The function is only executed when the button is clicked, rather than triggering it by pressing the enter key after inputting values.

Below is the code snippet for reference.

Can anyone assist with this issue?

Thank you!

```
<body>
    <div class="Member">
        <h1>Sign In</h1>
        <form name="myForm" ng-submit="updateMsg({name: name,room: room})">
            Please enter your details:
            <br>
            Name: <input name="name" ng-model="name" autocomplete="off">
            <br>
            Room: <input name="room" ng-model="room" autocomplete="off">
            <br>
            <button type="button" ng-click="updateMsg({name: name,room: room})">

            Enter
            </button>
        </form>
    </div>
</body>
```

From https://javascripter.space/questions/the-ng-submit-directive-in-angular-does-not-trigger-submission-when-the-enter-key-is-pressed-in-a-text-field

**Comment by jnizet** [comment]
Hi @jsV8.

Your code is not Angular code. It looks like AngularJS code, but AngularJS is a completely different framework, whose issue tracker is not here. And its support has ended in January 2022. See https://angularjs.org/

**Comment by Totati** [comment]
Yeah, it looks like AngularJS, however the problem is that your form does not have a submint button. Inputs need a submit button to support submitting the form via Enter.

**Comment by JeanMeche** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).
