### ISSUE TITLE
"&nbsp" following an "@if" block is not rendered

### ISSUE THREAD

**Issue by jason-eriksen** [angular/angular#57683]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

An &nbsp immediately following an @if block closing tag is not rendered properly, regardless of the evaluation of the conditional.
```
@if (true) {
  bar
}
&nbsp; <!-- not rendered -->
baz
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-vw4nzr?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
"&nbsp" following @if closing tag not rendered
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
"@angular/animations": "18.1.4",
    "@angular/common": "18.1.4",
    "@angular/compiler": "18.1.4",
    "@angular/core": "18.1.4",
    "@angular/forms": "18.1.4",
    "@angular/platform-browser": "18.1.4",
    "@angular/platform-browser-dynamic": "18.1.4",
    "@angular/router": "18.1.4",
```

**Comment by jnizet** [comment]
Same with &ngsp;. See https://github.com/angular/angular/issues/55791

**Comment by JeanMeche** [comment]
Closing as duplicate #55791
