### ISSUE TITLE
Router: isRouteActive(<Instruction>) defines "active" by rendering component...

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#5768]
If I have multiple routes that point to a single component, how can I know which "route" is being used?

E.g.

```dart
@RouteConfig(const [
  const Route(
      name: 'All',
      path: 'all',
      component: PortfolioConditionalViewComponent,
      useAsDefault: true),
  const Route(
      name: 'Planning',
      path: 'planning',
      component: PortfolioConditionalViewComponent)
])

class PortfolioConditionalViewComponent {
  PortfolioConditionalViewComponent(Router router) {
    var planningLink = router.generate(['Planning']);
    if (router.isRouteActive(planningLink)) {
      // I came here from "planning" so, do something special.
    }
  }
}
```

'isRouteActive' currently works by:

```ts
this._currentInstruction.component == instruction.component
```

Is there another way to get this information? Or expose the current instruction? One hack seems to be that I could overwrite `commit` to store the instruction, but maybe you have a better suggestion.

**Comment by naomiblack** [comment]
This is internal b/26059651

**Comment by vsavkin** [comment]
ActivateRoute should have the `config` property returning the corresponding used.

**Comment by vsavkin** [comment]
Fixed here https://github.com/angular/angular/pull/10367
