### ISSUE TITLE
Docs for @Component decorator: Missing consideration of standalone components

### ISSUE THREAD

**Issue by a2mar** [angular/angular#57689]
### Describe the problem that you experienced

In the documentation for the Component decorator, i stumpled accross the sentence:

> A component must belong to an NgModule in order for it to be available to another component or application. To make it a member of an NgModule, list it in the declarations field of the NgModule metadata.

Isn't it possible to create and run an Angular application entirely without the creation of `NgModule`, i.e. with `bootstrapApplication`?

I suggest to omit that sentence or to adjust it as follows:

> When running Angular with NgModule, a component must belong to an NgModule in order for it to be available to another component or application. To make it a member of an NgModule, list it in the declarations field of the NgModule metadata.

### Enter the URL of the topic with the problem

https://github.com/angular/angular/blob/227d13b86dc3de90c4bdeabb4855996f751ecc06/packages/core/src/metadata/directives.ts#L391

### Describe what you were looking for in the documentation

consideration of the possiblity to run Angular without declaring components in NgModule

**Comment by JeanMeche** [comment]
This is correct, NgModule are not required if your component is standalone. This will be even more true in [v19 as standalone will be the default for components](https://blog.angular.dev/the-future-is-standalone-475d7edbc706).

**Comment by EnverUsta** [comment]
I think this one should be closed since it's resolved with this PR: https://github.com/angular/angular/pull/57878/files
