### ISSUE TITLE
Pipe documentation Problem??

### ISSUE THREAD

**Issue by kmoart** [angular/angular#57704]
### Describe the problem that you experienced

Hello Angular friends, i can not acceso to Pipe documentation, there is a problem with this page??

### Enter the URL of the topic with the problem

https://angular.dev/guide/pipes

### Describe what you were looking for in the documentation

im looking what are the principal pipes that Angular offer to their developers

**Comment by ojadhav-onshape** [comment]
Correct link is here https://angular.dev/guide/templates/pipes#
