### ISSUE TITLE
Problem with component host bindings

### ISSUE THREAD

**Issue by robertdp** [angular/angular#5770]
Specifically binding classes to the host element, which refuses to work for me.

I'm using a component very similar to the one below. The template is just to give a target for testing the click event, which works. What doesn't work is the `[class.menu-open]` host binding.

Using literals works (`'class': 'menu-open'`), as do extremely simple string expressions (`'[class]': '"menu-open"'`). Anything more complex than that is dead in the water with no error message.

For example the following host class binding doesn't work:

```js
@Component({
    selector: 'my-layout',
    host: {
        '[class.menu-open]': 'menuIsOpen',
        '(click)': 'toggleMenu()'
    },
    template: '<div style="width: 250px; height: 250px; background-color: blue;"></div>'
})
export class LayoutComponent {
    menuIsOpen = false;

    toggleMenu() {
        this.menuIsOpen = !this.menuIsOpen;
    }
}
```

*Edit:* This is with `2.0.0-alpha.50`.

**Comment by alexpods** [comment]
Hmm, everything works fine for me (see [this plunk](http://plnkr.co/edit/71J8wPHoHh1mF2bvtMp8?p=preview))

**Comment by robertdp** [comment]
The plunker works for me, but building it locally doesn't. So it's a problem with my build process somewhere.

(5 mins later...)

Okay, so I'm using `angular2-webpack-starter` as a base, but with a couple of tweaks. In an unlikely version of reality I accidentally removed `zone.js` from the list of packages to bundle with `angular2`, which silently broke some features but not others. Angular is currently missing dependency/bundling smarts.

Since my specific problem is no longer relevant, I'll go ahead and close this.

@alexpods Thanks for your time.
