### ISSUE TITLE
pipe content is not showing

### ISSUE THREAD

**Issue by Nilam-Pal** [angular/angular#57714]
### Describe the problem that you experienced

Pipe content is not visible showing 404 error
 pipes#built-in-pipes

### Enter the URL of the topic with the problem

https://angular.dev/guide/pipes#built-in-pipes

### Describe the actions that led you to experience the problem

Angular.dev

### Describe what you want to experience that would fix the problem

url issue

**Comment by JeanMeche** [comment]
Duplicate of #57704
