### ISSUE TITLE
Issue with accessing the 'subscribe' property in nested calls within Angular 2 due to it being undefined

### ISSUE THREAD

**Issue by theangular** [angular/angular#57713]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

I am trying to implement a subscription in company-list.component using the method getCompanies() from the company.service. However, I am encountering the following error:

Cannot read property 'subscribe' of undefined

From https://angulars.space/questions/issue-with-accessing-the-subscribe-property-in-nested-calls-within-angular-2-due-to-it-being-undefined

Here is the code snippet:

company.service.ts
 ```
getCompaniesOfUser() {
    let r;
    this.userService.getUser().subscribe(
      res=> r = res,
      err => console.log(err),
      ()=>(this.getCompaniesWithSpecificLink())
    )
  }

  getCompaniesWithSpecificLink() {    
    if (isAdmin == false) {
      url = '/user/companies';
    } else {
      url = '/companies';
    }
    return this.getCompanies(url);

  }

  getCompanies(url):Observable<Company[]> {  
    return this.http.get(this.host + url)
      .map((res:Response) => res.json());
  }
```
company-list.component.ts
```
companies:Company[];

public getTheCompanies() {
    this._companyService.getCompaniesOfUser()
      .subscribe(companies => this.companies = companies); <-- the error occurred here
}
```

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
