### ISSUE TITLE
[windows][dart][alpha.51] Transformer error on @View styleUrls 

### ISSUE THREAD

**Issue by avoivo** [angular/angular#5772]
I  have the following component

    @Component(
      selector: "main"
    )
    @View(
      templateUrl: "package:angular2_example/components/main_component.html",
      styleUrls: const ["package:angular2_example/components/main_component.css"]
    )
    class MainComponent{
      
    }

and when i execute 'pub build' i get the following

    [Info from Dart2JS]:
    Compiling angular2_example|web/main.dart...
    [Error from Dart2JS on angular2_example|web/main.dart]:
    packages\angular2_example\components\main_component.css.shim.dart:5:28:
    Can't find ']' to match '['.
    \n}'];lor:red;YLES = const ['div[_ngcontent-%COMP%]{
                               ^
    [Error from Dart2JS on angular2_example|web/main.dart]:
    packages\angular2_example\components\main_component.css.shim.dart:5:71:
    Expected a declaration, but got '}'.
    \n}'];lor:red;YLES = const ['div[_ngcontent-%COMP%]{
                                                                          ^

I have created an example [here](https://github.com/avoivo/angular2_example).

I also have tested it on a Ubuntu machine on which 'pub get' executed without any problems.

Dart VM versions on both machines is 1.13.0

**Comment by IgorMinar** [comment]
@kegluneq please take a look

**Comment by kegluneq** [comment]
Sorry to pass this on, but the transformer does not know anything about the content of the stylesheets, it just outputs whatever is passed to it. This looks like it has to do with the `StylesheetCompiler` output.

https://github.com/angular/angular/blob/master/modules_dart/transform/lib/src/transform/stylesheet_compiler/processor.dart

**Comment by tbosch** [comment]
Just tried with Dart 1.12 and Dart 1.13: This example works in Dartium as well as in Chrome (via dart2js). I did the following:

1. `git clone git@github.com:avoivo/angular2_example.git`
2. `cd /angular2_example`
3. `pub get`
4. `pub serve`
5. open `http://localhost:8080`

@avoivo Could you please try the same steps in a new temporary folder to be sure your reproduction case works? Btw, I tested on MacOSX. What OS are you using?

**Comment by avoivo** [comment]
@tbosch Just tried on a different pc with windows and i am also getting the same errors. The OS i am using in both those PCs is windows 8.1.

Also some new info that can be helpfull, when i chage the css file from this:
```
div{
color:red;
}
```
to this:
```
div{color:red;}
```

the transformer executes without an error . Seems that the newline character is responsible for the errors that i am getting.

**Comment by vicb** [comment]
From the description and the output file, it seems like "\n" are escaped in the output file but "\r" rewind to the start of the line. @kegluneq do we test that "\r\n" are correctly handle by the transformer (writer) ?

**Comment by kegluneq** [comment]
I don't think we have an explicit test for it, let me take a look

**Comment by kegluneq** [comment]
[_styleCodeGen](https://github.com/kegluneq/angular/blob/master/modules/angular2/src/compiler/style_compiler.ts#L76) calls [compiler/util.ts](https://github.com/kegluneq/angular/blob/master/modules/angular2/src/compiler/util.ts) to escape the incoming style strings, but that util does not escape '\r' characters.

In Dart, we could pass the incoming css lines through the [LineSplitter](https://api.dartlang.org/134830/dart-convert/LineSplitter-class.html) and avoid dealing with newlines altogether. I'm not sure what the equivalent would be in TS.

This should be tested along with util.
