### ISSUE TITLE
Page not found on Angular docs

### ISSUE THREAD

**Issue by ashishaugust22** [angular/angular#57723]
### Describe the problem that you experienced

When try to navigate to one of the cards, I get a page not found.
Here is the route: https://angular.dev/tools/cli/esbuild

### Enter the URL of the topic with the problem

https://angular.dev/tools/cli/esbuild

### Describe what you were looking for in the documentation

Details on ES Build

### Describe the actions that led you to experience the problem

Clicking on one of the card
<img width="362" alt="Screenshot 2024-09-08 at 18 42 38" src="https://github.com/user-attachments/assets/8f636efc-0b8d-4273-b257-64096f555826">

### Describe what you want to experience that would fix the problem

A page with all the details about the card.

### Add a screenshot if that helps illustrate the problem

<img width="1090" alt="Screenshot 2024-09-08 at 18 43 13" src="https://github.com/user-attachments/assets/584d4056-5d75-40e0-a238-5204f22242c7">

**Comment by ishon19** [comment]
Thanks! From what I can see, the link to the https://angular.dev/tools/cli/esbuild page was changed to https://angular.dev/tools/cli/build-system-migration, so I've linked the PR above to update the redirection.

**Comment by rchod** [comment]
Hi @ishon19 I did a small PR too, apperently it was just merged moments ago even though I didn't put the commit in a separate PR

**Comment by ishon19** [comment]
> Hi @ishon19 I did a small PR too, apperently it was just merged moments ago even though I didn't put the commit in a separate PR

Oh my bad, I didn't see a PR linked to this issue, so I thought it's still open. I can close mine then :) 

Could you also link the issue number in your merged PR, so that this issue can be closed.

**Comment by rchod** [comment]
Hello @thePunderWoman thank you for your help in my previous PR, this commit https://github.com/angular/angular/commit/c425c77e88b50410d697df8c7b7b3c7812414cc4 should close this issue

**Comment by ishon19** [comment]
> Hello @thePunderWoman thank you for your help in my previous PR, this commit [c425c77](https://github.com/angular/angular/commit/c425c77e88b50410d697df8c7b7b3c7812414cc4) should close this issue

Thanks @rchod! All yours, I closed my PR :)
