### ISSUE TITLE
Extraneous backslashes in "Setting up wildcard routes" section

### ISSUE THREAD

**Issue by diesieben07** [angular/angular#57720]
### Describe the problem that you experienced

The "Setting up wildcard routes" shows extraneous backslashes.

### Enter the URL of the topic with the problem

https://angular.dev/guide/routing/common-router-tasks#setting-up-wildcard-routes

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/user-attachments/assets/25c48f66-dedf-42c5-855a-e58b0f574444)

**Comment by rchod** [comment]
this issue has been fixed by https://github.com/angular/angular/commit/ffdcac4e0cd79f90afc32f200652bce71db57b7e
