### ISSUE TITLE
Error: This command is not available when running the Angular CLI outside a workspace.

### ISSUE THREAD

**Issue by SriyanshNahar** [angular/angular#57728]
### Describe the problem that you experienced

Error: This command is not available when running the Angular CLI outside a workspace.

**Comment by JeanMeche** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).
