### ISSUE TITLE
Bad link to pipe documentation

### ISSUE THREAD

**Issue by stefanloerwald** [angular/angular#57727]
### Describe the problem that you experienced

The link to the "pipe" documentation in https://angular.dev/best-practices/slow-computations#optimizing-slow-computations points to https://angular.dev/guide/pipes, but should likely direct to https://angular.dev/guide/templates/pipes#

### Enter the URL of the topic with the problem

https://angular.dev/best-practices/slow-computations

**Comment by JeanMeche** [comment]
Hi, thank you for reporting this issue, we have a pending PR to fix this #57706, so it should be fixed very soon.
