### ISSUE TITLE
Provide a diagnostic for missing Signal invocation in template interpolation when used with pipes

### ISSUE THREAD

**Issue by maxime1992** [angular/angular#57729]
### Description

This is a follow up of https://github.com/angular/angular/pull/49660

I have been refactoring a component to use a signal and forgot to update a bit in the template where I was passing the value to a pipe. So I was passing the signal to the pipe instead of the value and it didn't crash but made my app fail in a sneaky way as the pipe ended up returning false all the time.

I think it'd be nice to have a warning when sending signals to pipe as I don't see a good reason to pass a signal instead of a value directly

### Proposed solution

On top of #49660 have a check in the template to always call a signal, even if it's going through a pipe

### Alternatives considered

None

**Comment by zakhenry** [comment]
(Colleague of Maxime here) - all the [ngx-pipes booleans](https://github.com/danrevah/ngx-pipes/tree/master/src/ng-pipes/pipes/boolean) use `input: any` as argument, which is the original cause here

**Comment by JoostK** [comment]
Well, that's awkward.. 😅 

How about

```ts
import {Signal, signal, PipeTransform} from '@angular/core';

class Pipe implements PipeTransform {
  transform<T>(value: T extends Signal<unknown> ? never : T): boolean {
    return true;
  }
}

declare const pipe: Pipe;
pipe.transform(signal(''));
pipe.transform('');

```

[TS Playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbwMrAOYDsCGAbANHAZzSzzgAVgwBTAFSk3QIDNoQBfOJqCEOAcgACDVAFdsmKAHoAxtCp8A3ACgl08QQLlKVOKDDYqIKuhiaK1Og2atESuHBj1GLKCAA8NAHwAKAG44RKgAuOBo4KgAPGGMAE00UDBw3EXQAa3QIAHd0TzgAfjh0Kl8qKDgQmgBKEIAjCAgDBlt7eygqGBEodAcoQOV7NiVBpRiqNQkdWUZ4MG0Q8yplWeoAOkcrFxBvIkTsbz4+Ssql7TWna1d9w+UgA)

I don't think having a diagnostic is the way to go; given `ngx-pipes` it would be a guaranteed false positive for e.g. a `isSignal` pipe.

**Comment by alxhub** [comment]
+1 - this should be handled by type-checking in the pipe arguments
