### ISSUE TITLE
[IE9] There's no shim for requestAnimationFrame

### ISSUE THREAD

**Issue by wkwiatek** [angular/angular#5775]
When I tried to run pretty clean app with only Angular 2 deps (and webpack as a dev server) I got following error on IE9: 
```
TypeError: Object doesn't support property or method 'requestAnimationFrame' 
``` 

I found such a code in the library (testing): 
https://github.com/angular/angular/blob/master/modules/angular2/src/testing/shims_for_IE.js#L103

Maybe it should be added also to the core?

**Comment by pkozlowski-opensource** [comment]
> Maybe it should be added also to the core?

What do you mean? The current thinking is that users need to include polyfills for older browsers, we don't want to penalize users of modern browsers.

**Comment by wkwiatek** [comment]
For me it was quite strange to see that there's something like this in tests but not in a library itself. You know - tests work but real app doesn't. I see your point and I'm just curious whether it should be stated somewhere in docs because currently there's only mention about `es6-shim`.

**Comment by pkozlowski-opensource** [comment]
> For me it was quite strange to see that there's something like this in tests but not in a library itself. You know - tests work but real app doesn't.

We don't have any pollyfils as part of the "library", really. What we've got for tests is a minimal polyffil that makes tests pass (in other words, it only has things that are used by a framework). We really don't want to be (or at least not too much!) in the business of choosing polyfills for users, as those will depend on a browser etc.

Having said this I think we should have a section in the docs on IE compatibility. @wardbell WDYT?

**Comment by wardbell** [comment]
I think that is nothing but pain. 

You are probably right. But other priorities supersede for now, yes?

**Comment by pkozlowski-opensource** [comment]
Closing this one as we don't want to ship polyffils. I guess Ward is tracking docs update needed.
