### ISSUE TITLE
Angular browser compatibility suggestion

### ISSUE THREAD

**Issue by shanmugapriyak1788** [angular/angular#57751]
### Describe the problem that you experienced

Hi Team, 
We have an samsung and LG TV app developed in angular 11, 12 . We are npt able to upgrade the angular app to latest 
We are only getting blank screens. These TV have chromium version 58. Users can replace these TV . We have one -3 million customers using our application. 

It is a huge OTT app. We are unable to rewrite the app in angular latest or upgrade this app.

Please suggest a solution for us to move forward.

**Comment by JeanMeche** [comment]
The Angular only provides support for the 2 previous major versions (see our [support policy](https://angular.dev/reference/releases#support-window)). In your case, you should check the console to see what feature isn't support by those TV and either enable some downleveling or add the required polyfills.
