### ISSUE TITLE
markForCheck() triggers Change Detection.

### ISSUE THREAD

**Issue by michalgrzegorczyk-dev** [angular/angular#57758]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

Why markForCheck() function triggers change detection if this is not its destiny?

![image](https://github.com/user-attachments/assets/eb231ccf-db8e-43ab-b09d-54c2db85b6ff)

### Please provide the environment you discovered this bug in (run `ng version`)

```true
@angular-devkit/architect       0.1802.1 (cli-only)
@angular-devkit/build-angular   18.2.1
@angular-devkit/core            18.2.1 (cli-only)
@angular-devkit/schematics      18.2.1 (cli-only)
@schematics/angular             18.2.1 (cli-only)
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10
```

**Comment by michalgrzegorczyk-dev** [comment]
I checked this with Profiler https://chromewebstore.google.com/detail/angular-devtools/ienfalfjdbdpebioblfackkekamfmbnh

**Comment by JeanMeche** [comment]
Yes, this is a change that landed in v18 with the new hybrid change detection system. 

You can disable that with `provideZoneChangeDetection({ignoreChangesOutsideZone: true})`
