### ISSUE TITLE
Compatibility Issue with Angular 17.3.11 and Module Federation Packages Leading to Dependency Injection Errors

### ISSUE THREAD

**Issue by venkateshby** [angular/angular#57765]
### Which @angular/* package(s) are the source of the bug?

core, platform-browser

### Is this a regression?

Yes

### Description

I am trying to load a custom plugin with Angular version 17.3.11 but encountering the following issue. This occurs after updating the two packages "@angular-architects/module-federation" and "@angular-architects/module-federation-tools" to version 18.0.4.

TypeError: Cannot read properties of null (reading 'firstCreatePass')
    at providersResolver (core.mjs:27484:15)
    at definition.providersResolver (core.mjs:27745:24)
    at N_ (remoteEntry.js:1:2842558)
    at aS (remoteEntry.js:1:2842076)
    at nE (remoteEntry.js:1:2919565)
    at Bh (remoteEntry.js:1:2919719)
    at Module.n_ (remoteEntry.js:1:2920554)
    at template (907.b0dee35ac08d6609.js:1:5554)
    at o0 (remoteEntry.js:1:2838321)
    at g0 (remoteEntry.js:1:2846321)

However, if I revert "@angular-architects/module-federation" and "@angular-architects/module-federation-tools" to version 17.0.8 (which I was using previously with Angular 17.3.5), I encounter a different error even though BrowserModule is already imported.

RuntimeError: NG0402: A required Injectable was not found in the dependency injection tree. If you are bootstrapping an NgModule, make sure that the `BrowserModule` is imported.
    at Object.useFactory (core.mjs:31898:27)
    at Object.factory (core.mjs:3322:38)
    at core.mjs:3219:47
    at runInInjectorProfilerContext (core.mjs:866:9)
    at R3Injector.hydrate (core.mjs:3218:21)
    at R3Injector.get (core.mjs:3082:33)
    at injectInjectorOnly (core.mjs:1100:40)
    at ɵɵinject (core.mjs:1106:60)
    at injectArgs (core.mjs:1237:23)
    at multiRecord.factory (core.mjs:3193:45)

When using Angular 17.3.5, everything works fine. However, once I upgrade my plugin to Angular 17.3.11, it stops working. After some debugging, I found that the issue seems to be related to the @angular/core and @angular/platform-browser packages. If I keep these two package versions at 17.3.5 while upgrading the rest of the Angular packages to 17.3.11, everything works fine.

Here is the list of Angular packages and their versions currently in use:

"devDependencies": {
  "@angular-devkit/build-angular": "17.3.8",
  "@angular-devkit/core": "17.3.8",
  "@angular-devkit/schematics": "17.3.8",
  "@angular-eslint/eslint-plugin": "17.3.0",
  "@angular-eslint/eslint-plugin-template": "17.3.0",
  "@angular-eslint/template-parser": "17.3.0",
  "@angular/cli": "17.3.0",
  "@angular/compiler-cli": "17.3.11",
  "@angular/language-service": "17.3.11",
  "@nx/angular": "18.3.2",
  "@nx/eslint": "18.3.2",
  "@nx/eslint-plugin": "18.3.2",
  "@nx/jest": "18.3.2",
  "@nx/js": "18.3.2",
  "@nx/workspace": "18.3.2",
  "@schematics/angular": "17.3.0",
  "@swc-node/register": "1.9.0",
  "@swc/core": "1.5.0",
  "@swc/helpers": "0.5.2",
  "@types/jest": "29.4.0",
  "@types/node": "18.16.9",
  "@typescript-eslint/eslint-plugin": "5.58.0",
  "@typescript-eslint/parser": "5.58.0",
  "eslint": "8.57.0",
  "eslint-config-prettier": "9.0.0",
  "jest": "29.7.0",
  "jest-environment-jsdom": "29.7.0",
  "jest-preset-angular": "14.0.3",
  "jsonc-eslint-parser": "2.1.0",
  "nx": "18.3.2",
  "prettier": "2.6.2",
  "ts-jest": "29.1.0",
  "ts-node": "10.9.1",
  "typescript": "5.4.5"
},
"dependencies": {
  "@angular-architects/module-federation": "18.0.4",
  "@angular-architects/module-federation-tools": "18.0.4",
  "@angular/animations": "17.3.11",
  "@angular/cdk": "17.3.10",
  "@angular/common": "17.3.11",
  "@angular/compiler": "17.3.11",
  "@angular/core": "17.3.11",
  "@angular/elements": "17.3.11",
  "@angular/forms": "17.3.11",
  "@angular/platform-browser": "17.3.11",
  "@angular/platform-browser-dynamic": "17.3.11",
  "@angular/router": "17.3.11",
  "ag-grid-angular": "31.0.1",
  "ag-grid-community": "31.0.1",
  "dayjs": "1.11.10",
  "echarts": "5.4.3",
  "jexl": "2.3.0",
  "@ngx-formly/bootstrap": "6.1.8",
  "@ngx-formly/core": "6.1.8",
  "ngx-echarts": "8.0.1",
  "numeral": "2.0.6",
  "ramda": "0.28.0",
  "chart.js": "4.3.0",
  "rxjs": "7.8.1",
  "tslib": "2.3.0",
  "zone.js": "0.14.3"
}

### Please provide the exception or error you saw

```true
RuntimeError: NG0402: A required Injectable was not found in the dependency injection tree. If you are bootstrapping an NgModule, make sure that the `BrowserModule` is imported.
    at Object.useFactory (core.mjs:31898:27)
    at Object.factory (core.mjs:3322:38)
    at core.mjs:3219:47
    at runInInjectorProfilerContext (core.mjs:866:9)
    at R3Injector.hydrate (core.mjs:3218:21)
    at R3Injector.get (core.mjs:3082:33)
    at injectInjectorOnly (core.mjs:1100:40)
    at ɵɵinject (core.mjs:1106:60)
    at injectArgs (core.mjs:1237:23)
    at multiRecord.factory (core.mjs:3193:45)


TypeError: Cannot read properties of null (reading 'firstCreatePass')
    at providersResolver (core.mjs:27484:15)
    at definition.providersResolver (core.mjs:27745:24)
    at N_ (remoteEntry.js:1:2842558)
    at aS (remoteEntry.js:1:2842076)
    at nE (remoteEntry.js:1:2919565)
    at Bh (remoteEntry.js:1:2919719)
    at Module.n_ (remoteEntry.js:1:2920554)
    at template (907.b0dee35ac08d6609.js:1:5554)
    at o0 (remoteEntry.js:1:2838321)
    at g0 (remoteEntry.js:1:2846321)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.0
Node: 20.12.2
Package Manager: npm 10.5.0
OS: win32 x64

Angular: 17.3.11
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.8
@angular-devkit/build-angular   17.3.8
@angular-devkit/core            17.3.8
@angular-devkit/schematics      17.3.8
@angular/cdk                    17.3.10
@angular/cli                    17.3.0
@schematics/angular             17.3.0
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.3
```

**Comment by JoostK** [comment]
`@angular-architects/module-federation` is a custom build tool not maintained by the Angular team. I am not familiar with their versioning strategy but I would expect that their v18 releasee versions are made for Angular 18, not 17.

**Comment by venkateshby** [comment]
Thank you for your response. However, I am facing the same issue even with Angular 17.x versions. When I use @angular-architects/module-federation and @angular-architects/module-federation-tools version 17.0.5 with Angular 17.3.11, the error still occurs. It seems that the issue is not limited to the v18 release of these packages, as it persists in the 17.x versions as well.
