### ISSUE TITLE
missing styles in angular animations documentation page

### ISSUE THREAD

**Issue by DimitriTsikaridze** [angular/angular#57768]
### Describe the problem that you experienced

![image](https://github.com/user-attachments/assets/b624cb80-0720-40af-ab95-42be8c2472ae)

### Enter the URL of the topic with the problem

https://angular.dev/guide/animations#enabling-the-animations-module

**Comment by JeanMeche** [comment]
Hi, I'm not sure to understand, what kind of styles are you missing on this page ?

**Comment by DimitriTsikaridze** [comment]
> Hi, I'm not sure to understand, what kind of styles are you missing on this page ?

Hi sorry I thought there was supposed to be some kind of background like in other parts of website where it shows hints but as I looked around bit more I found out it was actual behaviour
