### ISSUE TITLE
unify bundle names

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#5776]
from: https://code.angularjs.org/2.0.0-alpha.52/

```
web_worker/                                        10-Dec-2015 09:09                   -
  ui.dev.js                                        10-Dec-2015 09:09             1143996
  worker.dev.js                                    10-Dec-2015 09:09             1707152
angular2-polyfills.js                              10-Dec-2015 09:09              118236
angular2-polyfills.min.js                          10-Dec-2015 09:09               30378
angular2-testing.umd.dev.js                        10-Dec-2015 09:09             5306510
angular2.dev.js                                    10-Dec-2015 09:09             1264363
angular2.js                                        10-Dec-2015 09:09             1264359
angular2.min.js                                    10-Dec-2015 09:09              642941
angular2.umd.dev.js                                10-Dec-2015 09:09             5006149
angular2.umd.js                                    10-Dec-2015 09:09             1598201
angular2.umd.min.js                                10-Dec-2015 09:09              589653
http.dev.js                                        10-Dec-2015 09:09               48415
http.js                                            10-Dec-2015 09:09               48411
http.min.js                                        10-Dec-2015 09:09               26501
router.dev.js                                      10-Dec-2015 09:09              116373
router.js                                          10-Dec-2015 09:09              116369
router.min.js                                      10-Dec-2015 09:09               62272
testing.js                                         10-Dec-2015 09:09               96654
testing.js.map                                     10-Dec-2015 09:09              107010
```

the ones that stick out are:

- [ ] why are web_worker bundles in special dir? why not prefix them with `angular2-webworker` or something and put in them in the same dir?
- [ ] `angular2.umd.js` and `angular2.js` are not equal when it comes to content, why make the name look like they differ only in format?
- [ ] `angular2-testing.umd.dev.js` is prefixed with `angular2-` but `testing.js` is not
- [ ] some bundles have `dev` variant, others don't - seems a bit random
- [ ] `web_worker` uses underscore separators while `-testing` and `-polyfills` use dashes. do we need both? maybe if we rename webworker bundles as suggested in the first item, we can avoid this inconsistency..

**Comment by IgorMinar** [comment]
related issue: https://github.com/angular/angular/issues/5777

**Comment by pkozlowski-opensource** [comment]
Yeh, there are number of inconsistencies, especially when it comes to System.register bundles. This bundle list was growing "organically" and don't share the same config / build pipeline.

Will work through this list, but there are a couple of items that need discussion:

> angular2.umd.js and angular2.js are not equal when it comes to content, why make the name look like they differ only in format?

How about `angular2-all.umd.js` ?

> angular2-testing.umd.dev.js is prefixed with angular2- but testing.js is not

So `angular2-testing.umd.dev.js` contains angular2-all _plus_ testing, while `testing.js` has only testing stuff without anything from ng2 core (System.register bundles are additive, UMD are not)

**Comment by pkozlowski-opensource** [comment]
So, if we put WebWorker aside for now, we are left with those items:

- [ ] `angular2.umd.js` and `angular2.js` are not equal when it comes to content, why make the name look like they differ only in format?
- [ ] `angular2-testing.umd.dev.js` is prefixed with `angular2-` but `testing.js` is not
- [ ] some bundles have `dev` variant, others don't - seems a bit random

Let me tackle those one-by-one below.

**Comment by pkozlowski-opensource** [comment]
> `angular2.umd.js` and `angular2.js` are not equal when it comes to content, why make the name look like they differ only in format?

True, `angular2.umd.js` has much more barrels. How about `angular2-all.umd.js`?

**Comment by pkozlowski-opensource** [comment]
> angular2-testing.umd.dev.js is prefixed with angular2- but testing.js is not

Right. So `angular2-` prefix is there since UMD bundle contains angular2 _all_ and testing. If we go with the previous item the only name I can think of would be `angular2-all-testing.umd.js`

**Comment by pkozlowski-opensource** [comment]
> some bundles have dev variant, others don't - seems a bit random

So, the only bundles that don't have dev variant (putting WebWorkers aside) are:
* `angular2-polyfills.js` - here dev / prod doesn't come into play as we are not bundling ng2 code here
*  `testing.js` -> actually this one should be `testing.dev.js` IMO

So the actionable item here could be: rename testing.js -> testing.dev.js

**Comment by pkozlowski-opensource** [comment]
As a summary, here is a proposal for actionable items. Rename:
* angular2.umd.js -> angular2-all.umd.js
* angular2-testing.umd.js -> angular2-all-testing.umd.js
* testing.js -> testing.dev.js

How does it sound?

**Comment by IgorMinar** [comment]
yup!
