### ISSUE TITLE
Timeline for stabilization of RxJS Interop

### ISSUE THREAD

**Issue by json-derulo** [angular/angular#57779]
### Description

All functionality of `@angular/core/rxjs-interop` is currently in Developer Preview. This prevents some people from using it, especially in a corporate environment. The `toSignal()` function in particular is important for wider usage of Signals.

According to the [Reactivity project board](https://github.com/orgs/angular/projects/31), with v19 it is planned to stabilize `input()`, `output()` and `effect()`, which is great news.

### Proposed solution

It would be awesome to also stabilize `takeUntilDestroyed()`, `toSignal()` and `toObservable()` with v19. Or otherwise, to communicate the timeline / blockers for their stabilization.

### Alternatives considered

The functionality remains in Developer Preview for an indefinite period.

**Comment by pkozlowski-opensource** [comment]
There is no plan to stabilise `@angular/core/rxjs-interop` in v19 - we still discover usage patterns and thinking of improving those APIs. There are very subtle consideration for the timing of RxJS and signals interoperability and we don't want to rush those things. Our current focus is on stabilising `input()`, `output()`, `model()`, signal-based queries and effect() for which we are more confident.
