### ISSUE TITLE
docs: fix broken link on CONTRIBUTING.md page

### ISSUE THREAD

**Issue by bulicovic** [angular/angular#57774]
### Describe the problem that you experienced

On the [CONTRIBUTING.md](https://github.com/angular/angular/blob/0ebb2be538301a9a05c9399dbf069de183068f7c/CONTRIBUTING.md) is the header  [Conding Rules:](https://github.com/angular/angular/blob/0ebb2be538301a9a05c9399dbf069de183068f7c/CONTRIBUTING.md#-coding-rules) which contains a broken link of DEVELOPER.md.

### Enter the URL of the topic with the problem

https://github.com/angular/angular/blob/0ebb2be538301a9a05c9399dbf069de183068f7c/CONTRIBUTING.md#-coding-rules

### Describe what you were looking for in the documentation

I read the article how to contribute to Angular.

### Describe the actions that led you to experience the problem

1. Open this link: [Conding Rules:](https://github.com/angular/angular/blob/0ebb2be538301a9a05c9399dbf069de183068f7c/CONTRIBUTING.md#-coding-rules) 
2. click on the "DEVELOPER.md." link (picture included below)
3. in the browser following link will be open https://github.com/angular/angular/blob/0ebb2be538301a9a05c9399dbf069de183068f7c/contributing-docs/building-and-testing-angular#formatting-your-source-code

<img width="1120" alt="image" src="https://github.com/user-attachments/assets/642cc139-d323-47de-be55-a35aed80de3f">
<img width="1413" alt="image" src="https://github.com/user-attachments/assets/f43c2bee-fcaa-4049-af8f-81dd36f62a4d">

### Describe what you want to experience that would fix the problem

There is a missing file ending in the link. The link should look like this:
https://github.com/angular/angular/blob/0ebb2be538301a9a05c9399dbf069de183068f7c/contributing-docs/building-and-testing-angular.md#formatting-your-source-code
**I can provide a fix**

### If this problem caused an exception or error, please paste it here

```true
404 - page not found
The 
0ebb2be538301a9a05c9399dbf069de183068f7c

 branch of 
angular

 does not contain the path 
contributing-docs/building-and-testing-angular.
```

**Comment by bulicovic** [comment]
I can provide the fix

**Comment by JeevanMahesha** [comment]
@JeanMeche  / @bencodezen we can close this issue. The changes are merged
