### ISSUE TITLE
document bundle contents, formats, and intended usage

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#5777]
we need to document the current state of our packaging. I suggest a table with all the bundle files on one axis and barrels + info about format, dev/prod, minified on the other axis

example:

filename | list of barrels | format | dev/prod | minified? | usage
------------|-------------------|----------|-------------|--------------|-------------
angular2.js | `angular2/core`, `angular2/common`, ... | System.register | dev | no | development with SystemJS

we should publish this as an md file under `modules/angular2/docs/bundles/overview.md` or similar. later we'll incorporate it into the dev guide..

once we have the docs we should copy them to the bundles folder that appears on npm as well as code.angularjs.org

- [ ] write the doc
- [ ] copy the doc to npm's bundles directory during build
- [ ] ensure that the doc is also copied to the right folder so that it appears on code.angularjs.org

**Comment by pkozlowski-opensource** [comment]
Definitively! Had this on my TODO list but was waiting till I'm done with all the re-shuffling of bundles and their content.

**Comment by IgorMinar** [comment]
I broke this down into subtasks. @pkozlowski-opensource can you please take care of this on Monday?

**Comment by pkozlowski-opensource** [comment]
@IgorMinar see: https://github.com/angular/angular/pull/5878

I've split it into 2 tables to not repeat 2 columns that would be the same (format and usage). PTAL
