### ISSUE TITLE
Bazel Hot reloading broken 

### ISSUE THREAD

**Issue by rchod** [angular/angular#57778]
I was trying to contribute by implementing a feature taged with "good first issue", so I cloned the repo, installed the deps, run yarn docs, started doing some changes in the source code  but my problem is when I change the code it's not reflected on browser, I have to stop the local server and restart it to see the changes on localhost, If I reload the page without restarting the server I just have a black screen, ... is there something missing in my workflow to be able to see changes ? .. I think this will discourage a lot new comers to contribute 

![image](https://github.com/user-attachments/assets/f2610a53-e02a-45cf-bc4f-97f51c670142)

**Comment by josephperrott** [comment]
The issue was that we were caching the index file from the original build and then the generated chunk names changed and were no longer correct in the templates script srcs.
