### ISSUE TITLE
Wrong type definition for AttributeMetadata

### ISSUE THREAD

**Issue by mgechev** [angular/angular#5778]
The type definition for `AttributeMetadata` is incorrect since alpha51.

```ts
export declare class AttributeMetadata extends DependencyMetadata {
    attributeName: string;
    constructor(attributeName: string);
    token: this;
           ^^^^
    toString(): string;
}
```

**Comment by robwormald** [comment]
@mgechev `this` is a new feature in Typescript 1.7 - http://blogs.msdn.com/b/typescript/archive/2015/11/30/announcing-typescript-1-7.aspx

**Comment by mgechev** [comment]
Ups, my mistake.

**Comment by robwormald** [comment]
no stress :+1:
