### ISSUE TITLE
Composed accent character input handling inconsistency

### ISSUE THREAD

**Issue by jakubkolesar** [angular/angular#57789]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

There seems to be an issue with `control.value` not updating properly in some browsers (excluding Firefox) when handling composed accent characters on **macOS**. For instance, when entering `"ahč"`, the last character (or any accent character) isn’t correctly registered in the event binding method. However, it is correctly captured when subscribing to `valueChanges` on the control itself.

https://github.com/user-attachments/assets/54d9ed09-1335-4872-911b-5540cbf89595

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-hwk3zh?file=src%2Fapp%2Fcomponents%2Fform-demo%2Fform-demo.component.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.2.4
Node: 18.20.3
Package Manager: npm 10.2.3
OS: linux x64

Angular: 18.2.4
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.4
@angular-devkit/build-angular   18.2.4
@angular-devkit/core            18.2.4
@angular-devkit/schematics      18.2.4
@schematics/angular             18.2.4
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10
```

**Comment by JeanMeche** [comment]
You directly hook onto the `input` DOM event, when doing `(input)=...`. This is a browser "issue".

**Comment by JeanMeche** [comment]
Interesting, I can confirm there is a difference between macOS and windows. 
The input in macOS enters the composition mode while it doesn't on windows. 

I'm not sure we can consider this an Angular issue but more a browser/OS one.

**Comment by jakubkolesar** [comment]
Thank you for providing the workaround. However the problem remains interesting since it's working normally in Firefox. I would assume this is a browser-specific issue.
