### ISSUE TITLE
Effect onCleanup cannot be triggered in unit test

### ISSUE THREAD

**Issue by MurhafSousli** [angular/angular#57785]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

I moved the code from `ngOnDestroy` to `onCleanup` function inside an `effect` and now I cannot refactor the test case.

To trigger effect in unit test, we use `Testbed.flushEffects()` but how to trigger the clean up function inside the effect?

Example:

```ts
effect((onCleanup: EffectCleanupRegisterFn) => {
  // ... some code

  onCleanup(() => {
    if (this._scrollbarsRef) {
      this.appRef.detachView(this._scrollbarsRef.hostView);
      this._scrollbarsRef.destroy();
    }
  });
});
```

```ts
 it('should destroy the dynamically created component', () => {
    const hostViewDestroySpy: jasmine.Spy = spyOn(scrollbar._scrollbarsRef.hostView, 'destroy');

    // trigger onCleanup??

    expect(hostViewDestroySpy).toHaveBeenCalled();
  });
```

Previously when code was inside `ngOnDestroy` I could just use

```ts
 it('should destroy the dynamically created component', () => {
    const hostViewDestroySpy: jasmine.Spy = spyOn(component._scrollbarsRef.hostView, 'destroy');

    component.ngOnDestroy();

    expect(hostViewDestroySpy).toHaveBeenCalled();
  });
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.2.3
Node: 20.11.1
Package Manager: npm 9.6.1
OS: win32 x64

Angular: 18.2.3
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... platform-server, router, ssr

Package                         Version
@schematics/angular             18.2.3
ng-packagr                      18.2.1
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10
```

### Anything else?

I am not sure if this is a missing function in the unit test or just undocumented

**Comment by jnizet** [comment]
There is a `destroy()` method on ComponentFixture. In my test, calling it does trigger the onCleanup function of effects created in thi fixture's component.

**Comment by pkozlowski-opensource** [comment]
The `onCleanup` function runs at two different points in time:
* whenever effect re-runs (in response to change in its dependencies);
* when an effect is destroyed.

This means that testing `onCleanup` requires one of the two above conditions. As noted in #57757 we should improve the docs on the timing but I don't think there is anything else for us to investigate / fix here.
