### ISSUE TITLE
TitleCasePipeComponent should be localized

### ISSUE THREAD

**Issue by david-bulte** [angular/angular#57787]
### Which @angular/* package(s) are relevant/related to the feature request?

common

### Description

In English, all words in a title are capitalized. But e.g. in Dutch only the first word is capitalized. I am wondering whether the TitleCasePipeComponent could take localization into account?

### Proposed solution

Let TitleCasePipeComponent take into account the current locale. If that is not possible, we should be able to configure it ourselves (globally)

### Alternatives considered

We could write our own component. But it is a shame we have a pipe for titles and cannot use it.

**Comment by JoostK** [comment]
I don't think this is something we'd be willing to include in the framework. The current title case already isn't specific to English, in the sense that words like "and", "or", etc. are also capitalized. _All_ words are capitalized.

**Comment by david-bulte** [comment]
Fair enough I guess, I always found it a bit arbitrary to have this in the framework :)

**Comment by JeanMeche** [comment]
Localization is hard unless is hard unless it is provided by the platform. Currently, ECMA only defined `toLocaleUpperCase`/`toLocaleLowerCase`. We could only provide such feature if there was an API for that.

**Comment by pkozlowski-opensource** [comment]
Agreed with @JoostK and @JeanMeche - we don't have plans for the localized version of `TitleCasePipe`
