### ISSUE TITLE
Browser Support page is inaccessible to unsupported browsers

### ISSUE THREAD

**Issue by SonicPurity** [angular/angular#57795]
### Describe the problem that you experienced

Was on earthquake.usgs.gov. Page would not load. USGS provided a link to “view supported browsers”, linking to https://angular.io/guide/browser-support. This page would not load in the unsupported WWW browser, leaving the user (me) at a loss.

Went to the trouble of using a current browser. _Still_ would not load, because Javascript was disabled.

Browser support pages are special: they need to be as least-common-denominator as possible, to be acceptable to even crazy old browsers and ones with JS disabled or unavailable. Y’all behind Angular, USGS and other Angular users, or—better—both, should maintain a bare-bones pure text HTML 2 or less Supported Browsers page. Anything less is a failure to communicate across a wide range of populations, circumstances, and needs.

Thank you for considering this point.

### Enter the URL of the topic with the problem

https://angular.io/guide/browser-support

### Describe what you were looking for in the documentation

Basic plain text WWW browser support information, ideally aimed for a general audience.

### Describe the actions that led you to experience the problem

Had the audacity to use Safari 12 macOS in 2024, which still works fine on many sites, but not parts of USGS nor even GitHub any more. Wanted to read to learn what USGS considered a passable browser/version, was sent to angular.io, and could not access any relevant information.

### Describe what you want to experience that would fix the problem

Redo the Browser Support page in the most dirt-basic text-only HTML possible, so every WWW browser including ancient ones can understand the angular.io requirements and take action accordingly.

**Comment by atscott** [comment]
This seems like a problem with an outdated link, as this issue doesn't exist on the new docs site, which would work with javascript disabled: https://angular.dev/reference/versions/#browser-support

**Comment by SonicPurity** [comment]
I’ll try and contact USGS and let them know of this link. However, it still fails in Safari 12 on macOS 10.12 Sierra, whether JS is enabled or not. There’s some issue with the CSS whereby the whole page is black, other than a couple of code boxes. Disabling CSS makes the content viewable. This is fine for the intended audience of tech users who may want to implement things with angular, but hostile for members of the general public who might get referred here.

Maybe the solution is having any public-facing site which uses Angular host their own browser support page, making it their responsibility. I’ll bring that up with USGS (assuming i can contact anyone). Might be worth having something in an appropriate place in Angular deployment recommendations documentation strongly urging end users of Angular to host their own highly-accessible browser support page(s).

It would still be nice if Angular’s own page was visible on a wider range of old/weird WWW browsers. A dirt-simple HTML page ought to achieve that.

Thanks for looking into this. Off to USGS i go….

**Comment by JeanMeche** [comment]
> It would still be nice if Angular’s own page was visible on a wider range of old/weird WWW browsers. A dirt-simple HTML page ought to achieve that.


@SonicPurity This is already the case with the new docs on [angular.dev](https://angular.dev), the content is pre-rendered and doesn't require javascript to be displayed.

**Comment by atscott** [comment]
@JeanMeche I think the browser is so old that the css doesn’t work so it doesn’t display. I’m leaning towards closing this issue. Our browser support page is not meant to be a general purpose go-to for any website to link to when a user’s browser is unsupported but rather a reference for those looking to use Angular to build their site.

**Comment by JeanMeche** [comment]
As @atscott said, our doc page is not a reference in terms of browser support as we don't state the exact versions there.
