### ISSUE TITLE
Stop reexporting Observable via angular2/core

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#5780]
blocked on https://github.com/angular/angular/pull/5624

**Comment by jeffbcross** [comment]
I think @vsavkin is working on this.

**Comment by kylecordes** [comment]
I think this was fixed by commit 43f42d9c6e119bcb7357e741e95f7da6809d4dc2

**Comment by IgorMinar** [comment]
Yup.. Fixed by 43f42d9
