### ISSUE TITLE
Brave browser: error code attribute-directives

### ISSUE THREAD

**Issue by Jordan-Hall** [angular/angular#57812]
### Describe the problem that you experienced

Navigating directly to https://angular.dev/guide/directives/attribute-directives/ causes error code 5 with shield up and down. 

### Enter the URL of the topic with the problem

https://angular.dev/guide/directives/attribute-directives

### Describe what you were looking for in the documentation

Error code 5

### Describe the actions that led you to experience the problem

if you navigate to the page via https://angular.dev/guide/directives it breaks but if you navigate it via https://angular.dev/guide/directives/directive-composition-api it works fine

### Describe what you want to experience that would fix the problem

Should be able to navigate to the page

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/user-attachments/assets/673bb0f2-5d73-4966-ba53-7244429e4d89)

### If this problem caused an exception or error, please paste it here

No errors in console

### If the problem is browser-specific, please specify the device, OS, browser, and version

Brave Linux [Version 1.68.137 Chromium: 127.0.6533.100 (Official Build) unknown (64-bit)](https://brave.com/latest/)

**Comment by JeanMeche** [comment]
This is a Chromium issue that was fixed in v128. Please update your browser.

**Comment by Jordan-Hall** [comment]
Cheers sorry about that. Brave not showing their an update like normal. I'll update it now
