### ISSUE TITLE
[doc] Incorrect Spelling and Value for `preserveWhitespaces` in Advanced Configuration

### ISSUE THREAD

**Issue by waitingwittykitty** [angular/angular#57817]
### Describe the problem that you experienced

In the Angular documentation, the property `preserveWhitespaces` is incorrectly spelled as `preserveWhitespace`. Additionally, the value is stated as `false`, while it should be `true` to properly preserve whitespaces in templates.
You can find the error in the `PreserveWhitespace` section of the Advanced Configuration guide at the following link: [Advanced Configuration](https://angular.dev/guide/components/advanced-configuration#preservewhitespace).

**Incorrect Spelling**: The property name should be consistently referred to as `preserveWhitespaces` instead of `preserveWhitespace`.
**Incorrect Value**: The value should be `true` instead of `false` to align with the intended behavior of preserving whitespace in component templates.

### Enter the URL of the topic with the problem

https://angular.dev/guide/components/advanced-configuration#preservewhitespace

### Describe what you want to experience that would fix the problem

1. Ensure consistency in the spelling as `preserveWhitespaces` across all documentation references.
2. Modify the section title from `PreserveWhitespace` to `PreserveWhitespaces`.
3. Clearly state that the value for `preserveWhitespaces` should be `true` to keep whitespaces.

**Comment by Ingila185** [comment]
![image](https://github.com/user-attachments/assets/22a6f657-46de-483e-9a2f-6a4e259ea905)

Adding image for better visibility.

**Comment by bencodezen** [comment]
Thanks for filing the issue @waitingwittykitty! It looks like the PR has been issued and merged, so the issue should be solved. Appreciate it!
