### ISSUE TITLE
Is `RouteReuseStrategy` still supported?

### ISSUE THREAD

**Issue by alextse** [angular/angular#57811]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

The methods from a custom `RouteReuseStrategy` doesn't seem to be called at all.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-u6xhgs?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
I have the `alert()` call in some of the functions in the custom `RouteReuseStrategy` but none of them seems to be called when navigating between routes.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.2.4
Node: 18.20.3
Package Manager: npm 10.2.3
OS: linux x64

Angular: 18.2.4
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.4
@angular-devkit/build-angular   18.2.4
@angular-devkit/core            18.2.4
@angular-devkit/schematics      18.2.4
@schematics/angular             18.2.4
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10
```

**Comment by JeanMeche** [comment]
You shouldn't be extending the `RouteReuseStrategy`, you service doesn't get injected because of that.  You shoul rather implement it (or extend `BaseRouteReuseStrategy`).
