### ISSUE TITLE
docs: The pipe ("|") character is not escaped in markdown tables 

### ISSUE THREAD

**Issue by can-oezkan** [angular/angular#57819]
### Describe the problem that you experienced

When the pipe character is used to represent a union type, e.g. `number | string`, the pipe character should be escaped. This causes the pipe character to be interpreted as a column delimiter, resulting in incorrect table rendering.

The bug has been introduced by this commit: https://github.com/angular/angular/commit/b2ba94543637a5e94af4411bae62891c43ebe359

### Enter the URL of the topic with the problem

https://angular.dev/reference/configs/workspace-config#angular-cli-configuration-options

### Describe what you were looking for in the documentation

The `valueType` column for the `packageManager` option should show all valid package managers (i.e. `npm` | `cnpm` | `pnpm` | `yarn`, not just `npm`.

This is just an example. This issue is present several times.

**Comment by pkozlowski-opensource** [comment]
Fixed in #57823
