### ISSUE TITLE
Nested Signal is not rendered in the view

### ISSUE THREAD

**Issue by DevJaGz** [angular/angular#57841]
### Which @angular/* package(s) are the source of the bug?

core, zone.js

### Is this a regression?

Yes

### Description

Based on the following signal structure, the message is not rendered in the view after the signal is updated, why?:

```typescript
interface State {
  conversation: WritableSignal<Conversation | null>;
}

interface Conversation {
  title: string;
  messages: {
    [messageId: string]: WritableSignal<Message>;
  };
}

interface Message {
  content: string;
}

// Component class
@Component({
  selector: 'app-root',
  standalone: true,
  imports: [JsonPipe],
  template: `
    <h1>Conversation:</h1>
    <pre>{{conversation() | json}}</pre>
    <hr>
    <h1>Messages in conversation:</h1>
    <pre>{{messages() | json}}</pre>
  `,
})
export class App implements OnInit {
  name = 'Angular';
  state: State = {
    conversation: signal(null),
  };

  conversation = computed(() => this.state.conversation());
  messages = computed(() => this.conversation()?.messages);

  ngOnInit() {
    setTimeout(() => {
      console.log('Trigged By First Time!');
      this.state.conversation.set({
        title: 'Trigged By First Time!',
        messages: {},
      });
      console.log('Messages:', this.conversation()?.messages);
    }, 4_000);

    // Why the "first" property is not displayed in the view?? - as you can see in the console.log it is printed
    setTimeout(() => {
      console.log('Trigged By Second Time!');
      this.state.conversation.set({
        title: 'Trigged By Second Time!',
        messages: {
          first: signal({
            content: 'This is a message',
          }),
        },
      });
      console.log('Messages:', this.conversation()?.messages);
    }, 8_000);
  }
}
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-aygixr?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
{}
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.0.7
Node: 20.16.0
Package Manager: npm 10.8.2
OS: linux x64

Angular: 18.0.5
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.7
@angular-devkit/build-angular   18.0.7
@angular-devkit/core            18.0.7
@angular-devkit/schematics      18.0.7
@angular/cli                    18.0.7
@schematics/angular             18.0.7
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.7
```

### Anything else?

Should be render at something like: `{ first: ...}`

**Comment by jnizet** [comment]
Hi @DevJaGz 

The issue can be summarized to 

```ts
JSON.stringify({ first: signal('hello') }); // displays `{}`
```

and that's expected because JSON.stringify (which is used by the JSON pipe) omits properties of type function in object. And a signal is a function.

If you actually display the signals values in the template, not using the JSON pipe, you'll see that everything is displayed as expected. See https://stackblitz.com/edit/angular-t3b6w9?file=src%2Fmain.ts for example.

**Comment by JeanMeche** [comment]
Per above, this works as expected.

**Comment by DevJaGz** [comment]
> Hi @DevJaGz
> 
> The issue can be summarized to
> 
> ```ts
> JSON.stringify({ first: signal('hello') }); // displays `{}`
> ```
> 
> and that's expected because `JSON.stringify` (which is used by the JSON pipe) omits properties of type function in objects. And a signal is a function.
> 
> If you actually display the signals values in the template, not using the JSON pipe, you'll see that everything is displayed as expected. See https://stackblitz.com/edit/angular-t3b6w9?file=src%2Fmain.ts for example.

Hi @jnizet, you're right! Thank you so much for your help! I really appreciate it.
