### ISSUE TITLE
Using `ComponentFixtureAutoDetect` in a zoneful test triggers CD too early (causing errors like NG0950)

### ISSUE THREAD

**Issue by yjaaidi** [angular/angular#57856]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

When using `ComponentFixtureAutoDetect` in a zoneful test, a change detection cycle is triggered before inputs have the chance to be set.

In the example below, the test will pass but a first change detection cycle will be triggered on our component causing an `NG0950` error because the template tries to read the `message` required input while it is not set yet.

```ts
TestBed.configureTestingModule({
  providers: [
    {
      provide: ComponentFixtureAutoDetect,
      useValue: true
    }
  ]
});
const fixture = TestBed.createComponent(Greetings);
fixture.componentRef.setInput('message', 'Hello!');
await fixture.whenStable();
expect(fixture.nativeElement.textContent).toBe('Hello!');

@Component({
  template: `{{message()}}`
})
class Greetings {
  message = input.required<string>();
}
```

This seems to happen because:
1. when setting `ComponentFixtureAutoDetect` to `true`, `TestBed.createComponent` will immediately attach the view to the `ApplicationRef`.
2. then a tick is triggered synchronously here: https://github.com/angular/angular/blob/87e025ae7844a11f7af0173958ae1c8295dff080/packages/core/src/change_detection/scheduling/ng_zone_scheduling.ts#L48-L60
3. so change detection is triggered on our component before we get a chance to call `ComponentRef#setInput` and the signal is read in the template before it is set.

## Questions
A. should the first scheduled tick here be scheduled instead of executed synchronously?
https://github.com/angular/angular/blob/87e025ae7844a11f7af0173958ae1c8295dff080/packages/core/src/change_detection/scheduling/ng_zone_scheduling.ts#L57
B. or should the component attachment to the `ApplicationRef` be scheduled instead of done synchronously?
Cf. https://github.com/angular/angular/blob/87e025ae7844a11f7af0173958ae1c8295dff080/packages/core/testing/src/component_fixture.ts#L111
C. should the imperative `ComponentFixture#autoDetectChanges()` be preferred to `ComponentFixtureAutoDetect`? but in that case, the test will not be zoneless-ready, so what would be the most versatile alternative?

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/testbed-required-input-auto-detect-error-repro?file=src%2Fgreetings.spec.ts

### Please provide the exception or error you saw

```true
Error: NG0950: Input is required but no value is available yet. Find more at https://angular.dev/errors/NG0950
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 19.0.0-next.6
Node: 22.4.0
Package Manager: bun 1.1.21
OS: darwin arm64

Angular: 19.0.0-next.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.0-next.6
@angular-devkit/build-angular   19.0.0-next.6
@angular-devkit/core            19.0.0-next.6
@angular-devkit/schematics      19.0.0-next.6
@angular/cli                    19.0.0-next.6
@schematics/angular             19.0.0-next.6
rxjs                            7.8.1
typescript                      5.6.2
zone.js                         0.15.0
```

### Anything else?

Here are a few workarounds:
- using the imperative API _(i.e. `ComponentFixture#autoDetectChanges()`)_ instead and calling it after setting the initial inputs
- using zoneless testing _(i.e. `provideExperimentalZonelessChangeDetection()`)_

**Comment by atscott** [comment]
Closing in favor of canonical issue: https://github.com/angular/angular/issues/57858

**Comment by atscott** [comment]
> C. should the imperative ComponentFixture#autoDetectChanges() be preferred to ComponentFixtureAutoDetect? but in that case, the test will not be zoneless-ready, so what would be the most versatile alternative?

There is no way to make a zone-based test fully zoneless ready. Many operations in zone-based tests cause a synchronous `ApplicationRef.tick` (and would not require any `await fixture.whenStable` or `fixture.detectChanges`). This is never the case for zoneless tests.
