### ISSUE TITLE
Ivy compiling error: Cannot destructure property 'pos' of 'file.referencedFiles[index]' as it is undefined.

### ISSUE THREAD

**Issue by PedroS5499** [angular/angular#57850]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

when run ng build on shared library ivy compiler gave generic error

Cannot destructure property 'pos' of 'file.referencedFiles[index]' as it is undefined.

### Minimal Reproduction

ng build shared
[log.txt](https://github.com/user-attachments/files/17028197/log.txt)

### Exception or Error

```text
enable "traceResolution" on tsConfig.json have log output attach on log.txt
```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 18.2.4
Node: 20.15.1
Package Manager: npm 10.8.3
OS: win32 x64

Angular: 18.2.4
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, material
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.4
@angular-devkit/build-angular   18.2.4
@angular-devkit/core            18.2.4
@angular-devkit/schematics      18.2.4
@schematics/angular             18.2.4
ng-packagr                      18.2.1
rxjs                            7.8.1
typescript                      5.5.4
webpack                         5.94.0
zone.js                         0.14.10
```

**Comment by JoostK** [comment]
Without a runnable reproduction this won't be actionable to us.

**Comment by PedroS5499** [comment]
[APP-Core.zip](https://github.com/user-attachments/files/17030203/APP-Core.zip)

attach minimal project to reproduction.
After unzip,
Run:
```
npm i
npm run build
```

**Comment by PedroS5499** [comment]
founded possible cause/origin off error on typescript compiler:

https://github.com/search?q=repo%3Amicrosoft%2FTypeScript%20file.referencedFiles%5Bindex%5D&type=code

**Comment by JoostK** [comment]
> [APP-Core.zip](https://github.com/user-attachments/files/17030203/APP-Core.zip)
> 
> attach minimal project to reproduction. After unzip, Run:
> 
> ```
> npm i
> npm run build
> ```

These steps do not reproduce for me. Note that there's no lockfile included so I may have tested with slightly different dependencies.

**Comment by ATalaveraDev** [comment]
For me the issue dissapeared after removing `"composite": true` in the compiler options of `tsconfig.app.json` file

**Comment by PedroS5499** [comment]
Hi everyone, we found the issue. 
Was on tsconfig.json, with double relative paths with similar paths.
commented worked just fine

![image](https://github.com/user-attachments/assets/4bdb9718-c38c-4eff-979e-88acf7bffd72)

**Comment by vahid18u** [comment]
I encountered the same issue, but I found a solution: 
I have a workspace with two project. an application project and a library project. I was using a component from the application inside the library. While I could serve the application without issue, the error appeared when I tries to build the library.

**Comment by pumano** [comment]
Got that too while build some my libs via nx and ng-packagr, maybe somehow affected by https://github.com/microsoft/TypeScript/issues/58446

Looks like:

```bash
Reusing resolution of module '@typescript/lib-es2018/asynciterable' from '/Users/user/project/front-app/libs/cdk/__lib_node_modules_lookup_lib.es2018.asynciterable.d.ts__.ts' of old program, it was not resolved.
Reusing resolution of module '@typescript/lib-es2015/symbol' from '/Users/user/project/front-app/libs/cdk/__lib_node_modules_lookup_lib.es2015.symbol.d.ts__.ts' of old program, it was not resolved.
Reusing resolution of module '@typescript/lib-es2015/iterable' from '/Users/user/project/front-app/libs/cdk/__lib_node_modules_lookup_lib.es2015.iterable.d.ts__.ts' of old program, it was not resolved.

```

**Comment by DeabitTech** [comment]
okay mates but is still an issue, any true resolution?

**Comment by JoostK** [comment]
> okay mates but is still an issue, any true resolution?

@DeabitTech Please provide a reproduction to enable investigating this issue.

**Comment by crowmagnumb** [comment]
I also got this issue because I put "composite: true" in my nx root tsconfig.json because otherwise I get linter errors all over the place telling me that my referenced tsconfig must have "composite: true". But removing it again fixed the issue. I'm so confused about how I'm supposed to be using composite: true so that I can satisfy everything.

**Comment by nirmana** [comment]
In case this helps anyone: I had the same issue, and it turned out to be caused by referencing a file outside of my library's directory. Once I moved the file into the library and updated the reference paths, the issue was resolved.

**Comment by zakhenry** [comment]
I encountered this in an NX monorepo, the cause for me was a `package.json` of a buildable lib was misnamed (I had `@namespace/lib-child` when it should have been `@namespace/lib/child` to match exactly the name in `tsconfig.base.json`.

**Comment by julianpoemp** [comment]
> I also got this issue because I put "composite: true" in my nx root tsconfig.json because otherwise I get linter errors all over the place telling me that my referenced tsconfig must have "composite: true". But removing it again fixed the issue. I'm so confused about how I'm supposed to be using composite: true so that I can satisfy everything.

thank you very much! This fixed the issue for me

**Comment by samuelkavin-stampede** [comment]
In some cases, especially when working with an Nx library, you may want to structure components in separate folders within the library. To import files across different folders, it may be necessary to add an `ng-package.json` file in each folder.

**Comment by samuelkavin** [comment]
In some cases, especially when working with an Nx library, you may want to structure components in separate folders within the library. To import files across different folders, it may be necessary to add an `ng-package.json` file in each folder.
