### ISSUE TITLE
Proposal: single-source documentation site

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#579]
This is how I think we should build Angular 2 documentation site: auto-generate it from shared sources to all supported languages.

# Motivation

Users of Angular 2 have a choice of programming language. Maintaining a separate documentation site for every supported language would be wasteful. We should also strive for consistency, accuracy and completeness across all supported languages.

# Proposal

Generate the site from AtScript and HTML (or Markdown) sources. Use AtScript for code snippets. Use HTML or Markdown for prose. Code snippet boxes show up with little tabs next to them allowing the reader to switch between languages. The sticky query parameter lang=dart|es5|es6|... would set the language globally across all code examples.

## Accuracy

To keep the docs accurate the code snippets will be tested on the CI server.

**Comment by mhevery** [comment]
:+1:

**Comment by mhevery** [comment]
Closing as this is how we generate docs.
