### ISSUE TITLE
method listening to (custom-event) triggered by EventEmitter runs in Windows scope.

### ISSUE THREAD

**Issue by CarreraPHP** [angular/angular#5791]
The method binded to the custom event triggered using EventEmitter is executed in the Window Scope and not based on the Scope of the class it belongs to. In the sample code below, i am passing items array to the method 'onCardBoundedRectAvailable' which is already available in Viewport.ts file yet  unaccessible.

I am using '2.0.0-alpha.47' version of angular2.

Viewport.html:
```html
<div id="chartTitle" class="large mono bold">
        <span>{{name}}</span>
        <i class="icon icon-edit medium" (click)="editor.config.toggle()"></i>
    </div>
    <div id="chartscene">
        <pb-card *ng-for="#item of items" 
            [card-item]="item" 
            [style.left.px]="item.internal.left" 
            [style.top.px]="item.internal.top" 
            (rect-available)="onCardBoundedRectAvailable($event, items)" />
    </div>
```

Viewport.ts:
```typescript
@Component({
	selector: 'pb-viewport',
	templateUrl: 'app/components/viewport/Viewport.html',
	directives: [Card, CORE_DIRECTIVES],
	providers: [ChartService]
})

export class Viewport implements OnInit, OnDestroy, OnChanges {
	static CARD_GAP = 100;
	@Input('pb-name') name: string;
	public items:CardService[];
	
	constructor(private chartService:ChartService) {
		// debugger;
		// chartService.add();
		this.items = chartService.getAll();
		// console.log("This is a log generated with viewport...", this.items);
	 }

	ngOnInit() {
		// console.log("viewport : initialised");
	}
	
	ngOnChanges(changes: {[key:string]:SimpleChange}) {
		
	 }
	
	ngOnDestroy() { }
	
	onCardBoundedRectAvailable(prop:any, items:CardService[]) {		
		let refLeft = (prop.item.internal.left) + prop.rect.width + Viewport.CARD_GAP;
		let refTop = (prop.item.internal.left) + prop.rect.height + Viewport.CARD_GAP;
		// let refLeft = (prop.item.internal.left > prop.rect.left ? prop.item.internal.left : prop.rect.left) + prop.rect.width + Viewport.CARD_GAP;
		
		console.log("viewport listening", arguments);
		ListWrapper.forEachWithIndex(prop.item.options, function(opt:OptionInterface, k){
			// console.log("viewport listening", prop, this);
			
			// items referenced in the options should be placed to the right with the GAP.
			ListWrapper.forEachWithIndex(items, function(item:CardService, ik){
				if(item.name == opt.reference){
					item.internal.left = refLeft;
				}
			});
			
			for(var i = items.length-1; i >= 0; i--){
				
			}
		});
	}
}
```

Card.ts
```typescript
@Component({
	selector: 'pb-card',
	templateUrl: 'app/components/card/Card.html',
	directives: [CORE_DIRECTIVES]
})

export class Card implements OnInit, AfterViewInit, AfterContentInit {
	@Input('card-item') item: CardService;
	@Output('rectAvailable') BoundedRect: EventEmitter<any> = new EventEmitter();
	
	private _internal:InternalService;

	constructor(private elRef: ElementRef) {

	}

	ngOnInit() {
		// console.log("within card item, ", this.item);
	}

	ngOnChanges(changes: { [key: string]: SimpleChange }) {
		console.log("data assigned : ", changes);
		this._internal = changes['item'].currentValue.internal;
	}

	ngAfterViewInit() {
		this.emitBoundedRect();
	}

	ngAfterContentInit() {
		// console.log("Content Init : ", this.elRef.nativeElement, arguments);
		// this.emitBoundedRect();
	}
	
	ngAfterViewChecked() {
		console.log(this.item.name, this.item.internal.left, this._internal.left);
		// this.emitBoundedRect();
	}

	ngAfterContentChecked() {
		// this.emitBoundedRect();
	}
	
	emitBoundedRect() {
		let el = this.elRef.nativeElement,
			elRect = el.getBoundingClientRect();
		// console.log("View Init : ", elRect.height, elRect.left, elRect.top);
		this.BoundedRect.emit({
			event: 'init',
			rect: {
				height: elRect.height,
				width: elRect.width,
				left: elRect.left,
				top: elRect.top
			},
			item: this.item,
			el: el
		});
	}

	highlightRelation(cardCmp, enableAction) {

	}

	@HostListener('click', ['$event']) OnHostClick(event) {
		// console.log("tiggered when click is made", arguments);
	}
}
```

I have not included the html template as it is not relavant to the issue here. The complete source can be found @ https://github.com/CarreraPHP/Playbook. It is based on the 5mins quickstart code.

**Comment by vicb** [comment]
Similar to https://github.com/angular/angular.io/issues/475 ?

We should investigate this.

/cc @IgorMinar

**Comment by pkozlowski-opensource** [comment]
@vicb I don't think it is related to the issue you've linked, see my comment in https://github.com/angular/angular/issues/5823#issuecomment-163877937

@CarreraPHP could you please prepare a plunker that reproduces the issue? Please use the latest ng2 version (alpha.52 as of today)

**Comment by CarreraPHP** [comment]
@pkozlowski-opensource, I am unable to reproduce the issue in plunker based on 'aplha47' without ListWrapper. However, the issue is happening within the nested 'ListWrapper.forEachWithIndex' callback method. The callback is not getting the properties of the class as part of the 'closure'.

<img width="821" alt="screen shot 2015-12-11 at 6 17 50 pm" src="https://cloud.githubusercontent.com/assets/422070/11744179/1617425c-a034-11e5-8012-c752a8e73898.png">

**Comment by pkozlowski-opensource** [comment]
> I am unable to reproduce the issue in plunker based on 'aplha47' without ListWrapper. 

@CarreraPHP you should check with alpha.52 and send a plunk with a reproduction scenario (we can't confirm / fix bug if we can't see a reproduction scenario). In any case `ListWrapper` is a private API that you shouldn't be using.

**Comment by CarreraPHP** [comment]
@pkozlowski-opensource I recently started learning angular2 and haven't understood all the aspects of the API. Here is the plunk url based on alpha.52 http://plnkr.co/uT1PhCimLeGlGj98drqn. The custom-event is working fine in it but the properties/methods of the class are undefined(not available as part of closure) within the callback for  ListWrapper forEachWithIndex.

**Comment by pkozlowski-opensource** [comment]
@CarreraPHP this is really more of a JS question ("what `this` means in JavaScript) than a ng2 question. In short: if you want to preserve lexical scope of `this` use fat arrow function (`=>`) instead of a regular function: http://plnkr.co/edit/73uKHWLAixzsxSzumNOv?p=preview

So, nothing to do with ng2 in the end. And hey, you really should _not_ use `ListWrapper` - it is a private API (and one that is not terribly useful outside of ng2 internals TBH)

**Comment by vicb** [comment]
Thanks Pawel !

**Comment by CarreraPHP** [comment]
@pkozlowski-opensource Thank you very much for explaining it & sorry for wrongly reporting an issue.
