### ISSUE TITLE
[IE9] Including router produces error

### ISSUE THREAD

**Issue by wkwiatek** [angular/angular#5792]
I made a simple app to test compatibility with IE and it seems that adding router (`RouteConfig` and `<router-outlet>`) gives following error: 
```
TypeError: Unable to get value of the property 'contains': object is null or undefined
```
I can't really say which line exactly produces the error (debugging on IE is really painful, especially on VM - any tips regarding that are welcome).

Main component looks like this: 
```js
import {Component} from 'angular2/angular2';
import {RouteConfig, ROUTER_DIRECTIVES} from 'angular2/router';

import {TestComponent} from './components/test';

@Component({
  selector: 'app',
  template: '<router-outlet></router-outlet>',
  directives: [ROUTER_DIRECTIVES]
})
@RouteConfig([
  { path: '/', component: TestComponent }
])
export class App {}
```

`TestComponent` is:
```js
import {Component} from 'angular2/angular2';

@Component({
  selector: 'test',
  template: 'Hello from component: {{ test }}'
})
export class TestComponent {
  public test: string = 'test';
}
```

**Comment by brandonroberts** [comment]
@wkwiatek Did you add ROUTER_PROVIDERS to your bootstrap?

**Comment by wkwiatek** [comment]
@brandonroberts Sure. This code works on modern browsers. Only IE9 has the problem.

**Comment by brandonroberts** [comment]
@wkwiatek can you isolate which one causes the error? Try adding just RouterOutlet instead of ROUTER_DIRECTIVES

**Comment by wkwiatek** [comment]
`RouterOutlet` instead of `ROUTER_DIRECTIVES` gives the same error. 

Commenting out `@RouteConfig()` gives clean console output but nothing really happens.

**Comment by btford** [comment]
@wkwiatek can you put your example into a plunker (jsfiddle/jsbin)? It'd help me take a look at the problem quicker.

Thanks!

**Comment by wkwiatek** [comment]
It's really basic config. I've put in here: http://plnkr.co/edit/pwE8ODxhqsGBRIJYAbh0?p=preview

**Comment by wkwiatek** [comment]
Ok. The error the thread is about has gone but the new one comes (IE9 only): 
```
TypeError: Object doesn't support property or method 'pushState' 
```

**Comment by coutin** [comment]
+1

**Comment by ericmartinezr** [comment]
According to caniuse [pushState is not supported in IE9](http://caniuse.com/#search=pushstate), so it must be polyfilled.

**Comment by andycwk** [comment]
hmm... I'm having the same issues and tried adding a polyfill (history.js) with poor results so far.. 

I've created a new ticket as I've provided much more info!

https://github.com/angular/angular/issues/6506

**Comment by liquidboy** [comment]
+ 1

**Comment by btford** [comment]
I'm going to close this as a duplicate of #6506– let's continue discussion on that issue.
