### ISSUE TITLE
Named route query params in ActivatedRoute don't work

### ISSUE THREAD

**Issue by danPwiz** [angular/angular#57925]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

When inside an named route, `ActivatedRoute.queryParams` doesn't read the query params of the named route.
![Screenshot 2024-09-23 at 17 31 52](https://github.com/user-attachments/assets/1d18a47d-4b50-4c47-b88a-2d248a334a5e)

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/~/github.com/danPwiz/named-route-params?file=src/app/page/side-page-2.component.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.2.5
Node: 18.20.0
Package Manager: npm 10.5.0
OS: darwin arm64

Angular: 18.2.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.5
@angular-devkit/build-angular   18.2.5
@angular-devkit/core            18.2.5
@angular-devkit/schematics      18.2.5
@schematics/angular             18.2.5
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10
```

### Anything else?

When looking in to the issue I was having I noticed that using a nested route in the named route. The ActivatedRoute outlet is the primary outlet.

**Comment by diesieben07** [comment]
What you are setting are _matrix_ parameters, not _query_ parameters. If you check `ActivatedRoute#params` you'll see the values there. `withComponentInputBinding` binds queryParams, params [path and matrix] and data (in that order), that's why the input variant works.

Query parameters don't make sense for a named outlet, because a URL can only have _one_ set of query parameters, after the `?`.

**Comment by atscott** [comment]
Closing as working as expected. As @diesieben07 mentioned, these are matrix params, not query params. You can see in the log that the expected value _is_ being logged in the params observable on `ActivatedRoute`.

**Comment by danPwiz** [comment]
Got it, thank you!
