### ISSUE TITLE
Destructuring support for `@let`

### ISSUE THREAD

**Issue by json-derulo** [angular/angular#57923]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

It would be great if we could use JavaScript object & array desctructuring with the new `@let` syntax.

_Originally posted by @HyperLife1119 in https://github.com/angular/angular/issues/15280#issuecomment-2221898128_

### Proposed solution

The following syntax is supported (currently it throws an error):

```html
@let { key1, key2 } = myObject;
@let [item1, item2] = myArray;
```

### Alternatives considered

The same can be achieved with multiple `@let` blocks but it's more verbose and redundant:

```html
@let key1 = myObject.key1;
@let key2 = myObject.key2;
@let item1 = myArray[0];
@let item2 = myArray[1];
```

**Comment by alxhub** [comment]
#43485 is slightly distinct, as it intentionally covers _expressions_ specifically. `@let` is not an expression but a statement (though probably only compiler nerds like me spend time thinking about the difference...)

In general, we have no plans to work on destructuring for `@let`, for a few reasons:

* It adds a lot of syntax clutter to the template, complicating things like parsing, formatting, etc.
* In signal components, values produced by `@let` may not be plain values, but signals, so the semantics could be different than pure JS `let` declarations.
* We have plans to invest some R&D into Angular's authoring format. Without completing this work, it's hard to know whether such a feature would create issues or unnecessary overhead.

Therefore, we want to let these efforts resolve first before considering any expansion of the capabilities of `@let`. Given we have no plans to implement this feature for now, I'm going to close this - but we will revisit the idea at some point in the future.
