### ISSUE TITLE
Signals: get the value with a function like "isTaskCompleted.value()", instead of "isTaskCompleted()" for more consistency in writing.

### ISSUE THREAD

**Issue by HALLOUINJPH** [angular/angular#57933]
### Description

Frequently, in the template, I forget to add the parentheses. This happens because the way to set the signal is not consistent with how the value is retrieved:
To set, I must write: `isTaskCompleted.set(true);`
But to read, only `isTaskCompleted()` is necessary.

This inconsistency makes it confusing.

### Proposed solution

To maintain consistency in writing, the value should be read in the form like this:

`isTaskCompleted.value()`

### Alternatives considered

It is very important to maintain consistency in writing, especially for a feature that will be widely used in the future of Angular.

**Comment by alxhub** [comment]
The shape of this API was discussed considerably during the RFC and DX studies before the signal APIs were finalized. No API has all of the properties we wanted, but using function calls as signals came the closest.

In particular, we especially value the property that the no-arg function `() => T` is easily wrapped/abstracted. That is, it's possible to write APIs that read signals under the hood:

```typescript
const fullName = () => firstName() + ' ' + lastName();
```

And it's possible to write APIs that accept `() => T` in a way where signals can be passed directly:

```typescript
function valueOrDefault<T>(value: () => T|undefined, default: T): () => T {
  return () => value() ?? default;
}

const nameOrEmpty = valueOrDefault(firstName, '');
```

This isomorphism makes building higher-order abstractions very pleasant, which was a big reason in favor of the "signals as functions" API flavor. No other API style (`.value`, `.value()`, `read(s)`, etc) had such a clean abstraction.

Given that Angular Signals are stable now and the cost of making such an API change at this point would be heavy, we don't think there's a reason to reopen the API design discussion today.
