### ISSUE TITLE
AbstractControl has @internal members that are needed by extending classes

### ISSUE THREAD

**Issue by matthewdenobrega** [angular/angular#5793]
Currently _value and _initObservables are public but marked as @internal, which means classes which extend AbstractControl can access them, but the Typescript compiler complains that they don't exist.

Removing the @internal comments fixes this, but it's a problem that _ variables are then public and not internal. They can't be protected as Dart doesn't support protected variables.

My use case is a Control (extending AbstractControl) which handles immutable data. I imagine there will be other use cases for extending AbstractControl. I'm happy to do a PR but am unsure of the intent behind these - they are marked as internal but called by an extending class (Control)

**Comment by matthewdenobrega** [comment]
#5863 is a possible fix for this.

**Comment by vsavkin** [comment]
The _value field is internal because the users of ControlGroup and ControlArray should not be able to reset the value directly. That is why only the Control class has `updateValue` method.  

Could you just extend Control instead of extending AbstractControl? We can also consider making _value protected.

**Comment by matthewdenobrega** [comment]
I initially thought extending Control was overkill as the way I update the model with immutable data is quite different from the way Control does, but I just tried now and I can add the extra logic in by extending Control and calling the relevant update methods. 

I initially tried to make those fields protected, which is fine in Typescript but the Dart compiler threw. I agree with having _value private, and if in general it's possible to extend control rather than AbstractControl - which looks like the case - then there's no need to change the API.

Thanks
