### ISSUE TITLE
Angular signals update/set method can be easly confused

### ISSUE THREAD

**Issue by roma2341** [angular/angular#57931]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Today I have written these lines in my code:
```
  this.$stepsContainer.pipe(
        takeUntilDestroyed(this.destroyRef)
    ).subscribe(stepsContainer => {
      if(stepsContainer == null){
        this.leadFlowViewStorageService.mySignal.update(null);
        return;
      }
      this.leadFlowViewStorageService.mySignal.update(stepsContainer.nativeElement);
```
My signal looks like:
`mySignal = signal<HTMLElement>(null);`
      
And I got this error:
 `  updater is not a function`
   
   I thought that it was because I called this code from the constructor, I moved it to NgOnInit, but it didn't help. Then I thought that my signal was not writable.
   It turned out that I used update() instead of set(), it's easy to miss. 
   I think that error must be more clear - the update method doesn't have to accept null or undefined values.
   
   

### Please provide the exception or error you saw

```true
updater is not a function
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 18.2.0
```

**Comment by JeanMeche** [comment]
Update shouldn't accept `null`. You likely don't have `    "strictNullChecks": true,` in your `tsconfig`.

**Comment by alxhub** [comment]
@JeanMeche is likely correct here - this is a TypeScript strictness issue.

**Comment by JoostK** [comment]
Specifically, `stepsContainer.nativeElement` will be of type `any` if `stepsContainer` is just `ElementRef`, instead of `ElementRef<HTMLElement>`, so there won't be any type-checking around this type.
