### ISSUE TITLE
Unresolve variable or type $event

### ISSUE THREAD

**Issue by splincode** [angular/angular#57949]
### Which @angular/* package(s) are the source of the bug?

language-service

### Is this a regression?

No

### Description

In your documentation:
https://angular.dev/guide/components/host-elements#the-hostbinding-and-hostlistener-decorators

<img width="748" alt="image" src="https://github.com/user-attachments/assets/3e374a36-78b5-4c34-8748-28a0ddc18166">

After:

<img width="737" alt="image" src="https://github.com/user-attachments/assets/347f1cb2-eec5-4720-8c43-14547d08d5fa">

### Please provide a link to a minimal reproduction of the bug

Any source code

### Please provide the environment you discovered this bug in (run `ng version`)

```
IntelliJ IDEA 2024.3 EAP (Ultimate Edition)
Build #IU-243.15521.24, built on September 19, 2024
Licensed to IntelliJ IDEA EAP user: Maksim Ivanov
Expiration date: October 19, 2024
Runtime version: 21.0.4+8-b598.4 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 14.6.1
Kotlin plugin: K2 mode (Beta)
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 25008M
Cores: 12
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  com.ahmed3elshaer.true-black-theme (1.4.5)
Kotlin: 243.15521.24-IJ
```

**Comment by JoostK** [comment]
This is an IntelliJ bug. Just FYI I can also reproduce in 2024.2.1 so it's not an EAP-only issue.

**Comment by JoostK** [comment]
[WEB-54226](https://youtrack.jetbrains.com/issue/WEB-54226/)
