### ISSUE TITLE
The effect was not called when the input property changed

### ISSUE THREAD

**Issue by fantasy0v0** [angular/angular#57967]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

I am writing a component that needs to listen for changes to the input property. Since I am using signals, I tried using effect, but I found that the effect was not called when the input property changed.

**I found that if I call the signal in the effect, everything works fine.**

```javascript
effect(() => {
  // this.id();
  untracked(() => {
    console.log(this.id());
  });
});
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/sqh7rz?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
The effect was not called when the input property changed.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.2.6
Node: 18.19.1
Package Manager: npm 10.2.4
OS: linux x64

Angular: 18.2.6
... animations, build, cdk, cli, common, compiler, compiler-cli
... core, forms, material, platform-browser

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1802.6
@angular-devkit/core         18.2.6
@angular-devkit/schematics   18.2.6
@schematics/angular          18.2.6
rxjs                         7.8.1
typescript                   5.5.4
zone.js                      0.14.10
```

**Comment by JoostK** [comment]
Your evaluting the signal within `untracked`, so the signal won't be captured as dependency of the effect.
