### ISSUE TITLE
ng build fails with ENAMETOOLONG if there are a lot of uncommitted files

### ISSUE THREAD

**Issue by naris** [angular/angular#57978]
### Which @angular/* package(s) are the source of the bug?

compiler-cli, compiler

### Is this a regression?

Yes

### Description

I have run into a problem working with a JHipster application after migrating to a new version that ng build fails with ENAMETOOLONG. I googled the issue and according to this StackOverflow [[How to fix spawn ENAMETOOLONG error nrwl nx workspace](https://stackoverflow.com/questions/71185967/how-to-fix-spawn-enametoolong-error-nrwl-nx-workspace)](https://stackoverflow.com/questions/71185967/how-to-fix-spawn-enametoolong-error-nrwl-nx-workspace) this issue is because there are "too many" uncommitted  files, which tracks because after migrating the JHipster application there are indeed quite a lot of uncommitted files (856 of them). However, I really need to be able to compile and run the application before committing the files to ensure the migration did not break anything :(

### Please provide a link to a minimal reproduction of the bug

Unfortunately, it is not possible to provide a link to a project with uncommitted files :(

### Please provide the exception or error you saw

```true
[INFO] > ng build --configuration development
[INFO]
[INFO] - Generating browser application bundles (phase: setup)...
[INFO] âœ” Browser application bundle generation complete.
[INFO] node:internal/child_process:421
[INFO]     throw new ErrnoException(err, 'spawn');
[INFO]           ^
[INFO]
[INFO] Error: spawn ENAMETOOLONG
[INFO]     at ChildProcess.spawn (node:internal/child_process:421:11)
[INFO]     at spawn (node:child_process:762:9)
[INFO]     at Object.execFile (node:child_process:351:17)
[INFO]     at module.exports.fileCommand (C:\src\totalfact\node_modules\webpack-notifier\node_modules\node-notifier\lib\utils.js:76:13)
[INFO]     at C:\src\totalfact\node_modules\webpack-notifier\node_modules\node-notifier\notifiers\toaster.js:145:11
[INFO]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
[INFO]   errno: -4064,
[INFO]   code: 'ENAMETOOLONG',
[INFO]   syscall: 'spawn'
[INFO] }
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.2.5
Node: 20.16.0
Package Manager: npm 10.8.1
OS: win32 x64

Angular: 18.2.5
... cli, common, compiler, compiler-cli, core, forms, localize
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.5
@angular-devkit/build-angular   18.2.5
@angular-devkit/core            18.2.5
@angular-devkit/schematics      18.2.5
@angular/animations             18.0.4
@angular/cdk                    18.0.4
@schematics/angular             18.2.5
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10
```

**Comment by clydin** [comment]
The `webpack-notifier` package that is the origin of the error is not part of the Angular build system. This is either included as part of `nx` or as part of a custom Webpack configuration. Both of these cases is not supported by the Angular team.
Please consider opening an issue with `nx` or attempting to remove the `webpack-notifier` usage, if applicable.
