### ISSUE TITLE
`ServerModule` overrides `HttpClient` customizations

### ISSUE THREAD

**Issue by griest024** [angular/angular#57983]
### Which @angular/* package(s) are the source of the bug?

platform-server

### Is this a regression?

Yes

### Description

When using SSR with the module setup generated with `ng new --standalone=false --ssr=true` (or by `ng add @angular/ssr` to an existing module application), any `HttpClient` customizations are overridden by `ServerModule`. This is because `ServerModule` imports `HttpClientModule`. https://github.com/angular/angular/blob/1549afe10eddc92845cd1fde862aaa010c2395af/packages/platform-server/src/server.ts#L83-L88

The repro uses `angular-in-memory-web-api` to demo the customization behavior.

The following things fix this:
- Moving the `ServerModule` import above the `AppModule` in `AppServerModule` (https://github.com/griest024/ng18-ssr-module/tree/module-order)
- Replacing the `ServerModule` import with `provideServerRendering()` (https://github.com/griest024/ng18-ssr-module/tree/server-provider)

### Please provide a link to a minimal reproduction of the bug

https://github.com/griest024/ng18-ssr-module

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.2.6
Node: 18.20.4
Package Manager: npm 10.7.0
OS: linux x64

Angular: 18.2.6
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.6
@angular-devkit/build-angular   18.2.6
@angular-devkit/core            18.2.6
@angular-devkit/schematics      18.2.6
@schematics/angular             18.2.6
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10
```

### Anything else?

IMO the *correct* fix is the replace `ServerModule` with `provideServerRendering()` in `@angular/ssr` scaffolding. `HttpClientModule` should probably not be imported by `ServerModule` either.

Related to https://github.com/angular/angular/issues/50454

**Comment by alan-agius4** [comment]
I think `HttpClientModule` in this can shouldn't be listed in the `ServerModule`.
