### ISSUE TITLE
add flag to inject-migration generator to only refactor @Inject ones

### ISSUE THREAD

**Issue by robertIsaac** [angular/angular#58000]
### Description

currently in Angular there are two types of injector
1. `@Injectable` classes
2. `InjectionToken`

from my understanding the first type if fully compatible with the new standard decorators and the only problem is the second type since it needs `@Inject` decorator to work which will not be part of the standard and won't be supported by TS in the future

right now there is a generator `inject-migration`, this generator will migrate both types

### Proposed solution

to add flag to the mentioned generator in the description to only migrate the `InjectionToken` type and to leave the `@Injectable` classes as is

the reason? I prefer to have my dependency classes in the constructor instead of being a class property, it helps organize the code

### Alternatives considered

to have a guidance and later a lint rule (I understand it's outside of the Angular team) to group the properties together
so instead of having
```
export default class MyComponent {
  protected readonly output2 = output();
  protected readonly router = inject(Router);
  protected readonly input1 = input(undefined, { transform: numberAttribute });
  protected readonly activatedRoute = inject(ActivatedRoute);
  protected readonly formBuilder = inject(FormBuilder);
  protected readonly value = signal(1);
  protected readonly input2 = input(10);
  protected readonly output1 = output();
}
```

to have
```
export default class MyComponent {
  protected readonly router = inject(Router);
  protected readonly activatedRoute = inject(ActivatedRoute);
  protected readonly formBuilder = inject(FormBuilder);

  protected readonly input1 = input(undefined, { transform: numberAttribute });
  protected readonly input2 = input(10);

  protected readonly output2 = output();
  protected readonly output1 = output();
  
  protected readonly value = signal(1);
}
```

it needs to be agreed on that for example injectors to be group at the top, then the inputs, then the outputs ... so that we could have a lint rule to enforce it, otherwise people will keep arguing about it

**Comment by crisbeto** [comment]
We talked through this and decided not to do it, because it would add a lot of complexity to the migration without much benefit.
