### ISSUE TITLE
Blank page on window reload after ng SW version change

### ISSUE THREAD

**Issue by varsha18k** [angular/angular#58014]
### Which @angular/* package(s) are the source of the bug?

service-worker

### Is this a regression?

Yes

### Description

I have used below lines of code to reload the app when there is a version change in the change. However , after a version change the app shows a blank page and doesnt load

constructor(private swUpdate: SwUpdate)
{
if(this.swUpdate.isEnabled){
this.swUpdate.available.subscribe(()=>{
window.location.reload();

});
}

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Node : 14.21.3
npm 6.14.18
@angular/pwa: '0.1002.1'
@angular/core : 12.2.17
```

**Comment by JeanMeche** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).
