### ISSUE TITLE
Missing LICENSE file in shipped packages from npm

### ISSUE THREAD

**Issue by Frozen-byte** [angular/angular#58029]
### Which @angular/* package(s) are the source of the bug?

bazel

### Is this a regression?

Yes

### Description

The LICENSE files are missing in the packages and are not shipped.

This prevents SBOM generation tools from collecting evidences for Copyright or Original License Texts.

@JeanMeche [wrote](https://github.com/angular/angular/issues/44428#issuecomment-2027732012) that the file are shipped by now, but I am unable to see them from the given example: https://www.npmjs.com/package/@angular/core?activeTab=code
![image](https://github.com/user-attachments/assets/c5bda33b-eef4-470a-8e41-e3c47b2f956b)

### Related issues
Same Issue like https://github.com/angular/angular/issues/44428 or https://github.com/angular/angular/issues/53052

**Comment by JeanMeche** [comment]
You can expect the change to land in the next 18 patch version.
