### ISSUE TITLE
Issue with links of an Angular SSG application

### ISSUE THREAD

**Issue by balteo** [angular/angular#58020]
### Which @angular/* package(s) are the source of the bug?

router, ssr/ssg, Don't known / other

### Is this a regression?

No

### Description

I have generated an SSG angular application with the CLI. When I serve the generated HTML files with no backend/API running, and I navigate the links the content of the page (which was generated from a fetch request) is not displayed.

I noticed that when I navigate one of the links, only a **fetch** request (GET) is issued by my app, which results in the issue since no backend is running, and I have to refresh the page in order for the **document** request (GET) to be issued and the page to be actually displayed correctly with the data. 

I suspect there is something wrong with the links then.

### Please provide a link to a minimal reproduction of the bug

https://github.com/balteo/static-site-generation-demo-ng

### Please provide the exception or error you saw

```true
No content is displayed when navigating the links.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.2.5
Node: 22.0.0
Package Manager: npm 8.19.3
OS: darwin x64

Angular: 18.2.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.5
@angular-devkit/build-angular   18.2.5
@angular-devkit/core            18.2.5
@angular-devkit/schematics      18.2.5
@schematics/angular             18.2.5
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10
```

### Anything else?

In order to reproduce the bug, checkout the repo and run:

`npm i && npm run ssg:build && npm run ssg:serve`

This will generate the static HTML files and serve them with no backend running.

FYI, I have open a SO post here: https://stackoverflow.com/q/79023891/536299

**Comment by jnizet** [comment]
Hi @balteo 

That's expected behavior. SSR/SSG allows downloading server-generated HTML for the *initial* page load. Once the page is loaded, it's hydrated and the application then behaves like a traditional SPA, where everything is done in JavaScript on the client.

**Comment by JeanMeche** [comment]
Per above.

**Comment by balteo** [comment]
Hi @jnizet 
Thanks for your reply.
