### ISSUE TITLE
document.location.hostname return different value between v17  and v18

### ISSUE THREAD

**Issue by mathieu-morchipont** [angular/angular#58025]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

In the same infra and same domaine, I deploy angular 17 version with ssr
`document: Document = inject(DOCUMENT),
console.log(document.location.hostname); //return mydomain.com
`

in v18 : 

`document: Document = inject(DOCUMENT),
console.log(document.location.hostname); //return 10.0....  my ip
`

How to get domain hostname in server in v18 ? 

Thanks a lot

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.
