### ISSUE TITLE
docs: The title of the section on the tutorial page does not match the content

### ISSUE THREAD

**Issue by AnkitSharma-007** [angular/angular#58036]
### Describe the problem that you experienced

When navigating to this page: https://angular.dev/tutorials/first-app/11-details-page, I noticed that the title of the first section reads "Create a new service for your app." However, the content of this section doesn't discuss creating a service. Instead, it talks about fetching the dynamic "id" value from the route.

It seems like the title may need updating to reflect the actual content.

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/first-app/11-details-page

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/user-attachments/assets/f3723675-994f-46e4-8b4f-26952c843997)

**Comment by AndrewKushnir** [comment]
Closing this ticket, since the corresponding fix was merged (https://github.com/angular/angular/pull/58060).
