### ISSUE TITLE
use zone.js@0.5.x in package.json

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#5804]
It would be a good idea to use `"zone.js": 0.5.x` (same for other deps) to make sure you always get the latest patches. This would also avoid things like:
```shell
npm WARN EPEERINVALID angular2@2.0.0-alpha.52 requires a peer of zone.js@0.5.8 but none was installed.
```
When I have the dependency as `"zone.js": 0.5.x`.

**Comment by pkozlowski-opensource** [comment]
Yes, we might do this in the future. But for now we've got some dependencies (mostly zone and RxJS) that are undergoing very rapid changes and we want to be sure that users got a combination of dependencies that works. We can't lean on SemVer here as those libraries are in `0.x` version so there are no strong guarantees about breaking changes.

In short: as soon as things are more stable we will be relaxing dependency constraints. Unfortunately this can't happen now.
