### ISSUE TITLE
ErrorHandler stop working on Angular 18

### ISSUE THREAD

**Issue by pyozenou** [angular/angular#58043]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

Global ErrorHandler seem stop working on Angular 18.

import { Component, ErrorHandler } from '@angular/core';
import { bootstrapApplication } from '@angular/platform-browser';
import 'zone.js';

class MyErrorHandler implements ErrorHandler {
  handleError(e: any) {
    alert(e.message);
  }
}

@Component({
  selector: 'app-root',
  standalone: true,
  providers: [{ provide: ErrorHandler, useClass: MyErrorHandler }],
  template: `
    <button (click)="onClick()">click here</button>
  `,
})
export class App {
  onClick() {
    throw new Error('ops');
  }
}

bootstrapApplication(App);
click on button don't show the alert()

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-bnp2ce

### Please provide the exception or error you saw

```true
"@angular/animations": "^18.0.0",
    "@angular/common": "^18.0.0",
    "@angular/compiler": "^18.0.0",
    "@angular/core": "^18.0.0",
    "@angular/forms": "^18.0.0",
    "@angular/platform-browser": "^18.0.0",
    "@angular/router": "^18.0.0",
    "rxjs": "^7.8.1",
    "tslib": "^2.5.0",
    "zone.js": "~0.14.0"
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.1.1
Node: 18.20.3
Package Manager: npm 10.2.3
OS: linux x64

Angular: 18.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1801.1
@angular-devkit/build-angular   18.1.1
@angular-devkit/core            18.1.1
@angular-devkit/schematics      18.1.1
@schematics/angular             18.1.1
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.8
```

### Anything else?

No

**Comment by JoostK** [comment]
`ErrorHandler` should be overridden from the app level, providing it from a component doesn't do anything.

```ts
bootstrapApplication(App, {
  providers: [
    { provide: ErrorHandler, useClass: MyErrorHandler }
  ]
});
```

This hasn't changed compared to prior versions of Angular.
