### ISSUE TITLE
Rxjs adapter signal that can be late-subscribed

### ISSUE THREAD

**Issue by snortblt** [angular/angular#58055]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

When using Signals in conjunction with services or components that provide Observables, often `toSignal` isn't a viable option because the Obvservable isn't available at Signal creation time (usually signals must be created during their owner component's construction). To deal with this, instead we have to create a signal, then a subscription to the Observable that updates the signal, then teardown that subscription on component destruction. That's some plumbing that can be hidden and reused instead.

### Proposed solution

Create a new Signal type that has an `observe` function on it that accepts an Observable and that automatically subscribes and tears down the subscription when the signal is destroyed.

### Alternatives considered

Manual Observable subscribe,  signal update, unsubscribe.

**Comment by JeanMeche** [comment]
Hi,
This issue has been discussed in #55337, let's continue over there.

**Comment by snortblt** [comment]
@JeanMeche I'm not sure that's the same issue. The suggestion there is to use toLazySignal but that still appears to similarly require an observable to be passed in at construction time. The issue here is that the observable itself may not be available at construction time, not that it should be lazy or eager.
