### ISSUE TITLE
Test started to fail in angular 18  ( tick() is calling clearTimeout )

### ISSUE THREAD

**Issue by chabb** [angular/angular#58058]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

I have a test that spy on clearTimeout and use the fakeAsync
When I upgraded to angular 18, the test started to fail.
I've notice that when I call tick() in the fakeAsync zone, clearTimeout() is called. Then tests then fails because we have two calls to clearTimeout, one by the application, one by angular. This was not the case before ?
Is there something I can do to prevent this behaviours

**Comment by JoostK** [comment]
Please include a minimum reproduction, without it this isn't actionable.
