### ISSUE TITLE
Macbook M3 Sequoia: On Angular 18 new APP's: An unhandled exception occurred: Cannot find module 'postcss-media-query-parser'

### ISSUE THREAD

**Issue by aleftos** [angular/angular#58068]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Macbook M3 - Sequoia, Angular 18
node -v
v22.9.0
ng --version
18.2.7

ng serve
An unhandled exception occurred: Cannot find module 'postcss-media-query-parser'

[error] Error: Cannot find module 'postcss-media-query-parser'
Require stack:

node_modules/critters/dist/critters.js
node_modules/@angular-devkit/build-angular/node_modules/@angular/build/src/utils/index-file/inline-critical-css.js
node_modules/@angular-devkit/build-angular/node_modules/@angular/build/src/utils/index-file/index-html-generator.js
node_modules/@angular-devkit/build-angular/node_modules/@angular/build/src/tools/esbuild/index-html-generator.js
node_modules/@angular-devkit/build-angular/node_modules/@angular/build/src/builders/application/execute-post-bundle.js
node_modules/@angular-devkit/build-angular/node_modules/@angular/build/src/builders/application/execute-build.js
node_modules/@angular-devkit/build-angular/node_modules/@angular/build/src/builders/application/index.js
node_modules/@angular-devkit/build-angular/node_modules/@angular/build/src/private.js
node_modules/@angular-devkit/build-angular/src/builders/dev-server/builder.js
node_modules/@angular-devkit/build-angular/src/builders/dev-server/index.js
node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
at Module._resolveFilename (node:internal/modules/cjs/loader:1248:15)
at Module._load (node:internal/modules/cjs/loader:1074:27)
at TracingChannel.traceSync (node:diagnostics_channel:315:14)
at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
at Module.require (node:internal/modules/cjs/loader:1339:12)
at require (node:internal/modules/helpers:135:16)
at Object. (node_modules/critters/dist/critters.js:10:35)
at Module._compile (node:internal/modules/cjs/loader:1546:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
at Module.load (node:internal/modules/cjs/loader:1317:32)

**Comment by JeanMeche** [comment]
Hi, 
This is dependency issue. `critters` (a dependency of `@angular-devkit/build-angular`)  should pull `postcss-media-query-parser`. 

Make sure that your dependencies are correctly installed.

**Comment by JeanMeche** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).
