### ISSUE TITLE
Angular 17v - Not able to open shared file path on Network in a new browser tab as it results in opening "about:blank#blocked"

### ISSUE THREAD

**Issue by manjitKSokhi** [angular/angular#58066]
### Which @angular/* package(s) are the source of the bug?

core, Don't known / other

### Is this a regression?

Yes

### Description

I'm working on requirement using Angular 17 where I'm trying to open shared path on network.

I am using anchor tag to open folder location in a separate browser tab on click of link. Upon clicking it opens new browser tab however it redirects to about:blank#blocked URL.

If I manually try to access file path I'm able to do so.

Shared file path: file://xyz/

Not an ideal approach however I tried using jquery with Angular to open shared file path on Network but unable to do as it redirects to about:blank#blocked page.

### Please provide the exception or error you saw

Redirects to about:blank#blocked instead of opening shared folder location on network

**Comment by JeanMeche** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).
