### ISSUE TITLE
Plural support for typescript in Angular 18

### ISSUE THREAD

**Issue by gora-v2** [angular/angular#58074]
### Which @angular/* package(s) are the source of the bug?

localize

### Is this a regression?

Yes

### Description

Hi Team,
Currently am upgrading my app to angular 18 and also am migrating i18n from ngx-translate to angular/localize. Unfortunately i couldn't achieve plural in typescript i can do the same in html. Below is my translation text can someone suggest whether it is support if yes guide me how to do that properly,

const i18NValue = $localize`:@@MessageID:Found {presentationCount, plural, =1 {presentation} other {presentations}}`;
Expected text: Found presentation or Found presentations.

When i checked the trans-unit 

<trans-unit id="MessageID" datatype="html">
        <source>Found {presentationCount, plural, =1 {presentation} other {presentations}}</source>
</trans-unit>

**Comment by JeanMeche** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).
