### ISSUE TITLE
typings from angular2 conflict with project typings

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#5807]
As I am already including:
```js
"node/node.d.ts": {
	"commit": "e850b6ac0d59fee86dd7cb6a1be2caf6400bde14"
}
```
In my `tsd.json` file and angular also includes those, I get lots of `error TS2300: Duplicate identifier ...` errors.

Is there really no solution for this? If there is a solution, can someone point me to it because I cannot find something that would make it work, besides me not including these typings in my own `tsd.json` file.

**Comment by rolandjitsu** [comment]
Also, I need to include the jasmine typings that I need for some e2e tests that at this point do not import angular2 at all, so because I cannot include my own typings dependency in `tsd.json` (because of the duplicate identifier errors) I get errors like `error TS2304: Cannot find name 'it'`. So that is another annoying thing to see in the compilation output.

**Comment by manland** [comment]
:+1: 

Same here :cry: 

Also, i use express and it import node.ts like this : 

```js
/// <reference path="../node/node.d.ts" />
/// <reference path="../serve-static/serve-static.d.ts" />

declare module Express {

    // These open interfaces may be extended in an application-specific manner via declaration merging.
    // See for example method-override.d.ts (https://github.com/borisyankov/DefinitelyTyped/blob/master/method-override/method-override.d.ts)
    export interface Request { }
    export interface Response { }
    export interface Application { }
}
```

Any idea on a solution please ?

**Comment by dsebastien** [comment]
See #5459 and #5395.
This is indeed rather annoying atm :(

**Comment by xstof** [comment]
Same issue for electron projects, which each also reference node.  When using electron with angular 2, because of angular bringing it's own node.d.ts typings, there's lots of duplicate identifier errors.  Excluding the node.d.ts typings from angular 2 causes an error in "angular2/manual_typings/globals-es6.d.ts(14,1)": "node_modules/angular2/typings/node/node.d.ts' not found".  I assume this is because there's a reference path in the globals-es6.d.ts file like this: `<reference path="../typings/node/node.d.ts" />`.  So far this means I don't seem to be able to properly compile electron with angular 2.

**Comment by rolandjitsu** [comment]
@xstof it should still compile, but you will of course see all those nasty complaints in the compiler.

**Comment by xstof** [comment]
Thanks @rolandjitsu - much appreciate the answer; hope the issue will be resolved.  Will stick with the compile errors now.  When I exclude the node typings from angular it's only one error, coming from globals-es6.d.ts.  Alternatively, I'm thinking of doing two gulp-driven compile steps (one for angular related code, using angular node typings; andone for my own core functionality with my npm node import).

**Comment by rolandjitsu** [comment]
@xstof I think we just have to be patient until all this typescript business get's more stable. As far as I know there is something in the pipeline, plus there is another development for this typings business called [typings](https://github.com/typings/typings), an alternative to TSD which, from what I understand, should fix all these issues.

But I haven't had the chance to give that tool a try, don't really know where to get started with it :confused:

**Comment by Demurgos** [comment]
Hi,
I tried [typings](https://github.com/typings/typings) this week and it nicely solves the duplicate definition errors. From what I could see, it downloads definitions as *external* modules and then compile it at the root of your project as module *declarations*. During this process, typings are defined only once and do not clutter the global namespace. Unless you explicitly require a typing, it won't bother you which is really neat.

**Comment by rolandjitsu** [comment]
@Demurgos would you mind sharing that setup?

**Comment by Demurgos** [comment]
@rolandjitsu Sure, I'll just clean up my directory and I will upload it.

**Comment by IgorMinar** [comment]
sorry folks, this will have to wait until beta.1 - we will fix it for sure though, the fact that we are reexporting typings and forcing our versions onto angular apps is not right

**Comment by dsebastien** [comment]
86%, beta 0 is getting closer! That'll be a nice christmas gift for geeks =)

**Comment by tapas4java** [comment]
90% now....Kudos to team!

**Comment by episodeyang** [comment]
Second this one! Kudos to the team!

**Comment by episodeyang** [comment]
Here in this commit of my project, introduction of the angular2 dependency in this commit causes duplicate identifier error:

https://github.com/escherpad/luna/commit/4e3c7937fe58aa7c1999211755e07076e282aa42

**Comment by IgorMinar** [comment]
We'll fix this by the end of the year.

**Comment by stasberkov** [comment]
Any change to get this fixed till the end of this year?

**Comment by masaeedu** [comment]
@Demurgos Any chance of getting your setup on Github or a gist? Please and thanks.

**Comment by Demurgos** [comment]
Sorry for the delay, but [here is the repo](https://github.com/Demurgos/quick-chat) where I experiment with Angular 2.
I still had to create a small `.d.ts` manually for the browser to avoid conflicts with Angular2.
For this repo I converted the `socket.io` typings from `DefinitelyTyped` to the `typings`' external module format and it works really well with `tsc` and `WebStorm`.
Switching to external module definitions and letting `typings` or an other tool handle the ambient definitions looks like a good idea to me.
`typings` is not the only project working on better TS definitions, `typescript` itself seems to be working on a better system so I hope that all these conflicts will be solved soon.

**Comment by jomeier** [comment]
For me commenting out Line 14 (/// <reference path="../typings/node/node.d.ts" />) in:

/node_modules/angular2/manual_typings/globals-es6.d.ts

removed my TS2300 errors (conflicted with node).

**Comment by IgorMinar** [comment]
We are working on the fix. It's not trivial. If no more complications
appear, the fix will be part of beta.1 or 2 this week or the next.

**Comment by Finkes** [comment]
is there anything new to this?

**Comment by NikGovorov** [comment]
@Finkes, still the same for me in beta1.

**Comment by alexeagle** [comment]
I am working on it right now, https://github.com/angular/angular/pull/6267
Needs a change in zone.js to expose the typings, then should be ready.

**Comment by Slaals** [comment]
Any update about this issue? 

I still have a problem with `duplicate identifier` when I import `angular2/core`...

Also, I'm not able to find any quick fix with `typings`. Would anyone mind tell me how `typings` fixes the problem?
```
typings init --upgrade
typings install
```

Will result in more `duplicate identifier` when compile. I compile with `grunt ts`

**Comment by alexeagle** [comment]
Typings cannot fix the problem, it contributes additional types, it can't
remove any.
The fix is coming, it did not make beta.3 yesterday partly because we need
an rxjs release, but should be in beta.4.
