### ISSUE TITLE
Angular CSP, CSP_NONCE, ngCspNonce no longer works in version 18.2.7 after updating from 18.0.2

### ISSUE THREAD

**Issue by damienbod** [angular/angular#58088]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

When I update Angular from 18.0.2 to Angular 18.2.7, the CSP nonce no longer works.

No changes are made, just a plain Angular update. The server CSP is the same, but the JS packages created by Angular are now blocked.

### Please provide a link to a minimal reproduction of the bug

working: 
https://github.com/damienbod/bff-aspnetcore-angular/tree/main/ui

broken:
https://github.com/damienbod/bff-aspnetcore-angular/tree/dev-broken-csp/ui

### Please provide the exception or error you saw

The Angular scripts are blocked in the browser and cannot be loaded

### Please provide the environment you discovered this bug in (run `ng version`)

Last working version:

Angular CLI: 18.0.3
Node: 20.11.1
Package Manager: npm 10.5.0
OS: win32 x64

Angular: 18.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.3
@angular-devkit/build-angular   18.0.3
@angular-devkit/core            18.0.3
@angular-devkit/schematics      18.0.3
@angular/cli                    18.0.3
@schematics/angular             18.0.3
rxjs                            7.8.1
typescript                      5.4.4
zone.js                         0.14.4

### broken version:

Angular CLI: 18.2.7
Node: 20.11.1
Package Manager: npm 10.5.0
OS: win32 x64

Angular: 18.2.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.7
@angular-devkit/build-angular   18.2.7
@angular-devkit/core            18.2.7
@angular-devkit/schematics      18.2.7
@schematics/angular             18.2.7
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.4

### Anything else?

Update to the latest Angular 18.2.x and it breaks
_No response_

**Comment by JoostK** [comment]
Could this be because of angular/angular-cli#28114, which results in a duplicate `nonce` attribute because of the crude replacement logic in

https://github.com/damienbod/bff-aspnetcore-angular/blob/85051f87756213ea1c5bbc57a5c8d5eb8300860e/server/Pages/_Host.cshtml#L29-L30

**Comment by JeanMeche** [comment]
@JoostK The project relies on the webpack-based builder, the change is for the application builder. I don't think we changed much around this.

**Comment by damienbod** [comment]
@JoostK  @JeanMeche 

I found what changed between the versions. In development mode, the nonce is added to the scripts, using the release build, it is not added and I fix this with the crude replacement logic.

**Comment by alan-agius4** [comment]
Indeed as @JoostK pointed out this is caused by https://github.com/angular/angular-cli/pull/28114 which also effects the webpack based builders.
