### ISSUE TITLE
Proposal: Implement Live Component Preview

### ISSUE THREAD

**Issue by pikoscielniak** [angular/angular#58097]
### Description

It would be helpful to have a live preview feature for components, similar to Android Compose. This would allow developers to see style changes immediately without needing to use the component in a larger application.

### Proposed solution

For example, we could create a generic function like previewComponent<ComponentType>. By passing dummy data for inputs, we could quickly see the component's rendering in a separate browser window. Any changes to the component's HTML or styles would be instantly reflected.

### Alternatives considered

Do you think this feature would be valuable, and is it worth the development effort?

**Comment by JeanMeche** [comment]
There are already tools like [storybook](https://storybook.js.org/) that provide this kind of feature.
