### ISSUE TITLE
Project failed to build after circular module issue was resolved.

### ISSUE THREAD

**Issue by dailytabs** [angular/angular#58090]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

??

### Description

Was moving a component to another module and got things mixed up. Built and it failed with a primary message about a component Input not being found, but was actually the component itself not being found due to the module issue. Fixed the issue. Could not rebuild. Continued to attempt "fixes" while getting NG0301's, eventually deleted the .angular folder out of frustration, and the project immediately built.

### Please provide the exception or error you saw

NG0301

### Please provide the environment you discovered this bug in (run `ng version`)

Angular CLI: 18.2.6
Node: 20.17.0
Package Manager: npm 10.8.3
OS: linux x64

Angular: 18.2.6
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, localize, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.6
@angular-devkit/build-angular   18.2.6
@angular-devkit/core            18.2.6
@angular-devkit/schematics      18.2.6
@schematics/angular             18.2.6
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.10

### Anything else?

Not sure what I can provide, since the cache (which became corrupted?) is gone. Feel free to make a mental note and close this.

**Comment by JeanMeche** [comment]
Unfortunately without a repro this won't be actionable to us. Thank you for the feedback though, we'll investigate it if we get further reports.
