### ISSUE TITLE
Updating injector tree when switching ViewContainer

### ISSUE THREAD

**Issue by Andy1605** [angular/angular#58105]
Hello there,

how can the injector tree be updated, after moving a component into another view container.
The injector chain seems to be created at component compile time and is static until the end of time.
My issue is, that i am compiling components in advance and inserting it into another view container later.
Our base layout can also be switched at run-time, which offers completely different service implementations which are not used by already existing components.
Also components can switch view containers by D&D in some views. But the wrong services are fetched afterwards, since the injector chain does not care much about that fact.

Here is an example:
https://stackblitz.com/edit/9nxfml?file=src%2Fmain.ts
A component requests a certain service, which is provided by the view container component.
The service id will be displayed by the inserted component.
By clicking the button, the view gets switched from containerA to containerB. But the injector chain remains the old hierarchy, which results in requesting the wrong service.

Is there a possibility to re-build the injector chain from a given root view.
Smth like:
viewContainer.insert( view );
view.updateInjector( viewContainer.injector );
Or something like that.

**Comment by alxhub** [comment]
Creating a view causes components/directives to be created and their dependencies injected. Changing the injector after that wouldn't really work, since everything was already created with the old injector. To actually make use of the new injector, the comopnents/directives/services would have to be destroyed and recreated with different dependencies. You can do this easily just by destroying and recreating the view.

**Comment by Andy1605** [comment]
This might be easy for very straight forward cases. In our case, we have a highly modular application with factories, which create and initialize  components and do not even know where they will be rendered at all.
Being able to switch views between containers is therefore very dirty, since it might violate the integrity of your injector hierarchy. This is not what i was expecting from a closed framework offering those possibilities. :(
Alright, we will build our own injector system then, which is DOM based.

Thanks for the reply.
