### ISSUE TITLE
Differences in change detection between components using @for vs *ngFor

### ISSUE THREAD

**Issue by neena38** [angular/angular#58117]
I am facing the same issue already pointed by https://github.com/angular/angular/issues/55486.

As a part of migrating the project from Angular 15 to 17, I have replaced *ngFor with @for, and it is no longer working as before.

Ideal case, one edit values in parent component which on saving should be reflected in the child component.

Code before:

```
  <div table-row *ngFor="let action of actions; let i = index">
          <child-component
            [actionId]="action.actionId"
            (editEvent)="onEditEvent(action)"
          ></child-component>
   </div>
```

After Migration to 17:

```
     @for (action of actions; let i = $index; track action.actionId) {
        <div table-row>
          <child-component
            [actionId]="action.actionId"
            (editEvent)="onEditEvent(action)"
          ></child-component>
        </div>
        }
 
```
On editing parent component, values are no longer reflected in child component after using @for. Any idea why?

I did try tracking the entire object as below which works, but I have come to understand that it is not a good practice to do so.

```
     @for (action of actions; let i = $index; track action) {
        <div table-row>
          <child-component
            [actionId]="action.actionId"
            (editEvent)="onEditEvent(action)"
          ></child-component>
        </div>
        }
```

Note: 
ChangeDetectionStrategy is OnPush, howevere we are calling changeDetectorRef.detectChanges() in onEditEvent(action).
The action list is dynamic and could be added/modified in parent.

**Comment by JeanMeche** [comment]
Could you provide a reproduction of the issue, so we can have a look at this ? 
Without it, this isn't actionnable to us.

**Comment by JoostK** [comment]
> I did try tracking the entire object as below which works, but I have come to understand that it is not a good practice to do so.

This is actually the key difference here; not `@for` vs `*ngFor`; the latter defaults to identity tracking and your original code didn't specify a `trackBy` function, so the `track action.actionId` that is being used with `@for` is not equivalent.

**Comment by neena38** [comment]
Am extremely sorry. Turns out track is working just fine. It happened to be an issue with how child component is updating values on receiving from the parent and subscription.

@JoostK, you were right, I am facing the same problem when I use `*ngFor` with `trackBy`.

Thanks for the support. Closing the issue.
