### ISSUE TITLE
Feature request: Case guard: Extended when-conditions on @switch syntax

### ISSUE THREAD

**Issue by kklocker** [angular/angular#58121]
### Description

The new `@switch` syntax is a very welcome one for me. One of the things I noticed when migrating from `[ngSwitch]` was that I wanted to have a way of saying that I only want to switch on a thing `if` another condition was satisfied

### Proposed solution

Inspired by [case guards in c#](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/selection-statements#case-guards)

Main suggestion:

Using the (seems to be standard?) semicolon separated syntax in similar expressions (`@for (...; track ..) `, I would suggest something like this:
```
@switch (condition) {
  @case (caseA; when a == b) {
    Case A, and a is equal to b
  }
  @case (caseA) {
    Default for case A.
  }
.... // further cases
}
```

i.e adding support for a `when` selector in the `@switch` syntax

### Alternatives considered

C# also supports (from the same link as above) direct comparisons on variables themselves, as sort of implicit inline variables. 
```csharp
switch ((a, b))
{
    case (> 0, > 0) when a == b:
    // ....
}

```

Could be nice to have in angular as well, but probably would require some more thinking

**Comment by Segdo** [comment]
Is there a reason for not simply using an if statement inside the case block?

So instead of doing this
```
@switch (condition) {
  @case (caseA; when a == b) {
    Case A, and a is equal to b
  }
  @case (caseA) {
    Default for case A.
  }
.... // further cases
}
```

You would just do this:
```
@switch (condition) {
  @case (caseA) {
    @if (a == b) {
      Case A, and a is equal to b
    } @else {
      Default for case A.
    }
  }
.... // further cases
}
```

Also, if I remember correctly, you could do something like `@case (a == b ? caseA : somethingThatNeverMatches)`, but maybe this is no longer the case.

**Comment by kklocker** [comment]
@Segdo That is of course an option :) That does however increase nesting, which generally tends to reduce readability of the code*


*deduced from several linters suggesting to reduce nesting, not a fact I have any reliable sources on.

**Comment by alxhub** [comment]
Hi @kklocker,

We discussed this issue and decided not to implement as a feature. Generally we want to keep our control flow syntax as close to TypeScript as possible, so there's a high bar for introducing new functionality that's not in the base language.

In this case, we'd suggest using `@if` instead:
```html
@let cond = ...;
@if (cond === caseA && a === b) {
 Case A, and a is equal to b
} @else if (cond === caseA) {
  Default for case A.
}
```

**Comment by kklocker** [comment]
Understandable, thanks anyways for taking the time @alxhub 👍
