### ISSUE TITLE
HEAD TO ANGULAR.DEV button does lead to correct page for @defer

### ISSUE THREAD

**Issue by taylorwaddell** [angular/angular#58140]
### Describe the problem that you experienced

The old documentation page for `@defer`, [angular.io/api/core/defer](https://angular.io/api/core/defer), has the standard "HEAD TO ANGULAR.DEV" button in the header of the pagee. This button brings the user to [angular.dev/api/core/defer](https://angular.dev/api/core/defer) which is not a valid page. The new angular.dev page for `@defer` is [angular.dev/api/core/@defer](https://angular.dev/api/core/@defer).

### Enter the URL of the topic with the problem

https://angular.io/api/core/defer

### Describe what you were looking for in the documentation

I was looking for the updated docs page for `@defer`.

### Describe the actions that led you to experience the problem

Clicking the "HEAD TO ANGULAR.DEV" button in the header on the [angular.dev/api/core/defer](https://angular.dev/api/core/defer) page.

### Describe what you want to experience that would fix the problem

I want this button to bring me to [angular.dev/api/core/@defer](https://angular.dev/api/core/@defer).

**Comment by JeanMeche** [comment]
It'll be fixed by #58141
