### ISSUE TITLE
No need to implement OnInit etc... for lifecycle events

### ISSUE THREAD

**Issue by juristr** [angular/angular#5814]
If I'm not totally wrong, there is no need to implement `OnInit`, `OnDestroy` etc... in order to hook into the component's lifecycle events, right?

That said, this docs would need to be updated:
https://angular.io/docs/ts/latest/api/core/OnInit-interface.html

Just wanted to get a confirmation on this. I'm happy to provide a PR if that's desired :smile: .

**Comment by pkozlowski-opensource** [comment]
You don't have to, strictly speaking, as TypeScript doesn't retain types on runtime. So effect of implementing an interface is null and void during runtime. 

BUT implementing an interface gives you all the types / typos checking, so we still want to recommend it for TS users.

**Comment by juristr** [comment]
Oh, I see, good I asked before submitting the PR :+1: 

Thx.

**Comment by NathanWalker** [comment]
This is very good to know, thanks for asking @juristr 

@pkozlowski-opensource I will say, it is confusing to have to import and implement an interface called `OnInit` to use a function called `ngOnInit` (https://angular.io/docs/ts/latest/api/core/OnInit-interface.html)

A lil' strange and will most likely cause confusion to others.

**Comment by bentaly** [comment]
Agree @NathanWalker but having the name of a function and the interface with the same name would be more confusing!

**Comment by gauravparmar** [comment]
In latest version of Angular, I am using "ngOnInit()" function without importing "OnInit" from @angular/core and still it is going inside the ngOnInit() function body. Why? Is "OnInit" imported by default?
