### ISSUE TITLE
Unable to resolve dependency tree during NPM install

### ISSUE THREAD

**Issue by aguskov1987** [angular/angular#58151]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

THIS ERROR HAPPENS WHEN INSTALLING DEPS FOR THE ACTUAL ANGULAR FRAMEWORK, NOT ANGULAR APPLICATION
When installing the npm dependencies for the latest main branch (19.0.0-next-8) I encounter the following error:

npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: angular-srcs@19.0.0-next.8
npm error Found: @angular/core@19.0.0-next.5
npm error node_modules/@angular/core
npm error   dev @angular/core@"^19.0.0-next" from the root project
npm error   peer @angular/core@"^19.0.0-0 || ^19.1.0-0 || ^19.2.0-0 || ^19.3.0-0 || ^20.0.0-0" from @angular/material@19.0.0-next.4
npm error   node_modules/@angular/material
npm error     @angular/material@"19.0.0-next.4" from the root project
npm error   2 more (@angular/animations, @angular/cdk)
npm error
npm error Could not resolve dependency:
npm error peer @angular/core@"19.0.0-next.9" from @angular/common@19.0.0-next.9
npm error node_modules/@angular/common
npm error   peer @angular/common@"^19.0.0-0 || ^19.1.0-0 || ^19.2.0-0 || ^19.3.0-0 || ^20.0.0-0" from @angular/material@19.0.0-next.4
npm error   node_modules/@angular/material
npm error     @angular/material@"19.0.0-next.4" from the root project
npm error   peer @angular/common@"^19.0.0-0 || ^19.1.0-0 || ^19.2.0-0 || ^19.3.0-0 || ^20.0.0-0" from @angular/cdk@19.0.0-next.4
npm error   node_modules/@angular/cdk
npm error     @angular/cdk@"19.0.0-next.4" from the root project
npm error     1 more (@angular/material)
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error ---
npm verbose cwd ---
npm verbose os Windows_NT 10.0.22631
npm verbose node v20.18.0
npm verbose npm  v10.8.2
npm verbose exit 1
npm verbose code 1
npm error A complete log of this run can be found in: ---

### Please provide the environment you discovered this bug in (run `ng version`)

Angular CLI: 18.2.8
Node: 20.18.0
Package Manager: npm 10.8.2
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1802.8 (cli-only)
@angular-devkit/core         18.2.8 (cli-only)
@angular-devkit/schematics   18.2.8 (cli-only)
@schematics/angular          18.2.8 (cli-only)

**Comment by alxhub** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`, or consider asking in the [Angular Community Discord](https://discord.com/invite/angular).

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).

**Comment by JoostK** [comment]
The Angular framework repo uses Yarn as dependency manager, npm may not work.
