### ISSUE TITLE
test(public_api): ensure that public_api_spec tests imports from barrels instead of angular2

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#5816]
angular2/angular2 is deprecated, so let's make sure the spec is testing the real public APIs.

This may not be possible until #5815 lands since angular2.ts is only partially exporting the compiler barrel.

**Comment by pkozlowski-opensource** [comment]
This got fixed via 979162d324fe56522422da83ccf9d4f7329f3a29, yay!
