### ISSUE TITLE
provideClientHydration doesn`t work in angular 18

### ISSUE THREAD

**Issue by smrb76** [angular/angular#58181]
### Which @angular/* package(s) are the source of the bug?
@angular/ssr

### Is this a regression?
No

### Description
I'm adding hydration capabilities to my website project(with new builder system), but after adding it, nothing happens, and no errors or logs are displayed

### Please provide the exception or error you saw
There is no error & exception

### Please provide the environment you discovered this bug in (run ng version)
`Angular CLI: 18.0.6
Node: 20.11.1
Package Manager: npm 10.2.4
OS: win32 x64

Angular: 18.0.4
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.6
@angular-devkit/build-angular   18.0.6
@angular-devkit/core            18.0.6
@angular-devkit/schematics      18.0.6
@angular/cli                    18.0.6
@angular/fire                   18.0.1
@angular/pwa                    18.0.5
@angular/ssr                    18.0.6
@schematics/angular             18.0.6
rxjs                            7.8.1
typescript                      5.4.4
zone.js                         0.14.7`

### Anything else?
app.config,ts
```
export const appConfig: ApplicationConfig = {
  providers: [
    importProvidersFrom(
      MatButtonModule,
      MatTabsModule,
      MatExpansionModule,
      MatAutocompleteModule,
      MatIconModule,
      MatTooltipModule,
      MatBadgeModule,
      MatDialogModule,
      MatSelectModule,
      MatSnackBarModule,
      ServiceWorkerModule.register(
        `https://${
          environment.development ? "dev." : ""
        }xyz.net/mobile/combined-sw.js`,
        {
          enabled: environment.development || environment.production,
          registrationStrategy: "registerImmediately",
        }
      ),
      AngularFireMessagingModule,
      AngularFireModule.initializeApp(firebaseConfig),
      HammerModule
    ),
    {
      provide: APP_ID,
      useValue: "xyz",
    },
    {provide: APP_BASE_HREF, useValue: "/"},
    {provide: DEFAULT_TIMEOUT, useValue: 1200},
    CanDeactivateGuard,
    {provide: HAMMER_LOADER, useValue: () => import("hammerjs")},
    provideZoneChangeDetection({eventCoalescing: true}),
    provideAnimations(),
    provideRouter(appRoutes,
      withPreloading(CustomPreloadingStrategy)
    ),
    provideHttpClient(
      withFetch(),
      withInterceptors(
        [
          HeadersInterceptor
        ]
      ),
    ),
    provideClientHydration(),
  ],
};
```
app.config.server.ts:
```
import { mergeApplicationConfig, ApplicationConfig } from '@angular/core';
import { provideServerRendering } from '@angular/platform-server';
import { appConfig } from './app.config';

const serverConfig: ApplicationConfig = {
  providers: [
    provideServerRendering()
  ]
};

export const config = mergeApplicationConfig(appConfig, serverConfig);

```
app.server.module.ts:
```
import {NgModule} from '@angular/core';
import {ServerModule} from '@angular/platform-server';
import {FocusMonitor} from '@angular/cdk/a11y';

@NgModule({
  imports: [
    ServerModule,
],
  providers: [
    FocusMonitor
  ],
})
export class AppServerModule {
}

```

**Comment by JoostK** [comment]
Without a runnable reproduction this won't be actionable to us

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
