### ISSUE TITLE
Angular Deferrable Views not working as expected when load the defer component in the browser network

### ISSUE THREAD

**Issue by shereensaeedhasaneen** [angular/angular#58180]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I was trying the @defer decorator to lazy load a specific component called <app-box-five>. Below is a screenshot of my code:
![Image](https://github.com/user-attachments/assets/83808133-3b6d-44f1-bbbc-2f28ed598935)
`@defer (on timer(5s)) {
  <app-box-five></app-box-five>
}`

After waiting 5 seconds, I checked the network tab in the browser and noticed that app.component.ts was lazy-loaded instead of box-five.component.ts.

I expected that only box-five.component.ts would be lazy-loaded, as shown in the screenshot:

![Image](https://github.com/user-attachments/assets/1e93623b-4f4c-49bf-b4d0-6f9f6307d97e)

please could you explain why this behavior happened ?

### Please provide the environment you discovered this bug in (run `ng version`)

Angular CLI: 17.3.10
Node: 18.20.4
Package Manager: npm 10.7.0
OS: win32 x64

Angular: 17.3.12
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.10
@angular-devkit/build-angular   17.3.10
@angular-devkit/core            17.3.10
@angular-devkit/schematics      17.3.10
@angular/cli                    17.3.10
@angular/ssr                    17.3.10
@schematics/angular             17.3.10
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.10

**Comment by JeanMeche** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).
