### ISSUE TITLE
Typing issue in di.d.ts

### ISSUE THREAD

**Issue by thelgevold** [angular/angular#5822]
I am getting a typing error in di.d.ts in alpha.52

```
export declare class AttributeMetadata extends DependencyMetadata {
    attributeName: string;
    constructor(attributeName: string);
    token: this;//looks like a bug
    toString(): string;
}
```
The TypeScript compiler (version 1.6) complains about the token property.
Error: node_modules/angular2/src/core/metadata/di.d.ts(32,12): error TS1110: Type expected.

Changing this to 'any' solves the problem.

**Comment by ericmartinezr** [comment]
@thelgevold check this one https://github.com/angular/angular/issues/5778

**Comment by thelgevold** [comment]
Ah ok.. Thanks!
