### ISSUE TITLE
Need cleanup function for afterNextRender similar to afterRenderEffect

### ISSUE THREAD

**Issue by sheikalthaf** [angular/angular#58225]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Currently Angular doesn't provide cleanup for `afterNextRender` and `afterRender` when compare to `afterRenderEffect` and `effect`. If we want to cleanup something we have to depend on the OnDestroy. It is better we have an cleanup which will run on component destroy.

```ts
class TestComponent implements OnDestroy {
    target = viewChild.required('#foo');
    resizeObserver!: ResizeObserver;

    constructor() {
        afterNextRender(() => {
            const target = this.target();
            this.resizeObserver = new ResizeObserver(() => {
                ....
            });
            this.resizeObserver.observe(target());
        });
    }

    ngOnDestroy() {
        this.resizeObserver.disconnect();
    }
}
```

### Proposed solution

Introducing `cleanup` to `afterNextRenderer` will simplify the code like below

```ts
class TestComponent {
    target = viewChild.required('#foo');

    constructor() {
        afterNextRender((onCleanup) => {
            const target = this.target();
            const resizeObserver = new ResizeObserver(() => {
                ....
            });
            resizeObserver.observe(target());
            onCleanup(() => resizeObserver.disconnect());
        });
    }
}
```

### Alternatives considered

For now we can use OnDestroy life cycle hook

**Comment by pkozlowski-opensource** [comment]
@sheikalthaf thnx for opening the issue. Discussing it in the team - we don't think there is a need for the cleanup for the `afterNextRender` function - as it runs only once you can do all the necessary cleanup in this function.
