### ISSUE TITLE
The click event handler raises an exception (even with empty body, ES5)

### ISSUE THREAD

**Issue by Dotneteer** [angular/angular#5823]
Using `angular2-polyfill.js` and `angular2.umd.js` raises an exception right after running the click event handler (`TypeError: l_context.onClickMe is not a function`). The event handler body runs (it can be even empty), the exception is raised:

You can find the plunker here: http://plnkr.co/edit/OjnOz7h7L2W7fPSD9pSx?p=preview

Click "Click me", and see the console log.

```javascript
(function() {

var ClickMeComponent = ng.core
.Component({
  selector: 'click-me',
  template: '<button (click)="onClickMe()">Click me</button>'
})
.Class({
  constructor: function() {
    this.onClickMe = function() {
      // console.log("You are my hero!")
    }
  }
});

var AppComponent = ng.core
.Component({
  selector: 'my-app',
  templateUrl: 'app/app.html',
  directives: [
    ClickMeComponent,
  ]
})
.Class({
  constructor: function() { }
});

document.addEventListener('DOMContentLoaded', function() {
  ng.platform.browser.bootstrap(AppComponent);
});

})()
```

**Comment by vicb** [comment]
Also see https://github.com/angular/angular/issues/5791

**Comment by Dotneteer** [comment]
It works with TS/ES6.

**Comment by pkozlowski-opensource** [comment]
@Dotneteer you had extra `(click)` event handler in your `app/app.html` - this click handler was trying to invoke a non-existing function. Here is a fixed plunk: http://plnkr.co/edit/bVVmX9cG05aCJcuk4qpN?p=preview

IMO this is a _good thing_ that we've got an error when a member that we are trying to call doesn't exists. Are you sure it works in TS??? Could you put together a plunk?
