### ISSUE TITLE
@let pollutes component scope

### ISSUE THREAD

**Issue by austinw-fineart** [angular/angular#58242]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

Given the component:
```ts
@Component({
  selector: 'app-root',
  standalone: true,
  template: `
    @let i = 0;
    {{ this.i }}
  `,
})
export class App {
  protected i = 1;
}
```
What I expected: 1
What I got instead: 0
Given the warning below, it seems even the compiler is confused.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-pesdcd?file=src%2Fmain.ts

### Please provide the exception or error you saw

▲ [WARNING] NG8112: @let i is declared but its value is never read. [plugin angular-compiler]

    src/main.ts:8:4:
      8 │     @let i = 0;
        ╵     ~~~~~~~~~~

### Please provide the environment you discovered this bug in (run `ng version`)

Angular CLI: 18.2.7
Node: 18.20.3
Package Manager: npm 10.2.3
OS: linux x64

Angular: 18.2.7
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.7
@angular-devkit/build-angular   18.2.7
@angular-devkit/core            18.2.7
@angular-devkit/schematics      18.2.7
@schematics/angular             18.2.7
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10

**Comment by pkozlowski-opensource** [comment]
I believe that it was fixed via https://github.com/angular/angular/pull/55183 (merged last week, will be part of the v19 release).
