### ISSUE TITLE
Will standard decorators be supported in JIT mode?

### ISSUE THREAD

**Issue by trusktr** [angular/angular#58251]
### Description

A type definition to silence TypeScript 5+ non-experimental decorators was introduced here:

- https://github.com/angular/angular/pull/49492

Its a type definition only, but no implementation for plain JS without a build.

Is this going to be supported?

Who on the Angular team is most familiar with standard decorators?

I would like to get feedback on the following problem that standard decorators have, and whether or not the current design complicates things for Angular in supporting standard decorators in JIT mode, and if the proposed solution would make Angular's support easier not only for implementation, but for user migration:

[discrepancy: we're allowed to get/set private fields, but not public fields, and public auto accessors are not fields.](https://x.com/trusktr/status/1846989651543802133)

### Proposed solution

Run angular in JIT mode while implementing the same behavior with standard decorators (probably gonne be tricky).

### Alternatives considered

Keep buildless mode (JIT mode) not working.

**Comment by alxhub** [comment]
JavaScript standard decorators don't include parameter decorators, which Angular uses for dependency injection. As a result, we can't really fully support them, so we've opted to support JIT only for the experimental mode for now and not put energy into building partial support.
