### ISSUE TITLE
HttpClient.get type signature does not match documentation

### ISSUE THREAD

**Issue by matttelliott** [angular/angular#58273]
### Describe the problem that you experienced

Hi All 👋!

I'm coming back to Angular after a few years or hiatus in React and I'm running into some typing issues.  I'm working on a Hacker News PWA using the latest version of Angular CLI. I'm trying to make a simple GET request using HttpClient, but `ng serve` is complaining about type errors and refusing to serve my app.

Here is my demo app at the line that is causing issues https://github.com/matttelliott/nghnpwa/blob/master/src/app/stories-list/stories-list.component.ts#L15 (at commit [57486f3](https://github.com/matttelliott/nghnpwa/commit/57486f34baff84025d720e8bb5e1f2b79246cb63)

### Enter the URL of the topic with the problem

https://angular.dev/guide/http/making-requests#fetching-json-data

### Describe what you were looking for in the documentation

The documentation here describes `HttpClient.get` as having an optional type argument, and if the argument is omitted the response should be typed as `any`

https://angular.dev/guide/http/making-requests#fetching-json-data
>Note the generic type argument which specifies that the data returned by the server will be of type Config. This argument is optional, and if you omit it then the returned data will have type any.

What I'm actually seeing in my editor and from Angular CLI is that this response is typed as `Object`
> `(property) StoriesListComponent.storyIds$: Observable<Object>`

### Describe the actions that led you to experience the problem

Here is my demo app at the line that is causing issues https://github.com/matttelliott/nghnpwa/blob/master/src/app/stories-list/stories-list.component.ts#L15

### Describe what you want to experience that would fix the problem

I think in this case the documentation is correct and the HttpClient implementation has a bug. I think that if there is no explicit type argument provided to `HttpClient.get` then `any` or `unknown` are both better defaults than `Object`. In this particular case the publick Hackernews API returns a JSON response with an array of strings `string[]`, so the behavior that I'm seeing with type `Object` is not accurate in this case.

### Add a screenshot if that helps illustrate the problem

![Image](https://github.com/user-attachments/assets/cc85a6aa-228d-4fd2-8e0e-3e5c1816694c)

### Provide any additional information here in as much as detail as you can

I'm of course open to the possibility that I've made a mistake in my own code, but in this case I'm having a hard time finding where that might be. In this case I think the example I've provided at https://github.com/matttelliott/nghnpwa/blob/master/src/app/stories-list/stories-list.component.ts#L15 is fairly straightforward and does not match my expectations based on the documentation.

I also understand the motivations for discouraging the use of `any`, but in this case I think it is appropriate. In this case I need to combine multiple HTTP requests before I get a response that I can meaningfully type, and I'd like to be able to do this without needing to explicitly type every intermediary request, especially during development. I could also understand the use of `unknown` here, but I think that `Object` is incorrect.

As a stretch goal, I think it would be nice if Angular CLI and `ng serve` provided a command line option to skip type checking at development time. I'm a huge advocate for Typescript and strong typing, largely thanks to Angular's influence on me :P, but during development and especially during prototyping, I think it would be nice to be able to treat type errors as warnings so that I can continue to build out my UI without being hindered by type errors for types that I might not yet have fully fleshed out.

Thanks, Angular! I still think you're the best framework out there :)

**Comment by JeanMeche** [comment]
`any` is the worst type an API can provide/return. `Object` is actually a false-friend, it matches anything that's not-nullable. ([see demo](https://www.typescriptlang.org/play/?#code/MYewdgzgLgBAhgLgPICMBWBTYsC8MDaAugNwBQoksKy6WuMA5A2RdDMDZtjHgMwvg2AE050eMMAFcANtOIwA9ApgBpJOUGwMo7nklghGAGYBLMBiHylqpEA)). 

That being said, the API is correct but the doc is not up-to-date.

**Comment by matttelliott** [comment]
Thank you for your very fast response!

I see your demo, but what do you mean here by "false-friend"? I'm not familiar with this phrase.

I generally agree very much that `any` is something that we should strive to avoid, but I also hold the opinion that overly strict typing at development or prototyping time is something of a premature optimization. In the early stages I want to be able to iterate quickly, and I don't necessarily need this level of definition until I'm ready to go to QA or Production.

To this point and what I mentioned above as a "stretch-goal", does Angular offer any way to relax these standards during development time? I've searched around but I haven't found anything so far. I'm very much an advocate for strong typing for teamwork and production apps, but I think there is a fair argument for optionally relaxing these standards when developing on my local machine.

**Comment by JeanMeche** [comment]
See [False-friend on wikipedia](https://en.wikipedia.org/wiki/False_friend). 

I stand corrected, `Object` is more akin to `unknown` but excludes `undefined | null`. It allows you to do some narrowing

```
const a:Object = [];

if(Array.isArray(a)) {
    // This is runtime safe & typesafe 
    a[3];
}
```

Angular relies on typescript for typesafety, in the case of httpClient you can force the type of `any` by forcing the generic `http.get<any>(...) `. 
Also note that relaxing typesafety during developement is considered a footgun, as it becomes more and more difficult to fix type issues as the project size increases.


 ([see](https://www.typescriptlang.org/play/?#code/MYewdgzgLgBAhgLgPICMBWBTYsC8MDaAugNwBQoksKy6WuMA5A2RdDMDZtjHgMwvg2AE050eMMAFcANtOIwA9ApgBpJOUGwMo7nklghGAGYBLMBiHylq9aRNGAFAEEATi7gBPAHQmIr9x4OcACUwTAA3qQw0YrKACoAFr4wyS76UCYAthgwEHBGOQBkMFAeAA4YeQUwUTFw+LwkpAC+QA)).

**Comment by matttelliott** [comment]
> Angular relies on typescript for typesafety, in the case of httpClient you can force the type of any by forcing the generic http.get<any>(...) .
Also note that relaxing typesafety during developement is considered a footgun, as it becomes more and more difficult to fix type issues as the project size increases.

I agree with this, and this is the situation that I'd like to avoid. I understand that I could theoretically provide `<any>` as a type argument here as sort of shortcut, but I don't want to save this shortcut to disk or commit it to my project.

My thoughts here are inspired by how Vite separates transpilation from type checking, and I'm trying to emulate a similar workflow where i can iterate quickly at first and then have the type checker help me find where I need to fill in the details https://vite.dev/guide/features.html#transpile-only. For as much as I value strong typing and strict checking, I consider that check to be a validation layer that should run alongside unit tests and linting, and shouldn't get in the way during development, especially when working against third party APIs where responses are inconsistent or poorly documented.

I also appreciate that this might devolve into more opinionated, subjective arguments that are outside the scope of the original issue.

I think we are still in agreement that the docs don't match the behavior, and I'm happy to leave the issue at that :P Thank you and enjoy your weekend!
