### ISSUE TITLE
Angular Deferrable Views are not working as expected when loading the deferred component in the browser network

### ISSUE THREAD

**Issue by ChrisBoostwords** [angular/angular#58278]
**Description :**
```
@defer (on timer(10s)) 
{ 
  <app-box-five></app-box-five> 
}

```

After waiting 10 seconds, I checked the network tab in the browser and noticed that app.component.ts was lazy-loaded instead of box-five.component.ts.

I expected that only box-five.component.ts would be lazy-loaded.

Could you please explain why this behavior occurred?

**Comment by JoostK** [comment]
Please share additional on the exact setup, ideally a runnable reproduction; the current snippet doesn't give the full picture.

**Comment by JeanMeche** [comment]
Please have a look at https://stackoverflow.com/questions/79081921/angular-deferrable-views-not-working-as-expected-when-load-the-defer-component-i
