### ISSUE TITLE
Sometimes angular router comes to be vulnerable to throw error of Cannot read properties of undefined(reading 'ɵcmp')

### ISSUE THREAD

**Issue by luozt** [angular/angular#58277]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

I have been developing an app using the Angular framework for 7 years and it has a large user base. But there is a stubborn bug that often occurs, which is' Cannot read properties of undefined (reading 'ɵ cmp') '. This bug is usually triggered during route redirection. After triggering, the entire app can no longer redirect routes. But this problem is difficult to reproduce as there are no clear steps for reproducing it. Often, it can only be replicated on certain specific user devices. This may be related to the robustness of the angular/outer. Please arrange for research on this issue. Reference materials include:[01-error-reading-ecmp.txt](https://github.com/user-attachments/files/17449805/01-error-reading-ecmp.txt) [main.e4793e83.trimed.js.txt](https://github.com/user-attachments/files/17449811/main.e4793e83.trimed.js.txt)

### Please provide the exception or error you saw

Uncaught(in promise):
TypeError: Cannot read properties of undefined(reading 'ɵcmp')
at ht(main.e4793e83.js:1739:2039)
at rt (main.e4793e83.js:1739:1207)
at Array.map (<anonymous>)
at st.directiveDefs (main.e4793e83.js:1739:1133)
at wd (main.e4793e83.js:2099:6000)
at ap

### Please provide the environment you discovered this bug in (run `ng version`)

Angular CLI: 13.1.4
Node: 16.18.0
Package Manager: yarn 1.22.22
OS: win32 x64

Angular: 13.1.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1301.4
@angular-devkit/core         13.1.4
@angular-devkit/schematics   13.1.4
@angular/cli                 13.1.4
@schematics/angular          13.1.4
rxjs                         7.4.0
typescript                   4.5.5

**Comment by JoostK** [comment]
Without a true reproduction this won't be actionable to us; `Cannot read properties of undefined(reading 'ɵcmp')` may typically occur in the presence of import cycles within the application, where symbols are left uninitialized in order to break the cycle.

Closing as a support request for now, but feel free to open a new issue with reproduction.
