### ISSUE TITLE
Feature Request: detect circular dependency injection and throw compile error

### ISSUE THREAD

**Issue by ptandler** [angular/angular#58281]
### Which @angular/* package(s) are relevant/related to the feature request?

compiler

### Description

In a large Angular app it can happen that circular dependency injection is introduced - and this leads to run-time errors. It would be very handy to get an error already during static code analysis at compile time.

The simplest case that should be detected is this:

```ts
// a.service.ts
@Injectable()
export class A {
  private readonly b = inject(B);
}

// b.service.ts
@Injectable()
export class B {
  private readonly a = inject(A);
}
```

But of course, it's not as easy to track down if you have more services in between.

### Proposed solution

If there is a circular dependency injection, there should be a compile-time error

### Alternatives considered

- Currently, you get a run-time error. So if you're lucky and have good test coverage, tests will also detect this issue.
- Th eslint rule `import/no-cycle` implies that there are no dependency injection circles - but there are cases e.g. when you use `forwardRef()` where you might have import cycles - but still don't want circular dependency injection.
- This request is similar to #48976 but (slightly) different: The error should not just detect problems for standalone components, but everywhere when dependency injection is used.
- I suggested this as eslint rule first (https://github.com/angular-eslint/angular-eslint/issues/2082) and @JamesHenry said that this should rather be a framework feature.

**Comment by alxhub** [comment]
This is not really feasible - DI config is incredibly dynamic. There's really no way to know at compile time if any given provider will be circular or not.
