### ISSUE TITLE
Failure when building Angular/core

### ISSUE THREAD

**Issue by aguskov1987** [angular/angular#58292]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

When trying to build Angular from source (on Windows) the following error is encountered. Looks like an import cannot get resolved.

```
C:\Path\to\Angular\angular>yarn build
yarn run v1.22.19
$ tsx --tsconfig scripts/tsconfig.json scripts/build/build-packages-dist.mts
######################################
  Building release packages...
######################################
Loading: 0 packages loaded
//packages/animations:npm_package
//packages/common:npm_package
//packages/compiler:npm_package
//packages/compiler-cli:npm_package
//packages/core:npm_package
//packages/elements:npm_package
//packages/forms:npm_package
//packages/language-service:npm_package
//packages/localize:npm_package
//packages/platform-browser:npm_package
//packages/platform-browser-dynamic:npm_package
//packages/platform-server:npm_package
//packages/router:npm_package
//packages/service-worker:npm_package
//packages/upgrade:npm_package
C:/users/andrey/_bazel_andrey/4pgcrmzy/execroot/angular/bazel-out/x64_windows-fastbuild/bin
INFO: Analyzed 16 targets (1 packages loaded, 2007 targets configured).
INFO: Found 16 targets...
ERROR: C:/Path/to/Angular/angular/packages/core/BUILD.bazel:51:11: ng_package: Rollup fesm2022 (packages/core/core.mjs) failed: (Exit 1): rollup.bat failed: error executing command bazel-out\x64_windows-opt-exec-2B5CBBC6\bin\packages\bazel\src\ng_package\rollup\rollup.bat --input bazel-out/x64_windows-fastbuild-ST-2e5f3376adb5/bin/packages/core/core.mjs --config ... (remaining 9 arguments skipped)
(!) Plugin node-resolve: node-resolve: The `customResolveOptions.moduleDirectory` option has been deprecated. Use `moduleDirectories`, which must be an array.
[!] Error: 'producerMarkClean' is not exported by external/npm/node_modules/@angular/core/fesm2022/primitives/signals.mjs, imported by bazel-out/x64_windows-fastbuild-ST-2e5f3376adb5/bin/packages/core/src/render3/reactivity/linked_signal.mjs
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
bazel-out/x64_windows-fastbuild-ST-2e5f3376adb5/bin/packages/core/src/render3/reactivity/linked_signal.mjs (9:9)
 7:  */
 8: import { signalAsReadonlyFn } from './signal';
 9: import { producerMarkClean, SIGNAL, signalSetFn, signalUpdateFn, producerUpdateValueVersion, REACTIVE_NODE, defaultEquals, consumerBeforeComputation, consumerAfterComputation, producerAccessed, } from '@angular/core/primitives/signals';
             ^
10: import { performanceMarkFeature } from '../../util/performance';
11: const identityFn = (v) => v;
Error: 'producerMarkClean' is not exported by external/npm/node_modules/@angular/core/fesm2022/primitives/signals.mjs, imported by bazel-out/x64_windows-fastbuild-ST-2e5f3376adb5/bin/packages/core/src/render3/reactivity/linked_signal.mjs
    at error (C:\_bazel\4pgcrmzy\execroot\angular\node_modules\rollup\dist\shared\rollup.js:198:30)
    at Module.error (C:\_bazel\4pgcrmzy\execroot\angular\node_modules\rollup\dist\shared\rollup.js:12560:16)
    at Module.traceVariable (C:\_bazel\4pgcrmzy\execroot\angular\node_modules\rollup\dist\shared\rollup.js:12919:29)
    at ModuleScope.findVariable (C:\_bazel\4pgcrmzy\execroot\angular\node_modules\rollup\dist\shared\rollup.js:11571:39)
    at FunctionScope.findVariable (C:\_bazel\4pgcrmzy\execroot\angular\node_modules\rollup\dist\shared\rollup.js:6503:38)
    at ChildScope.findVariable (C:\_bazel\4pgcrmzy\execroot\angular\node_modules\rollup\dist\shared\rollup.js:6503:38)
    at ReturnValueScope.findVariable (C:\_bazel\4pgcrmzy\execroot\angular\node_modules\rollup\dist\shared\rollup.js:6503:38)
    at ChildScope.findVariable (C:\_bazel\4pgcrmzy\execroot\angular\node_modules\rollup\dist\shared\rollup.js:6503:38)
    at Identifier.bind (C:\_bazel\4pgcrmzy\execroot\angular\node_modules\rollup\dist\shared\rollup.js:7570:40)
    at CallExpression.bind (C:\_bazel\4pgcrmzy\execroot\angular\node_modules\rollup\dist\shared\rollup.js:5400:23)

ERROR: C:/Path/to/Angular/angular/packages/core/BUILD.bazel:51:11 Angular Packaging: building npm package //packages/core:npm_package failed: (Exit 1): rollup.bat failed: error executing command bazel-out\x64_windows-opt-exec-2B5CBBC6\bin\packages\bazel\src\ng_package\rollup\rollup.bat --input bazel-out/x64_windows-fastbuild-ST-2e5f3376adb5/bin/packages/core/core.mjs --config ... (remaining 9 arguments skipped)
INFO: Elapsed time: 35.487s, Critical Path: 28.88s
INFO: 40 processes: 23 internal, 6 local, 11 worker.
FAILED: Build did NOT complete successfully
node:internal/errors:984
  const err = new Error(message);
              ^

Error: Command failed: yarn -s bazel build --config=snapshot-build //packages/animations:npm_package //packages/common:npm_package //packages/compiler:npm_package //packages/compiler-cli:npm_package //packages/core:npm_package //packages/elements:npm_package //packages/forms:npm_package //packages/language-service:npm_package //packages/localize:npm_package //packages/platform-browser:npm_package //packages/platform-browser-dynamic:npm_package //packages/platform-server:npm_package //packages/router:npm_package //packages/service-worker:npm_package //packages/upgrade:npm_package //packages/bazel:npm_package
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:891:11)
    at execSync (node:child_process:963:15)
    at exec (C:\Path\to\Angular\angular\scripts\build\package-builder.mts:135:18)
    at buildReleasePackages (C:\Path\to\Angular\angular\scripts\build\package-builder.mts:89:3)
    at performDefaultSnapshotBuild (C:\Path\to\Angular\angular\scripts\build\package-builder.mts:45:10)
    at <anonymous> (C:\Path\to\Angular\angular\scripts\build\build-packages-dist.mts:17:1)
    at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:473:24) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 9528,
  stdout: null,
  stderr: null
}

Node.js v20.18.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

 It is rather strange since the producerMarkClean function is exported in the index.ts of core/primitives/signals ¯\(°_o)/¯

### Please provide the environment you discovered this bug in (run `ng version`)

Angular CLI: 19.0.0-next.11
Node: 20.18.0
Package Manager: yarn 1.22.19
OS: win32 x64

Angular: 19.0.0-next.5
... animations, core

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.0-next.11
@angular-devkit/architect-cli   0.1900.0-next.11
@angular-devkit/build-angular   19.0.0-next.11
@angular-devkit/core            19.0.0-next.11
@angular-devkit/schematics      19.0.0-next.11
@angular/build                  19.0.0-next.11
@angular/build-tooling          0.0.0-55c0cd826f5ad56c3bccc7272313c75467543f3f
@angular/cdk                    19.0.0-next.4
@angular/cli                    19.0.0-next.11
@angular/material               19.0.0-next.4
@angular/ng-dev                 <error>
@angular/ssr                    19.0.0-next.11
@schematics/angular             19.0.0-next.11
rxjs                            7.8.1
typescript                      5.6.2

### Anything else?

Building Angular "19.0.0-next.10"
bazel 5.0.0

**Comment by aguskov1987** [comment]
The exports of the signals.mjs file:

export { REACTIVE_NODE, SIGNAL, SIGNAL_NODE, consumerAfterComputation, consumerBeforeComputation, consumerDestroy, consumerMarkDirty, consumerPollProducersForChange, createComputed, createSignal, createWatch, defaultEquals, getActiveConsumer, isInNotificationPhase, isReactive, producerAccessed, producerIncrementEpoch, **_producerMarkClean_**, producerNotifyConsumers, producerUpdateValueVersion, producerUpdatesAllowed, runPostSignalSetFn, setActiveConsumer, setAlternateWeakRefImpl, setPostSignalSetFn, setThrowInvalidWriteToSignalError, signalSetFn, signalUpdateFn };
//# sourceMappingURL=signals.mjs.map

**Comment by JoostK** [comment]
That's a relatively new export. Could you try `yarn bazel clean` to see if this is stale cache issue?

**Comment by aguskov1987** [comment]
I cleaned the bazel cache with `yarn bazel clean` as well as with `bazel clean`. Both completed but unfortunately it did not help with the build error. Also, I checked the dist folder at the path specified and I stay corrected - indeed there is no producerMarkClean export in C:\Path\to\Angular\angular\dist\angular\external\npm\node_modules\@angular\core\fesm2022\primitives\signals.mjs

**Comment by aguskov1987** [comment]
After I manually copied the signals.mjs and signals.mjs.map from the dist/bin to dist/angular folder, the issue seems to be resolved. However, I am now getting: 

[!] (plugin commonjs--resolver) Error: Could not load C:\Users\Andrey\_bazel_Andrey\4pgcrmzy\execroot\angular\node_modules\@angular\core\schematics\migrations\signal-migration\src.js: ENOENT: no such file or directory, open 'C:\Users\Andrey\_bazel_Andrey\4pgcrmzy\execroot\angular\node_modules\@angular\core\schematics\migrations\signal-migration\src.js'

The file is not there, obviously. I don't quite understand how it is generated. Can somebody point to the BUILD file where it i specified please?

**Comment by JeanMeche** [comment]
fwiw, I'd recommend running `yarn bazel clean --expunge` (that last part is important).

**Comment by aguskov1987** [comment]
Nothing really helped. As I was trying to build on Windows, I installed Linux sub system, pulled the repo and did the build from there. Something is not working on my Windows box and it's probably not worth figuring out what it is. Closing the issue.

**Comment by wartab** [comment]
fwiw I never managed to get any of the bazel commands to work on any of my Windows machines either. Even installing all dependencies on Windows doesn't work without telling yarn to ignore basically everything that could go wrong.
