### ISSUE TITLE
[Angular Proxy] WebSocket Connection Doesn't Even Last 5min

### ISSUE THREAD

**Issue by AbdallahR99** [angular/angular#58293]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

when reverse a websocket connection it doesn't last few minutes then disconnect, how to set the websocket timeout?
in the ASP.NET when I do a reverse proxy for a websocket then try to extend its connection duration I got the `ActivityTimeout` option

what's equal to `ActivityTimeout` here?

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
