### ISSUE TITLE
Official hero form demo from angular.io broken in alpha 52

### ISSUE THREAD

**Issue by user414** [angular/angular#5831]
Upgrade to latest alpha 52, and beside noticing child dependencies need to be added manually in npm like rxjs and others a few things stopped working. I'm imagining it must be related to the problems in the official hero form here is a plunk with angular update to alpha 52

http://plnkr.co/edit/L0c9cXb7KHOe5K0dMj8o?p=preview

Not sure if it's a bug and alpha 52 needs to be fixed or the demo needs to be update either way something need to be done.

**Comment by vicb** [comment]
docs are getting updated to reflect the latest code updates.
