### ISSUE TITLE
Pipe instance inside if statement is created even if previous condition evaluates to false

### ISSUE THREAD

**Issue by Binek115** [angular/angular#58312]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I have a pipe which injects service that has not been provided by the component where pipe is used.
```typescript
@Injectable()
export class TestService {}

@Pipe({
  name: 'testPipe',
  standalone: true,
})
export class TestPipe implements PipeTransform {
  readonly TestService = inject(TestService);
  transform(item: any) {
    return true;
  }
}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [TestPipe],
  template: `@if(false && ('' | testPipe)) { }`,
})
export class App {}`
```
In template I use pipe in `@if` statement: `@if(false && ('' | testPipe)) { }` and I get a `NullInjectorError: No provider for _TestService!` but I think I should not because `false` inside `@if` statement should prevent from creating pipe instance.
If I wrap it with another `@if` there is no issue:
```typescript
@if(false) {
  @if('' | testPipe) {

  }
 }
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-yqjews?file=src%2Fmain.ts

### Please provide the environment you discovered this bug in (run `ng version`)

Angular CLI: 18.2.7
Node: 18.20.3
Package Manager: npm 10.2.3
OS: linux x64

Angular: 18.2.7
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.7
@angular-devkit/build-angular   18.2.7
@angular-devkit/core            18.2.7
@angular-devkit/schematics      18.2.7
@schematics/angular             18.2.7
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10

**Comment by JoostK** [comment]
This is working as designed; pipe instances are created per embedded view, so they follow its lifecycle. Pipe instances are therefore not created ad-hoc, nor are they destroyed whenever they aren't "reachable" anymore.
