### ISSUE TITLE
one standalone component with multiple HTML support

### ISSUE THREAD

**Issue by supercool-1989** [angular/angular#58327]
I'm trying to breakdown bigger HTML chunks which has repeated markup based on flags.

Is there a way we can make html code split into files one.html, two.html and render them into my component (.ts will decide which html to load)

Basically idea is one component -> multiple html files

I can have single big html like previous and use ng-template/ngContentOutlet but this is still making readability a issue for a 2k+ lines on html.

SO post: https://stackoverflow.com/questions/79118290/one-component-with-multiple-html-support

This option should is good to have esle HTML is not getting smaller anytime soon as even i cant split into components for 1 flag.

**Comment by pkozlowski-opensource** [comment]
In case of templates that are 2k+ lines I think there is a need to split those into smaller components. As you mentioned there are also `<ng-template>`s. So I believe that we do have enough primitives to split UI into smaller pieces and organize it better. Adding new mechanisms would muddy the waters and add yet another way of doing things. 

At the same time we are continuously working on making components lighter and easier to create.

I'm going close this issue based on the above.
