### ISSUE TITLE
redirecting binding errors in a routed view to console

### ISSUE THREAD

**Issue by lucamorelli** [angular/angular#5833]
Hi, from what I see this way
```
bootstrap(AppCmp, [ ROUTER_PROVIDERS, HTTP_PROVIDERS ])
.catch(err => console.error(err));;
```
I can redirect to console any error that is generated in the bootstrap phase and the opening of the main page, but this catch doesn't cover errors happening for the rest of the program activity.
Yesterday, updating a program from 47 to 52, trying to open any view of the program before completing the changes (ng-model -> ngModel) the loading fails leaving a blank page and aborting the creation of the component class, but I never received any error message in the log console, and I haven't found any resource that explains how to do this.
Same problem I had with the calls to http.get().map for the changes with rxJs: tracking the execution I see that the error is tracked but I don't see anything in the log console.
Where can I find any resource to explain how to route these kind of errors? sorry if I posted this here, but I asked this in gitter for a day without any answer

**Comment by vicb** [comment]
obsolete - former router
