### ISSUE TITLE
EventEmitter emitting 1-2 times and then do not working

### ISSUE THREAD

**Issue by Aibulat-Urazmetov** [angular/angular#58331]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

Im call this.MyEventEmitter.emit(this) in variable setter and it working 1-2 times and ignore .emit(this) calls after. Im do this in custom class (not angular component or similar). I've tried put new data every time when call emit() but its wasn't help.

**Comment by e-oz** [comment]
It is age of AI, try to translate your message usually AI. It's unreadable.

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
