### ISSUE TITLE
Bootstrapping in JS: Add sugar method to abstract away DOM interaction

### ISSUE THREAD

**Issue by wardbell** [angular/angular#5834]
As I write it seems necessary to launch an A2 app in ES5 with the following:

```
document.addEventListener('DOMContentLoaded', function() {
  ng.platform.browser.bootstrap(AppComponent);
});
```

An Angular goal is to abstract away interaction with the DOM.  Would be nice to have a function that added the event listener for us ... and perhaps also trapped boot-up failure and reported it nicely.

**Comment by humana-fragilitas** [comment]
@vicb @chuckjaz do you think it would make sense to apply the logic suggested by @wardbell in the `application_ref.ts` class ([line 498](https://github.com/angular/angular/blob/master/packages/core/src/application_ref.ts#L498)) and turn the type returned by the `bootstrap<C>()` method into a `Promise<ComponentRef<C>>` ?

```typescript
import { PLATFORM_ID } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';
. . .
bootstrap<C>(componentOrFactory: ComponentFactory<C> | Type<C>, rootSelectorOrNode?: string | any):
	Promise<ComponentRef<C>> {
	
	const platformId = this._injector.get(PLATFORM_ID);
	const bootstrapPromise = new Promise<ComponentRef<C>>((resolve, reject) => {

		function _bootstrap() {
			// component bootstrap logic here
		}
		
		function _bootstrapOnDOMContentLoaded(){
			if (document.readyState === 'complete') {
				_bootstrap();
			} else {
				document.addEventListener('DOMContentLoaded', () => {
					_bootstrap();
				});  
			}
		}
	
		(isPlatformBrowser(platformId)) ? _bootstrapOnDOMContentLoaded() :
			_bootstrap();

	});

	return bootstrapPromise;

}
```
I am getting into studying the Angular code base and I would like to possibly pursue my first contribution; a bit of help to get on the right track would be greatly appreciated.

**Comment by chuckjaz** [comment]
@tbosch Would be better able to answer this.

**Comment by pkozlowski-opensource** [comment]
I believe that this is obsolete now as we moved away from ES5.
