### ISSUE TITLE
Fresh build with Angular v18.2.1 has 'Unexpected '{' when opening in Safari, mobile browsers

### ISSUE THREAD

**Issue by rjc23** [angular/angular#58340]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I had Angular 18.2.1 installed

I ran `ng new myproject`

Changed nothing in the project. Ran

`ng build`

then `cd dist/myproject/browser`

then served it locally using

`http-server -p 8080`

The angular app ran perfectly on Chrome, firefox etc, but not on Safari, and not on Chrome, safari on mobile

![Image](https://github.com/user-attachments/assets/7fa00ae1-dabd-4e48-9479-f252ce02dfdd)

The issue is with an unexpected '{' in main.js and polyfills.js

I downgraded to v18.1.2 and did not encounter the error.

### Please provide the environment you discovered this bug in (run `ng version`)

Angular CLI: 18.2.10
Node: 18.19.0
Package Manager: npm 10.2.3
OS: darwin arm64

Angular: 18.2.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.10
@angular-devkit/build-angular   18.2.10
@angular-devkit/core            18.2.10
@angular-devkit/schematics      18.2.10
@angular/cdk                    18.2.10
@angular/cli                    18.2.10
@angular/material               18.2.10
@schematics/angular             18.2.10
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10

**Comment by JeanMeche** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).
