### ISSUE TITLE
Change detection doesn't fire in host directives on custom elements

### ISSUE THREAD

**Issue by snortblt** [angular/angular#58346]
### Which @angular/* package(s) are the source of the bug?

elements

### Is this a regression?

Yes

### Description

When adding a directive as a host directive to a component that gets exposed as a custom element, change detection doesn't fire in ANY case on that directive, including when calling `ChangeDetectorRef.detectChanges` directly. Inputs mapping also doesn't work. In contrast, the directive does work properly when used in Storybook as a native Angular component or when inheriting the component from it instead of using as host directive. Alternatively, changing the inputs on the directive to signals also fixes, but `ngOnChanges` is still never called regardless.

**Comment by alxhub** [comment]
Without a runnable reproduction, we don't have much chance of investigating the several different issues reported here.

**Comment by alxhub** [comment]
Closing as without a reproduction, we can't investigate this issue.

**Comment by chintankavathia** [comment]
@alxhub This one is duplicate of https://github.com/angular/angular/issues/53193 which provides reproduction steps. I also have a PR https://github.com/angular/angular/pull/57624 if you wanna take a look 😄 .
