### ISSUE TITLE
ReferenceError: Cannot access 'RufSidemenuComponent' before initialization

### ISSUE THREAD

**Issue by nehaGI** [angular/angular#58356]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

I'm getting  **ReferenceError: Cannot access 'RufSidemenuComponent' before initialization** when i'm running test cases. This error is not coming where running server. On UI my component renders without any errors but when run test cases it gives the error.

My component use forwardRef and it do not cause any problem in component but for test cases it is causing problem.

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
