### ISSUE TITLE
Standalone migration making standalone: true to standalone: false

### ISSUE THREAD

**Issue by sheikalthaf** [angular/angular#58353]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

I tried to update to next version of Angular and migration marks all the components standalone: false (note: all my components are standalone).
![Image](https://github.com/user-attachments/assets/d388674a-441d-413b-8b8f-1e9cce105185)

I upgrade from Angular 19.0.0-next.10 -> 19.0.0-next.11

### Please provide the environment you discovered this bug in (run `ng version`)

Angular CLI: 19.0.0-next.13
Node: 20.17.0
Package Manager: pnpm 9.8.0
OS: win32 x64

Angular: 19.0.0-next.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.0-next.13
@angular-devkit/build-angular   19.0.0-next.13
@angular-devkit/core            19.0.0-next.13
@angular-devkit/schematics      19.0.0-next.13
@angular/build                  19.0.0-next.13
@angular/cdk                    18.1.1
@angular/cli                    19.0.0-next.13
@angular/ssr                    19.0.0-next.13
@schematics/angular             19.0.0-next.13
ng-packagr                      19.0.0-next.6
rxjs                            7.8.1
typescript                      5.6.3

**Comment by JoostK** [comment]
Thanks for testing the prereleases! This problem is being tracked in https://github.com/angular/angular/issues/58344
