### ISSUE TITLE
Signals?

### ISSUE THREAD

**Issue by Rutaer** [angular/angular#58364]
### Description

Dear Angular Team. What about Signals? When they started at Angular 16/17 promises were big - zone free... observables f**k off! to this point signals are for  child <--> parent inputs/outputs and that's it.  Are these promises of "lets get rid of RxJs" - they are boiling plate... Is it sort of Russia fighting World without success or what?

### Proposed solution

I am not a hen and not producing eggs. But I am able to distinguish good ones from bad ones

### Alternatives considered

Please just do it - "make Signals great again!"

**Comment by spock123** [comment]
@Rutaer Not sure what you're talking about? Can you be more specific?

We're using signals everywhere, standalone components, with zoneless change detection, it works wonderfully.

**Comment by alxhub** [comment]
The issue tracker is not the place for non-constructive feedback.
