### ISSUE TITLE
TestBed.inject not working on standalone components with providers

### ISSUE THREAD

**Issue by thecp** [angular/angular#58365]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

When using TestBed.inject on a standalone component, there seem to be problems that TestBed.inject does not return the correctly injected service. 

Here is an example of the service:

```
@Component({
  selector: 'app-whatever',
  standalone: true,
  providers: [AlertService], // <-- Here is the problem
})
export class AppComponent {
  constructor(private alertService: AlertService) {}

  doSomething() {
    this.alertService.alert('I am working');
  }
}
```

We now want to to test if the service function was called, when the component does something:

```
const alertService = TestBed.inject(AlertService);
const alertSpy = spyOn(alertService, 'alert').and.stub();
component.doSomething();
expect(alertSpy).toHaveBeenCalled();
```

However this fails. When removing the providers array from the component metadata the test works but the application itself throws an error. A workaround is to get the service instance like this:

```const alertService = fixture.debugElement.injector.get(AlertService);```

### Please provide a link to a minimal reproduction of the bug

https://github.com/thecp/ng-test-problem-with-providers

### Please provide the exception or error you saw

Expected spy alert to have been called.
            at <Jasmine>
            at UserContext.apply (src/app/app.component.spec.ts:41:22)
            at _ZoneDelegate.invoke (node_modules/zone.js/fesm2015/zone.js:369:28)
            at ProxyZoneSpec.onInvoke (node_modules/zone.js/fesm2015/zone-testing.js:2081:39)
            at _ZoneDelegate.invoke (node_modules/zone.js/fesm2015/zone.js:368:34)

### Please provide the environment you discovered this bug in (run `ng version`)

Angular CLI: 18.2.10
Node: 20.18.0
Package Manager: yarn 1.22.22
OS: linux x64

Angular: 18.2.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.10
@angular-devkit/build-angular   18.2.10
@angular-devkit/core            18.2.10
@angular-devkit/schematics      18.2.10
@angular/cdk                    18.2.10
@angular/cli                    18.2.10
@angular/material               18.2.10
@schematics/angular             18.2.10
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10

**Comment by JeanMeche** [comment]
The Component use it's own instance of the `AlertService` because the provider has been overridden at the NodeInjector level.  

When you do `TestBed.inject` you're actually accessing the instance provided by the RootInjector.
