### ISSUE TITLE
Content security policy Issue for ZAP scan with -unsafe-inline' option

### ISSUE THREAD

**Issue by vinuvatassery** [angular/angular#58376]
### Which @angular/* package(s) are the source of the bug?

platform-browser

### Is this a regression?

Yes

### Description

In my application, I am configuring the Content Security Policy for script-src and style-src. When I include the 'unsafe-inline' option, it raises a vulnerability issue during the ZAP security scan. To address this, I removed all inline styles and scripts from the application. However, we are still encountering the same issue.

I created a sample Angular project, but I'm facing the same problem there as well. Can we set a Content Security Policy without using the 'unsafe-inline' option?

https://github.com/vinuvatassery/CSP-Implementation-main

Note: I have also tried using SHA and nonce, but those solutions are not working either.

### Please provide a link to a minimal reproduction of the bug

https://github.com/vinuvatassery/CSP-Implementation-main

### Please provide the exception or error you saw

platform-browser.mjs:381 

 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-XGYGoKIk88IyhvKNoTx7mpj0KKQwHNr9IRjk+Slrey4='), or a nonce ('nonce-...') is required to enable inline execution.

### Anything else?

![Image](https://github.com/user-attachments/assets/3cf5cfe8-e37d-4908-8874-a21cebe2f53b)

**Comment by JoostK** [comment]
Please see #54031 and #54963.

You'd first need to determine which style is causing this error. The error is reported from `platform-browser.mjs`, but originates from other code that initiates the inline style; that is the important part in determining how to resolve those violations.

**Comment by vinuvatassery** [comment]
In my fresh Angular project , there is no inline style or scripts , I have given. But still it is causing error.

**Comment by apappas1129** [comment]
> In my fresh Angular project , there is no inline style or scripts , I have given. But still it is causing error.

can you show your dependencies from the package.json?

**Comment by vinuvatassery** [comment]
@apappas1129  Please find the dependencies in below screenshot

![Image](https://github.com/user-attachments/assets/3e6ed821-d95b-4106-8b82-1cc028be3da0)

**Comment by JoostK** [comment]
This is working as expected; the contents of [Csp.component.css](https://github.com/vinuvatassery/CSP-Implementation-main/blob/main/src/Csp/Csp.component.css), although commented out, do cause a `style` element to be added to the `<head>` element of the document, which requires it to have a CSP nonce or hash when `unsafe-inline` is not enabled. Please see https://angular.dev/best-practices/security#content-security-policy for how to insert the `<style>` elements with nonce.
