### ISSUE TITLE
Missing documentation for FormControl

### ISSUE THREAD

**Issue by szeinedd-nrel** [angular/angular#58371]
### Describe the problem that you experienced

The documentation page for `FormControl` is essentially blank.

### Enter the URL of the topic with the problem

https://angular.dev/api/forms/FormControl

### Describe what you were looking for in the documentation

Something akin to https://v17.angular.io/api/forms/FormControl

**Comment by JoostK** [comment]
Yeah, it's a known issue with the docs extractor for the new docs site. Closing as duplicate of #56144.
