### ISSUE TITLE
Signals require previously-unnecessary type checking.

### ISSUE THREAD

**Issue by mcalmus** [angular/angular#58370]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Signals require previously-unnecessary type checking.

old:
```
@Input()
foo?: { bar: string };
```
template:
```
@if (foo) {
  {{ foo.bar }}
}
```
new:
```
readonly foo = input<{ bar: string }>();

@if (foo()) {
  {{ foo().bar }}
}
```
`error TS2532: Object is possibly 'undefined'.`

**Comment by JeanMeche** [comment]
Hi, this is a known issue and it's being discussed in #49161. 

You can currently work around this by using the `@let` template variable declaration. 

```
@let foo = this.foo; 
@if (foo) {
  {{ foo.bar }}
}
```
