### ISSUE TITLE
Component with  Encapsulation as ShadowDom leaking the styles to global styles when SSR is enabled

### ISSUE THREAD

**Issue by dushyanthb27** [angular/angular#58379]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

When SSR is enabled for the project and
When a component hierarchy is created such that CompA render CompB and CompB render CompC, 
And CompB has the encapsulation as ShadowDom, the CompB's styles are leaking out globally and all the elements getting the styles of CompB.

Component calling hierarchy:
![Image](https://github.com/user-attachments/assets/e1b0cfb5-2a68-4339-a312-4a8ee8bf1beb)

Render:
![Image](https://github.com/user-attachments/assets/d04893b6-5c84-45fb-b54f-c252c1e6c840)

### Please provide a link to a minimal reproduction of the bug

https://github.com/dushyanthb27/ViewEncapsulationIssue.git

### Please provide the environment you discovered this bug in (run `ng version`)

 Angular CLI: 18.2.10
Node: 20.11.0
Package Manager: npm 10.5.0
OS: win32 x64

Angular: undefined
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1802.10 (cli-only)
@angular-devkit/core         18.2.10 (cli-only)
@angular-devkit/schematics   18.2.10 (cli-only)
@schematics/angular          18.2.10 (cli-only)

**Comment by JeanMeche** [comment]
Can you double-check your github repo, it's currently the default CLI project, thank you.

**Comment by dushyanthb27** [comment]
Thank you @JeanMeche, added the missed code snippet.
You can observe the issue from the updated repo now.

**Comment by alan-agius4** [comment]
ShadowDOM is not supported when using SSR. 

See: https://github.com/angular/angular/issues/48746
