### ISSUE TITLE
Allow multiple `on interaction` triggers for the same deferred view

### ISSUE THREAD

**Issue by mwaibel-go** [angular/angular#58385]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

```
@defer(on interaction(addFooBtn); on interaction(removeFooBtn) { }

<button #addFooBtn> Add skill </button>
<button #removeFooBtn> Remove skill </button>
```

yields this error on the second `on interaction`:

> Duplicate "interaction" trigger is not allowed ngtsc(-995002)

```
@defer(on interaction(addFooBtn, removeFooBtn))
```

yields

> "interaction" trigger can only have zero or one parameters ngtsc(-995002)

The use case here is that there are two distinct actions (from a user’s perspective) that are very similar from the business logic’s point of view. Hence the actions are facilitated by the same component. I would like to toggle that component when any of the two buttons is pressed.

Another use case is toggling the same component from multiple parts of the UI (e.g. a button near the top of the screen and one near the bottom), so the user can press the one that’s easier to reach for them. Or one button that’s immediately visible on the page for recurring users and one link in an explanatory text that is read by new users.

### Proposed solution

Allow multiple interactive elements to toggle the same deferred view; either by allowing multiple triggers of the same type, or by allowing a list of toggling elements in the `on interaction` invocation.

### Alternatives considered

Workaround: Using a custom `when` condition that I manually set to `true` once either of the buttons is pressed.

**Comment by crisbeto** [comment]
We talked through it and decided that it's out of scope for `@defer`, because it's really meant for defer loading, rather than an advanced `@if`. As mentioned above, the same result can be achieved using the `when` trigger.
