### ISSUE TITLE
Helper for computed outputs from Signals

### ISSUE THREAD

**Issue by cwatzl** [angular/angular#58404]
### Which @angular/* package(s) are relevant/related to the feature request?

@angular/core

### Description

With Signal-based components, I often need an `output` emit a value when another `Signal`  changes its state to a particular value.

Currently I see to workarounds to do it: Either using `effect`, or RxJS interop.

The `effect` way: 

```typescript
readonly dialogOpen = signal(true);
readonly dialogClosed = output<void>();

constructor() {
  effect(() => {
    if (!this.dialogOpen()) {
      this.dialogClosed.emit();
    }
  });
}
```

The RxJS interop way:

```typescript
readonly dialogOpen = signal(true);
readonly dialogClosed = outputFromObservable(toObservable(this.dialogOpen).pipe(
  distinctUntilChanged(),
  filter((dialogOpen) => !dialogOpen),
  map(() => void 0)
));
```

The first version feels non-declarative, verbose and needlessly "side-effectful".  The second option is also verbose AND needs RxJS as dependency, but at least it's declarative and not resorting to a side effect.

I would very much like Signal-based APIs to support this use case more directly.

### Proposed solution

Provide a helper to create a "computed" output directly that works similar `computed`, e.g.:

```typescript
readonly dialogClosed = computedOutput(() => !this.dialogOpen());
```

The above solution would still be no complete replacement, as it would emit for all changes of the source Signal rather than filter for a specific condition. One way to deal with this would be to optionally pass a computed condition to the helper function, e.g.:

```typescript
readonly dialogClosed = computedOutput(() => 0 void, { emitWhen: () => !this.dialogOpen() });
```

### Alternatives considered

Provide documentation for a recommended way to cover this use case with existing means.

**Comment by JeanMeche** [comment]
Hi, please have a look at #57943, this has already been discussed in the past.

**Comment by cwatzl** [comment]
> Hi, please have a look at [#57943](https://github.com/angular/angular/issues/57943), this has already been discussed in the past.

@JeanMeche Missed those when searching for existing issues on this. Though after reading through all of them, I'm still not sure what the recommended pattern is :(
