### ISSUE TITLE
bug(matSort): matSort is leaking memory

### ISSUE THREAD

**Issue by tibi0010** [angular/angular#58407]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When destroying a table that uses matSort after user interacts with one or more mat-sort-header, detached elements and JS event listeners are left behind.

This behaviour can be reproduced with Angular version 17.3.0 and 19.0.0-next.9

![Image](https://github.com/user-attachments/assets/f22b2fb5-83ec-474c-a5a3-2a9174a0773f)

### Reproduction

StackBlitz link: https://stackblitz.com/edit/jjnak1-xedrsd?file=src%2Fexample%2Fsort-overview-example.html
Steps to reproduce:
1. Run application from stackblitz (link above)
2. Click on mat-sort-headers (sort data randomly)
3. Click toggle button twice
4. Repeat step 2-3 while observing DOM Node count and JS event listeners on Google Chrome Performance monitor
-> DOM Node count and JS event listeners are increasing

### Expected Behavior

DOM Nodes and JS event listeners are not increasing after each table creation and sort

### Actual Behavior

DOM nodes and JS event listeners increase each time the user interacts (sorts) with a table that has a mat sort.

### Environment

- Angular: 17.3.0
- CDK/Material: 17.3.6
- Browser(s): Google Chrome Version 130.0.6723.59 (Official Build) (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 22H2 (19045.5011)

**Comment by JeanMeche** [comment]
This is a known issue, let's continue tracking it with #54149.

**Comment by tibi0010** [comment]
After some investigation it looks like this issue is not the same as https://github.com/angular/angular/issues/54149 

I checked memory consumption with Firefox 132.0 (64-bit) and Chromium version 126.0.6478.234 and could not reproduce the leak.

Most likely this is a chromium issue: https://issues.chromium.org/issues/376777343

However, https://github.com/angular/angular/issues/54149  can be reproduced with the above mentioned Chromium and Firefox versions, so that one is still open.
