### ISSUE TITLE
Router: Parent component (one with @RouteConfig) needs to know...

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#5842]
what child route is activated.

The use case for this is something like having an icon change depending on the selected route.

```html
<img [src]="iconForSelectedRoute" />
<router-outlet></router-outlet>
```

Imagined API:

```html
<router-outlet (activate)="onActivate($event)"></router-outlet>
```

Workaround is to create a custom RouterOutlet (by extending the directive) and overriding 'activate', but I'd prefer not to do this long-term.

**Comment by nosachamos** [comment]
What about having a routeChanges oberservable provided by the Router instead?

I could see lots of use cases where components would want to know when routes change.d For example a breadcrumbs component, or changes in a header component. They might need to be alerted, but the routes might be defined in another component. An observable would cater for all of these needs, besides being a familiar concept for angular2 developers already.

**Comment by nosachamos** [comment]
Is it not enough to subscribe to the router, then get the route info by `router.recognize(url).then(instruction => ...);` ?  It seems to me that mechanism covers this use case as well.

**Comment by naomiblack** [comment]
This is internal issue b/26159296

**Comment by vsavkin** [comment]
This has been implemented in master. Closing this issue.
