### ISSUE TITLE
not enough guidance about how to use template fragments

### ISSUE THREAD

**Issue by YuliaKorobova** [angular/angular#58442]
### Describe the problem that you experienced

Here there's a description of how to create a template fragment, but there's no description how to **reference a template fragment with a template reference variable**. So I eventually read on stackoverflow, that I need to use `<ng-content [ngTemplateOutlet]=...>`, which wasn't working for me, and it took me some time to discover, that it should be ` <ng-content *ngTemplateOutlet=...> ` and also I should import `NgTemplateOutlet`. I would expect this instructions  to be in that doc, it would have saved me time.

### Enter the URL of the topic with the problem

https://angular.dev/guide/templates/ng-template#referencing-a-template-fragment-with-a-template-reference-variable

**Comment by JeevanMahesha** [comment]
@JeanMeche / @jessicajaniuk we can close this issue. we have changes are merged.
Thanks you
