### ISSUE TITLE
A signal value returned by its getter should be of a readonly type

### ISSUE THREAD

**Issue by pawel-twardziak** [angular/angular#58440]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Having a signal like this:
```TS
const config = signal({ options: { active: true, name: 'engine' } });
```
it is unfortunately possible to proceed this:
```TS
config().options.active = false
```
What a foully way.... 😆 
This change is happening outside the graph which means no consumers will be notified about the change.

Changing the signal value like this is an abuse that can cause some pretty unexpected code behavior, to say the least.
This also kinda violates the immutability pattern.

Correct me if I am wrong, but I reckon that each signal value should be readonly in a deep manner.

[Stackblitz playground](https://stackblitz.com/edit/stackblitz-starters-cdguyo)

### Proposed solution

I've digging around the code a bit and my proposal is quite simple. I am not sure about all possible consequences to the entire codebase.

```TS
export type SignalBaseGetter<T> = (() => ReadonlyDeep<T>) & {readonly [SIGNAL]: unknown};
```

```TS
export type ComputedGetter<T> = (() => ReadonlyDeep<T>) & {
  [SIGNAL]: ComputedNode<T>;
};
```

I've defined `ReadonlyDeep` type based on [type-fest](https://github.com/sindresorhus/type-fest)

Concluding, my commit is kinda ready - but yet again, I am totaly not sure about the impact.

Does it add up?

### Alternatives considered

Keep it as it is - each dev should be aware of how to set/update a signal value properly.

**Comment by alxhub** [comment]
We tried this, actually, and found that it doesn't really work in practice.

In principle it makes sense, but the consequence is that developers must structure all APIs and code that is receiving values from signals to accept readonly values. That is, if your value comes from `Signal<User>`, you can't just use it with a utility `function getRoles(user: User)`. That function would have to be written as `function getRoles(user: ReadonlyDeep<User>)`. This is an extremely burdensome and infectious requirement, and would severely limit the ability to start using signals in codebases not written in this style (which in our experience is all of them).

**Comment by pawel-twardziak** [comment]
Yea, that's true. Practise is the winner here. I see eye to eye with you @alxhub 👁 
Thank you for taking your time and explaining this issue 👍
