### ISSUE TITLE
External link is broken on docs for NG0100

### ISSUE THREAD

**Issue by vladboisa** [angular/angular#58459]
### Describe the problem that you experienced

At the bottom of [the page](https://angular.dev/errors/NG0100), there's a couple of links, and the first one is broken. It should either be updated or removed.

### Enter the URL of the topic with the problem

https://angular.dev/errors/NG0100

**Comment by JoostK** [comment]
The URL you linked does work for me, so I don't quite understand

**Comment by jnizet** [comment]
@JoostK the link that doesn't work is the link at the end of the page at https://angular.dev/errors/NG0100, labeled "Everything you need to know about the "ExpressionChangedAfterItHasBeenCheckedError" error'", and linking to `https://indepth.dev/posts/1001/everything-you-need-to-know-about-the-expressionchangedafterithasbeencheckederror-error/`.

**Comment by JoostK** [comment]
> [@JoostK](https://github.com/JoostK) the link that doesn't work is the link at the end of the page at https://angular.dev/errors/NG0100, labeled "Everything you need to know about the "ExpressionChangedAfterItHasBeenCheckedError" error'", and linking to `https://indepth.dev/posts/1001/everything-you-need-to-know-about-the-expressionchangedafterithasbeencheckederror-error/`.

Thanks, sorry I totally missed that 🤦‍♂ 

The link can be updated to https://angular.love/everything-you-need-to-know-about-the-expressionchangedafterithasbeencheckederror-error, probably due to https://angularindepth.com/posts/777/angular-in-depth-joins-forces-with-angular-love
