### ISSUE TITLE
String Pipe in @angular/common

### ISSUE THREAD

**Issue by ava-cassiopeia** [angular/angular#58454]
### Which @angular/* package(s) are relevant/related to the feature request?

common

### Description

For situations where I have a non-`string` value that I want to pass to a `string` input on an Angular component, I don't feel like I have a lot of good options to cleanly do that conversion _without_ binding to a method (eg. `.toString()` or `String()`).

Signals (or their `OnChanges` counterpart pre-Signals) work, but it feels silly to redeclare a version of a variable as a different type:

```typescript
export class ParentComponent {
  readonly id = input.required<number>();

  protected readonly idAsString = computed(() => this.id().toString());
}
```

String concatenation in the template also works, but again feels a little unclean and more difficult to read:

```html
<child-component [stringInput]="`${id()}`" />
<!-- or -->
<child-component stringInput="{{ id() }}" /> 
```

It feels like it would be much more readable and clear that there's a type conversion going on with something like:

```html
<child-component [stringInput]="id() | string" />
```

It's admittedly a sort of edge-case, so I defer to you Angular elders to decide whether this use-case makes sense, or if the approaches I outlined above are sufficient.

### Proposed solution

As mentioned above, a `StringPipe` pipe implementation that invokes `.toString()` on the provided value, living alongside all the other common pipes.

If you decide this is worth including, I'm happy to implement it :)

### Alternatives considered

I guess I sort of outlined the alternatives in the explanation, but I did consider and try:

- Signals (/ `OnChanges`)
- In-template inline string coercion via `{{ }}` or `${}`

These both work for my needs, but feel less readable than `value | string`.

**Comment by pkozlowski-opensource** [comment]
Thnx for the suggestion, but I don't think that a string conversion pipe adds enough value to the framework. 

To start with, there are existing mechanisms to convert types:
* you can use a transform on an input
* you can create a computed signal

Then, we need to realize that a pipe is not much more than calling functions in a template (!). In this particular case the overhead of having a pipe is _enormous_ - a pipe in the end would still call .toString() but now it needs to be generated in the code, instantiated at runtime etc.
