### ISSUE TITLE
jsonp is never finished

### ISSUE THREAD

**Issue by samio80** [angular/angular#5846]
jsonp.request(new Request(request))

The jsonbackend never calls finished function and there is not how to call it manually, so exception JSON_CALLBACK never invoked is thrown!
 
![screen shot 2015-12-11 at 23 08 01](https://cloud.githubusercontent.com/assets/4519631/11757052/97450484-a05e-11e5-9dcd-a0744f1478ba.png)

**Comment by samio80** [comment]
I see it's never called

  finished(data?: any) {
    // Don't leak connections
    this._finished = true;
    this._dom.removeConnection(this._id);
    if (this.readyState === ReadyState.Cancelled) return;
    this._responseData = data;
  }

**Comment by samio80** [comment]
I think the problem is that jsonp_backend onreadystatechanged is missing

**Comment by robwormald** [comment]
@samio80 can you post a plunker or code sample reproducing this? also note the callback name is JSONP_CALLBACK (not JSON_CALLBACK)

**Comment by samio80** [comment]
yes I see but I even not passing callback. I just simple copied and pasted the code from the examples

**Comment by samio80** [comment]
last beta version works for me

**Comment by robwormald** [comment]
:+1:
