### ISSUE TITLE
docs: 404 link for NG0100

### ISSUE THREAD

**Issue by vladboisa** [angular/angular#58469]
### Describe the problem that you experienced

On the [NG0100 url](https://angular.dev/errors/NG0100) link to the [source maps](https://developer.mozilla.org/docs/Tools/Debugger/How_to/Use_a_source_map) is broken

### Enter the URL of the topic with the problem

https://angular.dev/errors/NG0100

**Comment by vladboisa** [comment]
I would like to work on this problem!

**Comment by thePunderWoman** [comment]
The link is definitely not broken on the non-translated site. I'm not sure that there's much we can do here. I think there's a RU redirect that causes this.

**Comment by vladboisa** [comment]
> The link is definitely not broken on the non-translated site. I'm not sure that there's much we can do here. I think there's a RU redirect that causes this.

Yep, definitely, i'll close this issue, and will open on MDN ;)
