### ISSUE TITLE
CSS var inside max() optimised away to nothing

### ISSUE THREAD

**Issue by aaronclawrence** [angular/angular#58489]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes - was working in angular 14 and 15 at least.

### Description

We are using LESS. Using a CSS variable inside a max( ) expression somehow gets optimised away into nothing and does not work.

body {
  --test-var: 10px;
}

component.less:

:host {
  margin-left: max( 5px, var(--test_var));
}

With ng serve, the resulting CSS output is:

margin-left: max(5px)

### Please provide a link to a minimal reproduction of the bug

Not sure how to setup Stackblitz for LESS

### Please provide the exception or error you saw

CSS doesn't work. No error is logged anyway.

### Please provide the environment you discovered this bug in (run `ng version`)

Angular CLI: 17.3.11
Node: 20.17.0
Package Manager: npm 10.8.2
OS: win32 x64

Angular: 17.3.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.11
@angular-devkit/build-angular   17.3.11
@angular-devkit/core            17.3.11
@angular-devkit/schematics      17.3.11
@angular/cdk                    16.2.14
@angular/cli                    17.3.11
@schematics/angular             14.2.13
ng-packagr                      17.3.0
rxjs                            7.5.7
typescript                      5.2.2
zone.js                         0.14.10

**Comment by JoostK** [comment]
This appears to be a `less` bug: https://github.com/less/less.js/issues/4256
