### ISSUE TITLE
V19-RC.0 Imports is only valid on a component that is stand-alone

### ISSUE THREAD

**Issue by spock123** [angular/angular#58481]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

After flipping the switch to standalone as default, I am getting error messages in my editor in all components, complaining over the presence of the `imports` array in the component configuration object.

I am unsure where the source of the issue is - I suspect the @angular/language-service ?

I have tried installing the latest `@angular/language-service: "^19.0.0-rc.0"` but this has not helped.

Any ideas how to get rid of it?
I don't wanna start having to use `standalone:false` everwhere now :)

### Please provide the environment you discovered this bug in (run `ng version`)

Angular CLI: 19.0.0-rc.0
Node: 20.18.0
Package Manager: npm 10.8.2
OS: darwin arm64

Angular: 19.0.0-rc.0
... animations, build, cdk, cli, common, compiler, compiler-cli
... core, forms, language-service, localize, material
... material-date-fns-adapter, platform-browser
... platform-browser-dynamic, router, service-worker, ssr

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1900.0-rc.0
@angular-devkit/core         19.0.0-rc.0 (cli-only)
@angular-devkit/schematics   19.0.0-rc.0
@schematics/angular          19.0.0-rc.0
rxjs                         7.8.1
typescript                   5.6.3

### Anything else?

Apologies if there is an obvious solution - I have yet to figure it out.

**Comment by JeanMeche** [comment]
This is due to the language service issue. Please subscribe to angular/vscode-ng-language-service#2095
