### ISSUE TITLE
main route(/) should not be prerendered by default

### ISSUE THREAD

**Issue by smrb76** [angular/angular#58487]
### Which @angular/* package(s) are the source of the bug?

compiler-cli

### Is this a regression?

Yes

### Description

I've activated both pre-rendering and SSR simultaneously, but I don't want the homepage(/) to be pre-rendered. It should load with SSR.
Is there a specific configuration I've missed?

### Please provide the environment you discovered this bug in (run `ng version`)

@angular-devkit/build-angular   18.0.6
@angular-devkit/core            18.0.6
@angular-devkit/schematics      18.0.6
@angular/cli                    18.0.6
@angular/fire                   18.0.1
@angular/pwa                    18.0.5
@angular/ssr                    18.0.6
@schematics/angular             18.0.6
rxjs                            7.8.1
typescript                      5.4.4
zone.js                         0.14.7

### Anything else?

angular.json:
` "server": "projects/mobile/src/main.server.ts",
            "prerender": {
              "discoverRoutes": false,
              "routesFile": "./prerender-routes.txt"
            },
            "ssr": {
              "entry": "projects/mobile/server.ts"
            },`

prerender-routes.txt:
`/contact
/404
/about
`
prerendered-routes.json(after build):
`{
  "routes": [
    "/",
    "/404",
    "/about",
    "/contact"
  ]
}`

**Comment by JeanMeche** [comment]
Please have a looking at the hybrid rendering configuration that will be released in v19 later this month (It's already available in the RC).
