### ISSUE TITLE
Is it possible to define multiple entry point in angular.json?

### ISSUE THREAD

**Issue by i11010520** [angular/angular#58484]
### Description

Then I can directly build a browser extension  without webpack which is slow and resource killer.

### Proposed solution

As title.

### Alternatives considered

Or support custom-vite-config.

**Comment by JeanMeche** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).
