### ISSUE TITLE
Router feature withComponentInputBinding is overriding all component inputs even ones not passed to route data

### ISSUE THREAD

**Issue by ramyhhh** [angular/angular#58495]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

When I have an input signal in my component with initial value, that value will be overridden with `undefined` in runtime when component is activated by route (attached to view because of RouterOutlet).

I think the expected behaviour of withComponentInputBinding is to only bind inputs to value with provided  keys not just blindly set all inputs regardless of what the route has to offer.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/w7ssyx

### Please provide the exception or error you saw

No error message. When I visit the route defined the expected html should be `input: default value` however it is just `input: ` because input binder wrote `undefined` as input value.

### Please provide the environment you discovered this bug in (run `ng version`)

Angular 18
Node 18

I'm running my project via `nx` but this is irrelevant to this issue.

### Anything else?

Suggested solution:

In RoutedComponentInputBinder when setting inputs on line: `outlet.activatedComponentRef.setInput(templateName, data[templateName]);` check if `data` object has key `templateName` defined before calling `setInput`

https://github.com/angular/angular/blob/main/packages/router/src/directives/router_outlet.ts#L474

**Comment by JoostK** [comment]
This is working as designed, please see https://github.com/angular/angular/issues/52946
