### ISSUE TITLE
@for with dublicate entries and filter pipe kills browser

### ISSUE THREAD

**Issue by web-dave** [angular/angular#58509]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

I accidentally choose the wrong key for track in a @for, then my browser dies.

The problem get worse if the list of elements gets longer.

How to reproduce:

Go to the input.
Start typing (to filter the list)
Browser freeze.

If the list of user is about 150 ist freeze fo a few secunds.
if it is longer than 300 users, it gets worse.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-humfi8

### Please provide the exception or error you saw

`NG0955`

Browser freeze for few seconds or stops working at all

### Please provide the environment you discovered this bug in (run `ng version`)

Angular CLI: 18.2.10
Node: 18.19.1
Package Manager: npm 10.2.4
OS: darwin arm64

Angular: 18.2.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.10
@angular-devkit/build-angular   18.2.10
@angular-devkit/core            18.2.10
@angular-devkit/schematics      18.2.10
@angular/cli                    18.2.10
@schematics/angular             18.2.10
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.10

**Comment by JeanMeche** [comment]
Hi Dave  ! 

The code is firing `NG0955` because of the duplicate keys. The tracking expression shouldn't be returning duplicate keys.

**Comment by e-oz** [comment]
But it should not kill the page either.

**Comment by pkozlowski-opensource** [comment]
> But it should not freeze.

Does it freeze, though? It doesn't seem to be happening in the linked stackblitz.

**Comment by JeanMeche** [comment]
I'm seeing heavy CPU load for several seconds, we schedule a lot of ticks.

**Comment by e-oz** [comment]
> Does it freeze, though? It doesn't seem to be happening in the linked stackblitz.

Nice computer you have, sir 🧐

Try CPU throttling, 6x slowdown, and quickly type 5-10 symbols. On MBP Pro (M1) it first makes the app iframe dead, and soon the whole page is frozen, and even the browser itself becomes unresponsive.

**Comment by JoostK** [comment]
The problem originates here:

https://github.com/angular/angular/blob/c22b5accdd083f3bdc4141431cece196f0e33112/packages/core/src/render3/list_reconciliation.ts#L432

That assertion fails when detaching prior views, in the presence of duplicate keys. The `value` however is an `LView`, which chokes the browser when stringifying.

/cc @pkozlowski-opensource

**Comment by JoostK** [comment]
Note that it only freezes once entering something into the filter input, as that will start to detach views (with duplicate keys)

**Comment by pkozlowski-opensource** [comment]
Oh, this is interesting, thnx for digging into it @JoostK !

**Comment by web-dave** [comment]
@pkozlowski-opensource you can make it die if you change the number of user in the list `users.ts`
at the moment this is 150 users, and i tried 1k => died
