### ISSUE TITLE
官网崩溃

### ISSUE THREAD

**Issue by xingyan95** [angular/angular#58505]
### Describe the problem that you experienced

![Image](https://github.com/user-attachments/assets/d83f2c7c-183f-4a46-9753-1816ffc817a4)

**Comment by pkozlowski-opensource** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
