### ISSUE TITLE
No error occurs if required input has no value.

### ISSUE THREAD

**Issue by reuse-ay** [angular/angular#58519]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

This may be a feature request.

There is a directive with two required input.
```
import { Directive, Input, numberAttribute } from '@angular/core';

@Directive({
  selector: '[appAbc]',
  standalone: true,
})
export class AbcDirective {
  @Input({ required: true }) strInput!: string;

  @Input({ required: true, transform: numberAttribute }) numInput!: number;
}

```

There is a template using the directive.
```
<h1>Hello from {{ name }}!</h1>
    <a target="_blank" href="https://angular.dev/overview">
      Learn more about Angular
    </a>

    <div appAbc strInput numInput>
```

The template doesn't have errors. 

This looks strange for me. On the div element in template, the two attributes corresponding to the inputs doesn't have values, but there is no error. In fact I get an empty string or NaN, which is not what I would expect.

In my opinion, required inputs should throw an error if values are not set, but this is not necessary for boolean inputs.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-fbym5w?file=src%2Fmain.ts,src%2Fabc.directive.tshttps://stackblitz.com/edit/stackblitz-starters-fbym5w?file=src%2Fmain.ts,src%2Fabc.directive.ts

**Comment by JoostK** [comment]
This is working as expected; having the attribute present without value will bind an empty string into the input, which is an allowed value according to the types of the inputs/transform function.
