### ISSUE TITLE
Using for on a label element.

### ISSUE THREAD

**Issue by jamcoupe** [angular/angular#5851]
I am trying to do the following:

```
<label [for]="someProperty">
    <input type="checkbox" [id]="someProperty" />
</label>
```

It is throwing an error `Can't bind to 'for' since it isn't a known native property`

However `for` is a native property of `label` is it not?

**Comment by PascalPrecht** [comment]
@jamcoupe Angular 2 always binds to DOM/Component properties, not attributes. `<label>` doesn't have a property `for`, only an attribute `for`. This this use case you need to use the following syntax:

```
<label [attr.for]="someProperty"></label>
```
