### ISSUE TITLE
Rendering template fails on Safari

### ISSUE THREAD

**Issue by RomanKisilenko** [angular/angular#5852]
Angular 2 fails to render template on Safari if it contains more than plain text. E.g. for template

```<div class="test">Test</div>```

I'm getting following exception:

```EXCEPTION: TypeError: undefined is not a function (evaluating 'attrName.toLowerCase().startsWith('data-')')```

Sample code to reproduce the bug is attached.

[safari-bug.zip](https://github.com/angular/angular/files/60180/safari-bug.zip)

**Comment by pkozlowski-opensource** [comment]
What version of Safari? I presume that this is due to the lack of https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith method that was introduced only in Safari 9.

You need to include a polyfill for earlier versions, we are using [es-shim](https://www.npmjs.com/package/es6-shim) as described in https://angular.io/docs/ts/latest/quickstart.html ("Appendix: Browser ES6 support" section)

**Comment by pkozlowski-opensource** [comment]
BTW: sending zip files with a reproduction scenario won't help us. Many people, including me, wouldn't download / unzip random files from the internet. If you want to share a reproduce scenario put it on-line, ideally using tools like plunker, jsbin or similar.

**Comment by RomanKisilenko** [comment]
Thank you, it is indeed due to es6-shim import missing.

Btw, is there any documentation on how to import angular2-polifills correctly from typescript source? I'm getting a bunch of module not found errors when I try to 
```import 'angular2/bundles/angular2-polyfills';```

**Comment by pkozlowski-opensource** [comment]
> Btw, is there any documentation on how to import angular2-polifills correctly from typescript source? I'm getting a bunch of module not found errors when I try to 
import 'angular2/bundles/angular2-polyfills';

You should _not_ try to import this file. It is meant to be included in a `script` tag. This file contains code that should be executed as soon as possible without any module loader. Pulling it through the module loader might interfere with the code in the `angular2-polifills` bundle (mostly zone.js)
