### ISSUE TITLE
reflectComponentType not detect Inputs and Outputs Defined with output() and model() Functions

### ISSUE THREAD

**Issue by AsmisAlan** [angular/angular#58555]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Version: 17.3.12

Description:

In Angular version 17.3.12, the reflectComponentType function fails to recognize component inputs and outputs defined using the input(), output(), and model() functions. 

```ts
// component example
import { Component, input, output, model, EventEmitter } from '@angular/core';

@Component({
  standalone: true,
  template: `
    <p>inputSignalExample: {{ inputSignalExample() }}</p>
    <p>modelExample: {{ modelExample() }}</p>
    <button (click)="onClick()">Click</button>
  `,
})
export class MyComponent {
  inputSignalExample = input<string>();
  modelExample = model<string>();
  @Output() outputWithDecoratorExample = new EventEmitter<string>();
  outputSignalExample = output<string>();

  onClick() {
    this.outputWithDecoratorExample.emit('emit: outputWithDecoratorExample');
    this.outputSignalExample.emit('emit: outputSignalExample');
  }
}
```

Reflection results 
``` ts 
const componentType = reflectComponentType(MyComponent);

const componentInputProperties = componentType.inputs.map((x) => x.templateName);

console.log(componentInputProperties); 
// Expected: ['inputSignalExample', 'modelExample']
// Result: ['inputSignalExample']

const componentOutputProperties = componentType.outputs.map((x) => x.templateName);
console.log(componentOutputProperties);
// Expected: ['outputWithDecoratorExample', 'outputSignalExample', 'modelExample']
// Result: ['outputWithDecoratorExample']
```

### Please provide the exception or error you saw

In Angular version 17.3.12, the reflectComponentType function fails to recognize component inputs and outputs defined using the input(), output(), and model() functions. 

### Please provide the environment you discovered this bug in (run `ng version`)

Angular CLI: 17.3.0
Node: 20.16.0
Package Manager: yarn 1.22.10
OS: Windows 11 x64

Angular: 17.3.0
rxjs: 7.8.0
typescript: 5.2.2
zone.js: 0.14.7

**Comment by JeanMeche** [comment]
This works correctly in v18. Please update to the latest version as v17 is now in LTS and, per [our support policy](https://angular.dev/reference/releases#lts-fixes) ,only recieves security fixes.
