### ISSUE TITLE
NG0203 from newly created angular project

### ISSUE THREAD

**Issue by mwannenmacher** [angular/angular#58577]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

I 've started a new Angular Project with `ng create Test`. 
After running this project without modifying anything I got the following error message in the browser console:

```console
Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.dev/errors/NG0203
```

![Image](https://github.com/user-attachments/assets/db98ff16-96cf-4163-a5be-e648d9bc483c)

After some tests, I removed the RouterOutlet Import from the `app.component.ts` and removed the `router-outlet` tag from the template and the error was gone!

### Please provide the exception or error you saw

```true
rror: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.dev/errors/NG0203
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.2.11
Node: 20.14.0
Package Manager: npm 10.9.0
OS: darwin arm64

Angular: 18.2.11
... animations, cli, common, compiler, compiler-cli, core
... platform-browser, platform-browser-dynamic

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.11
@angular-devkit/build-angular   18.2.11
@angular-devkit/core            18.2.11
@angular-devkit/schematics      18.2.11 (cli-only)
@angular/forms                  18.2.10
@angular/router                 18.2.10
@schematics/angular             18.2.11
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10
```

**Comment by JeanMeche** [comment]
Hi, could you provide a minimal reprodcution example so we can have a look at it ? Thank you.

**Comment by JeanMeche** [comment]
Without any reproduction, this isn't actionable to us.
