### ISSUE TITLE
How to initialize routing with root module and where is documentation?

### ISSUE THREAD

**Issue by Neutrino-Sunset** [angular/angular#58583]
### Describe the problem that you experienced

With the change to using standalone components now being the default, what is the correct way to initialize routing when using a root module?

Where is the documentation for this? I don't find any current documentation relating to the use of routing with modules. And if there is no documentation, then why on earth not?

### Enter the URL of the topic with the problem

https://angular.dev/guide/routing/common-router-tasks

### Describe what you were looking for in the documentation

A description of how to use routing with modules.

### Describe the actions that led you to experience the problem

Needing to add routing to an application with a root NgModule.

### Describe what you want to experience that would fix the problem

A description of how to use routing with modules.

### If this problem caused an exception or error, please paste it here

```true

```

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true

```

### Provide any additional information here in as much as detail as you can

```true

```

**Comment by JeanMeche** [comment]
You can use `provideRouter` the same way in an `NgModule`

```
@NgModule({
  // provide Router with routes
  providers: [provideRouter(routes)],
 /* ... */
})
export class AppModule {}
```

Knowing that we are advocating for standalone, I'm not sure it worth mentionning specifically a router setup for NgModule. There are already plenty of examples outside of the official doc.

**Comment by JeanMeche** [comment]
`ng new --no-routing` will create an app without routing. 
Any boolean option in https://angular.dev/cli/new can be prefixed with `--no-`.
