### ISSUE TITLE
Broken Docs Link to Property Binding

### ISSUE THREAD

**Issue by ValentinTyanov** [angular/angular#58588]
### Describe the problem that you experienced

Clicking a link from https://next.angular.dev/tutorials/learn-angular/6-property-binding takes you to broken URL.

### Enter the URL of the topic with the problem

https://next.angular.dev/tutorials/learn-angular/6-property-binding#:~:text=Property%20binding%20is%20one%20of%20Angular%27s%20many%20powerful%20features.%20If%20you%27d%20like%20to%20learn%20more%20checkout%20the%20Angular%20documentation.

### Add a screenshot if that helps illustrate the problem
![Image](https://github.com/user-attachments/assets/e1fe5c39-86cc-42ba-a5bd-18a8ae10e539)

### If this problem caused an exception or error, please paste it here

```true

```

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true

```

### Provide any additional information here in as much as detail as you can

```true

```

**Comment by JeanMeche** [comment]
Hi can you check this is not a caching issue on your side, I didn't find any broken on that page.

**Comment by ValentinTyanov** [comment]
Hey, did ctrl+f5 after ticking Disable cache in dev tools. Issue remains the same. The link under "Property binding is one of Angular's many powerful features." points to non-existing page.

This is the page link. https://next.angular.dev/guide/templates/guide/templates/binding

It is not an issue for me, just wanted to let you know.

**Comment by JeanMeche** [comment]
Oh I see, the issue only occurs when opening the link in a new tab.
