### ISSUE TITLE
Review PACKAGE_ROOT_URL and APP_BASE_HREF injectables

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#5860]
Yesterday @jeffbcross removed `AppRootUrl` (via in https://github.com/angular/angular/commit/ed2c25eb2f280b7040382b402544b56c24b3112f).

That made me realized that we still have two similar APIs in our public API surface:
- [APP_BASE_HREF](https://github.com/angular/angular/blob/4e5cd1e558503aec87dd95e59337b31f261c941f/modules/angular2/src/router/location_strategy.ts#L32-L61)
- [PACKAGE_ROOT_URL](https://github.com/angular/angular/blob/db096a5e22d229db2a3aa2224040c5fa2d5c8e63/modules/angular2/src/core/application_tokens.ts#L63-L67)

We should review them and check if they couldn't be merged into one. If not then we should clearly document when and how to use them.

// @jeffbcross (for `AppRootUrl`), @tbosch (for compiler), @matsko (for PACKAGE_ROOT_URL), @btford (for APP_BASE_HREF and router), @wardbell (for docs)

**Comment by vicb** [comment]
obsolete
