### ISSUE TITLE
Async form reset is not reflecting pristine state change across angular components

### ISSUE THREAD

**Issue by AdrLeon** [angular/angular#58612]
### Which @angular/* package(s) are the source of the bug?

forms, core

### Is this a regression?

No

### Description

In an Angular application, the parent component contains a form and a button that is enabled only when the form is in a pristine state. This form is passed to a child component, which holds the input fields that modify the form’s state.

When the button in the parent component is clicked, it triggers an asynchronous function that takes about a second to complete and then performs a reset on the form. While the form state itself correctly resets to pristine, the button in the parent component does not reflect this change and remains active. The button should become disabled after the reset since the form has returned to a pristine state.

**Steps to Reproduce:**

1. Open the minimal reproduction of the bug.
2. Modify one of the fields.
3. Click the button.

**Current Result:**

The form’s pristine state updates correctly, but the button in the parent component remains active, not reflecting the form’s pristine status.

**Expected Result:**

After the reset, the form should return to a pristine state, and the button in the parent component should become disabled.

**Attached video**

https://github.com/user-attachments/assets/4c57b69b-9c49-4d05-a859-93c2039fb12a

### Please provide a link to a minimal reproduction of the bug

https://github.com/MADSENSE/AngularChangeDetection

### Please provide the exception or error you saw

```true

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.2.11
Node: 20.9.0
Package Manager: npm 10.7.0
OS: win32 x64

Angular: 18.2.11
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.11
@angular-devkit/build-angular   18.2.11
@angular-devkit/core            18.2.11
@angular-devkit/schematics      18.2.11
@schematics/angular             18.2.11
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.10
```

**Comment by JoostK** [comment]
This is working as expected. `ParentComponent` is marked `OnPush`, so any internal state changes won't be observed unless the change detector is marked as dirty. Injecting `ChangeDetectorRef` and calling its `markForCheck` method after the asynchronous activity has completed makes will result in running change detection as necessary to reevaluate the button's disabled state. The inputs are not subject to change detection as form control's are synced imperatively to the DOM by the various `ControlValueAccessor` implementations.
