### ISSUE TITLE
docs: add a section for community resources in adev

### ISSUE THREAD

**Issue by vimulatus** [angular/angular#58622]
### Describe the problem that you experienced

Angular is generally a difficult language to get started with, and although the community has a lot of great resources, finding these resources can sometimes be a challenge in of itself, especially for people new to angular and to coding in general. 
I think adding a section for community resources, something like awesome angular, can help foster the community even more.

### If this problem caused an exception or error, please paste it here

```true

```

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true

```

### Provide any additional information here in as much as detail as you can

```true

```

**Comment by JeanMeche** [comment]
Historically we did have this on https://v17.angular.io/resources, but decided to drop it on the new doc site. The page wasn't really curated and the team didn't want to spend its valuable time on this.
