### ISSUE TITLE
Resource state preservation

### ISSUE THREAD

**Issue by antimprisacaru** [angular/angular#58632]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Currently, a mechanism to persist the state through new loads is lacking. Potential use cases for this are for example on table pages, where one would want the state to persist in between the loading of a new page, if the table is paginated.

### Proposed solution

I think a good approach could be the following:

- adding a flag to determine the desired behavior (e.g., state persistence or nah);
- add an update fn, akin to how [scan](https://rxjs.dev/api/operators/scan) from RxJs (or well, reduce).

### Alternatives considered

N/A.

**Comment by JeanMeche** [comment]
Hi, we already have this request at #58602. Let's continue tracking it overthere.
