### ISSUE TITLE
@ViewChildren undefined when used in an attribute directive

### ISSUE THREAD

**Issue by szeinedd-nrel** [angular/angular#58642]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

Using `@ViewChildren` in an attribute directive to query for child components of an element using said directive results in the `@ViewChildren` property remaining undefined.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-4cfd6x?file=src%2Fsubject.directive.ts

### Please provide the exception or error you saw

```true
The bug does not directly cause an error. An error can be caused by attempting to interact with the undefined property if you assume it to have been set.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular: 18.2.10
```

**Comment by JeanMeche** [comment]
You're looking for `ContentChildren` not `ViewChildren`.

**Comment by e-oz** [comment]
You said that it is a regression. In what version did you encounter other behavior?

**Comment by JeanMeche** [comment]
Directives don't have templates, there are no children to query. 

The SO issue you're mentionning is pre-Ivy so probably doesn't apply anymore.
