### ISSUE TITLE
Discrepancy in TypeScript Inference Example in Angular Reactive Forms Documentation

### ISSUE THREAD

**Issue by Naresh2028** [angular/angular#58645]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

While following the Angular guide on reactive forms, I noticed a discrepancy related to typed controls and TypeScript inference![Image](https://github.com/user-attachments/assets/9cb335e5-72b1-40e7-8dd9-982537b08e25)
![Image](https://github.com/user-attachments/assets/62552d57-7728-4a09-a16d-7a41bf0d100b)
![Image](https://github.com/user-attachments/assets/8149e5a9-fb9e-46f2-8857-734b686f1710)
![Image](https://github.com/user-attachments/assets/b6f47040-e84c-417f-9f16-28ee4bd3181a)
. The documentation suggests the following:

"It is possible to specify the type, instead of relying on inference. Consider a control that is initialized to null. Because the initial value is null, TypeScript will infer FormControl<null>, which is narrower than we want."

typescript
Copy code
const email = new FormControl(null);
email.setValue('angularrox@gmail.com'); // Error!
However, in my local environment, setting a value of any data type to email does not raise an error unless I explicitly declare the type as FormControl<null>, as shown below:

typescript
Copy code
const email = new FormControl<null>(null);
email.setValue('angularrox@gmail.com'); // Argument of type '"angularrox@gmail.com"' is not assignable to parameter of type 'null'.ts(2345)
Steps to Reproduce:

Initialize a form control with new FormControl(null).
Set a string value to the form control, e.g., email.setValue('angularrox@gmail.com').
Observe that no TypeScript error is raised.
Explicitly define the type as FormControl<null> and re-attempt setting a value.
Expected Behavior: An error should occur when setting a value that does not match the inferred type, as described in the guide.

Screenshots: (Attach screenshots here if relevant)

This appears to be either a documentation error or an inconsistency in type inference handling that may need clarification. Thank you for reviewing this!

### Please provide the exception or error you saw

```true

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.0.1
Node: 18.20.4
Package Manager: npm 10.7.0
OS: win32 x64
```

**Comment by JeanMeche** [comment]
This is likely due to your typescript config. Check that you  either have `strict: true` or `strictNullChecks: true`. Without it the compiler won't throw.

**Comment by Naresh2028** [comment]
Dear Matthieu,

Thanks for the feedback.

Best Regards,
Naresh
