### ISSUE TITLE
Model signal type incorrectness

### ISSUE THREAD

**Issue by 0xdfc** [angular/angular#58653]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

When passing a complex type, such as a FormControl, to a component that accepts a model signal `<app-example [(formGroup)]> </app-example>` the Angular ngtsc errors out with the following message `cannot use a non-signal variable 'formGroup' in a two-way binding expression. Template variables are read-only.ngtsc(-99)`. Note that the variable stems from a loop running over a computed signal of controls.  For example:

```
@for(control of controls(); track control) {
    <app-example [(control)]> </app-example>
}
```

However, a way to work around this is to wrap the array stemming from the controls signal, making each element of type `{ [string]: FormGroup }`, and then you can pass the control as follows `<app-example [(control.formGroup)]> </app-example>`. For example:

```
@for(control of controls(); track control) {
    <app-example [(control.formGroup)]> </app-example>
}
```

### Please provide a link to a minimal reproduction of the bug

[stackblitz](https://stackblitz.com/edit/stackblitz-starters-dqiu3c?file=src%2Fapp.component.html)

### Please provide the exception or error you saw

```true
cannot use a non-signal variable 'formGroup' in a two-way binding expression. Template variables are read-only.ngtsc(-99)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.2.11
Node: 22.10.0
Package Manager: npm 10.9.0
OS: linux arm64

Angular: 18.2.11
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.11
@angular-devkit/build-angular   18.2.11
@angular-devkit/core            18.2.11
@angular-devkit/schematics      18.2.11
@angular/cdk                    18.2.13
@angular/material               18.2.13
@schematics/angular             18.2.11
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10
```

### Anything else?

It would be great if the error case was unified as the logic does the same thing just in a slightly different format however one errors out and the other doesn't.

**Comment by jnizet** [comment]
The error looks correct to me. `[(foo)]="bar"` is two way binding. It reads the calue of bar and passes it to the child component's `foo` model input, and when the child `foo` model changes, it must do `bar = newValue`. So `bar` must be something that can be assigned a value. It's not the case in your stackblitz since it's a local template variable defined by the for loop. 
O the contrary, `control.formGroup = newValue` is valid: it changes the `formGroup` property of the `control` object.

**Comment by 0xdfc** [comment]
🤦  yep that makes complete sense, I didn't think of that way, the error message was a bit foreign. Thank you.
