### ISSUE TITLE
Support two-way binding to nested signal

### ISSUE THREAD

**Issue by marklagendijk** [angular/angular#58685]
### Description

Nested signals are a useful tool, as @alxhub explains in [this video](https://www.youtube.com/watch?v=aKxcIQMWSNU).

A simple example looks like this:
```ts
name = input('');
myName = computed(() => signal(this.name()));
```

If we try to use such signal with the 'bananas in a box'-syntax for two-way binding to a `model` we get an error:
```html
<app-some-component [(name)]="myName()"></app-some-component>
```
```
 [ERROR] NG5002: Unsupported expression in a two-way binding [plugin angular-compiler
```

This forces us to use the explicit syntax:
```html
<app-some-component [name]="myName()()" (name)="myName().set($event)></app-some-component>
```
This is both unwieldy and not intuitive: most developers don't even know that the "bananas-in-a-box" are syntactical sugar for the 2nd notation.

### Proposed solution

Support this syntax.

### Alternatives considered

Flattening of signals.
When you return a Promise inside the `then` of a Promise it will be automatically "unwrapped" or "flattened".

Nested signals allow for nicely reactive solutions for certain problems. But nobody likes `()()`. It would be nice to have a simple way of flattening such signals.

**Comment by json-derulo** [comment]
Did you try removing the parentheses?

```html
<app-some-component [(name)]="myName" />
```

**Comment by marklagendijk** [comment]
@json-derulo yes that doesn't work because this is a nested signal: the outer computed signal contains an inner writable signal.
Watch the linked video for an explanation of the concept.

**Comment by marklagendijk** [comment]
The last thing I did before reading your reply was watching a video about `linkedSignal`. I only found out about it 20 minutes ago.

Yes, to me it seems that `linkedSignal` is an better alternative for the pattern I was describing. 
I'll close this issue.
