### ISSUE TITLE
Animations of height when changed input signal outside component

### ISSUE THREAD

**Issue by Argentum4k** [angular/angular#58701]
### Which @angular/* package(s) are the source of the bug?

animations, Don't known / other

### Is this a regression?

No

### Description

There's a different behavior in animations of component, when i change the input signal inside the component, and outside of it.
I made an accordion component (angular18) with lazy loading of it's body content and smooth animation of opening and closing. So it works pretty well when i toggle it from inside (by clicking on header), but when i toggle it from outside - it doesn't open smoothly (but closes smoothly).
Other animations on squares, added for test, works fine, problem only with height animation.

We found a solution: if we use  [@content]="($isOpen | async) ? ... where  $isOpen = toObservable(this.isOpen); - it works fine, so i think there's a bug with signals.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-rjsmkv

### Please provide the exception or error you saw

```true
accordion opens immediately after transition time, not smoothly.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true

```

**Comment by JeanMeche** [comment]
Your repro is a perfect example of why the timing of `effect` is important in components and why it should happen before change detection. In your case the `effect` is hidden the implementation of `toObserbable()`. 

In v19, `effect`s created in component will be executed ahead of them running change detection which fixes the issue you're observing.
