### ISSUE TITLE
Resource API: hasValue confusing naming

### ISSUE THREAD

**Issue by dexster** [angular/angular#58705]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

With the new NG19 experimental Resource API, I was using hasValue() to hide or show UI elements as my assumption of this method was that it would be true only if a non-null or not undefined value was returned.  

I see that it is more of a wrapper for success statuses:
 
```
return (
      this.status() === ResourceStatus.Resolved ||
      this.status() === ResourceStatus.Local ||
      this.status() === ResourceStatus.Reloading
    );
```
This caused some amount of time and frustration debugging my responses until I realised this.

Should this naming possibly be changed to reflect that it is just an indication of certain statuses and not actual values returned, something like "responseReceived" (yes, this name is not ideal either)?

### Please provide the exception or error you saw

```true

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true

```

**Comment by JeanMeche** [comment]
`hasValue` is meant to indicate that your resource has a value whatever it is and not that it's a truthy value. It helps distinguish `undefined` as value from `undefined` as the value isn't loaded yet. 

If you look at the signature its signature : 

```
hasValue(): this is WritableResource<T> & {value: WritableSignal<T>}; 
```

You can see that the method is actually a type guard that narrows down the type of `value` from `T|undefined` to `T`. 

In your case your resource is defined as `Resource<{ /* whatever*/} | undefined` which means that `undefined` is one the valid value of your resource.
