### ISSUE TITLE
Proposal: Add Template-Scoped Singleton Option for Pipes

### ISSUE THREAD

**Issue by cesco69** [angular/angular#58717]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

When using a pipe multiple times in the HTML template of a component, a new pipe instance is created for each occurrence. Here’s an example to illustrate this behavior:

```ts
import { Component, PipeTransform, Pipe } from '@angular/core';
import { bootstrapApplication } from '@angular/platform-browser';

@Pipe({
  name: 'myPipe',
  standalone: true,
})
export class MyPipe implements PipeTransform {
  constructor() {
    console.log('MyPipe');
  }

  transform(value: string) {
    return value.toLowerCase();
  }
}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [MyPipe],
  template: `
    {{ 'Hello' | myPipe }}
    {{ 'Hello' | myPipe }}
    {{ 'Hello' | myPipe }}
    {{ 'Hello' | myPipe }}
  `,
})
export class App {}

bootstrapApplication(App);
```

The console output for this example is:
```
MyPipe
MyPipe
MyPipe
MyPipe
```

This behavior has a performance impact when the pipe involves initialization logic or injects services. For example, consider a pipe that performs expensive computations during its construction.

### Proposed solution

Introduce an option in the `@Pipe` decorator to specify that the pipe should be treated as a **singleton** within the template. This could work like this:

```ts
import { Component, PipeTransform, Pipe } from '@angular/core';
import { bootstrapApplication } from '@angular/platform-browser';

@Pipe({
  name: 'myPipe',
  standalone: true,
  singleton: true // <---- Ensures only one instance per template
})
export class MyPipe implements PipeTransform {
  constructor() {
    console.log('MyPipe');
  }

  transform(value: string) {
    return value.toLowerCase();
  }
}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [MyPipe],
  template: `
    {{ 'Hello' | myPipe }}
    {{ 'Hello' | myPipe }}
    {{ 'Hello' | myPipe }}
    {{ 'Hello' | myPipe }}
  `,
})
export class App {}

bootstrapApplication(App);
```

With this change, the console output would become:
```
MyPipe
```

This ensures only one instance of the pipe is created per template, reducing unnecessary overhead while maintaining the current behavior for pipes where multiple instances are desired.

### Alternatives considered

```ts
@Pipe({
  name: 'myPipe',
  standalone: true,
  provideInTemplate: true // <---- Ensures only one instance per template
})
```

**Comment by pkozlowski-opensource** [comment]
In your particular example a pipe is no different from a regular function call (a function that could be exposed through a DI system if it needs some initialization logic). Generally speaking non-pure pipes are really just a fancy syntax for calling functions and from this perspective we don't want to add more complexity to the pipes system (and Angular in general)

**Comment by cesco69** [comment]
ok, thanks! now I understand. There is no way to use the same instance of the pipe?

**Comment by JeanMeche** [comment]
No, there is isn't and as Pawel said, they are glorified functions with memoisation. You could replace them is a function an take carte of the memoisation yourself.

**Comment by pkozlowski-opensource** [comment]
I _really_ do think that pipes add more confusion than value in this particular use-case. If you've got particular caching needs it is much easier to code and reason about a custom, rolled out function (bonus: only using public APIs):

```typescript
function cachingTransformFactory() {
  const cache = new Map<string, string>();
  return function transform(value: string) {
    if (!cache.has(value)) {
      console.log('Transforming', value);
      cache.set(value, value.toLowerCase());
    }
    return cache.get(value);
  };
}

const MyTransform = new InjectionToken<(value: string) => string>(
  'myTransform'
);

@Component({
  selector: 'app-root',
  standalone: true,
  providers: [{ provide: MyTransform, useFactory: cachingTransformFactory }],
  template: `
    {{ myTransform(value) }}
    {{ myTransform(value) }}
    {{ myTransform(value) }}
    {{ myTransform(value) }}
  `,
})
export class App {
  myTransform = inject(MyTransform);
  value = 'Hello';
}
```


https://stackblitz.com/edit/stackblitz-starters-rs9uu2?file=src%2Fmain.ts

**Comment by JeanMeche** [comment]
We're going to close as we're not looking to change how to pipes work and there are acceptable workarounds.
