### ISSUE TITLE
Resetting Angular Signals to Default Values

### ISSUE THREAD

**Issue by DevHanza** [angular/angular#58715]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Currently, Angular Signals do not support a built-in method to reset a signal to its default value. This lack of functionality can complicate state management in applications where signals may need to revert to their original state after changes. Developers are left to implement custom solutions, which can lead to inconsistencies and increased complexity in the codebase.

### Proposed solution

Could you implement a built-in method for Angular Signals that allows developers to reset a signal to its default value? This method could be named `reset()` and restore the signal to its value when first initialized.

Example Usage:

```
x = signal(5); // x = 5

x.set(999); // x = 999

x.reset(); // x = 5
```

### Alternatives considered

**Manual Default Tracking:** 
Developers currently have to manually track the default values and reset the signals accordingly, which can lead to repetitive code and increased maintenance overhead.

**Wrapper Services:** 
Some teams may create wrapper services to encapsulate the logic of resetting signals, but this adds unnecessary complexity and reduces the straightforwardness of using signals.

**Custom Reset Functions:** 
Writing individual reset functions for each signal can be a temporary workaround, but it is not scalable for larger applications and can lead to inconsistencies.

**Comment by JeanMeche** [comment]
Having a default default value means that every signal would keep a reference to an object it might not use anymore hence increasing the memory footprint. 

As you said this is mostly for state management and an abstraction for those is often welcome.
