### ISSUE TITLE
Cannot use UpdateValue on a Control when constructed via ControlGroup

### ISSUE THREAD

**Issue by plopinou** [angular/angular#5871]
This doesn't work :
```typescript
import {Control, ControlGroup} from 'angular2/angular2';

let group = new ControlGroup({
  'name': new Control('john')
});
group.controls['name'].updateValue('jack');
// error TS2339: Property 'updateValue' does not exist on type 'AbstractControl'.
```
but this does :
```typescript
import {Control} from 'angular2/angular2';

let name = new Control('john');
name.updateValue('jack');
```
The problem comes from /src/common/forms/model.ts where ControlGroup extends AbstractControl.
Because I'm still learning typescript, I first opened a issue on its github, believing this was a typescript related issue : https://github.com/Microsoft/TypeScript/issues/6085
But it seems that it's in fact a normal behavior.
So the correction may be to simply add a generic type to ControlGroup like that :
```typescript
export class ControlGroup<T extends AbstractControl> extends AbstractControl {
```

This may break something else so that's just a guess from a beginner :)

**Comment by vicb** [comment]
Your issue is that `group.controls` is a `{[key: string]: AbstractControl}`.

You would need to cast the `AbstractControl` to a Control: `(<Control>group.controls['name']).updateValue(...);`

**Comment by gonzofish** [comment]
Thank you @vicb for clarification on this. That's a nice, quick fix.

**Comment by plopinou** [comment]
Thank you @vicb for your answer. It adds more syntax but it does the job.
Just by curiosity, would the addition of <T extends AbstractControl> to the ControlGroup class in the angular 2 source code also have worked ?

**Comment by arunsn43** [comment]
Is this still valid? as there are still compilation errors like "AbstractControl" cannot be converted to type "Control". Property 'updateValue' is missing in type "AbstractControl"

**Comment by DzmitryShylovich** [comment]
yeas, this's' still valid. u need to cast AbstractControl to FormControl

**Comment by zoechi** [comment]
Is this a dup of #10040 ?
