### ISSUE TITLE
While upgrading from angular 6 to angular 7 getting error "Error: Must specify "tsConfigPath" in the configuration of @ngtools/webpack."

### ISSUE THREAD

**Issue by poonam197shukla** [angular/angular#58737]
Hi Team,

I upgraded from angular 6 to angular 7:

**version details of angular 6 before upgrade to version 7**
Angular CLI: 6.2.9
Node: 8.17.0
OS: win32 x64
Angular: 6.1.10
... animations, common, compiler, core, forms, http
... platform-browser, platform-browser-dynamic, router

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.8.9
@angular-devkit/core         0.8.9
@angular-devkit/schematics   0.8.9
@angular/cli                 6.2.9
@angular/compiler-cli        4.4.4
@angular/platform-server     4.4.4
@angular/tsc-wrapped         4.4.4
@schematics/angular          0.8.9
@schematics/update           0.8.9
rxjs                         6.6.7
typescript                   2.9.2
webpack                      3.5.5

**version details of angular 7 after upgrade from version 6:**
Angular CLI: 7.3.10
Node: 8.17.0
OS: win32 x64
Angular: 7.2.16
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.10
@angular-devkit/build-angular     0.13.10
@angular-devkit/build-optimizer   0.13.10
@angular-devkit/build-webpack     0.13.10
@angular-devkit/core              7.3.10
@angular-devkit/schematics        7.3.10
@angular/cli                      7.3.10
@ngtools/webpack                  7.3.10
@schematics/angular               7.3.10
@schematics/update                0.13.10
rxjs                              6.6.7
typescript                        3.9.10
webpack                           3.5.5

webpack.js:
const { AngularCompilerPlugin } = require('@ngtools/webpack');

module: {

      rules: [
        {
          test: /\.ts$/,
          use: [
            {
              loader: '@ngtools/webpack',
              options: {
                tsConfigPath: 'tsconfig.json', // Path to your TypeScript configuration (you might need tsconfig.app.json instead)
                mainPath: './src/main.ts', // Path to your main Angular entry file
                sourceMap: true, // Enable source maps for debugging
                skipCodeGeneration: false, // Set to true if you are using JIT (Just-In-Time) compilation instead of AOT
              }
            }
          ]
        }
      ]

    }

 plugins: [
      new AngularCompilerPlugin({
        tsConfigPath: 'tsconfig.json', // Path to your TypeScript configuration
        mainPath: './src/main.ts', // Your main entry file
        sourceMap: true, // Enable source maps (optional)
        skipCodeGeneration: false // Set to true if you use JIT compilation
      }),
]

**Note:** there is no change on any other file

**Error:**
..\node_modules\@ngtools\webpack\src\packages\ngtools\webpack\src\angular_compiler_plugin.ts:200
      throw new Error('Must specify "tsConfigPath" in the configuration of @ngtools/webpack.');
            ^
Error: Must specify "tsConfigPath" in the configuration of @ngtools/webpack.

**Question**: what dependency is missing from webpack which is causing this issue even after giving the correct path of tsconfig.json in tsConfigPath in webpack.js file.

**Comment by JeanMeche** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).
