### ISSUE TITLE
After update to version 19 tests not working

### ISSUE THREAD

**Issue by sysmat** [angular/angular#58749]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

- after upgrading to ng 19, test are failing
- test: 'ERROR', Error: NG0950: Input is required but no value is available yet. Find more at https://angular.dev/errors/NG0950

```typescript
beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [],
      providers: [
        provideHttpClient(),
        provideHttpClientTesting(),
        translocoForSpec,
        { provide: ComponentFixtureAutoDetect, useValue: true },
      ],
    }).compileComponents();

    fixture = TestBed.createComponent(AddressFormComponent);
    component = fixture.componentInstance;

    toaster = fixture.debugElement.injector.get(ToastService);
    userArnesService = fixture.debugElement.injector.get(UserArnesService);
    personService = fixture.debugElement.injector.get(PersonService);

    // we need to set some inputs and trigger detect changes to have tests with form
    fixture.componentRef.setInput('userId', 1);
    fixture.componentRef.setInput('address', testProfileAddressWithId);

    fixture.detectChanges();

    spyOn(toaster, 'error');
  });
```

- component

```typescript
export class AddressFormComponent {

  userId = input.required<number>();
  address = input.required<ProfileAddress | Person>();

  finished = output<boolean>();

  isCreate = computed(() => (this.address() ? false : true)); //  Error: NG0950: Input is required but no value is available yet

```
- even using `await fixture.whenStable();` not works/helps

### Please provide the exception or error you saw

```true

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 19.0.0
Node: 22.11.0
Package Manager: npm 10.9.0
OS: win32 x64

Angular: 19.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.0
@angular-devkit/build-angular   19.0.0
@angular-devkit/core            18.2.12
@angular-devkit/schematics      18.2.12
@schematics/angular             19.0.0
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0
```

**Comment by JeanMeche** [comment]
Hi, could you provide a minimal repro of your issue ? 

Where is `isCreate` used ?

**Comment by sysmat** [comment]
it is ok on ng 18

**Comment by sysmat** [comment]
I think the problem is when I use `{ provide: ComponentFixtureAutoDetect, useValue: true }`

**Comment by JeanMeche** [comment]
As mentionned above this was due to `ComponentFixtureAutoDetect` being set to `true` which is not compatible with required inputs in zonefull apps.

**Comment by sysmat** [comment]
yes I'm using zone, it should be documented

**Comment by DynamiteTom** [comment]
**Angular 19 Radio buttons are broken** with an important but subtle bug

This could break millions of applications without the authors realizing the problem
as the console.log or alert says everything is fine!

They always return one value - even though when you check with console.log - everything looks fine and
the log returns the correct value - But when you pass this value to a if then else or ternary operator
you always get the same value no matter which button is clicked!

I had 2 radio buttons returning 1 and 0 and for 5 years it worked fine on my application
But with Angular 19 - it always now returns 0 - no matter if I click the 1 or not

You can prove I'm right by setting the radio button value locally - see below

checkRB(rbValue : number){

// rbValue = 1; // this will prove the ternary operator is working fine

console.log('rbValue is ', rbValue); // this shows the correct value from the radio button

let color = (rbValue === 1)? 'Black' : 'White'; // always returns White

I thought at first the ternary operator was broken in Angular 19 but it and the if then else statements are fine

I had to change my radio button code to fix the bug -   Tom at dynaphoneimages@hotmail.com
