### ISSUE TITLE
`ng update` in v19 does not remove standalone flag for components without `imports`

### ISSUE THREAD

**Issue by sysmat** [angular/angular#58747]
### Command

update

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

when running `ng update` it should remove `standalone: true`

### Minimal Reproduction

- project was on ng 18
- running ˙ng update˙
```
@Component({
  selector: 'app-address-form',
  standalone: true,
```
- nothing heppens

### Exception or Error

```text

```

### Your Environment

```text
Angular CLI: 19.0.0
Node: 22.11.0
Package Manager: npm 10.9.0
OS: win32 x64

Angular: 19.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.0
@angular-devkit/build-angular   19.0.0
@angular-devkit/core            18.2.12
@angular-devkit/schematics      18.2.12
@schematics/angular             19.0.0
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0
```

**Comment by JeanMeche** [comment]
Hi, 
Currently the migration schematics will only remove `standalone: true` on components with imports. This is heuristic we use right now to keep the schematic idempotent. 

Having an unnecessary `standalone: true` has no impact on bundle size, but we're looking to improve our schematic, so we'll keep your issue open once this is done!

**Comment by sysmat** [comment]
@JeanMeche I don't understand I have many components with import and nothing was removed

```
@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  standalone: true,
  imports: [RouterLink, NgbNav, NgbNavItem, NgbNavLink, NgbCollapse, NgbAlert],
})
```

**Comment by JoostK** [comment]
> [@JeanMeche](https://github.com/JeanMeche) I don't understand I have many components with import and nothing was removed
> 
> ```
> @Component({
>   selector: 'app-navbar',
>   templateUrl: './navbar.component.html',
>   standalone: true,
>   imports: [RouterLink, NgbNav, NgbNavItem, NgbNavLink, NgbCollapse, NgbAlert],
> })
> ```

Could you please provide a reproduction of the update not dropping `standalone: true` for a component with `imports`?

**Comment by JeanMeche** [comment]
We discussed this with the team, 

Knowing that:
* Removing `standalone: true` in a straightforward manner break the idempotency of the migration
* It is kind of important to keep the migrations idempotent. As user might run `ng update` on each minor or also going to some of v19 minor directly
* Keeping `standalone: true` has no runtime impact, it's only an aesthetic issue. 
* a bare search-and-replace can take care of it
* Writing a complex migration will be costly (in time) for a low return. 

So we decided what we have right now is good enough.
If ever someone in the community wants to contribute to it we can have a look on the PR.

**Comment by DaSchTour** [comment]
As there is no possibility to have general discussions here I would like to leave my debrief of standalone migration here.
I think it would have been better to only add `standalone: false` and not remove `standalone: true` as this would offer a smoother migration path for the angular ecosystem.
Just consider the issue like this https://github.com/help-me-mom/ng-mocks/issues/10503 which for example can not be worked around when mocking angular material components. So in this case having version 19 with both flags set explicitly and giving the ecosystem time to migrate to the new default behavior would probably avoided a lot of headache for many devs migrating projects with these tools and also other third party dependencies.
I hope this might be something to consider in future. I really hope that the angular team will include the ecosystem a bit more into their development.
