### ISSUE TITLE
Angular.dev update guide (v18 to v19) is missing 'ng update' command

### ISSUE THREAD

**Issue by jitterbox** [angular/angular#58753]
### Describe the problem that you experienced

The Angular upgrade guide (v18 to v19) is missing the presumed command needed to actually upgrade Angular to v19:
`ng update @angular/core@19 @angular/cli@19`

### Enter the URL of the topic with the problem

https://angular.dev/update-guide?v=18.0-19.0&l=1

### Describe what you were looking for in the documentation

Need the actual upgrade command for upgrading Angular 18 to 19.
Carrying over the same syntax from 17 to 18 worked.

### Describe the actions that led you to experience the problem

Go to https://angular.dev/update-guide and select v18 to v19.
Any combination of the checkboxes produces the same output with the missing `ng update` command

### Describe what you want to experience that would fix the problem

Add the command.

### Add a screenshot if that helps illustrate the problem

![Image](https://github.com/user-attachments/assets/e57de28f-62de-4533-8d61-6793f17223ee)

### If this problem caused an exception or error, please paste it here

```true

```

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true

```

### Provide any additional information here in as much as detail as you can

```true

```

**Comment by tmac12** [comment]
I think that this issue is resolved, now it show `ng update` command.

![Image](https://github.com/user-attachments/assets/902c32f7-b969-4179-9cb1-a7e0c3788cd9)
