### ISSUE TITLE
feat(router): Add directive for active route link

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#5877]
A common use case is to attach a class to an element if the router link inside that element is active.

```html
<nav>
  Menu
   <ul>
    <li>
      <!-- "router-link-active" class attached when route is active -->
      <a [routerLink]="['Home']" class="link">Home</a>
    </li>
   </ul>
</nav>
```

There should be a built in directive to set a class on an element that isn't directly on the routerLink element

```html
<nav>
  Menu
   <ul>
    <!-- "active" class attached when route is active -->
    <li routerLinkActive="active">
      <!-- "router-link-active" class attached when route is active -->
      <a [routerLink]="['Home']" class="link">Home</a> 
    </li>
   </ul>
</nav>
```

**Comment by gionkunz** [comment]
I was seeking a similar solution and was using `@ViewChild(RouterLink) routerLink` in the component, to then access `routerLink.isRouteActive` from the view again. It works well and I believe it's a good solution, however, there seems to be a change detection issue related to `ViewChild` which forces you to use `ChangeDetectionRef.detectChanges()` in the `ngAfterViewInit` hook. I've opened an issue #5870  for this.

**Comment by brandonroberts** [comment]
@gionkunz thanks for the suggestion. I did something similar to that you did. I don't know if the same bug  happens there though.  http://plnkr.co/edit/AFwfpxGqnN6bBBGK86sq?p=preview

I think their should be some default implementation instead of everyone implementing their own solution in many different ways to accomplish the same thing.

**Comment by brandonroberts** [comment]
@gdi2290 has a PR in for this #6407
