### ISSUE TITLE
forkJoin/combineLatest works differently from 6.6.2 to 6.6.3

### ISSUE THREAD

**Issue by dmcliver** [angular/angular#58789]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

forkJoin/combineLatest works differently from 6.6.2 to 6.6.3 when used with a ReplaySubject and Observable, the replay subject doesn't seem to emit the next value.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/rxjs-7dw9nv?file=index.ts,package.json

### Please provide the exception or error you saw

```true
expected console output (as seen in rxjs 6.6.2):
0:one
1:two

actual console output (as seen in rxjs >= 6.6.3):
0:one
0:two

I thought combineLatest might solve this issue instead, but even using combineLatest also doesn't make any difference.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.2.12
Node: 18.20.2
Package Manager: npm 10.5.0
OS: win32 x64

Angular: 16.2.12
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1602.12
@angular-devkit/build-angular      16.2.12
@angular-devkit/core               16.2.12
@angular-devkit/schematics         16.2.12
@angular/cdk                       16.2.14
@angular/flex-layout               15.0.0-beta.42
@angular/material                  16.2.14
@angular/material-moment-adapter   16.2.14
@schematics/angular                16.2.12
rxjs                               7.8.1
typescript                         4.9.5
zone.js                            0.13.3
```

### Anything else?

I cant find anyone mentioning this problem from an internet search but as 7.8.1 is two years old it would strike me as odd that if this is a bug no one else has discovered it. So perhaps it's just our team using it wrong?

**Comment by crisbeto** [comment]
Closing since this is an issue with rxjs, not Angular.
