### ISSUE TITLE
@for not able to iterate formarray

### ISSUE THREAD

**Issue by govissasi** [angular/angular#58784]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

 

i create one formgroup like this 

getUserInfoForm(data?: UserInfo) {

return this.formBuilder.group({

name: [data?.name ? data.name : null, [Validators.required]],

age: [data?.age ? data.age : null, [Validators.required, Validators.min(18),Validators.max(99)]],

gender: [data?.gender ? data.gender : null, [Validators.required]],

hobbies: this.formBuilder.array([]),

})

}

this is my ts

ngOnInit() {

this.userInfo = this.formsService.getUserInfoForm();

this.addHobby();

}

getHobbies(): FormArray{

return this.userInfo.get('hobbies') as FormArray;

}

addHobby(data?: string) {

this.getHobbies().push(data ? new FormControl(data) : new FormControl(''))

}

removeHobby(index: number) {

this.getHobbies().removeAt(index);

}

here i able to iterate hobbies list using *ngFor 

<div class="col-12 d-flex justify-content-between" formArrayName="hobbies">

<label>Hobbies</label>

<div *ngFor="let hobby of getHobbies().controls; let i = index" class="d-flex gap-5 justify-content-start w-50">

<input class="form-control w-50" type="text" [formControlName]="i">

<button type="button" class="btn btn-primary" >Add</button>

<button type="button" class="btn btn-secondary" >Remove</button>

</div>

</div>

but i cant able did this using @for()

<div class="col-12 d-flex justify-content-between">

<label>Hobbies</label>

@for(hobby of getHobbies().controls; track $index) {

<div class="d-flex gap-5 justify-content-start w-50">

<input class="form-control w-50" type="text" name="hobby" formControlName="hobby">

<button class="btn btn-primary">Add</button>

<button class="btn btn-secondary">Remove</button>

</div>

}

</div>

facing below error 

Type

0 extends (1 & TControl) ? Array<AbstractControl<any>> : Array<TControl>

must have a [Symbol. iterator]() method that returns an iterator

### Please provide the exception or error you saw

```true
Type

0 extends (1 & TControl) ? Array<AbstractControl<any>> : Array<TControl>

must have a [Symbol. iterator]() method that returns an iterator
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI : 19.0.0
Node: 20.17.0
```

### Anything else?

![Image](https://github.com/user-attachments/assets/afd4b55e-70dc-40d7-b688-ce6c03298a57)

**Comment by JeanMeche** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).

**Comment by govissasi** [comment]
Repost this issue on [StackOverflow](https://stackoverflow.com/) @JeanMeche 

[click here](https://stackoverflow.com/questions/79208909/for-not-able-to-iterate-formarray-in-angular-19)
