### ISSUE TITLE
Incorrect warning of unused standalone pipe

### ISSUE THREAD

**Issue by chrillewoodz** [angular/angular#58794]
### Which @angular/* package(s) are the source of the bug?

language-service

### Is this a regression?

No

### Description

I have a standalone pipe:

```
@Pipe({
  standalone: true,
  name: 'libCharacterStyle',
  pure: true,
})
export class LibCharacterStylePipe implements PipeTransform {
  
  transform(characterStyle: LibCharacterStyle): any {
    return getClassesForCharacterStyle(characterStyle);
  }
}
```

Which I then use like this to include some tailwind classes:

```
<app-rich-text [config]="{ textClass: '{{ `body-l` | libCharacterStyle }} tw-text-white' }" />
```

But for some reason I'm getting a warning saying it's unused:

![Image](https://github.com/user-attachments/assets/9c2eb023-ff79-41f7-891b-5e6512890be5)

I'm using this pipe in other places where it doesn't give this warning, so I guess the problem arise due to the complex string pattern it's being used in.

### Please provide the exception or error you saw

```true
LibCharacterStylePipe is not used within the template of AppBlockSingleProductPricingComponent
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.2.11
Node: 20.10.0
Package Manager: npm 10.2.3
OS: darwin x64

Angular: 18.2.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.11
@angular-devkit/build-angular   18.2.9
@angular-devkit/core            18.2.9
@angular-devkit/schematics      18.2.9
@angular/cli                    18.2.11
@schematics/angular             18.2.9
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10
```

**Comment by JoostK** [comment]
You'd have to pull the substitution pattern out into manual string concatenation within the expression itself:

```
{ textClass: ('body-l' | libCharacterStyle + ') tw-text-white' }
```

I suspect there's a better way as this is quite atypical.
