### ISSUE TITLE
Router - Enable descendant components to terminate route configurations

### ISSUE THREAD

**Issue by gionkunz** [angular/angular#5879]
Sometimes it's required that a nested route is not linked to a component that is a direct child within the component tree. Currently this use-case is not supported and nested routes need to follow the direct configuration path along the component tree. Wouldn't it make more sense to allow skipping parents until a component is found with a route configuration? From a design point of view the route could establish through a mix of relevant and irrelevant components. Therefore in my naive view of the Angular source code, it wouldn't hurt if the `RouteRegistry` would traverse up to find the next configured Route https://github.com/angular/angular/blob/b1b0593ddfc69383d152a592a5e6faaa8647f0e1/modules/angular2/src/router/route_registry.ts#L355-L359, or does it?

Here's some example code:
http://plnkr.co/edit/bV92gAWMbJqkOz98fEoV?p=preview
```javascript
import {Component, Directive, Input, Inject, ViewChild, NgFor} from 'angular2/angular2';
import {RouteConfig, RouterOutlet, RouterLink, RouteParams, Route, Redirect} from 'angular2/router';

@Component({
  selector: 'content-one',
  template: `
    <p>Content One</p>
  `
})
export class ContentOne {}

@Component({
  selector: 'content-two',
  template: `
    <p>Content Two</p>
  `
})
export class ContentTwo {}

@Component({
  selector: 'descendant'
  template: `
    <h2>Descendant</h2>
    <a [routerLink]="['./ContentOne']">Content One</a>
    <a [routerLink]="['./ContentTwo']">Content Two</a>
    <router-outlet></router-outlet>
  `,
  directives: [RouterOutlet, RouterLink]
})
@RouteConfig([
  new Route({path: '/content-one', component: ContentOne, name: 'ContentOne', useAsDefault: true}),
  new Route({path: '/content-two', component: ContentTwo, name: 'ContentTwo'})
])
export class Descendant {}

@Component({
  selector: 'child'
  template: `
    <h2>Child</h2>
    <descendant></descendant>
  `,
  directives: [Descendant]
})
export class Child {}

@Component({
  selector: 'app'
  template: `
    <h1>App</h1>
    <router-outlet></router-outlet>
  `,
  directives: [RouterOutlet, RouterLink]
})
@RouteConfig([
  new Route({path: '/child/...', component: Child, name: 'Child', useAsDefault: true})
])
export class App {}
```

**Comment by soulcorrosion** [comment]
Any news on this? I have this use case and I can't delegate to my subcomponents to terminate the routing. Currently I am forced to specify a router-outlet along the way, which is not what I need and has issues. I managed to workaround by projecting the outlet to a subcomponent, but this has issues.

It is as described, having a component in the middle that does not have any RouteConfig. Please advise.

**Comment by vicb** [comment]
obsolete - former from module
