### ISSUE TITLE
ng generate @angular/core:route-lazy-loading fails

### ISSUE THREAD

**Issue by tibin-carestack** [angular/angular#58793]
### Command

generate

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

ng generate @angular/core:route-lazy-loading is failing after selecting the path in your project should be migrated.

Cannot read properties of undefined (reading 'kind') is the error message.

### Minimal Reproduction

> update to angular version 19
> run ng generate @angular/core:route-lazy-loading
> it will ask for Which path in your project should be migrated?
> press enter
> **gets error "Cannot read properties of undefined (reading 'kind')"**

### Exception or Error

```text

```

### Your Environment

```text
Angular CLI: 19.0.0
Node: 20.18.0
Package Manager: npm 10.9.0
OS: win32 x64

Angular: 19.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.12
@angular-devkit/build-angular   19.0.0
@angular-devkit/core            18.2.12
@angular-devkit/schematics      19.0.0
@angular/cdk                    18.2.14
@schematics/angular             19.0.0
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0
```

**Comment by JoostK** [comment]
This would need a reproduction if aligning the versions doesn't solve the problem.

**Comment by tibin-carestack** [comment]
Angular CLI: 19.0.0
Node: 20.18.0
Package Manager: npm 10.9.0
OS: win32 x64

Angular: 19.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.12
@angular-devkit/build-angular   19.0.0
@angular-devkit/core            19.0.0
@angular-devkit/schematics      19.0.0
@schematics/angular             19.0.0
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0

issue remains even after update

**Comment by JoostK** [comment]
Please provide a reproduction, without it this won't be actionable

**Comment by JoostK** [comment]
Do you happen to have an `@Component` without arguments?

```ts
@Component()
class ExampleComponent {}
```

that does break with this error, but is in itself invalid code.

**Comment by JoostK** [comment]
Oh, no, there's also the following valid code that breaks:

```ts
@OtherDecorator()
@Component({ template: '' })
class ExampleComponent {}
```

Working on a fix.

**Comment by tibin-carestack** [comment]
export class AppRoutingModule {}

code like this exist in my code
