### ISSUE TITLE
linkedSignal not tagged as experimental

### ISSUE THREAD

**Issue by kremerd** [angular/angular#58817]
### Describe the problem that you experienced

The [linkedSignal](https://next.angular.dev/api/core/linkedSignal) documentation is not tagged as "experimental" or "developer preview". This might trick developers into believing it is stable, although it actually is experimental according to [this blogpost](https://blog.angular.dev/meet-angular-v19-7b29dfd05b84). (It certainly tricked me 😅.)

### Enter the URL of the topic with the problem

https://next.angular.dev/api/core/linkedSignal

### If this problem caused an exception or error, please paste it here

```true

```

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true

```

### Provide any additional information here in as much as detail as you can

```true

```

**Comment by JeanMeche** [comment]
The function was actually promoted just before the release to `devPreview` but your point still stand, our doc infra doesn't pick up the tag correctly. 
Also note that the Jsdoc tag is the source of truth to determine the status of an api. 

https://github.com/angular/angular/blob/bd08d1ddacbf87acd23ee6e3531696a1a61fddef/packages/core/src/render3/reactivity/linked_signal.ts#L121-L123

**Comment by kremerd** [comment]
Thanks for the correction 👍. I did indeed believe the tags in the docs were extracted from the JSDoc.

**Comment by MikaelSvanasbakken** [comment]
> The function was actually promoted just before the release to `devPreview` but your point still stand, our doc infra doesn't pick up the tag correctly. Also note that the Jsdoc tag is the source of truth to determine the status of an api.
> 
> [angular/packages/core/src/render3/reactivity/linked_signal.ts](https://github.com/angular/angular/blob/bd08d1ddacbf87acd23ee6e3531696a1a61fddef/packages/core/src/render3/reactivity/linked_signal.ts#L121-L123)
> 
> Lines 121 to 123 in [bd08d1d](/angular/angular/commit/bd08d1ddacbf87acd23ee6e3531696a1a61fddef)
>   * @developerPreview 
>   */ 
>  export function linkedSignal<S, D>(options: {

I was looking at this - isDeveloperPreview does indeed just return false for linkedSignal preventing us from showing the proper label. I assume that it is a value grabbed from an API somewhere? If it's possible for me to solve, could you point me the right way perhaps?

**Comment by JeanMeche** [comment]
Each package has a bazel target to generate a json at build time. All those target are then used by the `generate_api_manifest` target. 

You can have a look at the generated json for the core package by running `yarn bazel build packages/core:core_docs_extraction`

**Comment by MikaelSvanasbakken** [comment]
> Each package has a bazel target to generate a json at build time. All those target are then used by the `generate_api_manifest` target.
> 
> You can have a look at the generated json for the core package by running `yarn bazel build packages/core:core_docs_extraction`

Seems like there was a missing developerPreview-tag in linked_signals.ts.

After adding it, Bazel was able to generate and provide a tag for it. Not sure how I managed to miss that on my first pass, d'oh. I'll make a PR and you can check if it's a viable solution.

**Comment by JeanMeche** [comment]
Actually It would be better if our tooling was able to pick-up the tags from the overloads and not only from the implementation.

**Comment by MikaelSvanasbakken** [comment]
> Actually It would be better if our tooling was able to pick-up the tags from the overloads and not only from the implementation.

Hm - I'll take a peek.

**Comment by MikaelSvanasbakken** [comment]
> Actually It would be better if our tooling was able to pick-up the tags from the overloads and not only from the implementation.

Unsure as of how to implement that since I'm still a little bit unfamiliar with the code in the repo. Should I just pass on creating a PR in anticipation that this gets reworked to grab tags from the overloads instead?
