### ISSUE TITLE
Add lint or diagnostic for "rules of computed" or "rules of signals"

### ISSUE THREAD

**Issue by NateRadebaugh** [angular/angular#58810]
### Description

Angular computed/effects have the same limitations as react hooks, but isn't well documented or warned about.
> https://react.dev/warnings/invalid-hook-call-warning

Specifically the rules outlined here are not immediately obvious and are difficult to debug if unknown:
> https://angular.dev/guide/signals#computed-signal-dependencies-are-dynamic

I think some diagnostic should be introduced, or eslint rule to hint.

### Proposed solution

https://www.npmjs.com/package/eslint-plugin-react

Maybe best handled by https://github.com/angular-eslint/angular-eslint

### Alternatives considered

Not sure

**Comment by JoostK** [comment]
I don't quite see overlap with "Rules of hook", TBH. The dynamic nature of dependency tracking is not a rule; it is a behavioral aspect to minimize when a computed needs to be reevaluated.

**Comment by NateRadebaugh** [comment]
> When you read conditionalCount, if showCount is false the "Nothing to see here!" message is returned without reading the count signal. This means that if you later update count it will not result in a recomputation of conditionalCount.

Maybe I'm confused by this explanation, but it seems the only way to get predictable results in a `computed` is to place all signal reads at the top of the block before any conditionals or early returns.

So to me there are some "foot guns" that can happen where things do not update as expected if you write code in the writing order, so a lint or diagnostic would help.

**Comment by JoostK** [comment]
Do you have an example in mind? If a value isn't needed for evaluation because of prior conditions evaluating to false, then changes to that value are also irrelevant as long as the conditions don't change. That's exactly the behavior that is modeled through computeds.

**Comment by JoostK** [comment]
See https://github.com/angular/angular/issues/56155 for the aspect of declaring dependencies explicitly upfront.

**Comment by NateRadebaugh** [comment]
Thanks, I appreciate your responses and time reviewing. I'll have to go back and see if my example was just a bug in my code or if there's something else I can provide in an example.

**Comment by NateRadebaugh** [comment]
Closing, I think my confusion was caused by expecting the `computed` to re-trigger when a child of an `if` statement changed, while the expression in the `if` statement was falsey, so it wouldn't trigger.

My mistake. Closing this one since it doesn't seem to be a functional issue.
