### ISSUE TITLE
Seeing detached elements in a memory snapshot when I navigate from one route to another

### ISSUE THREAD

**Issue by Tomas-CloudIQ** [angular/angular#58828]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

I am using Angular router module and trying to fix a memory leak problem.
In a sample application, I have 2 routes and I am in Page1.
Once I click anywhere in Page1 component and go to Page2 via routerLink, I can see Page1 component as a detached element in memory snapshot.
This is a screenshot.
![Image](https://github.com/user-attachments/assets/56d0b806-5a59-47de-97b0-5ea47abb787f)
I am in test-2 page now but can see app-test1 component is detached.

I tried in different Angular versions (12, 16, 19) and the behavior was exactly same.
Of course, I don't have any observables, pipes, services, ... My components are clean and it doesnt have any extra codes in component.ts files.
And I used only a and div tags in html.
It doesnt have any parent-child relationship too.

Can you please help me how I can fix this? or is this expected behavior in web applications?

### Please provide the exception or error you saw

```true

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular: 19.0.0
Node: 18.19.1
NVM
OS: Windows 10
Package.json
{
  "name": "new-test-detached",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^19.0.0",
    "@angular/common": "^19.0.0",
    "@angular/compiler": "^19.0.0",
    "@angular/core": "^19.0.0",
    "@angular/forms": "^19.0.0",
    "@angular/platform-browser": "^19.0.0",
    "@angular/platform-browser-dynamic": "^19.0.0",
    "@angular/router": "^19.0.0",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.15.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^19.0.1",
    "@angular/cli": "^19.0.1",
    "@angular/compiler-cli": "^19.0.0",
    "@types/jasmine": "~5.1.0",
    "jasmine-core": "~5.4.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "typescript": "~5.6.2"
  }
}
```

**Comment by JoostK** [comment]
Without runnable reproduction this won't be actionable to us.

**Comment by Tomas-CloudIQ** [comment]
Hi @JoostK , I made a simple sample angular app in StackBlitz and here is the link.
https://stackblitz.com/edit/stackblitz-starters-bztgsm?description=An%20angular-cli%20project%20based%20on%20@angular/animations,%20@angular/common,%20@angular/compiler,%20@angular/core,%20@angular/forms,%20@angular/platform-browser,%20@angular/platform-browser-dynamic,%20@angular/router,%20core-js,%20rxjs,%20tslib%20and%20zone.js&file=src%2Fapp.config.ts,src%2Fapp.routes.ts,src%2Fcomponents%2Froot%2Froot.component.html,src%2Fcomponents%2Froot%2Froot.component.ts,src%2Fcomponents%2Ftest1%2Ftest1.component.html,src%2Fcomponents%2Ftest1%2Ftest1.component.ts,src%2Fcomponents%2Ftest2%2Ftest2.component.html,src%2Fcomponents%2Ftest2%2Ftest2.component.ts,src%2Fmain.ts&template=node&title=Angular%20Starter

Reproduce steps.

- Click Test 1 text in the first page. (route is /test-1)
- Navigate to /test-2 by clicking GoTest2
- Open chrome DevTools and take a snapshot after garbage collection
![Image](https://github.com/user-attachments/assets/3b07c228-4e39-4285-a020-0dcbe9b38c95)

- You can see app-test1 component is detached which is not displayed in /test-2 route.
Please take a look of this application and let me know how we can avoid this probelm

**Comment by JoostK** [comment]
Thanks, that does show a retainer from Angular DevTools:

![Image](https://github.com/user-attachments/assets/2e00bc1a-c2e3-465f-bbb6-57119938be6f)

[Heap-20241125T230037.heapsnapshot.zip](https://github.com/user-attachments/files/17909395/Heap-20241125T230037.heapsnapshot.zip)


With the extension disabled (e.g. in Incognito mode) I don't see the same retainer, nor is it very persistent: opening DevTools caused it to be dropped.

**Comment by JoostK** [comment]
So the question is, are you experiencing the leak in production mode/without DevTools too?

**Comment by Tomas-CloudIQ** [comment]
Hi @JoostK , thanks for taking a look of my question.
In our production(different app), we are facing memory leak issue.
Dom nodes of previous pages are not fully removed when we navigate to another page via angular route.
We unsubscribed all observables and removed events listeners in ngOnDestroy but we still see some components are detached in sanpshot.

Here is my questions.

1. Is there any common factors which cause a memory leak in angular applications? Do you have any suggestions?
2. When we debug a memory leak from snapshot, should I focus on "Objects retained by detached DOM nodes" or "All objects"? In simple application, I can see some components are detached in "All objects" but those are not included in "Objects retained by detached DOM nodes".
3. Parent components has 3 child components (A, B, C). In Angular if A is not fully removed from DOM nodes, then  B C and Parent components are not fully removed as well?

Thanks again.

**Comment by JeanMeche** [comment]
Your narrowed down example doesn't reproduce your issue, in devmode without the extension or in prodmode the element doesn't get retained. 

Your snapshot clearly shoes that the devtools is retaining the element. 

Detached Domnode is a good entry point for leaks. 
Maybe to help a bit your investigation, you can keep the symbols while still building for prod with the `NG_BUILD_MANGLE=0` flag.

**Comment by Tomas-CloudIQ** [comment]
Hi @JeanMeche , thanks for your reply.

In sample application, in happens when you click some child elements before navigation. then you can see it is detached. I described repro steps in https://github.com/angular/angular/issues/58828#issuecomment-2498757303

Can you please help me on below question?
- When we debug a memory leak from snapshot, should I focus on "Objects retained by detached DOM nodes" or "All objects"?
- `NG_BUILD_MANGLE=0` where should I add this?

**Comment by Tomas-CloudIQ** [comment]
@JeanMeche , @JoostK 
Can you please let me know how to take a snapshot while running in production mode?
Is it same as we do in dev mode? (with chrome devtools)

**Comment by JeanMeche** [comment]
Yes, it's the same.

**Comment by Tomas-CloudIQ** [comment]
Thanks for your reply.
@JoostK , I have one more questions from your reply.
https://github.com/angular/angular/issues/58828#issuecomment-2499128541
How can I find that retainer comes from dev tools?

**Comment by Tomas-CloudIQ** [comment]
Hi @JoostK , @JeanMeche 
We are facing same issue again when we use angular material.
Currently, we are using matMenu and we can see some elements related to mantMenu are detached.
Here is an example link.
https://stackblitz.com/edit/v7o3ky-av3em4?file=package.json
if I click some menu items and go to test2 route, I can see menu elements are detached.
I followed the same steps you mentioned above. I did not open devtools while I am testing on the page.
![Image](https://github.com/user-attachments/assets/50822d1d-3436-466d-94bb-ce8441324dbb)

![Image](https://github.com/user-attachments/assets/4b1cca71-21a5-4738-9d61-9095ae12a41b)

Could you please help me on this?
or is this an open issue when we use angular material?

**Comment by JeanMeche** [comment]
So, the source of the leak is actually our animation module. 

![Image](https://github.com/user-attachments/assets/d20eee0d-f3ee-48eb-9bea-c5979e23775d)

This pretty much reminds me of #54149, where matSort had similar leaks. It was addressed very recently by angular/components#30057. 

Maybe @crisbeto can give some thoughts on this.

**Comment by JeanMeche** [comment]
v12 is outside of the support scope. Please have a look at our [support policy](https://angular.dev/reference/releases#support-policy-and-schedule).

**Comment by JoostK** [comment]
The animations memory leak is mostly benign, see https://github.com/angular/angular/issues/47748#issuecomment-1290868266.

**Comment by Tomas-CloudIQ** [comment]
@JeanMeche , was this fix released to Angular 17 latest versions now?

**Comment by JeanMeche** [comment]
Those fixes don't land in LTS versions but only the active one (currently v19).

**Comment by Tomas-CloudIQ** [comment]
@JeanMeche, So it was released to v19?
And do you have any plans to introduce this fix to v17?

**Comment by JeanMeche** [comment]
We don't do any backport fix beside security fixes. 
I think we can close this per above. The was no repro provided that exhibits a real leak.
