### ISSUE TITLE
Allow `rxResource`'s `request` fn to handle Observable triggers

### ISSUE THREAD

**Issue by markostanimirovic** [angular/angular#58854]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Currently, `rxResource`'s `request` function doesn't support returning an Observable that can trigger the loader function when new values are emitted.

Workaround:

```ts
const dataService = inject(DataService);
const click$ = new Subject<MouseEvent>();
const click = toSignal(click$, { initialValue: null });
const data = rxResource({
  request: click,
  loader: ({ request }) =>
    request ? dataService.getData() : of(null),
});
```

### Proposed solution

Allow `request` to return an Observable, where each emission triggers the loader function:

```ts
const dataService = inject(DataService);
const click$ = new Subject<MouseEvent>();
const data = rxResource({
  request: () => click$,
  loader: () => dataService.getData(),
});
```

**Benefits:**

- More reactive control over loader triggers
- Better integration with event-based workflows
- Reduced boilerplate when working with Observables

### Alternatives considered

_

**Comment by blueiceprj** [comment]
There is definitely a need for such a parameter to make the code cleaner and more understandable.
```
.......

shouldLoad: (parameters) => {
     return [parameters.request.name](http://parameters.request.name/) !== ''  
},

....
```

**Comment by pkozlowski-opensource** [comment]
@alxhub [already covered](https://github.com/angular/angular/issues/58854#issuecomment-2498647199) several things I wanted to mention, but I would like to further expand on one of the suggested benefits:

> Better integration with event-based workflows 

Here is the thing: `resource` was designed for data-based workflows. You set a state and and resource responds to changes in the state. With all the semantics that we already know from a computed - just that the computation is different / async. As Alex mention, event-based workflows are a completely different thinking and technical construct. IMO `resource` is not a good fit for those architectures - in the sense that it provides more friction than value. 

 I would suggest coming up with a different primitive for the event-based architectures.

**Comment by JeanMeche** [comment]
@e-oz You likely won't reach often for that status in the template. The loading status can be checked via the computed `myResource. isLoading()`.

**Comment by pkozlowski-opensource** [comment]
> As I understand this explanation, does it mean that resource is only a fit for loading data, aka GET requests? For loading, the declarative solution works great. But other verbs, such as POST or DELETE make sense when reacting to events.

@samuelfernandez yes, the idea of the `resource` is to represent data from the external story (regardless of the exact HTTP method used). As of today the `resource` doesn't have the change / mutation story for the external data sources. 

> Another question, what about the scenario where you want to define the request, but the source is defined later on? Example: the loader lives in a service, but the request params come from a component. How do you envision passing the request reference to the resource?

I believe that the current `resource` design covers this use-case - it takes 2 functions, regardless of where those are defined. unless I'm misunderstanding your question - a more concrete example would be needed.

**Comment by markostanimirovic** [comment]
Thank you all for sharing your thoughts! It seems this feature request is not in accordance with the `rxResource` design/future plans so I'm going to close it.

I wish we had an RFC for `resource`/`rxResource`. Many new ideas/challenges would emerge I guess.

Anyway, the overall design looks good to me, except for the name of the `request` property. When I saw `request` and `loader` for the first time, I was not sure which callback was the right place for sending HTTP requests. 👀 Consider renaming `request` to `source`, `payload`, or `trigger`.

**Comment by JeanMeche** [comment]
Note, an RFC is planned for early next year.
