### ISSUE TITLE
@if Syntax Not Rendering Content in Angular 18

### ISSUE THREAD

**Issue by EmbiiFox** [angular/angular#58856]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

The @if syntax introduced in Angular 18 is not rendering the content as expected. Although the conditions are valid, the HTML elements within the @if block do not render in the UI. However, when I remove the @if block, the UI elements appear as expected. Could you please give me advice to fix this issue? Thanks.

**To Reproduce**
Create an Angular 18 component with the following template:

```
@if (cvDetail && cvDetail.id) {
  <div class="right-content">
    <div>
      <div id="toc-target">
        <div #htmlToc class="toc-content"></div>
      </div>
      <div id="toc-target-no-water-mark" #htmlTocNoWaterMark>
      </div>
    </div>
  </div>
}
```
```
export class ExampleComponent implements OnInit, OnChanges {
  @Input() cvDetail: any; 

  @ViewChild('htmlToc') htmlToc: ElementRef | undefined;
  @ViewChild('htmlTocNoWaterMark') htmlTocNoWaterMark: ElementRef | undefined;
  constructor() { }
  ngOnInit(): void {
  }
  ngOnChanges() {
    if (this.cvDetail) {
        if (this.htmlTocNoWaterMark) {
          if (this.htmlToc) {
            this.htmlToc.nativeElement.innerHTML = '';
          }
          this.htmlTocNoWaterMark.nativeElement.innerHTML = this.cvDetail.body ? this.cvDetail.body : '';
        }
    }
  }
}
```
Expected behavior
value of this.cvDetail.body, example is '<p><span style="text-decoration: underline;"><strong><span style="color: rgb(224, 62, 45); text-decoration: underline;">summary sample (Red font, bold, underlined)</span></strong></span></p>' will be rendered in the UI

### Please provide the exception or error you saw

```true
when HTML have @if, this.htmlTocNoWaterMark is undefined
when I remove @if, this.htmlTocNoWaterMark have values
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.2.12
Node: 20.15.0
Package Manager: npm 10.7.0
OS: win32 x64

Angular: 18.2.12
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.12
@angular-devkit/build-angular   18.2.12
@angular-devkit/core            18.2.12
@angular-devkit/schematics      18.2.12
@angular/cdk                    18.2.13
@schematics/angular             18.2.12
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10
```

**Comment by JeanMeche** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).
