### ISSUE TITLE
Add hostDirectives Property to ComponentMirror object returned by reflectComponentType

### ISSUE THREAD

**Issue by DarioSpinosa** [angular/angular#58853]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Currently, the returned `ComponentMirror` object from the **reflectComponentType** function includes information about inputs, outputs, and other metadata of the component. However, it does not provide access to **host directives** and their respective inputs/outputs.

#### **Use Case**

In my specific scenario, I have the following structure:

- A base class `A`
- Multiple child classes `B`, `C`, `D`, etc., each with **different host directives**, including their own **inputs** and **outputs**.
- A service where i use reflectComponentType, passing all my child classes that are registered using an injection Token

When `reflectComponentType` is invoked on classes `B`, `C`, or `D`, the resulting `ComponentMirror` correctly includes the inputs and outputs of the specific child class. However, I also need access to the **host directives** metadata to retrieve their inputs and outputs. This is crucial for constructing a comprehensive API for the inputs and outputs of the child classes, including those inherited from their host directives.

### Proposed solution

Add a new `hostDirectives` property to the `ComponentMirror` object returned by `reflectComponentType`. This property should include
a list of the host directives applied to the component including their inputs and outputs

### Alternatives considered

Keep accessing host directives like in my code snippet below

```typescript
const componentDef = (componentType as any)['ɵcmp'];
const hostDirectives = componentDef.hostDirectives as {
  directive: Type<unknown>;
  inputs: Record<string, string>;
  outputs: Record<string, string>;
}[];

hostDirectives?.forEach(hostDirective => {
  const target = hostDirective.directive.prototype;
  const directiveInputs = hostDirective.inputs;
  const directiveOutputs = hostDirective.outputs;

  inputs.push(
    ...Object.keys(directiveInputs).map(input => ({
      name: directiveInputs[input],
      target
    }))
  );

  outputs.push(
    ...Object.keys(directiveOutputs).map(output => ({
      name: directiveOutputs[output],
      target
    }))
  );
});

**Comment by JeanMeche** [comment]
Hi, we're already tracking this issue at #49734.

**Comment by DarioSpinosa** [comment]
> Hi, we're already tracking this issue at [#49734](https://github.com/angular/angular/issues/49734).
The relative pull request has been closed due to inactivity. What should i do in this case?
