### ISSUE TITLE
invokeElementMethod doesn't return values?

### ISSUE THREAD

**Issue by tandu** [angular/angular#5885]
`<ClientRect>renderer.invokeElementMethod(el, 'getBoundingClientRect', []);` returns `undefined`, I expect it to return ClientRect object.

**Comment by tbosch** [comment]
To be able to work with web workers, the renderer would have to return a Promise with the result. We could add this, but I expect most of the methods on DOM elements actually to return non serializable values (as is the case for `ClientRect` in your example). So returning nothing is safer for now.

For your use case: 
You already assume that your code is running on the main thread of the browser (i.e. not serverside nor in a webworker) as you are working with `ClientRect` directly. In this case, it makes sense to call the method on `el.nativeElement.getBoundingClientRect()` directly.

**Comment by tandu** [comment]
I tried to avoid using `nativeElement` as there was a suggestion to always use `Renderer`.

**Comment by tbosch** [comment]
The general rule is:
If you want to interact directly with the DOM and are using DOM specific idioms like `ClientRect`, use the DOM directly (via `element.nativeElement`). 
If you want to write a cross platform application for webworkers, nativescript, serverside, ..., use the renderer, but then you can't use something like `ClientRect`. You would need to have a separate implementation for each of these platforms, and we need to document how to do this.

Btw, for your usecase, there already is a `Ruler` service (see [here](https://github.com/angular/angular/blob/master/modules/angular2/src/platform/browser/ruler.ts#L22)).

**Comment by tbosch** [comment]
See https://github.com/angular/angular/issues/2409 for tracking how to extend / write your own `Renderer` service...

**Comment by amcdnl** [comment]
@tbosch - Where did renderer `invokeElementMethod` not returning values land?

**Comment by DzmitryShylovich** [comment]
it does return whatever invoked method returns
