### ISSUE TITLE
`getTestBed().configureTestingModule` doesn't seem to respect `import`s added in Angular v19. Works in Angular v18

### ISSUE THREAD

**Issue by AtofStryker** [angular/angular#58862]
### Which @angular/* package(s) are the source of the bug?

core/testing

### Is this a regression?

Yes

### Description

It doesn't look like adding imports in `getTestBed().configureTestingModule` works as expected within `angular/core/testing`. When trying to add `CommonModule` as an import within the `cypress/angular` mount function, it doesn't look like the import is actually added into the test bed and the components with `CommonModule` directives are failing because the module is not registered.

 I noticed there were some changes in the [changelog](https://github.com/angular/angular/blob/main/CHANGELOG.md#1900-2024-11-19) but I didn't see anything that I would expect to break her

### Please provide a link to a minimal reproduction of the bug

https://github.com/AtofStryker/angular-19-cypress

### Please provide the exception or error you saw

To reproduce, clone the project and install dependencies with `npm install` with node 20.x

run `npx cypress open` and go to `component testing` -> `electron (or chrome)` -> `mount.cy.ts`

The test fails. The component doesn't mount correctly because it is using the `ngIf` directive, which should be registered when we run `getTestBed().configureTestingModule` when Cypress adds the import [here](https://github.com/AtofStryker/angular-19-cypress/blob/main/cypress/support/mount.ts#L180), but the console has the error that the `CommonModule` is not registered.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 19.0.1
Node: 20.18.0
package manager: npm 10.8.2
```

### Anything else?

I'm working on adding Angular 19 CT support within Cypress in https://github.com/cypress-io/cypress/issues/30175. I'm not an Angular export so hopefully I am just missing something 😅 .

**Comment by JoostK** [comment]
Angular 19 has switched to standalone by default, so the testing module imports are now irrelevant for components that don't have `standalone: false`, which the component in the repro doesn't have.

**Comment by AtofStryker** [comment]
> Angular 19 has switched to standalone by default, so the testing module imports are now irrelevant for components that don't have `standalone: false`, which the component in the repro doesn't have.

@JoostK ah that makes sense that testing modules are considered regular ng modules and would require `standalone: false`. THank you for getting back to me so quickly!
