### ISSUE TITLE
Where is documentation on how to upgrade the Angular cli?

### ISSUE THREAD

**Issue by Neutrino-Sunset** [angular/angular#58874]
### Describe the problem that you experienced

Searching the current Angular docs for `upgrade cli` or `update cli` returns plenty of results that describe how to upgrade an Angular project, but returns no information about how to update the Angular cli itself.

Searching Stackoverflow returns 7 year old questions with dozens of different answers.
https://stackoverflow.com/questions/43931986/how-to-upgrade-angular-cli-to-the-latest-version

Don't you think the Angular documentation should describe the current recommended approach to upgrade the Angular cli?

### Enter the URL of the topic with the problem

https://angular.dev/cli/update

### Describe what you were looking for in the documentation

How to upgrade the Angular cli.

### Describe the actions that led you to experience the problem

Searching the documentation found nothing.

### Describe what you want to experience that would fix the problem

Add the documentation.

### If this problem caused an exception or error, please paste it here

```true

```

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true

```

### Provide any additional information here in as much as detail as you can

```true

```

**Comment by JeanMeche** [comment]
[The update guide](https://angular.dev/update-guide?v=17.0-18.0&l=1) gives the update recommendations. 

Running `ng update @angular/core@18 @angular/cli@18 ` will update the CLI with the rest of the project.

**Comment by alan-agius4** [comment]
It is also listed in the page you linked in the issue.

**Comment by Neutrino-Sunset** [comment]
Doesn't that just update the Angular versions used in a specific project?

That doesn't update the globally installed Angular cli does it?

**Comment by JeanMeche** [comment]
If you want to update the global version, that like any npm package, nothing specific to angular : `npm i -i @angular/cli@latest`.
