### ISSUE TITLE
Transformed files have different line numbers, causing coverage data to be wrong

### ISSUE THREAD

**Issue by srawlins** [angular/angular#5887]
I thought that preserving line numbers in files with `@Component`s is important. I am seeing cases where transforming `templateUrl` and `styleUrls` changes line numbers though. Such as:

```dart
107  @View(
108      directives: const [ ... ],
109      templateUrl: 'package:some_directories/src/components/'
110          'some-file.html',
111      styleUrls: const [
112        'package:some_directories/src/components/'
113            'some-file.scss.css',
114      ])
```

gets transformed to:

```dart
107  @View(
108      directives: const [ ... ],
109      template: _template0,
110      styles: const [_style1,])
```

Or worse, it appears its getting fmt'ed:

```dart
697  @View(
698      template: '<ng-content></ng-content>',
699      styleUrls: const [
700        'package:some_directories/src/components/'
701            'some_panel.scss.css'
702      ])
```

gets transformed allllll the way down to:

```dart
697  @View(template: '<ng-content></ng-content>', styles: const [_style2,])
```

This breaks reports generated by Dart's coverage tooling.

**Comment by srawlins** [comment]
CC @kegluneq @cbracken

**Comment by TedSander** [comment]
We have found out how to remove the DartFmt. Now the problem is two lines being converted into one. Probably just need to comment out the old lines instead of replacing them to keep the line numbers. Example:
``` dart
107  @View(
108      directives: const [ ... ],
109      template: _template0, /*templateUrl: 'package:some_directories/src/components/'
110          'some-file.html',*/
111      styles: const [_style1,]) /*styleUrls: const [
112        'package:some_directories/src/components/'
113            'some-file.scss.css',
114      ])*/
```

**Comment by kegluneq** [comment]
This bug is appearing in test code which is using the `InlinerForTest` transformer to inline `templateUrl` & `styleUrls` values.

There is [code (and tests)](https://github.com/angular/angular/commit/a31e2f5f4799e9ce20ae508f9f91dfeba05805f2) in place to maintain line numbers, but these seem to not be working in some cases.

I like Ted's suggestion for fixing this.

**Comment by srawlins** [comment]
My bad. Tim's tests from a31e2f5f4799e9ce20ae508f9f91dfeba05805f2 work. If I print out the input and output from "should maintain line numbers when replacing values", I get:

```dart
INPUT LINES
  0  library playground.src.hello_world.url_expression_files;
  1  
  2  import 'package:angular2/angular2.dart'
  3      show Component, Directive, View, NgElement;
  4  
  5  @Component(selector: 'hello-app')
  6  @View(
  7      templateUrl: 'supersupersupersupersupersupersupersupersupersupersupersuper'
  8          'superlongtemplate.html',
  9      styleUrls: const [
  10        'pretty_longish_template.css',
  11        'other_pretty_longish_template.css'
  12      ])
  13  class HelloCmp {}
OUTPUT LINES
  0  library playground.src.hello_world.url_expression_files;
  1  
  2  import 'package:angular2/angular2.dart'
  3      show Component, Directive, View, NgElement;
  4  
  5  @Component(selector: 'hello-app')
  6  @View(
  7      template: _template0
  8  ,
  9      styles: const [_style1,_style2,]
  10  
  11  
  12  )
  13  class HelloCmp {}
```

This bug was 100% caused by using dartfmt on the transformed code. Thanks @TedSander @kegluneq !
