### ISSUE TITLE
Circular dependency error when injecting directive in materialized Template

### ISSUE THREAD

**Issue by NachmanBerkowitz** [angular/angular#58887]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

In the stackblitz that I link I have two versions of the same component, `WrapperOne` and `WrapperTwo`. They both contain a div which a directive, `MyDirective`, is applied to. They also both contain a component, `CompoentOne`, which is nested in that div. `ComponentOne` injects `MyDirective`. The only difference is that `WrapperTwo` wraps the nested `ComponentIOne` in an `@if(true)`.
When navigating to `WrapperOne` I get `Circular dependency in DI detected for _MyDirective` error. But when navigating to `WrapperTwo` I do not get this error.
All `MyDirective` does is
``` 
constructor(templateRef: TemplateRef<any>, viewContainer: ViewContainerRef) {
    viewContainer.createEmbeddedView(templateRef);
  }
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-bpb1py?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
.localservice@runtime.88b6dd69.js:26 
 ERROR RuntimeError: NG0200: Circular dependency in DI detected for _MyDirective. Find more at https://angular.dev/errors/NG0200
    at new _ComponentOne (component1.ts:9:15)
    at NodeInjectorFactory.ComponentOne_Factory [as factory] (component1.ts:9:33)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
"dependencies": {
    "@angular/animations": "^19.0.0",
    "@angular/common": "^19.0.0",
    "@angular/compiler": "^19.0.0",
    "@angular/core": "^19.0.0",
    "@angular/forms": "^19.0.0",
    "@angular/platform-browser": "^19.0.0",
    "@angular/router": "^19.0.0",
    "rxjs": "^7.8.1",
    "tslib": "^2.5.0",
    "zone.js": "~0.15.0"
  },
  "devDependencies": {
    "@angular/build": "^19.0.0",
    "@angular/cli": "^19.0.0",
    "@angular/compiler-cli": "^19.0.0",
    "typescript": "^5.6.3"
  }
```

**Comment by pkozlowski-opensource** [comment]
The actual error is legitimate: what is going on here is that `MyDirective` is creating an instance of a dynamic template containing `ComponentOne` and `ComponentOne` tries to inject `MyDirective` that didn't finish the construction yet. Hence the error.

A possible work-around is to move the TemplateRef instantiation logic to the `OnInit` lifecycle hook: https://stackblitz.com/edit/stackblitz-starters-ush4ag?file=src%2Fmain.ts

**Comment by pkozlowski-opensource** [comment]
@NachmanBerkowitz see the above explanation: the error is legitimate, you should restructure your code.
