### ISSUE TITLE
docs: location-pin SVG is missing

### ISSUE THREAD

**Issue by tauseefthedeveloper** [angular/angular#58890]
### Describe the problem that you experienced

Above the url i trouble to get the data please correct that the issue

### If this problem caused an exception or error, please paste it here

```true

```

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true

```

### Provide any additional information here in as much as detail as you can

```true

```

**Comment by JeanMeche** [comment]
Without any feedback, I'll close this.
