### ISSUE TITLE
Angular V19  ng build --configuration production -- dist folder tree

### ISSUE THREAD

**Issue by gskumar0708** [angular/angular#58896]
Hi Team,
  I have created a new Angular application using version 19 without SSR enabled. When I try to run the application from the Visual Studio terminal. where as I couldn't be able to deploy the code to iis.

![Image](https://github.com/user-attachments/assets/6384eac0-bb63-480c-8460-225e1df9101e)

Following options used while creation of Angular application:

![Image](https://github.com/user-attachments/assets/62afca50-f18e-480b-8094-c3df0a85991c)

When I try to build the application using the following command: ng build --configuration production
After successful execution, I can see the following folders under Dist Folder -> application folder name 

![Image](https://github.com/user-attachments/assets/20e7faed-7613-4de2-bff2-f22e8db3b976)

Here the Angular.json file configuration:
![Image](https://github.com/user-attachments/assets/5cbdaa56-7c46-45be-977d-9d4e5703b8e4)

 
Issue : I am unable to server the Angular application from Windows iis. After copying the dist folder content to the iis application folder below the error message.

![Image](https://github.com/user-attachments/assets/4837832c-dabb-4a72-893a-2c3ee17270be)

And also I have added web.config file in order to run the angular application from iis. 
Can you please help me on this?

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by gskumar0708** [comment]
Thanks @JoostK ,
 I have created issue on [StackOverflow](http://stackoverflow.com/) using tag angular.  Please help
