### ISSUE TITLE
Multi-line code retains leading and trailing spaces

### ISSUE THREAD

**Issue by paulthomas-lnrs** [angular/angular#58895]
### Command

build

### Description

Due to multi-line wrapping there are extraneous uncollapsed spaces.  When the preserveWhitespaces is set to remove them it doesn't.

```
let goodExample = 'Good';
let badExample = '*Bad*';

<table>
    <tr>
        <th>{{ goodExample }}</th>
        <th> 
            {{badExample}}
        </th>
    </tr>
    <tr>
        <td>Has Header with NO leading and trailing spaces</td>
        <td>Bad header with unwanted leading and trailing spaces</td>
    </tr>
</table>
```

minified prod build output with uncollapsed spaces:
`<table><tr><th>Good</th><th> *Bad* </th></tr> etc...</table>`

### Describe the solution you'd like

Ideally remove the surrounding spaces when preserveWhitespaces is set to do so.

### Describe alternatives you've considered

Removing all multi-line auto formatted lines wrapping with prettier.  Note: It's more of a testing overhead issue for automation having to strip them out.

**Comment by JoostK** [comment]
This is working as expected; HTML is whitespace-sensitive and Angular retains those semantics. Please see https://github.com/angular/angular/issues/57871
