### ISSUE TITLE
Why is the documentation so bad? It's totally unreadable

### ISSUE THREAD

**Issue by Agoni1** [angular/angular#58893]
### Describe the problem that you experienced

please build document in the old way

### If this problem caused an exception or error, please paste it here

```true

```

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true

```

### Provide any additional information here in as much as detail as you can

```true

```

**Comment by JoostK** [comment]
Without concrete aspects that you think deserve to be improved this isn't an actionable issue. I'd request you to open a new issue with constructure points.
