### ISSUE TITLE
Workspace with lib works during `ng serve` but not with `ng build && npm run serve:ssr:app`, throwing NG0203 Injection error

### ISSUE THREAD

**Issue by Mochitto** [angular/angular#58902]
### Which @angular/* package(s) are the source of the bug?

platform-server

### Is this a regression?

Yes

### Description

Hey there.

My team has upgraded angular from modules to standalone components and SSR (with the aim of adding i18n support).
We use angular v18 and have an external shared library between our projects, where we keep some services that are useful for our environment.

When using `ng serve` the app works as expected. 
When buildling the app, I get an `inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with runInInjectionContext.`.

After days of debugging, I've managed to pin down the problem to the DI between our shared-library and our application, creating [this Minimal Reproducible Example (MRE)](https://github.com/Mochitto/angular-ssr-NG0203), which consists in an angular workspace with an SSR application and a library with one service that uses `HttpClient`.

To build
```
ng build shared-library
ng build --configuration development
npm run serve:ssr:test-remote
```

Originally our use-case didn't make use of angular workspaces and just had the library in a parent directory, but the result is the same.
This issue also breaks SSG (build-time prerender) and seems to happen also with other angular's built-in services (ex. `Location`) when they are injected in the external library's services.

Things I've tried that didn't work:
- `preserveSymLink`, in angular.json and tsconfig
- Providing the service in the `app.config`
- Providing the service to the component
- Using `provideHttpClient` and the deprecated `HttpClientModule` in `app.config`
- (regarding APP_INITIALIZER in `app.config`) switching to ENVIRONMENT_INITIALIZER for service init (not shown in the MRE, but same error/issue)
- Removing the service from both `app.config` and `app.component`, leaving it in children components (throws the same error)
- Upgrading to Angular v19
- Updating all the dependencies
- Referencing the source code of the library instead of the `dist` when importing the service.

Things I tried that **did solve the issue somehow but aren't functional to our use-case**:
- Bringing the services inside of the app's `src`; when the same service is present in the same directory as the `app.component.ts`, the app builds and runs without any problem.

This makes me think the problem is the resolution of DI between libraries and applications.

The MRE doesn't mirror our use-case completely, as the error appears in `INITIALIZE_APP` while using said service, with the same error, but we have many of these services and most are used in components, so I figured this would bring to the same solution.
You can observe those extra errors by adding the service to `INITIALIZE_APP` or by turning on SSG.

**Notice**: the error is reported twice upon page navigation (one on the server and one on the client?) if used in the `app.component.ts`, while it's thrown during build if used in `app.config` with `APP_INITIALIZER`.

### Please provide a link to a minimal reproduction of the bug

https://github.com/Mochitto/angular-ssr-NG0203

### Please provide the exception or error you saw

```true
ERROR RuntimeError: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `ru
nInInjectionContext`. Find more at https://angular.dev/errors/NG0203                                                                                                     
    at injectInjectorOnly (file:///angular-workspace/dist/test-remote/server/chunk-KT33RR7F.mjs:2869:11)                         
    at ɵɵinject (file:///angular-workspace/dist/test-remote/server/chunk-KT33RR7F.mjs:2879:59)                                   
    at NodeInjectorFactory.HttpService_Factory [as factory] (file:///angular-workspace/dist/test-remote/server/chunk-BITCFHXY.mjs
:36964:52)                                                                                                                                                               
    at getNodeInjectable (file:///angular-workspace/dist/test-remote/server/chunk-BITCFHXY.mjs:6112:38)                          
    at searchTokensOnInjector (file:///angular-workspace/dist/test-remote/server/chunk-BITCFHXY.mjs:6061:12)                     
    at lookupTokenUsingNodeInjector (file:///angular-workspace/dist/test-remote/server/chunk-BITCFHXY.mjs:6011:26)               
    at getOrCreateInjectable (file:///angular-workspace/dist/test-remote/server/chunk-BITCFHXY.mjs:5952:19)                      
    at ɵɵdirectiveInject (file:///angular-workspace/dist/test-remote/server/chunk-BITCFHXY.mjs:9110:17)                          
    at NodeInjectorFactory.AppComponent_Factory [as factory] (file:///angular-workspace/dist/test-remote/server/chunk-BITCFHXY.mj
s:37015:53)                                                                                                                                                              
    at getNodeInjectable (file:///angular-workspace/dist/test-remote/server/chunk-BITCFHXY.mjs:6112:38) {                        
  code: -203                                                                                                                                                             
}                                                                                                                                                                        
Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionC
ontext`. Find more at https://angular.dev/errors/NG0203                                                                                                                  
    at injectInjectorOnly (file:///angular-workspace/dist/test-remote/server/chunk-KT33RR7F.mjs:2869:11)                         
    at ɵɵinject (file:///angular-workspace/dist/test-remote/server/chunk-KT33RR7F.mjs:2879:59)                                   
    at NodeInjectorFactory.HttpService_Factory [as factory] (file:///angular-workspace/dist/test-remote/server/chunk-BITCFHXY.mjs
:36964:52)                                                                                                                                                               
    at getNodeInjectable (file:///angular-workspace/dist/test-remote/server/chunk-BITCFHXY.mjs:6112:38)                          
    at searchTokensOnInjector (file:///angular-workspace/dist/test-remote/server/chunk-BITCFHXY.mjs:6061:12)
    at lookupTokenUsingNodeInjector (file:///angular-workspace/dist/test-remote/server/chunk-BITCFHXY.mjs:6011:26)
    at getOrCreateInjectable (file:///angular-workspace/dist/test-remote/server/chunk-BITCFHXY.mjs:5952:19)
    at ɵɵdirectiveInject (file:///angular-workspace/dist/test-remote/server/chunk-BITCFHXY.mjs:9110:17)
    at NodeInjectorFactory.AppComponent_Factory [as factory] (file:///angular-workspace/dist/test-remote/server/chunk-BITCFHXY.mj
s:37015:53)
    at getNodeInjectable (file:///angular-workspace/dist/test-remote/server/chunk-BITCFHXY.mjs:6112:38)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 18.2.12
Node: 20.14.0
Package Manager: npm 10.7.0
OS: linux x64

Angular: 18.2.12
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.12
@angular-devkit/build-angular   18.2.12
@angular-devkit/core            18.2.12
@angular-devkit/schematics      18.2.12
@schematics/angular             18.2.12
ng-packagr                      18.2.1
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10
```

### Anything else?

I wasn't able to find much about this problem in other issues or around the net... I hope someone can help with it.

**Comment by JoostK** [comment]
This smells like duplicate bundling of `@angular/core`, resulting in two non runtimes that are unaware of each other's state

**Comment by Mochitto** [comment]
@JoostK yeah. Some of the "promising" issues I had found were about this specific problem, but I wasn't able to confirm this by myself and find workarounds; I'm not sure how to manipulate the DI/packages resolution to solve this.

**Comment by JeanMeche** [comment]
@Mochitto check the you don't have dependencies that pull different versions of angular. It's the usual cause for this issue.

**Comment by alan-agius4** [comment]
@Mochitto, I looked at the reproduction, but the issue you mentioned does not appear in the provided reproduction.

```
$ npm i
...
$ ng build shared-library
...
$ ng build --configuration development
...
$ npm run serve:ssr:test-remote

> angular-workspace@0.0.0 serve:ssr:test-remote
> node dist/test-remote/server/server.mjs

Node Express server listening on http://localhost:4000
hello
Angular is running in development mode.
```

**Comment by Mochitto** [comment]
@alan-agius4 
Thanks for checking;
It does indeed not reproduce from a clean folder... It's odd since it did reproduce the error when I built it, although it was from a folder inside of the private repository; maybe some package.json higher up or other config files broke it

I'll check today and update the issue

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.
