### ISSUE TITLE
Showing cannot declare Standalone component even component is not Standalone

### ISSUE THREAD

**Issue by ganthixganesh** [angular/angular#58909]
### Command

build, version

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Migrated from 18.2.8 to 19.0.2. But unable to build after migration, but component is not standalone. Facing this issue in custom library/

NG6008: Component TestComponent is standalone, and cannot be declared in an NgModule. Did you mean to import it instead?

### Minimal Reproduction

1.Create one custom library with lower version of 19.0.2
2.Create component without standalone
3.Now migrate to version 19.0.2

### Exception or Error

```text

```

### Your Environment

```text
19.0.2
```

**Comment by JeanMeche** [comment]
Hi, could you share the result of your migration in a github repro. Without more details, this isn't actionable to us. Thank you.

**Comment by JeanMeche** [comment]
Without any feedback from OP, I'll close this.
