### ISSUE TITLE
feat(signals): Enhance Signal composition with reactive operators

### ISSUE THREAD

**Issue by shlyk** [angular/angular#58912]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

This proposal presents two approaches to enhance Angular Signals with powerful transformation capabilities.

The addition of operator composition capabilities to Angular Signals represents a significant step forward in making complex state management more maintainable and expressive. This proposal aims to:

1. **Enhance Signal Composition**
- Break down complex computed signals into smaller, reusable operations
- Enable clear separation of concerns in data transformation logic
- Improve code readability through familiar operator patterns
2. **Strengthen Signal Reactivity**
- Add powerful reactive capabilities to the Signal system
- Bridge the gap between synchronous computations and async operations
3. **Improve Developer Experience**
- Provide a clean, fluent API for complex state transformations
- Enable gradual adoption of more sophisticated Signal patterns
- Support natural decomposition of business logic into focused, testable units

## RxJS Integration

Add a new operator that allows seamless integration between Angular Signals and RxJS, enabling direct piping of Signal values through RxJS operators and back to Signals without explicit conversion steps.

### Current Behaviour

Currently, developers need to use both toObservable() and toSignal() to work with RxJS operators in a Signal context:

```typescript
query: WritableSignal<string> = signal('');

todos: Signal<Todo[]> = toSignal(
  toObservable(this.query).pipe(
    // RxJS operators
  ),
  { initialValue: [] }
);
```

### Desired Behavior
 
Introduce a new pipe() operator that handles the Signal-RxJS-Signal conversion internally:

```typescript
import { rxPipe } from "@angular/core/rxjs-interop";

...

query: WritableSignal<string> = signal('');

todos: Signal<Todo[]> = rxPipe(
  this.query, 
  map((query) => query.trim()),
  filter((query) => query.length > 0),
  distinctUntilChanged(),
  debounceTime(500),
  switchMap((query) => ...),
);
```

#### Proposed API

```typescript
import { OperatorFunction } from 'rxjs';

...

function rxPipe<T>(
  source: Signal<T>,
  ...operators: OperatorFunction<any, any>[]
): Signal<R>; // where R is the result of piping
```

## Native Signal Operators

Extend Signal interface with native implementations of common reactive operators, allowing direct operator chaining without RxJS dependency:

```typescript
interface Signal<T> {
    ...
    pipe<R>(
      ...operators: SignalOperatorFunction<T, R>[]
    ): Signal<R>;
  }

...

query: WritableSignal<string> = signal('');
todos: Signal<Todo[]> = query.pipe(
  map((query) => query.trim()),
  filter((query) => query.length > 0),
  distinctUntilChanged(),
  debounceTime(500),
  switchMap((query) => ...),
);
```

**Comment by JeanMeche** [comment]
Signals are a different paradigm than Observables. Both have reactivity patterns but Signals are state based where Observable are event based. 

The concept of `pipe` only suits well an event-based paradigm and is therefore not useful with signals.
