### ISSUE TITLE
resource request and loader functions should run in injection context when injector is provided

### ISSUE THREAD

**Issue by DmitryEfimenko** [angular/angular#58921]
### Description

Example:
```ts
@Injectable()
class ProductService {
  currentProductId = signal(1);
}
```

```ts
function createProductResource(injector: Injector) {
  const productResource = resource({
    injector,
    request: () => {
      // this line of code will fail because inject was called without injection context even though injector is passed in
      const productService = inject(ProductService);
      const productId = productService.currentProductId();
      if (productId  == null) {
        return undefined;
      }
      return { productId };
    },
    loader: ({ request: { productId } }) =>
      this.#http.get<Product>(`https://myapi/product/${productId}`),
  });
  return productResource;
}
```

### Proposed solution

if injector is passed in, wrap the `request` and `loader` calls in `runInInjectionContext()`

### Alternatives considered

none

**Comment by wartab** [comment]
Why would it do that? It's not an injection context. In your example, can just use the dependency injector yourself for that purpose. 
Also your example is clearly in a class (given I can see `this.#http`). Why not just inject the `ProductService` like you inject the `HttpClient`?

**Comment by pkozlowski-opensource** [comment]
We would rather not: both request and loader functions will run repeatedly and there is no point of interrogating the injector all the time. All the dependencies can be injected _above_ the resource and referenced in a closure.
