### ISSUE TITLE
RxResource with re-emitting observable as loader source doesn't reflect changes

### ISSUE THREAD

**Issue by kle-pra** [angular/angular#58930]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Shouldn't  rxResource reflect changes when using observable that re-emits as a loader function or is this expected behavior?

Best regards.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/~/github.com/kle-pra/ng-rx-resource-test

### Please provide the exception or error you saw

```true

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 19.0.2
Node: 22.4.1
Package Manager: npm 10.8.1
OS: linux x64

Angular: 19.0.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.2
@angular-devkit/build-angular   19.0.2
@angular-devkit/core            19.0.2
@angular-devkit/schematics      19.0.2
@angular/cli                    19.0.2
@schematics/angular             19.0.2
rxjs                            7.8.1
typescript                      5.6.3
zone.js
```

**Comment by JoostK** [comment]
This is working as documented: https://angular.dev/api/core/rxjs-interop/rxResource

> Like `firstValueFrom`, only the first emission of the `Observable` is considered.

Also see #58854

**Comment by sysmat** [comment]
@JoostK this is bad design, if prefix is meant for rxjs observables, then is misleading. It would be nice to work as sync pipe

**Comment by JeanMeche** [comment]
There is no way to get a loading status if an observable emits multiple data. The loading status is part of the resource experience.

**Comment by sysmat** [comment]
For years we are using rxjs, ok doc explicitly mention this "only the first emission of the Observable is considered." 
It would be great if we have reactivity from request and observable

**Comment by M0ns1gn0r** [comment]
> There is no way to get a loading status if an observable emits multiple data. 

As soon as the first emitted value is received the resource should become "loaded". As simple as that.

**Comment by JeanMeche** [comment]
@M0ns1gn0r, you might be interested in #59024 !
