### ISSUE TITLE
Directive is never used in a component template if is structural directive

### ISSUE THREAD

**Issue by legrottagliegionata** [angular/angular#58958]
### Which @angular/* package(s) are the source of the bug?

language-service

### Is this a regression?

Yes

### Description

If I import a structural directive, a warning is incorrectly reported stating that the directive is not used in the template. However, in my case, the directive is indeed used in the template.
I noticed that this only happens when the TemplateRef in the directive is injected using the inject(...) function instead of the constructor.

- Component.ts
![Image](https://github.com/user-attachments/assets/7f89fd02-b0f9-461c-80ca-1050ac7a533e)

- Component.html
![Image](https://github.com/user-attachments/assets/a49571ec-7ef8-4297-8f4f-166713f3b54a)

In fact, as shown in the following image, CdkTreeNodeDef uses the inject() function.
![Image](https://github.com/user-attachments/assets/3e487dbb-a818-4bcb-8d2e-e6afeee7c27c)

Below, I provide an example using a custom directive:

- In this case, the directive uses the InjectionToken in the constructor, and no issues are reported.
![Image](https://github.com/user-attachments/assets/b4ef7bd8-5865-4eba-a907-86d711606b3f)
![Image](https://github.com/user-attachments/assets/485739ee-8c54-4e3d-b341-999238016999)

- In this case, I used the inject() function to inject the TemplateRef, and the issue is reported.
![Image](https://github.com/user-attachments/assets/8c42ae6b-c78c-4894-9e26-91cfedced4ce)
![Image](https://github.com/user-attachments/assets/e393b187-654e-426c-9b19-581a0753cc8e)

### Please provide the exception or error you saw

```true
Directive CdkTreeNodeDef is never used in a component template
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 19.0.2
Node: 22.11.0
Package Manager: npm 10.9.0
OS: darwin arm64

Angular: 19.0.1
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1802.12
@angular-devkit/core         18.2.12
@angular-devkit/schematics   18.2.12
@angular/build               19.0.2
@angular/cdk                 19.0.0
@angular/cli                 19.0.2
@angular/material            19.0.0
@schematics/angular          18.1.1
ng-packagr                   18.2.1
rxjs                         7.8.1
typescript                   5.6.3
zone.js                      0.14.10
```

**Comment by JoostK** [comment]
The screenshots show diagnostics in a Jetbrains IDE, Which implements its own Angular support.

**Comment by wartab** [comment]
@legrottagliegionata 
There have been several reports about this in JetBrain's issue tracker and it's on their roadmap to fix this.
https://youtrack.jetbrains.com/issue/WEB-70386/Angular-Directive-CodeDirective-is-never-used-in-a-component-template
https://youtrack.jetbrains.com/issue/WEB-69383/False-positive-unused-import-for-Angular-structural-directive

People have reported as a workaround for custom structural directives, that adding `[*sIfReport], [*sIfReport]` as your selector will get rid of the warning.
