### ISSUE TITLE
Angular Language Service on Zed Editor

### ISSUE THREAD

**Issue by BeliliFahem** [angular/angular#58969]
### Which @angular/* package(s) are relevant/related to the feature request?

language-service

### Description

Have Angular Language Service on the Zed Editor ([www.zed.dev](http://www.zed.dev/))

### Proposed solution

I've tested Zed and noticed that it consumes significantly fewer resources compared to VS Code, which is impressive. I believe it would be highly beneficial to integrate angular language-service as extension into Zed alongside other tools.

### Alternatives considered

No alternative on Zed Editor.

**Comment by mauriziocescon** [comment]
See also https://github.com/zed-industries/extensions/issues/169

**Comment by JeanMeche** [comment]
Thank you for your interest in improving Angular's support for additional IDEs! At this time, the Angular team has chosen to focus our efforts on supporting a single IDE to ensure a high-quality and consistent experience for developers. Unfortunately, we aren't able to provide custom support for other IDEs, including Zed.

That said, Angular's language service is designed to be extensible, and it’s possible to build an extension for Zed on top of it. Additionally, other IDEs, such as WebStorm and Neovim, have implemented their own support for Angular by integrating with the language service. This approach allows the community to expand IDE compatibility while leveraging Angular's core tools.

We encourage you to explore building an extension for Zed and are happy to assist with any questions or guidance regarding the language service APIs. We truly appreciate your understanding and your enthusiasm for Angular.
