### ISSUE TITLE
NG0953 when updating an model signal within writeValue()

### ISSUE THREAD

**Issue by araareon** [angular/angular#58968]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

I have a model signal

`    checked = model<boolean>(false);`

Within writeValue (to implement ngModel) i have an easy .set

```
 writeValue(value: boolean | null): void {
        this.checked.set(value);
    }
```

Sometimes an NG0953 error comes up because the component seems to in an destroyed state and therefore he cant update the model 
(says "OutputRef" in the error message).

Does not happen always - i assume somehow inside @if / *ngIf

### Please provide the exception or error you saw

```true
NG0953
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.1.4
Node: 22.11.0
Package Manager: npm 10.2.4
OS: win32 x64

Angular: 18.1.4
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1801.4
@angular-devkit/build-angular   18.1.4
@angular-devkit/core            18.1.4
@angular-devkit/schematics      18.1.4
@schematics/angular             18.1.4
ng-packagr                      18.1.0
rxjs                            7.8.1
typescript                      5.5.4
webpack                         5.95.0
zone.js                         0.14.10
```

**Comment by JoostK** [comment]
Without a reproduction this won't be actionable.

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Comment by Nashuim** [comment]
@araareon Do you have any animations associated to this component? If so, you might be facing the issue described in #19826
