### ISSUE TITLE
Loose object type inference with resource and rxResource

### ISSUE THREAD

**Issue by lcottingham** [angular/angular#58976]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

The new experimental `resource()` and `rxResource()` api is producing pretty loose type inference with objects. The API adds an `any[]` type (<T | any[]>), which causes typescript to throw an error when the resource value object is accessed.

A simple rxResource test below shows the correct type hints within the loader() callback, and in the IDE. However, the type is lost in the `.value()` call.

```
readonly testResource = rxResource({
    request: () => this.submissionId(),
    loader: ({ request: id }) => {
        return this.submissionService.fetchCouponInformation(id).pipe(
            map(r => r.data.submission.coupon),
            catchError(error => of([]))
        )
    },
})

readonly resourceValue = computed(() => this.testResource.value()?.id)
```

With this test case, the output of the loader request would be `{ __typename?: "Coupon";     id: string;     code: string;     createdAt: string; }`
The resource API is adding `any[]` to the expected type, which is superseding the expected inferred type.

This creates the above type error on the computed `resourceValue`.

### Please provide the exception or error you saw

```true
[ERROR] TS2339: Property 'id' does not exist on type 'any[] | { __typename?: "Coupon"; id: string; code: string; createdAt: string; }'.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 19.0.2
Node: 20.18.0
Package Manager: npm 10.8.2
OS: darwin arm64

Angular: 19.0.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.2
@angular-devkit/build-angular   19.0.2
@angular-devkit/core            19.0.2
@angular-devkit/schematics      19.0.2
@angular/cli                    19.0.2
@schematics/angular             19.0.2
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0
```

**Comment by JoostK** [comment]
This seems to work as expected considering the use of `catchError(error => of([]))`

**Comment by lcottingham** [comment]
You, my friend... are exactly right.
Home time for me!
