### ISSUE TITLE
Failed to load out the Login page when using iPad device

### ISSUE THREAD

**Issue by arcjain240893** [angular/angular#59006]
### Describe the problem that you experienced

ipad version is 14. Our site even have customers who use safari v11. How can I support all those versions?

### Enter the URL of the topic with the problem

hillstohome.com

### Describe what you were looking for in the documentation

Our site even have customers who use safari v11. How can I support all those versions?

### Describe the actions that led you to experience the problem

Upgrade to angular 17

### Describe what you want to experience that would fix the problem

What updates should be done in polyfills?

### If this problem caused an exception or error, please paste it here

```true

```

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
ipad v14
```

### Provide any additional information here in as much as detail as you can

```true

```

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
