### ISSUE TITLE
The newest 2.0.0-alpha.53 Quick start tutorials requires Python to be installed first

### ISSUE THREAD

**Issue by aholbreich** [angular/angular#5901]
The newest 2.0.0-alpha.53 Quick start tutorials requires Python to be installed first.
I think this is accidetly the case, but
```
npm install
```
Complained about missing some python stuff..

Not it disspeared after i've installed python to my Windows machine

So why python at all?

---
P.S.
Package.json form tutorial
```
{
  "name": "angular2-quickstart",
  "version": "1.0.0",
  "scripts": {
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "lite": "lite-server",
    "go": "concurrent \"npm run tsc:w\" \"npm run lite\" "
  },
  "license": "ISC",
  "dependencies": {
    "angular2": "2.0.0-alpha.53",
    "systemjs": "0.19.6",
    "es6-promise": "^3.0.2",
    "es6-shim": "^0.33.3",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-alpha.14",
    "zone.js": "0.5.8"
  },
  "devDependencies": {
    "concurrently": "^1.0.0",
    "lite-server": "^1.3.1",
    "typescript": "^1.7.3"
  }
}
```

**Comment by pkozlowski-opensource** [comment]
@aholbreich could you please provide the relevant part of the NPM log? Was it an error or just a warning?

**Comment by filipesilva** [comment]
A lot of npm packages try to, as an optional dependency, recompile themselves natively via `node-gyp`. I ran the example myself and got a few of these:

```
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\filipe.silva\AppData\Roaming\nvm\v4.2.1\node_modules\npm\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Users\filipe.silva\AppData\Roaming\nvm\v4.2.1\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\filipe.silva\\AppData\\Roaming\\nvm\\v4.2.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\sandbox\quickstart\node_modules\lite-server\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\b fferutil
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
npm WARN optional dep failed, continuing bufferutil@1.2.1
```

This does not mean that `npm install` failed though - it's actually fine! It went on, and at the end printed a list of all installed packages. 

These are **gyp** errors, not **npm** errors. A npm error would be something like the below except, where I tried adding an hypothetical `angular2@3.0.0-alpha.53` version to `package.json`:

```
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7

npm ERR! version not found: angular2@3.0.0-alpha.53
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\sandbox\quickstart\npm-debug.log
```

Notice that every line starts with `npm` and at the end a `npm-debug.log` was generated.

**Comment by aholbreich** [comment]
@pkozlowski-opensource unfortunatelly not now, because it works after python installation.
ut @filipesilva  provided one.

**Comment by aholbreich** [comment]
@filipesilva gyp errors are maybe also not fine..

**Comment by tapas4java** [comment]
@filipesilva Looks like you are trying to install angular 3 `angular2@3.0.0-alpha.53` :)

**Comment by filipesilva** [comment]
@aholbreich They are not ideal for sure, but since they are part of a dependency of a dependency of a dependency (`lite-server -> browser-sync -> socket.io -> socket.io-client -> engine.io-client -> ws -> bufferutil`) there isn't much that can be done. Because the dependency is optional, it also has a very minor performance impact, if any. See [here](https://github.com/socketio/socket.io/issues/2272#issuecomment-155666295), [here](https://github.com/socketio/socket.io/issues/1842) and in general [here](https://github.com/socketio/socket.io/issues?utf8=%E2%9C%93&q=is%3Aissue+gyp).

@tapas4java yes, but that was only just to exemplify what a npm error would look like!

**Comment by dsebastien** [comment]
The --no-optional flag is a life saver. Node-gyp is the plague... https://www.dsebastien.net/2015/07/01/quick-npm-tip-and-a-little-rant-about-node-gyp/

**Comment by filipesilva** [comment]
Oh nice! Had no idea that existed. :+1:

**Comment by pkozlowski-opensource** [comment]
Sounds like a npm warning from one of the dependencies, not much to do with Angular.
