### ISSUE TITLE
withComponentInputBinding in combination with withRouterConfig({ paramsInheritanceStrategy: 'always' }) not working in child, queyparam is undefined

### ISSUE THREAD

**Issue by JessinhoW** [angular/angular#59013]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

I'am using withComponentInputBinding() to bind my query parameters to input signals. When I want to use the input signal in a child component it is always undefined.

Even when I add withRouterConfig({ paramsInheritanceStrategy: 'always' }) the signal is undefined (while queryparammap shows the correct value)

Is this expected behaviour?

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-vakejq-k3nnrk?file=src%2Fapp.component.ts,src%2Fapp.routes.ts,src%2Ffeatures%2Fparent%2Fparent.component.ts,src%2Ffeatures%2Fchild%2Fchild.component.ts,src%2Fmain.ts,src%2Findex.html

### Please provide the exception or error you saw

```true

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
@angular/animations
18.0.6
@angular/common
18.0.6
@angular/compiler
18.0.6
@angular/core
18.0.6
@angular/forms
18.0.6
@angular/platform-browser
18.0.6
@angular/platform-browser-dynamic
18.0.6
@angular/router
18.0.6
@ngrx/effects
18.0.1
@ngrx/store
18.0.1
@ngrx/store-devtools
18.0.1
rxjs
7.8.1
tslib
2.6.3
zone.js
0.14.7
```

**Comment by JoostK** [comment]
Yes this is expected behavior, only the routed components takes part in input binding when `withComponentInputBinding` is used.
