### ISSUE TITLE
unusedStandaloneImports incorrectly reports unused import when import is used as a hostDirective

### ISSUE THREAD

**Issue by john-melin** [angular/angular#59022]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

When using an imported directive in hostDirective both the angular language service and the compiler using unusedStandaloneImports: true, incorrectly reports the 'CdkMenuGroup' as being unused.

`
@Component({
  selector: 'app-selector',
  imports: [CdkMenuGroup],
  hostDirectives: [CdkMenuGroup],
`

### Please provide the exception or error you saw

```true
All imports are unused(-998113)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 19.0.2
Node: 20.11.1
Package Manager: yarn 4.5.0
OS: darwin arm64

Angular: 19.0.2
... animations, common, compiler, compiler-cli, core, elements
... forms, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/build-angular   19.0.2
@angular-devkit/core            19.0.2
@angular-devkit/schematics      19.0.2
@angular/cdk                    19.0.2
@angular/cli                    19.0.2
@schematics/angular             19.0.2
```

**Comment by JeanMeche** [comment]
You don't need to import your directive if you use it as a `hostDirective`.
