### ISSUE TITLE
Resource API undefined types

### ISSUE THREAD

**Issue by fabioemoutinho** [angular/angular#59021]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Not sure this is the correct place to provide some feedback about the resource API, but here it is:

1. I would love to be able to type narrow the value() type in the template (and outside too) to get rid of undefined type when verifying hasValue or if status is resolved, unless I would explicitly add undefined to the generic type. I am not sure this is possible, but it would be great.

2. when providing a request function to a resource, I would have expected the function to possibly return undefined, but not inside the loader as it should type narrow it because loader only runs if request does not return undefined.

### Proposed solution

1. In the template, if under a condition of status is equal to resolved, do not union undefined in return type of value()
2. in a resource, within loader function, request should not have undefined as a possible return type.

### Alternatives considered

Stay as is

**Comment by JeanMeche** [comment]
Hi,

Your #1 issue is being investigated by #58962, it is expected that `hasValue()` narrows down. 

About your #2, why would you want to prevent `undefined` to be returned ? `undefined` could be see as a valid state.

**Comment by fabioemoutinho** [comment]
> Hi,
> 
> Your [#1](https://github.com/angular/angular/issues/1) issue is being investigated by [#58962](https://github.com/angular/angular/pull/58962), it is expected that `hasValue()` narrows down.
> 
> About your [#2](https://github.com/angular/angular/issues/2), why would you want to prevent `undefined` to be returned ? `undefined` could be see as a valid state.

The documentation says if the resource function returns undefined, loader wont run.
While resource function can be typed as a function that returns T | undefined, within the loader function the resource parameter (the return value of resource function) can never be undefined, which causes you have to use the ! Operator or handle undefined value within loader function.

**Comment by JeanMeche** [comment]
Oh then this is the issue reported in #58871. 

I think we can close this one as a duplicate.

**Comment by fabioemoutinho** [comment]
I am glad both are already being tracked!
Thanks btw, the new resource API is amazing!
