### ISSUE TITLE
2.0.0-alpha.54 does not load @ViewChildren

### ISSUE THREAD

**Issue by frickt** [angular/angular#5903]
With the new Release 2.0.0-alpha.54 @ViewChildren is always null and the ngAfterViewInit() gets never invoked.

To create the component, i use DynamicComponentLoader.loadIntoLocation(...)

with release 2.0.0-alpha.53 it has worked.

**Comment by pkozlowski-opensource** [comment]
@frickt would you mind sharing a plunker?

**Comment by frickt** [comment]
is there a template for alpha.54?

**Comment by pkozlowski-opensource** [comment]
we should have it as soon as https://github.com/angular/angular/issues/5904 is solved

**Comment by jeffbcross** [comment]
Hey @pkozlowski-opensource I manually pushed bundles to code.angularjs.org. #5904 is just to make it automatic for future releases.

**Comment by frickt** [comment]
Plunker is working, It was my fault, I've used
<script src="./node_modules/reflect-metadata/Reflect.js"></script>
and not 
<script src="./node_modules/angular2/bundles/angular2-polyfills.js"></script>
sry for that...
