### ISSUE TITLE
After updating to Angular 19 router: Router gives error in all places but appears to work in any case

### ISSUE THREAD

**Issue by brianreinhold** [angular/angular#59047]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

Just updated to Angular 19. In every component where I inject Router I get the error
```
No suitable injection token for parameter 'router' of class 'ConfigComponent'.
  Consider using the @Inject decorator to specify an injection token
```

I get this error when building

```
Error: src/app/config/config.component.ts:2051:10 - error TS2339: Property 'router' does not exist on type 'ConfigComponent'.
2051     this.router.navigate([path]);
```

in all the components where I have the router. It is the only 'injection' effected. Was fine in Angular 18.

However, the code runs fine and I have no problems navigating (at least from the ng serve case0. I have not tried a remote deployment.

### Please provide the exception or error you saw

```true

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true

```

**Comment by JeanMeche** [comment]
Hi, we would need a larger example of the code to understand what is your issue. Ideally a narrowed down reproduction on stackblitz.

**Comment by brianreinhold** [comment]
@JeanMeche I really wanted to open up something in the discussion group but I could not figure out how to do that.

**Comment by JeanMeche** [comment]
You could do this via a [stackblitz](stackblitz.com).

**Comment by pkozlowski-opensource** [comment]
Going to close it for now as we haven't heard back with the reproduction scenario
