### ISSUE TITLE
Could not resolve "@angular/animations/browser"

### ISSUE THREAD

**Issue by davidbusuttil** [angular/angular#59050]
### Which @angular/* package(s) are the source of the bug?

platform-browser

### Is this a regression?

Yes

### Description

Since @angular/platform-browser@19.0.2, building or running an application/library that hasn't @angular/animations as a dependency results in the an error being thrown.

### Please provide the exception or error you saw

```true
Build: Could not resolve "@angular/animations/browser"

Serve: Cannot find package '@angular/animations' imported from C:\Users\...\node_modules\@angular\platform-browser\fesm2022\animations.mjs
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 19.0.3
Node: 20.18.1
Package Manager: npm 10.9.0
OS: win32 x64

Angular: 19.0.2
... common, compiler, compiler-cli, core, platform-browser
... platform-browser-dynamic, platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.3
@angular-devkit/build-angular   19.0.3
@angular-devkit/core            19.0.3
@angular-devkit/schematics      19.0.3
@angular/cli                    19.0.3
@angular/fire                   19.0.0-rc.0
@angular/ssr                    19.0.3
@schematics/angular             19.0.3
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0
```

**Comment by pkozlowski-opensource** [comment]
@davidbusuttil could you please share a minimal reproduction scenario?

**Comment by JeanMeche** [comment]
You need to add `@angular/animations` to your dependencies.

**Comment by pkozlowski-opensource** [comment]
@JeanMeche I'm actually not sure if we should revert - sounds like the animations module was brought almost "by accident"

**Comment by davidbusuttil** [comment]
> The workaround: You need to add `@angular/animations` to your dependencies.
> 
> I think we need to revert [#58997](https://github.com/angular/angular/pull/58997). Platform-server uses a animation ref.
> 
> [angular/packages/platform-server/src/server.ts](https://github.com/angular/angular/blob/60e59007b0dd579990c376730adcda55f316bb27/packages/platform-server/src/server.ts#L38)
> 
> Line 38 in [60e5900](/angular/angular/commit/60e59007b0dd579990c376730adcda55f316bb27)
> 
>  import {NoopAnimationsModule} from '@angular/platform-browser/animations';

Thank you for the prompt action.

**Comment by pkozlowski-opensource** [comment]
For anyone bumping into this issue:
* it is a regression that is already fixed in the source code;
* we are going to cut another release later today with the fix
* there is a work-around: https://github.com/angular/angular/issues/59050#issuecomment-2518080543

**Comment by pkozlowski-opensource** [comment]
FYI, https://github.com/angular/angular/releases/tag/19.0.3 was released with a fix.
