### ISSUE TITLE
NG0909: Expected to be in Angular Zone, but it is not!

### ISSUE THREAD

**Issue by AruljothySundaramoorthy** [angular/angular#59063]
### Which @angular/* package(s) are the source of the bug?

zone.js

### Is this a regression?

No

### Description

Have updated my angular application from V16 to V17 then moved to V18, while the running the App. in V18 its throwing err like "NG0909: Expected to be in Angular Zone, but it is not!"

### Please provide the exception or error you saw

```true
"NG0909: Expected to be in Angular Zone, but it is not!"
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true

```

**Comment by JeanMeche** [comment]
Hi, without a reproduction of this issue this isn't actionable to us. 
You'll need to give us a minimal repro for us to investigate that.
