### ISSUE TITLE
adev: getApiNavigationItems contains expensive sorting and delays application's bootstrap

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#59069]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Profiling https://angular.dev/api shows that there is (relatively) expensive `getApiNavigationItems` executed well before application bootstrap. This delays initial rendering. As far as I can tell the culprit is in the sorting of the navigation items.

![Image](https://github.com/user-attachments/assets/d1ef9fe4-7864-4e66-9700-2880c22849ab)

Maybe we could sort those entries at the build time? 

### Please provide the exception or error you saw

```true

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true

```

**Comment by JeanMeche** [comment]
fixed by #59106
