### ISSUE TITLE
Angular is decoding reserved characters from fragments

### ISSUE THREAD

**Issue by alexprudhomme** [angular/angular#59081]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

We use fragments (`#`) in the url to manage the search part of the state in our [redux based library](https://github.com/coveo/ui-kit/blob/master/packages/headless/README.md). When we encounter reserved characters in the state such as `&`, we use [encoreURIComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) to encode them. 

This works fine in most contexts. In the context of Angular we are encountering a problem where angular decodes those reserved characters and changes the url with the decoded part. 

Here is an example where `%26` is wrongfully changed into `&`.
https://kathleenwest.github.io/sample-angular-app/#q=This%26That
turns into 
https://kathleenwest.github.io/sample-angular-app/#q=This&That

This does not happen if we use query parameters (`?`)
https://kathleenwest.github.io/sample-angular-app/?q=This%26That
stays 
https://kathleenwest.github.io/sample-angular-app/?q=This%26That

Is this intended ? Why is angular decoding reserved characters in fragments ?

### Please provide a link to a minimal reproduction of the bug

Any new angular project

### Please provide the exception or error you saw

```true

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.4
@angular-devkit/build-angular   19.0.4
@angular-devkit/core            19.0.4
@angular-devkit/schematics      19.0.4
@angular/cli                    19.0.4
@schematics/angular             19.0.4
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0
```

**Comment by JoostK** [comment]
I'm on mobile right now so haven't checked why this happens, but `@` is a valid fragment character (https://stackoverflow.com/a/26119120) so there's nothing wrong with such URL.

**Comment by JeanMeche** [comment]
It is the expected behavior of the `DefaultUrlSerializer`.  

https://github.com/angular/angular/blob/46f00f951842dd117653df6cca3bfd5ee5baa0f1/packages/router/test/url_serializer.spec.ts#L375-L385

If you want an alternative behavior you can provide your own `UrlSerializer` token.
