### ISSUE TITLE
Ctrl+Click behaviour to open new tab does not work with RouterLink

### ISSUE THREAD

**Issue by pcroc** [angular/angular#5908]
In Chrome or FF, I often like to Ctrl+Click a link to open it in a new tab.

An anchor with the `[router-link]` directive does not behave this way, and affects the current browser tab. This could be very annoying for users.

**Comment by gaiottino** [comment]
Agree. This is something that many users rely on and should be supported.

**Comment by ThiagoT1** [comment]
Any workaround or ETA on this?

**Comment by ThiagoT1** [comment]
I required this thing before bootstraping my app and now CTRL+Click and MiddleClick will let the browser do its thing.

This assumes `router.ROUTER_DIRECTIVES` is used in all needed directives array.

```javascript
var core = require('angular2/core');
var router = require('angular2/router');

var MiddleClickRouterLink = (function () {
    function MiddleClickRouterLink(_router, _location) {
        var _this = this;
        this._router = _router;
        this._location = _location;
        this._router.subscribe(function (_) { return _this._updateLink(); });
    }
    MiddleClickRouterLink.prototype = router.RouterLink.prototype;
    MiddleClickRouterLink.prototype.onClickWithEvent = function (_) {
        if (_.ctrlKey || _.button == 1)
            return true;
        return this.onClick();
    };
    
    core.Directive({
        selector: '[routerLink]',
        inputs: ['routeParams: routerLink', 'target: target'],
        host: {
            '(click)': 'onClickWithEvent($event)',
            '[attr.href]': 'visibleHref',
            '[class.router-link-active]': 'isRouteActive'
        }
    })(MiddleClickRouterLink);
    Reflect.metadata('design:paramtypes', [router.Router, router.Location])(MiddleClickRouterLink);
    return MiddleClickRouterLink;
})();

router.ROUTER_DIRECTIVES[1] = MiddleClickRouterLink;

exports.MiddleClickRouterLink = MiddleClickRouterLink;
```

**Comment by pcroc** [comment]
Please can this issue be assessed and prioritized? Although there is a workaround be redefining router-link (as above), this is something that badly impacts UX and will affect almost everyone.

**Comment by pcroc** [comment]
Here is the code provided by @ThiagoT1 converted to TypeScript:

```typescript
import {Directive} from 'angular2/core';
import {Router, RouterLink, Location} from 'angular2/router';

@Directive({
  selector: '[routerLink]',
  inputs: ['routeParams: routerLink', 'target: target'],
  host: {
    '(click)': 'onClickWithEvent($event)',
    '[attr.href]': 'visibleHref',
    '[class.router-link-active]': 'isRouteActive'
  }
})
export class MiddleClickRouterLink extends RouterLink {
  constructor(router: Router, location: Location) {
    super(router, location);
  }
  public onClickWithEvent(e: MouseEvent): any {
    if (e.ctrlKey || e.button === 1) {
      return true;
    }
    return super.onClick();
  }
}

// Override Angular's RouterLink with our patched version
ROUTER_DIRECTIVES[1] = MiddleClickRouterLink;
```

**Comment by beljand** [comment]
Does this work for anyone? I do catch pressed metakey, but new tab doesn't get opened.

**Comment by gracew** [comment]
Looks like a fix for this is in progress, but for anyone using the suggested workarounds: make sure that you are only using the routerLink selector on `<a>` tags (not `<li>`, `<div>`, etc.).

**Comment by rahul-winner** [comment]
It seems still not working when I used routerLink directive within a component which is being rendered within '<router-outlet>'

For example below code works fine and takes me to the #/jobs when I right click on hyperlink
```
<div>
  <app-navigation></app-navigation>
</div>
<div>
	<a routerLink="jobs">My Jobs</a>
</div>
<div>
  <router-outlet></router-outlet>
</div>
```

But below code does not work
```
<div>
  <app-navigation></app-navigation>
</div>
<div>
  <router-outlet></router-outlet>
</div>
```
There is a route to 'home.component.html' present within App Navigation component.

**home.component.html**
```
<div>
	<a routerLink="jobs">My Jobs</a>
</div>
```

I'm using Angular version 4.4.4

Could anyone please help me.

**Comment by Cmacu** [comment]
I have the same issue as rahul-winner

**Comment by amaneer94** [comment]
https://stackoverflow.com/questions/41355830/angular-2-routing-run-in-new-tab

`` <a routerLinkActive="active" [routerLink]="['/projects']" >Projects</a>``
