### ISSUE TITLE
Typo in NgModules documentation

### ISSUE THREAD

**Issue by jvh-centric** [angular/angular#59096]
### Describe the problem that you experienced

https://github.com/angular/angular/blob/30e676098d72e9e11a6628b9716668df08f18c62/adev/src/content/guide/ngmodules/overview.md?plain=1#L155

This sentence seems wrong ? 

### Enter the URL of the topic with the problem

https://angular.dev/guide/ngmodules/overview

### Describe what you were looking for in the documentation

I'm not 100% what it is meant to say ...

Maybe:

Similarly, some NgModules may **have** a static `forChild` that indicates the providers are intended to be added to components within your application hierarchy.

?

### If this problem caused an exception or error, please paste it here

```true

```

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true

```

### Provide any additional information here in as much as detail as you can

```true

```

**Comment by JeanMeche** [comment]
It should be ` Similarly, some NgModules may define a static `forChild` that indicates the providers are intended to be added to components within your application hierarchy.`

The change is up for grab :)

**Comment by joshbenner851** [comment]
Looks like this got fixed and merged -  in this [commit](https://github.com/angular/angular/commit/2d49c36871bfc7407350cb241e616af16f732a50) which has been merged https://github.com/angular/angular/blob/1f4ff2fa36f5d6240cbc4a40839d3d89501519d8/adev/src/content/guide/ngmodules/overview.md?plain=1#L155

I believe someone can close this issue now
