### ISSUE TITLE
Clarification Needed: Key Differences Between `linkedSignals` and `computed` in Dynamic Scenarios

### ISSUE THREAD

**Issue by saikorthivada** [angular/angular#59090]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

As per my understanding on linkedSignals and computedSignals both can be used based some specific scenarios. Here is what i understand about

`linkedSignals`: For scenarios with dynamic or evolving dependency graphs, especially when conditions influence which signals are accessed.
`computed`: For scenarios with static and predictable dependencies, where simplicity and performance optimisation are key.

But as per these the computed signals and linkedSignals gives the same output.

Example code:

```
import { CommonModule } from '@angular/common';
import { Component, computed, linkedSignal, signal } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  imports: [CommonModule],
  styleUrl: './app.component.scss'
})
export class AppComponent {
  title = 'v-19';
  isDynamic = signal(true);
  signalA = signal(10);
  signalB = signal(20);

  // Using linkedSignal
  dynamicResult = linkedSignal(() => {
    return this.isDynamic() ? this.signalA() : this.signalB();
  });

  // Using computed
  staticResult = computed(() => {
    return this.isDynamic() ? this.signalA() : this.signalB();
  });

  constructor() {

    setTimeout(() => {
      this.isDynamic.set(false);
    }, 5000);
  }
}

```
### Code Explanation:  
The above code demonstrates the dynamic behavior of `linkedSignals` and `computed` signals. It uses a boolean signal called `isDynamic`, along with two integer signals, `signalA` and `signalB`. The goal is to dynamically determine the result:  
- When `isDynamic` is `true`, `linkedSignal` should dynamically provide `signalA` as the result.  
- The expectation is that `linkedSignals` can handle dynamic and complex signals more effectively, whereas `computed` should not behave the same way.

### Expected Outcome:  
Only the `linkedSignal` (i.e., `dynamicResult`) should update when there is a change in the value of `isDynamic`.

### Actual Outcome:  
Both `linkedSignals` and `computed` behave identically in this scenario, and the result updates for both when `isDynamic` changes.

### Question:  
If both `linkedSignals` and `computed` behave the same way in this case, what is the key difference between them? When should each be used effectively?

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-yambyv?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
### Expected Outcome:  
Only the `linkedSignal` should update when there is a change in the value of dynamic value.

### Actual Outcome:  
Both `linkedSignals` and `computed` behave identically in this scenario, and the result updates for both when dynamic value changes.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 19.0.2
Node: 20.14.0
Package Manager: npm 10.7.0
OS: darwin arm64

Angular: 18.0.3
... core

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1900.2 (cli-only)
@angular-devkit/core         19.0.2 (cli-only)
@angular-devkit/schematics   19.0.2 (cli-only)
@schematics/angular          19.0.2 (cli-only)
```

### Anything else?

Please let me know if I am missing something or misunderstanding the concept.

**Comment by alxhub** [comment]
I'd recommend asking questions like this on the [Angular Community Discord](https://discord.com/invite/angular) - the issue tracker is more for bug reports, feature requests, etc.

The difference between `linkedSignal` and `computed` has nothing to do with dynamic vs static dependencies. `linkedSignal` is a `computed` that can change away from its computed value, but will recompute the next time its source changes. As a first approximation, `linkedSignal(() => value())` is roughly equivalent to `computed(() => signal(value()))`: a computed that produces a new signal on every upstream change.
