### ISSUE TITLE
warn the user when defining `#` binding has capitals

### ISSUE THREAD

**Issue by rkirov** [angular/angular#591]
`<input #fooBar> {{fooBar.value}}` will fail because html attributes are case insensitive and the actually bound variable is `foobar`. However, currently the error thrown is not descriptive. 

Option 1) detect such bindings during Template loading.
Option 2) print the current context when `{{fooBar}}` evaluation fails, so the user can see `foobar` inside.

**Comment by mhevery** [comment]
dup of #1447
