### ISSUE TITLE
ability to remove attribute in production

### ISSUE THREAD

**Issue by robertIsaac** [angular/angular#59103]
### Description

in a lot of cases we add data-test-id for unit test and e2e to be able to catch exact element
but all of these attribute end up in production build

### Proposed solution

add one more more in angular.json file to specify a list of attribute that should be removed in some configuration (e.g. production)
and maybe by default for new projects to have data-test-id in this list (what about data-testid?)

### Alternatives considered

creating custom script that uses using regular expression to do replace in all files and run it before the compiler
it's error prune and harder to maintain between projects since if there is a bug, I need to fix it for every project (I'm maintaining 10+ Angular projects and almost all of them have them)

**Comment by pkozlowski-opensource** [comment]
Thnx for the suggestion @robertIsaac but we will pass on it - mostly because Angular is a very generic framework and you are asking for a feature that is very specific to a certain testing setup.
