### ISSUE TITLE
add async validators to a control throws an error (alpha.54)

### ISSUE THREAD

**Issue by jorgeunimicro** [angular/angular#5910]
```typescript
function test2(control) {
    return new Promise((resolve)=>{
        setTimeout(()=>{
            resolve(null);
        },1000);
    });
}

@Component({
    selector: 'form-demo',
    template: `
        <h1>Form demo</h1>
        <form>
            <input [ngFormControl]="myControl" />
        </form>
    `
})
export class FormDemo {
    myControl;
    constructor() {
        this.myControl = new Control("somevalue",Validators.required,test2); //that fails
    }
}
```

That will throw an error:
```
TypeError: Cannot read property 'create' of undefined
    at Function.ObservableWrapper.fromPromise (vendor.js?v=1450191928868:38918)
    at toObservable (vendor.js?v=1450191928868:41074)
    at Control.AbstractControl._runAsyncValidator (vendor.js?v=1450191928868:41213)
    at Control.AbstractControl.updateValueAndValidity (vendor.js?v=1450191928868:41192)
    at new Control (vendor.js?v=1450191928868:41292)
    at new UniFormDemo (uniFormDemoComponent.ts:45)
    at vendor.js?v=1450191928868:25978
    at Injector._instantiate (vendor.js?v=1450191928868:36487)
    at Injector._instantiateProvider (vendor.js?v=1450191928868:36429)
    at Injector._new (vendor.js?v=1450191928868:36419)
```

That is happening in alpha.54 it works fine in alpha.53

**Comment by ericmartinezr** [comment]
@jorgeunimicro this seems to be related to Rx. That stacktrace takes you to this code

```
var fromPromise_1 = require("rxjs/observable/fromPromise"); // This is returning undefined in your case
//....
ObservableWrapper.fromPromise = function(promise) {
     return fromPromise_1.PromiseObservable.create(promise);
};
```
This [plnkr](http://plnkr.co/edit/ekxcgnLg2EIT5HKf9baV?p=preview) with your code is working for me, although I couldn't reproduce your error (if I remove RxJS the app doesn't load at all).

Did you add Rx? Are you using some bundling system?

**Comment by jorgeunimicro** [comment]
I have RxJS in my project but not loaded in the script tags. I load Rx when I need to use it. I thought that angular2 requires RxJS when it needs it. Thank you for your help @ericmartinezr

**Comment by ericmartinezr** [comment]
@jorgeunimicro actually you don't need the full Rx. It's more a plnkr thing. You can add this config to your file

```
System.config({
    map: {
      rxjs: 'node_modules/rxjs'
    },
    packages: {
      rxjs: { defaultExtension: 'js' }
    }
}
```
This way you can skip adding the full Rx in your html, and it will automatically match the internal paths angular2 uses to the files in node_modules.

**Comment by jorgeunimicro** [comment]
@ericmartinezr I have that configuration and if I see the log, fromPromise.js is downloaded and every Rx files needed. That's why I ask if I should explicitly load Rx before my app.

**Comment by jorgeunimicro** [comment]
@ericmartinezr it worked whe I added require.resolve('rxjs/bundles/Rx.min.js') to my vendors bundle
