### ISSUE TITLE
@angular/elements - Values passed as input (via @Input) are not available on ngOnInit of a custom element component

### ISSUE THREAD

**Issue by jeanpaulattard** [angular/angular#59107]
### Which @angular/* package(s) are the source of the bug?

elements

### Is this a regression?

No

### Description

_Please note that the following bug is available on v17 / 18 / 19._

Input values passed via the `@Input` decorator to components that have been transformed into custom elements  are not available within the `ngOnInit` lifecycle hook of the transformed component. 

To replicate
- Create a very basic component that accepts an `@Input` value. (could be standalone or not, doesn't matter)
- Use the utilities exposed by the `@angular/elements` library to create a custom element from the created component
- Register the created element with the dom via `customElements.define(...)`
- Access the created custom element from another component while passing the values via variables (not static strings).
- When the custom element is created, and `ngOnInit` is fired, the values that are accepted as input are `undefined`.

This seems to be an odd behaviour since there is no feature parity between Angular Components and Angular Elements. In the first, any inputs passed to the component are available, wheres for Angular Elements, they aren't.

it is also important to note that if the angular element is rendered *before* the element has been registered with the DOM registry, the input variables are available within the `ngOnInit` lifecycle hook.

Both of the scenarios, ie. when input variables are undefined, and when not, are showcased in the linked stackblitz repo.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-6l4edbrm?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.2.12
Node: 20.11.1
Package Manager: npm 10.8.1
OS: darwin arm64

Angular: 18.2.13
... animations, common, compiler, compiler-cli, core, elements
... forms, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.12
@angular-devkit/build-angular   18.2.12
@angular-devkit/core            18.2.12
@angular-devkit/schematics      18.2.12
@angular/cli                    18.2.12
@schematics/angular             18.2.12
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.10
```

**Comment by JoostK** [comment]
This does indeed seem like unexpected behavior, for which an existing issue exists in #48303.
