### ISSUE TITLE
2.0.0-alpha.54 has no 'angular2/bootstrap' on code.angularjs.org

### ISSUE THREAD

**Issue by wkwiatek** [angular/angular#5911]
I've just tried to update and play with plunker on most recent version and it turned out that it cannot load `bootstrap` from `angular2/bootstrap`. I cannot see anything like `System.register` for module like that in the source.

Here is the plunker: http://plnkr.co/edit/pwE8ODxhqsGBRIJYAbh0?p=preview

Everything works fine when using with TS in projects.

**Comment by ericmartinezr** [comment]
@wkwiatek the path for bootstrap is now `angular2/platform/browser`

**Comment by pkozlowski-opensource** [comment]
The proper import path is `import {bootstrap} from 'angular2/platform/browser';`
Also see https://github.com/angular/angular/issues/5905
