### ISSUE TITLE
`/index.html` WITH query parameters/params does not match any routes

### ISSUE THREAD

**Issue by olfek** [angular/angular#59113]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

`/index.html` resolves to `/`
`/index.html?foo=bar` throws an error:
```
ERROR Error: NG04002: Cannot match any routes. URL Segment: 'index.html'
```

### Please provide a link to a minimal reproduction of the bug

https://github.com/user-attachments/files/18042548/angular-index.html-with-query-params-bug.zip

### Please provide the exception or error you saw

```true
ERROR Error: NG04002: Cannot match any routes. URL Segment: 'index.html'
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 19.0.4
Node: 22.11.0
Package Manager: npm 10.9.0
OS: win32 x64

Angular: 19.0.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.4
@angular-devkit/build-angular   19.0.4
@angular-devkit/core            19.0.4
@angular-devkit/schematics      19.0.4
@angular/cli                    19.0.4
@schematics/angular             19.0.4
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0
```

### Anything else?

Same thing seen by someone else in 2020 - https://stackoverflow.com/q/62259234

**Comment by Nico-Patch** [comment]
Hi,

I’m not sure if I’m using the router correctly, but 

I use only one route :

`export const routes: Routes = [
  {
    path: '',
    component: MyComponent
  }
];`

My app opens correctly in an iframe :

`<iframe id="my_id" src="mypath/fr/index.html"></iframe>`

But I have this error when I use queryParam :  error: de: NG04002: 'index.html'

`<iframe id="my_id" src="mypath/fr/index.html?myParam=something"></iframe>`

`"@angular/animations": "^18.2.12",
    "@angular/common": "^18.2.12",
    "@angular/compiler": "^18.2.12",
    "@angular/core": "^18.2.12",
    "@angular/forms": "^18.2.12",
    "@angular/platform-browser": "^18.2.12",
    "@angular/platform-browser-dynamic": "^18.2.12",
    "@angular/router": "^18.2.12",`
