### ISSUE TITLE
Remove RxJS bundle license-patching script when included in bundles

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#5912]
Blocked by https://github.com/ReactiveX/RxJS/issues/1067

* remove `tools/code.angularjs.org/add-license-to-rx.js`
* edit `tools/code.angularjs.org/publish.sh` to not execute `add-license-to-rx.js`

**Comment by pkozlowski-opensource** [comment]
Obsolete as we no longer bundle RxJS
