### ISSUE TITLE
withComponentInputBinding() includes url parameter "?parm=example"

### ISSUE THREAD

**Issue by gcrockenberg** [angular/angular#59137]
### Command

other

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

With withComponentInputBinding() enabled

`readonly routeValue = input<string>()`

includes the url parameters following the routeValue.

### Minimal Reproduction

1. Enable `withComponentInputBinding()`
2. Create a route with a parameter, for example: `path: 'test/:routeValue'`
3. Ensure component has matching input, for example: `readonly routeValue = input<string>()` 
4. Navigate to the page with url containing parameters, for example: `http://localhost:4200/test/test-value?parm=example`
5. The input is incorrectly set to "test-value?parm=example" when it should be "test-value"

### Exception or Error

```text

```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 19.0.3
Node: 18.20.3
Package Manager: npm 10.7.0
OS: win32 x64

Angular: 19.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.3
@angular-devkit/build-angular   19.0.3
@angular-devkit/core            19.0.3
@angular-devkit/schematics      19.0.3
@schematics/angular             19.0.3
ng-packagr                      19.0.1
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0
```

### Anything else relevant?

Hope this helps.

**Comment by alxhub** [comment]
Hi @gcrockenberg,

Can you please include a runnable version of your reproduction - Stackblitz is great for this sort of thing.

**Comment by gcrockenberg** [comment]
Issue was the url parameter got encoded into the url via some other logic (e.g. `%3Ft%3D2`) which made it become part of the route parameter string instead of remaining a url parameter (e.g. `?t=2`).

**Comment by gcrockenberg** [comment]
Just worked on that and identified the issue.  My url parameter got encoded into the url via some other logic (e.g. `%3Ft%3D2`) which made it become part of the route parameter string instead of remaining a url parameter (e.g. `?t=2`).

I closed it with explanation on GitHub.

________________________________
