### ISSUE TITLE
missing page

### ISSUE THREAD

**Issue by JuicyPasta** [angular/angular#59139]
### Describe the problem that you experienced

dependency injection guide referenced from https://angular.dev/guide/ngmodules/overview#ngmodule-providers is not there

### Enter the URL of the topic with the problem

https://angular.dev/guides/di

### If this problem caused an exception or error, please paste it here

```true

```

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true

```

### Provide any additional information here in as much as detail as you can

```true

```

**Comment by RafaelJCamara** [comment]
I think the correct page might be:
https://angular.dev/guide/di/dependency-injection

Instead of:
https://angular.dev/guides/di

**Comment by elgui1886** [comment]
Hi, is this issue still open? Can't find the problem in the docs
