### ISSUE TITLE
signal-input-migration should watch out for re-assigning issues

### ISSUE THREAD

**Issue by Gerandon** [angular/angular#59135]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Previously Input decorators were not readonly mandatorily.
I know it's not the best practice, but there could be special cases when we had to override the value of the input.

Not the best example, but illustrates the problem:
```typescript
@Input() public id: string;
@Input() public name = 'my-component';
ngOnInit() {
    this.id = this.id || this.name;
}
```
Using the migration api, the following will be the output:
```typescript
public readonly id = input.required<string>();
public readonly name = input.required<string>();
ngOnInit() {
    this.id = this.id || this.name;
}
```

There are 2 problems (or lets call it questions for now) with it for me:
- My input (even if it should) was not readonly, so i suppose the transformed signal form should not be that either.
- Migration did not do anything with the reassigning part

So basically it enforces me to refactor my code.

As far as I know theres no simple way for an InputSignal to be overwritten (thats why its readonly I assume).

Shouldn't it work like the migration "partially" migrates my code, so where it could, switches to signal forms, but where it causes problems, or makes breaking changes, leaves them as they were?

### Please provide the exception or error you saw

```true

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 19.0.4
Node: 20.18.0
Package Manager: npm 10.8.2
OS: darwin x64

Angular: 19.0.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.4
@angular-devkit/build-angular   19.0.4
@angular-devkit/core            19.0.4 (cli-only)
@angular-devkit/schematics      19.0.4
@angular/cdk                    19.0.2
@angular/cli                    19.0.4
@angular/material               19.0.2
@schematics/angular             19.0.4
ng-packagr                      19.0.1
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0
```

**Comment by JoostK** [comment]
What mode was used to migrate? There's  a "best effort mode" that forces various rewrites even if that would result in breakages. Assignments into inputs are generally considered by the migration to mark an input as incompatible, but this may be ignored in best effort mode.

**Comment by Gerandon** [comment]
> What mode was used to migrate? There's a "best effort mode" that forces various rewrites even if that would result in breakages. Assignments into inputs are generally considered by the migration to mark an input as incompatible, but this may be ignored in best effort mode.

Ah, guess you're right. I was stupid. At first, I thought I was running the "no breaking changes" mode, but after your comment ha dto recheck and with that, works like expected!

Thank you and sorry again :D 
Closing the issue :)
