### ISSUE TITLE
Form $submitted (ng-submitted) is incorrectly triggering when elements are dynamically added within the <form> tags

### ISSUE THREAD

**Issue by Quirksmode** [angular/angular#5913]
I have a form setup and inside it is a Content Block Editor which allows you to Dynamically add a set of blocks (e.g. Text, Video, Image). The bug occurs when I try to add a block, the $submitted triggers, even when there is not a submit button on the page. I have created a fiddle to show the problem. Click to add any block and you will see the issue:

http://plnkr.co/edit/6CsUgumyDNcWaNmsWJIC?p=preview

This seems to affect all versions of Angular from 1.2 onwards.

**Comment by ericmartinezr** [comment]
@Quirksmode this repo is for ng2, you are looking for this one https://github.com/angular/angular.js :D

**Comment by Quirksmode** [comment]
Ah crap, many thanks, will move it there :-)
