### ISSUE TITLE
@defer causes rollup error in v19

### ISSUE THREAD

**Issue by joewIST** [angular/angular#59136]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

After upgrading to v19, we are getting errors during bundling (coming from the rollup package used by Vite). This occurs when standalone components are a) wrapped inside a @defer block and b) referenced in a component's imports array. It looks like something has happened which causes rollup to try to add the component twice.

With @defer :
![Image](https://github.com/user-attachments/assets/c45754f4-af40-40d9-ad55-9e31a0b607e9)

When I remove the @defer blocks, the code builds as before.

### Please provide the exception or error you saw

```true
dist/libs/neve/ui/page/smart-generation/esm2022/portfolio-commentary/page-smart-generation-portfolio-commentary.component.mjs (172:704): Duplicate argument name "MoleculeAiCardComponent"
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 19.0.4
Node: 20.13.1
Package Manager: yarn 4.5.1
OS: win32 x64

Angular: 19.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.4
@angular-devkit/build-angular   19.0.4
@angular-devkit/core            19.0.4
@angular-devkit/schematics      19.0.4
@angular/build                  19.0.4
@angular/cdk                    19.0.2
@angular/cdk-experimental       19.0.2
@angular/cli                    19.0.4
@angular/material               19.0.2
@schematics/angular             19.0.4
ng-packagr                      19.0.1
rxjs                            7.8.1
typescript                      5.6.3
webpack                         5.97.1
zone.js                         0.15.0
```

**Comment by e-oz** [comment]
Works fine for me. Curious to see the repro.

**Comment by joewIST** [comment]
Hi, I'm not entirely sure how to provide a minimum repro without providing our entire application. Do you have any advice?

For now, I am going to remove all defer blocks and see if the app builds. I'd be interested to see if anyone else is having the same issues.

**Comment by joewIST** [comment]
I am able to provide more context.

The issue seems to arise in situations where the same component is wrapped inside a defer block multiple times in the same component. 

@e-oz does it still work for you if you add an additional defer block, with the same component inside it, but with a different "when" condition ?

I can of course update my code to remove these duplicate defers (in the whole code base, there were only two examples), but not sure if it's worth flagging as an issue.

Thanks

**Comment by alan-agius4** [comment]
A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by joewIST** [comment]
OK I will do that if/when I get a chance. 

Interested to hear any thoughts on the fact this is only occurring on separate defer blocks that contain the same component.

**Comment by JeanMeche** [comment]
Without any repro this is not actionable to us so we'll close this. If you still have the issue and can provide a narrowed down repro, feel free to file a new issue.

**Comment by joewIST** [comment]
@JeanMeche The repro can be achieved by adding 2+ defer blocks (containing the same component inside them) within the same template. Not sure that needed an entire app to reproduce...
