### ISSUE TITLE
test: run E2E tests against System and UMD bundles

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#5915]
Our e2e tests currently use the `System.register` version of bundles. Since we've added UMD bundles as well, we should run E2E tests with UMD. I don't expect this will be a simple task.

I'm going to start on this today.

**Comment by jeffbcross** [comment]
Wasn't able to get to this today :). Unassigning since I'm going to be OOO for a bit.

**Comment by juliemr** [comment]
@jeffbcross we do this now, right?

**Comment by vicb** [comment]
obsolete
