### ISSUE TITLE
Feature: Allow the type of "error" in HttpErrorResponse to be set using generics

### ISSUE THREAD

**Issue by reuse-ay** [angular/angular#59179]
### Which @angular/* package(s) are relevant/related to the feature request?

common

### Description

Now type of `error` property in [HttpErrorResponse](https://angular.jp/api/common/http/HttpErrorResponse?tab=api) is `any`.
It is convenient to use generics.

### Proposed solution

Allows the use of generics.
```
class HttpErrorResponse<T=any> extends HttpResponseBase implements Error {
  readonly name: "HttpErrorResponse";
  readonly message: string;
  readonly error: T;
  readonly ok: false;
  readonly override headers: HttpHeaders;
  readonly override status: number;
  readonly override statusText: string;
  readonly override url: string | null;
  readonly override type: HttpEventType.ResponseHeader | HttpEventType.Response;
}
```

If the default is any, compatibility will be maintained, right?

### Alternatives considered

Now I don't have ideas.

**Comment by JoostK** [comment]
Please see #45336 for an earlier discussion on this topic, with https://github.com/angular/angular/issues/45336#issuecomment-1066062933 still being the case today.
