### ISSUE TITLE
Avoid TS7006 with fat arrow calls: Parameter implicitly has an 'any' type 

### ISSUE THREAD

**Issue by Toadskin** [angular/angular#5917]
I set noImplicitAny=true in my tsconfig.json to enforce type declarations.  

Compilation fails when adding an HTTP call:

 http.get('/api/cats')
            .map(res => res.json()) // error on this line for implicit 'any' on res
            .subscribe(data => this.cats = data.cats) // error on this line for implicit 'any' on data

I'm fine adding res:any and data:any but that syntax generates an error: TS1005: ',' expected.  How to resolve this without setting noImplicitAny=false (that fixes it and the code compiles and runs fine)?

**Comment by vicb** [comment]
Have you tried `(res: any) => ...` ?

**Comment by Toadskin** [comment]
Thanks, that worked.  You would think the precedence of the colon in foo:bar would be sufficient.  Maybe it is and the compiler will handle that unassisted in the future?  Definitely feeling good about turning on the no-implicit switch before there is a mountain of code.

**Comment by JashaadGaines** [comment]
Using the angular tutorial I got the same error in hero-detail.component.ts. 

Error- TS7006: Parameter 'hero' implicitly has an 'any' type.
Solution - explicitly declare a type or use "any" type in function param. 
<Example> 
`this.heroService.getHero(id)  .then(hero` => this.hero = hero); `

I changed it to: 

`this.heroService.getHero(id)   .then((hero:Hero) => this.hero = hero); 
`

**Comment by flgx** [comment]
@vicb That save my life dude :). Thank you.

**Comment by Geraldinecs** [comment]
another surviving. Thanks you

**Comment by ayoubkhan558** [comment]
This code was showing error 
`map(prevVideos => {
        let videos = prevVideos.map(
          video => {
            return {
              id: video.id,
              title: video.snippet.title,
              thumbnail: video.snippet.thumbnails.medium.url
            }
          });
        //console.log(videos)
        return videos;
      }),`

But this solved my problem

`map(prevVideos => {
        let videos = prevVideos.map(
          (video: any) => {
            return {
              id: video.id,
              title: video.snippet.title,
              thumbnail: video.snippet.thumbnails.medium.url
            }
          });
        //console.log(videos)
        return videos;
      }),`

**Comment by quyennguyenvan** [comment]
@vicb you save my time, thanks bro
