### ISSUE TITLE
Named Routes

### ISSUE THREAD

**Issue by RSamaium** [angular/angular#59182]
### Which @angular/* package(s) are relevant/related to the feature request?

router

### Description

Add support for named routes in Angular Router, similar to Vue Router's implementation, to improve route management and navigation.

Currently, Angular Router requires using URLs or paths for navigation. Named routes would provide:

- More maintainable route definitions
- Type-safe navigation
- Easier refactoring when URLs change
- Better developer experience

### Route Definition
```typescript
const routes: Routes = [
  {
    path: 'products',
    name: 'products.list',  // New property
    component: ProductListComponent
  },
  {
    path: 'products/:id',
    name: 'products.detail',
    component: ProductDetailComponent
  }
];
```

### Navigation Usage

```typescript
// Current way
router.navigate(['/products', id]);

// Proposed way
router.navigateByName('products.detail', { params: { id: 123 } });
```

### Router Link Usage
```typescript
// Current way
<a [routerLink]="['/products', id]">Product</a>

// Proposed way
<a [routerLinkByName]="'products.detail'" [params]="{ id: 123 }">Product</a>
```

### Route Guards Integration
```typescript
{
  path: 'products',
  name: 'products.list',
  component: ProductListComponent,
  canActivate: [(route) => {
    // route.name would be available here
    console.log(route.name); // 'products.list'
    return true;
  }]
}
```

### Route Resolution
```typescript
// Resolve route by name
const route = router.resolveRouteName('products.detail', { 
  params: { id: '123' } 
});
console.log(route.url); // '/products/123'
```

### Route State Management
```typescript
// Get current route name
const currentRouteName = router.getCurrentRouteName();

// Check if current route matches name
const isProductRoute = router.matchRouteName('products.*');
```

### Alternatives considered

N/A

**Comment by jnizet** [comment]
AFAIK, the reason routes have no name is that it would make it impossible to navigate, by name, to a lazy-loaded route, since by definition, those routes are unknown at the time of the navigation.

**Comment by JeanMeche** [comment]
It's a nice idea to have but unfortunately this is incompatible with lazy-loaded routes. 

See #13416 and #24775 that previously requested that feature.
