### ISSUE TITLE
Using loadChildren and loadComponent for lazy loading together in AppRoutinModule

### ISSUE THREAD

**Issue by magioloro** [angular/angular#59186]
### Which @angular/* package(s) are the source of the bug?

core, router

### Is this a regression?

No

### Description

I am using Angular 18 with modules as well as standalone components. 

In my AppRoutingModule I want to lazy load my standalone components as well as my modules with with `loadComponent() `and `loadChildren().`
But if I navigate to a lazy component route /lazyComponent and then refresh the page, after the page refreshes, the component is not loaded.
I use `bootstrapModule()` in main.ts.

ALso If I use  

```
{
        path: 'lazyComponent',
        component: LazyComponent
},
```
without lazy loading, refreshing the page doe not load the component.

Is it even possible or do i have to transform my modules to standalone components, too and then using `bootstrapApplication()`?

### Please provide the exception or error you saw

```true

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.2.12
Node: 18.20.2
Package Manager: yarn 3.6.1
OS: win32 x64

Angular: 18.2.13
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1802.12
@angular-devkit/build-angular      18.2.12
@angular-devkit/core               18.2.12
@angular-devkit/schematics         18.2.12
@angular/cdk                       18.2.14
@angular/cli                       18.2.12
@angular/material                  18.2.14
@angular/material-moment-adapter   <error>
@schematics/angular                18.2.12
ng-packagr                         18.2.1
rxjs                               7.8.1
typescript                         5.4.5
zone.js                            0.15.0
```

**Comment by jnizet** [comment]
Hi @magioloro 

Without any code, it's impossible to understand exactly what you're doing. You should ask this as a question on the Angular discord or stackoverflow, with a minimal reproduction provided. And if it turns out that it could be an Angular issue, you should provide the minimal reproduction in this issue.

**Comment by JeanMeche** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).
