### ISSUE TITLE
NgFor blocks screen for 5 sec with medium data sets

### ISSUE THREAD

**Issue by Luchillo** [angular/angular#5921]
Hi, i have a simple list of names with 240 of them, the ngFor directive in angular 2 tries to show them all at once which as you would imagine generates a performance drawback, the issue is that it's blocking the screen for 5 secs!

In angular 1, angular material had virtual repeat that only instantiated how many items it could show +1 and in scroll it just used the one that left the screen to show the next one that should be showing, that way it would avoid instantiating a whole lot of items in DOM, thus giving a better performance.

Angular material is soo far to be implemented in angular 2, will angular staff give a solution to this?

**Comment by pkozlowski-opensource** [comment]
@Luchillo this sound odd: simple list of 240 items shouldn't cause any performance problems? Could you please demonstrate this issue using plunker or a similar tool?

**Comment by Luchillo** [comment]
Ok this performance issue dropped to half second in Angular.beta, i'll try to put a plunker together.

**Comment by pkozlowski-opensource** [comment]
Closing as we don't have reproduce scenario.
