### ISSUE TITLE
Include licenses in the UMD bundles

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#5926]
We had this in the system bundles. Need a @license JSDoc comment including the license body, for any licensed work included in a bundle.

**Comment by pkozlowski-opensource** [comment]
@alexeagle we don't bundle any non-ng2 stuff in ng2 bundles so is it only about the ng2 license? Or is there more to this issue than this? I'm asking since I'm not sure we've got ng2 license added to all bundles.

**Comment by alexeagle** [comment]
+ @rkirov who was looking at this as we synced this week.
We do bundle rxjs in the current UMD bundle, and we include zone.js and reflect-metadata in the sfx bundle.
We didn't see any license in the newest angular2.umd.dev.js ...

**Comment by pkozlowski-opensource** [comment]
@alexeagle with the code in master we shouldn't have RxJS in _any_ of the bundles. UMD shouldn't have RxJS, see: https://github.com/angular/angular/blob/2a2f9a9a196cf1502c3002f14bd42b13a4dcaa53/gulpfile.js#L1147 If they still do this is a bug which we should fix.

SFX bundles are gone, so I'm not sure which one are you referring to.

**Comment by rkirov** [comment]
@pkozlowski-opensource Correct, we just need the ng2 licence in the ng2.umd bundle.

**Comment by pkozlowski-opensource** [comment]
Bundles get a proper license now.
