### ISSUE TITLE
Adjusting the `ProviderToken` to `contentChildren`

### ISSUE THREAD

**Issue by qbr-dude** [angular/angular#59270]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

I wanted to do **general form management**: there is a component where it is pushed. Controls (**CVA**) are inserted through **`ng-content`** (marked through a directive), automatic button processing is immediately performed, etc. So I decided to get the components through **`contentChildren`** to link to the form, but it didn't work out. I tried different ways, but nothing.

**In general, the idea is to access all the components through a directive search.**

If search only through the directive, then the result will be only the directive. Searching through the base class does not work (more on this below). In general, I had to look at the source code:

1) I decided to take a look at why there is _no search through the base class_. [**I got to here**](https://github.com/angular/angular/blob/main/packages/core/src/render3/di.ts#L700-L707), the tokens are compared here, and the values are really the ones I need. But the class token is compared with the inherited one (which is the target here), so the verification fails. Maybe there is an idea to add an additional basic check?

2) And then I started going back up, and I got to ([**first here**](https://github.com/angular/angular/blob/main/packages/core/src/render3/query.ts#L257-L268), [**then here**](https://github.com/angular/angular/blob/main/packages/core/src/render3/query.ts#L503)], and I thought, why not pass **the `ProviderToken` array**. But **`contentChildren`** expects a single token, so I made a type cast via unknown. **And it worked**. [**Here is an example**](https://stackblitz.com/edit/stackblitz-starters-vzdztjvv?file=src%2Fapp%2Fform%2Fform.component.ts).

Therefore, it looks like **the type needs to be adjusted**. 
Or there is some other way, but I've tried, probably everything. Maybe you didn't think of such a thing, but I do not know why.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-vzdztjvv?file=src%2Fapp%2Fform%2Fform.component.ts

### Please provide the exception or error you saw

```true

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 19.0.0
Node: 18.20.3
Package Manager: npm 10.2.3
OS: linux x64

Angular: 19.0.0
... animations, build, cli, common, compiler, compiler-cli, core
... forms, platform-browser, router

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1900.0
@angular-devkit/core         19.0.0
@angular-devkit/schematics   19.0.0
@schematics/angular          19.0.0
rxjs                         7.8.1
typescript                   5.6.3
zone.js                      0.15.0
```

**Comment by JoostK** [comment]
This is working as designed; the predicate matches _tokens_ by equality, it does not do `instanceof` checks.

The typical pattern in such case is to let the subtypes provide themselves as their base class token using an `useExisting` provider:

```ts
@Component({
  providers: [{provide: BaseClass, use existing: ExampleCmp}]
})
export class ExampleCmp extends BaseClass {}
```
