### ISSUE TITLE
Add new sematic html support - dialog element support + others

### ISSUE THREAD

**Issue by mayeedwin** [angular/angular#59283]
### Description

Additon of these new elements as frequent updates will be great.

### Proposed solution

```html
<dialog>
  <h1>Test Maye</h1>
  <p>product-details works!</p>
</dialog>
```

### Alternatives considered

- Custom component 
- Third party components 
- Angular CDK

**Comment by e-oz** [comment]
Works fine: https://stackblitz.com/edit/stackblitz-starters-qnkylvxa?file=src%2Fmain.ts

**Comment by Totati** [comment]
Not sure what the native HTMLDialogElement has to do with Angular. 🤔 Could you explain it more, please.

**Comment by JeanMeche** [comment]
@mayeedwin Could you explain what is missing today, or what doesn't work for you today. Thank you.

**Comment by mayeedwin** [comment]
I tried to use the dialog element in an angular component, it does not work at all. I have to either fallback to the CDK, custom dialog component or a ui library cc @JeanMeche, @Totati

**Comment by mayeedwin** [comment]
Oh, I see, the `open` attribute was missing, thanks @e-oz
