### ISSUE TITLE
HttpInterceptor not working

### ISSUE THREAD

**Issue by olavivaino** [angular/angular#59294]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

I composed minimal angular 19 app where HttpInterceptor calls are not logged. Here I assume that request made with fetch() are supposed to be intercepted as well.
It seems that httpInterceptor constructor is not logged either so it may be a DI issue instead? Interceptor DI was made based on doc https://angular.dev/guide/http/interceptors#di-based-interceptors

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-giih8fmc

### Please provide the exception or error you saw

```true

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Stackblitz environemnt, not sure what node ver is used there
"@angular/build": "^19.0.0",
    "@angular/cli": "^19.0.0",
    "@angular/compiler-cli": "^19.0.0",
    "typescript": "^5.6.3"
```

**Comment by JeanMeche** [comment]
The Interceptors are only invoked if your rely on the `HttpClient`.
