### ISSUE TITLE
Severe issue with URLs containing parentheses in SSR mode

### ISSUE THREAD

**Issue by younes-chaoui** [angular/angular#59304]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

This issue needs immediate attention.

Any Angular application using SSR can crash when a URL contains parentheses followed by any character.

For example : "/product(3)"

The server crashes with the following exception:
ERROR RuntimeError: NG04002: Cannot match any routes. URL Segment: '3'

I see 2 problems here : 
1 - The exception.
2- Why to crash the whole prod if there is an exception.

### Please provide the exception or error you saw

```true
ERROR RuntimeError: NG04002: Cannot match any routes. URL Segment: '3'
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.5
Node: 20.4.0
Package Manager: npm 9.7.2
OS: linux x64

Angular: 17.3.5
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.5 (cli-only)
@angular-devkit/build-angular   17.3.5
@angular-devkit/core            17.3.5 (cli-only)
@angular-devkit/schematics      17.3.5
@schematics/angular             17.3.5
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.4
```

**Comment by JeanMeche** [comment]
Hi,

Parenthesis aren't considered valid characters in urls, you need to escape them. This is true in both CSR and SSR apps.
