### ISSUE TITLE
minLength, maxLength validators does not work on number type value of control and does not throw error

### ISSUE THREAD

**Issue by mehedihasansjs** [angular/angular#59306]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

I have used a control which returns value `number`. for validating max and min length, I have used `Validators.minLength` and `Validators.maxLength` also used `Validators.required`. Required returns error object (ValidatorErrors) perfectly, but minlength and maxlength is silent. I was not sure what I was doing wrong.

Later discovered, I can not use `Validators.minLength` and `Validators.maxLength` in a number. Good.

But at least compiler should throw error or warning in this case that we can not use or the use of those validators is not appropriate in this case.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular Version: 17.3.7
```

**Comment by JeanMeche** [comment]
This works the same as the HTML standard. Please see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#maxlength.

**Comment by mehedihasansjs** [comment]
> This works the same as the HTML standard. Please see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#maxlength.

But can't angular throw any warning at least for better DX?
