### ISSUE TITLE
Setting form null during creation breaks chain of validity updates

### ISSUE THREAD

**Issue by Vermilion755** [angular/angular#59309]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

I noticed that depending on how I build my reactive form, the ancestor forms will not track the child form validity. If I create my form all at once... that is to say I create all the child forms in the object at the same time, the validity tracking works. If instead, I set one child form to null, then on the next line of code I set that null property to a new child form, the validity tracking is broken. 

In the stackblitz example, I am building 3 instances of the same reactive form, but it's being built 3 times in different sets of steps as described above. To see the issue illustrated:
   1. Delete the contents of the first Test Input, which has the 'required' validator on it. You will see all 6 'valid' booleans above the input change from 'true' to 'false', because the validation issue has propagated up the chain to all the ancestor forms. Now type something into the input and again you'll see all 6 booleans change back to 'true' because the validity has propagated up the chain successfully. 
   
   2. Perform the same steps on the 2nd Test Input. Here you will see the booleans do not all update, as if the propagation is broken. Now type something into the input again and see the same 5 booleans change back to 'true'. So the base form here is not getting the update and the only difference is that I set the 'first' form to null and then created it on the next line. 
   
   3. Repeat the same steps on the 3rd Test Input and see how the propagation is further broken here, as only 3 booleans update this time now that I'm also setting the 'second' form to null and then setting it on the next line. 

Is this expected behavior? This is an ultra-simplified example. In my real use case, we create the base form but we don't have the data yet to hydrate the children forms, so we have null checks if the data isn't there and we don't create those forms yet. Later when the user performs an action and we retrieve the data from the API, we create a form on those child properties. We have a large nested form where we are highlighting things red in the UI when the form or it's children forms are invalid. So if we instead create blank children forms, we'd have to go and disable the form controls to ensure they aren't counted invalid, which is a hassle. It's much cleaner to just check null AND invalid, but it's not working due to this bug.

![Image](https://github.com/user-attachments/assets/fa6f2249-9d26-4b4b-b2ef-1aa537d93f6d)

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-9rojtqfs?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
There is no exception, just broken behavior
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 19.0.0
Node: 18.20.3
Package Manager: npm 10.2.3
OS: linux x64

Angular: 19.0.0
... animations, build, cli, common, compiler, compiler-cli, core
... forms, platform-browser, router

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1900.0
@angular-devkit/core         19.0.0
@angular-devkit/schematics   19.0.0
@schematics/angular          19.0.0
rxjs                         7.8.1
typescript                   5.6.3
zone.js                      0.15.0


  "dependencies": {
    "@angular/animations": "^19.0.0",
    "@angular/common": "^19.0.0",
    "@angular/compiler": "^19.0.0",
    "@angular/core": "^19.0.0",
    "@angular/forms": "^19.0.0",
    "@angular/platform-browser": "^19.0.0",
    "@angular/router": "^19.0.0",
    "rxjs": "^7.8.1",
    "tslib": "^2.5.0",
    "zone.js": "~0.15.0"
  },
  "devDependencies": {
    "@angular/build": "^19.0.0",
    "@angular/cli": "^19.0.0",
    "@angular/compiler-cli": "^19.0.0",
    "typescript": "^5.6.3"
  }
```

**Comment by Vermilion755** [comment]
Note, the same issue seems to occur if using a FormArray instead of the Record<string, FormGroup<IFirstLevelForm>>.

**Comment by JeanMeche** [comment]
You're getting tricked by typescript, passing `null` while building the formgroup is not supported. You should either have `strict: true` or `strictNullChecks : true`

**Comment by Vermilion755** [comment]
So then you're saying Angular has an undocumented requirement that we have strictNullChecks on, or that reactive forms can never be left null? If that's the case, the documentation needs to be updated. 

Either way, here's an updated version of the same issue, with  strictNullChecks: true and no null forms. Instead, I'm just creating a new form to replace the 2nd or 3rd level form and I still get the same problem: https://stackblitz.com/edit/stackblitz-starters-db7vn4nh?file=src%2Fmain.ts

**Comment by Vermilion755** [comment]
Ok, I'm closing this out because I found a viable workaround. This may be something to consider fixing in a future version though.

I'm calling this a workaround since nothing in the documentation seems to advise against it, but I'm sure the Angular developers will say this is how I should have been doing it all along. If you need to leave a form group null or replace it later, use addControl() and removeControl(). I haven't looked at the underlying code, but these functions must be kicking off a refresh of the form structure. If you leave a formgroup null or set it to a form group initially.... but then later use the equals sign to assign a new form group, that structure refresh seems to be skipped because the validation is broken. 

![Image](https://github.com/user-attachments/assets/cfc73827-d99b-426a-be27-801d1c212882)

**Comment by Vermilion755** [comment]
Using .setControl() works equally well so you don't have to remove the control first.
