### ISSUE TITLE
Angular 19 initial state change asynchronously scss triggering animations

### ISSUE THREAD

**Issue by muhamedkarajic** [angular/angular#59318]
### Which @angular/* package(s) are the source of the bug?

animations, Don't known / other

### Is this a regression?

Yes

### Description

Litteraly my navigation bar is transitioning when opening the page from visible to not visibe in Angular 19 while on Angular 18 it was when opening the page in the right state not visible. I had updated that project 3 4 times and never had such a issue. As if initially it has the value 'true' to show it and then transitions asynconously to 'false' which makes the UI render the animation as if the user had the navbar opened and is closing it now. 

Depending on the project this could be fatal even doe the hole app works the behavior is not acceptable and would hurt branding significantly. I wonder if the angular team is aware of such an flaw - which could be to some third party SCSS library etc? If necessry I'll see to make a reproduction of the code but hopefully this is already somehow a known issue cause I find it strange if I am the only one experiencing it.  

### Please provide the exception or error you saw

```true
No error just wrong behavior.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 19.0.6 // Here had also tested v18 its the same.
Node: 20.18.1
Package Manager: npm 10.8.2
OS: darwin arm64

Angular: 19.0.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.6
@angular-devkit/build-angular   19.0.6
@angular-devkit/core            19.0.6
@angular-devkit/schematics      19.0.6
@angular/cli                    19.0.6
@schematics/angular             19.0.6
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0
```

### Anything else?

M1 Pro macOS Monterey 12.6.6

**Comment by JeanMeche** [comment]
Hi, we would need a reproduction to understand what is happening.

**Comment by muhamedkarajic** [comment]
> Hi, we would need a reproduction to understand what is happening.

Thanks for quickly responding, I'm gonna leave one when I get to it but might take a week or two since I am gonna do some vacation. Please don't close the issue until then. I'll do my best to reproduce it.

**Comment by muhamedkarajic** [comment]
@JeanMeche hello, I have put together a minimal reproduction, everything step by step done and come to the same issues. Under the following repo https://github.com/muhamedkarajic/ng-v19-init-async-transition-bug-example you have two branches v18 when you install all package and run the project using `npm run serve` you will see a blank page, there is a small area of red on the corner but its not moving. When you go to the v19 branch and install the new packages, running the same command results then into the red circle moving.

**Comment by shannonvc** [comment]
@muhamedkarajic is this only happening with `npm run serve` and not in a production build? I think you might be running into the same HMR for styles issue as #59058 (this is enabled by default in v19)

I am not familiar with NX, but changing your `package.json` to inclide the `--no-hmr` flag to your script appears to fix the issue.

```
  "scripts": {
    "serve": "npx nx run portfolio:serve:development --no-hmr"
  },
```

See https://stackblitz.com/edit/github-zancyhgt?file=package.json

**Comment by muhamedkarajic** [comment]
@shannonvc thanks, it dose get solved when using `--no-hmr` which is cool and I'm very glad its only that.

**Comment by mmaask** [comment]
It happens in production build as well, not only ng serve.

**Comment by muhamedkarajic** [comment]
> It happens in production build as well, not only ng serve.

Ah that I did not test in my example. Did you try that in the example I linked?
