### ISSUE TITLE
Initializer of sub project isnt being called.

### ISSUE THREAD

**Issue by izzijaz** [angular/angular#59321]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

I have a root project which has its own provideAppInitializer() in providers array. Only the root Initializer gets run. Other subproject initialiser dont work. 

### Please provide a link to a minimal reproduction of the bug

No Link

### Please provide the exception or error you saw

```true
No error msg
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 19.0.6
Node: 23.4.0 (Unsupported)
Package Manager: npm 11.0.0
OS: linux x64

Angular: 19.0.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.6
@angular-devkit/build-angular   19.0.6
@angular-devkit/core            19.0.6
@angular-devkit/schematics      19.0.6
@angular/cdk                    19.0.4
@angular/cli                    19.0.6
@angular/material               19.0.4
@angular/ssr                    19.0.6
@schematics/angular             19.0.6
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.15.0
```

**Comment by JoostK** [comment]
Could you please share a runnable reproduction, as without it I have no idea what it is you're describing.

**Comment by izzijaz** [comment]
In my Root folder there is src/app.config.ts. 
i have added provideAppInitializer() to the array of providers there with code
`return of([]).pipe(
tap(()=>{console.log('ROOT INIT)})
)` 

my sub project is in root/projects/subapp/src/app.config.ts
i have added provideAppInitializer() to the array of providers there. 
`return of([]).pipe(
tap(()=>{console.log('SUB APP INIT)})
)` 

When i run bg serve and go into the page and check console. only the ROOT INIT gets displayed. SUB APP INIT doesnt log.

**Comment by bougwal** [comment]
@izzijaz you need to supply a link to a public github repository that has the issue you are describing or provide a stackblitz link https://stackblitz.com/. That would help you get a proper answer as without reproduction code it would be hard to relate to what you are facing.

**Comment by izzijaz** [comment]
https://stackblitz.com/edit/stackblitz-starters-tmzwyrbk?file=index.js

**Comment by JeanMeche** [comment]
You're never bootstraping the 2nd app. 

Your route is only pointing to a component that is located inside the sub-project.

**Comment by izzijaz** [comment]
How do i bootstrap it then before navigating to that project route.

**Comment by JeanMeche** [comment]
I invite you to look for support of the Angular Discord or stackOverflow, this not a support forum.
