### ISSUE TITLE
Arrows doesn't show on cmd terminal

### ISSUE THREAD

**Issue by kashyapkaki** [angular/angular#59336]
### Which @angular/* package(s) are the source of the bug?

compiler-cli

### Is this a regression?

Yes

### Description

When we run `ng serve` in VS code terminal, it shows arrow perfectly. 

![Image](https://github.com/user-attachments/assets/720852d9-e39a-4c63-a0ba-e10c2a92de65)

However, same command if we run in cmd command prompt, arrow is breaking.

![Image](https://github.com/user-attachments/assets/deae933a-ce03-4e7a-8389-9357a6e9dc54)

May be cmd is not supporting that symbol. Should look for another alternative? Please let me know your thoughts.

**Comment by hakimio** [comment]
Maybe just use the modern alternative [Powershell](https://github.com/PowerShell/PowerShell) instead?

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
