### ISSUE TITLE
Blank Page in Capacitor App After Upgrading to Angular 19

### ISSUE THREAD

**Issue by MahmoudMm** [angular/angular#59334]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Angular Version: 19.0.0 (latest)

Capacitor Version: 5.x

Description:

After upgrading to Angular 19, my Capacitor-based application displays a blank page when running on a physical Android device using adb. Prior to Angular 19, the same setup worked perfectly without any issues.

I initially suspected it could be related to my specific project setup. However, creating a fresh Angular project and integrating Capacitor leads to the same blank page issue, indicating it might be related to Angular 19 compatibility with Capacitor.

Steps to Reproduce:

Create a new Angular project:

```
ng new capacitor-test
cd capacitor-test
ng add @capacitor/core
npm install @capacitor/cli @capacitor/android @capacitor/ios

```
Configure the capacitor.config.ts file as follows:

```
import type { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
  appId: 'com.test.app',
  appName: 'CapacitorTest',
  webDir: 'dist/capacitor-test/browser/',
  loggingBehavior: 'debug',
  },
};

export default config;
```

Build the project:

`ng build --output-path=dist/capacitor-test/browser/`

Add the Android platform and run the app on a connected device:

```
npx cap add android
npx cap sync android
npx cap open android
```

Observe the application output on the device. A blank page appears.

### Please provide the exception or error you saw

```true

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true

```

**Comment by JeanMeche** [comment]
On what kind of Android device are you testing this ? Did you check for the browser console for any error message ?

**Comment by MahmoudMm** [comment]
It is on Pixel 9 Api 24 Emulator, when inspecting for errors in browser console it only says 
- Uncaught SyntaxError: Unexpected token (
- https://localhost/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)

pressing on Unexpected token  leads to this line in the code 
const convertFormData = async (formData) => {

it is part of that function 

`    const convertFormData = async (formData) => {
        const newFormData = [];
        for (const pair of formData.entries()) {
            const [key, value] = pair;
            if (value instanceof File) {
                const base64File = await readFileAsBase64(value);
                newFormData.push({
                    key,
                    value: base64File,
                    type: 'base64File',
                    contentType: value.type,
                    fileName: value.name,
                });
            }
            else {
                newFormData.push({ key, value, type: 'string' });
            }
        }
        return newFormData;
    };`


keep in mind it is just a standard project with no extra coding.

**Comment by JeanMeche** [comment]
Api 24 is way too old to support the default config. 

You'll need to update the `.browserslistrc` configuration. You can overwrite the default implicit one with `ng generate config browserslist`

**Comment by MahmoudMm** [comment]
Thank you for the fast reponse, I appreciate it. 

The issue has been resolved when upgrading to api 35
