### ISSUE TITLE
Nested `@if` breaks multi-slot content projection

### ISSUE THREAD

**Issue by mshavliuk** [angular/angular#59330]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

When using nested `@if` control flow blocks with content projection (`<ng-content select="...">`), the projected content does not get correctly selected compared to using a single `@if`. Instead, it falls back into the default `<ng-content />` element if one exists or doesn't get injected at all otherwise.

## Reproduction Steps
1. Create an `app-clild` component with content projection using `<ng-content select=".slot">`.
2. Create a parent component that uses this child component in two ways:
   - With a single condition: `<app-clild> @if (true) {<div class='slot'>Slot content</div>}</app-clild>`
   - With nested conditions: `<app-clild> @if (true) { @if (true) {<div class='slot'>Slot content</div>} }</app-clild>`

## Expected Behavior
Both approaches should result in identical DOM structures where the projected `<div class='slot'>Slot content</div>` is visible

## Actual Behavior
- Single condition works correctly: `Slot content` is projected
- Nested conditions fail: `Slot content` is not shown

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-xsmwxmhw?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 19.0.6
Node: 20.18.0
Package Manager: npm 10.8.2
OS: darwin x64

Angular: 19.0.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.6
@angular-devkit/build-angular   19.0.6
@angular-devkit/core            19.0.6
@angular-devkit/schematics      19.0.6
@angular/cli                    19.0.6
@schematics/angular             19.0.6
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0
```

**Comment by JoostK** [comment]
This is a known limitation of content projection, tracked in #54035.
