### ISSUE TITLE
feat(router): Include ROUTER_DIRECTIVES in ROUTER_PROVIDERS export

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#5938]
If you're going to use the router, you need the ROUTER_DIRECTIVES to use the outlets and links. Bundling ROUTER_DIRECTIVES in ROUTER_PROVIDERS would be one less thing to set up to make the directives available globally. I can submit a PR if needed.

**Comment by ericmartinezr** [comment]
@brandonroberts 

Wouldn't be better to use PLATFORM_DIRECTIVES?

```
bootstrap(..., provide(PLATFORM_DIRECTIVES, {useValue: [ROUTER_DIRECTIVES], multi: true}));
```
That's what I do to avoid specifying it in every component.

**Comment by brandonroberts** [comment]
@ericmartinezr that's what I'm suggesting. 

```js
provide(PLATFORM_DIRECTIVES, {useValue: [ROUTER_DIRECTIVES], multi: true})
```

Put that into the ROUTER_PROVIDERS array, which you normally include in your bootstrap

**Comment by ericmartinezr** [comment]
Good point. Sorry for the noise :+1:

**Comment by wardbell** [comment]
I understand and sympathize with the impulse. 

But I don't believe we should do this ... and I don't believe the team will do this ... because **the router is not part of Angular core**

The router is a separate, optional feature. Many apps won't use  a router. Some apps will choose a different 3rd party router (not yet available but easily anticipated).The router is on an independent evolutionary track with its own priorities and time-table quite apart from Angular core. We don't want to burden the core with a router and don't want to force the router to follow the core's priorities.

I think you should expect the team to close this issue with some form of "thanks, but no".

**Comment by brandonroberts** [comment]
@wardbell thanks for the response. I did a poor job of explaining what I was asking for. I don't want it to be part of Angular core. I just wanted to have one less step in setting up router outlets and router links in components if you're using the router.

Right now ROUTER_PROVIDERS looks like this:

```js
export const ROUTER_PROVIDERS: any[] = CONST_EXPR([
  RouteRegistry,
  CONST_EXPR(new Provider(LocationStrategy, {useClass: PathLocationStrategy})),
  PlatformLocation,
  Location,
  CONST_EXPR(new Provider(
      Router,
      {
        useFactory: routerFactory,
        deps: CONST_EXPR([RouteRegistry, Location, ROUTER_PRIMARY_COMPONENT, ApplicationRef])
      })),
  CONST_EXPR(new Provider(
      ROUTER_PRIMARY_COMPONENT,
      {useFactory: routerPrimaryComponentFactory, deps: CONST_EXPR([ApplicationRef])}))
]);
```

What I was asking for is the line to make ROUTER_DIRECTIVES global to be added to the ROUTER_PROVIDERS export. 

It would look like this:

```js
export const ROUTER_PROVIDERS: any[] = CONST_EXPR([
  RouteRegistry,
  CONST_EXPR(new Provider(LocationStrategy, {useClass: PathLocationStrategy})),
  PlatformLocation,
  Location,
  CONST_EXPR(new Provider(
      Router,
      {
        useFactory: routerFactory,
        deps: CONST_EXPR([RouteRegistry, Location, ROUTER_PRIMARY_COMPONENT, ApplicationRef])
      })),
  CONST_EXPR(new Provider(
      ROUTER_PRIMARY_COMPONENT,
      {useFactory: routerPrimaryComponentFactory, deps: CONST_EXPR([ApplicationRef])})),
  CONST_EXPR(new Provider(PLATFORM_DIRECTIVES, {useValue: [ROUTER_DIRECTIVES], multi: true}))
]);
```

**Comment by wardbell** [comment]
Not sure why this is a good idea, given that directives and providers are different kinds of things.

It is true that these collections are loaded as providers under separate tokens. That doesn't mean the values can or should be mixed under the same tokens.

Imagine that I register even numbers under the EVEN token and odd numbers under the ODDS token. Yes they are both registered as providers. But I don't think I'd get what I want by saying, "Lets mix them up under the INTEGERS token.

Maybe that's a bad analogy because we can easily tell them apart. Not so easy to tell a Router Directive (a class) from a Router Provider (a service class).

**Comment by ericmartinezr** [comment]
@wardbell I don't think the point here is to mix two different concepts (I don't know if that's something to be worried about, I may be wrong).

The point here is how easy is to set up the Router.

Consider the followibng  *tree*

```
- Parent
  - Child
    - Grandchild
      - More
        - And more...
```
In cases like this we have to add `ROUTER_DIRECTIVES` in each component, which may be a  LOT. We can save us all that by using  `PLATFORM_DIRECTIVES` as @brandonroberts showed in his proposal. So this is most likely to be the solution for every user that uses Routing, personally I ended up doing the same (as I wrote in my first comment in this issue). But you guys could save us even more by adding `ROUTER_DIRECTIVES` to `ROUTER_PROVIDERS`. 

How is router not related to router? Nothing is being added to core, we just want to simplify setting up routing for everyone.

Quoting a great philosopher
>It seems like a natural progression. You start with putting router directives in each component, then you move to putting router directives in platform directives. So why not just include it with the router providers?
You're gonna need them if you're using the router. Its one less thing to have to do

--  *Anonymous*

**Comment by PascalPrecht** [comment]
I agree with @brandonroberts and @ericmartinezr here. It'd be also more similar to what we used to do in ng1, which is, defining `ngRoute` as a module dependency. Now that there are no Angular modules in that sense anymore, we need to add providers to our injector configuration. Having `ROUTER_DIRECTIVES` added to `PLATFORM_DIRECTIVES` once `ROUTER_PROVIDERS` are used sounds like a reasonable thing to do to me.

It just saves us further typing and doesn't conflict with any other concepts or anything.

The only thing I'm a tiny bit worried about is the fact that, the more we move into `PLATFORM_*` tokens, the more people will be surprised that they *have* to specify *some* directives in their code. Which are all the ones that aren't part of `PLATFORM_DIRECTIVES`, so basically any custom directive a user builds.

**Comment by wardbell** [comment]
Ah. I'm coming around a tiny bit. I couldn't see the point if you only worry about config once.

That's the case with adding ROUTE_PROVIDERS  but not ROUTE_DIRECTIVES which, yes, must currently be added to each Routing Component.

Now, to be honest, you aren't going to need them on more than a few components. How many views will you have that need RouterLink? 1? 2? 4? I'm running out of realistic cases.

So I'm still not sold that this is much of an issue.

Fortunately, it is easy to extend PLATFORM_DIRECTIVES although the team isn't keen on encouraging that because of the potential for abuse.

I think I'll do a little spike on it for this particular use case (when I have a laptop again) and throw it into a comment.

**Comment by PascalPrecht** [comment]
I think, especially in bigger applications it's quite common that almost
each component needs router capabilities in the view (router-outlet and
router link).

`PLATFORM_DIRECTIVES` is already a public API and in fact, I could imagine
this becoming a good and widely used pattern in reusable third party
libraries, to make directives automatically available throughout the entire
application, as it also doesn't add additional overhead at runtime.

Maybe I'm overseeing something.

Let's hear what the core team has to say.

**Comment by wardbell** [comment]
>quite common that almost each component needs router capabilities ... Router Outlet

Fascinating! So unlike my experience. I'm eager to see how that works and why. The beauty of software in its diversity.

Extending the platform set is not something the team needs to do when it is so easy to do ourselves as I intend to demonstrate (or eat my hat)

**Comment by zoechi** [comment]
I don't know TS I only use Angular with Dart. Couldn't you just create a file that exports the combined set and import this file instead everywhere in your app where you want to use both?

**Comment by PascalPrecht** [comment]
@zoechi Whenever you need any kind of router directive you need to import `ROUTER_DIRECTIVES` and specify them as view dependency on your component where you want to use them like:

```
@Component({
  selector: 'm-foo',
  template: '...',
  directives: [ROUTER_DIRECTIVES]
})
class Foo {}
```

This you have to do for every component that needs router directives. However, you could add them to `PLATFORM_DIRECTIVES`, using multi providers, allowing you to use all of those directives where ever you want, without specifying them explicitly.

```
bootstrap(MyApp', [
  ROUTER_PROVIDERS,
  provide(PLATFORM_DIRECTIVES', {'useValue': ROUTER_DIRECTIVES, multi: true})
]);
```

This particular line could easily be added to `ROUTER_PROVIDERS` reducing your code to:

```
bootstrap(MyApp, [ROUTER_PROVIDERS]);
```

again, and you wouldn't have to worry about adding `ROUTER_DIRECTIVES` everywhere.

It''s really just ergonomics. In fact, as far as I can see, there are no downsides whatsoever, it'd be just a win.

> Fascinating! So unlike my experience.

I'm talking particularly about very complex applications with nested components and auxiliary routes which should be decoupled at the same time.

Again, technically it'd be just a win, unless we're overseeing sth. I'd really say it could be rather a could pattern that modules that sit on top of core, add commonly used directives to `PLATFORM_DIRECTIVES` using their `WHATEVER_PROVIDERS` so we as a consumer don't have to worry about this. This is just the router, but think about all the other third party libs we might end up using.

Maybe "platform" is should rather be reserved for things provided by core, then we could at least introduce another Opaque Token namespace for `THIRDPARTY_DIRECTIVES` (which could also be part of `PLATFORM_DIRECTIVES`).

**Comment by wardbell** [comment]
Looks like your wish may be granted. Stay tuned!

**Comment by brandonroberts** [comment]
Great! :+1:

**Comment by brandonroberts** [comment]
@wardbell anymore updates on this one?

**Comment by wardbell** [comment]
Not yet.  But  I'm going to press on it RIGHT NOW!

**Comment by mhevery** [comment]
Let me have a look at it as a stretch goal.

**Comment by brandonroberts** [comment]
Closing as router directives can be made global through upcoming AppModules
