### ISSUE TITLE
Removing Unused modules while application loads - Angular 2

### ISSUE THREAD

**Issue by zamamohammed** [angular/angular#5939]
Don't you think we can increase the performance of a website if we reduce the number of modules of a framework which are not used in the application. What I mean here is suppose I am creating Angular 1 application, and in my application I do not use directives like ng-switch, ng-mouseover etc, then I should be able to load the application even if we do not include such modules, even in filters, sometimes some filters are unused in the whole application, and sometimes I feel a filter to too heavy for my application, as I just need a simple date filter, I do not want all the options in the date filter, so either I should be able to select which options I require for my application, or I should be able to just write my simple filter while not including the date filter from angular, so if angular 2 has this ability to remove the unused modules, then not only is the size of the file reduces, but unused modules does not have to load in the browser, which will be a lot better for angular 2 application for performance. 

Just my thought, I might be wrong, please correct me if I am wrong here.

**Comment by pkozlowski-opensource** [comment]
@zamamohammed we use the term tree-shaking for the thing you describe. We very much would love to have a solution like this, and I'm sure we will in this form or another (in fact Dart has it today). But the solution is rather going to come from projects like https://github.com/angular/angular-cli, https://github.com/rollup/rollup or TypeScript proper. 

So, we are very much aware of the requirement and working towards this goal, but not in this repo.
