### ISSUE TITLE
Issue with ngFor Syntax in Developer Guide

### ISSUE THREAD

**Issue by aallaparthizc** [angular/angular#5940]
Hi,

I am following the tutorials provided in the website. In Developers Guide, Displaying Data page, we are using below code to display the list of heroes.
```javascript
<li *ngFor="#hero of heroes">
        {{ hero }}
      </li>
```
The above code is throwing console errors and no page is displayed. I changed it to ng-For and the page is working fine. Can you please check this once.

**Comment by thelgevold** [comment]
It sounds like you are on an old version of Angular. Check what version you are loading. 
Upgrade to beta and it will work.

**Comment by pkozlowski-opensource** [comment]
@thelgevold is right here! @aallaparthizc I'm going to close this one for now, but if you could link to the exact dev guide page where we mix cases and ng2 versions, we could check if there are not mistakes in the docs.
