### ISSUE TITLE
ngFor fails when binding to function in beta

### ISSUE THREAD

**Issue by thelgevold** [angular/angular#5941]
I noticed in beta that it's no longer supported to bind an ngFor to a function. Instead we have to assign the results of the function to an array before binding.

Pre Beta you could do this:
```
<td  *ngFor="#columnHeader of getHeader()">{{columnHeader}}</td>
```

Now after Beta it doesn't seem to work to bind to the function directly, so you have to do something like this:
```
this.header = this.getHeader();
<td  *ngFor="#columnHeader of header">{{columnHeader}}</td>
```

In my case this switch is ok, but I think it needs to be documented if function bindings aren't supported going forward.

The function binding currently throws the following error:
Expression 'getHeader() in Spreadsheet@4:33' has changed after it was checked. Previous value: 'a,b,c,d'. Current value: 'a,b,c,d' in [getHeader() in Spreadsheet@4:33]

**Comment by robwormald** [comment]
this works fine, though its not recommended. your likely issue is you're returning a new reference each time the function is called, which makes change detection see a new array each time it's checked.

Works fine, as the same reference is returned each time: http://plnkr.co/edit/zDiRPoVMKLsyrkoVnilx?p=preview

Complains, as its a new reference on each check: http://plnkr.co/edit/ahGa51VDJaK0RpxHbCVC?p=preview

**Comment by thelgevold** [comment]
I agree, but for some reason this was working fine for alpha.53, but in beta it fails. Maybe there was a change towards the end of alpha? 

To the point about references and change tracking though. If I update the plunker to the below it still works even though I return a new array reference after clicking the button. Shouldn't this in theory confuse the change tracking since I now have changed the reference of this.rows by assigning a brand new array after each click. It's the same variable, but a new memory reference every time. 

```
import {Component} from 'angular2/core'

@Component({
  selector: 'my-app',
  providers: [],
  template: `
    <div>
      <h2>Hello {{name}}</h2>
      <button (click)=createRows()>Create</button>
      <ul>
        <li *ngFor="#row of rows">{{row}}</li>
      </ul>
    </div>
  `,
  directives: []
})
export class App {
  constructor() {
    this.name = 'Angular2'
    this.rows = [1,2,3]
    this.length = 1
  }
  
  createRows(arr){
    this.length++;
    var temp = [];
    for(var i = 0 ; i < this.length; i++){
      temp.push(i);
    }
    this.rows = temp;
  }
  
  getRows(){
    return this.rows;
  }
}
```

**Comment by robwormald** [comment]
The change in beta is we turned on the dev mode, which checks for side effects caused by change detection - that's the real issue here. 

In your first example, each time a change detection is run, you'd get a new array - that's a side effect. In your second, you'd only get a new array with an explicit user action - which would trigger change detection once, and on the second check, you'd get the same instance - which is the way it's supposed to work.

**Comment by thelgevold** [comment]
Thanks! That helps clarify the behavior.
I guess having it throw an error here teaches people to avoid code that needlessly creates new instances when the change tracking is triggered by something unrelated. I think a few bugs were logged today based on similar scenarios :-)
