### ISSUE TITLE
Warning when using angular2-polyfills

### ISSUE THREAD

**Issue by AntJanus** [angular/angular#5942]
When importing angular2-polyfills via Webpack, I get the following warning:

```
WARNING in ./~/angular2/bundles/angular2-polyfills.js
Critical dependencies:
2157:113-120 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/angular2/bundles/angular2-polyfills.js 2157:113-120
```

The import is done via:

`angular2/bundles/angular2-polyfills`

Is there any way to import the various polyfills individually? I used to do the `import 'zone.js'`; `import 'reflect-metadata';` but Zone started giving me errors when imported by itself.

**Comment by gdi2290** [comment]
apply this fix
https://github.com/angular/angular2-seed/commit/9d95e85e232066a59e208f7ba4f67f648eaba79e

```es6
module.exports = {
  module: {
    noParse: [ /zone\.js\/dist\/.+/, /angular2\/bundles\/.+/ ]
  }
}
```

One of the biggest reasons to use webpack is the ability to files within a module and apply transforms on them with loaders. When we import a bundled (pre-built) file then webpack detects it and warns us of the fact. What webpack is trying to get us to do is adding a `noParse` regexp so it may correctly ignore the pre-bundled files. Providing webpack with a way to ignore files that have been already parsed (bundled by other bundlers) would prevent a lot of unintended side-effects with loaders.

**Comment by AntJanus** [comment]
ahhh! Thanks a ton! :)

**Comment by rixrix** [comment]
@gdi2290 thanks for this... encountered this issue today
