### ISSUE TITLE
Documentation error?

### ISSUE THREAD

**Issue by magnayn** [angular/angular#5951]
The documentation for Injection contains lines saying

     import {Injectable} from 'angular2/angular2';

I think that may be wrong, and ought to be

     import {Injectable} from 'angular2/core';

?

**Comment by pkozlowski-opensource** [comment]
@magnayn you are right! Where did you see this buggy code example? Could you please link to a page in question? Thnx!

**Comment by magnayn** [comment]
It's about 1/2 way down https://angular.io/docs/ts/latest/guide/dependency-injection.html

**Comment by pkozlowski-opensource** [comment]
Thnx. Moving over to https://github.com/angular/angular.io/issues/558 where documentation resides.
