### ISSUE TITLE
Injecting providers with given interface

### ISSUE THREAD

**Issue by wkwiatek** [angular/angular#5952]
Suppose we have some kind of `Storage` which is an interface (`IStorage`) and I'd like to say that my component wants to have injected a service which implements such an interface. How is it possible in beta.0? 

Let's say: 
```js
interface IStorage {
  store: string;
}
```
```js
constructor (storage: IStorage) {
   this.store = storage.store;
}
```

I found some discussion about it in following blog post: http://victorsavkin.com/post/126514197956/dependency-injection-in-angular-1-and-angular-2 but it seems to be a little bit outdated. 

What's the proper way to deal with the problem?

**Comment by pkozlowski-opensource** [comment]
So the problem is that TypeScript doesn't retain interface info for runtime. The best way now is to use abstract classes instead of interfaces.
