### ISSUE TITLE
i18n and L10n support

### ISSUE THREAD

**Issue by meriturva** [angular/angular#5953]
Hi to all,
after the beta release (great guys!), we have started to compile feature list to help us to decide when move our big project to angular 2.
What we are looking now for localization service..and we have found on today blog post: http://angularjs.blogspot.it/2015/12/angular-2-beta.html that angular2 will have support for i18n and L10n natively.
Right? 

Any ETA or preview release about this important feature?
Thanks.

**Comment by qina83** [comment]
+1 any comments?

**Comment by hitmanmcc** [comment]
No word on this yet?

**Comment by laco0416** [comment]
:+1:

**Comment by intellix** [comment]
I believe this is what you're looking for: https://github.com/angular/i18n

**Comment by meriturva** [comment]
@intellix Actually the i18n project you mentioned is quite stocked....we would like just to have  information to take decisions here!
Thanks!

**Comment by the-ult** [comment]
We are building our new front-end with Angular2 (beta) as well, and would really like to use internationalization.
@PascalPrecht, are you currently working on porting ng-translate into Angular2/i18n?

**Comment by PascalPrecht** [comment]
I don't plan to bring a 2.0 version for angular-translate in favour of angular/i18n, although, it seems like a lot of ppl are requesting it. Maybe I'll change my mind.

@ocombe actually started some work on that already.

**Comment by ocombe** [comment]
Yes, there is https://github.com/ocombe/ng2-translate/ but it doesn't have all the functionalities from angular-translate (but it works well with what is available). I just wanted basic i18n features until the official implementation was released.
If it turns out that the official implementation is too difficult to use, or doesn't cover my needs then I'll keep working on ng2-translate, otherwise I'll deprecate it in favor of the official solution.

@PascalPrecht: if you want to join me on ng2-translate I'd be glad to have you on board, and maybe move the repository to the angular-translate repository/organisation.

**Comment by the-ult** [comment]
@PascalPrecht, I thought you were working on angular/i18n with the Angular2 core team. Using you're experience to build angular/i18n for Angular2 v1.0.0
Just read the design docs and your blogpost: http://blog.thoughtram.io/angular/2015/03/21/angular-and-i18n-the-new-world.html which seems really promising

**Comment by PascalPrecht** [comment]
I'm not actively working on that solution. Most of the work was done by @chirayuk so all the credits should go to him. I just wrote about it. And yes, it is promising but I think it needs some love as the core team is quite busy.

**Comment by jtheoof** [comment]
There has not been any activity on https://github.com/angular/i18n since May 2015. @PascalPrecht Do you know if it is ready for use in Angular2?

**Comment by ocombe** [comment]
it is definitely not. I asked @robwormald about this and he should pop the question today at their meeting, let's hope that we'll have some news soon :)

**Comment by jtheoof** [comment]
Thanks @ocombe, keep us posted :)

**Comment by robwormald** [comment]
There's actually no meeting today, but will ask tomorrow!

**Comment by meriturva** [comment]
Any news after meeting?
Thanks!

**Comment by ocombe** [comment]
You can find some news in the meeting notes: https://docs.google.com/document/d/150lerb1LmNLuau_a_EznPV1I1UHMTbEl61t4hZ7ZpS0/edit

>Update on i18n support
>- Goal is to translate templates to multiple languages
>- First working on static messages - current work is on extracting static messages in the next two weeks
>- We'll generate one version of the application per locale
>- Next phase will be for dynamic scenarios like gender and pluralization

**Comment by jtheoof** [comment]
Cool, at least it's not stalled.

**Comment by mhevery** [comment]
It will be bart of the final release. 

Closing since this is a support question which does not belong here.
