### ISSUE TITLE
Publish prod sources in the root of npm

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#5959]
Currently we've got `dev` files (with in-lined data maps) published to the root of the NPM repository. Those are the files that are being picked up by WebPack and result in large (4MB+) bundle with a default config. 

Consider pushing `prod` files instead to ease live of people using bundlers with default config. Ultimately the issue to solve is this one:  https://github.com/angular/angular2-seed/issues/19

cc: @robwormald

**Comment by vsavkin** [comment]
I think we need to have two npm packages: dev and prod.

**Comment by pkozlowski-opensource** [comment]
Yeh, this would be another way of solving this very problem. Although it has "mental burden" cost for developers (which package do I need to pull) and maintenance cost both for us and developers (ok, I go to prod now, what do I need to change?)

It could work but doesn't seem very developer friendly...

**Comment by robwormald** [comment]
two npm packages is going to require either rewriting paths, or some loader config trickery to make it work... neither of which sound very nice. i think we should avoid this if it all possible, as its going to make an already complex loader configuration that much more complex.

**Comment by pkozlowski-opensource** [comment]
This is obsolete after new world repackaging.
