### ISSUE TITLE
Support multiple Templates per Component

### ISSUE THREAD

**Issue by mhevery** [angular/angular#596]
Prerequisite: #595 

# Goal

A given Component needs to be able to use different templates per locale, device type (and test). This requires that we decouple `@Component` definition from `TemplateConfig` (and rename `TemplateConfig` to `@Template`)

## Example

Simple Component (with separate `Template` annotation)
```
@Component({ selector: 'my-component' })
@Template({ 
  url: 'some/url'
})
class MyComponent {
}
```

As more local devices get added to the system we can add `@Template()`
```
@Component({ selector: 'my-component' })
@Template({ 
  url: 'some/url',
  directives: [DirA, DirB]
})
@Template({
  locale: 'en',
  device: 'mobile',
  url: 'some/url_en',
  directives: [DirA, DirC]
})
class MyComponent {
}
```
NOTE: different Templates can have different directive imports.

This works with existing [`Reflector`](https://github.com/angular/angular/blob/master/modules/angular2/src/reflection/reflector.js) Since the above can be rewritten as:

```
class MyComponent{}

Reflector.addAnnotation(MyComponent, new Component({ selector: 'my-component' }));
Reflector.addAnnotation(MyComponent, new Template({url: 'some/url',  directives: [DirA, DirB]});
Reflector.addAnnotation(MyComponent, new Template({locale: 'en', url: 'some/url_en', directives: [DirA, DirC]});
```

Because it can be rewritten into the Reflector form, it can be properly tree shaken, based on locale

# Compiler

To support this the Compiler needs to be aware of current `locale`/`device` while compiling the templates. The compiler will need a new `TemplateResolver` dependency which will select the right `@Template` per each `ComponentType`. The `TemplateResolver` can than also be used in tests to override the templates.

```
export class TemplateResolver {
  resolve(component: Type): Template {
    // ...
  } 
}
```

# Compilation Pipeline

1. We start with component `Type`
2. We use `TemplateResolver` to convert `Type` to `Template`
3. We use the `TemplateLoader` to covert the `Template` into HTML.

**Comment by vicb** [comment]
@mhevery as of today, the `DirectiveMetadatReader` returns max 1 directive per Type. It seems like we need to update it to support multiple directives (ie `@Template` in this case).

While we are updating it, should it also support multiple directives in other cases:

```
@Decorator({selector: [dec1]})
@Decorator({selector: [dec2]})
class MyDec {}
```

I think that the second decorator annotation currently as no effect, is this a use case we want to support ?

We could create an other prerequisite issue for this.

**Comment by mhevery** [comment]
- yes for supporting multiple directives in `DirectiveMetadatReader `
- no for supporting multiple `@Decorotors` I am not sure what it would mean to have two.

**Comment by mostafa8026** [comment]
Could you please provide a more detailed example of how to implement multiple templates per components, or at least reference some URL.
Do we allow to use other tags (if I name it correctly) except locale, device? like customerID, which refers to the customer template. if yes, how can we resolve this tag.
