### ISSUE TITLE
Components should create a `display:block` style by default

### ISSUE THREAD

**Issue by matsko** [angular/angular#5960]
Let's say I create a new component in Angular2 and I attempt to style it:

```ts
// hello_world_cmp.ts
@Component({
   selector: 'hello-world',
   styleUrls: ['hello-world.css']
   template: 'hello world!'
})
class HelloWorldCmp { }

// hello_world.css
:host { background: red; }
```

The styling **fails** to be applied for the sole reason that browsers have no clue what the `<hello-world></hello-world>` HTML element is. This is expected, but it's tricky to debug for those of whom are new to Angular and to web components. This is also the case with predefined Angular components (like `<router-outlet></router-outlet>`).

### Solution

I think it's best if Angular keeps track of each of the components created in an application and builds a CSS selector which is placed at the HEAD of the index.html file within a style tag.

```html
<head>
<style>
router-outlet, hello-world { display:block; }
<style>
</head>
```

Since the CSS selectors are **tag selectors** this means that they have the lowest specificity and the fact that the styles are placed **at the top of the index.html document** this then allows for ui-libraries and user-defined styles to easily override the styles without having to use a heavier selector (e.g. is a `.class` selector is used to match all components then a user style like `hello-world` would lose to that in the specificity battle).

We should also have a flag to disable this.

**Comment by kasperpeulen** [comment]
Why would `display: block` by default be better than `display:inline`?

I don't understand, why would not just style the `host` css using css yourself. As creator/designer of the web component, you would know best if it should be display: block or display: inline?

**Comment by tbosch** [comment]
If we want to do this, I would vote for not creating a stylesheet but rather just setting `element.style.display` property so that the browser does not need to parse the dynamically generated stylesheet.

In general, I am not sure whether we should do this:

1. if a component author is interested in the appearance of his component, he would already create stylesheet rules for the component. Adding an extra property to an already existing rule is not too bad.
2. why should is be `display:block` and not `display:flex`? How do we know what the component author actually needs?
3. this is a general problem with custom elements. Making angular components behave differently might be convenient, but we need to document it, ...

**Comment by matsko** [comment]
@tbosch we can't use `element.style.display` because that's an inline style and inline styles have the highest specificity. So something like this would always require `!important`.

```
// styles.css
:host { display:block!important; }
```

@tbosch and @kasperpeulen The reason why we use `display:block` here is because almost all components that contain more elements are block by default in HTML (think `<div>`, `<p>`). Even HTML5 elements like `<section>`, `<footer>`, `<aside>` are all block level. There's a higher chance that the user expects this as the default and then overrides to support something like `flex` or `inline`. This isn't so much about the component author vs the template author, it's more about allowing the user to skip an annoying step for every component created. Here's proof: http://plnkr.co/edit/aaIVUpEhqrVx6NltvFya?p=preview

**Comment by PascalPrecht** [comment]
I vote for this as well. I'm remember @maxlynch raised this too and in fact, I wonder if this shouldn't be also the default for custom elements (as in the WC spec), although, Angular actually doesn't create custom elements in that sense.

**Comment by matsko** [comment]
After chatting with @tbosch we've realized that it's much more complex than first thought. This is due to the issue of lazy-loading in code which upon execution would require another `<style>` tag to be created on the fly.

**Comment by zoechi** [comment]
From my experience with Polymer I also think `block` is the most common value. 
This could also fixed by tools that generate boilerplate and include a default style tag. Like live templates in WebStorm/IntelliJ.

**Comment by ShadowManu** [comment]
How's the discussion on this? Is there some kind of temporary concensus?

**Comment by vicb** [comment]
obsolete (would be a breaking change)

**Comment by edmundo096** [comment]
This is the 1st result (or one of the first) in Google  when searching about Angular components display block.

Maybe this link (to the Angular 2 Doc: Component Styles which describes about styling the Component with `display: block;` using `:host` can be useful:
https://angular.io/docs/ts/latest/guide/component-styles.html#!#-host

**Comment by nawlbergs** [comment]
I would prefer that angular components just received a css class when compiled.
**for example**: 
<my-component></my-component> would become: <my-component class="ng-component"></my-component>

Thus, the author could do a global style to default components to whatever they want:
<style>
.ng-component{  display:block; }
....
my-inline-component.ng-component{ display:inline-block;  }
</style>

**Comment by ialex90** [comment]
+1 @nawlbergs

**Comment by jhnns** [comment]
> I wonder if this shouldn't be also the default for custom elements (as in the WC spec),

[They discussed this](https://github.com/w3c/webcomponents/issues/224) and I understand the reasoning why they didn't change the `display` property.

**Comment by ialex90** [comment]
@jhnns What about a property on the AngularCLI compiler or on the tsconfig for adding a style or a class by default to all ng components? Well, it makes more sense on the AngularCLI as it's related to Angular and not to TS, and it might be better ask this to their team :)

**Comment by zoechi** [comment]
@ialex90 as mentioned in https://github.com/angular/angular/issues/5960#issuecomment-165257871 I also think it would be the right way to support this in tools. 
Just adding `@Component({ selector: 'foo', host: { 'style.display': 'block'}, ... }` would do.

**Comment by ialex90** [comment]
I missed that comment thanks! absolutely right

**Comment by tstpierre** [comment]
You can use ```host: { 'style': 'display: block' }```.  I had to do this to get routing animations to work.

**Comment by kvanberendonck** [comment]
FWIW if you're arriving here from google, Angular components using `display: flex` have a really bad interaction where if you don't set `display: block` it seems to just be inherited into the children components forever.

You have to 'tie the knot' with `display: block` in your `:host` style or use a solution provided from here. You don't usually notice this because the `display: block;` on `div` usually takes higher precedence and does this automatically ..

**Comment by zoechi** [comment]
@kvanberendonck 

> If it is an ng-content container use :host /deep/ > *

`/deep/` is deprecated and replaced by `::ng-deep` because SASS deprecated support for `/deep/`. 
`::ng-deep` is also deprecated but with another time range (when browsers provide native support for cross-web-component styling support) and it's compatible with SASS.

**Comment by briancodes** [comment]
@tstpierre You might also need to set the host's width/height to 100% if overriding the default `inline` style of the selector elements. If child components are using height/width 100%, they will probably not be referenceing the html/body sizing - but their hosts sizing
