### ISSUE TITLE
Wrong anchor 'Lifecycle Hooks' in the Architecture Overview page (Developer Guides)

### ISSUE THREAD

**Issue by micwic** [angular/angular#5961]
The Lifecycle Hooks link point to # instead of the description of what it is.
Seem not be defined or wrong to me.
https://angular.io/docs/ts/latest/guide/architecture.html

**Comment by pkozlowski-opensource** [comment]
Moving over to https://github.com/angular/angular.io/issues/565 where all the dev guides reside
