### ISSUE TITLE
Duplicate 'the' in text in Architecture Overview (Developer Guides)

### ISSUE THREAD

**Issue by micwic** [angular/angular#5962]
The HeroDetailComponent (code not shown) presents facts about a particular hero, the hero that the user selects from the list presented by the the HeroListComponent. The HeroDetailComponent is a child of the the HeroListComponent.
Search for the two 'the the' in the text.

**Comment by pkozlowski-opensource** [comment]
@micwic thnx for reporting, we always do appreciate documentation corrections! But all the documentation lives in a separate repository: https://github.com/angular/angular.io/issues

@onesick would you mind checking the latest version of the docs and if they still suffer from the problem open an issue in https://github.com/angular/angular.io/issues? Or better yet, send a PR with corrections! This would be very much appreciated!
