### ISSUE TITLE
Wrong component name for hero-list in Achitecture Overview (Developer Guides)

### ISSUE THREAD

**Issue by micwic** [angular/angular#5963]
Seem to me that the exported component is named 'HeroesComponent' in the code. The explanation later speak about HeroListComponent. Seem to me the exported component name in the code snippet from hero-list.component.ts may be named 'HeroListComponent'.

**Comment by pkozlowski-opensource** [comment]
@micwic thnx for reporting, we always do appreciate documentation corrections! But all the documentation lives in a separate repository: https://github.com/angular/angular.io/issues

@onesick would you mind checking the latest version of the docs and if they still suffer from the problem open an issue in https://github.com/angular/angular.io/issues? Or better yet, send a PR with corrections! This would be very much appreciated!
