### ISSUE TITLE
Zone throwing maximum call stack 

### ISSUE THREAD

**Issue by matthewdenobrega** [angular/angular#5964]
After upgrading to beta.0 and switching to loading zone and reflect-metadata from angular2-polyfills.min.js I now get a 'Maximum call stack size exceeded' on page load. This is for our large LMS app and a smaller app. The app is served with Webpack.

The larger app just cycles around angular2-polyfills.js:1088 which is patching addEventListener. The smaller app throws the following:

EXCEPTION: Error during instantiation of BrowserDetails! (Token Promise<ComponentRef> -> DynamicComponentLoader -> Compiler -> RuntimeCompiler -> ProtoViewFactory -> Renderer -> DomRenderer -> AnimationBuilder -> BrowserDetails).BrowserDomAdapter.logError @ browser_adapter.js?d744:76BrowserDomAdapter.logGroup @ browser_adapter.js?d744:86ExceptionHandler.call @ exception_handler.js:56(anonymous function) @ application_ref.js:317run @ core.js:96(anonymous function) @ ng_zone.js:343NgZone.run @ ng_zone.js:292ApplicationRef_.bootstrap @ application_ref.js:292bootstrap @ browser.js?94e0:101webpackJsonp.906 @ learnComponent.ts:41__webpack_require__ @ bootstrap 7117f112e4d02c7a2056:71webpackJsonp.0 @ learn.js:7__webpack_require__ @ bootstrap 7117f112e4d02c7a2056:71webpackJsonpCallback @ bootstrap 7117f112e4d02c7a2056:42(anonymous function) @ learn.js:1

browser_adapter.js?d744:76ORIGINAL EXCEPTION: RangeError: Maximum call stack size exceeded
BrowserDomAdapter.logError @ browser_adapter.js?d744:76ExceptionHandler.call @ exception_handler.js:65(anonymous function) @ application_ref.js:317run @ core.js:96(anonymous function) @ ng_zone.js:343NgZone.run @ ng_zone.js:292ApplicationRef_.bootstrap @ application_ref.js:292bootstrap @ browser.js?94e0:101webpackJsonp.906 @ learnComponent.ts:41__webpack_require__ @ bootstrap 7117f112e4d02c7a2056:71webpackJsonp.0 @ learn.js:7__webpack_require__ @ bootstrap 7117f112e4d02c7a2056:71webpackJsonpCallback @ bootstrap 7117f112e4d02c7a2056:42(anonymous function) @ learn.js:1
browser_adapter.js?d744:76ORIGINAL STACKTRACE:BrowserDomAdapter.logError @ browser_adapter.js?d744:76ExceptionHandler.call @ exception_handler.js:68(anonymous function) @ application_ref.js:317run @ core.js:96(anonymous function) @ ng_zone.js:343NgZone.run @ ng_zone.js:292ApplicationRef_.bootstrap @ application_ref.js:292bootstrap @ browser.js?94e0:101webpackJsonp.906 @ learnComponent.ts:41__webpack_require__ @ bootstrap 7117f112e4d02c7a2056:71webpackJsonp.0 @ learn.js:7__webpack_require__ @ bootstrap 7117f112e4d02c7a2056:71webpackJsonpCallback @ bootstrap 7117f112e4d02c7a2056:42(anonymous function) @ learn.js:1

browser_adapter.js?d744:76RangeError: Maximum call stack size exceeded
    at e.(anonymous function) (http://localhost:8081/lib/angular2-polyfills.min.js:1:7145)
    at global.zone.(anonymous function) (http://localhost:8081/__build__/angular2.js:40895:26)
    at e.(anonymous function) (http://localhost:8081/lib/angular2-polyfills.min.js:1:7145)
    at global.zone.(anonymous function) (http://localhost:8081/__build__/angular2.js:40895:26)
    at e.(anonymous function) (http://localhost:8081/lib/angular2-polyfills.min.js:1:7145)
    at global.zone.(anonymous function) (http://localhost:8081/__build__/angular2.js:40895:26)
    at e.(anonymous function) (http://localhost:8081/lib/angular2-polyfills.min.js:1:7145)
    at global.zone.(anonymous function) (http://localhost:8081/__build__/angular2.js:40895:26)
    at e.(anonymous function) (http://localhost:8081/lib/angular2-polyfills.min.js:1:7145)
    at global.zone.(anonymous function) (http://localhost:8081/__build__/angular2.js:40895:26)

**Comment by pkozlowski-opensource** [comment]
Are you bundling angular2-polyfills wit webpack? if so, you should not - it is meant to be included via a script tag. share your webpack config / sample repo if you need more info.

**Comment by matthewdenobrega** [comment]
I was including zone in one of the webpack chunks as well - removing it fixed the issue. Closing.

**Comment by gdi2290** [comment]
please see https://github.com/angular/angular/issues/5957#issuecomment-165286368 for the correct way to integrate polyfills with webpack

**Comment by skolsuper** [comment]
@matthewdenobrega Thank you for posting your fix, this helped me too.

**Comment by kemsky** [comment]
uglifyjs plugin option

mangle: {
        keep_fnames: true
}
also helps.

**Comment by zwhitchcox** [comment]
Having the same problem.

**Comment by bapatel1** [comment]
Having same issue right now. "RangeError: Maximum call stack size exceeded". I am not minifying or using webpacks. I am using gulp to copy same .js to lib folder. I have router implemented and when i click on any page navigation link, it's throwing this error on console. 

Any help is appreciated.
