### ISSUE TITLE
Box header in Quickstart omits "app."

### ISSUE THREAD

**Issue by michaelrommel** [angular/angular#5966]
Seems to me, the white-on-blue box heading in the 5min quickstart should read "app/app.component.ts (export)" instead of "app/component.ts (export)"

**Comment by ericmartinezr** [comment]
@michaelrommel the repo for reporting issues with the website is this one https://github.com/angular/angular.io

**Comment by michaelrommel** [comment]
I have reported it in the other repo. Thank you for pointing this out!!
