### ISSUE TITLE
Cannot target ES6 in Typescript (possible regression)

### ISSUE THREAD

**Issue by cherrydev** [angular/angular#5973]
Right now it appears that it's impossible to use angular2 directly from node_modules when typescript is targetting es6 because es6-shim.d.ts is indirectly referenced from zone.d.ts.  This APPEARS to be a regression of #4882 that has happened because zone.d.ts directly references es6-shim.d.ts.  This is confusing to me because zone.d.ts (in definitelytyped) has ALWAYS referenced es6-shim.d.ts and therefore this should never have worked.

The reference chain is:
`core.d.ts -> ./manual_typings/globals-es6.d.ts -> ../typings/zone/zone.d.ts -> ../es6-shim/es6-shim.d.ts`

**Comment by alexeagle** [comment]
Yes, the zone.d.ts shipping with angular2 (I tried beta.1) has `es6-shim` dependency (https://github.com/angular/DefinitelyTyped/blob/master/zone/zone.d.ts). The one on DefinitelyTyped has an `es6-promise` dependency (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/zone.js/zone.js.d.ts#L6)
Note, I have a PR to remove our fork, which might solve this problem
https://github.com/angular/angular/pull/6267

**Comment by DanielJoyce** [comment]
Bumping into this bug as well. Still encountering in angular2 2.0.0-beta.1

**Comment by kalahari** [comment]
Is the best current work around with 2.0.0-beta.1 going into `node_modules/angular2` and making changes to `.d.ts` files? I haven't found anything else that works.
