### ISSUE TITLE
Router navigate called twice with HashLocationStrategy

### ISSUE THREAD

**Issue by rerezz** [angular/angular#5978]
Navigating with the browsers back/forward button or Location.back()/forward() will call the router navigation function twice when using the HashLocationStrategy.

angular version: 2.0.0-beta.0

I've created a plunk: http://embed.plnkr.co/smUy1twVS8v5YBdDa0c9/ with a console.log when navigating.

**Comment by naomiblack** [comment]
seems likely related to internal b/27744755

**Comment by zarkosusnjar** [comment]
Seems that this is the same thing that happens to me in 2.0.0-beta.15 when changing routes using external links on the page.

For example, when I click application route link /#bookmarks, everything is fine, but if I click <a href="/#bookmarks"> outside the application, I get plain HTML template badly rendered and router subscribers called twice.

Any idea how to overcome this before new router and RC is in better shape?

**Comment by IgorMinar** [comment]
This issue was made obsolete by router v3: https://angularjs.blogspot.com/2016/06/improvements-coming-for-routing-in.html

If you believe this is not the case, please file a new issue updating the description to router v3. thank you!
