### ISSUE TITLE
Issue with loading zone in beta.0

### ISSUE THREAD

**Issue by dblVs** [angular/angular#5980]
Hello,

I'm getting an issue with zone when enableLongStackTrace is enabled,

angular/modules/angular2/src/core/zone/ng_zone.ts on line 352.

I might be wrong but I think Zone should be all lower case or am I missing something ?

**Comment by pkozlowski-opensource** [comment]
Could you please send a plunker with a reproduce scenario? We do lack context here...

**Comment by dblVs** [comment]
Can't connect to plunkr at the moment will try in 20 minutes. The context is just a bootstrap with a component. with a lot of childs. The problem comes when I bootstrap. It doesn't even load the component at all.

**Comment by eav** [comment]
I updated from alpha 53 to beta, and started to get the same issue, a little more details:
Uncaught ReferenceError: Zone is not defined
NgZone.createInnerZone @ ng_zone.ts:352
NgZone @ ng_zone.ts:163
createNgZone @ application_ref.ts:81
PlatformRef.application @ application_ref.ts:219
bootstrap @ browser.ts:111
(anonymous function) @ bootstrap.js:29
(anonymous function) @ app.js:864
__webpack_require__ @ app.js:51
(anonymous function) @ multi_app:6
(anonymous function) @ app.js:101
__webpack_require__ @ app.js:51
(anonymous function) @ app.js:94
(anonymous function) @ app.js:97

**Comment by pkozlowski-opensource** [comment]
@dblVs @eav sorry guys, but we really need to have a reproduce scenario to help
@eav your issue sounds like bad WebPack config and not the one reported originally. See a minimal WebPack setup here: https://github.com/angular/angular2-seed and compare it with yours  

Or use one of the other existing WebPack-based seeds that already updated to beta.0

**Comment by dblVs** [comment]
Sorry @pkozlowski-opensource had to do something else. I cannot reproduce it in plnkr.co because I have no jspm there. If it would be ok for you I can create repo with the problem.

**Comment by pkozlowski-opensource** [comment]
@dblVs JSMP is pretty hard at the moment as it doesn't play nicely with TS types resolution from node_modules. As such I'm not super keen on debugging people JSPM setups. Feel free to post a link to your repo here (or better yet, ask at https://gitter.im/angular/angular) so any people currently using JSPM might help.

**Comment by eav** [comment]
ok fixed my issue by not including zone.js in the bundle explicitly.

**Comment by wkwiatek** [comment]
The problem is that requiring file like `import 'zone.js'` (or something similar like `require('zone.js')`) we do not have global variable set. Zone imported file look as follows: 
```js
'use strict';

var core = require('./core');
var browserPatch = require('./patch/browser');

global.zone = new core.Zone();

module.exports = {
  Zone: core.Zone,
  zone: global.zone
};

browserPatch.apply();
```

So to have globally available `Zone` I made an workaround for my app like: 
```js
window.Zone = require('zone.js').Zone;
``` 

Another solution is to use files from `dist` of `zone.js` like:
```js
import 'zone.js/dist/zone-microtask';
import 'zone.js/dist/long-stack-trace-zone';
```

**Comment by pkozlowski-opensource** [comment]
Please, please **DO NOT** import zone through package managers. This will cause all kind of grief. See: https://github.com/angular/angular/blob/master/modules/angular2/docs/bundles/overview.md#required-polyfills

**Comment by dblVs** [comment]
As you said I included the polyfills without any package management. Even before every script I still get the same issue.

**Comment by wkwiatek** [comment]
@pkozlowski-opensource So what is the way of including `angular2-polyfills` through package managers? Importing `angular2/bundles/angular2-polyfills.js` seems to be also a little bit dirty.

**Comment by pkozlowski-opensource** [comment]
@wkwiatek good old `script` tag. Zone **CAN NOT** be loaded by a package manager.

**Comment by dblVs** [comment]
@pkozlowski-opensource It was working fine on @2.0.0-aplha.53 (I assume the problem is that devMode wasn't on by default)? Is relying on a window variable the right choice ?

P.S: Renaming the 'Zone' to 'zone' fixed launching of my app (the only problem is its a hack since it attached the error to the particular zone.

**Comment by wkwiatek** [comment]
> Zone CAN NOT be loaded by a package manager.

@pkozlowski-opensource Could you please expand more on that? If it's so strict then why Zone even exists as `npm` package? Just curious.

**Comment by dblVs** [comment]
@pkozlowski-opensource I fixed the issue because I had 1 component that uses zone.bind (because I'm using hello.js and it doesn't capture its events).
I removed that and it fixed it. But I end up not being able to get zone to react to the changes from hello.js

**Comment by pkozlowski-opensource** [comment]
Zone.js is doing non-trivial monkey-patching and if loaded via package manager it might not be able to do it properly or it might patch wrong things (ex. a polyfill used by a loader instead of API used by an application).

Once again, the only usage of zone.js we can support is where zone is loaded via a script tag, as early as possible

**Comment by kylecordes** [comment]
Some of the surprise here is that until very recently (the last alpha or beta zero), Angular 2 did actually work if you loaded Zone via webpack. Perhaps that was an accident all along; but it is still surprising to find after working with this code for months to suddenly need to elevate this one library all the way up to its own script tag even though everything else can be loaded via the module system. It feels like a step backward, even though there are strong technical reasons behind it.

About JSPM: JSPM transforms files during "jspm install", so we can't merely script-src the angular2-polyfills.js file put in place by JSPM in jspm_packages/..../bundles.  That file is enhanced/damaged relative to the same file installed by NPM. I found that I needed to revamp my JSPM examples to also depend on Angular 2 via NPM, in order to grab the original angular2-polyfills.js.

**Comment by SonofNun15** [comment]
Related issue: https://github.com/angular/angular/issues/5304

**Comment by dblVs** [comment]
@pkozlowski-opensource I'll be closing this issue. Thanks for the help.

**Comment by dsebastien** [comment]
I agree with @kylecordes, this feels like a regression. I liked being able to only have SystemJS being loaded through a script tag; it felt cleaner. Of course we come from a world were everything was loaded through script tags, for people who have tasted the modular JS world, having to write <script ... again feels painful :)

**Comment by SonofNun15** [comment]
Once one library has to be loaded *before* SystemJS, where does it stop? I agree, ultimate we want to load SystemJS and then it loads *everything*. Ultimately ultimately we want SystemJS built into the browser so we just import our app and *everything* works. :grinning:

**Comment by playground** [comment]
Does angular2@2.0.0-beta.0 still require reflect-metadata zone.js es6-shim?

such as:
jspm install angular2@2.0.0-beta.0 reflect-metadata zone.js es6-shim

Loading zone.js via script tag
  <script src="jspm_packages/npm/zone.js@0.5.10/dist/zone.js"></script>
  <script src="jspm_packages/system.js"></script>
  <script src="config.js"></script>


I'm getting 
zone.js:1005 Uncaught RangeError: Maximum call stack size exceededobj.addEventListener @ zone.js:1005Zone.addEventListener @ core.js:89obj.addEventListener @ zone.js:1014Zone.addEventListener @ core.js:89obj.addEventListener @ zone.js:1014Zone.addEventListener @ core.js:89obj.addEventListener @ zone.js:1014Zone.addEventListener @ core.js:89obj.addEventListener @ zone.js:1014Zone.addEventListener @ core.js:89
ximum call stack size exceeded
	Evaluating http://localhost:8009/jspm_packages/npm/rxjs@5.0.0-beta.0/util/Immediate.js
	Evaluating http://localhost:8009/jspm_packages/npm/rxjs@5.0.0-beta.0/scheduler/AsapAction.js
	Evaluating http://localhost:8009/jspm_packages/npm/rxjs@5.0.0-beta.0/scheduler/AsapScheduler.js

**Comment by dlebedynskyi** [comment]
Is this still an issue with angular2.0.0.0-beta.1?
