### ISSUE TITLE
IE9

### ISSUE THREAD

**Issue by peteringram0** [angular/angular#5981]
Has IE9 been removed from the browser support? It does not run in IE9, 10+ works fine.

**Comment by pkozlowski-opensource** [comment]
It was _not_, see the green status from SauceLabs: https://github.com/angular/angular/blob/master/README.md

**Comment by mlaval** [comment]
A few more polyfills are required for IE9:
- classList, e.g. https://github.com/eligrey/classList.js
- requestAnimationFrame, e.g. https://gist.github.com/paulirish/1579671

On top, of that, you may want to mock the console object, something like this:
```
if (!window.console) window.console = {};
if (!window.console.log) window.console.log = function () { };
if (!window.console.error) window.console.error = function () { };
if (!window.console.warn) window.console.warn = function () { };
if (!window.console.assert) window.console.assert = function () { };
```

**Comment by peteringram0** [comment]
Thats a more helpful response. Thanks @miaval

**Comment by peteringram0** [comment]
The only error i have now within IE9 is the following: 

`Potentially unhandled rejection [2] Error: Object doesn;t support this action Error loading dist/boot.js`

Its any very descriptive :P Any ideas?

**Comment by mlaval** [comment]
Hard to say ... Could you share a reproducer in plnkr or any other way?

**Comment by wesleycho** [comment]
One also needs the URL polyfill for system.js: https://github.com/ModuleLoader/es6-module-loader/blob/master/src/url-polyfill.js

**Comment by justindujardin** [comment]
@peteringram0 There may be other polyfills you need. 

I saw the issue you had because I was using `matchMedia` and the `addListener` method on it, which the normal paulirish shim did not include.  

I had to add: https://github.com/paulirish/matchMedia.js/blob/master/matchMedia.addListener.js to make my build happy.

**Comment by pkozlowski-opensource** [comment]
Sounds like a case for a missing polyfill.
