### ISSUE TITLE
Test failures not reported without timeout

### ISSUE THREAD

**Issue by vavasilev** [angular/angular#5983]
Hello,

I have written unit test for my component, which uses TestComponentBuilder. Unfortunately the test always passes (even when it should fail). I noticed that adding the following line of code fixes the problem:
window.setTimeout(function() {}, 100);
However this does not seem natural to me.

I am attaching the test itself,

[collectionsAppSpec.ts.txt](https://github.com/angular/angular/files/65655/collectionsAppSpec.ts.txt)

Regards,
Vasil

**Comment by juliemr** [comment]
Hello @vavasilev 

Because your test is asynchronous, it will need to use `injectAsync` and return a promise. See the [injectAsync docs](https://angular.io/docs/ts/latest/api/testing/injectAsync-function.html). 

I realize that documentation on the right way to do unit tests is lacking. We're working on the [testing docs](https://angular.io/docs/ts/latest/testing/), which will be the place to learn about this.

**Comment by vavasilev** [comment]
Hi Julie,

The initial variant of the test was with injectAsync, but later, when I upgraded it stopped working for some reason. Then I found in "testing: use zones to avoid the need for injectAsync (0c9596a)" in changelog and removed my injectAsync.

Now I returned back to injectAsync but still have the problem described above: If I do not put "window.setTimeout(function() {}, 100);" the test never fails.

I am attaching the test again.

Regards,

Vasil
[collectionsAppSpec.ts.txt](https://github.com/angular/angular/files/66369/collectionsAppSpec.ts.txt)

**Comment by vavasilev** [comment]
One more note: everything was OK in 2.0.0-alpha.45. The problem started when I upgraded to 2.0.0-alpha.47

**Comment by vavasilev** [comment]
I found a solution: Put the following line at the beginning of my test: jasmine.DEFAULT_TIMEOUT_INTERVAL = 5000;
I am not sure, though, if this is ok, because I did not find any usage of DEFAULT_TIMEOUT_INTERVAL in Angular sources

**Comment by juliemr** [comment]
Could you make sure you are updated to the latest version? Alpha.47 is some versions ago.

**Comment by antonybudianto** [comment]
@juliemr : same issue here, please check at my [repo](https://github.com/antonybudianto/angular2-starter)
