### ISSUE TITLE
angular2/animate 404 (Not Found)

### ISSUE THREAD

**Issue by miqmago** [angular/angular#5984]
I've tried to import `angular2/animate` and I'm getting `GET http://127.0.0.1:8080/angular2/animate 404 (Not Found)`

I've been searching for `System.register("angular2/animate"` in whole `node_modules/angular2` with no success.

**Comment by pkozlowski-opensource** [comment]
Indeed, we don't include the `animate` barrel in any of the System.register bundles: https://github.com/angular/angular/blob/master/modules/angular2/docs/bundles/overview.md#systemjs-loader-users

@IgorMinar @matsko - shell we add it to the `angular2` bundle or create a separate bundle for it (kind of leaning towards it). Or we don't want to have  System.register bundles for animate?

**Comment by miqmago** [comment]
Is there an alternative way to make `animate` to work? I've been looking all around how to use animate with angular2 but couldn't find any example. In case you don't want to have System.register for animate, could you point me to a complete example on how to use animate with angular2 if it's already available? (which imports, scripts should be included in `index.html` and where the scripts are).

**Comment by ericmartinezr** [comment]
@miqmago I [answered] about this. You can check it out and play with the plnkr :D

**Comment by miqmago** [comment]
@ericmartinezr thanks, I've already seen your thread and it is the only live example I've found. I've noticed that I was importing 'angular2/animate' (what seemed logical to me) but it should be 'angular2/src/animate/animation_builder':

```javascript
import { AnimationBuilder } from 'angular2/src/animate/animation_builder'; // 'angular2/animate';
...
```

Is it going to change in the future?

**Comment by deeleman** [comment]
Dust is settling down on this one. Will the animation tokens be wrapped around `angular2/animate` anytime soon or will remain as is until the inception of ngAnimate 2.0?

**Comment by valorkin** [comment]
@miqmago you was right :)

**Comment by pkozlowski-opensource** [comment]
Closing since SystemJS bundles are gone and UMD bundles were re-organized so this one is no longer relevant.

**Comment by linuradu** [comment]
I've added the following 3 lines in System.config: and is working fine

System.config({
          packages:{
            format: 'register',
            defaultExtension: 'js'
          },
          map: {
            '@angular/animations': 'npm:@angular/animations/bundles/animations.umd.js',
            '@angular/animations/browser': 'npm:@angular/animations/bundles/animations-browser.umd.js',
            '@angular/platform-browser/animations': 'npm:@angular/platform-browser/bundles/platform-browser-animations.umd.js',
          }
      });
