### ISSUE TITLE
How properly handle http error exception.

### ISSUE THREAD

**Issue by tandu** [angular/angular#5985]
I have method that handles any error and passes http observable farther.
```typeScript
  private prepareRequest(response: Observable<Response>): any {
    let res = response.map(res => {
      try {
        return res.json();
      } catch(e) {
        throw(url + '. Wrong json');
      }
    })
    .share();

    res.subscribe(null, errorObject => {
      this.user.logout();
      console.log('errorObject:', errorObject);
    });
    return res;
  }
```

I get uncaught exception probably when I subscribe to response where I don't add error method. How to fix it? Should I put error handling empty method everywhere?

**Comment by tandu** [comment]
I have checked, it seems that I need to put error handling method everywhere. I think it should be better if error is once handled then exception shouldn't fire on any other subscribers.

**Comment by thelgevold** [comment]
Not sure I understand the question, but are you asking about error handling in http calls?

I have done something like this:

```
this.http.get('./friends2.json').map((res: Response) => res.json()).subscribe(
                res => this.result = res,
                error => this.error = error);
```
The subscribe method can take both a success handler and an error handler.

**Comment by tandu** [comment]
`prepareRequest` returns `Observer`. I subscribe to it that way 
```typeScript
this.prepareRequest(http.get(url)).subscribe(d => console.log(d))
```
 and I get exception. I have changed it to
```typeScript
import {noop} from 'angular2/src/facade/lang';
// ...
this.prepareRequest(http.get(url)).subscribe(d => console.log(d), noop)
```
and now it works fine.

**Comment by pkozlowski-opensource** [comment]
Sounds like this one got resolved.
