### ISSUE TITLE
HashLocationStrategy not working anymore with beta version

### ISSUE THREAD

**Issue by koblass** [angular/angular#5987]
Hi,

I was using the HashLocationStrategy location strategy with Angular alpha 48 and it was working like a charm.
Unfortunately this is not the case anymore.
I haven't change anything, still using the following code:
```
provide(LocationStrategy, {useClass: HashLocationStrategy})
```

But it's like the strategy is not changed.

Best
Daniel

**Comment by kylecordes** [comment]
My example routing code still works 100% OK in beta.0, including HashLocationStrategy. Maybe an example of a program showing the failure?

**Comment by btford** [comment]
@koblass – I also don't see any problems. Can you please provide a reproduction via [jsbin](http://jsbin.com/), [plnkr.co](http://plnkr.co), or [jsfiddle](http://jsfiddle.net/)?

Otherwise, I'm going to close this issue.

**Comment by koblass** [comment]
Ok, found out I think.
Nothing to do with Angular nor the router, but for some strange reason webpack doesn't take into account my changes to the bootstrap file, so changing the LocationStrategy there is not reflected :-(

Sorry for the noise, I've made some tests and the router is working as expected.
You can close the issue...

Best
Daniel
