### ISSUE TITLE
Changes are not applied from onload method.

### ISSUE THREAD

**Issue by tandu** [angular/angular#5988]
```typeScript
isLoading = false;

constructor(
  private cdRef: ChangeDetectorRef,
  private el: ElementRef
) {}

@Input() set url(val: string) {
  this.loadImage(url);
}

loadImage(url: string) {
  this.isLoading = true;
  let img = new Image();
  img.src = url;
  img.onload = _=> {
    this.isLoading = false;
    this.renderer.setElementStyle(this.el, 'background-image', 'url(' + url + ')');
      this.cdRef.detectChanges(); // BUGFIX: changes are not assigned otherwise
    };
  }
```
```html
<spinner *ngIf="isLoading"></spinner>
```
I have to force changes to be applied by manually invoking `detectChanges` otherwise spinner is always visible.

**Comment by robwormald** [comment]
try with addEventListener

**Comment by robwormald** [comment]
actually, i can't reproduce this with your code as is - do you have zone.js / angular2-polyfills.js included in your page?
http://plnkr.co/edit/mQ5axJJdkfny5WrYGepu?p=preview

**Comment by tandu** [comment]
I'm using angular2-seed, they are included.

**Comment by tandu** [comment]
It is strange, I definetly had this bug yesterday but now when I comment `detectChanges` in my code everything works fine.
