### ISSUE TITLE
ReferenceError: zone is not defined

### ISSUE THREAD

**Issue by PandaChauve** [angular/angular#5998]
node_modules/angular2/bundles/angular2-polyfills.js:1089:76
function patchEventTargetMethods

```
handler[boundFnsKey][eventType] = handler[boundFnsKey][eventType] || zone.bind(fn);
```

zone isn't defined, using global.zone is working

**Comment by robwormald** [comment]
are you including the polyfill as a script tag?

**Comment by PandaChauve** [comment]
Followed the 5min intro

    <script src="../node_modules/angular2/bundles/angular2-polyfills.js"></script>
    <script src="../node_modules/systemjs/dist/system.src.js"></script>
    <script src="../node_modules/rxjs/bundles/Rx.js"></script>
    <script src="../node_modules/angular2/bundles/angular2.dev.js"></script>
    <script src="../node_modules/es6-shim/es6-shim.js"></script>

    <script src="../bower_components/jquery/dist/jquery.min.js"></script>
    <script src="../bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

**Comment by gdi2290** [comment]
remove `<script src="../node_modules/es6-shim/es6-shim.js"></script>`

**Comment by PandaChauve** [comment]
If i remove es6-shim that the page won't even load on nwjs (ok in chrome).

Error: undefined is not a function
	Error loading file:///.../nwjs/app/boot.js
message: "undefined is not a function
	Error loading file:///.../nwjs/app/boot.js"
stack: "TypeError: undefined is not a function
    at createArrayFromMap (file:///.../node_modules/angular2/bundles/angular2.dev.js:784:43)
    at Function.MapWrapper.values (file:///.../node_modules/angular2/bundles/angular2.dev.js:830:14)
    at _createListOfProviders (file:///.../node_modules/angular2/bundles/angular2.dev.js:10297:36)
    at Object.resolveProviders (file:///.../node_modules/angular2/bundles/angular2.dev.js:10276:22)
    at Function.Injector.resolve (file:///.../node_modules/angular2/bundles/angular2.dev.js:11784:25)
    at Function.Injector.resolveAndCreate (file:///.../node_modules/angular2/bundles/angular2.dev.js:11787:40)
    at _createPlatform (file:///.../node_modules/angular2/bundles/angular2.dev.js:14720:34)
    at Object.platform (file:///.../node_modules/angular2/bundles/angular2.dev.js:14707:14)
    at Object.bootstrap (file:///.../node_modules/angular2/bundles/angular2.dev.js:25054:19)
    at execute (file:///.../nwjs/app/boot.js:15:23)

**Comment by gdi2290** [comment]
ok now that problem has to do with the nwjs environment

**Comment by pkozlowski-opensource** [comment]
@gdi2290 why were you suggesting removal of `es6-shim`? It is needed for non-ES6 browsers. 

I guess that just order of inclusion is not correct - it should go before zone.js. I would suggest including things in this order:

```javascript
<script src="../node_modules/es6-shim/es6-shim.js"></script>
<script src="../node_modules/angular2/bundles/angular2-polyfills.js"></script>
<script src="../node_modules/systemjs/dist/system.src.js"></script>

<script src="../node_modules/rxjs/bundles/Rx.js"></script>
<script src="../node_modules/angular2/bundles/angular2.dev.js"></script>
```

**Comment by prolink007** [comment]
Here is an issue i just opened with more specific reason for the failure and a work around fix.

https://github.com/angular/angular/issues/6007

**Comment by ericmartinezr** [comment]
A PR was sent for this issue https://github.com/angular/angular/pull/5995

**Comment by prolink007** [comment]
Yeah, just saw that. Failed some tests though. =(

**Comment by gdi2290** [comment]
@pkozlowski-opensource I thought it was included in the polyfill

**Comment by mahendra001** [comment]
Can anyone please help i am getting this error 
"**Error: NameList is not defined**"

**Comment by vicb** [comment]
outdated
