### ISSUE TITLE
JSONP doesn't work

### ISSUE THREAD

**Issue by neridonk** [angular/angular#6002]
can anyone explain to me why a simple JsonP get/request doesn't work?

    var url = 'http://jsonplaceholder.typicode.com/posts';
    this.jsonp.get(url).subscribe(results => console.log(results));

all i get is a strange error 

EXCEPTION: [object Object]
angular2.min.js:17 EXCEPTION: [object Object]t.logError @ angular2.min.js:17t.logGroup @ angular2.min.js:17e.call @ angular2.min.js:1(anonymous function) @ 
...

**Comment by PascalPrecht** [comment]
Can you use the unminified Angular 2 source so we can easier debug?

**Comment by neridonk** [comment]
EXCEPTION: [object Object]
angular2.js:23514 EXCEPTION: [object Object]BrowserDomAdapter.logError @ angular2.js:23514BrowserDomAdapter.logGroup @ angular2.js:23525ExceptionHandler.call @ angular2.js:1145(anonymous function) @ angular2.js:14801NgZone._notifyOnError @ angular2.js:5796collection_1.StringMapWrapper.merge.onError @ angular2.js:5700run @ angular2-polyfills.js:141(anonymous function) @ angular2.js:5719zoneBoundFn @ angular2-polyfills.js:111
angular2.js:23514 STACKTRACE:BrowserDomAdapter.logError @ angular2.js:23514ExceptionHandler.call @ angular2.js:1147(anonymous function) @ angular2.js:14801NgZone._notifyOnError @ angular2.js:5796collection_1.StringMapWrapper.merge.onError @ angular2.js:5700run @ angular2-polyfills.js:141(anonymous function) @ angular2.js:5719zoneBoundFn @ angular2-polyfills.js:111
angular2.js:23514 
...
...

STACKTRACE:BrowserDomAdapter.logError @ angular2.js:23514ExceptionHandler.call @ angular2.js:1147(anonymous function) @ angular2.js:14801NgZone._notifyOnError @ angular2.js:5796collection_1.StringMapWrapper.merge.onError @ angular2.js:5700run @ angular2-polyfills.js:141(anonymous function) @ angular2.js:5719zoneBoundFn @ angular2-polyfills.js:111
....
...


-----async gap-----
Error
    at _getStacktraceWithUncaughtError (http://localhost:5555/node_modules/angular2/bundles/angular2-polyfills.js:2195:26)
    at Zone.fork (http://localhost:5555/node_modules/angular2/bundles/angular2-polyfills.js:2253:40)
    at Zone.bind (http://localhost:5555/node_modules/angular2/bundles/angular2-polyfills.js:109:48)
    at HTMLScriptElement.obj.addEventListener (http://localhost:5555/node_modules/angular2/bundles/angular2-polyfills.js:1089:81)
    at e._subscribe (http://localhost:5555/node_modules/angular2/bundles/http.min.js:1:18554)
    at e.subscribe (http://localhost:5555/node_modules/rxjs/bundles/Rx.min.js:6:24405)
    at HomeCmp.klick (http://localhost:5555/dist/dev/components/home/home.js:18:29)
    at AbstractChangeDetector.ChangeDetector_HomeCmp_0.handleEventInternal (eval at <anonymous> (http://localhost:5555/node_modules/angular2/bundles/angular2.js:10897:14), <anonymous>:29:30)
    at AbstractChangeDetector.handleEvent (http://localhost:5555/node_modules/angular2/bundles/angular2.js:8788:22)
    at AppView.dispatchEvent (http://localhost:5555/node_modules/angular2/bundles/angular2.js:9396:39)

**Comment by neridonk** [comment]
ok tryed it with mapping : 

    var url = 'http://jsonplaceholder.typicode.com/posts';
    this.jsonp.get(url).map(res => res.text()).subscribe(
      data => this.datas= data,
      err => this.logError(err),
      () => console.log(this.datas)
    );
  logError(err) {
    console.error('There was an error: ' + err);
  }



Error was following :: 


There was an error: [object Object]HomeCmp.logError @ home.ts:43(anonymous function) @ home.ts:36t.error @ Subscriber.js:117t._error @ Subscriber.js:101t.error @ Subscriber.js:117d @ http.min.js:1run @ angular2-polyfills.js:138(anonymous function) @ angular2.js:5719zoneBoundFn @ angular2-polyfills.js:111

**Comment by ericmartinezr** [comment]
@neridonk to debug you should use the `dev` bundles (angular2.dev.js / http.dev.js)

**Comment by neridonk** [comment]
BrowserJsonp.send @ http.dev.js:466
(anonymous function) @ http.dev.js:814
e._subscribe @ Observable.js:118
e.subscribe @ Observable.js:74
HomeCmp.klick @ home.ts:34
ChangeDetector_HomeCmp_0
.handleEventInternal @ VM1839:29
AbstractChangeDetector.handleEvent @ angular2.dev.js:8788
AppView.dispatchEvent @ angular2.dev.js:9396
AppView.dispatchRenderEvent @ angular2.dev.js:9391

when i stringfy the "err"
 There was an error: {"_body":null,"status":200,"statusText":"Ok","headers":"[]","type":3,"url":null}

**Comment by oumayma-ltaief** [comment]
Hello Pascal,
I'm using angular-translate with StaticFilesLoader. Can you tell me a method on $translate that returns the key of the language activated at the time ? Thanks.

**Comment by neridonk** [comment]
okey i got it working by deactivating my ESET antivir holy crap thx
