### ISSUE TITLE
Unexpected token error when using router.

### ISSUE THREAD

**Issue by RobiFerentz** [angular/angular#6003]
When attempting to follow the instructions of the Crisis Center example, Adding a RouterConfig annotation or even adding the ROUTER_PROVIDERS to the bootstrap call will cause an unexpected token error.

![screen shot 2015-12-18 at 13 10 26](https://cloud.githubusercontent.com/assets/4889861/11895679/6b3183b0-a589-11e5-8b73-1e5ce0a978c4.png)

When running the plunker example locally (that is runtime transpiling with remote script tags), it works fine, but even when copying the plunker ts files into my own project and transpiling with 'npm start', the error appears.

**Comment by ericmartinezr** [comment]
@RobiFerentz you have to add the router bundle

For example
```
<script src=".../router.dev.js"></script>
```

**Comment by RobiFerentz** [comment]
![screen shot 2015-12-18 at 13 28 59](https://cloud.githubusercontent.com/assets/4889861/11895986/7332afe2-a58b-11e5-8c4d-934e51e7678b.png)

Well, that helped, but now there are other errors.
Also, adding the router bundle doesn't seem to be mentioned in the docs.

**Comment by ericmartinezr** [comment]
That error is helping you. You have to add either `<base href="...">` in your `<head></head>` or `provide(APP_BASE_HREF, {useValue : 'path'})` in your bootstrap.

**Comment by RobiFerentz** [comment]
Hmm. thanks. Is there an explanation why such an element is needed?

**Comment by gdi2290** [comment]
also make sure you don't use directives in `index.html` we don't use them in there for security and server rendering reasons. 
```html
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>

  <app>
    Loading...
  </app>

</body>
</html>
```
ensure that you bootstrap your top level component with the selector 'app' or we can change it a bit and use the selector 'div.app' with this document
```html
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>

  <div class="app">
    Loading...
  </div>

</body>
</html>
```

**Comment by RobiFerentz** [comment]
@gdi2290 , Not sure how your answer relates to this issue.
Also, I know you from the AngularAir vids. I feel like I met a celebrity... :smile_cat:

**Comment by gdi2290** [comment]
I thought you were using a directive for the body tag but it turns it was from the Colorzilla browser extension.

Thanks watching/listening to @AngularAir :+1: if you have any suggestions for us or feedback feel free to tweet us [AngularAir](https://twitter.com/AngularAir). If you're attending `ng-conf` or `ng-nl` you can meet us in person :smile:

**Comment by RobiFerentz** [comment]
I'm in Israel and I'm not Shai Reznik (though I know him), so chances are slim I'll be able to get to a conf anytime soon. I wish I could. You're doing just fine, only wish the audio was clearer sometimes.

BTW, do YOU know why the <base> element is required for routing? Normally it can create quite a bit of annoying issues with # anchor tags etc, so I'm wondering why it's in use.

**Comment by ShaneCourtrille** [comment]
I think rather then this being closed it should be changed to an issue with the docs not explaining the need to add the router.

**Comment by wardbell** [comment]
Actually it is and always was [in the router documentation](http://localhost:3000/docs/ts/latest/guide/router.html#!#getting-started).

Unfortunately, this instruction appears well down the page.  I'll add it also to the "Basics" section near the top.

@RobiFerentz - the `<base>` tag and `APP_BASE_HREF` are also prominently discussed in the doc in about the same place. It wasn't mentioned in the "Basics" section; I'll add it there too.

I have the feeling that people aren't reading the entire document. It is long with many nuances. Maybe there's a way to make it crisper. But the router is a complicated beast whose features aren't obvious and require considerable explanation.

I suggest you bear with the poor author and strive to take in what he's tried to say.

**Comment by ShaneCourtrille** [comment]
@wardbell I think it's more a consistency problem.  Most of the time the documentation will explicitly tell you what changes to make to which files.  The problem here is that in the first "Here are the application-specific files" on https://angular.io/docs/ts/latest/guide/router.html the index.html is not in the list showing the additional script.  If I had seen it there I wouldn't have had an issue.

**Comment by wardbell** [comment]
@ShaneCourtrille Totally with you and with @RobiFerentz .  I'm grateful for the feedback and I have updated the doc (to be published to web soon) such that these two important points are covered in the basics at the top.

I know also see that including the `index.html` in the final listings was insufficient; I'll add it to the first milestone listings as well.

Please ignore my tantrum. ;-)
