### ISSUE TITLE
Nested Form validation status not rolling up

### ISSUE THREAD

**Issue by srivch** [angular/angular#6004]
I have a property component and an address component. Each property has a physical and a billing address. In the property template to create a new property i have
	`<property>`
		`property fields like name etc.. with required attribute`
		`<address></address> (for physical address) - has required attributes as well`
		`<address></address> (for billing address) - has required attributes as well`
	`</property>`

The save button in property has a form.valid check to validate whether all required fields are entered. In the above case the save button is enabled once all required property fields are entered and it ignores the address component. How do we validate the entire form with the address components? [this used to work in angular 1.4]

**Comment by pkozlowski-opensource** [comment]
Angular 1 is here: https://github.com/angular/angular.js

**Comment by srivch** [comment]
The issue raised is for angular 2 and not for angular1. We are using beta0 (angular 2)

**Comment by pkozlowski-opensource** [comment]
> The issue raised is for angular 2 and not for angular1. We are using beta0 (angular 2)

This got me confused: this used to work in angular 1.4

Please provide a minimal, live reproduction scenario (plunker or similar) as otherwise it is not clear what you problem is.

**Comment by srivch** [comment]
We want the submit button to be enabled only after the required fields in the physical address section are entered.... (example uses Formbuilder)
http://plnkr.co/edit/scq69cH3mjXrjFZn7pPp?p=preview

**Comment by JohnCashmore** [comment]
Can this item be reopened, did you ever find a solution

**Comment by srivch** [comment]
Yes i did find a solution... the solution is to access the parent forms ngFormModel using the Host variable in child component and add the child form to the parent form. For example if you have a parent component named customer which has a ngformmodel defined in its html
`<form [ngFormModel]="mCustomerCG" #frm="ngForm"></form>`
and lets say you have a child component called address.. in the address component you can 
```
constructor( @Host() f: NgFormModel) {
  //storing the form reference in variable just in case its required elsewhere
  this.mParentForm = f;

// child components control group 
this.mAddressCG = new ControlGroup({
            "address1": this.cAddress1,
            "address2": this.cAddress2
});
//adding the child component to parent form
this.mParentForm.form.addControl(this.iName, this.mAddressCG);
}

```
Note: it does not have to be ngFormModel in the parent component, it can be ngForm as well.. but just that in the child component's constructor you will receive it as NgForm instead of NgFormModel.. and this can go to any number of levels...

Disclaimer: Not sure if this is the prescribed way to get it working...

**Comment by josephvano** [comment]
Ran into solving something similar to this and I accomplished this just by passing the form object in as an Input to the child components.

The docs have something similar to this
https://angular.io/docs/ts/latest/cookbook/dynamic-form.html

**Comment by Pruthwirajj** [comment]
Hi srivch, Can you please let me know what and how you implemented because i'm facing same issue.

**Comment by srivch** [comment]
there are two options
1. passing the parent components form as an input parameter to the child component. In the child component add the child component form / controls (or control group) to the parent form's (the input variable)... using the addControl option

2. the second option is to inject the parent form using 

```
 // Child component variables
//remember this will available only in ngAfterViewInit, if you try to access it elsewhere like nginit it will //not work
@ViewChild('childForm') mChildForm: NgForm; 
mParentForm: NgForm;
constructor( @Host() f: NgForm) {
    this.mParentForm = f;
}
ngAfterViewInit() {
    if (this.mChildForm != null) {
        if (!this.mParentForm.form.contains("childForm")) {
                this.mParentForm.form.addControl("childForm", this.childForm.form);
         }
    }
}

// if you have a control group you can add it in ngOnInit instead of ngAfterViewInit()
```
Hope it helps!!!

**Comment by Pruthwirajj** [comment]
Thanks Srivch, but I'm new in Angular, I didn't understand the above code. Can you please share the complete code, It helps me more. Thanks in advance.
