### ISSUE TITLE
zone is not defined in angular2@2.0.0-beta.0

### ISSUE THREAD

**Issue by prolink007** [angular/angular#6007]
Zone is not defined in the following files in `angular2@2.0.0-beta.0`.

```
angular2\es6\dev\src\core\zone\ng_zone.js
angular2\es6\prod\src\core\zone\ng_zone.js
angular2\src\core\zone\ng_zone.js
angular2\ts\src\core\zone\ng_zone.js
angular2\bundles\angular2-all.umd.dev.js
angular2\bundles\angular2-all.umd.js
angular2\bundles\angular2.dev.js
angular2\bundles\angular2.js
angular2\bundles\web_worker\ui.dev.js
angular2\bundles\web_worker\worker.dev.js
```

Changing the line of code from
`StringMapWrapper.merge(Zone.longStackTraceZone, { onError: function (e) { ngZone._notifyOnError(this, e); } });`
To
`StringMapWrapper.merge(zone.longStackTraceZone, { onError: function (e) { ngZone._notifyOnError(this, e); } });`
Fixes the issue. Notice the capitalization change. There is no `Zone`, but a parameter `zone`.

This is breaking builds. How long can we expect this to take to fix?

Link to pull request https://github.com/angular/angular/pull/5995

Thanks

**Comment by pkozlowski-opensource** [comment]
@prolink007 all the files you are mentioning are generated from https://github.com/angular/angular/blob/master/modules/angular2/src/core/zone/ng_zone.ts

So if there is a pb, it needs fixing there.

**Comment by nesukun** [comment]
I've noticed this problem when updating to beta 0, but it seems to only affect my app on dev mode. using prod mode as a workaround currently fixes the issue for me

**Comment by prolink007** [comment]
@pkozlowski-opensource Yeah, you're right. I was just posting the places where it failed.

Here is the TS file that needs to be changed.

C:\projects\TampaApps\NewsApp\node_modules\angular2\ts\src\core\zone\ng_zone.ts@352

**Comment by ciriarte** [comment]
Hi guys, I opened I PR last night with a potential fix #5995

**Comment by prolink007** [comment]
@ciriarte I saw that earlier. Seems like it failed one of the tests.

**Comment by towa48** [comment]
fix ng_zone.ts with check for long-stack-trace-zone.js
```javascript
if (enableLongStackTrace && zone.longStackTraceZone) {
    errorHandling = collection_1.StringMapWrapper.merge(zone.longStackTraceZone, { onError: function (e) { ngZone._notifyOnError(this, e); } });
}
```

**Comment by vicb** [comment]
outdated
