### ISSUE TITLE
styling:markdown

### ISSUE THREAD

**Issue by usernamealreadyis** [angular/angular#6017]
Utha:seda/c:c/c:sudoku:param
[openid_certified (1) (1) (1).tiff](https://files.zenhub.io/5674bdac20b75d5d6e2691cf)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by benlesh** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists please open a new issue and provide a StackBlitz reproducing the problem and describing the difference between the expected and current behavior. You can use this StackBlitz template: https://stackblitz.com/fork/angular-gitter
