### ISSUE TITLE
strict:bug

### ISSUE THREAD

**Issue by usernamealreadyis** [angular/angular#6021]
< --|param:log|-- >
.travis.yml
< --|param:log|-- >
language: ruby
rvm:
- "1.8.7"
- "1.9.2"
- "1.9.3"
- rbx
  # uncomment this line if your project needs to run something other than `rake`:
  # script: bundle exec rspec spec

**Comment by benlesh** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists please open a new issue and provide a StackBlitz reproducing the problem and describing the difference between the expected and current behavior. You can use this StackBlitz template: https://stackblitz.com/fork/angular-gitter
