### ISSUE TITLE
bumb:down

### ISSUE THREAD

**Issue by usernamealreadyis** [angular/angular#6022]
language: ruby
rvm:
- "1.8.7"
- "1.9.2"
- "1.9.3"
- rbx
  # uncomment this line if your project needs to run something other than `rake`:
  # script: bundle exec rspec spec
  [openid_certified (1) (1) (1).tiff](https://files.zenhub.io/5674f81020b75d5d6e269267)
  Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by benlesh** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists please open a new issue and provide a StackBlitz reproducing the problem and describing the difference between the expected and current behavior. You can use this StackBlitz template: https://stackblitz.com/fork/angular-gitter
