### ISSUE TITLE
Broken link Routing & Navigation

### ISSUE THREAD

**Issue by Eslem** [angular/angular#6025]
The link for APP_BASE_HREF in DEVELOPER GUIDES (https://angular.io/docs/ts/latest/guide/router.html ) just before #-hashlocationstrategy- is broken, i think should point to https://angular.io/docs/ts/latest/api/router/APP_BASE_HREF-let.html

**Comment by wardbell** [comment]
Good catch. Fixed in [angular.io PR #637](https://github.com/angular/angular.io/pull/637) which will be published very soon.

**Comment by gkalpak** [comment]
Closing as https://github.com/angular/angular.io/pull/637 has been merged.
