### ISSUE TITLE
Order of Providers at Bootstrapping

### ISSUE THREAD

**Issue by zamamohammed** [angular/angular#6026]
While playing with Angular 2, I realized that the order of providers at bootstrapping is important, but I did not understood why. It would be great if someone can explain it.

HASHLOCATIONSTRATEGY DID NOT WORK
```javascript
bootstrap(APP, [JSONP_PROVIDERS, provide(LocationStrategy, { useClass: HashLocationStrategy }), provide(APP_BASE_HREF, {useValue: '/'}), ROUTER_PROVIDERS]);
```

HASHLOCATIONSTRATEGY WORKED
```javascript
bootstrap(APP, [JSONP_PROVIDERS, ROUTER_PROVIDERS, provide(LocationStrategy, { useClass: HashLocationStrategy }),provide(APP_BASE_HREF, {useValue: '/'})]);
```

**Comment by pkozlowski-opensource** [comment]
> It would be great if someone can explain it.

So, in the end of a day we need a _list_ (an array) of providers. But `JSONP_PROVIDERS` and  `ROUTER_PROVIDERS ` are arrays themselves (containing default providers, `LocationStrategy ` being one of them). So in your example we are providing an array of arrays. But once again, we can't have multiple providers for one key, so an array of arrays is flattened and duplicates are discarded. 

The algorithm of flattening / duplicates discarding will override "earlier" providers with "later" ones. So if you want to override defaults (which I understand is your intention) you need to list them _after_ defaults.

**Comment by PascalPrecht** [comment]
To be technically correct, we *can* have multiple providers for a single key as explained here http://blog.thoughtram.io/angular2/2015/11/23/multi-providers-in-angular-2.html
