### ISSUE TITLE
how to render escaped html

### ISSUE THREAD

**Issue by jzlxiaohei** [angular/angular#6027]
code：

    <div>
        {{content}}
    </div>

`content` will be  sanitized.

Is there a way to render escaped html?

**Comment by alexpods** [comment]
I think, `innerHTML` and `outerHTML` are what you're looking for (see [this plunk](http://plnkr.co/edit/oLhVH3kYrvjE89mehnoR?p=preview)):

```html
<div [innerHTML]="content"></div>
```

**Comment by jzlxiaohei** [comment]
@alexpods thank you very much. I find some articles says  it was `[inner-html]`. I forget that it is `camelCase` now (~_~!)
