### ISSUE TITLE
Quickstart for JS has a Faux-Pas Faux-Pas!

### ISSUE THREAD

**Issue by ckapilla** [angular/angular#6029]
This sentence in the Javacript Quick start: 
_Most application files export one thing into our faux-pas 'namespace_ 
should read 
_Most application files export one thing into our faux 'namespace'_ 
(The namespace is not an " an embarrassing social mistake", it is simply "fake".

**Comment by pkozlowski-opensource** [comment]
Closing as a duplicate of https://github.com/angular/angular.io/pull/593
