### ISSUE TITLE
Do Angular forms support the HTM5 "form" attribute on inputs

### ISSUE THREAD

**Issue by TheHandsomeCoder** [angular/angular#603]
I'm making use of the HTML5 "form" attribute on a few of my inputs as they're contained in a table that doesn't lend itself to being wrapped in a form correctly. By using the form attribute I can still make use of the ng-submit form attribute to submit my form, however when I pass the form with my submit function it doesn't have any of the additional inputs available on it that are outside the form.

My assumption is that this is due to the form directive not having access to the part of the DOM where these inputs are and this can't attach them to the form object. Is there any information on this that I could look at, or is there plans for this in a later version of angular?

**Comment by mhevery** [comment]
Can you makes sure we support this use case?

**Comment by vsavkin** [comment]
I believe we will be able to support this use case. 

In Angular2 the input handling is not tied to html forms. 

So you can have something like this:
 
```
<div #personform [new-control-group]="personForm">
  <input control="name">

  <form (submit)="submitForm(personform.value)">
    <input control="age">
  </form>
</div>
```

submitForm will receive an object containing both name and age.

**Comment by mhevery** [comment]
closing as this is already possible

**Comment by Shikoruma** [comment]
Is it still possible after the RC5 ?

I try the solution of vsavkin but I got the following error :
Can't bind to 'new-control-group' since it isn't a known property of 'div'
