### ISSUE TITLE
EXCEPTION: Template parse, special char with utf8

### ISSUE THREAD

**Issue by mkg0** [angular/angular#6036]
hi

i want show some special characters for template in a html file. when i try to save the file with utf8 encoding, i got this error:

`Error: Template parse errors:`
`Unexpected closing tag "iv>" ("<div class="icerik">İ<[ERROR ->]/div>`
`"): girisComponent@0:22`

for this --> `<div class="icerik">İ</div>`

but

`<div class="icerik">ĞÜşçö#$%&?_?=-*0+and other characters</div>` -> its fine

**Comment by MuhammedHasan** [comment]
Yes, I also have same issue. All Turkish character is OK but 'İ' . 

Thanks for reporting issue and pull request.
