### ISSUE TITLE
I am not getting standard mobile behavior with bootstrap3 navbar and beta0

### ISSUE THREAD

**Issue by user414** [angular/angular#6037]
This might have nothing to do with bootstrap and perhaps just an underlying bug but I'm not getting the standard mobile menu bar from bootstrap 3. This was with beta0 but didn't try it with other versions. With a compliant browser and the html below on a mobile, or emulation, you get the standard mobile square menu but if you use the same nav code in angular2 you only get the standard desktop version. Disregard the collapse behavior will wire that later. 

```
<html>
<head>
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
</head>
<body>
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#">Brand</a>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
				<li><a href="#">Link2</a></li>
				<li><a href="#">Link3</a></li>
				<li><a href="#">Link4</a></li>
				<li><a href="#">Link5</a></li>

			</ul>

		</div>
		<!-- /.navbar-collapse -->
	</div>
	<!-- /.container-fluid -->
</nav>
</body>
</html>
```

**Comment by PascalPrecht** [comment]
Since this is really just CSS, I don't think this is a problem with Angular. Can you create a plunk that demonstrates your issue though?

The given snippet unfortunately doesn't help here.

**Comment by user414** [comment]
Will do, is there a template plunk you know of somewhere I could fork from?

**Comment by user414** [comment]
Sorry had pushed the close by mistake

**Comment by PascalPrecht** [comment]
This should help you getting started http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5

**Comment by user414** [comment]
Ok turned out it was my problem, had forgotten that the dom is not ready at the end of the body was loading some bootstrap related js for collapse behavior and this was in part the problem. Just going with doing the collapse in pure angular2 with event and hidden instead. Thanks and sorry for that.
