### ISSUE TITLE
Tour of Heroes tutorial has broken md file links

### ISSUE THREAD

**Issue by apoku** [angular/angular#6039]
Throughout the "Tour of Heroes" for typescript tutorial there are inline references that do not render...

There are quite a few instances of:

BAD FILENAME: ../../../_fragments/toh-3/ts-snippets/app/mock-heroes-mocking-heroes.ts.md   Current path: docs,ts,latest,tutorial,toh-pt4 PathToDocs: ../../../

I'm seeing it in the Part 4 and Part 5 sections.

**Comment by neilyoung** [comment]
+1 
Part 4 has no problems except a little bug, but the entire tutorial seems to be not finished yet. When will it be available? The interesting parts (routing) are missing...

**Comment by rjmccluskey** [comment]
+1
I'm also curious when the other parts of the tutorial will be available

**Comment by Larsouille** [comment]
+1
