### ISSUE TITLE
Setting up model-based form triggers classic "expression changed after it was checked" error.

### ISSUE THREAD

**Issue by nosachamos** [angular/angular#6041]
In alpha 45, I could set up a form using form builder within a component's constructor. I could also use the control's valid and touched to show/hide error messages.

However, after upgrading to Beta 0, I get the classic "Expression 'xxx' has changed after it was checked." error. 

I'm guessing angular form will create those controls and set those values during the form creation, which will change the value of flags that are bound to in the template - all of that without triggering another round of change detection, so therefore the exception. However, I can't seem to find an appropriate way of setting up this form anymore. It seems FormBuilder should be triggering another round of change detections after initializing a form to avoid this common scenario.

Here is the plunker:

http://plnkr.co/edit/e5qAW6ywgJ8C0dNd91KQ?p=preview

There are other issues opened about this exception, most due to changes to boud properties within lifecycle hooks, but this one is different in the sense that FormBuilder is making the changes, and it seems to be preventing users from setting up model-based forms.

An option is to use `ChangeDetectionStrategy.OnPush`, but it'd be at the very least wierd to require this for any component setting up a model-based form. Having the FormBuilder trigger another round of change detection seems a far better approach.

**Comment by rosendi** [comment]
https://github.com/angular/angular/issues/5992

**Comment by kara** [comment]
@nosachamos  Thanks for reporting!  A lot has changed with forms since beta.0, so it looks like your problem has been resolved.  See this updated plunker:

https://plnkr.co/edit/pr3YuLeJF2SgScImw1KF?p=preview

As long as you use Validators.required, you shouldn't see a change detection error. Please feel free to re-open if you run into any additional issues with this in RC.4 or onward.

**Comment by nosachamos** [comment]
Thanks for the update @kara !
