### ISSUE TITLE
Adding SVG elements to html_tags.ts

### ISSUE THREAD

**Issue by gionkunz** [angular/angular#6043]
Currently only the SVG element is configured within the `html_tags.ts` file. Should we add default namespace for all SVG elements? Otherwise all SVG elements need to be written using `svg:` prefix on elements which does not really feel like writing modern SVG in the browsers today.

https://github.com/angular/angular/blob/080469f8e6692c7865fbd574aadd9be06ba35c55/modules/angular2/src/compiler/html_tags.ts#L383

**Comment by Tragetaschen** [comment]
An `<svg>`-element switches the parser to "SVG mode" so any child SVG-element doesn't need to be prefixed with the namespace. The `svg:` prefix is only needed when you have a template that starts "in the middle of an SVG" like `template: '<svg:g><rect/></g>'` and then only on the template's root element. In that case this disambiguates between the SVG element `g` and an HTML component `g`.

#5547

**Comment by pkozlowski-opensource** [comment]
@Tragetaschen is perfectly right on this one. Thnx.

**Comment by gionkunz** [comment]
Okay, thanks for explaining. Isn't there a way the parser can inherit its state through the component sub-tree? I kind of dislike the idea that I need to wrap all my component content into a single root element. There's already the host element that is a single root element and this would lead to an additional unnecessary element.

Given the example:

```javascript
import {Component} from 'angular2/angular2';

@Component({
  selector: '[graphic]',
  template: `
    <svg:g>
      <rect x="0" y="0" width="100%" height="100%" fill="gray"></rect>
    </svg:g>
  `
})
export class Graphic {}


@Component({
  selector: 'app'
  template: `
    <svg width="100%" height="100%">
      <g graphic></g>
    </svg>
  `,
  directives: [Graphic]
})
export class App {}
```

Would always lead to the following DOM:

```html
    <svg width="100%" height="100%">
      <g graphic>
        <g>
          <rect x="0" y="0" width="100%" height="100%" fill="gray"></rect>
        </g>
      </g>
    </svg>
```

The additional group element is unnecessary and its only purpose is to work around the issue that the parse can't detect the namespace automatically. Wouldn't it be nicer if the parser could know the current namespace from the context of the parent component already?
