### ISSUE TITLE
Mulit-line expressions are not working

### ISSUE THREAD

**Issue by doliver3** [angular/angular#6044]
Mulit-line expressions are not working.

If I put this in the template:

Ok: {{  "Hello " + "World on one line" }} <br/>
Not Ok: {{  "Hello " +
         "World split" }}

I get this output where the expression was not parsed for the expression split on multiple lines:

Ok: Hello World on one line 
Not Ok: {{ "Hello " + "World split" }} 

I'm using the latest beta version: 2.0.0-beta.0"

**Comment by wesleycho** [comment]
To describe this in depth since there is not enough detail here, Angular 2 does not throw an error, but instead just handles it this way

Input
```html
{{ 'foo' +
    'bar'}}
```
Output
```html
{{'foo' + 'bar'}}
```
It strips out the new line character, but does not actually interpolate.

**Comment by PascalPrecht** [comment]
Is this really a bug? Could we do multiline expressions in ng1?

**Comment by wesleycho** [comment]
@PascalPrecht just opened a PR fixing this - turns out the fix is super simple, and probably should be supported (although one should probably avoid doing complex expressions in the template itself for maintenance/testability reasons).

**Comment by michalstepien** [comment]
In beta 15, working . Example:
[http://plnkr.co/edit/dt3mEhJTyM7vYs6eINtl?p=preview](http://plnkr.co/edit/dt3mEhJTyM7vYs6eINtl?p=preview)

**Comment by wesleycho** [comment]
Yep, this can be closed, the fix got merged in a few months ago

**Comment by pkozlowski-opensource** [comment]
Thnx @michalstepien and @wesleycho ! Closing.
