### ISSUE TITLE
ngContent does not work on root component

### ISSUE THREAD

**Issue by veches** [angular/angular#6046]

**Comment by gdi2290** [comment]
related
https://github.com/angular/angular/issues/1858
https://github.com/angular/angular/issues/4946
https://github.com/angular/angular/issues/4921

**Comment by veches** [comment]
I cannot get much out of the mentioned related issues.
what I am trying to do is
   -- something equivalent to ng-app in angular 1
   -- root component without template or that can transclude.

**Comment by pkozlowski-opensource** [comment]
Closing as a duplicate of #1858
