### ISSUE TITLE
NgClass doenst evalute when object changes

### ISSUE THREAD

**Issue by era** [angular/angular#605]
We have faced a problem in our project using ngClass, we had an ajax call that return an array of objects. We wanted to use a property of the object as a css class if some other property was 50. Like the example above:
```
<span ng-class={
              'something': {{ajax_array[0].type == 10}},
              '{{ajax[0].rightClass}}':{{ajax_array[0].type == 50}}
}>Test</span>
```

When the span tag is rendered and the ajax call is not yet finish the ng-class doesn't choose any class (What is the expected).  But when the ajax call is finished and the condition ajax_array[0].type == 50 is true the ng-class did not changed. We inspected the element via chrome and 'OurDinamicClass': true appeared on the element, so we are not sure why this didn't work.

 To fix it we put an <div ng-if="ajax_is_finished"> before this span.

I'm not certain that this is a bug, but is a strange behavior so we decided to report.

**Comment by rkirov** [comment]
sounds like angular 1.x question, this is angular 2 repo. Reopen the issue at https://github.com/angular/angular.js
