### ISSUE TITLE
A freshly generated SVG doesn't render correctly in Edge

### ISSUE THREAD

**Issue by Tragetaschen** [angular/angular#6050]
I haven't seen this before the introduction of the new parser (alpha.46 and below). When I refresh my page with a rather large, generated SVG, the first thing Edge renders is this:

![broken-before](https://cloud.githubusercontent.com/assets/1947968/11928131/988cceec-a7d1-11e5-8f33-bfdac008de09.png)
Once I "do something" like clicking, the elements magically move to the expected position:
![working-after](https://cloud.githubusercontent.com/assets/1947968/11928330/c70c64fc-a7d2-11e5-9e82-49f9f860f47e.png)

I cannot really put my finger on what's going on, for example the time at the top center ("10:33") is literally just a `<text>` element with those five characters. Maybe angular needs to instruct Edge to do some sort of layout refresh when adding new elements via DOM?

**Comment by Tragetaschen** [comment]
One thing that's quite peculiar are the element attributes:
![attribute-capitalization](https://cloud.githubusercontent.com/assets/1947968/11937329/f325ea9a-a813-11e5-8de2-e6eca7c3f5ee.png)
Note that the `text` element has all-capital `FONT-SIZE`, `FONT-WEIGHT` and `FILL` while the `path` below has `fill` and `d` as expected with lower case.

**Comment by vicb** [comment]
- What angular version do you use ?
- Any chance you can share the source code for a small repro case ?

**Comment by Tragetaschen** [comment]
Version is beta.0.

I cannot share the application, however, I will try to further reduce the problem. From what I can see, though, only `text` elements seem to be affected.

**Comment by Tragetaschen** [comment]
I have reduced my code insofar that I can reasonably exclude angular2 as the culprit. I can now create the layout issue (albeit in an ngOnChanges method) when d3 is setting a rotation attribute (to the same value as before!) with a width="100%" svg element somewhere above.

**Comment by Tragetaschen** [comment]
If someone is interested:
https://connect.microsoft.com/IE/feedbackdetail/view/2157763/sometimes-svg-elements-vanish-or-render-incorrectly-when-setting-attributes-via-javascript
