### ISSUE TITLE
binding to getter function that returns a new array with the same elements causes an exception in dev mode

### ISSUE THREAD

**Issue by robianmcd** [angular/angular#6057]
If I have a getter function in my component like this:

```
getFilteredObjs() {
    return this.objs.filter((obj) => {
        //...
    });
}
```

And I bind to it like this:

```
<div *ngFor="#obj in getFilteredObjs()">
    ...
</div>
```

Then I will get an "Expression has changed after it was checked" exception. I get that this is happening because in dev mode angular will call the function a second time and it will return a different array instance on each call. What is the best way to avoid this exception? I've come up with the following solutions but I'm wondering if there is a simpler way.

1. I assume I could solve this with a custom pipe but that feels like a bit of over kill if the filtering logic is simple and only used in one component.

2. I could watch all the events that might cause the output of this function to change and manually update some extra state on my controller that would store the filtered objects.However that would require more state and potentially a lot more code if there were a lot of events that might change the array of objects being filtered.

3. I could use something like underscore to memoize the function and return the same instance of an array if the inputs haven't changed. This seems like a leaky abstraction though so I'd rather not have to do that.

Any other ideas? Or is one of the ideas I've mentioned my best bet?

**Comment by thelgevold** [comment]
I think the most standard way of solving this is some variation on the following:
```
this.filteredObjs = getFilteredObjs(); 

.....

<div *ngFor="#obj in filteredObjs()">
    ...
</div>
```

**Comment by robianmcd** [comment]
@thelgevold would you still take that approach if there are several things that could cause the result of `getFilteredObjs()` to change. E.g. whenever an http call finishes the underlying array of objects gets updated so `this.filteredObjs` would need to be recalculated. Or whenever a use types something into a search field the function might filter out different items so you'd have to watch for DOM events on that field and update `this.filteredObjs` whenever one is fired.

**Comment by thelgevold** [comment]
Probably since you have to mutate the array somewhere in all cases - even with the original code where the getter is called from the view. 

It's probably the same amount of work to mutate ```this.objs``` directly vs reassigning '''filteredObjs'''.

**Comment by robianmcd** [comment]
The nice thing about the original code where the getter is called from the view is that there is only a single source of truth. The `this.filteredObjs` field is just generated from other state fields so storing it separately opens up the potential for inconsistencies within the component's state.

Anyway thanks for the feedback. Just wanted to make sure there wasn't some feature of Angular that I was totally missing. I haven't used pipes before so maybe I'll try refactoring the `getFilteredObjs()` function into a "pure" pipe and see if that solves the change detection issue without loosing the single source of truth.

**Comment by thelgevold** [comment]
I actually ran into the same issue a few days ago. There is some discussion here that you might want to check out: https://github.com/angular/angular/issues/5918

**Comment by robianmcd** [comment]
Thanks! Looks like it's still up in the air how angular will handle this so I'll keep an eye on the issue you linked to
