### ISSUE TITLE
Add support for anonymous functions

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#6059]
To be able to implement ngFor.trackBy, we need to add support for anonymous functions or closures.

```
<div *ngFor="#item of items; trackBy: _ => _.id>
  {{item.text}}
</div>
```

You should be able to access local variables and context in an anonymous function.

**Comment by kylecordes** [comment]
I can see why this is necessary to implement "track by" in a completely generic way. But I wonder if it is really the best answer - do we want to live in a world where people write JavaScript like functions (in a sort of semi-JavaScript, angular expression language) inside strings inside HTML templates? In the long run I wonder if the Angular developer community would be best served by making the expression language as weak as possible.

**Comment by wardbell** [comment]
A less risky but useful alternative would be an alternative syntax in which you name the properties of the object, e.g.:
```
<div *ngFor="#item of items; trackBy:'id'>
<div *ngFor="#item of items; trackBy:'lastName,firstName'>
```
This is sugar. `ngForTrackBy` turns it into `_ => _.id` and `_ => mash(_.lastName,_.firstName)` where `mash` is whatever we think is an efficient, unique outcome.

**Comment by vicb** [comment]
closing as `TrackBy` has been implemented has been implemented a while ago
