### ISSUE TITLE
Add support for role and aria- attribute bindings.

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#606]
Angular 2 only currently supports data binding to *properties*. All of the ARIA spec, however, is an extension to HTML that relies on *attributes*. 

The end result would need to allow the user to do things like this:
```html
<div class="star" 
    role="checkbox" 
    [aria-checked]="isFavorite" 
    aria-label="Favorite"
    (click)="toggleFavorite()"></div>
```

**Comment by pkozlowski-opensource** [comment]
If nothing changed recently, based on discussion with @mhevery we are going to special-case this in a compiler for now.

**Comment by mhevery** [comment]
That is correct. Looking forward to the PR.

**Comment by pkozlowski-opensource** [comment]
We've got initial (to be improved) support for binding to `aria-*` attributes via 1846ce8c687b9ce86c2802876b564f4fd8041bf1

**Comment by pkozlowski-opensource** [comment]
Initial support for `role` attr bindings added via 92afad6ebcb7d375bfffdd9c72017d6438351035.

**Comment by pkozlowski-opensource** [comment]
I guess the next step is to improve the existing impl based on @yjbanov [idea](https://github.com/angular/angular/pull/643#issuecomment-74354425). @yjbanov ping me whenever you've got time to discuss.

**Comment by pkozlowski-opensource** [comment]
I think that we can close this one as the support for role and aria- attributes is in master. What reminds to be done is a refactoring that would remove special casing but I'm going to tackle this as part of #773
