### ISSUE TITLE
Http: RequestOptions.merge does not combine headers or search params

### ISSUE THREAD

**Issue by escardin** [angular/angular#6060]
When headers or search is present on both the base options and the to be merged options, the to be merged options overwrite, rather than combine with the base options.

This makes things like setting a default Content-Type while providing headers for other purposes impossible.

https://github.com/angular/angular/blob/master/modules/angular2/src/http/base_request_options.ts#L94-L97

Headers should be able to merge with each other, overwriting on a per header basis.

The same problem applies to search params. I suppose it could apply to other things, but method, body and url are all strings at this time.

**Comment by robwormald** [comment]
The tricky thing here is what we do when there's a conflict - headers, for example, can be appended (additive) or set (replacement) to the Headers object - so the expected behavior is sort of ambigious. I'm honestly not in love with the current API nor making override a thing. Needs some consideration in either case.

**Comment by escardin** [comment]
My use case for this is with angular2-jwt, while accessing an API. I want to be able to set my default content type to json, and then append an auth header via the jwt wrapper, while still adding my own headers for some requests, or changing the content type to something else.

I have a PR in with the jwt library to get it to match the Http API so that it is a drop in replacement. It would be nice to take it a step further and be able to compose wrappers together and expect it to work within reason. That's not really going to work without merging or replacement of individual header entries.

**Comment by pmulac** [comment]
I am surprised that default ("base") headers aren't merging with "provided" headers.  Like @escardin says, this approach makes it impossible to set default/global headers alongside specific case-by-case headers.  For example, I need to set a global header that is sent on every request, but I also need to set specific content-types for some of my services.  My services shouldn't need to know about global headers and manually append them before the http client "merges" (overrides(!)) them.

I see that a common recommendation is to extend the Http class, but I would prefer a more composable approach.

**Comment by vicb** [comment]
Could someone add a repro (plunker) here ? (based on angular 2.0.1) Thanks.

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by alirezamirian** [comment]
@robwormald You are right, there can be different possible strategies for merging, but these can be provided as options to `.merge()` method. I have some ideas about flexible implementation of these merge options.
