### ISSUE TITLE
$q Promise API chaining behavior

### ISSUE THREAD

**Issue by phsstory** [angular/angular#6068]
I may or may not be reading the spec https://promisesaplus.com/#point-64 2.3.4 correctly, but I my interpretation suggests these is a bug in the chaining logic.

2.3.4 suggests that in a chain, if the resolved or rejected callback do not return a value, the next in the chain should be resolved or rejected with the original value in turn.

Please see http://plnkr.co/edit/9Di1pjjcPdTZI7FsXID3?p=preview as an example

The only other option i see is the undefined behavior state in the spec involving 2.2.7.1 where neither onFilfilled nor onRejected returns a value, but in such a situation, I feel the specificity of 2.3.4 supersedes the undefined behavior.

If this ticket is deemed not a bug, I would suggest updating the docs to mention that all onFulfilled or onRejected callbacks should, at the least, return the original result

**Comment by robwormald** [comment]
@phsstory this is the angular2 repo, you want https://github.com/angular/angular.js :+1:
