### ISSUE TITLE
Cleanup npm publish

### ISSUE THREAD

**Issue by tbosch** [angular/angular#607]
Rename `rtts_assert` as `ng2_rtts_assert`

1. Rename source folder `moduels/rtts_assert` to `modules/ng2_rtts_assert`
2. Change transpile options in `gulpfile.js` to use `ng2_rtts_assert` instead of `rtts_assert`
3. Change `modules/angular2/package.json` to depend on `ng2_rtts_assert`
4. Change `mdoules/ng2_rtts_assert/package.json` to use `ng2_rtts_assert` as name

Rename npm name of angular to `angular2`:

1. change `name` in `modules/angular2/package.json`

Publish changes packages for angular and ng2_rtts_assert to npm:

1. adjust script `scripts/publish/npm_publish.sh` to use new path for `ng2_rtts_assert`
1. adjust the script to not use the `ng2` prefix for the npm tag name
2. run `scripts/publish/npm_publish.sh`

Unpublish previous 2.0.0-* versions via `npm unpublish` for:
- `angular` npm repo
- `rtts-assert` npm repo

**Comment by yjbanov** [comment]
I don't have access to NPM to actually publish/unpublish things, but sent #634 with relevant code changes.

**Comment by yjbanov** [comment]
Published as the following packages:

angular2
angular2-benchpress
rtts-assert
