### ISSUE TITLE
ngFor doesn't work in Dart beta.0  

### ISSUE THREAD

**Issue by zoechi** [angular/angular#6070]
> Build error:
Transform TemplateCompiler on ng_for|lib/app_element.ng_meta.json threw error: Template parse errors:
Property binding ng-forOf not used by any directive on an embedded template ("<h1>app-element</h1>
[ERROR ->]<span *ng-for="#f of fruits; #i = index">
  <div>{{i}}<span>{{f}}</span></div>
</span>
"): AppElement@1:0
package:angular2/src/compiler/template_parser.dart 112              TemplateParser.parse
package:angular2/src/compiler/template_compiler.dart 260            TemplateCompiler._processTemplateCodeGen
package:angular2/src/compiler/template_compiler.dart 212            TemplateCompiler.compileTemplatesCodeGen.<fn>
dart:core-patch/array.dart 77                                       List.forEach
package:angular2/src/compiler/template_compiler.dart 208            TemplateCompiler.compileTemplatesCodeGen
package:angular2/src/transform/template_compiler/generator.dart 64  processTemplates.<async>.<fn>.<async>
dart:async/future.dart 144                                          Future.Future.microtask.<fn>
dart:async/zone.dart 907                                            _rootRun
dart:async/zone.dart 802                                            _CustomZone.run
dart:async/zone.dart 735                                            _CustomZone.bindCallback.<fn>
dart:async/schedule_microtask.dart 41                               _microtaskLoop
dart:async/schedule_microtask.dart 50                               _startMicrotaskLoop
dart:isolate-patch/isolate_patch.dart 96                            _runPendingImmediateCallback
dart:isolate-patch/isolate_patch.dart 149                           _RawReceivePortImpl._handleMessage
> 
package:angular2/src/compiler/template_parser.dart 112              TemplateParser.parse
package:angular2/src/compiler/template_compiler.dart 260            TemplateCompiler._processTemplateCodeGen
package:angular2/src/compiler/template_compiler.dart 212            TemplateCompiler.compileTemplatesCodeGen.<fn>
[web] GET Served 22 assets.
dart:core                                                           List.forEach
package:angular2/src/compiler/template_compiler.dart 208            TemplateCompiler.compileTemplatesCodeGen
package:angular2/src/transform/template_compiler/generator.dart 64  processTemplates.<async>.<fn>.<async>
[web] GET main.ng_deps.dart => ng_for|web/main.ng_deps.dart
Build completed with 1 errors.
[web] GET Served 41 assets.
[web] GET packages/ng_for/app_element.ng_deps.dart => Could not find asset ng_for|lib/app_element.ng_deps.dart.
[web] GET Served 74 assets.

https://github.com/bwu-dart-playground/dart_playground/blob/master/angular2/ng_for/lib/app_element.html#L6

**Comment by andresaraujo** [comment]
`*ng-for` needs to be changed to camel case: `*ngFor`

**Comment by zoechi** [comment]
Stupid me, I'm aware of that change, I just missed that I have it there a 2nd time where I didn't change it.
