### ISSUE TITLE
AppViewManager.createRootHostView with ElementRef

### ISSUE THREAD

**Issue by frederikschubert** [angular/angular#6072]
Currently it is only possible to specify the position where a component is instantiated by `AppViewManager.createRootHostView` by providing an `overrideSelector`.
I am working on the [angular2-hot-loader](https://github.com/mgechev/angular2-hot-loader/) and want to reinitialize a component that has been changed. This works but has the limitation to only update the first component in the DOM due to the behavior of the `createRootHostView` method.
> Creates an instance of a Component and attaches it to the first element in the global View (usually DOM Document) that matches the component's selector or overrideSelector.

Is it possible to create a version of the `createRootHostView` that can be called with an ElementRef? Or is there any other way to achieve what i want to do.
You can see my current implementation [here](https://github.com/frederikschubert/angular2-hot-loader/blob/component-scoped-hot-reload/lib/client/client.ts#L112).

**Comment by pkozlowski-opensource** [comment]
Obsolete as `AppViewManager` is gone. Please open a new issue following the template if this is still a problem for you.
