### ISSUE TITLE
HTTP Headers .toJSON() only returns values (not keys) of the headers

### ISSUE THREAD

**Issue by choeller** [angular/angular#6073]
The current implementation of toJSON() of the Headers class only returns a JSON-Object containing all values.:

```
[
  [
    "no-cache"
  ],
  [
    "application/json; charset=utf-8"
  ],
  [
    "no-cache"
  ],
  [
    "-1"
  ]
]
```

IMO this should return a JSON Object mapping keys to values.

**Comment by robwormald** [comment]
cc @gdi2290 - i know you added this for universal - any input?

**Comment by gdi2290** [comment]
yeah I can fix that. The idea behind having `.toJSON()` was being able to recreate it on the client
```typescript
var serverHeaders = new Headers();
serverHeaders.append('Content-Type', 'image/jpeg');
var serialized = JSON.stringify(serverHeaders, null, 2);

console.log(serialized === `{
  "Content-Type": ["image/jpeg"]
}`);

var clientHeaders = new Headers(JSON.parse(serialized));
```

**Comment by gdi2290** [comment]
@choeller @robwormald I have a PR with the correct implementation and tests to ensure that you can also recreate the Header https://github.com/angular/angular/pull/6714
