### ISSUE TITLE
`ngFor` 'after' in CHANGELOG.md is wrong

### ISSUE THREAD

**Issue by zoechi** [angular/angular#6075]
It says at https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes-3

Before
```html
...
<template ng-for #my-item [ng-for-of]=items #my-index="index">
```
After:
```html
<template ngFor="#myItem" [ngForOf]=items #myIndex="index">
```
but `ngFor="#myItem"` just produces an error.
With

```html
<template ngFor #myItem [ngForOf]=items #myIndex="index">
               ^       
```
it's working fine

**Comment by vicb** [comment]
@zoechi thanks for noticing. It had been fixed in kebab-case.md but not in the changelog.
