### ISSUE TITLE
ng1 Component Router doesn't work with 1.5 components / restrict E directives

### ISSUE THREAD

**Issue by e-schultz** [angular/angular#6076]
* **Issue**: ngComponentRouter, in the outlet directive will place the component name as an attribute on a div tag, instead of creating an element for it
* Using Angular 1.5
* Building ngComponentRouter from current angular master
* **Motivation/Use Case**: Exploring migration of ui-router to the ngComponentRouter 

Looking at the [ngOutlet](https://github.com/angular/angular/blob/604c8bbad54ffbcec1d6a5e407821adda8a74a19/modules/angular1_router/src/ng_outlet.ts#L158)

```javascript
this.controller.$$template = '<div ' + dashCase(componentName) + '></div>';
```

If using a `.directive`, restrict needs to be `AE` as a result, if I am using `.component`, then the element won't display at all, assuming that behind the scenes it only works for elements, not attributes. 

Changing the line to something like:

```javascript
var dashName =  dashCase(componentName)
this.controller.$$template = '<' + dashName + '>' + '</' + dashName + '>' 
```
seems to work. 

Also a consideration when working with ngUpgrade, as the comments [indicate that restrict must be 'E'](https://github.com/angular/angular/blob/1b78342e23f00ed5c6494e7d192a7356c841d7cb/modules/angular2/src/upgrade/upgrade_adapter.ts#L209)

**Comment by brandonroberts** [comment]
@e-schultz you can override the restrict to work with the component helper. Its just set to E by default

```
angular.module('something').component('home', {
    restrict: 'AE'
});
```

**Comment by e-schultz** [comment]
:+1: thanks - overlooked that  your able to do that.

**Comment by JonnyBGod** [comment]
This is a problem when using with ng-forward as the @Component decorator defaults to restrict: 'E' and currently the is no way to override it.

**Comment by brandonroberts** [comment]
You have to use the @Directive decorator if you want to use the component router with ng-forward

**Comment by jamesmfriedman** [comment]
Ran into this problem with the latest build. All of my css is dependent on styling the actual component tags like <element></element> Until it's fixed, I just overloaded ngOutlet in my main app.js file. Not saying it's the right thing to do, but it definitely works...

```javascript
app.directive('ngOutlet', function($compile) {
    return {
        restrict: 'EA',
        priority: -400,
        require: 'ngOutlet',
        link: function (scope, element, attrs, ctrl) {
        	// The fix
        	var dashName = ctrl.$$componentName.replace(/[A-Z]/g, function (match) { return '-' + match.toLowerCase(); });
        	var template = ctrl.$$template = '<' + dashName + '></'+ dashName +'>';
        	
        	element.html(template);
            var link = $compile(element.contents());
            link(scope);
            // TODO: move to primary directive
            var componentInstance = scope[ctrl.$$componentName];
            if (componentInstance) {
                ctrl.$$currentComponent = componentInstance;
                componentInstance.$router = ctrl.$$router;
                componentInstance.$routeParams = ctrl.$$routeParams;
            }
        }
    };
});

**Comment by tolemac** [comment]
Using Angular 1.5rc2 you can not override `restrict` on component creation, this is the `.component` code:

```` javascript
this.component = function registerComponent(name, options) {
    var controller = options.controller || function() {};

    function factory($injector) {
      function makeInjectable(fn) {
        if (isFunction(fn) || isArray(fn)) {
          return function(tElement, tAttrs) {
            return $injector.invoke(fn, this, {$element: tElement, $attrs: tAttrs});
          };
        } else {
          return fn;
        }
      }

      var template = (!options.template && !options.templateUrl ? '' : options.template);
      return {
        controller: controller,
        controllerAs: identifierForController(options.controller) || options.controllerAs || '$ctrl',
        template: makeInjectable(template),
        templateUrl: makeInjectable(options.templateUrl),
        transclude: options.transclude,
        scope: {},
        bindToController: options.bindings || {},
        restrict: 'E', // <== HERE
        require: options.require
      };
    }

    // Copy any annotation properties (starting with $) over to the factory function
    // These could be used by libraries such as the new component router
    forEach(options, function(val, key) {
      if (key.charAt(0) === '$') {
        factory[key] = val;
      }
    });

    factory.$inject = ['$injector'];

    return this.directive(name, factory);
  }
````

And I think this is correct, I think you have to change the ngComponentRouter code.

**Comment by brandonroberts** [comment]
@petebacondarwin said he would fix the router soon to support components created with 1.5. See https://github.com/angular/angular/pull/6796

**Comment by tolemac** [comment]
Excellent!!

**Comment by petebacondarwin** [comment]
Yes, #6796 resolves this issue.
