### ISSUE TITLE
Add es6-shim.js to https://code.angularjs.org/tools/

### ISSUE THREAD

**Issue by wardbell** [angular/angular#6077]
We will be adding the es6 shim to samples by default in order to avoid complaints from users of older browsers (one is free to remove it if not worried about those browsers).

We should be able to get the shim from `https://code.angularjs.org/tools/` as we do other 3rd party libs (for use in plunkers and such).

The current workaround is to go elsewhere. Here's what I'm using now:
```
    <script src="https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.34.0/es6-shim.js"></script>
```

**Comment by pkozlowski-opensource** [comment]
Related: https://github.com/angular/angular/issues/6111

**Comment by wardbell** [comment]
I updated all published TS samples (except home page) in  [angular.io commit 7ed0fce](https://github.com/angular/angular.io/commit/7ed0fce10dedcbfd98aa4ff265edca389df9a3b0)

Still waiting for the two polyfill files to be added to `https://code.angularjs.org/tools/`.  Using Cloudfare CDN for the nonce.

**Comment by vicb** [comment]
can this be closed ?

**Comment by wardbell** [comment]
I think this is long past its _sell-by_ date. Closing
