### ISSUE TITLE
Reusable component : template ( Newbie Question )

### ISSUE THREAD

**Issue by gbouteiller** [angular/angular#6079]
Hi everyone
First of all, I'd like to apologize if my question sounds stupid but I'm a pretty new user of Angular2. Let's say I have a menu component with an inline template and I want to use the same component in another app but with a different template. What is the best way to achieve that in angular2? In angular 1, when I was playing with directives a little, I ended up using the template function and passing the template as a string from the parent via an attribute ( maybe it was bad practice too ;) ).

**Comment by pkozlowski-opensource** [comment]
See https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
