### ISSUE TITLE
Router.isRouteActive issue?

### ISSUE THREAD

**Issue by ribizli** [angular/angular#6080]
The code of this method looks a bit strange for me (admitting that I'm not fully familiar with the Component Router):

```typescript
while (isPresent(router.parent) && isPresent(instruction.child)) {
  router = router.parent;
  instruction = instruction.child;
}
```

I came to this code when I wanted to figure out what is wrong with my child `RouterLinks` (`['Games', 'Game']` and `['Games', 'List']`), that all of them are active (via CSS class) if the parent route is active. 
The links are on the root level, so the root router is injected into. Its current component is `Games`. The instruction's top component is also `Games`, which is compared against the router's one. This is why both of my links are active. (Btw, if I put the child links down to the child outlet they work fine, since the loop iterates once, because the child router is injected)

Maybe my explanation is wrong, the issue is somewhere else or there isn't any issue at all, but I'd ask before I dig deeper into the source.

**Comment by ribizli** [comment]
I see that there is already a PR for this method: #5274. I'm curious if it solves my problem.

**Comment by ciriarte** [comment]
@ribizli it works for us, I have been applying a patch to our build since alpha.44 to beta.0 and it always solves the problem for us, I'll post the patch I'm using as soon as I get to the office.

**Comment by ciriarte** [comment]
We usually apply this patch in our build:

```patch
diff --git client/jspm_packages/npm/angular2@2.0.0-beta.0/src/router/router.js client/jspm_packages/npm/angular2@2.0.0-beta.0/src/router/router.patched.js
index ef7a0aa..270ae37 100644
--- client/jspm_packages/npm/angular2@2.0.0-beta.0/src/router/router.js
+++ client/jspm_packages/npm/angular2@2.0.0-beta.0/src/router/router.patched.js
@@ -65,7 +65,10 @@ var Router = (function() {
       router = router.parent;
       instruction = instruction.child;
     }
-    return lang_1.isPresent(this._currentInstruction) && this._currentInstruction.component == instruction.component;
+
+    var currentInstruction =
+        lang_1.isPresent(this._currentInstruction) ? this._currentInstruction : router._currentInstruction;
+    return lang_1.isPresent(currentInstruction) && currentInstruction.component === instruction.component;
   };
   Router.prototype.config = function(definitions) {
     var _this = this;
```

With the following command:

```sh
  patch -p0 --forward < ng_route_is_active.patch
```

**Comment by ribizli** [comment]
Thanks @ciriarte.
I'm currently using angular2 bundles, so patching is not as easy. 
Anyway this is a proof, that there is a bug in the `isRouteActive` method

**Comment by rluba** [comment]
@ciriarte Your patch does not solve the bug described by @ribizli.

The problem is that the router only compares the outermost component but not the child components, so `isRouteActive` returns `true` for every route that has the same root component as the current route.

**Comment by rluba** [comment]
I’ve modified the Router example from the angular doc to demonstrate the problem: http://plnkr.co/edit/2ukyKVPKyGgocnVJu6wv?p=preview

Click on "Crisis Center" and you’ll see that both the "Crisis Center" and the "Crisis Detail that is not really active" link are displayed as "active" even though the latter is not really active.

**Comment by DzmitryShylovich** [comment]
any updates?

**Comment by dkulyk** [comment]
The current(b.15) implementation incorrectly. Because there is no instruction to check the depth.

    /*Router::*/isRouteActive(instruction:Instruction):boolean {
        var router:Router = this;
        var currentInstruction = this.currentInstruction;

        if (isBlank(currentInstruction)) {
            return false;
        }

        // `instruction` corresponds to the root router
        while (isPresent(router.parent) && isPresent(instruction.child)) {
            router = router.parent;
            instruction = instruction.child;
        }

        // check the instructions in depth
        do {
            if (isBlank(instruction.component) || isBlank(currentInstruction.component) ||
                currentInstruction.component != instruction.component) {
                return false;
            }
            if (isPresent(instruction.component.params)) {
                StringMapWrapper.forEach(instruction.component.params, (value, key) => {
                    if (currentInstruction.component.params[key] !== value) {
                        return false;
                    }
                });
            }
            currentInstruction = currentInstruction.child;
            instruction = instruction.child;
        } while (isPresent(currentInstruction) && isPresent(instruction) && !(instruction instanceof DefaultInstruction));

        // ignore DefaultInstruction
        return isBlank(instruction) || instruction instanceof DefaultInstruction;
    }

**Comment by SelcukTekin** [comment]
Both me @schippie

**Comment by zheffie** [comment]
@dkulyk 
Seems to be a good fix. Can you submit a pull request?

**Comment by vicb** [comment]
obsolete - old router
