### ISSUE TITLE
Less coupling between components and RouteParams

### ISSUE THREAD

**Issue by ewinslow** [angular/angular#6081]
Currently components need to depend on route params in order to be initialized, but often you want the route params deserialized into some domain-specific object anyways, and you end up doing this in the constructor.

This situation causes the following issues:
* Route param names are shared across multiple files, making renaming harder
* Work is happening in constructor, which hurts testability
* Model may have to be requested async

```ts
export default class Edit {
  private model :Model;

  constructor(service :Service, params :RouteParams) {
    this.model = service.getModel(params.get('alias'));
  }
}
```

A natural improvement would be to move this to the component providers, but this doesn't seem to be possible due to limitations in TypeScript: not able to annotate arrow functions?

```ts
@Component({
  providers: [
    provide(Model, {
      useFactory: (service :Service, params :RouteParams) => service.getModel(params.get('alias')),
    }),
  ],
}) 
export default class Edit {
  constructor(private model :Model) {}
}
```

But this still doesn't solve the "route param names shared across files" problem.

Instead of relying on routeParams at all, components that are routed to could just declare their public API like normal, which the route configuration then uses:

```ts
@RouteConfig([
  {
    path: '/:alias/edit',
    component: Edit,
    inputs: { // similar to "resolve" on ng1 router
      'model': (service :Service, params :RouteParams) => service.getModel(params.get('alias')),
    },
  }
])
class Parent {}

class Edit {
  @Input() private model :Model;
}
```

Alternatively, the component could request these inputs via constructor injection, and the RouteConfig would configure the injector: 

```ts
@RouteConfig([
  {
    path: '/:id/edit',
    component: Edit,
    providers: [
      provide(Model, {
        useFactory: (service :Service, params :RouteParams) :Model => service.getModel(params.get('id')),
      })
    ],
  } ,
])
class Parent {}

class Edit {
  constructor(private model :Model) {}
}
```

This way components are encouraged to:
 * have a clear public API
 * not entangle themselves with the router so much
   * great news if you ever wanted to switch to another router
   * makes components more reusable across multiple routes, since they are not tied to particular param names

**Comment by gionkunz** [comment]
I have the same issues and I believe that the router is way much too imperative in dictating a component design. Ideally my existing components that are encapsulated with inputs and outputs, can just be re-used in routing situations. This is not the case now and one need to re-write the whole component to be dependent on route params only.

I've created a different proposal than yours but to solve the same problem. https://github.com/angular/angular/issues/5875

**Comment by staeke** [comment]
+1

**Comment by CaptainCodeman** [comment]
I found the advice to split things up between "smart" components (that interact with services, http etc...) and "dumb" components (for rendering & UI interactions) works well but I'd add "routed" components (decoding parameters and navigation) as a distinct category too.

The router does seem intrusive into how certain components are developed and this helps limit this to a slightly thinner layer. I'm hoping things will improve as guidance and know-how evolves.

**Comment by jjpeters67** [comment]
attachViewAfter(node: any, viewRootNodes: any[]) {

**Comment by zoechi** [comment]
Is this still relevant with the new router?
