### ISSUE TITLE
Use "slot" concept instead of router-outlet

### ISSUE THREAD

**Issue by ewinslow** [angular/angular#6082]
After trying out angular2 for a while, I've had a few times where I want to do:

```
<my-component>
  Projected content
</my-component>
```

And then later on use `<my-component>` as the target of a route: 
`{path: '/whatevs/...', component: MyComponent}`

But this isn't possible because I have to use `<router-outlet>` in the one case and `<ng-content>` in the other. I haven't tried using them side-by-side, but that seems ugly and I suspect would cause problems.

`<slot>` from ShadowDOM v1 seems to be conceptually similar to `<router-outlet>`. You can have a default one without a name, or named slots (just like named outlets for auxiliary routes).

Using `<slot>` or a custom `<ng-slot>` similar thing seems like it could unify these concepts (fewer concepts is better, right?), and decouple components from knowing so much about routing, making them more testable in isolation.

**Comment by ericmartinezr** [comment]
Actually they discussed about renaming `ng-content` to `ng-slot` time ago, check https://github.com/angular/angular/issues/3882

**Comment by vsavkin** [comment]
It's an interesting idea, but doing it this way would be a large breaking change. So I don't think the benefit justifies the cost. Closing the issue.

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20782714/60f05eaa-b7c9-11e6-9006-f7beb8bef322.png)
