### ISSUE TITLE
possible error in forms documentation

### ISSUE THREAD

**Issue by anthonylrm** [angular/angular#6083]
It's just a documentation issue, but its been confusing me and I was hoping to get some clarity. On https://angular.io/docs/ts/latest/guide/forms.html, I think the line "When we added the ngControl directive, we bound it to the the model's name property"  is wrong. It's not bound to the model's name property. It's something else which I'm not sure I can express clearly. CAn someone change it or else let me know what I'm misunderstanding. Thanks.

**Comment by msimpson** [comment]
This is related to #5997.

**Comment by kara** [comment]
This docs page is being replaced by the docs page for the new forms API: https://angular.io/docs/ts/latest/guide/forms.html, so closing this.  Please feel free to re-open if you notice any oddness with the new forms documentation.
