### ISSUE TITLE
No 'TUTORIAL' section for https://angular.io/docs/js/latest/quickstart.html (Angular 2 For JavaScript

### ISSUE THREAD

**Issue by adamchenwei** [angular/angular#6084]
only see available for typescript... I don't understand. why the precious Tutorial not available for pure Javascript????? o.O

**Comment by horaceli** [comment]
Seeing as even the tutorials for typescript are still being written, it's probably just a matter of waiting (or contributing!)

**Comment by adamchenwei** [comment]
it would be nice the author who wrote type script can make javascript in parallel, since they basically same but go through some sort compiler for typescript lol, no?

**Comment by pkozlowski-opensource** [comment]
JS-version of the quick start is on-line: https://angular.io/docs/js/latest/quickstart.html

**Comment by adamchenwei** [comment]
@pkozlowski-opensource  Would you kindly read my topic again? its not the 'Quick Start' , its the 'Tutorial' section. that is NOT available. Thank you 

This https://angular.io/docs/ts/latest/tutorial/ is NOT available for javascript.
