### ISSUE TITLE
Unused peer dependencies

### ISSUE THREAD

**Issue by ColinEberhardt** [angular/angular#6087]
In the getting started guide you are directed to add the various peer dependencies via npm. However, of these dependencies only `rx.js` is actually used in the sample application. I confirmed this by removing the extra dependencies, and the app still worked fine:

https://github.com/johnpapa/angular2-tour-of-heroes/pull/42/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

My question is, why does the sample application encourage you to add `es6-promise`, `es6-shim`, `reflect-metadata` and `zone.js` when none of them are actually used in the application?

**Comment by kylecordes** [comment]
Reflect-metadata and zone are actually bundled up in the polyfills file that you are probably including on the page already; they are also declared as dependencies, for those who would prefer to include them directly from the upstream sources.

ES6 promise and shim are needed on some older browsers, if I understand correctly. I would guess that as the beta proceeds, we will end up with a chart somewhere showing what polyfills are needed for what versions of what browsers.

**Comment by laco0416** [comment]
:+1: 
reflect-metadata and zone.js are included in polymer2-polyfills.js. These aren't needed as peerDependencies now.

And angular2 depends on rxjs now. I think it should be depended as `dependencies`.

**Comment by pkozlowski-opensource** [comment]
We no longer advocate usage of the polyffils bundle so those peer dependeincies are still needed.
