### ISSUE TITLE
angular2-polyfills causing problems with setTimeout

### ISSUE THREAD

**Issue by bsagal** [angular/angular#6088]
According to the [doc of setTimeout](https://developer.mozilla.org/en-US/docs/Web/API/WindowTimers/setTimeout) the fuction supports the syntax `setTimeout(string code, [delay])`

The version in `angular2-polyfills.js` does not support this syntax and this is casing problems with ASP.NET which generates code using this version.

I understand that this version should be avoided but I am only able to replace the old asp.net code in stages

**Comment by pkozlowski-opensource** [comment]
If this is to be fixed, it would belong to https://github.com/angular/zone.js

**Comment by pkozlowski-opensource** [comment]
Duplicate of https://github.com/angular/zone.js/issues/265
