### ISSUE TITLE
Using Immutable on iOS 8 throws 'Cannot find differ' error 

### ISSUE THREAD

**Issue by cghislai** [angular/angular#6089]
I have an application running fine on iOS9.
on iOS 8, on a component binding an Immutable.List in its template and iterating over it using the NgFor directive, I get the following error in console :
(I hope its no issue uploading screenshots, copy-past does not work through VM)

![image](https://cloud.githubusercontent.com/assets/12647398/11974545/94fa6290-a965-11e5-9609-7d910d689ffd.png)
![image](https://cloud.githubusercontent.com/assets/12647398/11974576/d7aeef66-a965-11e5-9f31-1f3049f613ea.png)
![image](https://cloud.githubusercontent.com/assets/12647398/11974587/eb98b296-a965-11e5-8542-22cfa787bf63.png)

I'm using angular2 beta0

**Comment by cghislai** [comment]
Here is a snippset of the NewsComponent:

```
export class NewsComponent implements OnActivate {

    viewType:ViewType;
    newsService:NewsService;
    errorService:ErrorService;

    itemList:Immutable.List<NewsItem>;
    hasMoreNews:boolean;
    pageIndex:number;
    loggedIn:boolean;
    searching:boolean;
    searchTask:Promise<any>;

    constructor(newsService:NewsService, errorService:ErrorService, loginService:LoginService) {
        this.newsService = newsService;
        this.errorService = errorService;
        this.viewType = ViewType.RECENT;
        this.loggedIn = loginService.isLoggedIn();

        this.itemList = Immutable.List<NewsItem>([]);
        this.pageIndex = 0;
    }
// ...
}
```

**Comment by F1ow** [comment]
Having the same issue! Any updates on this?

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
