### ISSUE TITLE
Option 'emitDecoratorMetadata' cannot be specified without specifying option 'experimentalDecorators'.

### ISSUE THREAD

**Issue by EnguYoo** [angular/angular#6090]
On different cloned projects, I get
`error TS5052: Option 'emitDecoratorMetadata' cannot be specified without specifying option 'experimentalDecorators'.`
    Command `tsc -p src` failed with exit code 2

Indeed, several times on this repo the 'emitDecoratorMetadata' is used without 'experimentalDecorators'.
Am I doing something wrong ?

**Comment by pkozlowski-opensource** [comment]
> On different cloned projects, I get

Did you open issues for those projects?

> Indeed, several times on this repo the 'emitDecoratorMetadata' is used without 'experimentalDecorators'.

Could you point to specific examples?

**Comment by EnguYoo** [comment]
> Did you open issues for those projects?

No, actually the problems were somewhere else.

> > Indeed, several times on this repo the 'emitDecoratorMetadata' is used without 'experimentalDecorators'.

>Could you point to specific examples?

There is plenty of it :
https://github.com/angular/angular/search?utf8=%E2%9C%93&q=emitDecoratorMetadata

Maybe I missed something about that, but as far as i know it raises warnings.

**Comment by alexeagle** [comment]
TypeScript changed this when they introduced `experimentalDecorators`. You need to specify both. Any code in the angular project that doesn't is just stale.
