### ISSUE TITLE
RouteData is an empty object in component.

### ISSUE THREAD

**Issue by greg-md** [angular/angular#6091]
When you set some data in the Route, you get an empty RouteData in the component.

**Comment by thelgevold** [comment]
This seems to work for me
```
@RouteConfig([
    new Route({path: '/', component: About, name: 'About', data: {project: 'angular-2-samples'}})
])
```
Then in the About component I access the data like this:

```
export class About {
    id: string;
    constructor(params: RouteParams, data: RouteData){
        this.id = params.get('id');
        console.log(data.get('project'));
    }
}
```

Demo here: I write the routeData to the console when loading the page.
http://www.syntaxsuccess.com/angular-2-samples/

**Comment by greg-md** [comment]
Did you test on beta version?

**Comment by vicb** [comment]
obsolete - old router
