### ISSUE TITLE
Not Able to call WebAPI from angularJS-2 (hero.service.ts) file, given on official site "https://angular.io" heroes example.

### ISSUE THREAD

**Issue by pratuldubey** [angular/angular#6092]
I am working on Hero example given on  official site "https://angular.io" , and trying to give a call to webapi. I am checking in fiddler it is not even calling my WebAPI.
I cross checked my API is working fine and just exposing some json data.

app/hero.service.ts  ==>

import {Hero} from './hero';
import {HEROES} from './mock-heroes';
import {Injectable} from 'angular2/core';
import { Http, Response, Request } from 'angular2/http';
import {HTTP_BINDINGS} from "angular2/http";

@Injectable()
export class HeroService {
    constructor   (public http: Http ) {
        this.http = http;
    console.log('Task Service created.', http);
    }
  getHeroes() {
     this.http.get("https://api.github.com/users/Angular" )
                .map( (responseData) => {
      return responseData.json();
    })
  }
}

**Comment by zoechi** [comment]
Can you please edit your comment and wrap the code in triple-backticks ``` to make it more readable.

**Comment by tenowg** [comment]
you should assume that getHereos is going to return an Observable

    return this.http.get("...").map(responseData => responseData.json())

then on the caller, `getHeroes().subscription((responseData) => {this.data = responseData})`

The subscribe is what is going to make the http call happen.

**Comment by bharathimohan1993** [comment]
It's simple, you need to import map file to your component. 

import 'rxjs/add/operator/map';
