### ISSUE TITLE
markForCheck inside ngAfterViewChecked with OnPush change detection strategy

### ISSUE THREAD

**Issue by rosendi** [angular/angular#6094]
With the `OnPush` change detection strategy `markForCheck` inside `ngAfterViewChecked` works only if  it's wrapped in `setTimeout`. Is it an expected behaviour? What is the correct way to re-check a component? 

http://plnkr.co/edit/lzvx2ztikYNhupikk9jL?p=preview

**Comment by robwormald** [comment]
The expectation would be some external event would trigger markForCheck (like a Promise resolving, or  a button click....) - calling markForCheck inside afterViewCheck would effectively send the change detector into an infinite loop if it were to work, no? What's the use case?

**Comment by rosendi** [comment]
In most cases, yes. However, not in case with the router. Please check this issue https://github.com/angular/angular/issues/4452, especially the https://github.com/angular/angular/issues/4452#issuecomment-153889558 and https://github.com/angular/angular/issues/4452#issuecomment-160764221 comments.

The solution mentioned in the router issue works fine, but with the OnPush change detection strategy it requires additional setup, because the child components don't know that the parent component has passed a new value to them.

Plunker is sleeping now. I'll post a practical example.

**Comment by rosendi** [comment]
@robwormald  http://plnkr.co/edit/HJ7DMKZaWnixlimqX8XW?p=preview Line 140.

**Comment by rosendi** [comment]
@robwormald I can close this issue now. I still haven't found what I'm looking for, but I think that the behavior of the `ngAfterViewChecked` callback is correct. The issue is with the router, that doesn't provide a clear binding mechanism to the child components, even more it doesn't give us a simple way to access parent params. Don't you think so?

**Comment by pkozlowski-opensource** [comment]
Closing per https://github.com/angular/angular/issues/6094#issuecomment-168297281
