### ISSUE TITLE
Router Link never sets 'router-link-active' class

### ISSUE THREAD

**Issue by deeptowncitizen** [angular/angular#6095]
Router Link calls Router.IsRouteActive() to compare current instruction's components with host anchor component.

Then problem is that Router.commit (which assigns current instruction state) becomes called after IsRouterActive() call in Directive.

description: http://stackoverflow.com/questions/34439711/router-link-behavior-is-broken-in-angular2-beta

**Comment by gdi2290** [comment]
you mind be looking for something like this directive https://github.com/angular/angular/pull/6407/files

**Comment by vicb** [comment]
obsolete - old router
