### ISSUE TITLE
Misleading message: Call enableDevMode() to enable the development mode.

### ISSUE THREAD

**Issue by vlazar** [angular/angular#6096]
Angular version: 2.0.0-beta.0

When I use
```
import { enableProdMode } from 'angular2/core';
enableProdMode();
```

I see this message in console:

```Angular 2 is running in the production mode. Call enableDevMode() to enable the development mode.```

This message is misleading, since I can't do:
```
import { enableDevMode } from 'angular2/core';
enableDevMode();
```

See https://github.com/angular/angular/commit/3dca9d522a79d037b3c2deba537ed547fc3f65b8#diff-de4ce02776490d26d87799f461b31974R434

/cc @vsavkin

**Comment by michalstepien** [comment]
Please close. Fixed.

**Comment by vlazar** [comment]
This is fixed now.

Checked with Angular 2.0.0-rc.1 and [QuickStart](https://angular.io/docs/ts/latest/quickstart.html) guide.

In development mode there is a ***Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.***

If I add:
```javascript
import { enableProdMode }    from '@angular/core';
enableProdMode();
```

There is no message in console anymore.
