### ISSUE TITLE
New 

### ISSUE THREAD

**Issue by JohnMunsch** [angular/angular#6098]
I had crafted an example using one of the templates from Material Design Lite. Under alpha 46 my template compiled and worked (largely) correctly: http://plnkr.co/edit/OQstTG?p=preview

Here's the equivalent converted to beta 0: http://plnkr.co/edit/iwJHQm?p=preview

Now it throws a multitude of parsing errors like this:
```
Unexpected closing tag "mask" ("=0.5 cy=0.5 r=0.49 fill="white">
            <circle cx=0.5 cy=0.5 r=0.40 fill="black">
          [ERROR ->]</mask>
          <g id="piechart">
            <circle cx=0.5 cy=0.5 r=0.5>
"): App@68:10
Unexpected closing tag "g" ("5 0.5 0.5 0 A 0.5 0.5 0 0 1 0.95 0.28 z" stroke="none" fill="rgba(255, 255, 255, 0.75)">
          [ERROR ->]</g>
        </defs>
      </svg>
"): App@72:10
```

For the same "dashboard.component.html" file which worked under the older version. Note: It doesn't matter if you remove the three sub-components I put into the template of the main component or not, you'll get the same parsing errors.

**Comment by robwormald** [comment]
@JohnMunsch other than a couple of 404's on images, your second plunker appears to work fine to me - perhaps I'm misunderstanding your directions?

Also, would you mind fixing the title of your issue - currently it reads "New" :8ball:
