### ISSUE TITLE
New "Template parse errors" with beta.

### ISSUE THREAD

**Issue by JohnMunsch** [angular/angular#6099]
I had crafted an example using one of the templates from Material Design Lite. Under alpha 46 my template compiled and worked (largely) correctly: http://plnkr.co/edit/OQstTG?p=preview

Here's the equivalent converted to beta 0: http://plnkr.co/edit/iwJHQm?p=preview

Now it throws a multitude of parsing errors like this:
```
Unexpected closing tag "mask" ("=0.5 cy=0.5 r=0.49 fill="white">
            <circle cx=0.5 cy=0.5 r=0.40 fill="black">
          [ERROR ->]</mask>
          <g id="piechart">
            <circle cx=0.5 cy=0.5 r=0.5>
"): App@68:10
Unexpected closing tag "g" ("5 0.5 0.5 0 A 0.5 0.5 0 0 1 0.95 0.28 z" stroke="none" fill="rgba(255, 255, 255, 0.75)">
          [ERROR ->]</g>
        </defs>
      </svg>
"): App@72:10
```

For the same "dashboard.component.html" file which worked under the older version. Note: It doesn't matter if you remove the three sub-components I put into the template of the main component or not, you'll get the same parsing errors.

**Comment by Toadskin** [comment]
The parser is chirping about a valid </g> closing tag but notice the circle tag is not closed.  The parser is looking for the closing tag on <color.../> when it encounters </g> (error).  Not sure if there is a switch for markup leniency but at some point everything needs to comply.

**Comment by JohnMunsch** [comment]
Ugh. When I went through and fixed every <use>, <circle>, <path>, <line>, and <polygon> to have a slash before the end bracket so it was clear they were fully formed elements with only the one tag, it stopped throwing the error and started working.

"Hey kids! Make sure your SVG and HTML are perfectly formed," is not what I'm hoping to say to anybody in my course. As I said, alpha 46 wasn't freaked out by these oversights (in Google's own Material Design Lite template examples, *cough*) but beta is very unhappy about them.

**Comment by kylecordes** [comment]
I was also initially quite surprised to see it suddenly become picky. But I've been working through a lot of code with Angular 2, and I have now come to much appreciate this. I think the overall results, in terms of delivering high-quality software in a timely way etc., are much improved by a toolset which emits errors for mistakes rather than letting them slide through.

If one side effect of Angular 2 is to send people who want to write invalid HTML and their templates looking elsewhere, that could be a win - and I actually don't mind teaching in our classes here (we teach a lot of them) the importance of writing correct code.

**Comment by JohnMunsch** [comment]
My apologies, I accidentally saved on the beta Plunk after I altered the elements to all have a closing slash. That's why it appeared to be "fixed". I've rolled it back to an earlier version without that and frozen it.

**Comment by uglow** [comment]
@kylecordes , I think this is a bug. Tools like Webpack will take well-formed HTML and can optionally minify them (according to what is permissible in the HTML spec).

For example, this string is perfectly valid HTML `<div><h1>Page 1</h1><img src=/assets/demoModule/img/blank-logo.d71838b1.png> <a class=btn href=#/page2>Page 2</a></div>`. In this case, Webpack's `html-loader?minimize=true` produced this string from a HTML file that had all of the attribute quotes, indentation and whitespace.

This string is perfectly usable in any browser and in Angular 1.x components. Why does Angular 2 need to enforce a specification that is more-strict than the HTML spec itself?

**Comment by zoechi** [comment]
@uglow I think you should create a new issue for quotes around attribute values.

**Comment by vicb** [comment]
is this still an issue

**Comment by JohnMunsch** [comment]
No.
