### ISSUE TITLE
Error when using 'for' attribute in label inside ngFor

### ISSUE THREAD

**Issue by kiswa** [angular/angular#6100]
I've been playing with the ToDo list example and came across an error while trying to set the for attribute of a label.

This is the template:

```html
<ul class="unstyled">
    <li *ngFor=#todo of todos; #i = index">
        <input type="checkbox" [(ngModel)]="todo.done" id="chk{{ i }}">
        <label for="chk{{ i }}">
            <span class="done-{{ todo.done }}">{{ todo.text }}</span>
        </label>
    </li>
</ul>
```

And the error:
```
EXCEPTION: Template parse errors:
Can't bind to 'for' since it isn't a known native property ("
        <input type="checkbox" [(ngModel)]="todo.done" id="chk{{ i }}">
        <label [ERROR ->]for="chk{{ i }}">
            <span class="done-{{ todo.done }}">{{ todo.text }}</span>
        </lab"): TodoList@4:15
```

If I change the template so `for` is another attribute (I used `id` and `class` without error) or remove the `{{ i }}` from the `for` attribute, there are no errors. Of course, then I can't use the label to check the box.

**Comment by ericmartinezr** [comment]
@kiswa `for` is an attribute, therefore you should add `attr` to it.

This will work

```
<label attr.for="chk{{ i }}">
```

**Comment by kiswa** [comment]
Well, don't I feel like an idiot.

Why is `attr.` not necessary on `id` or `class`?

**Comment by kiswa** [comment]
In case anyone else comes across this issue, I found this to be very helpful: https://angular.io/docs/ts/latest/guide/template-syntax.html#!#html-attribute-vs-dom-property
