### ISSUE TITLE
dart: <select> ngModel doesn't support non-String values

### ISSUE THREAD

**Issue by pavelgj** [angular/angular#6102]
We're trying to use enums as `<option>` values and it doesn't work because [`OptionElement.value`](https://api.dartlang.org/135482/dart-html/OptionElement/value.html) must be a String.

Proposal: implement something like [`ng-value`](https://github.com/angular/angular.dart/blob/d5f45a695c316df5492d6ad764257e0b9f81377e/lib/directive/ng_model.dart#L700) that would allow dynamically typed option values.

**Comment by cghislai** [comment]
If you use typescript, you can easily switch between enum values (as int) or strings:
```
var myEnumValue:MyEnum = MyEnum.VALUE;
var myEnumStringValue: string = MyEnum[MyEnum.VALUE];
```

**Comment by DenisKolodin** [comment]
Not only dart. Typescript version also contains defect.

**Comment by pkozlowski-opensource** [comment]
NgValue is implemented now.
