### ISSUE TITLE
Declaring factory providers should be as easy as declaring class providers

### ISSUE THREAD

**Issue by ewinslow** [angular/angular#6105]
It would be awesome if instead of this:

```
  providers: [
    provide(Model, {
      deps: [Service],
      useFactory: (service :Service) :Model => service.getModel(...args),
    }),
  ],
```

I could just write this:

```
  providers: [
    (service :Service) :Model => service.getModel(...args),
  ],
```

Not sure how feasible it is (given the decorators spec doesn't allow for decorating plain functions IIRC), but figured I'd let my preference be known...

**Comment by PascalPrecht** [comment]
This is indeed nicer, unfortunately we can't emit metadata on functions. We lack typescript support here.

**Comment by gdi2290** [comment]
Support for this can be added to Webpack as a plugin or a transform (think ng-annotate) until there is TypeScript support

**Comment by vicb** [comment]
> Support for this can be added to Webpack as a plugin or a transform
:+1:
