### ISSUE TITLE
can not access https://angular.io/ demo

### ISSUE THREAD

**Issue by iloveyo123u1** [angular/angular#6109]
hi,there
i'm from china,you know!
some website,we can not access  [like google  u2b twitter ...]
i uesd  Shadowsocks ,can access google ,u2b,twitter ...
but ,i can't access plnkr.co

https://angular.io/ demo used  plnkr.co

can you write demo in  http://jsbin.com/ ,https://jsfiddle.net/,http://codepen.io/,  ...  ?

thank you  

:)

---------------------------

why they used one site, not more site, why only use plnkr.co,

maybe,they can used plnkr.co and jsbin.com and jsfiddle.net and codepen.io

if plunker is down,we can used other

now, we can't do something

**Comment by fxck** [comment]
plunker is down at the moment, but it's only temporary

**Comment by iloveyo123u1** [comment]
oh ,Really,thank you .why they used one site,  not more site,  why only use plnkr.co,

maybe,they can used   plnkr.co and jsbin.com and jsfiddle.net and codepen.io

if plunker is down,we can used other 

now, we can't do something

**Comment by kasperpeulen** [comment]
plunkr is the only one with multiple javascript file support

**Comment by pkozlowski-opensource** [comment]
It sounds like it was a temporary pb with plunker.
