### ISSUE TITLE
Angular 2 and IE9 requestAnimationFrame error

### ISSUE THREAD

**Issue by thany** [angular/angular#6111]
I followed the [quickstart](https://angular.io/docs/ts/latest/quickstart.html), and now that it's working fine, the only browser so far I've found it not working in, is IE9.

Full log:
```
HTML1300: Navigation occurred.
localhost:3000
EXCEPTION: Error during instantiation of function BrowserDetails() {! (Token Promise<ComponentRef> -> function DynamicComponentLoader() {} -> function Compiler() {} -> function RuntimeCompiler() { -> function ProtoViewFactory(_renderer, _platformPipes, _directiveResolver, _viewResolver, _pipeResolver, _appId) { -> function Renderer() {} -> function DomRenderer() { -> function AnimationBuilder(browserDetails) { -> function BrowserDetails() {).
   EXCEPTION: Error during instantiation of function BrowserDetails() {! (Token Promise<ComponentRef> -> function DynamicComponentLoader() {} -> function Compiler() {} -> function RuntimeCompiler() { -> function ProtoViewFactory(_renderer, _platformPipes, _directiveResolver, _viewResolver, _pipeResolver, _appId) { -> function Renderer() {} -> function DomRenderer() { -> function AnimationBuilder(browserDetails) { -> function BrowserDetails() {).
   ORIGINAL EXCEPTION: TypeError: Object doesn't support property or method 'requestAnimationFrame'

EXCEPTION: Error during instantiation of function BrowserDetails() {! (Token Promise<ComponentRef> -> function DynamicComponentLoader() {} -> function Compiler() {} -> function RuntimeCompiler() { -> function ProtoViewFactory(_renderer, _platformPipes, _directiveResolver, _viewResolver, _pipeResolver, _appId) { -> function Renderer() {} -> function DomRenderer() { -> function AnimationBuilder(browserDetails) { -> function BrowserDetails() {).
   EXCEPTION: Error during instantiation of function BrowserDetails() {! (Token Promise<ComponentRef> -> function DynamicComponentLoader() {} -> function Compiler() {} -> function RuntimeCompiler() { -> function ProtoViewFactory(_renderer, _platformPipes, _directiveResolver, _viewResolver, _pipeResolver, _appId) { -> function Renderer() {} -> function DomRenderer() { -> function AnimationBuilder(browserDetails) { -> function BrowserDetails() {).
   STACKTRACE:
   

-----async gap-----

   ORIGINAL EXCEPTION: TypeError: Object doesn't support property or method 'requestAnimationFrame'

Error: EXCEPTION: Error during instantiation of function BrowserDetails() {! (Token Promise<ComponentRef> -> function DynamicComponentLoader() {} -> function Compiler() {} -> function RuntimeCompiler() { -> function ProtoViewFactory(_renderer, _platformPipes, _directiveResolver, _viewResolver, _pipeResolver, _appId) { -> function Renderer() {} -> function DomRenderer() { -> function AnimationBuilder(browserDetails) { -> function BrowserDetails() {).
ORIGINAL EXCEPTION: TypeError: Object doesn't support property or method 'requestAnimationFrame'
	Error loading http://localhost:3000/app/boot.js
   {
      [functions]: ,
      description: "undefined",
      message: "EXCEPTION: Error during instantiation of function BrowserDetails() {! (Token Promise<ComponentRef> -> function DynamicComponentLoader() {} -> function Compiler() {} -> function RuntimeCompiler() { -> function ProtoViewFactory(_renderer, _platformPipes, _directiveResolver, _viewResolver, _pipeResolver, _appId) { -> function Renderer() {} -> function DomRenderer() { -> function AnimationBuilder(browserDetails) { -> function BrowserDetails() {).
ORIGINAL EXCEPTION: TypeError: Object doesn't support property or method 'requestAnimationFrame'
	Error loading http://localhost:3000/app/boot.js",
      name: "Error",
      number: NaN,
      stack: undefined
   }
```

It appears Angular is expecting `requestAnimationFrame` to exist, which on IE9 doesn't. This is [confirmed](http://caniuse.com/#search=requestAnimationFrame) on caniuse.com. I expect a similar error to occur on Android 4.1, which is also claimed to be supported and also doesn't have support for RAF.

Everything was built and downloaded today. So everything is at the latest version at the time of writing. Let me repeat myself: I followed the quickstart. I did nothing else. So if you need any code that might be causing this problem, please refer to the quickstart.

**Comment by pkozlowski-opensource** [comment]
You would need a polyffil for RAF in IE9. There are couple of other APIs to polyffil, see the minimal list here: https://github.com/angular/angular/blob/master/modules/angular2/src/testing/shims_for_IE.js

cc @wardbell for the documentation part

**Comment by thany** [comment]
So Angular2 does *not* support IE9, because it needs polyfills... Why does it claim support for IE9 then?

**Comment by otodockal** [comment]
@thany in my opinion, it's better to have support by polyfill, because a lot of people don't need the support, so Angular bundle doesn't have to have this useless code for modern browsers.

**Comment by thany** [comment]
True that, but things like that should be clearly noted in the browser support section. For example, you could use colours to indicate support. Red = no support, yellow = support by polyfills, and green = full support. Or something.

**Comment by thany** [comment]
Speaking of documentation @wardbell it's only half-way through. After the quickstart, or the tuorial for that matter, you end up with a billion files, most of them unminified, which needs to be tidied up for production. I cannot present this to my coworkers and keep a straight face.

**Comment by wardbell** [comment]
It would be unwise to think that what we show in quick start and docs represents a performance-tuned app.

There are facilities and formulas for getting skinny per the specific needs of your app.

They are entirely inappropriate for learning about the platform. We strive rather to reduce friction so we are free to experience Angular.

Of course we will need to provide guidance for more advanced scenarios. As you say we are half way on docs. Hope you like the half you see😃 

And we have high hopes for great guidance from the community!

**Comment by robwormald** [comment]
> For some reason, it depends on an external library (Rxjs) which is huge on its own, which is also weird since Angular1 never needed anything more than itself for basic use.

FWIW, the complete RxJS is roughly ~250KB unminified. We bring in about 10KB of it by default - users can opt into the other 90+ operators that RxJS provides.

**Comment by vsakaria** [comment]
You don't have to include the whole Rx library

**Comment by thany** [comment]
Then the quickstart needs updating. It should not teach newcomers to include a plethora of 3rd party libraries of which >90% isn't used. Better yet, put it in distribution of Angular itself, just like jQuery includes Sizzle, just like Angular 1 includes jqLite.

It'll still be humongous in comparison to Angular 1, but at least a "you don't have to include the whole Rx library" scenario cannot happen that way.

**Comment by smith64fx** [comment]
I have a solution!

Add this to your index.html

```
<script src="https://npmcdn.com/angular2@2.0.0-beta.17/es6/dev/src/testing/shims_for_IE.js"></script>
```

**Comment by Delagen** [comment]
@vicb does not work with latest RC.4 in IE9
on IE 10 works fine
Simple animations 
```
trigger("animateTrigger", [
					   state("hidden", style({transform: "translateX(0%)"})),
					   state("left", style({transform: "translateX(100%)"})),
					   state("right", style({transform: "translateX(-100%)"})),

					   // transition("void <=> *", []),
					   transition("* => dragging", [/*animate("0s linear", style({transform: AUTO_STYLE}))*/]),
					   transition("dragging => *", [style({transform: AUTO_STYLE}), animate("0.3s linear")])

					   transition("* <=> *", animate("0.3s linear"))
				   ])
```
Simply does not set state style on element. No errors in console

**Comment by vicb** [comment]
obsolete

**Comment by vicb** [comment]
Closing because the original issue seems to have been resolved. If you have further issues with ie9 and animations, please re-open a new issue.

**Comment by Stepannie** [comment]
how to make the ng-zorro animation can run on IE9

**Comment by Stepannie** [comment]
> 关闭因为原始问题似乎已经解决。如果您对ie9和动画有进一步的问题，请重新打开一个新问题
i use the way above,but i can't solve the problem and the bug follow
![_20181112200115](https://user-images.githubusercontent.com/12046839/48346326-c138e300-e6b5-11e8-9bc6-3fa9de619c83.png)
