### ISSUE TITLE
AngularJS 1.5.0-rc0 $http POST drops 'syntax-error' or 'not well-formed' on firefox

### ISSUE THREAD

**Issue by LaKing** [angular/angular#6117]
Scenario: 
The NodeJS server accepts POST requests on the given URL, and returns a "Cannot GET /url" for GET requests.
The frontend code executes as expected, the angular POST returns an OK 200 from the server, and the response functions execute correctly.  

On the firefox inspect console, but not chrome, neither on firebug, the $http POST request function - not the promise function - then , drops either a 'syntax error' on url:1:1 or a 'not well-formed' url :1:7 JS error,  at the end of the request when all data is uploaded,  pointing to the URL, as it would be a GET request.

I'm wondering if this is a firefox or an angular bug?

**Comment by wesleycho** [comment]
This should probably belong in https://github.com/angular/angular.js - might need to give me information on a reproduction there (or preferrably a reproduction itself) for any help with this though.

**Comment by LaKing** [comment]
Ahh, yes ... sorry.
