### ISSUE TITLE
Allow prod mode to be enabled via build-time environment variables + support dead-code elimination

### ISSUE THREAD

**Issue by gdi2290** [angular/angular#6118]
other frameworks support DCE, dead-code elimination, with environment variables for switching between `"development"`, `"production"`, and `"test"` modes
![screen shot 2015-12-24 at 6 25 08 pm](https://cloud.githubusercontent.com/assets/1016365/11999133/b4d73780-aa6b-11e5-8b9d-0c6a447bf80b.jpg)
can we do the same for `enableProdMode`

```
if (process.env.NODE_ENV !== 'production') {
  console.log("I'm in development");
  enableDevMode();
}
```

webpack(w/ DefinePlugin) and browserify(w/ envify) will replace `process.env.NODE_ENV` with `"production"`

```
if ("production" !== 'production') {
  console.log("I'm in development");
  enableDevMode();
}
```

which would then be replaced with

```
if (false) {
  console.log("I'm in development");
  enableDevMode();
}
```

and if they had UglifyJS then the statement would be removed. It would be great to have a list of standard environment variables that all libraries could use for universal modules for example.
- ENV: `'development' || 'production' || 'test'`
- PLATFORM: `'node' || 'worker' || 'browser' || 'browser-ui' || 'atom' || 'recreate-user-agent-standard'`

related: https://github.com/mishoo/UglifyJS2#conditional-compilation

[![github-tipe-logo](https://user-images.githubusercontent.com/1016365/34912701-7edec34c-f89c-11e7-8c89-bed6cef064b5.png)](https://tipe.io?ref=github-comment)

**Comment by IgorMinar** [comment]
@pkozlowski-opensource the "build & ci" component is meant for build and ci of angular/angular.

I think the request should be changed to ask for dev/prod mode to be enabled/disabled based on environmental variables. I'll change the title appropriately.

**Comment by tbosch** [comment]
See https://github.com/angular/angular/issues/12200

**Comment by pkozlowski-opensource** [comment]
This is how things are implemented in ivy (via ngDevMode). Going to close this issue here as:
* it is already fixed in ivy
* we are not planning on fixing it in the current view engine

**Comment by trotyl** [comment]
@pkozlowski-opensource So I guess https://github.com/angular/angular/issues/14358 is not valid anymore?

**Comment by pkozlowski-opensource** [comment]
@trotyl you are right, thnx!
