### ISSUE TITLE
Add support for <component>template data here ... </component>

### ISSUE THREAD

**Issue by born2net** [angular/angular#6124]
I think it would be awesome if you could insert your template inside your component's tags as in

```
 </button>
    <div id="campaignManagerWasp">
      <Sliderpanel>
         <template>
             <!-- Component template will be here -->
          <template>
      </Sliderpanel>
    </div>
    <div id=
```

this will allow for separation of concern and make the template dynamic per each Sliderpanel instance

Regards,

Sean - http://DigitalSignage.com

____________________________________________
MediaSignage.com, FREE Digital Signage for everyone!
5776-D Lindero Cyn Rd #182
Westlake Village, CA 91362
Phone: 1.877.DIG.SIGN (1-877-344-7446)
Fax: 1.818.337.0442
Live support: http://chat.digitalsignage.com

**Comment by zoechi** [comment]
What's your use case? I wouldn't want to specify the template each time I add a component somewhere.

**Comment by born2net** [comment]
In retrospect I think ng-content fills that gap ... closing...
