### ISSUE TITLE
Angular 2 Support template tag for templateUrl

### ISSUE THREAD

**Issue by Nness** [angular/angular#6126]
In Angular 1 we have script tag as `text/ng-template`. Where templateUrl will load from script tag if exist then load from disk. 

For angular 2, if it could support it in similar way with template tag, it would be nice.

This could open up possibility of bundling template and allow writing template outside of javascript file where you can control the template loading instead of rely on angular to load it from URL.

Here is [stackoverflow question](http://stackoverflow.com/questions/33672836/template-as-script-type-text-ng-template-equivalent-with-angular-2?newreg=7147806a581b44e88dc454fdc1d96cc3) for same issue.

**Comment by pkozlowski-opensource** [comment]
We are not planning to add the same mechanism with the `<script>` tags for templates. There are also no plans for supporting `<template>` tags to embed templates code (to be used as URLs).

Instead w are planning to have a pre-compiler (build-time) for templates. Such pre-compiler would convert HTML to JavaScript that can be bundled / minified with an app.
