### ISSUE TITLE
feat(router) Resolve inbound links for PathLocationStrategy

### ISSUE THREAD

**Issue by evanplaice** [angular/angular#6127]
### Issue

AFAIK, routing for PathLocationStrategy on the server-side requires 301 redirecting all requests to the root url. Assuming the following...

*Routes:*
```
example.com/
example.com/projects
```

*and..*
```html
<base href="/">
```

If a user were to bookmark `http://example.com/projects` the common practice is to redirect the incoming request to the root `http://example.com/`, breaking the expected behavior of direct linking.

It is possible to setup the server to maintain the inbound link by prepending the route with a hash.

*For example:*
`example.com/projects` => `example.com/#/projects`

Except, currently there's no built-in support to resolve the hash path.

--------
### Proposal

I have managed to resolve inbound links with the following...

```javascript
import {
...
  Location
} from 'angular2/router';
...
export class MainComponent {
    // ES7 dependency injection
    static get parameters() {
        return [[Location]];
    }

    constructor (location) {
        resolveHashURL(location);
    }
}

// redirects in inbound HashURL to its corresponding route
//  ex. evanplaice.com/#/designs => evanplaice.com/designs
function resolveHashURL (location) {
    let hash = location.platformStrategy._platformLocation.hash;
    if (hash) {
        let path = hash.substring(1);
        console.log('RedirectTo: ' + path);
        location.go(path);
    }
}
```

If a hash is present it converts the hash to a route path by stripping the hash char.

This seems like a 'fragile' approach because it only works with basic routes (ie not wildcard/aux/sub routes). It would make more sense to split the path on '/' and pop the each chunk off when a route can be matched and followed.

In addition, the history should be updated with the resolved path. Currently, the HashURL gets pushed to the history breaking the forward button.

I'm not familiar with the internals of `angular2/route` but I feel like if users choose to use `PathLocationStrategy`, the framework *should* have the ability to implicitly resolve inbound links.

*Note: I have searched the documentation and googled exhaustively for a solution to this issue. If there is a better way to resolve inbound linking, I'm all ears.*

This can be see in action @ [evanplaice.com](http://evanplaice.com)
The full source is available @ [github.com/evanplaice/evanplaice.com](https://github.com/evanplaice/evanplaice.com)

**Comment by robwormald** [comment]
typically you don't actually need to 301 redirect - simply respond to (all/some/specific) requests with the index.html page - and it all works pretty transparently. 

So its more of a rewrite than a redirect.

**Comment by evanplaice** [comment]
@robwormald You're right. The 301 is more of an implementation-specific detail for a server-less setup. In my case, hosting a SPA on S3.

If I used a back-end to route all inbound links to index.html: will Angular be able to follow the route of the inbound url when the app bootstraps; or, will everything be rerouted to the root component? If it's the former, I can understand that it wouldn't make sense to support such a rare edge case (`HashLocationStrategy` is a viable fallback if necessary). If it's the latter, it think it would be awesome to support the proposal and make the routing of inbound links via `PathLocationStrategy` transparent to the users.

Either way, I'm not the one planning or implementing the router so it's not my call. Just trying to be helpful.

Thank you for your time.

**Comment by vicb** [comment]
obsolete - old router
