### ISSUE TITLE
Question: Angular2 editable form with service using Observables?

### ISSUE THREAD

**Issue by panKt** [angular/angular#6130]
Hi, I got a plunker here describing simple form http://plnkr.co/edit/YhtPpSmEgDEZpZ2BKNVA?p=preview

What it does: There is a service that provides data, form - shows ui for user with editable fields bound to model,  **departments_list.ts** component that shows list of departments and current person's department. User changes name - model name changed, user changes department by clicking on it - model's **departmentId** changed. User clicks on 'Save' and in console you can see that it is current model that on screen.
Everything works fine except this is a toy example because in real world you need to fetch data from server and there will be delays. I prepared in **service.ts** lines 11, 17 that need to be uncommented to use completely the same data but pretending it is fetched from server. And this is where I got stuck...

So the question - how to implement this kind of form in Angular2 using Observables with server delay?
Thanks in advance

**Comment by machi1990** [comment]
You could enclose your use ngIf="person" or ngIf="department" in your template to get the behaviour you are seeking. 
E.g <div *ngIf="person"> {{person.name}} </div> etc etc. There could be a better way of achieving this same behaviour, but I have sticked with that for the moment and works just fine.

**Comment by panKt** [comment]
@machi1990 Thanks :+1:
