### ISSUE TITLE
CssSelector.getMatchingElementTemplate doesn't handle known void elements correctly

### ISSUE THREAD

**Issue by azasypkin** [angular/angular#6136]
Angular version: __2.0.0-beta.0__
OS and Browsers: __Ubuntu 15.10__ + __Firefox Nightly__ or __Chrome Beta__

I have the following component directive:
```
@Component({
  selector: 'input[vargin-type=range]'
})
```

When I'm trying to dynamically create this component with ```DynamicComponentLoader``` I get ```EXCEPTION: Template parse errors: Void elements do not have end tags "input" ("<input vargin-type="range">[ERROR ->]</input>"): HostRangeComponent@0:27```

Should ```CssSelector.getMatchingElementTemplate``` handle known void elements like ```HtmlParser``` does or it's forbidden to use known void elements as component selector?

**Comment by pkozlowski-opensource** [comment]
`<input></input>` is not valid HTML so having this as a component doesn't make sense. We don't want to support invalid HTML in selectors and hence the current behaviour (and the error message) is correct.

Closing as "works as expected".

**Comment by azasypkin** [comment]
> ```<input></input>``` is not valid HTML so having this as a component doesn't make sense.

Definitely, that is what I'm talking about, angular's ```DynamicContentLoader``` tries to create _invalid_ ```HTML``` using ```input[vargin-type=range]``` Component selector. 

@pkozlowski-opensource, but why ```CssSelector.getMatchingElementTemplate``` can't return ```<input ..... />``` instead of ```<input></input>``` e.g. using ```isVoid``` flag returned from ```import {getHtmlTagDefinition} from './html_tags';```

Does it mean that ```Component.selector``` is restricted by __non void__ elements only or maybe only by __custom non void__ elements? If so, should not it be noted in the documentation?
