### ISSUE TITLE
Router: router-link-active class is set to previous link, not current one - IE11 - version 2.0.0-beta.0

### ISSUE THREAD

**Issue by varadero** [angular/angular#6140]
Occurs in Chrome 46, Firefox 43, IE 11, 

Plunker:

http://embed.plnkr.co/tW8LFssehyVx1fEqeKs2/

Code:

http://plnkr.co/edit/tW8LFssehyVx1fEqeKs2?p=preview

1. Click on "First" link - first component is loaded but router-link-active class is not added to "First" link so it is not red
2. Click on "Second" link - second component is loaded but router-link-active class is added to "First" link so second component is on the screen but "First" link is made "active" with red background

**Comment by brandonroberts** [comment]
@varadero If you comment out the line below, it works fine. Do you need the system polyfills?

    <script src="https://code.angularjs.org/tools/system-polyfills.js"></script>

**Comment by varadero** [comment]
I think system-polyfills.js is needed if the page is loaded with IE11. At least my IE11 makes additional request (because system.js writes additional script tag into document) for system-polyfills.js and if it is not served, then it throws exception "'System' is undefined". The same happens if in a very simple index.html (no angular) you import only system.js - then system-polyfills.js is requested. This indicates that a polyfill of the system-polyfills.js actually breaks some logic in angular router.

**Comment by brandonroberts** [comment]
@varadero it may be an issue of the order of your scripts. Move angular2-polyfills and es6-shim below the typescript script tag and see if that helps.

**Comment by varadero** [comment]
@brandonroberts Moving angular2-polyfills.js below system.js script tag did the trick. Thank you Brandon ! I was following Angular Quick Start from here:

https://angular.io/docs/ts/latest/quickstart.html

Where the angular-polyfills.js script tab is at first place, maybe it should be moved after system.js script tag in order to overcome IE11 problem (surprisingly [or not ?] IE10 do not have problems with original Plunker).
