### ISSUE TITLE
root element gets replaces when using class name as app selector

### ISSUE THREAD

**Issue by episodeyang** [angular/angular#6144]
The plunkr is here: http://plnkr.co/edit/onTLf5hcjX4iG6A1H3Hp?p=preview

In order to reproduce: 

1. use a class name for the selector
2. add multiple classes to that root element in addition to the app component selector class

Symptom:

All of the additional classes are removed.

**Comment by pkozlowski-opensource** [comment]
@episodeyang it is not clear here what the error is... Could you please simplify your plunker to the bare minimum (the current one is kind of massive)?

**Comment by zoechi** [comment]
The title is misleading. As you said other classes are removed. It's not about the root element being replaced.

**Comment by pkozlowski-opensource** [comment]
Closing as we didn't hear back from the opener.
