### ISSUE TITLE
Dart doesn't accept components without selector

### ISSUE THREAD

**Issue by kasperpeulen** [angular/angular#6146]
I was trying to convert the typescript routing tutorial to Dart, but it seems to work differently in Dart.

For example, the following code fails. It seems to be that dart doesn't accept Components like this without a selector.

```dart
@Component(
    template: '''
    <h2>CRISIS CENTER</h2>
    <p>Get your crisis here</p>`
    '''
)
class CrisisListComponent {}

@Component(
    template: '''
    <h2>HEROES</h2>
    <p>Get your heroes here</p>`
    '''
)
class HeroListComponent {}

@Component(
    selector: 'my-app',
    template: '''
    <h1 class="title">Component Router</h1>
    <a [routerLink]="['./CrisisCenter']">Crisis Center</a>
    <a [routerLink]="['./Heroes']">Heroes</a>
    <router-outlet></router-outlet>
    ''',
    directives: const [ROUTER_DIRECTIVES])
@RouteConfig(const [
  const Route(
      path: '/crisis-center',
      name: 'CrisisCenter',
      component: CrisisListComponent,
      useAsDefault: true
      ),
  const Route(path: '/heroes', name: 'Heroes', component: HeroListComponent)
])
class AppComponent {}

main() {
  bootstrap(AppComponent, [ROUTER_PROVIDERS]);
}
```

**Comment by ericmartinezr** [comment]
If those components are being instantiated by routing there's no need to pass them in the directives. Remove them from directives property.

**Comment by kasperpeulen** [comment]
@ericmartinezr I tried that, but same problem.

**Comment by kasperpeulen** [comment]
see this repo to reproduce:
https://github.com/ng2-dart-samples/routing-sample

**Comment by kasperpeulen** [comment]
This still doesn't work in beta.1.

@yjbanov I'm not sure of anyone of the angular team has seen this issue because of christmas etc. But I think this is a serious bug.

**Comment by zoechi** [comment]
I also encountered this with a component I tried to pass to `TestComponentBuilder`. Even here it needs to have a selector.

**Comment by kevmoo** [comment]
@kegluneq Can you look into this?

**Comment by kegluneq** [comment]
Yep, will do

**Comment by yjbanov** [comment]
@kasperpeulen, @zoechi: This is certainly a bug. The transformer seems to assume that all components are meant to be used in templates, where you need a selector. That is not the case for router-instantiated components or any component instantiated using `DynamicComponentLoader`. How critical is this? It seems a workaround is to simply add a selector to the component.

**Comment by kasperpeulen** [comment]
@yjbanov I guess the priority is because this is required to port a typescript example to Dart. I would rather write: "This how it works." Then, "Because of a bug, you now have to do this workaround, but in the future you can do it also without a selector."

**Comment by yjbanov** [comment]
Fair enough. Bumping to P1.

**Comment by tbosch** [comment]
Hello,
the router is creating a new element for every component it routes to. 
This element is created via the selector of that component. E.g. a component with a selector `div[test]` will be created on an element `<div test>`. 

There was a past version of Angular2 that allowed to reused an existing element, but since some months the only way to load a new component is by creating a new element based on the selector.

In which version of Angular 2 did this work?

We need to update the typescript routing tutorial...

**Comment by kegluneq** [comment]
Now that I don't really have any background on this, unassigning myself

**Comment by yjbanov** [comment]
Since we require selectors, closing with `WORKS_AS_INTENDED`

**Comment by zoechi** [comment]
Here https://github.com/angular/angular/issues/1662#issuecomment-98928582 it seems then intention was to just use `<div>` if no selector is defined. If this is not supposed to work anymore then I think #1662 should be closed as well.

**Comment by yjbanov** [comment]
Wasn't aware of #1662. Good find. Let's continue the discussion there.

**Comment by jodinathan** [comment]
Hi,

Could you guys throw a warning on components without selector or an exception?
The only thing that chrome says when I click the router link is "EXCEPTION: NullError: method not found: 'Q' on null"
It took a whole day to figure this out.

Seriously, this almost made me drop the project in angulardart2.

**Comment by DzmitryShylovich** [comment]
Dart repo is here https://github.com/dart-lang/angular2

**Comment by jodinathan** [comment]
thanks
