### ISSUE TITLE
RouteParams.params is not of type Map<String,String>

### ISSUE THREAD

**Issue by kasperpeulen** [angular/angular#6147]
In the docs it is aid that RouteParams.params is of type `Map<String,String>` but this is not always the case it seems:

![image](https://cloud.githubusercontent.com/assets/1035299/12018148/e73f351e-ad5f-11e5-8ebf-afba4b948da9.png)

see the debugging message, in this case the value is of type `int` and not of `String`

**Comment by varadero** [comment]
You should check this.params not this.params['id'].

**Comment by vicb** [comment]
obsolete - old router
