### ISSUE TITLE
Router: When user goes away from current state and then comes back again, the state of the view is somehow cached - 2.0.0.0 beta.0

### ISSUE THREAD

**Issue by varadero** [angular/angular#6148]
Plunker:
http://plnkr.co/edit/RcA0ofTFVlZmtpBqmR9m?p=preview

The problem is that if the user made some changes to components' template not bound to controller (for example a simple check box without ngModel) and then navigates to another state and comes back to first one, the controls preserved their state. Look at explanations at above plunker.

Such behavior breaks synchronization between the view and controller state - for example if the user uses "changed" event of a drop down in a parent state to change child states, navigating away of parent state and coming back again shows the last selected drop down value but the loaded route is the default, possibly different than the one, selected in the drop down.

Is the caching of current view state when user navigates away intentional ?

**Comment by greg-md** [comment]
You have to use angular:

```javascript
<input type="checkbox" [checked]="checked1" />
<input type="checkbox" [checked]="checked2" />
<input type="checkbox" [checked]="checked3" />
```

**Comment by varadero** [comment]
@greg-md The problem is when I bind certain view elements to component controller and use only View -> Controller data flow for others. Like in case of changing a drop down and calling some method by ``` (change)="selectionChanged(...)"``` If you navigate away of the current state and then come back, the drop down will show say third item as selected but the state of the controller and other view parts bound to the controller will be in "initial" state.

Such behavior confuses me a little, because I'm developing everything in an "initial" state where view and controller are "synchronized" but at runtime they are not.

**Comment by greg-md** [comment]
I understood you. You should use angular to return them to the default state, because angular save the component state in background.

You could also try CanReuse interface: https://angular.io/docs/ts/latest/api/router/CanReuse-interface.html

**Comment by ericmartinezr** [comment]
Related to https://github.com/angular/angular/issues/5188

**Comment by varadero** [comment]
@greg-md I tried to use CanReuse by returning false but it doesn't help. Check boxes, text fields and select elements retain their values.

http://plnkr.co/edit/bOVcoful8zS3lz6KHcrg?p=preview

The interesting thing here is that "CanReuse" / "OnReuse" are called only if you are on the "Second" state and click again "Second" state link. But even then, values of each input element survive router navigation.

**Comment by vicb** [comment]
Could you please check if the issue still applies to 2.0.1 ? Thanks.

**Comment by vsavkin** [comment]
I don't think the issue still makes sense in the context of the new router. If you think it does, please reopen it with a plunkr reproducing the issue.
