### ISSUE TITLE
Deeply linked aux-routes is not working

### ISSUE THREAD

**Issue by abhibly** [angular/angular#6150]
Hie. I am trying to use aux-routes in a router-outlet.But it is not working. I came to know deep linking of aux-routes is not supported in angular2-beta. Is it true? I have created a plunker demo->http://plnkr.co/edit/MVWG76rh7PDvzc3oMYgB?p=preview  Hope someone helps me.

**Comment by wardbell** [comment]
Aux routes are broken at the moment. I'd avoid them until you see an announcement.

**Comment by bwells78** [comment]
What is current state of aux routes?  I'm trying to implement them and not sure if issues I'm seeing are my misunderstanding or them not being fully ready-

**Comment by CaptainCodeman** [comment]
Work has started on a re-write of the router: https://github.com/angular/angular/pull/8173

Current "new router" will most likely be deprecated. I don't know if the new one will have the exact same features, weekly meeting notes hint that it will be different in some ways.
