### ISSUE TITLE
ngAfterContentChecked and ngAfterViewChecked triggering on mouse movement?

### ISSUE THREAD

**Issue by gaiottino** [angular/angular#6152]
Hi,

I was trying to make an Angular2 component using Gridifier http://gridifier.io but quickly ran into a problem where `ngAfterContentChecked` and `ngAfterViewChecked` would trigger like crazy. I found at least one culprit which is a mousemove listener and I'm not sure this is by design or if it is a bug.

I created a plunkr http://plnkr.co/edit/btcVt7K9zIxaAxJrQ2ef?p=preview which just creates a mousemove listener to highlight the problem since in my component I init gridifier which in turn listens to mousemove.

Why does the mousemove listener in an external lib (or in my example manually added to a div using JQuery cause Angular to trigger these? If not a bug, how should I have initiated my mouselistener to not trigger the Angular methods?

**Comment by gaiottino** [comment]
If I update the code and add a listener to `System.import('app').then(...)` then Angular does not pick it up. Here's an updated plunkr showing this http://plnkr.co/edit/X2m7Wp0mYQtkUR4M9NNs?p=preview.

**Comment by robwormald** [comment]
you can use the `zone.runOutsideAngular` hook to accomplish this : http://plnkr.co/edit/cOsDQ2C3pCx0O8ZuwdBh?p=preview

**Comment by gaiottino** [comment]
Ah. Thanks for that.
