### ISSUE TITLE
how time angular2_material   support  List Menu Slider Tabs

### ISSUE THREAD

**Issue by iloveyo123u1** [angular/angular#6153]
how time angular2_material   support  List Menu Slider Tabs

thank you

**Comment by zoechi** [comment]
Please use StackOverflow, Gitter- or Slack channels,  or Google groups for questions. The issues are for bug reports and feature requests.

**Comment by pkozlowski-opensource** [comment]
I guess the question is about _when_ a given material component will be supported. If so the answer is: there are no dates set. You can hear about the progress on the material design components (in both Angular1 and Angular 2) in this video: https://www.youtube.com/watch?v=WitNPCLSZr0 (starting at 1 minute 30 seconds).
