### ISSUE TITLE
bug(router): navigating imperatively with router.navigate causes unexpected browser reload

### ISSUE THREAD

**Issue by cburgdorf** [angular/angular#6154]
I stumbled over some strange (to me) behavior with the router. Basically navigating imperatively through `router.navigate(args)` seems to force a browser reload if I don't wrap the call with a `setTimeout`.

Additionally I see the `?` character appearing in the URL for a brief moment before the reload.

So, to let code speak, this shows the faulty behavior:

```
this.router.navigate(['ContactDetail', {id: contact.id}]);
```

Whereas this works fine:

```
setTimeout(() => this.router.navigate(['ContactDetail', {id: contact.id}]));
```

I failed to put up a plunkr that demonstrates the bug. I created a repository instead.

https://github.com/cburgdorf/angular2-router-bug

To reproduce the behavior just follow these steps

1. Clone the repository

2. Run `npm install`

3. Run `npm start`

4. Click on any contact

5. Click *Edit*

6. Click *Cancel*

You should see the browser reloading as described which is caused by this line:

https://github.com/cburgdorf/angular2-router-bug/blob/master/app/components/contact-editor/contact-editor-component.ts#L41

If you comment that line and uncomment this instead it works just fine:

https://github.com/cburgdorf/angular2-router-bug/blob/master/app/components/contact-editor/contact-editor-component.ts#L44

**Comment by brandonroberts** [comment]
Might be a bug or an event bubbling issue with the form. If you return false in the `cancel` and `save` functions it works as expected. If you use the button outside the form tags, it works as expected also.

**Comment by cburgdorf** [comment]
Hey Brandon! Great find. Thanks for looking into it. I didn't think about the form. The behavior can also be fixed simply by giving the buttons `type="button`. Because if we omit the type they become `type="submit"` by browser default.

So, I think what we see here is just the browsers default submit behavior (also with appending the `?` char to the URL. The browser does exactly that for forms without `action` even if Angular isn't used at all).

This leads us to the question: Why does it fall back to the browsers default submit behavior in this particular case but not in others.

For instance if we add `<input type="submit" name="name" value="save">` to the form and click it, nothing happens. I would have actually expected the form to get submitted like a regular form in that case. 

Also if we add `<button class="btn" (click)="noop()">Save</button>` and click it, nothing happens. So Angular seems to prevent the default browser submit action even in cases where I would not expect it to get prevented but ironically lets it happen for the case where we invoke an action that calls `router.navigate(args)`.

**Comment by brandonroberts** [comment]
Good explanation Christoph. I also thought the default behavior was to prevent the default action as long as a non-truthy value was returned from the function, which is what made me think about the form.

**Comment by wardbell** [comment]
Looks like one for @vsavkin

**Comment by adnan15110** [comment]
Is this issue resolved??
Thanks in Advance.

**Comment by stefanocke** [comment]
I tried the [setTimeout-workaround](https://github.com/cburgdorf/angular2-router-bug/blob/master/app/components/contact-editor/contact-editor-component.ts#L44) and had some success but got the exception as described [in 6786](https://github.com/angular/angular/issues/6786) then.
Finally, I just tried to return false after navigating. Now it seems to work (since the ngSubmit is suppressed as described by @brandonroberts ?).
I am (still) on beta7.

**Comment by vicb** [comment]
obsolete - old router
