### ISSUE TITLE
IE11 Life Cycle Hooks not firing and [class.hidden] not working

### ISSUE THREAD

**Issue by ahitchen** [angular/angular#6155]
Hello,
I initially used [class.hidden] to hide/display popups, but then when the router took you to a new page, all the popups would be displaying by default in IE11. I fixed that issue with *ngIf, but now a new issue has popped up.

IE 11 is not firing "ngOnInit()" until I interact with the page. When the page loads I see all the icons that should either be hidden or displayed depending on the state. I assume this is because I am using [class.hidden] still for the icons. Separately, I have two tabs to the side that display different content using an [ngSwitch].

ngOnInit and ngAfterContentInit are only firing once I toggle between the two tab pages.
This is where the documentation mentioned I should be doing most of my initialization work. This is where I make the initial API calls to get the information to load on the page.

Is there something I am doing incorrectly, or is this a bug?

**Comment by ahitchen** [comment]
if I add the API calls back into the constructor, it gets the information, but the view still does not update until I interact with the page.

**Comment by hecurb** [comment]
You should try the suggestion mentioned in #6149

**Comment by ahitchen** [comment]
#6149 fixed the issue. Hopefully it doesn't cause any others though.
