### ISSUE TITLE
2.0.0-beta.0: Templates do not update in IE11

### ISSUE THREAD

**Issue by hecurb** [angular/angular#6157]
Testing out a simple app using the following code and the data is not being updated in IE.  This works in other browsers:

--- libraries used ---

<script src="../node_modules/es6-shim/es6-shim.js"></script>
    <script src="../node_modules/angular2/bundles/angular2-polyfills.js"></script>
    <script src="../node_modules/systemjs/dist/system.src.js"></script>
    <script src="../node_modules/rxjs/bundles/Rx.js"></script>
    <script src="../node_modules/angular2/bundles/angular2.dev.js"></script>

--- component.ts ---

import {Component} from 'angular2/core';

@Component({
    selector: 'my-app',
    template: `
    <h1>{{title}}</h1>
    `
})

export class app{

    public title: string = "current title";

    constructor() {
        setTimeout(() => {
            this.title = "updated title"
        }, 1000)
    }
}

Is there a bug or am I missing a library I need to include?

Thanks.

**Comment by ahitchen** [comment]
This might be related to my issue here: #6155 I have a feeling it has something to do with change detection in IE11, but then again I know nothing.

**Comment by hecurb** [comment]
The suggestion mentioned in #6149 fixed my issue.

Looks like system.js needs to be included first.
