### ISSUE TITLE
Enforcing Unidirectional Data Flow in Dev Mode

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#6160]
Currently, the following won't work in the dev mode:

```
@Component({template: `<child [filtered]="filtered">`})
class MyComponent {
  list;
  get filtered() {
    return list.filter(x => x > 4);
  }
}
```

This is because in the dev mode Angular walks the change detection graph twice: the first time to apply the changes, and the second time to check that nothing changed.

What does it mean "nothing changed"? Currently, we make sure that all the bindings produce the same object. The same in our case means "the same instance". 
### Specify Custom Equality in the Template

The following can be done right now without any changes to the framework:

```
@Component({template: `<child [filtered]="filtered|listEq">`})
class MyComponent {
  list;
  get filtered() {
    return list.filter(x => x > 4);
  }
}
```

The listEq pipe is a noop in the prod mode. In the dev mode, it will do the structural check. This solution works, but it is not very ergonomic.

Pros:
- works right now
- explicit

Cons:
- bad dev ergonomics
### Specify Custom Equality in Some Registry

We could make change detection pluggable, where you could specify custom equality checks for datatypes. 

Pros:
- good dev ergonomics

Cons:
- new concept
- slow (you have to run same checks in both the dev and prod modes)
### Nothing Changed Means Nothing Changed Visually

Instead of checking that bindings produce same instances, we can check that there are no changes in the DOM. We can do it by having a special flag in the renderer. So before running change detection second time, we will set this flag to true. And if any directive invokes the renderer, we will throw. 

Pros:
- no performance impact
- no new concepts
- easy to explain

Cons:
- it is a more relaxed check

**Comment by vsavkin** [comment]
I vote for "Nothing Changed Means Nothing Changed Visually"

**Comment by vsavkin** [comment]
@IgorMinar @mhevery @wardbell

**Comment by robwormald** [comment]
First question for me is "*should* we make the above code work"? 

I realize that's a off-the-cuff example, but I can't see a good reason to enable that sort of thing. I'd rather we throw an error and point them towards a documentation section explaining why having change detection trigger side effects is probably a bad idea, and that it would be preferable to assign the filtered list to a property. 

The "Nothing Changed Means Nothing Changed Visually" seems to solve the problem of annoying error messages in dev but it would seem to then allow less-performant code to actually ship into production / get missed? Am I misunderstanding that?

Maybe we should have a dev mode ("Nothing Changed Means Nothing Changed Visually") and a strict mode (what devmode does today, throw all the errors to help optimize your app pre-production)

**Comment by mhevery** [comment]
Even if nothing change visually, there could be side effects such as XHRs.
(This actually happened in the past). So visually is kind of arbitrary line
in the sand.

**Comment by robwormald** [comment]
@mhevery just to be clear, "side effects such as XHRs" - this is a Bad Thing, yes?

**Comment by mhevery** [comment]
correct.

**Comment by wardbell** [comment]
Interestingly, an XHR side-effect would NOT be caught by any form of DevMode because the effect occurs in the next JS turn. It feels like a bad thing ... but isn't a violation of uni-flow strictly speaking.

**Comment by vicb** [comment]
@vsavkin can this be closed ?
