### ISSUE TITLE
TemplateRef not accessible through a local variable

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#6163]
I was expecting that the following would be possible:

```javascript
@Component({
    selector: 'hello-app',
    template: `
        <template #tpl>
            Foo <span>Bar</span>
        </template> 
        <button (click)="showTpl(tpl)">Get template ref</button>
    `,
    directives: [NgbTooltip]
})
export class HelloApp {
    showTpl(tpl) {
        console.log(tpl);
    }
}
```

but the `tpl` in `showTpl` comes as undefined. The real use-case here is a class of tooltip-like directives where one could do:

```html
 <template #tpl>
     Foo <span>Bar</span>
</template> 
<button [tooltip]="tpl">Some button</button>
```

for cases where people want to specify some HTML as tooltip's / popover's content.

**Comment by mhevery** [comment]
Yes, this is a know problem. The issue is that `<template #tbl>` defines an input `tpl` field which can be used in template. What you want to do is declare a reference, rather than input variable.

**Comment by mhevery** [comment]
Dup of https://github.com/angular/angular/issues/7142
