### ISSUE TITLE
Problem with ng-content select atribute on components encapsulation.

### ISSUE THREAD

**Issue by majo44** [angular/angular#6164]
Problem is when one component wraps another one and is trying to provide the nested content to wrapped component, which additionally is trying to take this nested content by selectors.

**Case 0**
http://jsfiddle.net/majo44/nvaqhsse/

The goal is to provide component X-B which encapsulate component X-A, with possibility to provide nested content to X-A from usage of X-B.

X-A component
```javascript
@Component({
    selector: "x-a",
    template: `
            X-A Start
                <ng-content></ng-content>
            X-A End`
})
class XA{}
```

X-B component
```javascript
@Component({
    selector: "x-b",
    template: `
            X-B Start
            <x-a>
                <ng-content></ng-content>
            </x-a>
            X-B End`,
    directives: [XA]
})
class XB{}
```

Example usage
```javascript
@Component({
    selector: 'app',
    template: `
        <x-b>
            <div class="aClass">AClass Element</div>
            <div class="bClass">BClass Element</div>
        </x-b>
    `,
    directives: [XB]
})
class App{}
```

As a output I got:
```html
<app>
    <x-b>
        X-B Start
        <x-a>
            X-A Start
            <div class="aClass">AClass Element</div>
            <div class="bClass">BClass Element</div>
            X-A End
        </x-a>
        X-B End
    </x-b>
</app>
```

In this case everything works fine as I expected. 

**Case 1**
http://jsfiddle.net/majo44/nvaqhsse/1/

Now lets modify x-a component whit adding selectors to ng-content (eg. for reverse order of children, in real case this can be for placing content in different places of my page layout).

X-A component:
```javascript
@Component({
    selector: "x-a",
    template: `
            X-A Start
            <ng-content select=".bClass"></ng-content>
            <ng-content select=".aClass"></ng-content>
            X-A End`
})
class XA{}
```

Now output do not contains any of content provided to x-b component
As a output I got:
```html
<app>
    <x-b>
        X-B Start
        <x-a>
            X-A Start
            X-A End
        </x-a>
        X-B End
    </x-b>
</app>
```

**Case 2**
http://jsfiddle.net/majo44/nvaqhsse/2/

As a workaround I can re-package my content in x-b component (this is not good because I have to always know exact the x-a ng-content selectors in x-b component, this is not superb flexible)

X-B component
```javascript
@Component({
    selector: "x-b",
    template: `
        X-B Start
        <x-a>
            <div class="aClass">
                <ng-content select=".aClass"></ng-content>
            </div>
            <div class="bClass">
                <ng-content select=".bClass"></ng-content>
            </div>
        </x-a>
        X-B End`,
    directives: [XA]
})
class XB{}
```

Output looks better, but there still is a problem, because  ng-content is taking whole selected element I have now duplicated &lt;div class="...Class">:

```html
<app>
    <x-b>
        X-B Start
        <x-a>
            X-A Start
            <div class="bClass">
                <div class="bClass">BClass Element</div>
            </div>
            <div class="aClass">
                <div class="aClass">AClass Element</div>
            </div>
            X-A End
        </x-a>
        X-B End
    </x-b>
</app>
```

As I think, the best flexible solution for this will be support of *Case 1* directly. As an alternative solution for *Case 2* ng-content can provide additional attribute for "unwrap" the content from "selected" element.

Angular Version: 2.0.0-beta.0
Browser: Chrome

**Comment by michalstepien** [comment]
+1

**Comment by jjk3yz** [comment]
This limitation in ng-content affects our ability to create rich declarative components using markup. Would be nice to be able to define a tab component like this:

```
<tabs>
     <tab>
          <tab-title> </tab-title>
          <tab-content>  </tab-content>
     </tab>
    <tab>
          <tab-title> </tab-title>
          <tab-content>  </tab-content>
     </tab>
</tabs>
```

instead of this:

```
<tabs>
         <tab-title> </tab-title>
         <tab-content>  </tab-content>
         <tab-title> </tab-title>
         <tab-content>  </tab-content>
</tabs>
```

**Comment by vicb** [comment]
[`ngProjectAs`](https://github.com/angular/angular/blob/33340dbbd156d45e50b886f05095551f41c38600/modules/%40angular/compiler/test/template_parser/template_parser_spec.ts#L1236) might help you there.

There is an open PR on the docs site (angular/angular.io) to document it. Meanwhile the tests should be helpful to understand it.

**Comment by craigmichaelmartin** [comment]
@jjk3yz Does ngProjectAs address the example you posted?
