### ISSUE TITLE
This https://angular.io/docs/ts/latest/tutorial/ is NOT available for javascript.

### ISSUE THREAD

**Issue by adamchenwei** [angular/angular#6172]
it's only available for TypeScript. Would it possible made available for javascript as well? Thank you

**Comment by ericmartinezr** [comment]
@adamchenwei the repo for the website is https://github.com/angular/angular.io . Besides that I'm pretty sure they're working on it :)

**Comment by adamchenwei** [comment]
@ericmartinezr ah, I thought here is where I should post the issue. Shall I repost this issue? or I can some how move it? Thanks for the info btw.

**Comment by abhilashpullelil** [comment]
Yes, it is too difficult to find example or tutorials for Angular2.0 using javascript.

**Comment by ThiagoT1** [comment]
I also felt this need.

Writing an app using ES5 was a way of understanding more o what's going on
with the TS magic going on (decorators, metadata and so on).

With the docs in its actual state, there's no easy way do create
Components, Directives or Injectables and still maintain their unique
prototypes, not to mention subclassing.

Are we encouraged to go full typescript no matter what? Will ES5 be
supported, documentation wise?

Thiago

**Comment by PascalPrecht** [comment]
Hold your horses everyone. We're working hard on a decent ES5 strategy for all the docs. Just putting ES5 code in there doesn't do the trick, we need to establish best practices and clean APIs for ES5-land as well. As long as that's unclear, we can't put them up online because everyone would either complain, or write less good code.

We have some pending PRs for ES5 versions so stay tuned.

**Comment by khuongduybui** [comment]
Please do not forget this. (feel free to delete this comment)

**Comment by adamchenwei** [comment]
Did this resolved @vicb ? Wonder what is the reason closing it?

**Comment by khuongduybui** [comment]
Of course it's not resolved. The issue, however, should be tracked in https://github.com/angular/angular.io/issues repo instead.
