### ISSUE TITLE
A2 warning/error messages should all have links

### ISSUE THREAD

**Issue by wardbell** [angular/angular#6173]
Brought to mind by the message from DevMode which tells you that you can use ProdMode but doesn't tell you why or how.  Nor do I think it should. I think it should have a link.

A1 has links which is great! Also helped with size of the production version I'm sure. Let's do that in A2 too!

**Comment by splincode** [comment]
@wardbell Is the issue relevant?

**Comment by pkozlowski-opensource** [comment]
Duplicate of #18875
