### ISSUE TITLE
Using angular2 with Existing html tags.

### ISSUE THREAD

**Issue by mikeandersun** [angular/angular#6178]
n Angular 1 we set  `ng-controller` for any HTML tag in the Razor view and use the functions defined in the angular controller within the tag. How I can achieve this view Angular2? For exapmle I want to click on a HTML tag in Razor View and call a method from an angular2 component or directive. 
In other word I need a component without any template or view. It is have some methods that i can call  them from my Index.html.
It is possible?

**Comment by zoechi** [comment]
I don't know Razor view but maybe you're looking for `Directive`. GitHub issues are for bugs and feature requests, for questions please use other channels like StackOverflow, Google groups, Gitter,...

**Comment by mikeandersun** [comment]
@zoechi  I create a plunker for what is in mind here: http://plnkr.co/edit/TpsBwe?p=preview
I don't know this scenario can support in Angular2 or not. If not , I think it is a good feature to have. 
Thank you for your time.

**Comment by gdi2290** [comment]
There're a few ways to do this so it all depends on what your goal is. If you're trying to communicate messages from outside of the ng2 app you could do so by using javascript for index.html and create an EventEmitter or use a global Observable then create a service to interact with index events that will trigger your method.


```es6
// index
// this code is used outside of ng2 and assuming Observable is global from rx
window.__indexObserver = new Rx.Observable();
$('div button').click(function() {
  window.__indexObserver.next({
    action: 'save',
    args: [event]
  });
});
```
```typescript
// app
class IndexService {
  observer = new Rx.Observable();
  constructor() {
    window.__indexObserver.subscribe(observer);
  }
}

@Component({ /*... */})
class App {
  constructor(public index: IndexService) {
  
  }
  ngOnInit() {
    this.index.subscribe(event => {
      switch(event.action) {
        case 'save': return this.onSave(...event.args);
      }
    });
  }
  onSave() { /*... */}
}
```

The example is assuming you want events/data to flow down to your root component but you can easily send events back. I also created an IndexService for testing reasons so if we're lazy we can remove that step. We can also simply make the top level component the body tag then it's all ng all the way down

**Comment by pkozlowski-opensource** [comment]
This sounds like a support request and as such should be redirected to the appropriate support channel: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
