### ISSUE TITLE
Use of local template variable within a *ngIf

### ISSUE THREAD

**Issue by darknessm0404** [angular/angular#6179]
Hi,

With the beta 0, with a template like that:

    <input #test *ngIf="isVisible">
    <button (click)="focusInput(test)" *ngIf="isVisible">Focus it</button>

Even if boolValue is true (the input will be visible), test will be "undefined" in the click handler.

The only "fix" someone gave me was to make a directive to autofocus.
The problem that everytime I will need to access a field that may be hidden by a * [embedded template], I won't be able to use it, even if in plain javascript I could test if its value was defined or not.

Plunker link:
http://plnkr.co/edit/JmBBHMo1hXLe4jrbpVdv?p=preview

Is this a "bug" or an expected behaviour? 
Is there a more efficient way to deal with this?

**Comment by bennylut** [comment]
As I see it - the test variable in `focusInput(test)` refers to the field `test` of the component class - since such field is not defined you are getting `undefined` passed to the `focusInput` method. 

One fix that I know about is to use the [ViewChild](https://angular.io/docs/ts/latest/api/core/ViewChild-var.html) annotation and to actually declare the test field:

````
@Componenet({
  template: `
    <input #test *ngIf="isVisible">
    <button (click)="focusInput(test)" *ngIf="isVisible">Focus it</button>
  `,
...})
class MyComponent {
  @ViewChild('test') test;
}
```

**Comment by kasperpeulen** [comment]
> As I see it - the test variable in focusInput(test) refers to the field test of the component class - since such field is not defined you are getting undefined passed to the focusInput method.

I think this must be a bug with `*ngIf` because if you use `[hidden]` instead, everything works fine:

http://plnkr.co/edit/gVhzUEYaXuttK2tVmi2t?p=preview

**Comment by darknessm0404** [comment]
@bennylut Then why can we do "#test" if we can't use it in the template?
It's still a bug for me, as the documentation (of https://angular.io/docs/ts/latest/guide/template-syntax.html) clearly states it:
"We can reference a local template variable on the same element, on a sibling element, or on any of its child elements.

<input #phone placeholder="phone number">
<button (click)="callPhone(phone.value)">Call</button>"

@kasperpeulen hidden is only working because it's the way browsers work, it has no impact on creating/removing the node from the DOM.

**Comment by RomanGotsiy** [comment]
This still doesn't work in RC.3.
@bennylut workaround works fine for this particular example but it doesn't work if local reference is specified inside `ForOf` as we have lots of references and `ViewChild` queries the first.

this works:
```html
<div *ngFor="let thing of things">
  <span (click)="props.toggle()">
    {{thing.name}}
  </span>
  <div>
    <collapse #props>
      something
    </collapse>
  </div>
</div>
```

and this doesn't (even if `thing.extra` is `true`)
```html
<div *ngFor="let thing of things">
   <span (click)="props.toggle()">
    {{thing.name}}
  </span>
  <div *ngIf="thing.extra">
    <collapse #props>
      something
    </collapse>
  </div>
</div>
```

Check out [Plunker](http://plnkr.co/edit/z8YB4kaC39r3D5YE1rGy?p=preview)

**Comment by Splaktar** [comment]
I'm seeing this in rc.4: https://github.com/vaadin/vaadin-grid/issues/411

I really hate to have to use `display: none` or `[hidden]`, but they do actually "work"...

**Comment by dereklin** [comment]
Is it right that it used to work in rc.1 and is no longer working in rc.4?

**Comment by tbosch** [comment]
@RomanGotsiy your plunker works as intended:

A variable declared inside of an `*ngIf` cannot be used outside of the `*ngIf` (as in your plunker), but the other way around works now (to the time when this issue was filed this was not the case though).

I.e. this should work.
```
<div *ngFor="let thing of things">  
   <span *ngIf="thing.extra" (click)="props.toggle()">
    {{thing.name}}
  </span>
    <collapse #props>
      something
    </collapse>
</div>
```

**Comment by tbosch** [comment]
See http://plnkr.co/edit/s0Z2xdoIAMiR2oPZjlcr?p=preview.

**Comment by poke** [comment]
@tbosch I’m not sure why you are closing this. This seems to be a desired functionality (the one outlined in the original post on this issue).

**Comment by Splaktar** [comment]
I guess that I'll have to open a separate issue for my problem mentioned here: https://github.com/angular/angular/issues/6179#issuecomment-233114296

**Comment by Splaktar** [comment]
Tried to reproduce my issue in a [Plunkr](http://plnkr.co/edit/skEbKkk6tMTypVuslgvj?p=preview) but wasn't able to do so with an Angular 2 component.

It seems to only occur with angular2-polymer or vaadin-grid elements. So I've re-opened my issue here: https://github.com/vaadin/vaadin-grid/issues/411

**Comment by tbosch** [comment]
@poke Yes, the example in my comment shows the desired behavior and the plunker shows that this is working now. Only the opposite way (i.e. declare a variable inside of `*ngIf` and use it outside of `*ngIf`) is not working, and won't work by design.

**Comment by lindsaymarkward** [comment]
Can I confirm that the plan/design is for this to never work?
```
<div *ngIf="x.y">...</div>
<app-component #x></app-component>
```
when this does work?
```
<div [hidden]="x.y">...</div>
<app-component #x></app-component>
```
(where y is a variable within app-component that x refers to)

It seems sad that we can set the hidden property but not remove the component with *ngIf.

**Comment by poke** [comment]
@lindsaymarkward No, that example does work (see [plunkr](http://plnkr.co/edit/fN5WVjSRfJuA3bCQqjQl?p=preview)).

What will not work is if the component that declares a reference is within an `ngIf`, e.g.:

```html
<div *ngIf="show">
  <div *ngIf="x.y">...</div>
</div>
<div *ngIf="show">
  <!-- this makes the #x conditional, so is not available to others outside -->
  <app-component #x></app-component>
</div>
```

**Comment by lindsaymarkward** [comment]
Thanks, that's what I meant, actually. My code example was intended to be like yours with the div surrounding the component.
So, what is the pattern for conditionally showing/including a component (or element that surrounds it) based on the data in that component?

**Comment by brendanarnold** [comment]
Why is this closed? The problem still exists i.e. in the template ...
```
<div *ngIf="showMyDiv">
  <h1 #mytitle>My Title</h1>
</div>
```
and in the component class ....

```
@ViewChild('mytitle') title;
```
`title` is always undefined if `showMyDiv` starts out `false` but later set to `true`

This is a pretty common scenario and means I have to resort to binding to `hidden`. Am I missing something?

**Comment by michaelb-01** [comment]
I also have this issue, is there a solution yet?

**Comment by DzmitryShylovich** [comment]
use `@ViewChildren`. it returns QueryList which will notify u when element is present on the page.

**Comment by michaelb-01** [comment]
I have this working now. I'm using it on a video element to control the video among other things. I also need to get the width of the video so I tried the following but it returns 241 when the video is actually more like 600px, is it trying to get the width before the element has fully loaded?

  ngAfterViewInit() {
    this.mediaQuery.changes.subscribe(el => {
      this.media = el._results[0].nativeElement;
      console.log(this.media.clientWidth);
    });
  }

**Comment by kub1x** [comment]
As a solution I found the following. My issue was closest to what what @brendanarnold wrote. I wasn't able to make running the plnkr what @bennylut posted [up here](https://github.com/angular/angular/issues/6179#issuecomment-168042640). 

Say you have following template: 
```
<pre>{{test.value}}</pre>

<button (click)="isVisible = true">Show it</button>
<input #test *ngIf="isVisible">
```
Then in your component you "grab" the test element like this: 
```
private test: ViewContainerRef;
@ViewChild('test') set someDummySetterName(theElementRef: ViewContainerRef) {
    this.test = theElementRef;
}
```
The setter is called every time the `*ngIf` directive changes so the `this.test` on controller always corresponds to the actual state and, as a controller variable, it is visible everywhere in the template. 

Taken from here: http://stackoverflow.com/a/41095677/336753

**Comment by riscie** [comment]
This one is old, i know, but one could also use Renderer2 (https://angular.io/api/core/Renderer2) like so anywhere in the code. The renderer should return us the dom-element, as long as the element is rendered at this very moment.

(Setting focus for eg.)

**TS**


     import {Renderer2} from '@angular/core';

     constructor(renderer: Renderer2) {
     }

     getReferenceOfDOMElementAndDoSometing() {
        this.renderer.selectRootElement("#myTextArea").focus();
     }

**HTML**

    <textarea id="myTextArea" *ngIf="someCondition"></textarea>

**Comment by moxival** [comment]
Can you guys at least **FIX** the documentation, because now it is so misleading it makes me cry!

https://angular.io/guide/template-syntax#ref-vars

> You  can refer to a template reference variable **_anywhere_** in the template. 

**NO** you cannot reference a variable **anywhere** because Angular has contexts within the contexts within......

**Comment by gangsthub** [comment]
`as`:

```
*ngIf="expression && (expression | transformExpressionFilter) as dynamicallyGeneratedExpression"
```

https://angular.io/api/common/NgIf#storing-conditional-result-in-a-variable

**Comment by ocvx** [comment]
@kub1x solution worked for me, but in the case the var is used as an input to another child you should use change detection:
``` html
<app-child1 #ch1 *ngIf="loadChild"></app-child1>
<app-child2  [brother]="ch1"> </app-child2>
```

  ``` typescript
@ViewChild('ch1') set ch(ch: Child1Component){
    this.ch1 = ch;
    this.cdRef.detectChanges(); //update child2's 'brother' input
  }
  constructor(private cdRef:ChangeDetectorRef){
    setTimeout(() => this.loadChild = true, 2000);
  }
```

[Stackblitz example](https://stackblitz.com/edit/ngif-var-template-error?file=src%2Fapp%2Fapp.component.ts)
