### ISSUE TITLE
Remove RX from webworker bundles

### ISSUE THREAD

**Issue by jteplitz602** [angular/angular#6185]
RxJs is no longer bundled with the main angular distribution, but it is still bundled in both the worker ui and worker app bundles. It shouldn't be bundled with either of these.

Additionally, I don't think users should ever need to load it on the UI.

cc @jeffbcross: AFAIK we removed rx to reduce bundle size and have kept small chunks of it inside angular but not exposed them. Is that correct?

**Comment by robwormald** [comment]
@jteplitz602 that's correct - we import rxjs/Subject and rxjs/Observable, but they aren't bundled. Subject is the base for EventEmitter which AFAIK makes up both ends of the EventBus for workers, right?

**Comment by jteplitz602** [comment]
Yeah, we use EventEmiter for the message bus on both ends. Is that the
reason we're still bundling RX?

**Comment by jeffbcross** [comment]
This is covered by #6750
