### ISSUE TITLE
Add this massive demo Angaulr 2 app to resource list

### ISSUE THREAD

**Issue by born2net** [angular/angular#6186]
Angular 2 is still young and finding examples online can be hard... So I decided to develop a "real" app... This application was developed from scratch with Angular 2 and it's awesome.

Checkout the app: http://ng2.javascriptninja.io/
checkout the source: https://github.com/born2net/ng2Boilerplate

I recommend adding to central link repository so we can begin tracking different applications and setups

Regards,

Sean - http://DigitalSignage.com

**Comment by MateuszG** [comment]
+1

**Comment by friksa** [comment]
+1

**Comment by sasxa** [comment]
Nice! Thanks for sharing.

**Comment by born2net** [comment]
sure, glad to help... I was frustrated by the lack of demos, so decided to create one myself
Regards,

Sean - http://DigitalSignage.com

**Comment by pkozlowski-opensource** [comment]
@born2net thnx for the link but for now we don't have Angular 2 samples gallery - feel free to submit your project when / if we've got one. 

BTW: I would strongly encourage you to re-consider your packaging / loading strategy as currently your app is loading un-packaged framewrok and this is slow (+3.5s for DOM content loaded and +6s to finish is a _lot_).
