### ISSUE TITLE
@RouterConfig cannot be put on any component other than the root component

### ISSUE THREAD

**Issue by pdeva** [angular/angular#6188]
Due to this one has to put their *entire* app's routing config in a single file inside a single annotation config.

This is simply not scalable for a large scale app.
Please allow putting @RouterConfig on multiple components so we can split the router config across files

**Comment by frederikschubert** [comment]
You can already do this by defining a route in your root component's `RouteConfig` like this (note the three dots in the Route's path):
```typescript
{ path: "subroute/...", component: SubRoute, name: "SubRoute" }
```
And in your SubRoute component you can then define a RouteConfig like you normally do.

**Comment by thelgevold** [comment]
Yes, this is supported in Beta.

Here is a sample:

```
//Root
@RouteConfig([
    new Route({path: '/', component: About, name: 'About', data: {project: 'angular-2-samples'}}),
    new Route({path: '/demo/...', component: DemoPage, name: 'Demo'}),
])

//Inside DemoPage
@RouteConfig([
    new Route({ path: '/spreadsheet', component: Spreadsheet, name: 'Spreadsheet' }),
    new Route({ path: '/jquery', component: JqueryIntegration, name: 'JqueryIntegration' }),
])
```

More info here: 
http://www.syntaxsuccess.com/viewarticle/routing-in-angular-2.0

Here is also a live demo of the nested routing described above:
http://www.syntaxsuccess.com/angular-2-samples/#/demo/spreadsheet

**Comment by pdeva** [comment]
@thelgevold none of the links you showed have any example of how to navigate to a link programatically, for eg, on submission of a form.
Does api for that even exist? if not, that is a huge omission

**Comment by thelgevold** [comment]
Yes you can navigate directly to a route programatically..
```
this.router.navigate(['RouteName']);
```

This assumes that you have and instance of the router

```
class SomeComponent {

    router: Router;
 
    constructor(router: Router, location: Location) {
        this.router = router;
        this.location = location;
    }
}
```

**Comment by thelgevold** [comment]
There is also ```navigateByUrl('/someUrl'))```

**Comment by pdeva** [comment]
Why does the router require a separate path and a name for every route?
The react router 2.0 recently dropped this in favor of just having a path only.

I dont see what is the use case for having separate path and 'name' per route.

**Comment by pdeva** [comment]
@thelgevold ok this is very weird with subroutes. In the example you gave:

```
//Root
@RouteConfig([
    new Route({path: '/', component: About, name: 'About', data: {project: 'angular-2-samples'}}),
    new Route({path: '/demo/...', component: DemoPage, name: 'Demo'}),
])

//Inside DemoPage
@RouteConfig([
    new Route({ path: '/spreadsheet', component: Spreadsheet, name: 'Spreadsheet' }),
    new Route({ path: '/jquery', component: JqueryIntegration, name: 'JqueryIntegration' }),
])
```

I cannot have a link that points to `/Demo`. 

I can only have a link that points to `/Demo/Spreadsheet` or `/Demo/JqueryIntegration`.

What if i just want to display the `DemoPage` component?

**Comment by ericmartinezr** [comment]
@pdeva you can't. You must use `useAsDefault: true` in one of the children routes, or specify one when using routerLink

```
@RoteConfig([
   // Now everytime you write `Demo` it will redirect automatically to `SpreadSheet`
    new Route({ path: '/spreadsheet', component: Spreadsheet, name: 'Spreadsheet', useAsDefault: true}),
    new Route({ path: '/jquery', component: JqueryIntegration, name: 'JqueryIntegration' }),
])

// Or...
<a [routerLink]="['/Demo', 'SpreadSheet']">...
```

**Comment by pdeva** [comment]
well then what if u have say a (very common) ui master-> detail-> detail ui.
Say i select element 'x' in a list A. that pops up a detail view with another list B. 
Now i select element 'y' in list B that pops up another detail view W.

According to above router rules, I can never create a route to just list B, since I have to give it the route to the very leaf component.

**Comment by pdeva** [comment]
seems like this a huge flaw in angular router that prevents having more than 1 level of nesting.

Linking to bug #6204 created specifically for this.

**Comment by brandonroberts** [comment]
Here is an example of multi-level routes: http://plnkr.co/edit/v1Np3niVn3WNTZBvHQLf?p=preview

**Comment by pdeva** [comment]
that is a 1 level route.
/user has 2 routes on the same level: 'stats' and 'profile'
try 3 level deep nesting and navigating to just the 2nd level without rendering level 3. not possible

**Comment by thelgevold** [comment]
If you want the flexibility to render the page with or without the detail view, I think an optional route param is a perhaps a workable solution. If the param is not passed you can conditionally omit the detail view.

**Comment by wardbell** [comment]
@pdeva -  Please read the entire [router document](https://angular.io/docs/ts/latest/guide/router.html) and explore its [sample](https://angular.io/resources/live-examples/router/ts/plnkr.html) which I believe covers everything you say you want to do. After that, if you can be specific about what is missing, maybe I can help.

**Comment by pdeva** [comment]
@wardbell sample code has same issue as i described. comments [here](https://github.com/angular/angular/issues/6204#issuecomment-168549051)

**Comment by vicb** [comment]
This router is deprecated
