### ISSUE TITLE
enableProdMode console message is too mysterious

### ISSUE THREAD

**Issue by ewinslow** [angular/angular#6189]
I got this message in the console:

```
Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
```

Curious, I behaved literally and typed this into the console:

```
enableProdMode();
```

At which point I was greeted with this error:

```
VM1256:2 Uncaught ReferenceError: enableProdMode is not defined(…)(anonymous function) @ VM1256:2
InjectedScript._evaluateOn @ VM1126:875
InjectedScript._evaluateAndWrap @ VM1126:808
InjectedScript.evaluate @ VM1126:664
```

This console message should link to docs explaining what enableProdMode is and an example of how exactly to enable it. For example, something like this would have been much clearer (not sure if this is how you do it exactly):

```
import {enableProdMode} from "angular2/core";

enableProdMode();
```

**Comment by kasperpeulen** [comment]
I couldn't get enableProdMode to work in Dart either.

**Comment by powercoder23** [comment]
Guys just write this code on the bootstraped Component and make sure it is not inside any class or constructor just one below the other, it worked for me.!

```` Typescript
//.. other imports
import {enableProdMode} from 'angular2/core';
enableProdMode();

@Component({
//...my component code goes here
````

hope this helps!

**Comment by vishal123** [comment]
It also works when done on the boot.ts file.
Mine now looks like this:
```typescript
import {bootstrap}    from 'angular2/platform/browser'
import {AppComponent} from './app.component'
import {enableProdMode} from 'angular2/core';

enableProdMode();
bootstrap(AppComponent);
```

But now instead of 
`Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.`
i'm getting `Angular 2 is running in the production mode. Call enableDevMode() to enable the development mode.`

Surely in a production mode there shouldn't be any messages, specifically given that one has to write code to enable production mode.

**Comment by lordmat0** [comment]
I think the point @ewinslow is trying to make is that it's not clear exactly how to do this and it should link to some docs explaining how and why this is necessary.

**Comment by jasonslyvia** [comment]
There is even no docs about what `enableProdMode()` does.

**Comment by PascalPrecht** [comment]
@vishal123 In the latest beta, you should be able to mute the message for production.

@jasonslyvia Prodmode makes sure that change detection is run only once per browser event, so you won't have cycles.

In Devmode (which is the default) CD is performed twice to double check that you haven't written code with any side effects.

**Comment by Ghayyas** [comment]
Try This..
import {enableProdMode} from 'angular2/core';

enableProdMode();

**Comment by unseen1980** [comment]
@PascalPrecht Thanks for the explanation. Where can we find some for info about the change detection?

**Comment by alyn000r** [comment]
with the latest Beta you can try this

@App({
  templateUrl: 'build/app.html',
  prodMode: true,
  config: {}// http://ionicframework.com/docs/v2/api/config/Config/
})

**Comment by pitops** [comment]
@vishal123 doing it this way i do not get any messages in console.

So this is what works for me

in **boot.ts**

```import {enableProdMode} from 'angular2/core';

enableProdMode();
bootstrap(AppComponent);
```

**Comment by vishal123** [comment]
@pitops yup, the log was muted in beta 6. #6873

**Comment by Petrus1987** [comment]
This work massively thanx

**Comment by adampasz** [comment]
I agree current message is too mysterious. Worse yet, the API docs. don't provide an example.  I had to go to a stackoverflow article to figure out what to do.  

Almost every new ng2 developer is going to see this message!

**Comment by vlazar** [comment]
There is no message in production mode anymore. See https://github.com/angular/angular/issues/6096#issuecomment-223739298

**Comment by meffect** [comment]
import {enableProdMode} from '@angular/core';
    enableProdMode();

**Comment by vicb** [comment]
This is now documented on the docs site (angular.io)

If the documentation is not enough, please open an issue on the docs repo (angular/angular.io). Thanks.

**Comment by omouse** [comment]
error message should state which module to import the function from, it's ridiculous not to see that on the development console.

**Comment by karthikeyand08** [comment]
how to enable the production mode for JS based angular2?
I guess
import {enableProdMode} from 'angular2/core';
enableProdMode();
this is for typescript base angular2, right?
correct me if im wrong,

**Comment by DzmitryShylovich** [comment]
```
import {enableProdMode} from '@angular/core';
enableProdMode();
```

**Comment by russelltrafford** [comment]
Update: The documentation currently recommends the following:

```
import { enableProdMode } from '@angular/core';

// Enable production mode unless running locally
if (!/localhost/.test(document.location.host)) {
  enableProdMode();
}
```

See: https://angular.io/docs/ts/latest/guide/deployment.html#!#enable-prod-mode

**Comment by redfox05** [comment]
Update: The documentation currently recommends the following:

```
import { enableProdMode } from '@angular/core';

// Enable production mode unless running locally
if (!/localhost/.test(document.location.host)) {
  enableProdMode();
}
```

See: https://angular.io/docs/ts/latest/guide/deployment.html#!#enable-prod-mode

**Comment by addyosmani** [comment]
Ran into this today while building an Angular app :/ 

@IgorMinar It's unclear to me why https://angular.io/docs/ts/latest/guide/deployment.html#!#enable-prod-mode isn't enabled by default to ameliorate people not shipping dev mode to production by default. 

The current console logging given to users also doesn't link up to the above doc with the fix. Can we do better? :)

Also see: https://github.com/facebook/react/issues/8784, https://github.com/glimmerjs/glimmer-blueprint/issues/12 etc where we're running into similar issues across the rest of the ecosystem.

**Comment by KSuttle-cng** [comment]
There are also no docs describing how to do anything outside of `prodMode` if it returns false (show debug info, change templates, etc). That's quite frustrating.

**Comment by kapil0712** [comment]
oprating system - windows10

npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\Kapil\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Kapil\package.json'
npm WARN @schematics/schematics@0.0.11 requires a peer of @angular-devkit/core@0.0.22 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.0.0 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.0.0 requires a peer of popper.js@^1.12.9 but none is installed. You must install peer dependencies yourself.
npm WARN Kapil No description
npm WARN Kapil No repository field.
npm WARN Kapil No README data
npm WARN Kapil No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

up to date in 22.09s

**Comment by saraa1986** [comment]
I dont have boot.ts!!!
where do you import this:
import {enableProdMode} from '@angular/core';
enableProdMode();

**Comment by jigneshchudasama** [comment]
`enableProdMode()` is still executing `debugger` statement, can anyone please tell me how to disallow or disable the `debugger` statement in production mode.

Thanks

**Comment by ishan123456789** [comment]
You can call enable prod in main.ts or app.module.ts
