### ISSUE TITLE
Angular2 is suitable for SPA?

### ISSUE THREAD

**Issue by mikeandersun** [angular/angular#6197]
Happy new year all,
I try Angular2 a bit and i needs the following features that not exist :
1- Interacting with html tags that exist in `index.html`. Sometime  we needs to attach behavior to `index.html` like what we can do with JQuery.
2-Having more that one component(only root component) to the `index.html`. Sometime we need to render a page from server with a data model (e.g with Asp.net MVC) and interact with user by javascript from client. For example we need to have two components on `inex.html' one for `Rate it` and another for `Add to favorites' in to section of the `index.html`.

**Comment by zoechi** [comment]
You already asked that on StackOverflow. GitHub issues are for bugs and feature requests. I think Gitter and Angular Google groups are a better place for your question.

**Comment by mikeandersun** [comment]
Thanks I will go to there.
