### ISSUE TITLE
Should we camelCase ng-content?

### ISSUE THREAD

**Issue by krimple** [angular/angular#6199]
Since we're moving from kabob case for attribute-based directives, should we also change ng-content to ngContent? This tripped me up today when writing a bootstrap wrapper library.  The directives still use ng-content in beta 0.

**Comment by GaloisGirl** [comment]
Duplicate of #6308

**Comment by pkozlowski-opensource** [comment]
Nope. We want to keep tag names close to the web components specification which mandates `-` for custom component names.

**Comment by krimple** [comment]
Gotcha, so it's just attribute names.
