### ISSUE TITLE
Async validators and promise

### ISSUE THREAD

**Issue by DrBrooklyn** [angular/angular#6200]
Hello,

When i write a simple async validator: (taken from another issue)
```
//Validator
function test2(control) {
    return new Promise((resolve)=>{
        setTimeout(()=>{
            resolve(null);
        },1000);
    });
}
//...add with
this.username = fb.control("", Validators.compose([
    Validators.required, 
    Validators.minLength(4),
]), test2);
```
Angular throw an error: "Uncaught (in promise) TypeError: _this.subscribe is not a function(…)"

I Use angular 2.0 alpha and meteor-angular package. Sorry for my really bad english.

Thank you.

**Comment by ericmartinezr** [comment]
@DrBrooklyn it's impossible to say without a repro. Can you make a plnkr?

**Comment by DrBrooklyn** [comment]
Hi!

I can't make a plunker (dont found meteor on plunker), but I give you a live demo with sources.
Link:  http://async-validator-angular2.meteor.com/
Sources:
```
//app.ts
/// <reference path="../typings/angular2-meteor.d.ts" />

import {Component, View} from 'angular2/core';
//import {bootstrap} from 'angular2/bootstrap';
import {FORM_DIRECTIVES, NgIf,
    FormBuilder, ControlGroup, Validators, AbstractControl} from 'angular2/common';
    
import {MeteorComponent, bootstrap} from 'angular2-meteor';

function test2(control) {
    return new Promise((resolve)=>{
        setTimeout(()=>{
            resolve(null);
        },1000);
    });
}

@Component({
    selector: 'my-app'
})
@View({
    template: `
    <form [ngFormModel]="formGroup" novalidate>  
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" id="username" name="username" 
                [ngFormControl]="formGroup.controls['username']"/>
            {{ username.errors | json}}
        </div>
    </form>
    `
})
class MyApp extends MeteorComponent {
    formGroup;
    
    username;
    
    constructor(fb: FormBuilder) {
        super();
        
        this.username = fb.control("", Validators.required, test2);
        
        this.formGroup = fb.group({
            "username": this.username
        });
    }
}

bootstrap(MyApp);
//index.html
<body>
    <my-app></my-app>
</body>
```

Thank you!

**Comment by PascalPrecht** [comment]
@Drbrooklyn can you please check with latest beta and tell if this is still an issue?

**Comment by Drol** [comment]
[Plunker](http://plnkr.co/edit/CoRNcpslh2Ej5GmfJue3?p=preview)

When I use Validators.composeAsync() it throws the same error, "Error: Uncaught (in promise): TypeError: _this.subscribe is not a function".

When I use Validators.compose() it throws no error. The custom validator is executed and the promise seems to be resolved. But validity of the control never changes.

There might be usererrors on my side. In that case I apologize.

**Comment by balteo** [comment]
@ericmartinezr @PascalPrecht 

Here is a plunker demonstrating the issue: http://plnkr.co/edit/Pp5PTGVp2LAaORWVYaT1?p=preview

Have a look into `app/question-control.service.ts`

There are two async validators there: on based upon promises (see `myPromiseBasedAsyncValidator`) and another based upon observables (see `myObservableBasedAsyncValidator`).

By uncommenting one and commenting out the other, one can see that promise based async validators work as expected whereas observable based async validators throw the following TypeError:` _this.subscribe is not a function`

**Comment by vicb** [comment]
Please create a new issue if this is still a pb with Angular 2.0.1. Thanks.
