### ISSUE TITLE
Router: HashLocationStrategy must follow RouteProviders; order shouldn't matter

### ISSUE THREAD

**Issue by wardbell** [angular/angular#6201]
Reported in [angular.io issue #626](https://github.com/angular/angular.io/issues/626). 

Quote:
--
When I followed the documentation here: https://angular.io/docs/ts/latest/guide/router.html#!#browser-url-styles  for setting up a HashLocationStrategy it didn't work.

```
bootstrap(AppComponent, [

  provide(LocationStrategy,
       {useClass: HashLocationStrategy}),  // ~/src/#/crisis-center/
  ROUTER_PROVIDERS
]);
```

If I switch the bootstrap provider list order around to put the HashLocationStrategy second in the list, then everything seems to work.

```
bootstrap(AppComponent, [
  ROUTER_PROVIDERS,
  provide(LocationStrategy,
       {useClass: HashLocationStrategy}) // ~/src/#/crisis-center/
]);
```
--
I have am updating the documentation as he suggests. Note that I hadn't tested my original.

**Comment by PascalPrecht** [comment]
Not sure if we can fix this. If the order shouldn't matter, how should Angular know, which provider wins?

I think we just have to make clear in the docs, that `ROUTER_PROVIDERS` already comes with a provider for `LocationStrategy` and that one has to append to the providers list in order to override.

**Comment by wardbell** [comment]
Excellent point. It is an **override** (which I forgot) and of course it must come second.

I should have thought of that. Pretty obvious now that you point it out.

Closing.
