### ISSUE TITLE
Styling the :host with 

### ISSUE THREAD

**Issue by kasperpeulen** [angular/angular#6202]
I have the following component:
```
@Component(
    selector: 'login',
    templateUrl: 'login.component.html',
    directives: const [CORE_DIRECTIVES, FORM_DIRECTIVES, DROPDOWN_DIRECTIVES],
    styleUrls: const ['login.component.css'],
    encapsulation: ViewEncapsulation.None
    )
```

With the following style:
```
:host {
  position: fixed;
  display: block;
  right: 10px;
  top: 10px;
  z-index: 1;
}
```

I assumed that this would turn into a global css  style like:
```
login {
  position: fixed;
  display: block;
  right: 10px;
  top: 10px;
  z-index: 1;
}
```

But it is actually puts this `.host` selector as global style:
![image](https://cloud.githubusercontent.com/assets/1035299/12069136/f350e6fe-b020-11e5-9fa2-e3d95c2c1fde.png)

I'm not sure what the expected behaviour would be here, but I think this makes not much sense.

**Comment by ericmartinezr** [comment]
I think you need to read this [article](http://www.html5rocks.com/en/tutorials/webcomponents/shadowdom-201)

**Comment by kasperpeulen** [comment]
@ericmartinezr I know shadow dom etc. Maybe it doesn't make much sense, but maybe then raising an exception would be better? 

I do think it would make more sense to convert `:host` to the actual component name, if used in combination with `ViewEncapsulation.None`. After thinking about it, I also could have just written 

```
login {
  position: fixed;
  display: block;
  right: 10px;
  top: 10px;
  z-index: 1;
}
``` 

in the stylesheet in the first place. I forgot that this is just possible. Still I feel like it would be better to at least raise an exception, if people use `:host` in combination with `ViewEncapsulation.None`.

**Comment by ericmartinezr** [comment]
Yep, sorry, after a while I got the point here. I don't know if an exception would be good a idea, I mean, if I make a mistake in my CSS nothing really happens, it just doesn't work. Probably changing it to what you expect (changing `:host` to `.selector` or `.selector-host` so the user can see that it's mixing VE.None and `:host`) would make more sense. I'm really sorry for the noise...

**Comment by vicb** [comment]
`ViewEncapsulation.None` basically tells to include your unmodified CSS.

Because we don't follow includes in this case, there is no way we can catch errors
