### ISSUE TITLE
Router typings not resolving in 2.0.0-beta.0 npm package

### ISSUE THREAD

**Issue by aaronroberson** [angular/angular#6203]
When importing any symbols from `angular2/router` I get an error saying the symbol cannot be resolved. To fix this, I have to explicitly add the file to tsconfig.json as such:

`"files":["node_modules/angular2/router.d.ts"]`

This resolves most of the errors. I believe this may be due to the fact that there is an `angular2/router/` directory with type definitions that may be colliding.

The only other issue I'm having is that the `ROUTER_PROVIDERS` symbol still can't be resolved. Most likely due to the use of `CONST_EXPR`. I can use `ROUTER_BINDINGS` instead but have noted that it is marked as deprecated.

**Comment by zoechi** [comment]
I guess `ROUTE_PROVIDERS` contains the default `PathLocationStrategy`, if you want to override the default it must be passed afterwards.

**Comment by robwormald** [comment]
I can't reproduce this at all locally. What version of typescript are you using? Do you have "moduleResolution" : "node" set? Is this using `tsc` or in an editor?

**Comment by aaronroberson** [comment]
The errors are in Webstorm but appear to be acting as warning since
everything compiles. But that is also true if you omit typings altogether
so I don't think that it is completely a non-issue. This is also true for
the HTTP_PROVIDERS as well.

I created a repo here:

https://github.com/aaronroberson/angular2-tour-of-heroes-extended.

I'm using TypeScript 1.5.0-beta and am using the cli to build and transpile.

**Comment by alexeagle** [comment]
typescript 1.5 is too old, it doesn't include `moduleResolution=node` which is required to type-check against angular (at least until we have https://github.com/angular/angular/issues/5796)
