### ISSUE TITLE
Apparent bug with a href links reloading app

### ISSUE THREAD

**Issue by qdouble** [angular/angular#6212]
Not sure if this is a bug or just a design issue, but when going to an href link, the app seems to reload. While I know you can use the routerLink directive, it's not very always simple to do with dynamic links received from a server. On my computer the app reloads, but in this plunker it goes to a 404 page, probably because plunker doesn't properly process the app reload: https://plnkr.co/edit/mX5lyAu3YsQZzBqMl9k9?p=preview

**Comment by vsavkin** [comment]
I don't think the issue makes sense in the context of the new router (@angular/router). If you think it does, please reopen it with the plunkr reproducing the issue.
