### ISSUE TITLE
Add support for const bindings

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#622]
I think in addition to bindings a directive should be able to get a list of static values and those should be injectable into the constructor. 

```
@Decorator({
	selector: '[control]'
})
class Control {
	constructor(@Static('type') type:string){}
}
```

There are few reasons why it might be a good idea.

1. It is explicit. Certain properties are meant to be static. So defining them as bindings forces you to implement setters and throw if someone tries to rebind them. Semantically such properties are not bindings but rather  the directive configuration.
2. It allows to write directives that do some init work in the constructor. Right now you have to delay it until the first onChange.
3. The lack of such properties cripples the forms API.

Consider:
```
<div #form [new-control-group]="init">
  {{form.value}}
  {{form.valid}}
  <input type="text" control="name" required>
</div>
```

In this example the form is being constructed in the html. We can construct it only after the `control="name"` binding fires. The example above will not work because both value and valid will be modified by the binding that comes next.

If we had static properties, we could construct the form before the change detection kicks in (during hydration) and then the example would work.

## Closed issue #688 text
It would be very useful to read a components static attributes (not bindings). This is probably a prerequisite for to #633. There are many use-cases for this.

#### Example use case: imitating native input api
Standard radio buttons are put into one single-input-can-be-checked group with the name attribute:
```html
<label>
  <input type="radio" name="instrument">
  Guitar
</label>
<!-- some arbitrary html -->
<label>
  <input type="radio" name="instrument">
  Trombone
</label>
```
If a component author wants to support the same api on a custom radio button, the author needs to be able to read the name attribute. There's usually not a need, though, to create a binding on the property.

## Closed issue #633 text

There should be a way, from a Component, to check whether some attributes were provided. For example, if the end user has:
```html
<!-- Attribute specified with no value. -->
<scary-button no-scream>Boo!</scary-button>

<!-- Attribute not specified -->
<scary-button>Ahh!</scary-button>
```
The Component should be able to know the difference between an attribute being present and empty (top example) vs. an attribute being absent (bottom example). 

-------------------------------------

@jelbourn wouldn't proposal from #622 sufficient to cover your use-case? With that proposal one could do:

```javascript
ComponentDecorator({
    selector: 'scary-button'
})
class ScaryButton {
    constructor(@Static('no-scream') noScream:string){
        //noScream gets null when an attribute is not present here
    }
}
```

**Comment by mhevery** [comment]
Injection values:

`<input>` -> `@Static('type')` -> `null`
`<input type>` -> `@Static('type')` -> `""` (Empty string)
`<input type=text>` -> `@Static('type')` -> `"text"`

**Comment by mlaval** [comment]
After a discussion with @vsavkin , the intent here is to access the static attributes which were in the template. In fact, this already doable by injecting `NgElement`, which is going to be replaced very soon by some `BoundElementId`.

So this raises some questions for @mhevery :
-  Do we need this @Static if we have `BoundElementId`?
- If yes, is `Static` the appropriate name for this annotation?

**Comment by mhevery** [comment]
@mlaval I think `BoundElementId` will be async, where as `Static` can be resolved at compile time and hence be faster. It also makes it clear that you can not change the binding.

Proposed syntax:

```
class SomeClass {
  constructor(@Attribute('type') type:string) {}
}
```

1. we know that it always have to be a string (or `null` if no attribute found). 
2. it can be computed during the compilation phase and be part of the `ElementInjector`
