### ISSUE TITLE
Conflict with Prototype.js

### ISSUE THREAD

**Issue by arvind07** [angular/angular#6221]
I tried integrating angular 2 with Magento framework which uses Prototype as its main JS framework.
But angular 2 does no run on it. Even if you include prototype.js in any simple angular app, it will break.

I have created a plunker: http://plnkr.co/edit/XKKpriTPrTX3tXqqz8v2?p=preview

Error: No provider for ExceptionHandler!

**Comment by nikolafon** [comment]
This is a show stopper for me. I'm migrating Richfaces, which apparently is using Prototype.js, to the Angular 2 and for the time being I have to run it side by side. Angular 2 is crashing with this error when trying to bootstrap.

**Comment by nikolafon** [comment]
Prototype overrides behaviour of Array.from function. It might be prototype issue not Angular.
If you change prototype library (comment Array.from = $A; line) Angular works just fine.
Angular can't control what other shim libraries you use and you can brake a lot of stuff if you alter standard javascript functions.

**Comment by gdi2290** [comment]
http://plnkr.co/edit/MsremsQm69Qu1OdFEVjR?p=preview

**Comment by arvind07** [comment]
@gdi2290 Its awesome. Thanks a ton for your help :+1:
