### ISSUE TITLE
router outlet being appended to <undefined>

### ISSUE THREAD

**Issue by j3ddesign** [angular/angular#6222]
I've just started playing with secure routes and while I'm pretty sure it's just an out of date code issue I thought I'd raise it here. (I got the code for securing the route from https://github.com/auth0/angular2-authentication-sample)

I've used the following code to secure my routes (redirect to login if not logged in)
```
import {Directive, Attribute, ElementRef, DynamicComponentLoader} from 'angular2/core';
import {RouterOutlet, Router, ComponentInstruction} from 'angular2/router'

import {LoginComponent} from "../views/login/login.component";

@Directive({selector: 'router-outlet'})

export class SecureOutlet extends RouterOutlet {
    publicRoutes:any;
    private parentRouter:Router;

    constructor(_elementRef:ElementRef,  _loader:DynamicComponentLoader,  _parentRouter:Router,  @Attribute('name') nameAttr:String) {

        super(_elementRef, _loader, _parentRouter, nameAttr);
        this.parentRouter = _parentRouter;
        this.publicRoutes = {
            '/login':true
        }
    }

    activate(instruction: ComponentInstruction) {
        var url = this.parentRouter.lastNavigationAttempt;
        if (!this.publicRoutes[url] && !localStorage.getItem('jwt')) {
            //todo: redirect to Login, may be theres a better way?
            this.parentRouter.navigateByUrl('/login');
        }
        return super.activate(instruction);
    }
}
```

And here is my app.component.ts
```
import {Component, View} from 'angular2/core';
import {Location, RouteConfig, RouterLink, Router} from 'angular2/router';

import {DashboardComponent} from './views/dash/dashboard.component';
import {AdminComponent} from './views/admin/admin.component';
import {SettingsComponent} from './views/settings/settings.component';
import {FileBrowserComponent} from './views/filebrowser/files.component';
import {LoginComponent} from './views/login/login.component';
import {UserService} from "./Components/user.service";
import {SecureOutlet} from "./Components/secure.routeroutlet";

@Component({
    selector: 'shape-site'
})
@View({
    directives: [SecureOutlet],
    template: `<router-outlet></router-outlet>`
})
@RouteConfig([
    {path: '/', redirectTo: ['Dashboard']},
    {path: '/dashboard',        name: 'Dashboard',    component: DashboardComponent},
    {path: '/settings',         name: 'Settings',     component: SettingsComponent},
    {path: '/dashboard/admin',  name: 'Admin',        component: AdminComponent},
    {path: '/files',            name: 'FileBrowser',  component: FileBrowserComponent},
    {path: '/login',            name: 'Login',        component: LoginComponent}
])
export class AppComponent {
    constructor(public router:Router) {}
}
```

However while this all seems to work (Navigating to /dashboard will redirect to /login) The actual DOM is put in an `<undefined></undefined>` element instead of withing the `<router-outlet>`
Giving me the following
```
<shape-site>
    <router-outlet></router-outlet>
    <undefined>
        <h1>Login...</h1>
    </undefined>
</shape-site>
```

**Comment by ericmartinezr** [comment]
That's by design (there's an old issue that I remember of but can't find it). In your components loaded by routing you can skip the selector, in that case it's shown as `<undefined>`, if you want to avoid that simply specify a selector in your components. Check this [answer](http://stackoverflow.com/questions/34331358/undefined-html-tag-getting-generated-in-angular2-beta-0-app/34332772).

**Comment by j3ddesign** [comment]
@ericmartinezr ahh ok thats great, thank you! Not sure how I missed that question whilst searching for an answer :+1:

**Comment by mswehli** [comment]
Just to get some clarification since i'm experiencing the same issue.
So the issue is that angular2's router doesn't actually use the <router-outlet> element for the output of the routed component but instead adds a new element right after it. But you guys are all saying thats actually part of the design? And the selector is only used to set the name of the new element it is going to create, but the router-outlet element will never be used? Seems a bit flawed to me no? Would be much neater and more expected if it put the component inside the router-outlet element.

**Comment by xealot** [comment]
@mswehli I'm running into an issue right now where I'm using `router-outlet` inside of a `display: flex` component and the directive takes up a huge amount of space because it's flexed in with the rest of the content even though it's not really used. 

Sort of surprising and weird.

**Comment by mswehli** [comment]
@xealot Yeah, I'm also using it in flex, I changed the router-outlet css so its flex property is 0 0 0 (as I believe flex:none sets it to 0 0 auto), position to absolute, left to -1000, height and width to 0 and display to none, so its only used to mark the location in the html. However I haven't fully experimented with it to see what the effect will be if I change the justify to space-around or space-between as it might affect the location of the different children even though its not visible.

Based on reading the documentation however, there are some places where it mentions that the router will actually place the routed component into the router-outlet element, and some places where it says it will place the router-component immediately after router-outlet, so i'm worried it might change in the future and would have to do some minor rewrites to make sure it continues to work properly if its updated to a new version of angular2

**Comment by xealot** [comment]
My solution was to just nest the `router-component` in another element so it's insulated from this behavior for now. I wish I knew what the rules were regarding this.

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20781495/3686f5d0-b7be-11e6-9b51-c3ca1ca44c8a.png)
![Uploading 图片.png…]()
