### ISSUE TITLE
DynamicComponentLoader breaks Data binding

### ISSUE THREAD

**Issue by SuperManitu** [angular/angular#6223]
When you add a component via DynamicComponentLoader.loadAsRoot, you can't use data binding in your loaded component template.
Plunker: http://plnkr.co/edit/yzKAiXQQQwKi88g6wIdY?p=preview

**Comment by vintage** [comment]
Same here. A simple workaround for this issue in my app was to use `loadIntoLocation` instead of `loadAsRoot` which work like a charm.

**Comment by SuperManitu** [comment]
Yeah, I can confirm that loadIntoLocation is working as expected

**Comment by ericmartinezr** [comment]
Related to https://github.com/angular/angular/issues/3474 if not a dup.

**Comment by oliverjanik** [comment]
How can I use loadIntoLocation  if I want to add the element to the end of the global document (i.e.) modals?

The only workaround I found with loadAsRoot is to inject ChangeDetectorRef and do:

```
        setTimeout(() => changeDetector.detectChanges(), 0);
```

**Comment by SuperManitu** [comment]
That's a solution I found online:
```typescript
import {Injectable, DynamicComponentLoader, ElementRef,
    ApplicationRef, Type} from 'angular2/core'

import {Dialog} from '../dialogs/dialog'

@Injectable()
export class DialogService
{
    private appRef : ApplicationRef;
    private componentLoader : DynamicComponentLoader;
    
    constructor(dcl: DynamicComponentLoader, appRef : ApplicationRef)
    {
        this.appRef = appRef;
        this.componentLoader = dcl;
    }
    
    public openDialog(dialog : Type) : Promise<Dialog>
    {
        let elementRef: ElementRef = this.appRef['_rootComponents'][0].location;
        return this.componentLoader.loadIntoLocation(dialog, elementRef, 'dialog')
            .then(res => {
                return (<Dialog>res.instance).initDialog(res);
            });
    }
}
```

```html
<navbar></navbar>
<header></header>
<content></content>
<div #dialog></div>
```

**Comment by oliverjanik** [comment]
This is the juicy bit:

```
let elementRef: ElementRef = this.appRef['_rootComponents'][0].location;
```

I created #6446  for this purpose.

**Comment by gdi2290** [comment]
when using `loadAsRoot` you need to trigger change detection and manually wire up Inputs and Outputs
```typescript
this.componentLoader.loadAsRoot(YourComponent, this.elementRef, this.injector)
.then((compRef: ComponentRef) => {
  // manually include Inputs
  compRef.instance['myInputValue'] = {res: 'randomDataFromParent'};
  // manually include Outputs
  compRef.instance['myOutputValue'].subscribe(this.parentObserver)
  // trigger change detection
  cmpRef.location.internalElement.parentView.changeDetector.ref.detectChanges()
  // always return in a promise
  return compRef
});
```

**Comment by ericmartinezr** [comment]
@gdi2290 finally somebody shed some light on the subject. Why is that the behavior? Personally I would expect loadAsRoot to do it automatically

**Comment by gdi2290** [comment]
`loadAsRoot` is used during bootstrap (https://github.com/angular/angular/blob/2.0.0-beta.8/modules/angular2/src/core/application_ref.ts#L50) where angular is wiring everything (di, cd etc) up and by design doesn't wire anything up that was rendered on the server. This is for security reasons. What everyone is looking for is either `loadIntoLocation` (which uses `loadNextToLocation`) or `loadNextToLocation` used by the router (https://github.com/angular/angular/blob/2.0.0-beta.8/modules/angular2/src/router/router_outlet.ts#L65)

**Comment by ericmartinezr** [comment]
@gdi2290 thanks man, I really appreciate the clarification on this subject. Thanks :+1:

**Comment by 3ehu** [comment]
@gdi2290 I want to test your solution but
on beta.9 `Property 'internalElement' does not exist on type 'ElementRef'.`

On plunker seems that working but detectChanges trigger only on component loader 
any future changes (internal or on input) are not detected. 

http://plnkr.co/edit/bZf3aj20XVjVdVjZopqN?p=preview

**Comment by gdi2290** [comment]
@3ehu because you're wiring up everything manually you also need to manage the change detector. If you want to include the component in the application then you have to inject the ApplicationRef and to inject the ApplicationRef you have to use the long version of bootstrap
http://plnkr.co/edit/lH937n?p=preview
`main.ts`
```typescript
//main entry point
import {BROWSER_PROVIDERS, BROWSER_APP_PROVIDERS} from 'angular2/platform/browser';
import {platform} from 'angular2/core';
import {App} from './app';


var platformRef = platform(BROWSER_PROVIDERS.concat([]));
var appRef = platformRef.application(BROWSER_APP_PROVIDERS.concat([]));
appRef.bootstrap(App, [])
.then((cmpRef: ComponentRef) => {
  cmpRef.instance['appRef'] = appRef;
  cmpRef.instance['platformRef'] = platformRef;
  return cmpRef;
})
  .catch(err => console.error(err));
```
`app.ts`
```typescript
//our root app component
import {ApplicationRef, Component,DynamicComponentLoader, ElementRef,Injector,ComponentRef,Input} from 'angular2/core'

import {ChangeDetectorRef} from "angular2/core";


@Component({
  selector: 'my-test',
  template: `
  My Testing component
    <div>
      Child
      <input type="number" [(ngModel)]="model.value" >
      Value: {{ model.value }}
    </div>
  `,
  directives: []
})
export class Test {
  @Input() model: number;

  constructor() {}
  
  ngOnInit() {
    console.log('onInit');
  }

}

@Component({
  selector: 'my-app',
  providers: [],
  template: `
    <div>
      <h2>Parent</h2>
      <input type="number" [(ngModel)]="parentModel.value" >
      Value: {{parentModel.value}}
      
      <div id="test"></div>
     
      <my-test [model]="parentModel"></my-test>
      
    </div>
  `,
  directives: [Test]
})
export class App implements OnInit{
  public parentModel:number;
  private appRef: ComponentRef;
  
  constructor(private loader: DynamicComponentLoader, 
  private elementRef: ElementRef, 
  private injector: Injector) {
    this.parentModel = {
      value: 100
    };
  }
  
  ngOnInit(){
    this.loader.loadAsRoot(Test, '#test', this.injector)
      .then((cmpRef: ComponentRef) =>{
        cmpRef.instance.model = this.parentModel;
        this.appRef._loadComponent(cmpRef);
        return cmpRef;
      });
  }
}
```

**Comment by ericmartinezr** [comment]
@gdi2290 if we're not supposed to use loadAsRoot wouldn't be better to move it to be private api?

**Comment by dmarginian** [comment]
@gdi2290 I am currently using loadAsRoot to dynamically load dashboard widgets.  I have to use loadAsRoot because template variables (#) cannot be named dynamically. loadIntoLocation requires an anchorName rather than a selector so it won't work.  I triggered change detection per your recommendation and that is working, however, my component doesn't seem to be working properly (not responding to model updates).

**Comment by busbina** [comment]
@gdi2290 Your solution works great. How ever when I load the component from out side of the app it will only update when the base updates. In this demo the loaded component should be updating every 500ms but it will only update ever 2 sec which is the parent's update clock. Any ideas?
http://plnkr.co/edit/lry8aLklZbGSCPBhT5PQ?p=preview

**Comment by zoechi** [comment]
@busbina When called from outside the code doesn't run in Angulars zone, hence no change detection. Force it into the zone and it works http://plnkr.co/edit/QftdX28nhDKrh9a8o5xG?p=preview

**Comment by busbina** [comment]
@zoechi Works great! Thanks for the help.

**Comment by matthewvalimaki** [comment]
Per comments `loadAsRoot` seems private. But because of https://github.com/angular/angular/issues/4581#issuecomment-148786554 it should not be private.

Perhaps new API is needed so that `loadAsRoot` can be private? In any case indefinite dynamic loading with data binding should be possible and easy.

**Comment by matthewvalimaki** [comment]
The following seems to work with beta13. As mentioned above data binding is enabled once `_loadComponent` of `ApplicationRef` with your dynamic component is called.

These are the only changes I've made, no bootstrap or app changes.
```
export class MyComponent{
    @Input() myModel: any;
}

export class MyClass {
    constructor(
        private dcl: DynamicComponentLoader,
        private injector: Injector,
        private appRef: ApplicationRef
    ) {}

    ngAfterViewInit() {       
        this.dcl.loadAsRoot(MyComponent, '#component', this.injector)
            .then(componentRef => {
                componentRef.instance.myModel = this.myModel;
                
                (<any>this.appRef)._loadComponent(componentRef);
            });
    }
}
```

**Comment by pwpatton** [comment]
I'm having problems when mapping an @Output() when using loadAsRoot. It appears the target event handler doesn't have the "this" variable mapped to it's component but is undefined when I run it locally and is Window when I run it in this plunker. What could I be doing wrong?

[https://plnkr.co/edit/zOa6qVLMafSIC1rRZI2x?p=preview](https://plnkr.co/edit/zOa6qVLMafSIC1rRZI2x?p=preview)


```
import {bootstrap} from 'angular2/platform/browser';
import {Component, ComponentRef, ApplicationRef, DynamicComponentLoader, Injector, EventEmitter, Output} from 'angular2/core'

@Component({
  selector   : 'my-app',
  template   : '<some-component (loaded)="onLoaded($event)">{{message}}</some-component>'
})
export class App
{
  private message:string;

  constructor(
    public appRef   : ApplicationRef, 
    public loader   : DynamicComponentLoader, 
    public injector : Injector) {}

  ngOnInit()
  {
    this.loader.loadAsRoot(SomeComponent, 'some-component', this.injector)
      .then((cmpRef: ComponentRef) => {
        // hookups outputs
        (<SomeComponent>cmpRef.instance).loaded.subscribe(this.onLoaded);

        //register component with appRef change detector
        (<any>this.appRef)._loadComponent(cmpRef);

        // always return from a promise
        return cmpRef;
    });
  }

  onLoaded(event)
  {
    // handle "loaded" event. Notice 'this' isn't mapped to this components instance.
    let message = "App.onLoaded: 'this' is " + this + ", expected 'this' to be mapped to App component."
    console.log(message);
    window.alert(message);

    // ISSUE: This fails due to 'this' not being mapped to the App component instance.
    //this.message = message; 
  }
}

@Component({selector:'some-component', template:''})
export class SomeComponent
{
  @Output() loaded:EventEmitter<any> = new EventEmitter();
  ngAfterViewInit() 
  {
    // emit event once this components view is initialized 
    this.loaded.emit({loaded:true}); 
  }
}

bootstrap(App, []).catch(err => console.error(err));

````

**Comment by zoechi** [comment]
@pwpatton 

you need to change this line to use arrow function otherwise this is not retained

```
...subscribe((val) => this.onLoaded(val));
```

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by pwpatton** [comment]
Thanks @zoechi, I'll take care to post these to the correct spot.

**Comment by dmarginian** [comment]
There have been some significant API changes in beta 16 and gdi2290's bootstrap recommendation from March 10th is no longer working.

**Comment by ericmartinezr** [comment]
@dmarginian don't worry about any workaround, DCL is deprecated. Use `ComponentResolver` and `ViewContainerRef` instead.

**Comment by dmarginian** [comment]
DCL is deprecated?  The 16 change log doesn't indicate that:
https://github.com/angular/angular/blob/master/CHANGELOG.md

It looks like the API has changed but it doesn't say it has been deprecated:
"DynamicComponentLoader.loadNextToLocation now takes a ViewContainerRef instead of an ElementRef."

ComponentResolver is not well documented, do you have any recommended resources or should I just search through the source?

**Comment by ericmartinezr** [comment]
@dmarginian it will be deprecated, see https://github.com/angular/angular/commit/5297c9d9ccc6f8831d1656915e3d78e767022517

Here's a plnkr with the usage of those I mentioned earlier http://plnkr.co/edit/lxqPxFCa7gNlsRZfxI8E?p=info

**Comment by lroitman** [comment]
Wow. 
Will DynamicComponentLoader.loadAsRoot functionality be possible to implement with ComponentResolver and ViewContainerRef? I used to inject a component dynamically at the location specified by a selector like this:

`loader.loadAsRoot(MyComponent, ".my-location", ...)`

 will I still be able to accomplish the same?

**Comment by busbina** [comment]
Is there anyway to do this without the ViewContainerRef? I tried it and it will render basic HTML but seems to stop without error when I give it template bindings. I cant use anchors because I have HTML DOM elements being created dynamically outside of ng2 that I need to inject a component into. The component object is getting created just no rendering.

http://plnkr.co/edit/8o9dAcOQ4LTYa4Oms5wE?p=preview

**Comment by fletchsod-developer** [comment]
When will DCL (LoadAsRoot, LoadIntoLocation & LoadNextTo Location) be
removed from Angular?

**Comment by busbina** [comment]
@lroitman got it working.
Check out the plnkr.
http://plnkr.co/edit/8o9dAcOQ4LTYa4Oms5wE?p=preview

**Comment by lroitman** [comment]
Thanks @busbina ! will try the same...

**Comment by mbalex99** [comment]
@busbina love the plnkr but I see a cast to the app ref and a zone.js run block in the app constructor. Are these recommended APIs? They looks suspiciously private.

**Comment by lroitman** [comment]
@busbina , I was able to modify the solution provided by @gdi2290 earlier on Mar 8 with manually wiring inputs and change detection:

```
        this._componentResolver.resolveComponent(MyComponent).then((factory) => {
            factory.selector = '.test';
            var componentRef = factory.create(this._injector, null,'.test');
            componentRef.instance._myContext = context;
            componentRef.changeDetectorRef.detectChanges();
            componentRef.onDestroy(()=>{
                componentRef.changeDetectorRef.detach();
            })
            return componentRef;
        });

```
The only thing that bothers me is a possible memory leak. When I load component into a '.test' several times in a row, who destroys the one that was created earlier?

**Comment by zoechi** [comment]
@lroitman I think you need to destroy it yourself. Store the `componentRef` and call `destroy()` on the old instance before you create a new one.

**Comment by lroitman** [comment]
@zoechi Thanks a lot! Makes total sense.

The only catch is that once the `componentRef` is destroyed it also removes the selector, so next time I try to load to the same location I get an exception.

As a workaround I collect all the components I created and destroy them all once I am done with loading. But I thought I'd mention the pitfall.

**Comment by zoechi** [comment]
@lroitman I guess that is only an issue with `loadAsRoot()` or `loadIntoLocation()` (removed in beta.17) but not with `loadNextToLocation()`

**Comment by lroitman** [comment]
@zoechi Thanks again! I'll play around with `loadNextToLocation()` implementation.

**Comment by dqweek** [comment]
full solution for TypeScript users:

```
@Injectable()
export class DynamicComponentLoaderFix extends DynamicComponentLoader {
    constructor(private _loader: DynamicComponentLoader, private _app: ApplicationRef) {
        super();
    }

    loadAsRoot(type: Type, overrideSelectorOrNode: string | any, injector: Injector,
        onDispose?: () => void,
        projectableNodes?: any[][]): Promise<ComponentRef> {

        return this.loadAsRoot(type, overrideSelectorOrNode, injector, onDispose, projectableNodes)
            .then(component => {

                (<any>this._app)._loadComponent(component);

                component.onDestroy(() => {
                     (<any>this._app)._unloadComponent(component);
                });

                return component;

            });

    }
 
    loadNextToLocation(type: Type, location: ViewContainerRef,
        providers?: ResolvedReflectiveProvider[],
        projectableNodes?: any[][]): Promise<ComponentRef> {

        return this._loader.loadNextToLocation(type, location, providers, projectableNodes);
    }

}

```

**Comment by frantisekjandos** [comment]
@dqweek Thank you for the workaround, works like a charm ;) but with little fix of return this.loadAsRoot(.. should be this._loader.loadAsRoot(..

**Comment by dqweek** [comment]
Tanks you for noticing @frantisekjandos.
fixed.

**Comment by joebrassi** [comment]
@dqweek Your workaround works to place bindings again, but the lifecycle events (OnInit, OnDestroy, etc) are still not working, any idea why?

**Comment by ericmartinezr** [comment]
@joebrassi it won't be accepted, DCL is deprecated. Also consider that loadAsRoot was never broken, it was its behavior by design, instead of wiring up everything yourself manually you could use loadNextToLocation that does everything for you, but again, there's no point anymore. Move away from DCL to use ViewContainerRef and ComponentResolver.

**Comment by joebrassi** [comment]
@dqweek Wow! That's quite a revelation, and why is this issue still open then? This should be closed and point the functionality to the new `ViewContainerRef` and `ComponentResolver`, it would save a lot of time to people still struggling with `DynamicLoadComponent`. And the Angular official page still does not say anything about `DynamicLoadComponent`.

Anyways, thanks for the info, I'll investigate further that method and update my app as needed

**Comment by dqweek** [comment]
@joebrassi you are right that DCL is deprecated. however it doesn't mater cause behind the scene the loadAsRoot is using ComponentResolver and ViewContainerRef accordingly.

taken from @angular\core\src\linker\dynamic_component_loader.ts
```
loadAsRoot(type: Type, overrideSelectorOrNode: string | any, injector: Injector,
             onDispose?: () => void, projectableNodes?: any[][]): Promise<ComponentRef<any>> {
    return this._compiler.resolveComponent(type).then(componentFactory => {
      var componentRef = componentFactory.create(
          injector, projectableNodes,
          isPresent(overrideSelectorOrNode) ? overrideSelectorOrNode : componentFactory.selector);
      if (isPresent(onDispose)) {
        componentRef.onDestroy(onDispose);
      }
      return componentRef;
    });
  }
```

so your suggestion to use ComponentResolver only, will not work, cause it has the same issue.
I have created DynamicComponentLoaderFix to overcome this limitation, the internal implementation can easily be replaced by ComponenetResolver, only to not use deprecated angular classes.

I should mention, that loadNextToLocation method that is working perfectly, is not suitable for every scenario, especially it can't be used in case were you want to load a component into a place which is outside of angular zone/application. 

for example in my use case, I'm using 3rd party widgets that are not angular 2 native (not much products out there right now that are native). and one of which is a window popup, that when opened creates a popup element which is outside of angular scope attached directly to the body. I needed a way to inject a component as this window content. before beta.16 I was using ApplicationRef.bootstrap method, it was an acceptable solution, especially that the real difference between loadAsRoot and bootstrap is exactly that, lifecycle hooks are working cause (ChangeDetectorRef registered as root ChangeDetector). now after beta.16 angular team decided to remove ability to set additional providers while booting (don't know why, it is a really straightforward implementation) but I really needed that ability, cause I was looking for a way to bootstrap a new application but still able to provide a connection link (via service) to that new application from the old one.
found that loadAsRoot is the best candidate for doing that, but was lacking the lifecycle hooks cause ComponenetResolver assumes that the component is loaded inside angular scope

@joebrassi you are right, my DCL fix intended to be DI as a provider, sorry for not mentioning it early

**Comment by programmer512** [comment]
hi.
@dqweek, i use your code:

```
this._dcl.loadAsRoot(component, target, this._injector)
            .then(component => {
                (<any>this._app)._loadComponent(component);

                component.onDestroy(() => {
                     (<any>this._app)._unloadComponent(component);
                });

                return component;
            });

```
component is inserted correctly but have following  error in console:

browser_adapter.ts:73 EXCEPTION: Error: Uncaught (in promise): TypeError: Cannot read property 'replace' of undefined

**Comment by joebrassi** [comment]
@dqweek I see, but what's the point then to avoid using a deprecated DCL if we are going to end up using its very same implementation (with `ViewContainerRef` and `ComponentResolver`)? I am not seeing the advantage yet, anyhow I hope the contributors of Angular know what they are doing because this `loadAsRoot()` is quite useful and if we can use it with a couple parameters (Component and location) and get the component fully working then better, so I don't see why go down to a lower level to do the same, but as said before, I hope they know what they are doing. I come from using `loadIntoLocation()` which was removed in current RC1 and now I'm replacing that implementation with whatever has to be used now, but well, let's see what comes in the final release, it should come in few more months.

**Comment by henrique-rotava** [comment]
I have made a directive that works as [htmlContent] but instead of simple HTML it proccess directives too. Since DLC is going to be deprecated, I am using `ComponentResolver` and `ViewContainerRef`.

Check it out here: https://github.com/PulpoWork/angular2-inner-content/blob/master/src/inner-content.ts

I am also accepting suggestions to improve it.

**Comment by mcferren** [comment]
@ericmartinezr Can you please offer an example on how to define component variables using the resolveComponent and createComponent methods you describe above? Similar to how we did this in the old dcl way: http://stackoverflow.com/questions/36963504/angular2-dynamiccomponentloader-parameters-for-output

**Comment by ericmartinezr** [comment]
@mcferren see here http://plnkr.co/edit/wajtv5DzDU98ouZnMgjy?p=info it's basically the same, see lines 23-25 in app.ts.

**Comment by mcferren** [comment]
@ericmartinezr cool! Many thnx - can I use subscribe there instead of then or its only set up for promises?

**Comment by ericmartinezr** [comment]
@mcferren `resolveComponent` returns a Promise. See the signature in the [ComponentResolve](https://angular.io/docs/ts/latest/api/core/index/ComponentResolver-class.html) docs.

**Comment by mcferren** [comment]
@ericmartinezr Do we still need to procure an array of ComponentRef objects ourselves or will ViewContainerRef's remove/clear function(s) automatically destroy the cmpRef that gets generated and returned from ViewContainerRef's createComponent function? Alternatively, if you call ViewContainerRef's get function, how to access the cmpRef object and (and the instance variables we discussed 2 hrs ago)?

**Comment by ericmartinezr** [comment]
@mcferren nope, in that sense nothing has changed. If you have any question about it ask in gitter's chatroom https://gitter.im/angular/angular to not deviate the issue.

**Comment by sebastian-heinz** [comment]
Hello People, i wonder if i created a Component via viewContainerRef.createComponent, and this newly created component has an template ala <iframe #myframe></iframe> defined, i can not seem to get hold of that iframes reference via @ViewChild('myframe') _myFrame:any; is there anyways to do this?

**Comment by k-paxian** [comment]
Try out this one:

export class SwPlayerYoutube implements OnInit {
    @ViewChild('swPlayerYoutube') _iframe:any;

   ngOnInit():void {
     console.log(this._iframe);
   }
}

**Comment by zoechi** [comment]
Change `ngOnInit()` to `ngAfterViewInit()` and you'll be good http://plnkr.co/edit/ysRgoiHQjdlFeNm3kKC7?p=preview

**Comment by dmarginian** [comment]
The API has changed again. ComponentResolver is deprecated in RC5 and we are supposed to be using ComponentFactoryResolver.  I basically go this working, the problem is I can't use ViewRef.  Previously I was using ApplicationRef._loadComponent to load the component to a specific selector.  The reason for this is that I am using GridStack to create dashboard widgets dynamically.  The problem with the ViewRef approach is that I end up with selector's in my DOM and it screws up the DOM for gridstack.  Here is the old code:

`componentPromises.push(this._componentFactoryResolver.resolveComponentFactory(WidgetContainerComponent).then((factory: ComponentFactory<any>) => {
          let widgetId: string = this._widgetIdPrefix + dashboardItem.widgetConfig.widgetId;
          let selectorString: string = "[id=" + widgetId + "]";
          this._logger.log("Loading widget ... " + selectorString);
          let componentRef = factory.create(this._injector, null, selectorString);
          // Manually set the dashboardItem Input so that the WidgetContainer knows how to build itself.
          componentRef.instance["dashboardItem"] = dashboardItem;
          componentRef.instance["refreshObservable"] = this.refreshObservable;
          // Register the component with appRef change detector, this is critical, without it life cycle events, bindings, etc. will not work.
          (<any>this._appRef)._loadComponent(componentRef);
          this._idToComponent[widgetId] = componentRef;
        }));`

Notice the use of _appRef to load the component directly into a specific DOM element.  If I use this now it blows up (ApplicationRef.tick is called recursively).  What am I missing?

**Comment by dmarginian** [comment]
I got this working.  

Template:
```<div #widgetPlaceholder [attr.id]="_componentContainerIdPrefix + dashboardItem.widgetConfig.widgetId" class="container-fluid panel-body widget"></div>```

Code:
```
const factory = this._componentFactoryResolver.resolveComponentFactory(this._widgetTypeHelper.getType(this._componentConfig.type));
      // Set the selector on the component so it is inserted without it's default selector (<patch>, <abp-state>, etc.).
      // The default selector's presence will mess up the DOM for gridstack.
      let selectorString: string = "[id=" + this._componentContainerIdPrefix + this._widgetConfig.widgetId + "]";
      factory.selector = selectorString;
      this._componentRef = factory.create(this._injector, null, selectorString);
      this._componentRef.instance[this._componentConfig.configPropertyName || "config"] = this._componentConfig.config;
      this._viewContainerRef.insert(this._componentRef.hostView);
```
