### ISSUE TITLE
jquery losing their context

### ISSUE THREAD

**Issue by gustavolira** [angular/angular#6224]
Hi,
I'm using Angular 2 beta with typescript.
Jquery is losing their context when using directives, I will explain above.

If I use my html directly at page (without directive) jquery works well, but If I put this html on a directive and them use it at page using the selector jquery does not works well.

For example:

If I put this piece of html directly on a page:

```HTML
...
<nav>
    <ul>
      <li class="active">
        <a href="index.html" title="Dashboard"><i class="fa fa-lg fa-fw fa-home"></i> <span class="menu-item-parent">Dashboard</span></a>
      </li>
      <li>
        <a href="inbox.html"><i class="fa fa-lg fa-fw fa-inbox"></i> <span class="menu-item-parent">Inbox</span><span class="badge pull-right inbox-badge">14</span></a>
      </li>
...
```
And use my js like:

```javascript
$.fn.extend({
  jarvismenu : function(options) {
     console.log($(this))
  }
})
```
this print to me 
```javascript
Object[ul, ul, ul, ul, ul, ul, ul, ul, ul, ul, ul, ul, ul, ul, ul, ul, ul]
```

But if I use a component like:
```typescript
@Component({
  selector: 'menu'
})

@View({
  templateUrl: './components/app/menu.html'
})

export class Menu {}
```
```javascript console.log($(this)) ``` will print  ```javascript Object[] ```

Sorry If I was not so clear

**Comment by zoechi** [comment]
Can you please create a Plunker to demonstrate the issue?

**Comment by gustavolira** [comment]
Ok I will create!
Thank you for your attention!

**Comment by gustavolira** [comment]
See test.js at this plunker https://plnkr.co/edit/z4HAefWpt02DXARY6QJP?p=preview
 console.log('should enter here!!!!!!!!!!!'); is not printed

Now see this plunker https://plnkr.co/edit/t0tbTz0XCfWEWYLrKnRS?p=preview
 console.log('should enter here!!!!!!!!!!!'); is printed

**Comment by pkozlowski-opensource** [comment]
So you are trying to use jQuery with Angular 2 in the way that is super-tricky to get right and not really recommended. The issue is that both jQuery and Angular2 are "competing" over DOM generation and you will get wired results depending on timing of DOM generation.
