### ISSUE TITLE
angular 2.0 Beta unit testing components with templateUrl throwing error  Cannot read property 'addExpectationResult' of undefined

### ISSUE THREAD

**Issue by rajvirtual** [angular/angular#6227]
My unit test is throwing an error TypeError: Cannot read property 'addExpectationResult' of undefined
if i use templateUrl instead of template for my component.

```
@Component({
    selector: 'user',
//    template: `<h1>Fake</h1> <ul> <li *ngFor="#user of _users"> </li> </ul>`, This works in unit tests !
       templateUrl: './mytemplate.html',
       providers: [HTTP_PROVIDERS],
       directives: [ROUTER_DIRECTIVES, CORE_DIRECTIVES]
})

```

This is my spec.

```
    it('should add numbers', injectAsync([TestComponentBuilder], (tcb) => {
        return tcb.createAsync(MyComp).then((fixture) => {
            expect(1 + 1).toEqual(2);
        }, function (err) {
            console.log(err); // throws: Cannot read property 'addExpectationResult' of undefined
        });
    }));

```
Does anybody has any Github example how to write unit test for components with remote templates ?

Thanks !

**Comment by zoechi** [comment]
Wrapping code in triple backticks ``` makes it much easier to read.

**Comment by ericmartinezr** [comment]
Yep, that would make it more easy to read, and besides that this is related to, if not a dup of https://github.com/angular/angular/issues/5662
