### ISSUE TITLE
DynamicComponentLoader resolves promise too early?

### ISSUE THREAD

**Issue by gaiottino** [angular/angular#6228]
The DynamicComponentLoader resolves it's promise before the DOM has been updated
http://plnkr.co/edit/LCODN7DuVrWs0wMPpNOY?p=preview 

Is there another way to wait for the DOM to be ready?

**Comment by ericmartinezr** [comment]
@gaiottino I don't really understand what you're trying to achieve. You can easily put this code in the DCL

```
class DynamicCmp {
  options: [] = [];
  constructor(private _e: ElementRef) {}
  ngAfterViewInit() {
    console.log($(this._e.nativeElement).find('.option').length); // Prints 6
  }
}
```

And why are you using jQuery? You can achieve the same using angular2

```
@Component({
  selector : 'dynamic',
  template : `
    <div *ngFor="#option of options" #elem>{{option}}</div>`
})
class DynamicCmp {
  options: [] = [];
  @ViewChildren('elem') elements;
  
  constructor(private _e: ElementRef) {}
  ngAfterViewInit() {
    console.log(this.elements.length); // Prints 6
  }
}
```

**Comment by gaiottino** [comment]
Ultimately I'm looking for a replacement to Angular1's `$compile`. I'm simplifying, but basically the component I'm trying to write has two parts. The first handles the logic for the options that are passed and the reason I'm trying to use DCL is because I want the rendering part of the component to be dynamic. It should be able to have a default renderer

```
@Component({
  template: '{{option.name}}'
})
```

but I'd like to be able to do something like.

```<my-component [options]="options [renderer]="myRenderer" />```

where `myRenderer` is

```
@Componet({
  template: '<b>{{option.name}}</b>'
})

and then this is passed to the DCL. This I've managed to do, but the problem is that the component relies on a 3rd party JQuery lib which needs to be called once the chosen renderer has completed updated the DOM. This is when I realised that the DCL resolves it's promise before this has happened and hence my plunkr.

**Comment by gionkunz** [comment]
@ericmartinezr, the `ngAfterViewInit` would only be an option if you have control over the dynamic component. If you like to provide SPI mechanisms using dynamic components that are created by others, you'd probably want to run something after component hydration / initialization from outside the component.

**Comment by pkozlowski-opensource** [comment]
`DynamicComponentLoader` is depreciated and the closest thing to `$compile` from ng1 is `ComponentFactory` + inserting created view. Closing since this is not actionable / support question.
