### ISSUE TITLE
Router: Trying to load state that fails due to HTTP 404 disables all router links

### ISSUE THREAD

**Issue by varadero** [angular/angular#6233]
Simply add 2 or more router links, something like:
```
<a [routerLink]="['First']">First</a>
<a [routerLink]="['Second']">Second</a>
```

Let "Second" component reference non existing html in its ```@Component``` ```templateUrl``` in order for server to reply with HTTP 404. Now click on "First" link - the state should be loaded, now click on "Second" link - error will be logged in console and every router link now becomes unusable - clicking again on "First" does nothing - even console does not show anything.

I have observed similar behavior not with HTTP 404 but with other problems. Is this by design ? Could I intercept "state loading failed" event and do something ?

**Comment by vicb** [comment]
This router is deprecated
