### ISSUE TITLE
Is the example for overriding LocationStrategy backwards?

### ISSUE THREAD

**Issue by JohnMunsch** [angular/angular#6234]
When overriding the LocationStrategy with the HashLocationStrategy I followed the example given in the Routing & Navigation guide at the end:
 
```
bootstrap(AppComponent, [
  provide(LocationStrategy,
         {useClass: HashLocationStrategy}), // ~/src/#/crisis-center/
  ROUTER_PROVIDERS
]);
```

But that didn't work. It kept giving me the default strategy and screaming because I had removed the base from my index.html. Only when I reversed it and put the provide _after_ the ROUTER_PROVIDERS did it work:

```
bootstrap(AppComponent, [
    ROUTER_PROVIDERS,
    provide(LocationStrategy,
         {useClass: HashLocationStrategy})
  ]);
```

It makes sense that there is a precedence order for these dependency injections, did the example get it wrong or have I made some other mistake?

**Comment by wardbell** [comment]
Yes it is backwards. It's fixed in [angular.io PR #637](https://github.com/angular/angular.io/pull/637) which will be published very soon.

**Comment by pkozlowski-opensource** [comment]
This doc issue was fixed in https://github.com/angular/angular.io/commit/af458737be802f3e5f897529ad39f25d33425dc0
