### ISSUE TITLE
Provide method to override host view bindings on `ComponentFixture`

### ISSUE THREAD

**Issue by ovangle** [angular/angular#6235]
I was trying to write a unit test which relied on code that was intended to run during `ngOnChanges`, 

```typescript
it('should emit an event when the message has changed', injectAsync([TestComponentBuilder], (tcb) => {
  return tcb.createAsync(MyComponent, (fixture) => 
    var result = fixture.componentInstance.change.first().toPromise().then((change) => {
       //expectations
    });
   fixture.componentInstance.message = 'some message';
   fixture.detectChanges();
   return result;   
});
```

However this does nothing as the change detector will not detect that the input property has changed, since I'm modifying the value on the child component. 

I eventually solved the issue by wrapping the test component in another component as follows:

```typescript
@ng.Component({
   selector: 'my-component-host'
   template: '<my-component [message]="message" (change)="onChange.emit($event)"></my-component>
   directives: [MyComponent]
}) 
class MyComponentHost {
   message: string;
   onChange = new EventEmitter();
}
```

And then ran the test on the host component instead. However, this is needlessly cumbersome and verbose for what should be a simple unit test.

Would it be possible to add a method like `ComponentFixture.bindInput(input: string, toValue: any)` which would modify one of the component's input properties so that the change is detected during change detection?

**Comment by eddhannay** [comment]
This would be a really handy extra method - while both approaches work, neither are as neat as the other overrides that `TestComponentBuilder` offers.

**Comment by lroitman** [comment]
Having the same problem. I have a code that executes in ngOnChanges, but this code is not triggered when running 
`componentFixture.changeDetection();`
As an immediate workaround I will be wrapping the component under test in the unit tests, but I am wondering what the Angular team thinks the proper solution to the problem would be.

**Comment by sammichelson** [comment]
In your unit test why can't you call ngOnChanges?  For example: 

import { SimpleChange } from '@angular/core';
let oldPropertyReference = {};
let newPropertyReference = { test: 1};
let changes = new SimpleChange(oldPropertyReference, newPropertyReference);
fixture.componentInstance.ngOnChanges({ 'someComponentProperty': changes });

**Comment by pkozlowski-opensource** [comment]
> As an immediate workaround I will be wrapping the component under test in the unit tests, but I am wondering what the Angular team thinks the proper solution to the problem would be.

Wrapping is the way to go as it guarantees that the component under test executes in the environment identical to the one from the production app. In most cases you want to test input and outputs and this is best done with real-life registration of bindings / output listeners.

There are no particular plans to add new testing API to cater for this use case.

> In your unit test why can't you call ngOnChanges? 

This would be perilous as you would have to know exactly which lifecycle hooks are called in particular points in time (which roughly means duplicating internal Angular logic).

**Comment by sammichelson** [comment]
@pkozlowski-opensource You're given a doc page explaining the lifecycle hook sequence. https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html If you're creating a component shouldn't you understand how Angular uses your components? ngOnChanges is only called when the data-bound input properties change and it's called before ngOnInit. I'm not sure about you but I'd want to know this so my tests catch issues in my own logic and not Angular's. 

In your component tests you're calling fixture.detectChanges isn't that also duplicating Angular's change detection strategy?
