### ISSUE TITLE
Do not create new components via the attribute syntax

### ISSUE THREAD

**Issue by davidreher** [angular/angular#6238]
Hey,

I tried using the new 1.5 component router and component api. While doing this I created my components without an explicit restrict attribute. [The loader restricts them to 'E' by default](https://github.com/angular/angular.js/blob/master/src/loader.js#L426). 

The component router (for angular1?) creates new components [via attributes syntax](https://github.com/angular/angular/blob/master/modules/angular1_router/src/ng_outlet.ts#L158).

Please change the default restriction to 'AE' or change the component router ;)

I already posted this in [the angular1 repository](https://github.com/angular/angular.js/issues/13603) and they pointed me here.

**Comment by trelltron** [comment]
I'm not really familiar with any of the Angular source, but I think this is the project they are referring to: https://github.com/angular/router

**Comment by davidreher** [comment]
I just saw, that (pull request 5278)[https://github.com/angular/angular/pull/5278] fixes this issue ... Please merge it soon ;)

**Comment by davidreher** [comment]
as @petebacondarwin pointed out in the [angular1 bug report](https://github.com/angular/angular.js/issues/13603) this needs to be fixed in the component router.
