### ISSUE TITLE
angular2-polyfills.js messing up events

### ISSUE THREAD

**Issue by david10sing** [angular/angular#6239]
I'm calling a method from an external JS file to initialise a function and the function requires n.events but when the function is loaded, n.events is not available to that function and throws Type error of undefined. Is there a way for these events to be still available to the injected function after routing.

see example at demo.madappe.com/admin

**Comment by david10sing** [comment]
Most events are being hijacked by angular2-polyfills and is not being picked up by external scripts. Am I wrong here? Please correct me...

**Comment by pkozlowski-opensource** [comment]
This would belong to https://github.com/angular/zone.js. Please follow the issue template when reporting bugs.
