### ISSUE TITLE
Angular Router not supporting empty params

### ISSUE THREAD

**Issue by gmfun** [angular/angular#6242]
I have a Router like this
`{path: '/search/:query/:min_date', component: SearchComponent, as: 'Search'},`

It works fine when both query and min_date params are present (url = "/search/asd/2016-01-04T12:46:12.644Z"). When I refresh, it still works fine.

But when i have an empty min_date params (url = "/search/asd"), and I refresh the page, the component doesn't load.

This route I am using in a child component.

**Comment by ericmartinezr** [comment]
That's because it's a  totally different route, it isn't "empty" param, it's simple another route. You should be fine by adding another one

```
{path: '/search/:query', component: SearchComponent, name: 'SearchWithNoParam'},
{path: '/search/:query/:min_date', component: SearchComponent, name: 'SearchWithParam'},
```

**Comment by gmfun** [comment]
thanks.. It's very helpful.
