### ISSUE TITLE
Case sensitive CSS class names when creating component host element

### ISSUE THREAD

**Issue by dblVs** [angular/angular#6244]
Hello,

I believe having case sensitive CSS classes would be really beneficial. 

Example: 

```
@Component({
selector: 'example-tag.ExampleClass'
})
```

would be rendered as 
`<example-tag class="ExampleClass"> </example-tag>`

The problems this would solve are that you cannot put classes on elements inserted by router-outlet.
And for people who adopted certain conventions, it might be limiting them. Example convention 

https://suitcss.github.io/

**Comment by zoechi** [comment]
Please wrap multiline code in ```` ` and inline code in `

**Comment by dblVs** [comment]
Thank you. Fixed it.

**Comment by zoechi** [comment]
Much better :)

**Comment by dblVs** [comment]
Can anyone look at this ? Maybe @alexeagle?

**Comment by dblVs** [comment]
Any updates on this ?

**Comment by vicb** [comment]
As CSS is not case sensitive, why should we be case sensitive here ?

**Comment by dblVs** [comment]
CSS classes are case sensitive.

**Comment by dblVs** [comment]
https://www.w3.org/TR/selectors/#casesens

**Comment by dblVs** [comment]
Hello.
What you just said doesn't match the specification.

Please check this.

https://www.w3.org/TR/html4/struct/global.html#h-7.5.2

**Comment by cristinecula** [comment]
@vicb you are right that CSS is not case sensitive, but the `class` and `id` HTML attributes are.

> CSS is case insensitive in all matters under its control; however, some things, such as the document markup language, are beyond its control. HTML is case insensitive in most respects, except when it comes to certain attribute values, like the id and class attributes. 

> http://reference.sitepoint.com/css/casesensitivity

As you can see in this pen, the `.red` selector's styles are not applied to both elements:
http://codepen.io/cristinecula/pen/KVryRy

**Comment by vicb** [comment]
@cristinecula you're right.

@mhevery what do you think ?

**Comment by dblVs** [comment]
@vicb Could you reopen the issue please ?

**Comment by dblVs** [comment]
Also for a valid use case please check http://suitcss.github.io/

**Comment by mhevery** [comment]
We can revisit this post RC

**Comment by dblVs** [comment]
@mhevery since now it's post RC can we have a fresh look at this ?

**Comment by mhevery** [comment]
How could this be done in a backward compatible way?

**Comment by dblVs** [comment]
One naïve implementation is with flags.

**Comment by laco0416** [comment]
an idea; `CASE_SENTITIVE_SCHEMA` to enable that feature.

```ts
@NgModule({
  schema: [CASE_SENTITIVE_SCHEMA]
})
```

**Comment by zoechi** [comment]
@dblVs See https://github.com/angular/angular/issues/6244#issuecomment-173026398
Angular can't provide something that the browser doesn't support.

**Comment by dblVs** [comment]
@zoechi it would be nice if you actually read the comments. I'm pretty aware with the HTML specification. Class Names are case sensitive since ages ago. This issue is to stop Angular using .toLowerCase() on the class name since `.SomeClass` is different to `.someclass` 
```
id = name [CS]
This attribute assigns a name to an element. This name must be unique in a document.
class = cdata-list [CS]
This attribute assigns a class name or set of class names to an element. Any number of elements may be assigned the same class name or names. Multiple class names must be separated by white space characters.
```
[CS] means case sensitive.

When people put specs at least make the effort to read them.

**Comment by zoechi** [comment]
@dblVs I see. My bad.

**Comment by dblVs** [comment]
Shall I create a PR with this @mhevery ?

**Comment by mhevery** [comment]
Yes you can create PR. I think looking at how whitespace removal was handled and how that was implemented my be a good idea.

You will need a flag in `@Component.caseSensitiveStyles` which will enable this flag on a per component basis, and also a global `caseSensitiveStyles` flag in the system wide. We will than need to allow authors to turn on individual `@Compnoent.caseSensitiveStyles` flags than make them mandatory, than switch the global flag default to true and than deprecate the `@Component.caseSensitiveStyles` and this has to happen over two major releases. 

And of course Documentation and migration guide.

What you are signing up for is a lot of work over several months. I don't mean to scare you, but if you would be willing to do that I am hoppy to shepherd this process.

**Comment by dblVs** [comment]
@mhevery before I take this on, to be sure i'm clear what needs to be done (and save loads of time).
This needs some work on the `compiler` and `core` packages right ? (the parsers in compiler and adding the option in the linker) ? (I would like to give it a go)

**Comment by mhevery** [comment]
Yes, you seem on the right track.

**Comment by pkozlowski-opensource** [comment]
Here is a minimal stackblitz reproducing the issue: https://stackblitz.com/edit/angular-2pregz?file=src%2Fapp%2Fapp.component.ts

The actual problem being discussed in this issue is the fact that dynamically created element (representing a host of a dynamically inserted component) is a generated with a lower-cased class name (`class="mixedcase"` instead of `class="mixedCase"`).

This is caused by the fact that we want class names to be case insensitive when matching directives but we also go through the same code-path while _creating_ host element from a selector.

We've got exactly the same problem for attributes (as described in #25285)

**Comment by dblVs** [comment]
@pkozlowski-opensource @mhevery i'm closing this as it is fixed by ivy
