### ISSUE TITLE
Web Components support in features list

### ISSUE THREAD

**Issue by edoardocavazza** [angular/angular#6246]
Hi everyone,

first of all, really thanks for your fantastic work and support. 

I have noticed that "Web Components compatible" is disappeared from the [features list](https://angular.io/features.html) of Angular 2 after the beta announcement. 
Is this an oversight or it has been dropped?

Thanks again!

**Comment by kairun** [comment]
+1

**Comment by vicb** [comment]
Angular2 supports WebComponents. (however Angular2 components are not consumable as WC)

**Comment by rjsteinert** [comment]
> however Angular2 components are not consumable as WC

Would love to see that! Similar to Glimmer Web Components, the WC export of an Ember View.
