### ISSUE TITLE
Load angular2 outside of npm with TypeScript

### ISSUE THREAD

**Issue by samouss** [angular/angular#6247]
Hello, 

I have trouble for build an application with `JSPM` and `angular2` (`2.0.0-beta.0`).

When we install `angular2` through `npm`, the package is in `node_modules` and with a good `tsconfig` configuration we can load `angular2` modules with TypeScript without trouble like this:

```ts
import { Component } from 'angular2/core';
```

But I use `JSPM` for my app.

So I install `angular2` through it and `JSPM` put the dependency in the subfolder `jspm_packages` by default. When I load it in the browser with `SystemJS` I don't have any problems.

The only issue is in the TypeScript compiler.

When I try to import `angular2` modules, the TypeScript compiler will try to load modules specify in `tsconfig` (`files`) and in `node_modules` but like I said, the dependency isn't in `node_modules` but in `jspm_packages`. 

Therefore, I have the following error which is normal : 

```
Cannot find module 'angular2/core';
```

Because TypeScript try to load `nodes_modules/angular2/core` instead of `jspm_packages/.../angular2/core`.

So, my question is how I can do for load `angular2` correctly inside the TypeScript compiler ?

**Comment by dsebastien** [comment]
That is a TypeScript "issue" (or rather a missing functionality), not an Angular one. This is the issue that you should keep an eye on: https://github.com/Microsoft/TypeScript/issues/5039

Once that feature lands, it will be possible to configure path mappings, which will allow you to help the TypeScript compiler know where to find modules that you refer to in your code.

**Comment by samouss** [comment]
Thanks a lot for your response !

I don't know how I missed this issue.

I'm closing it.

**Comment by dsebastien** [comment]
Note that there is a second issue: https://github.com/Microsoft/TypeScript/issues/6012 and another one on the JSPM side: https://github.com/jspm/jspm-cli/issues/1344

**Comment by taxinvoice** [comment]
So how do i fix this issue in the meantime?  Using visual studio 2013.

**Comment by dsebastien** [comment]
You need to duplicate the dependencies (or let go of JSPM and play around with the config file used by SystemJS)

**Comment by Gaulomatic** [comment]
Are there any details how the achieve this workaround?
