### ISSUE TITLE
Allow directives to export variables

### ISSUE THREAD

**Issue by mhevery** [angular/angular#625]
- Exporting variables for `Directives` and `Viewport` is different
  - `Viewport`:
    - exports variables into child `View`
    - can change values at runtime
    - happens during the reaction function
  - `Directive`
    - exports variables into current view
    - can not change values at runtime
    - happens during View hydration. After directive instantiation, but before change detection

```
@Decorator({
  export: {
    'var_name': 'someProperty'
  }
})
class {
  someProperty; // This contains the value which needs to be exported
}
```

**Comment by mhevery** [comment]
@vsavkin do you need this for forms? Does this makes sense?
/cc @jelbourn

**Comment by vsavkin** [comment]
@mhevery Yes. Currently I have to use components to implements forms. This change would allow using Decorators instead.

In addition to exporting properties the directive should be able to export itself. Otherwise I would have to use the following workaround:

```
@Decorator({
  export: {
    'var_name': 'self'
  }
})
class {
 get  self() {return this;}
}
```

**Comment by jelbourn** [comment]
Do you have an example use-case for this feature?

**Comment by vsavkin** [comment]
@jelbourn Forms API is an example

```
@Decorator({
  selector: '[control-group]', 
  export: {form: 'this'}
})
class ControlGroup {
} 
```

In the template: 

```
<div #loginForm="form" [control-group]="blah">
</div>
```

**Comment by vsavkin** [comment]
@mhevery I think this PR closes this issue: https://github.com/angular/angular/pull/2350.

The directive can export itself into the view. You can get access to everything else via the directive instance.
