### ISSUE TITLE
Getter is being fired few times when value of service changes once

### ISSUE THREAD

**Issue by wkwiatek** [angular/angular#6251]
Take a look at this example: http://plnkr.co/edit/0bEbLib9agsvGIZMKRng?p=preview

Why this `console.info` from `app.ts` is being fired so many times? Is there something wrong with change detection?

**Comment by michalstepien** [comment]
I think, we can close this. Please read:
http://blog.thoughtram.io/angular/2016/02/22/angular-2-change-detection-explained.html

**Comment by wkwiatek** [comment]
Yes. It's a little bit outdated.
