### ISSUE TITLE
When decorating class, Dependency infection is not respected...

### ISSUE THREAD

**Issue by born2net** [angular/angular#6258]
so I am trying to decorate a class, and it's working fine, the only issue is that I am losing my original class's constructor dependency injection and so of course everything is failing.

so my original class is:
```
@RefreshTheme
export class App implements AfterContentInit {
private m_commBroker:CommBroker;
private m_styleService:StyleService;

constructor(commBroker:CommBroker, styleService:StyleService) {
    this.m_styleService = styleService;
    this.m_commBroker = commBroker;
    ...
```
so as you can see I am DI commBroker and styleService

and my @RefreshTheme is:
```
export function RefreshTheme<TFunction extends Function>(Target: TFunction): TFunction {
var newConstructor = function () {
    Target.apply(this);
    Object.freeze(this);
};

newConstructor.prototype = Object.create(Target.prototype);
newConstructor.prototype.constructor = Target;

return <any> newConstructor;
}
```
and as long as I don't use DI in the original class, all is good... but I need to respect the original class constructor regardless of what it is (diff classes will of course have diff constructor signatures)...

thanks for reading,

regards

Sean.

**Comment by zoechi** [comment]
I think http://stackoverflow.com/questions/34598117/in-angular-2-how-can-we-decorate-a-class-and-maintain-dependency-injection-of-t is the right place for this question.

**Comment by born2net** [comment]
yes tx, but no one seems to know :/

**Comment by zoechi** [comment]
Your question is out there for just 1h.

**Comment by born2net** [comment]
ok tx for the reply.. will wait...

**Comment by robwormald** [comment]
you're replacing (?) the constructor there - DI parameters get added to the constructor (see Reflect), so I suspect that's why this is failing.

**Comment by born2net** [comment]
can you suggest code snippet?
that's what I am doing now
```
export function RefreshTheme(theme:string) {
    return function <TFunction extends Function>(Target:TFunction):TFunction {
        var newConstructor = function () {
            console.log('do something with ' + theme);
            Target.apply(this);
            Object.freeze(this);
        };

        newConstructor.prototype = Object.create(Target.prototype);
        newConstructor.prototype.constructor = Target;

        return <any> newConstructor;
    }
}
```

**Comment by born2net** [comment]
and yes I am replacing the constructor sine I need to implement a new functionality but I chain it to the original constructor, but the problem is that now DI no longer works... there must be a trick to override the original constructor and still maintain the DI as that is what @Component() does....

**Comment by gsans** [comment]
You can find code for trick here:
https://github.com/angular/angular/blob/2.0.0-beta.0/modules/angular2/src/core/metadata/directives.ts#L759-L931

**Comment by born2net** [comment]
ya not much luck so far... I would almost say it's a missing feature... mmm....

**Comment by robwormald** [comment]
What exactly is a missing feature here? You're entirely replacing the constructor (to which Typescript attaches the metadata during compilation, to enable DI) so there's basically nothing Angular can do about this.

The manual workaround would be to use the Reflect API to do something like this:
```typescript
let injectorParams = Reflect.getMetadata("design:paramtypes", YourComponent);

Reflect.defineMetadata("design:paramtypes", injectorParams, YourNewComponentConstructor)
```

That said, I have no idea what will happen if you try injecting that into something else. It seems like this is a pretty drastic approach for theming, IMO.

**Comment by wesleycho** [comment]
It should be mentioned that this sort of code is recommended against in ng2 - extending a class or anything else that uses a new class will create this problem with the metadata from the decorator to be lost, since the metadata is on the static class.

The correct approach I believe would be to observe for changes to the theme and to subscribe to them in the component & trigger a `refreshTheme` method (or similar) when the theme updates.

**Comment by born2net** [comment]
it's not to apply a theme but to initiate a refresh on first load of a constructor which would be perfect, if it worked...

**Comment by pkozlowski-opensource** [comment]
We are tracking inheritance-related issues in #11606
