### ISSUE TITLE
Not able to render SVG attributes via a template

### ISSUE THREAD

**Issue by SteveVanOpstal** [angular/angular#6259]
The following code seems to me like a good way to handle some simple svg attributes. Yet this will not render the attributes (plunker) or generate an error (local).

```Javascript
@Component({
	selector: 'comp',
	template: `
	<svg width="{{width}}" height="{{height}}" viewBox="0 0 {{width}} {{height}}">
		<circle cx="50" cy="50" r="40" fill="red" />
	</svg>`
})
class Component {
  private width: number = 50;
  private height: number = 50;
  
  constructor() {}
}
```
http://plnkr.co/edit/tq6EpgX7iE5cBYhxIu30?p=preview

I suspect that the 'problem' lies in the SVG web API; the `width` and `height` attributes are `readonly`:
> SVGSVGElement
> [...]
> readonly SVGAnimatedLength width
> readonly SVGAnimatedLength height

[source](https://developer.mozilla.org/en-US/docs/Web/API/SVGSVGElement)

The before mentioned code generates an error which backs this up:
>TypeError: Cannot set property width of #<SVGSVGElement> which has only a getter in [{{width}} in [file-name]]

[I can work around this by using d3](http://plnkr.co/edit/tq6EpgX7iE5cBYhxIu30?p=preview) but I think many people will agree that this is less straight-forward as using the angular template.

**Comment by vicb** [comment]
`width="{{width}}"` creates a property binding (same as `[width]="width"`) and as shown on MDN (the link from your post), `width` and `height` **properties** are instances of `SVGAnimatedLength` and read-only.

You should use attribute binding here, ie `<svg [attr.width]="width" [attr.viewBox]="getViewBox()">` where `getViewBox` would be a method on your component returning `"0 0 50 50"` (you could also implement it as a getter).

**Comment by SteveVanOpstal** [comment]
Many thanks. My apologies for wasting your time. I was convinced it was a unsupported feature.

Until now I had no knowledge of the syntax distinction between properties and attributes. A look at the [angular 2 cheatsheet](https://angular.io/cheatsheet), quickly broadened my horizon.

A plunker with the solution:
http://plnkr.co/edit/yracmMi57oKraJMU5U6X?p=preview
