### ISSUE TITLE
Location API needs to expose more information about current route

### ISSUE THREAD

**Issue by pdeva** [angular/angular#6260]
Currently it just gives a full url which is too little info.

It should give info about the actual route objects too.

Currently if you are say at a route and want to go to its child and/or parent or retrieve some 'params' data from child/parent route, you have to do insane regex magic, specially if the path is composed of params.

People are taking to [tracking every single route transition](http://stackoverflow.com/questions/34597835/how-to-get-current-route-in-angular-2/34598745?noredirect=1#comment56943240_34598745) to try to build this themselves.

Please provide more data than just the url in the `Location` object.

**Comment by ericmartinezr** [comment]
If you want more data of the route you're in you have to use the [Router](https://angular.io/docs/ts/latest/api/router/Router-class.html), not Location, but still, afaik even with Router there's no easy way to get parent's params.

**Comment by zoechi** [comment]
+1

**Comment by NathanWalker** [comment]
It would help to at least have this as well:
https://github.com/angular/angular/pull/4905

**Comment by vicb** [comment]
obsolete - old router
