### ISSUE TITLE
Need documentation on using jquery widgets inside angular components

### ISSUE THREAD

**Issue by pdeva** [angular/angular#6261]
It is very common to come across a third party widget that uses jquery for dom manipulation.

There is no documentation around the proper way to setup/teardown such a widget inside an angular component.

If there is anything that might mess with angular 2's internal (shadow?) DOM representation, that should be documented too.

**Comment by wesleycho** [comment]
This wouldn't just apply to jQuery - for example, if one is working with SVG, there is a high likelihood of using d3.

Some recommended conventions in a developer guide would probably be a good thing, this question seems to get asked every now and then around.

**Comment by pkozlowski-opensource** [comment]
Closing as this is a general support request.
