### ISSUE TITLE
I find angular 2.0. Json file type value of it will be a script, which lead to my application error

### ISSUE THREAD

**Issue by febobo** [angular/angular#6264]
I find angular 2.0. Json file type value of it will be a script, which lead to my application error

**Comment by cuitianze** [comment]
I want to know when could i use withCredentials with http request ?

**Comment by febobo** [comment]
~~！！！！~~

**Comment by zoechi** [comment]
@febobo I find your question quite vague,  can you please add at least the concrete error message? 
@cuitianze your comment doesn't seem related. I guess this is what you are looking for #4231

**Comment by ocombe** [comment]
@zoechi I'm impressed at what you managed to answer to those cryptic messages ! :+1:

**Comment by zoechi** [comment]
@ocombe I have seen so many of them, they start making sense :stuck_out_tongue_winking_eye:

**Comment by pkozlowski-opensource** [comment]
Closing this one as it is not clear what is the question / problem here. @febobo if you need more help please clearly describe what is your problem / expected behavior and provide a live reproduce sccenario using plunker or similar
