### ISSUE TITLE
Angular 2.0 Beta does not work in Safari 5.1.7 in Windows 7 

### ISSUE THREAD

**Issue by wenyanzhu** [angular/angular#6265]
I run  a ASP.NET 5 MVC + Angular 2 (2.0.0-beta.0) application in Windows 7 and it is working in Chrome but not in Safari (5.1.7 in Windows).  The error in console is
 
Error
line: 1
message: "'undefined' is not a constructor (evaluating 'new t.Map')↵	Error loading http://localhost:60708/js/app/boot.js"
sourceId: 2091509568
sourceURL: "http://localhost:60708/lib/systemjs/system.js"
stack: undefined

It seems not working in Safari in Max OS as well.

**Comment by S-YOU** [comment]
Most likely Safari 5.1 is unsupported - 
http://gurustop.net/blog/2015/10/07/angularjs2-internet-explorer-support

**Comment by robwormald** [comment]
You likely need the ES6 polyfill...

**Comment by pkozlowski-opensource** [comment]
Given that Safari 5.1.7 is very old browser with minimal usage on Windows and no clear support statement from Apple we are not planning to support Safari 5.1.7. This means that we are not going to have automated tests for this version nor actively work on bug fixes.

It doesn't mean that Angular2 can't work on this browser - maybe it can be run given all the required polyffils are included.
