### ISSUE TITLE
Don't include node.d.ts in published typings

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#6266]
This is only needed for users who run their tests in node. They should make their own dependency on it if they want to do that.
https://github.com/Microsoft/TypeScript/issues/3215#issuecomment-168978840 reminded me of this.
@vicb do we have separate compilation units yet, so that we can have only a small part of angular depend on node.d.ts?

**Comment by vicb** [comment]
not yet, see #6262

**Comment by alexeagle** [comment]
The referenced PR is now in, so we should do this.

**Comment by rixrix** [comment]
:thumbsup:
