### ISSUE TITLE
Zone.js for angular 2 causes issue with jquery events

### ISSUE THREAD

**Issue by david10sing** [angular/angular#6268]
Zonejs is part of angular2-polyfills.js and zone.js hijacks events. This is causing issues with JS scripts that listen to jquery events. Is there a way to not be dependent on zonejs? I tried to exclude it but then normal mouse events are not working with angular 2.

**Comment by ericmartinezr** [comment]
Do you really think people will stop doing what they're doing to try to guess the *issues* you're having?

**Comment by david10sing** [comment]
@ericmartinezr, you did...

**Comment by ericmartinezr** [comment]
Yep, just to tell you that most won't, and I'm pretty sure you still don't get your answer, right? Yes, because I didn't stop to guess :)

**Comment by david10sing** [comment]
Ok. Here I updated the issue.

**Comment by ericmartinezr** [comment]
@david10sing check this issue https://github.com/angular/angular/issues/6152, it has the answer ot your question.
