### ISSUE TITLE
Getting "Could not find Directive entry for name" error on angular dart

### ISSUE THREAD

**Issue by adaojunior** [angular/angular#6269]
I created this directive [ng_mediaquery](https://github.com/adaojunior/ng_mediaquery) for angular dart and it worked fine for the example that I have in the `example` folder.
When I tried to use it in my other ng2 project [english-verbs](https://github.com/adaojunior/english-verbs) I got the following error.
```
> pub serve
Loading source assets...
Loading angular2 and dart_to_js_script_rewriter transformers...
Serving english-verbs web on http://localhost:8080
[Warning from TemplateCompiler on english-verbs|lib/src/components/conjugation-view/conjugation-view.ng_meta.json]:
Could not find Directive entry for name: MediaQuery
. Please be aware that Dart transformers have limited support for reusable, pre-defined lists of Directives (aka "directive aliases"). See https://goo.gl/d8XPt0 for details.
Build completed successfully
```
and the directive would not work.

It could not find out if I was missing something or if it is a angular bug. I tried a few diferent solutions like changing the class name, directive name or selector, even making it a Component, yet it does not work.
I went back to the `ng_mediaquery` and run it and it worked, I copied the `examples` folder to the `english` verbs folder.
when I run I get the same error.

Only this part changed:
```
[Warning from TemplateCompiler on english-verbs|example/main.ng_meta.json]
```

Am I missing something here ?

Let me know you need more details.

**Comment by zoechi** [comment]
I think you need to add (without actual entry points) in your library package(s):
```yaml
transformers:
- angular2:
```

Dart transformers can only process files in the package where they are added to the `pubspec.yaml` file.
If you have packages like

```
 - PackageA (with entry points)
   |- PackageB (with Angular components and services)
   |- PackageC (with Angular components and services)
      |- Package D (with Angular components and services)
```
the Angular transformer needs to be added to each of them, but the `entry_points` only need to be added where they apply ( for example PackageA: `web/main.dart`, `PackageB: `example/main.dart`, `PackageC: `test/some_test.dart`, ...)

I had this in Polymer and assume it's the same situation here.

**Comment by zoechi** [comment]
In order to be able to `pub build` your examples you'd need the transformer anyway.

**Comment by adaojunior** [comment]
@zoechi 's solution worked for me.
I added  the angular2 transformer in my pubspec:
```
transformers:
- angular2
```

Thank you
