### ISSUE TITLE
Async routes cause route data to be lost

### ISSUE THREAD

**Issue by hitmanmcc** [angular/angular#6272]
Hello guys,

I'm using angular 2 beta.0 and I'm trying to change the routeconfigs so some of my components are loaded asynchronously.
Unfortunately, when I do so, the data I pass to the data parameter of the route gets lost. This is only happening for ```AsyncRoute```s, I figured it might be the case that this is not supposed to be possible but the docs say otherwise.
I've set-up a plunkr where you can see this happen. There are 2 components to which you can navigate by clicking one of the 2 buttons.
The first one is for a synchronous route and it prints out the data I pass in.
The second one is for an asynchronous route and it does not print out anything because as you can see from the console output, the routeData object does not hold the data that I passed in the route configuration.
Example here: https://plnkr.co/edit/LYaQvPzpBmmI9ADn3poQ

Best regards,
André

**Comment by mattimatti** [comment]
+1

**Comment by hitmanmcc** [comment]
@mattimatti Thank you very much for the workaround, nicely caught Matteo. :) :+1: 
I'll still leave the issue open for the simple reason that Angular 2's current router DSL does not mandate that you specify which type of route you want, the framework recognizes that for you. 
As such, this is still a bug, which should be solved in one of two ways. Either change the framework to mandate that all route types should be specified when being declared in the route config or, fix whatever bit of code is causing the routeData to go missing.

**Comment by vsavkin** [comment]
We are no longer maintaining the deprecated router to focus our efforts on making the new router solid.

It doesn't look like the issue makes sense in the context of the new router. If you think it does, please reopen the issue.
