### ISSUE TITLE
How can I inject dependencies or init component as or after promise resolving

### ISSUE THREAD

**Issue by Jackson88** [angular/angular#6273]
Problem looks like this:
I want to use httpOnly cookie authentication, as result before bootstrap is loaded I shoud do one request to server for checking -  am I authorize or not (success response 200 - its ok, 401 - I'm not authorized)
example:
```typescript
class AuthService {
    constructor() {
           this.defineAuthentication();
    }
    isAuthenticated() : boolean {...}
    defineAuthentication() : Promise <any> {...}
}
bootstrap(AppComponent, [AuthService]);
```
Does it has possibility to init AuthService or even main AppComponent just after promise from "defineAuthentication" is resolved? Its needed to know - should user be "redirected" to other route or he can stay on this (or example if user authorized and opens in new tab "somesite.com/login" - he should be redirected to "somesite.com/home")

**Comment by Emnalyeriar** [comment]
Any news on this? I have a similar problem. The app I'm working on is translated to many languages. Before app init I need to fetch a json file containing all of the text content for the page. If I make my own instance of service before app init and resolve it then Angular will make its own instance after the init.
I tried many approaches and can't seem to get this working. Tried the `@CanActivate` decorator or angular life cycle events like `routerOnActivate` or `onInit` but this doesn't seem to work anyway.

Any tip would be greatly appreciated.

**Comment by Jackson88** [comment]
@Emnalyeriar I've fixed is in this way:
I've extended RouterOutlet directive in way like this:
```typescript

@Directive({
    selector: 'router-outlet',
})

export class OwnRouterOutlet extends RouterOutlet {
    
    private service: SomeService;

    constructor(_elementRef: ElementRef, _loader: DynamicComponentLoader,
                _parentRouter: Router, @Attribute('name') nameAttr: string,
                service: SomeService) {
        super(_elementRef, _loader, _parentRouter, nameAttr);
        this.service = service;
    }

    activate(instruction: ComponentInstruction): Promise<any> {
        return this.service.somePromiseAction().then( function (result: any) {
            return this._handeActivate(instruction);
        }.bind(this));
    }

    private _handleActivate(instruction: ComponentInstruction): Promise<any> {
          super.activate(instruction);
    }
}
```
In this solution you could do some other actions before you will activate current route, of cource you also should modify it in case to working this action just one time - when you just open your site in new tab for example

**Comment by pkozlowski-opensource** [comment]
Sounds like a support question that got resolved.
