### ISSUE TITLE
constructor(router:Router) {} cause error Make sure they all have valid type or annotations.

### ISSUE THREAD

**Issue by PrimeObjects** [angular/angular#6279]
index.html
<script src="https://code.angularjs.org/2.0.0-beta.0/angular2-polyfills.js"></script>
 <script src="https://code.angularjs.org/tools/system.js"></script>
 <script src="https://code.angularjs.org/2.0.0-beta.0/Rx.js"></script>
<script src="https://code.angularjs.org/2.0.0-beta.0/angular2.dev.js"></script>
<script src="https://code.angularjs.org/2.0.0-beta.0/router.dev.js"></script>

boot.ts

import {bootstrap}    from 'angular2/platform/browser'
import {ROUTER_PROVIDERS} from "angular2/router"
import {AppComponent} from './app.component'

app.component.ts

import {Component} from 'angular2/core';
import {RouteConfig, ROUTER_DIRECTIVES} from 'angular2/router';

@Component({
  selector: 'my-app',
  template: `...`
})
export class AppComponent {
   constructor(_router:Router){}
}

GET EXCEPTION: Cannot resolve all parameters for AppComponent(?). Make sure they all have valid type or annotations.

**Comment by ericmartinezr** [comment]
@PrimeObjects you have to import `Router` too

```
import {Router, RouteConfig, ROUTER_DIRECTIVES} from 'angular2/router';
```

**Comment by PrimeObjects** [comment]
Thank you ericmartinezr
Tried but it does not help.

**Comment by ericmartinezr** [comment]
@PrimeObjects can you move your question to [Gitter's chatroom](https://gitter.im/angular/angular)?  We can help you over there. There is where these kind of questions (or StackOverflow as well) should go.

**Comment by PrimeObjects** [comment]
I know how to reproduce the issue. If I run "npm start" (using the same package.json for angular2 quickstart), it works fine. in the js file, I can see System.register(['angular2/core', 'angular2/router'],
If I use 
"node.exe c:.....\node_modules\typescript\lib\tsc.js -m system C:.....\app\app2.ts", in the generated js file,  became System.register(['angular2/core'])

so do I have to manually install angular router or something?

package.json
{
  "name": "angular2-quickstart",
  "version": "1.0.0",
  "scripts": {
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "lite": "lite-server",
    "start": "concurrent \"npm run tsc:w\" \"npm run lite\" "
  },
  "license": "ISC",
  "dependencies": {
    "angular2": "2.0.0-beta.0",
    "systemjs": "0.19.6",
    "es6-promise": "^3.0.2",
    "es6-shim": "^0.33.3",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.0",
    "zone.js": "0.5.10"
  },
  "devDependencies": {
    "concurrently": "^1.0.0",
    "lite-server": "^1.3.1",
    "typescript": "^1.7.3"
  }
}

**Comment by PrimeObjects** [comment]
need tsconfig.json for unknown reason
