### ISSUE TITLE
ngSwitchDefault exception when using pipes

### ISSUE THREAD

**Issue by NisStrom** [angular/angular#6288]
If there are pipes being used to transform the content inside the ngSwitchDefault, an ex exection is thrown:
The example:

        <div>
                <div style="height:20;padding:10px;">1 = Switch1, 2 = Switch2, else = SwitchDefault</div>
                <input type="number" (input)="name = $event.target.value">
                <div [ngSwitch]="'2'">
                    <div *ngSwitchWhen="'1'" style="padding:10px;">	
                        Switch1
                    </div>
                    
                    <div *ngSwitchWhen="'2'" style="padding:10px;">
                        {{'Switch2'}}
                    </div>
                    
                    <div *ngSwitchDefault  style="padding:10px;">
                        {{'SwitchDefault' | emptyPipe}}
                    </div>
                </div>
  	    </div>

throws the following exception:
EXCEPTION: TypeError: Cannot read property 'constructor' of undefined in ['2' in HelloApp@9:25] 

The problem does not occur inside ngSwitchWhen. We found this issue when using the translate pipe of ng2-translate for translating text contet inside the ngSwitchDefault. It is however not releated to ng2-translate as even an empty pipe like the following produces the same exception:

    import {Pipe, PipeTransform} from 'angular2/core';

    @Pipe({name: 'emptyPipe'})
    export class EmptyPipe implements PipeTransform {
       transform(value) : any {
          return value;
       }
    }

**Comment by ericmartinezr** [comment]
Dup of https://github.com/angular/angular/issues/5169

**Comment by pkozlowski-opensource** [comment]
Thnx @ericmartinezr !
