### ISSUE TITLE
ngOnChanges and Input name are mismatched.

### ISSUE THREAD

**Issue by laco0416** [angular/angular#6289]
The argument of `ngOnChanges` doesn't match to the name of `@Input()` .

example: This code doesn't work well. 
I expect `changes["foo"]`, but actually `changes["_foo"]` is given.

```ts
export class MyElement implements OnChanges{
  
  @Input("foo") _foo = "";
  foo = "";

  ngOnChanges(changes) {
    console.log(changes);
    if(changes["foo"]) {
      this.foo = changes["foo"].currentValue;
    }
  }
}
```

Plunker: http://plnkr.co/edit/eiusxhNnWX0nOTPah7ct?p=preview

And, I think `@Input` and `changes` should have same key.
I want to know whether or not this is a bug.

**Comment by pe8ter** [comment]
The string argument to the property decorator `@Input("foo")` defines the name for making components appearing in templates. See the docs:

https://angular.io/docs/ts/latest/api/core/Input-var.html

The key should be the name of the property `_foo` as you're seeing.

**Comment by pkozlowski-opensource** [comment]
@pe8ter explanation is spot-on!
