### ISSUE TITLE
Angular2 template syntax odd behaviour

### ISSUE THREAD

**Issue by tbragaf** [angular/angular#6290]
Hi all!

How am I supposed to change the value of an inputbox?

I figured out 3 ways to do so, but it seems there's some inconsistency:
1. value="{{value}}"
2. [value]="value"
3. [attr.value]="value"

This is the plunkr: https://plnkr.co/edit/7yZqxLmVM22qO5fcN6Dg?p=preview.

The scenario is this:
1. Change the 3 input texts to some value of your choice.
2. Navigate with the button (confirm the navigation works by looking at the header text).
3. Confirm options:
  * Confirm that option 1 works.
  * Confirm that option 2 prints 'undefined' (instead of the placeholder).
  * Confirm that option 3 text did not change.

I understand that interpolating 'undefined' is different than binding the value to undefined (observed in option 1 and option 2), but I believe there is some inconsistency here, or am I missing something?

Best regards,
Tiago Braga

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
