### ISSUE TITLE
[(ngModel)] can't bind to array elements (foo[0])

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#6294]
`<input type="text" [(ngModel)]="values[0]">` won't update model on input's value change:

Plunker: http://plnkr.co/edit/HOdOeLTwYzyNke3DTWOl?p=preview

**Comment by pe8ter** [comment]
Change

```typescript
<input type="text" [(ngModel)]="values[0]"> => {{values}}
```

to

```typescript
<input type="text" [(ngModel)]="values[0]"> => {{values[0]}}
```

Looks like Angular 2 won't bind to an array in its interpolation, just elements within the array. The DOM updates only when bound properties change. My guess is that putting a plain array `{{values}}` in the template doesn't trigger change detection. Imagine an array with thousands of objects. Changing any one of those objects could trigger change detection which would be bad for performance.

**Comment by pkozlowski-opensource** [comment]
Wooooppppps, you are totally right @pe8ter, thank you! I've jumped to (wrong) conclussions. Thnx again.
