### ISSUE TITLE
Static content projection and templates

### ISSUE THREAD

**Issue by vicb** [angular/angular#6303]
This is the current situation as of beta.0

```
@Component({
  selector: 'cmp-a'
  template: `<ng-content select="span"></ng-content>`
})
class AComp {}

<cmp-a>
  <span></span>
  <span *ngIf="exp"></span>
<cmp-a>
```

`<span *ngIf>` is a template and is not projected inside `<ng-content select="span">`.
Only the first `<span>` gets projected.

### Proposal:

Change `<ng-content>` behavior so that templates gets projected when all their child nodes match the selector:

```
  <span *ngIf="exp"></span>

  <!-- or -->

  <template>
    <span></span>
  </template>
```

The template would be projected into `<ng-content select="span">` because the only child node matches the selector. (Text nodes composed of white spaces only are ignored for the purpose of matching the children)

Template matching algorithm details:

Multiple children:

```
  <template>
    <el1></el1>
    <el2></el2>
  </template>
```

`<ng-content select="el1">` would generate an error because some of the template children are selected but not all.

To project the template, all child nodes have to be selected. `<ng-content select="el1, el2">` would project the template.

Nested templates:

```
  <template>
    <el1></el1>
    <template>
      <el2></el2>
    </template>
  </template>
```

`<ng-content select="el1, el2">` is required to project the template (ie we descend into nested templates)

refs:
- static content projection [design doc](https://docs.google.com/document/d/1BXUFVpImyWN7ynyPKehAesctP0UJTaDYbDTNVkarSeQ/edit#heading=h.jq54stmcafin) as currently implemented,

**Comment by fenduru** [comment]
> <ng-content select="el1"> would generate an error because some of the template children are selected but not all.

I'm not necessarily sure that an error would be correct here - though I'm not sure what better behavior would be. I think it would be weird for the following templates to behave differently:

```html
<template [ngIf]="foo">
  <el1>...</el1>
  <el2>...</el2>
</template>
```

```html
<template [ngIf]="foo">
  <el1>...</el1>
</template>
<template [ngIf]="foo">
  <el2>...</el2>
</template>
```

**Comment by fenduru** [comment]
I also think it is important to consider the fact that the person writing the `<ng-content select="...">` may be different from the person writing the template with `ngIf` in it. Having the two templates shown above behave differently forces my abstractions (as a reusable component author) to be leaky
