### ISSUE TITLE
Wildcard Route doesn't get recognized

### ISSUE THREAD

**Issue by ethanve** [angular/angular#6305]
I have a defined route like so:

     $router.config([
        { path: 'foo/bar/*baz', component: 'Foo', name: 'foo' }
    ]);

And when I programmatically `$router.navigate(['foo', { baz: '1/2/3' }])` the wildcard portion of the url only shows the first part (in this case: `/1`)

What I believe that's happening is that the PathRecognizer isn't capturing the full wildcard and that the bug is in `path_recognizer.ts` in the `recognize` method

**Comment by zoechi** [comment]
Did you try a string instead of a number? There was a bug report recently that a number is misinterpreted. Might not be related though.

**Comment by ethanve** [comment]
Just tried it without numbers and it still causes the same issue.

**Comment by davidreher** [comment]
I am having the same issue here :+1: :/

**Comment by davidreher** [comment]
The problem is, that the `urlPath` is [constructed from the `captured` elements](https://github.com/angular/angular/blob/master/modules/angular2/src/router/path_recognizer.ts#L236). In the [`segment instanceof StarSegment` branch](https://github.com/angular/angular/blob/master/modules/angular2/src/router/path_recognizer.ts#L213-L218) we are breaking the loop, so captured does not contain all the necessary parts (only the first part of the StarSegment).

What we did for now is replacing [lines 211-218](https://github.com/angular/angular/blob/master/modules/angular2/src/router/path_recognizer.ts#L211-L218) with the following:
```javascript
  // the star segment consumes all of the remaining URL, including matrix params
  if (segment instanceof StarSegment) {
    const currentSegmentString = currentSegment.toString();
    positionalParams[segment.name] = currentSegmentString;
    captured.push(currentSegmentString);
    nextSegment = null;
    break;
  }

  captured.push(currentSegment.path);
```

If this is really a bug and not working as expected, I might work on a pull request ...

**Comment by davidreher** [comment]
So, after having slept about this I don't really see, why we are building the url from the `catpured` array at all ... I think it would be better to do the following:
```diff
diff --git a/modules/angular2/src/router/path_recognizer.ts b/modules/angular2/src/router/path_recognizer.ts
index 263ae94..788843f 100644
--- a/modules/angular2/src/router/path_recognizer.ts
+++ b/modules/angular2/src/router/path_recognizer.ts
@@ -197,7 +197,6 @@ export class PathRecognizer {
     var nextSegment = beginningSegment;
     var currentSegment: Url;
     var positionalParams = {};
-    var captured = [];
 
     for (var i = 0; i < this._segments.length; i += 1) {
       var segment = this._segments[i];
@@ -208,8 +207,6 @@ export class PathRecognizer {
       }
 
       if (isPresent(currentSegment)) {
-        captured.push(currentSegment.path);
-
         // the star segment consumes all of the remaining URL, including matrix params
         if (segment instanceof StarSegment) {
           positionalParams[segment.name] = currentSegment.toString();
@@ -233,7 +230,7 @@ export class PathRecognizer {
       return null;
     }
 
-    var urlPath = captured.join('/');
+    var urlPath = beginningSegment.toString();
 
     var auxiliary;
     var urlParams;
```

**Comment by davidreher** [comment]
@btford what do you think? Is there any reason why the `urlPath` is built the way it is now?

**Comment by ethanve** [comment]
It does seem like there is no need for it

**Comment by davidreher** [comment]
Of course there is a need for it, but I think most of the Google guys are just busy atm ...

**Comment by waeljammal** [comment]
+1 having this issue as well.

**Comment by vicb** [comment]
obsolete - former router
