### ISSUE TITLE
<ng-content select="..."> incompatible with ngIf/other structural directives

### ISSUE THREAD

**Issue by fenduru** [angular/angular#6308]
When using the `select` option of ng-content, if the consumer of my directive wishes to put an `ngIf` on the component I'm selecting for, the select does not find the component since it ends up inside of a `<template ngIf>`

http://plnkr.co/edit/EhV5i9rrXcThCZLZu64P?p=preview

What is the idiomatic way of supporting optional child components if you need the `select` behavior?

**Comment by zoechi** [comment]
You could just hide it instead of using `ngIf` (`[hidden]=true`)

**Comment by zoechi** [comment]
dup of #6303

**Comment by fenduru** [comment]
Closing in favor of #6303
