### ISSUE TITLE
Add support for setting a default Component role

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#631]
Component configuration should include an option for the default element role.

```js
@Component({
  selector: 'md-checkbox',
  role: 'checkbox'
})
class MdCheckbox{ /* ... */ }
```

**Comment by pkozlowski-opensource** [comment]
This is interesting, haven't thought about specifying role on the component level, which somehow makes sense. For now I've sent a PR to bind to the "role" attribute in templates #630, not sure if both the idea from this issue and template bindings are needed (I guess so).

**Comment by jelbourn** [comment]
Yeah, both are needed. #630 is about letting you *bind* to the role, but this is saying that a given Component should always have role X by default.

**Comment by mhevery** [comment]
Makes sense to me. +1

**Comment by pkozlowski-opensource** [comment]
I can take a stab at it. Before jumping to the impl, though, what is the advantage of expressing role in JS as opposed to having it as an attribute in a template? I guess it makes things easier if there are multiple templates, but is there more to it?

**Comment by jelbourn** [comment]
If you want to make a Component that always has a particular role, it would be annoying boilerplate to have to specify the role every time, like:
```html
<md-button role="button">Go!</md-button>
vs.
<md-button>Go!</md-button>
```
Obviously this Component will always be a `role="button"`, so the component author can save the user that boilerplate.

**Comment by pkozlowski-opensource** [comment]
@jelbourn sure, but what I meant is moving the `role` attribute to the template of a component. But now I realise it would be probably a wrong place, since the role would be marked on an element that is a child of the `md-button` element, right?

**Comment by jelbourn** [comment]
@pkozlowski-opensource That's right, and that would (potentially) be inside of the shadow DOM and would be invisible to screen readers.

**Comment by pkozlowski-opensource** [comment]
@jelbourn we should be fine with screen readers, seems like those can "break through" the shadow root barrier: http://substantial.com/blog/2014/02/05/accessibility-and-the-shadow-dom/

@mhevery @rkirov what would be the best place to add this logic? I can special case it in the DirectiveParser step, but maybe it is worth to have a dedicated pipeline step for this?

**Comment by mhevery** [comment]
I think this would have to be a compile step. Since you want to update the template so that you don't have to do it on clone.

assume template
```
<div>
  <md-button></md-button>
</div>
```

While compiling the template we would come across `md-button` and we would know that it has a component. We could then see that the component has a `role` and update the element in template. This would be a one time thing resulting in this template:
```
<div>
  <md-button role="button"></md-button>
</div>
```

**Comment by pkozlowski-opensource** [comment]
@mhevery yep, totally agree that this should be a compile step, no reason to do this work on view creation! 

But my question was more: should I create a new, specific compiler step for this or modify the existing one (the best I can think of would be DirectiveParser).

I'm slightly leaning towards creating new step, but don't feel strongly about it, so that is why I'm asking....

**Comment by mhevery** [comment]
I think we should have new `ComponentProcessingStep` as I think there may be other things we may need to do.

The question in mind is that what if there is a decorator which matches on `[role]` then Component adding a role would not trigger such a decorator. But I think I am fine with that.

**Comment by rkirov** [comment]
I agree with Misko.

Note this goes against our design goal for the templates to fully describe what is happening (without going into the annotations), but in this case the developer productivity gains outweigh that.

Also Pawel, make sure to mark the steps that mutate the template nodes vs the ones that just read them. So far only ViewSplitter mutates it, and your step will be the second.

**Comment by pkozlowski-opensource** [comment]
@rkirov @mhevery ok, separate `ComponentProcessingStep` sounds good, thnx for the input.

@rkirov what do you mean exactly by "mark the steps that mutate the template nodes". Is it about "just" documenting it or is there a special flag on `CompileStep`?

**Comment by rkirov** [comment]
Yeah, just add comments.

**Comment by mlaval** [comment]
Is `role` the only attribute in scope? Or should the solution be more generic (aria-* ?) ?

**Comment by mhevery** [comment]
@jelbourn can you comment on: https://github.com/angular/angular/issues/631#issuecomment-75334331

**Comment by pkozlowski-opensource** [comment]
Funny enough, it starts to sound like a place for similar things was previously discussed in [Compiler Macro pass](https://github.com/angular/angular/issues/521)

**Comment by jelbourn** [comment]
@mlaval Role is the only attribute I had in mind becuase I see it being needed very frequently. There are some other aria attributes that could make sense sometimes, though, such as aria-live or aria-atomic. Maybe what we really want to do is just specify a set of static attributes that we want applied to the component element (of which role is one).

**Comment by mhevery** [comment]
:+1 for a set of attributes which should be applied to the component.

**Comment by mlaval** [comment]
Thanks to #1052 , this is doable with `@PropertySetter('attr.role')`. Is it good enough or do we still need the map ?

**Comment by jelbourn** [comment]
@mlaval I think it will be good enough to move forward. There might be another issue in the future about how much boilerplate is involved with `@PropertySetter`

**Comment by mlaval** [comment]
It is true that it can be a lot of boilerplate with `@PropertySetter`, `@EventEmitter`, the future `@Static` if it happens, etc.
We could add some sugar with an option in the directive's configuration, but it will for sure make the annotation more complex.

@mhevery any thoughts ?

**Comment by jelbourn** [comment]
I agree that we absolutely need some way to cut down on the boilerplate of the sheer number of things a component needs to inject. For example, the material grid-list tile would be something like
```js
class MdGridTile {
  constructor(
      @Parent() gridList: MdGridList,
      @PropertySetter('style.height') heightSetter: Function,
      @PropertySetter('style.width') widthSetter: Function,
      @PropertySetter('style.top') topSetter: Function,
      @PropertySetter('style.left') leftSetter: Function,
      @PropertySetter('style.marginTop') marginTopSetter: Function,
      @PropertySetter('style.paddingTop') paddingTopSetter: Function,
      @PropertySetter('role') roleSetter: Function
      ) {
    this.gridList = gridList;
    this.heightSetter = heightSetter;
    this.widthSetter = widthSetter;
    this.topSetter = topSetter;
    this.leftSetter = leftSetter;
    this.marginTopSetter = marginTopSetter;
    this.paddingTopSetter = paddingTopSetter;
    roleSetter('listitem');
    // Now I can actually start doing things.
  }
}
```

**Comment by mhevery** [comment]
Can't you just inject:
```
class MdGridTile {
  constructor(
      @Parent() gridList: MdGridList,
      @PropertySetter('style') styleSetter: Function,
      @PropertySetter('role') roleSetter: Function
      ) {
    this.gridList = gridList;
    roleSetter('listitem');
    // Now I can actually start doing things.
  }
}
```

**Comment by jelbourn** [comment]
This was filed before you could do `@PropertySetter('attr.role')`. Closing now.
