### ISSUE TITLE
Tabs example from homepage breaks when nesting tabs

### ISSUE THREAD

**Issue by fenduru** [angular/angular#6310]
http://plnkr.co/edit/GNYqQROgM7DQ4ly9G8Xz?p=preview

This is a slight modification of the https://angular.io/ example tabs implementation to include a nested <ui-tabs> element. When the first tab is selected, the deeply nested tab is found by the QueryList of the outer <ui-tabs>, which causes an extra/incorrect tab to appear in the outer tabs.

This can be avoided by creating a separate component that encapsulates the extra <ui-tabs>, but this feels like overkill

**Comment by bekos** [comment]
This is probably an issue because `ui-pane` is attached to a `<template>` element. Even with explicit `{descendants: false}`, parent `ui-tabs` keeps selecting all children panes.

**Comment by bekos** [comment]
@fenduru I believe with latest RC this now fixed.
