### ISSUE TITLE
EventEmitter should deliver events sync

### ISSUE THREAD

**Issue by robwormald** [angular/angular#6311]
Ref: https://github.com/angular/angular/issues/5808 https://github.com/angular/angular/issues/6287

Currently we're overriding the JS EventEmitter's subscribe function with a timeout, this should be removed, which will default to sync delivery.  Dart Streams are async by default, and we'll need to force them to sync for this case.

**Comment by laco0416** [comment]
If I want to emit data as async, how should I do?

**Comment by robwormald** [comment]
for what use case? if you're doing something outside of using `EventEmitter` for emitting angular component events, you should be using Rx's Subject/AsyncSubject directly.

**Comment by laco0416** [comment]
OK, maybe I understood. It means `@Output` will be sync always, right?

**Comment by robwormald** [comment]
right. sync between the component and the framework - you could of course do something async before you emit() such an event.

**Comment by laco0416** [comment]
Thanks Rob. I agree this. :smile:

**Comment by robwormald** [comment]
:+1:

**Comment by JurajMlich** [comment]
When is this issue going to be fixed?

**Comment by JurajMlich** [comment]
Can you fix it as soon as possible? It makes all inputs unusable...

**Comment by JurajMlich** [comment]
@robwormald can you please answer, when will it be fixed? we are building an application and this issue is blocking it from using... (since it causes that inputs / textareas with ngModel work incorrectly)

**Comment by radek-holy** [comment]
If you have a workaround or a simple patch that I can apply before the pull request is merged I'd be very grateful. This is a real pain in my case. It bites me every now and then.

**Comment by ericmartinezr** [comment]
@radek-holy just pass `false` as parameter.

```
@Output() event : EventEmitter<any> = new EventEmitter(false);
```

**Comment by radek-holy** [comment]
All right, that was... stupid... obvious... I feel embarrassed. Sorry and thanks.
FTR, I guess the workaround does not solve the issues referenced above but it's enough for me now.

**Comment by halukkaramete** [comment]
@Eric, I would like to deploy your solution. `@Output() event : EventEmitter<any> = new EventEmitter(false);` but where does this go in? I've posed my question on [this stackoverflow link](https://stackoverflow.com/questions/49787872/deep-troubling-situation-with-angular-5-and-slow-typing-into-input-boxes) and this very issue you guys talked about here is just killing me.
