### ISSUE TITLE
Add `forEach` to QueryList

### ISSUE THREAD

**Issue by Alxandr** [angular/angular#6314]
Currently, the "best" way to loop through the result of a QueryList (as done in the ui-tabs sample at http://plnkr.co/edit/9E7T5XyLvn0SNQTOrVrJ?p=preview) is to use `.toArray().forEach()`. Here `.toArray()` copies the original array before allowing you to iterate through it. At least that's what I'm seeing when I'm running through the code.

Also, since it supports `map`, `reduce` and `filter` already, I think `forEach` should generally be available too.

**Comment by laco0416** [comment]
:+1:

**Comment by pkozlowski-opensource** [comment]
This was solved by e7470d557df0400a812d84551524970cb5f12eee
