### ISSUE TITLE
Getting 404 error while refreshing browser.

### ISSUE THREAD

**Issue by sagar-mindstix** [angular/angular#6315]
Hi ,

I have created a sample app using @RouteConfig and it working fine, See the url changes and view added according to configuration. but when I am refreshing page its shown 404 error :( .

**Comment by robwormald** [comment]
You have to configure this on your server, as angular has no chance to intercept the request. Something like this works for node https://ninja.sg/spa-router-fallback/ or you can configure the same thing in your backend of choice.

**Comment by sagar-mindstix** [comment]
Thanks for quick response.

I am using webStrom IDE to build and run the angularJS2 APP.

**Comment by cghislai** [comment]
You have two options:
- configure you web server (I guess the one provided by your IDE) to serve index.html whenever a page in your context path is requested
- configure angular to use the HashLocationStrategy, so that you actually won't leave the index page.
