### ISSUE TITLE
HTTP_PROVIDERS is undefined

### ISSUE THREAD

**Issue by chibisov** [angular/angular#6320]
My bootstrap file:

```typescript
import {bootstrap} from 'angular2/platform/browser';
import {ROUTER_PROVIDERS} from 'angular2/router';
import {HTTP_PROVIDERS} from 'angular2/http';

import {AppComponent} from './app.component';


bootstrap(
    AppComponent, 
    [
        ROUTER_PROVIDERS,
        HTTP_PROVIDERS,
    ]
)
```

I have an error `TypeError: Cannot read property 'toString' of undefined`. When I'm executing `console.log(HTTP_PROVIDERS)` I get `undefined`. What am I doing wrong?

**Comment by antonmoiseev** [comment]
`angular2/http` module should be added to the index.html as a separate bundle. Likely you need to add following line:

```html
<script src="node_modules/angular2/bundles/http.dev.js"></script>
```

**Comment by chibisov** [comment]
My bad, forgot about script tag. Thank you!
