### ISSUE TITLE
Template parser throws error when using custom properties for component

### ISSUE THREAD

**Issue by smalluban** [angular/angular#6322]
As far I know, component selector can be any proper css selector. But, usually it is just an element tag name. I've created some tests of how Angular is pushing values of custom properties to elements. And when I try to set something like this:

```
<h1 [customName]="'custom name'"></h1>
```

Parser throws an error: **Can't bind to 'customName' since it isn't a known native property**
Ok. I understand that we can not set custom properties which are not in prototype chain of native element. 

If I change element to some custom tag name, it works:

```
<hello-world [customName]="'custom name'"></hello-word>
```

I think this is done like that because of web components lifecycle, but also for utilizing Components. However, as I mentioned above, Components can use other css selector than tag name. For example we can create component with that decorator:

```
@Component({
  selector: "#hello-world"
})
````

Then we can use any tag with proper id. This can be also native element. If we do so, parser throws an error:

```
Can't bind to 'customName' since it isn't a known native property ("
    <div id="hello-world" [ERROR ->][customName]="'custom name'"></div>
```

This is really confusing. If components should be created as custom tags, `selector` should be used as tag name, not css selector. If I can create component with css selector, then parser should not throws error for custom properties with native elements.

[Link to "working" example](http://embed.plnkr.co/U4MyECFNtpLxC85Q754G/).

**Comment by PascalPrecht** [comment]
@smalluban That's an interesting discovery. I'm not sure how far CSS selectors are supported, but those are more for building **Directives**, which can have attribute selectors.

Whenever you build a **component**, the selector has to be a tag name, since that's going to be the host element Angular will look for. In other words: `selector: "#hello-world"` is not an appropriate use case here.

You either build a component, which is always an element with a tag (unless loaded dynamically), or you build a directive that can match multiple attribute selectors.

**Comment by smalluban** [comment]
I tried once again, and I think I was wrong. `selector` works only with tag name and attribute name. Parser throws error because Angular does not reconginze component. When I changed `selector` to use attribute like `<div hello-word></div>` It stops throwing error for custom property.

**Comment by PascalPrecht** [comment]
Cool, so this can be closed then?

**Comment by smalluban** [comment]
Yes. There is no documentation yet for `selector` (https://angular.io/docs/ts/latest/api/core/ComponentMetadata-class.html), so I think this will be documented and the problem will be gone :)

**Comment by xsilen** [comment]
help me a lot
