### ISSUE TITLE
[prodMode] Is there any simple way to disable log for production environment? 

### ISSUE THREAD

**Issue by wkwiatek** [angular/angular#6324]
Currently there is a log message depending on `enableProdMode()` function being called which ends up with following log in prod mode: 
```
Angular 2 is running in the production mode. Call enableDevMode() to enable the development mode.
```
How can I prevent Angular from logging such a message?

**Comment by zoechi** [comment]
Looks like a dup of #6096

**Comment by wkwiatek** [comment]
It's not really the same. I'd like to have a clear console in prod mode and the issue you refer to is about misleading text.

**Comment by michalstepien** [comment]
`import {enableProdMode} from "angular2/core";
enableProdMode();`
Please close.

**Comment by wkwiatek** [comment]
It’s outdated. Previously there was no way to remove that.

**Comment by jdang67** [comment]
Still does not work. I  enableProdMode but I can see the same log, debug  in my debug tool.  
Can you check again or show us how to turn of the debug output in production mode?

**Comment by davidzast** [comment]
This is my workarround, i hope it helps somebody.

In the maint.ts file use this
`if (environment.production) {
    enableProdMode();
    console.log = function (a, b, c, d, e, f, g, h, i, j, k, l) {
        return false;
    }
}`

**Comment by mzohaibqc** [comment]
@davideast IMO, if we are not using arguments then we don't need to pass `a,b,c ...`.
```
if (environment.production) { 
  enableProdMode();
  console.log = function () { return false; }
}
```
