### ISSUE TITLE
(Simple?) Feature Request: Multiple template options for a @Component and Class

### ISSUE THREAD

**Issue by leonaburime** [angular/angular#6328]
Hello, I am new to this so please forgive any etiquette mistakes.
I was wondering if it was possible to have a feature where a component could have a different template based on whichever type I decide to implement. For instance

```javascript
@Component({
    selector: 'some-selector',
    templateOptions: {
    	'line-chart':`
    		<div> HTML for a {{line}} chart  </div>
    	`,
    	'pie-chart':'./templates/piechart.html',
        default:'line-chart',
   }
})
export class Charts{
	createLineChart(options){
		//now I can render the chart and set the line-chart variables 
	}
	createPieChart(options){
		//now I can render the chart and set the pie-chart variables 
	}
}
```
and in the top-level app.component.ts code I merely select which template I want to render by
```javascript
<some-selector ^template='line-chart'>   </some-selector>
```

I believe this is much more flexible and still object oriented. Im running into an issue where I would like to create **ONE** component class that gets data related to something(say financial trends) but want to have the option of displaying it several different ways(over 6 months or as percentages) and still be able to manipulate the data sometime in the future. Having to create all these different components is not at all efficient

**Comment by zoechi** [comment]
You can use `ngSwitch`. 
There are plans to support multiple views (for different renderers or media queries)  no idea if your use-case is pla be supported this way.

**Comment by leonaburime** [comment]
Thanks @zoechi.  You seem to know a lot about Angular 2.0. How hard would it be to implement something like this? Would I be able to do it using a Pull Request?

**Comment by zoechi** [comment]
Actually, I'm just learning Angular2. Pull Request for what? Support for different views? There is an issue about this topic already. If you want to chime in, discuss with the architects first what and how it should be done.  I think there is enough functionality for your use case already though(`ngSwitch`).

**Comment by vicb** [comment]
This is something we are thinking about. Nothing concrete for now.

Closing as not actionable

**Comment by m98** [comment]
@vicb Any update on this?

Just as you said you were thinking about it, and I'm just curious to know is there anything for this yet?

**Comment by asantoli** [comment]
Seeing if there was any movement on this request? Is there a way to dynamically pull in a template for a Component? Im currently using Angular 4.3.4.

Thanks
