### ISSUE TITLE
Missing support for Emacs

### ISSUE THREAD

**Issue by sakshamsharma** [angular/angular#6329]
I've not been able to find some proper plugin to work with Emacs for Angular2. The existing one is for v1.
It'd be great if someone who's been using Angular2 with Emacs can share his config (etc).
In case there's nothing, when can we expect to see something? Is some package in progress?

**Comment by pkozlowski-opensource** [comment]
We are not actively working on any editors / editor plugins: all those tools extensions happened / are happening outside of Angular core. I'm sure that many bright folks are working on those extensions as we speak! 

We are very much interested in the vibrant ecosystem and rich tooling so if anyone implementing those tools extensions is hitting any road-blocks, please do let us know by opening issues with concrete problems / suggestions. 

Closing this one as it is not actionable as-is.
