### ISSUE TITLE
Add support for flag attributes in components

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#633]
There should be a way, from a Component, to check whether some attributes were provided. For example, if the end user has:
```html
<!-- Attribute specified with no value. -->
<scary-button no-scream>Boo!</scary-button>

<!-- Attribute not specified -->
<scary-button>Ahh!</scary-button>
```
The Component should be able to know the difference between an attribute being present and empty (top example) vs. an attribute being absent (bottom example).

**Comment by pkozlowski-opensource** [comment]
@jelbourn wouldn't proposal from #622 sufficient to cover your use-case? With that proposal one could do:

```javascript
ComponentDecorator({
    selector: 'scary-button'
})
class ScaryButton {
    constructor(@Static('no-scream') noScream:string){
        //noScream gets null when an attribute is not present here
    }
}
```

**Comment by jelbourn** [comment]
@pkozlowski-opensource Yes, this issue is really a detail/requirement about how reading static attributes is implemented.

**Comment by mhevery** [comment]
closing since it is a duplicate from #622
