### ISSUE TITLE
Sourcemap displays some errors, but works fine !? 

### ISSUE THREAD

**Issue by JLGouwy** [angular/angular#6330]
Hello everyone, 

Today, I wanted to watch closer Angular 2. So, I began by trying the quickstart in TypeScript.
So, I had to configure my IDE - PhpStorm. 

Now, the quickstart is finished, and is running well. But, still a problem. When the compiler is transpiling, there is few errors and i don't understand why. 

error TS1148 Cannot compile modules unless the '--module' flag is provided.
error TS2307 Cannot find module 'angular2/core'.
error TS1219 error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Specify '--experimentalDecorators' to remove this warning.

I use the tsconfig.json from angular.

I can go on to code, but this is annoying to see red errors...

Thanks in advance,

![capture d ecran 2016-01-07 a 18 08 29](https://cloud.githubusercontent.com/assets/3371103/12181647/d2368e52-b583-11e5-8a3f-1a8cbfc06752.jpg)
![capture d ecran 2016-01-07 a 18 07 05](https://cloud.githubusercontent.com/assets/3371103/12181648/d238e4a4-b583-11e5-9da5-38903e4b23ab.jpg)
![capture d ecran 2016-01-07 a 17 58 45](https://cloud.githubusercontent.com/assets/3371103/12181650/d23fe7b8-b583-11e5-8b12-8c46693a5971.jpg)
![capture d ecran 2016-01-07 a 17 58 29](https://cloud.githubusercontent.com/assets/3371103/12181649/d23fc06c-b583-11e5-8277-9ff15cd17b66.jpg)

**Comment by pkozlowski-opensource** [comment]
This sounds like a support request and as such should be redirected to an appropriate support channel: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
