### ISSUE TITLE
angular route does not load AsyncRoute when i use location.go()

### ISSUE THREAD

**Issue by mkrishna4u** [angular/angular#6331]
angular route does not load AsyncRoute for securitymgmt when i use location.go("/admin/securitymgmt") or direct url on web browser like 
http://host/myapp/#/admin/securitymgmt

But when i click on admin link (bind with routerLink) then it loads the AsyncRoute.
As per my understanding it should load the right page even if i specify the full path in 
web browser as mentioned above.

My code snippet is given below for your reference.

Scenario is: 
----------------------- Main component with routing ----------
@Component({
  selector: 'main-dashboard',
  templateUrl: 'app/main-dashboard.html',
  directives: [MainNavbar, ROUTER_DIRECTIVES]
})
@RouteConfig([ 
  new AsyncRoute({
    path: '/admin',
    loader: () => System.import('app/admin/admin').then(m => m.Admin),
    name: 'Admin'
  })
])
export class MainDashboard {
  constructor(router: Router, location: Location) {	
  }  
}
-------------------- Child component of MainDashboard  with routing -----------
@Component({
  selector: 'soii-admin',
  templateUrl: 'app/admin/admin.html',
  directives: [ROUTER_DIRECTIVES]
})
@RouteConfig([ 
  new AsyncRoute({
    path: '/securitymgmt',
    loader: () => System.import('app/admin/security-mgmt/security-mgmt').then(m => m.SecurityMgmt),
    name: 'SecurityMgmt',
	useAsDefault: true
  }),
  new AsyncRoute({
    path: '/systemconfig',
    loader: () => System.import('app/admin/system-config/system-config').then(m => m.SystemConfig),
    name: 'SystemConfig'
  })
])
export class Admin {	
}
-------------------- Child component of Admin --------
@Component({
  selector: 'admin-security-mgmt',
  templateUrl: 'app/admin/security-mgmt/security-mgmt.html',
  directives: []
})
export class SecurityMgmt {

}

**Comment by mkrishna4ua** [comment]
is there any update on it.

**Comment by vicb** [comment]
obsolete - old router
