### ISSUE TITLE
Location and Router inconsistencies (beta.0)

### ISSUE THREAD

**Issue by oliverjanik** [angular/angular#6337]
Forgive my tone, but Location and Router (even though they are in beta) have some serious issues.

Let's say I have a `CarsComponent` that loads up at `/cars` with route name `Cars`.

1. If I do `router.navigate(['Cars', { color: 'blue'}])` I get `/cars;color=blue`
1. if I do `location.go(location.path(), 'color=blue') I get '/cars?color=blue`

Now say I'm at `/cars?color=blue`

1. How do I get query params? Where is location.query()?
1. location.path() returns `/cars?color=blue` with query string, is it intended?
1. When I do `location.go(location.path(), 'make=saab')` I get `/cars?color=blue?make=saab`, surely this is a joke
1. When I navigate off to a completely different route the query parameters stay in the URL! so I get something like `/flowers?color=blue`. Shouldn't the router reset the query string?

I'm on Chrome/Win10 at beta.0

The use-case I'm trying to solve is have URL reflect state in the UI e.g. filter string from a search box.

Rant:
I think Router deserves a lot more attention from angular team. It is a fundamental concept to any SPA and as it stands it is the proverbial weakest link in the chain. I makes me worried after the whole angular-new-router fiasco.

Features I'd love to see:
- Easy inquiry about current route
- Handling query params with the option to not reload the component when they're modified
- Support for navigation pattern where Component is not destroyed when you navigate off and is preserved in stack and readily available for back() without reloading.

**Comment by michaelbromley** [comment]
I have been scouring the docs and issues for the past hour trying to find the solution to an issue highlighted above, namely:

I have a paginated list, and I want to store the current page as a query param (`customers?page=3`). I would guess that this is a very common use-case.

I cannot find any way to do this currently. The closest I get is:

```TypeScript
this.router.navigate(['CustomersCmp', { page: this.currentPage }]);
```

However, this causes a reload of the entire component so it is not a viable solution.

The first two features desired by the poster above - easy enquiry about the current route and straightforward handling of query params (like ng1's $location.search()) are really needed from my experience working with ng2 thus far.

**Comment by brandonroberts** [comment]
@michaelbromley you can accomplish this with the router lifecycle hooks, specifically the reuse hooks.

See example: http://plnkr.co/edit/Z3ZBINGvq95di9pBRk6W?p=preview

**Comment by michaelbromley** [comment]
@brandonroberts Thanks - really helpful example there. I used the `canReuse` and `onReuse` lifecycle hooks to achieve what I want.

**Comment by CaptainCodeman** [comment]
In case anyone finds this useful, here's the pattern I found works well, it removes the page number when it's 1 (like the ui-router default param)

The route is ```{ path: '/topic/:id/:slug', name: 'Topic', component: TopicDetailComponent }```

```
export class TopicDetailComponent implements CanReuse, OnActivate {
    topic:Topic;
    page:number;
    size:number;
    offset:number;
    end:number;

    constructor(private topicSvc:TopicService, private router:Router) { }

    routerCanReuse(next: ComponentInstruction, prev: ComponentInstruction) { return true; }
    routerOnActivate(next: ComponentInstruction, prev: ComponentInstruction) {
        this.load(next);
    }
    routerOnReuse(next: ComponentInstruction, prev: ComponentInstruction) {
        this.load(next);
    }

    load(next: ComponentInstruction) {
        var id = parseInt(next.params['id']);
        this.page = parseInt(next.params['page'] || 1);
        this.size = parseInt(next.params['size'] || 10);
        this.offset = this.size * (this.page - 1);
        this.end = this.offset + this.size;

        // topic contains all posts as children so only reload when topic changes
        // use offset + end to slice in view (alternative: load page of data here)
        if (this.topic !== undefined && this.topic.id === id) {
            return;
        }

        this.topicSvc.byId(id).subscribe(topic => {
            this.topic = topic;
        });
    }

    // methods called by view to set page no or page size
    setPage(page:number) {
        this.setParams(page, this.size);
    }
    setSize(size:number) {
        var page = Math.floor(this.offset / size) + 1;
        this.setParams(page, size);
    }

    // updates URL and causes reuse (to update params) by router
    setParams(page:number, size:number) {
        var params = { id: this.topic.id, slug: this.topic.slug };
        // only add non-default values
        if (page !== 1) {
            params['page'] = page;
        }
        if (size !== 10) {
            params['size'] = size;
        }
        this.router.navigate(['Topic', params])
    }
}
```

**Comment by oliverjanik** [comment]
Thanks for the CanReuse pointer. How do I force router to use query params instead of matrix params?

**Comment by brandonroberts** [comment]
@oliverjanik I don't think you can force it use query params. It uses query params on root level routes only, so if you don't specific them as named parameters, they will be query parameters.

**Comment by oliverjanik** [comment]
it gives me matrix parameters if they're not route parameters. I'd like to use query parameters.

**Comment by brandonroberts** [comment]
@oliverjanik are they child routes? Can you provide an example route config?

**Comment by oliverjanik** [comment]
Yes they are. Why are child routes different than root router?

**Comment by CaptainCodeman** [comment]
Maybe this is related to the issue you are having or it could be a separate issue but after adding a few more filtering parameters to the example I posted above I'm starting to see inconsistencies between navigating with the router and refreshing the page.

Maybe my expectations are wrong but it seems pretty fundamental - choices are serialized to the URL and the URL change then causes a route navigation and the routed component uses the values from the route as parameters. The same parameters should be used regardless of whether it is navigation happening within the site or the first page load (or a page refresh).

A page refresh consistently picks up the params but navigating within the app doesn't always even though the URL displayed is exactly the same in both cases. The only way I can make it work consistently is to try and bypass the router as much as possible which means converting parameters to instructions, using toUrlPath and toUrlQuery and then location.go with those.

I share your concern that the router is the weakest link right now - it seems anytime I step outside the basic / simple example type usage I start running into issues and it doesn't inspire confidence although I'm liking Angular 2 overall.

**Comment by brandonroberts** [comment]
@oliverjanik they are different so that each route can have its own parameters with no collisions. So you're parent route could have an optional route param named :id and your child route could have a optional param named :id and they would be independent of each other.

**Comment by oliverjanik** [comment]
@brandonroberts So you're saying there's no way to have a route like this:

```
/cars/:carId/parts?material=metal
```

Because it's a child route it will use matrix parameters?

Correct?

**Comment by brandonroberts** [comment]
@oliverjanik yes, you can do a route like that. You just set your query parameters on your root route.

```js
@RouteConfig([
    { path: '/cars/:id/...', name: 'Cars', component: Cars }
])
class App {}

@RouteConfig([
    { path: '/parts', name: 'Parts', component: Parts }
])
class Cars {}

class Parts {}
```

Then your route link needs to look like this
```html
    <a [routerLink]="['Cars', {carId: 12345, material: 'metal', 'Parts']">Car Parts</a>
```
And it will produce: /cars/:carId/parts?material=metal

Matrix parameters let you do something like

```html
    <a [routerLink]="['Cars', {carId: 12345, material: 'metal', 'Parts', {material: 'silver'}]">Car Parts</a>
```

Which will produce: /cars/12345/parts;metal=silver?material=metal

Cars has its own parameters, which include what we consider "normal" query parameters. (?name=value)
Parts has its own parameters, its query parameters are represented as matrix parameters.

**Comment by oliverjanik** [comment]
Thanks for that bit of wisdom. Honestly, I though I think it violates the principle of least surprise. I guess it just need really good docs.



While you're here, how do I setup a child route without an intermediate component? 

Parent component has: 
```
{ path: '/flowers/...', name: 'Flowers', component: FlowersComponent },
```

FlowersComopnent has:

```
{ path: '/new', name: 'NewFlower', component: FlowerBuilderComponent },
{ path: '/:flowerId', name: 'Flower', component: FlowerComponent }
```

Now I want Flowers component to also handle `/flowers` path, how do I do that? The only way I got it  done was to define an intermediate component that handles routing and has yet another route-outlet. Like so:

```
Parent:
{ path: '/flowers/...', name: 'Flowers', component: FlowersRoot },

FlowersRoot:
{ path: '/', name: 'FlowerList', component: FlowersComponent },
{ path: '/new', name: 'NewFlower', component: FlowerBuilderComponent },
{ path: '/:flowerId', name: 'Flower', component: FlowerComponent }
```

Is this the recommended approach?

**Comment by brandonroberts** [comment]
@oliverjanik you're right about the docs. I think query/matrix parameters are covered in the developer guide for routing though. As far as the routing question, that is the recommended approach. Nested routes have to eventually lead to a non-nested route.

I think this is a different approach than something like ui-router, which allows you to have an open-ended nested route.

**Comment by oliverjanik** [comment]
Seems a bit wasteful, this is quite common scenario in my projects. 

It is quite odd how `/` is considered a sibling route to `/new` or `/:flowerId` when it's clearly not.

Any reason why triple dot is needed at all?

**Comment by brandonroberts** [comment]
@oliverjanik the triple dot is needed to tell the router that the component has child routes so it will go and configure them.

`/` and `/flowerId` can be siblings because of what the router calls 'specificity'. Since /new is defined as a route, its more specific than /:flowerId. Its what allows you to have multiple route paths that are visually similar but have different levels of priority. 

If you wanted the FlowerComponent to handle a route with or without a flowerId, you'd have to make it optional and not part of the url path.
 
You can set a default route to be the default chosen for the nested outlet. Just add `useAsDefault: true` to the desired default route.

```
{ path: '/', useAsDefault: true },
{ path: '/new', name: 'NewFlower', component: FlowerBuilderComponent },
{ path: '/:flowerId', name: 'Flower', component: FlowerComponent }
```

**Comment by brandonroberts** [comment]
@oliverjanik after some digging it is possible to have one component that handles both situations. Basically you use the wildcard param. In the routes below, anything that doesn't match /new(or any other child routes you specify) will be treated as the flowerId param for the flower route. That way you don't have to create an empty component just to have a route for `/` and `/:flowerId`. And you can still use route link to it and provide a flowerId as normal.

```
    { path: '/*flowerId', component: FlowerComponent, name: 'Flower', useAsDefault: true },
    { path: '/new', name: 'NewFlower', component: FlowerBuilderComponent }
```

Example: http://plnkr.co/edit/iPnDspA3sTkKTFMtdD29?p=preview

**Comment by CaptainCodeman** [comment]
Does * signify "match all" as with many other routers? If so that would only work for a single parameter (it may not see different path segments).

**Comment by brandonroberts** [comment]
@CaptainCodeman Yes its a catch all. Anything else after the asterisk is combined into one parameter. It would be a match for that current route config. You could have multiple ones, but they would need different paths like `/new/*wildcard` and `/flower-detail/*wildcard`. Anything else that doesn't match more specifically gets caught by the catch all.

**Comment by oliverjanik** [comment]
Super useful tips. Thanks.

**Comment by oliverjanik** [comment]
Another issue.

With a route like this `'/list1/:id1/list2/:id2'` when I'm at `/list1/10/list2/5` and do:

```
this.router.navigate(['List2', {id2: 5, x: 'search');
```

I get `/list1/:id1/list2/:id2;x=search` which looks good, but router-link-active class gets removed I guess optional parameters mess it up?

Then, when I copy and paste that URL into a browser I get `/list1/:id1/list2;x=search/:id2;x=search`. That is a bit schizophrenic. Looks like router can't decide what to do with extra parameters. And when I navigate to a different :id2 it never clears that.

**Comment by brandonroberts** [comment]
@oliverjanik yes, the component is still required either way. I've filed a bug here for matrix parameters https://github.com/angular/angular/issues/6312. You might need to file another one for that.

**Comment by pkozlowski-opensource** [comment]
There is so much going on in this issue that it is no longer clear what was the root cause and if anything remains to be fixed. If there are still issues to be corrected please open a new issue following the bug report template (most importantly - a minimal reproduce scenario in a plunker).
