### ISSUE TITLE
Extend ES5 Component.Class DSL to support static members and definedProperties

### ISSUE THREAD

**Issue by wardbell** [angular/angular#6339]
Discussed this with Misko today in our review of the ES5 DSL

Currently, the object argument to `Class` can define some-but-not-all of the members of a class.

In particular, we cannot add static class members (`SomeComponent.foo`) nor add definedProperties.

Misko agreed that the syntax should be extended for these two cases.  His sketch looked like this:

```
var MyComponent = ng.core
  .Component(...) 
  .Class({
    constructor: function() {
       this.name = 'Harry'; // public field
       this._baz = 42;  // private backing field for defined property
    },
    doSomething: function() {}, // prototype method
    'static:foo': function () {},  // static class method
    'property:baz': {
        get: function() { return this._baz},
        set: function(value) { this._baz = value},
        // other definedProperty attributes
    }
  }) 
```

We do not have to follow this design literally.

**Comment by trotyl** [comment]
Obsolete since the DSL already removed.

**Comment by splincode** [comment]
@mhevery Is the issue relevant?
