### ISSUE TITLE
Angular metadata decorators should also add annotations

### ISSUE THREAD

**Issue by wardbell** [angular/angular#6342]
Today the decorators add metadata with the reflection API. It is very difficult for most people (who don't know the reflection API) to inspect a directive/component in the debugger and read its metadata. Missing or incorrect metadata is often the reason that something doesn't work.

A2 *also* supports a (legacy?) annotation syntax, e.g.,

```
MyComponent.annotations = [
  new ng.core.Component(...)
];
```

Misko proposed that A2 decorators should continue to add metadata with the reflection API and also ***add the corresponding annotations*** for easier inspection.

We considered the extra memory burden. Misko opined that it would be immaterial.

**All metadata is read-only** ... as a matter of policy. The developer should not suppose that monkey-patching will change anything.

Of course we can't prevent the developer from monkey-patching. Adding visible annotations as proposed here certainly invites monkey-patching (which is much harder to do through the reflection API).

**To minimize mischief, A2 should prefer metadata from the reflection API.** 

I would say that it should always ignore annotation metadata. That won't always be possible because (at least currently), an ES5 developer has the right to define metadata through annotations.

I recommend that A2 should fallback to annotations when (and only when) there is zero reflection metadata. Reflection metadata always wins.

**Comment by martinmcwhorter** [comment]
I would imagine that a tool like batarangle should be able to display the metadata associated with a Class, Method, Property or argument. Metadata aware tooling would eliminate the argument for monkey patching.
