### ISSUE TITLE
Multiple instances of services create

### ISSUE THREAD

**Issue by thesandbender** [angular/angular#6344]
I'm running into an issue with Beta.0 where services are being instantiated twice (easily verified by putting a console.log() into the services constructor).  In some cases, components are being issued different instances of the same service and creates the following problem.

1. MenuComponent and ContentComponent both have StateService as a provider.
2. ContentComponent subscribes to StateService.viewChanged (log viewChanged shows observers set)
3. MenuComponent changes StateService.view (via property set).
4. StateService.view.set saves view and calls viewChanged.next(_view) (log viewChanged shows no observers)
5. Observer(s) aren't called (since there are no observers on this instance).

What's interesting is I have another service that follows the same pattern and while two instances are created, the same instance is always injected so everything works properly.  

It does not seem to be dependent on the number of times a Service is listed as provider, it's always initialized twice.

**Comment by ericmdantas** [comment]
Could you set up a plnkr, please?

**Comment by thesandbender** [comment]
https://embed.plnkr.co/xnVaqaUjZptFntu0yZMD/

Creates three components (Header,Content,Footer) that all use TestService.  Each component gets a different instance of TestService (which is actually slightly different than what I'm seeing locally but still demonstrates the generally issue).

**Comment by thesandbender** [comment]
After re-reading the doc's it's working as it's supposed to with Providers creating a new instance for each component.  Apologies for the misunderstanding.

**Comment by zoechi** [comment]
If you want a single instance, only add it once to providers in `bootstrap(AppComponent, providers: [..., TestService]);` but not at the components.

**Comment by ericmdantas** [comment]
Yeah, if you really want an application-wise singleton, you could do:

```
bootstrap(MyApp, [MyService]);
```

And then *do not* use providers:

```
@Component/Directive({
   ...
   providers: [MyService] // this will give you new instance, 
                          // removing it will give you the same instance in bootstrap
})
```

**Comment by ericmdantas** [comment]
Lol, beat me for 2 seconds :laughing:

**Comment by thesandbender** [comment]
Appreciate the follow up.

**Comment by zoechi** [comment]
@ericcarraway less characters in my post ;-)
