### ISSUE TITLE
Use a Html template instead of an Inline Template in the QuickStart Docs.

### ISSUE THREAD

**Issue by VishalMadhvani** [angular/angular#6346]
Hey!
Just a thought when going through the quick start guide.
I found the inline templates off putting. As a dev it made me really hesitant to follow the guide.
Surely its a best practice to keep html in a html file and we should teach that from the onset?

Thought i'd check if there was any heavy resistance against this before i put together a PR.

(Same goes for CSS.. I assume there is a stylesUrl property.)

**Comment by louisbichard** [comment]
+1

**Comment by MichaelChambers** [comment]
I found brief info on this choice here: https://angular.io/docs/js/latest/guide/forms.html
"Why don't we write the template inline in the component file as we often do elsewhere in the Developer Guide?

There is no “right” answer for all occasions. We like inline templates when they are short. Most form templates won't be short. TypeScript and JavaScript files generally aren't the best place to write (or read) large stretches of HTML and few editors are much help with files that have a mix of HTML and code. We also like short files with a clear and obvious purpose like this one."

**Comment by vishal123** [comment]
Need some help.

I created the app.component.html example file for quickstart but need to generate the corresponding app.component.html.md fragment.
Sounds like its got to do with shredding, but i'm not sure if i need a gulp task that does this, or i need to define somewhere that i want the fragment to be generated.

**Comment by sheldonbarnes** [comment]
+1 I agree on using a template instead of Inline Template:

@Component({
    selector: 'my-app',
    templateUrl: 'template1.html'
})

**Comment by pkozlowski-opensource** [comment]
This belongs to https://github.com/angular/angular.io where documentation is located.
