### ISSUE TITLE
Cannot set property 'reuse' of undefined router issue

### ISSUE THREAD

**Issue by rlegrand** [angular/angular#6348]
Sorry if I do something wrong but it looks like a bug.
I configure the router with a structure like this one:
```
[
	AsyncRoute{
		loader: () => { return new Promise(...); },
		name: 'Slide1',
		path: '/slide1'
	} ,
	Object{
		path: '/',
		redirectTo: ['Slide1']
	}
]
```

This was perfectly working with latest alpha versions, but doesn't work anymore.
I now have the following error:
```
TypeError: Cannot set property 'reuse' of undefined
    at router.ts:227
    at Zone.run (zone.js:115)
    at Zone.run (ng_zone.ts:370)
    at zoneBoundFn (zone.js:88)
```
By debugging a little, it looks like (but I may be wrong) we are trying to set properties which will be resolved later.
This happens when I use the path '/' in order to be redirected to '/slide1'.
Apparently, a **RedirectInstruction** is initialized in [route_registry.ts](https://github.com/angular/angular/blob/master/modules/angular2/src/router/route_registry.ts#L207), line 207, based on an **UnresolvedInstruction**.
And the fields used to initialize the RedirectInstruction are not resolved at that time.
Maybe a promise should be used in order to check the method resolveComponent ended, or something like that?

Here is an example:
https://plnkr.co/edit/aGdzQB1seYeJVEHZeTFG?p=preview

**Comment by vicb** [comment]
obsolete - old router
