### ISSUE TITLE
Dart: measure and monitor todo app size

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#6353]

**Comment by pkozlowski-opensource** [comment]
We need to do this for TS / JS as well. @yjbanov could we sync to make sure that we use the same app / share as much code as possible?

For TS / JS side it would be good to have http module being involved to capture its size (+ RxJS dep size) so the actual store might be different.

**Comment by yjbanov** [comment]
@pkozlowski-opensource, from my discussion with @IgorMinar we want an idiomatic TS and an idiomatic Dart versions, so we don't want to share code. Which shared code were you referring to?

What is "store" in "actual store might be different"?

**Comment by IgorMinar** [comment]
We want to share infrastructure but not application code. By infrastructure I mean scripts to measure and aggregate size and a simple in-memory http storage server.

**Comment by pkozlowski-opensource** [comment]
Obsolete.
