### ISSUE TITLE
Http requests to content-negotiated API endpoints fail on Firefox

### ISSUE THREAD

**Issue by johnrbaur** [angular/angular#6354]
http://plnkr.co/edit/FamsVu1O3MxShrQIyMCy?p=preview

We investigated this and found that the default "Accept" header is different between Firefox and Chrome. 

Chrome defaults to: `"*/*"`
Firefox defaults to: `"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"`

Angular 1 handled this for us. With Angular 2, we're required to modify the headers to request JSON or accept the server default.

**Comment by wjke** [comment]
8 Jan and still not fixed...

**Comment by vicb** [comment]
In what is this an Angular issue ?

What solution do you propose ?

**Comment by johnrbaur** [comment]
I know it's not literally an Angular issue, but one of the great things about frameworks like Angular (or the polyfills underneath them) is how they abstract away many kinds of browser differences. It would be great if the Angular Http service also abstracted away the different browser AJAX behaviors.

My proposed solution is to set the default headers for the Http requests consistently across all browsers. 

The AngularJS default is `Accept: application/json, text/plain, * / *`.  This worked consistently across browsers.
