### ISSUE TITLE
5 Min QuickStart example is not working

### ISSUE THREAD

**Issue by denismp** [angular/angular#6356]
I am getting a TypeErr: p is undefined at angular2-polyfills.js at line 148, col 7.  I tried putting in the line
shim as per the suggestion in the guide, but it made no difference.  The page just says "loading..."

I am running on OS X and I am using the editor Visual Studio Code.

Is there a solution?

index.html

<html>

  <head>
    <title>Angular 2 QuickStart</title>

    
    <script src="node_modules/es6-shim/es6-shim.js"></script>
    <script src="node_modules/angular2/bundles/angular2-polyfills.js"></script>
    <script src="node_modules/systemjs/dist/system.src.js"></script>
    <script src="node_modules/rxjs/bundles/Rx.js"></script>
    <script src="node_modules/angular2/bundles/angular2.dev.js"></script>

    
    <script>
      System.config({
        packages: {        
          app: {
            format: 'register',
            defaultExtension: 'js'
          }
        }
      });
      System.import('app/boot')
            .then(null, console.error.bind(console));
    </script>

  </head>

  
  <body>
    <my-app>Loading...</my-app>
  </body>

</html>

**Comment by ahitchen** [comment]
Can you reproduce the error in a plunker or other tool?
It's a little difficult to tell what might be going on from your code snippet alone.

http://plnkr.co/edit/6MQ5sv6gR7nrhajiMgPU?p=preview is an example that is working.

Cheers.

**Comment by denismp** [comment]
I copied the code from plnkr.co to my local copy and now it works.  The difference is indicated below:

    
    <script src="node_modules/angular2/bundles/angular2-polyfills.js"></script>
    <script src="node_modules/systemjs/dist/system.src.js"></script>
    <script src="node_modules/rxjs/bundles/Rx.js"></script>
    <script src="node_modules/angular2/bundles/angular2.dev.js"></script>
  
    <script src="https://code.angularjs.org/2.0.0-beta.0/angular2-polyfills.js"></script>
    <script src="https://code.angularjs.org/tools/system.js"></script>
    <script src="https://code.angularjs.org/tools/typescript.js"></script>
    <script src="https://code.angularjs.org/2.0.0-beta.0/Rx.js"></script>
    <script src="https://code.angularjs.org/2.0.0-beta.0/angular2.dev.js"></script>

Please note the non-beta vs the beta.  My guess is that the code sample on the tutorial loads code that doesn’t work.

Sincerely,
Denis Putnam

**Comment by stigok** [comment]
Added the complete guide to a repo
https://github.com/stigok/angular2-quickstart

**Comment by michalstepien** [comment]
I think, we can close this.

**Comment by ahitchen** [comment]
I think the typescript update with support for tsconfig in visual studio 2015 fixed this. Cheers.
