### ISSUE TITLE
Dart transformer failures should be displayed in the browser

### ISSUE THREAD

**Issue by jbdeboer** [angular/angular#6357]
During development, using pub, the Dart transformers may fail (e.g. due to syntax errors).

When this failure happens, the error message should be displayed in the browser.

I don't always look at the "pub serve" output; it may also be fairly noisy where the relevant errors have scrolled out of view. But these are errors that are important.

When I refresh the pub serve'd page in my browser, instead of loading the broken app, I should be presented with the error message.

**Comment by zoechi** [comment]
Polymer.dart 0.16 has such an error reporter. I liked that.

**Comment by pkozlowski-opensource** [comment]
Obsolete.
