### ISSUE TITLE
Router problem: On clicking routing link active class is not set for that link (Internet Explorer 11)

### ISSUE THREAD

**Issue by mkrishna4ua** [angular/angular#6360]
I am using Internet Explorer 11 and found that when i click on a link as given below:
< a [routerLink]="['/Admin/SecurityMgmt']">Security Management< / a >

[NOTE] : I added in space in anchor tag so that you can see otherwise it will get converted into link.

then it does not set the class="router-link-active" in anchor tag on first click but when i click again then it sets the class.

On Chrome browser it is working fine.

**Comment by brandonroberts** [comment]
@mkrishna4ua your routerLink is not valid. Its one component/params per segment. It should be 

```html
```

**Comment by varadero** [comment]
@mkrishna4ua Try suggestion in #6140 - move angular-polyfills.js script tag below system.js script tag.

**Comment by mkrishna4ua** [comment]
Moving angular2-polyfills.js and es6-shim.js below system.js script tag did the trick. Thanks
