### ISSUE TITLE
RouterLink attribute is broken in NW.js

### ISSUE THREAD

**Issue by bakatrouble** [angular/angular#6365]
On latest NW.js, [routerLink] attribute does nothing in "a" element. In standalone Chrome/Firefox it correctly sets the href attribute. I've checked both html5 and hash routers. Manual setting href attribute gets my links work though (not tested with html5 router). Maybe, it's somehow connected with Chrome extension environment. I can't also see any errors (at least, HTML parser's ones) in dev console.

If needed, I can provide examples later.

**Comment by vicb** [comment]
obsolete - old router

**Comment by premalatha-bv** [comment]
Am facing same issue. Can I know the fix? 
Am working with latest nwjs version.
