### ISSUE TITLE
Dart: null coalescing operator (??) in template expressions

### ISSUE THREAD

**Issue by mastodon0** [angular/angular#6367]
Dart needs a way to handle null values in template expression like the `||` operator in JS.
The elvis operator (`?.`) doesn't help in situations like `selectedValue != null ? selectedValue : 'no selection'`. 
Since dart got the support for the `??` operator in 1.12, I think it should be a part of template expressions.

**Comment by zoechi** [comment]
+1 
and probably `??=`
https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md#1120---2015-08-31

**Comment by andresaraujo** [comment]
+1
That would be great

**Comment by pkozlowski-opensource** [comment]
Obsolete.
