### ISSUE TITLE
Compile error against typescript@next

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#6368]
We can't currently compile against the latest snapshot of typescript. This hurts our ability to verify fixes from TS team.
We should add a travis variant of build_only which installs typescript@next to keep this from regressing.

**Comment by alexeagle** [comment]
Looks like this is blocked on tslint:
```
[16:06:47] '!build.tools' errored after 1.71 s
[16:06:47] TypeScript error: /Users/alexeagle/Projects/angular/node_modules/tslint/lib/formatters/index.d.ts(2,1): error TS2308: Module "./jsonFormatter" has already exported a member named 'Formatter'. Consider explicitly re-exporting to resolve the ambiguity.
    at Output.getError (/Users/alexeagle/Projects/angular/node_modules/gulp-typescript/release/output.js:208:19)
```

My guess is that tslint needs a change due to something different in typescript, though I was unable to confirm that because of a peerDependency thing:
```
$ npm install typescript@next
npm WARN unmet dependency /Users/alexeagle/Projects/tslint/node_modules/grunt-cli requires findup-sync@'~0.1.0' but will load
npm WARN unmet dependency /Users/alexeagle/Projects/tslint/node_modules/findup-sync,
npm WARN unmet dependency which is version 0.2.1
npm WARN unmet dependency /Users/alexeagle/Projects/tslint/node_modules/grunt requires findup-sync@'~0.1.2' but will load
npm WARN unmet dependency /Users/alexeagle/Projects/tslint/node_modules/findup-sync,
npm WARN unmet dependency which is version 0.2.1
npm ERR! Darwin 15.2.0
npm ERR! argv "/Users/alexeagle/.nvm/versions/node/v4.2.1/bin/node" "/Users/alexeagle/.nvm/versions/node/v4.2.1/bin/npm" "install" "typescript@next"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package typescript@1.8.0-dev.20160111 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer tslint@3.2.1 wants typescript@>=1.7.3
```

@adidahiya: known issue?

**Comment by adidahiya** [comment]
That's strange, because we fixed that [here](https://github.com/palantir/tslint/commit/ccc844c33220a9b009f067706f3bf0b3b5de045a) and the fix is available in `3.2.1`.

However, you should be able to install `tslint@next` (latest is `3.2.1-dev.1`). Let me know if that fixes the issue.

**Comment by alexeagle** [comment]
Thanks that was a trivial fix. We use npm shrinkwrap so our deps get very
stale...

**Comment by alexeagle** [comment]
Update, working on this now. I have a repro in our travis build.
https://travis-ci.org/angular/angular/jobs/107134306
