### ISSUE TITLE
Windows 10/Edge: DI fails to find providers

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#6369]
This is happening on Edge 12.10240.0 (Windows 10 0.0.0) running in Saucelabs:

```
Error: No provider for RenderStore! (Serializer -> RenderStore)
```

This currently only affects a web worker test. All other tests pass.

Build log: https://travis-ci.org/angular/angular/jobs/101132744
Failing test: https://github.com/yjbanov/angular/commit/9b8a872d6977da2e12105c58a86ff952f4250821#diff-e59090efb102822e15491ec7ec9e4085R54

**Comment by vicb** [comment]
obsolete
