### ISSUE TITLE
Getting Form Values from component which is loaded using DynamicComponentLoader LoadAsRoot() not working.

### ISSUE THREAD

**Issue by abhibly** [angular/angular#6370]
Hie i am adding a component using DCL loadasroot(). The component consist of forms.When i submit the form it is showing empty object.I have created a plunker demo http://plnkr.co/edit/e7ySXW9ta4OIJKbjRcF6?p=preview .It seems to be a bug because if i load the component using DCL loadintolocation() it is working fine but implementation using loadasroot() is not working as expected.Somebody please tell me why my form is not working.

**Comment by frederikschubert** [comment]
I am also having problems related to this. When I use `loadAsRoot` on one component and then try to call it again on a subcomponent that is located in the view of the loaded component the `DynamicComponentLoader` fails to find the subcomponent.
Also the inputs of a component are not being updated after the component has been loaded as root.

**Comment by princjef** [comment]
I am seeing similar issues. I am using `DynamicComponentLoader.loadAsRoot()`, then using the returned `ComponentRef` to set the values of the inputs.

When I use `loadIntoLocation()`, the dynamically loaded component automatically updates when the inputs are changed and its template renders based on the updated input values. However, when doing the same thing using `loadAsRoot()`, the dynamically loaded component doesn't update to reflect the changed input values, even after manually performing a `run()` with `NgZone`. Seems like a bug with `loadAsRoot()`.

Using beta 1

**Comment by ericmartinezr** [comment]
There's an issue with loadAsRoot https://github.com/angular/angular/issues/6223 . In the OPs comment changing it to loadIntoLocation or loadNextToLocation works fine, this could be closed as dup.

**Comment by escardin** [comment]
Not an expert, but I did look into the code for this at one point. loadAsRoot really looks like what you would do to bootstrap angular2 and not instantiate a component. It looks to behave consistently with how I would expect loading the root component of an app to behave.

**Comment by princjef** [comment]
@ericmartinezr yeah it looks to be the same issue as #6223. This should probably be closed as a dup.

@escardin, from the documentation, it wasn't clear to me that this would be used to bootstrap an element. Even so, the [plunker](http://plnkr.co/edit/yzKAiXQQQwKi88g6wIdY?p=preview) from #6223 demonstrates this issue for a component that has data binding without external inputs. Even if you are loading an application root, the component should still perform data binding in it's template.

**Comment by gdi2290** [comment]
when using `loadAsRoot` you need to trigger change detection and manually wire up Inputs, Outputs, Injector, and the component dispose function
```typescript
function onYourComponentDispose() {
}
let el = this.elementRef
let reuseInjectorOrCreateNewOne = this.injector;
this.componentLoader.loadAsRoot(YourComponent, this.elementRef, reuseInjectorOrCreateNewOne, onYourComponentDispose)
.then((compRef: ComponentRef) => {
  // manually include Inputs
  compRef.instance['myInputValue'] = {res: 'randomDataFromParent'};
  // manually include Outputs
  compRef.instance['myOutputValue'].subscribe(this.parentObserver)
  // trigger change detection
  cmpRef.location.internalElement.parentView.changeDetector.ref.detectChanges()
  // always return in a promise
  return compRef
});
```

**Comment by arunsn43** [comment]
This should be corrected to as follows
  cmpRef.changeDetectorRef.detectChanges();

**Comment by vicb** [comment]
Please re-open if this is still valid with the new router. You will have to fill out the issue template and provide a repro.
