### ISSUE TITLE
removeError method for Control (angular2 - beta0)

### ISSUE THREAD

**Issue by srivch** [angular/angular#6371]
Is there a removeError method for control. We seem to have setErrors but no removeError?

**Comment by srivch** [comment]
setErrors(null) does it...

**Comment by JakeMuller** [comment]
but that would remove all errors. What if one only wants to remove a specific error?

**Comment by srivch** [comment]
yes you are correct, i am not sure how to remove a single error.. but in my case i wanted to remove all... and this did the trick..

**Comment by zoechi** [comment]
You can get the errors object, modify it and then pass it back using `setErrors(modified)`

**Comment by JakeMuller** [comment]
I guess that could also work. What's the best approach of removing it? `Delete errors['errorKey']` ? or `errors.errorKey = null`? Or undefined?

**Comment by zoechi** [comment]
I don't know, I don't use JS/TS myself a lot but I'm sure Google.com is able to provide a solution ;-)
See also [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by Kannndev** [comment]
if (error) {
          this.userForm.controls.email.setErrors({'notUnique': true});
        } else {
          if (!(this.userForm.controls.email.hasError('pattern') || 
                           this.userForm.controls.email.hasError('required'))) {
            this.userForm.controls.email.setErrors(null);
          }

This did the trick for me manually checking other errors and removing the manually set error
