### ISSUE TITLE
beta.0 changelog has vanished

### ISSUE THREAD

**Issue by ocombe** [angular/angular#6372]
Looks like with the release of the beta.1 we lost the beta.0 changelog: https://github.com/angular/angular/blob/master/CHANGELOG.md

:'(

Besides being an important part of history, there was a breaking change that is no longer listed (dev mode activated by default).

**Comment by pkozlowski-opensource** [comment]
It is not like it vanished - there was never changelog for beta.0, apart from Igor's enthusiastic commit: https://github.com/angular/angular/commit/463754bf16429276224fe1ed0b01238ccaf05776 :-)

All the major breaking changes were part of alpha.54 / alpha.55 and the entire changelog for all the previous versions is preserved.

You can also check the history to confirm that nothing have disappeared: https://github.com/angular/angular/commits/master/CHANGELOG.md

**Comment by ocombe** [comment]
Oh my bad, the dev mode was changed in the last alpha !

Sorry then :)
