### ISSUE TITLE
[testing] regression in beta-1 for queryAll

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#6373]
Bumping from beta-0 to beta-1, I've got a unit-test failing.
Simple use-case, a `UsersCmp` display a list of users, represented by a `UserCmp` : 
````TypeScript
@Component({
  selector: 'user-cmp',
  template: `<img [src]="'/images/user-' + user.id + '.png'">`
})
export class UserCmp {
  @Input() user: any;
}

@Component({
  selector: 'users-cmp',
  template: `<div><user-cmp *ngFor="#user of users" [user]="user"></user-cmp></div>`,
  directives: [UserCmp]
})
export class UsersCmp {
  @Input() users: any;
}
````

The failing unit test: 
````TypeScript
it('should have a list of users', () => {
    let usersCmp = fixture.componentInstance;
    // only one user
    usersCmp.users = [{id: 1}];

    fixture.detectChanges();

    let users = fixture.debugElement.queryAll(By.directive(UserCmp));
    // this fails with users.length being 2
    expect(users.length).toBe(1);
  });
````

It appears that `fixture.debugElement.queryAll(By.directive(UserCmp));` returns two elements, where it used to return only one.
The elements are: 

- `<user-cmp data-ngid="381#0"><img data-ngid="380#0" src="/images/user-1.png"></user-cmp>` which is expected.
- `<img data-ngid="380#0" src="/images/user-1.png">` which is not expected.

Maybe it is related to the big refactoring @tbosch made in 7ae23adaff2990cf6022af9792c449730d451d1d ?

**Comment by xyxabcdiy** [comment]
I have the same problem

**Comment by cexbrayat** [comment]
That's still breaking in beta.2

**Comment by cexbrayat** [comment]
That has been fixed in beta.3, probably by e1bf3d33f8a1fa05a832b9b7ee1300ef9862fd0b
