### ISSUE TITLE
Memory leaks according to canvas and CreateJs

### ISSUE THREAD

**Issue by thupi** [angular/angular#6376]
Hi :smile: 

I recently worked with CreateJs inside a Angular 2 project. I made a canvas menu and testet it and it worked just fine. Then i implemented it in a Angular 2 project and found memory leaks. 

Here is a video which shows two website running the exact same script except one of the sites running Angular 2: https://thupi.tinytake.com/sf/NDQ1MTM4XzI0MDk4NzM;

As you can see the first site(Angular 2 site) had a increasing memory usage compared to the site running with out Angular 2.

I was not able to make typescript in plunkr so the site can be found on:
Angular 2 Site: http://test.thupi.com/menu ( -> Menu )
Plain site: http://test.thupi.com/index-no-angular2.html
 
:)

**Comment by robwormald** [comment]
are you cleaning up your canvas using the destroy lifecycle hook? It's nearly impossible to debug anything using video or deployed websites. Use this template https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5 as a starter with Typescript.

**Comment by Thupi** [comment]
I am not cleaning up in this sample but that might not make a different because the memory leak appears before the menu gets destroyed as shown in the video :smile:  

I made this plunker: https://plnkr.co/edit/7vKJIQtrL1Pc5OAPm92N?p=info :smile:

**Comment by thupi** [comment]
It was long time ago and i have not spend time with angular in the last couple of months. I assume this issue could be closed og deleted :)
