### ISSUE TITLE
angular2-polyfills.js in SharePoint 2013 TypeError: fnRef.apply is not a function

### ISSUE THREAD

**Issue by lifan0127** [angular/angular#6377]
When 'angular2-polyfills.js' was loaded in any SharePoint 2013 page
```HTML
<script src="https://code.angularjs.org/2.0.0-beta.0/angular2-polyfills.js"></script>
```
The following error occurred:
```javascript
Uncaught TypeError: fnRef.apply is not a function
arguments.(anonymous function) @ angular2-polyfills.js:493
(anonymous function) @ angular2-polyfills.js:118
run @ angular2-polyfills.js:138
zoneBoundFn @ angular2-polyfills.js:111
```
This may be related to #6239. It appears to mess up SharePoint JS codes.

**Comment by williamyinssw** [comment]
I had the same error in SharePoint, temporarily using the below code as a workaround:
<pre>
$(window).load(function() {
        // load angular2-polyfills after page loaded to avoid "fnRef.apply is not a function" error
        // https://github.com/angular/angular/issues/6377
    	$.getScript("https://code.angularjs.org/2.0.0-beta.0/angular2-polyfills.js").done(function(){
	    	// do your angular thing
    	});
}); 
</pre>

it will be great if someone can resolve this issue via improving "angular2-polyfills.js" library.

**Comment by mattdemps** [comment]
Using beta12 I am no longer seeing this.

**Comment by lifan0127** [comment]
Yes. This issue no longer exists in beta-12. Thanks!
