### ISSUE TITLE
RouteConfig redirectTo

### ISSUE THREAD

**Issue by j3ddesign** [angular/angular#6379]
I've just discovered the cause of an issue I've been having related to my routing.

Turns out when you use `redirectTo` in the RouteConfig it doesn't actually update `window.location.pathname` or `router.lastNavigationAttempt` - This caused a few logic checks to fail in my navigation etc, which I have now corrected to also look for '/' - I just thought it was worth pointing out.

Is this by design? bug? or perhaps there's something I'm missing.

My routeconfig just incase it's requested :)
```
@RouteConfig([
    {path: '/', redirectTo: ['Dashboard']},
    {path: '/dashboard',        name: 'Dashboard',    component: DashboardComponent},
    {path: '/settings/...',     name: 'Settings',     component: SettingsComponent},
    {path: '/dashboard/creator',name: 'Creator',      component: CreatorComponent},
    {path: '/dashboard/admin',  name: 'Admin',        component: AdminComponent},
    {path: '/files',            name: 'FileBrowser',  component: FileBrowserComponent},
    {path: '/login',            name: 'Login',        component: LoginComponent}
])
```

**Comment by brandonroberts** [comment]
Can you reproduce in a plunker? It works fine here: http://plnkr.co/edit/sGBLM8Wd05NxnVhRDilK?p=preview

**Comment by j3ddesign** [comment]
This is as close as I could get to replicating the issue in plunker - http://plnkr.co/edit/Ecy646?p=preview

The problem I have isn't the actual navigation its self but rather a component knowing the route we're on. I had initially intended to either look at window.location (which seems even less reliable in that plunker than my app) or router.lastNavigationAttempt (which doesn't even output a string in that plunker for some reason, couldn't figure that out)

**Comment by brandonroberts** [comment]
I see. router.lastNavigationAttempt is set when the router.navigateByUrl function is used. In your case of using a redirect on the path '/', the location.path() with be an empty string, so the lastNavigationAttempt will be an empty string. Using the router links doesn't use the navigateByUrl function, so the lastNavigationAttempt won't be updated. If you want url updates, subscribe to the root router for url changes.

```js
    router.subscribe((url) => {
        // store most recent url
    });
```

**Comment by j3ddesign** [comment]
I had no idea the router had observables set. That helps immensely. Thanks!

(I really can't wait until docs are finished! :P  Though this is helping my problem solving massively)

**Comment by brandonroberts** [comment]
:+1:
