### ISSUE TITLE
[beta.2] ngDoCheck is not a function when using minified bundles

### ISSUE THREAD

**Issue by ericmartinezr** [angular/angular#6380]
When using minified bundles with SystemJS, and a simple snippet like this 

```
        <template ngFor #item [ngForOf]="items" #i="index">
          <li>{{i}}</li>
          <li *ngIf="i % 2 == 0">number is even</li>
        </template>
```

Will throw 

```
TypeError: this.directive_0_0.ngDoCheck is not a function
```

This is only reproducible with minified bundles, non-minified work correctly. 

As an example check this [plnkr](http://plnkr.co/edit/ZWiQqw3nR8xS1MRrpTry?p=preview) (took it from https://github.com/angular/angular/issues/6304#issuecomment-170200989). To reproduce switch between minified and unminified bundles.

This is also reproducible with Webpack using this line in the config

```
    plugins : [
    	new webpack.optimize.UglifyJsPlugin()
    ],
```

Am I missing something?

**Comment by ocombe** [comment]
I have a similar error on my ng2-webpack starter: ocombe/ng2-webpack#7
The message is `No provider for t! (t -> t)` and adding `mangle: false` to the UglifyJS plugin fixes the problem (but the files are much bigger, so that's only temporary).

**Comment by ericmartinezr** [comment]
Hey @ocombe thanks for the tip, it actually fixes the issue but it losts the *uglyfing* and the bundle is a lot heavier. Lets wait then, thanks :+1:

**Comment by ericmartinezr** [comment]
Beta.2 still have these issues with minifications, here's the plnkr updated http://plnkr.co/edit/24fjnjNdAvpbfY8a85B2?p=preview . Reproducible in the same way as in the first comment.

**Comment by alexeagle** [comment]
Marked P1 as lots of users are running into this

**Comment by ffMathy** [comment]
It is still present in beta 5.

**Comment by ffMathy** [comment]
Does P1 mean it will be fixed in the next beta?

**Comment by PascalPrecht** [comment]
@ffMathy It means that it has a very high priority to be fixed. Doesn't guarantee that'll land in next beta release.

**Comment by ffMathy** [comment]
Still, it is a low effort one-hour task wih a P1 tag. I'm hoping for the best. I am stuck on my project until this is complete.

**Comment by ffMathy** [comment]
Still present in beta 6 as well.

**Comment by weupagency** [comment]
@ffMathy +1

**Comment by ffMathy** [comment]
I should also add that this most likely also blocks all browserify users. For me, it picks the minified versions from NPM node_modules first.

**Comment by antonybudianto** [comment]
ran into this too
<img width="1280" alt="screen shot 2016-01-09 at 7 30 11 am" src="https://cloud.githubusercontent.com/assets/7658554/12212957/2edffc2c-b6a3-11e5-9f66-d6f008c0b85d.png">

with mangle disabled, it worked well, also happening since **beta.1**

**Comment by ffMathy** [comment]
It is still present in beta 7 as well.

**Comment by ffMathy** [comment]
Still doesn't work in beta 8.

**Comment by gdi2290** [comment]
here's the current workaround
```typescript
new UglifyJsPlugin({
  mangle: {
    except: ['RouterLink', 'NgFor', 'NgModel']
  }
}),
```

**Comment by ocombe** [comment]
Ahh tanks !

**Comment by ericmartinezr** [comment]
Thanks for the workaraound Patrick!

**Comment by CaptainCodeman** [comment]
@ericmartinezr `AsyncPipe` did it for me but then it fails on something else. I don't know if it's worth following the trail - who knows how long it is!

**Comment by ericmartinezr** [comment]
@CaptainCodeman thanks, I tried right now but I didn't succeed. It failed with a `EXCEPTION: RangeError: Maximum call stack size exceeded` on Chrome and `EXCEPTION: InternalError: too much recursion` in FF. This is getting weirder, lol. I'll just keep with unminified version, thanks :+1:. I'll just keep waiting until this gets officially fixed

**Comment by CaptainCodeman** [comment]
I get a different error so it probably depends heavily on which pieces are used and it could extend to app code as well. Not worth bothering with until it's fixed properly. This is the best i got for now:

```
    new LoaderOptionsPlugin({
      minimize: true,
      debug: false
    }),
    new UglifyJsPlugin({
      beautify: false,
      mangle: false,
      compress : { screw_ie8 : true },
      comments: false
    }),
```

(webpack 2 BTW)

**Comment by gdi2290** [comment]
related issue https://github.com/mishoo/UglifyJS2/issues/999

**Comment by ffMathy** [comment]
Still present in beta 9.

**Comment by zoechi** [comment]
@ffMathy if it would be fixed it would be listed in https://github.com/angular/angular/blob/master/CHANGELOG.md#200-beta9-2016-03-09

**Comment by Tschakki** [comment]
I would be so happy, if this would be fixed in the next beta :)

**Comment by ffMathy** [comment]
@zoechi I am aware of that.

**Comment by caffeineinc** [comment]
Are the minified versions always broken, as i've the same issue ? 

Minifying the development version still hovers around 600kb, but works - It seems crazy that no one can use the minified production version at the moment due to a p1 present in all versions of the beta.

**Comment by ericmartinezr** [comment]
@caffeineinc all this started since beta.1, before that there were no issues.

**Comment by matthiasbalke** [comment]
I'm not sure whether I am running into the same issue.

When I use any beta of angular2 running `npm start` like described in the tour-of-heroes tutorial everything works fine. As soon as I concat / uglify my js using gulp angular2 does not load.

@ericmartinezr If angular2.beta0 worked with gulp, could you provide a working gulp configuration for tour-of-heroes as an example?

**Comment by ericmartinezr** [comment]
@matthiasbalke I don't have any example with gulp, I don't know about it. But it will work for sure with any tooling using beta.0.

**Comment by dragGH102** [comment]
+1 here with beta 9

**Comment by playground** [comment]
+1, still seeing this issue in beta.11

**Comment by ayyash** [comment]
My problem with minified version appeared when I used the date pipe, very simple date pipe, broke in minified version, with an very generic error message (9)

**Comment by NisStrom** [comment]
+1 why is this not being fixed?

**Comment by zuozuo** [comment]
+1 for beta 9

**Comment by brechtbilliet** [comment]
Still happening in Beta 12 :(

**Comment by ffMathy** [comment]
I don't get it. Loads of comments wanting this fixed. A P1 task that is also tagged as "easy". Why is it still not fixed?

**Comment by Hongbo-Miao** [comment]
I came from angular2-meteor.
I think this issue needs to be P0, higher than P1.
Because even everyone's project was done, but it cannot be deployed. So people use our apps.

**Comment by user414** [comment]
@Hongbo-Miao , unless I'm missing something I fail to see how not having minified bundle working can prevent you from deploying? Before there was minifying we just gzipped the file, as far as I know the extra benefits in size is very small a few percentage points on average. As well until recently minified file ran slower on some browser, here is a blurb by MS touting their improvement in edge

https://blogs.windows.com/msedgedev/2015/05/20/delivering-fast-javascript-performance-in-microsoft-edge/

So all in all I can't see why this would prevent any deployment. Sure it would be nice if it would be implemented, but all in all can't even see why it's a P1 compared to much more crucial bug and/or features I've seen out there. Just my 2 cents.

**Comment by andreialecu** [comment]
Mangling is valuable because it adds extra obfuscation, which in certain cases can be good in order to further secure the code from theft or easy reverse engineering.

Also, the uncompressed .js in a project I'm working on is 1 MB bigger with mangling off disabled.

**Comment by Hongbo-Miao** [comment]
@user414 thanks, but I never succeed, for our angular2-meteor project, we can run `meteor remove standard-minifiers` first.
Then the program can run well using `meteor —-production` locally.

But once I deployed on heroku, it still shows:
> EXCEPTION: No Directive annotation found on e

**Comment by andreialecu** [comment]
FWIW I'm getting the same `No Directive annotation found on t` error, but I'm not even using meteor at all. Just plain old angular2.

**Comment by zuozuo** [comment]
@Hongbo-Miao I also met the problem when deploying angular2 app with ruby on rails assets pipeline. And i found this bug is caused by the Uglify process when deploying. So when i disabled the uglify of js, i can successfully run my app on production.

**Comment by Hongbo-Miao** [comment]
@zuozuo thanks! Since Meteor 1.3 just came out, once I update, I will try to deploy my angular2-meteor1.3 app again.

**Comment by jhades** [comment]
This might useful for someone stumbling upon this issue. cloudflare serves the unminified bundle in under 200ms -> https://cdnjs.cloudflare.com/ajax/libs/angular.js/2.0.0-beta.11/angular2.js

**Comment by IgorMinar** [comment]
I've looked into this issue and here is a brief assessment of the situation:

There are three issues going on:

1/ our minified bundles are broken
2/ if you use uglify to minify your directives, components or pipes, your code will be broken
3/ there is something super funky going on in the [plunker]() listed in the description of this issue. It looks like we somehow incorrectly compile templates. @tbosch is looking into this and we'll fix it regardless of the first and second issue.

The proper fix is to 1/ and 2/ is to do offline template compilation which takes all html templates and converts them to TS/JS code. This code should then be minified together with the directive/component class. Only this will ensure that Uglify renames all property names consistently. We are working on this solution and it looks like it's going to take a few more weeks before it's available.

In the meantime we should implement the following workarounds:
- to fix Angular bundles (1/) we'll need to whitelist all of the core directives, pipes and form related bits, just like @gdi2290 [did in his starter](https://github.com/AngularClass/angular2-webpack-starter/blob/820531520314f095443dce3db6946df04c859e7d/config/webpack.prod.js#L134-L181)
- to fix Angular applications that use uglify we should either recommend that people turn property renaming (mangling) off, or that they whitelist all directive/component classes.

**Comment by ffMathy** [comment]
Thanks @IgorMinar, but what about those who don't have control over mangling? I just use the NPM package and use TypeScript Node resolution to include Angular. Here, it doesn't seem like I can't control whether or not to use the minified or the non-minified versions.

**Comment by IgorMinar** [comment]
@ffMathy in that case you are getting the CJS formatted non-minified, non-bundled code so you shouldn't be affected by this problem.

**Comment by CaptainCodeman** [comment]
> The proper fix is to 1/ and 2/ is to do offline template compilation which takes all html templates and converts them to TS/JS code. This code should then be minified together with the directive/component class. Only this will ensure that Uglify renames all property names consistently.

Does this mean `templateUrl` won't be an option? What about CSS selectors - is it possible they could be impacted?

**Comment by tbosch** [comment]
@IgorMinar regarding 1/:
This is fixed in my PR https://github.com/angular/angular/pull/6567. Something strange is going on there, probably because of some optimization trick we used to do in change detection...

**Comment by playground** [comment]
@tbosch will this be in the next release?

**Comment by pxwise** [comment]
I'm using uglifyjs `--no-mangle` as a workaround for our launch. Works for me.

For those not using webpack:

```
npm i -g uglify-js
npm i angular2
cd node_modules/angular2/bundles
uglifyjs angular2.js --no-mangle --compress -o angular2-uglified.min.js
```
1060 Kb -> 828 Kb uncompressed 
156 Kb -> 140 Kb gzipped

**Comment by zuozuo** [comment]
@pxwise thanks!. @Hongbo-Miao @pxwise has given a much better solution.

**Comment by tbosch** [comment]
Might take a little while to land my PR...

**Comment by ericmartinezr** [comment]
@tbosch thanks for taking a look at this.

In the meantime this workaround from @gdi2290 (see https://github.com/angular/angular/issues/6695#issuecomment-204164687) works perfectly with minification.

Copy & pasting

```
mangle: {
  screw_ie8 : true,
  keep_fnames: true
}
```

**Comment by ericmartinezr** [comment]
For those following this issue, this is already fixed in latest master, here's the plnkr updated with the minified bundle from latest master http://plnkr.co/edit/3Bcdnef5C45tzOPSw5DE?p=preview

Can't wait to this to land :smile: :clap:

**Comment by ericmartinezr** [comment]
Ok people, to everyone following it's time to test this. The plnkr using b.16 works perfectly http://plnkr.co/edit/7TdYjVkbbvsy2AoLQcpf?p=preview , but there was a PR to disable mangle for bundles. So we should test in our local envs to see if minification actually works

This is my current config for UglifyJS plugin with webpack

```
    	new webpack.optimize.UglifyJsPlugin({
    		compress : {
    			warnings : false
    		}
    	})
```

Can you guys try if it works for you with minification and without mangle? It works for me :D !

**Comment by micaelmbagira** [comment]
I did and it works for me as well.

**Comment by brechtbilliet** [comment]
Works like a charm!

**Comment by antonybudianto** [comment]
Finally it works!

**Comment by HerringtonDarkholme** [comment]
Tested locally.
Every thing works like a charm with both `compress` and `mangle` options turned on for uglifyjs. Further more `keep-fname` is turned off as well. 
Both angular source and my application source are compression-safe.

Great works! @tbosch !

I wonder when we can turn the mangle and keep-fname off? @gdi2290 ?

**Comment by ericmartinezr** [comment]
This was fixed already, closing.
