### ISSUE TITLE
Zone is undefined

### ISSUE THREAD

**Issue by eesdil** [angular/angular#6381]
Cannot start the application as I am getting this error:
![image](https://cloud.githubusercontent.com/assets/1408181/12221934/c2158b88-b7ac-11e5-914c-9f7469cdb99e.png)

However if I chnge Zone to zone (coming from the parameter at 155) everythign is working fine.

**Comment by pkozlowski-opensource** [comment]
Are you bundling zones on your side using WebPack or similar?

**Comment by eesdil** [comment]
yes, using jspm.

**Comment by mgamsjager** [comment]
@eesdil 
Take a look at my boot.ts maybe that will help:
https://github.com/mgamsjager/angular2-seed/blob/upWeb/src/boot.ts

All build with jspm. Zone related part import 'zone.js/dist/zone.min.js';

**Comment by ciriarte** [comment]
Some of these issues are solved by using angular2-polyfills.js, there are more details about it here: https://github.com/angular/angular/pull/6008

The gist of this issue is that your code is not loading long-stack-trace-zone.js in dev mode.

**Comment by eesdil** [comment]
If I load zone from the dist, it is working fine. However it doesn't seem to include long-stack-trace-zone. Also Zone is included as global in the main zone.js file.

If I load angular2-polyfills.js (import 'angular2/bundles/angular2-polyfills'), it starts loading things it cannot find, so it is not working for me. 

The thing is that I would assume that just using import "zone.js" would work out of box.

**Comment by vicb** [comment]
obsolete
