### ISSUE TITLE
Child view is not accessible Beta.1

### ISSUE THREAD

**Issue by eesdil** [angular/angular#6382]
Everything is working fine in Beta.0, but in Beta.1 getting errors that the viewFactory_* function is not accessible (child view). However the file and the function itself is generated properly.

But strange thing is that it is not happening in all of the components. I suppose it has to do something with ngSwitch or ngIf as the components under this directives.

Reproduced in plunkr:
http://plnkr.co/edit/e8qlznCVbvZnXbLTk36z?p=preview

**Comment by johnrbaur** [comment]
When I run your plunkr, I get the following error:
EXCEPTION: No provider for Renderer! (AppComponent -> TestService -> Renderer)

I don't see anything about a child view.

**Comment by eesdil** [comment]
nice, seems like it's got lost... will recreate it...

**Comment by eesdil** [comment]
fingers crossed that this remains as it should :)

http://plnkr.co/edit/RtgGISYsUZ5OFrDJhgRj?p=preview

**Comment by ericmartinezr** [comment]
That's weird, I haven't played before with ngSwitch*

But this works

```
<div [ngSwitch]=childNumber>
  <child-1 *ngSwitchWhen="1">
  </child-1>
</div>
```
Note that I removed one of the `*ngSwitchWhen`, if I add the second one it fails.

**Comment by eesdil** [comment]
yes, also weird, that if you change the childNumber to 1 it works also...

**Comment by johnrbaur** [comment]
I think I have the same error, but without using ngSwitch. https://github.com/angular/angular/issues/6404

**Comment by Fank** [comment]
Can confirm this issue, need to rollback to beta.0. It's not easy to determine the issue.

**Comment by marcopotento** [comment]
Same here, not sure where exactly in component hierarchy this exception
occurs. Rolling back to beta-0...

Florian Kinder <notifications@github.com> schrieb am Di., 12. Jan. 2016 um
11:41:

**Comment by SIGAN** [comment]
Lost almost a day with that issue

**Comment by eesdil** [comment]
Fixed in beta2, thanks.
