### ISSUE TITLE
Rename "Elvis operator" in docs.

### ISSUE THREAD

**Issue by IRus** [angular/angular#6387]
I found that in [angular template docs](https://angular.io/docs/ts/latest/guide/template-syntax.html#!#expression-operators) operator that commonly named as "Safe navigation operator" or "Safe call" (refs.: [C#](http://blogs.msdn.com/b/jerrynixon/archive/2014/02/26/at-last-c-is-getting-sometimes-called-the-safe-navigation-operator.aspx), [Kotlin](https://kotlinlang.org/docs/reference/null-safety.html#safe-calls), [Groovy](http://groovy-lang.orgv/operators.html#_safe_navigation_operator), [Ruby](https://www.ruby-lang.org/en/news/2015/11/11/ruby-2-3-0-preview1-released/), [Swift](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/OptionalChaining.html#//apple_ref/doc/uid/TP40014097-CH21-ID245)) has name "Elvis". Even [wikipedia](https://en.wikipedia.org/wiki/Elvis_operator) stands, that elvis operator is different.

I suggest rename this operator to "Save navigation operator" or "Optional Chaining operator".

**Comment by ThorstenHans** [comment]
I guess that Elvis is short for "Expect left value is set" :D

**Comment by Nefarion** [comment]
.Net calls them [null-conditional operators](https://msdn.microsoft.com/en-us/library/dn986595.aspx)

**Comment by christopherthielen** [comment]
I agree, I understand the [elvis operator](https://en.wikipedia.org/wiki/Elvis_operator) as something different than ng2's  `?.`.  I know the elvis operator as ternary sugar.

Groovy calls `?.` the [safe navigation operator](http://www.groovy-lang.org/operators.html#_safe_navigation_operator)  

(note: groovy also has [elvis](http://www.groovy-lang.org/operators.html#_elvis_operator))

**Comment by vai** [comment]
null conditional / null coalescing would be more appropriate.

**Comment by wardbell** [comment]
Done. Please close.
