### ISSUE TITLE
ngFor and jquery isotope don't work

### ISSUE THREAD

**Issue by sk-iv** [angular/angular#6388]
Hi, here is an example: http://plnkr.co/edit/tAZzE9VdgOzVr96106Vf?p=preview

I want to with the help of jquery plug-in to add style to the elements. it turns out the construction *ngFor.  The directive ngFor not, why? What do I need to add a style attr using jquery in ngfor?

**Comment by ericmartinezr** [comment]
You can simply do it like this

```
<div class="project" [style.color]="'red'" *ngFor="#project of projects; #i = index">
```
No jQuery at all. 

Besides that please move your questions to [gitter's chatroom](https://gitter.im/angular/angular) or [StackOverflow](http://stackoverflow.com/questions/tagged/angular2)

**Comment by sk-iv** [comment]
I use jQuery plug-in isotope. Plug-in to each element adds a different style depending on the location of the element. With ngFor it does not work

**Comment by pkozlowski-opensource** [comment]
closing as a support question: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
