### ISSUE TITLE
Having some issues with dynamically loaded directives

### ISSUE THREAD

**Issue by j3ddesign** [angular/angular#6389]
I'm attempting to create a reusable "sound widget" within my app. I currently have it successfully switching modes and views and all that jazz using DynamicComponentLoader

However when I try and add my AudioBar component, none of the magical angular stuff is being rendered... here's a plunker that messily explains my situation http://plnkr.co/edit/hkgPhWT7uLLswo9gJK07?p=preview

Looking for some insight onto this if anybody has any :)

**Comment by ericmartinezr** [comment]
Known issue with `loadAsRoot`, dup of https://github.com/angular/angular/issues/6223

**Comment by j3ddesign** [comment]
Ah, thank you! My google-fu didn't find that one for me! :+1:

**Comment by j3ddesign** [comment]
So it seems using loadIntoLocation broke the logic to switch between the nested components. Is there a different way around this? Can't find too much on this sort of injection.

Here's the logic I'm using (now switched from loadAsRoot)

```
    setView(mode) {
        switch (mode.title) {
            case 'single':
                this.dynamicComponentLoader.loadIntoLocation(SoundWidgetsingle, this.elementRef, 'content');
                break;
            case 'random':
                this.dynamicComponentLoader.loadIntoLocation(SoundWidgetrandom, this.elementRef, 'content');
                break;
            case 'amount':
                this.dynamicComponentLoader.loadIntoLocation(SoundWidgetamount, this.elementRef, 'content');
                break;
            case 'combo':
                this.dynamicComponentLoader.loadIntoLocation(SoundWidgetcombo, this.elementRef, 'content');
                break;
        }
    }
```

Thank you for taking the time to help

**Comment by j3ddesign** [comment]
Moving my question to https://gitter.im/angular/angular as it's not specifically the issue described anymore.
