### ISSUE TITLE
Response ok is sometimes undefined

### ISSUE THREAD

**Issue by oliverjanik** [angular/angular#6390]
I'm doing this

```typescript
        return this.http.request(request)
            .map(res => {
                if (!res.ok) {
                    console.error(res.ok);
                    console.error(res.status);
                }
                
                return res.json();
            });
```

And some calls report status 200 and ok is undefined:

![image](https://cloud.githubusercontent.com/assets/2280140/12225239/293bc0e0-b85a-11e5-890f-4ca25f4c9093.png)

**Comment by pkozlowski-opensource** [comment]
@oliverjanik it is impossible to investigate / help based on the provided info. If you need further assistance please provide a live reproduce scenario using plunker or similar.

**Comment by oliverjanik** [comment]
Response.ok should be `true` when status is 200-299, correct? I'm getting `undefined`.

Looking briefly at the code here:

- https://github.com/angular/angular/blob/master/modules/angular2/src/http/static_response.ts
- https://github.com/angular/angular/blob/master/modules/angular2/src/http/backends/xhr_backend.ts
- https://github.com/angular/angular/blob/master/modules/angular2/src/http/http.ts

The ok property is never assigned to.
