### ISSUE TITLE
Property binding not working on IE11 when property set in a promise resolve function

### ISSUE THREAD

**Issue by gchurchley** [angular/angular#6391]
Angular2 Beta doesn't bind a property to a template when the property is set in the 'resolve' of a Promise. Check out this plunker: http://plnkr.co/edit/SRDBGMThMHRbpNgNX08X?p=preview - it works on Chrome and FF but the {{name}} field doesn't get updated on IE11.

**Comment by wardbell** [comment]
Please update to latest (beta.7 as I write) and try again using all three of these IE related shims:
```
    <!-- IE required polyfills, in this exact order -->
    <script src="node_modules/es6-shim/es6-shim.min.js"></script>
    <script src="node_modules/systemjs/dist/system-polyfills.js"></script>
    <script src="node_modules/angular2/es6/dev/src/testing/shims_for_IE.js"></script>
```
or in plunker
```
    <!-- IE required polyfills, in this exact order -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.33.3/es6-shim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.20/system-polyfills.js"></script>
    <script src="https://npmcdn.com/angular2/es6/dev/src/testing/shims_for_IE.js"></script>
```
Report back if still not working.

We hope to merge the two Angular-supplied shims in a beta coming soon.

**Comment by gchurchley** [comment]
@wardbell Your fix seems to work. Thanks!  I've updated the plunker
