### ISSUE TITLE
Strange behavior of template parsing depending on attributes order

### ISSUE THREAD

**Issue by aalexelis** [angular/angular#6395]
Hello,
I don't know if this is part of the template parser specs, but it seems that attributes order affects parsing.
In the The Basics example on the top page, in src/hello_world.html, if one replaces:
```html
<input type="text" [(ngModel)]="yourName" placeholder="Enter a name here">
```
for
```html
<input placeholder="Enter a name here" [(ngmodel)]="yourName" type="text">
```
the parser cannot parse the ngModel property

**Comment by zoechi** [comment]
It looks like you need to wrap some code in ```

**Comment by pkozlowski-opensource** [comment]
In your second use case (`<input placeholder="Enter a name here" [(ngmodel)]="yourName" type="text">`) the `ngmodel` is **lower-cased** - I don't know if this is intentional or not, but new HTML parser _is_ case sensitive when it comes to property names.

I don't know if this is your exact problem since you are not giving details on:
> the parser cannot parse the ngModel property

What does it mean exactly? Are you getting any error on the console? Bad runtime behavior? Putting together a plunker with a reproduce scenario would give us those details.

**Comment by aalexelis** [comment]
sorry for mistyping, does not work with ngModel too.
Plunker:
http://plnkr.co/edit/6D0bb7CCnGSFDp1Xw5Kh?p=preview

it gives:
EXCEPTION: Template parse errors:
Can't bind to 'ngmodel' since it isn't a known native property ("<label>Name:</label><input placeholder="Enter a name here" [ERROR ->][(ngmodel)]="yourName" type="text"><hr><h1 [hidden]="!yourName">Hello {{yourName}}!</h1>"): HelloWorld@0:59

**Comment by pietie** [comment]
Your "M" character has some funny encoding. Could it be your keyboard layout?

Try to copy and paste from here: [(ngΜodel)]

**Comment by aalexelis** [comment]
@pietie 
thanks for the reply ( I am a Greek living in Japan, sometimes encodings do get out of hand )

copying/pasting from you did not fix the problem, but I copied from the original plunker, shuffled the attributes and it seems to work fine, so it must not be the attributes order problem, as I initially supposed, sorry about alarming you.

Will keep trying to figure this out, thanks

**Comment by aalexelis** [comment]
@pkozlowski-opensource, @pietie 
thanks for your help, I finally figured it out, the problem was on my side, not of the parser, sorry for this.
(basically, the core cause was as @pkozlowski-opensource rightly pointed out that the parser is case-sensitive, while my  Html parser/writer turns everything to lowercase. Any way to tackle this?)

I am closing this issue.
