### ISSUE TITLE
[Router] child routes with "/" url and page reload bug

### ISSUE THREAD

**Issue by ocombe** [angular/angular#6400]
Hello, I have the following setup:
```js
// app route config:
@RouteConfig([
    {path: '/...', component: Home, as: 'Home', useAsDefault: true},
    {path: '/login', component: Login, as: 'Login'},
])

// home route config:
@RouteConfig([
    {path: '/', component: Logged, as: 'Logged', useAsDefault: true},
    {path: '/admin', component: Admin, as: 'Admin'}
])
```

```
app:
 |__ login: #/login
 |__ home: #/...
       |__ logged: #// (useAsDefault)
       |__ admin: #//admin
```

When I navigate to `#//` it loads "logged" and if I refresh the page it works (same route).
When I navigate to `#//admin` it loads "admin" and if I refresh the page it redirects to `#//` and loads "logged" instead of "admin".

Now if I change the home route from `/...` to `/home/...`:
When I navigate to `#/home/` it loads "logged", if I refresh the page it works (same route).
When I navigate to `#/home/admin` it loads "admin", if I refresh the page it works and loads admin immediately.

**Comment by ocombe** [comment]
Here is a repository with the bug: https://github.com/ocombe/bug-router-child
Just use `npm install` and then start the project with `npm start`, and go to `http://localhost:3000`.

- If you go to home / admin, the url is `http://localhost:3000/#//admin`, refresh the page and the url will be `http://localhost:3000` (which is home / logged).
- if you go to about / admin, the url will be `http://localhost:3000/#/about/admin`, refresh the page and the url stays the same.

**Comment by vicb** [comment]
obsolete - former router
