### ISSUE TITLE
bug(upgrade): leak: ngOnDestroy not called when angular1 destroys directive

### ISSUE THREAD

**Issue by andreialecu** [angular/angular#6401]
Repro: http://plnkr.co/edit/s0FLVw1fIbG2mat954hu?p=preview

OnInit is called, but OnDestroy is not called when angular1 destroys an angular2 component via `ng-if`

**Comment by andreialecu** [comment]
This seems pretty serious, since it's not even called for pipes or other directives inside the component resulting in serious leaks.

Currently it makes resource management impossible, can't even remove intervals and timeouts as there's no hook.

**Comment by cw-okuno** [comment]
:+1:

**Comment by laco0416** [comment]
@andreialecu I troubled by this bug too, but I found a workaround. 

```ts
@Component({
  selector: "my-app",
  ...
})
export class App {
  private element: HTMLElement;
  
  constructor(el: ElementRef) {
    this.element = el.nativeElement;
  }
  
  ngOnInit() {
    console.log("[my-app] init");
    
    // host as ng1 element
    angular.element(this.element).on("$destroy", () => {
      // re-fire $remove event
      this.element.dispatchEvent(new Event("$remove"));
    });
  }
  
  ngOnDestroy() {
    console.log("[my-app] destroy");
  }
}
```

[Plunker](http://plnkr.co/edit/2ObWPmAPf1BnudhBy1hO?p=preview)
