### ISSUE TITLE
Component nesting broken in beta.1

### ISSUE THREAD

**Issue by johnrbaur** [angular/angular#6404]
While updating to beta.1, I encountered an error with nested components. Depending on the order I use the components, it fails unexpectedly with the following error:

EXCEPTION: TypeError: viewFactory_BlueBox0 is not a function. 

This may be related to the change in https://github.com/angular/angular/commit/7ae23ad

I reproduced the error in this plunkr:
http://plnkr.co/edit/8Zl0JdbV5fuBMxDqcg1L?p=preview

**Comment by SIGAN** [comment]
I have the same issue

**Comment by cschroeter** [comment]
Same here

**Comment by david10sing** [comment]
if you put the <blue-box> tag before the <green-box> tag in your app component, it works... Strange

**Comment by tbosch** [comment]
Yes, this is a bug introduced by the recent compiler refactoring. Thanks for reporting!

**Comment by kylecordes** [comment]
I hope this fix makes it into beta 2.
