### ISSUE TITLE
beta.1 broke date pipe on unit tests

### ISSUE THREAD

**Issue by pjpsoares** [angular/angular#6405]
After updating to beta.1 the unit tests for components that used the date pipe broke. 
"The pipe 'date' could not be found"

**Comment by randyv12** [comment]
This is still happening in beta.9, please see the referenced issue.  Thank you!

**Comment by Doormouse2House** [comment]
Hit this, so +1

**Comment by tallkid24** [comment]
Does anyone know if there is any was around this issue without overriding the template?

**Comment by tallkid24** [comment]
Never mind, figured out that you could do this in beforeEachProviders to solve it.
```
import {provide, PLATFORM_PIPES} from "@angular/core";

provide(PLATFORM_PIPES, {useValue: YourPipe, multi: true}),
```

**Comment by tklever** [comment]
Did anyone find a work around for this? Unit Tests on Components with the Date pipe in the template fail fairly ugly when running on PhantomJS. Remove the pipe, and all is well. Change from PhantomJS to Chrome, all is well.

PhantomJS + Date Pipe fails, other pipes work fine.

**Comment by tallkid24** [comment]
@tklever take a look at my comment before yours. That should solve it.

**Comment by tklever** [comment]
@tallkid24 That did work using `overrideProvider`, thank you for your help.

Hope this issue gets fixed in the future.

**Comment by peterjp80** [comment]
I can't seem to get the date pipe to work, any help would be greatly appreciated.  I'm using rc4 and getting the error "ReferenceError: Can't find variable: Intl"

Here's my entire spec file:

`import { provide, PLATFORM_PIPES } from '@angular/core';
import { DatePipe } from '@angular/common';
import { addProviders, async, inject } from '@angular/core/testing';

import { Post, PostComponent, PostHtmlComponent } from './';
import { usingComponentFixture } from '../../test-helpers';

describe('Component: Post', () => {
    beforeEach(() => {
        provide(PLATFORM_PIPES, {useValue: DatePipe, multi: true });
        addProviders([PostComponent, PostHtmlComponent, ]);
    });

    it('should render an h1 tag with text matching the post title', 
        usingComponentFixture(PostComponent, fixture => {
            let component = <PostComponent>fixture.componentInstance;
            let element = fixture.nativeElement;

            component.post = <Post>{ title: 'Hello', publishedOn: new Date('8/5/2016') };
            fixture.detectChanges();
            expect(element.querySelector('.blog-post-header h1').innerText).toBe('Hello');
        })
    );
});`

**Comment by tallkid24** [comment]
I don't think it's anything to do with the pipe. Sounds like something in
your component.

**Comment by peterjp80** [comment]
@tallkid24 I don't receive the error when I remove the date pipe from the template.

**Comment by tallkid24** [comment]
Are you passing a variable named Intl to the pipe?

**Comment by peterjp80** [comment]
@tallkid24 No, I'm not using a variable named Intl anywhere in my code, but the date pipe provided in @angular/common does have this line:

`var intl_1 = require('../facade/intl');`

So I'm guessing Intl is used somewhere within the date pipe.

**Comment by peterjp80** [comment]
I was able to resolve this issue.  Here's what I had to do:

1. npm install karma-intl-shim --save-dev
2. Add 'intl-shim' to the frameworks collection in karma.conf.js
3. Add the following to karma-test-shim.js (this is referenced in the files collection of karma.conf.js)

`
    require('karma-intl-shim');
    require('./en-us.js'); // copied from https://github.com/andyearnshaw/Intl.js/blob/master/locale-data/json/en-US.json
    Intl.__addLocaleData(enUsLocaleData);
`

**Comment by pkozlowski-opensource** [comment]
Sounds like a support request that got resolved. Closing.
