### ISSUE TITLE
Routing enhancement-New Feature: page caching

### ISSUE THREAD

**Issue by mkrishna4ua** [angular/angular#6406]
i am very much interested in page caching feature in angular routing. the feature is described below:

Lets say there are multiple dynamic views in a single page application. If user opens page P1 then he performs some operation to fetch data from server based on some criteria and that data is displayed in data table of that page. Now if user navigate away from the page P1 and come again on the same page then i want user to see the same data on that page without making the call to the server. So if we can cache the page and its controller instance in router then we can achieve that functionality.

I do not know how to implement this feature but it is very useful feature (SmartGWT product has this feature) that can 
- reduce network traffic.
- user can navigate fast on single page application.

if you need more information, please get back to me.

**Comment by zoechi** [comment]
I think this better stays custom functionality. The data isn't part of Angular anyway, that's all custom implementation. 
I don't see an advantage in implementing a cache for this in Angular itself.
Why do you think Angular should manage a cache of your data instead of an cache implementation independent of Angular?

**Comment by robwormald** [comment]
this is easily handled at the service layer, simply by caching the *data* and immediately returning it.

**Comment by mkrishna4ua** [comment]
I agree. I thought if that can be added as a feature in router. 
Now i think better to keep caching separate from router.
