### ISSUE TITLE
Forms Angular 2 for Javascript Not Working

### ISSUE THREAD

**Issue by blwill** [angular/angular#6408]
I took a look a few weeks back and then noticed again today that this tutorial (https://angular.io/docs/js/latest/guide/forms.html) doesn't work.  Has anyone had any luck?  If not, is there a plan to get a corrected version up on the site?

**Comment by robwormald** [comment]
Could you expand a bit more on "doesn't work"?

**Comment by blwill** [comment]
Absolutely.  So I scroll to the bottom of the tutorial page under "Here’s the final version of the source:" and create all those files (in the appropriate directories), copy in the code provided, fire up the command line and start npm.  This launches Chrome (Version 47.0.2526.106 m) and all I get is the "Loading..." txt without anything actually loading.  This is in Win 7.  I open up Firebug and 2 errors pop up.  1) SystaxError: missing } after function body in hero-form.component.js 2) ReferenceError: ng is not defined in boot.js.  #1 appear to just be missing "})" in the example at the end of the file on the page but still leaves #2.  Hope this helps.

**Comment by kaippp** [comment]
Hello,

I have a similar problem with angular2-forms, javascript version.
https://angular.io/docs/js/latest/guide/forms.html

Running on a Raspberry Pi, Raspbian Jessie, Node.js V4.2.4.
After following the instructions and using "the final version of the source",
npm install bootstrap --save
npm start
I got the following messages. Iceweasel displays "Loading...".

16.01.19 14:32:17 304 GET /./index.html (Unknown - 388ms)
16.01.19 14:32:21 304 GET /node_modules/bootstrap/dist/css/bootstrap.min.css (Unknown - 310ms)
16.01.19 14:32:21 304 GET /styles.css (Unknown - 53ms)
16.01.19 14:32:21 304 GET /node_modules/angular2/bundles/angular2-polyfills.js (Unknown - 57ms)
16.01.19 14:32:21 304 GET /app/hero.js (Unknown - 59ms)
16.01.19 14:32:21 304 GET /app/hero-form.component.js (Unknown - 61ms)
16.01.19 14:32:21 404 GET /node_modules/angular2/bundles/angular2.umd.js (Unknown - 106ms)
16.01.19 14:32:21 404 GET /app/app.js (Unknown - 82ms)
16.01.19 14:32:21 304 GET /app/boot.js (Unknown - 52ms)
16.01.19 14:32:21 404 GET /node_modules/angular2/bundles/angular2.umd.js (Unknown - 21ms)
16.01.19 14:32:21 404 GET /app/app.js (Unknown - 23ms)
16.01.19 14:32:26 404 GET /favicon.ico (Unknown - 40ms)

My package.json look like this (Is it OK?):
{
  "name": "angular2-forms",
  "version": "1.0.0",
  "scripts": {
    "start": "npm run lite",
    "lite": "lite-server"
  },
  "license": "ISC",
  "dependencies": {
    "angular2": "2.0.0-beta.0",
    "bootstrap": "^3.3.6",
    "es6-promise": "^3.0.2",
    "es6-shim": "^0.33.3",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.0",
    "systemjs": "0.19.6",
    "zone.js": "0.5.10"
  },
  "devDependencies": {
    "lite-server": "^1.3.1"
  }
}

Indeed, the following files don't exist:
- angular2.umd.js
- app.js
- favicon.ico

But angular2-all.umd.js does exist.

Thanks.

**Comment by kara** [comment]
The forms tutorial has changed a lot since January, and the current version appears to work for me, so I'm closing for now. If you are still having trouble with it, please feel free to re-open.
