### ISSUE TITLE
Is there any way to configure that angular router should instantiate routing component only once for a single page application

### ISSUE THREAD

**Issue by mkrishna4u** [angular/angular#6411]
Is there any way to configure that angular router should instantiate routing component only once?
What is happening when we are visiting other pages and then coming back on the same page that last visited then router instantiate the component again so each time we visit the component then constructor is called. Is there any way to configure that router should only instantiate the class only once no matter how many times we are going to visit that page.

What i think, for parameterized routes constructor should be called every time. But for static routes it can be made configurable.

**Comment by thelgevold** [comment]
The is a concept called routerCanReuse
```
export class myComponent implements CanReuse {

    constructor(){
        console.log('init');
    }

    routerCanReuse(next: ComponentInstruction, prev: ComponentInstruction) { return true; }
}
```

If you set it to true it will not rerun the constructor. Just check the console.log and observe the difference when returning true vs false.

**Comment by mkrishna4ua** [comment]
I tried your solution but did not work. Probably, in my application all the routes are AsyncRoute, so in this case it is calling the constructor all the time. We are using the loader to load the Component as given below:
`new AsyncRoute({
    path: '/systemconfig',
    loader: () => System.import('app/admin/system-config/system-config').then(m => m.SystemConfig),
    name: 'SystemConfig'
  }`

**Comment by jevenson** [comment]
Yeah I am experiencing the same behavior, although I'm not using AsyncRoutes. The component I am trying to use is in a child route though.

When navigating back to the route the `routerCanReuse` method is never called, and the constructor is still called every time.

**Comment by vicb** [comment]
obsolete - former router
