### ISSUE TITLE
ViewEncapsulation.Emulated styles do not apply to children injected with <ng-content>

### ISSUE THREAD

**Issue by stringham** [angular/angular#6412]
If I have a list component with the following template:
```html
<style>
    li {
        line-height: 40px;
        color: #fff;
        border-bottom: 1px solid rgba(255, 255, 255, 0.15);
        cursor: pointer;
    }
</style>

<ul>
    <li>item 1</li>
    <ng-content></ng-content>
</ul>
```

and I use the component in another template

```html
<list-component>
    <li>item 2</li>
    <li>item 3</li>
</list-component>
```

the two list items defined in the second template don't get the styles defined in the list-component's template.

**Comment by kylecordes** [comment]
I think this is the intended behavior.

**Comment by zoechi** [comment]
If you want that set `ViewEncapsulation` to `None` instead.
With `Emulated` and `Native` use `::content`

```html
<style>
    li, ::content > li {
        line-height: 40px;
        color: #fff;
        border-bottom: 1px solid rgba(255, 255, 255, 0.15);
        cursor: pointer;
    }
</style>

<ul>
    <li>item 1</li>
    <ng-content></ng-content>
</ul>
```

See also http://www.html5rocks.com/en/tutorials/webcomponents/shadowdom-201/?redirect_from_locale=de

**Comment by stringham** [comment]
Should this work? Or should you have to use the `::content` pseudo element?

```html
<style>
    :host > li {
        color:#fff;
    }
</style>

<ul>
    <li>item 1</li>
    <ng-content></ng-content>
</ul>
```

Right now using the `:host` selector lets you style the dom in the insertion point.

**Comment by zoechi** [comment]
@stringham In your example the text in `<li>item</li>` shoule be white. `::content > li {` would show `<li>` children of your component with white text.

**Comment by stringham** [comment]
Having a template that is

```html
<style>
    :host li {
        color:red;
    }
</style>
<ul>
    <li>this is red</li>
    <ng-content>
</ul>
```

and then using it like this

```html
<red-list-component>
    <li>this item is also red</li>
</red-list-component>
```

the `<li>` elements included with `<ng-content>` get the styles applied to them. Is this an appropriate way to style `<ng-content>`? Or should I be doing something with `::content`?

**Comment by zoechi** [comment]
No it shouldn't. Only when `::content` is used. 
Have you tried `<ng-content></ng-content>` instead of just `<ng-content>`?

**Comment by stringham** [comment]
Sorry, I was using `<ng-content></ng-content>`, just didn't get that in my example in the previous comment. 

It looks like I can style `<ng-content></ng-content>` with `:host`, and that may be a bug. I'll try using `::content`.

**Comment by stringham** [comment]
I got it to work using `::content` as the psuedo element of `:host`, does this look right?

```html
<style>
    :host::content li {
        color:red;
    }
</style>
<ul>
    <li>I am red</li>
    <ng-content></ng-content>
</ul>
```

using it like this

```html
<list-component>
    <li>I am also red</li>
</list-component>
```

**Comment by stringham** [comment]
I am using Chrome, I haven't specified any ViewEncapsulation, so it defaults to `Emulated`, right?

Here's a plnkr:

http://plnkr.co/edit/nGs6Bll5Ax5xYRmsov3J

**Comment by zoechi** [comment]
Yes `Emulated` is default.
I investigated a bit more.

It seems if you use `ViewEncapsulation.Emulated` `:host` is actually required (`:host ::content` with a space works the same).  
`:host` is not necessary when `ViewEncapsulation.Native` and `<content>` (instead of `<ng-content>`) is used.
I run into requiring `:host` in addition to `:content` in Polymer with shady DOM (instead of full shadow DOM), therefore I think this is a limitation or bug of the emulation (shim).

**Comment by emolr** [comment]
👍  plunker by @stringham made my day! Thanks

**Comment by vicb** [comment]
Is this still an issue ?

It is not clear to me if we have a difference in behavior with the native shadow DOM. If this is the case please create 2 plunkers: One that shows the behavior with native shadow DOM and the other one that shows that our shim is not correct. Thanks.
