### ISSUE TITLE
peer dependency on reflect metadata pinned to 0.1.2 ?

### ISSUE THREAD

**Issue by johnpapa** [angular/angular#6415]
when i `npm install` i get a peer dependency issue on reflect metadata. why? cuz we had `    "reflect-metadata": "^0.1.2",` and `0.1.3` is out. But Angular requires `0.1.2`. for now i told the samples to use `0.1.2` exactly … but if this is right, we need to fix this a better way.

Ng has a peer dep on 1.2.  Anyone installing angular 2 directly will hit this then. Unless they go type in a specific version.

I think it happens under this case ... Your package json already has ^0.1.2 and then you run npm install.

reply from @IgorMinar ...
I guess we could change our package.json to contain version range for metadata and other peerDeps
e.g. 0.1.x rather than 0.1.2
you will still have issues once reflect-metadata goes to 0.2, but that will likely contain breaking changes
so we need to control the upgrade when that happens
can you file an issue and cc me on it please?

**Comment by digitaldonkey** [comment]
```

npm install
npm WARN angular2@2.0.0-beta.5 requires a peer of reflect-metadata@0.1.2 but none was installed.

```


As far as i can see there is no release for reflect-metadata tagged with 1.2 https://github.com/rbuckton/ReflectDecorators/releases

How is this possible?

**Comment by clemgrim** [comment]
+1, same issue with rxjs

It should be better to use `"reflect-metadata": "^0.1.2"` ?

**Comment by pkozlowski-opensource** [comment]
It is not pinned any more, currently `"reflect-metadata": "^0.1.3"`, see: https://github.com/angular/angular/blob/a19c4e8f9a76dbf02cddcaf96b29cad8ef6b03ec/package.json#L22
