### ISSUE TITLE
rename router-outlet to routerOutlet?

### ISSUE THREAD

**Issue by AerisG222** [angular/angular#6416]
This seems like it would be more consistent with current naming conventions like routerLink, ngFor, etc.

**Comment by laco0416** [comment]
`router-outlet` is an element name. element names are should follow the [Custom Elements](https://www.w3.org/TR/custom-elements/#concepts) spec.
See https://github.com/angular/angular/blob/master/modules/angular2/docs/migration/kebab-case.md#overview

> while tag name are case sensitive, the best practice is to use dash case for component elements so that the browser interpret them as custom elements,

**Comment by AerisG222** [comment]
makes sense, thanks for the explanation.
