### ISSUE TITLE
Question: Are you planning to support data-driven views in AngularJS 2.0?

### ISSUE THREAD

**Issue by dkazubekram** [angular/angular#642]
We use AngularJS to develop a suit of enterprise applications. We heavily rely on data-driven views. The views definitions are derived from a database and are not known at compile time.

**Are you planning to support data-driven views in AngularJS 2.0?** How data-driven views would fit into component-based directives? Are you planning to keep $compile available for compiling arbitrary fragments of HTML?

**Comment by jimthedev** [comment]
Seems like it is covered here: https://github.com/angular/angular/blob/master/modules/angular2/src/core/compiler/view.js#L530 

Not sure about the actual syntax used to make it happen.

**Comment by dkazubekram** [comment]
Thanks for prompt response.

I haven't played with AngularJS 2.0 yet and I can't work out myself whether that code reference should answer my questions.

What I understand thus far is that component-directives are what we need to put in routes instead of controllers that would serve views. If that is the case, they need a predefined list of directives they are going to use. *That is something that is not known at compile time* and for us it is derived from the database.

 **Would you be able to explain what would be the AngurlarJS 2.0 way of dealing with such cases?**

Thanks in advance.

**Comment by jimthedev** [comment]
I see what you're saying.  So you want to actually define directives at compile time from a database.  I don't have any more info on but I'd imagine if you post some boilerplate code that shows how you do it in 1.x then someone could look at it and figure how it might work in 2.0. It might change over time but at least the A2 developers could see your use-case as they move forward.

**Comment by dkazubekram** [comment]
I have put together an [example](http://jsfiddle.net/dkazubek/5mym33ua/2/) on jsFiddle. It is very simplified but it shows how we generate database derived views with angular.

**Could you please explain what this example would look like in Angular 2.**

**Comment by mhevery** [comment]
Yes these will be supported.
