### ISSUE TITLE
Turkish Character Problems

### ISSUE THREAD

**Issue by mustafacoskuncom** [angular/angular#6420]
Hi, I try to use Turkish character in an example Angular 2 app however I can not show the content. When I change the character everything is okey. Is there any solution about it? I saved the file UTF-8 or already UTF-8 Meta Tags in index file... I do not know what is the problem. Thanks for your interest.

**Comment by zoechi** [comment]
Probably a dup of #6036

**Comment by mustafacoskuncom** [comment]
As I see cause of IDE or external tools. Because I have checked so many example projects and some of them running without problem and a few projects give error. Thanks again.
