### ISSUE TITLE
$canReuse defaulting to true stops activation of child ng-outlet

### ISSUE THREAD

**Issue by horyd** [angular/angular#6423]
I'd like to know if this is by design (Angular 1.5rc, component router issue). I have a route "/competition/:id" which loads a component containing it's own $routeConfig and a ng-outlet in it's view. The component is called Competition. The $routeConfig specifies a child route "/leaderboard" that loads a component called Leaderboard. I have an ng-link which successfully loads this route when clicked. So far, so good.

But when I click the back button and then the ng-link again I encounter a bug. I am taken to the correct URL, the Competition component loads correctly in the root ng-outlet but the Leaderboard component is not loaded into the ng-outlet within the Competition component.

I chased the issue down to $canReuse defaulting to true for the Leaderboard component, as a result of this line: https://github.com/angular/angular/blob/master/modules/angular1_router/src/ng_outlet.ts#L125

It strikes me as sort of odd to have canReuse default to true. Wouldn't the general use case be for components to be reinstantiated when routing to them? Even still, why would an ng-outlet not activate in this instance? Would love to know more about what's going on here :) Perhaps one for you @brandonroberts  ;)

**Comment by brandonroberts** [comment]
@horyd :-) one thing that jumps out to me is that you don't have three periods at the end of your competition route `/competition/:id/....`. This lets the router know it has child routes that should be displayed. I can see why can reuse would keep the parent route from reloading, but it shouldn't prevent the child route fromb eing loaded at all. Can you reproduce here in the example below? 

http://plnkr.co/edit/Bb1HteMTdaRAfPXPHUdx?p=preview

**Comment by horyd** [comment]
Thanks for the quick comment @brandonroberts :) I do have the ```...``` in the route. What was odd is that it would work perfectly the first load, but then nothing would load into the child ng-outlet after exiting and then re-entering the same route.

I tried to reproduce exactly as I have it but no luck :S
http://plnkr.co/edit/PP31mHUnKJqUo0THPkVv?p=preview

**Comment by vicb** [comment]
obsolete - former router
