### ISSUE TITLE
routerOnActivate fires before location is updated

### ISSUE THREAD

**Issue by pcroc** [angular/angular#6427]
I have the following in a component that is defined for route `/account/...`

```typescript
public routerOnActivate(next: ComponentInstruction): any {
  console.log(location.pathname);
}
```

When the browser navigates directly to /account/something, the location.pathname is "/account/something", but when I navigate to the component from elsewhere in the SPA (e.g. using `[routerLink]`) the location.pathname contains the previous value, wherever the user navigated from.

The doc for OnActivate states _Defines route lifecycle method routerOnActivate, which is called by the router **at the end of a successful route navigation**._

This means it is impossible to use location for routing decisions, as it is not consistent.

Ideally I wouldn't have to use location to do routing decisions, but `ComponentInstruction` seems to have some shortcomings:
1. componentType is set to the current component, not the child component that would be rendered in `<router-outlet>`
2. urlPath contains just the portion of the URL for this component (i.e. navigate to "/account/something" and it contains just "account")

This means that using ComponentInstruction, I can't tell exactly where the user is going...

**Comment by btford** [comment]
I think in this case, you want to use `router.subscribe`.

I'll leave this open, because it still might be useful to change when `Location` is updated.

**Comment by vsavkin** [comment]
We are no longer maintaining the deprecated router to focus our efforts on making the new router solid.

This is not an issue in the new router.

**Comment by Blasz** [comment]
I believe this is still an issue with the new router.

**Comment by vicb** [comment]
> I believe this is still an issue with the new router.

In such a case please create a new issue and fill out the template. thanks.
