### ISSUE TITLE
Parent child routing with AsyncRoute (Lazy loading)

### ISSUE THREAD

**Issue by mkrishna4u** [angular/angular#6428]
I read the parent child routing in angular2 docs. It is pretty good, but my requirement is to create multilevel routes using angular2. And loading of the component is completely Lazy, means when we require it then only load the components and routes so i used AsyncRoute. So scenario is given below:

TopLinks: Home | Admin
Admin ChildLinks: SecurityMgmt | SystemConfig

Where Home & SecurityMgmt are the default routes, means when user clicks on Admin link or specify the correct url (i.e. http://localhost:8080/myapp/#/admin/securitymgmt) then Admin & SecurityMgmt links should be selected and security management page should be displayed under the child links.

Along with that when user clicks on Admin link then only the Admin.ts and Admin.html files should be loaded. Since SecurityMgmt link is the default so it should also select SecurityMgmt link and load SecurityMgmt.ts and SecurityMgmt.html files. This same behavior should be applicable if user specify the correct url on web browser i.e. 
1. http://localhost:8080/myapp/#/admin - After using this URL router should convert this to http://localhost:8080/myapp/#/admin/securitymgmt because of the default behavior and display the same page as specified using http://localhost:8080/myapp/#/admin/securitymgmt url.
2. http://localhost:8080/myapp/#/admin/securitymgmt

I just want to know how can we define this kind of routing using angular2 async routing.

I did my own way using angular2 Async routing, it is working but my solution is not so clean because i am duplicating the route configuration(As AsyncRoute does not provide all these features). If anybody have good solution to that, please share the same.
Thanks

**Comment by zoechi** [comment]
seems related to 
- #6358
- #6562

**Comment by zoechi** [comment]
Dup of #8861

**Comment by vsavkin** [comment]
We are no longer maintaining the deprecated router to focus our efforts on making the new router solid.

It doesn't look like the issue makes sense in the context of the new router. If you think it does, please reopen the issue.
