### ISSUE TITLE
Acceding to static class attributes, from html template

### ISSUE THREAD

**Issue by juanmrodriguez** [angular/angular#6429]
We wish implement an enumeration for a certain solution, so we try some like this code:

https://plnkr.co/edit/EbuASUc383bsEiI2Ry4R?p=preview

Enumerartion definition:
```javascript
export class BaseEnum {
    constructor(public key: number, public value: string, public moduleName: string, public typeName: string) {
    }

    toString(): string {
        return this.value;
    }

    toValue(): number {
        return this.key;
    }
    getResourceKey(): string {
        return this.moduleName + "." + this.typeName + "." + this.toString();
    }
    static getEnumByKey(key:number):BaseEnum{
        throw new Error("Implement this method on the concrete enum.");
    }
}

export class ProductType extends BaseEnum {

    static undefined = new ProductType(0, "undefined");
    static creditLine = new ProductType(6, "creditLine");

    constructor(key: number, value: string) {
        super(key, value, "common.entities", "productType");
    }

    static getEnumByKey(key:number):BaseEnum{

        let result : BaseEnum = ProductType.undefined;

        switch(key){
            case 6:
                result = ProductType.creditLine;
            break;
            default:
                result = ProductType.undefined;
        }
        return result;
    }
}
```
Component consumer:
```javascript
@Component({
    selector: 'mycomponent',
    template: `
                <h2>Producto Key : {{myproperty.getResourceKey()}} </h2>
            `
})


export class MyComponent{
    @Input() myproperty: ProductType;
    constructor(){}
}
```
The main class:
```javascript
@Component({
    selector: 'app',
    template: `
      <!-- expected use, but did not works -->
      <!-- <mycomponent  [myproperty]="ProductType.creditLine"></mycomponent >-->
      
      <!-- works -->
      <mycomponent  [myproperty]="prodtype"></mycomponent >
  `,
    directives: [MyComponent],
    provider: [ProductType]
})
export class App {
    prodtype:ProductType = ProductType.creditLine;
}

bootstrap(App);
```
Well as can you see when we try to consume the static attribute creditLine of the class ProductType, the execution of the typescript raises an exception saying "Cannot read property creditLine of undefined". But if in the class app we define an attribute called prodtype with the same value it works.
Could you help me with this? Has sense what we try to implement?

Best Regards
Juan Manuel

**Comment by zoechi** [comment]
I wouldn't expect this to work, static is like global and access to globals doesn't work either. Adding a getter to your class like

    get creditLine():ProductType {
        return ProductType.creditLine;
    }

works around this limitation.

**Comment by juanmrodriguez** [comment]
Thanks for the answer @zoechi, one more question you say that "static is like global and access to globals doesn't work either", so i can't call an static method or variable from an template?

**Comment by zoechi** [comment]
@juanmrodriguez I don't really know. I use Angular2 only with Dart and there are several things different anyway, so I can't be sure about TS.
I just tried to provide a workaround until someone with more knowledge chimes in.

**Comment by mhevery** [comment]
> Thanks for the answer @zoechi, one more question you say that "static is like global and access to globals doesn't work either", so i can't call an static method or variable from an template?

correct

**Comment by hidegh** [comment]
This is a nice design flaw, beside other... Wonder how many string-based fallbacks we have to use just to be "modern" Angular2 compilant...
