### ISSUE TITLE
Change detection and SignalR's foreverFrame don't work together

### ISSUE THREAD

**Issue by Tragetaschen** [angular/angular#6431]
I'm using [SignalR](https://github.com/SignalR/SignalR) for a real time server connection. Connecting to the server is embedded in a component and when SignalR's `received` event is triggered, I'm setting both a public member field in my component and `emit` data through an `EventEmitter`.

When SignalR uses Server Sent Events as transport mechanism or long polling (HTTP requests that return when the server has new data), everything works and the changed data is immediately reflected in my component tree.

However, when SignalR uses the Forever Frame transport (a long-running connection that emits `<script>` tags with new data arrives), it regularly takes something like 10 seconds (!) for changed data to land in a child component or for the parent component to receive the emitted event (I've used console.log in `ngOnChanges` in the child component).

This is in Edge. For now, I've reduced the SignalR transports to Server Sent Events and Long Polling and can use my application as expected.

I know it's quite a cross cutting issue, so maybe @davidfowl can help fill in some details as well.

**Comment by zoechi** [comment]
Can you provide some code that shows how Angular code interacts with SignalR code. I guess it is a missing `zone.run(...)`.

**Comment by Tragetaschen** [comment]
The code is along the lines of
```ts
@Component({})
class MyComponent implements OnInit, OnDestry {
    public field: string;
    @Output() public fieldChange = new EventEmitter<string>();

    private connection: SignalR;

    constructor() {
        this.connection = jQuery.connection("/path");
        this.connection.received((data) => this.onReceived(data));
    }

    public ngOnInit() {
        this.connection.start();
    }

    public ngOnDestroy() {
        this.connection.stop();
    }
    
    private onReceived(data: { field: string }) {
        this.field = data.field;
        this.fieldChange.emit(this.field);
    }
}
```

SignalR behind the scenes establishes a transport, deserializes the received data, and calls my `onReceived` member.

**Comment by Tragetaschen** [comment]
My current hypothesis for the the 10ish seconds is my current-time-component that updates every 15 seconds.

**Comment by robwormald** [comment]
its likely that the script tag hack (seriously? that's how it works? amazing...) isn't hooked into the angular zone (and therefore not triggering a change detection check)

Simplest fix is to do something like:
```typescript

constructor(public _zone:NgZone){
  this.connection.received((data) => {
    this._zone.run(() => {
     this.onReceived(data);
    })
  });
}

```

You'd also be best wiring this up inside of a service, and initiating the connection in there. For extra bonus points, wrap it in an Observable / Subject and it'll plug in nicely to Angular2's change detection (and you can use the `async` pipe)

See https://gist.github.com/robwormald/01f5ed49e40505580faa for a similar concept for electron's IPC bus.

**Comment by Tragetaschen** [comment]
Adding the `zone.run` indeed fixes the Forever Frame.

Yeah, I know. Putting this into a separate service (if only for unit testability) is on my list of things to do… Thanks for the help and the sample!
