### ISSUE TITLE
Wildcard route strips param value after '/' on page refresh

### ISSUE THREAD

**Issue by CaptainCodeman** [angular/angular#6433]
A wildcard route that contains forward slash works fine while navigating in-app but when the page is refreshed then anything after the first '/' is stripped from the URL although the correct component is still displayed.

e.g.
```
{ path: '/folder/*id', component: FolderComponent, name: 'Folder'},
```

Navigating through the app to `/folder/2016/photos/dogs` works fine but if the page is refreshed then after loading the correct page the URL reverts to `/folder/2016`

**Comment by CaptainCodeman** [comment]
Incidentally, if the following route is used instead (a regular parameter, not a wildcard) then the routes still work correctly for in-app navigation with the '/' characters not being encoded (a bit of a surprise) but this time refreshing the page causes the route to be completely unrecognized and the default route is loaded instead although the URL is retained.
```
{ path: '/folder/:id', component: FolderComponent, name: 'Folder'},
```

**Comment by davidreher** [comment]
I think this is related to https://github.com/angular/angular/issues/6305

**Comment by CaptainCodeman** [comment]
Yes, it does - thanks (don't know how I didn't find that !)

**Comment by CaptainCodeman** [comment]
This is probably the same issue but manifest in a different way. Maybe it will help ...

Given a wildcard route such as:
```
{ path: '/folder/*id', component: FolderComponent, name: 'Folder'},
```

If the first page I load (or I do a refresh) matches that route, e.g.:

`/folder/2015/parent/child/grandchild`

Then I can navigate around and all works fine *unless* I go to any parent of the original route. Navigating to `/folder/2015` leaves that as the URL in the address bar but the route that gets loaded is the original one again:

`/folder/2015/parent/child/grandchild`

As long as the first page load doesn't match that route then things work OK.

beta2, tried with `routerCanReuse` both true and false (same result)

**Comment by vsavkin** [comment]
We are no longer maintaining the deprecated router to focus our efforts on making the new router robust.

Could you reproduce the problem with the new router and submit a separate issue?
