### ISSUE TITLE
Binding to a property of an svg element throws in Dart transformers

### ISSUE THREAD

**Issue by tbosch** [angular/angular#6439]
Reason: `AbstractHtml5LibAdapter.createElementNS` is not implemented in Dart...

**Comment by tbosch** [comment]
In general, SVG DOM nodes only support changing their values via attributes, not via properties.
I.e. users should not use property bindings but attribute bindings, e.g. `[attr.height]` instead of `[height]`.

We should create a better error message though..

**Comment by domesticmouse** [comment]
Even something as simple as the above explanation and suggested fix would be wonderful.

**Comment by vicb** [comment]
obsolete - dart
