### ISSUE TITLE
Router problem: Link "["Admin"]" does not resolve to a terminal instruction.

### ISSUE THREAD

**Issue by mkrishna4ua** [angular/angular#6440]
i defined async routes as given below:
------------- MainDashboard component ----------------
@Component({
  selector: 'main-dashboard',
  templateUrl: 'app/main-dashboard.html',
  directives: [ROUTER_DIRECTIVES]
})
@RouteConfig([ 
  new AsyncRoute({
    path: '/home',
    loader: () => System.import('app/home/home').then(m => m.Home),
    name: 'Home',
	useAsDefault: true
  }),  
 new AsyncRoute({
    path: '/admin/...',
    loader: () => System.import('app/admin/admin').then(m => m.Admin),
    name: 'Admin'
  })
])
export class MainDashboard {
}

------------------------ Admin Component (Child component + routing)------------------------
@Component({
  selector: 'soii-admin',
  templateUrl: 'app/admin/admin.html',
  directives: [ROUTER_DIRECTIVES]
})
@RouteConfig([  
  new AsyncRoute({
    path: '/securitymgmt',
    loader: () => System.import('app/admin/security-mgmt/security-mgmt').then(m => m.SecurityMgmt),
    name: 'SecurityMgmt'
  }),
  new AsyncRoute({
    path: '/systemconfig',
    loader: () => System.import('app/admin/system-config/system-config').then(m => m.SystemConfig),
    name: 'SystemConfig'
  })
])
export class Admin {
}
-------------
If i specify useAsDefault: true in Admin route config then code works fine. If useAsDefault is not specified in any of the Admin routes then router throws an exception as given below:

EXCEPTION: Link "["Admin"]" does not resolve to a terminal instruction.

Just want to know why we default router is mandatory on child routing for non-terminal node. As per my understanding it should be user choice what they want to do but router should not throw an exception. For example user might not want to select any child node by default.

**Comment by ericmartinezr** [comment]
@mkrishna4ua please move your questions to [gitter's chatroom](https://gitter.im/angular/angular) or StackOverflow. The repository is for bugs and such.

**Comment by mkrishna4ua** [comment]
I mentioned this here because as per my understanding this behavior is not correct. 

I do not know why angular team want to limit user to specify default terminal node for the parent node, framework should be able to handle both scenario.

**Comment by ericmartinezr** [comment]
@mkrishna4ua here you have an [issue](https://github.com/angular/angular/issues/6204) you can read. It mentions a super hyper mega flaw in Router. It's about your same doubt.

**Comment by mkrishna4ua** [comment]
So are we planning to make changes in router or it will still be the same. In my opinion please add the functionality in such a way that no scenario will get left otherwise this router will become useless like the angular1. I hope angular2 team might be having relevant inputs to enhance the router. If you need any help from my side, i can also help in that.

**Comment by biwin** [comment]
If Google sent you here, See [this answer on StackOverflow](http://stackoverflow.com/questions/34317678/routing-in-angular2-link-name-does-not-resolve-to-a-terminal-instruction), It explains well.
