### ISSUE TITLE
Dynamical templateUrl

### ISSUE THREAD

**Issue by Longfld** [angular/angular#6442]
According to ComponentMetadata document, both template and templateUrl as ?string

But only template canbe:
template : "<h1> {{url}} </h1>"

not templateUrl:
templateUrl: "{{url}}"

**Comment by ericmartinezr** [comment]
Yes. because `templateUrl` is a `string` pointing to a file.

**Comment by Longfld** [comment]
In my project, this string that pointing to which file is driven by back-end data. 
templateUrl : "{{Url}}"  
templateUrl : function(){return "{{Url}}"}

**Comment by ericmartinezr** [comment]
Oh, yeah, you can't do that. You are looking for [`DynamicComponentLoader`](https://angular.io/docs/ts/latest/api/core/DynamicComponentLoader-class.html). You should move your questions to [gitter's chatroom](https://gitter.im/angular/angular) or StackOverflow. You'll get more help overthere.

**Comment by Longfld** [comment]
Any reason why can't do that? Just curiosity
 I've search internet and found lots of other developer want this
http://stackoverflow.com/questions/31692416/dynamic-template-urls-in-angular-2

**Comment by SavchenkoVV** [comment]
Very actual issue. It will possible to make component skins.
templateUrl : "{{skincode}}/index.html".

Very sorry that refused
