### ISSUE TITLE
ngFor does not work when used in dynamically loaded comoponent (loadAsRoot())

### ISSUE THREAD

**Issue by oliverjanik** [angular/angular#6444]
See details here: http://stackoverflow.com/questions/33986633/angular-2-dependency-injection-error-on-ngfor-in-dynamically-created-component

This is a showstopper for loadAsRoot. All I get is

```
<!--template bindings={}-->
```

where the repeated elements shoud be.

**Comment by ericmartinezr** [comment]
That's a known issue with loadAsRoot, see https://github.com/angular/angular/issues/6223

**Comment by oliverjanik** [comment]
Ok duplicate of #6223. Closing.
