### ISSUE TITLE
DynamicComponentLoader loadAsRoot reusability?

### ISSUE THREAD

**Issue by oliverjanik** [angular/angular#6445]
When I loadAsRoot and then later dispose() the component the element with selector is gone. I can't loadAsRoot again anymore.

**Comment by RomanGotsiy** [comment]
Faced the same issue.
I believe this is unexpected behaviour: `ApplicationRef .dispose()` shouldn't remove host element

**Comment by zoechi** [comment]
`loadAsRoot()` has several issues #6223 Seems it's only tested for bootstrapping the root component.

**Comment by gdi2290** [comment]
I also have a problem with this for reusing the fake document on the server. It would be great not to remove the rootElement or at least provide an option to ignore removing the element

**Comment by pkozlowski-opensource** [comment]
`DynamicComponentLoader` is deprecated so closing this one as obsolete
