### ISSUE TITLE
Create a way to easily inject or access the root component.

### ISSUE THREAD

**Issue by oliverjanik** [angular/angular#6446]
The use-case is this. I'm developing a library and the name of the root component is unknown to me but I still want to access it's `ElementRef`.

**Comment by mhevery** [comment]
you can have the root component get a hold of `ElementRef` and save it in the property. Then inject root component from the child directive.

**Comment by oliverjanik** [comment]
Well, that was exactly my plan. I don't know how how to do what your second sentence suggests.

**Comment by mhevery** [comment]
Inject `ApplicationRef` and get the type fromther.

**Comment by oliverjanik** [comment]
Can you confirm that `applicationRef.componentTypes[0]` will always contain the root component? 

Maybe the docs need to be updated or just have that exposed as special extra poperty?

**Comment by mhevery** [comment]
yes, that is correct.

**Comment by shlomiassaf** [comment]
Just to understand it better, for people reading this in the future.

In a child component once can request the `ApplicationRef` instance but calling `applicationRef.injector.get(APP_COMPONENT)` doesn't work.

What does work is requesting an `Injector` instance and using it, rather then the injector in `ApplicationRef`

Is it because the injector in `ApplicationRef` doesn't "know" about `APP_COMPONENT` and only child injectors of his "know" about it?

**Comment by amcdnl** [comment]
@mhevery - is there a cleaner way to do this in the final?

So right now this is how I'm going about it:

```
  getRootViewContainerRef(): ViewContainerRef {
    const appInstance = this.applicationRef.components[0].instance;

    if (!appInstance.viewContainerRef) {
      const appName = this.applicationRef.componentTypes[0].name;
      throw new Error(`Missing 'viewContainerRef' declaration in ${appName} constructor`);
    }

    return appInstance.viewContainerRef;
  }
```

which is fine except you HAVE to inject the view ref in the app, like:

```
import { Component, ViewContainerRef } from '@angular/core';

@Component({
  selector: 'app',
  template: `<div>Foo</div>`
})
export class App {
  constructor(
    public viewContainerRef: ViewContainerRef) {
  }
}
```

which is not super ideal.
