### ISSUE TITLE
angular2-polyfills.js gives error when incorporating javascript library AutobahnJS

### ISSUE THREAD

**Issue by bradws** [angular/angular#6447]
Hi team!

There seems to be an error in angular2-polyfills.js when getting a Javascript library (with its related Typescript typings) working in Angular 2 in the Browser.

It's a weird problem: I seem to be able to build and run when there is only 1 line of code from the library, but when I enter a 2nd line, it builds, but doesn't run?!?.

The library is [AutobahnJS](http://autobahn.ws/js/). It's a single .js file and the exact same library is designed to work in both the Browser and Node.
It works perfectly in both the Browser and Node as a normal (non-angular 2) javascript library.
I have it working in Node using Typescript and it's related Typings (There is an [example test](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/autobahn/autobahn-tests.ts) at  the Definitely Typed github page)

I have followed the basic [Angular 2 Quickstart](https://angular.io/docs/ts/latest/quickstart.html) for Typescript and got it working no problems.

HERE is the code and output which DOES work. Note the last line in testAutobahn() is commented out:

```typescript
import {Component} from 'angular2/core';
import autobahn = require('autobahn');

@Component({
    selector: 'my-app',
    template: `
        <h1>Project: {{_projectName}}</h1>
    `
})
export class AppComponent {

    constructor() {}

    private _projectName : string = "EXAMPLE7";

    testAutobahn() {
        var options: autobahn.IConnectionOptions =
         { url: 'wss://demo.crossbar.io/ws', realm: 'realm1' };

        //var connection = new autobahn.Connection(options);    //  <- THIS line commented out, app runs fine
    }
}
```
![output-working](https://cloud.githubusercontent.com/assets/9676439/12286483/446ef944-b9ff-11e5-9c44-607860fe1d3c.jpg)

HERE is the code and output which does NOT work. Note the last line in testAutobahn() is left in:

```typescript
import {Component} from 'angular2/core';
import autobahn = require('autobahn');

@Component({
    selector: 'my-app',
    template: `
        <h1>Project: {{_projectName}}</h1>
    `
})
export class AppComponent {

    constructor() {}

    private _projectName : string = "EXAMPLE7";

    testAutobahn() {
        var options: autobahn.IConnectionOptions =
         { url: 'wss://demo.crossbar.io/ws', realm: 'realm1' };

        var connection = new autobahn.Connection(options);    //  <- THIS line left in, app not run!
    }
}
```
![output-notworking](https://cloud.githubusercontent.com/assets/9676439/12286516/99c23d66-b9ff-11e5-8e6f-7d718e707851.jpg)

The only difference is the commenting/uncommenting of that line.
The error seems to come from angular2-polyfills.js and system.src.js

I have used  'tsd' to install all the typings. They all look correct and my editor [Atom](https://atom.io/) has intellisense on the autobahn.* types just fine.

Possible issues?:
1.    Using AutobahnJS v0.9.9 but the Typings seem to be for v0.9.6
            -> I can't see this being a real problem
2.    When building, Typescript emits the Javascript code, but it does give an error:
"Subsequent variable declarations must have the same type.  Variable '$' must be of type 'cssSelectorHelper', but here has type 'JQueryStatic'."
            -> I have resolved this error by simply commenting out the line   /* declare var $: JQueryStatic; */   in the jquery.d.ts file (I'm not using JQuery anyway)

Using Typescript v1.7.5, Angular 2 Beta 0 with the package.json, tsconfig.json and boot.ts files as per the [Angular 2 Quickstart](https://angular.io/docs/ts/latest/quickstart.html) for Typescript
My end goal is to get an Angular2 Service working with AutobahnJS (but just at the baby steps at the moment).

Any help would be greatly appreciated....

**Comment by david10sing** [comment]
Hi Brad,

For the JQueryStatic issue just declare var jQuery: any.

Also I think you need to declare something in the constructor. There are some stuff missing to be able to get the Autobahn.js to work.

**Comment by bradws** [comment]
Hey David,

Where do i put the declare var jQuery: any - in the app.component.ts file?
Which constructor are you talking about - which class/file?

Cheers.

**Comment by robwormald** [comment]
The error you are seeing is typically indicative of a misconfigured import path, and the server sending back an HTML file (hence the `<` in the error) - typescript errors typically manifest at compile time rather than runtime.

**Comment by robwormald** [comment]
(and you're seeing the error come from polyfills as that's where it's being caught)

**Comment by bradws** [comment]
But I get no build errors from Typescript though. The import command in app.component.ts:

```typescript
import autobahn = require('autobahn');
```

seems to work. Well, at least I think so as it gives me no reason to think that it doesn't. I'm not 100% sure how to verify it loads it correctly. There are no Typescript build errors and my editor (intellisense) doesn't complain.

If I change it to some other folder like:

```typescript
import autobahn = require('/node_modules/autobahn/lib/autobahn.js');
```
or
```typescript
import autobahn = require('../node_modules/autobahn/lib/autobahn.js');
```

Typescript *does* gives an error saying 'autobahn' cannot be found (and so does my editor in intellisense)

My folder structure is:

/app/app.component.ts
/app/boot.ts

/node_modules/*       <- All the Angular 2 node modules as per normal (including the Autobahn javascript library) 

/typings/autobahn/autobahn.d.ts
/typings/jquery/jquery.d.ts
/typings/when/when.d.ts

/index.html
/package.json
/tsconfig.json

I have no
```typescript
 /// <reference path="autobahn.d.ts"/> 
```
command anywhere.
Note that I have got the non-angular2, Typescript-only example working fine (i.e. the [test provided at Definitely Typed github page](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/autobahn/autobahn-tests.ts)).

How do I see this HTML that is returned to the browser? Would this possibly help with fining out why it doesn't work?

**Comment by mhevery** [comment]
seems like configuration issue. Reopen with proper plunker reprocase.
