### ISSUE TITLE
CSS @import with root path "/" bug

### ISSUE THREAD

**Issue by IHateGlamour** [angular/angular#6449]
When importing a css from inside another components css using the root path, the imported css file gets included globally affecting all components. Making it use a relative path solves this issue. Could someone tell me if this is ok, sorry if I did write something stupid...

For example if you have in child component template: 
`<h1>Child Header</h1>`
and in childs css file you import another css using root path:
`@import '/styles/component.css';`
it gets translated into:
`<style>@import '/styles/component.css';</style>`
affecting all components because it imports the css globally.

using relative path:
`@import '../styles/component.css';`
works ok, translating it to 
`<style>h1[_ngcontent-fba-2]{background-color:red;}</style>`

**Comment by vicb** [comment]
related to #4974
