### ISSUE TITLE
Jitting a template in IE11 generates invalid JS

### ISSUE THREAD

**Issue by Tragetaschen** [angular/angular#6450]
In beta.1 (so 7ae23ad is likely the culprit) in IE11, the generated JavaScript from jitting contains syntax errors:

```js
var appProtoView0_function SvgDefsImpl() {}0 = AppProtoView.create(resolvedMetadataCache, 1, [], {});
var renderType56_function SvgDefsImpl() {} = null;
var styles57_function SvgDefsImpl() {} = styles;
```

Instead of a sanitized name, `function SvgDefsImpl() {}` appears in the variable names on virtually every line.

**Comment by mhevery** [comment]
dub op #6516

**Comment by mlaval** [comment]
Dup of #6501, see my comment there: https://github.com/angular/angular/issues/6501#issuecomment-179502363
