### ISSUE TITLE
Cannot access parent view in outer

### ISSUE THREAD

**Issue by eesdil** [angular/angular#6451]
I would like to access the main (parent) component in a router.
But I am getting error:

    Cannot resolve all parameters for ChildView(?). Make sure they all have valid type or annotations.

if I am trying to access the parent component it without router it is working fine. Is it a bug or is it like this by design?

the plunkr (click on the ):
http://plnkr.co/edit/WU5NITvt5w27ZqAuYKbk?p=preview

**Comment by ericmartinezr** [comment]
First your parent component is called `ParentView`, not `Parent`. Second [classes in javascript are not hoisted](http://blog.thoughtram.io/angular/2015/09/03/forward-references-in-angular-2.html) so you need to use `Inject` and `forwardRef`

```
class ChildView {
  constructor(@Inject(forwardRef(() => ParentView) private parent: ParentView) {
    parent.hello();
  }
}
```
And that still seem not to work, probably related to https://github.com/angular/angular/issues/4452

You can get more help in [gitter's chatroom](https://gitter.im/angular/angular), StackOverflow and such.

**Comment by eesdil** [comment]
thanks, yes missed the forward class, but my implementation is giving the same error with importing so didn't notice it.
Actually I can pass the functions into the new components with AsyncRoute, but this looked shorter and more transparent.

**Comment by eesdil** [comment]
Does it mean that accessing the parent as a router child with DI won't be supported? thanks
