### ISSUE TITLE
RXJS deps to beta.1

### ISSUE THREAD

**Issue by frankbenoit** [angular/angular#6452]
Hi

please allow minor updates in the dependency of rxjs.
now there is
rxjs  5.0.0-beta.**1** 

Frank

**Comment by meriturva** [comment]
+1

**Comment by mhevery** [comment]
We will be updating RxJS on on going basis. No need to track it as a bug.

**Comment by Faradax** [comment]
Observables are half broken in Rxjs 5.0.0-beta.0, have a look here: https://github.com/ReactiveX/RxJS/commit/8f1fc93fd9d44c37ea047d2a3d43c2efb577495a
You can't do any meaningful error handling and you can't even fix it locally because it's a required dep. I'd suggest the same as OP.
