### ISSUE TITLE
SetAttribute on Renderer throws error

### ISSUE THREAD

**Issue by GreenToast** [angular/angular#6454]
The error "Cannot read property 'boundElements' of undefined" is thrown if I try to set the draggable-attribute or another with the renderer-method. But works fine when set directly.

http://plnkr.co/edit/B3KJuxnXpj0qmnWrBjck?p=preview

**Comment by ericmartinezr** [comment]
Please fix your plnkrs.

**Comment by GreenToast** [comment]
Sorry my Plunkr didn't save correctly. Works now again.

**Comment by eesdil** [comment]
In beta.0 you have to set the elementRef not the nativeElement. It changed in bet.1

**Comment by pkozlowski-opensource** [comment]
@eesdil is right - this is a documented breaking change: https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes
