### ISSUE TITLE
Using Component styles results in conflicting html/body styles

### ISSUE THREAD

**Issue by mark-norgate** [angular/angular#6455]
Hi there

I have two components in my Angular 2 app and they each define different styles in SASS files. Unfortunately it appears that both components' styles are being loaded for both components, resulting in conflicting html and body styles.

My component definitions looks like this:
```
@Component({
    selector: 'signup',
    directives: [RouterOutlet, RouterLink],
    styles: [require('../sass/signup.scss').toString()],
    template: require('./signup.component.html')
})
```
and
```
@Component({
  selector: 'signin',
  directives: [RouterOutlet, RouterLink],
  styles: [require('../sass/signin.scss').toString()],
  template: require('./signin.component.html')
})
```

The stylesheets look like this:
```
// signup.scss
html, body {
    height:100%;
    background-color: #eaeaea;
    display: flex;
    align-items: center;
    justify-content: center;
    display: -webkit-flex;
    -webkit-align-items: center;
    -webkit-justify-content: center;
}
```
and
```
// signin.scss
html, body {
    height:100%;
    background-color: #373746;
    display: flex;
    align-items: center;
    justify-content: center;
    display: -webkit-flex;
    -webkit-align-items: center;
    -webkit-justify-content: center;
}
```
The `backround-color` of both components is `#373746'.

Any thoughts? I could easily create two separate `<div>`s with with ids or classes but that would be a workaround; as my application grows I don't really want to be keeping track of which styles are defined for which components.

Thanks, Mark

**Comment by zoechi** [comment]
So,  only one of these components is shown at one time and you want the only the styles applied from the currently shown component?

**Comment by mark-norgate** [comment]
Well @zoechi I am quite satisfied with [this explanation](http://stackoverflow.com/questions/34766570/using-component-styles-results-in-conflicting-html-body-styles/34767358#34767358) of the issue. It is inappropriate to try to style anything other than the component using the `styles` property; that is, trying to style the `body` or `html` is going to be problematic. I will make the components full-screen and style them that way instead.

**Comment by user414** [comment]
Was having this issue but redesigned and no longer need it, however just for info using 
```
@Component({
  ...
  encapsulation: ViewEncapsulation.None,
  ...
})
```
works and I find it better then original solution.
