### ISSUE TITLE
[Mobile Chrome] ngControl(select[multiple]): input event won't fire

### ISSUE THREAD

**Issue by ThiagoT1** [angular/angular#6457]
Mobile Chrome wont fire input event when select [multiple] interacted with,  thus breaking ngControl.

A current workaround is to subscribe to nativeElement change event an call ngControl updateValue from there.

Its also possible to implement select[multiple] selectedOptions handling with this approach, while there's no builtin support.

**Comment by zoechi** [comment]
looks like a dup of #6573

**Comment by chybie** [comment]
It happens in RC 4, not working select[multiple] is not working in Firefox 47 and IE Edge 11. plunkr here http://plnkr.co/edit/7BcTcV?p=preview. The new form control.
.

**Comment by kara** [comment]
@chybie That plunker link doesn't seem to be working. Do you mind re-posting?

**Comment by kara** [comment]
@chybie  Since there's no repro case and haven't heard anything in a while, I'm going to close this. Please feel free to open a new issue with a working Plunker repo if it still persists.
