### ISSUE TITLE
The onChanges callback isn't called when updating the content of a bound object

### ISSUE THREAD

**Issue by templth** [angular/angular#6458]
Hello,

Following a question on [StackOverflow](http://stackoverflow.com/questions/34761224/angular2-child-property-change-not-firing-update-on-bound-property/), I wonder why the `onChanges` is called when a bound object is updated (a new value) but not when the content of a bound object is updated.

Here is the following use case:

```javascript
export class AppComponent implements OnChanges {
    test: { one: string; } = { one: "1" };
  
    ngOnChanges() {
      console.log('updated');
    }
    
    clicked() {
        // The ngOnChanges method is called
        this.test = { one: 3 };

        // The ngOnChanges method isn't called
        this.test.one = "4";
    }
}
```

Thanks for your help!
Thierry

**Comment by pkozlowski-opensource** [comment]
By default change detection system does reference comparison for objects - it doesn't do deep comparison by default as it would be too costly and would negatively impact performance. 

If you need to deep-observe object for changes you can do it explicitly using key-value differs. You  can check implementation of the [NgStyle directive](https://github.com/angular/angular/blob/master/modules/angular2/src/common/directives/ng_style.ts) for an example usage of a differ.

**Comment by templth** [comment]
Thanks very much, Pavel! That makes sense ;-)

**Comment by templth** [comment]
You tell "by default change detection ...". Is it possible to change this behavior in applications?

Thanks!

**Comment by mrajcok** [comment]
Just FYI, if you want to do the explicit checks yourself, you need to implement ngDoCheck() (which is called every change detection cycle) and do the checks inside that method.  (This is what the NgStyle directive example shows, but the ngDoCheck() part might not be obvious.)
