### ISSUE TITLE
Router Link does not remain active with optional parameters

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#6459]
If I navigate to a route without any optional parameters, the router link for that route is displayed as active. If I navigate to that same route with optional route parameters, the router link is no longer marked as active. 

Example: http://plnkr.co/edit/LVYtuiQ8O2d52UrrxV2e?p=preview

As long as I'm on the `Active` route, its router link should be marked as active even if there are optional parameters included.

**Comment by crisz** [comment]
This issue has been closed in April 2016, a year later I'm still facing the same problem. Why?

**Comment by Aaltuj** [comment]
having the same issue here

**Comment by astec** [comment]
Probably it make sense to raise a new issue with a link to this one. I doubt anyone from dev team is following closed issues.

**Comment by Aaltuj** [comment]
Never mind. Forgot the exact property to set to false

**Comment by smartm0use** [comment]
Any news about this issue?
