### ISSUE TITLE
Error in TypeScript documentation

### ISSUE THREAD

**Issue by fabienbellanger** [angular/angular#6462]
Hi,

i think there is an error on TypeScript documentation > Developer Guides > 6. Dependency Injection.
import {Injectable} from 'angular2/angular2'; should be import {Injectable} from 'angular2/core';

Thanks for your work!

**Comment by BeastCode** [comment]
Fixed, created a PR in angular.io: https://github.com/angular/angular.io/pull/738

**Comment by pkozlowski-opensource** [comment]
Closing as duplicate of https://github.com/angular/angular.io/pull/738
