### ISSUE TITLE
Using ngControl inside of element with class binding throws an error

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#6463]
This error was introduced in beta.1. If I have a form with an input wrapped in a div that is styled through a class binding an error is thrown.

```js
EXCEPTION: No provider for ControlContainer! (NgControlName -> ControlContainer)
```

Component 

```js
@Component({
  selector: 'app',
  template: `
    <form #f="ngForm">
      <div [class]="styles.input">
        <input type="text" placeholder="First Name" ngControl='firstName' #firstName="ngForm">
      </div>
    </form>
  `
})
export class App {
  styles: Object = {input: 'test'};
}
```

This same form works fine in beta.0. If I remove the `[class]="styles.input"` it works fine also

Beta.1 example: http://plnkr.co/edit/V1pnB23ryBROwIg5ofOr?p=preview
Beta.0 example: http://plnkr.co/edit/J8ReQ078I4Ul3DqlCAhi?p=preview

**Comment by ericmartinezr** [comment]
dup of https://github.com/angular/angular/issues/6374 :(

**Comment by brandonroberts** [comment]
:-1:

**Comment by saranyapm** [comment]
use [ngFormControl]="formName.controls['name']"  instead of ngControl="name"
