### ISSUE TITLE
ngFor for setting a property in stead of a var.

### ISSUE THREAD

**Issue by SanderElias** [angular/angular#6464]
This is something that is bothering me.

```
  <someComponent *ngfor="#video in videos" [video]='video'> 
```

I'm repeating video 3 times, and I'm creating an extra temp variable.

```
  <someComponent *ngfor="[video] in videos"> 
```

Makes much more sense to me. Is this something that is possible? Or is it a bad idea to begin with?

**Comment by kylecordes** [comment]
I have noticed this duplication in my code also, but on balance my recommendation is against adding more complexity to the syntax.

**Comment by SanderElias** [comment]
@kylecordes, It is not adding anything, It is extending what is already there in a (in my eye's) logical way.

**Comment by zoechi** [comment]
It clearly wraps each item in an array ;-)

**Comment by mhevery** [comment]
I think this further complicates the syntax, for benefit in only few cases. We will not implement this for now.
