### ISSUE TITLE
Can't utilize ngIf on a template selector

### ISSUE THREAD

**Issue by kamrenz** [angular/angular#6470]
I have been trying to only show a component based on an ng-if property. If the property is false I don't want the component to render. If the property is true I want the component to render.
1) An expepction is thrown: No provider for TemplateRef! (NgIf -> TemplateRef)
```
 <report-form [ngIf]="isFormVisible"></report-form>
```
2) An exception Template parse errors:
```
<report-form *ngIf="isFormVisible"></report-form>
```

Is this not possible? Do I need to pass a boolean into the component and handle the ng-if inside the component?

**Comment by pkozlowski-opensource** [comment]
`<report-form *ngIf="isFormVisible"></report-form>` should work. Could you send a plunker demonstrating a problem?

**Comment by mhevery** [comment]
closing as no repro case.

**Comment by ilune** [comment]
Hello,

Got the same problem:
This code works:
`<div *ngIf="races.length > 0"><h2>Races</h2></div>`

And not this one:
`<div [ngIf]="races.length > 0"><h2>Races</h2></div>`

**Comment by ericmartinezr** [comment]
@ilune read the [documentation](https://angular.io/docs/ts/latest/guide/template-syntax.html#!#star-template)

**Comment by kamrenz** [comment]
After digging in it seems I had issues with my SystemJS configuration.
