### ISSUE TITLE
Suppress dartdocs for secondary libraries

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#6471]
As of 1.14-dev.7.0 Dart SDK ships a way to suppress dartdocs for chosen parts of the code via a special `<nodoc>` comment. We should use it to suppress docs for duplicates caused by reexporting.

**Comment by naomiblack** [comment]
Specifically, we should suppress libs present in the dartdoc, but not shown in the API docs on angular.io for TS.

**Comment by naomiblack** [comment]
This can be done currently by running the command 
```
pub global run dartdoc --include angular2.common,angular2.animate,angular2.instrumentation,angular2.platform.browser,angular2.router,angular2.router.testing,angular2.testing
```

Output is on a server at https://ngdartdoc-dev.firebaseapp.com/
---
See https://github.com/astashov/dartdocs.org/issues/26 for updating what dartdocs.org does

**Comment by pkozlowski-opensource** [comment]
I guess this is obsolete now as Dart-specific.
