### ISSUE TITLE
"get diagnostic()"

### ISSUE THREAD

**Issue by taxinvoice** [angular/angular#6476]
What is "get diagnostic()" used for and where do i see this info?

**Comment by zoechi** [comment]
What `get diagnostic()`? Can you please add a link?

**Comment by pkozlowski-opensource** [comment]
There is no `diagnostic()` occurrence in the current ng2 code-base so I can't see how it is linked directly to the framework. Closing as there is no enough info here and we don't have `diagnostic()` in master.

**Comment by intellix** [comment]
My guess is he's referencing line 21 of the hero-component here: https://angular.io/docs/ts/latest/guide/forms.html

**Comment by pkozlowski-opensource** [comment]
> My guess is he's referencing line 21: get diagnostic() { return JSON.stringify(this.model); } of the hero-component here: https://angular.io/docs/ts/latest/guide/forms.html

Maybe :-) In any case any doc-related issues need to go to: https://github.com/angular/angular.io
