### ISSUE TITLE
Flip attr/value in @Component.bind

### ISSUE THREAD

**Issue by mhevery** [angular/angular#648]
Currently 

```
@Component({
  bind: {
    'attr-name': 'propertyName'
  }
})
class MyComponent {
  propertyName;
}
```

should be:
```
@Component({
  bind: {
    'propertyName': 'attr-name'
  }
})
class MyComponent {
  propertyName;
}
```

The reason for this is that right now we can have multiple properties mapping to the same property name. This is silly. A given property can only have a single mapping, (but it is possible that the same attribute is mapped to multiple properties. Especially after #627)

**Comment by jelbourn** [comment]
This is also good because it more closely matches the angular 1.X directive scope structure. Every time I've had to write a binding so far, I've had to remember "Right, this is backwards."

**Comment by pkozlowski-opensource** [comment]
@mhevery I've sent a PR for this: #684 but I was wondering if we still got `event` bindings as described in https://github.com/angular/angular/blob/master/modules/angular2/docs/core/02_directives.md#decorators

Or is it left-over in the docs?

**Comment by mhevery** [comment]
yes `event` bindings are part of Angular2. Not sure if they are implemented
yet.
