### ISSUE TITLE
Renderer deleting too much list items before re-rendering them

### ISSUE THREAD

**Issue by EnguGH** [angular/angular#6481]
Hi,
I'm running into an issue with the renderer : let's say I have an observable list `(a, b, c)` and I want to remove `b`: the renderer will first remove `c`, then delete `b`, then re-render `c`.
Which is not really a problem when using DOM cause it happens really fast, but it can be a huge problem when using a custom renderer with a tool having adding or removing animations.

Not 100% sure I'm not doing something wrong with Observable though, it's pretty new to me ^^
To see it please clone this project : https://github.com/EnguGH/angular2-tests
Then run `npm install` and `npm run browsersync`. Then put a breakpoint in `node_modules/angular2/src/platform/dom/dom_renderer.js` at `detachFragment`, line 225. Sorry but I haven't found an easier way to see the problem !

EDIT : since update to Beta1, break has now to be put at line 146.

Thanks !

**Comment by vicb** [comment]
I still a problem, please re-open an issue with a plunker based on v2.0.1.

One thing that could probably help here is to use `ngTrackBy` and have an "id" field in your objects.
