### ISSUE TITLE
[beta.1] Injecting service in Router-Component causes a polyfill-error

### ISSUE THREAD

**Issue by fr3dm4n** [angular/angular#6484]
I have the router component AppComponent:

``` typescript
@Component({
    selector: 'app'
})
@View({
    templateUrl: '/app/components/app/app.html',
    directives: [
        ROUTER_DIRECTIVES,
        ChuckComponent,
        MapComponent,
        TelemetrieComponent
    ],
    encapsulation: ViewEncapsulation.None
})
@RouteConfig([
    {path: '/gmap', name: 'Gmap', component: MapComponent},
    {path: '/chuck', name: 'Chuck', component: ChuckComponent},
    {path: '/wc-check', name: 'WcCheck', component: WebComponentCheckComponent},
    {path: '/', component: StartComponent, useAsDefault: true}
])
export class AppComponent implements AfterViewChecked{
   [...]

    constructor(elementRef:ElementRef, location:Location) {
        [...]
    }
```

and a service class:
```typescript
@Injectable()
export class TelemetrieService{
    private _bootstrapMarkerName:string="boostrap";
    private _start:number=0;

    constructor(){
        this._start=window.performance.timing.navigationStart;
    }

    [...]
}
```

Everything is fine until I add TelemetrieService to the AppComponent:
```typescript
constructor(elementRef:ElementRef, location:Location, telemetrieService:TelemetrieService) {
```

Browser shows me following error, but nothing more:
![image](https://cloud.githubusercontent.com/assets/6654064/12325992/4adb09a6-bace-11e5-8e91-2af4a492efc7.png)

The service is known through the bootstrap function:
```
bootstrap(AppComponent, [
    [...]
    TelemetrieService,
    provide(APP_BASE_HREF, {useValue : '/'}),
    provide(UrlResolver,{useClass:MobileUrlResolver})
]);
```

I am not sure if this is a bug, so apologies if I missed something.

**Comment by brandonroberts** [comment]
Are you importing ViewEncapsulation from `angular2/core`? Seems like its missing

**Comment by fr3dm4n** [comment]
Of course, all imports are up2date. My IDE is telling me missing imports btw

**Comment by brandonroberts** [comment]
@fr3dm4n can you reproduce in a plunker? Nothing else jumps out: Here is a starter: http://plnkr.co/edit/FdtB199NmtX4iWVV1oKX?p=preview

**Comment by fr3dm4n** [comment]
I will try to

**Comment by fr3dm4n** [comment]
ah, I apologize!
I extended the UrlResolver, because in Cordova a ressource from an absolute Url like `/app.html` was resolved to `file:///app.html` instead of `file:///android_asset/www/app.html`

After removing it, all is fine! Its my fault -> Sry and thx for your help
