### ISSUE TITLE
@Input only works if the type is declared (non typescript)

### ISSUE THREAD

**Issue by iksose** [angular/angular#6486]
```javascript
export class List {
  @Input() guests
}
```
Won't work, but if I specify `guests = []` it will work (receive the passed val). I think this is preventing me from binding to Observables.

Even stranger, guests = null, or basically anything but undefined, sees and updates props. I'm using babel 5 with stage 0, so I'm not ruling that out as the culprit. In fact I almost guarantee that's where the issue lies. But perhaps someone more intimate with Typescript could tell me if it's using one of [these imported angular decorators](https://github.com/shuhei/babel-plugin-angular2-annotations/blob/master/test/integration/parameter-decorator-alternative.spec.js), like `@Reflect.metadata('parameters', [[new AttributeMetadata('guests')]])`, behind the scenes?

Just weird that with ES2015 I have to specify a type for @Input to bind

**Comment by woppa684** [comment]
You know you need @Input() right, so, including the parentheses? Don't know if that solves it but I'm pretty sure it's needed.

**Comment by iksose** [comment]
Oops, yeah I was using the parens just forgot it in my snippet. Anyways, this doesn't actually stop me from binding to Observables or using the async pipe, just other primitive values.

**Comment by shuhei** [comment]
This is a bug of babel 5 and babel-plugin-transform-decorators-legacy for babel 6. https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy/pull/14

**Comment by vicb** [comment]
Not related to Angular.
