### ISSUE TITLE
route normalization bug

### ISSUE THREAD

**Issue by pjpsoares** [angular/angular#6488]
When you create a route using the 'as' on the route definition the route normalization sets the 'name' on the route with the content on the 'as'. The problem is that is changing the actual object. So if you're to provide the same component again to the route it will break!
This is not particularly important for normal use cases, but for testing purposes it's really important, since you're going to use the same component for each test to define the routes.

**Comment by pjpsoares** [comment]
It's a fairly simple bug to fix and I can fix it if you want, but it seems the best approach is jut to stop supporting the as.

**Comment by ericmartinezr** [comment]
Yes, `as` was renamed to `name`  long ago (see https://github.com/angular/angular/commit/7d83959be56780b1ba9cf7efb6cd96452bec2761). Eventually it will be removed, so it's as simple as stop using `as`.

**Comment by mhevery** [comment]
sounds like there is no actual work to be done. Closing. (re-open if you think this is a mistake)
