### ISSUE TITLE
TypeError: viewFactory_<name>0 is not a function

### ISSUE THREAD

**Issue by Necroskillz** [angular/angular#6489]
I don't even know how to describe this issue. See this example:

http://plnkr.co/edit/41jAiSpDiGTZKfntVB13?p=preview

Because the component `<faulty>` is both in the component with `<ng-content>` and the components which is rendered inside of that `<ng-content>` it throws the error. If you delete `<faulty>` in either place it works.

This used to work in `beta.0`

**Comment by rigoleto** [comment]
I've been struggling with the exact same issue, and likewise worked out that it comes up in beta1 but not beta0. 

It appears to have to do with repeating `<faulty>`, I was able to reproduce it without using `<ng-content>` at all.

**Comment by ericmartinezr** [comment]
This is a dup of https://github.com/angular/angular/issues/6404, and there's already a PR for it https://github.com/angular/angular/pull/6474

**Comment by Necroskillz** [comment]
Cool, didn't notice that. Didn't really know how to search for this.
