### ISSUE TITLE
DynamicComponentLoader.loadIntoLocation documentation should note whether "type" can be null

### ISSUE THREAD

**Issue by jbdeboer** [angular/angular#6497]
Our app may pass a null "type" to DynamicComponentLoader.loadIntoLocation. The behaviour of this case should be defined: e.g. Angular will throw an exception, or silently do nothing or something else..

**Comment by mohammedzamakhan** [comment]
@mhevery This can be closed since DynamicComponentLoader.loadIntoLocation has been removed from Beta16

**Comment by pkozlowski-opensource** [comment]
Closing since DynamicComponentLoader is deprecated.
