### ISSUE TITLE
Question: How to join early adopter program. 

### ISSUE THREAD

**Issue by satish860** [angular/angular#650]
As a consultant I have recommend a application to be built with angular . But i want to understand the changes happening and provide my feedback as the framework get shape . How can I get involved in the same.

**Comment by gdi2290** [comment]
There isn't an official program but if there were one then I would recommend you build a simple app to to gage where the api is going. I would recommend checking out [angular2's todo app by davideast](https://github.com/davideast/ng2do). I would also suggest you submit issues for any concerns you may have about the api so long as you check previous issues before submitting them.

**Comment by mhevery** [comment]
closing as there is no actual work for us.
