### ISSUE TITLE
`ControlGroup` `errors` doesn't contain errors of its controls (Dart)

### ISSUE THREAD

**Issue by zoechi** [angular/angular#6504]
From the codedoc of `ControlGroup`

> * A `ControlGroup` aggregates the values and errors of each [Control] in the group. 

but even when controls in `controls` have errors and the `status` of `ControlGroup` is `"INVALID"` `errors` in `ControlGroup` is `null`

Code at https://github.com/bwu-dart-playground/dart_playground/blob/master/angular2/bug_reports/issue6504_controlgroup_errors_null/lib/app_element.dart

**Comment by zoechi** [comment]
Just found in the change log for 2.0.0-alpha.46 (2015-11-11)

> Previously, the controlsErrors getter of ControlGroup and ControlArray returned the errors of their direct children. This was confusing because the result did not include the errors of nested children (ControlGroup -> ControlGroup -> Control). Making controlsErrors to include such errors would require inventing some custom serialization format, which applications would have to understand. Since controlsErrors was just a convenience method, and it was causing confusing, we are removing it. If you want to get the errors of the whole form serialized into a single object, you can manually traverse the form and accumulate the errors. This way you have more control over how the errors are serialized.

Then the docs should be updated

**Comment by PascalPrecht** [comment]
Turns out this is not a bug but by design.
