### ISSUE TITLE
 Route with component without selector results in mysterious error.

### ISSUE THREAD

**Issue by thso** [angular/angular#6509]
When a RouteDefinition uses a component without a selector:

    @RouteConfig(const [
      const Route(path: '/hello', name: 'Hello', component: HelloComponent)
    ])
    class AppComponent {}
    
    @Component(
      template: "Hello"
    )
    class HelloComponent {}

this result in the following mysterious error when attempting to navigate to `/hello`:
    `EXCEPTION: Invalid argument(s)`

Adding a selector, of course, solves the issue, but could we be more specific with the error here?

**Comment by zoechi** [comment]
Component without selector doesn't seem to be supported anymore 
- #6146
otherwise dup of #3464

**Comment by mhevery** [comment]
Closing as dum of #3464
