### ISSUE TITLE
How to get element style values from within directive?

### ISSUE THREAD

**Issue by esugoi** [angular/angular#6515]
Hello,
I have a directive and would like to read\observe an element style changes.

@Directive({
  selector: '[test]',
})
constructor(el: ElementRef, renderer: Renderer) {
  renderer.setElementStyle(el, 'width', '10px');

  // ?????
  renderer.getElementStyle(el, 'width');
}

I know I can set classes, styles and attributes using the Renderer interface. Is there any way to read the element current values or bind to them?
Something like the HostListener or HostBinding. But, as I undestand, the HostListener is only for events and the HostBinding is only for settings values from the directive to the host element.

I'm avoiding using the el.nativeElement, since I wanted to run this code on a web worker.
The way I see now would be binding these values as directive properties.

Thank you.

**Comment by ericmartinezr** [comment]
+1 to this, it makes sense. I asked about that a few days ago and nothing. 

>I'm avoiding using the el.nativeElement, since I wanted to run this code on a web worker.

In beta.1 that changed, quoting (see breaking changes for beta.1)
 
>renderer.setElementProperty, ..setElementStyle, ..setElementAttribute now take a native element instead of an ElementRef

I don't think that really makes sense. They have warned us about using nativeElement, but now Renderer depends on it. Probably something changed and we should not worry about that anymore?

Anyway, using Renderer to set classes/styles/attributes/etc and nativeElement to retrieve them doesn't really makes sense.

**Comment by esugoi** [comment]
Thanks for the answer, eric! :)
Indeed, I was using the beta0 version still and did not see the Renderer API changed on beta1.
I will try playing a bit with the beta1 version. But at first glance, there doesn't seem to be anything like a 'read' or 'get' version of the element.

There seems to be two new interesting methods:
abstract listen(renderElement: any, name: string, callback: Function): any;
abstract listenGlobal(target: string, name: string, callback: Function): Function;

Do you might know what they do?

Thank you!
Best regards!

**Comment by zoechi** [comment]
Looks like you can register event handlers for the element referred by `renderElement` or on a global event source like `window`.

**Comment by esugoi** [comment]
Cool, very nice!
There are other methods, but I'm finding difficult to understand what type of object does it expect to receive. They removed all documentation from it. :(
I would like to know what types the paremeters 'parentElement', 'hostElement' and 'renderElement' could be. Until know I know the 'renderElement' can be an HTML element. But what about the others?
The createElement was very useful to me, since I was trying to append a new element, but was not sure how to do that with the Renderer interface. Now I would like to know how to remove it.

Thanks again for the answers. :)

Best regards!

**Comment by esugoi** [comment]
I see there is a Ruler service. Is it possible to use this service to obtain an element's position and size, in the current version? Also, does this service use any DOM function directly or is there an abstraction  to enable us to run on a worker\service?

I tried importing the service, but it doesn't seem to be acessible.
Importing from 'angular2/src/platform/browser/ruler' give me this error:
Error: XHR error (404 Not Found) loading http://localhost:5000/angular2/src/platform/browser/ruler(…)

**Comment by mhevery** [comment]
Render should be write only (so that your app would run even in headless mode), for this reason render would never have methods for reading.

Why do you need to get style information? Presumably You are the one who wrote the styles in the first place? Or are you trying to get the element position? In which case Ruler is your friend.

Could you better describe the use case of what you are trying to achieve, rather than ask for a specific primitive?

**Comment by ThiagoT1** [comment]
@esugoi 
Ruler is not injectable at this point. it should be newed, more or less like this:
```javascript
this.domAdapter = new ng.platform.browser.BrowserDomAdapter();
this.ruler = new ng.platform.browser.Ruler(this.domAdapter);
```

**Comment by esugoi** [comment]
Hello, mhevery :)
Actually, I am trying to get the elements position and dimensions. Yes, I thought about using the Ruler service later. But my question is if it's safe to use this Service on a ui/webworker scenario?

Thanks, ThiagoT1. ;)
I am kind of new to javascript module system. Do I need the add something to use 'require' inside the browser? Do you know if I change the BrowserDomAdapter to Parse5DomAdapter it's possible to use this with a web worker?

Thanks guys!

**Comment by ThiagoT1** [comment]
@esugoi 

See this plunker: http://plnkr.co/edit/81nWDyreYMzkunihfRgX?p=preview

Please mind the plunker only hack in app.js, since I couldn't find a way to make the right import work.

**Comment by mhevery** [comment]
Yes, Rules service is safe in webWorker

**Comment by esugoi** [comment]
Thanks again, @ThiagoT1 
I tried using the commented import statement in the plunker, but it gave me the same error message as before. I copied the Rectangle and Ruler for the time being until I can import directly from angular2.

Ok, @mhevery !
Thank you again for the answer. I think the Ruler service is enough for me now.

I changed all my code to use the Ruler, instead of directly acessing the style property from the nativeElement.

I am closing the issue as answered. :)

Thank you, everybody.

**Comment by qdouble** [comment]
@mhevery I was able to get Ruler to work in Universal only, not Web Workers

```
domAdapter = new browser.BrowserDomAdapter();
ruler = new ruler.Ruler(this.domAdapter);
```
The above will give a 'window' is undefined error when trying to use Universal

However this will work in universal
```
import {DOM} from 'angular2/src/platform/dom/dom_adapter';
ruler = new Ruler(DOM);
```
Is there a proper way to load the DomAdapter while in using a web worker?

**Comment by esugoi** [comment]
Yes, thats what I did too, @qdouble :)
I suppose the above doesn't work on web worker or universal because the BrowserDomAdapter is the implementation on the browser side.
I was expecting using the Ruler through DI would inject the webworker\universal DomAdapter implementation instead. But since I can't use it with DI... I don't know if this is the problem.

Thanks for contributing! :D

**Comment by zoechi** [comment]
@esugoi I assumed DOM is the adapter that is initialized appropriately on each platform (#6904)

**Comment by qdouble** [comment]
@zoechi yeah DOM doesn't seem to be properly implemented in Typescript right now, is it supposed to be part of the public API?

**Comment by zoechi** [comment]
@qdouble That would be great to know, indeed.
