### ISSUE TITLE
IE 11 & Chrome errors - Quick Start (5 min) tutorial

### ISSUE THREAD

**Issue by oswaldomilet** [angular/angular#6516]
I'm trying to create my first Angular 2 app in Visual Studio (ASP.NET 5) and I followed Quick Start (5 min) tutorial.

First thing I noted is that was necessary change System.js format configuration from "register" to "cjs" (maybe cause I switched Typescript module system from "system" to "commonjs"?). But after that, apparently everything was ok until IE arrive to my test.

In IE 11 I'm getting the following message:
"SCRIPT5009: 'System' is undefined
Rx.js (206,1)"

After that I read in tutorial that es6-shim should be in index.html for Angular 2 works in IE 11. But after include es6-shim.js, besides IE keep not working, I have this message in Chrome:
"Uncaught (in promise) TypeError: object is not a constructor(…)".

**Comment by mhevery** [comment]
Dup of #6556

**Comment by mlaval** [comment]
Dup of #6501, see my comment there: https://github.com/angular/angular/issues/6501#issuecomment-179502363
