### ISSUE TITLE
Promote "cannot find Directive/Pipe" warning to error

### ISSUE THREAD

**Issue by kegluneq** [angular/angular#6519]

**Comment by kegluneq** [comment]
Any objections to this? The result would be broken builds if/when `@Injectable` or an `import` is omitted for a type which appears in the `directives` parameter of a `View` or `Component`.

**Comment by kegluneq** [comment]
@yjbanov @jbdeboer @tbosch @vsavkin

**Comment by jbdeboer** [comment]
I love errors and fully endorse your promotion.

**Comment by tbosch** [comment]
+1
