### ISSUE TITLE
angular2 optimized loading sample

### ISSUE THREAD

**Issue by rmannibucau** [angular/angular#6526]
Hi,

I think it would be nice to add to angular2 doc some page about optimization,

I tried to avoid to load dev js in an app and it is not that obvious to configure rx+angular2 without any guidance.

typically using systemjs angular2.js works but min version throws a "no provider t!"

Here is a config on a sample: https://github.com/tomitribe/weekler/blob/master/src/main/webapp/index.jsp#L44

**Comment by michalstepien** [comment]
I think we can close this.

**Comment by rmannibucau** [comment]
right
