### ISSUE TITLE
Unicode characters in @component style

### ISSUE THREAD

**Issue by CaptainCodeman** [angular/angular#6530]
Trying to use unicode characters in css content defined in an `@component` `styles` array needs the backslash character to be double-escaped, i.e. it needs to be '\\' rather than just '\'. The single slash appears to be stripped out of the style added to the page so `content: "\25BE";` displays the characters 25BE rather than a down arrow. It needs to be `content: "\\25BE";` instead to work. The style is in a multi-line string (with back-ticks)

Not a big deal bit if you are moving styles around it can catch you out.

version: beta.1

**Comment by mgechev** [comment]
It seems like something related to `tsc`. Here's a similar issue https://github.com/mgechev/angular2-seed/issues/390.

**Comment by CaptainCodeman** [comment]
Yes, looks like it's tsc - thanks for the link.

Ah, so many moving parts ...

**Comment by mgechev** [comment]
@CaptainCodeman, I guess you can close this issue?

**Comment by mgechev** [comment]
@CaptainCodeman here's link to the issue in the TypeScript repository https://github.com/Microsoft/TypeScript/issues/6521#issuecomment-172381883
