### ISSUE TITLE
http: do not require body arg in PUT and POST methods

### ISSUE THREAD

**Issue by wardbell** [angular/angular#6533]
The `http.put` and `http.post` methods require a body parameter.

This is not strictly necessary. A client can send a command to the server that needs no body; it simply tells the server to do something. POST is often used to send the command.

This isn't a big deal. It's easy enough to pass a null. But this shouldn't be necessary. The body parameter should be optional.

**Comment by thelgevold** [comment]
Looks like @robwormald has a PR to allow us to pass an object as body instead of a json string. Perhaps your idea of making it optional could be an enhancement on this?
https://github.com/robwormald/angular/commit/6865e25cb3eabd1a84a2fbeda8702b37201c51d8

**Comment by robwormald** [comment]
This issue was moved to angular/http#51
