### ISSUE TITLE
Question: contribute to outdated plunker example 

### ISSUE THREAD

**Issue by laco0416** [angular/angular#6534]
I found some outdated plunker example in angular.io. 
If the team needs it, I'd like to update those to beta version.
but plunker's code doesn't exist in GitHub. so I cannot send a PR. 
can I do something about it?

**Comment by PascalPrecht** [comment]
I think this can only be updated by the author of that plunk. =/

I think an automated plunk generation is in the making. @wardbell don't we have sth. like that for our docs?

**Comment by adaojunior** [comment]
All the examples are here :
https://github.com/angular/angular.io/tree/master/public/docs/_examples
You can send your PR there and plunker will be  generated from it.

**Comment by laco0416** [comment]
@adaojunior I asked about `live demo` in 'API Preview' . but those looks like developer-guide's examples. 

live demo's url is hardcoded in source. (e.g. https://github.com/angular/angular/blob/2.0.0-beta.1/modules/angular2/src/core/linker/interfaces.ts#L338)
I want some way to contribute to this.

**Comment by wardbell** [comment]
API plunkers are not maintained the way that DevGuide plunkers are. It's on the roadmap to get them on the same footing.

**Comment by laco0416** [comment]
@wardbell thanks! I look forward to it. :smile:

**Comment by mhevery** [comment]
Closing as it is not actionable for the angular core team.
