### ISSUE TITLE
Doc: Remove "5 Min" from Quickstart Page

### ISSUE THREAD

**Issue by fa137** [angular/angular#6536]
I just feel like 5 min is just too small of time to introduce someone to Angular. I know it's kind of sugar-coated words to attract new developers, but we should be honest to everyone. I am just wondering what everyone else feels about it. Was 5 min enough for you to get into Angular?

**Comment by PascalPrecht** [comment]
I agree. Saw someone tweeting today that it took him about an hour to do the 5 min quick start.

How about removing the "5 min" and just go with "Quickstart"?

**Comment by manekinekko** [comment]
@fa137 I understand you concern.
Could you tell us what was the issues you encountered? Was the doc too long to process, was it related to understanding angular 2 concepts, or build tooling...? thx

**Comment by kasrakhosravi** [comment]
Although the implementation process wan't lengthy and we could start an ng2 app with provided code snippets in the matter of few minutes, taking time to pause and understand each part can take an hour or two. IMO "5 Min" is redundant.

**Comment by Longfld** [comment]
Not enough documentation, read code to find out won't be quickstart.
Want: just like angularjs 1, 5 min/tutorial for every major release version.

I have difficult to make example code from internet to work with latest ng2 version like beta

**Comment by fa137** [comment]
@manekinekko It's really hard to introduce someone to Angular. It looks extremely foreign to them. With typescript and using npm as library manager can be a little too much for new developers. I am suggesting to make it simpler. Perhaps just give the people a static environment instead of live compilation of typescript. Just like the Plunker example, using systemjs's typescript transpiler we can easily make it a 5 min quickstart guide. Also a github repo to pull the quickstart would be amazing.

If that's not possible, then I suggest removing "5 min" from the Quickstart. @PascalPrecht , @kasrakhosravi  and @Longfld have solid points why the term is redundant.
