### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by MrRhino** [angular/angular#6537]
See issue: https://github.com/npm/npm/issues/11174

**Comment by robwormald** [comment]
is this an issue? what? explain? angular2 currently uses `rxjs@5.0.0-beta.0`, so it appears you're using a outdated version of something. closing as non-actionable, do comment if you'd like to clarify anything further.

**Comment by MrRhino** [comment]
I see this should have been addressed to angular/angular2
Except that doen't exist yet.
