### ISSUE TITLE
How to use $interval in Angular 2?

### ISSUE THREAD

**Issue by Smilefounder** [angular/angular#6539]
I can not found $interval to auto fetch data from API.
Is there any replace solution?

Thanks.

**Comment by robwormald** [comment]
You can use the regular setInterval in Angular2 without any issues.

Alternately, for polling an API:

```
Observable.interval(1000)
  .mergeMap(() => http.get(url).map(res => res.json())
  .subscribe(data => {
    //do something with data
  })
```

**Comment by dudih** [comment]
Tnx very much!
