### ISSUE TITLE
Dynamically routes loaded in children not working

### ISSUE THREAD

**Issue by Alberplz** [angular/angular#6541]
Creating child routes only works with @RouteConfig decorator but not working when they are loaded dynamically.
 
http://plnkr.co/edit/XgLnhzt5rMH41xn4iNFA

**Comment by waeljammal** [comment]
+1 I have this issue as well when using AsyncRoute that loads a component that contains routes.

**Comment by zoechi** [comment]
seems related to 
- #6358
- #6562

**Comment by vicb** [comment]
obsolete - former router
