### ISSUE TITLE
Keyboard events not firing on firefox

### ISSUE THREAD

**Issue by DominikDitoIvosevic** [angular/angular#6545]
So I have been coding on Chrome and everything is fine but I have tried using the app in firefox 43 and both keydown and keypress don't fire at all.
If it didn't work on chrome I'd suppose it was a bug of mine but a same app does work on chrome and doesn't on firefox.

Angular beta1
Tsc 1.7.5
Firefox 4.3
Chrome 47

Code:

jade:

    ul.content-primary.content-list
      li.content-list-item.content-list-search-item.editable-ui( '*ngIf'="editable" )
        form
          .content-list-item-content
            label(for='add_item_search') Dodaj administratora
            input.add-item-search(type='text', name='add_item_search' '(keypress)'="onKeyPressed($event)" '[(ngModel)]'="userSearch" )

ts:

        import { View, Component } from 'angular2/core';
        import { Location, RouteConfig, RouterLink, Router, CanActivate } from 'angular2/router';
        import { Http } from 'angular2/http';
        import { NgSwitchWhen, NgSwitch, NgSwitchDefault, NgIf, NgFor, FORM_DIRECTIVES} from 'angular2/common';

        import { Form } from '../../services/utilities';

        @Component({
            selector: 'ManageAdmins',
            templateUrl: './dest/views/manageAdmins/manageAdmins.html',
            directives: [NgSwitchWhen, NgSwitch, NgSwitchDefault, NgIf, NgFor, FORM_DIRECTIVES]
        })
        export class ManageAdmins {
            http: Http;
            admins: Admin[] = new Array();
            normalUsers: any[] = new Array();
            closestMatches: any[] = new Array();
            editable: boolean = false;
            userSearch: string = "";

            matching: boolean = false;
            matchingId: number = -1;
            matchingIndex: number = -1;

            toggleEditable() {
                this.editable = !this.editable;
            }

            checkIfMatching(searchString) {
                for (let i in this.normalUsers) {
                    let fullName = this.normalUsers[i].first_name + ' ' + this.normalUsers[i].last_name;
                    if (fullName.toLowerCase() === searchString.toLowerCase()) {
                        this.matching = true;
                        this.matchingId = this.normalUsers[i].id;
                        this.matchingIndex = i;
                        return;
                    }
                }
                this.matching = false;
                return;
            }

            onKeyPressed(event) {
                let count = 0;
                let enteredLetter = String.fromCharCode(event.keyCode);
                this.closestMatches = new Array();
                for (let i in this.normalUsers) {
                    if (count === 3) return;
                    let fullName = this.normalUsers[i].first_name + ' ' + this.normalUsers[i].last_name;
                    if (fullName.indexOf(this.userSearch + enteredLetter) === 0) {
                        count += 1;
                        this.closestMatches.push(this.normalUsers[i]);
                    }
                }
                this.checkIfMatching(this.userSearch + enteredLetter);
            }

            constructor(http: Http) {
                this.http = http;
                http.get('/owner/admins/list').map((res) => res.json().data).subscribe((res) => {
                    for (let i in res) {
                        let admin = new Admin(res[i]);
                        this.admins.push(admin);
                    }
                }, (err) => console.log(err));
                http.get('/admin/users/list').map((res) => res.json().data).subscribe((data) => {
                    this.normalUsers = data;
                    console.log(data);
                }, (err) => console.log(err));
            }
        }

**Comment by ericmdantas** [comment]
Seems to be working fine for me:

http://plnkr.co/edit/cKMLoF349wUqTz8XKt6m?p=preview

Tested on Firefox Nightly 45.0a1 and 46.0a1.

**Comment by DominikDitoIvosevic** [comment]
My apologies. It seems that I forgot to add to directives NgModel though it still worked on chrome

**Comment by ericmdantas** [comment]
Cool! :smile: 

Could you please close the issue?
