### ISSUE TITLE
Swipe events

### ISSUE THREAD

**Issue by Jonatthu** [angular/angular#6549]
In angular 2 already exists something to detect touch, like swipe left or right events on a element?

Example:

```
<div (swipeLeft)="OnSwipeLeft()"></div>
```

**Comment by zoechi** [comment]
Seem Angular uses hammer.js https://github.com/angular/angular/blob/master/modules/angular2/src/platform/dom/events/hammer_common.ts

**Comment by zoechi** [comment]
Btw, GitHub issues are for bug reports and feature requests. For questions please use StackOverflow, Google Groups, Gitter, ...

**Comment by Jonatthu** [comment]
Thanks a lot and it won't happen again

**Comment by vanthome** [comment]
This does not seem to be the case any more, can someone enlighten what Angular is using?

**Comment by vicb** [comment]
It is, you have to load HammerJS before angular there is one ex in modules/playground IIRC

**Comment by vanthome** [comment]
ok, many thanks for the hint!
