### ISSUE TITLE
How to get the parent component reference from children

### ISSUE THREAD

**Issue by templth** [angular/angular#6550]
Is it possible (and how) to get the parent component reference from children?

Thanks very much for your help!
Thierry

**Comment by ThiagoT1** [comment]
You could pass a reference to it using a child input property, like so:

<child-cmp [parentModel]="model"></child-cmp>

[]'s,

Thiago

**Comment by CaptainCodeman** [comment]
This might be useful:
http://blog.thoughtram.io/angular/2015/04/09/developing-a-tabs-component-in-angular-2.html

Maybe this too:
https://angular.io/docs/ts/latest/api/core/HostMetadata-class.html

**Comment by templth** [comment]
@ThiagoT1 Interesting approach!

**Comment by templth** [comment]
@CaptainCodeman Definitevely useful ;-) In fact, my problem came from a cyclic dependency when importing the parent in the child and the child in the parent. Putting both parent and child in the same module fixed my issue...

 Thanks very much your help!
