### ISSUE TITLE
Http class injection

### ISSUE THREAD

**Issue by ruwhan** [angular/angular#6554]
Hello, I got an issue when trying to inject Http class into my own service, here is the code

```typescript
import {Component, Injectable, OnInit} from "angular2/core";
import {HTTP_PROVIDERS, Http} from "angular2/http";

import {User} from "../models/user";

@Injectable()
export class UsersService implements OnInit {
  constructor(private _http:Http) {

  }
  
  ngOnInit() {}
}

```

This code caused 
```
Uncaught SyntaxError: Unexpected token < angular2-polyfills.js:138 
	Evaluating http://localhost:3000/angular2/http
	Error loading http://localhost:3000/scripts/boot.js
```

But if remove the `http` arguments from the parameter `constructor() {}`, the error will be gone. 

Am I doing it wrong? I'm using Angular v2.0.0-beta.0 btw.

Thanks.

**Comment by robwormald** [comment]
you need to include the http bundle most likely

**Comment by ruwhan** [comment]
@robwormald thanks, your are right, I need to include the http bundle just like router. this is so silly, lol.
