### ISSUE TITLE
2.0.0-beta.1 failed in IE 11 11.0.9600.18124

### ISSUE THREAD

**Issue by fjaweihyafei** [angular/angular#6556]
Our project was based on 2.0.0-bata.0, it works well in IE11 before I updated to Angular 2.0.0-beta.1, I got the error 
 at run (http://localhost:8089/lib/angular2-polyfills.js:138:7)

It works in Chrome and Firefox. It seems something wrong in the angular2-polyfills.js for IE when changed to Angular 2.0.0-beta.1.
Anyone can help me?

Thanks
Fei

**Comment by zoechi** [comment]
Any information that allows to reproduce? Any error message?

**Comment by dlebedynskyi** [comment]
I can confirm this issue. Here is [plunker](https://plnkr.co/edit/0M3RoFW2P6FXpCNC8P2y?p=preview) for beta 1. instead of beta1 try put beta0 - all works. IE only issue.
Tested on 11.0.9600.17959 on windows 7.

**Comment by mlaval** [comment]
Dup of #6501, see my comment there: https://github.com/angular/angular/issues/6501#issuecomment-179502363
