### ISSUE TITLE
2.0.0-beta1: How to access some exports in the compiled code?  

### ISSUE THREAD

**Issue by dotansimha** [angular/angular#6558]
Hi,
I am work on Angular2-Meteor project, and we are now implementing the actual package with Meteor 1.3, which uses NPM.
In our original code, we used the sources of Angular2 so we could access some exports of Angular2, which are not available at all in the compiled code.
I am installing Angular 2 from NPM (2.0.0-beta1) and I need to access `DefaultIterableDifferFactory` and `CollectionChangeRecord` in order to extend Angular2 to support MongoDB cursors (which comes from Meteor). 

When using the code from this repository (the actual source), we used to do:
```js
import {DefaultIterableDifferFactory, CollectionChangeRecord} from 'angular2/change_detection';
```

But now when I used the NPM version and get the compiled version - `angular2/change_detection`  does not exists at all, and in order to use it I need to do:
```js
import {DefaultIterableDifferFactory, CollectionChangeRecord} from 'angular2/src/core/change_detection/differs/default_iterable_differ';
```

Am I doing something wrong? Is there another way to get to those classes without accessing the sources? 

Thanks!

@Urigo

**Comment by pkozlowski-opensource** [comment]
I'm not sure what you mean exactly by "sources" and "compiled" code but:
* imports structure was re-organized lately and `angular2/change_detection` is not a top-level export any more - in other words - it doesn't and won't exist
* there is nothing, technically speaking, that would prevent you from importing any class from any part of the source tree but if you don't import from top-level exports (core, common etc.) you are building on top of non-public APIs and those my change at any point (you can see a list of public exports here: https://github.com/angular/angular/blob/master/modules/angular2/test/public_api_spec.ts
* are you _sure_ that you need to access `DefaultIterableDifferFactory` and `CollectionChangeRecord`? What is your exact need? You might want to check [ngClass code](https://github.com/angular/angular/blob/master/modules/angular2/src/common/directives/ng_class.ts) to see how it deals with instantiating / using various differs

**Comment by dotansimha** [comment]
Thanks @pkozlowski-opensource for you answer!

I am reviewing the need to access those right now. 

I will re-open this issue if I'll have another questions.

**Comment by dotansimha** [comment]
@pkozlowski-opensource 
So after some checks, I still have unresolved issue... 
We want to implement our custom Differ for custom type, it already implemented here: https://github.com/Urigo/angular2-meteor/blob/master/modules/mongo_cursor_differ.ts 
But this solution uses private classes that it should not use. 

Do you have another idea for solving it without accessing the private classes? 

Thanks.

**Comment by mhevery** [comment]
I believe your could should `implement IterableDifferFactory` rather than 'extend DefaultIterableDifferFactory`. Have you tried that solution? Did you run into issues? If so what were they?

Will close, please reopen if it does not solve your problem.

**Comment by dotansimha** [comment]
Oh great @mhevery ! thanks a lot ! 
One last thing: I also need to use `CollectionChangeRecord` which comes from `angular2/src/core/change_detection/differs/default_iterable_differ` , it there any other way to get it, or I'm doing something wrong here?

Thanks!

**Comment by mhevery** [comment]
I think that one should be part of the public API. can you file a separate
issue for that.

**Comment by dotansimha** [comment]
Thanks @mhevery . Also noticed that we need to use `ObservableWrapper.subscribe` from `angular2/src/facade/async`. Does it have a public alternative (did find one)? Or maybe we are doing something wrong? 

Thanks.

**Comment by mhevery** [comment]
its internall API see: https://github.com/angular/angular/issues/3074
