### ISSUE TITLE
Child components which only exists in the context of their parent

### ISSUE THREAD

**Issue by bennylut** [angular/angular#6560]
Some components only make sense on the context of their parents - 
for example, a `tab` component only make sense inside a `tabs` container component. 
In addition some components may be defined differently depending on their context, e.g., a `header` component may be differently defined for usage inside a `data-table` component and for a `panel` component.  Of course one may create two different components - i.e., panel-header and table-header but this makes the component api very  verbose and adds unneeded complexity to it.

- I know that angular does not support component selectors which involves looking at more than one element (i.e., `@Component({selector="tabs tab"...})` is not allowed)  - so we cannot use the selector to achieve this behavior

- I tried to define directive-dependency over the correct component - directly inside the parent component (wishing that angular will use it when parsing the parent content) but without success, i.e.:

```typescript
@Component({selector: 'tab'...}) class Tab {...}
@Component({selector: 'tabs', directives: [Tab]...}) export class Tabs{
    @ContentChildren(Tab) tabs:QueryList<Tab>; // <-- this is always empty!
}
@Component({
     selector: 'app',
     template: `<tabs> <tab>A Tab</tab></tabs>`,
     directives:[Tabs]
...})
class App{...}
```

I was wondering if there is a way to achieve the required behavior in the current beta version and if not, is there is a plan to have this feature before the first release?.

**Comment by zoechi** [comment]
`tabs` also won't contain elements before `ngAfterContentInit()`
Just to be sure - you use `<ng-content>` in `Tabs`?

**Comment by bennylut** [comment]
@zoechi - Yes I tried but without luck. 
Note though - that if it would work using the `<ng-content>` it will force the programmer to display all the tabs in advance.

**Comment by zoechi** [comment]
So does that mean you don't use `<ng-content>`? In this case you'd need to use `@ViewChildren` instead of `@ContentChildren`.

**Comment by bennylut** [comment]
@zoechi - It does not work either - using the `@ViewChildren` annotation only works if the elements you are trying to "catch" are defined inside the template of the component whom the annotated field belongs to. In our case the children of the `tabs` component (i.e., the `tab` component)  are defined as content coming from the parent component (i.e., the `app` component)

**Comment by zoechi** [comment]
But then you'd need to use `<ng-content>` wouldn't you. Can you please provide a Plunker?

**Comment by bennylut** [comment]
Sure, 
Here it is:
https://plnkr.co/edit/OpBbLnXS4t63bVPjvLgZ?p=preview

**Comment by pkozlowski-opensource** [comment]
@bennylut currently you have to list all directives you are using in your template: https://plnkr.co/edit/2nU6cTfXl1uxqpEBMLCo?p=preview

Having said this I'm not _exactly_ sure what is your complain / suggestion as IMO the current model is consistent to reason about and I don't see how you would like to change this...

**Comment by bennylut** [comment]
@pkozlowski-opensource,
assume that you have two components - the one is a data-table component which you can use in the following way: 
```
<data-table>
  <headers>
    <header> H1 </header>
    ...
  <headers>
  ...
</data-table>
```
and the other is a panel which you can use as follows: 

```
<panel>
    <header> PH1 </header>
    ...
</panel>
```
both these components defines a "sub-component" called `header`. The `header` component should be defined differently for the `data-table` and for the `panel` - if we cannot define something like `data-table > headers > header` component and a `panel > header` component we will have to use prefixes like: `data-table-header` and `panel-header`.
To make things worse - if these components belongs to a third party library they will have another prefix - i.e., xx-data-table-header and xx-panel-header. This is not only uneccesserily verbose but also misleading because xx-data-table-header is only make sense in the context of the xx-data-table but since it is defined "globally" one can use it anywhere it wants (and performance wise - angular must consider it when compiling the template no matter the context)

**Comment by pkozlowski-opensource** [comment]
@bennylut let's settle few things first:

> To make things worse - if these components belongs to a third party library they will have another prefix - i.e., xx-data-table-header and xx-panel-header. This is not only uneccesserily verbose but also misleading because xx-data-table-header is only make sense in the context of the xx-data-table but since it is defined "globally" one can use it anywhere he wants (and performance wise - angular must consider it when compiling the template no matter the context)

In Angular2 each component / directive is "local" to a component in which it was "declared". Unless you are saying that one could have a situation where I would like to use _both_ `<data-table>` and `<panel>` with a `header` child in one template?

>  component we will have to use prefixes like: data-table-header and panel-header.

Yes, but this is a "good thing" that is enforced in web components, for example (I mean, presence of a prefix is mandatory and enforced).

It seems to me like you would like to have `<header>` that behaves differently depending on a parent component where it is used, but I'm not sure what should be a difference nor how this difference could be expressed. Could you share a more concrete idea? How the header from your example should different depending on the context? How would you like to describe those differences?

**Comment by bennylut** [comment]
> In Angular2 each component / directive is "local" to a component in which it was "declared". Unless you are saying that one could have a situation where I would like to use both <data-table> and <panel> with a header child in one template?

Sure :)
```
<panel> 
    <header> My Data-Table </header>
    <content>
        <data-table>
           <headers> <header> First Header </header> </headers>
           ...
        </data-table>
    </content>
</panel>
```
> It seems to me like you would like to have <header> that behaves differently depending on a parent component where it is used, but I'm not sure what should be a difference nor how this difference could be expressed. Could you share a more concrete idea? How the header from your example should different depending on the context? How would you like to describe those differences?

I would have expressed it in the following way: 
```typescript
@Component({
    selector: 'data-table > headers > header',
    ...
})
class DataTableHeader {...}

@Component({
    selector: 'panel > header',
    ...
})
class PanelHeader {...}
```

**Comment by pkozlowski-opensource** [comment]
> I would have expressed it in the following way

Right. I was more after answers to the following:
* how would panel / table / header behave differently depending on the context?
* how would you code those differences? I mean, how / where you would write different code depending on the context?

**Comment by bennylut** [comment]
> how would panel / table / header behave differently depending on the context?

for example - a panel header will be composed from an `<h2>` with some styling and a button on the right that allows to minimize the panel 
while a header for a data-table may just be an `<th>` with some specific code that allows you to sort the table when clicking on it

> how would you code those differences? I mean, how / where you would write different code depending on the context?

Just like the example I gave in the previous post - I would create two different components each behaves as needed - and, when compiling a template - angular will choose the correct component to use using the selector and the context of the compiled element.

**Comment by pkozlowski-opensource** [comment]
> Just like the example I gave in the previous post - I would create two different components each behaves as needed - and, when compiling a template - angular will choose the correct component to use using the selector and the context of the compiled element.

I see. So what you are saying that you want to have the _same_ symbol / name to do _different_ things depending on their parent? If so I'm not sure I'm "buying" this one as IMO it would make templates harder to read / reason about.

**Comment by bennylut** [comment]
>I see. So what you are saying that you want to have the same symbol / name to do different things depending on their parent?
exactly

>If so I'm not sure I'm "buying" this one as IMO it would make templates harder to read / reason about.
IMO this: 
```html
<panel> 
    <header> My Data-Table </header>
    <content>
        <data-table>
           <headers> 
              <header>
                <icon src="myicon.png"></icon>
                First Header 
             </header> 
           </headers>
           ...
        </data-table>
    </content>
</panel>
```
can be much easier  to reason about than this:
```html
<panel> 
    <panel-header> My Data-Table </panel-header>
    <panel-content>
        <data-table>
           <data-table-headers> 
                 <data-table-header>
                     <data-table-header-icon src="myicon.png"></data-table-header-icon>
                      First Header 
                </data-table-header>
           </data-table-headers>
           ...
        </data-table>
    </panel-content>
</panel>
```
but we are each entitled to our own opinion :)

**Comment by mhevery** [comment]
@bennylut you can drop the `data-` prefix as it adds nothing to the discussion.

Currently in HTML each element behaves same regardless of where it is declared. We are simply following this precedence. Unless there is a really good technical reason to do otherwise, we will follow the HTML spec behavior.

So I am sorry to say, this is something which we do not plan to support, as we don't believe it is desirable. 

I understand that you have a different opinion, but we need to make sure that core framework principles are consistent, I am sorry we will not be able to accomodate you.

**Comment by bennylut** [comment]
No problem, thanks anyway :)
