### ISSUE TITLE
Dart: Router: integer type RouterParams exception

### ISSUE THREAD

**Issue by mark1010** [angular/angular#6564]
Inside a template it is possible to construct a router link parameter with an ‘int’ RuntimeType. When the link is followed, the target component retrieves the parameter and an exception is raised due to the ‘Int' type, being accessed via StringMapWrapper.

where e.id is an int:
```
<td><a id="entry-{{ e.id }}"
     [routerLink]="['/TsEditPage', {'id': e.id }]">{{ e.id }}</a></td>
```

in the target component, from RouterParams:
```
var id = rp.get("id");
```

causes exception in StringMapWrapper

```
>EXCEPTION: type 'int' is not a subtype of type 'String' of 'function result'.
  EXCEPTION: type 'int' is not a subtype of type 'String' of 'function result'.
    (anonymous function)	
  STACKTRACE:
    (anonymous function)	
  package:angular2/src/router/instruction.dart 42:29  RouteParams.get
```

In a subsequent page refresh, in which the parameter is retrieved from the browser location as a String, everything works ok of course.

It would be good to have an exception raised at the time the RouterLink is created, with the int type.

Dart VM version: 1.13.2 (Tue Jan  5 06:36:44 2016) on "macos_x64"
angular2: "2.0.0-beta.1"

**Comment by CaptainCodeman** [comment]
I've been wrapping things like this in `parseInt` as the router keeps the type during in-page navigation but when a page is refreshed the param will be a string.

I personally think it would be better if the router always gave the params to you as a string or else included some type information in the routes (like ui-router) so you could specify that the route expects an int to match (and the param can then be typed consistently when provided).

**Comment by vsavkin** [comment]
We are no longer maintaining the deprecated router to focus our efforts on making the new router robust.

It does not look like the issue makes sense in the new router. If you think it does, please reopen it in the context of the new router.

Closing this issue.
