### ISSUE TITLE
Cannot implement custom Exceptionhandler

### ISSUE THREAD

**Issue by CaptainCodeman** [angular/angular#6565]
Trying to implement a custom Exceptionhandler fails. The docs suggest:

```
import { ExceptionHandler } from 'angular2/core';

class MyExceptionHandler implements ExceptionHandler {
  call(error, stackTrace = null, reason = null) {
    // do something with the exception
  }
}
```
https://angular.io/docs/ts/latest/api/core/ExceptionHandler-class.html

But this fails with:

error TS2420: Class 'MyExceptionHandler' incorrectly implements interface 'ExceptionHandler'.
Property '_logger' is missing in type 'MyExceptionHandler'.

Trying to add a _logger causes:
error TS2420: Class 'MyExceptionHandler' incorrectly implements interface 'ExceptionHandler'.
Types have separate declarations of a private property '_logger'.

Trying to extend ExceptionHandler instead gives various other errors about _logger being duplicated.

**Comment by CaptainCodeman** [comment]
Ah, removed the `implements ExceptionHandler` and it worked fine.

**Comment by rbaz** [comment]
How can creat a component to handle all exception client side and add it to our project. Thks

**Comment by CaptainCodeman** [comment]
I'm using something like this:

exception-handler.ts
```
import { Injectable, ExceptionHandler } from 'angular2/core';

@Injectable()
export class CustomExceptionHandler {
  call(exception: any, stackTrace?: any, reason?: string): void {
    // custom handler code here, e.g. log to Google Analytics
  }
}
```

Then in boot.ts:
```
import { provide, Injector, ExceptionHandler } from 'angular2/core';
import { CustomExceptionHandler } from './exception-handler';

bootstrap(App, [
  ...
  provide(ExceptionHandler, { useClass: CustomExceptionHandler }),
  ...
]);
```

**Comment by tbragaf** [comment]
@CaptainCodeman 
In your solution, do you still run the normal flow code?
I would like to have my own Exception Handler, but I want it to add behaviour to the previous one.

**Comment by zoechi** [comment]
I also think this should be reopened. This is how it's explained in the docs but throws.
I also think it should be considered to allow the default implementation to be extended instead of just implemented.

**Comment by zoechi** [comment]
@tbragaf created a new one #6865
