### ISSUE TITLE
Why RouteData has to be immutable? 

### ISSUE THREAD

**Issue by shubhamMuttepawar** [angular/angular#6569]
Is there any way by which we can set routeData dynamically? If not, why it has to be immutable? It would be good if routeData was dynamically configurable.

**Comment by brandonroberts** [comment]
@shubhamMuttepawar RouteData is meant to be read-only, which is why its immutable. What's your use case that you couldn't use RouteParams instead?

**Comment by mhevery** [comment]
Closing as we don't want it to be mutable. Re-open if you have a good use case.

**Comment by shubhamMuttepawar** [comment]
@brandonroberts @mhevery  My use-case is very  simple. Lets say there is a parent component having two routes **`path1`** and **`path2`** and I want to navigate from **`path1`** to **`path2`** using `Router.navigate()` and while navigating I want to pass some **complex object**. I can use `RouteParams` for simple types but for complex ones I don't see how `RouteParams` can help and also whatever we pass in `RouteParams` is **visible in URL**. I don't want the data to be visible in the URL. Is there any other way to achieve this? 
I would also like to know if there is any specific thought process behind keeping `RouteData` immutable.

**Comment by zoechi** [comment]
What about using a shared service to pass data?

**Comment by shubhamMuttepawar** [comment]
That is what I am doing right now. I have a shared service having getter and setter for the data which I  want to pass, but then, as the application grows I will have to write lots of services just to pass the data among routes. If there had been any generic thing available at framework level then this will become very easy.

**Comment by gtzinos** [comment]
@shubhamMuttepawar I have the same problem. A simple solution is to have only one variable (string, json) with a setter, getter method to get,update it.. Everytime you need to set it you will have to initialize it again with setter. Last you can get it with a getter from the service.
