### ISSUE TITLE
es6-shim.d.ts conflicts with lib.es6.d.ts

### ISSUE THREAD

**Issue by kjozic** [angular/angular#6572]
es6-shim.d.ts conflicts with lib.es6.d.ts when typescript target is ES6.
![screenshot](https://cloud.githubusercontent.com/assets/16577444/12433189/eb6044c4-beff-11e5-9a32-f586fe0155df.jpeg)

**Comment by zoechi** [comment]
Is this related to #5807

**Comment by kjozic** [comment]
No, in this case problem is a conflict between lib.es6.d.ts (part of typescript package) and es6-shim.d.ts (part of angular2 library). When the code is compiled to ES5 everything is OK. Conflict only exists when compiling to ES6 because angular2 uses es6-shim which contains duplicate declaration from lib.es6 delivered with typescript.

**Comment by kjozic** [comment]
Problem is similar to #3508

**Comment by NikGovorov** [comment]
As temporary workaround I delete content of ```node_modules\angular2\typings\es6-shim\es6-shim.d.ts``` to be able target ES6.

**Comment by alexeagle** [comment]
fixed in beta.6, just released.
We no longer pollute the typechecker with our dependencies' types.

**Comment by NikGovorov** [comment]
Can confirm that beta.6 works for me.

**Comment by kjozic** [comment]
Beta.6 works for me also.

**Comment by arturocarrionglobant** [comment]
What Beta.6 are you talking about? TypeScript? es6? Could you be more explicit, please?

**Comment by pe8ter** [comment]
Angular 2 beta.6

**Comment by arturocarrionglobant** [comment]
ok thanks!

**Comment by arturocarrionglobant** [comment]
Anyone know why I cannot reach @angular/* 2.0.0-beta.6 to be restored from package.json in VS2015?

**Comment by alexeagle** [comment]
angular 2 betas were published to the `angular2` package on npm. The
`@angular` namespace has only been used since release candidate (RC1)

**Comment by arturocarrionglobant** [comment]
great thanks Alex!

**Comment by anorborg** [comment]
This seems to be occurring now with `core-js/index.d.ts` and targeting es6 with the latest typescript-2 `lib.es6.d.ts`
