### ISSUE TITLE
How to create a component without template but can bind attribute value to view

### ISSUE THREAD

**Issue by euclid1990** [angular/angular#6578]
I am starting with angular 2.0, and have two file:
**app.component.ts**
``` 
@Component({
    selector: 'my-app',
})

export class AppComponent {
    public title = 'Tour of Heroes';
}
```
**index.html**
``` 
<my-app>This is my page's {{ title }}</my-app>
```
But when I run it on Browser, It has error: `Error: Component 'AppComponent' must have either 'template', 'templateUrl', or '@View' set.`

It is not the same Controller in angular 1.x. We can sepearate view and controller to 2 files, and define by ng-controller="xxxx".

Because I want to integrate angular 2.x into my website (write by Laravel with Blade template). I want Component can process a DOM inside HTML by SELECTOR, but dont want to include any html template into Component.

Please help me !

**Comment by kittencup** [comment]
```javascript
@Component({
    selector: 'my-app',
    template:`<ng-content></ng-content> {{title}}`
})

export class AppComponent {
    public title = 'Tour of Heroes';
}
```

<my-app>This is my page's</my-app>

**Comment by woppa684** [comment]
Yes, and you can use templateUrl instead of template to separate the files...

**Comment by euclid1990** [comment]
@kittencup I try it, but it not output anythings

@woppa684: Yes, we can use templateUrl, but with the php web, I want to render template with php variable before pass it into `@Component`.
With angular 1.x, it could process html dom inside view, without create anything more !

**Comment by zoechi** [comment]
Seems related to #1858

**Comment by pkozlowski-opensource** [comment]
Yep, this is the same issue as #1858
