### ISSUE TITLE
routerLink: SyntaxError on empty parameters

### ISSUE THREAD

**Issue by npx** [angular/angular#6579]
_Using the `routerLink` directive as documented [here](https://angular.io/docs/ts/latest/api/router/RouterLink-directive.html)._

    <a [routerLink]="['Hub', {}, 'Child']">Hub/Child</a>

It results in a SyntaxError:

    dom_element_schema_registry.ts:43 EXCEPTION: SyntaxError: Unexpected token )

This only happens if the parameter 'object' is left empty.

    <a [routerLink]="['Hub', {something: 333}, 'Child']">Hub/Child</a>  -- Works
    <a [routerLink]="['Hub', 'Child']">Hub/Child</a> -- Works
    <a [routerLink]="['Hub', {}, 'Child']">Hub</a> -- Fails
    <a [routerLink]="['Hub', {}]">Hub</a>  -- Fails

**Comment by brandonroberts** [comment]
@npx this isn't a router bug. Its an invalid template expression. You can generate this error many ways

```html
   <div *ngIf="{}"></div>

   <div *ngIf="['Test', {}]"></div>
```

**Comment by mhevery** [comment]
Repro: http://plnkr.co/edit/w2FVfKlWP72pzXIsfsCU?p=preview
`<span>{{ {} }}</span>`

**Comment by vsavkin** [comment]
This has been fixed in master. Closing this issue.
