### ISSUE TITLE
Empty option in select shows at last position when using ng-options and ng-if on the empty option

### ISSUE THREAD

**Issue by latata** [angular/angular#658]
Check this: http://plnkr.co/edit/OtwP7LK34MuOeXDxiM3x?p=preview
When options are loaded from http request (in plunkr I use $timeout) the empty option apears at the last position when using ng-if on it. When I use ng-show everything works well.

**Comment by pkozlowski-opensource** [comment]
Wrong repo, see https://github.com/angular/angular#angular-
