### ISSUE TITLE
what's wrong with the http headers in angular 2 using typescript

### ISSUE THREAD

**Issue by yangpeng-chn** [angular/angular#6583]
I found several documents telling me to set the headers by the code below.
```
  	var tokenHeader = new Headers();
  	tokenHeader.append('token', 'somevalue');
  	var options = new RequestOptions({
	  method: RequestMethod.Get,
	  url: 'http://localhost:8080/v1/users',
	  headers: tokenHeader
	});
	var req = new Request(options);
  	this.http.request(req)
  	.subscribe((res: Response) => {
        <do something>
    });
```
when I look at the console when sending this request, the request headers look like:

```
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8,ja;q=0.6,zh-CN;q=0.4,zh;q=0.2
Access-Control-Request-Headers:token
Access-Control-Request-Method:GET
...
```
I can find "token" in Access-Control-Request-Headers,  but, where is my "somevalue"?,
by using "curl" command, the request headers look like the code below and it works well.
```
Host: localhost:8080
> User-Agent: curl/7.43.0
> Accept: */*
> Referer: rbose
> token: <somevalue>
> Cache-Control: no-cache
```
Also having this header problem, I receive the error message all the time even though I set the "w.Header().Set("Access-Control-Allow-Origin", "*")" in my server side.(no error occurs if I don't add headers in the request)
```
XMLHttpRequest cannot load http://localhost:8080/v1/users. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access. The response had HTTP status code 404.
```

**Comment by pkozlowski-opensource** [comment]
This sounds like a CORS in action and likely problem of your server configuration.

**Comment by perrin4869** [comment]
How come this is a server error when different clients produce a correct response? (curl seems to work while Angular XHR fails...)

**Comment by pkozlowski-opensource** [comment]
CORS doesn't come into play when using curl - it is only browser's mechanism. At this is a mechanism on a browser level, not a framework level. More info: http://www.html5rocks.com/en/tutorials/cors/

**Comment by yangpeng-chn** [comment]
@pkozlowski-opensource , Your link helped me a lot! Thanks! What I missed is to add a http OPTIONS method to handle the preflight request and set the response header properly.

**Comment by 3DRahul** [comment]
I have added :

			<customHeaders>
				<add name="Access-Control-Allow-Origin" value="*" />
				<add name="Access-Control-Allow-Methods" value="GET, OPTIONS" />
				<add name="Access-Control-Allow-Headers" value="session-variable" />
			</customHeaders>

However, still the header: **session-variable** is not passed with the preflight request. Please help.

**Comment by zoechi** [comment]
@3DRahul this is something your browser and your server have to deal with. Angular2 is not involved. 

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by hiedwincp** [comment]
Please use @CrossOrigin on the backend side in Java Spring boot controller (either class level or method level) as the solution for Chrome error'No 'Access-Control-Allow-Origin' header is present on the requested resource.'

This solution is working for me 100% ...

> Example : Class level

@CrossOrigin
@Controller
public class UploadController {

----- OR -------

> Example : Method level

@CrossOrigin(origins = "http://localhost:3000", maxAge = 3600)
@RequestMapping(value = "/loadAllCars")
    @ResponseBody
    public List<Car> loadAllCars() {


Ref: https://spring.io/blog/2015/06/08/cors-support-in-spring-framework

**Comment by rameezcm** [comment]
is adding @CrossOrigin works

**Comment by DzmitryShylovich** [comment]
you just need a proxy (webpack dev server has one) to redirect requests from 3000 to 8080 port.

**Comment by rameezcm** [comment]
I am trying this

 private heroesUrl = 'http://localhost:8080/springmvc-jpa-blank/person/getlist/';  // URL to web API
  constructor (private http: Http) {}
  
  addTodo(todo: Todo): TodoService {
    /**if (!todo.id) {
      todo.id = ++this.lastId;
    }
    this.todos.push(todo);
    return this;**/
	const headers = new Headers();
        headers.append('Access-Control-Allow-Headers', 'Content-Type');
        headers.append('Access-Control-Allow-Methods', 'GET');
        headers.append('Access-Control-Allow-Origin', '*');
	let people = this.http
      .get(this.heroesUrl);
	 
	  people.subscribe(
      data => {
        console.log(data[0]);
      }
    );
	
    return this;
  }

But getting No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access. The response had HTTP status code 404.

**Comment by DarthFarzad** [comment]
I had a similar issue before. What is happening is that the Method is set to OPTIONS. so you can either set the server to accept this method or create a new RequestOptionsArgs() and then use the http.request with the RequestOptions. I hope I makes sense lol

**Comment by vanrado** [comment]
@DzmitryShylovich Thanks, it helps me, I set up proxy config targeting to my Rest API, please could you explain why this now works? Response headers now contains Access-Control-Allow-Origin properties and it works properly, if I don't use proxy confing, response headers do not contains Access-Control-Allow-Origin properties, but calling api is successfull with "No 'Access-Control-Allow-Origin' header" response. Thanks

**Comment by phoenixTW** [comment]
getAppDescriptions(appName: String) {
        const url = this.routerService.getConfig(appName);
        return this.http.get(url)
            .map((response: Response) => {
                this.config = response.json() || {};
            });
    }

I am having this code on my service. I am also getting **XMLHttpRequest cannot load _http://URI_. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access**.

I am using nginx for the server proxy. 

events {
	worker_connections 1024;
}

http {
    include mime.types;

    server {
      listen 8000;

      location / {
       	 proxy_pass http://localhost:3001;
      }

     location /core {
	    proxy_pass http://localhost:3000/;
     }

     location /config {
	    proxy_pass http://localhost:3003/;
     }
   }
}

Whenever I am trying to make a call to **http://localhost:3003/**, I am getting the above error. Can anyone suggest me how to solve it?

**Comment by abhijitmhp** [comment]
You need to be specifying the URL in the options. What I noticed is that when I do an http.post, the url goes as null under options.

Hence making a change as below solved my problem:

`let headers = new Headers({ 'Content-Type': 'application/json' });
    headers.append('Access-Control-Allow-Headers', 'Content-Type');
    headers.append('Access-Control-Allow-Methods', 'POST');
    headers.append('Access-Control-Allow-Origin', '*');
      
  let options = new RequestOptions( {method: "post", headers: headers
         , url : "http://localhost:8080/XXXX/XXX"});
 
    var jsonData = JSON.stringify(data);

    return this.http.post("http://localhost:8080/XXXX/XXX",
     jsonData, options).map(res => res.json());`

**Comment by jpontdia** [comment]
@hiedwincp THANK YOU!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by rgantla** [comment]
In my experience the plugins worked with http but not with the latest httpClient. Also, configuring the CORS respsonse headers on the server wasn't really an option. So, I created a proxy.conf.json file to act as a proxy server.

Read more about this here: https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/proxy.md

below is my proxy.conf.json file

    {
      "/posts": {
        "target": "https://example.com",
        "secure": true,
        "pathRewrite": {
        "^/posts": ""
      },
        "changeOrigin": true
      }
    }

**I placed the proxy.conf.json file right next the the package.json file in the same directory**

**then I modified the start command in the package.json file like below**

    "start": "ng serve --proxy-config proxy.conf.json"

now, the http call from my app component is as follows

    return this._http.get('/posts/pictures?method=GetPictures')
    .subscribe((returnedStuff) => {
      console.log(returnedStuff);
    });

Lastly to run my app, I'd have to use **npm start** or **ng serve --proxy-config proxy.conf.json**

**Comment by JinnaBalu** [comment]
I want to use some API created using nodejs, How do i resolve this issue

**Comment by m00zi** [comment]
I had the same issue, 
client side --> angular 5
server side --> Nodejs v9.8.0

I have added cors to the server app 
npm install cors --save

then imported:
const cors = require('cors');

Then enabled the middleware :
app.use(cors());

Thats it, now it is working fine with no issue.

**Comment by m00zi** [comment]
I had the same issue, 
client side --> angular 5
server side --> Nodejs v9.8.0

I have added cors to the server app 
`npm install cors --save`

then imported:
`const cors = require('cors');`

Then enabled the middleware :
`app.use(cors());`

Thats it, now it is working fine with no issue.

**Comment by jdelgado18** [comment]
@m00zi thank you!! works like a charm!

**Comment by velkumars** [comment]
hi, 
I'm facing same issue 

I had the same issue,
client side --> angular 5
server side --> .NET Core

i couldn't send timezone from client. any suggestions? i have added below code in my server side, still no luck

```
context.Response.Headers.Add("Access-Control-Allow-Origin", "*");
context.Response.Headers.Add("Access-Control-Allow-Credentials", "true");
context.Response.Headers.Add("Access-Control-Allow-Headers", "authorization,timezone,Content-Type, X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Date, X-Api-Version, X-File-Name");
context.Response.Headers.Add("Access-Control-Allow-Methods", "POST,GET,PUT,PATCH,DELETE,OPTIONS");
```

**Comment by m00zi** [comment]
actually, you can do that without Cors module too, please check the below middleware for Nodejs,

`app.use((req, res, next) => {
    res.header('Access-Control-Allow-Origin', '*');
    res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept, Authorization');
    if (req.method === 'OPTIONS') {
        res.header('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, PATCH');
        return res.status(200).json({});
    }
    next();
});`

**Comment by IamGiel** [comment]
> I had the same issue,
> client side --> angular 5
> server side --> Nodejs v9.8.0
> 
> I have added cors to the server app
> `npm install cors --save`
> 
> then imported:
> `const cors = require('cors');`
> 
> Then enabled the middleware :
> `app.use(cors());`
> 
> Thats it, now it is working fine with no issue.

how is this done in angular 6? with java as back end?

**Comment by m00zi** [comment]
With your implementation as following should work fine:

```
const cors = require('cors');
app.use(cors());
```

**Comment by deadmann** [comment]
i have to part of code in two place when i was building my application... one work with no error, another delegate to CORS, why is that?

Direct Call:
Note: no fancy stuff used, just simple call:
```
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {
  registerMode = false;
  values: any;

  constructor(private http: HttpClient) { }

  ngOnInit() {
    this.getValues();
  }

  registerToggle() {
    this.registerMode = true;
  }

  getValues() {
    this.http.get('http://localhost:60421/api/Nest/anonymous')
    .subscribe(data => {
      this.values = data;
    });
  }

  cancelRegisterMode(registerMode: boolean) {
    this.registerMode = registerMode;
  }
}

```

From Service: (Cause Cross Origin Error)
Note: i used http header... first i though because on server i used authorize attribute it cause error, then i found out even calling to a method with [AllowAnonymous] cause same issue to
```
import { Component, OnInit } from '@angular/core';
import { BasePlace } from 'src/_models/entities/basePlace';
import { AlertifyService } from '../_services/alertify.service';
import { NestService } from '../_services/nest.service';

@Component({
  selector: 'app-property-list',
  templateUrl: './property-list.component.html',
  styleUrls: ['./property-list.component.css']
})
export class PropertyListComponent implements OnInit {
  basePlaces: BasePlace[];

  constructor(private nestService: NestService, private alertify: AlertifyService) { }

  ngOnInit() {
    this.loadUsers();
  }

  loadUsers() {
    this.nestService.getNests().subscribe((besePlaces: BasePlace[]) => {
      this.basePlaces = besePlaces;
    }, error => {
      this.alertify.error(error);
    });
  }

}

```

```
import { Injectable } from '@angular/core';
import { environment } from 'src/environments/environment';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Observable } from 'rxjs';
import { BasePlace } from 'src/_models/entities/basePlace';
import { map } from 'rxjs/operators';
import { ModelHelper } from 'src/_utility/modelHelper';
import { ModelType } from 'src/_utility/modelType';

@Injectable({
  providedIn: 'root'
})
export class NestService {
  baseUrl = environment.apiUrl;

constructor(private http: HttpClient) { }
  getNests(): Observable<BasePlace[]> {
    return this.http.get(this.baseUrl + 'nest/anonymous', this.jwt())
    .pipe(
      map(basePlace => ModelHelper.toArray(basePlace as any, ModelType.BasePlace) as BasePlace[])
    );
  }

  private jwt() {
    const token = localStorage.getItem('token');
    if (token) {
      return this.createRequestOptions(token);
    }
  }

  private createRequestOptions(token: string) {
    const headers = new HttpHeaders({ Authorization: 'Bearer ' + token });
    headers.append('Content-Type', 'application/json');
    const options = { headers };
    return options;
  }
}

```

> 2:60421/api/nest/anonymous:1 GET http://localhost:60421/api/nest/anonymous 401 (Unauthorized)
> properties:1 Access to XMLHttpRequest at 'http://localhost:60421/api/nest/anonymous' from origin 'http://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by singhsiddh** [comment]
In rest app set cors related settingsIn case rest service and angular both are in same host and port this error will not come else it is common security error .

    On Tuesday, 23 April 2019, 07:19:06 GMT+1, Hassan <notifications@github.com> wrote:  
 
 
i have to part of code in two place when i was building my application... one work with no error, another delegate to CORS, why is that?

Direct Call:
Note: no fancy stuff used, just simple call:
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {
  registerMode = false;
  values: any;

  constructor(private http: HttpClient) { }

  ngOnInit() {
    this.getValues();
  }

  registerToggle() {
    this.registerMode = true;
  }

  getValues() {
    this.http.get('http://localhost:60421/api/Nest/anonymous')
    .subscribe(data => {
      this.values = data;
    });
  }

  cancelRegisterMode(registerMode: boolean) {
    this.registerMode = registerMode;
  }
}


From Service: (Cause Cross Origin Error)
Note: i used http header... first i though because on server i used authorize attribute it cause error, then i found out even calling to a method with [AllowAnonymous] cause same issue to
import { Component, OnInit } from '@angular/core';
import { BasePlace } from 'src/_models/entities/basePlace';
import { AlertifyService } from '../_services/alertify.service';
import { NestService } from '../_services/nest.service';

@Component({
  selector: 'app-property-list',
  templateUrl: './property-list.component.html',
  styleUrls: ['./property-list.component.css']
})
export class PropertyListComponent implements OnInit {
  basePlaces: BasePlace[];

  constructor(private nestService: NestService, private alertify: AlertifyService) { }

  ngOnInit() {
    this.loadUsers();
  }

  loadUsers() {
    this.nestService.getNests().subscribe((besePlaces: BasePlace[]) => {
      this.basePlaces = besePlaces;
    }, error => {
      this.alertify.error(error);
    });
  }

}

import { Injectable } from '@angular/core';
import { environment } from 'src/environments/environment';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Observable } from 'rxjs';
import { BasePlace } from 'src/_models/entities/basePlace';
import { map } from 'rxjs/operators';
import { ModelHelper } from 'src/_utility/modelHelper';
import { ModelType } from 'src/_utility/modelType';

@Injectable({
  providedIn: 'root'
})
export class NestService {
  baseUrl = environment.apiUrl;

constructor(private http: HttpClient) { }
  getNests(): Observable<BasePlace[]> {
    return this.http.get(this.baseUrl + 'nest/anonymous', this.jwt())
    .pipe(
      map(basePlace => ModelHelper.toArray(basePlace as any, ModelType.BasePlace) as BasePlace[])
    );
  }

  private jwt() {
    const token = localStorage.getItem('token');
    if (token) {
      return this.createRequestOptions(token);
    }
  }

  private createRequestOptions(token: string) {
    const headers = new HttpHeaders({ Authorization: 'Bearer ' + token });
    headers.append('Content-Type', 'application/json');
    const options = { headers };
    return options;
  }
}



2:60421/api/nest/anonymous:1 GET http://localhost:60421/api/nest/anonymous 401 (Unauthorized)
properties:1 Access to XMLHttpRequest at 'http://localhost:60421/api/nest/anonymous' from origin 'http://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by duckShooter** [comment]
use @CrossOrigin on your controller
enable cors in your web security configuration 
```Java
configure(...) {
  http.csrf().disable().cors.and(). ..... ;
}
```

**Comment by deadmann** [comment]
@duckShooter  is this Angular or .Net-Core? cause first it's unfamiliar for me and second I was using .net-framework and Angularjs, then i migrate to Angular with same backend
