### ISSUE TITLE
ng-init="localVar = false" is not supported by Angular 2 or any equivalent?

### ISSUE THREAD

**Issue by tom10271** [angular/angular#6585]
I have started my journey in Angular 2 and lots of friends no longer exist.

Is one of the very often used directive ng-init by myself for declaring local variables is not the same as #? 

I got error for writing code like: 

```
<div #showSearch="false">
<a (click)="showSearch = !showSearch"> Click To toogle </a>
<div class="search-form" *ngIf="showSearch"> ... </div>
</div>
```

```
EXCEPTION: Template parse errors:
There is no directive with "exportAs" set to "false" ("  
        <div [ERROR ->]#showSearch="false" 
```

**Comment by zoechi** [comment]
See also http://stackoverflow.com/questions/34895083/ng-init-localvar-false-is-not-supported-by-angular-2-or-any-equivalent/34895111#34895111
GitHub issues are for bug reports and feature request, please use StackOverflow, Gitter, Google Groups, ... for questions.

**Comment by pkozlowski-opensource** [comment]
Nope, `#foo` is _not_ equivalent of `ng-init`. `ng-init` is gone and won't be back - you need to explicitly initialize fields in a component's class (equivalent of initalizing scope).

You can read up more on `exportAs` here: https://angular.io/docs/ts/latest/api/core/DirectiveMetadata-class.html

**Comment by todor-kisov** [comment]
You may use **[ngModel]="expression"** it is one way binding and works exactly the same

**Comment by tom10271** [comment]
I am asking for `ng-init` not `ng-model`

**Comment by todor-kisov** [comment]
In Angular 2 square brackets [] are used for one way binding from component class to the vie/template. So in [ngModel]="expression" if the expression doesn't change it will behave like ng-init in Angular JS/1. This is most simple near to needed solution.

**Comment by tom10271** [comment]
I don't think you need to bind it to a element, if it is declared in Component, you can use it directly already. And my problem is to initialize a new local variable but not binding something I simply don't need to bind as it is there already

**Comment by cheapsteak** [comment]
Both the links in this thread are 404s

**Comment by zoechi** [comment]
@cheapsteak you can just search for `DirectiveMetadata` in angular.io / docs / view API to get the actual link https://angular.io/docs/ts/latest/api/core/index/DirectiveMetadata-class.html

**Comment by shyamal890** [comment]
@pkozlowski-opensource @zoechi I see that you have mentioned that this feature won't be back. However, this is much needed in `ngFor` to assign length of array to local variable which can be used for DOM manipulation in template. So even if `ngInit` is not back can we expect to bind `arrayLength` to some variable in `*ngFor`?

**Comment by DzmitryShylovich** [comment]
@shyamal890 
```
`<li *ngFor="let item of items; let c = count">...</li>`
```

**Comment by amitport** [comment]
published https://www.npmjs.com/package/ngx-init
