### ISSUE TITLE
Emoji's in urls are not recognized

### ISSUE THREAD

**Issue by ubenzer** [angular/angular#6586]
I have a route config like 
```js
{ path: "/:collectionName/:categoryName/a/:page", component: MultiPost, name: "MultiPost" }
``` 

If I type `/aCollection/aCategroy/a/0` to browser it works and I see component `MultiPost` rendered.

If I change url to this:
```js
{ path: "/:collectionName/:categoryName/👀/:page", component: MultiPost, name: "MultiPost" }
``` 
and navigate to `/aCollection/aCategroy/👀/0` it does not match the route.

**Comment by mishra-ankit** [comment]
I'm a new contributor here and would love to get started with this bug fix. If someone could give me a direction on the same. Started by looking in angular-route.js.

**Comment by vsavkin** [comment]
Fixed here https://github.com/angular/angular/commit/46e105f3ab7c810ca32eebd9d5c5372b57c0f510
