### ISSUE TITLE
ngUpgrade: inject ng1 factories into ng2 application written in ES5 only

### ISSUE THREAD

**Issue by templth** [angular/angular#6588]
Hello,

I have some Angular1 code (1.4.8) defining one service and one factory:

```
function CustomService() {
}

CustomService.prototype.sayHello = function() {
  console.log('sayHello');
  console.log('[customService] sayHello');
  return 'hello';
}

angular.module('heroApp', [])
  .service('customService', CustomService)
  .factory('customFactory', function() {
    return {
      sayHello: function() {
        console.log('[customFactory] sayHello');
        return 'hello';
      }
    };
  });
```

I try to inject both into an Angular2 application (beta1) written in ES5. This works for the service but not for the factory using this code:

```
var upgrade = new ng.upgrade.UpgradeAdapter();
upgrade.upgradeNg1Provider('customService');
upgrade.upgradeNg1Provider('customFactory');

var Cmp = ng.core.
  Component({
    selector: 'cmp'
  }).
  View({
    template: '<div></div>'
  }).
  Class({
    constructor: [ CustomService, function(cService) {
      cService.sayHello();
    }]
  });

document.addEventListener('DOMContentLoaded', function() {
  ng.platform.browser.bootstrap(Cmp, [ CustomService ]);
});
```

I need to add the `CustomService` into the list of providers of the application (for example).

I try to use the same approach for the factory but I don't know what to put as provider in the `bootstrap` function. I made some tries with the `ng.core.provide` function with no success...

```
var Cmp = ng.core.
  Component({
    selector: 'cmp'
  }).
  View({
    template: '<div></div>'
  }).
  Class({
    constructor: [ ng.core.Inject('customFactory'), function(cFactory) {
      cFactory.sayHello();
    }]
  });

document.addEventListener('DOMContentLoaded', function() {
  ng.platform.browser.bootstrap(Cmp, [ ? ]);
});

```

Thanks very much for your help!
Thierry

**Comment by mhevery** [comment]
You can't use `bootstrap` with `ngUpgrade`

See working example here: http://plnkr.co/edit/yMjghOFhFWuY8G1fVIEg?p=preview

**Comment by templth** [comment]
Thanks very much, Miško, for your explanations and the sample!

**Comment by nikkwong** [comment]
This doesn't work anymore.

**Comment by gkalpak** [comment]
@nikkwong, please open a new issue with more details and a runnable demo of the problem.
