### ISSUE TITLE
Using DOM.query() other DOM methods

### ISSUE THREAD

**Issue by Arth95** [angular/angular#6589]
Hi!

I want to learn Angular 2, so I wanted to get div property via DOM methods.
This is error I got:

    Error: EXCEPTION: Error during evaluation of "click"
    ORIGINAL EXCEPTION: TypeError: dom_adapter_1.DOM is null
    ORIGINAL STACKTRACE:
    .execute/viewApp</viewApp.prototype.overBorder@http://localhost:3000/app/components/viewApp/viewApp.js:26:25
    anonymous/ChangeDetector_viewApp_0.prototype.handleEventInternal@http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js line 10897 > Function:28:19
    AbstractChangeDetector</AbstractChangeDetector.prototype.handleEvent@http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:8788:17
    AppView</AppView.prototype.dispatchEvent@http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:9396:19
    AppView</AppView.prototype.dispatchRenderEvent@http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:9391:14
    DefaultRenderView</DefaultRenderView.prototype.dispatchRenderEvent@http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:7819:32
    createRenderView/eventDispatcher@http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:9781:14
    createEventHandler/<@http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:9852:14
    decoratePreventDefault/<@http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:15370:34
    DomEventsPlugin</DomEventsPlugin.prototype.addEventListener/outsideHandler/<@http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:7874:18
    run@http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:138:14
    NgZone</NgZone.prototype._createInnerZone/<.$run/<@http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:5719:22
    NgZone</NgZone.prototype.run@http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:5681:18
    DomEventsPlugin</DomEventsPlugin.prototype.addEventListener/outsideHandler@http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:7873:1
    run@http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:138:14
    zoneBoundFn@http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:111:14

    ERROR CONTEXT:
    [object Object]

This is my code:

    import {Component} from 'angular2/core'
    import {Attribute} from 'angular2/core'
    import {EventEmitter} from 'angular2/core'
    import {DOM} from 'angular2/src/platform/dom/dom_adapter';
    import {setRootDomAdapter} from 'angular2/src/platform/dom/dom_adapter';

    @Component({
      selector: 'view-app',
      templateUrl: './app/components/viewApp/viewApp.html',
      styleUrls: ['./app/components/viewApp/viewApp.css']
    })

    export class viewApp{
     elementView: HTMLElement;
     viewHeight: number;

     overBorder(){
       var elementView = DOM.query('.view-main-screen');
       console.log(elementView);

       //var viewHeight = DOM.getProperty(elementView, 'height');
       //console.log(viewHeight);

    }
    }

**Comment by pkozlowski-opensource** [comment]
@Arth95 doing those types of low-level DOM manipulations is definitively _not_ a way to go about things in the Angular2. I would highly encourage you to go over  docs on https://angular.io/ and ask more specific support questions on https://gitter.im/angular/angular or a similar support forum.

**Comment by christaime** [comment]
@Arth95 Look at " TypeError: dom_adapter_1.DOM is null #118 " it will probably help you if you still have this problem.
