### ISSUE TITLE
TemplateCompiler.clearCache() is not clearing runtime data.

### ISSUE THREAD

**Issue by shlomiassaf** [angular/angular#6591]
I'v been playing around trying to change component template on the fly to enable live template modification.

Since heavy caching is involved in all components creations, in multiple levels, it is a hard task to do.
Every option I tried had issues.

The process is simple, use `DynamicComponentLoader` to init a new component, before that change the template by getting the component's `ViewMetadata` from `ViewResolver.resolve`

# __1 - Clearing the cache in the Compilers__
`DynamicComponentLoader` uses the current `Compiler` to do the job, the `Compiler` is actually a `RuntimeCompiler` that uses `TemplateCompiler`, so every call to `Compiler.compileInHost` will delegate to `TemplateCompiler.compileHostComponentRuntime`.

The `TemplateCompiler` class is a public injectable with a `clearCache()` member, it should clear all compiled template.
```
this.templateCompiler.clearCache();
```

Doesn't work, if we look at the source:
```
 clearCache() {
    this._styleCompiler.clearCache();
    this._compiledTemplateCache.clear();
    this._compiledTemplateDone.clear();
    this._hostCacheKeys.clear();
  }
```
Something is missing...

There is a private member `_runtimeMetadataResolver` that holds a private cache as well, every call to `TemplateCompiler.compileHostComponentRuntime` will first check if `_runtimeMetadataResolver` has the component in cache:

```
this._runtimeMetadataResolver.getDirectiveMetadata(type);
```
   
So, calling `clearCache()` is ineffective or misleading, any way cache can't be cleared completely.

A workaround is to:
```
this.templateCompiler._runtimeMetadataResolver._directiveCache.delete(MyComponent);
```
But this directly access private members... no good.

> NOTE: `clearCache()` is nice, but its rough, a developer should be able to clear a specific type, all of the Maps are using the Component type as key anyway, so its easily bubbled down.

# __2 - Using a new instance of `DynamicComponentLoader`__ 
Instead of using the injector's existing instance of `DynamicComponentLoader` we can create a new instance with a clean `TemplateCompiler` & `RuntimeMetadataResolver`.

This involves in creating a new Injector, fresh one, no tree, and populate it with all of the providers, closely to what happens on application bootstrap.
This is not light...

All of this could be avoided by just creating a child with inject overrides but this is not possible since some of the types involved are not exposed so there are no tokens.

**Comment by mhevery** [comment]
@tbosch can you comment on this? I think the easiest thing is to throw away the platform and re-bootstrap

**Comment by shlomiassaf** [comment]
@mhevery isn't it costly?

What is the expected behavior of TemplateCompiler.clearCache() ?
Shouldn't it clear the runtime metadata cache as well?

Of course clearing all of the cache is also a huge overhead when only one component needs to be cleared.

If clearCache should also clear runtime metadata cache then I think it should except a Type (or list of...) and clear them and them only. If none supplied clear all.

**Comment by tbosch** [comment]
`clearCache` was never really meant to be used from the outside :-)

Could you also create a new constructor function whenever the template is recreated? Then the cache would not be used...

@mhevery rebootstrapping would need to recreate the platform injector (and all children), and will therefore not allow to communicate with what was previously loaded.

**Comment by shlomiassaf** [comment]
@tbosch 

> clearCache was never really meant to be used from the outside :-)

Its a public member, its also available in other compiler with cache handling.

> Could you also create a new constructor function whenever the template is recreated? Then the cache would not be used.

I guess you mean creating a new component type, or making a factory for a component with different templates.
If so, wouldn't it cache all of these types and over time it will be an overhead? can I "destroy" a type (not an instance of course), I dont think I can.

Is there a reason not to allow people to invalidate a given type from the cache? its a powerful feature.

Anyway, just to give an idea, I want to allow custom templating features to the user of the component. This is doable with `ng-content` but in my case I have a directive (riding on <input />) thus I cant have `ng-content`.
I guess its possible to compile a `TemplateRef` my self and doing some crazy low level stuff to have it in... but invalidating the cache is so so easy... 

```
  let templateCompiler: any = this.injector.get(TemplateCompiler); // avoid TS screaming
        templateCompiler._compiledTemplateCache.delete(component);
        templateCompiler._compiledTemplateDone.delete(component);
        templateCompiler._hostCacheKeys.delete(component);
        templateCompiler._runtimeMetadataResolver._directiveCache.delete(component);

        this.injector.get(ViewResolver).resolve(component).template = template;
```

Of course i`m breaking the law here, but its tempting... just give me `TemplateCompiler.clearCache(type?: Type)` and i'm good :)

**Comment by tbosch** [comment]
A quick note: There won't be any compiler during runtime when users use
precompilation of templates, which will come soon. With this, users will
precompile there templates on the server into JS code...

**Comment by shlomiassaf** [comment]
@tbosch there won't be any means it won't be possible? 
There is no hybrid approach planned?

**Comment by mhevery** [comment]
You can have the runtime compiler, but your paload will be bigger. Or you can have small payload, and then there will be no compiler. You can chose.

We want this transition to be smooth, and so we are reluctant to give/recomend features which rely on compiler to be present at runtime.

**Comment by vicb** [comment]
obsolete
