### ISSUE TITLE
Child Component not picking up Host provider from Grandparent

### ISSUE THREAD

**Issue by jevenson** [angular/angular#6593]
I'm my solution (see plnkr below) I have a grandparent, parent, and child component. Ultimately, I want to inject the DemoService into the grandparent and child components, while the child component would use the same instance as the grandparent. I get this error message: 

`No provider for DemoService! (ChildComponent -> DemoService)`.

Open the plnkr link and observe that the parent is successfully able to get the grandparent's instance to DemoService. Then in `parent.component.ts`, switch the template in the `@Component` decorator via comments to include the `<child></child>` directive. Then you'll be able to observe the issue above in the developer console. The child cannot pass through the parent to get to the grandparent's instance of DemoService.

If this is intended behavior, I would really appreciate it if someone could explain why this approach doesn't work and what I can do alternatively. 

http://plnkr.co/edit/eEZvZyNW8voPsSDdwFH2?p=info

**Comment by ericmartinezr** [comment]
I'm not sure about this one. The docs says

>Specifies that an injector should retrieve a dependency from any injector until reaching the closest host.

So basically since `Parent` is the closes Children's host it will fail because `Parent` itself has no DemoService.

That's my guess. Note as well that removing `@Host` from everywhere makes your app to work as it should.

**Comment by jevenson** [comment]
Okay, you're right. I was under the impression that you needed @Host to get the parent's instance of the injected service. Otherwise it would create a new instance.
