### ISSUE TITLE
Webpack Bundled index.min.js + vendor.min.js ask for "Reflect.js.map" in safari

### ISSUE THREAD

**Issue by episodeyang** [angular/angular#6606]
This does not happen in Chrome. Looking at the source of vendor.min.js, it shows that the second line is ignored by Safari.

![sourceMapUrl](https://www.dropbox.com/s/6213y120in00lzu/Screenshot%202016-01-20%2022.08.00.png?raw=1)

![sourceMapUrlIgnored](https://www.dropbox.com/s/vkozh50tyvinwjp/Screenshot%202016-01-20%2022.08.41.png?raw=1)

Ge

**Comment by pkozlowski-opensource** [comment]
@episodeyang we are not maintaining WebPack build here in this repo. I guess you want to open this issue in one of the WebPack-based starter kits. If you are not using one and doing things on your side, you will have to dig into this problem a bit more, I'm afraid.

**Comment by episodeyang** [comment]
got it! the problem is solved after switching from `ts-loader` to `awesome-typescript-loader`.
