### ISSUE TITLE
Call multi-component in one file boot.ts

### ISSUE THREAD

**Issue by euclid1990** [angular/angular#6607]
**boot.ts**
```
import {bootstrap} from 'angular2/platform/browser'
import {HeaderMessageComponent} from './header_message.component'
import {HeaderNotificationComponent} from './header_notification.component'

declare var is_authenticated: any;

if (is_authenticated) {
    bootstrap(HeaderMessageComponent);
    bootstrap(HeaderNotificationComponent);
}
```
I have 2 component **HeaderMessageComponent** & **HeaderNotificationComponent**.
And when I import 2 component by the above way, I see console terminal. It ouput:
`(2) Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.`
The number (2) mean angular is called 2 times ? Does it make performance of application slowly ?
Have any way better to called more than one component ?

**Comment by zoechi** [comment]
Do you want two Angular components to be used independently on a site that otherwise doesn't use Angular?

**Comment by euclid1990** [comment]
@zoechi Yes. My web site built by Laravel and PHP.
I only want use angular in 2 element on header bar like following:
https://gyazo.com/ab7b75a90efc23f5a6570d4a3cb03697

**Comment by shlomiassaf** [comment]
@euclid1990 Why do you bootstrap 2 angular applications?

An Angular application runs in a Zone, each application has it's own Zone.
The zone is responsible for all change detection, so both components might not communicate well.

I really don't see any reason to bootstrap twice.

**Comment by euclid1990** [comment]
@shlomiassaf Could you help me, design new pattern for Boot 2 component in 1 times ? I have 2 html views messsage.html and notification.html in 2 separate areas.

**Comment by shlomiassaf** [comment]
@euclid1990 Build one container component that contains the 2 components you need.

They are siblings so it's not an issue.

**Comment by pkozlowski-opensource** [comment]
> Build one container component that contains the 2 components you need.

That's the way to go!
