### ISSUE TITLE
@ + in Router Config

### ISSUE THREAD

**Issue by jylinman** [angular/angular#6608]
Hey Guys,

Just wondering if it is possible to have @ or + in the URL structure (similar to how medium does their URLs) so that a URL can look like `something.com/@username`?

I have tried setting up the router both with:
```js
@RouteConfig([
  {
    path: '/@...',
    name: 'User',
    component: UserComponent
  }
])
```

And just in the app component here:

```js
@RouteConfig([
  {
    path: '/@:id',
    name: 'User',
    component: UserComponent
  }
])
```
And the result is always like this: `http://localhost:3000/@:id?id=username`... However, I can do the routes just fine if I switch out with a `/` am I missing a way to  use @?

**Comment by brandonroberts** [comment]
@jylinman I get what you are trying to do. Have you tried just using `path: '/:id'` and providing the @username?

```js
@RouteConfig([
  {
    path: '/:id',
    name: 'User',
    component: UserComponent
  }
])
```

```html
<a [routeLink]="['User', {id: '@jylinman'}]">Link</a>
```

**Comment by jylinman** [comment]
I suppose that would work, but I am concerned that it is also occupying the same route that another would try and use... For example `/:id` would also be used at the root to allow for "articles" or something else.  I am trying to have the `@` symbol be the route differentiator between a user and a post.

**Comment by brandonroberts** [comment]
Gotcha :+1:

**Comment by jylinman** [comment]
@brandonroberts Do you know if its possible to have a callback for a specific route to determin a subroute?  For instance, if we use your way, and it detects an @ symbol, then it will send it to a subroute without changing the url.  Is this possible?

**Comment by brandonroberts** [comment]
@jylinman Yes. You could have your route component navigate to another route without changing the URL using `router.navigateByUrl` or `router.navigateByInstruction`. The second argument in those functions is whether to skip the URL update.

```js
@Component({...})
class UserComponent implements OnActivate {
    constructor(public router: Router) {}
    routerOnActivate() {
        this.router.navigateByInstruction(this.router.generate(['Route', 'SubRoute']), true);
        return true;
    }
}
```

As a side note, you can do what you originally intended with the `@(...)` using a regex route path and serializer, which is supported now. See: https://github.com/angular/angular/issues/7531

**Comment by jylinman** [comment]
Fantastic! Thanks @brandonroberts huge help.
