### ISSUE TITLE
Router OnActivate does not delay render until promise settles

### ISSUE THREAD

**Issue by syndicatedshannon** [angular/angular#6611]
The documentation at:
 https://angular.io/docs/ts/latest/api/router/OnActivate-interface.html

and also the comment at line 22 here:
 https://github.com/angular/angular/blob/master/modules/angular2/src/router/interfaces.ts

... indicate that the intent is "If routerOnActivate returns a promise, the route change will wait until the promise settles to instantiate and activate child components."

We can see from the following Plunk that this is not currently the case:
 http://plnkr.co/edit/D0JNGJkFgCQM9bCj0Hy6?p=preview

Two issues I found currently directly relate to this problem:
 https://github.com/angular/angular/issues/4984 : Closed as not intended (conflicts with docs)
 https://github.com/angular/angular/issues/4015 : Open, but references OnActivate as the solution, not the problem

I understand the product is 'beta', and it's probable the router team is considering router architectural changes to address this in a different way, after discovering some needs or conflicts somewhere. 

However, I figure this qualifies as a defect currently, and it's also quite important to my use of Angular 2. Currently, I lean extremely heavily on UI-Router's resolve feature.

As a side note, I also love UI-Router's ability to inject parent resolves to children, but I appreciate that breaks the parent-agnostic Component design intent in the Component Router.

I'd love to know if the OnActivate Promise is no longer the planned implementation.

Thank you!

**Comment by syndicatedshannon** [comment]
Here is the most relevant portion of the Plunk, for convenience:

    import { Component }  from 'angular2/core';
    import { Router, OnActivate } from 'angular2/router';

    @Component({
        template: 'The model is: {{modelStatus}}'
    })
    export class DefaultComponent implements OnActivate {
        public modelStatus = "NOT ready, but we should never see this."
  
        // according to https://angular.io/docs/ts/latest/api/router/OnActivate-interface.html
        // also line 22 https://github.com/angular/angular/blob/master/modules/angular2/src/router/interfaces.ts
        // "If routerOnActivate returns a promise, the route change will wait until the promise settles to instantiate and activate child components."
  
        routerOnActivate(nextInstruction: ComponentInstruction, prevInstruction: ComponentInstruction) {
            return new Promise((res, rej) => {
                setTimeout(() => {
                    res('Now ready.');
                }, 5000);
            }).then((r) => this.modelStatus = r);
        }
    }

**Comment by brandonroberts** [comment]
@syndicatedshannon the routerOnActivate does not prevent the route from being loaded, it prevents the navigation from continuing until the promise settles. The key words are `promise settles to instantiate and activate child components`. If you have a parent route and a child route and you use routerOnActivate, the parent route will load, wait for the routerOnActivate to finish before loading the child route.

If you want to prevent the route from being rendered until the promise is settled you need to use the CanActivate decorator.

**Comment by syndicatedshannon** [comment]
Thank you Brandon. I don't immediately see how I can provide a model resolved using CanActivate into the Component constructor or component. I'm investigating, but I'd appreciate if someone confirmed that it's possible before closing this ticket.

**Comment by brandonroberts** [comment]
You currently can't access dependency injection in the CanActivate without a workaround, but its coming. If you want to see an example of this along with some other router examples, see here: 

http://plnkr.co/edit/Bim8OGO7oddxBaa26WzR?p=preview

**Comment by syndicatedshannon** [comment]
No problem, that's awesome. I just wanted to make sure it was a "planned" and not "defect" status before I moved code to this workaround.

A quick note to others who follow, the Plunk Brandon provided does use beta.1, but currently demonstrates the workaround, rather than the Angular2-futures-complete implementation.

**Comment by brandonroberts** [comment]
Good clarification :+1:

**Comment by syndicatedshannon** [comment]
Brandon's workaround here in #4112 is probably also useful if you find yourself here, due to his aforementioned current lack of DI within decorators.

**Comment by syndicatedshannon** [comment]
Closing, as the perceived defect was due to my mis-interpretation of the functionality of OnActivate.

**Comment by born2net** [comment]
tx for http://plnkr.co/edit/Bim8OGO7oddxBaa26WzR?p=preview
it's gold!

**Comment by davinkevin** [comment]
Thanks for information, but a real alternative to using @CanAcitivate to populate model would be welcomed.

**Comment by brandonroberts** [comment]
@davinkevin its being tracked here I suppose: https://github.com/angular/angular/issues/4015

**Comment by flyingsky** [comment]
The DI workaround in CanActivate cannot find existing class in parent injector. For example, I have parent injector create class A, now I want to use A in CanActivate on child component, how to do it?

**Comment by zoechi** [comment]
@flyingsky GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by born2net** [comment]
just wanted to comment that it would be very considerate from the ng2 team to update this plunkr:
http://plnkr.co/edit/8c2Wp04U2slZMi0eghWe?p=preview
with rc.2 when available and the new router. That example covers all the core important stuff for Routing and it would be GREAT if we can have that example work with rc.2 / new router
TX

Sean

**Comment by brandonroberts** [comment]
@born2net I will update the plunker with the new router once it lands

**Comment by born2net** [comment]
tx!!!!!!!!!!!!!
