### ISSUE TITLE
Implement mechanism equivalent to $templateCache

### ISSUE THREAD

**Issue by RomanKisilenko** [angular/angular#6612]
There is a common issue (IMHO) of compressing .html templates and .css styles referenced from @Components to a single resource for production environment. 

For angular 1 we have $templateCache, how we can implement similar functionality for Angular 2? And is it a good idea to do so?

**Comment by dotansimha** [comment]
Same here. 
I am using Meteor 1.3 beta5 as server side and he is the one who compiles my HTML files. 
Need to provide the ability to add files to store that brings those templates before trying to perform HTTP GET. 
In angular 1 the $templateCache.put provides that, is there any alternative in Angular 2? 
Thanks.

**Comment by ThiagoT1** [comment]
I solved that with webpack + raw-loader.

```javascript
    //templateUrl: './file.html'
    templare: require ('./file.html')
```

**Comment by tbosch** [comment]
The alternative in Ng2 will be offline compilation of templates. I.e. we
convert templates into code on the server so that we don't have to ship our
compiler at all..

**Comment by RomanGotsiy** [comment]
> The alternative in Ng2 will be offline compilation of templates

@tbosch do you have any estimates when offline compilation will be ready?
The corresponding issue (https://github.com/angular/angular/issues/3605) was closed 4 month ago

Thanks

**Comment by tbosch** [comment]
This will happen in the next month or so..

We will have it for sure before we release Angular 2 1.0.

**Comment by hlehmann** [comment]
Do you have any update about when it will be ready ?
Thanks

**Comment by webtrix** [comment]
Any news on this issue / request?

**Comment by playground** [comment]
+1 @tbosch is this available now?  Is there an example?

**Comment by amitmahbubani** [comment]
+1

**Comment by mhevery** [comment]
Something will be available soon. (As demoed at ng-conf)

**Comment by CodySchneider** [comment]
Is it done yet?

**Comment by CodySchneider** [comment]
Sorry ... I let my 8 yr old borrow my computer for a second ;)

**Comment by naveedahmed1** [comment]
@mhevery is there any update on offline templates compilation and tree-shaker mentioned in ng-con? One more question should it offer more size deduction than the bundle generated through systemJS builder.buildStatic feature?

**Comment by mhevery** [comment]
Yes, we are working hard on this. Should have some good updates in the next
few RCs.

**Comment by playground** [comment]
What can we expect to be in RC.2?

**Comment by naveedahmed1** [comment]
Thats great @mhevery! 

@playground  have a look at Angular Weekly Meeting https://docs.google.com/document/d/150lerb1LmNLuau_a_EznPV1I1UHMTbEl61t4hZ7ZpS0/mobilebasic?pref=2&pli=1

It seems that we can expect Animations, updates to the Router and support for the Template Compiler.

**Comment by ghpabs** [comment]
@ThiagoT1 would you have more info on how to implement webpack + raw-loader? Eg link to an article or tutorial.

**Comment by vicb** [comment]
You can use `CachedResourceLoader`
