### ISSUE TITLE
a template selector #6470

### ISSUE THREAD

**Issue by usernamealreadyis** [angular/angular#6613]
have been trying to only show a component based on an ng-if property. If the property is false I don't want the component to render. If the property is true I want the component to render.
1) An expepction is thrown: No provider for TemplateRef! (NgIf -> TemplateRef) #6470

``` javascript

// Assign handlers immediately after making the request,
// and remember the jqxhr object for this request
// <report-form [ngIf]="isFormVisible"></report-form>
var jqxhr = $.getJSON( "example.json", function() {
  console.log( "success" );
})
  .done(function() {
    console.log( "second success" );
  })
  .fail(function() {
    console.log( "error" );
  })
  .always(function() {
    console.log( "complete" );
  });

// Perform other work here ...

// Set another completion function for the request above
jqxhr.complete(function() {
  console.log( "second complete" );
});
```

**Comment by benlesh** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists please open a new issue and provide a StackBlitz reproducing the problem and describing the difference between the expected and current behavior. You can use this StackBlitz template: https://stackblitz.com/fork/angular-gitter
