### ISSUE TITLE
ng-animate can not be used to change of route .

### ISSUE THREAD

**Issue by ibufu** [angular/angular#6614]
I add class 'ng-animate' to  a component, but when route changed,  ng-enter and ng-leave was not added to the component.

**Comment by zoechi** [comment]
I don't think there is an ngAnimate yet.

**Comment by ibufu** [comment]
@zoechi 
I have seen the demo and success to run it. But I failed to use it to route.
https://github.com/angular/angular/blob/master/modules/playground/src/animate/animate-app.ts

**Comment by ericmartinezr** [comment]
You can use `routerOnActivate` and `routerOnDeactivaite` to achieve this.

**Comment by ibufu** [comment]
@ericmartinezr thx,but i have many route components, if I use the method, I should write routerOnActivate and routerOnDeactivaite to each route component.

**Comment by ThiagoT1** [comment]
You could try router.subscribe(...)

It fires when navigation occurs.

Thiago

**Comment by ibufu** [comment]
@ThiagoT1 thx,but i really think ng-animate should work at route changing.

**Comment by jesperronn** [comment]
@ibufu, @ThiagoT1, @ericmartinezr can you point me to a working example, which would be easier for me to understand?

**Comment by sdfacre** [comment]
you probably added ng-animate to the content not host.

**Comment by pkozlowski-opensource** [comment]
This is duplicate of #9845 and AFAIK this is work in progress.
