### ISSUE TITLE
Routing: useAsDefault - why an array member?

### ISSUE THREAD

**Issue by SetTrend** [angular/angular#6616]
I'm not absolutely sure about it yet, but I feel `useAsDefault` being a member of a `Route` within the `@RouteConfig` `RouteDefinition` array is a code smell.

What if more than one route in a route definition was having the `useAsDefault` property set to true?

I propose to extract the `useAsDefault` property from a `Route` and add it as a second, optional parameter to `@RouteConfig`, e.g:

```ts
@RouteConfig( [ { path:'/', name: 'CrisisCenter', component: CrisisListComponent }
              , { path:'/:id', name: 'CrisisDetail', component: CrisisDetailComponent }
              ]
            , useAsDefault: '/'
            )
```

instead of:
```ts
@RouteConfig( [ { path:'/', name: 'CrisisCenter', component: CrisisListComponent, useAsDefault: true }
              , { path:'/:id', name: 'CrisisDetail', component: CrisisDetailComponent }
              ]
            )
```

**Comment by sickelap** [comment]
It will throw exception if you will use multiple `useAsDefault` which make sense.
https://github.com/angular/angular/blob/master/modules/angular2/src/router/component_recognizer.ts#L84

**Comment by CaptainCodeman** [comment]
I haven't fully thought it through yet but isn't useAsDefault kind of redundant?

If the route segments are provided then the route will match anyway, but if they are missing in the URL then adding `useAsDefault` can't magically make the route match. The only time I can see it being used if for the empty route and the router should be able to figure that out itself (based on the lowest specificity?).

The discussion from here forward describes my thinking in more detail:
https://github.com/angular/angular/issues/6204#issuecomment-173387844

I'd love to know what it is meant to do for non-empty routes - does it add the static path of any route to the URL if you don't supply it?

**Comment by SetTrend** [comment]
@sickelap : That's my point: Why put `useAsDefault` into an array if there only supposed to be only a singleton in the end? Hence my suggestion to move the property out of the array.

**Comment by ericmartinezr** [comment]
With all due respect I don't like this idea at all. Consider the following code

```
@RouteConfig( [ 
           { path:'/my/long/:default/:path', ... }
           ], 
           useAsDefault: '/my/long/:default/:path'
)
```
Would I have to match the full path? Thanks, but no, thanks. 

What if I have a huge route definition (and I've seen huge route definitions)? I would have to go to `useAsDefault`, check which route it's matching and then look for that route in the paths... a brain killer... that exercise would be the same in the algorithm (take the useAsDefault path, go to route definitions, iterate over them, match paths and at that point redirect to the route).

Personally I think `useAsDefault` is perfect just like it is. Changing its behavior makes no sense.

**Comment by SetTrend** [comment]
Come on, be creative! `useAsDefault` can be anything you'd agree to as being comfortable.

You see, it's not a requirement to have the routing list be static as it is used by all the examples yet.

In the end each of the array's elements is a (not yet defined) `Route` class object. So the value of `useAsDefault` may be pointing to that object:

```ts
var r :Route

@RouteConfig( [ r = { path:'/', name: 'CrisisCenter', component: CrisisListComponent }
              , { path:'/:id', name: 'CrisisDetail', component: CrisisDetailComponent }
              ]
            , useAsDefault: r
            )
```

> What if I have a huge route definition

That's exactly my point: What if I have a huge route definition? Do you want to search through the array's elements to find the one which has the `useAsDefault` property set? What would you do if the routing list was dynamic?

**Comment by CaptainCodeman** [comment]
It seems to me that `useAsDefault` is just an alternate to having a `redirectTo` route with an empty path.

How does `useAsDefault` handle missing parameters? Can it only be used with static paths?

**Comment by ericmartinezr** [comment]
In your second example the mental exercise is the same : go to useAsDefault, check its value (whatever it is), go to route list to match their values. Personally I think it's making hard something that's simple already.

**Comment by SetTrend** [comment]
This was a static list again. Nonetheless: The suggested version can never error at runtime - in contrast to the current solution.

**Comment by SetTrend** [comment]
I'd like to add to my suggestion: Instead of using the `path` property a better option would be to utilize the `name` property for the suggested `useAsDefault` alternative.

**Comment by vicb** [comment]
obsolete - former router
