### ISSUE TITLE
Global resolve

### ISSUE THREAD

**Issue by marcalj** [angular/angular#662]
https://github.com/angular/angular.js/issues/4003

I think it will be very helpful to provide some kind of mechanism to initially wait for an optional global resolve on "app" initialization.

In some scenarios we have to fetch auth, role based permission, data model structures, etc, etc before executing the router handler.

I can put the same resolve login on each route, but feels super ugly to me. And also it's just for the really first app execution, nothing to do afterwards, so this resolves in routes will be useless.

Not sure if you plan to include a way to do this in AngularJS 2.X and also for 1.X.

Thanks!!!

**Comment by gdi2290** [comment]
This is actually really easy to do in Angular2 with the current setup. Importing your own config/run block module before app or afterwards. I can think of a few ways "fix" ng1 to have the same affect

app.js
```es6
import {bootstrap} from 'angular2/angular2';
import {appConfig} from 'app/config';
import {TodoApp} from 'components/todo-app/todo-app.js';

export function main() {
  // config() runs before app bootstraps then run()
  return appConfig.config().then(()=> bootstrap(TodoApp)).then(() => config.run());
}

```
index.html
```html
<script>
System.import('app')
    .then(function(module) {
      return module.main();
    })
    .catch(console.error.bind(console));
</script>
```

**Comment by marcalj** [comment]
Nice!!! This have to be mentioned in the documentation! ;)

**Comment by gdi2290** [comment]
angular2 is a lot more flexible compared to ng1 so this is just one of the neat benefits you get :)
you can even just use SystemJS if you wanted too since they're all just promises

```javascript
System
    .import('appConfig')
    .then(function(module) {
      return module.config();
    })
    .then(function() {
      return System.import('app');
    })
    .then(function(module) {
      return module.bootstrap();
    })
    .then(function() {
      return System.import('appRun');
    })
    .then(function(module) {
      return module.run();
    })
    .catch(console.error.bind(console));
```

**Comment by marcalj** [comment]
Great! I didn't play with it, just watch conferences talking about it. Looks really promising! Can't wait! :)
Thanks!

**Comment by pkozlowski-opensource** [comment]
I'm not sure there is any action here as in Angular2 one can fully control bootstrap process. I guess the only thing we need to assure is that people can "easily" get their hands on some fundamental services that might be needed in the pre-bootstrap (ex. equivalent of $http). 

I'm going to close this one for now as all is possible with the current design. We can think of making things easier on users when framework stabilises a bit and we see more real-life use-cases.

**Comment by marcalj** [comment]
:+1:

**Comment by ovaldi** [comment]
@gdi2290 It is necessary to remind, the module.config() does not return promise in ng1.

**Comment by gdi2290** [comment]
@ovaldi my pseudo code was an example of what you could already do in angular two years ago. 
Pre-bootstrap hook is now possible via Promise before boot using `APP_INITIALIZER` token. The `@angular/router` needs to use this feature to load the initial async/lazy route before bootstrapping


pre-bootstrap hook -> `APP_INITIALIZER` di token
during bootstrap -> use the `constructor` of your ngmodules
post-bootstrap hook -> `APP_BOOTSTRAP_LISTENER` di token
