### ISSUE TITLE
Http injecting error

### ISSUE THREAD

**Issue by barabaka** [angular/angular#6620]
There is the problem with injecting http to any component. Here is a simple component that fails when including HTTP_PROVIDERS. If I remove HTTP_PROVIDERS everything works fine. The similar error is when adding it to constructor as `http: Http` or `@Inject(Http) http`. Tested with 2.0.0-beta.0 and 2.0.0-beta.1.

```typescript
import {Component, Inject} from 'angular2/core';
import {HTTP_PROVIDERS, Http} from 'angular2/http';

@Component({
    selector: 'my-app',
    template:`
	<h1>Http Test</h1>
	`,
	providers: [HTTP_PROVIDERS]
})
export class AppComponent {
	constructor() { }
}
```
![http_injection_error](https://cloud.githubusercontent.com/assets/103233/12486357/0bce9294-c06b-11e5-97d6-5033952d7815.png)

**Comment by ericmartinezr** [comment]
Add the http bundle

```
<script src="node_modules/.../http.dev.js"></script>
```

**Comment by barabaka** [comment]
@ericcarraway Thanks, works now! I wonder if there could be a more meaningful error message :)
