### ISSUE TITLE
2.0.0-beta1: CollectionChangeRecord should be in the public API

### ISSUE THREAD

**Issue by dotansimha** [angular/angular#6622]
In order to provide the ability to create custom Differ.
Currently accessible by importing `'angular2/src/core/change_detection/differs/default_iterable_differ'` which is not part of the public API. 
Related to https://github.com/angular/angular/issues/6558.

**Comment by pkozlowski-opensource** [comment]
`CollectionChangeRecord` is public now, see: https://angular.io/docs/ts/latest/api/core/index/CollectionChangeRecord-class.html
