### ISSUE TITLE
Error in demo plunker

### ISSUE THREAD

**Issue by pidupuis** [angular/angular#6624]
The two last plunkers of the [demo page](https://angular.io/) fails on Firefox (and probably some other browsers), because of the use of `href="javascript: false"`.

Replacing it by `style="cursor: pointer;"` fixes it.

**Comment by Juleffel** [comment]
Approved.

**Comment by ericmartinezr** [comment]
There's already a PR to fix that here https://github.com/angular/angular.io/pull/719

**Comment by oulafen** [comment]
the page in [quickstart](https://angular.io/docs/ts/latest/quickstart.html) has error, tip `Uncaught ReferenceError: angular is not defined`  in chrome console when I  access it in China.

**Comment by pkozlowski-opensource** [comment]
@pidupuis @Juleffel @oulafen please direct documentation related questions / bug reports to https://github.com/angular/angular.io
