### ISSUE TITLE
Document Renderer method parameters, especially the element

### ISSUE THREAD

**Issue by wardbell** [angular/angular#6627]
The current documentation defines the type as "any", e.g.

```
setElementProperty(renderElement: any, propertyName: string, propertyValue: any)
```

That's all it says. No text to guide the developer about what that `renderElement` should be.

Why make a fuss about documentation on _this particular omission_ when so many things await documentation? Two reasons
1.  if you want to write almost any attribute directive, you HAVE to know what to pass here.
2. In beta.0 it was the `elementRef` ... something you could learn by looking at the DevGuide and external tutorials.  Beta.1 broke that; now you must pass `elementRef.nativeElement` 

**When we make breaking changes, lets take the time to document what is expected in the API docs!**

**Comment by esugoi** [comment]
Yes, I agree, I made a comment about this on issue #6515. At least put some code samples.
I don't know if they plan to change this API anytime soon, that's because they did not document it. But the beta1 API version is a work of guessing, there is no documentation at all, too bad. :(

**Comment by DzmitryShylovich** [comment]
Fixed here https://github.com/angular/angular/commit/d708a8859ca3078a98e371b33ad560096070ad00
