### ISSUE TITLE
structural directives could not be properly downgraded as an Angular 1 component

### ISSUE THREAD

**Issue by sherwoodwang** [angular/angular#6629]
When there is `<ng-content>` tag in `<template>`, the component could not been correctly downgraded.

During initialization, the `<ng-content>` inside a `<template>` may corresponds to no element in DOM. `DowngradeNg2ComponentAdapter.contentInsertionPoint.parentNode` is `null`. After <template> has been rendered into DOM, DowngradeNg2ComponentAdapter.prototype.projectContent won't been triggered again. So Angular 1 contents won't get projected after initialization.

For example:

```
    @Component({
        selector: 'cannot-be-downgraded',
        template: `
            <div *ngIf="show">
                <ng-content></ng-content>
            </div>`
    })
    export class CannotBeDowngraded {
        @Input() show: boolean = false;
    }
```

**Comment by petebacondarwin** [comment]
Fixed by #12675
