### ISSUE TITLE
Angular2 equivalent for Angular1 $parse

### ISSUE THREAD

**Issue by templth** [angular/angular#6631]
Hello,

Is there an Angular2 equivalent for the Angular1 $parse in order to converts Angular expression into a function that can be used then with a set of parameters?

Thanks very much for your help!
Thierry

**Comment by pkozlowski-opensource** [comment]
Nope, there is no `$parse` equivalent and no particular plans to add one.

**Comment by templth** [comment]
Thanks, Pawel!

**Comment by winnemucca** [comment]
Spoken with such brevity

**Comment by neilsoult** [comment]
bummer, $parse was one of the best things about AngularJs

**Comment by nicdlz** [comment]
Hi ! 
any other solutions ? 
I don't know how to use $parse in my Angular 2 component.

**Comment by nicdlz** [comment]
Hi ! 
does any one know how to use $parse in an Angular 2 component, since this issue was opened ?
