### ISSUE TITLE
Control is not removed immediately when i destroy it

### ISSUE THREAD

**Issue by abhibly** [angular/angular#6633]
Hi... I am adding a component using DCL and i am binding the components control group to parent. But when i remove control and submit the form the control is not removed.And if i make some changes like i write something into input box after removing the control and submit then it is working. How can i solve this issue? I have made a plunker demo here http://plnkr.co/edit/hOqzUkrYOIyWYkploJ4q?p=preview

**Comment by zoechi** [comment]
I don't see any submit action. Why do you expect the controls to be remove on submit?

**Comment by abhibly** [comment]
@zoechi  follow these steps:
1. Add a component and submit form.See the output in console log
2.Click on remove button and submit the form.See output in console log.here the control is not removed.
3.Make some changes in input box and again submit the form.Now control will be removed

**Comment by abhibly** [comment]
I want the control to be removed from the form when remove button is clicked.Is there a way that my control removes immediately?

**Comment by zoechi** [comment]
There is one input in the beginning. After adding one, submitting and clicking remove, there is again one. Is this not the behavior you have?
You also want the initially available input removed? or only the dynamically added ones? The dynamically added elements are removed for me.

**Comment by zoechi** [comment]
yup, could reproduce

**Comment by kittencup** [comment]
```javascript
 removeall(){
    this._children.forEach(cmp=>cmp.dispose());
    this._children = [];
    this.idx=1;
  this.completeForm.removeControl('phone1');
   this.completeForm.updateValueAndValidity()
}
```

**Comment by abhibly** [comment]
@kittencup Thank you for your help...
