### ISSUE TITLE
RouteData is not available in AsyncRoute

### ISSUE THREAD

**Issue by soulcorrosion** [angular/angular#6636]
Hello,

Found an issue in AsyncRoutes. It looks like RouteData is not preserved unlike with SyncRoutes.
Please check the following plunker: http://plnkr.co/edit/uc26p2QEMHZgiEYwqeK6?p=preview

Line 21 works, while 22 does not work.
Btw, I also have a question, how can we retrieve the name of the current route? For instance when routerOnActivate is called, I'm able to get the url path but what about the name? I need it to inject in a RouterLink.

**Comment by ericmartinezr** [comment]
dup https://github.com/angular/angular/issues/6272

**Comment by soulcorrosion** [comment]
What about the last question, can you help?

**Comment by brandonroberts** [comment]
@soulcorrosion just use the AsyncRoute type to get data working until this is fixed.

```js
new AsyncRoute({ path: '/', loader: () => Promise.resolve(ChildComponent), name: 'Sub', data : {id: "test"} })
```

**Comment by petebacondarwin** [comment]
Closing as a duplicate and there is a PR fix
