### ISSUE TITLE
Cannot run web worker with jspm

### ISSUE THREAD

**Issue by eesdil** [angular/angular#6638]
In "angular/modules/angular2/src/platform/server/parse5_adapter.ts" parse5 is referenced as:

`var parse5 = require('parse5/index');`

and as the parse5 package has main file: `lib.js`, so jspm/systemjs is not able load it.

Mapping/installing jspm package like `jspm install parse5/index=npm:parse5` solves it.

Also there is no peerdependency for parse5. If you are not using server or web worker than it is fine of course.

**Comment by ardf69** [comment]
Instead of 

jspm install parse5/index=npm:parse5 

you must use 

jspm install parse5@1.5.1.

Ciao Angelo

**Comment by pkozlowski-opensource** [comment]
This sounds like a support request that got answered.
