### ISSUE TITLE
[question] Angular 2 custom form input

### ISSUE THREAD

**Issue by TheCaptainDate** [angular/angular#6639]
Hi!
Sorry for postiong question in issues section. Already posted to stackowerflow but got no answer.

How can i create custom component which work just like native `<input>` tag? I want to make my custom form control able to support ngControl, ngForm, [(ngModel)].
As i understand i need implement some interfaces to make my own form control work just like native one.

Also, seems like ngForm directive binds only for `<input>` tag, is this righ? How cab i deal with that?

Let me explain why i need this at all. I want to wrap several input elements to make them able work together as one single input. Is there other way to deal with that? One more time: i want to make this controll just like native one. Validation, ngForm, ngModel two way binding and other. Any idead?

ps: I use Typescript.
ps: Sorry for bad English :/

**Comment by shlomiassaf** [comment]
You want to do something like an __IP Address__ component that has 4 inputs, each for an octet, but the worlds sees it as a whole, as 1 input.

I've built this one in Angular 1, I used the source code for ngModel to accomplish that.

I didn't try it in angular 2 but I believe its much simpler if you use `ControlGroup`, I think its exactly what you need.

I suggest you read the docs about [ControlGroup](https://angular.io/docs/ts/latest/api/common/ControlGroup-class.html).

You will also need to read about the Form, Control, ControlContainer, Model and other form related types, use the [API](https://angular.io/docs/ts/latest/api/) to find those and the ng* counterpart directives.

There is also a nice [Tutorial](https://angular.io/docs/ts/latest/guide/forms.html)

**Comment by byavv** [comment]
I've developed some controls, that acts just like you need with ngModel, ngControl, validation and all ng2 form's stuff. Take a look [this](https://github.com/byavv/ng2-playground/blob/master/client/app/modules/forms_explore/children.form.component.ts), [this] (https://github.com/byavv/ng2-playground/blob/master/client/app/modules/forms_explore/date.form.component.ts). [Sample usage](https://github.com/byavv/ng2-playground/blob/master/client/app/modules/forms_explore/forms.component.html#L158).
The main idea here is to implement [ControlValueAccessor](https://angular.io/docs/ts/latest/api/common/ControlValueAccessor-interface.html)

ps: My English is much worse than yours :)

**Comment by jhbe** [comment]
@byavv In your example your date-form sits within your outer form, right? But isn't nesting form tags forbidden?

**Comment by byavv** [comment]
Nested forms are really forbidden. But it works because angular forms are really ngForm, which is attached when you add FORM_DIRECTIVES to you component. But, I will update examples, thank you noticed. To avoid it you can try change <form> tag to <div> and it should work as well

**Comment by kara** [comment]
Looks like your question was answered, so closing!

**Comment by FredLoney** [comment]
Please reopen. ControlGroup is no longer in the API. It is not clear whether the @byavv example resolves the nested form prohibition. Furthermore, I don't see guidance, help, an example or a tutorial for implementing a custom non-form component that implements two-way data binding. The library I used based on the conventional wisdom, https://github.com/tb/ng2-nouislider, goes through the ngModel motions but does not reflect a model change back to the parent component. That is not a problem with the library. It seems that two-way binding only occurs when used in forms with directives supplied by Angular. If that is incorrect, I'd love to see a Plunkr example.

**Comment by byavv** [comment]
Try this tutorial: http://blog.thoughtram.io/angular/2016/07/27/custom-form-controls-in-angular-2.html

**Comment by FredLoney** [comment]
@byavv Thanks for the clear and complete tutorial; well done.

From playing around with the Plunkr, I conclude the following:

* Angular two-way [(ngModel)] binding is only available for the standard form controls as implemented by Angular. Two-way [(ngModel)] binding is not readily available for custom controls, either within or outside of a `form` element. Although perhaps the custom binding could be achieved by a deep dive into Angular internals, there is no guide or example for how to do so.

* One alternative is to propagate change from the custom control via an output. The parent component can then subscribe to the output and handle the change event.

* If the custom control is embedded in an Angular form, then ControlValueAccessor can be used in conjunction with FormBuilder and FormGroup to propagate the change back to the model. The form can be configured such that the parent component can access the custom control value via `form.value`.

**Comment by byavv** [comment]
Two way binding is available for custom controls as like as for standard if we can use these terms at all. Implementing *ControlValueAccessor*, you provide the way for @angular to receive notifications from your component about it's value change and write model value into your component. But it is an abstraction, which has custom implementation for all native elements. There are [*CheckboxControlValueAccessor*](https://github.com/angular/angular/blob/2.0.0-rc.5/modules/%40angular/forms/src/directives/checkbox_value_accessor.ts#L17-L46), [*SelectControlValueAccessor*](https://github.com/angular/angular/blob/2.0.0-rc.5/modules/%40angular/forms/src/directives/select_control_value_accessor.ts#L30-L90) and others, all implementing  *ControlValueAccessor*. And only thing they do is "listening" their "custom" update events and call function provided in *registerOnChange* when it occurs (simplifying, but that's it). And for your custom component **you need to do the same**. So, Angular doesn't care what your component is, because it doesn't work with it directly. This fact is what allow us to build any custom form input component. The only Angular need is how to construct your accessor when it's needed. That is why you register it as multiprovider. 
Based on Angular docs this class is: "a bridge between a control and a native element". Definitely not only native. 
Let me bring the sample I use in my projects: 
````javascript

...

@Component({
    selector: `myCustom`,
    template: `<button (click)="updateControl()"></button>`,   
    providers: [
        {
            provide: NG_VALUE_ACCESSOR,
            useExisting: forwardRef(() => MyCustomComponent),
            multi: true
        }
    ]
})
export class MyCustomComponent implements ControlValueAccessor {
    private _innerValue = {};
    set innerValue(value) {
        // transform it somehow
        this._innerValue = value;        
    }
    get innerValue() {
        return this._innerValue;
    }

    updateControl() {       
        const newValue = "I'm new value";
        this.onChange.next(newValue);
    }

    onTouched = () => {
    };

    @Output()
    onChange: EventEmitter<any> = new EventEmitter();

    writeValue(value) {
        if (value !== undefined) {
            this.innerValue = value;
        }
    }
    registerOnChange(fn): void {
        this.onChange.subscribe(fn);
    }
    registerOnTouched(fn): void {
        this.onTouched = fn;
    }
}

````

Usage within form
````html
<div [formGroup]='form'>     
       <myCustom formControlName="myControl" [(ngModel)]='myModel.someValue'></myCustom>
</div>
````
or regular "two-way" binding
````html  
<myCustom [(ngModel)]='myModel.someValue'>
````
or "one-way"
````html  
<myCustom [ngModel]='myModel.someValue' (onChange)="handleMe($event)">
````
Hope, it helps.

**Comment by asarapas** [comment]
Could someone explain why do we need to check for underfined in writeValue? From my observations I see that this methods gets called sometimes 2 and sometimes 3 times. First time being null - fair enough, initial object creation. Second time - actual initial value of the model - perfect. But third time being that culprit "undefined". What is causing it? I see it starts in zone.js drainMicroTaskQueue method...
