### ISSUE TITLE
Inject App Component instance

### ISSUE THREAD

**Issue by shlomiassaf** [angular/angular#6640]
Currently, AFAIK,  accessing a the application component __instance__ from a component is not possible (unless the instance is directly injected).

The reasons for me are clear, protection and isolation.

A hack is available by doing:

```
this.injector.get(ApplicationRef)._rootComponents[0];
```

Or safer with:

```
// access private types:
import {APP_COMPONENT_REF_PROMISE} from 'angular2/src/core/application_tokens';
 injector.get(APP_COMPONENT_REF_PROMISE).then(c => {
      // c = instance of root component.
 }) ;
```

I believe some components will need access to the root component instance, for example, if I would like to mimic a `attachToBody` behavior common in UI frameworks I would need access to the root component (the root is the new body in angular 2, as I see it)

I need to require an injection from the user but considering the depth of a component tree the user will have to store the reference somewhere for quick access, this is a tough requirement.
The user should be able to inject it quite easily.

Exposing `APP_COMPONENT_REF_PROMISE` will remove all isolation...

My question is, how can this be done is a secure way?
Do I have to force a user of a component to save the reference throughout the application?

**Comment by zoechi** [comment]
dup of #6217?

**Comment by zoechi** [comment]
dup of #6446

**Comment by shlomiassaf** [comment]
@zoechi It's no a dupe of #6446 

I'm asking to expose `APP_COMPONENT_REF_PROMISE`

Looking at the code in [application_ref.ts](https://github.com/angular/angular/blob/master/modules/angular2/src/core/application_ref.ts#L42):
```
/**
 * Construct providers specific to an individual root component.
 */
function _componentProviders(appComponentType: Type): Array<Type | Provider | any[]> {
  return [
    provide(APP_COMPONENT, {useValue: appComponentType}),
    // ...
```

`APP_COMPONENT` = Type of root component

While `APP_COMPONENT_REF_PROMISE` returns the instance itself wrapped in a promise.


Is there a reason not to expose APP_COMPONENT_REF_PROMISE?

**Comment by pkozlowski-opensource** [comment]
`ApplicationRef` now exposes an array of `ComponentRef`s (https://angular.io/docs/ts/latest/api/core/index/ApplicationRef-class.html) but I guess that you are after the root component so it might not be what you need.

@shlomiassaf since we've talked about those topics a lot I think that your use-case is modal-like and if so I feel the pain. Could we have the modal-related discussion in #9293 instead?
