### ISSUE TITLE
Initial page load creates duplicate history entry

### ISSUE THREAD

**Issue by pcroc** [angular/angular#6641]
If I navigate to an Angular SPA from another page (outside the SPA), I have to click back twice to return to where I was. When the page first loads a duplicate history entry is created. If I keep refreshing the SPA page, the history gets longer and longer...

Some initial investigation shows that:
* The problem does not occur if the URL that serves the SPA does not match any defined routes.
* The problem does not occur for applications that have no routing configuration.

Possibly related to #5025 ?

Using Angular 2.0.0-beta.0

**Comment by pcroc** [comment]
I believe this problem is caused by the last line of the `RootRouter` constructor: `this.navigateByUrl(location.path());`

Changing to `this.navigateByUrl(location.path(), true);` seems to prevent the problem.

Unfortunately I haven't been able to get the angular repo installed locally so can't run the tests to check this doesn't break anything, or write a new unit test - I tested this fix by patching the generated JS.

**Comment by bionicvapourboy** [comment]
+1, In multiapp sites it breaks UX when using history.back and browser history back button.

**Comment by dheeran1** [comment]
+1

**Comment by pcroc** [comment]
Hopefully will be fixed by #6069

**Comment by vicb** [comment]
obsolete - former router
