### ISSUE TITLE
RouteData should be part of public API

### ISSUE THREAD

**Issue by emesx** [angular/angular#6642]
The [RouteData](https://github.com/angular/angular/blob/a038bb9ae3a3464ba1f46c1adaabdcdc774577a0/modules/angular2/src/router/instruction.ts#L73) class currently lives under `/src` which indicates it's an implementation detail (at least in Angular 2 for Dart).

This class is necessary if you ever want to use the [Route.data](https://github.com/angular/angular/blob/6ddfff5cd59aac9099aa6da5118c5598eea7ea11/modules/angular2/src/router/route_config_impl.ts#L39) field.

Please move it out from `/src` :)

**Comment by evanplaice** [comment]
RouteData is available via ROUTER_DIRECTIVES. Does Dart support destructuring?

**Comment by emesx** [comment]
In Dart (which is what I use), the `ROUTER_DIRECTIVES` only contains the `RouterOutlet` and `RouterLink` classes. The public `router.dart` does export `RouteData` though, so maybe that's enough.

Today I feel like it's not a problem.. so feel free to remove this issue.

Cheers!
