### ISSUE TITLE
variable name enforcement turned off

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#6644]
https://github.com/angular/angular/commit/6cfc6f5bb2b166da602aff534462da756b958dcb#diff-b9e12334e9eafd8341a6107dd98510c9L330 by @btford turned off our check that we don't use keywords as variable names.

I discovered this problem in an earlier attempt to upgrade tslint - it appears that a new variable name check is turned on without being requested. Maybe a tslint bug, I need to investigate.

In the meantime we can still make dumb mistakes like

```
let f = (string) => string.length;
f(123);
```

(because of implicitAny)

**Comment by DzmitryShylovich** [comment]
@alexeagle is this still relevant?
["noImplicitAny": true](https://github.com/angular/angular/blob/master/tools/tsconfig.json#L10)

**Comment by alexeagle** [comment]
Looks like we are good due to https://github.com/angular/angular/blob/master/tslint.json#L16
