### ISSUE TITLE
Router: Provide ability to pass data to redirects

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#6650]
Currently if you want to redirect to another route, you use the redirectTo property and provide a route DSL array. There isn't a way to dynamically provide parameters to the intended destination route.

Proposal

```js
@RouteConfig([
    {
      path: '/oldpath/:id',
      redirectTo: (params: RouteParams) => {
        let userId = params.get('id');
        return ['NewPath', {id: userId}];
      }
  },
  { path: '/newpath/:id', component: NewPath, name: 'NewPath' }
])
class App {}
```

**Comment by DavidANeil** [comment]
Was this ever considered or implemented?
