### ISSUE TITLE
Better error messages when encountering invalid HTML

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#6652]
Opening this issue as a result of #6648 
It would improve the developer experience to give more detail error messages when the template parser encounters invalid HTML.
#### Example

Say you have some HTML like this:

``` html
<p><div></div></p>
```

This is invalid because `<p>` may only contain ["phrasing content"](https://www.w3.org/TR/html-markup/common-models.html#common.elem.phrasing). This is one of the more obscure rules in the specification. 

When Angular encounters this, the error message is:

```
EXCEPTION: Template parse errors:
Unexpected closing tag "p" ("<p><div></div>[ERROR ->]</p>"): HelloWorld@0:14
```

The developer here doesn't really know what the problem is, especially since actual browsers will accept this and still render something.

cc @vicb

**Comment by astec** [comment]
Agree, would be better to fail earlier with something like
```
EXCEPTION: Template parse errors:
Unexpected child tag "div" ("<p>[ERROR ->]<div></div></p>"): HelloWorld@0:14
```

**Comment by schippie** [comment]
I would like to voice my support for this issue, though for me the problem was even worse their was no error being thrown at all i had to manually enable/disable html to figure it out. This is of course mitigated by the fact that a good IDEA Webstorm etc. will warn you for such things. Though i was unaware it would cause problems like these. 

Here is my invalid HTML that caused nothing to be rendered nor any error to be thrown:

```html
		<p>We would like to have access to your webcam. So you can record yourself preforming sign language.</p>
		<p>This is done by:
			<ol>
				<li>Click on the
					<iron-icon icon="av:videocam"></iron-icon>
					within the url bar of your browser.
				</li>
				<li>Click on always allow INSERT_URL access to your camera</li>
				<li>Click on done</li>
				<li (click)="requestAccess()" style="cursor: pointer;">Click here to tell us when you have granted us
					permission
				</li>
			</ol>
		</p>
```

**Comment by patriciamarchand** [comment]
Any idea how to catch this not well formed HTML before? Which linter would you use catch this error...htmlTidy? Did you find any other case like this one, where the parser is more strict than the browser?

**Comment by radoslavpetranov** [comment]
Thanks for that @jelbourn - I was beginning to think I am blind. Didn't realize I couldn't put HTML elements (only) inside a <p> tag that was there by default (I'm using cli).

**Comment by patrikx3** [comment]
angular2 cretes custom elements in the dom.
but it forces not to allow <p><div></div></p>?
what is the idea?
