### ISSUE TITLE
Enable two way data binding on css

### ISSUE THREAD

**Issue by SuperManitu** [angular/angular#6658]
It would be really cool to be able to use two way binding on css.
E.g.: make all elements inside a div the same width equal to the widest
The template would be:
````html
<div>
    <div *ngFor="items" [(style.width)]="elementWidth"> ... </div>
</div>
```
The component would have those two properties (_elementWidth is a global variable in that component):
```typescript
set elementWidth(value : number)
{
    if(value > this._elementWidth) this._elementWidth = value;
}
get elementWidth() : number
{
    return this._elementWidth;
}
```
It would make it a lot easier for similar tasks

**Comment by pkozlowski-opensource** [comment]
Sorry, this is not going to happen. Doing so would requiring watching DOM properties and doing so is slow by default. Certain properties (like the mentioned `width`) are super-slow as merely reading it would cause reflow. 

Closing as doing what you are requesting would bring perf to its knees.
