### ISSUE TITLE
HTML import are not loading in beta.1

### ISSUE THREAD

**Issue by fr3dm4n** [angular/angular#6661]
Long story short:
I reported a problem to the developers of the google maps polymer element.
If I import a web component inside an Angular component view, I got a different result (see https://github.com/GoogleWebComponents/google-map/issues/253).

To be sure, its not a bug which has already been fixed, I tried the same with beta.1

__The problem with beta.1__  is that html import are no longer imported.
Please take a look at this Plunker:
http://plnkr.co/edit/5h6LUsiLMQkmqKq2HQi5?p=preview

The web component google-maps.html is simply not loading.

It looks like the renderer handles html-imports differently compared with beta.0 (plunkers for beta.0 can be found in the google map component ticket above).

I know, that html imports are in an early draft state, however polymers polyfills should take care of that. I suspect that it has something to do with the renderer.

Could somebody help me please?

**Comment by pkozlowski-opensource** [comment]
This sounds like a support request and as such should be discussed on one of the support channels: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
