### ISSUE TITLE
undocumented APIs in beta

### ISSUE THREAD

**Issue by naomiblack** [angular/angular#6664]
The following public APIs are undocumented in beta.1 and should be updated:

_angular2/src/core/render/api.ts_
- [ ] RenderComponentType

_angular2/src/core/linker/view_ref.ts_
- [ ] ViewRef
- [ ] HostViewFactoryRef

_angular2/src/testing/test_injector.ts_
- [ ] TestInjector
- [ ] getTestInjector
- [ ] createTestInjector
- [ ] createTestInjectorWithRuntimeCompiler

**Comment by naomiblack** [comment]
@tbosch assigning to you since most of these are in the renderer. 

@IgorMinar as FYI (and in case you want to clarify what to do about some of these in the interim, as it's not clear to me when the best time is to document them)

**Comment by naomiblack** [comment]
A current list of "not documented" API topics can be found here: https://angular.io/docs/ts/latest/api/overview-dump.html

**Comment by tbosch** [comment]
These APIs are still in flux. Can we wait until after my codegen
refactorings?

**Comment by fenduru** [comment]
I am also unable to find any documentation on `ng-content` aside from a few code examples where it is used.

**Comment by IgorMinar** [comment]
obsolete
