### ISSUE TITLE
How to test a service as injectable that takes a string parameter in constructor

### ISSUE THREAD

**Issue by nopantsmonkey** [angular/angular#6668]

**Comment by zoechi** [comment]
Can you please add some code that shows what you try to accomplish. How do you use the service in your application? If it works there why wouldn't it work in tests?

**Comment by nopantsmonkey** [comment]
I have 2 scenarios 
p.s this is an example service

```javascript
import { Injectable } from 'angular2/core';

@Injectable()
export class LocationService {
	params: {[key: string]: string};
	pathString: string;

	constructor(path: string) {
		this.pathString = path;
	}

	getParam(key: string): string {
		return this.params[key] || '';
	}

	createParamMap(): void {
		this.params = {};
		let queryString: string = this.pathString;
		let params: string[] = queryString.split(/[&||?]/);
		params.forEach((p: string) => {
			let arr: string[] = p.split('=');
			this.params[arr[0]] = arr[1];
		});
	}
}
```

1- I 've created a service and i want to use inject this service with bootstrap how to pass path parameter 
in constructor on bootstrap.

2- I want to use this service with another service should i do it like

```javascript
import {LocationService} from './locationService';
export class bService {
   private locationService: LocationService;
   constructor(path){
      this.locationService = new LocationService(path);
   }
}
```

is there any way to do it like this
```javascript
import {LocationService} from './locationService';
export class bService {
   constructor(private locationService: LocationService, path){
      //do something to initialize locationService
   }
}
```

or is there any other way to create service that takes a parameter in constructor

also i am not being able to write `location Service` unit test the below code with give this error 
`No provider for String!`

```javascript
describe('Location Service', () => {
	beforeEachProviders(() => [ LocationService ]);

	it('should parse and fetch params', inject([LocationService], (location: LocationService) => {
		let path: string = 'https://dummyurl.com/github?context=dummy&pasd=sada';
		location.createParamMap();
		expect(location.getParam('context')).toEqual('dummy');
		expect(location.getParam('undefinedvalue')).toEqual('');
	}));
});
```
----------------------------------------------------------------------------------------------------

P.S sorry for late reply

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
