### ISSUE TITLE
Enhance "Tour of Heroes" tutorial for dummies

### ISSUE THREAD

**Issue by nhducit** [angular/angular#6670]
Today, I start study Angular and I begin with: 5 Min tutorial. Everything are OK. Then I move to "Tour of Heroes" tutorial.
At "Hero Object" step: I put Hero interface below "@Component({})" and my application doesn't work as expected. I try to figure out where is the problem and find out I placed Hero interface in the wrong place. It should be placed after "import statement". That's my fault.
```ts
interface Hero {
  id: number;
  name: string;
}
```
I follow the tutorial to part 2: Master/Detail and "Displaying Our Heroes" step. I don't know where I should declare HEROES array. Because AppComponent use it, I guess I should place it before AppComponent and my application doesn't work. I have to scroll to the bottom to see where I have to place Hero array declaration, after export the AppComponent is exported. I don't why. I come from ES 5 and angular 1.
```ts
var HEROES: Hero[] = [...]
```

In tutorial, please explicit mention where developer should place new block of codes. I believe many developers have the same problem.

```ts
export class AppComponent {
//...
}

var HEROES: Hero[] = [
  { "id": 11, "name": "Mr. Nice" },
  { "id": 12, "name": "Narco" },
  { "id": 13, "name": "Bombasto" },
  { "id": 14, "name": "Celeritas" },
  { "id": 15, "name": "Magneta" },
  { "id": 16, "name": "RubberMan" },
  { "id": 17, "name": "Dynama" },
  { "id": 18, "name": "Dr IQ" },
  { "id": 19, "name": "Magma" },
  { "id": 20, "name": "Tornado" }
];
```

Meteor has a good tutorial:

![screenshot from 2016-01-24 22 42 21](https://cloud.githubusercontent.com/assets/4246176/12537199/c5cc6de2-c2eb-11e5-9ef3-4cd4111578b3.png)
https://www.meteor.com/tutorials/blaze/forms-and-events

Thanks.

**Comment by vishal123** [comment]
+1

**Comment by pkozlowski-opensource** [comment]
This belongs to https://github.com/angular/angular.io/issues
