### ISSUE TITLE
View not being updated when passing class method to observable.subscribe

### ISSUE THREAD

**Issue by Sammons** [angular/angular#6671]
Maybe this is expected behavior since I didn't find the existing issue;

Plunker here: http://plnkr.co/edit/xiqsCikskvDOivA8sMRZ, look at src/app.ts

This does not cause the view to update
```
var o = Observable.create((o) => {
      setInterval(() => { o.next(Math.floor(Math.random() * 5)) }, 1000);
    });
o.subscribe(this.update);
```
but if changed to be

```
var o = Observable.create((o) => {
      setInterval(() => { o.next(Math.floor(Math.random() * 5)) }, 1000);
    });
o.subscribe((n) => { this.update(n) });
```

then it works as I would expect. I guess this likely has something to do with Zone.js detection, but I'm not positive.

Thanks!

**Comment by bgoscinski** [comment]
This is how contexts in JS works :)
> In most cases, the value of this is determined by how a function is called. It can't be set by assignment during execution, and it may be different each time the function is called. ES5 introduced the bind method to set the value of a function's this regardless of how it's called, and ECMAScript 2015 introduced arrow functions whose this is lexically scoped (it is set to the this value of the enclosing execution context).

Check out https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this for more info.

**Comment by Sammons** [comment]
@bgoscinski my brain was someplace totally elsewhere. Thanks for bringing me back to reality ;)
