### ISSUE TITLE
Why RouteData has to be immutable? 

### ISSUE THREAD

**Issue by shubhamMuttepawar** [angular/angular#6672]
Lets say there is a parent component having two routes `path1` and `path2` and I want to navigate from `path1` to `path2` using `Router.navigate()` and while navigating I want to pass some **complex object**. I can use `RouteParams` for simple types but for complex ones I don't see how RouteParams can help and also whatever we pass in `RouteParams` is visible in URL. I don't want the data to be **visible in the URL**. Is there any other way to achieve this? 
I would also like to know if there is any specific thought process behind keeping `RouteData` immutable.

**Comment by ericmartinezr** [comment]
Really? https://github.com/angular/angular/issues/6569

**Comment by shubhamMuttepawar** [comment]
#6569 got closed so I re-opened this one explaining my usecase.

**Comment by mwawrusch** [comment]
You might want to read up on REST (https://www.ics.uci.edu/~fielding/pubs/dissertation/top.htm) and other architectural info about how to design web apps. Passing complex objects around while navigating is definitely not the way to go and is in general indicative of design flaws.

If you post more details about your problem (e.g. less abstract) then we might be able to propose a good solution for you.

**Comment by shubhamMuttepawar** [comment]
@mwawrusch  Yes, then maybe I should review my design again. Thanks for your help.
