### ISSUE TITLE
[enhancement] Angular 2: binding of multiple events at once (in template)

### ISSUE THREAD

**Issue by zifnab87** [angular/angular#6675]
As per:
http://stackoverflow.com/questions/34983140/is-there-a-way-to-bind-concisely-on-multiple-events-in-angular-2?noredirect=1#comment57695363_34983140

I was curious if there was a better way to bind on multiple events at once..
 I know I can do

```<input (keyup)="callFunc()" (keydown)="callFunc()" (customEvent)="callFunc()"/>..```

It would be great if there was such a shorthand:
```<input (keyup,keydown,customEvent)="callFunc()"/>```

Thanks,
Michail

**Comment by SimonHawesome** [comment]
+1

**Comment by robwormald** [comment]
Can you explain your use case(s) a little further?

**Comment by zifnab87** [comment]
In my use case I have a contenteditable div and I need to be updating the model everytime someone does a keypress, clicks or the domsubtree changes .. all of them trigger the same method.  Now I have them separately in three different (event) attributes

Thanks

**Comment by zoechi** [comment]
Doesn't seem a very common case. You could create a reusable directive that listens to a set of events and emits another one in case it receives one.
AFAIR since beta.7 it's supported to have event binding on a selector. 

    <div  contenteditable="true" (allEvents)="handleTheEvent($event)">

**Comment by zifnab87** [comment]
@zoechi I think what you suggest is the same thing I am doing it. I will need three times the handleEvent.

Here is my actual template with indicative methods I use:

```
<div id="editor"    
contenteditable="true" 
[innerHTML]="model"
(change)="constructModelFromHTML()" (keyup)="constructModelFromHTML();detectNewInsertion();updateQuery1();updateQuery2();updateQuery3();" 
(keydown)="preventDiv($event);constructModelFromHTML();"></div>
```

**Comment by zoechi** [comment]
I don't see how the requested feature would help in this case. You run different things for each event anyway.

**Comment by zifnab87** [comment]
@zoechi  I was thinking something like that:

<div id="editor"    
contenteditable="true" 
[innerHTML]="model"
(change,keyup,keydown)="constructModelFromHTML()" (keyup)="detectNewInsertion();updateQuery1();updateQuery2();updateQuery3();" 
(keydown)="preventDiv($event)"></div>

**Comment by SimonHawesome** [comment]
In a similar case to @zifnab87, I have a form input that is mean to run a function on (change) as well as on (blur). For now I've been writing it as such: `(change)="myFunction()" (blur)="myFunction()"` which works fine, but it's not DRY.

**Comment by TheLarkInn** [comment]
+1, this would be very beneficial especially if you wanted to bind multiple different types of keyboard keycodes to the same event, or blur and change etc. especially in elements like the <input> tag which has a lot of different events commonly bound to it with the same functionality for validation, async processes, interaction, etc. 

```html
<input type="text" (keyup.enter, keydown.control.shift.enter, blur, focus)="doTheSameThingForAllOfTheseKeyboardAndDomEvents()"  [(ngModel)]="name" />
```

If alone simply syntactic sugar, its also much DRYer than the following below.
```html
<input 
    type="text" 
   (keyup.enter)="doTheSameThingForAllOfTheseKeyboardAndDomEvents()" 
   (keydown.control.shift.enter)="doTheSameThingForAllOfTheseKeyboardAndDomEvents()" 
   (blur)="doTheSameThingForAllOfTheseKeyboardAndDomEvents()" 
   (focus)="doTheSameThingForAllOfTheseKeyboardAndDomEvents()" 
   (click)="doTheSameThingForAllOfTheseKeyboardAndDomEvents()" 
   [(ngModel)]="name" 
/>
```

**Comment by Josh1billion** [comment]
+1, this would be hugely beneficial in keeping code clean.

**Comment by ImAllInNow** [comment]
+1, in my case, I have an <input> that I want to call a updateValue() function for keyup.enter, blur, keydown.arrowdown, and keydown.arrowup. But otherwise, I don't want the updateValue() function called so that it doesn't get called with each digit the user enters. So I can't use (ngModelChange). So I end up copying the functions 4 times.

**Comment by benshope** [comment]
+1

**Comment by MrGuiMan** [comment]
+1

**Comment by TheLarkInn** [comment]
It appears that there is a little more involved to making this work _the right way_. For people who want a workaround you can either [implement it yourself](https://medium.com/@TheLarkInn/hacking-angular2-binding-multiple-dom-events-f781b14ef676#.1v9ydrcb0), or [use a plugin a wrote implementing this.](https://github.com/TheLarkInn/angular2-multievent-bindings-plugin).

https://embed.plnkr.co/kbcexKy3Q8xqvEyYiruM/ 

I've discussed this with @robwormald and it turns out there is a bit more complexity involved because of the canonical event names, etc. Code in the parser/lexer/ast is a deep dive.

**Comment by peterb0yd** [comment]
Why not just make a directive that fires on all required events? 

Easy way to keep HTML template clean.

**Comment by vicb** [comment]
not planned in a near future

**Comment by chendachao** [comment]
You can implement it with [angular2-hotkeys](https://github.com/brtnshrdr/angular2-hotkeys)

**Comment by slavafomin** [comment]
I have the following code:

```html
<input
  (change)="onValueChanged(input.value)"
  (keyup)="onValueChanged(input.value)"
  #input
>
```

And I've intuitively tried to use: `(change, keyup)` hoping it would work. I think this would be a great and very convenient addition to the API.

**Comment by gino8080** [comment]
this hack seems working

[https://medium.com/@TheLarkInn/hacking-angular2-binding-multiple-dom-events-f781b14ef676](url)

**Comment by zoechi** [comment]
@slavafomin comments on closed issues are at least "officially" ignored.
It would be better to create a new issue/feature request

**Comment by slavafomin** [comment]
@zoechi I think it would be easier to re-open this one, especially considering it was closed without any real explanation.

**Comment by zoechi** [comment]
@slavafomin but it's quite unlikely to happen, because as mentioned, closed issues are not monitored

**Comment by preda7or** [comment]
+1, desirable feature

**Comment by liukun** [comment]
Since the spaces within the brackets may lead to unexpected result like
```<input (change, keyup)="onValueChanged(input.value)"> <!-- WRONG -->```
being interpreted as
```<input (change,="" keyup)="onValueChanged(input.value)"> <!-- WRONG -->```

I suggest another format:
```html
<input (change)(keyup)="onValueChanged(input.value)"> <!-- RIGHT -->
```
which may prevent accidental spaces.

And to further improve readiness when multi-line, I suggest chain and alias actions if possible according to [specs](https://www.w3.org/TR/html5/syntax.html#elements-attributes):
```html
<input type="text"
   (blur)="submitText()"
   (keyup.enter)(keydown.control.shift.enter)=(blur)
   (alias-format-action)="formatText()"
   (focus)(click)=(alias-format-action)
/>
```
