### ISSUE TITLE
feat(Router): pass name and path to AsyncRoute loader factory

### ISSUE THREAD

**Issue by gdi2290** [angular/angular#6676]
loader should pass the name (and path) of the Route. Doing so allows for async dynamic loading

webpack1
```es6
new AsyncRoute({ path: '/about', loader: require('./about/about'), name: 'About'  })
```
es6-promise-loader
```es6
	module.exports = function (namespace) {
	  return new Promise(function (resolve) {
	    require.ensure([], function (require) {
	      resolve(require('./about/about')[namespace]));
	    });
	  });
	}
```
```es6
// the api could also change to
	module.exports = function (namespace, path) {
	  return new Promise(function (resolve) {
	    require.ensure([], function (require) {
	      resolve(require(path)[namespace]));
	    });
	  });
	}
```

also see [src/app/app.ts#L69](https://github.com/AngularClass/angular2-webpack-starter/blob/dd3e5015fa75986a6bf48ea779be7747682daec4/src/app/app.ts#L69)

### proposal
resolveComponentType should have the routeConfig or name and path
```es6
new AsyncRoute({ path: '/about', loader: (name, path) => require(path)(name), name: 'About'  })

**Comment by ollwenjones** [comment]
+1

**Comment by gdi2290** [comment]
done via new new router
https://github.com/AngularClass/angular2-webpack-starter/blob/695d779bb6d0330c3dc871ff2972fcb7b036281d/src/app/app.routes.ts
