### ISSUE TITLE
Nested Routes Broken in 2.0.0-beta.1

### ISSUE THREAD

**Issue by kukicadnan** [angular/angular#6677]
Setup

```
@Component({
    selector: 'app',
    template: `
    Root Component
    <router-outlet></router-outlet>
    `,
    ...
})

@RouteConfig([
    new Route({path:'/', name :'Home', component: Home, useAsDefault: true}),
    new Route({path:'/products/...', name:'ProductsRoot', component: ProductsRootComponent})
])
export class AppComponent {}
```

Then in the ProductRootComponent

```
@Component({
    template : `
    <h1>Product Child Component</h1>
    <router-outlet></router-outlet>
    `,
    ...
})

@RouteConfig([
    new Route({path:'/', name:'ProductsDashboard', component: ProductsDashboard, useAsDefault: true}),
])
export class ProductsRootComponent{}
```

The first path "/" works perfectly fine and loads the home component.

The second route to "/products" crashes the app. Nothing is spit out to the console - the app just hangs and eventually you get the popup asking you to kill the app.

Assume all the imports are correct (and for the @component decorator the directives and providers have been properly set - i just omitted them in the examples above)

Loading the ProductsDashboard component directly in a separate route works as well. Just the nested `<router-outlet>` refuses to work.  

Any ideas? Searched for open issues and didn't find anything relating to this.

**Comment by kukicadnan** [comment]
After messing with it some more - I've figured it out - it was an error on my part. My apologies.

**Comment by sickelap** [comment]
Maybe you might like to share what exactly was wrong as it might help the others.

**Comment by kukicadnan** [comment]
I got it working - then deleted the routes as they were just temp routes - so when I went to do the real implementation I ran into same issue. Not exactly sure what problem is but as soon as I figure it out I don't mind updating the ticket.  I'll also try to create a plnkr if I have time today for reference.

**Comment by sickelap** [comment]
I was having the same problem, solution was to add `useAsDefault: true` to one of sub-routes

**Comment by kukicadnan** [comment]
Strange. I had the useAsDefault set to true on one of the child routes and still had the problem.  Will try to track down the issue tonight and update ticket accordingly.
