### ISSUE TITLE
Incorrect error message when incorrect route in ChildComponent

### ISSUE THREAD

**Issue by aaronfoote** [angular/angular#6680]
When a component with a @routeconfig defined calls router.navigate( ['RouteName']) with an invalid route name the error message is correct:
"Component "BugComponent" has no route named "BugDummyyyyyy"."

However when a child component calls router.navigate() with an incorrect route name the error message is very confusing
"Component "BugDummy" has no route config."

Parent component:
```typescript
import {Component} from 'angular2/core';
import {RouteConfig, ROUTER_DIRECTIVES, Router} from 'angular2/router';
import {BugDummy} from './bug-dummy.component';
@Component({
    selector: 'bug',
    template: `   
    <h2>Roter Bug Test</h2> 
    <router-outlet></router-outlet> 
  `,
    directives: [ROUTER_DIRECTIVES]
})
    @RouteConfig([
        { path: '/bug-dummy', name: 'BugDummy', component: BugDummy, useAsDefault: true }
])
export class BugComponent {
    constructor(private _router: Router) {
        _router.navigate(['BugDummy']);
    }
} 
```

child component
```typescript
import {Component} from 'angular2/core';
import {Router} from 'angular2/router';

@Component({
    selector: 'bug-dummy',
    template: `   
    <h2>Roter Bug Test Dummy</h2> 
  `
})
export class BugDummy {
    constructor(private _router: Router) {
        this._router.navigate(['Bugdummyyyy']);
    }
} 
```

**Comment by ericmartinezr** [comment]
When you write `['Bugdummyyyy']` or `['./Bugdummyyyy']` you're navigating relative to the component where you are. Since `BugDummy` has no `@RouteConfig` it can navigate to the component itself, therefore the error message which is pretty clear.

**Comment by aaronfoote** [comment]
A Child component can navigate to route-names defined in the parent component.  This bit works fine.

The problem is that when a a child component tries to navigate to a route that is not defined in the route hierarchy, the error message is incorrect, confusing, and is very hard to debug.

To be clear - ['BugDummy'] will match on the route name defined in the route config..  I have not experimented with playing with matches on the 'path' defined in a route config so I will not speculate on that behavior.

**Comment by vicb** [comment]
obsolete - former router
