### ISSUE TITLE
Wrong Http status error

### ISSUE THREAD

**Issue by gustavolira** [angular/angular#6681]
Hi,
I'm using angular2 beta.1 and if I get the status code from some http error callback the status code is always 200.
Example:
this.http.get('http://foo/bar',{ headers: this.header}).subscribe(
        data => this.items = data.json(),
        error=> console.log(error.status) //Always 200 even if the server return something different
      );

**Comment by pkozlowski-opensource** [comment]
What is the version of Angular that you are using? Could you please provide a live reproduce scenario using plunker or similar?

**Comment by gustavolira** [comment]
Hi, first of all thanks for your attention
I'm using Angular 2.0.0-beta.1. I will create a plunker at night and update here

**Comment by tbragaf** [comment]
The same is happening to me, even when the API is down

**Comment by jeffbcross** [comment]
I created a plunker with beta.0 and beta.2 and could not reproduce: http://plnkr.co/edit/WMxNlGSYB004UG4tIURQ

@gustavolira or @tbragaf feel free to fork that plunker and create a reproducible case, and open a new issue with the reproduction. And please mention me in the issue so I'll see the notification.

**Comment by tbragaf** [comment]
@jeffbcross 
Replace '/foo' by 'localhost:12345'.

In the plunkr it gives a CORS error.
However, that is not happening with me since my app actually works, but if I close the API, it still throws 200.

**Comment by tbragaf** [comment]
@jeffbcross Also this:
![image](https://cloud.githubusercontent.com/assets/8090726/12759086/4491ffe2-c9d7-11e5-9330-508bbca94d66.png)

"The response had HTTP status code 404." > correctly thrown error.
But as you can see 200 is the status code.

**Comment by tbragaf** [comment]
@jeffbcross Also insecure response:
![image](https://cloud.githubusercontent.com/assets/8090726/12759170/a48f48e6-c9d7-11e5-96ba-8574cbf83f7a.png)

**Comment by binarious** [comment]
Dupe of https://github.com/angular/http/issues/54.

**Comment by gustavolira** [comment]
Any news about this?
