### ISSUE TITLE
Service bootstrap injection error

### ISSUE THREAD

**Issue by mrpotato3** [angular/angular#6682]
I have a problem with service injection in bootstrap. I tried all but I have this error all the time:

![error](https://cloud.githubusercontent.com/assets/9481003/12558226/d8746384-c38e-11e5-8c58-3d807154c24d.png)

UserService
```javascript
import {Http} from 'angular2/http';
import {Injectable} from "angular2/core";

@Injectable()
export class UserService
{
    id:string;
    name:string;
    email: string;

    constructor(http:Http)
    {
        this.authenticated = false;
    }

    login()
    {
        console.log('login()');
        this.authenticated = true;
    }

    logout()
    {
        this.authenticated = false;
    }

    isAuthenticated()
    {
        return Promise.resolve(this.authenticated);
    }

}
```

Boot
```javascript
import {bootstrap}    from 'angular2/platform/browser'
import {ROUTER_PROVIDERS, APP_BASE_HREF} from 'angular2/router';
import {AppComponent} from './app.component'
import {PathLocationStrategy} from "angular2/router";
import {LocationStrategy} from "angular2/router";
import {provide} from "angular2/core";
import {HTTP_PROVIDERS} from "angular2/http";
import {UserService} from "./user.service";


bootstrap(AppComponent, [
    ROUTER_PROVIDERS,
    HTTP_PROVIDERS,
    provide(LocationStrategy, {useClass: PathLocationStrategy}),
    provide(APP_BASE_HREF, {useValue : '/'}),
]);
```

There's something wrong?

Many thanks.

**Comment by spock123** [comment]
You need to reference UserService in the bootstrap call

**Comment by spock123** [comment]
Remember: services injected in bootstrap are singletons for the whole app. If you provide the service in a component, the service will be a singleton for that component (and child components) only

**Comment by mrpotato3** [comment]
Yes, sorry. I did a mistake with copy & paste. Correct code for 'Boot' is:

```javascript
import {bootstrap}    from 'angular2/platform/browser'
import {ROUTER_PROVIDERS, APP_BASE_HREF} from 'angular2/router';
import {AppComponent} from './app.component'
import {PathLocationStrategy} from "angular2/router";
import {LocationStrategy} from "angular2/router";
import {provide} from "angular2/core";
import {HTTP_PROVIDERS} from "angular2/http";
import {UserService} from "./user.service";


bootstrap(AppComponent, [
    ROUTER_PROVIDERS,
    HTTP_PROVIDERS,
    UserService, //-> ERROR
    //provide(UserService, {useClass: UserService}),
    provide(LocationStrategy, {useClass: PathLocationStrategy}),
    provide(APP_BASE_HREF, {useValue : '/'}),
]);
```

I'm getting that error with this code.

Yes, I need a singleton. :)

Thanks @spock123.

**Comment by spock123** [comment]
In your UserServices, shouldn't this.authenticated be defined in the class?

I am on a cellphone so cannot run your code , sorry


Your bootstrap code looks good to me

**Comment by mrpotato3** [comment]
Yes, hehe. It's already declared but I pasted old code, sry. The error still remains.

**Comment by machi1990** [comment]
Everything looks fine to me. Do you have only these two files? I do not think the error comes from the files you posted. Possible to provide the whole log messages so that we can help? Or reproduce this using plunker?

**Comment by mrpotato3** [comment]
Nope, I have many other files, but they're not using sevice by the moment.
Error appears when I put 'UserService' into bootstrap. It's frustrating because It's the same config as "Hero" tutorial. :/

**Comment by mrpotato3** [comment]
I attach full error...
![error](https://cloud.githubusercontent.com/assets/9481003/12564025/686b0f2e-c3ad-11e5-9662-3abb5ddfca53.png)

**Comment by ericmartinezr** [comment]
@mrpotato3 make a plnkr with your configuration, or share a repo. Besides move your questions to StackOverflow, o gitter's chatroom (you'll get more help over there). Can you specify which angular2 version are you using? In beta.1 the line 351 points to a `}` and in beta.0 points to a function called `print`.

**Comment by machi1990** [comment]
Should be beta.0. Angular's trying to print something which is undefined? He'll get more help with the plunker page reproducing his problem.

**Comment by mrpotato3** [comment]
Hi, I was using Angular beta.0. I upgrade to beta.1 but the error persists.
After hours and tests I discovered what's causing the error.

In bootstrap If you use:

```javacript
provide(LocationStrategy, {useClass: PathLocationStrategy}),
```

and you import your own service, app crashes.

**Comment by brandonroberts** [comment]
@mrpotato3 one thing I see from your imports in you're mixing single quotes and double quotes. Change all your imports to single quotes.

Example: http://plnkr.co/edit/glVHkXYMsSyBkFdxd1pM?p=preview

**Comment by pkozlowski-opensource** [comment]
Sounds like a support request that got resolved.
