### ISSUE TITLE
Consider exposing verifyNoBrowserErrors

### ISSUE THREAD

**Issue by juliemr** [angular/angular#6684]
`verifyNoBrowserErrors` is used in Angular's own e2e apps and is useful for smoke tests. Consider exposing it. (Note that the correct place to expose it may be a helper in Protractor, not anything from angular2)

cc @wardbell

**Comment by juliemr** [comment]
Code at https://github.com/angular/angular/blob/master/modules/angular2/src/testing/e2e_util.ts#L10

Note that there's some bugs here and it may not be cross-browser compatible at the moment.

**Comment by wardbell** [comment]
Might be sufficient for our immediate need of testing samples which we only bother to do in Chrome.

For general audiences, we'd need a robust version.

This will be helpful in teasing people into the e2e testing waters. Once they have a smoke test, they've got *something* which is better than nothing. More importantly, they have the prospect of better tests to come.

**Comment by vikerman** [comment]
Obsolete.
