### ISSUE TITLE
DI has a limit of 20 parameters but Dart transformer does not throw an error when limit is exceeded

### ISSUE THREAD

**Issue by vikerman** [angular/angular#6690]
There is a limit of 20 parameters for Angular 2 DI. However the Dart transformer doesn't throw an error when this limit is exceeded. During run time a null is returned when injecting the class which has more than 20 parameters in it's constructor.

The Dart transformer should throw an error when the limit is exceeded.

**Comment by tbosch** [comment]
Changing this to throw during instance creation, not in the transformer run, as the transformer is actually not limiting the number of arguments, but the runtime.

With #6270 this limit will go away as well.
