### ISSUE TITLE
Error in injecting one component to others with the same parent

### ISSUE THREAD

**Issue by resec** [angular/angular#6697]
I have a simple Angular2 Application, which contains `App`, `P1`, `P2`, `Child` in total 4 components, where `App` uses `P1` and `P2`, and both `P1` and `P2` uses `Child`.

Here is the code:

    @Component({ 
      selector: 'child',
      template: '<div> child <div>',
    })
    export class ChildCmp {}
    
    @Component({ 
      selector: 'p1',
      template: '<div> P1: <child></child></div>',
      directives:[ChildCmp],
    })
    export class P1Cmp {}
    
    @Component({ 
      selector: 'p2',
      template: '<div> P2: <child></child><child></child></div>',
      directives:[ChildCmp],
    })
    export class P2Cmp {}
    
    @Component({ 
      selector: 'my-test',
      template: '<p1></p1><p2></p2>',
      directives:[P1Cmp, P2Cmp],
    })
    export class TestApp {}
    
    bootstrap(TestApp);

The **index.html** to trigger the app is plain `<my-test></my-test>` with all required libs of Angular2.

You can check the demo in [Plunker][1], console log shows

    EXCEPTION: TypeError: viewFactory_ChildCmp0 is not a function

Why it breaks? 

This only happen when I put the `Child` into the both `P1` and `P2`, where they are in the same parent component.

I think it is normal for developer to buildup some reusable component like `child` then use it all around? 

The Angular version is beta.01 and I tried this in Chrome and Firefox in both Ubuntu and Mac.

  [1]: http://plnkr.co/edit/Kir7QmwhSsIuAU5IrnMh?p=info

**Comment by zoechi** [comment]
See also http://stackoverflow.com/questions/35008652/cannot-inject-reusable-component-to-different-components-in-the-same-level-in-an

**Comment by resec** [comment]
Just tired with `Beta.00`, it is working, so the problem is only limited to `Beta.01`.

**Comment by pkozlowski-opensource** [comment]
I believe that this is duplicate of https://github.com/angular/angular/issues/6404 and is already fixed in master.

**Comment by resec** [comment]
Yes, they are the same, thanks, @pkozlowski-opensource. Closing this one.
