### ISSUE TITLE
resetting ngModel of a textbox does nut update the value correctly.

### ISSUE THREAD

**Issue by NisStrom** [angular/angular#6700]
I have a textbox that only allows entering numbers between 1-9. However the range of the input can be variable, for example 1-25. So when initial the value in the textbox is 1 and the user enters a number higher than 25, like 30 then i want to reset the ngModel of the textbox to 25. 
This works as expected, however if the value before the change already was 25, then the textbox value is not getting updated correctly. The ngModel correctly changes to 25, and the behavior in the component is as expected. Only the UI Element displays the wrong value.

See the attached Plunker of this StackOverflow Post:
http://stackoverflow.com/questions/34893448/angular2-input-ngmodel-limiting-possible-values

**Comment by aciccarello** [comment]
I'm not sure that there is a bug here. I have left a suggestion on the StackOverflow post.

**Comment by zoechi** [comment]
Is this still an issue?

**Comment by pkozlowski-opensource** [comment]
Sounds like a support question and there are already answers on SO.
