### ISSUE TITLE
Input decorators not working in extended class

### ISSUE THREAD

**Issue by connorwyatt** [angular/angular#6701]
I have an abstract class with an @Input() decorator on a property, and when I extend that class I add a second @Input() decorator on a different property. The property on the original abstract class is not on the instance when it compiles. However when I remove the second property's decorator the first works again.

I would expect that both bindings would work however I'm not sure whether the issue is as I have outlined or that you can in some cases bind an @Input() on an abstract class.

P.S. I am using an abstract class as multiple classes have the same logic (as they are all input types), however I am aware that on its own @Input() doesn't make sense on an abstract class.

**Comment by zoechi** [comment]
dup of #5415 ?

**Comment by pkozlowski-opensource** [comment]
Let's centralize discussion on inheritance in #11606
