### ISSUE TITLE
[(ngModel)] on select does not work in IE10, IE11

### ISSUE THREAD

**Issue by NisStrom** [angular/angular#6703]
When using ngModel on a select element and setting the model to the desired initial value in the constructor or ngOnInit, the select value stays empty. In Firefox and Chrome this works fine but not in IE10/IE11.

See the example Plunker here: http://embed.plnkr.co/EKQcB2ZtnEetRrLYUq78/ (Note this does not work in IE but you can check out the code used in app.ts)

**Comment by brandonroberts** [comment]
@NisStrom IE needs specific polyfill scripts to work. Your included scripts should look something like this.

```
    <!-- IE required polyfills, in this exact order -->
    <script src="node_modules/es6-shim/es6-shim.min.js"></script>
    <script src="node_modules/systemjs/dist/system-polyfills.js"></script>

    <script src="node_modules/angular2/bundles/angular2-polyfills.js"></script>
    <script src="node_modules/systemjs/dist/system.src.js"></script>
    <script src="node_modules/rxjs/bundles/Rx.js"></script>
    <script src="node_modules/angular2/bundles/angular2.dev.js"></script>
```

**Comment by NisStrom** [comment]
@brandonroberts I know, it is still not possible to run the plunkr project in IE.
 I could provide you with an demoproject i created using ng2-play. Howevery Github does not allow me to upload a ZIP file. If you check out the code in app.ts, you see it is a very easy use case.

**Comment by NisStrom** [comment]
Here is the demo project, just change the file ending back .zip. 

[angular2_error_select_ngModel.pdf](https://github.com/angular/angular/files/106152/angular2_error_select_ngModel.pdf)

**Comment by cnaut** [comment]
@NisStrom did you try changing the es6-shim version to 0.34.2? This resolved some issues for me

**Comment by NisStrom** [comment]
@cnaut no, this does not work you can confirm it by changing the version in the demo project. Furthermore, even the newly released angular2 beta-2 is still referencing es6-shim 0.33.3.

**Comment by zoechi** [comment]
dup of #6573 ?

**Comment by NisStrom** [comment]
Well, this is in beta-0 and only in IE. #6573 is for beta-1 and Firefox. IF you check the demoproject with beta-1 and beta-2, it works all fine in Firefox, however in IE the issue still exists.

**Comment by mdsauer** [comment]
I am seeing this with beta-6 with IE11

**Comment by kara** [comment]
It looks like this issue was resolved, so I'm closing. See commit https://github.com/angular/angular/commit/c3daccd83b86e453ce538fa7f75c4cff2564a836.
