### ISSUE TITLE
Flip the import statement

### ISSUE THREAD

**Issue by vishal123** [angular/angular#6704]
Currently the import statement reads `import {class} from 'file'`.

This feels like the wrong way round because naturally you would type it in that order and the class would not exist and the IDE shows an error. Once you've entered the file name, the error goes away.

While this might not be the best solution, I guess it works in this case to instead say, `from 'file' import {class}`.
This allows an IDE to load the file before you start typing the class name and hence you get support from intellisense.

I guess the IDE's will eventually solve this by automatic discovery from unreferenced files, but unless there is a specific reason for the current ordering, maybe its something that can be improved now before "RTM".

**Comment by pkozlowski-opensource** [comment]
`import` syntax is not Angular specific, you would have to "fix it" in the ‎ECMAScript (JavaScript) itself, see:
* https://developer.mozilla.org/en/docs/web/javascript/reference/statements/import
* http://www.ecma-international.org/ecma-262/6.0/index.html#sec-imports

Closing as invalid.
