### ISSUE TITLE
No provider for String!

### ISSUE THREAD

**Issue by SakalaWeb** [angular/angular#6705]
Hi can somebody tell Me what am I doing wrong?
I think it's simple error, but I'm new to angular and I can't find it.
EXCEPTION: No provider for String! (SwNavItemCmp -> String)

////////////////////////////////////////////////////

export interface SwNavItemModel {
name: string;
  route: string;
  children?: Array<SwNavItemModel>;
}

/////////////////////////////////////////////

import {SwNavItemModel} from '../models/sw_nav_item_model';

export const NAV_ITEMS_DATA: Array<SwNavItemModel> = [
  { name: 'Home',
  	route: '/Home' },
  { name: 'Offer',
    route: '/Offer',
  	children: [
      { name: 'Prices',
      	route: '/Prices' },
      { name: 'Samples',
        route: '/Samples' }
    ]
  },
  { name: 'About',
    route: '/About',
    children: [
      { name: 'Us',
        route: '/Us' },
      { name: 'Projects',
        route: '/Projects' },
      { name: 'Skills',
        route: '/Skills' }
    ]
  },
  { name: 'Contact',
    route: '/Contact' }
];

////////////////////////////////////////////

import {Injectable} from 'angular2/core';
import {NAV_ITEMS_DATA} from '../data/mock_nav_data';

@Injectable()
export class NavService {
	getNavData() {
		return Promise.resolve(NAV_ITEMS_DATA);
	}
}

//////////////////////////////////

import {Component, OnInit} from 'angular2/core';
import {
ROUTER_DIRECTIVES
} from 'angular2/router';
import {SwNavItemCmp} from './sw-nav-item/sw_nav_item';
import {SwNavItemModel} from '../../../models/sw_nav_item_model';
import {NavService} from '../../../services/nav_service';

@Component({
  selector: 'sw-nav',
  templateUrl: './components/shared/sw-nav/sw_nav.html',
  styleUrls: ['./components/shared/sw-nav/sw_nav.css'],
  providers: [NavService],
  directives: [ROUTER_DIRECTIVES, SwNavItemCmp]
})
export class SwNavCmp implements OnInit {
  public items: Array<SwNavItemCmp> = []

  constructor(private _navService: NavService) {
  }

  ngOnInit(): any {
    this.getNavData();
  }

  getNavData() {
      this._navService.getNavData().then((navData: Array<SwNavItemModel>) => {
          console.log(navData);
          console.log(Object.keys(navData));
          this.addItems(navData);
      });
  }

  addItem(name: string, route: string, children?: Array<SwNavItemModel>) {
    console.log();
    console.log('name: ' + name);
    console.log('route: ' + route);
    console.log('children: ' + children);
    if(children) {
      let childrenItems: Array<SwNavItemCmp> = [];
      console.log('childrenItems: ' + childrenItems);
      children.forEach((child) => {
        console.log('child: ' + child);
        childrenItems.push(new SwNavItemCmp(child.name, child.route, null));
        console.log('childrenItems: ' + childrenItems);
      });
      this.items.push(new SwNavItemCmp(name, route, childrenItems));
      console.log('Items: ' + this.items);
    } else {
      this.items.push(new SwNavItemCmp(name, route, null));
      console.log('Items: ' + this.items);
    }
  }

  addItems(itemsArray: Array<SwNavItemModel>) {
    console.log('ItemsArray: ' + itemsArray);
    itemsArray.forEach((item) => {
      console.log('item: ' + item);
      item.children ? this.addItem(item.name, item.route, item.children) : this.addItem(item.name, item.route, null);
    });
    console.log('Items: ' + this.items);
  }
}

/////////////////////////////////////////////////
sw_nav.html

<nav>
	<sw-nav-item [items]="items"></sw-nav-item>
</nav>

//////////////////////////////////////////////

import {Component, Input} from 'angular2/core';
import {ROUTER_DIRECTIVES} from 'angular2/router';

@Component({
  selector: 'sw-nav-item',
  templateUrl: './components/shared/sw-nav/sw-nav-item/sw_nav_item.html',
  styleUrls: ['./components/shared/sw-nav/sw-nav-item/sw_nav_item.css'],
  directives: [ROUTER_DIRECTIVES]
})
export class SwNavItemCmp {
	@Input() items: Array<SwNavItemCmp>;
  name: string;
  route: string;
  children?: Array<SwNavItemCmp> = [];
  constructor(name: string, route: string, children?: Array<SwNavItemCmp>) {
    this.name = name;
    this.route = route;
    this.children = children;
  }
}

///////////////////////////////////////////////////

**Comment by zoechi** [comment]
You could wrap code-blocks with ``` for proper formatting.

**Comment by ericmartinezr** [comment]
```
constructor(name: string, route: string, children?: Array) {
```
That's what you're trying to do. You're passing your class as a directive, angular2 tries to instantiate it and it can't find providers for your class, in this case two strings and an array.

Please move your questions con StackOverflow or Gitter's chatroom.

**Comment by zoechi** [comment]
Ok, you win ;-)

**Comment by pkozlowski-opensource** [comment]
> Please move your questions con StackOverflow or Gitter's chatroom.

Exactly! https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
