### ISSUE TITLE
es6-shim reflect-metadata bundle conflict

### ISSUE THREAD

**Issue by UWouldlLose** [angular/angular#6706]
Library Versions
Angular: beta.0
es6-shim: 0.33.3

I have a gulp task which bundles up some of the scripts I need to import using uglify. 

```
gulp.task('concat:depsjs', function () {
    //Uglyify gets SUPER slow if you pass it minified files, make sure to bundle full libraries
    return gulp.src([
        'node_modules/es6-shim/es6-shim.js',
        'node_modules/systemjs/dist/system-polyfills.js',
        'node_modules/chart.js/Chart.js',
        'node_modules/angular2/bundles/angular2-polyfills.js',
		'node_modules/systemjs/dist/system.js'
    ])
    .pipe(concat('deps_bundle.js'))
    .pipe(uglify({mangle: false, preserveComments: true}))
    .pipe(gulp.dest('dist/vendor'));
});
```

In the given bundle, es6-shim is throwing an exception in the `defineOrOverrideReflectProperty` function ln3222. At this point Reflect is undefined and the lookup blows up. 

```
if (!ES.IsCallable(globals.Reflect[key])) {
      defineProperty(globals.Reflect, key, shim);
    }
```
Ln203 of es6-shim attempts to set `window.Reflect` by calling `defineProperty`. `defineProperty' returns immediately i believe because ln2338 of angular2-polyfills is also setting a Reflect variable. Since reflect exists in window, the function escapes, even though it's set to undefined. 

```
var defineProperty = function (object, name, value, force) {
    if (!force && name in object) { return; }
    if (supportsDescriptors) {
      Object.defineProperty(object, name, {
        configurable: true,
        enumerable: false,
        writable: true,
        value: value
      });
    } else {
      object[name] = value;
    }
  };
```

I'm not sure what the best course of action would be. Monkeypatching the es6-shim library to force `window.Reflect` to be set to `{}` allows the bundle to work, but isn't something I'd want in there long term. 

```
 // Reflect
  if (!globals.Reflect) {
    defineProperty(globals, 'Reflect', {});
  }

  //Andrew Hack
  if (!globals.Reflect)
  {
    globals.Reflect = {};
  }
```

Would it make sense to update es6-shim to also check if a function is undefined before returning early?

**Comment by oguimbal** [comment]
+1
Same scenario.

**Comment by danmarshall** [comment]
+1 
es6-shim cannot be in the same bundle as angular2-polyfill.
The Quickstart demos work because they aren't bundled.

**Comment by UWouldlLose** [comment]
@danmarshall Are you saying the code can't be changed to allow these two to be bundled together? If so why?

**Comment by carvadero** [comment]
@UWouldlLose no, I'm not saying that it cannot be changed. I'm saying that this is the current state of affairs.Sorry if that wasn't clear. This is a bug! I am referencing the two files that have the conflict.

**Comment by pkozlowski-opensource** [comment]
we've moved from es6-shim and bundling so this one is obsolete
