### ISSUE TITLE
Add API to override the rendered tagName for a component.

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#6710]
There are times when you want to offer a component API that uses a custom element, but _render_ something different. The most basic use-case: we want to provide the material button as `md-button`:

``` html
<md-button (click)="doStuff()"> GO! </md-button>
```

The problem with this is that you lose out on everything the native button element gives you (accessibility, interaction with form elements). You could put a native button _inside_ of the component, but then you end up forward a bunch of [properties](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button) with bindings that you don't really need. As such, the current implementation necesates the API:

``` html
<button md-button (click)="doStuff()"> GO! </button>
```
### Proposal

Add a configuration option to `@Component` for something like `renderAs` or `renderHostAs` (final name TBD). This would be a static string that is used as the rendered name of the component. The concept of the host having a name applies to every platform, not just the web. 

``` ts
@Component({
  selector: 'md-button',
  renderAs: 'button',
  ...
})
class MdButton() { ... }
```

I've chatted with @tbosch and he says that this should be trivial to implement. I would plan on making this change myself once his latest large-scale refactoring is complete (just to avoid merge conflicts).

**Comment by jelbourn** [comment]
cc @mhevery for thoughts

**Comment by gdi2290** [comment]
@jelbourn does this work too?
```typescript
@Component({
  selector: 'md-button',
  renderAs: 'div.md-button',
  //...
})
class MdButton() { ... }
```
or
```typescript
@Component({
  selector: 'md-button',
  renderAs: 'button.md-button',
  //...
})
class MdButton() { ... }
```

**Comment by kittencup** [comment]
+1

**Comment by sunao0626** [comment]
+1

**Comment by kunl** [comment]
+3

**Comment by jzlxiaohei** [comment]
+1

**Comment by leshin** [comment]
+ 9999999999999999

**Comment by WilliamDu1981** [comment]
+1

**Comment by jelbourn** [comment]
@gdi2290 classes and attributes can already be set to the host element using the `host` property, so I don't think they would be necessary.

**Comment by laco0416** [comment]
+1

**Comment by gkalpak** [comment]
LOL - so ng2 _will_ support `replace: TRUE` after all :stuck_out_tongue:

**Comment by zoechi** [comment]
sounds similar to Polymers `<button is="custom-button>` to extend DOM elements

**Comment by PascalPrecht** [comment]
@zoechi just to clarify, this is a native custom element functionality and works even without Polymer :)

@jelbourn I like that idea very much. But as @gkalpak mentioned it feels a bit like `replace` in Angular 1 (which is deprecated now), although it's not exactly the same thing, as we'd keep a host element instead of simply replacing everything. This should be documented.

In addition, how would that affect styling? E.g. as soon as we know we want to render a component with a different host element, would we also have to adjust all of our stylings, or would Angular take care of rewriting them (similar to emulated view encapsulation)?

This prolly won't work as nicely with no view encapsulation..

**Comment by jelbourn** [comment]
@PascalPrecht that is a very good point, I had not thought of the styling problem. 

Which seems preferable to you: having to use an attribute selector (on a native element) or using a custom element but potentially not having element selectors work on it?

**Comment by tbragaf** [comment]
Must have! :+1:

**Comment by astec** [comment]
@jelbourn what is the problem with this:
```html
<button md-button (click)="doStuff()"> GO! </button>
```
Looks better to me then
```html
<md-button (click)="doStuff()"> GO! </button>
```
Can you give an example to show advantage of having a custom element rather then extending native with a directive?

**Comment by tbragaf** [comment]
@astec 
Imagine the button has more HTML inside, like icons, texto etc

**Comment by astec** [comment]
@tbragaf If I understand it correctly there is no much difference in implementing inner icon using directive vs custom element.

**Comment by tbragaf** [comment]
@astec 
That was not the best example, but i need my buttons to have an i element tag for icons and a span element for text

**Comment by jelbourn** [comment]
@astec  It's simply that `<md-button>` is more concise than `<button md-button>`.

**Comment by astec** [comment]
@jelbourn it sounds nicer in English but introduces a set of challenges (_with CSS for example_).

How about:
```html
<md-button (click)>
<!-- vs -->
<button md (click)>
```
I still can imagine there are cases where custom elements rendered with different tag can make sense.

**Comment by e-oz** [comment]
All is clear when `renderAs` has native element as target. What should happen if renderAs will get custom element selector (another component)? If Angular will be able to render it too - would be great. But then they should put content into the same node, what will not work, obviously.

**Comment by dchacke** [comment]
An actual `replace` functionality would still be needed in some cases, especially where CSS frameworks expect a certain tag structure. I'm aware that one could use attributes as selectors instead, but sometimes tags are semantically better.

**Comment by kemsky** [comment]
This is really very desired feature. It allows to create very neat markup.

**Comment by paprende** [comment]
+1

**Comment by paprende** [comment]
I would very much like this feature too. When trying to create components composed of table elements, they don't play well with div's being rendered within them.

**Comment by awerlang** [comment]
```html
<md-button (click)="doStuff()"> GO! </md-button>
```

To retain button properties, it could be replaced with

```html
<button md-button type="button" (click)="doStuff()"> GO! </button>
```

But what if user wants this button to be `type[submit]`. How that would work?

**Comment by ronnyek** [comment]
I think if this is doable, this is an absolute necessity for building reusable components where there is fairly intuitive markup... The closest I've come to achieving this is having to use attribute selectors for things I want to effectively "replace".  That doesn't lend itself very well to build intuitive components.

**Comment by ronnyek** [comment]
Any word on this one... this would be huge... as would some way to emulate `replace: true` from angularjs days.

**Comment by vthinkxie** [comment]
Hi @jelbourn 
any update on this issue?

**Comment by jelbourn** [comment]
This is almost certainly not happening; the original idea was over three years ago. Closing the issue.
