### ISSUE TITLE
DatePipe does not work as expected

### ISSUE THREAD

**Issue by tom10271** [angular/angular#6713]
For `timeline.datetime = new Date()` 

```
    {{ timeline.datetime | date: "y - MMM" }} 
```

It should output:
```
2016 - Jan
```

but 
```
Jan 2016
```

Update:
`{{ data.birthday | date:"MMM /dd /y" }}` becomes `{{ data.birthday | date:"MMM dd, y" }}`

It make developers cannot stylize date as they want like PHP. Must we use what Angular 2 provides?

**Comment by Alsmile** [comment]
+1

**Comment by tom10271** [comment]
Dup #7008, close now
