### ISSUE TITLE
Can't upgrade ng1 component that references $attrs in the controller function

### ISSUE THREAD

**Issue by KarlPurk** [angular/angular#6715]
Hi,

I am unable to upgrade and use an ng1 component in an ng2 component if the ng1 component references $attrs in it's controller function signature.  

Here's a plunker that demonstrates the issue:
https://plnkr.co/edit/pfVsOcQcjLM6x9JcQSNj?p=preview

If you run the above plunker you will receive the following error:

```
Error: [$injector:unpr] Unknown provider: $attrsProvider <- $attrs
```

In the above plunker, `index.html` declares the ng1 component:

``` js
    var ng1 = angular.module('ng1Test', []);
    ng1.directive('ng1', function() {
      return {
        template: '<h1>Test</h1>',

        // Remove $attrs from below to fix error
        controller: function($attrs) { }
      }
    });
```

If you remove the references to `$attrs` from this ng1 directive, like so:

``` js
    var ng1 = angular.module('ng1Test', []);
    ng1.directive('ng1', function() {
      return {
        template: '<h1>Test</h1>',
        controller: function() { }
      }
    });
```

the plunker will run without errors and the ng1 component is upgraded successfully.

**Comment by Wildhoney** [comment]
[`$attrs` isn't a provider](https://docs.angularjs.org/api/ng/provider) in Angular 1 (nor Angular 2) &mdash; the error is nudging you to that conclusion.

Assuming you're after the directive attributes, you can use `scope` if you don't mind creating an isolated scope directive, where you can cherrypick certain attributes (read-only &mdash; use `=` otherwise):

```javascript
scope: { myAttribute: '@' }
```

Alternatively both the `compile` and `link` functions contain an object of **all** the element's attributes:

```javascript
compile(element, attrs) {}
// ...
link(scope, element, attrs) {}
```

Deciding on which one to use depends on whether you want access to the `attrs` before or after the directive has an associated DOM element.

Where is the Angular 2? As I'm a little confused how that's relevant &mdash; it seems as though this is purely an Angular 1 issue.

**Comment by KarlPurk** [comment]
Hey @Wildhoney

The ng1 component I'm attempting to upgrade is a third-party component and so I can't change the syntax.

This third party component references $attr as demonstrated in the plunker example.  Here's the particular LOC from the component I've tried to upgrade:
https://github.com/mbenford/ngTagsInput/blob/master/src/tags-input.js#L172

> Where is the Angular 2?

Admittedly I'm relatively new to Angular 1 & 2 so please let me know if I'm incorrect.  However, as this issue is related to an existing third-party Angular 1 component (which we've used internally in existing Angular 1 projects), and definitely works in Angular 1, I assume this is an issue with the Angular 2 upgrade adapter.  

I've also managed to get this particular component working by wrapping it in a proxy Angular 1 component, but I don't like that solution/hack.  I'd much rather use the Angular 1 component directly in the Angular 2 component.

Cheers!

**Comment by NickClark** [comment]
Running into this same issue. I've created a plunkr showing the issue: https://plnkr.co/edit/2Zg4vY You'll notice that the component works outside of the Angular 2 portion of the app, while inside the Angular 2 portion, it fails to inject $attrs. Is this intended behavior?

**Comment by tedp** [comment]
I'm having the same issue.  Did anyone find a solution for this?

**Comment by poupougnac** [comment]
Stuck on this also here ! Component related dependencies injection of Ng1.5 are not supported ($transclude, $element, $attrs)...

**Comment by gkalpak** [comment]
There are indeed certain things that can be injected into a directive's controller that do not come from providers, but are specific to the controller instance (they are referred to as `locals`). Off the top of my head, they are `$attrs`, `$element`, `$scope` and `$transclude`. 

From the above, `$element` and `$scope` should work (with the latest version). `$attrs` and `$transclude` do not work and cannot be supported by ngUpgrade. 

##
So, components that rely on these features are not directly "upgreable". You can always wrap components in an extra container and upgrade that (you just need some extra work to pass values between the container and the actual component).

I understand this is inconvenient if you want to upgrade such components (especially if they come from 3rd-party libraries), but there are technical limitations ofr the things ngUpgrade can do. Things like `$attrs` and `$transclude` are closly tied to the internals of AngularJS' compiler, so it is not easy for ngUpgrade to access or emulate.
