### ISSUE TITLE
[Testing] TestComponentBuilder uses real provider instead of mocked

### ISSUE THREAD

**Issue by wkwiatek** [angular/angular#6716]
I have following service:
```js
export class UserService {
  public users: Array<string> = ['John'];
}
```
and the component: 
```js
@Component({
  selector: 'list',
  template: '<span *ngFor="#user of users">{{user}}</span>',
  directives: [NgFor],
  providers: [UserService]
})
export class ListComponent {
  private users: Array<string> = [];

  constructor(userService: UserService) {
    console.debug(userService.users);
    this.users = userService.users;
  }
}
```

Now I wanted to make a test and mock the `UserService`. So I did: 
```js
class MockUserService {
  public users: Array<string> = ['John', 'Steve'];
}

describe('ListComponent', () => {

  beforeEachProviders(() => [
    provide(UserService, {useClass: MockUserService})
  ]);

  it('should render list', inject([TestComponentBuilder], (tcb: TestComponentBuilder) => {
    tcb.createAsync(ListComponent).then(fixture => {
      const element: HTMLElement = fixture.nativeElement;
      fixture.detectChanges();
      expect(element.querySelectorAll('span').length).toBe(2);
    });
  }));

});
```

the problem is that `debug` says I have list with only one element. It means that injected service was the real one (not the mock). If I remove `providers` completely from the component then everything works fine and the injected service is the mocked one.

**Comment by brandonroberts** [comment]
@wkwiatek have you tried using the overrideProviders function in the TestComponentBuilder?

**Comment by wkwiatek** [comment]
@brandonroberts Thanks for your response! If I do:
```js
tcb
  .overrideProviders(ListComponent, [provide(UserService, {useClass: MockUserService})])
  .createAsync(ListComponent).then(fixture => { ...
```
then everything works as expected. 

But I guess that the same thing should be done automatically when using `beforeEachProviders`. Is such a behaviour by design?

Maybe I have missed some change but it worked. I double checked this example with @juliemr's `ng2-test-seed` (e.g. https://github.com/juliemr/ng2-test-seed/blob/master/src/test/greeting-component_test.ts).

**Comment by brandonroberts** [comment]
@wkwiatek her greeting component doesn't have the UserService in the providers array. The UserService is in the bootstrap, which is why beforeEachProviders works. If you add providers to the component, they look for their own instance instead of the one provided in the bootstrap, which is what beforeEachProviders is mimicking.

**Comment by wkwiatek** [comment]
If it's by design I'm OK with this. Thanks!

**Comment by oocx** [comment]
Please document this better. I wasted several hours to figure out that TestComponentBuilder.createAsync does not use the providers from my beforeEachProviders configuration.

**Comment by kinggolf** [comment]
@brandonroberts @wkwiatek Thanks for presenting and covering this. My unit tests are now working, but I am still unsure what all is going on. Here is a portion of my spec file:
```
describe('SPCOnlyComponent', () => {
    var cmp, builder, store;

    beforeEachProviders(() => [
        SPCAdminComponent, TestComponentBuilder, HTTP_PROVIDERS,
        provideStore(combineReducers({trn, admin_action, evts, sups, tcnt, icnt})),
        { provide: SignupsService, useClass: MockSignupsService }
    ]);

    beforeEach(async( inject([SPCAdminComponent, TestComponentBuilder, Store], (_cmp, _tcb, _store) => {
        cmp = _cmp;
        builder = _tcb;
        store = _store;
    })));

    it('should have as title \'Spanish Points Cup Admin\'', () => {
        expect(cmp.title).toEqual('Spanish Points Cup Admin');
    });

    it('should have 3 buttons', async( () => {
        builder
            .overrideProviders(SPCAdminComponent, { provide: SignupsService, useClass: MockSignupsService })
            .createAsync(SPCAdminComponent).then((fixture: ComponentFixture<SPCAdminComponent>) => {
                let element = fixture.debugElement.nativeElement;
                fixture.detectChanges();
                expect(element.querySelectorAll('button').length).toEqual(3);
        })
    }));
```
The test 'should have 3 buttons' requires overrideProviders since SignupsService is a provider to SPCAdminComponent and as such will disregard this info in beforeEachProviders. However, the test 'it should have as title ...' does not require overrideProviders since cmp instance is created in beforeEach and as such will access the beforeEachProviders. Is that correct? Thanks.
