### ISSUE TITLE
Angular1 directive with controllerAs cannot receive data from parent Angular2 component

### ISSUE THREAD

**Issue by szgabsz91** [angular/angular#6718]
Hi,

I've created a little [JSFiddle](https://jsfiddle.net/szgabsz91/a98q58o0/) example to demonstrate the problem I'm hitting.

The first directive uses `bindToController` and `controllerAs`, and it does not receive the `name` attribute. However, when I remove these 2 properties from the DDO, the received attribute value is displayed properly.

From what I've read about Angular2 and the upgrade process, this should work. Also, I tried to use AngularJS 1.5 instead of AngularJS 1.4 and migrate to the `module.component(...)` syntax, but I couldn't solve the issue.

Is this a bug?

(Sorry for using vanilla ES5, but I want to test the upgrade process with my existing codebase before migrating to Typescript.)

Thanks in advance!

**Comment by KarlPurk** [comment]
Hi @szgabsz91,

Looks like you're syntax was a little incorrect, check out this fiddle: https://jsfiddle.net/unchL8d7/

Cheers,
Karl

**Comment by szgabsz91** [comment]
AFAIK this is the older syntax, isn't it?

    {
        scope: {
            name: '='
        },
        controller: function() {},
        bindToController: true,
        controllerAs: 'vm'
    }

The new one would be this, and it works fine outside of an Angular 2 component:

    {
        scope: {},
        bindToController: {
            name: '='
        },
        controller: function() {},
        controllerAs: 'vm'
    }

Or this is a restriction of upgrade? It would be odd since this latter syntax is encouraged, or the new `module.component(...)` syntax. In my opinion they should be upgradable without a problem, and I haven't read anything about the opposite. Although I might be wrong. :)

**Comment by KarlPurk** [comment]
@szgabsz91 you are right - Angular introduced that syntax in 1.4.  The syntax I referred to was 1.3.  Looks like this is a bug with the upgrade adapter.

**Comment by szgabsz91** [comment]
Yes, and the `component` syntax from version 1.5 didn't work for me either.

So I hope that this one will be fixed until stable 2.0 lands. I'm kind of new to the 2.0 codebase, so I don't think I'll be able to produce a PR, but who knows. Until then I hope this bug will be picked up by someone who's more experienced with Angular2 than me.

Thanks for the help!

**Comment by szgabsz91** [comment]
I retested it after #4784 was closed and both the `bindToController` and `module.component(...)` syntax work fine with beta-3. Thanks!
