### ISSUE TITLE
Two-way data binding doesn't work on Select field in Angular2.0.0-beta.1

### ISSUE THREAD

**Issue by kbugala** [angular/angular#6721]
This works in Beta.0 but doesn't work in Beta.1

```<select [(ngModel)]="name"> <option *ngFor="#n of names" [value]="n">{{n}}</option> </select> {{name}}```

the current workaround in beta-1:

template.html:

```<select class="form-control" #t (change)="update(t.value)"> <option *ngFor="#type of types" [value]="type">{{type}}</option> </select>```

in component.ts
```
update(value){
    console.log(value);
    this.name=value;
  }```

**Comment by eostrom** [comment]
Duplicate of #6573, which should probably have "select" added to its title.

**Comment by kara** [comment]
Yeah, this looks like a dupe of #6573, so closing!  Feel free to track in the other issue :)
