### ISSUE TITLE
Router doesn't update link

### ISSUE THREAD

**Issue by tandu** [angular/angular#6722]
I have slider that updates browser location using router
`gallery.ts`
```typeScript
changeItem(item: IItem) {
  this.router.navigate(['../Gallery', { id: item.accessionNumber }]);
}

routerCanReuse() {
  return true;
}

routerOnReuse(next: ComponentInstruction) {
  this.galleryService.select(next.params['id']);
}
```
`gallery.html`
```html
<slider></slider>
<infoButton [routerLink]="['Details']"></infoButton>
```
`infoButton` should show selected image details on click. When I check `infoButton` in browser inspector its `href` doesn't change on browser location change. I.e. it is set only once on component init and doesn't reflect location changes. I tried to play with `ChangeDetectionStrategy` `reattach`, `markForCheck` to manually force href recalculation but with no success.

**Comment by tandu** [comment]
I use this to solve the issue:
```html
<infoButton [routerLink]="['../Gallery', {id: gs.active?.accessionNumber}, 'Details']"></infoButton>
```

**Comment by vicb** [comment]
obsolete - former router
