### ISSUE TITLE
[Bug][V2] Currency pipe :symbolDisplay true not working

### ISSUE THREAD

**Issue by luchillo17** [angular/angular#6724]
I'm using the currency pipe with beta.0, and with the following code inside ionic 2:

> ```
> <ion-card-content>
>   Total: {{ total | currency:'COP':true }}
> </ion-card-content>
> ```

The output should be `Total: $ 110,000` but the actual output is this:
![image](https://cloud.githubusercontent.com/assets/9698639/12625787/455a9142-c503-11e5-998d-42d18793691f.png)

**Comment by golear91** [comment]
having a similar issue with PLR currency code.  Seems like the pipe works for some currencies (the most used ones) and not for others.
checkout my plunker here:
http://plnkr.co/edit/m3Kwtxv2i5hy0DUBM6dX?p=preview

**Comment by Luchillo** [comment]
@golear91 I had the same issue, but since i opt in for a config from the server that tells the app if want to show a `$` prefix i sorted this out with just the numeric pipe, a div with `$` on it along an `*ngIf` directive.

**Comment by golear91** [comment]
@Luchillo Yes, but my problem is that my application deals with 100s of different currencies so I can't use a single symbol ($).  It appears as though this may be a typescript issue though, because Angular2 depends on the intl module from typescript
https://github.com/angular/angular/blob/master/modules/%40angular/facade/src/intl.ts

**Comment by golear91** [comment]
Guess this is not typescript or angular, but a browser (ECMAScript?) issue
    
    Intl.NumberFormat("en-US",{
      style:'currency',
      minimumIntegerDigits:1,
      currency: 'PLN',
      currencyDisplay: 'symbol'
    }).format(43);

Displays "PLN43" while

    Intl.NumberFormat("en-US",{
      style:'currency',
      minimumIntegerDigits:1,
      currency: 'PLN',
      currencyDisplay: 'name'
    }).format(43);
Displays "43.00 Polish zlotys"

**Comment by Luchillo** [comment]
@golear91 There are a few issues related to this one, for example in ios mobile browser it doesn't work at all and break the app, i had to resort to intl pollyfil, maybe that could solve this issue, though i can't test that.

**Comment by DzmitryShylovich** [comment]
@Luchillo can u add a repro?

**Comment by Luchillo** [comment]
I'll have to do it monday in office, maybe it can be repro in safari.

**Comment by Luchillo** [comment]
@DzmitryShylovich I've testing a bit, i have a plunkr where it shows how the `currency pipe` pipe shows for both `USD` and `COP` and the same `symbolDisplay` parameter set to true, and both show different, however the COP one doesn't show the `$` symbol:

http://plnkr.co/edit/hH9IZJ71l9oSNAvHmN6E?p=preview

**Comment by pkozlowski-opensource** [comment]
The root cause here is the `Intl` API not having info about all the currency codes. This is somehow "fine" as I understand that there might be some missing info here and there. What is bad though is that there is no way of overriding / specifying missing symbols / overrides for symbols.

IMO it is worth checking with the Intl API authors if there is enough interest in adding currency symbols override mechanism.

**Comment by Luchillo** [comment]
@pkozlowski-opensource I suspected it had to do with the internationalization api, however is that symbols override mechanism the only way to fix this?

**Comment by pkozlowski-opensource** [comment]
> however is that symbols override mechanism the only way to fix this?

Of course not. The "proper" way of fixing this would be to have each browser vendor and polyfill author ... fix their implementation. The other option would be to drop Intl API altogether (not sure if this would do any good though, as we would simply exchange one set of bugs for another).

**Comment by Luchillo** [comment]
Aaand those browser vendors aren't going to provide those overrides, so i guess asking the `Intl` guys is probably faster and better.

**Comment by ahelord** [comment]
Hi, guys 
this issue have solution in this moment?

**Comment by PyroSA** [comment]
Interestingly Intl seems affected by your active region.

```Intl.NumberFormat('en-us', { style: 'currency', currency: 'ZAR' }).format(12.345)
"ZAR12.35"```

```Intl.NumberFormat('en-za', { style: 'currency', currency: 'ZAR' }).format(12.345)
"R12,35"```

**Comment by akana** [comment]
Same issue with KHR currency code.
https://plnkr.co/edit/ADw9qR1GFNr8rsi7vswg?p=preview

**Comment by hugosolar** [comment]
This link helped me
http://stackoverflow.com/questions/34904683/how-to-set-locale-in-datepipe-in-angular2

**Comment by Mcs-developer** [comment]
Hello, any solution ? :(

**Comment by ScarUgo** [comment]
A quick workaround for unsupported currencies is: 
- Use the [decimal pipe](https://angular.io/docs/ts/latest/api/common/index/DecimalPipe-pipe.html) to format the number
- Search for the html code for the currency (https://www.toptal.com/designers/htmlarrows/currency/) and place beside the formatted number

**Comment by ocombe** [comment]
Hello, a new option to display either the code/symbol/narrow symbol will be added with the PR to replace the intl API for angular v5 (see [#10809](https://github.com/angular/angular/issues/10809 "[Disscussion] Internationalization API issues.")).
Some countries have multiple money symbols (usually the local symbol is shorter, when the official international symbol is longer and more explicit)
ex: the canadian dollar has `CA$` by default, but the new narrow symbol will be `$`.
In the case of @luchillo17 COP example, the official symbol for COP is indeed `COP`, but the narrow symbol will be `$`.
This should cover all use cases.

**Comment by luchillo17** [comment]
@ocombe Great, that means we now only have to be aware of when transactions are made between different currencies to show the long syntax, right?

Glad solutions are coming, shame nor vendors nor Intl could help on this.

**Comment by priyankadavle** [comment]
> I'm using the currency pipe with beta.0, and with the following code inside ionic 2:
> 
> > ```
> > <ion-card-content>
> >   Total: {{ total | currency:'COP':true }}
> > </ion-card-content>
> > ```
> 
> The output should be `Total: $ 110,000` but the actual output is this:
> ![image](https://cloud.githubusercontent.com/assets/9698639/12625787/455a9142-c503-11e5-998d-42d18793691f.png)

Please Use <p>{{ 1234.56 | currency:'COP':'symbol-narrow':'.2-2'}}</p>
