### ISSUE TITLE
UrlResolver.resolve("http://localhost:8000/Bus" , 11)    return   "http://localhost:8000/11"

### ISSUE THREAD

**Issue by mashaly100200** [angular/angular#6728]
hi 

i faced this bug 
UrlResolver.resolve("http://localhost:8000/Bus" , 11)  

  return   "http://localhost:8000/11"

i solve this but by put /   after base url  , like this

UrlResolver.resolve("http://localhost:8000/Bus/" , 11)  
thin it's ok
"http://localhost:8000/Bus/11"

also if   UrlResolver.resolve("http://localhost:8000/Bus" , "")
it gives me error

**Comment by pkozlowski-opensource** [comment]
`UrlResolver` is not part of the public API any more. Feel free to open a new issue following the issue template and a minimal reproduce scenario if you still hitting problems.

**Comment by rsambathkumar** [comment]
If UrlResolver is no more part of public API, how can we do something like below with latest version.

https://github.com/angular/angular/blob/f7ff6c5a129f56723a8ef564de2b1e166d264554/modules/%40angular/examples/compiler/ts/url_resolver/url_resolver.ts
