### ISSUE TITLE
self closing components? <cmp />

### ISSUE THREAD

**Issue by gdi2290** [angular/angular#673]
Will there be self closing components this time around? `<custom-element />`

**Comment by caitp** [comment]
probably not, that's an HTML parsing issue. we aren't able to fix the way the browser parses html ._.

**Comment by gdi2290** [comment]
lol if you self close your top level app component then it will assume everything belows it belongs in the light dom

**Comment by b-laporte** [comment]
Well, #503 should fix this problem as HTML parsing would be moved to JavaScript (and probably through webworkers)

**Comment by mhevery** [comment]
Closing as this would make our templates not compatible with HTML. As @caitp this is per HTML spec, and it is how the browser parsers work :-(, and we use browser parser.

**Comment by gdi2290** [comment]
if we could allowed the shorthand during template compilation and output the long version I would be happy. For example we gain more expressive powers for small components such as <icon type="phone" /> or <custom-input />. These small components won't need access to the light dom so there is no reason to for them to use `<content />` (another example of a simple cmp). Then the only thing you really have to teach to new users is to not use the shorthand for the index page which is something users should probably do anyways for `()[]#`. You have to teach new users to how to set up systemjs, zone.js and traceur for the index page anyways as well as bootstrapping etc.

**Comment by mhevery** [comment]
Once the browser parses the DOM we can't tell if the element was self closed. The information is lost. What you are asking for is not possible, unless we have our own HTML5 parser and break the HTML spec, which I don't think is a good idea.

**Comment by jamm** [comment]
@gdi2290 
maybe you ask just for this:
http://plnkr.co/edit/8AdhwpWBOILkty6zkq7H?p=preview
I see the button in Chrome, FF, Safari.
Or I'm missing something? Sorry if so :)

**Comment by gdi2290** [comment]
I'm asking for that and it totally works. The problem was that it probably doesn't work in IE etc (keep in mind developing for Chrome is like developing with an instagram filter). I have a lot of constructive feedback about the opinion here that I can add to the convo (I'll submit them after work so I can focus on work stuff lolz)

I was suggesting something like the example below using pseudo ng2 code
```javascript
@Component({ selector: 'md-input' })
@Template({ inline: '<input />' })
class MaterialInput extends FacadeHTMLInputElement {
  constructor() {
    super();
  }
}
```
Rather than using  `<md-input [ng-model]="swag.swag"></md-input>` you can use a similar api just like `<input [ng-model]="swag.swag" />` with `<md-input [ng-model]="swag.swag"/>`. Since you're extending the native element you still end up missing out on one of it's attributes (self closing)

**Comment by mhevery** [comment]
@jamm your planker example works becouse of the HTML parsing rules. The `</>` is meaningless. Try parsing this and then inspect in DOM browser.

```
<custom-element />
<div>I should be custom-element sibling, but I am its child. :-(</div>
```

**Comment by jamm** [comment]
@mhevery thanks, see now. Looks like "standardized bug".

@gdi2290 I think for your purposes will be much more easy to use attribute (decorator instead of component).

**Comment by gdi2290** [comment]
@mhevery can we revisit this?

**Comment by mhevery** [comment]
@gdi2290 what new information do you have which would make this possible. 

Per HTML spec there is no such thing as a self closing element. The `/>` is ignored.

There are self closing tags such as; `<br>` and they are equivalent to `<br/>` because HTML spec says to ignore `/>`. 

So if we would implement this we would create different set of rules from HTML.

**Comment by gdi2290** [comment]
@mhevery the HTML rules were already broken after camelCase (HTML normalizes the attributes and you can use [any string for an event in polymer](https://twitter.com/addyosmani/status/634303767182200832) `<custom-polymer-cmp ($@56eVe_λλnt##)="onClick($event)></custom-polymer-cmp>`). The HTML spec also allows setting an attribute without quotes so something like this should/does work `<home [data]=data></home>` but if you want to pass a RxJS stream and conform to the conventions by appending `$` then `<home [data$]=data></home>` breaks without quotes. The Angular 2 HTML parser is also stricter than HTML (that already benefits everyone) but it's not to spec because the HTML spec is lenient by design. HTML was meant for people who aren't developers allowing more people to build websites in the early days of the internet. 

(there was a push for semantic web with HTML5 that introduced `<main> <nav> <section>`).

The Angular 2 HTML parser is already introducing more rules just as XHTML did in the past. Developers still use `/>` because it's leftover from back when people were pushing for XHTML (which was meant to save the world from writing poor markdown). I believe the HTML spec only matters for the output of the renderer rather than the template. 

If a developer cares so much about the spec, they're free to use the alternative syntax just as they would with `data-` or the other alternative syntaxes `on-click` and `bind-yolo`.

**Comment by fxck** [comment]
Also. I would like to be able to use `<div [class.💩]="foo"></div>` as it's perfectly valid html(https://mathiasbynens.be/demo/crazy-class) but angular won't let me. :(

**Comment by zoechi** [comment]
@fxck that's a different issue. Why don't you create a new bug report / feature request?

**Comment by pkozlowski-opensource** [comment]
> @fxck that's a different issue. Why don't you create a new bug report / feature request?

No need to create new issues, we've got one already: #517

**Comment by diogobernardelli** [comment]
React and Vue works perfectly with self closing components, so that's not so impossible as you guys are saying. 

Write something like <my-comp atr="atr" /> is easier then <my-comp atr="atr"></my-comp>, isn't?

But ok  ¯\_(ツ)_/¯

**Comment by zoechi** [comment]
@diogobernardelli nobody said it's impossible. It's just that the intention was to only parse valid HTML5

**Comment by benneq** [comment]
I don't get this argument. Angular already uses asterisks, brackets and other stuff in their templates. This isn't valid HTML5 as well. So why not support self closing tags?
Angular templates are not HTML, it's angular template language.

**Comment by trotyl** [comment]
@benneq

> Angular already uses asterisks, brackets and other stuff in their templates. 

All of these are valid HTML syntax didn't affect parsing, would become no-op semantically just like any other unknown attributes.

> Angular templates are not HTML, it's angular template language.

It's a template language based on HTML syntax, and extends existing HTML semantics.

> So why not support self closing tags?

There's no self-closing tag is HTML, and they're just treated as start tag, that's already well-defined behavior in HTML. So that:

```html
<my-comp />
42
```

Always results to:

```html
<my-comp>
42
</my-comp>
```
