### ISSUE TITLE
Http inject does not work on angular2.0.0.beta.1

### ISSUE THREAD

**Issue by gilAsier** [angular/angular#6730]
**I tried a lot of things and I didn't get any solution. All the time I am getting this console error:**

"Error: Cannot resolve all parameters for 'AppComponent'(?). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'AppComponent' is decorated with Injectable. at NoAnnotationError.BaseException \[as constructor\] (http://localhost:3000/jspm_packages/npm/angular2@2.0.0-beta.1/src/facade/exceptions.js:23:19) at new NoAnnotationError (http://localhost:3000/jspm_packages/npm/angular2@2.0.0-beta.1/src/core/di/exceptions.js:130:12) at _dependenciesFor (http://localhost:3000/jspm_packages/npm/angular2@2.0.0-beta.1/src/core/di/provider.js:299:11) at resolveFactory (http://localhost:3000/jspm_packages/npm/angular2@2.0.0-beta.1/src/core/di/provider.js:210:20) at Object.resolveProvider (http://localhost:3000/jspm_packages/npm/angular2@2.0.0-beta.1/src/core/di/provider.js:229:64) at Function.DirectiveProvider.createFromType (http://localhost:3000/jspm_packages/npm/angular2@2.0.0-beta.1/src/core/linker/element.js:104:25) at ResolvedMetadataCache.getResolvedDirectiveMetadata (http://localhost:3000/jspm_packages/npm/angular2@2.0.0-beta.1/src/core/linker/resolved_metadata_cache.js:35:44) at Function.AppProtoElement.create (http://localhost:3000/jspm_packages/npm/angular2@2.0.0-beta.1/src/core/linker/element.js:162:39) at eval (viewFactory_HostAppComponent:45:52) at Object.evalExpression (http://localhost:3000/jspm_packages/npm/angular2@2.0.0-beta.1/src/facade/lang.js:428:94)"

**My code looks like:**
```javascript
/********* boot.js ********* /
import 'reflect-metadata';
import {bootstrap} from 'angular2/platform/browser';

import './styles.css!';
import {AppComponent} from './app.component';

bootstrap(AppComponent);
/********* boot.js ********* /

/********* app.component.js ********* /
import {Component, View, Injectable} from 'angular2/core';
import {Http, HTTP_PROVIDERS} from 'angular2/http';

@Component({
  selector: 'my-app'
})
@View({
  templateUrl: "app/hello.html"
})
export class AppComponent {
  result: Object;

  constructor(http: Http){
    http.get('/test')
      // Call map on the response observable to get the parsed people object
      .map(res => res.json())
      // Subscribe to the observable to get the parsed people object and attach it to the
      // component
      .subscribe(res => this.result = res);
  }
}
/********* app.component.js ********* /
```

Thanks in advance, it's getting hard. :rage:

**Comment by ericmartinezr** [comment]
```
bootstrap(AppComponent);
```
You missed HTTP_PROVIDERS
```
bootstrap(AppComponent, [HTTP_PROVIDERS]);
```

**Comment by gilAsier** [comment]
Ty ericmartinezr.
I tried it too and I'm got the same result.

**Comment by ericmartinezr** [comment]
@gilAsier That should not be the case. Can you reproduce the issue in a plnkr, or create a repo?

**Comment by gilAsier** [comment]
I'm going to create a repo then, it's nice idea to see the error.

**Comment by gilAsier** [comment]
Here is the repo with the error -> https://github.com/gilAsier/angular2beta_errors

**Comment by ericmartinezr** [comment]
@gilAsier can't make it work, don't know if I'm missing something. Please consider moving your questions to Gitter's chatroom or stackoverflow, you'll get more help over there. Github is to report bugs and such.

**Comment by robwormald** [comment]
Appears you're using Babel, not TypeScript, which may not support the syntax you're using.

**Comment by gilAsier** [comment]
Thanks you guys for the help. I'm going to move the question to stackoverflow.

By the way @robwormald , my idea is to get a funtional angular2 proyect with jsmp and babel as a trasnpiler.

**Comment by cdcooksey** [comment]
@gilAsier Would you mind providing a link to your StackOverFlow question?
