### ISSUE TITLE
XHRConnection not populating statusText on response

### ISSUE THREAD

**Issue by rapropos** [angular/angular#6734]
XHRConnection's `onLoad` handler fills out a ResponseOptions object. It doesn't contain a statusText member. Because BaseResponseOptions has a statusText of 'Ok', this shines through on all responses, even if the actual XHR response has a different statusText.

**Comment by ericmartinezr** [comment]
There's a PR for this https://github.com/angular/angular/pull/4162

**Comment by rapropos** [comment]
Sorry, I tried searching issues but didn't find anything. Should I close this?

**Comment by ericmartinezr** [comment]
@rapropos I don't think, not yet, that PR looks old, let's see if it revives

**Comment by DavidWiesner** [comment]
:+1: what the state of this issue? Any News?

**Comment by vicb** [comment]
Should be fixed in 2.0.0
