### ISSUE TITLE
Response.totalBytes is always undefined

### ISSUE THREAD

**Issue by oliverjanik** [angular/angular#6735]
Looks like it's not implemented yet?

https://angular.io/docs/ts/latest/api/http/Response-class.html

**Comment by pkozlowski-opensource** [comment]
`totalBytes` is part of the Response class now, see: https://angular.io/docs/ts/latest/api/http/index/Response-class.html

Feel free to open a new issue with a specific use-cases and the reproduction scenario in plunker if you see this non-working in a specific scenario.

**Comment by jasonburrows** [comment]
I get this problem as well.  It never isn't undefined - no specific use case is required.  Angular 2.2.4

**Comment by oliverjanik** [comment]
@pkozlowski-opensource this was never fixed, was it? Please reopen.
