### ISSUE TITLE
Test with Router injected - Cannot resolve all parameters for 'Router'

### ISSUE THREAD

**Issue by alvipeo** [angular/angular#6739]
I have a component with the following constructor:

```
constructor(
    private _router: Router,
    private dispatcher: Observer<Action>,
    fb: FormBuilder
) { ... }
```
And if I run project everything works. But I need tests for it so here they are:

```
import {
it,
inject,
injectAsync,
beforeEachProviders,
TestComponentBuilder
} from "angular2/testing";

import {provide} from "angular2/core";
import {FormBuilder} from 'angular2/common';
import {Subject} from 'rxjs/Subject';
import {Router, RouteParams} from 'angular2/router';
// other imports ...

describe("SomeInfoEdit form", () => {

    const actions = new Subject<Action>(null);

    // provide our implementations or mocks to the dependency injector
    beforeEachProviders(() => {

        return [
            Router,
            FormBuilder,
            provide(dispatcher, { useValue: actions }),
            SomeInfoEdit
        ];
    });

    it('should have default data', inject([SomeInfoEdit], (component) => {
        expect(component.galtitle.value).toEqual("");
        expect(component.friendlyUrl.value).toEqual("");
        expect(component.isVisible.value).toBe(false);
    }));
...
```
This the test runs it gives me the error:

>Cannot resolve all parameters for 'Router'(?, ?, ?). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'Router' is decorated with Injectable.

I tried to put ROUTE_DIRECTIVES into beforeEachProviders but this doesn't help. Is there a bug or am I doing something wrong?

I appreciate some explanation.

**Comment by woppa684** [comment]
I think you need the ROUTER_PROVIDERS ...

**Comment by alvipeo** [comment]
Tried that, same thing.

**Comment by wkwiatek** [comment]
Try to inject this in `beforeEachProviders`: 
```js
provide(Location, {useClass: SpyLocation}),
provide(ROUTER_PRIMARY_COMPONENT, {useValue: App}),
provide(Router, {useClass: RootRouter})
```

**Comment by alvipeo** [comment]
I really don't get it. Is SpyLocation some kind of mock? Where is it defined?
Same with RootRouter...

**Comment by wkwiatek** [comment]
Sorry, I though yor IDE could import it for you:
```js
import { Location, RouteParams, Router, RouteRegistr, ROUTER_PRIMARY_COMPONENT } from 'angular2/router';
import { SpyLocation } from 'angular2/src/mock/location_mock';
import { App } from './app';
```

**Comment by alvipeo** [comment]
RouteRegistr - is there a typo? VS Code says no such thing.

And what's RootRouter?

**Comment by ericmartinezr** [comment]
You can follow official specs https://github.com/angular/angular/blob/master/modules/angular2/test/router/integration/navigation_spec.ts

**Comment by alvipeo** [comment]
Miracle! Thank you! Made it work!

**Comment by mshirishkumar** [comment]
Github link for navigation_spec is not working. Could you please share updated link?

**Comment by osadan** [comment]
I am also having issue with this subject . 
can not locate : Cannot find module "@angular/src/router/router"
in order to import RootRouter
(I am using rc4.0)

**Comment by kamran-pervaiz** [comment]
@alvipeo 
could you please write your solution here it will help all of us. the link @ericcarraway is not working

**Comment by alvipeo** [comment]
Guys, I'm not sure it's relevant because this was long time ago and angular 2 has changed a lot.

I'm personally waiting for RC.5 to refresh my project.

**Comment by TrevorBroderick1** [comment]
So... any idea how to get this working on RC5?

**Comment by programmist** [comment]
@TrevorBroderick1, This worked for me.

```javascript
class MockRouter {
  navigate = jasmine.createSpy("navigate");
}

...

TestBed.configureTestingModule({
  declarations: [MyComponent],
  providers: [
    {provide: Router, useClass: MockRouter}
  ]
});
```
You could use an instance with the provider key `useValue` if you wanted to access the Jasmine spies from your tests.

```javascript
const mockRouter = new MockRouter();

...

TestBed.configureTestingModule({
  declarations: [MyComponent],
  providers: [
    {provide: Router, useValue: mockRouter}
  ]
});
```

**Comment by TrevorBroderick1** [comment]
I'll give that a shot, thanks!

**Comment by tomgeorge** [comment]
@programmist your solution worked.  

How come you only have to create a spy for `navigate` in this instance?

**Comment by caggers** [comment]
@programmist It worked for me to, thanks!! Any idea where I could find more information to read up on about how and why?

**Comment by zhuanjiaozm** [comment]
@programmist It does not work for me . I get the error 'Error: Can't resolve all parameters for ActivatedRoute: (?, ?, ?, ?, ?, ?, ?, ?).'

**Comment by rameshrajendran214** [comment]
@zhuanjiaozm 

Try this 

 `const fakeActivatedRoute = {
        snapshot: { data: {} }
    }

{ provide: ActivatedRoute, useClass: fakeActivatedRoute },`

**Comment by lcortess** [comment]
@zhuanjiaozm 
You have to remove the ActivatedRoute from the providers in your `@Component` then you can provide a mock in your test without problems :)

**Comment by darkguy2008** [comment]
@lcortess that WAS the solution. THANK YOU!
