### ISSUE TITLE
RouteParams documentation

### ISSUE THREAD

**Issue by koriUA** [angular/angular#6742]
https://angular.io/docs/js/latest/api/router/RouteParams-class.html

Should import RouteParams class.

import {RouteParams} from 'angular2/router';

**Comment by evanplaice** [comment]
ROUTER_PROVIDERS includes RouteParams.

**Comment by koriUA** [comment]
very strange....
if I write
import {ROUTER_PROVIDERS} from 'angular2/router';
...
constructor(public http: Http, params: RouteParams) {....}
...

appears this exception:
EXCEPTION: Cannot resolve all parameters for User(Http, ?). Make sure they all have valid type or annotations.

**Comment by ericmartinezr** [comment]
You have to import RouteParams, even if it is included in ROUTER_PROVIDERS.

**Comment by krasevych** [comment]
@koriUA You should import and inject ROUTER_PROVIDERS 
like that:
```
import {ROUTER_PROVIDERS} from 'angular2/router';

bootstrap(AppComponent, [
  ROUTER_PROVIDERS
]);
```

then into your components you should import RouteParams 
like that:
```
import {RouteParams} from 'angular2/router';
```
BUT without any inject! only use into you constructor params:
```
import {RouteParams} from 'angular2/router';
@Component({
  selector: 'my-app'
})
export class AppComponent{
  constructor(routeParams: RouteParams) {}
}
```

**Comment by koriUA** [comment]
Yes. I got it. I just wrote that this line was missed in documentation
import {RouteParams} from 'angular2/router';

and code from documentation currently is not working

thank you for clarification

**Comment by krasevych** [comment]
Yes, it is really mistake.
