### ISSUE TITLE
doc - note about Internationalization API

### ISSUE THREAD

**Issue by ghost** [angular/angular#6744]
https://angular.io/docs/ts/latest/api/common/DecimalPipe-class.html says:

> WARNING: this pipe uses the Internationalization API. Therefore it is only reliable in Chrome and Opera browsers.

Which is simply untrue. Int API is fully supported on Firefox, Edge and IE11 as well.

Source: https://dev.windows.com/en-us/microsoft-edge/platform/status/ecmascriptinternationalizationapi.

**Comment by doubleddm** [comment]
+1

source: [http://caniuse.com/#search=internationalization](http://caniuse.com/#search=internationalization)

**Comment by pkozlowski-opensource** [comment]
Docs are correct now, https://angular.io/docs/ts/latest/api/common/index/DecimalPipe-pipe.html reads: 

> WARNING: this pipe uses the Internationalization API which is not yet available in all browsers and may require a polyfill. See Browser support for details.

Also  https://angular.io/docs/ts/latest/guide/browser-support.html has correct info on supported browsers and required polyfills.
