### ISSUE TITLE
DynamicComponentLoader and Lifecycle Hooks

### ISSUE THREAD

**Issue by BaruchFisherman** [angular/angular#6748]
Hi,
I want to implement DynamicComponentLoader approach in my Angular2 application.
I'm using loadIntoLocation function for this behavior.

My Application (root) component loads Header component Dynamically, and it's working good, but when my Header component created, the lifecycle of Header is not called.
All of them not called:
OnInit
OnDestroy
DoCheck
OnChanges
AfterContentInit
AfterContentChecked
AfterViewInit
AfterViewChecked

The only one - is the constructor called.

Because of this, in my child (Header) component i cannot dynamically creates elements with loadIntoLocation function.

Can you please explain regarding this limitation/bug?

**Comment by wendro** [comment]
+1 (having problems with missing life cycle events as well) - BETA-6

**Comment by otodockal** [comment]
prefix all the hooks with ng, so ngOnInit etc..

https://angular.io/docs/ts/latest/guide/cheatsheet.html

**Comment by mbalex99** [comment]
@otodockal I can confirm that loadAsRoot doesn't fire ngOnInit, even when properly implement. the other DynamicComponent methods work properly and fire ngOnInit

**Comment by wendro** [comment]
* I've prepared http://plnkr.co/edit/KjHF2n?p=preview (wanted to show my bizarre use case ;) ) As I distilled this case I'm seeing slightly different behaviour then in my app. Will work on it further. 
It worked only for loadNextToLocation (as expected). 
I'm suspecting not uniqueness upon #dynamic_internal or id="dynamic_internal"  when there are more then one DynamicContainerComponent can be a problem. Dunno if one should be doing multiple loadAsRoot (2 items written one after another).
I see constructors but I don't see hooks for elements which are in the DOM - maybe its because Im abusing API ;) but it does not behave as I would imagine from docs. Will try to boil another plunkr with simpler usage of the pure api for comparsion.
* I've distilled pure api usage from my sample http://plnkr.co/edit/PbN5uK?p=preview and I can see like @mbalex99 said only loadAsRoot is misbehaving - even if single time triggered.

**Comment by ericmartinezr** [comment]
loadAsRoot has issues https://github.com/angular/angular/issues/6223

**Comment by drew-moore** [comment]
+1 

In beta-7, I've got a component with lifecycle hooks (prefixed and implemented correctly) that are not firing when it's loaded using `loadIntoLocation` or `loadNextIntoLocation`

**Comment by ChrisProlls** [comment]
Same issue here in beta-7 as @drew-moore, any solution about that ?

**Comment by gdi2290** [comment]
when using `loadAsRoot` you need to trigger change detection and manually wire up Inputs and Outputs
```typescript
this.componentLoader.loadAsRoot(YourComponent, this.elementRef, this.injector)
.then((compRef: ComponentRef) => {
  // manually include Inputs
  compRef.instance['myInputValue'] = {res: 'randomDataFromParent'};
  // manually include Outputs
  compRef.instance['myOutputValue'].subscribe(this.parentObserver)
  // trigger change detection
  cmpRef.location.internalElement.parentView.changeDetector.ref.detectChanges()
  // always return in a promise
  return compRef
});
```

**Comment by lastmjs** [comment]
Does change detection work at all in the component that is loaded as root? I seem to be having problems getting [hidden] to detect changes automatically.

**Comment by komw** [comment]
This bug still exists in 2.0.0-beta.14 loadAsRoot doesn't fire ngOnInit etc

**Comment by ericmartinezr** [comment]
@komw https://github.com/angular/angular/issues/6223#issuecomment-193908465 we thought it had issues, it doesn't, that's its behavior by design. So you should be using loadNextToLocation instead.

**Comment by komw** [comment]
Hm, I know it, but when using a loadNextToLocation it is impossible to create a dynamic template and load to it a dynamic component.
It is impossible to use:
`<div *ngFor="#element of list" id="dynamic_{{element.getId()}}"></div>`
and next:

`list.forEach((element:SomeObject)=> {
        loader.loadAsRoot(element.toComponent(), "#dynamic_"+element.getId() ,injector);
});`

**Comment by zoechi** [comment]
You can use a wrapper component to create components with `*ngFor` http://stackoverflow.com/questions/36325212/angular-2-dynamic-tabs-with-user-click-chosen-components/36325468#36325468.

For further discussion about how to use futures please use one of the channelse mentioned in https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by joebrassi** [comment]
Still not working after 2.0.0-RC1. How is it possible that such an important feature is just broken? It simply does not work, seems like a plan to remove `loadAsRoot()` in next RC.

**Comment by pkozlowski-opensource** [comment]
Obsolete as DynamicComponentLoader is deprecated / gone.
