### ISSUE TITLE
Refactor WebWorker Bundle

### ISSUE THREAD

**Issue by jteplitz** [angular/angular#6750]
- [ ] Add bundle arithmetic to gulpfile (remove rx, router, core, common, http)
- [ ] Remove web_worker/worker.ts and web_worker/ui.ts
- [ ] Break WebWorker router code out into its own barrel
- [ ] Create a barrel for WebWorker messaging code #7419
- [ ] Add WebWorker bundle to table (https://github.com/angular/angular/blob/master/modules/angular2/docs/bundles/overview.md#systemjs-loader-users)
- [ ] Revise WebWorker imports to import from barrels

**Comment by pkozlowski-opensource** [comment]
@jteplitz602 here is a place in gulpfile where content of SystemJS bundles (which barrels go to which bundle) is configured: https://github.com/angular/angular/blob/fc5b128b43935b59599572873508113742d81531/gulpfile.js#L144-L160

This is also where you can see [bundle arithmetic](https://github.com/systemjs/builder#bundle-arithmetic) in action.

**Comment by mhevery** [comment]
closing as obsolete.
