### ISSUE TITLE
Angular 2 Router

### ISSUE THREAD

**Issue by lihongming** [angular/angular#6756]
Hi, I found all the examples about router in the internet is written in TypeScript. Where can I find a demo with Router functionality written in pure javascript aka ES5. 

PS:

Dose Angular2 encourage developers to use TypeScript to develop web applications?

**Comment by brandonroberts** [comment]
Its encouraged to use TypeScript, but there will be examples and documentation for ES5 also. Here is an ES5 example plunker: 

https://plnkr.co/edit/a0bftmaNTCCJDURLF5eG?p=preview

**Comment by vicb** [comment]
obsolete - former router
