### ISSUE TITLE
[beta.2] Error bundling using SystemJS Builder in Beta.2

### ISSUE THREAD

**Issue by antonybudianto** [angular/angular#6760]
Hi, I just updated my starter project to **angular2.0.0@beta.2** and when running in development, it was okay, but when I run production build and serve it, it showed error as follows:
<img width="1280" alt="screen shot 2016-01-09 at 6 46 17 am" src="https://cloud.githubusercontent.com/assets/7658554/12212459/3275147c-b69d-11e5-9540-f7123cbeb031.png">
**It's not happening in angular2.0.0@beta.0**

you can reproduce it by cloning my [repo](https://github.com/antonybudianto/angular2-starter) using `master` branch, then run `gulp serve-build`

and if you change [mangle](https://github.com/antonybudianto/angular2-starter/blob/master/tasks/build.js#L30) to false, it's working!

I'm using [SystemJS builder](https://github.com/systemjs/builder) for bundling, thanks!

**Comment by evanplaice** [comment]
Are you using any non-default loaders (ex plugin-css, plugin-text)?

**Comment by antonybudianto** [comment]
nope

**Comment by evanplaice** [comment]
I ran into that issue before. I fixed it by placing a `<script>` tag import for `zone.js` to load *before* `System.js`.

**Comment by antonybudianto** [comment]
you mean angular-polyfills before systemjs tag?

**Comment by evanplaice** [comment]
Nope. I've been using angular2 since before the polyfills were available as a single package but the result is the same.

I just tested it again by rebuilding my production bundle. Moving the import after System.js triggers 'EXCEPTION: RangeError: Maximum call stack size exceeded'.

![Maximum call stack size exceed proof](https://cloud.githubusercontent.com/assets/303159/12663890/8a8a0166-c5e0-11e5-93fe-ea2f9a1f4b5d.png)

You might be able to get away with loading the polyfills with a script tag before the tag that loads System.js.

**Comment by antonybudianto** [comment]
Actually I already put the polyfills before the systemjs tag, and the result is same

**Comment by evanplaice** [comment]
OK. What I've found to work is

- import zone.js in a script tag prior to system.js
- import system.js using a script tag
- import reflect-metadata + rxjs in the source

I think they removed rxjs from being imported by default in alpha.53. The lib is pretty heavyweight so if you need to create observables or use the extensions I suggest importing them piecemeal.

*Example:*
```javascript
import {Observable} from 'rxjs/Observable';
```

I haven't had to import anything else so AFAIK, System.js polyfills the rest.

**Comment by pkozlowski-opensource** [comment]
Sounds like @evanplaice has a solution here. As a reminder - please load all the polyfills through a script tag and don't package them.

**Comment by antonybudianto** [comment]
@evanplaice , I've tried your setup, but no luck. Can I take a look at your build setup somehow?
Thank you

**Comment by evanplaice** [comment]
@antonybudianto Sure.

Here's a starter I created https://github.com/evanplaice/angular2-es6-seed

And a site I'm using it https://github.com/evanplaice/evanplaice.com

**Comment by antonybudianto** [comment]
@evanplaice , turn out I must take out my navbar component to get it work, not sure why it works only in dev
