### ISSUE TITLE
angular1_router: What happened to multiple components on single route?

### ISSUE THREAD

**Issue by pranav-xx** [angular/angular#6762]
Hello,

I am very new to using the new router. I initially started playing with angular-new-router and then got to know that component-router is the new thing and has moved from angular/router to angular/angular.

Now I was expecting that I could still define multiple components on single route in route config. But that seems to give errors with this router.

The moment i try to do something like this:
 { path: '/', components: {"outlet1":"comp1", "outlet2":"comp2"} }
It throws error
Route config should contain exactly one "component", "loader", or "redirectTo" property

Looking very briefly at the code, it looks like I cannot define "components" under route. But not able to understand how to put multiple components on a single route

Can someone enlighten me on what has changed in terms of thought process. Is the concept of having multiple components per route still alive?

Thanks in advance.

**Comment by brandonroberts** [comment]
@pranav-xx what you want to use are auxiliary routes, which lets you load multiple routes(components) at once. They aren't supported in the angular 1 router yet.

**Comment by pranav-xx** [comment]
Thanks Brandon Roberts for your quick response.

I need to decide the router I should go with for a new project that is just starting. Do you recommend going with angular-new-router @ angular/router or with angular/modules/angular1_router/

In case we are going with angular 1 router which does not have support for auxiliary routes, should we use only one component per route and the embed multiple components in the template? Please suggest.

regards

**Comment by brandonroberts** [comment]
You should go with angular/modules/angular1_router. If you need multiple components then yes, I would suggest using the route as a container and embedding multiple components in the template.

**Comment by pranav-xx** [comment]
Sure. Thanks.
