### ISSUE TITLE
Angular date filter in IE

### ISSUE THREAD

**Issue by shavo007** [angular/angular#6764]
Hi,

I have an issue with date filter and timezone in IE 11.

I created a plunker. 
http://plnkr.co/FzVbYl

The filter is not formatting the date-time based on the timezone.

Example, if you change your system time and run the plunker, the time is the local time of browser. Which is incorrect.

This works btw in chrome, safari and firefox.

**Comment by ericmartinezr** [comment]
@shavo007 this repo is for angular2. You're looking for this one https://github.com/angular/angular.js . You could try asking in their chatroom (https://gitter.im/angular/angular.js) before opening an issue.

**Comment by shavo007** [comment]
thanks for that. will do
