### ISSUE TITLE
object is there, can be seen in |json pipe or  access its property though "?.", but not property directly though "."

### ISSUE THREAD

**Issue by RyanLiu99** [angular/angular#6765]
I build a very simple project and try to show information on the page. 

{{selectedCarManfacturer?.name}} will print out name on screen.

{{selectedCarManfacturer.name}} will give
ORIGINAL EXCEPTION: TypeError: Cannot read property 'name' of undefined

**Comment by gkalpak** [comment]
The object is obviously not there initially. The `?.` operator will not throw if the object on it's left is undefined and it will try to access the `name` property when `selectedCarManfacturer` is available. The `json` pipe will also not break when undefined is passed to it and it will re-evaluate as soon as `selectedCarManfacturer` is available.

**Comment by gdi2290** [comment]
`selectedCarManfacturer` might be being set asynchronously which is why it works with `?.`

**Comment by pkozlowski-opensource** [comment]
Closing as this is a support question and @gkalpak and @gdi2290 suggestions are excellent, given the amount of context we've got here.

If you still believe that there is a bug in the framework, please re-open following submission guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submission-guidelines
