### ISSUE TITLE
angular.io site - Request to have the Angular2 subreddit added to the Support page (angular.io/support.html)

### ISSUE THREAD

**Issue by aQutie** [angular/angular#6766]
There is a forum on reddit that is specifically targeted at Angular 2 that now has 1,430+ subscribers. In reddit parlance it is the [/r/Angular2](https://www.reddit.com/r/Angular2/) subreddit.

This subreddit is two months shy of being 1 year old and has steadily attracted a larger following. The forum's growth stats can be seen [here](https://www.reddit.com/r/Angular2/about/traffic/).

The forum is dedicated to helping Angular 2 enthusiasts learn the ropes, participate in discussions, share resource links and announce updates.

With 1,430+ current subscribers together with the accelerating subscriber growth rate, it would be great if the forum could be listed with the other Support websites listed on [this page](https://angular.io/support.html).

/r/Angular2 is a great resource for disseminating information to enthusiasts and is worthy of consideration for inclusion on the Support page.

**Comment by splintercode** [comment]
You can open this issue or submit a pull request under the angular.io repo here https://github.com/angular/angular.io

**Comment by aQutie** [comment]
Thank you, splintercode. Pull request submitted.
