### ISSUE TITLE
Using global import not possible to compile a typescript project

### ISSUE THREAD

**Issue by khomyakov42** [angular/angular#6772]
```
...
typings/browser/definitions/angular2/angular2.d.ts(6725,28): error TS2307: Cannot find module 'angular2/src/core/pipes/pipes'.
typings/browser/definitions/angular2/angular2.d.ts(6727,23): error TS2307: Cannot find module 'angular2/src/core/pipes/pipes'.
typings/browser/definitions/angular2/angular2.d.ts(7056,27): error TS2307: Cannot find module 'angular2/src/facade/collection'.
...
```

Example core.d.ts file has wrong import
```typescript
...
export { enableProdMode } from 'angular2/src/facade/lang';
...
```
if replace its to
```typescript
...
export { enableProdMode } from './src/facade/lang';
...
```
compilation finished with success.

**Comment by pkozlowski-opensource** [comment]
It depends on your TypeScript configuration - if you use `"moduleResolution": "node"` TS will try to resolve non-relative imports from node_modules projects.

Check the official tutorial for a correct setup: https://github.com/johnpapa/angular2-tour-of-heroes

You can also check one of the number starter kits / boilerplate projects.

Closing, as this is config issue not something we can "fix" on the framework side.

**Comment by khomyakov42** [comment]
This is a problem of the framework. Do not use absolute imports itself, unless it is a circular dependency.It turns out that "angular 2" depends on itself. Proof
proof/tsconfig.json
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "sourceMap": true,
    "moduleResolution": "node"
  }
}
```
proof/package.json
```json
{
  "name": "angular2-example",
  "version": "0.0.0"
}

```
proof/module.ts
```typescript
export function hello() {
  console.log('Hello');
}
```

proof/index.ts
```typescript
import * as m from 'proof/module';

m.hello();
```

```
$cd proof
$tsc -p ./
index.ts(1,20): error TS2307: Cannot find module 'proof/module'.
```

if you create symlink from "proof" to "proof/node_modules/proof" then compilation successful. But it is a circular dependency
