### ISSUE TITLE
Maximum call size exceeded when nesting components with the same class name (beta.2)

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#6774]
This worked fine in beta.0 but has caused issues with beta.2. If you have 2 components exporting the same class name and one component is including the other as a directive, a `Maximum call size exceeded` error occurs with unexpected results. If I rename one of the class names, it works as expected.

http://plnkr.co/edit/UlIlkGxxfMDYCbX1Z1Nh

**Comment by antonybudianto** [comment]
same issue here

**Comment by kylecordes** [comment]
I have seen an issue that results in the same error, upon doing a "production" build of a Angular 2 application with WebPack. By setting the minifier to not rename things, it went away. I'm not sure, but I suspect maybe the two classes were getting the same name at some point during minification - I don't think it warrants another separate issue yet (there being 1000 of them open right now), I'm hoping to see that problem go away when this one gets fixed.

**Comment by bennadel** [comment]
I think I happened across the same problem, but with different symptoms: https://github.com/angular/angular/issues/7117

**Comment by antonybudianto** [comment]
i have posted the same [issue](https://github.com/angular/angular/issues/6760), they said it had to do with how we put angular2-polyfills (it should not be bundled, but using script tag), but I used script tag and even didn't work until I disable `mangle` option

**Comment by kylecordes** [comment]
That is correct, you need to disable mangling (I suspect because it can make the classes (underlying constructor functions) have the same name, until this problem is fixed.

**Comment by cristi-badila** [comment]
I stumbled into a similar issue while running an app in production mode even without having components with the same name. When mangling names, the outputed javascript results in angular generating a recursive `viewFactory` that will eventually throw a `Maximum call stack size exceeded` exception. I isolated the issue in a repository [here](https://github.com/cristi-badila/angular-mangle-issue/tree/master) which contains both the working non mangled js and the mangled js which results in angular throwing exceptions. Hope this helps.

**Comment by Springrbua** [comment]
I am having this issue with an angular2 project i am currently working on.
I use the google closure compiler to minify the js-Files, which results in all components getting the same name ("A").
Therefore all the components share the same "viewFactory_*" and "viewFactory_*Component" (in this case "viewFactory_A" and "viewFactory_AComponent") files, which in my case, results in a "x is not a function" error (where x is a function in one component, but not in the other).
I solved it by setting the Compilation Level to "WHITESPACE_ONLY", which does not touch function names.
But ofc this should only be a temporary fix...
