### ISSUE TITLE
@Input() / component directives strangeness

### ISSUE THREAD

**Issue by CaptainCodeman** [angular/angular#6775]
This is a bit tricky to explain so please bear with me.

I have a `CurrencyDisplayComponent` that has an `@Input() price:Price`. Where Price is:

```
export interface Price {
  currency:string;
  amount:number;
}
```

When displaying the prices for an order it worked fine for items within an `*ngFor` using:
```<currency-display [price]="item.price"></currency-display```

But the taxes and total amounts just didn't display. They got their price from a function instead:
```<currency-display [price]="total()"></currency-display```

This function just returns a Price, e.g.:

```
price():Price {
  return {
    currency: 'USD',
    amount: 999
  };
}
```

Checking the constructor, OnInit and OnChanges methods in the `CurrencyDisplayComponent` showed nothing being created at all, it's like there was nothing on the page.

I then had a familiar ah-ha moment "oh dear, I forgot to add the component to the directives collection (yet again)". But now I am puzzled as to how was it was working and displaying for the items - was it picking up the component from some parent or other part of the tree? (there is a cart display that uses it) Why did it work for some parts of the view but not for others? (in the same component).

If I don't add directives for a component but some parent component has a directive that matches some selector then it seems like there is a real danger that it will be picked up and applied when not expected and not wanted and possibly applied inconsistently.

So the bug (if it's a bug) was an unreferenced component directive was being included when it really shouldn't have been.

**Comment by pkozlowski-opensource** [comment]
@CaptainCodeman it is super-hard to say anything without a minimal reproduce scenario in a plunker. I don't even know which version of ng2 you were using... 

I'm going to close this one as it is not actionable as-is. Happy to re-open if / when you got a minimal plunker.

**Comment by CaptainCodeman** [comment]
@pkozlowski-opensource it is also super hard to reproduce something that only shows up in part of a larger app. A component was being included and rendered in a view even though it wasn't in the list of directives so a bug with whatever beta version was out in late Jan but was fixed in a later release and I think discussed in chat at the time.
