### ISSUE TITLE
ngOnInit should never be called twice, even if an error happens

### ISSUE THREAD

**Issue by tbosch** [angular/angular#6782]
Right now, if an error happens during detecting changes of content/view children of a component, `ngOnInit` will be called twice (seen in `DynamicChangeDetector`). 
This can lead to follow up errors that hide the original error.

/cc @matanlurey

**Comment by dylanbaxter** [comment]
+1!

**Comment by alamgird** [comment]
If no one has this yet i can take this on.

**Comment by innoproject** [comment]
I get the same issue. I tried to pass in the object from one component to another using @Input decorator, and using the parameter i build another object in the passed component in ngOninit lifecycle method. In the first iteration i was able to get the value but in the second iteration (which shouldn't happen) reinitialized the values back to null.

**Comment by tbosch** [comment]
@innoproject Could you create a plunker?

**Comment by ihrimech** [comment]
I'm trying to use leaflet library an add a map to a component. It seems like the ngOnInit is called twice which is causing an issue to the map instantiation. Is there any workaround to this issue ?

**Comment by vicb** [comment]
@ihrimech Try to reproduce in a Plunker. Thanks (& include version info in your comments)

**Comment by ihrimech** [comment]
Can't reproduce it anymore. I've put it in a try-catch block meanwhile so I could go forward with the app development and now It seems to be working fine without. I'll keep it like this and make a plunker when the problem gets back. 
Angular version 2.0.0

**Comment by DILEEPKUMAREBIX** [comment]
Hi,
I am also facing this problem. ngOninit() calling twice of my component so @input property assigned with null.
First time i am getting actual value, but 2nd time in ngOninit()  @input property assigned with null.

Please look into this.

**Comment by DILEEPKUMAREBIX** [comment]
@tbosch  so what is work around for this issue to skip second time call?
Thanks in advance.

**Comment by prabhatsharma** [comment]
Still reproducible with 2.0.2

**Comment by francosioquim** [comment]
I get the same issue. I tried to pass in the object from one component to  
another using @Input decorator, and using the parameter i build another  
object in the passed component in ngOninit lifecycle method. In the first  
iteration i was able to get the value but in the second iteration (which  
shouldn't happen) reinitialized the values back to null.

**Comment by tbosch** [comment]
@francosioquim @prabhatsharma @DILEEPKUMAREBIX We really need a plunker that shows it. Otherwise it is super hard to reproduce your problem...

**Comment by agalazis** [comment]
@francosioquim  for me inputs were undefined not null (on the retriggered  onInit)

**Comment by amardeep157** [comment]
Hi,

Well the Problem in my case was the way I was bootstrapping the Child Components.
In my  @NgModule decorator’s  metadata object ,I was  passing  ‘child component’ in the bootstap property along with ‘parent component’.
Passing the child components in bootstap property  was resetting my child components properties and making OnInit() fired twice.


@NgModule({
  imports:      [ BrowserModule,FormsModule ],     // to use two-way data binding ‘FormsModule’
  declarations: [ parentComponent,Child1,Child2],       //all components   
  //bootstrap:  [parentComponent,Child1,Child2]    // will lead to errors in binding Inputs in Child  components  
  bootstrap:  [parentComponent]             //use  parent components only   
})

**Comment by Abuleilei** [comment]
Thanks @amardeep157 ! Solved my problem.

**Comment by p0rsche** [comment]
Still reproducible in 4.0.0, but due the nature of our project (relatively big) it's very hard to find where the error happens.

**Comment by prabhatsharma** [comment]
In my case I was using template driven forms. Switched to model driven
forms and issue disappeared.

**Comment by p0rsche** [comment]
The problem is that we cannot gran the original error. If someone could give a good advice how to catch the original error it would be great.

**Comment by razvanmitre** [comment]
We are also experiencing the problem. It is like routerLinkActive reinitializes the component.

**Comment by tbosch** [comment]
This still happens in production mode, tracking here: https://github.com/angular/angular/issues/15925

**Comment by jjlorenzo** [comment]
@razvanmitre I face the same issue with `routerLinkActive`, for know I remove this because I don't have time to properly debug the problem

**Comment by jamilalisgandarov** [comment]
I have deleted routerLinkActive, but still happens

**Comment by RajendrasinhParmar** [comment]
Any updates on this issue?
I'm also having the same issue in my project.

**Comment by onemantooo** [comment]
still have same trouble

**Comment by eivindvea** [comment]
Same trouble here

**Comment by ravindra-clairvoyant** [comment]
I am also facing the same issue, the constructor is getting called twice. I have created a thread [here](https://stackoverflow.com/questions/54632686/component-constructor-is-getting-called-twice-with-angular-elements). does anyone have any workaround for this?

**Comment by JNaeemGitonga** [comment]
This still happens

**Comment by JNaeemGitonga** [comment]
I am noticing this when my app sits Idle for ~10min in dev & prod.I can see (through logging) where it has been ran again, and again, and again.

**Comment by angelayanpan** [comment]
https://embed.plnkr.co/W3UHwl/

my best attempt to re-create. the error in console is ExpressionChangedAfterItHasBeenCheckedError for the plunkr

But in my app, I can see OnInit and constructor fires twice inside the app-selector. 

The main objective of the app is, when user Nav from 1 screen to another. We save the selectedId from another screen, and prepopulate the dropdown for the user. 

But selector is being initialized twice for some reason.

**Comment by adornala** [comment]
I was facing the same issue a while ago. Looks like, Angular 'nativeNode' is not destroyed properly, I was using the same selector name for creating customElements and component selector. During app startup 'ERROR TypeError: Cannot read property 'nativeNode' of null' shows up in the console, from what I understand angular tries 2nd time if it fails the 1st time, when angular tries the 2nd time it looks like it resolves the error. 

**Try differentiating selector names between @Component({selector: ''}) and createCustomElement(). If you are creating custom elements, it should help. That's the fix I had for now, at least it worked for me.**

**Comment by aashkashah** [comment]
2019 and still same issue. Constructor and NgOnInit called twice

**Comment by dalvarezsmiet** [comment]
Yep, still happens, ngOnInit and constructor fired twice just a per website is starting. Very disappointing, as it seems not possible to avoid it

**Comment by DILEEPKUMAREBIX** [comment]
You can avoid such thing by enabling PROD mode

**Comment by dalvarezsmiet** [comment]
No way, production mode is already enabled in my project,  and the ngOnInit is being fired twice, always. I've read about some binding errors or HTML non-closed tags that may cause this behavior, but I've checked it, and it's not the case... It's really weird
