### ISSUE TITLE
TypeError: null is not an object (evaluating 'utils_1.browserDetection.isSlow')

### ISSUE THREAD

**Issue by blacksonic** [angular/angular#6789]
Im getting the above error after upgrading to beta2 and testing my application. Im using the built Javascript files, not Typescript.
I think the problem comes from the following line in JS:
```
exports.browserDetection = null;
```
In beta1 it is
```
exports.browserDetection = new BrowserDetection(null);
```
I see no instantiation in Typescript, only the decalaration of the class ```BrowserDetection```.
```
export declare var browserDetection: BrowserDetection;
```
But it didnt change between beta1 and beta2.

**Comment by justindujardin** [comment]
This is related to the breaking changes mentioned in the Beta2 changelog.  You need to modify the bootstrap script for your tests.  Mine looked like this:

```javascript
System.import('angular2/src/platform/browser/browser_adapter')
  .then(function (browser_adapter) {
    browser_adapter.BrowserDomAdapter.makeCurrent();
  })
```

Now it looks like:

```javascript
Promise.all([
    System.import('angular2/testing'),
    System.import('angular2/platform/testing/browser')
  ])
  .then(function (modules) {
    var testing = modules[0];
    var browser = modules[1];
    testing.setBaseTestProviders(browser.TEST_BROWSER_PLATFORM_PROVIDERS, browser.TEST_BROWSER_APPLICATION_PROVIDERS);
  })
```

**Comment by blacksonic** [comment]
I modified my bootstrap script and got it after that.

**Comment by blacksonic** [comment]
The error comes from ```testing_internal```, where it is called at the start of the file:
```var globalTimeOut = utils_1.browserDetection.isSlow ? 3000 : jasmine.DEFAULT_TIMEOUT_INTERVAL;```

**Comment by blacksonic** [comment]
It occures as early as i import 

    import {it} from 'angular2/testing_internal'

**Comment by blacksonic** [comment]
Maybe this method call is missing

    static setup() { browserDetection = new BrowserDetection(null); }

**Comment by justindujardin** [comment]
@blacksonic If you follow the code, `BrowserDetection.setup()` is called by the fix I suggested above. It was in the changelog notes and is the recommended way of doing this.

If it isn't working for you, maybe you need to run the code earlier in your test process? I run it [before loading or executing](https://github.com/justindujardin/ng2-material/blob/2d11bb9cf63e35a3907bcef4ca1ac74defd818bf/karma.main.js) any tests.

**Comment by blacksonic** [comment]
The very first line in my tests:

    import {setBaseTestProviders} from 'angular2/testing';
    import {TEST_BROWSER_PLATFORM_PROVIDERS, TEST_BROWSER_APPLICATION_PROVIDERS} from 'angular2/platform/testing/browser';
    setBaseTestProviders(TEST_BROWSER_PLATFORM_PROVIDERS,TEST_BROWSER_APPLICATION_PROVIDERS);

What fails after this is importing the internals:

    import {
      afterEach,
      beforeEach,
      beforeEachProviders,
      describe,
      expect,
      inject,
      it
    } from 'angular2/testing_internal';

**Comment by justindujardin** [comment]
I have no other ideas.  Good luck getting your issue resolved.

**Comment by blacksonic** [comment]
It only sets the providers...but it is only a provider and not getting executed.

**Comment by ericmartinezr** [comment]
You're not supposed to use testing_internal. Importing all those from testing should be fine. I've seen that error when mixing dispatchEvent with injectAsync and others.

**Comment by blacksonic** [comment]
Yep that is right...finally figured it out myself also :)
The working solution is:

    import {BrowserDomAdapter} from 'angular2/src/platform/browser/browser_adapter';
    import {TEST_BROWSER_PLATFORM_PROVIDERS, TEST_BROWSER_APPLICATION_PROVIDERS} from 'angular2/platform/testing/browser';
    import {setBaseTestProviders} from 'angular2/testing';
    setBaseTestProviders(TEST_BROWSER_PLATFORM_PROVIDERS,TEST_BROWSER_APPLICATION_PROVIDERS);
    
    BrowserDomAdapter.makeCurrent();
    
    import {
      afterEach,
      beforeEach,
      beforeEachProviders,
      describe,
      expect,
      inject,
      injectAsync,
      it
    } from 'angular2/testing';

**Comment by zoechi** [comment]
I think `DOM` should be used instead of `BrowserDomAdapter` and `BrowserDomAdapter.makeCurrent()` should be called and `DOM` be initialized with a `DomAdapter`  by Angular instead. 
In Dart this works but in TS it currently doesn't seem to. See also https://github.com/angular/angular/issues/6904

**Comment by ericmartinezr** [comment]
@blacksonic since setBaseTestProviders you don't need anymore Browser...makeCurrent()

**Comment by mharris7190** [comment]
This still isn't working for me. I tried putting in those three imports and calling `setBaseTestProviders`, but I'm getting `Uncaught Invalid provider - only instances of Provider and Type are allowed, got: [object Object]`

Did anyone else have this issue?
