### ISSUE TITLE
EmulatedShadowDomStrategy error when a component is around another binding

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#679]
When using `EmulatedShadowDomStrategy`, the following works, where MdButton is a `@Component`
```html
<!-- whatever static html -->
<md-button>Go!</md-button>
<!-- whatever static html -->
```

However, if the component is followed or preceded by, seemingly, any other binding, an error is thrown in light_dom.js:

```html
<!-- whatever static html -->
<md-button (click)="increment()">Go!</md-button>
{{goCount}}
<!-- whatever static html -->
```
or
```html
<!-- whatever static html -->
<md-radio-group></md-radio-group>
<h3>Some header</h3>
<button type="button" (click)="demoClick()">Demo click</button>
<!-- whatever static html -->
```
or
```html
<!-- whatever static html -->
<div>
  <button type="button" (click)="demoClick()">Demo click</button>
</div>
<md-radio-group></md-radio-group>
<h3>Some header</h3>
<!-- whatever static html -->
```
The error is `TypeError: Cannot read property 'forElement' of null`. It's pretty easy to see where the error is occurring, but tracing back the route cause will be much faster for someone more familiar with the shadow DOM emulation.

**Comment by jelbourn** [comment]
Here's my branch with the error occuring: `https://github.com/jelbourn/angular/tree/binding-error`

To see it in action, run:
```
npm install gulp-sass
npm install gulp-autoprefixer
gulp build.material
gulp serve.js.dev
```
And then hit
`http://localhost:8000/angular2/src/material/components/button/demo/`

**Comment by vicb** [comment]
@vsavkin does 29f5ee0c293e8af4f4e8daf31ac7fb02e4783ec3 fix this ?

**Comment by vsavkin** [comment]
I believe so.

**Comment by jelbourn** [comment]
@vsavkin @vicb I can confirm that this seems to be fixed now.
