### ISSUE TITLE
Simple typo in docs

### ISSUE THREAD

**Issue by daprezjer** [angular/angular#6790]
First "it's" should be "its".

https://angular.io/docs/ts/latest/tutorial/toh-pt4.html

**Comment by ericmartinezr** [comment]
@daprezjer the repo for the website is here https://github.com/angular/angular.io :+1:

**Comment by daprezjer** [comment]
Thanks @ericmartinezr , however, for this simple change I didn't want to go through the process of the CLA, which requires giving out personal information.  So just passing along the info.

**Comment by robwormald** [comment]
@daprezjer @ericmartinezr's point is that issue with the docs should be reported in the appropriate repo in the future. thanks for the reports.

**Comment by daprezjer** [comment]
Ah right thanks @robwormald
