### ISSUE TITLE
Does asyncRouter only support Typescript?

### ISSUE THREAD

**Issue by PrimeObjects** [angular/angular#6791]
I got "Component is not defined" error when using ES5 js in the code below (the js content was transformed from typescript).

{path: "/pages", loader: () => System.import("/platform/page/js/web/c/ori/POKM.Pages/web.js").then(m => m.POKMPages), name: "POKMPages"}

Thanks
Gary

**Comment by Mischi** [comment]
Hi,

Besides the API docs i've only read about AsyncRoutes in [this](http://blog.mgechev.com/2015/09/30/lazy-loading-components-routes-services-router-angular-2/) blog entry from @mgechev so far and it seems you have to wrap your Route definition in a AsyncRoute?

According to this blog entry, it would look like this in TypeScript...
```ts
new AsyncRoute({path: "/pages", loader: () => System.import("/platform/page/js/web/c/ori/POKM.Pages/web.js"})
```

**Comment by PrimeObjects** [comment]
Hi Mischi, 

Thank you for help.

I made it work without need of new AsyncRoute().

The problem was that my JS files was a ES5 version (that was transformed from Typescript). ES5 JavaScript seems not work with AsyncRoute. So I have to change System.configure to make System.import to load typescript and use typescript file instead of ES5 file in RouteConfig, it works after change.

Step 1:
System.config({
        transpiler: "typescript",
        typescriptOptions: { emitDecoratorMetadata: true },
        packages: { "app": { defaultExtension: "ts" } }
    });
    System.import("/platform/js/ori/POKM.Default.Boot/include.ts").then(null, console.error.bind(console));

Step 2:
@RouteConfig([
	{path: "/pages", loader: () => System.import("/platform/page/js/web/c/ori/POKM.Pages/web.ts").then(m => m.POKMPagesComponent), name: "POKMPages"}
])


Thanks
Gary
