### ISSUE TITLE
Grunt-typescript and angular imports can't compile

### ISSUE THREAD

**Issue by Saint48198** [angular/angular#6793]
I get the following when trying to compile typescript using angular beta.2. This was working with beta.0.

>> Running "typescript:base" (typescript) task
>> node_modules/angular2/src/core/change_detection/parser/locals.d.ts(3,14): error TS2304: Cannot find name 'Map'.
>> node_modules/angular2/src/core/change_detection/parser/locals.d.ts(4,42): error TS2304: Cannot find name 'Map'.
>> node_modules/angular2/src/core/di/provider.d.ts(436,103): error TS2304: Cannot find name 'Map'.
>> node_modules/angular2/src/core/di/provider.d.ts(436,135): error TS2304: Cannot find name 'Map'.
>> node_modules/angular2/src/core/zone/ng_zone.d.ts(2,37): error TS2304: Cannot find name 'Zone'.
>> node_modules/angular2/src/facade/collection.d.ts(1,25): error TS2304: Cannot find name 'MapConstructor'.
>> node_modules/angular2/src/facade/collection.d.ts(2,25): error TS2304: Cannot find name 'SetConstructor'.
>> node_modules/angular2/src/facade/collection.d.ts(4,27): error TS2304: Cannot find name 'Map'.
>> node_modules/angular2/src/facade/collection.d.ts(4,39): error TS2304: Cannot find name 'Map'.
>> node_modules/angular2/src/facade/collection.d.ts(7,9): error TS2304: Cannot find name 'Map'.
>> node_modules/angular2/src/facade/collection.d.ts(8,30): error TS2304: Cannot find name 'Map'.
>> node_modules/angular2/src/facade/collection.d.ts(11,43): error TS2304: Cannot find name 'Map'.
>> node_modules/angular2/src/facade/collection.d.ts(12,27): error TS2304: Cannot find name 'Map'.
>> node_modules/angular2/src/facade/collection.d.ts(14,23): error TS2304: Cannot find name 'Map'.
>> node_modules/angular2/src/facade/collection.d.ts(15,25): error TS2304: Cannot find name 'Map'.
>> node_modules/angular2/src/facade/collection.d.ts(94,41): error TS2304: Cannot find name 'Set'.
>> node_modules/angular2/src/facade/collection.d.ts(95,22): error TS2304: Cannot find name 'Set'.
>> node_modules/angular2/src/facade/collection.d.ts(96,25): error TS2304: Cannot find name 'Set'.
>> node_modules/angular2/src/facade/lang.d.ts(2,22): error TS2304: Cannot find name 'BrowserNodeGlobal'.
>> node_modules/angular2/src/facade/lang.d.ts(48,59): error TS2304: Cannot find name 'Map'.
>> node_modules/angular2/src/facade/promise.d.ts(1,10): error TS2304: Cannot find name 'Promise'.
>> node_modules/angular2/src/facade/promise.d.ts(3,14): error TS2304: Cannot find name 'Promise'.
>> node_modules/angular2/src/facade/promise.d.ts(8,32): error TS2304: Cannot find name 'Promise'.
>> node_modules/angular2/src/facade/promise.d.ts(9,38): error TS2304: Cannot find name 'Promise'.
>> node_modules/angular2/src/facade/promise.d.ts(10,35): error TS2304: Cannot find name 'Promise'.
>> node_modules/angular2/src/facade/promise.d.ts(10,93): error TS2304: Cannot find name 'Promise'.
>> node_modules/angular2/src/facade/promise.d.ts(11,34): error TS2304: Cannot find name 'Promise'.
>> node_modules/angular2/src/facade/promise.d.ts(12,32): error TS2304: Cannot find name 'Promise'.
>> node_modules/angular2/src/facade/promise.d.ts(12,149): error TS2304: Cannot find name 'Promise'.
>> node_modules/angular2/src/facade/promise.d.ts(13,43): error TS2304: Cannot find name 'Promise'.
>> node_modules/angular2/src/http/headers.d.ts(43,59): error TS2304: Cannot find name 'Map'.
>> node_modules/angular2/src/http/url_search_params.d.ts(11,16): error TS2304: Cannot find name 'Map'.
>> node_modules/angular2/src/platform/browser/browser_adapter.d.ts(75,33): error TS2304: Cannot find name 'Map'.
>> node_modules/angular2/src/platform/dom/dom_adapter.d.ts(85,42): error TS2304: Cannot find name 'Map'.
>> node_modules/rxjs/CoreOperators.d.ts(22,67): error TS2304: Cannot find name 'Promise'.
>> node_modules/rxjs/CoreOperators.d.ts(72,67): error TS2304: Cannot find name 'Promise'.
>> node_modules/rxjs/CoreOperators.d.ts(77,31): error TS2304: Cannot find name 'PromiseConstructor'.
>> node_modules/rxjs/CoreOperators.d.ts(77,54): error TS2304: Cannot find name 'Promise'.
>> node_modules/rxjs/Observable.d.ts(87,67): error TS2304: Cannot find name 'PromiseConstructor'.
>> node_modules/rxjs/Observable.d.ts(87,88): error TS2304: Cannot find name 'Promise'.
>> node_modules/rxjs/Observable.d.ts(126,66): error TS2304: Cannot find name 'Promise'.
>> node_modules/rxjs/Observable.d.ts(180,66): error TS2304: Cannot find name 'Promise'.
>> node_modules/rxjs/Observable.d.ts(185,31): error TS2304: Cannot find name 'PromiseConstructor'.
>> node_modules/rxjs/Observable.d.ts(185,54): error TS2304: Cannot find name 'Promise'.
>> node_modules/rxjs/observable/forkJoin.d.ts(6,50): error TS2304: Cannot find name 'Promise'.
>> node_modules/rxjs/observable/forkJoin.d.ts(7,58): error TS2304: Cannot find name 'Promise'.
>> node_modules/rxjs/observable/from.d.ts(7,38): error TS2304: Cannot find name 'Promise'.
>> node_modules/rxjs/observable/from.d.ts(7,51): error TS2304: Cannot find name 'Iterator'.
>> node_modules/rxjs/observable/fromPromise.d.ts(9,31): error TS2304: Cannot find name 'Promise'.
>> node_modules/rxjs/observable/fromPromise.d.ts(10,26): error TS2304: Cannot find name 'Promise'.
>> node_modules/zone.js/lib/browser/zone-microtask.ts(4,29): error TS2307: Cannot find module 'es6-promise'.
>> node_modules/zone.js/lib/browser/zone-microtask.ts(13,3): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/browser/zone-microtask.ts(14,3): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/browser/zone-microtask.ts(14,21): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/browser/zone-microtask.ts(17,3): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/core.ts(105,19): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/core.ts(108,5): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/core.ts(122,7): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/microtask.ts(7,31): error TS2304: Cannot find name 'Promise'.
>> node_modules/zone.js/lib/microtask.ts(8,5): error TS2304: Cannot find name 'Promise'.
>> node_modules/zone.js/lib/microtask.ts(10,17): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/microtask.ts(11,5): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/microtask.ts(20,21): error TS2304: Cannot find name 'Promise'.
>> node_modules/zone.js/lib/microtask.ts(23,18): error TS2304: Cannot find name 'require'.
>> node_modules/zone.js/lib/microtask.ts(34,3): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/patch/browser.ts(13,33): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/patch/browser.ts(13,41): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/patch/browser.ts(22,25): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/patch/event-target.ts(7,13): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/patch/event-target.ts(8,41): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/patch/event-target.ts(36,19): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/patch/event-target.ts(36,34): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/patch/functions.ts(17,16): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/patch/functions.ts(17,43): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/patch/functions.ts(20,16): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/patch/functions.ts(20,45): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/patch/functions.ts(96,5): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/patch/functions.ts(101,14): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/patch/geolocation.ts(4,7): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/patch/geolocation.ts(4,27): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/patch/geolocation.ts(5,26): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/patch/mutation-observer.ts(9,23): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/patch/mutation-observer.ts(12,3): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/patch/mutation-observer.ts(13,51): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/patch/mutation-observer.ts(15,29): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/patch/mutation-observer.ts(20,3): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/patch/mutation-observer.ts(29,3): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/patch/mutation-observer.ts(40,18): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/patch/mutation-observer.ts(44,9): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/patch/mutation-observer.ts(48,31): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/patch/mutation-observer.ts(51,49): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/patch/promise.ts(24,5): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/patch/promise.ts(30,38): error TS2304: Cannot find name 'Promise'.
>> node_modules/zone.js/lib/patch/promise.ts(35,18): error TS2304: Cannot find name 'Promise'.
>> node_modules/zone.js/lib/patch/promise.ts(50,13): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/patch/promise.ts(91,7): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/patch/promise.ts(92,26): error TS2304: Cannot find name 'Promise'.
>> node_modules/zone.js/lib/patch/promise.ts(110,1): error TS2304: Cannot find name 'module'.
>> node_modules/zone.js/lib/patch/property-descriptor.ts(65,19): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/patch/register-element.ts(5,59): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/patch/register-element.ts(23,32): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/patch/register-element.ts(26,40): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/patch/register-element.ts(29,38): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/patch/websocket.ts(5,18): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/patch/websocket.ts(8,14): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/patch/websocket.ts(11,9): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/utils.ts(6,17): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/utils.ts(106,76): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/utils.ts(113,26): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/utils.ts(114,12): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/utils.ts(125,7): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/utils.ts(131,26): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/utils.ts(132,18): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/utils.ts(141,23): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/utils.ts(144,3): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/utils.ts(162,9): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/utils.ts(166,31): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/utils.ts(169,49): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/utils.ts(184,7): error TS2304: Cannot find name 'global'.
>> node_modules/zone.js/lib/wtf.ts(5,13): error TS2304: Cannot find name 'global'.
>> public/ts/common/easy-fetch.ts(13,14): error TS2304: Cannot find name 'Promise'.
>> public/ts/common/easy-fetch.ts(15,14): error TS2304: Cannot find name 'Promise'.
>> public/ts/common/easy-fetch.ts(25,23): error TS2304: Cannot find name 'Promise'.
>> public/ts/region/region.component.ts(20,12): error TS2304: Cannot find name 'Promise'.
>> public/ts/vendor.ts(7,22): error TS2304: Cannot find name 'process'.
>> public/ts/vendor.ts(9,3): error TS2304: Cannot find name 'require'.
>> public/ts/vendor.ts(11,3): error TS2304: Cannot find name 'Zone'.
>> public/ts/vendor.ts(11,32): error TS2304: Cannot find name 'require'.
>> public/ts/vendor.ts(14,22): error TS2304: Cannot find name 'process'.
>> public/ts/vendor.ts(17,16): error TS2304: Cannot find name 'require'.

**Comment by Saint48198** [comment]
Not an issue with Angular so to speak. The import file relative path was not to the liking of the Typescript compiler. simplified the relative path and it is all good.

**Comment by kisdaniel** [comment]
I have a same problem, if I set "target" to "es5".
If I set target to es6, only two compile errors are shown: 

>> node_modules/angular2/src/core/zone/ng_zone.d.ts(2,37): error TS2304: Cannot find name 'Zone'.
>> node_modules/angular2/src/facade/lang.d.ts(2,22): error TS2304: Cannot find name 'BrowserNodeGlobal'.

**Comment by Coaden** [comment]
I was going along fine, and checked out the project on a new machine, which caused all my node_modules to update (I have all modules in packages set with the ^ to get the latest version).  One all the modules installed I started getting the same problems (tons of compile errors).  

Changing target to "es6" solved the issue for me, but I'd like to compile to es5 for compatibility once I get read to publish.
