### ISSUE TITLE
Compilation error with TypeScript 1.8.0

### ISSUE THREAD

**Issue by juergenzimmermann** [angular/angular#6795]
I just upgraded from TypeScript 1.7.5 to 1.8.0. Now I'm getting this compilation error when I invoke tsc:
`.../node_modules/angular2/src/facade/promise.d.ts(1,10): error TS2661:
Cannot re-export name that is not defined in the module.`

**Comment by ericmartinezr** [comment]
dup of https://github.com/angular/angular/issues/6468

**Comment by alexeagle** [comment]
thanks @ericmartinezr

**Comment by born2net** [comment]
+1

**Comment by radek-anuszewski** [comment]
+1

**Comment by hzitoun** [comment]
got the same error

**Comment by alexeagle** [comment]
TS 1.8 requires angular2 beta.7 or higher.
