### ISSUE TITLE
Dynamically added DOM nodes don't get destroyed when the component gets destroyed

### ISSUE THREAD

**Issue by juristr** [angular/angular#6797]
_(hard to give a title to this issue)_

The main thing is this: DOM elements created dynamically from within a directive seem to be preserved even when the route changes and the directive and its parent component (seem to) get destroyed (the `ngOnDestroy` is being called).

Here's a plunkr that documents the "issue":
https://plnkr.co/edit/gXnXp07hchJuFjVkSvzA?p=preview

The `hello.directive.ts` adds new DOM nodes, a `<p>` in it's constructor. When I change the route, the directive and it's parent component get destroyed and removed from the HTML. But when I jump back to the 1st route, the `<p>` that has been added previously seems to be already there.

![cachingissue](https://cloud.githubusercontent.com/assets/542458/12703169/cae240ee-c83c-11e5-85b9-88ac7235f368.gif)

Seems like a template caching issue. When I remove the added DOM elements in the `ngOnDestroy` event, everything works as expected (and it's definitely best practice to clean up).  
But still, I think this is quite counter-intuitive, as when the components get destroyed I assume everything is cleaned up. Also because the next time the route gets active, all of the component's lifecycle events (constructor, onInit etc...) are being invoked again.

**Comment by ericmartinezr** [comment]
That was fixed in beta.1. It works fine with beta.2 https://plnkr.co/edit/e7hXy7R98VWQ0QCOpd2I?p=preview (using non minified bundles)

**Comment by juristr** [comment]
@ericmartinezr Awesome thx! I'll test it on my local setup and close the issue accordingly.
