### ISSUE TITLE
Elvis Operator fail with object that Arrary?

### ISSUE THREAD

**Issue by FreakDroid** [angular/angular#6798]
Hi, I was creating an example that recive a json from public Api, the json's structure is:

```
{
    "success": {
        "total": 1
    },
    "contents": {
        "quotes": [
            {
                "quote": "Never waste your time trying to explain who you are to people who are committed to misunderstanding you.",
                "length": "104",
                "author": "Dream Hampton",
                "tags": [
                    "inspire",
                    "misunderstanding",
                    "tso-life",
                    "tso-management",
                    "wasting-time"
                ],
                "category": "inspire",
                "date": "2016-01-31",
                "title": "Inspiring Quote of the day",
                "background": "https://theysaidso.com/img/bgs/man_on_the_mountain.jpg",
                "id": "OVmnzpHewxSTCw3AXDgnpweF"
            }
        ]
    }
}
```

But in my template when I try to use elvis operator It fails. I got the error 

> EXCEPTION: TypeError: Cannot read property '0' of null in [{{quote?.contents?.quotes[0]?.quote}} in App@4:20]

```
import {Component, OnInit, Injectable} from 'angular2/core';
import {Http, HTTP_PROVIDERS, URLSearchParams} from 'angular2/http';
import 'rxjs/add/operator/map';

@Component({
  selector: 'app',
  template: `<ul>
                <li (click)='myAlert()'> Helow World</li>
             </ul>
             <div>
              <spam>{{quote?.contents?.quotes[0]?.quote}}</spam>
             </div>`,
  providers: [HTTP_PROVIDERS]
})

export class App {
  public quote: Object;
  public  logError: string;

  constructor(private http: Http){
    this.quote = {};
  }

  myAlert(){
      this.http.get("http://quotes.rest/qod.json").map(res => { return res.json()})
        .subscribe(
          data => this.quote = data,
          err => this.logError(err),
          () => console.log('Random Quote Complete')
      );

  }
}
```

It failed because I'm trying to use an Elvis operator with an object that has an array. It works perfect with nested objects without array. I'm missing something??

**Comment by zoechi** [comment]
You probably would need a

    quotes?[0]

to only access the first item only when `quotes != null  && quotes.length > 0`.
I don't use TS/JS but I guess this doesn't exist.

**Comment by FreakDroid** [comment]
mmm the same thing ussing that

> EXCEPTION: Template parse errors:
> Parser Error: Conditional expression {{quote?.contents?.quotes?[0].qoute}} requires all 3 expressions at the end of the expression [{{quote?.contents?.quotes?[0].qoute}}] in App@4:20 ("
>              </ul>
>              <div>
>               <spam>[ERROR ->]{{quote?.contents?.quotes?[0].qoute}}</spam>
>              </div>"): App@4:20

**Comment by zoechi** [comment]
That was hypothetical, as mentioned it doesn't exist. You need a workaround. I don't think Angular provides anything here.

**Comment by FreakDroid** [comment]
@zoechi Yes It has a [definition](https://angular.io/docs/ts/latest/guide/template-syntax.html#!#expression-operators) Maybe It does not support objects with array.

**Comment by awerlang** [comment]
It works this way

```
<span>{{quote?.contents?.quotes && quote?.contents?.quotes[0].quote}}</span>
```

It is sad though that `quotes?[0]` isn't supported yet nor `(quotes || [])[0]`

**Comment by FreakDroid** [comment]
@awerlang thanks for your help :+1: I'm going to try this approach.

**Comment by user414** [comment]
Thanks for the suggestion, ran into this issue. +1 to add support for quotes?[0] or something similar.

**Comment by user414** [comment]
As a side note, before I found this I ended using ngfor which also works. It's not as elegant, especially if your array always contain only one element but it does the trick. Perhaps ngif would also work but didn't try.

**Comment by vicb** [comment]
works as expected

**Comment by dietergeerts** [comment]
@vicb , nope, still give the error as on today.

**Comment by DzmitryShylovich** [comment]
@dietergeerts reproduce in plunkr and file a new issue please

**Comment by Nicholas-Westley** [comment]
When you say it works as expected do you mean it is expected not to work?
{{ foo?.bar }} works
{{ foo['bar'] }} works
{{ foo?['bar']}} does not work
https://plnkr.co/edit/lDaTELc1cTpqnCQmNxts?p=preview

**Comment by zoechi** [comment]
Yes, it's expected not to work.

**Comment by raDiesle** [comment]
It might be expected to not work atm, but probably it makes sense to support it as new feature

**Comment by leotm** [comment]
Ran into this issue querying an API that returns a JSON with 1 bad piece of data (missing 1 property) when I display with *ngFor and a pipe to display keys/values - very annoying.
But `*ngIf` deals with it for now.
`property?[0]` would be lovely addition.
BlessRNG
