### ISSUE TITLE
Http getting json error

### ISSUE THREAD

**Issue by Lazarencjusz** [angular/angular#6799]
When I try use http.het i see in console:
`"SyntaxError: expected expression, got '<'`

Index.html:
<head>
    <meta charset="UTF-8">

    <title>Angular 2</title>
    <link rel="stylesheet" href="resources/semantic.min.css">
    <link rel="stylesheet" href="resources/custom.css">
    <script src="node_modules/angular2/bundles/angular2-polyfills.js"></script>
    <script src="node_modules/es6-shim/es6-shim.js"></script>
    <script src="node_modules/systemjs/dist/system.src.js"></script>
    <script src="node_modules/rxjs/bundles/Rx.js"></script>
    <script src="node_modules/angular2/bundles/angular2.dev.js"></script>
    <script src="node_modules/angular2/bundles/router.dev.js"></script>
    <base href="/">
    
    <script src="resources/jquery.min.js"></script>
    <script src="resources/semantic.min.js"></script>
    
    
    <script>
        System.config({
            packages: {
                app: {
                    format: 'register',
                    defaultExtension: 'js'
                }
            }
        });
        System.import('app/boot.js')
                .then(null, console.error.bind(console));

    </script>
    <link rel="stylesheet" href="css/style.css">
</head>

<body>
<div id="fb-root"></div>
<script>
    window.fbAsyncInit = function () {
        FB.init({
            appId: '1545125172465450',
            xfbml: true,
            version: 'v2.5'
        });
    };

    (function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) {
            return;
        }
        js = d.createElement(s);
        js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>
\<app>
    loading...
\</app>

\<page-menu>
Ładowanie...
\</page-menu>

boot.ts:

>import {PageMenu} from './widgets/page-menu/page-menu';
import {bootstrap} from 'angular2/platform/browser';
import {ROUTER_PROVIDERS} from 'angular2/router';
import {HTTP_PROVIDERS, Http} from 'angular2/http';
import {AppComponent} from './app.component';
import {App} from 'http/app'
bootstrap(AppComponent);
bootstrap(App);
bootstrap(PageMenu, [
    ROUTER_PROVIDERS
]).catch(err => console.error(err));

App.ts:

> import {Component} from 'angular2/core';
import {NgFor} from 'angular2/common';
import {HTTP_BINDINGS, Http} from 'angular2/http';
@Component({
    selector: 'app',
    //bindings: [HTTP_BINDINGS],
    template: `
    <div>
      <h1>People</h1>
      <ul>
        <li *ngFor="#person of people">
          {{person.name}}
        </li>
      </ul>
    </div>
  `,
    directives: [NgFor]
})
export class App {
    people:Object[];
    constructor(http:Http) {
        http.get('people.json').toRx().subscribe(res => {
            this.people = res.json();
        });
    }
    active:boolean = false;
    toggleActiveState() {
        this.active = !this.active;
    }
}

Sorry for bad looking issue.

**Comment by ericmartinezr** [comment]
You have commented the Http bundle. Please move your questions to to gitter's chatroom or StackOverflow (StackOverflow is full with these questions).

**Comment by Lazarencjusz** [comment]
Ok, I will do it. Moreover, I uncommented line you mentioned and do few little changes and it works. Why  Http needs this line?

**Comment by ericmartinezr** [comment]
@Lazarencjusz because Http is on its own module

**Comment by Lazarencjusz** [comment]
@ericmartinezr ok, my fail, waste whole day on it :) thanks for help
