### ISSUE TITLE
Two way data binding does not appear to be working in Firefox for <select>

### ISSUE THREAD

**Issue by fuzing** [angular/angular#6800]
Please see the following gist:
https://gist.github.com/fuzing/ae762b795dd3376edf78

'dmodel' is simply an object that holds values for the fields in the form.

Angular 2 version: 2.0.0-beta.2
I have the following relevant js files loaded in the browser:

es6-shim
angular2-polyfills.js
system.src.js
Rx.min.js
angular2.js
router.dev.js
http.dev.js

Thanks!

**Comment by fuzing** [comment]
BTW - working in Chrome/Safari/Opera

All other <input> elements working in Firefox - just issue with <select>

**Comment by ericmartinezr** [comment]
Dup of https://github.com/angular/angular/issues/6573

**Comment by fuzing** [comment]
thanks Eric - I'll close this out and watch #6573 - sorry for duplication!
