### ISSUE TITLE
Make sure Observable emitted a value in a test - how? lack of docs

### ISSUE THREAD

**Issue by alvipeo** [angular/angular#6801]
In my tests I need to make sure this.control.valueChanges emits a value in response of a dispatchEvent. How do I do this? I've seen an ObservableWrapper but don't really know how to use it.

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/blob/master/modules/angular2/test/facade/async_spec.ts#L31-L36

**Comment by alvipeo** [comment]
Oh, thank you! Another great example.
