### ISSUE TITLE
Move min version of Dart to 1.9.0-dev.8.0

### ISSUE THREAD

**Issue by kevmoo** [angular/angular#681]
- [ ] Update readme
- [ ] disable 'stable' release in travis file – until 1.9 hits stable
- [ ] update pubspecs to define an SDK version constraint

```yaml
environment:
  sdk: '>=1.9.0-dev.8.0 <2.0.0'
```

**Comment by vicb** [comment]
@kevmoo I'm curious why this is required ? (I prefer to dev on the stable channel because the dev channel could be unstable sometimes)

**Comment by kevmoo** [comment]
@vicb We were hitting a `pub build` issue that has been fixed in 1.9
