### ISSUE TITLE
ngDoCheck confusion

### ISSUE THREAD

**Issue by zoechi** [angular/angular#6810]
https://angular.io/docs/ts/latest/api/core/DoCheck-interface.html

states 

> Implement this interface to override the default change detection algorithm for your directive.

but if I implement the `DoCheck` interface with an empty `ngDoCheck() {}`, change detection still happens.

In `CustomCheckComponent` `list` is still updated (reflecting the changes made in the parent and the change is also reflected in the view, also the `{{value}}` in ``CustomCheckComponent` gets updated (by the periodic timer)

Example project: https://github.com/bwu-dart-playground/dart_playground/blob/9f966d21bb68b47a68d0f9772f552f7f29a3747b/angular2/ng_do_check/lib/app_element.dart#L15-L15
- `ngDoCheck` doesn't seem to "override" the default change detection
- there is no information about how to inform Angular about the changes detected by the custom change detection.

I don't know if this is a docs issue, an implementation issue or if I'm just misinterpreting the docs.

**Comment by qnimate** [comment]
@zoechi even I am confused. did u get answer for this?

**Comment by zoechi** [comment]
@qnimate no. Thanks for the reminder though. I'll have a look again myself. Maybe I gained some additional understanding about Angulars change detection since when I created this issue...

**Comment by qnimate** [comment]
@zoechi I feel even `ngAfterContentChecked` shouldn't be triggered when `ngDoCheck` is registered. If we can handle attribute changes then we should also be able to handle content changes isn't it?

**Comment by manfredsteyer** [comment]
I have exactly the same issue. Can anyone shed some light on this?

**Comment by manfredsteyer** [comment]
Just dug into it a bit. The notification seems to be done by the Differ. But I didn't find out, how the differ notifies angular.

**Comment by zbjornson** [comment]
New to this, but what I think is happening:

* `ngFor` is its own directive and thus has [its own change detector](https://github.com/angular/angular/blob/master/modules/%40angular/common/src/directives/ng_for.ts#L111-L116). The implementation of `ngDoCheck` in a component that happens to use `ngFor` in its template is independent of the change detection used by `ngFor`.
* `ngDoCheck` is for doing work in your controller whenever a digest runs. Look [further down in `ngFor`](https://github.com/angular/angular/blob/master/modules/%40angular/common/src/directives/ng_for.ts#L118-L149) to see that the work done in response to the changes is invoked manually; there's nothing to notify angular about per se.
* (@manfredsteyer I don't think the Differ is involved with change notification, it seems to just be a utility class.)

**Comment by zbjornson** [comment]
Continued:

* (See my last comment in https://github.com/angular/angular/issues/7307) It seems like implementing `ngDoCheck` supplements but does not replace the default change detection algorithm, and as a result `onChanges` will still be called whenever the default change detector detects a change.

I'd appreciate any corrections to this as well as any statements from the devs about intended/desired behavior (if different), as I'm working on back-porting this to Angular 1.5 and trying to empirically determine what the correct behavior is in Angular 2. :)

**Comment by DzmitryShylovich** [comment]
@zoechi re open on angular.io?

**Comment by maximusk** [comment]
`ngDoCheck` doesn't override the changed detection, it's simply called on every changed detection cycle and it's only job is to mark current view `cdMode` as `checkOnce`. See [this answer](http://stackoverflow.com/a/42807309/2545680) for details.
