### ISSUE TITLE
Missing DI providers with beta 2

### ISSUE THREAD

**Issue by andrashatvani** [angular/angular#6813]
We use TestComponentBuilder in our tests and after the upgrade to beta 2 the following providers won't be provided anymore automatically by angular:
- TestComponentBuilder
- DirectiveResolver
- ViewResolver
- DOCUMENT_TOKEN.
The problem is that DOCUMENT_TOKEN isn't in the codebase anymore; it used to reside in 'angular2/src/render/dom/dom_renderer'.

Furthermore, the Jasmine libraries won't be exported automatically anymore, either.

**Comment by zoechi** [comment]
You are using the `TEST_BROWSER_XXX_PROVIDERS` like explained in https://github.com/angular/angular/commit/b0cebdb ?
See also https://github.com/angular/angular/blob/master/CHANGELOG.md#features

**Comment by andrashatvani** [comment]
No, I missed the change. But after adding the required addition setup I see the following error:
Error: XHR error (404 Not Found) loading http://localhost:9876/angular2/platform/testing/browser

**Comment by ericmdantas** [comment]
Same problem here with `TestComponentBuilder`.

**Comment by brandonroberts** [comment]
The TEST_BROWSER_XXX_PROVIDERS didn't make it into the bundles: See https://github.com/angular/angular/issues/5351#issuecomment-176493983

**Comment by andrashatvani** [comment]
@brandonroberts What is the impact of the referenced issue on this one?

**Comment by brandonroberts** [comment]
You can't import TEST_BROWSER_XXX_PROVIDERS from angular2/platform/testing/browser which is why you were getting the 404.

**Comment by andrashatvani** [comment]
@brandonroberts But these providers are there in angular2/platform/testing/browser

**Comment by brandonroberts** [comment]
Ok, they must have updated the built bundles for beta.2.

**Comment by brandonroberts** [comment]
@andrashatvani  DOCUMENT_TOKEN is provided as DOCUMENT now from `angular2/platform/browser`

**Comment by ThorstenHans** [comment]
Both  `TEST_BROWSER_PLATFORM_PROVIDERS` and `TEST_BROWSER_APPLICATION_PROVIDERS` are there in the source but they didn't make it to the bundles. Is there a way how to fix this? 

According to the ChangeLog they should be there https://github.com/angular/angular/blob/master/CHANGELOG.md#features

**Comment by alexeagle** [comment]
I updated the bundles on code.angularjs.org.
Fix for the npm release will come this week in beta.3 (should be Wednesday)

**Comment by meriturva** [comment]
Great we really need it fixed here as soon as possible! So thanks!

**Comment by andrashatvani** [comment]
Verified fixed.
