### ISSUE TITLE
Angular Does not support more than 9 expressions in the view 

### ISSUE THREAD

**Issue by fouratachour** [angular/angular#6816]
i'm working on angular 2 , so i  ned to build a svg rect , that rect content more than 9 expression so angular show erreur and tell me that it can not handel more then 9 expression `<img src="http://i.stack.imgur.com/wImNs.png" /> `

**Comment by zoechi** [comment]
Could you please add the code (rect) that demonstrates what you try to accomplish?

**Comment by zoechi** [comment]
dup of #6966

**Comment by pkozlowski-opensource** [comment]
dup of #6966
