### ISSUE TITLE
Add hint to TemplateCompiler for propertyBinding not used by any directive

### ISSUE THREAD

**Issue by DavidSouther** [angular/angular#6820]
When you forget to include a component used by a template in the `directive` binding, the error message is `Property binding [component] not used by any directive on an embedded template ("[...context...]"): [ComponentClass]@[position]`.

This should also include a hint to the developer, "Did you mean to add [component, ...] to ComponentClass?"

**Comment by pkozlowski-opensource** [comment]
@DavidSouther as much as I hate the current error message we can't implement your suggestion for the following reasons: 
* we don't know to which directive a given template binding might belong (remember, it wasn't listed in directives!)
* it might be a simple typo so a directive might be correctly listed in `directives: [...]`

I'm going to send a PR with sth slightly better but yeh, we can't have what you are asking for, sadly...
