### ISSUE TITLE
Form: add `reset` feature in support of form clearing

### ISSUE THREAD

**Issue by wardbell** [angular/angular#6822]
As of beta.2 there is no clean way to reset a form and clear the control class values, `pristine` and `untouched` in particular.

The trick described in (closed) #6819 is a temporary workaround

**Comment by zoechi** [comment]
dup of #4933?

**Comment by wardbell** [comment]
@zoechi I agree. It is a dup

**Comment by robwormald** [comment]
closing as dupe of #4933
