### ISSUE TITLE
dart.dev build times out after 2h

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#6823]
This is currently blocking travis builds, even when dart.dev is an Allowed Failure.

**Comment by kegluneq** [comment]
It appears that this is likely due to https://github.com/dart-lang/sdk/issues/25636.

I'll take a look once that issue is cleared up.

**Comment by kegluneq** [comment]
Copied from @alan-knight update on the bug above:

> https://codereview.chromium.org/1653143002/ fixed my snapping problem and the bot failures, so with luck it also fixes this issue. We may need a cherry-pick to dev.

**Comment by kegluneq** [comment]
I tried enabling dev mode again today and it is still failing.

It looks like there is a fix for this in Dart's bleeding edge release but that it has not made it to dev yet.

**Comment by kegluneq** [comment]
The freeze seems to be fixed now, but there is now a `dartdoc` issue. Looking into that now.

https://travis-ci.org/angular/angular/jobs/108380582

**Comment by kegluneq** [comment]
`dartdoc` issue: https://github.com/dart-lang/dartdoc/issues/1099

In investigating, I found a workaround -- will try that now.

**Comment by kegluneq** [comment]
Still, broken, it seems
