### ISSUE TITLE
CSS in the Component JS

### ISSUE THREAD

**Issue by mohammedzamakhan** [angular/angular#6826]
As a Front End Developer, I do not find any problems having CSS files outside JS, and I love them being in CSS files. I don't want my application to waste time in ViewEncapsulation of my styles in the component, and not even include the JS that would deal with the CSS styles that is executed in the Component (I want my teams not to write any CSS in JS).

Is their a way to exclude this functionality from the angular, by that I mean, can that be a different module, which can be excluded from the core, or do something which will make the loading of application with my understanding in mind.

**Comment by CaptainCodeman** [comment]
You can combine CSS, SASS or LESS files as you normally do regardless of whether you keep the snippets alongside the components or elsewhere. Just don't define any styles for the components and none will be used (besides any global ones matching the regular selectors)

**Comment by mohammedzamakhan** [comment]
@CaptainCodeman I just don't want angular to include the code for styles in Components available for every project to use, they should create a provider for it to be injected to be used, so that I can use probably tree shaking and exclude the module from loading in the browser.

**Comment by zoechi** [comment]
Just set `encapsulation: ViewEncapsulation.None` in your component and import the CSS files just in the entry page.

**Comment by CaptainCodeman** [comment]
There are a couple of other approaches that may give you what you are after but depend on how you build and package your app.

If using webpack you could do a require() for the css in each component and then have those css snippets combined and output as a single external stylesheet. That way only the styles for components used in the app should be included.

Another approach is to look at something like uncss to try and remove styles that are not used in your app. This can help with things like bootstrap as well - even if you already have a custom build it's unlikely you use every class for a feature.

**Comment by mohammedzamakhan** [comment]
@zoechi I know that I can use ```encapsulation: ViewEncapsulation.None``` 

What I am asking is that angular should not include this code by default in it, since I will never use this in my project, and I do not want angular to include it by default, I want others who want this feature to include it by including the file for it and adding provider at bootstrap step.

**Comment by spock123** [comment]
What is the problem with the feature?
Performance?

It is not required to use component encapsulared styles.

**Comment by mohammedzamakhan** [comment]
@spock123 Their is no problem with the feature.

I am CSS Nerd and I like global css, and I do not want this functionality to be done by any framework, I know I can write best CSS in one file and serve in the application without any complications. I do not angular to load this functionality in the browser, because I do not know how heavy of a functionality is that for angular.

**Comment by robwormald** [comment]
`because I do not know how heavy of a functionality is that for angular.` -> negligible, and part of the compiler API anyway, which wouldn't ship in a production application once offline compilation is implemented.
