### ISSUE TITLE
Custom elements that extends existing elements does not upgrade in template on Chrome

### ISSUE THREAD

**Issue by jianliao** [angular/angular#6827]
I try to use a custom elements in my Angular 2 template, if my custom element extends an existing elements. It would not got upgraded. Please check my [plnkr](http://plnkr.co/edit/85E9s1siz0GHofMSpg92?p=preview) for detail. 

This problem is only on Chrome because it has native support for custom elements. Latest Firefox and Safari does not have any problem as custom-elements ployfills kicks in. My investigation show that it is related to DomRenderer.prototype.createElement function. If you want to create an custom elements that extends existing element, you need to call `var xFooButton = document.createElement('button', 'x-foo-button');`

EDIT:

Plunker based on Angular 2.0

http://plnkr.co/edit/mhSk6wNK3ZKMGqcwt5GG?p=preview

**Comment by lazd** [comment]
+1 this is a huge issue.

**Comment by zoechi** [comment]
I wild guess would be that Angular first adds the element and then later sets the `is="..."` attribute, which doesn't work. Changing the `is="..."` attribute after the element was added doesn't have any effect.

```
<div [innerHtml]="html"></div>
```
with 
```
html = '<button is="x-foo-button">You should not see this3</button>';
```
works
https://plnkr.co/edit/uqq0f45foPYXSPp0WJWc?p=preview

**Comment by joekukish** [comment]
+1

**Comment by Kevin-Monahan** [comment]
I ran into this problem with my first use of Angular 2. 
+1

**Comment by hac0demon** [comment]
+1

**Comment by knicholes** [comment]
+1

**Comment by tempoc** [comment]
+1

**Comment by jianliao** [comment]
@zoechi 
Yes, you are totally correct. The template like below:
`<button is="x-foo-button">You should not see this3</button>`
will be translated into the following JavaScript code:
`self._el_7 = self.renderer.createElement(self._el_0,'button',self.debug(7,3,2));
  self.renderer.setElementAttribute(self._el_7,'is','x-foo-button');
  self._text_8 = self.renderer.createText(self._el_7,'You should not see this3',self.debug(8,3,28));`

My customer element will not be upgraded.

**Comment by aadidasu** [comment]
+1

**Comment by agrajm** [comment]
+1

**Comment by suseegithub** [comment]
+1 I am facing this issue. Needs resolution.

**Comment by iamsudhanshu** [comment]
+1

**Comment by zoechi** [comment]
`+1` was deprecated in favor of "add reaction" please migrate to the new feature as soon as possible!

**Comment by stephanringel** [comment]
+1

**Comment by lazd** [comment]
@jianliao is this still a problem in Angular 2.0.0?

**Comment by jianliao** [comment]
Yes, it is still a problem on chrome.

**Comment by vicb** [comment]
Could you please provide a plunker updated to the latest Angular release 2.0.0. Thanks.

**Comment by vicb** [comment]
Do we agree than the problem only occur with custom element that extend other element ?

**Comment by vicb** [comment]
Might need a breaking change in the render API.

Could `customElements.get()` help here ? 
https://www.w3.org/TR/custom-elements/#dom-customelementregistry-get

**Comment by jianliao** [comment]
http://plnkr.co/edit/mhSk6wNK3ZKMGqcwt5GG?p=preview

Please try it on both Chrome and Firefox. You will see the different.

**Comment by nevinm** [comment]
@jianliao Any particular version of Chrome?

**Comment by jianliao** [comment]
@nevinm from 52 to 54beta.

**Comment by manklu** [comment]
>Could customElements.get() help here ? 
https://www.w3.org/TR/custom-elements/#dom-customelementregistry-get

Not necessary. All that's needed is to replace
```javascript
 createElement('button')
```
 with
```javascript
createElement('button', 'x-foo-button')
```

**Comment by vicb** [comment]
Adding some refs:

https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/j7Oo9JSPY8c/discussion

```
Interoperability and Compatibility Risk
This is tricky and why we’re seeking feedback early:
- Mozilla is implementing custom elements (for example, see dom/base/CustomElementRegistry.*) including arguments which relate to customized built-in elements.
- Microsoft Platform Status has custom elements under consideration/roadmap priority medium. At TPAC 2016 they indicated they’re “generally okay with is= proposal [which I take to be shorthand for customized built-in elements].” (Meeting minutes.)
- Apple has said they will NOT implement customized built-in elements (for example, here.)
```

https://github.com/w3c/webcomponents/issues/509#issuecomment-230780607

**Comment by jianliao** [comment]
Although it is still a workaround, but a customizable renderer help. https://blog.nrwl.io/experiments-with-angular-renderers-c5f647d4fd9e

**Comment by splincode** [comment]
@vicb This issue is relevant? This is similar to the problem before the Angular Elements

**Comment by Kim-Andersen** [comment]
This is still an issue in latest Angular (7.2.5 at time of writing):

[https://stackblitz.com/edit/angular-dginkc](https://stackblitz.com/edit/angular-dginkc)
[https://stackoverflow.com/questions/55287677/extended-custom-elements-not-working-in-angular-2](https://stackoverflow.com/questions/55287677/extended-custom-elements-not-working-in-angular-2)
[https://stackoverflow.com/questions/53604958/extending-native-html-element-in-angular-6](https://stackoverflow.com/questions/53604958/extending-native-html-element-in-angular-6)

**Comment by MichaelBrimer** [comment]
And it is still not working in Angular, I have tested https://stackblitz.com/edit/angular-dginkc
 with Angular version 8.2.14 and Angular version 9.0.0-rc.7

**Comment by pkozlowski-opensource** [comment]
Latest repro with Angular v9 + ivy: https://ng-run.com/edit/MTvoQ5ozUZFYZRAPQtle?open=index.html

This one is tricky since we would have to understand and interpret the `is` attribute when generating code.

**Comment by Kim-Andersen** [comment]
> Latest repro with Angular v9 + ivy: https://ng-run.com/edit/MTvoQ5ozUZFYZRAPQtle?open=index.html
> 
> This one is tricky since we would have to understand and interpret the `is` attribute when generating code.

Yes, however, this feature would make Angular fully compliant. It would be so neat to have.

**Comment by MichaelBrimer** [comment]
As I understand it, the "is" attribute is part of the specification for Web Components and since we believe that Web Components are the future, I really hope you will consider this.

**Comment by pkozlowski-opensource** [comment]
Additional data point: it seems like support for `is="..."` is somehow controversial and is happening in some browsers: https://github.com/webcomponents/custom-elements-everywhere/issues/376#issuecomment-576878118

**Comment by pkozlowski-opensource** [comment]
I'm going to mark it as a feature request since:
* we never designed / coded it to work;
* there are more changes / design that is needed
* state of support across browsers is not clear;

**Comment by calebdwilliams** [comment]
I also want to chime in support for this. It should be a relatively easy fix. When generating the element, check first if the element has an `is` attribute. `is` cannot be added/changed/removed at a later point, just grab the `is` out of the list and instead of `document.createElement(tagName)`, you call `document.createElement(tagName, { is: attributes.is })`. 

Browser support is solid across modern browsers except Safari who has said they won't implement it (but I believe one of their engineers said they would be open to revisiting that decision). There is a polyfill by @WebReflection that works well, but that's obviously up to consuming apps to choose to load or not. IMO this is a no-brainer and, seeing that it has been open for almost five years, I would love to see a commitment one way or another from the Angular team.

**Comment by gkalpak** [comment]
Given that extending built-in elements is currently not natively supported by Safari ([with no intention to support][1] 😢), we have decided not to move forward with this feature request at this time.

The fact that a major browser does not support the feature is a significant downside. Additionally, given the relatively low demand for this feature and the higher priority of other work, we are unlikely to get to it in the foreseeable future.

(We might revisit this decision if browser-support or user demand change in the future.)

[1]: https://bugs.webkit.org/show_bug.cgi?id=182671
