### ISSUE TITLE
Update SelectControlValueAccessor selector

### ISSUE THREAD

**Issue by anorborg** [angular/angular#6830]
This is related to #4427 (`<select multiple>` support).

Until  `<select multiple>` support can be implemented, I would like to request updating the selector in the mean time to allow for implementing a custom ControlValueAccessor:

Existing:
`selector: 'select[ngControl],select[ngFormControl],select[ngModel]',`

Proposed:
`selector: 'select:not([multiple])[ngControl],select:not([multiple])[ngFormControl],select:not([multiple])[ngModel]',`

Obviously implementing multiple would be ideal, but giving us an opportunity in the mean time to solve the issue in our own projects would be very helpful especially given the small change. Otherwise it would take wrapping a component around it which isn't ideal for some css frameworks.

I would attempt to do this myself, but not prepared to setup my dev environment for contributions quite yet :)

**Comment by sullyme** [comment]
+1

**Comment by kara** [comment]
Multi-select support was added with RC.2, so closing this.
