### ISSUE TITLE
quickstart tutorial bug

### ISSUE THREAD

**Issue by kellerapps** [angular/angular#6832]
https://angular.io/docs/ts/latest/quickstart.html
app/main.ts
`import {AppComponent} from './**app.**component'`
should be:
`import {AppComponent} from './component'`

**Comment by bjwyse** [comment]
I don't see that line on https://angular.io/docs/ts/latest/quickstart.html

Can you add screenshot please?

**Comment by kellerapps** [comment]
Maybe when I saw app dot component.ts I typed app/component.ts. Sorry for the false alarm & thx for angular 2.
