### ISSUE TITLE
Are expression bindings (angular 1 style) planned?

### ISSUE THREAD

**Issue by oliverjanik** [angular/angular#6836]
Angular 1 directives have '&' bindings that allow us bind to an expression and provide parameters for that expression.

Is this planned for Angular 2? If not what's the recommended replacement? This would be ideal for callbacks. Here's what I've tried:

1. `[callback]="myFunc"` - works
1. `(callback)="myFunc($event)"` - inside myFunc modifiy $event then check for this modification after emit within the Directive. Does not work, the emit seems to be async.
1. `[callback]="() => myFunc(param)"` -> does not work

I need more flexibility. Something like  this would be great:

```
<my-comp {canDrop}="canDrop($item, parent)">
```

and then within Component

```
var result = this.canDrop({$item: item});
```

**Comment by pkozlowski-opensource** [comment]
Events are delivered sync now so you can do (2)
