### ISSUE TITLE
Table with a list and custom items

### ISSUE THREAD

**Issue by unix1982** [angular/angular#6840]
I don't know if this is an issue or I that use falsely the objects. 

I'm trying to make a table with angularJs2 <code>2.0.0-beta.0</code>. This table lists items. I would decouple the item from the list. 

I have this code:
<code>app.item.list.html</code>

    <table class="table table-condensed"  [hidden]="items?.length==0">
      <thead>
        <tr>
          <th >id</th>
          <th >col 2</th>
          <th >col 3</th>
          <th >col 4</th>
          <th >col 5</th>
          <th >col 6</th>
        </tr>
      </thead>
      <tbody>

        <tr *ngFor="#item of items" >
          <item-detail [item]="item"></item-detail>
        </tr>
      </tbody>
    </table>

The <code>app.item.list.ts</code>

    import {Component, EventEmitter, Output, Input, OnChanges, SimpleChange} from 'angular2/core';
    import {FORM_DIRECTIVES} from 'angular2/common';
    import {Item} from './model/model.item';

    @Component({
        selector: 'item-list',
        templateUrl: 'app/app.item.list.html',
        directives: [FORM_DIRECTIVES, Item]
    })
    export class ItemList{

       @Input() Items:Array<Item> = new Array();
       public item: Item;

    }

the <code>app.item.html</code>

    <td >{{item.id}}</td>
    <td >{{item.col1}}</td>
    <td >{{item.col2}}</td>
    <td >{{item.col3}}</td>
    <td >{{item.col4}}</td>
    <td >{{item.col5}}</td>

And the <code>app.item.ts</code>

    import {Component, Input, EventEmitter, Output, OnChanges, SimpleChange} from 'angular2/core';
    import {FORM_DIRECTIVES, NgFor} from 'angular2/common';

    @Component({
        selector: 'item-detail',
        templateUrl: 'app/app.item.html',
        directives: [ FORM_DIRECTIVES, NgFor]
    })

    export class Item{

      @Input() item:Item;

    }

The Items informations are all displayed, but there is a format problem. All my items are raggrouped under the first column of the header (the id column). 

But I want to have the item.id under the id header, the item.col1 under col1 ....

What can I do having the list and the item decoupled? 

P.S.: When they were in a single html and ts file, it worked well

**Comment by zoechi** [comment]
I didn't have a very close look at your example but 
this doesn't generate valid HTML. `<item-detail>` is not an allowed tag within `<tr>`

```html
    <tr *ngFor="#item of items" >
      <item-detail [item]="item"></item-detail>
    </tr>
```
you probably want something like

    <tr *ngFor="#item of items" >
      <td item-detail [item]="item"></td item-detail>
    </tr>
```
The `selector: 'item-detail'` needs to be changed to `selector: '[item-detail]'` for this to work.

GitHub issues are for bug reports and feature requests. Please use StackOverflow, Google Groups, Gitter, ... for support questions.

**Comment by unix1982** [comment]
Hi, txs, I will look forward in stackoverflow or google groups.

**Comment by todoubaba** [comment]
@unix1982  You could do this:
```html
<tr *ngFor="#item of items" [item-detail]="item"><tr>
```

```typescript
@Component({
    selector: '[item-detail]',
    ...
})
export class Item{
  @Input('item-detail') item:Item;
}
```

**Comment by unix1982** [comment]
Yes this is the solution. Tank you @todoubaba
