### ISSUE TITLE
ngFormControl on select not changing if steered by webdriverjs/protractor3

### ISSUE THREAD

**Issue by Sabartius** [angular/angular#6841]
Hey,

after Upgrading my Application from Beta.0 to Beta.1, Beta.2 or Beta.3 my Protractor-Tests won't trigger any value-changes on select-Controls. This seems to be related to this change: https://github.com/angular/angular/commit/b44d36cf955acd81a3e7285ab0e1acbffe8c8dcc
There got the change-Event dropped, which seems to be vital to Protractor.
Using the Application on my own, the select control works as expected. Protractor runs under Chrome 47.

Any ideas on this?

**Comment by Sabartius** [comment]
As a workaroud i wrote a small Directive, which listens on the "old" change-Event and updates the ngFormControl accordingly, so that i can run my tests again successfully...

````
@Directive({
  selector: "select:not(multiple)[ngFormControl], 
  host: { "(change)":  "onChange($event.target.value)" } 
})
 export class SelectWorkAround {
  @Input() ngFormControl: Control;

  onChange: any = (value: any) => {
    if(this.ngFormControl) {
       this.ngFormControl.updateValue(value);
    }
  }
}
```

**Comment by zoechi** [comment]
looks like a dup of #6573

**Comment by kara** [comment]
As @zoechi mentioned, this seems like a dupe. Please follow the issue in #6573, thanks! :)
