### ISSUE TITLE
Ng2 Router: Impossible to style the created element.

### ISSUE THREAD

**Issue by thso** [angular/angular#6843]
Haven't found a solution to style the element that is inserted at the `router-outlet` marker. I would expect the following to work:

    <router-outlet class='flex'>

The attributes/class would then be copied on the generated tag. For example, when navigating to `/component`, it would render:

    <component class='flex'>

**Comment by dblVs** [comment]
you can use the example below as a work around for that. (it's a really bad practice with drawbacks like you will always have that class on your component).

```
@Component({
    selector: 'component',
    host: {
        'class': 'flex'
    },
})
```

**Comment by Namek** [comment]
It would need a manual passing of attributes. If you look into DOM, your component is not created inside RouterOutlet but next to it.

**Comment by mika-fischer** [comment]
This problem is also present in the Component Router for Angular 1 and there, I don't know the equivalent to @dblVs workaround, unfortunately...

**Comment by CaptainCodeman** [comment]
As @Namek said, the router outlet is just the point that the component is created (as a sibling) and not the container for it so it will *not* inherit styles or classes defined on it (maybe it should copy them?). Don't think of it as part of the DOM tree for your components.

In general, the router doesn't do anything but act as a placeholder. Unless you create a custom version  it won't pass any parameters or anything else and if that is required there are probably easier ways to achieve it.

**Comment by mika-fischer** [comment]
Well, when looking at my DOM, my component is actually a child of the ng-outlet element. ng-outlet retains its attributes. But I see no way to add attributes to the element that the router creates...

**Comment by CaptainCodeman** [comment]
Sorry, I was talking about v2, if it behaves differently in v1 then it's unfortunately going to cause some confusion for people on the upgrade path.

**Comment by mika-fischer** [comment]
For the people running into this issue with Angular 1, also see: https://github.com/brandonroberts/angularjs-component-router/issues/12

**Comment by brandonroberts** [comment]
This can be done with a custom router outlet in Angular 2.

Plunker: http://plnkr.co/edit/jCNEhA?p=preview

**Comment by vicb** [comment]
obsolete - former router

**Comment by hotstone** [comment]
@vicb  So how is the original problem (automatically apply a class to components generated by router) achieved in the current router?
Sorry if I'm missing something obvious, but I couldn't see it in the documentation.

**Comment by pauldraper** [comment]
@vicb in what way is this obsolete?

## AT ALL?
