### ISSUE TITLE
http Headers (copy) constructor

### ISSUE THREAD

**Issue by fjozsef** [angular/angular#6845]
In case: ` if (headers instanceof Headers)`
Headers (copy) constructor creates only the shallow copy of the given Headers.
```typescript
 constructor(headers?: Headers | {[key: string]: any}) {
    if (headers instanceof Headers) {
      this._headersMap = (<Headers>headers)._headersMap;
      return;
    }

    this._headersMap = new Map<string, string[]>();

    if (isBlank(headers)) {
      return;
    }

    // headers instanceof StringMap
    StringMapWrapper.forEach(
        headers, (v, k) => { this._headersMap.set(k, isListLikeIterable(v) ? v : [v]); });
  }
```

It should deep copy the `headers`.

Version: angular-2.0.0-beta.2

**Comment by robwormald** [comment]
perhaps i'm misunderstanding your use case here, but headers, by definition, are basically shallow as they are simple key/value pairs. could you expand on a case where this isn't working for you?

**Comment by fjozsef** [comment]
The `Headers` class has only one property (`_headersMap: Map<string, string[]>`) and look at this:
```typescript
var myHeaders: Headers = new Headers();
// ...
// Add additional headers to myHeaders
// ...
var myOtherHeaders: Headers = new Headers(myHeaders);
```
In case of shallow copy: Instead of the last line, I could have just write: 
```typescript
var myOtherHeaders: Headers = myHeaders;
```

Since the underlying data is the same, why would you expect from the constructor to create a shallow copy?

I just write these to Chrome Developer Tools (which uses the Fetch API's Headers class):
```javascript
var myHeader = new Headers();
myHeader.append("key","value");
var myOtherHeader = new Headers(myHeader);
myOtherHeader.append("other-key","other-value");
myHeader.get("other-key");
```
The result to the last line was `null`. If the the underlying map would be the same (in case of shallow copy) I should have got `"other-value"` as result.

Use case for deep copy:
```typescript
@Injectable()
export class MyService {
     private skeletonHeaders: Headers; //Every Headers has to contain this Headers's header-key pairs
     constructor(){
        skeletonHeaders = new Headers();
        skeletonHeaders.append("X-MY-CUSTOM-KEY", "VALUE");
    }
 
    request() : Observable<Response> {
          var myRequestHeaders: Headers = new Headers(this.skeletonHeaders);
          myRequestHeaders.append("other-key","other-value"); //request specific header
          // this.skeletonHeaders also contains the previous header, but I don't want it.
          // ....
         return observable;
    }
};
```

**Comment by mexx** [comment]
I've run into this issue as well.
I have an decorated XHRBackend and adjust the headers when `createConnection` gets called. However, as the original request have no headers attached, through my actions and the shallow copy the headers `_defaultOptions` gets modified.
I know my use case is not a common one, but it's pretty surprising to get the default headers modified, isn't it?

**Comment by sebastianhaas** [comment]
Just ran into the same problem. It's really not what you expect from a copy constructor, even more so since you get to choose between `headers?: Headers` and `{ [key: string]: any; }` where the first one will cause a completely different effect than the latter, not even mentioned in the documentation.
