### ISSUE TITLE
Run travis browser tests on Chrome >= stable

### ISSUE THREAD

**Issue by vsmenon** [angular/angular#6846]
Travis tests are currently running on Dartium, with lags Chrome stable.  The current Dartium is based on Chrome 39 from 2014.

This is blocking end-to-end testing of DDC, which requires Chrome 47 or newer (stable is 48):

https://github.com/angular/angular/pull/6783

@mhevery

**Comment by vsmenon** [comment]
@mhevery: this should be labeled DDC - but I don't have permission to tag issues.

**Comment by IgorMinar** [comment]
This is related to #5393 which is already being worked on

**Comment by zoechi** [comment]
A new Dartium that is based on a recent Chromium is worked on. It was announced and postponed several times already. I hope it will be included in one of the next 1.15.0-dev releases (as recently mentioned in an GitHub issue) and finally officially added to the 1.15.0 release.

**Comment by mhevery** [comment]
Any update on this? We need this for #6783

**Comment by IgorMinar** [comment]
The chromium pr landed or is about to land. Can you verify that that
satisfy this issue?

**Comment by yjbanov** [comment]
https://github.com/angular/angular/pull/5393 hasn't landed yet, so this issue is still blocking https://github.com/angular/angular/pull/6783

**Comment by zoechi** [comment]
Dartium is now based on Chromium 45 in the dev channel

**Comment by yjbanov** [comment]
@zoechi: thanks for the heads up!
@vsmenon: is Chromium 45 sufficient to run DDC code?

**Comment by vsmenon** [comment]
No, we need at least Chromium 47.  Stable is 48, so anything at least as recent as stable will work.

**Comment by zoechi** [comment]
I guess it's worth asking @alan-knigth about planned progress. There was a lot of work going on to make it easier to get Dartium updated. I expect (or hope) that when Dartium based on Chromium 45 is released, the next step is to get it updated to the most recent Chromium "shortly" afterwards. 
If it's worth it depends on how much work this task is of course. If it's not too much, it might still be better to use Chromium instead of Dartium.

**Comment by IgorMinar** [comment]
fixed by #5393

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166570.
------------------------------------------------------------------------------------------------------------


[[4d36165f98b71277f52bd1d83af709550d7c4d46-673074351]]
