### ISSUE TITLE
Accessing Control object using ngFormControl on a custom directive.

### ISSUE THREAD

**Issue by amanjain** [angular/angular#6855]
I have created a custom directive `<autocomplete></autocomplete>` and I am trying to access a `Control` object as `<autocomplete ngFormControl='controlObjectVar'></autocomplete>`. It raises the following exception: `EXCEPTION: No value accessor for '' in [controlObjectVar in ManagerComponent@38:63]`. Is there a document I can refer to, cause I could not find one..

**Comment by zoechi** [comment]
I guess you need a custom ControlValueAccessor.

- http://stackoverflow.com/questions/33981270/bind-angular-2-model-to-polymer-dropdown/33986250
- https://github.com/angular/angular/issues/2543

**Comment by pkozlowski-opensource** [comment]
What @zoechi said ^. More info on http://blog.thoughtram.io/angular/2016/07/27/custom-form-controls-in-angular-2.html
