### ISSUE TITLE
Angular 2.0/Dart should support an import file which only has annotations

### ISSUE THREAD

**Issue by irfantusneem** [angular/angular#6860]
Angular 2.0/Dart should support an import file which only has annotations instead of having to import all of angular2 just to add @Injectable() to a class or add create an array of providers.  It may be negligible for the entire app but having a trivial test depend on all of angular2 is a bit of an overkill.

**Comment by zoechi** [comment]
Did you do any benchmarks that demonstrate it makes a difference?

**Comment by pkozlowski-opensource** [comment]
Obsolete as Dart-specific.
