### ISSUE TITLE
misleading link in quickstart (javascript version)

### ISSUE THREAD

**Issue by paolochiodi** [angular/angular#6862]
At the end of the quickstart guide there's a link to the tutorial named "Join us on the Tour of Heroes Tutorial!" that links to the tutorial url but shows the docs home.
Overall, the tutorial is not available in the javascript versions.

I think this is misleading, especially for newcomers: would be helpful to have a message explaining that the tutorial is only available in the typescript or, at least, remove the link from the quickstart.

**Comment by brandonroberts** [comment]
@paolochiodi there is documentation coming for the javascript versions. You should file this issue over at: https://github.com/angular/angular.io

**Comment by paolochiodi** [comment]
Thanks, will do
