### ISSUE TITLE
ViewEncapsulation.Native

### ISSUE THREAD

**Issue by aquinum6** [angular/angular#6864]
I wonder if this by design because it's working quite different in Polymer, and polymer is shadow DOM as well (isn't it?).

For example this code
file.ts:
```
import {Component, ViewEncapsulation} from 'angular2/core';

@Component({
    selector:'native-2',
    template:`
    <div class="class-1"> <!-- css class is working fine -->
        <native-encaps-component> <!-- really awesome component with ViewEncapsulation.Native -->
            <div class="class-2"> <!-- css class is not working in here -->
                Anything
            </div>
        </native-encaps-component>
    </div>
    `,
    styleUrls:['style.css'],
    encapsulation: ViewEncapsulation.Native
})
export class something{
}
```
style.css:
```
.class-1{
    //definition
}

.class-2{
    //definition
}
```

I have described it in comments which classes are not applied (css style). I wonder if that's not a mistake. How about I want to create 2 native components from which second is extending first one and in final app both will be used (not only the second one).

If I use Emulated encapsulation everything seems to be working fine but with Native it's not.

**Comment by zoechi** [comment]
`<native-encaps-component>` does have an `<ng-content>` or `<content>` tag?

**Comment by aquinum6** [comment]
Yes it has. It's <ng-content>

**Comment by zoechi** [comment]
Can you please try if `<content>` instead of `<ng-content>` produces a different result?

**Comment by PascalPrecht** [comment]
@aquinum6 looks like you have to rewrite your css then to match shadow boundaries, as your Light DOM is going to be projected.

**Comment by aquinum6** [comment]
@PascalPrecht yes if I add css to "inside" native everything is working fine.

@zoechi Sorry I had a lot on my plate recently. <content> works! I was so surprised. So what's the different between this two (except that is working :P)

**Comment by zoechi** [comment]
I assume the difference is that `<ng-content>` is an Angular feature and `<content>` is a browser feature. I also assume `<content>` only works with `ViewEncapsulation.Native` when the browser has native shadow DOM support or when full web-components polyfills are loaded.

If `<content>` works but `<ng-content>` doesn't it looks like a Angular bug. 
A Plunker with a repo case would be great.

**Comment by aquinum6** [comment]
@zoechi Please see plunker. I have created it with `<ng-content>`. As you can see 'Text-1-2' does not have any background colour and it should be green. But If you change `<ng-content>` to `<content>` (like you advised) all starts working fine.

[https://plnkr.co/edit/QipYsjn9imXTyX68tv4h?p=info](https://plnkr.co/edit/QipYsjn9imXTyX68tv4h?p=info)

**Comment by zoechi** [comment]
Actually to me it looks like `<content>` and `<ng-content>` are broken with `Native`.
For `Text 1-2` to get styled from `native-2.css` the selector needs to be `::content .span-2-1`. This works fine with `Emulated`.

**Comment by aquinum6** [comment]
That's even different issue. I had problem just with getting css from `native-1.css` to be applied to `.span-1-2`, which is style file applied to `native-1` component, so logically should work  (and `<content>` solved it).

But this one is working fine. If you change `<ng-content>` to `<content>`, style from `::content .span-2-1` is applied to new `<span>` that I just added.
[https://plnkr.co/edit/lvnCvm?p=preview](https://plnkr.co/edit/lvnCvm?p=preview)

**Comment by zoechi** [comment]
I also think that should work with `<ng-content>`, at least if it is supposed to work like `<content>`. I haven't seen any detailed docs.

**Comment by timkindberg** [comment]
Have you loaded the web-components polyfill? Perhaps its a bug that the polyfill has smoothed over?

**Comment by zoechi** [comment]
I tried in recent Chrome. I assumed that here no polyfills are required.

**Comment by timkindberg** [comment]
Yes but perhaps bugs in chrome implementation. You should try with polyfill to see.

**Comment by zoechi** [comment]
I didn't notice any difference after adding the polyfills `<script src="https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/0.7.2/webcomponents.min.js"></script>` (before the other script tags)

**Comment by zoechi** [comment]
See also https://docs.google.com/document/d/1BXUFVpImyWN7ynyPKehAesctP0UJTaDYbDTNVkarSeQ/edit about the difference of `<ng-content>` and `<content>`
