### ISSUE TITLE
Custom Exception Handler

### ISSUE THREAD

**Issue by tbragaf** [angular/angular#6865]
Hi all!

I've been trying to implement my own ExceptionHandler and followed the docs: https://angular.io/docs/ts/latest/api/core/ExceptionHandler-class.html

However, I am using ES6, so I can't implement interfaces.
I couldn't get the call method trigger :/

Also, the docs say "export class" but use it as an interface ("implements ExceptionHandler"), is this correct?

This is my ExceptionHandler:
```js
import { ExceptionHandler } from 'angular2/core';

export class WtExceptionHandler extends ExceptionHandler {
  call(error, stackTrace = null, reason = null) {
    console.log("hello");
  }
}
```

But my transpiled code shows 'call' method as:
```js 
call(error) { ... } // And stackTrace and reason comes from arguments. Could this be the issue?
```

Best regards,
tbragaf

**Comment by tbragaf** [comment]
Ok, now I managed to do it.
However, I predicted that a 404 error would trigger the error clause. Shouldn't it?
```js
subscribe(res => {}, error => { /*  */ })
```

Thank you,
tbragaf

**Comment by CaptainCodeman** [comment]
I had the same issue, this was my fix: https://github.com/angular/angular/issues/6565

I don't think an HTTP 404 is really an Exception in typical use - it's possibly normal code flow and something that you'd want to report to the user in that component with a message or a redirect to a not-found view. Are you really looking for Exception handling in this case or just logging?

If you want an exception you'd probably have to raise one. Maybe create a custom Http wrapper implementation where they are raised. I don't think that should be the default behaviour though.

**Comment by tbragaf** [comment]
@CaptainCodeman It is an HTTP 404 sent frm the API, as a not found route path.

**Comment by tbragaf** [comment]
<h2>Update:</h2>

I managed to find the problem.
The error was simply the console was not logging my errors...

This is my ExceptionHandler:
```js
import { ExceptionHandler } from 'angular2/core';

class _ArrayLogger {
  res = [];
  log(s: any): void { this.res.push(s); }
  logError(s: any): void { this.res.push(s); }
  logGroup(s: any): void { this.res.push(s); }
  logGroupEnd(){};
}

export class CustomExceptionHandler extends ExceptionHandler {
  constructor() {
    super(new _ArrayLogger(), true);
  }
  
  call(error, stackTrace = null, reason = null) {
    super.call(error, stackTrace, reason);
  }
}
```

But super.call() is not logging the errors to the console... 
Inside the source code, the original ExceptionHandler throws the error. I was expecting it to be caught by the console...

I call simply go with:
```js
call(error, stackTrace = null, reason = null) {
    try {
      super.call(error, stackTrace, reason);
    }
    catch(ex) {
      console.error(ex);
    }
  }
```
But it doesn't show the errors as it did before. Now i'm working on this and will provide with further info :)

**Comment by tbragaf** [comment]
Done!
Simply did this:
```js
class _ArrayLogger {
  res = [];
  log(s: any): void { this.res.push(s); }
  logError(s: any): void { this.res.push(s); }
  logGroup(s: any): void { this.res.push(s); }
  logGroupEnd() {
    this.res.forEach(error => {
      console.error(error);
    })
  };
}
```

Which is kinda obvious, but I'ld like to not create the _ArrayLogger myself.

**Comment by zoechi** [comment]
This won't work in Dart :-( You can't just pass any object (like `_ArrayLogger` when a `_Logger` is requested).

**Comment by tbragaf** [comment]
@zoechi But _Logger is not a class.
Still _logger property is of any type: https://github.com/angular/angular/blob/4e5cd1e558503aec87dd95e59337b31f261c941f/modules/angular2/src/facade/exception_handler.ts#L35

**Comment by zoechi** [comment]
You are right of course. Sorry for the noise.

**Comment by davidrensh** [comment]
perfect.

**Comment by quodroc** [comment]
I'm doing the following instead, but I don't like referencing the src folder like this.
```
import { ExceptionHandler } from 'angular2/core';
import { DOM } from 'angular2/src/platform/dom/dom_adapter';

export class CustomExceptionHandler extends ExceptionHandler {
  constructor() {
    super(DOM, true);
  }

  call(error, stackTrace = null, reason = null) {
    super.call(error, stackTrace, reason);
  }
}
```

For some reason `import { DOM } from 'angular2/platform/common_dom'` doesn't work even though common_dom.d.ts has 
```export { DOM, setRootDomAdapter, DomAdapter } from 'angular2/src/platform/dom/dom_adapter';```

**Comment by tbragaf** [comment]
@quodroc They are different modules, right?
The module `angular2/src/platform/dom/dom_adapter` exports 'DOM' and 'angular2/platform/common_dom' does not.

If the module is only accessible from /**/src you should not use it, since it should be used by angular only. Do you actually need it?

**Comment by Grusho** [comment]
@tbragaf Help me to undrestand plz. Why can't I do so:
`export class CustomExceptionHandler extends ExceptionHandler {

  constructor(_logger: any, _rethrowException?: boolean) {
    super(_logger, _rethrowException);
  }
...
`
I don't want to change any logic with logger or somewhat, for example, I need only to overrider call method. But I need to inject my global service in this CustomExceptionHandler class, and I thought I can do somthing like that:
`export class CustomExceptionHandler extends ExceptionHandler {

  constructor(_logger: any, _rethrowException?: boolean, @Inject(AppService) private appService: AppService) {
    super(_logger, _rethrowException);
  }
...
`
But that doesn't work. 
Thx in advance

**Comment by tbragaf** [comment]
@Grusho It should work, it seems reasonable.
Have you change the implementation on bootstrap?:
```js
bootstrap(Application, [
  provide(ExceptionHandler, { useClass: CustomExceptionHandler })
]);

```

Also take a look a the comment for logging. https://github.com/angular/angular/issues/6865#issuecomment-179894046

Is any error of any kind being thrown to the console?

**Comment by Grusho** [comment]
@tbragaf Thx for the reply!
I have the following error:
`zone.js:260Uncaught Cannot resolve all parameters for 'AppExceptionHandler'(?, Boolean, AppState @Inject(AppState)). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'AppExceptionHandler' is decorated with Injectable.`

Bootstraping:
 ```
 return bootstrap(App, [
      ...
      AppState,
      provide(ExceptionHandler, {useClass: AppExceptionHandler}),
      provide(XHRBackend, {useClass: AppXHRBackend})
  ])
```
App service:
```
import { Injectable, EventEmitter } from '@angular/core';

@Injectable()
export class AppState {
...
}
```
Besides, my VSCode syntax checker highlights me an error of using third required param after optional (`constructor(_logger: any, _rethrowException?: boolean, @Inject(AppState) private app: AppState)`). Sounds reasonable, but removing "?" doesn't matter. Realy, how can I get optional parameter that I should pass to super constructor and to declare injection as third param after that -_-

**Comment by zoechi** [comment]
@Grusho  Does `AppState` have any dependencies? The constructor is omitted (if any).

**Comment by jderose9** [comment]
I think this issue should be open still. It seems like there should be a simpler way to implement custom exception handling logic while still executing the default behavior. In my case I am only doing special handling on exceptions for a specific HTTP status code range... I'd still like the default behavior of logging everything to the console. The only way I could see to accomplish this was to copy the logger class implementation into my local project the way that @tbragaf has done.

**Comment by Grusho** [comment]
@zoechi No, it doesn't

**Comment by vicb** [comment]
Could you please move discussion / support request to gitter ? (We receive notifications for all new messages).

**Comment by mbrookson** [comment]
Is there any progress on this? I am also trying to write a custom exception handler and I want to inject Http to make it able to post the errors to a server but can't seem to do so.

**Comment by zoechi** [comment]
@mbrookson please read the comment just before yours ;-)

https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by jderose9** [comment]
@zoechi This isn't a support request. We shouldn't have to drag internal class implementation into our projects to override the global exception handler.

**Comment by mbrookson** [comment]
@jderose9 I have actually managed to do this now by using jQuery. Seems to be a good solution because if the angular application crashes it might not be able to continue using the Http class, however it is able to still hit the error handler and call $.ajax without being tied to angular

**Comment by tbragaf** [comment]
I've just upgraded to rc4, and as @mbrookson said, the application now crashes.

@zoechi Any workaround I can use for now? Or should the upgrade remain pending?

**Comment by mbrookson** [comment]
@tbragaf If you use another library (such as jQuery) to handle sending the exception then it isn't relying on the angular framework (which has crashed) and should be able to continue? Works for me.

**Comment by ndamnjanovic** [comment]
Does someone have an idea, why my custom implementation fails with code below?
I would like to have different behavior whether I'm in production or in dev environment. 
But somehow, calling method from super class fails with
`zone.js:463 TypeError: Cannot read property 'logGroup' of undefined`

```
import { Injectable, ExceptionHandler } from 'angular2/core';

export class CustomExceptionHandler extends ExceptionHandler {

  call(error, stackTrace = null, reason = null) {

    if (ENV === 'production') {
        // send email
    }

    super.call(error, stackTrace, reason); <---- this line breaks
  }
}
```

**Comment by tbragaf** [comment]
@ndamnjanovic
The construtor cannot be empty. And since it is empty, the loggroup property is not defined. Check above samples

**Comment by ndamnjanovic** [comment]
@tbragaf thanks for the reply. I saw the examples above, I just thought that if I omit constructor in derived class, default constructor with super() call will be created.
Am I wrong? Cause looks like it's not happening.

**Comment by tbragaf** [comment]
@ndamnjanovic
I don't know how that works on typescript, since I don't use it.
But the construtor needs an Logger, which is not passed as a dependency for the DI to instanciate, but rather instanciated manually.
I know it seems unusual, but copy the logger from the source code, and call it inside your super call.

**Comment by tbragaf** [comment]
@mbrookson
By the way, my problem was probably different and it is now working with NG only.
What happened on my case it that an unsubscribe is called. A function called tryOrUnsub which  triggered the unsunscribe and broke some behaviour.
Thank you!

**Comment by liquidboy** [comment]
does anyone have a way to do this on RC6+ ?  the ExceptionHandler is nolonger public

**Comment by zakhenry** [comment]
@liquidboy `import { ErrorHandler } from "@anguar/core"` instead

**Comment by samipadwani** [comment]
ExceptionHandler  has been changed to ErrorHandler and call(error) has been changed to handleError(error)
