### ISSUE TITLE
ngForTrackBy use case

### ISSUE THREAD

**Issue by johnpapa** [angular/angular#6872]
I see this unit test, but I cannot seem to get ngForTrackBy to work for my sample. https://github.com/angular/angular/pull/6779

https://github.com/angular/angular/blob/cee2318110eeea115e5f6fc5bfc814cbaa7d90d8/modules/angular2/test/common/directives/ng_for_spec.ts#L364-L402

I added `[ngForTrackBy]="customTrackBy"` to my element in the template. Then I added the `customTrackBy` function the way the unit test shows it. But I am getting this error:

```
EXCEPTION: Template parse errors:
Can't bind to 'ngForTrackBy' since it isn't a known native property ("    <div class="mdl-cell mdl-cell--3-col"
        *ngFor="#character of characters | async"
        [ERROR ->][ngForTrackBy]="trackBy"
        (click)="gotoDetail(character)">

"): DashboardComponent@6:8
```

It seems it wants me to declare `ngForTrackBy` to the component, but I do not see where it is exported from any module by Angular. Nor is the unit test I referenced doing that.

What else is needed?

cc // @kara @wardbell

**Comment by kara** [comment]
@johnpapa  It looks like there could be a typo in the syntax you're using. If you're using the asterisk rather than a template element, you'll need to put the trackBy inside the quotes:

```
<div *ngFor="#character of characters | async; trackBy:trackBy">
    ....
</div>
```

You can use `[ngForTrackBy]` too, but it de-sugars to:

```
<template ngFor #character [ngForOf]="characters" [ngForTrackBy]="trackBy">
...
</template>
``` 

Try that and let me know if you're still getting the error?

**Comment by CaptainCodeman** [comment]
I'm using it like this which seems to work (well, the `customTrackBy` function gets called at least):

`*ngFor="#photo of photos" *ngForTrackBy="customTrackBy" `

I think the unit test is using the template syntax which is why it has the `[ngForTrackBy]` instead.

**Comment by johnpapa** [comment]
@kara thank you that worked.

I can either use the * `*ngFor="#character of characters | async" *ngForTrackBy="customTrackBy"`

or I can use `*ngFor="#character of characters | async ; trackBy:customTrackBy"`

It did not occur to me to use the * as I figured it was not a structural directive, but it makes sense as its tied to ngFor.

The other syntax with the semicolon ... I never would have guessed that as I have not sen it before. Is that new?

**Comment by CaptainCodeman** [comment]
> The other syntax with the semicolon ... I never would have guessed that as I have not sen it before. Is that new?

It's in the docs (https://angular.io/docs/ts/latest/api/common/NgFor-directive.html) and I think it's been there a while. I've only used it for the `index` part though - didn't think of it for the trackBy but it makes sense.

**Comment by johnpapa** [comment]
ah, yes, i use that with #index (variables) too.

what threw me off was the pipe and A1 experience :)

thanks again

**Comment by kara** [comment]
Yeah, we could probably add some clarity to the documentation. I'm editing the `ngFor` section soon to document `ngForTrackBy`, so I'll see if I can make it clearer.

**Comment by Ofer-Gal** [comment]
How do you get the "first" and "last" ? 
I did customTrackBy(index: number, obj: any,last: boolean): any {
     debugger;
    return index;
  }
but last was always undefined

**Comment by BrentMShanahan** [comment]
Apparently `*ngForTrackBy="customTrackBy"` is no longer supported 
but can still be utilized with `*ngFor="let item of items | pipe ; trackBy:customTrackBy"`

I just updated to 2.0.0-rc.4 and got the following error for my `*ngForTrackBy` attributes:
`Can't have multiple template bindings on one element. Use only one attribute named 'template' or prefixed with *`

**Comment by Yimiprod** [comment]
Since it's not well documented here https://angular.io/docs/ts/latest/api/common/index/NgFor-directive.html (no exemple, no use case). Is it possible to do this:
```
<div *ngFor="let item of myCollection; trackBy:item.id">{{ item.name }}</div>
```
At the moment the only way to not get an error is by doing `trackBy:item?.id` but it look wrong, and i'm not sure how to verify it work.
