### ISSUE TITLE
Angular and TypeScript with different folder structure?

### ISSUE THREAD

**Issue by ffMathy** [angular/angular#6874]
Today, Angular 2 only works with TypeScript and SystemJS if you have a very specific folder structure.

See these two questions (not made by me) for others with the same problems (the proposed solutions don't work either).

- http://stackoverflow.com/questions/34119720/angular2-0-in-subdirectory-systemjs-cant-import-angular-components
- http://stackoverflow.com/questions/34010970/running-angular2-in-subdirectory

**Comment by jmcota** [comment]
The problem arises with the most recent version of SystemJS (0.19.18).

Yesterday I was using SystemJS 0.19.17 and angular bootstrapping works well.

Now I have a 404 bootstrap.js not found when I boundle my js code in one file.

**Comment by robwormald** [comment]
Can you expand on this? You pretty much have total freedom as to how to organize your application, its generally just a matter of appropriately configuring your SystemJS config.js file.

Note that there is a distinct difference between typescript's compilation step and systemJS *runtime* configuration, and they have very little to do with each other.

See https://github.com/systemjs/systemjs/blob/master/docs/config-api.md for further information.

**Comment by ffMathy** [comment]
Aren't the two questions describing the exact situations?

**Comment by robwormald** [comment]
SystemJS configuration is out of scope for Angular2, as there's nothing specific to angular2 that would preclude basically any folder structure you'd like.

Closing this as github issues should be kept for issues with the framework. If you have how-to question, please take it to https://gitter.im/angular/angular
