### ISSUE TITLE
Add support for reading static attributes on Components

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#688]
It would be very useful to read a components static attributes (not bindings). This is probably a prerequisite for to #633. There are many use-cases for this.

#### Example use case: imitating native input api
Standard radio buttons are put into one single-input-can-be-checked group with the name attribute:
```html
<label>
  <input type="radio" name="instrument">
  Guitar
</label>
<!-- some arbitrary html -->
<label>
  <input type="radio" name="instrument">
  Trombone
</label>
```
If a component author wants to support the same api on a custom radio button, the author needs to be able to read the name attribute. There's usually not a need, though, to create a binding on the property.

**Comment by mhevery** [comment]
/cc: @vsavkin I think this is a dup of #622

**Comment by mhevery** [comment]
@pkozlowski-opensource Please add this to your list.

**Comment by mhevery** [comment]
moved text to #622 and closing this issue because of duplicate
