### ISSUE TITLE
comma separated list in ViewQuery factory only returning first match in beta.0 - beta.3

### ISSUE THREAD

**Issue by L-Gomez** [angular/angular#6881]
@ViewQuery("someEl1, someEl2") _elements:QueryList<ElementRef>)

Plnkr - http://plnkr.co/7pgGhjy2oPoy7Ha2eSIZ

https://angular.io/docs/ts/latest/api/core/Query-var.html

**Comment by L-Gomez** [comment]
Plnkr - http://plnkr.co/7pgGhjy2oPoy7Ha2eSIZ

https://angular.io/docs/ts/latest/api/core/Query-var.html

**Comment by ericmartinezr** [comment]
@L-Gomez yes, you're right, there should be no spaces between the commas. This is covered by @laco0416 's PR for [ViewChild and others docs](https://github.com/angular/angular/pull/7174). I'm pretty sure he sent a PR to fix the issue with the commas as well but I can't find it anymore.

**Comment by laco0416** [comment]
@L-Gomez @ericmartinerz
I have the patch to dix this in my local machine. but I'm waiting for merging the PR of docs because those may occur conflicting :)
