### ISSUE TITLE
Zone is not defined in Global

### ISSUE THREAD

**Issue by GreenToast** [angular/angular#6884]
Hey,

since I installed the new Beta 3, I have the error:

"Property 'zone' does not exist on type 'Global'"

. Coming out of the Zone-package, where the Typescript-dependencies in the zone-js-library are not fulfilled in all files under "zone.js/lib/browser.

Can you provide me any help here? haven't found anything in the Changelog regarding this.

**Comment by zoechi** [comment]
I guess you need to inject `zone: NgZone` to your constructor and use it this way.

**Comment by PascalPrecht** [comment]
@zoechi `NgZone` is a thing you can inject but it's not exposed on the global scope. @GreenToast talks about `Zone` here.

@GreenToast That's interesting. Can you give more information on how `zone.js` is installed in your project? It's super important that it's loaded via `<script>` tags as soon as possible.

**Comment by GreenToast** [comment]
My project was originally copied form some Angular2-templates on angular.io and is builded with webpack. I imported direct those two parts of zone in my boot.ts

import 'zone.js/lib/browser/zone-microtask';
import 'zone.js/lib/browser/long-stack-trace-zone';

and the typescript problem seem to be in the source.files there, but works when I switch to include the builded zone-lib with

import 'zone.js';

which is loading the d.ts and js files.

**Comment by gonzofish** [comment]
I'm getting the following

    ERROR in ./~/zone.js/lib/browser/zone.ts
    Module parse failed: /Users/gonzofish/webdev/designer-ng2-redux/node_modules/zone.js/lib/browser/zone.ts Line 1: Unexpected token
    You may need an appropriate loader to handle this file type.
    | import * as core from '../core';
    | import * as browserPatch from '../patch/browser';

Trying to figure out why, though...

**Comment by gonzofish** [comment]
@GreenToast thanks to https://github.com/AngularClass/angular2-webpack-starter, I was able to get around the issue by using require to pull in the compiled zone-microtask with:

    require('zone.js/dist/zone-microtask');

**Comment by GreenToast** [comment]
@gonzofish My mentioned with import 'zone.js'; woks only  with zone.js "0.5.13". It throws errors, when you install it on npm, because the "0.5.11" is referenced by angular2 but it contains a build folder with the builded files. That allows you to use the import syntax again.

**Comment by PascalPrecht** [comment]
Again, `zones.js` should *always* be included as `<script>` tag via HTML and not loaded via module loader as this might affect its monkey-patching

**Comment by gonzofish** [comment]
Understood, @PascalPrecht!
