### ISSUE TITLE
Question: No way to replace default injector?

### ISSUE THREAD

**Issue by remojansen** [angular/angular#6885]
Hi guys, 

I'm working on my a IoC container and I would like to see how well would it work with Angular 2.0 however I found that it seems to be not possible to replace Angular DI with my IoC container.

I found the following in the documentation:

> When the app developer invokes bootstrap() with the root component MyApp as its argument, Angular performs the following tasks:

> - It uses the component's selector property to locate the DOM element which needs to be upgraded into the angular component.
> - It creates a **new child injector** (from the platform injector). Optionally, **you can also override the injector configuration for an app by invoking bootstrap with the componentInjectableBindings argument**.
> - It creates a new Zone and connects it to the angular application's change detection domain instance.
> - It creates an emulated or shadow DOM on the selected component's host element and loads the template into it.
> - **It instantiates the specified component**.
> - Finally, Angular performs change detection to apply the initial data providers for the application.

So the solution seems to be to create my own `bootstrap` function which is not ideal. Do you guys provide some way to replace angular DI with another IoC container with ease? Something like [`IDependencyResolver`](https://msdn.microsoft.com/en-us/library/system.web.http.dependencies.idependencyresolver(v=vs.118).aspx) resolver in ASP .net.

Thanks!

**Comment by tbosch** [comment]
Hi,
FYI, we will soon Codegen all of our injectors to optimize initial
application load time. Ie generate code that calls "new" directly. Then the
application code won't even use an injector at all.

Replacing Angulars injectors is infeasible, sorry.

**Comment by remojansen** [comment]
Hi @tbosch do you have a link/resource so I can learn more about the process that you are mentioning please? thanks

**Comment by tbosch** [comment]
This PR will soon be merged: https://github.com/angular/angular/pull/6567

It will generate code that news up directives directly...

**Comment by remojansen** [comment]
If the compiler do this kind of code generation and optimizations, writing ES5 or ES6 is really not an option anymore right? I mean you can do it but all the code generation and optimizations would become manual work instead of the compiler work?

**Comment by tbosch** [comment]
You can write your source code in ES5, ES6 or TS. Angular will only codegen
code that calls your code, e.g. the template of a component.
