### ISSUE TITLE
2.0.0-beta3: zone.js 0.5.11 requires tsd in its postinstall step

### ISSUE THREAD

**Issue by hokkaido** [angular/angular#6887]
Since this is a peer dependency of 2.0.0-beta3: https://github.com/angular/zone.js/issues/240

In order to be installed, Angular 2.0.0-beta3 now effectively requires a globally installed `tsd`, which isn't desirable.

**Comment by mrowles** [comment]
Also seems to state that tsd is deprecated when trying to install: https://github.com/DefinitelyTyped/tsd/issues/269

`tsd@0.6.5: TSD is deprecated in favor of Typings (https://github.com/typings/typings) - see https://github.com/DefinitelyTyped/tsd/issues/269 for more information`

**Comment by theodorejb** [comment]
See angular/zone.js#240

**Comment by bourdeau** [comment]
Same here

**Comment by valorkin** [comment]
+1 https://travis-ci.org/valor-software/ng2-bootstrap/jobs/107475338

**Comment by dsebastien** [comment]
+1

**Comment by DiegoYungh** [comment]
+1 this should be fixed before ng2 beta.4 release or else the nightmare will continue

**Comment by alexeagle** [comment]
fixed in zone.js@0.5.14 which is the peerDependency of angular2@2.0.0-beta.6
