### ISSUE TITLE
Missing jasmine matchers in 2.0.0-beta2

### ISSUE THREAD

**Issue by filipesilva** [angular/angular#6888]
Upgrading from `2.0.0-beta1` to `2.0.0-beta2` causes a compilation error when using Jasmine matchers.

The following code does not compile anymore, `toBe` and `toEqual` matchers seem to be missing.

![image](https://cloud.githubusercontent.com/assets/4172079/12817039/c4390bde-cb47-11e5-978d-25fd93bda53a.png)

**Comment by ericmdantas** [comment]
Dup of #6817.

I solved this by installing the typings for jasmine manually, but I'd like to know if that's the case moving forward or if that's a bug.

**Comment by filipesilva** [comment]
Right you are. I should have searched better, thank you.

**Comment by mithun-daa** [comment]
@ericmartinezr Installing the typings manually did not resolve the issue for me:
````
typings install jasmine --save --ambient
````

What am I missing?

**Comment by ericmartinezr** [comment]
I didn't say anything! :joy:

**Comment by ericmdantas** [comment]
@ericmartinezr, that's what we get for having similar usernames, :laughing: 

@mithun-daa, at the time I installed it via `tsd`, not the brand new `typings`. I'll give it a try and I'll let you know.

**Comment by ericmdantas** [comment]
@mithun-daa, so I pushed the modification [here](https://github.com/ericmdantas/angular2-typescript-todo/commit/2dea1f522416159af0c31302bd8a95ddde808332).

Basically, all I had to do was:

- run `typings install jasmine --ambiente -so`
- in my test files, I had to change all `typings/tsd.d.ts` to `typings/main.d.ts`

**Comment by mithun-daa** [comment]
Thanks @ericmdantas I will check it out. Sorry about the username confusion.

**Comment by mithun-daa** [comment]
Sweet! that fixed it. Thanks @ericmdantas

**Comment by ericmdantas** [comment]
:+1:
