### ISSUE TITLE
Bindings in template are not updated in Safari.

### ISSUE THREAD

**Issue by tandu** [angular/angular#6889]
In Safari text is always black which is wrong, in other browsers text is changing its color to red when `isLoaded` is set to `true`.

https://plnkr.co/edit/A9HTfJhs8MU9KmKPq00C?p=preview

**Comment by robwormald** [comment]
this looks to be zone related. in the interim (and probably, just generally) using the `.addEventListener('load', fn)` method works properly.

**Comment by tandu** [comment]
Yes, it solves the issue, thank you. I think my example should be debugged anyway as it might reveal some other hidden bugs in angular2.

**Comment by ahauser31** [comment]
A very similar issue breaks my entire app on Safari / Safari Mobile... In my case, I use a service that returns subjects (observables) to components and updates (using `.next()` ) the components with new values (the service gets new values from a server via `http.get()` ).
This works fine on Chrome and FF, but not on Safari. If I debug or put `console.log()` in the `.subscribe` functions in the components, I see the new values arriving, but they are not updated in the views in Safari.

I tried to build a plnkr that shows this for a the last few hours, but haven't managed to replicate this in isolation so far. But it seems to me to be the very same issue @tandu has...
The views only get updated if I cause some event to fire, e.g. clicking a button in the view that is bound to a function of the component.

@robwormald : Can you explain more? I unfortunately can't follow your reply. Is this a bug in Safari or a bug in Angular's change detection? How can I work around it or is this something that is investigated?
(I already tried enclosing the code in `setTimeout` blocks, but that only helps partially in some cases and is not a good solution, IMHO...)

Thanks a lot for any pointers, this is driving me nuts...

**Comment by ahauser31** [comment]
@tandu @robwormald or anyone else with this issue: Do you have any news on that problem or some further pointer on how to avoid it / work around it? As mentioned, I'm using timeouts as a workaround, but that solution fails on some iOS devices for unknown reasons. I do not understand why not more people have that issue, as I'm hardly doing anything exotic here - and this bug is serious enough to cripple the entire framework, as the UI just does not get refreshed without the user triggering an event...

**Comment by tandu** [comment]
As @robwormald suggests use `.addEventListener('load', fn)` instead of `.onload = fn`.

**Comment by aconfee** [comment]
Hello!

I am seeing this issue as well. Same scenario, I'm binding a function to an images onload function and in Safari only, the changes onload makes to the component's properties is not digested. 

I applied the recommended workaround above, using .addEventListener('load', fn) instead, and it works. This, however, definitely seems like a bug. Will this be addressed? 

As a more general Javascript question, why is it better practice to use .addEventListener than onload?

Thanks!

P.S. Here is the code that causes the issue in Safari: https://gist.github.com/aconfee/b3a54e746d21448db5327063dfff209d

**Comment by mhevery** [comment]
Here is the updated code to the latest Zone: https://plnkr.co/edit/QRY99XlPaH3DyakQbRKN?p=preview

The issues is that `Image.prototoype.onload` is not patched is `Safari`

**Comment by mhevery** [comment]
The workaround is:

```
https://plnkr.co/edit/QRY99XlPaH3DyakQbRKN?p=preview
```
var zone = Zone.current;
let img = new Image();
img.src = "https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png";
img.onload = Zone.current.wrap(_=> {
   ...
});
```
```
