### ISSUE TITLE
My angular2 app is very slow

### ISSUE THREAD

**Issue by xyxabcdiy** [angular/angular#6890]
Sorry, my English is very poor.
I have bult a community website by angular2-beta.2 and bootstrap. But I found if my website run long time and not refresh, It will be very very slow, any css animation in my site can't show smoothly.
The same website built only by jQuery and bootstrap dosen't have this problem.
I feel very  puzzled, can anyone help me to resolve this problem? Thanks a lot !

**Comment by ericmdantas** [comment]
It's really hard to help you without some context and some code.

Consider creating a plnkr with some core functionalities or some stuff you think it is the bottleneck.

**Comment by zoechi** [comment]
Browser devtools should also allow to investigate where the ressources are used.

**Comment by xyxabcdiy** [comment]
Sorry, I don't known how to describe it. This problem dosen't show any error message
