### ISSUE TITLE
RouteParams not imported in RouteParams example.

### ISSUE THREAD

**Issue by amberwoodrow** [angular/angular#6891]
In the [current example](https://angular.io/docs/ts/latest/api/router/RouteParams-class.html#!#example) import looks like this:
`import {Router, ROUTER_DIRECTIVES, ROUTER_PROVIDERS, RouteConfig} from 'angular2/router';`
But should be:
`import {Router, ROUTER_DIRECTIVES, ROUTER_PROVIDERS, RouteConfig, RouteParams} from 'angular2/router';`

**Comment by brandonroberts** [comment]
There is a PR in to fix this. See #6805

**Comment by vicb** [comment]
obsolete - former router
