### ISSUE TITLE
DefaultIterableDiffer and CollectionChangeRecord should be made public

### ISSUE THREAD

**Issue by zoechi** [angular/angular#6892]
from 

https://github.com/angular/angular/blob/master/modules/angular2/src/core/change_detection/differs/default_iterable_differ.ts

to be exported in 

https://github.com/angular/angular/blob/master/modules/angular2/src/core/change_detection.ts

They are returned from `IterableDiffer` which I use in custom change detection but I can't cast (without linter warnings) to actual types because they are not exported.

**Comment by pkozlowski-opensource** [comment]
`DefaultIterableDiffer` is already exported: https://angular.io/docs/ts/latest/api/core/index/DefaultIterableDiffer-class.html

`CollectionChangeRecord` as well: https://angular.io/docs/ts/latest/api/core/index/CollectionChangeRecord-class.html

Both APIs seem public and marked as stable.
