### ISSUE TITLE
Http Client dev guide: handleError's arg isn't a Response

### ISSUE THREAD

**Issue by kellerapps** [angular/angular#6894]
private _heroesUrl = 'app/heroes';
Change it to 'foo' to force an error. When using lite-server & the in-mem API server, handleError's arg is not a Response.

As an exercise, I added an error message to AppComponent:

 getHeroes() {
        this.startLoading();
        this._heroService.getHeroes().subscribe(
            heroes => {
                this.heroes = heroes;
                this.stopLoading();
            },
            error => {
                this._errMsg = <any>error;
                this.stopLoading();
            });
    }

HeroService.handleEvent(): "this" doesn't seem to be the service so:

catch(this.handleError.bind(this))

in-mem API server's default delay is .5sec, which makes angular 2 feel sluggish. Unfortunately, if you set it to 0, the server rounds it up to 500. So set it to 1 in main.ts:

bootstrap(AppComponent, [HTTP_PROVIDERS, LoggerService,
    // in-memory web api providers
    provide(XHRBackend, { useClass: InMemoryBackendService }), // in-mem server
    provide(InMemoryBackendConfig, { useValue: { delay: 1/*msec -- zero is rounded to 500*/ } }),
    provide(SEED_DATA,  { useClass: HeroData }) // in-mem server data
]);

**Comment by zoechi** [comment]
Wrapping code blocks in ``` makes it so much more readable ;-)

**Comment by pkozlowski-opensource** [comment]
This issue is not clear at all, doesn't have a plunker and is likely obsolete. Please open a new issue following the bug report template if you still face problems in the latest version.
