### ISSUE TITLE
No selector specified results in `<undefined>` component.

### ISSUE THREAD

**Issue by Munhoziii** [angular/angular#6900]
Not specifying a selector for a component will render the component as `undefined` during the prerendering step of Universal Angular 2.

<img width="581" alt="screen shot 2016-02-04 at 3 16 32 pm" src="https://cloud.githubusercontent.com/assets/6660156/12832978/5be56126-cb52-11e5-8013-c8f004810289.png">

**Comment by zoechi** [comment]
Related to #1662

**Comment by pkozlowski-opensource** [comment]
Fixed via 9b39e499ace74addf7edbb0202dd261de038b32b
