### ISSUE TITLE
Dart doesn't do [class]

### ISSUE THREAD

**Issue by kwalrath** [angular/angular#6901]
If you use `[className]` instead, it works.

Misko says, "We alias `[class]` to `[className]` so it looks like the alias is broken in Dart."

Example:

```
// In Dart code:
class AppComponent {
  //...
  String badCurly = 'bad curly'; // Works with [className].
  //...
}

<!-- In HTML: -->
<div class="bad curly special">Bad curly special</div>

<!-- reset/override all class names with a binding  -->
<div class="bad curly special"
     [className]="badCurly">Bad curly</div>
```

If you change `[className]` to `[class]`, it stops working.

See the whole sample in https://github.com/angular/angular.io/pull/758. It's based on the [TypeScript Template Syntax page](https://angular.io/docs/ts/latest/guide/template-syntax.html), which has a [plunkr for its sample](https://angular.io/resources/live-examples/template-syntax/ts/plnkr.html).

**Comment by kwalrath** [comment]
cc @mhevery

**Comment by pkozlowski-opensource** [comment]
`class` -> `className` seems to be properly mapped in Dart (https://github.com/angular/angular/blob/e7470d557df0400a812d84551524970cb5f12eee/modules/angular2/src/platform/browser/browser_adapter.ts#L7) so there is sth else that must be going here.

I suspect that it might be interference of the `class` and `[class]` used on the same element. @kwalrath would you mind changing to `<div [class]="badCurly">Bad curly</div>`  and see if classes from the `badCurly` are applied?

**Comment by kwalrath** [comment]
Nope, they aren't applied. Here's what I see with `<div [class]="badCurly">Bad curly</div>`:

![image](https://cloud.githubusercontent.com/assets/2164483/13445202/bae6724c-dfbf-11e5-89c9-eb9e0270f6b9.png)

Here's what I see with `<div class="bad curly special"
     [class]="badCurly">Bad curly</div>`:

![image](https://cloud.githubusercontent.com/assets/2164483/13445213/cab27306-dfbf-11e5-907d-a0e750e19abc.png)

**Comment by kwalrath** [comment]
And, just to be complete, here's the correct version that I see when I use `<div class="bad curly special"
     [className]="badCurly">Bad curly</div>`:

![image](https://cloud.githubusercontent.com/assets/2164483/13445416/d235b380-dfc0-11e5-822c-67a4398c8ee3.png)

**Comment by kwalrath** [comment]
You can see the complete code in the [template-syntax example](https://github.com/angular/angular.io/tree/master/public/docs/_examples/template-syntax/dart). The HTML code is in [lib/app_component.html](https://github.com/angular/angular.io/blob/master/public/docs/_examples/template-syntax/dart/lib/app_component.html), and the Dart code is in [lib/app_component.dart](https://github.com/angular/angular.io/blob/master/public/docs/_examples/template-syntax/dart/lib/app_component.dart).

**Comment by pkozlowski-opensource** [comment]
Obsolete as Dart-specific.

**Comment by kwalrath** [comment]
This issue was moved to dart-lang/angular2#43
