### ISSUE TITLE
DOM is not initialized

### ISSUE THREAD

**Issue by zoechi** [angular/angular#6904]
http://plnkr.co/edit/1LImWdksAoHEuJE8CKFT?p=preview

This works fine in Dart but in this Plunker `DOM` is not initialized.

It should be initialized by the `PLATFORM_INITIALIZER`
https://github.com/angular/angular/blob/e1bf3d33f8a1fa05a832b9b7ee1300ef9862fd0b/modules/angular2/src/platform/browser_common.ts#L91  
using   https://github.com/angular/angular/blob/2c8fcec432ce352d6d514304445dd06a29aed364/modules/angular2/src/core/dom/dom_adapter.ts#L5

Does this need some additional step to get it initialized in TS?

**Comment by PascalPrecht** [comment]
It shouldn't. But I also don't think you should use `DOM` directly.

What you're trying to do in your plunk is better done by using host listener with targets:

```
@Component({
  host: [
    'window:click': 'doSth()'
  ]
})
class Cmp {
  doSth() { }
}
```

This also deregisters the event listener once that component is destroyed.

**Comment by zoechi** [comment]
I saw that already a while ago. Thanks for the hint!

**Comment by qdouble** [comment]
@PascalPrecht that method works for listening to window events, but what if you need to set scrolling? Looking for a web worker safe solution.

**Comment by ericmartinezr** [comment]
@qdouble use Renderer#listenGlobal, like

renderer.listenGlobal('window', 'scroll', callback)

**Comment by qdouble** [comment]
@ericmartinezr that seems to work for listening to the scroll event and performing a function....which `host: {'window:click': 'scrollFun()}'` but doesn't adjust scrolling.

The biggest issue right now is if you click a link at the bottom of a page and you redirect, without accessing window.scrollTo(0,0) or some preferable web worker safe method, you'd enter the next page at the bottom...unless there is some other way to get different behavior?

**Comment by DevVersion** [comment]
While I created that issue (http://stackoverflow.com/questions/34686856/angular-2-0-beta-access-dom-adapter-browserdomadapter) and it got transferred into GitHub, I used the actual `nativeElement` as a workaround.

So now I wanted know, if there is any progress here:
- Can someone explain the intention of the `initDomAdapter `?
  - Should the `BrowserDOMAdapater` be initialized by default?

**Comment by nupplaphil** [comment]
I stepped through the BrowserDomAdapter and found out that when I try to set DOM with "BrowserDomAdapter.makeCurrent()", the DOM was leaving "undefined".

The strange thing is that the isBlank method in the "setRootDomAdapter" gets the BrowserDomAdapter as parameter so returned "false" (meaning DOM is already set). But outside, the DOM was undefined so nothing was set.

Maybe a scope problem during the initialization?

**Comment by zoechi** [comment]
Seems related #7561

**Comment by guaido79** [comment]
@nupplaphil Have you found a solution? I have exactly yhe same problem

**Comment by youpage** [comment]
same here, I am doing this with beta 12:
`this.headElement = DOM.query('head');`
and got **TypeError: Cannot read property 'query' of null**

**Comment by TheLarkInn** [comment]
Coming across this issue while trying to create a custom DomEventsPlugin. DomEventsPlugin imports DOM in the same way to perform `DOM.getGlobalEventTarget(target);` and other methods.

**Comment by vicb** [comment]
obsolete
