### ISSUE TITLE
[Router] Add a getter for the list of configured routes

### ISSUE THREAD

**Issue by youdz** [angular/angular#6908]
Right now, the router provides ways to dynamically configure routes, either through the Router or the RouteRegistry itself. This is great.
But one problem is that you can even use RouteRegistry to add routes to the root component from any child component, with `ROUTER_PRIMARY_COMPONENT` and `RouteRegistry.config(parentComponent: any, config: RouteDefinition)`.

In an ideal world, I would always know what routes are configured at any time, but I'm still searching for that ideal world. :-(
So I would like to have, in the Router or RouteRegistry API, a way to list the currently configured routes on a component. At the moment, the only way to do this is to look into an internal field, `RouteRegistry._rules`.

I put together a [minimal example](https://plnkr.co/edit/Eg5m70GtxWGvmXB3SH9f?p=preview) of dynamic routing on plunker. _Please ignore the few bad ideas, like using route names for display when they're supposed to be CamelCase. The point of the example is to be simple._
If you check `src/app.ts`, you will see that in this example I can easily maintain the list of routes myself.
But if anyone can add routes to the root component from anywhere, the only way for me do maintain it would be to force all the devs on the project to go through a middleware service to add routes. While feasible, it would be much better if they could simply use the native Router API and I could just call something like `Router.getRoutes()`, to get a read-only list of all configured routes at the time of my call.

I'm open to any suggestion on better practices or alternative solutions to this problem. I don't think this use case is too specific, but correct me if I'm wrong. :-)
Thanks.

**Comment by vicb** [comment]
obsolete - former router
