### ISSUE TITLE
HelloWorld example in Dart doesn't work

### ISSUE THREAD

**Issue by jamm** [angular/angular#691]
Just built project, both `gulp serve.js.dev` and `gulp serve/examples.dart` launch servers, `localhost:8000/examples/src/hello_world/` works fine but `localhost:8080/hello_world` returns
```
404 Not Found
Could not find asset web/hello_world in package examples.
```
And in console:
```
$ gulp serve/examples.dart
Dart SDK detected
[02:18:23] Using gulpfile ...angular/gulpfile.js
[02:18:23] Starting 'serve/examples.dart'...
Loading source assets... 
Serving examples web on http://localhost:8080
Build completed successfully
[web] GET /hello_world → Could not find asset examples|web/hello_world.
[web] GET /favicon.ico → Could not find asset examples|web/favicon.ico.
```

**Comment by jamm** [comment]
Now I can't build project because last version in brew is 1.8.5, but 1.9 is required...
If somebody knows, please let me know how to install Dart 1.9

**Comment by kevmoo** [comment]
`brew tap kevmoo/kevmoo`
`brew install dart-editor --devel`

**Comment by jamm** [comment]
@kevmoo thanks!

But now new error:
https://gist.github.com/jamm/f0329c57dec667a9aa43

It's not urgent for me, not so important...

**Comment by kevmoo** [comment]
Try running `pub global activate dart_style`

What does it say?

**Comment by jamm** [comment]
```
Package dart_style is currently active at version 0.1.3.
Resolving dependencies... (2.2s) 
+ analyzer 0.23.0 (0.24.0-dev.1 available)
+ args 0.12.2+6
+ dart_style 0.1.5
+ logging 0.9.3
+ path 1.3.3
+ source_span 1.0.3
+ stack_trace 1.2.1
+ watcher 0.9.4
Downloading dart_style 0.1.5...
Downloading analyzer 0.23.0...
Downloading stack_trace 1.2.1...
Precompiling executables... 
Loading source assets... 
Precompiled dart_style:format.
Activated dart_style 0.1.5.
Installed executables dartfmt and dartformat.
```

and `gulp build` finally finished build, but 
http://localhost:8080 still gives "404", even in Chromium with Dart.

**Comment by kevmoo** [comment]
Did you try `localhost:8080/hello_world` per the readme?

**Comment by jamm** [comment]
@kevmoo yes, same result :(

**Comment by jamm** [comment]
```
404 Not Found

Could not find asset web/hello_world in package examples.
```
