### ISSUE TITLE
[Router] router-outlet does not update for routes to same component

### ISSUE THREAD

**Issue by rizwanhussain-vteams** [angular/angular#6910]
For some reason when there are multiple routes for same component, the router-outlet is only updated after a page refresh. Here is how they are defined:

    @RouteConfig([
      {path:'/route1', name: 'Route1', component: RouteComponent},
      {path:'/route2', name: 'Route2', component: RouteComponent},
      {path:'/route3', name: 'Route3', component: RouteComponent}
    ])
   
I see the xhr request when page is first loaded but after clicking the links, the view is not updated, there is no xhr request or console error either. But if i use different component for each route, it works fine.

**Comment by brandonroberts** [comment]
If you use navigate to a route with the same component, the route component will be reused and not re-instantiated every time. If you don't want the component to be reused, use the lifecycle hook: https://angular.io/docs/ts/latest/api/router/CanReuse-interface.html

**Comment by rizwanhussain-vteams** [comment]
And what are the performance impacts if i don't reuse?

**Comment by brandonroberts** [comment]
Your component will be disposed and reloaded every time you visit those routes, so it depends on how much work you're doing in the route component.

**Comment by rizwanhussain-vteams** [comment]
Ok. Thanks. That worked. Took a little while figuring out what the imports should be but just out of curiosity, i still see only one xhr request to the component template and no new xhr request for subsequent requests. 
So if i understand correctly, when we set `canReuse` to `false` the request to component is made more than once, not reusing anything but the templates? Because the data seems to change but no new ajax request is made and templates remain the same.
I'm just a little confused why there is no new ajax request.

**Comment by brandonroberts** [comment]
Yes, that is correct. See example: http://plnkr.co/edit/dUelD6jSC7MHpfoz8Plm?p=preview

**Comment by mcblum** [comment]
Anyone happen to know if there's a new way to do this in Angular 5? We have a pretty general `/page/:slug` component that gets called all of the time and it's less work to just rerender it than to try and fake the animations, loading, etc...

**Comment by gabrielcabralbfr** [comment]
Having the same problem rizwanhussain said. I have a route for place/:placeType and my component is beeing reused every time i change the route (placeType parameter), instead of instantiating a new one. Maybe i'm doing something wrong. Any help?

**Comment by RognerFung** [comment]
I had the same problem. Then I used ngDoCheck to detect the route param changes. If changes detected, just initiate the component again.

**Comment by netlander** [comment]
@gabrielcabralbfr 

Create a service that extends `RouteReuseStrategy`:
Below is a full implementation but the main functionality is in `shouldReuseRoute(...)`
```
import {ActivatedRouteSnapshot, DetachedRouteHandle, RouteReuseStrategy} from '@angular/router';

export class CustomRouteReuseStrategy extends RouteReuseStrategy {
    handlers: { [key: string]: DetachedRouteHandle } = {};

    shouldDetach(route: ActivatedRouteSnapshot): boolean {
        console.log('CustomReuseStrategy:shouldDetach', route);
        return false; // Used to be true
    }

    store(route: ActivatedRouteSnapshot, handle: DetachedRouteHandle): void {
        console.log('CustomReuseStrategy:store', route, handle);
        this.handlers[route.routeConfig.path] = handle;
    }

    shouldAttach(route: ActivatedRouteSnapshot): boolean {
        console.log('CustomReuseStrategy:shouldAttach', route);
        return !!route.routeConfig && !!this.handlers[route.routeConfig.path];
    }

    retrieve(route: ActivatedRouteSnapshot): DetachedRouteHandle {
        console.log('CustomReuseStrategy:retrieve', route);
        if (!route.routeConfig) {
            return null;
        }
        return this.handlers[route.routeConfig.path];
    }

    shouldReuseRoute(future: ActivatedRouteSnapshot, curr: ActivatedRouteSnapshot): boolean {
        console.log('CustomReuseStrategy:shouldReuseRoute', future, curr);
        return future.routeConfig !== curr.routeConfig; // Magic sauce
    }
}
```
Then ad it to all concerned modules:
```
...
    providers: [
        ...
        {
            provide: RouteReuseStrategy,
            useClass: CustomRouteReuseStrategy
        },
    ],
...
```
The above will force the Router to reload your components in a master-detail scenario.
