### ISSUE TITLE
$sce.trustAsHtml not working with JQuery

### ISSUE THREAD

**Issue by asaharan** [angular/angular#6912]
**Variable declaration**
$scope.eventContent=$sce.trustAsHtml($scope.eventData.desc[i].desc);

**Html**
<div  compile="eventContent"></div>

**Directive**
directive('compile', ['$compile', function ($compile) {
      return function(scope, element, attrs) {
          var ensureCompileRunsOnce = scope.$watch(
            function(scope) {
              return scope.$eval(attrs.compile);
            },
            function(value) {
              element.html(value);
              $compile(element.contents())(scope);
            }
        );
    };
Without Jquery this is working fine but not with Jquery.

**Comment by robwormald** [comment]
you want https://github.com/angular/angular.js - this is angular2
