### ISSUE TITLE
ngUpgarde and angular 1 $templateCache

### ISSUE THREAD

**Issue by jusefb** [angular/angular#6913]
Hi,

I have started upgrading one of our angular 1 apps to angular 2 and have stumbled upon the following issue. There does not seem to be a way to use the angular 1 $templateCache inside of angular 2. Am I missing something?

Kind regards

Jusef

**Comment by wesleycho** [comment]
That is yet to be implemented - one can use the `template` option with the Component decorator, and if one wants to split off the template, one can import the template as a string and insert it.

**Comment by jusefb** [comment]
Thanks, this is what I have done for now.

**Comment by spencerwi** [comment]
Is this slated for inclusion with 1.0?

**Comment by gkalpak** [comment]
I am not sure what this question is about (and whether it is an `ngUpgrade` question), but if you are asking...

- "Does Angular (2+) support a similar feature as AngularJS's `$templateCache`?", the answer is "maybe". This [looks similar][1], but it is still experimental, barely documented and will not work for AoT mode. (In AoT mode, the templates are inlined, so having a feature equivalent to `$templateCache` is unnecessary.)
- "Is it possible to use `$templateCache` in an ngUpgrade app for AngularJS (1.x) components?", the answer is "yes".
- "Is it possible to use `$templateCache` in an ngUpgrade app for Angular (2+) components?", the answer is "maybe". (You should be able to provide `ResourceLoader` as a wrapper around `$templateCache`, but it is unlikely to be worth the trouble).

##
Closing but feel free to open a new, more specific issue if your question wasn't answered (or ask for clarifications below).

[1]: https://angular.io/docs/ts/latest/api/platform-browser-dynamic/index/RESOURCE_CACHE_PROVIDER-let.html
