### ISSUE TITLE
router(angular1): Router build file not compatible with browserify for bundling

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#6914]
Using browserify for bundling causes errors using the angular_1_router.js file due to browserify trying to import the `require` statements in the built router file. A workaround is to rename all the occurrences of `require('` to `routerRequire('` and change the `var require = function...` to `var routerRequire = function...` in the `angular_1_router.js` file.

**Comment by ArniDzhan** [comment]
+1

**Comment by Mischi** [comment]
FWIW i've seen the same problem with SystemJS

**Comment by brandonroberts** [comment]
The fix for this has been merged

**Comment by OvidiuGuta** [comment]
Hi. Nice fix. But how can I get my hands on the fixed version from npm? Installing latest gives me only the router for Angular 2. Thank you in advance for your help.
