### ISSUE TITLE
ngModelChange doesn't update the input value correctly

### ISSUE THREAD

**Issue by Pmyl** [angular/angular#6916]
This is the [plnkr](http://plnkr.co/edit/YFsafUi0zKtha8dEab4W)
In the example if you type more than 10 characters 'name' will be truncated to 10. The model updates correctly but the input value doesn't change even if there is the [ngModel].

**Comment by NiXXeD** [comment]
If you change it to `[(ngModel)]`, it seems to work correctly for me.

**Comment by Pmyl** [comment]
Changing to `[(ngModel)]` it overrides my `(ngModelChange)` causing it to not truncating 'name' anymore.

**Comment by NiXXeD** [comment]
Are you just trying to limit the text box to 10 characters? Could you use `maxlength="10"` in the template?

If you're just using this to demonstrate the problem, you could put your change function in a defer/setTimeout, and it will actually update the model. Example: http://plnkr.co/edit/7eFKBAnTm0vXvMeLdRXG?p=preview

**Comment by Pmyl** [comment]
Thanks, this do the trick, but it's definitely a workaround to the problem. The docs uses an example like mine (ngModelChange used to uppercase the ngModel) to demonstrate the utility of ngModelChange, it's odd that we must use a workaround.

**Comment by pkozlowski-opensource** [comment]
@Pmyl for the scenario from your plunker `maxlength="10"` is definitively the way to go. uppercase scenario will be properly solved by #3009
