### ISSUE TITLE
Karma PhantomJS fails when importing NG2 modules in spec files

### ISSUE THREAD

**Issue by OClement** [angular/angular#6917]
So I thought it was a SystemJS related issue but it turns out it looks more like an NG2 one, or at least some combination of NG2, SystemJs and PhantomJS.

[Original Issue I opened at SystemJS](https://github.com/systemjs/systemjs/issues/1081)
---

---

Long story short:
I can run tests fin through Karma and Chrome, but as soon as I switch to PhantomJs it fails
If my Spec files doesn't import anything related to Angular2, it works fine, but if for instance I `import 
{it} from 'angular2/testing'` or `import {Component} from 'angular2/core`, it will fail with no error message;
I only get __[this stack trace](http://pastebin.com/UYiY1Z0S)__

If my spec file import a module from my application that in turns import something from NG2, it fails in the same way. But importing for example `{Observable} from 'rxjs/Observable'` it works fine

You can see details of my configuration in the original issue lined above

Thoughts?

**Comment by blacksonic** [comment]
It maybe connected to #6789

**Comment by OClement** [comment]
Thanks for the pointer @blacksonic 

I'm trying to load the testing and browser JS files mentioned in my shim but for some reasons I get 404s
I understand this is more related to my config than the actual issue described here but maybe you'll be able to provide an insight about what's going on

Relevant bit of my Karma_shim file:

```
System.paths = {
  'angular2/*': './node_modules/angular2/*'
};

Promise.all([
    System.import('angular2/testing.js'),
    System.import('angular2/platform/testing/browser.js')
  ]).then(...);
```

Made sure Karma can serve them (karma.conf `files` array - These files definitely exist at that location):
```
{
        pattern: './node_modules/angular2/testing.js',
        included: false,
        served: true
      },
      {
        pattern: './node_modules/angular2/platform/testing/browser.js',
        included: false,
        served: true
      },
```

Relevant output: 

```
18 02 2016 12:41:00.558:DEBUG [middleware:source-files]: Requesting /node_modules/angular2/testing.js /
18 02 2016 12:41:00.559:DEBUG [middleware:source-files]: Fetching /node_modules/angular2/testing.js
18 02 2016 12:41:00.560:WARN [web-server]: 404: /node_modules/angular2/testing.js
18 02 2016 12:41:00.562:DEBUG [middleware:source-files]: Requesting /node_modules/angular2/platform/testing/browser.js /
18 02 2016 12:41:00.563:DEBUG [middleware:source-files]: Fetching /node_modules/angular2/platform/testing/browser.js

18 02 2016 12:41:00.566:WARN [web-server]: 404: /node_modules/angular2/platform/testing/browser.js
18 02 2016 12:41:00.568:DEBUG [PhantomJS 2.1.1 (Windows 8 0.0.0)]: Disconnected during run, waiting 2000ms for reconnecting.
18 02 2016 12:41:00.578:ERROR [phantomjs.launcher]: Fatal Windows exception, code 0xc0000005.
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.

18 02 2016 12:41:00.594:DEBUG [launcher]: Process PhantomJS exited with code 3221225477
18 02 2016 12:41:00.595:ERROR [launcher]: PhantomJS crashed.

18 02 2016 12:41:00.596:DEBUG [temp-dir]: Cleaning temp dir C:\Users\oclement\AppData\Local\Temp\karma-99637624
```

Ideas maybe?

**Comment by papajuras** [comment]
adding 
`files: [
            // needed by phantomJS
            'node_modules/es6-module-loader/dist/es6-module-loader.js',
            'node_modules/traceur/bin/traceur-runtime.js',`

fixes the problem. found at [https://github.com/mgechev/angular2-seed/blob/master/karma.conf.js](url)

**Comment by OClement** [comment]
Thanks @papajuras 
I think I better understand the issue I was having, but I tried aligning my configuration with MGechev's, but still no dice

When including Traceur-Runtime I get an error 
`[phantomjs.launcher]:     at nextOrThrow (http://localhost:9876/base/node_modules/traceur/bin/traceur-runtime.js:1311:16`

I logged the arguments passed to that function and they're all undefined, beside the third one being 'next'

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166455.
------------------------------------------------------------------------------------------------------------


[[7a38e85dcd87e95564b2e8ae16405b14848315aa-673073401]]

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166461.
------------------------------------------------------------------------------------------------------------


[[e4da5b2e8b203e9c2a20a514347a6eb61e0e32e1-673073416]]

**Comment by vicb** [comment]
Is this still an issue?

**Comment by pkozlowski-opensource** [comment]
This sounds like a support request and doesn't belong here, see: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
