### ISSUE TITLE
DynamicComponentLoader loading multiple components in unexpected order

### ISSUE THREAD

**Issue by Munhoziii** [angular/angular#6920]
Using `DynamicComponentLoader` functionality (either through `loadIntoLocation` or `loadNextToLocation`) to add multiple components to the same location generate a race condition based on the `TemplateCompiler` (`compileHostComponentRuntime`) [cache](https://github.com/angular/angular/blob/eda4c3eb4c823029b885fdfcd602a8c3c93f0d31/modules/angular2/src/compiler/template_compiler.ts#L120) so the resulting elements can be added out of order if their caching status differ.

It seems that the index of each loaded component could be defined prior to the [compiler step](https://github.com/angular/angular/blob/7ae23adaff2990cf6022af9792c449730d451d1d/modules/angular2/src/core/linker/dynamic_component_loader.ts#L274) to make sure a consistent order with predictable results is delivered.

Related to #6071

**Comment by Zysce** [comment]
+1

**Comment by adambarthelson** [comment]
+1

**Comment by cziedins** [comment]
+1

**Comment by zoechi** [comment]
Plunker?

**Comment by Munhoziii** [comment]
http://plnkr.co/edit/eFWH6QuRSPGdPiUJMHvG?p=preview

**Comment by zoechi** [comment]
Is this what you want http://plnkr.co/edit/z5tCsCvn351W89ye7SVz?p=preview ?
You need to correctly chain async code to ensure a specific order.

**Comment by Munhoziii** [comment]
Not exactly that but applying that principle to the ComponentB (where the bug actually shows up) is how I went around it. I opened up the issue here because it didn't seem to be the expected behavior, having to chain all dynamically component generation.

**Comment by zoechi** [comment]
These are async actions, if you start the next before the previous is completed, you can't expect deterministc behavior.

**Comment by ThiagoMVF** [comment]
That is fair.

**Comment by Munhoziii** [comment]
That is fair.

**Comment by pkozlowski-opensource** [comment]
Sounds like a support question that got resolved, thnx @zoechi !
