### ISSUE TITLE
MessageBus example does not seem to work for Web Workers

### ISSUE THREAD

**Issue by qdouble** [angular/angular#6924]
Following the example here: https://github.com/angular/angular/blob/eda6a5d52aa352825308f3345c41474c07f41b44/modules/angular2/docs/web_workers/web_workers.md#using-the-messagebus-in-your-application

When following this part in particular
```
export class MyComponent {
  constructor (bus: MessageBus) {
    bus.initChannel("My Custom Channel");
    bus.from("My Custom Channel").observer((message) => {
      console.log(message); // will print "hello from the UI"
    });
  }
```
I get `error TS2339: Property 'observe' does not exist on type 'EventEmitter<any>'.` ... I tried substituting that with subscribe and doing other work arounds, but it doesn't seem to work. Is the example up to date? What's the current way to be able to use message bus? I'm trying to be use it to make the window scroll.

**Comment by qdouble** [comment]
Hmm, after trying to emit event from the web worker component to the UI, I did get the message, however I had to use subscribe and not observer...so the docs should be updated. I also think the example doesn't work because the message is emitted before worker is initialized. I've figured out what I need to do but you guys should update the example as it doesn't work as written.

**Comment by DutchKevv** [comment]
Pretty much still the same and no good MessageBus examples can be found
