### ISSUE TITLE
[hidden] does not work properly if element has display style defined in css

### ISSUE THREAD

**Issue by shadow999** [angular/angular#6927]
I tried to toggle display my component without destroying it by using [hidden] binding. But it does not work since I gave "display: inline-block" style to my element. Is it intended?

**Comment by zoechi** [comment]
This doesn't sound related to Angular. Can you please create a Plunker that demonstrates the issue. What is happening? What is the desired result?

**Comment by b-strauss** [comment]
To quote MDN:

> Changing the value of the CSS display property on an element with the hidden attribute overrides the behavior. For instance, an element styled display: flex will be displayed on screen regardless of the hidden attribute being present.

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden

**Comment by shadow999** [comment]
@b-strauss So the only way to hide/show an element having display style is using ngClass in this case?

**Comment by b-strauss** [comment]
That or you could also use [NgStyle](https://angular.io/docs/ts/latest/guide/template-syntax.html#!#ngStyle).

**Comment by shadow999** [comment]
@b-strauss Thanks.
