### ISSUE TITLE
Benchpress: smoke tests

### ISSUE THREAD

**Issue by tbosch** [angular/angular#693]
Selenium server: use the one from protractor:
```
./node_modules/.bin/webdriver-manager update
./node_modules/.bin/webdriver-manager start
```

Add an example under `modules/examples/src/benchpress` that just uses plain DOM with a button and a loop.

Versions:
- JS: Direct usage of `selenium-webdriver` -> via jasmine command line test
- Dart: `dart-async-webdriver` -> via guiness command line test
- Dart: `dart-sync-webdriver` -> via guiness command line test

**Comment by yjbanov** [comment]
Fixed by #720
