### ISSUE TITLE
the angular2dart DEVELOPERS GUIDE need update!

### ISSUE THREAD

**Issue by Matrix-Zhang** [angular/angular#6930]
I'm a fresh man with both dart and angularjs, 

i just follow the develop guide to learn...

but when i do the exercise with displaying data (https://angular.io/docs/dart/latest/guide/displaying-data.html)

the same code doesn't work, i google the solution for a lot of time...

finaly, i find the answer in issue #6070...

**Comment by zoechi** [comment]
should be moved to angular.io
