### ISSUE TITLE
Using Observable.fromArray throws an Exception

### ISSUE THREAD

**Issue by alvipeo** [angular/angular#6931]
This is driving me nuts...

The code:
```
                const f = Observable.fromArray([1, 3, 5]);
                f.subscribe(d => console.log(d));
```
throws:

>Failed: undefined is not a constructor (evaluating 'Observable_1.Observable.fromArray([1, 3, 5])')

WHY????

**Comment by ericmartinezr** [comment]
You should ask these questions in angular gitters chatroom, rxjs gitter chatroom, stackoverflow, and as last resource rxjs github. Github is for reporting bugs, and such.

**Comment by ericmartinezr** [comment]
You were answered here anyway... https://github.com/AngularClass/angular2-webpack-starter/issues/305#issuecomment-180848137

**Comment by alvipeo** [comment]
Sorry, this IS an issue to me - after some more research I see that this results in an error only when used in a test method. When I just run a project in a browser ('npm run server') I see emitted values in console log. So it has to do something with angular test code.

**Comment by robwormald** [comment]
can we see some larger context, like the files it is failing in? hard to debug from a single line.

**Comment by alvipeo** [comment]
I use this great repo as a base project - https://github.com/angularclass/angular2-webpack-starter. And created a separate spec file:

```
import {
it,
inject,
} from "angular2/testing";

import {Observable} from "rxjs/Observable";

describe("Test case for using Observable.of", () => {

    it("should emit values", () => {
        const f = Observable.of([1, 3, 5]);
        f.subscribe(d => console.log(d));
    });
});

```
The full error looks like this (don't know if it helps):

>TypeError: undefined is not a constructor (evaluating 'Observable_1.Observable.of([1, 3, 5])') in d:/Documents/SomeCode.../spec-bundle.js (line 46474)
    d:/Documents/SomeCode.../spec-bundle.js:46474:44 <- webpack:///src/app/observable-test.spec.ts:14:32

If this is not enough I could put the whole project somewhere and send you a link privately.

**Comment by robwormald** [comment]
you'd need to import the operators to make that work, or alternately import {Observable} from 'rxjs/Rx'

**Comment by alvipeo** [comment]
thanks! just added a whole bunch of operators and it started to work. damn, we've come from C++ includes which compiler checked to this... urgh...

**Comment by robwormald** [comment]
Note that when TS 1.8 is released, we'll be able to rework the RxJS lib to
make this more obvious - operators not explicitly imported will throw
errors at compile time.

**Comment by alvipeo** [comment]
Looking forward to an era of renaissance! When you open VS Code and start working on my project's code and not setting up build process or figuring out the stuff that should not even bother! :)

**Comment by WiktorKa** [comment]
I encountered the same problem, trying to use `toPromise()` function. Is it a proper way to get it working to add `require('rxjs/add/operator/toPromise');` in my `*.spec.ts` file? It works, but is this how it should be done?
