### ISSUE TITLE
EventEmitter Subscribe should not return any

### ISSUE THREAD

**Issue by SergeyBarskiy** [angular/angular#6934]
According to the specifications, subscribe method of the EventEmitter should return an object with unsubscribe method.  Right now its return type is any.  It would be better to add an ISubscription interface with the unsubscribe method instead and make it a return type.
Similar to 
    export interface ISubscription{
        unsubscribe(): any;
    }

**Comment by robwormald** [comment]
You should generally not be using EventEmitter for anything but Component events (@Outputs) - the only public API is `.emit()`

It's a subclass of RxJS's Subject, so import and use that if you want to use it in a standalone fashion.

**Comment by robwormald** [comment]
(Note there's also a change in newer version of RxJS that has `Subscriber` without a generic type, iirc.
