### ISSUE TITLE
ChangeDetector error: view changed after was checked

### ISSUE THREAD

**Issue by danielfigueiredo** [angular/angular#6935]
I know this is a common error, I've seen many different cases where most of the scenarios running inside zone helped and solved the issue. In this case it is different and the weird thing is that the error happens when a value is changed by a click event.
I've tried to run inside zone, outside zone and it doesn't make any difference.

Maybe the way I've found to make a dumb component be reused across different forms is wrong, but I've tried many different things and in terms of flexibility this seems to be the best option. My need is make each form that calls a dumb component be able to define which control is associated with it and what validations this dumb component is going to have in this particular form.

Everything works fine if the user manually inputs the data, in case of a date picker or something that the user clicks I get errors when the value is changed and the form is checking for error inside the controls.

This plunker can reproduce the error if you click and it also works if you type instead of clicking. Note that it needs to be restarted if the error happens since the application stops working.

http://plnkr.co/edit/gwLezCjEnD7Y0KXRTDJu?p=preview

**Comment by qdouble** [comment]
@danielfigueiredo You should probably be updating your control value like this so it populates to the form in the parent component properly instead of trying trying to assign a new value to a string: http://plnkr.co/edit/BEG4j58MKa4849FVmXZT?p=preview

**Comment by danielfigueiredo** [comment]
@qdouble Thanks! I can make it work this way, and I can close the issue I suppose.
