### ISSUE TITLE
ngForTrackBy blocks further update after first array change

### ISSUE THREAD

**Issue by wardbell** [angular/angular#6936]
I can make changes to an object displayed in an `*ngFor` repeater with `trackBy` ... until I do something to trigger `trackBy` intervention.

*NgForTrackBy* indeed does prevent unnecessary DOM updates when the list is refreshed with "new" content that satisfies the *trackBy* selection criteria.

However, it is a little too rigorous. Once I trigger it, it no longer updates the view with changes to the data-bound object.

Here is a [plunker repro](http://plnkr.co/edit/gFhiYPk9gk9YyDq7lQ16?p=preview).
* Change the name ... both repeater displays update

* Click *Refresh Heroes* a few times. Each click replaces the heroes list with a new array of hero clones.

*  Note the message under the first (no trackBy) display that reports each time the DOM elements have changed.

* Note that no such message appears under the second (with trackBy) display because the DOM elements are untouched. Although the hero objects change, *trackBy* doesn't replace the DOM elements.  **That's exactly what we want from *trackBy*!**

* Now change the name again. **SAD FACE!** The second (with trackBy) display is frozen. The changes do not appear.

This behavior makes `ngForTrackBy` essentially useless. 
* the displayed list is semi-immutability, which fits few if any scenarios
* we can't update the displayed object in any way once frozen
* this is no good for *mutable* entity scenarios
* this is no good for *redux* or *immutable* scenarios either ... because we see only the last mutated state of the entities, not the refreshed entities (as they might be after re-query from a server).

Here is an animated gif showing the unexpected and unwanted behavior. 

![ng-for-track-by](https://cloud.githubusercontent.com/assets/129061/12870420/c1878da4-ccf8-11e5-8a84-6a757a44ece9.gif)

Notice the last few frames where I make changes ***after*** freezing the second *trackBy* display .

**Comment by ericmartinezr** [comment]
Related to https://github.com/angular/angular/issues/6907 ?

**Comment by kara** [comment]
Yeah, this is definitely a bug.  It's already being tracked in #6907, and there is a pull request with the fix waiting to be merged into master [here](https://github.com/angular/angular/pull/6923).  For now, you can work around the issue by using `heroes[i]` rather than `hero` (which is the local not being updated).

Thanks for reporting; closing the issue as a duplicate in favor of the existing issue.

**Comment by wardbell** [comment]
@kara Oh well. Do I win an award for quality of issue report? ;-)

**Comment by kara** [comment]
Yes, appreciated the detailed report :-)
