### ISSUE TITLE
Error while routing from form submit in webworker-mode

### ISSUE THREAD

**Issue by vaseker** [angular/angular#6937]
Hello.
I have an error when submitting form using `Enter` key and trying to route using form input, but if event happens from `input[type="submit"].click()`, its okay. 
In some cases `submit` event doesn't fire at all.
And form submits works fine in not-worker mode.

Error is 

> EXCEPTION: TypeError: Cannot read property 'events' of null
> STACKTRACE:
> TypeError: Cannot read property 'events' of null
>     at WebWorkerRootRenderer._dispatchEvent (http://localhost:8080/worker_app.js:829:21)
>     at Object.next (http://localhost:8080/worker_app.js:818:88)

Code sample:

``` typescript
import { Component } from 'angular2/core';
import { NgForm } from 'angular2/common';
import { Router } from 'angular2/router';

@Component({
    selector: 'test-form',
    directives: [NgForm],
    template: `<form (ngSubmit)="onSubmit()">
        <input [(ngModel)]="field" placeholder="Type here smth" />
        <input type="submit" value="go" />
    </form>`
})

export class ListComponent {
    field: string = '';

    constructor(private _router: Router) {};

    onSubmit() {
        this._router.navigate( ['SomeRoute', { param: this.field }] );
    }
}

```

**Comment by vsavkin** [comment]
It seems like an issue with forms, not with the router.

**Comment by artdias90** [comment]
Any suggestion on workaround for this? It's quite a missing feature IMO

**Comment by vaseker** [comment]
It works fine for me [using](https://github.com/survarium/survarium-front-ng2/blob/master/app/components.logic/players/players-search.html#L1) `submit` hook:
```js
<form (submit)="navigate()"></form>
```

**Comment by artdias90** [comment]
Is your example using webworkers? For me I have the same problem with
(submit) or (ngSubmit)

**Comment by vaseker** [comment]
@artdias90 sorry, it is not ww example.

**Comment by splincode** [comment]
@mhevery This issue is relevant?

**Comment by mhevery** [comment]
non reproducable
