### ISSUE TITLE
Typescript Code Bundle

### ISSUE THREAD

**Issue by Johnaka** [angular/angular#6938]
hey, can we have typescript code all bundled? i'd like to write some more typescript code and i wanna do it quick so my fingers get used to typescript, and jumping from folder to folder is annoying for that,
Thank  you

**Comment by alexeagle** [comment]
Can you clarify what about our distribution causes you to jump from folder to folder? What format do you want the typescript sources in? Why not clone the repository?

Please re-open if you can give more specific request of what you want to do.
