### ISSUE TITLE
Using local variables with ngFor

### ISSUE THREAD

**Issue by templth** [angular/angular#6947]
__Context__

Local variables (defined with the `#` character at a element attribute) don't apply for this use case: rqw local variables for a loop with `ngFor`.

In fact, when you define a local variable on an HTML element it corresponds to the component if any. When there is no component on the element, the variable refers to the element itself.

Specifying a value for a local variable allows you to select a specific directive associated with the current element. For example:

    <input #name="ngForm" ngControl="name" [(ngModel)]="company.name"/>

will set the instance of the `ngForm` directive associated with the current in the `name` variable.

So local variables don't allow to set a value created for the current element of a loop.

If I try to do something like that:

    <div *ngFor="#elt of eltList" >
      <span #localVariable="elt.title"></span>
      {{localVariable}}
    </div>

I have this following error:

    Error: Template parse errors:
    There is no directive with "exportAs" set to "elt.title" ("
      <div *ngFor="#elt of eltList" >
        <span [ERROR ->]#localVariable="elt.title"></span>
        {{localVariable}}
      </div>
    "): AppComponent@2:10

Angular2 actually looks for a directive matching the provided name `elt.title` here)... This plunkr shows this: https://plnkr.co/edit/qcMGr9FS7yQD8LbX18uY?p=preview. The section "Local variables" of this link http://victorsavkin.com/post/119943127151/angular-2-template-syntax also describes this.

In addition to the current element of the iteration, `ngFor` only provides a set of exported values that can be aliased to local variables: `index`, `last`, `even` and `odd`.

__Question__

It would be interested to have a way to define custom local variables within the loop. This way you could define a computed variable once and use it several times in the loop block.

    <div *ngFor="#t of todos; #i=index; #formattedTodoName=format(t.name)">
      {{formattedTodoName}}
      (...)
      {{formattedTodoName}}
    </div>

I would be interested in having your feedbacks.

This question follows the one from the StackOverflow website: http://stackoverflow.com/questions/35257455/ng2-how-to-create-variable-in-ngfor-loop/.

Thanks very much!

**Comment by tycho01** [comment]
Seconding this, I was just looking for the same thing, then searched here hoping for existing solutions. Having to have duplicate code here is silly, and being able to call a function only once (in case it's expensive) without having to first store its result in the component admittedly also adds a bunch of convenience. I'd consider this feature request a pretty valuable improvement for the template language.

**Comment by zoechi** [comment]
dup of #2451 ?

**Comment by tycho01** [comment]
Looks like it to me, yeah. Guess if @templth agrees we can close this copy.

**Comment by templth** [comment]
Sure, I agree ;-) Thanks guys for pointing this out!
