### ISSUE TITLE
Component attribute value from host element attributes

### ISSUE THREAD

**Issue by ashokshetty1970** [angular/angular#6954]
The top level components scanned from html file doesn't initialize their attributes from host element attribute.
https://plnkr.co/edit/bnP6tM?p=info

Please refer to the above plunker. The my-app component has property called "helloName" which is decorated with annotation **@Input('helloName'). **As per document, this property should be initialized with the helloName attribute. However if you notice the index.html, i have specified the element as
<my-app helloName="Ashok"></my-app>, However this is ignored.

**Comment by zoechi** [comment]
dup of #1858 ?

**Comment by zoechi** [comment]
@ashokshetty1970 your post has some "invisible" code "i have specified the element as" ... ?
Is this a dup of 1858?

**Comment by pkozlowski-opensource** [comment]
dup of #1858 - thnx @zoechi
