### ISSUE TITLE
Add platform_directives and platform_pipes to transformer docs

### ISSUE THREAD

**Issue by kwalrath** [angular/angular#6956]
The docs at https://github.com/angular/angular/wiki/Angular-2-Dart-Transformer don't mention platform_directives, although we've been using that in pubspec.yaml files for a while now.

I'd like to be able to point people to more info about the transformer, in particular platform_directives, in response to Matan's comment on https://github.com/angular/angular.io/pull/666.

@kegluneq

**Comment by kegluneq** [comment]
+@vsavkin , who has the most background on `platform_directives`

**Comment by kwalrath** [comment]
Also: Please document platform_pipes (and anything else I missed).

**Comment by kegluneq** [comment]
Added sections for both platform_directives & platform_pipes, which were reviewed by @tbosch

**Comment by kwalrath** [comment]
Thanks!
