### ISSUE TITLE
Add zippy example

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular#696]
Hey everyone

I was playing with the Angular 2 code the last few days and built a very rudimentary zippy component with it. I wonder if you would be interested in having this added to your examples folder because I'm sure others would be interested in that too.

I can send a pull request and then we can polish it together if you want.

**Comment by mhevery** [comment]
Yes please send a PR.

**Comment by PascalPrecht** [comment]
Cool! Gonna do it tomorrow :)

**Comment by pkozlowski-opensource** [comment]
It landed via 783654e6a32e5cc3246e9e83a3b8459d186fa780
