### ISSUE TITLE
Proposal: OnInit with Promise

### ISSUE THREAD

**Issue by laco0416** [angular/angular#6960]
## Goal

I'd like to use `Promise` with `OnInit`. Similar implementation already exists on `routerOnActivate`.

[OnActivate - ts](https://angular.io/docs/ts/latest/api/router/OnActivate-interface.html)

> If routerOnActivate returns a promise, the route change will wait until the promise settles to instantiate and activate child components.

I want the component to wait its instantiation until the promise returned by `ngOnInit` resolved.

Example: (not works well)

```ts
@Component({
  selector: 'my-app',
  template: `
    <p>{{status}}</p>
  `,
})
export class App implements OnInit {
  
  ngOnInit() {
    return this.someAsyncProcess();
  }
  
  someAsyncProcess(): Promise<any> {
    // returns some promise
    ...
  }
}
```

[Plunker](http://plnkr.co/edit/hfNAGWk503iMw9gBzSkT?p=preview)

## Problem

Currently `ngOnInit` has no return. 

[angular/dynamic_change_detector.ts at 42231f571947fbd2db5ea5692d3990470c019990 · angular/angular](https://github.com/angular/angular/blob/42231f571947fbd2db5ea5692d3990470c019990/modules/angular2/src/core/change_detection/dynamic_change_detector.ts#L190)

[angular/change_detection_jit_generator.ts at 42231f571947fbd2db5ea5692d3990470c019990 · angular/angular](https://github.com/angular/angular/blob/42231f571947fbd2db5ea5692d3990470c019990/modules/angular2/src/core/change_detection/change_detection_jit_generator.ts#L482)

Please let opinion! :smile: 

Thanks

**Comment by jtokarski** [comment]
Agree! This is the behaviour I initailly expected from onInit.

**Comment by laco0416** [comment]
@robwormald Hi. I want to hear your impression about this. Thanks!

**Comment by Kriskit** [comment]
+1

**Comment by laco0416** [comment]
@IgorMinar I want to hear your thinking about this. Thanks.

**Comment by itrethan** [comment]
+1

**Comment by skreborn** [comment]
@Kriskit @itrethan Please use Github's reactions feature instead of commenting `+1`. Much appreciated!

**Comment by IgorMinar** [comment]
`ngOnInit` informs you that the component has been created and all the property bindings have been initialized. At this point it's too late to stop anything because everything that matters has happened already.

Guards like the one you are asking for should be available in the parents of component in question. We are still working through how this will work with a Router but even without the router a similar guard could be implemented using an `ngIf` that wraps the guarded component in the template of the parent component.

**Comment by itrethan** [comment]
@IgorMinar Thanks, but wrapping with ngIf is just a OK workaround. CanActivate seems works but it's in deprecate now.
