### ISSUE TITLE
Angular2/Dart should support adding functions to `Component.providers` annotation attribute

### ISSUE THREAD

**Issue by luisvt** [angular/angular#6961]
If we try to do this:

```dart
heroServiceFactory(Logger logger, UserService userService) =>
    new HeroService(logger, userService.user.isAuthorized);

heroServiceProvider() => provide(
    HeroService, useFactory: heroServiceFactory, deps: [Logger, UserService]);


@Component(
    selector: "my-heroes",
    template: '''
  <h2>Heroes</h2>
  <hero-list></hero-list>
  ''',
    providers: const [heroServiceProvider],
    directives: const [HeroListComponent])
class HeroesComponent {}
```
Application fails with next error:

```
EXCEPTION: Invalid provider - only instances of Provider and Type are allowed, got: Closure: () => dynamic from Function 'heroServiceProvider': static.
  EXCEPTION: Invalid provider - only instances of Provider and Type are allowed, got: Closure: () => dynamic from Function 'heroServiceProvider': static.
    (anonymous function)	
  STACKTRACE:
    (anonymous function)	
  #0      _normalizeProviders.<anonymous closure> (package:angular2/src/core/di/provider.dart:602:7)
```

It is caused because method `_normalizeProviders` in `package:angular2/src/core/di/provider.dart` does not check if the entered provider is a `Function` in which case should call the provided function.

**Comment by zoechi** [comment]
What you can do instead is

    providers: const [
        const Provider(HeroService, 
            useFactory: heroServiceFactory, deps: const [Logger, UserService]
        )
    ],

**Comment by luisvt** [comment]
I know, however when providing value, it should be constant as well. For example I cannot have next:

```
providers: const [
  const Provider(HeroService, useValue: new HeroServiceImpl())],
```

in that case `HeroServiceImpl` should be constant, like follows:

```
providers: const [
  const Provider(HeroService, useValue: const HeroServiceImpl())],
```

that means that `HeroServiceImpl` constructor should be constant, which at the same time means that `HeroServiceImpl` cannot be an implementation of `HeroService` if `HeroService` does not have a constant contructor.

I know that I can still work around it using a not implemented value, or using a factory. However this lose the IDE

**Comment by pkozlowski-opensource** [comment]
Obsolete as Dart-specific.
