### ISSUE TITLE
required file input field changes not shown.

### ISSUE THREAD

**Issue by elmsley** [angular/angular#6962]
I have a "required" in my input field.  Even though I have ngControl specified, the input class list still contains ng-invalid. 

    <form method="POST" enctype="multipart/form-data"
    action="blah" #importForm="ngForm" >
    File to upload:
    <input type="file" name="file" required #spy ngControl="file">
    <input type="submit" value="Import XLSX" [disabled]="!importForm.form.valid">
     {{spy.className}}
    </form>

If I change to use input type="text", the form is able to validate and enable the submit button.

**Comment by ericmartinezr** [comment]
Validators.required relies on the value of the field. Inputs type file do not have a value, therefore is considered as undefined or null, that's why it is invalid. You should write your own validator for this case.

**Comment by elmsley** [comment]
Ok.
