### ISSUE TITLE
Parent scopes and function arguments

### ISSUE THREAD

**Issue by joeghodsi** [angular/angular#6963]
In the plunker below I expect the function `foo` to be called and print "foo foo" but it doesn't get called at all. If you change the names of the functions to be consistent between the three directives, it works. Another oddity is that when it prints the scope and parent scope for each controller, you'll notice that directives `inside` and `outside` have the same parent while in the template, `inside` is a child element of `outside`. Thanks for your time.

http://plnkr.co/edit/Mxb4GYp5jIiLlfSSx1o7?p=info

**Comment by zoechi** [comment]
This repo is for Angular2. Your Plnkr looks like Angular 1 which is in this repo https://github.com/angular/angular.js.
The GitHub repos are for bug reports and feature requests. For support questions please use StackOverflow, Gitter, Google Groups, ...

**Comment by joeghodsi** [comment]
Thanks @zoechi! I believe this is a bug. I'll post it to the right repo. Sorry for the trouble.
