### ISSUE TITLE
Getting "Cannot read property 'style' of null" when combining Web Workers with NgIF in template or .dispose() with DCL

### ISSUE THREAD

**Issue by qdouble** [angular/angular#6964]
While porting over a notification service that disposes of last notification after a period of time or when a new notification comes in. If I dispose() of one notification using DCL to load another or just use NgIF to hide the previous notification, I will get an error. If I turn off web workers in my project, it works as normal...here's the error

> EXCEPTION: TypeError: Cannot read property 'style' of null BrowserDomAdapter.logError @ platform_location.ts:54BrowserDomAdapter.logGroup @ platform_location.ts:54ExceptionHandler.call @ vendor.js:20949(anonymous function) @ vendor.js:30082NgZone._notifyOnError @ vendor.js:30741collection_1.StringMapWrapper.merge.onError @ vendor.js:30636Zone.run @ vendor.js:15472(anonymous function) @ vendor.js:30654arguments.(anonymous function) @ vendor.js:15895
> platform_location.ts:54 STACKTRACE:BrowserDomAdapter.logError @ platform_location.ts:54ExceptionHandler.call @ vendor.js:20951(anonymous function) @ vendor.js:30082NgZone._notifyOnError @ vendor.js:30741collection_1.StringMapWrapper.merge.onError @ vendor.js:30636Zone.run @ vendor.js:15472(anonymous function) @ vendor.js:30654arguments.(anonymous function) @ vendor.js:15895
> platform_location.ts:54 TypeError: Cannot read property 'style' of null
>     at BrowserDomAdapter.setStyle (http://localhost:3000/main-worker_ui.js:15680:17)
>     at DomRenderer.setElementStyle (http://localhost:3000/main-worker_ui.js:7768:32)
>     at MessageBasedRenderer._setElementStyle (http://localhost:3000/main-worker_ui.js:16036:19)
>     at FunctionWrapper.apply (http://localhost:3000/vendor.js:18204:65)
>     at http://localhost:3000/main-worker_ui.js:16604:51
>     at ServiceMessageBroker_._handleMessage (http://localhost:3000/main-worker_ui.js:16613:47)
>     at Object.next (http://localhost:3000/main-worker_ui.js:16592:88)
>     at http://localhost:3000/vendor.js:27658:111
>     at cb (http://localhost:3000/vendor.js:30712:26)
>     at http://localhost:3000/vendor.js:15900:45
> 
> -----async gap-----
> Error
>     at _getStacktraceWithUncaughtError (http://localhost:3000/vendor.js:16467:30)
>     at Zone.fork (http://localhost:3000/vendor.js:16516:48)
>     at arguments.(anonymous function) (http://localhost:3000/vendor.js:15892:83)
> 
> -----async gap-----
> Error
>     at _getStacktraceWithUncaughtError (http://localhost:3000/vendor.js:16467:30)
>     at Zone.fork (http://localhost:3000/vendor.js:16516:48)
>     at NgZone._createInnerZone (http://localhost:3000/vendor.js:30642:15)
>     at new NgZone (http://localhost:3000/vendor.js:30428:37)
>     at createNgZone (http://localhost:3000/vendor.js:29942:13)
>     at PlatformRef_.application (http://localhost:3000/vendor.js:30043:34)
>     at Object.main (http://localhost:3000/main-worker_ui.js:17192:69)
>     at HTMLDocument.onDOMContentLoaded (http://localhost:3000/main-worker_ui.js:7330:41)
>     at Zone.run (http://localhost:3000/vendor.js:15468:25)
>     at HTMLDocument.zoneBoundFn (http://localhost:3000/vendor.js:15445:27)

**Comment by qdouble** [comment]
After playing with it further, this seems to be related to the Ruler not working properly and messing up the notification position directive I made. What is the proper way to load up the Ruler when using web workers? I have it working properly in Universal, but not with web workers turned on.

**Comment by zoechi** [comment]
`Ruler` was remove. I think this issue can be closed.
