### ISSUE TITLE
<ng-content> select attribute is too limited

### ISSUE THREAD

**Issue by OlsonDev** [angular/angular#6965]
I'm trying to make a `@Component` where I transclude a bunch of `<button>`s. If there are 4 or less buttons, display them all. If there are 5+, display 3 buttons and a "More" dropdown button.

So, I'd like to do something like:

```html
<section class="buttons">
    <ng-content select="button[type=button]:nth-of-type(-n+3), button[type=button]:nth-of-type(4):last-of-type"></ng-content>
    <button type="button" class="more" (click)="showMoreButtons()">More</button>
    <div class="dropdown more-buttons">
        <ng-content select="button[type=button]:nth-of-type(4):not(:last-of-type), button[type=button]:nth-of-type(n+5)"></ng-content>
    </div>
</section>
```

I can get `button[type=button]` to be `select`ed but once I add more complex selectors, it [silently fails](https://github.com/angular/angular/issues/6600). I traced it down to [`CssSelector.parse`](https://github.com/angular/angular/blob/master/modules/angular2/src/compiler/selector.ts#L34). As I was writing this, I noticed it'll eventually [no longer silently fail](https://github.com/wacii/angular/commit/2674de642aac3355f8cc7e9f28dca4ec5857b252).

... I'm guessing this selector parsing is necessary for server-side rendering? Or maybe to support [prioritization by selector specificity](https://github.com/angular/angular/issues/4598)?

Can we get an option to turn this off and just rely on angular using `querySelectorAll(...)` instead, ignoring [selector specificity](https://github.com/angular/angular/issues/4598)? Or maybe there's a better solution... either way, this got'cha is really limiting; `:not(elem[attr=value].class), ...` isn't enough. Obviously, for now, I can just add classes to my `<button>`s across my entire app but... :disappointed:

**Comment by zoechi** [comment]
`<slot name="xxx">` will replace `<content>` https://webkit.org/blog/4096/introducing-shadow-dom-api/. I'd expect `<ng-content>` follow that route. It might be better to add classes to your items for easier selection instead of using more complex selectors. 
Just my 2c until someone with more insight provides more details.

**Comment by OlsonDev** [comment]
>  It might be better to add classes to your items for easier selection instead of using more complex selectors.

I want the `@Component` to encapsulate the styling & which buttons get shown. This should be abstracted away from the consumer; I don't like the idea of having to remember to add `class="goes-in-more-dropdown"`. Also, that means if the consumer wants to swap the order of buttons, they might have to add/remove classes too. To me, that's just needless verbosity, a leaky abstraction. Hence, in my case, I'd disagree that classes are "better"; they will get the job done for now though.

Either way, I'll check out your link - thanks.

**Comment by zoechi** [comment]
I'm aware of that issue. You might be able to manipulate these classes from within your component imperatively but this requires direct DOM access AFAIK which is also not ideal :-/

**Comment by vicb** [comment]
> I'm trying to make a @Component where I transclude a bunch of <button>s. If there are 4 or less buttons, display them all. If there are 5+, display 3 buttons and a "More" dropdown button.

This should be possible with a directive (& querying children)
