### ISSUE TITLE
Exception Does not support more than 9 expressions

### ISSUE THREAD

**Issue by aminmagdich** [angular/angular#6966]
Hi,
I can't find any information online to point me in any direction of solving this issue

![captureaaa](https://cloud.githubusercontent.com/assets/11071691/12911384/9c41f874-cf12-11e5-896e-5daf13635bc3.PNG)

**App.ts**

```
import {Component,View} from 'angular2/core';
@Component({
    selector: 'app',
    })
@View({
  templateUrl: './components/app/app.html',
  styleUrls: ['./components/app/app.css']
})
export class AppCmp{
   a:string="aaaaaaaaaaaaa";
}
```
**App.html**

```
{{a}}
{{a}}
{{a}}
{{a}}
{{a}}
{{a}}
{{a}}
{{a}}
{{a}}
{{a}}
```
i use google chrome Version 48.0.2564.103 m like a browser but i tested this code in many browser.

**Comment by pkozlowski-opensource** [comment]
Still here: https://plnkr.co/edit/WrY6rcvzgn9af8XDl4l3

**Comment by vicb** [comment]
should be fixed with https://github.com/angular/angular/issues/11674
