### ISSUE TITLE
angular2 typescript example not working on internet explorer 11 and safari on windows 10

### ISSUE THREAD

**Issue by asiacoll** [angular/angular#6967]
It shows only "Loading". It works on Chrome. I just clicked on your live sample and was linked to github and your angular2 typescript example not working on internet explorer 11 and safari on windows 10. When  I put your code in visual studio 2015 and tested the sample, it is the same problem like on your website. Please fix!!! However when I use your Java  script instead of typescript version on visual studio 2015, it works on all browsers.

**Comment by danieleds** [comment]
Just for reference, this is a duplicate of #6501

**Comment by asiacoll** [comment]
I think it is a issue for angular, as you cannot expect  a internet visitor to fix any issue. The issue must be fixed by angular. When I use internet explorer 11 and safari to visit the angular 2.0 page, the content cannot be loaded.

**Comment by danieleds** [comment]
Did you try the temporary fix suggested at https://github.com/angular/angular/issues/6501#issuecomment-181145904 ?

**Comment by asiacoll** [comment]
when I add following script according to deadZedd, on internet explorer 11 it works, the content can be loaded. However on safari  it still not working:
 if (!Object.hasOwnProperty('name')) {
                Object.defineProperty(Function.prototype, 'name', {
                    get: function () {
                        var matches = this.toString().match(/^\s*function\s*(\S*)\s*\(/);
                        var name = matches && matches.length > 1 ? matches[1] : "";
                        Object.defineProperty(this, 'name', { value: name });
                        return name;
                    }
                });
            }

**Comment by asiacoll** [comment]
now the problem was solved without using above codes.

**Comment by AbhayVel** [comment]
What you have done to resolve problumn
