### ISSUE TITLE
EXCEPTION: No provider for Http! (SomeComponent -> SomeService -> Http)

### ISSUE THREAD

**Issue by rizwanhussain-vteams** [angular/angular#6969]
I am trying to inject a service within a component which uses Http component. I get the above error when i try to inject the Http component within the service. Below is the code for service:

_somerservice.ts_

    import {Injectable} from 'angular2/core';
    import {Http, HTTP_PROVIDERS, Headers} from 'angular2/http';

    @Injectable()
    export class SomeService {

        constructor(private _http: Http){}

        public someMethod(param: string){}

    }

And in _somecomponent.ts_

    @Component({

       ...        
      providers:  [SomeService]
       ...

    })
   
What am i missing? Thanks.

**Comment by brandonroberts** [comment]
You need to add HTTP_PROVIDERS to your bootstrap array if you  haven't already

**Comment by rizwanhussain-vteams** [comment]
Well, i was trying to avoid that. Should something like this work?

    @Injectable({

      providers:  [HTTP_PROVIDERS]

    })

But that givers me "Supplied parameters do not match any signature of call target." compile error. And the same providers exception in console.

**Comment by brandonroberts** [comment]
If you don't want to do that, you need to add it to your component's providers. 

```js
@Component({

   ...        
  providers:  [SomeService, HTTP_PROVIDERS]
   ...

})
```

**Comment by rizwanhussain-vteams** [comment]
Ok. Thanks.

**Comment by bofcarbon1** [comment]
Why?

**Comment by Delagen** [comment]
it's not supported anymore, angular 2 final provides module system, RTFM

**Comment by ColeBeckwith** [comment]
What is the solution to this now? When serving a dist file my services are unable to find the Http provider.

**Comment by johnkuriakose89** [comment]
You have to add HttpModule to your app.module.ts in @NgModule.
