### ISSUE TITLE
Dynamically loading directive

### ISSUE THREAD

**Issue by staeke** [angular/angular#6970]
I'm running Angular 2 and I'm trying to figure out how to dynamically load a directive into an existing element. The use case is I have different behaviors and depending on a condition I want to load different directives. I've looked at ```DynamicComponentLoader``` but that only seems to be able to load components (as opposed to pure directives) and only onto id defined locations.

Possible? If so, how do I do it?

**Comment by zoechi** [comment]
I haven't tried but I guess you can make class or attribute selectors and then add/remove the classes/attributes to get directives applied.
You need to add the possible list of directives to the `directives:` list of the `@Component()` annotation though.

**Comment by staeke** [comment]
@zoechi interesting...I gave it a try without success:
```html
<div attr.[foo]="bar"></div> <!-- error -->
<div [attr.foo]="bar"></div> <!-- no directive instantiated -->
<div attr.foo="bar"></div> <!-- no directive instantiated -->
```

**Comment by staeke** [comment]
also, since the directive name ```foo``` isn't known at template write time, I'd want to have it as a parameter. In other words, what I want to write (or wish there was) is a directive ```[attr]``` working like

```html
// One or the other
<div [attr]="['foo', {someParam:someValue}]"></div>
<div [attr]="[Foo, {someParam:someValue}]"></div>
```
...which would in essence be the equivalent of
```html
<div [foo]="{someParam:someValue}"></div>
```

Regarding directive reference - I guess that's a potential problem, but as long as the client of the ```[attr]``` directive can declare it, that seems fine still

It seems to me that the missing piece to glue this together is something like

```typescript
DynamicDirectiveLoader.loadIntoLocation(type: Type, hostLocation: ElementRef)
```

**Comment by zoechi** [comment]
I tried it as well without success. Seems only to support static classas and attributes.

**Comment by tristancaron** [comment]
In the component loaded by DynamicComponentLoader I can't either do
```
<p>{{'Hello world'}}</p>
```

but using something like `(click)="onClick()"` works...

**Comment by pkozlowski-opensource** [comment]
> Possible? If so, how do I do it?

Nope, not possible. Only components can be loaded dynamically.

**Comment by lucasklaassen** [comment]
@pkozlowski-opensource confirming that this is still true in angular 6? There is no way to dynamically render a directive onto an element?
