### ISSUE TITLE
routerLink support of null/undefined

### ISSUE THREAD

**Issue by staeke** [angular/angular#6971]
I think it would be convenient to allow `routerLink` to support a case where the binding resolves to null, empty array or undefined. In that case I'd expect an `<a>` tag to be created without a `href` attribute (or empty). This is useful for cases where something should be a link only if isn't the current item, or should be a link if some property is set, but keeping two different HTML structures and `*ngIf` seems overcomplicated.

I.e. something like this

``` html
<a [routerLink]="foo && ['Foo', {bar:foo}]">Here's my item</a>
```

...instead of today's

``` html
<a *ngIf="foo" [routerLink]="['Foo', {bar:foo}]">Here's my item</a>
<a *ngIf="!foo">Here's my item</a>
```

I could make a PR if it's not in the workings. What do you think?

**Comment by zoechi** [comment]
There should set `router_active` class the router-link is active. Using this you could solve this requirement using CSS only.
See also #6095 #6407

**Comment by staeke** [comment]
Maybe I wasn't clear enough. My problem is not an active css class if it's the current route but rather if I **can** generate an instruction at all as I dont't have the data

**Comment by zoechi** [comment]
Sorry, I didn't pay enough attention.
Still that attempt would be possible like `[class.disabled-link]="!foo"` and use CSS
```css
.disabled-link {
    pointer-events: none;
    cursor: default;
    opacity: 0.6;
}
```
It would allow to configure the behavior from outside. It would be convenient though if router-link would set the class by itself.
Hope it helps. Anyway, sorry for the noise.

**Comment by staeke** [comment]
@zoechi sure...appreciate taking the time!

**Comment by staeke** [comment]
And just to be clear again - the problem today is I'm getting an exception

**Comment by bokideckonja** [comment]
I have same problem. Really would be useful if we could write something like:
`[routerLink]="item.link"`
...and if that `item.link` resolves to false, null, udefined or empty array it just creates `a` tag without `href`. 

Today it throws:
`TypeError: Cannot read property 'forEach'`

Like @staeke said, only way around is setting two different `*ngIf` structures...and it gets even more complicated html structure if we have subnav items.

**Comment by vsavkin** [comment]
Doesn't the following work all right?

```
<a [routerLink]="foo ? ['Foo', {bar:foo}] : []">Here's my item</a>
```

**Comment by staeke** [comment]
@vsavkin no...as of beta 15, that broke. As of rc-4, empty array yields an href attribute. I think (haven't verified) that the generated href points to the page itself.

**Comment by mischkl** [comment]
Also having issues with routerLink being undefined here. This can easily happen if for instance the items with the routerLink are created using an ngFor. The current behavior is to send the user to the route "undefined", which seems pretty illogical - my expectation was that if the argument to routerLink is undefined and the user clicks on the item, nothing should happen.

**Comment by DzmitryShylovich** [comment]
can u add a small repro with the latest angular?

**Comment by staeke** [comment]
@DzmitryShylovich http://plnkr.co/edit/JZ35YLGhNSc0HZTwzVVx?p=preview

Binding to empty array yields a link to current route (it seems)
