### ISSUE TITLE
Inheritance messes up constructor injection

### ISSUE THREAD

**Issue by staeke** [angular/angular#6972]
When using component inheritance (which e.g. Meteor 2 Angular is based on right now), dependency injection can be tricky. First off, it seems like constructor injection is a bad choice for that use case, as it's easy for derived components to forget to pass DI parameters to the super class. Also, all dependencies propagate down, which makes it hard to introduce new dependencies in base classes. 

So, first question: Is this right? Is property injection somehow available? Maybe you'd recommend a manual approach, i.e. something like

```
Injector.resolveAndCreate([MyType]).get(MyType)
```

Second, even if running with constructor injection, it's sort of fine, as typescript passes along the requirements down to child components (you'll get typescript errors if you don't pass the args) if you declare a constructor. But...that only works as long as you declare a constructor. If not, it's silent and you're screwed. I don't see any easy fixes as I don't know a way to identify Typescript autogenerated constructors, look up the super class, and generate injection parameters for that.

Thoughts on best practices pattern? The current seems error prone.

**Comment by zoechi** [comment]
Isn't this an issue of TS compiler/linter if it doesn't warn when you don't call a super constructor or don't pass required arguments?

I use only Dart and there this isn't such an issue, I would always get warnings or errors.

Just my opinion: 
Constructors are cumbersome because object creation is cumbersome. Property injection would just move the problem somewhere else and Angular had to provide another definition about timings (what is initialized in what order).
That seems redundant and would make it more complex because there are the language requirements already (constructor, final fields, ...) and then additional framework requirements.
I wouldn't see this as improvement.

**Comment by staeke** [comment]
@zoechi now that you mention it I agree...I really think that is an issue with the typescript compiler.

I agree that property injection has its flaws too. And increasing complexity by having two modes for DI is negative. Still, not having an easy way to declare DI dependencies that don't spill down to child components leaves my unsatisfied. I guess the best in these cases would be to be able to do something like

```typescript
constructor() {
  // Hypothetical API - not working as of now
  Injector.getForComponent(this).resolveAndInstantiate(MyDependency)
}
```

Maybe such an api (```Injector.getForComponent```) already exists?

**Comment by staeke** [comment]
I guess this ticket can more concisely written as:
1. Maybe support property injection?
2. If not, and maybe in any case, provide an API ```Injector.getForComponent```

**Comment by zoechi** [comment]
@staeke can you clarify? If you inject an injector then you get the components injector and you can request instances from it. What are you missing? What is the expected API with some more details?

**Comment by staeke** [comment]
@zoechi Right, problem is - you're not always at the "driver seat" for a component. Use cases below. First, my expected API is:
```typescript
Injector.getForComponent(componentInstance:{}):Injector
```
I'd expect it to work equivalently to
```typescript
// Example service & API
const registry = new WeakMap<{}, Injector>();

function getForComponent(compInstance) {
  return registry.get(compInstance);
}

// Arbitrary component
class MyComponent {
  // Below should not be needed
  constructor(injector:Injector) {
    registry.add(this, injector);
  }
}
```

#### So why would you need it
- you may want to write a generalized property annotation, using some kind of service, for example something that autopopulates from ```RouteParams```. Then you're not in charge of annotating the constructor, but you have a constructor instance. By having this method you could write a generalized annotation and run ```Injector.getForComponent(this)``` and inject e.g. ```RouteParams```
- Base components using injected objects. The Angular2/Meteor project currently uses the ```ngZone``` of the component. We're doing general stuff with the ```ChangeDetectorRef```. By having it as a constructor parameter, you break your concerns a little, by spilling the requirement to your sub component. Unnecessary code, and prone to errors if you omit a constructor.
- Generalized other functionality that knows how to get hold of component, but not e.g. their ```ChangeDetectorRef``` since it may not be annotated as a dependency. This can be useful for building e.g. tracking of change detection patterns
- you're debugging somewhere, and it would be handy to, given an instance...get different things that this component could have injected....much like ```inspectNativeElement(componentEl).injector```, except we don't always have an HTML element.

**Comment by pkozlowski-opensource** [comment]
Related to #11606

**Comment by pkozlowski-opensource** [comment]
Actually #11606 is tracking this.
