### ISSUE TITLE
templateUrl error in PathLocationStrategy

### ISSUE THREAD

**Issue by udos86** [angular/angular#6973]
Hi,

when navigating away from a nested route to an app level route while using `PathLocationStrategy` the template url of the the target component is not resolved correctly. 

See this plunker (embedded Version in order to set `APP_BASE_HREF` correctly): https://embed.plnkr.co/KGAf7p8XcXGCFLlh0xfu/

In this example, when clicking on "Home", an error is thrown because Angular tries to load the template from url _"...test/src/home.html"_ instead of _".../src/home.html"_.

Best regards!

Udo

PS: Here's the original plunker: https://plnkr.co/edit/KGAf7p8XcXGCFLlh0xfu?p=preview

**Comment by prupp81** [comment]
same problem as you...

**Comment by pkozlowski-opensource** [comment]
Seems like this issue was opened for the deprecated router. @udos86 @prupp81 could you please verify that this still happens with the latest router (3.0.1 at this point) and open a new issue if this is still a problem? Thank you!

**Comment by udos86** [comment]
@pkozlowski-opensource it's not an issue anymore

**Comment by pkozlowski-opensource** [comment]
Thnx for coming back with the info @udos86 - much appreciated!
