### ISSUE TITLE
fix(ChangeDetection): doCheck runs more often than expected

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular#6974]
When bootstrapping a simple Angular 2 component, that basically does nothing than displaying "Hello World", also no child components involved, change detection is performed 5 (!) times for that particular component.

**Note: `enableProdMode()` didn't make any difference**

Plunk that reproduces bug: http://plnkr.co/edit/q54Fzwk6MgG2jCZET37o?p=preview

Talked to @robwormald about this 1:1. Maybe promises resolved by `bootstrap()` cause zones to perform change detection.

Another interesting observation I've made was that after bootstrap, whenever an event is fired, change detection is performed 3 (!) times for that component, instead of just once.

Plunk that reproduces **that** bug: http://plnkr.co/edit/XfBiFYdMLtQiotjYarGV?p=preview

/cc @vsavkin here as I talked to him 1:1 on this bug.

**Comment by vicb** [comment]
@PascalPrecht could you please provide a plunker on 2.x. Thanks !
