### ISSUE TITLE
Two-way binding causes WebDriver's sendkeys to drop characters

### ISSUE THREAD

**Issue by rapropos** [angular/angular#6977]
Combining my own experience with this problem with a couple of apparently related reports: [protractor #2019](https://github.com/angular/protractor/issues/2019) and [angular #6250](https://github.com/angular/angular/issues/6250), I think the root cause is a conflict between WebDriver's sendkeys method and Angular's two-way binding.

A relatively minimal, hopefully reproducible, testbed is available at [rapropos/twowaybind-sendkeys](https://github.com/rapropos/twowaybind-sendkeys). This also demonstrates a potential workaround for certain situations: eschewing two-way binding using `[(ngModel)]` in favor of binding to a form control using `[ngFormControl]`, which fixes the problem for me.

Version information:
webdriver 2.48.2
chromedriver 2.20.353124
chrome 47.0.2526.111

**Comment by zoechi** [comment]
This might fix the issue #6897

**Comment by rapropos** [comment]
@zoechi thank you for the suggestion, but it did not have any effect for me. I'm not even sure that code is referenced in my testbed app.

**Comment by juliemr** [comment]
I am now unable to reproduce this with RC2/RC3. I think the issues has been fixed. Please open a new bug if you can show us a reproducible test case. Thanks!
