### ISSUE TITLE
[Internal testing] - simplify focused dart unit tests

### ISSUE THREAD

**Issue by juliemr** [angular/angular#6979]
As part of moving to use the dart `test` package instead of the deprecated `unittest`, we need to find a way of dealing with `iit` and `ddescribe`. In the test package exclusive specs are not natively supported and test files are read one at a time. This means that we can patch `iit` using Guinness, but it will only work within one file.

There are two ways around this. We can have one master-test-file which calls out to all other tests (ugly). Or, we can modify the workflow slightly. This is what I propose below:

Guinness2 will patch `iit` to create a test with a tag - `test(name, fn, {tags: 'solo'})`. This tag by itself will do nothing. Then, introduce a new gulp task - `gulp test.unit.dart.solo` which will expand to `pub run test --tags="solo"`. The only change in user workflow is needing to run this task when using `iit` or `ddescribe`.

**Comment by kegluneq** [comment]
This sounds fine to me, but fyi I'm in the process of moving the Dart transformer tests to use `package:test` exclusively.

https://github.com/angular/angular/pull/6896

**Comment by juliemr** [comment]
@kegluneq excellent! I don't think we can remove Guinness from the tests that use ts2dart, but agree that dart-only tests should just use package:test direct.

**Comment by juliemr** [comment]
This turned out not to be an issue - we get around it using tags and a smart gulp script which determines which target to use based on.
