### ISSUE TITLE
locationChangeStart doesn't fire when routing variables are changed

### ISSUE THREAD

**Issue by zgrossbart** [angular/angular#698]
Set up an application with routing like this:

app.config(['$routeProvider', function($routeProvider) {
    $routeProvider.when('/a', {
        templateUrl: 'myView.html',
        controller: 'myController'
    }).
    when('/b/:myVar', {
        templateUrl: 'myView2.html',
        controller: 'myController2'
    });

Now add a listener to your application like this:

scope.$on('$locationChangeStart', function(event, nextUrl, currentUrl) {
  console.log('my location changed...');
});

Now when your route changes from #/a to #/b the listener will get called.  However, if you change the route from #/b/foo to #/b/bar the listener doesn't get called.  There's no way to have a listener that gets fired when a routing variable changes.

**Comment by pkozlowski-opensource** [comment]
This is wrong repo, I guess you wanted to open it here: https://github.com/angular/angular.js

Before doing so, though, please provide run-time reproduce scenario: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#submitting-an-issue
