### ISSUE TITLE
router.navigate from child tries to apply the route on parent router

### ISSUE THREAD

**Issue by malichishti** [angular/angular#6982]
Hi,
 I have following structure:

- Parent Router
       - Child Router

                - Grandchild1

                - Grandchild2

I want to call this.router.navigate(['/Grandchild2']) from Grandchild1 but this gives me an error: '/Grandchild2' is not defined on Parent router. which suggests its calling the .navigate on Parent router rather that Child router. Is there something that i'm doing wrong?

**Comment by kespenel** [comment]
I think you should try `this.router.navigate(['Grandchild2'])`, whithout the "/" because the parameter for navigate is the name of the route, not its path.

Example from the official developer guides :
```
onSelect(hero: Hero) {
    this._router.navigate( ['HeroDetail', { id: hero.id }] );
}
```

**Comment by malichishti** [comment]
This is brilliant, thank you.
