### ISSUE TITLE
DynamicComponentLoader not working in 2.0.0-beta.2 version. 

### ISSUE THREAD

**Issue by prateeknegi** [angular/angular#6983]
There is this working example of DynamicComponentLoader in plunkr (http://plnkr.co/edit/OEYeJv7UEQMrfTQibpGB?p=preview) 

If you change the angular2 js to point to the 2.0.0-beta.2 version in index.html, the example stops working. 
I changed the following lines in index.html 
from
<script src="https://code.angularjs.org/2.0.0-alpha.39/angular2.min.js"></script>
<script src="https://code.angularjs.org/2.0.0-alpha.39/http.min.js"></script>
to   
<script src="https://code.angularjs.org/2.0.0-beta.2/angular2.min.js"></script>
<script src="https://code.angularjs.org/2.0.0-beta.2/http.min.js"></script>

Any reason for the difference in behavior ? What is the right way of using the DynamicComponentLoader ?

**Comment by RomanGotsiy** [comment]
Exported names have changed: check out the CHANGELOG for [2.0.0-alpha.49](https://github.com/angular/angular/blob/master/CHANGELOG.md#200-alpha49-2015-12-09) (breaking changes section)

There was also changes to angular bundles (separated dependencies).
Check out updated plunk for details:
http://plnkr.co/edit/1ZUsxGjZp93O6Ct8cd5u?p=preview

So DynamicComponentLoader works on 2.0.0-beta.2.
This issue should be closed.

**Comment by alexeagle** [comment]
thanks for answering @RomanGotsiy
