### ISSUE TITLE
Emitting outputs in ngOnDestroy (ngBeforeDestroy)

### ISSUE THREAD

**Issue by JurajMlich** [angular/angular#6984]
Let's say I have an object having one property called `text`. The property is passed into the editor using `[text]="object.property"`. When some changes are present and the editor is destroyed or it loses focus, it emits the changeSave output / event. The parent component then saves the content. The problem is that editor can be focused and simultaneously have some changes, but since the editor has the focus, the changes are not saved yet. But what in case that the editor is destroyed? The blur would not get called and emitting events in ngOnDestroy does not work. 

Wouldn't it be a bad idea to implement in Angular something like ngBeforeDestroy, so that events emitted in this method would be truly emitted?

**Comment by ertle** [comment]
+1

**Comment by zoechi** [comment]
Seems to be related to #6786 even when you don't get the error.

**Comment by awerlang** [comment]
A synchronous event emitter would work for you?

```js
  @Output()
  done = new EventEmitter(false);
```

**Comment by awerlang** [comment]
Here's a workaround: http://stackoverflow.com/a/34743948/592792

**Comment by zoechi** [comment]
`EventEmitter` shouldn't be used in a service. Use an observable instead.

**Comment by aburakab** [comment]
Can you please tell me why using observable here is better than eventEmitter?

**Comment by zoechi** [comment]
@aburakab it's not about better. `EventEmitter` is only for `@Output()`s. Currently `EventEmitter` extends `Subject` but that might change at any time without notice because that is a private implementation detail.
