### ISSUE TITLE
Being able to fetch parent route params

### ISSUE THREAD

**Issue by staeke** [angular/angular#6985]
Consider the following url scheme
/playlists/:playlistId/tracks/:trackId

And assume there's a ```Playlist``` component with a route config mapping down to ```Track```. 

```typescript
@RouteConfig([{path: '/playlists/:playlistId', name: 'Playlist', component: Playlist}])
class Root { ... }
@RouteConfig([{path: '/tracks/:trackId', name: 'Track', component: Track}])
class Playlist { ... }
```

But...quite naturally ```TrackComponent``` may have as its public API a notion of knowing whether to render inside a playlist. It may be an optional parameter (there are other use cases with mandatory parameters), but it needs to find out the playlist id. This is currently **hard** (unless I've missed some way). You need to have the DI injector injected, and walk up the parent chain to optionally get RouteParams, and in turn then look for playlistId.

Alternatively you could create viewProviders with special information providing an internal API for fetching that playlistId. But these solutions all seem very much overkill for such a trivial and normal scenario.

This also touches on the discussion here https://github.com/angular/angular/issues/6081, where I agree with @ewinslow. It would be ideal for Track to just declare an optional DI parameter "playlistId". But in lack of that I'd like to propose a simpler addon to ```RouteParams```:

- either that the current ```get``` function walks up the route parameter hierarchy itself
- ...or that there's a new method ```getClosest``` (like jQuery's $closest) or similar that gets the closest matching parameter in the router hierarchy

**Comment by danieleds** [comment]
+1, this would be useful

**Comment by jjpeters67** [comment]
@RouteConfig([{path: '/playlists/:playlistId', name: 'Playlist', component: Playlist}])
class Root { ... }
@RouteConfig([{path: '/tracks/:trackId', name: 'Track', component: Track}])
class Playlist { ... }

**Comment by gionkunz** [comment]
+1 This should be supported in my view. I currently use forwardRef injection of the parent component to obtain the necessary parameters which is kind of ugly

**Comment by vicb** [comment]
obsolete - former router
