### ISSUE TITLE
Router deactivate strange behaviour

### ISSUE THREAD

**Issue by wkwiatek** [angular/angular#6989]
I've tried to reset programatically `routerOutlet` to initial state but when I used `router.deactivate` then I could go to the same state using `routerLink` because of error: 
```
Error: Cannot reuse an outlet that does not contain a component.
```

Also when I used: 
```js
this.router.deactivate(this.router.generate(['/Route1']));
```
while being in `/Route2` it seemed to ignore the argument passed in. 

Here is the plunker to play with: http://plnkr.co/edit/qA1Geq3NdezmV2P6zLhP?p=preview

**Comment by vicb** [comment]
obsolete - former router
