### ISSUE TITLE
Question: dynamically enable a Directive on a component

### ISSUE THREAD

**Issue by AndreyChernykh** [angular/angular#6990]
Hello. 

I want to share common behavior between my components, e.g. some kind of "isLoading" behavior, which puts a loading mask on a component. 

I was going to use a custom Directive to this purpose and enable it  dynamically by adding to the host an attribute or a class. But it doesn't work. 

```
// app.html
<my-child [isHighlighted]="true"></my-child>
...
// my_child.ts
@Component({
  ...
  host: {
    '[class.myHighlight]': 'isHighlighted'  
  }
})
export class MyChild {
  isHighlighted: boolean;
}
```

Is this a bug? Or maybe there are some more convenient  ways to mixin some behaviors? 
Here is the example code http://plnkr.co/edit/oRNKVBGynzV5UXxdeT8d

Thanks.

**Comment by zoechi** [comment]
dup of #6970

**Comment by pkozlowski-opensource** [comment]
@AndreyChernykh I think that you make it more complex than necessary. If you want to have common code for components, I would simply put it in a base class. But honestly if we are talking about common behavior triggered by a CSS class or an attribute, I would rather use composition and encapsulate reusable behavior and move it to a directive: http://plnkr.co/edit/0XpWYI88SM21S8bWqCpU?p=preview

There are other options of course.

Going to close this one as IMO this is better handled by a dedicated directive and we've got already an issue for a "fully dynamic" behavior.

**Comment by AndreyChernykh** [comment]
@pkozlowski-opensource I fully agree with a dedicated directive approach, but it appears that we can only control directives from outside a compoent, but I'd asked about controlling it from the inside of  the component thought its properties. 

But I've got your point. Thank you.
