### ISSUE TITLE
Which is the use of routerCanReuse in angular2?

### ISSUE THREAD

**Issue by giorgiofran** [angular/angular#6992]
I'm using angular2 (beta.3) with dart.
I'trying to understand which is the logic behind the routerCanReuse method.

What I have understood googling and doing some tests on a simple example, is that routerCanReuse is called when the same route as the active one is invoked.

In my component called by the route invocation, I have a variable (only for test) that is incremented in any method call.

What I could see is that if I set a true return value in routerCanDeactivate(), the variable is resetted, while if I return false in routerCanReuse, the variable is not resetted,even if the canActivate function is called immediately after.

In my tests, canReuse is called even if the route parameters are the same.
I'm confused because it seem to me that canReuse and canDeactivate, when I route to the same component, have the same meaning.

Obviously it is not like that and I'm missing something.

Is there anyone that can explain me how these methods work?

**Comment by giorgiofran** [comment]
I'm sorry, I guess I filed this to the wrong repository.

**Comment by giorgiofran** [comment]
Wrong repository, I close the issue.

**Comment by zoechi** [comment]
AFAIK `canReuse` is about whether the router can re-add the same component instance or drop it and create a new instance when the route is activated again.
