### ISSUE TITLE
[BETA-6] Gesture (swipeleft) event makes Zone throw Maximum call size exceeded

### ISSUE THREAD

**Issue by jimjim2a** [angular/angular#6993]
Hi,

Since Beta-2, it seems that gesture management using Hammer cause Zone to throw "Maximum call size exceeded".

Here's a reproductible plunk :

http://plnkr.co/edit/OLNs58Bp0HKjMROdW6yy?p=preview

Thx !

**Comment by Barryrowe** [comment]
Just ran into this using @HostListener('tap') for a custom directive as well.

**Comment by jimjim2a** [comment]
Updated plunk to use Beta 6, issue still there.

**Comment by takagiasuka** [comment]
+1

**Comment by takagiasuka** [comment]
https://github.com/angular/angular/blob/master/modules/angular2/src/platform/dom/events/hammer_gestures.ts#L18-L30

```typescript
  addEventListener(element: HTMLElement, eventName: string, handler: Function): Function {
    var zone = this.manager.getZone();
    eventName = eventName.toLowerCase();

    return zone.runOutsideAngular(function() {
      // Creating the manager bind events, must be done outside of angular
      var mc = new Hammer(element);
      mc.get('pinch').set({enable: true});
      mc.get('rotate').set({enable: true});
      var handler = function(eventObj) { zone.run(function() { handler(eventObj); }); };
      mc.on(eventName, handler);
      return () => { mc.off(eventName, handler); };
    });
  }
```
`handler`is defined by arguments.
>       var handler = function(eventObj) { zone.run(function() { handler(eventObj); }); };

Here is an infinite loop.

```typescript
  addEventListener(element: HTMLElement, eventName: string, handler: Function): Function {
    var zone = this.manager.getZone();
    eventName = eventName.toLowerCase();

    return zone.runOutsideAngular(function() {
      // Creating the manager bind events, must be done outside of angular
      var mc = new Hammer(element);
      mc.get('pinch').set({enable: true});
      mc.get('rotate').set({enable: true});
      var callback = function(eventObj) { zone.run(function() { handler(eventObj); }); };
      mc.on(eventName, callback);
      return () => { mc.off(eventName, callback); };
    });
  }
```
It can be fixed in this.

**Comment by gashawmola** [comment]
+1 I ran to the same issue.

**Comment by astec** [comment]
Is is fixed by https://github.com/angular/angular/commit/41e38e4330bee5f117d823aa51204449650cb385?

**Comment by godzsa** [comment]
@astec yes it is.

**Comment by CaptainCodeman** [comment]
no it isn't

**Comment by kara** [comment]
@CaptainCodeman Are you checking on master or beta.9?  The fix is only on master at the moment (and will go into our next beta release).

**Comment by CaptainCodeman** [comment]
Oh, I thought it was in the beta-9 release. There was no changelog so it wasn't clear.
http://plnkr.co/edit/Ic99R2YdhHKVk3EDjkaK?p=preview

**Comment by pkozlowski-opensource** [comment]
Sounds like this one got fixed in master.
