### ISSUE TITLE
Question: Load file before showing component

### ISSUE THREAD

**Issue by shadow999** [angular/angular#6997]
Hi,

I have a question about loading file before actually showing component. I am not sure it is doable or not in Angular 2 that a component would wait for a promise to finish before actually showing the content of that component? I tried using CanActivate which works fine. But I can only use CanActivate on those component that is loaded by router.

**Comment by CaptainCodeman** [comment]
You can put `*ngIf="theloadedthing"` on the component maybe?

**Comment by shadow999** [comment]
@CaptainCodeman This is more like a hack. The file loading process in my project might be applied to most of components. Using your approach is a bit annoying.

**Comment by zoechi** [comment]
@shadow999 If you wrap the template of your root component witn an `ngIf` no other components should be added before the expressions becomes true.

**Comment by shadow999** [comment]
@CaptainCodeman @zoechi Is it possible to add another lifecycle hook that runs before everything else and takes a promise. And only move on to next hook after that promise is resolved?

**Comment by zoechi** [comment]
I don't see any benefit in an additional lifecycle hook at all. What's the problem with `ngIf`? 

I'm not member of the Angular2 team, the official opinion might be different though.

**Comment by shadow999** [comment]
@zoechi The problem with ngIf is that I need to repeat same code and html structure in most of my components. CanActivate annotation is very helpful if it can be used by any component.

**Comment by zoechi** [comment]
But why do you need to repeat code? You only need the `ngIf` in the root component.

**Comment by shadow999** [comment]
I need to load different file for different component. If I just need to
load once, I am OK to use ngIf.

On Thu, Feb 11, 2016 at 10:40 PM, Günter Zöchbauer <notifications@github.com
