### ISSUE TITLE
Dart ctor are not inherited by default

### ISSUE THREAD

**Issue by vicb** [angular/angular#70]
In ES6, ctor are inherited by default, see https://github.com/angular/angular/issues/66#issuecomment-58371981

That is if the class inherit from a parent class and this class a no ctor, the parent ctor will be called:

```
class Parent {
  constructor(foo) {
    // ...
  } 
}

class Child extends Parent {
}

// acts as

class Parent {
  constructor(foo) {
    // ...
  } 
}

class Child extends Parent {
   constructor(...args) { super(...args); }
}
```

The equivalent for `constructor(...args) { super(...args); }  has to be generated for Dart

**Comment by mprobst** [comment]
@vicb what would the equivalent Dart code be? super(...args) probably won't work, and cannot be type checked.

**Comment by vicb** [comment]
```js
class Parent {
  constructor(foo: Foo) {
    // ...
  } 
}

class Child extends Parent {
}
```

In this case for Dart you should generate `Child(foo: Foo): super(foo);`

I think you should always have access to the parent class ctor signature in TS ? (which is not the case with Traceur).

**Comment by mprobst** [comment]
This issue was moved to angular/ts2dart#100
