### ISSUE TITLE
Error updating to Beta 5

### ISSUE THREAD

**Issue by harangue** [angular/angular#7000]
Upon running `npm update angular` to upgrade to Beta 5 from Beta 3 the post-install fails, which causes npm to cancel the entire update.
```
> angular2@2.0.0-beta.5 postinstall C:\Users\Jack\git\s\c\node_modules\angular2 
> typings install --ambient --name es6-promise github:DefinitelyTyped/Definitely
Typed/es6-promise/es6-promise.d.ts#830e8ebd9ef137d039d5c7ede24a421f08595f83; typ
ings install --ambient --name es6-collections github:DefinitelyTyped/DefinitelyT
yped/es6-collections/es6-collections.d.ts#9f97e2a2bc1f502550c9b4fcaad1c48df5521d
37                                                                              
                                                                                
? What is the dependency name? es6-promise                                      
typings ERR! message Unable to read typings for "es6-promise". You should check 
the path is correct                                                             
typings ERR! caused by https://raw.githubusercontent.com/DefinitelyTyped/Definit
elyTyped/830e8ebd9ef137d039d5c7ede24a421f08595f83;/es6-promise/es6-promise.d.ts 
responded with 404, expected it to equal 200                                    
```
Manually reinstalling my typings individually (including the "problem package" es6-promise) fixed this.

**Comment by rodbzro** [comment]
Same here.

`
Windows_NT 10.0.10586

node v5.6.0
npm v3.6.0
typings 0.6.6
`

**Comment by sentient-drone** [comment]
Same error here.

Manually running these on their own didn't seem to solve it.
```
typings install --ambient --name es6-promise
typings install --ambient --name es6-collections
```

Error:
```
typings install --ambient --name es6-promise github:DefinitelyTyped/DefinitelyTyped/es6-promise/es6-promise.d.ts#830e8ebd9ef137d039d5c7ede24a421f08595f83; typings install --ambient --name es6-collections github:DefinitelyTyped/DefinitelyTyped/es6-collections/es6-collections.d.ts#9f97e2a2bc1f502550c9b4fcaad1c48df5521d37
```

Node v5.6.0
NPM v3.3.6
typings v0.6.8

**Comment by CaptainCodeman** [comment]
I'm no expert on typings but it seems like installing things but not saving them into the typings.json file is wrong - shouldn't we be able to blow away the typings folder and do `typings install` to add everything back?

**Comment by alexeagle** [comment]
Are all of you on Windows? Did you all get a 404 from github?

**Comment by CaptainCodeman** [comment]
No, I'm on Mac. I didn't notice any 404 (you mean from npm?)

**Comment by beaverusiv** [comment]
I get this message on Ubuntu Wily
node v5.6.0
npm v3.6.0

> typings ERR! message Unable to read typings for "jasmine". You should check the path is correct
typings ERR! caused by https://raw.githubusercontent.com/angular/DefinitelyTyped/4b36b94d5910aa8a4d20bdcd5bd1f9ae6ad18d3c/jasmine/jasmine.d.ts responded with 404, expected it to equal 200

**Comment by alexeagle** [comment]
the OP has a github 404, but there's a spurious semicolon in the URL.
I suspect there is more than one problem, can you give more details on the failure you see?

**Comment by CaptainCodeman** [comment]
I don't think anything failed with my install - there were new typings files added but the webpack build then failed with a ton of ts errors (can't fine require, Promise etc...). I ended up adding things manually based on help from gitter before running into https://github.com/angular/angular/issues/7001

Sorry that's probably not very concrete enough to help.

**Comment by beaverusiv** [comment]
My full output:

https://gist.github.com/beaverusiv/f7bdfb736924c8296a40

**Comment by alexeagle** [comment]
I will move this typings step into our build so it doesn't happen in postinstall.

**Comment by sentient-drone** [comment]
Windows 10

Yeah looks like it's getting a 404.

```
> npm install angular2
npm WARN deprecated object-pick@0.1.2: Deprecated as of version 0.1.2 please use object.pick instead.

> angular2@2.0.0-beta.5 postinstall C:\[User]\Desktop\TinkerChest\angular2.beta5\node_modules\angular2
> typings install --ambient --name es6-promise github:DefinitelyTyped/DefinitelyTyped/es6-promise/es6-promise.d.ts#830e8ebd9ef137d039d5c7ede24a421f08595f83; typings install --ambient --name es6-collections github:DefinitelyTyped/DefinitelyTyped/es6-collections/es6-collections.d.ts#9f97e2a2bc1f502550c9b4fcaad1c48df5521d37

? What is the dependency name? (es6-promise)
? What is the dependency name? es6-promise
typings ERR! message Unable to read typings for "es6-promise". You should check the path is correct
typings ERR! caused by https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/830e8ebd9ef137d039d5c7ede24a421f08595f83;/es6-promise/es6-promise.d.ts responded with 404, expected it to equal 200
```

**Comment by Ristaaf** [comment]
Exactly the same issue as OP (including strange semicolon and 404).
Windows 10, node 5.6, npm 3.6.0, 
tried both git-bash and cmd

Also tested on a Windows 7 machine with the exact same issue.

**Comment by ericmdantas** [comment]
If I set the flag `--ignore-scripts` as mentioned by @rodbzro it does work, but then there's no `typings` inside  node_modules/angular2, as specified by the [breaking change](https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes).

**Comment by willhartman** [comment]
I'm also getting the extra semi-colon as above.

Windows 8
NPM 2.14.12
Node 4.2.4

**Comment by Ristaaf** [comment]
Even though this will be solved in another way, the simple solution and problem here is with the postinstall script (angular/modules/angular2/package.json) which uses a semicolon to separate commands, this will not work in windows, you should use && instead and it should work fine on all platforms.

**Comment by alexeagle** [comment]
Yes, I did not test on Windows and missed that. Sorry! We have a fix coming this morning.

**Comment by derekshi** [comment]
Anyone had any issues with angular2/platform/browser? I got error when using 'bootstrap', which import from 'angular2/platform/browser'. I am using mac with .beta.5

**Comment by SeriousM** [comment]
When will be the new version get published?

**Comment by ocombe** [comment]
they should release a new beta within the next 24 hours that will (hopefully) work :)

**Comment by alexeagle** [comment]
We are testing the pre-release to be careful - you can try it too, from our
npm snapshot.

`npm install angular/angular#2.0.0-build.19cfb4e.js typescript
rxjs@5.0.0-beta.0 zone.js@0.5.13`

**Comment by ocombe** [comment]
I get this on windows:
```sh
npm install angular/angular#2.0.0-build.19cfb4e.js typescript rxjs@5.0.0-beta.0 zone.js@0.5.13
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:213:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:818:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:319:11)
npm WARN addRemoteGit     at emitOne (events.js:77:13)
npm WARN addRemoteGit     at Socket.emit (events.js:169:7)
npm WARN addRemoteGit     at Pipe._onclose (net.js:469:12)
npm WARN addRemoteGit  angular/angular#2.0.0-build.19cfb4e.js resetting remote C:\Users\Olivier\AppData\Roaming\npm-cache\_git-remotes\git-github-com-angular-angular-git-2-0-0-build-19cfb4e-js-ca16d6dc because of error: { [Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
```

**Comment by theodorejb** [comment]
Why is zone.js back to version 0.5.13? When I try to install I get a "'tsd' is not recognized as an internal or external command" error due to angular/zone.js#240.

**Comment by alexeagle** [comment]
@theodorejb that's a good point - we didn't test against zone.js 0.5.14 but the only change is a fix for that postinstall step. I think we should bump to 0.5.14 in beta.6 @btford 

@ocombe I dunno, that looks like your git client is having problems fetching a github repo, maybe bad version of git or something?

**Comment by ocombe** [comment]
Maybe, it's not related to your code anyway so don't worry about it :)
