### ISSUE TITLE
Angular 2 should work with latest rxjs (beta.2)

### ISSUE THREAD

**Issue by CaptainCodeman** [angular/angular#7001]
Used https://github.com/angular/angular/issues/7000 to get around the es6 promise / shims issues but get this:

```
ERROR in ./~/angular2/src/facade/async.js
Module not found: Error: Can't resolve 'rxjs/observable/fromPromise' in '/[projectfolder]/node_modules/angular2/src/facade'
 @ ./~/angular2/src/facade/async.js 11:20-58
```

**Comment by rodbzro** [comment]
I'm also getting this error but from loading the application in the browser:

![image](https://cloud.githubusercontent.com/assets/840518/12968425/ed7575bc-d058-11e5-9a7b-391f5ca633b8.png)

**Comment by qdouble** [comment]
On line 11 of angular2/src/facade it has the wrong path as beta 2 of rxjs has changed the directory, you can manually change `var fromPromise_1 = require('rxjs/observable/fromPromise');` to `va fromPromise_1 = require('rxjs/observable/PromiseObservable');` and it should work.

The angular build does need to be update though so this is a bug.

**Comment by CaptainCodeman** [comment]
@rodbzro I should have mentioned I'm using webpack - sounds like the same issue.

Thanks @qdouble - that fixes things !

**Comment by jesperronn** [comment]
:+1: for a quick fix. I see that @IgorMinar is struggling to get a fix through Travis.

@IgorMinar will this be a release following immediately after the change?

**Comment by IgorMinar** [comment]
I proposed that we cut a release first thing tomorrow morning after #7002 and #7003 land.

**Comment by jesperronn** [comment]
Awesome! @IgorMinar Thanks for responding. This is truly being reactive :D :+1:

**Comment by danieleds** [comment]
The fix from qdouble wasn't enough for me: I ended up replacing the string in all files:

    find ./node_modules/angular2 -type f -print0 | xargs -0 sed -i 's|/observable/fromPromise|/observable/PromiseObservable|g'

**Comment by yfain** [comment]
I'm getting GET http://127.0.0.1:8080/rxjs/observable/fromPromise 404 (Not Found)

**Comment by IgorMinar** [comment]
we have a fix. testing it now and we'll cut beta.6 shortly

**Comment by digitaldonkey** [comment]
@danieleds temporary solution on **OS-X**:

```

find ./node_modules/angular2 -type f -exec sed -i '' 's/observable\/fromPromise/observable\/PromiseObservable/g' {} +

```

**Comment by digitaldonkey** [comment]
@danieleds  solution on **OS-X**

````
find ./node_modules/angular2 -type f -exec sed -i '' 's/observable\/fromPromise/observable\/PromiseObservable/g' {} +
````

**Comment by alexeagle** [comment]
beta.6 is released, but still uses rxjs beta.0.
We will keep this issue open to track the upgrade to rxjs beta.2.

**Comment by digitaldonkey** [comment]
Not working in beta.6 / rxjs 5.0.0-beta.2

**Comment by Olgagr** [comment]
@digitaldonkey beta.6 still needs rxjs beta.0, as I understand. See @alexeagle comment above.

**Comment by alexeagle** [comment]
Right, note the warnings from npm if you install a version with
incompatible peer dependencies.

**Comment by nxplus** [comment]
Im running 2.0.0-beta.6 (systemjs: 0.19.20 and es6-shim: 0.34.4), with no added rxjs dependencies. I get some errors in the console, anynone know if this is related to this issue?

```
GET http://localhost:5000/rxjs/Subject.js 404 (Not Found)D @ system.js:4(anonymous function) @ system.js:4Promise @ es6-shim.js:2306(anonymous function) @ system.js:4(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:4promiseReactionJob @ es6-shim.js:2152(anonymous function) @ es6-shim.js:2140
es6-shim.js:2152 Error: XHR error (404 Not Found) loading http://localhost:5000/rxjs/Subject.js(…)
system.js:4 GET http://localhost:5000/rxjs/observable/fromPromise.js 404 (Not Found)D @ system.js:4(anonymous function) @ system.js:4Promise @ es6-shim.js:2306(anonymous function) @ system.js:4(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:4promiseReactionJob @ es6-shim.js:2152(anonymous function) @ es6-shim.js:2140
system.js:4 GET http://localhost:5000/rxjs/operator/toPromise.js 404 (Not Found)D @ system.js:4(anonymous function) @ system.js:4Promise @ es6-shim.js:2306(anonymous function) @ system.js:4(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:4promiseReactionJob @ es6-shim.js:2152(anonymous function) @ es6-shim.js:2140
system.js:4 GET http://localhost:5000/rxjs/Observable.js 404 (Not Found)D @ system.js:4(anonymous function) @ system.js:4Promise @ es6-shim.js:2306(anonymous function) @ system.js:4(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:4promiseReactionJob @ es6-shim.js:2152(anonymous function) @ es6-shim.js:2140
system.js:4 GET http://localhost:5000/rxjs/Subject.js 404 (Not Found)D @ system.js:4(anonymous function) @ system.js:4Promise @ es6-shim.js:2306(anonymous function) @ system.js:4(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:4promiseReactionJob @ es6-shim.js:2152(anonymous function) @ es6-shim.js:2140
system.js:4 GET http://localhost:5000/rxjs/observable/fromPromise.js 404 (Not Found)D @ system.js:4(anonymous function) @ system.js:4Promise @ es6-shim.js:2306(anonymous function) @ system.js:4(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:4promiseReactionJob @ es6-shim.js:2152(anonymous function) @ es6-shim.js:2140
system.js:4 GET http://localhost:5000/rxjs/operator/toPromise.js 404 (Not Found)D @ system.js:4(anonymous function) @ system.js:4Promise @ es6-shim.js:2306(anonymous function) @ system.js:4(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:4promiseReactionJob @ es6-shim.js:2152(anonymous function) @ es6-shim.js:2140
system.js:4 GET http://localhost:5000/rxjs/Observable.js 404 (Not Found)
```

**Comment by cebor** [comment]
@nxplus rxjs is a required dependency

**Comment by nxplus** [comment]
@cebor 
I figured that must be the case, however with rxjs some further dependencies were needed, some libs seems to be looked up in the root, not sure how to solve this.

```
GET http://localhost:5000/zone.js 404 (Not Found)D @ system.js:4(anonymous function) @ system.js:4Promise @ es6-shim.js:2316(anonymous function) @ system.js:4(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:4Zone.run @ file-reader.ts:5zoneBoundFn @ file-reader.ts:5promiseReactionJob @ es6-shim.js:2162(anonymous function) @ es6-shim.js:2150
file-reader.ts:5 Error: XHR error (404 Not Found) loading http://localhost:5000/zone.js(…)
system.js:4 GET http://localhost:5000/reflect-metadata.js 404 (Not Found)D @ system.js:4(anonymous function) @ system.js:4Promise @ es6-shim.js:2316(anonymous function) @ system.js:4(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:4Zone.run @ file-reader.ts:5zoneBoundFn @ file-reader.ts:5promiseReactionJob @ es6-shim.js:2162(anonymous function) @ es6-shim.js:2150
system.js:4 GET http://localhost:5000/rxjs/observable/fromPromise.js 404 (Not Found)D @ system.js:4(anonymous function) @ system.js:4Promise @ es6-shim.js:2316(anonymous function) @ system.js:4(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:4Zone.run @ file-reader.ts:5zoneBoundFn @ file-reader.ts:5promiseReactionJob @ es6-shim.js:2162(anonymous function) @ es6-shim.js:2150
system.js:4 GET http://localhost:5000/rxjs/observable/fromPromise.js 404 (Not Found)
```

**Comment by alexeagle** [comment]
Looks like you have wrong version of rxjs - fromPromise was moved.

**Comment by meriturva** [comment]
We really need to move to rxjs beta.2 just to use webSocket....any workaround here?

**Comment by meriturva** [comment]
@jeffbcross any ETA about beta.7 and rxjs beta.2?

**Comment by emirhosseini** [comment]
I'm having this issue in beta 7 as well.

**Comment by CaptainCodeman** [comment]
@emirhosseini Have you checked your packages.json to make sure you are definitely on 5.0.0-beta.2? I've upgraded and this is fixed for me.

**Comment by emirhosseini** [comment]
Thank you for the reply @CaptainCodeman.  I did.  I'm using a project I downloaded from yeoman (the angular2-gulp-webpack).  It wasn't running initially so I started changing things and it's been one issue after another.  I come from an asp.net mvc background and trying to wrap my head around this new world of web development (new to me at least) and it's kind of rough!  Here are my dependencies in my package.json file:

"devDependencies": {
    "angular2": "2.0.0-beta.7",
    "del": "2.2.0",
    "es6-promise": "3.1.2",
    "es6-shim": "0.34.4",
    "express": "4.13.4",
    "gulp": "3.9.1",
    "gulp-autoprefixer": "3.1.0",
    "gulp-concat": "2.6.0",
    "gulp-cssnano": "2.1.1",
    "gulp-html-replace": "1.5.5",
    "gulp-htmlmin": "1.3.0",
    "gulp-uglify": "1.5.2",
    "livereload": "0.4.1",
    "reflect-metadata": "0.1.3",
    "rxjs": "5.0.0-beta.2",
    "systemjs": "0.19.22",
    "ts-loader": "^0.7.2",
    "typescript": "1.7.5",
    "webpack": "1.12.13",
    "webpack-stream": "3.1.0",
    "zone.js": "0.5.15"
  }

**Comment by emirhosseini** [comment]
Here are the errors right now with the list of dependencies I have in my previous comment:

stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
 Error: C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\core\linker\compiler.d.ts
(12,50): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\core\linker\compiler.d.ts
(16,41): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\core\linker\dynamic_component_loader.d.ts
(108,136): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\core\linker\dynamic_component_loader.d.ts
(156,150): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\core\linker\dynamic_component_loader.d.ts
(197,128): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\core\linker\dynamic_component_loader.d.ts
(203,127): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\core\linker\dynamic_component_loader.d.ts
(204,141): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\core\linker\dynamic_component_loader.d.ts
(205,119): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\core\change_detection\parser\locals.d.ts
(3,14): error TS2304: Cannot find name 'Map'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\core\change_detection\parser\locals.d.ts
(4,42): error TS2304: Cannot find name 'Map'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\core\debug\debug_node.d.ts
(14,13): error TS2304: Cannot find name 'Map'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\core\debug\debug_node.d.ts
(24,17): error TS2304: Cannot find name 'Map'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\core\debug\debug_node.d.ts
(25,17): error TS2304: Cannot find name 'Map'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\core\application_ref.d.ts
(83,60): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\core\application_ref.d.ts
(83,146): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\core\application_ref.d.ts
(96,51): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\core\application_ref.d.ts
(96,147): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\core\application_ref.d.ts
(133,90): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\core\application_ref.d.ts
(171,81): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\facade\collection.d.ts
(1,25): error TS2304: Cannot find name 'MapConstructor'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\facade\collection.d.ts
(2,25): error TS2304: Cannot find name 'SetConstructor'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\facade\collection.d.ts
(4,27): error TS2304: Cannot find name 'Map'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\facade\collection.d.ts
(4,39): error TS2304: Cannot find name 'Map'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\facade\collection.d.ts
(7,9): error TS2304: Cannot find name 'Map'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\facade\collection.d.ts
(8,30): error TS2304: Cannot find name 'Map'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\facade\collection.d.ts
(11,43): error TS2304: Cannot find name 'Map'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\facade\collection.d.ts
(12,27): error TS2304: Cannot find name 'Map'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\facade\collection.d.ts
(14,23): error TS2304: Cannot find name 'Map'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\facade\collection.d.ts
(15,25): error TS2304: Cannot find name 'Map'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\facade\collection.d.ts
(95,41): error TS2304: Cannot find name 'Set'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\facade\collection.d.ts
(96,22): error TS2304: Cannot find name 'Set'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\facade\collection.d.ts
(97,25): error TS2304: Cannot find name 'Set'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\rxjs\observable\PromiseObservable.d.ts
(9,31): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\rxjs\observable\PromiseObservable.d.ts
(10,26): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\rxjs\observable\FromObservable.d.ts
(7,38): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\rxjs\observable\FromObservable.d.ts
(7,51): error TS2304: Cannot find name 'Iterator'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\rxjs\observable\ForkJoinObservable.d.ts
(6,50): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\rxjs\observable\ForkJoinObservable.d.ts
(7,58): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\rxjs\CoreOperators.d.ts
(35,67): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\rxjs\CoreOperators.d.ts
(50,66): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\rxjs\CoreOperators.d.ts
(89,67): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\rxjs\CoreOperators.d.ts
(94,38): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\rxjs\CoreOperators.d.ts
(94,50): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\rxjs\Observable.d.ts
(46,62): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\rxjs\Observable.d.ts
(47,42): error TS2304: Cannot find name 'Iterator'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\rxjs\Observable.d.ts
(103,74): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\rxjs\Observable.d.ts
(103,84): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\rxjs\Observable.d.ts
(143,66): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\rxjs\Observable.d.ts
(158,65): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\rxjs\Observable.d.ts
(201,66): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\rxjs\Observable.d.ts
(206,38): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\rxjs\Observable.d.ts
(206,50): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\facade\promise.d.ts
(2,14): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\facade\promise.d.ts
(7,32): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\facade\promise.d.ts
(8,38): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\facade\promise.d.ts
(9,35): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\facade\promise.d.ts
(9,93): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\facade\promise.d.ts
(10,34): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\facade\promise.d.ts
(11,32): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\facade\promise.d.ts
(11,149): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\facade\promise.d.ts
(12,43): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\facade\async.d.ts
(27,33): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\facade\async.d.ts
(28,45): error TS2304: Cannot find name 'Promise'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\core\render\api.d.ts
(13,13): error TS2304: Cannot find name 'Map'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\core\render\api.d.ts
(14,84): error TS2304: Cannot find name 'Map'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\platform\dom\dom_adapter.d.ts
(85,42): error TS2304: Cannot find name 'Map'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\core\di\provider.d.ts
(436,103): error TS2304: Cannot find name 'Map'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\core\di\provider.d.ts
(436,135): error TS2304: Cannot find name 'Map'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\platform\browser\browser_adapter.d.ts
(75,33): error TS2304: Cannot find name 'Map'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\facade\lang.d.ts
(13,17): error TS2304: Cannot find name 'Map'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\facade\lang.d.ts
(14,17): error TS2304: Cannot find name 'Set'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\src\facade\lang.d.ts
(78,59): error TS2304: Cannot find name 'Map'.C:\Source\Repos\Sandbox\Angular2GulpWebpack\node_modules\angular2\platform\browser.d.ts
(77,90): error TS2304: Cannot find name 'Promise'.

**Comment by CaptainCodeman** [comment]
I'm ex ASP.NET MVC, ASP.NET Webforms (oh, the shame) heck even ASP classic and COBOL if you go back far enough (but shhh, don't tell anyone!). There's a lot to take in and lots of things to figure out with Typescript and Angular right now but it's worth it in the end.

Some of my dependencies are different versions to yours, I think these are the relevant ones:

```
    "angular2": "^2.0.0-beta.7",
    "es6-promise": "^3.0.2",
    "es6-shim": "0.33.3",
    "reflect-metadata": "0.1.2",
    "rxjs": "^5.0.0-beta.2",
    "systemjs": "^0.19.16",
    "zone.js": "^0.5.15"
```

I also have typings installed with this typings.json file:

```
{
  "dependencies": {
    "es6-promise": "github:typed-typings/npm-es6-promise#fb04188767acfec1defd054fc8024fafa5cd4de7"
  },
  "devDependencies": {},
  "ambientDependencies": {
    "es6-shim": "github:DefinitelyTyped/DefinitelyTyped/es6-shim/es6-shim.d.ts#6697d6f7dadbf5773cb40ecda35a76027e0783b2",
    "node": "github:DefinitelyTyped/DefinitelyTyped/node/node.d.ts#aee0039a2d6686ec78352125010ebb38a7a7d743",
    "zone.js": "github:DefinitelyTyped/DefinitelyTyped/zone.js/zone.js.d.ts#9027703c0bd831319dcdf7f3169f7a468537f448"
  }
}
```

and my tsconfig.json file:

```
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "moduleResolution": "node",
        "outDir": "./build",
        "sourceMap": false,
        "preserveConstEnums": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "removeComments": false,
        "noImplicitAny": false
    },
    "exclude": [
        "node_modules",
        "typings/main.d.ts",
        "typings/main"
    ]
}
```

Hope that helps.

**Comment by allenmoatallen** [comment]
@CaptainCodeman I am getting the same issue and I restored based on your versions.

**Comment by Carl-fridrix-zendolf-IV** [comment]
@CaptainCodeman thank you! Your package.json dependencies list help me on beta 7

**Comment by JavascriptMick** [comment]
If anybody is still stuck on this, these work for me as @ now
`  "devDependencies": {
    "typescript": "^1.8.7",
    "ts-loader": "^0.7.2",  
    "webpack": "^1.12.9",
    "webpack-dev-server": "^1.14.0"
  },
  "dependencies": {
    "angular2": "^2.0.0-beta.8",
    "rxjs": "5.0.0-beta.2"
  }`
