### ISSUE TITLE
NgModel bug for textarea fields in minified versions of beta 1, 2, 3 and 5 (but not 0)

### ISSUE THREAD

**Issue by ffMathy** [angular/angular#7006]
Hi there.

See this StackOverflow question, more specifically the comments of the 1st answer: http://stackoverflow.com/questions/35322608/two-way-binding-in-angular-2-with-ngmodel-and-mutating-bound-property

I can indeed confirm the issue with this Plunker: https://plnkr.co/edit/FB0dpLfIGEwV3mgs3KNJ?p=preview

Note how the beta 0 works just fine, but if you change it to beta 1, 2, 3 or 5, it won't work. *However*, if you change it to the non-minified versions, it works all the time (no matter what version it is).

What I mean by "works" is that I expect that mutating some value that is two-way bound to also update the text of the `textarea` field, which is not the case.

**Comment by ericmartinezr** [comment]
dup of https://github.com/angular/angular/issues/6380 (because of issues with minification, not the error itself). By the way, the minifications issues are here since beta.1, still alive in beta.5 as I can see...
