### ISSUE TITLE
angular2-polyfills.min.js throws deprecation warning since beta.3

### ISSUE THREAD

**Issue by tamalnath** [angular/angular#7007]
While loading, I am getting below error in Firefox browser console:

`DEPRECATION WARNING: 'enqueueTask' is no longer supported and will be removed in next major release. Use addTask/addRepeatingTask/addMicroTask`

`DEPRECATION WARNING: 'dequeueTask' is no longer supported and will be removed in next major release. Use removeTask/removeRepeatingTask/removeMicroTask`

Please get rid of it.

**Comment by antonybudianto** [comment]
this warning comes since beta.3

**Comment by jet0316** [comment]
my app wont load since I switched to beta.3, and this is the only error I'm getting

**Comment by robwormald** [comment]
not an error, its simply a logged warning. shouldn't have any breaking effects.

**Comment by tamalnath** [comment]
@robwormald : although these warning messages are harmless, can you please get rid of these warnings ?

**Comment by kylecordes** [comment]
I also request that this ultra-current framework (itself in beta, dependencies in beta, etc.) move away from older deprecated APIs in their warnings, if feasible to do so. (I am prepping for a series of Angular 2 classes, and don't look forward to explaining this console message... every... time...)

**Comment by robwormald** [comment]
Deprecation is what happens during beta, so as not to make *breaking*
changes wherever possible.

**Comment by kylecordes** [comment]
I must have mis-understood. I thought I read the thread above to mean: for some reason since beta 3, Angular began using older APIs and thus generating this item. From your message I'm thinking that must not be the case.

Staring at it more closely, maybe it instead means this: Angular 2 now depends on a newer version of Zone.js than before, and the newer Zone.js has deprecated an older API, and the Angular 2 needs to be updated to use the newest Zone.js API. This was not immediately clear, using the polyfills file, and thus seeing only that the message comes from somewhere in the polyfills -  upon a moment's thought about the names though, they clearly imply Zone.js.  Sorry for the slow cognition on my part.

**Comment by langley-agm** [comment]
+1, please fix.

**Comment by platzhirsch** [comment]
It would indeed be good to see that fixed.

**Comment by pkozlowski-opensource** [comment]
This belongs to https://github.com/angular/zone.js where the code resides (angular2-polyfills.min.js just bundles zones plus other polyffils).

The actual warning is part of the zone.js code so please direct issues / PRs to the appropriate repo: https://github.com/angular/zone.js

**Comment by tamalnath** [comment]
@pkozlowski-opensource This warning is still coming in angular2-polyfills.min.js for version 2.0.0-beta.8 although @mhevery closed the other bug: [#262](https://github.com/angular/zone.js/issues/262).

**Comment by cexbrayat** [comment]
@tamalnath That's because beta.8 still use zone 0.5.15. It will be solved when a beta is released with zone 0.6.x.

**Comment by jthantranon** [comment]
FYI - Manually npm'd the new zone 0.6.2 and edited angular2 beta.8's package to use zone 0.6.2 and I'm still getting the DEP warnings.

**Comment by hhsadiq** [comment]
I am also getting the same warning in angular 2.0.0-beta.7. Did anyone find a solution to get rid off...?

**Comment by kylecordes** [comment]
The fix will come when the Angular team and/or Zone team take care of whatever issues standing in the way see some comments above for details.

But as a interim workaround, just open the polyfills source file, find the line of code that emits those warnings, and remove. I did this when I needed to do a demonstration of a bunch of unrelated Angular 2 features, and didn't want the limited space on the screen I was projecting in front of a bunch of people to be wasted on these irritating deprecation warnings.

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166559.
------------------------------------------------------------------------------------------------------------


[[8261746289663af3e6c7113dbd5b9d838a51c63e-673074312]]
