### ISSUE TITLE
Date pipe is not working well with custom format

### ISSUE THREAD

**Issue by kevinsdooapp** [angular/angular#7008]
Date pipe is not working well when custom format is used. ie: dd/MM/yyyy.

You can see an example in this plunker: http://plnkr.co/edit/nNpBNaB8z7DEnZdpj7gM?p=preview

**Comment by yfain** [comment]
Pipes are broken in general, i.e. number, currency, date work only in Chrome and Firefox. Try your plunker in Safari - it won't even run.

**Comment by positron** [comment]
`'MM/dd/yy hh:mm'` produces `02/10/16, 5:05 PM`

Notice the extra comma. Also I didn't ask for AM or PM.

**Comment by qina83** [comment]
+1

**Comment by rexebin** [comment]
+1

**Comment by tom10271** [comment]
+1 

More example: #6713

**Comment by wealima** [comment]
+1

**Comment by deepakgd** [comment]
+1
@wealima if i change dd/MM/yyyy to yyyy/MM/dd not working showing date as dd/MM/yyyy

**Comment by laskoviymishka** [comment]
this is definetely bug inside of extractComponents function in src/facade/intl
all that i can say when i look at this code is:
![image](https://cloud.githubusercontent.com/assets/2754361/14667138/4997d65a-06e6-11e6-9fb6-3ca23c13ddf2.png)

**Comment by laskoviymishka** [comment]
After some research i found that this code never suppose to fit this scenario. It should be reimplemented from a scratch (may be just clone ng1 implementation?). Currently formatter only looking on your locale and what you pass in pattern string not how (MM dd yyyy and dd MM yyyy is really same pattern for him). It have no affect to any formatting inside this pattern. In a fact it strongly coupled to https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat global object. 
According to spec and my knowledge this object is not suppose to cover this scenario (and also it not suppose to work in safari and some legacy browsers). So its pretty major issue, but we have good news! Someone who will work on it have no need to adjust every line of code to dart compiler :+1: couse dart have they own implementation of datetime object and own implementation of datetime formatter as well.

**Comment by allenhwkim** [comment]
+1

**Comment by NickThakkar** [comment]
I can not achieve this date time format with date pipe : '13 Sep 2016, 10:15 PM'

**Comment by kleeb** [comment]
+1

**Comment by mmantovani** [comment]
When i try {{value | date:"dd/MM/yyyy"}} with value "2016-10-31T00:00:00.000Z" it produces "30/10/2016". In general, it is formatting one day earlier.

**Comment by laskoviymishka** [comment]
What is your time zone?

**Comment by mmantovani** [comment]
Sorry, I am UTC-03:00 so it is showing dd/MM/yyyy of my local date, it's correct.

**Comment by francosioquim** [comment]
I can not achieve this date time format with date pipe : '13 Sep 2016,  
10:15 PM'

**Comment by dowrow** [comment]
{{ value | date:"HH:mm" }} is rendering as "23:30" on latest Chrome and Firefox and as "23:11:30" on Safari 9.0.2.

**Comment by schungx** [comment]
`DatePipe` for Angular 2 Release seems to be working fine for FireFox and Chrome with custom format strings.  However, it fails on Edge (interpreting HH, mm, ss etc. for different long formats).  Doesn't even work on Safari due to lack of Intl.

**Comment by kleeb** [comment]
@schungx for Safari all you need to do is to add this script to your index.html
`<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.en"></script>`

**Comment by hneuer** [comment]
Same problem here in Edge.
As this ticket is closed, should we stay away from datePipe and create a custom pipe?

**Comment by laskoviymishka** [comment]
There is bug in Edge. See https://github.com/Microsoft/ChakraCore/issues/1223 until it fixed probably it the only one option.

**Comment by AlekseyChuyan** [comment]
Testing my project on iPhone5 and Ipad. Date pipe doesn't work. If I add this src:
<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.en"></script>
angular even not loading. Guys, really, not working primitive pipes in stable angular version 2.3.0? Damn, I think it was our PM big mistake to start new project on "stable" angular2...

**Comment by mhevery** [comment]
@AlekseyChuyan 

1. this is closed issue, posting here, will have no effect.
2. File a new issue with a repro and a plunker link which we can easily reproduce. We have a lot of issues to look at, the easier you make it for us the more likely we will be able to get to the bottom and have a fix for you.
3. I understand that you are frustrated, and developing code often is, but please don't bring negative feelings here, since they are contiguous and don't improve the situation.

-- Misko

**Comment by milla** [comment]
A quick way is doing a custom pipe, momentjs works fine with IE11.
`moment(yourDate).format("YYYY-MM-DD HH:mm:ss")`

**Comment by santhakumarmano** [comment]
in need to get the record of table based on start and end date, get all record based on start and end date
