### ISSUE TITLE
Reloading the main component

### ISSUE THREAD

**Issue by rizwanhussain-vteams** [angular/angular#7009]
How do i reload the main component? Is there a way to reset the app? Also, is there a way to refresh/initialize just a single component?

**Comment by zoechi** [comment]
Why would you need that?
GitHub issues are for bug reports and feature requests. 
      For support questions please use other channels like [StackOverflow](http://stackoverflow.com/questions/tagged/angular2), [Gitter](https://gitter.im/angular/angular), [Google groups](https://groups.google.com/forum/#!forum/angular), ...

**Comment by RomanGotsiy** [comment]
@rizwanhussain-vteams to reset the app you can save [`ComponentRef`](https://angular.io/docs/ts/latest/api/core/ComponentRef-class.html) instance which is resolved by promise that [`bootstrap`](https://angular.io/docs/ts/latest/api/platform/browser/bootstrap-function.html) returns.

```js
var appRef;
bootstrap(App).then((_appRef) => {
  appRef = _appRef;
});
```
So you can call `dispose` method of `ComponentRef` instance (appRef) to destroy component and then you can bootstrap it again.

Anyway, @zoechi is right. You'd better to ask this question on SO

**Comment by pkozlowski-opensource** [comment]
Sounds like a support question that got resolved.
