### ISSUE TITLE
Enable end-to-end testing of Angular2 samples with DDC

### ISSUE THREAD

**Issue by vsmenon** [angular/angular#7010]
Many Angular2 samples are now running with DDC.  We should keep them regression tested.

Here are [existing e2e tests](https://github.com/angular/angular/tree/master/modules/playground/e2e_test):

- [ ] async
- [ ] hash_routing
- [ ] hello_world
- [ ] http
- [ ] jsonp
- [ ] key_events
- [ ] material
- [ ] model_driven_forms
- [ ] order_management
- [ ] person_management
- [ ] relative_assets
- [ ] routing
- [ ] sourcemap
- [ ] svg
- [ ] template_driven_forms
- [ ] web_workers
- [ ] zippy_component

This PR enables regression testing for hello_world:  #6783

@mhevery @vsavkin This should be on the DDC hot list.

**Comment by mhevery** [comment]
@juliemr, @vsmenon will talk to you about these.
