### ISSUE TITLE
Cannot find name 'Zone'

### ISSUE THREAD

**Issue by kisdaniel** [angular/angular#7015]
I cannot compile my angular 2 app with typescript, compiler's message is:

```
Running "typescript:base" (typescript) task
>> node_modules/angular2/src/core/zone/ng_zone.d.ts(2,37): error TS2304: Cannot find name 'Zone'.
>> node_modules/angular2/src/facade/lang.d.ts(2,22): error TS2304: Cannot find name 'BrowserNodeGlobal'.
```

my compiler settings:

```
typescript: {
        base: {
          src: ['src/main/resources/public/ts/*.ts'],
          dest: 'src/generated/resources/js',
          options: {
            "target": "es6",
            "module": "system",
            "moduleResolution": "classic",
            "emitDecoratorMetadata": true, 
            "experimentalDecorators": true,
            "removeComments": false,
            "noImplicitAny": false,
            // basePath: 'src/main/resources/ts/',
            sourceMap: false,
            declaration: true
          }
        }
      }
```

**Comment by alexeagle** [comment]
I assume this is angular2-2.0.0-beta.3
I think the moduleResolution: classic is causing a problem, I don't see how any of your imports from 'angular2/*' would resolve to node_modules. I suggest changing it to moduleResolution: node

**Comment by kisdaniel** [comment]
thanx for your help: I have compiled successfully my project by downgrading my angular version to 2.0.0-beta.0 and typescript version to 1.7.3. It seems that it would be nice if there were a angular platform like Spring platform in java that contains the versions of other libraries that can work together.

**Comment by alexeagle** [comment]
Yeah I think Igor wants to send a PR for
https://github.com/npm/npm/issues/11213 so you get all the right versions
together.

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166562.
------------------------------------------------------------------------------------------------------------


[[54c389479d0cfa68871262e92316cf4a9602af8a-673074321]]

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166565.
------------------------------------------------------------------------------------------------------------


[[b6a0d4ba86bfbe6e5c99766fc1eae5778d1b0d11-673074323]]
