### ISSUE TITLE
typings installed together with angular on postinstall

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#7016]
I can see you removed TSD and started using Typings. And I can see that on npm postinstall you do a typings install, which, unfortunately installs at root and it also does not update my own `typings.json`. @blakeembrey already informed me that you are aware of that though.

But if you plan to use `es6-collections` and `es6-promise` typings, you should know it lacks in a few definitions, I get a couple of complaints during TS compilation:
```shell
src/app/common/checkbox/checkbox.ts(22,12): error TS2304: Cannot find name 'module'.
src/app/common/firebase_array.ts(332,50): error TS2339: Property 'isNaN' does not exist on type 'NumberConstructor'.
src/app/common/firebase_array.ts(332,88): error TS2339: Property 'isFinite' does not exist on type 'NumberConstructor'.
src/app/common/glyph/glyph.ts(11,12): error TS2304: Cannot find name 'module'.
src/app/components/account/account.ts(10,12): error TS2304: Cannot find name 'module'.
src/app/components/app/app.ts(16,12): error TS2304: Cannot find name 'module'.
src/app/components/auth/auth.ts(10,12): error TS2304: Cannot find name 'module'.
src/app/components/login/login.ts(8,12): error TS2304: Cannot find name 'module'.
src/app/components/register/register.ts(10,12): error TS2304: Cannot find name 'module'.
src/app/components/reset_password/reset_password.ts(8,12): error TS2304: Cannot find name 'module'.
src/app/components/todo_list/todo_list.ts(14,12): error TS2304: Cannot find name 'module'.
src/app/components/todo_list_item/todo_list_item.ts(12,12): error TS2304: Cannot find name 'module'.
src/app/components/todos/todos.ts(14,12): error TS2304: Cannot find name 'module'.
src/app/components/todos_count/todos_count.ts(13,12): error TS2304: Cannot find name 'module'.
src/app/services/auth.ts(35,37): error TS2339: Property 'includes' does not exist on type 'string[]'.
src/app/services/chores.ts(22,11): error TS2339: Property 'assign' does not exist on type 'ObjectConstructor'.
src/app/services/user.ts(49,35): error TS2339: Property 'from' does not exist on type 'ArrayConstructor'.
src/app/validators/user_availability.ts(28,24): error TS2339: Property 'from' does not exist on type 'ArrayConstructor'.
```

You might consider switching back to `es6-shim`. But it would be nice to know the plan for this anyway.

**Comment by alexeagle** [comment]
I updated the breaking change description.
We do not want to give users all the es6 api typings, because that requires you polyfill all of them in the target runtime, which makes your app bigger. Angular 2 only requires polyfill for Promise and Collections, so those are the types we expose at `node_modules/angular2/typings/browser.d.ts`. If you want to be able to type-check against other es6 apis, and you are polyfilling all of them, then you should install the `es6-shim` typing yourself and ignore the typings in the Angular 2 distro (as you would if you `--target=es6`)
cc @wardbell

**Comment by rolandjitsu** [comment]
The problem is that it installed globally in my own typings folder. I guess you fixed that, right?

**Comment by alexeagle** [comment]
I don't think that's true - in my testing and based on understanding of postinstall, the typings command run in postinstall creates a typings directory under the package that owns the postinstall, meaning under `node_modules/angular2`

**Comment by rolandjitsu** [comment]
Not sure what happened, but it did install the two packages along my own. Then after I update to `beta.6` (and completely removed `node_modules` before), the issue was no longer there.

**Comment by blakeembrey** [comment]
@alexeagle Really? Guess I should check, but I believed `postinstall` run in the context of the current working directory which would mean the users folder. Anyway, over now, but I am still curious.

**Comment by alexeagle** [comment]
No it runs under the package's directory, that's actually prevented me
using it for something-or-other.
