### ISSUE TITLE
Issue when a query string is used on url without trailing slash

### ISSUE THREAD

**Issue by cadilhac** [angular/angular#7017]
Using Angular 1.5 in an asp.net mvc site.

I have a base tag:

`<base href="/fr/">`

and html5mode is set.

The site works perfectly. I use ui-router... no issues.
But today I hit one and this is when I try to browse to this kind of url:

http://example.com/fr?arg=1
http://example.com/fr/about?arg=1

I get an error from angular:

> url is undefined
> trimEmptyHash@http://............/angular.js?tag=2016020919:12165:3

If I navigate to /fr/?arg=1 (with the trailing slash) the error goes away.

In this context, is this a bug? How to get the query string to work without a trailing slash? "Normal" people typing a url normally will never put a slash before the question mark...

**Comment by RomanGotsiy** [comment]
@cadilhac this is Angular 2 repo. Angular 1.* issues should be reported to https://github.com/angular/angular.js

anyway I believe you're looking for [this](https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-make-a-trailing-slash-optional-for-all-routes)

**Comment by cadilhac** [comment]
Oh sorry, for that. I will report there.
About your FAQ, I had already tried strictMode to false and it didn't do anything.

**Comment by pkozlowski-opensource** [comment]
This belongs to  https://github.com/angular/angular.js
