### ISSUE TITLE
EventEmitter TypeScript interface differs from Dart facade

### ISSUE THREAD

**Issue by hansl** [angular/angular#7018]
Using `EventEmitter.prototype.subscribe` in TypeScript will compile successfully, but its implementation in the Dart facade lacks that method.

**Comment by zoechi** [comment]
`ObservableWrapper` has `subscribe` which forwards to Darts `listen`. Not sure if this is the right way to go though.
From other code I found it looks like it - for example https://github.com/angular/angular/blob/4fa1809f807958651ede509e23fe07279b404ce8/modules/angular2/test/facade/async_spec.ts#L110

**Comment by hansl** [comment]
Yes that's what I ended up doing. But since Angular is implementing an EventEmitter facade it should provide the same interface in TS than Dart.

**Comment by zoechi** [comment]
In Dart `listen` is used everywhere to subscribe, I don't think adding/introducing `subscribe` adds any value. 
Just my 2c

**Comment by hansl** [comment]
The implementation of the facade is faulty. This is not about Dart having a different API, it's about the same API in Angular2 itself being different for both languages (there're methods missing which leads to errors).

When a class is implemented in Angular2, you would expect its interface to be consistent between Dart and TS. Either add `subscribe` to Dart, or remove it from TypeScript.

**Comment by robwormald** [comment]
The only real public API for EventEmitter is `emit()` - the expectation is that the framework does the subscription internally -  eg `ObservableWrapper.subscribe(emitter, fn)` 

Really though, EventEmitter should be re-implemented as an idiomatic JS EventEmitter (unrelated to Streams or Observables) - its causing a *lot* of confusion, and then `Observable.fromEvent(emitter, 'click')` should be used (and whatever the equivalent in Dart is)

Things in the framework that currently expose EventEmitter - formControls, etc should really expose Observables (as they are read-only) - and I reckon we should facade `Observable` for Dart.

**Comment by robwormald** [comment]
to clarify:
- EventEmitter is (or should be, anyway) treated as "write-only" in the current implementation
- Observables are "read-only"
- if you want Observable-y behavior "downstream" with the ability to push values, use a `Subject` (think - message bus) (this is what EventEmitter currently extends, which is why you see `.subscribe()`

**Comment by pkozlowski-opensource** [comment]
Obsolete as Dart-specific.
