### ISSUE TITLE
angular2-polyfills.min.js references a non existent RxJS file

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#7019]
It looks like with the latest beta, `angular2-polyfills.min.js` is referencing a `rxjs/observable/fromPromise.js` file, which does not seem to exist in RxJS `beta.2`.

**Comment by SeriousM** [comment]
fixed with #7000. the dependency to RxJS was changed back to `5.0.0-beta.0` because of this issue

**Comment by alexeagle** [comment]
should be fixed by beta.6, just released.
