### ISSUE TITLE
PathLocationStrategy does not work with Cordova ("base" element breaks the app)

### ISSUE THREAD

**Issue by ignaciolarranaga** [angular/angular#7023]
Following the tutorial, in the moment you add the <base href="/"> the Cordova apps gets broken.
(https://angular.io/docs/ts/latest/tutorial/toh-pt5.html)

I tried the solution provided here but does not work too:
https://angular.io/docs/ts/latest/api/router/PathLocationStrategy-class.html

But the workaround provided here for the live example does work:
https://angular.io/docs/ts/latest/guide/router.html#!#base-href

**Comment by zoechi** [comment]
Can you please be more specific?
What is the current behavior? What is the expected behavior? What exactly have you changed as workaround.

**Comment by pkozlowski-opensource** [comment]
Closing as we haven't heard back from the opener.
