### ISSUE TITLE
Angular 2 promises without timeouts?

### ISSUE THREAD

**Issue by anyatran** [angular/angular#7025]
I'd like to do something similar to node.js promises in Angular 2, like .then() and other functions. I've been doing a bit of research and all I've found so far is using setTimeout() function to wait when the function has completed(ex: http://twofuckingdevelopers.com/2015/04/angular-2-singleton-service/). Is there any way to do the same thing without setting the timeout? I'd like to use that with http.get()

**Comment by robwormald** [comment]
could you explain what you mean exactly? Promises work fine in angular2, and they are native to the browser (they're not a node specific thing). You can also do `http.get(url).toPromise()`

**Comment by anyatran** [comment]
@robwormald actually I think I'd like something like done(), so to call another function once the first function is finished

**Comment by robwormald** [comment]
that's what promises do?

`doSomething().then(doSomethingElse).then(doSomethingMore)`

**Comment by robwormald** [comment]
Suggest you read up on Promises:
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise
- http://www.html5rocks.com/en/tutorials/es6/promises/
