### ISSUE TITLE
NgUpgrade "Only selectors matching element names are supported"

### ISSUE THREAD

**Issue by Zizzamia** [angular/angular#7026]
I start doing upgrade and I had this error at `getComponentInfo	@	metadata.ts:30`
```
Uncaught Error: Only selectors matching element names are supported, got: [navbar-info]
```

js
```js
var navbarInfo = ng.core.Component({
  selector: '[navbar-info]',
  template: '<h1>Hello Navbar Info!</h1>'
}).Class({
  constructor: function() {
  }
});

var adapter = new ng.upgrade.UpgradeAdapter();
angular.module('Plan.components.navbarInfo', [])
.directive('navbarInfo', adapter.downgradeNg2Component(navbarInfo));
```

html
```html
<div navbar-info class="col-xs-9 navbar-info"></div>
```

Thanks

**Comment by ronnievdv** [comment]
Getting the same error for Attribute Directive

js

`@Directive({
	selector: '[contextMenu]'
})

export class ContextMenuDirective {
}`

html
`<div contextMenu></div>`

error
`Only selectors matching element names are supported, got: [contextMenu]`

**Comment by marcalj** [comment]
Bad experience while upgrading to ng2 :(

**Comment by mhevery** [comment]
Working as intended.

The reason for this is that each element can only be owned by one framework. Attribute selectors would allow both frameworks to own the elements.

**Comment by DanielSchuech** [comment]
If you want to up- and downgrade attribute directives you can try [ngAdapter](https://github.com/DanielSchuech/ngAdapter)
It extends the angular upgrade with the support of attribute directives (with another approach).

**Comment by marcalj** [comment]
Hi, I misunderstood the issue. It's possible to use ng2 attribute components inside a ng2 component. The problem is mixing it with ng1 component. So ok for me! Thanks!
