### ISSUE TITLE
NgUpgrade "Error: Expecting HostViewFactoryRef for: navbarInfo"

### ISSUE THREAD

**Issue by Zizzamia** [angular/angular#7027]
Keep trying to make my first ng2 component in my ng1 app but I got this error.
```
Error: Expecting HostViewFactoryRef for: navbarInfo
    at directiveFactory (upgrade_adapter.ts:501)
    at Object.invoke (angular.js:4604)
    at angular.js:7475
    at n (angular.js:321)
    at Object.<anonymous> (angular.js:7473)
    at Object.invoke (angular.js:4604)
    at Object.$get (angular.js:4443)
    at Object.invoke (angular.js:4604)
    at angular.js:4403
    at Object.d [as get] (angular.js:4550)
```

```js
var navbarInfo = ng.core.Component({
  selector: 'navbar-info',
  template: '<h1>Hello Navbar Info!</h1>'
}).Class({
  constructor: function() {
  }
});

var adapter = new ng.upgrade.UpgradeAdapter();
angular.module('Plan.components.navbarInfo', [])
.directive('navbarInfo', adapter.downgradeNg2Component(navbarInfo));
```

```html
<navbar-info class="col-xs-9 navbar-info"></navbar-info>
```

thanks

**Comment by brandonroberts** [comment]
Are you bootstrapping using the upgrade adapter bootstrap method?

**Comment by Zizzamia** [comment]
Yes
```js
var adapter = new ng.upgrade.UpgradeAdapter();
window.adapter = adapter;

var appPlan = angular.module('Plan', [ ... ])
adapter.bootstrap(document.body, ['Plan']);
```

**Comment by brandonroberts** [comment]
I think your downgrading the component after you've already bootstrapped. Here is a working example.

http://plnkr.co/edit/WxN4EpYuLf8bf8bzhgKs?p=preview

**Comment by Zizzamia** [comment]
You were right! ThankYou so much :-)

Do you know how make it work the inputs?
```html
<navbar-info class="col-xs-9 navbar-info" [currentDay]="currentDay"></navbar-info>
```

I search for two hours without a solution that works :-(
Also if you have a clear idea to how import a service from ng1 to ng2 in ES5 that will be amazing.
Thanks a lot!

**Comment by amcdnl** [comment]
@brandonroberts is there anyway around this? I'm lazy loading my ng1 proj w/ @ocombe ocLazyLoad and my ng2 components are blowing up. See ^^^ issue.

**Comment by brandonroberts** [comment]
@amcdnl not that I know of. As I understand it, all your upgrades/downgrades have to be done before bootstrapping. I ran into the same issue with ocLazyLoad and ui-router. The app is broken up into separate modules and lazy loaded with ui-router and we couldn't use ngUpgrade because of this issue.

I think since lazy loading isn't built-in to ng1, this is considered an edge case but that's only my opinion. Maybe someone from the team can clarify? @mhevery

**Comment by amcdnl** [comment]
@brandonroberts Yes, I'm using ui-router and ocLazy too. This is a small case of my setup that I authored about a year ago [angular-systemjs-seed](https://github.com/Swimlane/angular-systemjs-seed).

How did you work around it? And yes, I'd say this is def a edge case probably only .1% are doing anything like this.

**Comment by brandonroberts** [comment]
@amcdnl I don't have a clear way around it. The only solution I got to work was basically to lose the lazy loading and bring the entire app back into one monolithic bundle, which wasn't a viable option. 

One thought would be to upgrade your necessary ng1 components upfront, use a downgraded ng2 component as your bootstrap component and do everything else inside ng2 components. Then you could use the lazy loading feature in Angular 2's Router to load in your modules before loading your routes. Just a thought though. 

Here is a sample plunker: http://plnkr.co/edit/HFu7bU?p=preview

**Comment by amcdnl** [comment]
@brandonroberts Ya, my ui-router is not gonna be easy to yank..actually prob one of the last things I can do. Honestly though, I was talking to @ocombe we think things are just getting loaded out of order. I'm gonna hack on it, will let u know what i come up w/!

**Comment by brandonroberts** [comment]
Cool :+1:

**Comment by duncangrist** [comment]
Same problem here. We're using the exact same pattern (ui-router, oclazyload) and wanting to start our migration to Angular 2. The fact that you have to declare all your downgrades up front is preventing us from lazy loading our Angular 2 components.

**Comment by amcdnl** [comment]
@duncangrist lets move this convo over to: https://github.com/ocombe/ocLazyLoad/issues/288

**Comment by slimovic** [comment]
@brandonroberts  I got the same error when I want to inject a service into that Directive like this [example](http://plnkr.co/edit/rJyKEdPV6IuCcj9JEYXC?p=preview).
I posted a [question ](http://stackoverflow.com/questions/40636264/downgrade-an-angular-2-component-to-use-it-in-angular-1-app-using-upgrade-adapte)in SO.

Thank you.

**Comment by amcdnl** [comment]
@slimovic - chk out this demo i made - https://github.com/swimlane/ng1-ng2-webpack-lazy-uirouter
