### ISSUE TITLE
latest beta.6 breaks typings...

### ISSUE THREAD

**Issue by born2net** [angular/angular#7033]
so I added the ref as indicated in change log.
```
///<reference path="node_modules/angular2/typings/browser.d.ts"/>
```

and yet in latest .6 I get a bunch of missing types now.
am I missing something? or feature broken?

![err](https://cloud.githubusercontent.com/assets/5090936/12999797/df3bc488-d107-11e5-942e-6c72def49f30.PNG)

regards

Sean

**Comment by JamesUlph** [comment]
`npm install typings --global
typings install es6-shim --ambient --save
typings install require --ambient --save
`
Cleared a similar batch of error up for me.

**Comment by valorkin** [comment]
@born2net thx for it
seems I will need to create typings peer dependencies in https://github.com/valor-software/ng2-bootstrap#quick-start

check this btw https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes
it could have more things to apply via typings

**Comment by born2net** [comment]
tx JamesUlph 
did you also get rid of the duplicates...?

![capture](https://cloud.githubusercontent.com/assets/5090936/13012976/661a9a56-d162-11e5-9a9e-c5b2748745b7.PNG)

**Comment by born2net** [comment]
in my case adding the es6-shim added a lot of duplicates with angular2, so I just cherry picked the ones I needed and I am good now...

in my case it was

```
/**
 * ES6 shims taken from /typings/browser/ambient/es6-shim
 */
interface ObjectConstructor {
    assign(target:any, ...sources:any[]): any;
}
interface ArrayConstructor {
    from:any;
}
interface String {
    repeat(count:number): string;
}
```

**Comment by valorkin** [comment]
@born2net check this https://github.com/valor-software/ng2-bootstrap/issues/175#issuecomment-183440516
