### ISSUE TITLE
<input> bount with [(ngModel)] is not added to NgForm

### ISSUE THREAD

**Issue by prupp81** [angular/angular#7036]
Hi,

when using **[(ngModel)]** on an **input** the *Control* is not added to the *NgForm*.

Let's assume following form: 
``` html
<form #f="ngForm">
    <template [ngIf]="!f.valid">form invalid</template>
    
    <input type="text" [(ngModel)]="firstName" ngControl="firstNameInput" #firstNameInput="ngForm" required/>    
    <template [ngIf]="!firstNameInput.valid">firstName invalid</template>
    
    <input type="text" [(ngModel)]="lastName" #lastNameInput="ngForm" required/>
    <template [ngIf]="!firstNameInput.valid">lastName invalid</template>    
</form>
```
When all input-fields are empty I get following output:
```
form invalid
firstName invalid
lastNameInvalid
```
When I enter a value in the *firstName* input-field I get the following output:
```
lastNameInvalid
```
So when I enter a value to the *firstName*-input-field the form assumes it's valid because it knows nothing about the *lastName*-input-field.

Accordingly the other way round - output when entering value only to *lastName*-input-field - the form isn't affected.

```
form invalid
firstName invalid
```
Is there a way - without using the formBuilder - that the *lastName*-input-field behaves as the *firstName*-input-field?

**Comment by zoechi** [comment]
I didn't fully dig into your problem but this looks like a copy-paste bug
```html
<template [ngIf]="!firstNameInput.valid">lastName invalid</template>    
```
should probably be
```html
<template [ngIf]="!lastNameInput.valid">lastName invalid</template>    
```

**Comment by prupp81** [comment]
thanks for the hint. This is indeed just a copy-paste problem. I fixed it in the initial post.

The problem is that a form consisting of inputs that are two-way-bound with ngModel has no connection to it's inner controls and the form.valid property has the wrong value.

**Comment by prupp81** [comment]
here is the plunker: https://plnkr.co/edit/NoItUai26ERZ9pTkjgth?p=preview

**Comment by antonybudianto** [comment]
you miss the ngControl on the second input
https://plnkr.co/edit/XvOLLUkmxTPObZJiRKzR?p=preview

**Comment by kara** [comment]
Yeah, as @antonybudianto mentioned, the ngControl is missing on the second input. In the (now) deprecated forms API, ngControl was necessary for form registration. In the new forms module, all you need is ngModel and a name to register an input properly with the parent form.  You can read more about it in the proposal doc here: https://docs.google.com/document/u/1/d/1RIezQqE4aEhBRmArIAS1mRIZtWFf6JxN_7B4meyWK0Y/pub.
 Closing, as this is fixed.
