### ISSUE TITLE
beta6: why adding direct reference to browser.d.ts?

### ISSUE THREAD

**Issue by yfain** [angular/angular#7038]
The Breaking Change in the change log reads this:

"Transitive typings are no longer included in the distribution.
If you use --target=es5, you will need to add a line somewhere in your application (for example, at the top of the .ts file where you call bootstrap):
```///<reference path="node_modules/angular2/typings/browser.d.ts"/>```"

My apps have es5 as a target, but they work just fine even without adding the above reference.  Could you provide a better explanation of why we need to add a direct reference to browser.d.ts?

**Comment by curlyfro** [comment]
+1

**Comment by dsebastien** [comment]
It depends on how you configure TypeScript I guess. If you only use exclude in tsconfig.json and exclude typings/main.d.ts & typings/main then you don't need the /// reference. If you use files in tsconfig.json then you either need to add the /// reference or add typings/browser.d.ts in the list of files, etc :)

**Comment by yfain** [comment]
My app uses the tsconfig shown below and works fine with beta.6 without adding /// reference:

{
	"compilerOptions": {
		"experimentalDecorators": true,
		"module": "commonjs",
		"target": "ES5"
	}
}

**Comment by antonybudianto** [comment]
it works because you didn't specify `exclude` option, [for reference](https://github.com/Microsoft/TypeScript/issues/3043)

**Comment by dachibro** [comment]
You can also just include the `browser.d.ts` in the `tsconfig.json` like so:

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "removeComments": true,
    "experimentalDecorators": true
  },
  "filesGlob": [
    "node_modules/angular2/typings/browser.d.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

This way you can exclude the reference path in your application's bootstrap file.

**Comment by CaptainCodeman** [comment]
I never understood this. I exclude node_modules in tsconfig and don't add any ref anywhere and everything works fine. It must be using witchcraft instead.

**Comment by kylecordes** [comment]
filesGlob is not a TypeScript feature. It is something from Atom editor integration.

files *never* works in conjunction with exclude. If you use files, exclude is ignored.

There are highly numerous broken tsconfig examples all over the web.

My advice: don't use exclude. Use files: and point it to the right starting points. It will follow references form there.

**Comment by dachibro** [comment]
@kylecordes I did not know that filesGlob was an Atom feature... I actually didn't even know that the atom property was a reference to the editor; I thought it was something completely different.

I'm trying to build my own "starter" project from the ground up.  It looks like a lot of the existing starter projects borrow from each other, and I really want to understand how everything fits together.  I'm not even close to finished, just starting actually.  Changing my original snippet to:

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "removeComments": true,
    "experimentalDecorators": true
  },
  "files": [
    "node_modules/angular2/typings/browser.d.ts"
  ]
}
```

**Comment by kylecordes** [comment]
Getting back to the topic started this thread, you are on the right track here. In addition to listing that d.ts file, you would also need to add any other starting point files, most importantly the topmost file in your own application. And if you have anything brought in via the typings tool, you would point to something like "typings/browser.d.ts".

**Comment by pkozlowski-opensource** [comment]
Sounds like a support question that got resolved. Thnx @kylecordes
