### ISSUE TITLE
Docs: "ngOnDestroy" method description can be a little bit confusing

### ISSUE THREAD

**Issue by radek-anuszewski** [angular/angular#7039]
In [The Lifecycle Hooks](https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html) chapter we can read:
> ngAfterContentInit - after **component** content initialized
> ngAfterContentChecked - after every check of **component** content
> ngAfterViewInit - after **component's** view(s) are initialized
> ngAfterViewChecked - after every check of a **component's** view(s)
> ngOnDestroy - just before the **_directive_** is destroyed.

I thought, at first glace, that `ng*` hooks work for `component`s except `ngOnDestroy` which works only for `directive`s. Of course I tested it and test showed I was wrong, but maybe is worth to write:
> ngOnDestroy - just before the **component** is destroyed.

To avoid misunderstanding?

Thank you in advance for looking on this post.

Best regards,
Radek.

**Comment by zoechi** [comment]
Components are subclasses directives. What applies to directives also applies to components (not necessarily vice versa)

**Comment by pkozlowski-opensource** [comment]
If there are any remaining docs corrections a separate issue (or even better - a pull request!) shell be opened in https://github.com/angular/angular.io
