### ISSUE TITLE
If the transpiler erases IMPLEMENTS in generated Dart code, it should remove the import as well

### ISSUE THREAD

**Issue by kevmoo** [angular/angular#704]
test/core/compiler/ view_spec.js and view_container_spec.js both use the `@IMPLEMENTS` annotation

but the generated Dart code doesn't have it – leading to an 'unused import' warning.

**Comment by kevmoo** [comment]
I'm noticing some other things from `package:angular2/src/facade/lang.dart` that seem like they could be removed from generated Dart – and might allow the removal of the import entirely in many cases

* CONST
* Type
* int
* ABSTRACT

**Comment by yjbanov** [comment]
Should we merge this with #638?

**Comment by kevmoo** [comment]
Yup!
