### ISSUE TITLE
Pipe issue in Routed external template

### ISSUE THREAD

**Issue by mcgear** [angular/angular#7040]
I am trying to get a plunker together to demo this issue i am having with pipes in a routed template.  But to do that i need to first get this plunker working to show the home.htm page.

Any thoughts on why this Plunker won't show the HomeComponent content in the router-outlet?
https://plnkr.co/edit/dah76BS50mrQTw1KhvE9?p=preview

I'll update plunker to show my issue once i can get past this

**Comment by brandonroberts** [comment]
@mcgear you're missing a few things for routing.

You need

1. A `<base href=".">` in your index.html `<head>`
2. Import and add `ROUTER_PROVIDERS` to your bootstrap array
3. Import and add `ROUTER_DIRECTIVES` to your component `directives` array

**Comment by mcgear** [comment]
Thank you, i new it would be easy.

In the end, i just figured out the issue with the pipes.  It had to do with using the angular2.min.js file. When switching to the .dev.js file the pipe issue was resolved.

SO something in the min file was breaking it in the way i was using it

**Comment by brandonroberts** [comment]
Yep. There are issues with the minified builds, since beta.1: See #6380

**Comment by IgorMinar** [comment]
yup. this is a dupe. please see my assessment of the issue: https://github.com/angular/angular/issues/6380#issuecomment-203247147
