### ISSUE TITLE
Error when switching to angular2.min.js dependency in the hero form

### ISSUE THREAD

**Issue by user414** [angular/angular#7041]
Getting this in my code as well but easier to show on the official hero form. Here is the plunk of the official hero form with the dev dependency changed into min.

http://plnkr.co/edit/hKCBa1RDob5H9i9x7ZhT?p=preview

There error you get is

```
No provider for t! (t -> t)
```
And when you switch back to dev it goes away.

**Comment by brandonroberts** [comment]
There are issues with minified builds. See: https://github.com/angular/angular/issues/6380

**Comment by user414** [comment]
@brandonroberts  Thanks, sorry hadn't seen that one, will close this then as a duplicate of 

[beta.2] ngDoCheck is not a function when using minified bundles #6380
