### ISSUE TITLE
Beta 6 Safari Issue

### ISSUE THREAD

**Issue by mcgear** [angular/angular#7043]
Hey All,

So i just upgraded from Beta 0 to Beta 6, and maybe i missed something for safari support because it hasn't been working since Beta 0.  

http://pedalr.azurewebsites.net

This example fails for me on safari with error:
Error
line: 740
message: "'undefined' is not a constructor (evaluating 'new t.Map')↵	Error loading http://pedalr.azurewebsites.net/app/boot.min.js"
sourceId: 2099363264
sourceURL: "http://pedalr.azurewebsites.net/lib/system/js/system.js"
stack: undefined
__proto__: Error

Any help would be greatly appreciated.

**Comment by mcgear** [comment]
So i had some other deploy issues, and didn't want any extra complexity, so here is a plunker.. Open in Chrome and it works, open in safari (for PC) and nothing.
https://plnkr.co/edit/dah76BS50mrQTw1KhvE9?p=preview

**Comment by vicb** [comment]
obsolete
