### ISSUE TITLE
$q.when(value)'s promise does not get resolved when manually trigger a digest cycle from tests

### ISSUE THREAD

**Issue by yklee1013** [angular/angular#7047]
I'm using Jasmine/Karma to test an angular app, the function I'm testing looks something like this:

```
function foo() : ng.IPromise<SomeInterface>{
  var promise : ng.IPromise<SomeInterface> = returnedFromSomeAPI();
   return promise.then((data : SomeInterface) => {
           return this.$q.when(data.someAttribute);
    })
}
```

My test triggers $rootscope.$apply() right after calling foo(), but for some reason the promise inside of "this.$q.when(data.someAttribute);" does not get resolved with value. I tried triggering two digest cycles right after(one for promise.then and another for resolving promise inside of when()), but it still didn't work. 

I'm using Angular 1.3. Is this a bug?

**Comment by ericmartinezr** [comment]
@yklee1013 this repo is for ng2. You're looking for https://github.com/angular/angular.js . I recommend you though to ask in their gitter channel before opening an issue https://gitter.im/angular/angular.js
