### ISSUE TITLE
brocolli-typescript does not work with TS 1.9

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#7050]
The paths passed to `getScriptSnapshot` now all appear absolute, so we cannot resolve paths (eg. rxjs and .d.ts files in our sources)

**Comment by alexeagle** [comment]
FYI @IgorMinar our `typescript_next` build is disabled on Travis due to this issue. I don't have time to work  on this right now.

**Comment by alexeagle** [comment]
Actually it seems this problem also blocks Angular moving to the current release of TypeScript:
https://travis-ci.org/angular/angular/jobs/112191616

We need a broccolli maintainer

**Comment by mprobst** [comment]
@IgorMinar @vikerman what's the status of this? I'd be very nice if we could move forward here, this blocks adopting ts2dart v0.8.

**Comment by alexeagle** [comment]
Igor and Chuck have some PRs pending, I think they will land today, getting
angular2 on TS 1.8.
I'd like to get to TS 1.9 but we need to lower the output .d.ts files to
1.8-compatible; TS is putting 'readonly' modifiers in there.

**Comment by IgorMinar** [comment]
@mprobst does ts2dart depend on 1.9 or 1.8?

**Comment by mprobst** [comment]
>
> @mprobst does ts2dart depend on 1.9 or 1.8?
>

No, just 1.8 IIRC (@alexeagle will know exactly).

**Comment by alexeagle** [comment]
That's correct because that's what is stable in google3.
But we will move one or the other or both to 1.9 as soon as we can.

**Comment by alexeagle** [comment]
@chuckjaz has done most of the work fixing broccoli and angular2 to work with TS 1.9, this is almost done.
