### ISSUE TITLE
AsyncRoute doc out-of-date ?

### ISSUE THREAD

**Issue by gbataille** [angular/angular#7056]
Hi

from https://github.com/angular/angular/blob/2.0.0-beta.6/modules/angular2/src/router/route_config_impl.ts#L96-L140
I think the doc is not consistent with the typedef

I can't instantiate an AsyncRoute without passing ALL the params (data, useAsDefault, aux) that are supposedly optional. They are not marked with a '?'. Typescript will complain without those.

Are those really necessary?

**Comment by brandonroberts** [comment]
You don't have to pass all the params for an Async Router. At a minimum you need a `component`, `path`, and a `loader`

**Comment by gbataille** [comment]
that's what the doc said but the compiler threw an error, and if I'm not
mistaken, the params are not defined with '?'

**Comment by brandonroberts** [comment]
They are marked with a ?. Can you share you route?

**Comment by gbataille** [comment]
Well I was just playing around, I threw away the code cause I got stuck
anyway on something else.
AsyncRoute need SystemJS to load files async, and with webpack bundling
everything together in one file, I could not figure out how to do it.

I'll try again in a sandbox and let you know if I can reproduce the issue
then.

**Comment by brandonroberts** [comment]
I see. An AsyncRouter in webpack looks something like this:

```js
  new AsyncRoute({ 
    path: '/',
    name: 'Home',
    loader: () => new Promise(resolve => {
      (<any>require).ensure(['./routes/home'], require => resolve(require('./routes/home').Home));
    })
  })
```

**Comment by gbataille** [comment]
wow, I had an idea of doing something like that, but I was quite far from
it...
I'll give it a second try and double check on the AsyncRoute definition.

Let's just close this issue and I'll reopen it if I reproduce it

**Comment by gbataille** [comment]
I retried the Async route. It does compile with only name, path and loader. Don't know what I was doing.
I'll close the issue and I'll try the webpack snippet you gave me.

Thanks

**Comment by gbataille** [comment]
@brandonroberts Oh man, this just works. Thanks a lot. There is nothing (that I could find) on the web to do that.
I had an idea to use require.ensure to create the split point, but I did not know how to make it "Promisy" and return the component in the Promise.
