### ISSUE TITLE
Grandchild Component will not update Parent's/Grandparent's model

### ISSUE THREAD

**Issue by gabogabu** [angular/angular#7060]
I have the following scenario.  I have a **Grandparent** component which passes a value to a **Parent** component.  When one changes a value in the **Parent** component, the values of the **Grandparent** component also changes.  However, if I add a **Child** component to the **Parent** component, the changes on the **Child** component are not reflected to the **Parent**/**Grandparent**.

In the following plunker I have extended the example in the tutorial to show what I mean:
http://plnkr.co/edit/pWacvfr1p1VxU5GjVNs8?p=preview

In the plunker I added the power-select.component which is a child component of the hero-detail.component. In the application, if one chooses a Hero and proceeds to change the Hero's power, it will not be reflected in the model (seen in the json string below).

I have been trying to figure out what is wrong for a few hours, but I can't seem to know what it is.

**Comment by machi1990** [comment]
If you want changes on a Child Component to be reflected back to parent component you need to use declare an Output event with event emitter. If you need two way data binding (input and output) you can easily do so by adding
 `@Input() public power: string; 
  @Ouput() public powerChange:EventEmitter<string> = new EventEmitter()
` and then if emit any changes of the power property inside the child with a something like  `powerChange.next(this.power)`. 

With these lines inside you child component, the parent component can listen to any changes of the power property: `<power-select [(power)]="hero.power"></power-select>`.

**Comment by zoechi** [comment]
http://plnkr.co/edit/p9YcfGudIgSbGPp1xrlw?p=preview (like @machi1990 already explained)

GitHub issues are for bug reports and feature requests.  
For support questions please use other channels like [StackOverflow](http://stackoverflow.com/questions/tagged/angular2), [Gitter](https://gitter.im/angular/angular), [Google groups](https://groups.google.com/forum/#!forum/angular), ...

I understand that this might have looked like a bug to you and it's great that you reported it, but please consider to ask before reporting a bug.

**Comment by gabogabu** [comment]
I am sorry, I really should have first asked in one of the channels you said.  However what you guys said confuses me a bit so I posted a question in stackoverflow.
https://stackoverflow.com/questions/35393980/angular2-change-detection-in-components

Note: I thought you didn't need the @Output eventemitter since you are changing the same model that is passed from the parent. It works if you pass an object, but not a string.

**Comment by machi1990** [comment]
The way you described it works only for Object values (since it's the reference being passed). This will not work primitive types i.e string, booleans, int etc, hence the need of an Ouput event.

**Comment by gabogabu** [comment]
Ah thank you very much I really got confused.  I did forget immutability, but now I got it.
