### ISSUE TITLE
RouteParams in AppComponent 

### ISSUE THREAD

**Issue by playerx** [angular/angular#7061]
Hello,

When I try to inject RouteParams in AppComponent:
```ts
import {Component, OnInit} from 'angular2/core'
import {RouteConfig, ROUTER_DIRECTIVES, RouteParams} from 'angular2/router'
import {UIMatrix}     from './matrix'
import {ConfigProvider} from './Providers/ConfigProvider'
import {ROUTER_PROVIDERS} from 'angular2/router';

@Component({
    selector: 'game',
    template: `
    <router-outlet></router-outlet>
    `,
    providers: [ROUTER_PROVIDERS],
    directives: [ROUTER_DIRECTIVES]
})
@RouteConfig([
    { path: '/play/:channel', name: 'Play', component: UIMatrix }
])
export class AppComponent {

    constructor(private routeParams: RouteParams) {
    }
}
```

I get folowing error:
> EXCEPTION: No provider for RouteParams! (AppComponent -> RouteParams)

But when I try to inject in UIMatrix component, everything works fine.

Why is that limitation and is it an issue ? For me it's issue because I need to put some logic in AppComponent class.

Thanks

**Comment by zoechi** [comment]
I think `ROUTER_PROVIDERS` should only be added to `bootstrap(AppComponent, [...])` otherwise you'd get new instances of all providers listed in `ROUTER_PROVIDERS` for every component but only the shared ones contain the data you'd probably want to access.

**Comment by ericmartinezr** [comment]
dup of https://github.com/angular/angular/issues/4016
