### ISSUE TITLE
Documentation Update for Http neccessary

### ISSUE THREAD

**Issue by Batch1211** [angular/angular#7062]
As described in #5632, Observables only ship with the .subscribe method. All other operators have to be imported. This should definetely go into the documentation, since the Http Doc makes use of the .map() operator without mentioning the necessary import. This can be very frustrating for developers who just get startet with the framework.

The fact that almost all tutorials on the Http Component use the .map operator without mentioning the neccessary import makes it even worse.

Maybe it would be smart to document the Rx/Observable Object seperately and link to it from the various points of usage.

**Comment by ericmartinezr** [comment]
There's already a PR for that https://github.com/angular/angular/pull/5947

**Comment by Batch1211** [comment]
Thanks for pointing this one out.
