### ISSUE TITLE
Are multiple nested routes supported?

### ISSUE THREAD

**Issue by bastienJS** [angular/angular#7063]
I hope I gave it the correct naming:

**/companies/3/employees/edit/1**

I want to have a state where I edit the employee with Id 1 belonging to the company with Id 3.

Is that scenario already supported?

**Comment by danieleds** [comment]
I think you want this: https://github.com/angular/angular/issues/6985

**Comment by bastienJS** [comment]
On a first read it seems yes.

**Comment by brandonroberts** [comment]
@bastienJS yes, multiple nested routes are supported. Here is another example: http://plnkr.co/edit/ZM5sltrwn0HdATYjOzlD?p=preview

Basically when you want to add another level, add three periods to the end of your route path `/path/...`, add a `@RouteConfig([...])` to your parent component, and `ROUTER_DIRECTIVES` to the component directives, and a `<router-outlet></router-outlet>` to the template

**Comment by bastienJS** [comment]
@brandonroberts thx I will do that when needed. Do you know of any migration plan for ui router (which I used with ng1) to the new ng2 router?

**Comment by brandonroberts** [comment]
The ui-router folks said they would have an ng2 version of ui-router coming with some possible upgrade strategy, but that's as much as I know about it.

**Comment by peterchang770820** [comment]
Excute me. What mean is that route path `/...` ? Why is this written?

**Comment by zoechi** [comment]
To indicate that there are child routes (the component added by this route itself has routes). This doesn't apply to the new router introduced in RC.0. There is no `/...` anymore.

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)
