### ISSUE TITLE
Unable to resolve Typings dependencies

### ISSUE THREAD

**Issue by mariomatar** [angular/angular#7066]
Hi, 

I juste use the config of https://angular.io/docs/ts/latest/quickstart.html#!#package-json

And I have error about Typings when I run 'npm install'

Have an idea about it ? How to sole it ?

My Config :

config.json

{
    "name": "app-front-admin",
    "version": "1.0.0",
    "description": "App Admin",
    "author": "Project",
    "license": "private",
    "readme": "README.md",
    "private": true,
    "scripts": {
      "postinstall": "npm run typings install",
      "tsc": "tsc",
      "tsc:w": "tsc -w",
      "lite": "lite-server",
      "start": "concurrent \"npm run tsc:w\" \"npm run lite\" ",
      "typings" : "typings"
    },
    "dependencies": {
      "angular2": "2.0.0-beta.6",
      "systemjs": "0.19.20",
      "es6-promise": "^3.0.2",
      "es6-shim": "^0.33.3",
      "reflect-metadata": "0.1.2",
      "rxjs": "5.0.0-beta.0",
      "zone.js": "0.5.14"
    },
    "devDependencies": {
      "concurrently": "^1.0.0",
      "del": "latest",
      "gulp": "latest",
      "gulp-autoprefixer": "latest",
      "gulp-cssbeautify": "latest",
      "gulp-csscomb": "latest",
      "gulp-csso": "latest",
      "gulp-less": "latest",
      "gulp-load-plugins": "latest",
      "gulp-rename": "latest",
      "gulp-swagger": "latest",
      "gulp-connect": "latest",
      "gulp-typescript": "latest",
      "lite-server": "^2.0.1",
      "typescript": "^1.7.5"
    }
  }

tsconfig.json

{
    "compilerOptions": {
      "target": "ES5",
      "module": "system",
      "moduleResolution": "node",
      "sourceMap": true,
      "emitDecoratorMetadata": true,
      "experimentalDecorators": true,
      "removeComments": false,
      "noImplicitAny": true,
      "suppressImplicitAnyIndexErrors": true
    },
    "exclude": [
      "node_modules"
    ]
  } 

The error : 

    ~/dev/project/app/app-front-admin on  dev! ⌚ 14:45:26
    $ npm install
    npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.

    > app-front-admin@1.0.0 postinstall /home/momo/dev/project/app/app-front-admin
    > npm run typings install

    > app-front-admin@1.0.0 typings /home/momo/dev/project/app/app-front-admin
    > typings "install"

    typings ERR! message Unable to resolve Typings dependencies
    typings ERR! caused by Unable to find "typings.json" from "/home/momo/dev/project/app/app-front-admin"

    typings ERR! cwd /home/momo/dev/project/app/app-front-admin
    typings ERR! system Linux 3.16.0-60-generic
    typings ERR! command "/home/momo/dev/project/app/app-front-admin/node/node" "/home/momo/dev/project/app/app-front-admin/node_modules/typings/dist/bin/typings-install.js"
    typings ERR! node -v v4.3.0
    typings ERR! typings -v 0.6.8

    typings ERR! If you need help, you may report this error at:
    typings ERR!   <https://github.com/typings/typings/issues>

    npm ERR! Linux 3.16.0-60-generic
    npm ERR! argv "/home/momo/dev/project/app/app-front-admin/node/node" "/home/momo/dev/project/app/app-front-admin/node/node_modules/npm/bin/npm-cli.js" "run" "typings" "install"
    npm ERR! node v4.3.0
    npm ERR! npm  v3.7.3
    npm ERR! code ELIFECYCLE
    npm ERR! app-front-admin@1.0.0 typings: `typings "install"`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the app-front-admin@1.0.0 typings script 'typings "install"'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the app-front-admin package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     typings "install"
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs app-front-admin
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls app-front-admin
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /home/momo/dev/project/app/app-front-admin/npm-debug.log

    npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
    npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.7
    npm ERR! Linux 3.16.0-60-generic
    npm ERR! argv "/home/momo/dev/project/app/app-front-admin/node/node" "/usr/bin/npm" "install"
    npm ERR! node v4.3.0
    npm ERR! npm  v3.7.3
    npm ERR! code ELIFECYCLE
    npm ERR! app-front-admin@1.0.0 postinstall: `npm run typings install`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the app-front-admin@1.0.0 postinstall script 'npm run typings install'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the app-front-admin package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     npm run typings install
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs app-front-admin
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls app-front-admin
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /home/momo/dev/project/app/app-front-admin/npm-debug.log

**Comment by pe8ter** [comment]
It says `Unable to find "typings.json"`. Did you create that file in your project?

**Comment by mariomatar** [comment]
it's that ! ...
thank you

**Comment by Namek** [comment]
@mariomatar please close the issue if you're done asking

**Comment by Vannevelj** [comment]
Would it make sense to automatically create an empty `typings.json` file? I had to do it manually myself after finding this issue so it seems like a step that can be done when installing typings.

**Comment by tom94zoe** [comment]
I have the same issue, but the typings.json is already there.
