### ISSUE TITLE
chore: improve error message when multiple components use same selector

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular#7067]
I accidently ran into this due to copy and pasting. Forgot to change the selector of the copied component, here's the error I got:

```
EXCEPTION: Template parse errors:
More than one component: ComponentEight,ComponentNine ("

    <ul>
      <li>[ERROR ->]<cmp-eight></cmp-eight></li>
      <li><cmp-nine></cmp-nine></li>
    </ul>
"): ComponentFour@4:10
```

While this actually already gives enough information, I think we can do better with the `"More than one component"` message. Maybe we can make it sth. like `"The following components have the same selector: Cmp1, Cmp2"` ?

/cc @vsavkin

**Comment by kinggolf** [comment]
Thanks Pascal. I did the same exact thing just today and could not figure out what was going on, until I read your suggestion.

**Comment by SnareChops** [comment]
+1 here. Just bumped into this myself. Thanks Pascal for saving me probably a few hours of headache and searching.

**Comment by vicb** [comment]
note: It could be the same or *intersecting* selector. PR welcome, it should be an easy one

**Comment by Vercaelus** [comment]
Howdy! I'd like to begin making open source contributions, and this seems like a simple enough fix, but I'm not sure where to look, or what is involved. Is this just a wording fix in a .txt file, or is there more to it than that?

**Comment by nottinhill** [comment]
There's more to it than a .txt file, Vercaelus

**Comment by Vercaelus** [comment]
Thanks for the reply, Nottinhill. Do you know how I might find the source files of the error messages?

**Comment by jkyoutsey** [comment]
Honestly, this message means nothing to me.  I'm getting it now and it does nothing to help me know what is the source of the problem, or how to fix it.
```
"Template parse errors:↵More than one component: CellAuthoringComponent,CellComponent ("ernalProperties.columns}}" sio2Dropzone (dropped)="onDropped($event)" [accepts]="acceptCheck">
↵    [ERROR ->]<sio2-cell *ngFor="let colNum of (properties.columns | sio2Range)" [columnsSplit]="properties.columns"): LayoutAuthoringComponent@1:4↵More than one component: CellAuthoringComponent,CellComponent (" colNum of (properties.columns | sio2Range)" [columnsSplit]="properties.columns" ></sio2-cell>
↵    [ERROR ->]<sio2-cell *ngFor="let child of children"></sio2-cell>
↵</div>
↵"): LayoutAuthoringComponent@2:4"
```

**Comment by vicb** [comment]
@jkyoutsey it says that you have "More than one component: CellAuthoringComponent,CellComponent" (that's 2) at "ERROR ->]<sio2-cell>..."

I guess those 2 components use `selector: 'sio2-cell` which would be an obvious error.

If you need more help please use the support channels (gitter, SO)

**Comment by stchoukeu** [comment]
Good Morning to everyone,
Please i need your help. I'm facing this problem witch seem to be similar to the one you describe here. i'm not able to solve it. This is an Error message that i receive during the build process.
Error: Template parse errors More than one component: Button Item (" ngc failed ionic-app-script task: "build"  Error: Error

**Comment by zoechi** [comment]
@stchoukeu [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by stchoukeu** [comment]
Please it is a problem and  i can't go trought it because i have not wrote
Burton or Item component.

Le 27 nov. 2016 3:32 PM, "Günter Zöchbauer" <notifications@github.com> a
écrit :
