### ISSUE TITLE
Pass params when using EventEmitter

### ISSUE THREAD

**Issue by chinookproject** [angular/angular#7069]
Simply put, is it possible to pass parameters when using an `EventEmitter`?

I'm trying create a simple directive for a third party javascript library. In my case, jQueryUI's Sortable plugin. You can register a callback function when a specific event occurs, like "start drag" or "stop drag" etc. I'd like to handle those events in my page Component instead of the Directive, since it always holds custom logic.

The jQueryUI sortable event passes two parameters to a callback function. One is `event` and the other is `ui`. (API Ref: http://api.jqueryui.com/sortable/#event-start)

I'm able to recieve the `event` param in my custom function by putting a `$` dollar sign in front of the property name. (See plnkr code for more details). But I have no clue how to get the other param `ui` in my method as well. Is there currently any way to achieve this?

Here is a plnkr of my current situation:  http://plnkr.co/edit/5ACcetgwWWgTsKs1kWrA?p=info

**Comment by ericmartinezr** [comment]
@chinookproject your plnkr is actually not your plnkr :P

**Comment by chinookproject** [comment]
@ericmartinezr Oops, updated with correct link :)

**Comment by ericmartinezr** [comment]
You can pass an object holding both values

```
          stop: (event, ui) => {
            this.stopSort.emit({event:event, ui:ui}); 
          }
```

And then you get them as usual

```
 <ul id="sortable" sortable (stopSort)="stopSort($event)">

  stopSort(data) { // How do I get the 'event' and 'ui' params here?
    // do something with data.event
    // do something with data.ui
  }
```
Here's a plnkr with the above working http://plnkr.co/edit/Oxr5ga66EdQ1S7F6ihHm?p=preview

**Comment by chinookproject** [comment]
Awesome, thanks a lot!
