### ISSUE TITLE
setElementStyle in beta 6 vs beta 2

### ISSUE THREAD

**Issue by SergeyBarskiy** [angular/angular#7072]
In beta 6 in order to set a style in a directive, I called 
this._renderer.setElementStyle(this._element, 'font-size', '200%');

As of beta 6, I have to pass in nativeElement instead of ElementRef.
this._renderer.setElementStyle(this._element.nativeElement, 'font-size', '200%');

It seems that the original implementation was better and more intuitive.
Thanks.

**Comment by pkozlowski-opensource** [comment]
It was a documented breaking change, see changelog.
