### ISSUE TITLE
Tour of Heroes tutorial not working with minimized angular2 & router

### ISSUE THREAD

**Issue by kinggolf** [angular/angular#7074]
Using Angular2 tutorial Plunker at bottom of page
https://angular.io/docs/ts/latest/tutorial/toh-pt5.html

Works with these files:
`    <script src="https://code.angularjs.org/2.0.0-beta.6/angular2.dev.js"></script>`
`    <script src="https://code.angularjs.org/2.0.0-beta.6/router.dev.js"></script>`
Works with these files:
`    <script src="https://code.angularjs.org/2.0.0-beta.6/angular2.js"></script>`
`    <script src="https://code.angularjs.org/2.0.0-beta.6/router.js"></script>`
Does not work with these files:
`    <script src="https://code.angularjs.org/2.0.0-beta.6/angular2.min.js"></script>`
`    <script src="https://code.angularjs.org/2.0.0-beta.6/router.min.js"></script>`

**Comment by ericmartinezr** [comment]
Yes, there are issues with minified bundles since beta.1

**Comment by RomanGotsiy** [comment]
#6380

**Comment by laco0416** [comment]
This problem is still in beta.7

**Comment by IgorMinar** [comment]
yup. this is a dupe. please see my assessment of the issue: https://github.com/angular/angular/issues/6380#issuecomment-203247147
