### ISSUE TITLE
ChangeDetectionRef.reattach restores the CD mode to CheckAlways instead to the original

### ISSUE THREAD

**Issue by alfonso-presa** [angular/angular#7078]
While playing a little bit with change detection to investigate #7055 and #7054 I've realized that `ChangeDetectionRef.reattach` restores the CD mode to CheckAlways instead to the original ChangeDetectionMode that was used before detach. ¿Is this by design or is it a bug?

See this plunker to replicate:
http://plnkr.co/edit/8FnczklxX1WlRfWpquvM?p=preview

* Click on trigger buttons to see how OnPush strategy is working.
* Toggle the CD  in the internal component to detach and try trigger again.
* Toggle again and play with triggers. Now the internal component is always checked.

**Comment by jjpeters67** [comment]
[fetch] "A Value is but... [Web-pl...] Remove a... [Web fun...] Add Es 2015 Proxi...] [Web fun...] #2466-Adds in de... [Web-pl...] Add OW... [Web fun...] VP9 in Web RTC/... Adds smooth scroll... @17041149
