### ISSUE TITLE
Broken import paths for "parse5/index"

### ISSUE THREAD

**Issue by laco0416** [angular/angular#7081]
I tried to use `angular2/platform/testing/server`.

appSpec.ts

```ts
import "es6-promise";
import "es6-collections";
import "zone.js";
import "reflect-metadata";
import "rxjs/Rx";

import {ApplicationRef, provide, platform} from "angular2/core";
import {TEST_SERVER_PLATFORM_PROVIDERS, TEST_SERVER_APPLICATION_PROVIDERS} from "angular2/platform/testing/server";

describe("MyApp", () => {

  let application:ApplicationRef;
  beforeEach(()=> {
    application = platform(TEST_SERVER_PLATFORM_PROVIDERS).application(TEST_SERVER_APPLICATION_PROVIDERS);
  });
});
```

However compilation was failed in `angular2/src/platform/server`. 

```
Error: Cannot find module 'parse5/index' from '/Users/laco/Works/angular2-example/node_modules/angular2/src/platform/server'
```

that import paths are found in some places; e.g. https://github.com/angular/angular/blob/master/modules/angular2/src/platform/server/parse5_adapter.ts#L1

But `parse5` doesn't seem to provide `parse5/index` module. 
https://github.com/inikulin/parse5

I think it should be replaced from `var parse5 = require('parse5/index');` to `var parse5 = require('parse5');`.

BTW, why does `angular2/src/platform/server'` pass tests?

**Comment by laco0416** [comment]
cc. @IgorMinar

**Comment by gdi2290** [comment]
@laco0416 are you using the old version of parse5 `1.3.2`?

**Comment by laco0416** [comment]
@gdi2290 I'm  using the version 2.1.5.

**Comment by gdi2290** [comment]
There was a breaking change they follow semver (Semantic Versioning). So you're looking for issue https://github.com/angular/angular/issues/6237 downgrade the parse5 version and you should be good

**Comment by laco0416** [comment]
@gdi2290 Thank you very much! :smile: 
I'll close this issue and watch #6237 .
