### ISSUE TITLE
[(ngModel)] get Error on div's contenteditable in angular2

### ISSUE THREAD

**Issue by kitkimwong** [angular/angular#7082]
I am trying to use ngModel to two way bind div's contenteditable input content as follow:
`<div id="replyiput"   [(ngModel)]="replyContent" class="btn-input" contenteditable="true" data-text="type..." style="outline: none;"    ></div> `
but it is not work and occur an error
`EXCEPTION: No value accessor for '' in [ddd in PostContent@64:141]
app.bundle.js:33898 ORIGINAL EXCEPTION: No value accessor for `

**Comment by neoeahit** [comment]
+1

**Comment by zoechi** [comment]
See http://stackoverflow.com/questions/35378087/how-to-use-ngmodel-on-divs-contenteditable-in-angular2 for a workaround

**Comment by Nikolay-Uvarov** [comment]
@zoechi Is it maybe the textarea instead input? If I press enter, it does not move to a new line. Thank's!
