### ISSUE TITLE
Template doesn't refresh

### ISSUE THREAD

**Issue by HaehnleinMar** [angular/angular#7083]
I have a template which should display some values, which works just fine when the page is loaded.
But when the value get's changed the template doesn't refresh.

`<input type="checkbox" [checked]="seatmap.debug" (click)="seatmap.toggleDebug()" /><br />
{{ seatmap.debug }}`

The function `toggleDebug()` toggles the bool-value and prints the value to the console, so it really get's changed, but the printed value is just the initialized one.

**Comment by zoechi** [comment]
Can't reproduce https://plnkr.co/edit/LwYuEVcQ41S3wanWJ8fA?p=preview

GitHub issues are for bug reports and feature requests. 
      For support questions please use other channels like [StackOverflow](http://stackoverflow.com/questions/tagged/angular2), [Gitter](https://gitter.im/angular/angular), [Google groups](https://groups.google.com/forum/#!forum/angular), ...

**Comment by HaehnleinMar** [comment]
Okay, thank you! Thought it would be an Angular-Side problem because it there's the same problem i nde example-apps from `ng-book 2`

**Comment by HaehnleinMar** [comment]
Found out it's a problem with ngUpgrade - will post a code-example to fix it later.

**Comment by HaehnleinMar** [comment]
Okay... Worked around it with
`angular.element('body').on('click', function() {
    $rootScope.$apply();
})`
but it tourned out I just forgot to include `angular2-polyfills.min.js`:
`<script src="webjars/angular2/2.0.0-beta.6/bundles/angular2-polyfills.min.js"></script>`
