### ISSUE TITLE
ngIf directive not respecting expression value in element using transclusion

### ISSUE THREAD

**Issue by hitmanmcc** [angular/angular#7085]
Hello everyone,

I ran into a problem today for which I've created the following example plunkr:
https://plnkr.co/edit/8yfJvF8EFIknhaYD8BC8

What happens here is that, when I'm using `*ngIf="somecondition"` inside the selector tag of a nested component that is projecting dom (transclusion), the condition in the `*ngIf` clause is not respected. The affected element is not rendered whether or not the result of evaluating the condition is `true` or `false`.

Regards,
André

**Comment by todoubaba** [comment]
See https://github.com/angular/angular/issues/5363#issuecomment-158998243

**Comment by hitmanmcc** [comment]
@todoubaba Thanks for the pointer. :+1:

**Comment by zoechi** [comment]
dup of #3397
