### ISSUE TITLE
Beta 6 issues

### ISSUE THREAD

**Issue by jlaustill** [angular/angular#7087]
I'm trying to run the most basic basic displaying data example, and I can't get Beta 6 to even run.  I have the following directly from the docs

`function DisplayComponent() {
    this.myName = "Joshua";
}

DisplayComponent.annotations = [
    new angular.ComponentAnnotation({
        selector: "display"
    }),
    new angular.ViewAnnotation({
        template:
            '<p>My name: {{myName }}</p>'
    })
];

document.addEventListener('DOMContentLoaded', function() {
    angular.bootstrap(DisplayComponent);
});`

`<!DOCTYPE html>
<html>
  <head>    
    <script src="https://code.angularjs.org/2.0.0-beta.6/angular2-all.umd.dev.js"></script>
    <script src="main.js"></script>
  </head>
  <body>
    <display></display>
  </body>
</html>`

If I run this with the latest alpha version is runs fine, but with Beta 6 I am getting the following two errors.

> Uncaught TypeError: Cannot read property 'Observable' of undefinedwebpackUniversalModuleDefinition @ universalModuleDefinition:9(anonymous function) @ universalModuleDefinition:10
main.js:9 Uncaught ReferenceError: angular is not defined(anonymous function) @ main.js:9

> Uncaught ReferenceError: angular is not defined(anonymous function) @ main.js:9

Is this an issue with the build, or something I am doing wrong?  I have tried just about every file in the build directory, angular2.js, angular2.dev.js, added the poly fills(I'm using the newest chrome), and nothing, same error all over the place.  I searched and couldn't find anyone else referencing this, so I'm pretty sure it's just me doing something wrong...

**Comment by jlaustill** [comment]
OK, I found a working example using Beta 6 and boy did it look different :)  So I changed my javascript to 

`(function(app) {
app.DisplayComponent = 
	ng.core.Component({
	selector: "display",
    template: '<p>My name: {{myName }}</p>'
    })
	.Class({
		constructor: function() {
			this.myName = "Joshua";
		}
	})
})(window.app || (window.app = {}));

(function(app) {
  document.addEventListener('DOMContentLoaded', function() {
    ng.platform.browser.bootstrap(app.DisplayComponent);
  });
})(window.app || (window.app = {}));`

and now it is working.  SO it would appear that the way you define your models and components has fundamentally changed from alpha to beta 6.  But the docs aren't updated to reflect that change maybe?  If this is the case, can anyone point me to the release notes that detail these changes?  I'm an experienced developer, but pretty new to angular and just trying to get my feet wet with angular 2, so feel free to point out any stupidity on my part :)

**Comment by brandonroberts** [comment]
You can check the https://github.com/angular/angular/blob/master/CHANGELOG.md for breaking changes. Also you can come the gitter chatroom to ask questions as github is for filing bugs and pull requests: http://gitter.im/angular/angular

**Comment by jlaustill** [comment]
Awesome, that's exactly what I was looking for, thanks!

**Comment by brandonroberts** [comment]
Close this issue if this is resolved. :+1:
