### ISSUE TITLE
Is Angular 2 faster ?

### ISSUE THREAD

**Issue by davidtran** [angular/angular#7088]
Hi guys,

Today I made a performance comparison test between Angular 2 and Angular 1. So I implemented an app in both Angular 2 and Angular 1 to see which framework faster. But the result made me surprise, I expect that Angular 2 would be faster but I found out that the winner is Angular 1 instead. 

You can see my app at here:

Angular 1: http://davidtran.github.io/ng2performance/src/ng1/index.html

Angular 2: http://davidtran.github.io/ng2performance/src/ng2/index.html

You can see side by side comparison in this gif file:

![gif file](http://i.imgur.com/Zrhu8YQ.gif)

**Comment by ericmartinezr** [comment]
Impossible to say based in two gifs. You should provide both examples so people with knowledge in both fworks can take a look at it.

**Comment by davidtran** [comment]
I have already provided links to repos.

**Comment by ericmartinezr** [comment]
So I must be missing something because I can't see the code for any of the examples. How do we access to them?

**Comment by davidtran** [comment]
Let's me push the code to another repo so you can see it.

**Comment by Geertje123** [comment]
The source is in the html files he linked. Just check it with chrome dev tools for example.

![image](https://cloud.githubusercontent.com/assets/821358/13054539/acafd2ce-d40a-11e5-9c6c-9c48364d6430.png)

**Comment by davidtran** [comment]
Yes, you can see the code in html file with Chrome dev.

**Comment by willhartman** [comment]
I haven't tested it but I have a suspicion that if you remove the "track by" clause from the Angular 1 ng-repeat the performance of that example will drop.

There is currently no equivalent of "track by" for ngFor as far as I am aware.

**Comment by todoubaba** [comment]
Yes, trackBy in ng2 faster than ng1.

**Comment by Archcry** [comment]
I can confirm that Todoubaba is right by comparing his Plunker with the Angular1 example from the first post.
Angular2 seems to be even faster then Angular1 with this example.

**Comment by ericmartinezr** [comment]
You're a genius @todoubaba :clap:

**Comment by oguimbal** [comment]
Yea, but even with trackBy, ngFor is still painfully slow with IE.

See updated https://plnkr.co/edit/mFzd0Ema6hCHLQRZ6i1m  (just added es6-shim & a fix related to #6501)

On a projet of mine, here is a perf analysis:
That's for a simple ngFor, with ~100 lines and trackBy. 
Hangs for 20secs before initial paint.

![image](https://cloud.githubusercontent.com/assets/8973947/13074936/aa46df7e-d49f-11e5-9427-d5fe815557df.png)

![image](https://cloud.githubusercontent.com/assets/8973947/13074955/c563dbea-d49f-11e5-9cce-f91b15cc3b0f.png)

**Comment by NightkingCH** [comment]
I face the same experiences. I have a view where a table is rendered with approximately 150 rows and 33 columns. In Chrome 48 everything works smooth and fast, Edge, IE11, IE10 crashes after loading my data. Even the trackBy functionality didn't speed up the things.

Basically I have users (rows) which have several roles (columns) which are read from the database (non static data) and stored in a simple array. So I have to loop over my user data and then over their role to display if they have the specific role or not.

Markup-Example:

```
	<table class="table table-bordered table-user">
                <tr>
                    <th colspan="3" text="user"></th>
                    <th text="widgets" [attr.colspan]="widgetCount"></th>
                    <th text="roles" [attr.colspan]="roleCount"></th>
                </tr>
                <tr>
                    <th text="prename"></th>
                    <th text="surname"></th>
                    <th text="login"></th>
                    <td *ngFor="#headline of headlines; trackBy: trackByHeadline">
                        {{ headline.name }}
                    </td>
                </tr>
                <tr *ngFor="#user of userMatrix; trackBy: trackByUserMatrix">
                    <td><a [routerLink]="['/User/Detail', {id:user.userId}]">{{ user.userId }}</a></td>
                    <td>-</td>
                    <td>{{ user.login }}</td>
                    <td *ngFor="#headline of headlines; trackBy: trackByHeadline">
                        <custom-checkbox (change)="onChange($event, headline, user)" [active]="user[headline.code.toLowerCase()] > 0"></custom-checkbox>
                    </td>
                </tr>
            </table>
```

Any suggestions to speed that up?

**Comment by oguimbal** [comment]
For the record: IE doesnt like debug mode...

Calling enableProdMode();  improves performances dramatically

[with enableProdMode()](https://plnkr.co/edit/Srd4vGW9tgiyRMCMZP05?p=preview) : less than 500ms

[without enableProdMode()](https://plnkr.co/edit/XuGTGI8rwRrqUwqX6X9J?p=preview) : more than 10s !

Only with IE. I dont see much difference using other browsers.

**Comment by wesleycho** [comment]
This probably can be closed, it's a generic catch-all issue that isn't terribly useful as is (especially since some perf suggestions have been given, and #8112 is a more granular issue).
