### ISSUE TITLE
Documentation does not change between Typescript and ES5

### ISSUE THREAD

**Issue by developernaren** [angular/angular#7090]
https://angular.io/docs/js/latest/api/http/Http-class.html
Even if this page shows es5 as selected option for the type of language, the displayed documentation is on typescript. I am starting on angular2, this has got me stuck.

**Comment by jlaustill** [comment]
I'm running into this as well, and I'm also just starting on Angular2.  Trying to wade through the documentation is proving challenging mainly because it seems to have changed so much and I'm not always sure I'm looking at something that still applies.

**Comment by brandonroberts** [comment]
The ES5 documentation isn't finished yet for Angular 2: Here is an example plunker in ES5: 

http://plnkr.co/edit/YfwUEK0WEmundrZxdE3N?p=preview
