### ISSUE TITLE
CanActivate change Component

### ISSUE THREAD

**Issue by damiandennis** [angular/angular#7091]
Is it currently possible to switch component in the CanActivate annotation? I can resolve false but this does nothing except halt execution. I don't wish to change route as I want to return a 403 forbidden page. I know this can be done at the loader level in the router however I cant do a route.navigate there for the 401 reponse which is a redirect to the login. I would really like to do all checks in one location. Something like a onReject callback.

**Comment by pcroc** [comment]
Possible dup of #2965
