### ISSUE TITLE
Angular2 - Select: Two-way binding doesn't work on firefox

### ISSUE THREAD

**Issue by nereujunior** [angular/angular#7092]
When I change the select option, the two way binding do not work in Firefox 44.0.2
Sample: https://angular.io/resources/live-examples/forms/ts/plnkr.html

It's working fine on Chrome.

**Comment by ericmartinezr** [comment]
Dup of https://github.com/angular/angular/issues/6573

**Comment by grunzmeniroj** [comment]
It is not fixed , Change Event on select is still not firing on FireFox ... I am using angural2.beta9 and Firefox 44 on ubuntu

**Comment by Artod** [comment]
Any news? angural2.beta11 the same

**Comment by RichiWIP** [comment]
It is still exactly like @nereujunior describes. This issue should be reopened.

**Comment by digitalfiz** [comment]
This have anything to do with https://bugzilla.mozilla.org/show_bug.cgi?id=126379 ?

**Comment by theodorejb** [comment]
It looks like this is a duplicate of #6573.

**Comment by centigrade-thomas-becker** [comment]
The sample page https://angular.io/resources/live-examples/forms/ts/plnkr.html does not even load for me with Firefox 43.0.1. I get the following error: 

> Error: (SystemJS) in strict mode code, functions may be declared only at top level or immediately within another function

**Comment by DzmitryShylovich** [comment]
@centigrade-thomas-becker update firefox version

**Comment by centigrade-thomas-becker** [comment]
Now it works with Firefox 47.0.2
