### ISSUE TITLE
Specifying units on width style binding required

### ISSUE THREAD

**Issue by harangue** [angular/angular#7093]
The [cheatsheet](https://angular.io/docs/ts/latest/guide/cheatsheet.html) claims that `<div [style.width.px]="mySize">`
> Binds style property width to the result of expression mySize in pixels. Units are optional.

But [my Plunker](https://plnkr.co/edit/8QyQjyRX3dhtsPK72dac?p=preview) doesn't work unless `[style.width]` is specified with `px`.

EDIT: Someone pointed out that a string with `px` specified will work. While that is true, I find it unintuitive (and the documentation still misleading). There's nothing to indicate that `mySize` is a string with units specified. Also following the example of other frameworks a unitless number usually defaults to px, though I'd understand if you didn't want to replicate that functionality.

**Comment by zoechi** [comment]
I don't see the problem. In CSS dimensions, units are required (except for `0`)
https://developer.mozilla.org/en-US/docs/Web/CSS/length.
Either you define it in the attribute name or in the value.

**Comment by harangue** [comment]
The only reason I bring it up is that in the Gitter chat I've seen at least two other people with the same problem meaning it'll likely be a common point of pain. You're right though, a warning would suffice - it's just currently an invisible failure.
