### ISSUE TITLE
On imported files used as providers, beforeEachProviders breaks, whereas beforeEach and injector is fine

### ISSUE THREAD

**Issue by nolazybits** [angular/angular#7094]
I have this really weird behavior (bug?) with beforeEachProviders, which I can't seem to fix.
I have created 2 plunkers.

The [FIRST ONE](http://plnkr.co/edit/6jUwAcN0JQH5xNvMfJT4?p=preview) as you can see works fine. The tests pass and I can log my instance of the interceptorBackend (which I ultimately would like to test).
Please note that in this plunker the class is define in the SAME FILE.

Now in [SECOND ONE](http://plnkr.co/edit/vJKIffKeuC23c0o2nGRJ?p=preview). It's an exact copy of the first one except the InterceptorBackend class is in it's own file.
If you run it like this it will work, as the misbehaving code as been commented out. Please uncomment the second describe and you will receive this error show at the end of this issue.

So to resume:
- InterceptorBackend defined in the same file:
  - beforeEach and injector works
  - beforeEachProviders works
- **Interceptorbackend defined in an external file**
  - beforeEach and injector works
  - **beforeEachProviders FAILS**

The error:

`InterceptorBackend using beforeEach and injector should intercept request and call request interceptors
TypeError: Cannot read property 'toString' of undefined
TypeError: Cannot read property 'toString' of undefined at new InvalidProviderError (https://code.angularjs.org/2.0.0-beta.3/angular2.dev.js:1727:111) at https://code.angularjs.org/2.0.0-beta.3/angular2.dev.js:9767:15 at Array.forEach (native) at _normalizeProviders (https://code.angularjs.org/2.0.0-beta.3/angular2.dev.js:9757:15) at Object.resolveProviders (https://code.angularjs.org/2.0.0-beta.3/angular2.dev.js:9723:22) at Function.Injector.resolve (https://code.angularjs.org/2.0.0-beta.3/angular2.dev.js:11290:25) at Function.Injector.resolveAndCreate (https://code.angularjs.org/2.0.0-beta.3/angular2.dev.js:11293:40) at Object.<anonymous> (http://run.plnkr.co/c8BxhKyi5sjrQRiO/src/main.ts!transpiled:37:52) at attemptSync (http://cdnjs.cloudflare.com/ajax/libs/jasmine/2.2.1/jasmine.js:1741:24) at QueueRunner.run (http://cdnjs.cloudflare.com/ajax/libs/jasmine/2.2.1/jasmine.js:1729:9)
TypeError: Cannot read property 'createConnection' of undefined
TypeError: Cannot read property 'createConnection' of undefined at Object.<anonymous> (http://run.plnkr.co/c8BxhKyi5sjrQRiO/src/main.ts!transpiled:53:32) at attemptSync (http://cdnjs.cloudflare.com/ajax/libs/jasmine/2.2.1/jasmine.js:1741:24) at QueueRunner.run (http://cdnjs.cloudflare.com/ajax/libs/jasmine/2.2.1/jasmine.js:1729:9) at QueueRunner.execute (http://cdnjs.cloudflare.com/ajax/libs/jasmine/2.2.1/jasmine.js:1714:10) at Spec.Env.queueRunnerFactory (http://cdnjs.cloudflare.com/ajax/libs/jasmine/2.2.1/jasmine.js:608:35) at Spec.execute (http://cdnjs.cloudflare.com/ajax/libs/jasmine/2.2.1/jasmine.js:346:10) at Object.fn (http://cdnjs.cloudflare.com/ajax/libs/jasmine/2.2.1/jasmine.js:2059:43) at attemptAsync (http://cdnjs.cloudflare.com/ajax/libs/jasmine/2.2.1/jasmine.js:1771:24) at QueueRunner.run (http://cdnjs.cloudflare.com/ajax/libs/jasmine/2.2.1/jasmine.js:1726:9) at QueueRunner.execute (http://cdnjs.cloudflare.com/ajax/libs/jasmine/2.2.1/jasmine.js:1714:10)
InterceptorBackend using beforeEachProviders should intercept request and call request interceptors
Failed: Cannot read property 'toString' of undefined
TypeError: Cannot read property 'toString' of undefined at new InvalidProviderError (https://code.angularjs.org/2.0.0-beta.3/angular2.dev.js:1727:111) at https://code.angularjs.org/2.0.0-beta.3/angular2.dev.js:9767:15 at Array.forEach (native) at _normalizeProviders (https://code.angularjs.org/2.0.0-beta.3/angular2.dev.js:9757:15) at Object.resolveProviders (https://code.angularjs.org/2.0.0-beta.3/angular2.dev.js:9723:22) at Function.Injector.resolve (https://code.angularjs.org/2.0.0-beta.3/angular2.dev.js:11290:25) at Injector.resolveAndCreateChild (https://code.angularjs.org/2.0.0-beta.3/angular2.dev.js:11336:40) at TestInjector.createInjector (https://code.angularjs.org/2.0.0-beta.3/testing.dev.js:1848:37) at TestInjector.execute (https://code.angularjs.org/2.0.0-beta.3/testing.dev.js:1854:14) at Object.<anonymous> (https://code.angularjs.org/2.0.0-beta.3/testing.dev.js:1970:44)`

Any help would be greatly appreciated.
Thanks

**Comment by brandonroberts** [comment]
@nolazybits you've got a mix of single quotes and double quotes in your imports. You should keep those consistent one way or the other. If you change line 2 `import {inject} from 'angular2/testing';` to `import {inject} from "angular2/testing";` and uncomment your test it runs successfully.

**Comment by nolazybits** [comment]
@brandonroberts you are the man... Thank you!!!!
I didn't think about the imports mixing single quote and double quote. Is it still considered as a bug though as mixing single and double quote, and using normal beforeEach and injector does work...

Thanks again!!!

**Comment by efortes** [comment]
@nolazybits that worked for me. Why is quotation a problem. I had this problem for 2 days now and its fixed with changing the quotes. This s really wierd. Thanks
