### ISSUE TITLE
New data-driven forms, how flexible?

### ISSUE THREAD

**Issue by Anthropic** [angular/angular#7096]
I use json-schema.org based **data** definition and generate forms from a **form** definition that uses the keys defined in the data definition. It is a very similar approach to the ng2 data-driven forms, but follows the **json-schema.org** standard and has a feature rich capability for validations and default behaviours like conditional display. I wonder how much flexibility will there be to try to emulate some of the features.

Can I reload either the form description, data definition or the actual data all dynamically as required and in any order?

I love the logical structure found in json-schema.org and I just want to know how best to continue using it in conjunction with ng2's form tools. Really just looking for tips or experience anyone has on how best to work with Angular 2 forms to validate using a tool like **tv4** or **is-my-json-valid** etc..

Thank you for your time and any suggestions/suggested reading.

**Comment by pkozlowski-opensource** [comment]
You can learn more about the current status of the model-driven forms support from this excellent ng-conf talk https://www.youtube.com/watch?v=ihYc9y7dQA0 and decide for yourself if it suits your needs.
