### ISSUE TITLE
beta.6 quick start npm doesn't work behind proxy

### ISSUE THREAD

**Issue by JonathanYates** [angular/angular#7097]
The latest beta-6 quick start npm doesn't work behind a corporate proxy, even with the correct npm proxy setting set. Issue is regarding the new typings dependency Error output is:

typings ERR! message Unable to read typings for "es6-shim". You should check the path is correct
typings ERR! caused by Unable to connect to "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/6697d6f7dadbf5773cb40ecda35a76027e0783b2/es6-shim
/es6-shim.d.ts"
typings ERR! caused by getaddrinfo ENOTFOUND raw.githubusercontent.com
...

Work around is to place a  .typingsrc file in the root with these settings:
 proxy=http://proxy.example.com:8080
 rejectUnauthorized=false

More info on this here
https://github.com/typings/typings/issues/106

**Comment by d0nkeyBOB** [comment]
Thanks for this work around. i'm seeing the same behind a corp proxy.

**Comment by pkozlowski-opensource** [comment]
Thnx for the info @JonathanYates - hopefully people searching for similar problems will find this issue. Having said this it is more StackOverflow type of question / answer.
