### ISSUE TITLE
Typed TSX like templates in angular 2

### ISSUE THREAD

**Issue by PavelPZ** [angular/angular#7100]
TSX (= typed JSX) for React templates is a big advantage compared to Angular templates. It has many design time advantages.

- Angular 2 use strictly typed approach (Typescript), it's a shame to leave templates untyped.
- I can see a lot of official Angular examples like... 
```
@Component({
  template: `<div>    
      <h4>{{order + '. ' + title}}</h4>
    </div>`
```
... why not to have those HTML fragments strictly typed... 
```
@Component({
  template: (<div>    
      <h4>{{order + '. ' + title}}</h4>
    </div>)
``` 
... including all Atom or Visual Studio Code IDE benefits: find all symbol reference, rename symbol, syntax highlighting, auto indent, etc.
- when we have TypeScript fragments in HTML (like {{order + '. ' + title}} above), let's have it under compiler control.
- If somebody got used to write React strictly typed TSX templates in Atom or Visual Studio, then coding HTML fragments to untyped string is backward step.
- why not to use Typescript 1.8 (in beta now) custom JSX factories for compile time generation?

**Comment by MikeRyan52** [comment]
I think you will be interested in Microsoft/TypeScript#6508

In short, typed templates are on the horizon. Angular 2 doesn't need to support JSX to achieve this.

**Comment by PavelPZ** [comment]
Thanks @MikeRyan52 for your info, this is exactly what I mean.

**Comment by remojansen** [comment]
:+1:

**Comment by zoechi** [comment]
dup of #5131 ?

**Comment by pkozlowski-opensource** [comment]
The same discussion is already happening in https://github.com/angular/angular/issues/5131, let's centralize it in there.
