### ISSUE TITLE
<select>: <option selected> is not actually selected when using ngControl

### ISSUE THREAD

**Issue by DavideViolante** [angular/angular#7101]
Version: beta.6
Browser: Chrome 48
I reproduced this bug into this plunk:
http://plnkr.co/edit/HFvG6xGVnwYnp0Bft87l?p=preview
http://embed.plnkr.co/HFvG6xGVnwYnp0Bft87l/

Code:
```
      			<form (ngSubmit)="onSubmit(fileForm.form.value)" #fileForm="ngForm">
					<select ngControl="cat" #cat="ngForm">
							<option selected disabled>Selected option</option>
							<option value="option1">option1</option>
							<option value="option2">option2</option>
							<option value="option3">option3</option>
					</select>
			</form>
```
The "Selected option" should be selected by default, but it's not.
If you remove the outer form tag or if you remove ngControl="cat" #cat="ngForm" the "Selected option" is correctly selected by default.

Not sure if it's a real bug or I'm making some mistake.

UPDATE: plunker for Angular v2.0.2: http://plnkr.co/edit/FDVOX79ckgTUxIwAgfcX?p=preview

**Comment by mcpDESIGNS** [comment]
You need to actually have a value in Angulars model of `cat`. This works just how it does in Angular1. If nothing is present, nothing is selected.

**Comment by DavideViolante** [comment]
Sorry, can you please show me a working example?

**Comment by woppa684** [comment]
This works:

```
<form #fileForm="ngForm">
    <select ngControl="cat" #cat="ngForm" ngModel="option0">
        <option value="option0" disabled>Selected option</option>
        <option value="option1">option1</option>
        <option value="option2">option2</option>
        <option value="option3">option3</option>
    </select>
</form> 
```

**Comment by DavideViolante** [comment]
Thank you, but the FileForm.form.valid property is true when that option is selected.
The same plunk updated: http://plnkr.co/edit/HFvG6xGVnwYnp0Bft87l?p=preview
To make things clear, what I'd like to achieve is this: a select-option form, with a default value you cannot select (label), and with the submit button disabled if no option has been selected.

**Comment by sod** [comment]
`<option disabled [ngValue]="null">Unselected</option>` works for me as default option.

**Comment by vicb** [comment]
Is this still an issue with ng 2.0.1 ?

**Comment by DavideViolante** [comment]
Hmm, I think is still not working. Here a plunker:
http://plnkr.co/edit/FDVOX79ckgTUxIwAgfcX?p=preview
The option "Select a category" should be immediately readable (so selected), but the select tag is blank instead. The form is correctly disabled since no option has been selected.

**Comment by daddyschmack** [comment]
I'm having a very similar issue when binding the select control to an option (scalar) as opposed to an option property.
http://plnkr.co/edit/Drli3JaQ7WfbkkGmsK0r?p=preview

**Comment by kara** [comment]
To clarify, the source of truth for the select's value is the form control model. Setting the value of the form control model will initialize the select element with that value.  We don't support the selected attribute as well because that would create two conflicting sources of truth for the select's value. 

If you'd like the select to be empty, @sod's solution should work. If you want the initial "select a category" value to show (but still be disabled), you'll want to initialize the form control model to null as well. Example [here](http://plnkr.co/edit/tQH828InDm8pZn7zBtGd?p=preview).

**Comment by DavideViolante** [comment]
@kara In your example the Submit button is still enabled, should be disabled if no option is selected.

**Comment by daddyschmack** [comment]
@kara, in your example of default text, your control does not have two way
binding. No [(ngModel)].

If you add the following to the select control, the default selection
disappears:
[(ngModel)]="cat"

[image: Inline image 1]
