### ISSUE TITLE
angular2@2.0.0-beta.6 has unmet peer dependencies, even when in package.json

### ISSUE THREAD

**Issue by rbaarsma** [angular/angular#7105]
I have the following package.json
```json
{
  "dependencies": {
    "angular2": "^2.0.0-beta.6",
    "bootstrap": "^4.0.0-alpha.1",
    "es6-shim": "^0.33.13",
    "reflect-metadata": "^0.1.3",
    "rxjs": "^5.0.0-beta.2",
    "systemjs": "^0.19.21",
    "zone.js": "^0.5.11"
  },
}
```
When I `npm install` this, I get the following UNMET PEER DEPENDENCY errors:
├── UNMET PEER DEPENDENCY reflect-metadata@0.1.3
├── UNMET PEER DEPENDENCY rxjs@5.0.0-beta.2

This causes several errors both on the typescript compile and after starting the lite server.

If you need a working example you can clone and npm install this repository:
https://bitbucket.org/rbaarsma/timesheet-front

**Comment by alexeagle** [comment]
The errors from npm install should not cause any later problems like typechecker or runtime errors.

However you have rxjs beta.2 which doesn't work yet. Try beta.0

**Comment by rbaarsma** [comment]
I was pretty sure I tried that, but must've tried it with ` "rxjs": "^5.0.0-beta.0",` which still installs 5.0.0.-beta.2. 

But you're right - it does work with rxjs@5.0.0-beta.0

Thanks for your time!
