### ISSUE TITLE
Not showing data in a route component.

### ISSUE THREAD

**Issue by MohhamedRafi** [angular/angular#7107]
So I been trying to get a head start in angular 2. For this reason I was trying to create a starter kit with basic routing. I was planning on using this kit for other projects but I been running into trouble when displaying data. 

I create a component that is used in the route '/'. But when I try displaying data with it I get nothing. 

The code for the component (MainComponent.ts): 
```

import { Component, View } from 'angular2/core';

// Main Route Component
@Component({
	selector: 'Main'
})
@View({
	directives: [],
	templateUrl: './app/main/MainTemplate.html'
})
export class MainComponent {
	name: string;

	constructor() {
		this.name = 'Bob';
	}
}

```

The template html file (MainTemplate.html):
```
<div class="container-fluid">
	<div class="jumbotron">
		<h1> Mohhamed Rafi</h1>
	</div>

	{{name}}
</div>
```

At first I thought it was that I was not using Main.name because in the route config I set it the as property to Main but after trying that it was not working. 

The full code is in this repo: https://github.com/MohhamedRafi/Angular2StarterKit

**Comment by brandonroberts** [comment]
You need to `npm install rxjs@5.0.0-beta.0` and you're also missing zone.js which is usually included via script tag from node_modules/angular2/bundles/angular2-polyfills, but you can add it to the top of your bootstrap `import 'zone.js';`

**Comment by MohhamedRafi** [comment]
Thank you that solved everything!
