### ISSUE TITLE
Ability to dynamically add styles (need shimming)

### ISSUE THREAD

**Issue by jardilio** [angular/angular#7108]
edit(vicb)
## This issue is about scoping the dynamically added styles

/edit

**Problem:**

If you are developing a component with inline styles and try to write styles for content that will be generated later, the styles will fail to match due to the way Angular alters the styles using "namespaces" in selectors based on the uniquely generated attribute for all components template elements. 

In the following example, the dynamically generated element "h3" should be blue according to the defined styles, however it fails to match due to how angular altered the style definitions:

http://plnkr.co/edit/qGOE7EAHB4FlmGg6ZC0i?p=preview

A more practical example that illustrates the issue is a Component which wraps a D3 generated chart. The component tries to set styles for the generated SVG content, however those styles fail to match since Angular compiler didn't know about the elements at compile time and were added later.

**Possible Solution:**

Rather than adding the unique attribute all ALL template elements and _suffixing_ all style selectors, would be better to only apply the unique attribute to the root component element, then namespace selectors by adding the parent prefix selector.

```
/*current solution*/
h2[_ngcontent-jlf-1] {
color: blue;
}
.h3[_ngcontent-jlf-1], h3[_ngcontent-jlf-1] {
color: red
}
```

```
/*proposed solution*/
[_ngcontent-jlf-1] h2 {
color: blue;
}
[_ngcontent-jlf-1] .h3, [_ngcontent-jlf-1] h3 {
color: red
}
```

I believe that this change to the way the style blocks are altered would be less destructive and possibly resolve https://github.com/angular/angular/issues/6249.

**Comment by jardilio** [comment]
After digging thru the source, perhaps the problem is that we actually need to make sure to prefix our style blocks with the host-component selector, then the output is as expected:

http://plnkr.co/edit/dTYcFvkIEMnZG7aqqcaH?p=preview

With that, the generated CSS matches what I expected in the proposed solution.

**Comment by gbataille** [comment]
I wonder if you are not using the "namespacing" or "context" if you use your second solution.

I originally had the same issue with Ember a year ago when I wanted to try it, and was applying my jQuery and D3 knowledge and patterns.

But I think one of the core concept of Angular2 (and one of its promises) is NOT to have to manipulate the DOM (_ok I hope I'm not mistaken there_). And I think that Ember is the same and that was an error to try and use it like that. I think what you ought to do is write your "full" template, with the conditional h3 but have some control (e.g. a __hidden__ class) that tells whether it should be displayed (and/or whether it's ready with content yet).

And then possibly when you find that you have too much logic in a component it's the time to consider splitting it into subcomponents

How does that sound for you?

**Comment by zoechi** [comment]
@gbataille There are components that are just dynamic, depending on user provided data for example, where `*ngIf`s and `*ngSwitch` would get out of hand fast. This shouldn't be part of the view.

Polymer has an `updateStyles()` API method to notify to re-apply style shims.
This would be enough IMHO.

**Comment by jardilio** [comment]
@gbataille while I would typically agree with you about Dom manipulation, I made the example as simple as possible to illustrate the point, but indicated the real world example is more like having your component wrap another framework the does manipulation, such as D3 to render a chart. 

I think perhaps this is a non issue based on my second comment if the :host-context selector is used in the style block.

**Comment by twilliamsgsnetx** [comment]
I just ran into this issue creating d3js content. My paths, while classed, are not receiving styling from my component stylesheet. If I use :host followed by my classnames, they apply correctly as @jardilio  said.

It would be nice to not have to prefix every selector with :host

**Comment by tomwanzek** [comment]
@twilliamsgsnetx @jardilio I came across the same issue (in a D3 use case as well) 

I agree that the styling should work without prefixing the style statements in the component css. However, let me add the following observation:

Having the following in the component stylesheet unexpectedly **fails** to apply as raised.
```
.d3chart-background {
  fill: rgba(250, 250, 250, 0.8);
  border-radius: 3px;
}
```
Forcing it down with a _deep_ selector works:
```
>>> .d3chart-background {
  fill: rgba(250, 250, 250, 0.8);
  border-radius: 3px;
}
```
As mentioned above the host selector works as well, although this seems counterintuitive.
```
:host .d3chart-background {
  fill: rgba(250, 250, 250, 0.8);
  border-radius: 3px;
}
```

**Comment by zoechi** [comment]
@tomwanzek `>>> .d3chart-background`, `:host >>> .d3chart-background` and `:host .d3chart-background` are equivalent AFAIK.

**Comment by twilliamsgsnetx** [comment]
I wasn't even aware of the `>>>` syntax. I've been using `:host /deep/ .d3chart-background` 

I'm assuming this is also equivalent in the larger scheme of things?

**Comment by vicb** [comment]
`>>>` is the same as `/deep/` (different version of the CSS spec, the former is known to cause troubles with SASS)

**Comment by tomwanzek** [comment]
@vicb Thx. I was not aware of the SASS issue with the `>>>` shadow piercing descendant combinator. I referenced it, because one of the Shadow DOM W3C documents stated it has replaced the `/deep/` combinator. For all intents and purposes with ng2 they are still interchangeable, I suppose.

But to add to the above, **I just upgraded an RC.5 project to RC.7**, and now the following occurs (_Regression?_):

```css
:host .d3chart-background {
/* some styling */
}
````
The **style is no longer applied** to a `rect` dynamically appended with the class using an attribute selector component and D3. This behavior is **different from RC5**. (I cannot comment on RC6)

```css
:host >>> .d3chart-background {
/* some styling */
}
````
Using the `:host`selector in combination with `>>>` or `/deep/` applies the style, but at the cost of it piercing all the way down even through "child shadow trees".

```css
>>> .d3chart-background {
/* some styling */
}
````
Without `:host` selector, but using `>>>` or `/deep/`, the style is applied, BUT the style rule becomes globalized. I.e. while it resides in a component-style sheet, the style would _also_ apply at a parent DOM element.

I guess, my main question becomes the apparently changed behavior with a `:host`-selector only style rule. The other two are more clarifications, but not unexpected.

Were there any changes in RC7 (or RC6) that would explain?

**Comment by vicb** [comment]
> For all intents and purposes with ng2 they are still interchangeable, I suppose.

yep.

> The style is no longer applied to a rect dynamically appended

That's because selector after host are now properly scoped while your dynamically added nodes are not scoped - and no there is no way to do it currently but it's on the todo list

> Using the :hostselector in combination with >>> or /deep/ applies the style, but at the cost of it piercing all the way down even through "child shadow trees".

You're right. The workaround is to apply a class/attribute to your dynamically added component and scope your rule manually. 

Changes is https://github.com/angular/angular/pull/10997/commits

**Comment by splincode** [comment]
@vicb  This issue is relevant?

**Comment by vishranti5** [comment]
Hi 
I have created one micro application using angular elements. In the components css file i have imported external style sheet using @import. when i consume this micro application in base app then style sheet is downloaded but classes doesnt get applied. do anyone knows about this?
Also, If i dynamically add style sheet creating link element using html in components Ts file this time Styles got applied after consuming micro app in base application
