### ISSUE TITLE
Component router 1.5 - conflicts with existing routes

### ISSUE THREAD

**Issue by KhoaSydney** [angular/angular#7112]
Hi,

I have two routes configured in the run phase of my app module as follow:

` $router.config([
        { path: '/', name: "Home", component: "home", useAsDefault: true },
        { path: "/home/home/home", redirectTo: ["/Home"] }
    ]);`

and inside my Home component I also have a route configure as follow:

` export default class HomeController {
     
     static $inject = ["$router"];

     constructor(private $router) {
        
     }

     $onInit() {
       
         this.$router.config([
             { path: "/settings/home/home", name: "Settings", component: NavigationPath.Settings.controllerId + ".component" }]);
     }
 }`

When I run my application it gives me the following error:
**Configuration "/settings/home/home" conflicts with existing route "/setting/home/home" (158770632)**
this is because the Home component has been instantiate or called twice which trigger the the router to add routes config twices. If I remove the ` { path: "/home/home/home", redirectTo: ["/Home"] }` from the run phase then everything is working fine.  Is there anything wrong with the way I set up the routes?

cheers,
Khoa

**Comment by brandonroberts** [comment]
Is there a reason you aren't setting up all your routes in the run phase?

**Comment by KhoaSydney** [comment]
Hi @brandonroberts ,

the routes are dynamic based on user roles/permissions and also should each component responsible for configuring child routes? I only configure route in run phase to map the Root Router with a single Route, which maps the `/` URL to the whatever component user has permission to run. My idea is that when user navigates to the component, all its child routes will be configured within this component. Correct me if this is the wrong way to do it.

cheers,
Khoa

**Comment by brandonroberts** [comment]
I don't see why this wouldn't work if you have it setup right. You can't setup routes dynamically that way though, since the ng1 router expects your child routes to be defined before navigation. You want to setup  three routes in your run config, with your child routes attached statically to the child component. Child routes can't be independent of their parent.

Run Config
```
$router.config([
    { path: '/', name: "Home", component: "home", useAsDefault: true },
    { path: "/home/home/home", redirectTo: ["/Home"] }
]);
```

Home Component
````
export default class HomeController {

 static $inject = ["$router"];

 static $routeConfig: [
     { path: "/settings/home/home", name: "Settings", component: NavigationPath.Settings.controllerId + ".component" }
  ]

 constructor(private $router) {}
}
```

If this is confusing, you can put together a plunker and we can go from there.

**Comment by vicb** [comment]
obsolete
