### ISSUE TITLE
[Router] Hash links do not work with PathLocationStrategy

### ISSUE THREAD

**Issue by tamalnath** [angular/angular#7114]
I have followed the first example of [Router Sample](https://angular.io/docs/ts/latest/guide/router.html) and tried to add below code in _HeroListComponent_ template:

```html
<a href="#link">Link</a>
<p id="link">Link</p>
```
On click of the hyperlink, entire page is reloaded and the URL in the navigation bar becomes: http://localhost:3000/#link. To my understanding, this might be because of **base href** tag in _index.html_. So I have removed it:
```html
<base href="/">
```
and modified _main.ts_ as:
```typescript
import {AppComponent}     from './app.component';
import {provide}          from 'angular2/core';
import {bootstrap}        from 'angular2/platform/browser';
import {ROUTER_PROVIDERS, APP_BASE_HREF} from 'angular2/router';
bootstrap(AppComponent, [
  ROUTER_PROVIDERS,
  provide(APP_BASE_HREF, {useValue: '/'})
]);
```
In this case, URL temporarily becomes: http://localhost:3000/heroes#link and automatically changes to http://localhost:3000/heroes.

HashLocationStrategy do not support links within same document. Now, it appears like PathLocationStrategy also don't support it. Am I missing something?

**Comment by zoechi** [comment]
dup of #6595?

**Comment by tamalnath** [comment]
Yes!

**Comment by tamalnath** [comment]
I am closing this bug as fixing #6595 will solve my issue.

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166604.
------------------------------------------------------------------------------------------------------------


[[bdb52b4fdabf6195d91fc21c9c79d0f3c1b17b50-673074606]]
