### ISSUE TITLE
[ngComponentRouter] for Angular 1.5.0 cannot be minified using gulp-uglify

### ISSUE THREAD

**Issue by alexgoldstone** [angular/angular#7115]
I am testing with Angular 1.5.0

I concatenate and minify my JS code using `gulp-concat` and `gulp-uglify`.

I installed `ngComponentRouter` using: 

`npm install @angular/router@0.1.0 --save`

I then attempt to use the following JS file:

`./node_modules/@angular/router/angular1/angular_1_router.js`

Using `gulp-concat` on its own is fine and `ngComponentRouter` works without error.

Using `gulp-uglify` causes [this error](http://bit.ly/249f2oe) to be reported by Google Chrome (Version 48.0.2564.109).

No error is reported by `gulp-uglify` itself.

Other than referencing the file, no code is changed to actually use `ngComponentRouter` and eliminating the `gulp-uglify` process is all that is required to prevent the error.

**Comment by brandonroberts** [comment]
There have been issues with minification, so you should try setting `mangle` to `false` for gulp-uglify and see if that works correctly in the meantime.

**Comment by alexgoldstone** [comment]
Thank you.

I have just tested and can confirm that using `gulp-uglify` with `mangle` set to `false` works correctly.

This is specific to `ngComponentRouter ` and setting `mangle` to `true` is fine when not using Angular 1.5.0 without `ngComponentRouter `.

**Comment by vicb** [comment]
obsolete
