### ISSUE TITLE
Extending NG2 components

### ISSUE THREAD

**Issue by tbragaf** [angular/angular#7116]
Hi all!

I need to extend a component. What is the best way to do so?
First of all, let's say I have a Document component which has a lot of HTML to be used across 10 other components.
First thing that comes to mind is to have a Document component that would be used as a ViewChild with its inputs and outputs.

However, I also need to add some common behaviour to the Document component, 3 textboxes with some associated behaviour.
It is true that these 3 textboxes and behaviours/methods are common to every specific Document.

So the obvious choice is to have these 3 textboxes inside the Document component and bind inputs and outputs.
Let's now say I also have a button, which saves the Document, and the Save method is common to every specific Document (a specific Document is for example a Product Document).

Again, the obvious choice is to put this method inside the Document Component.
But what if I want to catch events before and after and, sometimes prevent the save method from the Product Document from occurring?

It seems a lot of work if one is using events for before and after behaviour right?

So, in conclusion, this is my solution:

The Document Component:
```js
@Component({
  selector: 'document',
  outputs: [
    'saveEvent: save'
  ],
  template: `
  	<div>
  		<input type="text" value="Textbox1" />
  		<input type="text" value="Textbox2" />
  		<input type="text" value="Textbox3" />
  		<ng-content></ng-content>
  		<button (click)="save($event)">Save</button>
  	</div>
  `
})
export class Document {
	saveEvent = new EventEmitter();

	save(event) {
	    this.saveEvent.next(event);
	  }
}

// Abstract Document with common behaviour
export class AbstractDocument {
	save(event) {
	    /* Do something like saving */
	}
}
```

And my Product Document Component:
```js
@Component({
  selector: 'product-document',
  template: `
  	<document (save)="save($event)">
  		<input type="text" value="Textbox4" />
  		<input type="text" value="Textbox5" />
  	</document>
  `
})
export class ProductDocument extends AbstractDocument {
	constructor() { super(); }

	// At this point I don't need this save method. Because the prototype chain will do the work for me if it doesn't find the save method.
	save(event) {
	    super.save(event);
	}
}
```

What do you think? I also need to have inputs and outputs for the textboxes to update correctly.

Thank you,
tbragaf

**Comment by zoechi** [comment]
Looks fine so far. 
GitHub issues are for bug reports, feature and pull requests. 
For support questions please use StackOverflow, Gitter, Google Groups, ... .

**Comment by tbragaf** [comment]
@zoechi Sorry I know, since it was a big explanation, I didn't want people to ignore it! :)
Thank you!
