### ISSUE TITLE
Directives that export the same class name cause a conflict in the same view.

### ISSUE THREAD

**Issue by bennadel** [angular/angular#7117]
If I happen to have two directives that export the same class name and try to apply them to the same view, only the last one seems to be picked up. And, it then gets inappropriately applied to the selector of the "ignored" directive. For example, if I have (pseudo-code):

@selector: "p"
export function MyClass() { .... }

@selector: "section"
export function MyClass() { .... }

... and I try to apply them to the same View that has both \<P\> and \<Section\> tags, only the "selector:section" will be applied. And, it will be applied to both P and Section tags. This only happens because they both use "MyClass()" as the constructor name.

This worked fine in Beta 1, but breaks (at least as early) as Beta 3 (I don't have Beta 2 locally). I have documented my findings here complete with a video walk-through:

http://www.bennadel.com/blog/3026-directive-conflict-when-classes-export-the-same-name-in-angular-2-beta-6.htm

This looks like it **may be related** to this issue:

https://github.com/angular/angular/issues/6774

But, I opened a new issue since the symptoms are different (even though the underlying cause _may_ be related).

**Comment by vicb** [comment]
Please add a repro in a plunker

**Comment by vicb** [comment]
Please re-open when you have a minimal repro available
