### ISSUE TITLE
Extending a service disregards parent provider and creates a new instance

### ISSUE THREAD

**Issue by subsite** [angular/angular#7121]
I'm not sure this is a bug, it might just be me trying to do something I'm not supposed to... I'm new to angular2. But anyway, I'm making a site as an angular2 test project, which has two navigational menus. The components for these menus are identical except for the template code. All necessary logic happens in a globally provided service which is used for both menus.

The working version for the two menus looks like this (top menu shown here, somewhat simplified):
```typescript
import {Component} from 'angular2/core';
import {NaviService} from './navi.service';

@Component({
    selector: 'ss-navi-top',
    template: `
        <div *ngFor="#item of navi" (click)="onNavi(0, i)" click)="onNavi(0, i)"> 
            <a href="/#/{{item.page}}/{{item.sub[0].page}}">{{item.name}}</a>
        </div>
    `
})
export class NaviTopComponent {
   private navi: any[];
   private curNaviIdx: number[];

   constructor(private naviService: NaviService) { }

    ngOnInit() {
        this.navi = this.naviService.navi;
        this.curNaviIdx = this.naviService.curNaviIdx;
    }
    onNavi(level: number, idx: number) {
        this.curNaviIdx = this.naviService.onNavi(level, idx);
    }
}
```
With this setup, the component for the other menu is identical except for its name, its selector and template. Repeating the code in both components felt rather redundant, and as all necessary logic happens in the service, I thought I'd be clever, and did this:

```typescript
@Component({
    [...]
})
export class NaviTopComponent extends NaviService  { }
```
It works ok (no errors), but the problem is it creates a new instance ov NaviService, and thus doesn't update values in the site-wide instance of NaviService. (More specifically, NaviService keeps information about the current navigation position, which has to be correct in order for other components to use it.)

The repository for the complete project is here: https://github.com/subsite/slender-site

I use angular version 2.0.0-beta.6.

**Comment by pcroc** [comment]
A component can extend another _component_ but it doesn't make much sense for a component to extend a _service_.

So you could do something like this:

```typescript
@Component(...)
export class NaviTopComponent implements OnInit {
   private navi: any[];
   private curNaviIdx: number[];

   constructor(private naviService: NaviService) { }

    ngOnInit() {
        this.navi = this.naviService.navi;
        this.curNaviIdx = this.naviService.curNaviIdx;
    }
    onNavi(level: number, idx: number) {
        this.curNaviIdx = this.naviService.onNavi(level, idx);
    }
}

//--------------------------------

@Component(...)
export class NaviLeftComponent extends NaviTopComponent {
  constructor(naviService: NaviService) {
    super(naviService);
  }
}
```

**Comment by subsite** [comment]
Thanks prcoc! Yes, I thought this might be the case, it did feel like circumventing the angular system a bit. 

I actually thought of doing like you suggest, but it didn't feel completely satisfying as one on the components would then be dependent on the other. But maybe that's not a bad idea if I name the components in a way that makes the fact that one is the parent and the other a child clear. I think I'll do just that.

**Comment by vicb** [comment]
relates to #11606

**Comment by pkozlowski-opensource** [comment]
It is tracked in  #11606 now.
