### ISSUE TITLE
Router : How to know current navigation ?

### ISSUE THREAD

**Issue by vguede** [angular/angular#7122]
How can I know current navigation ?
Use case : I want to access to as protected component (url = "/protected"). In $canActivate, I perform a redirect to login page. Once logged, I want to return to the first page.
Before redirect to login page, I must know the requested url was "/protected", navigate to login page and then navigate to "/protected".
@petebacondarwin  or @brandonroberts , any idea ?

**Comment by brandonroberts** [comment]
@vguede in the $canActivate you can inject the `$prevInstruction` which has a property of `urlPath` which will tell you what the previous url you came from was.

**Comment by petebacondarwin** [comment]
Thanks @brandonroberts - strictly it is not an injection: the method simply receives two parameters: `$canActivate(next, previous)`

**Comment by vguede** [comment]
Yes @brandonroberts , but when I use a nested route (example : '/layout/protected'), $prevInstruction contains only 'protected'. Or, I want to obtain '/layout/protected'.
Is there any property ou method of $router to obtain thsi ?

**Comment by brandonroberts** [comment]
@petebacondarwin right, thanks.

@vguede I just filed an issue for that a little while ago: https://github.com/angular/angular/issues/7120

**Comment by petebacondarwin** [comment]
Here is a thing. There are some that say that a component should not know where in the hierarchy it is placed, since it could be moved around.
Perhaps what we really need is a "navigateBack()` method on the `$rootRouter`?

**Comment by vguede** [comment]
@petebacondarwin  Ideally, a property with the url path of actual navigation. So this url can be stored to perform a redirect later.

**Comment by brandonroberts** [comment]
@petebacondarwin I agree with that notion about the component in the hierarchy. I think something like a `navigateBack` is needed to go back to the previous route. Could you inject $window and use `window.history.back()` @vguede or do you need to know that was a specific url?

**Comment by vguede** [comment]
@brandonroberts I need to know the url because I want to return to my page after 2 or 3 navigations.
My worfflow is :
1) /layout/protected => unauthorized
2) HTTP redirect to backend (with "/layout/protected" in params)
3) backend redirects to front /layout/selectProfile (with "/layout/protected" in params)
4) navigate to "/layout/protected"

**Comment by brandonroberts** [comment]
@vguede ok. And you are using `$canActivate` to check to see if `/layout/protected` should be displayed and if its not then start the chain of going to `unauthorized`?

**Comment by vguede** [comment]
@brandonroberts I use `$canActivate` to check if :
1) is the component protected ?
2) if `false` => `return true` to `canActivate` ;
    if `true` => is user authenticated ?
3) if `false` => redirect HTTP to backend, and `return false` to `canActivate` ; 
    if `true` => check ACL...

**Comment by brandonroberts** [comment]
@vguede As I understand it, the $canActivate functions are done in a bottom up approach instead of a top down approach, so when the $canActivate is called for your /protected component, it doesn't have knowledge of who its parent is. That being said, unless you tell your unauthorized route that `/layout/protected` is where it should come back to when you start that process, I don't see a way that you can get that complete URL information from the previous instruction.

**Comment by vguede** [comment]
@brandonroberts but the `$router` knows the complete URL at the begining of navigation, no ?

**Comment by brandonroberts** [comment]
The $router knows the complete instruction, but its not stored during the navigation process and each child router gets its own instruction to process. The URL for the complete instruction is generated at the end. If you navigated with navigateByUrl, then you could get that information from the `$router.lastNavigationAttempt`, but navigation through a link is by instruction.

One way could be to get the href from the link and store it somewhere when clicked? At that point you reliably know what the URL is. Seems hacky though.

**Comment by vguede** [comment]
I can't strore the href because there are hundred of links...
But if I could store the instruction, il could use `navigateByInstruction()` instead of `navigateByUrl()`, and all would be fine !

**Comment by CaptainCodeman** [comment]
I've been using a class extended from `RouterOutlet` which uses the `activate(instruction: ComponentInstruction)` method to check if the navigation is allowed based on route data (public flag + roles). Depending on the authentication status is redirects to the sign-in route (set as an `@Input()`) and passes the `instruction.urlPath` which is used after authentication to redirect back to the intended route.

```
import {Directive, Input, Attribute, ElementRef, DynamicComponentLoader} from 'angular2/core';
import {Router, RouteData, RouterOutlet, Instruction, ComponentInstruction} from 'angular2/router';

/*
  Example implementation

  Given a route:
  @RouteConfig([
  { path: '/thing/:id', component: ThingComponent, name: 'Thing', data: { public: false, roles:['thinger'] } }
  ])

  authorize(instruction: ComponentInstruction):boolean {
    // simplest case - route is public
    if (<boolean>instruction.routeData.data['public']) {
      return true;
    }

    // if not public then we at least need an authenticated user
    if (this.isAuthenticated()) {
      var routeRoles = <any[]>instruction.routeData.data['roles'];
      var userRoles = <string[]>this.roles();

      // no roles required for route = user just needs to be authenticated
      var authorized = routeRoles.length === 0 || routeRoles.some(routeRole => userRoles.indexOf(routeRole) >= 0);

      return authorized;
    }

    return false;
  }
*/
export abstract class IAuthService {
  authenticated:boolean
  authorize(instruction: ComponentInstruction, params:any):boolean {
    // authorized if route allows public access or user is authenticated
    return this.authenticated || <boolean>instruction.routeData.data['public']
  }
}

@Directive({
  selector: 'secure-outlet'
})
export class SecureRouterOutlet extends RouterOutlet {
  @Input() signin:string;
  @Input() unauthorized:string;
  @Input() params:any;

  publicRoutes: any;
  private parentRouter: Router;
  private authService: IAuthService;

  constructor(_elementRef: ElementRef, _loader: DynamicComponentLoader,
              _parentRouter: Router, @Attribute('name') nameAttr: string,
              authService:IAuthService) {
    super(_elementRef, _loader, _parentRouter, nameAttr);
    this.parentRouter = _parentRouter;
    this.authService = authService;
  }

  activate(instruction: ComponentInstruction) {
    if (this.authService.authorize(instruction, this.params)) {
      return super.activate(instruction);
    }

    this.parentRouter.navigate([this.signin, { path: instruction.urlPath, params: instruction.urlParams }])
  }
}
```

Within the view it's used as:

`<secure-outlet signin="Signin" unauthorized="Home"></secure-outlet>`

(the signin / unauthorized attributes are the route names to use)

Hope that makes sense.

**Comment by brandonroberts** [comment]
You could also override the `$router.navigateByInstruction` to get the URL.

```js
    var $navigate = $router.navigateByInstruction;
    
    $router.navigateByInstruction = function(instruction) {
      // set url
      console.log(instruction.toRootUrl());
      
      // call original $router.navigateByInstruction
      $navigate.apply(this, arguments);
    };
```

Example: http://plnkr.co/edit/YFyqCfWzJ9IG8bayTsop?p=preview

**Comment by CaptainCodeman** [comment]
Oops, I may have simplified it too much - it should check the `authenticated` property to decide whether to redirect to the signin or home route if not authorized.

The `IAuthService` is implemented by an `authService` which handles the role checks, sign-in, JWT tokens etc...

**Comment by vguede** [comment]
@brandonroberts Your solution is perfect ! Thank you so much once more !

**Comment by vguede** [comment]
Even simpler :
```javascript
var $navigate = $router.navigateByInstruction;

$router.navigateByInstruction = function(instruction) {
  // set url
  this.currentUrl = instruction.toRootUrl();

  // call original $router.navigateByInstruction
  $navigate.apply(this, arguments);
};

console.log($router.currentUrl);
```

**Comment by brandonroberts** [comment]
I wouldn't call it the current URL since the instruction may get cancelled
but :+1:

**Comment by vguede** [comment]
You're right, as usual !
