### ISSUE TITLE
Router: Order of imports breaks the app

### ISSUE THREAD

**Issue by AlmeroSteyn** [angular/angular#7125]
When defining a basic route config the order of importing router components seems to matter. Found this at AngularClass at NG-NL. Igor debugged the application and saw this happening.

Using 0.19.8 version of SystemJS.

**With the following import sequence it fails:**

import {Component} from 'angular2/core';
import {ROUTER_PROVIDERS} from 'angular2/router';
import {bootstrap} from 'angular2/platform/browser';
import {ContactHeaderComponent} from './components/contact-header/contact-header-component';
import {ContactsListComponent} from './components/contacts-list/contacts-list-component';
import {ContactsService} from "./common/contacts-service";
import {RouteConfig} from "angular2/router";
import {ROUTER_DIRECTIVES} from "angular2/router";
import {ContactDetailComponent} from "./components/contact-detail/contact-detail-component";

@Component({
  selector: 'contacts-app',
  template: `<contact-header></contact-header>
             <router-outlet></router-outlet>
             `,
  directives: [ContactHeaderComponent, ROUTER_DIRECTIVES]
})
@RouteConfig([
  {
    path: '/',
    component: ContactsListComponent,
    name: 'ContactsList'
  }  ,
  {
    path: '/contacts',
    component: ContactDetailComponent,
    name: 'ContactDetail'
  }
])
export class ContactsApp {
}

bootstrap(ContactsApp, [ContactsService, ROUTER_PROVIDERS]);

**If defined as follows it works:**

import {ROUTER_PROVIDERS, ROUTER_DIRECTIVES, RouteConfig} from 'angular2/router';

import {Component} from 'angular2/core';
import {bootstrap} from 'angular2/platform/browser';
import {ContactHeaderComponent} from './components/contact-header/contact-header-component';
import {ContactsListComponent} from './components/contacts-list/contacts-list-component';
import {ContactsService} from "./common/contacts-service";
import {ContactDetailComponent} from "./components/contact-detail/contact-detail-component";

@Component({
  selector: 'contacts-app',
  template: `<contact-header></contact-header>
             <router-outlet></router-outlet>
             `,
  directives: [ContactHeaderComponent, ROUTER_DIRECTIVES]
})
@RouteConfig([
  {
    path: '/',
    component: ContactsListComponent,
    name: 'ContactsList'
  }  ,
  {
    path: '/contacts',
    component: ContactDetailComponent,
    name: 'ContactDetail'
  }
])
export class ContactsApp {
}

bootstrap(ContactsApp, [ContactsService, ROUTER_PROVIDERS]);

**Comment by ericmartinezr** [comment]
I think this comment can give you some hints about this issue (at first sight it seems related) https://github.com/angular/angular/issues/7094#issuecomment-184683890

**Comment by CaptainCodeman** [comment]
I remember when software development seemed to involve less prayer, magic and reliance on planets being aligned correctly for things to work.This is making me feel old.

**Comment by AlmeroSteyn** [comment]
@ericmartinezr : Well spotted! Importing all with double quotes fixed the problem. Would be nice if this was not an issue.

For the record, and to relate it to the fix, the error this produced was "Error: router_2.RouteConfig is not a function". 

I assume this is a systemjs issue?
