### ISSUE TITLE
What's the proper way of accessing native element in angular2 (2 diff ways) docs are scarce

### ISSUE THREAD

**Issue by born2net** [angular/angular#7129]
What's the proper way of accessing native element in angular2 (2 diff ways)
so I have seen code that uses:
```
    constructor(ele: ElementRef) {
	 	let myEl = ele.nativeElement;
        // do some work on myEl such as jQuery(myEl).hide()
	    ...
```
as well as code that uses native dom via BrowserDomAdapter:
```
    constructor(viewContainer:ViewContainerRef) {
       let dom = new BrowserDomAdapter();
       let el = viewContainer.element.nativeElement; 
       let myEle = dom.getElementsByClassName(el, element)[0];
       // or jQuery(myEle).hide()
       ...
```
and I am wondering what's the Pro / Cons and "proper" way of doing things...
docs seems scarce still

I am assuming the latter will give you WebWorkers support through the interface but its just my assumption

regards

Sean

**Comment by zoechi** [comment]
http://stackoverflow.com/questions/35463642/whats-the-proper-way-of-accessing-native-element-in-angular2-2-diff-ways-docs
GitHub issues are for bugs and feature requests. Please use SO, Gitter, Google groups,...  for support questions.

**Comment by born2net** [comment]
no prob, sorry... closing!
