### ISSUE TITLE
Router: Changing views breaks PolymerJs component

### ISSUE THREAD

**Issue by disposition68** [angular/angular#7130]
This is how my markup should and does look before routing:

`<iwe-panelcontent><div>...</div></iwe-panelcontent>`

After routing to a new page and then pressing the browser's back button, it becomes:

`<iwe-panelcontent></iwe-panelcontent><div>...</div>`

Polymer uses the `<content>` tag in templates so that the inner html of a custom element becomes the content of said element. It seems that everything inside the `<content>` tag is getting thrown out to the element's outer html. Not sure if this has anything at all to do with routing, but since the issue crops up while using the routing functionality, I assume they are related in some way.

**Comment by vicb** [comment]
Please add a repro in a plunker. Thanks.

**Comment by vicb** [comment]
Closing as no repro. Please re-open if you have a minimal repro!
