### ISSUE TITLE
MockConnection.mockError() should result in a returned Response instead of Error

### ISSUE THREAD

**Issue by justindsmith** [angular/angular#7135]
In the base implementation of `XHRBackend` ([link](https://github.com/angular/angular/blob/2.0.0-beta.6/modules/angular2/src/http/backends/xhr_backend.ts#L69-L75)) when an error is detected a `Response` object is created and returned to the observer. In the `MockBackend`, when `mockError()` is called, the error is directly passed to the observer ([link](https://github.com/angular/angular/blob/2.0.0-beta.6/modules/angular2/src/http/backends/mock_backend.ts#L85-L88)). 

This means error use cases can't be easily tested because the error payload object will be different between browser and testing.

In the mean time you can pass a `Response` object to the `mockError()` function to get around the problem, but it will break the typescript compiler (lots of warnings).

Suggestion is to either accept a `Response` object in the `mockError()` or package the `Error` into a `Response` object as is done in the `XHRBackend`. (I notice that there is already a [TODO](https://github.com/angular/angular/blob/2.0.0-beta.6/modules/angular2/src/http/backends/mock_backend.ts#L79) in the `MockConnection` class to "consider using Response type".)

**Comment by lthoang101** [comment]
I was facing the same issue. The temporary workaround that I've come up with is to do a double cast of type Response to type Error. 
e.g mockError(myResponse as any as Error)

**Comment by ckuetbach** [comment]
This would fix the problem: #8961

**Comment by evasquez26** [comment]
Any news on this?

**Comment by splincode** [comment]
@mhevery @justindsmith This issue is relevant?
