### ISSUE TITLE
Testability whenStable should work with XHRs and Routing

### ISSUE THREAD

**Issue by juliemr** [angular/angular#7141]
Here is a branch showing that `whenStable` will not correctly wait for XHRs or route changes: https://github.com/juliemr/angular/commit/4f31e168a4db61e475ab8030e83d0052e208b655

It should.

**Comment by juliemr** [comment]
Chatted with @mhevery and we decided that the best way to fix this is to submit a change to zone.js to track XHRs like macro events ("timeouts").

I'm not yet sure how this would work with Dart zones.

**Comment by mhevery** [comment]
Hmm... I don't see a way to do it in Dart either. I think we should fire this question to the dart team.

**Comment by juliemr** [comment]
For the record - another option would be to use `testability#increasePendingRequestCount` in Angular's XHR wrappers - see WIP commit here: https://github.com/juliemr/angular/commit/de807dfc054e5a09bc9db45e18eee3982ec21c05

This has a couple disadvantages - it won't work for user's application code which uses XHR via any other method, and it doesn't solve the core problem in zones.

**Comment by mhevery** [comment]
In dart we don't wrap the XHR, we let the developers use them directly.

**Comment by juliemr** [comment]
After chatting with the Dart team, their view is that Dart Zones won't be able to do this without either unstable hacks or wrapping the XHR anyway.

**Comment by juliemr** [comment]
This now works with TypeScript - see #7290 for the issue with Dart.
