### ISSUE TITLE
EXCEPTION: [object Object] when HTTP error occurs without an error handler

### ISSUE THREAD

**Issue by dceddia** [angular/angular#7143]
This is with Angular 2 beta 2 - see the Plunker here: http://plnkr.co/edit/QItK2ECim8IZvGXTPHeb?p=preview (check the console).

I expected something more descriptive than "[object Object]".

This is the relevant bit, from `app.ts`:
```javascript
    // This handles the error:
    http.get("/")
      .map(res => res.text())
      .subscribe(
        body => console.log(body),
        err => console.log('error!', err)); 
    
    // Without an error handler, "EXCEPTION: [object Object]" is thrown
    http.get("/")
      .map(res => res.text())
      .subscribe(
        body => console.log(body)); 
```

Try a breakpoint at angular2.js:1187 - it looks like the problem is in [exception_handler.ts](https://github.com/angular/angular/blob/b0009f03d510370d9782cf76197f95bb40d16c6a/modules/angular2/src/facade/exception_handler.ts#L82-L84) - when the exception is a `Response`, toString doesn't do anything meaningful. Not sure about the best way to fix this.

**Comment by michalstepien** [comment]
You can always write own Error handler 
https://github.com/angular/angular/blob/979657989bab4fb93faf6a207d30760faa9bd696/modules/%40angular/core/src/error_handler.ts
:)

**Comment by DzmitryShylovich** [comment]
@vicb I think this was fixed by https://github.com/hbkrunal/angular/commit/458ad159ea884f25651153419cccad77398e8178 and can be closed.

**Comment by vicb** [comment]
@DzmitryShylovich thanks !
