### ISSUE TITLE
Add shims_for_IE.js to bundle and https://code.angularjs.org

### ISSUE THREAD

**Issue by wardbell** [angular/angular#7145]
See issue #7144

**Question: Why not fold these polyfills into angular2-polyfills.js which is required already???**

If not, we should make these shims more easily accessible.

I realize that `shims_for_IE.js` is in the npm package ... buried as `angular2/es6/dev/src/testing/shims_for_IE.js`.

That's way down there and it is a concern far broader than testing.
We also need it in `https://code.angularjs.org` for plunkers and such

**Comment by adiospl** [comment]
In my project I added also these code to shims_for_IE:
`
// Shim for proper handling SVG g element in Angular
if (!("classList" in document.createElementNS("http://www.w3.org/2000/svg","g"))) {
    var descr = Object.getOwnPropertyDescriptor(HTMLElement.prototype, 'classList');
    Object.defineProperty(SVGElement.prototype, 'classList', descr);
}
`

it enables interactions with svg documents on IE.

**Comment by IgorMinar** [comment]
Some of the current shims are problematic from the licensing standpoint. we can't just distribute code without proper license. we'll need to investigate some better alternatives (or resolve the licensing issues) before publishing this code on our servers.

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166441.
------------------------------------------------------------------------------------------------------------


[[321b11083c6998f5009fdf1b7ecec76765b9684c-673073283]]

**Comment by allenhwkim** [comment]
+1 on this issue

**Comment by skreborn** [comment]
@allenhwkim The current [Quickstart](https://angular.io/docs/ts/latest/quickstart.html) advises you to use `core-js` instead.

**Comment by tiagomatosweb** [comment]
I have added core-js as the quickstart recommend, but it didn't work! So, back to the old approach adding

'./node_modules/es6-shim/es6-shim.min.js',
'./node_modules/systemjs/dist/system-polyfills.js',
'./node_modules/angular2/es6/dev/src/testing/shims_for_IE.js',

**Comment by IgorMinar** [comment]
we are not going to publish the shims file on code. we should use npm cdn or https://polyfill.io instead
