### ISSUE TITLE
Can not use Angualr 2 router in a component when using ngUpgrade

### ISSUE THREAD

**Issue by jusefb** [angular/angular#7147]
Hi,

I am trying to embark on the upgrade process for one of my Angular 1 applications. I have managed to get Angular 1 and Angular 2 working together by creating an Angular 2 component and then bootstrapping it using the ngUpgrade adapter. I have then tried to use the Angular 2 Router in the component to wire other portions of the application but got the following error:

"Bootstrap at least one component before injecting Router"

Does this mean that it is not possible to use Angular 2 router when going down the ngUpgrade path? If this is the case then the upgrade story becomes a lot more complicated as you can start writing component using Angular 2 that work in angular 1 but you can't write an Angular 2 component that has routable child components and then use it in an Angular 1 application.

Am I misunderstanding something here?

Kind regards

Jusef

**Comment by ericmartinezr** [comment]
see https://github.com/angular/angular/issues/5423

**Comment by brandonroberts** [comment]
You can get the Angular 2 Router working with ngUpgrade now. You have to provide the router with its root component.

TypeScript example: http://plnkr.co/edit/SzTNu5X6uNeSVC0Lq85N?p=preview

**Comment by jusefb** [comment]
Yup, exactly what I was looking for. Thanks a lot for such a quick and helpful response.

**Comment by ptomaszi** [comment]
@brandonroberts your example works fine with Angular 1 RC.1. Angular team changed how the router works in the latest RC.4 so I cannot see any examples how can we get component router working withing the upgraded environment?

**Comment by mwaa** [comment]
see #9870

**Comment by vicb** [comment]
obsolete
