### ISSUE TITLE
Angular 2 - Multilingual Support

### ISSUE THREAD

**Issue by pshirsath** [angular/angular#7148]
We are using Angular 2.0 in our Application. In that application we want to give multilingual support.We know using angular 1.0 how to implement. but don't know how to use in 2.0.

**Comment by OsoianMarcel** [comment]
https://angular.io/features.html read last feature

**Comment by woppa684** [comment]
For now you could look at 

https://github.com/ocombe/ng2-translate

**Comment by zoechi** [comment]
https://github.com/angular/i18n/issues/28

**Comment by mhevery** [comment]
Closing since this is a question not an issue.
