### ISSUE TITLE
API Docs: Make "exported from ..." message more visible 

### ISSUE THREAD

**Issue by traviskaufman** [angular/angular#7151]
Consider the page https://angular.io/docs/ts/latest/api/core/EventEmitter-class.html

At the very bottom in small text it reads

> exported from angular2/core defined in angular2/src/facade/async.ts (line 64)

For me this was relatively difficult to locate. I feel like this should maybe be put in a more visible place, such as next to the title of the entity being viewed. Placing this here makes it so that all of the information needed to write a complete `import ...` statement is in one place. 

Just a suggestion :smile: Keep up the great work!

**Comment by vicb** [comment]
obsolete
