### ISSUE TITLE
angular2: EXCEPTION: TypeError: viewFactory_ColumnIteratorComponent0 is not a function in [element.column in RowIteratorComponent@4:26]

### ISSUE THREAD

**Issue by tonimora74** [angular/angular#7153]
I updated my core files AngularJS 2 Beta 0 to Beta 6 and have this incomprehensible error (in Beta 0 works perfectly). This is my coce:

```
import {Component,forwardRef} from 'angular2/core';
import {RowIteratorComponent} from './rowIterator.component';
import {ModuleIteratorComponent} from './moduleIterator.component';

@Component({
  selector: '[columnIterator]',
  template:`    
    <div *ngFor="#element of columnData">    
      <div rowIterator *ngIf="element.row" [ngClass]="element.class" [rowData]="element.row"></div>    
      <div moduleIterator *ngIf="element.module" [ngClass]="element.class" [moduleData]="element.module"></div>
    </div>
  `,
  inputs: ['columnData'],
  directives: [forwardRef(function(){return RowIteratorComponent;}), ModuleIteratorComponent]
})
export class ColumnIteratorComponent {
}
```
I use "forwardRef" because this component works "loop" and thus runs smoothly.  El RowIteratorComponent is the same code: 

```
import {Component,forwardRef} from 'angular2/core';
import {ColumnIteratorComponent} from './columnIterator.component';
import {ModuleIteratorComponent} from './moduleIterator.component';

@Component({
  selector: '[rowIterator]',
  template: `
    <div *ngFor="#element of rowData">
      <div columnIterator *ngIf="element.column" [ngClass]="element.class" [columnData]="element.column"></div>

      <div moduleIterator *ngIf="element.module" [ngClass]="element.class" [moduleData]="element.module"></div>
    </div> 
    `,
  inputs: ['rowData'],
  directives: [forwardRef(function() { return ColumnIteratorComponent; }),ModuleIteratorComponent]
})
export class RowIteratorComponent {

}

```

What is the problem in AngularJS 2 Beta 6? I'm going crazy...

**Comment by ericmartinezr** [comment]
Dup of https://github.com/angular/angular/issues/7037

**Comment by tonimora74** [comment]
Thanks @ericmartinezr, from now on I'm the other thread or link?

**Comment by tonimora74** [comment]
thank @ericmartinezr , from now on I'm the other thread or link?

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166446.
------------------------------------------------------------------------------------------------------------


[[4a486e49165a261eea0369fac046bc04817a6193-673073310]]

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166451.
------------------------------------------------------------------------------------------------------------


[[f7600d4b375b2f7eb14cbe615e5ebcec2cbcdac2-673073331]]

**Comment by pkozlowski-opensource** [comment]
Dup of #7037, already fixed. Thnx @ericmartinezr
