### ISSUE TITLE
Templates need to distinguish imports from refs.

### ISSUE THREAD

**Issue by mhevery** [angular/angular#7158]
Current semantics of `#ref` are not correct in context of templates. Consider this example:

```
<ul #parent>
  <template #child ngFor #item [ngForOf]='items'><li>{{item}}</li></template>
</ul>
<button (click)="log(parent)">works</button>
<button (click)="log(child)">breaks</button>
```

Here the `parent` can be accessed anywhere in the outer template but `child` can only be accessed in the inner template. This means that it is not possible to get a reference to the inner template.

The issue is that `#` is declaring a reference not an input. So the above example should be written in a way where references and inputs are declared in a clear way by changing the semantics of `#` to be consistent, and have a separate syntax template inputs.

## Proposal

- `#foo` or `ref-foo` create a reference which is visible anywhere in the parent template.
- `let-foo` (no shorthand syntax) creates an input into a template which can only be used on a template.
```
<ul #parent>
  <template #child ngFor let-item [ngForOf]='items'><li>{{item}}</li></template>
</ul>
<button (click)="log(parent)">works</button>
<button (click)="log(child)">works</button>
```

## Consequences

Template syntax will change to:

```
<ul>
  <template ngFor let-item [ngForOf]='items'><li>{{item}}</li></template>
</ul>
```

or

```
<ul>
  <li *ngFor="let item in items">{{item}}</li>
</ul>
```

and long form `var-foo` will change to `ref-foo`.

## Deprecation

- temporarily support `*ngFor="#item in items"` with a `console.warn` to switch to the new `*ngFor="let item in items"` syntax.
- depreciation  warning on using  `var-foo`.

**Comment by tbosch** [comment]
+1

**Comment by tbosch** [comment]
Blocked on https://github.com/angular/angular/issues/6270

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166501.
------------------------------------------------------------------------------------------------------------


[[5dec737bb4a58afa4eff388553b1a8f141c31215-673073831]]

**Comment by user414** [comment]
Haven't updated to latest yet, but saw this change and wanted to comment. To keep things consistent in providing shorthand notation for a lot of things I would have liked to see another symbol for "let-" so perhaps something like "@variable" for variable and "#reference" for reference. Not so much the extra character that's an issue but more for consistency in providing non verbose mean for a lot of other semantic.
