### ISSUE TITLE
Type error when using downgradeNg2Component

### ISSUE THREAD

**Issue by chrisnicola** [angular/angular#7159]
The following code seems to throw a Type error if you are using the ambient Angular 1.x typings files with Typescript.

```
angular.module('components').directive('myComponent', upgradeAdapter.downgradeNg2Component(Angular2Component))
```

```
error TS2345: Argument of type 'Function' is not assignable to parameter of type 'any[]'.
  Property 'find' is missing in type 'Function'.
```

Seems that the Angular typings file expects either `IDirectiveFactory` or `any[]` to be passed in here. 

For now casting the component to `any` solves the issue but I figured this might want to be looked at so it integrates more smoothly under Typescript.

**Comment by jesussobrino** [comment]
Hi there @chrisnicola.

I had the same problem, and I found a possible solution on stackoverflow: http://stackoverflow.com/questions/34954650/angular-2-setup-issue 

Try this code:

`angular.module('components', []).directive('myComponent', <angular.IDirectiveFactory>adapter.downgradeNg2Component(Angular2Component) );`

**Comment by petebacondarwin** [comment]
I believe that the typings for Angular 1 have been updated to address this: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/angular/index.d.ts#L30
