### ISSUE TITLE
Missing example on how ContentChild works with refs in the docs.

### ISSUE THREAD

**Issue by mhevery** [angular/angular#7160]
https://angular.io/docs/ts/latest/api/core/ContentChild-var.html

```
@ContentChild("btn1")
<button #btn1></button>
```

**Comment by manekinekko** [comment]
I'll fix this

**Comment by ericmartinezr** [comment]
This should consider ViewChild/ViewChildren and ContentChildren. All of them can use refs.

**Comment by manekinekko** [comment]
this makes sens
