### ISSUE TITLE
Http client call in AngularJS 2.0 does not work

### ISSUE THREAD

**Issue by xAngular** [angular/angular#7164]
I followed through the steps described in 10. Http Client under Developer Guide. As soon as I took out the lines in toh.component.ts related to "in-memory web api", it does not work. Please see plunker: http://plnkr.co/edit/rDiKhxaITrZJusKsRMEi?p=preview
Can someone be help?

**Comment by ericmartinezr** [comment]
@xAngular you should report this issue over here https://github.com/angular/angular.io , for what I see they missed the `.json` in the url.

**Comment by xAngular** [comment]
Thank you very much. You are exactly right. As soon as I added .json at the end of the url. It start returning "Heroes". I should have spotted that.

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166463.
------------------------------------------------------------------------------------------------------------


[[647121c669ff5958c444b9f0a7f9793cb7f7ca23-673073419]]

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166495.
------------------------------------------------------------------------------------------------------------


[[84b601f868e1423b1d295376af8c8d449701472b-673073814]]
