### ISSUE TITLE
bug: setting readonly on ElementRef nativeElement

### ISSUE THREAD

**Issue by bitbay** [angular/angular#7173]
Setting the `readonly` property through script on a `<HTMLInputElement>ElementRef`s `nativeElement` doesn't set the attribute on the DOM element.

Please see [this plnkr](http://plnkr.co/edit/x9ePvRb2BrOt2XRcKVYF?p=preview).

**edit**
updated plnkr link to preview

**Comment by zoechi** [comment]
```ts
this.elementRef.nativeElement.setAttribute('readonly', true);
```
works fine though

http://plnkr.co/edit/DXMQzGbohE0etnMdtsMZ?p=preview

**Comment by bitbay** [comment]
facepalm - javascript uses camelCase for this
```
this.elementRef.nativeElement.readOnly = true;
```

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166436.
------------------------------------------------------------------------------------------------------------


[[c7418b1cd25522a1d7d368c9085011875ec3f8db-673073271]]

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166433.
------------------------------------------------------------------------------------------------------------


[[ccee1fa9999928a5dd2d397781722d146a284b2e-673073267]]

**Comment by craros92** [comment]
@zoechi @bitbay but what happen if i put this:
`this.elementRef.nativeElement.setAttribute('readonly', false);` or
`this.elementRef.nativeElement.readOnly = false;`

why readOnly is still working?

**Comment by tytskyi** [comment]
@craros92 

Just checked with your example:

`this.elementRef.nativeElement.readOnly = false;`
this works - field is read-write.

the method approach is
`this.elementRef.nativeElement.removeAttribute('readonly');`

__

Short answer why it works like this, because `setAttribute()` set's HTML attribute on element (which works when present). For example `this.elementRef.nativeElement.setAttribute('readonly', "blablabla");` blocks input from write-mode as well.

Meanwhile `readOnly` is a DOM property.

It happened historically that some attributes has matching pair property. Then when you update attribute matching DOM property also updates (and vice versa), BUT with value that is allowed for the property. Which means that browser hides this process from you - and calculates valid value of property.

Try this in your example:

```typescript
  ngAfterViewInit(){
    alert(this.elementRef.nativeElement.readOnly);
    this.elementRef.nativeElement.setAttribute('readonly', "blabla");
    setTimeout(() => {
      alert(this.elementRef.nativeElement.readOnly);
    });
  }
```
Output will be: "false",  "true". Which looks like non-sense. But it works like this.

Observe the same effect on `value`
```typescript
  ngAfterViewInit(){
    alert(this.elementRef.nativeElement.value);
    this.elementRef.nativeElement.setAttribute('value', "blabla");
    setTimeout(() => {
      alert(this.elementRef.nativeElement.value);
    });
  }

// elementRef.nativeElement
// blabla
```

But again **this is exclusively** for matching pairs of known attribute/property. For example:
```typescript
  ngAfterViewInit(){
    alert(this.elementRef.nativeElement.custom);
    this.elementRef.nativeElement.setAttribute('custom', "blabla");
    setTimeout(() => {
      alert(this.elementRef.nativeElement.custom);
    });
  }
// undefined
// undefined
```

**Comment by bitbay** [comment]
@craros92 have a look at the specs [here](https://html.spec.whatwg.org/multipage/forms.html#the-input-element).
I [was referring to](https://github.com/angular/angular/issues/7173#issuecomment-186198886) the subtle difference between what is stated as "Content attributes" and "DOM (programming) interface" in the whatwg.org document.
While in the "content attributes" (aka node attributes, as in `<element attribute="value"/>`) the property appears **all lowercase** `readonly`, in the DOM interface ("as it appears to javascript") it is listed with **camelCase** `readOnly`.
Doesn't matter if You use the `readOnly` property in javascript of the element or use the `.setAttribute()` method of it, You are still accessing to the same "content attribute" of the `<input>` DOM element/node.
Hope this clears it up! Cheers.
