### ISSUE TITLE
External plugins and form controls

### ISSUE THREAD

**Issue by schusovskoy** [angular/angular#7175]
Hello,
I create a directive which simply add jquery.inputmask plugin in ngAfterViewInit callback. All work great, except one thing. When I get the whole form value, the value of control on which the plugin is applied is empty string. It seems that angular doesn't detect changes on that input.

**Comment by zoechi** [comment]
Some Plunker to reproduce and demonstrate what you tried to accomplish?

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166437.
------------------------------------------------------------------------------------------------------------


[[326eaefc455f7623259595ad94fcd18951fa51dc-673073273]]

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166444.
------------------------------------------------------------------------------------------------------------


[[e5756c9af58e3cfa03f1db0124ca2775198088a5-673073303]]

**Comment by pkozlowski-opensource** [comment]
Closing as we are lacking details to make it actionable.
