### ISSUE TITLE
Internationalising the application

### ISSUE THREAD

**Issue by jusefb** [angular/angular#7179]
Hi,

We continuing our upgrade of our Angular project and starting to make some good progress. Our app is used by Dutch and English clients and we have used angular-translate in the past to translate our application. I was trying to see if I could use the inbuilt internationalisation capabilities of Angular 2 but could not find anything on how to use it and could not see any source files in the Angular 2 package. 

Is there a way to translate Angular 2 applications today that will not require another rewrite in the future?

Kind regards

Jusef

**Comment by brandonroberts** [comment]
Take a look at ng2-translate. https://github.com/ocombe/ng2-translate

**Comment by spock123** [comment]
Yeah, I'm usingn ng2-translate in my application and it works great!

**Comment by jusefb** [comment]
Ok thanks will try this out since there does not seem to be an alternative at the moment

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166450.
------------------------------------------------------------------------------------------------------------


[[4024b528eb0926299fa5bc5f6cbb2bda0b0929bd-673073329]]

**Comment by pkozlowski-opensource** [comment]
i18n solution is still in the works / finalization
