### ISSUE TITLE
Lock external dependencies

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#718]
Our build is currently non-deterministic and therefor hard to reproduce because many of the external dependencies are being resolved during build time, so it's possible for a single sha to create many different build artifacts depending on when the build happens.

To fix this, we need to lock down all external dependencies.

This will include:

- [ ] npm dependencies (which should be locked down via `npm-shrinkwrap.json`)
- [ ] pub dependencies (which should be locked down via `pubspec.lock` file)
- [ ] dart sdk + dartium dependencies (which should be locked down by fetching a concrete version rather than whatever the latest version is

Once the dependencies are locked, we can use travis cache to cache the dependencies and speed up the build startup time just like we did in the [angular.js repo](https://github.com/angular/angular.js/commit/507ee2d9bac77841681282dfcba9297dda576b41).

**Comment by alexeagle** [comment]
This issue should probably be broken into smaller ones; most of the work is done (npm shrinkwrap)
If we make smaller bugs, we should also have one for making the shrinkwrap work better. We need npm and node to be the same version as travis, and fix the rough edges that everyone hits when they have to update shrinkwrap

**Comment by mhevery** [comment]
Most of it is done.
