### ISSUE TITLE
Quickstart fails with Beta7

### ISSUE THREAD

**Issue by cagataycivici** [angular/angular#7181]
When updating the quick start to beta7, app doesn't start up and following error is displayed on console;

> Uncaught SyntaxError: Unexpected token <
	Evaluating http://localhost:3000/rxjs/observable/PromiseObservable
	Error loading http://localhost:3000/app/main.js

**Comment by onikiienko** [comment]
same issue for me, so the only one decision is
"angular2": "2.0.0-beta.6"
for now

**Comment by jeffbcross** [comment]
The peerDependency of rxjs was also updated with beta.7. So you'll need to `npm install rxjs@5.0.0-beta.2` or download the bundle from https://code.angularjs.org/2.0.0-beta.7/Rx.js

**Comment by onikiienko** [comment]
works fine. thanks!

**Comment by alexeagle** [comment]
Cc @igorminar

**Comment by cagataycivici** [comment]
Works, thanks!

**Comment by xuhong** [comment]
Works, thanks!

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166438.
------------------------------------------------------------------------------------------------------------


[[72048d47e1420af5f44227bc1bae7342ec28e701-673073272]]
