### ISSUE TITLE
Doubt: Encapsulation and component recursion

### ISSUE THREAD

**Issue by dlcardozo** [angular/angular#7184]
I have the next plunker

https://plnkr.co/edit/NkGx0h?p=preview

I want to know if this one is the expected behavior and if it's, how I can get something like native encapsulation but with emulated encapsulation?

Usage:

If you press the toggle button, the text color of one component will change and all the childrens instead of be independent like if you use native encapsulation.

The problem is that I know that the browser in which this app will run doesn't support native encapsulation, so how I should proceed with this?

**Comment by zoechi** [comment]
Load the https://github.com/WebComponents/webcomponentsjs polyfill (not the `-lite`)

**Comment by dlcardozo** [comment]
thanks @zoechi I'll try it!

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166453.
------------------------------------------------------------------------------------------------------------


[[ab58af6699e1634d9a1addf1487b698922c91cb5-673073389]]
