### ISSUE TITLE
How i can bind non-singleton dependency to singleton (application wide) service?

### ISSUE THREAD

**Issue by sanex3339** [angular/angular#7189]
At first, sorry for many grammar errors.

For example, i have two application-wide singleton services (ServiceA and ServiceB) - wrappers over CollectionService, and have CollectionService as their constructor dependency. These two services must store various data through all application life-cycle. These services just pass data through himself to the CollectionService. 
So, CollectionService should not be an singleton service, just regular dependency, that create new object each time, when their parent was created.
Also, CollectionService can be used somewhere else in application as dependency in other non-singleton services.

I have tried to set ServiceA and ServiceB inside bootstrap throug useFactory:

```
imports ...

bootstrap(AppComponent, [
    provide(ServiceA, {
        useFactory: () => {
            rerturn new ServiceA(new CollectionService<ServiceADataType>())
        }
    }),
    provide(ServiceB, {
        useFactory: () => {
            rerturn new ServiceB(new CollectionService<ServiceBDataType>())
        }
    })
]);
```

With that code i got error 
`Cannot read property 'getOptional' of undefined`

I can't put CollectionService directly into bootstrap, because after that CollectionService becomes an singleton, and data that will passed to this service from ServiceA and ServiceB will shared.

Also, i want to use ServiceA inside CanActivate routeHook, so, i need to use singleton Injector inside that hook, which must give me ServiceA with resolved CollectionService.

```
export const AppInjector = (injector?: Injector): Injector => {
    if (injector) {
        appInjectorRef = injector;
    }

    return appInjectorRef;
};

bootstrap(AppComponent, [
   ...
]).then((appRef: ComponentRef) => {
    AppInjector(appRef.injector);
});
```
So, my question - how i can correct bind all that services?

PS: StackOverflow didn't help me (but tried)

**Comment by sanex3339** [comment]
```
provide(ServiceA, {
    useValue: new ServiceA(new CollectionService<ServiceADataType>())
})
```

That works. So, why useFactory throws `Cannot read property 'getOptional' of undefined` error?

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166479.
------------------------------------------------------------------------------------------------------------


[[64f084c56a22570a27bacb71f891da32644e6e4c-673073749]]
