### ISSUE TITLE
Use travis cache

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#719]
(This is related to #718 but doesn't really depend on it.)

Use [travis cache] to cache the following dependencies:
- [ ] `node_modules` directory for npm dependencies
- [ ] `packages` directory for pub dependencies

Example commit of how this was done for Angular v1: https://github.com/angular/angular.js/commit/507ee2d9bac77841681282dfcba9297dda576b41

More docs on travis caching: http://docs.travis-ci.com/user/caching/

**Comment by IgorMinar** [comment]
This will be slightly more complicated due to npm being vulnerable to cache poisoning, we have a workaround though see: https://github.com/angular/angular.js/pull/11110#issuecomment-75302946

**Comment by alexeagle** [comment]
It would also be good to cache the pub dependencies. The Travis build sometimes flakes when it cannot download a pub package.

**Comment by vicb** [comment]
`packages`should not be cached for Dart, it only symlinks to the actual pub cache, see https://www.dartlang.org/tools/pub/cmd/pub-get.html for more info.

TL;DR:
Default pub cache directory is `~/.pub-cache` could be overridden via the PUB_CACHE env variable.

**Comment by mhevery** [comment]
I think this is done. Reopen if not
