### ISSUE TITLE
Component initialization infinity loop

### ISSUE THREAD

**Issue by DontRelaX** [angular/angular#7190]
Hi,
I got infinity initialization loop if I add component in plain js defined like:
```
Component({
    ...
    directives: [SuperComponent] 
}).Class({
    constructor: function costructor() {}
});
```
Important points here is not empty directives and constructor function with dublicated name. Code like this I got after using babel with es2015 preset.
As workaround I made preset without plugin that generate dublicated name:
https://github.com/DontRelaX/babel-preset-es2015-without-function-name

How to reproduce:
1. Open http://jsfiddle.net/5th3tqsc/5/
2. It should work
3. Add constructor name for both components
4. Press Run
5. Browser crashed.

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166489.
------------------------------------------------------------------------------------------------------------


[[f9e139f02407417335a36f21edee22ed204547cb-673073791]]

**Comment by vicb** [comment]
Is this still a pb with 2.0.0 ?

**Comment by vicb** [comment]
closing as not updated.
