### ISSUE TITLE
@Output attributes not emitting events if subclass has any @Input defined.

### ISSUE THREAD

**Issue by derekshi** [angular/angular#7191]
I have a following class
```
export class AddAnimalComponent {
  public st: string;
  public dyn: string;
  public errMessage: string;
  @Output() added = new EventEmitter<Animal>();

  constructor() {
  }

  add() {
    throw new Error('Not implemented');
  }

  clearErr() {
    this.errMessage = '';
  }

  normalize() {
    this.st = this.st.trim();
    if (this.dyn) {
      this.dyn = this.dyn.trim();
    }
  }

  clear() {
    this.clearErr();
    this.st = '';
    if (this.dyn) {
      this.dyn = '';
    }
  }
}
```

And then a subclass:
```
@Component({
  selector: 'add-expansion',
  templateUrl: './templates/add-expansion.html',
  directives: [MultiValueInput]
})

export class AddExpansionComponent extends AddAnimalComponent implements AfterViewInit {
  //@Input('expansion') expansionType: string;

  constructor(private _animalService: AnimalService,
              @Inject('App.constants') private constants,
              private toastr: ToastsManager
  ) {
    super();
  }

  ngAfterViewInit() {
    //if (!this.expansionType) {
    //  throw new Error('No expansion synonym type specified.');
    //}
  }

  add() {
    this.clearErr();
    this.normalize();

    if (this.st && this.st.length) {
      let abbr = new Animal(this.st);
      this._animalService.addAnimal(this.constants.activePartner, 'expansion-synonym', abbr)
        .subscribe((data) => {
            if (!data.success) {
              this.toastr.error(data.error, 'Oops');
              if (data.result) {
                this.errMessage = 'Existed: ' + JSON.stringify(data.result[0]);
              }
            } else {
              abbr = new Animal(data.result.st, data.result.dyn, data.result._id, data.result.status, data.result.action, data.result.newdyn);
              this.added.emit(abbr);
              this.clear();
            }
          },
          (err) => { this.errMessage = `Oops, server error: ${err}`; }
        );

    }
  }

  onDuplicate(item) {
    this.toastr.warning(`You have entered '${item}' more than once.`);
  }

}
```

When I have @Input expansionType defined, the line 
`this.added.emit(abbr);` is not emitting any events. However, once I got all expansionType commented, the emit works.

**Comment by zoechi** [comment]
dup of #5415

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166487.
------------------------------------------------------------------------------------------------------------


[[a3e0ce7a989943da9d71ab2fffb9baae2595f295-673073787]]

**Comment by vicb** [comment]
closing as duplicate

relates to #11606
