### ISSUE TITLE
Hide and Show div within the template

### ISSUE THREAD

**Issue by yogeshhub** [angular/angular#7196]
Hi,

I have some clarification about hide and show divs in angular 2.

**Comment by zoechi** [comment]
http://stackoverflow.com/questions/30744882/angular2-hidden-ignores

GitHub issues are for bug reports and feature requests. Please use other channels like StackOverflow, Gitter, Google Groups, ... for support questions.

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166518.
------------------------------------------------------------------------------------------------------------


[[c7322fde78ff83298f6a9ed65772d8d9dcf2c7da-673073935]]

**Comment by michalstepien** [comment]
Please close.

**Comment by yogeshhub** [comment]
I am very sorry about this kind of questions here...
