### ISSUE TITLE
When two components have the same class name (for instance after minification with mangling), the first component is rendered with the template of the second component.

### ISSUE THREAD

**Issue by stefanocke** [angular/angular#7199]
See here:

http://plnkr.co/edit/sKkTPTraGIP2BcLWzEQU?p=preview

It is a situation that occurs after minification with mangling, but I tried to reproduce without minification by using the same class name for both components  (since I don't know how to easily provide a minified example in Plunkr). Mangling will typically convert all class names to something like "a".
As you can see, both components are rendered with the template of Component2, unless you switch back to beta.0.

I have found several other issues about minification, but not any open one that is exactly the same as this.
https://github.com/angular/angular/pull/6397 mentions there might be name collisions in TemplateCompiler.

**Comment by antonybudianto** [comment]
I've reported this twice, #6760 and #6366, and the issue still persists, and yes, I don't bundle/package my angular2-polyfills, I put it in the script tag as recommended, but still didn't work unless I disable `mangle` option when uglifying.

**Comment by stefanocke** [comment]
@antonybudianto  Thank you. However, I did not get the exception you reported. I just have the issue with the wrong template. So I just wanted to make sure that one is not mixed with other issues related to mangling...

**Comment by antonybudianto** [comment]
the point is uglification broken since **beta.1**, no matter how many kind of issues it caused, let's hope this can be fixed soon

**Comment by antonybudianto** [comment]
looks like it'll get resolved in [here](https://github.com/angular/angular/issues/6380)

**Comment by stefanocke** [comment]
Sorry, but I think such speculations just increase the probebility that this will be marked as duplicate and that the remaining issues don't tell the whole story. As far as I can see, #6380 is a different story.

**Comment by IgorMinar** [comment]
I don't think that his is realted to #6380. It's more likely that this is a dupe of #7306.

**Comment by stefanocke** [comment]
Right. #7306 is a duplicate of this one. The example there is basically the same as here.

**Comment by DzmitryShylovich** [comment]
is this still an issue after final?

**Comment by stefanocke** [comment]
The duplicate #7306 is fixed. So this one is fixed as well. Verified with this plunkr: http://plnkr.co/edit/pPdWRdt8Ap46YeTs1cUw?p=preview
