### ISSUE TITLE
Angular2 beta.6 issue with tsc: Cannot find module "angular2/core"

### ISSUE THREAD

**Issue by Futourism** [angular/angular#7200]
Hello,

First, congrats for the work made with Ng2.

I'm a user of the brand new framework but I've already problems bootstrapping a simple component, and I open this issue since I wasn't able to find a solution with the previous issues.

my simple fileTree is like that (I don't list all the files):
- tsconfig.json
- package.json
- bower.json
- [bower_components]
- [node_modules]
- [components]
- - [table]
- - - _contact-manager.ts

the content of **tsconfig.json** is:

> {
>     "compilerOptions": {
>         "target": "ES5",
>         "module": "system",
>         "sourceMap": true,
>         "experimentalDecorators": true,
>         "emitDecoratorMetadata": true,
>         "watch": false,
>         "removeComments": true
>     },
>     "exclude": [
>         "bower_components",
>         "node_modules",
>         "typings"
>     ],
>     "bundles": {
>         "components": {
>             "files": ["components/**/*.ts"],
>             "config": {
>                 "declaration": true,
>                 "outDir": "./",
>                 "minify": true,
>                 "sourceMap": true
>             }
>         }
>     }
> }

... the excluded folders are actually more, and the "bundles" property is a config part for the NPM module "tsproject" that I use in Gulp to compile the ts files.

the code in my **_contact-manager.ts** file is:

> ///<reference path="../../node_modules/angular2/typings/browser.d.ts"/>
> import {Component, View} from 'angular2/core';
> import {bootstrap} from 'angular2/platform/browser';
> 
> @Component({
>     selector:'contact-manager'
> })
> @View({
>     template:'&lt;h1&gt;Welcome to {{title}}&lt;/h1&gt;'
> })
> export class ContactManager { 
>     title:string;
> 
>     constructor(){
>         this.title = "Contact Manager";
>     }
> }
> 
> bootstrap(ContactManager)
>     .then(app => {
>         console.log('Bootstrap Successful');
>     }, err => {
>         console.error(err);
>     });

... fact is: when I simply run "tsc" (but even when I try to compile the ts file with gulp and tsproject) I get the errors 
_components/table/_contact-manager.ts(2,31): error TS2307: Cannot find module 'an
gular2/core'.
components/table/_contact-manager.ts(3,25): error TS2307: Cannot find module 'an
gular2/platform/browser'._

... what's wrong?
Is there a configuration to setup for SystemJS too to be able to resolve the paths?
Also is browser.d.ts a good replacement for the previous angular2.d.ts?

Thanks and best regards!
Stefano

**Comment by ericmdantas** [comment]
Hello, @Futourism.

Do you have `/// <reference path="path/to/your/node_modules/angular2/typings/browser.d.ts"` set on the top of the main file of your app?

**Comment by Futourism** [comment]
Hello @

**Comment by Futourism** [comment]
Hello @ericmdantas 

Thanks for the reply.

the reference is on top of _contact-manager.ts that is the only ts file in all the project.

I get the error just running "tsc" or "gulp typescripts" where the typescripts task is like:

> gulp.task("typescripts", function () {
>     return tsproject.src("./")
>         .pipe(gulp.dest("./public/js/"));
> });

in the web page once I run it before including the resolved js file from the ts I've included SystemJS, jQuery, Foundation and Angular2 (polyfills, main and router) in this order.

Must be said that in the tsconfig.json file before I used "common" as the module instead of "config" and I'd much more errors but not import errors.

**Comment by ericmdantas** [comment]
When you don't bundle the app, does it work?

**Comment by Futourism** [comment]
A progress!
I tried changing the tsconfig.json "module" property back to "commonjs", I ran "tsc" (so not using gulp with tsproject that actually I would like to use to bundle everything) and no errors showed up, and I've my _contact-manager.js compiled file in the same folder of the .ts

If I copy the compiled file, link it to the page after the inclusion of systemjs/angular2 and I try the page I get the error:

> Uncaught ReferenceError: require is not defined(anonymous function) @ _contact-manager.ts:2

**Comment by ericmdantas** [comment]
hmm.. do you have a repo with that?

**Comment by Futourism** [comment]
I can upload all the project in minutes, I'll post the link once uploaded.

Thank you a lot @ericmdantas

**Comment by ericmdantas** [comment]
Alright :+1:

**Comment by ericmdantas** [comment]
Also, since this doesn't seem a bug with the framework itself, could you please close the issue and we can carry on the gitter chat? https://gitter.im/angular/angular

**Comment by Futourism** [comment]
Sure!

Done with the upload, the repository is https://github.com/Futourism/test2.git

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166542.
------------------------------------------------------------------------------------------------------------


[[9b3eda040f6b772efe1a945e54528bb605b1ad8a-673074163]]

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166536.
------------------------------------------------------------------------------------------------------------


[[119775084ed1196992b2f600f5209e2488d37f4c-673074157]]

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166532.
------------------------------------------------------------------------------------------------------------


[[0a1ddc5189be345e4583642648e7547d1560b0d2-673074148]]

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166534.
------------------------------------------------------------------------------------------------------------


[[4486bdc06840195a450221659f41c45153299990-673074150]]

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166545.
------------------------------------------------------------------------------------------------------------


[[44156a720378c7e2fec0518246d497d632762c10-673074168]]

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166551.
------------------------------------------------------------------------------------------------------------


[[7dabbe175822693e154ec3f966b634e07eca63a7-673074173]]

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166546.
------------------------------------------------------------------------------------------------------------


[[5b8c967a9e9d00f87219fc695aa1e334f5f1266e-673074169]]

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166552.
------------------------------------------------------------------------------------------------------------


[[20d22d44d7757ba0c8b9c537943d454acd1b2f99-673074176]]

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166540.
------------------------------------------------------------------------------------------------------------


[[99d5d411f9dcab10b8742c7a76938b62dbcd8068-673074159]]

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166537.
------------------------------------------------------------------------------------------------------------


[[6e03db1db0d1e9a7ade4d7aad732df796b1edb46-673074156]]

**Comment by NChandrasekar** [comment]
Hi,
Make sure the angular 2 dependencies imported into node_modules directory. In app.component.ts file write the 'import { component } from 'angular2/core';' line. This should be worked.
