### ISSUE TITLE
Try use phantom to render file html with angular 1.3, but show err

### ISSUE THREAD

**Issue by nicholasess** [angular/angular#7205]
Error: [$injector:modulerr] Failed to instantiate module App due to: [$injector:nomod] 
Module 'App' is not available! You either misspelled the module name or forgot to load it. 
If registering a module ensure that you specify the dependencies as the second argument. 
http://errors.angularjs.org/1.3.0/$injector/nomod?p0=App 
http://br.welearnit.com/angular/angular.js:1799:71 
ensure@http://br.welearnit.com/angular/angular.js:1721:45 
module@http://br.welearnit.com/angular/angular.js:1795:20 
http://br.welearnit.com/angular/angular.js:4064:35 
forEach@http://br.welearnit.com/angular/angular.js:335:24 
loadModules@http://br.welearnit.com/angular/angular.js:4048:12 
createInjector@http://br.welearnit.com/angular/angular.js:3974:22 
doBootstrap@http://br.welearnit.com/angular/angular.js:1484:34 
bootstrap@http://br.welearnit.com/angular/angular.js:1505:23 
angularInit@http://br.welearnit.com/angular/angular.js:1399:14 
http://br.welearnit.com/angular/angular.js:25579:16 
trigger@http://br.welearnit.com/angular/angular.js:2742:9 
eventHandler@http://br.welearnit.com/angular/angular.js:3013:25 
http://errors.angularjs.org/1.3.0/$injector/modulerr?p0=App&p1=%5B%24injector%3Anomod%5D%20Module%20'App'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.3.0%2F%24injector%2Fnomod%3Fp0%3DApp%0Ahttp%3A%2F%2Fbr.welearnit.com%2Fangular%2Fangular.js%3A1799%3A71%0Aensure%40http%3A%2F%2Fbr.welearnit.com%2Fangular%2Fangular.js%3A1721%3A45%0Amodule%40http%3A%2F%2Fbr.welearnit.com%2Fangular%2Fangular.js%3A1795%3A20%0Ahttp%3A%2F%2Fbr.welearnit.com%2Fangular%2Fangular.js%3A4064%3A35%0AforEach%40http%3A%2F%2Fbr.welearnit.com%2Fangular%2Fangular.js%3A335%3A24%0AloadModules%40http%3A%2F%2Fbr.welearnit.com%2Fangular%2Fangular.js%3A4048%3A12%0AcreateInjector%40http%3A%2F%2Fbr.welearnit.com%2Fangular%2Fangular.js%3A3974%3A22%0AdoBootstrap%40http%3A%2F%2Fbr.welearnit.com%2Fangular%2Fangular.js%3A1484%3A34%0Abootstrap%40http%3A%2F%2Fbr.welearnit.com%2Fangular%2Fangular.js%3A1505%3A23%0AangularInit%40http%3A%2F%2Fbr.welearnit.com%2Fangular%2Fangular.js%3A1399%3A14%0Ahttp%3A%2F%2Fbr.welearnit.com%2Fangular%2Fangular.js%3A25579%3A16%0Atrigger%40http%3A%2F%2Fbr.welearnit.com%2Fangular%2Fangular.js%3A2742%3A9%0AeventHandler%40http%3A%2F%2Fbr.welearnit.com%2Fangular%2Fangular.js%3A3013%3A25 http://br.welearnit.com/angular/angular.js:4088
http://br.welearnit.com/angular/angular.js:335 in forEach 
http://br.welearnit.com/angular/angular.js:4048 in loadModules 
http://br.welearnit.com/angular/angular.js:3974 in createInjector 
http://br.welearnit.com/angular/angular.js:1484 in doBootstrap 
http://br.welearnit.com/angular/angular.js:1505 in bootstrap 
http://br.welearnit.com/angular/angular.js:1399 in angularInit 
http://br.welearnit.com/angular/angular.js:25579 
http://br.welearnit.com/angular/angular.js:2742 in trigger 
http://br.welearnit.com/angular/angular.js:3013 in eventHandler

The same err, show when i test application in yellowlab
http://yellowlab.tools/result/ec3w8uarf1/rule/jsErrors

Thanks

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166560.
------------------------------------------------------------------------------------------------------------


[[f30a8e103f67eac4b6eef4398719f94f24f0572a-673074315]]

**Comment by pkozlowski-opensource** [comment]
This repo is for Angular 2, Angular 1.x issues should go to https://github.com/angular/angular.js. Having said this it reads more like a user's error rather than a bug in a framework.
