### ISSUE TITLE
"Displaying Data" guide for Angular 2 is unusably broken.

### ISSUE THREAD

**Issue by DanielLangdon** [angular/angular#7206]
I'm trying to teach myself to use this new Angular 2 framework.

I read over the "5 Minute Introduction", which was okay, and then the "Angular 2 Cheat Sheet", which seemed out of place given that the reader presumably doesn't know how anything on the Cheat Sheet fits into Angular 2.

I then went on to the "Displaying Data" tutorial (https://angular.io/docs/js/latest/guide/displaying-data.html).  This is just uselessly awful.  I couldn't get any of the code to run.  It tells me to start by creating an HTML page with "<display></display>".  Okay, first of all, that's a *fragment* of an HTML page.  It doesn't give any instructions about how to reference required Javascript/Typescript.  I got to the part where it says "Reload and you've got your list of friends!" and I realized that I hadn't yet run anything, nor did I have any idea how to make it work apart from trying to reference the correct files.  I re-read the preceeding part of the document several times and I can't make heads or tails out of this "basic" example.

All I can get is a message that says "angular is not defined"

Oh, and was I supposed to make that part of the package that I set up with npm in the "5 Minute Tutorial", or is it something else.  It's completely incoherent.

I hate to be a squeaky wheel, but I'm not able to learn Angular 2 from your documentation.  However, I would be happy to help with any more feedback to help make this better.

**Comment by zoechi** [comment]
I don't use TS (I use Dart)  but I think this is valuable feedback. Documentation issues should be filed in https://github.com/angular/angular.io/issues instead though.

**Comment by steinsag** [comment]
I believe the writers of the docs have some kind of reading sequence in mind. After completing the 5 minutes quick start, you should head over to the more lengthy [tutorial](https://angular.io/docs/ts/latest/tutorial/). Everything under "Developer Guides" basically extends this tutorial. So without the tutorial, you are lost.

**Comment by DanielLangdon** [comment]
Okay, I think I see what the problem is.  I had clicked on the "tutorial", but when I clicked to change from Javascript to Typescript, it doesn't have this particular document in Javascript and the next one is "Displaying Data."

I think that either the "tutorial" is only available in Typescript, or there is a bug in the web site that prevents the tutorial from displaying when Javascript is selected.

**Comment by zoechi** [comment]
Switching between TS/JS/Dart doesn't show the "same" document, no matter if it exists or not.

**Comment by PascalPrecht** [comment]
@DanielLangdon hi, I'm on the docs team. If you can't see a chapter for a certain language, then this chapter likely doesn't exist in that language yet.

**Comment by wardbell** [comment]
Yes ... this is a problem and we need to address it more effectively. TypeScript is the language in which we *start* to explain things. Our intention is to offer the same material in JS and Dart. But we're way behind on that effort with most of our efforts concentrated on first coverage of Angular 2 features.

For the moment, that obliges ES5 JS and Dart developers to switch to the TS language track for most content.

I wish we could just throw a switch and the TS content is instantly available as ES5 and Dart. Unfortunately, translation isn't automatic. We are open to suggestions for improvement ***in the short term**.

Longer term, we will have language parity in the documentation.

**Comment by wardbell** [comment]
@zoechi  That language switch at the top doesn't work the way it should. I'd welcome suggestions on how to improve it when content does not exist in JS/Dart.

**Comment by DanielLangdon** [comment]
@wardbell, I would think that a simply message indicating the the selected document isn't available in the selected language would be plenty sufficient.

**Comment by zoechi** [comment]
I also think that a message that the content is not available in that language would suffice. The navigation at the top and left is still available. This allows to switch to the previous or just another language or continue elsewhere.

**Comment by DanielLangdon** [comment]
As before, the issue to me is that I tried to switch language, some of the content wasn't available in ES5, and so what I saw was an incomprehensible mess like a Harry Potter book that was missing pages with no indication that the pages were missing.

**Comment by wardbell** [comment]
This is really an issue that belongs on the `angular.io` repo.

FWIW, we've made it much easier to switch language tracks in the documentation over there without getting lost. 

I recommend closing this issue here ... and reopening over there if someone has a substantive suggestion for improvement.

**Comment by zoechi** [comment]
Switching language worked fine for me when I last tried a few days ago.

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166556.
------------------------------------------------------------------------------------------------------------


[[90276f86432930ef9f37bf202ce5a25920d6659e-673074290]]

**Comment by pkozlowski-opensource** [comment]
> This is really an issue that belongs on the angular.io repo.

Exactly
