### ISSUE TITLE
debug_node.dart needs docs

### ISSUE THREAD

**Issue by trinarytree** [angular/angular#7211]
Right now it has none.  Here are a few points that need clarification:
- What is the difference is between a `DebugNode` and a `DebugElement`?
- What is the difference between `query`, `queryAll`, and `queryAllNodes`?
- Do these functions include the root in the search?  I would have thought so, yet after trying it, I think they don't.  Why do I have to write a test just to find out basic info like that?

**Comment by pkozlowski-opensource** [comment]
Obsolete as Dart-specific.
