### ISSUE TITLE
@Input doesn't support typed input variables

### ISSUE THREAD

**Issue by cheungtitus** [angular/angular#7214]
Playing around with Tour of Hero's app/hero-detail.component.ts on the different types of ways we can declare attribute directive inputs, I notice it'd work only if I declare it as Any, String, or nothing but failed to work if I declare it as Hero.

So here's the exact code shown on [https://angular.io/docs/ts/latest/tutorial/toh-pt3.html](url)
```
    import {Component} from 'angular2/core';
    import {Hero} from './hero';
    @Component({
      selector: 'my-hero-detail',
      template: `
        <div *ngIf="hero">
          <h2>{{hero.name}} details!</h2>
          <div><label>id: </label>{{hero.id}}</div>
          <div>
            <label>name: </label>
            <input [(ngModel)]="hero.name" placeholder="name"/>
          </div>
        </div>
      `,
      inputs: ['hero']
    })
    export class HeroDetailComponent {
      hero: Hero;
    }
```

Now check this out, if I try the @Input() decorator way, I have 3 additional approaches of achieving the same thing, which is to pass in an object of type Hero.  Note that I have 2 sections of the template, depending on whether the variable 'hero' or 'myHero' is set.  I need to do this because the @Input decorator allows us to assign the property (ie hero) set to another variable (ie myHero).
```
import {Component, Input} from 'angular2/core';
import {Hero} from './Hero'

@Component({
    selector: 'my-hero-details',
    // Approach 4
    inputs:  ['hero'],
    template: `<div *ngIf="hero">\n\
                        <h2>{{hero.name}} details</h2>\n\
                        <div><label>id:  </label>{{hero.id}}</div>\n\
                        <div><label>name:  </label><input [(ngModel)]="hero.name" placeholder="name"></div>
                </div>\n\
                <div *ngIf="myHero">\n\
                        <h2>{{myHero.name}} details</h2>\n\
                        <div><label>id:  </label>{{myHero.id}}</div>\n\
                        <div><label>name:  </label><input [(ngModel)]="myHero.name" placeholder="name"></div>
                </div>
    `
})
export class HeroDetailComponent {
    // Approach 4
    public hero:  Hero;
    
    // Approach 1
//    @Input() hero: Any;
    
    // Approach 2
//        @Input('hero') myHero: Any;
    
    // Approach 3
//        private myHero: Hero;
//        @Input() set hero(heroPassedIn: Any) {
//            this.myHero = heroPassedIn;
//        }
}
```

Try each of the approach one by one by commenting and uncommenting the appropriate lines.  You'd see that they all work.  If I remove the type 'Any', they all work as well.

But notice I have declared them all with type 'Any'?  This is because if I declare them to type 'Hero', it won't work.  In Chrome, I get the following printed in the console.
`Uncaught SyntaxError: Unexpected token export`

In fact the most absurd thing is they'd work even if I declare the type as String!

**Comment by ericmartinezr** [comment]
Does it work if you lowercase the filename in your import? 
`import {Hero} from './Hero'` should be `import {Hero} from './hero'`

**Comment by cheungtitus** [comment]
@ericmartinezr Just tried that but same result.  In fact I notice some of the files are already using `import {Hero} from './hero'` instead of `import {Hero} from './Hero'`

What I did was renamed the file Hero.ts to hero.ts, deleted the Hero.js and Hero.js.map files that were generated, and updated the import line to reference the lowercase file name.  Interesting observation is that the files Hero.js and Hero.js.map were generated again with the capital 'H'.

**Comment by zoechi** [comment]
I don't use TS and I'm not sure if it makes a difference, but `any` seems to be lowercase everywhere in TS. 
`\n\` on the line endings in the template string seems quite weird to me as well.

**Comment by cheungtitus** [comment]
@zoechi "any" or "Any" both works and isn't the problem.  Problem is when I use the actual type the variable is supposed to hold which is "Hero".  Understand what you mean by the '\n\' line ending.  It's added by Netbeans but is working fine.

**Comment by zoechi** [comment]
It can't parse the source and fails because it doesn't expect `export` here
```
`})
export class HeroDetailComponent {
```
therefore it's likely an error just before that

**Comment by zoechi** [comment]
@cheungtitus I just found the error in this answer http://stackoverflow.com/a/34539845/217408 because I run into it in a similar situation.

**Comment by cheungtitus** [comment]
@zoechi Thanks.  I tested it by changing from `packages: {'app': {defaultExtension: 'ts'}} ` to `packages: {'app': {defaultExtension: 'js'}}` and it works.

**Comment by zoechi** [comment]
@cheungtitus Can this be closed?
