### ISSUE TITLE
Angular2 routing removes hash problem

### ISSUE THREAD

**Issue by damienbod** [angular/angular#7215]
I'm using OpenId with Angular2 and receive to token payload in the hash part of the URL callback. 

My problem is that the angular2 router removes the hash part before I can use it. How do I configure the angular2 app to keep the hash or use it inside my service?

/Authorized#..... required.

Angular2 resets this to 
 
/Authorized

Or how can use the hash part of the callback in angular2?

Greetings Damien

**Comment by zoechi** [comment]
dup of #6595 ?

**Comment by damienbod** [comment]
Similar, but I think this is really important, because without this, OpenId security cannot be implemented without reverting back to Javascript, we'd have to hack the security from the beginning...

**Comment by jameskeongchen** [comment]
also having issues with this and OpenID; any updates on the best way to get the #...token_id= etc

**Comment by theely** [comment]
A related issue is the OAuth integration. After a successful sign-in the third party website will redirect the user to the webpage that initiated the sing-in process adding to the request a state token. Some times the token is passed as query param some times as hash fragment.
Because Angular2 is currently removing the hash fragment the sing-in process can not be completed.
For instance the usage of Google Identity Toolkit in association with Angular2 in currently broken, I have posted a issue here: http://stackoverflow.com/questions/36885167/gitk-with-angular-2-has-issues-on-redirects-using-fragments-hash if anybody knows a temporary workaround please add a note.

**Comment by damienbod** [comment]
If you implement the OAuth or the OpenID connect logic in Angular2 outside the routing paths, it will work. (Or use ng2-ui-router)

I have a working example here:
https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/tree/master/src/Angular2Client

Greetings Damien

**Comment by theely** [comment]
Yep, thanks that works like a charm 👍 
However its quite an hack as the login component was meant to be embedded in the root component therefor it can't really be outside the routing paths.

**Comment by damienbod** [comment]
Hi @theely 

Cool, nice that it works, I agree, its quick a hack. Maybe ng2-ui-router should be considered, this has also another major advantage, diagnosis when the routes are incorrect.

Greetings Damien

**Comment by IgorMinar** [comment]
This issue was made obsolete by router v3: https://angularjs.blogspot.com/2016/06/improvements-coming-for-routing-in.html

If you believe this is not the case, please file a new issue updating the description to router v3. thank you!

**Comment by BenDevelopment** [comment]
I still can get hash parameters with Angular2.0.0.
Can someone give me a example?
I'm trying to connect with facebook which redirect to my angular2 app with this url:
`http://localhost:4200/login/?#access_token=my_access_token&expires_in=5181634&code=my_code`
The part after `http://localhost:4200/login` is removed before I can extract it.
How can I extract the parameters before that?

**Comment by BenDevelopment** [comment]
I've found the solution here:
http://stackoverflow.com/questions/39668916/angular2-get-url-query-parameters/40058721#40058721

Imports:

```
import { Router, NavigationCancel } from '@angular/router';
import { URLSearchParams, } from '@angular/http';
```
Constructor:

```
 constructor(public router: Router) {
    router.events.subscribe(s => {
      if (s instanceof NavigationCancel) {
        let params = new URLSearchParams(s.url.split('#')[1]);
        let access_token = params.get('access_token');
        let code = params.get('code');
      }
    });
  }
```

**Comment by doniaZaela** [comment]
This solution works only with  pathlocationstrategy in Angular2. Did anybody else find a solution for those using hashlocationstrategy in Angular 2?

**Comment by doniaZaela** [comment]
@damienbod your working solution link is broken, can you please correct it?

**Comment by vikramjangra783** [comment]
You can use preserveFragment: true in navigation
