### ISSUE TITLE
Add the ability to pass a reviver function to Http Response's Json method

### ISSUE THREAD

**Issue by TFleury** [angular/angular#7217]
`Json.Parse` method supports passing a reviver function. It's especially useful to correctly handle date parsing from JSON.

**Comment by zoechi** [comment]
I guess this should filed in the https://github.com/angular/http/issues repo

**Comment by TFleury** [comment]
Sorry, I didn't know there was a distinct repo for HTTP module.
I reopened it at the right place.

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166603.
------------------------------------------------------------------------------------------------------------


[[fde305debbe114496b44cca0ddc9382418448b0f-673074604]]

**Comment by fvilers** [comment]
@TFleury, the http repository doesn't exist (anymore?), do you know if there's a way to use a reviver with the json method?

**Comment by fvilers** [comment]
This what I'm doing right now. I tried to extend the Response object to have a `jsonWithReviver` method but without success.
