### ISSUE TITLE
External libs and angular patching

### ISSUE THREAD

**Issue by brandom** [angular/angular#7218]
When importing [plotly.js](https://github.com/plotly/plotly.js) change detection breaks. Removing this lib or placing it before `angular-polyfills.js` fixes the issue.

This [Plunker](https://plnkr.co/edit/I7w1ur6VgGek0z5jnsVR?p=preview) provides a simple example.

This kind of issue may or may not be able to be fixed in angular and could cause major confusion regarding expected change detection behavior.

If there is no way to prevent an external lib from clobbering angular patches would it be possible to provide a warning in development mode? Any thoughts or feedback would be appreciated.

**Comment by robwormald** [comment]
spoke with @brandom a bit about this on gitter. My guess would be it's plotly's use of the es6-promise.polyfill() call here - https://github.com/plotly/plotly.js/blob/master/src/plotly.js#L22

Moving zone.js after plotly presumably re-patches it, but this is counter to our advice about including polyfills first. 

The *right* answer I think is to encourage third parties to not import polyfills like this directly, as even outside of angular-land it'll enforce a dependency that might not be necessary - I suspect plotly is likely just using the Promise constructor as normal...

cc @mhevery - any ideas? Can we maybe PR to es6-promise to have it not polyfill twice?

**Comment by mhevery** [comment]
I think this will be solved with the latest Zone rewrite:
https://github.com/angular/zone.js/pull/231

**Comment by frederikaalund** [comment]
I just wanted to add that this is still an issue in RC5. I still have to import plotly.js before the polyfills. Otherwise, `NgZone.assertInAngularZone()` fails even in `ngOnInit` of the root component.

**Comment by rolandjitsu** [comment]
If anyone needs this fix, you should vote on [#955](https://github.com/plotly/plotly.js/issues/955).

**Comment by vicb** [comment]
fix is on the plotly.js side (see previous comment)
