### ISSUE TITLE
RouterLink inside component does not work

### ISSUE THREAD

**Issue by linvi** [angular/angular#7222]
Hello,

Before posting I have read multiple issues regarding the subject but I could not find what I wanted.
My issue is that if I have `[RouterLink]` that are located inside a component displayed by the `router-outlet` these links change the URL of the page but does not update the UI.

This [plunker](http://plnkr.co/edit/Xg592nVJZeT4IjXsL7vO) is the exact copy of what has been provided as an example with 1 minor change to `app/hero-detail.component.html`.

I have change the `Go Back` button to a link that is `<a [routerLink]="['Dashboard']">Go back</a>`.
Also in order to do this I added the `ROUTER_DIRECTIVES` and `ROUTER_PROVIDERS` to the file `app/hero-detail.component.ts` :+1: 

``` ts
@Component({
  selector: 'my-hero-detail',
  templateUrl: 'app/hero-detail.component.html',
  styleUrls: ['app/hero-detail.component.css'],
  inputs: ['hero'],
  directives: [ROUTER_DIRECTIVES],
  providers: [ROUTER_PROVIDERS]
})
```

As you can note if you select the details page of any hero, the `Go back` link does not work anymore.

Thank you for your help.

**Comment by brandonroberts** [comment]
There is an error in the example plunker. In `app/hero-detail.component.ts` there is `providers: [ROUTER_PROVIDERS]` which shouldn't be there. If you remove it, the `Go Back` link works as intended.

**Comment by linvi** [comment]
Thank you for your help. It does work.

> There is an error in the example plunker

Could you please explain the reason why `[ROUTER_PROVIDERS]` needs to be removed? Is it wrong to add it, or is it a bug of the current version of Angular?

If it is wrong to add the provider, could you please explain why?

**Comment by spock123** [comment]
Hi @linvi , in my opinion the following happens:

- when you declare ROUTER_PROVIDERS as providers in your component, what happens is that you instantiate new instances of the ROUTER_PROVIDERS in your component and child components.

- therefore, the routerLink directives you use in your template, will use the new instances of the ROUTER_PROVIDERS. In those instances, you have no configuration of routes etc. Those are in the instances you added to your bootstrap (hopefully).

The providers attribute for the @Component selector is used to instantiate new singletons for the component (and children).

Hope this makes sense

Cheers

**Comment by PascalPrecht** [comment]
@linvi as @spock123 explained, you're introducing providers for a child injector which is not what you want to do at this point. If you want to read more about dependency injection, you might want to check out this article: http://blog.thoughtram.io/angular/2015/05/18/dependency-injection-in-angular-2.html

Can we close this issue?

**Comment by linvi** [comment]
Yes, thank you all of you for your help. This is a bit more clear now. I am still in the process of learning angular 2, so I hope it will make sense in the coming days!
