### ISSUE TITLE
Angular 2 routing doesn't work in firefox in case of special character %2F

### ISSUE THREAD

**Issue by Somiks** [angular/angular#7224]
My link https://domain1.lv/static/loan/#/credit-details/HEAD-RLC-161%2F2013 doesn't work in firefox (after refreshing component isn't running). In chrome it works fine. Without %2F refreshing works properly.

**Comment by Somiks** [comment]
I found solution. I just updated to newer version. Now all works.

**Comment by zoechi** [comment]
Newer version of Angular or of the browser?

**Comment by Somiks** [comment]
@zoechi ups. i forgot to say. it was firefox old version
