### ISSUE TITLE
[IE-11] Performance : It take almost 5 seconds to display only 100 item lists.

### ISSUE THREAD

**Issue by rizvankukad** [angular/angular#7225]
Hi,

Today i made performance test in different browsers, i found that there is slowness issue in IE-11. Refer -> http://plnkr.co/edit/1fK44bFkDqxcVJovtAdG?p=preview

**Comment by CaptainCodeman** [comment]
Check the console:
`Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.`

I believe that dev mode does some extra change detection operations to warn if things have changed unexpectedly so it isn't really valid to use for any performance testing. Try adding `ng.core.enableProdMode();` and see if that makes a difference.

**Comment by rizvankukad** [comment]
@CaptainCodeman Tested both cases. No change in performance even with trackBy.

Thanks.

**Comment by jth0024** [comment]
I experienced this problem as well. I added a call to `enableProdMode()` and this fixed my issue.

**Comment by rizvankukad** [comment]
Yep working for me as well. Closing this issue for now.
