### ISSUE TITLE
Dynamic ng-content position

### ISSUE THREAD

**Issue by Andy1605** [angular/angular#7226]
Hi there,

I have the following component template on which i cannot change anything because of defined css selectors from a third party framework.

```
template: `<label class="classA">
  <input type="checkbox" />
  <span class="classB"></span>
  <ng-content></ng-content>
</label>`
```

Now i was wondering if i could make the position of ng-content based on conditions, like so:

```
template: `<label class="classA">
  <ng-content *ngIf="labelPos == 'left'" ></ng-content>
  <input type="checkbox" />
  <span class="classB"></span>
  <ng-content *ngIf="labelPos != 'left'" ></ng-content>
</label>`
```

Which does not work at all! It doesn't show anything since it always selects the second ng-content even though the condition doesn't even match!

**Comment by ericmartinezr** [comment]
You can use `ng-content select="..."` as in [here](https://github.com/angular/angular/blob/master/modules/angular2/test/core/linker/projection_integration_spec.ts#L659).

Please move your questions to stackoverflow, gitter's chatroom and similars. Github is to report issues, bugs, and such. Thanks.

**Comment by Andy1605** [comment]
Hmm... it is an issue to me, since it does not what one would expect! I cannot use select="" either since it is a simple label text which gets inserted by the user!

**Comment by ericmartinezr** [comment]
It's working for me http://plnkr.co/edit/B18l1fypgtSUL8MBJrqc?p=preview . To be honest I don't see the complexity on your issue. You should create a plnkr showing your case.

By the way, I have to rephrase something...

Github is to report issues *to the framework* (asking for features is a different thing), bugs, and such

**Comment by zoechi** [comment]
```
template: `<label class="classA">
  <div  *ngIf="labelPos == 'left'">
    <ng-content ></ng-content>
  </div>
  <input type="checkbox" />
  <span class="classB"></span>
  <div *ngIf="labelPos != 'left'">
    <ng-content  ></ng-content>
  </div>
</label>`
```

might work (not tried myself).

The `<ng-content>` doesn't seem to be added to the DOM at all and is only used internally by Angular. Using a wrapper element (doesn't have to be a `<div>` of course) probably makes it work as you expect.

**Comment by Andy1605** [comment]
@zoechi Unfortunately not. Tried that before.
@ericmartinezr The select rule doesn't apply for that issue. Since my content comes from the user of my component which is a plain text. By attribute the user selects if to print the label left or right.
`<ng-content select=".right" class="right" ></ng-content>` alone doesn't work at all!

But i will stop writing that here, since it is not an actual buggish issue.

**Comment by ericmartinezr** [comment]
@Andy1605 it's ok to continue the conversation, sorry if I sounded too rude. You're free to open a new issue asking for this as a feature since right now this is not a bug. This sounds to me as `select` should be bindable `select=".{{labelByTheUser}}"`, or `[select]="'.'+labelByTheUser"` or something like that (that's all I came up with right now)

**Comment by Andy1605** [comment]
Hmm... not quite, even though it would be a good feature, too.
I made a [Plunker ](https://plnkr.co/edit/BNUU28yO0ffT3H7JIpcL?p=preview)example to point out my intentions. My component is a blackbox to the user. He does not know anything about internal selectors and stuff. He simply controls the position of the label text by using the labelpos attribute.

**Comment by zoechi** [comment]
I see. I guess this is probably the only way you can do it https://plnkr.co/edit/CYtT9pG1sSFFXKfrwmPG?p=preview
