### ISSUE TITLE
[testing] Testing a form

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#7229]
Let's say we have a very simple model-driven form:

```TypeScript
@Component({..})
export class Register {

  login: Control;
  userForm: ControlGroup;

  constructor(fb: FormBuilder) {
    this.login = fb.control('', Validators.required);
    this.userForm = fb.group({
      login: this.login,
    });
  }
}
```

with a template:

```HTML
<form (ngSubmit)="register()" [ngFormModel]="userForm">
    <input id="login" ngControl="login">
</form>
```

The following unit test would come to mind:

```TypeScript
describe('Register Component', () => {

  let fixture: ComponentFixture;

  beforeEachProviders(() => []);

  beforeEach(injectAsync([TestComponentBuilder],
    (tcb: TestComponentBuilder) => tcb.createAsync(Register).then(f => fixture = f)
  ));

  it('should display a form to register', () => {

    // given a form
    let userForm = fixture.componentInstance.userForm;

    expect(userForm.valid).toBe(false);
    expect(userForm.find('login').getError('required')).toBe(true);

    // when adding values in the form
    let nativeElement = fixture.nativeElement;
    nativeElement.querySelector('input').value = 'Cédric';
    nativeElement.querySelector('input').dispatchEvent(new Event('input'));

    fixture.detectChanges();

    // then we should have a valid form, with no error
    expect(userForm.valid).toBe(true);
    expect(userForm.find('login').getError('required')).toBe(null);

  });

});
```

But the test will fail: after the `detectChanges()`, the form is still not valid.

I encountered this issue when I was writing my ebook with early alphas

The test is green with:

```TypeScript
// when adding values in the form
let login = fixture.debugElement.query(By.css('input'));
login.nativeElement.value = 'Cédric';
login.nativeElement.dispatchEvent(new Event('input'));
```

Looks like it works with `fixture.debugElement.query` but not with `fixture.nativeElement.querySelector`.

Is that normal?

cc @juliemr @mhevery

**Comment by binarious** [comment]
I'm using:
```
return tcb.createAsync(LoginComponent).then((fixture: any) => {
    // Getting the elements
    let compiled = fixture.debugElement.nativeElement;
    let username = compiled.querySelector('input[type="text"]');

    fixture.detectChanges();

    // Change value
    username.value = 'my username';

    // dispatch input event
    dispatchEvent(username, 'input');

    compiled.querySelector('button').click();
    expect(mockOAuthService.login).toHaveBeenCalled();
});
```
With username being a required control and `mockOAuthService.login` is just called when the form is valid. This test passes. I'm also using `dispatchEvent` from `import {dispatchEvent} from 'angular2/src/testing/utils';` - no other method worked for me (I'm still on beta3 though).

**Comment by cexbrayat** [comment]
@binarious That sadly doesn't fix it for me. Would have been surprising as it does pretty much the same thing under the hood, but that was worth a try, thanks for your answer :)

I had this issue from the first alphas to the last beta (beta.7).

**Comment by cexbrayat** [comment]
The test does work if I use:

```TypeScript
// when adding values in the form
let login = fixture.debugElement.query(By.css("input"));
login.nativeElement.value = "Cédric";
dispatchEvent(login.nativeElement, "input");
```

So the problem seems to be the use of `fixture.nativeElement.querySelector` versus `fixture.debugElement.query`. Is that normal?

**Comment by cexbrayat** [comment]
The test is green with: 

```TypeScript
// when adding values in the form
let login = fixture.debugElement.query(By.css('input'));
login.nativeElement.value = 'Cédric';
login.nativeElement.dispatchEvent(new Event('input'));
```

Looks like it works with `fixture.debugElement.query` but not with `fixture.nativeElement.querySelector`.
Is that normal?

**Comment by binarious** [comment]
I'd need to be `fixture.debugElement.nativeElement.querySelector` as far as I know.

**Comment by cexbrayat** [comment]
@binarious `nativeElement` is directly accessible on `ComponentFixture` (and is the same as `debugElement.nativeElement`)

**Comment by juliemr** [comment]
To follow up here - changing between querying by native `querySelector` and `query(By...)` should make no difference and doesn't make a difference when I try it locally.

An issue in general with testing form is that due to the use of observables, sometimes changes are done in asynchronous microtasks, and `detectChanges` is required in some places.. So it's difficult to use a synchronous test. https://github.com/angular/angular/pull/8301 will help with this by allowing a unit tests to wait for microtasks to complete.

In the meantime, here's a working incantation:

```js
  it('should display a form to register', async(() => {
    // This first detectChanges is necessary for forms t set themselves up.
    fixture.detectChanges();

    // given a form
    let userForm = fixture.componentInstance.userForm;

    expect(userForm.valid).toBe(false);
    expect(userForm.find('login').getError('required')).toBe(true);

    // when adding values in the form
    let login = fixture.debugElement.query(By.css('input'));
    login.nativeElement.value = 'Cédric';
    login.nativeElement.dispatchEvent(new Event('input'));

    fixture.detectChanges();

    // then we should have a valid form, with no error
    expect(userForm.valid).toBe(true);
    expect(userForm.find('login').getError('required')).toBe(null);
}));
```

**Comment by juliemr** [comment]
See https://github.com/juliemr/ng2-test-seed/blob/form3/src/app/form-component.ts and https://github.com/juliemr/ng2-test-seed/blob/form3/src/test/form-component_test.ts 

Some experimentation with various ways of testing forms. Note that whether the form is asynchronous or not depends on whether you use `ngFormBuilder`.

**Comment by cexbrayat** [comment]
The problem has indeed disappear between in beta.17.
Thanks @juliemr for taking the time to check and for the examples. I look forward to the new API of ComponentFixture!

**Comment by nioperas06** [comment]
@cexbrayat I know it's pretty off-topic but do you have resources for testing template driven forms?

**Comment by cexbrayat** [comment]
@nioperas06 I have several examples in my online training but I don't think I have public examples or articles, I'm sorry.

**Comment by nioperas06** [comment]
I just bought the Ninja Squad ebook. I hope to find my happiness inside. :smiley:
