### ISSUE TITLE
Tutorial docs need a typings reference for es6 Promises

### ISSUE THREAD

**Issue by brazenest** [angular/angular#7231]
The "Tour of Heroes" tutorial code uses the `tsconfig.json` from Quickstart, which targets ES5, but beginning at Part 4 it makes use of the Promises feature which was introduced in ES6 (aka ES2015). TypeScript compilers fail at this stage because the tutorial's code currently does not reference a typings file for the Promises feature.

As specified in the "Breaking Changes" section of the beta6 changelog, the top section of the `main.ts` file in Part 4 of the tutorial should begin with:
```
import {bootstrap}    from 'angular2/platform/browser';
///<reference path="node_modules/angular2/typings/browser.d.ts"/>
import {AppComponent} from './app.component';
```

**Comment by zoechi** [comment]
doc issues are managed over there in https://github.com/angular/angular.io/issues/

**Comment by aciccarello** [comment]
@brazenest, I've migrated your issue for you
