### ISSUE TITLE
"npm install" failing on source build

### ISSUE THREAD

**Issue by damiandennis** [angular/angular#7233]
Trying to build from source and npm is failing with "no such file or directory, chmod '/var/www/angular/node_modules/bower/node_modules/cardinal/node_modules/redeyed/node_modules/esprima/bin/esvalidate.js'"

running npm version 3.7.5
running node version 5.4.1
running in a vagrant box with ubuntu 14.04 installed
node installed using nvm 

following the guide below:
https://github.com/angular/angular/blob/master/DEVELOPER.md

**Comment by michalstepien** [comment]
Hi, please close.
