### ISSUE TITLE
What is the difference between “selectRootElement” and “createViewRoot” in AngularJS 2?

### ISSUE THREAD

**Issue by tonimora74** [angular/angular#7235]
in the "Renderer" section, the official documentation does not specify... "Not Yet Documented".

this is the oficial page: https://angular.io/docs/ts/latest/api/core/Renderer-class.html

**Comment by aciccarello** [comment]
What do you mean that it does not specify "Not Yet Documented"? This is what I see on the official page

![image](https://cloud.githubusercontent.com/assets/11273838/13253131/67cf82ea-da08-11e5-97ad-45635227fbb6.png)

I'd assume `selectRootElement(selector)` gets an element and `createElement(parentElm, name)` creates a sub element. At the bottom of the docs there is a link to the [source code](https://github.com/angular/angular/blob/2.0.0-beta.7/modules/angular2/src/core/render/api.ts#L14-L60) but it's an abstract class so there is no implementation. You can look at the [dom_renderer implementation](https://github.com/angular/angular/blob/2.0.0-beta.7/modules/angular2/src/platform/dom/dom_renderer.ts#L83) to get a better idea.

**Comment by tonimora74** [comment]
that is, to not know what it is?

**Comment by vicb** [comment]
obsolete
