### ISSUE TITLE
Control value won't update in a dynamic selectbox (or any other input)

### ISSUE THREAD

**Issue by IHateGlamour** [angular/angular#7237]
If values of a select box are defined dynamically(or after the form was created) the value of the control won't change. Description of the problem with a plunker example can be found [here](http://stackoverflow.com/questions/35579302/angular2-update-form-control-value/35579471)
In short, if you have a control bind to a selectbox like this:

```
<select ngControl="package">
    <option *ngFor="#package of packages | filterValueBy:package_type" [value]="package.ID">{{package.NAME}}</option>
  </select>
```
each time the filter will be applied, the value of the selectbox will change, but the value of the controller will not.

**Comment by ericmartinezr** [comment]
I think this will be fixed when @basvandenheuvel implements `reset()`. I'm guessing something like 
```
this.form.reset();
// or per field
this.form.selectField.reset();
```

**Comment by IHateGlamour** [comment]
The idea is that a selectbox(or other types of components) would update on various events, and the control should be always up to date, I don't think that you should be the one keeping it up to date, this could be the source of a lot of bugs. And it's not just about resetting the form or the fields.

**Comment by kara** [comment]
@IHateGlamour Select controls appear empty when their value cannot be matched to one of their option values. So when you change the option value list, the form control value no longer matches any of the options, and should be blank.  If you'd like to select a value from the list of new options when you change the list, you'll want to set the value programmatically when you change the list with `setValue` or `patchValue`.
