### ISSUE TITLE
feat(forms): easy way to access validation error objects

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular#7238]
An `ngControl` can have `errors`, when one or more of its validators fail. Say we have a control like this:

```
<input ngControl="name" #name="ngForm" minlength="3">
```

If I enter something into this input which doesn't satisfy the `minlength` validator, here's what `ngControl`'s `error` object might look like:

```
{
  minLength: {
    actualLength: 1,
    requiredLength: 3
  }
}
```

Now, if I want to display an error message accordingly, I can access the object using the `ngControl` reference:

```
<div *ngIf="name.errors">
  <p *ngIf="name.errors['minLength']">Way too short!</p>
</div>
```

However, if I want to access the information provided by that particular error, I have to walk down the entire property path, over and over again:

```
Actual: {{name.errors.minLength.actualLength}}, Required: {{name.errors.minLength.requiredLength}}
```

To be honest, I'm not sure if these properties are actually meant to be used, but if yes, maybe it would be nicer to find a way to access these properties easier.

**Comment by ericmartinezr** [comment]
@PascalPrecht I think a more appropriate way is to use `hasError` and `getError`

```
    <form [ngFormModel]="myForm">
      <input type="text" minlength="3" ngControl="myText" />
    </form>
    
    <div *ngIf="myText.hasError('minlength')">
      Rquired length : {{myText.getError('minlength').requiredLength}}
      <br />
      Actual length : {{myText.getError('minlength').actualLength}}
    </div>
```
This is slightly shorter than your original comment.

**Comment by PascalPrecht** [comment]
@ericmartinezr ah, didn't know this API exists! That's indeed cleaner :) thank you!

**Comment by PascalPrecht** [comment]
Closing this. If someone has an even better idea, please lemme know, I can also reopen then.

**Comment by ericmartinezr** [comment]
@PascalPrecht I think you need a proposal here

**Comment by PascalPrecht** [comment]
One thing I could think of also as a more general solution to other things, would be to allow local variable assignment in the template. So not just getting references a la `#foo="bar"` but also allowing variable creation + value assignment like `#errObj="myText.getError('minLength')"` and then one could do `errObj.foo`.

**Comment by PascalPrecht** [comment]
@ericmartinezr neither `hasError()` or `getError()` defined on my `ngControl` instance. Do you know when they've been introduced?

**Comment by PascalPrecht** [comment]
@ericmartinezr little update:

The reason why I don't have these APIs is because I don't do model-driven forms a the moment. 

`getError()` and `hasError()` are defined in `AbstractControl`. `NgControlName` doesn't extend this particular class, so it's missing. I think I'm gonna open another issue for that.

**Comment by ericmartinezr** [comment]
@PascalPrecht Oh, nice :+1:

**Comment by todoubaba** [comment]
@PascalPrecht NgControlName has `get control(): Control`.

**Comment by PascalPrecht** [comment]
Right but then I can also just call the properties directly as it doesn't
give any API benefits

**Comment by todoubaba** [comment]
As @ericmartinezr said, the template could be:
```html
  <form>
    <input type="text" ngControl="myText" minlength="5" #myText="ngForm">
    <div *ngIf="myText.control?.hasError('minlength')">
    Rquired length : {{myText.control.getError('minlength').requiredLength}}
    <br />
    Actual length : {{myText.control.getError('minlength').actualLength}}
    </div>
  </form>
```
See, http://plnkr.co/edit/GjK771LpW348RlJw7zvg?p=preview

**Comment by PascalPrecht** [comment]
Thank you that's even better.

However, Don't you also think that we should have at least the same experience no matter if we do template driven or model driven forms?

**Comment by todoubaba** [comment]
It's tedious to setup each field in template, it's better using a `FormFieldComponent` to take care the details, see `Form component for fields` in http://restlet.com/blog/2016/02/17/implementing-angular2-forms-beyond-basics-part-2/

**Comment by PascalPrecht** [comment]
I agree that it's not very nice we have to reference each control. Especially when using template-driven forms (which is a use case we want to support, so we should get this straight).

Your article uses model-driven forms too. I'm still trying to grok and improve template-driven forms.

**Comment by PascalPrecht** [comment]
@todoubaba found out that the `control` getter doesn't help either in case of template-driven forms https://github.com/angular/angular/issues/7255#issuecomment-189454280 <- FYI
