### ISSUE TITLE
Feature request: allow specifying extra providers on @Route

### ISSUE THREAD

**Issue by pavelgj** [angular/angular#7241]
Child routes doesn't work with `DynamicComponentLoader` so I'm unable to provide extra providers for a child route component.

It would be great to be able to specify extra providers right on the route:

```dart
@RouteConfig(const [
  const Route(
      path: '/foo/...',
      component: FooComponent,
      name: 'Foo',
      providers: const [const Provider(MyService, useFactory: myFactory)]),
])
```

This is useful if I a child component relies on provider which is not available until the parent provides it.

**Comment by btford** [comment]
How urgent is this? And should it be on one of our hotlists?

Thanks!

**Comment by pavelgj** [comment]
There are workarounds (ugly they may be), so it's not currently blocking anything (at least for us). It seems like a powerful and useful feature... angular.dart has it and IIRC angular.js too. I'm not very familiar with the hotlists and the criteria of being added to one, but if you have "feature parity" hotlist then I'd add it there.

**Comment by btford** [comment]
:+1:

**Comment by naomiblack** [comment]
internal tracking issue is 27386618

**Comment by naomiblack** [comment]
Closing this. @pavelgj we think you are actually asking for something else. Please set up some time to come chat with the team?
