### ISSUE TITLE
Router paths that match * (star) seem to consume URL variables

### ISSUE THREAD

**Issue by xealot** [angular/angular#7244]
Angular's new Matrix URL type variables seem to get consumed by star matching routes.

A path constructed like this...

`{ path: "/browse/*path", name: "ListPath", component: StepListing },`

Produces `RouteParams` objects like this:

![image](https://cloud.githubusercontent.com/assets/189873/13269701/1f80f948-da57-11e5-8182-2a48d126c3a2.png)

**Comment by xealot** [comment]
May relate to #7312

**Comment by vicb** [comment]
obsolete
