### ISSUE TITLE
Input properties are always undefined

### ISSUE THREAD

**Issue by Futourism** [angular/angular#7245]
Hello guys.

I tried badly to make a component that takes an input parameter directly from HTML, something like this:

`<my-cmp [parm]="'SomeText'"></my-cmp>`

I tried every solution using "@Input", "inputs" and "properties", but I never had success.

My component looks like this:

> import {Component, View, Input, enableProdMode} from "angular2/core";
> import {bootstrap} from "angular2/platform/browser";
> 
> enableProdMode();
> 
> @Component({
>     selector: "my-cmp"
> })
> 
> @View({
>     templateUrl: "_item.html"
> })
> 
> export class MyCmp { 
>     @Input() parm: string;
> 
>     constructor() {
>         
>     }
>     
>     ngOnInit() {
>         console.log(this.parm);
>     }
> }
> 
> bootstrap(MyCmp)
>     .then(app => { }, 
>     err => {
>         console.error(err);
>     });

The HTML Template is something straightforward like "&lt;h1&gt;{{parm}}&lt;/h1&gt;"

The result is that the &lt;h1&gt; DOM is generated empty and the console.log of "parm" returns undefined.

What is wrong in this code?

Thank you

**Comment by ericmartinezr** [comment]
dup of https://github.com/angular/angular/issues/1858

**Comment by Futourism** [comment]
Ah ok thanks, I close the issue immediately
