### ISSUE TITLE
The case of the built in control validators minLength and maxLength is inconsistent

### ISSUE THREAD

**Issue by harangue** [angular/angular#7246]
Hey, I'm loving the way forms are implemented in Angular.

I will say however, that I was confused for quite a bit by the `minLength` and `maxLength` validators. They are accessed through `Validators.minLength()` and `Validators.maxLength()`, but if you want to check `.hasError` on the control you must use all lowercase, `control.hasError('minlength')`.

For consistency, these should probably be the same. :)

**Comment by mhevery** [comment]
Dup of #7407

**Comment by kara** [comment]
Closing in favor of #7407
