### ISSUE TITLE
router: URParser.parseParam ignore arrays

### ISSUE THREAD

**Issue by aslubsky** [angular/angular#7253]
When we have a some array parameters URParser join it to one. Example:
```
http://localhost:8080/news/edit?filter[created_at]=2016-02-20&filter[created_at]=2016-02-24
```
it will be automatically replaced to 
```
http://localhost:8080/news/edit?filter[created_at]=2016-02-24
```
because parseQueryParams use 
```
var params = {};
 ```
(file url_parser.js line 146, angular version 2.0.0-beta.3)
like associative array and parameter name (filter[created_at] in my case) like a key

**Comment by ca136** [comment]
looks like this is happening somewhere else but looks like there's still an issue:
https://github.com/angular/angular/blob/master/modules/%40angular/router/src/url_tree.ts#L407

**Comment by vsavkin** [comment]
Dup of https://github.com/angular/angular/issues/11374
