### ISSUE TITLE
CanActivate, base class not invoked? Should this work?

### ISSUE THREAD

**Issue by Steveiwonder** [angular/angular#7256]
If i have the following:

```typescript
@CanActivate((next: ComponentInstruction, prev: ComponentInstruction) => {

  //return bool or promise.
  return true;
});

export class BaseComponent {

}

export class UserComponent extends BaseComponent {

}
```

When I navigate to the **/User** route (`UserComponent`) `CanActivate` is not invoked on the base class.

**My question**: Should it be? If not will it be supported in the future?

I see on here: https://angular.io/docs/ts/latest/api/router/CanActivate-decorator.html

> Note that unlike other lifecycle hooks, this one uses an annotation rather than an interface.
> This is because the function is called before the component is instantiated.

I wonder if this has something to do with it?

Thanks

Steve

**Comment by thomashilzendegen** [comment]
> I wonder if this has something to do with it?

Exactly, as there is no instance available where class inheritance could be used. Otherwise the component would need to be instantiated (and this is not wanted in that case). I am not sure, if decorator inheritance should/could be implemented, but this could complicate many things...

**Comment by zoechi** [comment]
AFAIK currently no annotations of subclasses are considered. `@Component()`, `@Input()`, ...

**Comment by zoechi** [comment]
Similar to #5415

**Comment by zoechi** [comment]
`@CanActivate` is for the old router. This can be closed.
