### ISSUE TITLE
Developer Guide - Forms tutorial missing the style.css at the end

### ISSUE THREAD

**Issue by datoml** [angular/angular#7258]
Hello,
As I went through the documentation of the forms I found an error in the conclusion part.
[Forms Documentation](https://angular.io/docs/ts/latest/guide/forms.html)

No big deal but the product structure is missing the style.css file.

**Comment by zoechi** [comment]
Documentation issues are maintained in the https://github.com/angular/angular.io repo.

**Comment by datoml** [comment]
@zoechi Thanks.
Didnt know that. Sorry.

**Comment by zoechi** [comment]
No prob, thanks for reporting.  Can you please create the issue there and close it here?

**Comment by datoml** [comment]
@zoechi I hope I did it in the right way.
Instead of creating an issue I forked the forms.js and made an pull request.

**Comment by zoechi** [comment]
Not sure what you mean by "I forked the forms.js" but a pull request sounds great.

**Comment by datoml** [comment]
Sorry. I edited my post before. I ment the forms.jade in the docu :).

**Comment by zoechi** [comment]
I see. I don't see the pull request in the angular.io repo. 
Anyway can you please close tis issue here in the angular repo?
