### ISSUE TITLE
2-way data binding to an attribute

### ISSUE THREAD

**Issue by disposition68** [angular/angular#7261]
It doesn't seem like this is currently possible in Angular 2. I'm using a series of PolymerJs components in conjunction with my Angular 2 app, and many of the form elements that have been created reflect their value up to an attribute on the element. Allowing for 2-way binding here would make my life much simpler. Are there any plans to allow view -> data source binding for attributes?

**Comment by zoechi** [comment]
That's currently possible but your comment doesn't provide enough information to give detailed guidance. 

GitHub issues are for bug reports and feature requests. 
      For support questions please use other channels like [StackOverflow](http://stackoverflow.com/questions/tagged/angular2), [Gitter](https://gitter.im/angular/angular), [Google groups](https://groups.google.com/forum/#!forum/angular), ...

**Comment by disposition68** [comment]
If it's possible, I'll take the issue to SO. Thanks.
