### ISSUE TITLE
Injecting service into service leads to "EXCEPTION: Error during instantiation of"

### ISSUE THREAD

**Issue by Futourism** [angular/angular#7264]
Hello,

I'm going step by step further into NG2 and I hit another rock, although till now the learning curve didn't seem too steep.

I successfully created a service and injected it into a component that I use into a page.

Now I want to inject into the service itself a native service I need from NG2, but I get the errors:

> EXCEPTION: Error during instantiation of InitObject! (ListItem -> InitObject).
> ORIGINAL EXCEPTION: unimplementedt.logError @ angular2.min.js:17
> angular2.min.js:17ORIGINAL STACKTRACE:t.logError @ angular2.min.js:17
> angular2.min.js:17Error: unimplemented
>     at new t (angular2.min.js:5)
>     at Object.i [as unimplemented] (angular2.min.js:5)
>     at e.Object.defineProperty.get [as nativeElement] (angular2.min.js:4)
>     at new InitObject (injectorHelpers.js:27)
>     at angular2.min.js:1
>     at e._instantiate (angular2.min.js:8)
>     at e._instantiateProvider (angular2.min.js:8)
>     at e._new (angular2.min.js:8)
>     at e.getObjByKeyId (angular2.min.js:8)
>     at e._getByKeyDefault (angular2.min.js:8)t.logError @ angular2.min.js:17
> angular2.min.js:17ERROR CONTEXT:

I tried to follow the examples online but I'm not able to solve it ...

my Component looks like this:

```
import {Component, View, ElementRef, enableProdMode} from "angular2/core";
import {bootstrap} from "angular2/platform/browser";
import {InitObject} from "../_services/injectorHelpers";

enableProdMode();

@Component({
    selector: "list-item"
})

@View({
    templateUrl: "_item.html"
})

export class ListItem { 
    
    initObj : any;
    
    constructor(initObject: InitObject) {
        this.initObj = initObject.value;
    }
}

bootstrap(ListItem, [InitObject, ElementRef])
    .then(app => { }, 
    err => {
        console.error(err);
    });
```

... while my Service looks like:

```
import {Injectable, ElementRef} from "angular2/core";

@Injectable()
export class InitObject {
    value : any;
    isNull : boolean;
    
    constructor(myElement: ElementRef) {
        this.value = JSON.parse(myElement.nativeElement.getAttribute("ng2-initobj"));
        this.isNull = (this.value == null);
    }
}
```

I tried even using @Inject (@Inject(ElementRef) public ...) instead of @Injectable() and without passing ElementRef to the bootstrap.

Without the injection of ElementRef into the Service and making the service just assign constants to "value" everything works fine.

What am I doing wrong?
Thanks a lot.

EDIT:
to specify ...
debugging in Chrome I get the error once I try to access myElement.nativeElement

**Comment by Futourism** [comment]
to specify ...

debugging in Chrome I get the error once I try to access myElement.nativeElement

**Comment by zoechi** [comment]
Can you please edit your initial post and wrap the code with triple-backtick ``` instead of formatting as quote. It's really hard to read this way.

**Comment by zoechi** [comment]
A plunker that demonstrates the issue would be helpful as well.

**Comment by Futourism** [comment]
Hi @zoechi , thanks for the reply!

I cleaned my previous post, and asap I'll link a plunker with the code ...
is a generic problem for a basic feature as it is the IOC inside services used by components.

**Comment by zoechi** [comment]
This usually just works but I couldn't see a problem with your code.

**Comment by ericmartinezr** [comment]
From the docs

>An ElementRef is created for each element in the Template that contains a Directive, Component or data-binding.
>An ElementRef is backed by a render-specific element. In the browser, this is usually a DOM element.

Where does the ElementRef you're trying to inject being populated? Nowhere. That ElementRef is not being backed by anything.

Your approach is wrong. Instead of trying to inject ElementRef in your bootstrap you should inject it in some component/directive and then use some setter from your service to pass its content.

```
class Service {
   elementRef;
}

class App {
 constructor(svc: Service, elementRef: ElementRef) {
       svc.elementRef = elementRef;
 }
}

bootstrap(App, [Service])
```

**Comment by Futourism** [comment]
Thanks @ericmartinezr I'll try this solution.

In general so, we can say that IOC doesn't work for DOM manipulation services.

**Comment by Futourism** [comment]
Yes, in the end I cam out with this code, and it works:

**APP**
```
import {Component, View, ElementRef, enableProdMode} from "angular2/core";
import {bootstrap} from "angular2/platform/browser";
import {InitObject} from "../_services/injectorHelpers";

enableProdMode();

@Component({
    selector: "list-item"
})

@View({
    templateUrl: "_item.html"
})

export class ListItem { 
    
    initObj : any;
    
    constructor(elementRef: ElementRef, initObject: InitObject) {
        initObject.init(elementRef);
        this.initObj = initObject.value;
    }
}

bootstrap(ListItem, [InitObject])
    .then(app => { }, 
    err => {
        console.error(err);
    });
```

**SERVICE**
```
import {Injectable} from "angular2/core";

@Injectable()
export class InitObject {
    value : any;
    isNull : boolean;
    
    constructor() {
        
    }
    
    init(elementRef) {
        this.value = JSON.parse(elementRef.nativeElement.getAttribute("ng2-initobj"));
        this.isNull = (this.value == null);
    }
}
```

Is that ok?
Do you know more elegant ways of writing this?

Thanks

**Comment by pkozlowski-opensource** [comment]
Sounds like a support question that got resolved. Closing.
