### ISSUE TITLE
Is FormData support coming anytime soon to http?

### ISSUE THREAD

**Issue by vladimir-ivanov** [angular/angular#7265]

**Comment by zoechi** [comment]
https://github.com/angular/http/issues/75

**Comment by joewoodhouse** [comment]
Is this now supported? That issue link above no longer works.

**Comment by DzmitryShylovich** [comment]
yeap https://github.com/angular/angular/blob/efbbefd353fb1ab18b9011eccd45cf7b4ebc4ef6/modules/%40angular/http/test/backends/xhr_backend_spec.ts#L314
