### ISSUE TITLE
Routing hard refresh with forward tilde on quick start guide.

### ISSUE THREAD

**Issue by damiandennis** [angular/angular#7267]
Going through the quick start guide. If I put in a path that has a forward slash in the path and hard refresh e.g http://localhost:3000/dsfsdfdsf/sdfdsfdsf, the application breaks. I have tried updating all paths to be absolute with no success. When I do I get Unexpected token <(…)
```javascript
SyntaxError: Unexpected token <
	Evaluating http://localhost:3000/app/main
	Error loading http://localhost:3000/app/main
    at eval (native)
    at SystemJSLoader.__exec (http://localhost:3000/node_modules/systemjs/dist/system.src.js:1395:16)
    at entry.execute (http://localhost:3000/node_modules/systemjs/dist/system.src.js:3521:16)
    at linkDynamicModule (http://localhost:3000/node_modules/systemjs/dist/system.src.js:3126:32)
    at link (http://localhost:3000/node_modules/systemjs/dist/system.src.js:2969:11)
    at Object.execute (http://localhost:3000/node_modules/systemjs/dist/system.src.js:3301:13)
    at doDynamicExecute (http://localhost:3000/node_modules/systemjs/dist/system.src.js:703:25)
    at link (http://localhost:3000/node_modules/systemjs/dist/system.src.js:905:20)
    at doLink (http://localhost:3000/node_modules/systemjs/dist/system.src.js:557:7)
    at updateLinkSetOnLoad (http://localhost:3000/node_modules/systemjs/dist/system.src.js:605:18)
```

The route does not exist by the way but it should be handled by the application.

**Comment by brandonroberts** [comment]
I'm not sure this is a router error. Can you reproduce in a plunker?

**Comment by damiandennis** [comment]
Hard to reproduce in a plunker as its based on path based routes in html5, with a hard refresh on that route. I could probably get it up on a external site to demonstrate what I mean.

**Comment by brandonroberts** [comment]
What does your index.html file look like?

**Comment by damiandennis** [comment]
created a simple example: http://route.damiandennis.com/
click on the course route, that works fine. The hit ctrl R or however you want to do a hard refresh on that route and you will see what I mean. can see my html source: view-source:http://route.damiandennis.com/

**Comment by damiandennis** [comment]
also pushed up the code to https://github.com/damiandennis/route-issue-example

**Comment by brandonroberts** [comment]
Ok, this isn't a router issue specifically, its a server issue. Your server needs to be setup to redirect all requests to index.html if you're using HTML5 mode.

**Comment by damiandennis** [comment]
It is setup to redirect in my htaccess to index.html, I can show you another route that will work, gimme a few to set it up.

**Comment by damiandennis** [comment]
actually if you just look at the source of the file you will see that it is the same html page.

**Comment by damiandennis** [comment]
view-source:http://localhost:3000/courses/1

**Comment by damiandennis** [comment]
view-source:http://route.damiandennis.com/courses/1

**Comment by damiandennis** [comment]
trying to avoid HashLocationStrategy as we want pretty urls.

**Comment by brandonroberts** [comment]
Right, but anything that doesn't exist on your server should return index.html. If you look at the network tab in the debugger, all your scripts are returning the index.html source. Try moving your <base href="/> above your scripts.

Your request looks like this

```
Request URL:http://route.damiandennis.com/courses/node_modules/systemjs/dist/system.src.js
```

**Comment by damiandennis** [comment]
ok looks like you are right about the <base href="/"> and it needing to be at the top, thanks... I should have read the router docs more carefully about it being right after the opening "head" tag.

**Comment by damiandennis** [comment]
also is it possible to do the same thing using the bootstrap loader?
provide(APP_BASE_HREF, {useValue: '/central'})

**Comment by brandonroberts** [comment]
:+1:

**Comment by brandonroberts** [comment]
Yep, you can do either one
