### ISSUE TITLE
bug(Lifecycle): Lifecycle hooks not called unless defined on the prototype

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#7270]
The lifecycle hooks (component, router) are called if defined on the class, or the function prototype, but are not called if defined in the constructor. 

```js
class MyComponent implements OnInit {
    ngOnInit() { 
        // works
    }
}

class MyComponent implements OnInit {
    ngOnInit: any = () => {
         // no TypeScript warning, never called
    }
}

function MyComponent() {
}

MyComponent.prototype.ngOnInit = function() {
    // works
};

function MyComponent() {
    this.ngOnInit = function() {
        // never called
    };
}
```

I expect the lifecycle hook to be called in either scenario. Is this by design?

cc: @mhevery

**Comment by ValeriiVasin** [comment]
Have the same issues with lifecycle hooks. That was totally unexpected...

Will it be fixed?

BTW, React lifecycle hooks [behave the expected way](https://jsbin.com/vokozo/2/edit?js,console,output).

**Comment by wardbell** [comment]
Easy to guess why as it would be safer to analyze a prototype and store the information about the component rather than instantiate one (risk of it doing something in the ctor) to find out what it has.

Why is this proposal important?

**Comment by mhevery** [comment]
Sorry, this is working as intended. The reason for this is that we need to code-gen different code depending if we have such a hook or not. Code-gen can only access the prototype chains, as we can't instantiate/run code. So if you want speed, prototype is the only thing we can look at.
