### ISSUE TITLE
module.id - missing typings unresolved variable or type module

### ISSUE THREAD

**Issue by tsm91** [angular/angular#7271]
I get "Unresolved variable or type module" when i specify `modelId: model.id` @Component metadata.

I temporary fixed it with this chunk of code:

```
interface ModuleInterface {
  id: any;
}

declare var module: ModuleInterface;
```

i think something like this is missing from a d.ts file, i checked metadata.d.ts `ComponentFactory`  i see `moduleId?: string;`

I don't exactly know where does module.id comes from, but the [documentation](https://angular.io/docs/js/latest/api/core/ComponentMetadata-class.html) says :

> The module id of the module that contains the component. Needed to be able to resolve relative urls for templates and styles. In Dart, this can be determined automatically and does not need to be set. In CommonJS, this can always be set to module.id.

So i guess it should be defined somehow.

**Comment by dohomi** [comment]
@tsm91 how exactly did you resolve this issue? I receive the same error in `Webstorm`. Thanks

**Comment by skreborn** [comment]
@dohomi
> In CommonJS, this can always be set to `module.id`.

CommonJS defines `module.id`, it's not something defined by Angular, so you can only use it if your modules are using the CommonJS format.

**Comment by dohomi** [comment]
Hi @skreborn yes I'm using commonjs - actually I run a `Meteor + Angular2` experiment and can't get rid of the error message. This is my `tsconfig.json`:
```
{
  "name": "test",
  "dependencies": {
    "es6-promise": "registry:npm/es6-promise#3.0.0+20160211003958",
    "lodash": "registry:npm/lodash#4.0.0+20160416211519"
  },
  "globalDependencies": {
    "es6-shim": "registry:dt/es6-shim#0.31.2+20160317120654"
  }
}
```

**Comment by dohomi** [comment]
Ok @skreborn I added node to my typings. Would be great if there would be a hint at the angular docs to add typings for node if moduleId is in use. Cheers
