### ISSUE TITLE
Route changed event

### ISSUE THREAD

**Issue by malichishti** [angular/angular#7272]
Just a quick question, is there anything which can inform a component that a route has changed? as a result of some navigation, which might not have been initiated by the component itself.

**Comment by zoechi** [comment]
You can subscribe to the `Router` to get notified about route actions.
```ts
constructor(router:Router) {
   router.subscribe(value => onRouteChange(value));
}
```
GitHub issues are for bug reports and feature requests. 
      For support questions please use other channels like [StackOverflow](http://stackoverflow.com/questions/tagged/angular2), [Gitter](https://gitter.im/angular/angular), [Google groups](https://groups.google.com/forum/#!forum/angular), ...

**Comment by malichishti** [comment]
Thank you, will keep that in mind.

**Comment by malichishti** [comment]
Perhaps a suggestion, this doesn't work on child routers.

**Comment by zoechi** [comment]
@malichishti t AFAIK the workaround is to do it in a global service and inject the service wherever you need access to.
