### ISSUE TITLE
Missing event property error raises silently in web workers

### ISSUE THREAD

**Issue by eesdil** [angular/angular#7276]
Not sure it is a big issue, but quite annoying. 

In a web worker  a method/property which doesn't exists defined on an event, example `event.stopPropagation()`, it is raising an error, however in console it cannot be seen...

You have to switch on "Pause on caught events".
Switching on this feature is nice, but having on all the time is not convinient...

**Comment by splincode** [comment]
@eesdil This issue is relevant?
