### ISSUE TITLE
Angular2 *ngFor calls right hand side for each loop

### ISSUE THREAD

**Issue by Andy1605** [angular/angular#7283]
Hi there,

Let's say i have got smth like in this plunker here: [https://plnkr.co/edit/8qBCiGIrepiQ7OMbZ4zk?p=preview](https://plnkr.co/edit/8qBCiGIrepiQ7OMbZ4zk?p=preview)

I was just wondering if ngFor would call a function on the right hand side of the 'of' operator more than once. I tested it and found out that it does.
Isn't that a bit of a performance killer? Even if that example i gave you may not be the strongest. Is there any reason why that is?
Or is there a possibility to define an initial variable which would be very helpful. Something like this:
`<li *ngFor="#a = keys(items); #c of a">{{a[c]}}</li>`

Sincerely

**Comment by zoechi** [comment]
The Plunker shows that `keys()` is called more than once in devMode which is expected because Angular evaluates each binding twice in each change detection cycle. 

You shouldn't call functions like this in bindings. A better way is to assign the value (the result of the `keys(xxx)` call to a field and bind to that field.

**Comment by Andy1605** [comment]
Ok, i see. But does that really make sense? If angular doesn't like it anyways, why not just cache the right hand side, like common compilers (like java, c++) do and the problem would be solved.

**Comment by zoechi** [comment]
How would Angular know when to evict the cached value and fetch a new one? You need to cache it instead and return a new one when the old is outdated.

**Comment by Andy1605** [comment]
I mean not permanently caching but for one ngFor run.

Like so:
var target = rightHandSide();
for(var i in target)
 //do magic

**Comment by zoechi** [comment]
I'm sure this is what it does. What you see in your Plunker is change detection in `devMode` always checking twice.
