### ISSUE TITLE
Feature request: add support to xml on http module ...

### ISSUE THREAD

**Issue by born2net** [angular/angular#7284]
today ng2 supports text() and json()

```
this._http.get(`${BASE_URL}`)
                .map(result => {
                    var xmlData:XML = result.xml() // <====
                     ...
```
it will be symmetrical and desirable to do the same for XML (XML is still popular)...

Regards,

Sean

**Comment by zoechi** [comment]
XML is deprecated in Chrome. I guess this would require some external library. 
`Http` was moved over to https://github.com/angular/http. 
See also angular/http#75

**Comment by robwormald** [comment]
This is easily handled with a 3rd party XML parser, and I don't think it's something we want to support in core:
```js
http.get(url).map(res => thirdPartyXMLParser(res.text())).subscribe()
```
or in a more reusable form:

```js
function parseXMLResponse(responseObservable){
  return responseObservable.map(res => thirdPartyXMLParser(res.text()))
}

http.get(url).let(parseXMLResponse).subscribe()
```

**Comment by born2net** [comment]
tx, yes that's what I am already doing... but figured it would be nice to be part of the framework... no worries, tx!

**Comment by robwormald** [comment]
@born2net i added an issue above, we'll think about it a bit deeper. If you want to post your use cases and such, please feel free.
