### ISSUE TITLE
Typescript files throwing errors after modifying a file, when gulp tries to recompile it

### ISSUE THREAD

**Issue by twilliamsgsnetx** [angular/angular#7286]
This Stackoverflow has more information about my problem, but I will detail it below as well.

http://stackoverflow.com/questions/35580944/gulp-typescript-emitting-errors-upon-save-but-is-fine-with-subsequent-saves?noredirect=1#comment58946776_35580944

Ever since upgrading to Beta 6, and now Beta 7 from Beta 0, I have been having this issue where my gulp builds throw out a whole bunch of errors like the following, but only after a successful initial build. It builds first, and then if I made a modification to a .ts file it causes the errors. Subsequent attempts to save, and it continues working again but I think it is really failing still because the files don't seem to be emitted with changes.

`client\platform\report catalog\details\reportDetails.component.ts(7,15): error TS2304: Cannot find name 'module'.
C:/Github/Data-Platform/src/DataPlatform/node_modules/angular2/src/core/application_ref.d.ts(171,81): error TS2304: Cannot find name 'Promise'.
C:/Github/Data-Platform/src/DataPlatform/node_modules/angular2/src/core/di/provider.d.ts(436,135): error TS2304: Cannot find name 'Map'.`

There's over 100 of these errors with Beta 7, but I think part of it is due to the size of my project.

I am currently solving the module error by having a typing that I've defined which declares a module variable.

`declare var module: any;
`
This and the other typing reference from Beta 6 are located in my boot.ts file, but nowhere else.

```
///<reference path="../../node_modules/angular2/typings/browser.d.ts"/>
///<reference path="../../typings/shim.d.ts"/>
```

This is completely throwing a wrench into my ability to recompile the typescript files with gulp-watch, and I think it's something to do with angular.

**Comment by antonybudianto** [comment]
if you're using [gulp-typescript](https://www.npmjs.com/package/gulp-typescript) to compile, then include these files as source
```javascript
'typings/main.d.ts',
'typings/main/*.d.ts',
'node_modules/angular2/typings/browser.d.ts'
```
since some of `tsconfig.json` config are not supported

**Comment by Raziaar** [comment]
@antonybudianto Include the files as a source where? In the tsconfig file, as references in the root component, where?

**Comment by pkozlowski-opensource** [comment]
Seems like the StackOverflow question was answered. @Raziaar plesae don't cross-post and don't use GitHub issues as the support forum.

**Comment by antonybudianto** [comment]
@Raziaar , please look at this [setup](https://github.com/antonybudianto/angular2-starter/blob/master/tasks/typescript.js#L10)
