### ISSUE TITLE
Create zone-aware HttpRequest wrapper for Dart

### ISSUE THREAD

**Issue by juliemr** [angular/angular#7290]
See https://github.com/angular/angular/issues/7141

We will try creating a dart HttpRequest wrapper with the same API, that ngZone can get the information it needs from.

**Comment by juliemr** [comment]
see https://github.com/angular/angular/pull/7466

**Comment by paullessing** [comment]
Hi @juliemr, I just found this issue cross-referenced from #7141. Would you please be so kind to clarify for me, would fixing this issue resolve #7141 too, i.e. fix the XHR Testability behaviour for Typescript, not just Dart?

**Comment by juliemr** [comment]
@paullessing Hope this is still useful - #7141 has been resolved for TypeScript. It will now wait on XHRs and treat them as macrotasks.

**Comment by vicb** [comment]
obsolete
