### ISSUE TITLE
[hidden] cannot hide if with Bootstrap class

### ISSUE THREAD

**Issue by Hongbo-Miao** [angular/angular#7300]
In Angular 2,

`[hidden]` does not work on any elements including `class="glyphicon"`, `class="label"`, `class="help-block"`, etc. from Bootstrap.

This cannot hide, so not works
`<span [hidden]="true" class="glyphicon glyphicon-plus-sign"></span>`

This can hide, works well
`<span [hidden]="true">test</span>`

**Comment by ericmartinezr** [comment]
This is not related to angular2 at all. Check this [fiddle](https://jsfiddle.net/2njhh223/). Check this [answer](http://stackoverflow.com/questions/22145285/can-we-hide-glyphicons-using-hidden-hidden). It's a bootstrap thing.

**Comment by Hongbo-Miao** [comment]
@ericmartinezr thanks!
