### ISSUE TITLE
Mock out all window DOM objects

### ISSUE THREAD

**Issue by jeffwhelpley** [angular/angular#7304]
Although we are encouraging users to not directly use the window DOM objects, we can't stop anyone from using them. We just need mocks for all window objects so that when an Angular 2 app runs on the server, in a web worker, on a mobile device, etc. the app doesn't break.

**Comment by manekinekko** [comment]
How about [JSDOM ](https://github.com/tmpvar/jsdom) ?

**Comment by jeffwhelpley** [comment]
No, JSDOM is way to heavyweight and we are not talking about actually implementing functionality. We just want to see if we can add mocks so that window object code doesn't break the app. So, it would be more like:

```
var window = {
  document: {
    querySelector: function () {} // do nothing
  } 
}
```

**Comment by jeffwhelpley** [comment]
OK, closing this out after conversation with @jeffbcross. We are going to handle this issue on the Universal repo.
