### ISSUE TITLE
Token to key mapping is using the name of the constructor rather than the token passed as the constructor.

### ISSUE THREAD

**Issue by stringham** [angular/angular#7306]
I believe this is the cause of #7204 (and possibly #6380 too).

If you have an app that looks like the following:

```javascript
var Component1 = function Component() {};
var Component2 = function Component() {};

Component1 = ng.core
    .Component({
        selector:"cmp1",
        template:"<div>cmp1</div>"
    })
    .Class({
        constructor:[
            Component1
        ]
    });

Component2 = ng.core
    .Component({
        selector:"cmp2",
        template:"<div>cmp2</div>"
    })
    .Class({
        constructor:[
            Component2
        ]
    });

var AppComponent = ng.core
    .Component({
        selector:'test-app',
        template:`
            <cmp1></cmp1>
            <cmp2></cmp2>
        `,
        directives:[
            Component1,
            Component2,
        ]
    })
    .Class({
        constructor:[
            function() {
                window.app = this;
            }
        ]
    });

document.addEventListener('DOMContentLoaded', function() {
    ng.platform.browser.bootstrap(AppComponent, []);
});
```

The output is:

cmp2
cmp2

If you change the first two lines to

```javascript
var Component1 = function Component1(){};
var Component2 = function Component2(){};
```

the output of the app is:

cmp1
cmp2

plnkr: http://plnkr.co/edit/HjQUFXRNryipVgKBDIfx?p=preview

The minified code creates all of the core components with name "e" rather than "ngIf", "ngFor", etc. So when it goes to inject one of them, it usually finds the wrong one.

**Comment by mark-buer** [comment]
This issue seems to most accurately describe the root of problem with minification etc.

In simple terms, the Angular framework makes the misguided assumption that constructor function names are unique.

**Comment by IgorMinar** [comment]
per @gdi2290 these two lines look suspicious:

https://github.com/angular/angular/blob/ebe531bf92b931280383a2d5262ea23a0879d891/modules/angular2/src/compiler/template_compiler.ts#L253
https://github.com/angular/angular/blob/ebe531bf92b931280383a2d5262ea23a0879d891/modules/angular2/src/compiler/template_compiler.ts#L258

as they seem to be referencing Function.prototype.name which we can't rely on because fn names get stripped or renamed by minifiers.

**Comment by patrickmichalina** [comment]
Would this be the issue to track when I have minification issues when "mangled" options is used on a JSPM single file build? "--no-mangle" works fine, but when mangle is used, I am getting silent failures.

**Comment by tbosch** [comment]
No, this issue is independent of minification.

The issue here was actually fixed by https://github.com/angular/angular/pull/11145
