### ISSUE TITLE
ngOnChanges called when ngDoCheck implemented

### ISSUE THREAD

**Issue by wardbell** [angular/angular#7307]
According to the [DoCheck API documentation](https://github.com/angular/angular/blob/master/modules/angular2/src/core/linker/interfaces.ts#L136)

>a directive should not implement both DoCheck and OnChanges at the same time. ngOnChanges would not be called when a directive implements DoCheck. Reaction to the changes have to be handled from within the ngDoCheck callback.

But `ngOnChanges` **is called** as of beta.7.

See [this plunker](http://plnkr.co/edit/RRSlfk1Rizqp1PwX4Qno?p=preview)

**Comment by mhevery** [comment]
The behavior is correct, the documentation is wrong. `DoCheck` and `OnChanges` can be implemented together and will work together. Not sure where the text that they are exclusive came from.

**Comment by wardbell** [comment]
Thanks.I'll correct the devguide and its sample. 

Let's leave this open until someone fixes the API doc

**Comment by zbjornson** [comment]
@mhevery looking at property_binder.ts, it looks like `OnChanges` will only fire using the default change detector, and there is no way to use `DoCheck` to change when `OnChanges` is fired, is that right? (So in that sense, the docs are sort of correct that it probably won't be useful to use both together, but one would also hope that using `DoCheck` will remove the default CD for perf reasons.)

**Comment by petebacondarwin** [comment]
Does `DoCheck` get triggered if the change detection strategy is set to `Checked`?

**Comment by zbjornson** [comment]
@petebacondarwin Good question. `ChangeDetectionStrategy.{Checked|OnPush|Detached}` will still cause `DoCheck` to trigger at least once per update *iff a bound property changes.* If no bound property changes, then only `{Default|CheckAlways}` will trigger hooks.

[Plunker](http://plnkr.co/edit/74d0r3byCy4azyaGDSfj) (toggle on/off line 84)
(Same conclusion from tweaking the [live demo plunker from the docs](https://angular.io/resources/live-examples/lifecycle-hooks/ts/plnkr.html), which differs at least in that the child component is not instantiated until after application boostrapping.)

With bound property changing:

| Default/CheckedAlways | Checked/OnPush/Detached |
| --- | --- |
| *Construction* <ol><li>Construction</li><li>OnChanges</li><li>OnInit</li><li>**DoCheck**</li><li>AfterContentInit</li><li>AfterContentChecked</li><li>AfterViewInit</li><li>AfterViewChecked</li><li>**DoCheck**</li><li>AfterContentChecked</li><li>AfterViewChecked</li><li>**DoCheck**</li><li>AfterContentChecked</li><li>AfterViewChecked</li><li>**DoCheck**</li><li>AfterContentChecked</li></ol> *Update* <ol><li>AfterViewChecked</li><li>OnChanges</li><li>**DoCheck**</li><li>AfterContentChecked</li></ol> *Update* <ol><li>AfterViewChecked</li><li>OnChanges</li><li>**DoCheck**</li><li>AfterContentChecked</li></ol> | *Construction* <ol><li>Construction</li><li>OnChanges</li><li>OnInit</li><li>**DoCheck**</li><li>AfterContentInit</li><li>AfterContentChecked</li></ol> *Update* <ol><li>AfterViewInit</li><li>AfterViewChecked</li><li>**DoCheck**</li><li>AfterContentChecked</li><li>AfterViewChecked</li><li>**DoCheck**</li><li>AfterContentChecked</li><li>AfterViewChecked</li><li>**DoCheck**</li><li>AfterContentChecked</li><li>AfterViewChecked</li><li>OnChanges</li><li>**DoCheck**</li><li>AfterContentChecked</li></ol>  *Update* <ol><li>AfterViewChecked</li><li>OnChanges</li><li>**DoCheck**</li><li>AfterContentChecked</li></ol> |

Without bound property changing:

| Default/CheckedAlways | Checked/OnPush/Detached |
| --- | --- |
| *Construction* <ol><li>Construction</li><li>OnChanges</li><li>OnInit</li><li>**DoCheck**</li><li>AfterContentInit</li><li>AfterContentChecked</li><li>AfterViewInit</li><li>AfterViewChecked</li><li>**DoCheck**</li><li>AfterContentChecked</li><li>AfterViewChecked</li><li>**DoCheck**</li><li>AfterContentChecked</li><li>AfterViewChecked</li><li>**DoCheck**</li><li>AfterContentChecked</li></ol> *Update* <ol><li>AfterViewChecked</li><li>**DoCheck**</li><li>AfterContentChecked</li></ol> *Update* <ol><li>AfterViewChecked</li><li>**DoCheck**</li><li>AfterContentChecked</li></ol> | *Construction* <ol><li>Construction</li><li>OnChanges</li><li>OnInit</li><li>**DoCheck**</li><li>AfterContentInit</li><li>AfterContentChecked</li></ol> *Update* <br> (nada) <br> *Update* <br> (nada) |
