### ISSUE TITLE
md-items is not updating the suggesion list properly in md-autocomplete Angular Material in ajax $http call

### ISSUE THREAD

**Issue by balamanigandan** [angular/angular#7309]
I'm using md-autocomplete, in that md-items which is not updating the response list properly which is obtained from the Service Host - Ajax Call.

HTML Source Code

```
<md-autocomplete flex required
    md-input-name="autocompleteField"
    md-no-cache="true"
    md-input-minlength="3"
    md-input-maxlength="18"
    md-selected-item="SelectedItem"
    md-search-text="searchText"
    md-items="item in querySearch(searchText)"
    md-item-text="item.DisplayName" Placeholder="Enter ID" style="height:38px !important;">
    <md-item-template>
        <span class="item-title">
            <span md-highlight-text="searchText" md-highlight-flags="^i"> {{item.ID}} </span>
            <span> - </span>
            <span md-highlight-text="searchText"  md-highlight-flags="^i"> {{item.Description}} </span>
        </span>
    </md-item-template>
</md-autocomplete>
```

AngularJS Script

```
//bind the autocomplete list when text change
function querySearch(query) {
    var results = [];
    $scope.searchText = $scope.searchText.trim();
    if (query.length >=3) {
        results = LoadAutocomplete(query);
    }
    return results;
}

//load the list from the service call
function LoadCPTAutocomplete(id) {
    TestCalculatorService.searchAutocomplete(id).then(function (result) {
        if (result.data != null) {
            $scope.iList = result.data;
        } else {
            $scope.iList = [];
        }
    });
    return $scope.iList;
}
```

I'm getting the autocomplete list from the Service Host. I'm getting the response properly, but it does not update in the UI properly.

Screen Shot 1: 
![autocomplete](https://cloud.githubusercontent.com/assets/17493171/13349742/bd0a8fb6-dca1-11e5-930e-9825d24cafd2.png)

Here I'm searching for 8224 but it shows the result for 822. I debugged the issue in Firebug, see the above Screen shot it shows, the request was sent for the search term 8224 and I got the response of two matching items as a JSON Object, which is shown in the below Screen Shot 2

Screen Shot 2: 
![firebug](https://cloud.githubusercontent.com/assets/17493171/13349741/bd0a6158-dca1-11e5-8ce4-3ca30bb289f2.png)

Full Issue is posted in Stackoverflow : [http://stackoverflow.com/questions/35624977/md-items-is-not-updating-the-suggesion-list-properly-in-md-autocomplete-angular?lq=1](url) and [http://stackoverflow.com/questions/35646077/manually-call-scope-apply-raise-error-on-ajax-call-error-rootscopeinprog?lq=1](url)

**Comment by ericmartinezr** [comment]
Hey @balamanigandan this repo is for ng2. You're looking for this one https://github.com/angular/angular.js (for ng1 :D). I recommend you though to ask in their gitter's chatroom first https://gitter.im/angular/angular.js :+1:

**Comment by pkozlowski-opensource** [comment]
Thnx @ericmartinezr
