### ISSUE TITLE
Should injector create singletons?

### ISSUE THREAD

**Issue by SekibOmazic** [angular/angular#731]
Hi,

I've changed `injector_spec.js` like this:
 
```Javascript
      it("should use the matching binding when it is available", function () {
        var injector = new Injector([
          bind(Car).toClass(SportsCar)
        ], {defaultBindings: true});

        var car = injector.get(Car);
        var sc = injector.get(SportsCar);
        expect(sc).toBeAnInstanceOf(SportsCar);
        expect(car).toBeAnInstanceOf(SportsCar);
        expect(car === sc).toBe(true);
      });
```

I thought that an Injector always returns singletons, but the test above fails. Is this a correct behavior for Injector?

**Comment by pkozlowski-opensource** [comment]
@SekibOmazic I think there is a slight confusion about what `defaultBindings` does - in a nutshell turning on this option allows you to instantiate, through DI, bindings that were not previously registered. If encountering non-registered binding and having the `defaultBindings` option on the injector will:
* create a new binding using `toClass` method
* use this new binding to create a new instance

The mentioned "magic" happens [here](https://github.com/angular/angular/blob/0dfd287ec33a72e040480caf54fec008b4b04a0f/modules/angular2/src/di/injector.js#L107-L108)

So in your case you could view  `defaultBindings` as sugar for:

```
var injector = new Injector([
          bind(Car).toClass(SportsCar),
          bind(SportsCar).toClass(SportsCar)
       ]);
```

I hope that de-sugared version makes it obvious that there are 2 separate bindings, 2 separate keys in DI and 2 separate instances. 

Hope this clarifies things.

**Comment by SekibOmazic** [comment]
@pkozlowski-opensource Thanks for the explanation. Yes, that clarifies it, definitely.
