### ISSUE TITLE
There's no simple way to start without npm and full source tree

### ISSUE THREAD

**Issue by armanx64** [angular/angular#7313]
I'm using Visual Studio; it compiles TS itself. I had expected that I'm just need add .js files and .d.ts typings to start. Second version must be cleaner and easier, they said. 

After some research on SO I've got use on modules loader, in-browser compiler and other things which I really don't need. But no ready-to-use solution. 

I've tried to download over npm, but it got a whole sources, which in VS even can not compile due to bunch of errors (that's VS fault or project really too raw?). 
I found d.ts on DefinitelyTyped, and found es6-shim and rx typings (why I need them?), but still getting stupid errors like «Cannot find module angular2/core» or «rxjs/Rx». 

Guys, what I'm doing wrong? I don't need nodejs, I need angular with types.

**Comment by episodeyang** [comment]
Try looking up angular seed

**Comment by Binvention** [comment]
you could just load the angular 2 files as plain JavaScript they can be found on [the angular code repository](https://code.angluar.org )and then put their script files in your html. then just compile your typescript files to JavaScript and add those to your html as well. i don't know if there's a different way to do it i haven't used visual studios but i am using just plain JavaScript so i know how to use it without compiling it all.

**Comment by armanx64** [comment]
But excuse me, how I can develop for angular2 on Typescript without d.ts files? 
Without them I lose compile-time checking and other good things.

**Comment by L1ghtm4n** [comment]
No problem here with VS2015 and typescript 1.8.4 for VS.

What is your setup?

**Comment by galtrold** [comment]
I am very excited to get cranking with Angular 2 but experiencing sort of the same as armanx64. I can find the angular 2 library files in node_modules\angular2\bundles\ but angular2.d.ts is no where to be found.
It is a little confusion when all the examples you can find on the web, pull the angular2.d.ts from DefinitelyTyped, which have been removed now. Do you have to build the angular2.d.ts file from the npm download ?

**Comment by zoechi** [comment]
@armanx64 @galtrold even heaven and hell are now switching to Angular2? Love it :D

**Comment by alexeagle** [comment]
Typings are shipped in the angular npm distro now, please re-open if this is still a problem.

**Comment by alcoforado** [comment]
Hey alexeagle, the d.ts files are spread among many files. Is there any way to create d.ts files for the  angular bundles  javascript files in the  bundles folder or combine all of the type def files in just one d.ts ?. 

This one is for desktop applications using WPF and IE embedded browsers. I really don't want to create a dependency with npm or add all those 70  d.ts files in my VS project.

**Comment by alexeagle** [comment]
That's https://github.com/angular/angular/issues/5796
