### ISSUE TITLE
fix: ngIf and ngFor on same element should throw

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular#7315]
Based on https://github.com/angular/angular/issues/4792, putting multiple template directives on a single element doesn't work on Angular 2. It should throw.

However, this plunk demonstrates that it *doesn't* throw. Plus, we see 4 instead of 3 buttons, which is rather confusing.

http://plnkr.co/edit/oK47qCG1BnQsC2Qio1ID?p=preview

**Comment by kukicadnan** [comment]
Looks like both expressions get evaluated. 3 buttons for the ng-for array, and 1 button the ng-if.

**Comment by PascalPrecht** [comment]
@kukicadnan Yeap. But I'd assume it to throw instead.

**Comment by fxck** [comment]
seriously it's not possible to have ngIf and ngFor on the same element? what if you are iterating over a list(`<li>`) and you don't empty `li`s there?

**Comment by zoechi** [comment]
@fxck that would require the order of the directives to be relevant. You might want to render nothing if `*ngIf` evaluates to `false` or as in your example render all but where `*ngIf` evaluates to `false`. 
A workaround is to not use `<ul>` and `<li>` but instead use `<span style="{display:list-item;}">` with the long form 
```
<template [ngFor] ...>
  <span *ngIf="..." style="{display:list-item;}"></span>
</template>
```

**Comment by PascalPrecht** [comment]
> A workaround is to not use <ul> and <li> but instead use <span style="{display:list-item;}"> with the long form

Not the actual solution to this would be to put the `*ngIf` on a `<template>` element that wraps the `<li>`.

@fxck you can still use `<ul>` and `<li>` where it semantically makes sense.

**Comment by zoechi** [comment]
@PascalPrecht I assumed `<template>` is not allowed in all browsers inside `<ul>`. I'm not up-to-date what the status is with all supported browsers. 
Does Angular even insert the `<template>` tag to the DOM when it is used this way?

**Comment by tbosch** [comment]
No, angular will never create the <template> element but a comment instead

**Comment by marcalj** [comment]
I was unaware of this limitation and had a hard time debugging it, since my whole application didn't render and doesn't show me any error in console.

Please, show a big error with clear description. Thanks!

PD: I'm using UpgradeAdapter migrating big NG1 app.

**Comment by naomiblack** [comment]
Fix in 098b461b69862ad011c7b13dc539e187d3761f86 was overly broad. @mhevery has details.

**Comment by mhevery** [comment]
@pkozlowski-opensource 

You created https://github.com/angular/angular/commit/098b461b69862ad011c7b13dc539e187d3761f86 which was a fix for #7315. This fix made `<div *a *b>` illegal, which is correct. But it also made  `<template *ngFor>` illegal, which is perfectly valid. See: https://github.com/angular/angular.io/blob/074a33a6225471852774b51c235f85462d12058f/public/docs/_examples/homepage-tabs/ts/app/di_demo.ts

**Comment by MarkPieszak** [comment]
Is the only solution for having both on the same item, to wrap the ngFor separately (outside) then?

```
<div *ngFor="let item of items">
    <div *ngIf="item.name === 'test'> Test </div>
</div>
```

**Comment by pkozlowski-opensource** [comment]
> Is the only solution for having both on the same item, to wrap the ngFor separately (outside) then?

Yes. If you don't wan't to see any additional elements rendered in the DOM use the `<template>` tag.

**Comment by MarkPieszak** [comment]
Oh okay just wanted to make sure! Thank you Pawel.

**Comment by imalhasaranga** [comment]
I really don't like the idea of using another extra html element to get rid of the problem, designer should have the freedom to design they way it should look perfect right! and we can't come and say Oh... this is not right I can't use the ngFor here ...  

is there a performance issue if we make a method call to get the desired dataset from the class itself  within ngFor ?

**Comment by andreialecu** [comment]
@imalhasaranga the `<template>` element is only a placeholder, it will not actually be included in the generated html/DOM.

**Comment by imalhasaranga** [comment]
Oh.. Sorry for the misunderstanding, but still this does print out an empty ul as the result, i'm pretty sure data is there because without template it works

`<template *ngFor="let nav_link of defaultLinks" >
                    <li [ngClass]="{active : nav_link.routeIsActive}">
                        <a  [routerLink]="nav_link.routePath">{{nav_link.routeText}}</a>
                    </li>
                </template>`

**Comment by imalhasaranga** [comment]
for some reason this 

`<template *ngFor="let item of items" >
   <li>{{item}}</li>
</template>`

does not work in `2.0.0-rc.4` but below works which I took from the documentation

`<template ngFor let-item [ngForOf]="items" let-i="index"><li>...</li></template>`

**Comment by rpark4** [comment]
Hi,  Just another response to the problem of iterating over a list with some empty elements.  This works for me in beta10: 
`<ion-pane *ngFor="let item of steps">
 <ion-pane *ngIf="item.test"> Output: {{item.test}}
 </ion-pane>
 </ion-pane>`

**Comment by imalhasaranga** [comment]
@rpark4 the constraint is you can't have multiple template directives in the same element.

**Comment by markusfalk** [comment]
So what is the proposed solution for now to get the following code example to work?

```html
<ul>
  <li *ngFor="let item of items" *ngIf="item.visible">{{item.name}}</li>
</ul>
```

**Comment by behzad888** [comment]
@imalhasaranga Good job!
You can see https://github.com/angular/angular/issues/4792

**Comment by ashikjs** [comment]
I got this nice solution from
[stackoverflow Q Answer By Imal hasaranga perera](https://stackoverflow.com/questions/34657821/ngif-and-ngfor-on-same-element-causing-error
)
```
<ng-container *ngFor="let nav_link of defaultLinks" >
   <li *ngIf="nav_link.visible">
       .....
   </li> 
</ng-container>
```

**Comment by imalhasaranga** [comment]
:) :)
