### ISSUE TITLE
Zone.js? memory leak -> Observable.Interval

### ISSUE THREAD

**Issue by Guardiannw** [angular/angular#7320]
[After performing some testing with the guys on the ReactiveX/RxJS project](https://github.com/ReactiveX/RxJS/issues/1391), @trxcllnt @kwonoj, it seems like `Observable.interval` does not behave well in the angular2 environment.  If it is standalone, it seems to perform fine. See [this plunk.](http://embed.plnkr.co/QQ76ad4nQQnSdmO0x3Dq/)  But whenever it is inside of angular, it starts to leak memory and overtime has caused my mobile browsers to crash.

I have seen this issue on chrome on linux, as well as Safari on iOS and a webkit based browser: "ZetaKey." See [this plunk](http://embed.plnkr.co/BVK3azp5XT7FpY2MirZI/) to see an example of the leak.  Tip: Run the web inspector timeline for about 1min and hit the garbage collection about every 5 seconds.  When you look at the graph, notice the minimums and how they keep rising. I am not sure exactly what is causing the problem at the moment, but I think it might be some recursive problem involving Zone.js.

I posted an alternative code implementation for Observable.interval that works fine inside angular2; that one doesn't have any recursion at all.  I would appreciate any comments as I would really like to get this resolved.

**Comment by PascalPrecht** [comment]
@Guardiannw As I don't think that this is a problem with Angular's `NgZone` but rather with `Zone.js` itself, this might rather be better posted in this repo here: https://github.com/angular/zone.js

Would keep this one open for visibility though, until someone picks it up.

**Comment by Guardiannw** [comment]
Thanks @PascalPrecht , I could totally post it over there, but I am not 100% that it is Zone.js.  It may be, but I might just leave it here until we are sure.

**Comment by Guardiannw** [comment]
@btford Can you take a look at this?

**Comment by Guardiannw** [comment]
Issue does [seem to reside in zone.js](https://github.com/ReactiveX/RxJS/issues/1391#issuecomment-190451469).  Awaiting integration of zone.js release into ng2.
