### ISSUE TITLE
Route Parameters Datatypes 

### ISSUE THREAD

**Issue by electricBonfire** [angular/angular#7321]
This may already be implemented, and if not, is a Feature Request

I am looking to set datatype requirements on the route params?

For example take the following route:

    @RouteConfig([
        {path: '/product/:id', component: productComponent, as: 'ProductDetail'}
    ])

I would like `:id` to only match if it is a number

`/product/3` would match that route

`/product/foo` would not match the route

**Comment by zoechi** [comment]
Looks like #7126 would allow what you ask for

**Comment by electricBonfire** [comment]
Great thanks!

**Comment by vicb** [comment]
obsolete
