### ISSUE TITLE
fix(ngControlGroup): ngControl errors are not propagated to outer control group

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular#7323]
Control groups track errors of their inner controls. Meaning, whenever an error exists on a single form control because of its validity state, the outer control group becomes invalid too and should give access to all errors in that control group.

Example:

```
<form>
  <div ngControlGroup="name" #nameGroup="ngForm">
    <input ngControl="firstname" minlength="3">
    <input ngControl="lastname" minlength="3">
  </div>
</form>
```

When `firstname` or `lastname` is invalid, `nameGroup` gets invalid too, however, `errors` stays `null`. 

**Note** that this is a template-driven form and might not be an issue in a model-driven form.

**Comment by jingignoli** [comment]
Same problem with a model driven form.

**Comment by zoechi** [comment]
looks like a dup of #6504

**Comment by PascalPrecht** [comment]
@zoechi totes. Closing in favour of #6504
