### ISSUE TITLE
angular router - url parameter with forward slash / gets truncated

### ISSUE THREAD

**Issue by fctucker09** [angular/angular#7324]
When I use angular router, and my url parameter contains a forward slash, the url becomes truncated:

e.g. 
http://localhost:3000/?thisis=atest/withaslash
will be changed to 
http://localhost:3000/?thisis=atest

When i try to access the parameters using RouteParams, i get the truncated url parameter value - 'atest' instead of 'atest/withaslash'.

any idea what is happening and how to fix?

slashes are valid characters in a url parameter, and the issue goes away if i urlencode the forward slash with %2F. Additionally, when retrieving the RouteParam value, the returned value contains the escaped slash (e.g. with the %2F).  not sure if the latter is considered a bug though.

**Comment by zoechi** [comment]
Sounds like #7312

**Comment by vicb** [comment]
obsolete
