### ISSUE TITLE
(submit) -> (ngSubmit)

### ISSUE THREAD

**Issue by e-oz** [angular/angular#7326]
Please add to Changelog information about breaking change: `(submit)` now is `(ngSubmit)`.

**Comment by laco0416** [comment]
`(submit)` is still currently usable. The breaking change is changing `(ng-submit)` to `(ngSubmit)`. 

See https://github.com/angular/angular/blob/master/modules%2Fangular2%2Fsrc%2Fcommon%2Fforms%2Fdirectives%2Fng_form.ts#L84

**Comment by e-oz** [comment]
@laco0416 no, I tried it just now and with (submit) form acts just like usual form (and reload page).

**Comment by laco0416** [comment]
@e-oz Really? I can use it in Beta.7 [plunker](https://plnkr.co/edit/Y38B9p3uVgY8aBAFjD0d?p=preview)

**Comment by e-oz** [comment]
@laco0416 please try this: https://plnkr.co/edit/ZNSl03wDpWh1nyLIQn8v?p=preview

**Comment by ericmartinezr** [comment]
@e-oz you're missing `#f=ngForm` as you see in @laco0416 's plnkr.

Check the docs for [NgForm](https://angular.io/docs/ts/latest/api/common/NgForm-directive.html).

>If NgForm is bound in a component, `<form>` elements in that component will be upgraded to use the Angular form system.

Since you didn't add `ngForm` that form is not an angular form, but a common one.

**Comment by laco0416** [comment]
I think this is an issue of the selector's behavior.

`ngForm` selector is `form:not([ngNoForm]):not([ngFormModel]),ngForm,[ngForm]`.
I think this selector should match simple `<form>`, but its behavior is not so.

Really we need to add `ngForm` not only use `FORM_DIRECTIVES`?

**Comment by e-oz** [comment]
@ericmartinezr I'm not missing it, I removed it intentionally. I have 11 forms without `#f=ngForm` and `(submit)` worked there just fine. I don't mind to replace `(submit)` to `(ngSubmit)` (and I don't need to add #f=ngForm), I just ask to add it into Changelog, because I spend around 30 minutes to find it - just to save somebody's else time :)
It's good to see docs are up to date, but rereading all docs on each beta release is not an option, hehe :)

**Comment by laco0416** [comment]
No, no, no. I'm wrong. :)

![image](https://cloud.githubusercontent.com/assets/1529180/13369652/8e4bcb92-dd3a-11e5-9d94-6616d86bf059.png)

`f` is undefined. 

Fixed: [plunler](https://plnkr.co/edit/qK3ggcnTg68NBYjG36yI?p=preview)

**Comment by ericmartinezr** [comment]
@laco0416 lol... nice finding.

**Comment by laco0416** [comment]
If an error occurs in `(submit)`, angular passes `submit` event to normal form behavior (reloading).

**Comment by e-oz** [comment]
@laco0416 hah, really, and only for `(submit)`, not `(ngSubmit)`.
Well, undocumented feature, and I think content of this issue will be helpful enough for future readers.
Thank you very much, @laco0416 !

**Comment by PascalPrecht** [comment]
@laco0416 funny, I was wondering two days ago why we have `(submit)` and `ngSubmit()`, when the actual idea behind event binding was that we *don't* have to introduce our own `ng*` events. Looking at the code, there's also no difference between `ngSubmit()` and `(submit)`, both emit the same event.

However, this make sense now. Thanks everyone so so much
