### ISSUE TITLE
Angular breaks silently, mysteriously if zone shim is loaded incorrectly

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#7327]
If zones are loaded correctly, Angular can end up in a weird state where everything initially *seems* to work, but fails in subtle, mysterious ways. When loading up an app, this manifests as change detection not always running when it's supposed to (such as at app start-up). In tests, this can manifest as fakeAsync flushes seeming to do nothing. 

Incorrect loading can happen pretty easily if you load any polyfill or shim that may overwrite Angular's own zone shim (and thus angular2-polyfills.js should be loaded _after_ all other polyfills/shims). 

Angular should perform some kind of zone sanity check on bootstrap with a more informative error message.

cc @mhevery

**Comment by matthewdenobrega** [comment]
I had this recently with oidc-token-manager - a sanity check would be helpful as it's not easy to debug.

**Comment by CaptainCodeman** [comment]
I've hit this several times as well. There are so many different seed / setup projects that all do things very differently and so little definitive guidance that it's easy to get things slightly wrong and everything appears to work but the change detection is hit and miss - it's then a very bad and frustrating experience until you figure out what is happening.

**Comment by pkozlowski-opensource** [comment]
From RC5 we are getting `ReferenceError: Zone is not defined` which I think is consistent with what we get for other polyfills (Reflect, System).

**Comment by pkozlowski-opensource** [comment]
Going to close for now, let's re-open if this is still causing confusion.
