### ISSUE TITLE
Upgrade traceur to v0.0.84

### ISSUE THREAD

**Issue by caitp** [angular/angular#733]
https://github.com/google/traceur-compiler/commit/e19973caae9cf5fc24a1db881aeebdb723772544 landed which fixes a syntax error in the ES5 builds. It would be nice to pull that in

**Comment by zzo** [comment]
Also fixes a bug that transpiled:

    for (var prop in ...) {}

into

    for (var prop = void 0 in ...) {}

which is invalid es6.
There are 6 occurrences of this syntax in src/facade/collection.es6 and nowhere else.
Another 'fix' for this is to change the code in collection.es6 to read:

    var prop;
    for (prop in ...) {..}

https://github.com/google/traceur-compiler/issues/1647

**Comment by pkozlowski-opensource** [comment]
We are on traceur v0.0.87: https://github.com/angular/angular/blob/master/package.json#L36
