### ISSUE TITLE
error TS2304 cannot find name TabComponent

### ISSUE THREAD

**Issue by nhhockeyplayer** [angular/angular#7331]
Using node-5.7.0
angular2 2.0.0-beta.7

all I am doing is designing a simple composite
a TabsComponent class that houses one or more TabComponent classes

here is the parent
export class TabsComponent implements AfterContentInit {
	@ContentChildren(TabComponent) tabs: QueryList<TabComponent>;
	ngAfterContentInit() {
	}
}

here is my output

##############>gulp ts2js
[05:57:44] Using gulpfile ################\GulpFile.js
[05:57:44] Starting 'clean'...
[05:57:45] Finished 'clean' after 158 ms
[05:57:45] Starting 'less'...
[05:57:45] Finished 'less' after 422 ms
[05:57:45] Starting 'sass'...
[05:57:45] Finished 'sass' after 59 ms
[05:57:45] Starting 'ts2js'...
##############/node_modules/angular2/src/core/metadata.d.ts(367,18): error TS2304: Cannot find name 'TabComponent'.
[05:57:50] TypeScript: 1 semantic error
[05:57:50] TypeScript: emit succeeded (with errors)
[05:57:50] Finished 'ts2js' after 4.93 s
refuses to compile

**Comment by nhhockeyplayer** [comment]
here is the config
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "sourceMap": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "suppressImplicitAnyIndexErrors":false,
        "noImplicitAny": false,
        "listFiles":    true,
        "removeComments": true,
        "preserveConstEnums": true,
        "declaration": false
    },

    "exclude": [
        "typings/main",
        "typings/main.d.ts",
        "node_modules",
        "dist"
    ],

    "files": [
        "node_modules/angular2/src/core/metadata.d.ts",
        "typings/browser/definitions/es6-promise/es6-promise.d.ts"
    ],
    "fileGlobs": [
        "./app/**/*.ts"
    ],
    "compileOnSave": false,
    "buildOnSave": false
}

**Comment by zoechi** [comment]
`@ContentChildren(forwardRef(() =>TabComponent)) tabs: QueryList;` might be worth a try.

**Comment by nhhockeyplayer** [comment]
Thanks friend, that didnt work... tried several variations including any

right now I got this

	@ContentChildren(forwardRef(() =>TabComponent)) tabs: QueryList<TabComponent>;

compile error 'argument type Type is not assignable to parameter type TabComponent'

**Comment by nhhockeyplayer** [comment]
I checked out all the chatter... on this... problem clearly understood about why we need forwardRef()

nothing covers the TabComponent that lives deep in angular2

I am declaring/defining my own TabComponent and I am wondering if this is colliding with the TabComponent being referenced deep in angular2 for @ContentChildren annotation

kinda stuck...I will try to rename mine and see what gives

**Comment by nhhockeyplayer** [comment]
Here is where I am at

export class TabsComponent implements AfterContentInit {
	tab:	TabComponent;
	constructor(@Inject(forwardRef(() => TabComponent)) tab: TabComponent) {
		this.tab = tab;
	}

	//@ContentChildren(TabComponent) tabs: QueryList<TabComponent>;
	//@ContentChildren(forwardRef(() =>tab)) tabs: QueryList<TabComponent>;
	@ContentChildren(forwardRef(() =>typeof this.tab)) tabs: QueryList<TabComponent>;

still receiving same original error

**Comment by nhhockeyplayer** [comment]
well node_modules/angular2/src/core/metadata.d.ts
references a TabComponent

but none is found within angular2

did they forget to include the typedef for this ? or is the user suppose to provide their own

**Comment by zoechi** [comment]
Ups, I missed the difference `TabComponent` vs `TabComponent`. I guess you need to create and import the `TabComponent`. Not sure where you expect it to come from.

**Comment by nhhockeyplayer** [comment]
create & import ? I do that and it compiles fine.

Here is the TabComponent code

```
import { Component, Input, Output } from 'angular2/core';

import {uniqueId} from './tabs.component';

@Component({
	selector: 'tab',
	templateUrl: 'app/components/tab/tab.component.tmpl.html',
	styleUrls: ['app/components/tab/tab.component.css']
})

export class TabComponent {
	id: string = uniqueId('tab_');

	@Input('tabTitle') title: string;
	@Input() active = false;
}
```

**Comment by nhhockeyplayer** [comment]
Here is the parent

```

import { Component, Input, Output, EventEmitter, Type } from 'angular2/core';
import { ContentChildren, Query, QueryList, AfterContentInit } from 'angular2/core';

import {CORE_DIRECTIVES} from 'angular2/common';

import {TabComponent} from './tab.component';

@Component({
	selector: 'tabs',
	directives: [CORE_DIRECTIVES,TabComponent],

	templateUrl: 'app/components/tab/tabs.component.tmpl.html',
	styleUrls: ['app/components/tab/tabs.component.css']
})

export class TabsComponent implements AfterContentInit {

	id: string = uniqueId('tabs_');

	@ContentChildren(TabComponent) tabs: QueryList<TabComponent>;

	ngAfterContentInit() {
		let activeTabs = this.tabs.filter((tab)=>tab.active);	// get all active tabs

		if(activeTabs.length === 0) {		// if there is no active tab set, activate the first
			this.selectTab(this.tabs.first);
		}
	}

	selectTab(tab: TabComponent){
		this.tabs.toArray().forEach(tab => tab.active = false);	// deactivate all tabs
		tab.active = true;	// activate the tab the user has clicked on.
	}
}

let id: number = 0;
export function uniqueId(prefix: string): string {
	return prefix + ++id;
}
```

**Comment by nhhockeyplayer** [comment]
This one was a bit of a wipeout for me today... things are in such flux... comments, docs, plunks, etc...

I am going to be brave and say at face value @ContentChildren seems to be broken for beta-7

below is the result that works... after 
1. backing down to     "angular2": "^2.0.0-beta.0"
2. literally modifying node_modules/angular2/src/facade/promise.d.ts 
2.1 added declare var Promise: PromiseConstructor; to top of module
3. kept my typescript compiler rev at 1.75

pheewwww..... !!!

```

import { Component, Input, Output, EventEmitter, Type } from 'angular2/core';
import { ContentChildren, Query, QueryList, AfterContentInit } from 'angular2/core';

import {CORE_DIRECTIVES} from 'angular2/common';

import {TabComponent} from './tab.component';
import {forwardRef} from 'angular2/core';
import {ContentChild} from 'angular2/core';
import {View} from 'angular2/core';

@Component({
	selector: 'ttabs'
//	directives: [CORE_DIRECTIVES, TabComponent]
})

@View ({
	templateUrl: 'app/components/tab/tabs.component.tmpl.html',
	styleUrls: ['app/components/tab/tabs.component.css']
})

export class TabsComponent implements AfterContentInit {
	id: string = uniqueId('tabs_');

	@ContentChildren(forwardRef(() => TabComponent)) tabs: QueryList<TabComponent>;

	ngAfterContentInit() {
		let activeTabs = this.tabs.filter((tab)=>tab.active);	// get all active tabs

		if(activeTabs.length === 0) {		// if there is no active tab set, activate the first
			this.selectTab(this.tabs.first);
		}
	}

	selectTab(tab: TabComponent){
		this.tabs.toArray().forEach(tab => tab.active = false);	// deactivate all tabs
		tab.active = true;	// activate the tab the user has clicked on.
	}
}

let id: number = 0;
export function uniqueId(prefix: string): string {
	return prefix + ++id;
}

```
and here is the tab

```
import { Component, Input, Output } from 'angular2/core';

import {uniqueId} from './tabs.component';

@Component({
	selector: 'ttab',
	templateUrl: 'app/components/tab/tab.component.tmpl.html',
	styleUrls: ['app/components/tab/tab.component.css']
})

export class TabComponent {
	id: string = uniqueId('tab_');

	@Input('tabTitle') title: string;
	@Input() active = false;
}

not sure if you want this open or closed... its your call 
```

**Comment by ericmartinezr** [comment]
```
"files": [
    "node_modules/angular2/src/core/metadata.d.ts",
    "typings/browser/definitions/es6-promise/es6-promise.d.ts"
],
```
Why do you have those two files in your tsconfig.json? You don't need them at all in there.

**Comment by naomiblack** [comment]
Please move requests for support to other channels. See https://angular.io/support.html
