### ISSUE TITLE
loadIntoLocation example from the API docs does not work

### ISSUE THREAD

**Issue by ntrrgc** [angular/angular#7334]
Here is a plunkr using the example code shown in the API docs for [DynamicComponentLoader.loadIntoLocation](https://angular.io/docs/ts/latest/api/core/DynamicComponentLoader-class.html):

    @Component({
      selector: 'child-component',
      template: 'Child'
    })
    class ChildComponent {
    }
    @Component({
      selector: 'my-app',
      template: 'Parent (<div #child></div>)'
    })
    class MyApp {
      constructor(dcl: DynamicComponentLoader, elementRef: ElementRef) {
        dcl.loadIntoLocation(ChildComponent, elementRef, 'child');
      }
    }
    bootstrap(MyApp);

Running it throws these errors:

![Error: There is no component directive at element [object Object]](http://i.imgur.com/IwVLtyZ.png)

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/pull/7186

**Comment by ntrrgc** [comment]
I see. Thanks for the quick reply.

This code indeed works:
```
@Component({
  selector: 'child-component',
  template: 'Child'
})
class ChildComponent {
}

@Component({
  selector: 'my-app',
  template: 'Parent (<div #child></div>)'
})
class MyApp implements OnInit {
  constructor(
    private _dcl: DynamicComponentLoader, 
    private _elementRef: ElementRef) 
  { }
  
  ngOnInit() {
    this._dcl.loadIntoLocation(ChildComponent, this._elementRef, 'child');
  }
}

bootstrap(MyApp);
```

https://plnkr.co/edit/lu25nVaA8Zqxcp2sFlje?p=preview

**Comment by pkozlowski-opensource** [comment]
`DynamicComponentLoader` is depreciated, closing as obsolete.
