### ISSUE TITLE
feat(QueryList): update list on demand

### ISSUE THREAD

**Issue by ericmartinezr** [angular/angular#7336]
Currently the only way to trigger an update on QueryList is using an ngFor, QueryList#reset and probably others way I'm not aware of.

What I'm doing is adding elements dynamically into a component's view using Renderer#createElement. The problem is that QueryList has no idea that I did add an element that satisfies a directive.

To be more clear  here's a [plnkr](http://plnkr.co/edit/YLq0PoHgnSvpOFWP3MEp?p=preview).

As you see in the plnkr I have a view with only a button that add inputs when is clicked. I want the ViewChildren to be triggered (viewchildren.changes, etc) when I add a new input, but rechecking the view everytime sounds to be a really heavy task, so I was thinking of a `update()` method for QueryList, so I can do `QueryList.update()` to get the list with the inputs it found in the view.

```typescript
@Directive({ selector : 'input' })
class Input {}

@Component({
  selector: 'my-app',
  directives : [Input]
})
export class App {
  @ViewChildren(Input) inputs;
  
  ngAfterViewInit() {

    // Hopefully this would be triggered by "update()"
    this.inputs.changes.subscribe(q => console.log(q));
  }
  
  addElement() {
    let element = this._renderer.createElement(this._elementRef.nativeElement, 'input');
    this._renderer.setElementAttribute(element, 'type', 'text');
    
	// I know I've added an input by now so I want to recheck it looking for the new inputs
	this.inputs.update(); // Maybe ???
  }
}
```

If I'm missing something and this is already possible I would appreciate any comment about it (not using ngFor, of course). Thanks :smile:

**Comment by laco0416** [comment]
Any way to re-query view is necessary, but `update()` is not intuitive. I think `refresh()` or `reload()` makes more sense.

My picture:

```ts
  addElement() {
    let element = this._renderer.createElement(this._elementRef.nativeElement, 'input');
    this.inputs.reload().then((newList) => { // re-querying should return Promise.
      ...
    });
  }
```

**Comment by zoechi** [comment]
To me this looks like adding HTML with `[innerHtml]="something"` which doesn't result in any directives, components, or  template variables to be applied. 
I tried it in your Plunker and `Input` is not instantiated, therefore `this.inputs.update();` wouldn't find these inputs anyway. 
Would be interesting if adding components added by DCL are found.

**Comment by ericmartinezr** [comment]
@laco0416 the name is up to discussion (not naming again :joy:), but that's the point. 

@zoechi exactly, that's why I want this, to the directive/component to be instantiated/rechecked when we call `update()`, `refresh()`, or whatever.

**Comment by zoechi** [comment]
My point is that there are no components to query if you add HTML this way. Check if any directive or component is actually instantiated.
