### ISSUE TITLE
Angular 2 typings in Visual Studio 2015 (ASP.NET 4)

### ISSUE THREAD

**Issue by Gaulomatic** [angular/angular#7337]
Before integrating the definitions to the package directly including those into a ASP.NET 4 project that uses SystemJS was really easy: Just put the file from DefinitelyTyped into the project, do an `import * as ng from 'angular2/angular2'` in a TypeScript file and everything worked fine. This doesn't fit anymore (in my case), since there is no single `.d.ts` file with all definitions.

When I was using the import statement above, the `'angular2/angular2'` (path and JS file) was resolved by SystemJS and Visual Studio knew about it because of the definition file that was declaring a module. How do I achieve that Visual Studio will know about that again? I tried many hours without success, except using the old Alpha stage `.d.ts` file and changing it slightly to declare it as `angular2/core`.

How can this problem be resolved without using the new project system of ASP.NET 5?

**Comment by alexeagle** [comment]
`angular2/angular2` is no longer an import location. The typings should be discovered by the compiler by looking in your `node_modules/angular2` directory.
If you're using `--module=system` then you need `--moduleResolution=node` to make the discovery work.
(that's the default when using `--module=commonjs` which is why it's not documented everywhere)

**Comment by Gaulomatic** [comment]
I am working with JSPM to manage packages, so i have no `node_modules` folder.

**Comment by alexeagle** [comment]
We only distribute typings via NPM right now, so you'd have to fetch a copy of angular2 from NPM even if you don't plan to use any of the `.js` files in the distribution. https://github.com/angular/angular/issues/5796 is the issue for distributing a standalone typescript typings.

'moduleResolution' is a TypeScript option, see https://github.com/Microsoft/TypeScript/wiki/Compiler-Options
Typically you'd add that in a `tsconfig.json` file.

**Comment by Gaulomatic** [comment]
I could manage it for development time very simply. I just copied the `angular2` and `rxjs` folders to the root of the web project, Visual Studio will automatically pick those up and provides IntelliSense and compiles the TypeScript correctly. At runtime the duplication doesn't matter because they are needed only for VS compilation of the TypeScript files and angular2, which is managed by JSPM, will be loaded by SystemJS.
