### ISSUE TITLE
Response.type is integer expected string.

### ISSUE THREAD

**Issue by Maks3w** [angular/angular#7338]
https://fetch.spec.whatwg.org/#concept-response-type

> A response has an associated type which is "basic", "cors", "default", "error", "opaque", or "opaqueredirect". Unless stated otherwise, it is "default".

Type is defined as an enum type in https://github.com/angular/angular/blob/master/modules/angular2/src/http/enums.ts#L34

But TypeScript use the enum index (integer)

```typescript
let response = new Response(new ResponseOptions({body: err, type: ResponseType.Error});

response.type == "error"; // False, response.type = 3
```
https://github.com/angular/angular/blob/master/modules/angular2/src/http/backends/xhr_backend.ts#L70-L74

Line to fix: https://github.com/angular/angular/blob/master/modules/angular2/src/http/static_response.ts#L81

Example of fix:
https://github.com/angular/angular/blob/master/modules/angular2/src/http/static_request.ts#L80
https://github.com/angular/angular/blob/master/modules/angular2/src/http/http_utils.ts#L17

**Comment by robwormald** [comment]
yep, agreed. previous to TS 1.8 we didn't have any way to do string based enums, but now we can, so we'll move all the index based enums to this style.

**Comment by robwormald** [comment]
opened in Http as https://github.com/angular/http/issues/85, closing this one.
