### ISSUE TITLE
Forms - Allow an array of ControlGroups

### ISSUE THREAD

**Issue by intellix** [angular/angular#7340]
I'm trying to create a sort of CMS for our content team to populate spaces of a page based on a template we define. I'd like to create a form structure that looks like:

```javascript
constructor(fb: FormBuilder) {
  this.myForm = fb.group({
    key: ['', Validators.required],
    name: ['', Validators.required],
    fields: fb.array([
      fb.group({
        label: ['Titles', Validators.required],
        type: ['text', Validators.required],
        required: ['true', Validators.required]
      }),
      fb.group({
        label: ['CTAs', Validators.required],
        type: ['button', Validators.required],
        required: ['true', Validators.required]
      }),
    ])
  });
}
```

but it seems like a ControlArray can only accept Controls, which means I'm limited to an array of singular values.

I've managed hack around it by storing an extra array of ControlGroups on the class itself and checking for validity like so, but it's starting to get really painful as my form structure gets deeper:

```js
get isValid() {
  return this.myForm.valid && this.myFormFields.every((fGroup) => {
    return fGroup.valid;
  });
}
```

**Comment by IHateGlamour** [comment]
Cannot check right now, but Isn't it an array of AbstactControls, and not controls? in beta.0:
```
export declare class ControlArray extends AbstractControl {
controls: AbstractControl[];
    ...
}

```

**Comment by intellix** [comment]
Ahah, you're right. After playing with the ControlArray example a little bit, I can see that it's entirely possible and even working with my fork: http://plnkr.co/edit/pZv32C?p=preview
I suppose this can be closed and would be good to update the example to show both usages :)
Thanks
