### ISSUE TITLE
Missing ControlValueAccessor for file input

### ISSUE THREAD

**Issue by Maks3w** [angular/angular#7341]
I notice there is no control value accesor for inputs of type "file"

**Comment by zoechi** [comment]
See http://stackoverflow.com/questions/5903323/cant-get-value-of-input-type-file
probably dup of #6962

**Comment by PascalPrecht** [comment]
@Maks3w There's in fact no value accessor for that file type. We can't set values that way. @vsavkin the interface requires a `writeValue()` method, how do we want to deal with this? Make it optional? Or would `input[type="file"]` be so special that it'd simply return a `not implemented` error?

@zoechi how is #6962 related to this one...?

**Comment by zoechi** [comment]
@PascalPrecht sorry dup was the wrong relation.  It was mentioned there that a file input doesn't  have a `value` field.

**Comment by Maks3w** [comment]
I agree is not possible to set a default value. But the field has a value.

For example SelectControlValueAccesor stores the value in an internal variable
https://github.com/angular/angular/blob/master/modules/angular2/src/common/forms/directives/select_control_value_accessor.ts#L53-L61

So I think could be possible achieve similar behavior using the filelist provided by the input

**Comment by ericmartinezr** [comment]
@PascalPrecht we can simply pass `target.files` through onChanges, the problem is that 99,9% value accessors require the property value while files use `files`, I have a custom [file value accessor](http://plnkr.co/edit/POw5WGkA7GMyTJOmefKP?p=info). There are a few details to have in consideration that are not part of this issue, but I think the idea is pretty simple to implement.

**Comment by Maks3w** [comment]
I've write this Gist with an implementation https://gist.github.com/Maks3w/8a02cc0f7745335695f3

**Comment by asnowwolf** [comment]
I met this issue too, I think the root cause is the `input[file]`'s change event won't trigger change detection. so, maybe it's a issue of Zones.

**Comment by TeodorKolev** [comment]
still?

**Comment by stevenrobijns** [comment]
Check my answer [here ](https://stackoverflow.com/a/41938495/5413117) for a full working example + explanation

**Comment by stevenrobijns** [comment]
Check my answer [here ](https://stackoverflow.com/a/41938495/5413117) for a full working example + explanation

**Comment by mildfuzz** [comment]
Thanks @stevenrobijns 

Why is this still not part of core?

**Comment by dalu** [comment]
It's not clear what the current status of this is and I came here from a Google search trying to find out about "angular multipart/formdata -angularjs"

**Comment by mfish0005** [comment]
@dalu Same here.  Have been trying to figure out how to POST a JSON object as multipart/formdata in Angular 5 for about 4 hours now.

**Comment by Brachacz** [comment]
> @dalu Same here. Have been trying to figure out how to POST a JSON object as multipart/formdata in Angular 5 for about 4 hours now.

Have you resolved the issue?
I'm trying to send a file using multipart/form-data

**Comment by Brachacz** [comment]
I resolved my issue, I had used `FormData` before.

Actually it was the classic 'hide in plain sight' gotcha - I set `FormData` key to something else than what backend expected ;)

**Comment by KostyaTretyak** [comment]
Hi guys. In my [@ng-stack/forms](https://github.com/KostyaTretyak/ng-stack/tree/master/projects/forms) I also used "classic" approach with using `FormData` to upload files, but there are several profits:

- by default, in `formControl.value` we have instance of `FormData`, but with attribute `valueAsFileList` you can works with `FileList`
```html
<input type="file" valueAsFileList [formControl]="formControl">
```
- automatically retrieve form input name, e.g. `<input type="file" name="someName">` -> `formControl.value` with `someName` file name;
- support `multiple` attribute with properly setting field name (note `userpic[]` here)
```html
<input type="file" multiple name="userpic" [formControl]="formControl">
```
```ts
formData.append('userpic[]', myFileInput.files[0]);
formData.append('userpic[]', myFileInput.files[1]);
```
- `Validators` have four static methods for files
```ts
import { Validators } from '@ng-stack/forms';

Validators.fileRequired;
Validators.fileMaxSize(1024);
Validators.fileMaxLength(10);
Validators.fileMinLength(2);
```

**Comment by dylhunn** [comment]
I don't think we have seen sufficient demand for this feature to justify the whole new class and significant bundle size increase. This is also easily implemented with a custom CVA -- there are few options on npm, and in the comments above.
