### ISSUE TITLE
CanActivate is called on child before parent

### ISSUE THREAD

**Issue by nicolashenry** [angular/angular#7342]
I think the parent "CanActivate" should be tested before the child "CanActivate" in this case :

```typescript
@CanActivate(() => new Promise(resolve => {
  console.log('child canactivate');
  setTimeout(() => resolve(true), 1000);
}))
@Component({
  selector: 'child',
  template: 'Child template'
})
class Child { }

@CanActivate(() => new Promise(resolve => {
  console.log('parent canactivate');
  setTimeout(() => resolve(true), 1000);
}))
@Component({
  selector: 'parent',
  template: '<router-outlet></router-outlet>',
  directives: [RouterOutlet]
})
@RouteConfig([
  {path: '/',   name: 'Child',     component: Child}
])
class Parent { }

@Component({
  selector: 'root',
  template: '<router-outlet></router-outlet>',
  directives: [RouterOutlet]
})
@RouteConfig([
  {path: '/...',   name: 'Parent',     component: Parent}
])
export class AppComponent { }
```
The result is :
```
child canactivate
parent canactivate
```
I think it should be :
```
parent canactivate
child canactivate
```

**Comment by wardbell** [comment]
Why is that better?

**Comment by laco0416** [comment]
I think the current behavior is smarter than @nicolashenry 's idea.

Parent state depends on states of all children. When one component of the children cannot be active, its parent also cannot be. So, it's not wrong that angular checks children at first.

**Comment by btford** [comment]
Agree with @wardbell and @laco0416

**Comment by nicolashenry** [comment]
@wardbell, @laco0416, @btford 
Ok, I should be wrong in my approach :
For example, with this path "/car/:carId/wheel/:wheelId", if my parent @CanActivate is testing is if the user can see the Car identified by "carId" and the child one is testing if the user can see the Car wheel identified by "wheelId", I think it's strange to test if the user can see the wheel if he should not see the car anyway.
How could I prevent the parent to do a useless call to the child @CanActivate in this case ?

**Comment by nicolashenry** [comment]
@laco0416 I would rather say that "States of all children depends on parent state." and "When parent component cannot be active, its chrildren also cannot be", where I am wrong here ?

**Comment by lppedd** [comment]
Absurd this is still an issue.
