### ISSUE TITLE
Support named optional parameters in @Injectable ctors

### ISSUE THREAD

**Issue by kegluneq** [angular/angular#7344]
Right now, named optional parameters do not work in `@Injectable` ctors, but maybe they should.

* Should a named optional parameter be implicitly annotated as `@Optional`?

**Comment by langley-agm** [comment]
+1

**Comment by langley-agm** [comment]
Is there any reason for closing this?

**Comment by zoechi** [comment]
@langley-agm because Dart issues are now maintained in dart-lang/angular2
