### ISSUE TITLE
Remove unnecessary `isPresent` checks from `SelectorMatcher._addSelectable()`

### ISSUE THREAD

**Issue by chuckjaz** [angular/angular#7348]
Either many of the calls to `isPresent` in `_addSelectable()` are redundant or there needs to be more of them.

Assume `cssSelector.attrs` is `undefined` on enter to the function and `cssSelector.element` is defined, the following line will throw `var isTerminal = attrs.length === 0 && classNames.length === 0` which is the first line of the `isPresent(element)` case.

Later the function guards access to `attrs` with `isPresent(attrs)`.

Either the `isPresent(attrs)` guard is necessary for accessing `attrs` or `isPresent(attrs)` is a precondition of the function making the `isPresent(attrs)` guard unnecessary. 

The `isPresent(classNames)` guard is the same.

**Comment by vicb** [comment]
see https://github.com/angular/angular/pull/11906
