### ISSUE TITLE
feat: routerCanDeactivate must prevent/ nullify browser history manipulations by itself.

### ISSUE THREAD

**Issue by dabalyan** [angular/angular#7351]
While implementing `routerCanDeactivate` I figured that on triggering any `history` event 
i.e: clicking browser's back/forward button, backspace

returning `false` does prevent navigation but it doesn't keep the `history` intact.

Which means if I return false at least one time before returning true then
it will not navigate to the previous page like it was supposed to instead
it would be like `history.go(COUNT_OF_FALSE_RETURNS_BEFORE_RETURNING_TRUE)`
because `history` is changed by back/forward calls while view is the same.

And once it's down to the first state in history it would lose the view also and navigate to the browser's homepage.

**Comment by dabalyan** [comment]
```
routerCanDeactivate(nextInstruction: ComponentInstruction, prevInstruction: ComponentInstruction) {
    if(confirm("Do you want to discard unsaved changes ?")){
      return true;
    }
    else {
      history.forward();
      return false;
    }
  }
```

This is the closest I could get to nullify the history manipulations, but it handles only `history.back()` calls effectively, if `history.forward()` is triggered it would fail to nullify it. 

It would be nice if **routerCanDeactivate** handles this by itself.

**Comment by vicb** [comment]
obsolete
