### ISSUE TITLE
Proper workflow to use a polymer component inside Angular2

### ISSUE THREAD

**Issue by roby2001** [angular/angular#7354]
I'm trying to get a polymer component to work inside my Angular 2 App but I keep getting the error : ` Maximum call stack size exceeded on angular2-pollyfills`. I saw a few issues about it but didn't really realize how to fix it from them.

**Comment by PascalPrecht** [comment]
@roby2001 can you setup a punkr or jsfiddle that demonstrates your concrete example?

**Comment by zoechi** [comment]
The discussions in #5980 or #5964 are about the same error maybe they provide some information.

**Comment by roby2001** [comment]
@PascalPrecht Not really atm, but I'm using http://blog.edenmsg.com/angular2-typescript-gulp-and-expressjs/ for the base project and I just tried to import a simple polymer component with link ref in which I literally have the simplest polymer component I could've tought of.

**Comment by roby2001** [comment]
@PascalPrecht , http://plnkr.co/edit/etQwN1uYvfLmlyCu5x1L?p=preview . Without Angular2-pollyfills I don't get the Maximum call stack but I get ` reflect-metadata shim is required when using class decorators
	Error loading http://localhost:3000/app/bootstrap.js ` .If i try to add import zonejs and reflect-metadata I get the stack error again. I can't seem to figure out what to remove, or what to add in order to make it work properly.

**Comment by zoechi** [comment]
http://plnkr.co/edit/1Gx2G2utKwgnNFvf0I8c?p=preview
http://plnkr.co/edit/kMuyWiNfDwrLSSc3JGDx?p=preview

**Comment by roby2001** [comment]
@zoechi  I've tried to copy your plunkers but now I just seem to get errors for everything/anything angular related : http://prntscr.com/aa7rh2. If I remove the authentification component I just get some other errors. Here is the old index file that works :  https://plnkr.co/edit/7J8smmZM1qmtkauv3Qjj?p=catalogue
                     And here is the new index file that does not work : https://plnkr.co/edit/df9wlftK2PLF6g2OoFrg?p=catalogue

**Comment by zoechi** [comment]
I provided some guidance but I'm not too interested in that topic. I don't see how the exception in your screenshot is related. Seems you need to add some providers somewhere. Maybe someone else will have a closer look.

Besides that

GitHub issues are for bug reports and feature requests. 
      For support questions please use other channels like [StackOverflow](http://stackoverflow.com/questions/tagged/angular2), [Gitter](https://gitter.im/angular/angular), [Google groups](https://groups.google.com/forum/#!forum/angular), ...

**Comment by naomiblack** [comment]
Closing. Please do move discussion to support channels.
