### ISSUE TITLE
Get instance of Component after dynamicComponentLoader

### ISSUE THREAD

**Issue by chinookproject** [angular/angular#7355]
I'm using  `DynamicComponentLoader` to dynamically insert a component in my view. I have that working. Now I also want to call a method on  the loaded component. But I can't figure out how to do that.

Basically what I have now is this:

1st step:
```
class MainComponent {
    constructor( ... ) {

        // load component dynamically and inject into DOM
        var obj = this.dynamicComponentLoader.loadAsRoot(BaseElementSettings, '#field'+id, this.injector);

        // call method in injected component class
        obj.renderElement('something'); // <--- ERROR
    }
}
```

2nd step:
```
class BaseElementSettings {
    constructor() {
    }

    // Want to call this method from MainComponent class
    public renderElement(elementType:string) {
        console.log(elementType);
    }
}
```

How can I call the `renderElement()` method after the component is loaded through `dynamicComponentLoader.loadAsRoot()`?

**Comment by zoechi** [comment]
```ts
var obj = this.dynamicComponentLoader.loadAsRoot(BaseElementSettings, '#field'+id, this.injector).then(cmp => {
  cmp.instance....
});
```

GitHub issues are for bug reports and feature requests. 
      For support questions please use other channels like [StackOverflow](http://stackoverflow.com/questions/tagged/angular2), [Gitter](https://gitter.im/angular/angular), [Google groups](https://groups.google.com/forum/#!forum/angular), ...

**Comment by chinookproject** [comment]
Sorry, will keep that in mind next time. Thanks for the answer.
