### ISSUE TITLE
@Input decorator bug

### ISSUE THREAD

**Issue by kisdaniel** [angular/angular#7361]
Hi,

I have created a parent class and created a child for it. I have added a property with @input annotation to a parent class. Type of the property was a FiledValidator: 

```
export interface FieldValidator {
    validate(inputValue: string): FieldValidationResult;
}


export abstract class AbstractBootstrapInput {

   @Input("validator")
    public set validator(newValue: FieldValidator) {        
        this.fieldValidator = newValue;
        if(!this.fieldUnchanged) {
            this.validate.emit(this.fieldValidator.validate(this.inputValue));
        }
    }


    public get validator(): FieldValidator {
        return this.fieldValidator;
    }
}

@Component({
    selector: 'bs-text-input'
})
@View({
    templateUrl: "templates/component-form-text-input.html",
    directives: [NgModel]
})
@Inject(BootstrapFormGroup)
export class TextInput extends AbstractBootstrapInput {
    
    ...
                
    constructor(@Optional() formGroup: BootstrapFormGroup) {
    }
}
```

The child is  a component and when I tried to use it does'n bind the validator property:

```
<bs-form-group [label]="'login.userName' | translate">
                <bs-text-input [validator]="userNameValidator"
                               [value]="userName"></bs-text-input>
</bs-form-group>
```

but when I move the validator to child class It binds the property and works. How can I define validator in parent class?

**Comment by zoechi** [comment]
When you use data binding the `@Input()` has to be on the child (`TextInput`) not on the parent. 

` <bs-text-input [validator]="userNameValidator"` ...>` would require 
```
export class TextInput ... {
   @Input() validator;
}
```
and a field `userNameValidator` on the parent.

This line is also redundant
```
@Inject(BootstrapFormGroup)
```

GitHub issues are for bug reports and feature requests. 
      For support questions please use other channels like [StackOverflow](http://stackoverflow.com/questions/tagged/angular2), [Gitter](https://gitter.im/angular/angular), [Google groups](https://groups.google.com/forum/#!forum/angular), ...

**Comment by kisdaniel** [comment]
I think you misunderstand the problem. If I put the @Input to TextInput as I mentioned in question, it works.
 TextInput is an AbstractBootstrapInput so why I cannot put @Input decorated property to AbstractBootstrapInput class?

**Comment by zoechi** [comment]
Your question wasnt entirely clear to me. Maybe you mean subclass and superclass instead of parent snd child. 

dup of #5415?

**Comment by pkozlowski-opensource** [comment]
It is indeed dup of #5415, thnx @zoechi
