### ISSUE TITLE
Passing ngControl inside a form template throw an error

### ISSUE THREAD

**Issue by remohy1** [angular/angular#7362]
`import {Component, View, EventEmitter, ElementRef, OnInit, ContentChild, AfterContentChecked, NgForm} from 'angular2/core';
import {ROUTER_DIRECTIVES, RouteConfig, Router, Location, Route, RouteData, RouteParams} from 'angular2/router';
import {FORM_DIRECTIVES, FORM_BINDINGS,FORM_PROVIDERS, NgFormModel, ControlGroup, Control, Validators, CORE_DIRECTIVES} from 'angular2/common';

import {TimerWrapper} from 'angular2/src/core/facade/async';

@Component({
    selector: 'bfm-form',
    templateUrl: 'app/common/form/bfmForm.html',
    styleUrls: ['app/common/form/bfmForm.css'],
    inputs: ['title', 'width'],
    providers: [
                    FORM_PROVIDERS
                ],
     directives: [Field, BFMForm, FORM_DIRECTIVES, Alert, CORE_DIRECTIVES, NgFormModel],
     bindings: [FORM_BINDINGS]
    //outputs: ['closed']
})
export class BFMForm implements OnInit, AfterContentChecked{
    title:string = 'test';
    width: number;
    //closed: EventEmitter<any> = new EventEmitter();
    constructor(private el : ElementRef) {
        
    }
    
    ngOnInit() {
       //this.el.nativeElement.getElementsByTagName('input')[0].className = "form-control";
    }
    ngAfterContentChecked(){
            
    }
    
    onSubmit(){
        console.log('sub');
    }
}
BFMForm.parameters = [[ElementRef]]`

Here is bfmForm.html

`<form>
	<ng-content></ng-content>
	<button id="save" class="btn btn-success" type="submit">Save</button>
</form>`

Now when I consume this:

`import {Component, OnInit} from 'angular2/core';
import {NgForm}    from 'angular2/common';
import {HTTP_PROVIDERS}    from 'angular2/http';
import {FORM_DIRECTIVES, FORM_BINDINGS,FORM_PROVIDERS, NgFormModel, ControlGroup, Control, Validators, CORE_DIRECTIVES} from 'angular2/common';

import {BFMForm} from '../../common/form/bfmForm'

@Component({
    selector: 'application-form',
    template: '<bfm-form>
	<input type="text" [(ngModel)] = "application.useBeastId" required ngControl="name" #name="ngForm"/>
</bfm-form>',
    styleUrls: ['app/forms/application/applicationform.css'],
     providers: [
                    HTTP_PROVIDERS,
                    FORM_PROVIDERS
                ],
     directives: [BFMForm, FORM_DIRECTIVES, CORE_DIRECTIVES],
     bindings: [FORM_BINDINGS],
     inputs: ['application']
})

export class ApplicationForm implements OnInit{
    application;
    constructor() {
       
    }
    
    onSubmit() { 
        
    }
    
    ngOnInit(){
       if (this.application == null){
            this.application = {
            }    
       }
    }
    
}
`

I get an error:

EXCEPTION: No provider for ControlContainer! (NgControlName -> ControlContainer) in [showAddEdit in Home@36:32]

**Comment by zoechi** [comment]
Can you please edit your comment and wrap the code in ``` to make it more readable.

```
directives: [Field, BFMForm, FORM_DIRECTIVES, Alert, CORE_DIRECTIVES, NgFormModel],
bindings: [FORM_BINDINGS]
```
`FORM_DIRECTIVES` and `CORE_DIRECTIVES` don't need to be added anymore. `NgFormModel` is already included in `FORM_DIRECTIVES`.
`bindings` were renamed to `providers` and `FORM_BINDINGS` also don't need to be added.

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests. 
      For support questions please use other channels like [StackOverflow](http://stackoverflow.com/questions/tagged/angular2), [Gitter](https://gitter.im/angular/angular), [Google groups](https://groups.google.com/forum/#!forum/angular), ...

**Comment by remohy1** [comment]
I think this needs to be re-opened. This is not a support request, it is a feature request. ng-content need to support using ngControl. 

I updated the code section and provided a plnkr example to the issue

**Comment by rbriank** [comment]
Yes, please! I've been looking for a way to have sub-components be part of a form including validations and on matter which way I slice it, I end up with the same error too.

**Comment by littlebeeper** [comment]
Hi,

I've run into this issue as well. The trick is to use [ngFormModel] on a div tag to wrap around input fields with ngControl.
Then pass that ControlGroup object to parent ControlGroup. 
So the fix for the example code shoulde be like below; 

 ```
<div>
      <h2>Hello {{name}}</h2>
      <frm [controlGroupContent]="childForm">
           <div [ngFormModel]="childForm">
               <input [(ngModel)] = "name" ngControl="inp" />
           </div>
      </frm> 
    </div>
```
There is also new tutorial available on the angular site. 
It should give you a better idea.

**Comment by mburger81** [comment]
@remohy1  @rbriank I have the same problem, did you found a solution?
