### ISSUE TITLE
Proposal: Drop @View decorator

### ISSUE THREAD

**Issue by tbosch** [angular/angular#7363]
Initially we thought that we want to support multiple templates per component, switching between them based on the the device the application is running.

But:

- we never implemented this switching, as it needs to be done during compilation already
- switching views is probably not enough, as different environments use different libraries, i.e. different `import` statements that are mutually exclusive.

**Comment by mlaval** [comment]
For me, there is a need to be able to build one application for various platforms or renderers.
The switch should be doable:
- at compilation time for a specific target, e.g. mobile web or iOS with React Native
- at run time to enable adaptive design

I fully agree that `@View` is not enough, for example the router should be involved too.
But it seemed that it would a good first step.

**Comment by L1ghtm4n** [comment]
@mlaval I am curious, why isn't a ngIf or ngSwitch enough to switch between templates?

**Comment by PascalPrecht** [comment]
@jpleclerc you'd still ship both templates which can be a problem on mobile.

@tbosch is there at least an alternative?

**Comment by tbosch** [comment]
We have to think about this problem more.
However, as we are currently not supporting multiple @View decorators we
should drop it.

We might add something similar later when we know exactly how this should
work...

**Comment by laco0416** [comment]
`ViewMetadata` will be dropped too?

**Comment by mhevery** [comment]
https://github.com/angular/angular/pull/7495

**Comment by ericmartinezr** [comment]
@laco0416 I think it should be removed as well, see this piece of code https://github.com/angular/angular/blob/master/modules/angular2/src/core/linker/view_resolver.ts#L97-L101 , the error message keeps referencing `@View`.

**Comment by mhevery** [comment]
@btford can you fix the error message: https://github.com/angular/angular/blob/master/modules/angular2/src/core/linker/view_resolver.ts#L97-L101 ,

**Comment by chrisnicola** [comment]
@PascalPrecht @mlaval this seems to me like it would very solve-able at build with a tool like webpack.

**Comment by pkozlowski-opensource** [comment]
`@View` was dropped long time ago so closing this one. We will need to think about multiple templates per component in the future but this is whole different issue.
