### ISSUE TITLE
How to update parent's variable from child's component?

### ISSUE THREAD

**Issue by anyatran** [angular/angular#7366]
I want to be able to modify parent's variable from child's component. I'm already using @Input in child for getting parent's variable but when i update it, I can see changes only in child's component but not in parent

**Comment by zoechi** [comment]
If you add an `@Output()` to the child you can bind the other direction child->parent as well
https://angular.io/docs/ts/latest/guide/template-syntax.html

GitHub issues are for bug reports and feature requests. 
      For support questions please use other channels like [StackOverflow](http://stackoverflow.com/questions/tagged/angular2), [Gitter](https://gitter.im/angular/angular), [Google groups](https://groups.google.com/forum/#!forum/angular), ...

**Comment by pkozlowski-opensource** [comment]
@zoechi is right - child components should raise events on which a parent could act. And he is very right about GitHub not being a support forum :-)
