### ISSUE TITLE
NgFormControl memory leak

### ISSUE THREAD

**Issue by mgreenland** [angular/angular#7368]
It looks like a few of the form directives keep circular references to each other and so can't be GC'ed.

Given these two components:

```dart
@Component(
    selector: 'form',
    directives: const [FORM_DIRECTIVES],
    template: r'''
<input [ngFormControl]="control">
''')
class FormComponent {
  final control = new Control();
}

@Component(
    selector: 'memory-test',
    directives: const [NgIf, FormComponent],
    template: r'''
<button (click)="show = !show">toggle</button>
<br />
<form *ngIf="show"></form>
''')
class MemoryTestComponent {
  bool show = false;
}
```

If I toggle the form on and off, and then take a heap snapshot using Chrome's devtools, it looks like instances of NgFormModel (among other things) pile up in memory:

![heap](https://cloud.githubusercontent.com/assets/602239/13451328/f1a44a92-dff2-11e5-8f42-066324290e25.png)

There are a bunch of circular references going on here; for instance:

- NgFormControl holds a reference to the value accessor directive (DefaultValueAccessor)
- DefaultValueAccessor holds onto its ElementRef
- ElementRef holds onto its parent AppView
- AppView holds on to the FormComponent instance
- FormComponent holds the actual Control
- Control holds onto the original NgFormControl in its onChange closure

This seems to mainly be a problem when using Dart (transformer-generated code behaving slightly differently than reflection?). I gave something similar a shot in TypeScript and it looks like a change detector ends up hanging around, but nothing else: http://plnkr.co/edit/JjLQ1lwsdc88TQJXx5Zh?p=preview

**Comment by naomiblack** [comment]
Also filed as internal issue b/27547292
