### ISSUE TITLE
Poposal: URLSearchParams - additional constructor with object param

### ISSUE THREAD

**Issue by Qszer94** [angular/angular#7370]
Hello,
Why there is no constructor which allows us to pass Object as parameter in URLSearchParams class ?
At least there is nothing documented in the api yet.

I can navigate by routes like:
`router.parent.navigate(["Users", {"id": "10", "name" : "John,Martin"});`

Then if I inject RouteParams to component constructor I can read all params like:

```
params = routeParams.params
// params =  {"id": "10", "name" : "John,Martin"}
```

But I can't simply pass my routeParams to http request and I have to iterate through all params and add them manually using set method like in example below:

``` TS
    getData(params) { // params =  {"id": "10", "name" : "John,Martin"}
        let searchParams = new URLSearchParams();
        for (let param in params) {
            searchParams.set(param, params[param]);
        }

        let options = new RequestOptions({
            search: searchParams
        });

        return this.http.get(this.myUrl, options)
            .map(res => <MyClass[]> res.json())
            .catch(this.handleError)
    }
```

It is nothing, but in my opinion it would be great if it were available additional constructor of URLSearchParams class:
`constructor(objParams?: Object)`
or additional string property in RouteParams class which will store route search query like:
`"?id=10&name=John,Martin"`

Am I right ? Maybe I'm doing something wrong and there is a better way to pass search query from url to http request ?

**Comment by kentongray** [comment]
this is definitely one thing that i'm seeing when porting an angular 1 app that seems backwards, even if there was a `UrlSearchParams.setFromObject()` that would be nice

**Comment by wardbell** [comment]
This seems to me to be more an `http` issue than a router request.

I like the idea. Meanwhile, your code can be made somewhat nicer in TypeScript/ES6 with destructured assignment
```
  let params =  {"id": "10", "name" : "John"};

 ...
  var {id, name} = params;
  let url = `some/${id}/place/${name}`

  return this.http.get(url) ...

```

**Comment by damiandennis** [comment]
I have this as a utility might help someone ...

```javascript
import {isPrimitive} from "angular2/src/facade/lang";
/**
 * Converts an object to a parametrised string.
 * @param object
 * @returns {string}
 */
export default function objectToParams(object)
{
    return Object.keys(object).map((value) => {
		var objectValue = isPrimitive(object[value]) ? object[value] : JSON.stringify(object[value]);
		return `${value}=${objectValue}`;
	}).join('&');
}
```

**Comment by wardbell** [comment]
That sees useful to for the query portion

**Comment by ZeBigDuck** [comment]
Thank you @damiandennis for your function,
I made my own objectToParams function based on your, this one allows to encode objects recursively :

```ts
import {isJsObject} from 'angular2/src/facade/lang';

/**
 * Converts an object to a parametrised string.
 * @param obj
 * @returns {string}
 */
export function objectToParams(obj): string {
    return Object.keys(obj).map((key) => isJsObject(obj[key]) ?
        subObjectToParams(encodeURIComponent(key), obj[key]) :
        `${encodeURIComponent(key)}=${encodeURIComponent(obj[key])}`
    ).join('&');
}

/**
 * Converts a sub-object to a parametrised string.
 * @param obj
 * @returns {string}
 */
function subObjectToParams(key, obj): string {
    return Object.keys(obj).map((childKey) => isJsObject(obj[childKey]) ?
            subObjectToParams(`${key}[${encodeURIComponent(childKey)}]`, obj[childKey]) :
            `${key}[${encodeURIComponent(childKey)}]=${encodeURIComponent(obj[childKey])}`
    ).join('&');
}
```

Usage example :
```ts
let params = {
    order: {
        values: {
            alphabetically: 'ASC',
            arr: [ 'A', { thisIs: 'B' } ]
        }
    },
    filter: 'test'
};

objectToParams(params); // Returns
// ?order[values][alphabetically]=ASC&order[values][arr][0]=A&order[values][arr][1][thisIs]=B&filter=test
```

Hope this could be helpful for someone.

**Comment by jasoncavaliere** [comment]
thank you @damiandennis @ZeBigDuck  - I'm working on a prototype and this one got me stuck badly - thanks and hopefully it gets rolled into the API soon!

**Comment by juanmaflyer** [comment]
:+1:

**Comment by oddlyfunctional** [comment]
:+1:

**Comment by vicb** [comment]
Closing, we do not want to deviate from the standards here.
