### ISSUE TITLE
Input field's touched status is always false for textarea.

### ISSUE THREAD

**Issue by sabbirrahman** [angular/angular#7371]
I'm trying to show error messages for input filed when the field is not valid. The error message is hidden at the begging by testing if the field is touched or not. The message will appear if the field is not valid & the field is being touched once. This works great for normal input types like text, email, password but when tried to use this method with textarea it didn't work. After inspecting the control object of that textarea I found that the touched property is always set to false and don't get updated on blur.

**Comment by zoechi** [comment]
Can you please show some code that demonstrates what you are trying to accomplish?

**Comment by sabbirrahman** [comment]
@zoechi I'm trying the example in this link: [Angular 2 Form Builder and Validation Management](https://coryrylan.com/blog/angular-2-form-builder-and-validation-management)
If you look at the ControlMessages component you'will find this:
`if (c.errors.hasOwnProperty(propertyName) && c.touched) {
    return ValidationService.getValidatorErrorMessage(propertyName);
}`
The if block never executes for textarea as the c.touched property remain false forever.

**Comment by zoechi** [comment]
I guess this needs a Plunker with reproduction case.

**Comment by zoechi** [comment]
This should work as a template https://plnkr.co/edit/PClI775hEI6iijOIxExO?p

**Comment by sabbirrahman** [comment]
@zoechi It's works on the Plunker but not in my local project. Look like there's a problem with my own code. Sorry for the trouble. Closing the issue now.
