### ISSUE TITLE
unable to use lodash in angular2

### ISSUE THREAD

**Issue by deepakgd** [angular/angular#7373]
I am using this [scaffolding](https://github.com/angular/angular2-seed). I am getting error

`error TS2304: Cannot find name '_'.`

I have installed lodash using npm. In my component i did

`import _ from 'lodash';`

Now i am getting 

`error TS2307: Cannot find module 'lodash'.`

May i know how to install lodash in angular2?

**Comment by zoechi** [comment]
This might help http://stackoverflow.com/questions/34660265/importing-lodash-into-angular2-typescript-application

GitHub issues are for bug reports and feature requests. 
      For support questions please use other channels like [StackOverflow](http://stackoverflow.com/questions/tagged/angular2), [Gitter](https://gitter.im/angular/angular), [Google groups](https://groups.google.com/forum/#!forum/angular), ...

**Comment by deepakgd** [comment]
ok thanks

**Comment by zoechi** [comment]
@deepakgd if this fixes your problem please close the issue.

**Comment by pkozlowski-opensource** [comment]
Thnx again @zoechi !
