### ISSUE TITLE
Zone.js afterTask is called three times

### ISSUE THREAD

**Issue by PavelPZ** [angular/angular#7376]
doClick event of this component:

```javascript
import * as core from 'angular2/core';
import {global} from 'angular2/src/facade/lang';

@core.Component({
  selector: 'my-app',
  template: '<h1 (click)="doClick()">Click</h1>'
})
export class AppComponent {

  constructor(private zone: core.NgZone) {//, private http: http.Http) {
    zone.onTurnDone.subscribe(() => console.log('onTurnDone'));
  }

  doClick() {
    global.zone.fork({
      afterTask: function () {
        console.log('After task');
      }
    }).run(() => setTimeout(() => { setTimeout(() => { }, 2000); }, 2000)); //afterTask is called three times
  }
}


```

produced this console log:

```javascript
After task
onTurnDone
After task
onTurnDone
onTurnDone
After task
onTurnDone
onTurnDone
```

first "After task" is printed immediatelly
second "After task" is printed after two seconds
thirds "After task" is printed after another two seconds

------------------
I am using Flux to record x play flux actions (example of such action is "doClick"). For playing recorder actions I need to play them in sync. I try to use zone.js to recognize "action is completed".

Or is there any other possibility to use zone.js or ngZone to recognize "action completed" event?

**Comment by ericmartinezr** [comment]
Hey @PavelPZ the repo for zone.js is here https://github.com/angular/zone.js , note that zone.js has been refactored and hopefully it will be available on next angular2 release. Check this issue as well https://github.com/angular/angular/pull/7345

**Comment by PavelPZ** [comment]
Thanks @ericmartinezr for info, can you please close this issue? I copy it to correct repo.

**Comment by ericmartinezr** [comment]
@PavelPZ I'm not part of the team nor anything :smile: let's wait for someone to close it :+1:

**Comment by PascalPrecht** [comment]
Hi @PavelPZ,

as far as I can see your code behaves as expected. You're executing 3 tasks, hence `afterTask` callback is executed 3 times.

First task is the `zone.run()` code, second task is the first `setTimeout()` call, third is the second `setTimeout()` call.

**Comment by PavelPZ** [comment]
Hi @PascalPrecht, is there any possibility call single event after all three (or more) tasks with help of zone.js? 
Otherwise I need to make callback logic.

**Comment by PascalPrecht** [comment]
@PavelPZ Yes, `NgZone` emits an `onEventDone` event you can subscribe to (similar to `onTurnDone`). This gets fired when the event is done, after all Angular turn tasks are done.

**Comment by PascalPrecht** [comment]
You can learn more about that here: http://blog.thoughtram.io/angular/2016/02/01/zones-in-angular-2.html

**Comment by PavelPZ** [comment]
Thanks for link, @PascalPrecht. 
But, when I change 
```javascript
zone.onTurnDone.subscribe(() => console.log('onTurnDone'));
```
to
```javascript
zone.onEventDone.subscribe(() => console.log('onEventDone'));
```
in my code, then I receive this log:
```javascript
After task
onEventDone
After task
onEventDone
onEventDone
After task
onEventDone
onEventDone
```
onEventDone is called five times. What is wrong?
