### ISSUE TITLE
async pipe does not work with custom @Input declarations

### ISSUE THREAD

**Issue by SuperManitu** [angular/angular#7385]
Hi,
I think I found an issue: I have an RxJS Observable of an Array of Models. This Observable is computed with an `@Input` property in `ngOnInit()`. Then I have the following template:
```typescript
<g *ngIf="dataStreamArray | async | exists">
        <text
            *ngFor="#border of (DataStream | first | async).Borders.AsArray"
            [attr.x]="0"
            [attr.y]="graphService.getY(border, (DataStream | first | async).Borders)"
            style="fill: black"
        >
            {{border}}
        </text>
    </g>

    <g horizontalLines
        [data]="dataStreamArray | log | async | log"
        [yMin]="graphService.DateHeight"
        [yMax]="graphService.SvgHeight"
    ></g>
```
`<g horizontalLines>` is a custom angular2 child component, `log` is a simple pipe that logs the incoming value and returns it again.

So, now the problem: The first `g` Element works as intendet and the `async` pipe returns the proper value.
In the second `g` element, where I try to add the result of the Observable to the property, it does not work. The first `log` returns an Observable as it should, the second only `null`. Switching the positions of those in the template doesn't affect the result.

**Comment by tycho01** [comment]
Could you reproduce in a plunk?
You stated `Switching the positions of those in the template doesn't affect the result`. If you have it as `"dataStreamArray | log | async"`, or even `"dataStreamArray | async"`, would it work?

**Comment by SuperManitu** [comment]
I will try to create one
With switching positions i meant originally the `g` Elements, but the position of the log pipe doesnt do anything too

**Comment by SuperManitu** [comment]
Seems to be fixed in the current beta, closing
