### ISSUE TITLE
Problems using the maxlength attribute on text input

### ISSUE THREAD

**Issue by giorgiofran** [angular/angular#7393]
Dart 1.14.0, Angular2 beta.7
I'm trying to using the maxlength attribute on an input field with ngModel.
this is my component:
```
import 'package:angular2/angular2.dart';

@Component(selector: 'my-app',
    template: '''
    <form>
      <input type="text" [(ngModel)]="value" maxlength="{{max}}" [readonly]="readonly" (input)="dummy()">
      {{value}}
    </form>
    ''',
    directives: const [FORM_DIRECTIVES])
class AppComponent {

  String value = 'test';
  String max = '10';
  bool  readonly =false;

  dummy() { }
}
```
I'm getting the following error:

>  EXCEPTION: Error during instantiation of MaxLengthValidator! (NgModel -> Token NgValidators -> MaxLengthValidator).
>     (anonymous function)	
>   ORIGINAL EXCEPTION: Invalid argument(s): The source must not be null
>     (anonymous function)	
>   ORIGINAL STACKTRACE:
>     (anonymous function)	
>   #0      int.parse (dart:core-patch/integers_patch.dart:48)
> #1      NumberWrapper.parseInt (package:angular2/src/facade/lang.dart:176:16)
> #2      MaxLengthValidator.MaxLengthValidator (package:angular2/src/common/forms/directives/validators.dart:101:44)
> #3      initReflector.<anonymous closure> (package:angular2/src/common/forms/directives/validators.template.dart:32:27)
> #4      Injector._instantiate (package:angular2/src/core/di/injector.dart:895:24)
> #5      Injector._instantiateProvider (package:angular2/src/core/di/injector.dart:792:12)

If I set a fixed maxlength (ex. maxlength="10") everything works fine.

It seems a bug to me, but please let me know if I'm doing something wrong

**Comment by PascalPrecht** [comment]
Maxlength validator doesn't take an expression, but only string values. It takes that string and parses it to an integer, which is why it throws, because it can't parse `{{max}}`

**Comment by giorgiofran** [comment]
Why it doesn't take an expressione? Sorry, but this way is of no use for me.
My case is, I use an input inside of a component, but the maxlength value is set on the component, so, how can I set it that value on the input?
I think that it is inconsistent. I mean, I can set any attribute programmatically (see readonly in the example above), but the maxlength...

**Comment by PascalPrecht** [comment]
I agree with you, property binding should be supported for validators, but it's not implemented yet.

Pinging @vsavkin for opinion, I think we can give it a shot and prepare a pull request for that. Vic, what do you think?

**Comment by zoechi** [comment]
Ah, they use `constructor(@Attribute("maxlength") maxLength: string)` instead of `@Input()` https://github.com/angular/angular/blob/master/modules/angular2/src/common/forms/directives/validators.ts#L97

**Comment by marcodelgatto** [comment]
Try this:
<input type="text" [attr.maxlength]="myExpression" />

works for me :)

**Comment by tolemac** [comment]
@marcodelgatto this works due to native implementation of maxlength on HtmlInputElement but not work with validators.

See this minlength binding example plunkr:  http://plnkr.co/edit/XWVfisxVcmsoh5woIS8P
Write something in both inputs, the first input has minlength setted and it produces minlength error, the second one has minlength binding (usin [attr.minlenth]="minlen") and don't produce minlength error.

**Comment by tolemac** [comment]
I have created a pull request (#10518) that solve it.

**Comment by kara** [comment]
Fixed by https://github.com/angular/angular/pull/11116.
