### ISSUE TITLE
TestComponentBuilder.overrideDirective does not work with Lists of directives

### ISSUE THREAD

**Issue by choeller** [angular/angular#7397]
Having a component "TaskItem" configured like this:
```javascript
@Component({
  selector: 'task-item',
  directives: [ROUTER_DIRECTIVES],
  ...
})
export class TaskItem {
}
```
and trying to override the RouterLink Directive in the test like this:
```
 return tcb
      .overrideDirective(TaskItem, RouterLink, DummyRouterLink)
      .createAsync(TaskList)
      .then((fixture: any) => {
```
leads to the exception:
```
Overriden directive RouterLink not found in the template of TaskItem
```
configuring the component like:
```javascript
@Component({
  selector: 'task-item',
  directives: [RouterLink, RouterOutlet],
  ...
})
export class TaskItem {
}
```
works fine...

**Comment by naomiblack** [comment]
@juliemr could you take a quick look? It seems as though this is a general issue with our ability to test child directives?

**Comment by juliemr** [comment]
The issue is that the override happens before the expansion of `ROUTER_DIRECTIVES` into its parts - this shouldn't be a more general issue.
