### ISSUE TITLE
Relative RouterLinks do not work in Karma Test

### ISSUE THREAD

**Issue by choeller** [angular/angular#7398]
Having one main RouteConfig in AppComponent and a nested config in a component called TasksContainer. In TaskContainer there are two components "TaskList" and "TaskForm". 

Configuring the routerLink from TaskList to TaskForm like this:
```html
<a [routerLink]="['../TaskForm', {id: task.id}]" class="link">{{task.title}}</a>
```
works totally fine in the running app, but trying to write a Karma-Test for this component with this configuration:
```javascript
  beforeEachProviders(() => [
    provide(TaskService, {useClass:MockTaskService}),
    RouteRegistry,
    provide(Location, {useClass: SpyLocation}),
    provide(Router, {useClass: RootRouter}),
    provide(ROUTER_PRIMARY_COMPONENT, {useValue: AppComponent}),
    provide(APP_BASE_HREF, {useValue: '/'})
  ]);
```
leads to the following exception:
```
EXCEPTION: Link "["../TaskForm",{"id":"1"}]" has too many "../" segments.
```

When using absolute Links in routerLink, the test passes as expected:

```html
<a [routerLink]="['/Tasks', 'TaskForm', {id: task.id}]" class="link">{{task.title}}</a>
```

**Comment by choeller** [comment]
```
    provide(ROUTER_PRIMARY_COMPONENT, {useValue: Tasks}),
```
throws the same exception

**Comment by vicb** [comment]
obsolete
