### ISSUE TITLE
Form email validation issue

### ISSUE THREAD

**Issue by VizuaaLOG** [angular/angular#740]
I was looking through the guide on forms within angular and noticed that in the first example the email field validates if the value is like the following "myemail@mail", this is still not a valid email. [The example I was looking at is on this page](https://docs.angularjs.org/guide/forms)

**Comment by SekibOmazic** [comment]
@VizuaaLOG You should file the issue here: https://github.com/angular/angular.js

This is the repository of Angular 2.0

**Comment by kirandc** [comment]
@SekibOmazic same issue in angular.js V1.4.0 I am sending pull request for this.

**Comment by VizuaaLOG** [comment]
Ok sorry :)
