### ISSUE TITLE
img ng-src doesn't work as expected with 404 server errors

### ISSUE THREAD

**Issue by danidev** [angular/angular#7401]
Hello,

the ng-src binding for error doesn't work as expected if the server responds with an image but the response status is 404.

in a link function on a directive to manage the ng-src events I have this code:

    element.bind('load', function() {
        console.log('image is loaded');
    });
    element.bind('error', function() {
        console.log('image could not be loaded');
    });

From some tests I did, if I have a broken link in the url, the ng-src triggers the error function (even if the status of a broken url is 200) but if I send a status code of 4xx with an image in the response, the error function is not triggered.

Can you check if this behavior is correct (maybe it is a feature of the img element and there are no options to check the header status) and eventually suggest a workaround?

Many thanks in advance,
Daniele

**Comment by PascalPrecht** [comment]
Hi, this is the Angular 2 repository. Can you file your issue at http://github.com/angular/angular.js/issues/new please?

Thanks!

**Comment by danidev** [comment]
ok. thanks
