### ISSUE TITLE
Upgrade Benchpress dart to use Webdriver@1

### ISSUE THREAD

**Issue by juliemr** [angular/angular#7404]
Currently it's stuck on an old version, webdriver 0.9.0. Upgrade is non-trivial because the newer version of dart webdriver is incompatible with Dartium (since Dartium is based on such an old version of Chrome), and the current benchpress specs run against Dartium. 

A quick attempt to switch the tests to using desktop Chrome failed on Travis.

**Comment by tbosch** [comment]
This repository is no longer maintaining the Dart version of benchpress, as Angular 2 Dart and Angular 2 TS split (see http://news.dartlang.org/2016/07/angulardart-is-going-all-dart.html)
