### ISSUE TITLE
[testing] TestComponentBuilder.createAsync() swallows template compilation exception

### ISSUE THREAD

**Issue by traviskaufman** [angular/angular#7406]
Given this component:

```typescript
@Component({
  selector: 'foo',
  template: `
    <label>What's your name?</label> 
    <input type="text" required [(ngModel)]="model.name" ngControl="name">
  `
});
export class Foo {
  model = {
    name: ''
  }
}
```

and this test

```typescript
import {Foo} from './foo';
// ...
describe('Foo', function() {
  var builder: TestComponentBuilder;

  beforeEach(inject([TestComponentBuilder], (b) => builder = b));

  it('has a blank name', function(done) {
    builder.createAsync(Foo).then(function(fixture) {
      expect(fixture.componentInstance.model.name).toEqual('');
    }).then(done).catch(done);
  });
});
```

The above test will fail with a `TypeError` saying that `model` is undefined. However, this happens because the template of `Foo` uses `ngControl`, which is not compilable outside of an `ngForm` component. I would expect that `createAsync()` should catch this error and fail its promise, but that doesn't seem to be happening.

If there is a link to a plunkr I could use to set up a test case, I would be happy to reproduce. But I can't find a plunkr that works with angular2 and jasmine2. Thanks!

**Comment by vicb** [comment]
obsolete
