### ISSUE TITLE
Request to have validation errors named in camelCase opposed to all lowercase

### ISSUE THREAD

**Issue by jevenson** [angular/angular#7407]
See the code below:
https://github.com/angular/angular/blob/38cb526f60f910ddbdb532639a03b57d9da378c5/modules/angular2/src/common/forms/validators.ts#L60

If I use the `minLength` validator on a control, the error I check for is `minlength`. It's just a bit inconsistent, so that's why I'm suggesting this change.

Thoughts?

**Comment by ScottMGerstl** [comment]
Agreed. This caused me a lot of hassle.

**Comment by PascalPrecht** [comment]
I think this just so that it aligns with validators applied via template.

**Comment by ericmartinezr** [comment]
Dup of https://github.com/angular/angular/issues/7246 (or leave this one that got more attention, sorry @harangue)

**Comment by jevenson** [comment]
@PascalPrecht do you mean like this?

```
<input type="text" maxlength="10" [(ngModel)]="username"></input>
```

**Comment by ps2goat** [comment]
+1

**Comment by PascalPrecht** [comment]
@jevenson yes.

**Comment by PascalPrecht** [comment]
After all, it's really up to the validator what the error object looks like. E.g. when you build a custom validator, no one can prevent you from putting whatever you want in whatever shape into that object. 

So despite the fact this not being super consistent, there won't be prolly any way to guarantee consistency in other validators.

**Comment by ps2goat** [comment]
@PascalPrecht, I think the argument here is that the html template match the built-in validators' casings.  If the Angular 2 team uses consistency, so will the majority of devs.

In our case, we missed the difference between 'maxlength' in the template and the 'maxLength' object.  If the object is 'minLength', that's what we want to see in the html template.  If the object is 'minlength', that's what we want to see in the template.  I think Angular 2 has done a pretty good job of getting rid of magic strings (e.g., snake-casing in the template converted to camel casing in the code), and this seems to be another one of these magic strings that can be removed.

**Comment by ScottMGerstl** [comment]
Agreed. From a self documenting code standpoint. since I used Validators.maxLength I would expect to use control.errors?.maxLength on the html as it matches the validator I set up in code. 

the magic strings problem that @ps2goat described is a great way to think about this.

**Comment by harangue** [comment]
Alternatively, if you really want to align it with validators applied via template, change 'em all to all lowercase `Validators.maxlength`.

**Comment by ScottMGerstl** [comment]
or apply both

```
static minLength(minLength: number): Function {
    return (control: modelModule.Control): {[key: string]: any} => {
      if (isPresent(Validators.required(control))) return null;
      var v: string = control.value;
      return v.length < minLength ?
                 {"minlength": {"requiredLength": minLength, "actualLength": v.length}, "minLength": {"requiredLength": minLength, "actualLength": v.length}} :
                 null;
    };
  }
```

**Comment by jevenson** [comment]
@ScottMGerstl If you apply both, the errors collection could potentially have two errors for the same thing which would mess up some error checking logic.

@PascalPrecht I think the argument that just because a developer can create custom validators and return anything they want is a poor argument to make against this case. At that point, if I can return whatever I want, wouldn't it be in my best interest to make it as similar as possible?

If there are no technical limitations to this, I don't understand why this change shouldn't be made. Of course, it would be a breaking change, but hey, that's why we're in beta.

**Comment by ScottMGerstl** [comment]
@jevenson good point. I didn't consider that.

**Comment by PascalPrecht** [comment]
@jevenson There was no argument against your proposal. I actually agree with you.

**Comment by ScottMGerstl** [comment]
@PascalPrecht what is the likelyhood we will see the validators changed to match the function names?

**Comment by PascalPrecht** [comment]
I'm currently collecting issues, bugs and missing features on forms. This will go on that list, then we'll see what happens to this one

**Comment by mhevery** [comment]
@PascalPrecht where are you keeping such list? can you share?

**Comment by PascalPrecht** [comment]
@mhevery Yes, that's the plan. Need to polish it. Gonna share it on Slack, hold your horses. :)

**Comment by zoechi** [comment]
Is the Slack channel private or public? I couldn't find anything about it.

**Comment by kara** [comment]
Hey all, we've talked about this internally, and we've decided to keep the validators as "maxLength" and "minLength" to match the native property names.

**Comment by GeorgeKnap** [comment]
two years later but getting into this issue while using `minLength` validator.

`userForm.get('password')!.hasError('minlength') ` works but `userForm.get('password')!.hasError('minLength')`  doesn't.

This has not been fixed?

**Comment by mlc-mlapis** [comment]
@GeorgeKnap ... the directive is and was ... lower case ... do you remember when it was different?
```
@Directive({
  selector: '[minlength][formControlName],[minlength][formControl],[minlength][ngModel]',
  providers: [MIN_LENGTH_VALIDATOR],
  host: {'[attr.minlength]': 'minlength ? minlength : null'}
})
```

**Comment by GeorgeKnap** [comment]
@mlc-mlapis 
Might be getting bit confused here. As @kara posted above, they decided to keep validators lowerCamelCase  i.e. `minLength`.

So why `userForm.get('password')!.hasError('minLength')` does not work?

**Comment by trotyl** [comment]
@GeorgeKnap That was talking about validator name, which is `minLength`. And the error property used has always been `minlength`, please try read the thread again.

**Comment by GeorgeKnap** [comment]
@trotyl 
Ah ok, my bad.

**Comment by kenmorechalfant** [comment]
Bump - This is still not fixed.

@kara 
> we've decided to keep the validators as "maxLength" and "minLength" to match the native property names.

That's the opposite of what the issue is. The problem is not that they are camel cased, it's that when trying to access them on `someFormControl.errors` they are NOT camel cased.
