### ISSUE TITLE
[testing] difficulty testing Component which implements ControlValueAccessor 

### ISSUE THREAD

**Issue by traviskaufman** [angular/angular#7409]
So I've got a component that implements `ControlValueAccessor` and therefore need to test/validate that `ngModel` works correctly with it. However, I'm finding it non-trivial to test the two-way binding behavior between the model and the view. Here's what my test looks like

```typescript
describe('usage as a form control', function() {
      var fixture: ComponentFixture;
      // Component which contains a "model" property bound to md-checkbox with [(ngModel)]
      var controller: CheckboxFormcontrolController; 

      beforeEach(function(done: () => void) {
        builder.createAsync(CheckboxFormcontrolController).then(function(_fixture_) {
          fixture = _fixture_;
          controller = fixture.componentInstance;
          fixture.detectChanges();
        }).then(done).catch(done);
      });

      it('supports ngModel', function(done: (err?: Error) => void) {
        fakeAsync(function() {
          controller.model.isChecked = true;
          fixture.detectChanges();
          tick();
          fixture.detectChanges();

          const el = fixture.debugElement.query(By.css('.md-checkbox'));
          expect(el.nativeElement.className).toContain('md-checkbox--checked');

          // where "click()" is a helper function that dispatches a click event on `el.nativeElement`
          // and then runs `fixture.detectChanges()` 
          click(el, fixture);
          tick();
        })();

        setTimeout(function() {
          var err: Error;
          try {
            expect(controller.model.isChecked).toBe(false);
          } catch(e) {
            err = e;
          } finally {
            done(err);
          }
        }, 100);
      });
```

This setup is the only way I could figure out to verify two-way binding, and there's a lot of complication going on here, specifically:

* **The need for fakeAsync() is not immediately obvious.** You have to look at how Zone + RxJS is scheduling/running subject subscriptions in order to deduce that this could be helpful.

* **The detectChanges()/tick() dance is not straightforward.** I _believe_ this is needed as the first call to `detectChanges()` will register the model --> view propagation of `isChecked`, then `tick()` is needed to run the zone microtask needed to tell the value accessor to write the new value to the component, and then another `detectChanges()` is needed to actually process those updates. However, this code looks pretty weird on its own.

* _(speculative)_ **Internal event handlers seem to run using native timeouts**. While the above test will complain if that last `tick()` before exiting out of the `fakeAsync` zone, the assertion currently in the native `setTimeout()` block fails when run within the async zone. Upon debugging this, it appeared to be that even when running inside `fakeAsync()`, the subscription callback for _this_ particular call was scheduled using the native `setTimeout()` function rather than the mocked one. As a corollary, I tried wrapping `createAsync()` in a `fakeAsync()` zone but when I did so, the promise never settled.

I realize this issue is cumbersome and touches on many different things so please follow up with me on anything that needs more clarification or simply needs to be narrowed down. Thanks!

**Comment by traviskaufman** [comment]
I should also mention that on that last `setTimeout()`, a delay seems to be necessary as the test fails when it's omitted.

**Comment by traviskaufman** [comment]
Following up, I did find a better way to test changes back to the model. The idea is to have the model also emit a change when its bound property changes, and expose a means of listening for that.

```typescript
class FormcontrolModel {
  private _isChecked = false;
  private _changeEmitter = new EventEmitter<boolean>();

  get isChecked(): boolean {
    return this._isChecked;
  }

  set isChecked(isChecked: boolean) {
    const shouldEmitChange = this._isChecked !== isChecked;
    this._isChecked = isChecked;
    if (shouldEmitChange) {
      this._changeEmitter.emit(this._isChecked);
    }
  }

  waitForChange(): Promise<boolean> {
    return new Promise((resolve, reject) => {
      let subscription: {unsubscribe: () => void};
      const subscriber = function(isChecked: boolean) {
        subscription.unsubscribe();
        resolve(isChecked);
      }
      subscription = this._changeEmitter.subscribe(subscriber, reject);
    });
  }
}
```

Then in your Component's template:

```html
<md-checkbox [(ngModel)]="model.isChecked"
                         ngControl="cb" #cb="ngForm">
</md-checkbox>
```

And finally in the test:

```typescript
// where "controller" and "click" are the same as above
const onceChanged = controller.model.waitForChange();
click(el, fixture);
// import {tick} from 'angular2/testing'; 
// used inside fakeAsync().
tick();
onceChanged.then(function() {
  expect(controller.model.isChecked).toBe(false);
}).then(done).catch(done);
```

**Comment by jelbourn** [comment]
cc @juliemr

**Comment by rbnzdave** [comment]
Where are you getting `builder` from ? I'm having similar issues and cant figure out how to initialise TestComponentBuilder in the beforeEach

**Comment by jelbourn** [comment]
@rbnzdave 
```ts
    let builder: TestComponentBuilder;

    beforeEach(inject([TestComponentBuilder], (tcb: TestComponentBuilder) => {
      builder = tcb;
    }));
```

**Comment by juliemr** [comment]
We're looking to improve this a lot once new zones land - you won't need to use that `waitForChange` hack. See WIP PR https://github.com/angular/angular/pull/7604 and the issue https://github.com/angular/angular/issues/7472

**Comment by juliemr** [comment]
Closing as this will be obsolete with new AsyncTest.

**Comment by bmbell** [comment]
Is there any documentation on how to do this?  I am struggling to test a component that implements ControlValueAccessor.  The component works great, but simple test cases are failing and seem difficult to write.

**Comment by nickiewooster** [comment]
Where is the new AsyncTest you are referring to ? I cant find any information about it

**Comment by stevenjob** [comment]
Is there an example of how to do this nicely now?
Are there tests for existing angular implementations of ControlValueAccessor?
[e.g checkbox value accessor](https://github.com/angular/angular/blob/bebedfed24d6fbfa492e97f071e1d1b41e411280/packages/forms/src/directives/checkbox_value_accessor.ts)

**Comment by stevenjob** [comment]
@juliemr?

**Comment by tommck** [comment]
So... Any chance someone can point us to how to handle this?  

Seems like the ball was kinda dropped here

**Comment by djindjic** [comment]
@juliemr ? really cannot find any example how to test ControlValueAccessor components

**Comment by JiaLiPassion** [comment]
I would like to look into this one, I am working on enhancing `fakeAsync` and `async` in `zone.js` recently and added several new features to support `fakeAsync/async` which will be released in the next version of `zone.js`.

So could @traviskaufman  or anybody here provide al repo to reproduce the issue? so I may make some proposal about how to implement those features in `zone.js` or `angular`.

**Comment by jpzwarte** [comment]
After a *lot* of googling and finally looking at the angular material sources, i got it to work: you need to wrap the component you want to test (the one that implements the ```ControlValueAccessor``` interface in a dummy component: https://stackblitz.com/edit/spectator-br9npq

**Comment by dirkluijk** [comment]
@jpzwarte thanks again. 👍With ES7 async/await, it is even a bit less ugly:

```typescript
it('should check and uncheck', async () => {
  host = createHost('<input [(ngModel)]="true"></input>');
  await host.hostFixture.whenStable();
  expect(host.element).toHaveClass('checked');
});
```
