### ISSUE TITLE
The list of local variables should be known statically

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#741]
In order for `ChangeDetctor` to not have to decide between the `Locals` and `Context` at runtime each time it executes (negative perf implication) we need to know which vars are locals and which are not during the compilation of the `ChangeDetector` Such information can be collected by the HTML compiler and should be available in the `ProtoRecord`.

Work:
- [ ] [`ProtorRecord.variableBindings`](https://github.com/angular/angular/blob/895b2a7bdfc626725af2d5a749d11873c33713a0/modules/angular2/src/core/compiler/view.js#L282) need proper initialization
- [ ] [`new ProtoView`](https://github.com/angular/angular/blob/895b2a7bdfc626725af2d5a749d11873c33713a0/modules/angular2/src/core/compiler/pipeline/proto_view_builder.js#L37) Pull things from [`CompileElement.variableBindings`](https://github.com/angular/angular/blob/895b2a7bdfc626725af2d5a749d11873c33713a0/modules/angular2/src/core/compiler/pipeline/compile_element.js#L28)
- [ ] [`CompileElement.addVariableBinding`](https://github.com/angular/angular/blob/895b2a7bdfc626725af2d5a749d11873c33713a0/modules/angular2/src/core/compiler/pipeline/compile_element.js#L112) verify that all vars get added.

**Comment by mhevery** [comment]
Has this been resolved?

**Comment by vsavkin** [comment]
Yes.
