### ISSUE TITLE
scrollTop binding is not working [beta.8]

### ISSUE THREAD

**Issue by leosvelperez** [angular/angular#7411]
I'm trying to bind to the "scrollTop" property of a div element but it isn't working. It's recognizing well the property, it throws no error at all but it just simply doesn't do anything.
This is what I have:
main-container.component.html:
```html
<div #mainContainer class="main-container" (scroll)="onScroll($event)"
    [scrollTop]="scrollTopPosition">
</div>
```
main-container.component.ts:
```javascript
@Component({
    selector: "bl-main",
    templateUrl: "app/businesslist/components/main/bl-main.component.html",
    styleUrls: ["app/businesslist/components/main/bl-main.component.css"],
    directives: [BlGridComponent, PAGINATION_DIRECTIVES],
    providers: [SearchBusinessService]
})
export class BlMainComponent implements OnInit {
    scrollTopPosition: number = 0;

    ngOnInit() {
        this.searchBusinesses();
    }

    searchBusinesses(page: number = 1) {
        this.searchBusinessService.searchBusinesses(page, this.itemsPerPage).subscribe((response: BlGridData) => {
            this.businessData = response;
            this.scrollTopPosition = 0;
        });
    }

    pageChanged(event: any): void {
        this.searchBusinesses(event.page);
    }

    onScroll(event: any) {
        //logic
    }
}
```
I've also tried using "scroll-top" which was working on an example I had on a prior alpha version but the syntax has changed and it doesn't work anymore, this way an error is thrown:
```html
<div #mainContainer class="main-container" (scroll)="onScroll($event)"
    [scroll-top]="scrollTopPosition">
</div>
```
Am I missing something here? Or is it a bug?

Thanks in advance.

**Comment by zoechi** [comment]
Can you create a Plunker?

**Comment by thomashilzendegen** [comment]
Hm, works in my example: http://plnkr.co/edit/OQqEa9LZknPKLdjKs3NA?p=preview

**Comment by leosvelperez** [comment]
Thank you, but I found that I forgot to do:
```typescript
this.scrollTopPosition = event.target.scrollTop;
```
on the onScroll function, so the scrollTopPosition was always 0 so Angular didn't trigger the update of the property because nothing was changed. I'm closing this.
Thank you.
