### ISSUE TITLE
jspm install brings in un-needed deps

### ISSUE THREAD

**Issue by amcdnl** [angular/angular#7412]
[Bug: Angular2@2.0.0-beta.8]

Installing from JSPM like `jspm install angular2` brings in a whole mess of things that are not needed.  See config result from install: https://github.com/amcdnl/ngupgrade-changedetection-bug/blob/master/wwwroot/config.js

Should investigate configuring a jspm override: https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm

I was looking at something along these lines:

```
{
  "main": "bundles/angular2",
  "dependencies": {
    "zone.js": "npm:zone.js@0.6.2",
    "rxjs": "npm:rxjs@5.0.0-beta.2",
    "reflect-metadata": "npm:reflect-metadata@0.1.3"
  },
  "directories": {
    "lib": "src",
    "dist": "bundles"
  }
}
```

**Comment by robwormald** [comment]
@amcdnl if you can add to override to the JSPM registry and validate it works over there, that'll solve the problem in the near term for JSPM users, and give us some guidance for configuring it on this end once we get closer to RC and the TS/JSPM stuff stabilizes - currently there's a bit of overhead on managing deps twice.

**Comment by amcdnl** [comment]
@robwormald Sure! I'll get it hammered out and PR up. I'd rather it be included in the main repo rather than having a override that is constantly needing to be updating in the overrides package ( its versioned of course and w/ betas coming out frequently it would happen quickly).

**Comment by amcdnl** [comment]
@robwormald please take a look at https://github.com/jspm/registry/pull/797
