### ISSUE TITLE
FR: sandbox for angular2 dart similar to plunker

### ISSUE THREAD

**Issue by trinarytree** [angular/angular#7414]
When I want to know how some nit-picky HTML thing works, I go to jsfiddle.
When I want to know how Angular2 typescript works, I go to plunker.
When I want to know how Angular2 dart works, I have to build my team's massive application and insert my little test, which takes ~10 minutes.  I can't share the result with anyone and I don't have total confidence that I have isolated the issue or whether I'm seeing contamination from some weird thing our app does.  Each time I permute the test, I have to reload the entire massive app, which is slow and subject to failures of irrelevant infrastructure, such as the dev backend.

These tools are extremely valuable when submitting bug reports, discussing issues with other devs, rapid prototyping, etc.  Can we get some kind of sandbox like jsfiddle or plunker but for Angular2 dart?

**Comment by trinarytree** [comment]
Maybe this just involves making some copy of the Angular2 lib available online and connecting a [dartpad](https://dartpad.dartlang.org/) template to it.

**Comment by zoechi** [comment]
I think the issue should be filed for dartpad. 

I have a simple Dart project template I copy and publish to github to make it public. Much less work than creating a Plunker because I can user a proper IDE instead of the cumbersome Plunker online editor. 

Just the sharing part of a running example is a big disadvantage.

**Comment by trinarytree** [comment]
I believe that this issue belongs with Angular.  If you guys decide to solve it by using dartpad, go ahead and file a bug with them, but as far as Angular Dart users are concerned, that's just an implementation detail.  You are free to use some other technology besides dartpad.

Btw, you said that sharing an example is a disadvantage.  Not sure what you mean.

**Comment by zoechi** [comment]
@trinarytree I meant that sharing is not as comfortable using GitHub as it is for example using Plunker.

**Comment by zoechi** [comment]
See also dart-lang/dart-services#43

**Comment by pkozlowski-opensource** [comment]
Obsolete as dart-specific.
