### ISSUE TITLE
WebWorker messaging Infrastructure should have its own barrel

### ISSUE THREAD

**Issue by jteplitz** [angular/angular#7419]
The MessageBroker (inlcuding factories), MessageBus, and Serializer are not actually WebWorker specific and may be used by third party libraries that want to add worker support. They should have their own import barrel (independent of the WebWorker bundle although this barrel should be included in the WebWorker bundle) so that those libraries can import them without pulling in the rest of the WebWorker code base, which is currently significant since we're still including parse5.

This will also allow people to use these classes to add support for more platforms (electron, chrome apps, etc...)

**Comment by IgorMinar** [comment]
I believe that this is done already.
