### ISSUE TITLE
WebWorker UI libraries need an entrypoint

### ISSUE THREAD

**Issue by jteplitz** [angular/angular#7420]
If a 3rd party library wants to add WebWorker support and pass messages between the UI and the Worker, they need an entrypoint where the MessageBus is guaranteed to be set up. Ideally they should be able to provide this entrypoint to angular (probably through DI). That way the framework can call it when the worker is set up so that users of the library never need to call the entrypoint specifically. Unfortunately, this is not true if they use the `APP_INITIALIZER` token right now because we use it to set up the MessageBus. If their initialized runs before ours the MessageBus will be null.

I propose we export a `WORKER_INITIALIZED` token and 3rd party libraries can provide multi bindings to it. At the end of `initWebWorkerApplication` (or `spwanIsolate` in Dart) we should call every function provided through this binding.

**Comment by jeffbcross** [comment]
@tbosch or @vsavkin do you approve of adding a new `WORKER_INITIALIZED` token to the public API for  `angular2/platform/worker_render`?

**Comment by LayZeeDK** [comment]
This issue is old, but I still do not see a `WORKER_INITIALIZED` token in the source code. Has this been resolved in another way?

**Comment by splincode** [comment]
@jteplitz @IgorMinar Is the issue relevant?
