### ISSUE TITLE
router(angular1): wrong lang_1 references

### ISSUE THREAD

**Issue by davidreher** [angular/angular#7422]
When I build the angular 1.5 component router from git commit [5a59e44](https://github.com/angular/angular/commit/5a59e44765412c7f68c18ea7b8db62e52a22f33c) (latest at the moment of writing) you can find `lang_1` references (which points to `require('angular2/src/facade/lang')`) all over the place (line 2158, 2182, 2201, ...).

There are two options to work around this: Really require the [angular2/src/facade/lang](https://github.com/angular/angular/blob/master/modules/angular2/src/facade/lang.ts) file or replace `lang_1.` with blanks (the methods are already defined in lines 281-598 imported from [lib/facades.es5](https://github.com/angular/angular/blob/master/modules/angular1_router/lib/facades.es5)).

@btford @petebacondarwin I can work on a pull request for either one if you shed some light on the right path to the solution ;)

**Comment by petebacondarwin** [comment]
@davidreher - how are you building the angular 1 router? Did you run `gulp buildRouter.dev` and look for the file in `/dist/angular1_router.js`?

**Comment by davidreher** [comment]
Yes

**Comment by petebacondarwin** [comment]
I just did an install of router@0.2.0 via npm and the files in there (angular_1_router.js and ng_route_shim.js) do not contain any reference to `lang_1`.
I think you are looking at the A2 version?

**Comment by davidreher** [comment]
I just did a fresh install of the angular project on Windows. Then a gulp buildRouter.dev and looked at the file in the dist folder ...

**Comment by petebacondarwin** [comment]
OK, let me try

**Comment by petebacondarwin** [comment]
I just did:

```bash
git checkout master
git pull
npm run build
gulp buildRouter.dev
```

The resulting file at `angular/dist/angular_1_router.js` does not contain any reference to the string `lang_1` or even `lang` for that matter.

**Comment by davidreher** [comment]
hmm, I will try it again in the evening ... It is does not work, I will reopen this issue ...

**Comment by Wapweb** [comment]
@davidreher Hi. I have the same issue.
Did you solve it?

**Comment by davidreher** [comment]
Seems to be a windows issue. I cannot run the build at all, so I think this will be the problem. See #7457.
