### ISSUE TITLE
http.put() sends HTTP OPTIONS

### ISSUE THREAD

**Issue by andrashatvani** [angular/angular#7424]
* **I'm submitting a ... **
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
I'm reporting a bug.

* **What is the current behavior?**
When calling http.put('http://localhost/endpoint', '', {search: searchParams}), then an HTTP OPTIONS will be sent instead of an HTTP PUT.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**
HTTP PUT will be sent.

* **What is the motivation / use case for changing the behavior?**
Sending HTTP PUT when calling http.put() should be the standard behavior.

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.8
- Browser: [48.0.2564.116 m (64-bit) ]
- Language: [TypeScript 1.8 | ES5]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by zoechi** [comment]
Are you sure this is not the browser that is doing that? http://stackoverflow.com/questions/1256593/why-am-i-getting-an-options-request-instead-of-a-get-request

**Comment by pkozlowski-opensource** [comment]
@zoechi is right, CORS is not the "Angular thing" but rather "a browser thing". Closing as invalid.
