### ISSUE TITLE
Angular 2.0 SCRIPT438 error in IE9 when running the getingstarted tutorial

### ISSUE THREAD

**Issue by andreitour** [angular/angular#7427]
SCRIPT438: Object doesn't support property or method 'bind' 
es6-shim.min.js, line 10 character 180

**Comment by andreitour** [comment]
SCRIPT438: Object doesn't support property or method 'bind' 
es6-shim.min.js, line 10 character 180

**Comment by vicb** [comment]
no repro, closing.
