### ISSUE TITLE
feat(router): Provide way to force reload of entire route

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#7429]
**Note: for support questions, please use one of these channels:** https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

Feature

* **What is the current behavior?**

When navigating to the same route more than once, the route components in the route tree are reused.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

The reload function is called, and all routes in the current instruction reload without being reused.

* **What is the motivation / use case for changing the behavior?**

There are cases where the user would want to force a reload of an entire route to go through the entire navigation process again including triggering lifecycle events.

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
- Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]

All

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

This was the result of a conversation with @petebacondarwin about adding a reload feature for the router. This issue is to officially track that item. https://github.com/angular/angular/pull/7163#issuecomment-190363127

**Comment by matstank** [comment]
+1

**Comment by petebacondarwin** [comment]
More concretely, one use case is where there is a state change in the application, such as a user logging in. If Routing Components check this state in their `routerOnActivate` hook for instance, and change their behaviour accordingly then this would require a reload.

But I am wondering if we are looking at this the wrong way. I think it is easy to give the Router too much emphasis and to use it for the state management of the entire app. The more I look at the Router, the more I feel it is purely about providing entry points to the application, via URLs.

In an SPA, we would not normally require a reload the web page if a state has changed, such as login state. Instead we would design the app to respond to this state change dynamically. I wonder if such as state change should also be handled by the components without requiring a reload of the routing too?

@brandonroberts do you have a more concrete use case where there is a state change that is not reflected in the URL and which is not feasible to handle within the Routing Components themselves?

**Comment by petebacondarwin** [comment]
@btford and @wardbell do you have a view on this?

**Comment by KhoaSydney** [comment]
Hi guys,
I would like the router to be able to reload a completely different route based on user permissions. My application consist of two ng-app under one index.html. The first one is the existing Silverlight application wrap under a angular directive. The second ng-app is the angular app which we are porting over from Silverlight. The second ng-app is a work in progress and once a module is implemented I would like the user to use this module in angular and retire the existing module in silverlight. User can also log in as another user in Silverlight which means that when we navigate to angular from Silverlight we need to reload the route based on this impersonation. 

I am currently stuck with this limitation and can not progress any further. 
cheers,
Khoa

**Comment by petebacondarwin** [comment]
@KhoaSydney what do you mean by a completely different route? If it has a different URL/router path then you simply navigate to that path and you are done.

**Comment by brandonroberts** [comment]
@petebacondarwin I agree that the router shouldn't be responsible for maintaining application state. I don't have another use case outside of some internal state of the application changing and triggering a reload based on that. I think its useful that the router should be able to reload the entire route tree for the current URL without having to set up whether the route should be reused at every level. 

I suppose the same could be accomplished some service I pass through each route component telling the router not to reuse the route component, but seems like overkill.

**Comment by petebacondarwin** [comment]
Perhaps any route that cares about the authorisation of the current user should have a listener to that bit of state changing. If it does then it should cause a navigation to a route that can deal with this unauthorised situation.

**Comment by wardbell** [comment]
I agree with where @petebacondarwin and @brandonroberts are headed. The logout/login use case shouldn't be a router concern and should be handled by other application logic. That include navigating to a safe place when the user logs out.

@brandonroberts Do you want to withdraw this proposal and close the issue or defend it?

**Comment by brandonroberts** [comment]
I'm fine with withdrawing this one

**Comment by MrAntix** [comment]
... but if you navigate to a safe place you loose your place in the application

You should be able to logout, keep the url and log in as another user - for example

The url is a pointer to a resource, the application decides whether that resource is available to the logged in user or not, but shouldn't redirect them elsewhere
