### ISSUE TITLE
Race condition when switching router-outlets and navigating

### ISSUE THREAD

**Issue by kvantetore** [angular/angular#7430]
There is a possible race condition when switching router-outlets and triggering a navigation at the same time.

Switching router-outlets (via *ngIf or similar) triggers a re-commit of _currentInstruction, but in contrast to other methods logic in Router, it does not wait until _currentNavigation is completed. 

It is possible that the re-commit is started, but takes a while to complete. In the mean time, another navigation is commited. If the navigation commit happens before the re-commit finishes loading the component, the componentRef of the re-commit will never be disposed.

This can be fixed by waiting for _currentNavigation before re-commiting _currentInstruction in router.ts:124.

**Comment by zoechi** [comment]
I think at least related #9500

**Comment by Apee** [comment]
Yes, I really think this is the main cause of the #9500

**Comment by vicb** [comment]
is this still applicable to the latest router ?

**Comment by kvantetore** [comment]
router 3 doesn't use "instructions" in the same way the old router did, so it's not completely applicable, but the latest router doesn't support router-outlets in templates either. See #11142.
