### ISSUE TITLE
TypeScript transpiler on code.angularjs.org fails when mixing single/double quotes on imports

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#7433]
**Note: for support questions, please use one of these channels:** https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

Bug

* **What is the current behavior?**

Using https://code.angularjs.org/tools/typescript.js

When importing multiple modules from the same bundle (e.g. angular2/core) on separate lines and the import statements are mixed with single quotes and double quotes, unexpected errors occur.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

Using TypeScript transpiler: http://plnkr.co/edit/DbHVNm?p=preview

* **What is the expected behavior?**

Mixing single quotes and double quotes for imports should not cause errors. Babel transpiler works as expected

Using Babel transpiler: http://plnkr.co/edit/W2b6o3?p=preview

* **What is the motivation / use case for changing the behavior?**

Using double quotes/single quotes should not affect imports.

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
- Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]

Angular: 2.0.0-beta.7
Browser: all
Language: TypeScript 1.7.3 (browser transpiler)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Prior issues: 
https://github.com/angular/angular/issues/7094#issuecomment-184683890
https://github.com/angular/angular/issues/6682

**Comment by ericmartinezr** [comment]
For reference https://github.com/Microsoft/TypeScript/issues/7616

**Comment by brandonroberts** [comment]
:+1: Maybe the build on angularjs will get updated with this soon also.
