### ISSUE TITLE
Angular downloads template files many time with DynamicComponentLoader

### ISSUE THREAD

**Issue by Zysce** [angular/angular#7434]
In this [plunker](http://plnkr.co/edit/ezhcab7W0nM2nvggbhxh?p=preview), I use the class DynamicComponentLoader to dynamically instantiate components.

However, when I open the Developer Tools Windows and look at the network tab, the html files associated to the components dynamically created are retrieved more than one time.

Why does the caching not working ?
Is it because the components are dynamically created so Angular doesn't know to not download the template files again ?

![image](https://cloud.githubusercontent.com/assets/17613158/13532328/25edd716-e22b-11e5-8949-878db52d7f7e.png)

- Angular version: 2.0.0-beta.8
- Browser: all
- Language: TypeScript

**Comment by pkozlowski-opensource** [comment]
Duplicate of #6612
