### ISSUE TITLE
Can not navigate after rejecting in routerOnActivate

### ISSUE THREAD

**Issue by waeljammal** [angular/angular#7437]
Reporting a bug.

I can not navigate after rejecting in routerOnActivate

To repeat it reject a promise in routerOnActivate and then try to navigate to a new route.

I should be able to navigate to a new route after rejecting, I know it has rejected because the rest of my view has not loaded and I get the reject error message in the console.

Due to the fact that @CanActivate is not feasible at the moment I need to redirect if my logic fails without creating any child components.

- Angular version: 2.0.0-beta.6

**Comment by brandonroberts** [comment]
@waeljammal you don't reject in the router lifecycle hooks. Ultimately, you either return a boolean or a Promise that resolves a boolean value. If you reject, it throws an exception which is what is causing your app to break.

**Comment by waeljammal** [comment]
Thanks for the response, however if I resolve(false) it still renders the children and my app errors at that point because expected logic did not run correctly before hand.

Is resolve(false) supposed to prevent the children from being created?

**Comment by brandonroberts** [comment]
Yes, if you return false in the parent route using routerOnActivate, it should prevent the child routes from being activated. Can you reproduce in a plunker?

**Comment by wardbell** [comment]
Yes. See #7576.  Dup.

**Comment by zoechi** [comment]
@brandonroberts isn't that only `@CanActivate´ that allows to prevent routing to a component?

In the docs to `routerOnActivate()` 

> If routerOnActivate returns a promise, the route change will wait until the promise settles to instantiate and activate child components.

There is no mention of returning `false`.

I think the purpose of `OnActivate` and `OnReuse` is just to do some initialization depending on whether the component is a new instance  or a reused one, but not to manipulate the routing.

**Comment by brandonroberts** [comment]
@zoechi currently yes. The `routerOnActivate` will only prevent navigation from completing until the promise is settled, but doesn't prevent child routes from being activated if it resolves to false. This  discussion we had on #4112 was using `routerOnActivate` as an alternative way to prevent child routes from being activated.

**Comment by zoechi** [comment]
@brandonroberts Got it. Thanks for the feedback!

**Comment by vicb** [comment]
obsolete - former router
