### ISSUE TITLE
Core universal services

### ISSUE THREAD

**Issue by jeffwhelpley** [angular/angular#7438]
**I'm submitting a feature request **

This issue replaces #7301, #7302 and #7303. At a high level, we need to define tokens for commonly used services that typically exist on both the client and the server such as:

* Head Service - In addition to modifying the title (which was just recently added), modify any other head tag value.
* Cookie Service - Similar to $cookie in ng1, but would have a different server side implementation
* Storage Service - localStorage on the client side, but either in memory or redis on the server.

The motivation behind this is that almost every universal app we have seen needs these services and we have to ensure that the interface for these services is consistent on the client and server for all users.

@gdi2290 and @jeffbcross have been discussing this change for the past couple weeks and I believe Jeff is going to have some talks with other core team members to finalize what we do here.

**Comment by gdi2290** [comment]
can you add `Intl` to the list

**Comment by jeffwhelpley** [comment]
What is `Intl`?

**Comment by gdi2290** [comment]
Internationalization
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl

**Comment by jeffbcross** [comment]
We're going to start with implementing a few basic, easy `OpaqueToken`s into `angular2/platforms/tokens.ts`:

 * Global
 * Location
 * Title

Title will actually be an abstract class, since an implementation already exists in browser platform.

Chatted with @IgorMinar about the implementation and the location of the tokens.

@gdi2290 is going to start on a PR to just add the tokens for now, and then focus on integrating them in the platform later.

**Comment by gdi2290** [comment]
the PR for Title, Location, and Global is here https://github.com/angular/angular/pull/7984

**Comment by vicb** [comment]
Can this be closed now ?

**Comment by gdi2290** [comment]
@vicb ya

**Comment by bisubus** [comment]
@gdi2290 I see that PR doesn't address the part of the issue about Head Service (and not sure if Global service solves the rest of the issue). Should #7301 be re-opened then?

**Comment by jeffwhelpley** [comment]
The head service work is being tracked here:

https://github.com/angular/universal/issues/309

**Comment by bisubus** [comment]
@jeffwhelpley Great, thank you for the reference.

**Comment by intergleam** [comment]
so how do I access localstorage and cookies? thanks

**Comment by bisubus** [comment]
@imagentleman Angular isn't currently responsible for that. Use third-party extensions.

**Comment by imagentleman** [comment]
> @imagentleman Angular isn't currently responsible for that. Use third-party extensions.

@intergleam

**Comment by intergleam** [comment]
hm and I thought solution  is here https://github.com/angular/universal/tree/master/modules/express-engine#using-the-request-and-response

Only I can't compile the project
