### ISSUE TITLE
benchpress: add cloud reporter again

### ISSUE THREAD

**Issue by tbosch** [angular/angular#744]

**Comment by tbosch** [comment]
Previous implementation: https://github.com/angular/angular/blob/benchpress_old/tools/benchpress/src/cloud_reporter.es6

- Needs to use new interface: https://github.com/angular/angular/blob/master/modules/benchpress/src/reporter.js
- Needs unit tests

**Comment by jeffbcross** [comment]
thanks!

**Comment by tbosch** [comment]
We are running our benchmarks internally at Google now.

**Comment by laco0416** [comment]
@tbosch Can I see running benchmarks easily on my browser at somewhere like firebase-hosting?

**Comment by tbosch** [comment]
@laco0416 our benchmarks are only running internally at Google where we have calibrated machines...
