### ISSUE TITLE
angular_router_1 v.0.2.0 Error: [$injector:unpr] Unknown provider: $routerProvider <- $router

### ISSUE THREAD

**Issue by KhoaSydney** [angular/angular#7444]
Hi,

After upgraded to @angular/router^0.2, The application give me the following error which used to work on 0.1.0

*Error: [$injector:unpr] Unknown provider: $routerProvider <- $router
http://errors.angularjs.org/1.5.0/$injector/unpr?p0=%24routerProvider%20%3C-%20%24router*

in the run phase:

`.run(["$router","breeze", "$rootScope",  "AppConstants", "$injector", "$http", ($router,breeze, $rootScope, appConstants, $injector, $http: ng.IHttpProvider) => {
}]);`

I have added ** "ngComponentRouter"** as one of the dependencies to my main application. To confirm that there is something wrong with the latest router, I deleted v0.2.0 and installed v0.1.0 back again and it is working fine. 

cheers,
Khoa

**Comment by KhoaSydney** [comment]
After replacing  **$router** with **$rootRouter** based on the the following line in the source code of angular_router_1 it is working again. So from now on we need to use $rootRouter to inject into the controller for use?

`factory('$rootRouter', ['$q', '$location', '$$directiveIntrospector', '$browser', '$rootScope', '$injector', '$routerRootComponent', routerFactory]);`

cheers,
Khoa

**Comment by PascalPrecht** [comment]
@KhoaSydney correct, this has been renamed in https://github.com/angular/angular/commit/a1c3be2

**Comment by KhoaSydney** [comment]
@PascalPrecht Thank you.
