### ISSUE TITLE
Http.post request becomes OPTIONS when setting headers.

### ISSUE THREAD

**Issue by lrem** [angular/angular#7445]
* **Do you want to request a *feature* or report a *bug*?**

*bug*

* **Code**
```
  onSubmit() {
    let headers = new Headers();
    headers.append('Content-Type', 'application/json');
    let result = JSON.stringify({'outcome': this.players});
    console.debug(result);
    this.http.post(`http://127.0.0.1:5000/${this.ladder}/game`,
              result, {headers: headers}).subscribe();
  }
```

* **What is the current behavior?**

This request is send using the OPTIONS method, as seen in logs:
`INFO:werkzeug:127.0.0.1 - - [05/Mar/2016 19:45:51] "OPTIONS /foo/game HTTP/1.1" 200 -`

* **What is the expected behavior?**

This should be a POST.

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.8
- Browser: Chrome 48 | Safari 9.0.3
- Language: TypeScript

**Comment by laco0416** [comment]
isn't that a _preflight_ request?

**Comment by robwormald** [comment]
this is controlled by the browser, below angular's HTTP module. 

see https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS, specifically:

> Preflighted requests

> Unlike simple requests (discussed above), "preflighted" requests first send an HTTP request by the OPTIONS method to the resource on the other domain, in order to determine whether the actual request is safe to send.  Cross-site requests are preflighted like this since they may have implications to user data.  In particular, a request is preflighted if:

> It uses methods other than GET, HEAD or POST.  Also, if POST is used to send request data with a Content-Type other than application/x-www-form-urlencoded, multipart/form-data, or text/plain, e.g. if the POST request sends an XML payload to the server using application/xml or text/xml, then the request is preflighted.
> **It sets custom headers in the request (e.g. the request uses a header such as X-PINGOTHER)**

**Comment by lrem** [comment]
Thanks, this was actually the case and I was able to fix it with CORS settings on the backend.

**Comment by salaivanamali** [comment]
how did you fix this issue. I am facing similar issue. Angular 2 invoking  the webapi.. this is my client code.

   let headers = new Headers({ 'Content-Type': 'application/json' }); // ... Set content type to JSON
         headers.append('Accept', 'application/json');
         headers.append('Access-Control-Allow-Methods', 'POST, GET, OPTIONS, DELETE, PUT');
         headers.append('Access-Control-Allow-Origin', 'http://localhost:4503');
         headers.append('Access-Control-Allow-Headers', "X-Requested-With, Content-Type, Origin, Authorization, Accept, Client-Security-Token, Accept-Encoding");
         console.log("headers1: value" + JSON.stringify(headers));
         let options = new RequestOptions({ headers: headers });
            
     let bodyString = JSON.stringify({ "strbody": body }); // Stringify payload
         //let bodyString = JSON.stringify(body);// Stringify payload
             console.log(saveurl);
             console.log('bodystring: ' + bodyString);
             return this.http.put(saveurl,bodyString, options) // ...using put request
                 .map((res: Response) => res.json()) // ...and calling .json() on the response to return data
                 .do(data => console.log('ALL' + JSON.stringify(data)))
                 .catch(this.handleError)    

server side I have  added the following
  <customHeaders>
        <add name="Access-Control-Allow-Origin" value="*" />
        <add name="Access-Control-Allow-Methods" value="GET, POST, OPTIONS, PUT, PATCH, DELETE" />
        <add name="Access-Control-Allow-Headers" value="accept, authorization, Content-Type" />
  
      </customHeaders>

I am getting the error XMLHttpRequest cannot load http://localhost:4503/api/AssessmentLists/?id=1. Response for preflight has invalid HTTP status code 405

**Comment by lrem** [comment]
It's been a while, but I believe this piece of server-side code is what I did here:

```Python
@app.after_request
def allow_cross_domain(response: flask.Response):
    """Hook to set up response headers."""
    response.headers['Access-Control-Allow-Origin'] = '*'
    response.headers['Access-Control-Allow-Headers'] = 'content-type'
    return response
```

**Comment by patilragini** [comment]
how did u resolved it my backend in spring is getting hit but in response i am getting blank array "[ ]" while POSR requsest

**Comment by cirix** [comment]
@patilragini it's not relevant to angular that your post request returns and empty array. Check if the Spring controller on the ResponseEntity you are attaching a value after the POST.For example if the spring returns ResponsEntity.ok()....this is a 200 with OK but no payload.

**Comment by pawan8525** [comment]
In react-native when i call REST API with PUT request method , In response  it  gives status "200 OK" but not update record. API is working very well in postman with put method but when i use in react-native it not update record and also not give any error

**Comment by patilragini** [comment]
@cirix their was issue with node server solved
