### ISSUE TITLE
Herores Tutorial

### ISSUE THREAD

**Issue by rameshbas** [angular/angular#7446]
* **I'm submitting a ... **
-problem in tutorial

The first 3 tutorials worked ok ( up tp mulitpart). Once I moved the Heroes data to mockup service and added the service to the appcomponent it never worked. I tried 2-3 times.  I did cut and paste the final code in the tabs. still no help. 
All I wanted a sample program with data served from a service.
thanks. Attached files are modified to show routes feature

[test.zip](https://github.com/angular/angular/files/160093/test.zip)

.

**Comment by Foxandxss** [comment]
Please open the issue at [angular.io](https://github.com/angular/angular.io). This is not the right repository for documentation issues.

And when you are at it, please add more details. What error do you have, which concrete part...

Thank you.
