### ISSUE TITLE
Upg to 0.7 beta and getting TypeError: _this._http.get(...).map is not a function

### ISSUE THREAD

**Issue by born2net** [angular/angular#7450]
Upg to 0.7 beta and getting TypeError: _this._http.get(...).map is not a function
went back to 0.6 and no issues.
double checked my file and I do import:
```import 'rxjs/add/operator/map';```

and my code is:
```
return this._http.get(url)
                    .map(result => {
```

I looked at the change log of 0.6 > 0.7 and I don't see anything that can cause this but never the less I still get this error...

tx for reading,

Sean

**Comment by zoechi** [comment]
Plunker?

**Comment by born2net** [comment]
this is a huge project :( 
not something I can run on Plunker easily :(
Anything you can think of I can try?

**Comment by zoechi** [comment]
If you can't reproduce in a simple Plunker the Angular team won't be able to reproduce as well and when there is no bug to demonstrate they probably won't be able fix it.

**Comment by born2net** [comment]
I understand... I will work on the issue be checking all libs are up to date and re-open if I can't fix.
tx as always for the quick replies.
