### ISSUE TITLE
Renderer.setElementClass does not work on ElementRef (beta 8)

### ISSUE THREAD

**Issue by chrkorn** [angular/angular#7451]
* **I'm submitting a ... **
[x] bug report

* **What is the current behavior?**

Renderer.setElementClass (and other Renderer methods) fail when an ElementRef is passed (e.g. with 'cannot read property 'add' of undefined'.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
Plunker: http://plnkr.co/edit/Xa7LY6gjEoXjuGCJ2jzV

* **What is the expected behavior?**
 I expect Renderer to work with ElementRefs. According to the ElementRef documentation, Renderer should deal safely with ElementRefs.

* **Please tell us about your environment:**
- Angular version: 2.0.0-beta.8
- Browser: Chrome 48
- Language: TypeScript

**Comment by zoechi** [comment]
This was changed recently (see [CHANGELOG.md](https://github.com/angular/angular/blob/master/CHANGELOG.md#200-beta1-catamorphic-involution-2016-01-08). You need to pass `elementRef.nativeElement` http://plnkr.co/edit/Ela9dGAXzD3lt1ZMLh9a?p=preview

**Comment by chrkorn** [comment]
In that case, the bug is in the documentation and https://angular.io/docs/js/latest/api/core/ElementRef-class.html needs to be updated.

**Comment by pkozlowski-opensource** [comment]
Seems like a case of a documented breaking change. From what I can see docs were updated already.
