### ISSUE TITLE
ngModel errors only in minified Angular 2

### ISSUE THREAD

**Issue by toddmotto** [angular/angular#7452]
### Bug report

* **What is the current behavior?**

Using `[(ngModel)]=foo` inside a Component works fine when using `angular2.js`, however, switching to `angular2.min.js` bails an error that prevents ngModel working, and I'm not quite sure what's causing it.

* **Steps to reproduce**

See working (uncompressed): http://plnkr.co/edit/TBhTjdXYwHWuZdN37xJg?p=preview
See not working (minified): http://plnkr.co/edit/eKfyl1IlBFouLtcd1E9U?p=preview

* **What is the expected behavior?**

I'd expect both to work the same. Note how the second example only switches the file extension from `angular2.js` to `angular2.min.js`.

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.8
- Browser: Chrome 48
- Language: TypeScript

**Comment by Foxandxss** [comment]
As an extra note, with the `dev` one it also works.

**Comment by zoechi** [comment]
dup of #7435 ?

**Comment by Foxandxss** [comment]
Yes, definitely.

**Comment by toddmotto** [comment]
Cheers all, closing off.
