### ISSUE TITLE
Template Interpolation does not work with DynamicComponentLoader.loadIntoLocation

### ISSUE THREAD

**Issue by gevgeny** [angular/angular#7453]
* **I'm submitting a bug report **

Interpolation does not work in templates of components created dynamically by `DynamicComponentLoader.loadIntoLocation`. But it does with `DynamicComponentLoader.loadAsRoot`.
[Plunker](http://plnkr.co/edit/fHzpvb6CwVxMTnzJ2mk6?p=preview) 

- Angular version: 2.0.0-beta.8
- Language: [tested with TypeScript 1.8]

**Comment by zoechi** [comment]
I tried your Plunker and for me it's working with `loadIntoLocation()` and **not** working with `loadAsRoot()`
Looks like a dup of #6223

**Comment by gevgeny** [comment]
Oh, You are right, the problem is `loadIntoLocation()`.

**Comment by zoechi** [comment]
No, it's `loadAsRoot()` :D

**Comment by gevgeny** [comment]
@zoechi I need more sleep ;( Should i close the issue because of the dup ?

**Comment by zoechi** [comment]
Yes, I think so. Please close it. If you think it's a different issue after you wake up, you can reopen ;-) Sleep well.

**Comment by gevgeny** [comment]
thanks )

**Comment by gdi2290** [comment]
you have to trigger change detection when using loadAsRoot. loadAsRoot is used internally during bootstrap 
http://plnkr.co/edit/tcgbI2?p=preview

**Comment by gevgeny** [comment]
@gdi2290 yea, looks like the best workaround for me, thanks!

**Comment by fletchsod-developer** [comment]
:-(  Works great with 2.0.0-beta.8 as in beta 8 but not working in beta 15.
