### ISSUE TITLE
typescript does not generate the proper code

### ISSUE THREAD

**Issue by ghost** [angular/angular#7460]
the issue is regenerated on the example here https://angular.io/docs/ts/latest/guide/architecture.html

** Issue **
property binding is not working, <hero-list> and <hero-detail> selectedHero and hero
missing code from the generated javascript

** file **
hero-detail.component.ts

generated code using `https://npmcdn.com/typescript@1.8.2/lib/typescript.js` 

```
                __decorate([
                    core_1.Input(), 
                    __metadata('design:type', (typeof (_a = typeof hero_1.Hero !== 'undefined' && hero_1.Hero) === 'function' && _a) || Object)
                ], HeroDetailComponent.prototype, "hero", void 0);
                HeroDetailComponent = __decorate([
```

**generated code withn pm typescript**

```
    __decorate([
        core_1.Input(), 
        __metadata('design:type', hero_1.Hero)
    ], HeroDetailComponent.prototype, "hero.f1380af0");
    HeroDetailComponent = __decorate([

```

tsconfig file is the same as quick start 5min
npm typescript is the same version as the cdn one, listed above.

why the same version of typescript generate two different pieces of code?

**Comment by aciccarello** [comment]
Can you clarify your expectations? Is one generated version working and the other not working?

> why the same version of typescript generate two different pieces of code?

This probably has to do with your runtime or some compiler configuration. How are you running the TypeScript configuration? Is the first example compiling in the browser and the second in your build?

**Comment by pkozlowski-opensource** [comment]
Sounds like a support request without enough context / info.
