### ISSUE TITLE
NgModel writes multiple values and can throw change-detection errors

### ISSUE THREAD

**Issue by jonrimmer** [angular/angular#7461]
* **I'm submitting a ... **
[x] bug report

* **Do you want to request a *feature* or report a *bug*?**

A bug.

* **What is the current behavior?**

When it is initialising, ngModel calls its value accessor's ```writeValue``` method with two different values. If the accessor writes to the input of another component, this can easily trigger change detection errors in dev mode depending on how the child component uses the input.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: 

https://plnkr.co/edit/j7TNlNi4GFvjkUCS6ImX?p=preview

See app.ts. There is an ngModel value accessor that writes to the ```value``` input of the ```child-component``` component it is declared on. ```child-component``` uses the ```value``` input in the template and in a host binding to a class name.

This arrangement causes a ChangeDetectionError to be thrown at startup when in dev mode. The problem seems to be that ```writeValue``` is called twice, first with null, and secondly with the ```true``` value set to its bound property in the ```my-app``` constructor.

* **What is the expected behavior?**

It should be possible for a value accessor to write to a component's input without causing change-detection errors.

* **What is the motivation / use case for changing the behavior?**

The current behaviour will cause a great deal of confusion and angst amongst developers trying to integrate ngModel with their custom components.

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.8
- Browser: [all ]
- Language: [all ]

* **Other information**

This issue was originally discovered and documented by @bennadel here: http://www.bennadel.com/blog/3007-failure-using-ngmodel-with-a-custom-component-in-angular-2-beta-1.htm

**Comment by afirdousi** [comment]
+1

**Comment by pkozlowski-opensource** [comment]
I can't reproduce it anymore with rc.6: http://plnkr.co/edit/H7fWAeJWfNJP4UEmW4d8?p=preview
