### ISSUE TITLE
color input with ngModel lags one content check behind

### ISSUE THREAD

**Issue by Binvention** [angular/angular#7462]
When a ngModel is attached to a HTML5 color input the resulting variable seems to lag one check behind. meaning if you listen for the input to be changed and then log the value the first ngDoCheck or ngAfterContentChecked returns the previous value of the color not the current value. 
A example of this is this code 

```
(function(app){
	app.testing=ng.core.Component({
		selector:"testing",
		template:"<input type='color' [(ngModel)]='value' (change)='changeupd()'/>"
	}).Class({
		constructor:[function(){
			this.value="#ffffff";
			this.changed=false;
			this.changeupd=function(){
				this.changed=true;
			};
		}],
		ngAfterContentChecked:function(){
			if(this.changed){
				console.log(this.value);
				this.changed=false;
			}
		},
	});
})(window.app||(window.app={}));
```
the result of this code is `#ffffff` for the first console.log and then whatever the previous color was for all subsequent changes 

this creates a problem for any programs that run specific functions only after specific inputs are changed. i have not seen that problem with any other type of input except the html5 color 

Environment 
- Angular version: 2.0.0-beta.7 and 2.0.0-beta.8
- Browser: Chrome 49.0.2623.75 m
- Language: ES5

**Comment by cgomezmendez** [comment]
Samething happening to me on angular 1.x

**Comment by pkozlowski-opensource** [comment]
@Binvention the main problem here is that you are trying to assume order of execution of the `change` event and the model binding timing. Unfortunately at present those are not deterministic and can't be relied upon, see: 

Having said this you can easily execute logic after a color gets selected by de-sugaring `[(ngModel)]` and dropping `(change)` completely: `<input type="color" [ngModel]="color" (ngModelChange)="colorSelected($event)">`. Here is a working example: https://plnkr.co/edit/Bx7Eb3mRjMguXF3bKkrD?p=preview

We've got already other issues to tackle order of events execution in #3406 and #7570 so I'm going to close this one as a duplicate.
