### ISSUE TITLE
form two way databinding not working

### ISSUE THREAD

**Issue by asiacoll** [angular/angular#7465]
on angular 2 website, under Basics - Forms at live example  :

Hero Power section (Dropdown selection part) only working on Google Chrome browser.

**Comment by zoechi** [comment]
This should be reported in https://github.com/angular/angular.io where online documentation and tutorials are mainainted.

**Comment by asiacoll** [comment]
thanks, the problem was solved when I add "(change)="onChangeStatus($event.target.value)".
