### ISSUE TITLE
Problems mocking MockConnection error response

### ISSUE THREAD

**Issue by denromani4** [angular/angular#7471]
I'm testing http service in Angular2. I want to test the server, the server responds 'Unauthorized Error'. In test I used this code:

```
this.backend.connections.subscribe(
            (connection: MockConnection) => {
                console.log("Connection");
                connection.mockError(<any>new Response(new ResponseOptions({status: 401, body: 'error'})));
            }
        );
```

In test I used handleError from [angular.io.](url).

It is the wrong decision. Tell me how to test this situation.

**Comment by RomanKisilenko** [comment]
Hi,

So the problem is that MockConnection method to mock error response accepts an instance of Error which does not allow to pass response object to error handler. Cast to any allows to bypass type checks so we can finally pass the response, but to me it looks like a dirty hack.

Is this a bug in MockConnection API or do we do something wrong?

Thank you,
Roman

**Comment by leovrf** [comment]
+1 interested on this.

**Comment by cbomkamp** [comment]
Anyone have a solution to this yet?

**Comment by dkro** [comment]
+1 ... bump

**Comment by vicb** [comment]
Could somebody add a minimal repro ? thanks

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
