### ISSUE TITLE
Angular2: Support dependency injection of ElementRef in a Component's providers.

### ISSUE THREAD

**Issue by BlackHC** [angular/angular#7474]
(Feature request)

I would like to inject the ElementRef into a dependency that has been specified in the providers list of a Component.

Currently, only directives can inject a component's ElementRef. 

Victor told me that this constraint could be relaxed. Relaxing it would make it easier to write fully decomposable features (that are encapsulated from the user of a component).

We want to use it to encapsulate some infrastructure code and simplify its interface.

**Comment by tbosch** [comment]
I think just asking for `ElementRef` is not enough, as recently we removed the feature of getting a `ViewContainerRef` form an ElementRef, but users have to ask for ViewContainerRef explicitly. So you probably also want to be able to inject `ViewContanerRef` as well.

Do you also need query support? (i.e. injecting a `QueryList` in the constructor)?

**Comment by BlackHC** [comment]
The main reason I need the ElementRef is because I want to determine the tag name of the element. I haven't reread the Angular2 code recently :( Did that change as well?

I think when Victor and I discussed this, we saw that injector was artificially constraining what could be injected into component models. In general, it would be nice if the constraints could be relaxed as much as possible to allow for more decoupled elements/behaviors. I think it's good if one can provide more self-contained models that perform orthogonal tasks. What do you think? (Sorry for becoming philosophical.)

Thanks,
 Andreas

**Comment by BlackHC** [comment]
Friendly ping? Any updates on this? Can you think of another way to get the ElementRef/the tag name in a component?

**Comment by vicb** [comment]
It has been fixed some time ago.
