### ISSUE TITLE
isRouteActive by Instruction Alias

### ISSUE THREAD

**Issue by yossicadaner** [angular/angular#7476]
**Note: for support questions, please use one of these channels:** https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
request a feature

* **What is the current behavior?**
isRouteActive determines if instruction is active by Instruction object

* **What is the expected behavior?**
isRouteActive should allow to provide name of instruction

* **What is the motivation / use case for changing the behavior?**
ability to gain simpler and quicker access to making decisions on active instruction. Navigation bar is able to display itself in 'active' state when its instruction is active.

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.8

**Comment by yossicadaner** [comment]
This would work for single-level routing, but for nested routes a simple string just doesn't do it. 
Perhaps a better solution would be
 `isRouteActive(['parentComponent','childComponent','grandChildComponent',...etc])`
which would indicate when that wrapping is active. 
This idea can obviously be extended to further check if the parents match or children match.
 `isRouteActive(['parentComponent'], PARENT_CHECK)`
 `isRouteActive(['childComponent', 'grandChildComponent'], CHILDREN_CHECK)`

**Comment by brandonroberts** [comment]
Why not use `router.isRouteActive(router.generate(['Parent', 'Child']))` ?

**Comment by vicb** [comment]
obsolete
