### ISSUE TITLE
Get the list of subscribed events/outputs of `Component`

### ISSUE THREAD

**Issue by bharathm03** [angular/angular#7479]
- *_I'm submitting a ... *_
  [ - ] Feature report
- **What is the current behavior?**
  All the events listed in outputs meta getting subscribed by dynamically generated "Component_viewFactory" file. Also ElementRef don't have details of bounds events/outputs. So, it is impossible to detect what are events subscribed in the application/parent component.
- **What is the expected behavior?**
  ElementRef should have details of bound events.
- **What is the motivation / use case for changing the behavior?**
  Ability to bind only subscribed events of an Component, to remove unwanted memory usage and event handling. 

Detailed explanation:
In custom component, we will list all the supported events in Outputs meta, however user of the custom component only use/subscribe only what is required for their application. Since angular2, subscribing to all the events provided, we need to bind all the supported events to DOM which creates some unwanted lags. 
- **Please tell us about your environment:**
- Angular version: 2.0.0-beta.X
- Browser: all
- Language: [TypeScript X.X | ES5 ]

**Comment by DzmitryShylovich** [comment]
@bharathm03 
> Since angular2, subscribing to all the events provided

don't think it's true. can you pls add a plunkr with a small demo?
