### ISSUE TITLE
Tracking: Router works with code generation

### ISSUE THREAD

**Issue by mhevery** [angular/angular#7484]
@tbosch can you fill in what things have to happen?

**Comment by tbosch** [comment]
This is detailed in the design doc for codegen.

In general: Rewrite `@RouteConfig` into `@Component` with providers that are injecting `ComponentFactories`.

**Comment by mhevery** [comment]
@tbosch could you put some code example is the bug as to what you have in mind?

**Comment by tbosch** [comment]
The `@RouteConfig` needs to get a `componentFactory` field besides the `component` field, and invoke the `RuntimeCompiler` if only the `component` field is given.

See [this doc](https://docs.google.com/document/d/1-LppG1cUbIDvxmgHgqxt-w95c86uSBj9ridTI-ddR-U/edit) for details.

**Comment by tbosch** [comment]
Blocked on https://github.com/angular/angular/issues/6270

**Comment by IgorMinar** [comment]
obsolete
