### ISSUE TITLE
Menu Navigation 404 not found error

### ISSUE THREAD

**Issue by kuntal-b** [angular/angular#7486]
Navigate from **REFERENCE=>Api Preview**  at https://angular.io/docs/ts/latest/  generate a 404 error.

**Comment by zoechi** [comment]
This should be reported in This should be reported in https://github.com/angular/angular.io.
I can reproduce when the left side menu is used.
It works when `Docs` is clicked in the top menu and then the link in 
> API PREVIEW
API 2.0 Preview
VIEW API
