### ISSUE TITLE
Angular2 site/ API Preview link  is not working 

### ISSUE THREAD

**Issue by micronyks** [angular/angular#7487]
I have been trying to access different APIs through API Preview link.When I try to click the link `API Preview` https://angular.io/docs/ts/latest/api.html, it says,

```
404

Whoops. Looks like what you're looking for can't be found.
```

There was/is no prior intimation on site.

I don't know where to submit or intimate about this issue. If its not suitable place let me know. I'll delete it from here.

**Comment by zoechi** [comment]
This should be reported in https://github.com/angular/angular.io.
Can you please add the URL of the page where the link is and the URL the link is pointing to. I couldn't reproduce.

**Comment by zoechi** [comment]
This should be reported in https://github.com/angular/angular.io.
Can you please add the URL of the page where the link is and the URL the link is pointing to. I couldn't reproduce.

Looks like a dup of #7486

**Comment by micronyks** [comment]
https://angular.io/docs/ts/latest/api.html. you can check this here.

**Comment by zoechi** [comment]
I was able to reproduce when opened from the menu on the left.

**Comment by zoechi** [comment]
Dup of angular/angular.io#928
please close.
