### ISSUE TITLE
Parent form - childern form relationship (way to access child form from parent form)

### ISSUE THREAD

**Issue by micronyks** [angular/angular#7488]
I want to know how can I access children form from parent form? Angular2 provides way to use multi component within single component **[one parent- multi child (children)]**. <bR>Now consider, every child component has form within. how can I access children form from parent's form???
Moreover, parent's form should be valid if every child's form is valid.
I haven't found any docs on this topic. 
This could be a new feature request if not available. 

You can check my SO question for more information : http://stackoverflow.com/questions/35860224/parent-form-child-from-communication-or-relation-or-validation

**Comment by kara** [comment]
You'll want to either pass through the `FormGroup` instance down or implement `ControlValueAccessor`.  See https://github.com/angular/angular/issues/9281#issuecomment-238610807 for more info.
