### ISSUE TITLE
Custom form control causes infinite loop

### ISSUE THREAD

**Issue by gaiottino** [angular/angular#7490]
I've found way to quite easily put Angular2 in an infinite loop. Some background: I've been trying to figure out how to properly create reusable custom form controls and have another issue here: https://github.com/angular/angular/issues/7391 where I'm trying to get help with how to pass the control and validation to e.g. an input field wrapped by a component (still looking for help with that issue)

I'm reusing the custom input I created in the previous plunkr to demonstrate the infinite loop bug here: http://plnkr.co/edit/z8xwRwdEfTJsY4FgL7F1

We only found the bug when rendering became a bit more slow which is why I've added the `RandomPipe` to the plunkr. If you type slowly, it works as intended, but if you type something fast and watch the log you'll get some nice christmas trees that won't stop until you hit the Stop-button.

```
t
te
tes
test
tes
test
testi
testin
testing
tes
test
testi
testin
testing
tes
test
testi
testin
testing
tes
```

Referring to my previous issue, the `custom-input` is coded based on information I've been able to find of how to create a custom form control that will accept `ngModel`, `ngControl` and `ngFormControl` but it feels like there is still a lack of official information of how to properly create one since I've not been able to figure out how to get hold of i.e. the validations passed to the custom control and then use then with the wrapped control elements.

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.8
- Browser: Chrome 48.0.2564.116
- Language: TypeScript

**Comment by zoechi** [comment]
If it happens only when typing fast, it's probably caused by #6311

**Comment by gaiottino** [comment]
Yeah that sounds about right.

**Comment by zoechi** [comment]
I think this can be closed
