### ISSUE TITLE
Angular2 tour of heroes guide strange behavior 

### ISSUE THREAD

**Issue by FrancescoMussi** [angular/angular#7491]
* **I'm submitting a ... **
bug report

* **What is the current behavior?**

I am following the tour-of-heroes tutorial. Currenly at the master/detail section. 
Before wrapping the detail part with  `<div *ngIf="selectedHero">` i am not able to see anymore the list of heroes, each block is blank.

But why is that?
I should still be able to see the list of HEROES.
That array exists and if i make a ngFor of it i should be able to see its element.

This template doesn't work:

    <ul class="heroes">
	    <li *ngFor="#hero of heroes" (click)="onSelect(hero)">
		    <span class="badge">{{hero.id}}</span> {{hero.name}}
	    </li>
    </ul>

    <h2>{{selectedHero.name}} details!</h2>
    <div><label>id: </label>{{selectedHero.id}}</div>
    <div>
	    <label>name: </label>
	    <input [(ngModel)]="selectedHero.name" placeholder="name"/>
    </div>

But if i delete the second part of the template and leave only the first, than it works and i can see the list.
This template works:

    <ul class="heroes">
	    <li *ngFor="#hero of heroes" (click)="onSelect(hero)">
		    <span class="badge">{{hero.id}}</span> {{hero.name}}
	    </li>
    </ul>

* **What is the expected behavior?**

In the first case i except to properly see the list of heroes.
How is possible that adding some extra feature to the view (template) can affect other part of the view previously working?
The list of heroes should be displayed properly despite the fact that select function is not finished/correct or it make debug process much more difficult no?

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.8
- Browser: [Chrome Version 48.0.2564.116 (64-bit)  ]
- Language: [TypeScript ]

**Comment by zoechi** [comment]
Seems there is missing something

> l part with
>
>i am not able t

probably some HTML that needs to be wrapped in backticks ``` to be displayed properly

**Comment by zoechi** [comment]
BTW 
GitHub issues are for bug reports and feature requests. 
      For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by FrancescoMussi** [comment]
yes the both parts of the template are included inside 
template: `...`
Just keep the html only for simplicity.

Then, since it seemed as a strange behaviour that a part of the view affect another part that was previously worked, I just thought I could signal it here.
If is not the proper place, no problem, we can close this and i can report it somewhere else.

**Comment by zoechi** [comment]
Did you check the lines quoted in my comment. In there seems to be something missing in between in your original question.

**Comment by FrancescoMussi** [comment]
Ah sorry. Edited the question.

**Comment by sensharma** [comment]
I have exactly the same issue. Any solutions/ suggestions on this?

**Comment by agouriou** [comment]
If selectedHero is not initialized, then you should have an error in the console, something like 

> "cannot read property name of undefined in <h2>{{selectedHero.name}} details!</h2>". 

So debugging process doesn't seem complicated.

**Comment by FrancescoMussi** [comment]
It's not a debug problem. It's kind of structural. When something is not working with a variable in a specific part of the view, then the whole app crash, instead of just that part. I was used to AngularJs 1 so i thought was a kind of bug, but probably is just the way Angular2 works.

**Comment by niwsa** [comment]
@FrancescoMussi So shouldn't the doc need improvement i.e instead of saying "When our app loads we see a list of heroes," something else?

**Comment by vicb** [comment]
Please reopen on angular/angular.io if still an issue. Thanks

**Comment by sreckovic** [comment]
@FrancescoMussi did you create a new ticket regarding this, I have the same exact problem, thanks!

**Comment by FrancescoMussi** [comment]
@sreckovic I don't remember exactly what was about. But most probably there was an error in the console - and the whole view was then affected.
Try to check the console and see if there are some error.

**Comment by sreckovic** [comment]
@FrancescoMussi yes, there is a console error that _co.hero is undefined, which do have some logic behind it, at that point I didn't declared hero variable or I have renamed it to heroes at some point in quick start tutorial. Anyway as it is now what happens and what is written in quick start tutorial is not the same. Will continue with quick start and hopefully this will resolve at some point. Thanks for your reply!

**Comment by alenb** [comment]
Same tutorial, but further in.

I got up to the part when you're using `http` to access data from the hero service. I noticed there's an issue when you separate out the hero details component and allow people to go it via `heroes/:id`

The issue when you go to the above URL is, `ERROR TypeError: Cannot read property 'name' of undefined`. 
It's because the data is still being loaded in via the `http`. It still displays the data and the application continues to function normally, but this error message persists on every load of the edit page.

The solution many have offered was to use `hero?.name`, however, this breaks the application completely and the error you get from using this is the following:
```
Uncaught Error: Template parse errors:
Parser Error: The '?.' operator cannot be used in the assignment at column 12 in [hero?.name=$event] in ng:///AppModule/HeroDetailComponent.html@9:11 ("
  <label>
    name: 
    <input [ERROR ->][(ngModel)]="hero?.name" placeholder="name">
  </label>
</div>
"): ng:///AppModule/HeroDetailComponent.html@9:11
Empty expressions are not allowed ("
  <label>
    name: 
    <input [ERROR ->][(ngModel)]="hero?.name" placeholder="name">
  </label>
</div>
"): ng:///AppModule/HeroDetailComponent.html@9:11
Parser Error: The '?.' operator cannot be used in the assignment at column 12 in [hero?.name=$event] in ng:///AppModule/HeroDetailComponent.html@9:11 ("
  <label>
    name: 
    [ERROR ->]<input [(ngModel)]="hero?.name" placeholder="name">
  </label>
</div>
"): ng:///AppModule/HeroDetailComponent.html@9:4, Directive DefaultValueAccessor
Parser Error: The '?.' operator cannot be used in the assignment at column 12 in [hero?.name=$event] in ng:///AppModule/HeroDetailComponent.html@9:11 ("
  <label>
    name: 
    [ERROR ->]<input [(ngModel)]="hero?.name" placeholder="name">
  </label>
</div>
"): ng:///AppModule/HeroDetailComponent.html@9:4, Directive DefaultValueAccessor
Parser Error: The '?.' operator cannot be used in the assignment at column 12 in [hero?.name=$event] in ng:///AppModule/HeroDetailComponent.html@9:11 ("
  <label>
    name: 
    [ERROR ->]<input [(ngModel)]="hero?.name" placeholder="name">
  </label>
</div>
"): ng:///AppModule/HeroDetailComponent.html@9:4, Directive DefaultValueAccessor
Parser Error: The '?.' operator cannot be used in the assignment at column 12 in [hero?.name=$event] in ng:///AppModule/HeroDetailComponent.html@9:11 ("
  <label>
    name: 
    [ERROR ->]<input [(ngModel)]="hero?.name" placeholder="name">
  </label>
</div>
"): ng:///AppModule/HeroDetailComponent.html@9:4, Directive DefaultValueAccessor
Parser Error: The '?.' operator cannot be used in the assignment at column 12 in [hero?.name=$event] in ng:///AppModule/HeroDetailComponent.html@9:11 ("
  <label>
    name: 
    [ERROR ->]<input [(ngModel)]="hero?.name" placeholder="name">
  </label>
</div>
"): ng:///AppModule/HeroDetailComponent.html@9:4, Directive NgControlStatus
Parser Error: The '?.' operator cannot be used in the assignment at column 12 in [hero?.name=$event] in ng:///AppModule/HeroDetailComponent.html@9:11 ("
  <label>
    name: 
    [ERROR ->]<input [(ngModel)]="hero?.name" placeholder="name">
  </label>
</div>
"): ng:///AppModule/HeroDetailComponent.html@9:4, Directive NgControlStatus
Parser Error: The '?.' operator cannot be used in the assignment at column 12 in [hero?.name=$event] in ng:///AppModule/HeroDetailComponent.html@9:11 ("
  <label>
    name: 
    [ERROR ->]<input [(ngModel)]="hero?.name" placeholder="name">
  </label>
</div>
"): ng:///AppModule/HeroDetailComponent.html@9:4, Directive NgControlStatus
Parser Error: The '?.' operator cannot be used in the assignment at column 12 in [hero?.name=$event] in ng:///AppModule/HeroDetailComponent.html@9:11 ("
  <label>
    name: 
    [ERROR ->]<input [(ngModel)]="hero?.name" placeholder="name">
  </label>
</div>
"): ng:///AppModule/HeroDetailComponent.html@9:4, Directive NgControlStatus
Parser Error: The '?.' operator cannot be used in the assignment at column 12 in [hero?.name=$event] in ng:///AppModule/HeroDetailComponent.html@9:11 ("
  <label>
    name: 
    [ERROR ->]<input [(ngModel)]="hero?.name" placeholder="name">
  </label>
</div>
"): ng:///AppModule/HeroDetailComponent.html@9:4, Directive NgControlStatus
Parser Error: The '?.' operator cannot be used in the assignment at column 12 in [hero?.name=$event] in ng:///AppModule/HeroDetailComponent.html@9:11 ("
  <label>
    name: 
    [ERROR ->]<input [(ngModel)]="hero?.name" placeholder="name">
  </label>
</div>
"): ng:///AppModule/HeroDetailComponent.html@9:4, Directive NgControlStatus
Parser Error: The '?.' operator cannot be used in the assignment at column 12 in [hero?.name=$event] in ng:///AppModule/HeroDetailComponent.html@9:11 ("
  <label>
    name: 
    [ERROR ->]<input [(ngModel)]="hero?.name" placeholder="name">
  </label>
</div>
"): ng:///AppModule/HeroDetailComponent.html@9:4, Directive NgControlStatus
Parser Error: The '?.' operator cannot be used in the assignment at column 12 in [hero?.name=$event] in ng:///AppModule/HeroDetailComponent.html@9:11 ("
</div>
<p>
  <button [ERROR ->](click)="save()">save</button>
</p>"): ng:///AppModule/HeroDetailComponent.html@13:10
    at syntaxError (compiler.js:2427)
    at TemplateParser.push../node_modules/@angular/compiler/fesm5/compiler.js.TemplateParser.parse (compiler.js:20311)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._parseTemplate (compiler.js:25857)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileTemplate (compiler.js:25844)
    at compiler.js:25787
    at Set.forEach (<anonymous>)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileComponents (compiler.js:25787)
    at compiler.js:25697
    at Object.then (compiler.js:2418)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileModuleAndComponents (compiler.js:25696)
```

**Please note,** this only occurs when the `?` operator is used in the `ngModel`. When used on `<h2>{{hero?.name | uppercase}} Details</h2>` it works just fine.

The best solution I found is to wrap the entire hero details Html in an `if` instead:
```
<div *ngIf="hero"></div>
  <h2>{{hero.name | uppercase}} Details</h2>
  <p>
    <button (click)="this.location.back()">go back</button>
  </p>

  <div>id: {{hero.id}}</div>
  <div>
    <label>
      name: 
      <input [(ngModel)]="hero.name" placeholder="name">
    </label>
  </div>
  <p>
    <button (click)="save()">save</button>
  </p>
</div>
```

Am I doing something incorrectly?
