### ISSUE TITLE
RouterOutlet loads component 2x in a race condition

### ISSUE THREAD

**Issue by tbosch** [angular/angular#7497]
`RouterOutlet#reuse` checks if there is no current `_componentRef` and in that case creates a new component.
However, `_componentRef` is not set until the call to `DynamicComponentLoader.loadNextToLocation` is finished (in `RouterOutlet#activate`). If that call takes a bit longer (e.g. loading an html file from the server) `RouterOutlet` will create 2 instances of the component.

On my branch for codegen templates that changes the timing of `DynamicComponentLoading` a bit, the test for `syncRoutesWithDynamicComponents` (in `sync_route_spec_impl.ts`) fails because of this.

**Comment by tbosch** [comment]
Setting to P1 as the issue the commit that introduced this logic was marked as P0...

**Comment by naomiblack** [comment]
@mhevery can you figure out who should work on this one? It seems to be related to https://github.com/angular/angular/pull/7318. Tests for the codegen branch are failing because of this issue.
