### ISSUE TITLE
Conflicting, incorrect API doc for HostBinding

### ISSUE THREAD

**Issue by wardbell** [angular/angular#7500]
**I'm submitting a ...**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, see note at the top of this template.

API documentation conflict for `@HostBinding`.

Explained in (now closed) [issue #904 in angular.io](https://github.com/angular/angular.io/issues/904)

**Comment by vicb** [comment]
`()` is not supported (use `HostListener` instead)
`[]` is not supported (implied)

**Comment by francosioquim** [comment]
Closed #7500.

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/angular/angular/issues/7500#event-815564273
