### ISSUE TITLE
cheatsheet glitch

### ISSUE THREAD

**Issue by wardbell** [angular/angular#7504]
**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] support request

![glitch](https://cloud.githubusercontent.com/assets/13602053/12261319/3f706c7e-b95b-11e5-9cf2-e5d12793abcc.png)

See [angular.io issue 670](https://github.com/angular/angular.io/issues/679)

**Comment by naomiblack** [comment]
@petebacondarwin -- any chance you could fix this one?

**Comment by petebacondarwin** [comment]
This is already fixed at https://github.com/angular/angular/commit/c8e909f8c9f0b18a6728b0088851099f54ca7826
