### ISSUE TITLE
Infinite loop with javascript es5 when constructor functions are unnamed

### ISSUE THREAD

**Issue by micaelmbagira** [angular/angular#7507]
**Note: for support questions, please use one of these channels:** https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
[x] bug report

* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behavior?**
When the app has at least 2 components with an unnamed constructor (`constructor: function() { }`), the app goes into an infinite loop that increases the CPU and memory usage until the page crashes.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via

**Here is a demo project you can clone to reproduce the issue : [https://github.com/micaelmbagira/angular-issue-7507](https://github.com/micaelmbagira/angular-issue-7507).**  
Or here is the source code :
*jspm version is 0.17.0-beta.9*

*index.html:*
````html
<!doctype html>
<html>
  <head>
  </head>
  <body>
    <App>Loading...</App>
  </body>
  <script src="jspm_packages/system.js"></script>
  <script>
    System.config({
      defaultExtension: 'js',
      transpiler: 'plugin-babel',
      map: {
          'plugin-babel': 'npm:systemjs-plugin-babel@0.0.8',
      }
    });
    System.import('index.js');
  </script>
</html>
````
**index.js**
````javascript
import 'reflect-metadata';
import 'zone.js';
import ng from 'angular2/bootstrap';
import Main from './app/main.js';

ng.bootstrap(Main);
````
**main.js**
````javascript
import ng from 'angular2/core';
import Header from './header.js';

export default ng.Component({
  selector: 'App',
  template:
    '<div>' +
      '<Header></Header>' +
      '<p>Hello</p>' +
    '</div>',
  directives: [Header]
})
.Class({
  constructor: function () {}
});
````
**header.js**
````javascript
import ng from 'angular2/core';

export default ng.Component({
  selector: 'Header',
  template:
    '<header class="header">' +
      '<p>Header</p>' +
    '</header>'
})
.Class({
  constructor: function () {}
});
````
The problem doesn't happen if you add a name to constructors of both javascript file like this : 
````javascript
.Class({
  constructor: function headCons () {}
});
````

* **What is the expected behavior?**

The header should be displayed and the app should not crash

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.8
- Browser: all
- Language: ES5

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
As explained above, a workaround is to *name each constructor function* (by the way, this issue does not happen when there is only 1 component in the app)

**Comment by zoechi** [comment]
@micaelmbagira so, what was the issue, how did you solve it?

**Comment by micaelmbagira** [comment]
The issue disappeared on beta.11 and changed into this one https://github.com/angular/angular/issues/7747

**Comment by micaelmbagira** [comment]
Actually, it has not disappeared, it was only hidden by https://github.com/angular/angular/issues/7747, but after fixing 7747, it's still there.

**Comment by micaelmbagira** [comment]
Obsolete, is fixed now.
