### ISSUE TITLE
Getting Error during evaluation of "click" on production build

### ISSUE THREAD

**Issue by deepakgd** [angular/angular#7508]
In development, everything is working fine. But in production same code is not working showing error as below. 
```
**Uncaught EXCEPTION: Error during evaluation of "click"
ORIGINAL EXCEPTION: TypeError: this.directive_0_0.onClick is not a function
ORIGINAL STACKTRACE:
TypeError: this.directive_0_0.onClick is not a function
    at e.ChangeDetector_e_0.handleEventInternal (viewFactory_e:224:35)**
```

How to fix this issue?

**Comment by ericmartinezr** [comment]
dup of https://github.com/angular/angular/issues/6678

Change to use non-minified bundles, or use `mangle:false` if you're using bundlers (webpack, jspm, etc)

**Comment by deepakgd** [comment]
Hi @ericmartinezr Can you please explain how to do?

This is my code:

```
var webpack = require('webpack');
var path = require('path');

module.exports = {
  entry: {
    'app': './src/app.ts',
    'vendor': './src/vendor.ts'
  },
  output: {
    path: path.join(__dirname, 'dist'),
    filename: "bundle.js"
  },
  plugins: [
    new webpack.optimize.CommonsChunkPlugin('vendor', 'vendor.bundle.js')
  ],

  resolve: {
    extensions: ['', '.ts', '.js']
  },

  module: {
    loaders: [
      { test: /\.ts$/, loader: 'ts-loader' },
    ],
    noParse: [ /angular2\/bundles\/.+/ ]
  },

  devServer: {
    historyApiFallback: true
  }
};
```

**Comment by ericmartinezr** [comment]
That's weird, you have nothing minifying/mangling your bundle. Try this comment https://github.com/angular/angular/issues/6678#issuecomment-192436233

Are you using some seed project?

**Comment by deepakgd** [comment]
yes in github [angular2/angular-seed](https://github.com/angular/angular2-seed)

**Comment by ericmartinezr** [comment]
@deepakgd ok, try the comment above (the one I referenced).

@gdi2290 sorry for pinging. Can you comment on this one? The config doesn't seem to be minifying/mangling the bundle, anything I may be missing?

**Comment by deepakgd** [comment]
Thanks @ericmartinezr I did. actually config done in gulpfile. now its working fine.
