### ISSUE TITLE
Expose route name on Router.currentInstruction

### ISSUE THREAD

**Issue by oliverjanik** [angular/angular#7509]
Continuing from #5335.

Can you please add route name to the currentInstruction. This would be very handy for conditional behaviour when multiple routes point to the same component.

**Comment by btford** [comment]
:+1:

**Comment by PavelPZ** [comment]
I thing that "accessing route name from instruction" request in #5318 is more general solution, I am right?

**Comment by vsavkin** [comment]
We are no longer maintaining the deprecated router to focus our efforts on making the new router solid.

It doesn't look like the issue makes sense in the context of the new router. If you think it does, please reopen the issue.

Closing this issue.
