### ISSUE TITLE
Delete _analyzer.dart files after successful analysis

### ISSUE THREAD

**Issue by kevmoo** [angular/angular#751]
I could see leaving them there if analysis fails to aid debugging, but if analysis succeeds they are just confusing

**Comment by naomiblack** [comment]
@jakemac53 can you take this one on?

**Comment by naomiblack** [comment]
This is ugly but not urgent. As long as they aren't checked into the packages that get published, it's not a big deal.

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.
