### ISSUE TITLE
Emit routing events

### ISSUE THREAD

**Issue by zackarychapple** [angular/angular#7510]
* I'm submitting a ... *

[ x ] feature request
* **What is the current behavior?**
Currently there is no way to subscribe to the routing events.  When it comes to measuring user performance / user behavior having the routing events allows us visibility into the behavior of both the user and the application as a whole in the wild.   This is something that ui.router has and I think would be a great addition to the new router. 

- Angular version: [2.0.0-beta.8]
- Browser: [all]
- Language: [all]

**Comment by nigeman** [comment]
Isnt this what your after? Or are you expecting further features?

```
import {Route} from 'angular2/router';

export class Main {

    constructor(private router: Router) {
        router.subscribe(path => {
            // Router change event
        });
    }

}
```

**Comment by zackarychapple** [comment]
I am looking for a little bit more than just the path change. [ ui.router](https://github.com/angular-ui/ui-router/wiki#state-change-events) has events for the start of a state change as well as when the view is loaded.  

For this router I think having events around the following would be useful:

- pathChangeStart
- altRouteStart
- pathChangeDone
- altRouteDone
- viewLoaded (this is after any resolutions are complete and bindings are resolved)

**Comment by nigeman** [comment]
Yeah those events are handy but I am not sure they are going to be implemented anytime soon into angular2 ( I could be wrong )

Take a look at this ticket. https://github.com/angular/angular/issues/5175

**Comment by nigeman** [comment]
@zackarychapple probably not perfect ( someone can correct me ) But you can extend from the current RouterOutlet directive and write your own logic. Just add this in the list of directives where you start your router-outlet.

```
import {Directive, Attribute, ElementRef, DynamicComponentLoader} from 'angular2/core';
import {Router, RouterOutlet, ComponentInstruction} from 'angular2/router';

@Directive({
	selector: 'router-outlet'
})

export class CustomRouterOutlet extends RouterOutlet {
	private parentRouter: Router;

	constructor(_elementRef: ElementRef, _loader: DynamicComponentLoader,
	            _parentRouter: Router, @Attribute('name') nameAttr: string) {
		super(_elementRef, _loader, _parentRouter, nameAttr);

		this.parentRouter = _parentRouter;

		this.parentRouter.subscribe(()=> {
			console.log('routeEnded?');
		})
	}

	activate(instruction: ComponentInstruction) {
		console.log('routeStarted??');

		return super.activate(instruction);
	}
}
```

**Comment by brandonroberts** [comment]
What's the difference between altRouteStart and pathChangeStart?

**Comment by vsavkin** [comment]
We are no longer maintaining the deprecated router to focus our efforts on making the new router solid. And the new router allows you to subscribe to routing events.

Closing this issue.
