### ISSUE TITLE
Route initialized twice when reached using navigate function 

### ISSUE THREAD

**Issue by ericj79** [angular/angular#7515]
**Note: for support questions, please use one of these channels:** https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
My application is displaying a certain route. From that route when the user makes certain selections, the injected root routers *navigate* function is called, passing in the path to this route , and a parameters with values to denote the current selections. one of those paramters is an object so I stringify it and URI encode it. (This allows the query parameters in the URI to be updated so the user can link directly to the current settings again.) The routes *$routerOnActivate* function is then called twice. Which in this case kicks off an unwanted second request to the server for data.
I am able to block this second request using the *$routerCanDeactivate* hook and checking if the parameters are the same between the next and previous routes. (I noticed that on the first call to activate the route the parameters are in the order I defined them. The second call has them in a new order. If I update the order I define them in to match that order they do not change between calls.)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
http://plnkr.co/edit/45efcNTMnLAIATgwPEsu?p=preview
click on the button and the initialization count increments by twos

* **What is the expected behavior?**
The activate function should only be called once.

* **What is the motivation / use case for changing the behavior?**
avoid routes being initialized multiple times for now reason

* **Please tell us about your environment:**

- Angular version: 1.5.0 (ngComponentRouter 0.2.0)
- Browser: Firefox 46.0a2
- Language: ES5

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
The uri encoded stringified version of the object seems to change between the two calls, although the JSON version seems to be identical.

**Comment by ericj79** [comment]
I was able to resolve this issue by switching how I encoded the object. When I switched the encoding to use *encodeURI*, instead of *encodeURIcomponent*, the route stopped being initialized twice.
My guess for what was happening is that the router was updating everything based on the navigation call I made, but when the browsers location bar was set with the route the browser was transforming it to a simpler form. Then the router was triggering on the location bar not matching its location updating the view to match the new location.
The router could check to do the transformation itself, but that may have unintended consequences for some user. It is probably better to have people do this step on their own, so they no how to reverse it on the other end.
A paragraph in the router documentation about a recommended way to pass objects might be beneficial though.

**Comment by jarbitlira** [comment]
For any other person that have the same issue.
I fix with a little 'hack' in the controller, i think that is not correct but was my fast solution

You can see my [solution here](https://gist.github.com/jarbitlira/df14cc9212ad4ce1c803ee309d569f29)

**Comment by cmoonExpedia** [comment]
Have the same problem. hopefully fix this soon.

**Comment by vicb** [comment]
If still an issue with ng2.0.1 & the latest router, please re-open with an up to date plunker. thanks.
