### ISSUE TITLE
Asynchronous router navigation with OnPush change detection does not load initial data.

### ISSUE THREAD

**Issue by dougmill** [angular/angular#7519]
* **I'm submitting a ... **
[x] bug report

* **Do you want to request a *feature* or report a *bug*?**
Report a *bug*.

* **What is the current behavior?**
When router navigation is done in an asynchronous callback, and a parent component of the target route has change detection strategy set to OnPush, the routed component is displayed with all data empty - even data set in the constructor is ignored.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

[Demonstration plunker](https://plnkr.co/edit/mAZUTEDnSqfnNcJd9QVi?p=preview)
Click the button to navigate asynchronously, and the routed component will display the contents of its template, but not the data string ("This is data"), even though that string is set in the component's constructor. Click the synchronous navigation button, and the data string is displayed as expected.

If the OnPush change detection setting is commented out, both buttons display the data string as expected.

* **What is the expected behavior?**
Data that is set in a component's constructor or ngOnInit() method should always be loaded into the template no matter how the component is navigated to or what change detection strategy is used.

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.8
- Browser: [Chrome 48]
- Language: [TypeScript | Dart]
I tried testing the plunker in IE, but it just gives me a console error:
[object Error]{description: "undefined", message: "Object doesn't support property or method 'keys'", name: "Error", number: NaN, stack: "TypeError: ..."}

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
Automatically calling markForCheck() on the change detector for the component being navigated to should make it work. Calling it manually is a viable workaround, but shouldn't be necessary - at least not for data set in the component's constructor.

**Comment by nosachamos** [comment]
I believe this can be closed now that the [new router](https://github.com/angular/vladivostok) is on the way.
