### ISSUE TITLE
ng-repeat render order reversed by ng-if

### ISSUE THREAD

**Issue by jamesbrobb** [angular/angular#752]
Expected behaviour with `replace: true` on element created by `ng-repeat`

http://plnkr.co/edit/qG9zBzFg857NiOWBdDOI?p=preview

Reversed behaviour when `ng-if` is on root element using `replace: true`

http://plnkr.co/edit/3AlGxz3YAvYbTURQ6nnW?p=preview

The issue does not exist when using `template` instead of `templateUrl`

http://plnkr.co/edit/ErWSV8IWBwVazF9aOt4d?p=preview

**Comment by otodockal** [comment]
Wrong repo! Please, move your issue to the Angular 1.x repo https://github.com/angular/angular.js
