### ISSUE TITLE
Dehydrated Detector on number values in ngModel in ngFor

### ISSUE THREAD

**Issue by hansl** [angular/angular#7520]
* **I'm submitting a ... **

* [x] bug report
* [ ] feature request
* [ ] support request => Please do not submit support request here, see note at the top of this template.

-----

* **What is the current behavior?**

https://plnkr.co/edit/KQe81xC6huNj1vaOEzry?p=preview

Having an array of number, an `ngFor` on those items, and banana-boxing the `ngModel` to an element in it generates an exception `"Attempt to use a dehydrated detector: InputDemo_1 -> ngModelChange"`.

Banana-boxing an `ngModel` on one of the items (like `items[3]`) works, and iterating over a list of objects and banana-boxing the `ngModel` on a key of those objects work. It's only this special case.

* **What is the expected behavior?**

Items should be modified. This is pretty self explanatory.

**Comment by vijayaragavendiran** [comment]
+1
 When I dynamically created the text box and once I change the value I am getting this issue. Please guide me 

Vijay

**Comment by kara** [comment]
@hansl Tested this case with the latest master and it seems to work now. Closing!
