### ISSUE TITLE
Doc (changelog.md): Angular2 2.0.0-beta.9 (2016-03-09) CHANGELOG.md -  breaking changes same information is displayed twice.

### ISSUE THREAD

**Issue by micronyks** [angular/angular#7523]
Angular2 2.0.0-beta.9 (2016-03-09) CHANGELOG.md - breaking changes document information needs to be fixed as it is shown **_same information two times_** !

check here : https://github.com/angular/angular/blob/master/CHANGELOG.md

**Please let me know where to submit this doc change? If this is not the right place, I'll submit it at right place.**

**Comment by laco0416** [comment]
#7521

**Comment by micronyks** [comment]
Sent fix in https://github.com/angular/angular/pull/7524

**Comment by pkozlowski-opensource** [comment]
This was fixed in master.
