### ISSUE TITLE
UpgradeAdapter throws "Error: Expecting HostViewFactoryRef..." when downgrading a ng2 component

### ISSUE THREAD

**Issue by kvantetore** [angular/angular#7525]
Downgrading ng2 components crashes when mixing ng1 and ng2 components to a certain level of complexity. "ng1 app" -> "ng2 comp" -> "ng1 comp" -> "inner ng2 comp"

http://plnkr.co/edit/5yVFDBOcRHIwGrWwewrV?p=preview

I've seen #7027, but I'm definitely not bootstrapping before downgrading.

Tested on 
- Angular version: 2.0.0-beta.9
- Browser: Chrome, Firefox, Edge

**Comment by kvantetore** [comment]
Possible fix:

https://github.com/kvantetore/angular/commit/aef29ee25c0d702d6e388c3eae61ee43159bddd8

**Comment by alexandrejunges** [comment]
I ran into this same problem.
I updated to the last version of angular (beta 17), and the error message changed to: 
`Expecting ComponentFactory for: [componentName]`

Have you found a workaround?

**Comment by naeramarth7** [comment]
> Expecting ComponentFactory for: [componentName]

Ran in this issue having code structured in different files, of course. My mistake was creating a `new UpgradeAdapter()` in each of them, though you need to **use the same instance**, otherwise the one calling `bootstrap` won't be aware of the downgraded components.

**Comment by Bolza** [comment]
@kvantetore the Angular guys are ready to merge your PR but you need to rebase it, the codebase is changed a lot in the meantime and your patch needs to be applied on the new one

**Comment by alexsapps** [comment]
for people who reach this page regarding error:

`angular.js:14078 Error: Expecting ComponentFactory for: YourComponent
`
be sure to include the component's class in the declarations array in your Ng2AppModule that is passed to the upgrade adapter.

```
@NgModule({
  declarations: [
    YourComponent,
  ],
})
class Ng2AppModule {
}
```

**Comment by jashmenn** [comment]
In addition to @alexsapps, for folks who reach this page with the error:

```
angular.js: Error: Expecting ComponentFactory for: YourComponent
```

I've also seen this error if your version of `@angular/core` is out of sync with `@angular/upgrade`.

**Comment by gkalpak** [comment]
AFAICT, everything works as expected and the errors are not ngUpgrade-specific.
If anyone is still having issues and believe there is something we can improve in ngUpgrade, please open a new issue (providing all the necessary details).
