### ISSUE TITLE
Compiler's url_resolver.dart default package URL forbids deployement in folders

### ISSUE THREAD

**Issue by cporte** [angular/angular#7527]
The current [url_resolver of the dart compiler](https://github.com/angular/angular/blob/master/modules/angular2/src/compiler/url_resolver.dart) configures a default provider resolving "package:" uri to "/packages" URLs.

This prevents deployement of compiled Angular 2 dart applications in sub-folders, as resolved URL will be `http://domain/packages/**` instead of `http://domain/subfolder/packages/**`

Plus, I didn't figure out how to override this default provider. So my current workaround is to replace "/packages" by "packages" in the generated index.dart.js

- Angular version: 2.0.0-beta.6
- Browser: [all]
- Language: [Dart]

**Comment by pkozlowski-opensource** [comment]
Obsolete as Dart-specific.
