### ISSUE TITLE
JSONP error while calling apache solr rest api.

### ISSUE THREAD

**Issue by prakash-choudhary** [angular/angular#7529]
Hi,

This is my JSONP call.

> import {Injectable} from 'angular2/core';
> //import {CONTENTS} from './mock-searchdata';
> import {Ajaxconfig} from './ajaxconfig';
> import {Http,Jsonp, Response,URLSearchParams} from 'angular2/http';
> import {Observable}     from 'rxjs/Observable';
> 
> @Injectable()
> export class SearchService {
>         constructor (private jsonp: Jsonp) {}
>         //private url = Ajaxconfig.getBaseURL() + "/typeahead?q=";
>         private url = "http://localhost:3030/solr/ens/typeahead?";
>         getSearchData(searchQuery: string){
>                //return CONTENTS;
>                //return this.http.get(this.url+searchQuery);
> 
>                /*return this.http.get(this.url+searchQuery)
>                                 .map(res => res.json().data)
>                                 .do(data => console.log(data)) // eyeball results in the console
>                                 .catch(this.handleError);*/
>                var params = new URLSearchParams();
>                params.set('q', searchQuery); // the user's search value
>                params.set('wt', 'json');
> 
>                return this.jsonp.get(this.url,{ search: params }).subscribe(response => console.log(response.json()),error=>console.log(error),()=>console.log("completed"));//.map(request => <string[]> request.json()[1]);
>         }
> 
>         private handleError (error: Response) {
>           // in a real world app, we may send the error to some remote logging infrastructure
>           // instead of just logging it to the console
>           console.error(error);
>           return Observable.throw(error.json().error || 'Server error');
>         }
> }

I am able to see proper success call in chrome network tab i.e status 200.
I can also see the response from network tab, but in console I get error.

![image](https://cloud.githubusercontent.com/assets/16873294/13672223/df103432-e6f9-11e5-8ea0-ba7eee5092e6.png)

![image](https://cloud.githubusercontent.com/assets/16873294/13672174/ae69cf50-e6f9-11e5-941e-f077e2c955d9.png)

=============API Response=============

{
  "responseHeader":{
    "status":0,
    "QTime":1},
  "response":{"numFound":62,"start":0,"docs":[
      {
        "title_s":"Samantha Who?"},
      {
        "title_s":"Afro Samurai"},
      {
        "title_s":"Afro Samurai"},
      {
        "title_s":"Same Sex America"},
      {
        "title_s":"Same Sex America"},
      {
        "title_s":"Sam & Cat #124"},
      {
        "title_s":"Sam & Cat #125"},
      {
        "title_s":"Sam & Cat #999"},
      {
        "title_s":"Samantha Who? Season 1"},
      {
        "title_s":"Samantha Who? Season 2"}]
  }}

====================================

Please let me know what is missing since its a cors ajax call, I am using JSONP

**Comment by pkozlowski-opensource** [comment]
@prakash-choudhary please direct support questions to an appropriate channel: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by chevalierc** [comment]
@prakash-choudhary  did you figure this out? Have the same problem

**Comment by prakash-choudhary** [comment]
Yes for me I was missing these two parameters in JSONP call, 
wt=json&json.wrf=JSONP_CALLBACK

After adding these parameters in the request URL I was able to get the response.
