### ISSUE TITLE
Js2Dart transpiler doesn't fully support Promise.then() and Promise.catch()

### ISSUE THREAD

**Issue by b-laporte** [angular/angular#753]
Promise.then doesn't currently support a 2nd argument, and Promise.catch generates a transpiler error.
As an example the following samples fail:
```
// in integration_spec.js
it('should support Promise.catch()', (done) => {
      tplResolver.setTemplate(MyComp, new Template({inline: '<div></div>'}));
      compiler.compile(MyComp).then(() => {
        done();
      }).catch((err) => { // this generates an 'identifier expected' exception
        done();
      });
 });

it('should support Promise.then()', (done) => {
      tplResolver.setTemplate(MyComp, new Template({inline: '<div></div>'}));
      // raises: incorrect number of arguments passed to method named 'then'
      compiler.compile(MyComp).then(() => {
        done();
      },(err) => {
        done();
      });
 });
```

**Comment by vicb** [comment]
@b-laporte there is a `PromiseWrapper` in `async.js`:

`PromiseWrapper.then(promise, successFn, errorFn)`, if `successFn` is `null`, this is a `catch` - may be we can add a `catch` on the `PromiseWrapper`

**Comment by b-laporte** [comment]
OK - thanks - I thought PromiseWrapper was only used to create promises (i.e. to wrap `Promise.resolve`, `Promise.reject`, etc.) but I realize now that it should also be used to call functions returning promises (at least when we want to pass an error function). So `PromiseWrapper.then` solves the 2-arguments problem - and we can live without `catch()`. `PromiseWrapper.catch(promise, errorFn)` would not have much added value IMO, so I will close the issue - thanks!
