### ISSUE TITLE
Feature request: Flag to disable HTMLParser in TemplateNormalizer

### ISSUE THREAD

**Issue by baloodevil** [angular/angular#7530]
Allow invalid HTML within ngContent templates. Specifically, HTML fragments, like an opening tag (`<table>`) without a closing tag.  Example...

In component  #template...
`<ng-content select="HeaderTemplate"></ng-content>...<ng-content select="FooterTemplate"></ng-content>`

In page using component...
`<HeaderTemplate><table></HeaderTemplate><FooterTemplate></table></FooterTemplate>`

This throws `Template parse errors: Unexpected closing tag "HeaderTemplate"`.  See [plunker](http://plnkr.co/edit/UDbfinkFxisMbWmiOeJ1) for the beginning of a re-implementation of a Repeater control.

If HTMLParser in [TemplateNormalizer](https://github.com/angular/angular/blob/master/modules/angular2/src/compiler/template_normalizer.ts#L51) could be disabled with a flag, it would allow more types of controls to be developed, like [ASP.NET's Web Controls](http://www.w3schools.com/aspnet/aspnet_repeater.asp) of yore, with nearly identical syntax.  While those controls are old, they are still widely used in corporations.  Supporting a nearly seamless transition from ASP.NET Web Forms to Angular 2 would attract more users.

[#6303](https://github.com/angular/angular/issues/6303) would also need resolved.

**Comment by CaptainCodeman** [comment]
It doesn't need to be malformed HTML, just "not great" (invalid? there's probably a proper word for it).

For example, just having `<p><div></div></p>` will make it blow up. see: http://plnkr.co/edit/Ado1bkRXrsRHj5KJdZlr

I get that some HTML is 'wrong' but sometimes that's not the focus of what you're working on - the HTML / CSS may be what it is for whatever reason and you need to work with it.

**Comment by vicb** [comment]
You can override the `TemplateNormalizer` (now `DirectiveNormalizer`) if you need this behavior
