### ISSUE TITLE
feat(Router): expose GeneratedUrl

### ISSUE THREAD

**Issue by ericmartinezr** [angular/angular#7531]
**I'm submitting a ...**
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**

With the new beta 9 we can use regex and serializers. The example in this commit https://github.com/angular/angular/commit/75343eb34007579be9cdc803da834c38e02ae12c is as follows 

```
{ regex: '[a-z]+.[0-9]+',
    serializer: (params) => `{params.a}.params.b}`,
    component: MyComponent }
```

But that doesn't work, it actually needs `GeneratedUrl` to work correctly (thanks @brandonroberts).

So the example would look like this

```
{ regex: '[a-z]+.[0-9]+',
    serializer: (params) => new GeneratedUrl(`{params.a}.params.b}`),
    component: MyComponent }
```

Currently `GeneratedUrl` must be imported from `angular2/src/router/rules/route_paths/route_path`

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

Not a bug, but here's a plnkr with the example working http://plnkr.co/edit/mk8wPfoqS66Qsuu2yN4F . Remove `GneratedUrl`, let the plnkr as is shown in the commit example and you'll get 'undefined' in the url.

* **What is the expected behavior?**

`GeneratedUrl` should be imported from `angular2/router`

* **What is the motivation / use case for changing the behavior?**

Simplify routing

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.9
- Browser: [all]
- Language: [all]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Conversation with the great @brandonroberts where he finally found out that I was missing `GeneratedUrl`

https://gitter.im/angular/angular?at=56e183b56fde057c268583a7 (read from there)

**Comment by brandonroberts** [comment]
CC: @petebacondarwin

**Comment by petebacondarwin** [comment]
Actually I think this is a bug. We should be expecting the serializer to return a string, IMO.
What do you think?

**Comment by brandonroberts** [comment]
I was expecting to return a string also. How will the optional params work returning a string? Another question is the regex only for serializing params or can it be used in path matching for routes/child routes also?

**Comment by brandonroberts** [comment]
Nevermind about the path matching question.

**Comment by naomiblack** [comment]
Closing in favor of a more general issue to catch others like these. Will revisit post-2.0

**Comment by jylinman** [comment]
FYI anyone looking for this I believe the import is now

`import { GeneratedUrl } from '@angular/router-deprecated/src/rules/route_paths/route_path';`

**Comment by zoechi** [comment]
@jylinman you can't mix imports from `@angular/router` and `@angular/router-deprecated`

**Comment by jylinman** [comment]
@zoechi Then what should it be?  There is no `@angular/router`

**Comment by zoechi** [comment]
@jylinman I don't know about `GeneratedUrl`, I just wanted to point out that if you have imports to `@angular/router` in your application you must not have imports to `@angular/router-deprecated`. If you are using `@angular/router-deprecated` it's fine to import other stuff of course, but then don't import from `@angular/router`. Just don't mix these two.

**Comment by jylinman** [comment]
@zoechi Which version has `@angular/router`?  I don't see it anywhere in the package.  I only see router-deprecated on https://angular.io/docs/ts/latest/tutorial/toh-pt5.html as well...  I was wondering if there was a new router but can't see it.  Do you know the trick? :D

**Comment by zoechi** [comment]
Ignore the new router for now until it's clear how they will go forward with the router topic. The new router misses basic features and has several issues.
