### ISSUE TITLE
bug(Router) (Dart only) Router stops receiving updates after first error

### ISSUE THREAD

**Issue by tiziano88** [angular/angular#7532]
Branching from #7349 .

In Dart, subscribing to Router changes happens via the `ObservableWrapper` class, which [always passes `cancelOnError: true`](https://github.com/angular/angular/blob/169869a195438fc6eaa7181242a6a75b0f61a284/modules/angular2/src/facade/async.dart#L31) when subscribing to the underlying `Stream` object. This has the effect that, after the first error (e.g. incorrect URL entered by the user), future updates are lost.

I am not familiar with the reasons behind unconditionally setting `cancelOnError: true`, but if that was not a hard requirement, perhaps just removing it or allowing setting it via an explicit argument would solve this issue.

**Comment by tiziano88** [comment]
I have a workaround for this issue:

```dart
void _subscribe(_) {
  // Recursively re-subscribe to router upon error.
  _router.subscribe(_update, _subscribe)
}

void _update(String url) {
  // Do stuff.
}
```

**Comment by naomiblack** [comment]
@petebacondarwin are you familiar enough with the code from the prior fix to have a go at this one?

**Comment by petebacondarwin** [comment]
@naomiblack - this is not strictly a router problem. It is just that now the router emits the `onError` on the subscription it is showing up the difference between the Dart and TS versions of the facade.

We need to identify why the Dart version of `ObservableWrapper.subscribe()` cancels the subscription upon error.

**Comment by petebacondarwin** [comment]
The commit where this behaviour was define is https://github.com/angular/angular/blame/a97a2266d34ae6acd072c239cc704b7702ef1b95/modules/angular2/src/facade/async.dart#L37

**Comment by petebacondarwin** [comment]
Having been educated in the ways of Rx and Observables I now understand that they should indeed close the observable stream when an error occurs.

Instead, I propose that we change the API to expose an Observable stream that contains a sequence of Router change events, which can have a status of either success:

```
{ status: 'success', next: ..., previous: ... }
```

or failure
```
{ status: 'fail', next: ..., previous: ... }
```

**Comment by tiziano88** [comment]
@petebacondarwin thanks for the fix, it looks like it would fix the problem! Any plan to merge it into master soon?
