### ISSUE TITLE
Bug: tick fails to handle rxjs timed sequences

### ISSUE THREAD

**Issue by jamesbs** [angular/angular#7533]
**Case:** Create a timed observable and test its behaviour using `fakeAsync`/`tick`.

```
describe("failed test", () => {
   it("rxjs delay", inject([], fakeAsync(() => {
       const obs = Rx.Observable.of("message").delay(1000);
       let result = "";

       obs.subscribe(val => result = val);

       tick(2000);

       expect(result).toBe("message");
    })));
});
```

**Result:**

```
Expected '' to be 'message'.
    at example.spec.js:78:34
    at testing.dev.js:1366:22
    at Zone.run (angular2-polyfills.js:1243:24)
    at testing.dev.js:1365:31
Failed: 1 timer(s) still in the queue.
Error: 1 timer(s) still in the queue.
    at new BaseException (angular2.dev.js:7385:21)
    at testing.dev.js:1374:15
    at FunctionWrapper.apply (angular2.dev.js:327:17)
    at FunctionWithParamTokens.execute (testing.dev.js:1947:37)
    at TestInjector.execute (testing.dev.js:1868:17)
    at Object.<anonymous> (testing.dev.js:2006:44)
```

**Expected:** Observable to resolve to completion since the time simulated by tick is greater than the observable's delay.

**Version:** angular2@2.0.0-beta.8, rxjs@5.0.0-beta2
**Platform:** karma@0.13.21, jasmine-core@2.3.2, chrome@48.0.2564, typescript@1.8.2

**Comment by vankeer** [comment]
I had the same issue and unsubscribing fixed it.

```ts
let subscription = obs.subscribe(val => result = val);
tick(2000);
expect(result).toBe("message");
subscription.unsubscribe();
```

**Comment by larrifax** [comment]
I have the same issue, and @vankeer's workaround did not solve it. I even tried cloning @juliemr's [ng2-test-seed](https://github.com/juliemr/ng2-test-seed) and adding the above mentioned test to it. No luck there either, so it shouldn't be a problem with my test environment setup.

https://github.com/angular/angular/issues/8251 may be related to this issue.

**Comment by larrifax** [comment]
Looks like there's a duplicate issue with more detailed information about this issue: #10127
