### ISSUE TITLE
date pipe not working for date '2008-06-17T00:00:00'

### ISSUE THREAD

**Issue by asiacoll** [angular/angular#7534]
when using "{{item?.datum | date}} in html template". the date is an original date from a database.
error message:
EXCEPTION: Invalid argument '2008-06-17T00:00:00' for pipe 'DatePipe' in [
                {{item?.datum | date}} in ArtikelListComponent@94:44]

**Comment by ericmartinezr** [comment]
see https://github.com/angular/angular/issues/3261

**Comment by asiacoll** [comment]
it works when using following codes : 

{{ stringAsDate(sampleValue) | date }}
 with
 stringAsDate(dateStr) {
 return new Date(dateStr);
 }

**Comment by Slaals** [comment]
Hi,

You can create a pipe `@Pipe` as the following : 

```
@Pipe({
  name: 'dateFormat'
})
export class DateFormat {
  transform(date, args) {
    return new Date(date);
  }
}
```

Then include the pipe in your Component. To use it you just have to write `{{item?.datum | dateFormat}}`. This will do the work.

**Comment by asiacoll** [comment]
thanks for the info.

**Comment by jrisk** [comment]
But there will be ISO string support for DatePipe at some point in the future yes? from reading #3333 it seems theres  issues with integrating parts of the internationalization standard that includes the ISO date format so it's just being left out temporarily
