### ISSUE TITLE
Setting template - url

### ISSUE THREAD

**Issue by LotusShiv** [angular/angular#7535]
*Setting *Note: for support questions, please use one of these channels:** https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
- Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by zoechi** [comment]
There is not much information in this issue ...

**Comment by pkozlowski-opensource** [comment]
Agree with @zoechi - not actionable as-is - closing.

**Comment by LotusShiv** [comment]
Sorry wasn't able to edit my post yesterday. The issue was with setting the templateUrl and I was able to get over the hurdle by removing all angular2 related installations and redo. But later had issues with the ngFor and ngIf. According to the various information pools that I could pour into, some say to use ngfor and some say to use with F capitalized in ngFor and I capitalized in ngIf for example (camel case vs kebab case)... I know Angular2 is still in the beta stage and things are fluid. Still I had to play around and work with it and also if I use *ngFor (with a star preceding), the template was not processed on the browser I had to use without the *. I have a separate template as a .html file which I set for templateUrl and obviously the for loop and the if conditions are there. Anyway, I would like to know from the development community what other issues are you facing in this regard.

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests. 
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)
