### ISSUE TITLE
[beta.9] Breaking changes Router

### ISSUE THREAD

**Issue by Slaals** [angular/angular#7537]
- Angular version: 2.0.0-beta.9

Since I upgraded my Angular2 from beta.8 I have an issue with the router, it's probably related to the [breaking changes](https://github.com/angular/angular/blob/master/CHANGELOG.md).

Here is the exception I get : 
```
EXCEPTION: Error during instantiation of t!.
```
The error is thrown [here](https://github.com/angular/angular/blob/master/modules/angular2/src/router/router.ts#l84)

UPDATE : 
Over my application I use 2 `router-outlet`, in 2 different components. Typically a primary component routes to a component which will also routes to different components. The error appears to be thrown because of the 2 `router-outlet` and is related to beta.9 changes. Any idea?

Thanks.

**Comment by ericmartinezr** [comment]
@Slaals you should provide a plnkr to reproduce your issue, and use `dev` bundles to see the full message

**Comment by CaptainCodeman** [comment]
@Slaals That's why I thought it was todo with minification. The exact error might change depending on what the minifier spits out but it looks like it has been minified.

As @ericmartinezr suggests a plunker will help narrow things down to identify the core issue.

I haven't come across any new beta-8 -> beta-9 issues so far.

**Comment by Slaals** [comment]
@CaptainCodeman @ericmartinezr You both helped me to find a solution... And it's a very simple one. It's either related to minification or `dev` bundles (or both?).

I solved the issue by changing these : 
```
...
<script src="node_modules/angular2/bundles/router.min.js"></script>
<script src="node_modules/angular2/bundles/angular2.js"></script>
...
```
To these : 
```
...
<script src="node_modules/angular2/bundles/router.dev.js"></script>
<script src="node_modules/angular2/bundles/angular2.dev.js"></script>
...
```
Thanks guys.
