### ISSUE TITLE
Async validation results on a control are not updating the valid value of the control group

### ISSUE THREAD

**Issue by c-crosby** [angular/angular#7538]
Bug

* **What is the current behavior?**

Using a control group and a collection of controls where one has an async validator, when the async validator returns valid it does not update the control group status to be valid.  This is contrary to how validators work which do update the control group valid accordingly.

This case specifically requires the async validator be the last validator to be resolved that should mark the control group valid.  If another control's validity changes then the control group will accurately display the state as long as that validator is not async.

The work around I'm using is to subscribe manually to the controls statusChanged and calling updateValueAndValidity on the control group.

In a case where the submit button is disabled until the control group is valid the button remains disabled when the last validator was async.

* **What is the expected behavior?**
When the async control is no longer pending I expect it to update the control group's valid value.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.7, 8, 9
- Browser: [Chrome XX]
- Language: [TypeScript ES5]

**Comment by kara** [comment]
This issue looks stale (lots of changes in the new forms API), so I'm closing it for now.  If you still experience this issue with the new API, please feel free to open another issue.
