### ISSUE TITLE
feat(AsyncPipe): allow for error and/or complete callbacks as arguments to |async pipe

### ISSUE THREAD

**Issue by gdi2290** [angular/angular#7539]
```html
<h3>Repo list</h3>
<ul>
	<li *ngFor="#repo of repos | async:onError">
    <a [routerLink]=" ['RepoDetail', {org: repo.owner.login, name: repo.name}] ">
      {{ repo.name }}
    </a>
  </li>
</ul>
```

* **I'm submitting a ... **
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
feature

* **What is the current behavior?**
when there's an error the observable error throws

* **What is the expected behavior?**
some users wants a graceful way of handling the error

* **What is the motivation / use case for changing the behavior?**
even though you would manually subscribe to the observable for more control when prototyping or for demos etc it's best to use the abstraction

**Comment by gdi2290** [comment]
I don't mind making a PR if everyone is on board

**Comment by yfain** [comment]
+1.

Unless async pipe has a provision for specifying error handling, it's pretty much useless.

**Comment by Martin-Wegner** [comment]
Any plans to fix PR #7990?

**Comment by gdi2290** [comment]
@Martin-Wegner there was an error in IE9 that reverted this PR

**Comment by Martin-Wegner** [comment]
And no workaround available for IE9?

**Comment by gdi2290** [comment]
I tweeted about this PR for someone in the community to reimplement this PR with IE9 support
https://twitter.com/gdi2290/status/756567812085350401

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource Rob in gitter said that this is not actual anymore so I think u can close it.

**Comment by yfain** [comment]
While you can handle errors by adding the catch operator the the function that returns an Observable, this is not an elegant solution.  IMO, async pipe is cool for presentations at  conferences, but for a real world development subscribe() is a better option.

Besides, from testing prospective the less magic is done inside the template the better.

**Comment by Martin-Wegner** [comment]
@pkozlowski-opensource  and @DzmitryShylovich why do you think this issue is not actual anymore? It is not solved and we need it!
