### ISSUE TITLE
Value setters for directives should be called before the component inputs

### ISSUE THREAD

**Issue by saxenasaurabh** [angular/angular#7542]
- *_I'm submitting a ... *_
  [ ] bug report
  [X] feature request
  [ ] support request => Please do not submit support request here, see note at the top of this template.
- **What is the current behavior?**
  Dart:

```
@Component(
  selector: 'foo',
  inputs: const ['fooInput'],
  directives: const [BarDirective]
)
class Foo {
  set fooInput(_) {
    print('Foo input called');
  }
}

@Directive(
  selector: '[bar]',
  inputs: const ['barInput: bar']
)
class BarDirective {
  set barInput(_) {
    print('Bar input called');
  }
}
```

HTML:

```
<foo fooInput="abc" barInput="def"></foo>
```

Expected:
Bar input called
Foo input called

Actual:
Foo input called
Bar input called

Above is a simplified example. However there are cases where Foo could inject BarDirective or some provider bound by BarDirective which depends on the state of BarDirective. Calling the setters of Foo first leads to unexpected behavior. I am currently using the following workaround

<div barInput="def">
  <foo fooInput="abc"></foo>
</div>

which is not very pretty :-/

**Comment by tbosch** [comment]
So what would be the ordering between directives?

I think in general, the order in which we process the inputs should be
determined by DI.
I.e. if the components injects the directives, than the inputs of the
components should be checked before the directive.
But if the directive injects the component, then the inputs of the
component should be checked before the inputs of the directive.

**Comment by naomiblack** [comment]
this is internal issue b/27598576
