### ISSUE TITLE
(Question)Is there any plan to deploy angular1router as a bower repository?

### ISSUE THREAD

**Issue by alanpurple** [angular/angular#7544]
As a built output

angular_1_router.js and angular_1_router.min.js

or am I the only one who can't find that?

**Comment by pkozlowski-opensource** [comment]
Unlikely for the new router - npm is out preferred package manager.

**Comment by rvl** [comment]
@alanpurple https://github.com/rvl/bower-angular-component-router

**Comment by fdcastel** [comment]
@pkozlowski-opensource: While I fully understand and agree with the move to npm in 2.x, it would be nice -- at least for 1.x releases -- to keep going with bower. Just like every other module of official Angular releases.

Many Angular 1.x projects today rely on bower and bower-main-files. The lack of a bower repository can be a problem to integrate with some complex build pipelines that use them (e.g. the ones created by the excellent generator-gulp-angular -- https://github.com/Swiip/generator-gulp-angular).
