### ISSUE TITLE
"SyntaxError: Unexpected token {" when using ES6 target

### ISSUE THREAD

**Issue by andrashatvani** [angular/angular#7547]
* **I'm submitting a ... **
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
I'm reporting a bug.

* **What is the current behavior?**
When I start my app which is flawlessly working with ES5 target, then I see the following exception in the console:

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

"compilerOptions": {
    "target": "ES6",
    "module": "system",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  }

* **What is the expected behavior?**
The application launches as with ES5.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.9
- Browser: [Chrome 49.0.2623.87 | Firefox 45.0]
- Language: [TypeScript 1.8.7 | ES6]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
**I see the following stacktrace in Chrome:**
`
angular2.dev.js:23597 EXCEPTION: SyntaxError: Unexpected token {BrowserDomAdapter.logError @ angular2.dev.js:23597BrowserDomAdapter.logGroup @ angular2.dev.js:23608ExceptionHandler.call @ angular2.dev.js:1260(anonymous function) @ angular2.dev.js:12576NgZone._notifyOnError @ angular2.dev.js:13620collection_1.StringMapWrapper.merge.onError @ angular2.dev.js:13524Zone.run @ angular2-polyfills.js:1247(anonymous function) @ angular2.dev.js:13543zoneBoundFn @ angular2-polyfills.js:1220lib$es6$promise$$internal$$tryCatch @ angular2-polyfills.js:468lib$es6$promise$$internal$$invokeCallback @ angular2-polyfills.js:480(anonymous function) @ angular2-polyfills.js:1028(anonymous function) @ angular2-polyfills.js:123microtask @ angular2.dev.js:13575Zone.run @ angular2-polyfills.js:1243(anonymous function) @ angular2.dev.js:13543zoneBoundFn @ angular2-polyfills.js:1220lib$es6$promise$asap$$flush @ angular2-polyfills.js:262
angular2.dev.js:23597 STACKTRACE:BrowserDomAdapter.logError @ angular2.dev.js:23597ExceptionHandler.call @ angular2.dev.js:1262(anonymous function) @ angular2.dev.js:12576NgZone._notifyOnError @ angular2.dev.js:13620collection_1.StringMapWrapper.merge.onError @ angular2.dev.js:13524Zone.run @ angular2-polyfills.js:1247(anonymous function) @ angular2.dev.js:13543zoneBoundFn @ angular2-polyfills.js:1220lib$es6$promise$$internal$$tryCatch @ angular2-polyfills.js:468lib$es6$promise$$internal$$invokeCallback @ angular2-polyfills.js:480(anonymous function) @ angular2-polyfills.js:1028(anonymous function) @ angular2-polyfills.js:123microtask @ angular2.dev.js:13575Zone.run @ angular2-polyfills.js:1243(anonymous function) @ angular2.dev.js:13543zoneBoundFn @ angular2-polyfills.js:1220lib$es6$promise$asap$$flush @ angular2-polyfills.js:262
angular2.dev.js:23597 SyntaxError: Unexpected token {
    at Object.evalExpression (http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:451:12)
    at TemplateCompiler._createViewFactoryRuntime (http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:24894:23)
    at http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:24848:41
    at Zone.run (http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1243:24)
    at Zone.run (http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:13543:32)
    at zoneBoundFn (http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1220:26)
    at lib$es6$promise$$internal$$tryCatch (http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:468:17)
    at lib$es6$promise$$internal$$invokeCallback (http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:480:18)
    at http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1028:14
    at http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:123:10

-----async gap-----
Error
    at _getStacktraceWithUncaughtError (http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:2244:29)
    at Zone.fork (http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:2293:47)
    at Zone.bind (http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1218:53)
    at bindArguments (http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1401:36)
    at lib$es6$promise$promise$$Promise.obj.(anonymous function) [as then] (http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1413:46)
    at http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:24846:60
    at Zone.run (http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1243:24)
    at Zone.run (http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:13543:32)
    at zoneBoundFn (http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1220:26)
    at lib$es6$promise$$internal$$tryCatch (http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:468:17)

-----async gap-----
Error
    at _getStacktraceWithUncaughtError (http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:2244:29)
    at Zone.fork (http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:2293:47)
    at Zone.bind (http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1218:53)
    at bindArguments (http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1401:36)
    at lib$es6$promise$promise$$Promise.obj.(anonymous function) [as then] (http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1413:46)
    at TemplateCompiler._compileComponentRuntime (http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:24837:14)
    at TemplateCompiler._compileNestedComponentRuntime (http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:24863:12)
    at http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:24844:26
    at Array.forEach (native)
    at http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:24843:37

-----async gap-----
Error
    at _getStacktraceWithUncaughtError (http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:2244:29)
    at Zone.fork (http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:2293:47)
    at Zone.bind (http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1218:53)
    at bindArguments (http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1401:36)
    at lib$es6$promise$promise$$Promise.obj.(anonymous function) [as then] (http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1413:46)
    at TemplateCompiler._compileComponentRuntime (http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:24837:14)
    at TemplateCompiler.compileHostComponentRuntime (http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:24789:14)
    at RuntimeCompiler_.compileInHost (http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:25140:37)
    at DynamicComponentLoader_.loadAsRoot (http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:12338:29)
    at di_1.provide.useFactory (http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:12438:39)

-----async gap-----
Error
    at _getStacktraceWithUncaughtError (http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:2244:29)
    at Zone.fork (http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:2293:47)
    at NgZone._createInnerZone (http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:13531:39)
    at new NgZone (http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:13397:32)
    at createNgZone (http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:12460:12)
    at PlatformRef_.application (http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:12535:31)
    at Object.bootstrap (http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:25335:64)
    at execute (http://localhost:8000/app/boot/boot.js:41:23)
    at ensureEvaluated (http://localhost:8000/node_modules/systemjs/dist/system.src.js:3218:26)
    at Object.execute (http://localhost:8000/node_modules/systemjs/dist/system.src.js:3336:13)BrowserDomAdapter.logError @ angular2.dev.js:23597ExceptionHandler.call @ angular2.dev.js:1263(anonymous function) @ angular2.dev.js:12576NgZone._notifyOnError @ angular2.dev.js:13620collection_1.StringMapWrapper.merge.onError @ angular2.dev.js:13524Zone.run @ angular2-polyfills.js:1247(anonymous function) @ angular2.dev.js:13543zoneBoundFn @ angular2-polyfills.js:1220lib$es6$promise$$internal$$tryCatch @ angular2-polyfills.js:468lib$es6$promise$$internal$$invokeCallback @ angular2-polyfills.js:480(anonymous function) @ angular2-polyfills.js:1028(anonymous function) @ angular2-polyfills.js:123microtask @ angular2.dev.js:13575Zone.run @ angular2-polyfills.js:1243(anonymous function) @ angular2.dev.js:13543zoneBoundFn @ angular2-polyfills.js:1220lib$es6$promise$asap$$flush @ angular2-polyfills.js:262
angular2-polyfills.js:1152 DEPRECATION WARNING: 'dequeueTask' is no longer supported and will be removed in next major release. Use removeTask/removeRepeatingTask/removeMicroTask`

**This is the stacktrace in Firefox:**
`EXCEPTION: SyntaxError: missing ; before statement
BrowserDomAdapter</BrowserDomAdapter.prototype.logError() angular2.dev.js:23597
BrowserDomAdapter</BrowserDomAdapter.prototype.logGroup() angular2.dev.js:23608
ExceptionHandler</ExceptionHandler.prototype.call() angular2.dev.js:1260
PlatformRef_</PlatformRef_.prototype._initApp/</<() angular2.dev.js:12576
NgZone</NgZone.prototype._notifyOnError() angular2.dev.js:13620
NgZone</NgZone.prototype._createInnerZone/errorHandling<.onError() angular2.dev.js:13524
Zone</Zone.prototype.run() angular2-polyfills.js:1247
NgZone</NgZone.prototype._createInnerZone/<.$run/<() angular2.dev.js:13543
zoneBoundFn() angular2-polyfills.js:1220
lib$es6$promise$$internal$$tryCatch() angular2-polyfills.js:468
lib$es6$promise$$internal$$invokeCallback() angular2-polyfills.js:480
lib$es6$promise$promise$$Promise.prototype.then/<() angular2-polyfills.js:1028
<anonymous> angular2-polyfills.js:123
NgZone</NgZone.prototype._createInnerZone/<.$scheduleMicrotask/</microtask() angular2.dev.js:13575
Zone</Zone.prototype.run() angular2-polyfills.js:1243
NgZone</NgZone.prototype._createInnerZone/<.$run/<() angular2.dev.js:13543
zoneBoundFn() angular2-polyfills.js:1220
lib$es6$promise$asap$$flush()

evalExpression@http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:451:12
TemplateCompiler</TemplateCompiler.prototype._createViewFactoryRuntime@http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:24894:16
TemplateCompiler</TemplateCompiler.prototype._compileComponentRuntime/done</<@http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:24848:35
Zone</Zone.prototype.run@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1243:21
NgZone</NgZone.prototype._createInnerZone/<.$run/<@http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:13543:22
zoneBoundFn@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1220:21
lib$es6$promise$$internal$$tryCatch@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:468:17
lib$es6$promise$$internal$$invokeCallback@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:480:18
lib$es6$promise$promise$$Promise.prototype.then/<@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1028:14
@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:123:10
NgZone</NgZone.prototype._createInnerZone/<.$scheduleMicrotask/</microtask@http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:13575:17
Zone</Zone.prototype.run@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1243:21
NgZone</NgZone.prototype._createInnerZone/<.$run/<@http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:13543:22
zoneBoundFn@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1220:21
lib$es6$promise$asap$$flush@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:262:10

-----async gap-----
_getStacktraceWithUncaughtError@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:2244:29
exports.longStackTraceZone.$fork/<@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:2293:47
Zone</Zone.prototype.bind@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1218:48
bindArguments@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1401:1
patchPrototype/</obj[name]@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1413:46
TemplateCompiler</TemplateCompiler.prototype._compileComponentRuntime/done<@http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:24846:18
Zone</Zone.prototype.run@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1243:21
NgZone</NgZone.prototype._createInnerZone/<.$run/<@http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:13543:22
zoneBoundFn@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1220:21
lib$es6$promise$$internal$$tryCatch@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:468:17
lib$es6$promise$$internal$$invokeCallback@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:480:18
lib$es6$promise$$internal$$publish@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:451:12
@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:123:10
NgZone</NgZone.prototype._createInnerZone/<.$scheduleMicrotask/</microtask@http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:13575:17
Zone</Zone.prototype.run@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1243:21
NgZone</NgZone.prototype._createInnerZone/<.$run/<@http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:13543:22
zoneBoundFn@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1220:21
lib$es6$promise$asap$$flush@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:262:10

-----async gap-----
_getStacktraceWithUncaughtError@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:2244:29
exports.longStackTraceZone.$fork/<@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:2293:47
Zone</Zone.prototype.bind@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1218:48
bindArguments@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1401:1
patchPrototype/</obj[name]@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1413:46
TemplateCompiler</TemplateCompiler.prototype._compileComponentRuntime@http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:24835:16
TemplateCompiler</TemplateCompiler.prototype._compileNestedComponentRuntime@http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:24863:7
TemplateCompiler</TemplateCompiler.prototype._compileComponentRuntime/done</<@http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:24844:20
TemplateCompiler</TemplateCompiler.prototype._compileComponentRuntime/done<@http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:24843:11
Zone</Zone.prototype.run@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1243:21
NgZone</NgZone.prototype._createInnerZone/<.$run/<@http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:13543:22
zoneBoundFn@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1220:21
lib$es6$promise$$internal$$tryCatch@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:468:17
lib$es6$promise$$internal$$invokeCallback@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:480:18
lib$es6$promise$$internal$$publish@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:451:12
@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:123:10
NgZone</NgZone.prototype._createInnerZone/<.$scheduleMicrotask/</microtask@http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:13575:17
Zone</Zone.prototype.run@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1243:21
NgZone</NgZone.prototype._createInnerZone/<.$run/<@http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:13543:22
zoneBoundFn@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1220:21
lib$es6$promise$asap$$flush@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:262:10

-----async gap-----
_getStacktraceWithUncaughtError@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:2244:29
exports.longStackTraceZone.$fork/<@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:2293:47
Zone</Zone.prototype.bind@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1218:48
bindArguments@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1401:1
patchPrototype/</obj[name]@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1413:46
TemplateCompiler</TemplateCompiler.prototype._compileComponentRuntime@http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:24835:16
TemplateCompiler</TemplateCompiler.prototype.compileHostComponentRuntime@http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:24789:1
RuntimeCompiler_</RuntimeCompiler_.prototype.compileInHost@http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:25140:14
DynamicComponentLoader_</DynamicComponentLoader_.prototype.loadAsRoot@http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:12338:14
_componentProviders/<.useFactory@http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:12438:16
Injector</Injector.prototype._instantiate@http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:11440:19
Injector</Injector.prototype._instantiateProvider@http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:11373:16
Injector</Injector.prototype._new@http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:11363:14
InjectorInlineStrategy</InjectorInlineStrategy.prototype.getObjByKeyId@http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:11140:23
Injector</Injector.prototype._getByKeyDefault@http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:11564:19
Injector</Injector.prototype._getByKey@http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:11518:16
Injector</Injector.prototype.get@http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:11318:14
ApplicationRef_</ApplicationRef_.prototype.bootstrap/<@http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:12706:30
Zone</Zone.prototype.run@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1243:21
NgZone</NgZone.prototype._createInnerZone/<.$run/<@http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:13543:22
NgZone</NgZone.prototype.run@http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:13505:18
ApplicationRef_</ApplicationRef_.prototype.bootstrap@http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:12697:7
bootstrap@http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:25335:12
.execute@http://localhost:8000/app/boot/boot.js:41:1
ensureEvaluated@http://localhost:8000/node_modules/systemjs/dist/system.src.js:3218:5
bootstrap/</</</</</<.execute@http://localhost:8000/node_modules/systemjs/dist/system.src.js:3336:13
doDynamicExecute@http://localhost:8000/node_modules/systemjs/dist/system.src.js:727:20
link@http://localhost:8000/node_modules/systemjs/dist/system.src.js:929:20
doLink@http://localhost:8000/node_modules/systemjs/dist/system.src.js:581:7
updateLinkSetOnLoad@http://localhost:8000/node_modules/systemjs/dist/system.src.js:629:18
proceedToTranslate/</<@http://localhost:8000/node_modules/systemjs/dist/system.src.js:441:11
Zone</Zone.prototype.run@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1243:21
zoneBoundFn@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1220:21
lib$es6$promise$$internal$$tryCatch@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:468:17
lib$es6$promise$$internal$$invokeCallback@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:480:18
lib$es6$promise$$internal$$publish@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:451:12
@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:123:10
Zone</Zone.prototype.run@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1243:21
zoneBoundFn@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1220:21
lib$es6$promise$asap$$flush@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:262:10

-----async gap-----
_getStacktraceWithUncaughtError@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:2244:29
exports.longStackTraceZone.$fork/<@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:2293:47
NgZone</NgZone.prototype._createInnerZone@http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:13531:1
NgZone@http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:13397:27
createNgZone@http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:12460:12
PlatformRef_</PlatformRef_.prototype.application@http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:12535:31
bootstrap@http://localhost:8000/node_modules/angular2/bundles/angular2.dev.js:25335:12
.execute@http://localhost:8000/app/boot/boot.js:41:1
ensureEvaluated@http://localhost:8000/node_modules/systemjs/dist/system.src.js:3218:5
bootstrap/</</</</</<.execute@http://localhost:8000/node_modules/systemjs/dist/system.src.js:3336:13
doDynamicExecute@http://localhost:8000/node_modules/systemjs/dist/system.src.js:727:20
link@http://localhost:8000/node_modules/systemjs/dist/system.src.js:929:20
doLink@http://localhost:8000/node_modules/systemjs/dist/system.src.js:581:7
updateLinkSetOnLoad@http://localhost:8000/node_modules/systemjs/dist/system.src.js:629:18
proceedToTranslate/</<@http://localhost:8000/node_modules/systemjs/dist/system.src.js:441:11
Zone</Zone.prototype.run@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1243:21
zoneBoundFn@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1220:21
lib$es6$promise$$internal$$tryCatch@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:468:17
lib$es6$promise$$internal$$invokeCallback@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:480:18
lib$es6$promise$$internal$$publish@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:451:12
@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:123:10
Zone</Zone.prototype.run@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1243:21
zoneBoundFn@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:1220:21
lib$es6$promise$asap$$flush@http://localhost:8000/node_modules/angular2/bundles/angular2-polyfills.js:262:10`

**Comment by pkozlowski-opensource** [comment]
If you specify ES6 as a target you need to have a browser that fully supports ES6, including module loading. To my knowledge non of the existing browsers fully supports ES6 so you can't use ES6 as a target really.

Closing as not something that is related or can be fixed by the Angular itself.
