### ISSUE TITLE
Using External Libraries with Angular 2

### ISSUE THREAD

**Issue by DanielYKPan** [angular/angular#7548]
Hi, I am pretty new to ng2
Right now i try to install underscore and use it.
I tried 
typings install underscore --ambient --save
and include the path in system.js config

But in my service ts file, I still could not import the underscore module
import * as _ from 'underscore'

Please give me a hint, thanks in advances.

**Comment by zoechi** [comment]
Sorry, I can't help you with your question.

Anyway, GitHub issues are for bug reports and feature requests. 
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by robwormald** [comment]
hi @DanielYKPan - please take issues like this to one of the support channels, like https://gitter.im/angular/angular - you'll find lots of helpful people there.
