### ISSUE TITLE
[testing] valueChanges-Event of Control is not executed when dispatching Event for Input-Field

### ISSUE THREAD

**Issue by choeller** [angular/angular#7549]
- **What is the current behavior?**

I want to Unit Test my Typeahead component that is configured as followed:

``` html
    <input type="text" #query class="form-control"
           id="searchField"
           [ngFormControl]="searchTerm">
```

``` ts
  searchTerm = new Control();
  ngOnInit() {
    Observable.merge(
      Observable.of(""),
      this.searchTerm.valueChanges.debounceTime(500))
      .switchMap((term :string) => this.taskService.findTasks({'q': term}))
      .subscribe();
  }
```

Trying to unit test the form like this:

``` ts
  iit('should execute a Typeahead-Search', <any> fakeAsync(() => {
    fixture.detectChanges();
    let taskList = fixture.componentInstance,
      element = fixture.nativeElement;
    var spy : Spy = spyOn(taskService, 'findTasks').and.callThrough();
    let input = element.querySelector('#searchField');
    input.value = 'Term';
    dispatchEvent(input, 'input');
    //dispatchEvent(input, 'change'); doesn't matter what I dispatch here
    //dispatchEvent(input, 'blur');
    fixture.detectChanges();
    tick(600);
    console.log(input.value); // prints "Term" so value was updated
    expect(taskService.findTasks).toHaveBeenCalledWith({'q': 'Term'});
  }));

```

never emits a valueChanges Event for the form. When doing it like this:

```
  iit('should execute a Typeahead-Search', <any> fakeAsync(() => {
    fixture.detectChanges();

    let taskList = fixture.componentInstance,
      element = fixture.nativeElement;
    var spy : Spy = spyOn(taskService, 'findTasks').and.callThrough();
    let input = element.querySelector('#searchField');
    taskList.searchTerm.updateValue("Term", {});
    fixture.detectChanges();
    tick(600);
    expect(taskService.findTasks).toHaveBeenCalledWith({'q': 'Term'});
  }));
```

the test works.
- **What is the expected behavior?**

dispatchEvent should lead to a valueChanges-call in the component
- **What is the motivation / use case for changing the behavior?**
- **Please tell us about your environment:**
- Angular version: 2.0.0-beta.8
- Browser: [Chrome / Karma]
- Language: TypeScript 1.8.7]
- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by sstorie** [comment]
I've got a similar issue, but I can't get your working example to work in my case. If I include the debounceTime() call I always get an exception from zone.js like so:

> Error: 1 periodic timer(s) still in the queue.

Is there a decent guide on how to do these kinds of tests?

**Comment by DzmitryShylovich** [comment]
@choeller is this still an issue?

**Comment by DzmitryShylovich** [comment]
@kara deprecated forms. I think can be closed

**Comment by jordivila** [comment]
@DzmitryShylovich I'm still experiencing the same behaviour using angular 4.1.2

**Comment by Orodan** [comment]
Getting a similar problem.
I have a component with an input looking like this : 
```
<input type="text" class="form-control name-input" placeholder="Search" 
       name="name" ngModel #name="ngModel">
```

In my class I've got the following :

```
export class Example {
   @ViewChild('name') name;

   ngOnInit () {
      const that = this;
      
      this.name.valueChanges
            .debounceTime(300)
            .distinctUntilChanged()
            .subscribe(this.onInputChange.bind(that));
   }

   private onInputChange (search: string) { ... }
}
```

This code works as expected in my application, however when I try to test this it's not working. 
Here is my test : 

```
it('test', async(() => {
   /** Do some async stuff **/
   this.fixture.whenStable().then(() => {
      this.fixture.detectChanges();
      const nameInput = this.fixture.debugElement.query(By.css('input[name="name"]'));
      nameInput.nativeElement.value = 'test';
      nameInput.nativeElement.dispatchEvent(new Event('input'));
   });
}));
```
At this moment, I expect the onInputChange method to be called with the new input value, but it never happens.

If anyone can help, I would appreciate.

**Comment by aleixsuau** [comment]
Same problem here, did you find any solution @Orodan ?

**Comment by davinkevin** [comment]
We still have the same issue in Angular5.

Some of you find the solution about this issue ? 

//cc @neonox31 @gasperiguillaume @Yann29

**Comment by Orodan** [comment]
@aleixsuau not yet, I had to comment my test and I didn't really have the time to look at it for now.

**Comment by gabrielalan** [comment]
And here we are with another problem without solution... 
In my case, even if I use `patchValue` on the group, it doesn't trigger the `valueChanges`.
I really miss  React...

**Comment by jorgeso** [comment]
Is there a solution to this problem? I'm having that same issue. I'm using angular 6.

**Comment by jorgeso** [comment]
@Orodan @davinkevin @gabrielalan @choeller 

My issue was fixed when focusing on the input before dispatchEvent. so in @Orodan's example:

nameInput.focus();
nameInput.nativeElement.value = 'test';
nameInput.nativeElement.dispatchEvent(new Event('input'));

**Comment by nicodh** [comment]
Same problem with a reactive form control in Angular 7.1.4
The workaround suggested by @jorgeso didn't help.  No value change event is emitted.
If I call inputElement.dispatchEvent(new Event('input')) in the browser the change event is emitted...

**Comment by nicodh** [comment]
I should mention, that I debugged the registered onChange handler of the ValueAccessor and it is called and the input is marked as dirty.

**Comment by nicodh** [comment]
Ok I found that in my case I had to add a tick() since I had a debounceTime in my value changed pipe.
After that change it worked as expected (and without trigger a focus event)

**Comment by dalepo** [comment]
can confirm under fakeAsync wrap form.valueChanges does not trigger.

**Comment by gelhaimer** [comment]
> can confirm in Angular 10.0.8 under fakeAsync wrap form.valueChanges does not trigger. How do people test their forms if controls are co-dependant?

I got the same issue and it's annoying af. I feel obliged to move my form construction from service to component just to be able to test the form's behavior...

**Comment by gelhaimer** [comment]
> can confirm in Angular 10.0.8 under fakeAsync wrap form.valueChanges does not trigger. How do people test their forms if controls are co-dependant?

Using 
```
formControl.setValue(myValue)
formControl.updateValueAndValidity()
```
 does the job

**Comment by RobARichardson** [comment]
> > can confirm in Angular 10.0.8 under fakeAsync wrap form.valueChanges does not trigger. How do people test their forms if controls are co-dependant?
> 
> Using
> 
> ```
> formControl.setValue(myValue)
> formControl.updateValueAndValidity()
> ```
> 
> does the job

Having the same issue as well.  I'm using Angular 9.1 and unfortunately this didn't work for me.

**Comment by Jeremias-Nater** [comment]
Same issue in Angular 9.1.6.

In my case i call the onChange() function in the custom form control. The (change) and (input) events on my <app-custom-input> are never called but if i use (ngModelChange) it works.

I dont really like this solution since i am now mixing ngModel attributes with the reactiveForm-version "formControlName".

Outside of the test everything is working as expected and it does not matter if i use (input), (change) or (ngModelChange) event on my <app-custom-input>.

**Comment by identiq** [comment]
`<input
        (keyup)="onKey($event)"
        type="text"
        formControlName="input"
        name="example"
      />`

` onKey(event: KeyboardEvent): void {
    const value = (event.target as HTMLInputElement).value;
    this.exampleForm.get('input').setValue(value);
    this.exampleForm.get('input').updateValueAndValidity();
  }
`

**Comment by MikaStark** [comment]
Correctly mocking input event works for me even in a fakeAsync

```ts
const searchInput = fixture.debugElement.query(
      By.css('.search-field input')
    );
    searchInput.nativeElement.value = 'test';
    searchInput.triggerEventHandler('input', {
      value: 'test',
      target: searchInput.nativeElement,
    });
```

**Comment by gregkopp** [comment]
> Correctly setting target event property works for me even in a fakeAsync
> 
> ```ts
> const searchInput = fixture.debugElement.query(
>   By.css('.search-field input')
> );
> searchInput.nativeElement.value = 'test';
> searchInput.triggerEventHandler('input', {
>   target: searchInput.nativeElement,
> });
> ```

The problem with this approach is it requires TestBed. The OP was not using TestBed. Neither would I, if i didn't need to for situations like this. I avoid TestBed at every cost.

**Comment by JeanMeche** [comment]
I have a working example on [this stackblitz](https://stackblitz.com/edit/angular-vitest-starter-v18-var2cx?file=README.md). 

```
@Component({
  standalone: true,
  imports: [ReactiveFormsModule],
  selector: 'app-root',
  template: `<div [formGroup]="formGroup">
    <input formControlName="name" id="name" />
    <span id="reverseName" style="padding-left: 10px;">{{ reverseName }}</span>
  </div>`,
})
export class AppComponent implements OnInit {
  value: string = '';

  formGroup = new FormBuilder().group({
    name: [''],
  });

  ngOnInit() {
    this.formGroup.valueChanges
      .pipe(debounceTime(500))
      .subscribe((data) => (this.value = data.name!));
  }
}

describe('AppComponent', () => {
  let fixture: ComponentFixture<AppComponent>;
  let app: AppComponent;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [AppComponent],
    });
    fixture = TestBed.createComponent(AppComponent);
    fixture.autoDetectChanges(true);
    app = fixture.componentInstance;
  });

  it('should init', () => {
    expect(app).toBeTruthy();
  });

  it("should call formGroup.valueChanges when 'input' event is dispatched", async () => {
    const nameEl =
      (fixture.debugElement.query(By.css('#name'))
        ?.nativeElement as HTMLTextAreaElement) || undefined;
    expect(nameEl).toBeTruthy();
    nameEl.value = 'ab';
    nameEl.dispatchEvent(new Event('input'));

    await fixture.whenStable();
    expect(app.value).toEqual('ab');
  });
});
```

The value is correctly emitted, the debounce is awaited. 

I'm going to close the issue.
