### ISSUE TITLE
Consider renaming eval methods as those are disallowed in strict mode

### ISSUE THREAD

**Issue by cburgdorf** [angular/angular#755]
While trying to get angular2 running with babel I [stumbled over an issue](https://github.com/babel/babel/issues/867#issuecomment-75466303) with [some methods](https://github.com/angular/angular/blob/master/modules/angular2/src/change_detection/parser/ast.js#L6) being named `eval` which is disallowed in strict mode.

What's your opinion on that one? Any plans to change the name to something that won't conflict with strict mode?

**Comment by caitp** [comment]
this is actually a bug in v8, which arv has already fixed afaik

**Comment by cburgdorf** [comment]
You mean that 'use strict' does not allow methods to be named eval is the bug? /cc @sebmck

**Comment by caitp** [comment]
no, I mean it does allow that. Hang on, I'm trying to dig up the bug

**Comment by caitp** [comment]
https://code.google.com/p/v8/issues/detail?id=1984 particularly this one

**Comment by cburgdorf** [comment]
Ah, interesting! Thanks for clarifying. Closing here.
