### ISSUE TITLE
[testing] form tests need excessive amounts of "detectChanges" and "ticks"

### ISSUE THREAD

**Issue by choeller** [angular/angular#7551]
**Note: for support questions, please use one of these channels:** https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
[ ] bug report
[x ] feature request / enhancement
[ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

Enhancement

* **What is the current behavior?**

When trying to test ngModel-Forms it is neccessary to add a lot of calls to "detectChanges" and "tick" to run the test successfull. This is a typical example:

```javascript
  it('should have an enabled submit button for valid forms', <any> fakeAsync(() => {
    fixture.detectChanges(); //trigger change detection
    tick();
    let element = fixture.nativeElement;
    let titleInput = element.querySelector('#title');
    titleInput.value = "Test";
    dispatchEvent(titleInput, "input");
     fixture.detectChanges(); //trigger change detection
    tick();
    expect(element.querySelector('#submit').disabled).toBeFalsy();
  }));
```
leaving out any of the detectChanges and ticks lets the test crash

* **What is the expected behavior?**

Have a more "natural" way to interact with forms in tests

* **What is the motivation / use case for changing the behavior?**

Writing tests currently is more or less trial-and-error, so currently I add `detectChanges` and `tick` at various points until the test passes ;)

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [Chrome / Karma ]
- Language: [TypeScript 1.8.7]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by juliemr** [comment]
We'll recommend  using `async` and `inject` separately once that hits (in the next couple weeks). See also https://github.com/angular/angular/issues/7473 for reducing the need to run `detectChanges`.
