### ISSUE TITLE
router-outlet not registering NgModel onChange

### ISSUE THREAD

**Issue by rweng** [angular/angular#7553]
Hi, 

[I am struggeling w/ the router-outlet](http://stackoverflow.com/questions/35924504/angular2-adding-router-outlet-causes-ngmodel-not-to-fire) and I am unsure if this is a bug or intended behavior. When the router inserts my component next to `router-outlet`, [AbstractChangeDetector#runDetectedChanges](https://github.com/angular/angular/blob/master/modules/angular2/src/core/change_detection/abstract_change_detector.ts#L100) is not fired. Thus, `NgModel` doesn't register `onChange` on the `ValueAccessor` and input isn't propagated to the model. The change detector should fire, though, shouldn't it? I am using beta.9. Sorry for spaming your issue tracker if this is just my mistake ;)

**Comment by zoechi** [comment]
See also http://stackoverflow.com/questions/35924504/angular2-adding-router-outlet-causes-ngmodel-not-to-fire

**Comment by rweng** [comment]
See [stackoverflow](http://stackoverflow.com/questions/35924504/angular2-adding-router-outlet-causes-ngmodel-not-to-fire/36011636#36011636): It was not a bug in ui-router but a zonejs problem. Sorry for that.
