### ISSUE TITLE
bug(Router): RouteParams not consistent when using regex route

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#7554]
**Note: for support questions, please use one of these channels:** https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

Bug

* **What is the current behavior?**

When using regex and a serializer for route parameters, the route parameters are correct when navigating using a router link, but are not recognized when the page is refreshed, or on initial load.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

http://plnkr.co/edit/s2ocxR?p=preview

* **What is the expected behavior?**

The RouteParams are serialized into the correct variables on initial load or page refresh.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
- Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]

Angular 2.0.0-beta.9
Browser: Chrome 48.0.2564.116 (64-bit)
Language: TypeScript

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

To reproduce

1. Click the blue button to open the plunker in a separate window
2. Click on the *Regex Test* link
3. Note the values for a and b are populated, and the values for 0, 1, 2 are empty
4. Refresh the window using CMD-R(Mac) or CTRL-R(Windows)
5. Note the values for a and b are empty, and the values for 0, 1, and 2 are populated

**Comment by bastih** [comment]
This is due to the Regex having no mapping to function parameters. JS doesn't support named groups as far as I can tell, so we probably need a mapping structure between group index and parameter name, which might even obviate the need for the serializer function.

This could look like this:
`  {
    name : 'Test',
    regex: '^test/(.+)/(.+)$',
    regex_group_names: ['a', 'b'],
    serializer: (params) => {
      return new GeneratedUrl(`test/${params.a}/${params.b}`, {});
    },`

For more complex regex, and when no group names are given, we could still populate the match indexes, if there is an advantageous case for that somehow - maybe in the case of dynamic number of groups?
