### ISSUE TITLE
Expose routerLink property: activeClass instead of automatically assigning class 'router-link-active' to the active router link.

### ISSUE THREAD

**Issue by robertbrower** [angular/angular#7555]
**Note: for support questions, please use one of these channels:** https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

*feature

* **What is the current behavior?**

routerLink gets class 'router-link-active' when it is the active router link.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**The router-link-active class is useless. I am using Material and would like to use md-accent for example.
**
* **What is the expected behavior?**

The developer should be able to set the class to be used for the active router link.

* **What is the motivation / use case for changing the behavior?**

Not having to write code to work around such a simple thing.

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
- Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Wapweb** [comment]
Hello. There are have already router-active directives 
-  [for angular 2](https://github.com/AngularClass/angular2-webpack-starter/blob/master/src/app/directives/router-active.ts)
-  [for angular 1.5 component router](https://github.com/Wapweb/angular-component-router-active)

**Comment by CaptainCodeman** [comment]
It's such a basic requirement it should be a built in directive provided by the router IMO.

**Comment by robertbrower** [comment]
Router active is a workaround. I agree with simon. It is currently
incorrectly implemented.

**Comment by wardbell** [comment]
I don't think we should remove or replace router-link-active (if that's what you were recommending). But I do think that the dev should be able to specify a _supplemental_ active class

**Comment by CaptainCodeman** [comment]
Unless the existence of "router-link-active" has some significance in the inner workings of Angular, I don't know why I'd want the framework applying a superfluous class to any of my HTML - the only class I'd care about is the one I could set (if I could).

My vote would be to have a single class but allow us to define what that class should be called.

**Comment by robertbrower** [comment]
Simon is right. What do CSS classes have to do with the inner workings of
Angular? Or are we talking about jQuery? No angular component should be
placing css classes on elements. If you are using the class
router-link-active for any reason other than CSS styles, in the logic of
angular for example, then you're making a mistake IMHO. Thanks.

**Comment by choeller** [comment]
I guess there is already an open pull request for this: https://github.com/angular/angular/pull/6407

**Comment by zoechi** [comment]
You can create a simple directive that adds supplement classes if needed. I think in most cases the default class `router-link-active` is just fine. 

The next discussion is about configuring `ng-pristing`, `ng-touched`, ....  classes on form elements.

**Comment by brandonroberts** [comment]
I also think having the default `router-link-active` class is good because you don't have to attach another directive to each link by default to make it active or inactive in the case that you don't need a special class based on your styling framework. I do think there should be a way to add additional classes, but it seems like it would add too much to the routerLink directive's responsibility.

**Comment by choeller** [comment]
So @gdi2290 s Pull-Request (#6407) does exactly this - current state is "discuss" and there are insecurities if a directive like this is needed - so maybe you guys could give a :heart: for it ;)

**Comment by vsavkin** [comment]
We are no longer maintaining the deprecated router to focus our efforts on making the new router robust.

It's possible to configure the new router to set a custom 'active' class.

Closing this issue.

**Comment by simeyla** [comment]
For future googling: The new router uses this syntax:

    <a routerLink="/crisis-center" routerLinkActive="active-class-name">Crisis Center</a>
