### ISSUE TITLE
Improve the ISSUE_TEMPLATE.md

### ISSUE THREAD

**Issue by todoubaba** [angular/angular#7556]
### I'm submitting a ...
[  ] bug report
[x] feature request

### Current Behavior
The current issue template contains repeat info and inconsistant format.

1.  `I'm submitting a ... ` and `Do you want to request a feature or report a bug?` provide same info.
2.  `I'm submitting a ..`, `Angular version`, `Browser` and so on are not formatted to `<strong>`.
3.   The contents of `<li>` are rendered outside, the appearences are inconsistant, such as the contents of `I'm submitting a ... ` vs others.
4. Issue reports could be viewed by anybody, not only by the core team members. The title of each section should be short and declarative.
5. There are too many comments left over in the issues, such as 

> Note: for support questions, please use one of these channels: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

>  (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

### Expected Behavior
Format the template and improve the readability.

**Comment by jvcjunior** [comment]
Hi, I am new in the open source world and would like to help with this. I think it is easy and it would be my first experience contributing to an open source project. Can I do this?

**Comment by alexeagle** [comment]
@jvcjunior sure, send us a PR against that template file. It was just recently introduced, you can see the conversation in https://github.com/angular/angular/pull/7389
