### ISSUE TITLE
Backspace and delete keys on input text doesn't update model on IE9.

### ISSUE THREAD

**Issue by miguelangelorocha** [angular/angular#7557]

**Comment by MarkPieszak** [comment]
If internally it's using a `.change() event then yes, it ignores those. (More of an IE9 bug / bizarre difference) but maybe it should be changed to a keyup/down for this jnstance?

**Comment by miguelangelorocha** [comment]
All keys change the model except delete and backspace. When events keyup/down are debugged, after delete or backspace, the model don't change too.

**Comment by renehamburger** [comment]
We've got a similar issue with input validation not being triggered on IE9 for backspace, delete or cut. The reason is that IE9 only triggers a `keyup` but no `input` event for these operations (see https://developer.mozilla.org/en-US/docs/Web/Events/input#Browser_compatibility), while Angular only binds `input` and `blur` events to the handler.

**Comment by zoechi** [comment]
You should be able to workaround by providing a custom `ControlValueAccessor`

**Comment by Delagen** [comment]
Please fix this. This is a breaking issue for using any form in IE 9.

**Comment by kara** [comment]
Can someone post a repro case for this?  

@Delagen If this issue is important to you, feel free to submit a PR.

**Comment by Delagen** [comment]
@kara Plunker: http://plnkr.co/edit/Q1MNpMgjuYwBcnYx4AA0?p=preview
Open run frame in IE 9.
Try to change input. Changing value using backspace and delete keys does not update model.

**Comment by pkozlowski-opensource** [comment]
The root cause here is that IE9 doesn't fire `input` events on backspace / delete. In Angular 1.x we were working around it by listening to the change event as well.

**Comment by Delagen** [comment]
@pkozlowski-opensource Yes. You are right. I found it when I learn code of NgModel directive.
http://caniuse.com/#feat=input-event

**Comment by pkozlowski-opensource** [comment]
@kara I'm going to remove the "Need repro" label as the issue is known - see https://github.com/angular/angular/issues/7557#issuecomment-253723850

**Comment by thomasmerieux** [comment]
Hi guys,

Do you have any update on this issue (or a workaround) ?

Thanks

**Comment by ncroma** [comment]
Using **_FormControl_** and **_formControlName_** on IE9 doesn't update the model either when using backspace. Is this getting worked on soon? This is making text input for IE9 users really unreliable.

**Comment by Fabyao** [comment]
Hi, is there an update/workaround? I believe this is a fundamental issue and the severity set to "inconvenient" is very questionable. This makes IE9 unusable with Angular 2. Until the issues is fixed, I don't think the angular team can claim to support IE9 as suggested here https://angular.io/docs/ts/latest/guide/browser-support.html

**Comment by zoechi** [comment]
I haven't found the page where it's listed what browsers Dart supports but AFAIR it's the last 2 versions of evergreen browsers. I assume the link you posted is for Angular TS/JS only.

**Comment by JCWardle** [comment]
I've been able to use this poly fill as a work around https://github.com/buzinas/ie9-oninput-polyfill

**Comment by katesowles** [comment]
@JCWardle thanks for the polyfill link. That fixed my issue 🎉

**Comment by jamiemac87** [comment]
@JCWardle thank you for the polyfill link you really saved my bacon with this one.

**Comment by yimam-michael** [comment]
I saw this happening when i use `(keypress)`, `(keyup)` or `(keydown)` event emitters on the input element. Try using `(input)` event emitter instead. It will handle all input related events including deleting using backspace or delete key and also pasting a value in to the input itself.
