### ISSUE TITLE
Interpolation does not handle ES 2015 template strings (backticks)

### ISSUE THREAD

**Issue by DeborahK** [angular/angular#7558]
**Note: for support questions, please use one of these channels:** https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
This could be considered a bug or a "missing feature".

* **What is the current behavior?**
When using an ES 2015 template string in interpolation, such as this:
`{{<backtick>Title: ${pageTitle}<backtick>}}` where `<backtick>` is an ES 2015 backtick.

This results in the following error:
EXCEPTION: Template parse errors:
Lexer Error: Unexpected character [`<backtick>`] at column 0 in expression [`Title: ${pageTitle}`] ("<div class='panel panel-primary'>
    <div class='panel-heading'>[ERROR ->]
        {{'Title: ' + pageTitle}} 
        {{`Title: ${pageTitle}`}}
"): ProductListComponent@1:31

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
Add a ES 2015 template string in an interpolation in any template.

* **What is the expected behavior?**
It should display: Title: My Page Title

* **What is the motivation / use case for changing the behavior?**
Using the ES 2015 string interpolation is much easier than concatenating a set of strings. 

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.7
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
- Language: [all | TypeScript 1.8.2 | ES6/7 | ES5 | Dart]
Tried it in IE 11 and Chrome 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by AlexYankee** [comment]
{{}} is the interpolation syntax itself.
Why don't you simply use <span>Title: {{pageTitle}}</span>?
Therefore, for more complex cases it's preferable to incapsulate such computations in component:
``` javascript
constructor(user: User) {
  this.user = user;
  this.prepareProperty();
}
prepareProperty() {
  this.someProperty = `${user.firstName} ${user.lastName}`;
}
```
``` html
<span>{{myComponent.someProperty}}</span>
```
instead of
``` html
<span>{{myComponent.user.firstName}} {{myComponent.user.lastName}}</span>
```
That will help you to scale you app properly in future

**Comment by nickspoons** [comment]
A use case for this that I've run into is performing string interpolation before passing the resulting string to a pipe - which has to happen inside {{}}, i.e.:
```html
<select>
  <option *ngFor="let opt of options" [value]="opt">{{`localization.key.${opt}` | localize}}</option>
</select>
```
Here I'm passing strings to a LocalizePipe. Of course this can currently be done as `{{'localization.key.' + opt | localize}}` but the backtick string interpretation is more readable for complex strings.

**Comment by wesleycho** [comment]
This would require an addition to the parser in `@angular/compiler/expression_parser`, as well as changes to the AST and lexers in that directory.

**Comment by praveenpuglia** [comment]
So this was closed for no reason? Any plans on this?

**Comment by VRedondo** [comment]
any updates on this?

**Comment by Davilink** [comment]
@wesleycho Why the issue was closed.

**Comment by sleshJdev** [comment]
Why did you close the issue???

**Comment by fallenreaper** [comment]
I would like to see more insight in why this was closed, In an effort to keep the framework up to date with the underlying languages, this *should* be a thing.  @vicb will you consider reopening this?

**Comment by lukad** [comment]
I would be interested in this feature as well and I think this issue should not be closed without giving a reason.

**Comment by gustavshf** [comment]
An essential feature.
