### ISSUE TITLE
FirefoxBeta won't connect on SauceLabs

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#7560]
Has been consistently failing for angular/angular and angular/material2
Seems like a Sauce problem, we should report to them?

**Comment by alexeagle** [comment]
Maybe reach them at https://twitter.com/sauceops ?

**Comment by mlaval** [comment]
From what I can see, dev and beta versions of both Firefox and Chrome are no longer available in SL and BS.
I've properly deactivated them in #7718
