### ISSUE TITLE
Drop DomAdapter

### ISSUE THREAD

**Issue by tbosch** [angular/angular#7561]
We should rather:
- have separate `Renderer` implementation for TS browser / TS server / Dart browser / Dart server
- use the `DebugElements` instead of the real DOM in our integration tests.

This might make us also faster in rendering,
and will drop some code.

**Comment by christopherthielen** [comment]
FYI, I'm currently using these things from `DOM` (not `Renderer` concerns) in ui-router-ng2:
- `getLocation()`
- `getHistory()`
- `getBaseHref()`

**Comment by gdi2290** [comment]
@christopherthielen the 3 global objects you mentioned will be available with https://github.com/angular/angular/pull/7984 and https://github.com/angular/angular/pull/7962

**Comment by DzmitryShylovich** [comment]
@tbosch wan't it implemented here https://github.com/angular/angular/commit/d708a8859ca3078a98e371b33ad560096070ad00 ?
