### ISSUE TITLE
Support `/deep/` and `>>>` selectors in `ViewEncapsulation.Emulated`

### ISSUE THREAD

**Issue by tbosch** [angular/angular#7562]
Right now, selectors after `:host` are not properly shimed (see https://github.com/angular/angular/issues/5390). Users already use this feature for theming purposes.

If we supported the `/deep/` and `>>>` selectors, users could just replace `:host ...` with `:host >>> ...`.

Semantics:
```
a >>> b
```
Will be converted into
```
a[ngcontent_xzy] b
```

I.e. the selector after `>>>` and `/deep/` will not be shimmed.

**Comment by todoubaba** [comment]
Has already been implemented?

https://github.com/angular/angular/blob/master/modules/angular2/src/compiler/shadow_css.ts#L437
https://github.com/angular/angular/blob/master/modules/angular2/test/compiler/shadow_css_spec.ts#L145

**Comment by ericmartinezr** [comment]
What about this comment https://github.com/angular/angular/issues/6511#issuecomment-173406175 ?

**Comment by tbosch** [comment]
Thanks @ericmartinezr!

**Comment by tbosch** [comment]
@todoubaba Not implemented yet. If you check the specs, they show that the selectors after `/deep/` are still shimmed.

**Comment by ericmartinezr** [comment]
@tbosch sorry, but my comment was more like *why support something that is/has being deprecated*? See https://bugs.chromium.org/p/chromium/issues/detail?id=489954

**Comment by tbosch** [comment]
@ericmartinezr Supporting `/deep/` is the most logical solution for now. Once we have more resources to implements css variables and also have a good way that is fast enough, we might revisit this.

**Comment by zoechi** [comment]
What's the purpose of adding `/deep/` **and** `>>>`. In shadow DOM that later was supposed to replace the former but they fulfill the same purpose. If you really want to add this feature, it should IMHO be `>>>` and `::shadow` or `/deep/` and `::shadow` (I think `/deep/` was more in use than `'>>>` because these combinators were deprecated shortly after it was announced that `>>>` replaces `/deep/` AFAIR.

**Comment by samvloeberghs** [comment]
Is >>> still the way to go? From what I can read from the web fundamentals, using web components, the best way to do this is using css custom properties / variables:
https://developers.google.com/web/fundamentals/getting-started/primers/shadowdom
I'm sensing great browser compatibility issues here, thank God I'm targetting Chromium on Electron!

**Comment by DzmitryShylovich** [comment]
angular has it's own css parser.

**Comment by samvloeberghs** [comment]
thanks for being so clear @DzmitryShylovich.. So what's the recommendation?
What if I use `ViewEncapsulation.Native`?

**Comment by DzmitryShylovich** [comment]
https://angular.io/docs/ts/latest/guide/component-styles.html#!#-deep-
> The /deep/ and >>> selectors should only be used with emulated view encapsulation.

**Comment by samvloeberghs** [comment]
I managed to read that part already.. But you're totally avoiding my question and suggestion..
> What if I use ViewEncapsulation.Native?
> From what I can read from the web fundamentals, using web components, the best way to do this is using css custom properties / variables:
https://developers.google.com/web/fundamentals/getting-started/primers/shadowdom
Will/should the css custom properties / variables work with emulated?

**Comment by zoechi** [comment]
@samvloeberghs AFAIK you can use it if the browser supports it. Angular doesn't have any special support for them (like for example Polymer does)

**Comment by janwo** [comment]
What is the status now? Shall I use /deep/ in the emulated mode?

**Comment by zoechi** [comment]
@janwo `/deep`/ and `>>>` work the same, just SASS doesn't like `>>>`, but works fine with `/deep/`

**Comment by janwo** [comment]
@zoechi But are there any plans against using /deep/ in angular?

**Comment by zoechi** [comment]
I guess so, probably depending on where shadow DOM is heading.
Angular emulates `/deep`/, therefore it's not relevant it's deprecated in Chrome. Chrome never has to deal with `/deep/`.

**Comment by aperl** [comment]
Is there a clear decision if this will be supported long term? If not then it probably ought to be removed form the documentation. https://angular.io/docs/ts/latest/guide/component-styles.html#!#special-selectors. I would rather it stuck around.

**Comment by zoechi** [comment]
@aperl I'm pretty sure there are no plans to remove it as long as there is not good replacement, and AFAIK there currently isn't, therefore there is no reason to remove it from the docs.

**Comment by kuncevic** [comment]
just being deprecated need to use `::ng-deep` with a versions `4.3` and up https://github.com/angular/angular/commit/b754e60

**Comment by kuncevic** [comment]
will be deprecated soon https://github.com/angular/angular/commit/b754e60

**Comment by ericmartinezr** [comment]
@kuncevic https://github.com/angular/angular/issues/17867#issuecomment-312322174

**Comment by kuncevic** [comment]
@ericcarraway 
>Closing this as we have no plan to remove ::ng-deep in a near future. 
didn't realize that ;) tnahks

**Comment by daddyschmack** [comment]
@kuncevic, that's not what this article is saying:
https://angular.io/guide/component-styles#!%23special-selectors
