### ISSUE TITLE
Replace all 'bindings' with 'providers' throughout source code

### ISSUE THREAD

**Issue by wardbell** [angular/angular#7564]
Metadata in much of the code base still refers to `bindings:` and `viewBindings:` instead of `providers:` and `viewProviders:`

Exs: [NgModel](https://github.com/angular/angular/blob/master/modules/angular2/src/common/forms/directives/ng_model.ts#L52), 
[Directive metadata](https://angular.io/docs/ts/latest/api/core/DirectiveMetadata-class.html)

We've deprecated that forever. Should remove from the product before release?

**Comment by johnpapa** [comment]
good idea. do you think others should happen?
- `as` --> `name`  (router)
- the old events and props --> `input` and `output`
- `@view`

**Comment by wardbell** [comment]
Yes!  The sweep of `@View` is currently underway.

**Comment by vamsivarikuti** [comment]
@wardbell : shall i take this task? I have previously migrated  `as` to `name`
If `@View` is swept, I'll take the following

- `bindings` --> `providers`
- `viewBindings` --> `viewProviders`
- `events`--> `input`
- `props` --> `output`
I will delete `as` property and allow only `name`
I'll update the unit tests accordingly. 
Anything else that i should know about?

**Comment by IgorMinar** [comment]
this is done already.
