### ISSUE TITLE
dartdoc shouldn't display "const const"

### ISSUE THREAD

**Issue by kwalrath** [angular/angular#7565]
**1. Screenshot of bad content**
![angulardocbug](https://cloud.githubusercontent.com/assets/2164483/13717344/b902fd5a-e795-11e5-8bd6-d6eec6c219f1.png)

**2. URL where screenshot was taken**
https://ngdartdoc-dev.firebaseapp.com/angular2.common/angular2.common-library.html

**3. Why the content is bad**
It's weird to see `const const` everywhere.

**4. What the content should look like**
I'd expect one or no `const`s. After all, the section is already called "Constants".

**5. Where else this issue occurs**
I suspect this would happen anywhere you show constants, but I didn't see constants anywhere else in the docs.

@naomiblack

**Comment by naomiblack** [comment]
@vikerman this seems to have been introduced (maybe?) by the latest ts2dart changes. can you have a look?
