### ISSUE TITLE
json pipe broken by Promise?

### ISSUE THREAD

**Issue by sebastianovide** [angular/angular#7568]
* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
error in console:
`angular2.dev.js:23607 EXCEPTION: Expression 'data promise: {{data | json}} in AppComponent@4:9' has changed after it was checked.`

* ** to reproduce** 
in [plnkr](https://plnkr.co/edit/6OXyaTOCPLcjGRuNaze0?p=preview) uncomment json pipe. 

* **What is the expected behavior?**
you should see the promise value in json format before and after the click. Or, if for some reason Promises are not supported by the json pipe, an error saying so.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.9
- Browser: [Chrome 49.0.2623.87 (64-bit) | Firefox 45.0  | Safari 9.0.3 (11601.4.4)]
- Language: [TypeScript 1.7.3 ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
[stackoverflow](http://stackoverflow.com/questions/35879923/angular2-beta9-json-pipe-broken-by-promise
)

**Comment by gdi2290** [comment]
this is a problem with AsyncPipe not providing a `toJSON` method that maps to `_result`

**Comment by gdi2290** [comment]
nvm, I didn't uncomment it I was looking at the `*ngIf` this is by design since you're meant to do `data | async | json` otherwise json will also include logic to resolve the async value

**Comment by robwormald** [comment]
`data | async | json` is the right way to do this - see https://plnkr.co/edit/uaMoY6oyjDivWf3mM1Z4?p=preview
