### ISSUE TITLE
TypeError: Cannot read property 'registerPrimaryOutlet' of null

### ISSUE THREAD

**Issue by davidrensh** [angular/angular#7569]
We got the error:TypeError: Cannot read property 'registerPrimaryOutlet' of null
This is only happened when I add parameter in constructor with :params:RouteParams

Error during instantiation of Home
    at Home.RouterOutlet (router.dev.js:1958)
    at new Home (Home.ts:38)
    at angular2.dev.js:1432
    at Injector._instantiate (angular2.dev.js:11367)
    at Injector._instantiateProvider (angular2.dev.js:11294)
    at Injector._new (angular2.dev.js:11284)
    at InjectorInlineStrategy.instantiateProvider (angular2.dev.js:11048)
    at ElementDirectiveInlineStrategy.init (angular2.dev.js:8962)
    at new AppElement (angular2.dev.js:8652)
    at HostViewFactory.viewFactory_HostHome0 [as viewFactory] (viewFactory_HostHome:73)

angular2.dev.js:23501 _Context {element: reddit, componentElement: router-outlet, injector: Injector}BrowserDomAdapter.logError @ angular2.dev.js:23501ExceptionHandler.call @ angular2.dev.js:1202(anonymous function) @ angular2.dev.js:12489NgZone._notifyOnError @ angular2.dev.js:13533errorHandling.onError @ angular2.dev.js:13441Zone.run @ angular2-polyfills.js:1247(anonymous function) @ angular2.dev.js:13456zoneBoundFn @ angular2-polyfills.js:1220lib$es6$promise$$internal$$tryCatch @ angular2-polyfills.js:468lib$es6$promise$$internal$$invokeCallback @ angular2-polyfills.js:480lib$es6$promise$$internal$$publish @ angular2-polyfills.js:451(anonymous function) @ angular2-polyfills.js:123microtask @ angular2.dev.js:13488Zone.run @ angular2-polyfills.js:1243(anonymous function) @ angular2.dev.js:13456zoneBoundFn @ angular2-polyfills.js:1220lib$es6$promise$asap$$flush @ angular2-polyfills.js:262

The router config:
```
 <a [routerLink]="['/Home', {a: '', b: ''}]">Home</a>
@RouteConfig([
        { path: '/home/:a/:b', name: 'Home', component: Home },
])

```
Then navigate to:
`this.router.parent.navigate(['/Home', { a: store, b: branch }]);`

The target component with params:RouteParams:
```
export class Home extends RouterOutlet{
..
    constructor(params:RouteParams,_elementRef: ElementRef, _loader: DynamicComponentLoader,
        _parentRouter: Router, @Attribute('name') nameAttr: string) {
        super(_elementRef, _loader, _parentRouter, nameAttr);
```

**Comment by zoechi** [comment]
Seems to be similar to #6425

**Comment by wahtye** [comment]
Happens to me as well. As soon as I inject anything but the 4 extended components into the RouterOutlet, this error appears.  
I'm trying to inject a service that has been initiated in the Component, which hosts the <route-outlet>-selector.

**Comment by brandonroberts** [comment]
@wahtye can you reproduce in a plunker?

**Comment by wahtye** [comment]
This should reproduce the issue:  
https://plnkr.co/edit/uplZMfT5VoeBtRY7AkJ3?p=preview

**Comment by brandonroberts** [comment]
@wahtye I see. Another weird issue is that if you move the service to be injected after the `@Attribute` it works fine. 

https://plnkr.co/edit/bFQO7Xh5ks5Fy8fxJw65?p=preview

**Comment by davidrensh** [comment]
My workaround is remove elementRef , ie:
`constructor(params: RouteParams, _parentRouter: Router)` 
It's not working if you really want elementRef

**Comment by wahtye** [comment]
@brandonroberts Welp, this solves it embarrassingly. Thanks a lot.  

@davidrensh You need the ElementRef for a valid extension and the super call of RouterOutlet though, don't you?

**Comment by davidrensh** [comment]
My case is simple. I just need navigate to login router, no elementRef is ok for that.
I did not try if it's working with route parameters with brandonroberts solution.

**Comment by brandonroberts** [comment]
@davidrensh Ok, so you're using a router outlet to redirect to another route? Are you doing some type of auth check there?

**Comment by davidrensh** [comment]
Yes, we use firebase email password check

**Comment by vicb** [comment]
obsolete
