### ISSUE TITLE
BUG: ngModelChange fired in different order on mobile vs. desktop

### ISSUE THREAD

**Issue by jamesandersen** [angular/angular#7570]
- **What is the current behavior?**
  The event handlers for `keyup` and `ngModelChange` fire in a different order on desktop (Chrome 48 on Mac) vs. Samsung Galaxy S4 (Chrome 48 on Android 5.0)

Use [this Plunkr](http://plnkr.co/edit/sXdpYyYYS4il4gSOoVJC?p=preview) to repro.
1. Type a letter in the plunkr **while on desktop** and see:
   <img width="492" alt="desktop_keyup" src="https://cloud.githubusercontent.com/assets/2119576/13720440/aa0ec50e-e7d6-11e5-9da5-2d545d1e2161.png">
2. Type a letter in the plunkr **while on mobile** and see:
   ![screenshot_2016-03-11-22-06-51](https://cloud.githubusercontent.com/assets/2119576/13720442/b1730ca6-e7d6-11e5-8694-5eb8cc5beb5f.png)
- **What is the expected behavior?**
  The order of events fired should be consistent on both platforms; I think I'd expect the key event first on both platforms personally.
- **What is the motivation / use case for changing the behavior?**
  Unexpected order of events leads to buggy code.  In my case I found that I couldn't rely on the model value being set in my `keyup` handler when on mobile devices.
- **Please tell us about your environment:**
- Angular version: 2.0.0-beta.9
- Android Browser: Chrome 48 on Android 5.0
- Desktop Browser: Chrome 48 on Mac
- Language: TypeScript 1.8.2 (see plunkr)

**Comment by AndrewKushnir** [comment]
Hi, I've just re-created the repro using Stackblitz, see [here](https://stackblitz.com/edit/angular-ivy-m5ru92) and we tested the behavior using:

- Chrome (83.0.4103.83) on Android 
- Chrome (83.0.4103.61) on MacOS

In both cases the events fired in the same order ("change fired" and after that "key event fired").
It looks like it was browser-specific issue which is now resolved. I will close this ticket and feel free to open a new one if the problem still exists.

Thank you.
