### ISSUE TITLE
Rename `ngSwitchWhen` to `ngSwitchCase`

### ISSUE THREAD

**Issue by userpixel** [angular/angular#7571]
* **I'm submitting a ... **
[ ] bug report
[X] feature request

* **What is the current behavior?**

```
<X ngSwitch]="...">
  <Y *ngSwitchWhen="..."></Y>
  <Y *ngSwitchWhen="..."></Y>
  <Y *ngSwitchWhen="..."></Y>
  <Z *ngSwitchDefault></Z>
</X>
```

* **What is the expected behavior?**

```
<X ngSwitch]="...">
  <Y *ngSwitchCase="..."></Y>
  <Y *ngSwitchCase="..."></Y>
  <Y *ngSwitchCase="..."></Y>
  <Z *ngSwitchDefault></Z>
</X>

```

* **Please tell us about your environment:**

It would be great to rename `ngSwitchWhen` to `ngSwitchCase` to keep it consistent with Javascript and Typescript switch/case keywords. From the first time I got to know angulat I've been wondering why it uses "when" instead of "case" where the "default" is used properly indeed. Just a syntactic sugar, but it would be great to fix it before Angular 2 is in production because then it would be almost impossible to change.

**Comment by robwormald** [comment]
this seems like a reasonable suggestion to me, and justifiable given we stick to ES6 semantics and left behind ng-repeat-in for ngForOf. @IgorMinar ?

**Comment by IgorMinar** [comment]
I agree. @mhevery can we put this on the rc list?

**Comment by gkalpak** [comment]
<sub>(It will also be more consistent with `NgPlural/NgPluralCase`.)</sub>

**Comment by mhevery** [comment]
Yes, added.
