### ISSUE TITLE
Error Template parse, <div> with <p>

### ISSUE THREAD

**Issue by languorous001** [angular/angular#7572]
I don't no this is a bug, but I try to help.

`<div class="navbar-right">
        ................
</div>`

Using div is not error. But I try using tags p

`<p class="control">
       <div class="navbar-right">..........</div>
</p>
`

it error template parse: Unexpected closing tag "p".
I using bulma.io

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/issues/6648

**Comment by languorous001** [comment]
thank a lot.

**Comment by pkozlowski-opensource** [comment]
Closing as duplicate of #6648, thnx @ericmartinezr !
