### ISSUE TITLE
router.generate returns always undefined

### ISSUE THREAD

**Issue by mburger81** [angular/angular#7574]
It seems that generating a route to check if route is active doesn't work anymore

```
import { ROUTER_DIRECTIVES, Location, Router } from 'angular2/router';
....
constructor(private location: Location, private router: Router) {
    router.generate['/MyRoute'];
}
```

router.generate always return undefined

this
Michael

**Comment by ericmartinezr** [comment]
[Router#generate](https://angular.io/docs/ts/latest/api/router/Router-class.html) is a function. Read the docs. Its' working fine for me in this [plnkr](http://plnkr.co/edit/TlIwqOElC0VpoMLAXAe7?p=preview).

**Comment by mburger81** [comment]
Infact, router.generate should return an Instruction.
but
`router.generate['/Test']);`
returns in your plnkr example undefined.

Some beta before I'm sure I was able to do this for check which router is active

return this.router.isRouteActive(this.router.generate(['/MyRoute']));

**Comment by ericmartinezr** [comment]
@mburger81 I don't really understand your issue. You're doing it wrong, `generate` is a function, if you do `generate['/Route']` it will obviously be undefined since `generate` is a function, not a property. But in your last example you're using it as a function, as you should...

**Comment by mburger81** [comment]
@ericmartinezr It wos only an example, I clearly intended to use it as a function,

infact if do this in your plnkr  `this.router.isRouteActive(this.router.generate(['/MyRoute']));` you will get this error `TypeError: Cannot read property 'isRouteActive' of undefined` becouse the return of the function `router.generate` is always `undefined`  I think this was working some time ago.

If not how can I check if route is active?

The second answer here was working for me time ago

http://stackoverflow.com/questions/34323480/in-angular-2-how-do-you-determine-the-active-route

**Comment by ericmartinezr** [comment]
`router.isRouteActive(router.generate(['/Test']))` that works perfectly in the plnkr above, and your example had nothing to do with your issue. Provide a plnkr with your issue please.

**Comment by mburger81** [comment]
okay i found the error, i passed the router wront to generate.

so no issue thx you
