### ISSUE TITLE
ng2-bootstrap could not be loaded in angular 2

### ISSUE THREAD

**Issue by asiacoll** [angular/angular#7575]
ng2-bootstrap could not be loaded in angular 2 when for example: "import {Alert} from 'ng2-bootstrap/ng2-bootstrap';" .

error mssage:

Error: SyntaxError: Unexpected token <
	    at eval (native)
	    at https://cdnjs.cloudflare.com/ajax/libs/ng2-bootstrap/1.0.6/ng2-bootstrap.min.js:2:7940
	Evaluating https://localhost:44344/node_modules/moment/moment.js
	Error loading https://localhost:44344/app/main.ts

**Comment by ericmartinezr** [comment]
@asiacoll this repo is not for ng2-bootstrap, and it's not supported by ng2 team. Ask your questions in their chatroom https://gitter.im/valor-software/ng2-bootstrap or StackOverflow, keep github for reporting bugs related to the framework.

**Comment by pkozlowski-opensource** [comment]
Thnx @ericmartinezr !
