### ISSUE TITLE
routerOnActivate promise does not delay component display.

### ISSUE THREAD

**Issue by wardbell** [angular/angular#7576]
**I'm submitting a**
[x] bug report
[ ] feature request
[ ] support request 

The router displays the component immediately, regardless of the result of `routerOnActivate`. 

This is most apparent when that method returns a promise.

I believe the cause is in `RouterOutlet.activate` which calls the `DynamicComponentLoader.loadNextToLocation` _before the result of `routerOnActivate` is known_.
The loader displays the component immediately.

See [this plunker](http://plnkr.co/edit/TobmZH2lMRpUam9HTBaI) (a cut down version of the router demo in the docs) for a demonstration of the experience.

You may wonder why I wrapped `CrisisDetailComponent` in `CrisisDetailShellComponent`.  I wanted to be true to the letter of [the documentation](https://angular.io/docs/ts/latest/api/router/OnActivate-interface.html) which says

>If routerOnActivate returns a promise, the route change will wait until the promise settles to instantiate and activate **child components**. [*emphasis mine*]

I think that wrapping should be unnecessary. It shouldn't display the component itself let alone its children. But in case that mattered, I made sure that the `routerOnActivate` governed the parent of the child that it should not display.

**Comment by naomiblack** [comment]
Can you check to see whether this PR solves the problem for you? https://github.com/angular/angular/pull/7545

**Comment by wardbell** [comment]
Does not appear to have solved it. This PR was merged to master on March 16; beta.11 released on March 18;  I updated the plunker to beta.11 just now and it still fails the same way.

**Comment by brandonroberts** [comment]
@wardbell if this fix is implemented, will it force users to push routes down a level in order to protect child routes using this lifecycle hook?

**Comment by vicb** [comment]
@wardbell as discussed, the child routes will only get activated once the Promise is settled, see this [plunker](http://plnkr.co/edit/4SFbJrwrFaehSkYHtc4P?p=preview).

The behavior is expected and the docs should be updated

**Comment by wardbell** [comment]
Thanks for that clarification, @vicb. 

Accordingly, one part of the resolution of this issue is documentation updates.  We need to correct the API doc which currently says:
>If routerOnActivate returns a promise, the route change will wait until the promise settles to instantiate and activate child components.

### Trouble remains ...

The `routerOnActivate` method is quite useful in *all* routed components, including leaf components. But the semantics of the method's return value feel deeply broken to me. 

And the more you look at this, the more you stumble over the difficulties of discovering programmatically what the router is doing at any moment.

I took my new understanding about `routerOnActivate` with routing components and [extended the plunker](http://plnkr.co/edit/TobmZH2lMRpUam9HTBaI?p=preview) with your new example + my variations.  
> Checkout the second section, "OnActivate in Routing Component". The code behind it is `app/parent.child.component.ts`

Here are some observations from using `OnActivate` in a routing component.

>I define a _routing_ component defined as a component that handles routing and contains a `<router-outlet>`; the terminal destination component I'm calling a _leaf_ component.

1. Doesn't matter if the returned value is true, false, undefined ... the parent & child are displayed. Had this been a leaf, a synchronous false value would abort navigation as we see in the Crisis Center example.

2. The promise can delay the appearance of the child but not thwart it.

3. There is no way to tell from within the parent where the navigation is headed. You get only the path to the parent ... no info about the destination.  Therefore, can't make decisions based on destination.

4. I tried to stuff something in the `routeData` but couldn't find a good way to do that for this purpose. That speaks also to uncertainty surrounding the `RouteData` object: what is it? when to use it? is it mutable or not? etc.

5. Had to make clever use of routeParams ​_to the parent_​ to differentiate destination component ... yuck. 

6. FWIW, this trick of using the params has the unfortunate side-effect of polluting the url: `~/parent/fastchild?isFast=true`

7. The behavior of `routerOnActivate` is radically different between leaf and routing component. In a leaf component, if  `routerOnActivate` method returns `false` synchronously, the router returns to the previous component. But if it returns `false` asynchronously, the router stays on the destination component. Why _that_ difference? Why is the treatment of a synchronous `false` different in routing and leaf components?

### Apology
I realize I've turned this into a big sack of ... issues ... that might better be broken apart.  Tell me how you'd like me to approach that and I will do so.

OTOH, it demonstrates how the trouble is compounded by design problems throughout the router, in particular
* lack of router access/transparency
* `Instruction` v. `ComponentInstruction`
* Imperfect information about the route
* `RouteData`
* oddities in router lifecycle method behavior
* lack of injectable `CanActivate` that drove me into this ditch to begin with.

**Comment by mhevery** [comment]
> Doesn't matter if the returned value is true, false, undefined ... the parent & child are displayed. Had this been a leaf, a synchronous false value would abort navigation as we see in the Crisis Center example.

Return value should always be ignored. We need to investigate the leaf claim here.

> The promise can delay the appearance of the child but not thwart it.

correct, only `canActivate` can prevent. By the time we got to `onActivate` we are commited.



> There is no way to tell from within the parent where the navigation is headed. You get only the path to the parent ... no info about the destination. Therefore, can't make decisions based on destination.

Yes, this is something which we are working on redesigning. 



> The behavior of routerOnActivate is radically different between leaf and routing component. In a leaf component, if routerOnActivate method returns false synchronously, the router returns to the previous component. But if it returns false asynchronously, the router stays on the destination component. Why that difference? Why is the treatment of a synchronous false different in routing and leaf components?

There should be no difference. Please help me understand your code so that we can get to the bottom of this.

**Comment by wardbell** [comment]
@mhevery  Owe you one. The following claim is false:
>Had this been a leaf, a synchronous false value would abort navigation as we see in the Crisis Center example.

I somehow overlooked the line in the synchronous path that was causing it to navigate away. `this._router.navigate(['CrisisList']);`   I feel like a bone head.

All that remains to do is:

1. Fix the API documentation to explain (a) what this method does, (b) what the promise is good for and (c) that the result of the method (sync or resolved promise) has no effect on the router.

2. Make it possible for the `routerOnActivate` method to know where the navigation is going.

Feel free to close and open these two issues separately (or ask me to do so).

**Comment by vsavkin** [comment]
We are no longer maintaining the deprecated router to focus our efforts on making the new router robust.

It does not look like the issue makes sense in the new router. If you think it does, please reopen it in the context of the new router.

Closing this issue.
