### ISSUE TITLE
Uncaught (in promise) TypeError: object is not a constructor(…)  at then (native)

### ISSUE THREAD

**Issue by sap9433** [angular/angular#7583]
* **Issue -  was working perfect without any console error . Now throwing error while using angular2 Router.**
```
Uncaught (in promise) TypeError: object is not a constructor
    at then (native)
```

Using webpack to bootStrap [ng-2](https://github.com/sap9433/angular2-webpack-starter-kit).Getting console error on app load . It might be a problem with `"es6-shim": "^0.33.3"` and people are saying it's fixed in `"es6-shim": "^0.35.0"` , but `"angular2": "2.0.0-beta.9",`  still depends on `"es6-shim": "^0.33.3"` , and just changing the peer-dependency in my local for ng2 and using `"es6-shim": "^0.35.0"` didn't fix the issue .

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Getting error Uncaught (in promise) TypeError: object is not a constructor(…)  at then (native) at then (native)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
1. clone this - https://github.com/sap9433/angular2-webpack-starter-kit
2. npm install
3. npm run start
4. load the localhost:9876 in your browser , it shows the errors.

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.7 
- Browser: [Version 49.0.2623.75 (64-bit) . Mac El Capitan  ]
- Language: [TypeScript]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by ericmartinezr** [comment]
Remove the `shims` entry point in your webpack.config.js, you're including `router.dev.js` which is bundled using systemjs builder (why are you even doing that?). After you remove it, add `angular2-polyfills` in your index.html above your app.js script tag.

If you want to bundle all your possible polyfills follow this webpack starter https://github.com/AngularClass/angular2-webpack-starter/blob/master/webpack.config.js#L35

**Comment by sap9433** [comment]
Edited the bug report , added that line by mistake and that was causing the system error. . __Sorry . And Thanks for detecting that__ . However  the main error mentioned in title `Uncaught (in promise) TypeError: object is not a constructor(…) at then (native) ` got nothing to do with it . And I think `"angular2": "2.0.0-beta.9"` should update it's peerDependencies to `"es6-shim": "^0.35.0"`

**Comment by sap9433** [comment]
Ok . [ericmartinezr](https://github.com/ericmartinezr) . Thanks a ton for pointing to right direction , `angular2/bundles/angular2-polyfills.js` contains all shims es6 , zones , reflex meta-data etc . No need to bundle them separately .. So just removing everything esle form shim entry fixes this . __Thanks again. Closing it__

**Comment by davidrensh** [comment]
It's fixed for chrome. It will give error "Object doesn't support property or method 'keys' on IE.

**Comment by CaptainCodeman** [comment]
> angular2/bundles/angular2-polyfills.js contains all shims es6 , zones , reflex meta-data

Not quite - it contains zones and reflect-metadata but no es6 shims. They still need to be loaded separately (otherwise you get the error @davidrensh describes above). You can use es6-shim or core.js for that (and core.js also includes reflect-metadata as well).

So many shims, polyfills and possibly combinations to load them all in ...
