### ISSUE TITLE
(angular1_router) Bug: isRouteActive returning incorrect results

### ISSUE THREAD

**Issue by alexgoldstone** [angular/angular#7587]
The result of `isRouteActive` seems to be based on the parent instruction and not the specified child instruction.

I have a parent component with routeConfig that looks like:

```
$routeConfig: [
    {path: '/organisations/...', name: 'Organisations', component: 'organisations', useAsDefault: true}
]
```

I have a child component with routeConfig that looks like:

```
$routeConfig: [
    {path: '/', name: 'OrganisationsList', component: 'organisationsList', useAsDefault: true},
    {path: '/new', name: 'OrganisationNewForm', component: 'organisationForm'},
    {path: '/:id', name: 'OrganisationEditForm', component: 'organisationForm'}
],
```
 
In the parent component's controller I declare a `routeIsActive` function as:

```
var ctrl = this;

ctrl.routeIsActive = function(childRouteName) {
    var instruction = ctrl.$router.generate([childRouteName]);
    return ctrl.$router.isRouteActive(instruction);
};
```

In the parent component's view I use my `routeIsActive` function as follows:

```
<div ng-show="$ctrl.routeIsActive('Organisations')">
    <div class="buttons-container right">
        <button ng-show="!$ctrl.routeIsActive('Organisations/OrganisationNewForm')" class="btn btn-info" ng-link="['Organisations/OrganisationNewForm']">Add <i class="icon right ion-md-add"></i></button>
    </div>
    <h1>Organisations</h1>
</div>
```

The problem is that when `$ctrl.routeIsActive('Organisations')` is `true` then `$ctrl.routeIsActive('Organisations/OrganisationNewForm')` is also returning true even when it shouldn't be.

**Comment by alexgoldstone** [comment]
I missed it earlier but this seems to describe the same issue with the Angular 2 router:

https://github.com/angular/angular/issues/6080#issuecomment-182775326

**Comment by stnor** [comment]
I can confirm this. The "ng-link-active" class gets applied to all child routes.

**Comment by vicb** [comment]
obsolete
