### ISSUE TITLE
[testing] TestComponentBuilder.overrideDirective does not work with RouteConfig

### ISSUE THREAD

**Issue by choeller** [angular/angular#7589]
**Note: for support questions, please use one of these channels:** https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

a bug

* **What is the current behavior?**

When testing routing it is not possible to override the components used in a `@RouteConfig`

e.g. having a main component like this:

```ts
@Component({
  selector: 'project-manager-app',
  templateUrl: 'app/project-manager.html',
  styleUrls: ['app/project-manager.css'],
  directives: [ROUTER_DIRECTIVES]
})
@RouteConfig([
  {path: '/', component: Dashboard, name: 'Dashboard'},
  {path: '/settings', component: Settings, name: 'Settings'},
 { path: '/**', redirectTo: ['Dashboard'] }
])
export class ProjectManagerApp {
...
```
and trying to override Settings and Dashboard to use a DummyComponent like this:

```ts
        return tcb
          .overrideDirective(ProjectManagerApp, Dashboard, Dummy)
          .createAsync(ProjectManagerApp)
```
leads to the following error:
` : Overriden directive Dashboard not found in the template of ProjectManagerApp`

* **What is the expected behavior?**

It needs to be possible to override the Components used in a RouteConfig, otherwise the whole application gets bootstraped when testing routing

* **What is the motivation / use case for changing the behavior?**

The need to test routing behaviour

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [Chrome / Karma]
- Language: [TypeScript 1.8.7]

**Comment by vicb** [comment]
obsolete
