### ISSUE TITLE
Add milliseconds support on Date Pipe

### ISSUE THREAD

**Issue by meriturva** [angular/angular#7590]
As Angular 1 we need milliseconds support on date format from Date Pipe....
Actually new Date Pipe doesn't support it:

https://angular.io/docs/ts/latest/api/common/DatePipe-class.html

please add it, otherwise it will be quite difficult to migrate old components using new pipes!
Thanks!

**Comment by qina83** [comment]
+1

**Comment by DydFreeman** [comment]
+1

**Comment by wesleycho** [comment]
This appears to be a weakness of the Intl api that Angular is using under the hood - see [Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat). I suspect this is not going to be supported by the date pipe as a result, so one may need to write a custom pipe if one wants millisecond support.

**Comment by meriturva** [comment]
Sorry @pkozlowski-opensource i just would like to have an update here. We have to take a decision on our side...do we have to develop our solution? or are you going to add that on i18n project?

**Comment by wesleycho** [comment]
IMO this would involve reinventing date parsing if Angular is to support it in the date pipe, which introduces a significant amount of bloat for users who get no benefit from this.

It is simpler for the user to create their own solution for things like this - we had to create a custom pipe at work around moment.js to work around non-standard date formatting for example.

**Comment by ocombe** [comment]
Hello, the millisecond format option will be added with the PR to replace the intl API for angular v5 (see [#10809](https://github.com/angular/angular/issues/10809 "[Disscussion] Internationalization API issues."))
