### ISSUE TITLE
Hot reloading

### ISSUE THREAD

**Issue by doczoidberg** [angular/angular#7597]
Is something like react's [hot reloading](https://medium.com/@dan_abramov/hot-reloading-in-react-1140438583bf#.jphvnz146) possible with Angular 2 + Webpack?
Are there plans to support something like this?

**Comment by zoechi** [comment]
Sorry, I can't help you with your question.

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by doczoidberg** [comment]
this is a feature request and not a support question

**Comment by ericmartinezr** [comment]
See Patrick's repo https://github.com/AngularClass/angular2-webpack-starter/blob/master/src/main.ts#L78

**Comment by doczoidberg** [comment]
The state of all components is lost when a module is reloaded.

Is it possible to keep/reload the state by using RxJs?

**Comment by MarkPieszak** [comment]
I didn't know it lost state, really? Thought everything worked! I'd be curious to know if you ever find a way around this. @doczoidberg

**Comment by doczoidberg** [comment]
@MarkPieszak I set the data.value via input and then change the template in about.ts. The data.value is gone then.

**Comment by MarkPieszak** [comment]
There's this but I haven't tried it yet

http://blog.mgechev.com/2015/10/26/angular2-hot-loader-hot-loading-tooling

**Comment by gdi2290** [comment]
it's possible to maintain the state by reusing the injector and/or using proxy component/services.

**Comment by gdi2290** [comment]
please read the article by the creator of suggesting that the current method I've used in the webpack starter is now the prefered and recommended method
https://medium.com/@dan_abramov/hot-reloading-in-react-1140438583bf#.j3l954n58

**Comment by robwormald** [comment]
in theory this is possible, but tooling is out of scope of angular core.

**Comment by doczoidberg** [comment]
@MarkPieszak thanks for the link. Seems that the reloading already works but you have to use the mentioned architecture to keep the state. The other approach is the patching of components as stated in the article. This is a tooling thing as robwormald has said.

**Comment by MarkPieszak** [comment]
@doczoidberg I'll do any type of architecture to get it going haha. Once I've experienced HMR, there's no going back, spoiled now haha.

**Comment by gdi2290** [comment]
@MarkPieszak I can make an example in the angular2-webpack-starter if you're interested

**Comment by gdi2290** [comment]
I just got it working locally

**Comment by MarkPieszak** [comment]
I'd love that! I think it's important to showcase Angular2 has HMR just like React "hypes" it up haha
Yeah, I thought everything worked (in your repo) too, let me double check as well. @gdi2290

**Comment by robwormald** [comment]
This would be a useful thing to add to angular-CLI - maybe open a PR there.

**Comment by doczoidberg** [comment]
I already opened and closed an issue there. They've sent me to this repository....

**Comment by MarkPieszak** [comment]
@gdi2290 Running the angular2-webpack-starter now and ya it looks like the example of `this.data = { "value: "" }` gets lost when updating anything. 

I guess that's what doczoid was talking about.

Seems like that'd be a tough one to figure one to figure out... hm

**Comment by doczoidberg** [comment]
[this](https://github.com/mgechev/angular2-hot-loader) is the rep of @mgechev by the way

**Comment by gdi2290** [comment]
I haven't pushed it up the changes to maintain state yet so it's not in the starter

**Comment by MarkPieszak** [comment]
Is it something that needs to be done webpack wise (with a loader or something) or with the way we need to code Angular2 itself? @gdi2290
