### ISSUE TITLE
Date filter is not working on iPhone version of chrome and safari

### ISSUE THREAD

**Issue by davidrensh** [angular/angular#7598]
Date filter is not working on iPhone version of chrome (49.0.2623.73) and safari, it's working on desktop chrome (48.0.2564.116)
`Last` swipe:{{last | date:'dd MM yyyy'}} &nbsp; Expiry:{{expiry | date:'dd MM yyyy'}}

**Comment by zoechi** [comment]
Looks like a dup of #6736 and therefore #3333

**Comment by davidrensh** [comment]
Chrome version 49.0 iPhone version cannot display result. chrome 48.0 desktop version for Windows 7 is fine.

**Comment by ericmartinezr** [comment]
@davidrensh when you created the issue there was a template you were supposed to follow. In that template you can read the next section

```
* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
``` 

Next time would be nice of you to follow that template, don't remove it and provide a minimal example. The template is there for a reason.

**Comment by davidrensh** [comment]
sorry, plnkr is here [http://plnkr.co/edit/ytyvVstVtZ2PDY4UuCBj?p=preview](http://plnkr.co/edit/ytyvVstVtZ2PDY4UuCBj?p=preview)

**Comment by wesleycho** [comment]
This could probably be closed as a duplicate. One needs to polyfill for the Intl api.

**Comment by vicb** [comment]
Duplicate (need to include Intl polyfill)
