### ISSUE TITLE
Updated to 0.9 and getting EXCEPTION: No Directive annotation found on ...

### ISSUE THREAD

**Issue by born2net** [angular/angular#7599]
I've updated to 0.9 and getting EXCEPTION: No Directive annotation found on ModalComponent.
ModalComponent is part of the bs3 lib: https://github.com/dougludlow/ng2-bs3-modal
and the ModalComponent is decorated as a @Component...

as you can see here: https://github.com/dougludlow/ng2-bs3-modal/blob/master/src/ng2-bs3-modal/components/modal.ts

any ideas?

Sean

**Comment by PascalPrecht** [comment]
Hi @born2net 

Can you please create a plunk that reproduces your issue so people can take a look?

Thanks!

**Comment by pkozlowski-opensource** [comment]
Closing ad it is a support question.
