### ISSUE TITLE
Class selector for root component removes other existing classes

### ISSUE THREAD

**Issue by gsans** [angular/angular#7606]
**Note: for support questions, please use one of these channels:** https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
When using the selector: ".my-app" for the root component it removes any other classes being used. So for this html
```html
<div class="title my-app other">loading...</div>
```
we get
```html
<div class="my-app">...</div>
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
https://plnkr.co/edit/1arcIgGRv6U2qNljnrgv?p=preview

* **What is the expected behavior?**
I would expect any other classes to remain in the element.

* **What is the motivation / use case for changing the behavior?**
Be able to use a class as a selector for the root component while keeping any pre-existing classes.

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.8
- Browser: [Chrome 48]
- Language: [TypeScript]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by vicb** [comment]
fixed
