### ISSUE TITLE
[Animate] ng-leave not applied

### ISSUE THREAD

**Issue by youdz** [angular/angular#7607]
First of all, I know animations are not released yet. But you have the basic ones almost done, as far as I can see from the code, except you have a bug that prevents the animations to trigger when an element is detached. If it is minimal work to get them working again, maybe it's worth it to do it now?

For instance, your [current example](https://github.com/angular/angular/tree/master/modules/playground/src/animate) of animations through CSS classes is broken: the box fades in correctly, but does not fade out.

I believe this is due to the current implementation of the [DOM renderer](https://github.com/angular/angular/blob/e7470d557df0400a812d84551524970cb5f12eee/modules/angular2/src/platform/dom/dom_renderer.ts#L149): the `detachView` method removes the node before animations can trigger.
```typescript
  detachView(viewRootNodes: any[]) {
    for (var i = 0; i < viewRootNodes.length; i++) {
      var node = viewRootNodes[i];
      DOM.remove(node);
      this.animateNodeLeave(node);
    }
  }
```

I looked into alternative solutions with the [CSS animation builder](https://github.com/angular/angular/blob/master/modules/angular2/src/animate/css_animation_builder.ts), but [OnDestroy](https://angular.io/docs/ts/latest/api/core/OnDestroy-interface.html) does not allow to return a Promise or an Observable to delay the removal.

Could you offer an equivalent of [routerCanDeactivate](https://angular.io/docs/ts/latest/api/router/CanDeactivate-interface.html) or [routerOnDeactivate](https://angular.io/docs/ts/latest/api/router/OnDeactivate-interface.html) for directives that are not linked to routing? For instance by having `ngOnDestroy()` "pause" the destruction of the directive or component if it returns a Promise?

Thanks

**Comment by ericmartinezr** [comment]
I think it may be dup of https://github.com/angular/angular/pull/6768

**Comment by matsko** [comment]
Now that we have the new API in place (which has working support for [leave animations](https://angular.io/docs/ts/latest/guide/animations.html#!#example-entering-and-leaving)) this issue can be closed.
