### ISSUE TITLE
Angular2 bootstrap hides the original error when one or more module is not loaded by systemjs properly

### ISSUE THREAD

**Issue by kisdaniel** [angular/angular#7610]
I have faced the following error when my app bootstrap function is called:

"VM590 angular2-polyfills.js:1243 Error: Cannot read property 'getOptional' of undefined"

it is caused because one module is not loaded properly (ng2-translate). I have to spend a hours to debug what the problem is. 

It would be nice if bootstap throwed the error like:

Invalid customprovider [null] was given to bootstrap.

http://plnkr.co/edit/hNC0gNVVIM3tEHQ3YvMW?p=preview

**Comment by vicb** [comment]
obsolete
