### ISSUE TITLE
DehydratedException when using router.navigate method with forms.

### ISSUE THREAD

**Issue by bromzh** [angular/angular#7611]
In my component I want to navigate to another component via `router.navigate` method. I call this method into `onSubmit` event handler:
```ts
@Component({
    selector: 'login-form',
    directives: [FORM_DIRECTIVES],
    template: `
        <form (submit)="onSubmit($event)">
            <button type="submit">Submit</button>
        </form>
    `
})
export class LoginForm {
    constructor(private _router: Router) {}
    onSubmit($event: Event) {
        $event.preventDefault();
        this._router.navigate(['/Home']);
    }
}
```
Full code with bug: http://plnkr.co/edit/26JUMn?p=preview

Application change location, but I have error messages in console: 
```
VM432 angular2.dev.js:23083 EXCEPTION: Attempt to use a dehydrated detector: LoginForm_0 -> ngSubmit
```
Full stacktrace you may see in my plunker (in console).

But if I wraps `router.navigate` method call into timeout, error dissapears:
```js
setTimeout(() => {
    this._router.navigate(['/Home']);
}, 10);
```
Also, this bug don't reproduces with some another events. For example, if I replace <button> to <a> and bind my event handler to `onclick` event, navigation works fine:
```html
<form (submit)="onSubmit($event)"> <!-- now this didn't call -->
    <a href (click)="onSubmit($event)">Submit</a> <!-- some handler, but another event -->
</form>
````

My enviroment: Angular 2.0.0-beta.9 (TypeScript), Chrome 49.0.2623.87 (64-bit) on Kubuntu 15.10.

**Comment by zoechi** [comment]
dup of 6786 ?

**Comment by bromzh** [comment]
I checked on beta.16, problem is gone. Thanks!

**Comment by bikramhfs** [comment]
I had a same problem, I rose the event on (submit) and then redirect to another component.
I solved the issue with: instead of using form (submit), i handled with  (click) event handle.
Problem is solved. 
Please suggest, is this correct or not?
