### ISSUE TITLE
pipes not working on safari

### ISSUE THREAD

**Issue by asiacoll** [angular/angular#7612]
live example at "https://angular.io/docs/ts/latest/guide/pipes.html " not working on safari.

**Comment by zoechi** [comment]
dup of #3333 or #7396 ?

**Comment by wesleycho** [comment]
The fix would be in the Plunker template, just add `<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.en"></script>` to `index.html`.
