### ISSUE TITLE
angular_1_router compoenent $canActivate navigate to useAsDefault route

### ISSUE THREAD

**Issue by luisgarciaalanis** [angular/angular#7614]
Repro:

// App component
function(template) {
    App.component('application', {
        template: template,
        $routeConfig: [
            { path: '/login', name: 'Login', component: 'login', useAsDefault: true },
            { path: '/home', name: 'Home', component: 'home' },
        ]
      });

App.component('home', {
        template: template,
        controller: HomeController,
        $canActivate: function () { return false; }
    });

1) Type the URL of the home route example http://www.mySite.com/home
2) it does not activate as expected, however it stays there with a blank page.

EXPECTED: shouldn't it go to the default page? in this case ['Login']?

Maybe this is not a bug, but I can't find any place on the documentation to address this.

Only workaround is to inject $rootRouter into the function and route manually, however imagine if you have a site with 100 pages...

**Comment by brandonroberts** [comment]
This doesn't seem like a bug. You're going to the `/home` rout and you have $canActivate returning false, which will prevent the route from loading. If you go to `http://www.mySite.com` it should go to `/login` by default.

**Comment by vicb** [comment]
obsolete
