### ISSUE TITLE
bug(Router): [routerLink] is not displaying custom query params

### ISSUE THREAD

**Issue by greg-md** [angular/angular#7616]
For example I have a route `{path: '/heroes',   name: 'Heroes',     component: HeroesComponent}`

If I try to navigate via `router.navigate(['Heroes', {foo: 'foo'}])`, I will be redirected to `/heroes?foo=foo` which is ok.

If I try to set in template `[routerLink]="['Heroes', {foo: 'foo'}]"`, it will display only `/heroes` in href attribute, which is not ok.

Angular version: 2.0.0-beta.9

**Comment by choeller** [comment]
Furthermore when having a link that needs one path param, trying to pass additional query-parameters leads to invalid links like the following:
```
[routerLink]="['../TaskForm', {id: task.id, foo: 'foo', bar: 'bar'}]"
```
```
http://localhost:4200/#/tasks/edit/3;foo=foo;bar=bar
```

**Comment by brandonroberts** [comment]
@choeller those params are correct. Optional params for child routes are represented as matrix parameters (e.g. ;name=value). Only root level routes get the the ?name=value if they are optional.

@greg-md this should be fixed already: https://github.com/angular/angular/pull/7431

**Comment by choeller** [comment]
@brandonroberts oops,  my fault! Thanks for clarification!  To be honest I didn't know about matrix parameters. Interesting you can add optional parameters for each part of the URL...

**Comment by greg-md** [comment]
@brandonroberts It displays url without query string, but when you click, it redirects you to url with query string.

**Comment by brandonroberts** [comment]
@greg-md correct. Its been fixed to where it will display query string in the link before you click.

**Comment by nosachamos** [comment]
This issue has been made obsolete by the router v3, I believe we can close it.
