### ISSUE TITLE
Expose debug info for batarangle

### ISSUE THREAD

**Issue by tbosch** [angular/angular#7617]
For tooling, we need to expose more debug information.

- [ ] Expose RouteRegistry: 
    * Tools can't just rely on the annotations as applications can register routes during runtime as well.
    * E.g. expose the `RouteRegistry` token via `ng.probe.coreTokens['RouterRegistry']` so it can be read via `DebugElement.injector.get(...)`. Also, add getters to the `RouterRegistry` to read out the existing rules.
- [ ] Expose declaration parent element
    * needed as the parent element in the DOM might be different because of content projection
    * expose `DebugElement.declarationParent` which should return another `DebugElement`.
- [ ] Expose providers used to create the platform and application injector
    * needed to visualize the injector hierarchy.

**Comment by tbosch** [comment]
Needed for batarangle...

**Comment by vicb** [comment]
@tbosch can this one be closed now ?
