### ISSUE TITLE
 es6-shim peer dependency 0.33.3 throws; update to v.0.35.0

### ISSUE THREAD

**Issue by wardbell** [angular/angular#7618]
**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] support request 

The v.0.33.3 es6-shim (our current peer dependency) throws an error *in every documentation sample*!: 

>`Uncaught (in promise) TypeError: object is not a constructor(…) in undefined:1`

This may or may not be harmless ... the app keeps running in Chrome ... but it's obnoxious. 

Fortunately, it disappears after updating the shim to v.0.35.0 

I am updating the doc samples. But npm install complains  - `peer dep missing` - because we're looking for 0.33.3.  That complaint will go away when this is fixed.

**Comment by ericmartinezr** [comment]
@wardbell Patrick beat you to it https://github.com/angular/angular/issues/7601 

PS : Wouldn't be nice to drop 3 dependencies and add a new one? (See his workaround)

**Comment by wardbell** [comment]
Darn.  I looked too! The github search is terrible (more likely it is just me).  Well let's get-er-done.

And ... yes ... I'd like to have fewer of these to maintain. I've asked about it. Priorities I'm afraid.

Close as dup of #7601

**Comment by wardbell** [comment]
Reopening because this is a pre-release action item to be solved _either_ as recommended here _or_ as recommended in #7601

**Comment by gdi2290** [comment]
both are the same issue I just gave a workaround for others who find the issue

**Comment by mhevery** [comment]
@wardbell please provide a repro plunker.

**Comment by naomiblack** [comment]
It's an issue at npm install.

running `npm install` in `public/docs/_examples` yields an npm error at the moment

```
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package es6-shim@0.35.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer angular2@2.0.0-beta.9 wants es6-shim@^0.33.3

npm ERR! Please include the following file with any support request:
npm ERR!     E:\dev\ideablade\angular.io\public\docs\_examples\npm-debug.log

**Comment by mhevery** [comment]
Could we try this with the latest zones? (next beta release) and see if the issue goes away? At least it will be easier to track down. Ref: `Uncaught (in promise) TypeError: object is not a constructor(…) in undefined:1`

**Comment by wardbell** [comment]
Why don't we just update the peer dependency version fro `es6-shim`?  We need that shim regardless (so you told me).

**Comment by IgorMinar** [comment]
@wardbell the peerDep in angular is currently set to `^0.33.0`, so you should be free to use 0.35.0. If 0.33.0 is causing issues then we should upgrade and require `^0.35.0` but nothing should prevent you from upgrading your code to use 0.35.0 - which is what you've done already: https://github.com/angular/angular.io/commit/2929255bb46aa391fd6bd1e849cef49d9ba32e82

My understanding of the current situation is that:
- you are not blocked
- we should change angular's package.json to require `^0.35.0` of es6-shims

Is that correct?

**Comment by ReneVallecillo** [comment]
Main doc (https://angular.io/docs/ts/latest/quickstart.html) was changed to 0.35.0 but if I just follow the guide, I would not be able to run the app(It runs but i does not compile). So I guess I'll have to downgrade and keep ignoring the promise error.

**Comment by mhevery** [comment]
https://github.com/angular/angular/pull/7653

**Comment by rhbecker** [comment]
@IgorMinar 
The `^0.33.0` version constraint is **NOT** satisfied by `0.35.0`, as I believe you are suggesting.

If you review [npm's semver documentation for caret ranges](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004), you'll notice that pre-1.0.0 versions are handled as though the minor number is major. To confirm, you can also try out their [semver calculator](http://semver.npmjs.com/).

**Comment by wardbell** [comment]
Although @rhbecker  is correct, I think this is no longer an issue since we updated to v.0.35.0. We should be able to close this issue now.
