### ISSUE TITLE
angular2 will be kiiled by react in the future?

### ISSUE THREAD

**Issue by buuug7** [angular/angular#7621]
angular2 will be kiiled by react in the future?  
angular2 is very heavily for Agile Development ,so it will be killed by react,but the react will be killed by vue in the next year,this just my opinion.what about yours?

**Comment by otodockal** [comment]
This is not issue! It should be closed!

**Comment by buuug7** [comment]
i want to know what framework i need to learn ?react or angular?

**Comment by ridecrafty** [comment]
@buuug7 use coin to choice

**Comment by MacKentoch** [comment]
@buuug7 answer is so simple and obvious : 

### learn both!

Angular2 is the perfect illustration of `not limiting yourself to a framework or mindset`.
It offers the best from Angular JS and takes nices concepts from ReactJS and others.

**Comment by pkozlowski-opensource** [comment]
@buuug7 this type of discussion don't belong to GitHub. We want to keep GitHub issues for bug reports and future requests only, check:  https://github.com/angular/angular/blob/master/CONTRIBUTING.md. Thnx!

**Comment by buuug7** [comment]
@pkozlowski-opensource i know your means

**Comment by gnesher** [comment]
It's less about React and more about the odd choices the Angular 2 team made, forcing us to relay on the Angular CLI, Type Script, RxJS are all making the transition (and actual use) painful

**Comment by DzmitryShylovich** [comment]
> TypeScript, RxJS

the best part of angular :)

**Comment by NilsHolger** [comment]
@buuug7 learn all 3, that will only make you a better angular developer.
@pkozlowski-opensource absolutely right.
@gnesher are google and microsoft collaborating to take over the world? ;-)
@DzmitryShylovich the best part of angular is the pure JS google code in the source. we don't need ts and rxjs, we can kick them out, replace them quickly. everything and everybody is replaceable. :)

**Comment by gnesher** [comment]
@DzmitryShylovich the increase of external dependencies (that are not really covered by the Angular documentation nor are directly supported by Angular) is causing endless pain (also releasing a final version of Angular without a final version of the build tool was a little misleading as Angular 2 can not be used in production without AOT which is nearly impossible to run outside of the recommended Angular 2 CLI, which is still in Beta and died on us multiple times)

**Comment by DzmitryShylovich** [comment]
> can not be used in production without AOT which is nearly impossible to run outside of the recommended Angular 2 CLI

are you kidding? :) cli is absolutely an optional tool.

**Comment by gnesher** [comment]
@DzmitryShylovich I'm going to point out once again that your claim is misleading at best.

I'm not saying that it's not possible to run it outside the CLI, I am saying it's a hit / miss experience with no clear guidelines and not something I would generally consider "production ready".

I had a brief attempt at running this with rollup - https://github.com/steveblue/angular2-rollup/issues/10#issuecomment-270782472 (existing starter kit, works for the creator, doesn't work for me and a few other of the guys unless we lock to specific versions of typescript / angular).

Just to be clear this is a simple empty project just trying to get AOT running, when we try to run it on our big, dependency heavy project there's quite a few extra errors.

**Comment by steveblue** [comment]
@gnesher AOT is very strict. To compile with ngc all Typescript errors must be cleaned up and then theres possibly some additional errors due to the functional programming style AOT forces you into. This IMHO is not a bad thing. Now that a team is forced to adhere to guidelines their codebase remains consistent. Some of the coding practices you must follow to get AOT to compile are not well documented, at least it wasn't when I had to convert a large project over. It is possible.  

The dependency chain will be a problem no matter which framework you use.  If you don't lock down the versions then builds going out to production could be fraught with errors in any framework. 

@buuug7 Comparing React to Angular is like comparing apples and oranges. Both projects have different goals. For Enterprise Web Engineering I have to say Angular is hands down the best choice.

**Comment by gnesher** [comment]
@steveblue lets separate Typescript errors that you should fix regardless to functional programming style limitation which should either be enforced throughout Angular, or not. The fact that a perfectly compiled Angular codebase (with no errors) fails with AOT is a problem.

The fact there's very little documentation also makes this a rather big issue as this is not a minor feature, but a requirement to use Angular2 in production.

Finally unless I've missed something the idea behind the idea behind patch and minor versions in NPM is you should be able to upgrade safely. If AOT magic breaks that it's a little sad.

**Comment by DzmitryShylovich** [comment]
> The fact there's very little documentation also makes this a rather big issue as this is not a minor feature, but a requirement to use Angular2 in production.

it was true ~6 months ago. Now you have blog posts, github repos (for example, https://github.com/rangle/angular-2-aot-sandbox#current-status), tools (codelyzer, ide, language service) that help a lot. There're very few simple rules that you need to follow (don't use default exports, don't use arrows, everything you annotate for angular must be public). Never had any issues with aot.

**Comment by alxhub** [comment]
Hi all,

Locking this issue as there are better avenues for support for AOT, there is no clear bug or issue in Angular here, and the original issue goes against our [Code of Conduct](https://github.com/angular/code-of-conduct/blob/master/CODE_OF_CONDUCT.md).
