### ISSUE TITLE
Router.navigate() and RouterLink have inconsistent behavior

### ISSUE THREAD

**Issue by a2dude** [angular/angular#7623]
There appears to be a difference in behaviour between routerLink in html and router.navigate(...).
Using routerLink in html provides the expected behaviour when navigating between states. "navigate()" does not behave in the same way.

Using [routerLink]="['/AuthenticatedHome']" in the login panel correctly moves to the expected ui state.

However the following code
                this._router.navigate(['/AuthenticatedHome']); 
while it takes the app to the same ui state it causes the app to be reloaded.

- Angular version: 2.0.0-beta.9
- Browser: Chrome 49.0.2623.87 / Edge 
- Language: TypeScript 1.8.7

See github project to repro: [https://github.com/a2dude/route1]

**Comment by disposition68** [comment]
+1

I have a .net MVC application where I have run into a very similar issue. For me, the issue arises when trying to use router.navigate() within the child of an element that has a route config. The method seems to work fine for me in the parent element itself.

**Comment by a2dude** [comment]
As suggested on other related issues the following does appear to be a workaround which appears to only generate hideous exceptions the first time the code is exercised...

            setTimeout(() => {
                this._router.navigate(['/AuthenticatedHome']); 
            }, 10);

**Comment by laco0416** [comment]
dup of #6786 ?

**Comment by a2dude** [comment]
In the same area I agree but adds detail re the discrepancy between routerLink and navigate

**Comment by borttrob** [comment]
+1

I have the same problem with 2.0.0-beta.11

**Comment by borttrob** [comment]
5 minutes after commenting, I found the reason in my code (After spending half of the day on that problem). My code looked like

                <li [class.active]="todo.id == currentTodo.id"
                    (click)="setCurrentTodo(todo)"
                    *ngFor="#todo of todos">
                    <a href="">{{todo.id}}</a>
                </li>

It seems that the href part interfered with the programmatic routing but not with the the router-link directive. After removing href the code works as expected. Hope that helps.

**Comment by a2dude** [comment]
I have updated the code (See github project to repro: [https://github.com/a2dude/route1]) to beta 11.

The problem persists...

**Comment by mringrose** [comment]
I have the same problem with beta 11.  Using (click) on <a> with href="" causes app to reload.  Since I am using bootstrap I am using this button styled as a link for a workaround: 
<button class="btn btn-link" *ngIf="isLoggedIn" (click)="logout()">logout</button>

**Comment by naomiblack** [comment]
@a2dude  Could you please create a minimal example in plunkr that illustrates this? Your code is pretty large for us to sift through.
