### ISSUE TITLE
The callback ngAfterViewChecked() runs unpredictably 

### ISSUE THREAD

**Issue by yfain** [angular/angular#7629]
I'm having hard time understanding when the component lifecycle callback ngAfterViewChecked() runs. It seems that it runs more often than expected. Here's the plunk with three simple components: Parent, Child, and GrandChild: http://plnkr.co/edit/EHJs2KxzL3NtYCIHWWa4?p=preview

Each component prints a message from  its ngAfterViewChecked().  Run this app, and it prints messages from ngAfterViewChecked() total 11 times. **Why not 3 times?**

Add one character  to the Greeting value in the Parent and tab out of the field - it prints messages from ngAfterViewChecked() from Parent, Child, and Grandchild.  Even if you simply move the focus away from the field (without changes) to another application you'll see three messages from ngAfterViewChecked() on the console.

Add one character in the Message field in the Child, and you'll see 8 messages printed from ngAfterViewChecked() from Parent, Child, and GrandChild. **Why 8?**

Can anyone explain this behavior?
What's the practical use of the callback ngAfterViewChecked()?

Thanks

**Comment by robwormald** [comment]
The underlying issue here is to do with EventEmitter - there's a pending PR to fix it's behavior. See http://plnkr.co/edit/ffELnnGGL6gNq5wF21CN?p=preview for a demo that works more like you'd expect it to.

**Comment by gkalpak** [comment]
Could point to the mentioned PR ?
