### ISSUE TITLE
angular_1_router: double slash at the root when path is the root itself

### ISSUE THREAD

**Issue by Krisa** [angular/angular#7633]
Regarding the new Angular1 Router (for 1.5), there is an issue when defining the root component with a path like `path: '/...'` or `path: '...'`. I have taken the sample application to illustrate the issue:
http://plnkr.co/edit/FVZZwxAjlOmxQ8uA9YLF?p=preview

Click on "Heroes", and then hover over the list. You will see paths like `xxxxxx//10` instead of `xxxxxx/10`.

The only difference compared to the sample application is the line 20 in app.js.

**Comment by ericmartinezr** [comment]
This was supposed to be fixed in https://github.com/angular/angular/pull/6729 but I don't know if the fixes for ng2 router are valid for ng1 router too.

**Comment by btford** [comment]
I think @petebacondarwin just solved a similar issue specific to Angular 1. I expect #6729 to have fixed this, but Pete would know better than I.

**Comment by dibosh** [comment]
Is this going to be resolved some time soon? Or anyone going to give it a go? @btford

**Comment by petebacondarwin** [comment]
We are currently undergoing a review of the router design. This will significantly affect this router. I would wait for a week and there will be some more information about what will happen next.

**Comment by petebacondarwin** [comment]
So we have a new router, based a lot upon Observables. We are currently investigating how to backport this to Angular 1. Either way, the version of the router to which this issue refers is no longer maintained. So we will not be providing a fix.
