### ISSUE TITLE
bug(ngUpgrade): modules provided to resumeBootstrap do not affect downgraded ng2 directives

### ISSUE THREAD

**Issue by sjelin** [angular/angular#7635]
* **I'm submitting a ... **
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**

Currently `resumeBootstrap` causes ngUpgrade to crash, but pending #7603 it will work.  However, as @gkalpak [points out](https://github.com/angular/angular/pull/7603#discussion_r56125778), the current solution causes modules provided to `resumeBootstrap` not to reach downgraded ng2 directives.  There isn't a straightforward solution though, because if bootstrapping happens before the ng2 directives are downgraded then the app will crash, since the ng2 templates don't work in ng1.  Since there isn't a clear solution, I've decided to move forward with #7603 and document the problem here.

* **What is the expected behavior?**

Mock modules passed to `resumeBootstrap` should affect downgraded ng2 directives

**Comment by gkalpak** [comment]
Actually, I don't think the modules won't be available to downgraded components. It's just that `ng1compilePromise` will be undefined when passed to `Promise.all()`, which means that `ngUpgrade`'s `bootstrap()` method, could return a prematurely resolved promise.

That's off the top of my head, so take it with a grain of salt. Proper investigation is needed.

**Comment by sjelin** [comment]
Oh, that's what you're saying?  Never mind, I can fix that
