### ISSUE TITLE
求判断服务器两次推送过来的对象的某个属性是否不一样的优秀解决方案

### ISSUE THREAD

**Issue by maoguiyou** [angular/angular#7638]
项目需求：后台不断的推送赔率票数等数字过来，如果两次推送的数字不一样，需要该数字闪一下黄色，所以需要判断两次对象的具体属性是否一样，求较好的解决方案

**Comment by robwormald** [comment]
@maoguiyou the angular team does not speak Chinese, so we can't help you if we can't understand. Could you try in English, or give an example using https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5 ?

**Comment by lightningtgc** [comment]
@maoguiyou You should use Immutable data or Observables to reduce the change.

You can post your question on http://stackoverflow.com/

**Comment by kittencup** [comment]
666666

**Comment by pkozlowski-opensource** [comment]
Sounds like a general support question that should be asked using one of the support forums. Closing.

**Comment by ibufu** [comment]
2333333
