### ISSUE TITLE
Angular 2 inherited Input properties become undefined after a new own property

### ISSUE THREAD

**Issue by tamasfoldi** [angular/angular#7640]
**Note: for support questions, please use one of these channels:** https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
I report a bug

* **What is the current behavior?**
I have a class, which has 2 properties with @Input() annotation(or decorator). 
I extend it with a component and I can use it as I expect it, but if I define a property for my component the input values become undefined. 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
Here is my repo: https://github.com/tamasfoldi/TypewritingApp/commits/game If you run this in the console, you can see undefined logs. Waypoint's posx and posy are undefined but figure posx and posy are not, and if I remove the figurecomponent from the waypointcomponent the input values become correct again.

* **What is the expected behavior?**
It should not become undefined

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.7
- Browser: Chrome 49.0.2623.87 m
- Language: TypeScript 1.8.7

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Maybe it is a Typescript related issue, I dont know.

**Comment by tamasfoldi** [comment]
Maybe easier to see the problem here:
http://plnkr.co/edit/Jy4KFE55r0efLGwKzaTi?p=preview

**Comment by zoechi** [comment]
dup of #5415 ?

**Comment by tamasfoldi** [comment]
Think so

**Comment by vicb** [comment]
relates to #11606 

closing as duplicate
