### ISSUE TITLE
Having access to route config data outside the `RouterLink` directive

### ISSUE THREAD

**Issue by templth** [angular/angular#7641]
**Note: for support questions, please use one of these channels:** https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

I request a feature

* **What is the current behavior?**

I defined some roles within the `data` of the route config and I try to hide a routerLink if these roles aren't contained into the ones of the current user. For this, I need to get these data from an injected `RouterLink`. I can get them using private fields:

```
var routeConfigData = this.routerLink._navigationInstruction.component.routeData.data
```

 but I would like to have a public method providing this. Something like:

```
var routeConfigData = this.routerLink.getRouteConfigData();
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

See this https://plnkr.co/edit/zC56jp?p=preview

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.9
- Browser: Version 49.0.2623.87 (64-bit) but I think that it applies to all browsers
- Language: TypeScript 1.7.3

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

See this question as reference: http://stackoverflow.com/questions/36041192/angular2-how-to-hideno-render-the-link-in-the-menu-after-check-access

**Comment by brandonroberts** [comment]
Another option would be to provide your `secured` directive with the linkParams used in your routerLink. Then you could use the router to generate the instruction that contains the routeData without accessing private properties. 

https://plnkr.co/edit/9sKlXZ?p=preview

**Comment by templth** [comment]
Great idea @brandonroberts!

I would reuse the `routerLink` attribute:

```
export class Secured {
  @HostBinding('hidden')
  hideRouterLink:boolean;

  @Input('routerLink')
  routeParams:string;

  constructor(private router:Router) {
  }

  ngAfterViewInit() {
    var instruction = this.router.generate(this.routeParams);
    var data = instruction.component.routeData.data;
    this.hideRouterLink = this.shouldBeHidden(data);
  }

  (...)
}
```

Thanks very much for your help, Brandon!

**Comment by brandonroberts** [comment]
Even better :+1:

**Comment by templth** [comment]
I update the associated stackoverflow answer by quoting you for your great help: http://stackoverflow.com/questions/36041192/angular2-how-to-hideno-render-the-link-in-the-menu-after-check-access/36043628?noredirect=1#comment59742449_36043628! 

Thanks again!

**Comment by FarhodKurbonov** [comment]
This is good approach to resolve data from routeConfig. I was tried this approach with updated version of  "@angular/router": "3.0.0-beta.2", but unfortunately in new version of angular2 router there is not method this.router.generate(this.routeParams).  So could not generate instruction for retriveve data from routeConfig. Can you help for handle this issue?(Sorry for my bad English)

**Comment by zoechi** [comment]
https://angular.io/docs/ts/latest/api/router/index/Router-class.html#!#createUrlTree-anchor might do what you want (didn't fully dive into the problem discussed above)

**Comment by FarhodKurbonov** [comment]
@zoechi Main reason of generating instruction as I understand, retrieve data from that route. I saw createUrlTree but can not find how to retrive data that declared in RouterConfig. Later I will give demo link

**Comment by FarhodKurbonov** [comment]
As I say in this plunk show problem: [https://plnkr.co/edit/vvksROeIR8XPIMFMznRy?p=preview](url)

**Comment by zoechi** [comment]
Plunker that use https://npmcdn.com/ don't work for me. I don't know why.

> XMLHttpRequest cannot load https://npmcdn.com/@angular/platform-browser-dynamic@2.0.0-rc.4/bundles/platform-browser-dynamic.umd.js. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://run.plnkr.co' is therefore not allowed access.

**Comment by FarhodKurbonov** [comment]
@zoechi Yes, but after install Chrome's CORS plugin  https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?utm_source=chrome-app-launcher-info-dialog it work fine.

**Comment by ericmartinezr** [comment]
npmcdn was moved to unpkg, more here https://github.com/angular/angular.io/pull/2227

**Comment by Zasuk** [comment]
the solution provided by @templth and @brandonroberts don't work with the latest Router version...
any other solution for this?

**Comment by zoechi** [comment]
@Zasuk 
- https://angular.io/docs/ts/latest/api/router/index/ActivatedRoute-interface.html#!#routeConfig-anchor
- https://angular.io/docs/ts/latest/api/router/index/Router-class.html#!#config-anchor

**Comment by kaleemullah360** [comment]
is there a complete example of acl (Access Based Control) based routes and component restrictions in angular 2.
I searched but didn't found.

**Comment by FarhodKurbonov** [comment]
@kaleemullah360 You can use this gists. This is my final solution: https://gist.github.com/FarhodKurbonov/139cc0a7bc7d23e975a38a8afcd02826

**Comment by kaleemullah360** [comment]
Thanks @FarhodKurbonov I'll use this solution. :+1: :100:
