### ISSUE TITLE
angular_1_router: useAsDefault is not working as "expected" 

### ISSUE THREAD

**Issue by Krisa** [angular/angular#7643]
A bit like this issue https://github.com/angular/angular/issues/7614, but actually slightly different.

"We" (at least myself :) ) expect the `useAsDefault`to behave like the `otherwise` of `ngRoute` / `uiRouter`, meaning that when a route is not found, it's where it will default, but this only works when we are requesting the rootPath (i.e. `/`)

E.g. defining a rootComponent like following:
```js
[{
    path: '/login/...',
    name: 'BaseLogin',
    component: 'baseLogin',
    useAsDefault: true
}]
```

And trying to access `/wrongpath`will not redirect to `/login` but will display an empty page (the base component is loaded through the html tag, but not the `BaseLogin` one defined in the Router). And unless I have missed something, there is currently no (easy) way to solve this simple issue.

I would expect that when a route is not found, it navigates through the tree of components (as long as there is a `...`) and display the real "default" component - instead of staying on an empty page.

**Comment by brandonroberts** [comment]
Default routes like you said are for being able to use a child route as the default thats path isn't `/`. It allows you to have shorter routerLink arrays also if you have default routes. An `otherwise` route hook hasn't been implemented yet. See: https://github.com/angular/angular/issues/2965

Alternatively, you can use a wildcard route as an otherwise route for now.

```js
[{
    path: '/login/...',
    name: 'BaseLogin',
    component: 'baseLogin',
    useAsDefault: true
},{
    path: '/*otherwise',
    redirectTo: ['BaseLogin']
}]
```

**Comment by Krisa** [comment]
I was not aware of the wildcard option. Well, it's clearly an "otherwise" and works well, thank you!
