### ISSUE TITLE
set required attribute conditionally with ngIf and ngCtrl

### ISSUE THREAD

**Issue by micronyks** [angular/angular#7644]
Is there a way in `angular2` we can set `required` attribute conditionally, as used to do with `ngRequired` in `angular1`??

http://plnkr.co/edit/qOCGmiGjoswIiOXyc29D?p=preview

Look at the use case below,
```
<form [ngFormModel]="loginForm"    (submit)="doLogin($event)"> 

  <div *ngIf="show">  // if show is True, then I want name to be required else not required

    <input ngControl="name" type="text"  placeholder="Your name" #name="ngForm"  required>
    
     <div [hidden]="name.valid || name.pristine" class="alert alert-danger">
          Name is required
     </div>
     <br/>
        <div>Valid ={{name.valid}}</div>
        <div>Pristine ={{name.pristine}}</div>
        <div>Touch ={{name.touched}}</div>
    </div>
 ...
 ...
 ...
</form>
```

```
export class Login { 
    show:boolean:false;
    loginForm: ControlGroup;
    name:Control = new Control("", Validators.required);
  constructor(fb: FormBuilder) {
    this.loginForm = fb.group({
      name: this.name,
      password: ["", Validators.required]
    });
  }
   
}
```

**Comment by izll** [comment]
+1

**Comment by zoechi** [comment]
dup of #7393

**Comment by vicb** [comment]
can you use `[attr.required]=true/null` ?

**Comment by micronyks** [comment]
@vicb . I don't think I can't do it. How would ngCtrl come to know whether it is now required or not?

When `show`'s value becomes **false**, by providing some value to **password field** , **login button** should become enable but it is not happening.

**Comment by about-code** [comment]
@micronyks  Did you try something like

```html
<input ... [required]="myBoolVar ? myBoolVar : undefined"></input>
```
Worked for me lately (I'm on RC.5).

**Comment by kara** [comment]
Fixed by https://github.com/angular/angular/pull/11116.

**Comment by niaz-oployeelabs** [comment]
just use [required]="your angular expression" in input element. Works on latest angular 4.

**Comment by sujoydc** [comment]
Not working with latest angular version 4.3.3 for <select>. Is that a bug or for select we have to do it in a different way?

**Comment by niaz-oployeelabs** [comment]
try the latest stable 4.3.4. Didn't try in 4.3.3

**Comment by fopnet** [comment]
attention because the value can not be the raw true or false, it must to be a boolean string like 'true' or 'false' in order to work properly

**Comment by Prakruthee** [comment]
[required]="your angular expression" is not working for ng2-datepicker with latest angular version 4.3.3. Anybody have different solution

**Comment by sandangel** [comment]
@Prakruthee have you tried with angular v5 ?

**Comment by harmonikas996** [comment]
> just use [required]="your angular expression" in input element. Works on latest angular 4.

You saved me. Thanks a lot!
