### ISSUE TITLE
Using ngModel causes data binding to propagate to Parent Components

### ISSUE THREAD

**Issue by toweryb** [angular/angular#7645]
* **I'm submitting a ... **
[X] bug report

* **What is the current behavior?**

I create three components (Parent, Child, and Grandchild) where the Parent uses the Child as a directive and the Child uses the Grandchild as a directive.  I create an object (called “item”) with a key “name” in the parent object

`item = { name: 'item value' };`

 and pass it as a Component property to my Child component (one-way binding using [item])
`<child-comp [item]="item"></child-comp>`

 and the Child component passes the object to the Grandchild component (also using one-way binding).
`<grandchild-comp [item]="item"></grandchild-comp>`

On the Grandchild component, I add an input tag and add two-way binding using ngModel to the item.name property.
`<input type="text" [(ngModel)]="item.name" />`

When the value is changed in the input textbox, the value of item changes in the Grandchild component (which I expect), but it also changes in the Child and Parent components which I would not expect (as I am only using one-way binding).
![image](https://cloud.githubusercontent.com/assets/17903836/13848439/3beba438-ec28-11e5-8a1c-4e016141c879.png)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 
Here is a Plnkr example of the issue - [https://plnkr.co/edit/T3RgJTrUuDztkZUO6N0O?p=preview]
* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.9
- Browser: [Chrome 48 | IE 11]
- Language: [TypeScript]

**Comment by benneq** [comment]
This is intended behavior. You're passing the **reference** one-way. This means, that changes to the reference won't propagate to the parent. But the object behind the reference is still mutable!

You have (at least 3 options):
1. use immutable data structures (see for example immutable.js)
2. copy the whole object and pass a copy to: `[item]=createCopyOf(item)`
3. use only single values instead of objects: `[name]=item.name [foo]=item.foo ...`

... Or 4.: you simply deal with the mutability of objects.

**Comment by pkozlowski-opensource** [comment]
Sounds like a support question that got resolved. Thnx @benneq

**Comment by zalshabab** [comment]
I have the opposite problem. I am actually trying to reflect the model value through all the layers ( parent ->child -> grand Child) but i couldn't.. 
I created a  textbox component  <input type="text" [(ngModel)]="value" />.
and a addressInfo component which uses the textBox component. I added a two ways binding property. [(address)] to the addressInfo component to hold the model value.
and created bankDetails component which uses addressInfo component. now when i add [(address)] to <addressInfo> the value of the model doesnt get reflected to its model . even though i can see that [(address)} on addressInfo component and ngModel at textBox component hold the correct value 

Can you please help?
