### ISSUE TITLE
Filesize too big for mobile

### ISSUE THREAD

**Issue by DavidValin** [angular/angular#7646]
Hello.

Loving Angular 2 but I saw a 566kb filesize, is that correct? I can imagine that I will end up with 1MB js only easily.

I'm wondering will it be possible to include more like tiny libraries in a way that we exclude unused code, it seems too much javascript upfront with no application specific code. Is these 566kb totally needed to use Angular components? We need to have fast downloadable mobile apps

Cheers

**Comment by BojDom** [comment]
Angular release candidate will wight less , not much more, and there will be the minified version which i tink ti will weigth like 150kb.... by the way 500kb is like 2 images, and if you use cdn you can't be worry about the downloading time since it caches the files in the browser

**Comment by DavidValin** [comment]
150kb sounds very different! Hopefully the final application won't exceed 250kb.

Thanks
