### ISSUE TITLE
Provide a createTestComponentBuilder to instantiate TestComponentBuilder outside inject

### ISSUE THREAD

**Issue by vikerman** [angular/angular#7648]
I am looking at ways we can reduce the number of things for which we use inject so as to decrease boiler plate.

One common pattern in tests is this

```
beforeEach(inject([TestComponentBuilder], function(tcb: TestComponentBuilder) {
      builder = tcb;
    }));
```

I don't think we gain much by instantiating the TestComponentBuilder through injection. It would be easier if we just had a createTestComponentBuilder() factory method to create a TestComponentBuilder. With this it would just be

```
beforeEach(() => { builder = createTestComponentBuilder(); });
```

**Comment by juliemr** [comment]
To clarify - we need to use injection to create the TCB, but we could do this with a helper function.

**Comment by juliemr** [comment]
I think we've decided to move a different direction, @vikerman any problem closing this?
