### ISSUE TITLE
@ContentChild not working as expected and undefined

### ISSUE THREAD

**Issue by asotog** [angular/angular#7649]
Hi,
Trying to get a child component from a parent component found that ContentChild decoration not working as documentation describes, looks like an issue to me.
I have this 
```
<squeezebox>
    <sb-item  *ngFor="#item of itemsList">
        <sb-item-head>{{item.title}}</sb-item-head>
        <sb-item-body>{{item.description}}</sb-item-body>
    </sb-item>
</squeezebox>
```
It renders fine, there are 4 components types, so im trying to get sb-item-body component from sb-item with @ContentChild but is returning nothing:
```
import {Component, ContentChild, AfterContentInit} from 'angular2/core';
import {NgClass} from 'angular2/common';
import {SBItemBody} from './squeezebox';

@Component({
    selector: 'sb-item',
    template: `
        <div class="sb-item" [ngClass]="{'is-collapsed': collapsed}">
            <ng-content></ng-content>
        </div>
    `,
    directives: [NgClass]
})
export class SBItem {
    
    private collapsed: boolean = true;
    
    @ContentChild(SBItemBody) body: SBItemBody;

    constructor() {}

    toggle(collapsed: boolean) {
        this.collapsed = collapsed;
        this.body.toggle(collapsed);
    }

    ngAfterContentInit() {
        console.info(this.body);
    }
}
```
Thanks in advance,

**Comment by ericmartinezr** [comment]
@asotog I can't reproduce your issue. See this [plnkr](http://plnkr.co/edit/EjQ8ifk4kJoOg3OWeRlH?p=preview), update it to reproduce your case.

**Comment by asotog** [comment]
mm interesting only difference i see, im building locally with npm packages same versions looks like:

```
"dependencies": {
    "angular2": "^2.0.0-beta.9",
    "es6-promise": "^3.0.2",
    "es6-shim": "^0.35.0",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.2",
    "systemjs": "^0.19.22",
    "zone.js": "^0.6.4"
  },
  "devDependencies": {
    "concurrently": "^2.0.0",
    "lite-server": "^2.1.0",
    "typescript": "^1.8.7"
  }
```

will give it more shot later tonight to try to find something

**Comment by asotog** [comment]
I was able to reproduce it, just put each component in separate files, and log started printing undefined http://plnkr.co/edit/oYUXKo?p=preview , on my local happens the same only difference im building from node modules the angular typescripts

**Comment by ericmartinezr** [comment]
@asotog 

it works fine if you write the correct path

**squezeebox.ts**
```
//import {SBItem} from './squeezbox'; // wrong!!
import {SBitem} from './sb-item'; // Correct!!
```

**sb-item.ts**"
```
//import {SBItemBody} from './squeezbox'; // wrong!!
import {SBItemBody} from './sb-item-body';// Correct!!
```

Here's the plnkr working http://plnkr.co/edit/8diqAk?p=preview

**Comment by asotog** [comment]
awesome thanks man, mm i think this ticket is closable, that is more related to typescript, i still think is an issue, code is just importing squeezebox which exports the other modules working as an index kind file
