### ISSUE TITLE
Add "no binding errors" mode

### ISSUE THREAD

**Issue by wardbell** [angular/angular#7651]
**I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] support request
- **Do you want to request a _feature_ or report a _bug_?**

Feature
- **What is the current behavior?**

App fails to render and crashes when a data-binding fails (e.g, when `hero` is null or misspelled in `hero.firstName`. There is no way to trap and handle. Doing so at app level loses context. There's a constant danger of application failure which may not be necessary.

Yes, I could use the elvis operator. But forcing devs to write elvis for thousands of bindings on hundreds of screens is an unfair burden. There is no way to search for missing elvis. It's a mine waiting for someone to step on it.

Yes I could try to look for these with e2e tests. Good luck with that. Particularly difficult when `NgIf` is usually guarding the fort and the `true` state is both rare and difficult to produce. 

I'm speaking from deep experience. Other platforms are more forgiving (I'm reminded of Silverlight but also Angular 1 and KnockOut, and _insert-framework-here_.
- **What is the expected behavior?**

When `bindingErrors('ignore')` , Angular short-circuits the binding exactly as it would if I bound to `hero` or `hero?.firstName` ... it presents a blank space.

When `bindingErrors('console')` it writes an error to console but does not throw.

`bindingErrors('throw)` is the default behavior we know today.
- **What is the motivation / use case for changing the behavior?**

See above.
- **Please tell us about your environment:**

All environments Angular version: 2.0.0-beta

**Comment by johnpapa** [comment]
This would be superbly helpful when debugging as binding errors are super common.

**Comment by DanWahlin** [comment]
Agreed. Ran into several issues where my binding wasn't really an error per se (object just hadn't loaded yet). Easily fixed with ? or through other means, but it'd definitely be nice to have an ignore or console option initially.

**Comment by areai51** [comment]
I too agree that we need to be forgiving with binding errors but, I would be quite happy with binding errors just written to the console in dev mode which gets disabled on production. 
Not sure how much lines of code and bytes it would save at the framework level... but keeping it simple is always nice.

**Comment by mhevery** [comment]
This would have a negative perf impact since we would have to wrap each binding in a try catch. 

There are two choices:

1) Silence the errors, but then run a risk of incorrect binding making into production. (negative perf impact due to try catch)
2) Fail early (as we do now)

It is not a clear cut choice for me, so I think we should collect more data before we go against performance.

**Comment by DanWahlin** [comment]
Could the try/catch you mention only be enabled in specific scenarios - for "ignore" or "console" mode for example? That adds additional logic per binding so I'm not sure what the performance impact would be in that case.

**Comment by wardbell** [comment]
If forced to choose between performance and app failure ... I don't know a user or business owner who would ever prefer failure.

Maybe there is something to Dan's conjecture that a perf switch would erase the try/catch so that those (few) who prefer crashing can have their wish.

There is a tension between safety and performance ... and different audiences may choose differently. I'm long-time friends with the safety crowd. Maybe I need new friends.

**Comment by jtraband** [comment]
I have an actual use case for this.  Currently working on an Angular2 app for a paying customer that has over a hundred components with many bindings per component.  Currently, I have no way of insuring that every combination of ngIf along with any bindings internal to it are actually safe i.e will not kill the entire app.  I am working with a legacy database with a great deal of inconsistent data.  Even if I use the elvis operator consistently, ( and I may have missed a few places) I still occasionally run into  issues with bad bindings occurring as a result of unexpected ngIf combinatorics.  Right now, I am very worried that the app will crash on some unexpected data and I have no easy way of stopping this from occurring.  Testing for all the possible combinatorics is simply not feasible.  I would gladly trade an occasional binding failure for an occasional application failure any day.   As applications get larger this is likely to become even more common.  To me not being able to trap an entire, (pretty common) family of errors seems to be a real oversight.  

As for the perf impact, I don't believe that it will be noticeable in the vast majority of cases, and where it is I imagine that having the ability to turn off error checking for these specific components would be a sufficient solution.

**Comment by mhevery** [comment]
@jtraband OK, I can see that point of view. I think it is something we may explore as on option. (unlikely to become the default behavior.)

**Comment by jtraband** [comment]
@mhevery thanks for considering it.  I don't need it to be the default. Just some mechanism for trapping and handling binding errors.

**Comment by wardbell** [comment]
I like the current default!

Just looking for an escape plan when I'm trapped in Jay Traband's world ... as so many of us are.

**Comment by wardbell** [comment]
I also don't think we need try/catch. Functional programming and the `Maybe` monad to the rescue, right?

**Comment by wardbell** [comment]
In case I was less than clear, I'm suggesting that we may not need any try/catch to give us this feature. Particularly if we can easily/performantly detect bad bindings without throwing.

Clearly Elvis is doing that work to a degree. We don't get errors today when binging to a null `hero`, but rather only when binding to `hero.name` when `hero` is null. These examples suggest that the framework is in a position to forecast failure before encountering it. 

I'd be satisfied with a compromise approach that intercepted easily detected failures at the expense of throwing when detection is hard/impossible.

Opinions?

**Comment by DanWahlin** [comment]
I agree - I'm not stuck to any particular way of dealing with it. I just hit this issue again yesterday with a project and wished there was an alternate way to handle those types of errors (such as you've proposed above). 

Things like this are always easier said than done I realize, but if it's something that's possible I'm all for it as a configurable alternative to the current default.

**Comment by mhevery** [comment]
Sure we could auto insert the elvis operator everywhere. (This does have a pref impact) which would make it into AngularJS v1 kind of mode. 

(again, I think this is post RC)

**Comment by pkozlowski-opensource** [comment]
I think that the several things have happened over the years:
* "Elvis" made it to ES/TS becoming "standard";
* errors with ivy got much better (although not perfect).

At this point it is not clear to me what are the next steps here? Would would people expect given the several-years experience working with the current system?

**Comment by mgechev** [comment]
It definitely could be challenging to ensure consistency with the shape of the business model, especially in a mature system with a lot of data migrations. I see the process of detecting a bug in an app on several levels (from better to worst):

1. Writing a bug-free program. That's ideal but unrealistic.
1. Catching a bug in your IDE/text editor, thanks to your tooling's language service.
1. Detecting a bug at build-time, thanks to compile-time type checking, or other static checks.
1. Finding a bug at runtime while developing the application.
1. Catching a bug in production, thanks to an error reporting system (Sentry, Rollbar, etc.)

In case we don't throw when there's an invalid binding in an application, the bug can remain undiscovered for a long time, and finding it could be hard.

In Angular, we're working towards allowing developers to catch bugs as early as possible. That's the reason we're using TypeScript instead of recommending JavaScript by default, that's the reason we're investing in compile-time type checking in templates, building the Angular language service, etc. Adding a "no binding errors" mode will be a step against this direction.
