### ISSUE TITLE
TypeError: Cannot read property 'zone' of null (touch)

### ISSUE THREAD

**Issue by CaptainCodeman** [angular/angular#7652]
* **I'm submitting a ... **
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
See above

* **What is the current behavior?**
Touch events now function (see: https://github.com/angular/angular/issues/6993) but also output a number of exceptions:
`Uncaught TypeError: Cannot read property 'zone' of null`

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
See http://plnkr.co/edit/53gbav4XuvWrDt6oEiYO?p=preview
Swipe left on title with console open

* **What is the expected behavior?**
touch function is called without exceptions

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.10
- Browser: [Chrome 48 ]
- Language: [TypeScript]

**Comment by biiiipy** [comment]
I got a similar error after updating to beta10, app won't bootstrap: ```angular2-polyfills.js:142 Uncaught TypeError: Cannot read property 'zone' of undefined```. Here's the line 142 from angular2-polyfills: ```task.zone.cancelTask(task);```

**Comment by gdi2290** [comment]
@biiiipy as a workaround add this to your typings.json and typings install
typings.json
```json
{
  "dependencies": {
    "zone.js": "github:gdi2290/typed-zone.js/lib/zone.d.ts#225aa313388bdf78b18ed9f0b29f93a395146229"
  },
  "devDependencies": {},
  "ambientDependencies": {
  }
}
```

**Comment by msklvsk** [comment]
@gdi2290, can a typing fix runtime error? Still having same exception.

**Comment by pitops** [comment]
tried this, having same problem, @gdi2290 your fix does not seem to fix the issue.

**Comment by CaptainCodeman** [comment]
It happens with the pre-built packages in the plunkr so I don't think typings are going to have any effect one way or the other.

**Comment by xbtequila** [comment]
Got the same exception when using websockets/socket.io.

**Comment by chrisnicola** [comment]
Getting similar error using Ionic 2 beta 3 with Angular 2 beta 11:

```
browser_adapter.js:76 Error: Uncaught (in promise): TypeError: Cannot read property 'zone' of undefined
    at resolvePromise (angular2-polyfills.js:534)
    at angular2-polyfills.js:570
    at ZoneDelegate.invokeTask (angular2-polyfills.js:355)
    at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (ng_zone_impl.js:35)
    at ZoneDelegate.invokeTask (angular2-polyfills.js:354)
    at Zone.runTask (angular2-polyfills.js:254)
    at drainMicroTaskQueue (angular2-polyfills.js:473)
    at XMLHttpRequest.ZoneTask.invoke (angular2-polyfills.js:425)
```

**Comment by CaptainCodeman** [comment]
Same here - beta-11 now gives a similar error in more places and stops the app functioning:

`TypeError: Cannot read property 'zone' of undefined`

**Comment by todoubaba** [comment]
Same here, stacktrace:
```
Uncaught TypeError: Cannot read property 'zone' of null
(anonymous function) @ browser_platform_location.ts:58
clearTimeout @ VM9380:3
n @ tether.min.js:1
```

**Comment by ganeshkbhat** [comment]
downgrading to beta 9 resolves the issue. not related to typings. Error pointing to source:

```
var clearNative = utils_1.patchMethod(window, cancelName, function () { return function (self, args) {
	        var task = args[0];
	        task.zone.cancelTask(task); **<<<<===**
 }; });
```

**Comment by manekinekko** [comment]
I think that this issue is somehow related to browsersync. Because when using the Angular 2 CLI, everything works fine.

![image](https://cloud.githubusercontent.com/assets/1699357/13899846/04e36dbe-edf8-11e5-9d92-d444868925bd.png)

**Comment by johnpapa** [comment]
i confirmed what @manekinekko sees. it works fine with live-server, but not with lite-server (which uses browser-sync).

here is what i get with bs

![image](https://cloud.githubusercontent.com/assets/1202528/13900102/c5b601c4-edd4-11e5-9e52-daeee0810dff.png)

**Comment by caninojories** [comment]
im getting same error just using node server to serve a SPA
<img width="770" alt="screen shot 2016-03-20 at 1 43 03 am" src="https://cloud.githubusercontent.com/assets/6065240/13900267/4d44dbca-ee3d-11e5-9265-3dbfdb8de688.png">

**Comment by zewa666** [comment]
Oh man, each update a new challenge :unamused:

in the meantime surrounding the mentioned section with an if clause checking for whether the task is defined fixes the problem temporary

**Comment by architruc** [comment]
I'm getting the same issue with [systemjs-hot-reloader](https://github.com/capaj/systemjs-hot-reloader) (the error goes away when disabling hot reloading). As far as I know, it is not using BrowserSync, but also provides hot reloading. In case it can help to point the cause.

**Comment by panjiesw** [comment]
Might be useful for those who want to use 2.0.0-beta.11

I am using [live-server](https://www.npmjs.com/package/live-server) instead of lite-server/browser-sync for now, until this is resolved. It works well with similar watch files and reload, just like lite-server.

**Comment by belevtsev** [comment]
For me [live-server](https://www.npmjs.com/package/live-server) doesn't work. in 2.0.0-beta.11

**Comment by johnpapa** [comment]
The angular team is aware of the issue and are working on a fix. Keep the reports coming as more and new information is helpful in diagnosing it.

For now, you can either use your server of choice with beta 11 and you may see the error in the console or go back to beta 9. I am using beta 11 for now as the error msg doesnt appear to cause any problems with my app at this time.

**Comment by todoubaba** [comment]
Seems https://github.com/angular/zone.js/commit/5783663a80926b6154d5c900a3a5645be7bd53bb fixed this. Temp workaround is patching angular2-polyfills.js the with:

```javascript
	    var clearNative = utils_1.patchMethod(window, cancelName, function (delegate) { return function (self, args) {
	        var task = args[0];
	        if (task && typeof task.type == 'string') {
                task.zone.cancelTask(task);
            } else {
                delegate.apply(window, args);
            }
	    }; });
```

**Comment by gdi2290** [comment]
here's the workaround if you build from source
https://github.com/AngularClass/angular2-webpack-starter/commit/1661e4ce847f90547e7bc875c57e8ebdfb3fef98

**Comment by sethflowers** [comment]
+1

**Comment by andycwk** [comment]
I'm having the same issue, but I'm not running any form of live reload software, think that's just a red herring or linked to how browsersync is doing it's thing!

In my case I'm trying to boot intercom.js, I also tried using zone.runOutsideAngular() in an attempt to resolve!

The error appears in the console as Intercom drops it's UI overlay on the screen.

`
    constructor(
        private userService: UserService,
        private router: Router) {
        this.userService.profile$.subscribe(profile => profile ? this.boot(profile) : this.shutdown());
        this.router.subscribe(_ => window.Intercom('update'));
        });
    }

    private boot(profile: UserProfile) {
            window.Intercom('boot', {
                app_id: "xxxxx",
                user_id: profile.userId,
                name: profile.fullName(),
                email: profile.emailAddress
            });
    }`

**Comment by asotog** [comment]
same here, updated to latest beta release and getting the same error, im building from npm modules,
`angular2-polyfills.js:142 Uncaught TypeError: Cannot read property 'zone' of undefined`

when getting back to beta 9, it disappears

**Comment by ericmdantas** [comment]
Got this problem when using `socket.io`.

**Comment by JasnaMRB** [comment]
Switching from lite-server to [https://github.com/AveVlad/gulp-connect](url) with livereload, I no longer get an error.

**Comment by ericmdantas** [comment]
I think it all comes down to `socket.io-client`, since I don't use any `server-reloading-module` that depends on `browser-sync` and I've got the same problem.

**Comment by otabekgb** [comment]
I am getting the same error while running/debugging from Visual studio

**Comment by MaxGeissel** [comment]
Same here with socket.io. Any ideas?

**Comment by johnpapa** [comment]
This issue has also affected `lite-server` and its ability to refresh the browser using BrowserSync with sockets. https://github.com/johnpapa/lite-server/issues/56#issuecomment-199888554

I recommend staying on beta 9 if you need this feature until this is resolved

cc // @naomiblack @wardbell

**Comment by CaptainCodeman** [comment]
I think the issue of browser syncing while developing is just a symptom - something that happens to trigger the issue.

It still also happens with a production build for me.

**Comment by johnpapa** [comment]
yes, the issue is with the new version of zones and the team is working on a fix.

**Comment by CarlosAmaral** [comment]
Even with BrowserSync, it takes forever to recompile if you have made a couple of changes. Might be due to my computer's specs.

**Comment by johnpapa** [comment]
recompiles may be slow on TypeScript 1.7. There was a bug with it. Go to 1.8.x

**Comment by CarlosAmaral** [comment]
@johnpapa It's 10x faster. Thanks!

**Comment by amcdnl** [comment]
@CarlosAmaral  i switched off of browsersync this week to nginx to fight some of these perf related issues.

**Comment by shakyShane** [comment]
Browsersync author here, please see my comment:

https://github.com/angular/angular/issues/7705#issuecomment-200019429

The issue lies with how socket.io is calling clearTimeout - something the zone.js will be intercepting

**Comment by Yagger** [comment]
Weird fact. I changed lite-server to live-server and the error is gone. Besides, with lite-server updates on the app did not cause page refresh, with live-server page refreshes automatically.

**Comment by vsDizzy** [comment]
Including "angular2-polyfills.min.js" breaks browser-sync, so the page could not be auto-reloaded.

**Comment by CarlosAmaral** [comment]
@Yagger `npm run lite` ?

**Comment by otabekgb** [comment]
Does anybody know if this issue resolve on beta.12?

**Comment by ericmdantas** [comment]
There's no mention to it.

I created a `live-reloading-server-module-thing` that doesn't depend on `socket.io`, so it's working just fine. For those interested, feel free to [check it out](https://github.com/ericmdantas/aliv).

**Comment by meriturva** [comment]
I checked right now on our main project and it seems to be resolved with beta.12.

**Comment by tiagoroldao** [comment]
I believe this was a fix on zone.js, which is why you wouldn't see it in the changelog: https://github.com/angular/zone.js/issues/276

**Comment by ericmdantas** [comment]
Zone doesn't seem to have a changelog, though :disappointed:

**Comment by aboudard** [comment]
I just reset my npm install with beta 12 and dependencies, and it works all good !

**Comment by asrullat** [comment]
i can confirm that - i had that issue when i was using ng2 beta 11 with browsersync. now everything works fine. big thx

**Comment by CaptainCodeman** [comment]
beta-12 seems to be running well for me :thumbsup:

**Comment by qheolet** [comment]
Update to Beta 12 and the Zone.js to 0.6.6

**Comment by cpiock** [comment]
Updated to Beta 12 and the Zone.js to 0.6.6. works with lite-server but not with iis express and visual studio. 
![image](https://cloud.githubusercontent.com/assets/5016620/14122349/bf2f5aec-f5fb-11e5-955b-b153ab08c2bf.png)

**Comment by meriturva** [comment]
@cpiock this is not related to ....'zone' of null! i guess your problem is something on path/filesystem!

**Comment by yoava** [comment]
Still happens for me, when running a compiled app on a simple node server, using `angular2@2.0.0-beta.10` to `beta.13` + `zone.js@0.6.6`. Works fine with `angular2@2.0.0-beta.9` + `zone.js@0.6.6`.

Getting `Uncaught TypeError: Cannot read property 'fork' of undefined` on **ng_zone_impl.js** (source map) here:

```
var NgZoneImpl = (function () {
    function NgZoneImpl(_a) {
        var trace = _a.trace, onEnter = _a.onEnter, onLeave = _a.onLeave, setMicrotask = _a.setMicrotask, setMacrotask = _a.setMacrotask, onError = _a.onError;
        this.name = 'angular';
        this.properties = { 'isAngularZone': true };
        this.onEnter = onEnter;
        this.onLeave = onLeave;
        this.setMicrotask = setMicrotask;
        this.setMacrotask = setMacrotask;
        this.onError = onError;
        if (lang_1.global.Zone) {
            this.outer = this.inner = Zone.current;
            if (Zone['wtfZoneSpec']) {
                this.inner = this.inner.fork(Zone['wtfZoneSpec']);
            }
            if (trace) {
                this.inner = this.inner.fork(Zone['longStackTraceZoneSpec']); // <== FAILS HERE (inner and outer are undefined)
            }
```

**Comment by micaelmbagira** [comment]
+1 Also still happens to me with beta.14 (https://github.com/angular/angular/issues/7747) but it doesn't on beta.9. I managed to workaround by importing `angular2-polyfills` but I don't like this hack.
