### ISSUE TITLE
Breaking change missing from Changelog, View gone in Beta 10?

### ISSUE THREAD

**Issue by Ristaaf** [angular/angular#7658]
[X] bug report

In Beta 9, View works as always but in Beta 10 I get:
error TS2305: Module '"<my local path>/node_modules/angular2/core"' has no exported member 'View'.

This seems to me to be a breaking change, but nothing is mentioned in the changelog.

**Comment by Zuzon** [comment]
@View is obsolete,  use @Component

**Comment by Ristaaf** [comment]
Yes I know, but I would have thought that when it finally goes away (which it has now) it should be noted as a breaking change in the changelog. It is actually not even noted anywhere in the changelog that it is obsolete!

**Comment by micronyks** [comment]
@Ristaaf you have got a valid point. it should be mentioned in breaking change section ! I don't use @view but still it should be mentioned as you said.

**Comment by Ristaaf** [comment]
Since #7707 is fixed now in 1f7449ccf458d49137b85074f16da8bbe392c178, which fixes this issue too, I am closing this to help with the backlog cleanup.
