### ISSUE TITLE
broken links in API docs

### ISSUE THREAD

**Issue by naomiblack** [angular/angular#7661]
The link checker reports the following broken errors originating from the API docs. @tbosch any impact on your work if I make these changes in the doc sections of the API? 

**Bad links**
- [ ] https://angular.io/docs/ts/latest/api/core/angular2/lifecycle_hooks
- [ ] https://angular.io/docs/ts/latest/api/router/Router/RouteRecognizer
- [ ] https://angular.io/docs/ts/latest/api/common/NgLocalization-class.html
- [ ] https://github.com/angular/angular/tree/2.0.0-beta.9/modules/angular2/src/common/directives/ng_plural.ts#L15-L17
- [ ] https://github.com/angular/angular/tree/2.0.0-beta.9/modules/angular2/src/common/directives/ng_plural.ts#L82-L146
- [ ] https://angular.io/docs/ts/latest/api/core/angular2/di/OpaqueToken

**From the following API docs files**
- https://angular.io/docs/ts/latest/api/core/DirectiveMetadata-class.html
- https://angular.io/docs/ts/latest/api/router/ComponentInstruction-interface.html
- https://angular.io/docs/ts/latest/api/core/ComponentMetadata-class.html
- https://angular.io/docs/ts/latest/api/common/NgLocalization-class.html
- https://angular.io/docs/ts/latest/api/common/NgPlural-directive.html
- https://angular.io/docs/ts/latest/api/common/NgPluralCase-directive.html
- https://angular.io/docs/ts/latest/api/core/Component-decorator.html
- https://angular.io/docs/ts/latest/api/core/Directive-decorator.html
- https://angular.io/docs/ts/latest/api/core/APP_COMPONENT-let.html
- https://angular.io/docs/ts/latest/api/core/bind-function.html

**Comment by tbosch** [comment]
@naomiblack They are fine

**Comment by steven-fernandez** [comment]
Not fine from here. They are indeed broken

**Comment by naomiblack** [comment]
@steven-fernandez indeed. Tobias was answering the question about impact on other work in flight... I'm working on getting these fixed. :)

**Comment by kutyel** [comment]
@mhevery should this be closed when commit ecb9bb9 was merged? :wink:

**Comment by IgorMinar** [comment]
obsolete
