### ISSUE TITLE
Installing Angular 2 adds spurious dependecies to my package.json

### ISSUE THREAD

**Issue by keirlawson** [angular/angular#7662]
Using npm 2.14.20, running `npm install --save angular2` results in `es6-promise` and `es6-shim` being added to my package.json dependecies block.  As I am using babel (with runtime/polyfill) I do not require these, nor should they be required by those targeting ES6 complaint browsers.  Removing manually from my package.json and then running a fresh `npm install` results in:

```
npm ERR! Linux 4.2.0-27-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "i"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package reflect-metadata@0.1.3 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer angular2@2.0.0-beta.10 wants reflect-metadata@0.1.2
```

**Comment by CaptainCodeman** [comment]
I agree. I've never understood why so many things get added. I stripped most of them out and now just have:

```
"angular2": "2.0.0-beta.10",
"rxjs": "5.0.0-beta.2"
```

(plus whatever the build and app uses of course)

Things like zone.js and reflect-metadata are already built into angular2-polyfills - so why do we need the source for Angular's dependencies added to the project? IMO it makes the quickstart look slightly more complex and daunting than it really needs to for someone new to Angular 2.

**Comment by therealaldo** [comment]
Same issue here

**Comment by keirlawson** [comment]
So according to https://angular.io/docs/ts/latest/guide/npm-packages.html these are to eventually be made `optionalPeerDependencies`, however according to https://github.com/npm/npm/issues/3066 `optionalPeerDependencies` are not going to be a thing.  I would argue that Angular2's use of peer dependencies doesn't really tie in with the intention of peer dependencies by my reading, namely to specify an API you are meant to work with (polyfill versions presumably don't represent API changes, just implementation changes of the constant ES6 API).  The way angular is doing it currently seems unprecedented/out of keeping with the way others are using this feature.

**Comment by wesleycho** [comment]
Angular 2's polyfills are no longer a thing.

Even if es6-shim isn't being used, it is listed as a peer dependency of reflect-metadata, so it would have to be removed from peer dependencies there if it is to be removed.

One should also upgrade to npm 3 if one wants to avoid installing peer dependencies automatically.

**Comment by pkozlowski-opensource** [comment]
> Using npm 2.14.20, running npm install --save angular2 results in es6-promise and es6-shim being added to my package.json dependecies block

This is no longer the case, check https://github.com/angular/core-builds/blob/master/package.json
