### ISSUE TITLE
Dynamic Form Value Binding

### ISSUE THREAD

**Issue by DanielYKPan** [angular/angular#7669]
In the Cookbook dynamic form tutorial, there may be some issues about form binding.
I tried this: if the new TextboxQuestion({}) does not set the required property to true, the value could not be shown in the form field.

**Comment by zoechi** [comment]
Docs issues are maintained in https://github.com/angular/angular.io.
I tried with the live example from https://angular.io/docs/ts/latest/cookbook/dynamic-form.html but couldn't reproduce. Could you explain in more details what you tried, what the expected and actual behavior is?

**Comment by DanielYKPan** [comment]
In question.service.ts file, I created a new TextboxQuestion like this {label: 'Last Name", value: 'Joe'} (which is created without required set to true), the value: 'Joe' did not bind to the input field. I thought even the input field is not set to 'required', if TextboxQuestion's value was set, it should have bind to the input field.

**Comment by zoechi** [comment]
Can you please provide a Plunker that demonstrates the behavior?

**Comment by DanielYKPan** [comment]
http://plnkr.co/edit/bDNQnjhm0Df9EhPAOiFR?p=preview

**Comment by micronyks** [comment]
There is nothing new in it.  See `app/question-control.service.ts`'s this code.

 ```
toControlGroup(questions:QuestionBase<any>[] ) {
    let group = {};

    questions.forEach(question => {
      group[question.key] = question.required ? [question.value || '', Validators.required] : [];


      // this line says if question.required is true it will bind Joe value else it will bind " ".
      // if you change this line by,
      // group[question.key] = !question.required ? [question.value || '', Validators.required] : [];
      // it will bind Joe value
   
    });
    return this._fb.group(group);
  }
```

**Comment by kara** [comment]
Closing this, as it doesn't seem to be a bug.

**Comment by aswathaman** [comment]
how to change dynamic value in form Group name
//
format 
return this.form.group({
      headname: ['', Validators.required],
      category_sub: new FormArray([
        this.addFrom()
      ])
result:
headname:"hand"
category_sub:[
{ length:5},
{height:5}
];
i want like:
hand:[            // hand is input form dynamic value(array name:hand)
{ length:5},
{height:5}
]
how to write form group
