### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'task.zone.cancelTask') in Beta.11

### ISSUE THREAD

**Issue by rkrayovskyy** [angular/angular#7672]
* **I'm submitting a ... **
[x] bug report
[ ] feature request

* **What is the current behavior?**
Error raises when calling JS function at an html element. Worked well in Beta.8 and earlier.

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.11
- Browser: [all]
- Language: [TypeScript 1.8.9]

* **Other information**
I am trying to initialize http://c3js.org charts

```
// template
<div id="c3chart"></div>

// component
declare var c3;

buildChart() {
    c3.generate({
      bindto: '#c3chart',
      data: {
        columns: [
          ['data1', 30, 200, 100, 400, 150, 250],
          ['data2', 50, 20, 10, 40, 15, 25]
        ]
      }
    });
  }
```

**Comment by pkozlowski-opensource** [comment]
There is not enough context / details to help here. Please open issues following our submission guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue
