### ISSUE TITLE
ngModel has error on chrome and firebox, when typing composite character(like Korean)

### ISSUE THREAD

**Issue by vifore** [angular/angular#7674]
* **I'm submitting a ... **
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, see note at the top of this template.

When I type Korean(composite character) in input form with ngModel, cursor goes to end before composite complete.

I want to input : 서울(Seoul)
In chrome : 서우ㄹ
In firefox : 서ㄹ

'울' is composite character with ㅇ, ㅜ, ㄹ.
If only type '울' , no bug occurs.

Composite sequence of '서울' :
ㅅ -> 서 -> 성 -> 서(cursor position)우 -> 서울.
But in chrome :
ㅅ -> 서 -> 성 -> 서우(cursor position) -> 서우ㄹ.
Firefox:
ㅅ -> 서 -> 성 -> 서(우 disappers) -> 서ㄹ

Only IE11, Edge works fine input ngModel.
I'm sorry for poor English.

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.11
- Browser: Chrome 49
- Language: TypeScript

**Comment by diginalog** [comment]
#7503

**Comment by vss0705** [comment]
1+

**Comment by vifore** [comment]
Fixed after updating rc2 or rc3. Thank you.
