### ISSUE TITLE
unable to find a detach command to remove a @HostListener

### ISSUE THREAD

**Issue by born2net** [angular/angular#7675]
I looked through the docs and can't seem to find a way to remove @HostListener assignment.
Is this a needed feature that has not been added yet?

regards

Sean

**Comment by ericmartinezr** [comment]
Maybe you're looking for https://github.com/angular/angular/issues/7626

**Comment by born2net** [comment]
yes, looks like needs to be added :/

**Comment by ericmartinezr** [comment]
@born2net Yes, it's a feature request so far.

**Comment by ericmartinezr** [comment]
@born2net would be nice of you to close this issue if you think it is a dup of the one I referenced. You could also update your SO [question](http://stackoverflow.com/questions/36104167/angular2-how-do-you-remove-a-hostlistener) so other users know that this issue is being tracked.

**Comment by born2net** [comment]
np, tx
