### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by Johnaka** [angular/angular#7676]
* **I'm submitting a ... **
[*] feature request

why don't you put the library right into the browser ? like an engine. I think this would make it much faster

**Comment by zoechi** [comment]
You mean native Angular support in Chrome?

**Comment by TenthEstate** [comment]
Why not jqeury, react, ember, meteor and so on? I understand including dart or typescript engines in browsers but a framework.. are you serious?

**Comment by Johnaka** [comment]
@ zoechi @TenthEstate WHY other libraries ? and why dart+typescript ? what i am saying is transpiled version of angular to be native in chrome. es5, later es6, and so on. and even if you put all the libraries natively  i'ts going to be around 40mb, other libraries who use CDNs would never use them, and angular app that you build would stay in the cloud untouched, or another idea libraries as google extensions.

**Comment by TenthEstate** [comment]
@Johnaka as a browser you can't play favourites, I believe in an open web and I believe that any technology has the right to compete. If angular is browser builtin no other framework or new idea can compete. As great I think angular 2 is, and I think its amazing, it is not the be all end all and doesn't fit all software stacks.So no, native support is ridiculous.

**Comment by TenthEstate** [comment]
@Johnaka How many end users do you expect to download angular chrome extension or even know what angular is

**Comment by btford** [comment]
While we appreciate the enthusiasm, others have given good reasons why this can't happen. Standardization is the right process for this, and exactly what we're doing with Zones, for instance.
