### ISSUE TITLE
@ViewChild declared on parent class no longer works and is undefined

### ISSUE THREAD

**Issue by user414** [angular/angular#7679]
I have a simple class that extends another where ViewChild is defined in the parent class and the component defined in the html template of each of the subclass. I Updated from beta 6 to beta 11 and didn't notice this in the breaking changes. Perhaps it was never suppose to work in the first place? I could change the code around to make it work again, which might actually turn out better structured, but wanted to know if it suppose to work or just a bug. What's happening now is that the variable is undefined in beta 11.

**Comment by zoechi** [comment]
I guess this is a dup of #5415

**Comment by user414** [comment]
@zoechi Thanks again, yes it duplicate of 
https://github.com/angular/angular/issues/5415
will close and comment on that one.
