### ISSUE TITLE
Zone.js throwing an exception for clearTimeout(undefined)

### ISSUE THREAD

**Issue by pavanpodila** [angular/angular#7680]
I am using the Chart.js library which does auto-sizing of the chart on window resize. It does that by using setTimeout() and clearTimeout() when the event is triggered.

The `clearTimeout` is tripping zone.js

Plunkr: http://plnkr.co/edit/JZMytm59PPlYq3bdSoHy

Not sure if this is an issue with Angular or Zone or Chart.js. I tested chart.js independently and it works fine for window resize, when not inside an Angular component.

**Comment by pavanpodila** [comment]
Could be a dupe of https://github.com/angular/angular/issues/7666

**Comment by ericmartinezr** [comment]
Yes, actually they mentioned it in the website https://angular.io/docs/ts/latest/

**Comment by gdi2290** [comment]
if you build from source you can apply this workaround
https://github.com/AngularClass/angular2-webpack-starter/commit/1661e4ce847f90547e7bc875c57e8ebdfb3fef98

**Comment by pavanpodila** [comment]
@ericmartinezr @gdi2290 Thanks for the speedy responses. Hope to see **beta.12** come out soon

**Comment by Queatz** [comment]
This is breaking things.  Needs to be fixed!!

**Comment by igorzg** [comment]
+1 Same issue

**Comment by bianchessi** [comment]
+ 1

**Comment by pkozlowski-opensource** [comment]
Duplicate of #7666, fixed in beta.12.
