### ISSUE TITLE
Delays when typing in input field on Ubuntu GNOME 15.10

### ISSUE THREAD

**Issue by rsmith31415** [angular/angular#7684]
* **I'm submitting a ... **
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behavior?**
Unusual delays in input tag only affecting Chrome (dev, beta and stable) in Ubuntu GNOME 15.10. Other distributions behave okay (tested in Ubuntu 15.10)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via https://plnkr.co or similar (you can use this template as a starting point: 
Go to this [demo](https://plnkr.co/edit/Kxv5gkZMJ9RCpowzIAQw?p=preview) and start typing sufficiently slowly to notice delays between letters. 

* **What is the expected behavior?**
No delays should be noticeable.

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.8
- Browser: [Chrome 51.0.2679.0 dev  | Chrome  50.0.2661.37 beta | Chrome  49.0.2623.87
- Language: Typescript 1.7.3

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

I believe this is related to this [other](https://github.com/angular/angular.js/issues/13264) issue in the angular.js repo. I already reported that bug in the Chrome tracker [here](https://bugs.chromium.org/p/chromium/issues/detail?id=580606). Let me know if you think both bugs are related in order to provide additional information.

**Comment by zoechi** [comment]
It's not clear to my why you reported this bug here. Doesn't seem to be related to Angular2.

**Comment by rsmith31415** [comment]
Now that you say that, I think you're right. It is an overall issue in Chrome. I noticed it in Angular 2 but I think it occurs the same in other fields, although less noticeable.
