### ISSUE TITLE
path with extra parameters won't trigger router

### ISSUE THREAD

**Issue by naivefun** [angular/angular#7685]
**Note: for support questions, please use one of these channels:** https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
[*] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
A bug.

* **What is the current behavior?**
```
/resources;key=/value
```
it won't trigger /resources component/template

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.9
- Browser: [all]
- Language: [all | TypeScript 1.8]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by zoechi** [comment]
Can you please provide more information? Maybe a Plunker that demonstrates the issue?

**Comment by naivefun** [comment]
I updated to beta.11 and it works already, thanks.

**Comment by naivefun** [comment]
@zoechi 

I reproduced it.

Basically because the value contains '/', which makes the server fail to locate the router. For example:

```
/user;from=/product/123
```
In app itself if I click `routerLink` there is no problem, however if I copy the full URL and paste into another tab/window, the browser will consider `/product/123` as sub paths. That is why.

I'm not sure if this is a bug, I would just process the special character for now. Thanks.

**Comment by zoechi** [comment]
@naivefun sounds like #7312
