### ISSUE TITLE
binding inputs with [value] + ngControl

### ISSUE THREAD

**Issue by fxck** [angular/angular#7690]
- *_I'm submitting a ... *_
  bug report
- **What is the current behavior?**
  Inputs filled in with `[value]` do not update `form.value` or `form.validity`, while(in some cases at least) they visually fill in the value of the input.
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 
  - trimmed down example - http://plnkr.co/edit/dAN39ooSq5ySVz2T39Du?p=preview
  - example with working ngModel - http://plnkr.co/edit/LQHE4rs6syMnKKTrX9wJ?p=preview 
  - related issue(visually filled in value, `form.value` empty): https://github.com/justindujardin/ng2-material/issues/100 for both cases
- **Please tell us about your environment:**
  - Angular version: 2.0.0-beta.9
  - Browser: all
  - Language: typescript/all

**Comment by Devidian** [comment]
I'm currently having the same issues in my environment, using Meteor@1.3-rc.5 with angular beta.9 and ng2-material .11.
I can type into my forms and save user profile data but they wont show up in the forms. Even if i just add some default hardcoded text it isn't showing. As of my long time testing and wasteing time on this, i figured out that it must have to do something with ng2-material. I'm getting frustrated on this :(


profile.html
```
      <form name="userProfileForm" [ngFormModel]="userProfileForm" #f="ngForm" (ngSubmit)="doSaveProfile($event)">
				<div layout-gt-sm="row">
					<md-input-container class="md-block" flex-gt-sm>
						<label>First Name</label>
						<input md-input type="text" ngControl="firstname" [(ngModel)]="userProfileForm.firstname">
					</md-input-container>
          <md-input-container class="md-block" flex-gt-sm>
						<label>Last Name</label>
						<input md-input type="text" ngControl="lastname" [(ngModel)]="userProfileForm.lastname">
					</md-input-container>
				</div>
				
				<div layout-gt-sm="row">
          <button md-fab type="submit" class="md-button md-primary md-hue-2" aria-label="Comment" [disabled]="!f.dirty || !f.valid">
						<i class="md-icon"><i class="fa fa-user"></i></i>
					</button>
				</div>
      </form>
```

profile.ts
```
import {Component, NgZone, OnInit} from 'angular2/core';
import {RouterLink, Router} from 'angular2/router';
import {MeteorComponent} from 'angular2-meteor';
import {MATERIAL_DIRECTIVES} from 'ng2-material/all';
import {FORM_DIRECTIVES, FormBuilder, ControlGroup, Validators, FORM_BINDINGS} from 'angular2/common';

@Component({
	selector: 'profile',
	templateUrl: '/imports/ui/components/user/profile/profile.html',
	directives: [RouterLink, MATERIAL_DIRECTIVES, FORM_DIRECTIVES],
  viewBindings: [FORM_BINDINGS]
})

export class Profile extends MeteorComponent implements OnInit {
	user: Meteor.User;
	userProfileForm: ControlGroup;
	error: Meteor.Error = null;


	constructor(private _router: Router, private _ngZone: NgZone, private builder: FormBuilder) {
		super();

		this._ngZone.run(() => {
			this.user = Meteor.user();
    });
	}

	ngOnInit() {
		var User = this.user;

		console.log(User ? User.profile : "No User");

		this.userProfileForm = this.builder.group({
			firstname: [User ? User.profile.firstname : 'User not looaded'],
			lastname: [User ? User.profile.lastname : 'User not looaded']
		});
		console.log(this.userProfileForm.value);
	}

	doSaveProfile(event: Event) {
		event ? event.stopPropagation() : null;

		var profile: { firstname: string, lastname: string } = this.userProfileForm.value;

		console.log(event, this.userProfileForm);

		if (this.userProfileForm.valid) {
			Meteor.users.update(Meteor.userId(), {
				$set: {
					"profile.firstname": profile.firstname,
					"profile.lastname": profile.lastname
				}
			});
			console.log(profile);
			console.log(this.user);
		} else {
			// Validation errors
			this._ngZone.run(() => {
				this.error = new Meteor.Error("Failed to save profile");
				console.log(profile);
      });

		}
	}
}
```

also in this (my current try) setup $event is not set and the page keeps refreshing/ changeing route.

**Comment by fxck** [comment]
Hello? Anyone?

**Comment by fxck** [comment]
http://plnkr.co/edit/VJkmHWDhHEUoAx307s8k updated example to rc

**Comment by pkozlowski-opensource** [comment]
Updated plunker to RC6: https://plnkr.co/edit/lTPJagcowHYuJmzEczaz?p=preview

@fxck while I see the "bug" I don't think I get _why_ are you trying to set value from a template while using reactive forms. What is the advantage of setting this initial value from a template instead from JS code while constructing form controls in FB?

**Comment by pkozlowski-opensource** [comment]
Funny enough, when I looked at your plunker I would rather expect that the input field gets cleared up and UI is consistent with the form's state (in other words what is specified in the control "wins"). I don't think we should read value from the DOM and use it as a value in a control. It would be super-confusing if I specify a value in a control and another one in the DOM (value binding).

Well, it is super confusing today as both are not synchronized :-)

**Comment by fxck** [comment]
Well the thing is.. as far as I know, when you want to fill in the initial value, you can either wait until data is available, then do setValue/patchValue on each corresponding element, or use `ngModel`, the way ngModel seems to me is that it sets up some sort of binding, which is something I wanted to avoid. Thus trying to use `ngValue`, which seemed to me like a one time thing.

**Comment by bofcarbon1** [comment]
I'm having trouble understanding Angular 2 and binding data to forms with ngControl. I had no problem in Angular 1. I do what I have done for years with APIs, model objects and view binding. I list items then when one is selected use the key to retrieve details. So I do that in Express from MongoDB. I call the Express API using an Observable and return the JSON result to my class object. The problem is with this form control and ngControl format I can't figure out how to tell the form that I want it to use the class object to bind data. There is a gap.
