### ISSUE TITLE
Support case insensitive URL

### ISSUE THREAD

**Issue by jpleclerc** [angular/angular#7691]
* **I'm submitting a ... **
[ ] bug report
[X] feature request

* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
The router only supports case sensitive URLs.

* **What is the expected behavior?**
Add an option in the router to support case insensitive URLs.

* **What is the motivation / use case for changing the behavior?**
Some backend routers, like asp.net, are case insensitive. To be consistent with those backends we should be able to configure the router to resolve case insensitive URLs.

**Comment by ericmartinezr** [comment]
You have regex paths since beta.9 https://github.com/angular/angular/commit/75343eb34007579be9cdc803da834c38e02ae12c

**Comment by jpleclerc** [comment]
Going through all my routes and converting them to regex and serializers seems a little bit overkill for such a simple and common case. I would rather have a global option.

**Comment by btford** [comment]
I don't think a global option is a good idea.

A per-route flag might be OK, but as @ericmartinezr points out you can already accomplish this quite easily.

**Comment by vsavkin** [comment]
We are no longer maintaining the deprecated router to focus our efforts on making the new router robust.

You can provide a custom url serializer/deserializer when using the new router. So what you can do is you can wrap the default serializer to, for instance, lower-case the url.

Closing this issue.

**Comment by jebright** [comment]
Being able to control case-sensitivity on routes is important.  regex and/or custom serializers are a bit much to have to do for something basic like this.  Why close this request?  Why not keep open as a nice to have?

**Comment by bresleveloper** [comment]
ohh common guys, just some true/false property plz!
