### ISSUE TITLE
EXCEPTION: ApplicationRef.tick is called recursively

### ISSUE THREAD

**Issue by greg-md** [angular/angular#7693]
When I use external scripts, I have to run manually tick method to check for app changes.

For example facebook login:

```js
FB.login(response => {
  // do some changes
  this.isLoggedIn = true;

  // required tick
  this.applicationRef.tick();
});
```

All works ok while I wait for the response callback to be executed.

But I get `EXCEPTION: ApplicationRef.tick is called recursively` when I do some actions before the response callback is executed. For example when I focus an input element or whatever that angular will check for changes.

Version: 2.0.0-beta.9

**Comment by pkozlowski-opensource** [comment]
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by Rambatino** [comment]
How unhelpful @pkozlowski-opensource. It's not the most well-formed question, but there is no need to be arrogant and post a link as a response such as that.

**Comment by vicb** [comment]
@Rambatino we have so many incoming issues that we can not afford to spend too much time on each of them. There are documentation and GH templates to let users know when and how to use the issue tracker.

**Comment by Senthe** [comment]
@vicb @pkozlowski-opensource 
This thread is the first google result now for "ApplicationRef.tick is called recursively".

**Comment by maxisam** [comment]
can anyone delete this issue? This thread is unhelpful and showing on google result.
