### ISSUE TITLE
I can't find Provider in the dartdoc

### ISSUE THREAD

**Issue by kwalrath** [angular/angular#7696]
**1. Screenshot of bad content**
![image](https://cloud.githubusercontent.com/assets/2164483/13928399/b1ca2b16-ef52-11e5-9313-7bd6e8c63a48.png)

**2. URL where screenshot was taken**
https://ngdartdoc-dev.firebaseapp.com/index.html

**3. Why the content is bad**
Provider is an important class, but it's not documented. I can find references to it in API names, but no references to the actual Provider type. I believe this is because you aren't generating docs for angular2.core, for some reason.

The most recent generated doc I could find for Provider was beta.9 (the last release that dartdocs.org generated docs for angular2.core). URLs I tried include:

https://www.dartdocs.org/documentation/angular2/2.0.0-beta.9/angular2/Provider-class.html (works)
https://www.dartdocs.org/documentation/angular2/2.0.0-beta.9/angular2.core/Provider-class.html (works)
https://www.dartdocs.org/documentation/angular2/2.0.0-beta.10/angular2.core/Provider-class.html (404)
https://ngdartdoc-dev.firebaseapp.com/index.html

**4. What the content should look like**
Provider should be in the drop down, and docs should be available.

**5. Where else this issue occurs**
I suspect angular2.core has other important classes that need documentation. Examples: Injectable, Input, ...

@naomiblack

**Comment by pkozlowski-opensource** [comment]
Obsolete as dart-specific.

**Comment by kwalrath** [comment]
Also, fixed!
