### ISSUE TITLE
Browser refresh in beta.11

### ISSUE THREAD

**Issue by chundemer** [angular/angular#7699]
Browsersync not launching in beta.11

package.json:
...
"scripts": {
"postinstall": "npm run typings install",
"tsc": "tsc",
"tsc:w": "tsc -w",
"lite": "lite-server",
"start": "concurrent \"npm run tsc:w\" \"npm run lite\" ",
"typings": "typings"
},

"dependencies": {
"angular2": "^2.0.0-beta.11",
"es6-promise": "^3.1.2",
"es6-shim": "^0.35.0",
"reflect-metadata": "^0.1.3",
"rxjs": "^5.0.0-beta.2",
"systemjs": "^0.19.23",
"zone.js": "^0.6.2"
},
.....

Environment:
MAC/Chrome

"Issue":
When executing npm start, browsersyc does not appear to be starting. Changes are detected but not refreshed in browser.

"Resolution:
Changing entry in package.json from "angular2": "^2.0.0-beta.11" to ("angular2": "^2.0.0-beta.9" or "angular2": "^2.0.0-beta.8") browsersyc works as expected.

**Comment by CarlosAmaral** [comment]
Geez. Thought I was the only one. It doesn't compile at all.

**Comment by magbeat** [comment]
Hi. Happens to me too. For what I understand it has to do with 

"The current beta.11 release has known bugs relating to significant changes to the zones subsystem. All apps will report an error to the console:
Uncaught TypeError: Cannot read property 'zone' of undefined
The app will run unimpeded but it is disconcerting. We hope to have this and other bugs repaired by beta.12. Thanks for your patience."

... stated on https://angular.io/docs/ts/latest/

The app crashes and whether BrowserSync nor Livereload will connect.

I guess we have to wait for beta-12.

**Comment by Foxandxss** [comment]
Yes, let's wait for beta 12.

**Comment by magbeat** [comment]
Same issue as #7652, I guess.

**Comment by skovmand** [comment]
See also #7714

**Comment by pkozlowski-opensource** [comment]
Sounds like #7714 was fixed and this was supposed to be a duplicate. Closing. Please re-open if this is still an issue.
