### ISSUE TITLE
feat(compiler): improve error messages for change detection

### ISSUE THREAD

**Issue by btford** [angular/angular#7706]
We've seen several users confused by the `X has changed after it was checked` message. I'm in the process of collecting these issues here to see if we can provide a more prescriptive error by statically analyzing the template.

Consider this case from [a user's blog](http://www.bennadel.com/blog/3040-i-have-a-fundamental-misunderstanding-of-change-detection-in-angular-2-beta-8.htm):

```
@Component({
  selector: 'app',
  directives: [ ChildComponent ],
  queries: {
    children: new ViewChildren(ChildComponent)
  },
  template: `
    <h2>Child Count: {{ children?.length }}</h2>
    <child></child>
    <child></child>`
})
class AppComponent {}
```

Binding to the length of the `ViewChildren` query implicitly creates a cycle in change detection. Because we know the type of `children` in the template, we could provide the application developer with a much better error or warning in development mode.

According to @tbosch, this will require some significant changes.

Related to #7481, #7443

**Comment by steven-fernandez** [comment]
Looking forward to this improvement :)

**Comment by vicb** [comment]
obsolete
