### ISSUE TITLE
CI should include a job that tests against an npm-installed snapshot

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#7708]
There have been some issues recently where all of the project tests pass, but consuming the framework from npm has been broken. To address this, there should be a new job on Travis CI that does an `npm install` from a snapshot and tests that install against some simple example app. This will reduce the likelihood of accidentally releasing a broken version and then having to scramble to fix the issue and publish a new version.

cc @IgorMinar @alexeagle

**Comment by laco0416** [comment]
Also, I think it needs to put a release tag like `latest`, `next`, or others we need. 

all release installed with `npm install angular2` should always be correct. but I and some users probably think to want to use edge (sometimes broken) version through `npm install angular2@next`.

relates: https://github.com/angular/angular/issues/4671

**Comment by IgorMinar** [comment]
we already install from packages-dist folder for some integration tests. we can't install from npm because CI doesn't publish builds to npm. publishing to npm on every commit would be too expensive.
