### ISSUE TITLE
The saucelabs_required CI job is highly flaky

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#7710]
When running `test.unit.js.sauce/ci` in the CI `saucelabs_required` job, the test very frequently fails on Microsoft Edge. [Example](https://travis-ci.org/angular/angular/jobs/117590745#L2833).

This is a major timesink for the caretaker, as it requires a lot of re-running of jobs, or sometimes manual pushing of commits. 

I'm not sure if this is related, but we encountered a similar issue in material2 where Edge was very flaky because, for some reason, it took significantly longer to perform HTTP requests in tests than other browsers, making it consistently time-out.

**Comment by mehmetg** [comment]
Please see: https://github.com/angular/angular/issues/8604

**Comment by IgorMinar** [comment]
closing in favor of  #8604
