### ISSUE TITLE
Error: core_1.View is not a function when upg from beta 0.9 to 0.11

### ISSUE THREAD

**Issue by born2net** [angular/angular#7711]
Trying to upg to latest 0.11 from 0.9 is a no go with the following snapshot...
Unfortunately this is not something I can easily put in plunkr as it is a large project.
I did update zone and es6 shims.. will appreciate any tips on how to resolve this.

... and if I revert back to 0.9 all is well... tried 0.10 and same issue, so must be something that broke in between 0.9 and 0.10 but from the change log nothing seems obvious....

![capture](https://cloud.githubusercontent.com/assets/5090936/13942506/4e893b2e-efb0-11e5-922a-9f12f0a1b99d.PNG)

regards

Sean

**Comment by ericmartinezr** [comment]
@born2net `@View` was dropped in beta.10, you should stop using it. Move all your content from `@View` to `@Component. 

There's already a PR to add this breaking change to the changelog https://github.com/angular/angular/pull/7707

**Comment by born2net** [comment]
haaaa checking now... tx

**Comment by born2net** [comment]
tx again...
