### ISSUE TITLE
Upgrading to Angular2 beta 0.11 and getting zone.js fork error with system.js

### ISSUE THREAD

**Issue by born2net** [angular/angular#7712]
Upgrading to Angular2 beta 0.11 and getting TypeError: Cannot read property 'fork' of undefined
If I go back to 0.9 is all well... wondering if anyone seen this?

I looked at the change log and I see a lot of zone changes so wondering maybe this broke>
here is the error:

![capture](https://cloud.githubusercontent.com/assets/5090936/13942901/ca8ab03c-efb4-11e5-8248-c0383f6a9bc3.PNG)

regards and tx for reading,

Sean.

**Comment by born2net** [comment]
closing and as desc wrong

**Comment by ericmartinezr** [comment]
@born2net simply search in angular2's repo using your error messages. All the errors you're seeing have been reported a lot of times ;)

**Comment by micaelmbagira** [comment]
What was the solution of this one ?

**Comment by bromzh** [comment]
@micaelmbagira, use beta 13. For example, see working project [here](https://github.com/AngularClass/angular2-webpack-starter).
