### ISSUE TITLE
Upg from ng 0.9 to 0.11 getting error: ZoneSpec required!

### ISSUE THREAD

**Issue by born2net** [angular/angular#7713]
Anyone seen the following error when upg to 0.11?

![capture](https://cloud.githubusercontent.com/assets/5090936/13943045/49f121ca-efb6-11e5-8274-0618d5321a54.PNG)

tx,

Sean

**Comment by gdi2290** [comment]
include long stack trace. see fix here https://github.com/angular/angular/pull/7702

**Comment by born2net** [comment]
just saw that ;)
tx!!!!!

**Comment by born2net** [comment]
also added

import 'zone.js/dist/zone';
import 'zone.js/dist/long-stack-trace-zone';
