### ISSUE TITLE
Component property is not immediately updated after it has been modified by an event triggered by another component

### ISSUE THREAD

**Issue by robinbakkerus** [angular/angular#7715]
A property inside a regular angular2 (ts) component is automatically refreshed if is bound like {{msg}}
But it is **not** immediately refreshed if this value changed via an event being by another component.
This plunkr demonstrates this problem:
http://plnkr.co/edit/lgTmNdD7jjVkCIx2WIWO?p=info

**Comment by zoechi** [comment]
Looks like you're requesting #7421

**Comment by pkozlowski-opensource** [comment]
events from the `EventEmitter` are delivered synchronously now so this issue should be solved.
