### ISSUE TITLE
When implementing CanReuse, RouteParams do not update.

### ISSUE THREAD

**Issue by sidneydobber** [angular/angular#7716]
When implementing `CanReuse`, `RouteParams` do not update. While the `prev` and `next` parameters from `routerCanReuse` do contain updated paths. Is this intentional?

**Comment by brandonroberts** [comment]
@sidneydobber yes, RouteParams don't update once injected and the lifecycle hooks are where you access the updated params.

**Comment by btford** [comment]
You'll want to use `OnReuse` to get the new params. This is intentional. You should think of the params object as an immutable map.
