### ISSUE TITLE
Cannot resolve module zone.js/dist/zone-microtask in angular2 2.0.0-beta.11 and zone.js 0.6.4

### ISSUE THREAD

**Issue by mehrad-rafigh** [angular/angular#7717]
**Note: for support questions, please use one of these channels:** https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
[x ] bug report

* **Do you want to request a *feature* or report a *bug*?**
see above

* **What is the current behavior?**
With angular 2.0.0-beta.11 and zone.js 0.6.4 I get the following error:
**Module not found: Error: Cannot resolve module 'zone.js/dist/zone-microtask'** 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
- Update dep in package.json to angular2 2.0.0.beta-11 and zone.js to 0.6.4 
- npm install

* **What is the expected behavior?**
No errors when using npm install with angular 2.0.0-beta.11 and zone.js 0.6.4

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.11
- Browser: [ all ]
- Language: [TypeScript 1.8.9]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
multi main
Module not found: Error: Cannot resolve module 'zone.js/dist/zone-microtask' in /Users/xxx/repo/
resolve module zone.js/dist/zone-microtask in /Users/xxx/repo/garcon_hybrid2
  looking for modules in /Users/xxx/repo/.../node_modules
    resolve 'file' or 'directory' dist/zone-microtask in /Users/xxx/repo/node_modules/zone.js
      resolve file
        /Users/xxx/repo/node_modules/zone.js/dist/zone-microtask doesn't exist
        /Users/xxx/repo/node_modules/zone.js/dist/zone-microtask.js doesn't exist
        /Users/xxx/repo/node_modules/zone.js/dist/zone-microtask.ts doesn't exist
      resolve directory
        /Users/xxx/repo/node_modules/zone.js/dist/zone-microtask doesn't exist (directory default file)
        /Users/xxx/repo/node_modules/zone.js/dist/zone-microtask/package.json doesn't exist (directory description file)
[/Users/xxx/repo/node_modules/zone.js/dist/zone-microtask]
[/Users/xxx/repo/node_modules/zone.js/dist/zone-microtask.js]
[/Users/xxx/repo/node_modules/zone.js/dist/zone-microtask.ts]

**Comment by seanrkerr** [comment]
I'm having the same issue. 

My deps:  package.json to angular2 2.0.0.beta-11 and zone.js to 0.6.5.

**Comment by ericmartinezr** [comment]
Change it to `zone.js/dist/long-stack-trace-zone`

**Comment by mehrad-rafigh** [comment]
@ericmartinezr your suggestion does not solve the problem. When I open my developer console I can see the following error after I set `zone.js/dist/long-strack-trace-zone`:

`Uncaught ReferenceError: Zone is not defined`

**Comment by ericmartinezr** [comment]
What about doing some research? https://github.com/angular/angular/issues/7660#issuecomment-198624392

**Comment by mehrad-rafigh** [comment]
I close this issue and hope that it will be solved with beta.12

**Comment by jasonwaters** [comment]
Was not fixed in beta.12

**Comment by RemnantArcher** [comment]
Also not fixed in beta.13

**Comment by ericmartinezr** [comment]
There's no more `zone-microtask`, simply look at the repo https://github.com/angular/zone.js/tree/master/dist

You have to import `zone.js/dist/zone`.

**Comment by bromzh** [comment]
@RemnantArcher I use beta.13, zone.js 0.6.8. There are no problems with zone.js. My polyfills looks like this:
```js
import 'core-js';
import 'zone.js/dist/zone';

if ('production' === process.env.ENV) {
    // Production
} else {
    // Development
    Error.stackTraceLimit = Infinity;
    require('zone.js/dist/long-stack-trace-zone');
}
```
Also, you always can try fresh working angular2 project [here](https://github.com/AngularClass/angular2-webpack-starter).

**Comment by RemnantArcher** [comment]
I had already tried that. Simply updating from 0.6.6 to 0.6.8 did the trick

**Comment by kewix** [comment]
Same for me, have to change to "zone.js/dist/zone" instead of "zone-microtask" in my webpack.config.js and update to 0.6.8 ! Thanks.

**Comment by petervojtek** [comment]
hmm, i experience this eror with 
```
"angular2": "2.0.0-beta.15"
"zone.js": "^0.6.10",
```

**Comment by vikrana** [comment]
Thanks guys. this worked for me as well.
