### ISSUE TITLE
UNMET PEER DEPENDENCY rxjs@5.0.0-beta.3 with angular2 2.0.0-beta.11

### ISSUE THREAD

**Issue by mehrad-rafigh** [angular/angular#7719]
**Note: for support questions, please use one of these channels:** https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
[x ] bug report

* **Do you want to request a *feature* or report a *bug*?**
see above

* **What is the current behavior?**
angular2 2.0.0-beta.11 requires a peer of rxjs@5.0.0-beta.2 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
set angular2 to 2.0.0-beta.11 and rxjs to rxjs@5.0.0-beta.3 in package.json
npm install

* **What is the expected behavior?**
no warnings in the console

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.11
- Browser: [all ]
- Language: [TypeScript 1.8.9]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
+-- angular2@2.0.0-beta.11 
`-- UNMET PEER DEPENDENCY rxjs@5.0.0-beta.3

npm WARN angular2@2.0.0-beta.11 requires a peer of rxjs@5.0.0-beta.2 but none was installed.

**Comment by Foxandxss** [comment]
When installing angular 2, you need to install the following dependencies seen in [here](https://github.com/angular/angular/blob/master/package.json#L34-L39).

Even if there are modern version of the dependencies, you should use the ones that angular 2 requires.

**Comment by brian428** [comment]
Ideally they'd loosen up the peer dependency version requirement so that people can use the most current versions of the dependencies. However, I understand that everything is in rapid flux right now, so this may not work well while things are changing so quickly.

In this case, RxJS beta 3 fixes an issue that's causing really long TS compile times, so I understand why folks are eager to get onto RxJS beta 3 ASAP.

**Comment by robwormald** [comment]
as @brian428 mentions, there's a lot of things in flux at the moment. Rx beta.3 introduces a number of changes - a large one that requires TypeScript 1.8 is blocking us at the moment. We're working to resolve it, and that's exactly why we version lock.

**Comment by aSwains** [comment]
Hi @robwormald ! I'm just wondering if there's any status on updating the Rx dependency, or if there is an assigned github issue I can follow?
Thanks for your time, I really appreciate the work you guys do!

**Comment by gajusp** [comment]
Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/ng2-dropdown-treeview

or
+-- ng2-dropdown-treeview@0.1.4
+-- UNMET PEER DEPENDENCY rxjs@5.0.0-beta.12
`-- UNMET PEER DEPENDENCY zone.js@0.6.26

i have added the dependency in system.config.js file for ng2-dropdown-treeview, then it works for me

'rxjs': 'npm:rxjs',
            'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js',
            'lodash': 'npm:lodash/lodash.min.js',
            'ng2-dropdown-treeview': 'npm:ng2-dropdown-treeview/bundles/ng2-dropdown-treeview.umd.js',
