### ISSUE TITLE
Query with QueryList strips inline script tags

### ISSUE THREAD

**Issue by mlakmal** [angular/angular#7720]
when using Query with QueryList to get a reference to content defined in the widget definition it strips script tags.

```html
<widget>
  <div #content>
    <script type="application/json">
     {
        "test": "test"
     }
    </script>
  </div>
</widget>
````

```javascript
@Component({
selector: 'widget',
template: `<div></div>`
})
export class Widget {
constructor(@Query('content', {descendants: true}) elList: QueryList<ElementRef>){

//innerHTML of the element doesn't contain the script tag and json content associated with it.
elList.changes.subscribe(e => console.log(elList.first.nativeElement.innerHTML));

}
}
```

**Comment by ericmartinezr** [comment]
That's by design. They remove script tags https://github.com/angular/angular/issues/2766

**Comment by mlakmal** [comment]
do we have another means to access this script content before it gets removed ? 
we are using this mechanism in angular 1 to inject i18n content to directives to be used in text labels.

**Comment by zoechi** [comment]
@mlakmal a workaround is to create the script tags imperatively http://stackoverflow.com/questions/35570746/angular2-including-thirdparty-js-scripts-in-component/35570783#35570783

**Comment by mlakmal** [comment]
Thanks, i dont think that will work for us. in our application page route template html is generated by CMS system. and this html contains components/directive definitions. as part of that content generation, it will add the script tag inline between the component definition tags like i have given above. 

I guess we will have to use div tag instead of script tag to hold the json content when we move to angular 2. we used script tag so its clean solution that doesnt break html concepts ...

**Comment by pkozlowski-opensource** [comment]
@as noted by @ericmartinezr this is by design. If you want to load JS files use a JS module loader instead of injecting script tags.
