### ISSUE TITLE
Dart Router not working from entered URL

### ISSUE THREAD

**Issue by yageek** [angular/angular#7728]
### Bug Report

- Angular version: 2.0.0-beta.11
- Browser: [all]
- Language: [Dart]

### Reproduce

- Get code of the simple Dart application at https://github.com/gecker/gecker-frontend.
- A default route with path equals to `/welcome` is defined in the main component.
- Browse to http://localhost:8080/, the router forwards correctly to http://localhost:8080/welcome.
- Enter the URL http://localhost:8080/welcome in the browser, a 404 error is triggered : `Could not find asset web/welcome`.
- A child router is defined at path `/admin`
-  Enter the URL to http://localhost:8080/admin, a 404 error is triggered.

### Expected
I would expect to reach the component as defined in the `@RouteConfig`

**Comment by brandonroberts** [comment]
The issue of navigating directly to /welcome seems like more of a server issue. If you're using HTML5 mode which is the default, your server needs to be set to return your index.html whenever it doesn't match any other asset from the server.

The child router defined at `/admin` should be linked to your main app component, so you could define a route in your main app component with a path of `/admin/...` and define a default route in your admin component with a path of `/`

**Comment by yageek** [comment]
Regarding the child router, I think I did the link. What did I miss ?
Regarding the server, I simply ran `pub serve`. Should I add any other arguments to make it works correctly ?

**Comment by zoechi** [comment]
@yageek you need to configure your server to support HTML5 pushState or use `HashLocationStrategy`

```ts
bootstrap(MainApp, [
  ROUTER_PROVIDERS,
  provide(LocationStrategy, {useClass:HashLocationStrategy});
]);
```
http://stackoverflow.com/questions/31415052/angular-2-0-router-not-working-on-reloading-the-browser

**Comment by zoechi** [comment]
@yageek Just saw it's about Dart. Have a look at https://pub.dartlang.org/packages/pub_serve_rewrites
`pub serve` doesn't support HTML5 pushState.

**Comment by brandonroberts** [comment]
@yageek the admin route looks correct now, and if you use HashLocationStrategy as @zoechi said, it should work on direct navigation also.

**Comment by yageek** [comment]
I tested it works if I prefix the admin with a `#`. How should I proceed if I want to use `/admin` and not `/#/admin` ?

**Comment by brandonroberts** [comment]
@yageek then you have to look at the `pub_serve_rewrites` solution.

**Comment by yageek** [comment]
I will try the mentioned packages. Should I close this issue or you will handle it ?

**Comment by brandonroberts** [comment]
@yageek you can go ahead and close it

**Comment by AugustusLZJ** [comment]
I added this file <Ng2Dart-Workspace>/bin/dev_server.dart:
import 'package:pub_serve_rewrites/rewrites.dart';

main(){
  server()
    ..ignoreAll([
      r'^(\S+\.(json|html|js|dart|css|png))$',
    ])
    ..rewrite('/admin/(.*)',to:'admin.html')
    ..rewrite(r'(.*)',to:'/index.html')
    ..start('http://localhost:8080');
}

However, I got the following errors:

$ pub run bin/dev_server.dart
Proxying at http://localhost:8081
[GET] 
ERROR - 2018-04-15 03:00:28.834525
GET /
Error thrown by handler.
SocketException: OS Error: Connection refused, errno = 61, address = localhost, port = 57892
package:shelf_proxy/shelf_proxy.dart 46:19          proxyHandler.<fn>
package:pub_serve_rewrites/src/rewrites.dart 60:21  Server._handler.<fn>
package:shelf/shelf_io.dart 88:29                   handleRequest

[GET] favicon.ico
ERROR - 2018-04-15 03:00:29.033546
GET /favicon.ico
Error thrown by handler.
SocketException: OS Error: Connection refused, errno = 61, address = localhost, port = 57894
package:shelf_proxy/shelf_proxy.dart 46:19          proxyHandler.<fn>
package:pub_serve_rewrites/src/rewrites.dart 60:21  Server._handler.<fn>
package:shelf/shelf_io.dart 88:29                   handleRequest

**Comment by AugustusLZJ** [comment]
Just figure out a very simple solution, add a # between the path instead, e.x. "localhost:8080/#/welcome".
