### ISSUE TITLE
Special case attr.foo bindings

### ISSUE THREAD

**Issue by mhevery** [angular/angular#773]
To allow binding to attributes (as an escape hatch when binding to the properties is not working). This should fallow same philosophy as in #505 

`<div [attr.foo-bar]="expr">` would bind to the `foo-bar` attribute (not property) on the `div` element.

**Comment by pkozlowski-opensource** [comment]
This was fixed via 02aa8e794579ba8e19c2296d92e86513afe112bb. @mlaval if you add something like `Fixes #773` to the commit message this issue would get closed automatically when a commit lands.
