### ISSUE TITLE
2.0.0-build.cad693d fails on clearInterval

### ISSUE THREAD

**Issue by wardbell** [angular/angular#7730]
@mhevery -

Here is the plunker for the failing sample http://plnkr.co/edit/47lsARG9GPILwHaEX4JY?p=preview

It cuts down the cookbook "Communicating Components" sample to the two examples that use  `clearInterval`

Clicking the stop button one or more times triggers the exception

```
ZoneDelegate.prototype._updateTaskCount = function (type, count) {
                var counts = this._taskCounts;
                var prev = counts[type];
                var next = counts[type] = prev + count;
                if (next < 0) {
                    debugger;
---here ----->>>        throw new Error('More tasks executed then were scheduled.');
                }
```
I had to paste A2-polyfills.js and A2.min.js into plunker 'cause I couldn't think of another way to reach it. A2.dev.js was too big ... but it dies in pollyfills anyway so that should do it for you. You can always download the plunker source and move it to a good home for you.

**Comment by misko** [comment]
@mhevery ;)

**Comment by wardbell** [comment]
Sorry!  I dig the suits!  
You need to get those, @mhevery

**Comment by gaiottino** [comment]
There's also a `debugger` row which is rather annoying. Feels like something unfinished was accidentally released. The debugger and error occurs very often.
