### ISSUE TITLE
Additional predicate in By

### ISSUE THREAD

**Issue by gionkunz** [angular/angular#7733]
I frequently need to select `DebugElement`'s based on their text representation within my tests. What would you think of a new predicate that allows selecting elements based on their truncated text content?

``` javascript
fixture.debugElement
          .queryAll(By.css('.auto-complete__item'))
          .find((item) => item.nativeElement.textContent==='two')
          .triggerEventHandler('click');
```

Would be much nicer with:

``` javascript
fixture.debugElement
          .query(By.content('two'))
          .triggerEventHandler('click');
```

**Comment by zoechi** [comment]
You can create such a filter easily yourself. It's basically just a function that does a simple check for each element it gets passed in. No need to add it to the `By`class.

https://github.com/angular/angular/blob/master/modules/angular2/src/platform/dom/debug/by.ts

**Comment by gionkunz** [comment]
yeah sure, there's always the DIY option ;-)

**Comment by gionkunz** [comment]
Actually

```javascript
fixture.debugElement
          .query((e) => e.nativeElement.textContent === 'whatever')
          .triggerEventHandler('click');
```

Would do the trick too, just thought this could be part of By already. But maybe it's better to keep it simple.

**Comment by oauthentik** [comment]
I think someone just pulled up a library that and more  
[Angular Testing library](https://testing-library.com/docs/angular-testing-library/intro)
