### ISSUE TITLE
"Sticky States" support for Router

### ISSUE THREAD

**Issue by shaharvaldman** [angular/angular#7734]
* **I'm submitting a ... **
[X] feature request

* **Do you want to request a *feature* or report a *bug*?**
We are in the process of upgrading an existing angular1 application to angular2. 
One of the features we are missing is the ability for "**Sticky States**" with the router. On angular1 we used ui-router-extras, but for angular2 I would much rather go with a standard framework solution.

* **What is the motivation / use case for changing the behavior?**
Sticky states are often very useful for applications that require complex routing and allow the user to keep several states "alive" at the same time. The user often wants to work on a state, switch to another state(s), and then return to the original state and finalize it (or not). The different "live" states may live in different statuses (different data/valid/invalid etc.) and include internal routing as well.

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.11

**Comment by jpleclerc** [comment]
That feature request has been submitted multiple times:

https://github.com/angular/angular/issues/5275
https://github.com/angular/angular/issues/6634

I'm not sure if the Angular team is working on it.

**Comment by shaharvaldman** [comment]
10x!
I should have looked better myself...
