### ISSUE TITLE
Injecting incorrect generic type under Dart / DDC

### ISSUE THREAD

**Issue by vsmenon** [angular/angular#7736]
[This should be on the DDC hotlist]

The TodoMVC app injects a Store<dynamic> where the code expects a Store<Todo>.  This will fail in DDC which requires stronger typing.

(This may be captured in one of the DOWN_CAST_COMPOSITE warnings here: https://github.com/angular/angular/issues/7356)

In general, it's not clear if / how injectors can inject a reified type.  One possibility is to allow this and let Store<Todo> be injected.  Another is to disallow this.  E.g., Store (local to the app) could be non-generic or the actual injected type could be defined as:

```dart
class TodoStore extends Store<Todo> { ... }
```

@mhevery

**Comment by pkozlowski-opensource** [comment]
Obsolete as Dart-specific.
