### ISSUE TITLE
Demo of Animation Anchoring (via ng-animate-ref) broken on latest

### ISSUE THREAD

**Issue by vidhill** [angular/angular#7739]
Sorry if this is known or I shouldn't report bugs on the snapshot (I'm not sure on the protocol)

**Steps to reproduce and a minimal demo of the problem**
Visit https://docs.angularjs.org/api/ngAnimate#anchoring-demo 
v1.5.3-build.4692 (snapshot)

**Current behavior**
Pin animation demo not working as pin should work
**Expected/desired behavior**
Should work as in current stable release: https://code.angularjs.org/1.5.2/docs/api/ngAnimate#anchoring-demo

**Comment by ericmartinezr** [comment]
@vidhill I think you're looking for ng1 repo https://github.com/angular/angular.js, this one is for ng2

**Comment by vidhill** [comment]
Whoops, sorry!
