### ISSUE TITLE
@ContentChild with Interface as Type not working

### ISSUE THREAD

**Issue by asotog** [angular/angular#7741]
Hi there, 
I was trying to retrieve a @ContentChild but using an `interface` instead of component class directly as parameter, something like this:

```
@ContentChild(IResults) suggestion: IResults;
```

but ts compiler throwing: cannot find name 'IResults'

i implemented this interface in component and didnt throw errors, but start complaining when passing the interface on the contentchild parameter,

Any thoughts about this?

**Comment by robwormald** [comment]
Interfaces have no runtime value, and thus can't be used for this sort of thing - `interface` is purely a compiler construct.

**Comment by cguilhermef** [comment]
Ok @robwormald, even so, if I use a class - that still exists on runtime, I can't querying content child by "interface". How can we query a child that implements some interface? How to generalize that querying made by @ContentChild/@ContentChildren ?
