### ISSUE TITLE
[beta.12] Zonejs throwing Cannot read property 'fork' of undefined

### ISSUE THREAD

**Issue by micaelmbagira** [angular/angular#7747]
**Steps to reproduce and a minimal demo of the problem**
To reproduce it, you just can clone and run this repo https://github.com/micaelmbagira/angular-issue-zone/ and you will see the error in the browser console.

_What steps should we try in your demo to see the problem?_

**Current behavior**
Zonejs throws the following error : `Error: TypeError: Cannot read property 'fork' of undefined`

**Other information**
The error comes from `angular2@2.0.0-beta.12/src/core/zone/ng_zone_impl.js:29:36` which is this line : https://github.com/angular/angular/blob/master/modules/angular2/src/core/zone/ng_zone_impl.ts#L47

**Comment by zoechi** [comment]
Sounds like #7652

**Comment by micaelmbagira** [comment]
I solved it by including `angular2-polyfills` in my index.html.

**Comment by micaelmbagira** [comment]
Is there a real solution for this one, because importing `angular2-polyfills` is definitely not a good one ?
By the way, this doesn't happen with `beta.9`.
