### ISSUE TITLE
`RouterLink`/`ngLink` break the expected behavior of native anchor elements

### ISSUE THREAD

**Issue by gkalpak** [angular/angular#7749]
I'm not sure if this is a bug report, feature request or question. Let's see...

As seen in [router_link.ts#L76-L84][1], `RouterLink` is using the `click` event to navigate programmatically, instead of relying on the default behavior of `<a>` elements.

This approach has the drawback that native behaviors which the users are used to and expect (e.g. `Cmd/Ctrl+Click` to open in new tab, using the `target` to specify where to open etc) either don't work or `RouterLink` needs to "emulate" these behaviors, which entails certain risks/problems (e.g. accidentally missing one, having to account for browser quirks, having to keep `RouterLink` and `ngLink` (for the ng1 version) in sync etc).

So, there are mainly two parts in this issue:

1. Why is that so ? (I bet there must be reasons, because it wasn't like this from the beginning), but I couldn't find them (see below).)
    Off the top of my head, one possible reason is suporting `RouterLink` on non-`<a>` elements, but there are probably more.
    If we identify the actual reasons, maybe we can come up with a better solution, while still taking advantage of native browser implementations when possible.

2. If it turns out that there is no better way, then there are some things that need to be implemented/fixed:
    i. `Cmd/Ctrl+Click` should open in a new tab/window (with both `RoutrLink` and `ngLink`).
    ii. `ngLink` should respect the value of `target` (if present).

--
I tried to find out the reasoning behind this behavior by tracing the evolution of `RouterLink` (but without much success). Here is a little background:

* [Initially][2], it would just update the `href` attribute of the host element.
* [Then][3], a `click` listener was introduced _"to prevent default behavior"_ (but it's not clear _why_ we wanted to prevent default behavior).
* [Later][4], it was refactored to use `hostListeners` (I think this is unimportant for this issue).
* [Finally][5], some logic was added to not do anything (and allow the browser default behavior) if `target` is set and other than `_self`. And that's pretty much where we are now.

--
To make things a little more confusing, the `ngLink` directive (which is the equivalent of `RouterLink` for the ng1 version of the router) uses a [quite different implementation][6]:  

* It explicitly ignores non-'left' clicks (which `RouterLink` doesn't - but it doesn't seem necessary either).
* It doesn't respect the `target` property (which `RouterLink` handles properly).

Related to #5908.

--
Here are some runnabe demos of the issues:

[ng2 + `RouterLink` demo](http://plnkr.co/edit/hce31mZuLVNjCmYtUEnq?p=preview)
* Shows that `target` is respected.
* Shows that `Cmd/Ctrl + Click` does **not** work as expected.
* (Indirectly shows that `ngLink`'s special handling of non-`left` clicks, is probably redundant, since `right` clicks work as expected for `RouterLink` (even if it doesn't handle them in any special way).)

[ng1 + `ngLink` demo](http://plnkr.co/edit/PUfUljeLadooIaGOcfMe?p=preview)
* Shows that `target` is **not** respocted.
* Shows that `Cmd/Ctrl + Click` does **not** work as expected.

--
/cc @wardbell, @petebacondarwin 

[1]: https://github.com/angular/angular/blob/0898bca9398f851573743af706b456bd699e86f8/modules/angular2/src/router/directives/router_link.ts#L76-L84
[2]: https://github.com/angular/angular/commit/1b2754dacdd15e8fea429d56cdacb28eae76d2b1#diff-9a18e53799483fd90a9ffd5e0259704aR37
[3]: https://github.com/gdi2290/angular/commit/77d1fc149a0eb34bc872b8444c763bd05466f53c#diff-9a18e53799483fd90a9ffd5e0259704aR50
[4]: https://github.com/angular/angular/commit/92f1af86d8fca1bb87ef006b39e393403a3c284a
[5]: https://github.com/angular/angular/commit/a69e7fe297d993522167060cad275334ac95768e#diff-9268e07c1cf512e763f02b15bbcc652fR68
[6]: https://github.com/angular/angular/blob/0898bca9398f851573743af706b456bd699e86f8/modules/angular1_router/src/ng_outlet.ts#L239-L246

**Comment by gkalpak** [comment]
Right after submitting the issue, it occurred my that one more reason we can't rely on the default behavior  (with the current implementation) is that the URLs produced in `PathLocationStrategy` would result in a full-page reload.

If that is indeed the main reason and if we can't/don't want to work around it, then this is a bug report :grin:

**Comment by zoechi** [comment]
dup of #5908 ?
