### ISSUE TITLE
ensure same versions of shared packages in pubspec.yaml

### ISSUE THREAD

**Issue by tbosch** [angular/angular#775]
Already done for `angular2/package.json` and `benchpress/package.json`, should be done the same way for `angular2/pubspec.yaml` and `benchpress/pubspec.yaml`

**Comment by tbosch** [comment]
Still to be done.

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.
