### ISSUE TITLE
"in" operator is not supported in ngIf condition

### ISSUE THREAD

**Issue by dfsq** [angular/angular#7751]
If [in operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/in) is used in context of expression:

```
<div *ngIf="'prop' in obj">Content</div>
```

parser throws the error:

> EXCEPTION: Template parse errors:
Can't bind to 'ngIfIn' since it isn't a known native property ("
    &lt;div [ERROR ->]*ngIf="'prop' in obj"&gt;Content&lt;/div&gt;
  "): App@1:9
Property binding ngIfIn not used by any directive on an embedded template ("
    [ERROR ->]&lt;div *ngIf="'prop' in obj"&gt;Content&lt;/div&gt;
  "): App@1:4

**Demo**: http://plnkr.co/edit/3jvwZIBY5aeV9H8Lm0fj?p=preview 

**Current behavior**: parser throws an exception.

**Expected behavior**: ngIf should properly evaluate an expression containing in-operator.

**Comment by micronyks** [comment]
I think this syntax of `in` is used in `javascript` or its `javascript syntax` as shown. I don't think it will work with `ngIf` in `HTML template`. Many times angular has different ways to parse something in javascript (in angular) and same in html template. 
But still wait for some logical/promising reply .

**Comment by ericmartinezr** [comment]
I have a few thoughts about this one. The error makes me think that it's being desugared to

```
<template ngIf #'prop' [ngIfIn]="obj">...</template>
```
Just like `*ngFor="#var of array"` does, so it's unlikely to make this work with the current behavior for templates with these kind of operators. I would add a new directive called `NgIfIn` (yes, I know, not a good idea but it's the best I came up with) that takes two inputs : [ngIfIn] and [ngIfValue]

Here's a plnkr with a simple approach http://plnkr.co/edit/YcMg202wgIIrVK9c5o66?p=preview

All this assuming that what I think about what's going on is true, if it's not please ignore this comment.

**Comment by vicb** [comment]
You can use `o.hasOwnProperty(...)` or an helper method

**Comment by dfsq** [comment]
I know that I can use `hasOwnProperty` but anyway one would expect that in-operator was also supported. Anyway.

**Comment by whiteblackkeys** [comment]
@vicb have a look at this typescript snippet:

`   
    myvar: Aaa | Bbb; 
    if (myvar.hasOwnProperty('myfield')) {
      // typescript does NOT infer the type
    }

    if ('myfield' in myvar) {
       // typescript does infer the type, so if myfield is only present in Aaa, typescript can now know that myvar is of type Aaa
    }
`

I would like the same behavior in angular templates, what you think? Because I'm using fullTemplateTypeCheck and it's bothering me a lot saying that 'myfield does not exist on type Bbb'.

I hope I made myself clear, let me know.
