### ISSUE TITLE
child AsyncRoute with route parameter does not construct the path correctly with Angular Universal

### ISSUE THREAD

**Issue by wellingWilliam** [angular/angular#7752]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here, see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. 

**Steps to reproduce and a minimal demo of the problem**

`new AsyncRoute({ path: '/:id', loader: () => Promise.resolve(CommunityComponent), name: 'Communities' })`

```
<li *ngFor="#directory of directories" class="list-group-item">    
    <!-- Router link -->
    <a [routerLink]="[directory.path, directory.component, {id:directory.id}]" (click)="select(directory)" class="clickable">{{ directory.name }}</a>
</li>
```
https://github.com/wellingWilliam/AngularUniversalDSpaceUIPrototype.git

_What steps should we try in your demo to see the problem?_

Disable JavaScript and click templated link. 

**Current behavior**

The href of the anchor tag generated does not include the child route parameter supplied. 

I narrowed it down to a recursive method in instruction that builds the path from an aggregated instruction. See below. The internal recursive method calls _stringifyPathMatrixAuxPrefixed, which calls _stringifyPathMatrixAux which returns an empty string because the component is null yet the urlPath contains the route parameter value. This may be due to the Promise of the loader in the AsyncRoute. 

```
// default instructions override these
    Instruction.prototype.toLinkUrl = function () {
        return this.urlPath + this._stringifyAux() +
            (lang_1.isPresent(this.child) ? this.child._toLinkUrl() : '') + this.toUrlQuery();
    };
    // this is the non-root version (called recursively)
    /** @internal */
    Instruction.prototype._toLinkUrl = function () {
        return this._stringifyPathMatrixAuxPrefixed() +
            (lang_1.isPresent(this.child) ? this.child._toLinkUrl() : '');
    };
    /** @internal */
    Instruction.prototype._stringifyPathMatrixAuxPrefixed = function () {
        var primary = this._stringifyPathMatrixAux();
        if (primary.length > 0) {
            primary = '/' + primary;
        }
        return primary;
    };
    /** @internal */
    Instruction.prototype._stringifyMatrixParams = function () {
        return this.urlParams.length > 0 ? (';' + this.urlParams.join(';')) : '';
    };
    /** @internal */
    Instruction.prototype._stringifyPathMatrixAux = function () {
        if (lang_1.isBlank(this.component)) {
            return '';
        }
        return this.urlPath + this._stringifyMatrixParams() + this._stringifyAux();
    };
    /** @internal */
    Instruction.prototype._stringifyAux = function () {
        var routes = [];
        collection_1.StringMapWrapper.forEach(this.auxInstruction, function (auxInstruction, _) {
            routes.push(auxInstruction._stringifyPathMatrixAux());
        });
        if (routes.length > 0) {
            return '(' + routes.join('//') + ')';
        }
        return '';
    };
```

Here is a log of this.component in _stringifyPathMatrixAux which evaluates isBlank as true.

```
UnresolvedInstruction {
   component: null,
   child: null,
   auxInstruction: {},
   _resolver: [Function],
   _urlPath: '2',
   _urlParams: [] }
```

A quick fix would be to check the urlPath or the _resolver as well as checking if the component is blank.

```
Instruction.prototype._stringifyPathMatrixAux = function () {
        if (lang_1.isBlank(this.component) && lang_1.isBlank(this.urlPath)) {
            return '';
        }
        return this.urlPath + this._stringifyMatrixParams() + this._stringifyAux();
    };
```

or

```
Instruction.prototype._stringifyPathMatrixAux = function () {
    if (lang_1.isBlank(this.component) && lang_1.isBlank(this._resolver)) {
        return '';
    }
    return this.urlPath + this._stringifyMatrixParams() + this._stringifyAux();
};
```

Not exactly sure what the _resolver Function is. 

I do not know of the implications of appending the child unresolved instruction urlPath when the component is null. I do not know why the component is null. That may be the source of the problem, if it should not be null. Then again, not sure how the AsyncRoute populates component of the UnresolvedInstruction when it is being loaded via a promise.

**Expected/desired behavior**

When rendering server side using Angular Universal the href should be complete with route parameters. The server side event when clicking the routerLink must not be the same as running client side.

**Other information**

https://github.com/angular/universal/issues/330

**Comment by vaseker** [comment]
To reproduce that, simply build [routerLink] to async child component. There is no dependency on dynamic path building. E.g. 

```
<a [routerLink="['RootComponent', 'AsyncChildComponent', { param: 'value' }]"]>
```

constructs `a href="/rootComponent"`

**Comment by brandonroberts** [comment]
See https://github.com/angular/angular/issues/6562. This is an issue with the way the router constructs links for async routes. Since the route component hasn't been loaded, the router doesn't know what the full path is yet. The router generates enough of the base path for the route and then figures out the rest once the user navigates. I agree that the issue needs to be resolved, because in theory you could have your whole route tree defined in your app, so all your paths are known, but want to lazy load all the routes to save on initial load.
