### ISSUE TITLE
Object property with the same name as a local variable in template throws when handling events

### ISSUE THREAD

**Issue by rpdasilva** [angular/angular#7759]
Repeating over a set of objects in a template throws a TypeError when attempting to call a method with the same name as a local variable. In this case looping over a list of "action" objects and dynamically generate buttons i.e.

Edit: More concise example: https://plnkr.co/edit/QAygbyXHgseecK3xKTm9?p=preview
```
<div #action>
   <!-- ... some markup ... -->
   <div class="nested">
      <button *ngFor="#thing of things"
        (click)="thing.action($event)">
        {{thing.label}}
      </button>
  </div>
  <!-- ... some more markup ... -->
</div>
```

Original example: https://plnkr.co/edit/qIIz03Zq6R8iEGeCgP5N?p=preview
```
<button *ngFor="#action of actions"
    (click)="action.action($event)">{{action.label}}</button>
```

Angular 2: 2.0.0-beta.12
OS X: 10.11.2
Chrome: 49.0.2623.87 (64-bit)
```
TypeError: l_action2_0 is not a function
    at AbstractChangeDetector.ChangeDetector_Comp_2.handleEventInternal (VM1171 viewFactory_Comp:355)
    at AbstractChangeDetector.handleEvent (VM1197 angular2.dev.js:9833)
    at AppView.triggerEventHandlers (VM1197 angular2.dev.js:10511)
    at eval (VM1750 viewFactory_Comp:579)
    at VM1197 angular2.dev.js:13979
    at VM1197 angular2.dev.js:13407
    at ZoneDelegate.invoke (VM1180 angular2-polyfills.js:332)
    at Object.NgZoneImpl.inner.inner.fork.onInvoke (VM1197 angular2.dev.js:2216)
    at ZoneDelegate.invoke (VM1180 angular2-polyfills.js:331)
    at Zone.runGuarded (VM1180 angular2-polyfills.js:241)
```

Looking at the transpiled code, it seems the issue appears to be in `CodeGenViewFactory` trying to reference the `action.action()`method as if it were the local variable `action`
```
l_action0_0 = locals.get('action'); // <- this is going to get your action object, {label: 'Method, action: Function}
l_event1_0 = locals.get('$event');  // <- this gets the event that is going to be sent to your function, this case MouseClick
l_action2_0 = locals.get('action'); // <- here is the problem, I think since action is the local template
                                    //    variable name the code gen generates a locals.get instead of function
                                    //    invocation, because the property has the same name and it gets lost
                                    //    (should be smart to see that is a invocation from the template local variable
                                    //    and not apply locals to get from ngFor context)
```

Changing the local variable name allows this case to work as expected
```
l_actionObj0_0 = locals.get('actionObj');
l_event1_0 = locals.get('$event');
l_action2_0 = l_actionObj0_0.action(l_event1_0);  // <- looks good right because my local template variable is #actionObj
```

**Comment by danielfigueiredo** [comment]
+ 1
I think Angular should look at the entire expression before and understand that difference between properties from an Object and the template object itself.

**Comment by ericmartinezr** [comment]
Can you check if this PR solves your issue https://github.com/angular/angular/pull/7209 ?

**Comment by rpdasilva** [comment]
Not quite - this will instead throw an error on template compile because its detected a duplicate local variable.

Really the issue is the misidentification of an object's property as a local variable.
To expand on my example, this will throw an error on button click:

```
<div *ngFor="#action of actions">
    <button *ngFor="#subAction of alternateActions"
        (click)="subAction.action($event)"></button>
</div>
```

it's the `.action($event)` method that's being treated as if it were `#action`

**Comment by zoechi** [comment]
I think an error is the correct behavior. The expression is ambiguous and should not be allowed.

**Comment by rpdasilva** [comment]
So you're saying I need to worry about local template variable names conflicting with object properties I may be looping over deeper in my template?

My original example may be rather ambiguous, so here's a more concise plnkr using a template ref this time
https://plnkr.co/edit/QAygbyXHgseecK3xKTm9?p=preview

I'm choosing the name `action` but really I feel that this name collision between the local and an object property is itself arbitrary and not obvious as to why this should cause an error

**Comment by zoechi** [comment]
With template variables you introduce names in the same scope as component members. 

    (click)="subAction..."

could address the template variable `#subAction` or the components field. It is supported to use both in this context. How should Angular know which one you mean?

**Comment by rpdasilva** [comment]
I would expect Angular to look at the the entire expression rather than just the trailing property
`#subAction.action` is very different from `#action`

**Comment by pkozlowski-opensource** [comment]
This now fixed in RC.4: https://plnkr.co/edit/wP3I3z9K8TREt4TBn8El?p=preview
