### ISSUE TITLE
Compiler cannot reliably know element properties ahead of time 

### ISSUE THREAD

**Issue by rkirov** [angular/angular#776]
line
https://github.com/angular/angular/blob/cfe71def7e607968b03a03553dc3257926cdd4a1/modules/angular2/src/core/compiler/pipeline/element_binder_builder.js#L174

checks `property in element` in order to setup the element property binding. However, if element is a web component its properties are not known before the element is part of the live dom.

Simplest solution is to skip the check altogether and always bind to the element property.

However, if there is a directive on the same element that has bound to the same property, we should only bind with the directive.

**Comment by rkirov** [comment]
Additionally the dev mode property checks also fail for inactive web components.

check is here:
https://github.com/angular/angular/blob/master/modules/angular2/src/core/compiler/pipeline/directive_parser.js#L137

I don't see an easy solution for this one, suggestion?

**Comment by pkozlowski-opensource** [comment]
@rkirov OK, I've looked into this one a bit more and I'm slightly worried about this assumption:

> However, if there is a directive on the same element that has bound to the same property, we should only bind with the directive.

If I understand you correctly you are saying that in case like this:

```html
@Decorator({
   selector: '[title]',
   bind: {'title': 'title'}
})
class TitleDecor {
   title;
}
``` 
and template like `<div [title]='exp'>` we would bind to the TitleDecor's property, but not to the div's title property, right? In other words, directives would be more "eager" in consuming property bindings?

I'm not sure how I feel about it right now, it sounds a bit arbitrary - especially if we consider web components. On top of this behaviour of the system would depend on presence / absence of directives witch could be confusing / surprising at times... 

@rkirov could we discuss about this one when you've got a moment?

**Comment by pkozlowski-opensource** [comment]
So, the other problem (?) with skipping this check altogether is that Dart gets very upset about setting a non-existing property, ex: `<div [someprop]="exp>"` will fail at run-time with:

> Caught Class 'DivElement' has no instance setter 'someprop='

This might a "good thing", though, depending on one's perception...

**Comment by rkirov** [comment]
I see your concern about Angular components taking over the binding. However, consider the alternative, always binding to both DOM element and Angular component. Most of the time the developer uses bindings to propagate data between his own directives and the extra work we are doing to sync with the DOM is unnecessary. That work is not without a cost, especially in environments like webworkers where dom operations have to be brokered across a channel.

The dart error is inevitable because objects are sealed. A dart user would not be expecting expando properties of DOM elements to begin with, that's how `dart:html` works, are we cannot magically change it. I did a small test with the dart polymer [demo](https://www.dartlang.org/docs/tutorials/polymer-intro/#an-example) and indeed after polymer runs HtmlElement instance gets replaced with the proper custom element instance, where you can use the proper setters. I see this as another reason only to bind to one object - either Dom Element or Angular component.

Taking over the binding is the right thing to do, and it needs to be carefully documented and explained to the users.

**Comment by mhevery** [comment]
I was thinking about this, and I would like to suggest a possible solution.

What if we have a list of element-names and their attributes overrides.

Algorithm.
1. Check `hasOwnProperty`
2. Check exeception list
3. Throw error

**Comment by rkirov** [comment]
@mhevery so given `<google-youtube>` component with property binding `video`. During the compiler run `<google-youtube>` hasn't waked up as a web component so it does not `haveOwnProperty('video')`, should `google-youtube` or `video` be in the exception list?

Who will be responsible for maintaining the exception list?

**Comment by mhevery** [comment]
Also we should be using `'property' in instance` rather than `instance.hasOwnProperty('property')`

The waking up is a general problem, and it seems like we need to delay checking the property until after we import into `document` from the `template`. 

The exception list is something we may have to do after all else fails. 

(Just throwing crazy ideas out.) 

Perhaps we should disable the check for now.

**Comment by mhevery** [comment]
@pkozlowski-opensource  can we just disable this check for now, until we figure out a proper way to handle this?
