### ISSUE TITLE
Preventing location changes for aux outlets

### ISSUE THREAD

**Issue by orcun** [angular/angular#7768]
I have an auxiliary outlet (mostly hidden) which is sort of like an application wide context menu. I have a main router outlet that hosts many child components and each child component can request different components to be shown at the auxiliary outlet. My main component navigates to links requested by child components and while doing so, it sets skipLocationChange to true: 

    app.context.subscribe((linkParams: any[]) => {
      let ins = this.router.generate(linkParams);
      this.router
        .navigateByInstruction(ins, true)
        .then(() => {
          this.sidenav.show('context');
        });
    });

Everything is OK for now, however when I navigate to another main route, location changes to `/other(context;x=[object%20Object])` which was not something I wanted but I could not find any way to prevent it. You may notice that I'm using an object as the parameter as well, which is pretty handy in a context menu scenario.

After diving into angular source code, all could do was to override existing behavior as in:

    Instruction.prototype['_stringifyAux']=function(){
      return '';
    }

What I would like to suggest is something like `<router-outlet name='context' [persist]='false' [required]='true'>` where `[persist]=false` prevents its route showing up in the location. Since I am shameless :sunglasses: , I also propose a `[require]='true'` which means if I don't provide a specific instruction in my route link, this auxiliary outlet should navigate to its default route.

**Comment by vicb** [comment]
obsolete - former router
