### ISSUE TITLE
Router `CanDeactivate` doesn't mention that it waits of a returned `Promise` like `OnActivate`

### ISSUE THREAD

**Issue by zoechi** [angular/angular#7779]
**Steps to reproduce and a minimal demo of the problem**
https://github.com/angular/angular/blob/2.0.0-beta.12/modules/angular2/src/router/interfaces.ts#L99-L124
shows the return type is `boolean | Promise<boolean>` but the docs only mention `true` / `false`
while `OnDeactivate mentions that it waits for the returned `Promise` https://github.com/angular/angular/blob/2.0.0-beta.12/modules/angular2/src/router/interfaces.ts#L64

**Comment by vicb** [comment]
obsolete
