### ISSUE TITLE
feat(ngSwitch): Control of spacing between word in ngSwitch

### ISSUE THREAD

**Issue by user414** [angular/angular#7780]
Unless there's something I'm missing the only way to control whether inline element will be treated as one word or multiple word in a ngSwitch inside an ngFor is to have them all in one line. For example

```
<span [ngSwitch]="toeChoice">
  <span *ngSwitchWhen="'Eenie'">Eenie</span>
  <span *ngSwitchDefault>other</span>
</span>
```

vs

```
<span [ngSwitch]="toeChoice"><span *ngSwitchWhen="'Eenie'">Eenie</span><span *ngSwitchDefault>other</span></span>
```

the last one will cause the two span to be next to each other and display on the same word according to w3 specs and the first one since the span are generated on separated line will treated as two words with a space in between them, in latin locale. Now if your ngSwitch is more then a few statements and you want them to be displayed as one logical entity it makes for very unreadable code. It would be nice if this could be controlled via a property of the ngSwitch statement instead of the code formatting.

**Comment by pkozlowski-opensource** [comment]
But this is _exactly_ how HTML behaves, no? I don't think we want to have custom Angular rules here - this would be one more thing to code, test, explain etc.

Having said this in your particular case I wouldn't really use `ngSwitch`. Why not do:
`<span>{{toeChoice === 'Eenie' ? 'Eenie' : other}}</span>` (unless of course your use-case is more complex than this).

I'm going to close this one for now but if you've got more details concerning your use-case I would be happy to re-open.
