### ISSUE TITLE
multi-line text will not do line break in view

### ISSUE THREAD

**Issue by asiacoll** [angular/angular#7781]
I have a multi-line text data from database and want it to be displayed as {{text}} in template. However the result just display a text string, no line break. br  is just ignored. Please fix!

**Comment by asiacoll** [comment]
I mean br is ignored.

**Comment by zoechi** [comment]
That's by design. You can't bind HTML using `{{}}`. Use instead `<div [innerHTML]="text"></div>` (or any other tag instead of `div` of course)

**Comment by asiacoll** [comment]
thanks. It works. However i found another issue.
I found that "\n" can break line in textarea,but not in <div [innerHTML]="text"></div> . I know I must replace "\n" with "<br>" in <div [innerHTML]="text"></div>. The problem is "\n" is no more exist in <div [innerHTML]="text"></div>. May be "\n" has changed it's form in <div [innerHTML]="text"></div>. But what is the changed form. Please help.

**Comment by asiacoll** [comment]
I mean I know I must replace "\n" with  "br"

**Comment by asiacoll** [comment]
"<div [innerHTML]="text"></div>" is missing above

**Comment by asiacoll** [comment]
the issue was resolved using `x.replace(new RegExp('\n', 'g'), "<br />")`

**Comment by zoechi** [comment]
If your problem is solved, you could go ahead and close the issue.

**Comment by Paulmolin** [comment]
Be careful, as interpreting user input as HTML enables users to use html tags. Angular seems to remove Javascript handlers such as onerror or onmouseover etc. but you migth insert XSS in your app.

**Comment by Airblader** [comment]
This issue appears on Google pretty quickly, so I just wanted to share a simple solution for this:

```
white-space: pre-wrap
```

(It's also what YouTube seems to do for their comments)

**Comment by Amrit1994** [comment]
<div class="angular-with-newlines" ng-repeat="item in items">
   {{item.description}}
</div>

/* in the css file or in a style block */
.angular-with-newlines {
    white-space: pre-wrap;
}

Reference: https://stackoverflow.com/questions/19684708/preserve-line-breaks-in-angularjs

**Comment by Paradisee** [comment]
That's what i did: `<div><pre>{{ whatever }}</pre></div>`

**Comment by Akitha** [comment]
Just add this to your styles, this works for me

    white-space: pre-wrap

**HTML**
  

       <p class="text-style">{{product?.description}}</p>

  
**CSS**

    .text-style{
        white-space: pre-wrap
    }

By this text in `<textarea>`can be display as it's in there with spaces and line brakes
