### ISSUE TITLE
error TS2300: Duplicate identifier , after upgrading to "angular2": "2.0.0-beta.12", "typings": "^0.7.9",

### ISSUE THREAD

**Issue by sap9433** [angular/angular#7786]
**Steps to reproduce and a minimal demo of the problem**
1) Clone `https://github.com/sap9433/angular2-webpack-starter-kit`,  
2) npm install & npm start
App works fine because it's using ` "angular2": "2.0.0-beta.7" `and `"typings": "^0.7.9",`
3) Update the dependencies `npm-check-update -u`
4) package.json is updated with ` "angular2": "2.0.0-beta.12"`, `"typings": "^0.7.9",`
5) Update your ambient dependencies as well to
```
{
  "ambientDependencies": {
    "es6-shim": "github:DefinitelyTyped/DefinitelyTyped/es6-shim/es6-shim.d.ts#7de6c3dd94feaeb21f20054b9f30d5dabc5efabd"
  }
}
```
6) Do `npm install` and `npm start`

Now you will get plethora of *_duplicate identifier error_* like following

```
ERROR angular2-webpack-starter-kit/typings/browser/ambient/es6-shim/index.d.ts
(8,14): error TS2300: Duplicate identifier 'PropertyKey'.

ERROR in typings/browser/ambient/es6-shim/index.d.ts
(11,5): error TS2300: Duplicate identifier 'done'.
.....
.....
```

_What steps should we try in your demo to see the problem?_
1) Run the app in your local
2) look at the dev-server logs.

**Current behavior**
Updating angular2, typings, and ambient dependencies to latest release throwing  `error TS2300: Duplicate identifier` errors.

**Expected/desired behavior**
App shouldn't throw `error TS2300: Duplicate identifier` errors

**Other information**
It might as well be an es6 shim issue with typescript , as both the files are using same global variable

**Comment by sap9433** [comment]
As suspected issue is with ambient dependency ... Changing Ambient dependency to the following fixed the issue.

```
{
  "ambientDependencies": {
    "es6-shim": "registry:dt/es6-shim#0.31.2+20160215162030"
  }
}
```

**Comment by salibhai1** [comment]
Details on how to fix found here: http://blog.mgechev.com/2016/03/28/ambient-type-definitions-duplicate-identifier-typescript-fix/

**Comment by nottinhill** [comment]
What if we use npm?

**Comment by aderbas** [comment]
I'm use Angular 2.0.0 and no longer es5-shim, but I am getting this error after installing typings the core-js. =/

**Comment by wuno** [comment]
@Splaktar Hey thanks for the suggestion. That worked for me too for clearing the errors I got when moving from es5 to es6. Do you have an explanation for this? It  "@types/core-js": "^0.9.34", just not needed when using es6 for some reason? Just one less dependency and nothing to worry about?

**Comment by Splaktar** [comment]
@wuno It's also mentioned here: https://github.com/angular/angular-cli/issues/1908#issuecomment-248775633

This is related but the answers and explanations aren't very clear: http://stackoverflow.com/questions/38814049/howto-import-core-js-map-into-angular-cli-webpack-generated-application

This answer seems to give a hint about what we're seeing: http://stackoverflow.com/a/31800188/633107

It seems that `lib.d.ts` or `lib.es6.d.ts` is imported automatically by TypeScript. So when using core-js types that override those, you get a conflict. More details on `lib.d.ts` [here](https://basarat.gitbooks.io/typescript/content/docs/types/lib.d.ts.html).

Perhaps the proper fix is using the `"noLib": true` in `tsconfig.json` and importing the core-js types?

**Comment by Splaktar** [comment]
I was able to test some more today and `noLib` didn't work for me.

It resulted in `Error in bail mode: [default]                                                                                                                                                                                                                                         
Cannot find global type 'Array'.` or `Error in bail mode: [default]                                                                                                                                                                                                                                         
Cannot find global type 'Boolean'.` I tried a number of workarounds for this including modifying the `libs` array, but nothing worked.

**Comment by shahzadns** [comment]
In my case, after using official [quickstart tutorial](https://angular.io/docs/ts/latest/quickstart.html), got the same error.

This answer(http://stackoverflow.com/a/36907668) helped me, used for ES5.
Cheers !
