### ISSUE TITLE
bug(router) Lifecycle-Hooks loose information about prior route when using nested components

### ISSUE THREAD

**Issue by choeller** [angular/angular#7787]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here, see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. 

**Steps to reproduce and a minimal demo of the problem**

http://plnkr.co/edit/wbcGotYtNKKmYSf9PaTH?p=preview

This plnkr contains a RouteConfig with a nested Route `['/Tasks', 'List']` clicking the "Tasklist"-Link you can see that in the `routerOnActivate`-Hook the Tasklist-Component gets no information about the `from`-part of the link. Furthermore the `to`-parameter only contains the relative part of the Url (relatated to the `Tasks`-Component).

**Current behavior**

TaskList-Component gets no information about the prior route

**Expected/desired behavior**

TaskList-Component should get information about the prior route

**Other information**

**Comment by vicb** [comment]
obsolete
