### ISSUE TITLE
bug(router) Instruction passed to component in Lifecycle-Hook is not usuable for further navigation

### ISSUE THREAD

**Issue by choeller** [angular/angular#7788]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here, see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. 

**Steps to reproduce and a minimal demo of the problem**

http://plnkr.co/edit/wbcGotYtNKKmYSf9PaTH?p=preview

The plnkr tries to utilize the Instruction passed into `routerOnActivate` to navigate back to the prior location:

```ts
export class About {
  from: Instruction;
  constructor(private router: Router) {}

  routerOnActivate(to, from) {
    this.from = from;
    console.log("About: ", to, from);
  }
  
  goBack() {
    this.router.navigateByInstruction(this.from);
  }
}
```

**Current behavior**

Clicking the "Go Back" button in "About"-View leads to the following exception:

```
Error: Uncaught (in promise): TypeError: instruction.resolveComponent is not a function
    at resolvePromise (angular2-polyfills.js:543)
    at angular2-polyfills.js:579
    at ZoneDelegate.invokeTask (angular2-polyfills.js:365)
    at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (angular2.dev.js:2208)
    at ZoneDelegate.invokeTask (angular2-polyfills.js:364)
    at Zone.runTask (angular2-polyfills.js:263)
    at drainMicroTaskQueue (angular2-polyfills.js:482)
    at HTMLButtonElement.ZoneTask.invoke (angular2-polyfills.js:434)
```

**Expected/desired behavior**

There should be a way to use the information passed into `routerOnActivate` to navigate back to the prior location

**Other information**

**Comment by ericmartinezr** [comment]
@choeller you can with the following code

```
this.router.navigateByInstruction(new ResolvedInstruction(this.from, null, {}));
```
@brandonroberts helped me with this a time ago. Obviously your point stands, the instruction should be enough to navigate to it.

**Comment by choeller** [comment]
@ericmartinezr Interesting! Thanks a lot! As my actual use case involves nested routes (see https://github.com/angular/angular/issues/7787) I will currently have to stay with `window.history.back()` -  but good to know there is workaround for other situations...

**Comment by brandonroberts** [comment]
We seem to be relying more and more on subscribing to the router, which seems likes it going against its intended use. That being said, you could use a service to subscribe to the root router, and store the full previous/current instruction and use it when you want to use the instruction to navigate somewhere else.

**Comment by revoxover** [comment]
@brandonroberts Could you expand on what you mean by "subscribe to the root router"? I am having the same problem as @choeller with nested routes. If I understand what you mean by subscribe _router.subscribe(...)_; I simply get a URL in return. 

I need access to the **actual** (not relative) next and previous instructions from within a component's lifecycle hooks (i.e. onReuse) to determine if the current component is the active url endpoint (i.e. /home/current) or if the current component is a parent to a further nested endpoint (i.e. /home/current/child).

**Comment by brandonroberts** [comment]
@revoxover I mean subscribe to the root router for updates, but not necessarily just to get the URL. When a new URL is emitted, you know that the navigation is complete. The root router also holds the entire instruction used to generate that URL. The lifecycle hooks `routerOnActivate` is called after the component is instantiated, but that doesn't mean the navigation cycle is over. 

The information you want isn't in the lifecycle hook because they have no knowledge of where they came from or what's happening next. You could glean that information from the full instruction provided from the root router.


```
router.root.subscribe(() => {
   let instruction = router.root.currentInstruction; // full instruction

    // loop through each instruction
    while (instruction.child) {
        instruction = instruction.child;

        // instruction contains the component, slice of urlPath, params, etc
    }
});
```

**Comment by revoxover** [comment]
@brandonroberts Ahhh yeah "router.root"...that is the secret handshake I needed. I saw that mentioned in the docs but overlooked it since it is not documented yet. Thanks again!
