### ISSUE TITLE
Placeholder not working for select-options in angular 2.

### ISSUE THREAD

**Issue by KannanMuruganmony** [angular/angular#7789]
code attached as screenshot in the image attached

![placeholder not wokring](https://cloud.githubusercontent.com/assets/8846631/14067783/f5a1dcaa-f464-11e5-8d7e-f26e0053a70c.png)

Placeholder text (Account) is not visible when the form loads. It's just an extra options in the options list.Please help!!. My first post :+1:

**Comment by micronyks** [comment]
what error you get?
check if its suitable for you. OR can you just reproduce it here  with your implementation?

http://plnkr.co/edit/MgsJcflE8wpTeOnY9Cfg?p=preview

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by MarkPieszak** [comment]
Use stackoverflow for support questions @KannanMuruganmony

**Comment by pkozlowski-opensource** [comment]
Sounds like a general support question without a reproduce scenario. Closing.
