### ISSUE TITLE
Improved style support for components (rough proposal)

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#779]
As part of emulating shadow DOM, we have to implement a solution for *loading* CSS inside of components. 

#### Embedding style rules directly into the component template is undesirable
* Makes templates harder to read
* Makes it much harder to use CSS pre-processors (sass, less)
* Would lead to duplicating "common" styles

#### Problems
* The `<link>` element (the normal way of loading CSS) [is inert in shadow DOM](http://www.w3.org/TR/shadow-dom/#inert-html-elements).
* CSS `@import` is generally [frowned](https://developers.google.com/web/fundamentals/performance/critical-rendering-path/page-speed-rules-and-recommendations?hl=en) [upon](https://developer.yahoo.com/performance/rules.html#csslink) [for](https://www.modern.ie/en-us/performance/css-web-performance-optimizations) [performance](http://www.stevesouders.com/blog/2009/04/09/dont-use-import/) [reasons](http://stackoverflow.com/questions/1022695/difference-between-import-and-link-in-css).

#### Opportunity
Since Angular will control how styles are actually rendered for a component (because of shadow DOM emulation), we can extend There are other ideathe process to give component authors more power.

### Proposal
Angular core implements a directive to include a style file via URL. For discussion's sake, let's call this `<ng-style>` (it will probably end up being something like `<style>` or `<link>`, though):

```html
<!-- fancy-button.html --> 
<ng-style src="../my/style/file.css">
<button class="super-fancy">...</button>
```

When `ng-style` is used in a Component with native shadow DOM, the output `<style>` element is rendered inside of the shadow DOM for each component. When using emulated shadow DOM, one common`<style>` element is added to the document head for all component instances. 

`ng-style` can also be used to provide component authors a means through which to apply some arbitrary transformation to the embedded style. This could look vaguely something like:
```html
<!-- fancy-button.html --> 
<ng-style src="../my/style/file.css" transform="MaterialThemeTransformer">
<button class="super-fancy">...</button>
```
```js
class MaterialThemeTransformer {
  transform(input: string): string {
    // do some transformation
  }
}
```
This is purposefully hand-waving a lot of details, but I just want to get the idea across. The main use-case I have in mind for this is creating style rules that are defined in terms of some theme (e.g, `background-color: {{primaryColor}}`)

This would let people do whatever arbitrary transformation on the incoming rules, including applying sass or less on the fly (if you wanted to do that for some reason). If CSS shimming is enabled, that process would occur after any user-defined transformations. The CSS shim itself could potentially just be another transform.

#### Other notes
It's possible that this mechanism doesn't have to be so tightly coupled to styles, and could instead just be a part of how interceptors/transforms work for all http requests, depending on how http support looks when it's built.

**Comment by vicb** [comment]
Some thoughts based on discussions with @mhevery and my work on #772 

> CSS @import is generally frowned upon for performance reasons.

We should use `@import` to stay close to web components. Performance should not be an issue as `@import` would be inlined by the build system.

> Would lead to duplicating "common" styles

When styles are scoped (current `EmulatedShadowDomStrategy`), styles are re-written per component hence we have to "duplicate" styles for each component. However there are plans to have an Emulated strategy with shared styles. The strategy will take care of de-duplicating (ie styles will be inserted once in the `<head>`)

> The main use-case I have in mind for this is creating style rules that are defined in terms of some theme (e.g, background-color: {{primaryColor}})

This could be nice but require more thinking. When we have such rules it would not be possible to share styles (ie different components could have different `primaryColor`.

> including applying sass or less on the fly (if you wanted to do that for some reason)

This is also something we have discussed with @mhevery. It is currently not possible and #772 will probably not include support for that. However I have some ideas in mind to support CSS transformations.
The handling of CSS transformations need to be quite flexible:
- we need to inline `@import`, rewrite URLs and optionally scope the rules in dev mode,
- in prod mode none of this should happen as the templates are pre-processed.
While designing support for that, it should be easy to add sass, less, or whatever arbitrary transform support.

**Comment by jelbourn** [comment]
> We should use @import to stay close to web components.

@vicb What do you mean by `@import` being close to web components? CSS `@import` has been around for a long time, and popular sentiment is that it should be avoided. Even if browsers have improved it, it's still a common perception that it's slower. It may *still* a problem in IE- [this MS blog post](https://www.modern.ie/en-us/performance/css-web-performance-optimizations) from less than a year ago still advises against it (this will probably need some testing).

> When styles are scoped (current EmulatedShadowDomStrategy), styles are re-written per component hence we have to "duplicate" styles for each component.

As for the style component scoping, I want to be able to build components that explicitly do not use the CSS shimming (mainly for performance reasons). I plan on building styles for components that will work both in native and emulated shadow DOM modes.

> When we have such rules it would not be possible to share styles (ie different components could have different primaryColor.

I left out some background here- the whole point of this is to build components that all have the *same* primary color. This is coming from the way Material Design prescribes [selecting a palette](http://www.google.com/design/spec/style/color.html#color-ui-color-application): you choose a primary color, an accent color, and lighter/darker hues of each. The rest of the colors are determined by this choice. This palette affects every material component.

**Comment by jelbourn** [comment]
Had some further conversion w/ Misko about this, have a different idea for moving forward that should work with what's currently in place.
