### ISSUE TITLE
Thoughts about adding CanReuse to RouteDefinition

### ISSUE THREAD

**Issue by iDev0urer** [angular/angular#7797]
It would be nice if we could define that a route should be reusable on the RouteDefinition rather than just in the route's class.

**Current behavior**

```typescript
// RouteConfig has no parameter for the CanReuse option.
@RouteConfig([
	{ path: '/', name: 'ProductTable', component: ProductTable, useAsDefault: true },
	{ path: '/add-product', name: 'AddProduct', component: AddProduct }
])
...
// It instead has to be defined in the controller as a method
export class ProductTable {
    constructor() {}

    routerCanReuse(next: ComponentInstruction, prev: ComponentInstruction) { return true; }
}
```

Seems like some unnecessary typing as well as not being very intuitive, at least in my opinion. This is not to say that the method should be removed, but a simple boolean option on the RouteDefinition would be nice.

**Comment by zoechi** [comment]
#7784 seems related. The title is about `routerCanActivate` but the discussion is a lot about `canReuse`

**Comment by zoechi** [comment]
dup of #9811
