### ISSUE TITLE
code style: multiple imports allowed from same module

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#7802]
We have a handful of files which do this:
```
import {a,b} from 'angular2/module';
...
import {c} from 'angular2/module';
```

Ideally we should tidy this up.
It also affects downstream tooling (see b/27877430 for motivation)

**Comment by alexcastillo** [comment]
Hey @alexeagle 

I took a pass at this. Let me know if PR #8209 is sufficient.

**Comment by alexeagle** [comment]
Now we need to add the lint check to prevent it happening more.

**Comment by alexeagle** [comment]
the lint check is live on circleci.
