### ISSUE TITLE
Feature: Improve router serializer API and make it more general

### ISSUE THREAD

**Issue by naomiblack** [angular/angular#7803]
Placeholder -- needs team discussion after final 2.0 ships.

see https://github.com/angular/angular/issues/7531for an example of a use case we are missing.

**Comment by IgorMinar** [comment]
This issue was made obsolete by router v3: https://angularjs.blogspot.com/2016/06/improvements-coming-for-routing-in.html

If you believe this is not the case, please file a new issue updating the description to router v3. thank you!
