### ISSUE TITLE
BrowserDomAdapter querySelector should be return dom when selector is dom

### ISSUE THREAD

**Issue by xsilen** [angular/angular#7805]
**Current behavior**
http://plnkr.co/edit/aRHZKYWUh6u1McC4NNxb?p=preview
when DCL.loadAsRoot work in ngFor, it's no need to transform dom to a `selector`, BrowserDomAdapter.querySelector should return dom directly
**Expected/desired behavior**
```
https://github.com/angular/angular/blob/master/modules/angular2/src/platform/browser/browser_adapter.ts#L98-L100
query(selector: any): any {
    if (selector instanceof HTMLElement) return selector;
    if (isString(selector)) return <HTMLElement>document.querySelector(selector);
    return null;
  }
  querySelector(el, selector: any): HTMLElement {
    if (selector instanceof HTMLElement) return selector;
    if (isString(selector)) return <HTMLElement>el.querySelector(selector);
    return null;
  }
  querySelectorAll(el, selector: any): any[] {
    if (selector instanceof HTMLElement) return selector;
    if (isString(selector)) return <HTMLElement>el.querySelectorAll(selector);
    return null;
  }
```
**Other information**
I think this change maybe make it different from standard. so how to do

**Comment by micronyks** [comment]
Its yet not clear what you are trying to say as (may be) your plunker code is not working upto the mark. Can you elaborate more?

**Comment by xsilen** [comment]
Problem: 
```typescript
DynamicComponentLoader.loadAsRoot(type: Type, overrideSelector: string, injector: Injector, onDispose?: () => void, projectableNodes?: any[][])
```

I want use dom directly instead of param `overrideSelector` string.

**Comment by micronyks** [comment]
Yes definition says `overrideSelector:string` , overrideSelector should be type of `string` which defines entry/injection point for the dynamic component. 
check this ---> http://plnkr.co/edit/hcfGuo7gTMIcqJKlXGTc?p=preview

Buy in your case `this.child.nativeElement` will returns whole DOM object. That being said, new question will arise  -  where will you inject your dynamic component using `loadAsRoot`?
Or what will be an entry/Inject point?

**Comment by zoechi** [comment]
@xsilen looks like closing the issue was not intended.

**Comment by xsilen** [comment]
I need to find a better solution. before that i don't want to trouble angular.
