### ISSUE TITLE
Hello World Error Angular2

### ISSUE THREAD

**Issue by Rian0702** [angular/angular#7808]
i recently did [this ](http://www.mithunvp.com/angular-2-in-asp-net-5-typescript-visual-studio-2015/)tutorial and i did the [Hero Editor](https://angular.io/docs/ts/latest/tutorial/toh-pt1.html) from Angular too. My Problem now is, everytime i go to "localhost:123/dashboard" my Chrome browser just displays "Hello World" ("localhost:123" works fine). Same happens if i try to debug the scripts with Chrome.

I Uploaded my Code to [here](https://github.com/Rian0702/AngularAdventure):

**Comment by zoechi** [comment]
Your code link is broken.

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by pkozlowski-opensource** [comment]
Thnx @zoechi !
