### ISSUE TITLE
CanActivate not called on root component.

### ISSUE THREAD

**Issue by thso** [angular/angular#7810]
I'm using the Dart version.

Provided function for `@CanActivate` on a root component is never called. I would expect this to work and the rendering to be delayed until either the function returns or the returned future completes.

**Comment by brandonroberts** [comment]
The root component isn't considered to be a routable component. If you wanted to achieve this, you should use your root component as an outlet and move your routes down a level and use CanActivate there.

```js
@Component({
    template: '<router-outlet></router-outlet>'
})
@RouteConfig([
    { path: '/...', component: MainComponent, name: 'Index' }
])
class AppComponent {}

@RouteConfig([...])
@CanActivate(...)
class MainComponent{}
```

**Comment by thso** [comment]
If this is going to stay, could there be a warning when `@CanActivate` is
used on the root component?

**Comment by CaptainCodeman** [comment]
What are you actually trying to achieve? There may be another approach that is more appropriate than CanActivate.

**Comment by thso** [comment]
Re-route the user to another application if some condition is met.

**Comment by CaptainCodeman** [comment]
It depends on the condition and where it comes from but some options are to do it before the bootstrap or in an asyncApplication init as part of the bootstrap or just within the service or constructor for the app component (using the service if that what provides the check).

**Comment by thso** [comment]
Good suggestions, will look into that.

Some more context: The data comes from a request and I need quite a few
services to build up the deps of the service that makes the request, say
about 20. Additionally these should be singletons at the top level of the
app, I don't want these to be recreated later on if the check decides not
to re-route the user.

**Comment by brandonroberts** [comment]
You could also hide your router-outlet in your main component until you finish your check if you don't want to use CanActivate since DI doesn't exist inside CanActivate yet.

**Comment by thso** [comment]
That sound like the best solution actually, thanks!

**Comment by thso** [comment]
Still insisting that we should show a warning if @CanActivate is used on
the root component :p

**Comment by brandonroberts** [comment]
@thso its a valid reason, but I'm just saying it would be very low on the priority list.

**Comment by virtualvoid** [comment]
@brandonroberts now imagine someone like me who just spent 2hours trying to figure out why isn't CanActivate called on root component (e.g. checking if user is authenticated). 

then think again with that 'very low on priority list'.

thanks

**Comment by vicb** [comment]
obsolete
