### ISSUE TITLE
Improve AsyncPipe invalid argument error message

### ISSUE THREAD

**Issue by eppsilon** [angular/angular#7811]
http://plnkr.co/edit/OYkkkCrbj0zSMv19tmfw?p=preview

Currently if you pass some non-async value to an `AsyncPipe`, you get an error like this:

```
EXCEPTION: Invalid argument '1,2,3' for pipe 'AsyncPipe' in [someArray | async in App@9:12]
```

If the value happens to be an array of objects, it might be less clear:

```
EXCEPTION: Invalid argument ',,,,,,' for pipe 'AsyncPipe' in [someArray | async in App@9:12]
```

It would be helpful if the message said something like:

```
EXCEPTION: Invalid argument for pipe 'AsyncPipe' - argument must be an async (Observable/Promise) object in [someArray | async in App@9:12]
```

**Comment by vicb** [comment]
fixed in 2.0
