### ISSUE TITLE
Protractor testing with an application in "worker mod"

### ISSUE THREAD

**Issue by JonathanDaSilva** [angular/angular#7812]
Hi everyone.
I have an angular2 that I want to convert to "worker mod", everything is fine except for my test with protractor.

From what I'm understading protractor is using some global functions/variables that seems to not be available.

 "getAllAngularRootElements" is not available for exemple.

I have made a realy simple [angular2 application](https://jonathandasilva.github.io/demo-worker-angular-bug/)

You can see the code that i'm using [here](https://github.com/JonathanDaSilva/demo-worker-angular-bug).

Hope I'm clear otherwise feel free to ask anything.

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
