### ISSUE TITLE
Typo on Architecture Page

### ISSUE THREAD

**Issue by writex** [angular/angular#7816]
https://angular.io/docs/ts/latest/guide/architecture.html

Not: Modules export things — classes, function, values — that other modules import.
But: Modules export things — classes, functions, values — that other modules import.

Also should interfaces be added to that list?

**Comment by gdi2290** [comment]
can you create a pull-request?

**Comment by pkozlowski-opensource** [comment]
This belongs to https://github.com/angular/angular.io
