### ISSUE TITLE
Router/Interfaces API docs show `<boolean>` instead of `Promise<boolean>`

### ISSUE THREAD

**Issue by wardbell** [angular/angular#7819]
Reported in [angular.io issues #1008](https://github.com/angular/angular.io/issues/1008)
---
@zoechi: 

docs https://angular.io/docs/ts/latest/api/router/CanDeactivate-interface.html

source https://github.com/angular/angular/blob/2.0.0-beta.12/modules/angular2/src/router/interfaces.ts#L123

@Foxandxss:
I debugged it. The problem is that we generate our API based on the angular source and you can see:

![](http://puu.sh/nUOhd/172ea86137.png)

Notice the `Promise<boolean>` indentation.

Then that will generate:

![](http://puu.sh/nUOjT/5febb327cc.png)

What my editor marks as blue would be interpreted as `Jade` syntax and the white part will be printed out. Due how Jade works (indentation based) it will interpret the `Promise` as syntax and never print it out.

@wardbell What should we do here? Can be fixed in our side?

@wardbell:
Easiest thing to do is reformat the signature in angular/angular. I'll do that and make a PR

---

This issue goes with PR #7820

**Comment by vicb** [comment]
obsolete
