### ISSUE TITLE
ngModel appears to have issues with typing fast, or moving the cursor in a textarea or text input

### ISSUE THREAD

**Issue by tylerchurch** [angular/angular#7822]
**Steps to reproduce and a minimal demo of the problem**

Minimal demo of the problem: http://plnkr.co/edit/ddXKPITqdaSl15hZjvxz

_What steps should we try in your demo to see the problem?_

1. Type quickly in the textarea, you may see characters get dropped or otherwise, presumably as Angular's change-detection cycle kicks in and resets the content to what it thinks the current content is, despite the new characters you've typed. Just from normal typing this doesn't always happen, so proceed to step 2 if you don't see the issue.
2. Try typing and then using the arrow keys to go back a few characters and correct something. Or hit the Home button to go to the beginning of the line. Or copy/paste something. You should see your cursor jump to the end of the input when you're not expecting it, or what you type might not make it in.

Here's a GIF showing what I mean: ![angular 2 bug gif](https://cloud.githubusercontent.com/assets/2380817/14125357/a5f1739e-f5bf-11e5-9a75-698ebadbc191.gif)

In that GIF I:

1. Typed 1s and 2s for a while.
2. Used the arrow keys go back a few characters
3. Started typing different characters.

In the GIF you should be able to see that the cursor jump to the end, that was not me, Angular was doing that.

**Current behavior**

ngModel appears to be replacing the content of the textarea with an older version of the contents of the textarea while the user is still typing in the input.

**Expected/desired behavior**

Text should remain as the user typed it.

**Other information**

I've tested with:

- Chrome 49.0.2623.110
- Firefox 44.0.2
- Angular 2.0.0-beta.3
- Angular 2.0.0-beta.12
- All on Windows 10 x64 (I haven't tested on Mac or Linux, but can if requested)

I've searched for related issues through Google and GitHub issues and haven't been able to find anybody seeing anything like this, but one of my coworkers has confirmed seeing the same thing, so I don't think I'm going crazy :stuck_out_tongue: 

For now the workaround seems pretty easy: Use native DOM access or jQuery instead of ngModel, but this feels really unfortunate. I can't reproduce this issue with Angular 1.

**Comment by ericmartinezr** [comment]
See if this issue is related to yours https://github.com/angular/angular/issues/5808

**Comment by tylerchurch** [comment]
Yep, seems very much related. From reading that issue it looks like this is probably the root cause: https://github.com/angular/angular/issues/6311 I will go upvote that.

**Comment by tylerchurch** [comment]
I wanted to clarify for anyone reading this: what I wrote above makes it sound like this is just an edge case where you have to type really fast, but that was only for ease of reproducing the issue.

We are seeing this quite often just in the normal use of a complex Angular 2 app that we've been building.

**Comment by fdelayen** [comment]
Same here, it's clearly not an edge case.
As your app grows a little bit, it's really usual to see this.

**Comment by Kilhog** [comment]
Some issue with me in a Ionic2 app, the effect is amplified with the use of "ion-input" component, but the effect are always there with a simple input [(ngModel)].
Plunker : http://plnkr.co/edit/yoYEOn6P4dnS31AMECKC?p=preview

**Comment by bensgroi** [comment]
I'm seeing this "cursor jump to the end" issue pretty reliably on a moderately complex app. This is a pretty serious bug, as it renders it nearly impossible to edit long textareas. We had a user trying to use the app, and after several attempts at editing text where the cursor repeatedly jump to the end, she gave up in frustration.

**Comment by mengxiw** [comment]
Same as @Kilhog 
Also has this input bug in Ionic2 app. The error happen when I use Protractor to test login page. Each time when I used 'sendKeys', both number or character will missing.
**Code**
```
<ion-input id="userName11" [(ngModel)]="login.username" ngControl="username1" type="number" #username1="ngForm" required>
</ion-input>
<ion-input [(ngModel)]="login.password" ngControl="password1" type="password" #password1="ngForm" id="passWord11" required>
</ion-input>
```
**Test code**
```
browser.sleep(1500);
usern.sendKeys('12345');
browser.sleep(500);
passw.sendKeys('1234');
expect(usern.getAttribute("value")).toEqual("12345");
expect(passw.getAttribute("value")).toEqual("1234");
browser.sleep(500);
usern.clear();
browser.sleep(1500);
usern.sendKeys('78475');
expect(usern.getAttribute("value")).toEqual("78475");
```
**Failures**
```
 - Expected '145' to equal '12345'.
 - Expected '745' to equal '78475'.
```

**Comment by zoechi** [comment]
I can't reproduce with RC.4 http://plnkr.co/edit/1cL5xFJLKFzjjCE9zr3p?p=preview
