### ISSUE TITLE
NgModel - No value accessor for ''

### ISSUE THREAD

**Issue by rascada** [angular/angular#7823]
NgModel don't work in [webpackbin](http://www.webpackbin.com/)
## exception
`No value accessor for '' in title`

## demo
[angular2 webpackbin demo](http://www.webpackbin.com/4kwi20X0g)

**Comment by ericmartinezr** [comment]
@rascada could you reproduce it in a plnkr? Although I would say it's because of minification which has been broken since beta.1. Try adding `mangle:false` to your uglify plugin.

**Comment by rascada** [comment]
Problem is everywhere it work ([ng2-webpack](https://github.com/rascada/ng2-webpack) - webpack reproduction, same as in [bin](http://www.webpackbin.com/4kwi20X0g)) excluding [webpackbin](http://www.webpackbin.com/) (I'm not author)

**Comment by christianalfoni** [comment]
Hi guys,

Webpack uglifyplugin mangles by default, so let me try turning this off on webpackbin :-) Let you know how it goes!

**Comment by christianalfoni** [comment]
woop woop, now it works. Thanks @ericmartinezr :-)
