### ISSUE TITLE
Update quick start to use rxjs 5.0.0-beta.3

### ISSUE THREAD

**Issue by CodeJason** [angular/angular#7826]
I recently experienced really long compile times  which would always crash due to a memory error.
I could get around the problem by using  --max_old_space_size option with node but would still take 20 seconds or longer. 
Someone tracked the issue down to memory leaks in RXJS and it seems the issue was solved in 5.0.0-beta.3.
https://github.com/mgechev/angular2-seed/issues/259#issuecomment-199553493

**Comment by gdi2290** [comment]
rxjs beta.4

**Comment by CodeJason** [comment]
@gdi2290 Thanks, didn't check recently

**Comment by Ristaaf** [comment]
#7719

**Comment by Mc-Mido** [comment]
I have the same issue with throw method on Observable, i.e:
`return Observable.throw(error || 'Server error');`

lead to compilation performance issue and node.exe seems to be stuck just after compiling _ts_ file with this code.

Is there any workaround until angular2 switch rxjs version to 5.0.0-beta.4 ?

**Comment by CodeJason** [comment]
Even though there are errors that pop up, updating to beta.3 still works for me. Before updating, I was using
node --max-old-space-size=3000 ./node_modules/typescript/bin/tsc
To do the job.

**Comment by pkozlowski-opensource** [comment]
Updated to beta.6 via b62bccf25488a887cf0c51eeaf16adbdaa0a43eb.
