### ISSUE TITLE
Enable @Input and @Output on routed components

### ISSUE THREAD

**Issue by cquillen2003** [angular/angular#7827]
Routed components are sorely lacking @Input variables and @Output events IMO.  Can these be added so that Angular 2 components are de-coupled from how they are mounted in the DOM?

Writing (and using) a component via its custom tag vs. @RouteConfig({ ... component: MyComponent }) should be nearly identical.

**Comment by fxck** [comment]
see https://github.com/angular/angular/issues/7784

**Comment by vicb** [comment]
obsolete
