### ISSUE TITLE
Is it possible to create something like [attr.name] using Directive?

### ISSUE THREAD

**Issue by esugoi** [angular/angular#7830]
I would like to create a Directive that would behave like the [attr.name] binding. I've searched the source code for it, but as far as I understood, this binding is something done during the template compilation process.
So, my question is if I can create a Directive something like:
[bind.attributename]="value"

And inside the Directive, obtain the 'attributename' and 'value' content. Is it possible and how?

**Comment by zoechi** [comment]
You can't introduce a new `[xxx.yyy]` prefix but if you provide more information it might be possible there is another solution that works as well (or close)

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by esugoi** [comment]
Hello @zoechi , thanks for answering.
Well, what I wanted to do was really something similar to `[attr.name]`. But, instead of passing the property source as a value, I would pass an expression that would be resolved at runtime. This would create a binding using another binding source mechanism that is related to the framework I am working on.

**Comment by zoechi** [comment]
That should be possible with a simple directive. Your explanation is to abstract to give concrete advice

**Comment by esugoi** [comment]
Well, an example would be. Having this component:
```
@Component({ selector: 'foo', template: '' })
export class FooComponent {
  @Input() property: string;
  constructor() { }
}
```

I would like to create a binding of my own like this:
```
<component [bind.property]="path/to/my/resource">
</component>
```

I was hoping that I could create a Directive to do this, like:
```
@Directive({ selector: 'bind.*' }
export class BindDirective implements OnInit {
  constructor(/* obtain 'property' and 'value' somehow */) {
  }

  ngOnInit(): void {
    /* resolve and create binding on 'path/to/my/resource' */
  }
}
```

**Comment by zoechi** [comment]
I see. So what you want is something like a dynamic input name. Not entirely sure but I'd say that is not possible. It should work with two inputs though where one gets the value and the other the name like

```html
<component [myProperty]="someName [value]="path/to/my/resource"></component>
```
```ts
@Directive({ selector: '[myProperty]' }
export class BindDirective implements OnInit {
  @Input() myProperty;
  @Input() value;
  ngOnInit(): void {
    console.log(this.myProperty + ' - ' + this.value);
  }
}
```

**Comment by esugoi** [comment]
Thanks for the quick answer, @zoechi :)
Well, I was thinking about something like your example. But what if I wanted to bind to multiple properties, can I use this directive multiple times on the same component?

```
<component [myProperty]="property1" [value]="path/to/my/resource1"
           [myProperty]="property2" [value]="path/to/my/resource2">
</component>
```

**Comment by zoechi** [comment]
I'll leave this for the Angular team to answer. I'm in favor of simple questions ;-)

**Comment by robwormald** [comment]
no, i don't think this is possible, as it breaks all kinds of static analyzation guarantees. why not pass an object or an array?

**Comment by esugoi** [comment]
Thanks, @robwormald 
You mean something like:
```
<component [myProperties]="['prop1', 'prop2', 'prop3']" [myValues]="['resource1', 'resource2', 'resource3']">
</component>
```

Never tried that...

**Comment by pkozlowski-opensource** [comment]
Or `<component [bindings]="{prop1: 'resource1', prop2: 'resource2'}">`.

FYI it is not possible to "extend" `[foo.bar]` syntax as it is part of the compiler. And as noted by @robwormald introducing such dynamic syntax would break ability to statically reason about templates.
