### ISSUE TITLE
matchUrlSegment regexp wrong

### ISSUE THREAD

**Issue by tamascsaba** [angular/angular#7831]
https://github.com/angular/angular/blob/75343eb34007579be9cdc803da834c38e02ae12c/modules/angular2/src/router/url_parser.ts#L82-L86

I have an valid url:
http://localhost:8080/#/foo?q=bar%3A(foo%20bar)

I pasted to browser URL bar, but angular matchUrlSegment sliced at the first bracket and pushState wrong url to browser bar (after initialize Instruction):

http://localhost:8080/#/foo?q=bar%3A

**Comment by tamascsaba** [comment]
@btford ??

**Comment by vicb** [comment]
obsolete - former router
