### ISSUE TITLE
*ngFor conditional component

### ISSUE THREAD

**Issue by elijahiuu** [angular/angular#7832]
I want to have different component types render within a *ngFor loop. I want to target those components with child component's selector (using classes) to narrowly target the "concrete" child implementation: like this:
```
<div *ngFor="#a of arr">
      <child class="foo"></child>  ---this works
      <child [attr.class]="cls">**DID NOT RENDER**</child> --- this doesn't work
    </div>

cls = 'foo';
```
[http://plnkr.co/edit/YeCCY4JJsjZeMEId5oWJ](http://plnkr.co/edit/YeCCY4JJsjZeMEId5oWJ)

I am having problems with dynamic classes: [attr.class]. it doesn't render that child component. Vs if I statically hard code class="foo", which does work. 

Is this working as designed? Or is this an ngFor directive deficiency?  

running version: 2.0.0-beta.12

**Comment by esugoi** [comment]
Maybe I understood this wrong, but what you want to achieve could be this?
`<div *ngFor="#a of arr">
  <child class="foo"></child>  ---this works
  <child [attr.class]="**a.**cls">**DID NOT RENDER**</child> --- this doesn't work
</div>`

Then the cls property should be on the array element instance...

**Comment by elijahiuu** [comment]
i want *ngFor to dynamically stamp out different types of components, without doing any ngIf, ngSwitch, but simply relying on child's selector to do it's job. 

If i was to rewrite this with ngIf, same idea but less elegant:
```
<div *ngFor="#a of arr">
   <child-one *ngIf="a.type == 'ONE'></child-one>
   <child-two *ngIf="a.type == 'TWO'></child-two>
</div>
```
which unfortunately throws exception: `angular2.min.js:17 EXCEPTION: TypeError: this.directive_0_0.ngDoCheck is not a function in [arr in App@2:9]`

[http://plnkr.co/edit/iJwIcl](http://plnkr.co/edit/iJwIcl)

**Comment by ericmartinezr** [comment]
@elijahuu it works fine with unminified bundles. Can also you please move your questions to [gitter's chatroom](https://gitter.im/angular/angular), StackOverflow or similar? The error message you see now is a bug reported long time ago, but your original issue is a question, and github is not the place for them.

**Comment by michalstepien** [comment]
Can we close?

**Comment by pkozlowski-opensource** [comment]
Thnx @michalstepien
