### ISSUE TITLE
DynamicComponentLoader load component within structural directive

### ISSUE THREAD

**Issue by Munhoziii** [angular/angular#7835]
_What steps should we try in your demo to see the problem?_

**Current behavior**
The DynamicComponentLoader is unable to instantiate a new component that should be attached to a DOM node within a structural directive (ngIf, ngFor).

**Expected/desired behavior**
DynamicComponentLoader should be able to attach components inside portions of the template/DOM/page surrounded by structural directives (ngIf, ngFor)

**Other information**
Plunker: https://plnkr.co/edit/PjYZjaZfvtXfo53tsgs1?p=preview
If you remove the ngIf directive everything works fine, but that doesn't account for the cases when structural conditionals or loops are needed to generate the desired structure.

If you run the plunker and look in your console you can see the exception and how it fails.

**Comment by zoechi** [comment]
You can create a helper component just for inserting a component using DCL inside itself:

```html
<div *ngFor="#item in items>
  <dcl-helper [component]="item.component"></dcl-helper>
</div>
```

**Comment by pkozlowski-opensource** [comment]
`DynamicComponentLoader` is deprecated. I'm not aware of any limitations of new APIs (ComponentFactory + ViewContainerRef) in respect to structural directives so I'm going to close this one for now. But if you can update your plunk to rc1 I could surely have a look.
