### ISSUE TITLE
Suggestion: Typed get for Injector

### ISSUE THREAD

**Issue by chuckjaz** [angular/angular#7836]
The `Injector.get` method returns type of `any` but it could be overloaded to provide more type information. For example, consider the following overload:

```typescript
get<R>(token: { new (...args: any[]): R}): R;
```

This implies that passing any class will return an instance of that class such as:

```typescript
var injector: Injector;
class Foo {}
var foo = injector.get(Foo);
```

The inferred type of `foo` is `Foo`.

This technique can be extended to handle arbitrary token values, not just classes, by introduce a typed token:

```typescript
get(token: TypedToken<R>): R;
```

where the `TypedToken<R>` type is something like:

```typescript
interface TypedToken<R>{}
```

A token for the `Foo` type above would look like:

```typescript
var fooToken = "foo token" as TypedToken<string>;
var foo = injector.get(fooToken);
```

Here the inferred type of `foo` is also `Foo`.

```typescript
var someNumber = "someNumber" as TypedToken<number>;
var n = injector.get(someNumber);
```

Here the type of `n` is inferred to be `number`.

**Comment by laco0416** [comment]
I agree your idea about typed-get. but I doubt a necessary of `TypedToken`.

Seemingly `TypedToken` is a typed `OpaqueToken` ?
I think `OpaqueToken<T>` is better than it because adding a new API makes users wondering about what they should use which API.

**Comment by chuckjaz** [comment]
Decision: The change is not justified because 1) calling `get` directly is discouraged 2) offline complilation makes calling `get` unnecessary in most cases. Making calling `get` more convenient would lead users down the wrong path as it might look like they should be calling it directly.
