### ISSUE TITLE
Loading Parent Component's Child Routes Dynamically (default route issue)

### ISSUE THREAD

**Issue by pratikthecook** [angular/angular#7847]
I am trying to add a certain parent components Routes from a service dyanmically using the `Router.config(RouteDefinition[]).` The issue here is that since a parent component Must have a default `component(useAsDefault or [routerLink] = "['Parent','Child1']"` and due to this i am unable to add the default route to the route definition array and configure it in working mode. The same behaviour works if i hard code the default route and then dynamically load routes from a service.

**Current behavior**
My bootstrapped component routes
```
@RouteConfig([
    {path : '/home' , name : 'Home' , component : HomeComponent , useAsDefault : true},
    {path : '/dash/...' , name: 'Dash' , component : DashBoard}
])
```

// Now all child routes of DashBoard must come from a service(Not Working)
Following is the DashBoard Component

```
@Component({
    directives : [ROUTER_DIRECTIVES],
    template : `<h3>{{componentName}}</h3>

                <nav>
                    <ul>
                        <!--<li><a [routerLink]="['Child1']">Child 1</a></li>                    &lt;!&ndash;
                        <!--<li><a [routerLink]="['Child2']">Child 2</a></li>&ndash;&gt;-->
                        <div *ngIf="routesReady">
                            <a *ngFor="#router of routerView" [routerLink]="[router.name]">{{router.name}}</a>
                        </div>
                    </ul>
                </nav>

                <router-outlet></router-outlet>`,
    providers : [MenuService]
})

/*
 @RouteConfig([
 {path : '/child1' , name : 'Child1' , component : ChildComponent1, useAsDefault: true},  //
 {path : '/child2' , name : 'Child2' , component : ChildComponent2, useAsDefault: false}
 ])*/

export class DashBoard{
    componentName : string;

    routesReady : boolean;
    routerView : any[];

    constructor(private _router : Router, private menuServ : MenuService){
        console.log(" Dashboard Init");
        this.componentName = 'Parent Route';

        this.routerView = [];
        this.routesReady = false;

        this.menuServ.loadMenuStructure(this,_router);
    }
}

```
Here the Console says 

> Component "DashBoard" has no route config.

Now i figured this might be issue where upon the click of user that navigates, at that time the routes might not be configured, so i shifted the code to configure routes dynamically to the bootstrapped Component but then in this case it conflicts and says only one route can be set as default route .i.e it sets the route not on parent but on a level above.

Hope the issue is clear.
thanks

**Comment by vsavkin** [comment]
We are no longer maintaining the deprecated router to focus our efforts on making the new router solid.

The new router supports this functionality.

Closing this issue.
