### ISSUE TITLE
outerHTML does not include the identifier for viewEncapsulation

### ISSUE THREAD

**Issue by oscarlopez1616** [angular/angular#7848]
Is there some fancy way to make the outerHtml output includes the viewEncapsulation identifiers?

In a default ViewEncapsulation component where the output html before oterHTML processing is:

```
<div  _ngcontent-pcc-16>
     <span [outerHTML]="menuHtml"></span>
</div>
```

and where:

`menuHtml="<p>Hello</p>"`

The result should be something like:

```
<div _ngcontent-pcc-16>
   <p _ngcontent-pcc-16 >Hello</p>
</div>
```

Instead, Angular2 is showing:

```
<div _ngcontent-pcc-16>
   <p >Hello</p>
</div>
```

The solution I found is adding the identifier by myself like this:

`this.myRenderer.selectRootElement("span").attributes[0].nodeName`

**Comment by DzmitryShylovich** [comment]
@oscarlopez1616 is this still relevant? can you please add the plunkr that illustrates the issue? thanks
