### ISSUE TITLE
[beta.13] Incorrectly closed tag throws Cannot set property endSourceSpan of null

### ISSUE THREAD

**Issue by ericmartinezr** [angular/angular#7849]
_What steps should we try in your demo to see the problem?_

Take a look at this plnkr http://plnkr.co/edit/GMMWZ3xVkcGsqlg9m11a?p=preview 

The plnkr is using beta 13, to see the correct error message change the version to beta 12 in index.html

Consider this template

```
template : '<div</div>'
```

Note that I missed a closing tag for div

**Current behavior**

Beta 13 throws the following error

```
EXCEPTION: TypeError: Cannot set property 'endSourceSpan' of null
```

**Expected/desired behavior**

Works like beta 12 did throwing this error

```
Unexpected closing tag "div" ("<div[ERROR ->]</div>"): App@0:4
```

**Other information**

**Comment by ericmartinezr** [comment]
Havin this template, with a child node the message is a little bit more clear but unacurrate

```
template: <div<li></li></div> // I missed closing the starting div tag
```
Throws
```
// Makes no sense, <li> is correctly closed
Unexpected closing tag "li" ("<div<li>[ERROR ->]</li></div>"): App@0:8

// Makes sense! But the error message is not where it should be
Unexpected closing tag "div" ("<div<li></li>[ERROR ->]</div>"): App@0:13  
```

**Comment by bananenmannfrau** [comment]
The uncaught error happens in `angular2/src/compiler/html_parser.ts`

where `this._getParentElement()` is undefined in the function `_consumeEndTag`

Replacing 
    `this._getParentElement().endSourceSpan = endTagToken.sourceSpan;`
with
```
if(!this._getParentElement() ){
  this.errors.push(HtmlTreeError.create(fullName, endTagToken.sourceSpan, "Unexpected closing tag \"" + endTagToken.parts[1] + "\""));
}
else{
  this._getParentElement().endSourceSpan = endTagToken.sourceSpan;
}
```
created a better and clearer error message.

**Comment by VsMaX** [comment]
Same still happening to me on 2.0.0-rc.1. When you have too many closing tags this might happen. Only because of this issue I was able to quickly fix the real problem.

**Comment by RolfVeinoeSorensen** [comment]
I am using umd so I had to alter compiler.umd.js with the fix suggested by bananenmannfrau

**Comment by ericmartinezr** [comment]
@bananenmannfrau what about sending a PR? :D It would be nice to have this fixed by the next RC
