### ISSUE TITLE
Invalid twitter and webiste url on about us page

### ISSUE THREAD

**Issue by nned** [angular/angular#7850]
https://angular.io/about/

Jules Kremer's info has invalid twitter and webiste urls :
https://twitter.com/undefined
https://angular.io/about/undefined

**Comment by kara** [comment]
Can you refile in the angular.io repo?  :)

https://github.com/angular/angular.io

**Comment by nned** [comment]
Oh, I see. Thanks, Kara) 
Sorry for creating issue in wrong repo)
