### ISSUE TITLE
ComponentRouter displays a false error message

### ISSUE THREAD

**Issue by Duskdown** [angular/angular#7851]
If you define the name of a route in CamelCase you get the following error message from the ComponentRouter:

> Route "/:isbn" with name "bookDetail" does not begin with an uppercase letter. Route names should be CamelCase like "BookDetail".

Correct would be
> Route "/:isbn" with name "bookDetail" does not begin with an uppercase letter. Route names should be **PascalCase** like "BookDetail".

**Comment by laco0416** [comment]
"camel case" includes two formats, "lowerCamelCase" and "UpperCamelCase". the later is also called "PascalCase".

I think it's not false, but may be misleading.

**Comment by vicb** [comment]
obsolete
