### ISSUE TITLE
angular_1_router Access the active route name array or similar from somewhere...

### ISSUE THREAD

**Issue by stnor** [angular/angular#7853]
I cannot find a way to access the RouteConfig name from a child component's router nor the ComponentInstruction passed to $routerOnActivate. There is no such information exposed in the rootRouter either from what I can see.

The use case is:
/students/123/overview
/students/123/report

There is a tab for 'overview', 'reports' and a dropdown to change the student (123) to another student.

App:
```
    $routeConfig: [
      {path: '/students/...', component: 'students', name: 'Students'},
      ....
```

StudentsComponent:
```
    $routeConfig: [
      {path: '/:id/...', component: 'student', name: 'Student'},
      ....
```

StudentComponent:
```
    $routeConfig: [
      {path: '/overview', component: 'studentOverview', name: 'StudentOverview'},
      {path: '/report', component: 'studentReport', name: 'StudentReport'}
```

In the StudentComponent's controller I bound the $router and would like to navigate to another student (but keep the last part of the url intact).

I currently have:
```
   vm.changeStudent = function (id, event) {
      if (event) event.preventDefault();

       function capitalizeFirstLetter(string) {
        return string.charAt(0).toUpperCase() + string.slice(1);
      }

      var lastPartOfUrl = $location.path().split('/').slice(-1)[0];

      this.$router.navigate(['/Students', 'Student', {id: id}, 'Student' + capitalizeFirstLetter(lastPartOfUrl)]);
    }
```

Surely there must be a way to solve this use-case with the existing implementation other than looking at $location and mapping it to route names?

Ideally, one would like to do **this.$router.routeCurrentWithNewParams({id: id})** and the rest of the hierarchy would stay as is...

**Comment by vicb** [comment]
obsolete
