### ISSUE TITLE
DynamicComponentLoader not respecting promise execution order when loading multiple instances of same components

### ISSUE THREAD

**Issue by hitmanmcc** [angular/angular#7854]
**Steps to reproduce and a minimal demo of the problem**
Just run the demo over on my plnkr:
[DCL rendering order demo](http://plnkr.co/edit/LHi2UPV59hBMo3mKIbSN)

**Current behavior**
I setup a plunkr with a demo that shows an angular2-beta.13 app dynamically loading a component list with 3 different component types.
The first list just has components 1, 2 and 3 loaded in order and it works fine.
The second list has components 1, 2 and 3 listed to be loaded more than once and the order is the following: 1, 2, 3, 2, 3, 1. However, they get loaded as 1, 1, 2, 2, 3, 3.

**This is what the app renders:**
```HTML
list.json order is: 1, 2, 3 
DynamicComponentLoader output:
I'm widget 1
I'm widget 2
I'm widget 3

list2.json order is: 1, 2, 3, 2, 3, 1 
DynamicComponentLoader output:
I'm widget 1
I'm widget 1
I'm widget 2
I'm widget 2
I'm widget 3
I'm widget 3
```

**Expected/desired behavior**
The loading is being done by resolving an array of promises which have the correct order so I would expect components to be dynamically loaded onto the screen by the order I've set, which is 1, 2, 3, 2, 3, 1.

**This is what the app should render:**
```HTML
list.json order is: 1, 2, 3 
DynamicComponentLoader output:
I'm widget 1
I'm widget 2
I'm widget 3

list2.json order is: 1, 2, 3, 2, 3, 1 
DynamicComponentLoader output:
I'm widget 1
I'm widget 2
I'm widget 3
I'm widget 2
I'm widget 3
I'm widget 1
```

**Comment by zoechi** [comment]
Looks like a dup of #6920

**Comment by hitmanmcc** [comment]
@zoechi Indeed, upon analysis, I can see that it is the same issue in fact.
Nevertheless, I had a discussion with @tbragaf and he found a workaround for the issue which can be seen over on this plnkr:
[DCL rendering order workaround demo](http://plnkr.co/edit/ldcI7l3Hs7Ez0hWGN0cm)

**Comment by zoechi** [comment]
Looks like http://stackoverflow.com/questions/20100245/how-can-i-execute-array-of-promises-in-sequential-order
Just a way to properly process async tasks sequentially.  
So this "bug" is actually about DCLs `loadIntoLocation` being async?

**Comment by hitmanmcc** [comment]
Yes, in fact it would seem so. When you pointed out that it was a dupe of another issue I ran some further testing and then I ran into the race condition/cache aspect of the problem described in that issue. Where for instance if the first list's order was:
1, 3, 2
 
then the second list would be rendered as:
1, 1, 3, 3, 2, 2 instead of 1, 1, 2, 2, 3, 3.
