### ISSUE TITLE
ViewEncapsulation.Native errors in (Safari Technical Preview)

### ISSUE THREAD

**Issue by TheLarkInn** [angular/angular#7856]
**Steps to reproduce and a minimal demo of the problem**
It looks like the Safari Technical Preview is now using the new ShadowDOM API standard `attachShadow()` rather than the deprecated `createShadowRoot()`.

I wanted to have an issue at least documented that covered updating ViewEncapsulation to handle the new standard in the future. 

**Current behavior**
ViewEncapsulation.Native errors in Safari Technical Preview

**Comment by MarkPieszak** [comment]
Nice catch this would definitely have to be upgraded in core to reflect this.
Maybe check for the existence of either createShadowRoot or attachShadow? Just my 2 cents!

**Comment by TheLarkInn** [comment]
It's strange because chrome stable doesn't support attachShadow() quite yet. In fact I don't know what does besides STP. It feels like a polyfill like check to see if either method exists on Element and use that one would be a desirable approach in my opinion also.

**Comment by vicb** [comment]
Should be an easy fix in `BrowserDomAdapter.createShadowRoot` (the underlying fn should be memoized when the adapter is instanciated)

**Comment by abraham** [comment]
This is going from Shadow DOM v0 to Shadow DOM v1. I assume if Angular were to drop support for v0 and add support for v1 would that have to be held for a 5.x release?

**Comment by HitkoDev** [comment]
Since my issue has been closed, could anyone give us any progress on this? Maybe at least some hints on whether we should push in the direction of adding a separate `ViewEncapsulation.ShadowDom`, or should we instead fix the `ViewEncapsulation.Native`, considering Custom Elements v0 never moved beyond experimental implementations and `Element.attachShadow` is now a part of DOM Living Standard (https://dom.spec.whatwg.org/)?

**Comment by abraham** [comment]
The feedback from #19059 is that `ViewEncapsulation.Native` can't be changed due to backward compatibility reasons. There is an initial implementation of `ViewEncapsulation.ShadowDom` but there has been no feedback recently on next steps.

**Comment by HitkoDev** [comment]
@abraham Thanks, it would be nice hearing from the Angular devs about it (@TheLarkInn and @robwormald ?), I'm especially curious about why this hasn't been pushed for v6, considering it's been standardised and #19059 was sufficiently ready months before v5 has been released.

**Comment by robwormald** [comment]
Fixed

**Comment by chriszrc** [comment]
I'm getting a similar error in Chrome now:

"Element.createShadowRoot is deprecated ..."

Is there any way to patch older angular apps (4.x) or is upgrading to 6 the only way to proceed here?

**Comment by sarunint** [comment]
@chriszrc That is expected, because `ViewEncapsulation.Native` uses the *old* and *deprecated* Shadow DOM v0 Specification. Use `ViewEncapsulation.ShadowDom` instead.

<sup>Don't blame Angular team for that, they designed this years ago, even before it was deprecated.</sup>
