### ISSUE TITLE
Replacing the component-elemen with the content of the template

### ISSUE THREAD

**Issue by janbaer** [angular/angular#7857]
Is it possible,like in Angular 1 that the element tags from my components will be replace by the html content of the template html? I've actually a problem with a css framework I use in project that has some jQuery functions which uses some element selector with a given structure like 

```
> li > .collapsible-header
```

The problem is now that I want to use in an *ngFor loop a child component, but now the element tag of the child component is between the li element and the div with the classname collapsible header.
And now the jQuery plugin no longer works...

**Comment by zoechi** [comment]
That's not supported. I'm pretty sure there is an issue already.
The closest you can do currently IMHO is

```ts
@Component({
  selector: '.collapsible-header',
  ...
})  
```

**Comment by bromzh** [comment]
```
@Component({
    selector: '.class',
    template: `class`
})
class ClassComponent {}

@Component({
    selector: '[attribute]',
    template: `attribute`
})
class AttributeComponent {}

@Component({
    selector: 'li.item',
    template: `elem + class`
})
class ElemClassComponent {}
```

I think, attribute variant is the best solution for this.

**Comment by janbaer** [comment]
Thanks for the tip! Will try this...

**Comment by zoechi** [comment]
It's already deprecated in Angular1, why would they add it in 2 http://stackoverflow.com/questions/24194972/why-is-replace-deprecated-in-angularjs

**Comment by janbaer** [comment]
Ah ok, thanks for the clarification...

**Comment by darkguy2008** [comment]
Removing ```replace=true``` was the worst decision by the Angular team, ever. It's fricking hard to make a semantic, generic CSS framework with all these random extra container tags.

**Comment by sarunint** [comment]
@darkguy2008, use `ng-container` for that.

**Comment by michaeljota** [comment]
I would like this behavior for other purposes, like NativeScript special templates, but, I don't think this should affect a CSS framework. I really think you are doing things in the wrong way if you need special path in your html for the CSS works properly.

**Comment by Daveawb** [comment]
@michaeljota Are you sure that this statement is true? Take flex box as an example. Flex applies to direct children only and adding an extra tag between parent and child requires special treatment in the css to add `display: flex;` to the angular component tag.

**Comment by trotyl** [comment]
@Daveawb Angular components is consistent with custom elements, like `<video>` or `<audio>` tags, there're internal views inside them but should not be affected by context. What you need is more `Fragment`s rather than `Component`s.

But indeed both concepts have valid use-cases.

**Comment by michaeljota** [comment]
@Daveawb but in that case, it sounds like the place for a `directive` instead of a `component`.

**Comment by MrDrProfX** [comment]
I've done horrible things because this feature does not exist. Horrible horrible things...

**Comment by vajnorcan** [comment]
as users before me has mentioned, it just doesn't make much sense and people are forced to write (again) workarounds to deliver the product. As they pointed out, it breaks the css frameworks, e.g. I have a component that needs to fit in particulat css schema but instead of declaring all the classes within the template, I have to do so on the markup-declaration which makes it ridiculously unreadable

**Comment by michaeljota** [comment]
> I have to do so on the markup-declaration which makes it ridiculously unreadable

You can add classes to your component inside your component.

I understand that adding a new node tree is not always a desired behavior, but finding something that really break the layout is something that you put effort on. If you want to see how to implement flexbox with components and directives, you could take a look at Angular Material 2, and Angular Flex. 

There is a open issue requesting Fragments Components #22208

**Comment by 1pocketaces1** [comment]
I am working with ionic and angular,does anyone have an idea why on-tap events inside of a component do not fire when the component is placed inside another component?

**Comment by darkguy2008** [comment]
@1pocketaces1 that has nothing to do with this issue. Please open a new issue.

**Comment by cScarlson** [comment]
99% of the time, enforcing a specific CSS structure is simply coupling to markup (Coupling === BAD). This is not the reason to include this feature. But here's an example: **try implementing a `<custom-table-column>` without using `:host { display: table-cell; }` in your CSS.** Now, if you could define metadata to your component decorator (`@Component`) to provide the container a CSS class, that would certainly help but still not be sufficient. A great approach to this problem could be using an HTML WebComponents approach where you could *inherit from a native element*. DISCLAIMER, `@Component({...}) class MyComponent extends HTMLDivElement {...}` won't cut it.

**Comment by dramentol** [comment]
This is how custom elements work and I guess that's why angular components are this way.

**Comment by artfanvikram** [comment]
I had to get a subcomponent in the middle of tbody, i applied table-row property to container tag name, and problem solved :)

**Comment by dramentol** [comment]
@artfanvikram you could use a class or attribute selector for your custom component and apply it to an html table row.

```
@Component({
  selector: '[yourCustomComponent]',
  ...
})
```

```
<tr yourCustomComponent>
```

**Comment by tml123** [comment]
What about something like:

`:host {
    display: contents;
}`

Putting that in the host component's css (or scss) file will cause the component's box _not to render_.

It has worked for me before -- but obviously I'd be worried about browser compatibility especially if you're developing to support older browsers.  I'm also pretty sure that's not entirely out of the "experimental" phase.

**Comment by liujingbreak** [comment]
I use ng-template to workaround like I would wrap actual template content inside a top-level ng-template.
```
<ng-template #content>
   ... actual component template content
</ng-template>
```
Then I grab TemplateRef when my component is `ngAfterViewInit()`, and render to root element as ViewContainerRef, I guess this is what `<router-outlet>` kinda does. Then everything inside my ng-template will become siblings of the original root element in DOM tree.
```ts
@ViewChild('content', {read: TemplateRef}) actualContentTmpl: TemplateRef;
constructor(private root: ViewContainerRef)
ngAfterViewInit() {
  const changeDetector = root.createEmbeddedView(this.actualContentTmpl);
  // If you are doing different change detection strategy, use this changeDetector instead of component's
}
```
Problem is that is still leaves an empty component host element in DOM tree, same as `<router-outlet>`

**Comment by trevorhreed** [comment]
@liujingbreak This seems pretty slick for my use case, except, I get a `ExpressionChangedAfterItHasBeenCheckedError` error. Moving the following statement:

```
const changeDetector = root.createEmbeddedView(this.actualContentTmpl);
```

into `ngOnInit()` instead of `ngAfterViewInit()` seemed to resolve this issue, though I frankly don't understand some of the deeper nuances of the component lifecycle and this particular error, so I'm not sure if this is the best way to resolve this error.

**Comment by edmundo096** [comment]
May be related with https://github.com/angular/angular/issues/6710 ?
That "renderAs" Component configuration metadata Proposal is still _Open_ (since Jan 2016).

(Linked for reference, as this issue comes first on Google searches.)
