### ISSUE TITLE
Check or enforce Dart version greater than 1.15.0 during build

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#7860]
Older versions of dart, particular < 1.14.2, may seem to work fine, but actually produce bad artifacts in some cases (See #7395 where Windows+Dart users cannot use angular2 packages generated from Dart SDK 1.14.0). 

We should update the build process in the following ways:

 * For any gulp tasks that check if Dart SDK exists, also check that the SDK is >= 1.15.0 (latest stable version at time of opening this issue). 
   * If user doesn't have Dart SDK installed, do nothing.
   * If user does have Dart SDK, and they DO NOT have a version greater than 1.15.0, log a warning.
   * If user is running `pub_publish.sh` script, escalate the warning to an error and cancel the build.

**Comment by pkozlowski-opensource** [comment]
Obsolete.
