### ISSUE TITLE
Http - Observable completed function not firing

### ISSUE THREAD

**Issue by ibrahimyu** [angular/angular#7865]
Hi, I encountered this problem while using Http. I thought the third function is supposed to be called whatever happens (success or error) after the http request is finished, like `.finally()` method on promises, but it was never called. I'm on Angular 2 beta 13.

````
this.http.get('/orders')
   .subscribe(
         data => this.orders = data,
         error => console.log(error),
         () => { alert('finished!'); } // <- this was never called
   );
````

Tried using `.toPromise()`, but there is no `.finally()` function on returned promise, just `.then()` and `.catch()`.

Anyone encounter the same problem?

**Comment by bromzh** [comment]
3) Third callback didn't called when error.
1) ES6 promises hasn't method `finally`, only `then` and `catch`.
2) Observable object has method `finally`, try it.

**Comment by beeterry** [comment]
I have a question that I've been trying to search the Web for a while on..In my service, the http.get().map() isn't recognized. Have they released a new version that has another way of "mapping" it or something? All I have is .lift and ._isScala

**Comment by MarkPieszak** [comment]
You need rxJS for `.map()` @beeterry 

Make sure you are importing rxJS/map up top.

    import 'rxjs/operators/map';

**Comment by ibrahimyu** [comment]
@bromzh Thanks, but I think the third callback was never called even when there's no error. `.finally()` on Observable works though, had to call it before calling `.subscribe()`. Would be very helpful if this is mentioned on the docs, so people would not confuse between using third callback or observer's finally.

**Comment by zoechi** [comment]
Seems to be an Rxjs issue then, not an Angular2 issue?

**Comment by ibrahimyu** [comment]
@zoechi Rxjs is just fine (because its observable works). It's Angular's Http module that's not firing the third callback function.

**Comment by mautematico** [comment]
Should we use `() =>` (aka complete)? or should we use `.finally()` when looking for a function that excecutes **after** http request ends (wheter it success or it fails)?

I've seen a lot of docs that say things about () =>, but this is the first time I found something about .finally. 

anyway. I'll try it and report it back. :)
 ```
this.http.get('/orders')
   .map(res => res.json())
   .finally(() => this.isLoading = false)
   .subscribe(
         data => this.orders = data,
         error => console.log(error)
   );
```

**Comment by robwormald** [comment]
I can't replicate this in beta.14: https://plnkr.co/edit/gqPafqfqV9zTG1kx5mRO?p=preview

The observable specification says *either* .error() or .complete() will be called, but *never* both. .finally() is useful in the case you want to do something in either case.

**Comment by ibrahimyu** [comment]
@robwormald Confirmed, fixed in beta.14. Closing this. Thanks!

**Comment by mbrookson** [comment]
`.subscribe()` has three callbacks; `success`, `error`, `complete`. So how come for `Rxjs` calls the complete one is never called, yet `.finally()` does work? Surely they should both be called if they are both meant to be a final callback to invoke?

**Comment by trickpattyFH20** [comment]
The promise `.finally()` and the RxJS `complete` callback of `.subscribe()` have different functionality as it was explained by @mbrookson and @robwormald

Maybe it would be good to consider reopening this issue till we can find out if the missing `complete` callback is an intended implementation in Angular http Observables (and why its missing) ? @ibrahimyu

**Comment by mbrookson** [comment]
I agree @trickpattyFH20, I'd be interested to know if this was intentional because to me it seems like the `.finally()` and the `complete` callbacks imply the same thing and should both be called

**Comment by Aleksandr-Leotech** [comment]
Complete and finally are totally different things. Complete means that the observable steam was finished successfully. Because you can have many success calls. Finally means that steam has ended, either successfully or not.

It is not obvious with HTTP requests, but imagine two additional scenarios.

1. Mouse events. You will be receiving a never-ending steam of success callbacks, but you will never receive finally or complete, because user events will never stop (unless you trigger an exception with buggy code, then you will get error and finally).

2. Working with web sockets. You will get multiple success callbacks, but at some point in time your communication with back end will stop and you will get both complete and finally unless you have some errors, which will call error and finally.

So, you might be getting multiple or no success calls, zero or one error call, zero or one complete and zero or one finally.

**Comment by debben** [comment]
I experienced this exact behavior today. Calling http.get().toPromise() was returning a promise that would never fulfill or reject. The complete callback was never being called. 

This ended up being an issue with an [Http Interceptor library I was using.](https://www.npmjs.com/package/@covalent/http) to display a loading message. After removing this library and just using the standard HttpModule, the complete callback started working again. If you're using any sort of wrapper or other interceptor functionality around Http, be mindful of this.

**Comment by larssn** [comment]
I don't really understand why this is the default.

Using a RESTful service, why wouldn't ng2's http use the complete functionality of rxjs?
It's not like we're opening an actual stream to a http endpoint; we do our request, and the request is DONE, COMPLETE.

To avoid memory leaks one would have to do:

```
let sub = this.http.get('/myplace')
   .map(resp => resp.json())
   .subscribe(() => {
      sub.unsubscribe();
   });
```

**Comment by DzmitryShylovich** [comment]
http://plnkr.co/edit/3gRgLU1oBl74WLqd7Hcr?p=preview

**Comment by zoechi** [comment]
@larssn @DzmitryShylovich showed that in fact observables are completed after the first event,
and if you really only want the first item and then unsubscribe use `first` instead
```
this.http.get('/myplace')
   .map(resp => resp.json())
   .fist()
   .subscribe(() => {
      // redundant // sub.unsubscribe();
   });
```

**Comment by larssn** [comment]
@DzmitryShylovich @zoechi Hm, I neglected to mention that I'm using Angular 2 via Ionic 2, so I'm stuck with version 2.2.1 atm. Don't know if http completing was a recent development.

**Comment by DzmitryShylovich** [comment]
the same behaviour with 2.2.1 http://plnkr.co/edit/3gRgLU1oBl74WLqd7Hcr?p=preview

**Comment by larssn** [comment]
@DzmitryShylovich Sorry for the inconvenience then, has gotta be something else in our setup then.

**Comment by kamok** [comment]
@zoechi It was necessary for me to use `first()` when I use http POST with a custom return.
```
return this.http.post(this.apiUrl + '/members', JSON.stringify(member), options)
      .map(res => {
        return {
          'status': res.status,
          'member': member
        };
      })
      .catch(err => { return Observable.throw({
          'status': err.status,
          'member': member
        });
      })
```

**Comment by mrdulin** [comment]
@Aleksandr-Leotech 
Ok.

I thought there is problem. 

```ts
const formChangeSub: Subscription = this.formChange$
      .throttleTime(2000)
      .do(() => {
        this.loading = true;
      })
      .switchMap(($event) => this.getDiseasesByPage($event))
      // the formChange$ is never-ending stream during the component life cycle.
      
      // not trigger
      // .finally(() => {
      //   console.log('done');
      //   this.loading = false;
      // })
      .subscribe(null, this.getDiseasesByPageFailed, 
        // the complete method, not trigger too.
        //() => {
        //  this.loading = false;
        //}
      );
```

How to solve this case?

**Comment by MacKinley** [comment]
I had a similar issue described by @debben. I am using my own custom HttpInterceptor and the issue was being cause by the use of `.switchMap()` on a separate stream which emitted a dependency for all of my calls. The actual http call was made inside the switchMap, converting the observable returned by that to another observable which never is what never completes. (Or something like that please correct any misconceptions I have.)

My Http get looked something like this:
```typescript
get(url: string, options?: RequestOptionsArgs): Observable<Response> {
  options = this.getRequestOptionArgs(options);
  return this.customHeaderItemStream.switchMap((customHeaderItem: string) => {
    options = this.injectCustomHeaderItem(options, customHeaderItem);

    return super.get(url, options);
  });
}
```

Solved by adding `.first()` to the result of `.switchMap()` to complete the resulting Observable after the first item is emitted.

```typescript
get(url: string, options?: RequestOptionsArgs): Observable<Response> {
  options = this.getRequestOptionArgs(options);
  return this.customHeaderItemStream.switchMap((customHeaderItem: string) => {
    options = this.injectCustomHeaderItem(options, customHeaderItem);

    return super.get(url, options);
  }).first(); // <---- Added .first() here!
}
```

I'm still kinda new with RX and Anglular 2+ so any advice or corrections are appreciated.

**Comment by im4aLL** [comment]
None of above helped me to get it to work. This finally worked - 

**Angular v6**
```js
this.authService.login(requestData)
  .pipe(finalize(() => this.isLoading = false)) // import { finalize } from 'rxjs/operators';
  .subscribe(response => {
    this.router.navigate(['dashboard']);
  }, error => {
    this.errorResponseMessage = error.error.message;
  });
```

**Comment by ezebc182** [comment]
@im4aLL also works in Angular v5! Thanks!!!

**Comment by mamad1295** [comment]
@im4aLL worked for me too in V5 Thanks

**Comment by pravin02** [comment]
finalize operator working for me also in ionic3, thanks

**Comment by digeomel** [comment]
The proposed solution with `finalize` doesn't seem to work with the Apollo GraphQL client on Angular 7... 😞

**Comment by kenttanl** [comment]
I think the `complete()` method should be run after success and error is the correct approach.
