### ISSUE TITLE
Cross platform debugger that work on all platforms

### ISSUE THREAD

**Issue by m-amr** [angular/angular#7875]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here, see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. 

I have used angular batarang with angular 1 and it was a great tool and for angular 2 batarangle is good tools, but it still a chrome tools, we need these tool to reproduces Issues in Firefox, IE or on mobile browsers too.

If we can build a tool in Typescript or Javascript have all the functionality of  batarangle, so that engineers can use it in all platforms.

At the development mode.
it can be a bar at the bottom of the Page or the App that contain all the information needed to debug.

At the production mode.
It can send the Crashes to a dashboard so engineers can use this data to reproduce the Issues.

Thanks.

**Comment by pkozlowski-opensource** [comment]
Indeed it sounds like it would a nice tool to have but I don't think we've got enough free cycles to do this as part of the core. Sounds like a perfect project for a motivated community member(s) and we would be willing to help, for sure.
