### ISSUE TITLE
5 min quickstart - pointing to incorrect module 'angular2/platform/bootstrap'

### ISSUE THREAD

**Issue by MarkPieszak** [angular/angular#7879]
In the 5 minute quickstart it currently states:

    import { bootstrap } from 'angular2/platform/bootstrap';

Which was moved recently to:

    import { bootstrap } from 'angular2/bootstrap';

I can put in a quick PR for this if someone can point me in the direction of where these files are located in the repo (or if it's another repo). Thanks.

**Comment by cebor** [comment]
nope, `import {bootstrap}    from 'angular2/platform/browser';` is the right import statement and its correct in the 5min quickstart.

**Comment by MarkPieszak** [comment]
Strange but I'm using "angular2": "2.0.0-beta.13"

![image](https://cloud.githubusercontent.com/assets/2574412/14231503/eddf045e-f953-11e5-9c62-49ed97a2fdda.png)

ERROR in ./client/app/app.ts
(1,27): error TS2307: Cannot find module 'angular2/platform/bootstrap'.

No where to be found in platform. 
![image](https://cloud.githubusercontent.com/assets/2574412/14231513/48552120-f954-11e5-9954-6bc9adbea467.png)
