### ISSUE TITLE
Cannot bind to all ngComponentRouter events

### ISSUE THREAD

**Issue by zackarychapple** [angular/angular#7880]
version `1.5`

I have multiple components using the routeOnActive in their component controllers and I am trying to bind to any event for routeOnActive, however I can't seem to pick it up on rootScope. I tried specifying both routerOnActivate and $routerOnActivate as the name of the event and neither worked.

```
if (typeof angular.module('ngComponentRouter') !== 'undefined') {
  this.$rootScope.$on('routerBeforeActivate', function (next, prev) {
    //Do stuff
  });
  this.$rootScope.$on('routerOnActivate', function (next, prev) {
    //Do stuff
  });
}
```

**Comment by zoechi** [comment]
If this is about Angular 1.x please report in https://github.com/angular/angular.js
