### ISSUE TITLE
bug(Router): Query Parameters Stripped On Reload

### ISSUE THREAD

**Issue by awiseman** [angular/angular#7881]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here, see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. 

**Steps to reproduce and a minimal demo of the problem**

Note:  This is hard to demo in a plunk due to the way plnkr encapsulates the app.  This plunk at least provides code that can be copied into a local environment, though.  If ran using live-server (as described in the quickstart), the issue is readily visible.

http://plnkr.co/edit/4vo91z5wQkGmKpsBtgnp?p=preview

1. Create a parent route that uses '/...' as the path
2. Create a child route from that parent
3. Apply query parameter to URL
4. Perform a browser page refresh

**Current behavior**

Child route query parameters are stripped from URL on page refresh

**Expected/desired behavior**

Query parameters should remain intact

**Other information**

This only seems to happen if the parent route definition uses the root path ('/...').  The issue doesn't occur if the parent path is anything else (e.g. '/parent/...').

**Comment by chybie** [comment]
+1

**Comment by p-mcgowan** [comment]
+1

**Comment by zoechi** [comment]
Seems to be related to #6595

**Comment by vsavkin** [comment]
It seems the issue was opened before the last router rewrite. And it doesn't look like the issue still makes sense. I'm closing it. Please reopen it if you think it still makes sense.

**Comment by amitabharya23** [comment]
I am still having this issue. 
Scenario:

From Home page click on profile link and route to profile view (angular so no refresh). 
Now on profile view I have tabs (google material design lite tabs) (mdl-tabs). These tabs has anchor link (href="#photos-panel"). Now if I click on this it's redirecting me to home view (no refresh). 
But If I refresh this profile view page, then it's working fine.
