### ISSUE TITLE
angular 2 and spring mvc

### ISSUE THREAD

**Issue by rtasaithambi** [angular/angular#7892]
Hi all, 

Am a java spring MVC developer, I was using angular 1 in my previous project and I would like to use  angular 2 in up coming projects. please suggest me to walk through this. 

Thanks,

**Comment by cebor** [comment]
Support questions should asked at

Stackoverflow: http://stackoverflow.com/tags/angular2

or

Gitter: https://gitter.im/angular/angular

**Comment by pkozlowski-opensource** [comment]
@cebor is right, this is a support question that should be asked using one of the provided support channels.
