### ISSUE TITLE
TypeError: require is not a function (electron + beta.13)

### ISSUE THREAD

**Issue by ruleb** [angular/angular#7894]
An electron app that uses `require` is not working anymore since beta.13 upgrade

```
TypeError: require is not a function
```
when requiring a node module:
```
var uuid = require('node-uuid');
```

I've created a skeleton project here that can shows the problem: 
```
git clone https://github.com/ruleb/angular2-13-require-issue
cd angular2-13-require-issue
npm install
npm run tsc
npm run start
```

The issue will show itself in the devtools that open on `npm run start`

To see the working beta.12 version, you can use the beta.12 config:
```
cp package.json.12 package.json
rm -rf node_modules
npm install
npm run tsc
npm run start
```

**Comment by pkozlowski-opensource** [comment]
This sounds like a general support question around build / packaging and as such would be better asked using one of the support channels: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
