### ISSUE TITLE
@ContentChild is null but must have a value

### ISSUE THREAD

**Issue by alvipeo** [angular/angular#7895]
Creating a dialog component and needed to have some content projected. So, created a gist - https://gist.run/?id=013108b407a520a4655621348c00d4f0 .

Both @ContentChild props are not set. Which looks like a bug.

**Comment by alvipeo** [comment]
ok, with the help from guys in gitter, it narrows down to not working with selectors. but works with types - http://plnkr.co/edit/ybwpTyS1UV1WLu8hvb10?p=preview

**Comment by zoechi** [comment]
`@ContentChild()` supports component or directive types as parameter or the name of a template variable

```ts
@ContentChild('header') dheader: any;
```
```html
      <ilg-dialog>
        <ilg-dialog-header #header></ilg-dialog-header>
        <ilg-dialog-body></ilg-dialog-body>
      </ilg-dialog>
```

`@ContentChildren()` also supports a comma-separated list of template variables like
```ts
@ContentChild('header,body') contentElements: any;
```
CSS selectors are not supposed to work.

**Comment by alvipeo** [comment]
thanks! good to know! (someone please update the docs ;) )

**Comment by zoechi** [comment]
#7174
