### ISSUE TITLE
angular 2 and java

### ISSUE THREAD

**Issue by rtasaithambi** [angular/angular#7901]
How can I run the angular 2 application in apache Tomcat 7 by using JSP.

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by zoechi** [comment]
see also #7899

**Comment by pkozlowski-opensource** [comment]
See https://github.com/angular/angular/issues/7892#issuecomment-205269947
