### ISSUE TITLE
Start dragging on touchstart

### ISSUE THREAD

**Issue by mburger81** [angular/angular#7903]
I need to add handle drag&drop on mobile devices, the touchstart event is firing as expected but there is naturally no VISIBLE effect for drag&drop.

So is there a possibilty to start a native DRAG and DROP on touchStart or how should I handl the drag and drop for touch systems in angular2?

```
 this.htmlElement.ontouchstart = (touchEvent: TouchEvent) => {
     // here I check if user intend starting a drag&drop or if there are some other touch behaviours
     
    if (dragging) {
        //WHAT to do here to start visbile drag and drop, can I launch a DRAGSTART for HTML or something like that
    }
}
```

**Comment by pkozlowski-opensource** [comment]
Please direct support questions to an appropriate channel: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
