### ISSUE TITLE
Remove unused import in dowgrade_ng2_adapter.ts

### ISSUE THREAD

**Issue by tsle** [angular/angular#7905]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here, see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. 

dowgrade_ng2_adapter.ts has unused "import Element protractor.Element". This import requires a dependency on the angular protractor typings which conflicts with angular typings because they have different type defs for "$".

**Comment by pkozlowski-opensource** [comment]
Looks like the offending import is gone in master: https://github.com/angular/angular/blob/04220be8fd8efb265a2f74812a6b7b7e91be0b94/modules/%40angular/upgrade/src/downgrade_ng2_adapter.ts
