### ISSUE TITLE
Can not use @ViewChild with es6

### ISSUE THREAD

**Issue by kone** [angular/angular#7906]
when i use @ViewChild with es6 ,seems it not take effect;

the js code is:
```

import {Component, ElementRef, ViewChild} from 'angular2/core';
@Component({
    selector: 'hamburger-icon',
    template: require('./hamburgerIcon.html'),
    styles: [require('./hamburgerIcon.scss')],
    providers: [],
    directives: [],
    pipes: []
})
export class HamburgerIcon {
    @ViewChild('pathA') pathA;

    static get parameters() {
        return [[ElementRef]];
    }

    constructor(element) {
        this.element = element;
    }

    ngAfterViewInit() {
        console.info(this);
    }
}
```

and the tempalte is：

```
<div class="hamburger-icon">
    <div class="icon-wrapper" style="visibility: hidden">
        <svg width="1000px" height="1000px">
            <path #pathA d="M 300 400 L 700 400 C 900 400 900 750 600 850 A 400 400 0 0 1 200 200 L 800 800"></path>
            <path #pathB d="M 300 500 L 700 500"></path>
            <path #pathC d="M 700 600 L 300 600 C 100 600 100 200 400 150 A 400 380 0 1 1 200 800 L 800 200"></path>
        </svg>
        <button class="menu-icon-trigger"></button>
    </div>
</div>
```

**Comment by zoechi** [comment]
Works fine in TS https://plnkr.co/edit/2FyRfH?p=preview (I suspected an issue with SVG elements)

**Comment by b-strauss** [comment]
Are you using pure es6? Decorators and class properties don't exist in es6.

**Comment by kone** [comment]
@zoechi yes，works fine in typescript。
@b-strauss  i use webpack to compile es6 ，the babel-loader config like it：

```
{
                extensions: ["js"],
                test: /\.js$/,
                loader: "babel-loader",
                exclude: /(node_modules)/,
                query: {
                    presets: ['es2015'],
                    plugins: [
                        'transform-decorators-legacy',
                        'transform-class-properties'
                    ]
                }
            }
```

i want to use typescript for angular2 , but some npm module like (d3-ease,segment-js) always can't find module。

**Comment by kone** [comment]
@zoechi your demo https://plnkr.co/edit/2FyRfH?p=preview  seems work fine

**Comment by CarlCui** [comment]
@kone I believe babel has a plugin for angular2 annotations. You should check it out.

**Comment by CarlCui** [comment]
@kone babel has a plugin for [angular2 annotations](https://github.com/shuhei/babel-plugin-angular2-annotations). I don't use babel, so you have to try some luck. ;) Also, I found a babel angular2 example [here](https://github.com/shuhei/babel-angular2-app).

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by kone** [comment]
@CarlCui THX , @zoechi i close this issue

**Comment by shuhei** [comment]
FYI It's a bug of babel 5 and babel-plugin-transform-decorators-legacy.

https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy/pull/14

babel-plugin-angular2-annotations fixes the bug at the moment.

https://github.com/shuhei/babel-plugin-angular2-annotations

Or you can initialize the property to detour the bug. `@ViewChild('pathA') pathA = this.pathA;`
