### ISSUE TITLE
Router: Why does HashLocationStrategy listen to popState and hashChange events?

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#7908]
**Steps to reproduce and a minimal demo of the problem**

View hash_location_strategy:

```dart
  void onPopState(UrlChangeListener fn) {
    this._platformLocation.onPopState(fn);
    this._platformLocation.onHashChange(fn);
  }
```

Internal clients rely on manually dispatching `window.hashchange` events in order to have other libraries that rely on listening to hashchange manually know what the route is. Unfortunately, this seems to cause duplicate routing now.

A workaround is to override `HashLocationStrategy` and replace:

```dart
@override
  void onPopState(UrlChangeListener fn) {
    // Instead of listening to hashChange + popState, just listen to hashChange.
    //
    // We manually invoke hashChange events which can cause duplicate routing.
    _platformLocation.onPopState(fn);
  }
```

I'd prefer *not* to keep it like that long-term.

**Current behavior**

Listens to both type of events.

**Expected/desired behavior**

I'd imagine listen to just one?

**Comment by vsavkin** [comment]
Closed here https://github.com/angular/angular/pull/10011
