### ISSUE TITLE
fakeAsync can fail on Edge

### ISSUE THREAD

**Issue by juliemr** [angular/angular#7909]
cc @vikerman 

@kara  found a case where the `_scheduler` in fakeAsync is set to null too early, and tests fall over. Log looks like:

```
Edge 13.10586.0 (Windows 10 0.0.0) ERROR
  EXCEPTION: Error during evaluation of "input"
  ORIGINAL EXCEPTION: TypeError: Unable to get property 'scheduleFunction' of undefined or null reference
  ORIGINAL STACKTRACE:
  TypeError: Unable to get property 'scheduleFunction' of undefined or null reference
     at _setTimeout (Unknown script code:146:5)
     at FakeAsyncZoneSpec.prototype.onScheduleTask (Unknown script code:26:25)
```

We should ensure that this doesn't happen when moving `fakeAsync` to a ZoneSpec.

**Comment by juliemr** [comment]
Is this obsolete now?

**Comment by kara** [comment]
Haven't tried it yet with the new code, but we can close for now. I'll re-open if it crops up again.
