### ISSUE TITLE
Doc form exmaples code incorrectly written

### ISSUE THREAD

**Issue by onesick** [angular/angular#7910]
Hi guys, I am following the form building basic, and found out an error
https://angular.io/docs/ts/latest/guide/forms.html

here you have used [hidden] property set to pristine or valid. This does not produce the result when the value is wrong. the code should be instead, what I used, *ngIf="address.touched && !address.valid" so that when the control is touched but not valid, the error message gets attached to it.

previously using hidden property binding, it does nothing.

Thanks!

**Comment by zoechi** [comment]
documentation issues are maintained in https://github.com/angular/angular.io/issues

**Comment by pkozlowski-opensource** [comment]
@onesick thnx for reporting, we always do appreciate documentation corrections! But as @zoechi pointed out (thnx so much for helping out with issues!) all the documentation lives in a separate repository: https://github.com/angular/angular.io/issues

@onesick would you mind checking the latest version of the docs and if they still suffer from the problem open an issue in https://github.com/angular/angular.io/issues? Or better yet, send a PR with corrections! This would be very much appreciated!
