### ISSUE TITLE
Query string is being duplicated when entering wildcard route - /**

### ISSUE THREAD

**Issue by wkwiatek** [angular/angular#7911]
**Steps to reproduce and a minimal demo of the problem**
Add path `/**` and try to reach it with some query string e.g. http://plnkr.co/edit/pnsgl3P3pfS0pT4bydvv?p=preview

**Current behavior**
On the wildcard route (`/**`) query params appears twice. 

**Expected/desired behavior**
Query string should not be duplicated

**Other information**
Angular beta.13 

I couldn't find what line causes such a behaviour. I got lost somewhere in Zone's `drainMicroTaskQueue`

**Comment by vicb** [comment]
obsolete
