### ISSUE TITLE
Angular 1 router: arrow function

### ISSUE THREAD

**Issue by dpogue** [angular/angular#7913]
https://github.com/angular/angular/blob/master/modules/angular1_router/src/module_template.js#L99

This line remains as an arrow function when the angular_1_router.js file is generated, which breaks in several non-Chrome browsers. TypeScript isn't compiling it because this is a JS file, not a TS file.

It should be replaced with an ES5-friendly `function() { return $injector.invoke(loader); }`.

**Comment by jelbourn** [comment]
attn @petebacondarwin

**Comment by vicb** [comment]
obsolete
