### ISSUE TITLE
Angular2: ReferenceError in Internet Explorer 11 - Symbol is undefined.

### ISSUE THREAD

**Issue by DennisTanghe** [angular/angular#7914]
I followed the quickstart on https://angular.io/docs/ts/latest/quickstart.html in VS2015 and it works fine in IE Edge and Google Chrome, but not in IE11 (Version: 11.162.10586.0)
I'm using Angular2 beta 13.

IE 11 gives the following error:
   {
      [functions]: ,
      __proto__: { },
      description: "undefined",
      message: "",
      name: "Error",
      number: NaN,
      originalErr: {
         [functions]: ,
         __proto__: { },
         description: "'Symbol' is undefined",
         message: "'Symbol' is undefined",
         name: "ReferenceError",
         number: -2146823279,
         stack: "ReferenceError: 'Symbol' is undefined
   at getSymbolIterator (http://localhost:52202/Scripts/angular2.dev.js:436:7)
   at Anonymous function (http://localhost:52202/Scripts/angular2.dev.js:6381:5)
   at Anonymous function (http://localhost:52202/Scripts/angular2.dev.js:6333:3)
   at u (http://localhost:52202/Scripts/system.js:5:3540)
   at s (http://localhost:52202/Scripts/system.js:5:3172)
   at Anonymous function (http://localhost:52202/Scripts/system.js:5:3627)
   at Anonymous function (http://localhost:52202/Scripts/angular2.dev.js:8404:3)
   at u (http://localhost:52202/Scripts/system.js:5:3540)
   at s (http://localhost:52202/Scripts/system.js:5:3172)
   at Anonymous function (http://localhost:52202/Scripts/system.js:5:3627)"
      },
      stack: null
   }

IE doesn't support Symbol but in the code below it seems that the function 'isPresent' is never called. The error is thrown immediately at that line:

  var _symbolIterator = null;
  function getSymbolIterator() {
    if (isBlank(_symbolIterator)) {
      **if (isPresent(Symbol) && isPresent(Symbol.iterator)) {**
        _symbolIterator = Symbol.iterator;
      } else {
        var keys = Object.getOwnPropertyNames(Map.prototype);
        for (var i = 0; i < keys.length; ++i) {
          var key = keys[i];
          if (key !== 'entries' && key !== 'size' && Map.prototype[key] === Map.prototype['entries']) {
            _symbolIterator = key;
          }
        }
      }
    }
    return _symbolIterator;
  }
  exports.getSymbolIterator = getSymbolIterator;

I haven't created a plunker as I encounter there this bug https://github.com/angular/angular/issues/6501.
But if you follow the quickstart it should be reproducible when you run the app in IE11.

**Comment by CaptainCodeman** [comment]
Try using core.js instead of es6-shim

**Comment by DennisTanghe** [comment]
Thanks, with core.js it works indeed on IE11 as well.

**Comment by ctrl-brk** [comment]
Could you list the exact js files you're using for IE? Not sure what I need from Core.js. I'm new to all this.
Thank you.

**Comment by CaptainCodeman** [comment]
The polyfills I use are in here (check ./src/index.html):
https://github.com/CaptainCodeman/angular2-webpack-polyfill

I don't know why we have green lights on the home-page for browsers that don't actually work if you follow all the provided instructions. It's time the polyfills were fixed or the instructions updated.

**Comment by ctrl-brk** [comment]
Thanks a lot!

So, I got rid of those:
es6-shim.min.js
system-polyfills.js
shims_for_IE.js
angular2-polyfills.js

and added these:
https://cdn.polyfill.io/v2/polyfill.min.js?features=default,console.*,Intl.~locale.en&gated=1
zone.min.js
core.min.js

So far seems to be working. I didn't use ie-fix.js - should I?

**Comment by CaptainCodeman** [comment]
It depends which features you use so it's very hard to say - if you're not using anything that depends on it then you may be fine. If you don't use date / number pipes for instance then the Intl polyfill isn't needed for Safari (otherwise core.js is possibly enough).

Ideally there would be a definitive list of ES6 features that are used / required which would allow more focused polyfills to be used - the list above for core.js was just a bit of trial and error working through things with IE.

**Comment by ctrl-brk** [comment]
Is there a quick summary document describing what these poly- and shim- things are and how they work? Don't need to go deep right now but would be good to understand what I'm doing ))

**Comment by CaptainCodeman** [comment]
No, the basic idea is that they implement new browser and language features in older browsers that don't yet support things natively so apps can take advantage of them. 

Ideally, this should be mostly transparent. IMO it should be a single file that's referenced that figures out what needs to be patched and how. If we need to have in-depth and intimate knowledge of exactly which shims are required and specific orders for loading them then something is wrong or missing.

It really shouldn't be this difficult.

**Comment by ctrl-brk** [comment]
Well, now I have this problem:
https://github.com/angular/angular/issues/4809

Reverting back to original shims/fills fixes it but then still IE doesn't work. OMG!

**Comment by tom10271** [comment]
It is super annoying to keep fixing polyfill for every new version.... The angular polyfill is not working. I am heavily stuck for hours

**Comment by jpleclerc** [comment]
Anyone know if the polyfills work in RC?

**Comment by pierreUMAknow** [comment]
They definitely don't work with RC1. I use both Currency and Date pipes and both fail with the following error in IE11:

    EXCEPTION: ReferenceError: 'Intl' is undefined

**Comment by vicb** [comment]
obsolete

**Comment by tamtran-asnet** [comment]
IE9 'Map' is undefined.

**Comment by IcodeNet** [comment]
AppModule:  ReferenceError: 'Headers' is undefined
