### ISSUE TITLE
Url is missing guide attribute

### ISSUE THREAD

**Issue by Krunal-Promact** [angular/angular#7915]
when we go to the link https://angular.io/docs/ts/latest/glossary.html#!#O from glossary in that the links of template syntax are not working, they are showing 404. The url of template syntax are right but they are missing one "guide" word in between after "latest" word. if we put "guide" word after "latest" word then they are working. please replace asap

**Comment by brandonroberts** [comment]
This should be filed over at: https://github.com/angular/angular.io

**Comment by pkozlowski-opensource** [comment]
@Krunal-Promact  thnx for reporting, we always do appreciate documentation corrections! But as @brandonroberts  pointed out (thnx so much for helping out with issues!) all the documentation lives in a separate repository: https://github.com/angular/angular.io/issues

@Krunal-Promact  would you mind checking the latest version of the docs and if they still suffer from the problem open an issue in https://github.com/angular/angular.io/issues? Or better yet, send a PR with corrections! This would be very much appreciated!
