### ISSUE TITLE
bug: CurrencyPipe should accept `null` input on currencyCode

### ISSUE THREAD

**Issue by qwesda** [angular/angular#7917]
The `CurrencyPipe` should accept `null` as a valid input for the `currencyCode` argument and (in this case) behave like the `DecimalPipe`, i.e. just display the number.

If the currency (and currency code) are part of the model than there can be situations where the currency has not yet been set by the user. It would of cause be possible to work around this by using `ngIf`, but this would make the template unnecessarily complex and reduces its readability.

This behaviour would also be consistent with the fact that the number pipe accept `null` as the value and don't throw an error.

**Steps to reproduce and a minimal demo of the problem**

use the `CurrencyPipe` like this: `{{12.34 | currency:null}}`

example: http://plnkr.co/edit/VqorIUr9gahX7rcMRtzP?p=preview

**Current behavior**

The following error is thrown: `RangeError: Invalid currency code: null` and the template is not rendered and crashes.

**Expected/desired behavior**

The number should just be formatted as if the `DecimalPipe` would have been used.

**Comment by laco0416** [comment]
why don't you use `number` pipe?

**Comment by golear91** [comment]
agreed, have run into the same issue.

**Comment by michaelgeorgeattard** [comment]
Undefined does not work either.

If template is something like `{{` currency | currency:undefined:true:'1.2-2' }}` CurrencyPipe.prototype.transform is receiving `null` as currencyCode parameter.

**Comment by pkozlowski-opensource** [comment]
> The CurrencyPipe should accept null as a valid input for the currencyCode argument and (in this case) behave like the DecimalPipe, i.e. just display the number.

I don't think it should be the case. If, as programmers, expect a given number to represent currentcy tat it should be displayed as currency with a proper currency code. A currency that was once specified should not changed / converted into a number.

I'm going to close this one as won't fix, we are going to implement a configurable default currency code instead (see #12364). If you need functionality that you are describing in this issue you could create a custom pipe that wraps the existing currency and decimal pipes.
