### ISSUE TITLE
Support Query<type> injection in ElementInjector

### ISSUE THREAD

**Issue by mhevery** [angular/angular#792]
There are cases where the component would like to inject a list of child components in its light DOM into it. Such a list needs to be an Observable so that the Component can be notified of child component creation/destruction through `if` and `foreach`.

Example:
```
@Component()
@Template({
  inline: '<div *foreach="var pane in panes">{{pane.title}}</div>'
})
class MyComponent {
  panes;
  constructor(@Query<Pane> panes:QueryList) {
    this.panes = panes;
  }
}
```

This would inject `QueryList` which could be further data-bound inside the component template. 

QueryList:
- Only works with `ElementInjector`
- Should be List like so that it can be data bound by children
- Should have APIs which will allow component to listen to the addition/remove/re-position of the children.
- Will change its content as a response to child components being adde/removed in light DOM
- Should support `@descendand` and `@child` to control if direct or any child will match in light DOM

**Comment by matanlurey** [comment]
Please promote to M7 if possible.
