### ISSUE TITLE
Can't bind data to non native properties

### ISSUE THREAD

**Issue by janbaer** [angular/angular#7920]
Hello, I use in my project a ui-framework which uses some custom data attributes to display for example a tooltip. I tried now to show dynamic data in the tooltip with binding some data from my model into such an attribut. Unfortunately it doesn't worked, since I got the following error:

```
Can't bind to 'tooltip' since it isn't a known native property ("the">
```

This is the code I used:

```
data-tooltip="{{ isClosed(question) ? 'is answered' : 'open' }}"
```

How can I fill this attribute from angular with dynamic data?

**Comment by pkozlowski-opensource** [comment]
> How can I fill this attribute from angular with dynamic data?

Try `[attr.data-tooltip]=isClosed(question) ? 'is answered' : 'open'`

https://angular.io/docs/ts/latest/guide/template-syntax.html#!#other-bindings

**Comment by janbaer** [comment]
Thanks! This code has worked:

```
[ngClass]="{isClosed: isClosed(question), isOpen: !isClosed(question)}">
```
