### ISSUE TITLE
Question: Can this repos Community-hotlist be updated?

### ISSUE THREAD

**Issue by MarkPieszak** [angular/angular#7922]
The last bug in the community hotlist is from Jan 20th. 

Anyway we could update and add some new ones so we can know how we can contribute? Not sure what I can try and fix and put a PR in for. Just trying to help 🎱

**Comment by pkozlowski-opensource** [comment]
@MarkPieszak yeh, we are a bit behind with properly flagging issues.... We want to get better on this but need to figure out a better way of tracking "first bugs"... I will need to ask you for a bit more patience: currently there are many issues opened and we want to go over backlog first to properly flag them.

Once again, thnx for being eager to help out, we do appreciate it! Just need to get better organized to have smooth contribution experience.

**Comment by MarkPieszak** [comment]
Czesc Pawel, totally understand! Just wanted to get it out there :)
