### ISSUE TITLE
Update tools library with systemjs to v.0.19.25 to support module-relative loading

### ISSUE THREAD

**Issue by wardbell** [angular/angular#7923]
Please update `https://code.angularjs.org/tools/system.js` to a more recent version.

As of v.0.19.25, systemjs supports setting the `__moduleName` global (as does node and the commonjs loader).  That enables relative loading of styles and templates in metadata because we can write this now:
```
declare var __moduleName: string;

@Component({
  moduleId: __moduleName,
  selector: 'quest-summary',
  templateUrl: 'quest-summary.component.html', // module relative 
  styleUrls: ['quest-summary.component.css']  // module relative 
})
```
Our docs samples use v.0.19.25 so this works when they run locally.

But our plunkers are stuck with the old version in `https://code.angularjs.org/tools/system.js`

**Steps to reproduce and a minimal demo of the problem**

See `app/quest-summary.component.ts` in plunker: http://plnkr.co/edit/9FbldVcacKHkE1kcBrqc?p=preview

The index.html loads both the systemjs in our tools (commented out) and v.0.19.25 from a CDN.

The CDN version works; the version in our tool library (as of April 4) fails (see console).

**Comment by jeffbcross** [comment]
@wardbell this would be nice. Are you able to make a PR to this repo first so we can make sure the new loader is compatible?

**Comment by born2net** [comment]
using latest jspm and ng2 still getting Error: ReferenceError: __moduleName is not defined
and not working as per how it should via https://angular.io/docs/ts/latest/guide/component-styles.html

regards

**Comment by wardbell** [comment]
@born2net perhaps we are not as clear as we should be ... The `moduleId` technique works only with cooperating module loaders.

The variable  `__moduleName` is defined for systems. Other loaders may have a similar variable with a different name. I don't know about jspm. Perhaps you can research this and tell us what, if any, support jspm offers for this concept.

Clarifying text would also be welcome

**Comment by born2net** [comment]
will research some more, tx for the feedback...

**Comment by cexbrayat** [comment]
@wardbell Is this working for TypeScript/SystemJS right now? For angular.io, it looks like you rely on [a trick](https://github.com/angular/angular.io/blob/0ef63166f8175a110fb0bfc9c24ac9c956e4f27e/public/docs/_examples/component-styles/ts/app/quest-summary.component.ts#L9), but maybe I'm missing something...

I tried with angular-cli and in one of my own projects recently, and it was still not working for me (whereas using CommonJS and `module.id` was working).

**Comment by wardbell** [comment]
Yes it does but you must load systemjs v.0.19.19 or later.

**Comment by born2net** [comment]
FYI I did use jspm 0.16.33 which uses 

```
  "systemjs": "0.19.26",
   "systemjs-builder": "0.15.15",
```

**Comment by cexbrayat** [comment]
Strange, I'm using SystemJS (without JSPM) 0.19.26 and it doesn't work for me. And I think it doesn't work with a newly generated project with angular-cli either... Maybe there is another tiny option to switch somewhere that I missed in the angular.io config...

**Comment by cexbrayat** [comment]
My mistake, it does work with angular-cli.

**Comment by vicb** [comment]
obsolete
