### ISSUE TITLE
#blah='ngForm' does not bind as expected in a loop

### ISSUE THREAD

**Issue by escardin** [angular/angular#7928]
**Steps to reproduce and a minimal demo of the problem**
http://plnkr.co/edit/v92OmzCM3A3pWFPqP0Cp?p=preview

_What steps should we try in your demo to see the problem?_
enter something into the top field and bottom field. the true/false only updates when the second field's validity changes.

**Current behavior**
ngForm is bound to the last control of the ngFor

**Expected/desired behavior**
ngForm binds to the control for the current element, just like an unparameterized binding.

**Comment by kara** [comment]
This appears to work in RC.6 (see [plunker](http://plnkr.co/edit/vbZSijk7mkN6P5vZctBu?p=preview
)), so closing.
