### ISSUE TITLE
Angular 1 router: not unloading child component

### ISSUE THREAD

**Issue by dpogue** [angular/angular#7934]
**Steps to reproduce and a minimal demo of the problem**

http://plnkr.co/edit/v253WIugAY9KaW8Er9xE?p=preview

_What steps should we try in your demo to see the problem?_
Click on "Contact 1" to show the contact details.
Hit the back button, notice that the details view stays loaded even though the URL says it should not.

**Current behaviour**
The child component is not unloaded when going to a previous route that had no child.

**Expected/desired behaviour**
The child component should fire its deactivate event and the ng-outlet should be removed.

**Comment by vicb** [comment]
obsolete
