### ISSUE TITLE
bug: app crashes if a component defines `static name="..."` under TS 1.8.x

### ISSUE THREAD

**Issue by wardbell** [angular/angular#7937]
Try it!  This is a tweak to our QuickStart

```ts
class AppComponent{
  static name = "foo" 
}
```
Throws: 
```
Error: Cannot assign to read only property 'name' of function 'function AppComponent() {
(…)
```
BUT ... change the variable to any other name ... `namex`, `nam`, etc. ... and all is well

Here's a repro plunker: http://plnkr.co/edit/20xuFILOcvsWCoelmA6v?p=preview

Seems related to TypeScript 1.8.x (here in 1.8.9, first detected with 1.8.0). 
Apps running all recent A2 betas work fine with TypeScript 1.7.x.

Fearing it was a TypeScript error, I tried simple repro in the [TS Playground](http://www.typescriptlang.org/play/index.html). 
```
class AppComponent{
  static name = "foo" 
  constructor() {
	   alert('all is well')
  }
}
new AppComponent();
```
Worked fine ... alert box pops right up.

TS Playground is TS 1.8.x

**Comment by cebor** [comment]
Maybe related to: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name

Example: https://www.typescriptlang.org/play/index.html#src=class%20MyClass%20%7B%7D%0D%0Aalert(MyClass.name)%3B

**Comment by vicb** [comment]
obsolete
