### ISSUE TITLE
Build instructions in the Developer guide for the Angular 2 repo

### ISSUE THREAD

**Issue by zackhall** [angular/angular#7938]
Currently the [developer guide](https://github.com/angular/angular/wiki/Guide) in the repo wiki has no instructions on how to build the Angular 2 repo. 

There are many experiencing build errors in the repo's GitHub issues, and it would help to know if we're taking the right steps to try to build, run, and test the repo before creating a new issue.

The request is for a guide in the README or wiki on how to build the project, run it, and run the tests.

Thanks!

**Comment by brandonroberts** [comment]
Here you go https://github.com/angular/angular/blob/master/DEVELOPER.md

**Comment by zackhall** [comment]
Well... I'll be damned. 😆 Good eye, missed that one. Thanks, @brandonroberts!

**Comment by zoechi** [comment]
The instructions in https://github.com/angular/angular/blob/master/DEVELOPER.md seem a bit outdated.

I created this dockerfile a few days ago. Might be helpful.

```dockerfile
FROM google/debian:jessie

MAINTAINER Günter Zöchbauer <gunter@gzoechbauer.com>

RUN echo "deb http://ftp.de.debian.org/debian/ jessie main non-free contrib" >> /etc/apt/sources.list

RUN \
  apt-get -q update && \
  DEBIAN_FRONTEND=noninteractive && \
  apt-get install --no-install-recommends -y -q \
    curl \
    git \
    git-core \
    # npm \ 1.4.21 but requires >= 3.5.3 < 4.0.0
    # nodejs \ 0.10.29 but requires >=5.4.1 < 6.0.0
    apt-transport-https \
    ca-certificates \
    make \
    build-essential \
    g++ && \
  apt-get upgrade -y

RUN \
  curl -sL https://deb.nodesource.com/setup_5.x | bash - && \
  apt-get install -y nodejs

RUN \
  sh -c 'curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -' && \
  # Set up the location of the stable repository.
  sh -c 'curl https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list' && \
  apt-get update && \
  DEBIAN_FRONTEND=noninteractive && \
  apt-get install --no-install-recommends -y -q \
    dart/stable

ENV DART_SDK /usr/lib/dart
ENV PATH $DART_SDK/bin:$PATH

RUN git clone --recursive https://github.com/angular/angular.git

WORKDIR /angular


RUN \
  npm install bower -g && \
  npm install tsd -g

RUN \
  npm install && \
  bower --allow-root install && \
  cd tools && npm install && tsd install && \
  cd ../modules/angular2 && npm install && tsd install

RUN node --max-old-space-size=4096 $(npm bin)/gulp build  # --projects=angular2,benchpress,bundle_deps

# docker run -ti -v $(pwd)/dist:/angular/dist zoechi/angular_build sh
# node --max-old-space-size=4096 $(npm bin)/gulp build
# creates the build output in $(pwd)/dist
```

**Comment by aburlak** [comment]
Was able to build Angular 2 Betas without much issues, but now struggling to compile Angular RC from source (on Arch Linux, tried many different Node.JS/NPM versions with nvm).
After spending some time debugging, it still looks like an uphill battle.

Is the gulpfile even supposed to be working at this point, or am I doing something seriously wrong?
It looks like many undocumented manual steps are needed before it will have any chance to work.

Also tried ./build.sh, but it has some Mac-specific syntax in it - so I only was able to run it after editing those commands.
The ./build.sh, however, did not produce the full build output - in particular, there was no compiler_cli (which is why I actually wanted to build Angular 2 RC from source).

Thank you!

**Comment by brandonroberts** [comment]
The compiler_cli is part of the `./build.sh` process, so when you run that command it should create the cli in the dist/@angular folder

**Comment by aaaa0441** [comment]
I believe the latest 'build' instructions are here https://github.com/angular/angular/blob/master/docs/DEVELOPER.md
