### ISSUE TITLE
Allow @Directive to control ChangeDetection contract

### ISSUE THREAD

**Issue by mhevery** [angular/angular#794]
Currently the ChangeDetection supports pruning branches and only updating components on binding changes. The current mechanism is imperative and we should have declarative one.

Suggested property `Component.changeContract` which can be set to [`NONE`, `BINDING_ONLY`], where `NONE` is the default.
```
@Component({
  selector: 'my-component',
  bind: {
    'a': 'a',
  },
  changeContract: BINDING_ONLY 
})
class MyComponent {
}
```

**Comment by mhevery** [comment]
@vsavkin can you suggest better name? Add your thoughts.

**Comment by vsavkin** [comment]
It was implemented a while ago.
