### ISSUE TITLE
Add event like onHasTask to NgZone

### ISSUE THREAD

**Issue by Gigitsu** [angular/angular#7942]
Can you please add an event that notifies when all tasks, either macro and micro, have been completed to `NgZone`? Something like the zone.js `onHasTask` event would be great.
With that event I can do this:

``` js
onHasTask(parent, current, target, hasTask) {
  if ( !( hasTask.macroTask || hasTask.microTask ) ) {
    console.log("All Tasks have been completed.");
}
```

**Comment by pkozlowski-opensource** [comment]
Please open it in https://github.com/angular/zone.js

**Comment by Gigitsu** [comment]
Why should I open this issue on zone.js repository?
Zone.js already exposes `onHasTask` event, but I can't subscribe to that event because `NgZone` doesn't expose it and `NgZone` is part of angular.

**Comment by MarkPieszak** [comment]
@Gigitsu Could this be used to tell if all tasks (multiple XHR requests let's say) are completed so you can fire off an event after? If so, that'd be amazing. This would be a great addition. 👍

**Comment by vicb** [comment]
What is your use case ?

**Comment by cwmrowe** [comment]
I'm interested in this so that I could print a page with PhantomJS, once the page is 'ready'.

**Comment by karsunke** [comment]
A usecase would be a loading-overlay which hides itself when all async tasks in this zone have finished.
