### ISSUE TITLE
Router: allow parent route to be assigned to path: '/' on the child route by default

### ISSUE THREAD

**Issue by webtrix** [angular/angular#7946]
Hi, 

I've create this very simple plunk: [https://plnkr.co/edit/u8VOB7lhTH90fvxtl94x](https://plnkr.co/edit/u8VOB7lhTH90fvxtl94x?p=preview) to explain my issue / thoughts.

So when creating a route with `...` it tells angular that this route has children (sorry if I don't get all technical, but I want to explain it, the way I see it).  Now in this example we're creating an `app/` route.

What I really find illogical is that in the `AppComponent` I need to create a route for the `/` path, being in this case the `AppHomeComponent`.  Why can't the router assign that path by default to `AppComponent` ?

So.. the actually code in the `AppComponent` would become

```javascript
@Component({

  selector: 'app',
  template: `
    <nav>
      //since the AppComponent is referenced to the "/" path we can just do this
      //which will generate a link with the path /app/
      <a class="button" [routerLink]="['../AppComponent']">Home</a>
      // OR
      <a class="button" [routerLink]="['/AppComponent']">Home</a>
      <a class="button" [routerLink]="['./AppFooComponent']">Foo</a>
      <a class="button" [routerLink]="['./AppBarComponent']">Bar</a>
    </nav>
    <router-outlet></router-outlet>`,
  directives: [ROUTER_DIRECTIVES],
  providers: [],

})

@RouteConfig([
  
  {path: '/bar', name: 'AppBarComponent', component: AppBarComponent},
  {path: '/foo', name: 'AppFooComponent', component: AppFooComponent},
  
])
```

**Comment by CaptainCodeman** [comment]
Because / may not be the parent

It's just like folder paths or URLs - some things are root absolute and some are relative. You can't assume that the parent of where you are is always going to be the root as well.

**Comment by webtrix** [comment]
@CaptainCodeman could you put that into an some kind of example maybe? Would like to understand your point better.

I think, if there is a default behavior, that you can change, of course then you know how the router will act by default, but you can change it, if needed. E.g. if I don't want the router to use `AppComponent` to use as the default child root, then I would just need to add it to the `@RouteConfig`

 ```
@RouteConfig([

  {path: '/', name: 'AppHomeComponent', component: AppHomeComponent, useAsDefault: true},

])
```

This way, you can modify it any way you like, but if you don't there is still a default, in my opinion more logical way.

**Comment by brandonroberts** [comment]
This has come up before in #5505 and #6204. As @CaptainCodeman said you can have a default child path for `'/app/...` that could be `/home` or something else. The component router treats nested routes like abstract routes in ui-router. You can't navigate to `/app/...` without terminating the route tree. You can choose to put a "dummy" component there or set a child route as your default, but currently it has to terminate somewhere.

**Comment by webtrix** [comment]
@brandonroberts by `dummy component` you mean something like my `AppHomeComponent` in my plunk?

**Comment by brandonroberts** [comment]
@webtrix yea. I just say dummy component because in other cases I've seen people want to navigate to '/app' without drilling down to one of the children. The component doesn't do anything besides terminate the route tree for the nested route.
