### ISSUE TITLE
Request for common tools to return change detection metrics

### ISSUE THREAD

**Issue by ananthmo** [angular/angular#7950]
The common tools library contains a method timeChangeDetection, this prints out how long it took angular to run change detection. It outputs the number of cycles ran (numTicks) and how long each cycle took (msPerTick).

https://github.com/angular/angular/blob/d272f96e23f379e1b565435b3af010138e710ab9/modules/angular2/src/platform/browser/tools/common_tools.ts#L44

In addition to printing that information to console.log, would be great if the method returned the numTicks and msPerTick values, rather than returning nothing.  This would allow clients to have programmatic access to the values.

**Comment by pkozlowski-opensource** [comment]
Seems like it was fixed by 75463cd8df67805d266ee4e8b3e29665b569ebe3
