### ISSUE TITLE
Router: Provide better error message when linkParams is not an array

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#7952]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here, see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. 

**Steps to reproduce and a minimal demo of the problem**

_Use https://plnkr.co or similar -- try this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5_

http://plnkr.co/edit/UjhDOPlYOnh8DF9dXQUT?p=preview

_What steps should we try in your demo to see the problem?_

1. Open the developer console log.
2. Note the error thrown for the invalid redirect route `linkParams.forEach is not a function`.

**Current behavior**

When a redirect, or router link is setup incorrectly and an array is not provided, an error is thrown with a non-specific message.

**Expected/desired behavior**

The error thrown should state that the linkParams provided should be an array.

**Other information**

This will aid in troubleshooting errors for invalid router DSL.

**Comment by basarat** [comment]
I would hope this to be reported at compile time instead of *runtime* `linkParams.forEach is not a function`. 

A user reported the error on stackoverflow as well : http://stackoverflow.com/a/36492491/390330 :rose:

**Comment by ericmartinezr** [comment]
@basarat the problem is that there are users that don't write typescript, so it should be validated at both compile and runtime.

**Comment by basarat** [comment]
@ericmartinezr indeed. Nevertheless typescript users (like the one I linked to) should have had a compile time error (he was passing a string) 🌹

**Comment by ericmartinezr** [comment]
@basarat that's weird, I get an error when I compile. See

VSCode
![image](https://cloud.githubusercontent.com/assets/13039652/14399202/c8c38cd2-fdc0-11e5-8823-20934eba21eb.png)


Compiling
![image](https://cloud.githubusercontent.com/assets/13039652/14399199/b48293c6-fdc0-11e5-95b4-6dbe3da39bfa.png)

The user env must be different
