### ISSUE TITLE
router-link-active added to child link when in parent route

### ISSUE THREAD

**Issue by tiagoroldao** [angular/angular#7953]
Demo plunkr of the issue: http://plnkr.co/edit/0VHBhUuVq5bgCrAke0nd?p=preview

To reproduce, select 'Heroes' and notice that the link to the child component is marked active when the parent route is active.

**Current behavior**
A child route alwayshas the router-link-active class if a parent is currently active 

**Expected/desired behavior**
A link to /parent/child should not be active when on /parent or /parent/otherChild

**Comment by brandonroberts** [comment]
Dupe of https://github.com/angular/angular/issues/5334

**Comment by tiagoroldao** [comment]
True. I did search for this, dammit :smile:
