### ISSUE TITLE
`<input />` should not work but it does

### ISSUE THREAD

**Issue by zoechi** [angular/angular#7961]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here, see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. 

**Steps to reproduce and a minimal demo of the problem**

_Use https://plnkr.co or similar -- try this template as a starting point: 

 [**Plunker**](https://plnkr.co/edit/r6tBmF?p=preview)

_What steps should we try in your demo to see the problem?_

**Current behavior**
Angular doesn't complain and it's working fine

**Expected/desired behavior**
https://github.com/angular/angular/pull/5591
https://github.com/angular/angular/issues/5563
https://github.com/angular/angular/pull/2133

I haven't found any issues where self-closing tags were reintroduced.

**Other information**

See also http://stackoverflow.com/questions/36492169/i-have-an-error-in-angular-2-when-im-trying-to-use-nested-components/36492238#36492238

**Comment by frederikschubert** [comment]
I think that the standard says that only void elements can be self-closing. And angular implements the standard luckily quiet closely. :)

**Comment by zoechi** [comment]
@frederikschubert After reading several times it seems like  `/>` is valid for void elements? Thanks for the hint.
