### ISSUE TITLE
Event bindings don't support unary +

### ISSUE THREAD

**Issue by Tragetaschen** [angular/angular#7964]
http://plnkr.co/edit/0v2kxn8GBxdCM6Pzcj3C?p=preview

**Current behavior**
The unary `+` of the `ngModelChange` expression doesn't appear in the generated JavaScript, so the called method receives a string value.

**Expected/desired behavior**
The unary `+` should be applied to the string before calling the function.

**Comment by Tragetaschen** [comment]
That's still an issue in `rc.1`.

The expression in the event handler `(input)="id=+$event.target.value"` is compiled to `self.context.id = $event.target.value` without the unary `+`.

**Comment by pkozlowski-opensource** [comment]
I don't think we want to support unary `+` atm so going to close this one for now. Please comment if you feel strongly about this one. Is your use-case primarily about type conversion?

**Comment by Tragetaschen** [comment]
Yes, it's type conversion. In my TS component, I'm declaring a  method  expecting a number, but at runtime, I'll get a string. So essentially, TypeScript *and* the template are lying to me.
