### ISSUE TITLE
Router: child router with Component error

### ISSUE THREAD

**Issue by doxiaodong** [angular/angular#7966]
* AppComponent
```typescript
@RouteConfig([
  {path: '/article/...', name: 'Article', component: ArticlComponent}
])
```
* ArticleComponent
```typescript
@Component({
  template: `
    <router-outlet></router-outlet>
  `,
  directives: [ROUTER_DIRECTIVES]
})
@RouteConfig([
  {path: '/:category', name: 'ArticleList', component: ArticleListComponent},
  {path: '/:category/:url', name: 'ArticleDetail', component: ArticleDetailComponent}
])
```
* ArticleCategoryComponent
```typescript
@Component({
  selector: '[article-categories]',
  template: `
    <div>
      <a class="a type" [class.active]="articleCategory === category.key" [routerLink]="['ArticleList', {category: category.key}]">{{ category.name }}</a>
    </div>
  `,
  directives: [ROUTER_DIRECTIVES]
})
```
* ArticleListComponent
```typescript
@Component({
  template:  '<div article-categories></div>',
  directives: [ROUTER_DIRECTIVES, ArticleCategoryComponent]
})
```

1. It throws an error like ` EXCEPTION: Component "ArticleListComponent" has no route config. in [null]`
2. It works normal when I remove `[article-categories]` component from ArticleListComponent  template.
3. It also works normal if I do not use child router.
4. I use https://github.com/AngularClass/angular2-webpack-starter for seed.
5. https://new.darlin.me/articl/error click the link to see error
6. complete code: https://github.com/doxiaodong/darlin-angular2/tree/child_router_issue/src/app

**Comment by zoechi** [comment]
A plunker to reproduce the issue would be great.

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by doxiaodong** [comment]
I think it because `[routerLink]="['ArticleList', {category: category.key}]"`, use `[routerLink]="['../../ArticleList', {category: category.key}]"` replace it will fix.
