### ISSUE TITLE
Select change event occurs before ngModel updates

### ISSUE THREAD

**Issue by brtnshrdr** [angular/angular#7971]
I'm trying to get the updated select box value, which in this case is an object, when it changes. I'm trying to use the [ngValue]="object" syntax added in https://github.com/angular/angular/pull/7842 like so

```
<select [(ngModel)]="selectedObj" (change)="objChanged($event)">

<option *ngFor="#obj of searchResults" [ngValue]="obj">
    {{obj.name}}
</option>

</select>
```

The $event.target.value is a string equal to "1: Object" (The "1" is the index of the array I assume)
However, if in that same method I print out "selectedObj", it's always the old value. It seems as though the change event fires before the model is updated.

**edit** - If ngFor redraws the array of option values, the index keeps incrementing, so you can't use it to pull the correct object from the array ("searchResults" in this case)

**Steps to reproduce and a minimal demo of the problem**

http://plnkr.co/edit/7rIHLBWWVqpcPL1NrpDz?p=preview

_What steps should we try in your demo to see the problem?_

If you look at the console.log()'s, you'll notice that the "Selected Obj: " is always equal to the old value when you select a new value

**Expected/desired behavior**

I would like either the model object to be updated before the change event fires, or a way to access the new value from the $event obj passed into the change function.

**Comment by samridh90** [comment]
I have the same issue. I wanted to use the new value when the select option changed. here's the workaround I used:
In the component class
```
private _selectedObj;
get selectedObj() {
    return this._selectedObj;
}
set selectedObj(newObj) {
    this.objChanged(newObj);
}

ngOnInit(): void {
    this._selectedObj = this.getDefaultValue();
}
```
In the template
```
<select [(ngModel)]="selectedObj">
<option *ngFor="#obj of searchResults" [ngValue]="obj">
    {{obj.name}}
</option>
</select>
```

**Comment by zoechi** [comment]
I think it's the same as #7822 and caused by #6311

**Comment by kleinech** [comment]
You can use (ngModelChange) instead of (change):

```
<select [(ngModel)]="selectedObj" (ngModelChange)="objChanged($event)">

<option *ngFor="#obj of searchResults" [ngValue]="obj">
    {{obj.name}}
</option>

</select>
```

**Comment by pkozlowski-opensource** [comment]
`(ngModelChange)` is the way to go

**Comment by pawantiwari1** [comment]
you can also used change method 
In html file
<select  [(ngModel)]="selectedObj" (change)="selectChangeHandler($event)">
<option *ngFor="#obj of searchResults" [ngValue]="obj">
    {{obj.name}}
</option>

in ts file
selectChangeHandler(event:any)
  {
     this.selectedshift=event.target.value;
   console.log("if change in method "+this.selectedshift)
  }

**Comment by nsivaji61** [comment]
This code is not working prod mode. Any suggestion?

**Comment by mlc-mlapis** [comment]
@nsivaji61 ... it has to be `ngModelChange` as ... `<input [ngModel]="username" (ngModelChange)="username = $event">`

**Comment by nsivaji61** [comment]
I want to fire onchange event when ever user selects anything because i have a cascading dropdown lists. Please suggest.

Thanks

**Comment by vishbal** [comment]
nsivaji61 : Were you able to resolve the issue ? I have same problem of updating cascading drop downs and (change)="somemethod()" is triggered without any user selection change.

**Comment by pawantiwari1** [comment]
You can build as  ng build command then its work in my project

**Comment by ashfaq-unstoppable** [comment]
sample ngValue use

**Comment by ishwara-bhat** [comment]
> this.selectedshift=event.target.value;

With angular 8, I saw that event.value works. 
console.log(event) gives me-
MatSelectChange {source: MatSelect, value: "ffff"}

Best recomemndation is do console.log of the event object, if nothing is working. Then tune your code.
