### ISSUE TITLE
Can't set the 'Access-token' property in the request headers on a http.get.

### ISSUE THREAD

**Issue by CVarisco** [angular/angular#7972]
Hi Guys! 

I have create a networkService that get a list of resources. 
To get this resources you need to be authorized with a jwt access-token that must be inserted into the headers of our GET request.

This is the code snippet where I do the call:
```typescript
public get(network:string) {
      let params: URLSearchParams = new URLSearchParams();
      params.set('network', network);
      const headers = new Headers();
      headers.append('Access-token', 'xxxxxxxxx');
      headers.append('Content-Type', 'application/json');
      return this._http.get(`${this._API_URL}/list`, {search: params, headers: headers})
          .map(res => res.json())
          .catch(this.handleError);
}
```
I can't set the 'Access-token' property in the request headers on a http.get.
We Expected in the Request-Headers the property 'Access-token', but the 'Access-token' property comes set in [this way:](http://imgur.com/wUdUvyV)

Access-Control-Request-Headers:access-token 

Any ideas ? Does it work for you ?
Thanks a lot

**Comment by CaptainCodeman** [comment]
That looks like CORS kicking in - your server needs to be configured to accept certain headers.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Access-Control-Allow-Headers

Also maybe worth thinking about using the standard "Authorization" header with a Bearer token rather than inventing your own.

**Comment by CVarisco** [comment]
Hi Captain!
We have configured our server to accept certain header, but the property doesn't arrive.
Thanks :)

**Comment by CaptainCodeman** [comment]
The real thing to check is whether it's sent - look at the request in the network tab of the browser. If it *is* being sent then the problem is not with the angular end but with the server (or some intermediary).
