### ISSUE TITLE
Native submit behavior impossible as ngForm does always preventDefault()

### ISSUE THREAD

**Issue by sod** [angular/angular#7973]
Demo: http://plnkr.co/edit/faVCGBuBJbG6A5Y7f5hO?p=preview

HTML component template:
```html
<form action="?submit=1">
  <input type="submit" value="Submit">
</form>
```

Click submit, but nothing happens.

angular 1 skips the preventDefault code, if an `action` attribute exists on `<form>`  (https://github.com/angular/angular.js/blob/master/src/ng/directive/form.js#L484).

But angular 2 ngForm always listens on submit and returns false, thus preventing the submit from ever coming through (https://github.com/angular/angular/blob/master/modules/angular2/src/common/forms/directives/ng_form.ts#L163).

Is this intended? Of course I can decorate or override ngForm. But the angular 1 way seems logical.

**Comment by b-strauss** [comment]
Lookin at the code it seems that if you give your form the ngNoForm attribute, it will not get decorated by angular.

https://github.com/angular/angular/blob/master/modules/angular2/src/common/forms/directives/ng_form.ts#L81

Would that be enough or do you still want a directive that decorates your form element?

**Comment by sod** [comment]
Oh you are right. Yes that works for my usecase! Thank you.

But what if someone wants to use any part of ngForm (e.g. validation)?

**Comment by b-strauss** [comment]
I don't know if that is possible. If not, this would be a good feature request. :)

**Comment by PascalPrecht** [comment]
@sod validation is performed on form controls that have either `ngControl` `ngModel` or `[ngFormControl]` directives on them, regardless of `ngForm`.
