### ISSUE TITLE
Allow `<template>` tag to be added to the DOM

### ISSUE THREAD

**Issue by zoechi** [angular/angular#7974]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here, see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. 
[x] feature request

**Steps to reproduce and a minimal demo of the problem**

_Use https://plnkr.co or similar -- try this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5_

_What steps should we try in your demo to see the problem?_

**Current behavior**
Polymer elements like `<iron-list>` expect a `<template>` element to be passed as child element.  
Angular processes `<template>` elements internally and doesn't add them to the DOM.

**Expected/desired behavior**

There should be a way to tell Angular that the `<template>` element should be treated as a DOM element like for example
```html
<iron-list>
  <template ngNonBindable>
    <div>{{item}}</div>
  </template>
</iron-list>
```

where the `<template>` tag is passed to `<iron-list>` as-is.

**Other information**

**Comment by b-strauss** [comment]
Would {{item}} come from angular or polymer? Would it even be possible to mix both template systems? Maybe it would be easier to tell angular to completely ignore everything under a specific element?

```html
<!-- don't evaluate anything below iron-list -->
<iron-list ngIgnoreDom>
  <template>
    <div>{{item}}</div>
  </template>
</iron-list>
```

**Comment by zoechi** [comment]
The entire `<template>` with its content should just be passed as-is. `{{item}}` is supposed to be processed by Polymer.
`ngNonBindable` was just an example because it already exists for a similar purpose.   
I haven't run into situations except for the `<template>` tag where this would be necessary, but a more general mechanism would work for me as well.

**Comment by b-strauss** [comment]
I have not yet used the two systems at the same time. I have no idea how polymer and angular would interact when, for instance, both of them have a string interpolation identifier that has the same name, but I guess a more general mechanism would be needed.

**Comment by zoechi** [comment]
This works fine. A Polymer element can be treated like any DOM element and Angular binding syntax can be used to pass values in and listen for events. There are no conflicts except the template tag.

**Comment by b-strauss** [comment]
I was thinking about a situation where both Polymer and Angular have a binding with the same name in the same template. Although now that I think about it, this would probably not be an issue because the template scope would not overlap.

**Comment by bluEEil** [comment]
I also need a solution for this, but I do need to use angular binding for one of the template childrens:
`<template is="dom-bind">
        <paper-datatable [data]="data" selectable multi-selection>
            <paper-datatable-column header="Name" property="exmp" sortable editable>

            </paper-datatable-column>
        </paper-datatable>
    </template>`

As the data parameters comes from a component property. So just making angular ignore the template tag and treat it as if it was a <div> could probably make this use case work

**Comment by PascalPrecht** [comment]
What specifically would be the use case here? Let's say we could project a template element like this, it would then stick around in the (emulated) Shadow DOM of the component for further processing right?

I think this can be handled by `NgTemplateOutlet` then, unless you have an actual reason to keep the template element where it is.

**Comment by bluEEil** [comment]
@PascalPrecht 
My use case is for using a polymer element that "sits" on the template tag as 
<template is="dom-bind">
So I want to declare template tags without angular interfering with them inside the html of the component that im writing, but still be able to use all angular template features inside this template tag (such as data binding the table data from the component property). I hope this clarifies the use case, if not tell me and I will try to explain further.

For a more deeper explanation of the overall problem i'm facing you can check my question on stack over flow:
http://stackoverflow.com/questions/36864501/using-paper-datatable-in-angular2/36864636?noredirect=1#comment61339397_36864636

**Comment by zoechi** [comment]
There are elements like https://elements.polymer-project.org/elements/iron-list that want get a `<template>` element passed that is used to render the list items. That is currently not possible.

**Comment by b-strauss** [comment]
> I think this can be handled by NgTemplateOutlet then, unless you have an actual reason to keep the template element where it is.

Polymer mandates template tags for certain elements. There is no way around it.

**Comment by bluEEil** [comment]
Is there a way around it by adding the template to the DOM imperatively?

**Comment by vicb** [comment]
Could this be solved with ngNonBindable ?

**Comment by zoechi** [comment]
@vicb what do you mean? I tried `ngNonBindable` and my initial comment shows that.

There is no way to add a `<template>` tag, (which is a regular tag) to the DOM using Angular2 and I think that is a serious limitation.
It makes several use cases for example with Polymer quite cumbersome (needs an additional Polymer element that wraps the element that actually was supposed to be used where the `<template>` tag can be passed from)

**Comment by vicb** [comment]
> I tried `ngNonBindable` and my initial comment shows that.

Oops didn't see that, sorry. `ngNonBindable` should be on the parent - use a `ng-container` if you don't want the parent stamped out.

**Comment by zoechi** [comment]
I see. I'll try that. Thanks for the hint!

**Comment by vicb** [comment]
Please close the issue once you have confirmed.

**Comment by cissecedric** [comment]
I think I face the same issue, trying to use this element in my angular2 app:
https://github.com/Zecat/paper-stepper

in my app.html :
<template is="dom-bind" id="eventScope">

  <paper-stepper on-paper-stepper-completed="completed">
    <paper-step label="step 1" on-paper-step-saved="saved" editable on-paper-step-updated="updated"></paper-step>
    <paper-step label="step 2"></paper-step>
  </paper-stepper>
  <paper-toast id="toast"></paper-toast>

  <script>
    scope = document.getElementById('eventScope');
    scope.completed = function() { this.$.toast.show('Stepper completed'); }
    scope.saved = function() { this.$.toast.show('Step 1 saved'); }
    scope.updated = function() { this.$.toast.show('Step 1 updated'); }
  </script>

</template>

in my app.module:
@NgModule({
  declarations: [
    AppComponent,
    PolymerElement('vaadin-combo-box'),
    PolymerElement('paper-input'),
    PolymerElement('vaadin-grid'),
    PolymerElement('paper-stepper')
  ],

Regards,

**Comment by zoechi** [comment]
@cissecedric Please wrap your code in triple backticks ``` to make it readable

**Comment by cissecedric** [comment]
Sorry Zoechi, and thanks now I know the trick.
And for my previous question I found a workaround just by removing the template tags ! and I've used jQuery to access to the paper-stepper element methods...

**Comment by yushadowx** [comment]
Hi @zoechi, have the issue eventually be solved? I tried @vicb's suggestion as:

```html
<ng-container ngNonBindable>
  <template>
    <div>{{item}}</div>
  </template>
</ng-container>
```
The ```<template>``` tag appeared in DOM, but the content was still not exactly the same with not using angular.

**Comment by zoechi** [comment]
@yushadowx please create a new issue with a Plunker to reproduce.
