### ISSUE TITLE
Select box option [value]'s not being set in NgFor without using NgModel

### ISSUE THREAD

**Issue by brtnshrdr** [angular/angular#7975]
After beta.14, if you have a select box and you are using an NgFor loop for your options, you can no longer use [value] if you are NOT using [(ngModel)]. (It only sets the "value" attribute on the option element if you are using ngModel). Bug was most likely introduced in https://github.com/angular/angular/pull/7842

**Steps to reproduce and a minimal demo of the problem**

http://plnkr.co/edit/vcI7spvX4832scqrkSmo?p=preview

_What steps should we try in your demo to see the problem?_

If you look at the console, you'll notice that the select box with an ngModel (which is set to a fake object that does **NOT** exist on the component), it outputs the value option after the (change) event. The select box with**OUT** the ngModel attribute however, doesn't have the value attribute set, and outputs the display value of the option.

**Expected/desired behavior**
[value] should work regardless of the presence of an NgModel

**Comment by zoechi** [comment]
I'm not sure I fully understand your issue.
What I found is that the `value` attribute is not created in the DOM when `[value]` is used. That is IMHO the expected behavior.
`[attr.value]="obj.name"` seems to work fine though - which is the syntax to bind to attributes instead of properties.

**Comment by kara** [comment]
@brtnshrdr  I'll take a look. Thanks for reporting!
