### ISSUE TITLE
Child components cannot read route params of parents

### ISSUE THREAD

**Issue by mharris7190** [angular/angular#7976]
Suppose in app.component.ts I have route config: 

/users/:user_id/..., component: UserComponent

Then in user_component.component.ts I have route config:

/contact_info, Component: ContactInfo,

Then in the ContactInfo component, I am unable to read from route params the user_id.

I could have it as an input, but I'd rather have it be able to read directly from the route. I noticed I could use route registry to get to the user_id, but it feels hacky to do so.

I would expect route params to carry all the route params present in the route. Not just the ones specified in a trickle down manner.

P.S. I am currently running Beta.6. Has this potentially already been patched since that release?

**Comment by CaptainCodeman** [comment]
No, this is how it works.

IMO it'a a mistake to use dependency injection in the constructor for what are effectively per-instance values and it would be better if the routeParams were a service that could be kept around, observed (for changes) and use to reference parent params as well. e.g.

`routeParams.get('id');`
`routeParams.parent.get('parentId');`

One options for what you want to do is to use a shared service to pass the parent param to the child component.

**Comment by vicb** [comment]
outdated
