### ISSUE TITLE
chore: use typings instead of tsd internally

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#7982]
**Current behavior**
We use `tsd` to install our own typings, which has been deprecated in favor of `typings`. We should use `typings` as long as all of the dependencies we need are available.

**Comment by Charlkie14** [comment]
Not sure if this is a stupid question but will you start using Typescript's new @types in package.json for typings? It would be cool.

**Comment by vicb** [comment]
could this be closed now ?
