### ISSUE TITLE
Possible bug with integration with asp.net 5/core

### ISSUE THREAD

**Issue by energeticspark** [angular/angular#7983]
Hello,

**Platform**
This is a possible bug for Angular2 with ASP.NET 5/core.

**Description of the issue**
I receive a template parse error (EOF) whenever I reference a Component within a sub-folder that attempts to display a databound / non-databound html table (no matter how simple).
This is not a bug with a simple list (ul, li) (outputting data via databound ngFor/hardcoded list) but it does with a very simple table.  This makes me think there is a bug.
Also, if the code is placed into a multi-lined template it works fine - this steers me to thinking that it is a bug.  

**Steps to reproduce can be found at:**
The solution works in plunkr - template errors only occur in asp.net.
ASP.NET had node_modules.  The content of these node_modules is copied to wwwroot/nodelibs.
The nodelibs are referenced in script references and no 404 errors take place.

**Steps to reproduce and a minimal demo of the problem**

Details of error here:
http://stackoverflow.com/questions/36366018/angular2-template-parse-errors-eof
(expand comments in answer for chat discussion for further details).

Working plunkr of what I am attempting achieve:
https://plnkr.co/edit/B6gc0iYRB6IyisOy06ky

**Current behavior**

> EXCEPTION: Template parse errors:
> Unexpected character "EOF" ("
>         <td>hello cell</td>
>     </tr>
> </tab[ERROR ->]"): ApplicationsTestComponent@4:5
> :62706/nodelibs/angular2/src/platform/browser/browser_adapter.js:76 EXCEPTION: Template parse errors:
> Unexpected character "EOF" ("
>         <td>hello cell</td>
>     </tr>
> </tab[ERROR ->]"): ApplicationsTestComponent@4:5BrowserDomAdapter.logError @ :62706/nodelibs/angular2/src/platform/browser/browser_adapter.js:76
> :62706/nodelibs/angular2/src/platform/browser/browser_adapter.js:85 EXCEPTION: Error: Uncaught (in promise): Template parse errors:
> Unexpected character "EOF" ("
>         <td>hello cell</td>
>     </tr>
> </tab[ERROR ->]"): ApplicationsTestComponent@4:5
> :62706/nodelibs/angular2/src/platform/browser/browser_adapter.js:76 EXCEPTION: Error: Uncaught (in promise): Template parse errors:
> Unexpected character "EOF" ("
>         <td>hello cell</td>
>     </tr>
> </tab[ERROR ->]"): ApplicationsTestComponent@4:5BrowserDomAdapter.logError @ :62706/nodelibs/angular2/src/platform/browser/browser_adapter.js:76
> :62706/nodelibs/angular2/src/platform/browser/browser_adapter.js:76 STACKTRACE:BrowserDomAdapter.logError @ :62706/nodelibs/angular2/src/platform/browser/browser_adapter.js:76
> :62706/nodelibs/angular2/src/platform/browser/browser_adapter.js:76 Error: Uncaught (in promise): Template parse errors:
> Unexpected character "EOF" ("
>         <td>hello cell</td>
>     </tr>
> </tab[ERROR ->]"): ApplicationsTestComponent@4:5
>     at resolvePromise (angular2-polyfills.js:543)
>     at angular2-polyfills.js:579
>     at ZoneDelegate.invokeTask (angular2-polyfills.js:365)
>     at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (:62706/nodelibs/angular2/src/core/zone/ng_zone_impl.js:35)
>     at ZoneDelegate.invokeTask (angular2-polyfills.js:364)
>     at Zone.runTask (angular2-polyfills.js:263)
>     at drainMicroTaskQueue (angular2-polyfills.js:482)
>     at XMLHttpRequest.ZoneTask.invoke (angular2-polyfills.js:434)BrowserDomAdapter.logError @ :62706/nodelibs/angular2/src/platform/browser/browser_adapter.js:76
> angular2-polyfills.js:469 Unhandled Promise rejection: Template parse errors:
> Unexpected character "EOF" ("
>         <td>hello cell</td>
>     </tr>
> </tab[ERROR ->]"): ApplicationsTestComponent@4:5 ; Zone: angular ; Task: Promise.then ; Value: BaseExceptionconsoleError @ angular2-polyfills.js:469
> angular2-polyfills.js:471 Error: Uncaught (in promise): Template parse errors:(…)consoleError @ angular2-polyfills.js:471
> angular2-polyfills.js:469 Unhandled Promise rejection: Template parse errors:
> Unexpected character "EOF" ("
>         <td>hello cell</td>
>     </tr>
> </tab[ERROR ->]"): ApplicationsTestComponent@4:5 ; Zone: <root> ; Task: Promise.then ; Value: BaseExceptionconsoleError @ angular2-polyfills.js:469
> angular2-polyfills.js:471 Error: Uncaught (in promise): Template parse errors:(…)

**Expected/desired behavior**
No template error - it is perfectly valid HTML?

**Other information**
1. Behaviour present in beta 12, 13, 14 (that's how long i've been working against this lol)
2. Below is the host page

```
@{
    ViewData["Title"] = "Home Page";
    Layout = null;
}
<!DOCTYPE html>
<html lang="">
<head>
    <base href="/" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SPA</title>
    <script src="~/nodelibs/es6-shim/es6-shim.js"></script>
    <script src="~/nodelibs/systemjs/dist/system-polyfills.js"></script>
    <script src="~/nodelibs/angular2/es6/dev/src/testing/shims_for_IE.js"></script>
    <script src="~/nodelibs/angular2/bundles/angular2-polyfills.js"></script>
    <script src="~/nodelibs/systemjs/system.js"></script>
    <script src="~/nodelibs/rxjs/bundles/Rx.js"></script>
    <script src="~/nodelibs/angular2/bundles/angular2.js"></script>
    <script src="~/nodelibs/angular2/bundles/router.js"></script>
    <script src="~/nodelibs/angular2/bundles/http.js"></script>
</head>
<body>

    <cache vary-by="@Context.Request.Path">
        <app>
            Loading...
        </app>
    </cache>

    <script>

        var rootPath = "@Url.Content("~/")" + "nodelibs/";

        System.config({
            baseURL: rootPath,
            defaultJSExtensions: true,
            //map: {
            //     'rxjs/*': './nodelibs/rxjs/*.js',
            //     'angular/**/*': './nodelibs/angular/**/*.js'
            //},
            packages: {
                app: {
                    //format: 'register',
                    defaultExtension: 'js'
                }
            }
        });

        System.import("/app/boot").catch(console.log.bind(console));

    </script>
</body>
</html>
```

3. Here is my App.component.ts

```
import {Component, EventEmitter, OnInit, Input, Output, OnChanges, Inject} from 'angular2/core';
import {HTTP_PROVIDERS}    from 'angular2/http';
import { RouteConfig, RouterOutlet } from 'angular2/router';

import 'rxjs/Rx'; 

import {MenuService} from './Container/Menu/Services/MenuService';

import {ApplicationsTestComponent} from './applications/applicationtest.component';
import {SummaryComponent} from './Dashboard/Components/Summary.component';

@Component({
    selector: 'app',
    templateUrl: './app/app.html',
    providers: [RouterOutlet],
    directives: [SummaryComponent, ApplicationsTestComponent]
})
@RouteConfig([
        { path: '/', name: 'Summary', component: SummaryComponent, useAsDefault: true },
        { path: '/test', name: 'Test', component: ApplicationsTestComponent }
])
export class AppComponent implements OnInit {
   
    constructor() {
  
    }
    ngOnInit() {
   
    }
 }

```
4. It breaks at this moment when ApplicationsTestComponent is referenced.
5. It must find the HTML page because it is able to retrieve the HTML
6. The content of the HTML page it is failing to parse the following:

```
<table>
    <tr>
        <td>hello cell</td>
    </tr>
</table>
```

7. Really need better error messages because I don't know what I have done wrong.
8. The first page loads fine - but when I attempt to traverse to the 2nd page the template exception is triggered

**Many thanks and I will gladly provide/try anything you like**

**Best wishes,**
**Dan.**

**Comment by liquidboy** [comment]
for me I was getting the same error (but different html fragment) and it was because I had "Enable Browser Link" enabled in VS2015 when I was running it  ...

**Comment by energeticspark** [comment]
Hi @liquidboy,
I think you were probably right.  I recall installing extension "WebEssentials" and then clicking the live update button on the overlay that appears at the base of the page.  

I can't confirm 100% because in the end I just re-built my PC (thus the late reply).
I was due an upgrade anyway though let it be said I don't re-build to solve issues.

Perhaps it was just browser link but it is working fine just now without having actively disabled Browser Link in any settings after reinstall. 

I was so buzzed to get your reply - getting stuck for 2 weeks no fun.  

Thanks a lot!
Dan.

----------------------------------------------------------------------------------------------
Guess this issue can now be closed as a weird interaction between WebEssentials/BrowserLink/VS2015.  Hope this helps someone.
