### ISSUE TITLE
When the value of a input:text is invalid, why the value of the model is 'undefind'?

### ISSUE THREAD

**Issue by vrbvillor** [angular/angular#7991]
```HTML
<div class="Outer" ng-controller="CtrlMyApp">
<form name="LoginForm">
    <div class="TEXTCONTAINER">
        <input ng-class="judge();" ng-model="username" type="text" id="username" name="username" ng-pattern="/^[\w\d][\w\d\_\-]*(\@[\w\d][\w\d\-\_]+(\.[\w\d][\w\d\-\_]+)+)?$/i">
        <label for="username" ng-class="{TEXTLABEL:true}">用户名</label>
    </div>
</form>
</div>
```

```javascript
    angular.module('myapp', [])
        .controller('CtrlMyApp', ['$scope','$timeout',function($scope,$timeout) {
            $scope.username="123";
            var n=0;
            $scope.judge=function(){
                n++;
                console.log($scope.username,n);
                return "TEXTINPUT"+ ($scope.username=='' && '' || ' filled');
            }
        }]);
```

When I typing in the input:text, as soon as the value is not valid, the console will output "undefined" and a number. Why the username might be undefined? How can I get the exact value no matter when   the value is valid or not.

Thank you!!!!

**Comment by zoechi** [comment]
Looks like AngularJS 1.x to me. 
AngularJS 1.x issues are managed in https://github.com/angular/angular.js/issues

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question) or for Angular2 [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)
