### ISSUE TITLE
element.find is unnormal atfer refresh browser

### ISSUE THREAD

**Issue by andyandox** [angular/angular#7992]
please see https://plnkr.co/edit/DoYqJL?p=preview, the demo in plunker is run normally.I want to express that when I use this demo in my project which using angular-router and requireJS, I find the demo is normally after the first load, but when I press F5 to refresh browser, the alert cannot show.I test many times and finally find the element obj cannot find the children element.So, I don`t know if this is a bug, or just I have something wrong.Thanks.

**Comment by zoechi** [comment]
Looks like AngularJS 1.x to me. 
AngularJS 1.x issues are managed in https://github.com/angular/angular.js/issues

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question) or for Angular2 [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)
