### ISSUE TITLE
feature request(router): Asynchronous auxiliary routes

### ISSUE THREAD

**Issue by Richterrettich** [angular/angular#7993]
### Problem 

At the moment, it is not easily possible to load aux-components asynchronously. This is a problem when the aux-components are not yet present at compile time or lazy loading in general is required.  I think it is a valid feature for large sized apps.

### Current Workarround

There is the possibility to use a virtual proxy for the component (see here: http://blog.mgechev.com/2015/09/30/lazy-loading-components-routes-services-router-angular-2/), but it breaks the router tree and is generally cumbersome.

### What is the expected behaviour?

Generally,  I want to be able to configure aux-routes with a loader function. Something like this:
```javascript
@RouteConfig([{
    aux: 'testAux1',
    loader: () => System.import("./test.component.js").then(m => m["TestComponent"]),
    name: 'TestAux1'
}])
export class AppComponent{}
```

Let me know if you are okay with this feature. I think I can implement it.

**Comment by zoechi** [comment]
See https://docs.google.com/document/d/150lerb1LmNLuau_a_EznPV1I1UHMTbEl61t4hZ7ZpS0/edit#heading=h.eyde8v56ir1g April 4

> 
- Router update
  - Are simplifying aux routes and makeing them just routes.  They will behave in the same way.  The default route just has a blank name.
  - The canActivate API has been hard as it can't be injected.  Moving this to the parent so it can prevent lazy loading of code and you get full access to the injector.
  - All Routes are async routes which will aid in lazy loading.

**Comment by Richterrettich** [comment]
Well... this looks pretty promising. Thanks for pointing me to the weekly notes!
