### ISSUE TITLE
Proposal: Type-safe FormBuilder

### ISSUE THREAD

**Issue by laco0416** [angular/angular#7994]
## Motivation
The purpose is to gain benefits by the static type checking.

Currently, `FormBuilder` API takes control configurations as **Array**.

```ts
    this.loginForm = builder.group({
      login: ["", Validators.required],
      passwordRetry: builder.group({
        password: ["", Validators.required],
        passwordConfirmation: ["", Validators.required, asyncValidator]
      })
    });
```

The first element of configuration array is `value`, the second is `validator` and the third is `asyncValidator`. 
It's useful to writing code but isn't type-safe. The array is typed as `any[]`. 

## Design

<del>
I think there are two approaches for making it type-safe.

### class `ControlConfig`
One is using a class, `ControlConfig`. 

Example: 

```ts
    this.loginForm = builder.group({
      login: new ControlConfig("", Validators.required),
      passwordRetry: builder.group({
        password: new ControlConfig("", Validators.required),
        passwordConfirmation: new ControlConfig("", Validators.required, asyncValidator)
      })
    });
```

### interface `ControlConfig`
Another way is using an interface. This is like `Route` of angular2/router.

Example: 

```ts
    this.loginForm = builder.group({
      login: {value: "", validator: Validators.required)},
      passwordRetry: builder.group({
        password: {value: "", validator: Validators.required},
        passwordConfirmation: {value: "", validator: Validators.required, asyncValidator}
      })
    });
```

</del>

We can use `Control` instead of the config array. (thanks @DzmitryShylovich )

```ts
    this.loginForm = builder.group({
      login: new Control("", Validators.required),
      passwordRetry: builder.group({
        password: new Control("", Validators.required),
        passwordConfirmation: new Control("", Validators.required, asyncValidator)
      })
    });
```

## Pros.
- We can gain benefits of the static types 
- Types are good documentation

## Cons.
- Big breaking change
- Increase amount of code

Please tell me your impressions and thoughts.
Thanks.

**Comment by laco0416** [comment]
cc/ @mhevery @IgorMinar

**Comment by DzmitryShylovich** [comment]
There is already `Control` class with the following constructor signature
```
constructor(value?: any, validator?: ValidatorFn, asyncValidator?: AsyncValidatorFn);
````
which you can use instead of array:
```
this.loginForm = builder.group({
      login: new Control("", Validators.required),
      passwordRetry: builder.group({
        password: new Control("", Validators.required),
        passwordConfirmation: new Control("", Validators.required, asyncValidator)
      })
    });
```

**Comment by laco0416** [comment]
@DzmitryShylovich Oops! I forgot about `Control`. Thank you!

so my proposal can focus on "We should use `Control` instead of an array."

**Comment by mhevery** [comment]
@laco0416 I think this falls into the realm of opinion as we support both. I imagine that people with type language backgrounds will prefer your style, while JS developers will prefer the shorter untyped syntax.

I think the thing to do would be to create a PR which updates the API docs to make both of the modes explicit. Would you like to take on that?
