### ISSUE TITLE
Invalid HTML rendering in Angular 2?

### ISSUE THREAD

**Issue by Kettja12** [angular/angular#7995]
**Expected/desired behavior**
Should  template file be rendered  inside [router-outlet] -tags? 

**Steps to reproduce and a minimal demo of the problem**
@Component({'
    templateUrl:'app/invoicing.component.html',
    directives: [ROUTER_DIRECTIVES],
    providers: [
        ROUTER_PROVIDERS,
        CustomersService
    ] 
})

Template file: app/invoicing.component.htm

[h1]Start[/h1]'
[a [routerLink]="['Desktop']"]Desktop[/a]'
[a [routerLink]="['Customers']"]Customers[/a]'
[router-outlet][/router-outlet]'
[h3]end[/h3]'

Deskptop component:

@Component({
  templateUrl: 'app/desktop/desktop.component.html'
})
export class DesktopComponent { }

And its template;

[h2]Desktop[/h2]

**Current behavior**
Rendered following way, cached from Chrome.
[invoicing-app]
[h1]Start[/h1]
[a href="/desktop" class="router-link-active"]Desktop[/a]
[a href="/customers"]Customers[/a]
[router-outlet][/router-outlet]
[undefined _ngcontent-wbb-2=""][h2]Desktop[/h2][/undefined]
[h3]end[/h3]
[/invoicing-app]`

**Comment by brandonroberts** [comment]
This is intended behavior. The route is rendered next to the router outlet.

```html
<router-outlet></router-outlet>
<route></route>
```

**Comment by dominique-mueller** [comment]
I am also wondering why the route isn't rendered inside the router outlet. Any specific reasons for that?

**Comment by gdi2290** [comment]
it's not rendered within the element for animation reasons
