### ISSUE TITLE
Change detection not working in hybrid app

### ISSUE THREAD

**Issue by robianmcd** [angular/angular#7998]
**Steps to reproduce and a minimal demo of the problem**

In this plunker http://plnkr.co/edit/vEx5b94utZQBMU1lFyeL?p=preview
1. Click "Show Child" button
2. Click "Click Me" button

**Current behavior**

This will result in an upgraded ng1 component calling the following callback function in it's parent 
ng2 component.

```
setTest() {
    this.test = 'setTest() called';

    setTimeout(() => {
      this.test = 'setTimeout finished';
    });
  }
```

The `test` variable is bound to the view and the view ends up showing `'setTest() called'`.

**Expected/desired behavior**
The view should show that the test variable has been set to 'setTimeout finished'

**Other information**
This issue only happens if the child ng1 component is remove from the DOM with `ng-if` after it calls the callback in it's parent component. 
Clicking the "Show Child" button again after experiencing the issue will trigger change detection and show the expected value on the view. Manually trigging change detection with the `ChangeDetectorRef` service's `detectChanges()` function also will show the expected output on the view.

**Comment by guojenman** [comment]
related

https://github.com/angular/angular/issues/11572

https://github.com/angular/angular/issues/10208

**Comment by gkalpak** [comment]
I believe this has been fixed. If anyone is still having problems (with the latest version), please open a new issue.
