### ISSUE TITLE
WiiU Browser INVALID_STATE_ERR DOM Exception 11 from angular2-polyfills.js

### ISSUE THREAD

**Issue by headhunter45** [angular/angular#8000]
**Steps to reproduce and a minimal demo of the problem**

* Enable developer tools on the browser and connect to them from another computer.
* Open the live example from the 5 Min Quickstart. https://angular.io/resources/live-examples/quickstart/ts/plnkr.html
* Wait a few seconds and check the console output.  

**Current behavior**
The "Loading..." text stays on the screen and the app never loads.  There is an error in the console "INVALID_STATE_ERR: DOM Exception 11: An attempt was made to use an object that is not, or is no longer, usable."

**Expected/desired behavior**
The app should display "My First Angular 2 App" and there should not be errors in the console.

**Other information**
The error is reported from angular2-polyfills line 941. The browser is a fork of an older version of WebKit.

**Comment by zoechi** [comment]
Should the plunker contain anything?

**Comment by CaptainCodeman** [comment]
There have been problems with angular2-polyfills recently even in more mainstream browsers. You could try using core.js + a more up-to-date version of zone.js instead. Maybe try loading http://captain-codeman.appspot.com/ to see if that works to see if it works.

**Comment by headhunter45** [comment]
I've put in the correct plunker url.  I tried the cpatain-codeman url and I get a similar error in your vendor.js library.

**Comment by CaptainCodeman** [comment]
You may be faced with the task of figuring out which browser features are missing and need to be polyfilled if possible. I can't imagine there are going to be many people targeting WiiU browser and also using Angular 2 to provide much help though.

**Comment by headhunter45** [comment]
I've got it working with a hack.. The error only happens when patchClass tries to read the type of an XMLHttpRequests responseBlob property.  It's in the patchClass method iterating through the properties of an XMLHttpRequest instance.  What's an appropriate way to avoid reading this property there?  For now I've just added a check and if the property name is responseBlob I just return.

**Comment by tkazec** [comment]
Unfortunately this is also an issue with Android 4.0 and 4.1. The captain-codeman example has the same issue. Problem with Zone.js?

**Comment by headhunter45** [comment]
This does't happen in an [NWF app](https://en.wikipedia.org/wiki/Nintendo_Web_Framework).  In that case you just need some extra polyfills (es5-shim, es6-promise, and requestAnimationFrame) and to remove the <base> tag since you're serving from a file url.

The DOM error only occurs for me when using the web browser directly.

That specific property was proposed as a part of XMLHttpRequest2 with this behavior when the object wasn't in a state where it should be read from.  It has since been removed.

Would it be acceptable to throw a try/catch around that check?

**Comment by tkazec** [comment]
Can confirm skipping `responseBlob` fixes things, thanks @headhunter45 – so for now I've switched our `package.json` to reference our temporary fork: https://github.com/Buzzvil/zone.js/commit/1c3f040cba8a1745829c0f8143620564c250b895

**Comment by yulonh** [comment]
I fixes it by this way:
```javascript
 ~function (w) {
    var xhr = new w.XMLHttpRequest();
    if (Object.keys(xhr).indexOf('responseBlob') !== -1) {
      var _XMLHttpRequest = w.XMLHttpRequest;
      w.XMLHttpRequest = function () {
        var _xhr = new _XMLHttpRequest();
        delete _xhr.responseBlob;
        return _xhr;
      };
    }
  }(window);```

**Comment by rhushi-lokhande** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#Methods

**Comment by vicb** [comment]
obsolete
