### ISSUE TITLE
ngUpgrade: $digest already in progress 

### ISSUE THREAD

**Issue by christopherthielen** [angular/angular#8004]
In an ng-upgrade application, a `$digest already in progress` error is thrown in some specific case.

**Steps to reproduce and a minimal demo of the problem**

From within a downgraded ng2 component:
- Inject ng1 services: `$http` and `$location`
- Fetch some data using `$http`
- Chain a `.then` off the `$http.get()` which updates the url using `$location.url('/foo')`

http://plnkr.co/edit/KBcwSi?p=preview 

_What steps should we try in your demo to see the problem?_
Click Button #3 of the NG2 component

**Current behavior**
HTTP data is fetched, logged to console, and the url updates to '/foo'. The `$digest already in progress` error appears in the console.

**Expected/desired behavior**
HTTP data is fetched, logged to console, and the url updates to '/foo'.  No `$digest` errors should appear in console

**Other information**

These steps to reproduce were distilled down from UI-Router's hybrid ng1/ng2 sample app.  

- This happens against Angular 2 beta 14
- If you only fetch HTTP without location, or only update the location without chaining off a $http the error does not occur
- If you chain off a `$timeout` instead of a `$http.get()` the error does not occur
- If you initiate the promise chain from within the ng1 context (instead of inside the ng2 component), the error does not occur.

@ericmartinezr helped me replace angular2-polyfills with core.js and zone 0.6.10 and the issue still occurs.  Here is that plunk:  http://plnkr.co/edit/Hxt062?p=preview

Possibly related? #7666

**Comment by dnear** [comment]
I am having this issue aswel. I don't notice any after effects from it though.

**Comment by adamduren** [comment]
I have this issue as well when using `$state.go` from `ui-router`. Unfortunately the only thing I could find to fix it was to upgrade the Controller to a Component.

**Comment by thelgevold** [comment]
I am seeing $digest issues as well wen bootstrapping an A1 application using ngUpgrade.
```
 ng1compilePromise = new Promise((resolve, reject) => {
      ng1Module.run([
        '$injector',
        '$rootScope',
        (injector: angular.IInjectorService, rootScope: angular.IRootScopeService) => {
          ng1Injector = injector;
          ngZone.onMicrotaskEmpty.subscribe(
              {next: (_) => ngZone.runOutsideAngular(() => rootScope.$apply())});
          UpgradeNg1ComponentAdapterBuilder.resolve(this.downgradedComponents, injector)
              .then(resolve, reject);
        }
      ]);
    });
```

I have pasted the code block where it happens above.

Isn't it considered a bad practice to call ```$apply()``` directly. I realize this is a bit different, but I have generally stayed away from direct call like this, and instead wrapped my code in a $timeout or similar.

**Comment by thelgevold** [comment]
My issue seems to be related to a $state.go in ui-router as well. Not seeing the error if I navigate directly to the final url and bypassing the $state.go step.

**Comment by andreialecu** [comment]
I'm having the same issue and it is completely killing performance for my app after the error occurs.

However, changing the `rootScope.$apply()` to a simple `$timeout(() => {});` call seems to fix this, and is also the recommended workaround as per http://stackoverflow.com/questions/12729122/angularjs-prevent-error-digest-already-in-progress-when-calling-scope-apply

I'm going to submit a PR for this.

**Comment by thelgevold** [comment]
I already submitted a PR

**Comment by thelgevold** [comment]
It's pending review

**Comment by andreialecu** [comment]
@thelgevold great! didn't see it.

**Comment by andreialecu** [comment]
@thelgevold I already had a [PR submitted and accepted](https://github.com/angular/angular/pull/6386) for that particular line of code as well. 

Quite a buggy line looks like. :smile:

**Comment by mhevery** [comment]
fixed by https://github.com/angular/angular/pull/6386

**Comment by christopherthielen** [comment]
#9054
