### ISSUE TITLE
Problem with style on 'router-link-active' class

### ISSUE THREAD

**Issue by sanket30** [angular/angular#8005]
**Steps to reproduce and a minimal demo of the problem**
 https://plnkr.co/edit/IyQ9ifja87KE8TtmV20w

_What steps should we try in your demo to see the problem?_
1) Click on `contact` navbar tag (color doesn't change to blue)
2) Now click outside (color changed to blue)

**Current behavior**
style `router-link-active` is not getting applied even I can see that class in DOM, and once I clicked outside its getting applied.

**Expected/desired behavior**
style `router-link-active` should get applied once I click on `contact` navbar.

**Comment by zoechi** [comment]
It's working fine when you remove
