### ISSUE TITLE
Bootstrap vs Providers

### ISSUE THREAD

**Issue by wizardnet972** [angular/angular#8007]
Hey all,

for my understending, I can inject the service in bootstrap application or providers section in component.
my question is: what is the best practices for inject service?
and my another question is if i inject in component providers section, then can i use it on different component without loading this injection/service again?

**Comment by Hachero** [comment]
It depends on how you want the service to be used; if you bootstrap it, it'll be available to the whole program, but behaves a little differently.  If in parent; it's available to all children components.  I think the behavior in bootstrapping is singleton ... 
>I did however notice one important difference between the two approaches. Registering the provider at the **_app level creates the injected dependency as a singleton for the entire application_**, but providers at the **component level** result in **_new instances at the component level._** Objects are created new for every injection per component, so you can't use them to store state at the application level, but the hierarchy within the component still share the same instance. I guess you can view it as a local, component level, "Singleton". This is different from Angular 1.x where you only have pure singleton dependencies. from [Torgeir Helgevold](http://www.syntaxsuccess.com/viewarticle/dependency-injection-in-angular-2.0)

I hope this helps.  Cheers

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by pkozlowski-opensource** [comment]
See https://angular.io/docs/ts/latest/guide/hierarchical-dependency-injection.html

Thnx @zoechi
