### ISSUE TITLE
<div style="color: {{ color }}"> does not work in Safari

### ISSUE THREAD

**Issue by sod** [angular/angular#8009]
Angular Version: angular2@2.0.0-beta.14

If you use this expression in your template:
```html
<div style="color: {{ color }}">Text</div>
```

Works in:
* firefox 45.0.1
* chrome 49.0.2623.112

Doesn't work in:
* Safari (9.0.3) 
* iOS Safari (iOS 9.3.1)

Plunkr: http://plnkr.co/edit/YuVbxEmsFDjnJDbrVfSH?p=preview (color should alternate between green and black)

Angular2 does `documentElement.style = 'color: red'`. That operation is allowed in chrome and firefox. In Safari `style` is read only.

Chrome:
![image](https://cloud.githubusercontent.com/assets/905328/14434142/92c5a0e0-0011-11e6-854f-7c00b3232bd7.png)

Safari:
![image](https://cloud.githubusercontent.com/assets/905328/14434133/88ba375a-0011-11e6-8982-f43b4f75be59.png)

**Comment by sod** [comment]
I am aware that i am able to write `<h1 [style.color]="color">`. But the behavior above feels like a trap because it works in the browser most developers use (chrome) and doesn't work in a browser many customer use (iOS) :)

**Comment by pkozlowski-opensource** [comment]
I don't think we should special-case this in Angular. What you can do (and it should work cross-browser) is to use NgStyle: https://angular.io/docs/ts/latest/api/common/NgStyle-directive.html

**Comment by robwormald** [comment]
Agree with @pkozlowski-opensource here. Where possible, use the [style.whatever] or ngClass syntax. Doing so escapes the actual property and prevents weird and wacky behavior.

**Comment by pkozlowski-opensource** [comment]
Going to close this one as I don't think we should be masking how browsers are handling DOM properties.
