### ISSUE TITLE
Broken links on website documentation

### ISSUE THREAD

**Issue by steven-fernandez** [angular/angular#8014]
Broken links on website documentation

To reproduce go to:

[https://angular.io/docs/ts/latest/glossary.html#!#A](https://angular.io/docs/ts/latest/glossary.html#!#A)

Scroll down to:

Data Binding

All of those links you can see are broken links 404

**Comment by robwormald** [comment]
thanks @steven-fernandez - could you open this issue on the https://github.com/angular/angular.io repo?

**Comment by steven-fernandez** [comment]
Done
