### ISSUE TITLE
StealJS support

### ISSUE THREAD

**Issue by wrldtrvllr** [angular/angular#8015]
Has anybody considered/tried supporting StealJS (http://stealjs.com/) as an additional module loader option for Angular2 apps? StealJS promises to have superior performance compared to SystemJS and uses plain npm modules instead of introducing its own package manager. In my opinion, this makes it quite desirable to use. 

I've done some experiments recently, but wasn't able to make it work. However, as the API is kind of similar to SystemJS, it shouldn't be that much of an effort to support it.

What's your opinion in supporting StealJS as an alternative to SystemJS? Any ideas/suggestions?

**Comment by gdi2290** [comment]
if StealJS supports CommonJS or ES6 then Angular 2 should work with it via npm

**Comment by robwormald** [comment]
There shouldn't be anything we need to do on our end to make Steal work, but I don't think we have the bandwidth to "support it" it any official way (eg, writing docs about how to use it). @wrldtrvllr i'm going to close this as its not really actionable at the moment, but if there's a non-invasive change we need to make on the angular end, please ping me here and i'll re-open it.

**Comment by wrldtrvllr** [comment]
Sure, thanks for your comments. I'll have a deeper look at it and will come back here if necessary.
