### ISSUE TITLE
how do i use jade in angular?

### ISSUE THREAD

**Issue by THCloud** [angular/angular#8018]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here, see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. 

**Steps to reproduce and a minimal demo of the problem**

_Use https://plnkr.co or similar -- try this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5_

_What steps should we try in your demo to see the problem?_

**Current behavior**

**Expected/desired behavior**

**Other information**

Hi,
I'm a new learner, and recently I'm trying to do something with MEAN(mongodb, express, angular, node)
For the template, I used Jade. And I found a problem with angular+express+jade:
As I can't send jade to browser, I write like this in Angular's route.js
`angular.module('myApp')`
`.config([$routeProvider, $locationProvider,function($routeProvider, $locationProvider){`
`$routeProvider.when('/', {templateUrl: '/', controller: 'indexCtrl'})`
`.when('/errror', {templateUrl: '/error', controller: 'errorCtrl'})`
`...`

well, templateUrl in angular's route.js is matched with express router.

and I write an ajax method in errorpage, I just wanna try the ajax communication with angular and express.
I write like this in express' route.js

`var express = require('express');`
`var router = express.Router();`
`...`
`router.get('/error', function(req, res, next) {`
`res.render('error.jade');`
`});`
`router.post('/error', function(req, res, next){`
`console.log('I have recieved ajax request.');`
`res.json({ state: 'success' });`
`});`
`...`

And I just found that , when i jump to error page, the ajax request send automaticlly although I haven't call the ajax method !!!

I don't know what problems in it. I think that maybe something wrong with my angular's route.js

And I don't think my angular route.js is a good design. But I haven't found another solution when using jade. 

So, any better solution for my route.js to solve the problems with jade ??

**Comment by robwormald** [comment]
The *first* line of the issue template you ignored says `"IMPORTANT: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here"` - please take this question to StackOverflow or similar (also, this is the Angular2 repo)
