### ISSUE TITLE
fix(validators): NgControlName doesn't expose error object of async validator anymore

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular#8022]
Having an async validator like this:

```
function checkSomethingAsync() {                                                                                                       
  return (c: Control) => {                                                                                                                                                
    return checkAsync(c.value)                                                                                                                      
              .map(response => !response.error ? null : {                                                                                                     
                asyncError: {                                                                                                                     
                  valid: false                                                                                                                             
                }                                                                                                                                             
              });
  };
}                                                                                                                                             
```

And a validator directive like this:

```
@Directive({
  selector: 'asyncValidator',
  providers: [
    provide(NG_ASYNC_VALIDATORS, {useExisting: forwardRef(() => AsyncValidator), multi: true})
  ]
})
class AsyncValidator {
   constructor() {
     this._validate = checkSomethingAsync();
   }
   validate(c) {
     return this._validate(c);
   }
}
```

I could use the error information exposed on `ngControl` to display error messages like this:

```
<input ngControl="foo" #foo="ngForm" asyncValidator>
<p *ngIf="foo.errors.asyncError">Some error message</p>
```

**This worked in beta.6**, however, in the latest beta (tbh I'm not sure when this changed), the error object of async validators is not exposed on `foo.errors` anymore. It now has information about the observable state.

```
errors {
  _isScalar: false
  operator: MapOperator
  source: Observable
}
```

Unfortunately, the same structure is exposed in `foo.control.errors`.

This seems like a bug **and a breaking change** to me, as there's currently no way to receive information about the error object of the async validator. It also overrides the errors that have been exposed by synchronous validators before.

/cc @vsavkin

**Comment by vsavkin** [comment]
I don't think there have been any changes to how we run async validations in the last few releases. 

/cc @kara

**Comment by PascalPrecht** [comment]
I couldn't find them either, but I can confirm that with beta.6, error objects of asynchronous validators have been resolved and exposed, not it's just the observable..

**Comment by choeller** [comment]
@PascalPrecht Can you try to just use the `errors` property instead of `errors.asyncError`? Or is `asyncError` your own error-code? For me async Validations work perfectly well. This code is running on beta.15:
```ts
@Directive({
  selector: '[async-email-validator]',
  providers: [
    provide(NG_ASYNC_VALIDATORS, {useExisting: forwardRef(() => AsyncEmailValidator), multi: true})
  ]
})
export class AsyncEmailValidator {

  validate(control) {
    console.log("Going to validate EMAIL")
    let promise = new Promise((resolve, reject) => {
      setTimeout(() => {
        let result = null;
        var re = /^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$/i;
        if (control.value !== '' || !re.test(control.value)) {
          result = {"invalidEMail": true};
        } else {
        }
        resolve(result);
      }, 500);
    });
    return promise;  }
}
```
```html
      <input type="text"
             id="assignee_email"
             class="form-control"
             ngControl="email"
             async-email-validator
             #email="ngForm"/>
      <show-error [control]="email"></show-error>

      <div *ngIf="email.errors && email.errors.invalidEMail"> 
        Invalid E-Mail!
      </div>
```

**Comment by PascalPrecht** [comment]
@choeller `asyncError` is my custom error object.

**Comment by choeller** [comment]
@PascalPrecht  Hmm, interesting. So for me it's working as expected.  Are you mixing sync and async validations? Maybe your issue is somehow connected to the problems I experience here: https://github.com/angular/angular/issues/8118

**Comment by PascalPrecht** [comment]
@choeller it's not related. I actually think that #8118 works as expected. I have a sync email validator that checks if the value is an email address and *then* the async validator kicks in that checks if the email address is available.

But again, the async validator error, overrides the sync error object.

**Comment by PascalPrecht** [comment]
Lemme try to come up with a plunk

**Comment by choeller** [comment]
alright... about https://github.com/angular/angular/issues/8118: your case works as you kick out a sync validation first. starting with async validations doesn't work (see the plnkr. connected to the issue)

**Comment by choeller** [comment]
@PascalPrecht Here is what's working for me: http://plnkr.co/edit/9ICedquWTOJu5E3x2kqM?p=preview

**Comment by choeller** [comment]
@PascalPrecht @vsavkin 

Now I could also reproduce the problem. It's a really weird behaviour, that only occurse, when returning Observables and using the map-method. This code works:
```
@Directive({
  selector: '[asyncEmailValidator]',
  providers: [
    provide(NG_ASYNC_VALIDATORS, {useExisting: forwardRef(() => AsyncEmailValidator), multi: true})
  ]
})
export class AsyncEmailValidator {
  validate(control) {
    let result = null;
    var re = /^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$/i;
    if (control.value !== '' && !re.test(control.value)) {
      result = {"invalidEMail": true};
    } 
    return Observable.of(result);
  }
}
```
but this code - that is logically the same, only return `true` and `false`. So the `map`-method seems to be ignored!
```
@Directive({
  selector: '[asyncEmailValidator]',
  providers: [
    provide(NG_ASYNC_VALIDATORS, {useExisting: forwardRef(() => AsyncEmailValidator), multi: true})
  ]
})
export class AsyncEmailValidator {
  validate(control) {
    let result = true;
    var re = /^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$/i;
    if (control.value !== '' && !re.test(control.value)) {
      result = false;
    } 
    return Observable.of(result)
     .map(result => {
       result === false ?  {"invalidEMail": true} : null;
     });
  }
 
}
```
See this plnkr for a live demo:
http://plnkr.co/edit/yAYubFVF4LTnzb6QonNo?p=preview

**Comment by choeller** [comment]
Hi again, I found the bug in the code and just created a PR for it. Could any of you have a look at it? As it's my first PR I'm not sure if I considered everything...
