### ISSUE TITLE
Controllers instantiated in other iframe is not accepted

### ISSUE THREAD

**Issue by ltearno** [angular/angular#8024]
When a Controller instantiated in another iframe (i am using GWT super dev mode) is given in a directive of another controller, it gets rejected as non valid with the following message :

`Unexpected directive value 'xxx' on the View of component 'yyy'`

This is because when the directive is checked in the `isValidType(value)` (in src/compiler/runtime_metadata.ts) the implementation of that function uses the `instanceof` operator, which is not very kind with cross iframe prototypes.

One solution would be to use `typeof` instead of comparing the prototypes with `instanceof`. I implemented a patch and it works perfectly.

If you want i can make a pull request...

**Comment by vicb** [comment]
Could you please add a repro in a plunker ?

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
