### ISSUE TITLE
In Firefox, select tags do not update the controls object in ngControls

### ISSUE THREAD

**Issue by mLaird** [angular/angular#8030]
In beta.14, when a user selects from a select tag, in Firefox, the controls object does not update the value of the element, nor other properties like _pristine and _touched.  All these properties are correctly updated in the controls object for a form's input tags, but not for select tags. No Console error occurs.  The problem is in the properties of the controls object.  For example, when country is selected in a select and an address is entered in an input:
controls: Object
  country: Object
    _pristine: true
    _touched: true
    _value: ""
  address: Object
    _pristine: false
    _touched: true
    _value: "4 Main Street" 

The HTML for this situation is:
              <label for="country">COUNTRY</label>
              <select name="country" id="country" md-select [(value)]="residenceForm.country" ngControl='country' #country="ngForm" [ngFormControl]="residenceForm.controls['country']">
                <option *ngFor="#country of countries" [ngValue]="country.name">
                  {{country.name}}
                </option>
              </select>

The controls object properly updates in Chrome. I have not tested the update of the controls object for radio buttons and check boxes, nor have I tested it in the Edge browser.

**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here, see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. 

**Steps to reproduce and a minimal demo of the problem**

_Use https://plnkr.co or similar -- try this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5_

_What steps should we try in your demo to see the problem?_

**Current behavior**

**Expected/desired behavior**

**Other information**

**Comment by mLaird** [comment]
The HTML was erased / altered when posted. Here it is without tag symbols. I hope its helpful.

              label for="country" class="selectLabelAdjust">COUNTRY label
              select name="country" id="country" md-select [(value)]="residenceForm.country" ngControl='country' #country="ngForm" [ngFormControl]="residenceForm.controls['country']"
                option *ngFor="#country of countries" [ngValue]="country.name"
                  {{country.name}}
                option
              select

**Comment by ericmartinezr** [comment]
Related to https://github.com/angular/angular/issues/6573

**Comment by mLaird** [comment]
Additionally on page load, I found that Chrome does not populate any selection from the array of selections in a select tag, Firefox populates the last item in the selection array, and Edge populates the first item in the array of selections.

**Comment by zarkosusnjar** [comment]
This has been fixed in beta.16 and later. Input element change detection in IE and Firefox still doesn't work, but you created an issue for select so you can close this one.

**Comment by mLaird** [comment]
close #8030
