### ISSUE TITLE
Whitespace in end of templateUrl declaration = blank page

### ISSUE THREAD

**Issue by jahala** [angular/angular#8033]
I found this bug when i had an actual whitespace at the end of a filename (app.html ) .. I'm on mac and created the file from sublime text, which resulted in this strange filename.. And this was driving me insane for two hours. After I found the bug I tested with adding a whitespace in the declaration and it produced the same error (displays nothing on page load).

```
@Component({
  selector: 'app',
  templateUrl: 'client/app.html ', <-- whitespace at the end after filename
})
```

Perhaps strip whitespaces from the declaration or give a warning of some kind?

**Comment by ericmartinezr** [comment]
@jahala did you check the console? This [plnkr](http://plnkr.co/edit/kjYQ31NkYY0dbPiSmrJ3?p=preview) fails with `Failed to load app.html%20`

**Comment by jahala** [comment]
This was served through meteor .. I'm guessing that concealed the error then.. thanks @ericmartinezr
