### ISSUE TITLE
IE11 in Forms demo - Select does not update

### ISSUE THREAD

**Issue by MichaelChambers** [angular/angular#8034]
From the forms page: https://angular.io/docs/ts/latest/guide/forms.html
The live example link is https://angular.io/resources/live-examples/forms/ts/plnkr.html
When I open up the Live Example link in IE11, and then change the Power, nothing updates on the page.
When I do the same in Chrome, the diagnostic JSON on the 3rd hero form updates, as well as the 3rd form's Power select.

This is using angular2@2.0.0-beta.14

When I found this, I was following along with the demo step and running locally using IE11. Everything went well until I was in the 2-way data binding section. I replaced the 3 divs and then it went askew when I read the "If we ran the app right now and changed every Hero model property, the form might display like this:" since my select wouldn't update.

**Comment by MichaelChambers** [comment]
Probably the same as https://github.com/angular/angular/issues/8030

**Comment by MichaelChambers** [comment]
Sorry, just the same as this older issue: https://github.com/angular/angular/issues/6573

**Comment by kara** [comment]
Okay, closing as a duplicate. We should be able to look into it soon.
