### ISSUE TITLE
XHR error loading jspm_packages/npm/rxjs@5.0.0-beta.6/subject/ReplaySubject.js

### ISSUE THREAD

**Issue by playground** [angular/angular#8036]
Just upgraded to beta.14, looks like error may have been introduced prior to rxjs@5.0.0-beta.6.  Not sure if this is a rxjs issue.

Error loading jspm_packages/npm/rxjs@5.0.0-beta.6/subject/ReplaySubject.js as "rxjs/subject/ReplaySubject" from jspm_packages/npm/angular2@2.0.0-beta.14/src/http/backends/mock_backend.js

**Comment by playground** [comment]
The issue was resolved by updating mock_backend

import { ReplaySubject } from 'rxjs/subject/ReplaySubject';

to

import { ReplaySubject } from 'rxjs/ReplaySubject';

**Comment by pkozlowski-opensource** [comment]
Sounds like it was a support question about setup and it got resolved. Closing.
