### ISSUE TITLE
html5 data-attribute templating error when inside *ngFor loop

### ISSUE THREAD

**Issue by MarkPieszak** [angular/angular#8039]
_What steps should we try in your demo to see the problem?_
http://plnkr.co/edit/jAcqi6HWvkMuBTlu9q7b?p=preview
Check the console

**Current behavior**

I'm creating a simple `*ngFor` loop and I put a **`[data-test]=""`** attribute on it.

      <div *ngFor="#item of items" [data-test]="item">
	    {{ item }} 
	  </div>

The result is the template erroring out stating:

    Can't bind to 'data-test' since it isn't a known native property
    <div *ngFor="#item of items" [ERROR ->][data-test]="item">

**Expected/desired behavior**
The ability to be able to bind a data-attribute without having to do `[attr.data-test]`

Is this the desired behavior? It seems unnatural to have to state `[attr.something]` if you want to just create an attribute on the fly.

**Comment by zoechi** [comment]
`<div *ngFor="#item of items" [attr.data-test]="item">`

Error messages are quite easy to search for and this is a common one. 

GitHub issues are for bug reports and feature requests.
For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by MarkPieszak** [comment]
@zoechi I was posting it as a Bug request, although it might be common why is this syntax preferred? It seems sort of unnecessary to do `attr.`

**Comment by pkozlowski-opensource** [comment]
> although it might be common why is this syntax preferred? It seems sort of unnecessary to do attr

`[foo]="exp"` means "propagate value of `exp` evaluation to the `foo` _property_". If you want to influence _attribute_ value you need to use `[attr.foo]`.

Closing as invalid.

**Comment by MarkPieszak** [comment]
@pkozlowski-opensource Ok I understand then, I might have to put in some information into the docs to explain this better. That's what I assumed, I just didn't understand why it was being done that way right away. Thanks guys

**Comment by pkozlowski-opensource** [comment]
@MarkPieszak I think it is well documented in https://angular.io/docs/ts/latest/guide/template-syntax.html
Feel free to send a PR if you believe that things are missing in the referenced doc.

**Comment by MarkPieszak** [comment]
Oh wow the doc has way more in it than I remembered, nevermind then :+1: It's been a while didn't know it got big updates! Sorry to bother you, definitely not a bug then ;)
