### ISSUE TITLE
Unit testing - Integration with Karma?

### ISSUE THREAD

**Issue by vb8190** [angular/angular#8042]
We have an enterprise application written in angular 1.4. All our unit tests are written using jasmine and utilize karma as test runner and then karma-coverage to display code coverage report and it works great and is a complete solution. We are now trying to move towards angular 2.0 framework utilizing typescript but I did not find any mention of how to integrate unit tests with karma? To be able to execute unit tests and capture the coverage in some kind of reports is a key thing for us. The examples shown in angular 2 guide talk about creating a a unit-test.html page and then manually loading systemsJS and test files and that is fine but it then does not show how to achieve code coverage, if there is a need?

If there was a feature or plugin to enable angular2 to work with karma test runner then code coverage can be achieved through karma-coverage plugin and there is no need to have development teams create manual test html pages, just to execute their unit tests.

**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here, see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. 

**Steps to reproduce and a minimal demo of the problem**

_Use https://plnkr.co or similar -- try this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5_

_What steps should we try in your demo to see the problem?_

**Current behavior**

**Expected/desired behavior**

**Other information**

**Comment by ericmdantas** [comment]
See if this helps: https://github.com/ericmdantas/angular2-typescript-todo

**Comment by ericmartinezr** [comment]
You can see also Julie Ralph's repo https://github.com/juliemr/ng2-test-seed and her [talk at AngularConnect 2015](https://www.youtube.com/watch?v=C0F2E-PRm44)

**Comment by pkozlowski-opensource** [comment]
Thnx for chiming in @ericmdantas and @ericmartinezr 

@vb8190 please don't post general support question on the GitHub issue tracker, see: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
