### ISSUE TITLE
ngClass cause template parse error if the CSS rule contains dashes

### ISSUE THREAD

**Issue by NoNameProvided** [angular/angular#8043]
**Steps to reproduce and a minimal demo of the problem**

Try to set a css rule name containing one or more dash on any element with ngClass.

Example:   `[ngClass]="{ruleWith--Dash: true}"` 

[Here is the modified version of the 5 min quickstart what shows the problem](http://plnkr.co/edit/4fl3tiIOHeGlOYQvaSRf?p=preview), all I did is: 

- added two css rules to the styles.css file (`ruleWith--Dash` and `ruleWithOutDash`) 
- added the problematic ngClass snippet to the template in `app/app.component.ts`  

_What steps should we try in your demo to see the problem?_

Open the snippet and see that the app is not loading. Open the console to see the template errors. Change the `ruleWith--Dash` to `ruleWithOutDash` and see that the app loads and the rule is applied. 

**Current behavior**

A template error is raised when a css name with dash is present in an `ngClass` directive. 

**Expected/desired behavior**

The `ngClass` directive should be able to apply any rule with dashes in their names. 

**Other information**

This issue could block any migrating process or project where developers use or want to use the BEM conventions to write their CSS.

**Comment by pkozlowski-opensource** [comment]
What are you passing to the `NgClass` directive is a JS object literal. In JS you can't have unquoted object keys with `-`, try this in your favourite console: `var bam = {fob-bar: false};`. 

If you want to use dashes, you need to quote them: `var bam = {'fob-bar': true};`: http://plnkr.co/edit/Tjj3aSUnhG9Wmj632tmv?p=preview

Closing as invalid.
