### ISSUE TITLE
Angular2 routing stops working after a few clicks in IE10

### ISSUE THREAD

**Issue by yoxel** [angular/angular#8046]
Copying the details from the StackOverflow question:
http://stackoverflow.com/questions/36460640/angular2-routing-stops-working-after-a-few-clicks-in-ie10

We're experiencing an issue in IE10, using Angular2(Dart). Routing stops showing corresponding views after 3-4 clicks.

Test case:
https://github.com/danbilbo/route-example-for-ie10

IE10 VM can be downloaded from here:
https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/windows/

**Steps to reproduce and a minimal demo of the problem**

_Use https://plnkr.co or similar -- try this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5_

_What steps should we try in your demo to see the problem?_

**Current behavior**

**Expected/desired behavior**

**Other information**

**Comment by zoechi** [comment]
I experimented quite a bit with the repo and I can confirm that it works well in Chrome and Edge but brings down IE10 pretty hard. Sometimes I even had to restart the VM I use to test IE10, otherwise I wasn't even able to reload the page because the browser stopped responding.  
The repo is quite a small and basic routing example.

**Comment by pcroc** [comment]
We find our SPA performs awfully in IE10 when in dev mode, but seems to work fine in production mode. You could try calling enableProdMode to see if it makes any difference.

**Comment by yoxel** [comment]
In Angular2Dart we see this:

@Deprecated('Do not use this function. It is for JS only. There is no alternative.')
void enableProdMode() {}

**Comment by zoechi** [comment]
Looks similar #8122 but not as extreme.

**Comment by zoechi** [comment]
@yoxel do you call `enableProdMode()`?

**Comment by yoxel** [comment]
@zoechi I commented above re: 

@Deprecated('Do not use this function. It is for JS only. There is no alternative.')
void enableProdMode() {}

Would it make any difference if used this? Am I missing something?

**Comment by zoechi** [comment]
@yoxel I saw the comment, I just wonder why you get the message if you don't use it.

**Comment by yoxel** [comment]
@zoechi wait, what message? We're not getting nay message. @pcroc asked if we can turn it on and we simply looked into the source code and saw that annotation there.

**Comment by zoechi** [comment]
@yoxel 

> @Deprecated('Do not use this function. It is for JS only. There is no alternative.')
void enableProdMode() {}

**Comment by zoechi** [comment]
@yoxel got it. I Dart there is no `devMode' therefore nothing to switch`

**Comment by vicb** [comment]
obsolete
