### ISSUE TITLE
Forms - required but empty type=number still valid

### ISSUE THREAD

**Issue by MichaelChambers** [angular/angular#8048]
For this plunk: http://plnkr.co/edit/0UAKr1OGulovFUefmMDt?p=preview
I edited the forms example plunk to add a new number property, strength.

Removing the 80 strength value changes
spy.className to: form-control **ng-valid** ng-dirty ng-touched 
strength.valid: **true** 
strength.pristine: false

I thought it would change it to ng-invalid
If on the HTML's line 36 I change the input's type to text instead, and then remove the 80 strength, then I get the expected behavior of ng-invalid

spy.className: form-control ng-dirty **ng-invalid** ng-touched 
strength.valid: **false** 
strength.pristine: false

Using Chrome and 2.0.0-beta.14

**Comment by ericmartinezr** [comment]
dup of https://github.com/angular/angular/issues/6932 and https://github.com/angular/angular/issues/6248

**Comment by MichaelChambers** [comment]
Ah, thanks @ericmartinezr , sorry about that.
