### ISSUE TITLE
RouterLink breaks routes by replacing slash with %2F

### ISSUE THREAD

**Issue by KevinSleegers** [angular/angular#8049]
Since the latest Angular2 version (2.0.0-beta.14) it is possible to have query parameters that contain multiple slashes, like /foo/bar.

This works great, however whenever I use a parameter with multiple slashes within a RouterLink link, it escapes the `/` with `%2F` causing the routes to not work anymore on reload.

My link looks like this: `<a [routerLink]="['/Page', {page: page.url | slug}]" class="list-group-item">{{ page.title }}</a>`

Inside of the 'slug' pipe I even `URIDecode` the string, and when I log it it is correct. It would log something like `/pages/level-1/`, but when I inspect the actual `a` tag on the page it says `href="/pages%2Flevel-1"`.

I'm pretty clueless, because even when I print the value of `{{ page.url | slug }}` within my HTML template, it returns the url with slashes. So it seems that the LinkRouter component is escaping the url again.

**Comment by CaptainCodeman** [comment]
That is correct behavior (escaping special characters). You need to use wildcard matching `/*page` instead for the parameter if you don't want it to see path separators as separate route segments.

**Comment by KevinSleegers** [comment]
You're a life saver! Thank you so much. I did take a look at the documentation, but didn't find anything on a wildcard for situations like these. 

Thanks again! 👍

**Comment by theRealAbdurrahman** [comment]
@CaptainCodeman 
I'm facing this exact problem, and I don't understand where to use `/*page`. 
I tried to use it in the routing module 
``` 
{
    path: '/*page',
    loadChildren: 'page.component.ts'
  },
```
and in the routerLink itself `[routerLink]="['/*Page']`
with no luck.
It seems like I don't get your answer, would you please elaborate?.
Thank you.

**Comment by mlc-mlapis** [comment]
@theRealAbdurrah what is the syntax as you used above: `path: '/*page'`?

**Comment by CaptainCodeman** [comment]
Sorry @theRealAbdurrahman, I stopped using Angular completely.

I now use a combination of universal-router, redux-first-routing and lit-html which works great and gives tiny app-bundles (the entire app is usually 20kb - 30kb).
