### ISSUE TITLE
Empty, terminating StarPathSegment should not be appended to the URL as `null`.

### ISSUE THREAD

**Issue by emesx** [angular/angular#8052]
Given a wildcard route `const Route(path: '/test/*any', name: 'Test', ...)` and a navigation `router.navigate(['/Test'])` the browser url ends up with something like `/test/null`, because `any` is not specified.

This is caused by this piece of code: [param_route_path.ts#L178](https://github.com/angular/angular/blob/60727c4d2ba1e4b0b9455c767d0ef152bcedc7c2/modules/angular2/src/router/rules/route_paths/param_route_path.ts#L178)

I don't know if the current behavior is a feature, but personally this seems weird that the framework insists on having anything as the wildcard value.

If the above piece of code was changed to:

```
if (!(segment instanceof ContinuationPathSegment)) {
  var generated = segment.generate(paramTokens);
  if (generated != null || !(segment instanceof StarPathSegment)) {
    path.push(generated);
  }
}
```
then the `null` would not be appended.

What do you think?

**Comment by naomiblack** [comment]
also see internal issue b/28289405

**Comment by vicb** [comment]
obsolete - former router
