### ISSUE TITLE
[beta-15] - Error installing

### ISSUE THREAD

**Issue by ericmdantas** [angular/angular#8053]
Running `npm i --save angular2` or `npm i --save angular2@2.0.0-beta.15` is returning the following error:

```shell
npm ERR! cb() never called!
```

```shell
$ npm -v
3.8.6
```

```shell
$ node -v 
v5.9.0
```

I'm on Windows 10, if that helps.

**Comment by neolwc** [comment]
Same here for the beta.15

**Comment by splintercode** [comment]
I had the same issue on the latest OSX. Doesn't look like a windows specific issues.

**Comment by HJHorst** [comment]
My coworker is on npm 3.7.3, also has this issue.
I'm on npm version 2.14.12, do not have this problem.

**Comment by TekSiDoT** [comment]
There might be a problem installing zone.js@0.6.10 (which seems to not have been published). Manually editing the ng2 package.json to require zone.js@0.6.11 seems to resolve the install issue, but I have no idea in how far this could create compatibility issues. 

I've tested the installation with a rather basic application and had no issues.

**Comment by todoubaba** [comment]
Same issue, fixed after upgrading to node.js 5.10.1

**Comment by razaa** [comment]
I'm facing the same issue on OSX, never try it on windows. Also after restricting version to just 2.0.0-beta.14 works for me.

**Comment by ericmdantas** [comment]
Updating node to `5.10.1` solved the problem.

Anyone still having it?

**Comment by razaa** [comment]
Yeah updating node to 5.10.1 solved the problem.

**Comment by dargoan** [comment]
Sames goes for me.

**Comment by wardbell** [comment]
I'm running node v.5.6.0, npm v3.8.2 ... no problem.  So it looks like there is some combo of beta.15 and anything between > v.5.6.0  and < v.5.10.1.

**Comment by Foxandxss** [comment]
It seems to only happen with 5.9.x

**Comment by ericmdantas** [comment]
Well, I'm going to close it then.
