### ISSUE TITLE
exports need to supply related types

### ISSUE THREAD

**Issue by trinarytree** [angular/angular#8054]
`platform_location.dart` is "internal" (being in a src folder) and contains only interfaces:
`PlatformLocation`
`UrlChangeEvent`
`UrlChangeListener`.

Of these 3 symbols that work intimately together, only `PlatformLocation` is publicly exported through `router.dart`.  That makes it annoying to use it, e.g. I can't implement the `PlatformLocation` interface because that would require me to repeat the signature of one of its methods, `onPopState`, which uses the symbol `UrlChangeListener`, which wasn't publicly exposed.  I can cheat and import the relevant library anyway, but I shouldn't be forced to subvert the intended privacy rules.

More generally, I feel like any time a library L publicly exposes a symbol S, all related types need to be publicly exposed too.  "Related" means the type of S; or if S is a method, then all the types of its signature; or if S is a class, then recursively, all the related types of its fields and methods.

We probably don't need to be so pedantic as to insist that L exports these related types itself, e.g. here
```dart
library L;

import 'dart:async';

Future<int> willBeAnInt;
```
it's probably silly to insist that L export `dart:async`.  But anyway, all the related types should be somehow publicly accessible, and if they are rare and only needed when you need L, then, yeah, maybe L should just export them for convenience.

For this bug, please at least resolve the problem with `platform_location.dart`.

**Comment by pkozlowski-opensource** [comment]
Obsolete.
