### ISSUE TITLE
Anchor tags are not opening in new tag by CMD/Ctrl + Mouse left click

### ISSUE THREAD

**Issue by tom10271** [angular/angular#8058]
In normal situation, when user press and hold Cmd in Mac or Ctrl in Windows then left click on any links, browser will open that link in a new window.

https://angular.io/resources/live-examples/tutorial/ts/plnkr.html

However, in Angular 2 application, if links with `routerLink` attribute, it only resolve the route and transit to  it corresponding component only. I think it should at least let developers to decide whether it can only resolve and transit or safe to open in new tap.

This is harming user experience. I am building a CMS with Angular 2, I expect lots of user love to open Angular internal links in separated tabs by Cmd/Ctrl + left click, although right click then click `Open in new window` works.

Thank you

**Comment by CaptainCodeman** [comment]
See also https://github.com/angular/angular/issues/6806 and https://github.com/angular/angular/issues/5908

**Comment by amaneer94** [comment]
https://github.com/angular/angular/issues/5908#issuecomment-414234656
