### ISSUE TITLE
http return only old data insteady of just updated data on windows Edge

### ISSUE THREAD

**Issue by asiacoll** [angular/angular#8059]
when I have updated a form and then revisit the form, the data loaded is still the old one in steady of the new updated one when I using windows Edge. On Chrome und Firefox, it works correctly.
following is the code at service:

`@Injectable()
export class ItemService {
    constructor(private http: Http) { }
        getItem(id: string) {
        return this.http.get('/api/item/getItem/' + id)
            .retry(3)
            .map(res => res.json())
            .catch(this.handleError);
    }`

The code at component:
`this._service.getItem(id)
            .subscribe(
            data => this.processResult(data),
            err => this.logError(err));`

When I revisit the form page, the data which retrieved is the old data instead of the new one from  the database. When I revisit the form page, I notice that the program goes and stops at service and return the old data, MVC 6 API Controller doesn't take any action. Normally the process should go to MVC 6 API Controller and returned data from the database. According to my understanding the http should always get data from the Api in steady a cached data. This situation on Windows Edge is really strange to me.

**Comment by zoechi** [comment]
Where do you call the code in the component? Constructor, Angular lifecycle method, ...?

**Comment by asiacoll** [comment]
it was called in ngOnInit(). When I reload the page, it fetches still the cached data.

**Comment by zoechi** [comment]
Did you check `this._service.getItem(id) ... ` is actually executed when you navigate to the form the 2nd time?

**Comment by asiacoll** [comment]
` this._service.getItem(id)` is executed, as ItemService is called. It seems that the API is not called as it has no reaction at all. The problem exists also on internet explorer.

**Comment by CaptainCodeman** [comment]
Check the network tab in your browser. As long as there is a request then there is no issue with Angular. If data isn't updated it could be either Http caching or caching within your MVC app or data layer.

**Comment by asiacoll** [comment]
I checked the network tab.  ` this._service.getItem(id) ` is called. in Firefox the data is received from API. However in Edge the data is received from cache. Why it is different. How can I force the http to get data from API instead of from cache?

**Comment by zoechi** [comment]
That's a browser feature ;-) https://msdn.microsoft.com/en-us/library/hh673569(v=vs.85).aspx (search for caching) 
See also http://stackoverflow.com/questions/3984961/prevent-xmlhttpreq-s-browser-caching

**Comment by asiacoll** [comment]
thanks. The trick from the second link above works for me.
