### ISSUE TITLE
HammerGestureConfig

### ISSUE THREAD

**Issue by Delagen** [angular/angular#8061]
refer #7924 
Cannot override this in UMD builds due
does not exports in UMD builds due browser.ts does not export this from browser_common.ts

**Comment by jelbourn** [comment]
cc @kara

**Comment by Delagen** [comment]
I solved this problem with provide custom EventManagerPlugin with the same event set, this placed above Hammer and work. But I think for some cases it would be nice to only tune Hammer.

**Comment by kara** [comment]
This should be fixed with 2.0.0-rc.0. Let us know if not!
