### ISSUE TITLE
$HttpParamSerializerJQLikeProvider() in angular2

### ISSUE THREAD

**Issue by bergmito** [angular/angular#8063]
HttpParamSerializerJQLikeProvider in angular2. There is a prediction to make it?

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by bergmito** [comment]
Sorry, this is not question. HttpParamSerializerJQLikeProvider not exist in angular2. Only in angular. There is a prediction to make it?

**Comment by wesleycho** [comment]
For reference: https://github.com/angular/angular.js/blob/0727bfc141db6e60bce2fb1e09ad4f53963dec5d/src/ng/http.js#L63-L133

As a general rule of thumb, if it doesn't make sense to live in Angular 2's world, it probably won't be recreated. In this case, Angular 2 has a cleaner implementation as seen https://github.com/angular/angular/blob/master/modules/%40angular/http/src/static_request.ts#L67-L77 and with `URLSearchParams.prototype.toString` as seen https://github.com/angular/angular/blob/master/modules/%40angular/http/src/url_search_params.ts#L123-L128 .

This probably can be closed with a `No`.

**Comment by pkozlowski-opensource** [comment]
Thnx @wesleycho

**Comment by bergmito** [comment]
I changed the way server receive the parameters. But anyway, thank you @wesleycho !
