### ISSUE TITLE
PhantomJS is exiting test with `Can't find variable: Symbol` (can be fixed)

### ISSUE THREAD

**Issue by select** [angular/angular#8064]
I am using angular2@2.0.0-beta.13 with ES6 and Babel, not TypeScript

Testing my app with Karma PhantomJS is exiting tests before starting them with the error message `ReferenceError: Can't find variable: Symbol`

It can be fixed by changeing `~/angular2/src/facade/lang.js:426`
```
        if (isPresent(Symbol) && isPresent(Symbol.iterator)) {
            _symbolIterator = Symbol.iterator;
        }
```
to 
```
        if (false) {
            _symbolIterator = '';
        }
```

**Comment by select** [comment]
This broke the browser a better fix is
```
        if ((navigator.plugins.length !== 0) && isPresent(Symbol) && isPresent(Symbol.iterator)) {
            _symbolIterator = Symbol.iterator;
        }
```

**Comment by ericmartinezr** [comment]
You need polyfills, see https://github.com/angular/angular/issues/7914

**Comment by laco0416** [comment]
You can use core-js shim instead of es6-shim

**Comment by select** [comment]
So basically I just have to import it and should fix the error?

**Comment by ericmartinezr** [comment]
@select I don't know exactly what's your environment, but if you're using Karma + SystemJS you should do it as in this repo, see https://github.com/juliemr/ng2-test-seed/blob/master/karma.conf.js#L10-L16
