### ISSUE TITLE
Broken web link to "PlatformBrowserLocation" on angulario.com documentation

### ISSUE THREAD

**Issue by fletchsod-developer** [angular/angular#8066]
Go to https://angular.io/docs/ts/latest/api/router/PlatformLocation-class.html and click on "BrowserPlatformLocation" hyperlink.  You get a 404 not found error.    

This "BrowserPlatformLocation" link is at the top, in the 1st few paragraphs.

**Comment by brandonroberts** [comment]
This should be filed over at http://github.com/angular/angular.io

**Comment by fletchsod-developer** [comment]
Thanks.  I thought AngularIO documentation comes with this Angular2 package.  Closing.
