### ISSUE TITLE
Template parsing lexer doesn't allow non-ascii characters in expressions

### ISSUE THREAD

**Issue by penmark** [angular/angular#8067]
**Steps to reproduce and a minimal demo of the problem**

http://plnkr.co/edit/SYzr0x2nwrVfxHfhA5fB

_What steps should we try in your demo to see the problem?_
Just load it. Something in the line of
```
Template parse errors:
Lexer Error: Unexpected character [Á] at column 3 in expression [nonÁscii] ("<h1>My First Angular 2 App</h1><p>[ERROR ->]Utf8: {{nonÁscii}}"): AppComponent@0:34
```
will appear in the console.

**Current behavior**
Non-ascii characters are not allowed in the template.
Lexer will fail with an error.

**Expected/desired behavior**
To be able to use non-asc characters in interpolated code. For instance to access non-ascii members in json data.

**Comment by penmark** [comment]
Hmm duplicate of #7456

**Comment by pkozlowski-opensource** [comment]
Duplicate of #517
