### ISSUE TITLE
Changing directory structure in Angular 2 (beta 14) breaks the app

### ISSUE THREAD

**Issue by dragGH102** [angular/angular#8068]
I just completed the official tutorial for beta 14 at https://angular.io/docs/ts/latest/tutorial/toh-pt5.html.
The final code is almost the same as the one proposed in the tutorial with several comments, a few enhancements (until there it was working) and a different directory structure (this is what break the app)

I created a sample repository to show this: https://github.com/dragGH102/angular2-beta14--tutorial-enhanced-demonstration

Basically, instead of putting everything in app/, I created subdirectories services/, models/ and views/ (with one subdirectory for each view's file: .ts + .css + .html)

After doing that and running **npm start**, for some reason it doesn't look any longer for *.js files (which are there and correctly compiled) but for **ts.js** files and I didn't change anything in tsconfig.

Sample errors (the app is stuck on "loading..."):

```
http://localhost:3000/app/services/hero.service.ts.js Failed to load resource: the server responded with a status of 404 (Not Found)
angular2-polyfills.js:332 Error: Error: XHR error (404 Not Found) loading http://localhost:3000/app/services/hero.service.ts.js(…)ZoneDelegate.invoke @ angular2-polyfills.js:332
http://localhost:3000/app/views/heroes/heroes.component.ts.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:3000/app/views/dashboard/dashboard.component.ts.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:3000/app/views/hero-detail/hero-detail.component.ts.js Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by pkozlowski-opensource** [comment]
You need to update your [SystemJS config](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#packages) in https://github.com/dragGH102/angular2-beta14--tutorial-enhanced-demonstration/blob/master/index.html#L27-L31 accordingly.

In any case this is a general support question that doesn't belong here, see: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
