### ISSUE TITLE
Error: Uncaught (in promise): ObjectUnsubscribedError 

### ISSUE THREAD

**Issue by janbaer** [angular/angular#8072]
What could be the reason for the error that you can see in the attached screenshots.

I think it's not reproducible in a plunkr, but I'll try to describe what I'm doing. I've a child component that is emitting an event to a parent component. This parent component has an event handler for this event and when I'm calling it, I just show a modal dialog which is show some details.

```
  showQuestionDetails(question) {
    this.selectedQuestion = question;
    this.materialize.showDialog('questionDetailsDialog');
  }

  closeQuestionDetailsDialog() {
    this.selectedQuestion = undefined;
    this.materialize.closeDialog('questionDetailsDialog');
  }
```

What is happening inside the showDialog function is just the following code:

```
$(`#${dialogId}`).openModal();
```

And the closeDialog function just calls **closeModal** and that's everything.

After I closed the dialog I'm getting this error messages.

![bildschirmfoto 2016-04-14 um 21 05 59](https://cloud.githubusercontent.com/assets/528331/14540358/e67ce0fc-0284-11e6-93ca-0656fcab563e.png)
![bildschirmfoto 2016-04-14 um 21 05 26](https://cloud.githubusercontent.com/assets/528331/14540357/e6790d60-0284-11e6-9cc8-204388202adc.png)

Event when I remove the component that shows the details and I just show an empty dialog which has nothing todo with Angular 2, I'm getting this error. What could be the reason for this?

The component that I use for showing the dialog is MaterializeCSS and the dialog will be shown via jQuery. I hope that Angular2 has no problem with jQuery, isn't it?

*** Please tell us about your environment: ***
Angular version: 2.0.0-beta.15 ( It's the same with Beta 14 and 13)
Browser: Chrome Canary the latest
Language: ES6 transpiled with babel

**Comment by janbaer** [comment]
To be honest, with the time I'm more and more frustrated about all these small bugs and issues. I know it's a beta, but I think it's far from to be a productive ready version. I started before a while with my project, since I wanted to learn more about Angular2 and I also made a good progress, but some strange things taken me a lot of precious time...

I hope that someone can help me with that problem, otherwise I've to cancel my Angular2 experiments...

**Comment by janbaer** [comment]
Is it maybe a problem to do dom manipulations when I'm inside of a Angular context and the dom manipulations will be done with an external component?

**Comment by ericmartinezr** [comment]
I reproduced the error in this [fiddle](https://jsfiddle.net/a0wkj080/) with these few lines

```
var obs = new Rx.Subject();
obs.next('Some value');
obs.complete();
obs.next('Some value');
```
I googled the error and I found this [question](http://stackoverflow.com/questions/35579662/exception-objectunsubscribederror-when-working-with-observables-with-rxjs-and-a), I'm pretty sure you did google also, right? I also found this [spec](https://github.com/ReactiveX/rxjs/blob/7efcdc99973d496b70702eb6a40dd384a2e702c4/spec/Subject-spec.ts#L354) on RxJS repo  that helped me to reproduce it.

>I think it's not reproducible in a plunkr

At least you tried to reproduce it, right? You're no providing any information, and considering that I reproduced the same error without angular2 being involved I can say this is not a bug, you're doing something weird in your code. But who knows... there's no repro of it.

You really need to read the [contributing guide](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question), I also recommend you to watch this [talk](https://youtu.be/hY14Er6JX2s).

If you want help, you need to help others to help you. And look it for in the right place, github is not the right place when it comes to users errors. You'll get help faster if you look for it where you should.

**Comment by janbaer** [comment]
@ericmartinezr Thank for your advice! But that you could raise the same error with 4 lines of code doesn't mean, that I did the same thing in a wrong way and that it's so easy to reproduce. When it would be so obvious what is wrong I wouldn't ask here. But I know that I don't use any RxJS functionality in my code in this context. But I know that Angular 2 is doing it, whenever I use an event with @Output. So maybe the error will be occurred from this...

And yes I searched before with a search engine (in my case it was duckduckgo) and I also found this link, but even it was the same error, it was another situation and the solution doesn't helped me.

Of course I know that I can also ask on stackoverflow to get help with my problem, but I just found the best place for problems with using a beta is where the issues that happen with using the beta should be collected and that's here!

But of course you're right, I should try to make it reproducible or when the effort is too much, post a link to a repo where the error can very easy reproduced.

The repo is here:
https://github.com/howcani-project/howcani - you just need to clone it, npm i and gulp

Steps to reproduce:
1. Click on the headline of one of the cards you see on the right side
2. Click ok to close the modal dialog.
3. Now you can see in the console log the errors I posted here.

I'm aware that a plunkr is the fasted way for all here to help and try out to find the problem, but in some cases it's too much effort to make it reproducible in a plunkr and a lot faster to just try it out in the original source code. And by the way, the problem is also reproducible on the live page on www.howcani.eu (but it runs there only in Safari because of another problem), but the code there is without source map files.

**Comment by ericmartinezr** [comment]
@janbaer I think I got it. Your problem is here

```
<a href="#!" class="modal-action waves-effect waves-green btn-flat" (click)="closeQuestionDetailsDialog()">Ok</a>
```

You have defined HashLocationStrategy as your LocationStrategy for router. So when you clicked that link it was actually trying to navigate. Sadly I can't be more precise than that. The router detected the hash to a non-route path and everything blew up.

The fix is not to use `#!`, but `javascript:void(0);`, or any way to prevent de default behavior, for example,.

```
<a href="javascript:void(0)" class="modal-action waves-effect waves-green btn-flat" (click)="closeQuestionDetailsDialog()">Ok</a>
```

cc @brandonroberts (sorry for pinging), any clue on what was Router trying to do with that hash? Is this a known issue (didn't know how to look for this)?

**Comment by janbaer** [comment]
@ericmartinezr Thank you very much, for your help!!!! How did you found it? I mean it wasn't so obvious to detect from the call stack that it came from the router!

And of course it was my fault, even I didn't it with intention. So my sorry for that! I just fixed it and now there's no error!

**Comment by ericmartinezr** [comment]
@janbaer just by trial and error, mostly, lol. I saw that href, then I went to see the router set up in your bootstrap and I saw the HashLocationStrategy. I had problems before because of hashes and HLS, so I gave it a try and it worked.

Glad it worked :+1:

**Comment by brandonroberts** [comment]
@ericmartinezr @janbaer The router is handling all hash links and tries to convert them into a navigation instruction. Since `#!` isn't a valid route, that's why it was throwing the error.

**Comment by janbaer** [comment]
@brandonroberts Thanks for clarification! But it would be helpful when the source of the error would be a bit more obvious.

**Comment by brandonroberts** [comment]
Agreed

**Comment by 3ffy** [comment]
Hi, i got a philosophical problem with this routing system behavior. If the developer is using a bad "url" (anchor in fact) the router is throwing an error and it is not really astonishing. 

**But when the user (the final one, the one visiting your commercial website etc) edit the url without reloading the page from the browser, that mean the website will just stop working, without any visible piece of information.** This is hard to afford in a professional application.

Do you think there is a way to get a descent degradation, like catch this specific behavior and redirect to a /404 route? I think 404 error handling should be a native part or the rooting system... 

In my personal opinion,  this should work : 

```
/*
Since the route /404 is the default one, no error should be raised and all unknown routes should be redirected to it. I can't get this working.
*/
@RouteConfig([
  { path: '/cartridges/...', component: CartridgesMainComponent, as: 'CartridgesMain'},
  { path: '/', component: CalibrationComponent, as: 'Calibration' },
  { path: '/404', useAsDefault: true, component: E404Component, as: 'E404' }
])
```

**Comment by zoechi** [comment]
@3ffy 
I guess you want a `/**` route.
Your comment doesn't seem to be related to the original issue.

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by 3ffy** [comment]
@zoechi Thanks for your answer ! Actually it's 100% the same issue, but, for me, the answer given don't really fix it (despite the original author was satisfied). Maybe you could consider my point of view as a feature request (but i still think it's rather a bug).

I'm aware about nested routing `/...`, matter is what happens when the user use an url who is not filled by the RouterConfig. From my experience, using the HashLocationStrategy, the application crash with the promise error from this issue. 
I'm asking why the `useAsDefault:true` parameter on a route is not used to handle urls which are not explicitly created into the router. 

The idea beside my point of view is to natively provide a "404-like" feature into the ng2 route system. I think it's a bug since useAsDefault should logically fill this purpose... The original author called a wrong url, and the ng2 framework brutally crashed. It would be so much better to get redirected into the default route instead (the 404-like). He would have understood it was a bad path call in few seconds by himself. It's even more relevant about the final user, he got no way to understood why the site crashed.

I hope my question is a bit more understandable this time :') !

**Comment by ORESoftware** [comment]
@ericmartinezr 

referencing your code above here:

```js
var obs = new Rx.Subject();
obs.next('Some value');
obs.complete();
obs.next('Some value');
```

IMO if that indeed causes an error in the library, that's the libraries fault...There is no way that user code should always be able to account for that.

Just like promises can only be resolved/rejected once, and further calls will become no-ops, in the same way RxJS should make` obs.next() `a no-op if that obs.completed() has already been called.

Unless there is soome sort of good reason to not make it a no-op, of course. You tell me.
