### ISSUE TITLE
Error: Uncaught (in promise): No provider for t! (e -> t)

### ISSUE THREAD

**Issue by giancarloa** [angular/angular#8078]
Hello...

I just upgraded from angular2 beta.0 to beta.15...

Since then however I started encountering the error: 

> angular2.min.js:17 Error: Uncaught (in promise): No provider for t! (e -> t)
>     at l (angular2-polyfills.min.js:1)
>     at angular2-polyfills.min.js:1
>     at e.invoke (angular2-polyfills.min.js:1)
>     at Object.inner.inner.fork.onInvoke (angular2.min.js:2)
>     at e.invoke (angular2-polyfills.min.js:1)
>     at e.run (angular2-polyfills.min.js:1)
>     at angular2-polyfills.min.js:1
>     at e.invokeTask (angular2-polyfills.min.js:1)
>     at Object.inner.inner.fork.onInvokeTask (angular2.min.js:2)
>     at e.invokeTask (angular2-polyfills.min.js:1)

In order to troubleshoot the error I switched to using the angular2.dev.js file... I get the error using the angular2.min.js file... however to my surprise when I switch to using the angular2.dev.js file the error goes away... any idea on what the issue may be? Thank you

**Comment by brandonroberts** [comment]
Dupe of #6308. The minified bundles are broken, but will be fixed soon. Use the dev bundles.

**Comment by giancarloa** [comment]
@brandonroberts ... thank you

**Comment by danday74** [comment]
(e -> t) phone home

**Comment by vicb** [comment]
:ufo:
