### ISSUE TITLE
Router changes query parameters on refresh

### ISSUE THREAD

**Issue by tdterry** [angular/angular#8080]
When using the router, router params are not maintained correctly after refresh.

**Steps to reproduce and a minimal demo of the problem**

http://plnkr.co/edit/Kc7VhMJccxpduiFBkEwb

_What steps should we try in your demo to see the problem?_

**Current behavior**

Click on "?value=no parens". See that value is displayed as "no parens". Now refresh, see that value is displayed as "no%20parens" (space is not decoded). 

Click on "?value=parens()". See that value is displayed as "parens()". Now refresh, see that value is displayed as "parens" (parens are stripped).

**Expected/desired behavior**

After refresh, the route params should be the same as when I navigate. Params should be decoded automatically, and parens should not be stripped.

**Other information**

**Comment by CaptainCodeman** [comment]
It is *possible* to cajole the router into producing the correct querystring params but it's really, *really*, **_really_** ugly. Seriously, don't read this - just avert your eyes, but if you absolutely need it:

use router.generate() to create an instruction for the route
fudge around with the instruction.urlParams
get url path and query using .toUrlPath() and .toQueryPath()
use location.go(path, query) to navigate
make sure routed component returns true for routerCanReuse()
handle routerOnActivate() to get the parameters

Simple!

It would be nice if the router could actually understand URLs, it seems fairly fundamental to being a router.

**Comment by vsavkin** [comment]
It seems the issue was opened before the router rewrite. And it doesn't look like the issue still makes sense. I'm closing it. Please reopen it if you think it still makes sense.
