### ISSUE TITLE
Need testing story for components that use router dirs

### ISSUE THREAD

**Issue by juliemr** [angular/angular#8083]
Currently, TestComponentBuilder falls over with a component which needs `ROUTER_DIRECTIVES`. Figure out what's going on and fix.

Note that a complete router mock is not in scope for this issue, we just need some solution so that the components can render. Testing route config is also out of scope.

cc @marcysutton

**Comment by wardbell** [comment]
>a complete router mock is not in scope for this issue,

I think that is true. I would recommend e2e tests for now for anything that involves confirming that `RouterLink`s are working.

Components will call methods on instances of an injected `Router`, `RouteParams` and such. I think these are pretty easy for us to fake on our own as far as we need them.

**Comment by marcysutton** [comment]
YES thank you! This all sounds appropriate. It was really unit testing for UI components that seemed unnecessarily difficult.

**Comment by wardbell** [comment]
Recently, after much work, I have somewhat tamed the beast, thanks to a collection of Router mocks that  "work on my machine".  We'll see what experience brings. But at least I'm not stopped cold by the presence of `RouterLink` or `RouterOutlet`  and the setup isn't too horrendous.

Here's an excerpt:

```
/* other imports */

import { Hero, HeroService, MockHeroService } from './mock-hero.service';

import { Router,       MockRouter,
         RouterLink,   MockRouterLink,
         RouterOutlet, MockRouterOutlet} from './mock-router';

describe('AppComponent', () => {
  let fixture: ComponentFixture;
  let comp:    AppComponent;

  beforeEach(injectAsync([TestComponentBuilder], (tcb: TestComponentBuilder) => {
    return tcb
      .overrideDirective(AppComponent, RouterLink,   MockRouterLink)
      .overrideDirective(AppComponent, RouterOutlet, MockRouterOutlet)
      .overrideProviders(AppComponent, [
        provide(HeroService, {useClass: MockHeroService}),
        provide(Router,      {useClass: MockRouter}),
      ])
      .createAsync(AppComponent)
      .then(fix => {
        fixture = fix;
        comp = fixture.debugElement.componentInstance;
      });
  }));

  /* the tests go here; the component and fixture are ready */

});
```

**Comment by wardbell** [comment]
Forgot to mention that you can't use `ROUTER_DIRECTIVES` because our test framework doesn't know how to unroll it yet (I see that Julie is on it).

Do this ...
```
  directives: [RouterLink, RouterOutlet],
```
instead of ...
```
    directives: [ROUTER_DIRECTIVES],
```

**Comment by juliemr** [comment]
Ward's method is a good temporary one.

My current idea is: use the real `RouterLink` and `RouterOutlet` directives. Provide a router fake with literally empty functions. No overrides necessary via the TestComponentBuilder. If you try to click on links nothing will happen.

```js
import {ROUTER_FAKE_PROVIDERS} from 'angular2/platform/testing/router';

beforeEachProviders(() => [ROUTER_FAKE_PROVIDERS]);
```

**Comment by juliemr** [comment]
See https://github.com/angular/angular/pull/8270

**Comment by cmiagssh** [comment]
I just tried to write tests for a component that uses routes as well as ng2-translate pipes.
The only way there is also that you have to mock components.
As far as I can tell there is no proper documented or even implemented way to handle special cases or dependancies inside unit tests.
Is it possible to demand some effort in this direction?

**Comment by juliemr** [comment]
Closing in favor of https://github.com/angular/angular/issues/9496
