### ISSUE TITLE
Validators.pattern Question

### ISSUE THREAD

**Issue by doxiaodong** [angular/angular#8085]
**"angular2": "2.0.0-beta.14"**

**Current behavior**
Validators.pattern('^\w{6,20}$') will be parse to new RegExp("^" + "^w{6,20}$" + "$") in `src/common/forms/validators.js`;
It removed the `\` before `w` 

How to fixed it??

**Comment by zoechi** [comment]
Have you tried `Validators.pattern('^\\w{6,20}$')` (double `\`)?

**Comment by doxiaodong** [comment]
@zoechi, It works but it's unreasonable I think. No one should be ask to double `\`

**Comment by zoechi** [comment]
Strings and backslashes in strings work the same in most programming languages http://stackoverflow.com/questions/3903488/javascript-backslash-in-variables-is-causing-an-error. I think you should close that issue.

**Comment by zoechi** [comment]
You can also try `Validators.pattern(/^\w{6,20}$/)`. Not sure if this is supposed to work though.

**Comment by pkozlowski-opensource** [comment]
Sounds like a support question that got answered. Thnx @zoechi
