### ISSUE TITLE
ng-if is not working properly for components

### ISSUE THREAD

**Issue by vasuneet** [angular/angular#8088]
I have created for components with their templates.

1. StateWidgetComponent. - (Parent Component)
2. StateOneComponent - (Child Component)
3. StateTwoComponent - (Child Component)
4. StateThreeComponent- (ChildComponent)

StateWidgetTemplate is 

`<div >
    {{currentState}}
    <p *ngIf="currentState=='state1'">State is One</p>
    <p *ngIf="currentState=='state2'">State is Two</p>
    <p *ngIf="currentState=='state3'">State is Three</p>
    <state-one-component *ngIf="currentState=='state1'" (stateChanged)="changeState($event)"></state-one-component>
    <state-two-component *ngIf="currentState=='state2'" (stateChanged)="changeState($event)"></state-two-component>
    <state-three-component *ngIf="currentState=='state3'" (stateChanged)="changeState($event)"></state-three-component>
</div>`

Default state is : "State1"
Issue : StateOneComponent rendered properly but when i changed the state to "state2" state-two-component not rendered its template. So ngIf is not working for components.

Regards
Vasuneet Arya

**Comment by zoechi** [comment]
Please provider more information. For example a Plunker that allows to reproduce the problem.

**Comment by pkozlowski-opensource** [comment]
@zoechi is right - impossible to determine if this is a bug or not just based on the information provided. Closing.

Thnx @zoechi !
