### ISSUE TITLE
bug(testability): scheduling a task with setInterval causes angular to be seen as unstable indefinitely

### ISSUE THREAD

**Issue by sjelin** [angular/angular#8089]
When you use `setInterval`, [`zone.js` will count that as a pending task](https://github.com/angular/zone.js/blob/f8d5dc73a3c24d0ba34703e8b7a31808df6bd082/lib/zone.ts#L728), and then [will not decrease the pending task count](https://github.com/angular/zone.js/blob/f8d5dc73a3c24d0ba34703e8b7a31808df6bd082/lib/zone.ts#L739) until [the event is canceled](https://github.com/angular/zone.js/blob/f8d5dc73a3c24d0ba34703e8b7a31808df6bd082/lib/zone.ts#L756).  The result is that if you use `setInterval`, then `zone.js` will think itself unstable until the interval is cleared.  This is a reasonable design choice, but the problem is that we then [wait on `zone.js` to be stable in the testability API](https://github.com/angular/angular/blob/60727c4d2ba1e4b0b9455c767d0ef152bcedc7c2/modules/angular2/src/core/testability/testability.ts#L19).  So if an app uses `setInterval` without the intention ever clearing the interval, the app will forever be seen as unstable by the testability API.  This is clearly wrong, leading [some protractor tests to hang](https://github.com/angular/protractor/pull/3127).  I propose that the testability API wait only on non-periodic tasks.

**Comment by sjelin** [comment]
Minimal(ish) reproduction:

```js
describe('async angular2 application', function() {
  it('should work with setInterval', function() {
    browser.get('/ng2/#/async');
    $('#periodicIncrement .action').click();
    browser.waitForAngular();
  });
});
```

This is a protractor spec against our [ng2 testapp](https://github.com/angular/protractor/tree/master/testapp/ng2).  I tried just doing an `executeScript` instead of clicking on an element but that didn't work, presumably because it wasn't being executed within an angular component.

**Comment by juliemr** [comment]
This is working as intended - you should run the `setInterval` outside of the Angular zone. We should make sure that we have good documentation for this.

**Comment by juliemr** [comment]
See instead https://github.com/angular/angular/issues/8219
