### ISSUE TITLE
package.json is still referencing rxjs-beta.2 while jspm is calling for (5.0.0-beta.6)

### ISSUE THREAD

**Issue by playground** [angular/angular#8092]
"dependencies": {
    "es6-shim": "^0.35.0",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.2",
    "zone.js": "^0.6.10"
  },

Should this be updated to (5.0.0-beta.6)?

**Comment by pkozlowski-opensource** [comment]
Same as https://github.com/angular/angular/issues/7826. Dependencies are updated when a new version is properly tested.
