### ISSUE TITLE
Dart angular transformer hangs

### ISSUE THREAD

**Issue by frankpepermans** [angular/angular#8093]
This happens after upgrading to b15, prior versions run just fine.
It is a closed source project, and other ng2 projects do run fine in b15.

When I fire up pub serve, it loads the angular 2 transformers, and they just hang up without any output whatsoever. 
I can best describe it as if a Future never completes and the transformer is just waiting forever.

This is with
Windows 10
Sdk 1.15.0
Angular 2 b15

**Comment by kwalrath** [comment]
@jakemac53 could you please help with this? In general, testing Angular 2 apps with Dartium has been problematic lately. See also https://github.com/dart-lang/sdk/issues/26260.

I've asked Frank (on Slack) to test whether `pub build` works. He's confirmed that he's not importing `bootstrap.dart`.

When I update the angular2 version (e.g. https://github.com/angular/angular.io/pull/1085), I test every app, and lately I've often had to clear the cache and/or hard reload. Repeatedly. And this is for toy apps. But `pub build` (or just opening the app in a non-Dartium browser) works for me.

**Comment by frankpepermans** [comment]
Just to confirm that pub build also fails for me,
same situation, it hangs midway without anything being thrown,
dart process sits at 0% and no memory fluctuation

**Comment by jakemac53** [comment]
@kwalrath do we have any real world examples where this is happening?

**Comment by kwalrath** [comment]
I have none. @frankpepermans would it be possible for you to create a small (or at least non-proprietary), reproduce-able case?

**Comment by frankpepermans** [comment]
I'll try, can you give me some pointers?
Best would be a way to debug transformers of course,
did something change in the way you iterate over / or compile a list of files to transform?

Reason I'm asking is because the project that fails is split over 2 separate projects, both have each other as dependency in their pubspec files

**Comment by jakemac53** [comment]
It is highly likely this is a result of the cyclic dependency between the two packages, I can do a bit of investigation into that.

@vsavkin might know more about what changed in the recent version that would trigger an issue where there wasn't one before. Most likely something changed with respect to what files are being read in order to generate the *.template.dart files.

**Comment by jakemac53** [comment]
Confirmed, cyclic dependencies in packages cause pub build/serve to hang.

**Comment by frankpepermans** [comment]
This is new from b15 or has this always been a known issue?

I've added a few print statements inside the angular 2 transformers, specifically inside the template transformer, trying to detect where it would hang, but it seems that the template transformer does traverse each file, is there anything else I need to check that would run after this transformer?

**Comment by jakemac53** [comment]
It looks like I can repro this in b14 as well actually. It is still possible though that in your app it wouldn't show up until b15 if it changed what files are read in during some phases of the transformer.

**Comment by jakemac53** [comment]
https://github.com/jakemac53/angular_cycle_repro is a simple repro case. Remove the import to the other package from `a/lib/app_component.dart` or `b/lib/app_component.dart` and it no longer blocks.

**Comment by frankpepermans** [comment]
I found that if I comment-out line 83 -> 89 within deferred_rewriter/transformer, then it seems to stop hanging on pub serve.

The lines are:

```
await for (Asset a in transform.primaryInputs) {
    if (a.id.path.endsWith(DEFERRED_EXTENSION)) {
      deferredCountAsset = a;
    } else if (a.id.path.endsWith('.dart')) {
      dartAsset = a;
    }
  }
```

This would hang if transform.primaryInputs never receives an event

**Comment by frankpepermans** [comment]
transform.primaryInputs is indeed empty sometimes, causing the for loop to hang,
tested it with transform.primaryInputs.isEmpty.

I'll try to investigate further tomorrow, if you can give me some leads as to why this would be empty, much appreciated

**Comment by jakemac53** [comment]
The for loop shouldn't hang unless its waiting on more files, are you sure that is happening or is it just the fact that its returning null right away after that (and thus not doing any work)?

**Comment by frankpepermans** [comment]
It just wait and no assets ever are added.

Seems like the close method is never reached

**Comment by frankpepermans** [comment]
To test this, I've added a timeout

Transformer.primaryInputs.timeout of 10 seconds inside the for loop.

After that duration, it throws an exception with 'no events'

**Comment by frankpepermans** [comment]
If it helps, the code of this transformer didn't change compared to b14, so something else causes the primaryInputs to never complete

**Comment by frankpepermans** [comment]
I've refactored my code base to get rid of the circular dependency and moved all shared code to a new, third library which both now depend on.

After these changes, b15 works again for me, so this is indeed an issue with circular dependencies,
not sure why it worked fine prior to b15, from digging into the transformers, it seems to be a problem with the AggregateTransformer (see above).

Anyway, we can close this I assume? If the circular reference is a known issue already, then having this open is just confusing?

**Comment by pkozlowski-opensource** [comment]
Obsolete.
