### ISSUE TITLE
Placeholder and i18n

### ISSUE THREAD

**Issue by Kettja12** [angular/angular#8094]
**Steps to reproduce and a minimal demo of the problem**
use äöå  (germain,swedish/finnish characters) with placeholder

**Current behavior**
captured from screen: 
```HTML
    <input [(ngModel)]="customer.contactperson" placeholder="yhdyshenkil�  
```
**Expected/desired behavior**
input control with placeholder="yhdyshenkilö'

**Comment by pkozlowski-opensource** [comment]
From where was the screen capture taken? It looks like from an editor, no? So how Angular would be involved here?

**Comment by Kettja12** [comment]
i just copy paste text  from IE screen.

**Comment by michalstepien** [comment]
You not closed properly tag. For example:
[http://plnkr.co/edit/Q7uk1JdJYrxh739kjoBO?p=preview](http://plnkr.co/edit/Q7uk1JdJYrxh739kjoBO?p=preview)
should be:
`<input [(ngModel)]="contactperson" placeholder="óäöå">``

**Comment by pkozlowski-opensource** [comment]
I guess the proper plunker would be: http://plnkr.co/edit/UJ5prBdfhQgHYwx0BPHB?p=preview

In any case it proves that things work as expected. Closing for now, happy to re-open if @Kettja12 is able to modify the plunk to expose the issue.

**Comment by pkozlowski-opensource** [comment]
Thnx @michalstepien
