### ISSUE TITLE
Memory Leak with Angular2 http and rxjs .publish.refCount

### ISSUE THREAD

**Issue by Guardiannw** [angular/angular#8095]
**RxJS version:**
5.0.0-beta-6

**Angular2 version:**
2.0.0-beta.15

**Code to reproduce:**
See http://embed.plnkr.co/T0timA2kSvHwuIkARgOp/

**Expected behavior:**
It should not memory leak.

**Actual behavior:**
The leak is shown when high volume of angular2 http requests are called, (e.g. using the repeat operator) using the .publish.refCount (and others) operators are used. When run, it causes a continuous memory leak until the hot observable no longer has any subscribers.

**Additional information:**
I have not been able to find the code that is causing the problem. I only know 2 things.

1. It doesn't occur when I refrain from using the .publish.refCount (or others, e.g., share()) operators.
2. It seems to be only happening when i use angular 2's http observables. (i.e., I tried it using Observable.of([0,1,2,3]) and it did not leak).

@mhevery Does this have anything to do with the stack traces in Zone.js?

See [https://github.com/ReactiveX/rxjs/issues/1630](https://github.com/ReactiveX/rxjs/issues/1630)

**Comment by Guardiannw** [comment]
It looks like this a problem with angular's implementation of zone.js.  I will file on the zone.js board.

**Comment by dchacke** [comment]
@Guardiannw Can you post the link to the zone.js issue you filed? I'm curious where this went from here.

**Comment by Guardiannw** [comment]
@dchacke https://github.com/angular/zone.js/issues/332

**Comment by dchacke** [comment]
Thanks.

**Comment by iBasit** [comment]
+1

**Comment by redcameron** [comment]
Any progress on this issue? Does it still exist in the latest stable release?

**Comment by bdwellons** [comment]
I'm using Angular 4.0.0, with Zone.js 0.8.5, RxJS 5.2.0. I have a polling scenario via setInterval every 30s, GET request sets local var to response. Every call adds between 75k & 125k to the memory used. Leak ultimately crashes application within 24 hours.

**Comment by DzmitryShylovich** [comment]
@bdwellons reproduce in plunkr and file a new issue please

**Comment by redcameron** [comment]
@bdwellons I'm very eager to see your implementation so that we can see if ours are similar to each other. Are you planning on creating a new plunkr for this issue?  It would be greatly appreciated!

**Comment by bdwellons** [comment]
http://plnkr.co/edit/jmPY8Lq3H1wSVnEet8Ol?p=preview

**Comment by redcameron** [comment]
@bdwellons Thanks for the plunkr! I'm looking at the sample app and using the Chrome task manager to view the memory usage and I don't see much of a memory leakage at all.
