### ISSUE TITLE
ngOnChanges executed before ngOnInit with angular2/upgrade

### ISSUE THREAD

**Issue by andreialecu** [angular/angular#8099]
**Steps to reproduce and a minimal demo of the problem**

When using `angular2/upgrade` to use an angular2 component inside an angular1 context, binding some angular1 inputs to the angular2 component makes the angular2 component's `ngOnChanges` handler be called before `ngOnInit` was ever called. This could lead to obscure bugs.

**Current behavior**

`ngOnChanges` is called before `ngOnInit`

**Expected/desired behavior**

`ngOnInit` should be called first.

**Comment by andreialecu** [comment]
Repro: http://plnkr.co/edit/oM0xuOgODWvIJ2LMZ0nN?p=preview

**Comment by CaptainCodeman** [comment]
I agree this seems counterintuitive to me as well but it is by design.

https://github.com/angular/angular/issues/7782

**Comment by zoechi** [comment]
For me the inputs being resolved before `ngOnInit()` is called is mandatory. I don't see what purpose `ngOnInit()` would fulfill otherwise at all. When inputs are updated `ngOnChanges()` is called. 
Seems quite straight-forward to me.

**Comment by andreialecu** [comment]
Alright. Didn't realize this is by design. I understand why it works this way but I think angular could defer the *first* ngOnChanges so it occurs immediately after ngOnInit.
