### ISSUE TITLE
feat(ngMessages): allow using template tags for included messages

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular#810]
This is a projection of https://github.com/angular/angular.js/issues/10846

**Comment by trotyl** [comment]
Obsolete? Seems we no longer have an `ngMessages` package.

**Comment by Toxicable** [comment]
Or a need for one
As with Material I think this is concise enough:
`<mat-error *ngIf="email.invalid">{{getErrorMessage()}}</mat-error>`

**Comment by splincode** [comment]
@PascalPrecht Is the issue relevant?

**Comment by PascalPrecht** [comment]
ngMessages actually goes beyond just

```
<mat-error *ngIf="email.invalid">{{getErrorMessage()}}</mat-error>
```

Whether is relevant or not needs to be decided by the team.

**Comment by ajitsinghkaler** [comment]
@PascalPrecht @mhevery @kara I think we can close this issue. Please correct me if this issue holds relevance in angular 2+.
