### ISSUE TITLE
dgeni: @deprecated tag has no visible output in API docs

### ISSUE THREAD

**Issue by naomiblack** [angular/angular#8101]
See https://angular.io/docs/ts/latest/api/common/FORM_BINDINGS-let.html for an example of a live page that should have an @deprecated warning, per https://github.com/angular/angular/blob/2.0.0-beta.15/modules/angular2/src/common/forms.ts#L64-L64

**Comment by naomiblack** [comment]
@petebacondarwin @IgorMinar  I'm going to ask @ericjim to work on a style for making this visible.

**Comment by petebacondarwin** [comment]
Probably should be an issue in angular.io then?

**Comment by naomiblack** [comment]
oh, yes. Filed https://github.com/angular/angular.io/issues/1097
