### ISSUE TITLE
CanActivate strange behavior

### ISSUE THREAD

**Issue by flauc** [angular/angular#8104]
Sorry i haven't managed to get a plunker working. 

What i've noticed is that if i have a parent route that uses CanActivate and then a child route which also has a CanActivate, then only the child's CanActivate function gets called. 

I'm just wondering whether this is the desired behavior or a bug?

**Comment by CaptainCodeman** [comment]
I don't know if it's still the case but CanActivate is apparently called on children *before* the parent. You can still have CanActivate to protect the parent and therefore the group of it's children but if they also use it you may have to handle the fact that the ordering means it hasn't done any of the parent checks first.

See: https://github.com/angular/angular/issues/7342

**Comment by flauc** [comment]
In my case the parents CanActivate doesn't get called at all. It only gets called on children that don't have there own CanActivate. 

Therefore the only way to use the same protection logic of the parent on a child that has it's own CanActivate is to repeat the logic of the parents CanActivate before the childs.

I'm so sorry i can't get a plunker working i simply can't get routing to work on a plunker at all.

**Comment by CaptainCodeman** [comment]
Is that child CanActivate returning false? If so it might explain why the parent isn't called - if it depends on the result of all it's children then any of them returning false could make testing the rest pointless.

**Comment by flauc** [comment]
Yes you'r right in my case all the child canActivates would resolve to false so the parent would never get called. Which is just the right behavior.
