### ISSUE TITLE
Hash fragment should not be modified by Angular running PathLocationStrategy 

### ISSUE THREAD

**Issue by emesx** [angular/angular#8105]
When the location strategy is `PathLocationStrategy` the hash fragment is still cleared upon navigation.

This happens in the [RootRouter.commit](https://github.com/angular/angular/blob/60727c4d2ba1e4b0b9455c767d0ef152bcedc7c2/modules/angular2/src/router/router.ts#L517) method, which itself calls `Location.go` .. and ends calling `History.pushState`.

I think it's reasonable (or, actually, expected) NOT to tangle with the hash fragment at all, when the strategy is using URL paths.. what do you think?

A very short piece of code added to `RootRouter.commit` could help achieving this:

```
var hash = this._location.hash;
if (this._location.platformStrategy instanceof PathLocationStrategy && hash.length > 0) {
  emitPath += '#' + hash;
}
```

What do you think? Without this change it's hard to embed apps using different location strategies.

**Comment by zoechi** [comment]
Looks like #6595

**Comment by naomiblack** [comment]
also see internal issue b/28289405

**Comment by vsavkin** [comment]
I don't think the issue still makes sense in the context of the new router (@angular/router). If you think it does, please reopen it with a plunkr reproducing the issue.
