### ISSUE TITLE
*ngFor trackBy error, if array is empty

### ISSUE THREAD

**Issue by xr0master** [angular/angular#8106]
```
@Component(
  template: `
   <div *ngFor="#item of items; trackBy: item.foo">
      {{item}}
   </div>
   `
)
class MyComponent {
}
```

if items = []
Get error: Cannot read property 'foo' of undefined

cc // @kara

**Comment by zoechi** [comment]
try 

```html
<div *ngFor="#item of items; trackBy: item?.foo">
```

(added `?`)

**Comment by xr0master** [comment]
@zoechi 
It fixes this issue, thank you. However, I don't understand if it was planned or it is a bug. I thought that the trackBy method should not be called if array is empty.

**Comment by zoechi** [comment]
Good question. Sounds reasonable. I leave it to the Angular team to response to that. At least you have a workaround.

**Comment by kara** [comment]
@xr0master, `ngFor` and `trackBy` both support empty arrays, and shouldn't error. However, from your code sample, it looks like you might be constructing the `trackBy` incorrectly.  `trackBy` actually expects a function, not a property name.  If you rewrite your code to pass in a function that returns `item.foo`, it should work (whether or not the array is empty):

```javascript
@Component(
  template: `
   <div *ngFor="#item of items; trackBy: myTrackBy">
      {{item}}
   </div>
   `
)
class MyComponent {
  myTrackBy(index: number, item: Object) {
      return item.foo;
   }
}
```

I'm closing for now, as this looks like a usage issue. But please feel free to re-open if you are still having issues (with a Plunker to help us replicate).   

We should definitely think about throwing an error if the argument is not a function to prevent any confusion, so thanks for reporting! I'll see if I can implement that soon.
