### ISSUE TITLE
ngChange is not working when ngChange in ngRepeat 

### ISSUE THREAD

**Issue by re661b** [angular/angular#8110]
I'm trying to use ngChange in ngRepeat [jsfiddle](http://jsfiddle.net/ax78djjL/1/) 

1.click [Item one] trigger ng-change event
2.click  [Check All] can't trigger ng-change event

Thanks for any advice

**Comment by zoechi** [comment]
https://github.com/angular/angular.js is the Angularjs 1.x repo

For support questions please use one of the channels listed in https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by aralroca** [comment]
But this is not angular 2 ... But I hope this help you: http://stackoverflow.com/a/31010847/4467741

**Comment by pkozlowski-opensource** [comment]
Closing as the original question was Angular 1.x related. Thnx @zoechi !
