### ISSUE TITLE
*ngFor Performance Issues on IE 11 and Microsoft Edge

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular#8112]
The performance of *ngFor is very slow on IE as compared to Chrome, Firefox and Opera.

The below plunker loops through over 1500 items using *ngFor, it takes less than a second in other browsers whereas it takes several seconds in IE 11 and Microsoft Edge.

http://plnkr.co/edit/sEujClHmuCbrydIiYQYL?p=preview

The code is constantly calling isNan function in es6-shim.js.

The problem seems to be due to the reason that set and get functions of the polyfill are extremely slow (compared to their native counterparts) and take most of the time.

Please have a look at http://stackoverflow.com/questions/36570532/angular-2-performance-ie11-ngfor and the accepted answer.

This performance issue is also noticeable on forms with some dynamically populated drop down lists (8-10 drop downs).

**Comment by zoechi** [comment]
For performance tests you should switch to `prodMode` (https://github.com/angular/angular/issues/6189#issuecomment-172857228 - before `bootstrap()` !!)

See also #7088

**Comment by naveedahmed1** [comment]
The issue persists even with prodMode enabled.

**Comment by jornare** [comment]
I experience the same. The profiler suggests the AppView.prototype.notifyOnBinding > textContent takes more than a millisecond, which for a table with 3cols and 1000rows sums up to 4.3seconds. In addition there's a huge callstack through zone and different event emitters.
 In Chrome it's lightning fast.

**Comment by bensgroi** [comment]
I'm seeing the same thing in IE 11. Total calls of ES.SameValueAsZero and isNaN (in es6-shim) are chewing up 27s and 13s on a singe page respectively, according to the profiler. Firefox is a little laggy too, though not nearly so bad. It runs perfectly smoothly in Chrome. I'm using RC1.

**Comment by onlyann** [comment]
I experience the exact same behavior. 
Here's an IE11 profiler extract of a page displaying a list of 120 items in debug mode:
![ie_profiling](https://cloud.githubusercontent.com/assets/1916218/15308139/5ff4fb8e-1c1d-11e6-959d-15359dadc8b7.png)

And now with production mode enabled:
![ie_profiling_prodmode](https://cloud.githubusercontent.com/assets/1916218/15308273/d9ed59e4-1c1e-11e6-8c72-2112b131650c.png)

I can't show the code but this is is not really a complex UI.
I am not sure if I should be worried that there are still over 55 million calls to `IsNan` and `SameValueZero` in production mode.

**Comment by onlyann** [comment]
To fix the performance issue with IE11, I used [core-js](https://github.com/zloirock/core-js) instead of es6-shims.
Steps are (may differ depending on your build process):

1. `npm i core-js --save`
2. replace references to *node_modules/es6-shim/es6-shims.min.js* with *node_modules/core-js/client/core.min.js* . 

So far, it seems to be working fine and performance is much closer to Chrome. 
I haven't had time to fully test and that may cause other issues.

**Comment by bensgroi** [comment]
@onlyann This solved the problem for me too, making my app usable in IE once again. It helped significantly in Firefox too. Thanks!

**Comment by Toktik** [comment]
This is not angular issue, it's shim issue. lets close?

**Comment by dblVs** [comment]
With core-js, there are still problems with the performance in IE. Ever since the '# -> let' and angular2-polyfill removal.

**Comment by aronallen** [comment]
I am having this problem too, tried production mode, tried es6-shim and core-js, still have unacceptable performance.

**Comment by omt66** [comment]
Even after using the core.js instead of es6-shims.min.js, I am still experiencing the same performance issues in  IE and Edge browsers!

**Comment by neelsbr** [comment]
I am also having this performance issue in IE & Edge. anybody got solution for this?

**Comment by neelsbr** [comment]
I have tried both the options . Enable prodmode() & use core.js instead of es6-shim. Still no luck. Single dropdown takes 12 to 15 seconds to render.

**Comment by patrickmichalina** [comment]
Same here! Using prodMode and core-js still brutally slow on IE (11 in our case) when rendering a reasonably sized dropdown menu (butter smooth in Chrome)

**Comment by AAAnderson7301** [comment]
Anybody make any headway with this? Using core.js made it faster all around but screens with large lists with ngFor are still hanging up

**Comment by MarkPerryBV** [comment]
Any further workarounds or developments with this one? My app is really smooth in Chrome but suck in IE11 and Edge currently.

**Comment by neelsbr** [comment]
Any luck?? Still I am also facing the same problem. Running in prod mode and used core.js instead of es6 shim.js. Still I cant find major differences in render time.

**Comment by vicb** [comment]
see also #9155

**Comment by Cleudi** [comment]
Any news regarding this issue? I still experience heavy performance issues with IE11.

**Comment by pkozlowski-opensource** [comment]
For all people still experiencing issue on IE _with_ core-js - could you please provide a minimal plunker with latest ng2, latest core-js and a reproduce scenario? This would speed up investigation & resolution.

**Comment by mlaval** [comment]
Here is an update of the initial plnkr to lastest Angular, core-js and enableProdMode(): https://plnkr.co/edit/c3BWJ2wOc3a2wR39iYLY?p=preview

On the same Windows machine, I measured the time between the display of "Loading App Component..." and the list of 1500 items. It takes 1s in Chrome, and 1.4s in IE11.

We definitely need reproducers to investigate this issue.

**Comment by vicb** [comment]
@mlaval thank you very much for looking into this.

Would it be hard to reproduce the same test using es6-shim ? 

Then we can document on https://angular.io/docs/ts/latest/guide/browser-support.html and close this issue.

Thanks !

**Comment by mlaval** [comment]
Here is the same scenario with the latest es6-shim: https://plnkr.co/edit/SMbM70ELBcgw66ZliUcG?p=preview

Perf are similar, about 1.5s. And the profiler too:
![image](https://cloud.githubusercontent.com/assets/2316643/20268275/bf3b1ad4-aa7e-11e6-80ba-fa2b500240a0.png)

On thing though, perf are very bad with es6-sim in dev mode. It takes 22s to load the list of 1500 items. This doesn't happen with core-js.

**Comment by tbosch** [comment]
Dev mode is always slow as we use the debug renderer which creates
DebugElements...

Marc, are the numbers above from prod or dev mode?

**Comment by mlaval** [comment]
With this particular scenario:

|     | Dev | Prod |
----|-----|-----|
core-js | 2.3s | 1.4s |
es6-sim | 22s | 1.5s |

So dev mode + es6-shim is super slow

**Comment by ljharb** [comment]
I'd be happy to help speed things up in es6-shim for dev mode, if anyone can point to the specific methods angular is using that are slow.

**Comment by vicb** [comment]
@ljharb from https://github.com/angular/angular/issues/8112#issuecomment-219592955 the culprit seems to be `Map.get`, `Map.set`,  `isNaN` and `SameValueZero`.

@mlaval Thanks for the perf tests.
- could you please attach a profile for es6-sim/dev ?
- could you please create an issue on angular.io so that we warn about perfs with es6-shim ?

**Comment by Cleudi** [comment]
Finally... I found out that my issue was NOT related to *ngFor.

Applying this fix manually to zone.js solved the problem (and yes, we use WebSocket):
https://github.com/angular/zone.js/pull/493

**Comment by jdalton** [comment]
I'd be interested to know how many items are being stored in the Map. It looks like it's hitting the slower linear search part of the map implementation. This would make sense since core-js uses a different implementation to avoid linear lookups by bolting on a non-enumerable property onto the key object. IE 11 has limited support for Map/Set so maybe in those cases it could actually use that as the internal data store.

**Comment by jdalton** [comment]
**Update**

It looks like this demo is creating 179 maps. The size of the maps are small with the highest size being 55, but its trying to set over 9,000 objects as keys which means it's hitting the slow path a lot.

**Comment by jdalton** [comment]
I've [opened a PR](https://github.com/paulmillr/es6-shim/pull/429) to address the perf issue in es6-shim.
You can see the result [here](https://embed.plnkr.co/rPU3KB/) ⚡️

**Comment by ljharb** [comment]
es6-shim [v0.35.2](https://github.com/paulmillr/es6-shim/releases/tag/v0.35.2) includes @jdalton's [PR](https://github.com/paulmillr/es6-shim/issues/429) - please let me know if that doesn't improve performance!

**Comment by vicb** [comment]
Thanks for the update !

**Comment by nykewl** [comment]
I'm facing a similar issue with IE 11 performance. I am using code-js and angular v.2.2.3. Creating a plunkr may be a little more involved due to the number or services/components required but i'll try.
I have a component with about 8 fields for dropdowns as shown below. The selects could have varying number of options (10-1000). 
The problem is rendering on IE 11 and Edge which takes over 1 min (84s). Other browsers take between 3-6s. Attached are some images from profiling on IE 11.
I think the problem is caused by IE recalculating the styles when classes (for pristine, touched, etc) are added to the FormControl fields but I cannot be sure. 
Any suggestions / ideas?

`<div *ngIf="showColumn('rateCode')" [ngStyle]="getColumnWidth('rateCode')">
        <select class="keywatch form-control" formControlName="ratecode" [tabIndex]="calcTabIndex('rateCode')">
            <option [value]="item.val" *ngFor="let item of rateCodes | async; trackBy:trackFn">
                {{item.txt}}
            </option>
        </select>
    </div>
    <div *ngIf="showColumn('cc1')" [ngStyle]="getColumnWidth('cc1')">
        <select class="keywatch form-control" formControlName="cc1" [tabIndex]="calcTabIndex('cc1')">
            <option [value]="item.val" *ngFor="let item of cc1Codes | async ; trackBy:trackFn">
                {{item.txt}}
            </option>
        </select>
    </div>`

![blob](https://cloud.githubusercontent.com/assets/19688014/21232659/6459e0b0-c2ba-11e6-956a-5abf1aa17170.png)
![untitled](https://cloud.githubusercontent.com/assets/19688014/21232660/645b27ea-c2ba-11e6-8563-54aa70b18225.png)

**Comment by reinhardsual** [comment]
using **core-js** AND **enableProdMode()** before bootstrapModule()
works for me!

IE 11(4s) still slower than Edge (2s) and Chrome (1s).

Before, it took more than 20s for IE11.

**Comment by imsarvesh** [comment]
https://github.com/rintoj/angular2-virtual-scroll

This helped me.

**Comment by matejkramny** [comment]
I had this issue and the cause I found was accidentally including debug stack tracing in the build.

```
Error['stackTraceLimit'] = Infinity;
require('zone.js/dist/long-stack-trace-zone');
```

**Comment by dblVs** [comment]
Seems like 90% of the issues are event binding related where ngFor just highlights the performance issues you have. 
It was the same case for me. Something that was triggering events for me was killing my thread.

**Comment by reinhardsual** [comment]
In package.son -> include core-js:
[image: Inline image 1]

in main-aot.js -> enableProdMode() :
[image: Inline image 2]

**Comment by cbcolleenb** [comment]
thank you.. I don't see the 2 images you reference.. what is the exact syntax?

**Comment by cbcolleenb** [comment]
also, where is main-aot.js?

**Comment by reinhardsual** [comment]
declare var System: any;

import { platformBrowser } from '@angular/platform-browser';
import { enableProdMode } from '@angular/core';
import { AppModuleNgFactory } from
'../aot/angularApp/app/app.module.ngfactory';

enableProdMode();

platformBrowser().bootstrapModuleFactory(AppModuleNgFactory);

**Comment by cbcolleenb** [comment]
I put     "core-js": "^2.4.0"
in package.json.  What file should I put the above code (enableProdMode();) etc.  I don't see any platformBrowser().bootstrapModuleFactory(AppModuleNgFactory); in my code anywhere.
Thanks, Colleen

**Comment by reinhardsual** [comment]
Depends on your project structure, and the loader used (eg. WebPack,js or
System.js)

It can be main.ts or main-aot.ts (You can name your file anything you like).
This file is where you bootstrap your Angular App.

If you use Webpack,js: It is the file you use as an entry point.

example on webpack.prod.js:
module.export = {
entry:{
'app' : './angularApp/main-aot.ts'
},


Thanks.
Reinhard Sual

**Comment by Dan203** [comment]
I'm still having this issue. In production mode the app is barely usable in Edge and basically unusable in IE. In Chrome, FireFox and Opera it runs perfectly. 

I'm using latest Angular 5 and ng-bootstrap for UI elements. Code is pretty basic. It's just a list of items (~150) in a container set to oveflow:auto. Each one is clickable to expand and show more information. (using [hidden]="isExpanded" on a DIV inside each list item element.

**Comment by Ploppy3** [comment]
@Dan203 If your users are not able to open all the items at once, you should really use `*ngIf` instead of `[hidden]`, your view will then be generated much faster.

**Comment by thekhoi** [comment]
Like many others, I'm seeing this issue as well. I've created a simple app that creates an array of 500 items.

I've wrapped the ngFor directive inside of an ngIf to make it easier to profile.

```
<ng-container *ngIf="showList">
            <div *ngFor="let todo of (list | asCompletedFilter:showCompleted); let i=index">
               ...
            </div>
</ng-container>
```
It takes roughly 2-2.5 seconds to render the list of todo items.

From the UI responsiveness tools, it looks like the template is generating thousands of calls to appendChild.

I know that IE prefers setting [innerHTML over direct DOM manipulation](https://jsperf.com/innerhtml-vs-w3c-dom/6), innerHTML peforms 2x better.

As an experiment, I used the dev console to extract the HTML from the parent element, and profiled setting the innerHTML.  According to the profile, this only took 53ms, a HUGE difference.

My suspicion is that the ngFor directive inserts a containing node into the DOM before appending any child nodes.  This means that each child node causes the browser to do a style calculation.  Ideally, the ngFor should create the containing node and only insert it into the DOM **after** all child nodes are inserted into that containing node.

Can anyone from the angular team verify?

**Comment by matteonovelli** [comment]
I'm having the same problem, my app runs perfectly in all browsers but Internet Explorer.

**Comment by mlc-mlapis** [comment]
@matteonovelli ... simply because IE engine is slower + using degradation because of using polyfills.

**Comment by pkozlowski-opensource** [comment]
The original issue is resolved now with suggestions to:
* test in prod mode;
* use core-js as a polyfill

Moreover it seems like the  es-shim was patched as well: https://github.com/angular/angular/issues/8112#issuecomment-265643759

I'm going to close this issue as the problem originally reported is fixed and this issue starts to accumulate unrelated bug reports and serves no useful purpose any more. There is nothing more to fix for us in Angular.
