### ISSUE TITLE
routerCanReuse prevent a component from being destroyed when navigated away

### ISSUE THREAD

**Issue by Binvention** [angular/angular#8115]
Currently, routerCanReuse lifecycle hook only takes effect when navigating from one location to a location that contains the same component which I see how that is useful for if you're having a form field or something similar stay constant from location to location but it doesnt keep the component alive if it isn't in the next navigation. I think it would make a lot more sense if it also allowed the components to stay alive (but hidden) when navigating to a location that doesn't contain that component. Just for example I have a component that contains many WebGL images and whenever I renavigate to that page it has to recreate all of those WebGL images which can take a lot of processing and is rather slow on the other hand if they could stay running in the background when on pages that don't contain them it wouldn't require so much loading. this would also be useful for components that require a lot of network activity so that they could stay running (keeping all of their network retrieved data) even when they aren't part of the current navigation. One other major situation that I would like to see this implemented for is when you want to edit a different navigation route's component from the current component like an options page or something similar.

**Comment by zoechi** [comment]
dup of #5275 ?

Similar to

- #7965
- #7757

**Comment by vicb** [comment]
obsolete
