### ISSUE TITLE
Date Pipe iOS Exception

### ISSUE THREAD

**Issue by danbucholtz** [angular/angular#8116]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here, see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. 

**Steps to reproduce and a minimal demo of the problem**

1.  Run [this plunkr](http://plnkr.co/iYSO9HnUsk2xdgEoJQdI) in desktop Safari or Chrome and observe the full date being printed out
2.  Run the plunkr in mobile Safari or a cordova app and observe the exception thrown

_What steps should we try in your demo to see the problem?_

1.  Open plunkr in browser.
2.  See problem :)
3.  Go to edit mode in plunkr
4.  Open src/app.ts
5.  Note the assigning of new Date in constructor, and the template binding to the date and pushing into a date pipe.

```
//our root app component
import {Component} from 'angular2/core'

@Component({
  selector: 'my-app',
  providers: [],
  template: `
    <div>
      <h2>Todays date is: {{viewModel.date | date:'fullDate'}}</h2>
    </div>
  `,
  directives: []
})
export class App {
  constructor() {
    this.name = 'Angular2'
    this.viewModel = {};
    this.viewModel.date = new Date();
  }
}
```

**Current behavior**

```
Exception with thrown value: ReferenceError: Can't find variable: Intl
```

**Expected/desired behavior**

No exception occur

**Other information**

**Comment by cexbrayat** [comment]
Duplicated #3333

Check this comment for a possible workaround https://github.com/angular/angular/issues/3333#issuecomment-203327903

**Comment by danbucholtz** [comment]
Thanks, feel free to close angular team.  The dupe should be sufficient.

**Comment by kara** [comment]
Given the dupe issue and the workaround, I'm going to close this one now. Thanks for reporting!
