### ISSUE TITLE
beta15 npm package does not exists!!!!!!

### ISSUE THREAD

**Issue by leonibr** [angular/angular#8120]
**IMPORTANT**: beta15 npm package does not exists!!!!!!

**Comment by QuentinFchx** [comment]
What command are you using to install it ?

**Comment by leonibr** [comment]
npm install angular2


2016-04-18 10:01 GMT-03:00 Quentin <notifications@github.com>:

**Comment by leonibr** [comment]
npm install angular@2.0.0.beta14 works great


2016-04-18 10:01 GMT-03:00 Ashley Marques <marques.ashley@gmail.com>:

**Comment by QuentinFchx** [comment]
If you `npm info`, it shows `2.0.0-beta.15, 2.0.0-beta.14, ...`. Meaning that beta 15 IS published.
Make sure you have a dot `.` between `beta` and `15`
Check your `package.json`

**Comment by QuentinFchx** [comment]
and also, it's npm install angular**2**  ,not angular...

**Comment by MarkPieszak** [comment]
https://www.npmjs.com/package/angular2

angularcore published 5 days ago
2.0.0-beta.15 is the latest of 66 releases

**Comment by pkozlowski-opensource** [comment]
Closing as angular2 package is well published. This sounds like the usage / npm setup issue and has nothing to do with the framework itself.

**Comment by leonibr** [comment]
Ok

2016-04-18 10:37 GMT-03:00 Pawel Kozlowski <notifications@github.com>:

**Comment by leonibr** [comment]
check that out

![npmerror](https://cloud.githubusercontent.com/assets/7917333/14606655/9005a92a-0554-11e6-83a0-7bc9f88eb3a2.gif)

**Comment by pkozlowski-opensource** [comment]
This sounds like https://github.com/angular/angular/issues/8053 - check your node / npm version.

**Comment by leonibr** [comment]
Thank you @pkozlowski-opensource,  updating node to 5.10.1 solved the problem!!!!
