### ISSUE TITLE
Angular 2 grid: Can't make sample car grid to react on row click

### ISSUE THREAD

**Issue by bibermar** [angular/angular#8121]
This about Angular 2 ag-grid,
I’m new in Angular (both 2 & JS); I need a row click be captured in a function with row object passed. The goal is to create a form for editing of a row.
I’m working on “Cars” grid example provided in ag-grid-angular2-beta-ts-master.zip
Inside gridOption, I put:

onRowClicked: function(event) { console.log('a row was clicked');

But the execution doesn’t go there when I click a grid row.
Can you please advise what I do wrong?
Please see modified example code below (changed to "txt" from "ts" to be attacheble) .
Thank you in advance.

[SampleAppComponent.txt](https://github.com/angular/angular/files/223819/SampleAppComponent.txt)

**Comment by MarkPieszak** [comment]
Please use stackoverflow for questions & coding issues. This section is for actual bugs/issues with the Angular framework itself. @bibermar

**Comment by pkozlowski-opensource** [comment]
Thnx @MarkPieszak - you are completely right about not using issue tracker as a support forum.
