### ISSUE TITLE
angular2 app extremely slow with 1000+ router-links

### ISSUE THREAD

**Issue by advgal** [angular/angular#8122]
Try my little test app here:

http://advgal.github.io/portman-debug/

This app does nearly nothing. Click on any link and the browser will hang for a couple of seconds, even on fast hardware. I tested it with Firefox and Chrome on Linux, IE11 and Firefox on Windows.

I added a similar long list of links to the hero demo plnkr:

http://plnkr.co/edit/XHRtZr14QmRiZYWToKL1?p=preview

This is only slow on IE11.

**Comment by michalstepien** [comment]
import {enableProdMode} from "angular2/core";
enableProdMode();

**Comment by michalstepien** [comment]
[#7088](https://github.com/angular/angular/issues/7088)

**Comment by advgal** [comment]
Where do I enable ProdMode? In index.html, in boot.ts, in every ts-file?

**Comment by u0m3** [comment]
before calling **bootstrap**

**Comment by advgal** [comment]
I changed it a little, so you get feedback when you click on a link. It is still extremely slow on most browsers, even with production mode enabled. Click on the links and see how long it takes till the first line is updated.

http://advgal.github.io/portman-debug/

firefox, ie11 and edge are slow, chrome 45 is better, chrome 49 performs. Maybe ES6 support?
I found the following in the console:

mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create es6-shim

**Comment by cebor** [comment]
chrome and safari perform nice for me ...

**Comment by CaptainCodeman** [comment]
Painfully slow in FF, Edge and IE

**Comment by mbakker96** [comment]
@CaptainCodeman did you enable production mode?

**Comment by CaptainCodeman** [comment]
See link and description above: "... with production mode enabled"

**Comment by mbakker96** [comment]
@CaptainCodeman  sawry ;)

**Comment by gamebox** [comment]
Did something change on this?  Running Chrome 49.0.2623.87 (64-bit) on Mac OS X 10.11 with an i5 and 4GB of ram and it runs smooth as butter.  Took about 600ms to load initially, and then worked like a charm.

**Comment by sateffen** [comment]
With chrome it's ok, but using IE11 and FF45 the initial load is ~1-3sec (so it's ok), but after clicking the first item, I can't click a second one in IE11, and in FF45 the page needs about 5-10seconds to handle a second item click. In both browsers windows tells me, that the process has hung up as well.

Using windows 7 with relativly new i5-5200U and 16gig ram while testing this.

Something odd: After this hung up thing in IE11 and FF45, I changed to chrome and worked a little, and after ~5min I've gone back, and everything behaved like after a reload. First click superfast, second super slow or not responding.

**Comment by wesleycho** [comment]
It has been recommended to use core-js instead of es6-shim for shimming, see https://github.com/angular/angular/issues/8112#issuecomment-219623759.

**Comment by advgal** [comment]
with core-js it is much better, not perfect on IE, I close it.
