### ISSUE TITLE
trackBy don't work?

### ISSUE THREAD

**Issue by krasevych** [angular/angular#8123]
Hello.
I have the code http://plnkr.co/edit/PNMu9bYdcH8HUNQOSKTn on angular 1.x
and I try to do the same on angular 2 - http://plnkr.co/edit/Yx51PogyCQXYE8bKM65l
but it doesn't work on angular2
maybe I made mistake?

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by krasevych** [comment]
I think it is a bug with trackBy

**Comment by zoechi** [comment]
You don't even explain what the desired behavior is. Your Angular 1.x Plunker does nothing.
```
  myTrackBy(i, item) {
    return i;
  }
```
might be what you want.

**Comment by krasevych** [comment]
I corrected link for angular 1. and there you can see error into console

**Comment by krasevych** [comment]
I have list: list = [{a:1},{a:2},{a:2}];
and I try to track by property 'a'.
it should be throw error like angular 1. because there is duplicate a:2.
```Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: item in list track by item.a, Duplicate key: 2, Duplicate value: {"a":2}```
but angular 2 don't throw error.

**Comment by MarkPieszak** [comment]
To go along with what @krasevych is saying though, it seems the trackBy isn't doing anything (although the code is getting there).

The for loop goes through like normal...

**Comment by choeller** [comment]
@krasevych @MarkPieszak Angular 2 allows duplicates in NgFor, so this is why no error is thrown. So this is totally legal:

```ts
  numbers =  [42,42,42,43]

```
```html
  <li *ngFor='#number of numbers'>{{number}}</li>
```

AFAIK trackBy function is only used for DOM-Node reuse - so out of the box ngFor uses Object-Identity for DOM-Node creation and with trackBy Angular reuses the nodes when they are already in the list. See the following plnkr and press "refresh". First list is with trackBy and second one without:

http://plnkr.co/edit/KRKbiCj2MBSyPdscYtiv?p=preview

**Comment by krasevych** [comment]
@choeller what does 'trackBy' do? I tested the 'trackBy' and set different return value but behavior the same.

**Comment by CaptainCodeman** [comment]
Related: https://github.com/angular/angular/issues/8011 https://github.com/angular/angular/issues/7689

**Comment by krasevych** [comment]
Thank you! I got it.
