### ISSUE TITLE
angular 1.5 + es5-shim + currency filter crashes safari 8.x

### ISSUE THREAD

**Issue by stringbeans** [angular/angular#8127]
When using the built-in currency filter in Angular 1.5.x , with es5-shim 4.5.8 and browsing with Safari 8.x the browser will crash...

http://plnkr.co/edit/zshIf4lDR0YgUXmHl8ou?p=preview

(also logged with es5-shim... https://github.com/es-shims/es5-shim/issues/398)

**Comment by nicolaspayot** [comment]
These are Angular 2 related issues. I think you may want to go there: https://github.com/angular/angular.js/issues.

**Comment by stringbeans** [comment]
Oh wow sorry! My mistake. Closing.
