### ISSUE TITLE
EXCEPTION: Expression: has changed after it was checked

### ISSUE THREAD

**Issue by asiacoll** [angular/angular#8128]
my angular 2 program worked fine until I upgrade from beta13 to beta15.
in template view: `{{test}}`
in component: `this.test = new Date().getTime()`.
I do pagination for the page.  When I move from page 1 to 2 or 3 ... it comes error message as following:
`EXCEPTION: Expression '{{test}} in ArtikelListComponent@0:0' has changed after it was checked. Previous value: '1461055916227'. Current value: '1461055916252' in [{{test}}`
the page then doesn't work any more

**Comment by zoechi** [comment]
Can you try to make it reproducible? https://plnkr.co/edit/h9TrbC?p=preview

**Comment by asiacoll** [comment]
i am using ng2-bootstrap for pagination. This time I also upgraded from ng2-bootstrap version 1.0.6 to 1.0.13. Now when I change the cdn back to ng2-bootstrap version 1.0.6 and the program works again. It seems there is a conflict between angular 2 beta 15 and ng2-bootstrap 1.0.13.

**Comment by zoechi** [comment]
I guess you should report this with ng2-bootstrap. Usually this indicates a bug in the application.

**Comment by asiacoll** [comment]
Thanks, I will report with ng2-bootstrap.

**Comment by asiacoll** [comment]
I have found a solution. It is not a issue from Angular 2 it should be an issue from ng2-bootstrap pagination change detection.
