### ISSUE TITLE
Router subscription happens after navigation

### ISSUE THREAD

**Issue by HalfLegend** [angular/angular#8129]
**Current behavior**
I am using Router and a Login Page.
Other pages will redirect to Login page if the user haven't loged in.
I redirect the page using the Router.subscriber function:

```javascript
        this._routerService.subscribe(nextValue => {
            if (!this._noLoginPageSet.has(nextValue) && !this._userCacheService.IsLogin) {
                this._routerService["redirectUrl"] = nextValue;
                this._routerService.navigate(['/Login']);
            }
        });
```

And I find the above method is happen after the page navigation, not before it.

For example, I am navigating to AbcPage, because I haven't loged-in, so the page should redirect to Login Page.
But actually, the route will first load AbcPage, after the whole AbcPage is fully loaded, and the AbcPage is displayed, then it will go to the function above and navigate to Login in page.

This will bring me a lot of trouble, because some initilaize will be happened in AbcPage, and I want them after Login.
**And for another thing**, after the Login, I will get the UserInfo, and some inner fields will be displayed on AbcPage. But the actual behaviour is, because the UserInfo is null, before Login, AbcPage will be error and it won't display, and because the navigation of AbcPage is not completed, the above function will not be called, so it will never navigate to LoginPage

**Expected/desired behavior**
this._routerService.subscribe should happen before the page navigation, or add a methed to observe the behaviour before navigation

**Other information**

**Comment by brandonroberts** [comment]
@HalfLegend currently, a couple of ways to redirect before a route is loaded is to use the `CanActivate` decorator, which is going to change soon. See #4112. You can also redirect using a custom outlet before the route is activated. @CaptainCodeman has a good article here: http://www.captaincodeman.com/2016/03/31/angular2-route-security/

**Comment by vsavkin** [comment]
It seems the issue was opened before the router rewrite. And it doesn't look like the issue still makes sense. I'm closing it. Please reopen it if you think it still makes sense.
