### ISSUE TITLE
Hiding JSON string from URL

### ISSUE THREAD

**Issue by aryantutor** [angular/angular#8130]
## Can anyone please help me to Hiding JSON string from URL ?

**Steps to reproduce and a minimal demo of the problem**

_Use https://plnkr.co or similar -- try this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5_

_What steps should we try in your demo to see the problem?_

**Current behavior**

**Expected/desired behavior**

**Other information**

**Comment by pkozlowski-opensource** [comment]
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
