### ISSUE TITLE
Reference Error: System is not defined

### ISSUE THREAD

**Issue by sqwk** [angular/angular#8131]
Using the current version of the quickstart with angular `2.0.0-beta.15`, systemjs `0.19.26` and zone.js  `0.6.10` angular produces a `Reference Error: System not defined` when running angular inside a nw.js app. Note that running it inside a browser works fine.

Using the previous version of the quickstart (angular `2.0.0-beta.14`, systemjs `0.19.25` and zone.js  `0.6.6`) the app works fine, both inside the browser and the nw.js app.

**Comment by zoechi** [comment]
dup of #25
See also http://stackoverflow.com/questions/33728887/angular2js-uncaught-reference-error-system-is-not-defined

**Comment by pkozlowski-opensource** [comment]
Thnx @zoechi
