### ISSUE TITLE
Pipe life cycle on destroy throwing exception if pipe wasn't been initialized

### ISSUE THREAD

**Issue by danrub** [angular/angular#8132]
ChangeDetectionUtil.callPipeOnDestroy method, doesn't check if pipe is in uninitialized state  causing exception to be thrown if ComponentRef dispose called before first change detection

**Steps to reproduce and a minimal demo of the problem**

http://plnkr.co/edit/N6yIfXPir0QP4jHIqpgj?p=preview

_What steps should we try in your demo to see the problem?_

1) run planker demo. Text: "I am a dynamic view" displayed
2) uncomment line 55 (file: src/app.ts)
3) run plunker again, exception will be thrown (logged to console)

**Current behavior**

throwing exception TypeError: Cannot read property 'constructor' of undefined

**Expected/desired behavior**

no exception to be thrown

**Other information**

The pipes are lazy initialized on first change detection (view rendering). so if dispose on component is called before that, the life cycle fails due non existing check if pipe is valid object

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/issues/6425 and https://github.com/angular/angular/issues/5169

**Comment by danrub** [comment]
Thanks :)
