### ISSUE TITLE
ag-Grid implemention issue

### ISSUE THREAD

**Issue by pushpsingh** [angular/angular#8133]
I am implementing ag-Grid with angular2 in visual studio2015 from https://github.com/helix46/ag-grid-angular2-beta-ts

aggrid.component
import {Component} from 'angular2/core';
import {AgGridNg2} from 'ag-grid-ng2/main';
import {GridOptions} from 'ag-grid/main';

@Component({
selector: 'agGrid',
templateUrl: "/partial/agGrid",
directives: [AgGridNg2]
})
export class agGridComponent {
constructor() {
console.log("agGrid Component Start");
}
}

Index.cshtml

<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>@ViewData["Title"]</title>

<environment names="Development">

<link rel="stylesheet" asp-href-include="~/css/*.css">

<script src="~/js/jquery.js"></script>
<script src="~/js/bootstrap.js"></script>
<script src="~/js/system.js"></script>
<script src="~/js/rx.js"></script>
<script src="~/js/typescript.js"></script>
<script src="~/js/angular2/angular2.dev.js"></script>
<script src="~/js/angular2/angular2-polyfills.js"></script>
<script src="~/js/angular2/http.dev.js"></script>
<script src="~/js/angular2/router.dev.js"></script>

<script src="node_modules/ag-grid/dist/ag-grid.js"></script>

</environment>

<environment names="Production">

<link rel="stylesheet" asp-href-include="~/css/*.min.css" asp-append-version="true">

<script src="~/js/jquery.min.js"></script>
<script src="~/js/bootstrap.min.js"></script>
<script src="~/js/system.min.js"></script>
<script src="~/js/rx.min.js"></script>
<script src="~/js/typescript.min.js"></script>
<script src="~/js/angular2/angular2.dev.min.js"></script>
<script src="~/js/angular2/angular2-polyfills.min.js"></script>
<script src="~/js/angular2/http.dev.min.js"></script>
<script src="~/js/angular2/router.dev.min.js"></script>

<script src="~/js/ag-grid.js"></script>
</environment>

<script>
System.config({
packages: {
app: {
format: 'register',
defaultExtension: 'js'
},
'ag-grid-ng2': {
defaultExtension: "js"
},
'ag-grid': {
defaultExtension: "js"
},
'ag-grid-enterprise': {
defaultExtension: "js"
}
},
map: {
'ag-grid-ng2': 'node_modules/ag-grid-ng2',
'ag-grid-enterprise': 'node_modules/ag-grid-enterprise',
'ag-grid': 'node_modules/ag-grid'
}
});
System.import('app/boot')
.then(null, console.error.bind(console));
</script>
</head>
<base href="/" />
<body>
<div>
@RenderBody()
</div>
</body>
</html>

I am getting error unable to load Failed to load resource: the server responded with a status of 404 (Not Found) ag-grid-ng2/main.js

which is inside node_module and i am giving correct path but still it show unable to load resoure. here i am attaching snap of error.

Thanking you 
![ag-griderror](https://cloud.githubusercontent.com/assets/17490528/14640509/6eff76c8-065f-11e6-8a97-3ff48f67544b.JPG)

Ag-grid team is saying that there is issue in angular2 please check the comment
https://ag-grid.com/forum/showthread.php?tid=3629&pid=8526#pid8526

Please help me to resolve this.Thanking you.

**Comment by zoechi** [comment]
This looks like an issue with your configuration.

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by pkozlowski-opensource** [comment]
@zoechi is completely right, this is a general support request that doesn't belong here.... Thnx @zoechi !
