### ISSUE TITLE
Components in table are inserted outside the table

### ISSUE THREAD

**Issue by samueltardieu** [angular/angular#8135]
**Steps to reproduce and a minimal demo of the problem**

https://plnkr.co/edit/D1CYxP

**Current behavior**

The component instances (`row`) are not inserted inside the table. It looks they attach somewhere outside the table and show:

```
10 20 30
Column
```

**Expected/desired behavior**

```
Column
10
20
30
```

**Other information**

**Comment by michalstepien** [comment]
It is angular 2 repo.

**Comment by samueltardieu** [comment]
Ooops
