### ISSUE TITLE
bug(forms): sub-form component after form controls cause exception

### ISSUE THREAD

**Issue by awiseman** [angular/angular#8139]
**Steps to reproduce and a minimal demo of the problem**

http://plnkr.co/edit/Je0Df9uiCCjuibYQn10U?p=preview

_What steps should we try in your demo to see the problem?_
1. Run the plunk and view the browser's console output to see exception 
2. Open app/hero-form.component.html
3. Comment out line 20:
   
   `<hero-other-form [form]="model"></hero-other-form>`
4.  Clear console output and re-run.  No exception is expected.
5.  Reverse step 3.  Instead, comment line 5:
   
   `<hero-sub-form [form]="model"></hero-sub-form>`
6.  Clear console output and re-run.  Exception should be visible.

**Current behavior**

If the sub-form component is designed to modify a ControlGroup of the parent form, Angular2 throws exception when a sub-form component is added to a form component's template following elements that have ngControl attributes.  

`Expression 'submitted || !model.valid in HeroFormComponent@22:8' has changed after it was checked.`

**Expected/desired behavior**

Sub-form components should be able to invoke methods of input ControlGroups, such as addControl, without breaking interpolation in the parent component.

**Other information**

This exception appears to be thrown during interpolation of the ControlGroup.

**Comment by AnKlaGo** [comment]
I'm having the exact same problem. I've tried to find a workaround for this with various ways of using ControlGroup, Control or Model within the subcomponent without success. The changed after it was checked error is thrown every time.

**Comment by zoechi** [comment]
As a workaround like explained here http://stackoverflow.com/questions/36590376/angular2-and-disabling-button-exception get a reference from the form instead of the control directly. 

```
<form #myform="ngForm">
  <input ... ngControl="myInput">
  <div ...="myform.controls.myInput.valid">
</form>
```

**Comment by zoechi** [comment]
dup of #6041

**Comment by DzmitryShylovich** [comment]
@awiseman is this still an issue? can u update your plunker.
btw #6041 was closed

**Comment by DzmitryShylovich** [comment]
@vicb can be closed

**Comment by kara** [comment]
This issue looks stale given that the original plunker was built on forms before the re-design, and quite a bit of the module has been re-written since then. If you're still having problems, please feel free to open a fresh issue with a minimal repro with updated Angular
