### ISSUE TITLE
DynamicComponentLoader.loadAsRoot not binding inputs 

### ISSUE THREAD

**Issue by diegoparraleal** [angular/angular#8146]
I'm trying to use this method to load dynamically a component using a selector, but in the promise when setting the values to the child component is not working

Here is my plunker
http://plnkr.co/edit/pVFAGm?p=info 

**Current behavior**
The second child component is not getting binded

**Expected/desired behavior**
Both children should have the same behaviour

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/issues/6223#issuecomment-193908465

**Comment by gdi2290** [comment]
use `compRef.location.parentView.changeDetectorRef.detectChanges` but if you do that then you have to manually trigger the change detection for that component

**Comment by diegoparraleal** [comment]
Ok, I would like to use loadIntoLocation , but I can't load the components inside a for

Here you can see the plunker facing the problem i'm having with loadIntoLocation

http://plnkr.co/edit/kIjUeO4CihdWYeTg0i6i?p=preview

**Comment by gdi2290** [comment]
@diegoparraleal how about this?  http://plnkr.co/edit/BHJoY96Odw9xOVDyGTHA?p=preview

**Comment by diegoparraleal** [comment]
@gdi2290 Thanks for your suggestion, 

I tried that before, but I have a little problem with that approach, I need the component inside the for, because I need to create some wrappers (_i'm using a jquery plugin named gridstack, and I want to add the components inside the grid cells_),  in order to create different child components, I'm posting my problem in this new plunker

http://plnkr.co/edit/kIjUeO4CihdWYeTg0i6i?p=info

**Comment by zoechi** [comment]
Perhaps a wrapper like demonstrated in http://stackoverflow.com/questions/36325212/angular-2-dynamic-tabs-with-user-click-chosen-components/36325468#36325468 works for you

**Comment by diegoparraleal** [comment]
Yeah, thanks!!!

That works for me!,

I updated my plunker (https://plnkr.co/edit/cTphBdYuvxYd8xw9xyjo?p=preview), but I have a question to the angular team.

Is this the right way to do dynamic component binding?? sometimes it feels like a workaround.

Thanks again!

**Comment by ericmartinezr** [comment]
@pkozlowski-opensource this could be closed I guess, DCL is ded.
