### ISSUE TITLE
the dropdown option not displaying selected value

### ISSUE THREAD

**Issue by aashishab** [angular/angular#8149]
**IMPORTANT**: I am dynamically loading the values for drop down in angular with the following way. However the drop down appear with empty option first then displaying the other values. 

**Code example**

> < select ngControl="country" #country="ngForm">
< option selected="true" [value]="_widget.countryCode">{{widget.country}}</option>
< option *ngFor="#country in list.country" [value]="country.code">{{country.description}}</option>
< /select>

I have tried with this also:
<select ngControl="country" #country="ngForm">
< option *ngFor="#country in list.country" [value]="country.code" [selected]="_widget.countryCode === country.code">{{country.description}}</option>
< /select>

in the above code snippet:
the variable **_widget** and **list** fetched dynamically from API. And, i am trying to achive here is selected the widget.country to be displayed as default selected.**

**Please help me on this.**

**Comment by zoechi** [comment]
I think that would need a more complete example with actual values you're using.

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by aashishab** [comment]
Component:
@Component({
	selector: 'sample-widget',
	moduleId: module.id,
	templateUrl: './editDetails.html',
	providers: [EditService]
})
export class EditDetailsDataComponent {
	@Input('_widget') _widget: string;
....some code here...
}

HTML:

< select ngControl="country" #country="ngForm">
< option selected="true" [value]="_widget.countryCode">{{widget.country}}
< option *ngFor="#country in list.country" [value]="country.code">{{country.description}}
< /select>

**Comment by zoechi** [comment]
I still don't see any actual data you are using and it still looks like a support request that doesn't belong here.

**Comment by aashishab** [comment]
due to some organizational rule i won't be able to provide actual code but this is related to or similar to following link:
http://stackoverflow.com/questions/12654631/why-does-angularjs-include-an-empty-option-in-select 

However this link has a context of angular 1.x

Hope this make sense.

**Comment by tianjy15** [comment]
perhaps, you can set value directly like this:
<select [ngModel]="buildType" >
     <option *ngFor="#item of buildTypeList; #i = index" value="{{item.name}}">{{item.name}}</option>
 </select>

 buildType = this.buildTypeList[0].name

**Comment by aashishab** [comment]
Thanks it works for me..
