### ISSUE TITLE
Do we HAVE TO use a static DI for benchmarks ?

### ISSUE THREAD

**Issue by vicb** [angular/angular#815]
@tbosch do we really have to use a static DI for benchmarks ?

The configuration is a pain to maintain, it would be great to switch to dynamic DI (ie reflection in Dart).

**Comment by tbosch** [comment]
Most of our benchmarks measure how fast it is to create pages / objects/ ... 
Reflection is not only used for finding dependencies between classes, but also for creating them. So even if we ignored compilation time, this would still affect view instantiation, ...

**Comment by vicb** [comment]
You're right, thanks.
