### ISSUE TITLE
history.back and custom query paramater

### ISSUE THREAD

**Issue by qiu8310** [angular/angular#8150]
Using angular2-beta.15, come across the two problems：

* `history.back()` or `angular2's Location.back()` will not work if I refresh current page.
* custom query paramater will disappear

Because English is not my first language, so I create an example to express myself:

[Demo](http://qiu8310.github.io/angular2-issue-demo/)
[Source Code](https://github.com/qiu8310/angular2-issue-demo)

**Comment by zoechi** [comment]
The 1st issue is probably #5025
I don't know about the 2nd

**Comment by vicb** [comment]
obsolete
