### ISSUE TITLE
angular_1_router Optional route params?

### ISSUE THREAD

**Issue by stnor** [angular/angular#8151]
Hi,
I'm struggling with this use case:

/foo
/foo/345 (this would expand item 345 in the same view).

Is there a better way to pass on optional route params in the url than this:

  $routeConfig: [
    { path: '/',         name: 'Home',     component: homeComponent },
    { path: '/login',    name: 'Login',    component: loginComponent },
    { path: '/foo',   name: 'Foo',   component: fooComponent },
    { path: '/foo/:id',   name: 'FooWithId',   component: fooComponent },
  ]

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by vicb** [comment]
obsolete
