### ISSUE TITLE
Missing Documentation on Custom form controls

### ISSUE THREAD

**Issue by mbeckenbach** [angular/angular#8155]
Hi, 

for the last few days i've searched throgh the internet for a clear and simple example on how to implement a custom form control that works with ngFormModel so that i can apply some custom validation on that control. Nothing i've tried worked as expected.

Could you please add some kind of reference code to the documentation. Maybe something as simple as a custom checkbox that uses an icon font instead of an input[type="checkbox"].

I think of something like this: 

<flying-hero-checkbox #canFly="ngForm"  ngControl="canFly" [(ngModel)]="hero.canFly"></flying-hero-checkbox>

This component would render an icon that can be toggled on/off by clicking on it.
If the hero cannot fly, we cannot add the hero to the flying heroes database.

Thx
Max

**Comment by zoechi** [comment]
Something like https://github.com/angular/material2/tree/master/src/components ? (checkbox, input, radio)
Search for `accessor` in the TypeScript source files

**Comment by mbeckenbach** [comment]
Yes like this. Maybe the docs could be extended with a walkthrough based on a simplified version of md-checkbox.

**Comment by kara** [comment]
That's a good idea, but can you open an issue about this on the docs site?  https://github.com/angular/angular.io .  Closing, as this isn't a bug or a feature request.
