### ISSUE TITLE
Provide a user-friendly way to get at Jasmine's done fn

### ISSUE THREAD

**Issue by juliemr** [angular/angular#8156]
The current thought is to have something similar to the internal `AsyncTestCompleter` but with a more user-friendly name:

```js
it('is a test that explicitly needs done', inject([MyService, Done], (service, done) {
  doComplicatedAsync()
      .whenItsFinished(done)
      .ifItFails(done.fail);
}));
```

cc @wardbell @vikerman

**Comment by vikerman** [comment]
One problem with the inject([Done]) pattern is that it makes inject() which is expected to be synchronous to an asynchronous test function. Can we make the Done concept associated with async instead of inject?

**Comment by juliemr** [comment]
Will be resolved with https://github.com/angular/angular/pull/8257

**Comment by juliemr** [comment]
Closing since that is merged. See https://github.com/vikerman/angular/blob/2dfffcd2eb1600bffcc043ce3cea53f4f84cd872/modules/angular2/test/testing/testing_public_spec.ts#L154 for an example of how to use this.
