### ISSUE TITLE
Remove templateUrl from components or anywhere it is being used

### ISSUE THREAD

**Issue by jonricaurte** [angular/angular#8163]
Feature Request:

I think templateUrls should be removed. Both JSPM/SystemJS and WebPack have loaders for loading external templates. I think every template should be imported at the top of the file like so (or be inlined):

```
import homeTemplate from './home.component.html';

@Component({
  template: homeTemplate
})
class HomeComponent(){}
```

I think right now is the perfect time to set this expectation since Angular 2 is still in beta. Angular 2 is forcing people to adopt the component-based pattern to make it easier to build apps and use imports for dependencies, why not force people to import template files and even css files for styles? It seems like templateUrls should not be carried over from angular 1 based on the new patterns in angular 2. There is no such thing as a $templateCache in angular 2 so people using templateUrl are actually incurring a performance penalty by having to request templates.

Would like to hear input on this.

Thanks.

**Comment by mbeckenbach** [comment]
Some kind of convention would be even better. Think of some convention like this:

If there is no template property, look for an html file in the same folder with the same name. Similar to the conventions that the new router can use in ng1.

**Comment by garethslinn** [comment]
Good point but I disagree, I find the new implementation of templateUrl convenient and efficient.

**Comment by pkozlowski-opensource** [comment]
Sorry guys, templateUrl is not going away.
