### ISSUE TITLE
"Unexpected token u in JSON at position 0 ; Zone: angular ; ..."

### ISSUE THREAD

**Issue by Giegling** [angular/angular#8169]
Hello, after updating from angular 2 beta 12 to beta 15, I'm getting this error:

`zone.js:461 Unhandled Promise rejection: Unexpected token u in JSON at position 0 ; Zone: angular ; Task: Promise.then ; Value: SyntaxError: Unexpected token u in JSON at position 0
    at Object.parse (native)
    at http://localhost:8100/build/js/app.bundle.js:67275:43
    at ZoneDelegate.invoke (http://localhost:8100/build/js/app.bundle.js:1364:30)
    at Object.NgZoneImpl.inner.inner.fork.onInvoke (http://localhost:8100/build/js/app.bundle.js:17189:42)
    at ZoneDelegate.invoke (http://localhost:8100/build/js/app.bundle.js:1363:36)
    at Zone.run (http://localhost:8100/build/js/app.bundle.js:1257:45)
    at http://localhost:8100/build/js/app.bundle.js:1612:59
    at ZoneDelegate.invokeTask (http://localhost:8100/build/js/app.bundle.js:1397:39)
    at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (http://localhost:8100/build/js/app.bundle.js:17180:42)
    at ZoneDelegate.invokeTask (http://localhost:8100/build/js/app.bundle.js:1396:44)`

I have no idea what's the problem. Here's the [pic](https://imgur.com/OYILlgE) of the whole error. Thanks

**Comment by michalstepien** [comment]
Any example code? Maybe you parse undefined value.

**Comment by pkozlowski-opensource** [comment]
It is impossible to diagnose / help with the problem based just on the info provided. If you still experience this issue with the latest RC.1 please provide reproduction in plunker. Check bug submission guidelines:  https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue

**Comment by precious-coder** [comment]
I'm getting this error as well with 2.0.0-rc.1

```typescript
/**
 * coffee-bean-collection.ts:
 */
export class CoffeeBeanCollection {
    public beanMap: {
        [beanName: string]: string
    } = {};

    public getObject(key: string): Object {
        return JSON.parse(this.beanMap[key]);
    }

    public putObject(key: string, value: Object): void {
        this.beanMap[key] = JSON.stringify(value);
    }

    public remove(key: string): void {
        delete this.beanMap[key];
    }
}

/**
 * coffee-bean-collection.spec.ts:
 */
import { CoffeeBeanCollection } from './coffee-bean-collection';

describe('CoffeeBeanCollection', function () {
    let testItem: CoffeeBeanCollection;

    beforeEach(function () {
        testItem = new CoffeeBeanCollection();
    });

    it('should work', function () {
        expect(testItem.getObject('arabica')).toBeUndefined();
        expect(Object.keys(testItem.beanMap).length).toBe(0);
        testItem.putObject('arabica', '\89PNG rawdata');
        expect(testItem.getObject('arabica')).toMatch('\89PNG rawdata');
        testItem.remove('arabica');
    });
})
```

> CoffeeBeanCollection
> ✖ should work
>   Chromium 50.0.2661 (Ubuntu 0.0.0)
> SyntaxError: Unexpected token u in JSON at position 0
>     at Object.parse (native)
>     at CoffeeBeanCollection.getObject (cbc/config/spec-bundle.js:75836:420 <- webpack:///src/app/services/coffee-bean-collection.ts:9:406)
>     at cbc/config/spec-bundle.js:75419:26 <- webpack:///src/app/services/client-flow-handler.spec.ts:50:24
>     at Object.<anonymous> (cbc/config/spec-bundle.js:35848:27 <- webpack:///~/@angular/core/testing/testing.js:98:0)
>     at Object.<anonymous> (cbc/config/spec-bundle.js:35855:18 <- webpack:///~/@angular/core/testing/testing.js:105:0)

**Comment by noumanbhatti** [comment]
This happened bcz u r not returning the data in json format.
