### ISSUE TITLE
relying on ASI (auto semicolon insertion) in AtScript makes tooling harder

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#817]
Stock Webstorm gives a warning on statements which don't end with semi. We could turn the warning off in the IDE, but I'd rather not rely on ASI.

We'd like to format the codebase with clang-format, but it doesn't understand javascript syntax enough to understand a statement which terminates with a linebreak instead of a semicolon. Instead it removes the linebreak, breaking the code.

In general, it's a pity to carry forward ASI into AtScript since it complicates all the tooling. Does anyone have a strong desire to omit semicolons in AtScript code?

@mprobst suggests this as well. We are working on a mechanism for finding all the ASI abuses in the codebase.

**Comment by mprobst** [comment]
For context, the Rules of Automatic Semicolon Insertion.
http://www.ecma-international.org/ecma-262/5.1/#sec-7.9

Essentially you're safe most of the time, except for return, break,
continue, throw statements, and ++/--. Of course having code occasionally
fail sucks. It might be feasible to just error out in those cases -
essentially you have unreachable code in these cases.

Then again, just not relying on ASI is the simple fix, and makes tooling
easier (also stuff like error recovery in compilers).

Martin

Alex Eagle <notifications@github.com> schrieb am Do., 26. Feb. 2015 um
18:59 Uhr:

**Comment by rkirov** [comment]
+1 for dropping ASI. 

Also dart doesn't have ASI, and I don't see a transformer to add `;` in [1], so we should already be mostly using mandatory semicolons.

[1] https://github.com/angular/angular/blob/master/tools/transpiler/src/codegeneration/DartTransformer.js#L28

**Comment by gdi2290** [comment]
optional ASI seems more feasible;
Using semicolons for `break`, `continue`, `throw` statements, and `++`/`--` does make sense while the only problem with return could be solved by using an expression for dangerous returns. (for those who want to do that);
[example via traceur](http://google.github.io/traceur-compiler/demo/repl.html#%2F%2F%20Options%3A%20--annotations%20--array-comprehension%20--async-functions%20--async-generators%20--exponentiation%20--for-on%20--generator-comprehension%20--member-variables%20--proper-tail-calls%20--require%20--symbols%20--types%20%0A%0Afunction%20swag(a)%20%7B%0A%20%20return%20%2F%2F%20asi%0A%20%20%20%20a%20%2F%2F%20asi%0A%7D%20%0A%0Afunction%20swag(a)%20%7B%0A%20%20return%20(%0A%20%20%20%20a%0A%20%20)%20%2F%2F%20asi%0A%7D)
```javascript
function swag(a) {
  return // asi
    a // asi
} 

function swag(a) {
  return (
    a
  ) // asi
}
```

**Comment by mhevery** [comment]
Is there anything to do here? Can this be closed?

**Comment by alexeagle** [comment]
We will use clang-format for all *.ts files in angular codebase, which means ASI won't be allowed (all semis required)
Other than that, I don't think we are suggesting any restrictions, either for us or for Angular users.

**Comment by alexeagle** [comment]
Actually, my last comment was wrong. clang-format doesn't require semicolons, instead, it can break your code in strange ways when semicolons are omitted. We need something else to enforce that our TypeScript code isn't using ASI.
