### ISSUE TITLE
feat(forms): ngControl add html5 attributes to element for FormBuilder validation 

### ISSUE THREAD

**Issue by awiseman** [angular/angular#8175]
**Steps to reproduce and a minimal demo of the problem**

http://plnkr.co/edit/IAMpyeJl9rQlAcEFPoRs?p=preview

_What steps should we try in your demo to see the problem?_

1. put some input longer than 2 characters in the first input
2. try to put some input longer than 2 characters in the second input

**Current behavior**

HTML5 specifies a number of validation attributes for form elements that browsers are able to interpret to various effects.  These are useful for things like restricting input length (maxLength) and for doing DOM queries (e.g. find all required input elements).

Currently, Angular2 applies validation for a number of these attributes if they are applied in the form template.  However, when forms are built using FormBuilder, validation is defined in the ControlMeta object and not as attributes on the form elements.  ngControl does not apply these validations as attributes to the host element, so when FormBuilder is used, either these attributes will not get defined and therefore the browser's HTML5 validation behavior will not be in effect or validation constraints must be duplicated in the form templates and ControlMeta.

**Expected/desired behavior**

I think it would be useful to have the ngControl directive manage HTML5 validation attributes on the host form element based on the validators applied to the Control object.

**Other information**

**Comment by pkozlowski-opensource** [comment]
> ngControl does not apply these validations as attributes to the host element, so when FormBuilder is used, either these attributes will not get defined and therefore the browser's HTML5 validation behavior will not be in effect

But this is the desired behaviour, no? You don't want to have validation errors coming from _both_ Angular app _and_ a browser. Not to mention that browser error messages are notoriously hard to style, localize etc.

I would be leaning towards "won't fix" unless you've got a very good use-case. Going to close this one for now but happy to re-open if you got use cases where you think it is must-have.

**Comment by awiseman** [comment]
Your reasoning makes sense and I suppose having a single validation mechanism in play is the better option.  In that case, though, I would like to have Angular provide some of the same behavior from browser validations.  This mostly applies to the maxLength validation, that prevents users from typing beyond the allowed length.  There may be others, but that's the one I rely on the most.

**Comment by pkozlowski-opensource** [comment]
@awiseman I see what you are saying. I will re-open so we can think a bit more about this one.

**Comment by pkozlowski-opensource** [comment]
@awiseman, wait but reactive forms _do_ pick up max-length validator rule from a template: https://plnkr.co/edit/jdNXBjmetRe4h9dSNWcg?p=preview

So if you don't want to duplicate max-length just stick it in a template. This would be the one and only "source of truth".

Given the above I'm not sure if we want to reflect certain validation rules back to the DOM. Then again, I hear what you are saying. Leaving it open for now...

**Comment by awiseman** [comment]
The template-based form validations is what initially drove me to think NgControl (now FormControl), should manage validation attributes on host elements for reactive forms.  Using that approach makes use of browser validation behavior, though, since the Angular validations become based on host element attribute values.

It also seems counter-intuitive to require the use of template-based form validations when we're trying to use reactive forms.  One of the main reasons to use reactive forms is that you can define all of your validation behavior in your component, which is more testable than DOM-based validations.

**Comment by manklu** [comment]
@pkozlowski-opensource
> Given the above I'm not sure if we want to reflect certain validation rules back to the DOM.

But you should reflect the aria attributes of the validations

**Comment by kara** [comment]
@awiseman We are actually planning to support this. See https://github.com/angular/angular/issues/9121 for the initial discussion. Closing as a dupe.
