### ISSUE TITLE
JQuery Xeditable is not working with Angular2

### ISSUE THREAD

**Issue by aashishab** [angular/angular#8181]
**IMPORTANT**: I am using JQuery xeditable with Angular2 as given below. But, it the xeditable popup is opening only once.

Can anyone help me on this?. 

**Code snippet are as given below**

Component class:

`
@Component({
//some code here..
})

export class ClientDetailsComponent {
ngOnInIt() {
    $.fn.editable.defaults.mode = 'popup';
    		$.fn.editable.defaults.emptytext = '<i class="pe-7s-pen fa-1x text-primary text-left" title="Click to enter comments"></i>';
    		$('#comments').editable({
    			'rows	':4,
    			'inputclass':'word-wrap newComments',
                onblur:'cancel'
    		});
}

 public showpCommentBox() {
        $('#comments').editable('show');
    }
}

HTML File:

< a class="comments vertical-top word-wrap" id="comments" data-type="textarea" data-pk="1" data-url="" (click)="showpCommentBox()"
									data-title="Enter comments">< i class="pe-7s-pen fa-1x text-primary text-left" title="Click to enter comments"></i>< /a>
`

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by aashishab** [comment]
Thanks for your response i will raise it in another forum.
