### ISSUE TITLE
Model Driven Architectures in AngularJS 2 and ASP.NET

### ISSUE THREAD

**Issue by maroebuck** [angular/angular#8187]
**Concept:**
I'd like to develop independently a Nuget package for Microsoft Visual Studio that generates a  ViewModel Specification for AngularJS 2 for propagating changes from ASP.NET Models to AngularJS 2.

**Scope**
Models and Data Validation in AngularJS 2 and ASP.NET Core 1.0

**Issues:**
It is a proverbial pain having to repeat Models and Data Validation both in ASP.NET Core 1.0 and AngularJS 2 and it is prone to error.

**My Request**
Can you put me in touch with someone that is interested in the concept please and can sponsor?

**Comment by pkozlowski-opensource** [comment]
Sorry, this doesn't sound like an issue that belongs to GitHub. @robwormald are you aware of any initiatives regarding better integration of ng2 and .net ?

**Comment by bastienJS** [comment]
@maroebuck  I can just encourage you to do that, because I am looking for .asp.net core mvc extensions for angular 2 :-). If you need help let me know :-)
