### ISSUE TITLE
bug: number pipe not working on Chrome 34 or older (Cannot redefine property: length)

### ISSUE THREAD

**Issue by ajantsch** [angular/angular#8188]
When using the number pipe like

`<span>{{order.total | number:'.2-2'}}</span>`

I get the following error on Chrome 35 or older:

`EXCEPTION: TypeError: Cannot redefine property: length in [{{order.total | number:'.2-2'}} in ...]`

Intl polyfill is in place.

**Comment by marcoskubis** [comment]
Any progress about this? 
When I the number pipe in a android device:

`{{ item.price | number }}`

I get the following error:

`TypeError: Cannot redefine property: length `

**Comment by rockertux** [comment]
Any news on that?

**Comment by marcoskubis** [comment]
Making custom filters, I get no errors.

**Comment by michaelkrog** [comment]
Same issue with DatePipe and CurrencyPipe.

Example:
```
@Component({
  templateUrl: 'build/pages/page.html'
})
export class Page {
  currentDate: Date = new Date();
...
```

```
<ion-navbar *navbar>
  <ion-title>
    Plan for {{currentDate | date:'shortDate'}}
  </ion-title>
</ion-navbar>
```

Works in Chrome, but on iOS and Android 4.4.2 it results in `TypeError: Cannot redefine property: length`

**Comment by vicb** [comment]
Please find the root cause and open an issue on the Intl project. Thanks.

**Comment by Geoffrey-D** [comment]
For some who want an easy solution, you can use [angular2-moment](https://github.com/urish/angular2-moment)  and then use their pipe :

` {{myDate | amDateFormat:'LL'}}`

This works on KitKat 4.4 (tested on 4.4.2)

**Comment by mlaval** [comment]
The root cause of this issue is in fact zone.js#391

**Comment by Geoffrey-D** [comment]
Thanks for that, I add the link to that issue : https://github.com/angular/zone.js/issues/391
