### ISSUE TITLE
iframe call parent will not trigger component update on the first time

### ISSUE THREAD

**Issue by qiu8310** [angular/angular#8190]
DEMO:  http://qiu8310.github.io/angular2-issue-demo/#/update/from/iframe
SOURCE:  https://github.com/qiu8310/angular2-issue-demo/blob/master/src/components/UpdateFromIframe.ts

Using angular2.0.0-beta.15

**Comment by tbosch** [comment]
Please provide more details if this is still an error. It is not obvious from the demo what is wrong.

**Comment by qiu8310** [comment]
@tbosch  In the demo, if you first click the button `Load iframe to Update`, the text below will not update; when you click it again, the text will update, but the time in the text is not the current click time, but last.

**Comment by mhevery** [comment]
close due to non-reproducibility.
