### ISSUE TITLE
A nicer syntax for 2-way data binding

### ISSUE THREAD

**Issue by userpixel** [angular/angular#8192]
**Current behavior**

- `{{value}}` for interpolation (nice, the industry standard)
- `[property]=value` for 1-way data binding (nice, similar to how you would set an object property in JS)
- `(event)=handler` for event handlers (nice, given the functions use paranthesis)
- `[(ng-model)]=property` (I think this syntax can be expressed nicer. Specially the `[]` and `()` don't really sum up with the above 2 conventions of function and property)

**Desired behavior**
`[[ng-model]]=property` for 2-way data binding

pretty much like how this one is for 1-way data binding: `[property]=property`

I think it's easier to remember.

**Other information**

I know it's probably too late to change the syntax and I respect that. But it would be virtually impossible to change after Angular 2 is released so I rushed to write about it.

**Comment by PascalPrecht** [comment]
Actually, since technically, two-way  data binding really just boils down
to property binding and event binding, `[()]` makes totes sense.

**Comment by robwormald** [comment]
`[property] + (propertyChange) => [(property)]` literally sums it up. 

This was debated endlessly and won't be changed at this point. Sorry :)
