### ISSUE TITLE
MockBackend has different behavior than real backends

### ISSUE THREAD

**Issue by JessieAMorris** [angular/angular#8194]
**Steps to reproduce and a minimal demo of the problem**

On the Observable returned by the MockBackend's response call .map() to transform the response.

https://github.com/JessieAMorris/angular/commit/5788ef1d553ca6d18fdc1ccd3330c3b0a63e4429 has a test for this case that currently fails due to the .map() function never being called.

I would also argue that some of the design decisions made in the MockBackend are invalid. For example being able to subscribe to a response after that response has already been sent does _not_ match the XHRBackend's behavior. This would mean that you could very easily create mocks that work but when it comes time to do it for real it fails. Mocks should emulate the real behavior as closely as possible.

**Comment by JessieAMorris** [comment]
Just kidding about the .map() call. This was something that I was doing incorrectly by calling `.do` which doesn't activate until someone else calls .subscribe().

I would still argue that the design for MockBackend should be looked at again, though.

**Comment by JessieAMorris** [comment]
Actually, it looks like .do() should work but it's not working for unknown reasons.

**Comment by mildfuzz** [comment]
I have produced a test case here #12857

**Comment by alxhub** [comment]
You are absolutely correct in that `MockBackend` behaves synchronously and it should not.

This will be fixed in the newer HTTP APIs that are coming soon.
