### ISSUE TITLE
Routeconfig issue commenting within export class line

### ISSUE THREAD

**Issue by KHAAAAN** [angular/angular#8200]
So lets say you have an app.component.ts and in it you have this:

@RouteConfig([
	{
		path: '/business_demographics', 
		name: 'LocationForm',
		component: LocationFormComponent,
		useAsDefault: true
	}
])

lets say i have a location.form.component with the component decorator and the following code:

export class LocationFormComponent /\*implements OnInit\*/ {
 ngOnInit(){
//etc..
}
}

I get the following log issue, HOWEVER it works just fine without defining it in our RouteConfig. 

[log file](https://github.com/angular/angular/files/232755/notswag.txt)

To fix: Once you take out the comment /\*implements OnInit\*/ it will work with RouteConfig.
Sorry if this is a known issue or I'm missing something, but it got me for a bit and was hoping if it ever came up with anyone else, this might help.

Also, I was using beta11 for this app.

**Comment by zoechi** [comment]
I think there is more information required to debug this issue. Can you create a Plunker?

**Comment by vicb** [comment]
obsolete - former router
