### ISSUE TITLE
import {CORE_DIRECTIVES} from "angular2/common": mark CORE_DIRECTIVES deprecated?

### ISSUE THREAD

**Issue by about-code** [angular/angular#8206]
API-Docs indicate CORE_DIRECTIVES seem identical to COMMON_DIRECTIVES but don't tell what's the future proof export. Can one or the other be marked/documented as deprecated? Having both make their way to 1.0 doesn't look advisable to me.

**Comment by pkozlowski-opensource** [comment]
`CORE_DIRECTIVES` and `COMMON_DIRECTIVES` are 2 different things: `CORE_DIRECTIVES` has core primitives (NgFor, NgIf etc.) while `COMMON_DIRECTIVES` contains core + forms. In any case it shouldn't impact users much since common directives are available in all templates by default.
