### ISSUE TITLE
Tour of Heroes tutorial back link does not refresh dashboard or heroes on Safari

### ISSUE THREAD

**Issue by applequist** [angular/angular#8207]
Hi,

I've been following the Tour of Heroes tutorial. I've noticed that the back link to return from the hero detail component to the dashboard or the list of heroes does not work properly on safari. 

Environment:
Safari 9.1 on Mac OS X 10.11.4

1. Go to https://angular.io/resources/live-examples/toh-5/ts/plnkr.html
![dashboard-on-init](https://cloud.githubusercontent.com/assets/4221155/14768326/79dd1dbe-0a3f-11e6-9fbe-ca021d692090.png)

2. click on one hero on the dashboard => details appears
![detail](https://cloud.githubusercontent.com/assets/4221155/14768327/7ecdc71a-0a3f-11e6-96a2-3e8ff471e427.png)

3. click on the back button at the button => the dashboard is empty !!!
![dashboard-after-back](https://cloud.githubusercontent.com/assets/4221155/14768329/81e9991a-0a3f-11e6-9136-9476b63a00a7.png)

I tested it on Firefox 45.0.1 and it works ok: in step 3 the dashboard is correctly populated.

thanks. 

Brieuc

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/issues/7722 and https://github.com/angular/angular/issues/7873

**Comment by applequist** [comment]
thanks. Sorry for the duplicate...

**Comment by ericmartinezr** [comment]
@applequist all good :+1:

**Comment by theodorejb** [comment]
I'm seeing this same issue in Internet Explorer 11, and it completely breaks routing on these platforms. IMO this should block the release candidate @mhevery.

**Comment by CaptainCodeman** [comment]
The current broken router has been abandoned, there is an alt router that we hope will fix these types of issues.

**Comment by pkozlowski-opensource** [comment]
This should be reported in https://github.com/angular/angular.io/issues if still an issue.
