### ISSUE TITLE
Benchpress: report FPS, SPF and missed frame count

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#821]
FPS: average, min and max frames per second
SPF: average, min and max seconds per frame
Missed frame count: number of frames that took more than 16ms (60fps), 33ms (30fps) and 66ms (15fps)

**Comment by naomiblack** [comment]
Assigning to @tbosch (as owner for @goderbauer, who is working on this actively)

**Comment by goderbauer** [comment]
With the last two pull requests, the following metrics were added to benchpress:
* `frameTime.mean`: mean frame time in ms (target: 16.6ms for 60fps)
* `frameTime.worst`: worst frame time in ms
* `frameTime.best`: best frame time in ms
* `frameTime.smooth`: percentage of frames that hit 60fps

To collect these metrics, you need to execute `console.time('frameCapture')` and `console.timeEnd('frameCapture')` either in your benchmark application or in you benchmark driver via webdriver. The metrics mentioned above will only be collected between those two calls and it is recommended that you wrap the time/timeEnd calls as closely as possible around the action you want to evaluate to get accurate measurements.

In addition to that, you also need to pass one extra binding to benchpress in tests that want to collect these metrics:

    benchpress.sample(bindings: [bp.bind(bp.Options.CAPTURE_FRAMES).toValue(true)], ... )

@tbosch @yjbanov I believe, with these metrics the issue can be closed. If you feel like we should add more metrics related to this issue let me know.

**Comment by tbosch** [comment]
+1 for closing this. We can reopen when we know what things are missing specifically when benchmarks are written.

**Comment by naomiblack** [comment]
this is internal b/20763038
