### ISSUE TITLE
Remove current animation + instruction for early access to animate

### ISSUE THREAD

**Issue by shlomiassaf** [angular/angular#8210]
Hi,

Reading the [public document ](https://docs.google.com/document/d/1rTJKNJ6Rv2N5jElLIrrukuEsS_kFOQPH1D5O1Dfva44/edit#heading=h.y8l40ifx6ic9) about animation in angular 2, I can't wait for it to land.

It seems that there's no way to get the feeling of it and play with the alpha of animate.
I'v seen the progress in @matsko 's fork, it look great but it is split to branch's, master way behind (b7).

On top of that, there is an animate implementation in `master` that is known to be obsolete.
I spent around 5 hours playing with it and writing a blog post, for nothing... no hint it's a gonner.

Is there a way to integrate such alpha features into an experimental build so people can play with these features, write blog posts and provide feedback?

Just to be clear, this is not criticism, just an offer.

Thank you all!

**Comment by pkozlowski-opensource** [comment]
Updated animations landed in master via 5e0f8cf3f06f866634ffc0ff6d73081f42ed4225 and docs are in the works.
