### ISSUE TITLE
Error in a single routerLink breaks the entire routing 

### ISSUE THREAD

**Issue by smedavarapu** [angular/angular#8211]
Hello,
The BaseException in a child route is breaking the route configurations of the application.

**Steps to reproduce and a minimal demo of the problem**
Demo in this [plunker](https://plnkr.co/edit/UTjIqBZZT20QJWLgOvNv?p=preview)
Steps are clearly explained in component section of home.component.ts 

**Current behavior**
For instance misspelling 'bar' as 'ba' in [routerLink]="['foo', 'ba']", generates a Base Exceptions that can be handled by a custom handler, but the errors are breaking the route configurations before catching them. A single route failure is blocking the entire application and there is no further navigation to the independent routes. The only solution is to reload the entire app. 

**Expected/desired behavior**
A failure in a single route is supposed to block the respective route but not the other independent routes registered in RouteConfig.

**Comment by michalstepien** [comment]
In new router bad router links not throw errors. Pls close.
