### ISSUE TITLE
navigation issue on Safari

### ISSUE THREAD

**Issue by akaRem** [angular/angular#8214]
**Steps to reproduce and a minimal demo of the problem**

Used demo from official page https://angular.io/docs/ts/latest/tutorial/toh-pt5.html

in HeroDetailComponent  ``window.history.back();`` doesn't fully reload previous view.

**Steps to reproduce and a minimal demo of the problem**
https://angular.io/resources/live-examples/toh-5/ts/plnkr.html
actions:
Dashboard -> any hero -> back
and 
Heroes -> any hero-> details -> back

**Current behavior**

Only Top Heroes / My Heroes header is shown

**Expected/desired behavior**

List of heroes should be rendered

**Other information**

Reproducible:
10/10 on Safari 9.1 (11601.5.17.1)
0/10 on Chrome 49.0.2623.110 (64-bit)

Looks like platform-dependent issue

I also tried Location#back() — didn't work too

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/issues/7722 and https://github.com/angular/angular/issues/7873

**Comment by akaRem** [comment]
@ericmartinezr Agree, the same issue

**Comment by vicb** [comment]
obsolete
