### ISSUE TITLE
Two-way data-binding <select> does not work in Firefox

### ISSUE THREAD

**Issue by Hongbo-Miao** [angular/angular#8215]
This is a simple two-way data-binding for `<select>`.

[Live demo using plnkr](http://plnkr.co/edit/gcACo4TkRLoDNfHJrmj8?p=preview) (Angular 2 beta 15).

    @Component({
      selector: 'my-app',
      template: `
        <select [(ngModel)]="product.partCode">
          <option *ngFor="#part of parts" [value]="part.code">{{part.name}}</option>
        </select>
        <select [(ngModel)]="product.levelCode">
          <option *ngFor="#level of levels" [value]="level.code">{{level.name}}</option>
        </select>
        {{product|json}}
      `
    })
    export class App {
      product = { partCode: 'aa', levelCode: 'lv1' };
      parts = [
        { code: 'aa', name: 'AA' },
        { code: 'bb', name: 'BB' }
      ];
    
      levels = [
        { code: 'lv1', name: 'Level 1' },
        { code: 'lv2', name: 'Level 2' }
      ];
    }

When you select a new option, `{{product|json}}` can show it changes. This works well in **Chrome**, **Safari**, and **Opera**.

However when I use **Firefox Developer Edition 47.0a2** and **Firefox Nightly 48.0a1**, `{{product|json}}` won't change.

Refer to [here](http://stackoverflow.com/questions/36828450/how-to-let-two-way-data-binding-select-work-in-firefox).

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/issues/6573, it is fixed in master afaik so it should be fixed in beta 16. You can see in that same issue for workarounds.

**Comment by Hongbo-Miao** [comment]
@ericmartinezr thanks for letting me know!
