### ISSUE TITLE
Testability should be able to get info on pending tasks

### ISSUE THREAD

**Issue by juliemr** [angular/angular#8219]
When waiting for stability times out, it is useful to be able to get information about pending tasks. (Protractor does this for Angular 1 with a decorator on the timeout and http services).

Testability may be able to export some info on pending tasks from the `ngZone`. Could look like:

``` js
testability.listPending() => {
  type: 'macroTask';
  source: 'xhr.send';
  isPeriodic: 'false'
}
```

**Comment by rcomblen** [comment]
Any update on this?

It's pretty hard to debug failing tests without this feature.

**Comment by juliemr** [comment]
Note that we've also run into difficulty debugging `whenStable` in the context of an ngUpgrade application - with two sets of testability running at once, it becomes even more difficult to reason about.

**Comment by J-Swift** [comment]
Any progress here? Or any pointers on how to get at this information myself? I'm finding it really difficult to find what is causing my zone to hang indefinitely when heavily utilizing rxjs across the application.

**Comment by magnattic** [comment]
Relevant SO question: https://stackoverflow.com/questions/48627074/how-to-track-which-async-tasks-protractor-is-waiting-on

Maybe the answer helps people with this problem until Angular supports this better.

**Comment by EugeneSnihovsky** [comment]
Solution from @magnattic not perfect but this is much better then nothing and it is stable works. It is possible to collaborate with ngZone team and create OOB solution?

**Comment by JiaLiPassion** [comment]
I will check this one.

**Comment by stasberkov** [comment]
guys, please, very needed feature.

**Comment by Anton2478** [comment]
+1

**Comment by stasberkov** [comment]
Infact you can get list of pending tasks **without zone.js patching**.

Import `node_modules/zone.js/dist/task-tracking.js` file after `zone.js`
Then in your code get `NgZone` instance and use it like
```
import * as _ from "lodash";
...

setInterval(() => {
   var tasks: any[] = (<any>ngZone)._inner._parent._properties.TaskTrackingZone.getTasksFor("macroTask");
   tasks= _.clone(tasks);
   if (_.size(tasks) > 0) {
          console.log("ZONE pending tasks=", tasks);
   }
}, 1000);
```
I posted my solution here: https://stackoverflow.com/a/57854350/586609

**Comment by jessicajaniuk** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular version.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
