### ISSUE TITLE
metadata collection doesn't include Provider

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#8223]
https://github.com/angular/angular/blob/master/modules/angular2/src/common/forms/directives/ng_control_name.ts

```
const controlNameBinding =
    CONST_EXPR(new Provider(NgControl, {useExisting: forwardRef(() => NgControlName)}));
@Directive({
  selector: '[ngControl]',
  bindings: [controlNameBinding],
  inputs: ['name: ngControl', 'model: ngModel'],
  outputs: ['update: ngModelChange'],
  exportAs: 'ngForm'
})
export class NgControlName extends NgControl implements OnChanges,
    OnDestroy {
...
```
https://raw.githubusercontent.com/angular/angular/builds-js/src/common/forms/directives/ng_control_name.metadata.json
```
bindings: [
{
__symbolic: "reference",
name: "controlNameBinding",
module: "angular2/src/common/forms/directives/ng_control_name"
}
],
```

is missing the provider of NgControl.

cc @chuckjaz

**Comment by chuckjaz** [comment]
The expression used to initialize `bindings` is constant but is a constructor call which I don't represent in the AST so the variable value is referenced.

This would work, I believe, if the const was exported.

**Comment by alexeagle** [comment]
I tried adding `export` on the declaration of `controlNameBinding` but there is still no entry for it in `ng_control_name.metadata.json` - just the reference from the decorator's `bindings`

**Comment by tbosch** [comment]
@mhevery is talking about changing all of our providers into object literals like
```
const controlNameBinding =
    {  token: NgControl, useExisting: forwardRef(() => NgControlName) };
```

Then this should probably be easier.

Maybe related:
See my [last comment](https://github.com/angular/sickle/issues/131#issuecomment-214588864) on the sickle issue to produce annotations, which requires to desugar decorators into similar object literals.

**Comment by alexeagle** [comment]
I see, then we also need to change the reflectors to read data in this way, correct? I suppose we need to make that decision before trying to fix this issue.

**Comment by chuckjaz** [comment]
The function call with a lambda would still be a problem. We would have to treat forward similar to how we currently treat CONST_EXPR, That is I would need to know that it really translates into a reference to `NgControlName`.

For now I propose we do the following, 

- Encode constructor calls into an AST with a reference to the constructor (much like decorators already are).
- Special case calls to functions of the name `forwardRef()` that are passed a zero parameter lambda expression as simplifying to the body of the lambda.
- Add code to StaticReflector to call the `Provider` constructor.

The would allow the original declaration to work as well as supporting the proposed change. With the change we could remove collecting constructor invocations and the constructing `Provider`.

**Comment by vicb** [comment]
@chuckjaz what is the status here?

**Comment by chuckjaz** [comment]
This is obsolete. `Provider` was deprecated and removed.
