### ISSUE TITLE
Beta 16, breaking change?!

### ISSUE THREAD

**Issue by Ristaaf** [angular/angular#8229]
In beta 16, I suddenly get 
error TS2305: Module '"<my repo path>/node_modules/angular2/router"' has no exported member 'LocationStrategy'.
error TS2305: Module '"<my repo path>/node_modules/angular2/router"' has no exported member 'HashLocationStrategy'.
error TS2305: Module '"<my repo path>/node_modules/angular2/router"' has no exported member 'Location'.

No mention in the changelog about a possible change to the naming, path, or functioning of using LocationStrategy, HasLocationStrategy and Location.

**Comment by choeller** [comment]
Hi, I also stumbled over this. The breaking change is explained here: https://github.com/angular/angular/commit/b602bd8c835ef33f9d0c44e2595558471462fec5 I already added a pull request with the missing changes

**Comment by KillerCodeMonkey** [comment]
All location stuff is now in 'angular2/platform/common'

**Comment by pkozlowski-opensource** [comment]
It is part of the changelog now: https://github.com/angular/angular/blob/master/CHANGELOG.md
