### ISSUE TITLE
resolve routerOnActivate Promise (and unblock navigation) when user go away by routerLink

### ISSUE THREAD

**Issue by ertle** [angular/angular#8231]
Hey, guys! 

I have a route that waits until the AJAX request  is completed. Promise returned by routerOnActivate hook blocks route navigation.

There is a some problem. When user go away by some routerLink to another route, how can app respond to user interaction? Routing is blocking, and now app is waiting while blocked route will be resolved, and only then navigate by routerLink.

**Steps to reproduce and a minimal demo of the problem**

http://plnkr.co/edit/paupFnGsRdI0mEsge5Pz?p=preview

**Comment by zoechi** [comment]
JS/TS isn't actually my main language but I guess something like this should work:

```html
< [routerLink]="xxx" (click)="cancelRequest()">xxx</a>
```
```ts
routerOnActivate() {
  new Promise((resolve, reject) => { 
    this.subscription = service.getData().observable.subscribe(val => {
      ...
      resolve();
    },
      error => reject(); /* or resolve()  anyway */);
    });
  });
}

cancelRequest() {
  if(this.subscription) {
    this.subscription.unsubscribe();
  }
}
```

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by ertle** [comment]
I think handle click is not a good practice. 

Here is a plunk - http://plnkr.co/edit/paupFnGsRdI0mEsge5Pz?p=preview  (please note link 'page2' is outside of my Page1 component ) 

1. Click page1 link 
2. Click page2 link

No navigation happens. It seems wrong.

**Comment by vicb** [comment]
is this still an issue with the latest router

**Comment by vsavkin** [comment]
It seems the issue was opened before the router rewrite. And it doesn't look like the issue still makes sense. I'm closing it. Please reopen it if you think it still makes sense.
