### ISSUE TITLE
Doesn't work after upgrade

### ISSUE THREAD

**Issue by diamo1213** [angular/angular#8233]
Hi guys,
I've just upgraded angular2 and all mods. And my angular2 app stops to work. Developer tool of the browser says:

EXCEPTION: Error in :0:0 browser_adapter.js:86
"EXCEPTION: Error in :0:0" browser_adapter.js:77:12
BrowserDomAdapter.prototype.logError() browser_adapter.js:77
BrowserDomAdapter.prototype.logGroup() browser_adapter.js:87
ExceptionHandler.prototype.call() exception_handler.js:57
ApplicationRef_.prototype.run/<() application_ref.js:308
Zone</ZoneDelegate</ZoneDelegate.prototype.invoke() angular2-polyfills.js:349
NgZoneImpl/this.inner<.onInvoke() ng_zone_impl.js:45
Zone</ZoneDelegate</ZoneDelegate.prototype.invoke() angular2-polyfills.js:348
Zone</Zone</Zone.prototype.run() angular2-polyfills.js:242
NgZoneImpl.prototype.runInner() ng_zone_impl.js:76
NgZone.prototype.run() ng_zone.js:223
ApplicationRef_.prototype.run() application_ref.js:297
ApplicationRef_.prototype.bootstrap() application_ref.js:319
coreLoadAndBootstrap/</<() application_ref.js:109
Zone</ZoneDelegate</ZoneDelegate.prototype.invoke() angular2-polyfills.js:349
NgZoneImpl/this.inner<.onInvoke() ng_zone_impl.js:45
Zone</ZoneDelegate</ZoneDelegate.prototype.invoke() angular2-polyfills.js:348
Zone</Zone</Zone.prototype.run() angular2-polyfills.js:242
scheduleResolveOrReject/<() angular2-polyfills.js:597
Zone</ZoneDelegate</ZoneDelegate.prototype.invokeTask() angular2-polyfills.js:382
NgZoneImpl/this.inner<.onInvokeTask() ng_zone_impl.js:36
Zone</ZoneDelegate</ZoneDelegate.prototype.invokeTask() angular2-polyfills.js:381
Zone</Zone</Zone.prototype.runTask() angular2-polyfills.js:282
drainMicroTaskQueue() angular2-polyfills.js:500
ZoneTask/this.invoke() angular2-polyfills.js:452

"ORIGINAL EXCEPTION: TypeError: styles is undefined" browser_adapter.js:77:12

"ORIGINAL STACKTRACE:" browser_adapter.js:77:12

"_flattenStyles@http://localhost:3000/node_modules/angular2/src/platform/dom/dom_renderer.js:303:21
DomRenderer@http://localhost:3000/node_modules/angular2/src/platform/dom/dom_renderer.js:68:24
DomRootRenderer.prototype.renderComponent@http://localhost:3000/node_modules/angular2/src/platform/dom/dom_renderer.js:43:24
DebugDomRootRenderer.prototype.renderComponent@http://localhost:3000/node_modules/angular2/src/core/debug/debug_renderer.js:9:37
MdDialog@http://localhost:3000/node_modules/ng2-material/components/dialog/dialog.js:32:26
ReflectionCapabilities.prototype.factory/<@http://localhost:3000/node_modules/angular2/src/core/reflection/reflection_capabilities.js:16:51
ReflectiveInjector_.prototype._instantiate@http://localhost:3000/node_modules/angular2/src/core/di/reflective_injector.js:692:27
ReflectiveInjector_.prototype._instantiateProvider@http://localhost:3000/node_modules/angular2/src/core/di/reflective_injector.js:627:20
ReflectiveInjector_.prototype._new@http://localhost:3000/node_modules/angular2/src/core/di/reflective_injector.js:616:16
ReflectiveInjectorDynamicStrategy.prototype.getObjByKeyId@http://localhost:3000/node_modules/angular2/src/core/di/reflective_injector.js:271:1
ReflectiveInjector_.prototype._getByKeyDefault@http://localhost:3000/node_modules/angular2/src/core/di/reflective_injector.js:796:23
ReflectiveInjector_.prototype._getByKey@http://localhost:3000/node_modules/angular2/src/core/di/reflective_injector.js:768:20
ReflectiveInjector_.prototype.get@http://localhost:3000/node_modules/angular2/src/core/di/reflective_injector.js:577:16
anonymous/_View_AppComponent_Host0.prototype.createInternal@AppComponent_Host.template.js:13:298
AppView.prototype.create@http://localhost:3000/node_modules/angular2/src/core/linker/view.js:77:24
ComponentFactory.prototype.create@http://localhost:3000/node_modules/angular2/src/core/linker/component_factory.js:150:27
ApplicationRef_.prototype.bootstrap/<@http://localhost:3000/node_modules/angular2/src/core/application_ref.js:321:27
ApplicationRef_.prototype.run/<@http://localhost:3000/node_modules/angular2/src/core/application_ref.js:299:26
Zone</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:349:20
NgZoneImpl/this.inner<.onInvoke@http://localhost:3000/node_modules/angular2/src/core/zone/ng_zone_impl.js:45:32
Zone</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:348:20
Zone</Zone</Zone.prototype.run@http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:242:25
NgZoneImpl.prototype.runInner@http://localhost:3000/node_modules/angular2/src/core/zone/ng_zone_impl.js:76:60
NgZone.prototype.run@http://localhost:3000/node_modules/angular2/src/core/zone/ng_zone.js:223:51
ApplicationRef_.prototype.run@http://localhost:3000/node_modules/angular2/src/core/application_ref.js:297:9
ApplicationRef_.prototype.bootstrap@http://localhost:3000/node_modules/angular2/src/core/application_ref.js:319:1
coreLoadAndBootstrap/</<@http://localhost:3000/node_modules/angular2/src/core/application_ref.js:109:43
Zone</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:349:20
NgZoneImpl/this.inner<.onInvoke@http://localhost:3000/node_modules/angular2/src/core/zone/ng_zone_impl.js:45:32
Zone</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:348:20
Zone</Zone</Zone.prototype.run@http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:242:25
scheduleResolveOrReject/<@http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:597:53
Zone</ZoneDelegate</ZoneDelegate.prototype.invokeTask@http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:382:24
NgZoneImpl/this.inner<.onInvokeTask@http://localhost:3000/node_modules/angular2/src/core/zone/ng_zone_impl.js:36:32
Zone</ZoneDelegate</ZoneDelegate.prototype.invokeTask@http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:381:24
Zone</Zone</Zone.prototype.runTask@http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:282:29
drainMicroTaskQueue@http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:500:26
ZoneTask/this.invoke@http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:452:22
" browser_adapter.js:77:12

"ERROR CONTEXT:" browser_adapter.js:77:12

Object { _view: Object, _nodeIndex: 0, _tplRow: 0, _tplCol: 0 }

**Comment by zoechi** [comment]
Can you please provide more details. From what version did you upgrade to what version? Which browsers have you tried. How does your project configuration look like, ...

**Comment by diamo1213** [comment]
package.json:

{
  "name": "angular2-boilerplate",
  "version": "1.0.0",
  "scripts": {
    "postinstall": "npm run typings install",
    "lite": "lite-server",
    "gulp": "gulp",
    "start": "concurrent \"npm run gulp\" \"npm run lite\" ",
    "typings": "typings"
  },
  "license": "ISC",
  "dependencies": {
    "angular2": "^2.0.0-beta.7",
    "es6-promise": "^3.0.2",
    "es6-shim": "^0.33.3",
    "ng2-material": "^0.2.7",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.2",
    "systemjs": "0.19.22",
    "zone.js": "0.5.15"
  },
  "devDependencies": {
    "autoprefixer": "^6.2.1",
    "cssnano": "^3.4.0",
    "concurrently": "^1.0.0",
    "gulp": "^3.9.0",
    "gulp-ext-replace": "^0.2.0",
    "gulp-imagemin": "^2.4.0",
    "gulp-postcss": "^6.0.1",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-typescript": "^2.10.0",
    "gulp-uglify": "^1.5.1",
    "lite-server": "^2.0.1",
    "postcss": "^5.0.13",
    "postcss-scss": "^0.1.3",
    "precss": "^1.3.0",
    "typings": "^0.6.8",
    "tsd": "^0.6.5-beta"
  }
}

**Comment by diamo1213** [comment]
FireFox ESR 38.3.0

**Comment by diamo1213** [comment]
html:

<html>
<head>
    <base href="./">
    <title>MyBizzo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    
    

    <link rel="stylesheet" href="node_modules/ng2-material/dist/ng2-material.css">
    <link rel="stylesheet" href="node_modules/ng2-material/dist/font.css">

    <script src="node_modules/es6-shim/es6-shim.min.js"></script>
    <script src="node_modules/systemjs/dist/system-polyfills.js"></script>
    <script src="node_modules/angular2/bundles/angular2-polyfills.js"></script>
    <script src="node_modules/systemjs/dist/system.src.js"></script>
    <script src="node_modules/rxjs/bundles/Rx.js"></script>
    <script src="node_modules/angular2/bundles/angular2.dev.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
    


    
    <script>
        System.config({
            map: {
                app: "app",
                'ng2-material':"node_modules/ng2-material",
                'angular2':"node_modules/angular2"
            },
            packages: {
                app: {
                    format: 'register',
                    defaultExtension: 'js'
                },
                'ng2-material': {
                    defaultExtension: 'js'
                },
                'angular2': {
                    defaultExtension: 'js'
                }
            }
        });
        System.import('app/boot')
                .then(null, console.error.bind(console));
    </script>

    <link rel="stylesheet" href="src/css/app.css">
</head>

<body><script type='text/javascript' id="__bs_script__">//<![CDATA[
    document.write("<script async src='/browser-sync/browser-sync-client.2.11.1.js'><\/script>".replace("HOST", location.hostname));
//]]></script>

<my-app>Loading...</my-app>

<script src="mods/b2bapic_sdk_1.x.js"></script>
</body>
</html>

**Comment by diamo1213** [comment]
bootstrap:
`
import {bootstrap} from 'angular2/platform/browser';
import {provide} from 'angular2/core';
import {AppComponent} from './app.component';
import {BackEnd} from './backend.service';
import {ComuteService} from './comute.sevice';
import {MATERIAL_PROVIDERS, SidenavService} from 'ng2-material/all';
import {ROUTER_PROVIDERS} from 'angular2/router';

bootstrap(AppComponent, [BackEnd, ROUTER_PROVIDERS, MATERIAL_PROVIDERS,
    SidenavService, ComuteService]);
`

**Comment by diamo1213** [comment]
I rolled back to 2.0.0-beta-14. works now

**Comment by ericmartinezr** [comment]
@diamo1213 the problem is not in angular2 but in ng2-material, you can follow this issue https://github.com/justindujardin/ng2-material/issues/204
