### ISSUE TITLE
Glitch while panning a map in Leaflet

### ISSUE THREAD

**Issue by bel3atar** [angular/angular#8236]
I am working on a Leaflet based project with Ionic 2.
After [this](https://github.com/driftyco/ionic2-app-base/commit/37352d7dd8d21f02bab0169cd7a4ccde8ea2fa79) commit which moves from Angular beta 6 to beta 13, I started experiencing glitches when panning a map.

I would've liked to provide a demo app but I can't make plunkr work with older beta versions.

**Comment by pkozlowski-opensource** [comment]
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
