### ISSUE TITLE
Beta.16 - Location.createComponent function is not defined when using custom router-outlet

### ISSUE THREAD

**Issue by BrunoAMSilva** [angular/angular#8238]
After updating to beta 16 I've come across an issue with a custom router I've created to validate if the user has permission to access the route.

```
import { Directive, ElementRef, DynamicComponentLoader, Attribute } from "angular2/core";
import { Router, RouterOutlet, ComponentInstruction } from "angular2/router";
import { Location } from "angular2/platform/common";
import { DataStoreService } from "../../core/core";

@Directive({
	selector: "router-outlet"
})
export class LoggedInRouterOutlet extends RouterOutlet {
	private publicRoutes: Array<string>;

	constructor(
		_elementRef: ElementRef,
		_loader: DynamicComponentLoader,
		private parentRouter: Router,
		private _location: Location,
		@Attribute("name") nameAttr: string,
		private _dataStore: DataStoreService) {
		super(_elementRef, _loader, parentRouter, nameAttr);

		this.publicRoutes = [
			"", "login"
			];
	}

	public activate(instruction: ComponentInstruction) {
		if (this._canActivate(instruction.urlPath)) {
			return super.activate(instruction);
		}

		this.parentRouter.navigate(["Login"]);
	}

	private _canActivate(url) {
		return this.publicRoutes.indexOf(url) !== -1 || this._dataStore.Utilizador;
	}
}
```

`"dependencies": {
    "angular2": "2.0.0-beta.16",
    "systemjs": "0.19.26",
    "es6-shim": "^0.35.0",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.2",
    "zone.js": "0.6.12",
    "lodash": "^4.8.2"
  }`

This code doesn't give any exception, however I receive an error in the developer tools and the route doesn't change.

EXCEPTION: Error: Uncaught (in promise): TypeError: location.createComponent is not a function
STACKTRACE:
Error: Uncaught (in promise): TypeError: location.createComponent is not a function
    at l (http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.min.js:1:2975)
    at http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.min.js:1:2725
    at e.invoke (http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.min.js:1:7197)
    at Object.NgZoneImpl.inner.inner.fork.onInvoke (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:2185:31)
    at e.invoke (http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.min.js:1:7148)
    at e.run (http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.min.js:1:4584)
    at http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.min.js:1:3318
    at e.invokeTask (http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.min.js:1:7828)

This was working with beta.15, so I assume something has changed but looking at the changelog I don't see any obvious reason for this not to work.

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/commit/b602bd8c835ef33f9d0c44e2595558471462fec5, `Location` was moved to `angular2/platform/common`

**Comment by BrunoAMSilva** [comment]
I've read that and changed it, same error, just forgot to put it in the code.

**Comment by pietie** [comment]
I got the same error when calling loadNextToLocation on my DynamicComponentLoader. 
The ElementRef parameter changed type to ViewContainerRef. So I just injected that and used that instead which fixed my issue. I see the RouterOutlet constructor also takes a ViewContainerRef where you are passing an ElementRef so perhaps try changing that?

**Comment by BrunoAMSilva** [comment]
Thank you pietie. That solved my issue too. My docs weren't updating on VSCode so I had no idea it had changed.

**Comment by scosc** [comment]
@pietie can you give an example of you solved the issue when calling loadNextToLocation on DynamicComponentLoader?

**Comment by denodaeus** [comment]
Also looking for an example.  I'm trying to get the location from the element ref from before, but when I change this to a viewcontainerref I'm not exactly sure how that translates a particular ref vs the whole view container:

before:
`
  constructor(private loader: DynamicComponentLoader, private elementRef: ElementRef) { }

  open(inputEventName: 'click' | 'dblclick') {
    if (inputEventName !== this.eventBinding) {
      return false;
    }

    let appEleRef = elementRef['_rootComponents'][0].location;
    let bindings = ReflectiveInjector.resolve([provide(WORK_ITEM_TOKEN, { useValue: this.workItem })]);
    return this.loader.loadNextToLocation(WorkItemModalComponent, appEleRef, bindings).then(workItemModalRef => {
      let workItemModelComponent = <WorkItemModalComponent>workItemModalRef.instance;
      workItemModelComponent.closeEvent.subscribe(_ => {
        workItemModalRef.dispose();
        this.close.emit(_);
      });
      workItemModelComponent.saveEvent.subscribe(_ => this.save.emit(_));
      return workItemModalRef;
    });
  }
`

after:
`
  constructor(private loader: DynamicComponentLoader, private viewContainerRef: ViewContainerRef) { }

  open(inputEventName: 'click' | 'dblclick') {
    if (inputEventName !== this.eventBinding) {
      return false;
    }

    let appEleRef = this.viewContainerRef['_rootComponents'][0].location;
    let bindings = ReflectiveInjector.resolve([provide(WORK_ITEM_TOKEN, { useValue: this.workItem })]);
    return this.loader.loadNextToLocation(WorkItemModalComponent, appEleRef, bindings).then(workItemModalRef => {
      let workItemModelComponent = <WorkItemModalComponent>workItemModalRef.instance;
      workItemModelComponent.closeEvent.subscribe(_ => {
        workItemModalRef.dispose();
        this.close.emit(_);
      });
      workItemModelComponent.saveEvent.subscribe(_ => this.save.emit(_));
      return workItemModalRef;
    });
  }
`

**Comment by sfabriece** [comment]
@BrunoAMSilva can you give an example of how you ended up fixing you routeroutlet problem? thanks.

**Comment by ericmartinezr** [comment]
This first argument for router outlet is the ViewContainerRef

```
constructor(private _viewContainerRef: ViewContainerRef, private _loader: DynamicComponentLoader,
              private _parentRouter: routerMod.Router, @Attribute('name') nameAttr: string) {
```
Ref https://github.com/angular/angular/blob/master/modules/angular2/src/router/directives/router_outlet.ts#L42

So if you have your own extension of router-outlet you should pass ViewContainerRef as first argument instead of ElementRef

Using @BrunoAMSilva's code snippet
```typescript
export class LoggedInRouterOutlet extends RouterOutlet {
    private publicRoutes: Array<string>;

    constructor(_viewContainer: ViewContainerRef, _loader: DynamicComponentLoader, ...) {
        super(_viewContainer, _loader, ...);
    }
}
```

**Comment by sfabriece** [comment]
Thanks @ericmartinezr
