### ISSUE TITLE
The beta.16 changelog is missing the *Location and APP_BASE_HREF breaking change

### ISSUE THREAD

**Issue by Tragetaschen** [angular/angular#8240]
In b602bd8c, there is a well documented breaking change that's not part of the changelog for beta.16

**Comment by ericmartinezr** [comment]
There's already a PR for it https://github.com/angular/angular/pull/8230

**Comment by Delagen** [comment]
Throws the error
```
No base href set. Please provide a value for the APP_BASE_HREF token or add a base element to the document.
```
added
```
provide(LocationStrategy, {useClass: HashLocationStrategy}),
provide(APP_BASE_HREF, {useValue: "/"})
```
but nothing changed

**Comment by ericmartinezr** [comment]
@Delagen you don't need to provide APP_BASE_HREF if you're using HashLocationStrategy. Your issue must in your imports, router works perfectly for me with b16 http://plnkr.co/edit/XFyit3Lim3MyLZRFVSiP?p=preview

**Comment by Tragetaschen** [comment]
Changelog has landed.Yay!
