### ISSUE TITLE
[RC.x] Injecting missing import throws Cannot read property query of null

### ISSUE THREAD

**Issue by ericmartinezr** [angular/angular#8245]
Hard to explain in the title

**Steps to reproduce and a minimal demo of the problem**

See http://plnkr.co/edit/BpjzGxQU5CEStzmWdWfh?p=preview , note that I correctly imported Renderer, but I forgot to add ElementRef. Renderer is undefined when it shouldn't.

**What steps should we try in your demo to see the problem?**

Run the plnkr and see the console

**Current behavior**

Now if I inject something I forgot to import no error is thrown and all of the classes injected in the constructor are undefined, even if they're correctly imported

**Expected/desired behavior**

It should work as <= b.15 throwing an error like

```
Cannot resolve all parameters for 'App'(Renderer, ?)
```
See plnkr http://plnkr.co/edit/aP6UWXsDOYaz3yV9U7Pp?p=preview with b.15

**Other information**

**Comment by ericmartinezr** [comment]
With RC.x an error is thrown but it's not really helpful

```
VM764 browser_adapter.js:77 EXCEPTION: TypeError: Cannot read property 'query' of null
```
http://plnkr.co/edit/fkeQoc562NIEWJh2WwMd?p=preview

**Comment by ericmartinezr** [comment]
This is not really about missing imports. To be more exact is about injecting *undefined* items in the constructor, for a repro using custom classes. For a repro see the plnkr on this issue https://github.com/angular/angular/issues/8573

**Comment by pkozlowski-opensource** [comment]
@ericmartinezr I'm trying to reproduce this under non-plunker conditions (ng2 test suite) and it is super-hard since if you compile things with TS you are going to get a very descriptive error: `error TS2304: Cannot find name 'ElementRef'`.

So I'm starting to suspect that this is more of a TS + SystemJS thing. I mean: it should have been reported by SystemJS. 

I will try some more to reproduce this under non-plunker conditions but it would be interesting to check with you / anyone else if you've ever seen this error outside plunks / SystemJS?

**Comment by ericmartinezr** [comment]
@pkozlowski-opensource you're absolutely right, I can't reproduce it outside a plnkr, compilers and IDE complain. That being said there's clearly a regression on the error message as stated in the original message, previous beta.16 the error message was clear

```
Cannot resolve all parameters for 'App'(Renderer, ?)
```
Now it's that `query of null` thing.

Should we assume then that we all must be using IDE + compiler? In that case we won't see this error message and angular could avoid checking against it.

**Comment by rlegrand** [comment]
@pkozlowski-opensource 
@ericmartinezr 

Hi, 
The one I added in issue 8506 you just closed comes from a real case (outside of plunker): http://plnkr.co/edit/2GQwDiDAm3S0dGWEAIFD?p=preview

I just used plunker to share the problem, issue is exactly the same with tsc.

**Comment by pkozlowski-opensource** [comment]
> Should we assume then that we all must be using IDE + compiler? In that case we won't see this error message and angular could avoid checking against it.

Nope. It just that it is not as severe as was initially thinking. Anyway, I've managed to reproduce it by declaring dependency on an interface (which are undefined after TS transpiles). 

> That being said there's clearly a regression on the error message as stated in the original message, previous beta.16 the error message was clear

Yes, it clearly is and this is why we need to fix it. On it.

**Comment by rlegrand** [comment]
If you take my plunk and replace rc.1 by rc.2 in **config.js**, you will see that the error message has changed "Can't resolve all parameters for ManageDefinitions" but is still there.
Does it mean the issue comes from **system**? I don't find the answer in this issue.

**Comment by ericmartinezr** [comment]
@rlegrand you have a circular import ManageDefinitions imports MenuService and MenuService imports ManageDefinitions, that's causing your issue.

**Comment by rlegrand** [comment]
Ahhh ok! 
Thank you
