### ISSUE TITLE
ts to dart: === is converted to identical() call, breaking ngSwitch (and maybe other features)

### ISSUE THREAD

**Issue by cporte** [angular/angular#8246]
**Current behavior**
ng_switch.ts contains the following code:
`if (newWhen === this._switchValue)`
converted in ng_switch.dart to:
`if (identical(newWhen, this._switchValue))`

The meanings of the two lines of code are different. "===" in ts and js means "same type, and equal".
In dart, "identical" checks that "two references are to the same object".
so ngSwitch doesn't work as intended in dart.
It seems to be that same issue as #2458

**Comment by pkozlowski-opensource** [comment]
Obsolete.
