### ISSUE TITLE
[beta.16] async(inject( ... ))  Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

### ISSUE THREAD

**Issue by schippie** [angular/angular#8248]
**Steps to reproduce and a minimal demo of the problem**

Goto: http://plnkr.co/edit/JAybGNUO1YV8UnynNes7
Look in the console (dev tools) 

You will notice it will call the two console.log messages yet the tests still fail as they never seem finish the test. Which leads to a timeout error being thrown by jasmine. 

`Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.` 

**Current behavior**

It does not seem to call done() from within the async() function whenever their are no more actions taking place. Within the provided example, yet it does work for a simple Promise example

**Expected/desired behavior**

It should complete the `async()` function like it did within beta.15 whenever you returned the promise to `injectAsync(...)` and called `resolve/reject` within it.

**Comment by schippie** [comment]
I managed to figure it out. The problem was due to the fact that i was having another timeout run within the constructor of my Socket class. 

This should have been a setInterval but thats besides the point. I think zone.js / async()  should more clearly specify the running tasks that are still running upon the moment a task timesout. I now managed to figure it out by adding a console.log() line within the async-test.js (zone.js)

```javascript
AsyncTestZoneSpec.prototype.onScheduleTask = function (delegate, currentZone, targetZone, task) {
	            if (task.type == 'macroTask' && task.source == 'setInterval') {
	                this._failCallback('Cannot use setInterval from within an async zone test.');
	                return;
	            }
				console.log(task);
	            return delegate.scheduleTask(targetZone, task);
	        };
```

**Comment by KillerCodeMonkey** [comment]
@schippie 
I have a component that provides a function. This function sends a http-requests and shows a message after completion. This message gets hidden after 3 seconds (setTimeout).

Now i get this error, because this setTimeout is not catched. 

I tried to load and inject the "Done" function in my test, but i get "Done" is not exported by angular2/testing.

How do you solved your problem?

i think nested async code is not that unusual.

**Comment by schippie** [comment]
@KillerCodeMonkey The way i fixed it was by removing the second setTimeout. That would also be my advice right now to you. If you have any places in your code that trigger multiple timeouts you either have to:

- Remove the other timeouts / mock them out of the scope of that unit test (what I currently did I moved the setInterval / timeout call into the socket backend. This socket backend always gets mocked in my tests as i never communicate directly with a web socket while running tests) .
- Make the duration of the timeouts configurable like I do in my socket.spec.ts as well:

```javascript
let socketOptions: SocketOptions = {
	url: 'wss://test.com',
	replyAddressKey: 'key',
	responseAddressKey: 'key',
	timeoutDuration: 500
}
```

I have tests for instance that should throw an error if no reply is pushed through the observable (so the timeout https://github.com/ReactiveX/rxjs/blob/master/src/operator/timeout.ts) throws an error after x amount of ms's
In that case you can adjust the it timeout for every tests like so:

```javascript
it('should timeout after 10000', () => { .... }, 10000)
```

**Comment by ersandeepranjit** [comment]
@KillerCodeMonkey  did you solve your issue ?

**Comment by KillerCodeMonkey** [comment]
nope i gave it up to test this angular 2 app ... i was playing around with newer RCs, but did not tried this to test.


But it is not working in the beta releases. Maybe you can check if it is working now in RC4?

**Comment by ersandeepranjit** [comment]
@KillerCodeMonkey  I Solved it by adding   `jasmine.DEFAULT_TIMEOUT_INTERVAL = 6000;`  in Karma test shim ,  you can try it out too and I am using RC 4
