### ISSUE TITLE
Router URL cannot be accessed directly if parameter contains "." (dot) in it's value

### ISSUE THREAD

**Issue by GitAngel** [angular/angular#8249]
**Description**
As soon as you try to access URL containing `.` symbol the page cannot be displayed.

**Steps to reproduce and a minimal demo of the problem**
1. Create router accepting parameter, e.g.:
`{ path: '/data/:date', component: DataDetails, name: 'DataDetails' }`
2. Try accessing URL from your browser: `http://localhost/data/2016.05`

**Current behavior**
An error is returned that page cannot be displayed (`Error 404`)

**Expected/desired behavior**
Corresponding component is properly displayed.

**Other information**
1. If you access this URL programmatically, e.g. using: 
`this._router.navigateByUrl('/data/2016.05');`
it works fine and proper component is shown.
2. As soon as you remove `.` from the URL, e.g.: `http://localhost/data/2016-05` it works fine as well.
Looks like the problem is cause by `.` symbol.

**Comment by MarkusPint** [comment]
Still an issue with @angular/router@3.0.0-beta.2

**Comment by Perezmarc** [comment]
Did you solve this?

**Comment by schippie** [comment]
Reporting here that I'm experiencing this problem as well when we redirect to a url in which the users email is contained. I can't use the users email in this case as it contains a dot.

**Comment by nbuso** [comment]
Same problem here

**Comment by DzmitryShylovich** [comment]
Cannot reproduce it using express server. Looks like the issue is related to webpack dev server treated urls with dots as file names https://github.com/webpack/webpack-dev-server/issues/454

**Comment by vsavkin** [comment]
I'm sorry but we can't reproduce the problem following the instructions you provided. 

If the problem still exists please open a new issue with a plunkr reproducing the problem.

**Comment by gyuho** [comment]
@vsavkin I am still having this issue with

```
angular-cli: 1.0.0-beta.15

@angular/common: 2.0.0
@angular/compiler: 2.0.0
@angular/core: 2.0.0
@angular/forms: 2.0.0
@angular/http": 2.0.0
@angular/platform-browser: 2.0.0
@angular/platform-browser-dynamic: 2.0.0
@angular/router: 3.0.0
```

What version of angular should I try to see if it is resolved?

Thanks!

**Comment by gyuho** [comment]
Ok this is probably fixed by newer versions. I tried this and works

```
  "dependencies": {
    "@angular/common": "~2.1.0",
    "@angular/compiler": "~2.1.0",
    "@angular/core": "~2.1.0",
    "@angular/forms": "~2.1.0",
    "@angular/http": "~2.1.0",
    "@angular/platform-browser": "~2.1.0",
    "@angular/platform-browser-dynamic": "~2.1.0",
    "@angular/router": "~3.1.0",
    "core-js": "^2.4.1",
    "rxjs": "5.0.0-beta.12",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.6.23"
  },
  "devDependencies": {
    "@types/jasmine": "^2.2.30",
    "@types/node": "^6.0.42",
    "angular-cli": "1.0.0-beta.19-3",
    "codelyzer": "1.0.0-beta.1",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "4.0.9",
    "ts-node": "1.2.1",
    "tslint": "3.13.0",
    "typescript": "~2.0.3",
    "webdriver-manager": "10.2.5"
  }
```

Thanks!

**Comment by donwilli** [comment]
Hey,

i have still this Problem in Version 4.0.3

`"dependencies": {
    "@angular/common": "^4.0.3",
    "@angular/compiler": "^4.0.3",
    "@angular/core": "^4.0.3",
    "@angular/forms": "^4.0.3",
    "@angular/http": "^4.0.3",
    "@angular/platform-browser": "^4.0.3",
    "@angular/platform-browser-dynamic": "^4.0.3",
    "@angular/router": "^4.0.3",
    "angular-in-memory-web-api": "^0.3.2",
    "core-js": "^2.4.1",
    "devextreme": "^16.2.7",
    "devextreme-angular": "^16.2.7",
    "rxjs": "5.0.1",
    "systemjs": "0.19.40",
    "zone.js": "^0.8.12"
  },
  "devDependencies": {
    "@types/jasmine": "2.5.36",
    "@types/node": "^6.0.78",
    "canonical-path": "0.0.2",
    "concurrently": "^3.2.0",
    "jasmine-core": "~2.4.1",
    "karma": "^1.7.0",
    "karma-chrome-launcher": "^2.1.1",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "lite-server": "^2.2.2",
    "lodash": "^4.16.4",
    "protractor": "~4.0.14",
    "rimraf": "^2.5.4",
    "tslint": "^3.15.1",
    "typescript": "~2.1.0"
  }`

**Comment by kuiperr005** [comment]
I had the same issue and the solution of @DzmitryShylovich worked for me.
