### ISSUE TITLE
Microsoft Edge renders a frame around <object> tag when used to load SVG's - in some cases

### ISSUE THREAD

**Issue by tawfiqin** [angular/angular#8250]
Hello
Microsoft Edge renders a frame around object tag when used to load SVG's (only when set the "data" attribute for object tag using binding.

please see the issue on this Plunker
https://plnkr.co/edit/GZ00PckDA3xt1cln40iH?p=preview

the object tag should not have this frame.

**Comment by zoechi** [comment]
Looks more like a browser issue.

add `<object *ngIf="data"` ...` as a workaround

Seems to be caused by setting `null` initially

**Comment by tawfiqin** [comment]
I also  reported the issue to Microsoft

**Comment by zoechi** [comment]
I tried it in Edge and it worked for me. I'll check again. Maybe I did something wrong.

**Comment by vicb** [comment]
if still an issue please re-open with a plunker based on 2.0.1
