### ISSUE TITLE
[beta.16 regression/testing] Scheduler / tick not working for code with multiple async-events

### ISSUE THREAD

**Issue by choeller** [angular/angular#8251]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here, see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. 

This is pretty hard to describe, but I'm basically testing the typical Typeahead-Example everybody demonstrates. So this is my controller-code:

``` ts
  searchTerm = new Control();
  ngOnInit() {
      this.searchTerm.valueChanges
        .do((val)=> console.log("Before debounce", val))
        .debounceTime(200)
        .do((val)=> console.log("After Debounce", val))
        .switchMap((term :string) => { return this.taskService.findTasks({'q': term})})
        .subscribe(() => {
        });
  }
```

and this is my test: 

``` ts
  iit('should execute a Typeahead-Search', fakeAsync(() => {
    fixture.detectChanges();
    let taskList = fixture.componentInstance,
      element = fixture.nativeElement;

    var spy : Spy = spyOn(taskService, 'findTasks').and.callThrough();
    let input = element.querySelector('#searchField');
    taskList.searchTerm.updateValue("Term");
    tick(500);
    console.log("Input Value: ", input.value); // prints 'Input Value: ', 'Term' correctly
    expect(taskService.findTasks).toHaveBeenCalledWith({'q': 'Term'});
  }));
```

this worked perfectly fine in beta.15 but fails with beta.16 / zone0.6.12. The error message is:

`Error: 1 timer(s) still in the queue.`

After some debugging I think the problematic line is this one:

https://github.com/angular/zone.js/blob/master/lib/zone-spec/fake-async-test.ts#L23

As for every scheduled task the member-variable `_currentTime` is increased by the passed delay. In my example the `scheduleFunction` is executed twice:

First time for the `valueChanges` with delay (0) and second time for the `debounceTime` with delay(200). As in the mean-time there was also a call to `tick(500)` the endTime sums up to 700 which will noch be reached in the test. Changing the mentioned line to:

``` ts
    var endTime = delay;
```

lets my test work properly. But I'm not sure if this maybe leads to other problems... 

**Current behavior**

multiple async functions  (valueChanges + debounceTime) break test because of buggy scheduler behaviour

**Expected/desired behavior**

multiple async functions should not break the scheduler

**Other information**

**Comment by choeller** [comment]
I was able to reproduce the error way easier. The problem is when an async-event triggers another async-event (in case of the typeahead it's the async "valueChanges"-execution that triggers the debounceTime). The following test also fails with: `Error: 1 timer(s) still in the queue.`

```ts
  it('tick should simulate a given time period', fakeAsync(() => {
    let flag = false;
    setTimeout(() => {
      Observable.timer(500).subscribe(() => flag = true);
    });
    tick(800);
    expect(flag).toBeTruthy();
  }));
```
In `fake-async-test.js` the calculated endTime is 1300:

```
Scheduler.prototype.tick = function (millis) {
	if (millis === void 0) { millis = 0; }
		this._currentTime += millis;
		while (this._schedulerQueue.length > 0) {
			var current = this._schedulerQueue[0];
			console.log("_currentTime", this._currentTime); // PRINTS 800 in the last execution
			console.log("endTime", current.endTime); // PRINTS 1300 in the last execution
			if (this._currentTime < current.endTime) {
				// Done processing the queue since it's sorted by endTime.
				break;
				}
				else {
					// Time to run scheduled function. Remove it from the head of queue.
					var current_1 = this._schedulerQueue.shift();
					var retval = current_1.func.apply(global, current_1.args);
					if (!retval) {
							// Uncaught exception in the current scheduled function. Stop processing the queue.
							break;
					}
				}
		}
};
```

**Comment by tycho01** [comment]
I'd experienced many errors like `Error: 1 timer(s) still in the queue.` as well (before beta 16); my hacky workaround had been to add `tick(1000);` statements.

**Comment by bczengel** [comment]
ticking twice works for me    

    tick(); //Needed to get around issue: https://github.com/angular/angular/issues/8251
    tick(delay);`

**Comment by zijianhuang** [comment]
I could confirm what reported by the OP. And even those test cases in the tutorials of Angular 2 official Website are not working for async functions: with async, injectAsync.

**Comment by vicb** [comment]
is this still an issue with 2.0.0

**Comment by jacobrabjohns** [comment]
Ticking twice is not working for me, and can confirm this is still an issue as of 2.0.1. Testing an observable with debounce, seemingly impossible with the current state of play.

**Comment by DmitryEfimenko** [comment]
This cannot be closed. Still experiencing the issue

**Comment by vicb** [comment]
Please add a repro based on 2.0.1

**Comment by DmitryEfimenko** [comment]
@vicb: See the previous comment by @choeller. He has an example of failing test.

**Comment by pdavin** [comment]
Started experiencing this issue today in an application test after upgrading @angular/material from 2.0.0-beta.1 to 2.0.0-beta.2. 
Worked around with tick(1000) following example from https://github.com/axelhodler/blabverific/commit/4edc57928d4ac4e841ea26bb27d19e9925877286

**Comment by royling** [comment]
this is still happening in v4.

**Comment by nethulap** [comment]
for a quick fix for this issue call <code>discardPeriodicTasks()</code> at the end.

**Comment by vespertilian** [comment]
@nethulap 

Your discardPeriodicTasks() tip helped me. I was dispatching KeyUp events, which would work on the first tick(500) but give the "Error: 1 periodic timers(s) still in queue" the second time I tried to dispatch same event.

Code excerpt
```ts
    @HostListener('keyup') private onKeyUp(): void {
        console.log('keyup');
        this.activityStream.next(true);
    }

    this.activityStream
        .do(() => this.setActive()) // this will change is active class
        .debounceTime(500)
        .subscribe(() => this.setIdle());
```

Test excerpt 
```ts
    it('should remove the is idle class if a user starts typing again', fakeAsync(() => {
        const {input, fixture} = setup();

        input.dispatchEvent(new Event('keyup'));
        tick(500);
        fixture.detectChanges();
        expect(input.classList.contains('is-idle')).toBe(true);
        expect(input.classList.contains('has-idled')).toBe(true);
        input.dispatchEvent(new Event('keyup'));
        
       discardPeriodicTasks(); **<- YOU NEED THIS**

        tick(100);
        fixture.detectChanges();

        // this is checking that is-idle will be false if we keyup 
        // without hitting another 500ms
        expect(input.classList.contains('is-idle')).toBe(false);
        expect(input.classList.contains('has-idled')).toBe(true);
    }));

```

**Comment by nethulap** [comment]
@vespertilian 
I am glad this helped you to fix the issue. 👍

**Comment by cexbrayat** [comment]
@vikerman I think this issue should still be opened: a simple test involving a `delay()` still fail since ng `2.0.0-beta.16`...

Let's take a method returning an observable with a delay:

```typescript
list(): Observable<Array<RaceModel>> {
  return of([ { name: 'Lyon' } ]).pipe(delay(500));
}
```

The following simple test is still failing with ng `5.2.x`, CLI `1.6.5`, RxJS `5.5.x`:

```typescript
it('should list races', fakeAsync(() => {
  let fetchedRaces: Array<RaceModel> = [];
  const observable = service.list();
  observable.subscribe((races: Array<RaceModel>) => fetchedRaces = races);

  tick(200);

  expect(fetchedRaces.length).toBe(0, 'The service should return the races after a 500ms delay');

  tick(400);

  expect(fetchedRaces.length).toBe(5, 'The service should return a race after 500ms');
}));
```

It also fails if we tick 600ms directly:

```typescript
it('should list races', fakeAsync(() => {
  let fetchedRaces: Array<RaceModel> = [];
  const observable = service.list();
  observable.subscribe((races: Array<RaceModel>) => fetchedRaces = races);

  tick(600);

  expect(fetchedRaces.length).toBe(5, 'The service should return a race after 500ms');
}));
```
