### ISSUE TITLE
[Beta.16 regression] ng.core.ApplicationRef and ng.core.Compiler no longer exist

### ISSUE THREAD

**Issue by stringham** [angular/angular#8254]
As of beta.16 ng.core.ApplicationRef and ng.core.Compiler no longer exist, and therefore can't be injected.

With this code:

```javascript
var Component1 = function Component(compiler, avm) {
  this.hasCompiler = !!compiler;
  this.hasAVM = !!avm;
};
Component1 = ng.core
    .Component({
        selector:"cmp1",
        template:"<div>has ng.core.Compiler: {{hasCompiler}}</div><div>has ng.core.AppViewManager: {{hasAVM}}</div>"
    })
    .Class({
        constructor:[
            ng.core.Compiler,
            ng.core.AppViewManager,
            Component1
        ]
    });

var AppComponent = ng.core
    .Component({
        selector:'test-app',
        template:`
            <cmp1></cmp1>
        `,
        directives:[
            Component1,
        ]
    })
    .Class({
        constructor:[
            function() {
                window.app = this;
            }
        ]
    });

document.addEventListener('DOMContentLoaded', function() {
    ng.platform.browser.bootstrap(AppComponent, []);
});
```

the output is:

```
has ng.core.Compiler: false
has ng.core.AppViewManager: false
has ng.core.ElementRef: false
```

with beta.15 we can successfully inject ng.core.*

beta.16 plnkr: http://plnkr.co/edit/hesqS5Iv9o3HfTOnslBl?p=preview

beta.15 plnkr: http://plnkr.co/edit/WwougkLpagwQxOj0eygg?p=preview

There was no mention of this in the breaking changes in the CHANGELOG.

**Comment by zoechi** [comment]
https://github.com/angular/angular/pull/8239/files

> `Compiler` is renamed to `ComponentResolver`,

>  `AppViewManager` is renamed into `ViewUtils` and is a mere private utility service. ([efbd446](https://github.com/angular/angular/commit/efbd446))

`ApplicationRef` seems to still exist
