### ISSUE TITLE
angular2-polyfills causes JS errors when used in conjunction with a new relic JS snippet

### ISSUE THREAD

**Issue by zachcarroll** [angular/angular#8255]
when running angular1 and angular2 in parallel, along with a new relic monitoring JS snippet, there is a namespace issue with xhr. this issue causes xhr to be null when running the xhr.onload function in angular1 source.  This causes JS errors on application load, route changes, and all api calls.

**Comment by pkozlowski-opensource** [comment]
`angular2-polyfills` is gone and we don't have reproduce scenario. Closing as non-actionable. Happy to re-open if / when you've got a reproduce scenario following our submission guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue
