### ISSUE TITLE
[beta.16] Dart Dev Guide pipes example throws: no constructor 'AsyncPipe()'

### ISSUE THREAD

**Issue by chalin** [angular/angular#8258]
The Angular.io [Developer Guide Pipes example in TS](https://angular.io/docs/ts/latest/guide/pipes.html) runs fine in both beta.15 and beta.16 (after some minor edits).

The Dart version of the **Pipes example** has a subset of the TS functionality and it **ran fine under beta.15**; here are links to the beta.15 Dart Pipes example

- [source][1]
- [live demo][]

After making minor updates to migrate the Dart example sources **beta.16**, it no longer runs due to:

```
EXCEPTION: Error in asset:pipe_examples/lib/hero_async_message_component.dart class HeroAsyncMessageComponent - inline template:null:null
ORIGINAL EXCEPTION: No constructor 'AsyncPipe' with matching arguments declared in class 'AsyncPipe'.

NoSuchMethodError: incorrect number of arguments passed to method named 'AsyncPipe'
Receiver: Type: class 'AsyncPipe'
Tried calling: AsyncPipe(...)
Found: AsyncPipe(ChangeDetectorRef)
ORIGINAL STACKTRACE:
#0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:188)
#1      _View_HeroAsyncMessageComponent0.createInternal (package:pipe_examples/hero_async_message_component.ngfactory.dart:33:47)
#2      AppView.create (package:angular2/src/core/linker/view.dart:139:21)
#3      _View_AppComponent0.createInternal (package:pipe_examples/app_component.ngfactory.dart:173:16)
#4      AppView.create (package:angular2/src/core/linker/view.dart:139:21)
```

Trace line `#1` above refers to `hero_async_message_component.ngfactory.dart:33:47`:
```dart
  import7.AppElement createInternal(String rootSelector) {
    final parentRenderNode = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'',this.debug(0,0,0));
    this._expr_0 = import9.uninitialized;
    this.debug(null,null,null);
    this._pipe_async_0 = new import4.AsyncPipe(); // LINE 33
    this.init([],[this._text_0],[],[]);
    return null;
  }
```

This is generated from the following [component code](https://github.com/angular/angular.io/blob/master/public/docs/_examples/pipes/dart/lib/hero_async_message_component.dart):
```dart
import 'dart:async';

import 'package:angular2/angular2.dart';

@Component(
    selector: 'hero-message', template: 'Message: {{delayedMessage | async}}')
class HeroAsyncMessageComponent {
  Future<String> delayedMessage =
      new Future.delayed(new Duration(milliseconds: 500), () {
    return 'You are my Hero!';
  });
}
```

Indeed, the `AsyncPipe` constructor expects a `ChangeDetectorRef ` (in both TS and Dart; see [here](https://github.com/angular/angular/blob/master/modules/angular2/src/common/pipes/async_pipe.ts#L64)).

**Steps to reproduce and a minimal demo of the problem**

The live demo site (http://angular-examples.github.io/pipes/) currently runs beta.15, but could be updated to run the (faulty) beta.16. Otherwise, to reproduce, pub serve the [Dart pipes beta.16 example][2] into Dartium.

 [1]: https://github.com/angular/angular.io/tree/master/public/docs/_examples/pipes/dart
 [2]: https://github.com/angular/angular.io/pull/1192
 [live demo]: http://angular-examples.github.io/pipes/

**Comment by zoechi** [comment]
@chalin did you take this change from beta.16 into account?

> BREAKING CHANGES
> 
pipes now take a variable number of arguments, and not an array that contains all arguments.

**Comment by chalin** [comment]
@zoechi : thanks for pointing that out, but `async` is a pipe provided as part of ng2 (cf. [API](https://angular.io/docs/ts/latest/api/common/AsyncPipe-class.html)). My guess is that something changed in the code generation.

**Comment by luisvt** [comment]
error still persist on `beta.17`, I'm getting this error:

```
EXCEPTION: Error in asset:pipe_examples/lib/hero_async_message_component.dart class HeroAsyncMessageComponent - inline template:null:null
    (anonymous function)	
  ORIGINAL EXCEPTION: No constructor 'AsyncPipe' with matching arguments declared in class 'AsyncPipe'.

NoSuchMethodError: incorrect number of arguments passed to method named 'AsyncPipe'
Receiver: Type: class 'AsyncPipe'
Tried calling: AsyncPipe(...)
Found: AsyncPipe(ChangeDetectorRef)
```

**Comment by kwalrath** [comment]
@mhevery could you please take a look?

**Comment by mhevery** [comment]
@tbosch can you have a look?

**Comment by chalin** [comment]
Fixed in beta.18.
