### ISSUE TITLE
ng-content as plain html or text / don't evaluate during projection

### ISSUE THREAD

**Issue by alindsay55661** [angular/angular#8260]
It would be great if we could project the content of a component as plain html or text, rather than evaluating it. The main use case here is of course components that render code examples. Right now there is a great deal of black magic required to implement components that accept code as content. 

```html
<!-- <code-block> component template -->
<code>
  <ng-content></ng-content>
</code>
```

```html
<!-- usage example -->
<code-block>
  <p>{{name}}</p>
</code-block>
```

I would like the above to output this raw, unevaluated html:

```html
<code-block>
  <code>
    <p>{{name}}</p>
  </code>
</code-block>
```

**Comment by CaptainCodeman** [comment]
You can use the `ngNonBindable` directive to stop the expression being evaluated.

**Comment by alindsay55661** [comment]
Based on the docs I could find this appears to be limited to interpolation. What I need is something at the content projection level, something that applies to the entire component's content. Also, it should prevent any processing including things like `*ngIf`, `*ngFor`, etc. Here is a more complete example:

```html
<!-- <code-block> component template -->
<code>
  <ng-content></ng-content>
</code>
```

```html
<!-- usage example -->
<code-block>
  <ul *ngIf="names">
    <li *ngFor="#name of names" (click)="showDetail(name)">{{name}}</li>
  </ul>
</code-block>
```

I would like the above to output this raw, unevaluated html:

```html
<code-block>
  <code>
    <ul *ngIf="names">
      <li *ngFor="#name of names" (click)="showDetail(name)">{{name}}</li>
    </ul>
  </code>
</code-block>
```

**Comment by CaptainCodeman** [comment]
I doubt you want html, you probably want html to appear on the screen in which case you should be using <pre> or <code>

**Comment by alindsay55661** [comment]
> I doubt you want html, you probably want html to appear on the screen in which case you should be using

> or 

What is this exactly?

**Comment by zoechi** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre

**Comment by pkozlowski-opensource** [comment]
@CaptainCodeman is right - if you want to just display HTML without browser / angular processing it you should quote HTML. Closing as this is not really Angular specific.

Thnx @CaptainCodeman and @zoechi for helping out guys, much appreciated!

**Comment by 9KenM** [comment]
@pkozlowski-opensource Can you show an example? I'm trying to solve the same problem.
