### ISSUE TITLE
'APP_BASE_HREF' Not Included in angular2/router

### ISSUE THREAD

**Issue by phillipcurl** [angular/angular#8268]
On a fresh install of angular2 2.0.0-beta.15, I'm getting the following error: 

"node_modules/angular2/router" has no exported member 'APP_BASE_HREF'.

My import statement is: 

import {ROUTER_PROVIDERS, APP_BASE_HREF} from 'angular2/router';

I'm running Node v5.4.1 and npm 3.3.12 on OSX 10.11 Beta (15A278b). I used the exact same import on a separate project a few days ago, so I'm wondering if the latest update may have changed this. I'm happy to provide additional details if necessary. Thanks!

**Comment by CaptainCodeman** [comment]
Are you sure you don't have beta-16 instead? APP_BASE_HREF was just moved which would explain that error.

**Comment by ericmartinezr** [comment]
What Captain said, you can see the changelog as well https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes (which was fixed)

**Comment by CaptainCodeman** [comment]
FYI: If your npm ref is to `"2.0.0-beta.15"` then you would get beta-15 but if you have `"^2.0.0-beta.15"`` (note the caret prefix) it may give you the higher version.

https://docs.npmjs.com/misc/semver

**Comment by phillipcurl** [comment]
It being moved was my first suspicion as well, but I'm on beta.15 right now. I didn't realize that .16 had released, so I'll update to that now and let you know if that resolves it. Thanks for reaching out, @ericmartinezr @CaptainCodeman

**Comment by phillipcurl** [comment]
That was exactly it, @CaptainCodeman. My suspicion was that the API had just changed, but I should have caught the fact that I was using the npm caret declaration earlier. Everything is running smoothly now. Thanks again, @ericmartinezr and @CaptainCodeman for the quick response!

**Comment by RichardHwang886** [comment]
try this,
import {APP_BASE_HREF} from 'angular2/platform/common';

**Comment by shaffi** [comment]
@RichardHwang886  it worked. thanks

**Comment by RichardHwang886** [comment]
if you use rc , you should try this:
import { APP_BASE_HREF } from '@angular/common';
