### ISSUE TITLE
Impossible (?) to inject default AppDocument from DI in Dart

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#827]
As of today a default app document is registered using an `OpaqueToken` in the application.js like so:

```javascript
export var appDocumentToken = new OpaqueToken('AppDocument');
```

To have it injected in another class I would then write:

```javascript
import {appDocumentToken} from 'angular2/src/core/application';

export class Title {
  _appDocument;
  constructor(@Inject(appDocumentToken) appDocument) {
    this._appDocument = appDocument;
  }
}
```

This works perfectly fine in JS but fails in Dart (compilation time) with:
>   Internal error: 'package:angular2/src/services/title.dart': error: line 7 pos 16: expression is not a valid compile-time constant
   Title(@Inject(appDocumentToken) appDocument) {

I'm not sure if this is a transpilation problem to Dart or just a limitation that we can't overcome. In such a case we should probably change how a document is registered (for example, by introducing a new `Document` type and using it as a token in DI).

This blocks #749

**Comment by rkirov** [comment]
Dart requires all annotations to be `const`. Const in dart is not like `const` in js [1]. A `const` custom object needs all its fields to be `const`.

What needs to be done is:
* OpaqueToken needs to be made to transpile to `const` object with dart using the @Const transpiler annotation (see [2]). AFAIK, dart does not treat string interpolation as compile-time constant, so it needs to be changed to string addition in the initializer list. 
*  `export var appDocumentToken = new OpaqueToken('AppDocument');` should become `export const appDocumentToken = const OpaqueToken('AppDocument');` Again not sure if the transpiler can output that.

So yes, this is not a fundamental limitation, but might need some traspiler work to make it happen.


[1] http://news.dartlang.org/2012/06/const-static-final-oh-my.html 
[2] https://github.com/angular/angular/blob/master/modules/angular2/src/di/annotations.js#L15

**Comment by pkozlowski-opensource** [comment]
@rkirov thnx for the info. I will try to change the `OpaqueToken` to use the `@CONST()` annotation and report back here if I hit any pbs.

**Comment by pkozlowski-opensource** [comment]
So, with recent changes to the DOM facade this is no longer relevant. The original issue of using annotations from Dart still exists but with the migration to TypeScript I don't think it makes much sense to keep this issue open.

@rkirov if I recall properly our conversation at ng-conf you were planning to open a separate issue for Dart transpiler. But it moved to a separate repo, no?

Anyway, I don't see any point in keeping this issue open in the current form. Closing.
