### ISSUE TITLE
Inherit of @Input() annotations only work if the extending component has no @Input() annoation

### ISSUE THREAD

**Issue by kmcs** [angular/angular#8272]
1) Try the example code:
http://plnkr.co/edit/qFMOlE6qK9f9eSfQP2xU?p=preview
You can see the property placeholder of NumberFieldComponent is not inherited.

2) Comment the line 18 out of app/app.component.ts
Then you can see also placeholder is inherited.

I think it should inherit always all properties of the extended class.

**Comment by zoechi** [comment]
looks like a dup of #7191

**Comment by IgorMinar** [comment]
dupe. please subscribe to #11606
