### ISSUE TITLE
Breaking change attr.styleClass override ngClass in beta16

### ISSUE THREAD

**Issue by cagataycivici** [angular/angular#8275]
There is a breaking change with attr.styleClass and ngClass on the same element.

**Steps to reproduce and a minimal demo of the problem**

`<fieldset [ngClass]="{'ui-fieldset: true, 'ui-fieldset-toggleable': toggleable}" [attr.class]="styleClass">
`

**Current behavior**
Fieldset does not get any style class.

**Expected/desired behavior**
As in beta15 or before, it has ui-fieldset by default and ui-fieldset-toggleable if toggleable is on, also if there is a styleClass property, it should be appended to the overall evaluation. Not [attr.styleClass] overrides everything.

**Comment by zoechi** [comment]
[Plunker repo](https://plnkr.co/edit/ZOV2Zo?p=preview)

**Comment by pkozlowski-opensource** [comment]
@cagataycivici I don't think you should be binding to `[attr.class]` as Angular 2 is all about _property_ bindings. As such you should be binding to the `className` _property_ (it is also aliased as `[class]` ), so: `<fieldset [ngClass]="{'ui-fieldset: true, 'ui-fieldset-toggleable': toggleable}" [class]="styleClass">`

This works as expected: https://plnkr.co/edit/2PNlTRVVCudRWOyL3qi5?p=preview and we've got a test to prove it: https://github.com/angular/angular/blob/c209836fd0c7f831c42efff45c6fe73a624d9481/modules/angular2/test/common/directives/ng_class_spec.ts#L460

So, while I understand it "worked" before beta.16 I would say that it was "by chance" and I'm not sure we want to support it in the long run. In any case you've got a proper solution here that works.

**Comment by cagataycivici** [comment]
I'll buy that, thank you :) Do you also suggest the same for style e.g.

[style]="userStyle" instead of [attr.style]="userStyle"?

**Comment by pkozlowski-opensource** [comment]
> Do you also suggest the same for style

I would argue that one should bind to properties if they exist. For styles I don't think that all browsers let you set the `style` property so you should probably use `NgStyle` or `[style.foo]="conditionalExp"` binding.

**Comment by cagataycivici** [comment]
Thank you!
