### ISSUE TITLE
Beta.16 - [ngClass] and [attr.class] cannot coexist

### ISSUE THREAD

**Issue by vmateixeira** [angular/angular#8278]
I noticed that `[attr.class]` is now overriding `[ngClass]`, a behavior different from the one on Beta.15 version, where both could exist. As I didn't notice any information regarding this change in https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes I'm reporting this as an Issue.

Here's a plunker that shows the reported current behavior:
http://plnkr.co/edit/vJdPAvkBdtxPJsinR2Sf

Thanks!

**Comment by pkozlowski-opensource** [comment]
See #8275
