### ISSUE TITLE
[beta.16] Using exclamation in ngIf (when using null propagation operator)

### ISSUE THREAD

**Issue by eommund** [angular/angular#8281]
Use of exclamation in an `ngIf` does not work when using null propagation operator. It worked in beta-15, not in beta-16.

See plunker for demo:
http://plnkr.co/edit/2TGZ2XVESVQQJ1IN39AA?p=preview

(change to beta-15 to see difference)

Short version:
```
    <div *ngIf="!myData?.myBoolean">
      <h2>With exclamation</h2>      <---- does not show
    </div>
    <div *ngIf="myData?.myBoolean === false">
      <h2>With === false</h2>        <---- shows as expected
    </div>
```

I could not find anything about this in the changelog - is this as designed?

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/issues/8235

**Comment by pkozlowski-opensource** [comment]
It is a bug already reported in #8235, closing as a duplicate. Thnx @ericmartinezr
