### ISSUE TITLE
decimalPipe : incorrect behaviour in some cases

### ISSUE THREAD

**Issue by phiphou** [angular/angular#8283]
Currently, when using `decimalPipe`, we got an incorrect behaviour in this case : 

When the value is negative and smaller than `-0.25`, if we use the decimalPipe with format syntax `number:'1.0-0'` (simple rounding with no decimals), we got `-0` and not the correct `0`.

Here is a plunker that reproduce the bug :http://plnkr.co/edit/bURMjI

Do you agree that it's not the expected behaviour ? 

Not working on BETA 17.

**Comment by michalstepien** [comment]
Please look at discussion:
http://stackoverflow.com/questions/7223359/are-0-and-0-the-same

**Comment by phiphou** [comment]
Sure, but here I'm talking about a formater, a textual  formater, for humans I mean, and for them, there's no -0 ...

**Comment by pkozlowski-opensource** [comment]
`-0` is sth that we ultimatelly get from the `Intl` API built into browsers. Just try `Intl.NumberFormat('en-US', {maximumFractionDigits: 0}).format(-0.3)` in your favorite browser:
* Chrome: `"-0"`
* Firefox: `"-0"`

I'm not saying that Chrome / Firefox does "good thing" but rather that:
* this is the logic currently implemented in browsers
* Angular decided to use `Intl` to do actual work

Given the above we've got 2 options:
* close it as "works as designed"
* re-consider usage of `Intl` which would be substantial change.

**Comment by DzmitryShylovich** [comment]
> re-consider usage of Intl which would be substantial change.

there're already a lot of issues about that.
I think we should close this one @pkozlowski-opensource

**Comment by phiphou** [comment]
I finaly agree with that ;) Let me close this issue ;)
