### ISSUE TITLE
When LocationStrategy is provided before ROUTER_PROVIDERS angular will ignore LocationStrategy definition

### ISSUE THREAD

**Issue by eyal453** [angular/angular#8285]
**Steps to reproduce and a minimal demo of the problem**

create an angular app with routing and in your bootstrap file provide the following

```
bootstrap(AppComponent,  [
    provide(LocationStrategy, { useClass: HashLocationStrategy }), //<-- this line comes first
    ROUTER_PROVIDERS,
    HTTP_PROVIDERS
]);
```

**Current behavior**
Seems like angular ignores the LocationStrategy provide statement and uses the default html5 one.
If I move the `provide(LocationStrategy,...)` line after the `ROUTER_PROVIDERS` one everything works fine.

**Expected/desired behavior**
I believe this should work regardless of custom providers order.

**Comment by zoechi** [comment]
That's by design. `LocationStrategy` is included in `ROUTER_PROVIDERS` (as `PathLocationStrategy`) if you want to override it with your custom `HasLocationStrategy`is has to come afterwards.
Order is significant if you want to override.
Please close this issue.

**Comment by eyal453** [comment]
Alright, thanks.

**Comment by roni-frantchi** [comment]
@zoechi even so, would it be possible to perhaps add some sort of sensible warning to the console log?
Letting you know that "a custom location strategy was overridden by a default one"..
Would have saved me a couple of hours of my day.

**Comment by zoechi** [comment]
@roni-frantchi Everything (almost ;-) is possible but if it's worth it is a different question (not my call anyway).

How should Angular know what you want to override by what. These are just types or variables referring types with no meaning to DI. This would need some special-casing of every type that is likely to be overridden by someone and that are quite a few.
Just my 2c (I'm not an Angular team member)

**Comment by roni-frantchi** [comment]
@zoechi true. Just thought that if one would provide a library with strategies that are intended to be used as defaults, perhaps you can assert that you do not override custom providers, or have some information spet out to the log, so one can keep track of what's been strategy was finally set.
Just a thought.

**Comment by zoechi** [comment]
@eyal453 If you really want this implemented then you should probably create a new issue. This one is closed and nobody will monitor it.
It might be worth to be documented more prominently. Once you understood how DI works this behavior will not be surprising in any way. If you want to see what is effectively provided, just inject a type and you see what you get like

```ts
bootstrap(AppComponent, [... providers ...).then(ref => console.log(ref.injector.get(LocationStrategy));
```
