### ISSUE TITLE
Cannot read property 'length' of undefined after updating to Beta16

### ISSUE THREAD

**Issue by guehmann** [angular/angular#8286]
Hello,

i got the following error after updating from beta15 to beta16:
EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in app/areas/hr/BookingList.html:16:0
ORIGINAL EXCEPTION: TypeError: Cannot read property 'length' of undefined
ORIGINAL STACKTRACE:
TypeError: Cannot read property 'length' of undefined
    at _flattenStyles (http://localhost:24413/dist/vendor.js:18643:32)
    at new DomRenderer (http://localhost:24413/dist/vendor.js:18408:25)
    at DomRootRenderer_.DomRootRenderer.renderComponent (http://localhost:24413/dist/vendor.js:18383:25)
    at DebugDomRootRenderer.renderComponent (http://localhost:24413/dist/vendor.js:20000:53)
    at new MdDialog (http://localhost:24413/dist/esuite.js:1382:40)
    at http://localhost:24413/dist/vendor.js:3489:52
    at ReflectiveInjector_._instantiate (http://localhost:24413/dist/vendor.js:2898:28)
    at ReflectiveInjector_._instantiateProvider (http://localhost:24413/dist/vendor.js:2833:26)
    at ReflectiveInjector_._new (http://localhost:24413/dist/vendor.js:2822:22)
    at ReflectiveInjectorDynamicStrategy.getObjByKeyId (http://localhost:24413/dist/vendor.js:2477:51)
ERROR CONTEXT:
[object Object]

This occurs when i use this directive, the directive is in a separate component:
<time-bookings [employee]="employee"></time-bookings>

import { Component, OnInit, ElementRef } from 'angular2/core';
import { Http, Response, HTTP_PROVIDERS } from 'angular2/http';
import { RouterLink } from 'angular2/router';
import { MATERIAL_DIRECTIVES, MATERIAL_PROVIDERS, MdDialog, MdDialogConfig, MdDialogBasic, MdDialogRef } from 'ng2-material/all';
import { appSettings } from './../../common/appSettings';

@Component({
    selector: 'time-bookings',
    templateUrl: 'app/areas/hr/TimeBookings.html',
    directives: [RouterLink, MATERIAL_DIRECTIVES],
    inputs: ['employee']
})
export class TimeBookings implements OnInit {
    data: Object;
.......

I use webpack to bundle the files.
Does anyone now where my problem is?

Thank in advance.
Jens

**Comment by ericmartinezr** [comment]
>Does anyone now where my problem is?

Right here
>Error in app/areas/hr/BookingList.html:16:0

**Comment by guehmann** [comment]
This is the line where the directive
<time-bookings [employee]="employee"></time-bookings>
is located in the file BookingList.ts

From this i want to use the code from TimeBookings. I cannot locate the problem in my TimeBookings.ts

**Comment by guehmann** [comment]
I tried a little bit the code and found out the error occurs on my directives when they have an input element in the component section, perhaps something about this? Something must have changed vom b15 to b16. If i go back to b15 everything works fine.
![capture1](https://cloud.githubusercontent.com/assets/8971747/14865868/1d8f8c02-0cc1-11e6-9f3a-dbf7b05cff0b.PNG)
![capture2](https://cloud.githubusercontent.com/assets/8971747/14865875/2174b9d2-0cc1-11e6-8dfa-eecd97d29b83.PNG)

**Comment by ericmartinezr** [comment]
@guehmann it's impossible to say. Can you share a repo of your project to take a look?

**Comment by guehmann** [comment]
@ericmartinezr How can I share it, please help me.

**Comment by ericmartinezr** [comment]
@guehmann [create a repository](https://help.github.com/articles/create-a-repo/) of your project in github, like we will be able to clone it. 

I would guess that the problem it is the version of material, probably not yet upgraded to b16.

**Comment by guehmann** [comment]
Thank you, I'll create it and let you now if it's done. But I know material is only build with beta 14, perhaps this is the error. Thanks again.

**Comment by guehmann** [comment]
@ericmartinezr Hi, here is the repo. https://github.com/guehmann/vSuite.git
It comes from Visual Studio
Thank you.

**Comment by ericmartinezr** [comment]
@guehmann it's impossible, the project is big and I can't make it run (I did run it, but I get thousands of errors). I don't have any version of VS so probably somebody that owns a copy of it can help you. 

My recommendation is : go back to b.15 and wait for a new release of ng2-material to be released that is compatible with beta 16.

See these two issues https://github.com/angular/angular/issues/8233 and https://github.com/justindujardin/ng2-material/issues/204. The error points to `flattenStyles` which doesn't seem to be part of ng2 core, so the problem must be on ng2-material.

I'm really sorry but I can't provide any more help than that.

**Comment by guehmann** [comment]
Thank you very much for your help. I'll do als you decribed. Will traf the issue you mentioned. Thanks Jens.

Estoy en camino.

Am 27.04.2016 um 23:46 schrieb Eric Martinez <notifications@github.com<mailto:notifications@github.com>>:


@guehmann<https://github.com/guehmann> it's impossible, the project is big and I can't make it run (I did run it, but I get thousands of errors). I don't have any version of VS so probably somebody that owns a copy of it can help you.

My recommendation is : go back to b.15 and wait for a new release of ng2-material to be released that is compatible with beta 16.

See these two issues #8233<https://github.com/angular/angular/issues/8233> and justindujardin/ng2-material#204<https://github.com/justindujardin/ng2-material/issues/204>. The error points to flattenStyles which doesn't seem to be part of ng2 core, so the problem must be on ng2-material.

I'm really sorry but I can't provide any more help than that.

-

**Comment by guehmann** [comment]
Thank you very much for your help. I will do it like you mentioned. Go back first to beta15 and read the issues you posted. Many thanks again.

Best Jens.
