### ISSUE TITLE
[beta.16] Inject self ReflectiveInjector

### ISSUE THREAD

**Issue by JulioC** [angular/angular#8288]
Before 2.0.0-beta.16 it was possible to get the inject `Injector` and use `resolveAndInstantiate` to instantiate dependencies, **even if there were no providers for them**. These dependencies would be injected with their own dependencies as needed, using the registered providers if available.

Working demo on Beta 15: http://plnkr.co/edit/GppluCy6VYH5NdgNdvdn?p=preview

In the example, `OtherDependency` is instantiated with `resolveAndInstantiate`, because it's not already provided. Its `Dependy` is already provided from the `App` component, so the same is used in this case.

With Beta 16, there `Injector` changed to `ReflectiveInjector`, but I can't inject it into `Service`. **I expect to be able to get the `ReflectiveInjector`** used to instantiate `Service`.

Some context: I use the created instances to create providers used on `DynamicComponentLoader.loadNextToLocation`. This approach is to dynamically load "sub apps" (components which can have their own self-contained dependencies, but also use app-wide providers).

**Comment by zoechi** [comment]
Have you tried to inject `Injector`. It might be the key for DI is still `Injector` (super class) and only the concrete implementation is `ReflectiveInjector'

**Comment by JulioC** [comment]
I tried to inject `Injector` and cast it to `ReflectiveInjector`, it does work, but when instantiating the component with DCL, a error is thrown: `TypeError: Cannot read property 'parentInjector' of undefined`.

I expanded the Plunker example with the DCL component loading, but it doesn't work as in my app: `Property 'resolveAndInstantiate' does not exist on type 'Injector'.`. Looks like the `Injector` injected is a `ElementInjector`.

http://plnkr.co/edit/NpZephc670N8adU7Q7ek?preview

**Comment by JulioC** [comment]
Running through the execution, I was able to identify where that the error `TypeError: Cannot read property 'parentInjector' of undefined` was referencing the `location` param in `DynamicComponentLoader.loadNextToLocation`, which was indeed undefined due to a mistake.

The issue with injector was solved by casting it:

```
@Injectable()
export class Service {
  constructor(injector: Injector) {
    let reflectiveInjector: ReflectiveInjector = <ReflectiveInjector>injector;
    console.log(injector, reflectiveInjector);
    let other = reflectiveInjector.resolveAndInstantiate(OtherDependency);
  }
}
```

Thanks!

**Comment by zoechi** [comment]
I didn't have a closer look yet myself but I assume the cast is not necessary. Only when you access static members or cteate a new instance with `new` it should be necessary to use the name of the concrete implementation `ReflwctiveInjector`

**Comment by JulioC** [comment]
Indeed, the cast is not necessary to run the function. Using `ReflectiveInjector` was for using IntelliSense completion.

**Comment by batchu** [comment]
Can anyone post a plunkr with this impl? The previous plunkr is for an earlier beta version of Angular. Looks like a lot has changed in the RC3. Thank you.

**Comment by zoechi** [comment]
I think you should not assume that the injected injector is actually a `ReflectiveInjector`. 

If you want an instance provided by the injected injector (or one of its parents) then use 

```
let other = injector.get(OtherDependency)`. 
```

If `OtherDependency` is not provided create a child injector. 

```
let resolvedProviders = ReflectiveInjector.resolve([OtherDependency]);
let child = ReflectiveInjector.fromResolvedProviders(resolvedProviders, this.injector);
let other = child.get(OtherDependency);
```

http://stackoverflow.com/a/37734641/217408 contains a Plunker.

I don't know if it is supposed to be used this way but it works for me.

**Comment by batchu** [comment]
@zoechi Any plunkr that shows how to create a new instance of a class on the fly?

**Comment by zoechi** [comment]
@batchu `new SomeClass()` ;-) Actually no idea what you mean. 

anyway GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)
