### ISSUE TITLE
static reflector does not unwrap directives array

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#8291]
```
@Component({directives: [FORM_DIRECTIVES]})
class Foo {}
```

fails to static reflect because the symbols inside the form directives are not unwrapped in the simplify method.

Workaround is to use spread operator:

```
@Component({directives: [...FORM_DIRECTIVES]})
class Foo {}
```

**Comment by gdi2290** [comment]
sort of maybe related https://github.com/angular/angular/pull/6049

**Comment by alexeagle** [comment]
turns out the workaround didn't work in the static reflector either, it just masked the real issue.
Tobias and I almost have the static reflector fixed, this will be included.

**Comment by vicb** [comment]
obsolete (`directives` has been removed)
