### ISSUE TITLE
@Query problematic behavior with TemplateRef

### ISSUE THREAD

**Issue by cagataycivici** [angular/angular#8292]
To begin with this behavior only happens in beta16, previous releases are working as expected. The commit seems to be related to;

https://github.com/angular/angular/commit/efbd446

@Query also finds the template elements of descendant elements, see plunker please;

http://plnkr.co/edit/sANW6mfss5EvPfWpXRde

I expect "1" to be logged on console, but "2" is logged. Template of child is also found.

But replacing template element with some random component e.g. otherchild, produces the expected result;

http://plnkr.co/edit/OzXjz8niAurzr6CZIoes

"1" is printed as container has only one otherchild.

So something is different with template elements causing confusion.

**Comment by Mrtcndkn** [comment]
I also have the same problem in beta 15 everything works perfectly fine but after upgrading my app to beta 16 it's not working anymore.

**Comment by mertsincan** [comment]
+1

**Comment by pkozlowski-opensource** [comment]
Isn't `Query` depreciated in favor of ContentChildren/ContentChild ?

**Comment by cagataycivici** [comment]
I don't know about deprecation however it also happens with @ContentChildren, here is plunker that replicates;

http://plnkr.co/edit/EI1Qbgppi3sLCeYBfTyl

 I assume this is a bug caused by the change to @ContentChilren() and @ViewChildren() in beta.16.

**Comment by zoechi** [comment]
It seems the `descendants: true/false` has no effect when the selector parameter is `TemplateRef`, works for normal component types though.

**Comment by cagataycivici** [comment]
Would have been great if this was fixed before the RC.

**Comment by pkozlowski-opensource** [comment]
Yeh, I agree this is a bit strange it works right now and it still happens in RC.1: http://plnkr.co/edit/EG1agILF5rUrkNM6Lj8a?p=preview

@tbosch for me it looks like a bug but maybe there are reasons for such behavior?

**Comment by mko** [comment]
This seems to still happen in RC4 (can't test in RC5 yet).

**Comment by vicb** [comment]
obsolete
