### ISSUE TITLE
Router: useAsDefault option doesn't work

### ISSUE THREAD

**Issue by yfain** [angular/angular#8294]
I have two routes configured as follows:
@RouteConfig([
    {path: '/',        component: HomeComponent, as: 'Home'},
    {path: '/product', component: ProductDetailComponent, as: 'ProductDetail', useAsDefault: true  }
])

Tried to set the ProductDetail route as default, but it still shows the Home route
Here's the plank for beta.16: http://plnkr.co/edit/HC9zaCES5IcELRBx67c9?p=preview

**Comment by brandonroberts** [comment]
The intent of `useAsDefault` is to provide a default in the case that you don't have a route defined with a path of `/`, whether it be on a top level route or a child route. Its also used for making linking to child routes easier without have to define the default route in the router link array. If you change the home path to `/home` it works as designed.

**Comment by yfain** [comment]
Thank you, Brandon!
