### ISSUE TITLE
Beta16 UMD bundle missing ng.platform.common export

### ISSUE THREAD

**Issue by starjumper30** [angular/angular#8299]
Looking at line 67 of angular2-all.umd.js bundle file pulled using npm, I see the platform export being defined and it only contains browser and common_dom. It does not contain the common sub-module. We are unable to run our app because we can't access the things that have been moved to angular2\platform\common.

**Comment by starjumper30** [comment]
tools\build\webpack\angular2-all.umd.js and tools\build\webpack\angular2-all-testing.umd.js were not updated to export the new common module under platform. These files need to be updated and the bundles regenerated.

**Comment by starjumper30** [comment]
Workaround for devs in the meantime:
You can manually edit the bundle files. At line 69 of angular2-all.umd.js, insert this line:
common: __webpack_require__(249),

Do the same for the other bundle files (line number might be a little different).

This got us past the error we were getting about the module, but app is still broken, so not promising anything.

**Comment by NathanWalker** [comment]
@starjumper30 the above PR should take care of it.

**Comment by pkozlowski-opensource** [comment]
This should be fixed with current packages.
