### ISSUE TITLE
[beta.16 test regression] using angular2-all-testing.umd.dev.js TypeError: AsyncTestZoneSpec is not a constructor

### ISSUE THREAD

**Issue by stringham** [angular/angular#8302]
In beta.16 when writing async jasmine tests using es5 I get `TypeError: AsyncTestZoneSpec is not a constructor`

works in beta.15 but not beta.16:

```javascript
ng.testing.describe('a test using injectAsync', function() {
  ng.testing.it('should run the test', ng.testing.injectAsync([], function(){
    return new Promise(function(resolve, reject) {
      expect(true).toBe(true);
      resolve();
    })
  }))
});
```

in beta.16 `injectAsync` has been deprecated, but this also fails:

```javascript
ng.testing.describe('a test using async inject', function() {
  ng.testing.it('should run test', ng.testing.async(ng.testing.inject([], function(){
    return new Promise(function(resolve, reject) {
      expect(true).toBe(true);
      resolve();
    })
  })))
});
```

a plnkr: http://plnkr.co/edit/L6orkkRAKVDzHC1gqeEQ?p=preview

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/issues/8232

**Comment by stringham** [comment]
That's very helpful. Thanks @ericmartinezr.

Should this issue stay open until these files are distributed by Angular, or added to the bundles?

**Comment by ericmartinezr** [comment]
@stringham for sure, this will hit to all those users using the bundles and specially the UMD ones

**Comment by robwormald** [comment]
cc @juliemr - best to build these into the testing bundle?

**Comment by juliemr** [comment]
Is base zone.js included? If so, yeah, these should be.

**Comment by pkozlowski-opensource** [comment]
zone.js is part of angular-polyfills but I don't think it is part of the umd / systemjs bundles (and probably shouldn't be as it would break format of testing boundles). What we could do instead is to create something like angular-testing-polyfills.

**Comment by pkozlowski-opensource** [comment]
Closing as this seems to be a question about a testing setup. We can't pre-append zones to the testing bundle as it wouldn't be umd any more.
