### ISSUE TITLE
[beta.16 test regression] Error: Cannot resolve all parameters for 'ElementRef'(?).

### ISSUE THREAD

**Issue by stringham** [angular/angular#8303]
I am testing a component that injects a directive found on a parent component. Since I am testing this component in isolation I need to add the directive to the `beforeEachProviders`. The directive I'm injecting injects `ng.core.ElementRef`, and if I don't add `ng.core.ElementRef` to the `beforeEachProviders` I get an error saying that there is no provider for `ng.core.ElementRef`.

In beta.15 I could add the directive and `ng.core.ElementRef` both to the `beforeEachProviders` and the tests worked great. In beta.16 I get the following error:

    Error: Cannot resolve all parameters for 'ElementRef'(?). 
    Make sure that all the parameters are decorated with Inject 
    or have valid type annotations and that 'ElementRef' is 
    decorated with Injectable.

Here is some example components and the directive:

```javascript
var Directive = ng.core
    .Directive({
      selector: '[directive]',
    })
    .Class({
      constructor:[
        ng.core.ElementRef,
        function Directive(elementRef) {}
        ],
      callFunction:function(){
        console.log('function called');
      }
    });
    
var ParentComponent = ng.core
    .Component({
      selector: 'parent-component',
      directives:[Directive],
      template:'<div directive><component-to-test></component-to-test></div>'
    })
    .Class({
      constructor:[
        function ParentComponent(){}
      ]
    })

var ComponentToTest = ng.core
    .Component({
        selector: 'component-to-test',
        template: '<p>Hello world!</p>',
        directives:[
            ng.common.COMMON_DIRECTIVES,
        ],
    })
    .Class({
        constructor:[
            Directive,
            function ComponentToTest(directive) {
              directive.callFunction();
            }
        ]
    });
```

and here is the test:
```javascript
ng.testing.describe('My child component', function() {
  
  ng.testing.beforeEachProviders(function() {
    return [
        ng.core.ElementRef,
        Directive,
        ng.platform.testing.browser.TEST_BROWSER_PLATFORM_PROVIDERS,
        ng.platform.testing.browser.TEST_BROWSER_APPLICATION_PROVIDERS,
    ];
  });
  
  ng.testing.it('should run be able to inject a directive provided in beforeEachProviders', ng.testing.injectAsync([ng.testing.TestComponentBuilder], function(tcb){
    return tcb
      .overrideTemplate(ComponentToTest, '<p>Hello world!</p>')
      .createAsync(ComponentToTest).then(function(fixture) {
        expect(true).toBe(true);
        fixture.destroy();
      })
       
  }))
});
```

beta.15 plnkr: http://plnkr.co/edit/bey6B0NJycbjRkasTchb?p=preview
beta.16 plnkr: http://plnkr.co/edit/bJEVYRoeIfWe781G8KEJ?p=preview

**Comment by ericmartinezr** [comment]
I think you're making a mistake here and I think your plnkr working with beta 15 is pure coincidence. ElementRef is not supposed to be provided manually, let angular do that for you. Your directive shouldn't be provided either, it's a directive/component, it goes in `directives: []` property. Another thing is that if you want to call your child from your parent you have to query for it (e.g ViewChild). Finally I moved `TEST_BROWSER_PLATFORM_PROVIDERS` and `TEST_BROWSER_APPLICATION_PROVIDERS` to `setBaseTestProviders` and I changed `injectAsync` to `async(inject(...`.

Here's your [plnkr](http://plnkr.co/edit/w45gnj5jNaTxO0dpUXsS) working. Hopefully I made myself clear.

**Comment by stringham** [comment]
My `ComponentToTest` doesn't actually _use_ the directive in it's markup. The component is used in a parent component, and the child component injects it.

When using the component it is always beneath a component using that directive, so injecting it works great. However, when testing the component, I test it in isolation so need to set up the dependency injector to know about the directive. The problem I'm finding is that `ng.core.ElementRef` can no longer be added as a dependency to the `beforeEachProviders(`

In my case, we created a directive that we call a popupAnchor, which we put on the root element, it injects an `ElementRef`, a `ViewContainerRef`, and a `ComponentResolver`.

A child component injects the popupAnchor and calls functions on the popupAnchor to add components (such as tooltips, callouts, or dialogs).

**Comment by SteveVanOpstal** [comment]
I've experienced a similar issue and solved it by providing a mock ElementRef implementation:

```
class MockElementRef implements ElementRef {
  nativeElement = {};
}

describe('ComponentToTest', () => {
  beforeEachProviders(() => [
    provide(ElementRef, { useValue: new MockElementRef() }),
    ComponentToTest
  ]);
});
```

Could have something to do with ElementRef now having nativeElement in its constructor due to following commit: https://github.com/angular/angular/commit/efbd446d18e6e0380beafcad6e94a7751d788623

**Comment by pkozlowski-opensource** [comment]
Sounds like this one got resolved.

**Comment by ajentering** [comment]
I got the same issue and resolved by changing the extends keyword to implements. and also removed export before class keyword.

Here it what i did to resolve it.

class MockElementRef implements ElementRef {
	nativeElement = {}; 
}

This worked perfectly fine.
