### ISSUE TITLE
[Blocker for upgrade] ng2 upgrade adapter does not call ng1 controller lifecycle methods

### ISSUE THREAD

**Issue by palmanis** [angular/angular#8304]
**Steps to reproduce** 
https://plnkr.co/edit/bnV4PCQmF8f7AYqD3VUp
The example has an ng1 directive as per the upgrade guidelines https://angular.io/docs/ts/latest/guide/upgrade.html#!#using-component-directives

Part 1: ng2 component is using upgraded ng1 component inside. When the button is clicked, it does change the baseValue, but DOES NOT call the $onChanges lifecycle method which calculates the derivedValue, so the derivedValue never gets updated.

Part 2: This confirms, that in purely ng1 mode, the directive works fine, clicking the button does increment baseValue and through $onChanges method the derivedValue also gets updated.

**Current behavior**
$onChanges is not getting called for ng1 directive, when a change is initiated from ng2 component. The value bound is updated, but the directive does not get to know that something changed. So there is no way to run any change handlers.

**Expected/desired behavior**
$onChanges should get called on ng1 controller, when a change is initiated from ng2 component, so that the code can update any derivedValues based on the change.
Not just $onChanges, but all the lifecycle methods should get called.

**Other information**
I checked the code inside upgrade.dev.js and it is not calling $onChanges.

``` javascript
UpgradeNg1ComponentAdapter.prototype.ngOnChanges = function(changes) {
      for (var name in changes) {
        if (changes.hasOwnProperty(name)) {
          var change = changes[name];
          this.setComponentProperty(name, change.currentValue); // With this the property does get updated, but the ng1 component does not get to know, that a change has happened, so it cannot react to it.
        }
      }
 };
```

Not sure if this is already known, but is really important for ng1 components to be upgradable.

**Comment by ericmackrodt** [comment]
Anything new on this one? It's been opened for months. I can't upgrade my app from bottom to top, only from top to bottom which is annoying as I wanted to change my routing mechanism from Angular 1 to Angular 2, but angular 1 components don't work properly when upgraded.

**Comment by rizoom** [comment]
It is interesting to note that while `UpgradeNg1ComponentAdapter.prototype.ngOnChanges` does not try to call `$onChanges`, `$onInit` gets called as expected (as shown in the snippet below):

```
UpgradeNg1ComponentAdapter.prototype.ngOnInit = function () {
    [...]
    if (this.destinationObj.$onInit) {
        this.destinationObj.$onInit();
    }
};
```

**Comment by jonrimmer** [comment]
For months we've been writing our ng1 components using this the component approach, making heavy use of the lifecycle methods, with the understanding that it would simplify the conversion process to ng2. The upgrade documentation on angular.io recommends this explicitly.

Now I find out the upgrade adapter doesn't even bridge these events? And this has been left as an open issue for *months*?

**What the hell is going on!?** How is anybody supposed to upgrade a reasonably sized app if basic stuff like this is broken?

**Comment by pangwa** [comment]
Looks like a fundamental issue before considering using ngUpgrade to upgrade an existing angular1.5 app.....
I've being working on to convert directives to components for an existing app and plan to upgrade to angular2  using the ngUpgrade module(and already working on to setup the environment).... I changed plan and hold until ngUpgrade become stable and workable after seeing this issue....

**Comment by dezoxel** [comment]
I believe this no longer actual.

My env:
```
    "@angular/common": "2.2.3",
    "@angular/compiler": "2.2.3",
    "@angular/core": "2.2.3",
    "@angular/forms": "2.2.3",
    "@angular/http": "2.2.3",
    "@angular/platform-browser": "2.2.3",
    "@angular/platform-browser-dynamic": "2.2.3",
    "@angular/router": "3.2.3",
    "@angular/upgrade": "2.2.3",
...
    "angular": "1.5.9",
```

Works just fine!

**Comment by gkalpak** [comment]
As mentioned above, lifecycle hooks have been working with `ngUpgrade` for a while now.
Closing as _fixed_.
