### ISSUE TITLE
Beta16 - [attr.class] override the [ngClass] instead of merge

### ISSUE THREAD

**Issue by guaido79** [angular/angular#8307]
From beta 16 the `[attr.class]` override the `[ngClass]`.

Here is [demo](http://plnkr.co/edit/1gGKICZo2R1pnL2AV1JZ?p=preview)

Before beta.16 all the class from `[attr.class]` and from `[ngClass]` were merged.

**Comment by pkozlowski-opensource** [comment]
See #8275
