### ISSUE TITLE
Bug: Missing quotes in package.json break babel/browserify build

### ISSUE THREAD

**Issue by mgreschke** [angular/angular#8309]
**Steps to reproduce and a minimal demo of the problem**

Running beta.16 on ubuntu 14.04.

The package.json has no quotes around some dynamic content statements:
```
"contributors": <%= JSON.stringify(packageJson.contributors) %>,
  "license": "<%= packageJson.license %>",
  "repository": <%= JSON.stringify(packageJson.repository) %>,
  "devDependencies": <%= JSON.stringify(packageJson.defaultDevDependencies) %>,
```

**Current behavior**

We receive this error, adding quotes around the dynamic content statements (JSON....) fixes the build and angular2 runs just fine afterwards.

```
> browserify -t babelify src/app/app.js -o build/public/app.js

Error: SyntaxError: Unexpected token < while parsing json file /srv/veyo_care/veyo/node_modules/angular2/es6/dev/package.json
    at /srv/veyo_care/veyo/node_modules/module-deps/index.js:493:30
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
```

**Expected/desired behavior**

npm run build worked just fine with earlier versions. Nothing was changed on the npm script command.

**Other information**

Manually putting quotes around the JSON.... statements fixes the build.

Anyone else having the problem? Would "fixing" this break other things? Feeling a bit weird about it since its in the package.json file.

**Comment by robwormald** [comment]
this sounds like you're using a version off github, not the npm distribution - is that correct?

**Comment by mgreschke** [comment]
Thanks for getting back @robwormald 

We're using the npm distribution beta.16. 
We're however currently not using the --production flag with npm install if that matters.
Also we removed the ^ symbol the npm version we wanted to stay at that version explicitly.

Could that change things?

Regards

**Comment by pkozlowski-opensource** [comment]
Generated `package.json` looks correct now, see: https://github.com/angular/core-builds/blob/master/package.json

Closing but feel free to open a new issue if there are still things not fully correct.
