### ISSUE TITLE
Better error handling for offline compilation

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#8310]
- [x] Symbol used in a decorator is not exported
- [ ] Empty project fails with `TypeError: Cannot read property 'symbol' of undefined`
more to come...

**Comment by vicb** [comment]
@alexeagle @chuckjaz can this be closed ?

**Comment by alexeagle** [comment]
Sure, but we still have a lot of individual issues with bad error reports...

**Comment by chuckjaz** [comment]
I propose we add separate issues for the bad errors we find instead of having one larger tracking issue.
