### ISSUE TITLE
How do I access specific validators on a given input in a form?

### ISSUE THREAD

**Issue by tchoulihan** [angular/angular#8311]
I want to display specific messages, for specific types of failed validation, when using the validation markup in html. 

My example:
```html
<input type="text" class="form-control"
 [(ngModel)]="newCourseTitle" 
ngControl="name" 
required 
pattern="^[a-zA-Z0-9(),-_.+]*$"
maxLength="255"
#newCourseName="ngForm">
```

Unfortunately, I only know how to see if its wholly valid:
`<div [hidden]="!newCourseName.valid || newCourseName.pristine" >` ...

But I would like to display specific messages; telling the user that the `A name is required`... if that specific validator is the one that failed. 

Thanks in advance.

**Comment by zoechi** [comment]
`newCourseName.errors` should provide that information

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by pkozlowski-opensource** [comment]
Thnx @zoechi

**Comment by tchoulihan** [comment]
Are there any docs for this? I couldn't find any.

**Comment by zoechi** [comment]
@tchoulihan doesn't look like this is documented. Document issues are maintained in https://github.com/angular/angular.io/issues

**Comment by tchoulihan** [comment]
Thanks, I'll open up an issue for this.
