### ISSUE TITLE
[Beta 16] - angular doesn't work after upgrade

### ISSUE THREAD

**Issue by clamarque** [angular/angular#8312]
Hi guys !

I have some bugs after upgrade.  Developer tool of the browser(Google Chrome) says:

angular2-polyfills.js:127 **GET http://localhost:3000/symbol-observable.js 404 (Not Found)**scheduleTask @ angular2-polyfills.js:127ZoneDelegate.scheduleTask @ angular2-polyfills.js:362Zone.scheduleMacroTask @ angular2-polyfills.js:299(anonymous function) @ angular2-polyfills.js:148send @ VM637:3fetchTextFromURL @ system.src.js:1154(anonymous function) @ system.src.js:1735ZoneAwarePromise @ angular2-polyfills.js:610(anonymous function) @ system.src.js:1734(anonymous function) @ system.src.js:2759(anonymous function) @ system.src.js:3333(anonymous function) @ system.src.js:3600(anonymous function) @ system.src.js:3985(anonymous function) @ system.src.js:4448(anonymous function) @ system.src.js:4700(anonymous function) @ system.src.js:406ZoneDelegate.invoke @ angular2-polyfills.js:349Zone.run @ angular2-polyfills.js:242(anonymous function) @ angular2-polyfills.js:597ZoneDelegate.invokeTask @ angular2-polyfills.js:382Zone.runTask @ angular2-polyfills.js:282drainMicroTaskQueue @ angular2-polyfills.js:500ZoneTask.invoke @ angular2-polyfills.js:452
angular2-polyfills.js:349 **Error: Error: XHR error (404 Not Found) loading http://localhost:3000/symbol-observable.js(…)**ZoneDelegate.invoke @ angular2-polyfills.js:349Zone.run @ angular2-polyfills.js:242(anonymous function) @ angular2-polyfills.js:597ZoneDelegate.invokeTask @ angular2-polyfills.js:382Zone.runTask @ angular2-polyfills.js:282drainMicroTaskQueue @ angular2-polyfills.js:500ZoneTask.invoke @ angular2-polyfills.js:452
angular2-polyfills.js:127 **GET http://localhost:3000/symbol-observable.js 404 (Not Found)**scheduleTask @ angular2-polyfills.js:127ZoneDelegate.scheduleTask @ angular2-polyfills.js:362Zone.scheduleMacroTask @ angular2-polyfills.js:299(anonymous function) @ angular2-polyfills.js:148send @ VM637:3fetchTextFromURL @ system.src.js:1154(anonymous function) @ system.src.js:1735ZoneAwarePromise @ angular2-polyfills.js:610(anonymous function) @ system.src.js:1734(anonymous function) @ system.src.js:2759(anonymous function) @ system.src.js:3333(anonymous function) @ system.src.js:3600(anonymous function) @ system.src.js:3985(anonymous function) @ system.src.js:4448(anonymous function) @ system.src.js:4700(anonymous function) @ system.src.js:406ZoneDelegate.invoke @ angular2-polyfills.js:349Zone.run @ angular2-polyfills.js:242(anonymous function) @ angular2-polyfills.js:597ZoneDelegate.invokeTask @ angular2-polyfills.js:382Zone.runTask @ angular2-polyfills.js:282drainMicroTaskQueue @ angular2-polyfills.js:500ZoneTask.invoke @ angular2-polyfills.js:452
system.src.js:371 Assertion failed: loading or loaded(anonymous function) @ system.src.js:371ZoneDelegate.invoke @ angular2-polyfills.js:349Zone.run @ angular2-polyfills.js:242(anonymous function) @ angular2-polyfills.js:597ZoneDelegate.invokeTask @ angular2-polyfills.js:382Zone.runTask @ angular2-polyfills.js:282drainMicroTaskQueue @ angular2-polyfills.js:500ZoneTask.invoke @ angular2-polyfills.js:452

and my config:

{
  "name": "Angular2_Dashboard",
  "version": "1.0.0",
  "description": "a dashboard",
  "main": "index.js",
  "scripts": {
    "start": "concurrently \"npm run tsc:w\" \"npm run lite\" ",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "lite": "lite-server",
    "typings": "typings",
    "postinstall": "typings install",
    "test": "karma start"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "concurrently": "^2.0.0",
    "firebase": "^2.4.2",
    "lite-server": "^2.2.0",
    "typescript": "^1.8.10",
    "typings": "^0.7.12"
  },
  "dependencies": {
    "angular2": "^2.0.0-beta.16",
    "es6-shim": "^0.35.0",
    "ng2-translate": "^1.11.3",
    "reflect-metadata": "^0.1.3",
    "rxjs": "^5.0.0-beta.2",
    "systemjs": "^0.19.26",
    "zone.js": "^0.6.10"
  }
}

what is this the file: symbol-observable.js ?
Thank !

**Comment by robwormald** [comment]
this is a new dependency in RxJS beta 7 (which angular has not yet upgraded to) - you'd need to install it and add it to your systemJS config, if you want to use a later version of Rx than the docs have.

**Comment by clamarque** [comment]
this my systemJS config:

 System.config({
        defaultJSExtensions: true,
        packages: { 
         '/angular2': {defaultExtension: false},
          app: {
            format: 'register',
            defaultExtension: 'js'
          }           
        },
            map: {
                'angular2': 'node_modules/angular2',
                'ng2-translate': 'node_modules/ng2-translate',
                'rxjs': 'node_modules/rxjs',
                'firebase': '/node_modules/firebase/lib/firebase-web.js',
            }
      });
      System.import('app/main')
            .then(null, console.error.bind(console));


Have same error .. What is wrong here ?

**Comment by clamarque** [comment]
ok. it's work with rxjs@5.0.0.beta.6. thanks !

**Comment by zoechi** [comment]
@clamarque I think you can close the issue.
