### ISSUE TITLE
Dart Angular 2.0.0-beta.17's # deprecation causes TemplateCompiler stack traces

### ISSUE THREAD

**Issue by domesticmouse** [angular/angular#8325]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here, see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. 

**Steps to reproduce and a minimal demo of the problem**

Upon upgrading to Dart Angular 2.0.0-beta.17 I have the following situation:

    $ pub build
    Loading source assets... 
    Loading angular2/transform/codegen, dart_to_js_script_rewriter, less_dart, observe and smoke/src/default_transfLoading angular2/transform/codegen, dart_to_js_script_rewriter, less_dart, observe and smoke/src/default_transformer transformers... 
    Loading angular2 transformers... (4.1s) 
    [Info from less-dart] lessc --no-color web/styles/styles.less > web/styles/styles.css took 0.2s
    Template parse warnings:
    "#" inside of expressions is deprecated. Use "let" instead! ("    <panel [ERROR ->]*ngFor="#p of panels" [panel]='p'></panel>"): DashboardComponent@0:11

**Current behavior**

Now pub serve blows up:

    package:angular2/src/transform/template_compiler/compile_data_creator.dart 263  _CompileDataCreator._extractNgMeta.<async>
    Build error:
    Transform TemplateCompiler on xxxx|lib/components/dashboard/dashboard_component.ng_meta.json threw error: Template parse errors:
    Property binding ngFor not used by any directive on an embedded template ("    [ERROR ->]<panel *ngFor="let p of panels" [panel]='p'></panel>

**Expected/desired behavior**

Implement all of the # -> let renaming =)

**Other information**

**Comment by pkozlowski-opensource** [comment]
Obsolete: http://angularjs.blogspot.fr/2016/07/a-dedicated-team-for-angulardart.html
