### ISSUE TITLE
"angular2": "2.0.0-beta.16", DynamicComponentLoader load component problem

### ISSUE THREAD

**Issue by racktime** [angular/angular#8326]
"angular2": "2.0.0-beta.16", DynamicComponentLoader load component
template variable value setting has encountered a problem.
It was well until the previous beta.15 version. 

  System.import ( 'path'). Then (o => {
//Child component
             this.loader.loadAsRoot (comp, '#' + this.model.id, this.elementRef.injector); 
         });

child component
test = '123412341234'
template '<div> {{test}} </ div>'

dynamic add child component template test variable not setting value

**Comment by zoechi** [comment]
Can you please create a Plunker to reproduce?

**Comment by racktime** [comment]
test url : https://plnkr.co/edit/SpsVDz?p=preview

but node_module is local url
can not run

**Comment by zoechi** [comment]
Seems related to https://github.com/angular/angular/issues/8146#issuecomment-212218894 I haven't tried it myself in older versions. In the Plunker link in the linked comment similar binding as in your example is workign.

**Comment by racktime** [comment]
it's problem solved thank u 
 constructor(public loader: DynamicComponentLoader, public elementRef: ViewContainerRef) {      
        System.import('./test/childComp').then(o => {
            this.loader.loadAsRoot(ChildComp, '#child', this.elementRef.injector).then((compRef) => {
                //cmpRef.instance.test = someData;
                compRef.instance.test = 'asdfasdfasdfasdfa';
                compRef.changeDetectorRef.detectChanges();
                return compRef;
            });              
        });
    }

**Comment by zoechi** [comment]
@racktime I think you can close this issue then.
