### ISSUE TITLE
Angular2 beta 17: error TS2339: Property 'from' does not exist on type 'typeof Observable'. (Visual Studio 2015 ASP.NET 5)

### ISSUE THREAD

**Issue by virtualvoid** [angular/angular#8327]
Observable
            .from(this.resourceStaffs) // resourceStaffs is array
            .map((resourceStaff: ResourceStaff, index: number) ...
...

before upgrade, it worked well.

**Comment by virtualvoid** [comment]
"rxjs": "5.0.0-beta.6",

import { Observable } from 'rxjs/Observable';
import 'rxjs/Rx';



what else I'm missing here ?

**Comment by zoechi** [comment]
Might be related to #8312

**Comment by virtualvoid** [comment]
@zoechi I'm sorry but I think it's not related at all. The method "from" / "fromArray" disappeared from observable.d.ts. 

I've downgraded ng2 back to beta16 which depends on rxjs 5.0.0-beta.2 - that version is still working.

**Comment by virtualvoid** [comment]
![observable_error_01](https://cloud.githubusercontent.com/assets/234315/14914849/446e4324-0e0e-11e6-80ae-d13238a639bb.png)

**Comment by fjozsef** [comment]
Have you tried `import 'rxjs/add/observable/from';` ?

**Comment by virtualvoid** [comment]
@fjozsef yes I tried that, sadly that makes no difference.

i'm starting to think that this is somehow related to Visual Studio 2015. Because i've created sample project outside of it and the `Observable.from` magically works there .

**Comment by Ristaaf** [comment]
Maybe you use a built in TypeScript version that is too old in VS2015, Think I read somewhere that one reason Angular 2 stayed on beta 2 for so long was that they needed to upgrade TypeScript version first. My guess is that you need TypeScript 1.8 or higher.

**Comment by virtualvoid** [comment]
@Ristaaf good point. however I'm compiling TS files using gulp and these packages :
```
"gulp-typescript": "2.13.0",
"typescript": "^1.8.10",
```

**Comment by ericmartinezr** [comment]
Change
```
import { Observable } from 'rxjs/Observable';
import 'rxjs/Rx';
```
To
```
import {Observable} from 'rxjs/Rx';
```

**Comment by ChrisProlls** [comment]
Same problem here with the `map` method. These import doesn't work 
```
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/observable/map';
```

**Comment by ericmartinezr** [comment]
@ChrisProlls `map` must be imported from `rxjs/add/operator/map`.

**Comment by ChrisProlls** [comment]
That was my import before the beta17, so I tried what you suggested, but with the `map` method, but I have the same error too ...

**Comment by virtualvoid** [comment]
Thanks for all suggestions - I've tried all options I've found and ended up with at least little success.

Gave up on Visual Studio and opened project in another IDE.
I have changed the `Observable.fromArray` to `Observable.from` and my `.zipAll` to just `.zip` which was good start. I managed to get it compiling.

When I got back to Visual Studio the compilation using gulp was still fine but the IntelliSense is still messed up (Method from not found in Observable).

So this is definitelly M$'s problem...

**Comment by virtualvoid** [comment]
Hmm, turns out that i can't use just `.zip`. I need replacement for `.zipAll` anybody knows solution ?

**Comment by virtualvoid** [comment]
So here's what i need to do with new ng2 and rxjs :

```
    Observable
      .fromArray(this.resourceStaffs)
      .map((resourceStaff: ResourceStaff, index: number) => this._resourceService.saveResourceStaff(resourceStaff, index))
      .zipAll()
      .subscribe((objectIndices: Array<ObjectIndex<ResourceStaff>>) => { ... });
```
can anybody help me please ?

**Comment by ericmartinezr** [comment]
@virtualvoid this works for me

```
import {Observable} from 'rxjs/Observable';
import 'rxjs/add/observable/from';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/zipAll';

Observable
      .from(this.resourceStaffs)
      .map((resourceStaff: ResourceStaff, index: number) => ...)
      .zipAll()
      .subscribe(...);
```
Note that `fromArray` was removed (see https://github.com/ReactiveX/rxjs/pull/1539), so you should use `from`.

I just tried the imports, not the functionality and I had no issues. My config in case you're curious

package.json
```
    "angular2": "^2.0.0-beta.17",
    "rxjs": "^5.0.0-beta.7",
    "typescript": "^1.9.0-dev.20160428-1.0"
```
tsconfig.json
```
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "moduleResolution" : "node",
    "module": "commonjs",
    "removeComments": true,
    "sourceMap": true,
    "lib" : ["es6", "dom"]
  },
```

**Comment by virtualvoid** [comment]
sadly though, this does not make any difference for me :(

Visual Studio doesn't see the method from:
![rxjs_vs_2015](https://cloud.githubusercontent.com/assets/234315/14948218/30ad9376-103e-11e6-9140-570fab66db2b.png)

and the compiler says:
```

error TS2345: Argument of type '**(objectIndices: ObjectIndex<ResourceStaff>[]) => void**' is not assignable to parameter of type '**NextObserver<Observable<ObjectIndex<ResourceStaff>>[]> | ErrorObserver<Observable<ObjectIndex<Res...**'.
  Type '(objectIndices: ObjectIndex<ResourceStaff>[]) => void' is not assignable to type '(value: Observable<ObjectIndex<ResourceStaff>>[]) => void'.
    Types of parameters 'objectIndices' and 'value' are incompatible.
      Type 'Observable<ObjectIndex<ResourceStaff>>[]' is not assignable to type 'ObjectIndex<ResourceStaff>[]'.
        Type 'Observable<ObjectIndex<ResourceStaff>>' is not assignable to type 'ObjectIndex<ResourceStaff>'.
          Property '_object' is missing in type 'Observable<ObjectIndex<ResourceStaff>>'.

```
Which is weird more than previously.

**Comment by virtualvoid** [comment]
Well, looking at that error message _that actually_ makes difference. But why the `subscribe `method expects `Observable<... ` ?

**Comment by virtualvoid** [comment]
Thanks all for your support.

**Comment by ammar91** [comment]
This not seems to be working for me as well with 

```
 "angular2": "^2.0.0-beta.17",
  "rxjs": "^5.0.0-beta.7",
```
Can't find map and other rxjs operators. Only getting subscribe in intellisense, please help

**Comment by kb3eua** [comment]
I'm having the exact same issue with 2.0.0-rc.0.  Webpack compiles the typescript just fine, but VS2015 intellisense can't find the "map" method on Observables.  And I'm running the latest version of everything.

**Comment by tb** [comment]
@kb3eua Make sure VS2015 uses typescript 1.8 - it might be using global typescript which is older. For more details see http://stackoverflow.com/a/37034227/478584

**Comment by bstaley** [comment]
I know this fix doesn't seem related but I had the same thing happen for 'fromPromise'. The following fixed it in VS2015 update 3. https://github.com/Microsoft/TypeScript/issues/8518#issuecomment-229506507

**Comment by ignacioliveros** [comment]
@bstaley  it's works for "property 'map' does not exist on type 'observable'" , thank you..

**Comment by iBasit** [comment]
I have all the right tags, it does not show error on build anymore, but still shows error on IDE (phpStorm)

```
import {Observable} from "rxjs/Observable";
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/switchMap';
import 'rxjs/add/observable/from';
import 'rxjs/add/observable/empty';
```

![image](https://cloud.githubusercontent.com/assets/34341/18792895/4ccd206a-81b0-11e6-8594-0c75cc04fe82.png)

**Comment by tdinar** [comment]
well I am having this problem too:
``ERROR in [default] /projects/oped/src/app/dashboard.component.ts:60:35 Property 'startWith' does not exist on type 'typeof Observable'."

``import {Observable} from 'rxjs/Observable';
import { Subject}                   from 'rxjs';
import    "rxjs/add/operator/startWith";
import    "rxjs/Rx"
 all these imports would not relief me from the error

**Comment by Moonlighter** [comment]
Hello, i think that a have a same problem : but with tis error : app/app.component.ts(74,19): error TS1109: Expression expected. Some idea ?

`import {Component, OnInit} from '@angular/core';
import { Hero } from './hero';
import { HeroService } from './hero.service';

@Component({
    selector:'my-app',
    template:`
     <h1>{{title}}</h1>
     <h2>My Heroes</h2>
     <ul class="heroes">
        <li *ngFor="let hero of heroes" [class.selected]="hero === selectedHero" (click)="onSelect(hero)">
         
         <span class="badge">{{hero.id}}</span>{{hero.name}}
        </li>
     </ul>
     <my-hero-detail [hero]="selectedHero"></my-hero-detail>
     `,
    styles: [`
  .selected {
    background-color: #CFD8DC !important;
    color: white;
  }
  .heroes {
    margin: 0 0 2em 0;
    list-style-type: none;
    padding: 0;
    width: 15em;
  }
  .heroes li {
    cursor: pointer;
    position: relative;
    left: 0;
    background-color: #EEE;
    margin: .5em;
    padding: .3em 0;
    height: 1.6em;
    border-radius: 4px;
  }
  .heroes li.selected:hover {
    background-color: #BBD8DC !important;
    color: white;
  }
  .heroes li:hover {
    color: #607D8B;
    background-color: #DDD;
    left: .1em;
  }
  .heroes .text {
    position: relative;
    top: -3px;
  }
  .heroes .badge {
    display: inline-block;
    font-size: small;
    color: white;
    padding: 0.8em 0.7em 0 0.7em;
    background-color: #607D8B;
    line-height: 1em;
    position: relative;
    left: -1px;
    top: -4px;
    height: 1.8em;
    margin-right: .8em;
    border-radius: 4px 0 0 4px;
  }
`],
    providers:[HeroService]


})

export class AppComponent implements  OnInit{
    title = 'Tour of Heroes';
    **heroes = Hero[];**
    selectedHero : Hero;

    constructor(private heroService: HeroService){}

    getHeroes(): void {
        this.heroService.getHeroes().then(heroes=>this.heroes = heroes);
    }

    ngOnInit(): void{
        this.getHeroes();
    }

    onSelect(hero: Hero): void{
        this.selectedHero = hero;
        // console.log(this.selectedHero);
    }
}

`

**Comment by Moonlighter** [comment]
Ok, there is good now !
I watched a thousand times and I have not seen the sign of equality " = " ; lol ! Thank's .

**Comment by ozknemoy** [comment]
have same story 
[at-loader] node_modules\rxjs\src\Notification.ts:88:27 
    Property 'of' does not exist on type 'typeof Observable'. 
[at-loader] node_modules\rxjs\src\Notification.ts:92:27 
    Property 'empty' does not exist on type 'typeof Observable'. 

import { Observable } from 'rxjs/Observable';
import 'rxjs/add/observable/of';
import 'rxjs/add/observable/empty';

service:
dataObs$ = new ReplaySubject(1);

    getData(forceRefresh?: boolean):any {
        // If the Subject was NOT subscribed before OR if forceRefresh is requested
        if (!this.dataObs$.observers.length || forceRefresh) {
            this.http.get('http://jsonplaceholder.typicode.com/posts/2').subscribe(
                (data:any) => this.dataObs$.next(data),
                (error:any) => {
                    this.dataObs$.error(error);
                    // Recreate the Observable as after Error we cannot emit data anymore
                    this.dataObs$ = new ReplaySubject(1);
                }
            )
        }
        return this.dataObs$;
    }

and component: 
constructor () {
this.httpService.getData().subscribe((requestData:any):any => {
            this.ret =  requestData.json();
        });
}


Notification.ts:88:27 : (ide highlighted "throw" , "of" and "throw" as unresolved function or method)
![123](https://cloud.githubusercontent.com/assets/16036508/22143533/cb035ec0-df13-11e6-9a07-a7bcc7f5b017.png)

**Comment by kevindqc** [comment]
@ozknemoy Have you found a solution? I can't use `Observable.delay` because it can't find `delay`...

**Comment by ozknemoy** [comment]
@kevindqc nope

**Comment by DzmitryShylovich** [comment]
@kevindqc `delay` is an instance method `import 'rxjs/add/operator/delay';`

**Comment by ozknemoy** [comment]
@kevindqc just updated angular to 2.4.9 and the issue gone

**Comment by trsh** [comment]
Same here. 

`import { Observable } from 'rxjs/Observable'`
`import 'rxjs/add/operator/startWith';`

gives Property 'startWith' does not exist on type 'typeof Observable'.

Ide: Atom

**Comment by tumoxep** [comment]
Same thing with 'delay'. I've found that `src/app/hero.service.ts` source in https://angular.io/guide/reactive-forms contains working delay code. This thing works for me
```
import { Observable } from 'rxjs/Observable';
import { of } from 'rxjs/observable/of';
import 'rxjs/add/operator/delay';

of(true).delay(1000).subscribe(() => {
  /* code to ex. after delay */
});
```
Didn't know is it ok to write this way btw

**Comment by DeepzSandra** [comment]
Same thing with 'delay'. contains working delay code. This thing works for me

import { Observable } from 'rxjs/Observable';
import { of } from 'rxjs/observable/of';
import 'rxjs/add/operator/delay';

of(true).delay(1000).subscribe(() => {
  /* code to ex. after delay */
});
