### ISSUE TITLE
ngFor "let " vs ngFor "#"

### ISSUE THREAD

**Issue by robertellis100** [angular/angular#8328]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here, see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. 

**Steps to reproduce and a minimal demo of the problem**
Use the current Hero tutorial!

_Use https://plnkr.co or similar -- try this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5_

_What steps should we try in your demo to see the problem?_

**Current behavior**
nhandled Promise rejection: Template parse errors:
Can't bind to 'ngFor' since it isn't a known native property ("
    <h2>My Heroes</h2>
    <ul class="heroes">
      <li [ERROR ->]*ngFor="let hero of heroes"

**Expected/desired behavior**

**Other information**
started the tutorial yesterday with *ngFor="#hero of heroes", then today early this morning ish, it flips to *ngFor="let hero of heroes" and throws errors.

**Comment by jrub** [comment]
I guess they updated the tutorial to yesterday's new beta, beta17. See https://github.com/angular/angular/blob/master/CHANGELOG.md it says `<div *ngFor="#item of items"> now becomes <div *ngFor="let item of items">`

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by pkozlowski-opensource** [comment]
Yup, this change is part of the changelog.
