### ISSUE TITLE
[beta 17] Error: Uncaught (in promise): TypeError: componentView.parent.removeChild is not a function

### ISSUE THREAD

**Issue by ngydat** [angular/angular#8329]
Hello,

Before I updated angular2 to the latest version, everything was working fine (even though I had to keep using the 9th beta of Angular 2 ) but now I have this [error](http://hpics.li/c9cba51). Between the 9th beta and the latest one, I had other issues (I couldn't even launch my mobile application).
And [here](https://github.com/ngydat/connect) is the code of my project

Edit : I've just noticed I have this error only if I use the latest version of [nativescript-angular](https://github.com/NativeScript/nativescript-angular)(0.0.46). If I use this combination (angular2@2.0.0-beta.9 + nativescript-angular 0.0.45), everything works fine.

**Comment by zoechi** [comment]
Can you reproduce in a Plunker?

**Comment by ngydat** [comment]
@zoechi Not sure I can because as you can see in the [code](https://github.com/ngydat/connect) I put in my post and from what I understand, Plunker is for web development and my code is for a mobile application using Nativescript and Angular 2. Maybe my issue doesn't come from Angular

**Comment by vicb** [comment]
obsolete
