### ISSUE TITLE
[testing] can't access children directive componentInstance (regression in beta.16/17)

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#8332]
Updating from `beta.15` to `beta.17`, a few of my unit tests stopped working.

For a directive like this one: 

```typescript
@Directive({
  selector: '[simpleDirective]'
})
export class SimpleDirective {

}
```

Used in a template: `<div simpleDirective></div>`

In `beta.15`, it was possible to access a children directive `componentInstance`, with something like:

    let simpleDirective = fixture.debugElement.children[0].componentInstance;

But in `beta.17`, `simpleDirective` is now undefined.

I think this is a regression, as I did not spot a commit explicitly disallowing the previous behavior.

cc @juliemr

**Comment by juliemr** [comment]
This is an intended consequence of the recent refactoring to enable codegen (I will find the exact commit and link it). I think that this is actually a bug fix because directives were never components, so `componentInstance` should have never returned instances of directives. 

The proper way to do this is

```js
let simpleDirective = fixture.debugElement.query(By.directive(SimpleDirective)).injector.get(SimpleDirective);
```

**Comment by juliemr** [comment]
That commit: https://github.com/angular/angular/commit/0c600cf6e31b7f69f5a36f7dea959e4884217a4d

**Comment by juliemr** [comment]
@cexbrayat are you OK with me closing this as 'working as intended'?

**Comment by cexbrayat** [comment]
Sure, I was just checking if that was normal. Thank you for taking the time to verify.
