### ISSUE TITLE
Tutorial-6-routing: Html issue in the tutorial

### ISSUE THREAD

**Issue by aurrelhebert** [angular/angular#8334]
Hello, 
I finished the tutorial "Tour of hero" and notice a small error than can lead to further mistake on it. 
In the paragraph of the chapter 6. routing: 

> While we're in index.html, we add `<base href="/">` at the top of the `<head>` section. 
`<head>`
`<base href="/">`

The balise base is opened but never close. It means, that if an user doesn't close it by himself, he will not be noticed and keep going on. Then he may have trouble to find where was its mistake.
The solution can be 
`<head>`
` <base href="/"/>`

**Comment by ericmartinezr** [comment]
@aurrelhebert would you mind to report this over https://github.com/angular/angular.io ? That repo is for the website :smile:

**Comment by CaptainCodeman** [comment]
You don't needs to close all tags in html5 - that was an xhtml thing.

https://developer.mozilla.org/en/docs/Web/HTML/Element/base

**Comment by pkozlowski-opensource** [comment]
@CaptainCodeman is an [void](https://www.w3.org/TR/html-markup/syntax.html#syntax-elements) element. Self-closing tag is optional for void elements.

**Comment by aurrelhebert** [comment]
Thanks :)

**Comment by CaptainCodeman** [comment]
@pkozlowski-opensource optional *if using html5*, self-closing tags were *required* for xhtml, void means that the element can't contain content. i.e. `<img>` or `<img />` (with xhtml) vs `<img></img>` but obviously is what self-closing would most likely apply to.

**Comment by aurrelhebert** [comment]
Working with the index file of the tutorial, self-closing do not work. And in the HTML code of the solution provided, the tag base is closed. If you delete it, like its written in the tutorial, it doesn't work neither on Mozilla nor on Chrome.

**Comment by pkozlowski-opensource** [comment]
> optional if using html5

tutorial _is_ using HTML5, isn't it?

**Comment by aurrelhebert** [comment]
It is, I opened a new issue in the right place: https://github.com/angular/angular.io/issues/1216

**Comment by CaptainCodeman** [comment]
> tutorial is using HTML5, isn't it?

No, it misses out the doctype
