### ISSUE TITLE
*ngFor on a component with [ngClass] does not render content as of beta.17

### ISSUE THREAD

**Issue by adamdbradley** [angular/angular#8344]
**Current behavior**

A component with `<ng-content>` does not render its content when it uses `*ngFor` and `[ngClass]`. In this example, the first `ngFor` is not rendering any content, but the second one is.

Beta.17 example: http://plnkr.co/edit/EBbpWOubKNsdETr6HI14?p=preview

**Expected/desired behavior**

In this example, both ngFor's are rendering their text, and the css class is correctly being applied to the first set:

Beta.16 example: http://plnkr.co/edit/q3K2QHKf3h8umdNenUOT?p=preview

**Comment by pmowrer** [comment]
I'm seeing a related content projection bug in beta.17.

A component with `<ng-content>` does not render its content if a directive matches the component's selector AND that directive is declared before the component in `directives`.

beta.17: http://plnkr.co/edit/mUxkmjGqZ0ZDzbTdBUMj?p=preview

beta.16: http://plnkr.co/edit/CdeJ7quEe8uXd61uCSpo?p=preview

**Comment by jelbourn** [comment]
cc @tbosch

**Comment by jelbourn** [comment]
I am seeing the same issue with `ngModel` (instead of ngClass)
