### ISSUE TITLE
fakeAsync doesn't propagate errors from async tasks

### ISSUE THREAD

**Issue by vikerman** [angular/angular#8351]
The fakeAsync Zone Spec has code to catch and rethrow exceptions that happen in async task callbacks. However this doesn't seem to propagate out of the fakeAsync() wrapper in angular.

Need to fix this and re-enable the test at https://github.com/angular/angular/blob/master/modules/angular2/test/testing/fake_async_spec.ts#L93

**Comment by tbosch** [comment]
I was able to reenable the test and it works.
However, I had some problems where a test in isolation would not throw, only when run together with others tests that don't use `fakeAsync`. Was not able to reproduce this exactly though...

**Comment by vicb** [comment]
@vikerman can this be closed ?
