### ISSUE TITLE
alt_router: RouterUrlSerializer cannot parse query parameter

### ISSUE THREAD

**Issue by laco0416** [angular/angular#8356]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here, see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. 

**Current behavior**

```ts
let url = new DefaultRouterUrlSerializer();

it("should parse a query parameter", () => {
  let tree = url.parse("/one?a=1");
  expect(url.serialize(tree)).toEqual("/one?a=1");
});
```

```
Expected ';a=1/one' to equal '/one?a=1'.
```

RouterUrlSerializer cannot parse query params correctly.

**Expected/desired behavior**

It should pass above test. 

**Other information**

cc/ @vsavkin

**Comment by vicb** [comment]
obsolete
