### ISSUE TITLE
alt_router: support routerLink on other elements then anchors

### ISSUE THREAD

**Issue by choeller** [angular/angular#8357]
**Steps to reproduce and a minimal demo of the problem**

The new implementation of `RouterLink` currently only supports `<a>` tags. Using the directive on a `div` leads to the following exception:

```html
<div [routerLink]="['/tasks','edit', task.id]" class="fade-in task-list-entry">
  ...
</div>
```

```
Template parse errors:
Can't bind to 'href' since it isn't a known native property ("[ERROR ->]<div [routerLink]="['/tasks','edit', task.id]" class="fade-in task-list-entry" [ngClass]="{selected :"): ...
```

**Expected/desired behavior**

RouterLink should also work on `<div>`-Elements

**Other information**

**Comment by laco0416** [comment]
you can use `Router.navigate` in on-click handler of any element. 
I doesn't think RouterLink should allow non-anchor elements.

**Comment by choeller** [comment]
Hmm, I don't know - so it would be nice to have a cleaner way to react on click events then using `router.navigate`. I used it to activate my aux-route before. 

Currently my components only dependency to the router is `ROUTER_DIRECTIVES` what makes it pretty easy to unit-test most of it. For calling `router.navigate` I would need to inject `Router` into the component and make it available as a membervariable, which makes it way harder to test...

**Comment by CaptainCodeman** [comment]
I think it is more 'correct' to wrap the element with an anchor element. This then retains all the proper anchor behavior (e.g. opening in new tab etc...)

**Comment by choeller** [comment]
In my case wrapping it in a "anchor" elements leads to a quite a lot of other problems. So the element I want to use as a trigger for activating the aux-route has quite some other stuff on it. like a button to delete the element etc:

![bildschirmfoto vom 2016-04-30 16 51 35](https://cloud.githubusercontent.com/assets/423277/14936725/5265ab02-0ef4-11e6-9324-65ebb9e36e9a.png)

So when clicking into the element, the aux-route should open (JIRA-like). now making the whole element an anchor e.g. activates the button-hover effect when just hovering the element etc. I agree that in most cases it's cleaner to use a real link instead of a div, but I also see use-cases for divs to activate another route... Hmm, now talking about it maybe this is really an edge-case... so for now `router.navigate` works as a workaround for me ;)

**Comment by AloeDream** [comment]
@CaptainCodeman this is wrong. I have a WinJS menu and it was working just fine in beta. Now if I place router link inside <a> it will look like this.
![default](https://cloud.githubusercontent.com/assets/13584857/15097280/a92c9034-1527-11e6-93b5-6a889cbaf1f0.png)
So yes, calling router.navigate is a workaround, but I would rather continue using router links declaratively.

**Comment by leon** [comment]
One of the scenarios that I often encounter is being able to add routerLink to `<tr>` tags

**Comment by Doormouse2House** [comment]
Worth highlighting that any future users who plan to integrate with Bootstrap & utilise buttons would hit this, f.e I was previously using:
```
<div class="td-button-wrapper">
					<div class="btn-group" role="group">
						<button id="involvedButton" [routerLink]="['/involved']" type="button" class="btn btn-default">Get Involved</button>
					</div>
				</div>
```
Yes, you could wrap this in an anchor element, but it seems strange to need to make adjustments to your DOM to accomodate the Directive, particularly as this is a familiar HTML pattern.

**Comment by Doormouse2House** [comment]
Actually, just noted that wrapping a button in an anchor would contravene HTML5 spec, see:
https://stackoverflow.com/questions/6393827/can-i-nest-a-button-element-inside-an-a-using-html5#6393863

**Comment by jmsegrev** [comment]
In my case I had many buttons tag with the [routerLink] together with [disabled] attribute, replacing the button with an anchor, failed because [disabled] is not a native attribute of the anchor tag. I had bootstrap so was able to replace the [disabled] with the [class.disabled]. 

Having the RouterLink directive work in any element should be the way to go. It was like this before RC.

**Comment by ThiagoT1** [comment]
We should keep in mind that when RouterLink is used on elements other than <a> (I also use it), MiddleClick will fail to open the new route on a new tab, while also failing to navigate at all.

PS: MiddleClick is still not supported by RouterLink, and a work around is still the only way to do it.

**Comment by spacebeers** [comment]
It would be really useful to be able to use this on other elements than anchor tags.
