### ISSUE TITLE
(feat)alt_router: Support relative links in components that don't have their own Routes-configuration

### ISSUE THREAD

**Issue by choeller** [angular/angular#8358]
**Steps to reproduce and a minimal demo of the problem**

Currently relative-links are only working if they are placed in a component that has it's own `@Routes`-configuration. When trying to add a RouterLink from a component to a "sibling component" (e.g. from a list to the edit-view) the following exception is thrown:

```html
<span>
   <a [routerLink]="['../edit', task.id]" class="link">{{task.title}}</a>
</span>
```

```
EXCEPTION: Error: Uncaught (in promise): Component 'TaskListComponent' does not have route configuration
```

the link seems to be created correctly as the generated "href" points to `http://localhost:4200/tasks/edit/1` and when opening the link in a new tabs everything works fine, just clicking on the link causes the error

**Expected/desired behavior**

relative links should work without a `Routes` config on the component

**Other information**

**Comment by laco0416** [comment]
AFAIK, alt_roiter doesn't support a navigation to parent (`../`) yet.

**Comment by ericmartinezr** [comment]
Maybe this commit adds relative navigation? Merged yesterday, should be on the next release https://github.com/angular/angular/pull/8354/commits/e5b87e55da794c367d475e0aec9a09e005899aa9

**Comment by choeller** [comment]
I just built the release from master, so this commit is already in my version, but I also think  `../` is not support yet - that's why I marked it as a feature ;)

**Comment by laco0416** [comment]
It's also a problem when using absolute path.

I tried to rewrite https://github.com/angular/angular2-seed to using alt_router, but I was blocked by this problem.

```
// repo-browser.ts has <router-outlet>
@Component({...})
@Routes([
  {path: "/:org", component: RepoListComponent},
  {path: "/:org/:name", component: RepoDetailComponent},
])
export class RepoBrowserComponent {
...
}

// repo-list.ts has <a [routerLink]="['/repo', repo.owner.login, repo.name]">
@Component({...})
export class RepoListComponent {
...
}

// repo-detail.ts
@Component({...})
export class RepoDetailComponent {
...
}
```

When I try to move from `/repo/angular/` (`RepoListComponent`) to `/repo/angular/angular` (`RepoDetailComponent`), An error occurs.

```
browser_adapter.ts:73 Error: Uncaught (in promise): Component 'RepoListComponent' does not have route configuration
``` 

Currently, we cannot move to anywhere from _terminal_ (old router word) route component.

**Comment by laco0416** [comment]
cc/ @vsavkin

**Comment by JohnCashmore** [comment]
Did you ever resolve this?
