### ISSUE TITLE
beta.17 using [ngStyle] prevents ng-content from working

### ISSUE THREAD

**Issue by abuda7em** [angular/angular#8364]
When using [ngStyle] on a component, `<ng-content>` stops working inside that instance. The issue is new to beta.17

Here is a plunk to show it:

[Plunk for beta.17](http://plnkr.co/edit/1s8Fd6MePkKe4nSBLHJJ?p=preview)
[Plunk for beta.16](http://plnkr.co/edit/si935WyUzeghoZPdII86?p=preview)

**Comment by ericmartinezr** [comment]
Related to / dup of https://github.com/angular/angular/issues/8344

See if it is the same behavior

**Comment by abuda7em** [comment]
Yup, it seems related. Thanks Eric.
