### ISSUE TITLE
Supply context to NgTemplateOutlet

### ISSUE THREAD

**Issue by shlomiassaf** [angular/angular#8368]
**Current behavior**
`NgTemplateOutlet` does not accept context.

**Expected/desired behavior**
`NgTemplateOutlet` has an additional `@Input` that allows attaching local context to `EmbeddedViewRef`

**Other information**
After [feat(core): introduce template context](https://github.com/angular/angular/commit/cacdead96dcfbb80dff899b5f5143b7c28c4d6dd#diff-eacaaeea1bf64a5081b7e14613111ec7) it is relativly easy to supply a context to the template ref

Should be something like
```ts
import {Directive, Input, ViewContainerRef, ViewRef, TemplateRef} from 'angular2/core';
import {isPresent} from 'angular2/src/facade/lang';

/**
 * Creates and inserts an embedded view based on a prepared `TemplateRef`.
 *
 * ### Syntax
 * - `<template [ngTemplateOutlet]="templateRefExpression"></template>`
 */
@Directive({selector: '[ngTemplateOutlet]'})
export class NgTemplateOutlet {
  private _insertedViewRef: ViewRef;
  private _context: Object;

  constructor(private _viewContainerRef: ViewContainerRef) {}

  @Input()
  set ngTemplateOutletContext(context: Object) {
    this._context = context;
  }

  @Input()
  set ngTemplateOutlet(templateRef: TemplateRef<Object>) {
    if (isPresent(this._insertedViewRef)) {
      this._viewContainerRef.remove(this._viewContainerRef.indexOf(this._insertedViewRef));
    }

    if (isPresent(templateRef)) {
      this._insertedViewRef = this._viewContainerRef.createEmbeddedView(templateRef, this._context);
    }
  }
}
```

**Comment by shlomiassaf** [comment]
@tbosch

**Comment by shlomiassaf** [comment]
I'm not sure it will work, given that these are 2 different templates.

```ts
    ctx = { self: {} };
```

```html
<template [ngTemplateOutlet]="templateRef" [ngTemplateOutletContext]="ctx"></template>
```

And in another file:
```html
<template #templateRef let-context="self">
    <pre>{{self | json }}</pre>
</template>
```

Will this work? `let-context` will search in the original template, not the injected one right?
So is this doable?

**Comment by bekos** [comment]
This doesn't seem so easy to achieve atm, but it would be really useful :+1: 
cc @pkozlowski-opensource

**Comment by pkozlowski-opensource** [comment]
This would be very easy to do, technically speaking - we just need to come up with an appropriate API for this.

**Comment by bekos** [comment]
@pkozlowski-opensource Awesome! Looking forward to this :-)

**Comment by pmowrer** [comment]
@shlomiassaf Your sample implementation works well... thanks!

**Comment by fxck** [comment]
According to @pkozlowski-opensource the code posted on https://github.com/angular/angular/issues/8368#issue-152201433 look ok, there are couple of test cases that needs to be added(https://gitter.im/angular/angular?at=5755486d824488852c4f3cdc)

- data from context gets displayed
- data changes if you update context (ex. add new property)
- Another case to consider would be what happens when the context gets re-binded (reference to an object changes)

**Comment by pkozlowski-opensource** [comment]
This was fixed in kaster via https://github.com/angular/angular/commit/164a091
