### ISSUE TITLE
Undefined error with child component with using Observable.create

### ISSUE THREAD

**Issue by Sharpiro** [angular/angular#8374]
**Steps to reproduce and a minimal demo of the problem**

http://plnkr.co/edit/wZw8W68N3mpKUmwupzkj?p=preview

Open console and select "Characters" from the nav bar

**Current behavior**
It seems the component thinks its child component is undefined.  The issue is in "app/characters/character.service.ts" at line 46 with the Observable.create method.  If you comment out the manually created observable and uncomment out the old http.get code, the application will begin to function once again.

**Comment by zoechi** [comment]
Would be great if you could strip the plunker of 20+ files ...

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by Sharpiro** [comment]
sure seems like a bug to me

**Comment by ericmartinezr** [comment]
It works fine if you use the lifecycle hook you should use. See the documentation for [ViewChild](https://angular.io/docs/ts/latest/api/core/ViewChild-var.html) to see in which lifecycle hook it will work. When you fix that you'll see other errors that you can search for in github.

**Comment by Sharpiro** [comment]
So this isn't my project, this is a template project from @johnpapa's angular 2 course.  I'm guessing he thought the lifecycle hook in use was acceptable.  And it seems odd that simply by using the create method of an observable rather than http.get would break it.

**Comment by ericmartinezr** [comment]
@Sharpiro in any case that's not an angular2 issue, it's not a bug or anything, it's simply a mistake and it has nothing to do with Observable.create.

You have this snippet

*CharacterListComponent*
```
  @ViewChild(FilterTextComponent) filterComponent: FilterTextComponent;

  getCharacters() {
    ...
        this.filterComponent.clear();
    ...
  }

 ngOnInit() {
 ... 
    this._dbResetSubscription = this._characterService.onDbReset
      .subscribe(() => this.getCharacters());
  }
```
Do you see the problem? You're calling `getCharacters` in `ngOnInit` which calls `filterComponent` which is a `@ViewChild`. That won't work, as I said in my previous comment. So change it to `ngAfterViewInit` and you're done.

**Comment by Sharpiro** [comment]
Ahh that does make sense.

However, after that quick change there is a new error:

```
EXCEPTION: Expression 'filteredCharacters | sortCharacters in CharacterListComponent@8:8' has changed after it was checked. Previous value: 'undefined'. Current value: '[object Object]' in [filteredCharacters | sortCharacters in CharacterListComponent@8:8]
```

I'm guessing that's what you meant by the "other errors" I will encounter.  Though I saw this [Stackoverflow anser](http://stackoverflow.com/questions/34364880/expression-has-changed-after-it-was-checked) but the plunker in that showing how to resolve the issue....still had the issue.  I also saw a few open github issues.  Any hints on how to fix this or avoid it?

**Comment by ericmartinezr** [comment]
@Sharpiro no, it isn't. That answer and using OnPush are workarounds, you should fix your code, and to be honest that plnkr it is extremely massive.

**Comment by Sharpiro** [comment]
ok, so I stripped out like half the files so it's not as huge.  anyone have details on how to go about fixing my code the right way?

**Comment by pkozlowski-opensource** [comment]
Support questions like this one should be directed to an appropriate support channel: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question 

@ericmartinezr thnx for trying to help out, much appreciated!
