### ISSUE TITLE
Scoping issue with directive

### ISSUE THREAD

**Issue by devin6391** [angular/angular#8379]
Applying same directive to many components in a single view, attaches event listener of that directive to only the last one.

I have 50 divs on a single component. I am making a directive named "lazyload". Then I am applying this directive to all those divs. In the onInit of "lazyload" directive, I have registered for scroll event. The eventlistener function of scroll is supposed to check if this div(in my case, all these 50 divs where this directive is applied) is inside viewport or not, and then do few operations on that particular div. But it seems that this scroll event is registered only for the last div of my view.

Is this a bug with directive? Some kind of scoping issue I think. In angular js 1.x we could apply the directives with separate scope and it worked perfectly.

**Comment by zoechi** [comment]
Also on http://stackoverflow.com/questions/36975851/applying-same-directive-to-many-divs-in-a-single-component-attaches-event-liste

**Comment by zoechi** [comment]
This can be closed - resolved on SO.
