### ISSUE TITLE
ngFor should have a "OnPush" option

### ISSUE THREAD

**Issue by brechtbilliet** [angular/angular#8382]
## The problem
By default *ngFor will check changes by object equality, which is great.
On the other hand, it will check all the html inside the generated code.
When you have big lists this can result in a lot of checks and rerenders.

```html
<ul>
  <li *ngFor="#user of users; trackBy index">
    {{user.firstName}}  {{user.lastName}} (age: {{user.age}}) 
  </li>
</ul>
```

## The solution
When writing a component with ChangeDetectionStragety.OnPush we can make sure it will **not** perform html changedetection when the inputs aren't changed. This means that when we add a component inside the *ngFor we have more control over the changedetection.

To optimize my code, I can create a component for every result of the *ngFor.
This might be a best practice anyway, but for one line of code it's not always pragmatic to write a new component.
```html
<ul>
  <li *ngFor="#user of users; trackBy index">
    <user-view-onpush [user]="user"></user-view-onpush>
  </li>
</ul>
```

## Feature request
It would be awesome if I could do something like:
```html
<ul>
  <li *ngFor="#user of users; trackBy index; OnPush = true">
    {{user.firstName}}  {{user.lastName}} (age: {{user.age}}) 
  </li>
</ul>
``` 
That way only the third line would be checked/rendered when the reference of #user changed.
This makes it easier to work with immutable data

## Plunkr
[https://plnkr.co/edit/RTm1H6qrj8DxQMxLoyVL?p=preview](https://plnkr.co/edit/RTm1H6qrj8DxQMxLoyVL?p=preview)

## Explanation through scheme
![change detection -ngfor 1](https://cloud.githubusercontent.com/assets/480083/14951632/a9239712-105a-11e6-9ac9-19b61f3a385f.jpg)

**Comment by pkozlowski-opensource** [comment]
Couldn't you create a component with the OnPush strategy and stick it _above_ ngFor? Wouldn't it better express your situation? On top of this ngFor wouldn't need to do any work and no changes would be needed to the framework.

**Comment by wesleycho** [comment]
This looks like it'd require extra configuration in order to implement this, which results in a bigger core framework. The workaround is fairly minor in cost, so maybe it would be better unsupported via configuration, but I don't know - this does look a bit like a nuance in which a change could net performance benefits.

**Comment by vicb** [comment]
As @pkozlowski-opensource said, you should create a nested component

**Comment by nickwinger** [comment]
i also need this, why this is closed ??
ngFor evaluates the expression all the time, instead of just once !

**Comment by danranVm** [comment]
I also need this.
I don't want ngFor trigger change detection all the time when I use Onpush.

**Comment by mlc-mlapis** [comment]
@vicb @pkozlowski-open @brechtbilliet ... the idea to be able to use the detection of a new reference for each element of `users` as shown below has some real potential ... especially when iterating over a larger set of elements, when **overhead** for the initial creation of a component for each element is really measurable.

Sure, there is always some way of using virtual scrolling (for nested `*ngFor` really not trivial as a flat one level `*ngFor`) but still, it adds the significant complexity.

```
<li *ngFor="#user of users; trackBy=myTrackBy; OnPush = true">
    {{user.firstName}}  {{user.lastName}} (age: {{user.age}}) 
</li>
```
