### ISSUE TITLE
access componentTypes from within APP_INITIALIZER function

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#8383]
Before I updated to version `beta.17` I was using `APP_INITIALIZER` to register a callback for when the app was bootstrapped in order to get a hang of `componentTypes`.

I basically had the following:
```js
new Provider(APP_INITIALIZER, {
	useFactory: (appRef: ApplicationRef, myService: MyService) => {
		return () => {
			appRef.registerBootstrapListener(() => {
				for (let component of appRef.componentTypes) {
					myService.registerFromComponent(component);
				}
			});
		};
	},
	multi: true,
	deps: [
		ApplicationRef,
		MyService
	]
})
```

Which worked just fine, but once I updated I started getting `Error: EXCEPTION: Error during instantiation of ApplicationRef_! (ApplicationRef -> ApplicationRef_).`.

After investigating, I found that `APP_INITIALIZER`is now dep of `ApplicationRef` [application_ref.ts#L276](https://github.com/angular/angular/blob/ce5b37239ec4214ef1db1a460c71056ec5135489/modules/%40angular/core/src/application_ref.ts#L276), hence the cyclic dep error.

So now that what I had is not working anymore, how else should I get a hang of `componentTypes` when `APP_INITIALIZER` is called? Is there an alternative way of doing it?

It is important though that the solution would work similar to registering a `APP_INITIALIZER` due to the fact that `MyService` will be a npm package and the user should not have to register that callback themselves.

**Comment by pkozlowski-opensource** [comment]
It is currently not possible to inject `ApplicationRef` in `APP_INITIALIZER`s and adding back this posiibility is tracked in #9101
