### ISSUE TITLE
Disabling Auxiliary Routeroutlet After Parent Link Is Clicked

### ISSUE THREAD

**Issue by user592102** [angular/angular#8388]
Normally routeroutlet content disappears after parent link is clicked.  However, auxiliary routeroutlet tags remain in HTML page after parent link get triggered.  

Please look at following link for details.  Run the program below and click on chat hyperlink.  Then, click Home or Product Details link.  The Chat component supposed to be hidden after the click.  Instead, the component remains on the page.  

http://plnkr.co/edit/JsZbuR?p=preview

**Comment by zoechi** [comment]
Seems related to #5122 The router is currently rewritten anyway.

**Comment by user592102** [comment]
Thank you for your help.

**Comment by IgorMinar** [comment]
This issue was made obsolete by router v3: https://angularjs.blogspot.com/2016/06/improvements-coming-for-routing-in.html

If you believe this is not the case, please file a new issue updating the description to router v3. thank you!
