### ISSUE TITLE
ng-repeat within ng-repeat input model loses focus after input

### ISSUE THREAD

**Issue by zwhitchcox** [angular/angular#839]
Not sure if this is a bug, but [as you can see in the plnkr](http://plnkr.co/edit/XoMVzZmOTskALVnJTLAw), if you have an ng-model inside an ng-repeat, that is using a direct reference to the parent array in its ng-model, it loses focus upon input.

Is there a work around for this?

I need this to be able to edit the actual array in ng-repeat.

**Comment by pkozlowski-opensource** [comment]
Yes, `track by $index`: http://plnkr.co/edit/l5IRj2pwnvUvSMlnuQRk?p=preview

Check the "Tracking and Duplicates" section in https://docs.angularjs.org/api/ng/directive/ngRepeat for more info.

**Comment by zwhitchcox** [comment]
Sorry, to waste your time, but thank you so much!!
