### ISSUE TITLE
New router: Router link active for multiple links

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#8397]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here, see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. 

**Steps to reproduce and a minimal demo of the problem**

_Use https://plnkr.co or similar -- try this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5_

_What steps should we try in your demo to see the problem?_

**Current behavior**

Given the two routes

```ts
@Routes([
    { path: '/', component: Home },
    { path: '/test', component: Test }
])
```

```html
<a [routerLink]="['/']">Home</a>
<a [routerLink]="['/test']">Test</a>
```

If I'm on the `/test` route, the `router-link-active` class is added to the link for `/` and for `/test`

**Expected/desired behavior**

Active class should only apply to current route

**Other information**

cc: @vsavkin

**Comment by nareshbhatia** [comment]
I am running into the same issue.

**Comment by nickroberts** [comment]
This looks like when setting `isActive` in the `router_link.ts` file, when the `href` is empty (for `/`), the `this._router.urlTree.contains(tree)` function will always return true.

```
  private _updateTargetUrlAndHref(): void {
    let tree = this._router.createUrlTree(this._commands, this._routeSegment);
    if (isPresent(tree)) {
      this.href = this._router.serializeUrl(tree);
      this.isActive = this._router.urlTree.contains(tree);
    } else {
      this.isActive = false;
    }
  }
```

https://github.com/angular/angular/blob/9e3df8eefef86133c838a474498869c1e8ed2f53/modules/%40angular/router/src/directives/router_link.ts#L92-L100

**Comment by nickroberts** [comment]
This works, but, I don't think it is a good solution:

`this.isActive = this.href ? this._router.urlTree.contains(tree) : !this._router.urlTree._root.children.length;`

**Comment by jeserkin** [comment]
Any workaround for the bugy behavior?

**Comment by Namek** [comment]
My replacement:
```typescript
import {Directive, Input, Query, QueryList} from '@angular/core'
import {isBlank, isPresent} from '@angular/common/src/facade/lang'
import {Router, RouterUrlSerializer} from '@angular/router'
import {RouterLink} from '@angular/router/src/directives/router_link'


@Directive({
	selector: '[linkActive]',
	host: {
		'[class.active]': 'isRouteActive'
	}
})
export class LinkActive {
	@Input('linkActive') linkParams: any[]
	routerLink: RouterLink

	constructor(
		@Query(RouterLink) routerLinks: QueryList<RouterLink>,
		private router: Router,
		private urlSerializer: RouterUrlSerializer
	) {
		routerLinks.changes.subscribe((_) => {
			this.routerLink = routerLinks.first
		})
	}
	
	ngOnInit() {
		console.log(this.linkParams)
	}

	get isRouteActive() {
		if (!this.routerLink || !this.routerLink.href)
			return false
			
		let thisUrl = this.urlSerializer.parse(this.routerLink.href)
		let currentUrl = this.router.urlTree
		
		if (!currentUrl.contains(thisUrl))
			return false
		
		return !this.isExactCheck || thisUrl.contains(currentUrl)
	}
	
	private get isExactCheck(): boolean {
		return !isBlank(this.linkParams) && isPresent(this.linkParams['exact'])
			? this.linkParams['exact'] : true
	}
}
```

Usage:

```html
<ul class="product-tabs nav nav-tabs" role="tablist">
	<li class="nav-item">
		<a [routerLink]="['.']" class="nav-link" linkActive>
			<i class="fa fa-list-alt"></i> <b>Products</b>
		</a>
	</li>

	<li class="nav-item" *ngFor="let tab of productTabs">
		<a [routerLink]="['./', tab.pid]" class="nav-link" [linkActive]="{exact: false}">
			<i class="fa fa-inbox"></i> &nbsp;{{tab.name}}
		</a>
	</li>
</ul>
```

Reason behind this is that Product tab (the second `<li>`) contains nested tabs and the Product tab itself should be still active.

**Comment by justaniles** [comment]
Going off what @nickroberts said above about the issue being the way ```this.isActive``` is being set, would the correct functionality not be an equality operator for the urlTree?

```typescript
  private _updateTargetUrlAndHref(): void {
    let tree = this._router.createUrlTree(this._commands, this._routeSegment);
    if (isPresent(tree)) {
      this.href = this._router.serializeUrl(tree);
      this.isActive = this._router.urlTree.contains(tree); // should be: this._router.urlTree.equals(tree)
    } else {
      this.isActive = false;
    }
  }
```

This would require a change to the [segments.ts](https://github.com/angular/angular/blob/master/modules/%40angular/router/src/segments.ts) class, since the ```Tree``` class does not currently have an equality method.

I'm trying to determine if this functionality of the ```router-link-active``` class is intended. I did a quick test and the ```router-link-active``` would also be double applied in the case where you have two routes such as ```/home``` and ```/home/test```.

Maybe the Angular team was trying to give the ability to highlight the parent component (Home), in addition to the child component (Test) by applying the ```router-link-active``` to both?

**Comment by griter** [comment]
@brandonroberts If you get the new Angular router (https://github.com/angular/vladivostok) then you can use the _routerLinkActive_ directive. No further action is required. Here's the example:
```
<ul class="nav navbar-nav">
  <li [routerLinkActive]="['active']"><a [routerLink]="['/']">Home</a></li>
  <li [routerLinkActive]="['active']"><a [routerLink]="['/projects']">Projects</a></li>
</ul>
```

I used the latest version for testing: _3.0.0-alpha.7_

**Comment by brandonroberts** [comment]
Support for this has been added to the v3 router

**Comment by andresespinosapc** [comment]
It still doesn't work for me :(

**Comment by brandonroberts** [comment]
@andresespinosapc what's your issue?

**Comment by andresespinosapc** [comment]
If I understood well, this issue have seen solved in router v3. I have versión 3.0.0.beta.1 and when I click on a routerLink different than '/', the '/' link keeps active.

**Comment by brandonroberts** [comment]
@andresespinosapc you need to add an additional option to your routerLink. 

`[routerLinkActiveOptions]="{ exact: true }"`

Then your home route will only be active if you're on the exact route. The home route with an empty path will be a partial match on all routes

**Comment by andresespinosapc** [comment]
Thanks, it worked perfectly!

**Comment by vijender1256** [comment]
@brandonroberts If we have nested routes like below code has generated reports and adhoc reports under reports tab. when user clicks on reports tabs bootstrap dropdown whill show and we can click on adhoc or generated reports, how can we make Reports tab as active even though we are actually clicking on Adhoc reports. I dont want to high adhoc report dropdown menu but the tab Reports itself.

Below is the code:

 ` <ul class="nav navbar-nav ">
                <li><a id="cashierRiskProfile" routerLink="/cashierriskprofile" routerLinkActive="active">Cashier Risk Profile</a></li>
                <li><a id="exceptionDashboard" routerLink="/exceptionDashboard" routerLinkActive="active">Exception Dashboard</a></li>
                <li class="dropdown">
                    <a id="reports" class="dropdown-toggle" data-toggle="dropdown" routerLinkActive="active">
                        Reports
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a routerLink="/reportDetail">Generated Reports</a></li>
                        <li><a routerLink="/heroes">Adhoc Reports</a></li>
                    </ul>
                </li>
            </ul>`

**Comment by brandonroberts** [comment]
@vijender1256 the `routerLink` has to be a descendant element of the of where the `routerLinkActive` element is. If you need a more custom approach, the router has a `isActive` method. So you inject the `Router` into your component and use it in the html below

```html
<ul class="nav navbar-nav ">
           <li><a id="cashierRiskProfile" routerLink="/cashierriskprofile" routerLinkActive="active">Cashier Risk Profile</a></li>
           <li><a id="exceptionDashboard" routerLink="/exceptionDashboard" routerLinkActive="active">Exception Dashboard</a></li>
           <li class="dropdown">
                    <a id="reports" class="dropdown-toggle" data-toggle="dropdown" [class.active]="router.isActive('/reportDetail') || router.isActive('/heroes')">
                     Reports
                    <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a routerLink="/reportDetail">Generated Reports</a></li>
                        <li><a routerLink="/heroes">Adhoc Reports</a></li>
                    </ul>
                </li>
 </ul>

**Comment by vijender1256** [comment]
@brandonroberts thank you, I am getting below error:

![image](https://cloud.githubusercontent.com/assets/12258728/17822878/8878c2f8-6627-11e6-90ce-e191fcb7fe88.png)

**Comment by brandonroberts** [comment]
@vijender1256 you need to inject the `Router` into your component

```ts
import {Router} from '@angular/router';

constructor(private router: Router) {}
```

**Comment by kushalpandya** [comment]
I'm still facing this problem, here's my routing config.

```typescript
    { path: '', redirectTo: '/home', pathMatch: 'full' },
    {
        path: 'home',
        component: HomeComponent,
        children: [
            { path: '', component: ActivityStreamComponent },
            { path: 'recent', component: RecentActivityComponent },
            { path: 'archive', component: ArchiveActivityComponent }
        ]
    },
    { path: 'people', component: PeopleComponent },
    { path: 'about', component:AboutComponent }
```

And within template of `HomeComponent`, I'm having nav for child routes.

```html
<div class="pills-wrapper">
    <ul class="nav nav-pills">
        <li class="nav-item">
            <a routerLink="" class="nav-link" routerLinkActive="active" [routerLinkActiveOptions]="{exact: true}">Activity Stream</a>
        </li>
        <li class="nav-item">
            <a routerLink="recent" class="nav-link" routerLinkActive="active">Recent</a>
        </li>
        <li class="nav-item">
            <a routerLink="archive" class="nav-link" routerLinkActive="active">Archive</a>
        </li>
    </ul>
    <div class="tab-content">
        <router-outlet></router-outlet>
    </div>
</div>
```

And as I have mentioned `routerLinkActiveOptions` for first child route, it doesn't add `active` class at all, while remaining child routes work fine. Also, if I remove `routerLinkActiveOptions`, I get the same original problem of `active` class being applied on both blank route (which is `Activity Stream`) as well as any other route I navigate to.

Is it anything I'm missing here? I'm current using `@angular/router v3.0.0-rc.2`.

**Comment by brandonroberts** [comment]
@kushalpandya you should trying using the `home` path for your link instead of the empty path since its  a redirect.

**Comment by Rajdeepc** [comment]
routerLinkActive="active" in the anchor tag solves the problem in v 3

**Comment by Ashokkumar1995** [comment]
<li><a routerLink="side" routerLinkActive="active" [routerLinkActiveOptions]="{exact: true}">Test</a></li>
      <li><a routerLink="sideLibrary" routerLinkActive="active">Library</a></li>
      <li><a routerLink="sideReport" routerLinkActive="active">Report</a></li>
i have added routerLinkActiveOptions but i still didnt get active change in tab

**Comment by brandonroberts** [comment]
@Ashokkumar1995 the "active" class should be on the `li` element and not the `a` element

**Comment by grungondola** [comment]
I'm hitting this same issue. @brandonroberts according to the documentation here https://angular.io/api/router/RouterLinkActive the RouterLinkActive directive goes on the anchor tag with the RouterLink directive.

I do not run into this issue on initial load or when the user navigates with the navbar, but when I manually navigate in the code, it doesn't update what is active. I change the links based on a drop-down and then navigate to the "Home" link of whatever the selection is, and it doesn't mark that as active in the DOM. I think this may be because of how the lifecycle hits, trying to mark the active link before updating the links in the ngFor that I have in the navbar.

**Comment by brandonroberts** [comment]
@grungondola the router guide states that it can be on the parent elemeny also.

```
The RouterLinkActive directive on each anchor tag helps visually distinguish the anchor for the currently selected "active" route. The router adds the active CSS class to the element when the associated RouterLink becomes active. You can add this directive to the anchor or to its parent element.
```

**Comment by vidhyasgr** [comment]
<ul>
        <li>
          <a routerLink="search" >Find Match</a>
        </li>
        <li><a routerLink="chat">Messages</a></li>
        <li><a routerLink="basic">Community</a></li>

      </ul>


Here is my router code. I have configured everything correctly like in document, but the problem is whenever i click the routerLink, the new page is router, but the old page also there. It goes on adding new elements (components).

**Comment by vidhyasgr** [comment]
Why angular 4 app is not working in Safari Version 9.1.3 ? 
Please help me to fix it.!!!

I got this exception in console.

**Exceptions**
SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.
TypeError: null is not an object (evaluating 'element.addEventListener')

**Comment by roopkt** [comment]
Hi Can I match partially and make one link active ? In below example profile link should be active when I go to any user. 
```
      <li [routerLinkActive]="['active']" [routerLinkActiveOptions]="{exact:false}">
          <a [routerLink]="['/user',1]"> Profile</a>
        </li>
```
Here on click I want to take it to user one but if via routing manually from browser I happened to go to `user/3` I still want to active profile link.  I tried doing `exact:false` it is still not active when i go to `user/3`

**Comment by petrskalicka** [comment]
I use this simple CSS solution:

`.active:not([href='/']) {background-color: blue}`

**Comment by liamlaverty** [comment]
> I use this simple CSS solution:
> 
> `.active:not([href='/']) {background-color: blue}`

If you've got the routerLink on an element that doesn't have `href` then you could also do 

`&.active:not([ng-reflect-router-link='/,/']) {background-color: blue}`

**Comment by jsbimra** [comment]
Why they don't build simple things simple? why do they require to make it complex with so much of re-writing of codes again to fix or to use small things in the apps? I think new frameworks forgot the basics stuffs to tackle easily, in a process of creating robust frameworks which end with the huge threads of comments, isn't it?

**Comment by oscarterce** [comment]
In routing.module.ts adding:
const routes: Routes = [
    {
        path: '',
        component: HomeComponent
    },
    {
        path: 'home',
        component: HomeComponent
    },
....
