### ISSUE TITLE
requestAnimationFrame returns ZoneTask instead of a handle

### ISSUE THREAD

**Issue by artemverbo** [angular/angular#8401]
Hi there!

**requestAnimationFrame** called from components (both via window directly and from DOM adapter) returns **ZoneTask** object instead of a handle id, which is not allowing to call cancelAnimationFrame with it. I managed to do it via `DOM.cancelAnimationFrame(this.requestAnimationFrameHandler.data.handleId);` but don't think that's correct usage.

Sorry in advance if that's expected behaviour or maybe me doing something wrong.

Angular 2 Beta 17 and zone.js 0.6.12

Thanks!

**Comment by gdi2290** [comment]
you can run requestAnimationFrame outside of zone.js to get the normal behavior
```typescript
class App {
  constructor(public ngZone: NgZone) {

    this.ngZone.runOutsideAngular(() => {

      requestAnimationFrame(() => {
      });

    });
  }
}
```

**Comment by laco0416** [comment]
To use rAF we have to think about zone? I think that's not good. 

Zone should save the code, `let handleId = requestAnimationFrame(fn);` and `cancelAnimationFrame(handleId)`

And maybe this is an issue which should be filed in https://github.com/angular/zone.js/issues

**Comment by pkozlowski-opensource** [comment]
Closing since this belongs to the zone repo and is already opened in there.
