### ISSUE TITLE
New router: Router needs to be injected to do initial navigation

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#8409]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here, see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. 

**Steps to reproduce and a minimal demo of the problem**

_Use https://plnkr.co or similar -- try this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5_

_What steps should we try in your demo to see the problem?_

**Current behavior**

If you have routes setup without any router links and you don't inject the router, initial navigation does not occur.

**Expected/desired behavior**

Once routes are defined, and an outlet is added to the template, navigation should occur on initial page load.

**Other information**

cc: @vsavkin

**Comment by todoubaba** [comment]
Temp workaround: put an empty  reouterLink in template
```typescript
@Component({
    ...
    template: `<a [routerLink]="['/']"></a><router-outlet></router-outlet>`
    directives: [ROUTER_DIRECTIVES],
})

**Comment by thvu** [comment]
I had this issue when setting up the AppComponent in the way upgrading the app to Angular 2 rc1. Its inline template contains only a router outlet and root component at path '/' did not show up. Adding empty routerLink did not work as there is an exception:
```js
browser_adapter.ts:78 TypeError: s.charCodeAt is not a function
    at Function.StringWrapper.charCodeAt (http://localhost:5555/node_modules/@angular/compiler/src/facade/lang.js:158:63)
    at _HtmlTokenizer._advance (http://localhost:5555/node_modules/@angular/compiler/src/html_lexer.js:244:77)
    at new _HtmlTokenizer (http://localhost:5555/node_modules/@angular/compiler/src/html_lexer.js:132:14)
    at Object.tokenizeHtml (http://localhost:5555/node_modules/@angular/compiler/src/html_lexer.js:62:12)
    at HtmlParser.parse (http://localhost:5555/node_modules/@angular/compiler/src/html_parser.js:39:44)
    at DirectiveNormalizer.normalizeLoadedTemplate (http://localhost:5555/node_modules/@angular/compiler/src/directive_normalizer.js:60:51)
    at DirectiveNormalizer.normalizeTemplate (http://localhost:5555/node_modules/@angular/compiler/src/directive_normalizer.js:47:56)
    at DirectiveNormalizer.normalizeDirective (http://localhost:5555/node_modules/@angular/compiler/src/directive_normalizer.js:24:21)
    at eval (http://localhost:5555/node_modules/@angular/compiler/src/runtime_compiler.js:60:165)
    at Array.map (native)
```
It seems to be a problem with template parser. Then I changed to template file with same content and it worked!

**Comment by webtrix** [comment]
This only solves auto routing for the `"/"` path, but since the `useAsDefault` option isn't available anymore, if one would want to use `"/home"` as the default route, you need to use `ngOnInit()` ?

Doesn't really seem to be a nice solution tbh.

**Comment by ps2goat** [comment]
+1

**Comment by ps2goat** [comment]
nested routers don't seem to work, either.  We were trying to upgrade from beta.8, and it doesn't even seem like we can use the @angular/router-deprecated library because so much of the functionality has regressed.

**Comment by brandonroberts** [comment]
@ps2goat the new router is still a work in progress. The deprecated router should still work for the time being.

**Comment by ps2goat** [comment]
It was not working for us.  Default routes seemed to be ignored and the
`subscribe` event on the router did not seem to be firing properly.

**Comment by brandonroberts** [comment]
@ps2goat can you reproduce? You can only subscribe to the root router for updates, so if you injected the router in a child route, the subscribe wouldn't fire anything.

**Comment by findjonmos** [comment]
Hey all I am having the same issue but I found a fix that doesn't require you to add in a routerLink

```
import { Component } from '@angular/core';
import { TimerComponent } from './+timer';
import { Routes , ROUTER_DIRECTIVES, ROUTER_PROVIDERS, Router} from '@angular/router';
import { ExplosionComponent } from './+explosion';

@Component({
  moduleId: module.id,
  selector: 'pomodoro-app',
  templateUrl: 'pomodoro.component.html',
  styleUrls: ['pomodoro.component.css'],
  directives: [ROUTER_DIRECTIVES],
  providers: [ROUTER_PROVIDERS]
})
@Routes([
  {path: '/timer', component: TimerComponent},
  {path: '/explosion', component: ExplosionComponent}
])
export class PomodoroAppComponent {
  title = 'pomodoro works!';

  constructor(private router: Router){}
}
```

The 3rd import statement at the top will be missing 'Router' when you use the cli to generate a route for the first time, and the constructor statement in the exported class also doesn't get created.

If you manually add these things to your main app component then any subsequent route generations with the cli will work...I tested this by adding a silly route named explosion.

Hope this helps, not sure if I should drop this message somewhere else rather than here?

**Comment by Priyanka1103** [comment]
Thanks @findjonmos . Your solution works.

**Comment by MyNameIsURL** [comment]
@findjonmos  Thanks, good catch! Your solution worked.  Adding the missing Router import and adding the constructor solved the issue.

**Comment by brandonroberts** [comment]
Support for this has been added to the v3 router

**Comment by jrmcdona** [comment]
I have this issue in Angular 4.0

Injecting Router or embedding empty route does not work for me.

https://stackoverflow.com/questions/45849706/is-routerlink-required
