### ISSUE TITLE
New router: Improve API for retrieving parent information from child

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#8411]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here, see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. 

**Steps to reproduce and a minimal demo of the problem**

_Use https://plnkr.co or similar -- try this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5_

_What steps should we try in your demo to see the problem?_

**Current behavior**

Currently to retrieve the parent parameter for a route, you have to use the route tree along with the current segment

```ts
  routerOnActivate(
    current: RouteSegment,
    prev?: RouteSegment,
    currTree?: RouteTree,
    prevTree?: RouteTree
  ) {
    let parentId = currTree.parent(current).getParam('id');
  }
```

**Expected/desired behavior**

A less verbose way to get a parent parameter.

```ts
   let parentId = current.parent().getParam('id');
```

**Other information**

cc: @vsavkin

**Comment by cquillen2003** [comment]
Will this new parent() method be chainable to grab params further up the component tree?

Something like this:

let grandParentId = current.parent().parent().getParam('id');
