### ISSUE TITLE
[compiler] Can't bind to 'textContent' since it isn't a known native property 

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#8413]
Updating from beta.17 to rc.0, `textContent` is no longer recognized as a native property.

```
Failed: Uncaught (in promise): Template parse errors:
	Can't bind to 'textContent' since it isn't a known native property ("
	<p [ERROR ->][textContent]="user.name"></p>
```

**Comment by IEvangelist** [comment]
We encountered the very same issue :+1:

**Comment by zoechi** [comment]
Repo https://plnkr.co/edit/nvcN7nZedIkHOWDUFc65?p=preview

**Comment by IEvangelist** [comment]
@zoechi, when I visit that plunker - here is the console 

![image](https://cloud.githubusercontent.com/assets/7679720/15081396/7099a66c-1388-11e6-97eb-ae84dfb9ecdf.png)

**Comment by zoechi** [comment]
@IEvangelist it's just confirmation. I tried it in Plunker, could reproduce it and thought that I can as well post the Plunker link here in case someone else wants to check it.

**Comment by kylecordes** [comment]
Same issue here. From various articles around the web, it seems textContent is preferable to innerText for performance reasons, especially on Webkit-based browsers. I wonder why the latest Angular has forgotten about its validity as a known native property.

**Comment by kylecordes** [comment]
A question closely related to this issue... I wonder how we can tell Angular "trust me, there is a property by the name I am using" in the general case, as well as for this specific case.

**Comment by pkozlowski-opensource** [comment]
Yeh, this is a valid bug, I suspect this is due to the fact that we've got a schema now that is "static" and not taken from the browser's runtime properties.

**Comment by kylecordes** [comment]
With the amazing pace of commits going in angular/angular nowadays, it would be so nice to include this and other similar small fixes in the flow.

**Comment by mprobst** [comment]
Because I was asked – this is not due to security concern, binding `textContent` should be fine as it is just the inert text of an element (even binding it for `<script>` would be OK). CC @rjamet.

**Comment by rjamet** [comment]
Yep, that looks good security-wise.

**Comment by LimarenkoDenis** [comment]
try to use Input fron @angular/core
https://angular.io/docs/ts/latest/cookbook/component-communication.html
