### ISSUE TITLE
RouteParams not working in root component

### ISSUE THREAD

**Issue by dheran** [angular/angular#8415]
`bootstrap(AppComponent, [ROUTER_PROVIDERS]);`

```
@Component({
    template: `
    <h1>Hello</h1>`
})
@RouteConfig([
  {path: '/', name: 'Root', component: Root},
  {path: '/other', name: 'Other', component: Other},
])
export class AppComponent {
  constructor(routeParams: RouteParams) {
    console.log(routeParams);
  }
}
```

While loading the page I'm getting following error,

> EXCEPTION: No provider for RouteParams! (AppComponent -> RouteParams)
> VM645 angular2.dev.js:23925 EXCEPTION: No provider for RouteParams! (AppComponent -> RouteParams)BrowserDomAdapter.logError @ VM645 angular2.dev.js:23925BrowserDomAdapter.logGroup @ VM645 angular2.dev.js:23936ExceptionHandler.call @ VM645 angular2.dev.js:1320(anonymous function) @ VM645 angular2.dev.js:12995ZoneDelegate.invoke @ VM626 angular2-polyfills.js:390onInvoke @ VM645 angular2.dev.js:2126ZoneDelegate.invoke @ VM626 angular2-polyfills.js:389Zone.run @ VM626 angular2-polyfills.js:283(anonymous function) @ VM626 angular2-polyfills.js:635ZoneDelegate.invokeTask @ VM626 angular2-polyfills.js:423onInvokeTask @ VM645 angular2.dev.js:2118ZoneDelegate.invokeTask @ VM626 angular2-polyfills.js:422Zone.runTask @ VM626 angular2-polyfills.js:320drainMicroTaskQueue @ VM626 angular2-polyfills.js:541ZoneTask.invoke @ VM626 angular2-polyfills.js:493
> VM649 main.ts!transpiled:16 NoProviderError {message: "No provider for RouteParams! (AppComponent -> RouteParams)", stack: "Error: DI Exception↵    at NoProviderError.BaseExc…larjs.org/2.0.0-beta.15/angular2.dev.js:11788:19)", keys: Array[2], injectors: Array[2]}(anonymous function) @ VM649 main.ts!transpiled:16ZoneDelegate.invoke @ VM626 angular2-polyfills.js:390Zone.run @ VM626 angular2-polyfills.js:283(anonymous function) @ VM626 angular2-polyfills.js:635ZoneDelegate.invokeTask @ VM626 angular2-polyfills.js:423Zone.runTask @ VM626 angular2-polyfills.js:320drainMicroTaskQueue @ VM626 angular2-polyfills.js:541ZoneTask.invoke @ VM626 angular2-polyfills.js:493

**Comment by ericmartinezr** [comment]
RouteParams exist only for routed components, the same goes for RouteData, root component is not a route component. Besides that the old new router has been deprecated, use the new new router.

**Comment by ManuelRauber** [comment]
@ericmartinezr When using the "new new router" -> How can we get the "routeParams"? Within the documentation there is nothing similar. Any hint? Thanks!

**Comment by ManuelRauber** [comment]
Ok, I just found it out myself:

```
// App Component
@Routes([
    new Route({ path: 'somePath/:id', component: SomeComponent })
])
@Component({
    // snipped
})
export class AppComponent {}

// Some other component

import {OnActivate, RouteSegment} from '@angular/router';

export class SomeComponent implements OnActivate {
    private _idToLoad: number;

    routerOnActivate(current: RouteSegment) {
        this._idToLoad = parseInt(current.getParam('id'));
    }
}
```

**Comment by bennylut** [comment]
@ericmartinezr is there any documentation available for the new-new router? the site's developers guide still uses the router_deprecated package, the API section for the new router is filled with "Not yet documented" phrases, and finally, the document referenced in the changelog about the new router seems like it has many unresolved issues. Should we even attempt to move to the new-new router or maybe it is still not fully implemented in rc0?

**Comment by ericmartinezr** [comment]
@bennylut the tutorial docs are being rewritten, see https://github.com/angular/angular.io/pull/1268. On the other hand the API docs are not yet completed, and hopefull they will be in a not so far future. Sadly the new router was written against the clock (ng-conf *cough*), so we will have to wait till they give the new new router some love. So far your best documentation is the source code.

**Comment by tapas4java** [comment]
Check word's PR [#1268](https://github.com/angular/angular.io/pull/1268)
for new router doc.

**Comment by bennylut** [comment]
@ericmartinezr thanks, It is fully understandable that the documentation is not in its top shape for a release candidate - I just wasn't sure if I should wait with the migration to the new router. I understand that it is in a shape that it can be already be used in rc0 - thanks.  I will start migrating soon.

@tapas4java thank you too - It will be useful!

**Comment by dheran** [comment]
guys is there any way to get the routeparams in root component?

**Comment by dreambo8563** [comment]
@ManuelRauber the example of new router http://plnkr.co/edit/?p=preview, maybe you need it.
there is the way to pass the data when navigate

`  this.router.navigate([`/heroes`, {id: heroId, foo: 'foo'}]);` I didn't try it locally, but I thought maybe the data will be displayed in the url.

I still didn't find a way to pass data like 'RouteParams' (won't shown in url)

**Comment by ManuelRauber** [comment]
@dreambo8563 Thx! It's the same as I mentioned in my comment above. Glad to see, that it is the currently correct way of doing it. :)

**Comment by IgorMinar** [comment]
This issue was made obsolete by router v3: https://angularjs.blogspot.com/2016/06/improvements-coming-for-routing-in.html

If you believe this is not the case, please file a new issue updating the description to router v3. thank you!
