### ISSUE TITLE
APP_BASE_HREF does no longer exist in ES5/ES6 since beta 16

### ISSUE THREAD

**Issue by SmaugTheGreat** [angular/angular#8419]
`ng.core.provide(ng.common.APP_BASE_HREF, {useValue: '/'})` gives the error `Error: Token must be defined!`
In fact `ng.common.APP_BASE_HREF` is undefined and so are `ng.platform.APP_BASE_HREF` and `ng.common.platform.APP_BASE_HREF` and `ng.router.APP_BASE_HREF` and `ng.platform.common.APP_BASE_HREF`.

Furthermore, 

    function findBasehref(obj) {
        if(typeof(obj) != "object" || obj == null)
            return;
        if(obj.APP_BASE_HREF) {
            console.log("FOUND IT!!");
        }
        for(let s in obj) {
            findBasehref(obj[s]);
        }
    }

    findBasehref(ng);

doesn't find it either.

**Comment by ericmartinezr** [comment]
There's a PR for that https://github.com/angular/angular/pull/8300

**Comment by rixrix** [comment]
hi,
just passing by as I'm tweaking an app for rc1 and that particular pr mentioned by @ericmartinezr was already closed, should be closed as well ? tnx

**Comment by wesleycho** [comment]
I don't think this is valid any more, everything is being exported as far as I could tell from the distribution version.
