### ISSUE TITLE
New Router : Routes order throw "Component X does not have route configuration"

### ISSUE THREAD

**Issue by ericmartinezr** [angular/angular#8420]
Having

```typescript
@Routes([
  {path : 'main', component : Main},
	{path : 'main/:param', component: Main}
])
```
And a router link like
```typescript
<a [routerLink]="['/main', {param : 'some value'}]">Go to main/:param<a
```
Will throw 
```
Uncaught (in promise): Component 'Main' does not have route configuration
```
While changing the order of the Routes makes everything to work correctly
```typescript
@Routes([
  {path : 'main/:param', component: Main},
  {path : 'main', component : Main},
])
```
This seems to be related to https://github.com/angular/angular/issues/8414 or both are victim of the same issue, but I don't think it is a dup (if I'm wrong close it).

Here's a plnkr with RC.0 reproducing the issue http://plnkr.co/edit/DGifBYPfr7N0fRrFwrb2?p=preview

cc: @vsavkin

**Comment by brandonroberts** [comment]
Params for router link aren't in an object anymore.

```html
<a [routerLink]="['/main', 'some value']">Go to main/:param</a>
```

**Comment by ericmartinezr** [comment]
@brandonroberts really? How come then it does work by changing the order? How does the router know if the second parameter it is a path or a parameter? What am I missing :worried:?

**Comment by brandonroberts** [comment]
Could be a bug. The router essentially puts together the link based on the items in the array. So if you're route path has a parameter, you define it as an item in the array instead of an object. The object is for query/matrix params that are optional to the path.

**Comment by Krisa** [comment]
that's a bit confusing if it really works this way. I have the feeling that what stands in the [change log](https://docs.google.com/document/d/1WLSNV3V1AKdwLwRiLuN7JqbPBKQ_S5quRlcT5LPIldw/edit#) is different, but I can't get working the various examples of this document.

**Comment by ericmartinezr** [comment]
You guys are right, I forgot to read the document searchng for this

>[‘/app’, ‘HomeCmp’]
[‘/app’, [[‘HomeCmp’]] ] // same as above
[‘/app’, [[‘HomeCmp’], [‘ConfirmationCmp’]] ] 
[‘/app’, ‘ModelCmp’] // navigate to child route in the right outlet
[‘/app’, ‘!right’] // remove right outlet

So I don't know, I'll leave it open to see what Victor has to say.

Thank you both!

**Comment by reecebradley** [comment]
I have a similar error that showed up after upgrading from old RouteConfig to Routes..
ArticleComponent
```js
@Component({
    selector:'blog',
    template:`
        <h1>My Blog</h1>
        <div>
        <router-outlet></router-outlet>
        </div>
    `,
    directives: [ ROUTER_DIRECTIVES ]
})
@Routes([
    {path: '/:year',
        component: ArticleComponent
    },
    {path: '/:year/:month',
        component: ArticleComponent
    },
    {path: '/:year/:month/:day',
        component: ArticleComponent
    },
    {path: '/:year/:month/:day/:title',
        component: ArticleComponent
    }
])
export class BlogComponent {
    constructor() {
        
    }
}
```
Typing this URL in the browser:
`http://localhost:8080/blog/2016`
Works fine, but typing this in the browser:
`http://localhost:8080/blog/2016/01`
...will throw:

```
browser_adapter.ts:78 Error: Uncaught (in promise): Component 'ArticleComponent' does not have route configuration
    at resolvePromise (zone.js:538)
    at resolvePromise (zone.js:523)
    at zone.js:571
    at ZoneDelegate.invokeTask (zone.js:356)
    at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (ng_zone_impl.ts:56)
    at ZoneDelegate.invokeTask (zone.js:355)
    at Zone.runTask (zone.js:256)
    at drainMicroTaskQueue (zone.js:474)
    at XMLHttpRequest.ZoneTask.invoke (zone.js:426)
```
Note: I'm not using `[routerLink]`, just typing it in the browser. `/:year` works but `/:year/:month` does not, or anything after month.

Perhaps this is the same situation, just wanted to point out nested params fail as well.

**Comment by Cody-Nicholson** [comment]
It does appear as though order matters when declaring Routes.

App Routes (parent component):
```
@Routes([
    {
        path: '/manage',
        component: ManageComponent,
    },
])
```

Manage Component (child): 
```typescript
@Component({    
   selector: 'manage',
   template: `
        <sidebar class="sidebar"></sidebar>
        <div class="manage-main">
            <router-outlet></router-outlet>
        </div>
  `,
    directives: [ROUTER_DIRECTIVES, SidebarComponent],
    providers: [
        PublisherService,
    ]
})
```
Manage Routes A:
```typescript
@Routes([
   {
        path: '/publishers',
        component: PublisherListComponent,
    },
    {
        path: '/publishers/:pub',
        component: PublisherDetailsComponent,
    },
])
```
Manage B:
```typescript
@Routes([
   {
        path: '/publishers/:pub',
        component: PublisherDetailsComponent,
    },
   {
        path: '/publishers',
        component: PublisherListComponent,
    }
])
```

As you can guess, Route B works and Route A does not.

`EXCEPTION: Error: Uncaught (in promise): Component 'PublisherListComponent' does not have route configuration`

This issue occurs both when trying to navigate using a direct url link `/manage/publishers/789` and router link `<a [routerLink]="['/manage/publishers', publisherId]">
              {{publisherId}}
            </a>`

**Comment by GuillaumeUnice** [comment]
I have the same issue with the following error : 

`EXCEPTION: Error: Uncaught (in promise): TypeError: Cannot convert undefined or null to object`

my main App component : 
`import {Component, OnInit} from '@angular/core';
import { Routes, Router, ROUTER_DIRECTIVES, ROUTER_PROVIDERS} from '@angular/router';


import { MainNavComponent } from './shared/main-nav/main-nav.component';
import { FruitComponent } from './fruit/fruit.component';
import { DessertComponent } from './dessert/dessert.component';
import { HomeComponent } from './home/home.component';

@Component({
    selector: 'my-app',
    template: `
        <header>
            <ul>
                <li><a [routerLink]="['/home']">Home</a></li>
                <li><a [routerLink]="['/fruit']">Fruit</a></li>
                <li><a [routerLink]="['/dessert']">Dessert</a></li>
             </ul>
        </header>
        <h1>Angular 2 Routing</h1>
        <router-outlet></router-outlet>
    `,
    providers: [ROUTER_PROVIDERS], 
    directives: [ROUTER_DIRECTIVES, MainNavComponent]
})
@Routes([
  {path: '*',      component: HomeComponent},
  {path: '/fruit',      component: FruitComponent},
  {path: '/dessert',      component: DessertComponent}
])
export class AppComponent implements OnInit {

    constructor(private router: Router) {}

    ngOnInit() {
        this.router.navigate(['/home']);
    }
 }`

**Comment by nellboy** [comment]
Greetings Angularinos! - I had a similar issue,  then renamed "*" to "/" and as if by magic it worked ...

**Comment by sharpmachine** [comment]
I'm having the same issue. 

If I go to `/subject/create` and @Routes are as follows, I get the proceeding error:
`
@Routes([
  { path: '/:id', component: SubjectComponent },
  { path: '/create', component: SubjectDetailComponent }
])
`

`zone.js:101 GET http://localhost:3000/subjects/NaN 404 (Not Found)scheduleTask @ zone.js:101ZoneDelegate.scheduleTask @ zone.js:336Zone.scheduleMacroTask @ zone.js:273(anonymous function) @ zone.js:122send @ VM167968:3(anonymous function) @ xhr_backend.js:68Observable.subscribe @ Observable.js:52Observable._subscribe @ Observable.js:109MapOperator.call @ map.js:54Observable.subscribe @ Observable.js:52SubjectComponent.getSubject @ subject.component.js:28SubjectComponent.ngOnInit @ subject.component.js:22_View_SubjectComponent_Host0.detectChangesInternal @ SubjectComponent_Host.template.js:34AppView.detectChanges @ view.js:200DebugAppView.detectChanges @ view.js:289AppView.detectContentChildrenChanges @ view.js:215AppView.detectChangesInternal @ view.js:210AppView.detectChanges @ view.js:200DebugAppView.detectChanges @ view.js:289AppView.detectViewChildrenChanges @ view.js:220_View_SubjectsComponent_Host0.detectChangesInternal @ SubjectsComponent_Host.template.js:30AppView.detectChanges @ view.js:200DebugAppView.detectChanges @ view.js:289AppView.detectContentChildrenChanges @ view.js:215_View_CaseManagerAppComponent0.detectChangesInternal @ CaseManagerAppComponent.template.js:79AppView.detectChanges @ view.js:200DebugAppView.detectChanges @ view.js:289AppView.detectViewChildrenChanges @ view.js:220_View_CaseManagerAppComponent_Host0.detectChangesInternal @ CaseManagerAppComponent_Host.template.js:30AppView.detectChanges @ view.js:200DebugAppView.detectChanges @ view.js:289ViewRef_.detectChanges @ view_ref.js:119(anonymous function) @ application_ref.js:361ApplicationRef_.tick @ application_ref.js:361(anonymous function) @ application_ref.js:267ZoneDelegate.invoke @ zone.js:323NgZoneImpl.inner.inner.fork.onInvoke @ ng_zone_impl.js:45ZoneDelegate.invoke @ zone.js:322Zone.run @ zone.js:216NgZoneImpl.runInner @ ng_zone_impl.js:76NgZone.run @ ng_zone.js:223(anonymous function) @ application_ref.js:267schedulerFn @ async.js:123SafeSubscriber.__tryOrUnsub @ Subscriber.js:225SafeSubscriber.next @ Subscriber.js:174Subscriber._next @ Subscriber.js:124Subscriber.next @ Subscriber.js:88Subject._finalNext @ Subject.js:128Subject._next @ Subject.js:120Subject.next @ Subject.js:77EventEmitter.emit @ async.js:112NgZone._checkStable @ ng_zone.js:141NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.setMicrotask @ ng_zone.js:117NgZoneImpl.inner.inner.fork.onHasTask @ ng_zone_impl.js:57ZoneDelegate.hasTask @ zone.js:382ZoneDelegate._updateTaskCount @ zone.js:399ZoneDelegate.invokeTask @ zone.js:360Zone.runTask @ zone.js:256drainMicroTaskQueue @ zone.js:474ZoneTask.invoke @ zone.js:426
browser_adapter.js:86 EXCEPTION: [object Object]
`

However if I define the routes in the following order, it works as expect:
`
@Routes([
  { path: '/create', component: SubjectDetailComponent },
  { path: '/:id', component: SubjectComponent }
])
`
