### ISSUE TITLE
rc-0: Tour of Heroes list fails to re-render on back-navigation

### ISSUE THREAD

**Issue by CaptainCodeman** [angular/angular#8421]
**Steps to reproduce and a minimal demo of the problem**

Go to https://angular.io/docs/ts/latest/tutorial/
Click "run the live example"
Click a hero in the list
Click the browser back button or the 'back' link

**Current behavior**
List of heroes is empty

**Expected/desired behavior**
List of heroes is rendered

(tested with Chrome)

**Comment by pkozlowski-opensource** [comment]
Please open in https://github.com/angular/angular.io where the documentation lives.
