### ISSUE TITLE
Scoped NPM Packages not available

### ISSUE THREAD

**Issue by MarcelCremer** [angular/angular#8423]
Hello everyone,

I've just tried to receive angularjs2 packages via npm.

**Current behavior**
NPM won't find the package @angular/core according to https://github.com/angular/angular/blob/master/CHANGELOG.md:

![image](https://cloud.githubusercontent.com/assets/6123724/14989228/185b201c-1157-11e6-90ca-d431b2cd3413.png)

**Expected/desired behavior**
NPM should find the package :)

**Other information**
I've attached the npm-debug log if it's helpful:

[npm-debug.zip](https://github.com/angular/angular/files/247246/npm-debug.zip)

I don't know if this one is a bug or I am doing something wrong, but any help is appreciated.

Thank you very much and best regards
Marcel

**Comment by ericmartinezr** [comment]
Upgrade your node/npm version (use nvm in case you need different versions on your env). I'm currently on node v5.10.1 and npm v.3.8.6

**Comment by MarcelCremer** [comment]
Thank you for your help, it looks like I had two versions installed - one manually and one by chocolatey. After installing the latest node and npm it works now.

Also: npm install npm -g does not seem to work under windows. If someone else has the problem, try 
downloading the latest Installer and install it over the currently installed version.
