### ISSUE TITLE
Rename $event to event

### ISSUE THREAD

**Issue by felixfbecker** [angular/angular#8425]
I am so happy that Angular 2 does not prefix everything anymore with `$`. That was extremely annoying and unneeded in Angular 1 (`$scope`, `$element`, `$scope.$apply()`, `$http` and everyone who followed: `$mdDialog`, `$stateProvider`, ...). It comes from the legacy jQuery world were everything with a $ was cool.

In Angular 2 it is now finally just `Http`, `ElementRef`, etc. Except in ___one___ case, and that is `$event`. Is there any reason why this is prefixed with a dollar?

When you assign a native DOM event handler like `onclick="event.preventDefault()"`, the event object is available under `event`. When I do the same in Angular, I would expect the same: `(click)="event.preventDefault()"`. Why `$event`? Please consider changing this (at least allow `event` without dollar and change the docs) before Angular 2 goes into RC.

**Comment by schippie** [comment]
Agree seems silly that we still need to use the `$` sign in one place. 

Maybe it has something to do with the window.event ? https://developer.mozilla.org/en-US/docs/Web/API/Window/event that is implemented in chrome and ie/edge.

I am kinda curious if changing https://github.com/angular/angular/blob/bb8976608db93b9ff90a71187608a4390cbd7a07/modules/%40angular/compiler/src/view_compiler/constants.ts#L70 is enough to change the variable name.

**Comment by pkozlowski-opensource** [comment]
`event` would be way to easy to clash with other vars in a template. Not to mention that it would be a massive breaking change at this point... Thnx for the suggestion but we are going to pas on it right now.

**Comment by felixfbecker** [comment]
> we are going to pas on it right now

if you are not changing it before stable, you will never change it, just sayin. The change will only get harder. So it will be $$$ bling bling forever.

I don't actually think it is _that_ likely to have a template variable named `event` that _also happens to be used inside an event handler_. Even if you have a template variable called `event` event handlers are normally just a function call like `changeValue($event.target.value)` etc.

It should be possible to simply add `event` in addition to `$event`, deprecate `$event` and change the docs so it is at least _possible_ and _recommended_ to write Angular code without dollars. If you want to be _really_ careful, you could not do that if there is a template variable for `event`. But honestly, you just comepletely replaced the router for RC with one that is totally not BC, misses a lot of features and published the working router under `router-deprecated`. After this, I think developers can take (even welcome) a small change like this ;)
