### ISSUE TITLE
rc-0: Extending router-outlet with deprecated router fails silently

### ISSUE THREAD

**Issue by CaptainCodeman** [angular/angular#8427]
**Steps to reproduce and a minimal demo of the problem**
See plunker:
http://plnkr.co/edit/wiyXdxEMQ2hV8wI9frwn?p=preview

**Current behavior**
No `<custom-router>` outlet rendered

**Expected/desired behavior**
`<custom-router>` outlet is rendered

**Other information**
This is commonly used for adding security to routes and worked upto latest RC-0
No error messages are displayed, the code fails silently and the component is never instantiated

**Comment by PinkTiu** [comment]
To fix your problem you can do this: 
In your `app.component.ts` do another import `import {RouterOutlet} from '@angular/router-deprecated';` rename `<custom-outlet></custom-outlet>` to `<router-outlet></router-outlet>`. Change your directives to `  directives: [ROUTER_DIRECTIVES.filter(direc => direc != RouterOutlet), CustomOutlet]`

For me this works.

**Comment by CaptainCodeman** [comment]
Thanks @PinkTiu 

I tried it and It *kind* of works, in that the component gets instantiated, but unfortunately none of the extra services my app uses are injected into it - like it sees it as RouterOutlet and nothing more.

I'll have a play around with it and see if I can solve the DI part.

**Comment by blacksonic** [comment]
If you don't modify the name of the selector it works for me: https://github.com/blacksonic/angular2-esnext-starter/blob/master/client/app/auth/directives/router_outlet.js

**Comment by CaptainCodeman** [comment]
Thanks @blacksonic that approach seems to do the trick - using the same selector and also adding the `static get parameters()` method

**Comment by blacksonic** [comment]
The ```static get parameters()``` is only necessary for Javascript as far as i know, Typescript should work with parameter decorators.

**Comment by CaptainCodeman** [comment]
I'm using typescript but needed that as well.

**Comment by robwormald** [comment]
Tracked this down in core, working on a PR to fix.

**Comment by ghaiat** [comment]
i tried with RC1 and i m still facing the same issue : silent fail...

**Comment by Kevin-K** [comment]
Updated from RC0 -> RC1: 
When extending `RouterOutlet` without changing the selector name works for me.
I was able to remove the `static get parameters()` and still have my services DI work as expected.

**Comment by CaptainCodeman** [comment]
It didn't work for me with a custom name so IMO it's still not really fixed properly - you could envisage a situation where you have a standard and custom outlet in a page which currently wouldn't be possible.

**Comment by benharrell** [comment]
was just able to get this working much like blacksonic's version (although his path change slightly from the link above) i had to use a diff selector name as well

**Comment by vsavkin** [comment]
@andrui We are no longer maintaining the deprecated router to focus our efforts on making the new router solid.

You can add security to routes by using guards instead of extending outlets in the new router. But you also should be able to extend outlets.

Closing this issue.

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20781540/9600165e-b7be-11e6-9c59-417f18932c07.png)
![Uploading 图片.png…]()
