### ISSUE TITLE
New Router: Hard coded multi-tier routes failing

### ISSUE THREAD

**Issue by coryshaw1** [angular/angular#8428]
When hardcoding a mult-tier route `/main/test`, the new Router seems to not be able to match any routes from the Routes attribute when clicking a [routerLink].

You can manually navigate to the route above on refresh, but using a [routerLink] fails. Look in console when clicking the 'main/test' link of the Plunker below.

http://plnkr.co/edit/35pH4mykr1tPfgdov92o?p=preview

**Comment by todoubaba** [comment]
http://plnkr.co/edit/cJXJWk7uJ4XuQ25Kj7mK?p=preview

**Comment by Spittal** [comment]
Should the Router not be smart enough to parse the string? I might be reading into it wrong but it looks like it should be able to 

https://github.com/angular/angular/blob/master/modules/%40angular/router/src/router_url_serializer.ts

**Comment by CaptainCodeman** [comment]
The routes need some specificity to determine the *best* match, not a simplistic *first* match.

**Comment by sirajc** [comment]
On launching the app, it loads all nested components `http://localhost:4200`
![image](https://cloud.githubusercontent.com/assets/5340498/15269730/6093d8b0-1a26-11e6-80db-a3be42fab8a2.png)

Navigating to same component with nested route does not load grand-child `http://locahost:4200/test/child/grand-child`
![image](https://cloud.githubusercontent.com/assets/5340498/15269751/d8bfca88-1a26-11e6-88a1-180b832082af.png)

Now with URL in place (`http://locahost:4200/test/child/grand-child`) refreshing browser loads all the nested component
![image](https://cloud.githubusercontent.com/assets/5340498/15269730/6093d8b0-1a26-11e6-80db-a3be42fab8a2.png)

**Comment by IgorMinar** [comment]
This issue was made obsolete by router v3: https://angularjs.blogspot.com/2016/06/improvements-coming-for-routing-in.html

If you believe this is not the case, please file a new issue updating the description to router v3. thank you!
