### ISSUE TITLE
Create a CssAdapter (like DomAdapter)

### ISSUE THREAD

**Issue by vicb** [angular/angular#843]
Some methods of the current DomAdapter deal with style:
```
  isPageRule(rule) {
    throw _abstract();
  }
  isStyleRule(rule) {
    throw _abstract();
  }
  isMediaRule(rule) {
    throw _abstract();
  }
  isKeyframesRule(rule) {
    throw _abstract();
  }
```

We should probably extract them to a `CssAdapter` and use:
- something like [this css parser](https://github.com/reworkcss/css) in JS,
- [ccslib](https://pub.dartlang.org/packages/csslib) in Dart

**Comment by mhevery** [comment]
@vicb is this still relevant? Can we close it?

**Comment by vicb** [comment]
let's close it. We can create a new issue if we need this in the future.
