### ISSUE TITLE
Starter repositories to readme

### ISSUE THREAD

**Issue by blacksonic** [angular/angular#8434]
**Steps to reproduce and a minimal demo of the problem**

**Current behavior**
The current readme only links to the 5 min quickstart.
A short list to starter repositories would be also useful.

**Expected/desired behavior**
Add short list of curated starter repositories after 5 min quickstart link.

**Other information**

**Comment by pkozlowski-opensource** [comment]
@blacksonic  thnx for reporting, we always do appreciate documentation corrections! But all the documentation lives in a separate repository: https://github.com/angular/angular.io/issues

Would you mind checking the latest version of the docs and if they still suffer from the problem open an issue in https://github.com/angular/angular.io/issues? Or better yet, send a PR with corrections! This would be very much appreciated!
