### ISSUE TITLE
New Router: imperative navigation return + click fails

### ISSUE THREAD

**Issue by wardbell** [angular/angular#8437]
VS - the RC0 component router bug I mentioned.

Easier to show than explain.

Here's the plunker: http://plnkr.co/edit/sjOPaA0azcANt8MGm3NG?p=preview

Steps:
1. Click a crisis
2. Click either save/cancel
3. It returns to Crisis Center list
4. Click Crisis Center button ... list disappears  !!!
5. Continuous clicking doesn't help. The URL looks fine (open plunker in own window to confirm)

To recover
6. Click Heroes
7. Click Crisis Center ... list restored.

-- 
Here's what it looks like:
![new-router-cc-bug](https://cloud.githubusercontent.com/assets/129061/14997676/33217a50-113d-11e6-8799-57abf3cea47b.gif)

**Comment by CaptainCodeman** [comment]
Looks like same symptom as https://github.com/angular/angular/issues/8421

**Comment by IgorMinar** [comment]
This issue was made obsolete by router v3: https://angularjs.blogspot.com/2016/06/improvements-coming-for-routing-in.html

If you believe this is not the case, please file a new issue updating the description to router v3. thank you!
