### ISSUE TITLE
Rendering multiple tspan with ngFor inside an svg doesn't work as expected

### ISSUE THREAD

**Issue by fjozsef** [angular/angular#8438]
**Steps to reproduce and a minimal demo of the problem**
See  [Plunker](http://plnkr.co/edit/GXfl1lL4Tf10oLawDvpU?p=preview)

**Current behavior**
The labels array length is 2, despite it the ngFor renders 3 tspans. 

**Expected/desired behavior**
Render only two tspans.

**Other information**
I have this problem since rc.0.
Doing the same with divs works fine.
See console log for more info. Rendering the third tspan throws an error because index is not a valid value.

**Comment by zoechi** [comment]
You can't have `*ngIf` and `*ngFor` on the same element. You need to use the canonical form for one of them
See for example http://stackoverflow.com/a/34659638/217408

**Comment by fjozsef** [comment]
Using canonical form solves the problem, so I close this. 
However it would be nice to have an error message when `*ngIf` and `*ngFor` are used on the same element.
