### ISSUE TITLE
[Dart Angular2-beta.17] platform_directives only apply when compiled to JavaScript, not in Dart

### ISSUE THREAD

**Issue by ahirschberg** [angular/angular#8439]
**Steps to reproduce and a minimal demo of the problem**
Given a pubspec.yaml with the following inside the transformers key:
```yaml
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#FORM_DIRECTIVES'
    entry_points: web/main.dart
```
and a main.dart with a component:
```dart
@Component(
    selector: 'my-app',
    template: '''
      <h2>My name is {{hero.name}}</h2>
      <input [(ngModel)]="hero.name">
      ''')
class AppComponent {
  Hero hero = new Hero(10, 'Mr. Incredible');
}
```

**Current behavior**
The input does not update the `Hero` object's `name` field when running in Dartium, but does when compiled to JavaScript. The `ngModel` attribute is ignored when running this code snippet in Dartium because the `FORM_DIRECTIVES` attribute present in pubspec.yaml is not applied. 

A temporary fix is to import `FORM_DIRECTIVES` from `angular2/common.dart`
and add the line 
```dart
@Component(
// ...
    directives: const [FORM_DIRECTIVES],
// ...
``` 
to the `@Component` annotation of my component.

**Expected/desired behavior**
The directives defined in `platform_directives` should apply to the project regardless of whether it is running via the Dart VM or as compiled JavaScript.

**Other information**
[Here is a gist containing the relevant project files](https://gist.github.com/ahirschberg/6560d9b029ff5b07c3957098e788987f)

Apologies if I misused any terminology!

**Comment by pkozlowski-opensource** [comment]
Obsolete.
