### ISSUE TITLE
Use super() only in subclasses, and before any use of `this`

### ISSUE THREAD

**Issue by caitp** [angular/angular#844]
Blocks #733 as Traceur is now enforcing these rules correctly

**Comment by caitp** [comment]
actually, I guess someone went through and did these, afaict

**Comment by caitp** [comment]
I'm wrong, I guess this wasn't completely dealt with =)

**Comment by vicb** [comment]
@caitp the current version of Traceur (0.0.82) enforces that super calls must be present in derived class & be the first statement. It is then more strict than 0.0.84. I guess this issue can be closed ?

**Comment by caitp** [comment]
No, it can't be --- There is plenty of broken code in the tree

**Comment by caitp** [comment]
Landing the fix is blocked on 0.0.86 shipping, and I'm still working on a few additional fixes that are needed for that upgrade.

**Comment by vicb** [comment]
you're right, the check is currently only active when the `memberVariable` is true (it is false for the transpiler) + it does not enforce that the class extends an other class.
