### ISSUE TITLE
Move TestComponentBuilder and ComponentFixture to @angular/core/testing

### ISSUE THREAD

**Issue by vikerman** [angular/angular#8441]
Currently TestComponentBuilder and ComponentFixture are in @angular/compiler/testing because of the need to override templates and directives but it is not an intuitive place to find TestComponentBuilder(and ComponentFixture)

We can separate overriding into a different class(TestComponentOverrides?) that can still come out of @angular/compiler/testing and that should be ok as overriding can be considered as an advanced feature.

For the the simple use cases an Angular test author can find the TestComponentBuilder and ComponentFixture in @angular/core/testing with the rest of the testing classes without having to know about the compiler.

**Comment by vicb** [comment]
fixed
