### ISSUE TITLE
ComponentFixture autoDetectChanges, whenStable and isStable should throw an exception if there is no NgZone present

### ISSUE THREAD

**Issue by vikerman** [angular/angular#8442]
It is possible to being up TestComponentBuilder with an NgZone by providing a true value for token ComponentFixtureNoNgZone.

In that case the APIs in Component Fixture that depend upon NgZone to function properly - autoDetectChanges, whenStable, isStable should throw an exception if called without the NgZone being present.

**Comment by vicb** [comment]
@vikerman status ?

**Comment by vikerman** [comment]
Obsolete
