### ISSUE TITLE
Change ComponentFixture onStable handler to scheduleMicrotask only if there's someone waiting for the completion

### ISSUE THREAD

**Issue by vikerman** [angular/angular#8445]
The scheduleMicrotask in test_component_builder should be called only when this._completer !== null.

Code here - https://github.com/angular/angular/blob/master/modules/@angular/compiler/testing/test_component_builder.ts#L107

should be change to 

```
        if (this._completer !== null) {
          scheduleMicroTask(() => {
            if (!this.ngZone.hasPendingMacrotasks) {
              if (this._completer !== null) {
                this._completer.resolve(true);
                this._completer = null;
              }
            }
          });
        }
```

Currently it's queueing extraneous microtasks that don't get resolved until the next whenStable is called.

**Comment by vicb** [comment]
@vikerman what is the status ?
