### ISSUE TITLE
testing missing in @angular/platform-server

### ISSUE THREAD

**Issue by mlaval** [angular/angular#8447]
**Steps to reproduce and a minimal demo of the problem**

npm install --save @angular/platform-server

**Current behavior**
`testing.js` and `testing/server.js` are missing in the package

**Expected/desired behavior**
`testing.js` and `testing/server.js` are available in the package

**Other information**
Happens in rc0 and rc1

**Comment by tamascsaba** [comment]
I am really miss this files :(

**Comment by mlaval** [comment]
No longer occurring in rc5 (I haven't checked r2, rc3 or rc4).
