### ISSUE TITLE
Offline compiler fails at runtime with "No provider" errors

### ISSUE THREAD

**Issue by robwormald** [angular/angular#8448]
cc @tbosch 

Setup:
`app.ts`
```typescript
import {Component} from '@angular/core'
import {TestComponent} from './test'

@Component({
	selector: 'test-app',
	template: `
	  <div>Hello {{name}}</div>
	  <test-component></test-component>
	`,
	directives: [TestComponent]
})
export class App {
	name: string;
	constructor(){
		this.name = 'hello'
	}
}
```
`test.ts`
```typescript
import {Component} from '@angular/core'
import {NgIf} from '@angular/common'


@Component({
	selector: 'test-component',
	template: `
	  <div *ngIf="show">hello child</div>
	`,
	directives: [NgIf]
})
export class TestComponent {
	show: boolean = false;
	constructor(){
		setInterval(() => {
			console.log('tick')
			this.show = !this.show;
		}, 1000)
	}
}
```
`main-static.ts`
```typescript
import {coreBootstrap, ReflectiveInjector} from '@angular/core';
import {browserPlatform, BROWSER_APP_STATIC_PROVIDERS} from '@angular/platform-browser';
import {AppNgFactory} from './app.ngfactory';
import {App} from './app';

const appInjector =
    ReflectiveInjector.resolveAndCreate(BROWSER_APP_STATIC_PROVIDERS, browserPlatform().injector);
coreBootstrap(appInjector, AppNgFactory);

```

Result:
- compilation succeeds
- runtime throws with 
<img width="1018" alt="screen shot 2016-05-03 at 4 42 06 pm" src="https://cloud.githubusercontent.com/assets/534930/15000951/c742c370-1150-11e6-97da-c9ffec3856d8.png">

**Comment by tbosch** [comment]
Ok, `NgIf` works.
But for `NgFor` we need the following:

1. support lifecycle hooks (for `NgFor.ngDoCheck`)
2. the generated code should not use deep imports by rather private symbols of the compiler

For 1): Simplest solution is to collect all methods names (a trivial change in `tools/metadata/collector.ts`) and then use that information to reason about lifecycle hooks in a similar way as we do it during runtime

For 2): This is not trivial. Right now, we calculate the import to write by the absolute path of the declaration module of the symbol and the generated file.

**Comment by tbosch** [comment]
Note that the deep imports should only be a problem when using UMD packages, and when we do offline compilation users probably won't use the UMD packages.

@robwormald I really need that repro of yours that used `ngFor` and reported a "no provider for IterableDiffers"...

**Comment by tbosch** [comment]
Also note that the deep imports are not a problem in our setup on CI (as e.g. `NgIf` works). Mmh...

**Comment by tbosch** [comment]
Lifecycle hooks are supported via https://github.com/angular/angular/pull/8467

**Comment by robwormald** [comment]
@tbosch are we running an E2E test for this on CI? or just successful compile?

**Comment by damrbaby** [comment]
I see the #8467 was closed without merge.  What is the reasoning behind that?  What is the current plan to support lifecycle hooks and thereby support `NgFor` in the offline compiler?

**Comment by vicb** [comment]
@robwormald is this still an issue with 2.0.1 ?
