### ISSUE TITLE
Bundles missing from new @angular packages as of RC1

### ISSUE THREAD

**Issue by kylecordes** [angular/angular#8456]
Expected (er, hoping for): new packages include the very-convenient ready-to-use System bundles. Or, than the angular2 package be updated to RC, and include those bundles.

Actual: new @angular/blah packges appear not to contain any System bundles. They do contain UMD bundles.

**Comment by meriturva** [comment]
I guess related to https://github.com/angular/angular/issues/8412

**Comment by kylecordes** [comment]
There is plenty of discussion there, I will close this issue.

**Comment by peter-bozovic** [comment]
I think this issue is different from #8412 which  is more related to publishing configuration with new package structure

I'm also having issues with System.js dynamically loading necessary components individually.
When using bundles, page refresh took 1 second.
With RC1 system.config.js it takes around 10 seconds (in Firefox) because there are more than 350 js files loaded.

It's big time lose during development and using bundles from beta was really helpful for that.

So I woud like to ask to reopen this issue and bring back bundles please.

**Comment by sgbeal** [comment]
In fact, i spent today trying to integrate a bundling solution with angular-cli and found that it's impossible to do. We got bundle-creation working using systemjs, but angular-cli has no hooks which allow us to inject the bundle, and its (ng server) deletes any files it did not inject itself. If you try to work around that by overwriting a dummy file after ng deploys it, ng only serves the original (deployed) content, not the new contents of the file. You also can't store static (pre-generated) bundles in your source tree because angular-cli is hard-coded to exclude .js files from your tree when it copies everything to its 'dist' directory(!!!). So client-provided bundling literally impossible to implement on top of angular-cli!

**Comment by kylecordes** [comment]
I believe the path to achieve that is not to try to use angular-cli and cobble on additional behavior in an application, but rather to go assist with the angular-cli project. It is a community project, not only worked on by core Angular team members. And it already has the goal of supporting a production build option out of the box for trivial optimal use. I think it will succeed, and it will be fantastic. You will be able to do a three minute demo of getting started with Angular 2 which includes a highly optimized production build. However, to get from here to there...  there is some chance the team working on it might appreciate more help :-)

**Comment by damiandennis** [comment]
changing my system config to the following speed up my application a lot.
```javascript
/**
 * System configuration for Angular 2 samples
 * Adjust as necessary for your application needs.
 * Override at the last minute with global.filterSystemConfig (as plunkers do)
 */
(function(global) {

    // map tells the System loader where to look for things
    var map = {
        'app': 'app', // 'dist',
        'angular2-in-memory-web-api': 'node_modules/angular2-in-memory-web-api',
        '@angular': 'node_modules/@angular'
    };

    // packages tells the System loader how to load when no filename and/or no extension
    var packages = {
        'app': {
            main: 'main.js',
            defaultExtension: 'js',
            format: 'cjs'
        },
        'angular2-in-memory-web-api': { defaultExtension: 'js' }
    };

    var packageNames = [
        '@angular/common',
        '@angular/compiler',
        '@angular/core',
        '@angular/http',
        '@angular/platform-browser',
        '@angular/platform-browser-dynamic',
        '@angular/router-deprecated'
    ];

    // add package entries for angular packages in the form '@angular/common': { main: 'index.js', defaultExtension: 'js' }
    packageNames.forEach(function(pkgName) {
        packages[pkgName] = { main: 'index.js', defaultExtension: 'js' };
    });

    packages['@angular/common'].main = 'common.umd.js';
    packages['@angular/core'].main = 'core.umd.js';
    packages['@angular/compiler'].main = 'compiler.umd.js';
    packages['@angular/http'].main = 'http.umd.js';
    packages['@angular/platform-browser'].main = 'platform-browser.umd.js';
    packages['@angular/platform-browser-dynamic'].main = 'platform-browser-dynamic.umd.js';
    packages['@angular/router-deprecated'].main = 'router-deprecated.umd.js';

    var config = {
        // Maps all rxjs to the bundled version... included in head.
        paths: {
            "rxjs/*": "node_modules/rxjs/bundles/Rx.umd.min.js"
        },
        map: map,
        packages: packages
    };

    System.config(config);

})(this);
```

**Comment by damiandennis** [comment]
The above no longer works because of the router v3.

**Comment by omeryounus** [comment]
@damiandennis  any help on this?

**Getting the following error:**
zone.js:101 GET http://localhost:4200/node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js 404 (Not Found)scheduleTask @ zone.js:101ZoneDelegate.scheduleTask @ zone.js:345Zone.scheduleMacroTask @ zone.js:282(anonymous function) @ zone.js:122send @ VM6320:3fetchTextFromURL @ system.src.js:1051(anonymous function) @ system.src.js:1781ZoneAwarePromise @ zone.js:607(anonymous function) @ system.src.js:1780(anonymous function) @ zone.js:101 

GET http://localhost:4200/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js 404 (Not Found)scheduleTask @ zone.js:101ZoneDelegate.scheduleTask @ zone.js:345Zone.scheduleMacroTask @ zone.js:282(anonymous function) @ zone.js:122send @ VM6320:3fetchTextFromURL 


**Systemjs.config.js**

/**
 * System configuration for Angular 2 samples
 * Adjust as necessary for your application needs.
 */
(function (global) {
  System.config({
    paths: {
      // paths serve as alias
      'npm:': 'node_modules/'
    },
    // map tells the System loader where to look for things
    map: {
      // our app is within the app folder
      app: 'app',

      // angular bundles
      '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
      '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
      '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
      '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
      '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
      '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
      '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
      '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',




      // other libraries
      'rxjs':                       'npm:rxjs',
    },
    // packages tells the System loader how to load when no filename and/or no extension
    packages: {
      app: {
        main: './main.js',
        defaultExtension: 'js'
      },
      rxjs: {
        defaultExtension: 'js'
      }
    }
  });
})(this)

**Comment by damiandennis** [comment]
@omeryounus I did an alternative solution in this issue https://github.com/angular/angular/issues/9359 I ended up having to bundle rxjs myself.

**Comment by omeryounus** [comment]
@damiandennis  Yes, I got it fixed, thanks

But now I am getting this issue:

**Index.html**
<script>
    System.import('app').catch(function(err){ console.error(err); });
  </script>

**main.ts**
```
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { AppModule } from './app.module';
const platform = platformBrowserDynamic();
platform.bootstrapModule(AppModule);

```
(28 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:4200/src/app/main.js
	Error: XHR error (404 Not Found) loading http://localhost:4200/src/app/main.js

**Comment by damiandennis** [comment]
@omeryounus need more information to help with that. Also I am not using lite-server so not sure If i would be of much help.

**Comment by omeryounus** [comment]
@damiandennis sure, from index.html it's not able to find the main.ts file. There is something is not referenced properly. Do you have any idea to test these references?

Browser console showing the main.js not found.
Cannot GET /src/app/main.js

thanks
