### ISSUE TITLE
ngOnDestroy is not triggered

### ISSUE THREAD

**Issue by martinvondracek** [angular/angular#8458]
**Steps to reproduce and a minimal demo of the problem**
demo http://plnkr.co/edit/7uoVecfa62i8No8GtQHI?p=preview
Angular2 beta 16 or higher - When I hide first section with nested components using *ngIf, ngOnDestroy of every nested component is triggered - this is OK.

```
  <div *ngIf="!ff2">
    <my-component
    ></my-component>
    <my-component
    ></my-component>
    <my-component
    ></my-component>
    <my-component
    ></my-component>
    <my-component
    ></my-component>
  </div>
```
Outpu in console is
```
    init
    init
    init
    init
    init
    destroy
    destroy
    destroy
    destroy
    destroy

```
But when I hide second section where subcomponents are duplicated by *ngFor, not every ngOnDestroy is triggered.

```
<div *ngIf="!ff">
   <my-component
     *ngFor="#i of [1,2,3,4,5,6]"
   ></my-component>
</div>
```
output in console is

```
(6) init
(3) destroy
```

**Current behavior**
not every ngOnDestroy is triggered

**Expected/desired behavior**
every ngOnDestroy should be triggered

**Other information**
in angular2 beta 9 it was working correctly
http://plnkr.co/edit/Q8tLJKlpF6wEVcMWfxH1?p=preview

**Comment by zoechi** [comment]
cross-ref http://stackoverflow.com/questions/37012854/angular-2-ngondestroy-is-not-triggered

**Comment by leeching** [comment]
I have once in the same situation. And, by the way, in the above example, `destroy` are logged by 1st, 3rd and 5th `my-component`. `ngOnDestroy` of 2rd, 4th and 6th are not trigged. It is weird.

**Comment by adammartin1981** [comment]
I'm still seeing this issue in RC1 (should I be?)

I'm not hiding any components (or using ngIf), but I am using an ngFor loop to generate them (as well as ViewContainerRef and ComponentResolver to dynamically insert components) if that's of any use?

**Comment by adammartin1981** [comment]
Think I've found the issue, it was to do with iterating over a moving target (a decreasing array).

Inside core/src/linker/view.ts, there is a piece of code at line 203:

```    
var children = this.contentChildren;
for (var i = 0; i < children.length; i++) {
   children[i]._destroyRecurse();
}
children = this.viewChildren;
for (var i = 0; i < children.length; i++) {
   children[i]._destroyRecurse();
}
```

Where children always decreased, but i remained a constant, you could never hit the even items in the array, as i would be '1' on the second loop, but the [1]th item in the array would now be the 3rd item (as the original [0]th item in the array would have been removed and the new [0]th item in the array would now be the 2nd). 

A quick fix would be to have:
```
var children = this.contentChildren;
var i = children.length;

while( i > 0 ) {
   children[i - 1]._destroyRecurse();
   i--;
}
```

I might knock up a PR at some point, but I didn't know what anyone else thought?
