### ISSUE TITLE
[Angular 2] Link in Structural Directives - guide broken

### ISSUE THREAD

**Issue by 0815fox** [angular/angular#8459]
[Structural Directives](https://angular.io/docs/ts/latest/guide/structural-directives.html)

Just right before "Wrap up", the link [Look at the source code](https://github.com/angular/angular/blob/master/modules/angular2/src/common/directives/ng_if.ts) points to https://github.com/angular/angular/blob/master/modules/angular2/src/common/directives/ng_if.ts, which doesn't exist anymore.

**Comment by pkozlowski-opensource** [comment]
Seems to be fixed now. Doc issues should be reported at  https://github.com/angular/angular.io/issues
