### ISSUE TITLE
[rc.1] Router cannot initialize route when params supplied by user

### ISSUE THREAD

**Issue by Delagen** [angular/angular#8461]
when i navigate from code 
```
this.router.navigate(["/login", {back: "/backurl"}]);
```
the url states `http://.../#/login;back=/backurl`

but when i simply reload page
then error
```
Error: Uncaught (in promise): Component 'LoginView' does not have route configuration
```

**Comment by zoechi** [comment]
How do the routes look like?

**Comment by Delagen** [comment]
@Routes([
	{path: "/login", component: LoginView},
	{path: "/account", component: AccountView},
	{path: "/", component: RootView}
])
export class App {
	constructor(@Inject(Router) protected router: Router) {
	}
}

**Comment by Delagen** [comment]
I think this is due / in param value

**Comment by ericmartinezr** [comment]
I had a similar issue, although I found it by mistake https://github.com/angular/angular/issues/8420

**Comment by Delagen** [comment]
Reference #8603

**Comment by Delagen** [comment]
router@3.0.0-alpha6 does not solve this (

**Comment by Delagen** [comment]
fix supplied at #8603 does not work, but issue closed ((

**Comment by zoechi** [comment]
Please provide a Plunker that allows to reproduce.

**Comment by Delagen** [comment]
http://run.plnkr.co/mzwbtNPqfhN0TI3P/#/crisis-center;aaa=aaa/aaa
See what happened with parameters... That destroyed totally

**Comment by zoechi** [comment]
@Delagen can you please post the Plunker linke without queryparams. The link you posed doesn't work.

**Comment by Delagen** [comment]
http://plnkr.co/edit/abJikLZ6spXDvJtHQME3

**Comment by zoechi** [comment]
Sounds like #9460

**Comment by Delagen** [comment]
in #9483 that closed error isn't fixed

**Comment by vsavkin** [comment]
The issue has be fixed. See the last comment here https://github.com/angular/angular/issues/9483
