### ISSUE TITLE
[rc0] Unable to use new router with UpgradeAdapter

### ISSUE THREAD

**Issue by aleksclark** [angular/angular#8463]
Previously, in Beta 17, it was possible to utilize the (now deprecated) router in an ng2 component that was bootstrapped in an ng1/ng2 hybrid application. This was enabled in part by specifying `ROUTER_PRIMARY_COMPONENT` as one of the providers for the "root" ng2 component. In turn, this use case enables large ng2 "sections" of an app that already use the ng2 router, minimizing the big-bang aspects of any upgrade from ng1.

However, with the advent of the new router, all has changed: it is no longer possible to specify `ROUTER_PRIMARY_COMPONENT`, and any attempts to use the new router in a hybrid app result in: `Error: Bootstrap at least one component before injecting Router.`

Here is a functional Beta 17 plunker demonstrating a functional ng1/ng2 hybrid app with an ng2 component that uses the router: http://plnkr.co/edit/hJi1zysfFSdQ6atGjEAK

Here is a non-functional version that uses RC0: http://plnkr.co/edit/L31dWUoAnTnI3CnYEYrH

**Comment by choeller** [comment]
Any news on this? Is there another way than `ROUTER_PRIMARY_COMPONENT` to use the new router in a hybrid app? 

/cc @vsavkin

**Comment by NickNevius** [comment]
I am running into this same issue. I even stole the ROUTER_PRIMARY_COMPONENT from @angular/router-deprecated/src/route-registry.js and tried providing that in the same way that it would work for the deprecated router but it still fails.

**Comment by MikeMatusz** [comment]
This still appears to be an issue in RC3: http://plnkr.co/edit/COB27qdf31exkuPx0lHn

Attempted to register PRIMARY_OUTLET, guessing that it might be analogous to ROUTER_PRIMARY_COMPONENT, but apparently that is incorrect.  Has anyone gotten this to work yet?

**Comment by MikeMatusz** [comment]
@brandonroberts posted the solution against #9870

**Comment by vsavkin** [comment]
The issue has been fixed in master. It's possible to use the new router in hybrid applications.
