### ISSUE TITLE
When trying to install rc1 I get an npm error

### ISSUE THREAD

**Issue by Avien** [angular/angular#8464]
![rc-error](https://cloud.githubusercontent.com/assets/4569044/15016705/1643ecd6-121b-11e6-9571-350556b10d72.png)

Using node v6
npm 3.8.6

Have also tried node v 4, 5 but still no go

**Comment by ericmartinezr** [comment]
Have you tried cleaning the cache? `npm cache clean`

**Comment by Avien** [comment]
Yes, I have also tried deleting the node_modules library

**Comment by jsight** [comment]
I am seeing similar errors as well.

**Comment by Avien** [comment]
3.8.8 or 3.8.6?

**Comment by jsight** [comment]
@Avien 

```
npm --version
3.8.8
```

I just updated this morning.

**Comment by Avien** [comment]
I have installed latest and its only 3.8.6

**Comment by jsight** [comment]
@Avien https://www.npmjs.com/package/npm

The latest is 3.8.8. You can do an npm install -g npm if you want to update.

**Comment by Avien** [comment]
I already did that and got 3.8.6

**Comment by raduGaspar** [comment]
@Avien if you're on Windows, download the installer from the node homepage and install it like that. Works faster than the steps required to update the version after you do
npm install -g npm

**Comment by Avien** [comment]
Thanks but I'm on Mac

**Comment by battistaar** [comment]
same issue with npm 3.8.6 and 3.8.8 on osx

**Comment by Avien** [comment]
Still not working for me

**Comment by jsight** [comment]
@Avien - Can you post the exact command that you are running and the full output?

**Comment by ericmartinezr** [comment]
@Avien maybe this issue may help you https://github.com/angular/angular/issues/8483

**Comment by Avien** [comment]
@jsight you can see it above in the screen shot image I attached
@ericmartinezr No it doesn't, just tried it

**Comment by jsight** [comment]
IIRC, I had to specify the version number. Something like "npm install '@angular/core^2.0.0-rc1'".

I'm really baffled as to how that could return "invalid name".

**Comment by DanailMinchev** [comment]
@Avien 

I am on Ubuntu and `node-v6.0.0`, the default `npm` is `3.8.6`, to update the `npm` you need to install it as a global package:

`npm install -g npm`

and also you need to check in your `PATH` which version of npm is picked up first.

For example:

I have installed node here: `/opt/nodejs/node`

The `default npm`:
```
/opt/nodejs/node/bin/npm -v

3.8.6
```

My `~/.npmrc` (https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-2-change-npms-default-directory-to-another-directory):
```
$ cat ~/.npmrc
prefix=/home/user/npm-global
registry=http://registry.npmjs.org
```

Update npm and check npm:
```
npm install -g npm

$ which npm
/home/user/npm-global/bin/npm

$ /home/user/npm-global/bin/npm -v
3.8.8
```

Fix the `PATH`:

```
export NODE_HOME='/opt/nodejs/node'
export NPM_PACKAGES='/home/user/npm-global'
export PATH=$NPM_PACKAGES'/bin':$NODE_HOME'/bin':$PATH
```

Anyway, on latest Node and latest Npm I have the same issue: `Angular 2.0.0-rc.1 / 2.0.0-rc.0` are not found, probably because https://www.npmjs.com/package/angular2 is `2.0.0-beta.17` ?

**Comment by DanailMinchev** [comment]
I also tried:

```
npm set registry http://registry.npmjs.org
rm -rf node_modules/
npm cache clean
```

**Comment by jsight** [comment]
@DanailMinchev The projects are https://www.npmjs.com/~angular and https://www.npmjs.com/package/@angular/core

**Comment by DanailMinchev** [comment]
@jsight thanks!

So, in my understanding https://www.npmjs.com/~angular is the user/organization.

What confuses me is:
When I go to https://www.npmjs.com/package/angular2:
```
...
This is the repository for the upcoming 2.0 version.
...
```

Is @angular/* packages like https://www.npmjs.com/package/@angular/core are the new latest ones and https://www.npmjs.com/package/angular2 will be deprecated?

**Comment by jsight** [comment]
Yes, https://www.npmjs.com/package/angular2 is basically being deprecated AFAICT. A lot of this is explained in the changelog.

**Comment by DanailMinchev** [comment]
@jsight 

Thank you!

https://github.com/angular/angular/blob/master/CHANGELOG.md#200-rc0-2016-05-02

**Comment by Avien** [comment]
@DanailMinchev npm 3.8.9 solved my problem!
Thanks

**Comment by pkozlowski-opensource** [comment]
Sounds like this one got resolved, closing.
