### ISSUE TITLE
No 'readme' and 'repository' entry in published npm packages of release candiates

### ISSUE THREAD

**Issue by tscheinecker** [angular/angular#8465]
In the new packages published to npm neither 'readme' nor 'repository' fields are provided.

This leads to a not very informative package page: https://www.npmjs.com/package/@angular/core

and also breaks webjar deployment (http://www.webjars.org/npm) with the following message

```
Failed!
The source repository for @angular/core 2.0.0-rc.1 could not be determined but is required to published to Maven Central. This will need to be fixed in the project's package metadata.
If you feel you have reached this failure in error, please file an issue:https://github.com/webjars/webjars/issues

Determined Artifact Name: angular__core
Starting Deploy´
```

**Comment by pkozlowski-opensource** [comment]
`repository` field is already fixed, see https://github.com/angular/core-builds/blob/master/package.json

README is tracked in #9238
