### ISSUE TITLE
Renderer.createElement - possibly incorrect call signature

### ISSUE THREAD

**Issue by terrawheat** [angular/angular#8466]
**Current behavior**
Before the release candidate the following compiled without issue:

```
export class Foo {
  constructor(private renderer: Renderer) {
    const tag = 'p';
    const element = /* some kind of HTMLElement */;
    let el = this.renderer.createElement(element, tag);
  }
}
```

Since the release candidate this now throws a compile error:

 error TS2346: Supplied parameters do not match any signature of call target.

The third parameter `DebugInfo` I believe should be an optional parameter.

**Expected/desired behavior**
Be able to compile with just `element` and `tag` provided.

**Comment by vaudy** [comment]
the "debugInfo:RendererDebugInfo" should be optional at least..

// createElement(parentElement: any, name: string, debugInfo: RenderDebugInfo) : any

**Comment by scttcper** [comment]
Piggy backing on this issue with Renderer.invokeElementMethod
```ts
invokeElementMethod(renderElement: any, methodName: string, args: any[]);
```
args should be optional.

**Comment by terrawheat** [comment]
Was going to PR this, however it involves a change to a public API, and there's a big scary warning at the top of that file.

**Comment by ericmartinezr** [comment]
@terrawheat you can change the public API, but it's up to ng2 team to approve it or not, so do it with no worries.

**Comment by terrawheat** [comment]
@ericmartinezr ah thanks for the info. I've reopened the PR now then :)
