### ISSUE TITLE
bug(testing) detectChanges not waiting for controls of Template driven forms

### ISSUE THREAD

**Issue by choeller** [angular/angular#8468]
**Steps to reproduce and a minimal demo of the problem**

I have a test that worked on beta.15 but is not working with new zones / testing. I'm testing a template driven form like this:

``` ts
  beforeEach(async(inject([TestComponentBuilder, TaskService],
    (_tcb:TestComponentBuilder, _taskService) => {
      taskService = _taskService;
      tcb = _tcb;
      return _tcb
        .createAsync(EditTaskComponent)
        .then(_fixture => {
          fixture = _fixture;
        } ).catch((e) => console.log(e));
    })));

  iit('should validate the title correctly', fakeAsync(() => {

    fixture.detectChanges()
    tick();
    let form:ControlGroup = fixture.componentInstance.ngForm.form;
    console.log("Controls:", form.controls); // logs 'Object{}'
    var titleControl = (<Control> form.controls["title"]);
    expect(titleControl.errors['required']).toBeTruthy(); // Throws Cannot read property 'errors' of undefined
  }
```

**Current behavior**

fakeAsync / detectChanges / tick is not "waiting" long enough to work with a Template driven form

**Expected/desired behavior**

fakeAsync tests should be able to work with Template driven forms

**Other information**

**Comment by DzmitryShylovich** [comment]
@choeller `TestComponentBuilder` was deprecated. is this still an issue with `TestBed`?
