### ISSUE TITLE
Angular 2 RC 1 IE9 Unable to get property 'contains' of undefined or null reference

### ISSUE THREAD

**Issue by pgarge** [angular/angular#8469]
I am using the following with angular 2:

node_modules/zone.js/dist/zone.min.js
node_modules/reflect-metadata/Reflect.js
node_modules/es6-shim/es6-shim.min.js
node_modules/systemjs/dist/system.js
node_modules/rxjs/bundles/Rx.min.js

This seems to be generated when template is drawn:
EXCEPTION: Error in App/Profile/longprofile.html:0:8

Works in all other browsers except IE 9. Anyone seeing this error?

**Comment by evgeniynet** [comment]
me too
I also using node_modules/angular2/es6/dev/src/testing/shims_for_IE.js
but same error

**Comment by evgeniynet** [comment]
me too
even Im using node_modules/angular2/es6/dev/src/testing/shims_for_IE.js

**Comment by pkozlowski-opensource** [comment]
@parge @evgeniynet could you please provide a minimal code example that gives you this error?

**Comment by dboyne** [comment]
I'm also seeing this issue has any come up with a fix ?

**Comment by flipppp** [comment]
I have the same error:

Component:

    import { Component } from '@angular/core';
    import { PostService } from './post.service';

    @Component({
        selector: 'posts',
        templateUrl: 'app/post.html',
    })

    export class PostComponent {
        private posts;
        private title;
        private body;
        private newPost;

        constructor(private _postService:PostService) {
            this.posts = this._postService.getPost();
        }

        addPost() {
            this.newPost = {
                title: this.title,
                body: this.body
            }

            this._postService.addPost(this.newPost);
        }
    }

Template:

    <h1>Posts</h1>

    <form (submit)="addPost()">
        <label>Title</label>
        <input type="text" [(ngModel)]="title" />
        <br />

        <label>Body</label>
        <input type="text" [(ngModel)]="body" />
        <br />

        <input type="submit" value="Submit" />
    </form>

    <ul>
        <li *ngFor="let post of posts">
            <h3>{{ post.title }}</h3>
            <p>{{ post.body }}</p>
        </li>
    </ul>

**Comment by zoechi** [comment]
@flipppp can you please move this into a Plunker that allows to reproduce?

**Comment by pkozlowski-opensource** [comment]
Closing as we don't have any reproduce scenario.
