### ISSUE TITLE
Chrome updates break svg xlink:href links with ngRoute

### ISSUE THREAD

**Issue by MattBroach** [angular/angular#8474]
I'm not entirely sure whether to post this here or file as a chrome bug report, but just to be safe I'm doing both.  I have several angular apps that have internal ngRoute links on svg objects, using an anchor tag with xlink:href attributes.  This was working fine until the latest Chrome update, at which point the links stopped working: they don't even redirect to the default route, but simply leave the ng-view empty (although any content not in the ng-view remains visible).  No error is reported in the console, the ng-view is just blank.

Demo here:
http://www.aphasiac-design.com/angularXlinkDemo/#/
(angular 1.5.5)

In the above demo, the svg link works in:
Firefox 46.0.1 (OS X 10.10.5)
Safari 9.1 (OS X 10.10.5)
iOS Safari (don't have version number)

the svg link does NOT work in:
Chrome 50.0.2661.94 (OS X 10.10.5)
Chrome 50.0.2661.94 (Windows 10)
Chrome 50.0.2661.94 (Android 6.0.1)

In all of the Chrome versions tested, the svg links were working just fine before updating to the latest version, at which point they started exhibiting the above-described behavior.  Any ideas?

Here's the code of the above demo:
```
<!DOCTYPE html>
<html lang="en" ng-app="xlink">
  <head>

    <title>Angular xlink:href bug demo</title>
  </head>
  <body>

    <div ng-view></div>
    <script src="angular.min.js"></script>
    <script src="angular-route.min.js"></script>

    <script>
      var app = angular.module('xlink', [
        'ngRoute'
        ]);

      app.config(['$routeProvider', function ($routeProvider) {
        $routeProvider
          .when('/', {
            template: '<p><a href="#/target">Normal Link</a></p>' +
                      '<svg><a xlink:href="#/target"><text x="0" y="20">SVG Link</text></svg>'
          })
          .when('/target', {
            template: '<p> The linked page. <a href="#/">Go back</a></p>'
          })
      }]);

    </script>
  </body>

</html>
```

**Comment by zoechi** [comment]
This is for Angular2. Angular.js is in https://github.com/angular/angular.js

**Comment by MattBroach** [comment]
Shoot, sorry.  Reposted my issue there.
