### ISSUE TITLE
offline template compiler does not discover files not listed in files[]

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#8475]
configure `tsconfig.json` with `files: ['bootstrap.ts', 'app.ts']` where `app.ts` imports `mycomp.ts` that has a Component in it.
offline compiler does not generate `mycomp.ngfactory.ts` file.

reported by @hansl

**Comment by kylecordes** [comment]
I noticed this also, and hope very much that ngc will be made to work more like tsc in this respect. Otherwise, build setup complexity will escalate even further.
