### ISSUE TITLE
How to include external HTML template in examples

### ISSUE THREAD

**Issue by dylanb** [angular/angular#848]
I am trying to create an example of an ARIA menu. I am able to see how to include an HTML template using the url attribute but I do not see any support for copying template (other than CSS) files to the dist directories in the Gulp script. I may be missing something - in which case, please point it out.

If I am not missing anything, I can add this but wanted to see whether there are any preferences for how this should be added to the Gulp script? I see support for .cjs files being copied and renamed to .js, should I create similar capabilities for .chtml files?

**Comment by mhevery** [comment]
This is a concern of angular CLI, which is a separate project.
