### ISSUE TITLE
Router does not allow users to navigate to a route in the address bar unless a link is added some where in the page

### ISSUE THREAD

**Issue by rahulbats** [angular/angular#8481]
So i realized this, i have to add a router link to my page to get the routes to work.
`<a [routerLink]="['/heroes']">Heroes</a>`

Now if i type http://localhost:4200/heroes i actually get to the heroes page. If i remove the link from my page typing it in address bar does not load the route content.

Please refer to this [thread](https://github.com/angular/angular-cli/issues/629)

**Comment by cexbrayat** [comment]
I'm running into a similar issue (new router in rc.1).

Also I have to click twice on the link to display the component sometimes.

**Comment by ericmartinezr** [comment]
Related to https://github.com/angular/angular/issues/8409 ?

**Comment by luxueyan** [comment]
Me too

**Comment by yfain** [comment]
We have an app with a page that has several components, and one of the children had a [routerLink] to open a specific component. It used to work fine with old router. After upgrading the app to RC.1, this page didn't render half of the components without reporting any errors. 

After we've added unneeded ```      <a  [routerLink]="['/']">My page</a> ```  to one of the components the page rendered correctly.

This is clearly a bug in the router.

**Comment by ps2goat** [comment]
+1 - a lot of broken router features.

**Comment by blackheart01** [comment]
I'm having the exact same problem. It took me all day to figure this out. The routerLink doesn't even have to link to a valid route. It just has to exist.
Ex.
`<a [routerLink]="['/it_does_not_matter_what_is_in_here']">ABOUT</a>`

**Comment by blackheart01** [comment]
I'm able to remove the routerLinks all together if I inject Router into the top level app.component:
```
import { Component } from '@angular/core';
import { ROUTER_DIRECTIVES, Routes, Router } from '@angular/router';

import { AboutComponent } from './+about/index';
import { HomeComponent } from './+home/index';
import { NameListService, ToolbarComponent, NavbarComponent } from './shared/index';

@Component({
  selector: 'sd-app',
  viewProviders: [NameListService],
  templateUrl: 'app/app.component.html',
  directives: [ROUTER_DIRECTIVES, ToolbarComponent, NavbarComponent]
})
@Routes([
  {
    path: '/',
    component: HomeComponent
  },
  {
    path: '/about',
    component: AboutComponent
  }
])
export class AppComponent {
  constructor(private router: Router) { }
}

```

**Comment by IgorMinar** [comment]
This issue was made obsolete by router v3: https://angularjs.blogspot.com/2016/06/improvements-coming-for-routing-in.html

If you believe this is not the case, please file a new issue updating the description to router v3. thank you!
