### ISSUE TITLE
Angular2 routing stops working after clicking once in IE10

### ISSUE THREAD

**Issue by aashishab** [angular/angular#8482]
**IMPORTANT**: Angular2 routing is not working after clicking once. Please find below the code snippet that I am using wherein i have a dropdown that showing up some nitfications anf then redirecting to a link. However, it is working on once.

**Code snippet for HTML**

`< a [routerLink]="['Review']" (click)="fetchDetails($event)" id="{{i}}" >VIEW</a>`

Component file as:

`public fetchDetails(event) { 
this.message= this._messagesList.message[event.target.id];
    this._messageService.getMessageDetails(this.message);
  }`

Routing definition:

`@RouteConfig([
  { path: '/projectX/review', name: 'Review', component: ReviewComponent }
])`

**Comment by zoechi** [comment]
The router version you are using is deprecated and a new implementation was introduced in rc.0

**Comment by aashishab** [comment]
Thanks for the update
