### ISSUE TITLE
Incorrect rendering in Microsoft Edge

### ISSUE THREAD

**Issue by virtualvoid** [angular/angular#8484]
Hi,

today I came across this weird issue. I don't know how to describe it so here are screenshots:

IE Edge (wrong):
![edge_cut](https://cloud.githubusercontent.com/assets/234315/15043599/87678cf2-12ce-11e6-8393-457c13505b29.png)

Firedfox (correct):
![ff_cut](https://cloud.githubusercontent.com/assets/234315/15043600/876bdcc6-12ce-11e6-9e15-bda81d55f3c7.png)

The buttons are appearing after hovering around them in Edge. 

Does anybody know what's going on ? Thanks.

- Angular2 beta17
- App is built using webpack.
- When I resize the window it suddenly redraws and it seems to be OK

**Comment by zoechi** [comment]
Looks more like a CSS issue than an Angular issue to me. Without a Plunker that allows to reproduce I fear there is not much that can be done anyway.

**Comment by virtualvoid** [comment]
@zoechi thanks but nope, it's related to exactly Microsoft Edge "browser".

for anyone who came across this issue, this helped http://stackoverflow.com/a/12395506
