### ISSUE TITLE
Documentation: many example code blocks broken/missing

### ISSUE THREAD

**Issue by BrendanFDMoore** [angular/angular#8488]
For example: https://angular.io/docs/js/latest/api/core/testing/describe-var.html

The "Example" block should show sample code pulled form the repo. Instead it fails to find the requested resource and shows an error:
```
BAD FILENAME: ../../../../../_fragments/_api/testing/ts/testing-describeIt.ts.md   Current path: docs,js,latest,api,core,testing,describe-var PathToDocs: ../../../../../
```

Repository re-organization seems to be the culprit.

Many more samples of this are available, this is just one.

**Comment by BrendanFDMoore** [comment]
More samples:
https://angular.io/docs/js/latest/api/common/index/JsonPipe-class.html
https://angular.io/docs/js/latest/api/common/index/UpperCasePipe-class.html
https://angular.io/docs/js/latest/api/core/index/ComponentMetadata-class.html

**Comment by Foxandxss** [comment]
Hello sir, we are aware of that and there is a PR to fix that. That will be fixed soon :)

**Comment by pkozlowski-opensource** [comment]
Closing as apparently this is on the radar of the doc team and doc issues should be reported at https://github.com/angular/angular.io/issues
