### ISSUE TITLE
Missing angular-polyfills bundle in release candidate

### ISSUE THREAD

**Issue by hardik91** [angular/angular#8489]
I am using angular2 with systemjs . When I upgraded angular2 beta to @angular rc I found out that angular2-polyfills bundles are missing and in turn which breaks my project cause it is not able to find reflect-metadata and zone.js.

How can I resolve this situation?

Any help would be much appreciated.

**Comment by ericmartinezr** [comment]
You may want to read this comment https://github.com/angular/angular/issues/8412#issuecomment-216469197. As it is shown on the docs so far, you have to install zone.js and reflect-metadata, that should fix your issue.

**Comment by smith** [comment]
What if we're using other polyfills from that module (Set, Promise, Map, etc.)?

Is there supposed to be an external replacement module to use somewhere or is it just gone?

**Comment by ericmartinezr** [comment]
angular2-polyfills never contained es6 polyfills, that's what the quickstart used to teach by installing es6-shim.

**Comment by smith** [comment]
Ok looks like what I was thinking of were the es6-promise and es6-collections directories in /typings. I got these by using the modules individually.

**Comment by pkozlowski-opensource** [comment]
We no longer intend to publish angular-polyfills bundle. Include individual polyfills instead.
