### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by jbdeboer** [angular/angular#849]
The Angular project should write a documentation spec and implement it throughout their codebase.

I would propose, at minimum:
-> all exported classes have a documentation comment describing what the class does.
-> all public methods of exported classes also have a documentation comment.

**Comment by ladyborg** [comment]
Totally agree and would add:
-> clear documentation of all arguments that each public method takes.

Obviously with atscript handling types, I think the documentation should as
well.

**Comment by jbdeboer** [comment]
@ladyborg as in understanding types in comments? e.g. something like Dartdoc:

```
/**
 * This class stores [CuteAnimalTypes] and modifies incoming [SMSMessage]s to includes random animals
*/
```

**Comment by mhevery** [comment]
We are working on this. Some progress can be seen here: https://angular-mhevery.c9.io currently only have `angular2/annotations`.

as this is ongoing moving to later milestone.

**Comment by jbdeboer** [comment]
The bulk of this work will be needed for M7, we will scope it, though.

**Comment by mhevery** [comment]
I am going to close this, as this is not a measurable line in sand rather a continues process. We are hard at work on API docs as well as dev guide. We have other places where we are tracking doc progress @naomiblack and we will not be updating this bug as it is too general.
