### ISSUE TITLE
Rc1 LocationStrategy, HashLocationStrategy location?

### ISSUE THREAD

**Issue by radoslavpetranov** [angular/angular#8490]
Hi there,

I just updated my app to rc1 and I can't seem to figure out what the correct path would be for this import that I have in my existing code:

````
import {LocationStrategy, HashLocationStrategy} from 'angular2/platform/common';
````

I tried ```@angular/router``` and ```@angular/router-deprecated``` but that doesn't seem to work.

Is this a bug or am I missing something?

**Comment by ericmartinezr** [comment]
The [changelog](https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes-1) for beta.16 says that those were moved to `angular2/platform/common`, and [changelog](https://github.com/angular/angular/blob/master/CHANGELOG.md#200-rc0-2016-05-02) for RC.0 says that `angular2/platform/common` (actually says `angular2/common` which probably includes `platform/...`) was renamed/moved to `@angular/common`

**Comment by radoslavpetranov** [comment]
Thanks @ericmartinezr - I saw the Rc1 changelog but missed the beta16 one and that's why I got confused. Thanks again!
