### ISSUE TITLE
Style Binding in RC.1 does not work for some CSS selectors (background-image, transform)

### ISSUE THREAD

**Issue by Spittal** [angular/angular#8491]
**Steps to reproduce and a minimal demo of the problem**

Both of the plunks below will work if you go to `config.js` and switch `var ngVer = '@2.0.0-rc.1';` to `var ngVer = '@2.0.0-rc.0';`

Plunk showing `[style.background-image]` failing:
http://plnkr.co/edit/rRKupFRs2i4YoAU7Ayi1?p=preview

Plunk showing `[style.transform]` failing
http://plnkr.co/edit/fP12KXNfL8TxXmuydxCx?p=preview

**Current behavior**
Some style bindings like `background-image` and `transform` are not working in RC.1 however. the style binding for `opacity` *does* work. 

**Expected/desired behavior**
For the style bindings to reflect the property given to them

**Other information**
We've tested only a small set of the selectors, there may be more that do and do not work.

_All of the bindings work in RC0_

**Comment by QuentinFchx** [comment]
I'm sure this is due to this PR https://github.com/angular/angular/pull/8387
Especially [this line](https://github.com/angular/angular/pull/8387/files#diff-a37a6bff9f74b09a4bed1ed4acf080feR16)
Can't believe this regex made it to rc-1

**Comment by mprobst** [comment]
Yes, that's due to sanitization of the CSS value. We'll work on making the sanitization more lenient. In the mean time, you can explicitly mark values you know to be safe as sanitized (also see this plunkr http://plnkr.co/edit/MwQlVceeiMfKsaFCinsm):

```ts
import {DomSanitizationService} from '@angular/platform-browser';
// ...

@Component({
  selector : 'child',
  template : `<div [style.transform]="safeTransform">ASD</div>`
})
class Child {
  transform: string;
  constructor(sanitizer: DomSanitizationService) {
    this.transform = sanitizer.bypassSecurityTrustStyle('rotate(7deg)');
  }
}
// ...
```

**Comment by QuentinFchx** [comment]
or
```javascript
import {DomSanitizationService} from '@angular/platform-browser';
@Pipe({name: 'safe'})
export class Safe {
    constructor(sanitizer:DomSanitizationService){
        this.sanitizer = sanitizer;
    }

    transform(style) {
        return this.sanitizer.bypassSecurityTrustStyle(style);
    }
}
```
and here we go

**Comment by mprobst** [comment]
@QuentinFchx ack, works too, but it's a bit more efficient to only sanitize the value once, not on every digest loop.

**Comment by QuentinFchx** [comment]
The pipe is pure, so afaik it should not be evaluated more than once unless the input changes

**Comment by mprobst** [comment]
@QuentinFchx I might be missing something, but by my understanding this would still call `bypassSecurityTrustStyle` on every digest loop. Not that that's super expensive, but you'd still be causing a bunch of method calls and some object allocation.

**Comment by mprobst** [comment]
If you don't mind, I'll close this in favour of #8514, which is a bit more precise in language (but thanks for the repro!).

**Comment by flyingsky** [comment]
bypassSecurityTrustStyle output is not string, which is SafeStyle (SafeStyleImpl in runtime), so it's caused tsc warning. How do you think about it?

The only way I can do is cast it to string like this.transform = <string>(bypassSecurityTrustStyle(rawUrl))

**Comment by ericmartinezr** [comment]
@flyingsky see https://github.com/angular/angular/issues/8568

You probably could do as a workaround

`import {SafeStyle} from '@angular/platform-browser/src/security/dom_sanitization_service';`,

 you will have to try that, haven't tried it myself.
