### ISSUE TITLE
rc.1 Error:(39, 88) TS2304: Cannot find name 'Promise' and other ES6 methods...

### ISSUE THREAD

**Issue by born2net** [angular/angular#8492]
Are there changes we need to make to TypeScript definition config? 
As I am getting lots of errors from the ng2 frameworkon rc.1 from files on ES6 methods as you can see below:

![capture](https://cloud.githubusercontent.com/assets/5090936/15054331/ac86cbf0-12bb-11e6-918d-b97aa23fb38a.PNG)

regards

**Comment by jpleclerc** [comment]
Do you have es6-shim in your typings?

**Comment by born2net** [comment]
its the same config I had in 0.17 which worked just fine.

```
///<reference path="../typings/jquery/jquery.d.ts" />
///<reference path='../node_modules/angular2/typings/browser.d.ts'/>
///<reference path="../typings/browser/ambient/systemjs/systemjs.d.ts" />
// <reference path="../typings/browser/ambient/es6-shim/es6-shim.d.ts" />
///<reference path="../typings/browser/ambient/require/require.d.ts" />
///<reference path="../typings/browser/ambient/redux/redux.d.ts" />
///<reference path="../typings/browser/ambient/redux-thunk/redux-thunk.d.ts" />
///<reference path="../typings/browser/ambient/reselect/reselect.d.ts" />
///<reference path="../typings/bootbox/bootbox.d.ts" />
///<reference path="../typings/lodash/lodash.d.ts" />
///<reference path="../typings/moment/moment-node.d.ts" />
///<reference path='../node_modules/immutable/dist/Immutable.d.ts'/>
```

**Comment by born2net** [comment]
I think you are correct, in rc.1 I had to bring back the line of:
<reference path="../typings/browser/ambient/es6-shim/es6-shim.d.ts

I will pay with it some more and update

**Comment by born2net** [comment]
fixed with es6 shim that apparently is needed again rc.x

**Comment by martinnormark** [comment]
If you have a build pipeline set up in gulp, you can also include the [`typings/browser.d.ts` file when compiling](https://github.com/antonybudianto/angular2-starter/blob/master/tasks/typescript.js#L69) TypeScript sources:

```javascript
    var typingFiles = [
        'typings/browser.d.ts'
    ];
    var tsProject = ts.createProject(config.root + 'tsconfig.json');
    var allFiles = [].concat(files, typingFiles);
    var res = gulp.src(allFiles, {
            base: '.'
        })
        .pipe(tslint())
        .pipe(tslint.report('prose', {
            summarizeFailureOutput: true,
            emitError: !watchMode
        }))
        .pipe(sourcemaps.init())
        .pipe(ts(tsProject))
        .on('error', function () {
            process.exit(1);
        });
```

**Comment by kattianita** [comment]
Hello - I just updated my project from Angular2 beta to RC1 and I am getting the above errors - 
I do have  "es6-shim": "^0.35.0", in package.json in the dependencies section -- What are the other changes I need to implement?
