### ISSUE TITLE
Where did RouteParams / RouterLink / RouteConfig go in RC.X?

### ISSUE THREAD

**Issue by born2net** [angular/angular#8494]
Where did RouteParams / RouterLink / RouteConfig go in RC.X?

Can't find it in @angualr/router

tx

Sean

**Comment by jpleclerc** [comment]
RouterLink -> ROUTER_DIRECTIVES
RouteConfig -> Routes
RouteParams  -> RouteSegment

RouteSegment has a different interface, use getParam(string) instead of get(string)

**Comment by born2net** [comment]
tx!!!!!

**Comment by born2net** [comment]
I take it there is also a new members for:
ComponentInstruction, CanReuse,   OnReuse, CanActivate, OnDeactivate

where can I see these changes?

tx again

Sean

**Comment by jpleclerc** [comment]
Most of the new features aren't documented yet. We will have to guess how everything work until we have proper doc.

**Comment by ericmartinezr** [comment]
Here's the design doc for the refactoring https://docs.google.com/document/d/1WLSNV3V1AKdwLwRiLuN7JqbPBKQ_S5quRlcT5LPIldw/edit?disco=AAAAAmr7xRo#

You can see the changes on the PRs, if you go through them you can find for example this one https://github.com/angular/angular/pull/8477.

The official docs are being rewritten so we have to wait. If you have any question related to the new router you can ask over here https://gitter.im/angular/angular, you'll get answers faster.

**Comment by born2net** [comment]
tx!!!

**Comment by rixrix** [comment]
@ericmartinezr tnx for the doc link - had an issue with our old ng2 app and the link provides some good insights... cheers
