### ISSUE TITLE
jspm install not working with rc1

### ISSUE THREAD

**Issue by pehu71** [angular/angular#8496]
I tried to install @angular/common (rc1) via jspm as I used to do successfully with all betas of Angular2, but I didn't succeed. 

when I fire this command:

`jspm install npm:@angular/common`

jspm complains as follows:
err  TypeError: Install of @angular/common to 2.0.0-rc.0 has no registry property provided.

**Comment by KapuzenSohn** [comment]
I just installed all packages with `jspm install npm:@angular/packagename` and it works for me.
Maybe try again? When it still not works maybe try `jspm install npm:@angular/packagename@2.0.0-rc.1`

**Comment by playground** [comment]
Not working for me either.   jspm install angular2@2.0.0-rc.1 reflect-metadata zone.js es6-shim css

     Updating registry cache...
     Looking up npm:reflect-metadata
     Looking up npm:zone.js
     Looking up github:systemjs/plugin-css
     Looking up github:es-shims/es6-shim
     Looking up github:angular/bower-angular
ok   Installed reflect-metadata as npm:reflect-metadata@^0.1.3 (0.1.3)
ok   Installed css as github:systemjs/plugin-css@^0.1.21 (0.1.21)
ok   Up to date - es6-shim as github:es-shims/es6-shim@^0.35.0 (0.35.0)
     Looking up github:jspm/nodelibs-process
     Looking up github:jspm/nodelibs-buffer
     Looking up npm:process
     Looking up npm:buffer
     Looking up npm:base64-js
     Looking up npm:ieee754
     Looking up npm:isarray
     Looking up github:jspm/nodelibs-assert
     Looking up github:jspm/nodelibs-child_process
     Looking up github:jspm/nodelibs-fs
     Looking up npm:assert
     Looking up npm:util
     Looking up npm:inherits
     Looking up github:jspm/nodelibs-util
ok   Installed zone.js as npm:zone.js@^0.6.12 (0.6.12)

err  No version match found for github:angular/bower-angular@2.0.0-rc.1

warn Installation changes not saved.

**Comment by playground** [comment]
Turns out you will have to install Angular packages individually...

jspm install npm:@angular/common@2.0.0-rc.1 npm:@angular/compiler@2.0.0-rc.1 npm:@angular/core@2.0.0-rc.1  npm:@angular/http@2.0.0-rc.1  npm:@angular/platform-browser@2.0.0-rc.1  npm:@angular/platform-browser-dynamic@2.0.0-rc.1  npm:@angular/router@2.0.0-rc.1  npm:@angular/router-deprecated@2.0.0-rc.1  npm:@angular/upgrade@2.0.0-rc.1

**Comment by KapuzenSohn** [comment]
Oh, I thougth thast you already tried it. Does it also works when you remove the `@2.0.0-rc.1`?

**Comment by playground** [comment]
Nope.  It works if install them individually as 

jspm install npm:@angular/common@2.0.0-rc.1 npm:@angular/compiler@2.0.0-rc.1 ...

**Comment by KapuzenSohn** [comment]
Okay, strange. I don´t have to add the version.
That we have to install them individually is ok, same as we have to install them individually with npm, like they say in the Changelog.

**Comment by playground** [comment]
actually, sorry I misunderstood your question.  jspm install npm:@angular
works too.


On Sat, May 7, 2016 at 6:33 AM, Lars <notifications@github.com> wrote:

> Okay, strange. I don´t have to add the version.
> That we have to install them individually is ok, same as we have to
> install them individually with npm, like they say in the Changelog.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/angular/issues/8496#issuecomment-217632626>
>



-- 
*Jeff **Lu  *| Principal Software Engineer
*w:* 770-226-2629      *e:* jeff.lu@weather.com

**Comment by playground** [comment]
Where is system.js and system-polyfills.js?  I don't see them in jspm_packages anymore

Karma-jspm is complaining
Uncaught Error: SystemJS was not found. Please make sure you have initialized jspm via installing a dependency with jspm, or by running 'jspm dl-loader'

**Comment by pehu71** [comment]
Now it works for me as well, probably it was caused by wrong "`jspm`" section of my applications's main `package.json` file. So maybe it can be a tip for those who still fight with this issue.
