### ISSUE TITLE
rc1 new router: RouterLink doesn't generate the correct link.

### ISSUE THREAD

**Issue by jpleclerc** [angular/angular#8498]
**Steps to reproduce and a minimal demo of the problem**
http://plnkr.co/edit/TBjO78YYc4TtrTHzTVpb?p=preview

**Current behavior**
The generated link for "AppLink" is wrong. When you click it you get "VM20085 zone.js@0.6.12:421 Error: Uncaught (in promise): Cannot match any routes. Current segment: 'Test'. Available routes: ['', '/:app/...']."

**Expected/desired behavior**
Should generate a working link.

**Comment by zoechi** [comment]
Just remove `/...` AFAIK this isn't necessary anymore in the new router

**Comment by jpleclerc** [comment]
Thank you, it works now. I can navigate without any errors but the generated HREF on the <a> tag is still wrong. It is missing the APP_BASE_HREF I injected in my bootstrap so I can't "Open link in new tab".

**Comment by fknop** [comment]
I have the same issue without the `...` after the route path... I'm stucked...

**Comment by rmannibucau** [comment]
I have the same issue with rc1 cause new router didnt get all features of the old router, in particular prepareExternalUrl is not called on the url set as href which makes the strategy not respected (hash strategy misses the hash breaking all links if not accessed using click hook but direct copy/paste in another tab). This method is called in pushState so either it should be called in both hooks (click and _updateTargetUrlAndHref) or before IMO.

**Comment by vicb** [comment]
obsolete
