### ISSUE TITLE
Feature request for dart platform tools to return the evaluated change detection metrics

### ISSUE THREAD

**Issue by ananthmo** [angular/angular#8499]
See this line
https://github.com/angular/angular/blob/bb8976608db93b9ff90a71187608a4390cbd7a07/modules/%40angular/platform-browser/src/browser/tools/tools.dart#L24

Invoking that command, via javascript "ng.profiler.timeChangeDetection()", calls the "tools.profiler.timeChangeDetection(config)" method but does not return the result to the caller.  The result will contain metrics about change detection.

This will be useful for clients to process the change detection metrics, such as by plotting how it changes over time.

**Comment by ananthmo** [comment]
To add a bit, would be useful if the method returned the response in JSON format, for clients to easily interpret the metrics in return value.

**Comment by pkozlowski-opensource** [comment]
Obsolete: http://angularjs.blogspot.fr/2016/07/a-dedicated-team-for-angulardart.html
