### ISSUE TITLE
Compability with some libs (WinJS) is broken in RC. Add option to "escape" template binding operators to keep compability with some JS libs.

### ISSUE THREAD

**Issue by AloeDream** [angular/angular#8502]
I'm using WinJs. And in RC it's not working anymore, because it uses curly brackets.

Consider following component template:
`<div id="app">
	<div class="splitView" data-win-control="WinJS.UI.SplitView">
		
		<div>
			<div class="header">
				<button class="win-splitviewpanetoggle"
						data-win-control="WinJS.UI.SplitViewPaneToggle"
						data-win-options="{ splitView: select('.splitView') }"></button>
				<div class="title">Title</div>
			</div>
			<div class="nav-commands">
				<div data-win-control="WinJS.UI.SplitViewCommand" data-win-options="{ label: 'Home', icon: 'home'}"></div>
				<div data-win-control="WinJS.UI.SplitViewCommand" data-win-options="{ label: 'Hello world', icon: 'comment'}" [routerLink]="['/hello-world']"></div>
				<div data-win-control="WinJS.UI.SplitViewCommand" data-win-options="{ label: 'Settings', icon: 'settings'}"></div>
			</div>
		</div>
		
		<router-outlet></router-outlet>
	</div>
</div>`

As you can see, it uses curly brackets to set data-win-options value. In RC Angular thinks that this is binding expression and tries to parse it. Previously I was using this exact template (only router link changed) in one of latest betas and I didn't have such behavior.
Now I'm getting this:

> EXCEPTION: Template parse errors:
> Can't bind to 'href' since it isn't a known native property ("n-control="WinJS.UI.SplitViewCommand" data-win-options="{ label: 'Home', icon: 'home'}"></div>
> 				[ERROR ->]<div data-win-control="WinJS.UI.SplitViewCommand" data-win-options="{ label: 'Hello world', icon: 'co"): AppComponent@13:4
> EXCEPTION: Error: Uncaught (in promise): Template parse errors:
> Can't bind to 'href' since it isn't a known native property ("n-control="WinJS.UI.SplitViewCommand" data-win-options="{ label: 'Home', icon: 'home'}"></div>
> 				[ERROR ->]<div data-win-control="WinJS.UI.SplitViewCommand" data-win-options="{ label: 'Hello world', icon: 'co"): AppComponent@13:4
> Unhandled Promise rejection: Template parse errors:
> Can't bind to 'href' since it isn't a known native property ("n-control="WinJS.UI.SplitViewCommand" data-win-options="{ label: 'Home', icon: 'home'}"></div>
> 				[ERROR ->]<div data-win-control="WinJS.UI.SplitViewCommand" data-win-options="{ label: 'Hello world', icon: 'co"): AppComponent@13:4 ; Zone: angular ; Task: Promise.then ; Value: BaseException
> Error: Uncaught (in promise): Template parse errors:(…)
> 

Am I getting something wrong?

**Comment by ericmartinezr** [comment]
The *problem* is that routerLink only supports `<a>` tags, see https://github.com/angular/angular/issues/8357

**Comment by AloeDream** [comment]
@ericmartinezr thanks for hint, I'll check it

**Comment by AloeDream** [comment]
@ericmartinezr I tried your solution and you're right. Placing router link in <a></a> element made exceptions disappear.
Though, I find this behavior totally wrong. And it was working just fine in beta!
Now my menu looks like this:
![default](https://cloud.githubusercontent.com/assets/13584857/15097254/e38ab28e-1526-11e6-8c05-b4ec7ff34709.png)
I'll try to find a workaround, but this is really wrong. I think this should be counted as a bug.
