### ISSUE TITLE
Model values not trimming automatically in angular 2

### ISSUE THREAD

**Issue by amoldorkar-ezest** [angular/angular#8503]
**Steps to reproduce and a minimal demo of the problem**
type empty spaces in textbox and it will not show a required error message

**Current behavior**
model accepts white spaces and no required error message is thrown

**Expected/desired behavior**
model should not accepts only spaces and throws an error

**Other information**

**Comment by laskoviymishka** [comment]
White space it already something, if you want such behavior you have to implement your own validator.

**Comment by schippie** [comment]
Agree with @laskoviymishka and it's honestly is not very difficult to do:

https://github.com/angular/angular/blob/master/modules/%40angular/common/src/forms/validators.ts#L48

Is the current required validator that angular 2 provides on its own if you wanted to have it also trim the result you could do something like:

**app.ts**
```
constructor(private builder: FormBuilder) {
   this.form = builder.group({
     name: ["", CustomValidators.required]
   });
 }
```

**custom-validators.ts**
```
export class CustomValidators {
    static required(control: Control): ValidationResult {
         return isBlank(control.value) || (isString(control.value) && control.value.trim() == "") ?
               {"required": true} :
               null;
    }
}
```

Hopefully written correctly.

**Comment by smnbbrv** [comment]
@laskoviymishka 

> White space it already something

If you are a programmer and think globally - yes, if you are a user and need to insert a value which minLength is 4 and maxLength is 10 - it makes absolutely no sense to have a `Validators.minLength(4)` validation. What you propose is to write our own validators instead of built-in Validators functions; just think of in how many cases you would **not** require to trim the value (in my experience I never had the case). In fact you propose every angular programmer writing own validators just because standard ones are absolutely useless in 99% of the cases.

Technically the space is a symbol - yes. But nobody prevents us to have e.g. `Validators.required` and `Validators.requiredNoTrim`.

**Comment by laskoviymishka** [comment]
In your case probably regex validation can be prefered

**Comment by smnbbrv** [comment]
As a workaround it works, but in this case I lose control over the error message. E.g. I have regex validation which is about to check the not allowed symbols and let's say I allow spaces in the name. Now we additionally say the regexp validation should check for the length as well, e.g. `^[a-z ]{4,10}$`. I don't know what was the reason of the `pattern` error: the symbols or the length so there is no way to show a proper message to the user, only something like 'Your input is wrong' can work out.

As I already told, there are ways to do things, but in my opinion angular should support trimming in some way out of the box.

**Comment by laskoviymishka** [comment]
you could add 2 validators - one for length, another one for non empty string. That simple.
If you have only spaces - say to people, that only spaces is illegal. 
If you have to few input entered - say to people, that they should add more.
Keep it simple ;)

**Comment by smnbbrv** [comment]
yes, but again you say about custom validators. Exactly this is not simple :) Simple is when I take the validator which already exists and work with it. Not simple is when validator which already exists is nearly always useless.

**Comment by kara** [comment]
The required validator is intended to mimic how the native required validator works (it also accepts white spaces as valid input).  Apps will all have different requirements, so as a framework, it doesn't make sense for us to depart from the native functionality and prescribe that white spaces don't count globally.  As mentioned above, creating a custom validator for this would be the preferred solution.

**Comment by khashayar** [comment]
You may want to take a look at [TrimValueAccessor](https://github.com/khashayar/ng-trim-value-accessor), which is an equivalent of AngularJS `ng-trim`

**Comment by jberall** [comment]
cc @vikramtiwari

**Comment by jberall** [comment]
Validators.requiredTrue seems to consider whitespaces.
However the Input trim is still an issue

**Comment by namzee-repos** [comment]
https://github.com/angular/angular/issues/8503

**Comment by tommck** [comment]
@derek90 `keyup` doesn't handle pasting values

**Comment by derek90** [comment]
@tommck change the keyup event to another, like change or just add a paste event too. The logic will be the same
