### ISSUE TITLE
rc.1 view not refreshing when model changes in IE 11

### ISSUE THREAD

**Issue by pgarge** [angular/angular#8505]
First time the template draws correctly but if the model data is refreshed the view doesn't get refreshed and uses the old value, this is happening in IE, other browsers work fine.

I am using zone and reflect-metadata.

Also, if you have developer's tool open in IE it works.

**Comment by zoechi** [comment]
Can you provide a Plunker that allows to reproduce the issue?

**Comment by hanijizan** [comment]
Are you sure it works when developer window is open? if so, it's most likely a caching issue somewhere. Is the data refreshed from the server by ajax call or is it changed inside browser itself?

**Comment by pgarge** [comment]
IE was caching the ajax calls, have to pass these headers:

import {Headers, BaseRequestOptions} from "@angular/http";
import {Injectable} from "@angular/core"

@Injectable()
export class DefaultRequestOptions extends BaseRequestOptions {
    headers: Headers = new Headers({
        "Cache-Control": "no-cache",
        "Pragma": "no-cache"
    });
}

Use it like this:
bootstrap(LongProfile, [HTTP_PROVIDERS, provide(RequestOptions, { useClass: DefaultRequestOptions })]);

This fixes this issue.
