### ISSUE TITLE
rc1 new router: child routing issue

### ISSUE THREAD

**Issue by andrui** [angular/angular#8507]
Hi,

I have app component with root routing ( two components ). Component 1 has own routing config with two subcomponents. But when I try to open subcomponent route link I receive exception:
EXCEPTION: Error: Uncaught (in promise): TypeError: Cannot read property 'annotations' of undefined

Here is demo: https://plnkr.co/edit/8QP1BBI3qGgwedKrJB6W?p=preview

STR:
1) Click 'Page 1'
2) Click 'Subpage 1.1' or 'Subpage 1.2'

AFAIK new router doesn't require '/...' for child routes. And from 'RouterLink' code comment:

> If the segment begins with `./`, or doesn't begin with a slash, the router will instead look in the current component's children for the route.

Any ideas what is wrong?

**Comment by ericmartinezr** [comment]
Move `Subpage1_1` and `Subpage1_2` above `Page1`

**Comment by andrui** [comment]
@ericmartinezr, Thx!
