### ISSUE TITLE
Debug change detection appears to run when prodmode is called

### ISSUE THREAD

**Issue by escardin** [angular/angular#8508]
**Steps to reproduce and a minimal demo of the problem**
http://plnkr.co/edit/oOsWYXMeXMq7nPzBLETH?p=preview
In the console, the same number of change detection calls shows up whether prodmode is enabled or not.
_What steps should we try in your demo to see the problem?_
Enable/disable prod mode and compare change calls in the console.

**Current behavior**
As many change detection cycles as when in debug mode.

**Expected/desired behavior**
Approximately half as many change detection cycles.

**Other information**
Totally not sure if I've reproduced this correctly.

**Comment by beakdoctor** [comment]
I can add that it didn't seem to be this way back in beta 17. IE 11 got a huge speedbost by enabling prodmode but it doesn't have any effect anymore as far as I can see.

**Comment by jhades** [comment]
I just noticed the same while profiling an angular universal app. The app is in production mode (100% sure), no enableProd Mode warning shows. And we can see that the DebugAppView is present at multiple places in the component tree, for a run in production mode:

![screen shot 2016-05-18 at 9 51 16 pm](https://cloud.githubusercontent.com/assets/5454709/15372835/b8703672-1d42-11e6-9581-053eac28cc68.png)

**Comment by shaharvaldman** [comment]
We're experiencing the same behavior.
It is very difficult to analyze the performance of an angular2 application (especially the change-detection cycle) when the app appears (?) to spend so much time on Debug mode, even though we tried to disable it.
Is the production-mode not ready yet, or is this the expected behavior in production?

**Comment by tbosch** [comment]
See #9295 for a workaround. Will fix this ASAP. 
Closing this issue to track in #9295.
