### ISSUE TITLE
Angular 2.0.0-rc.1 no longer exports BrowserDomAdapter

### ISSUE THREAD

**Issue by rn1d** [angular/angular#8509]
Prior to Angular 2.0.0-rc.0, it was possible to import and use BrowserDomAdapter in the application. Seems like it is no longer exported from @angular/platform-browser. Is this intentional or a bug? 

Originally, I asked the question on StackOverflow: http://stackoverflow.com/questions/37068937/accessing-dom-in-angular-2-rc

Is there an API that should be used instead?

**Comment by mprobst** [comment]
Could you just implement `DomAdapter`?

**Comment by twilliamsgsnetx** [comment]
Dealing with this issue myself. Where is DomAdapter?

**Comment by mprobst** [comment]
I spoke to soon, `DomAdapter` isn't exported either.

The disappearing `BrowserDomAdapter` is an accidental side effect of @IgorMinar's big package refactoring in a66cdb4. That also seems to have disabled the former API test.

**Comment by naveedahmed1** [comment]
Martin can you please also check AnimationBuilder, it seems this has also been removed. The below line doesn't work anymore:

import {AnimationBuilder} from 'angular2/src/animate/animation_builder';

**Comment by mprobst** [comment]
@naveedahmed1 `'angular2/src/animate/...` should be `@angular/platform-browser`, but I think the export for `AnimationBuilder` also got accidentally removed.

**Comment by naveedahmed1** [comment]
Ok, thank you Martin for the information. It seems currently the beta 17 is more stable than RC1.

**Comment by Falx** [comment]
Are there any reasons to use `BrowserDomAdapter` in favor for plain js `document` ?

**Comment by mprobst** [comment]
@Falx `document` works as long as you don't render on the server side. But beware of XSS bugs!

**Comment by Falx** [comment]
Ok thanks, because I removed `BrowserDomAdapter` when I saw it wasn't exported anymore, in favor of `document`. But I seems it would be better to add it in again, once fixed.

**Comment by twilliamsgsnetx** [comment]
So is using document fine then? I thought we encouraged to not use it in favor of browserdomadapter

**Comment by IgorMinar** [comment]
DomAdapter, BrowserDomAdapter and Parse5DomAdapter are just implementation details and should not be used as public apis. This is why you can't find it any more in the public api surface.

If you need access to document then you can inject it via the [`DOCUMENT` token](https://angular.io/docs/ts/latest/api/platform-browser/index/DOCUMENT-let.html). If you don't care about DI then you can access it directly. If you are using web workers and want to render stuff into dom then you should be implementing a [custom renderer](https://angular.io/docs/ts/latest/api/core/index/Renderer-class.html).

**Comment by zoechi** [comment]
@IgorMinar any pointer how to create and provide a custom renderer for different platforms (browser, webworker, server, ...)

**Comment by Elvynia** [comment]
@IgorMinar I was using `requestAnimationFrame(callback): number` which was handy and it's still only available through `DomAdapter`. If dom adapters are kept in the private API, will it be accessible from elsewhere ?

**Comment by zoechi** [comment]
@Elvynia it's in the private API only because it is not supposed to be used outside Angular itself.

**Comment by Elvynia** [comment]
@zoechi Sure I get it. I'm calling `requestAnimationFrame` directly in my component and it works. But I think the implementation in `DomAdapter` support all browsers with the right polyfills and it was helpful.

**Comment by mprobst** [comment]
@Elvynia nope, `DomAdapter` is not a polyfill, it just calls into the browser APIs directly. It's purpose is to abstract between actual browsers, a virtual DOM in NodeJS on the server side, and Dart APIs.

**Comment by zoechi** [comment]
@mprobst AFAIK this is necessary for custom code to be compatible with server side rendering and webworker.
I have seen this question dozens of times and when there was an answer it was one of

- don't access the DOM directly
- don't use `BrowserDomAdapter` it's only for internal use
- use a custom renderer

It would be great if someone could point out how to implement and provide a custom renderer.

**Comment by twilliamsgsnetx** [comment]
@IgorMinar When trying to use DOCUMENT it says cannot find name DOCUMENT. How exactly is it supposed to be used to replace what BrowserDomAdapter accomplished?

**Comment by IgorMinar** [comment]
this should do the trick:

```
import {Inject, Component} from "@angular/core";
import {DOCUMENT} from "@angular/platform-browser";

@Component(...)
class MyComponent(@Inject(DOCUMENT) doc) {}
```

**Comment by Falx** [comment]
@twilliamsgsnetx  So I had the same problem as you. This is how I figured it out (since documentation is not complete yet). As you can see [here](https://angular.io/docs/ts/latest/api/platform-browser/index/DOCUMENT-let.html): DOCUMENT is an OpaqueToken. I searched for that concept and found out that it is a mechanism to have a handle to inject something that you would normally name with a String. Since if you have multiples of that, they all have the same type (String) and DI would not be able to deduce which provider to use for that type. 
By using the **@Inject** syntax you can use this DOCUMENT token with Dependency Injection.


```
import { Component, Inject } from '@angular/core';
import { DOCUMENT } from '@angular/platform-browser';

@Component({})
class MyClass {

    constructor (@Inject(DOCUMENT) private document) { }

    doSomething() {
        this.document.someMethodOfDocument();
    }
}
```

**Comment by Falx** [comment]
Ah it seems @IgorMinar beat me to it ;-P

**Comment by thekalinga** [comment]
@zoechi Did you get answer for your question?

Tho you can access `document` object using the above method, you cant do the same for `window` (or can you?)

I was trying to get the computed value of a native element using `window.getComputedStyle(elementRef.nativeElement)` & am left with no option other than accessing window object directly.

Does anyone know any better solution other than accessing window directly?

**Comment by matheo** [comment]
@IgorMinar What's the way to access the `document` with AoT?
DOCUMENT is not provided in this scenario and injecting it into `platformBrowser` with:
```
{ provide: DOCUMENT, useValue: document }
```
doesn't work. A custom renderer is needed? TIA
