### ISSUE TITLE
Angular testing doesn't support pending specs (it with no function)

### ISSUE THREAD

**Issue by abierbaum** [angular/angular#8512]
**Steps to reproduce**

In any angular test suite using Jasmine, add a line like:

```
it("can be declared with 'it' but without a function");
```

In standard Jasmine use, this means a pending spec.  The wrappers that are used for ng2 don't support this variation.  

See "Pending Specs" in the jasmine docs: http://jasmine.github.io/2.4/introduction.html

**Comment by pkozlowski-opensource** [comment]
We are not wrapping Jasmine, using bare-bones one. Thus you should be able to use all the capabilities of Jasmine.
