### ISSUE TITLE
Where's the equivalent of 'typings/browser.d.ts' for Angular RC1?

### ISSUE THREAD

**Issue by curlyfro** [angular/angular#8513]
in Visual Studio 2015/angular betas i was able to get my typescript typings working by adding a reference path in my boot.ts:

/// `<reference path="../node_modules/angular2/typings/browser.d.ts" />`

this file doesn't exist under the rc @angular2 paths.  does  anyone know the equivalent or how to get the typings working for VS2015?

**Comment by ericmartinezr** [comment]
It should be enough by installing es6-shim typings and adding `typings/browser.d.ts` (from the root folder).

Option1 : 
```
typings install es6-shim --ambient --save

// In your app.ts
/// <reference path="typings/browser.d.ts" />
```
Option 2:
```
typings install es6-shim --ambient --save

// In your tsconfig.json
files : ["typings/browser.d.ts", "everything else..."]
```

Alternatively you can remove es6-shim typings, and if you're using TS >= 1.9 you can add `lib: ["es6", "dom"]` to your tsconfig.json.

**Comment by hanijizan** [comment]
Another way would be to use 'es6' as the value of 'target' in your tsconfig.json. The errors you'll probably see on compile all go away.

**Comment by curlyfro** [comment]
thanks eric -- that worked!
