### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by jonnysamps** [angular/angular#8517]
**Steps to reproduce and a minimal demo of the problem**

1. Clone repo
2. Using:
  - nvm: 0.29.0
  - npm: 3.8.9
  - node: 5.4.1
3. Follow build instructions: 
  - `npm install` and get
    ```:-( npm dependencies are stale or in an in unknown state!```
  - `$(npm bin)/gulp build`
4. Get all sorts of Typescript compiler errors and 

```
Error: Cannot find module './dist/tools/broccoli/angular_builder'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at DestroyableTransform.<anonymous> (/Users/jonathansamples/projects/angular/gulpfile.js:1179:34)
    at emitNone (events.js:72:20)
    at DestroyableTransform.emit (events.js:166:7)
    at endReadableNT (/Users/jonathansamples/projects/angular/node_modules/gulp-sourcemaps/node_modules/readable-stream/lib/_stream_readable.js:960:12)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickCallback (node.js:388:17)
```

**Comment by aburlak** [comment]
I had more luck with ./build.sh instead of the gulpfile, but I still had to edit it by hand (it uses non-portable 'sed' syntax, assuming MacOS).
I also had to copy around some directories to work around
'Could not resolve module @angular/core/src/di/provider relative to /home/build/angular/index.ts' error in compiler_cli.

I don't know what are the actual correct building steps for Linux - so I want the developers to comment on that.

**Comment by ericmartinezr** [comment]
Can someone who knows comment on how to build succesfully the latest master? A lot of users who want to contribute for the first time are getting stuck on this issue.

@aburlak 's made a point here, and it seems that `$(npm bin)/gulp build` is not the correct way to build anymore, but running `./build.sh` throws a lot of TS errors and it fails. 

I'm stuck at this too.

**Comment by gonzofish** [comment]
seems a bit obvious, but without running `$(npm bin)/gulp build` you'll get an error saying `./dist` doesn't exist.

What directories did you copy around @aburlak?

**Comment by luisdogg13** [comment]
I only get a few errors when running `$(npm bin)/gulp build`

They appear to be related to the rename of "angular2" to "@angular"... for example
`Error: ENOENT: no such file or directory, lstat 'modules/angular2'
    at Error (native)
    at Object.fs.lstatSync (fs.js:887:18)
    at symlink (/angular/node_modules/symlink-or-copy/index.js:63:26)
    at symlinkOrCopySync (/angular/node_modules/symlink-or-copy/index.js:58:5)
    at /angular/node_modules/broccoli-plugin/read_compat.js:58:9
    at lib$rsvp$$internal$$tryCatch (/angular/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/angular/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/angular/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/angular/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)`
    at symlink (/angular/node_modules/symlink-or-copy/index.js:63:26)
    at symlinkOrCopySync (/angular/node_modules/symlink-or-copy/index.js:58:5)
    at /angular/node_modules/broccoli-plugin/read_compat.js:58:9
    at lib$rsvp$$internal$$tryCatch (/angular/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/angular/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/angular/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/angular/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)`

but when I look in the "modules" folder there is an "@angular" folder not "angular2".

Maybe I'm misunderstanding something, but just figured I'd add my experience trying to get this thing building.

**Comment by gonzofish** [comment]
i noticed also that, for me at least, the `_checkCache` in `tools/npm/check-node-modules.js` is failing because it cannot find `node_modules/.npm-shrinkwrap.cached.json`

**Comment by aburlak** [comment]
I've made a small script that does the necessary steps to build the JavaScript/TypeScript version of Angular from the current master branch.
Didn't try building Dart version yet.

**DISCLAIMER**: These are not official build instructions and will likely become obsolete very soon. Use at your own risk!

1) Make sure your NodeJS version is >= 5.4.1 but < 6.0 (check with `node -v`)
If your distro is already on Node 6.x, use nvm to install NodeJS 5.11.1 locally.

2) Clone the repo and run `npm install`. 
Ignore `:-( npm dependencies are stale or in an in unknown state!` message - it's a bug (preinstall script checks for the file that is created only at postinstall).
As a workaround, you may run `npm run postinstall` and then `npm install` again  (but it's not necessary).

3) Unless you are on Mac, you have to run
 `export TRAVIS=true`
in your Bash session.
Alternatively, you can fix the OS detection bug in the ./build.sh script (as shown [here](https://github.com/aburlak/angular/commit/68432ce80237fba77aaa955311c2b5043ba444b0))

4) Put [the following script](https://github.com/aburlak/angular/blob/master/build-packages.sh) in your Angular working directory and run
`./build-packages.sh`

Ignore the `Your node_modules directory is stale or out of sync with npm-shrinkwrap.json` warning - it's a consequence of the preinstall script issue desribed above.

5) The output should be in `./dist/packages-dist/`
The packages will have version `2.0.0-rc.1` (can be overrriden by setting `ANGULAR_VERSION` environment variable)

**Comment by joost-de-vries** [comment]
I don't think it's necessary to maintain your own build script. I had success building and testing using the scripts that are [used by travis CI](https://github.com/angular/angular/blob/master/.travis.yml) as well.  
I.e. `./scripts/ci-lite/install.sh` to install.

See also [this issue](https://github.com/angular/angular/issues/8637)

**Comment by aburlak** [comment]
To joost-de-vries: I was looking to produce the output that is as close as possible to the official packages published on NPM (without actually publishing the packages, and without any OS X dependency).

The scripts in ./scripts/ci-lite do not, by themselves, produce the same output (e.g. no UMD bundles, no package.json, etc.).
The script 'test_e2e.sh' will almost do the right thing, but it will work only in a very particular environment (either OS X or, if TRAVIS is set, you have to make the environment compatible with ./env.sh, for example it sets CXX=g++-4.8).
And it will attempt to run tests (including browser tests) and publish the packages, which is not what I want.

I am building on Linux and using the produced NPM packages on Windows (the only reason I am buiding my packages is to work around some bugs, and to be able to rebuild the packages with the most recent changes).

**Comment by tycho01** [comment]
I'm trying to build on Windows; same build errors as @jonnysamps.
* On Windows, the `$(npm bin)` in `build.sh` doesn't seem to be working either (npm itself works fine).
* It also seems to assume a globally available `ng2tc`, which depends on `@angular`, implying prior global install of that?

At that point it's getting pretty confusing which parts it's supposed to load from where, and in fact, invoking `ng2tc` then triggers a `can't resolve module @angular/core/src/di/provider from D:\shared\js\angular\index.ts` for me; no clue why.

**Comment by vicb** [comment]
Use /build.sh for now
