### ISSUE TITLE
[Dart] CSS @import not behaving as documented (TS)

### ISSUE THREAD

**Issue by chalin** [angular/angular#8518]
The Dart equivalent of the [Dev Guide Component Styles example][1], doesn't behave like its TS counterpart when it comes to CSS `@import`s.

**Steps to reproduce and a minimal demo of the problem**

I will post a URL to the Dart sources in a followup comment to this issue (as soon as I can). In the meantime, the relevant files are:

* `lib/hero_details_componet.dart`:

> ```dart
@Component(
    selector: 'hero-details',
    template: ...,
    styleUrls: const ['hero_details_component.css'],   /*<<<<<<<*/
    directives: const [HeroTeamComponent])
class HeroDetailsComponent {
  @Input() Hero hero;
}
```

* `lib/hero_details_componet.css` (excerpt):

> ```css
@import 'hero_details_box.css';   /*<<<<<<<*/
:host {
  display: block;
  border: 1px solid black;
}
...
```

**Current behavior**

An attempt at doing a **`pub build` fails** with the error:
```nocode
Building component_styles...
Build error:
Transform StylesheetCompiler on component_styles|lib/hero_details_component.css threw error: Url component_styles|lib/hero_details_component.css.dart is not a valid asset: url
```

Replacing the `@import` target with other values yields the given results:
* `@import 'foo.css'` - pub build error (as described above).
* `@import '/foo.css'` - gets **web/foo.css** and the CSS for
  - normal selectors work, but 
  - **ng special selectors** like `:host` **do not work**.
* `@import '/packages/component_styles/foo.css'`<br>gets **lib/foo.css** and the CSS has the same issues as `@import '/foo.css'`.

**Expected/desired behavior**

According to the [Dev Guide Component Styles, CSS @imports subsection][2]:
> We can also import CSS files into our CSS files by using the standard CSS @import rule.
> In this case the URL is relative to the CSS file into which we are importing.

**Other information**

This was tested with **beta.17**. Possibly related (but different) issues:
* CSS @import with root path "/" bug #6449
* Transformer does not work well with web urls #2607
* styleUrls does not work with root path "/" #4974

[1]: https://angular.io/docs/ts/latest/guide/component-styles.html
[2]: https://angular.io/docs/ts/latest/guide/component-styles.html#css-imports

**Comment by kwalrath** [comment]
@mhevery could you take a look?

**Comment by mhevery** [comment]
@tbosch can you have a look?

**Comment by chalin** [comment]
Migrated to https://github.com/dart-lang/angular2/issues/39.
