### ISSUE TITLE
Binding get and set property in Angular 2

### ISSUE THREAD

**Issue by Tech-Rk** [angular/angular#8520]
I have get and set properties named `position`. I have a position saved in a variable `positionInPerc` that has position stored in percentage(%) and it has a default some default value. By position I mean the position of a div. `get position` will take value from `positionInPerc` and convert the position from percentage to pixel and return it. `set position` will take value in pixel and convert it to % and set the value to variable `positionInPerc`.

Code :

In component -

    private positionInPerc:number;
    public get position() : number {
        return this.Helper.convertFromPercToPx(this.positionInPerc);
    }
    public set position(value){
        var converted = this.Helper.convertFromPxToPerc(value);
        this.positionInPerc = converted;
    }

And in HTML -

    <div [style.top.px]="position"> Hello </div>

Is there anyway in Angular 2 that I can bind getter setter with the html? If not, can we have getter setter binding in Angular 2?

**Comment by zoechi** [comment]
I don't understand the problem. What do you try to accomplish and what are you missing to be able to do it?

Sounds a bit like you want two-way-binding to a style property?

**Comment by Tech-Rk** [comment]
Yes, I want two-way binding on a style property, but using getter/setter only. But after a research, I found that Angular 2 doesn't support binding to getter/setter yet. Do you know any way I can achieve this? Also, out of curiosity, I want to know why Angular 2 isn't supporting binding to get/set? Will it be supported in future?

**Comment by zoechi** [comment]
Angular doesn't support 2-way binding in general for performance reasons. I supports binding from the model to the view and from events to the model. I don't think it's planned to change that. That's a quite basic principle of Angular2. So the problem are not the getter/setters but that the styles don't emit an event when the value changes. You could create a custom directive that polls style values and emits an event in case the value changed as a workaround for the missing native support.

**Comment by Tech-Rk** [comment]
Thanks @zoechi for your response and suggestion. I needed a cleaner way to implement it. But I think directive is also a useful option.

**Comment by pkozlowski-opensource** [comment]
Sounds like a general support question, see: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
