### ISSUE TITLE
After you refresh the browser should go to the router path.

### ISSUE THREAD

**Issue by racktime** [angular/angular#8521]
http://url.com/routerpath

After you refresh the browser should go to the router path.
but  The move to the root url.

What should I do?

**Comment by dloukadakis** [comment]
Just tested seems to be working fine for me.

Are you sure your server is not performing a redirect?

Keep in mind the request browser sends on refresh is on url "http://url.com/routerpath" so you might want to map any request that is handled by the client-side router to your index file on server.

**Comment by zoechi** [comment]
http://stackoverflow.com/questions/31415052/angular-2-0-router-not-working-on-reloading-the-browser

**Comment by pkozlowski-opensource** [comment]
Thnx @zoechi !
