### ISSUE TITLE
New router [rc.1] - Browser back & forward buttons not working correctly

### ISSUE THREAD

**Issue by dominique-mueller** [angular/angular#8524]
**Current behavior**

Currently I see two issues when navigating with the new router:

* When pressing the browser back button, I get redirected to the previously opened page (so this works) - but the forward button of the browser is (always) greyed out and cannot be used. Is this a bug or a decision?

* When I click on a router link which links to a another route using an absolute route path, and this route path is the same I'm already in, the route will not be reloaded (which is good) - but mysteriously the browser back button completely breaks and cannot be used any longer.

**Expected/desired behavior**

Well, it would be nice if the user just can use the browser navigation buttons in any Angular 2 application. Maybe this aspect just hasn't been developed yet?

**Other information**

Tested on both Chrome & Firefox (latest versions) with identical behaviour.

**Comment by neilhem** [comment]
It seems like will be implemented/fixed ASAP

**Comment by ravinderpayal** [comment]
Same problem here 
[StackOverflow Question](http://stackoverflow.com/questions/37192628/history-forward-backward-button-doesnt-work-angular-2-router)

**Comment by AhsanAyaz** [comment]
+1 ..

**Comment by jmurphzyo** [comment]
Also when using the back button it will only go back one route.
