### ISSUE TITLE
RC.1 Router - Get route params from parent route.

### ISSUE THREAD

**Issue by innovative1** [angular/angular#8526]
The new router is lacking a critical feature which is a very common use case when you have nested routes:
There's no way to access a parent's route params.
Say you have a parent route with parameter `id`, and a child route needs to know which item id this is.
Using `Input`s isn't the solution because there might be `<router-outlet>`s or `routeLink`'s between the parent and child, and the nesting might be several levels deep, such that the parent can not pass the data directly to the child.

In the deprecated router, a workaround was to use the Injector, as indicated in this post.

http://stackoverflow.com/questions/34906888/angular-2-access-parent-routeparams-from-child-component

This does not seem to work anymore and this was always a workaround. 
There should be a way to access parent route params. Maybe something like:

`router.parent.get('id')`

or using the `RouteSegment`s

```javascript
routerOnActivate(curr: RouteSegment, prev?: RouteSegment, currTree?: RouteTree, prevTree?: RouteTree): void {
    this.itemId = curr.getParent().getParam('id');
}
```

**Comment by Delagen** [comment]
Seem to work as expected:
```
currTree.parent(curr).getParam("id")
```

**Comment by innovative1** [comment]
Right. That does work as expected. Did not find this API since it's not yet documented.
Closing this issue
