### ISSUE TITLE
Get the "router-activated" component from the actual router

### ISSUE THREAD

**Issue by maximedupre** [angular/angular#8528]
Before the RC version, one could easily get access to the "router-activated" component like so:

    // $event represents the "router-activated" component
    <router-outlet (activate)="$event"></router-outlet>

This allowed easy interaction between the router and the "router-activated" component (The router being the component that has the `@Routes` annotation).

I know there is the `OnActivate` interface, but this doesn't allow communication between the router and the "router-activated" component.

**Comment by vsavkin** [comment]
This issue has been implemented in the new router.
