### ISSUE TITLE
challenge: help update this ng2 stopwatch plunkr to ng2 rc.1

### ISSUE THREAD

**Issue by born2net** [angular/angular#8530]
would be awesome if we could get this plunkr updated to rc.1 as the docs are still not available and would be a great example on how this is now done in the new API:

StopWatch: http://plnkr.co/edit/4pToagzeAI5wuLgHg61j?p=preview

**Comment by ericmartinezr** [comment]
Please read https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by born2net** [comment]
got it tx...
