### ISSUE TITLE
rc1 new router: navigation is not performed when same component is used for both routes 

### ISSUE THREAD

**Issue by mdudek** [angular/angular#8533]
The routerOnActivate is not called when same component is used for both routes.

Here's a plnkr with RC.0 reproducing the issue: http://embed.plnkr.co/iIBWMr7e5Tt0i7VYmxlw/

**Comment by IgorMinar** [comment]
This issue was made obsolete by router v3: https://angularjs.blogspot.com/2016/06/improvements-coming-for-routing-in.html

If you believe this is not the case, please file a new issue updating the description to router v3. thank you!
