### ISSUE TITLE
Inconsistent Form State -  using ngFormModel (removeControl API)

### ISSUE THREAD

**Issue by afirdousi** [angular/angular#8534]
If we use [ngFormModel] on our Angular 2 forms and try to dynamically delete controls from it, the controls is removed but the form remains in inconsistent state unless I call the ** updateValueAndValidity** or do *model[controlName] = false;* . It's not a bug but a slight improvement in our form API. I think removeControl() should always be calling *updateValueAndValidity* implicitly.

**Plunkr**
http://plnkr.co/edit/xWuAkxaB8ayMTDe2h2rF?p=preview

**Steps on Plnkr**
1. Add values to the configName and configToken fields 
2. Hit save button
3. Now click on any of the 'Delete' button
4. Notice the *Payload* of the form (form model) still has the deleted control in it but the control itself is removed from the form which can be seen on *Individual Controls* list.
5. Look into src/form.ts file for fix within deleteControl() method. I have listed 2 options. 

**Expected/desired behavior**
removeControl() should have explicitly called updateValueAndValidity()

**Other information**
-Click below to check our ngFormModel in Angular Core here with line highlight:
https://github.com/angular/angular/blob/119abe7bb93d5992699f3ab8ebb4c5f749fcc9c7/modules/%40angular/common/src/forms/directives/ng_form_model.ts#L150

It calls ListWrapper.remove which is a generic remove method found here:
https://github.com/angular/angular/blob/119abe7bb93d5992699f3ab8ebb4c5f749fcc9c7/modules/%40angular/facade/src/collection.ts#L214-L221

**in contrast to above API** , check the base [ngForm] removeControl() API here:
https://github.com/angular/angular/blob/119abe7bb93d5992699f3ab8ebb4c5f749fcc9c7/modules/%40angular/common/src/forms/directives/ng_form.ts#L120-L128

Is it on purpose? Please let me know if I am missing something.

**Comment by kara** [comment]
Thanks for reporting! This should be fixed in RC.2, so closing: 
https://github.com/angular/angular/commit/50acb96130f74ba1e82db27e49f1a3b508ab4154.
