### ISSUE TITLE
HtmlParser ,  endSourceSpan = null

### ISSUE THREAD

**Issue by valentin78** [angular/angular#8535]
Clarify how work Html parser. I made small example, where you can see in console parse result and rootNode object has endSourceSpan == null, but type is HtmlElementAst, Why so?
http://plnkr.co/edit/oMQGAbg7qBLOl4zzhmkC?p=preview
that is bug or feature?

**Comment by sir-valentin** [comment]
http://plnkr.co/edit/yOBe6c0Joxs6xc7EB2tS?p=preview

**Comment by valentin78** [comment]
i added sample in plunker where you can see how parsed that html piece
```
<div><span></span><div>
div
  |_ span
  |_ div
```
