### ISSUE TITLE
router randomly reloads page

### ISSUE THREAD

**Issue by rahulbats** [angular/angular#8537]
i am using this to go to a route 
router.navigate(['/hero']);

but it puts a hero? and then reloads the page. 
It goes to the page but does a unnecessary refresh.

I found that if i used a routerlink instead, it does not do that.
Also weirdly if i move the button out of the form tags , it does not give the issue

**Comment by CaptainCodeman** [comment]
What do you mean by "unnecessary refresh"? is it that the page is completely re-loading or just some component(s) being re-rendered?

You may want to look at the `routerCanReuse` hook which can help with the latter. Return `true` and it will sometimes save some re-rendering of things on the page (make sure you use `routerOnReuse` as well as `routerOnActivate` to pick up parameters).

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by Namek** [comment]
Maybe try bootstrapping with `HashLocationStrategy`.

**Comment by Arbixal** [comment]
I found a similar issue (only in Chrome) if the function called by the button does not return false or alternatively calling preventDefault on the click event.

**Comment by radoslavpetranov** [comment]
Same issue. Say I'm at the following URL creating a new entity

```
http://localhost:8080/#/person/new
```

I fill up the form and hit the create button. The service is called and after it succeeds I have the following line

```
this._router.navigate(['/Person']);
```

which should take me to ```http://localhost:8080/#/person``` but instead, it takes me to
```http://localhost:8080/?#/person``` which needless to say refreshes the entire page.

I will try to put a plunker together sometime tomorrow to demonstrate the issue.

**Comment by brandonroberts** [comment]
@radoslavpetranov the comment by @Arbixal applies in your situation also. You button needs a `submit` type or you need to return false in your function. See #6154

**Comment by radoslavpetranov** [comment]
Oh thanks @brandonroberts & @Arbixal  - I totally missed that comment. I added a return false to the ```(click)``` function and it's all set now. I'm not sure if this is a bug or expected behavior but the workaround works great - thanks guys!

**Comment by IgorMinar** [comment]
This issue was made obsolete by router v3: https://angularjs.blogspot.com/2016/06/improvements-coming-for-routing-in.html

If you believe this is not the case, please file a new issue updating the description to router v3. thank you!
