### ISSUE TITLE
get access to ngForm in a component for template driven forms

### ISSUE THREAD

**Issue by squadwuschel** [angular/angular#8538]
Feature Request:

I would like to use template driven forms, like in NG1 with ngModel and that works fine so far. But I need to get the current form status like touched or dirty in my component (in functions like "routerCanDeactivate" where I can't pass the ngForm) for the current form and I don't want to create the hole form with the formBuilder. 

I use the system with asp.net mvc and I get my viewModels from my .NET controller (ajax calls) and I like to bind the viewModel data directly to the view with ngModel and so I can directly send the modified Modeldata back to ASP.NET and I don't need to create the hole data structure twice. I only want to set the properties with two way databind with ngModel and don't want to create a hole formBuilder to rebuild my existing viewModel.

**Current behavior**
currently its not possible to get the current form status like "dirty" or "valid" in the component (e.g. the "routerCanDeactivate" function, here I can't pass the form as parameter) without creating the hole form "twice" once with ngModel and with the formBuilder.

That works great:

    <form #frm="ngForm" (ngSubmit)="save(frm)">
        <input [(ngModel)]="user.name" #name="ngForm" required type="text" >
        <span *ngIf="name.touched && name.errors"> 
                  <label *ngIf="name.errors?.required">Please insert name</label>
        </span>
    </form>

But It's not possible to access the "frm" in the component to check status values or reset the form status.

**Expected/desired behavior**
I only want to use the possiblity to create the form with the ngModel directive, that works great and is a lot less to write in TypeScript code, just some directives in HTML.

    @Component({ ... } 
     export class AddUserComponent implements CanDeactivate {

      routerCanDeactivate(nextInstruction: Object, prevInstruction: Object): boolean |   Promise<boolean> {
         //Thats not working I know, but like this it was possible in NG1
         if (this.frm.dirty) {
            return confirm("Want to change?");
        }
            return true;
         }
     }

So far I know you allready build a "formBuilder" structur in the background for the temaplte driven forms, can you just open the access to this model, because when I need to find some controls in the formBuilder I also need to use the find function and a STRING to get the right control.

**Comment by zoechi** [comment]
To get a reference to the form you can use

```ts
@ViewChild('frm') form;
```
https://plnkr.co/edit/1KmG32bxpzuFri1ployd?p=preview

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by squadwuschel** [comment]
I know, but I got no answer and thought its not possible. So I decided to create a feature request. Thx for your Solution.

**Comment by zoechi** [comment]
`form` is not yet set in the constructor, only when `ngOnInit()` is called.  You might know that, just to be sure.

**Comment by squadwuschel** [comment]
thx much works fine so far - the only thing I have to add is "ngControl" to my input field, only then the frm Values are set right like valid:false in the component.

    <input [(ngModel)]="user.name" #name="ngForm" ngControl="name" required type="text">
