### ISSUE TITLE
New Router Error: Uncaught (in promise): Cannot find default outlet

### ISSUE THREAD

**Issue by cquillen2003** [angular/angular#8539]
I am getting the following error when nesting a few routes using the new router.

Error: Uncaught (in promise): Cannot find default outlet

The route tree is based on the following url: "/nav/contacts/list" and has 4 components: root, navbar, contacts, and list.  The contacts component has an inline template ("`<router-outlet></router-outlet>`") that is not being found by the router, but I can see the router-outlet in the DOM.

**Comment by ericmartinezr** [comment]
If the route tree starts with `navbar` you MUST put a router-outlet in it. Besides that a repro is always useful.

**Comment by cquillen2003** [comment]
Each of the first three components has a "`<router-outlet></router-outlet>`" and navigating to "/nav/contacts" works fine.  The navbar appears and has a "`<router-outlet></router-outlet>`" below it as expected.

It's the "/nav/contacts/list" url that fails with the above error.

I apologize for the lack of repo or plunkr.  I couldn't find 2.0.0-rc.1 in plunkr.

**Comment by ericmartinezr** [comment]
Here's the official plnkr http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=preview (for future reference go to plnkr.com -> New -> AngularJS -> Angular 2.0.x (TS) )

**Comment by cquillen2003** [comment]
I could not reproduce the error in plunker and I found my issue.  I was including ROUTER_PROVIDERS in the root component and the contacts component.  Removing them from the contacts component fixed the issue.

**Comment by ammar91** [comment]
I am having a similar issue, I can try to repro on plnkr but when I open and run this 
[http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=preview
](url)

Below error occured

![plnkr](https://cloud.githubusercontent.com/assets/7683970/15182045/f1e3774c-17a3-11e6-96ee-2857710fbcec.PNG)

**Comment by zoechi** [comment]
@ammar91 this is not related to Angular at all. You need to configure your server properly http://stackoverflow.com/questions/10143093/origin-is-not-allowed-by-access-control-allow-origin

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by ammar91** [comment]
I am sorry but I meant, I am trying to repro this issue on plnkr but not able to run this (plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=preview) as provided above by @ericmartinezr

Can you please let me know how to setup plnkr with angular 2 rc? I am getting error in console when try to run.

**Comment by ericmartinezr** [comment]
@ammar91 I opened the plnkr and I don't get the error in your screenshot. Go to plnkr.co -> Launch Editor -> New -> AngularJS -> Angular 2.0.x (TS) and that will create a plnkr with RC.x template

**Comment by ammar91** [comment]
Just repeat the same steps but unfortunately get the same 

> 
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://run.plnkr.co' is therefore not allowed access. The response had HTTP status code 403.

**Comment by ammar91** [comment]
Added CORS extension in chrome browser, but there is still an error that says

> GET https://npmcdn.com/@angular/platform-browser-dynamic/platform-browser-dynamic.umd.js 403

> Error: XHR error (403) loading https://npmcdn.com/@angular/platform-browser-dynamic/platform-browser-dynamic.umd.js(…)

> GET https://npmcdn.com/@angular/core/core.umd.js 403

**Comment by ericmartinezr** [comment]
@ammar91 try clearing and disabling your browser's cache, I don't see any of those errors when I follow the steps I mentioned, so I don't think it is really a npmcdn issue.

**Comment by mhoyer** [comment]
We had this issue randomly too (with RC1) and found the reason on our side. We had a ```ngIf``` binding on our root router outlet to hide/show main content depending on login state of the user:

```
<main>
  <router-outlet *ngIf="isUserLoggedIn"></router-outlet>
</main>
```

Thus, depending on the evaluation performance of the binding the ```<router-outlet>``` element existed or not. Which in turn raised this exception in particular. Especially on IE 11 it was more often seen (if not always).

**Comment by ammar91** [comment]
Yes, I was having a same issue when using `ngIf ` binding on `router outlet`.

**Comment by maxailloud** [comment]
I have the same error, as soon as the router-outlet doesn't exist in the DOM this error is raised.

**Comment by mattxo** [comment]
Having the same error during unit tests.

**Comment by mattxo** [comment]
For me, removing this
   
```
provide(Router, 
{
    useFactory: (resolver, urlParser, outletMap, location) => new Router(
        "RootComponent", App, resolver, urlParser, outletMap, location),
        deps: [ComponentResolver, RouterUrlSerializer, RouterOutletMap, Location]        
)    
    
```

And mocking the router fixed the problem

**Comment by tobias74** [comment]
in my case I was missing the ROUTER_DIRECTIVES on the component that was hosting the subcomponent:
---
	directives: [ROUTER_DIRECTIVES],
---

**Comment by Larisho** [comment]
@mhoyer What did you do to solve the problem? I've encountered the same situation

**Comment by frederikaalund** [comment]
@Larisho in 3.0.0-alpha.6 you can do:

	<div *ngIf="isConnectionOpen">
		<router-outlet></router-outlet>
	</div>

Note that the very same code did not work in 3.0.0-alpha.3.

**Comment by zoechi** [comment]
@frederikaalund I would not expect this to work. If a component has routes, it needs a `<router-outlet>`. You can't just remove it, and that's what `ngIf` does.

**Comment by frederikaalund** [comment]
@zoechi You're right. I concluded too hastily. It *did* work since `isConnectionOpen` was true while I tested it... My mistake! Using `[hidden]` is indeed a better way to do things. Cheers!

**Comment by Larisho** [comment]
@zoechi Thank you for the answer. The problem with using [hidden] is that you can just open chrome dev tools or an equivalent to that and see the hidden content. The reason I was using *ngIf is because you can't do that. 
Is there any way to catch that exception?

**Comment by zoechi** [comment]
@Larisho What's the problem with devtools? Not being able to see it in devtools doesn't make it more secure. You can also just navigate to a different route if the user is not authorized or if you use the new new new router you can use guards to prevent navigating to routes on conditions.

**Comment by Larisho** [comment]
@zoechi Is there any documentation on guards yet?

**Comment by zoechi** [comment]
@frederikaalund a similar issue was opened with #9500

**Comment by tschuege** [comment]
@mattxo I'm facing the same issue as you did with the outlet while testing. But I'm not sure how to mock the router. Could you please send me an example? thanks!

**Comment by ramonhc** [comment]
http://stackoverflow.com/questions/38270702/error-uncaught-in-promise-error-cannot-match-any-routes-rc4-child-routes

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20781399/70672956-b7bd-11e6-8613-021762c22e31.png)
