### ISSUE TITLE
Feature: Make asterisk syntax sugar more logical for structural directives

### ISSUE THREAD

**Issue by mavericken** [angular/angular#8540]
Basically, I feel that the asterisk syntax sugar implementation is the logical inverse of ideal syntax.

I was reading about it here: https://angular.io/docs/ts/latest/guide/structural-directives.html
I stumbled upon this bit right here:

```
<!-- Examples (A) and (B) are the same -->

<!-- (A) *ngFor div -->
<div *ngFor="let hero of heroes">{{ hero }}</div>

<!-- (B) ngFor with template -->
<template ngFor let-hero [ngForOf]="heroes">
  <div>{{ hero }}</div>
</template>
```

Example (A) is supposed to be more convenient than Example (B)...  and it is.
However, why not make the more convenient version even more convenient, and reverse the asterisk usage?

My reverso world example:
```
<!-- Examples (A) and (B) are the same -->

<!-- (A) ngFor div -->
<div ngFor="let hero of heroes">{{ hero }}</div>

<!-- (B) *ngFor with template -->
<template *ngFor let-hero [ngForOf]="heroes">
  <div>{{ hero }}</div>
</template>
```
You kinda have to look carefully to notice the difference.  I took the asterisk from (A) and put it on (B).

Let fancy things be fancy, and let simple things be simple.

**Comment by CaptainCodeman** [comment]
I can't say I _fully_ understand what the asterisk adds in either case (more than the ngFor / ngIf part) but I doubt very much that it is likely to be switched at this stage.

**Comment by frederikschubert** [comment]
Also your change would bind the string to the ngFor input of the ngFor directive. So ngFor would not have the heroes list and could not do anything useful with it.

**Comment by ericmartinezr** [comment]
Also `*` is a special syntax, it converts

```
<div *ngFor="...">
```
to
```
<template ngFor ...>
  </div></div>
</template>
```
Making the change you suggested would affect every single directive in existence, even the custom ones writen by ourselves.

**Comment by mavericken** [comment]
Well, I can see your points.  My proposed change would require either breaking consistency or breaking everything else.  Breaking everything else wouldn't be any fun, and violating the consistency of the syntax at the framework level would be unacceptable also.  So I will close it.

**Comment by mavericken** [comment]
I did have some more thoughts on the subject though, so I will document them here.  A third party add on library could cash in on that consistency provided by the framework and do some nice things by simply transforming from a more convenient syntax to the Angular2 standard syntax, either by a function call or under the covers.  I was toying with some ideas.

```
<div ngFor="let hero of heroes">{{ hero }}</div>
 =>
<div each="heroes">{{ this }}</div>
or
<div for="hero of heroes">{{ hero }}</div>
```

```
<input type="text" [(ngModel)]="name">
 =>
<input type="text" bind="name">
```

And while were at it, why not pipes to simplify input and output designation:
```
(directive)="item"    =>  |directive="item"
[directive]="item"    =>  directive|="item"
[(directive)]="item"  =>  |directive|="item"
```

**Comment by zoechi** [comment]
Seems to be related to some former knowledge. I can't see any more logic in your syntax than the current Angular syntax. The template syntax was extensively discussed about a year ago and examples similar to yours were mentioned but not used in the end.
