### ISSUE TITLE
over 290 xhr requests to bootstrap hello world app (many duplicated)

### ISSUE THREAD

**Issue by sgbeal** [angular/angular#8542]
**Steps to reproduce and a minimal demo of the problem**

create a new A2RC1 app with angular-cli:

    ng new blah
    cd blah
    npm start

load the page with your dev tools open and observe that it submits over 290 xhr requests at startup. beta-14 (from which we just upgraded) loads about 40.

**Current behavior**

more than 290 requests. (>600 once our 20-30 client-side classes are added)

Many of these requests are duplicated, e.g. exception_handler.js, base_wrapped_exception.js, and collection.js.

**Expected/desired behavior**

_Far_ fewer requests.

**Other information**

This many requests is going to KILL us at roll-out time.

**Comment by neilhem** [comment]
Issue related to angular-cli https://github.com/angular/angular-cli/issues/636

**Comment by damiandennis** [comment]
Yeah I also noticed the increase in requests, which is a pain during development.. however going production you should probably bundle it up which will decrease the amount of requests.

**Comment by neilhem** [comment]
Yeah, bundling using `ng build -prod` helps a lot

**Comment by sgbeal** [comment]
ng build -prod and ng server -prod no longer work for us - some file is missing. It works in a clean (ng new) environment, so the different is apparently in our tree, but we currently have no idea what:

    $ ng server -prod
    Livereload server on http://localhost:49152
    Serving on http://localhost:4200/
    The Broccoli Plugin: [BundlePlugin] failed with:
    Error on fetch for main at file:///D:/elided/nms-gui/tmp/bundle_plugin-input_base_path-Ti1N9MAJ.tmp/0/main
            Error: ENOENT: no such file or directory, open 'D:\src\maros\nms-facade\nms-gui-parent\nms-gui\tmp\bundle_plugin-input_base_path-Ti1N9MAJ.tmp\0\main'
        at Error (native)

any hints here would be appreciated :)

**Comment by neilhem** [comment]
Update both local & global angular-cli versions. If you are on windows, run ng commands with sudo. Because of project structure changed a lot, try to create a brand new project & update config files in your older project.

**Comment by sgbeal** [comment]
we've done all that :(. We updated our tree by creating a new ng project, copying all our sources over, adjusting them for the new imports, and then copying everything back once everything worked (which took 3 hours!). We're unfortunately on Windows, but we run our consoles in admin mode because npm doesn't work properly without it.

i'll keep poking around. It works in a clean-slate project, so it's apparently a conflict on our side (but non-prod works fine, which makes me assume that the breakage is somewhere else).

**Comment by sgbeal** [comment]
Aha, but 0.0.39 was the end of last week, practically ages ago. After changing to 1.0.0-beta.0 ...

nope. Same problem :/.

    Error: ENOENT: no such file or directory, open 'D:\...\nms-gui\tmp\bundle_plugin-input_base_path-dmWsjMfF.tmp\0\main'

**Comment by hesing** [comment]
angular 2 quick start very very slow, it kills development, ~303 http request, ~ 8 sec 

![very-slow](https://cloud.githubusercontent.com/assets/13429969/15122539/4199e856-163d-11e6-9c68-0516cbfd8fe3.png)

**Comment by sgbeal** [comment]
fyi: (ng build/server -prod) does not reduce this as all. Our small app, with roughly 40 classes in our tree, serves 630+ requests to load because someone (in a dependency we indirectly rely on) packed hundreds of individual functions each in their own file.

**Comment by DarthDerrr** [comment]
This issue is not helping any pro-angular arguments at my company.

**Comment by ericmartinezr** [comment]
You guys have to bundle your apps yourselves. You shouldn't have used the bundles distributed in previous versions nor expect them to be distributed again.

**Comment by sgbeal** [comment]
@ericmartinezr that's not a useful argument. 99+% of angular users follow the docs from the angular team, which say, "do this and this and it works," and then it works. And suddenly, after an update, it increased the number of requests by 15x, and starts duplicating requests. This is all going on under the hood - the users are not loading this stuff. It's being loaded by deps of deps of deps of deps. We most certainly did not "use the bundles distributed with previous versions" on purpose - they are part of the infrastructure, not part of our apps.

**Comment by ericmartinezr** [comment]
>99+% of angular users follow the docs from the angular team, which say, "do this and this and it works," and then it works


Agree, and that config is for plnkrs mostly, you should bundle your app yourself, again. And it's not really my argument, see https://github.com/angular/angular/issues/8412#issuecomment-216469197

**Comment by sgbeal** [comment]
FWIW, there's no mention of anything being "mostly for plnkers" in the docs, nor any mention of having to build bundles on one's own (nor any mention of how to do it). They say, paraphrased, "do this, and there's your app. See how easy that is?"

When we spent a week evaluating/testing A2 it did not have this deficiency, and then *blam*, it suddenly it does, and the onus is on each and every client app to find its own solution?

_What a huge kick in the balls._

(long rant snipped)

Well, i now know what i'll end up having to do next week, after we explain to the customer during Friday's end-of-sprint demo that "no, it _won't_ perform 637 [at last count] XHR requests at startup when we deliver it [in 5 weeks]"...

**Comment by yfain** [comment]
In my case a tiny app (I'm not using CLI) makes 350 requests and it takes 4 sec just to see the app.  The Angular should have remained in beta for a while after introducing so many breaking changes.

**Comment by rhaynie8028** [comment]
What about the situation where we do not have all the code that will be deployed in our web app? I my case we offer clients an sdk that allows custom functionality to be added to what is basically a giant CMS type banking application (potentially long after we have shipped), so we relied on the bundles to create a complete angular2 environment. This is a brownfield app and there is no option to add "the new fancy and shiny" build approach that has suddenly be thrust on us with the RC and using the angular CLI is not an option either. 

We simply want Angular2 to be "the platform" on the page no matter what is placed on it without the need for excessive requests or a custom bundling solution.

**Comment by nosaku** [comment]
Same problem for me. Till beta 17 it was good and I upgraded to RC and the app sends so many requests. It is really killing the development time.

**Comment by nosaku** [comment]
Is there any workaround for this issue as of now?

**Comment by adamwuyu** [comment]
@nosaku please check this: https://github.com/angular/angular/issues/8591#issuecomment-218932496
and this: https://github.com/angular/quickstart/issues/96#issuecomment-218701180

**Comment by pkozlowski-opensource** [comment]
yep, a proper solution is contained in the linked issues. thnx @adamwuyu

**Comment by sgbeal** [comment]
i beg to differ. Those tickets vaguely describe several script-kiddie half-solutions which do not work out of the box like A2 did before this breaking change. All require significant effort on the client's side to both understand them and get them working (i spent 2 hours this morning trying unsuccessfully to do both).

This is a major kick in the balls to your users.

**Comment by nosaku** [comment]
@sgbeal I completely agree with you. I have wasted many hours on these scripts without much luck.

**Comment by peter-bozovic** [comment]
I also agree the new "build" solution is not helping during the development phase as described in #8456 

But issues stay closed :(

**Comment by radusuciu** [comment]
Agreed completely with @sgbeal. The quickstart shouldn't be "mostly for plnkr", it's what everyone starting out with angular2 will be using to structure their app, and currently every single developer will be running into this. Does the "5 minute quickstart" refer to the time your hello world takes to load?

**Comment by chrislambe** [comment]
Is there another issue tracking this problem? I hope this isn't closed as a `wontfix`; this makes angular-cli pretty much useless to me and my team.

**Comment by nosaku** [comment]
I have created my own bundle of Angular2 and required files for doing the plunkr type transpiling in browser. The number of requests are very few (4 to 5). Here is the github project. Also if you don't want to build it, just download the "release" and see the example folder and the "dist" folder in it.

[ng2-bundle](https://github.com/nosaku/ng2-bundle)
[ng2-bundle-release](https://github.com/nosaku/ng2-bundle/files/288094/ng2-bundle-v1.0.zip)
