### ISSUE TITLE
rc.1 backgroundImage style binding no longer works

### ISSUE THREAD

**Issue by pe8ter** [angular/angular#8543]
The style binding `[style.backgroundImage]="url_to_image"` no longer works in Angular 2.0.0-rc.1.

**Steps to reproduce and a minimal demo of the problem**

_Use http://plnkr.co/edit/fXofYLByhAHKF3mL18KK_ to see the usage of this binding in  _src/app.ts_.

**Current behavior**

No image appears.

**Expected/desired behavior**

A small image should appear.

**Comment by damiandennis** [comment]
Seems to happen on all style.anything sets to string unsafe.

**Comment by pe8ter** [comment]
What is "string unsafe"?

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/issues/8491

**Comment by pe8ter** [comment]
Thanks @ericmartinezr.
