### ISSUE TITLE
RC1 TestComponentBuilder TypeError: params.map is not a function

### ISSUE THREAD

**Issue by pgarge** [angular/angular#8547]
I am getting this error, when i have two or more tests running:
TypeError: params.map is not a function
    at CompileMetadataResolver.getDependenciesMetadata (https://localhost/CE.InsightsWeb/node_modules/@angular/compiler/src/metadata_resolver.js:181:23)
    at CompileMetadataResolver.getTypeMetadata (https://localhost/CE.InsightsWeb/node_modules/@angular/compiler/src/metadata_resolver.js:128:26)
    at CompileMetadataResolver.getDirectiveMetadata (https://localhost/CE.InsightsWeb/node_modules/@angular/compiler/src/metadata_resolver.js:92:28)
    at RuntimeCompiler.resolveComponent (https://localhost/CE.InsightsWeb/node_modules/@angular/compiler/src/runtime_compiler.js:34:47)
    at initComponent (https://localhost/CE.InsightsWeb/node_modules/@angular/compiler/testing/test_component_builder.js:307:73)
    at e.invoke (https://localhost/CE.InsightsWeb/node_modules/zone.js/dist/zone.min.js:1:7215)
    at Object.NgZoneImpl.inner.inner.fork.onInvoke (https://localhost/CE.InsightsWeb/node_modules/@angular/core/src/zone/ng_zone_impl.js:45:41)
    at e.invoke (https://localhost/CE.InsightsWeb/node_modules/zone.js/dist/zone.min.js:1:7166)
    at e.run (https://localhost/CE.InsightsWeb/node_modules/zone.js/dist/zone.min.js:1:4602)
    at NgZoneImpl.runInner (https://localhost/CE.InsightsWeb/node_modules/@angular/core/src/zone/ng_zone_impl.js:76:71)

Code below:
import "rxjs/add/operator/map"
import {describe, expect, beforeEach, it, inject, async, beforeEachProviders, setBaseTestProviders} from "@angular/core/testing";
//import {Observable} from "rxjs/Observable";
import {TestComponentBuilder} from "@angular/compiler/testing";
import {Component, provide, Injector, ElementRef} from "@angular/core";
import {BaseRequestOptions, Http, HTTP_PROVIDERS, XHRBackend, Response, ResponseOptions} from "@angular/http";
import {TEST_BROWSER_DYNAMIC_PLATFORM_PROVIDERS, TEST_BROWSER_DYNAMIC_APPLICATION_PROVIDERS} from '@angular/platform-browser-dynamic/testing';

describe('DOM Template', () => {
    setBaseTestProviders(TEST_BROWSER_DYNAMIC_PLATFORM_PROVIDERS, TEST_BROWSER_DYNAMIC_APPLICATION_PROVIDERS)
    beforeEachProviders(() => [
        HTTP_PROVIDERS,
        TestComponentBuilder
        
    ]);
    beforeEach(() => [
        ElementRef
    ]);
    beforeEach(inject([TestComponentBuilder], (tcb) => {
        return tcb
            .overrideProviders(LongProfile, [provide(AppService, { useClass: MockAppService })],
            [provide(ProfileService, { useClass: MockProfService })])
            .createAsync(LongProfile).then((fixture) => {
                this.fixture = fixture;
            });
    }));

    it('should get full list of tabs', () => {

        this.fixture.debugElement.componentInstance.enableLoader = false;
        var json =":;
        this.fixture.debugElement.componentInstance.result = json
        this.fixture.debugElement.componentInstance.sectionCount = 2;
        var jsonSec = "";
        this.fixture.debugElement.componentInstance.sections = jsonSec.Sections;

        this.fixture.detectChanges();
        let lis = this.fixture.nativeElement.querySelectorAll('li');
        expect(lis.length).toBe(9);

    });

    it('should get sections for tab', () => {
        this.fixture.debugElement.componentInstance.enableLoader = false;
        var json = "";
        this.fixture.debugElement.componentInstance.result = json
        this.fixture.debugElement.componentInstance.sectionCount = 2;
        var jsonSec ="";
        this.fixture.debugElement.componentInstance.sections = jsonSec.Sections;

        this.fixture.detectChanges();
        let sec = this.fixture.nativeElement.querySelectorAll('#iws_lp_sections > li')
        expect(sec.length).toBe(1);
    });
});

If I comment the second test it works fine

**Comment by pe8ter** [comment]
Did you see this thread?

https://github.com/angular/angular/issues/8495

The claim is that older versions of the TypeScript compiler have trouble with the `map` function. Worth a shot.

**Comment by IgorMinar** [comment]
This issue is now obsolete. TestComponentBuilder has been replaced with TestBed. If you still face a similar issue with TestBed, please file a new issue and describe the steps to reproduce the problem. Thank you!

**Comment by srix55** [comment]
Writing this for the benefit of ppl coming across this weird error. This is very very hard to debug as the compiler doesn't give anything other than that one line 'params.map is not a function'. After wasting 2 days on this, I pinpointed the error to missing square brackets.

```
@NgModule({
  declarations: [ AppComponent ],
  imports: [ BrowserModule, FormsModule, HttpModule ],
  providers: [ 
CookieService,
  // The square brackets on HttpClient were missing
  {provide: HttpService, useClass: HttpService, deps: [HttpClient]}
],
  bootstrap: [ AppComponent ]
})
export class AppModule { }
```
