### ISSUE TITLE
Feature: Use text value of select options if value prop is not added

### ISSUE THREAD

**Issue by Matthias247** [angular/angular#8549]
The two-way data binding was already broken before in Firefox in the sense that user input did not modify the model (#8215). This was fixed.

However in the recent version there is now the problem that the initial model value (which is assigned to a `Control` in its constructor) is not applied to the view and instead the view initially displays the first possible select option. The bug occurs in Firefox as well as Chrome. Maybe the fix for #8215 introduced this new other bug.

Reproducer: http://plnkr.co/edit/EGBoO2xRDJXByZykgiHF?p=info
You can see that `bCtrl` initially displays the value AA although CC is stored in the model.

**Comment by zoechi** [comment]
It's working when you add `[value]="opt"`
http://plnkr.co/edit/G0duBjbX4lFoXVPfcX6C?p=preview
No idea if it should work without as well.

**Comment by Matthias247** [comment]
Ah, that absolutely makes sense, as the value is not necessarily the same as the possibly localized text content. I will check tomorrow if I missed that part also in my actual application and close the issue if thats the case.

**Comment by Matthias247** [comment]
Ok, works properly now. However now I'm wondering why the binding in the other direction (from view to model) has worked at all with no value and only an innerText assignment.

**Comment by zoechi** [comment]
It might still be a bug. I also think it should work when then `value` is omitted and the content of the `<option>...</option>` is set to the options value (and the value is of type string)

**Comment by Matthias247** [comment]
@zoechi Do you think I should reopen the issue or can you address the question directly to someone who should know the correct behavior?

**Comment by zoechi** [comment]
Just reopen it and wait for an official response.

**Comment by binarious** [comment]
Just had the same problem after upgrading to RC1, but in my case the value doesn't come from the control constructor. Instead the select box is not displaying the value of `[(ngModel)]` when received via http. The hack of setting a `value` attribute is working, too.

**Comment by prabhu43** [comment]
I tried select with 2-way binding using ngModel. The first option is shown in select box by default in firefox and IE11, even though the select value is empty. It is working as expected in chrome, the select box is empty by default.

**Comment by wesleycho** [comment]
My guess is that `[value]="..."` should be set - this is very similar to a prior issue where input events were unexpectedly happening on different inputs than expected when using ngFor. This is due to how change detection works I believe, so given that the other issue was closed, I would expect this to be rejected as a user error as well.

**Comment by kara** [comment]
It's designed to work with the `value` as an input property, so including it is currently required. It's probably going to stay this way for a while in terms of priority because of how the benefit weighs against the actual work (tricky). I'll keep it open for now.

**Comment by wardbell** [comment]
Please **do** keep open as it is not obvious that one must bind to the option `value` property when the `value` and the displayed text are the same.

The spec is pretty clear that the value should be the text when not specified explicitly.

Here is how [doc'd in MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option)
