### ISSUE TITLE
AJ2 HashLocationStrategy in CleanURL Sites

### ISSUE THREAD

**Issue by DirkPersky** [angular/angular#8551]
Hello,

i got a litle problem and dont find a solution myslef.

**The Problem:**
i have a WebSeite with diefferend subpages like:
- example.com/
- example.com/products
- example.com/contact
- example/....

on the "products"  page i have to add my Logic.
Every time the route change the path in example.com/#/xyz
but he have to do it in example.com/products/#/xyz.

I tryed it with the AJ2 BaseURL but it dont work:

`import {provide, Component,
        enableProdMode}         from 'angular2/core';
import {ROUTER_PROVIDERS,
        ROUTER_DIRECTIVES,
        LocationStrategy,
        HashLocationStrategy,
        RouteConfig, Route, APP_BASE_HREF}     from 'angular2/router';
import {bootstrap}              from 'angular2/platform/browser';
import {ConfigService}          from './services/configService';
import {Standort}               from './comps/standort';
import {Search, ResultList}     from './comps/search';
import {HTTP_PROVIDERS}         from 'angular2/http';

enableProdMode();

var config = new ConfigService();
@Component({
  selector: 'location',
  templateUrl: `${config.default.template_base}/location.html`,
  providers: [ConfigService],
  directives: [Standort, Search]
})

@RouteConfig([
  new Route({
    path: '/location/:location/:country/:lat/:lng/:filter',
    name: 'ResultList',
    component: ResultList
  })
])
class LocationMain {
  config:ConfigService = new ConfigService();
  constructor() {

  }
}

bootstrap(LocationMain, [
  HTTP_PROVIDERS,
  ROUTER_PROVIDERS,
  // provide(APP_BASE_HREF, {useValue: config.default.SystemBaseURL}),
  provide(LocationStrategy, {useClass: HashLocationStrategy}),
]);
`
my route is changed by:
`// Change Route to Result List
          self._router.navigate( ['ResultList', {
            location: self.form.value.adresse,
            country: country,
            lat: latLng.lat(),
            lng: latLng.lng(),
            filter: filter.join('+') || 0
          }] );`

the `<base href="/" />` shows to **example.com/** for the JavaScripts and CSS.

Can you say me where my mistake is?

Greetings
Dirk

**Comment by IgorMinar** [comment]
I'm sorry but I don't understand what the problem is here.

If the problem still exists please open a new issue and provide a plunker reproducing the problem. You can use this template: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue
