### ISSUE TITLE
require node_modules

### ISSUE THREAD

**Issue by kazemihabib** [angular/angular#8553]
when I want to use node_modules in angular2 if that module has 'require' in it,systemjs tries to find it in 'dist' folder how can I solve this?how can i configure it?

**Comment by pkozlowski-opensource** [comment]
See https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by MichaelNTU** [comment]
I have problem when trying to built my project in angular console, the error message "node_module not found". I have included numbers of packets to solved this problem but could not.
