### ISSUE TITLE
angular2-beta-17 Accessing not mapped route with dot in the url

### ISSUE THREAD

**Issue by NaughtyExperience** [angular/angular#8554]
When i navigate to url that contain a dot like: /track.t my application returns html with message:
Cannot GET /track.t
[Screenshot](http://img.prntscr.com/img?url=http://i.imgur.com/0lPgNXB.png)

Im using angular2-beta-17

Central component which handles routes:

```
@Component({
    selector: 'sampleSelector',
    template: `<router-outlet></router-outlet>`,
    directives: [ROUTER_DIRECTIVES],
    providers: [ROUTER_PROVIDERS]
})
@RouteConfig([
    {path: '/...', name: 'Dashboard', component: DashboardCenterComponent, useAsDefault: true}

])
export class AppComponent {
     constructor(router:Router, location:Location) {
            router.recognize(location.path())
                .then((instruction) => {
                    if (!instruction) {
                        // this code will execute if there no route exists for the current url
                        router.navigate(['Dashboard']);
                    }
                });
    }
    } 
```

**Comment by ericmartinezr** [comment]
@NaughtyExperience you'll have to test the same behaviour using RC.x and the new new router. You're using the deprecated router plus a beta that was changed a *little bit*

**Comment by sandekuk** [comment]
@NaughtyExperience: I am facing the same issue with Angular2-rc4. 
Routes are working fine when I use them with the normal flow. Instead if I want to bookmark an url with "." in the url then I am not able to launch the bookmarked url. I get "Cannot Get url" error on the browser

**Comment by vicb** [comment]
>I get "Cannot Get url" error on the browser

This is most probably due to your server config. If you believe there is a real issue in Angular, please provide a repro case. Thanks.

Closing as outdated.

**Comment by sanjay-patel** [comment]
I am also facing the same issue. 
I am using following URL

http://localhost:8080/activation/abc.xyz@gmail.com

Getting following in browser
Cannot GET /activation/abc.xyz@gmail.com

**Comment by 0xTryCatch** [comment]
Same here, Angular 2.4.8. Nothing fancy, just a basic app:

`17.02.28 21:20:41 404 GET /main/value1.value2`

There is definitely an bug with the dots.
