### ISSUE TITLE
Benchpress: "TypeError: capsObject.serialize is not a function" error when running with Protractor version 3 or higher

### ISSUE THREAD

**Issue by thompsnm** [angular/angular#8559]
**Steps to reproduce and a minimal demo of the problem**

- Clone [this repo](https://github.com/thompsnm/benchpress-protractor-version-bug)
- Run `npm install`
- Run `npm test`

**Current behavior**

The test fails with the following output:

    > benchpress-protractor-version-bug@0.0.1 test /Users/nathan.thompson/Projects/personal/benchpress-protractor-version-bug
    > webdriver-manager update; protractor performance/support/protractor.conf.js

    selenium standalone is up to date.
    chromedriver is up to date.
    [18:08:24] I/local - Starting selenium standalone server...
    [18:08:24] I/launcher - Running 1 instances of WebDriver
    [18:08:25] I/local - Selenium standalone server started at http://192.168.1.229:56785/wd/hub
    Started

    /Users/nathan.thompson/Projects/personal/benchpress-protractor-version-bug/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1329
          return callbackFn(this.value_);
                 ^
    TypeError: capsObject.serialize is not a function
        at /Users/nathan.thompson/Projects/personal/benchpress-protractor-version-bug/node_modules/benchpress/index.js:6086:115
        at Promise.invokeCallback_ (/Users/nathan.thompson/Projects/personal/benchpress-protractor-version-bug/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1329:14)
        at TaskQueue.execute_ (/Users/nathan.thompson/Projects/personal/benchpress-protractor-version-bug/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2790:14)
        at TaskQueue.executeNext_ (/Users/nathan.thompson/Projects/personal/benchpress-protractor-version-bug/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2773:21)
        at /Users/nathan.thompson/Projects/personal/benchpress-protractor-version-bug/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2652:27
        at /Users/nathan.thompson/Projects/personal/benchpress-protractor-version-bug/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
        at runMicrotasksCallback (node.js:326:7)
        at doNTCallback0 (node.js:419:9)
        at process._tickCallback (node.js:348:13)

**Expected/desired behavior**

No exceptions should be thrown, and output like this should appear:

    > benchpress-video-loader@0.0.1 test /Users/nathan.thompson/Projects/personal/benchpress-video-loader
    > webdriver-manager update; protractor performance/support/protractor.conf.js

    selenium standalone is up to date.
    chromedriver is up to date.
    Starting selenium standalone server...
    [launcher] Running 1 instances of WebDriver
    Selenium standalone server started at http://192.168.1.229:64396/wd/hub
    .

    Finished in 0.026 seconds
    1 test, 0 assertions, 0 failures

    BENCHMARK Initial video load
    Description:
    - forceGc: false
    - sampleSize: 5
    - userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36
    Metrics:
    - gcAmount: gc amount in kbytes
    - gcTime: gc time in ms
    - majorGcTime: time of major gcs in ms
    - pureScriptTime: script execution time in ms, without gc nor render
    - receivedData: encoded bytes received since navigationStart
    - renderTime: render time in ms
    - requestCount: count of requests sent since navigationStart
    - scriptTime: script execution time in ms, including gc and render

              gcAmount |             gcTime |        majorGcTime |     pureScriptTime |       receivedData |         renderTime |       requestCount |         scriptTime
    ------------------ | ------------------ | ------------------ | ------------------ | ------------------ | ------------------ | ------------------ | ------------------
    Shutting down selenium standalone server.
    [launcher] 0 instance(s) of WebDriver still running
    [launcher] chrome #1 passed

**Other information**

- The example repo is set up to use Protractor `v3.2.2`. Downgrading to `v2.5.1` yields the expected behavior.
- I'm running Node `v4.2.2` with npm `v2.14.7`

**Comment by deeeed** [comment]
+1

**Comment by vicb** [comment]
@juliemr could you please take a look ?

**Comment by tbosch** [comment]
This is fixed on master.
