### ISSUE TITLE
The ViewPool should be configurable

### ISSUE THREAD

**Issue by jbdeboer** [angular/angular#856]
We view the ViewPool as one of the riskiest features in Angular2. Before we take the plunge and enable the ViewPool for our application we need extensive testing.

Therefore, we would like to
a) disable the ViewPool. Right now, Angular2 hard-codes a 10000 item cache. This number is not configurable.
b) enable it on a per-component basis.  i.e. we intend on testing each component and then promoting it to a "cachable component".

**Comment by mhevery** [comment]
1. Agree that it should be configurable, we will work on it.
2. Can you better explain your concerns of trust? If Angular solely controls the DOM, the app can't break the DOM, and so it should be safe for reuse.

**Comment by jbdeboer** [comment]
This appears to be implemented; 10000 is now configurable.
