### ISSUE TITLE
Feature Request: Allow #referencing any directive (i.e. default exportAs)

### ISSUE THREAD

**Issue by Yona-Appletree** [angular/angular#8561]
**Current behavior**

It appears that only directives which declare an `exportAs` value in their `@Directive` can be assigned to a reference (e.g. `<input ngControl="name" #name="ngForm">`). This is limiting and confusing, as the `exportAs` name is both optional and arbitrary. (See https://github.com/angular/angular/issues/7236 for an example of a desired change in export name). As far as I can tell, it is impossible to get a handle on the public API of a directive which does define an `exportAs`.

My specific case involves wanting to be able to reference a `RouterLink` directive to see if it is active from another element. I cannot find an elegant way to do this.

**Expected/desired behavior**

Create a way to bind any directive to a reference. The simplest method to do this would be to default the `exportAs` name to the directive class name. There could be name conflicts, but that is already possible with `exportAs`. This would allow things like `<a [routerLink]="..." #myLink="RouterLink">` and `<input #ctrl="NgFormControl" />`. Ideally, any ancestor class name in the Directive's hierarchy could be used, allowing for more generic references.

If making such a change is not possible at this stage, at least provide `exportAs` values for all directives included with angular2, or minimally, for those directives which expose a useful API.

**Comment by zoechi** [comment]
You can just use 

```ts
@ViewChildren(RouterLink) routerLinks:QueryList<RouterLink>;
   
ngAfterViewInit() {
  console.log(this.routerLinks);
}
```

[**Plunker example**](https://plnkr.co/edit/cE1y0l8TAD9KkkuO78Zz?p=info)

**Comment by Yona-Appletree** [comment]
Thanks, that's a nice method of getting them into controller, but it would still require a bit of code to pull the RouterLinks out of the array and associate them with other components in the controller. Being able to directly reference in the view seems much more elegant.

For reference, I'm trying to do things like this:

    <li class="menuitem"
        [class.menuitem-is-active]="loginLink?.isRouteActive"
        *ngIf="!loggedIn"
    ><a [routerLink]="['Login']" #loginLink="RouterLink">Login</a></li>

That's a nice and self contained bit of view template that requires no extra logic in the controller. Your method would require involving the controller. Now, I assume it's possible to use `@ViewChildren` in a custom directive, and that may be what I do. However, it still seems fairly trivial and quite useful to be able to refer to and directive directly from the view.

**Comment by choeller** [comment]
@Yona-Appletree I guess the problem here is, that you can add put a component and as many directives as you want onto an element. Having
```html
  <myCrazyComponent [routerLink] #whatAmI></myCrazyComponent>
```
makes it pretty hard to determine what '#whatAmI' is supposed to be. Nevertheless being able to access Directives that have no `exportsAs` property would be quite cool. Maybe it could be referenced by type or something like this:
```html
  <myCrazyComponent [routerLink] #imTheLinkRef="routerLink"></myCrazyComponent>
```

**Comment by pkozlowski-opensource** [comment]
@choeller is right. With Angular you can have several directives and a component on the same element so you need to specify which one to assign.

**Comment by Yona-Appletree** [comment]
@pkozlowski-opensource I'm curious why this was closed. @choeller implied that it would be "quite cool" and proposed an idea. Is there a new slip to track this?

**Comment by pkozlowski-opensource** [comment]
@Yona-Appletree it was closed as there is no concrete proposal. If you've got one that would allow to specify which directive you are referencing I would be more than willing to re-open. BTW, referencing a type won't work since you couldn't minify your code.

**Comment by choeller** [comment]
So maybe it would be possible to just use the selector of the directive as identifier. Without thinking too much about it, this seems quite reasonable to me. exportAs would then just override this behavior. As @mhevery labeled this today as needs design he didn't seem to find the idea totally stupid...

**Comment by Yona-Appletree** [comment]
@pkozlowski-opensource Totally understand, and your point about class name is well taken. I agree with @choeller that using the selector would be easiest and work well in most cases. It would also be clear in most cases that it isn't a standard exportAs because of the selector syntax.

Consider, then, the proposal to be: if exportAs is not specified for a directive, default the value to its selector.

**Comment by pkozlowski-opensource** [comment]
@choeller  @Yona-Appletree guys, I'm totally with you on the fact the currently we need to "repeat the same thing" 3 times for exported directives. Let's consider this example:

```javascript
@Directive({
    selector: '[foo-bar]',
    exportAs: 'fooBar'
})
export class FooBar {
    ...
}
```

So we've got:
* `FooBar` - class name / type
* `[foo-bar]` - selector
* `fooBar` - export name

Now, having those 3 things sucks, we are all in agreement here. Now what we could do about it? Seems like we can't use type information as it would break with minification. Using a selector name to indicate export name is also problematic as:
* it can contain special characters not suitable for a selector name (as in the above example)
* it would assume that we want to systematically export a directive which might not be the case

I'm going to re-open the issue but it won't be "fixed" until someone brings up an idea / design that would satisfy all the constraints. We want to make it better, we can see inefficiencies in the current  model but I can't see any better model atm.

**Comment by Yona-Appletree** [comment]
Fair enough. I understand the issues with using the selector.

I understand the concern about the special characters, but I don't think 
it would be much of a problem. In practice, it would look like this:

<a [routerLink]="whatever" #myLink="[routerLink]" />

For class based selectors, it would look like this:

<a class="fancy-thing other-thing" #myLink=".facny-thing" />

In fact, I think that's very clear and rather intuitive.There are cases 
of more complex selectors that might not be as a clean, but for the 
majority of cases, I personally prefer this to the existing syntax.

One example of such a case is NgForm, whose selector is: 
form:not([ngNoForm]):not([ngFormModel]),ngForm,[ngForm]. Clearly, in 
such a case, a manual exportAs would be preferable.

As for explicitly not exporting a directive, that could be accomplished 
with exportAs: null or similar.

My biggest concern is the discoverability and consistency of exportAs 
names in general, which in many cases would be improved by this, but not 
all. That angular-wide conversation may be out of scope for this thread, 
though.
> Pawel Kozlowski <mailto:notifications@github.com>
> May 13, 2016 at 13:54
>
> @choeller <https://github.com/choeller> @Yona-Appletree 
> <https://github.com/Yona-Appletree> guys, I'm totally with you on the 
> fact the currently we need to "repeat the same thing" 3 times for 
> exported directives. Let's consider this example:
>
> @Directive({
> selector: '[foo-bar]',
> exportAs: 'fooBar'
> })
> export class FooBar {
> ...
> }
>
> So we've got:
>
>   * |FooBar| - class name / type
>   * |[foo-bar]| - selector
>   * |fooBar| - export name
>
> Now, having those 3 things sucks, we are all in agreement here. Now 
> what we could do about it? Seems like we can't use type information as 
> it would break with minification. Using a selector name to indicate 
> export name is also problematic as:
>
>   * it can contain special characters not suitable for a selector name
>     (as in the above example)
>   * it would assume that we want to systematically export a directive
>     which might not be the case
>
> I'm going to re-open the issue but it won't be "fixed" until someone 
> brings up an idea / design that would satisfy all the constraints. We 
> want to make it better, we can see inefficiencies in the current model 
> but I can't see any better model atm.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/angular/angular/issues/8561#issuecomment-219156268>
>

-- 
Yona Appletree
Senior Developer
Concentric Sky, inc
yona@concentricsky.com

**Comment by wizarrc** [comment]
@pkozlowski-opensource Any updates on this? I think it's best to get something in there. Right now I'm not too concerned with all the fancy ways that it could be identified, but to be able to have a single way to identify it without specifying in exportAs, which seems to be a little known property. I think the simplest approach is to automatically add an exportAs default to all non-overridden directives without it defined. i.e. selector `foo-bar` to default exportAs `fooBar`. Anything else is overkill at this point. Having to guess the QueryList index number is too burdensome, difficult, and is non-productive. Can this be added to the compiler to auto-generate all exportAs properties that are null or undefined to be set to a default string based on the mandatory selector property?

**Comment by StevenLiekens** [comment]
Until this feature is implemented, here's a way to keep your code a little dry-er:

```ts
const NAME: string = 'fooBar';

@Directive({
    selector: `[${NAME}]`,
    exportAs: NAME
})
export class FooBar {
    ...
}
```

**Comment by wizarrc** [comment]
@StevenLiekens that works? nice simple hack!
