### ISSUE TITLE
New Router : export RouterLink and RouterOutlet

### ISSUE THREAD

**Issue by ericmartinezr** [angular/angular#8562]
**Current behavior**

Currently RouterLink and RouterOutlet are not exposed so we can't import them individually, I could use it to query for RouterLinks on my view, but right now it's not possible.

See https://github.com/angular/angular/blob/master/modules/%40angular/router/index.ts

**Expected/desired behavior**

Be able to do

```
import {RouterLink} from '@angular/router';
import {RouterOutlet} from '@angular/router';
```
Or in one line works too :P
```
import {RouterLink, RouterOutlet} from '@angular/router';
```

**Other information**

cc : anyone who can build latest master

**Comment by ps2goat** [comment]
You should be able to import from '@angular/router/src/directives/router_link' and '@angular/router/src/directives/router_outlet', in the meantime.  I have local copies, but I do the same thing with some of the core/src/facade/ classes (not sure if this would help you if using a cdn).  You'll need to map the paths in system.js

**Comment by ericmartinezr** [comment]
@ps2goat thanks, that's what I'm doing right now, the problem is that we're not supposed to access anything through `src/...`

**Comment by ps2goat** [comment]
@ericmartinezr so should we creating issues for each of these instances?

**Comment by ericmartinezr** [comment]
@ps2goat not sure what you mean. If you mean about the `facade` classes, you shouldn't be using them, that's internal API.

**Comment by ps2goat** [comment]
One in particular was the ValidatorFn interface, required to be returned
when using `Validators.compose`

**Comment by hannahhoward** [comment]
it looks like you can import ROUTER_DIRECTIVES (which is both RouterLink & RouterOutlet) -- is there some reason you would want just RouterLink or RouterOutlet as opposed to both?

**Comment by michalstepien** [comment]
extends RouterOutlet

**Comment by hannahhoward** [comment]
in that case PR submitted. #8912

**Comment by ericmartinezr** [comment]
Anyway, will this still be an issue with the new new new router?
