### ISSUE TITLE
angular 2.0.0-rc.1 is not found on registry.npmjs.org

### ISSUE THREAD

**Issue by advgal** [angular/angular#8564]
```
git clone https://github.com/angular/quickstart quickstart
cd quickstart/
npm install
```

yields error:

```
...
npm http 404 https://registry.npmjs.org/angular/common/2.0.0-rc.1
npm http 404 https://registry.npmjs.org/angular/compiler/2.0.0-rc.1
npm ERR! 404 'angular' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 
...
```

excerpt from package.json:

```
...
  "dependencies": {
    "@angular/common":  "2.0.0-rc.1",
    "@angular/compiler":  "2.0.0-rc.1",
...
```

**Comment by sateffen** [comment]
Which npm version do you use? [Here](https://github.com/mgechev/angular2-seed/blob/master/package.json) the people use the same reference, and I guess this seed is some kind of reference.

Can you install the dependencies of this seed?

**Comment by advgal** [comment]
% npm -v
1.3.6

seems to be too old

**Comment by sateffen** [comment]
That's pretty... Yep, old^^

Usually upgrading nodejs to a version of 4 or newer installs a npm version that'll work as well. From experience I would advice you not to use nodejs 6, because some packages aren't up to date yet, but 4.4 is pretty good. Never encountered something bad.

**Comment by advgal** [comment]
that's what you get on RedHat EL
