### ISSUE TITLE
binding style.background-image does not work in rc.1

### ISSUE THREAD

**Issue by ClementVidal** [angular/angular#8565]
Hi, i get a weird issue when trying to bind something to **[style.background-image]** in rc.1:

When the result of the binding expression evaluate to a simple string like: _'none'_, everything works fine, and the _background-image_ style is correctly set to _'none'_

But if the expression evaluate to something like: _'img(some/path.jpg)'_, the binding does not work and the css property _background-image_ **is not set**.

Checkout this plunker for an exemple:

http://plnkr.co/edit/uOGUsM?p=info

- If the first return of the bg getter is uncommented, the css style is set.
- If the second return of the getter is uncommented, the css style is not set.

This was working perfectly in beta 16.

Did you guys already faced this ?

**Comment by zoechi** [comment]
Dup of #8491

**Comment by zoechi** [comment]
See also #/8522
