### ISSUE TITLE
Include the Safe* interfaces in the exports of @angular/platform-browser

### ISSUE THREAD

**Issue by Tragetaschen** [angular/angular#8568]
After reading #8491, I tried to implement the solution to [mark the generated style string as safe](https://github.com/angular/angular/issues/8491#issuecomment-217467582). 
```ts
this.svgUrl = sanitizer.bypassSecurityTrustStyle('url(\'image.svg\')');
```
However, `bypassSecurityTrustStyle()` returns `SafeStyle` instead of `string` (as the comment suggests) and this marker interface isn't exported by `@angular/platform-browser`. That means, I cannot properly type my class member.

Please export the marker interfaces `SafeStyle`, `SafeHtml`, etc. so this solution works without `any`.

**Comment by pantonis** [comment]
Had the same problem:

temporary workaround I did until it is exported

`this.svgUrl = <string>sanitizer.bypassSecurityTrustStyle('url(\'image.svg\')');`

**Comment by mprobst** [comment]
Mea culpa, oversight on my side. Let me fix that.

**Comment by mprobst** [comment]
@pantonis casting to a string is a bit nasty as the value is not a string. I'd recommend using `any` as the type of the field for the time being.

**Comment by Tragetaschen** [comment]
That's great, thanks!

**Comment by daBishMan** [comment]
I am doing the import in my component, `import { SafeUrl } from '@angular/platform-browser';` but when I build using the CLI I get 'SafeUrl' was not found in '@angular/platform-browser'  

what am I missing ?

**Comment by mprobst** [comment]
@daBishMan that should work, but there's a bunch of things that could be wrong. See [here](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) on how to get support with that.

**Comment by SamVerschueren** [comment]
Not sure if I'm the only one, but using the `angular-cli`, I receive this error message

> WARNING in ./src/app/shared/directives/background.directive.ts
> 53:55 export 'SafeStyle' was not found in '@angular/platform-browser'

It works though so might be an "issue" with Webpack or something. Not sure.

**Comment by emoralesb05** [comment]
Same here, it works fine and all that, but the `CLI` complains that is not part of the module.

**Comment by emoralesb05** [comment]
Huh.. it complains if we add `SafeResourceUrl` or any of those as an input parameter.

`set backgroundUrl(backgroundUrl: SafeResourceUrl) {`

`"export 'SafeResourceUrl' was not found in '@angular/platform-browser'`

**Comment by devoto13** [comment]
Looks like webpack/webpack#2977.
