### ISSUE TITLE
feat(directive): Add stylesheet for attribute directive to enable pseudo selector styling.

### ISSUE THREAD

**Issue by Guardiannw** [angular/angular#8569]
It would be very helpful to have the ability to add inline styles to an element through an attribute directive.

**Use Case: **
I have a HotKey directive that will enable the user to press a keyboard key to navigate to a particular link.  I need all elements with a HotKey directive to have the first letter underlined.  I cannot find an easy way to style the first letter on the element with an underline without using pseudo selectors.  In order to use pseudo selector :first-letter, I have to have stylesheet use.  For encapsulation best practices, I want to be able to style this inline with the directive, and not through a global stylesheet.

**Comment by mhevery** [comment]
Only components have visual representation. Directives only have behavior. Your request would break our separation. Won't implement.
