### ISSUE TITLE
Script Tag for SystemJS Config is linked incorrectly

### ISSUE THREAD

**Issue by DavisSylvester** [angular/angular#8570]
The script tag SystemJS config file for 5 MIN QUICKSTART under Typescript appears to be incorrect.

It reads:

    <script src="systemjs.config.js"></script>

Should it read:

    <script src="system.config.js"></script>

**Comment by kabua** [comment]
Also, the file contents for the 'systemjs.config.js' tab states:
"BAD FILENAME: ../../_fragments/quickstart/ts/systemjs.config.1.js.md   Current path: docs,ts,latest,quickstart PathToDocs: ../../"

It appears that the link is bad. I also noticed else were but at the time, I didn't fully understand what it was it was stating.

**Comment by wardbell** [comment]
No, it is correct as written ... or at least written as intended ... because it is configuration for SystemJS.

Please close.
