### ISSUE TITLE
"repository" metadata missing in package.json RC.0

### ISSUE THREAD

**Issue by joost-de-vries** [angular/angular#8571]
[webjars.org/npm](http://www.webjars.org/npm) makes npm packages available through jar files published through mavencentral.org

This way it is possible to have only one build definition for both server- and browser code. [see here for my seed project](https://github.com/joost-de-vries/play-angular2-typescript)

Since RC.0 this no longer works. At webjars.org/npm I get the following error. 
```Failed!
The source repository for @angular/core 2.0.0-rc.0 could not be determined but is required to published to Maven Central.  This will need to be fixed in the project's package metadata.
```

And indeed I don't see the "repository" field in [core package.json](https://github.com/angular/angular/blob/master/modules/%40angular/core/package.json) like it did in the [overall package.json](https://github.com/angular/angular/blob/master/package.json).

So my request is to add "repository" metadata to the package.json of the new packages. So that it will work with webjars.org

Pls let me know if you'd appreciate a pull request....

**Comment by mhevery** [comment]
We don't support webjars.org, Perhaps talk to whoever published it there?

**Comment by jamesward** [comment]
What is the reason for not having a `repository` specified in the `package.json`?  This is required metadata for deploying to Maven Central.  Thus the reason why it is needed for WebJars.  But this seems like just a good thing to have in there so library consumers know where to get the source.

**Comment by joost-de-vries** [comment]
@mhevery hi I'm really sorry to see that you closed the issue.
I agree with @jamesward that it's not so much about supporting webjars as much as having proper npm metadata.
I'd like to urge you to reconsider. Unchanged this will create a major issue for some projects developing with Angular2. Mine for one.
While it seems to be just some standard npm metadata that's involved.
I'm perfectly willing to do the legwork like providing a pull request with the relevant metadata filled in.

**Comment by mhevery** [comment]
@joost-de-vries please create a PR which updates our `package.json`

**Comment by joost-de-vries** [comment]
@mhevery done.
Thanks!

**Comment by mhevery** [comment]
@joost-de-vries, thank you!

**Comment by nicolashenry** [comment]
@joost-de-vries @mhevery
"repository" metadata is missing again in RC2 in platform-browser-dynamic/package.json

**Comment by joost-de-vries** [comment]
I've opened a new issue for that and submitted a PR see #9388
