### ISSUE TITLE
DI problem when create children with ComponentResolver

### ISSUE THREAD

**Issue by Mc-Mido** [angular/angular#8573]
**Steps to reproduce and a minimal demo of the problem**
Reproduce with this plnkr: http://plnkr.co/edit/xk7UoztmT8Tp5TF0OLUF

**Current behavior**
It seems that the TestService reference can't be injected into IndicatorComponent  (if you remove the reference to TestService from the IndicatorComponent contructor then it works).

There is an error: 
`EXCEPTION: Error: Uncaught (in promise): TypeError: Cannot read property 'query' of null`

**Expected/desired behavior**
Services provided by the parent should be reachable/injected at all its children which need them.

**Comment by ericmartinezr** [comment]
Move `TestService` above everything. By when `IndicatorComponent` tries to inject it in the constructor `TestService` doesn't exist yet, therefore it is undefined/null. I reported this over here https://github.com/angular/angular/issues/8245 it comes from beta 16. I should probably edit the title and make it easier to find.

**Comment by todoubaba** [comment]
```typescript
this._cmpRef = this._child.createComponent(factory, 0, this._child.parentInjector);
```
or
```typescript
var childInjector = ReflectiveInjector.fromResolvedProviders([/** additional */], this._child.parentInjector);
this._cmpRef = this._child.createComponent(factory, 0, childInjector);
```

**Comment by Mc-Mido** [comment]
Thanks a lot **ericmartinezr** & **todoubaba**.

I'll check tomorrow in our full stack app (the service is in a different TS file and the import where it's used is already done at the top otherwise tsc should throw an error). 

I've already tried to use and pass injector but not exactly in the same way and I had an other error (don't remember exactly).

I'll update this issue asap.

**Comment by Mc-Mido** [comment]
I has split components/service as in our full stack app:

**New plnkr:** http://plnkr.co/edit/elro260zGZ7Zyj5dQCo0

I can't reproduce the error in plnkr but we have still the error in our app. It's into **resolveComponent** call, only with a specific service (no problem with logger service injection for example). It worked fine in beta 16. 

Recently we migrate our application to Webpack and rc.1, may be it's a problem with Webpack, may be an import cycle problem?

BTW it's really difficult to investigate issues/errors with this kind of error messages.

**Comment by ericmartinezr** [comment]
@Mc-Mido is there any chance that you can share your project? We could clone it and see it, that would be much better.

**Comment by Mc-Mido** [comment]
Unfortunately I'm not allowed to upstream our project.

I've found a root cause and a workaround for our error. The problem seems to be on Webpack side:
* My injected service uses a A class which itself uses a B class.
* In my service ts file, A is import first then B.
* If a B instance isn't created before the DI trying to inject my service then there is this error
* **workaround**: in the entry point constructor, create an unassigned instance of B.

In the webpack bundle, the only difference between with/without workaround bundle file is around where (and thus when) require for B is defined. It's why I suppose that it's a webpack problem.

As I said in my previous comment, more error information as which import has failed would be a really useful feature :)

Thanks for your help **eric**!

**Comment by tinchou** [comment]
Thanks @Mc-Mido for your description, it really helped me debug! I had that exact issue, I was importing things in the wrong order. SystemJS here, configured through angular-cli.

**Comment by mhevery** [comment]
Sounds like this has been resolved, closing
