### ISSUE TITLE
RC.1: AppViewManager.getViewContainer replacement

### ISSUE THREAD

**Issue by alexi2014** [angular/angular#8574]
What is the replacement for the AppViewManager.getViewContainer method in the new (Beta.16+) API? Changelog states that _"AppViewManager is renamed into ViewUtils and is a mere private utility service"_, but ViewUtils contains only two methods not related to what AppViewManager was comprised of.

**Comment by bennylut** [comment]
does this help?
cited from the changelog: 

> use  @ViewChild(‘myVar’, read: ViewContainerRef) to get hold of a ViewContainerRef at an element with variable myVar

**Comment by alexi2014** [comment]
No, I need to get ViewContainerRef for an **arbitrary** ElementRef, not for a child.

**Comment by ericmartinezr** [comment]
Inject ViewContainerRef in that arbitrary element

**Comment by mhevery** [comment]
Sorry `AppViewManager` is private API.

Please re-open with use case demonstrating what you need to achieve, rather than what API you need.
