### ISSUE TITLE
Can't retrieve ReflectiveInjector

### ISSUE THREAD

**Issue by alexi2014** [angular/angular#8575]
What's the way to obtain a reference to ReflectiveInjector associated with the component?
Changelog for Beta.16 states that _"Injector was renamed into ReflectiveInjector"_. If I add it to the component constructor parameter in the following way:
`@Inject(ReflectiveInjector) @Optional() private reflInj: ReflectiveInjector`
, the `reflInj` parameter receives null.
If I add
`@Inject(Injector) injector: Injector`
, the `injector` parameter gets a reference, but it's not a ReflectiveInjector class instance.

**Comment by zoechi** [comment]
Just inject an `Injector`. Only when you `new` it directly or call static methods (don't know if it actually has one) use `ReflectiveInjector`.
