### ISSUE TITLE
New Router: `changes` event no longer passes in the url

### ISSUE THREAD

**Issue by ps2goat** [angular/angular#8578]
Previous behavior, at least for us on beta.8:

THEN: The router had a `subscribe` event with a 'url' parameter (url: string).  We could use this url however we wanted, and this event would fire before navigation.

NOW: The router has a `changes` event with a `void` parameter.  There's no simple way to get a snapshot of the new url without messing with urlsegments and urlTrees/RouteTrees.  We can get access to these in OnActivate and CanDeactivate, but those methods are only fired when those components are being _routed to_.  For example, my main AppComponent has a router; the router lifecycle events only fire for child components of the router.

Can you bring back the url parameter in the `router.changes` event?

**Comment by zoechi** [comment]
You can just inject `Location` and get the Url from there
