### ISSUE TITLE
New Router: default route support needed

### ISSUE THREAD

**Issue by ps2goat** [angular/angular#8579]
Can you bring back the ability to specify a default route to the @angular/router RC1+ bundle?  This seems like a necessity for most everyone using the router.

Also, the same default parameter that was remove in the new router seems to not work in the beta router in @angular/router-deprecated.  In fact, much of our routing was broken when testing.  (Every page depends upon default routes).  Navigating directly to the defined routes did not work, either; I'm not sure if that's related to similar RC1 router bugs (8409, 8481).

**Comment by dehli** [comment]
According to the documentation [here](https://angular.io/docs/ts/latest/guide/router.html) `useAsDefault` is coming soon.

**Comment by renehamburger** [comment]
@ps2goat, here's a possible temporary workaround:

1) Define catch-all route in app.component.ts:
```ts
import PageNotFoundComponent from './page-not-found.component';
...
@Routes([
  ...
  {path: '/*', component: PageNotFoundComponent},
])
```

2) Redirect to default route in page-not-found.component.ts:
```ts
import {Component} from '@angular/core';
import {Router} from '@angular/router';

@Component({
  selector: 'page-not-found',
  template: 'Page not found',
})
export default class PageNotFoundComponent {
  constructor(private router: Router) {
    this.router.navigate(['/defaultRoute']);
  }
};
```

**Comment by ps2goat** [comment]
@renehamburger - I thought about something like that, but without the ability to bind to a property to tell it the default route, I need at least 3 such components.  One for the main app and one for each of our main child routes.

**Comment by xtiancapil** [comment]
@ps2goat I took @renehamburger code and modified it so I could pass the url I want to redirect to. I'm using navigateByUrl but I imagine you could also use router.navigate(). This again is just a temporary workaround until useDefault is added.

``` javascript
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

export const RedirectComponent: any = (name: string) => {
    @Component({
        selector: 'redirect-route',
        template: `Redirecting to ${name}`
    })
    class RedirectComponent implements OnInit {
        constructor(private router: Router) { 
        }
        
        ngOnInit(): void {
            this.router.navigateByUrl(name);
        }

    }
    return RedirectComponent;
}
```

**Comment by sqlsolver** [comment]
Another temporary workaround is to change the order in which you import components into the app file so that the one whose template you want displayed first by the router is listed before the others. Make sure they're listed in that order inside the array of directives also.

**Comment by vsavkin** [comment]
The current version of the router supports "empty path" routes and "wild card" routes. The first one is used to match any route without consuming any url fragments. And the second one is used to match any route with consuming all fragments. The router also support redirects, which among other things allow you to implement "aliases".

You can read more about it here: https://github.com/angular/angular/blob/master/modules/@angular/router/src/config.ts

'useAsDefault' is not necessary in the current version of the router.
