### ISSUE TITLE
Feature request: take directive super-type into account when querying 

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#8580]
Assuming the following markup:

```HTML
<my-list>
   <my-item>...</my-item>
   <my-fancy-item>...</my-fancy-item>
   <my-super-fancy-item>...</my-super-fancy-item>
   <my-item>...</my-item>
</my-list>
```

where `my-item`, `my-fancy-item` and `my-super-fancy-item` are directives such that:

```javascript
class MyItem {
...
}

class MyFancyItem extends MyItem {
...
}

class MySuperFancyItem extends MyItem {
...
}
```

I would like to query all directives of type `MyItem` like so:

```javascript
@ContentChildren(MyItem) allItems: QueryList<MyItem>;
```

and allItems should contain all instances of `my-item`, `my-fancy-item` and `my-super-fancy-item` (as all of them are passing the `foo instanceOf MyItem` test.

cc.: @mhevery @tbosch

**Comment by mhevery** [comment]
Had a chat with @pkozlowski-opensource and @vsavkin. The take away is that

1. DI should not understand inheritance because to DI the token is opaque, and does not have to be a class ref.
2. The above can be achieved by publishing yourself with a different token.

```
@Component({
  selector: 'my-fancy-item',
  providers: [provide(MyItem, useExisting: MyFancyItem)]
})
class MyFancyItem extends MyItem {}
```

**Comment by mhevery** [comment]
@pkozlowski-opensource please close after you verify that it solves your use case.

**Comment by zoechi** [comment]
The feature request doesn't seem to be about dependency injection. Currently you would need to add a template variable to each element to be able to query them at once like

```
<my-list>
   <my-item #myItem>...</my-item>
   <my-fancy-item #myItem>...</my-fancy-item>
   <my-super-fancy-item #myItem>...</my-super-fancy-item>
   <my-item #myItem>...</my-item>
</my-list>
```
And query like

```
@ContentChildren('myItem') allItems: QueryList<MyItem>;
```

**Comment by vsavkin** [comment]
@zoechi you can query for directives as follows

```
@ContentChildren(MyItem) allItems;
``

But directives are not special, and you can query for any injectable object.

```
@ContentChildren(MyService) servicesInTemplate;
``

So the solution Misko provided should work (except you need to use `useExisting: forwardRef(() => MyFancyItem)`). If it doesn't work, it's a regression, and we'll fix it.

**Comment by zoechi** [comment]
@vsavkin I guess I see it now. Thanks a lot. Quite valuable information!

**Comment by mhevery** [comment]
@pkozlowski-opensource I think this works as intended and should be closed. (Will close if no response.)

**Comment by pkozlowski-opensource** [comment]
@mhevery yeh, this solves use-cases cases I've got right now. Will re-open / open a new issue when another use-case surfaces where we can't play the trick described here.

**Comment by kub1x** [comment]
I got here googling and had quite a hard time realizing the `profide()` function apparently doesn't exist any more. So here is a snippet of what I got working today for future struggelers. Mixing @mhevery's and @vsavkin's answers above with [this blog](https://blog.thoughtram.io/angular/2015/05/18/dependency-injection-in-angular-2.html).

```javascript
@Component({
  selector: 'my-fancy-item',
  providers: [{provide: MyItem, useExisting: forwardRef(() => MyFancyItem)}]
})
class MyFancyItem extends MyItem {}
```

**Comment by egcram** [comment]
The proposed solution works for me perfectly. Unfortunately I get an error in my unit tests during creation of a component which uses the syntax like in the post from kub1x.
 The error is: 

`Error at injectionError(...) at noProviderError(...)`

Does somebody know how to fix this? I tried various things but none of them worked.

**Comment by Toxantron** [comment]
Over two years later and the API in v7 now changed to:

```ts
@Component({
  selector: 'my-fancy-item',
  providers: [{provide: MyItem, useExisting: MyFancyItem }]
})
class MyFancyItem extends MyItem {}
```
Instead of `useExisting` you can also use `useClass` depending on your lifecycle needs as per [this documentation](https://v7.angular.io/guide/dependency-injection-providers).

**Comment by mlc-mlapis** [comment]
@Toxantron … But this was possible even before Angular 7 / 8.
