### ISSUE TITLE
Bootstrapping and dependency injection does not work when importing from a "barrel"

### ISSUE THREAD

**Issue by jussikinnula** [angular/angular#8586]
Bootstrapping `bootstrap(AppComponent)` and dependency injection (injecting a service like `import { FooService } from './index';` and `@Component({ ... providers: [FooService] ... });` don't work when importing the component or service from a barrel (barrel being an `index.ts` containing the `export * from ...` for the components and services in the directory that the `index.ts` is on).

**Steps to reproduce and a minimal demo of the problem**

This plunk can be used to reproduce both of the problems:

http://plnkr.co/edit/3lNjEr?p=preview

- For the bootstrapping problem, uncomment line 3 and comment line 4 from `app/main.ts` (e.g. making the importing of the `AppComponent` come via the "barrel")
- For the dependency injection problem, uncomment line 3 and comment line 4 from `app/foo.component.ts` (e.g. similarly make importing of the `FooService` to come via the "barrel")

**Current behavior**

- The plunk fails to load `AppComponent` when `app/main.ts` line 3 is in use (and line 4 commented)
- The plunk fails to dependency inject `FooService` when `app/foo.component.ts` line 3 is in use (and line 4 commented)

**Expected/desired behavior**

- Both bootstrapping and dependency injection should work even when using barrels to import components and services.

**Other information**

N/A

**Comment by gonzofish** [comment]
I didn't think it was possible to import a dependency from a barrel that you're putting the file into...what I mean is that, since `AppComponent` is being exported via the barrel and is trying to include `FooComponent` via that same barrel, it would have a hard time find the `FooComponent` reference.

When I pulled in `FooComponent` from `./foo.component` and `FooService` from `./foo.service` I was able to pull `AppComponent` from the barrel into `main.ts`

**Comment by jussikinnula** [comment]
I understand it now, so basically the barrels are meant to be only used outside of the directory, in another words - some other component using the component or some of it parts. So if I would have a BarComponent, it could use the FooService from FooComponent's directory - but if everything is in the same directory the files need to be addressed directly.

I guess the bug could be closed.

**Comment by gonzofish** [comment]
yes! that's how they should be used. it's so you can reference a file without doing `'../../../../app/src/components/my-component/my-component.component'` :)
