### ISSUE TITLE
Missing modules platform-browser-worker and platform-browser-ui?

### ISSUE THREAD

**Issue by datrinh** [angular/angular#8587]
Hi,

my app was running in a web worker before RC1 and the splitting into scpoed npm modules. I can't seem to get it working anymore. When will the modules be added?

**Comment by GreenToast** [comment]
The files are moved to @angular/browser-platform under src, but they seem not to be contained at npm =(, only in the github-release-srces.

**Comment by CaptainCodeman** [comment]
Checkout the weekly meeting notes - there's mention of work to make web-workers available again.

**Comment by mhevery** [comment]
Can you please provide more concrete information. I know that @vicb and @IgorMinar have been looking at resurrecting the web-worker support.

**Comment by datrinh** [comment]
Well, I'm not sure what information you need, but here is how I used to run the app pre RC1:

```
// boot.ts
import {bootstrapRender} from "angular2/platform/worker_render";

bootstrapRender("dist/loader.js");
```
```
// loader.js
importScripts("../node_modules/systemjs/dist/system.src.js",
              "../node_modules/angular2/bundles/web_worker/worker.dev.js",
              "../node_modules/rxjs/bundles/Rx.js",
              "../node_modules/angular2/bundles/angular2-polyfills.js"
              );

System.import("app/worker");
```
```
// worker.ts
import {bootstrapApp} from "angular2/platform/worker_app";
import {AppComponent} from "./app.component";

bootstrapApp(AppComponent);
```

**Comment by ratscrew** [comment]
:+1:

**Comment by vicb** [comment]
@datrinh your issue should be fixed with https://github.com/angular/angular/pull/8646, you can check the playground examples for usage. Feel free to re-open if you think something is missing/not covered in the PR.
