### ISSUE TITLE
Use Enum in an angular2-template and *ngIf

### ISSUE THREAD

**Issue by Katy91** [angular/angular#8588]
Hello,

I have a problem with using typescript enums in angular2 templates.

http://plnkr.co/edit/orQTAcYkySK3tU5wr1Me?p=preview

I hope the plunker works :)

The plunker example shows, that it is not possible to use enums with *ngIf or somethingelse in the angular2 template. But with the numeric value it works. 
Is it possible to use the enum expression?

Thanks

**Comment by woppa684** [comment]
This is by design I think ... See https://github.com/angular/angular/issues/2885

**Comment by Katy91** [comment]
Oh wow it is the solution. Thanks for this tip. 

Just one line more and it works :)

http://plnkr.co/edit/orQTAcYkySK3tU5wr1Me?p=preview

**Comment by Klyner007** [comment]
I had to make sure that my enum was an Export class.
