### ISSUE TITLE
New Router: router.generate support needed

### ISSUE THREAD

**Issue by tamascsaba** [angular/angular#8589]
In new router missing this functionality:
https://angular.io/docs/ts/latest/api/router-deprecated/index/Router-class.html#!#generate-anchor

**Comment by zoechi** [comment]
What do you need this for? AFAIK the new router only works with path.

**Comment by tamascsaba** [comment]
For permission filter (in menu) I store the permission roles in annotated component.

**Comment by zoechi** [comment]
Maybe someone else is able to interpret this. For me this information is not concrete enough (it's not necessary that I understand it to be a valid issue though ;-) )

**Comment by tamascsaba** [comment]
A little example:
```
const component = this.router.generate([name]).component;
const roles = this.getRolesByComponent(component); //magic
```

```
getRolesByComponent(component) {
    return reflector.annotations(component.componentType).filter(_ => _ instanceof PermissionMetadata)[0];
}
```

**Comment by mhevery** [comment]
New router has a different philosophy, and so it does not have generate. 

Please reopen a new issue with what use case you can't achieve.
