### ISSUE TITLE
Feature Request:[router] Support for configuring Routes lazily & dynamically using a service

### ISSUE THREAD

**Issue by ajayambre** [angular/angular#8590]
## Use Case
>An application has multiple modules and each module has multiple navigation menu items in it. 
>Both modules and navigation menu items are authorization driven and fetched using a module and menu service from the server after the user logs in.

### Expected/desired behavior
Support for configuring Routes lazily and dynamically using a service after the user logs in.

**Comment by zoechi** [comment]
Routes are per component. I don't see how this should work.

**Comment by b-strauss** [comment]
You can load components lazily. Have you tried loading a component lazily that has a routeconfig?

**Comment by ajayambre** [comment]
@zoechi  RouteMetaData was recently updated with component parameter now supporting string type.
https://github.com/angular/angular/blob/master/modules/%40angular/router/src/metadata/metadata.ts#L25

This was for lazy loading the components as you no longer require to add import statement for components.

The service could return an array of RouteMetaData with component name as string and the router could lazy load those components.

**Comment by ajayambre** [comment]
@b-strauss Even if I lazy load components, I will have to define all possible routes from that component in my code statically. I want the possible routes to be configured dynamically and loaded lazily based on the user authorizations .

**Comment by b-strauss** [comment]
The RouteConfig accepts a simple array object. Can't you load a module that has a function that gets a route config array and returns a component? I have not yet tried this myself.

```typescript
export function getMyComponent(config: Array): Type {
  @Component({
    selector: 'my-component'
  })
  @RouteConfig(array)
  class MyComponent{
    constructor() {
    }
  }

  return MyComponent;
}
```

**Comment by ajayambre** [comment]
@b-strauss I have seen similar examples of creating components and it looks OK for sample apps.
But in a large scale enterprise application, the component will have complex templates and lots of other functions and logic associated to it.

I think we need a cleaner approach to handle this.

**Comment by b-strauss** [comment]
@ajayambre But how is that different to a "normal" component that isn't nested inside a function? If your component has that much code, it should be broken up in smaller parts anyway. I don't see whats "not clean" about this solution (if it really works):

**Comment by ajayambre** [comment]
@b-strauss Thanks for your inputs on this. I will give it a try to see if that works.
What if I have multiple such components? Do I need to have multiple getMyComponents? 
Would prefer a public api though which handles this. :)

**Comment by b-strauss** [comment]
@ajayambre Well, unfortunately EcmaScript doesn't have configurable modules imports (few languages have). So yes. :) But I think this is a shortcoming of the language not angular.

Btw.: The only component you need to import like this is the one that sits at the top of your routes. Subroutes of that component can be imported normally again.

**Comment by ajayambre** [comment]
@b-strauss Have a look at this http://plnkr.co/edit/IwdcGvAokzFX8CxJEFpc?p=preview
You will get an idea of what I am trying to achieve.
The modules and screens have to be fetched based on user authorizations and links created dynamically. Each screen could be a different component with different view template and functions.

Thanks in advance :)

**Comment by ajayambre** [comment]
@mhevery I am on RC1 and wanted this feature in the new router. Is this already in plan for the new router? Why was this labelled comp:router-deprecated and not comp: router? Thanks.

**Comment by mhevery** [comment]
Yes, this will be part of the new router.

**Comment by sirajc** [comment]
Even, I have the similar use case. Building Menu from the data provided by service ,whixh is achievable. But assinging this data from service to `@Routes` is not. We need a public API for this.
And orcourse on New Router

**Comment by dominikstrasser** [comment]
@mhevery Any news when this is planned? I need this feature in order to upgrade my projects to RC :)
ps: The label of this issue should be changed to the new router and not the router-deprecated.

**Comment by LennardWesterveld** [comment]
This would be awesome, i the solution that are comming also covering my problem @mhegazy? http://stackoverflow.com/questions/37361604/angular-2-pretty-routing-api-based

**Comment by vsavkin** [comment]
@andrui We are no longer maintaining the deprecated router to focus our efforts on making the new router solid. 

This functionality is implemented in the new router. So I'm closing this issue.
