### ISSUE TITLE
Beta 17 connected ngModel's in ngFor

### ISSUE THREAD

**Issue by Fenixsar** [angular/angular#8592]
Hi! This code worked in beta 16.
```typescript
this.nowFeedback.dic = [];
this.nowFeedback.dic[0] = { value: '' };
```
```html
<div *ngFor="let dic of nowFeedback.dic; let k = index">
      <span>{{k + 1}}.</span>
      <div>
           <textarea row="5" [(ngModel)]="dic.value"></textarea>
      </div>
      <button (click)="nowFeedback.dic.splice(k, 1);"></button>
</div>
<button type="button" (click)="nowFeedback.dic[nowFeedback.dic.length]={value:''}">Add value</button>
```

But in beta 17 nowFeedback.dic[1],nowFeedback.dic[2] ... nowFeedback.dic[n] - connected;
Namely if I will change nowFeedback.dic[1] in textarea,  nowFeedback.dic[2] ... nowFeedback.dic[n] - changed too.

If I will try
```typescript
this.nowFeedback.dic = [];
this.nowFeedback.dic[0] = { value: '' };
this.nowFeedback.dic[1] = { value: '1111' };
this.nowFeedback.dic[2] = { value: '123123' };
```
0,1,2 - nice, next - connected.

P.S. Thank you. Sorry for my english.

**Comment by zoechi** [comment]
Can you create a plunker?

**Comment by Fenixsar** [comment]
[http://plnkr.co/edit/OWcVhCBTBjwDNohF467u?p=preview](url)

**Comment by zoechi** [comment]
Looks like this is indeed a bug.
`{value:''}` in 
```
<button type="button" (click)="nowFeedback.dic[nowFeedback.dic.length]={value:''}">Add value</button>
```    
creates only one instance and it is reused every time.

With 
```
<button type="button" (click)="nowFeedback.dic[nowFeedback.dic.length]=newValue()">Add value</button>
```
```
newValue() {return {value: ''};}
```
it's working as expected.

http://plnkr.co/edit/OWcVhCBTBjwDNohF467u?p=preview

**Comment by mhevery** [comment]
This is working as intended. All literals in templates are cached and reused.
