### ISSUE TITLE
Angular 2.0.0-rc.1 Router not instantiated

### ISSUE THREAD

**Issue by renehamburger** [angular/angular#8593]
In the absence of an up-to-date documentation, I can't be absolutely sure whether this is a bug or not.

The following steps are not sufficient to trigger an instantiation of the Router and activate the routing:
- Bootstrapping an app component with `ROUTER_PROVIDERS` in main.ts
- Specifying the base URL via `<base href="...">` in index.html
- Defining routes via `@Routes()` and adding the `ROUTER_DIRECTIVES` in app.component.ts

I only got this to work by adding at least one `routerLink` directive into the template, which then triggered the instantiation of `RouteSegment` and `Router`.

**Comment by brandonroberts** [comment]
@renehamburger its a known issue. See #8409

**Comment by renehamburger** [comment]
Thanks!
