### ISSUE TITLE
@Output from base class doesn't work for child class that uses @Input

### ISSUE THREAD

**Issue by mpetkov** [angular/angular#8596]
The latest angular style guide suggest to use (at)Input/(at)Output instead of inputs/outputs.  However there is a bug when using the suggesting style guide for the following scenario:

- A base class has an (at)Output
- A child class that is extending the base class and has an (at)Input

Here is code to illustrate the issue.  Please have your console open:

**Works - Base class with Output:**
https://embed.plnkr.co/LUd4vhtoZnHMmQ214GEx/

**Doesn't Work - Base class with Output and child class has Input:** (It's exact same code as above except one line is un-commented)
https://embed.plnkr.co/ThhfvnkFGoqUxWk3cXz6/

**Works - If we use the outputs method instead of (at)Output:**
https://embed.plnkr.co/2kAftKWxBX2y4Guy8VF1/

Please let me know if this is a bug or I am doing something wrong.

**Comment by CarlCui** [comment]
This is simply because all the `@`s do not get inherited. Notice in the case you use `outputs`, the thing is in the child component declaration. It has nothing to do with whether you use `@output` or `outputs`.

**Comment by mpetkov** [comment]
@CarlCui - Thank you for the input but did you look at the examples I provided?  First example inherites `@Output` and it works.  Second example it doesn't work because child is also using `@Output`.  Third example works where I use `outputs` instead of `@Output`. 

Please elaborate after looking at the examples.

**Comment by zoechi** [comment]
dup of #7191 and #5415

**Comment by mhevery** [comment]
closing as dup
