### ISSUE TITLE
bug(core): ChangeDetectorRef.detectChanges() doesn't work as well as its spec.

### ISSUE THREAD

**Issue by laco0416** [angular/angular#8597]
**Steps to reproduce and a minimal demo of the problem**

Plunker: http://plnkr.co/edit/KasOxhFhkNRaiFLmtF8X

**Current behavior**

`ChangeDetectorRef` documentation says as following: 

```
   * Detaches the change detector from the change detector tree.
   *
   * The detached change detector will not be checked until it is reattached.
   *
   * This can also be used in combination with {@link ChangeDetectorRef#detectChanges} to implement
   * local change
   * detection checks.
```

https://github.com/angular/angular/blob/bb8976608db93b9ff90a71187608a4390cbd7a07/modules/%40angular/core/src/change_detection/change_detector_ref.ts#L43-L100

I created a small example to see that behavior (plunker above).
But it seems broken. `detectChange()` is skipped while it is detached.

https://github.com/angular/angular/blob/bb8976608db93b9ff90a71187608a4390cbd7a07/modules%2F%40angular%2Fcore%2Fsrc%2Flinker%2Fview.ts#L230-L235

```
    if (this.cdMode === ChangeDetectionStrategy.Detached ||
        this.cdMode === ChangeDetectionStrategy.Checked ||
        this.cdState === ChangeDetectorState.Errored)
      return;
```

**Expected/desired behavior**

Even if it is detached, `ChangeDetectorRef.detectChanges` should execute its own detection by force.

**Other information**

**Comment by laco0416** [comment]
I think probably we need `force` option in `detectChanges`. 
Because `detectChanges()` is used as the core of `ApplicationRef`, it is difficult to change its current behavior.

My idea is:

```
// in my component
updateViewForcedly() {
  this.cdRef.detectChanges(true);
}
```

This can keep current behavior and run change detection by force even if it is detached.

**Comment by mhevery** [comment]
@vsavkin and @tbosch I would like to get your opinion on this

**Comment by tbosch** [comment]
A simpler solution would be this:
Move the check for `ChangeDetectorMode.Detached` into the loop where a parent view calls its children (i.e. `AppView. detectContentChildrenChanges` / `AppView. detectViewChildrenChanges`). Then `ChangeDetectorRef.detectChanges()` should works as expected.

**Comment by hristokostov** [comment]
Calling `detectChanges()` on a detached `ChangeDetectorRef` instance has no effect in version 2.2+

[Detached ChangeDetector example](https://angular.io/docs/ts/latest/api/core/index/ChangeDetectorRef-class.html#!#detach-anchor) from the documentation doesn't work with version 2.2 and 2.3 (it does work with 2.1).

Simple demo with manually incremented counter:

  * [2.1 works](https://plnkr.co/BEoIXH1kiAP7Y3CJLHGf)
  * [2.2 doesn't work](https://plnkr.co/iMX75SWmM8CLkCOxYdT0)

Is this a regression (maybe from [this commit](https://github.com/angular/angular/commit/e5fdf4c70ace58e5af9c99200bac3195fba530bf#diff-7628e769898d171e83796126a14d6847))? Or it is a change not reflected by the documentation yet?

**Comment by DzmitryShylovich** [comment]
I think it would be better to file a separate issue for it

**Comment by hristokostov** [comment]
OK, I'll create a new issue and delete this comment. Thanks.

**Comment by DzmitryShylovich** [comment]
@vicb this one can be closed as well after https://github.com/angular/angular/pull/13472

**Comment by DzmitryShylovich** [comment]
@laco0416 afaik it was fixed. Can you pls confirm and close the issue? Thx

**Comment by laco0416** [comment]
ok
