### ISSUE TITLE
Angular source code does not follow own file name styleguide from https://angular.io/styleguide

### ISSUE THREAD

**Issue by stasberkov** [angular/angular#8598]
**Current behavior**
Angular source code files use *underscore* for word separation.

**Expected/desired behavior**
Use *dashes* for word separation in file names to be consistent with angular guidelines. It is expected that framework source code should follow own guidelines. Angular should be an example of good style. How style can be good if developers who declare it do not use it?
https://angular.io/styleguide style 02-02.

**Comment by zoechi** [comment]
Angular source also uses `_` prefix for private fields. I guess both is necessary for transpilation to Dart.
