### ISSUE TITLE
Problem with ngFor

### ISSUE THREAD

**Issue by pamerio** [angular/angular#8602]
With this pattern:

` <li *ngFor="let test of testItems; let i = index">
             <input type="text" [(ngModel)]="test" />
 </li>`

I got this error: Cannot assign to a reference or variable! 
Last call on stack before exception: at _AstToIrVisitor.visitPropertyWrite (http://localhost:5001/node_modules/@angular/compiler/src/view_compiler/expression_converter.js

testItems is an array of string. If it was an array oj object and i put for instance test.Text into [(ngModel)] all is ok.
It's more than 6 months I use Angular2 by now but I couldn't understand this issue...

**Comment by pkozlowski-opensource** [comment]
Wouldn't `[(ngModel)]="testItems[i]"` do the trick?

I think that the error is saying that you can assign input's value to a dynamically created variable (and `test` is a dynamically created local var)

**Comment by pamerio** [comment]
thanks for the answer. Yes, it does actually....
but what's wrong with my pattern...? I'm afraid I drown in an inch of water...

**Comment by pkozlowski-opensource** [comment]
> but what's wrong with my pattern...? I'm afraid I drown in an inch of water...

`let foo` creates a local variable and `ngModel` can't assign to local variables. You can only assign to properties (fields) of your component.

**Comment by meiriko** [comment]
I tried this approach yet the input field looses focus after the first letter I enter. Any ideas?

**Comment by zoechi** [comment]
@meiriko 
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by harunurhan** [comment]
@meiriko  You need to add `trackBy` to `ngFor`
It is related to this, #4402

**Comment by nuthalapativarun** [comment]
Hey @meiriko , I'm facing the same problem you've mentioned. The input field looses focus after i enter the first letter. Did you find any solution? I've attached my working problem in here: https://plnkr.co/edit/7SSpZDec2N2zjrSUM04X?p=preview .
Please reply me.

**Comment by nuthalapativarun** [comment]
Hey @harunurhan , I'm trying to implement inline editing in Angular2 and i'm using ngFor and ngModel combined to implement this. But when i'm trying to iterate through the array and trying to edit, I can only enter or remove one letter. I've attached the working problem: https://plnkr.co/edit/7SSpZDec2N2zjrSUM04X?p=preview . Can you please help me here.

**Comment by monalisasaha79** [comment]
Hi @pamerio,

There is nothing wrong in the pattern. Issue is in the index declaration i.e. reference doesn't work if you declare the index separately.

`<li *ngFor="let test of testItems; let i = index">
<input type="text" [(ngModel)]="test" />

Your pattern will work, if you take out the "let i = index"
without this template treat this as an object. and you will not have any option to manipulate the index, like delete.

If you still need to use index, then best option if to refer direct object of the array like

<input type="text" [(ngModel)]="testItems[i]" />

Hope this clarifies.

Thanks,

**Comment by trichetriche** [comment]
For those who have an issue with the inputs (focus lost when you type a single letter) and ended up there, the answer provided by @harunurhan works like a charm.

**Comment by sirhcybe** [comment]
@trichetriche @harunurhan I'm trying the approach you suggest but I can't get it to allow me to type more than one character without the ngFor re-rendering and my input box loosing focus. Am I missing something here? 
[https://plnkr.co/edit/7YV5qfZ5IbYscRlofIXd?p=preview](https://plnkr.co/edit/7YV5qfZ5IbYscRlofIXd?p=preview)

**Comment by harunurhan** [comment]
@sirhcybe you forgot to put your trackBy function to the template

Here, it's fixed https://plnkr.co/edit/tLdmWGL22ZluIdJmTUpO?p=preview

**Comment by Fiala-CN** [comment]
@pkozlowski-opensource Thank you very much. Your answer solved my problem perfectly. Thank you.

**Comment by VadMat** [comment]
<li *ngFor="let test of testItems; let i = index">
<input type="text" [(ngModel)]="testItems[i]" />

indredible, but it works...

**Comment by HoudhaifaHamza** [comment]
But still not working with form 
it return the same value for all fields 

<form [formGroup]='Form'>
<div *ngFor="let periode of list;index as i;trackBy: trackByIndex;">
 <mat-form-field class="example-full-width">
                  <input matInput [min]="minDateT2"  [max]="maxDateT2" placeholder="Sélection dates début / fin"
                    [satDatepicker]="pickerT2" formControlName="periodeT2" name="{{i}}"  [(ngModel)]="list[i]"
                    >  </mat-form-field>
 </div>
</form>

**Comment by HoudhaifaHamza** [comment]
`<form [formGroup]='addMembreForm'>
 <div *ngFor="let periode of listPeriode2;index as i;trackBy: trackByIndex;">
 <mat-form-field class="example-full-width">
                  <input matInput [min]="minDateT2"  [max]="maxDateT2" placeholder="Sélection dates début / fin"
                    [satDatepicker]="pickerT2" formControlName="periodeT2Debut" name="{{i}}"  [(ngModel)]="listPeriode2[i]"
                    >  </mat-form-field>
 </div>
</from>`

**Comment by HoudhaifaHamza** [comment]
I found the solution :  

I added this to my input element :

[ngModelOptions]="{standalone: true}"  and make the formControlName in small case => formcontrolName if we use ngModel inside ngFor inside a Form
