### ISSUE TITLE
MS Edge is failing on SauceLabs

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#8604]
11 05 2016 00:58:35.765:ERROR [launcher.sauce]: Heartbeat to microsoftedge 20.10240 (Windows 10) failed
  [title()] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: Unknown error (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 285 milliseconds
Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
System info: host: 'WIN-SB3ER6JQ6ME', ip: '172.20.60.246', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_73'
Driver info: org.openqa.selenium.edge.EdgeDriver
Capabilities [{acceptSslCerts=true, browserVersion=25.10586.0.0, platformVersion=10, browserName=MicrosoftEdge, takesScreenshot=true, pageLoadStrategy=normal, takesElementScreenshot=true, platformName=windows, platform=ANY}]
Session ID: XXXXXXXX-XXXX-XXXX-XXXX-XXXX478C1C1A
11 05 2016 00:58:35.766:ERROR [launcher]: microsoftedge 20.10240 (Windows 10) on SauceLabs failed 2 times (failure). Giving up.

**Comment by IgorMinar** [comment]
I attempted to move edge to browserstack but on the first run edge disconnected in the middle of a test run. I've temporarily disabled edge for now in #8601

**Comment by mehmetg** [comment]
@IgorMinar Trying to replicate, but the master branch fails to build let alone test with instructions provided in the repo? Could you provide any pointers? 
```FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
[1]    76538 abort      $(npm bin)/gulp build.js```

**Comment by mehmetg** [comment]
Update: I was able to build from your branch and run Edge tests. I believe the problem is stemming from Karma's sensitivity to browser disconnects. Using the karma option **browserDisconnectTolerance** helps. Also, I do recommend upgrading to **'selenium-version': '2.53.0'** in the karma-js.conf.js file.
After the two changes I was unable to reproduce the issue on Sauce Labs.

``` function launchKarmaWithExternalBrowsers(reporters, browsers, done) {
  var karma = require('karma');

  new karma.Server(
               {
                 configFile: __dirname + '/karma-js.conf.js',
                 singleRun: true,
                 browserNoActivityTimeout: 240000,
                 captureTimeout: 120000,
                 reporters: reporters,
                 browsers: browsers,
                 browserDisconnectTolerance: 5,
               },
               function(err) {
                 done();
                 process.exit(err ? 1 : 0);
               })
      .start();
}```

**Comment by IgorMinar** [comment]
@mehmetg we've already [upgraded the selenium version](https://github.com/angular/angular/commit/d537a26297c44d3d9638b799a46e689187d6752b), so I tried to reenable edge and it still failed: https://travis-ci.org/angular/angular/jobs/129839354#L1001

the best way to repro this is by sending a PR with a change and seeing it fail on travis. running the tests on saucelabs locally is possible but quite tricky right now.

**Comment by mehmetg** [comment]
@IgorMinar I have jumped through the hoops yesterday. I agree. I will do a PR and see what I can find out. Thank you for the link.

**Comment by mehmetg** [comment]
@IgorMinar I just upgraded the SC version and added the disconnect tolerance into the karma config. This should help waiting for travis results anxiously.

**Comment by pkozlowski-opensource** [comment]
@mlaval Marc, I think this is already fixed and could be closed, right?

**Comment by mlaval** [comment]
It seems to be quite stable on BrowserStack, where the preview version (14.xxx) of Edge is the default.
Given that we haven't been able to do run consistant campaigns on SL or BS with the stable (13.xxx) version, I think the current setup is good.
