### ISSUE TITLE
angular2  angular/2.0.0-rc.1  routing is not working

### ISSUE THREAD

**Issue by RohitLuthra19** [angular/angular#8607]
Hi,
I am trying to use Angular2 release candidate's routing feature but its not working showing an error.
![image](https://cloud.githubusercontent.com/assets/11659536/15204633/f35bc8de-182c-11e6-8def-5b11d9ef2f91.png)

**Comment by Elanor-L** [comment]
Hi,
There's a new file to add in your index. It's called systemjs.config.js
Just look for it in the quickstart.

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by RohitLuthra19** [comment]
For me its an issue ... so i reported it....

**Comment by ericmartinezr** [comment]
@RohitLuthra19 make sure you included `@angular/router` in your config.

Like

```
    '@angular/router': {
      main: 'router.umd.js',   // not sure this is the exact bundle name
      defaultExtension: 'js'
    },
```
Although I would recommend you to bundle your own app instead of using this plnkr-only config.

**Comment by RohitLuthra19** [comment]
Thanks @ericmartinezr  and @Elanor-L for your kind help...
You both gave me right suggestion...
**thanks alot...**

**Comment by zoechi** [comment]
@RohitLuthra19 Sure, but the other channels can help you to figure out if it's actually a bug and then you still can report it here.

**Comment by RohitLuthra19** [comment]
Ok,,, @zoechi  i will try to report further issue there...Thanks for the reply...
