### ISSUE TITLE
Please see how pissed off everyone is at you after ng-conf -- re: router changes

### ISSUE THREAD

**Issue by denodaeus** [angular/angular#8608]
1500 issues open in RC is just embarrassing, especially when you guys provided a burn down to RC chart that was just irrelevant.

https://www.reddit.com/r/Angular2/comments/4iwaup/whats_happening_to_the_angular2_router/

**Comment by ericmartinezr** [comment]
@CaptainCodeman and @choeller are there, I'm not surprised.

**Comment by choeller** [comment]
:joy: IMO @aQutie really hit the point, that the way things are currently communicated are really unfair to the community - I totally appreciate the work done by the team and the new features look awesome, but on the other hand it's also important to be honest about the current state - people are (were) relying on that and currently being told "we*re really close" seems just awkward to me...

**Comment by choeller** [comment]
and just to make sure no one gets me wrong because of answering here - I'm *not* "pissed" at the team after ng-conf - they do a great job on the product - I just critizise the current way of communicating with / involving the community...

**Comment by PeEllAvaj** [comment]
@denodaeus @choeller Thanks for your messages. @robwormald and I very recently joined the Angular team as Developer Advocates and part of our mission is to help make sure you are being heard and that your concerns are being addressed. We are working on a communication and community plan that will hopefully give you a better way to funnel your frustrations into collaboration.
