### ISSUE TITLE
Angular2 Relative Paths for template and styleURL's using moduleId.

### ISSUE THREAD

**Issue by PardeepJain** [angular/angular#8609]
While Searching i found something named as `moduleId` to set the relative paths of template and css files,
  but I don't know exactly how to use moduleId in our components of angular2. actully the problem is in my folder structure,
  i am loading my all .js files from `dist` folder whereas my view(.html files) are in the `src` folder.so when i am using
  `moduleId: module.id` like this angular took the path from dist folder, instead of src folder. so anybody here help me tell
  that How to set custom moduleId for my component angualr2.
  
  my folder structure like this.
  
                                      App
                                      /\
                                     /  \
                 (.js + .map files)Dist    Src(.ts + .html + .css files)

* Folder Dist containes all .map and .js files
* Folder src containes all .ts, .HTML, and .css file.

Actual coding (working) - 

    @Component({
    	selector: 'class-timing',
    	templateUrl: 'src/components/TimeTable/class-timing/class-timing.html',
    	styleUrls: ['src/app.css']
    })

Modified coding (Not working due to incorrect path) - 

    @Component({
    	selector: 'class-timing',
    	templateUrl: 'class-timing.html',
    	moduleId: module.id,
    	styleUrls: ['src/app.css']
    })

Referring to this tutorial
http://schwarty.com/2015/12/22/angular2-relative-paths-for-templateurl-and-styleurls/

**Comment by pe8ter** [comment]
If your JS files live in dist then so must your HTML/CSS. You need to a build step to copy them over. Once they are there you configure your component like this:

    @Component({
        selector: 'class-timing',
        templateUrl: './class-timing.html',
        moduleId: module.id,
        ...
    })

Notice how the path begins with a period.

**Comment by mhevery** [comment]
working as intended, please copy the files to `dist`

**Comment by devin6391** [comment]
What is module? What does it refer to. My browser tells me that there id not present in undefined variable named module.

**Comment by DzmitryShylovich** [comment]
See https://github.com/angular/angular/issues/6131#issuecomment-167775780
