### ISSUE TITLE
Problem with @Directive

### ISSUE THREAD

**Issue by ardf69** [angular/angular#8610]
I was playing with angular 2.0.0-beta.15 and polymer and it works well but I found a bug (not blocking) with @Directive.
In a my template there is a code like this

```
<paper-tabs selected="0">
    <paper-tab>test1</paper-tab>
   ...
    <paper-tab>testn</paper-tab>
</paper-tabs>

```
and as a glue (to map polymer change events to angular change events) I use

```
@Directive({
    selector: 'paper-tabs',
    host: {
        '(selected-changed)': 'selectedChange.next($event.target.selected)'
    }
})
export class PaperTabsGlue {
    @Output() selectedChange:EventEmitter<any> = new EventEmitter();
}
```

If I run the code it gives me the error:

browser_adapter.ts:73 EXCEPTION: Attempt to use a dehydrated detector: ContentComponent_0 -> selected-changed

The problem is that polymer start to dispatch an selected-changed event before the PaperTabsGlue directive is ready. All the other selected-changed events are correctly handled.
A workaround is to write the template as

```
<paper-tabs [selected]="mySelectModel">
    <paper-tab>test1</paper-tab>
   ...
    <paper-tab>testn</paper-tab>
</paper-tabs>

```
Ciao Angelo

**Comment by vicb** [comment]
obsolete
