### ISSUE TITLE
The AsyncTestCompleter class should be defined as provider in RC1

### ISSUE THREAD

**Issue by templth** [angular/angular#8611]
**Steps to reproduce and a minimal demo of the problem**

If I only define platform and application providers for testing as described below:

```
(...)
import {AsyncTestCompleter} from '@angular/core/testing/async_test_completer';

import {
    TEST_BROWSER_DYNAMIC_PLATFORM_PROVIDERS,
    TEST_BROWSER_DYNAMIC_APPLICATION_PROVIDERS
} from '@angular/platform-browser-dynamic/testing/browser';


describe('Test for graticule layer', () => {
  setBaseTestProviders(TEST_BROWSER_DYNAMIC_PLATFORM_PROVIDERS,
    [TEST_BROWSER_DYNAMIC_APPLICATION_PROVIDERS, , AsyncTestCompleter]);

  it('should something',
    inject([TestComponentBuilder, AsyncTestCompleter], (tcb: TestComponentBuilder, async) => {
      (...)
    })):
});
```

I have the following error:

> Error: No provider for AsyncTestCompleter!

**Current behavior**

To make things works I need to explicitly add this provider:

```
setBaseTestProviders(TEST_BROWSER_DYNAMIC_PLATFORM_PROVIDERS,
    [TEST_BROWSER_DYNAMIC_APPLICATION_PROVIDERS, AsyncTestCompleter]);

```

**Expected/desired behavior**

It will great not to have to specify it esplicitly.

**Other information**

**Comment by cexbrayat** [comment]
@templth Isn't this supposed to be an internal API? 

You should be able to write async tests without this, using `async()` or `fakeAsync()`. Or is there a particular use case not covered you have in mind ?

**Comment by mhevery** [comment]
This is an internal API. You should be only importing things from `@angular/core/testing` not deep imports.

**Comment by templth** [comment]
See what you mean @cexbrayat and @mhevery! Thanks your comments!
