### ISSUE TITLE
node_modules/crypto is not found 

### ISSUE THREAD

**Issue by RohitLuthra19** [angular/angular#8612]
Hi ,
I am trying to create webapp with angular2-highcharts but its showing an error in console
**_node_modules/crypto_** is not found 

![image](https://cloud.githubusercontent.com/assets/11659536/15209935/7c242390-1851-11e6-8b58-f52892265486.png)

**Comment by DamonGant** [comment]
You need to install the crypto shim.

`npm i crypto`

**Comment by RohitLuthra19** [comment]
I have used it .. but didn't work for me...

**Comment by RohitLuthra19** [comment]
@ericmartinezr  @Elanor-L 
Can you please help in this issue ...

**Comment by kukicadnan** [comment]
do you see the crypto library in your node_modules folder?

**Comment by RohitLuthra19** [comment]
Yes

**Comment by mhevery** [comment]
This is not Angular related, therefore we are closing it. Check out https://angular.io/resources/ for ideas on how you can get your questions answered with the community.

**Comment by RohitLuthra19** [comment]
If this is not angular2 related then please help me..

**Comment by RohitLuthra19** [comment]
Yes you are right @mhevery ..This was because of Reflect
/*import "node_modules/reflect-metadata/Reflect.js";*/
 Finally I get my solution by own..
