### ISSUE TITLE
Gracefully detect missing metadata

### ISSUE THREAD

**Issue by schittler** [angular/angular#8614]
In some cases, especially working with TypeScript, metadata could go missing (`emitDecoratorMetadata` not set). Right now angular makes the assumption that metadata is intact, leading to cryptic error messages (things like `cannot read query of null`). Angular should do some simple checks and throw a more useful error message.

**Comment by zoechi** [comment]
related to #7481

**Comment by mhevery** [comment]
Yes, that would be nice, but I don't see a mechanism by which Angular could determine that. Do you have ideas?

**Comment by DamonGant** [comment]
Well, `_getContentQueries` in compiler/provider_parser seems to be the place it's crashing for most people that encountered the issue I know about. `directive.type.diDeps` is `[null]` when metadata is missing and you're trying to inject a component. A check around there for `dep === null` would be a good start.

I don't know enough about reflect-metadata to point out a better solution unfortunately.

**Comment by DzmitryShylovich** [comment]
@DamonGant is this still an issue with the latest angular?

**Comment by pkozlowski-opensource** [comment]
I believe that this one is obsolete with the latest compiler rewrites.
