### ISSUE TITLE
Angular2: Template will fail with error if Router is in providers while routerLink is used in template.

### ISSUE THREAD

**Issue by oodboo** [angular/angular#8619]
A child template will fail if you uncomment following **/*, Router*/** and **//private _router: Router,**

```
@Component({
    template:`
        <h1>Add a User</h1>
        <div class="col-md-6 col-lg-6">
            <a class="btn btn-primary" [routerLink]="['ListUsers']">Add User</a>
        </div>
    `,
    directives: [ROUTER_DIRECTIVES],
    providers: [HTTP_PROVIDERS, UserService /*, Router*/]
})
export class NewUserComponent {
    form: ControlGroup;

    constructor(
        _fb: FormBuilder,
        //private _router: Router,
        private _userService: UserService
    ) {}
}
```

with following error:
```
EXCEPTION: Error in ./NewUserComponent class NewUserComponent - inline template:3:39 angular2.dev.js:25644:9

ORIGINAL EXCEPTION: TypeError: this.registry is undefined angular2.dev.js:25644:9

ORIGINAL STACKTRACE: angular2.dev.js:25644:9

Router</Router.prototype.generate@http://localhost:3000/node_modules/angular2/bundles/router.dev.js:3305:7
RouterLink</RouterLink.prototype._updateLink@http://localhost:3000/node_modules/angular2/bundles/router.dev.js:1455:37
```

Routes are defined in central component like this:

```
@RouteConfig([
    { path: '/', name: 'ListUsers', component: ListUsersComponent, useAsDefault: true },
    { path: '/new', name: 'NewUser', component: NewUserComponent },
])

```
I will try this in rc1, shortly for now this is issue for beta17.

Aditionally TypeScript will fail if comment is here but I guess this is issue for TypeScript compiler:
export class NewUserComponent /*implements CanDeactivate*/ {

**Comment by brandonroberts** [comment]
You don't need to add the Router to the providers array. Its already provided through the ROUTER_PROVIDERS. All you need to do is import it and use it in your constructor.

**Comment by oodboo** [comment]
Are ROUTER_PROVIDERS default so they do not need to be declared in the form "providers: [ROUTER_PROVIDERS] Or because they are defined in bootstrap level ?

import {ROUTER_PROVIDERS}    from 'angular2/router';
bootstrap(AppComponent, [ROUTER_PROVIDERS]);

**Comment by brandonroberts** [comment]
Right. Since you've included ROUTER_PROVIDERS in the bootstrap array, the services it provide don't need to be provided again further down in the application.
