### ISSUE TITLE
@Inject(token) throws 'No provider for @Inject(Token initState)!'

### ISSUE THREAD

**Issue by alvipeo** [angular/angular#8623]
@vsavkin has a great [article on state management](http://victorsavkin.com/post/137821436516/managing-state-in-angular-2-applications), so I use it in my app. Victor provides a [Plunkr](http://plnkr.co/edit/rDq2LUMz0iNdlv54CfUj?p=preview) to the article and it works but it uses beta.1.

Now, I created a new project with angular-cli (the latest) and added state management to it, **splitting it to separate files**. See this project - [project done in VS Code](http://inus.blob.core.windows.net/ttl/InjectTest.zip?sv=2014-02-14&ss=2016-05-12T21%3A03%3A14Z&se=2016-05-19T21%3A03%3A10Z&sp=r&sr=b&sig=p32hkyTz%2BksvqCuUhXDnFHbYLj5M9jCxDLFs6djKMN0%3D). But when I run it I get the following error:

>> **No provider for @Inject(Token initState)!**

but there IS injection (file /shared/state/diconfig.ts):
```
// -- DI config
export const initState = new OpaqueToken("initState");
export const dispatcher = new OpaqueToken("dispatcher");
export const state = new OpaqueToken("state");

export const stateAndDispatcher = [
  provide(initState, {useValue: {todos: [], visibilityFilter: 'SHOW_ALL'}}),
  provide(dispatcher, {useValue: new Subject<Action>(null)}),
  provide(state, {useFactory: stateFn, deps: [new Inject(initState), new Inject(dispatcher)]})
];
```

So, why it worked in beta.1 and doesn't work in RC1? Is this a bug or just something changed in the DI?

**Comment by PascalPrecht** [comment]
Hi, can you please setup a plunker that reproduces the error?

Thanks!

**Comment by alvipeo** [comment]
Well, not sure. I can try. Is that zip not enough? 2 steps - Unzip, 'ng serve'.

**Comment by pkozlowski-opensource** [comment]
> Well, not sure. I can try. Is that zip not enough? 2 steps - Unzip, 'ng serve'.

Nope. As a rule of thumb I would never, ever download, unpack and run random things from GitHub

**Comment by alvipeo** [comment]
got it. doing it now...

**Comment by alvipeo** [comment]
here we go - http://plnkr.co/edit/zJfUeUzY1XgINbTq16m5?p=preview

**Comment by mhevery** [comment]
1. Your example is too complicate. Please create a simpler one.
2. Change your `diconfig.ts` to `provide(state, {useFactory: stateFn, deps: [initState, dispatcher]})` to make the error go away. 
3. I don't see anything working, so I am not sure if there are more issues.

Please re-open with a simpler usecase and specific steps needed to re-create the problem and expected and actual behavior.

**Comment by alvipeo** [comment]
ok, exact copy of @vsavkin Plunkr, but converted to RC1:
1. Igor's plunkr **beta.1** - http://plnkr.co/edit/rDq2LUMz0iNdlv54CfUj?p=preview
2. same Plunkr **RC.1** - http://plnkr.co/edit/lKjMY4BuAOR6y1blumAN?p=preview

Please reopen.

**Comment by alvipeo** [comment]
What I'm telling you is that the same code that worked in beta.1 doesn't work in RC1. More specifically, this part
```
// -- DI config
const initState = new OpaqueToken("initState");
const dispatcher = new OpaqueToken("dispatcher");
const state = new OpaqueToken("state");

const stateAndDispatcher = [
  provide(initState, {useValue: {todos: [], visibilityFilter: 'SHOW_ALL'}}),
  provide(dispatcher, {useValue: new Subject<Action>(null)}),
  provide(state, {useFactory: stateFn, deps: [new Inject(initState), new Inject(dispatcher)]})
];
```
used to work in beta.1 and now it doesn't. In order to see the error, please open the console.

Can't put it more simpler.

**Comment by alvipeo** [comment]
Oh, I just found out what I missed. This:
```
provide(state, {useFactory: stateFn, deps: [new Inject(initState), new Inject(dispatcher)]})
```
throws error. By @mhevery advice I changed it to:
```
provide(state, {useFactory: stateFn, deps: [initState, dispatcher]})
```
and it all works now. But I don't understand why should we remove new Inject(). Please give me a link to docs that explains it.

**Comment by mhevery** [comment]
@alvipeo you are right, in that in the past we were more free and would auto unwrap the `Inject`, but that was not correct. The correct behavior is the current behavior.

Here is how to think about it.

```
const token = new OpequeToken('token');
class MyClass {
  constructor(@Inject(token) x:any){}
}
```

Here the `@inject` is needed because we need a decorator to store the `token` someplace.

In this case we don't need it:
```
provide(MyClass, {useFactory: ..., deps: [token]}
```

Because if we wrap it we are saying that the what we are injecting is the `Inject` instance rather than the `token`. So that was incorrect behavior in the past.

If we write this:
```
provide(MyClass, {useFactory: ..., deps: [token]}
```

it would mean:
```
const token = new OpequeToken('token');
class MyClass {
  constructor(@Inject(new Inject(token)) x:any){}
}
```

which is not what you mean.

**Comment by alvipeo** [comment]
So, in other words, what goes into _deps_ should be plain dependencies, and not wrapped into Inject (or anything). Is that correct statement?

**Comment by mhevery** [comment]
Yes, that is correct.

**Comment by alvipeo** [comment]
Thank you! Hopefully this thread will help others too.

**Comment by GrantGochnauer** [comment]
Thank you - this helped me!
