### ISSUE TITLE
compiler_cli: Unable to find any resolvable import

### ISSUE THREAD

**Issue by ludohenin** [angular/angular#8625]
In this scenario, 

```
├── +home
│   ├── home.component.css
│   ├── home.component.html
│   ├── home.component.ts
└── shared
    ├── index.ts
    ├── name-list
    │   ├── index.ts
    │   └── name-list.service.ts
```
where in `home.component.ts`
```
import {NameListService} from '../shared/index'
```

I'm getting an error from `NodeReflectorHost.prototype.getImportPath`

**Comment by mhevery** [comment]
Thank you for submitting the issue. All issues require an easy way to demonstrates the problem and how to reproduce it. Can you provide a zip file and the commands needed to reproduce it.

**Comment by ludohenin** [comment]
Here it is.
[demo.zip](https://github.com/angular/angular/files/262829/demo.zip)
execute `./demo.sh`

_I'm also having an issue with `COMMON_DIRECTIVE` that needs to be included in the component where those directives are used (but I should probably have to submit another issue for that ?)_

**Comment by vicb** [comment]
obsolete
