### ISSUE TITLE
router-deprecated doesn't trigger Location.subscribe

### ISSUE THREAD

**Issue by JulioC** [angular/angular#8630]
When changing routes using router-deprecated, `Location.subscribe` never gets triggered.

It should trigger the subscription, since it's the only method available to check for URL changes keeping compatibility with the new router.

From my initial investigation, `window.onpushstate` and `window.onhashchange`, which Location (indirectly) uses to check for URL changes, never get called when changing routes (manually changing the hash does trigger them). I suspect it's related to the method router-deprecated uses to set the hash, but I couldn't dig any further.

**Comment by mhevery** [comment]
Thank you for submitting the issue. All issues require a [plunker](https://plnkr.co/) which demonstrates the problem and how to reproduce it. Please re-open the issue or create a new issue once you have a reproducible use case.

We are sorry that we are so aggressive on closing the issues. We are overwhelmed with the number of issues we get, and so we only have time to look at the ones which are easy for us to reproduce.

**Comment by JulioC** [comment]
Here it is: http://plnkr.co/edit/EGUZfXdCVowTS102mDQG

**Comment by vsavkin** [comment]
We are no longer maintaining the deprecated router to focus our efforts on making the new router robust. So I'm closing this issue.

Could you reopen the issue with the plunker using the new router?
