### ISSUE TITLE
Issue with access data in angular v1 directive after upgrading it with 'upgradeAdapter.upgradeNg1Component(...)'

### ISSUE THREAD

**Issue by huyph** [angular/angular#8631]
**Steps to reproduce a minimal demo of the problem**

- Run this: https://plnkr.co/edit/mXzBehUZW9G3Z5u9D8gA?p=preview
- And obverse two different ouputs for  anuglar one directive

**Current behavior**
- `$scope.data` is undefined if it is called by the upgraded angular v1 directive (the one produced by upgradeAdapter.upgradeNg1Component(...))

**Expected/desired behavior**
- `$scope.data` should be accessible the same way it used to be in angular v1

OR is there any workaround for now?

**Comment by mhevery** [comment]
The issue seems to be that the `ngUpgrade` is not honoring the `scope` binding.

**Comment by hannahhoward** [comment]
the scope binding is working, but the binding happens after the controller or link functions are called. I've submitted a PR to delay calling these function till the ngOnInit lifecycle hook, so this won't be an issue, at least when bindToController isn't used.

btw, there is a work around for now-- make a $onInit() function on scope inside your controller/link function and put your code inside it.

**Comment by mhevery** [comment]
@hannahhoward do you have a link to the PR?

**Comment by hannahhoward** [comment]
https://github.com/angular/angular/issues/8645

**Comment by mhevery** [comment]
Thank you for your PR.

**Comment by huyph** [comment]
Nice. Thanks heaps guys! 👍

**Comment by huyph** [comment]
It seems RC4 does resolve this issue. 

But i want to report an issue on passing a function. The following works fine in angular 1, but not angular 2

In a ng2 component's template, I have
```javascript
<ng1Directive (publishDataFunc)="publishDataFuncFromNg2(id)"
```

Then somewhere in that ng1 directive, I have:
```javascript
publishDataFunc: '&'
...
publishData({
   id: '123'
});
}
...
```

`id` is undefined when it gets to `publishDataFuncFromNg2` though. 

In the angular 1's world, this works by doing:
```javascript
<ng1Directive publish-data-func="someFunc(id)"
```
Could it because the upgraded directive does not support `dash-separated` attrtibute name? And `dash-separated` is the key to get this working..?
