### ISSUE TITLE
UpgradeAdapter does not call ng1 controller lifecycle methods

### ISSUE THREAD

**Issue by palmanis** [angular/angular#8632]
** Steps to reproduce **
https://plnkr.co/edit/bnV4PCQmF8f7AYqD3VUp
The example has an ng1 directive as per the upgrade guidelines https://angular.io/docs/ts/latest/guide/upgrade.html#!#using-component-directives

Part 1: ng2 component is using upgraded ng1 component inside. When the button is clicked, it does change the baseValue, but DOES NOT call the $onChanges lifecycle method which calculates the derivedValue, so the derivedValue never gets updated.

Part 2: This confirms, that in purely ng1 mode, the directive works fine, clicking the button does increment baseValue and through $onChanges method the derivedValue also gets updated.

**Current behavior**
$onChanges is not getting called for ng1 directive, when a change is initiated from ng2 component. The value bound is updated, but the directive does not get to know that something changed. So there is no way to run any change handlers.

**Expected/desired behavior**
$onChanges should get called on ng1 controller, when a change is initiated from ng2 component, so that the code can update any derivedValues based on the change.
Not just $onChanges, but all the lifecycle methods should get called.

**Other information**
I did raise this issue earlier also, but did not attach an example, not sure if that is the reason why nobody looked at it. 
https://github.com/angular/angular/issues/8304
This is really important, since without this, i don't see what use does the UpgradeAdapter have ?

**Comment by palmanis** [comment]
So what will it take for the angular team to look into this ?
Are people going in for the UpgradeAdapter route not the priority ?

**Comment by zoechi** [comment]
There are lots of important issues. If this is about the same problem as #8304, then please close this issue and add the additional information to #8304

**Comment by palmanis** [comment]
Information added to original issue #8304

**Comment by palmanis** [comment]
@zoechi : I closed this, but would be good, if you can pick up #8304, UpgradeAdapter seems to have way too many limitations in the first place to be much useful, and if the documented features also do not work, it isn't much useful.
