### ISSUE TITLE
providers: [ROUTER_PROVIDERS] in multiple Components in RC.1 causes: default router-outlet not found

### ISSUE THREAD

**Issue by MiltoxBeyond** [angular/angular#8633]
## This is more of a note for documentation purposes. 
**Steps to reproduce and a minimal demo of the problem**

Create multiple Components with nested routes, including ROUTE_PROVIDERS in the providers member of the `@Component` decorator on the Subcomponents.

Example: 

```
@Component({
  selector:'child',
  template: 'Child',
})
export class ChildComponent {}

@Component({
  selector: 'sub',
  template: '<router-outlet></router-outlet>',
  providers: [ROUTER_PROVIDERS],
  directives: [ROUTER_DIRECTIVES]
})
@Route([
 ...
])
export class SubComponent {}

@Component({
  selector: 'main',
  template: '<router-outlet></router-outlet>',
  providers: [ROUTER_PROVIDERS],
  directives: [ROUTER_DIRECTIVES]
})
@Route([
{ path: '/sub', component: SubComponent }
])
export class MainComponent {}

bootstrap(MainComponent); // or bootstrap(MainComponent, [ROUTER_PROVIDERS]);
```

_What steps should we try in your demo to see the problem?_

Run it...

**Current behavior**

Basically if you run it the router throws an error saying it cannot find the default router-outlet, which set me off on a quest to ensure that the router-outlets were defined etc.

**Expected/desired behavior**

A simple routing demo.  The way I got it to work was removing the ROUTER_PROVIDERS from all components and adding it to the bootstrap.  Apart from simplifying my code, it actually worked for my routes and nested routes(finally).

**Other information**
Any hints on how to do `AsyncRoutes` again with the new `Route` implementation?  I figure the Async is probably a work in progress for the new router, although seeing as this is a Release Candidate it is slightly worrisome that we are getting close to a final milestone without it.

**Comment by zoechi** [comment]
AFAIK this is by design. Why do you want to add them to different components? These components get new disconnected instances of the provides in `ROUTER_PROVIDERS`

**Comment by MiltoxBeyond** [comment]
I was doing it similar to how you have in the documentation, but since
nested routers weren't mentioned nor is it clear that child routers are
connected to a parent, seeing as they aren't included in the providers
array of the parent component.  I figured it out through trial and error
and figured I'd share my experience to ensure it is clear in the final
documentation since the error message wasn't clear
On May 13, 2016 5:43 AM, "Günter Zöchbauer" <notifications@github.com>
wrote:

AFAIK this is by design. Why do you want to add them to different
components? These components get new disconnected instances of the provides
in ROUTER_PROVIDERS

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/angular/angular/issues/8633#issuecomment-219010111>

**Comment by vicb** [comment]
obsolete

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20781542/96509688-b7be-11e6-8783-d8587fde4c40.png)
![Uploading 图片.png…]()
