### ISSUE TITLE
bug(build) Build broken when doing a clean checkout and following Developer-Explanations

### ISSUE THREAD

**Issue by choeller** [angular/angular#8637]
**Steps to reproduce and a minimal demo of the problem**

Doing a clean checkout of angular leads to several errors when trying to build angular from master. Doing

```
 git clone https://github.com/angular/angular.git
 npm i
node --max_old_space_size=4000 ./node_modules/.bin/gulp build.js
```

leads to 

```
[10:24:03] Finished 'build/clean.bundles.benchpress' after 4.45 ms
[10:24:03] Finished 'build/clean.js' after 139 ms
[10:24:03] Starting 'build.js.dev'...
[10:24:03] Finished 'build/clean.tools' after 219 ms
[10:24:03] Starting 'build.tools'...
[10:24:03] Starting '!build.tools'...
[10:24:04] Starting 'clean'...
[10:24:04] Finished 'clean' after 4.89 μs
[10:24:04] Starting '!bundle.ng.polyfills'...
[10:24:04] Starting '!bundles.js.docs'...
[10:24:04] Finished '!bundles.js.docs' after 15 ms
[10:24:04] Finished '!bundle.ng.polyfills' after 335 ms
tools/broccoli/angular_builder.ts(1,16): error TS2304: Cannot find name 'require'.
tools/broccoli/angular_builder.ts(2,10): error TS2304: Cannot find name 'require'.
tools/broccoli/angular_builder.ts(3,23): error TS2304: Cannot find name 'require'.
tools/broccoli/angular_builder.ts(4,20): error TS2304: Cannot find name 'require'.
tools/broccoli/angular_builder.ts(5,12): error TS2304: Cannot find name 'require'.
tools/broccoli/angular_builder.ts(6,22): error TS2304: Cannot find name 'require'.
tools/broccoli/angular_builder.ts(7,9): error TS2304: Cannot find name 'require'.
tools/broccoli/angular_builder.ts(40,48): error TS2304: Cannot find name 'Promise'.
tools/broccoli/angular_builder.ts(46,49): error TS2304: Cannot find name 'Promise'.
tools/broccoli/angular_builder.ts(52,42): error TS2304: Cannot find name 'Promise'.
tools/broccoli/angular_builder.ts(58,49): error TS2304: Cannot find name 'Promise'.
tools/broccoli/angular_builder.ts(64,14): error TS2304: Cannot find name 'Promise'.
tools/broccoli/angular_builder.ts(119,24): error TS2304: Cannot find name 'require'.
tools/broccoli/broccoli-check-imports.ts(1,21): error TS2307: Cannot find module 'fs'.
```

as the typings are not installed via tsd in the tools folder. Doing a manual `tsd install` in tools folder then leads to further errors when executing the build:

```
[10:10:48] Finished '!build.tools' after 3.22 s
[10:10:48] Finished 'build.tools' after 3.22 s
[10:10:48] Starting 'broccoli.js.dev'...
[10:10:48] Starting '!broccoli.js.dev'...
[10:10:48] Starting 'build.js.prod'...
[10:10:48] Starting '!broccoli.js.prod'...
[10:10:48] Starting 'build.js.cjs'...
[10:10:48] Starting '!build.js.cjs'...
[10:10:48] '!broccoli.js.dev' errored after 71 ms
[10:10:48] Error: ENOENT: no such file or directory, lstat 'modules/angular2'
    at Error (native)
    at Object.fs.lstatSync (fs.js:887:18)
    at symlink (/home/christoph/sources/angular/node_modules/symlink-or-copy/index.js:63:26)
    at symlinkOrCopySync (/home/christoph/sources/angular/node_modules/symlink-or-copy/index.js:58:5)
    at /home/christoph/sources/angular/node_modules/broccoli-plugin/read_compat.js:58:9
    at lib$rsvp$$internal$$tryCatch (/home/christoph/sources/angular/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/home/christoph/sources/angular/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/home/christoph/sources/angular/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/home/christoph/sources/angular/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
```

creating this folder manually and running the build leads to:

```
[10:14:45] Finished 'build.tools' after 3.17 s
[10:14:45] Starting 'broccoli.js.dev'...
[10:14:45] Starting '!broccoli.js.dev'...
[10:14:45] Starting 'build.js.prod'...
[10:14:45] Starting '!broccoli.js.prod'...
[10:14:45] Starting 'build.js.cjs'...
[10:14:45] Starting '!build.js.cjs'...
[10:14:45] '!build.js.cjs' errored after 400 ms
[10:14:45] Error: ENOENT: no such file or directory, lstat '/home/christoph/sources/angular/tmp/funnel-input_base_path-QH7r3x9b.tmp/0/angular2/typings/hammerjs/hammerjs.d.ts'
    at Error (native)
    at Object.fs.lstatSync (fs.js:887:18)
    at symlink (/home/christoph/sources/angular/node_modules/symlink-or-copy/index.js:63:26)
    at Function.symlinkOrCopySync [as sync] (/home/christoph/sources/angular/node_modules/symlink-or-copy/index.js:58:5)
    at Funnel._copy (/home/christoph/sources/angular/node_modules/broccoli-funnel/index.js:398:19)
    at Funnel.processFile (/home/christoph/sources/angular/node_modules/broccoli-funnel/index.js:381:8)
    at Funnel.applyPatch [as _applyPatch] (/home/christoph/sources/angular/node_modules/broccoli-funnel/index.js:298:12)
    at Funnel.<anonymous> (/home/christoph/sources/angular/node_modules/broccoli-funnel/index.js:250:10)
    at Array.forEach (native)
    at Funnel.processFilters (/home/christoph/sources/angular/node_modules/broccoli-funnel/index.js:249:9)
```

then I gave up... 

**Expected/desired behavior**

Build of a clean checkout should be possible just following the Developer Guidelines:

https://github.com/angular/angular/blob/master/DEVELOPER.md

**Other information**

**Comment by choeller** [comment]
Hmm, looking at `gulpfile.js` it looks that all the paths are still pointing to `modules/angular2` so this is just not possible to work. I now wonder how the build of the master is running for the internal builds - is it not using `gulp` anylonger?!

**Comment by brandonroberts** [comment]
The normal build process is broken at the moment. You can use the `./scripts/ci-lite/install.sh` to install dependencies and typings and the `./build.sh` scripts to get a build working.

You'll need to add the following to line 7 in the `./build.sh` script

```sh
    export NODE_PATH=$NODE_PATH:$(pwd)/dist/all:$(pwd)/dist/tools
```

Hope this helps

**Comment by choeller** [comment]
@brandonroberts cool  - thanks a lot! I can finally run the build and unit - tests again. For everyone interested: If you  only want to execute the unit-tests you can run:

```
./scripts/ci-lite/test_js.sh
```
from main folder.

**Comment by digioak** [comment]
@choeller after running `./scripts/ci-lite/install.sh &&  ./build.sh` I'm seeing this error:

```
====== (all)COMPILING: $(npm bin)/tsc -p ./modules/tsconfig.json =====
/Users/chantosa/workplace/angular
modules/@angular/compiler_cli/src/codegen.ts(26,33): error TS2307: Cannot find module 'ts-metadata-collector'.
modules/@angular/compiler_cli/src/main.ts(13,49): error TS2307: Cannot find module 'ts-metadata-collector'.
modules/@angular/compiler_cli/src/reflector_host.ts(3,49): error TS2307: Cannot find module 'ts-metadata-collector'.
```

Earlier in the build, I saw this:

```
+ npm install -g npm@3.5.3
/Users/chantosa/.nvm/versions/node/v5.11.1/bin/npm -> /Users/chantosa/.nvm/versions/node/v5.11.1/lib/node_modules/npm/bin/npm-cli.js
/Users/chantosa/.nvm/versions/node/v5.11.1/lib
└── npm@3.5.3

+ echo travis_fold:end:install-npm
travis_fold:end:install-npm
+ echo travis_fold:start:install.node_modules
travis_fold:start:install.node_modules
+ node tools/npm/check-node-modules --purge
:-( npm dependencies are stale or in an in unknown state!
    purging...
+ npm install
```

May not be related.

**Comment by madskonradsen** [comment]
Maybe @tbosch knows what the future of the gulp setup will be? It just seems strange not to update the gulp setup to work with the RC changes. I wonder what the core team uses if they don't use the gulp setup...

**Comment by choeller** [comment]
@digioak I think this was fixed with https://github.com/angular/angular/commit/05266241af9973c33cf7ab44a8ca00aeca33ba0d I also saw the stale dependencies before but now it's working for me...

**Comment by hannahhoward** [comment]
Is there some way to get some core team attention on this? @juleskremer, pinging you cause you're head of community relations. it feels weird to at once be told that NG team welcomes contributions from community but to have the build & test instructions in DEVELOPER.md be non-functional for almost a month. I managed to get things going well enough to make some PRs, but it took a lot of sleuthing. Also, while @brandonroberts suggestion gets the build going for me, I then have to remember to reset that file every time before I commit, which is a major pain in the butt.

**Comment by mhevery** [comment]
We are in a midst of redoing the CI etc, so most gulp tasks are broken. We are well aware of this and working hard on fixing it. 

use `./build.sh` and `./test.sh` for now.

I don't think there is a specific action here other than what we are already doing, so I am going to close this PR.

**Comment by hannahhoward** [comment]
fair enough. :)

**Comment by choeller** [comment]
Is  it only me, or aren't  `./build.sh` and `./test.sh` working in current master? `build.sh` returns successfully, but only seems to build the tools folder...

**Comment by choeller** [comment]
So this is the output I get on commandline:

```
====== (all)COMPILING: $(npm bin)/tsc -p ./tools/tsconfig.json =====
====== Copying files needed for e2e tests =====
/home/christoph/sources/angular
====== (all)COMPILING: $(npm bin)/tsc -p ./modules/tsconfig.json =====
======      COMPILING: node dist/tools/@angular/tsc-wrapped/src/main -p ./modules/@angular/core/tsconfig-es5.json        =====
======      TSC 1.8 d.ts compat for ./dist/packages-dist/core   =====
sed: can't read : No such file or directory

```

**Comment by ericmartinezr** [comment]
@choeller I'm glad I'm not the only one with that issue :P 

I've had that issue since the change from b.17 to RC.x and to be honest I have no idea what could it be nor how to solve it.

This is the piece of code that fails for me in `build.sh`

```
  if [[ ${TRAVIS} ]]; then
    find ${DESTDIR} -type f -name '*.d.ts' -print0 | xargs -0 sed -i    -e 's/\(^ *(static |private )*\)*readonly  */\1/g'
    find ${DESTDIR} -type f -name '*.d.ts' -print0 | xargs -0 sed -i    -E 's/^( +)abstract ([[:alnum:]]+\:)/\1\2/g'
  else
    // THIS LINE SPECIFICALLY
    find ${DESTDIR} -type f -name '*.d.ts' -print0 | xargs -0 sed -i '' -e 's/\(^ *(static |private )*\)*readonly  */\1/g'
    find ${DESTDIR} -type f -name '*.d.ts' -print0 | xargs -0 sed -i '' -E 's/^( +)abstract ([[:alnum:]]+\:)/\1\2/g'
  fi
```
If I add `-t` to `xargs` for a verbose log, I get this in the console (a full list of the files where it tries to apply that command)

```
sed -i  -e s/\(^ *(static |private )*\)*readonly  */\1/g ./dist/packages-dist/core/index.d.ts etc...
```
[full log](http://pastebin.com/MbZtmVVn)

if I manually write the command from build.sh to the console with the file above I still get the error you see, and I made sure the file and folders to have all the permissions to write/read them.

```
sed -i '' -e 's/\(^ *(static |private )*\)*readonly  */\1/g' ./dist/packages-dist/core/index.d.ts
sed: can't read : No such file or directory
```
So I'm still wondering what it is, and I have no idea how to debug any of this (kind of hard for a non linux user like me).

**Comment by hannahhoward** [comment]
just curious @ericmartinezr and @choeller did you apply @brandonroberts fix:

```
export NODE_PATH=$NODE_PATH:$(pwd)/dist/all:$(pwd)/dist/tools
```

Nothing works for me if I don't run that before compiling.

**Comment by vicb** [comment]
Have you tried to `npm i` ?

**Comment by brandonroberts** [comment]
@ericmartinezr Have you tried running the command with the slashes in the path switched since your on Windows? It shouldn't matter, but its worth a shot.

```
sed -i '' -e 's/\(^ *(static |private )*\)*readonly  */\1/g' .\dist\packages-dist\core\index.d.ts
```

**Comment by ericmartinezr** [comment]
@hannahhoward yep, actually latest master already has [that line](https://github.com/angular/angular/blob/master/build.sh#L7)

@vicb in my case yes, I did as follow

```
npm i
./scripts/ci-lite/install.sh
./build.sh
```
And I still get that error

@choeller if you find anything please let me know =P

Node 5.10.1
Npm 3.5.3
Ubuntu

**Comment by brandonroberts** [comment]
@ericmartinezr I got this working in a Ubuntu VM. In the second set of that build.sh, I removed the `''` from the `sed -i ''` to match what's in the `${TRAVIS}` section

```
  if [[ ${TRAVIS} ]]; then
    find ${DESTDIR} -type f -name '*.d.ts' -print0 | xargs -0 sed -i    -e 's/\(^ *(static |private )*\)*readonly  */\1/g'
    find ${DESTDIR} -type f -name '*.d.ts' -print0 | xargs -0 sed -i    -E 's/^( +)abstract ([[:alnum:]]+\:)/\1\2/g'
  else
    // THIS LINE SPECIFICALLY
    find ${DESTDIR} -type f -name '*.d.ts' -print0 | xargs -0 sed -i    -e 's/\(^ *(static |private )*\)*readonly  */\1/g'
    find ${DESTDIR} -type f -name '*.d.ts' -print0 | xargs -0 sed -i    -E 's/^( +)abstract ([[:alnum:]]+\:)/\1\2/g'
  fi
```

**Comment by ericmartinezr** [comment]
@brandonroberts Thanks again, this solved the problem, I don't understand how the `''` can cause this problem, but it solved it, Thanks!!!

**Comment by choeller** [comment]
@brandonroberts great! that also did the trick for me! thanks a lot! is this something specific to linux/windows or why are @ericmartinezr and me the only ones having the problem?

**Comment by brandonroberts** [comment]
@choeller @ericmartinezr I'm not sure why the `-i` flag for `sed` is being treated differently on Linux/Windows. The `-i` flag with no extension or an empty `''` just tells `sed` to do the replacement inline instead of outputting to a separate file.
