### ISSUE TITLE
angular 1 $interpolate alternative?

### ISSUE THREAD

**Issue by Delagen** [angular/angular#8638]
Found project https://github.com/PawelGerr/angular2-interpolation

But no way to use with bundles due no way to import dependencies.

```
import {Parser} from 'angular2/src/core/change_detection/parser/parser';
import {Interpolation, PropertyRead, ImplicitReceiver} from 'angular2/src/core/change_detection/parser/ast';
```

**Comment by michalstepien** [comment]
Yep, this project use beta 9, so I think you have to rewrite . I dont know if Rc1 have getter in PropertyRead.

**Comment by Delagen** [comment]
I think this functionality is needed for services like angular-translate for 1 version. Because angular does not provide it

**Comment by pkozlowski-opensource** [comment]
There is no direct equivalent of the `$interpolate` service from Angular 1 and there are no particular plans to add one. The expression parser work differently in ng2 and there is no need for `$interpolate` for Angular 2. If anyone needs similar functionality it would have to be done outside of the core.
