### ISSUE TITLE
'FakeAppRootCmp' does not have route configuration'

### ISSUE THREAD

**Issue by williamhallatt** [angular/angular#8640]
Completed an upgrade from Beta to RC1.  Running unit tests with Karma and Jasmine and, although they still pass, I am receiving a weird error that is injected into the console output.  There is no consistency as to where it gets injected into the stream, so I am reasonably certain that this is not related to my tests.  It does, however, happen with every single test run.  The output received follows:

`ERROR: 'Unhandled Promise rejection:', 'Component 'FakeAppRootCmp' does not have route configuration', '; Zone:', '<root>', '; Task:', 'Promise.then', '; Value:', BaseException{message: 'Component 'FakeAppRootCmp' does not have route configuration', stack: undefined, line: 19}                                       
ERROR: Error{line: 538, sourceURL: 'http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277', stack: 'resolvePromise@http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:538:76                                             
resolvePromise@http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:523:32                                   
http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:571:32                                                  
invokeTask@http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:356:43                                       
runTask@http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:256:58                                          
drainMicroTaskQueue@http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:474:43                              
F@http://localhost:9876/base/node_modules/systemjs/dist/system-polyfills.js?a9f0c97e865a53da4c067b98cf2e65a23b2f0608:4:12217                                  
H@http://localhost:9876/base/node_modules/systemjs/dist/system-polyfills.js?a9f0c97e865a53da4c067b98cf2e65a23b2f0608:4:11846                                  
when@http://localhost:9876/base/node_modules/systemjs/dist/system-polyfills.js?a9f0c97e865a53da4c067b98cf2e65a23b2f0608:4:15520                               
run@http://localhost:9876/base/node_modules/systemjs/dist/system-polyfills.js?a9f0c97e865a53da4c067b98cf2e65a23b2f0608:4:16632                                
_drain@http://localhost:9876/base/node_modules/systemjs/dist/system-polyfills.js?a9f0c97e865a53da4c067b98cf2e65a23b2f0608:4:3250                              
drain@http://localhost:9876/base/node_modules/systemjs/dist/system-polyfills.js?a9f0c97e865a53da4c067b98cf2e65a23b2f0608:4:1667', rejection: BaseException{message: 'Component 'FakeAppRootCmp' does not have route configuration', stack: undefined, line: 19}, promise: ZoneAwarePromise{__zone_symbol__state: 0, __zone_symbol__value: BaseException{message: ..., stack: ..., line: ...}}, zone: Zone{_properties: Object{}, _parent: null, _name: '<root>', _zoneDelegate: ZoneDelegate{_taskCounts: ..., zone: ..., _parentDelegate: ..., _forkZS: ..., _forkDlgt: ..., _interceptZS: ..., _interceptDlgt: ..., _invokeZS: ..., _invokeDlgt: ..., 
_handleErrorZS: ..., _handleErrorDlgt: ..., _scheduleTaskZS: ..., _scheduleTaskDlgt: ..., _invokeTaskZS: ..., _invokeTaskDlgt: ..., _cancelTaskZS: ..., _cancelTaskDlgt: ..., _hasTaskZS: ..., _hasTaskDlgt: ...}}, task: ZoneTask{runCount: 1, type: 'microTask', zone: Zone{_properties: ..., _parent: ..., _name: ..., _zoneDelegate: ...}, source: 'Promise.then', data: undefined, scheduleFn: undefined, cancelFn: null, callback: function () { ... }, invoke: function () { ... }}
}`

**Comment by zoechi** [comment]
Any concrete example that causes this error?

**Comment by williamhallatt** [comment]
Unfortunately I do not have a minimal working example.  That is literally all I have.  I am not expecting an investigation based on this little bit of information, was more hoping that someone had seen this before.  Am actively trying to get more useful information together at the moment, but been at it for most of the day already, hence reaching out.

**Comment by antonmoiseev** [comment]
How do you configure `beforeEachProviders()`? Do you use `ROUTER_FAKE_PROVIDERS` or explicitly register all required dependencies as [here](https://github.com/angular/angular/blob/b30ddfbfc5192f526ceaac525cf6965635831c46/modules/%40angular/router/test/integration_spec.ts#L38-L49)?

**Comment by williamhallatt** [comment]
I use ROUTER_FAKE_PROVIDERS like so:

`import {HTTP_PROVIDERS, URLSearchParams, RequestMethod} from '@angular/http';
import {describe, expect, it, inject, beforeEachProviders, beforeEach} from '@angular/core/testing';
import {ROUTER_FAKE_PROVIDERS} from '@angular/router/testing';

import {MyService} from './employee.service';

export function main() {
  describe('MyService', () => {
    let _myService: MyService;

    beforeEachProviders(() => [MyService,      
      HTTP_PROVIDERS,
      ROUTER_FAKE_PROVIDERS]);

    beforeEach(inject([MyService], (myService) => {
      _myService = myService;
    }));

    // test test test test test
  });
};`

**Comment by antonmoiseev** [comment]
Here is a minimal configuration extracted from the router integration test that works for us - [app.spec.ts](https://github.com/Farata/angular2typescript/blob/5bb79d8ad59111b2528375f101160842cb28a5ae/chapter10/angular2-webpack-starter/src/app/app.spec.ts#L24-L44).

My understanding is that there is no connection between the `Router` instance and your application component that has `@Routes()` configuration when you use `ROUTER_FAKE_PROVIDERS`. To create that connection we have to fallback to the explicit configuration. Take a look at lines [32](https://github.com/Farata/angular2typescript/blob/5bb79d8ad59111b2528375f101160842cb28a5ae/chapter10/angular2-webpack-starter/src/app/app.spec.ts#L32) and [39](https://github.com/Farata/angular2typescript/blob/5bb79d8ad59111b2528375f101160842cb28a5ae/chapter10/angular2-webpack-starter/src/app/app.spec.ts#L39), this is where we connect component to the router instance.

Ideally I would like the `FakeAppRootCmp` component to be an injectable entity, so we can leverage compact configuration of `ROUTER_FAKE_PROVIDERS` but inject our custom component instead of the default one.

**Comment by williamhallatt** [comment]
@antonmoiseev Thank you for such detailed help, seeing the working examples helped me identify where the error was coming from.

Regarding the issue itself, I managed to find a solution after finally identifying the set of tests that caused the exception to be raised.  The problem was that there was still functionality (after the RC1 upgrade) that called 'navigate' on a router instance, but with the old route name (e.g. `this._router.navigate(['Home']);`  Changing that to the actual route path did the trick (`this._router.navigate(['/home']);`).
