### ISSUE TITLE
[BUG] Zones don't run on SpeechRecognition Events

### ISSUE THREAD

**Issue by amcdnl** [angular/angular#8642]
**Description**
When a `SpeechRecognition` event runs, you have to manually invoke `ngZone.run()` in order for changes to be applied. Events such as:
- `onspeechstart`
- `onspeechend `
- `onstart `

and so on do not trigger this. I assume this is a result of that event not being monkey patched.

**Reproduction**
You can reproduce it with @manekinekko project: https://github.com/manekinekko/angular2-speech-engine . 

You can see where he has to manually invoke the run here: https://github.com/manekinekko/angular2-speech-engine/blob/master/src/engine/abstract-speech-engine.ts#L91

**Comment by zoechi** [comment]
I guess this should be reported in https://github.com/angular/zone.js/issues

**Comment by manekinekko** [comment]
@amcdnl I guess this is a normal behaviour of zones.js. I don't think it's meant to patch all possible async events.
@mhevery Am I wrong?

**Comment by campersau** [comment]
Zone.js patches the [`EventTarget`](https://github.com/angular/zone.js/blob/master/lib/browser/event-target.ts#L5) and since `SpeechRecognition` inherits from it, the methods should also be patched, or at least the `addEventListener` method.

So you could try to use `addEventListener` instead and see if it works.

**Comment by amcdnl** [comment]
@zoechi - Ok, I wasn't 100% sure if it should be here or there. Should I move this?
@manekinekko - Thats fine, we just need to make sure and document this then. It took me a bit to track it down.

**Comment by mhevery** [comment]
@amcdnl please move to https://github.com/angular/zone.js, Even better would be to create a PR.
