### ISSUE TITLE
Variable pattern validation

### ISSUE THREAD

**Issue by Chronophobe** [angular/angular#8643]
**Steps to reproduce and a minimal demo of the problem**
See [Plunker](http://plnkr.co/edit/A2OOUUzTUtic9Bgi5hHt) for a basic form. 

1. Create a dictionary with regex patterns (empty and/or non-empty strings)
2. Use this to create a set of inputs validated using the pattern-validator
3. (optional) use a ternary operator to use a default expression if the pattern is empty

**Current behavior**
Using "variable" patterns the pattern validation fails while it should pass.  
Plain strings in html work, albeit that an empty string seems to invalidate any non-empty input. Whether this is wanted behaviour is debatable.

**Expected/desired behavior**
The interpolated patterns should work equal to their plain string counterparts. In the above example, the first validation pattern should allow at least one word-character and the second at least one digit.

**Comment by zoechi** [comment]
dup of #7393

**Comment by meeroslav** [comment]
@Chronophobe: Not sure if it's still relevant, but problem is PatternValidator gets created before interpolation of "pattern" attribute happens.

This works:
`<input [attr.pattern]="somePattern" ... />`

Although I would expect this to work just as same:
`<input [pattern]="somePattern" ... />`

**Comment by kara** [comment]
This should have been fixed by https://github.com/angular/angular/pull/11116.
