### ISSUE TITLE
Bootstrapping with offline compiler using upgrade adapter

### ISSUE THREAD

**Issue by damrbaby** [angular/angular#8648]
Currently there are some examples (using the cli and [here](https://github.com/robwormald/ng2-compiler-test2)) that show how to bootstrap an angular app using compiled templates, making the payload size much smaller.  Is there a way to do this with the upgrade adapter?  For us, that's important, because we don't want to incur too much extra weight in our already largish angular 1 app that targets mobile devices.

**Comment by petebacondarwin** [comment]
You must use the newer `upgrade/static` library. See https://angular.io/docs/js/latest/api/upgrade/static/UpgradeModule-class.html
