### ISSUE TITLE
EventEmitter to array, changes not detected in RC1

### ISSUE THREAD

**Issue by shaunmccann-87** [angular/angular#8650]
Updated to RC1 and noticing changes which occur from an event emitter arent now trigger any change detection.

This was working right up to RC1.

Trigger an update from lets say a button within the page will however show all event emitter additions pushed to the array.

**Comment by zoechi** [comment]
Can you please provide a Plunker that demonstrates the issue?

**Comment by shaunmccann-87** [comment]
It's hard to provider a plunker as I first noticed this using signalr.  I will try this within a single page but not a true test.

**Comment by zoechi** [comment]
Than it's probably a zone issue with signalr. Try injecting `NgZone` and run the code that emits the event (or updates the array - don't know because you provided no code) in `this.zone.run(() => ...)`

**Comment by shaunmccann-87** [comment]
Thanks. That's worked well. I guess this makes sense but I am not sure I should have to tell the UI to update when an observable object is updated.

**Comment by zoechi** [comment]
You normally don't have to. When part of your code runs outside Angulars zone then you're out of luck. Angular runs change detection when it detects that an "event" has happened. It recognizes this only for code that runs inside Angulars zone and the event was emitted by an async APIs that is patched by Angulars zone. Angular just doesn't update the view when it doesn't know that it should.

**Comment by shaunmccann-87** [comment]
Thanks for the explanation, sounds straight forward enough. Happy to close the issue as it appears to be by design and is work-around-able.

**Comment by Ashar99** [comment]
zoechi.... what is the "inject ngZone" solution to this ?   I'm having the same issue with RC1 not receiving an emitted event in the parent component.  Just import ngzone in the parent with the () listener?, in the child that's emitting the event ?

**Comment by Ashar99** [comment]
Just saw this post which solved my problem.... http://stackoverflow.com/questions/37192619/angular-2-update-app-component-from-router-outlet-component
