### ISSUE TITLE
HTTP. Response object could be caught by catch hook. Some omissions in angular2 http tutorials

### ISSUE THREAD

**Issue by MikeYermolayev** [angular/angular#8652]
Hello!

I'm looking through the angular2 http tutorial (https://angular.io/docs/ts/latest/guide/server-communication.html) and there is something interesting. We get our heroes with help of http request below
```
return this.http.post(this.heroesUrl, body, options)
                    .map(this.extractData)
                    .catch(this.handleError);
```
and method extractData looks like this
```
private extractData(res: Response) {
  if (res.status < 200 || res.status >= 300) {
    throw new Error('Bad response status: ' + res.status);
  }
  let body = res.json();
  return body.data || { };
}
```

But as far as I can see angular2's xhr_backend.js raises error when res.status isn't OK. So it means that extractData would never be called when there would be bad status because this error would lead to `catch` hook execution. 

Is it expected behaviour? Does it mean that this error-throwing in extractData method makes no sense?

Here you could look at my callstack http://screencast.com/t/smXJYVYbW

This leads to small problem. Response object could be caught by `catch` hook instead of Error object

**Comment by zoechi** [comment]
See angular/http#52

400 would be treated as valid response and wouldn't throw but the application still needs to handle it.

**Comment by akozhemiakin** [comment]
Related stuff: https://github.com/angular/angular.io/pull/1265
