### ISSUE TITLE
Cannot find module 'angular2-meteor-accounts-ui'

### ISSUE THREAD

**Issue by arshadattari** [angular/angular#8653]
Uncaught Error: Cannot find module 'angular2-meteor-accounts-ui' in Angular2 Beta.17 :
My code: 
import {Page, NavController, } from 'ionic-angular';
import {Component, NgZone} from 'angular2/angular2';
import {FORM_DIRECTIVES, FormBuilder,  ControlGroup, AbstractControl,Control} from 'angular2/common';
import {Signup} from '../signup/signup';
import {Profile} from '../profile/profile';
import {Mongo} from 'meteor/mongo';
import {Accounts} from 'meteor/accounts-base';
import {RequireUser, InjectUser} from 'angular2-meteor-accounts-ui';
import {CORE_DIRECTIVES} from 'angular2/common';
import {ROUTER_PROVIDERS, ROUTER_DIRECTIVES, RouteConfig, APP_BASE_HREF, RouterLink, RouterOutlet, Router} from 'angular2/router';
import {LocationStrategy, HashLocationStrategy} from 'angular2/platform/common';
import {ReactiveVar} from 'meteor/reactive-var';
import {Counts} from 'meteor/tmeasday:publish-counts';
import {Cards} from '../../../collections/cards/cards';
import {CardsCategory} from '../../../collections/cardscategory/cardscategory';
import {MeteorComponent} from 'angular2-meteor';

@Page({
    templateUrl: "client/pages/cards/cards.html",
    directives: [
        FORM_DIRECTIVES,
        RouterLink,
        CORE_DIRECTIVES,
        RouterOutlet
    ]
})

@RequireUser()
@InjectUser()

export class Cards {
    categories: Mongo.Cursor<Object>;
    user: Meteor.User;

    constructor(
        private router: Router,
        private nav: NavController){
        super();

        this.subscribe('cardscategory', {
            onReady: () => {
                this.categories = CardsCategory.find({}).fetch();
                console.log("CardsCategory.....", this.categories);
            }
        }, true);
    }
}

**Comment by pkozlowski-opensource** [comment]
This sounds like a support question for module loading / 3rd party library and as such should be asked using an appropriate support forum, see: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
