### ISSUE TITLE
RC.1: @angular/http: Return comma-separated header values as distinct items

### ISSUE THREAD

**Issue by about-code** [angular/angular#8654]
Given the following client-code:

```typescript
import {Inject} from "@angular/core";
import {Http} from "@angular/http";
export class Test {
    constructor(@Inject(Http) http) {
        http.get("http://foo.bar").subscribe((response) => {
             console.log(response.headers.getAll("Link"));
        });
    }
}
```
The server http://foo.bar/ responds with an HTTP message with multiple `Link` headers. But instead of
```
Content-Type: application/json
Link: <http://foo.bar/related/1>; rel="related"
Link: <http://foo.bar/related/2>; rel="related"
```
the response header looks like
```
Content-Type: application/json
Link: <http://foo.bar/related/1>; rel="related" , <http://foo.bar/related/2>; rel="related"
```
which is valid [HTTP 1.1](https://www.ietf.org/rfc/rfc2616.txt) according to Section 4.2 of  the RFC

> Multiple message-header fields with the same field-name MAY be
   present in a message if and only if the entire field-value for that
   header field is defined as a comma-separated list [i.e., #(values)].
   It MUST be possible to combine the multiple header fields into one
   "field-name: field-value" pair, without changing the semantics of the
   message, by appending each subsequent field-value to the first, each
   separated by a comma.

From the signature and API-Doc of [Headers.getAll()](https://github.com/angular/angular/blob/master/modules/%40angular/http/src/headers.ts) I'd expect `response.headers.getAll("Link")` to return an array with two items, for the comma-separated case e.g.:
```
[
 '<http://foo.bar/related/1>; rel="related"',
 '<http://foo.bar/related/2>; rel="related"'
]
```
but it returns an array with only one item
```
[
  '<http://foo.bar/related/1>; rel="related" , <http://foo.bar/related/2>; rel="related"'
]
```
So [Headers.getAll()](https://github.com/angular/angular/blob/master/modules/%40angular/http/src/headers.ts) may split comma-separated header values and return them as distinct items.

**Comment by vicb** [comment]
is this still an issue with 2.0.1 ?
