### ISSUE TITLE
What to use in place of @CanActivate in the R.C?

### ISSUE THREAD

**Issue by cristianrgreco** [angular/angular#8655]
Now that @CanActivate has been removed from the release candidate there is no way to prevent navigation to a route, such as restricting access to a view based on a condition. 

How is such functionality achieved in the current release candidate without using the deprecated router?

**Comment by CaptainCodeman** [comment]
Labeling an unfinished router as "Release Candidate" is incredibly misleading.

**Comment by kylecordes** [comment]
Although I realize it may be unhelpful to substitute one thing in progress for another, I recommend taking a look over at this alternate router implementation, to get a feel for some of directions things can go, while waiting for an upcoming later release candidate that makes the "new new router" complete.

https://github.com/ngrx/router

**Comment by zoechi** [comment]
There currently is no replacement yet but something will be added again from what I remember being mentioned.

**Comment by mburger81** [comment]
Waiting for it too
:+1:

**Comment by zoechi** [comment]
I have seen a PR containing the missing router lifecycle callbacks being merged already recently.

**Comment by kushwahashiv** [comment]
When it would be available

**Comment by CrisGrec** [comment]
Bump

**Comment by netdesk** [comment]
Any news on this? Any alternatives other than switching to another router?

**Comment by pkozlowski-opensource** [comment]
The only alternative is a new router, just released. See http://angularjs.blogspot.fr/2016/06/improvements-coming-for-routing-in.html

**Comment by kylecordes** [comment]
To put a little more positive spin than "only alternative"... the "new new new router" is a great improvement.  There is little reason to spend anymore time with any of the old routers.

**Comment by mburger81** [comment]
okay, but are there some documentation on how to implement @CanActivate or some authorization mechanism for the new router?

**Comment by ericmartinezr** [comment]
@mburger81 the documentation is being updated (see https://github.com/angular/angular.io/pull/1636). The new new new router has a `canActivate` property that achieves the same behavior (see https://github.com/angular/vladivostok/blob/master/test/router.spec.ts#L507).
