### ISSUE TITLE
form method="post" action="/blahblah" does not work in any component

### ISSUE THREAD

**Issue by alanpurple** [angular/angular#8657]
simple 

`<form name="testForm" method="post" action="/account/login">
    <input name="abc" type="email" />
    <input name="bbb" type="password" />
    <button type="submit">submit</button>
</form>`
doesn't fire post call in any angular2 component with rc.1

it works fine in body element

**Comment by zoechi** [comment]
Just add the `ngNoForm` attribute. 

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)
