### ISSUE TITLE
Folder and File access using FileSystem API

### ISSUE THREAD

**Issue by aprinaresh97** [angular/angular#8659]
For an application create a sandbox folder to access and create files and sub-folders. The configuration of the folder should happen as part of the bootstrapping the application. For the content or document management application this feature will greatly help. 

The Angular should incorporate this sandbox concept to allow the FileSystem APIs to work in the sandbox area.

**Comment by zoechi** [comment]
Why does this need to be part of Angular?

**Comment by aprinaresh97** [comment]
Angular is a framework and it would be nice if Angular could abstract the usage of FileSystem API with sandbox concept to support widely used document/content management application. Most of the available solution use Java Applet to accomplish the FileSystem functionality. With browser developers planning not to support Java Applet in their browsers, it would be good if Angular can fill up this gap quickly and attract those kind of applications to port to Angular 2.

**Comment by mhevery** [comment]
Outside the scope of Angular2
