### ISSUE TITLE
dash case to camel case conversion on all HTML attributes

### ISSUE THREAD

**Issue by mhevery** [angular/angular#866]
All HTML attributes are lowercased per HTML spec. This means that we have to convert dash case to camel case. `a-b` => `aB`

See: 
https://github.com/angular/angular/blob/94e203b9df6c4b79ba30f1f08fc54ff919f722e1/modules/angular2/src/core/compiler/pipeline/property_binding_parser.js

https://github.com/angular/angular/blob/master/modules/angular2/src/core/compiler/pipeline/element_binder_builder.js

**Comment by mhevery** [comment]
@pkozlowski-opensource can we prioritize this so that we can close this milestone? Thanks in advance.

**Comment by pkozlowski-opensource** [comment]
@mhevery sure, will submit a PR tomorrow.

**Comment by pkozlowski-opensource** [comment]
@mhevery @rkirov I'm on it at the moment but while changing the compiler I was wondering if we want to see dash-cased or cammelCased property names through the compiler pipeline. In other words, I can either normalise property name either in:
* `PropertyBindingParser` step but this is pretty early on, so next steps need to be aware of this mapping (ex.: `DirectiveParser` / selector matching)
* `ElementBinderBuilder` - this would be a small and simple change but if we want to have additional mappings in the future (ex.: stripping `data-` prefixes like in ng1) we might want to have normalized property names inside a compiler.

Any thoughts on what we should be dealing with in the compiler pipeline? Original property names vs. normalized names?

**Comment by ladyborg** [comment]
Well, it sounds nice to be able to safely assume that you're always working
with camelCase, not having to check for dash-case or camelCase anywhere by
normalizing asap. But it doesn't really make sense to convert from
dash-case -> camelCase and then back to dash-case later on for certain use
cases. I think the best approach is to leave property names dash-case for
as long as they are still needed in selectors/matching/etc... and then
normalize to camelCase.

**Comment by mhevery** [comment]
I think we should convert to camel case as soon as we read it. So it sounds like `PropertyBindingParser`. We should just assume that everything is camelCase.

We should than apply the same transform when reading the `bind` from the `Directive` annotation.

**Comment by pkozlowski-opensource** [comment]
@mhevery so, after spending some time knee-deep in the compiler code, we need to discuss the `CssSelector` design where all the [rules are lower-cased](https://github.com/angular/angular/blob/1d4ff9bcdcb6dd4e033a4404261b15b13a32c44f/modules/angular2/test/core/compiler/selector_spec.js#L35-L48).

Now, this becomes problematic if we want to camel-case property / attribute names early on in the `PropertyBindingParser`. If we do so the `DirectiveParser` only has access to camel-cased version and this is the only thing that we can give to a CSSSelector.

Let's take this example: `<input read-only="foo">`, here is what all the steps would do:
* `PropertyBindingParser`: `read-only` => `readOnly`
* `DirectiveParser` (`CSSSelector`): readOnly` => `readonly`

So all of the sudden directives or directive bindings might start matching `read-only` attribute while the intention was to match `readonly`.

I can see 3 ways of moving forward:
* make `CSSSelector` case-sensitive
* convert back and forth between camel and dash case (ugly...)
* stick to the initial proposal from #911

Personally I think that (1) and (3) are the most reasonable.

***Question***: does `CSSSelector` needs to be case-insensitive?
