### ISSUE TITLE
Timeline for testing documentation

### ISSUE THREAD

**Issue by abierbaum** [angular/angular#8662]
As Angular is targetted for solid testing and in general a test first methodology, our team has tried to stay focused on testing all Angular code.  Unfortunately it has been very painful because there is no solid documentation about how to test Angular 2 applications and components.  There is some documentation about how to setup jasmine, etc and that has proven very useful. [1] 

I don't want to sound like I am complaining though.  Angular 2 is great and up to this point it has been in alpha and beta releases with much of the code changing rapidly.  We have tried to make do by patching together community blog posts about testing and trying to read through the test helpers to decipher how to use them. 

Now that RC versions are out I am wondering what the timeline is for more complete documentation of how to test Angular 2 applications?

I know it would help our team tremendously and I expect it would help others if the "forthcoming" sections of the test docs [1] could be fleshed out sooner rather than later.  I know there are many other things pending as well, but I think this one would be very well received by Angular 2 developers.

1: https://angular.io/docs/ts/latest/guide/testing.html

**Comment by zoechi** [comment]
Google generally doesn't provide timelines or estimates. Documentations issues are maintained in the https://github.com/angular/angular.io repo
