### ISSUE TITLE
DomSanitizationService inserts double-quotes inside style statements needing single quotes

### ISSUE THREAD

**Issue by Ashar99** [angular/angular#8664]
For certain styles that require single quotes inside of the double-quoted style statement, the DomSanitizationService is inserting double-quotes, thereby prematurely ending the style string in the browser, making it break.

**Steps to reproduce and a minimal demo of the problem**

Here is a style string that needs to be used for [style.background-image]="cleanImageUrl"

cleanImageUrl = <any>sanitizer.bypassSecurityTrustStyle('url(/pImages/' +  this.recipientId + '.jpg)');

Which results in the following being sent to the browser :

style="background-image: url("/pImages/57211a89b65ff1be3edd14c9.jpg");"

Notice the double quotes after url(  , this breaks the style=""  string prematurely and the
image is not being pulled.

I've also tried manually inserting the single quotes:

cleanImageUrl = <any>sanitizer.bypassSecurityTrustStyle("url(\'/pImages/" +  this.recipientId + ".jpg\')");

But that gives the same result... it replaces my single quotes with double quotes inside the resulting string

Regarding the <any> cast :
The sanitizer doesn't return a string and <any> was used because it was recommended to be better than <string>, but <any>, <string> and not casting it at all have been tried

_What steps should we try in your demo to see the problem?_

Try the DomSanitizationService on any style statement that requires single quotes inside of the style statement,  i.e.   style="background-image: url('/path/image1.jpg');"    Even though this will also work without the single quotes at all, the DomSanitizationService inserts double quotes anyway, or replaces your single-quotes with double-quotes.

**Expected/desired behavior**

1) Stop inserting double quotes where they aren't needed,  url(/path/image.jpg) works fine, or
2)  Stop replacing the single quotes put into the url with double-quotes,  url('/path/image.jpg'), or
3)  Don't insert or replace double quotes, and let the developer put in single quotes if needed, and if so, ignore them

**Comment by zoechi** [comment]
Cross-ref http://stackoverflow.com/questions/37238757/angular2-rc1-sanitizer-inserts-double-quotes-inside-styles-breaking-it

Plunker http://plnkr.co/edit/yodLhTSsHYjOojRK3Gpl?p=preview

**Comment by Ashar99** [comment]
zoechi's Pipe method works fine

**Comment by tbosch** [comment]
@mprobst FYI...

**Comment by mprobst** [comment]
I'm not sure we have gotten entirely to the bottom of this. There's no code in the Sanitizer that would add quotes inside of a `url(...)` value like that. In addition, Angular should not send a value as `style="..."` to the browser. Angular just calls `setStyle` on the DOM element directly, so values never get serialized, so quotes (`"` vs `'` vs `&quot;` etc) should never come into question in the first place.

@Ashar99 where do you observe the quotes being added? If it's just in the Chrome inspector tools for CSS properties, the quote issue might not be your problem at all. Do you have a working demo showing how incorrect quotes get added?

@zoechi's example (thanks by the way!) shows in the `backgroundImageStyle` case (third `<div>`) that `bypassSecurityTrustStyle` seems to work fine. I also see Chrome displaying it in the DOM as `style="background-image: url("https://unsplash.it/500/500");"`, but I'm pretty sure that's just an artefact of Chrome developer tools, the value comes out correctly.

**Comment by Ashar99** [comment]
Yeah, I was seeing the double quotes inside both the Chrome developer tool as well as the IE developer tool, and the image wasn't displaying on either.   The Pipe workaround also displays the double quotes in both tools, but the image displays fine.

**Comment by mprobst** [comment]
@Ashar99 I'm pretty confident that was just Chrome Dev Tools being misleading then, and the actual problem was somewhere else (e.g. URI wrong or so).

I'm closing this issue, but please feel free to reopen in case you find a repro or strongly disagree :-)
