### ISSUE TITLE
Router "invalid number of '../'

### ISSUE THREAD

**Issue by aquinum6** [angular/angular#8666]
Seems like a bug,
Routes config:

/auth
    + /
    + /signup
    + /confirmation
**app.ts**
```
@Routes([
    { path: '/auth',  component: loginCmp }
])
```
**login-cmp.ts**
```
@Routes([
    { path: '/', component: signInCmp }
    ,{ path: '/signup', component: signUpCmp }
    ,{ path: '/confirmation', component: confirmationCmp }
])
```
I have found similar problem on stackoverflow: http://stackoverflow.com/questions/37199272/angular-2-new-rc1-router-nested-routes

Error appears when I'm trying to get from /signup to /confirmation with _router.navigate_
```
$_router.navigate(['/confirmation']);
$_router.navigate(['./confirmation']);
$_router.navigate(['../confirmation']);
```
all above produce this error

To check if my routing setup is right I have used _routerLink_ to navigate to /confirmation and it works
`<a [routerLink]="['../confirmation']">Confirm</a>`
Also absolute path works fine
`$_router.navigate(['/auth/confirmation']);`

**Comment by zoechi** [comment]
For relative navigation you need to pass the segment as 2nd parameter to `_router.navigate(...)` to which the path should be relative to.
