### ISSUE TITLE
New Router: "TypeError: Cannot read property 'map' of null

### ISSUE THREAD

**Issue by aquinum6** [angular/angular#8667]
```
TypeError: Cannot read property 'map' of null at UrlTree.Tree.pathFromRoot (http://localhost:3000/node_modules/@angular/router/src/segments.js:30:85) at _findUrlSegment (http://localhost:3000/node_modules/@angular/router/src/link.js:79:24) at _findStartingNode (http://localhost:3000/node_modules/@angular/router/src/link.js:90:26) at Object.link (http://localhost:3000/node_modules/@angular/router/src/link.js:14:24) at Router.createUrlTree (http://localhost:3000/node_modules/@angular/router/src/router.js:133:23) at RouterLink._updateTargetUrlAndHref (http://localhost:3000/node_modules/@angular/router/src/directives/router_link.js:42:33) at RouterLink.Object.defineProperty.set [as routerLink] (http://localhost:3000/node_modules/@angular/router/src/directives/router_link.js:28:18) at DebugAppView._View_signUpCmp0.detectChangesInternal (signUpCmp.template.js:517:37) at DebugAppView.AppView.detectChanges (http://localhost:3000/node_modules/@angular/core/src/linker/view.js:200:14) at DebugAppView.detectChanges (http://localhost:3000/node_modules/@angular/core/src/linker/view.js:289:44)
```
1. I have setup my node to send index.html of app to any request that have 'manager' in address.
2. app.ts router setup
```
@Routes([
    { path: '/auth',  component: loginCmp }
    //,{ path: '/licence', component: licenceCmp }
    //,{ path: '/app/...', component: appCmp }
    //,{ path: '*', component: loginCmp }
])
```
3. child router setup
```
@Routes([
    { path: '/', component: signInCmp }
    ,{ path: '/signup', component: signUpCmp }
    ,{ path: '/confirmation', component: confirmationCmp }
])
```

Everything was working fine until I have added to app.ts this code
```
ngOnInit(){
        this.$_router.navigate(['/auth'])
    }
```
I wanted to make sure if someone open app with just **localhost:3000/manager** will be redirected to **/manager/auth**

And then I'm getting error only in one situation
When I navigate to **/manager/auth/signup**, and refresh website, browser displays **/manager/auth** and I'm getting error that I had copied into the first line

**Comment by MrCroft** [comment]
Yup... Same here.
I have the following in my app.component.ts :
```javascript
@Routes([
    { path: '/dashboard', component: DashboardComponent },
    { path: '/login', component: LoginComponent },
    { path: '/unprotected', component: UnprotectedComponent }
])
```
Then, in my dashboard.component.ts
```javascript
@Routes([
    { path: '/', component: DashboardHomeComponent },
    { path: '/another-route', component: AnotherComponent }
])
```
also in dashboard.component.ts I implement routerOnActivate where I do the redirect to login:
```javascript
export class DashboardComponent implements OnInit, OnActivate {
    constructor(private myRouter: Router) { }
    routerOnActivate(segment: RouteSegment): void {
        this.myRouter.navigateByUrl('/login');
        console.log('NO NO !!!');
    }

    ngOnInit() {}

}
```
But here's the weird scenario:
If I load my app by simply accessing `localhost` or `localhost/unprotected`  and then click on the dashboard link, I get the error (and also I get redirected to the login), but the unprotected link also keeps the class "router-link-active".
If I load my app by directly accessing `localhost/dashboard`... again, I get the error but I also get redirected to the download link.
In any of the above 2 cases, if after the app loads I click on (navigate to) the login link, then I can navigate to whatever route I want and be redirected without error.
Or if I simply load my app by directly accessing `localhost/login` and then click on the dashboard link, I get no error (and I get redirected back to /login).

I'm sorry, I wanted to make a plunker for this, but I'm just not able to do it... tried for half an hour, no luck. I just couldn't manage to make a plunker work.

**Comment by ericmartinezr** [comment]
In this issue the same error is reproduced and there seems to be a workaround (I think so) https://github.com/angular/angular/issues/8567

**Comment by IgorMinar** [comment]
now that there is router v3 is now obsolete
