### ISSUE TITLE
Angular2 alternative of $http

### ISSUE THREAD

**Issue by RohitLuthra19** [angular/angular#8670]
var data = {
        				TimeStamp : "2016-04-25 12:50:00"
        		};
        		$http({
        		    method: 'POST',
        		    url: 'http:localhost:8080/serverutilizationreport',
        		    headers: {'Content-Type': 'application/x-www-form-urlencoded'},
        		    data: $httpParamSerializerJQLike(data),
        		})
                .success(function(data) {

                }

**I want to make this kind of call in Angular2 - Release candidate "2.0.0-rc.1" . Can Anybody help me...Previously i was working on Angular 1 but now i moved to Angular2 - Release candidate "2.0.0-rc.1"**

**Comment by Green-Cat** [comment]
There is @angular/http which works rather similarly.

**Comment by RohitLuthra19** [comment]
@Green-Cat  Can you help me with an example..

**Comment by olakara** [comment]
@RohitLuthra19 Refer to the docs: [https://angular.io/docs/ts/latest/guide/server-communication.html#!#http-client](https://angular.io/docs/ts/latest/guide/server-communication.html#!#http-client) We can see working examples in this page.. hope this helps

**Comment by RohitLuthra19** [comment]
Thanks @Green-Cat

**Comment by RohitLuthra19** [comment]
**I have found two methods :** 

First Method for Same origin :
				var body = "TimeStamp=" + "2016-04-12 12:50:00" ;
				//let headers = new Headers({ 'Content-Type': 'application/x-www-form-urlencoded' });
				var headers = new Headers();
				headers.append('Content-Type', 'application/x-www-form-urlencoded');
				headers.append('Access-Control-Allow-Origin','http://localhost:8080');
				let options = new RequestOptions({ headers: headers });
				http.post('http://localhost:8080/serverUtilizationReport',body, options)
				//.map(response => response.json())
				.map((res: Response) => res.json())
				.subscribe((records: Array<Object>) => this.records = records);


Second Method for Cross origin :
				var params = new URLSearchParams();
				params.set('TimeStamp', '2016-04-12 12:50:00');
				params.set('callback', 'JSONP_CALLBACK');
				jsonp.get('http://localhost:8080/serverUtilizationReport', { search: params })
				.map(res => res.json());

**Is this a right approch...????????**

**Comment by otabekgb** [comment]
stackoverflow is the right place to search/ask this kind of questions

**Comment by RohitLuthra19** [comment]
@otabekgb Actually i dont have a enough reputation (points) to ask question on stakoverflow..

**Comment by TheNando** [comment]
Have you considered trying the native Fetch API? It has pretty decent support if you are using a modern browser. Since there is no more digest cycle, you don't necessarily need to rely on an Angular specific library or module to get features like these anymore. I hope this helps.

https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API

**Comment by mhevery** [comment]
Sorry, this is reserved for issues, please check out https://angular.io/resources/ for ideas on how you can get your questions answered with the community.

**Comment by Kriztianbran** [comment]
Hi i solve this problem whit URLSearchParams. 
let headers = new Headers({
	     'Content-Type': 'application/x-www-form-urlencoded',
         'Accept': '*/*'});
	  let options = new RequestOptions({ headers: headers });
	  let body = new URLSearchParams();
     
      body.set("message", JSON.stringify(m_dataRequest));
      body.set("webService", "authService");
   
	  return this.http
	             .post(this.Url, body.toString(), options)
	             .toPromise()
	             .then(this.extractData)
	             .catch(this.handleError);

this work for me
