### ISSUE TITLE
Traversal on Angular 2 Router

### ISSUE THREAD

**Issue by bloodbare** [angular/angular#8671]
At Plone community the urls of our actual system is based on traversal behavior. You go throw a tree of objects to reach the final document you want to return to the user. This behavior has some urls like /folde1/page1/edit format. We are trying to move the front logic to an angular 2 application that renders with the same urls the content from the API.

With the new router is it possible to have nested routing and its awesome in a lot of ways, but we could not find how we should implement a non URL Dispatcher routing, we don't know the urls that are going to be accessible, somebody can create a new object and a new route will be available, we never know how many urls we will have available.

_Use https://plnkr.co or similar -- try this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5_

_What steps should we try in your demo to see the problem?_

**Current behavior**

Current behavior of routing with a wildcard does not provide a way to do traverse on the url, neither know which component is going to be rendered based on what a server endpoint can answer.

**Expected/desired behavior**

We want to be able to define which component is going to be rendered based on a API call with the url location information.

**Other information**

**Comment by DzmitryShylovich** [comment]
@bloodbare is this still an issue with the new router? Pls add a small repro in plunkr

**Comment by bloodbare** [comment]
@ebrehault is checking this issue right now, he will be able to keep track of the actual situation.

**Comment by ebrehault** [comment]
I have asked this question at the Angular framework team meeting, and @vsavkin explained we can do that by implementing our own `routerStateSnapshot`. I haven't tried it yet, I will keep you informed.

**Comment by DzmitryShylovich** [comment]
@ebrehault any update?

**Comment by ebrehault** [comment]
@DzmitryShylovich after testing different approaches, it seems the router was bringing a lot of useless complexity for our use case, so I have implemented our own directive. You can have a look here if you are interested: https://github.com/makinacorpus/angular-traversal/ and you can close the issue.

**Comment by DzmitryShylovich** [comment]
@ebrehault 👍 
@bloodbare close the issue pls. thx
