### ISSUE TITLE
Want to make service in Angular2 which can make http call to different origin

### ISSUE THREAD

**Issue by RohitLuthra19** [angular/angular#8673]
###  **I want to make service in Angular2 which can make http call to different Cross origin with 'Content-Type', 'application/x-www-form-urlencoded'   and get json response in Angular2 array or any object.**

Basically How to submit Formdata using JSONP for **cross-domain**

				/**
				 * Created by rkumar on 5/16/2016.
				 */

				import {Injectable} from "@angular/core";
				import {Jsonp, URLSearchParams, Http, Response, Headers, RequestOptions} from '@angular/http';
				import 'rxjs/add/operator/map';
				import {Observable} from 'rxjs/Observable'

				@Injectable()
				export class JsonDataService{

				  records: Object;
				  private jsonDataUrl = "http://localhost:8080/serverUtilizationReport";

				  constructor(private http: Http){  }

				  getJsonData(){
					var headers = new Headers();
					headers.append('Content-Type', 'application/x-www-form-urlencoded');
					headers.append('Access-Control-Allow-Origin','http://localhost:8080/serverUtilizationReport');
					return this.http.post(this.jsonDataUrl,JSON.stringify({TimeStamp:'2016-04-12 12:50:00'}),{headers:headers})
					  .map(this.extractData)
				  }

				  private extractData(res: Response) {
					if (res.status < 200 || res.status >= 300) {
					  throw new Error('Response status: ' + res.status);
					}
					let body = res.json();
					return body.data || { };
				  }

				}

**# But  i am getting an error in Console as follows:** 

![image](https://cloud.githubusercontent.com/assets/11659536/15291202/54f25b2e-1b9a-11e6-9aeb-3837e0490df4.png)

**Comment by ericmartinezr** [comment]
@robertmesserle github is not the place for support questions. See https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem. Your problem is very well known, so please ask where you are supposed to so you can get the answer you need.

**Comment by RohitLuthra19** [comment]
Rather than helping a person everyone gives you suggestion that post your question at stackoverflow blaw blaw...

**Comment by ericmartinezr** [comment]
@RohitLuthra19 the place to ask for help is where the link suggests, did you read it? It mentions a few more options than StackOverflow. If you ask on Gitter, StackOverflow, Google groups, etc, people will be more than willing to help you.

**Comment by robwormald** [comment]
> Rather than helping a person everyone gives you suggestion that post your question at stackoverflow bla bla...

This is because, as @ericmartinezr stated, GitHub issues are reserved for issues rather than technical support. Please take this question to the gitter channel.
