### ISSUE TITLE
RouteMetadata / name

### ISSUE THREAD

**Issue by savvaoff** [angular/angular#8674]
would be nice to add/return `name` property to routes. for example:
```
@Routes([
  {path: '/signin', component: SigninComponent, name: 'signin'},
...
```

ps.
and the ability to navigate by names (using it in django backend framework and can say it's handful).

**Comment by proggeramlug** [comment]
That would just make the new router more complicated and doesn't really add any value. Since the path should be unique anyways it's almost an equivalent of a name.

**Comment by zoechi** [comment]
AFAIK this was a deliberate decision to fix issues with lazy loading.

**Comment by Zefling** [comment]
Change an URL with the new router is little complicated on big project, is absolute not equivalent of the name.

**Comment by dharders** [comment]
Metadata would be great.

Eg. `{name: 'My navbar title'}`. Currently I have to define this in two places. 

1. Once for `@Routes( { path: 'sales', component: SalesComponent } )`
2. Then again to map `path` to _title_ to display in my NavComponent

Have it all in one place `@ Routes()`, then have the metadata **passed to me from the `router.events` observable**.

**Comment by vsavkin** [comment]
We recently merged a new implementation of the router. You can find the overview here http://victorsavkin.com/post/145672529346/angular-router.

The new implementation doesn't have the notion of route names and instead relies on redirects to achieve what you want. 

Closing this issue.
