### ISSUE TITLE
JitEmitterVisitor producing incorrect arguments

### ISSUE THREAD

**Issue by jfromme** [angular/angular#8676]
I have situation where code generated by angular is trying to call ngOnInit on an injectable service which does not have this method.

I believe the problem is caused by JitEmitterVisitor.visitExternalExpr() producing duplicate names for two different arguments at the line:

`this._evalArgNames.push(sanitizeIdentifier(`jit_${name}${id}`));`

I have a component which is given the name class11 and the service has the name class1. There is a function evaluation where the component is the 4th arg visited (id = 3) and the service is the 14th. (id = 13). So both args end up with the name jit_class113. Then getArgs() overwrites the component with the service and the wrong object is passed during evaluation.

Maybe the fix is to add a separator between the name and the id?

`this._evalArgNames.push(sanitizeIdentifier(`jit_${name}_${id}`));`

I don't know if it's a coincidence, but running in production mode seems to fix the problem.

**Comment by vicb** [comment]
already fixed

**Comment by chuckjaz** [comment]
Fixed with #18179
