### ISSUE TITLE
fakeAsync tick does not mock the Date object

### ISSUE THREAD

**Issue by diestrin** [angular/angular#8678]
**Steps to reproduce and a minimal demo of the problem**
- Use fakeAsync in a test
- Create a variable with the current Date
- tick(2000) or any other number
- Create another variable with the current Date

**Current behavior**
The 2nd date is not the one you think it is

**Expected/desired behavior**
The 2nd date will be 2000ms later than the first one

**Comment by DzmitryShylovich** [comment]
@diestrin is this still an issue? pls add a small repro

**Comment by Necroskillz** [comment]
Would be nice if this worked. Since `fakeAsync` doesn't freeze javascript `Date`, it's very awkward to mock `Date` in angular 2. Unfortunately `jasmine.clock().mockDate()` clashes with `zone` and also is not usable without some hacks. (see http://stackoverflow.com/questions/39600819/conflict-between-zone-js-and-jasmines-clock)

Is it possible to make this work?
```
fit('should move date', fakeAsync(() => {
    const date = new Date().getTime();

    tick(2000);

    let diff = new Date().getTime() - date;

    expect(diff).toBe(2000);
}));
```

Another option would be to somehow fix `zone` and `jasmine.clock()` interaction.

**Comment by dfederm** [comment]
Any progress on this bug?

The code above does repro the issue, and here's the flip side (the "`zone` and `jasmine.clock()` interaction") with a somewhat practical application:

```ts
class TimeAgoPipe implements PipeTransform
{
    public transform(date: Date | string): string
    {
        let time = date.getTime();
        let timeDiff = new Date().getTime() - time;
        // For brevity, cutting out code that picks the correct granularity of time
        return Math.ceil(timeDiff / 1000) + " seconds ago";
    }
}

it("should display how many seconds ago", () =>
{
  jasmine.clock().withMock(() =>
  {
    let time = new Date();
    time.setSeconds(time.getSeconds() - 5);

    let pipe = new TimeAgoPipe();
    expect(pipe.transform(time)).toEqual("5 seconds ago");
  });
});
```

The error is `Jasmine Clock was unable to install over custom global timer functions. Is the clock already installed?` and is thrown on the `jasmine.clock().withMock()` call.

**Comment by Jopie64** [comment]
I made a small library that mitigates this problem.
https://www.npmjs.com/package/angular-testing-ext
https://github.com/Jopie64/angular-testing-ext

Hopefully we won't need it very long.

**Comment by vikerman** [comment]
Coming up with a test wrapper library that should solve this issue.

**Comment by cwmrowe** [comment]
@vikerman why did you close this? I'm using @Jopie64's `angular-testing-ext` which is great, but I was hoping the angular team would include a fix themselves.

**Comment by JiaLiPassion** [comment]
I would like to try to make a PR in `zone.js` to 

- mock Date
- patch jasmine.clock 

when in `fakeAsyncZone`.

**Comment by JiaLiPassion** [comment]
I have made a PR, https://github.com/angular/zone.js/pull/1009

support `Date.now` in `fakeAsync`. there are `3` features in this PR.

- support auto patch `Date.now` in `fakeAsync`.

```javascript
it ('fakeAsyncTest', fakeAsync( () => {
        const start = Date.now();
        testZoneSpec.tick(100);
        const end = Date.now();
        expect(end - start).toBe(100); // will be true.
  });
```

- automatically run a `fakeAsync` test when `jasmine.clock().install` is called.

```javascript
beforeEach(() => {
      jasmine.clock().install(); // will not throw error any more, and will automatically run a fakeAsync in `it`.
    });

    afterEach(() => {
      jasmine.clock().uninstall();
    });

    it('should get date diff correctly', () => {  // we don't need fakeAsync here.
      // automatically run into fake async zone, because jasmine.clock() is installed.
      const start = Date.now();
      jasmine.clock().tick(100);
      const end = Date.now();
      expect(end - start).toBe(100);
    });
```

- rxjs `Scheduler` support, need to import `zone.js/dist/zone-patch-rxjs-fake-async`.

```javascript
    import '../../lib/rxjs/rxjs-fake-async';
    it('should get date diff correctly', (done) => {
      fakeAsyncTestZone.run(() => {
        let result = null;
        const observable = new Observable((subscribe: any) => {
          subscribe.next('hello');
        });
        observable.delay(1000).subscribe(v => {
          result = v;
        });
        expect(result).toBeNull();
        testZoneSpec.tick(1000);
        expect(result).toBe('hello');
        done();
      });
    });
```

I will make a PR in `angular` when the PR in `zone.js` is merged. 

@diestrin , @Necroskillz , @dfederm , @Jopie64 , @cwmrowe 
Please check whether the requirement is met or not.

**Comment by Jopie64** [comment]
@JiaLiPassion 
For your info, your last test leaks a subscription because the observable never completes and the subscription is never unsubscribed.
Instead of this:

```javascript
const observable = new Observable((subscribe: any) => {
  subscribe.next('hello');
});
observable.delay(1000).subscribe(v => {
  result = v;
});
```

You can write this to fix it:
```javascript
Observable.of('hello').delay(1000).subscribe(v => result = v);
```
(`Observable.of()` completes after sending the single value)

Anyway, for me it looks like this will fix my issue. Thanks for making my library obsolete! 👍 XD

**Comment by intellix** [comment]
I'm guessing we need something upstream to angular/angular before we can use this? Not able to test RxJS delay operator right now.

Does it make sense to add this by default to CLI **test.ts** as well? https://github.com/angular/devkit/blob/master/packages/schematics/angular/application/files/src/test.ts

**Comment by vicneanschi** [comment]
Please read https://github.com/angular/zone.js/pull/1009#issuecomment-378449144 if using Angular 5
