### ISSUE TITLE
"/" path for a route causes the router link to always have the "router-link-active" class, no matter what other route you're navigating to

### ISSUE THREAD

**Issue by MrCroft** [angular/angular#8679]
##### Angular 2.0.0-rc.1

Given the following route config in my app component:
```javascript
@Routes([
    { path: '/', component: HomeComponent },
    { path: '/another-route', component: AnotherComponent }
])
```

And the following router links in a template:
```html
<a [routerLink]="['/']">Home</a>
<a [routerLink]="['/another-route']">Another Page</a>
```

The anchor for the home component route will always have the class "router-link-active", not just when you navigate to it.

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/issues/8397

**Comment by MrCroft** [comment]
Thank you @ericmartinezr , I couldn't find that. I'll close this now, as it's a dupllicate!
