### ISSUE TITLE
Angular2 socket call

### ISSUE THREAD

**Issue by Nishchit14** [angular/angular#8683]
**Angular** and **Angular2** mainly used with **_NodeJS_** and other real-time frameworks like **_meteor_**. So user need to call **web-socket** for real-time call. 

So it would be cool to have socket library built in `@angular/socket`

**Current behavior**
Currently angular2 use `http` library under `@angular/http`.
There is no library for `socket`

**Expected/desired behavior**

Simply it can use by impoting like
```
import { Socket } from '@angular/socket';
```

**Comment by mhevery** [comment]
outside the scope of angular.
