### ISSUE TITLE
[style.background-color] works but [style.background-image] doesn't

### ISSUE THREAD

**Issue by dabalyan** [angular/angular#8686]
Is it possible to add any possible css style property with `[style.property]` annotation or is there any limitation for properties with a `-` hyphen in the name,

If it is then why does `[style.background-color]` work but `[style.background-image]` doesn't ?
Is there some other syntax for this ? 

I already know that `[ngStyle]` can do this.

**Steps to reproduce and a minimal demo of the problem**

[PLUNKER](http://plnkr.co/edit/D2C0f2r7EbtzL42V1FCC?p=preview)

**Comment by djejaquino** [comment]
Aparently, it doesn't work in RC releases. I've been struggling with this problem aswell, since I've seen it working in previously versions.

**Comment by ericmartinezr** [comment]
It's not a bug, it's a feature, see https://github.com/angular/angular/issues/8491

**Comment by mhevery** [comment]
working as intended
