### ISSUE TITLE
http request param escaping insufficient

### ISSUE THREAD

**Issue by nahratzah** [angular/angular#8688]
## Reproducable step:

```
import Http from '@angular2/http';

export class TestCase {
  constructor(private http: Http) {}  // provided by bootstrap

  public callHttp() {
    let params: URLSearchParams = new URLSearchParams();
    params.set('q', '1+1');

    return this.http.get("http://www.google.com/",  { search: params });
  }
}
```

_What steps should we try in your demo to see the problem?_

Follow the http request in the browser debug tools.

**Current behavior**

Performs a call to `https://www.google.com/?q=1+1`.
(Due to HTTP URL arguments, the `+` will be interpreted as a space.)

**Expected/desired behavior**

Correctly encodes the `+` symbol using `%2B`, creating a call to `https://www.google.com/?q=1%2b1`

**Other information**

As a workaround, build the query manually:

```
return this.http.get("http://www.google.com/?q=" + encodeURLComponent("1+1"));
```

**Comment by janbaer** [comment]
It seems that it's the same problem that I described in #9348

**Comment by DzmitryShylovich** [comment]
I believe it was fixed here https://github.com/angular/angular/commit/16204263939944a04e717f4dd44fdb9eb63119c5

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource close?
