### ISSUE TITLE
New Router: Add API to get all Routes of a component

### ISSUE THREAD

**Issue by paroga** [angular/angular#8690]
I like to have an API to get all Routes of my application. This could then be used on the server (e.g. via angular universal) to register them in the framework.

For the [Router Demo](https://angular.io/resources/live-examples/router/ts/plnkr.html) this should return ```["/crisis-center", "/crisis-center/:id", "/heroes", "/hero/:id"]```.

Where can such an function be exposed by angular? (I'd like to create a PR for it)

**Current Code (can be added to AppComponent)**
```javascript
static getAllRoutes() {
  let RoutesMetadata = Routes.annotationCls;
  let ret = [];

  function addComponentRoutes(prefix, component) {
    let metadata = reflector.annotations(component)
      .filter(f => f instanceof RoutesMetadata)[0];
    if (!metadata)
      return false;
    metadata.routes.forEach((route) => {
      let routePath = prefix + route.path;
      if (!addComponentRoutes(routePath, route.component))
        ret.push(routePath);
    });
    return true;
  }

  addComponentRoutes('', this);
  return ret;
}
```

Example:
```AppComponent.getAllRoutes() == ["/crisis-center", "/crisis-center/:id", "/heroes", "/hero/:id"]```

**Comment by sirajc** [comment]
This is good to have for new router.±1

**Comment by vsavkin** [comment]
Closing this as the new router provides access to the configuration.
