### ISSUE TITLE
template-compiler: error on installation from npm and when running

### ISSUE THREAD

**Issue by developer82** [angular/angular#8691]
I'm trying to run the npm as suggested in npm page:
`npm install angular2-template-compiler typescript@next rxjs @angular/compiler`

This is the output (which indicates that some stuff are missing):
`npm WARN deprecated angular2-template-compiler@0.1.9: use @angular/compiler-cli instead
my-app@0.0.0 C:\TEMP\my_app
+-- UNMET PEER DEPENDENCY @angular/compiler@2.0.0-rc.1
+-- UNMET PEER DEPENDENCY @angular/core@2.0.0-rc.1
+-- UNMET PEER DEPENDENCY @angular/platform-server@^0.0.0-5
+-- angular-cli@1.0.0-beta.1
| +-- broccoli@1.0.0-beta.7
| | `-- handlebars@4.0.5
| |   `-- uglify-js@2.6.2
| |     +-- async@0.2.10
| |     +-- source-map@0.5.6
| |     +-- uglify-to-browserify@1.0.2
| |     `-- yargs@3.10.0
| |       +-- camelcase@1.2.1
| |       +-- cliui@2.1.0
| |       | +-- center-align@0.1.3
| |       | | +-- align-text@0.1.4
| |       | | | +-- kind-of@3.0.3
| |       | | | | `-- is-buffer@1.1.3
| |       | | | +-- longest@1.0.1
| |       | | | `-- repeat-string@1.5.4
| |       | | `-- lazy-cache@1.0.4
| |       | +-- right-align@0.1.3
| |       | `-- wordwrap@0.0.2
| |       +-- decamelize@1.2.0
| |       `-- window-size@0.1.0
| +-- ember-cli@2.5.0
| | `-- testem@1.7.1
| |   `-- tap-parser@1.2.2
| |     `-- readable-stream@2.1.2
| |       +-- core-util-is@1.0.2
| |       +-- inherits@2.0.1
| |       +-- isarray@1.0.0
| |       +-- process-nextick-args@1.0.7
| |       +-- string_decoder@0.10.31
| |       `-- util-deprecate@1.0.2
| `-- typescript@1.8.10
+-- angular2-template-compiler@0.1.9  extraneous
+-- protractor@3.3.0
| `-- request@2.67.0
|   `-- http-signature@1.1.1
|     `-- sshpk@1.8.3
|       +-- ecc-jsbn@0.1.1
|       +-- jodid25519@1.0.2
|       +-- jsbn@0.1.0
|       `-- tweetnacl@0.13.3
+-- UNMET PEER DEPENDENCY typescript@1.9.0-dev.20160517-1.0 extraneous
`-- typings@0.8.1
  `-- typings-core@0.3.1
    `-- typescript@1.8.10

npm WARN optional Skipping failed optional dependency /karma/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm WARN tslint@3.10.2 requires a peer of typescript@>=1.7.3 but none was installed.
npm WARN angular2-template-compiler@0.1.9 requires a peer of @angular/compiler@^0.0.0-5 but none was installed.
npm WARN angular2-template-compiler@0.1.9 requires a peer of @angular/platform-server@^0.0.0-5 but none was installed.
npm WARN angular2-template-compiler@0.1.9 requires a peer of @angular/core@^0.0.0-5 but none was installed.`

when trying to run `ng2tc` I get:
`module.js:440
    throw err;
    ^

Error: Cannot find module '@angular/core/src/facade/collection'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Ophir_O\AppData\Roaming\npm\node_modules\angular2-template-compiler\static_reflector.js:2:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)`

**Comment by mhevery** [comment]
Sorry, this is still experimental. It will be officially supported in few RC drops.

**Comment by developer82** [comment]
Any way to be part of the experiment? make it work?
