### ISSUE TITLE
New Router: method _navigate is called two times in case of HashLocationStrategy

### ISSUE THREAD

**Issue by andrui** [angular/angular#8692]
The issue is caused by location subscription:

`
    _setUpLocationChangeListener() {
        this._locationSubscription = this._location.subscribe((change) => { this._navigate(this._urlSerializer.parse(change['url'])); });
    }
`

In case of HashLocationStrategy _location emits two events with different types:
Object {url: "/mypage", pop: true, type: "popstate"}
Object {url: "/mypage", pop: true, type: "hashchange"}

In order to reproduce use HashLocationStrategy in app, open root page and navigate to some page via browser URL

The problem is that 'changes' event of the Router is also emitted two times

**Comment by vsavkin** [comment]
@andrui We are no longer maintaining the deprecated router to focus our efforts on making the new router solid. 

Could you reproduce the problem with the new router and submit a separate issue? 

Close this issue.
