### ISSUE TITLE
router doesn't escape arguments properly

### ISSUE THREAD

**Issue by nahratzah** [angular/angular#8695]
**Steps to reproduce and a minimal demo of the problem**

    @Routes([
      { path: '/formula-edit', component: FormulaComponent }
    ])
    export class ExampleComponent {
      constructor(private router: Router) {}

      public showFormula() {
        let args = {};
        args['formula'] = '1 + (2 * 3)';

        this.router.navigate(['/formula-edit', args]);
      }
    }

_What steps should we try in your demo to see the problem?_

Invoke showFormula.
When on page /formula-edit, reload with the same arguments.

**Current behavior**

location is updated to ``/formula-edit;formula=1 + (2 * 3)``
Loading this URL directly causes the router component to fail, trying to do some special processing with respect to the brackets.

If the ``formula`` argument contained a slash, ex:  ``/formula-edit;formula=4/2``, the router attempts to interpret ``formula-edit;formula=4`` as a single path element and resolve ``/2`` as a subcomponent path.

**Expected/desired behavior**

Keys and values following the first semicolon are properly escaped:
- slashes are escaped (or maybe the router stops analyzing path components, when it encounters the first semicolon, although that may be hard with certain webservers?)
- round brackets are escaped

**Other information**

Workaround, by manually escaping all keys and values:

    function _escape(s: string): string {
      return encodeURIComponent(s)
          .replace(/\(/g, '%28')
          .replace(/\)/g, '%29');
    }

    args[_escape('formula')] = _escape('1 + (2 * 3)');

and decoding them when read:

    routerOnActivate(curr: RouteSegment,
                     prev?: RouteSegment,
                     currTree?: RouteTree,
                     prevTree?: RouteTree): void {
      let exprs: Map<string, string> = new Map<string, string>();

      Object.keys(curr.parameters).forEach((enc_k) => {
        let k: string = decodeURIComponent(enc_k);
        let v: string = decodeURIComponent(curr.getParam(enc_k));

        // Do something with argument named k, with value v.
      });
      this.exprs = exprs;
    }

**Comment by CaptainCodeman** [comment]
I think the label is incorrect - it looks like new router, not deprecated.

**Comment by vsavkin** [comment]
Fixed here https://github.com/angular/angular/commit/46e105f3ab7c810ca32eebd9d5c5372b57c0f510

**Comment by mtpultz** [comment]
Not sure if I'm missing something, but a URL of `http://localhost:4200/list;id=8` is converted into `http://localhost:4200/login?redirectUrl=%2Fform%2Firc%2Flist`, and then a route is performed on the redirectUrl param like this `this.router.navigate([this.redirectUrl]);` produces this `http://localhost:4200/list%3Bid%3D8`, which isn't converting the semi-colon or equal sign to match the original URL.
