### ISSUE TITLE
New RC Router seems to throw random exceptions

### ISSUE THREAD

**Issue by tylerchurch** [angular/angular#8696]
**Steps to reproduce and a minimal demo of the problem**

Here's a plunker: http://plnkr.co/edit/3M5XUpH0qVl9i6ZtVloS

It's a modified version of the one linked to from here: https://angular.io/docs/ts/latest/guide/router.html My version adds next/previous buttons to the crisis center.

_What steps should we try in your demo to see the problem?_

- Play around with pressing the next/previous buttons, eventually an error will be thrown.

**Current behavior**

Eventually you'll see an error like this in the console:

```
Error: Uncaught (in promise): Cannot match any routes. Current segment: '1'. Available routes: ['/crisis-center', '/heroes', '/hero/:id'].
    at resolvePromise (VM464 zone.js@0.6.12?main=browser:538)
    at resolvePromise (VM464 zone.js@0.6.12?main=browser:523)
    at VM464 zone.js@0.6.12?main=browser:571
    at ZoneDelegate.invokeTask (VM464 zone.js@0.6.12?main=browser:356)
    at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (VM503 core.umd.js:6066)
    at ZoneDelegate.invokeTask (VM464 zone.js@0.6.12?main=browser:355)
    at Zone.runTask (VM464 zone.js@0.6.12?main=browser:256)
    at drainMicroTaskQueue (VM464 zone.js@0.6.12?main=browser:474)
    at HTMLLIElement.ZoneTask.invoke (VM464 zone.js@0.6.12?main=browser:426)
```

**Expected/desired behavior**

An error shouldn't be thrown.

**Other information**

My real reason for filing this bug is that yesterday I was upgrading one of our projects to the latest version of Angular 2 and decided to upgrade to the new router as well. Similar to the plunker, we have some links that simply change the number at the end of the URL, and after a couple `router.navigate`s (not immediately one after the other, I just mean after a user has clicked on a couple links) the app would throw this exception:

```
TypeError: Cannot read property 'map' of null
    at UrlTree.Tree.pathFromRoot (segments.ts:38)
    at _findUrlSegment (link.ts:87)
    at _findStartingNode (link.ts:98)
    at Object.link (link.ts:19)
    at Router.createUrlTree (router.ts:145)
    at RouterLink._updateTargetUrlAndHref (router_link.ts:55)
    at Object.eval (router_link.ts:33)
    at eval (async.ts:130)
    at ZoneDelegate.invokeTask (zone.js:356)
    at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (ng_zone_impl.ts:56)
```

I haven't been able to get the plunker to produce the exact same error, but perhaps the two different errors are related somehow since they seem similar.

As far as I can tell, part of the cause of the above stack trace is the code located here: https://github.com/angular/angular/blob/master/modules/%40angular/router/src/segments.ts#L29

```ts
pathFromRoot(t: T): T[] { return _findPath(t, this._root, []).map(s => s.value); }
```

Which calls `_findPath`, which can return `null`, but the code never checks for that. Not sure if that's the root cause of the issue (e.g. I have no idea about all the calling code and why that particular code path would end up with `_findPath` returning `null`.)

The weird thing though is that the app still seems to navigate successfully despite the error.

Finally, the "release candidate" label for the router seems incorrect to me. To me "release candidate" would mean "this is something we could release if the testers find no bugs" but basic features like useAsDefault ( https://github.com/angular/angular/issues/8579 ) seem to be missing, documentation seems to be sorely lacking, and I ran into these errors really quickly...

**Comment by ajayambre** [comment]
@tylerchurch  #8567 has plunker links which give this error <code>TypeError: Cannot read property 'map' of null</code>

**Comment by tylerchurch** [comment]
@ajayambre Ah, yep, that one does look like the same issue I'm seeing.
@mhevery Not sure how the issues are organized, but shouldn't the tag be `router` not `router-deprecated` since this is an issue in the new router?

**Comment by TerryMooreII** [comment]
@tylerchurch You are not alone, I am also experiencing this issue.
Version
"@angular/router": "2.0.0-rc.1",

```
TypeError: Cannot read property 'map' of null
    at UrlTree.Tree.pathFromRoot (segments.js:30)
    at _findUrlSegment (link.js:79)
    at _findStartingNode (link.js:90)
    at Object.link (link.js:14)
    at Router.createUrlTree (router.js:133)
    at RouterLink._updateTargetUrlAndHref (router_link.js:42)
    at Object.eval (router_link.js:17)
    at eval (async.js:122)
    at ZoneDelegate.invokeTask (zone.js:356)
    at Object.NgZoneImpl.inner.inner.fork.onInvokeTask 
```

I am not sure the exact steps to reproduce other than click on some routes and you will eventually get the error.  But like @tylerchurch said, it still routes successfully.

**Comment by webdokkeren** [comment]
Experincing the same as @tylerchurch and @TerryMooreII

**Comment by zoechi** [comment]
@tylerchurch The error message seems to be caused because the `id` is passed as objects. Parameters are just passed as "directory" in the new router. http://plnkr.co/edit/8ry4DCNMdCtMIwvP86DZ?p=preview (app/crisis-center/crisis-detail.component.ts)

**Comment by tylerchurch** [comment]
@zoechi Then why is this in the docs?:

```ts
this.router.navigate([`/heroes`, {id: heroId, foo: 'foo'}]);
```

And this in the example plunker?:

```ts
this.router.navigate(['/crisis-center', {id: crisisId, foo: 'foo'}]);
```

You saying this is a documentation bug?

**Comment by zoechi** [comment]
@tylerchurch  Do you have a link to this code in the docs? AFAIK they are still working on getting the docs up-to-date therefore it's possible that the docs have outdated content.

**Comment by tylerchurch** [comment]
Link: https://angular.io/docs/ts/latest/guide/router.html

Under "Milestone #4: Query Parameters" is the first snippet I pasted.

Right at the top of the page are these words: "We cover the router's primary features in this chapter, illustrating them through the evolution of a small application that we can _run live_." "run live" is a link which ends up leading to this plunker: http://plnkr.co/edit/DfvjrEJabdbJRI3JFKSR Which has the second snippet I pasted in `app/crisis-center/crisis-detail.component.ts`

**Comment by zoechi** [comment]
It starts with a red banner 

> This chapter is a work in progress.

**Comment by IgorMinar** [comment]
this issue is now obsolete. for more info please see: https://angularjs.blogspot.com/2016/06/improvements-coming-for-routing-in.html
