### ISSUE TITLE
Integrate CSS Parser into compile pipeline

### ISSUE THREAD

**Issue by tbosch** [angular/angular#8698]
For animations, we need to read styles from the stylesheets. Right now that is not possible as stylesheets are compiled independently of components. To solve this, we should do the following changes:

New `OfflineCompiler` interface:
```
class ComponentWithDeps {
  constructor(public component: CompileDirectiveMetadata,
              public directives: CompileDirectiveMetadata[], public pipes: CompilePipeMetadata[]) {}
}

class OfflineCompiler {
  compileComponents(components: ComponentWithDeps[]): Promise<SourceModule[]> {
    ...
  }
}
```

The `OfflineCompiler.compileComponents` should do the following:

1. normalize all directives via the `DirectiveNormalizer`.
2. load and parse all referenced style sheets (including their imports) via `XHR`
3. produce the `.ngfactory.ts` file as before, passing in the parsed stylesheets to the 
    `AnimationCompiler` (if it is already in master)
4. for each stylesheet, call the `StylesheetCompiler` and produce a `SourceModule`

Note that this has the side effect of producing the `SourceModule`s for stylesheets that are shared between components multiple time. The caller can either dedupe these across components, or just overwrite the existing files as the content of these `SourceModule`s are the same.

Detailed changes / commits:

1. change the API of the `OfflineCompiler` as shown above, but:
    - don't use the css parser
    - don't pass in the parsed styles into the `AnimationCompiler`
    - don't use the css parser for style encapsulation
2. parse the stylesheets via the css parser and use the `CssAST` for the style encapsulation
3. pass the `CssAST` into the `AnimationCompiler` and use it to read styles for animations

**Comment by mhevery** [comment]
SGTM

**Comment by tbosch** [comment]
See https://github.com/angular/angular/pull/9594 which already loads all shared templates before compiling...

**Comment by vicb** [comment]
obsolete
