### ISSUE TITLE
Clear steps to build angular 2 contributing

### ISSUE THREAD

**Issue by miguelramos** [angular/angular#8702]
Following the guide on development doc, it's pretty clear that the project is not building correctly. After clone and configure environment to Dart even, npm install keeps failing.
Errors are like:
- Unmeet dependency on typescript
- No typings install
- On OSX brokes when node-sass is compiling
- Dart retrieving packages hang

What are the necessary steps to put this working for contributing?

**Comment by mhevery** [comment]
Sorry we are in the middle of redoing the build system and it is a mess. Please hang in there we should have it cleaned up soon. Will close this issue since we are aware and are working on it already.

**Comment by miguelramos** [comment]
Thanks @mhevery for the answer. Can you reference here when it's ready?
