### ISSUE TITLE
Add @Input accessibility to Attribute Directive documentation

### ISSUE THREAD

**Issue by JoostvdB94** [angular/angular#8706]
Documentation: https://angular.io/docs/ts/latest/guide/attribute-directives.html
**Current behavior**
Attribute directive does not mention that `@Input` is not available in the constuctor. The documentation assumes that the user knows this.

**Expected/desired behavior**
An explanation that the `@Input` variables have to be used in an Event in order to access the variable.

**Comment by zoechi** [comment]
Doc issues are maintained in https://github.com/angular/angular.io 
There is a distinct chapter for lifecycle hook anyway. Some reference might not hurt though.
