### ISSUE TITLE
Fix names of Dart libraries - remove _dart from name

### ISSUE THREAD

**Issue by kevmoo** [angular/angular#871]
...and `angular2.angular2_dart` should just be `angular2`

![screen shot 2015-03-03 at 12 38 14 pm](https://cloud.githubusercontent.com/assets/17034/6471757/9e43bdb6-c1a2-11e4-9550-1939394dec04.png)

**Comment by rkirov** [comment]
This was added because we have a directive named `if` and if we naively transpile to `library if;` dart barfs - `if` is a keyword. 

So we added `_dart` to all library names, but it would be better if we keep a list of forbidden library names and just append `_dart` to those.

**Comment by kevmoo** [comment]
@rkirov that sounds great.

Or we could ponder changing the name of the `if` library?
