### ISSUE TITLE
Select input resets to original Control value even if it has been updated, when the options get altered. 

### ISSUE THREAD

**Issue by schippie** [angular/angular#8710]
**Steps to reproduce and a minimal demo of the problem**

It seems that the ngControl value does not reflects an update within the view (it resets a few milliseconds after it was altered) when the value is changed by the select and the options that are displayed within the select are altered. Yet the actual value is updated (on the formBuilder/ControlGroup) yet this is not reflected within the view:

```html
<option 
	*ngFor="let d of days" 
	[value]="d.value" 
	[selected]="formModel.controls.day.value === d.value"
	[disabled]="d.disabled"
>{{d.label}}</option>
```

You can see it happening clearly within the plunk (else if you can add a timeout around the following code):

```javascript
//clear current days
this.days.splice(1, this.days.length);

//add list of new days to the array	
for(var i = 1; i <= days; i++) {
	this.days.push({
		label: i.toString(),
		value: i
	})
}
```

http://plnkr.co/edit/c7J1muLgoEhVNp0hVKfY?p=preview

_What steps should we try in your demo to see the problem?_

1.  Change the value in the dropdown to something else as today's date
2.  It should blink and immediately return back to the value of today yet below it the actual value of the Control is shown. 

**Current behavior**

Control value gets updated yet selected option automatically resets to the original Control value. 

**Expected/desired behavior**

Updated value should be reflected by the view even if the options get altered. As long as a viable option is found for the value it should mark that option as the selected one.

**Comment by butters16** [comment]
I've be struggling with the same issue. This plunk is a simple demonstration of how the actual value is correct, but the UI has the wrong option selected.
https://plnkr.co/edit/OVKq8uxYM45G16Ifpa4r?p=preview

**Comment by schippie** [comment]
I really wonder what might cause it though. Wonder if it has to do with the fact that a select as a different ControlValueAccessor : https://github.com/angular/angular/blob/master/modules/%40angular/common/src/forms/directives/select_control_value_accessor.ts
