### ISSUE TITLE
ngModel it isn't a known native property in angular2 rc2.0.0-rc.1

### ISSUE THREAD

**Issue by HilmiDEV** [angular/angular#8711]
How can use the two-way data binding angular2 rc2.0.0-rc.1 because I have problem with [(ng-model)] 
"Can't bind to 'ng-model' since it isn't a known native property"

**Comment by ericmartinezr** [comment]
You answered your own question in the title ._. ... it is `ngModel`, not `ng-model`. See https://angular.io/docs/ts/latest/guide/template-syntax.html#!#ngModel for more

**Comment by zoechi** [comment]
@HilmiDEV Can you please close this issue?
