### ISSUE TITLE
Angular 2 DOA continued

### ISSUE THREAD

**Issue by adrianme8** [angular/angular#8714]
so a new thread, some idiot locked the old one. Maybe that person should open up a browser and search for Angular 2 and check the opionin of its community.

https://github.com/angular/angular/issues/8208

**Comment by CaptainCodeman** [comment]
I understand your frustrations with the project, but seriously - anything like this is just going to be locked and rightly so.

Why do you need to convince people it's dead? Just use whatever framework you think is better instead.

**Comment by otodockal** [comment]
@adrianme8 it should be locked again...this is not issue! :)

**Comment by robwormald** [comment]
@adrianme8 final warning. follow the [code of conduct](https://github.com/angular/code-of-conduct) or we'll remove your ability to contribute entirely.
