### ISSUE TITLE
How to access angular 2 components from Chrome debug console in production mode

### ISSUE THREAD

**Issue by bluejaye** [angular/angular#8715]
Dear guys

Thank to @mhevery that I learnt ng.probe() function is unavailable in production mode because of the performance problem. 

@mhevery also gives another suggestion that hold of root component instance by the return value of boostrap. Which works in other angular's components, but not outside(eg. chrome debug console). I think I didn't find the right way to call it.

[My question is:]
If I have a property defined like below, how can I find and use the property from outside please (by using javascript in chrome's console)

**var testabc= bootstrap(AppComponent, [ROUTER_PROVIDERS]);**

Cheers
Jay

**Comment by DzmitryShylovich** [comment]
Look at [Augury](https://augury.angular.io/).

**Comment by bluejaye** [comment]
Thank you Dzmitry

I know this plugin. I can monitor angular 2 by it, but still I don't know how to run Angular's methods in debug console.

Can you give me more hints please. thank you very much.

Cheers
Jay

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
