### ISSUE TITLE
bug(AsyncPipe): AsyncPipe throws errors from the Observable, crashing the application

### ISSUE THREAD

**Issue by KlausConrado** [angular/angular#8719]
Hi.

The AsyncPipe simply throws any errors coming from the Observable, preventing any chance of error handling cause it crashes the whole application. This makes the AsyncPipe useless in a real application scenario like using http Observables. Is there any workaround for this bug? 

The following code from async_pipe.ts shows the bug location (`e => { throw e} `).

```
createSubscription(async: any, updateLatestValue: any): any {
    return ObservableWrapper.subscribe(async, updateLatestValue, e => { throw e; });
}
```

**Steps to reproduce and a minimal demo of the problem**
Just use a AsyncPipe in a component and attach an observable that finishes with a error to it.

**Current behavior**
The application crashes and there is no way to handle the error properly.

**Expected/desired behavior**
Let the application handle the error by itself (subscribing to the same observable of the AsyncPipe, for example).

Thanks.

**Comment by ericmartinezr** [comment]
There's a PR on hold for handling this case https://github.com/angular/angular/pull/7990. afaik you can also handle the error before it reaches the Async pipe, like (not 100% sure)

```
http.get('...').map(res => res.json()).catch(someFunctionThatHandlesTheError)
```

**Comment by KlausConrado** [comment]
I confirmed that the `catch` operator can prevent the error from reaching the AsyncPipe.
With this operator in mind i think it's ok the AsyncPipe throw any errors that reach it, because it will warn that the developers they should handle these erros.

Maybe the async_pipe.ts doc could point the importance of the `catch` operator in the Observables used with it.

Thanks for the help.
