### ISSUE TITLE
Support for absolute paths in component urls.

### ISSUE THREAD

**Issue by rkirov** [angular/angular#872]
Currently, component templates do not accept absolute paths i.e. `/foo/bar/template.html`.
First, should we support absolute paths in component templates? If yes, how should they resolve?
- `current_domain + absolute path`
- `current_url + absolute path`

I think, yes, and it should resolve just like anchor tag would resolve that path - `current_domain + absolute path`.

Note, that we all agree that file-relative paths are better for component reuse, but the question is what to do if an user writes absolute path.

If no, we should reword the error thrown to be explicit about our support - https://github.com/angular/angular/blob/03793d0714eb406927dbd037161b1c64979a2009/modules/angular2/src/core/compiler/url_resolver.js#L22

**Comment by gdi2290** [comment]
Can we also have a way for us to configure TemplateResolver or UrlResolver with SystemJS maps/paths/baseUrl. I want a way to explicitly configure them independently of the module system

**Comment by vicb** [comment]
Some background on why we only support relative paths:
- it makes component re-usable because they need not be aware of their own urls,
- it is also easier to handle server-side compilation where the compiler works with file paths rather than urls.

> I think, yes, and it should resolve just like anchor tag would resolve that path - current_domain + absolute path.

That's probably the best thing to do. Nobody would expect an absolute url to resolve to current_url + absolute path.
OTOH if your application is served from 'http://www.domain.com/myapp', you would have to prefix the urls with `/myapp`.

Need more thinking / discussion before selecting a solution.

**Comment by matanlurey** [comment]
Is this planned in an upcoming milestone? Most places that use Angular 1.0 will have to change all of their URLs to support Angular 2.0 right now.

**Comment by vicb** [comment]
@matanlurey do you have links to code / docs related to this for ng1 ?

**Comment by matanlurey** [comment]
Best example I can give is [how the template cache generator/transformer works in ng1](https://github.com/angular/angular.dart/blob/73b4153fad623a01eac25bd6f9a6b3489f2f5cd6/test/tools/transformer/template_cache_generator_spec.dart):

```dart
    it('should cache cssURLs', () {
      return generates(setupPhases(),
      inputs: {
          'a|web/main.dart': '''
                import 'package:angular/angular.dart';
                import 'dir/foo.dart';
                @Component(cssUrl: "test1.css")
                class A {}
                main() {}
                ''',
          'a|web/dir/foo.dart': '''
                import 'package:angular/angular.dart';
                @Component(cssUrl: ["test2.css"])
                class B {}
            ''',
          'a|web/test1.css': cssContent1,
          'a|web/dir/test2.css': cssContent2,
          'angular|lib/angular.dart': libAngular,
      },
      cacheContent: {
          'test1.css': cssContent1,
          'dir/test2.css': cssContent2,
      });
    });
```
