### ISSUE TITLE
Angular application embedded inside cordova was not working on Android 4.4 

### ISSUE THREAD

**Issue by dheran** [angular/angular#8721]
Angular application embedded inside codova not working in android 4.4 version. But working fine in 5.0. I checked for the logs and found **date pipe** was culprit

> 04-27 17:38:28.562: I/chromium(5160): [INFO:CONSOLE(30929)] "EXCEPTION: TypeError: Cannot redefine property: length in [{{appt.formattedDate | date : 'yMMMdjm'}} in PlayersListPage@19:29]", source: file:///android_asset/www/build/js/app.bundle.js (30929)
> 04-27 17:38:28.562: I/chromium(5160): [INFO:CONSOLE(30929)] "ORIGINAL EXCEPTION: TypeError: Cannot redefine property: length", source: file:///android_asset/www/build/js/app.bundle.js (30929)
> 04-27 17:38:28.562: I/chromium(5160): [INFO:CONSOLE(30929)] "ORIGINAL STACKTRACE:", source: file:///android_asset/www/build/js/app.bundle.js (30929)
> 04-27 17:38:28.562: I/chromium(5160): [INFO:CONSOLE(30929)] "TypeError: Cannot redefine property: length
> 04-27 17:38:28.562: I/chromium(5160): at defineProperty (native)
> 04-27 17:38:28.562: I/chromium(5160): at Function.Object.defineProperty (file:///android_asset/www/build/js/angular2-polyfills.js:1083:17)
> 04-27 17:38:28.562: I/chromium(5160): at freezeArray (v8/i18n:2004:8)
> 04-27 17:38:28.562: I/chromium(5160): at initializeLocaleList (v8/i18n:286:8)
> 04-27 17:38:28.562: I/chromium(5160): at resolveLocale (v8/i18n:1812:4)
> 04-27 17:38:28.562: I/chromium(5160): at initializeDateTimeFormat (v8/i18n:1149:7)
> 04-27 17:38:28.562: I/chromium(5160): at new Object.defineProperty.value.ax (v8/i18n:1227:8)
> 04-27 17:38:28.562: I/chromium(5160): at Function.DateFormatter.format (file:///android_asset/www/build/js/app.bundle.js:28941:25)
> 04-27 17:38:28.562: I/chromium(5160): at DatePipe.transform (file:///android_asset/www/build/js/app.bundle.js:6118:37)
> 04-27 17:38:28.562: I/chromium(5160): at AbstractChangeDetector.ChangeDetector_PlayersListPage_2.detectChangesInRecordsInternal (viewFactory_PlayersListPage:943:105)", source: file:///android_asset/www/build/js/app.bundle.js (30929)
> 04-27 17:38:28.562: I/chromium(5160): [INFO:CONSOLE(30929)] "ERROR CONTEXT:", source: file:///android_asset/www/build/js/app.bundle.js (30929)
> 04-27 17:38:28.582: I/chromium(5160): [INFO:CONSOLE(30929)] "[object Object]", source: file:///android_asset/www/build/js/app.bundle.js (30929)

**Comment by ericmartinezr** [comment]
dup of https://github.com/angular/angular/issues/8188

**Comment by pkozlowski-opensource** [comment]
Indeed, dup of #8188. Thnx @ericmartinezr
