### ISSUE TITLE
prevent navigation from nested component

### ISSUE THREAD

**Issue by bluEEil** [angular/angular#8722]
have a component which is set to a be inserted in some route. I want to write another more general component, that I can place in that first component and will prompt the user when he trys to navigate away from the first component route and ask him if he is sure he wants to leave

I tried to use CanDeactivate in this Leave Dialog component but it is never being called (when switching routes).

**Steps to reproduce and a minimal demo of the problem**
I have asked a question about this in stack over flow with more explanation and a code sample:
[http://stackoverflow.com/questions/37118511/prevent-navigation-from-nested-component-in-angular-2](prevent navigation from nested component)

**Current behavior**
The routerCanDeactivate method isn't called in the nested component and only in the root component of the route when the user tries to navigate away.

**Expected/desired behavior**
The routerCanDeactivate method should be called in the nested component as well so they can prevent navigation if needed

**Other information**
If there is a different way to achieve this behavior that Im not aware of then this might not be an issue.

**Comment by zoechi** [comment]
What Angular2 version, what Router version `router` of Angular2 RC.1 or router-deprecated?
In the new router `CanDeactivate` was just implemented (not yet released) https://github.com/angular/angular/pull/8477

**Comment by bluEEil** [comment]
Angular 2.0.0-beta.6
How can I tell about the router version? I dont see it in my package.json

**Comment by zoechi** [comment]
In beta.6 there is only one version. Since RC.0 there are two (the one already in beta.6 and a new one). #8477 is about the new one. I don't expect fixes for the old one anymore.

**Comment by bluEEil** [comment]
So this should be fixed by updating my version?

**Comment by zoechi** [comment]
Nope - "(not yet released)". Probably when Angular2 RC.2 is released. You'd also need to migrate to the new router.

**Comment by IgorMinar** [comment]
This issue was made obsolete by router v3: https://angularjs.blogspot.com/2016/06/improvements-coming-for-routing-in.html

This particular feature is available in router v3.
