### ISSUE TITLE
App startup lag around linkDynamicModule

### ISSUE THREAD

**Issue by zackarychapple** [angular/angular#8724]
Using RC0 and the AngularCLI I have generated a project and after working on it for a while I performed a prod build in the CLI and tested the deploy of the project.  I noticed there is an almost 1 second delay from the point at which my `main.js` and `index.js` files are retrieved and my first component is pulled down. 

Here is my bootstrap.
`bootstrap(WfaNg2AppComponent, [ ROUTER_PROVIDERS, provide(LocationStrategy, { useClass: HashLocationStrategy }) ]);`

Here is the network tab during the bootstrap. 
![screen shot 2016-05-19 at 8 48 08 am](https://cloud.githubusercontent.com/assets/2133184/15394037/74dba1b0-1d9e-11e6-8b40-dfb8f41dddc9.png)

Here is the timeline for that period of wait. 
![screen shot 2016-05-19 at 8 42 41 am](https://cloud.githubusercontent.com/assets/2133184/15393950/f4ece194-1d9d-11e6-999f-68300427644a.png)

If I turn off hash location strategy here is my network.
<img width="1675" alt="screen shot 2016-05-19 at 9 27 28 am" src="https://cloud.githubusercontent.com/assets/2133184/15395014/fd36ee0c-1da3-11e6-9970-78ad79051e1c.png">

Here is the timeline with the hash location strategy off.
<img width="1674" alt="screen shot 2016-05-19 at 9 29 19 am" src="https://cloud.githubusercontent.com/assets/2133184/15395057/3d0c3bae-1da4-11e6-966a-6b5530c9fb02.png">

**Comment by sod** [comment]
Module loader performance in general is very disappointing if you throw the angular modular structure against it. I guess thats the reason why the bundles where removed in rc.0

At the moment the team experiments with http://rollupjs.org/. A module bundler that can get rid of the module syntax alltogether and removes unused methods in the process.

@robwormald has a test repository https://github.com/robwormald/ng2-compiler-test2 that spawned from ng-conf. The build there is just 50kb gzipped and loads very fast. I hope he writes a blog about it or we get a rollup guide like the webpack one on https://angular.io/docs/ts/latest/guide/webpack.html

**Comment by zackarychapple** [comment]
Thats good information, I remember that talk well, the performance was fantastic.  I use the CLI though so I'm not quite ready to change the build strategy just yet.

**Comment by IgorMinar** [comment]
the AOT compilation and squashing modules via rollup addresses this problem. CLI will have these features enabled by default in the future releases. In the meantime it's possible to set these up via your own build pipeline.

**Comment by zackarychapple** [comment]
@IgorMinar looks like it's in the current build of the CLI. https://github.com/angular/angular-cli/issues/1732#issuecomment-251042818  Thank you again for helping to make sure this got fixed.
