### ISSUE TITLE
Angular 2 RC1 slow download comparing to beta7

### ISSUE THREAD

**Issue by karayv** [angular/angular#8725]
Hello,

I am preparing to prod my UI app initially implemented using Angular 2 beta5 (then upgraded version to beta7).

When it was beta7, the load script from quickstart looked like this:
`
    
    <script src="node_modules/systemjs/dist/system-polyfills.js"></script>
    <script src="node_modules/es6-shim/es6-shim.min.js"></script>

    <script src="node_modules/intl/dist/Intl.min.js"></script>
    <script src="node_modules/intl/locale-data/jsonp/en.js"></script>

    <script src="node_modules/angular2/bundles/angular2-polyfills.js"></script>
    <script src="node_modules/systemjs/dist/system.src.js"></script>
    <script src="node_modules/rxjs/bundles/Rx.js"></script>
    <script src="node_modules/angular2/bundles/angular2.dev.js"></script>
    <script src="node_modules/angular2/bundles/router.dev.js"></script>
    <script src="node_modules/angular2/bundles/http.dev.js"></script>

    <script src="node_modules/jquery/jquery.min.js"></script>
    <script src="node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="node_modules/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
    <script src="node_modules/bootstrap-timepicker/js/bootstrap-timepicker.min.js"></script>

    
    <script>
        System.config({
            packages: {
                app: {
                    format: 'register',
                    defaultExtension: 'js'
                }
            }
        });
        System.import('app/main')
                .then(null, console.error.bind(console));
    </script>
`
To load the app it took less than 5 seconds with this script in index.html

Now the script changed 

`    
    
    
    <script src="node_modules/es6-shim/es6-shim.min.js"></script>

    <script src="node_modules/zone.js/dist/zone.js"></script>
    <script src="node_modules/reflect-metadata/Reflect.js"></script>
    <script src="node_modules/systemjs/dist/system.src.js"></script>

    
    <script src="node_modules/intl/dist/Intl.min.js"></script>
    <script src="node_modules/intl/locale-data/jsonp/en.js"></script>

    
    <script src="node_modules/jquery/jquery.min.js"></script>
    <script src="node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="node_modules/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
    <script src="node_modules/bootstrap-timepicker/js/bootstrap-timepicker.min.js"></script>

    
    <script src="systemjs.config.js"></script>
    <script>
        System.import('app').catch(function(err){ console.error(err); });
    </script>`

systemjs.config.js contents you can see on quickstart page https://angular.io/docs/ts/latest/quickstart.html

After upgrading to RC1 and changing all those scripts the app takes to load more than 11 seconds.

Does anyone see the same behaviour? Is there a workaround? And can I use old Systemjs configuration (as it was for quickstart guide for beta7). 
Thank you!

**Comment by michalstepien** [comment]
Use webpack or systemjs to bundling files.

**Comment by zoechi** [comment]
Looks like a dup of #8542

**Comment by karayv** [comment]
Webpack solved the issue for me.

Thanks to this guide
https://angular.io/docs/ts/latest/guide/webpack.html
