### ISSUE TITLE
Exception when iteration an rxjs observable

### ISSUE THREAD

**Issue by LiorKooz** [angular/angular#8728]
Hi,

In my code I declared an input to view:
`@Input() public chatRoomies: Observable<any>;`

which being initialized at constructor
`this.chatRoomies = Observable.from(['1', '2', '3']);`

I'm trying to display it be iterate it:
` <div *ngFor="let thread of chatRoomies | async">`

I'm getting this exception in console:
**Cannot find a differ supporting object '3' of type 'string'. NgFor only supports binding to Iterables such as Arrays.**

can someone advice how to iterate this observable and display it in the ui?

Thanks,
Lior

**Comment by ericmartinezr** [comment]
Use the `of` operator. `from` will create a sequence per item in the array, meaning that the async pipe will get each item in the array and not the array, which is what it needs. `of` on the other hand will create a sequence with the full array. See the documentation for [from](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/from.md) and [of](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/of.md), and please also read this https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by LiorKooz** [comment]
Thanks ericmartinezr, it worked :)

**Comment by farantesrodrigues** [comment]
you can actually use the toArray method to diff well in ngFor. Something like this :  
`this.chatRoomies = Observable.from(['1', '2', '3']).toArray()`

**Comment by ssougnez** [comment]
Thanks, the "toArray()" fixed it for me.

**Comment by codekraft-studio** [comment]
I've a similar issue using ngFor with `async` pipe, it expects a Observable and so i'm doing this:
```javascript
items: Observable<Array<any>>;

this.myControl.valueChanges
      .debounceTime(250)
      .subscribe( val => {

        let url = `${this.url}/${val}`;

        this.items = this.http.get(url).map(res => {
          console.log( res.json() ) )
          return res.json()
        })
} )
```

The response is a valid array of objects, but I still get this error:
```
ERROR Error: Cannot find a differ supporting object '[object Object]' of type 'object'. 
NgFor only supports binding to Iterables such as Arrays.
```
How should I modify the code? I tried in many ways, thanks in advance!

**Comment by DzmitryShylovich** [comment]
@codekraft-studio 
```
items: Observable<Array<any>>;

this.items = this.myControl.valueChanges
      .debounceTime(250)
      .mergeMap( val => {
        const url = `${this.url}/${val}`;
       return this.http.get(url).map(res => {
          console.log( res.json() ) );
          return res.json()
        })
} )
```

**Comment by codekraft-studio** [comment]
@DzmitryShylovich 
I tried but now is not calling the function when the input  value changes.
can you explain (even shortly) what's happening and why you suggested to use __mergeMap__ instead of __subscribe__ ?

**Comment by jonap51** [comment]
Can anybody help me please.
I have the same problem and I do not know how to solve it. I started very recently and I'm learning from tutorials. But this time I do not know how to fix it.

# todo-routes.js
var express = require('express');
var app = express.Router();
var Todo = require('./todo');

app.get('/todos', (req, res) => {
  Todo.find({}, (err, todos) => {
    if (err)  {
      return res.json({ success: false, message: 'Error while creating Todo', error: err })
    }
    
    res.status(200).send({ success: true, result: todos });
  })
});


#todo-service.js
  public getTodos() {
   return this.http.get (this.apiUrl + 'todos')
   //.map(response => response .json().result);
 }

#Slide7Page.js
export class Slide7Page {
  todos: Observable <any>;

  constructor(public navCtrl: NavController, public navParams: NavParams, public todoService: TodoServiceProvider, public alertCtrl: AlertController, public toastCtrl: ToastController) {
    this.loadTodos();
  }

  loadTodos() {
    this.todos = this.todoService.getTodos();
  }


#Slide7Page.html
<ion-content>
  <ion-list>
    <ion-item-sliding *ngFor="let todo of todos | async">
      <ion-item>
        {{ todo.text }}
      </ion-item>
      <ion-item-options side="right">
        <button ion-button color="danger" (click)="removeTodo(todo._id)">
        <ion-icon name="trash"></ion-icon>
        Delete
      </button>
      </ion-item-options>
    </ion-item-sliding>

  </ion-list>
