### ISSUE TITLE
downgradeNg2Component with multi-transclusion places content only in first ng-content

### ISSUE THREAD

**Issue by Blackbaud-PatrickOFriel** [angular/angular#8729]
**Steps to reproduce and a minimal demo of the problem**
- Downgrade an angular 2 component with multiple `ng-content` nodes and use in an Angular 1 application.
- Observe that all content is placed in the first `ng-content`

See this plunker for an example http://plnkr.co/edit/yLhy7YmppI09xQBHs8ud?p=preview

**Current behavior**
- Downgraded Angular 2 components with multi-transclusion place all content in the first `ng-content`

**Expected/desired behavior**
- Downgraded Angular 2 components with multi-transclusion will place content in the appropriate area

**Other information**

Thanks for your help

**Comment by petebacondarwin** [comment]
Fixed by #12675
