### ISSUE TITLE
A story for accessing the DOM from components

### ISSUE THREAD

**Issue by jbdeboer** [angular/angular#873]
We need a solid story for accessing and manipulating the DOM. Right now, there is ```NgElement```, but it appears to be very rough and not complete (it has a single "getAttribute" method).

In particular, we have a use case where we want to query elements in a component's shadow DOM and then manipulate attributes on that element.

**Comment by mhevery** [comment]
Can you provide a concrete use case? Our current thinking is to provide a special Directive which would run in UI Thread which would have full access to DOM, but most components should not need DOM access.

Have you seen:
- https://github.com/angular/angular/issues/621
- https://github.com/angular/angular/pull/882
- https://github.com/angular/angular/pull/883

**Comment by jbdeboer** [comment]
Seeing that #882 and #883 were filed after this issue, no, I have not seen them. Looking now, they don't seem to be related.

I have provided you a list of our use-cases offline, but here are two to tackle:
1. setting attributes on a component's element (the actual element, not the shadow root)
2. integrating with D3: a component should be able to invoke an external renderer to fill in the shadow root.

**Comment by mhevery** [comment]
I think this is resolved.

* `hostPoperties` are implemented 8ccafb0524e3ac4c51af34ef88e0fe27482336a6
*  `` full dom access is custom renders ada1e642c57f19ad5cecde57db1aca1727bf2325

closing.
