### ISSUE TITLE
bug(newrouter): ngOnInit navigate not working when the component of the current route has a templateUrl

### ISSUE THREAD

**Issue by Nasicus** [angular/angular#8733]
Angular version: 2.0.0 rc1

This may sound a little strange but I found out that `navigate` or `navigateByUrl` doesn't work correctly, when the component of the "current" matching route has a `templateUrl`and not a `template`.

This is the code:

```typescript
import {Component, OnInit} from '@angular/core';
import {Router, Routes, ROUTER_DIRECTIVES, ROUTER_PROVIDERS} from '@angular/router';
import {HomeComponent} from './h.component';
import {LetterComponent} from './l.component';

@Component({
  selector: 'my-app',
  template: '<router-outlet></router-outlet>',
  directives: [ROUTER_DIRECTIVES],
  providers: [ROUTER_PROVIDERS]
})
@Routes([
  { path: '/home', component: HomeComponent },
  { path: '/letter',component: LetterComponent }
])
export class AppComponent implements OnInit {

  constructor(private _router: Router) {
  }

  ngOnInit() {
    this._router.navigate(["/letter"]);
  }

}
``` 

```typescript

import {Component, OnInit} from '@angular/core';

@Component({
  selector: 'my-home',
  // template: `home`, // when it's only a template, the navigate works as expected
  templateUrl : './app/simple.template.html' // when it's a templateUrl, the navigate doesn't work correclty: the url changes, but the content (component) is wrong. Note: simple.template.html, just contains the word 'simple'
})
export class HomeComponent
{
}
```
side note: LetterComponent is as simple as it's get and is therefore omitted.

If you now access your app under `/home` the router will actually change the URL (in the addressbar) to `/letter` however the content which is displayed, is the one of the `HomeComponent`. However if you use a `template` instead of a `templateUrl` in the `HomeComponent` the routing works as expected.

**Comment by zoechi** [comment]
I don't think calling `router.navigate()` in `ngOnInit()` is a good idea. How does it work if you wrap it in `setTimeout(() => this._router.navigate(["/letter"]));`?

**Comment by Nasicus** [comment]
Why not? Just curious...if this is not "recommended" I can live with it.

It does indeed work if you wrap it within `setTimeout`, but only if you add a "big" enough timeout number (it won't work with `1` for example).

**Comment by zoechi** [comment]
I don't know if this is by design but `ngOnInit()` also causes "EXCEPTION: Expression has changed after it was checked." when the model is changed within `ngOnInit()`. It seems `ngOnInit()` is called by Angulars change detection (CD) and CD doesn't like it when CD itself causes model changes (throws above exception). I have seen this with other lifecycle methods (don't remember which exactly).

**Comment by IgorMinar** [comment]
This issue was made obsolete by router v3: https://angularjs.blogspot.com/2016/06/improvements-coming-for-routing-in.html

If you believe this is not the case, please file a new issue updating the description to router v3. thank you!

**Comment by doudbanks** [comment]
Hi there,

I'm facing the same issue even with the router v 3... I'm just trying to redirect at OnInit and the router.navigate returns false but I can't find out why... If I insert it in a setTimeout it works.

If you have any idea it would be appreciated :)

**Comment by DeanWilliamMills** [comment]
I have the same issue. I can't navigate when the page loads, I must first add a click event then the navigation works, but I want to navigate when page loads

**Comment by DzmitryShylovich** [comment]
@doudbanks https://github.com/angular/angular/issues/13795#issuecomment-270659667

**Comment by lawenliu** [comment]
Same issue. But solved with "*ngIf" in corresponding html.
I want to redirect to login page if user doesn't login. I add the the check in ngOnInit function, if user doesn't login, then redirect. If only do this, URL will change, but page is still there.
But after I add "*ngIf" to check my condition in top most tag of corresponding component html, then it works well.
