### ISSUE TITLE
Quickstart Systemjs.config.js content is not correct

### ISSUE THREAD

**Issue by raydeng83** [angular/angular#8735]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here, see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. 

**Steps to reproduce and a minimal demo of the problem**
Just go to https://angular.io/docs/ts/latest/quickstart.html and check on the systemjs.config.js content, which shows "BAD FILENAME: ../../_fragments/quickstart/ts/systemjs.config.1.js.md   Current path: docs,ts,latest,quickstart PathToDocs: ../../"

_Use https://plnkr.co or similar -- try this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5_

_What steps should we try in your demo to see the problem?_

**Current behavior**

**Expected/desired behavior**

**Other information**

**Comment by raydeng83** [comment]
Quickstart Document Issue

**Comment by Osein** [comment]
If anyone still searches for this file I think this is the right one. I didn't received any error with this.

https://gist.github.com/Osein/132353ad85b9fa76fc3bf56bc6931c0e

**Comment by VickyRonnen** [comment]
So a newbie on Angular2 and typescript has to guess which of the two answers is right?
This issue demonstrates that the getting start section is not tested at all. And the one who created this page doesn't care at all.
AngularJS2 is not production ready.

**Comment by cwiki** [comment]
Darn it, I found this after I figured out a quick fix to the problem. 

For those searching for a quick solution they can use.
When you are in the quickstart guide. -- [https://angular.io/docs/ts/latest/quickstart.html]

Go to the first header that says "Try it!" and go to the "live example" link.
Here the code for **systemjs.config.js** is alive and well.

**Comment by zoechi** [comment]
Doc issues should be reported in https://github.com/angular/angular.io

**Comment by VickyRonnen** [comment]
They become censored. Getting started guide for angularjs2 has not been tested at all.The angularjs2 team is lacking any form of quality control.When you plubish a getting started guide it should be checked on a clean vm.Anything not working is an error in the documentation.Documentation is integral part of the software.
Code of conduct should be not to frustrate newbees.


Groet,Vicky Ronnen 

-------- Oorspronkelijk bericht --------
Van: Günter Zöchbauer <notifications@github.com> 
Datum: 22-05-2016  19:47  (GMT+01:00) 
Aan: angular/angular <angular@noreply.github.com> 
Cc: VickyRonnen <v.ronnen@upcmail.nl>, Comment <comment@noreply.github.com> 
Onderwerp: Re: [angular/angular] Quickstart Systemjs.config.js content is not
  correct (#8735) 

Doc issues should be reported in https://github.com/angular/angular.io

**Comment by robwormald** [comment]
Is this still an issue? It appears to work as linked from the original post and resolved on the angular.io end.
