### ISSUE TITLE
Routing requires a router membre in the component

### ISSUE THREAD

**Issue by ssougnez** [angular/angular#8737]
Hi,

I'm new in angular 2, so maybe this is not a bug but just something that I'm wrong about... Basically, I'm trying to use the router in angular2, so I read this tutorial : "https://angular.io/docs/ts/latest/guide/router.html" to get started and it works pretty well. 

Then I realised that, in my code, I didn't really need to redirect the user to a page in the "_AppComponent_", therefore, I removed the "_ngInit_" method and the constructor and then, my routing stopped working and I had no error, just my page with nothing "in the _router-outlet_". No message either in the Chrome console. During my investigation, I noticed that if I added back the constructor:

```
constructor(private router:Router)
{
}
```

It started to work again. I also tried a parameterless constructor but it failed again, so it looks like it was required to have a "Router" member in the component. However, what bothers me a bit is that when I modify the plunker provided by the tutorial and remove the constructor, it continues to work... Anyway, here is my root component:

```
import {Component} from '@angular/core';
import {ROUTER_DIRECTIVES, Routes, Router} from '@angular/router';
import {CompanyComponent} from "../company/company";
import {MissionComponent} from "../mission/mission";
import {HomeComponent} from "../home/home-component";

@Component({
    selector: 'my-app',
    templateUrl: 'app/components/root/template.html',
    directives: [ ROUTER_DIRECTIVES ]
})
@Routes([
    { path: '/', component: HomeComponent },
    { path: '/company', component: CompanyComponent },
    { path: '/missions', component: MissionComponent }
])
export class AppComponent
{
    constructor(private router:Router)
    {
    }
}
```

So, I hope that I didn't just make a stupid mistake and make you all guys lose your time :-D Sorry if it's the case.

**Comment by ericmartinezr** [comment]
It's a bug, see https://github.com/angular/angular/issues/8409

**Comment by ssougnez** [comment]
Oops, my bad. I searched for it before posting nevertheless. 

Thanks

**Comment by zoechi** [comment]
@ssougnez would you mind closing this issue if it is actually a dup of #8409

**Comment by IgorMinar** [comment]
This issue was made obsolete by router v3: https://angularjs.blogspot.com/2016/06/improvements-coming-for-routing-in.html

If you believe this is not the case, please file a new issue updating the description to router v3. thank you!
