### ISSUE TITLE
CLI Should Give More Information About Getting Watchman

### ISSUE THREAD

**Issue by JimTheMan** [angular/angular#8741]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here, see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. 

**Steps to reproduce and a minimal demo of the problem**

The problem occurs for every fresh install through ng init and ng new (on a machine that doesn't have ember cli installed).

_What steps should we try in your demo to see the problem?_
First, you have need to come in from the perspective of someone who doesn't already have ember installed and is starting with Angular 2. Get a new computer, and try to run the Angular project.

**Current behavior**
The command line prints out one subtle line, "Visit http://ember-cli.com/user-guide/#watchman". This makes absolutely no sense. Just "visiting" a url is not going to do anything for my test runner. What's even worse is that this page is not even instructions for how to get watchman for Angular 2, **_it's the getting started guide for ember_**. This is awful since 1) I'm not trying to get started with ember, 2) I don't know how much of the guide to do, 3) I start getting sidetracked and wonder if maybe ember is BETTER than Angular 2...

**Expected/desired behavior**
Just add a page to the Angular docs titled, "Installed Watchman for Angular" and display clearly what to do. If you're just going to put a single link to a webpage, at least make it an Angular page that links to that ember docs page. 

**Other information**

I could help write the doc for it if I could figure it out myself...

**Comment by jeffbcross** [comment]
Can you open an issue on https://github.com/angular/angular-cli?
