### ISSUE TITLE
Component Decorator API Documentation >> Broken

### ISSUE THREAD

**Issue by Stephn-R** [angular/angular#8742]
**Steps to reproduce and a minimal demo of the problem**

https://angular.io/docs/ts/latest/api/core/index/Component-decorator.html

**Current behavior**

The example below mentions a fragment file is missing

**Expected/desired behavior**

An example of how to use the component metadata decorator

**Comment by zoechi** [comment]
Docs issues are maintained in https://github.com/angular/angular.io

**Comment by pkozlowski-opensource** [comment]
Thnx @zoechi
