### ISSUE TITLE
DecimalPipe not working on Safari (OS X and iOS)

### ISSUE THREAD

**Issue by marvin89** [angular/angular#8744]
**Steps to reproduce and a minimal demo of the problem**

http://plnkr.co/edit/21Ac2CcNXBkxzi7p5YyD

You should be able to see the number *22.22* under the default heading.

**Current behavior**

It works on every major browser (Chrome, Firefox, Edge) except for Safari (iOS and OSX). The view does not load at all if there is a DecimalPipe in it.

**Expected/desired behavior**

The pipe should work on Safari exactly as it does for all of the other browsers.

**Other information**

Unfortunately, Plunker fails to load on Safari.
This was experienced during an Ionic2 iOS build and debugged afterwards on Safari OS X.

**Comment by frederikschubert** [comment]
This is due to a missing [polyfill](https://github.com/andyearnshaw/Intl.js/). You can include that in your application and then it should work.

**Comment by marvin89** [comment]
Thanks for the fast reply!

I had to also use [**es6-shim**](https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.35.1/es6-shim.js) to make it work, but now it loads properly, without errors.
I hope a better fix is in the works though.
