### ISSUE TITLE
RC1: ngSwitchWhen alternative does not work

### ISSUE THREAD

**Issue by oodboo** [angular/angular#8746]
This work:
```
        <div [ngSwitch]="active">
            <div *ngSwitchWhen="'test'"></div>
        </div>
```
but this does not:
```
        <div [ngSwitch]="active">
            <div [ngSwitchWhen]="'test'"></div>
        </div>
```
tried variation but no luck:
```
            <div [ngSwitchWhen]="test"></div>
            <div [ngSwitchWhen]="('test')"></div>
```
and according documentation:
https://angular.io/docs/ts/latest/api/common/index/NgSwitch-directive.html
it should ....

**Comment by schippie** [comment]
@oodboo It actually works you are forgetting the <template> tags which are required when you do not use the *ng... shortcut:

http://plnkr.co/edit/QlWvYKmtMjbKH4A1ldOt?p=preview

See: https://angular.io/docs/ts/latest/guide/template-syntax.html#!#star-template

**Comment by oodboo** [comment]
D'oh! ....
