### ISSUE TITLE
angular_1_router doesn't support html5 mode

### ISSUE THREAD

**Issue by jrauschenbusch** [angular/angular#8747]
The angular_1_router currently doesn't support the html5 mode. If i enable it via `$locationProvider.html5Mode(true);` the components will not be initialized. Furthermore no error message is displayed.

**Comment by jrauschenbusch** [comment]
It seems that only **`useAsDefault: true`** is not working properly in html5 mode. But a direct access of routes is still working.

**Comment by jrauschenbusch** [comment]
Ok, my failure. I've activated the html5 mode without a path mapping / to index.html. Hence the internal location.path() lookup doesn't work properly. !

**Comment by zoechi** [comment]
If this is solved, would you mind closing the issue?

**Comment by jrauschenbusch** [comment]
Sorry for the delayed answer. My mobile GitHub client wasn't able to close any issue. Hence i make it for now.
