### ISSUE TITLE
RC1:  ngSwitch without wrapping element?

### ISSUE THREAD

**Issue by oodboo** [angular/angular#8748]
Is it possible to have ngSwitch without wrapping element that will be rendered?

```
    <div [ngSwitch]="value">
      <p *ngSwitchWhen="'init'">increment to start</p>
      <p *ngSwitchWhen="0">0, increment again</p>
    </div>
```
I am trying to find a solution where the DIV will not be rendered ...

For now only solution I could think of is to use *ngIF ... is there any other way?

**Comment by michalstepien** [comment]
Hi, template doesent work?

**Comment by tycho01** [comment]
To elaborate on michalstepien's answer, `template` is an 'element' that doesn't generate an element in the DOM. That'd make:

    <element [ngSwitch]="value">
      <p *ngSwitchWhen="'init'">increment to start</p>
      <p *ngSwitchWhen="0">0, increment again</p>
    </element>

**Comment by oodboo** [comment]
@michalstepien does not ...
@tycho01  will render <element> tag like this :
```
<element>
        <!--template bindings={}--><p>increment to start</p>
        <!--template bindings={}-->
</element>
```

**Comment by tycho01** [comment]
Whoops! Updated my comment.

**Comment by oodboo** [comment]
@tycho01 
in this form does not work 
```
<template [ngSwitch]="value">
or in this form 
<template ngSwitch="value">
```
.... and we can use it with *ngSwitch

**Comment by tycho01** [comment]
Hm, my code uses `[ngSwitchWhen]` rather than `*ngSwitchWhen`. That aside, it turns out I still had the original `div` in there in my own code too...

**Comment by michalstepien** [comment]
@oodboo , yes you are right, It doesent work. Look at this issue: https://github.com/angular/angular/issues/3306

**Comment by zoechi** [comment]
dup of #3306

**Comment by vicb** [comment]
```
    <ng-container [ngSwitch]="value">
      <p *ngSwitchWhen="'init'">increment to start</p>
      <p *ngSwitchWhen="0">0, increment again</p>
    </ng-container>
```

IIRC there is an issue on angular.io for adding it to the doc

**Comment by AviwT** [comment]
It's possible to just create a "virtual" container, which will not be rendered:
`<ng-template [ngSwitch]="itemType">`
