### ISSUE TITLE
Component 'e' does not have route configuration

### ISSUE THREAD

**Issue by ruffiem** [angular/angular#8749]
Hi everyone,

I can't make the new router work, I tried pretty much everything but it looks like it just won't work. I keep having this error

> EXCEPTION: Error: Uncaught (in promise): Component 'e' does not have route configuration

** Screenshot **
![screen shot 2016-05-20 at 17 32 50](https://cloud.githubusercontent.com/assets/1785492/15433045/eb8b005e-1eb0-11e6-9bf7-483e5177add3.png)

**My component**
```Javascript
import { Component } from '@angular/core'
import { Routes, Router, ROUTER_DIRECTIVES } from '@angular/router'

import { User } from '../../models/user.model'
import { SearchComponent } from '../../../components/search/search.component'

@Routes([
  { path: '/search', component: SearchComponent }
])

@Component({
  selector: 'sidebar',
  templateUrl: './app/shared/layout/sidebar/sidebar.html',
  directives: [ ROUTER_DIRECTIVES ]
})

export class SidebarComponent {

  constructor (private router: Router) { }

  goTo(way) {
    this.router.navigate([way]);
  }
}
```

**My HTML**
```Html
<a [routerLink]="['/search']">Go</a>
<button class="btn btn-primary" (click)="goTo('/search')">Go</button>
<router-outlet></router-outlet>
```

And ROUTER_PROVIDERS is loaded in main.js...

What am I doing wrong ?

Thanks

**Comment by michalstepien** [comment]
@ruffiem ,Hi, can you provide plunkr?

**Comment by ericmartinezr** [comment]
>What am I doing wrong ?

As said, you're not providing a reproduction. There are similar issues around, and you see that message because of minification most likely.

**Comment by ruffiem** [comment]
Thank for your answer. Good lookin @ericmartinezr, without minification, the error output is "KernelComponent" does not have a route configuration but it does have one.

Plunkr there : http://plnkr.co/edit/4BvicN3jero8EfbNYJpx?p=preview

It doesn't work but the logic's there... Thank you 👍

**Comment by ruffiem** [comment]
Can't route to kernel, sorry folks but thanks to put me in the right direction
