### ISSUE TITLE
typings: upgrade to 1.x

### ISSUE THREAD

**Issue by vance** [angular/angular#8754]
**Steps to reproduce and a minimal demo of the problem**

do the quickstart guide. the typings.json file has "ambient" instead of "global" as the prefix. 
```
{
  "globalDependencies": {
    "es6-shim": "registry:dt/es6-shim#0.31.2+20160317120654",
    "jasmine": "registry:dt/jasmine#2.2.0+20160412134438",
    "node": "registry:dt/node#4.0.0+20160509154515"
  }
}
```

_What steps should we try in your demo to see the problem?_

**Current behavior**
typings thinks there's no dependencies because it's looking for global

**Expected/desired behavior**
installs as expected

**Other information**
please refer to the new typings readme.md  update.

**Comment by alexeagle** [comment]
quickstart lives in the angular.io repo, so moved this issue there.
