### ISSUE TITLE
API link is broken => 404

### ISSUE THREAD

**Issue by bastienJS** [angular/angular#8756]
https://angular.io/docs/ts/latest/api/router/index/RouteMetadata

**Comment by Trendy** [comment]
I don't the that the documentation has been completed for RouteMetaData in the RC1 router just yet.

**Comment by wesleycho** [comment]
This should be reported at https://github.com/angular/angular.io/issues - this issue queue is for the framework itself.

**Comment by pkozlowski-opensource** [comment]
Obsolete. RouteMetadata is not part of the new-new router
