### ISSUE TITLE
Angular 2 (keyup) event would not work when  Input type="number" and if you use touchpad.  (HTML 5 gives Special option to move numbers up and down ),<input #box (keyup)="0" type="number">     <p>{{box.value}}</p>

### ISSUE THREAD

**Issue by DhananjayaG** [angular/angular#8763]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here, see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. 

**Steps to reproduce and a minimal demo of the problem**

_Use https://plnkr.co or similar -- try this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5_

_What steps should we try in your demo to see the problem?_

**Current behavior**

**Expected/desired behavior**

**Other information**

**Comment by wesleycho** [comment]
The keyup event is reserved for when a user lifts their finger from a key - it sounds like you mean to use the `input` event.

**Comment by pkozlowski-opensource** [comment]
Thnx @wesleycho
