### ISSUE TITLE
ngClass and ng-content not working together

### ISSUE THREAD

**Issue by luisvt** [angular/angular#8765]
version: 2.0.0-alpha.17
language: dart

**Steps to reproduce and a minimal demo of the problem**

I have next component code:
```dart
@Component(selector: 'bs-progress',
    template: '''
    <progress [max]="max" [value]="value"></progress>
    <label id="label"><ng-content></ng-content></label>
    ''')
class Progress implements OnInit {
  /// if `true` changing `value` of progress bar will be animated (*note*: not supported by Bootstrap 4)
  @Input() bool animate = true;

  /// maximum value of the bar
  @Input() num max;

  /// value of the progress bar
  @Input() num value;

  /// initialize the attributes
  ngOnInit() {
    animate ??= true;
    max = max ??= 100;
  }
}
```

when I use it like this:
```html
<bs-progress class="striped" [value]="value" ngClass="{{type}}">Some Content</bs-progress>
```
content is not rendered. However if I remove `ngClass` attr, content is rendered again.

_What steps should we try in your demo to see the problem?_
* remove `ngClass` attr
* put `[ngClass]="type"` instead `ngClass={{type}}`

**Current behavior**
The rendered content is as fallow:
```html
<bs-progress class="warning">
  <progress value="50" max="100"></progress>
  <label id="label"></label>
</bs-progress>
```

**Expected/desired behavior**
The rendered content should be:
```html
<bs-progress class="striped warning">
  <progress value="50" max="100"></progress>
  <label id="label">Some Content</label>
</bs-progress>
```

**Other information**
if we remove `ngClass` attr the rendered content is:

```html
<bs-progress class="striped">
  <progress value="50" max="100"></progress>
  <label id="label">Some Content</label>
</bs-progress>
```

It looks this bug is related to:
https://github.com/angular/angular/issues/7384

However I would like a confirmation

**Comment by NZSmartie** [comment]
I can confirm I'm experiencing this issue as well with `2.0.0-beta.17`

**Comment by zoechi** [comment]
What value does `type` have in `ngClass="{{type}}"` and where does it come from. I can't find `type` anywhere.
I don't think it's related to #7384. #7384 is about more than one `<ng-content>` tag rendered by `*ngFor`
I assumed `warning` for `type`.
It's working in RC.1 TS https://plnkr.co/edit/3JQPgTwGttkAMPTiABOa?p=preview

**Comment by pkozlowski-opensource** [comment]
Agree with @zoechi that isn't related to #7384 at all. Moreover it works correctly in a plunker provided by @zoechi and it still works in rc.2: https://plnkr.co/edit/tLrYVGWtmFqiz6Avh6oD?p=preview

Going to close this one as we don't have any evidence of things being broken. Happy to re-open if / when we've got a plunker with a reproduce scenario in rc.2
