### ISSUE TITLE
Angular Dart component tests hang on initAngularTests();

### ISSUE THREAD

**Issue by sanfordredlich** [angular/angular#8767]
To make a really generic app, I installed the Angular template app from Dart, then added only these pub_spec.yaml dependencies
--------------------------
  **test: any
  angular2_testing: any**

This is the complete test code
--------------------------
@TestOn('browser')
import 'package:test/test.dart';
import 'package:angular2_testing/angular2_testing.dart';

void main() {
  initAngularTests();

  test('normal function', () {
    var string = 'foo,bar,baz';
    expect(string.split(','), equals(['foo', 'bar', 'baz']));
  });
}

Running the test hangs with no output:
--------------------------
| ~/WebstormProjects/untitled3 @ Sanfords-MBP (sanford) 
| => pub run test -p content-shell --verbose-trace
03:14 +0: loading test/app_component_test.dart     

Could it be my Dart? I reinstalled Dart:
--------------------------
| ~/WebstormProjects/untitled3 @ Sanfords-MBP (sanford) 
| => brew uninstall --force dart
Uninstalling dart... (972 files, 64.2M)

| ~/WebstormProjects/untitled3 @ Sanfords-MBP (sanford) 
| => brew install dart --with-dartium --with-content-shell
==> Installing dart from dart-lang/dart
==> Downloading https://storage.googleapis.com/dart-archive/channels/stable/release/1.16.0/sdk/dartsdk-macos-x64-release.zip
Already downloaded: /Library/Caches/Homebrew/dart-1.16.0.zip
==> Downloading https://storage.googleapis.com/dart-archive/channels/stable/release/1.16.0/dartium/dartium-macos-ia32-release.zip
Already downloaded: /Library/Caches/Homebrew/dart--dartium-1.16.0.zip
==> Downloading https://storage.googleapis.com/dart-archive/channels/stable/release/1.16.0/dartium/content_shell-macos-ia32-release.zip
Already downloaded: /Library/Caches/Homebrew/dart--content_shell-1.16.0.zip
==> Caveats
Please note the path to the Dart SDK:
  /usr/local/opt/dart/libexec

--with-dartium:
  To use with IntelliJ, set the Dartium execute home to:
    /usr/local/opt/dart/Chromium.app

.app bundles were installed.
Run `brew linkapps dart` to symlink these to /Applications.
==> Summary
🍺  /usr/local/Cellar/dart/1.16.0: 1,212 files, 480.1M, built in 9 seconds

| ~/WebstormProjects/untitled3 @ Sanfords-MBP (sanford) 
| => brew linkapps dart
Linking: /usr/local/opt/dart/Chromium.app
Linking: /usr/local/opt/dart/Content Shell.app
Linked 2 apps to /Applications

| ~/WebstormProjects/untitled3 @ Sanfords-MBP (sanford) 
| => pub run test -p content-shell --verbose-trace
00:54 +0: loading test/app_component_test.dart                                                     

No change:
----------------
| ~/WebstormProjects/untitled3 @ Sanfords-MBP (sanford) 
| => pub run test -p content-shell --verbose-trace
05:00 +0 -1: loading test/app_component_test.dart                                                  
  TimeoutException after 0:05:00.000000: Test timed out after 5 minutes, 5 seconds.

Other notes
-----------------
* Dartium does launch from the command line
* pub run test returns (but no tests are run, naturally, since there's no browser and the only test needs one)
* pub run test -p dartium hangs like this, so does pub run test -p content-shell
* also fails with the unchanged [Angular example](https://raw.githubusercontent.com/angular/angular/master/modules_dart/angular2_testing/test/angular2_testing_test.dart)

Library versions used
-----------------
Resolving dependencies...
  analyzer 0.27.3 (0.27.4-alpha.6 available)
  angular2 2.0.0-beta.17
  angular2_testing 2.0.0-beta.17
  args 0.13.4+2
  async 1.11.0
  barback 0.15.2+8
  boolean_selector 1.0.1
  browser 0.10.0+2
  build 0.3.0+2
  charcode 1.1.0
  cli_util 0.0.1+2
  code_transformers 0.4.2+2
  collection 1.7.0
  convert 1.1.1
  crypto 0.9.2+1 (1.1.1 available)
  csslib 0.13.2
  dart_style 0.2.4
  dart_to_js_script_rewriter 1.0.1
  fixnum 0.10.5
  func 0.1.0
  glob 1.1.2
  html 0.12.2+2 (0.13.0 available)
  http_multi_server 2.0.1
  http_parser 3.0.1
  intl 0.12.7+1 (0.13.0 available)
  logging 0.11.3
  matcher 0.12.0+2
  mime 0.9.3
  observe 0.13.5
  package_config 0.1.3
  path 1.3.9
  petitparser 1.5.3
  plugin 0.1.0 (0.2.0 available)
  pool 1.2.4
  protobuf 0.5.1 (0.5.1+2 available)
  pub_semver 1.2.4
  shelf 0.6.5+2
  shelf_static 0.2.3+4
  shelf_web_socket 0.2.1
  smoke 0.3.6+2
  source_map_stack_trace 1.0.4
  source_maps 0.10.1+1
  source_span 1.2.2
  stack_trace 1.6.5
  stream_channel 1.4.0
  string_scanner 0.1.4+1
  test 0.12.13+4
  typed_data 1.1.3
  utf 0.9.0+3
  watcher 0.9.7+2
  web_socket_channel 1.0.3
  when 0.2.0
  which 0.1.3
  yaml 2.1.9

**Comment by zoechi** [comment]
Have you tried without Angular. It might be a `pub` or `test` issue instead of an Angular issue

**Comment by sanfordredlich** [comment]
Thanks, yes. This passes immediately:

@TestOn('browser')
import 'package:test/test.dart';
//import 'package:angular2_testing/angular2_testing.dart';

void main() {
  //initAngularTests();

  test('normal function', () {
    var string = 'foo,bar,baz';
    expect(string.split(','), equals(['foo', 'bar', 'baz']));
  });
}


This times out:

@TestOn('browser')
import 'package:test/test.dart';
import 'package:angular2_testing/angular2_testing.dart';

void main() {
  //initAngularTests();

  test('normal function', () {
    var string = 'foo,bar,baz';
    expect(string.split(','), equals(['foo', 'bar', 'baz']));
  });
}


That is, simply importing angular2_testing.dart' gives me the timeout.

| ~/WebstormProjects/untitled3 @ Sanfords-MacBook-Pro (sanford)

| => pub run test -p content-shell --verbose-trace

05:00 +0 -1: *loading test/app_component_test.dart*

TimeoutException after 0:05:00.000000: Test timed out after 5 minutes,
5 seconds.

**Comment by ntaoo** [comment]
I guess you forgot to start up `pub serve` for browser testing, and also forgot adding `--pub-serve=8081` option.

I uploaded the working example.
[https://github.com/ntaoo/angular2_testing_example](https://github.com/ntaoo/angular2_testing_example)
