### ISSUE TITLE
ngLoaded lifecycle hook ?

### ISSUE THREAD

**Issue by ssougnez** [angular/angular#8768]
Hi,

**Steps to reproduce and a minimal demo of the problem**

I'm having a component called "_HomeComponent_" with a view that contains a "_RibbonComponent_". As you have guessed, the "_RibbonComponent_" is just a component that I'm building used to render a "_Office Ribbon_". In the "_ngOnInit_" of "_HomeComponent_", I set the property "_tabs_" and "_contextualTab_" of it. These two properties are bound to the "_RibbonComponent_" like this:

`<ribbon [tabs]="tabs" [contextualTabs]="contextualTabs"></ribbon>`

This works and display a ribbon with two tabs. However, I'd like to call the method "_setActiveTab_" of "_RibbonComponent_" from "_HomeComponent_". Therefore, I did this:

```
@ViewChild(RibbonComponent)
private ribbon:RibbonComponent;

ngAfterViewChecked()
{
    this.ribbon.setActiveTab(this.tabs[0]);
}
```

However, this is not well received by angular2 :-D

The "setActiveTab" is just looping through the "_tabs_" array and set the "_active_" property to "_true_" for the tab I want to set as active (and "_false_" for the other ones). Actually, I don't get any error, but the view of "_RibbonComponent_" does not get updated. However, I also have a hook on the click event of each tab and if I execute the "_setActiveTab_" from this hook, the view gets refreshed.

Therefore, I'm guessing that "_ngAfterViewChecked_" is not the correct hook to modify a child control. Indeed, if on the top of that, I modify a member of "_RibbonComponent_" in "_setActiveTab_", I get an error (_Expression has changed after it was checked. Previous value: 'undefined'. Current value: '[object Object]'_) when this is called from "_ngAfterViewChecked_".

Therefore, I checked the [documentation](https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html) and it appears that there is not really a hook that I can use to execute instructions when the view is loaded/stabilized.

For my problem, I could of course modify the constructor of my "_Tab_" class to be able to define the "_active_" property on it, but I'm still interested by the manner to do what I just mentioned.

It could be that there is a way that I don't know of (I'm quite new in ng2), but if there is, I'm surprised that it is not mentioned in the documentation.

**Current behavior**

I don't have a hook where I can execute instructions when the component is totally loaded/stabilized.

**Expected/desired behavior**

I expect to have a hook to execute instructions when the component is totaly loaded/stabilized.

**Other information**

The closest I've been to a solution is by adding an "_EventEmitter_" in the "_RibbonComponent_" and emits this one in "_ngAfterViewInit_". Then I bound this event to a method in the "_HomeComponent_" and, in this one, I call the "_setActiveTab_" method. It works but I think that it would be more straightforward with a "_ngOnLoaded_" hook :-D

**Comment by zoechi** [comment]
Angular change detection doesn't like changes to happen in lifecycle methods. Just wrap the code that mutates the model in `setTimeout(() => {...})` to schedule it to be executed after change detection cycle is completed. `setTimeout()` also notifies Angular to run change detection after the callback was executed.

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by ssougnez** [comment]
Well, I don't know if you read my post entirely, but the bottom line was about asking a new feature: the "_ngLoaded_" life cycle hook...

For the "_setTimeout_" solution, it looks a bit like a dirty workaround, but thanks for the proposition.

**Comment by zoechi** [comment]
I don't see why `setTimeout` would be a hack. It's just scheduling code to be executed after the current content of the event queue is processed.

**Comment by pkozlowski-opensource** [comment]
I think this is a pb of approach to building tabs component. If we would allow model changes after view was checked this would have schedule another change detection loop and we would be back to the same algorithm as in ng1.

If you want to have a look at a tabs implementation example that doesn't suffer from those circular checks have a look at: https://github.com/ng-bootstrap/core/blob/master/src/tabset/tabset.ts
