### ISSUE TITLE
not all ngFor generated components are destroyed

### ISSUE THREAD

**Issue by ribizli** [angular/angular#8771]
http://plnkr.co/edit/0pLzZGjOPxBVb9mDAWT9?p=preview

_What steps should we try in your demo to see the problem?_

click 'toggle' button and see in console that only 5 components of 10 are destroyed (aka ngOnDestroy called)

**Current behavior**
Not all component's `ngOnDestroy` is called.

**Expected/desired behavior**
Should be called all.

**Other information**

**Comment by zoechi** [comment]
Probably a dup of #8458

**Comment by ribizli** [comment]
Yes, I close this, thanks.
