### ISSUE TITLE
Returning a promise as the result of a $http then causes a weird behavior when said promise is cancelled

### ISSUE THREAD

**Issue by odedniv** [angular/angular#8774]
**Steps to reproduce and a minimal demo of the problem**

* Simple case with just `$q`: https://jsfiddle.net/fvdgsjoL/2/

1. Create a promise (A).
2. Return a second promise (B) as a result of a function given to the `then` of promise A.
3. Resolve promise A (either before or after 4, doesn't happen otherwise).
4. Cancel promise B.

* Real scenario with `$http` and `$timeout`: https://jsfiddle.net/4ao7cw31/3/

1. Create $http request.
2. Return a $timeout as a result of a function given to the `then` of a $http request (done by mistake, CoffeeScript).
3. Cancel the timeout at some point.

**Current behavior**

Promise A (the $http request) is rejected with whatever was given to the `reject()` of promise B ("canceled" in case of canceling a `$timeout`), even though it was already resolved.

**Expected/desired behavior**

This is very confusing and was hard to track down. Could not figure out where the `catch`'s response was coming from or how it is possible for both the `then` and `catch` to be called.

Not sure this is documented or expected.

**Other information**

Angular 1.4.8.

**Comment by ericmartinezr** [comment]
@odedniv this repo is for ng2, you're looking for this one https://github.com/angular/angular.js =P
