### ISSUE TITLE
(docs) Document best practices on clean up after using Http services

### ISSUE THREAD

**Issue by nareshbhatia** [angular/angular#8775]
Reading the docs, it's not clear how to clean up after using Http services. Calling `Http.get()`, `Http.post()` etc. creates observables. Subscribing to these observables creates subscriptions. Do these observables and subscriptions have to be cleaned up manually? Most examples in the docs do nothing. Here's an example from the [style guide](https://angular.io/docs/ts/latest/guide/style-guide.html#!#style-05-15):

    getHeroes() {
        this.heroes = [];
        this.http.get(heroesUrl)
            .map((response: Response) => <Hero[]>response.json().data)
            .catch(this.catchBadResponse)
            .finally(() => this.hideSpinner())
            .subscribe((heroes: Hero[]) => this.heroes = heroes);
    }

As far as I can tell, every time `getHeros()` is called, a new observable and a new subscription is created. It is not clear if they are being cleaned up.

**Comment by zoechi** [comment]
If it's not assigned to a variable, it will get garbage collected. If you assign it to a variable it will get GCed when the class gets GCed where the variable is stored. This is IMHO general programming knowledge and not specific to Angular2. I also don't think everything Rx needs to be documented by Angular just because Angular uses Rx. 
Just my 2c. I'm not a member of the Angular team.

**Comment by nareshbhatia** [comment]
@zoechi, thanks for your thoughts. What you are saying is absolutely correct - in most cases GC will take care of the cleanup. I am concerned about corner cases where that may not happen. For example (not specific to Angular), we can get into tricky situations when event handlers refer to variables in their closure scope. I agree that this is general JS knowledge, but with several places in the docs talking about unsubscribing from Observables, it may be worth putting a sentence or two saying that it is not generally required. Just a suggestion, please feel free to close if this is generally clear.

**Comment by ross-nordstrom** [comment]
Good to know this isn't an issue in Services!

I think this is a really valid question, given that you need to manually cleanup your Subscription in Components, as [described in the docs for `ngOnDestroy`](https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html#!#lifecycle-sequence)

> ngOnDestroy	

> Cleanup just before Angular destroys the directive/component. **Unsubscribe observables** and detach event handlers **to avoid memory leaks.**

> Called just before Angular destroys the directive/component.

I've become so hard-coded to check for `unsubscribe` in Components, that I get code-smell false positives anytime I'm looking at RxJS code in Services.

I think this is worth mentioning in the Services docs that **unlike Components,** you don't need to cleanup after yourself.

**Comment by DzmitryShylovich** [comment]
https://medium.com/@benlesh/rxjs-dont-unsubscribe-6753ed4fda87#.gdc1qkg9f

@vicb I think you can close this.

**Comment by vicb** [comment]
thanks!
