### ISSUE TITLE
The extended strategy could not inject the own provider

### ISSUE THREAD

**Issue by armorik83** [angular/angular#8777]
Hi.

http://plnkr.co/edit/kRLoIs92mHihxeKa8ncS?p=preview

In 2.0.0-rc.1.

**Current behavior**
```ts
@Injectable()
class MyService {
  foo(): string {
    return 'foo';
  }
}

@Injectable()
export class MyHashLocationStrategy extends HashLocationStrategy {

  constructor(private __platformLocation: PlatformLocation,
              MyService: MyService,
              @Optional() @Inject(APP_BASE_HREF) _baseHref: string) {
    super(__platformLocation, _baseHref);
    debugger;
    console.log(MyService.foo());
  }
}

bootstrap(App, [
  ROUTER_PROVIDERS,
  MyService,
  provide(LocationStrategy, {useClass: MyHashLocationStrategy})
])
  .catch(err => console.error(err));
```

```
TypeError: Cannot read property 'foo' of null
```

**Expected/desired behavior**

It should be correctly DI to `MyService` in `class MyHashLocationStrategy extends HashLocationStrategy`.

Thanks.

**Comment by zoechi** [comment]
You provide an alternative class for `LocationStrategy` (with `provide(LocationStrategy, {useClass: MyHashLocationStrategy})`)?. If you inject `PlatformLocation` this doesn't take effect, only when you inject `LocationStrategy`

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by armorik83** [comment]
I'd like to inject `MyService` to `MyHashLocationStrategy`. I think it's a bug. Or, can't we inject own providers when bootstrapping?

**Comment by laco0416** [comment]
I think this issue relates #11606 as parameter decorator inheritance
