### ISSUE TITLE
Feature Request: $compile alternative API

### ISSUE THREAD

**Issue by laco0416** [angular/angular#8778]
I want `$compile` alternative API in Angular 2.

## Use-case

```
@Component({
  selector: "app",
  template: `
    <app-shell>
      <app-content [src]="content"></app-content>
    </app-shell>
  `
})
class AppComponent {
  content: string;

  ngOnInit() {
    this.http.get('/api/app-content')
      .map(resp => resp.json())
      .subscribe(data => {
        this.content = data.template; // HTML as string
      });
  }
}
```

When I use `innerHTML` property to apply my HTML to `<app-content>`, standard HTML elements work  well, but any directives/components don't work.

I want to load **a template which contains ng2 directives/components**.

**Comment by zoechi** [comment]
Looks like a dup of #7596

**Comment by laco0416** [comment]
@zoechi Thank you! I'll watch that issue.
