### ISSUE TITLE
RC1: Continuous comment will cause a template failure

### ISSUE THREAD

**Issue by oodboo** [angular/angular#8782]
Writing comments as continuous line will cause template to fail:

```
            <!--|------------------------------------------------->
            <!--|------------------------------------------------->
```
but if you put space at second line it will not:
```
            <!--|------------------------------------------------->
            <!--|----------------------------------------------- -->
```

this is the error:
```
EXCEPTION: Template parse errors:
Unexpected character "EOF" ("
        </div>
    </div>
</div>[ERROR ->]"): TasksComponent@43:6
```

**Comment by zoechi** [comment]
The comments are invalid. See https://www.w3.org/TR/html-markup/syntax.html#comments

> ...
> must not contain the string "--"
> must not end with a "-" character

**Comment by oodboo** [comment]
@zoechi hasn't that been change in html5 ?!

**Comment by zoechi** [comment]
@oodboo do you know a better Link. I'm never sure what version a w3.org link is about.

**Comment by oodboo** [comment]
@zoechi just updated sorry ...

**Comment by zoechi** [comment]
Looks the same to me 

>  ... nor start with a U+002D HYPHEN-MINUS character (-) followed by a ">" (U+003E) character, nor contain two consecutive U+002D HYPHEN-MINUS characters (--), nor end with a U+002D HYPHEN-MINUS character (-).

**Comment by oodboo** [comment]
I will need a pair of glasses ... thanks ...
