### ISSUE TITLE
Angular doesn't recognize immutable-js iterable objects anymore in IE11

### ISSUE THREAD

**Issue by AntanasBarauskas** [angular/angular#8784]
In version rc.1 angular doesn't recognize iterable objects in IE 11 anymore from immutable-js and possibly other libraries as well. As a result `*ngFor` isn't working and angular throws an exception _"Cannot find a differ supporting object 'List'..."_ when immutable List is passed in. This worked before (angular beta.16) because older version of rxjs used to populate global scope with `Symbol` implementation for IE 11. They dropped this recently: https://github.com/blesh/RxJS/commit/0d33d3b8b550feee095ba2ac2b61dac1af121974

**Steps to reproduce:**

This problem is reproducible by using starter project and adding immutable-js. Just create immutable list and try passing it in for `*ngFor` in the view, like: `*ngFor="let listItem of immutableList"`.

[Example project](https://github.com/AntanasBarauskas/angular-immutable-list-test/)

**Whats wrong:** 

From what i've managed to find, angular recognizes iterable objects by checking if they are simple array objects or have an iterator method. This is done in method `isListLikeIterable(obj)`:

```javascript
function isListLikeIterable(obj) {
 if (!lang_1.isJsObject(obj))
      return false;
  return lang_1.isArray(obj) 
             || (!(obj instanceof exports.Map) && lang_1.getSymbolIterator() in obj);
}
```

After es6-shim library is included, _"iterator"_ method name in IE 11 (result of `lang_1.getSymbolIterator()`) becomes `'_es6-shim iterator_'`. It is resolved by iterating threw `Map.prototype` keys in rxjs. And `Map` implementation is already altered by es6-shim, which sets method name to `'_es6-shim iterator_'`. The problem is that other libraries, when `Symbol` implementation is not provided, are defaulting to method name `'@@iterator'`.

Implementation of `getSymbolIterator()`:

```javascript
// AB: Condition 'typeof Symbol === 'function'' is skipped, since IE 11 doesn't have 
//     implementation for Symbol.
if (typeof Symbol === 'function') { 
    ...
}
else {
    if (root_1.root.Set && typeof new root_1.root.Set()['@@iterator'] === 'function') {
        // Bug for mozilla version
        exports.$$iterator = '@@iterator';
    }
    // AB: This part is beeing hit, since es6-shim populates Map implementation.
    else if (root_1.root.Map) { 
        // es6-shim specific logic
        var keys = Object.getOwnPropertyNames(root_1.root.Map.prototype);
        for (var i = 0; i < keys.length; ++i) {
            var key = keys[i];
            if (key !== 'entries' && key !== 'size' && root_1.root.Map.prototype[key] === root_1.root.Map.prototype['entries']) {
                exports.$$iterator = key; // AB: Exported key is '_es6-shim iterator_'
                break;
            }
        }
    }
    else {
        exports.$$iterator = '@@iterator';
    }
}
```

So at this point angular knows that iterable objects have `'_es6-shim iterator_'` method, but other libraries like immutable-js are defaulting to `'@@iterator'` and create objects that have `'@@iterator'` implemented instead of `'_es6-shim iterator_'`. In the end angular doesn't recognize that the object is iterable and cannot find a differ for it.

**Comment by tine2k** [comment]
Try [core.js](https://github.com/zloirock/core-js) instead of es6-shim. This seems to be a good idea anyway since Angular2 now uses core.js as a dependency and drops es6-shim. Have a look at #5755 to get background info.

**Comment by vicb** [comment]
> Try core.js instead of es6-shim

Does this fix your issue ?

If not please include a small repro with latest angular version. Thanks.

**Comment by AntanasBarauskas** [comment]
Yes, issue doesn't occur when core.js is used. Closing.
