### ISSUE TITLE
Plunkr url in issue template not working

### ISSUE THREAD

**Issue by Fank** [angular/angular#8786]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here, see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. 

**Steps to reproduce and a minimal demo of the problem**

_Use https://plnkr.co or similar -- try this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5_

_What steps should we try in your demo to see the problem?_

**Current behavior**
http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5_ in issue template can't be open, plnkr say its invalid

**Expected/desired behavior**
A working example

**Other information**

**Comment by zoechi** [comment]
I can't reproduce. I don't get an error.

**Comment by mlaval** [comment]
I can't reproduce neither when using the correct url (i.e. the one without a trailing underscrore).
