### ISSUE TITLE
updateValue in a ControlGroup does not update validator classes

### ISSUE THREAD

**Issue by Fank** [angular/angular#8787]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here, see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. 

**Steps to reproduce and a minimal demo of the problem**

_Use https://plnkr.co or similar -- try this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5_

_What steps should we try in your demo to see the problem?_

**Current behavior**
By updating a value in a `Control` via `updateValue`, which will isn't valid, will run validator. `error` and `valid` property will be set.
```
error: ...
valid: false
```

But the classes which came from the `NgControlStatus` directive, won't be updated.
So the `valid` property is `false` and the html class is `ng-valid`.

If i interact with the control in the view changedetection will trigger and update the class to `ng-invalid`

**Expected/desired behavior**
A value update in the controller/component should trigger the `NgControlStatus` to update the classes in the view.

**Other information**
Will add a plunkr if #8786 is fixed

**Comment by ericmartinezr** [comment]
go to http://plnkr.co/ > launch editor > new > angularjs > 2.0.x (ts), that has the official template.

**Comment by Fank** [comment]
Hm plnkr works fine, looks like something with our code is wrong
