### ISSUE TITLE
Route throws 404 error when refreshed 

### ISSUE THREAD

**Issue by liongoncalves** [angular/angular#8788]
_What steps should we try in your demo to see the problem?_
Go to any route different form home and refresh 

**Current behavior**
When you are on any route different from / (for example /home, /products/1234) and you refresh the page, a 404 error appear.

**Expected/desired behavior**
It should go to the route.

**Other information**
I think i because de new Router comes with the HTML5 mode enable by default, but I'm trying to switch back to the HashLocation mode and I simply can't. And well the documentation is way out of date.

**Comment by zoechi** [comment]
The issue should at least contain the code that demonstrates what you tried.
The docs are work in progress. It's possible that they are not yet fully up-to-date.

If you can't switch to `HashLocationStrategy` then this seems to apply:

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by ssougnez** [comment]
Note that if you're using a simple server such as "_http-server_" or even something like "_wamp_" without any configuration, the problem is normal. Indeed, when you access the homepage, your "_index.html_" is automatically loaded, but if you access something like "_http://url/part1_", the server will look for a folder "_part1_" that contains an "_index.html_" page => error 404.

If this is indeed the issue you have, I would advise you to use "_lite-server_" which redirect redirect to "_index.html_" without any configuration.

**Comment by liongoncalves** [comment]
In fact I tried to switch to HashLocationStrategy, but i think is not yet implemented in the new router. So that’s the problem. I guess I have to look for another solution. 

Still thanks for your response and sorry to bother.

**Comment by dloukadakis** [comment]
HashLocationStrategy is implemented check:
https://angular.io/docs/js/latest/api/router/HashLocationStrategy-class.html

You need this part to switch to it:
```
bootstrap(AppCmp, [
  ROUTER_PROVIDERS,
  provide(LocationStrategy, {useClass: HashLocationStrategy})
]);
```

Check also #8521 for more info.

**Comment by liongoncalves** [comment]
Yeah i checked that. But the documentation is old (the new documentation is in progress). The “@angular2/router” doesn’t have that component. And the old version “@angular2/router-deprecated” doesn’t have it either.

So i think for now that is not working/not implemented

**Comment by zoechi** [comment]
This just needs different imports since a while. The changelog contains the changes. See also http://stackoverflow.com/questions/36861628/location-and-hashlocationstrategy-stopped-working-in-beta-16
If you had provided your code (as Plunker for example) your problem would probably be fixed since hours.

**Comment by robwormald** [comment]
This has nothing to do with Angular, per se - if you refresh the page, the request goes to the server before angular is even in the picture, so your server has to handle the request - typically it should just serve the index.html page for all routes, and then angular's routing will take over.

**Comment by kelvinrolex** [comment]
From what @robwormald  said 

This has nothing to do with Angular, per se - if you refresh the page, the request goes to the server before angular is even in the picture, so your server has to handle the request - typically it should just serve the index.html page for all routes, and then angular's routing will take over.

so i created a .htaccess code for that and its working fine.

@liongoncalves you can use the following .htaccess code

RewriteEngine on
    RewriteCond %{REQUEST_FILENAME} -s [OR]
    RewriteCond %{REQUEST_FILENAME} -l [OR]
    RewriteCond %{REQUEST_FILENAME} -d
    RewriteRule ^.*$ - [NC,L]

    RewriteRule ^(.*) /index.html [NC,L]

**Comment by lozthiensu** [comment]
@kelvinrolex tks u very much, it worked for me.

**Comment by SumanKalyanAcharya** [comment]
i am also facing same kind of problem when refreshing the URL. 

Please find below the code details 
 1. Within index.html <head> I have <base href="/">
2.  In app.module.ts I have the following router defined :+1:
`@NgModule({
    imports: [BrowserModule, FormsModule, RouterModule.forRoot([
       
        {
            path: 'heroes',
            component: HeroesComponent
        },
        {
            path: 'dashboard',
            component: DashboardComponent
        },
        {
            path: 'herodetails/:id',
            component: HeroDetailComponent,
            
        },
             
    ],
   //{ useHash: true }
    )],
    providers: [HeroService],
    declarations: [DefaultAppComponent, AppComponent, HeroDetailComponent, HeroesComponent, DashboardComponent],
    bootstrap: [AppComponent]

})

`
Now when I run the application through visual studio its opening properly. And even I click different buttons the URL is changing to http://localhost:52616/heroes and http://localhost:52616/dashboard as expected.

But if I refresh the page or manually update the URL from  http://localhost:52616/heroes to http://localhost:52616/dashboard  it is throwing 404 Error.  I am getting the  error even when refreshing http://localhost:52616  .

Tried to use HashStrategyrouting to add `{ useHash: true }` in app.module . It is working for manual URL change but not working with the URL refresh.

Please suggest. And also comment on the best routing strategy to follow.

**Comment by mpaul360** [comment]
use `<script>document.write('<base href="' + document.location + '" />');</script>` 
instead of `<base href="/">`

**Comment by SumanKalyanAcharya** [comment]
thanks @mpaul360 for responding back. The issue can be resolved using PathStrategyRouting as well. 
Actually when we are using HTML5 supported PathStrategyRouting  then we need to rewrite the URL in order to refer the startpoint of the application,index.html in our case.

For that you need to add the following code to your application web.config. It resolved the issue.

``<system.webServer>
    <rewrite>
      <rules>
        <rule name="redirect all" stopProcessing="true">
          <match url="^(.*)$" ignoreCase="false" />
          <conditions logicalGrouping="MatchAll">
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" pattern="" ignoreCase="false" />
          </conditions>
          <action type="Rewrite" url="PLEASE PROVICE PATH FOR INDEX.HTML" appendQueryString="true" />
        </rule>
      </rules>
    </rewrite>
  </system.webServer>``

**Comment by odairto** [comment]
Guys, if someone still have this problem and are using IIS, just add config in web.config:

original solution: [https://github.com/angular/angular/issues/11046](url)

`<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <system.webServer>
    <rewrite>
        <rules>
            <rule name="angularjs routes" stopProcessing="true">
                <match url=".*" />
                <conditions logicalGrouping="MatchAll">
                    <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                    <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
                </conditions>
                <action type="Rewrite" url="/egs/" />
            </rule>
        </rules>
    </rewrite>
  </system.webServer>
</configuration>`

**Comment by rakeshrnjn** [comment]
I 'm facing the same issue, using angular cli 1.6.5. but it works fine on lower cli  version.

**Comment by submjn** [comment]
For apache server, adding .htaccess file in my root directory (example.com), solved the issue

RewriteBase /
RewriteRule ^index\.html$ - [L]
 RewriteCond %{REQUEST_FILENAME} !-f
 RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.html [L]

Reference: https://tylermcginnis.com/react-router-cannot-get-url-refresh/

**Comment by Tahir77667** [comment]
https://angular.io/api/router/ExtraOptions

**Comment by timusiiit123** [comment]
> thanks @mpaul360 for responding back. The issue can be resolved using PathStrategyRouting as well.
> Actually when we are using HTML5 supported PathStrategyRouting then we need to rewrite the URL in order to refer the startpoint of the application,index.html in our case.
> 
> For that you need to add the following code to your application web.config. It resolved the issue.
> 
> `<system.webServer> <rewrite> <rules> <rule name="redirect all" stopProcessing="true"> <match url="^(.*)$" ignoreCase="false" /> <conditions logicalGrouping="MatchAll"> <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" pattern="" ignoreCase="false" /> </conditions> <action type="Rewrite" url="PLEASE PROVICE PATH FOR INDEX.HTML" appendQueryString="true" /> </rule> </rules> </rewrite> </system.webServer>`

Hi, I am facing the same problem. I am using Apache2 on the server what I do then. I followed the Rewrite Engine Rules but that did not work for me.
