### ISSUE TITLE
character set issue in the renderer

### ISSUE THREAD

**Issue by elijahiuu** [angular/angular#8796]
I was having problem with this portion of a template:
`<a>&nbsp;</a>`

it generated a renderer with the `&nbsp;` character like this (notice the **Â** char):
`  self._text_17 = self.renderer.createText(self._el_16,'Â ',self.debug(17,11,134));`

I troubleshooted the issue until conclusion that when Tomcat assigned a character-set of ISO-8859-1 on my angular bundle, that has caused the Â to show up. If I tell Tomcat to set charset to utf-8, then all is good.

Using 2.0 rc1

**Comment by jeffbcross** [comment]
Sounds like a Tomcat issue, not an Angular issue. If I'm misunderstanding something, please open a new issue with details of what you think is broken with Angular.
