### ISSUE TITLE
rc 1 router subscribe to router.changes does not receive url parameter

### ISSUE THREAD

**Issue by gregbown** [angular/angular#8798]
In Beta 17 the URL was passed to the subscriber like so this.
    router.subscribe(function(url){
        console.log('Handle router changes /' + url);
    }.bind(this));

In rc 1 I believe you have to subscribe to the router.changes emitter however no parameters are passed? Is this a bug?
    this.router.changes.subscribe(function(url){
        // url is always null
    }.bind(this));
Am I missing something or is there some other way to subscribe to router changes in rc1

**Comment by woorea** [comment]
The router *always* sends null

https://github.com/angular/angular/blob/master/modules/%40angular/router/src/router.ts#L166

**Comment by zoechi** [comment]
There might be a better way but this worked for me

```
  constructor(private router:Router, private routeSerializer:RouterUrlSerializer, private location:Location) {
    router.changes.first().subscribe(() => {
      console.log('router', this.router);
      let urlTree = this.routeSerializer.parse(location.path());
      // get different segments from the route 
      console.log('serializer', urlTree.children(urlTree.root)[0].segment);
      console.log('serializer', urlTree.children(urlTree.children(urlTree.root)[0])[0].segment);
    });
  }
```

**Comment by gregbown** [comment]
Why would the router emit null? Its of no use, also beta 17 used to pass the URL so I would think this is appropriate with the rc1 router?  The current functionality makes subscribing to the router useless beyond just knowing the route changed.  I may as well just check window.location.pathname.

**Comment by IgorMinar** [comment]
This issue was made obsolete by router v3: https://angularjs.blogspot.com/2016/06/improvements-coming-for-routing-in.html

If you believe this is not the case, please file a new issue updating the description to router v3. thank you!
