### ISSUE TITLE
Angular2 RC1 Router Issues  - browser_adapter Cannot read property 'map' of null

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular#8801]
Hi,

Switching between two routes which are at the same level and make http call throws error "browser_adapter.ts:78 EXCEPTION: TypeError: Cannot read property 'map' of null".

For example when I visit any of the below urla it works perfectly. But when after visiting first url if I visit second url I get error.

app/admin (displays admin dashboard and fetch data through http get request)
app/user (displays user dashboard and fetch data through http get request)

On the other hand if I switch between two urls which are parent/child and both make http request, I dont get any error.

Below are the error details:

```
browser_adapter.ts:78 EXCEPTION: TypeError: Cannot read property 'map' of nullBrowserDomAdapter.logError @ browser_adapter.ts:78BrowserDomAdapter.logGroup @ browser_adapter.ts:89ExceptionHandler.call @ exception_handler.ts:53(anonymous function) @ application_ref.ts:304schedulerFn @ async.ts:131SafeSubscriber.__tryOrUnsub @ Subscriber.ts:240SafeSubscriber.next @ Subscriber.ts:192Subscriber._next @ Subscriber.ts:133Subscriber.next @ Subscriber.ts:93Subject._finalNext @ Subject.ts:154Subject._next @ Subject.ts:144Subject.next @ Subject.ts:90EventEmitter.emit @ async.ts:117NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ ng_zone.ts:138NgZoneImpl.inner.inner.fork.onHandleError @ ng_zone_impl.ts:90ZoneDelegate.handleError @ zone.js:327Zone.runTask @ zone.js:259ZoneTask.invoke @ zone.js:423
browser_adapter.ts:78 STACKTRACE:BrowserDomAdapter.logError @ browser_adapter.ts:78ExceptionHandler.call @ exception_handler.ts:56(anonymous function) @ application_ref.ts:304schedulerFn @ async.ts:131SafeSubscriber.__tryOrUnsub @ Subscriber.ts:240SafeSubscriber.next @ Subscriber.ts:192Subscriber._next @ Subscriber.ts:133Subscriber.next @ Subscriber.ts:93Subject._finalNext @ Subject.ts:154Subject._next @ Subject.ts:144Subject.next @ Subject.ts:90EventEmitter.emit @ async.ts:117NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ ng_zone.ts:138NgZoneImpl.inner.inner.fork.onHandleError @ ng_zone_impl.ts:90ZoneDelegate.handleError @ zone.js:327Zone.runTask @ zone.js:259ZoneTask.invoke @ zone.js:423
browser_adapter.ts:78 TypeError: Cannot read property 'map' of null
    at UrlTree.Tree.pathFromRoot (segments.ts:32)
    at _findUrlSegment (link.ts:87)
    at _findStartingNode (link.ts:98)
    at Object.link (link.ts:19)
    at Router.createUrlTree (router.ts:145)
    at RouterLink._updateTargetUrlAndHref (router_link.ts:55)
    at Object.eval (router_link.ts:33)
    at eval (async.ts:130)
    at ZoneDelegate.invokeTask (zone.js:356)
    at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (ng_zone_impl.ts:56)BrowserDomAdapter.logError @ browser_adapter.ts:78ExceptionHandler.call @ exception_handler.ts:57(anonymous function) @ application_ref.ts:304schedulerFn @ async.ts:131SafeSubscriber.__tryOrUnsub @ Subscriber.ts:240SafeSubscriber.next @ Subscriber.ts:192Subscriber._next @ Subscriber.ts:133Subscriber.next @ Subscriber.ts:93Subject._finalNext @ Subject.ts:154Subject._next @ Subject.ts:144Subject.next @ Subject.ts:90EventEmitter.emit @ async.ts:117NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ ng_zone.ts:138NgZoneImpl.inner.inner.fork.onHandleError @ ng_zone_impl.ts:90ZoneDelegate.handleError @ zone.js:327Zone.runTask @ zone.js:259ZoneTask.invoke @ zone.js:423
Subscriber.ts:243 Uncaught TypeError: Cannot read property 'map' of null
```

**Error seems to be on the below line in (segments.ts:32)**

`pathFromRoot(t: T): T[] { return _findPath(t, this._root, []).map(s => s.value); }`

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/issues/8667 and https://github.com/angular/angular/issues/8567

**Comment by naveedahmed1** [comment]
Thank you so much for your reply Eric. Gone through the plunker in the above link, it suggest converting it seems to be suggesting to convert links to absolute path, if I understood it correct rite?

Can you please confirm if it really is a bug in RC1, or something is wrong with the way I am using it (i.e. using relative paths in components)?

**Comment by ericmartinezr** [comment]
It is a bug. If it is an error from the user, it should at least throw an error (a clear one), if it is not an error from the user, it should work, which it doesn't, so yes, it is a bug. So don't worry, you're not crazy =P

**Comment by naveedahmed1** [comment]
Great! Looking forward to have it fixed in next release. :)

**Comment by mi9rom** [comment]
I get exactly the same error after upgrade from rc1 to rc2.

**Comment by DanielMcAssey** [comment]
Getting the same problem when upgraded from rc1 to rc2

**Comment by zoechi** [comment]
@mi9rom  @DanielMcAssey sounds like a different issue if it only happens in RC.2. This would require a Plunker to reproduce otherwise the comments probably won't not cause any action.

**Comment by mi9rom** [comment]
I found the cause. It is the RouterLink directive.  It was and worked in RC1 -  [routerLink]="['#/about'] , in RC2 it should be [routerLink]="['/about'].  Mean little '#'. ;)  bdw logical change, but error messages should be more human being friendly , I realize it is easy to say such things but much harder to implement but you should try :)

**Comment by ericmartinezr** [comment]
RC router is abandoned, you should all start using the new new new router https://github.com/angular/vladivostok

**Comment by mi9rom** [comment]
@ericmartinezr I would gladly switch but I get system-polyfills.src.js:1276 Error: (SystemJS) TypeError: router_1.Routes is not a function(…).  Is there perhaps on the plnkr/git  simple working example I could check, It would save my time. Sorry for off the topic conversation.

**Comment by alexproca** [comment]
There is a plunker here http://plnkr.co/edit/ER0tf8fpGHZiuVWB7Q07?p=preview

**Comment by ericmartinezr** [comment]
@mi9rom the new new new router has no compatibility with the previous versions, there's no more Routes annotation. See http://victorsavkin.com/post/145672529346/angular-router and this plnkr http://plnkr.co/edit/bInAap?p=info. It follows ngrx/router concepts.

**Comment by IgorMinar** [comment]
now that there is router v3, this issue is now obsolete
