### ISSUE TITLE
[i18n] do not extract message when there is not child nodes

### ISSUE THREAD

**Issue by vicb** [angular/angular#8802]
`<div i18n></div>` should not create a new message

**Comment by manekinekko** [comment]
@vicb I'm working on this one

**Comment by manekinekko** [comment]
@vicb could you provide a couple more examples that should not create new messages ? I need to make sure my   spec tests are solid :)

**Comment by vicb** [comment]
I have nothing else in mind

**Comment by manekinekko** [comment]
what about the following examples ?
```
<div i18n></div>
<div i18n>text</div>
<div i18n><b></b></div>
<div i18n><b>text</b></div>
```

**Comment by vicb** [comment]
when there is no child text node
