### ISSUE TITLE
Angular2 Zone.js and requestAnimationFrame - CPU usage is very high

### ISSUE THREAD

**Issue by hragavan** [angular/angular#8804]
I am seeing the same issue as the one here : https://github.com/angular/angular/issues/2912. I am using zone.js 0.6.10 and I still see it. I have a map which on move calls requestAnimationFrame but since my CPU usage is high, map move crashes.

**Comment by robwormald** [comment]
Could you reproduce this in a plunker please? It's very difficult to troubleshoot such things without a code sample to verify.

**Comment by gdi2290** [comment]
please run any calls to requestAnimationFrame outside of angular.

```typescript
class App {
  constructor(public ngZone: NgZone) {

    this.ngZone.runOutsideAngular(() => {

      requestAnimationFrame(() => {
      });

    });
  }
}
```

**Comment by pxwise** [comment]
Thanks @gdi2290. This got us on the right path to unwrapping our map library requestAnimationFrame calls from Zone.js.

**Comment by ericmartinezr** [comment]
@gdi2290 any particular reason to run `requestAnimationFrame` outside angular? I have a little project using it inside and all works fine, probably I'm not abusing it. What would be that reason? Thanks.

**Comment by gdi2290** [comment]
related https://github.com/angular/angular/issues/2912

**Comment by hragavan** [comment]
Thanks @gdi2290. Moving our map calls outside of zone.js worked!

**Comment by ghetolay** [comment]
@gdi2290 this is more a zonejs related question but it fits well in this thread : 
Can't we just call directly the native browser function ? 
Found out zonejs keep the native function under the name ```__zone_symbol__requestAnimationFrame```.
What may be wrong about using it directly ?

**Comment by gdi2290** [comment]
that's super private (double `_`) so you can't guarantee that it will be `__zone_symbol__requestAnimationFrame` in the future. `runOutsideAngular` returns whatever is returned by the callback so you can change it to 
```typescript
    var cancel = this.ngZone.runOutsideAngular(() => requestAnimationFrame(() => {
      // do stuff
    }));
    cancelAnimationFrame(cancel)
```

**Comment by ghetolay** [comment]
I was more asking if ```runOutsideAngular()``` had another purpose we could miss by calling the native function directly. But it seems not so thank you. 
I'll be a bad guy and go for the private reference (or create my own public one before running zonejs).

**Comment by harryjubb** [comment]
I'm using a 3rd party library that calls `requestAnimationFrame`, and am seeing the CPU usage of Google Chrome Helper go through the roof when I'm using it.

Is there anything I can do about this when I don't have control over when `requestAnimationFrame` is called?

**Comment by gdi2290** [comment]
@harryjubb whenever you use the 3rd party module you can run it outside of the zone
```
// in zone
var value = moment.yolo()
// outside
var value = this.ngZone.runOutsideAngular(() => moment.yolo());
```

**Comment by harryjubb** [comment]
@gdi2290 Thank you, I was a bit nervous about trying it because I wondered if it would break any of the interactions between the 3rd party module (NGL: https://github.com/arose/ngl) and my app, but from what I can tell so far just running the constructor for the WebGL stage it creates outside of the Angular Zone works, CPU usage is much lower, and the events it emits are still picked up by my app as far as I can tell.

```
this.ngZone.runOutsideAngular(() => {
      this.stage = new NGL.Stage("ngl-stage");
    });
```

Thanks for your help.

**Comment by michaelb-01** [comment]
I'm creating a custom video player and using requestAnimationFrame to update a frame accurate time value. However when I run it outside angular as suggested here it runs much slower (it updates roughly every 8 frames..). Without the runOutSideAngular function it runs fine and updates every frame..

This is the relevant section of my component:

```
  updateFrame() {
    this.time = this.pipeVideo.nativeElement.currentTime;
    this.frame = Math.round(this.time * this.fps) + 1;  // frame rate of 25 fps

    requestAnimationFrame(() => {
      this.updateFrame();
    });
  }

  playVideo() {
    this.animFrame = this.ngZone.runOutsideAngular(() => requestAnimationFrame(() => {
      this.updateFrame();
    }));
    this.pipeVideo.nativeElement.play();
    this.playing = true;
  }
```

**Comment by JiaLiPassion** [comment]
@michaelb-01 , if you want to run `requestAnimationFrame` outside `zone`, there is a faster way, I will document it later.

add following code in `polyfill.ts` before loading `zone.js`.

```javascript
__Zone_disable_requestAnimationFrame=true;
import 'zone.js/dist/zone';  // Included with Angular CLI.
```

**Comment by hiepxanh** [comment]
@JiaLiPassion can you make a small guilde how to run`requestAnimationFrame` outside `zone` faster way?

**Comment by hiepxanh** [comment]
why we need add that following code:
```
__Zone_disable_requestAnimationFrame=true;
import 'zone.js/dist/zone';  // Included with Angular CLI.
```
`__Zone_disable_requestAnimationFrame` what is that for?

**Comment by JiaLiPassion** [comment]
@hiepxanh, the `__Zone_disable_requestAnimationFrame=true;` means disable `zone.js monkey-patch  requestAnimationFrame API`, so your app will use `native window.requestAnimationFrame` which will have no preformance impact.

**Comment by hiepxanh** [comment]
@JiaLiPassion thank you, can you make a small guilde how to runrequestAnimationFrame outside zone faster way?

**Comment by ericmartinezr** [comment]
Just read the comments in the issue (https://github.com/angular/angular/issues/8804#issuecomment-221456326) or read the docs https://angular.io/api/core/NgZone#runoutsideangular

**Comment by JiaLiPassion** [comment]
@hiepxanh.

1. edit your `src/polyfills.ts`.
2. before `loading zone.js`. add the `flag`.

```
(window as any).__Zone_disable_requestAnimationFrame=true;
import 'zone.js/dist/zone';  // Included with Angular CLI.
```

**Comment by hiepxanh** [comment]
thank you sir.
