### ISSUE TITLE
`HashLocationStrategy` break if user uses middle mouse click or 'Open in new tab'

### ISSUE THREAD

**Issue by TheHippo** [angular/angular#8806]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request

**Steps to reproduce and a minimal demo of the problem**

http://plnkr.co/edit/qH3h1LZvV0PntgJj5hLu?p=preview

But things are much more clearer if you open the embed view with the top frame removed:

http://run.plnkr.co/plunks/qH3h1LZvV0PntgJj5hLu

_What steps should we try in your demo to see the problem?_

Use middle-click on mouse or 'Open in tab' function of your browser on one of the two links on the demo page. Normal click work fine.

**Current behavior**

New tab will open http://run.plnkr.co/one

**Expected/desired behavior**

New tab should open http://run.plnkr.co/plunks/qH3h1LZvV0PntgJj5hLu/#/one or at least http://run.plnkr.co/#/one

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc1
 
* **Browser:** Current FF & current Chrome have same behaviour 
 
* **Language:** TypeScript 1.6.2 and whatever plnkr.co uses

**Comment by zoechi** [comment]
Dup of or at least related to #5908

**Comment by dloukadakis** [comment]
This was a legit bug report why it was closed? it should have been closed when someone merges my pull request...

**Comment by zoechi** [comment]
Because it was fixed.
