### ISSUE TITLE
angular1_router | Is there a way to listen to onDeactivate at rootScope level

### ISSUE THREAD

**Issue by pranav-xx** [angular/angular#8809]
I'm submitting a clarification. It might be a feature request:

Scenario:
I have a popup in my application which does not belongs to any route. What I need to ensure is, while the popup is open, when user clicks on a navigation (which takes to a component route), before activating this route, I need to close the popup. This popup when closing gives user a prompt to close or not close. Now in case user chooses to not close, the route should not change.

Is there a way I can provide $canDeactivate hook at the rootRouter level which is executed at each route change along with component specific $canDeactivate hooks?

Thanks,
Pranav Kaushik

**Comment by Mischi** [comment]
Hi, 

i think this is currently not possible as ng-outlet only checks `$routerCanDeactivate` of the currently active component. See [ng-outlet.ts](https://github.com/angular/angular/blob/master/modules/angular1_router/src/ng_outlet.ts#L86-L92).
Maybe you can solve your problem via some kind of inheritence without to much code duplication?

Here's a simple example:
https://embed.plnkr.co/JBvl4MC0OIEwFgVPyl26/

Cheers,
Fabian

**Comment by vicb** [comment]
obsolete
