### ISSUE TITLE
getting error with ng serve --prod 

### ISSUE THREAD

**Issue by KushagraGitter** [angular/angular#8810]
![image](https://cloud.githubusercontent.com/assets/13452634/15501501/61ccbec0-21cb-11e6-9562-f04a4d89b580.png)
* **I'm submitting a ...**
- [ ] bug report

**Comment by zoechi** [comment]
Can you reproduce in a Plunker? What does the project and code look like that results in this error message?

**Comment by KushagraGitter** [comment]
Hi,
i have not anything special, just follow the angular mobile demo.
created project using      ng new hello-mobile --mobile
ng serve is working fine, but when try to serve it with --prod then getting this error

**Comment by Cammisuli** [comment]
Looks like it's an Angular CLI issue
