### ISSUE TITLE
Inherited decorators are ignored

### ISSUE THREAD

**Issue by kemsky** [angular/angular#8813]
Assume we have the following base class:

```
class Base 
{
    @Output('event')
    protected emitter:EventEmitter<any> = new EventEmitter<any>()
}
```

The `event` will not be triggered if we extend `Base`class:

```
@Component({selector: 'child'})
class Child extends  Base 
{
    public method()
    {
         this.emitter.emit(true);    
    }
}
```

```
...
<child (event)="Alert()"></child>
...
```

I can set `outputs: ['event']` as a workaround, but it is not good to do that manually for every child component.

I'm using `2.0.0-rc.1`.

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/issues/5415

**Comment by kemsky** [comment]
thank you, this issue is duplicate.
