### ISSUE TITLE
new router bug,   nginx 404

### ISSUE THREAD

**Issue by iloveyo123u1** [angular/angular#8816]
web server i used nginx 

**http://127.0.0.1**    is my webpage index

then i click a button to **home** , router change to `home`

url change to **http://127.0.0.1/home** ，website display `home` component

then。 i look  a user info,   url is **http://127.0.0.1/user/12**

i want share the url to my colleagues(firend),  bug she open the url, get a error:
```
404 Not Found

nginx/1.9.15

```

i think   old router is work,like this **http://127.0.0.1/#/user/12**

i have a question,

Do you give up this route ？ **http://127.0.0.1/#/user/12**

**Comment by iloveyo123u1** [comment]
and   would you help me?

thank you very much

**Comment by sod** [comment]
If you want to route by `#` you can override the location strategy with `HashLocationStrategy`

https://angular.io/docs/ts/latest/api/common/index/HashLocationStrategy-class.html

**Comment by zoechi** [comment]
See also http://stackoverflow.com/questions/31415052/angular-2-0-router-not-working-on-reloading-the-browser 

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by dloukadakis** [comment]
Maybe we must write this somewhere in documentation to avoid future issues or make HashLocationStategy the default LocationStrategy :smile: 

Related Issues:
#8521 #8788

**Comment by iloveyo123u1** [comment]
thanks @sod @zoechi  @dloukadakis   

yes, we must  make HashLocationStategy the default LocationStrategy

**Comment by zoechi** [comment]
HashLocationStrategy is only relevant for simple demos or might be an barrier for beginners but PathLocationStrategy is the better strategy. If the server you are using isn't supporting HTML5 pushState than its an issue with your server not with Angular. 
This was discussed several times and a deliberate decision was made to keep PathLocationStrategy the default.

**Comment by zsfarkas** [comment]
Can anybody tell here, how to configure nginx, in order to be able to use path location strategy?
Thank you.

**Comment by mlc-mlapis** [comment]
You have to configure Nginx that it will return index.html page for all resource requests that do not exist on the server (valid for project root directory and its all subdirectories).

**Comment by zsfarkas** [comment]
@mlc-mlapis Thank you. It is a good answer for understanding.

Actually I have found, what I was looking for. It is quite special, but maybe someone wants to know:

If you use the staticfile-buildpack in cloud foundry (maybe it is the same for heroku), then you have there the option ["pushstate: enabled"](https://docs.cloudfoundry.org/buildpacks/staticfile/index.html#pushstate). It does the work for me. So I am able to use the path location strategy of angular 2.

**Comment by mlc-mlapis** [comment]
@zsfarkas Ah, yes. It has a relation to A2 docs at https://angular.io/docs/ts/latest/guide/router.html:

> The Component Router uses the browser's history.pushState for navigation. Thanks to pushState, we can make our in-app URL paths look the way we want them to look, e.g. localhost:3000/crisis-center. Our in-app URLs can be indistinguishable from server URLs.

> Modern HTML 5 browsers were the first to support pushState which is why many people refer to these URLs as "HTML 5 style" URLs.
