### ISSUE TITLE
Angular2 rc.1 router-deprecated, No provider for Router! OR Cannot read property 'isSkipSelf' of null

### ISSUE THREAD

**Issue by born2net** [angular/angular#8820]
so I am trying to setup rc.1 with router-deprecated and so I am getting an error of: 
```
EXCEPTION: No provider for Router!
``` 
ok easy enough, so I just add to my providers and imports:
```
import {RouteConfig, ROUTER_DIRECTIVES, ROUTER_PROVIDERS, Router, RouterLink} from "@angular/router-deprecated";
...
providers: [ROUTER_PROVIDERS, Router],
```

but as soon as I do that, it blows up with:
```
Cannot read property 'isSkipSelf' of null
```

![capture](https://cloud.githubusercontent.com/assets/5090936/15522180/8b0d6a2e-21c5-11e6-9241-0c346fc44eef.PNG)

is this a known issue? 
any help is appreciated

Sean

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/issues/8704, and also, remove `Router` from `providers`.

**Comment by born2net** [comment]
tx @ericmartinezr I did see that post but I am unclear as to the solution.. is it a circular reference as I dont have any .. or a bug in existing router-deprecated?

**Comment by ericmartinezr** [comment]
No, you're doing it wrong. 

You never provide Router yourself, that's what ROUTER_PROVIDERS do for you

```
providers: [ROUTER_PROVIDERS, Router], // wrong...
```
put ROUTER_PROVIDERS in your bootstrap, don't do it in your components.

```
bootstrap(App, [ROUTER_PROVIDERS])
```

**Comment by born2net** [comment]
got it tx!

**Comment by born2net** [comment]
Hi @ericmartinezr 
if I make your change and only import in:
```
bootstrap(App, [ROUTER_PROVIDERS])
```
I error out with ```No provider for Router!```

and if I add the Router via:
```
bootstrap(App, [HTTP_PROVIDERS, ROUTER_PROVIDERS, Router
```
it errors out with:
```
ncaught (in promise) Error: Error: Cannot resolve all parameters for 'Router'(RouteRegistry, Router, ?, Router)
```
I didn't have any of this mess until I moved to rc.1 with router-deprected... am I doing it wrong?
tx

Sean

**Comment by ericmartinezr** [comment]
Yes, you're doing it wrong. Again, you don't provide Router yourself, that's what ROUTER_PROVIDERS is for. Come to gitter's chatroom https://gitter.im/angular/angular and provide a plnkr with your case.

**Comment by born2net** [comment]
ok will do.

**Comment by AishApp** [comment]
I am facing the similar issue. @born2net have you found the solution?

**Comment by born2net** [comment]
unfortunately no, I am not using deprecated router because of this bug and waiting for rc.2, no fun.

**Comment by born2net** [comment]
unfortunately no, I am not using deprecated router because of this bug and waiting for rc.2, no fun.

**Comment by AishApp** [comment]
Thanks for the reply @born2net

**Comment by riccardo-tesio** [comment]
Same problem here.
I have nested routes. They worked correctly in Angular2 beta.

**Comment by riccardo-tesio** [comment]
Sorry, it was my fault.
In one file I put 
`import {Router} from '@angular/router';`
instead of
`import {Router} from '@angular/router-deprecated';`
so my app was looking for the wrong Router. Migrating from Beta to RC is not so easy...

**Comment by BrainCrumbz** [comment]
@riccardo-tesio well said. When migrating and doing search & replace on many files one can fall into that trap. It happened to us as well. Better double check that all `'angular2/router'` instances have been replaced by `'@angular/router-deprecated'`
