### ISSUE TITLE
Loading a named or aux route with a routerLink is not possible in rc1

### ISSUE THREAD

**Issue by gregbown** [angular/angular#8824]
I can load the main and aux outlets via navigateByUrl however I cannot determine the correct structure for a routerLink to load both?  Loading aux or named routes appears to be broken or unsupported?

None of these work:
[routerLink]="['/virtual-currency(/sidebar)']"
[routerLink]="['/virtual-currency(sidebar)']"
[routerLink]="['/virtual-currency(aux:sidebar)']"
[routerLink]="['/virtual-currency', ['/sidebar']" <- works in beta 17 but not rc1
[routerLink]="['/virtual-currency/aux:sidebar']"

my template
               <a class="nav-link" [routerLink]="['/virtual-currency']">VirtualCurrency</a>
                <div class='main-content col-md-8 col-sm-12 col-xs-12'>
                  <router-outlet></router-outlet>
                </div>
                <div class='sidebar col-md-4 hidden-sm hidden-xs'>
                  <router-outlet name="aux"></router-outlet>
                </div>
in root component
Routes([
  { path: "/virtual-currency", component: shop.VirtualCurrency},
  { path: "/membership", component: shop.Membership},
  { path: "/products", component: shop.Products},
  { path: '/sidebar', component: shop.Sidebar}
])

In my root component this.router.navigateByUrl('/virtual-currency(/sidebar)'); works perfectly.
However in the link I have tried every conceivable format eluded to in the documentation, tests and router refactorings doc.
https://github.com/angular/angular/commit/89704e0
https://docs.google.com/document/d/1WLSNV3V1AKdwLwRiLuN7JqbPBKQ_S5quRlcT5LPIldw/edit#heading=h.k0qj682gz0jw

Thank you
Greg

**Comment by arpit-agarwal** [comment]
I assume you are use new router rather than deprecated router

You can target a named outlet like this
`<routeroutlet ></routeroutlet >
<routeroutlet name="sidebar" ></routeroutlet > `
In route link use
 
`[routerLink]="['/virtual-currency(sidebar:sidebar)']"`

I think they deprecated any special handling for "aux" keyword but just use name outlet instead. 
Add a plankr and i will fork and update teh same to demo if needed

**Comment by gregbown** [comment]
Thank you for your response.
Yes, I am using the new router.
Actually, it appears that aux is the only name that is supported.  If you name it anything else you get:
Uncaught (in promise): Cannot find the outlet aux.
Also I have tried the routerLink format you describe and it does not work.
Oddly, both these formats work inside the component:
this.router.navigateByUrl('/virtual-currency(aux:sidebar)');
this.router.navigateByUrl('/virtual-currency(/sidebar)');

**Comment by Delagen** [comment]
+1
http://host/#/root(left:menu) works
routerLink="/root(left:menu)" does not generate valid route

**Comment by ericmartinezr** [comment]
You should always test all these "issues" against latest versions. RC.3 + router alpha 8

See also https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by michaelbromley** [comment]
I'm having issues with named outlets. [Here is a plunk with rc.4 and router beta.2 which illustrates the issues](http://plnkr.co/edit/RHwMW1gcRE74HXC7C6t9?p=preview).

Basically - how does one route to named outlets using either `routerLink` or `router.navigate()`?

There are no docs on this and I can't find any articles or tutorials out there, so it is not clear to me whether there are bugs, or I am just doing things wrong out of ignorance.

**Comment by arpit-agarwal** [comment]
My suggestion does not work on rc.4 and router beta.2. I am also looking for this fix

**Comment by zoechi** [comment]
#10003 seems to fix that

**Comment by IgorMinar** [comment]
This issue was made obsolete by router v3: https://angularjs.blogspot.com/2016/06/improvements-coming-for-routing-in.html

If you believe this is not the case, please file a new issue updating the description to router v3. thank you!
