### ISSUE TITLE
Parent variable not working inside of ng-content

### ISSUE THREAD

**Issue by sjova** [angular/angular#8825]
**Intro:** I'm working on ng2 components whose structure looks like this:

    <cards>
      <card>
      	<card-content-type-1></card-content-type-1>
      </card>
      <card>
      	<card-content-type-2></card-content-type-2>
      </card>
      <card>
      	<card-content-type-3></card-content-type-3>
      </card>
      ...
    </cards>

I'm changing states of each `<card>` based on click/mouseenter/mouseleave events, and when some action happen inside of `<card>` component (parent component), based on current state, I'd like to trigger some animation methods inside `<card-content-type-N>` components (children component). For animations I'll use `AnimationBuilder` and `ElementRef`.

----------

**Issue:** I decided to pass parent component variable to children component, and to implement `ngOnChanges()` inside of children, which will trigger specific animation depends of current variable value. But I have troubles to pass parent variable to children when I use ng-content inside of parent template.

I created simplified example (only parent and children components): https://plnkr.co/edit/OHIJjMwdx6ifRiSxsanB?p=preview

In this example `parentVar` is not passed into the `child-comp`. Is this some bug in Angular2 or I'm doing something wrong? I suppose that is related with `ng-content` scope, but we lack good docs/examples about this (or at least, I missed docs about `ng-content`)

In same example inside of `src/parent-comp.ts` if we replace intial template with `<child-comp [childVar]="parentVar"></child-comp>` parent variable is passed properly.

Also inside of `src/app.ts` if we replace initial template with  this:

    <parent-comp>
      <child-comp [childVar]="true"></child-comp>
    </parent-comp>

static variable is passed properly.

Does someone have a similar issue? Or have idea how I can solve this issue? Thanks.

* **Angular version:** 2.0.0-beta.17 
* **Browser:** all
* **Language:** TypeScript 1.7.3

**Comment by zoechi** [comment]
Is this a follow up to http://stackoverflow.com/questions/37425958/parent-variable-not-working-inside-of-ng-content because on SO there is an accepted answer. 

This probably doesn't do what you want:

    <child-comp [childVar]="true"></child-comp>

because it binds the value of property `true` of the parent class to the input `childVar` (I don't think you actually can name a property `true` though)

If you want to bind the value `true` then you need a property that returns that value or use a string value that can be evaluated to `true` by the receiver. In the template you can't express the value `true`, only the string `'true'` like

        <child-comp [childVar]="'true'"></child-comp>

**Comment by zoechi** [comment]
I investigated your Plunker. It's not clear what it should demonstrate.

https://plnkr.co/edit/v3L6wehMefkL8P5DVCYD?p=preview

```
  <parent-comp>
    <child-comp [childVar]="parentVar"></child-comp>
  </parent-comp>
```
binds to `parentVar` in `App` (which is commented out)

```
  <parent-comp #parent>
    <child-comp [childVar]="parent.parentVar"></child-comp>
  </parent-comp>
```

is similar to what the SO answer suggests and binds `parentVar` from `ParentComp` which seems to be what you want. This way `ngOnChanges()` in `ChildComp` is called. 

I haven't found anything about click/mouseenter/mouseleave (mentioned in the initial request) in the Plunker.


GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by jeffbcross** [comment]
The plunker appears to work correctly if I uncomment `public parentVar: boolean = false;` in app.ts. If you're still experiencing this issue, can you update the plunker to work against rc.1 and open a new issue?
