### ISSUE TITLE
bug(forms): controlgroup add/remove control doesn't trigger change detection properly

### ISSUE THREAD

**Issue by awiseman** [angular/angular#8826]
* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**

Change detection seems not to work properly when calling addControl or removeControl from a ControlGroup after the form has been initialized.

When a control is added or removed from the control group, the form's value and validation is not re-evaluated in the template.  This can lead to cases where the form becomes unsubmitable or requires the user to do some janky workaround.

**Expected/desired behavior**

Adding or removing controls from a ControlGroup should trigger change detection that re-evaluates the form state based on the new control state.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via

http://plnkr.co/edit/RTwcYiVroifResV9s1ZR?p=preview

This plunk demonstrates a form that can mutate based on values of its controls.  When the select box has the value 'yes', another input control is added to the form.  When the select box has the value 'no' the input control should be removed from the form.

Currently, adding the control works, but removing the control doesn't show the control removed in the interpolated form value.  The button also remains disabled if the text box is empty and the select value changes to 'no'.

When I inspect the value of the controlgroup, I can see that the control is actually removed/added to the group, as expected.  It just seems that the template does not pick up on the changes, correctly.

* **What is the expected behavior?**

When the textbox is empty and the select value changes from 'yes' to 'no', the button should become enabled based on the validity of the select control.

When the select value changes from 'yes' to 'no', the interpolated value of the form should show that the input control has been removed from the form's ControlGroup.

When the select value changes from 'no' to 'yes', the interpolated value of the form should show that the input control has been added from the form's ControlGroup.

* **What is the motivation / use case for changing the behavior?**

In the application I am writing, I need to mutate a large form based on a field in the form; essentially, a 'report type' selector.  Based on the selected type, I need to add or remove controls from the form.  In order to avoid bugs, I need Angular2 to re-evaluate the validity and value of the form when controls get added and removed.

* **Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.1
 
* **Browser:** [Chrome 50.0.2661.102 (64-bit)] 
 
* **Language:** [TypeScript 1.8.10 | ES5]

**Comment by kara** [comment]
If you call `this.form.updateValueAndValidity()` after you add or remove a control from the ControlGroup, it should update the way you want.  The fact that addControl and removeControl don't do this by default is a bit confusing though.  Looking into how we can do better, but the above should work in the meantime.

**Comment by skraghava** [comment]
even after using updateValueAndValidity, its not working for me.

**Comment by jackesdavid** [comment]
you need to call remove control in your FormGroup to update...
if you are inserting controls inside a form dynamic in code or in a ui interaction...

**Comment by jackesdavid** [comment]
```typescript
   public deregisterAsFormControl = (name: string): void =>
    {
        if (this.isInit)
        {
            this.form.removeControl(name);
            console.log("control unregistered -> " + name);
        }
    }
```
