### ISSUE TITLE
Drag Events Using Directives On Table Row Works Very Slow :ChangeDetection On DragEvents

### ISSUE THREAD

**Issue by maheshnvv** [angular/angular#8827]
bug report
   : Drag Events Using Directives On Table Row Works Very Slow
**Current behavior**
The Drag / Drop Events are getting fired very slowly. In stack trace I found zone js code is getting Executed. I don't know why that is getting executed even I set ChangeDetection.Onpush

**Expected/desired behavior**
Should Be fast.

Please Refer To :http://stackoverflow.com/questions/37408247/angular2-drag-events-using-directives-on-table-row-works-very-slow

Angular version: 2.0.0-rc.1
All Browsers
 
Language: TypeScript

**Comment by vicb** [comment]
If event are registered inside the Angular, the listener will also run inside this zone.

The solution is to register outside of the angular zone.
