### ISSUE TITLE
bug(Headers): header keys should be case-insensitive

### ISSUE THREAD

**Issue by stakach** [angular/angular#8831]
> A header consists of a name and value. A name is a case-insensitive byte sequence that matches the field-name token

The spec can be found here: https://fetch.spec.whatwg.org/#infrastructure

This is primarily an issue with response headers as different browser implement this differently. Chrome lowercases the header keys whereas Firefox returns the original values provided by the server and performs case-insensitive comparisons when required.

The Angular implementation currently does not lowercase response headers or perform case-insensitive comparisons:
https://github.com/angular/angular/blob/a66cdb469f56f8ebab2e5f2e44d59b53effd0489/modules/%40angular/http/src/headers.ts

This complicates developer code as multiple versions of a header need to be considered:

```typescript
// To support both Chrome and Firefox currently:
let length: string = response.headers.get(`Content-Length`) || response.headers.get(`content-length`);
// This is still fragile as a server may respond with `Content-length` breaking the above
```

**Comment by ericmartinezr** [comment]
See https://github.com/angular/http/issues/53
