### ISSUE TITLE
bug(http) 404 error always appears in console even if caught

### ISSUE THREAD

**Issue by abuda7em** [angular/angular#8832]
When trying to send a request to a url that returns 404 error, the error will always appear in console even if I catch it. 

This behavior happens when using `@angular/http`, or even when using the native `XMLHttpRequest`, Which makes me think it's a zone task issue. 

Please refer to [this plunk](http://plnkr.co/edit/Pi2G6tP3RomRBOcyYt5A?p=preview)

**Expected/desired behavior**

I think the error message should not appear in console if the error was caught.

**Comment by zoechi** [comment]
This issue doesn't provide enough information to reproduce or debug the issue.
If http://stackoverflow.com/questions/37430092/angular-2-how-to-handle-404-before-logging-to-browser-console is also from you, please provide enough information there, so it can be reproduced.

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by jeffbcross** [comment]
This is just default browser behavior. See this plunker without angular or zones and the 404 is still logged: http://plnkr.co/edit/FUj5kgPPNyGzUnc3e07i?p=preview

**Comment by lohiarahul** [comment]
You could use  GlobalErrorHandler that extends the  `ErrorHandler` and implement the handleError() method. It shouldnt throw it to the browser then.
