### ISSUE TITLE
UpgradeAdapter is not a constructor

### ISSUE THREAD

**Issue by ascalonwa** [angular/angular#8833]
* **I'm submitting a ...**
- [x ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**
when using the UpgradeAdapter, I get the following error. "UpgradeAdapter is not a constructor"
before when i was using the "angular2/upgrade", I was able to bootstrap my application in hybrid mode with angular1 and angular2 running at the same time.  I am currently using webpack, not sure if that makes a difference.

**Expected/desired behavior**
successful bootstrapping of application

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
Current Code Snippet:
http://plnkr.co/edit/jIcs2C

* **What is the expected behavior?**
successful bootstrapping of application

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.1 
 
* **Browser:** [all ] 
 
* **Language:** TypeScript 1.8.10 | Javascript

**Comment by IgorMinar** [comment]
I believe that this issue is now obsolete. I can't reproduce it. If the issue still persists please open a new issue and provide steps to reproduce the problem.
