### ISSUE TITLE
ValidatorFn not included in the src/common/forms barrel

### ISSUE THREAD

**Issue by matheo** [angular/angular#8834]
* **I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current declaration**

Building my own Form Validators, I found that there's no easy way to get the ValidatorFn interface, as it's not included in the barrel, so we need to import it like:
```
import {ValidatorFn} from 'angular2/src/common/forms/directives/validators';
```

**Expected/desired declaration**

It would be cool to have something like:
```
import {ValidatorFn} from 'angular2/common';
```
so we can easily define our own validator functions with parameters enabled:
```
export class MyValidator
{
  static myValidatorFunction(param: any): ValidatorFn {
    return (control: AbstractControl): {[key: string]: any} => {
      ...
    };
  }
}
```
please include it in the barrel :)

**Statement** 

I know this isn't a bug, but it would be nice if this have a little attention as it's easy to resolve. I would submit a pull request but I'm not familiar enough with any JS builds there.
Thanks in advance

**Comment by jeffbcross** [comment]
Seems reasonable to me, @vsavkin thoughts?

**Comment by matheo** [comment]
Pretty nice stuff on your blog @vsavkin thanks!

**Comment by jjk3yz** [comment]
For anyone needing to import ValidatorFn while using rc1 the import statement is:

`import {ValidatorFn} from '@angular/common/src/forms/directives/validators';`

I tend to need this quite a bit in my components so it would be very welcome if added to the '@angular/common' barrel of fun.

**Comment by achimha** [comment]
With RC2 and the new forms module, the import has changed to

`import {ValidatorFn} from "@angular/forms/esm/src/directives/validators";`

**Comment by zoechi** [comment]
@achimha that's an invalid import. You should not import from `@angular/somemodule/src/...` because the `src/` directory is considered private implementation.

**Comment by matheo** [comment]
Then that's a reason to make `ValidatorFn` available in the RC2 forms barrel. cc @jeffbcross @vsavkin

**Comment by Tragetaschen** [comment]
I've got another use case:
```
var validators = [
    Validators.required,
    invalidNumber,
];
if (!(this.minValue == null || this.maxValue == null))
    validators.push(outOfRange(this.minValue, this.maxValue));
```
The push statement is a type mismatch error and I could fix this by using `var validatiors: ValidatorFn[]` as type annotation.

**Comment by matheo** [comment]
I'm using this code temporary:
```
import { AbstractControl } from '@angular/common/src/forms-deprecated/model';
import { ValidatorFn } from '@angular/common/src/forms-deprecated/directives/validators';

export class GenericValidator
{
  static required(errorMsg: string): ValidatorFn {
    return (control: AbstractControl): {[key: string]: any;} => {
      var val: string = control.value;
      return (val === '') ?
                 {'required': errorMsg} :
                 null;
    };
  }
}
```
a little example of my validator with a custom error message "coonfigured"

**Comment by matheo** [comment]
Thanks! :smiley:

**Comment by SaraSlm** [comment]
hi, i wanna write my own validator in rc5  (i know it in rc4)but i don't know how:( can you help to explain for how can i do this **please**?
