### ISSUE TITLE
Async Pipe should check for Symbol.observable to determine interop

### ISSUE THREAD

**Issue by robwormald** [angular/angular#8848]
The async pipe (and all places which leverage ObservableWrapper.isObservable) should check for a [Symbol.observable] property, rather than a naive `isPresent(thing.subscribe)`, and cast compatible values to an Observable. This will allow any Observable-ish type that implements Symbol.observable interop to work with the async pipe and other observable features.

**Comment by DzmitryShylovich** [comment]
is this still actual?
