### ISSUE TITLE
Dates formatted as isostrings - "invalid date"

### ISSUE THREAD

**Issue by yusijs** [angular/angular#8857]
* **I'm submitting a ...**
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**
When you pass in a date formatted as an isostring to the date-pipe, it returns "invalid date". As isostrings are now the defacto standard returned by node/express (from v.6, https://github.com/nodejs/node/commit/93d6b5fb68eae8b0912579980e17ebf0723ab2cc), they should be supported by the date pipe.

**Expected/desired behavior**
Passing a new Date().toIsoString() to the date pipe should work as it would with date objects.

* **What is the motivation / use case for changing the behavior?**
Currently I've created a toDate pipe that I use to chain all dates with (obj.date | toDate | date: 'format'). This is undesirable imo, and being able to pass isostrings would simplify the process. 

* **Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.1
* **NodeJS:** 6.2.0
 
* **Browser:** all
 
* **Language:** all

**Comment by michalstepien** [comment]
I think PR for this bug is now merged, so in rc2 probably will be correct.

**Comment by yusijs** [comment]
Oh, it's a bug? Any idea on the issue #?

**Comment by michalstepien** [comment]
Look on this PR:
https://github.com/angular/angular/pull/7794
https://github.com/angular/angular/pull/8038

**Comment by yusijs** [comment]
Fab - closing this off then.
