### ISSUE TITLE
Make RequestOptions easier to construct

### ISSUE THREAD

**Issue by jnizet** [angular/angular#8858]
- **I'm submitting a ...**
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

I find the design of `RequestOptions` and the classes it uses cumbersome:
- the constructor isn't type-safe: we can pass an object with a search attribute, for example, but it can be of any type
- the type of search should actually be `URLSearchParams`, but its constructor, instead of taking a hash of parameters, takes a raw query string, which is useless most of the time
- the headers should be of type Headers, and the structure of headers and parameters is the same (they're both a glorified `Map<string, string[]>`), but the way to construct instances of both classes is different.

Simply passing a search parameter for an Http service call is cumbersome:
- you need to import RequestOptions
- you need to import URLSearchParams
- you need to create a URLSearchParams
- you need to append a param 
- you need to create a RequestOptions with the search:

``` typescript
    import { RequestOptions, URLSearchParams } from '@angular/http';
    ...
    let params = new URLSearchParams();
    params.append('foo', 'bar');
    let options = new RequestOptions({
      search: params
    });
    return this.http.get(url, options).subscribe(...)
```

What I suggest in this feature request is to use a fluent type-safe builder to make that process less cumbersome. This builder allows to type-safely construct a RequestOptions, and to deal with parameters and headers is a similar way.

The above example, with the proposed builder, would be reduced to

``` typescript
    import { RequestOptions } from '@angular/http';
    ...
    let options = RequestOptions.builder().withParam('foo', 'bar').build();
    return this.http.get(url, options).subscribe(...)
```

Multiple options can of course be set in a fluent way. Here's a more complete example:

``` typescript
let options = RequestOptions.builder()
    .withUrl('/hello/world')
    .withMethod(RequestMethod.Get)
    .withParam('foo', 'bar')
    .withParams('hobbies', ['programming', 'cinema'])
    .withHeader('Accept', 'application/json')
    .build();
```

If you're OK with the idea, I can submit a PR.

Here's how the builder would look like:

`````` typescript
/**
 * A fluent builder to construct a `RequestOptions` object.
 *
 * ### Example
 *
 * ```typescript
 * let options = RequestOptions.builder()
 *     .withHeader('Accept', 'application/json')
 *     .withHeader('Authorization', `Bearer: ${token}`
 *     .withParam('question', question)
 *     .withParam('option', 'fast')
 *     .build();
 * ```
 */
export class RequestOptionsBuilder {

  private options: RequestOptions;

  constructor() {
    let options = new RequestOptions();
    options.search = new URLSearchParams();
    options.headers = new Headers();
    this.options = options;
  }

  /**
   * Sets the URL (replaces the previous one, if any)
   * @param url the URL to set in the request options
   * @returns {RequestOptionsBuilder} this builder, for chaining
   */
  withUrl(url: string): RequestOptionsBuilder {
    this.options.url = url;
    return this;
  }

  /**
   * Sets the method (replaces the previous one, if any)
   * @param method the method to set in the request options
   * @returns {RequestOptionsBuilder} this builder, for chaining
   */
  withMethod(method: RequestMethod | string): RequestOptionsBuilder {
    this.options.method = method;
    return this;
  }

  /**
   * Appends the given header
   * @param header the name of the header to append in the request options
   * @param value the value of the header to append in the request options
   * @returns {RequestOptionsBuilder} this builder, for chaining
   */
  withHeader(header: string, value: string): RequestOptionsBuilder {
    this.options.headers.append(header, value);
    return this;
  }

  /**
   * Sets (or replaces) the given header with the given values
   * @param header the name of the header to set in the request options
   * @param newValues the values for the header to set in the request options
   * @returns {RequestOptionsBuilder} this builder, for chaining
   */
  withHeaders(header: string, newValues: string[]): RequestOptionsBuilder {
    this.options.headers.set(header, newValues);
    return this;
  }

  /**
   * Sppends the given search parameter
   * @param param the name of the parameter to append in the request options
   * @param value the value of the parameter to append in the request options
   * @returns {RequestOptionsBuilder} this builder, for chaining
   */
  withParam(param: string, value: string): RequestOptionsBuilder {
    this.options.search.append(param, value);
    return this;
  }

  /**
   * Sets (or replaces) the given search parameter with the given values
   * @param param the name of the parameter to set in the request options
   * @param newValues the values for the parameter to set in the request options
   * @returns {RequestOptionsBuilder} this builder, for chaining
   */
  withParams(param: string, newValues: string[]): RequestOptionsBuilder {
    this.options.search.delete(param);
    newValues.forEach(value => this.options.search.append(param, value));
    return this;
  }

  /**
   * Sets (or replaces) the `withCredentials` flag with the given value
   * @param withCredentials the new value of the flag
   * @returns {RequestOptionsBuilder} this builder, for chaining
   */
  withCredentials(withCredentials: boolean): RequestOptionsBuilder {
    this.options.withCredentials = withCredentials;
    return this;
  }

  /**
   * Builds the request options
   * @returns {RequestOptions}
   */
  build(): RequestOptions {
    return this.options;
  }
}
``````

**Comment by zoechi** [comment]
Looks similar to #7370

**Comment by felixfbecker** [comment]
Why a fluent interface? It would be enough if we could pass object literals instead of the class instances that get converted under the hood. Less boilerplate.

**Comment by Bolza** [comment]
Yes, honestly this is much more complicated than it should be and doesn't really help writing readable code on the end-user side.

Just having `URLSearchParams` accepting an object literal in the constructor would be the perfect solution. 
Otherwise having a `fromObject` instance method of URLSearchParams.

**Comment by felixfbecker** [comment]
It would also be in line with how `Headers` object behaves in the fetch spec.

**Comment by arg20** [comment]
I came here hoping to find an issue dealing with the fact that I have to construct the `URLSearchParams` manually. I'm glad I'm not alone. It should be way easier to build, I mean, do I really want to turn an object into an instance of `URLSearchParams` by looping over the object properties and setting them on the instance of `URLSearchParams`?. That seems like it's complicated for nothing (unless I'm missing something). Please prioritize this. 

I get that there may be more complicated use cases but optimizing for 90% of the use cases is reasonable. I'd like to do `http.get(url, {search: {normal object}}` and have it converted behind the scenes, or, do something like `new URLSearchParams(myNormalObject)`.

**Comment by DzmitryShylovich** [comment]
According to [spec](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/URLSearchParams) :
> var URLSearchParams = new URLSearchParams(init);
init Optional
A USVString or a URLSearchParams instance.

**Comment by arg20** [comment]
I'm not sure that helps. it receiving a `string` is fine, but I also want it to receive a hash. Or the `http` methods accepting POJOs as a `search` equivalent.

**Comment by DzmitryShylovich** [comment]
Currently angular polyfills native URLSearchParams but in the future (probably ng3) they will switch to native impl so I don't think it will be supported.

**Comment by arg20** [comment]
Fair enough, maybe we can do something about it in the `http` module? I mean, for the simple use cases it just feels like overkill.

**Comment by felixfbecker** [comment]
Why can't HTTP just take an object hash and implicitly convert it so `URLSearchParams`. The native `fetch` API does the same for `headers`, you can pass an object hash or a `Headers` bag.
