### ISSUE TITLE
Lazy loading with RC Router

### ISSUE THREAD

**Issue by phiphou** [angular/angular#8861]
Hi,

Until beta 17, here is what I was doing for lazy load components : 

```
import {Component} from '@angular/core';
import {RouteConfig, ROUTER_DIRECTIVES, ROUTER_PROVIDERS} from '@angular/router-deprecated';
import {ClassicComponent} from './comps/classic.component';

@Component({
    selector: 'app',
    providers: [ROUTER_PROVIDERS],
    directives: [ROUTER_DIRECTIVES],
    template: require('./app.html')
})
@RouteConfig([
    { path: '/classic', name: 'Classic', component: ClassicComponent, useAsDefault: true },
    { path: '/lazy', name: 'Lazy', loader: () => require('es6-promise?global,chunk-name!./comps/lazyloaded.component')('Lazy') }
])
export class AppComponent {
  ...
}
```

and in Webpack ;

```
config.output = {
    chunkFilename: 'js/[name].chunk.js' 
};
```

I was using [es6-promise-loader](https://github.com/gdi2290/es6-promise-loader ) , that can expose this `name `property for webpack

So, everything worked well, I got my lazyloaded comp working, and in a separate named chunk.

But, as you can see, I was using the deprecated router.

Trying to update to new RC1 router, I can't make it working anymore.

I obviously apply the changes (`@Routes` instead of `RouteConfig`, no more route `name`, etc.) but I can't figure out how I can handle the "missing loader issue" (there's no more `loader `property in the new router, no?). 

I tried  this : 

```
@Routes([
    { path: '/classic', component: ClassicComponent, },
    { path: '/lazy', component: () =>  require('es6-promise?global,chunkname!./comps/lazyloaded.component')('Lazy') }
])
```

but got this error : 

`Error: Uncaught (in promise): No Directive annotation found on component`

and also tried this : 

```
@Routes([
    { path: '/classic', component: ClassicComponent, },
    { path: '/lazy', component: require('es6-promise?global,chunkname!./comps/lazyloaded.component')('Lazy') }
])
```
and now got this error: 

`Uncaught (in promise): No Directive annotation found on [object Object]`

So, can anybody help me to achieve this ? Thanks.

**Comment by michalstepien** [comment]
`new Route({path: '/drafts', component: 'app/drafts.js'})`

**Comment by michalstepien** [comment]
Sample:
https://github.com/angular/angular/pull/8455

**Comment by phiphou** [comment]
Thanks, I'll check. Do I find this in RC1 or do I have to clone the latest ?

**Comment by michalstepien** [comment]
Hmm, sorry I dont know :)

**Comment by vicb** [comment]
obsolete
