### ISSUE TITLE
RC1 Router - Back Button Does Not Work

### ISSUE THREAD

**Issue by ThiagoT1** [angular/angular#8863]
Plunker: https://angular.io/resources/live-examples/router/ts/plnkr.html

1) Click the popout button, as instructed here: https://angular.io/docs/ts/latest/guide/router.html
2) Click Heroes button
3) Click Mr. Nice
4) ALT + Left Arrow (shortcut for Back Button)
5) ALT + Left Arrow

Result: 
We are stuck on /heroes

Expected Result
We should be back on /crisis-center

**Comment by dloukadakis** [comment]
This was already fixed in 595bcdd1ac922fcdc52e50e057d8d85fc0a704d3
