### ISSUE TITLE
make INTERPOLATE_REGEXP customizable #7417

### ISSUE THREAD

**Issue by vicb** [angular/angular#8865]
`INTERPOLATE_REGEXP` was made configurable in #7417 

I'm not sure if this will work well [with i18n](https://github.com/angular/angular/blob/8e38291156623a82f10dc449a87cbbd3f8916447/modules/%40angular/compiler/src/i18n/i18n_html_parser.ts#L357)

/cc @laco0416

**Comment by mhevery** [comment]
A better design would be to pass in start/end delimiter rather than a generic RegExp.

**Comment by laco0416** [comment]
I agreed. I think `CompilerConfig#interpolateSymbols` is better
2016/05/27 5:43 "Miško Hevery" <notifications@github.com>:

**Comment by laco0416** [comment]
Do we need the following symbol settings?

- interpolationStart/End
- i18nStart/End
2016/05/27 9:13 "Suguru Inatomi" <laco0416@gmail.com>:

**Comment by pkozlowski-opensource** [comment]
This got fixed in master via c3fafa0651afd07b6fb5905b426121b2467e16c3

**Comment by laco0416** [comment]
@pkozlowski-opensource that commit was reverted. this issue's goal is re-implementatiom.
