### ISSUE TITLE
Jasmine Testing Dependency Injection Fails when using `provide`

### ISSUE THREAD

**Issue by jonnysamps** [angular/angular#8867]
**I'm submitting a bug report**

**Current behavior**
When using Jasmine to test services with dependencies, injection fails when using `provide` to provide mocks. This is the error.
`Error: Invalid provider - only instances of Provider and Type are allowed, got: [object Object]`

I looked at the source code and the method that is failing is in `@angular/core/src/di/reflective_provider.ts` in the `_normalizeProviders` function. On line 199 the test

`b instanceof Provider` 

fails even though `b` is indeed a `Provider`

**Expected/desired behavior**
I would expect DI to not fail and properly inject the mock.

**Example**
Plnkr: http://embed.plnkr.co/OCqLH555fmTzxAn0F0zy/
- **Please tell us about your environment:**
- **Angular version:** 2.0.0-RC1 
- **Browser:** Chrome
- **Language:** TypeScript 1.8.10

**Comment by KhalipskiSiarhei** [comment]
I have the same issue btw...

**Comment by zoechi** [comment]
This might be worth a try
```
new Provider(SomeClass, { useClass: SomeClassMock })
```

**Comment by jonnysamps** [comment]
@zoechi I did...

I did figure out that this works: 
```
{ provide: SomeClass, useClass: SomeClassMock }
```

**Comment by zoechi** [comment]
Ok, that's the new way. Thanks for the feedback.

**Comment by DzmitryShylovich** [comment]
`provide` was deprecated and removed.
@pkozlowski-opensource close?

**Comment by theBull** [comment]
@DzmitryShylovich any chance you could provide a reference as to what version of angular `provide` is removed in? There's a good chance that for anyone who mocks, for example, service providers for their unit tests, they lean heavily on `{ provide: someClass, useClass: someClassMock }`. This is the first I've heard of this and my unit tests are heavily reliant on that feature as I'm sure many others' are. I appreciate any tips :)

**Comment by DzmitryShylovich** [comment]
@theBull `provide` function was deprecated long long ago

**Comment by uglow** [comment]
I think this is the new way to do it: https://angular.io/docs/ts/latest/testing/#!#component-override

**Comment by mchambaud** [comment]
@uglow link is dead. What is the new way to do it?

**Comment by bensinther** [comment]
@mchambaud I guess this is the new link: https://angular.io/guide/testing#the-overridecomponent-method

**Comment by johnstaveley** [comment]
You say this was 'deprecated long ago' and yet the links to source code at the top of the page you reference still make extensive use of provide.
