### ISSUE TITLE
es5build failure

### ISSUE THREAD

**Issue by zzo** [angular/angular#887]
v$ node es5build.js  -d tmp

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: src/directives/foreach.js:11:5: super call is only allowed in derived constructor

Don't know if just getting rid of that 'super()' call is legit.

**Comment by caitp** [comment]
there are a lot of incorrect uses of super() in the tree, especially in the transpiler. Basically, it's never valid to use `super()` in a base class, so it's totally safe to remove it from base classes

**Comment by zzo** [comment]
thanks!  So maybe the original AtScript files should be directly transpiled into ES5 instead of ES6 and then into ES5?  I don't really want to hand-edit auto-generated files to get to ES5...

**Comment by caitp** [comment]
it's the source files that are wrong

**Comment by caitp** [comment]
Last time I counted, there were less than 10 instances of this error in the project, but that was about a week ago, who knows if anyone added any news ones =) anyways it should be cleaned up next week, hopefully

**Comment by zzo** [comment]
ah right I see them in the AtScript - ok so someone is cleaning it up I shouldn't make a PR?

**Comment by caitp** [comment]
there's one open, it's blocked on some fixes in traceur which need to ship first

**Comment by zzo** [comment]
great thank I'll follow https://github.com/angular/angular/issues/844
