### ISSUE TITLE
Injector allows binding undefined, `provide` function does not fail when incorrectly used

### ISSUE THREAD

**Issue by mprobst** [angular/angular#8870]
- **I'm submitting a ...**
- [x] bug report

**Current behavior**

It's very easy to get incorrect behaviour out of the injector, e.g. by accidentally forgetting to pass an object literal to `provide`. For example, the following will silently fail and bind `undefined` to `MyFoo`.

``` ts
provide(MyFoo, MyFooImpl)  // should be: {useClass: MyFooImpl}
```

**Expected/desired behavior**

This should fail on two levels:
- `provide` should check its arguments, and if none of the arguments are defined, given an error.
- it should be impossible to bind `undefined`, and probably also impossible to bind `null`.

_`undefined`_ is a common error (some import or property is missing, something went wrong)

Allowing to bind `null` means the code that gets instantiated by the injector gets a ctor parameter (field, whatever) that does not satisfy the contract the injected code expects; doing anything with it will fail. This means very hard to debug error cases, where once the app is running, much later something somewhere fails. Guice handles this by requiring bindings to be annotated as `@Nullable` if they should take null, but I think we might as well just disallow it; passing `null` values long distance through a large software system is prone to create very hard to debug error cases.

**Comment by tbosch** [comment]
This also happens when using the provider literals, e.g. the following code is wrong as the class is declared after the provider, but this is super hard to debug right now.
```
let providers = [{provide: SomeClass, useClass: SomeClass}];

class SomeClass {}
```

/cc @vsavkin
