### ISSUE TITLE
tsc-wrapped package can't be under @angular scope

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#8881]
Currently we have published `@angular/tsc-wrapped` to NPM, but our code imports `tsc-wrapped` instead. So offline compiler is broken at HEAD.

We don't have a test for this, because our tests mock up the node_modules directory with a `NODE_PATHS` hack, allowing us to load modules from a name that doesn't match what's in the package.json.

I think the right fix is for integration tests to run in a real installation.

**Comment by alexeagle** [comment]
cc @IgorMinar

**Comment by tbosch** [comment]
This is fixed
