### ISSUE TITLE
feature request (api docs): show import statement on documentation page

### ISSUE THREAD

**Issue by TTTee** [angular/angular#8883]
**I'm submitting a feature request**

It happens quite often, that I search for certain classes, interfaces, etc. to learn more about them. Then, when I decide to use one I need to know where it is located in order to create my import statement, but there is no such information. The information is present on the overview page, but that is not the most convenient way for looking it up. (see https://angular.io/docs/ts/latest/api/#!?apiType=Class).

**Current behavior**
_This affects all instances, but I use `OnInit` as an example._
The Reference page for the class `OnInit` does not contain any information about its location, except for its URL: https://angular.io/docs/ts/latest/api/core/index/OnInit-class.html

Therefore the following import statement is not obvious to the user.
```js
import { OnInit } from '@angular/core'
```

**Expected/desired behavior**
There are many ways to provide this information, currently I have these two in mind.

![import](https://cloud.githubusercontent.com/assets/6278665/15600910/43966522-23ed-11e6-977c-811357c92994.PNG)

![location](https://cloud.githubusercontent.com/assets/6278665/15600911/43977656-23ed-11e6-87a5-133f8c1229bf.PNG)

Any ideas / suggestions?

**Comment by TTTee** [comment]
Another possibility is to show the location directly in the header:

![image](https://cloud.githubusercontent.com/assets/6278665/15607810/e4f8ed68-2415-11e6-9203-f90c261a525e.png)

**Comment by JimTheMan** [comment]
+1 for the first way

`import {OnInit} from '@angula/core`

. Maybe a little more wordy, but it's straight to the point. No beating around the bush.

Especially to newbies this isn't totally obvious. I do like TTTee's latest suggestion though in addition to the import.

**Comment by robwormald** [comment]
Cool, I like this idea. Can you re-open this over on https://github.com/angular/angular.io and I'll poke somebody to make it happen 👍

**Comment by TTTee** [comment]
Ok, I just reopened it over on the agular.io repo. I added my last example there: https://github.com/angular/angular.io/issues/1535
