### ISSUE TITLE
Reducing render time when the ng2 app in iframe.

### ISSUE THREAD

**Issue by scotthuang** [angular/angular#8884]
* **I'm submitting a feature request**

**Current behavior**
I was using systemjs + angular2. The scirpt tag(src='angular.min.js')  will be contained in the page. When the ng2 app has a iframe which is also builded by ng2, the ng2 resource will be scripted twice. 

I was wondering if the app in iframe can use the parent's SystemJS variable so I wrote like this
```
if(self != top && typeof top['System'] != 'undefined'){
      pSystem = top['System'];
      System = SystemJS = pSystem;
}else{
      angularScript = document.createElement('script');
      angularScript.src = angularResUrl;

      document.body.appendChild(angularScript);
}
```

But the result is not working. The module which is imported form SystemJS will be not executed in iframe.

**Expected/desired behavior**
Ng2 resource can only be scripted one time if the parent window has contained the resource.

* **What is the motivation / use case for changing the behavior?**
If the app in iframe can share the ng2 module from parent window, it can be more fast to render the page. Though browser can cache the code, it is only cutted down a network request and what I want to do is reducing the ng2-scripting time( about 600 ~ 700 ms which you can see in chrome timeline ).

* **Angular version:** 2.0.0-beta.X 
2.0.0-beta.13 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
all 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart] 
ES6/7

**Comment by IgorMinar** [comment]
Hi Scott, thanks for reaching out but this particular issue is not suitable for our issue tracker. If you want System.js to reuse the resources across iframes, please file an issue against System.
