### ISSUE TITLE
ngModel does not update propterty of an object in an object

### ISSUE THREAD

**Issue by JoostvdB94** [angular/angular#8885]
* **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [X] I have no idea if it is a bug..
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**
When assigning a property of an object within a object, that property does not change.
for example:

    export class SomeComponent{
        private cities:string[];
        private person:Person;
    }

    export class Person{
        private name:string;
        private address:Address
    }
    
    export class Address{
        private street:string;
        private city:string;
        private houseNr:number;
    }

when using this in my template:

    <select [(ngModel)]="person.address.city">
        <option *ngFor="let city of cities" [value]="city">{{city}}<option>
    </select>

the city property of a user does get set when loading the page, but does not change upon selecting another option.

**Expected/desired behavior**
The `city` property should change upon selecting another option.

* **What is the motivation / use case for changing the behavior?**
This is unexpected behaviour. It should work, or else it should be documented if it works as intended.

* **Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.1 
 
* **Browser:** Chrome 50 (maybe others)
 
* **Language:** TypeScript 1.8.10

**Comment by zoechi** [comment]
Can you provide a plunker to reproduce?

**Comment by JoostvdB94** [comment]
Strange enough, the plunkr works..
http://plnkr.co/edit/KJj9AGCWaGDLeDh3gRAR?p=preview

**Comment by JoostvdB94** [comment]
Never mind. Forgot to make a setter, so the property was read-only.. :disappointed_relieved:
