### ISSUE TITLE
DatePipe not suporting timezone

### ISSUE THREAD

**Issue by FallenRiteMonk** [angular/angular#8887]
I get the following error: `Unsupported time zone specified undefined`
Using following pipe: `date:"MMMddyyyyHHmm"`
representing following Date (date.toString()): `Fri May 27 2016 01:10:03 GMT+1000 (AEST)`
running Angular rc1
on chrome 51.0.2704.63 (64-bit)
under opensuse 42.1

firefox 46.0 prints as expected: `May 27, 2016, 01:10`

**Comment by TTTee** [comment]
I don't think this a problem caused by Angular.

- This is what causes the Error, it is not Angular specific: https://chromium.googlesource.com/external/v8-i18n/+/b40edd742ce30f92b5538526361c937681e48f2c/src/date-format.js#285
- Also I've created a Plunker and it works fine for me on Chrome (Version 51.0.2704.63 m): http://plnkr.co/edit/Kg3TisMCrpGAJgskMXom?p=preview

**Comment by FallenRiteMonk** [comment]
The application doesn't crash due to the format of the Date element, but if you set you machines timezone to GMT+1000.
Just try setting you machines timezone and then open the Plunker you created, it won't work

**Comment by TTTee** [comment]
Windows only supports UTC, I can't change it to GTM+1000.
But still, I don't see how this is related to Angular. When you open your console in Chome and enter the following code, does that work?
```js
var myDate = new Date ("Fri May 27 2016 01:10:03 GMT+1000 (AEST)");
```

**Comment by FallenRiteMonk** [comment]
That works without problems

Then it has to be eighter a issue with chrome on linux, or with opensuse itself.

**Comment by felipedrumond** [comment]
@TTTee, my Chrome displays "May 26, 2016, 12:10". 
GMT-3 here.

05/May/16 here is displayed at the day before: 04/May/16

Is there a way to setup the application's time zone?

**Comment by ocombe** [comment]
You can now set the time zone in the date pipe in Angular V5.
