### ISSUE TITLE
Unexpected behaviour of RouteConfig

### ISSUE THREAD

**Issue by kuldeeppoonia** [angular/angular#8899]
Hello All,
I am new to Angular2 and working on a project last 15 days. I am using Angular2 2.0.0 RC.1 version 
I'm submitting a bug report about Route Config

**Current behavior**
I am working on a login page and want to navigate on another page on logged in. Problem is that  it doesn't navigate me on another page. The strange thing is that if I didn't insert any value in Username or Password field(for testing purpose) then it's navigate to my desired page. 

Here is my Code
Main.ts

@Component({
    selector: 'main-page',
    template: '<router-outlet></router-outlet>',
    directives: [ROUTER_DIRECTIVES],
})

@RouteConfig([
    {path: '/login', as: 'Login', component: LoginPage, useAsDefault: true},
    {path: '/locations/:id/...', as: 'Main', component: orderDetails}
])

LoginPage.ts
this.router.navigate(['Main', {id: '122222'}]);

Base url is **http://localhost:3000/#/login**
When I login with parameters then my page navigate to **http://localhost:3000/?#/login**.
I explore a lot but I didn't found from where **?** is coming in path.
while it should be **http://localhost:3000/#/locations/122222/selectlocation**

* **Please tell us about your environment:**
Angular version: 2.0.0-RC.1
 
* **Browser:** [Chrome ] 
 
* **Language:** [TypeScript ]

**Comment by zoechi** [comment]
This router is deprecated and I guess it's unlikely that issues will be fixed here anymore.

If it is a bug report a Plunker is required that allows to reproduce the problem (with the new router)

If it is a support question:  
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by vicb** [comment]
support & obsolete
