### ISSUE TITLE
Feature request: Add providers to @Injectable()

### ISSUE THREAD

**Issue by kjozic** [angular/angular#8901]
I would like to suggest to add providers expression to @Injectable() to simplify injection of a service into a service. Adding a service into providers list in bootstrap is unjustified if a service is used only once or twice.

**Comment by schippie** [comment]
@PascalPrecht  responded to this question before with a detailed explanation what the problems are with this idea: https://github.com/angular/angular/issues/5622#issuecomment-170916680
