### ISSUE TITLE
ngOnChange and Binding is not working for dynamically added Components

### ISSUE THREAD

**Issue by divyakumarjain** [angular/angular#8903]
I'm submitting a bug report where ngOnChange and binding is not working for dynamically added Components using ViewContainerRef.createComponent

**Current behavior**
1. ngOnChange is not called on Dynamically created Component
2. Binding of input properties not working for Dynamically created Component

**Expected/desired behavior**
1. ngOnChange should be called on Dynamically created Component
2. Binding of input properties should work for Dynamically created Component 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
http://plnkr.co/edit/MBYdMP?p=preview

* **What is the expected behavior?**
1. ngOnChange should be called on Dynamically created Component
2. Binding of input properties should work for Dynamically created Component 

* **What is the motivation / use case for changing the behavior?**
Any changes to data model outside dynamic component should flow into dynamic component. When we faced problem with Binding we though of using ngOnChange but that also did not work.

* **Please tell us about your environment:**

* **Angular version:** @2.0.0-rc.1 
 
* **Browser:** Tested on [Chrome 50.0.2661.102 m | Firefox 46.0.1| IE 11] 
 
* **Language:** [TypeScript | ES6 | ES5]

**Comment by pkozlowski-opensource** [comment]
It is not a problem if dynamic loading but rather the fact that you've got `@Input` \ `@Output` annotations in a super-class. Decorators are not carried over from base to sub-class.

If you can update your plunker to the latest rc.1 I can help fixing it.

**Comment by divyakumarjain** [comment]
If i look at systemjs.config.js in Plunker its using @2.0.0-rc.1.

Because of https://github.com/angular/angular/issues/5415 Derived class is using inputs and outputs parameter in ```@Component``` annotation instead of ```@input```\```@output``` annotation.

**Comment by divyakumarjain** [comment]
In Following Plunker i have removed inheritance and it uses ```@Input()``` & ```@Output()``` annotations. But still same behavior where ngOnChanges is not called and Two binding is not working.

http://plnkr.co/edit/oJh4daD4fBGArazBCw0g

**Comment by zoechi** [comment]
dynamic created components don't support `@Input()` or `@Output()` therefore I don't see the point of calling `ngOnChanges()`
`ngOnChanges()` is only called when Angular bindings update inputs. In your Plunker you are setting the value property imperatively. That also doesn't cause `ngOnChanges` being called for statically added components.

**Comment by divyakumarjain** [comment]
@zoechi thanks for your reply.

In that case what would be best way to achieve two way binding for dynamically components.

**Comment by zoechi** [comment]
Not sure what you mean. There is no two-way binding between dynamically added components.
If you want to reuse the same component statically and dynamically, you can create a wrapper element that contains the (previously) dynamically added component statically, and add the wrapper element dynamically.
Otherwise you might want to make the input a getter/setter where code can be added when the setter is called.

**Comment by divyakumarjain** [comment]
@zoechi Thanks for your clarification and suggestion on wrapper approach.

What i understand is that Dynamically added components does not support all the features which are supported by statically added components.  Example.

1. Support for Input and Output Annotation.
2. Support for two way bindings.

Do you think opening a feature request in Github will be right thing to do so that it can be tracked. And also Documenting these limitation would save unnecessary issue creation in github by other users.

**Comment by zoechi** [comment]
2. actually there is no two-way binding, it is just the combination of input and output binding.

There is one already. It's too cumbersome to look it up on the phone though ;-)
