### ISSUE TITLE
Documentation: Tutorial: Chapter7 Http: .ts file endings for for HTML files

### ISSUE THREAD

**Issue by rskokan** [angular/angular#8904]
* **I'm submitting a ...**
- [ x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

The Angular 2 tutorial at https://angular.io/docs/ts/latest/tutorial/toh-pt6.html several time has in the header of file excerpts .ts extension instead of .html.

Example:

> Add the following HTML to the **heroes.component.html**, just below the hero list (the *ngFor).
> 
> **app/heroes.component.ts (add)**
> ... HTML code here ...

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart]

**Comment by ericmartinezr** [comment]
@rskokan the repository to report issues with the website tutorial is over here https://github.com/angular/angular.io

**Comment by rskokan** [comment]
@ericmartinezr OK, copy-pasted the & closing this one
