### ISSUE TITLE
OnDestroy is not working on Directives

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular#8907]
Hi,

It seems that the OnDestroy isn't working on directives.

The below works on Components but doesn't work on directives.

```
ngOnDestroy() {
        console.log("ngOnDestroy called");
}
```

**Comment by ericmartinezr** [comment]
It's working perfectly fine for me http://plnkr.co/edit/w3aRF6fL2xPUbHioGLvn?p=info press the button to show/hide the div and check the console

**Comment by naveedahmed1** [comment]
Correct, it does work this way, in my case I have a div with a directive applied on that div. When I move away from that page, I assume that component and directive should be destroyed. But it seems that when I switch the page, it does destroy the component but the directive used in that page still exists, since the ngOnDestroy isn't called on directive in that case..

**Comment by ericmartinezr** [comment]
In that case you should reproduce it, it's impossible to say anything without a repro.

**Comment by naveedahmed1** [comment]
Below is just the shell directive which just logs  a line when its destroyed:

```
import { Directive, ElementRef, Input, Output, EventEmitter, OnDestroy} from '@angular/core';

@Directive({
    selector: '[infinite-scroll]'
})
export class InfiniteScroll implements OnDestroy {
    @Input() set infiniteScrollDistance(distance: number) {
        this._distance = distance;
    }

    @Output() scrolled = new EventEmitter();

    private _distance: number;

    constructor(private element: ElementRef) {
    }

    ngOnDestroy() {
        console.log("ngOnDestroy - Directive");
    }

}
```

This directive is used in template of a component which is mapped against a route.

`/products`

In products component I have imported the directive:

```
import { Component,OnDestroy } from '@angular/core';
import { InfiniteScroll } from './directives/infinite-scroll';


@Component({
    template: `
<div infinite-scroll [infiniteScrollDistance]="2" (scrolled)="list()">
List contents...
</div>
`,
    directives: [InfiniteScroll]
})
export class ProductsComponent  implements OnDestroy {

    constructor() {
    }

    ngOnDestroy() {
        console.log("ngOnDestroy - Component");
    }
}
```

Now when I visit /products page, the component is initialized and the directive is also initialized, verified it through ngOnInit. But when I click any link on that page, the Console log shows

ngOnDestroy - Component

but doesnt display 

ngOnDestroy - Directive


This means that the ngOnDestroy is called on Component, but not on the directive.

I also tested the approach you demonstrated in plunker, it works i.e. if I add *ngIf to my Div and set the *ngIf condition to false (I added a button on its click event I set *ngIf condition to false), It removed the DIV having directive from the DOM and also removed the attached Directive, in that case it showed the below message in Console:

ngOnDestroy - Directive

**Comment by theFifthElf** [comment]
I've seen the exact same issue in rc1. My directive is displayed in a 2nd level child route (a leaf route). On navigating away from the route ngOnDestroy is called in the route component but not on the directive. Other directives in my site destroy correctly so it appears it could be related to it's location in a child route (2nd level).

**Comment by pkozlowski-opensource** [comment]
@naveedahmed1 @theFifthElf could you please reproduce this issue in a plunker? Otherwise this one is not actionable as it stand and will be closed if we don't have reproduce scenario in a plunker.

**Comment by theFifthElf** [comment]
http://plnkr.co/edit/KxznheqcReYdQ1kuZo8r?p=preview

If you click between the Crisis Center and Heroes top routes and look in the console you'll see a log of 'created' every time mydirective is created but no matched destroy. (I've just added the directive to the crisis-list.component.ts.
Hope this is enough.

**Comment by theFifthElf** [comment]
I have attempted it and it worked fine in Plunker :(.
[Plunker](http://plnkr.co/edit/KxznheqcReYdQ1kuZo8r?p=preview) Clicking between Crisis Center and Heroes routes shows the destroyed and created methods firing on the directive I added.
One difference is that the Plunker uses the new router and my code uses the deprecated one. I'll personally re-visit this when I upgrade to the new router and have worked around the issue in my own project for now so I'm happy for it to close (speaking just for myself).

**Comment by pkozlowski-opensource** [comment]
Thnx for getting back to me on this @theFifthElf . I'm going to close this one for now as we don't seem to have any reproduce scenario. But more than happy to re-open when we've got one.

**Comment by GeorgeSokolovsky** [comment]
I've created a new plunker example, which demonstrate that `ngOnDestroy` doesn't trigger at directives when they used as a directive and their `elementRef` removed from DOM. But if we use directive as a component, then it works as expected.
Plunker example https://plnkr.co/edit/GsBBjxHpL1weoPvgTxe2?p=preview

**Comment by tytskyi** [comment]
@GeorgeSokolovsky your selector does not match (However i don't know why it is not reported as error).

Should be 
```typescript
@Directive({
  selector: 'mydirective, [mydirective]'
})
```

**Comment by GeorgeSokolovsky** [comment]
@tytskyi Seems like u r right, however the same directive not working at my project. Thanks, I'll invistigate my case.

**Comment by GeorgeSokolovsky** [comment]
I've find out that my problem was in using `ng-content` and structural directive `*ngIf`. So my problem not related to this issue. However I can't find docs for `ng-content` and I find it disturbing.
