### ISSUE TITLE
Angular 2 templates do not support <link rel='prefetch'>

### ISSUE THREAD

**Issue by RoxKilly** [angular/angular#8908]
Angular 2 rc1

If I add `<link rel="prefetch" href="http://website.loc/image.png">` to a basic webpage, the browser (Firefox 46) will prefetch the image.

However if I put the same tag within an Angular 2 template, the prefetching does not happen even though the `<link>` element shows up in the DOM once Angular is done parsing the template.

Is this expected?

**Comment by robwormald** [comment]
As far as I can tell, this behavior is specific to firefox, and unrelated to Angular. Firefox doesn't appear to prefetch images when the link is added after DOMContentLoaded, whereas Chrome does.

See https://plnkr.co/edit/LZIaH88LbBVcSPANg6U0?p=preview for a Angular-free reproduction. Whether or not this is to spec, I'm not entirely sure, but it's out of Angular's control in either case. I'll ask our DevRel team at Google next week.

**Comment by RoxKilly** [comment]
Thanks. Changed the title to reflect your find. It seems I'll need to learn the clumsy [JS way](http://blog.mgechev.com/2013/10/01/angularjs-partials-lazy-prefetching-strategy-weighted-directed-graph/) of preloading content and adapt it to Angular 2.
