### ISSUE TITLE
bizarre problem with css position

### ISSUE THREAD

**Issue by mcgri** [angular/angular#8909]
Hi
I am having a bizarre problem with  repeating component and assigned css position.

My real life component is a  user activities timeline. The timeline has a number of repeating sub components. The amount of entries could be more then 100.

The bizarre issue comes when I apply a css position  property to those components. Whole application became slower. If I apply any other rule..it's will be fine.

Here is a plunker for issue (Warning - there is 10K sub elements):
http://plnkr.co/edit/qeYm77HiPfdE4YNLC3h1?p=preview

If you go to app/number.html and add "position:relative" to .logentry-point class,then the mouse over animation of "Hello WOrld !!!" menu will became slower.

I also created vanila js example of this issue...and  it works just fine (Warning - there is 10K sub elements) :

http://plnkr.co/edit/HCDpGrqc3BRTFQ9KHCd0?p=preview

My real life application has less number of repeating sub components,but there are with logic.

I am not sure  how it's could be related to  ng2, but I could re-create the issue only using ng2. 

* **environment:**
Latest Google Chrome

* **Angular version:** 2.0.0-R.C 1
 
Thanks

**Comment by zoechi** [comment]
Any hint why you think this is caused by Angular?

**Comment by wesleycho** [comment]
Forked with the proper way to do styling in Angular 2 components [here](http://plnkr.co/edit/fS0cWiPWu5LcWpdDqdvA?p=preview).

If I had to suspect, something about `position: relative` is expensive on that many elements for the browser. I'm not sure there is much to be done on the Angular 2 side here.

**Comment by mcgri** [comment]
Thanks for the proper plunker and your opinion. I will close this ticket.
I had similar suspicion. So I created a vanila js plunker ,where script inserts 10k "li" elements with position attribute. The issue is not occurring there.  In my code,I have about 100 (repeating via ngFor) sub ng2 components with 3 "position:relative" elements.  I didn't had same issue in ng1 version of my code.  I will try to make my components bigger..and won't use  position property
