### ISSUE TITLE
angular2.0.0-beta.17 requires a peer of other packages?

### ISSUE THREAD

**Issue by jiapei100** [angular/angular#8913]
* **I'm submitting a ...**
- [x] bug report

**Current behavior**
npm WARN angular2@2.0.0-beta.17 requires a peer of es6-shim@^0.35.0 but none was installed.
npm WARN angular2@2.0.0-beta.17 requires a peer of reflect-metadata@0.1.2 but none was installed.
npm WARN angular2@2.0.0-beta.17 requires a peer of rxjs@5.0.0-beta.6 but none was installed.
npm WARN angular2@2.0.0-beta.17 requires a peer of zone.js@^0.6.12 but none was installed.

* **Angular version:** 2.0.0-beta.17

**Comment by pkozlowski-opensource** [comment]
Yes, it does.

**Comment by jiapei100** [comment]
Hi, pkozlowski:

I'm wondering during the installation of angular2, if there is a way to install all relied dependencies automatically?

Cheers
Pei

**Comment by pkozlowski-opensource** [comment]
Nope, you need to manually list all peer dependencies in your package.json file.

**Comment by jiapei100** [comment]
It looks like angular2 now is based on some old version of these packages ??? Even if I installed the most recent version of these packages, it still gives out UNMET PEER DEPENDENCY message.

> 
> jiapei@jiapei-GT72-6QE:~/Downloads$ sudo npm install -g es6-shim
> /usr/local/nodejs/lib
> └── es6-shim@0.35.1 
> 
> jiapei@jiapei-GT72-6QE:~/Downloads$ sudo npm install -g reflect-metadata
> /usr/local/nodejs/lib
> └── reflect-metadata@0.1.3 
> 
> jiapei@jiapei-GT72-6QE:~/Downloads$ sudo npm install -g rxjs
> /usr/local/nodejs/lib
> └─┬ rxjs@5.0.0-beta.8 
>   └── symbol-observable@0.2.4 
> 
> jiapei@jiapei-GT72-6QE:~/Downloads$ sudo npm install -g zone.js
> /usr/local/nodejs/lib
> └── zone.js@0.6.12 
> 
> jiapei@jiapei-GT72-6QE:~/Downloads$ sudo npm install -g angular2
> /usr/local/nodejs/lib
> ├── angular2@2.0.0-beta.17 
> ├── UNMET PEER DEPENDENCY es6-shim@^0.35.0
> ├── UNMET PEER DEPENDENCY reflect-metadata@0.1.2
> ├── UNMET PEER DEPENDENCY rxjs@5.0.0-beta.6
> └── UNMET PEER DEPENDENCY zone.js@^0.6.12
> 
> npm WARN angular2@2.0.0-beta.17 requires a peer of es6-shim@^0.35.0 but none was installed.
> npm WARN angular2@2.0.0-beta.17 requires a peer of reflect-metadata@0.1.2 but none was installed.
> npm WARN angular2@2.0.0-beta.17 requires a peer of rxjs@5.0.0-beta.6 but none was installed.
> npm WARN angular2@2.0.0-beta.17 requires a peer of zone.js@^0.6.12 but none was installed.
> 
>

**Comment by dland512** [comment]
Why zone.js is set up as a peer dependency of angular? What is the relationship between angular and zone.js that requires it to be a peer?
