### ISSUE TITLE
Angular 2 - Tour of Heroes Tutorial - TSScript - 3. Master/Detail - Expose the selected hero

### ISSUE THREAD

**Issue by sergru** [angular/angular#8914]
* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**
If `selectedHero` declared like this:
```JavaScript
    selectedHero: Hero;
```
then there is no `HEROES` ids/names shown; just a bullets (no styling) or empty items (with styling) like this:

-
##### My Heroes
 -
 -
 -
 -
id: 
name: ` name       `
-

**Expected/desired behavior**
HEROES list is fully visible.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

http://plnkr.co/edit/b0jQYbYfxmjuslM7czYQ?p=preview

from `Tutorial`:
1. Execute all stpes including `Expose the selected hero`
2. Wait for browser update.
3. HEROES list is created but witout any ids/names in each element.

* **What is the expected behavior?**

HEROES list is visible with ids and names in each elements.

* **What is the motivation / use case for changing the behavior?**

Update properties that are correct at the time of rendering/calculating.

* **Please tell us about your environment:**

Windows 7 x64 / Chrome browser 50.0.2661.102 m (64-bit) / Internet Explorer

* **Angular version:** 2.0.0-beta.X 
npm info: @angular/common@2.0.0-rc.1
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 

 Chrome browser 50.0.2661.102 m (64-bit)
 Internet Explorer 11.0.9600.18204

* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart] 

npm info: typescript@1.8.10

**Comment by ericmartinezr** [comment]
The plnkr for the part 2 is working fine for me https://angular.io/resources/live-examples/toh-2/ts/plnkr.html . If you found differences between the tutorial and the example working the place to it is https://github.com/angular/angular.io

**Comment by sergru** [comment]
Plunker from tutorial is final and it works. But plunker after 'Expose the
selected hero' and real local result are not as I expected. See this:
http://plnkr.co/edit/b0jQYbYfxmjuslM7czYQ?p=preview

The difference is that I removed

*<div *ngIf="selectedHero">* and  it's *</div>* from template allowing
undefined *selectedHero* to be shown.


Thanks, Serg

**Comment by sergru** [comment]
My expectations:

*HEROES* property completely independent from *selectedHero*, and it's data
will be shown on the page.

Serg

**Comment by sergru** [comment]
Hi Eric,

Looks like it is ts compiler issue. If I declare like this:
  selectedHero: Hero;
I see empty heroes list.

If I declare like these:

selectedHero: Hero = {};or

selectedHero = {};

**Comment by sergru** [comment]
Sorry, sent not finished message.

Anyway, if I declare as:

selectedHero: Hero = {};
or
selectedHero = {};


everything works as expected. I see the list and nothing in selected hero.


Thanks, Serg

**Comment by sergru** [comment]
Looks like it is ts compiler issue. If I declare like this:
```JavaScript
  selectedHero: Hero;
```

I see empty heroes list.

But if I declare `selectedHero` like these:

```JavaScript
selectedHero: Hero = {};
```
or
```JavaScript
selectedHero = {};
```
everything works as expected. I see the list and nothing in selected hero.

**Comment by sergru** [comment]
Actually it's even simpler. I am new with `TypeScript` and jus tby googling `typescript constructor` I found that you have to `new` the class. So this works perfectly:
```
    selectedHero = new Hero;
```
So it is not a `ts compiler` issue. Just use `typescript` objects correctly and everything else will be flowless.

**Comment by robwormald** [comment]
closing this as it seems like you've worked it out.
