### ISSUE TITLE
facing issue on first time loading app the nginit of component is not executed but on user click event the binding occurs.

### ISSUE THREAD

**Issue by varunnagarSeedoc** [angular/angular#8915]
* **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [x] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**

**Expected/desired behavior**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

* **Angular version:** 2.0.0-beta.14
 
* **Browser:** [Chrome XX ] 
 
* **Language:** [TypeScript X.X | ES6/7]

**Comment by zoechi** [comment]
This doesn't provide enough information to debug the issue.

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by varunnagarSeedoc** [comment]
ok sure, thanks for the direction.
