### ISSUE TITLE
Controlling zone when running inside Chrome App

### ISSUE THREAD

**Issue by fpmchu** [angular/angular#8916]
- **I'm submitting a ...**
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**
I'm running Angular2 inside of a Chrome App.  Some of Chrome's APIs (e.g. chrome.storage.local.set) is an async API foreign to Angular, and so changes caused by using such an API may not trigger change detection.

**Expected/desired behavior**
When an API like chrome.storage.sync.set is called in a Chrome App, the callback, when called, should restore the zone just like in setTimeout.  I'm talking Chrome App, but I imagine there are other APIs out there and other environments where zone.js does not work by default.  There are several solutions
1. Manually use Zone.current.wrap, as in
   `chrome.storage.local.set(items, Zone.current.wrap(myCallback))`
   This works (in zone.js 0.6), and if this is the right solution, Angular should provide the 'wrap' method in NgZone so we can call `this._ngZone.wrap()` instead so we don't rely on having `window.Zone`.
2. Override all the Chrome APIs manually, as in
   `chrome.storage.local.set = ...`
   This is quite a lot of manual work and prone to error.  My guess is zone.js would eventually provide a cleaner API for users to monkey-patch APIs, given the changes in 0.6 (adding wrap) and its clear anticipation of more server-side usage.  If this is the desired solution I should file a feature request against zone.js instead.
3. Use some other methods involving the current NgZone APIs which I have not discovered.  Perhaps I'm missing something and am overthinking it.
- **Language:** [TypeScript | ES6 | ES5]

**Comment by frederikschubert** [comment]
You can wrap the code in your callback in `NgZone.run()`. This way change detection is triggered when the callback has run.
This doesn't rely on window.NgZone and works also in a web worker.

**Comment by fpmchu** [comment]
Using `NgZone.run` seems to be a more messy workaround from using `wrap()`.  Basically I'll have to do
`chrome.storage.local.set(items, (results) => { this._ngZone.run(realCallback, results); });`
If that's the right approach, I still think Angular should provide the `wrap()` method since it's provided by zone.js 0.6.

**Comment by zoechi** [comment]
@fpmchu What do you think is the difference between `wrap` and `run`?

**Comment by fpmchu** [comment]
@zoechi `wrap` takes a callback and returns a callback that does `zone.run()` (technically speaking it's `runGuarded`).
In my case, code using `wrap()`
`chrome.storage.local.set(items, Zone.current.wrap(realCallback));`

code using `run()`
`chrome.storage.local.set(items, (results) => { Zone.current.run(realCallback, results); });`

With `run()` I would also have to spell out all the parameters for each callback so the callback can properly delegate.  It just seems quite messy is all.

**Comment by DzmitryShylovich** [comment]
isn't it a zonejs issue? I think it should be re-opened here https://github.com/angular/zone.js/

**Comment by DzmitryShylovich** [comment]
@fpmchu is this still relevant? can you re-opened it on https://github.com/angular/zone.js/ please? thanks

**Comment by mhevery** [comment]
closing since this is an issue with  https://github.com/angular/zone.js/
