### ISSUE TITLE
Input Range and ngForm is always null in IE

### ISSUE THREAD

**Issue by krunal039** [angular/angular#8921]
* **I'm submitting a bug for input range and ngForm is always null in ie 11.**
- [ ] bug report

We have sample form where we have ngForm and it works fine in chrome but input range control return always null and cannot get values of selected range.

**Expected/desired behavior**
Should return value for input range for ie 11

Demo plubker : http://plnkr.co/edit/owcvOZj99gUMB65TZXMx?p=preview

Angular version:** 2.0.0-beta.17 
 
* **Browser:** [IE 11 ] 
 
* **Language:** [ TypeScript : Version 1.8.10]

**Comment by aciccarello** [comment]
I can't get the plunker to load in IE11. I get the following error before the app loads. Are you missing any IE polyfills?

## Message
_Object doesn't support property or method 'keys'
	Error loading http://run.plnkr.co/MBGvWHHXhI663BY0/src/main.ts"_

## Stacktrace
> TypeError: Object doesn't support property or method 'keys'
>    at Anonymous function (Unknown script code:3322:9)
>    at Anonymous function (Unknown script code:3321:5)
>    at i (https://code.angularjs.org/tools/system.js:5:11510)
>    at i (https://code.angularjs.org/tools/system.js:4:31560)
> ...

**Comment by krunal039** [comment]
@aciccarello Thanks for comment, yes I did not include ie polyfills for IE11. Now updated same.

http://plnkr.co/edit/owcvOZj99gUMB65TZXMx?p=preview

**Comment by aciccarello** [comment]
Okay, thanks. I confirm that it does not work in IE11 but does in Chrome.

**Comment by krunal039** [comment]
@robwormald anyone help me to resolve?

**Comment by kara** [comment]
This one looks pretty stale. @krunal039 If you're still having problems with IE in the post-final version, please open a new issue with an updated plunker. Worth noting that we have a PR right now for a range value accessor, so you might want to wait for that to get in (in case it resolves your issue).
