### ISSUE TITLE
{Route,Url}{Segment,Tree} cannot possibly work

### ISSUE THREAD

**Issue by mustrumr** [angular/angular#8922]
s1=new UrlSegment('a1', {}, '')
    s2=new UrlSegment('a1', {}, '')
    s3=new UrlSegment('b1', {}, '')
    s4=new UrlSegment('b1', {}, '')
    t1=new UrlTree(new TreeNode(s1, [new TreeNode(s3, [new TreeNode(s2, [new TreeNode(s4)])])]));
    // t1 represents '/a1/b1/a1/b1'
    t1.parent(s3) == a1
    t1.parent(s4) == a1

Both 'b1' segments are indistinguishable. A `UrlSegment` _cannot_ be used as a pointer inside the UrlTree. Imagine `/list_items/42/42` meaning the 42-nd item in the 42-nd list. There using segments will fail miserably.

**Comment by mhevery** [comment]
`s3 !== s4` os while the objects have same shape they are different objects and it does work.

What is the actual problem your are running into.

**Comment by mustrumr** [comment]
My problem is that UrlSegments are used as pointers inside UrlTree (example: UrlTree.parent). A UrlSegment does not always identify a single segment of the URL.
