### ISSUE TITLE
Dependency injection doesn't work anymore in classes that extends BaseRequestOptions

### ISSUE THREAD

**Issue by templth** [angular/angular#8925]
* **I'm submitting a bug report**

**Current behavior**

I try to inject something into a class that extends the `BaseRequestOptions` one but I get `undefined`. This worked on beta versions but not on RC1.

See this plunkr to reproduce the problem: https://plnkr.co/edit/MK30JR2qK8aJIGwNqMZ5?p=preview.

**Expected/desired behavior**

I expect the dependency injection to be done correctly for such classes.

* **Angular version:** 2.0.0-beta.X 
 
* **Browser:**

Chrome but I think that it's not specific to a particular browser.

* **Language:**

TypeScript

**Comment by zoechi** [comment]
Cross-ref http://stackoverflow.com/questions/37549599/angular2-rc-baserequestoption-constructor-injection

**Comment by templth** [comment]
Yes, it's because of this question. Thanks very much, Günter, for pointing this out ;-)

**Comment by pliscki** [comment]
@templth 
I was facing the same issue you reported here when I tried to extend BaseRequestOptions to define a base URL, then I did what @zoechi suggest, but now it's not working for PUT operations. Are you having the same issue?

**Comment by whuang04** [comment]
Anyone know if this issue is fix on RC2 or RC3?  Thanks

**Comment by vicb** [comment]
Check the console logs for the plunker. Seems like your issue is due to 404 on loading the bundles. They have moved to bundles subdir as indicated in the release note, ie `https://npmcdn.com/@angular/http@2.0.0-rc.3/bundles/http.umd.js`

**Comment by whuang04** [comment]
This still doesn't seem to work in RC3.
`bootstrap(AppComponent, [
  HTTP_PROVIDERS,
  provide(RequestOptions, {useClass: JsonApiHeaderOptions})
]);
`

**Comment by Dinistro** [comment]
I have a similar problem and created an own issue: #9758. There is also a plunkr that demonstrates the problem: http://plnkr.co/edit/44imf9KpE06cIyQ395sg?p=preview

**Comment by Dinistro** [comment]
@vicb Did you take a look at my plunkr? Should this really be like this?

**Comment by Dinistro** [comment]
@templth This seems to be a bigger problem in the DI. This does not only affects the BaseRequestOptions, it affects (nearly) all Angular Base classes. More information here: https://github.com/angular/angular/issues/9146#issuecomment-230410616
