### ISSUE TITLE
Throw error when emitting from an @Output when not in dev mode

### ISSUE THREAD

**Issue by alxhub** [angular/angular#8927]
A common pattern I've seen is an Angular component wrapping a third-party library (e.g. Google Maps or Recaptcha APIs). These libraries are loaded outside of the Angular zone and thus any events that they initiate run outside of it.

Unfortunately, that means that if component attempting to wrap the library naively passes a callback to it, that callback will be executed outside the Angular zone. Frequently such callbacks attempt to emit `@Output` events.

It might be valuable to warn the developer in such cases that this is probably not what they want, by detecting whether the Angular zone is active for an `@Output` `EventEmitter.emit()` call and throwing if it's not. This check could be disabled in production mode, and could also be avoided by constructing an `EventEmitter` with a special flag if emitting events outside the Angular zone is indeed the desired behavior.

What do you think @mhevery @robwormald?

**Comment by robwormald** [comment]
sounds like a reasonable idea to me 👍

**Comment by wardbell** [comment]
I've run into this scenario multiple times and ways. Do we have a pattern? I'd like to show that in a cookbook.

**Comment by mhevery** [comment]
sounds reasonable to me as well.
