### ISSUE TITLE
OpaqueToken cannot be implemented in Dart

### ISSUE THREAD

**Issue by chalin** [angular/angular#8928]
**Summary**: The Angular DI [OpaqueToken][ot-api] wrapper class exists solely to create unique token instances, independent of any string argument value that might be provided to the constructor. Given that the `OpaqueToken` constructor must be `const` in Dart, and that `const` constructors are canonicalized, it fails to serve its purpose. In fact, **a `const` constructor that always returns a unique instance cannot be written in Dart.**

**Details**

Each new Angular DI [OpaqueToken][ot-api] is meant to be unique. Given that, in Dart, `OpaqueToken`s are meant to be used in annotations, they must be `const`; hence [the class is defined as][ot.dart] follows (note the `const` constructor):
```dart
class OpaqueToken {
  final String _desc;
  const OpaqueToken(this._desc);
  String toString() {
    return '''Token ${ this . _desc}''';
  }
}
```

But `const` objects are ***canonicalized*** (cf. [this commentary in the latex source][spec-latex], or correspondingly, [page 68 in the 4th ed. of the spec][spec-p68]). Those who might have a doubt can try:
```dart
@Component(
    selector: 'my-app',
    template: "<p>const OpaqueToken('abc') == const OpaqueToken('abc') is {{test}}</p>")
class AppComponent {
  final bool test = const OpaqueToken('abc') == const OpaqueToken('abc');
}
```
yields
```
const OpaqueToken('abc') == const OpaqueToken('abc') is true
```
> Note: since `OpaqueToken` doesn't override `==`, it uses the one defined in `Object`, which is [true iff the operands are `identical`][obj-eq].

This issue came to light during rework of the **angular.io DI chapters** (for [Dart][ngio-ot-dart] and [TS][ngio-ot-ts]). Issue https://github.com/angular/angular.io/issues/1563 has been opened to hold the thread of discussion of alternatives to `OpaqueToken`. Once an alternative has been agreed upon, at least for Dart, then `OpaqueToken` should be deprecated --- given that the Dart implementation is faulty and cannot be fixed, it should just be removed.

[ot-api]: https://angular.io/docs/ts/latest/api/core/index/OpaqueToken-class.html
[ot.dart]: https://github.com/angular/angular/blob/2.0.0-build.0700c8a.dart/lib/src/core/di/opaque_token.dart
[spec-latex]: https://github.com/dart-lang/sdk/blob/master/docs/language/dartLangSpec.tex#L3445
[spec-p68]: http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-408.pdf#page=72
[obj-eq]: https://api.dartlang.org/stable/dart-core/Object/operator_equals.html
[ngio-ot-dart]: https://angular.io/docs/dart/latest/guide/dependency-injection.html#!#opaque-token
[ngio-ot-ts]: https://angular.io/docs/ts/latest/guide/dependency-injection.html#!#opaque-token

**Comment by zoechi** [comment]
It was discussed a few times already if `const` in Dart couldn't be removed entirely. This might be another nail to its coffin ;-) @lrhn ?

**Comment by chalin** [comment]
Migrated to https://github.com/dart-lang/angular2/issues/35.
