### ISSUE TITLE
ngUpgrade nesting is running into issues.

### ISSUE THREAD

**Issue by mhevery** [angular/angular#8929]
Here is a faling test

https://github.com/shelbyd/angular/commit/f4bb56bf117cecce55cba7070687dcfd44d6917c

**Comment by mhevery** [comment]
@hannahhoward since you have done such an awesome work on the other ngUpgrade work, I was wondering if you could take a look at this?

**Comment by hannahhoward** [comment]
PR Submitted https://github.com/angular/angular/pull/8949

**Comment by mhevery** [comment]
Thank you for being awesome @hannahhoward!
