### ISSUE TITLE
CompilerConfig should take options as named params

### ISSUE THREAD

**Issue by laco0416** [angular/angular#8933]
* **I'm submitting a ...**
- [x] feature request

From https://github.com/angular/angular/pull/8906#discussion_r65288949

cc/ @vicb 

**Current behavior**

All are general arguments. 

```
class CompilerConfig {
  constructor(public genDebugInfo: boolean, public logBindingUpdate: boolean,
                     public useJit: boolean, renderTypes: RenderTypes = null,
                     interpolation: InterpolationConfig = null,
                     defaultEncapsulation: ViewEncapsulation = null) {
  }
}
```

**Expected/desired behavior**

```
interface CompilerConfigArgs {
  genDebugInfo: boolean;
  logBindingUpdate: boolean;
  useJit: boolean;
  renderTypes?: RenderTypes;
 ...
}

class CompilerConfig {
  constructor(args: CompilerConfigArgs) {
  }
}
```

**Comment by vicb** [comment]
@laco0416 do you have time to take a look at this ?

We need to keep backward compatibility, so the ctor signature should look like: 
`constructor(enDebugInfo: boolean | CompilerConfigArgs, <other args>)`

**Comment by laco0416** [comment]
One way is a static method

 `CompilerConfig.create({...})`

and make constructor deprecated

**Comment by laco0416** [comment]
https://github.com/angular/angular/commit/bc888bf3a102aa6bf62e134661022a9fdb5e2ff5 solved this.
