### ISSUE TITLE
Dependency injection for directives

### ISSUE THREAD

**Issue by Aetet** [angular/angular#8934]
* **I'm submitting a ...**
- [x ] feature request

**Current behavior**
There's no way to use dependency injection with directives. It'll be very interesting feature. For example:
We have two components **UserProfile** and **SuperNewUserProfile**. But don't want expose **SuperNewUserProfile** until it will be hardly tested at production. So we use flag isNewProfileEnabled = true. But if we place this logic to template we mix business logic with view logic. 

```ts
@Component({
  selector: 'my-app',
  template: `
<UserProfile ngIf="!isNewProfileEnabled "></UserProfile>
<SuperNewUserProfile ngIf="isNewProfileEnabled "></SuperNewUserProfile>
`,
  directives: [
    UserProfile
  ]
})

export class AppComponent { }
```

**Expected/desired behavior**

For more distiguish this behaviour - using DI would be helpful. 

```ts
@Component({
  selector: 'my-app',
  template: `
<UserProfile></UserProfile>
`,
  directives: [
    provide(UserProfile, { useFactory: () => (isNewProfileEnabled) ? 
      new UserProfile() :
      new SuperUserProfile()
    })
  ]
})

export class AppComponent { }
```

Is there way to achieve that without messing with template?

**Comment by mateuszkocz** [comment]
You can simply use that ternary operator directly in the directives array, or write a function to do that.

```
function getProfileComponent(isNewEnabled: boolean): Function {
  if (isNewEnabled) {
    return SuperUserProfile;
  } else {
    return UserProfile;
  }
}

@Component({
  selector: 'my-app',
  template: `
<UserProfile></UserProfile>
`,
  directives: [getProfileComponent(isNewProfileEnabled)]
})

export class AppComponent { }
```

Also, using a factory provider is a bit bothersome, since you need to manually provide dependencies of those component.

**Comment by Aetet** [comment]
Ok. At Dart side I cannot use dynamically loaded cocmponents. Only compile time construction.

**Comment by pkozlowski-opensource** [comment]
This is obsolete, as Dart-specific.
