### ISSUE TITLE
Documentation is inconsistent :(

### ISSUE THREAD

**Issue by alphashuro** [angular/angular#8935]
* **I'm submitting a ...**
- [x] bug report

**Current behavior**
There is Typescript code on javascript docs pages

**Expected/desired behavior**
I expect to see Javascript on a page titled "Angular 2 for JavaScript"

* **What is the motivation / use case for changing the behavior?** *
As a developer who swears by javascript, when I am using something and encounter a situation where I do not have enough information to solve the problem, I look at the docs. I looked at your docs for ViewChild (and a couple others as well) and clicked on "Angular 2 for javascript". however, the code examples there were written in type script, and there is no explanation for how to achieve the intended objective with javascript. This does not make sense to me. If you change it to JavaScript, I strongly believe it will actually make sense.

* **Angular version:** 2.0.0-beta.X 
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [ES6]

**Comment by zoechi** [comment]
Documentation issues should be reported in https://github.com/angular/angular.io. Can you please close here and reopen there?

**Comment by pkozlowski-opensource** [comment]
@alphashuro could you be please more precise when you say "on javascript docs pages"? Could you link to a concrete example? In any case, as pointed out by @zoechi (thnx!) all documentation issues should be reported in https://github.com/angular/angular.io so closing it here.
