### ISSUE TITLE
Problem with emulated view encapsulation when using [innerHTML] binding 

### ISSUE THREAD

**Issue by svi3c** [angular/angular#8936]
When I use emulated view encapsulation, HTML tags inserted via a property binding on `innerHTML` is scoped outside of the view encapsulation.

I created [this plunk](https://plnkr.co/edit/O39rx39hJz3QI3htagtp?p=preview) to reproduce the problem.
Note that the `<emulated>` element and it's children have an attribute like `_ngcontent-xxx-3`, except for `<styled>` element which was inserted via `[innerHTML]`.

**Comment by mhevery** [comment]
This works as intended, and will not be fixed. The encapsulation will only be done for templates of components.

**Comment by svi3c** [comment]
@mhevery, it's okay for me that the emulated view encapsulation is not completely emulating the behavior of shadow dom, if the support would cause performance impacts or very ugly hacks.

I was just trying to insert translations with html content as suggested in https://github.com/ocombe/ng2-translate/issues/86 and style this content.
My intention was that the inserted content is part of the component (when working with shadow dom, this seems to be a valid assumption) and as such should be stylable within this context.

In many Angular 1 apps I've seen or developed, HTML code was used within translations. This has the advantage that elements can be placed randomly inside the translated content.
I think it would be nice to be able to style this translated content per component.

Unfortunately using shadow dom is not a viable solution yet.
So do we have to use global styles to style this content or is there any other solution to get this working?

**Comment by zoechi** [comment]
You can try 

```
:host >>> .dynamic { color: red; }
```
where `.dynamic` is a selector that matches dynamically added HTML.

**Comment by svi3c** [comment]
Thanks @zoechi, `>>>` works for the emulated view encapsulation and `/deep/` seems to work with both encapsulation modes. And `/deep/` also works in combination with sass preprocessing.
