### ISSUE TITLE
@ContentChild is null in nested component when parent project it's content

### ISSUE THREAD

**Issue by vladimirivanoviliev** [angular/angular#8937]
* **I'm submitting a ...**
- [x] bug report

**Current behavior**
I'm trying to create panel (bar, menu) like component which is hierarchical.I have three components: Panel, PanelGroup (ul) and PanelItem (li). 

**Panel code:**

    @Component({
    selector: "panel",
    directives: [PanelGroup,PanelItem],
    template: `
    <panel-group>
      <ng-content select="panel-item"></ng-content>
    </panel-group>
    `})

    export default class Panel {}

**PanelGroup code:**

    @Component({
    selector: "panel-group",
    directives: [forwardRef(() => PanelItem)],
    template: `
    <ul>
      <ng-content></ng-content>
    </ul>`
    })

    export default class PanelGroup {
      @ContentChildren(forwardRef(() => PanelItem)) items;

      //I need to access children here and modify them eventually:
      ngAfterContentInit() {
        console.log(this.items.toArray()); //the array is always empty
      }
    }

PanelItem code:

    @Component({
    selector: "panel-item",
    directives: [forwardRef(() => PanelGroup)],
    template: `
      <li>
        <span (click)="onClick()">
            {{title}}
        </span>
        <panel-group>
            <ng-content select="panel-item"></ng-content>
        </panel-group>
      </li>`
    })

    export default class PanelItem {
      @Input() title = 'SomeTitle';
    }

As seen in the above example I try to get the content children inside the PanelGroup component, however the collection is always empty. Also tried to add selector to the 'ng-content' inside it - in this case the children are never rendered which is bit weird and seems like an issue (__the nested component `ng-content` selector and `@ContentChildren` are not finding the children__).

**Expected/desired behavior**

I expect that both `ng-content` selector and `@ContentChildren` are selecting the PanelItem children from the projected content.

**Demo to reproduce this behavior:**
[http://plnkr.co/edit/tKjmqYhTZOfSYfAfXCtJ?p=preview](http://plnkr.co/edit/tKjmqYhTZOfSYfAfXCtJ?p=preview)

The motivation to use content projection in this case is to reduce the component markup (in this case to type the PanelGroup on each hierarchy level). This allows defining the component levels more clearly as demonstrated below:

    <panel>
        <panel-item [title]="'Level 1'">
          <panel-item [title]="'Level 2'">
            <panel-item [title]="'Level 3'">
              <div>NestedContent</div>
            </panel-item>
          </panel-item>
        </panel-item>
      </panel>

* **Angular version:** 2.0.0-rc.1
 
* **Browser:** all
 
* **Language:** TypeScript | ES

**Comment by zoechi** [comment]
Cross-ref http://stackoverflow.com/questions/37554729/contentchildren-is-not-being-populated-when-parent-render-items-using-ng-conten

**Comment by ajoslin** [comment]
I'm experiencing this too.

**Comment by ajoslin** [comment]
I'm experiencing this too.

@gdi2290

**Comment by kemsky** [comment]
`ContentChildren` works only for the component-owner of template.

This works (panel owns content):
`<panel><div>some content</div></panel>`
but this does not (content belongs to component where this template is defined):
`<panel><ng-content></ng-content></panel>`

Most important here is lack of documentation for `ng-content`, which leads to confusion in any non-trivial example.

As a work around you could update children manually from parent: `child.setContent(this.content)`.

**Comment by BrainCrumbz** [comment]
@vladimirivanoviliev just a note on a typo. First class reported:

```
export default class PanelGroup {}
```

should probably be:

```
export default class Panel {}
```

**Comment by zoechi** [comment]
try

`@ContentChildren(forwardRef(() => PanelItem), {descendants: true}) items;`

**Comment by vladimirivanoviliev** [comment]
I already figured out that current behavior is expected a few days after reporting the issue. After some refactoring the code I came up with version that works which is similar to the following code (**removed the PanelGroup component entirely**):

```html
@Component({
    providers: [PanelBarService],
    selector: 'panelbar',
    template: `
        <ng-content select="panelbar-item"></ng-content>
    `
})

export class PanelBarComponent implements AfterViewChecked, OnChanges {
	//....
  	@ContentChildren(PanelBarItemComponent, { descendants: true }) private contentItems: QueryList<PanelBarItemComponent>;
}

@Component({
    selector: "panelbar-item",
    template: `<span
            #header
            (click)="onItemAction()"
        >
            {{title}}
        </span>
        <div
            *ngIf="!disabled && hasChildItems"
        >
            <div>
                <ng-content select="kendo-panelbar-item"></ng-content>
            </div>
        </div>
        `
})

export class PanelBarItemComponent implements AfterContentChecked, AfterViewChecked {
  @ContentChildren(PanelBarItemComponent, {}) private contentItems: QueryList<PanelBarItemComponent>;
}
```

**Comment by jofran73** [comment]
@kemsky I couldn't find anything on setContent as you mentioned in your workaround. Could you help me out?

**Comment by desfero** [comment]
Any updates to this?

**Comment by AnimaMundi** [comment]
@zoechi thanks, your suggestion fixed my problem!
