### ISSUE TITLE
Changing the value of an @Input field is not getting propagated correctly.

### ISSUE THREAD

**Issue by NisStrom** [angular/angular#8938]
* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**
If a bind a property to a child component and both the parent and the child are able to change the value of that, then the changes are not correctly propagated between the 2 components. In our code this problem occurred from the beginning, in the Plunker demo it happens after it correctly works for 2-3 times.

**Expected/desired behavior**
Changes of a bound property should always be propagated to the child or back to the parent component.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 
See the Plunker demo: https://plnkr.co/edit/EJaZj7vkIEfTGcV5nBHh?p=preview
Click the TextButtons 1 then 2 and repeat it multiple times. In the beginning the displayed name is getting updated and after 2-3 changes it stays the same,

* **What is the expected behavior?**
The name should always change between that set from the child and that from the parent.

**Comment by vicb** [comment]
use events (or a message bus) to communicate from the child back to the parent.
