### ISSUE TITLE
A component 'transcluded' with content isn't compiled

### ISSUE THREAD

**Issue by ajoslin** [angular/angular#894]
I don't know if this is a duplicate, but I figured I'd post anyway.

In this case, the `tab` component is never compiled.

```html
<ion-tabs>
  <ion-tab>CONTENT</ion-tab>
</ion-tabs>
```
```js
//tabs.js
import {Component, Template} from 'angular2/angular2';
import {Tab} from './tab';

@Component({
  selector: 'ion-tabs',
})
@Template({
  inline: `<div style="background: red;">
    <content></content>
  </div>`,
  directives: [Tab],
})
export class Tabs {
}
```
```js
//tab.js
import {Component, Template} from 'angular2/angular2';

@Component({
  selector: 'ion-tab'
})
@Template({
  inline: `<div style="background: olive;">
      <content></content>
    </div>`,
})
export class Tab {
  constructor() {
    alert('compiled');
  }
}

```

The alert never fires. I played this for awhile and I'm convinced it's a bug.

I end up with a `background: red` CONTENT

**Comment by ajoslin** [comment]
If I look into the DOM, it *is* transcluding the HTML. Just it's not compiling `tab` with angular.

**Comment by gdi2290** [comment]
do you have the repo on github? (it's easier if I you your env since the api changes a lot)

**Comment by ajoslin** [comment]
Closing because David East just proved me wrong!

**Comment by ajoslin** [comment]
@gdi2290 I'll put it up on Github soon.

**Comment by gdi2290** [comment]
yeah I just got it working. was it the backticks?
