### ISSUE TITLE
name or as in @Routes configuration when called from route.navigate

### ISSUE THREAD

**Issue by cmiagssh** [angular/angular#8940]
* **I'm submitting a ...**
- [ x ] bug report
- [ x ] feature request

**Current behavior**
I have defined a route synonyme called "Authentication" that I am trying to open with  this.router.navigate(['/Authentication']); . Unfortunately it tells me that the route does not exist. The synonym does not work with "name" as well as it does not work with "as" in the Route configuration. Am I doing something wrong? Is this a bug? Or does the behaviour only work for  <a [routerLink]="['/Authentication']">Link</a>

    @Routes([
          {
            path: '/authentication',
            component: Authentication,
            name: 'Authentication',
            as: 'Authentication'
          }
        ])
    export class MyComponent {
        ....
    }
    
    export class SomeOtherClass {
        constructor(
            private router: Router
        }
        private navigateToAuthentication() {
            this.router.navigate(['/Authentication']);
        }
    }

EXCEPTION: Error: Uncaught (in promise): Cannot match any routes. Current segment: 'Authentication'. Available routes: ['/', '/authentication'].

**Expected/desired behavior**
In my opinion "this.router.navigate(['/Authentication']);" and "<a [routerLink]="['/Authentication']">Link</a>" should work in the same way.

* **What is the expected behavior?**
Forward the page on route synonyms when calling "this.router.navigate(['/Authentication']);"

* **What is the motivation / use case for changing the behavior?**
Consistent behaviour over all functions that do the same thing

* **Please tell us about your environment:**

    "dependencies": {
        "@angular/common": "2.0.0-rc.1",
        "@angular/compiler": "2.0.0-rc.1",
        "@angular/core": "2.0.0-rc.1",
        "@angular/platform-browser": "2.0.0-rc.1",
        "@angular/platform-browser-dynamic": "2.0.0-rc.1",
        "@angular/router": "2.0.0-rc.1",
        "es6-shim": "^0.35.0",
        "reflect-metadata": "0.1.3",
        "rxjs": "5.0.0-beta.6",
        "systemjs": "0.19.26",
        "zone.js": "^0.6.12"
      },

* **Angular version:** 2.0.0-rc.1
 
* **Browser:** [all] 
 
* **Language:** [TypeScript 1.8.10 | ES5]

**Comment by skreborn** [comment]
As far as I can see, the only problem is that you are trying to navigate to `Authentication` (upper case), while your defined route is `authentication` (lower case).

**Comment by cmiagssh** [comment]
Thats where the synonym (defined with as or name) should kick in.

https://www.youtube.com/watch?v=z1NB-HG0ZH4
describes this feature on the old router

possibly the routing has changed as described in 
https://www.youtube.com/watch?v=d8yAdeshpcw

Unfortunately I have not found a complete documentation on this issue

**Comment by skreborn** [comment]
The new Router doesn't seem to have a `name` or an `as` property. The only two defined are `path` and `component`.

https://github.com/angular/angular/blob/master/modules/%40angular/router/src/metadata/metadata.ts#L23

**Comment by cmiagssh** [comment]
Thank you

**Comment by adduss** [comment]
Ok but how to add fallback route in that case ?

@Routes([
  { path: '/dashboard', component: Dashboard },
  { path: '/login', component: Login },
  { path: '*',        component: Login }  // --> this not redirect to login page for localhost:XXXX
])

**Comment by skreborn** [comment]
@adduss This seems to be a totally unrelated question. Please consider opening a new issue next time. To have the `Login` component show up, define the path as a single slash (`/`).

**Comment by adduss** [comment]
I thought that this is suitable place because now there is no navigateUrl in Routes and it was in RouteConfig. Thank you for the answer !!!

**Comment by cmiagssh** [comment]
There is navigateByUrl. It might do the same...
