### ISSUE TITLE
Dynamically resolved / created components got empty text nodes instead of an interpolated string

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#8941]
* **I'm submitting a ...**
- [ x] bug report

**Current behavior**

Assuming a component:

```javascript
@Component({
  selector: 'overly-container',
  template: '<h1>Overly container {{foo}}</h1>'
})
class OverlyContainer {
  foo = 'bar';
}
```

and this code to resolve + create component:

```javascript
this._componentResolver.resolveComponent(OverlyContainer).then((cf: ComponentFactory) => {
      var cRef = cf.create(this._injector);
      console.log(cRef.location.nativeElement);      
    });
```

The console will log `<h1></h1>`.

**Expected/desired behavior**

The console should log `<h1>Overly container bar</h1>`

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

http://plnkr.co/edit/Qg6TX9G6q7k71x4dblXE?p=preview

* **Please tell us about your environment:**

rc.1

**Comment by zoechi** [comment]
Same issue as with DCL (https://github.com/angular/angular/issues/6223#issuecomment-206955628)

Calling
```
this.appRef._loadComponent(cRef);
```
makes it show `Overly container bar`
http://plnkr.co/edit/B4RhQ4wxQRvDIKQmMhc3?p=preview

**Comment by pkozlowski-opensource** [comment]
@zoechi `_loadComponent(cRef);` is a private API so I don't think this is a way to go. 

Generally speaking the question here is: how to load a component "outside" of ng2 application element (a typical use-case for this are modals, tooltips and the like).

**Comment by pkozlowski-opensource** [comment]
@tbosch based on your suggestion from yesterday I was trying to add a component to any view container (since my understanding now is that it would connect components change detector to its parent and take care of the lifecycle hooks). 

But the problem I'm facing here is that I'm triggering load from a service (an API to open modals / tooltips would be encapsulated as a service). 

Maybe we should have some public API to do what `AppRef::_loadComponent` does? Or is there is a better way?

**Comment by tbosch** [comment]
@pkozlowski-opensource, where does this service live? On a component or is it provided to `bootstrap`?
I think we should allow any service that lives inside of a component to inject a `ViewContainerRef`.

**Comment by pkozlowski-opensource** [comment]
@tbosch so the use-case here is that I want to create a `ModalService` that people can use to open modals. But I'm afraid that I won't be able to control where this service gets declared in the user's apps. So in the absolute I can't exclude that people will stick it on `bootstrap`.... And it kind of makes sense since there is no point in having more than one modal service for the entire app. 

Are you saying that `ViewContainerRef` should be injectable into services if a service was provided as part of a component's providers? I'm assuming that it isn't supported today?

**Comment by pkozlowski-opensource** [comment]
Basically what I'm trying express here is:
* create a component from a `ComponentFactory`
* get it's nodes and stick under a provided selector (possibly outside of the app's root node)
* hook component's change detection into app's root element cd 
* wire lifecycle hooks so they follow lifecycle of an app element

Obviously I would be more than happy with any other method of creating a component "outside" of the app's element + making it "live" (cd + lifecycle).

**Comment by zoechi** [comment]
My approach http://stackoverflow.com/a/36566919/217408. 
Use a shared service to communicate between two indepently bootstrapped components.  
Not beautiful either. A simple official API for what `AppRef::_loadComponent` does, would be much better.

**Comment by zoechi** [comment]
@pkozlowski-opensource did you find a solution to make change detection work for components added this way?

**Comment by pkozlowski-opensource** [comment]
@zoechi nope. Closed this one before I can better isolate what I want from ng2 :-) For now it seems like I need to get a hand on _some_ ViewContainerRef (probably one of the root component). Will open a more focused issue and report back here.

**Comment by pkozlowski-opensource** [comment]
@zoechi here is a new issue with a more specific request: #9293
