### ISSUE TITLE
bug(test-runner): karma internal-reporter not producing output after upgrade to 0.13.20

### ISSUE THREAD

**Issue by hannahhoward** [angular/angular#8942]
* **I'm submitting a ...**
- [x ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**
Run ./scripts/ci-lite/test_js.sh or just run karma manually
No . output on successful test
Failed tests fail silently

**Expected/desired behavior**
Each successful test should produce an '.' output
Each failure should produce an error message

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: 

Clean npm install to update Karma
Run ./scripts/ci-lite/test_js.sh or just run karma manually
No . output on successful test
Failed tests fail silently

* **What is the expected behavior?**

Each successful test should produce an '.' output
Each failure should produce an error message

* **Please tell us about your environment:**

Mac OS X

* **Angular version:** 2.0.0-beta.X 
 
Latest Master

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart] 

n/a

**Notes:**

Believe the karma commit that broke the reporter is this one: https://github.com/karma-runner/karma/commit/486c4f31c43fbbd63450b0aa6c64d3cb4c78ada4

Was able to get reporter working again by changing line 55 of `tools/karma/reporter.js` from:

```javascript
  DotsReporter.call(this, formatter, false)
```

to

```javascript
  DotsReporter.call(this, formatter, false, config.colors) 
```

but not sure if this is the correct fix.

**Comment by mhevery** [comment]
Send a PR?

**Comment by hannahhoward** [comment]
See #8977
