### ISSUE TITLE
Event Emitter event not handled

### ISSUE THREAD

**Issue by devology-micko** [angular/angular#8943]
* **I'm submitting a ...**
- [ x ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

I don't know whether this issue is a bug (it smells like one), and I've not had any help on StackOverflow so I'm posting here for some help.

http://stackoverflow.com/questions/37532434/angular2-event-emitter-rxjs-event-not-fired

* **Please tell us about your environment:**

* **Angular version:** 2.0.0-RC 1 - I have only tried it on Chrome and Safari. LanguageTypescript.

**Comment by vicb** [comment]
Please add a plunker to reproduce the issue (with the least possible code)

**Comment by pkozlowski-opensource** [comment]
Closing as we don't have any reproduce scenario.
