### ISSUE TITLE
DynamicComponentLoader not correctly parsing self-closing divs.

### ISSUE THREAD

**Issue by tchoulihan** [angular/angular#8944]
* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**
HTML loaded: `<div class="test"/>`

```ts
this.dcl.loadAsRoot(TestComponent, loc, this.injector).then(componentRef => {
  componentRef.instance.test = this.test[0];
  (<any>this.appRef)._loadComponent(componentRef);
});
```

Is rendered as: `<div class="test">`, without the close tag, meaning many elements are grouped as subelements.

This also might pertain to #6223 

**Expected/desired behavior**
It should render as:  `<div class="test"/>`

* **Angular version:** 2.0.0-rc.1

**Comment by pkozlowski-opensource** [comment]
Self-closing divs are not valid HTML5. Only void elements can be optionally closed in HTML5. Closing as invalid (btw it has nothing to do with #6223)

**Comment by tchoulihan** [comment]
Okay, thanks.
