### ISSUE TITLE
Router Outlet  Content

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular#8945]
I think in previous version of Angular the contents we add to router outlet tag were overridden when the component is loaded.

For example in the below case "Loading..." was replaced with the component's content when the component was loaded. But now, the component's content are appended to the existing contents in router-outlet.

<router-outlet>Loading...</router-outlet>

Wouldn't it be better to add this behavior back?

This can also allow us to show some contents on the shell page on initial load.

**Comment by CaptainCodeman** [comment]
I think you are perhaps confusing the `<app>Loading ...</app>` approach (where the content is replaced once the app loads) with the use of `<router-outlet>`. For the latter, the routed components aren't even loaded within it, it's just a placeholder and they are loaded next to it as siblings in the DOM.

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20782714/60f05eaa-b7c9-11e6-9006-f7beb8bef322.png)
