### ISSUE TITLE
Annotations looks dangerously big

### ISSUE THREAD

**Issue by jamm** [angular/angular#895]
That line 9: http://youtu.be/Xw93oketp18?t=11m3s (db binding) bothers me. Why it's not in constructor? Should we move DI from constructors to annotations? (usually we shouldn't hardcode path to DB in controller). How will look analogue in ES6?

**Comment by gdi2290** [comment]
so if I understand this correctly you can avoid this via moving your Di to the app level


```es6
import {bootstrap} from 'angular2/angular2';
import {bind} from 'angular2/di';
import {AngularFire, FirebaseArray} from 'firebase/AngularFire';
import {App} from 'components/app/app';

export function main() {
  return bootstrap(Tabs, [
    bind(Firebase).toValue(new Firebase('https://webapi.firebaseio-demo.com/test'))
  ]);
}
```
then in your components you only need to use Firebase constructor as the token. Again if I'm understanding this correctly I think that's how you avoid that

**Comment by jamm** [comment]
thanks, @gdi2290
