### ISSUE TITLE
ngUpgrade not managing digest cycles properly

### ISSUE THREAD

**Issue by thelgevold** [angular/angular#8951]
* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**
ngUpgrade doesn't seem to always synchronize its own digest cycles with digest cycles triggered by the Angular 1 code. My suspicion is that zone based modifications made to async functions like setTimeout aren't completely accounted for by ngUpgrade. 

ngUpgrade makes explicit calls to rootscope.apply() without checking if there is another digest cycle already in progress. This results in digest already in progress errors under certain conditions.

Routing seems to play a role in this, but I am not sure if this is the only scenario. 

I have created a plunker to reproduce the problem
https://plnkr.co/edit/9YwVs1UkjVjydzcF21QV?p=preview

The example is a bit contrived in that it makes an http call and navigates - all inside a setTimeout. I am encountering the same error inside a larger application, but this was the only way to reproduce the symptoms in a simple plunker. The scenario might be contrived, but still seems like a valid use case.

**Expected/desired behavior**
There should not be digest already in progress errors as a result of ngUpgrade calling rootscope.apply

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 
Just load this plunker to reproduce: https://plnkr.co/edit/9YwVs1UkjVjydzcF21QV?p=preview

This looks like a problem related to making unprotected $apply calls from ngUpgrade. My guess is that there needs to be a safe guard around these calls (e.g. rootScope.$applyAsync() or similar). Currently the calls are not checking to see if there is another cycle already in progress. Not sure if this is a simple as using rootScope.$applyAsync() to only trigger a digest if one isn't already running though.

Including the $apply call from ngUpgrade here:
```
ng1compilePromise = new Promise(function (resolve, reject) {
                ng1Module.run([
                    '$injector',
                    '$rootScope',
                    function (injector, rootScope) {
                        ng1Injector = injector;
                        ngZone.onMicrotaskEmpty.subscribe({ next: function (_) { return ngZone.runOutsideAngular(function () { return rootScope.$apply(); }); } });
                        UpgradeNg1ComponentAdapterBuilder.resolve(_this.downgradedComponents, injector)
                            .then(resolve, reject);
                    }
                ]);
            });
```

I am aware of https://github.com/angular/angular/issues/8004, which seems related, but I am am opening a new bug since this is on rc 1 instead of Beta 14. Also, this reproduces the issue from the Angular 1 side, whereas the other bug reproduces the problem from the Angular 2 side of things.

* **Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.1 
 
* **Browser:** [Chrome] 
 
* **Language:** [TypeScript]

**Comment by thelgevold** [comment]
@mhevery I wanted to run a potential suggestion by you. I have not tested this extensively, but tried quickly in a plunker to change ```rootScope.$apply()``` to ```rootScope.$applyAsync()``` in ```ng1compilePromise```

My understanding is that this will allow the the code to piggy back on an existing digest cycle if one already exists. Again have not had a chance to test this extensively, but just hacked the upgradeAdapter file locally and the plunker seemed to no longer throw the error, but I am not sure if this idea will have other unintended consequences. 

Is there a reason why the code calls $apply directly without checking for existing digest cycles? Or is this an idea worth pursuing?

**Comment by thelgevold** [comment]
Looks like my suggestion fixes the issue in my actual application as well.

**Comment by mhevery** [comment]
Would you be willing to create a PR with the fix?

**Comment by thelgevold** [comment]
@mhevery Yes, definitely. I will make a PR.
Thanks!

**Comment by thelgevold** [comment]
Fixed by https://github.com/angular/angular/pull/9054
