### ISSUE TITLE
Router - Make relative navigation easier

### ISSUE THREAD

**Issue by Hacklone** [angular/angular#8956]
* **I'm submitting a ...**
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

I don't know if this is a bug or by design (in this case this is a feature request :))

**Current behavior**
DI seems to inject the parent's Router in embedded child component with routes.

**Expected/desired behavior**
In a reusable component with inner routes I want to be able to navigate with the injected router, without knowing about my host component's routes.

**Plunker example**
**https://plnkr.co/edit/b5cTMlLjPo63eeeU3rjw?p=preview**

**Error:**
_Cannot match any routes. Current segment: 'child'. Available routes: ['/parent']._

 **What is the expected behavior?**
this.router.navigate(['/child-route']); would work in a component, without knowing the parent path.

* **What is the motivation / use case for changing the behavior?**
A reusable component that has routing in it and doesn't have to know about hosting routes.

* **Angular version:** 2.0.0-rc1
 
* **Browser:** [all] 

* **Language:** TypeScript

**Comment by zoechi** [comment]
I guess that's as designed

    routerOnActivate(curr: RouteSegment, prev?: RouteSegment, currTree?: RouteTree, prevTree?: RouteTree) : void {
      this.router.navigate(['child'], curr);
    }

should do what you want. The 2nd parameter tells the router relative to what segment the router should navigate.

https://plnkr.co/edit/Zw2tGzJmdM2uR9knaHh3?p=preview

**Comment by Hacklone** [comment]
Oh :)
 
That good to know and I see the logic between it but it's still kind of more code than I'd expect, so that I'll have to save the current RouteSegment from the routerOnActivate() and always use it with every navigation.

And how about [routerLink] does that work out of the box? Does it work without the parent path?

**Comment by zoechi** [comment]
I don't know by heart. I had to try myself, but I assume that's what `routerLink` does.
I guess it will derive the segment from the prefix, like  `/path`(relative to root segment), or `./path` (relative to current segment, probably the same as just `path`), or `../path` (relative to parent segment)
You could try if `this.router.navigateByUrl()` has the expected behavior (like explained for `routerLink` above)

**Comment by Hacklone** [comment]
```this.router.navigateByUrl()``` is absolute and throws a (not too beautiful) error if you provide a not absolute url: 
```error
this._remaining.startsWith is not a function
    at _UrlParser.peekStartsWith (https://npmcdn.com/@angular/router/router.umd.js:1418:87)
    at _UrlParser.parseSegments (https://npmcdn.com/@angular/router/router.umd.js:1443:22)
    at _UrlParser.parseRoot (https://npmcdn.com/@angular/router/router.umd.js:1435:33)
    at _UrlParser.parse (https://npmcdn.com/@angular/router/router.umd.js:1431:29)
```

So I converted this issue into a feature request to provide an easier (more beautiful) way to do relative navigation.

**Comment by vsavkin** [comment]
It seems the issue was opened before the last router rewrite. And it doesn't look like the issue still makes sense. I'm closing it. Please reopen it if you think it still makes sense.
