### ISSUE TITLE
Incorrect NgFor Documentation

### ISSUE THREAD

**Issue by marvinscharle** [angular/angular#8957]
The [documentation page for NgFor](https://angular.io/docs/ts/latest/api/common/NgFor-directive.html) is currently pointing to an old file version (Beta 17).

This means there are incorrect statements about NgFor's syntax:

```
<li *ngFor="let item of items; #i = index">...</li>
<li template="ngFor #item of items; #i = index">...</li>
<template ngFor #item [ngForOf]="items" #i="index"><li>...</li></template>
```

**Comment by brandonroberts** [comment]
This is the correct link for the NgFor documentation that contains the correct syntax: https://angular.io/docs/ts/latest/api/common/index/NgFor-directive.html

How did you get to that link?

**Comment by pkozlowski-opensource** [comment]
@marvinscharle thnx for reporting. Indeed it looks like there is an old link hanging around... 

But as brandonroberts  pointed out (thnx so much for helping out with issues!) all the documentation lives in a separate repository: https://github.com/angular/angular.io/issues

@marvinscharle would you mind opening an issue in https://github.com/angular/angular.io/issues? This would be very much appreciated!

**Comment by marvinscharle** [comment]
@pkozlowski-opensource done

**Comment by pkozlowski-opensource** [comment]
Thnx @marvinscharle !

**Comment by marvinscharle** [comment]
Guys over at angular.io think this is your problem @pkozlowski-opensource 

See: angular/angular.io#1588

**Comment by pkozlowski-opensource** [comment]
I will talk to @wardbell - I think it wasn't clear that the issue is about pruning old pages still being published.
