### ISSUE TITLE
NgControlName update should not be internal

### ISSUE THREAD

**Issue by Dinistro** [angular/angular#8958]
* **I'm submitting a ...**
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**

At the moment, the update EventEmitter in `NgControlName` is internal: [source](https://github.com/angular/angular/blob/04220be8fd8efb265a2f74812a6b7b7e91be0b94/modules/%40angular/common/src/forms/directives/ng_control_name.ts#L102-L103).

* **What is the expected behavior?**

It should be like in `NgModel`, not internal: [source](https://github.com/angular/angular/blob/04220be8fd8efb265a2f74812a6b7b7e91be0b94/modules/%40angular/common/src/forms/directives/ng_model.ts#L65).

* **What is the motivation / use case for changing the behavior?**

It makes it accessible for special needs.

* **Angular version:** 2.0.0-rc.1 
 
* **Browser:** all 
 
* **Language:** TypeScript

**Comment by pkozlowski-opensource** [comment]
Could you elaborate on "special needs" by describing a concrete, real-life use-case?

**Comment by Dinistro** [comment]
@pkozlowski-opensource In my case, I try to implement a `HasErrorDirective`. This directive adds a has-error class on a form-group div. This should make the form creation easier and faster. 

So we could write html like this:

```
<div class="form-group spacer-top-sm control-action" hasError>
    <input [(ngModel)]="search.nachname" ngControl="nachname" class="form-control no-label"
           type="text" [disabled]="isIdCriterionSet()">
</div>
```

And this would add the `has-error` class on the form-group if the input is invalid. Of course this can also be solved with ngClass, but would need more code for every form-group. 

My directive code looks like this:

```
@Directive({
    selector: '[hasError]'
})
export class HasErrorDirective implements AfterContentInit {
    @ContentChild(NgControl) control : NgControlName;

    private wasValidBefor : boolean = true;
    
    constructor(private el: ElementRef) {
        //
    }
    
    public ngAfterContentInit() {
    //It's working, but the compiler does not like this...
        this.control.update.subscribe(() => {
            if(this.control.valid !== this.wasValidBefor) {
                if(this.wasValidBefor = this.control.valid) {
                    this.el.nativeElement.classList.remove('has-error');
                } else {
                    this.el.nativeElement.classList.add('has-error');
                }
            } 
        });
    }
}
```

I know that this could be solved with other approaches, but I find it special, that it's possible to access the update on `NgModel`, but not on `NgControlName`.

**Comment by Dinistro** [comment]
This is fixed in the new @angular/forms.

**Comment by Dinistro** [comment]
This is fixed in the new @angular/forms.
