### ISSUE TITLE
tabIndex attribute cannot be removed with null value

### ISSUE THREAD

**Issue by vladimirivanoviliev** [angular/angular#8960]
**I'm submitting a ...**
- [x] bug report

**Current behavior**
Currently when you set element "tabIndex" attribute to null it renders this attribute with value 0:

Input (inside component template):

    <ul [tabIndex]="root ? 0 : null">

Output (where root is set to false): 

    <ul tabIndex="0">

**Expected/desired behavior**
Expected behavior is when you set the "tabIndex" property to null to not render the attribute (as other attributes behave).

Plunk:

-  [demo](http://plnkr.co/edit/VtDI6kMbcAOadmLJf2oq?p=preview)

* **What is the motivation / use case for changing the behavior?**
The motivation is to nest such components in hierarchical manner and make them focusable only when on root level. Such example could be panel-like component (menu, accordion).

* **Angular version:** 2.0.0-RC1
 
* **Browser:** all
 
* **Language:** TypeScript | ES

**Comment by zoechi** [comment]
Works fine with attribute binding `[attr.tabindex]="tab"`

https://plnkr.co/edit/ossRURXRCyu2srlEoqMP?p=preview

It seems to be a browser feature that the attribute is not removed when the `tabindex` property is set to `null`

**Comment by vladimirivanoviliev** [comment]
Thank you a lot :)
