### ISSUE TITLE
Refactor decorator to metadata mapping

### ISSUE THREAD

**Issue by tbosch** [angular/angular#8962]
Right now, users can create their own decorators that just create our internal `ComponentMetadata`, ... However, this does not work in offline compilation as we don't evaluate the user's code.

Internally, we already have a mapping from decorator to metadata classes at 2 places (StaticReflector and ReflectionCapabilities). We could make this mapping generic and configurable via `CompilerConfig`.

# Proposal

Allow something like this:
```
// Metadata class
class MyComponentMetadata extends ComponentMetadata { ... }
// Decorator
function MyComponent(...args) {
  return (cls) => {
    var decoratorMetadata = {
      type: MyComponent,
      args: args
    };
    Reflect.defineMetadata(...);
    return cls;
  };
}

var decoratorsToMetadata = new Map<any, Type>();
decoratorsToMetadata.set(Component, ComponentMetadata);
decoratorsToMetadata.set(Directive, DirectiveMetadata);
decoratorsToMetadata.set(MyComponent, MyComponentMetadata);
...

var compilerConfig = new CompilerConfig({
  decorators: decoratorsToMetadata
});
```

This relies on the following principles:

- a decorator takes exactly the same arguments as the metadata that it represents
- the decorator only stores its invocation (in the form of decoratorType / args), but does not create the metadata class
- metadata classes are only created in the `CompileMetadataResolver` based on the mapping in the `CompilerConfig` from decorator classes to metadata classes.

With this, we get the following benefits:

- works for offline compile, as we can also capture decorator invocations without running the decorator
- simplification of `StaticReflector` and `ReflectionCapabilities` and all of our decorators, as they don't have to produce metadata instances any more.
- we can unify the way tsickle stores metadata on the type and the metadata created by executing decorators during runtime
- support for user defined decorators

# Implementation details

- Our decorators should not use `Reflect` to store metadata, but just patch properties like `MyComp.decorators` / `MyComp.propDecorators` in the same way as tsickle does it. With that we don't need a special support for tsickle.
- Apply the approach above also for functions used to define animation. I.e. they should not return instances of metadata classed, but rather just return an object literal like `{ fn: trigger, args: [...] }`.
- Change our utility functions to create decorators to take not argument and export them as public API for others to use.
- The mapping in `CompilerConfig` would need to use `CompileIdentifierMetadata` to represent types and functions so that we can use it during runtime and offline compile alike.

**Comment by IgorMinar** [comment]
If we start using CompilerConfig for this and we don't add a way to compose configuration coming from various parties then the end application will need to know about all of the decorators used by anyone in the application and 3rd party components. This means that use of decorators will become part of the public api of a 3rd party component.

The decorators used by 3rd parties are an implementation detail that should not leak outside of the component (as long as the component has the standard metadata attached to it).

Can we avoid this?

**Comment by tbosch** [comment]
Talked to @mhevery, decided that the refactoring is good for cleaning up but not for allowing custom decorators.

**Comment by IgorMinar** [comment]
that sounds good to me.

**Comment by tbosch** [comment]
This has landed in master, although without the support for custom decorators.
