### ISSUE TITLE
Error compiling using Browserify and TSify

### ISSUE THREAD

**Issue by Soviut** [angular/angular#8969]
* **I'm submitting a ...**
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**

I'm trying to build my project using Gulp, Browserify and TSify using the following code.

```javascript
    return browserify({
        basedir: '.',
        debug: true,
        entries: [
            `${src.app}/main.ts`
        ],
        cache: {},
        packageCache: {}
    })
    .plugin(tsify)
    .bundle()
    .pipe(source('bundle.js'))
    .pipe(gulp.dest(dist.scripts))
```
When I run this task, I get the following error.

```
TypeScript error: node_modules/@angular/common/esm/src/directives/ng_for.d.ts(7,14): Error TS1005: '=' expected.
```

**Expected/desired behavior**

* **What is the expected behavior?**

Browserify should be able to build the code with all dependencies.

* **Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.1 
  
* **Language:** TypeScript, tsc 1.8.7

**Comment by pkozlowski-opensource** [comment]
Please direct support questions to an appropriate channel: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by Soviut** [comment]
Ah sorry. I was considering this a legitimate bug report because of the error angular was throwing during TS compilation.
