### ISSUE TITLE
@angular/router documentation

### ISSUE THREAD

**Issue by PivotalAnimal** [angular/angular#8972]
The documentation for @angular/router is broken. e.g. https://angular.io/docs/ts/latest/api/router/index/RouteMetadata

I am a little frustrated trying to switch from the deprecated route engine to the new model when your documentation only references the old and not the new. Please enhance documentation of the new router syntax and use-cases - routerLink, @Routes, etc. Hopefully there is a 1 to 1 correspondence of features?

Thanks!

**Comment by ericmartinezr** [comment]
dup of https://github.com/angular/angular/issues/8756

anyway, if you're already using the deprecated, stay on it. The new router is undocumented and unfinished. We have no much details but it looks like there's going to be a third router that follows ngrx/router concepts (either a full rewrite again, or they will continue the new one to follow those concepts), so you could start using that one that's pretty cool https://github.com/ngrx/router

**Comment by Namek** [comment]
I ported my app to new router and that become a failure. Yes, it seems to be better in architectural way, but still it's not really useful. The greatest error in whole thing is that I sometimes want to manually decide what router does but there's only option to auto-create component on route navigation.

Also note that there are multiple issues reported that relate to the new router.

**Comment by vapits** [comment]
Yeah it's good to stay to deprecated but if you update the CLI for example (and therefore you get the new router) you are doomed...
I did it and now nothing works and no documentation. I understand, really, that you guys make our life easier and better but this think with the deprecations in A2 and the non existence of documentation is kinda frustrating :/

I think this is a high priority issue. dup or not.

**Comment by Namek** [comment]
@vapits if you didn't know then third router is comming: http://angularjs.blogspot.com/2016/06/improvements-coming-for-routing-in.html

**Comment by vapits** [comment]
@Namek I know that thx, angular-cli had a new version disabling the routes generation as a result of this so current projects works only through router-deprecated.

Let's hope it will come soon and with a documentation.

**Comment by zoechi** [comment]
angular/angular.io#1636

**Comment by pkozlowski-opensource** [comment]
New router docs were merged via angular/angular.io#1636 and on-line now at: https://angular.io/docs/ts/latest/guide/router.html
