### ISSUE TITLE
"Expression is too complex to resolve statically" needs more context information.

### ISSUE THREAD

**Issue by chuckjaz** [angular/angular#8978]
* **I'm submitting a ...**
- [x] feature request

When a 'Expression is too complex to resolve statically' is generated by the `StaticReflector` there isn't enough context to figure out where, in the original file, the offending expression is.

**Comment by steida** [comment]
That's because Angular is http://www.joelonsoftware.com/articles/LeakyAbstractions.html

**Comment by vicb** [comment]
When this happen because of an inline function (provider factory) it would be great to tell the dev to use a reference instead.
