### ISSUE TITLE
location.path() of default route in RC router yields empty string

### ISSUE THREAD

**Issue by paynoattn** [angular/angular#8986]
* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**
In an example like the following, ```currentRoute``` would yield an empty string on the home component.
 
```
// ...

export class AppComponent {

 public currentRoute: string;
 
 constructor( private route: Router, private locate: location ) { 
   route.changes.subscribe(() => {
      this.currentRoute = this.locate.path();
      console.log(this.currentRoute);
    });
 }
}
````

**Expected/desired behavior**

* **What is the expected behavior?**
The default route should have a path of '/', a name, or other identifier.

* **What is the motivation / use case for changing the behavior?**
In the case where someone wants to determine if it is the default/home route.

* **Please tell us about your environment:**
Mavericks, Webpack, Typescript

* **Angular version:** 2.0.0-rc.1
 
* **Browser:** [ all ] 
 
* **Language:** [ all ]

**Comment by zoechi** [comment]
How do the routes look like. Please provide a plunker that allows to reproduce.

**Comment by brandonroberts** [comment]
@paynoattn the RC router isn't ready so you will run into lots of issues. If you were previously on the deprecated router, stay on that.

**Comment by bastienJS** [comment]
@brandonroberts Will the successor of the RC1 router preserve the structure of a beta router app? When I migrate NOW from beta to RC1 there are lots of changes and nothing works as before.  Thus I plan to revert to the old beta router (deprecated router)

**Comment by paynoattn** [comment]
@bastienJS you have it backwards. The succesor of the beta router (@angular/router-deprecated) is the RC router. It does not have the same structure of the beta router. I'm writing up a piece on the RC router here: https://medium.com/@paynoattn/routing-in-with-angular2s-new-rc-x-router-6321c4a3d835#.p3u8mx5pl

@brandonroberts I don't mind bugs I'm building a project and I wanted to try it out. I'm just creating the bug.

@zoechi I'm working on the plunker, I'll post a link shortly.

**Comment by brandonroberts** [comment]
@bastienJS @paynoattn the RC router as it is today is not what it will be once finished and that version of the RC router will receive no further updates.

**Comment by paynoattn** [comment]
@brandonroberts so should I just close this bug report?

**Comment by brandonroberts** [comment]
@paynoattn yes. The issue itself of location.path() returning `''` for the path of `/` is expected behavior
