### ISSUE TITLE
<svg> elements don't scale properly inside angular templates

### ISSUE THREAD

**Issue by capnfabs** [angular/angular#8987]
* **I'm submitting a ...**
- [x] bug report

* **Current behavior**

When an `<svg>` element is rendered as part of an angular template, the actual element scales to the width and height set via css, but the contents of the `<svg>` don't scale accordingly.

**Minimal repro**: http://plnkr.co/edit/zWqmpJ1NG2NZe7u8TSOz?p=preview

When the same SVG is specified inside a template and outside:

```svg
<svg style="width: 200px; height: 200px" viewbox="0 0 100 100">
  <circle cx="50" cy="50" r="50"/>
</svg>
```

We get:

<img width="422" alt="screen shot 2016-06-03 at 2 23 23 pm" src="https://cloud.githubusercontent.com/assets/1336508/15768727/ea460c7a-2996-11e6-9308-97092e11ef7b.png">

Expected:

<img width="431" alt="screen shot 2016-06-03 at 2 27 29 pm" src="https://cloud.githubusercontent.com/assets/1336508/15768771/5a3dd170-2997-11e6-96ba-774b5557a247.png">

* **Please tell us about your environment:**

* **Angular version:** 2.0.0-beta.17
 
* **Browser:** Confirmed in (on OSX 10.11.5):
  - Chrome 51.0.2704.79
  - Safari 9.1.1 (11601.6.17)
  - Firefox 46.0.1
 
* **Language:** Reproduced in TypeScript and Dart

**Comment by capnfabs** [comment]
The problem seems to be that `viewBox` is supposed to be camelCased, and I haven't done that. It's strange that this only affects templates, though, and not HTML directly rendered by the browser.

From the JS console:
```
> document.getElementsByTagName('svg')[0]
<svg style=​"width:​ 200px;​ height:​ 200px" viewbox=​"0 0 100 100">​…​</svg>​

> document.getElementsByTagName('svg')[1]
<svg style=​"width:​ 200px;​ height:​ 200px" viewBox=​"0 0 100 100">​…​</svg>​

> document.getElementsByTagName('svg')[0].viewBox
SVGAnimatedRect {baseVal: SVGRect, animVal: SVGRect}

> document.getElementsByTagName('svg')[0].viewBox.baseVal
SVGRect {x: 0, y: 0, width: 0, height: 0}

> document.getElementsByTagName('svg')[1].viewBox.baseVal
SVGRect {x: 0, y: 0, width: 100, height: 100}
```

**Comment by palmanis** [comment]
most likely because angular has it's own custom parser, which is case sensitive, but browser isn't.

**Comment by zoechi** [comment]
Outside Angular the browser somehow makes it camelcase automatically. Even though in the Plunker it is lowercase, the devtools show it camelcase.   
If you change it to lowercase in the devtools then it doesn't scale outside Angular as well anymore. If you change it to camelcase inside the Angular component using devtools it scales there as well. 

For dynamically added HTML the browser doesn't seem to do the rewrite from lowercase to camelcase.

**Comment by capnfabs** [comment]
@zoechi Good point. What do you think the right behaviour should be in this situation? It's bad that there's a discrepancy, but the discrepancy is probably on the browser side more than the Angular side.

**Comment by zoechi** [comment]
It would be interesting how other browser behave and what the standard has to tell about it.
A nice solution would be if Angular would adjust the casing but what if you actually want a lowercase `viewbox` attribute anywhere...

**Comment by pkozlowski-opensource** [comment]
I don't think we want to do any case adjusting right now in the Angular. I'm surprised that browsers (or at least one tested here) will auto-correct casing for HTML in the main document but won't do this in dynamically inserted HTML :-/ 

I'm going to close this one for now but if anyone could dig into specs / other browsers behavior and report back here we could see if / how to act.
