### ISSUE TITLE
how to send custom EventEmitter to parentComponent when the childComponent load by router?

### ISSUE THREAD

**Issue by cjd6568358** [angular/angular#8990]
how to send custom EventEmitter to parentComponent when the childComponent load by router?
* **Angular version:** 2.0.0-rc1

thanks a lot

**Comment by Namek** [comment]
in previous versions `ViewChildren`/`ViewChild` annotations worked for me. I'm not sure about it's current state. http://plnkr.co/edit/QaKJHF

**Comment by cjd6568358** [comment]
@Namek thank you for your demo.but i solve this problem with a EventEmitter service.like it:

`import {Injectable,EventEmitter} from '@angular/core';
@Injectable()
export class eventService {
  _emitter: EventEmitter<any> = new EventEmitter();
  get emitter() {
    return this._emitter;
  }
}`

and send message with 
`this.eventService.emitter.emit({type:"shoppingCartChange"});`

receive it with
`constructor(private eventService:eventService) {
  this.eventService._emitter.subscribe(data => this.onShoppingCartChange(data))
}

onShoppingCartChange(data){
    if(data.type == "shoppingCartChange"){
    }
  }`

**Comment by pkozlowski-opensource** [comment]
Sounds like a support question that got solved. Closing. In the future please use dedicated support forums for this type of questions: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
