### ISSUE TITLE
Having a + in the URL for lazy loaded components

### ISSUE THREAD

**Issue by cmiagssh** [angular/angular#8992]
* **I'm submitting a ...**
- [ x ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**
In his ng-conf talk (https://www.youtube.com/watch?v=d8yAdeshpcw&index=9&list=PLOETEcp3DkCq788xapkP_OU-78jhTf68j at around minute 15) Misko Hevery introduces a special code structure that allows the lazy loading of components. Components are plazed in a separate folder and the folder name has to start with a + (like +login/ for the LoginComponent). When running on an IIS Webserver the Server throws an error:

    HTTP Error 404.11 - Not Found
    The request filtering module is configured to deny a request that contains a double escape sequence.
    Most likely causes:
    
    The request contained a double escape sequence and request filtering is configured on the Web server to deny double escape sequences.
    
    Things you can try:
    
    Verify the configuration/system.webServer/security/requestFiltering@allowDoubleEscaping setting in the applicationhost.config or web.confg file.

The error is described in the Post http://stackoverflow.com/questions/7739233/double-escape-sequence-inside-a-url-the-request-filtering-module-is-configured

**Expected/desired behavior**
Now obviously the Server can be configured to not show this error. But then you have to take action on each server you deploy. Is there a better way to implement this feature or can the behaviour be reconfigured?

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

Run it on an IIS Webserver

* **What is the expected behavior?**
Does not generate errors on a default installation of a webserver

* **What is the motivation / use case for changing the behavior?**
Does not generate errors on a default installation of a webserver

* **Please tell us about your environment:**
"dependencies": {
    "@angular/common": "2.0.0-rc.1",
    "@angular/compiler": "2.0.0-rc.1",
    "@angular/core": "2.0.0-rc.1",
    "@angular/platform-browser": "2.0.0-rc.1",
    "@angular/platform-browser-dynamic": "2.0.0-rc.1",
    "@angular/router": "2.0.0-rc.1",
    "es6-shim": "^0.35.0",
    "reflect-metadata": "0.1.3",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "0.19.26",
    "zone.js": "^0.6.12"
  },
  "devDependencies": {
    "angular-cli": "0.0.*",
    "clang-format": "^1.0.35",
    "codelyzer": "0.0.14",
    "ember-cli-inject-live-reload": "^1.4.0",
    "jasmine-core": "^2.4.1",
    "jasmine-spec-reporter": "^2.4.0",
    "karma": "^0.13.15",
    "karma-chrome-launcher": "^0.2.3",
    "karma-jasmine": "^0.3.8",
    "protractor": "^3.3.0",
    "ts-node": "^0.5.5",
    "tslint": "^3.6.0",
    "typescript": "^1.8.10",
    "typings": "^0.8.1"
  }

* **Angular version:** 2.0.0-rc.1
 
* **Browser:** [all] 
 
* **Language:** [TypeScript 1.8.10 | ES5]

**Comment by CaptainCodeman** [comment]
I haven't seen any evidence that the + actually changes behavior at all - last time I checked there was no lazy loading completed for the new router and even if it did, having it set by naming the folder is unworkable IMO - what if you wanted the same component to be shared and lazy loaded for some apps/routes and not for others? Having it as a prefix doesn't help when finding components (a suffix would be better) and of course it should be a character that doesn't cause hosting issues.

If feels like it was something just thrown together for ng-conf rather than properly thought through so I expect it may disappear.

**Comment by kylecordes** [comment]
Regardless of the behavior, the new-new-new router, etc. I would like to request that this lazy load feature be invisible in the URLs. URLs are part of the public face of software...  In spite of certain browser makers who had been conspiring to hide them from the UI :-)   Whether a project developer uses lazy loading, a decision that can change over time, should not be radiated to every user in the form of an unusual character in the middle of the URL.

**Comment by cmiagssh** [comment]
I guess this ticket is not relavant any more
