### ISSUE TITLE
Only first uncaught exception is handed to ExceptionHandler

### ISSUE THREAD

**Issue by PhilippSoehnlein** [angular/angular#8993]
- **I'm submitting a ...**
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**
An exception is thrown and gets printed in the browser's console. If there are other exceptions thrown afterwards, they don't come up in the browser's console and never reach `ExceptionHandler`.

**Expected/desired behavior**
Every exception thrown should reach `ExceptionHandler` (and therefore a maybe existing custom exception handler can kick in).
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 
  http://plnkr.co/edit/4pA92Dbkg5YXLbJ7dmhl?p=preview
  Click on any of the two buttons and you will see an exception in the browser's console. Do another button click and you will see that the click handler is called, but the exception isn't printed in the console.
  It doesn't matter if the consecutive exceptions are thrown from the same component, a child component or an asynchronous thing (like `window.setTimeout`).
- **What is the expected behavior?**
  Every button click should trigger an exception which comes up in the browser's console.
- **What is the motivation / use case for changing the behavior?**
  I found this bug while digging into implementing my own exception handler and reporting exceptions to a service like [https://exceptionless.com/](Exceptionless).
- **Please tell us about your environment:**
  My app was created with angular-cli beta 5.
- **Angular version:** 2.0.0-rc1
- **Browser:** all
- **Language:** TypeScript 1.8

**Comment by zoechi** [comment]
The Plunker doesn't contain a custom exception handler. Is that intentional?

I guess this is what you want http://plnkr.co/edit/zbzllPKzAd7T0AQp22Id?p=preview

**Comment by PhilippSoehnlein** [comment]
> The Plunker doesn't contain a custom exception handler. Is that intentional?

Yes. Though implementing a custom exception handler is my final goal, I just wondered why only the first exception is logged by the default exception handler?

> I guess this is what you want http://plnkr.co/edit/zbzllPKzAd7T0AQp22Id?p=preview

In the end it is, but I wasn't able to do so yet, because I'm getting a TypeScript transpile error:
> Class 'MyExceptionHandler' incorrectly implements interface 'ExceptionHandler'. 
> Property '_logger' is missing in type 'MyExceptionHandler'.

Thanks to your example I found out that my tries of implementing a custom handler would have worked with TypeScript 1.7, but not with TypeScript 1.8 (which is used by angular-cli), which leaves me in the weird situation in which I can't use angular-cli when I want to make something which uses a custom exception handler. At least I currently can't see a way…

**Comment by pkozlowski-opensource** [comment]
So, if I understand correctly we've got 2 separate issues here:
* why `_logger` is part of the `ExceptionHandler` interface
* why the default exception handler behaves in a strange way "logging only first exception"

Is my understanding correct?

**Comment by henritoivar** [comment]
+1 
I use a custom ExceptionHandler to show a login screen when a 401 response is returned and an error toast message. Currently the app breaks because of this issue.

Could _logger be an optional parameter in the constructor perhaps?

**Comment by marpstar** [comment]
FWIW, I'm also having this issue. For the moment I'm working around it by declaring a custom Exception Handler that does NOT `extends ExceptionHandler`, in order for me to work around the issue with the type definitions. I've spent a few hours trying to figure out why I can't ever get more than one uncaught exception to appear... is this documented anywhere?

```typescript
@Injectable()
class MyExceptionHandler {  //note, I don't extend ExceptionHandler because of the issue with the typings file. 
  
  call(error: any, stackTrace: any = null, reason: any = null) {
    // do something with the exception
    console.log(error);   // console.error() didn't seem to work for me. 
    debugger;
  }
}
```

**Comment by sqlsolver** [comment]
Same error, used @marpstar workaround.

**Comment by awerlang** [comment]
The default error handler always rethrows:

```ts
// We rethrow exceptions, so operations like 'bootstrap' will result in an error
// when an error happens. If we do not rethrow, bootstrap will always succeed.
if (this.rethrowError) throw error;
```
ref: https://github.com/angular/angular/blob/745e10e6d2ea9097b7ec650ae54cea91e3d193f2/modules/%40angular/core/src/error_handler.ts#L73

IMO, it isn't the task of the error handler to rethrow, because a custom exception handler would also have to carry this burden, only in some situations as stated for `bootstrap`.
