### ISSUE TITLE
UNMET PEER DEPENDENCY angular2-universal@^0.101.4

### ISSUE THREAD

**Issue by dehian** [angular/angular#8995]
* **I'm submitting a ...**
- [x ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**
I'm using angular2 with the universal component, i had my project working few weeks ago but now i wanted to install the app on another machine and i have a dependency issue
my package.json refers to 
    "angular2": "2.0.0-beta.15",
    "angular2-universal": "0.98.3"
    ...
on my local machine, the initial install made few weeks ago succesfully installed the following
+-- angular2@2.0.0-beta.15
+-- angular2-universal@0.98.3
| +-- angular2-express-engine@0.11.1
| +-- angular2-hapi-engine@0.11.1
| +-- angular2-universal-polyfills@0.4.1
| | +-- es6-promise@3.0.2
| | `-- ie-shim@0.1.0
...

same thing today on another machine gives 
+-- angular2@2.0.0-beta.15
+-- angular2-universal@0.98.3
| +-- angular2-express-engine@0.13.1
| +-- angular2-hapi-engine@0.13.1
| +-- UNMET PEER DEPENDENCY angular2-universal@^0.101.4
| +-- angular2-universal-polyfills@0.4.1
| | +-- es6-promise@3.0.2
| | `-- ie-shim@0.1.0
...
and i assume that this is why my project aint working there

**Expected/desired behavior**
have a package that works with those dependencies

* **What is the motivation / use case for changing the behavior?**
it just fails

* **Please tell us about your environment:**
node 5.11.1
windows 7

* **Angular version:** 2.0.0-beta.15 
 
* **Browser:** [all ] 
 
* **Language:** [ TypeScript]

**Comment by pkozlowski-opensource** [comment]
This is a difference in npm versions on 2 machines. Check npm's changelog for peerDependencies handling. Closing as it has nothing to do with Angular itself.

**Comment by dehian** [comment]
no it's not a difference in npm version on different machines, same version on both machines (3.8.6)
i could even reproduce it on my local env by duplicating the project
one works, the other fails

**Comment by pkozlowski-opensource** [comment]
Try asking in https://github.com/angular/universal/issues then

**Comment by dehian** [comment]
thx
