### ISSUE TITLE
@ViewChild by selector not working

### ISSUE THREAD

**Issue by keathmilligan** [angular/angular#8998]
Prior to upgrading to RC.1, my app used the method suggested on the Angular blog here: http://angularjs.blogspot.com/2016/04/5-rookie-mistakes-to-avoid-with-angular.html for setting focus on an element. Specifically, using @ViewChild with a selector to get an ElementRef to an input field:

```typescript
@ViewChild('myInput') input: ElementRef;
```

After updating to RC.1 however, the reference is undefined when trying to use it in the ngAfterViewInit handler.

**Comment by pkozlowski-opensource** [comment]
Could you please provide a plunker reproducing this issue? The query should still work.

**Comment by pkozlowski-opensource** [comment]
Seems like the example from the Kara's article works perfectly fine with rc.1: http://plnkr.co/edit/Qg6TX9G6q7k71x4dblXE?p=preview so going to close this one for now. Please re-open if you've got live reproduce scenario.
