### ISSUE TITLE
Angular should auto-prefix css 

### ISSUE THREAD

**Issue by judygogo** [angular/angular#9002]
* **I'm submitting a ...**
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**
Angular does everything else for us, like CSS encapsulation, but some of our orgs can't ditch SASS because there are so many modules that we find useful. One of these is browser prefixing.

**Expected/desired behavior**
We'd like Angular to add browser prefixes automatically =) 

@ajoslin just said "I'll write a library that autoprefixes styles"
Thanks, @ajoslin! 

* **What is the motivation / use case for changing the behavior?**
So we can all use javascript for our styles and ditch css compilers!

* **Please tell us about your environment:**

* **Angular version:** 2.0.0-beta.X 
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart]

**Comment by aciccarello** [comment]
I think the angular-cli project has support for SASS

**Comment by laco0416** [comment]
I think that feature probably shouldn't be supported by Angular because _browser prefixing_ depends on browsers and its update. That is a job of a CSS preprocessor.

**Comment by laco0416** [comment]
But if it is provided as a library, it's very cool.

**Comment by ajoslin** [comment]
Check out npm.im/ng-style for an extremely opinionated approach to styling your Angular components.

**Comment by vicb** [comment]
Such feature will probably not come to Angular. That's the job of CSS preprocessors.

_(That being said we are investigating using PostCSS as a CSS parser in Angular, it could help making this simpler)_
