### ISSUE TITLE
[Dart transformers]: generate a setter for `@PropertySetter`

### ISSUE THREAD

**Issue by vicb** [angular/angular#901]
PR #883 add a new `@PropertySetter` annotation that is used this way:

```js
class NeedsPropertySetter {
  propSetter;
  constructor(@PropertySetter('title') propSetter: Function) {
    this.propSetter = propSetter;
  }

  setProp(value) {
    // Set the value of the current Element
    this.propSetter(value);
  }
}
```

Internally we we need to have a setter to set the property on the `Element`.

@kegluneq Could you please update the Dart transformers to generate those setters ? Thanks.

**Comment by kegluneq** [comment]
Just to make sure I understand:

I want to set `title` on my DOM element from within my Component. I *could* do this:
```
constructor(@Inject(NgElement) ngEl) {
  this.propSetter = (String value) {
    new JsObject.fromBrowserObject(ngEl.domElement)['title'] = value;
  };
}
```

But instead we want the syntactic sugar above and to have the transform create that code.

Additional consideration: if the property is one that is known by dart:html, we do not have to go through the `JsObject.fromBrowserObject` pain and can (should, they're faster) use the available convenience methods.

Is that correct?

**Comment by vicb** [comment]
@kegluneq that is correct.

The goal is that the could be executed on an element proxy (when we do not run in the UI thread).

@mhevery considering this, what should the setter look like in Dart ?

**Comment by mhevery** [comment]
I think it is just:

```
(element, value) =>  element.title = value;
```

I don't think we need to do property name matching.

**Comment by kegluneq** [comment]
@mhevery , am I correct that your code is what should be generated instead of what I wrote above and the framework will auto-magically transform the `element` passed in from Dart to Js?

**Comment by jelbourn** [comment]
I think this issue is obsolete now. Properties on the host element are set via `hostProperties` and data binding. Closing now, can re-open if something still needs to be done.
