### ISSUE TITLE
*ngFor + ngControl + fast typing = Uncaught (in promise) exception

### ISSUE THREAD

**Issue by digdugpooka** [angular/angular#9016]
* **I'm submitting a ...**
- [x] bug report

**Current behavior**
- Create a component whose model contains an array of a simple object, e.g. { Id: "foo" }
- In the template, add a `<div *ngFor="let obj of myObjects">...` 
- Within the div, add: `<input [(ngModel)]="obj.Id" NgControl={{obj.Id}}" />`
- Hydrate the model w/ fake data, then run the site. Rapidly type/switch between the rendered <input> fields...
- If you type too quickly you'll eventually see:
Error: Uncaught (in promise): TypeError: Cannot read property 'updateValue' of null
    at resolvePromise (zone.js:538)
    at zone.js:574
    at ZoneDelegate.invokeTask (zone.js:356)
    at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (ng_zone_impl.ts:56)
    at ZoneDelegate.invokeTask (zone.js:355)
    at Zone.runTask (zone.js:256)
    at drainMicroTaskQueue (zone.js:474)
    at ZoneTask.invoke (zone.js:426)BrowserDomAdapter.logError @ browser_adapter.ts:78
zone.js:461 Unhandled Promise rejection: Cannot read property 'updateValue' of null ; Zone: angular ; Task: Promise.then ; Value: TypeError: Cannot read property 'updateValue' of null(…)consoleError @ zone.js:461

**Expected/desired behavior**
An exception should not be thrown based on how fast one types; there should be a straightforward way to handle this exception.

* **Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.1
 
* **Browser:**  
Chrome 50.0.2661
 
* **Language:** [all | TypeScript 1.8.30 | ES5

**Comment by zoechi** [comment]
Probably a dup of #7822 and AFAIK caused by #6311 which got fixed recently (not yet shipped in RC.1)

**Comment by zoechi** [comment]
I think this can be closed. I can't reproduce #7822
