### ISSUE TITLE
Testing: typings for `expect` should express Jasmine matchers (extended for Ng)

### ISSUE THREAD

**Issue by wardbell** [angular/angular#9017]
* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**

`expect` is typed as follows in `angular/core/testing/testing.ts`
```
export var expect: Function = _global.expect;
```
This means that we get no intellisense for `expect`

**Expected/desired behavior**
The type definition should be this (which works)
```
export declare function expect(spy: Function): NgMatchers;
export declare function expect(actual: any): NgMatchers;
```
### Discussion

`expect` is the one item in the Jasmine test framework that has a rich API and should offer the developer type support. The others - `it`, `beforeEach`, etc - aren't chained and are too simple to require typing. We can live without typing support for them. But `expect` has a big API that's hard to remember.

I suspect the source of the problem is that `expect` is exported from `@angular/core/testing` which defines a Jasmine-like api but has no Jasmine dependency.  I get that although, tbh, `expect`, `beforeEach`, etc are the Jasmine API, not anyone else's; other expectation libraries have a different API.

We have to go to `@angular/platform-browser/testing` to find the dependency on Jasmine. Not sure why it's OK here and not OK in `@angular/core`. Be that as it may, we should give the developer a version of `expect` with the full (extended) Jasmine API.

If the separation is still desired, then maybe we should invite the developer to get _all of the Angular/Jasmine members from `@angular/platform-browser/testing`_ rather than from `@angular/core/testing`.

```
import {
  beforeEach, beforeEachProviders,
  describe, ddescribe, xdescribe,
  expect,
  it, iit, xit,
} from '@angular/platform-browser/testing';
```

### Workaround

My ugly work around involves creating a file, `expect-proper.ts`, that produces an `expect` with typings and then importing `expect` from that module.

```
// expect-proper.ts
import { expect as expectCore} from '@angular/core/testing';
import { NgMatchers } from '@angular/platform-browser/testing';

export function expect(spy: Function): NgMatchers;
export function expect(actual: any): NgMatchers;
export function expect(actual: any): NgMatchers {
  return expectCore(actual) as NgMatchers;
}

/*** usage ***/

// Boilerplate
import {
  beforeEach, beforeEachProviders,
  describe, ddescribe, xdescribe,
  it, iit, xit,
  async, inject,
  fakeAsync, tick, withProviders
} from '@angular/core/testing';

import {expect} from './expect-proper';

// Specs
...
    it('should use FancyService',
      inject([FancyService], (service: FancyService) => {
        expect(service.value).toEqual('real value');  // we now get intellisense for expect.
    }));
...
```

**Comment by ovrmrw** [comment]
+1

**Comment by senseiweb** [comment]
+1

**Comment by Foxandxss** [comment]
Is this issue relevant anymore? We don't have wrappers anymore

/cc @juliemr

**Comment by juliemr** [comment]
Yup, let's close this one.
