### ISSUE TITLE
Declarative property initialization

### ISSUE THREAD

**Issue by ruslanulyanets** [angular/angular#902]
<p>Angular had a paradigm shift and became component-oriented. Having taken a fresh look it would be natural to treat html markup as serialized hierarchy of objects of any type(components are just particular case of the objects). The objects then could have properties of other complex types.</p> 
<p>Right now setting component properties is limited and can be done using JSON inserts only in html attributes. But sometimes it's difficult especially when you have to type a lot of JSON code. Consider adding a declarative way for property initialization so that instead of this markup:</p>
<pre>
&lt;panel [layout]=&quot;{type:&quot;table&quot;, cells:4, rows:4}&quot;&gt;
  &lt;childElement/&gt;
  &lt;childElement2/&gt;  
&lt;/panel&gt;
</pre>

<p>I could write its declarative counterpart like this:</p>
<pre>
&lt;panel&gt;
  [layout]
    &lt;tableLayout cells=&quot;4&quot; rows=&quot;4&quot;&gt;
  [/layout]
  &lt;childElement/&gt;
  &lt;childElement2/&gt;  
&lt;/panel&gt;
</pre>
<p>Where [layout] is a complex property of the panel component, &lt;tableLayout&gt; is an instance of the tableLayout class which is set to the property.</p>

<p>By doing this I can: </p>
<ol>
<li>Describe in markup instance of which class I want to instantiate(it's not possible in JSON unless I do the trick like in the first example).</li>
<li>Easily set complex properties/array properties(like defining columns for the Grid component).For example:
<pre>
&lt;grid&gt;
  [columns]
    &lt;textColumn width=&quot;100&quot; title=&quot;test1&quot;/&gt;
    &lt;dateColumn width=&quot;200&quot; title=&quot;test2&quot;/&gt;
    &lt;numberColumn width=&quot;200&quot; title=&quot;test2&quot;/&gt;
    ... (+ 50 more column definitions which would be hard to describe in JSON)
  [/columns]
&lt;/grid&gt;
</pre>
Here each column element is an instance of the appropriate class. And the Grid component has an array property which stores the columns.
</li>
<li><b>What is most important: Angular will act like a serialization format(take a look at XAML specification for example).</b></li>
</ol>

To decide where property value should go(property value itself or added to the array) user could specify array property in the constructor method:
<pre>
<code>
class Grid {
  constructor() {
    this.columns = [];//elements inside "columns" tag will be added to the array    
  }  
}
</code>
</pre>

<p>
<b>I understand that this is an epic story. Do you think this enhancement fits the architecture and could be implemented at least in next version of the framework?</b>
</p>

**Comment by mhevery** [comment]
Your syntax is not valid HTML, so that is a blocker.
While a valid point of view, I don't think that is the directions we would like to take the framework. 

Closing as it will not be implemented.
