### ISSUE TITLE
RouterOutlet stops working without routerLink

### ISSUE THREAD

**Issue by blacksonic** [angular/angular#9020]
* **I'm submitting a bug report**

* **Current behavior**
When i place a RouterOutlet into my application, configure the Routes, the outlet only activates when a link is provided next to. Strangely when i remove that router link it stops working.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Here is my application: https://github.com/blacksonic/angular2-esnext-todomvc
When i remove the hidden router link from here: https://github.com/blacksonic/angular2-esnext-todomvc/blob/master/app/components/app/app.template.html#L1
the outlet stops working.
No error is displayed on the console though.

* **What is the expected behavior?**
The RouterOutlet shouldnt depend on routerlinks weather rendered or not.

* **Please tell us about your environment:**

* **Angular version:** 2.0.0-RC.1 
 
* **Language:** [ES6/7]

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/issues/8409

**Comment by blacksonic** [comment]
it works now with the new router
