### ISSUE TITLE
Using angular2 direct file upload to Firebase (without Express Multer middleware)

### ISSUE THREAD

**Issue by andlcool** [angular/angular#9024]
* **I'm submitting a ...**
- [x] feature request

**Current behavior**
Hi, I am exploring ways to handle file upload (images in particular) using ng2. I was searching around the web and all the solutions points to using the multer middleware which is an express app for file upload. 

**Expected/desired behavior**
The outcome I would like to achieve is to us ng2 front end to allow user to upload the file and ng2 to write the file to a Firebase3 storage as per Firebase SDK3.

Will ng2 be able to provide this feature to handle file upload and calling a http api to save the file to. Thanks.

**Comment by robwormald** [comment]
angular/http will (eventually) handle file uploads, though its something you can do with fetch or XHR today. for firebase specifically, this will be provided through [angularfire2](https://github.com/angular/angularfire2) - FirebaseSDK3 support is forthcoming.

**Comment by daslicht** [comment]
robwormald:
does angularfire2 support the storage api now?
