### ISSUE TITLE
if *ngIf is working the same element with *ngFor ,it desn't work?

### ISSUE THREAD

**Issue by cjd6568358** [angular/angular#9025]
my demo is like it:
`<div class="cart" *ngFor="let mealInfo of mealInfoList;let mealInfoIndex = index" *ngIf="mealInfo?.selectedCount > 0">`
the *ngIf desn't work.

`<div *ngFor="let a of [11,12,13]" *ngIf="a == 11"></div>`
the *ngFor desn't work.

* **Angular version:** 2.0.0-rc1

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/issues/4792, actually this should throw https://github.com/angular/angular/issues/7315

**Comment by cjd6568358** [comment]
@ericmartinezr thanks. it's usefully for me

**Comment by pkozlowski-opensource** [comment]
Yeh, we should throw so going to close this one as a duplicate of #7315

**Comment by pkozlowski-opensource** [comment]
Oh, @robwormald was 10s faster :-)

**Comment by calidion** [comment]
should be working regardless of how many directives are used.
