### ISSUE TITLE
SVG Path Rendering Incorrect

### ISSUE THREAD

**Issue by gonzofish** [angular/angular#9026]
* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**
Example plnkr: http://embed.plnkr.co/eIEm9Soh2kgCRgQgUg1K/

The first arrow is rendered outside Angular 2. The second arrow is rendered within an Angular 2 component.

I am trying to render an arrowhead for a line in SVG within Angular 2. I'm using all `svg:` prefix where I should (as far as I know) but rendering the same SVG within an Angular 2 component & outside the component are yielding different results.

**Expected/desired behavior**

The arrow inside the Angular 2 component would render identical to one rendered outside Angular 2.

* **Angular version:** 2.0.0-rc.1
 
* **Environment:** Mac OS X 10.11.5

* **Browser:** Chrome 50.0.2661.102, Opera 37.0
This could potentially be a Blink issue, as it works as expected in Firefox 
 
* **Language:** TypeScript 1.8

**Comment by pkozlowski-opensource** [comment]
SVG attributes are case-sensitive (one messed up where refX, refY), see it working in practice: https://plnkr.co/edit/b04nvLTD9XqvjpHdi6dx?p=preview

So why it works outside Angular 2 with incorrect casing? It looks like browsers will auto-correct casing where parsing HTML but will not do the same auto-correction when creating SVG elements dynamically (this is what ng2 does). Browser impls are full of wired, wired cases...

Oh, BTW, you don't need to use `svg:` prefix when your elements are inside the `<svg>` element (corrected plunker for this as well).

**Comment by gonzofish** [comment]
Ah, thanks! I appreciate the quick turnaround & I'll give that all a go.

**Comment by gonzofish** [comment]
The `refX` & `refY` solved it! You're a genius!
