### ISSUE TITLE
Class binding doesn't work with ng-content feature

### ISSUE THREAD

**Issue by michel-p** [angular/angular#9027]
**I'm submitting a bug report**

**Current behavior**
I have a component which uses multiples <ng-content> : 

`<section id="tp-all-notes-panel" class="row">
            <div class="col s12 m6 l4">
                <ng-content select="[note.firstCol]"></ng-content>
            </div>
            <div class="col s12 m6 l4">
                <ng-content select=".secondCol"></ng-content>
            </div>
            <div class="col s12 m6 l4">
                <ng-content select=".thirdCol"></ng-content>
            </div>
        </section>`

Everything is fine when I use this component like this : 
`<note-panel>
            <note *ngFor="#note of allNotes, #index = index" [note]="note" class="firstCol"></note>
       </note-panel>`

But, the thing is, the class attribute must be dynamic, and, not working when defined like this : 
`<note-panel>
            <note *ngFor="#note of allNotes, #index = index" [note]="note"
                  [class.firstCol]="index == 0 || index % 3 == 0"
                  [class.secondCol]="index % 3 == 1"
                  [class.thirdCol]="index % 3 == 2"></note>
        </note-panel>`

**Expected/desired behavior**
Normal behavior would be that the <ng-content select="firstCol"> detects the dynamiccal added class, and not just static declared classes.  

**Plunker**
https://plnkr.co/edit/pdvNSqBTnMg7XxaiF5iz?p=preview

* **Please tell us about your environment:**

* **Angular version:** 2.0.0-beta.15 
 
* **Browser:** [ Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX  ] 
 
* **Language:** [TypeScript 1.8.10] 

Tell me if i'm missing something.

Thank you

**Comment by pkozlowski-opensource** [comment]
I suspect that what is going on here is that class bindings end up on a `<template>` element when you are using `*ngFor` sugar syntax. Try using de-sugared syntax (with a template element) as described in https://angular.io/docs/ts/latest/api/common/index/NgFor-directive.html

If it doesn't help please provide a minimal plunker with a reproduce scenario. Without a plunker we can't help more and a plunker is a mandatory requirement for bug reports anyway:  https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue

**Comment by michel-p** [comment]
Hi and thank you for your quick response. When I De-sugar the syntax, I get a "Property binding firstCol not used by any directive on an embedded template".

Here's my code : 
` <template ngFor let-note [ngForOf]="allNotes" let-i=index
                      [class.firstCol]="i == 0 || i % 3 == 0"
                      [class.secondCol]="i % 3 == 1"
                      [class.thirdCol]="i % 3 == 2">
                <note [note]="note"> </note>
            </template>`

Am I missing something ? 

If not, I'll provide a Plunker asap.

Thanks !

**Comment by pkozlowski-opensource** [comment]
> Am I missing something ?

Yes, I think that you want to add class to the `<note>` element, not the `<template>` one, right? Once again, lack of plunker makes us both loosing time, so....

**Comment by michel-p** [comment]
Okay, here is the plunk : https://plnkr.co/edit/pdvNSqBTnMg7XxaiF5iz?p=preview

**Comment by pkozlowski-opensource** [comment]
Oh, I see. It has nothing to do with `[class.foo]` binding but rather with the static nature of `<ng-content>` projection. AFAIK `<ng-content>` selectors are resolved at compile time so you can't use runtime-mutated CSS classes as selector targets. 

I'm not 100% sure that I'm right here, @tbosch would be able to confirm

**Comment by michel-p** [comment]
Thanks, do you think there is a workaround for my issue then ? :(

**Comment by vicb** [comment]
`<ng-content>` is indeed static (compile time) content projection. The selector has to be known at compile time.
