### ISSUE TITLE
When using hot-reload with ng2 and jspm, removing a debugger point does not work until webstorm is restarted

### ISSUE THREAD

**Issue by born2net** [angular/angular#9028]
When using hot-reload with ng2 and jspm, removing a debugger point does not work until browser / chrome is restarted.

for reference: https://github.com/capaj/systemjs-hot-reloader/issues/90#issuecomment-221508478
I am aware that this is potentially a chrome bug, not ng2, but this is just a huge and important feature, hot-reload for systemjs which works GREAT for all ng2 developers, so I am hoping the ng2 team can expose this issue to the Chrome team, as they do all work for Google :)

tx

Sean.

**Comment by robwormald** [comment]
You've already filed a chromium bug about this, and it's not actionable by the angular team.
