### ISSUE TITLE
Selectors on Decorators and Shadow DOM

### ISSUE THREAD

**Issue by dylanb** [angular/angular#903]
Here is some code that does not work the way I would expect it to work.

Specifically, I want to write a component that uses a decorator that should be applied to content that is included into the template from the instantiating document through the use of a `<content>` element.

To illustrate this, I have one decorator and two components in this code, one of which works as expected and one which does not.

```
import {Component, Template, Decorator, NgElement, bootstrap} from 'angular2/angular2';

// Annotation section
@Component({
  selector: 'my-shadow-app'
})
@Template({
  inline: '<content></content>',
  directives: [ShadowSelector]
})
// Component controller
class MyShadowAppComponent {
  constructor() {
  }
}

@Component({
  selector: 'my-light-app'
})
@Template({
  inline: '<div class="target"></div>',
  directives: [ShadowSelector]
})
// Component controller
class MyLightAppComponent {
  constructor() {
  }
}

@Decorator({
    selector: '.target'
})
class ShadowSelector {
    // NgElement is always injectable and it wraps the element on which the
    // directive was found by the compiler.
    constructor(el: NgElement) {
    	el.domElement.innerHTML = 'Yo!';
    }
}

bootstrap(MyLightAppComponent);
bootstrap(MyShadowAppComponent);
```

The HTML content for the above is:

```
 <my-shadow-app><div class="target"></div></my-shadow-app>
 <my-light-app><my-light-app>
```

And only the second one gets the decorator applied. What am I doing wrong and how can I apply decorators to content included into the shadow DOM in this way?

**Comment by vicb** [comment]
@dylanb the component template (`<content></content>`) is the shadow DOM while your div (in `<my-shadow-app><div class="target"></div></my-shadow-app>`) is the light DOM. Templates directives only apply to the shadow DOM.

> Here is some code that does not work the way I would expect it to work.

But it is the way it should work with shadow DOM.

Might be easier to reason if you think of a complete app:

```html
<app>
   <my-shadow-app><div class="target"></div></my-shadow-app>
</app>
```

then the `ShadowSelector`  directives must be declared on the app template. Makes sense ?
