### ISSUE TITLE
Sub-optimal template compilation (duplicate work?)

### ISSUE THREAD

**Issue by CaptainCodeman** [angular/angular#9031]
* **I'm submitting a ...**
- [X] bug report

**Current behavior**
Angular may be performing unnecessary duplicate work when starting up the app. I would expect that the *first* time that a component is encountered that it's "compiled" (the template string parsed and the JS code generated) and after that it's re-used if and when the component is encountered again.

But if you use templateUrl you will see the same template file being requested over and over which suggests this may not be the case. For example, I have a price display component which is used in multiple places and the template can be requested 8+ times or more. Is it being re-parsed and re-built each time?

It seems unnecessary and wasteful.

**Expected/desired behavior**
Any templateUrl should be requested no more than once.

* **What is the expected behavior?**
Still only request the templateUrl once (erm, maybe the issue template doesn't need this same heading repeated?)

* **What is the motivation / use case for changing the behavior?**
Optimize behavior

* **Angular version:** 2.0.0-beta.X 
2.0.0-RC-1

**Comment by zoechi** [comment]
Looks similar to #6612

**Comment by CaptainCodeman** [comment]
Maybe related, but a cache would possibly just mask the issue. Whether the html is pre-cached or cached on-demand, it's really about whether it's being re-parsed and components re-compiled (presumably the only reason a template is requested in the first place?).

The duplicate / multiple requests for a template are possibly a symptom of the issue, not the issue itself.

**Comment by robwormald** [comment]
I think this happening at the injector level - using a component multiple times in a view doesn't repeatedly refetch, but it does in a child view (and thus new injector) 

Template precomp would solve this, but its probably not a bad idea to solve it for dynamic mode.

**Comment by CaptainCodeman** [comment]
Don't know if this is still the case so closing.
