### ISSUE TITLE
Speed up initial loading 

### ISSUE THREAD

**Issue by dheran** [angular/angular#9032]
We're developing an app which is partially native and partially hybrid. 
We will open cordova activity when user clicks on an menu item and finish the activity when user clicks back.
Problem with this approach is, it takes a while to render on the screen for first time. We are hosting all the resource files in the assets folder so caching doesn't make much sense. Is there any progressive way to load the application?

**Comment by pkozlowski-opensource** [comment]
@dheran this is such a general meta-question that is impossible to answer in a concise form that would fit into an issue. Not to mention that GitHub issues are only for bug reports / feature requests. Please post on one of the support channels instead: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
