### ISSUE TITLE
form controls and content projection

### ISSUE THREAD

**Issue by fxck** [angular/angular#9033]
- **I'm submitting a ...**
- [x] feature request

When you try to use `ngControl` or `ngControlGroup` inside a child component template, or/and inside `<ng-content>` / `<template>` it doesn't work. Probably because its scope is somehow limited to it's direct parent, and thus can't find that is on the parent directive `[ngFormModel]`. This makes it really hard to create some dynamic forms.

The whole usecase is:

my form model shape looks like this

``` javascript
{
  contents: ControlGroup({
    title: ControlGroup({
      en: ControlGroup({
        id: Control(),
        content: Control()
      })
    })
  })
}
```

and I'm dynamically adding `type`, that is for example `title`, `perex`, `text`, and each can have language, that is `en`, `cs`, `de` etc, I got it working fine on the backend side, but when it comes to the template, I have to repeatedly do this 

``` html
<form [ngFormModel]="form">
  <div ngControlGroup="contents">
    <div ngControlGroup="title">
      <div *ngFor="let lang of selectedLanguages$ | async" [ngControlGroup]="lang">
        <md-input placeholder="Title" ngControl="content"></md-input>
      </div>
    </div>
  </div>


  <div ngControlGroup="contents">
    <div ngControlGroup="perex">
      <div *ngFor="let lang of selectedLanguages$ | async" [ngControlGroup]="lang">
        <md-textarea placeholder="Perex" ngControl="content"></md-textarea>
      </div>
    </div>
  </div>
</form>
```

which is a lot of repetition, since neither that `*ngFor` nor `ngControlGroup="contents"` really ever changes, since the only changing part is the input itself, so ideally I'd want to create a `form-item` component, and reduce it to this 

``` html
<form-item type="title">
  <!-- template, so I can use it inside [ngTemplateOutlet] -->
  <template>
    <md-input placeholder="Title" ngControl="content"></md-input>
  </template>
</form-item>
```

with `form-item`'s template looking like this 

``` html

  <div ngControlGroup="contents">
    <div [ngControlGroup]="titleFromInput">
      <div *ngFor="let lang of selectedLanguages$ | async" [ngControlGroup]="lang">
        <template [ngTemplateOutlet]="tmpl"></template>
      </div>
    </div>
  </div>
```

and it's gonna throw error `No provider for ControlContainer`, because it's "not" a child of `[ngFormModel]`, I can solve this by providing the form instance to my `<form-item>`, so it would look like this instead 

``` html
<form-item type="title" [form]="form">
....
```

and it's template like this 

```
<div [ngFormModel]="formFromInput">
  <div ngControlGroup="contents">
  ....
```

ugly, but it will work, but now it's gonna throw `Cannot find control 'content'`, because the projected content doesn't know about `ngControlGroup` on the `form-item` and that, I have no idea how to hack around.

---

as a side note, this use case has got another small problem, that is if I wanted to do something like [placeholder]="'Title' + language" - http://stackoverflow.com/q/37654004/301596

edit: there's an issue already for the ngTemplateOutlet context https://github.com/angular/angular/issues/8368

**rc.1**

**Comment by fxck** [comment]
This https://github.com/angular/angular/issues/8368 could actually help solve it, since I could then pass the control back to the template and use `[ngFormControl]` there, so the component's template would like this 

```html
  <div ngControlGroup="contents">
    <div [ngControlGroup]="titleFromInput">
      <div 
        *ngFor="let lang of selectedLanguages$ | async" 
         #cgForm="ngForm"
         [ngControlGroup]="lang">
        <template 
          [ngTemplateOutlet]="tmpl" 
          [ngTemplateOutletContext]="{ ctrl: cgForm.control.controls.content }"></template>
      </div>
    </div>
  </div>
```

+

```
<form-item type="title">
  <!-- template, so I can use it inside [ngTemplateOutlet] -->
  <template let-ctrl="ctrl">
    <md-input placeholder="Title" [ngFormControl]="ctrl"></md-input>
  </template>
</form-item>
```

**Comment by fxck** [comment]
@kara could you please take this into consideration since you are working on the api changes? I've read the new design doc and there's not a single mention about this problem. It might just be doing something wrong, but I think it's a valid use-case and none on neither stackoverflow or gitter was able to help me with it. I can try explaining the problem better if it's not clear from the issue, just let me know..

cc @robwormald

**Comment by sod** [comment]
@fxck could you provide a link to the new design doc?

**Comment by frederikschubert** [comment]
https://docs.google.com/document/d/1RIezQqE4aEhBRmArIAS1mRIZtWFf6JxN_7B4meyWK0Y/pub

**Comment by tolemac** [comment]
It would be great.

I'm using RC6 and I have something similar:

```` html
<template #tmpl let-model="model">
  <em-textbox [(ngModel)]="model.property" name="property" required></em-textbox> 
</template>

<form #createForm novalidate name="createForm">
  <template 
           [ngTemplateOutlet]="tmpl" 
           [ngTemplateOutletContext]="{ model: model }"></template>
</form>
Form.valid: {{createForm.valid}}
````

`createForm.valid` always is true.

To solve it, I have implemented a "dirty" trick, I have added a `form` property to my `em-textbox` and I set it manually to `ngModel`.

````typescript
@Component({...})
export class EmTextboxComponent {
    (....)
    @Input() form: NgForm;

    @ViewChild("inputModel") private _inputModel: NgModel;

    ngAfterViewInit() {
        if (this.form) {
            (this._inputModel as any)._parent = this.form;
            this.form.addControl(this._inputModel);
        }
    }    
````

Then I can do: 

```` html
<template #tmpl let-model="model" let-form="form">
  <em-textbox [form]="form" [(ngModel)]="model.property" name="property" required></em-textbox> 
</template>

<form #createForm novalidate name="createForm">
  <template 
           [ngTemplateOutlet]="tmpl" 
           [ngTemplateOutletContext]="{ model: model, form: createForm }"></template>
</form>
Form.valid: {{createForm.valid}}
````

I don't like it but works.

@kara could you please tell what do you think about that?

**Comment by tolemac** [comment]
What about this? some news?

I would like to help contributing with this, but I'm not sure where start...
I think this isn't forms related, I think this is related to core.

¿Someone can tell about this?

**Comment by fxck** [comment]
Just use [formControl] and you'll be fine, you can pass form control instances easily with it.

**Comment by tolemac** [comment]
I'm not using reactive forms. I'm use template driven forms.

**Comment by fxck** [comment]
Then it's the same, you just pass around object instead of form control instance.

**Comment by tolemac** [comment]
Sorry, I don't understand you ... can you write a little example?

**Comment by tolemac** [comment]
For example:

````typescript
import { Component } from "@angular/core";

@Component({
    selector: "my-form",
    template: `
    <form #myForm="ngForm">
        <ng-content></ng-content>
        <button type="submit" [disabled]="!myForm.valid">Send</button>
    </form>
    `,
})
export class MyForm {
    objeto = {};
}


@Component({
    selector: "my-app",
    template: `
    <my-form>
        <input type="text" class="form-control" id="name" required [(ngModel)]="obj.name" name="name">    
    </my-form>
    `,
})
export class AppComponent {
    name = "Angular";
    obj = {};
}
````

How to do that `myForm` validation will be affected by projected input?

**Comment by dobrevad** [comment]
Any updates on this? I'm also interested in a example of the solution @fxck mentioned.
Thanks!

**Comment by valera33** [comment]
any solutions to @tolemac problem?

**Comment by maxime1992** [comment]
@fxck I don't understand how you got that working.

I've made a small stackblitz repro: https://stackblitz.com/edit/angular-5n2wxu

If you have some time helping on that, really curious how to get it working.

**Comment by JonasRudolph** [comment]
Hey guys :) I just found a solution in [this SO-response](https://stackoverflow.com/a/42145570) (when using ngModel):

```ts
import {Component} from "@angular/core";
import {AfterContentInit, ContentChildren, QueryList, ViewChild} from '@angular/core';
import {NgForm, NgModel} from '@angular/forms';

@Component({
    selector: "my-form",
    template: `
    <form #myForm="ngForm">
        <ng-content></ng-content>
        <button type="submit" [disabled]="!myForm.valid">Send</button>
    </form>
    `,
})
export class MyForm implements AfterContentInit {
    @ContentChildren(NgModel, {descendants: true})
    public models: QueryList<NgModel>;

    @ViewChild('myForm')
    public form: NgForm;

    ngAfterContentInit(): void {
        // This is needed because when <input>s get transcluded into the form via ng-content, the form will not pick them up as children
        this.models.forEach((model) => {
            this.form.addControl(model);
        });
    }

}


@Component({
    selector: "my-app",
    template: `
    <my-form>
        <input type="text" class="form-control" id="name" required [(ngModel)]="obj.name" name="name">    
    </my-form>
    `,
})
export class AppComponent {
    obj = {name: ''};
}
```

**Comment by AsafAgranat** [comment]
> Hey guys :) I just found a solution in [this SO-response](https://stackoverflow.com/a/42145570) (when using ngModel):

This yields the error `Cannot read property 'addControl' of undefined`

**Comment by srinivasanr22** [comment]
Hey guys - any update on this issue? 

@AsafAgranat - i tried the way which you are demonstrated here, but its not work-out.

**Comment by limitlessx** [comment]
when i changed this @ViewChild('myForm')  to @ViewChild(NgForm), the addControl went wrong.

**Comment by maxime1992** [comment]
I'm not sure how helpful that is for you guys, but if the final purpose is to break down your form into sub components we've been working at work on a generic solution that simplifies that process a lot.
If it can be of any help, here's the repo: https://github.com/cloudnc/ngx-sub-form
