### ISSUE TITLE
Release status is not trackable by the public

### ISSUE THREAD

**Issue by alippai** [angular/angular#9034]
**I'm submitting a ...**
- [x] feature request

**Current behavior**
There is no publicly available PM and docs for the last month

**Expected/desired behavior**
Any blogpost, tweet, milestone (it's outdated on GitHub) on the release status

**What is the motivation / use case for changing the behavior?**
Better PR, happy developers.

**Comment by woppa684** [comment]
According to the weekly meetings there should be an RC.2 release later today.

https://docs.google.com/document/d/150lerb1LmNLuau_a_EznPV1I1UHMTbEl61t4hZ7ZpS0/edit

**Comment by StephenFluin** [comment]
Closing this as we're trying to get better about sharing our plans via the weekly meeting doc (listed above), blogposts that acknowledge progress and changes, and more frequent posts & messages about where we're headed.
