### ISSUE TITLE
Angular 2 RC1: RxJS not installed correctly even if in package.json

### ISSUE THREAD

**Issue by dragGH102** [angular/angular#9036]
**I'm submitting a ...**
- [X ] bug report

**Current behavior**
In my Angular 2 application I use SystemJS to load modules.
All the modules (**dependencies**) to be installed are listed in **package.json**, as well as 

"rxjs": "^5.0.0-beta.6",

**Expected/desired behavior**

I'd expect **npm install**, just installs all the module listed in **package.json**
It's the case for most of the but no rxjs.

In fact after **npm install**, if I run

> npm ls | grep 'rxjs'

 I get:

        ├─┬ UNMET PEER DEPENDENCY rxjs@5.0.0-beta.8
        npm ERR! peer dep missing: rxjs@5.0.0-beta.6, required by @angular/core@2.0.0-rc.1
        npm ERR! peer dep missing: rxjs@5.0.0-beta.6, required by @angular/http@2.0.0-rc.1

However running manually

> npm install rxjs@5.0.0-beta.6

resolved the issue completely (including client error:

> zone.js:101 GET http://localhost:3000/symbol-observable 404 (Not Found)

)

**Why isn't rxjs correctly installed with NPM INSTALL?**

* **Please tell us about your environment:**

* **Angular version:** 2.0.0-rc1
* **npm**:  3.9.3
* **node**: 6.2.1
 
* **Browser:** Chrome (latest)
 
* **Language:**  Typescript

**Comment by pkozlowski-opensource** [comment]
In your pacakge.json you've got `^5.0.0-beta.6` and `^` means "get me the latest one from the 5.x" line which in your case happens to be `rxjs@5.0.0-beta.8`. At the same time Angular needs `rxjs@5.0.0-beta.6` (specifically this version) hence the conflict.

In any case this is more of the npm question than Angular question so doesn't belong here. Please use an appropriate channel to submit support requests: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
