### ISSUE TITLE
ngModel doesn't seem to support object property array expressions

### ISSUE THREAD

**Issue by tstone84** [angular/angular#9038]
I'm submitting a bug report.
**Current behavior**
I'm attempting to create a component that is dynamic in nature. I have a definition of the controls on a form and an entity. Based on a binding property value in the control group, I set the ngModel using an expression accessing the entity property using the properties array of the entity.

EX: [(ngModel)]="entity[control.BindingProperty]"

Where entity is an object: {prop1: 'text', prop2: 'number'...}  and 'control.BindingProperty is: "prop1" for example.

This binds the value on the first show, however, upon changing the value of 'entity', the values in the template do not update.  I have verified that the 'entity' in my component is updated using the ngOnChanges event.

**Expected/desired behavior**
I would expect that when I change the value of 'entity' that the markup would update the input with the new value.

* **Angular version:** 2.0.0-rc.1 
 
* **Browser:** Chrome 50.0.2661.102 m
 
* **Language:**  TypeScript 8.11

**Comment by zoechi** [comment]
I think that is answered on SO already http://stackoverflow.com/questions/37661947/angular2-ngmodel-doesnt-seem-to-support-object-property-array-expressions

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by tstone84** [comment]
It turns out my issue was not with the way I was binding, but with an ngControl I had in my template: [ngControl]="control.Key". When I removed this, things worked just fine.

**Comment by pkozlowski-opensource** [comment]
OK, sounds like it got resolved.
