### ISSUE TITLE
TAAS or Template As A Service

### ISSUE THREAD

**Issue by shlomiassaf** [angular/angular#9049]
A bit humour doesn't hurt, but a real idea it is!

Offline compilation is great but it has it's limitation, no runtime compilation. If you need to compile ad-hoc templates you're currently lost. 

As angular gain's more popularity this limitation will make more noise, it started already #6886 

Here are some points:

  * The use case is limited, maybe 5% of the apps out there. But its a use case non the less.
  * A lot of those use cases can be solved using angular tools (with more effort and boilerplate)
  * Angular will eventually expose an API for runtime template compilation and instantiation, no doubt.

**So I was thinking about this, if we want to have pure offline compiled application and we have the need for runtime compilation, this can be easily done in the server, right?**

**Calling an API with a raw template and getting back all the ingredients angular needs as if it was compiled offline and had those already!**

This doesn't block the option to ship the app with a runtime compiler as well, but it also allows TAAS :)
Another use for server side rendering!

@gdi2290 @jeffwhelpley Doable?

**Comment by mhevery** [comment]
You can combine offline and online compilation. You will just have to pay
for the extra bytes on the wire.

**Comment by shlomiassaf** [comment]
I know you can, this is just another option.

Instead sending the compiler over the wire there is an option to compile on the server...
another option, not instead (which isn't possible, it must be doable on the client as well)

This can enable caching of templates or even sending the app without templates letting the server render them.

A lot of nice things, role based templates etc...

**Comment by shlomiassaf** [comment]
Since this is an idea not directly related to the repo no point in polluting the issues, i'll close this

**Comment by gdi2290** [comment]
you're most likely looking to load the compiler asynchronously in a web worker after initial boot during cpu idle to get best of both worlds
