### ISSUE TITLE
The application throws an exception when tested on a simulated mobile device

### ISSUE THREAD

**Issue by soloproyectos** [angular/angular#9051]
The applications throws an exception when it is tested on a simulated mobile device. I use Dartium Chrome and the "toggle device" button included in the debugger console. It throws the following exception:

_EXCEPTION: Symbol("AppComponent") implements interfaces but does not declare them: Symbol("AfterContentChecked"), Symbol("AfterContentInit"), Symbol("AfterViewChecked"), Symbol("AfterViewInit"), Symbol("DoCheck"), Symbol("OnChanges"), Symbol("OnDestroy"), Symbol("OnInit"). See https://goo.gl/b07Kii for more info._

Steps to reproduce the problem:

- Create a project from scratch (stagehand version: 1.0.8)
```bash
> stagehand web-angular
```
- Include the following directive in the pubspec.yaml file (**this is causing the error**):
```text
transformers:
- $dart2js:
    commandLineOptions: [--enable-experimental-mirrors]
```

- Get dependencies and run the dart server (pub version: 1.16.0)
```bash
> pub get
> pub serve
```
- Launch Dartium browser (dartium-lucid64-full-stable-1.16.0.0)
- Open the debugger console (Ctrl + Supr + J)
- Press the "Toggle device mode" button (the little button at the top left of the console)
- And refresh (**wait for a few seconds to view the error**)

More info:
OS version: Xubuntu 16.04
Angular 2 version: 2.0.0-beta.17

Attached is the app:
[app.zip](https://github.com/angular/angular/files/301463/app.zip)

**Comment by zoechi** [comment]
Sounds like #8305
