### ISSUE TITLE
Dynamic property binding between parent and child component in Angular 2 (Rootscope)

### ISSUE THREAD

**Issue by NayabHussain** [angular/angular#9055]
**how can we dynamically bind the property of child component to the html page of parent component in angular2?**

  **Component property binding 

Parent component should be able to access the child component** property in html page dynamically
Parentcomponent.ts parentcomponent{ ngOnInit(){

    call child component method
   } }
**Here the value must be binded**
    parentcomponent.html
    "here how to bind items of childcomponent through parentcomponent "
    ex: i want the value like {{items.name}}
    and it has to change dynamically when value in childcomponent changes
    **This is child component whixh will get the value of the** item.name  from service and bind it to the html of parent component
    childcomponent.ts
    ChildComponent{
    items:any;(Item is json object with properties item id,item name etc)
    ngOnInit(){
    this.items=Itemsservice.getItems();
    }
    }
     **This is the service method.**
    itemservice.ts
    @Injectable()
    export class ItemService{
    getItems(){
    return items;
    }

**Comment by zoechi** [comment]
Can you please wrap code blocks in triple ` to get proper formatting. 
I don't really understand what the issue is about. It sounds a bit like http://stackoverflow.com/questions/37583909/angular2-bind-ngmodel-to-a-reference-of-a-property

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by gdi2290** [comment]
you need to use an EventEmitter on the child component to emit an event to it's top most parent component that will update the data sent from it's child.

**Comment by NayabHussain** [comment]
@gdi2290 
There is no event to use EventEmitter in our child componnet. Without using event emitter I want to bind data to the parent html page dynamically  using angular2. Please ping the solution

**Comment by vicb** [comment]
> you need to use an EventEmitter on the child component to emit an event

As @gdi2290 said, the way to communicate from a child to a parent is an EventEmitter.
Alternatively you could also use some kind of message bus.
