### ISSUE TITLE
Dart Angular2 JS Interop bug - cannot invoke method

### ISSUE THREAD

**Issue by daniel-v** [angular/angular#9056]
* **I'm submitting a ...**
- [x] bug report

**Current behavior**
I can't invoke JS class instance method from Dart with very specific set of circumstances:

- The name of the method must be `open`. 
- Parameters and return type of the method does not seem to affect behavior..
- The name of the class does not affect the behavior. 
- The function must be a method of a class.
- First invocation to the method must happen from inside an Angular 2 Component.
- If an invocation to the method happens say right after calling `bootstrap`, all is well.
- Happens with transpiled code only, Dartium seem to be OK.

**Expected/desired behavior**
I can invoke JS class instance method from Dart with the above constraints.

* **Reproduction steps**
```bash
git clone https://github.com/daniel-v/angular2_js_interop.git
pub get && pub serve
# open in non-dartium browser and click on button
```
* **What is the expected behavior?**
Upon clicking on the button, a console log message appears without any errors: `open called`

* **Please tell us about your environment:**
Windows
Dart 1.16.1
Angular 2.0.0-beta.17
JS 0.6.0

* **Angular version:** 2.0.0-beta.17
 
* **Browser:** all 
 
* **Language:** Dart

PS: let me know if you need any more information or if I can aid you in any way.

**Comment by mhevery** [comment]
sorry, this is a Dart issue, not Angular. Please take it to the Dart repo.

**Comment by anders-sandholm** [comment]
This issue was moved to dart-lang/sdk#26667
