### ISSUE TITLE
DOM manipulation / querying

### ISSUE THREAD

**Issue by markpritchett** [angular/angular#9057]
I am struggling to understand how to do DOM manipulation / querying the Angular 2 way.

I think there is a strong need for documentation on this area as the community are resorting to using the document object (which I'm guessing is the wrong approach).

I've two examples of things I'm trying to achieve that I believe can only be done with DOM manipulation, namely:

1. Scroll Sync on multiple divs - here's a http://jsfiddle.net/HB7LU/24745 showing a working example from Angular v1

2. Making two elements the same height (using the tallest element).  I'm trying to implement fixed columns in a table.  I was thinking of having two tables, the second of which would be scrollable and then the height of each td element would be set to the maximum height out of the two tables.

Any pointers would be appreciated.

**Comment by zoechi** [comment]
Documentation issues are maintained in the https://github.com/angular/angular.io repository. 
Can you please reopen there?

**Comment by markpritchett** [comment]
Opened at https://github.com/angular/angular.io/issues/1612 as requested
