### ISSUE TITLE
Http tedious to use with JSON

### ISSUE THREAD

**Issue by matejkramny** [angular/angular#9058]
**I'm submitting a feature request**

**Current behavior**

Currently every http request has to be configured manually & its very tedious.

```
headers = new Headers({...})
this.http.get('/user', { headers })
.subscribe(user => {
	... json decode ...
	console.log(user)
}, err => {
	console.log(err)
});
```

**Expected/desired behavior**

in Angular 1 it was possible to set default content-type, and it was possible to automatically decode the response into json when the content-type was `application/json`.

Angular 2 seems to take 2 steps forward and 2 back with this since it is very tedious to keep repeating `JSON.parse` etc. This contributes to more LOC needed to write some sensible code.

There should be a class that extends `Http` and takes care of this.

* **What is the motivation / use case for changing the behavior?**

Developer productivity (& sanity)

* **Please tell us about your environment:**

* **Angular version:** 2.0.0-rc1
 
* **Browser:** [all] 
 
* **Language:** [all]

**Comment by fxck** [comment]
it doesn't have to be configured manually with every request, you can easily extend http yourself and create your own http class that suits your needs

like angular2-jwt did for example https://github.com/auth0/angular2-jwt/blob/master/angular2-jwt.ts

**Comment by matejkramny** [comment]
Looks like the solution. I extended `RequestOptions` but json parsing is a step ahead of that.

I take it this isn't expected to be in Angular and should be done in a library?

**Comment by fxck** [comment]
You can decode response as well, simply do something like this 

```
   return this.http.get(url, {
      headers: headers
    }).map(res => res.json());
```

instead of just 

```
   return this.http.get(url, {
      headers: headers
    })
```

**Comment by ericmdantas** [comment]
> I take it this isn't expected to be in Angular and should be done in a library?

Seems to be the way forward.

**Comment by matejkramny** [comment]
#2684 is what i was after
