### ISSUE TITLE
Reflector._typeInfo should be object not map

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#906]
It is always made of "factory", "parameters" and "annotations", so there's no reason for it to be `Map`. Making it an object would speed up instantiation of type info and lookup.

**Comment by yjbanov** [comment]
@vsavkin @mhevery, does it make sense?

**Comment by yjbanov** [comment]
Forgot to mention that it will also make

**Comment by vsavkin** [comment]
It makes sense.

**Comment by sigmundch** [comment]
fwiw - I tried this locally a couple weeks ago and it seemed possible to do this even with private properties if we are willing to put the definition of this object directly in reflector.ts

**Comment by yjbanov** [comment]
I'm going to bump the priority on this as we're entering the optimization phase.
