### ISSUE TITLE
Observable from window resize event is ignored by change detection in Internet Explorer

### ISSUE THREAD

**Issue by rasmk** [angular/angular#9060]
- **I'm submitting a bug report**
- **Current behavior**

I have an observable to trace window resize events: `Observable.fromEvent(window, 'resize')`.
Than later in the code I subscribe to it and update fields in my component class:

```
    resizeEvtObs.subscribe(val => {
      this.width = val.width;
      this.height = val.height;
    });
```

The fields are bound to the template with interpolation: `Window dimensions: {{ width }} x {{ height }}`.

When I run this in Firefox, Chrome or Edge, the binding works perfectly and my page is updated immediately.
In Internet Explorer he binding is never updated though.
- **Steps to reproduce**

http://plnkr.co/edit/J7L0G0Iw5CHBulma0sND
Best to run the preview in a separate window mode, as the screen updates are immediate then (in the browsers that work).
- **Expected/desired behavior**

I would like the app in IE to behave like in the other browsers.
As all the other browsers behave as expected, I suspect the bug lies somewhere in Angular missing the IE window resize event and not triggering the change detection. I don't know enough of the NG internals to know better.
- **Angular version:** 2.0.0-rc.1. I was able to reproduce in beta17 too.
- **Browser:** Internet Explorer 11 (11.306.10586.0).

**Comment by pkozlowski-opensource** [comment]
It is not Angular thing, IE11 simply doesn't support `resize` event, see: http://stackoverflow.com/questions/20875688/how-to-detect-element-resize-on-ie11-alternative-for-element-onresize-event

Not sure we can do anything about it...

**Comment by rasmk** [comment]
@pkozlowski-opensource The event is detected fine. In the [plunk](http://plnkr.co/edit/J7L0G0Iw5CHBulma0sND) I log to console in the `subscribe` function. And the console outputs the stream updates correctly. Only the values are not refreshed on the screen.
The SO question you are referring to concerns onresize detection on arbitrary DOM element. I believe it is not relevant for this issue.

I forked the plunk to http://plnkr.co/edit/Aum4b6H614Z8iLpEQTct and experimented a bit more.
I tried to put `setTimeout` inside `subscribe` and update the values in timeout. But still no luck.
On the other hand, if I update the title in a `setInterval`, the title is updated and the screen dimensions bindings are updated too, to the most recent value.

All in all, the binding update from the event -> stream does not work, even via timeout.
The values are stored in the component though and are brought to screen the next time change detection is run.

**Comment by zoechi** [comment]
Maybe it's a zone issue. Can you try http://plnkr.co/edit/APA4wM5zuprpNptPsayc?p=preview
My Linux box won't run IE just now :-/

**Comment by rasmk** [comment]
@zoechi, your guess is right. Your plunk works in IE.
What does it mean?

**Comment by rasmk** [comment]
Closed incidently :/
Reopening until it's clear what's the way to proceed.

**Comment by ericmartinezr** [comment]
http://plnkr.co/edit/O2ONLUJpcwe3RdCybhA9?p=preview

**Comment by nosachamos** [comment]
@ericcarraway when I run your plunk in Chrome, most of the times the size updates, but sometimes it doesn't. Not sure what's going on but surely looks like a zone problem.

**Comment by ericcarraway** [comment]
@nosachamos intended to tag @ericmartinezr 😉

**Comment by nosachamos** [comment]
haha true, thanks man!

**Comment by ericmartinezr** [comment]
@nosachamos lol :joy: I haven't been able to reproduce the *non-working case*. The Observable case is more obvious since they can run outside angular's zone, but I don't see how angular can run outside of its own zone. I tried it in both Chrome and IE11, in both work correctly.

**Comment by nosachamos** [comment]
@ericmartinezr exactly, so in this case you're in angular's zone and maybe it has a bug in which it is not always detecting when the event queue empties out, or something along those lines.

**Comment by rasmk** [comment]
@ericmartinezr Your plunk works fine. It's a different case though. In the real app I have my screen size detection in a service, pass it through debounce and use in several components.
I believe there are two ways to close this issue:
* since Angular is supposed to support IE, this needs to be fixed in the Angular implementation
* my approach is somehow deemed to be against the design principles of Angular and I should take care myself to trigger the change detection (e.g. with the use of `zone.run`)

Could somebody from the Angular team comment on it please, so that I know whether I should wait for the fix or handle myself?

**Comment by zoechi** [comment]
@ramk If you have this centralized in a service, it's quite easy to move this into Angulars zone like explained in my Plunker above, no need to wait for a fix.

**Comment by rasmk** [comment]
@zoechi Am I right to assume, I would have to put the zone wrap into each component that subscribes to the Observable? Or can I somehow inject the NgZone into the service and have it applied in the Observable operator (I am not clear how though)?
Are there any side effects of calling `zone.run` on NgZone? Performance penalty?

**Comment by zoechi** [comment]
Just inject it to the zone and ensure the `this.someObservable.next(someValue)` is called like

```ts
class MyService {
  resize$ = new Subject();
  constuctor(zone:NgZone) {
    window.addEventListener('resize', event => {
      zone.run(() => {
        this.resize$.next({
          width: window.innerWidth,
          height: window.innerHeight
        });
      });
    });
  }
}
```

**Comment by rasmk** [comment]
Thanks @zoechi. That's exactly what I needed.
Unless the Angular team cares to fix it globally, the issue can be closed.

**Comment by ericmartinezr** [comment]
>so that I know whether I should wait for the fix or handle myself?

Until this is implemented https://github.com/angular/angular/issues/4603 you'll have to do both

**Comment by DzmitryShylovich** [comment]
is this still an issue using the latest angular? repro?

**Comment by DzmitryShylovich** [comment]
@vicb can be closed

**Comment by trotyl** [comment]
RxJS integration in Zone.js [has been added for a long time](https://github.com/angular/zone.js/pull/843), can be closed.
