### ISSUE TITLE
Components inside ng-content are instantiated regardless of parent ngIf directives

### ISSUE THREAD

**Issue by benelliott** [angular/angular#9061]
* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**
Perhaps this is the desired behaviour but it was not what I presumed would happen.

See this plunkr: http://plnkr.co/edit/FLOQpvH9iwhnC8t7VJ8d?p=preview

I have created three components:
- TabsComponent: a component which maintains a set of tabs and displays their content using ng-content.
- TabComponent: a component which holds some content (again using ng-content) which is shown or hidden based on whether a parent TabsComponent tells this TabComponent that it is active. The content is shown or hidden using ngIf.
- LoggerComponent: a component which logs to the console on init and after view init.

You can see that before any of the tabs are clicked, both logger components inside the tabs have been initialised.

**Expected/desired behavior**

I expected that the tab content would not be initialised until its containing ngIf evaluated to true for the first time.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

See this plunkr: http://plnkr.co/edit/FLOQpvH9iwhnC8t7VJ8d?p=preview

* **What is the motivation / use case for changing the behavior?**

In my own use case I am using these lifecycle hooks to make expensive API calls, which I only want to happen if the user has opened the containing tab. At the moment, all API calls from all tab content components are fired when the app is first loaded.

* **Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.1
 
* **Browser:** all
 
* **Language:** TypeScript

**Comment by mhevery** [comment]
Sorry, this is expected behavior / working as intended. Whether a component choses to project content or not, the content is always created. Including a component should in no way change the behavior of the parent template.

**Comment by benelliott** [comment]
I see. Thanks @mhevery!

**Comment by zoechi** [comment]
@benelliott See #8277 (seems currently not supported)

**Comment by benelliott** [comment]
For anyone who is in a similar situation and finds this thread, take a look at what the ngMaterial team do to implement their own [tabs component](https://github.com/angular/material2/tree/master/src/components/tabs). From what I understand, they have created their own concept called a [portal](https://github.com/angular/material2/tree/master/src/core/portal) which allows them to dynamically instantiate components while sidestepping the regular Angular content projection, so that their initialisation can be delayed until necessary.
