### ISSUE TITLE
Angular2 Component not initializing after login

### ISSUE THREAD

**Issue by IAMtheIAM** [angular/angular#9064]
I setup authentication in my angular2 app, which is based on the [Angular2 Webpack Starter repo](https://github.com/AngularClass/angular2-webpack-starter).

Protected routes and login works perfectly, but the problem is that after login, the component does not initialize itself. It just loads the component but all the the Angular2 bindings like `{{ somevar }}` don't load, UNTIL I click on a form or click the component navigation route again. Then it initializes.

What could be causing the components to fail to load after login? 

Here is my app:
[http://starterhome.azurewebsites.net](http://starterhome.azurewebsites.net)

**Comment by aciccarello** [comment]
This is probably the wrong place to ask that. See the following link: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by IAMtheIAM** [comment]
OK, I'll go on stackoverflow. Thanks
