### ISSUE TITLE
confused about angular 2.0, microsoft<ngconf2015demo> typescript, traceur, rtts_assert

### ISSUE THREAD

**Issue by SerkanSipahi** [angular/angular#907]
Im confused about all these ( see below ) news, libs:

1.) typescript [announced](http://blogs.msdn.com/b/typescript/archive/2015/03/05/angular-2-0-built-on-typescript.aspx) that angular 2.0 will use typescript but why i cant find anything about typescript in https://github.com/angular/angular/search?utf8=%E2%9C%93&q=typescript ? 

2.) If angular 2 team really want to use typescript, does that means that they remove/kick traceur?

3.) If angular team want to use typescript what about these https://www.npmjs.com/package/rtts_assert => [see here](https://github.com/angular/angular/blob/master/karma-js.conf.js#L48) ? I like this lib

4.) Do you sync your repro( https://github.com/angular/angular ) with https://github.com/Microsoft/ngconf2015demo when all things are right( announcements )

Well, what is the roadmap? what is used and what is removed?

**Comment by mhevery** [comment]
This was just announced. Once TypeScript v1.5 will be released we will switch to it. Yes, we will drop traceur. You can still use rtts_assert

**Comment by chalin** [comment]
@mhevery: once Traceur is dropped, which tool will be handling the TypeScript to Dart transpiling and who will be driving the (continued) development of this functionality. I'm asking because I would like to contribute. Thanks

**Comment by SerkanSipahi** [comment]
@mhevery rtts_assert is a part of Angular 2.0 ?

**Comment by AliMD** [comment]
:-1:
WTF !

**Comment by mhevery** [comment]
@AliMD I have deleted your comment because it violates our https://github.com/angular/code-of-conduct/blob/master/CODE_OF_CONDUCT.md
