### ISSUE TITLE
fix(platform-server): replace public Parse5DomAdapter export with providers

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#9075]
Right now, platform_server only exports `Parse5DomAdapter`, which will soon be a private API. This API is being used by angular/universal in [several places](https://github.com/angular/universal/search?utf8=%E2%9C%93&q=Parse5DomAdapter). Instead, platform-server should export a set of providers that will automatically call `Parse5DomAdapter.makeCurrent()` when instantiated. Probably called `PLATFORM_SERVER_PROVIDERS`.

CC @IgorMinar @gdi2290 @jeffwhelpley

**Comment by IgorMinar** [comment]
actually, I think that the makeCurrent call should be done via a platform initializer so that we don't depend on a particular service being instantiated.

**Comment by jeffbcross** [comment]
Closing this since a new bootstrap method is being implemented instead, `serverBootstrap`
