### ISSUE TITLE
rc1 Router clears query string parameters

### ISSUE THREAD

**Issue by kamarouski** [angular/angular#9080]
I'm using Angular 2 rc1 with the ASP.NET website

The new Router seems to clear all query string parameters when accessing the page.

For example:

When I hit http://aweso.me/test?p=param1 

'q=param1' section is cleared for the URL and I'm not able to access parameter from my code.

Expected behavior: Query String parameters are not cleared.

This is important for compatibility reasons with old systems when the newly developed Angular 2 app must support original URLs

**Comment by frederikschubert** [comment]
The RC router is now also deprecated and will not be improved. The new router is currently under [development](https://github.com/angular/vladivostok).

**Comment by kamarouski** [comment]
Wow. Now we have three routers :) 

Is there any more or less stable router that can be used with Angular 2?

**Comment by ericmartinezr** [comment]
@kamarouski ngrx/router or ui-router. The new new new router will follow ngrx/router's concepts fwiw.

**Comment by nosachamos** [comment]
So, can we close this one?

**Comment by kamarouski** [comment]
Yes, let's close it  as it's not going to be fixed in existing router.
