### ISSUE TITLE
@angular/http throws errors of type Request type

### ISSUE THREAD

**Issue by dmho418** [angular/angular#9082]
* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**
@angular/http throws errors of type Request type.
Example of error thrown:
`Response {_body: "<HTML><BODY>503 - This request has timed out.</BODY></HTML>", status: 503, ok: false, statusText: "Ok", headers: Headers…}`

**Expected/desired behavior**
Throw an Error type.

* **Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.1 
 
* **Browser:** all
 
* **Language:** TypeScript 1.8.10

**Comment by DzmitryShylovich** [comment]
Can you pls provide working reproduction?

**Comment by DzmitryShylovich** [comment]
No answer since June. I think it can be closed.

**Comment by pkozlowski-opensource** [comment]
Thnx @DzmitryShylovich
