### ISSUE TITLE
RC1 routerLink not known property in child Component

### ISSUE THREAD

**Issue by RicardoVaranda** [angular/angular#9083]
I'm using the latest version of Angular and for some reason I need to declare 

`import {ROUTER_DIRECTIVES} from '@angular/router';`
`directives: [ROUTER_DIRECTIVES]`

In a component in which I use the following:

`  <a [routerLink]="['/createStudent']">Test</a>`

or else I get the following error:

> Error: Uncaught (in promise): Template parse errors:
> Can't bind to 'routerLink' since it isn't a known native property

My main App Looks like this:

```
@Component({
  moduleId: module.id,
  selector: 'training-ui-app',
  templateUrl: 'training-ui.component.html',
  styleUrls: ['training-ui.component.css'],
  directives: [ROUTER_DIRECTIVES],
  providers: [ROUTER_PROVIDERS]
})
```

While the child component looks like this:

```
@Component({
  moduleId: module.id,
  selector: 'app-menu-item-cmp',
  templateUrl: 'menu-item-cmp.component.html',
  styleUrls: ['menu-item-cmp.component.css'],
  inputs : ['itemName', 'iconName']
})
```

For some reason the directive dependencies are not being passed from the parent to its children, is this a common issue or am I doing something wrong?

**Comment by zoechi** [comment]
Hard to tell. Please provide a Plunker that allows to reproduce. Looks like this router will also be replaced soon. If you are about to migrate from `router-deprecated` it's probably better to wait until the new router becomes available.

**Comment by PascalPrecht** [comment]
This is intended behaviour.

Every component needs to define its own directive dependencies. If you use `[routerLink]` in the child component, but don't declare `ROUTER_DIRECTIVES` on that component, Angular doesn't know about it.

And since `<a>` doesn't have a DOM property for `routerLink` natively, you run into this error.

**Comment by RicardoVaranda** [comment]
That's perfect thanks for the clarification just wanted to make sure this behaviour was working as intended like that.

**Comment by ORESoftware** [comment]
How to do this with Angular 5?
