### ISSUE TITLE
Core.js polyfills don't work on IE9

### ISSUE THREAD

**Issue by vsakaria** [angular/angular#9084]
The core.js polyfill doesn't work in IE9 specifically. I have a polyfills.ts file which imports core-js and additionally I requires the specific shim to be sure.

`import 'core-js'; require('core-js/client/shim.min'); require('zone.js/dist/zone'); require('zone.js/dist/long-stack-trace-zone');`

And in IE9 I get the following error:

`ORIGINAL EXCEPTION: TypeError: Object doesn't support property or method 'requestAnimationFrame'`

I have used the seed project.

It's a real shame the Beta version had a standard way of dealing with IE9 and RC doesn't wired :(

**Comment by CaptainCodeman** [comment]
The build status has been showing red for IE9 for quite some time now, maybe related.

You could maybe use https://cdn.polyfill.io/v2/docs/ to add the extra pieces required if Angular isn't going to supply the pieces anymore.

**Comment by sod** [comment]
Well, the file you are looking for is here: https://github.com/angular/angular/blob/master/shims_for_IE.js

I read somewhere they can't publish/bundle it, because of license issues.

**Comment by ericmartinezr** [comment]
@vsakaria you were answered here anyway https://github.com/angular/angular/issues/5755#issuecomment-224575252

**Comment by CaptainCodeman** [comment]
The licensing issues would explain not shipping them, but possibly not why the build is failing. I presume the shims_for_IE are still being used in the tests?

**Comment by marcalj** [comment]
We need a document explaining which polyfills are required for each browser version (I'm targeting IE11+ and not sure what I should include).

Also, which polyfills are required if we use TypeScript (transpiling to ES5 or ES6), without TS (but in ES5 or ES6), etc.

A table for all options would be great!!! Thanks!

**Comment by gdi2290** [comment]
import `ie-shim`

**Comment by wesleycho** [comment]
rAF is not part of the ES spec, so it doesn't make sense for it to be in core.js.

That said, it's pretty easy to [polyfill for rAF](https://gist.github.com/paulirish/1579671), and it'd be the first thing I'd think in that situation.

The IE9 build passes currently, so that is not an issue here.

This should probably be closed and if users want, open an issue with the docs repo at https://github.com/angular/angular.io, a more appropriate location about documentation of what browsers need what polyfills.

**Comment by vicb** [comment]
> This should probably be closed and if users want, open an issue with the docs repo at https://github.com/angular/angular.io

:+1:
