### ISSUE TITLE
ngFor starts with key 0 of array

### ISSUE THREAD

**Issue by mcgri** [angular/angular#9085]
I found a strange behavior with  ngFor. I am not sure what ever it's a bug or feature ;) . It looks like it loops through key 0 of an array, even when key 0 is not there.

Lets say we have array (no key 0):
[1:{object}, 2:{object}, 3:{object}]

The ngFor would start with  key 0 and assigns undefined value.  

Here is plunk : [Plunk](http://plnkr.co/edit/fYPpjtQNtboCZNVLK3cu?p=preview)

I was expecting ngFor to work same as Array.forEach loop, but it seems like it uses "for" loops in source code of ngFor directive source code(perhaps because they are more efficient ) 

So, when length of array is less then first key value, then ngFor will print a lot of empty objects,because ngFor rely on Array.length . i.e :

```
var foo = [];
foo[33]="aaa";
console.log(foo.length); //prints 34
```

* **Angular version:** 2.0.0 RC 1

**Comment by mcgri** [comment]
It looks like there is also a "feature" with Array.length in general in all browsers which I could lay my hand on 


```
var a=["a","b","c"];  

a["Key"]='value';

console.log(a.length)  // prints 3 (Edge/FF/Chrome)

console.log(a["Key"])  // prints value(Edge/FF/Chrome)

console.log(a) // prints ["a","b","c"] (FF/Chrome) ,but in Edge it prints [object Array][0:"a",1:"b",2"c","Key": "value"] length 3
```

**Comment by mhevery** [comment]
This works as expected. If you have an array we will iterate even if it is sparse. It is just how Browser works.

```
var a = [];
a[1] = 'test';
a.length ==> 2
```

**Comment by mcgri** [comment]
JS does not support associative arrays either. I learned something new today! :) Thanks for explanation.
