### ISSUE TITLE
Angular2 Release Candidate Router 2.0.0-rc.1 history navigation broken

### ISSUE THREAD

**Issue by jeffschwartz** [angular/angular#9088]
* **I'm submitting a ...**
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**
The browser's forward nav button is permanently disabled and the browser's back nav button only works for the previous history event losing all history events preceding that one. 

**Expected/desired behavior**
Normal push and popstate history navigation via browser's back/forward nav buttons.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

1 Add release candidate router to project or use the quick start project

2  configure routing in main.ts:
```typescript
import { bootstrap }    from "@angular/platform-browser-dynamic";
import { provide } from "@angular/core";
import { LocationStrategy, HashLocationStrategy } from "@angular/common";
import { ROUTER_PROVIDERS } from "@angular/router";
import { AppComponent } from "./app.component";
import { Title } from "@angular/platform-browser";

bootstrap(AppComponent, [
    ROUTER_PROVIDERS,
    Title,
    provide(LocationStrategy, {useClass: HashLocationStrategy})
]);
```

3 Configure the router:

```typescript
import {Component} from "@angular/core";
import {Routes, ROUTER_DIRECTIVES} from "@angular/router";
import {ChangeLogComponent} from "./changelog.component";
import {ApiComponent} from "./api.component";
import {HomeComponent} from "./home.component";
import {Title } from "@angular/platform-browser";

@Component({
    selector: "my-app",
    templateUrl: "app/app.component.html",
    styleUrls: ["app/app.component.css"],
    directives: [ROUTER_DIRECTIVES]
})

@Routes([
    { path: "/", component: HomeComponent }, // useAsDefault comming soon!
    { path: "/changelog", component: ChangeLogComponent },
    { path: "/api", component: ApiComponent }
])

export class AppComponent {
    constructor(private titleService: Title) {}
    setTitle(newTitle: string) {
        this.titleService.setTitle(newTitle);
    }
}
```

4 Add  an anchor tag with routerLink attribute for each route/view in markup similar to the following:
```html
<nav>
    <h1>Preamble BDD</h1>
    <ul>
        <li><a (click)="setTitle('Preamble BDD')" [routerLink]="['/']">Home</a></li>
        <li><a (click)="setTitle('Preamble BDD Changelog')" [routerLink]="['/changelog']">Changelog</a></li>
        <li><a (click)="setTitle('Preamble BDD API')" [routerLink]= "['/api']">API</a></li>
    </ul>
</nav>
<router-outlet></router-outlet>
```

* **What is the expected behavior?**
Normal push and popstate history navigation via browser's back/forward nav buttons.

* **What is the motivation / use case for changing the behavior?**
push and popstate handling appears currently broken.

* **Please tell us about your environment:**
Mac OS X 10.9.5
Chrome browser v 50.0.2661.102 (64-bit)

* **Angular version:**
2.0.0-rc.1
 
* **Browser:**
Chrome v 50.0.2661.102 (64-bit)

* **Language:**
TypeScript v 1.8.10

**Comment by raijinsetsu** [comment]
I am also experiencing this issue.

**Comment by CaptainCodeman** [comment]
That router is no longer being developed and will be deprecated like the one before it. There is a new new new router currently in development.

**Comment by jeffschwartz** [comment]
@CaptainCodeman so the Release Candidate Router is now depricated? You aren't confusing that with @angular/router-deprecated": "2.0.0-rc.1" are you :)?

**Comment by CaptainCodeman** [comment]
@jeffschwartz No, the replacement for the deprecated router (presented at ng-conf) has also now been abandoned and will be replaced by another router. I don't know whether the names will all shuffle down or what the plan is.

The new router repo is currently here: https://github.com/angular/vladivostok

**Comment by jeffschwartz** [comment]
@CaptainCodeman it's raining routers lol. OK and thanks for the heads up. Knowing this now really makes me wish this would have been made very obvious somewhere in the current documentation so that I and others might not have even bothered with it in the first place. Yes, the docs do refer to the deprecated router but I and I can assume many others thought they are referring to the one that actually has deprecated as part of its name and which is included in the quick start project. Knowing this now also makes me wonder why the Angular2 development team isn't just deferring the whole router business to UI-Router2 or whatever they are going to call the ang2 version? Oh, well lol.

**Comment by Namek** [comment]
I guess that even the new new router will be a thing that will be not accepted widely. I don't get why they insist on having *Component* Routers. That should simply a router where component creation is an addon, not a must.

Whatever, @jeffschwartz this issue probably won't be fixed, so I propose to close this issue.

**Comment by CaptainCodeman** [comment]
Yes, it's appalling that the current router was given the RC1 designation when it was known to be incomplete and that the real state of things wasn't made more clear. It simply ends up wasting a lot of people's time, energy and money and I don't see the point - it isn't going to endear anyone to the framework, simply leave the impression that it doesn't work properly and is unreliable.

There are some hints in the weekly meeting notes but the communication has been simply awful. Communication should be more than tweeting PR news, it should be keeping people informed.

**Comment by raijinsetsu** [comment]
Can we use this issue to track updating the documentation to indicate that
both routers are deprecated?

**Comment by ericmartinezr** [comment]
@raijinsetsu you could use this one or any other issue opened about the new new router where people were told that a new new new router is on the way. Anyway, I don't think they will write documentation about anything that's unfinished. So my answer would be :use ngrx/router or ui-router, and if you want anything related to the official router you'll just have to wait.

**Comment by jeffschwartz** [comment]
This router is dead. Long live the new new new router :)

**Comment by Namek** [comment]
Discussion about somewhat-lack of transparency will go on and on. As others, I lost a lot of time for both routers, throwing them away at the end.

And just few hours ago we were introduced to another deprecation: https://github.com/angular/angular/commit/515a8e07654b745b60a9a12762081dbd0702a4fa And I just feel like DI will be deprecated soon. However, [#WeBelieveInYou](https://scotch.io/bar-talk/the-best-news-from-angulars-ng-conf-2016#webelieveinyou-angular-team)

**Comment by jbeckton** [comment]
Fortunately there was hope for my situation. Just some undocumented reorganization of some code did the trick. This may help with the history issue as well.

@jeffschwartz  try this fix for your situation...

https://github.com/angular/angular/issues/9099#issuecomment-224935527

**Comment by jeffschwartz** [comment]
@jbeckton thanks for the headsup on #9099. I've decided to use the ui-router version for angular2. It looks very feature complete at the moment and appears to also be simple to use. I know from previous use with angular1 that ui-router support is top notch. I will, though, reevaluate my decision once the vladivostok router is documented and officially released. Thanks again.

**Comment by jbeckton** [comment]
@jeffschwartz  I too liked the ui-router with angular 1.x, I did not know they had one for 2.0 that was far enough along to consider. I'm heading over there now to check it out. Thanks!

**Comment by jeffschwartz** [comment]
@jbeckton http://angular-ui.github.io/ui-router/1.0.0-alpha.3/modules/ng2.html

**Comment by jeffschwartz** [comment]
Because of the recent information presented [here](https://angularjs.blogspot.com/2016/06/improvements-coming-for-routing-in.html) and the excellent article [here](http://victorsavkin.com/post/145672529346/angular-router) I've decided to move forward with [3.0.0-alpha.3](https://github.com/angular/vladivostok).

**Comment by jbeckton** [comment]
How can we be sure? We have heard "This is the one" before. I just need to
produce solid software solutions for my clients, I cannot keep chasing
various attempts to create a router. Seems like they could have worked with
the guys that built UI-Router and came up with something that satisfies the
required use cases.

**Comment by sharpmachine** [comment]
I'm experiencing this exact issue in the new router: `3.0.0-alpha.3`. Back buttons works once and forward button doesn't work at all.

**Comment by zoechi** [comment]
@sharpmachine maybe angular/vladivostok#64

**Comment by tomskip123** [comment]
I have this issue in 3.4.1?
