### ISSUE TITLE
Document how to create a codegen bootstrap

### ISSUE THREAD

**Issue by vicb** [angular/angular#9089]
Add this information to https://github.com/angular/angular/tree/master/modules/%40angular/compiler-cli

@wardbell is there any plan for angular.io ?

**Comment by thelgevold** [comment]
This would be very helpful. I have not seen any working samples of this yet...

**Comment by vicb** [comment]
see https://github.com/angular/angular/blob/master/modules/%40angular/compiler-cli/README.md#install-and-use
