### ISSUE TITLE
Extend *foreach syntax to support ES6 data structures

### ISSUE THREAD

**Issue by TylerEich** [angular/angular#909]
~~This might be a pedantic request, but shouldn't `*foreach` microsyntax use `of` instead of `in`, since a for-in loop (`for (item in items)`) iterates an array's keys rather than its values?~~

This issue has expanded to include more than array iteration. [One of my comments on this thread](https://github.com/angular/angular/issues/909#issuecomment-78165514) describes one possibility for making the `*foreach` syntax more flexible.

**Comment by pkozlowski-opensource** [comment]
Hmm, ng1 is uses `in`: https://docs.angularjs.org/api/ng/directive/ngRepeat

**Comment by TylerEich** [comment]
@pkozlowski-opensource when ng1 was designed, for-of loops didn't exist in JavaScript. Maybe it would make more sense now to adopt the ES6 `of` operator…

**Comment by pkozlowski-opensource** [comment]
@TylerEich sure, my comments was more a "note to self" to take historical reasons into account to ease migration.

**Comment by caitp** [comment]
personally, I love it. closer to the language people are actually writing

**Comment by mhevery** [comment]
I could go either way. Can you point us to some prior art showing that foreach-of is common?

**Comment by gdi2290** [comment]
I was also thinking the same way with `of` but that would also mean switching `foreach` to `for`. The `of` implies that you're providing a functor (iterable objects [aka you can use .map or .filter etc]) which is why js introduced `of`. This include Arrays and Objects but is not limited by them since you can provide your own functors. an example in es6/es7 is
```es6
for (let item of new WebSocket('wss://url.com/realtime/') {
  console.log(item);
}
```
in angular you do this with filters
```es6
<li *foreach="var item in items | async">
  {{ item }}
</li>
<script>
  class Cmp {
    constructor() {
      this.items = new WebSocket('wss://url.com/realtime/');
    }
  }
</script>
```
If I'm understanding the the pipeline correctly the problem with the interface above, in angular 1 and 2, is that your pipes need to know the type of object rather than assuming the interface will always be the same. Again this may not actually be the case for angular2 but I wasn't too much of a fan of the `async`/`rx` pipe for the Observables integration

**Comment by mhevery** [comment]
So it sounds like we can have `foreach-in` or `for-of`.

Our choices are:

1. do nothing `foreach-in`
2. switch to `foreach-of` 
3. switch to `for-of` 
4. have selector which supports all of the above.

Anyone want to vote?

**Comment by caitp** [comment]
I like the idea of using "for="#thing of collection", but unfortunately html itself uses the "for" attribute for some elements, so it might not be a great thing to use. I'd prefer not supporting "both", though.

**Comment by gdi2290** [comment]
I'm all in for only providing `for-of` (keeping foreach during alpha) since we (js community) is trying to convert the everyone to use `for-of` (sadly perf problems atm for js). Doing so would be more inline with the original principles of angular (using future js/html today) but may or may not need work to rework some of the patterns of the codebase. The minimal amount of work leaving everything the way it is and adding a `for-of` for experiments until the decision is reached. ("for" attribute may be taken but angular2  already accounts for this using *for="" or template="for" to prevent conflicts)

**Comment by caitp** [comment]
I'm aware of the "workarounds", but I've expressed pretty loud and clear that the workarounds are bad ideas (wider api surface for no good reason, higher learning curve for new users, more cases to test and maintain with no real benefit, etc). Lets not turn this into #133 though, I've said my piece =)

**Comment by gdi2290** [comment]
haha I wasn't trying to bikeshed but I do see your point. I'm not the best at names (case in point my username) so I couldn't say I'm qualified to suggest one to replace `for` other than keeping `foreach` with the difference being `of` and `in`

**Comment by Alxandr** [comment]
@gdi2290 As far as I know, `for .. of` is a pull-based mechanism, and given that javascript does not support async -> sync execution (or blocking), using `for .. of` to aggregate a event stream (like a websocket) does not make sense.

**Comment by SekibOmazic** [comment]
`*for="#item of items"` would be nice.

**Comment by gdi2290** [comment]
My argument is trying to provide concepts that are trying to be pushed in the future of javascript into the framework today. @jhusain is better suited to articulate the reason behind the example (using `for var item of new WebSocket()`)  but I may also be wrong in my assessment. I'm sure I'm missing the `await` keyword that would be more inline with the pipe version but then also begs the question of an `async` directive


```es6
for (let item of new WebSocket('wss://url.com/realtime/') {
  console.log(await item);
}
```

```html
<li *foreach="var item in items">
  {{ await item }}
</li>
<script>
  class Cmp {
    constructor() {
      this.items = new WebSocket('wss://url.com/realtime/');
    }
  }
</script>
```

**Comment by TylerEich** [comment]
I would **love** to see something like:

  - `*for="let prop in object"`
  - `*for="let item of iterable"`

I share @caitp's concern with the `for` attribute already being defined by the HTML standard; maybe the `*` prefix removes that concern…

I also believe `*foreach` has a place alongside `*for`, possibly as follows:

  - `*foreach="arrayOrMapOrSet as #value"`
  - `*foreach="arrayOrMapOrSet as (#key, #value)`

`as` is not a [reserved keyword in JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar), so it's meaning can flex for Angular's purposes. `forEach` is a prototype method on [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/forEach), [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/forEach), and [Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach); Angular might be able to internally allow:

  - `*foreach="object as #value`
  - `*foreach="object as (#key, #value)`

to make the transition easier.

**Comment by mhevery** [comment]
Sounds like people are voting for: `*for="#item of iterable"` (existing `for` property on `Element` is not an issue)

**Comment by TylerEich** [comment]
@mhevery Is there any merit to expanding the `*foreach` syntax? Or should `*for` replace `*foreach`? I can't recall if there will be an internal `$index` property anymore; if that's gone, should there be some way to assign the index to a variable as well?

**Comment by SanderElias** [comment]
+1 for the `*for="#item of iterable"`
This is nicely aligning with the new es6 syntax, and as it is clearly stating it demands a iterator, you don't need to take special care for objects. 
However this brings up a new question.  how about destructuring? an usecase:

`*for='[#key, #val] of Object.entries(myModel)"`

The Object.entries(myModel)  is a substitute for something in the controller that produces something similar.

**Comment by gdi2290** [comment]
in order to keep `$index` helper it does make sense to keep `*foreach` for those who want to use the old style and everything that may come with it. Maybe there should even be a way for users to define their own helpers so they can create `$even`, `$odd`, `$middle`, `$last`, `$first`. That might be asking too much

Destructuring is a good point since es6 introduced a lot of sugar the template syntax doesn't really support it since you
>  sidenote: Object.entries returns an array which is why we're destructuring with the same type
>  example: `var [a, b] = [a, b]`

```html
<li template="for; [#key, #val]; of=Object.entries(myModel);"></li>
<template for [#key, #val] [of]="Object.entries(myModel)">
  <li></li>
</template>
```
unless you use `var` or was it `def`
```html
<li template="for; var [#key, #val] of=Object.entries(myModel);"></li>
<template for var="[#key, #val]" [of]="Object.entries(myModel)">
  <li></li>
</template>
```
which can look like 
```html
<li *for="var [#key, #val] of Object.entries(myModel)">
  {{ key }}: {{ val }}
</li>
```

**Comment by mhevery** [comment]
`*for` is replacement for `ng-repeat` we can move all of the existing features over once we settle on the basics.

**Comment by mhevery** [comment]
@gdi2290 your proposal do not fallow the micro-syntax expansion rules. (see: https://github.com/angular/angular/blob/master/modules/angular2/docs/core/01_templates.md#template-microsyntax)

**Comment by SanderElias** [comment]
@mhevery I did reread the micro-syntax. As I see it it does not prevent destructuring as in my use-case. 
Supporting it would make the micro-syntax line up with ES6 quite nicely.

**Comment by gdi2290** [comment]
yeah it doesn't work haha I was only suggesting that we could probably add it. deconstructing is probably too much for the template microsyntax but it might be a good idea to consider it
```html
<li template="for; #[key, val] of=Object.entries(myModel);"></li>
<template for #[key, val] [of]="Object.entries(myModel)">
  <li></li>
</template>
```
I just had the # in the wrong places

**Comment by gdi2290** [comment]
After double checking out the microsyntax again in order to exporting the internal variables are done with `#` which mean you would use `[#key, #val]` after deconstructing but the question is if the microsyntax can detect deconstructing

**Comment by mhevery** [comment]
@gdi2290 Not sure I understand you goal. 

1. We think iterating over maps was a bad idea, and we don't want to support it. Instead we will have a pipe which can convent a map into iterable. `<div *for="var i in map | toArray">{{i.key}}: {{i.value}}</div>`
2. We don't want to have special `$index` variables. instead: `<div *for="var o in os; var  i = index">{{i}}: {{o}}</div>`

**Comment by gdi2290** [comment]
The goal was trying to bring more imperative es6 features to the declarative template world but that's probably defeating the purpose of writing declaratively 

as template
```html
<template for [#key, #val] [of]="Object.entries(myModel)">
  <li></li>
</template>
```
as js
```es6
// actually I'm not sure if you can deconstruct here but I'm sure you can ;)
for (var [key, val] of Object.entries(myModel)) {
  console.log('Key:', key, 'Val:', val);
}
```
`Object.entries` converts an object into an iterable where each time you invoke `.next()` you get a 2-tuple (to preserve the key) providing the key and value. So providing something like `| entries` (assuming we create our own pipe `entries` using `Object.entries` internally)
```html
<div *for="var obj in objectLists | entries; var key = obj[0]; var val = obj[1]">{{i}}: {{o}}</div>
```
is more declarative even if you're not deconstructing the point of deconstructing is that it's imperative

**Comment by otodockal** [comment]
<pre>*for="#item of iterable"</pre> 

because of ES6 (ES2015) syntax alignment, it's good idea!

**Comment by alexpods** [comment]
@gdi2290 When you're writing:
```js
for (let item of new WebSocket('wss://url.com/realtime/') {
  console.log(await item);
}
```

I think you're confusing it with [`for on` loop] (https://github.com/jhusain/asyncgenerator) for asynchronous generators:
```js
for (let message on new WebSocket('wss://url.com/realtime/') {
  console.log(message);
}
```

`WebSocket` does not implement [iteratable](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols) interface (at least in ES6). In ES7 it'll become an asynchronous generator, if TC39 will decide it so

**Comment by gdi2290** [comment]
the TC39 is trying to push js towards a unified method of dealing with async so an iterable WebSocket is the ideal solution. since it was just example code I figured I might as well. I did get the `await` wrong

**Comment by Alxandr** [comment]
The problem isn't `await`, it's `for .. of` as opposed to `for .. on`, which behaves very differently.

**Comment by gdi2290** [comment]
oh that's right, I totally overlooked that subtle.

**Comment by ewinslow** [comment]
Since we're voting, big +1 from me to `*for="#item of items"`.

**Comment by Evertt** [comment]
Also +1 from me to `*for="#item of items"`

**Comment by krimple** [comment]
Angular 2 learning question: Is the * prefix solving a problem with a specific naming collision as mentioned above? Saw this at ng-conf, been reading and still haven't found where the reasoning of prefixing with * came from.  Googling "*foreach" and "*for" with "angular2" isn't bringing up any explanations.  Can this be clarified?

**Comment by pkozlowski-opensource** [comment]
@krimple nope - this is not to avoid naming collisions - this is just sugar on top of the full form, see: https://github.com/angular/angular/blob/master/modules/angular2/docs/core/01_templates.md#template-microsyntax

**Comment by mhevery** [comment]
b61b8d60b7cfd10786ccd9ba4071738d4f2bf15a

**Comment by ewinslow** [comment]
Woohoo!
