### ISSUE TITLE
Clean up TODOs from automatic explicit 'any's

### ISSUE THREAD

**Issue by ScottSWu** [angular/angular#9100]
In order to enable the --no-implicit-any flag on all angular2 code (#4924), we automatically inserted explicit 'any's where necessary. All these insertions should now marked with a TODO comment pointing to this issue. The next step is to go through these changes to verify they are correct, or change them to their appropriate types.

**Comment by AliMD** [comment]
I saw many TODO #9100 in the source !
How can find/make correct type to done these task ?

**Comment by ScottSWu** [comment]
It depends. The use of the variable / function will tell what type it should be.

If an array is declared `var names: any[] /* TODO */ = [];`, and only strings are added to it, then  `names` should probably be of type `string[]`.

If there's an interface with a method `abstract setText(text: string): any /* TODO */` and all subclasses return void, then `setText` should probably be `void`.

There are some places where the any type is necessary, which in that case it should be left and the comment removed.

**Comment by merlosy** [comment]
Hi, just wondering if the comments were normal considering @ScottSWu message,
at the end of file (maybe in other files too?):
https://github.com/angular/angular/blob/master/packages/http/src/static_request.ts
