### ISSUE TITLE
OnDestroy not fired on all instances of a component

### ISSUE THREAD

**Issue by jbeckton** [angular/angular#9107]
* **I'm submitting a ...**
- [x ] bug report

**Current behavior**
When an instance of a component is created inside ngFor from an array on the parent then the user navigates to another route the ngOnDestroy method is only called for a subset of the instances that where created. The other instances are still running in memory.

**Expected/desired behavior**
ngOnDestroy would be called on every component instance as they go out of scope (leave the route).

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

open console and look for logging messages
http://plnkr.co/edit/gFa5gHoeRh8MtWOrJH82?p=preview

* **What is the motivation / use case for changing the behavior?**
I have components that manage their own subscriptions to a socket connection and I need for them to unsubscribe when the user leaves the route that the components live under. The plunk I provided clearly shows that of the 10 instances of the component only half of them execute the ngOnDestroy method. This is where I unsubscribe to corresponding channel within the socket namespace. Since only a few of them run ngOnDestroy I'll have the others running and responding to events even though the route view that displays the event data is not active. There is about 30 channels my app can subscribe to and based on a filter I only have about 7 or 8 subscriptions active and any given time, without being able to clean up the un used subscriptions my app performance will suffer.

* **Please tell us about your environment:**
CentOs Linux & Node.js 6

* **Angular version:** 2.0.0-RC-1
 
* **Browser:** [all  ] 
 
* **Language:** [ TypeScript X.X | ES6/7 | ES5]

**Comment by ericmartinezr** [comment]
That's interesting. I really don't know what could it be, but you can use this workaround

```ts
// PanelComponent.ts

export class PanelComponent {

  @Input() name: string;

  cleanUp() {
    // Handle the clean up here
    console.log('Goodbye %s', this.name);
  }
}
```

```ts
// DashboardComponen.ts

export class DashboardComponent implements OnInit { 
  
  @ViewChildren(PanelComponent) panels;
  
  routerOnDeactivate(next, prev) {
    this.panels.forEach(cmp => cmp.cleanUp());
  }
}
```
http://plnkr.co/edit/h2MoR6i4m3pzvF8etDo6

I hope this helps you for a while until this is clarified/fixed

**Comment by zoechi** [comment]
dup of #8458 (recently fixed)

**Comment by pkozlowski-opensource** [comment]
dup of #8458 indeed, thnx @zoechi !

**Comment by jbeckton** [comment]
@zoechi How recent? I just got the RC1 a couple days ago and discovered this issue. I was on beta 13 for a while and it worked fine there. I'm not sure how to look up the build or release that includes that fix.

**Comment by zoechi** [comment]
After https://github.com/angular/angular/blob/master/CHANGELOG.md#200-rc1-2016-05-03
#8458 was created at `opened this issue on May 4`

**Comment by jbeckton** [comment]
ok so it should be available in the next release. I'll hold off on any refactoring or design changes on my side until this gets released.

**Comment by jbeckton** [comment]
@ericmartinezr Worked like a charm, this is a pretty clean work around and I can pull it out later if I want and just un-comment a line of code in the onDestroy once the framework is fixed
