### ISSUE TITLE
Angular2 with Polymer

### ISSUE THREAD

**Issue by JesusSD** [angular/angular#9108]
Material2 components for Angular2 are few and unstable and seems to remain so for a long time and to use quality components with "Material Design" must be used Polymer components and integrate them into angular 2 Incredible !.

PLEASE GOOGLE: Join and integrate natively Polymer and Angular2 unifying the syntax (now is a war, Polimer VS Angular2 while React is the real enemy). and also create components valid for desktop and mobile simultaneously as Ionic2 natively (One component for all platforms).﻿

**Comment by robwormald** [comment]
This can already be done, you can use polymer elements inside of angular apps, as they are just web components. There are some exceptions to this but generally they play nicely together.

That said, all three frameworks have different philosophies on how to do things, and so its highly unlikely the projects will ever merge, and that is *okay* - there's no war between anyone.

**Comment by JesusSD** [comment]
I want to use Angular2 with Polymer Toolbox as "ng new my-awesome-app --app-drawer-template"

Vaddin tutorial say: "2.3. Remove the AppComponent Tests
The QuickStart respository contains tests for the AppComponent class. Unfortunately, some changes that will be done to AppComponent in this tutorial would break the compilation of these tests."

**Comment by aciccarello** [comment]
@JesusSD 

> Material2 components for Angular2 are few and unstable and seems to remain so for a long time

Material 2 is being [actively developed](https://github.com/angular/material2/pulse) but it will take time to complete them. Your could always [contribute](https://github.com/angular/material2/blob/master/CONTRIBUTING.md) to speed it along. :smile: 

> PLEASE GOOGLE: Join and integrate natively Polymer and Angular2 unifying the syntax

The projects have different goals but as Rob said, they are unified around web components so they can be used together just like Angular can be used with any other HTML elements. But I wouldn't expect them to be tightly integrated out of the box. It's not a war. There are different tools for different problems, preferences, and needs. :rose:
