### ISSUE TITLE
how to load the child component with parent component itself while routing in angular2 ?

### ISSUE THREAD

**Issue by NayabHussain** [angular/angular#9113]
problem: I have an button in parent component's html when it got clicked it will routes to child component where in its html it has one modal pop up but the target id to select that is in parent component's html 
when  we click in parent we have to click twice so the pop up gets loaded from child component's html

i want to click only ones to load the pop up....

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)
