### ISSUE TITLE
Radio button setting value false is not selectable

### ISSUE THREAD

**Issue by hupf** [angular/angular#9114]
* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**
I have two radio buttons and use ``[checked]`` and ``(click)`` to read/write the value to/from the form model (due to the issues with ``ngModel``):

```
    <input name="property1" type="radio"
           [checked]="formModel.property1"
           (click)="formModel.property1 = true">
    <input name="property1" type="radio"
           [checked]="!formModel.property1"
           (click)="formModel.property1 = false">
```

With the values ``true``and ``false``, the latter radio button is not selectable. Although it is selected if ``formModel.property1`` is initially ``false``, but when I then switch to ``true``, ``false`` is again not selectable.

It seems like the value ``false`` causes the problem, since it works with the values ``true``/``null`` or ``'foo'``/``'bar'`` for example.

**Expected/desired behavior**
It should be possible to create a radio button, that sets the value ``false`` to a property.

I've created a plunker to reproduce it:
http://plnkr.co/edit/CiGYNCgzGJNWqWClwVwt?p=preview

* **Angular version:** Tested with 2.0.0-rc.1
 
* **Browser:** Tested with Chrome 51.0 and Firefox 48.0a2
 
* **Language:** TypeScript 1.8.10

**Comment by zoechi** [comment]
This code 

    (click)="formModel.property1 = false">

is like

    (click)="setProperty2(false)"

with

    setProperty2(value: boolean) {
      this.formModel.property2 = value;
      return false; /// <== 
    }

Returning false in an event handler results in `e.preventDefault()` which causes your click to do nothing.

Without the explicit `return false` in `setProperty()` `null` is returned which doesn't result in `preventDefault()` being called.

A short form to explicitly return `true` could also be

    (click)="formModel.property1 = false;true">

As mentioned `null` works as well:

    (click)="formModel.property1 = false;null">

**Comment by hupf** [comment]
Okay, make somehow sense. Thanks.
