### ISSUE TITLE
keyValueDiffer is sensitive to key order

### ISSUE THREAD

**Issue by ghetolay** [angular/angular#9115]
* **I'm submitting a ...**
- [x ] bug report

**Current behavior**
When you re-create the object used by ngStyle, depending on the properties order, changes may not be detected.

for example with a ngStyle set as follow : 

```javascript
@Component({
    template: '<a [ngStyle]="style"></a>'
    ...
})

export class A{
    style: { ... }
}
```

Doing this may work : 

```javascript
update(){
   this.style = {
       height: '10px',
       width: '10px'
    }
}
```

while doing it like this may not : 

```javascript
update(){
   this.style = {
      width: '10px',
      height: '10px'
   }
}
```

This exact example will probably work, this is just a quick representation of the problem.
You can find a (non) working minimal example [here](http://plnkr.co/edit/fo399MunOGGn4APeU33t), file of interest is ```src/layout.ts```.

**Expected/desired behavior**
The order should not matter and ngStyle should always update all keys (if different).

* **What is the motivation / use case for changing the behavior?**
In my case the style object is returned by an external function that's why I'm re-affecting it instead of updating each properties.

* **Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.1
 
* **Browser:** Probably all but at least  Chrome & Firefox
 
* **Language:** [TypeScript 1.8]

**Comment by zoechi** [comment]
Looks weird. ChangeDetectionStrategy (default vs OnPush) doesn't make a difference.
A 2nd click makes the size of the 2nd item update as well.


AFAIK trackby should look differently

    *ngFor="let item of items" trackBy:trackItem

should be

    *ngFor="let item of items;trackBy:trackItem" 

but it doesn't make a difference with the reported issue.

**Comment by ghetolay** [comment]
Yes sorry, I just updated the plunker to make it really minimal (no ChangeDetection, no ngFor etc..).

**Comment by vicb** [comment]
Seems like it's a bug int the kv differ.

Failing tests:

```
          iit('should work regardless the key order', () => {
            let m = {a: 0, b: 0};
            differ.check(m);

            // m = {a: 1, b: 1}; -> works
            m = {b: 1, a: 1};
            differ.check(m);

            expect(differ.toString())
              .toEqual(kvChangesAsString({
                map: ['a[0->1]', 'b[0->1]'],
                previous: ['a[0->1]', 'b[0->1]'],
                changes: ['a[0->1]', 'b[0->1]']
              }));
          });
```

```
    iit('should change styles specified in an object expression',
      inject([TestComponentBuilder, AsyncTestCompleter], (tcb: TestComponentBuilder, async: any /** TODO #9100 */) => {
        var template = `<div [ngStyle]="expr"></div>`;

        tcb.overrideTemplate(TestComponent, template)
          .createAsync(TestComponent)
          .then((fixture) => {
            var expr: Map<string, any>;

            fixture.debugElement.componentInstance.expr = {
              height: '10px',
              width: '10px'
            };
            console.log('##### 1');
            fixture.detectChanges();
            let el = fixture.debugElement.children[0].nativeElement;
            expect(getDOM().getStyle(el, 'height')).toEqual('10px');
            expect(getDOM().getStyle(el, 'width')).toEqual('10px');

            fixture.debugElement.componentInstance.expr = {
              width: '5px',
              height: '5px',
            };
            console.log('##### 2');

            fixture.detectChanges();
            expect(getDOM().getStyle(el, 'height')).toEqual('5px');
            expect(getDOM().getStyle(el, 'width')).toEqual('5px');

            async.done();
          });
      }));
```
