### ISSUE TITLE
[i18n] ICU plural format - support `#` and `offset`

### ISSUE THREAD

**Issue by vicb** [angular/angular#9117]
We currently do not support `offset` nor `#`

ICU:

```
    "{num_guests, plural, offset:1 "
      "=0 {{host} does not give a party.}"
      "=1 {{host} invites {guest} to her party.}"
      "=2 {{host} invites {guest} and one other person to her party.}"
      "other {{host} invites {guest} and # other people to her party.}}}"
```

While this is not strictly required because we can use angular expression, it would be nicer for translators.

For `#` we need:
- to be able to use escaping, /ref #9286
- localize the number https://github.com/angular/angular/issues/11761

**Comment by thekip** [comment]
Moreover current interpolation syntax in ICU breaks support of ICU in most of the translation tools.

For example ICU from docs: 

```
{VAR_PLURAL, plural, =0 {just now} =1 {one minute ago} other {<x id="INTERPOLATION" equiv-text="{{minutes}}"/> minutes ago} }
```
Put it to commonly used ICU validator: https://format-message.github.io/icu-message-format-for-translators/editor.html

ICU supprot tools usually don't understand `<` symbol inside ICU, and if understand they become completele broken when they rich `}}` inside interpolation tag.

This forces users to search for tool wich is Angular-aware which greatly reduces the choice (i actually didn't find any) or just give up to full ICU syntax and edit it as simple string.

**Comment by Kamshak** [comment]
This would be incredibly nice to have, currently translation tool support for angular is not very good and this would help a lot. It's also a lot nicer to write and read in templates. 

Additionally when you look at ICU guides they very often mention the # shortcut and it was a bit suprising to me that this didn't work in Angular.
