### ISSUE TITLE
When implementing '@angular/router', I am unable to inject a service with a bootstrapped service dependency. I receive the error 'No provider for Service'

### ISSUE THREAD

**Issue by ChuckkNorris** [angular/angular#9128]
* **I'm submitting a ...**
- [x ] bug report

**Current behavior**
When implementing '@angular/router', I am unable to inject custom Service B into Service A with Service B bootstrapped in main.ts as a singleton dependency. I receive the error 'No provider for FirebaseService'. 

- After switching to '@angular/router-deprecated' it was fixed. 
- If I added Service B as a provider in the page component's decorator, it would also work. 
- By replacing Service B with Http and bootstrapped HTTP_PROVIDERS, it worked so there must be a difference between the Http service and a custom built @Injectable() service

**Expected/desired behavior**
Service B should be properly injected as a singleton into the component injected service A without needing to provide it within each component when using '@angular/router'

https://github.com/ChuckkNorris/Ng2RcTest
http://stackoverflow.com/questions/37649401/how-do-you-inject-a-custom-service-into-another-custom-service

* **What is the motivation / use case for changing the behavior?**
I cannot properly build an application with child services.

* **Please tell us about your environment:**
Visual Studio Code
* **Angular version:** 2.0.0-rc.1

**Comment by zoechi** [comment]
The SO question has an answer with a Plunker. Does that not solve your problem? The GitHub repo is way too big. You can't expect anyone to debug a whole application for you. Can you provide a Plunker that with minimal code that allows to reproduce the problem?
I'm quite sure injecting a service to another service just works (when configures correctly)

**Comment by ChuckkNorris** [comment]
Will be creating trying to reproduce the issue in Plunkr after work.

**Comment by ChuckkNorris** [comment]
False alarm - I just learned that the import statements' paths are case-sensitive. I had the folder as 'SERVICES/MyService' and I typed 'Services/MyService' not thinking anything of it.

When I was trying to root cause the problem, I swapped routers and removed the broken page from routing which led me to believe it was the router.

Everything is working correctly now with `@angular/router`.
