### ISSUE TITLE
issue for ie browser

### ISSUE THREAD

**Issue by pawankhaire** [angular/angular#9129]
Hi. i am using 
 <script src="App/scripts/controllers/Uplaod/ng-file-upload.min.js"></script>
    

its causes problem for ie browser to upload a file, the problem gets solved when i used direct post method from javasript. is there is any solution to this problem.

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)
