### ISSUE TITLE
Add facade for window.matchMedia

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#913]
[window.matchMedia](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia) is used to determine if the current window matches a given media query. Some material design components use this in order to do responsive rendering.

**Comment by mhevery** [comment]
can you tell me more about the use case? What are you planning to do with the information?

**Comment by jelbourn** [comment]
This is used to programmatically check media queries in order to use a different layout or a different behavior based on window size. The material library also has the ability to set up a callback for when the result of a query changes so that the layout of a component can change (which is just used by the grid-list component presently)

**Comment by jelbourn** [comment]
No longer needed.
