### ISSUE TITLE
Sharing a provider instance between two components in different subtrees

### ISSUE THREAD

**Issue by yjaaidi** [angular/angular#9135]
Hi !

I'm thinking about this issue.

Suppose you are using a component or different components from a cool library you found on NPM. These components might need to share a singleton of a service and you don't want all the apps or components using this library to declare the providers related to these components.

We need a way to allow different components at different places to share the same singleton.

Here is a plunker with two `Item` components using two different instances of a `Data` service because they declare `Data` in their providers but the `App` using the `Item` components is not aware of that service.

https://plnkr.co/edit/OuopKs?p=preview

In order to share the same singleton, I came up with the following design pattern.

https://plnkr.co/edit/uNrW6q?p=preview

It works and it is possible to customize the `DataFactory` in order to get the singletons by id or something.

Why do we really need this?

Imagine we have two routes `route1` and `route2` who are lazy loaded. `route1` and `route2` use a `Data` service and need to share the same instance.
We can put `Data` in the app's providers but then we loose the benefits of lazy loading as `Data` will be loaded even if we never visit `route1` and `route2`.

The idea is to declare dependencies as late a possible and still keep the same singleton.

It would be really nice to have something generic like:

```
@Component {
}
class ItemComponent {

    constructor(@InjectSingleton(Data) data: Data) {
    }

}
``` 

or 

```
@Component {
}
class ItemComponent {

    @Input dataId: string;

    constructor(private dataFactory: Factory<Data>) {}

    ngOnInit() {

        /* Get a global singleton. */
        dataFactory.getDefault();

        /* Get a singleton by id. */
        dataFactory.get(this.dataId);
    }
}
```

We can then imagine the following usage:

```
<div *ngFor="let item of itemList">
    <wt-item [dataId]="item.groupId()"></wt-item>
</div>
```

Items from the same group will share the same service.

Well this is an advanced use case but just having a global app singleton would be a nice first step.

Thank you in advance for your feedback.

**Comment by zoechi** [comment]
You can just create a single variable that contains all providers that should be made available globally like for example `HTTP_PROVIDERS` https://github.com/angular/angular/blob/f39c9c9e75671a7e235734b6b8aef263f6dff254/modules/%40angular/http/http.ts#L175 then they can be made available with a single import and `providers: [MY_PROVIDERS]` entry.

This is common even for most Angular modules.

**Comment by yjaaidi** [comment]
Of course, I already do this for my services.

But this doesn't fix my lazy loading issue. When using Webpack and lazy loaded routes, I don't want the service to be loaded until the route is loaded.

**Comment by zoechi** [comment]
The service is just a bit of code and probably won't hurt download size. You can easily design the service in a way that it doesn't download anything before some component subscribes to observables or calls a method on the service to call data.

If you put the providers on a component that is lazy loaded then it won't be initialized before the the component is loaded. If you need it outside, then the component that accesses it is not loaded lazy anyway.

**Comment by yjaaidi** [comment]
Actually, I'm thinking of a generic design pattern to lazy load global service singletons.
A service might be a bit of code but imagine a `BusinessLogic` service that needs a  `RestApi` service that needs `Http` etc... this can be a big chain of services that can represent KBs of code.

The usual use case is an app that has a "stupid" landing page that needs no services at all then while the user is browsing the app, he loads lazy routes that load the `BusinessLogic` service and keep the same singleton when the user goes to another route.

**Comment by zoechi** [comment]
As far as I know the services are instantiated when they are first injected. Sounds like an extremely complex feature for questionable benefit to me. 

It's not my call anyway. I'm not on the Angular team. I just try to get as much information as possible out of you, so when one from the Angular team checks the issue they have a full picture ;-).

**Comment by escardin** [comment]
@yjaaidi you can do this today, no special support is needed (basically use the factory provider and a classic singleton antipattern). I think it's a negative to hide your dependencies though, it goes against what everyone else is doing (making them expicit and handing control to the library consumer).

**Comment by yjaaidi** [comment]
@escardin ???
I think it's exactly the opposit. I'm trying to make the dependencies more explicit.

Suppose you have a Wishlist app which is using two different components `WishList` and `WishDetail`.
Both need the singleton of the `WishStore` service.

Imagine this real life scenario:

Day 1:
I write the `WishList` component and `WishStore` service and I of course I naively add `WishStore` in `WishList` providers.

Day 2:
Another developer writes the `WishDetail` component and adds `WishStore` service in `WishDetail` providers...
Bouh... components work but the app doesn't as the two components are not sharing the same instance of `WishStore`.
To fix this, here's what he does:
- He discovers that `WishDetail` and `WishList` are both used in the parent `WishListManager` component.
- He removes `WishStore` dependency from `WishList` and `WishDetail`.
- He adds `WishStore` dependency to the `WishListManager` component.

It works!

Day 3:
We write the `Admin` component which needs `WishList` component.
A naive developer would add the `WishStore` to the `Admin` component's dependencies but then we'll have another instance of `WishStore` for the `Admin` component and we don't want that.
A smarter developer would add the `WishStore` to the `App` dependencies...

So, there are two solutions for every shareable service we use.
1 - We add it as an app dependency which is ugly as we'll end up with all services loaded by the app without knowing which components are using them... and maybe they are not used anymore.
2 - We add them to the highest common parent component but this can change regularly so we'll be refactoring all the time.

What I want is to declare `WishStore` as a direct dependency of `WishDetail` and `WishList` but still share the same instance.

Here are the advantages of this approach:

1 - Dependencies are explicit, I can see that `WishStore` is a dependency of `WishDetail` and `WishStore`.
2 - Nobody can break my app by shadowing my `App`'s `WishStore` dependency.
3 - The day, developer 1 removes `WishStore` from `WishDetail` and developer 2 removes `WishStore` from `WishList`, `WishStore` won't be loaded anymore. 
4 - If `WishDetail` and `WishList` are loaded lazily, `WishStore` won't be loaded until `WishDetail` or `WishList` are loaded.


Otherwise, we'll end up with same issues as AngularJS... In one year, all our apps will have hundreds of dependencies on the root component or bootstrap and we'll load tons of useless code if don't cleanup manually.

Meanwhile, the design pattern I'm encouraging people to put the list of providers in static property of each component and it would look like this:

```
@Component({
  providers: [WishListManager.PROVIDERS, Admin.PROVIDERS]
})
class AppComponent {}

class WishListManager {
  static PROVIDERS = [WishList.PROVIDERS, WishDetail.PROVIDERS]
}

class Admin {
  static PROVIDERS = [WishList.PROVIDERS, WishDetail.PROVIDERS]
}

class WishList {
  static PROVIDERS = [WishStore]
}

class WishDetail {
  static PROVIDERS = [WishStore]
}
```

Problem with this solution:
Suppose that `Admin` component is a lazy loaded route. By Importing `Admin` because I need `Admin.PROVIDERS`, I will lose the benefits of lazy loading.

This is really a common issue.
Have a look at @vsavkin's router@3.0.0 plunker: http://plnkr.co/edit/ER0tf8fpGHZiuVWB7Q07?p=preview

`AppComponent` has `HeroService` in it's dependencies while `HeroService` is a private matter of `HeroListComponent` and `HeroDetailComponent`. So even if these components are loaded lazily, `HeroService` will be loaded no matter what.
Plus, if we decide to remove these components, nobody will (and has) to think about removing `HeroService` from `AppComponen`.

Now look at `AppComponent` again, where is `CrisisService` dependency declared? You'll have to browse the component tree logic to find out it's declared as a dependency of `CrisisCenter` and what if you want to reuse `CrisisDetail` in another component... well you'll have to refactor and move `CrisisService` to `AppComponent`.

Can anyone validate this issue or tell us how one can handle this in a big app with hundreds of services without loosing benefits of lazy loading.

I feel so alone with this issue :)

**Comment by escardin** [comment]
> 1 - Dependencies are explicit, I can see that WishStore is a dependency of WishDetail and WishStore.

They're explicit in the constructor (which is where they're declared as dependencies, where they're provided is a distinct step, and separate from making deps explicit)

>2 - Nobody can break my app by shadowing my App's WishStore dependency.

Nobody can have two copies of WishStore now either, since we're dealing with YAGNI hypotheticals.

>3 - The day, developer 1 removes WishStore from WishDetail and developer 2 removes WishStore from WishList, WishStore won't be loaded anymore. 

This doesn't have any bearing on having a global instance or not.

>4 - If WishDetail and WishList are loaded lazily, WishStore won't be loaded until WishDetail or WishList are loaded.

I doubt your wishStore is so big that you can't afford the bytes on bootstrap, but even if that's the case, you can use `useFactory` to fetch it async when it's first instantiated (which is when a component that depends on it is instantiated)

>AppComponent has HeroService in it's dependencies

Nope, it's in its PROVIDERS, which are not it's dependencies. It won't even be instantiated until something actually uses it. This is comparable to factory and configuration classes in Spring, if you're familiar with that.

>Plus, if we decide to remove these components, nobody will (and has) to think about removing HeroService from AppComponen.

If you delete the classes, then next time you compile you'll get an error. If you don't delete the service, then it's either still in use, or you have dead code, even if it's not loaded.


>Now look at AppComponent again, where is CrisisService dependency declared? You'll have to browse the component tree logic to find out it's declared as a dependency of CrisisCenter and what if you want to reuse CrisisDetail in another component... well you'll have to refactor and move CrisisService to AppComponent.

That refactoring sounds like a good thing to me, you kept your app component small, until it needed to be bigger.

>Meanwhile, the design pattern I'm encouraging people to put the list of providers in static property of each component and it would look like this:

IMO this is the right direction, but you need to put them in their own file, so you're not loading the component file. Also, you could just `export HERO_PROVIDERS=[HeroService,VillanService]` instead of declaring a class with a static field.

Also, if you want to do EXACTLY as you requested, use the singleton antipattern and then use the useFactory provider method to call it's getInstance() (or equivalent).

**Comment by yjaaidi** [comment]
The problem here is that I'm a angular trainer and coach and I try to find the best patterns to avoid beginners mistakes I meet every day...

>Nobody can have two copies of WishStore now either, since we're dealing with YAGNI hypotheticals.

? Look at victor's plunker. A beginner trying to use the `CrisisDetail` component outside the `CrisisCenter` will have an error as `CrisisService` is not provided, do you agree?
If he puts `CrisisService` in his `AdminComponent` or something, he'll end up with two instances? Agreed?
If he puts it in the `App` components, it will end up with two instances as `CrisisCenter` has an instance shadowing the one from the `App`. 

> 3 - The day, developer 1 removes WishStore from WishDetail and developer 2 removes WishStore from WishList, WishStore won't be loaded anymore.
> This doesn't have any bearing on having a global instance or not.

Of course it does as the service is declared in the nearest component's providers which will more luckily be refactored by the developper instead of having to crawl the whole app and see which component is handling the singleton and if other components need it.

> 4 - If WishDetail and WishList are loaded lazily, WishStore won't be loaded until WishDetail or WishList are loaded.
> I doubt your wishStore is so big that you can't afford the bytes on bootstrap, but even if that's the case, you can use useFactory to fetch it async when it's first instantiated (which is when a component that depends on it is instantiated)

I'm not worried about one service's size but about the cumulative size of all services + their dependencies.
Think about this app where the landing page is almost empty but the admin route needs API Client / Analytics / Dashboard libraries etc.... This can go big...

> AppComponent has HeroService in it's dependencies
> Nope, it's in its PROVIDERS, which are not it's dependencies. It won't even be instantiated until something actually uses it. This is comparable to factory and configuration classes in Spring, if you're familiar with that.

Sorry, I'm not talking about Angular dependencies but webpack. What I mean by this is that loading `AppComponent`'s file will also load `HeroService's` file...

> Plus, if we decide to remove these components, nobody will (and has) to think about removing HeroService from AppComponen.
> If you delete the classes, then next time you compile you'll get an error. If you don't delete the service, then it's either still in use, or you have dead code, even if it's not loaded.

Great example! Do you have a tool that can detect your dead code while `HeroService` is still in `AppComponent`'s providers?
With the singleton pattern or at least if each component/service exports it's providers, any IDE will see that `HeroService` is not used anymore if `HeroDetail` and `HeroList` are removed.

> Now look at AppComponent again, where is CrisisService dependency declared? You'll have to browse the component tree logic to find out it's declared as a dependency of CrisisCenter and what if you want to reuse CrisisDetail in another component... well you'll have to refactor and move CrisisService to AppComponent.
> That refactoring sounds like a good thing to me, you kept your app component small, until it needed to be bigger.

With the singleton or the providers export design pattern, no refactoring is needed.

> Meanwhile, the design pattern I'm encouraging people to put the list of providers in static property of each component and it would look like this:
> IMO this is the right direction, but you need to put them in their own file, so you're not loading the component file. Also, you could just export HERO_PROVIDERS=[HeroService,VillanService] instead of declaring a class with a static field.

The idea behind the PROVIDERS static property is to make it easier for developers. Let's say you want to use `HeroService`, you auto-import with your favorite IDE and you get the providers in `HeroService.PROVIDERS`... with an independent variable, let's say you don't know much about the app and just want to use `VillanService`, how would you guess that the providers are in `HERO_PROVIDERS` etc...

> Also, if you want to do EXACTLY as you requested, use the singleton antipattern and then use the useFactory provider method to call it's getInstance() (or equivalent).

Yup, thank you for your time ;)

By the way, the more I read this conversation, the more I think that this it should be entitled "Stateless vs Stateful Services".

Let's forget about the Lazy Loading now.

Concerning the Stateless Services, we don't care about having multiple instances so we should put them in the nearest component's providers.

Stateful Services will have to be global singletons most of the time like `UserCurrent`, `ShoppingCart`.
It would be really cool to have a way (a `@Singleton` decorator) to prevent Angular from shadowing them?
Beginners will and do simply add `UserCurrent` to their component's providers. It should trigger an error instead of failing silently by creating another instance and having strange behaviour.

**Comment by escardin** [comment]
As a trainer, you should be teaching them how the rest of the community makes and uses modules, even if it seems awkward. 

The whole problem with the Singleton pattern is that it's a global without being explicitly declared global. If they're global services and you're not worried about lazy loading, then they SHOULD be in the bootstrap or app component, because then it's clear they're global. 

By only providing them in the components that need them and getting the same instance, you're muddying the behaviour of the DI system and making it hard for users to know what to expect. 

New users of NG2 do make the mistake of providing all the time more than they should (It's a relatively common question on the angular gitter). It sucks that the multiple pages of documentation and cookbooks on DI didn't sink in, but then they learn the general rule that 'every time you provide, you get a new instance' and they're set.

You may wish to read these:
http://misko.hevery.com/2008/08/17/singletons-are-pathological-liars/
http://misko.hevery.com/2008/08/21/where-have-all-the-singletons-gone/
http://misko.hevery.com/2008/08/25/root-cause-of-singletons/

**Comment by yjaaidi** [comment]
I agree !

I've been preaching explicit coding for a while now + explicit class usages with AngularJS since the beginning etc... 

Now the problem is that first I'm always trying to teach people how to be developers and not simple coders but most of them just code & fix. 
In addition to this beginners are focused on the syntax, async logic etc... and we add DI to this. So, the whole point here is that I am looking for a simple generic design pattern that works for most cases.

The easiest design pattern I could come up with for the moment is the following rule:
1 - Every service/component should expose a static PROVIDERS property with the list of dependencies including : itself and direct dependencies PROVIDERS property.
2 - Only the root component or bootstrap function should declare providers.
3 - If any component uses the PROVIDERS property it should be justified for each entry.

And more advanced users can use this pattern only for stateful services.

But still, don't you agree for a decorator that avoids shadowing? It's error prone otherwise.

Plus, the problem is hard to detect because unit-tests will not detect it and we can only count on e2e tests for this.

**Comment by escardin** [comment]
No, I don't agree. It might be 'simpler' now, but I think it leads to confusion later. A lot of the trouble with picking up Angular 1 is how magical it is. Angular 2 avoids a lot of that by being explicit. 

If you have an annotation that configures the injector somewhere other than `providers`, then people are going to start guessing at what the right thing to do in a situation is. Adding a `@global` annotation will mean another place to look, and another set of behaviours to remember. You don't want to give people a lot to remember, because they won't.

I do think Angular 2 is a relatively tall hill to climb, especially for beginners. Consistent behaviour and expectations makes things smoother. That said, the docs do a really good job of smoothing that out, even for JS beginners.

**Comment by yjaaidi** [comment]
I'm not talking about a `@global` decorator.

Just one that prevents shadowing `@NoOverride` that triggers an explicit error:
'_UserStore is flagged `NoOverride` and it has been loaded by `AppComponent` and it's child `UserDetailComponent`, remove it from `UserDetailComponent`'s providers to use the instance from `AppComponent`'_

**Comment by Delagen** [comment]
I solved this problem with source of RouterModule implementing forRoot static method returning module with providers

**Comment by yjaaidi** [comment]
Hi @Delagen, this sounds tricky. Do you have a plunker?
Thanks

**Comment by Delagen** [comment]
@yjaaidi No i wrote internal project, so you can import NgModule with needed providers into tree where you need single instance (i my project it global so i used OwnNgModule.forRoot() only for root NgModule) but for others i simply import simple OwnNgModule. So if in some tree component you wish to create own provider you import OwnNgModule.forRoot() or something else for override it.
But yes it propagate to tree.
Example of module
```
@NgModule({
			 .... without providers or providers without singleton
		  })
export class OwnNgModule {
	static forRoot(): ModuleWithProviders {
		return {
			ngModule:  OwnNgModule ,
			providers: [.......]
		};
	}

	static forChild(): ModuleWithProviders {
		return {
			ngModule:  OwnNgModule 
		};
	}
}
```

for root NGModule use `imports:[OwnNgModule.forRoot()]`
for child modules you can use simple: `imports:[OwnNgModule]`

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
