### ISSUE TITLE
Location, LocationStrategy, HashLocationStrategy... disappeared from angular2/router package

### ISSUE THREAD

**Issue by rodrigozc** [angular/angular#9137]
* **I'm submitting a ...**
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**
My application was broken because classes LocationStrategy, HashLocationStrategy, PathLocationStrategy, APP_BASE_HREF and Location disappeared from angular2/router.
I found these classes in source folder src/platform/browser/location, but the router package do not export anyone.

**Expected/desired behavior**
Classes LocationStrategy, HashLocationStrategy, PathLocationStrategy, APP_BASE_HREF and Location available in angular2/router package.

* **Please tell us about your environment:**
I'm using npm 2.15.5 to install and manage dependencies.

* **Angular version:** 2.0.0-beta.7 
 
* **Browser:** [all] 
 
* **Language:** [ TypeScript ]

**Comment by ericmartinezr** [comment]
See the changelog for beta 16 https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes-1

**Comment by pkozlowski-opensource** [comment]
Thnx @ericmartinezr !

**Comment by rodrigozc** [comment]
Thanks @ericmartinezr, I will remember to look for changelog before any questions... ;-)
