### ISSUE TITLE
Properly model querystring input which can contain multiple values

### ISSUE THREAD

**Issue by xealot** [angular/angular#9138]
**I'm submitting a ...**
- [x] bug report
- [x] feature request

**Current behavior**

In the old router, the new router and the very new router querystring parameters always are accessible as `{[k:string]:string}`. To pass an array of values via the querystring we have to rely on encoding within the application to serialize and then deserialize the array. We *should* be able to simply rely on existing URL standard behavior.

Adding to my frustration, there is already a class, `URLSearchParams` that fully models the querystring but seems unused when retrieving url search params from the router.
https://angular.io/docs/ts/latest/api/http/URLSearchParams-class.html

**Expected/desired behavior**

When retrieving data parsed from a querystring it should be presented either in a datastructure that supports the standard or in a class that models it properly.

```typescript
const q: Observable<URLSearchParams> = r.routerState.queryParams;
```

```typescript
const q: Observable<{[k:string]:string[]}> = r.routerState.queryParams;
```

My vote is for the URLSearchParams version of course.

**Comment by xealot** [comment]
Cross posted to https://github.com/angular/vladivostok/issues/35

**Comment by pkozlowski-opensource** [comment]
There is no point of duplicating it here if it was reported in  angular/vladivostok#35 where the new router lives.
