### ISSUE TITLE
Heroes tutorial toh-pt1.html does not mention to add platform_directives to pubspec.yaml

### ISSUE THREAD

**Issue by sturmf** [angular/angular#9139]
* **I'm submitting a because for a beginner it is not obvious if you add ngModel that you need to add platform_directives to the pubspec.yaml**
- [x ] bug report

**Expected/desired behavior**
Info in the tutorial step about this

Forgot to add that I am doing the Angular2-Dart heroes tutorial.

**Comment by ericmartinezr** [comment]
Hey @sturmf would you mind to open this issue in the website's repo https://github.com/angular/angular.io (there is where they track issues related to the tutorial/website in general) ?

**Comment by pkozlowski-opensource** [comment]
Thnx @ericmartinezr !

**Comment by sturmf** [comment]
Sorry I'll do this, and I reported this here since at the bottom of the docu is a link which points to this github repo to report issues :-)
