### ISSUE TITLE
Throw error when template declared but no Viewport directive match

### ISSUE THREAD

**Issue by mhevery** [angular/angular#914]
```
@Component()
@Template({
  inline: '<div *if="exp"></div><span template="if: exp"></span><template if="exp"></template>',
  directives: []
})
class SomeComponent{}
```

The above code should throw an error during compilation. This is because each of the sub-template syntaxes ref to a directive but no Viewport directive was matched.

In general it should be an error to have sub-template without a Viewport

**Comment by gdi2290** [comment]
+1

**Comment by pkozlowski-opensource** [comment]
@mhevery what is the version you've tested with? As I think that we do have checks for this already, [see those tests](https://github.com/angular/angular/blob/da4862a0c82866e117ee3727f80b205c00da0710/modules/angular2/test/core/compiler/integration_spec.js#L548-L570 ). 

Or is it a different condition / different error that you are looking for?

**Comment by mhevery** [comment]
Must have been an old version. Closing
