### ISSUE TITLE
How to override multiple providers in TestComponentBuilder 

### ISSUE THREAD

**Issue by pgarge** [angular/angular#9142]
I have tried this, it only takes the first one:

```
 .overrideProviders(LongProfile, [provide(AppService, { useClass: MockAppService }),provide(ProfileService, { useClass: MockProfService }),provide(AppService1, { useClass: MockAppService1 })])
```

Is this a bug?

**Comment by zoechi** [comment]
dup of #7397

**Comment by ndcunningham** [comment]
Have the same issue

`Failed: No provider for QuestionServiceMock!`

`  
tcb.overrideProviders(QuestionTextComponent,
        [
          ROUTER_PROVIDERS,
          provide(Location, {useClass: SpyLocation}),
          provide(ROUTER_PRIMARY_COMPONENT, {useValue: WizardComponent}),
          provide(Router, {useClass: RootRouter}),
          provide(QuestionService, {useClass: QuestionServiceMock})
]
`

`Error: No provider for Router! (line 776)`

Using beforeEachProviders somehow conflicts with another test file that has beforeEachProviders.

I know this is true because if i delete that test file or remove it from the runner and run the test again it works fine.
So I have to override each and every `it` in order to make my test 'work'

**Comment by zoechi** [comment]
@ndcunningham There were lots of changes. What Angular2 version are you using? Can you provide a Plunker to reproduce?

**Comment by ndcunningham** [comment]
@zoechi 
Angular RC1
router-deprecated

basically the seed project from @mgechev 
where i just switched from RC router (v2) to deprecated to match my current project structure.

**Comment by zoechi** [comment]
And Plunker?

**Comment by ndcunningham** [comment]
Will have to create an update since my Main (app component) route tree has a child route which has it's own route tree.

Might give results which are not correlating to my own if not reflected.

**Comment by zoechi** [comment]
The bug report is not actionable when there are no exact steps to reproduce the problem.

**Comment by ndcunningham** [comment]
[Partial Plunk](http://plnkr.co/edit/qW96v1jkGscomYXlIRl0)

It's takes a lot to recreate it that's why i couldn't give it to you right away. 
Additionally, I thought it was already known and i was just adding information to the issue...

**Comment by DzmitryShylovich** [comment]
TestComponentBuilder is obsolete.
@pkozlowski-opensource close?

**Comment by pkozlowski-opensource** [comment]
> TestComponentBuilder is obsolete.

It is indeed...
