### ISSUE TITLE
Get error 'Cannot resolve all parameters...' when injecting custom service into another service

### ISSUE THREAD

**Issue by dwasyluk** [angular/angular#9144]
When attempting to access a custom injectable service from within another custom injectable service, getting the error:

`Cannot resolve all parameters for ApiService(undefined). Make sure they all have valid type or annotations.`

**Plunkr example:** http://plnkr.co/edit/wFodvyvIWHD6OSNcICJx

All annotations are correct per the Angular documentation as far as I can tell- is this a bug?

**Comment by ericmartinezr** [comment]
You're using a really old beta, really old, and no, it is not a bug. Anyway, your answer is here http://blog.thoughtram.io/angular/2015/09/17/resolve-service-dependencies-in-angular-2.html and here http://blog.thoughtram.io/angular/2015/09/03/forward-references-in-angular-2.html

**Comment by dwasyluk** [comment]
I've updated the plunkr to use the latest beta (9), unfortunately I get the same error. I've read the two linked articles but I'm still unclear on what's incorrect regarding the linked plunkr as its following the articles examples.

**Comment by ericmartinezr** [comment]
```
export class ApiService {
  constructor(testService:TestService) {}
}

export class TestService {
  constructor(apiService:ApiService) {}
}

```

ApiService is trying to inject a class that doesn't exist yet, which is explained in the second article. 

@dwasyluk please consider asking your questions in gitter's chatroom or stackoverflow. The repository is really for reporting bugs and issues with the framework. We will be more than willing to help you with your questions :+1:

**Comment by dwasyluk** [comment]
Awesome thanks very much for the pinpoint explanation and sample code :) really appreciate it. Didn't even know about the gitter chatroom I'll jump in there and close this issue so the team doesn't burn time on it 👍
