### ISSUE TITLE
Directive that extends from DefaultValueAccessor applies to all controls instead of respecting the selector. Host's events not being trigerred

### ISSUE THREAD

**Issue by daniel-a-melo** [angular/angular#9146]
* **I'm submitting a ...**
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**

I am implementing masked input for text boxes. With ng1 I used to implement using ngModelController's `$parsers` and `$formatters`. An example implementation can be found at https://plnkr.co/HQSyZkr4VgezzcSNWnuJ (ng1) . On this example the input displays uppercase text and stores (via ngModel) lowercase text.

I managed to replicate the same behavior using `DefaultValueAccessor` as in in the following snippet (based on code posted on example posted on other issue). This code **works** on beta 17 but **doesn't work** on RC1.  Obviously the beta 17 version differs on the import statements.

The code samples for beta 17 and RC 1 may be found here:

https://plnkr.co/yDvm2x3YiKY6LKhRSzQ3 (Beta 17 - It works)
http://plnkr.co/eAEML8VTnvNo78IFGgSB (RC1 - It doesn't work)

With RC1 the directive applies to all input controls in the form instead of respecting the selector `input[type=uppercase]`. Futhermore the `input` event is never triggered and nor the method `writeValue`

```typescript
import {Directive, Provider, forwardRef, Renderer, ElementRef} from '@angular/core';
import {DefaultValueAccessor, NG_VALUE_ACCESSOR, NG_VALIDATORS, Validator, Control} from '@angular/common';

const FORMAT_CPF_VALUE_ACCESSOR = new Provider(NG_VALUE_ACCESSOR, {
    useExisting: forwardRef(() => UpperCaseValueAccessor),
    multi: true
});

@Directive({
    selector: 'input[type=uppercase]',
    host: {
        "maxlength": "14",
        "minlength": "14",
        "min": "0",
        "type": "text",
        "(input)": "input($event.target.value)",
        "(blur)": "blur()"
    },
    bindings: [FORMAT_CPF_VALUE_ACCESSOR]
})
export class UpperCaseValueAccessor  extends DefaultValueAccessor  {

    constructor(renderer: Renderer, elementRef: ElementRef) {
        elementRef.nativeElement.style.backgroundColor = 'yellow';
        super(renderer, elementRef);
    }

    ngAfterViewInit() { }

    blur() {
        this.onTouched();
    }
    
    input(value : string) {
        // Write back to model
        if (value) {
            value = value.toLowerCase();
            //write formatted to to control view
            (<any>this)._elementRef.nativeElement.value = value.toUpperCase();
        }
        this.onChange(value);
    }

    writeValue(value: any): void {
        // Write to view
        if (value) {
            value = value.toUpperCase();
        }
        super.writeValue(value);
    }
}
```
The code for component using the directive : 

```typescript
import {Component} from '@angular/core';
import {ControlGroup, Control, FormBuilder, Validators} from '@angular/common';
import {UpperCaseValueAccessor} from './uppercase-directive';

interface FormData {
    name : string;
    uppercaseText: string;
}

@Component({
  selector: 'my-app',
  providers: [],
  template: `
        <form [ngFormModel]="dataForm">
            <label for="inputName">Name</label>
            <input type="text" [(ngModel)]="data.name" [ngFormControl]="dataForm.controls.name" id="inputName" placeholder="Name">
            <div [hidden]="dataForm.controls.name.valid || dataForm.controls.name.pristine" class="alert alert-danger">Name is required</div>

            <p></p>

            <label for="upperText">Uppercase text</label>
            <input type="uppercase" [(ngModel)]="data.uppercaseText" [ngFormControl]="dataForm.controls.uppercaseText" id="upperText" placeholder="Something">

            <p></p>

             <button [disabled]="!dataForm.valid" (click)="submitForm()">Submit</button>
             <button (click)="resetForm()">Reset</button>

             <p></p>

             <pre>{{data | json}}</pre>
        </form>
  `,
  directives : [UpperCaseValueAccessor],
})
export class App {
    dataForm : ControlGroup; 
    data : FormData = <FormData> {};
    
    constructor(private fb : FormBuilder) {
        this.buildForm();
    }
    
    buildForm() {
        this.dataForm = this.fb.group({
            name : ['', Validators.required],
            uppercaseText : ['']
        });
    }
    
    submitForm() {
        console.log(this.dataForm.value);
    }
    
    resetForm() {
        this.buildForm();
    }
}
```

**Expected/desired behavior**

https://plnkr.co/yDvm2x3YiKY6LKhRSzQ3 (Beta 17 - It works)
http://plnkr.co/eAEML8VTnvNo78IFGgSB (RC1 - It doesn't work)

* **What is the expected behavior?**

The directive would apply only to componenet specified in the selector `input[type=uppercase]`, the event `input` would be triggered and the method `writeValue` would be invoked.

* **Please tell us about your environment:**

* **Angular version:** 2.0.0-RC.1 
 
* **Browser:** [Chrome 51] 
 
* **Language:** [all | TypeScript 1.8.10]

**Comment by Dinistro** [comment]
I can confirm, that this is still the case in rc.3. Is there any progress?

**Comment by Dinistro** [comment]
@daniel-a-melo After long researches I found out, that this is a bigger bug than I expected. The problem here is, that the `@Directive`-Decorator is not able to add the right metadata to a `CustomValueAccessor
`. 
This problem can be found in other cases, where one extends a angular class and the metadata is not changed. 

There are multiple issues that are based on this bug: #9758 #8925 #8777

**Comment by Celebes** [comment]
Still appears in rc.4

**Comment by zouabimourad** [comment]
I have  the same problem with RC4

**Comment by stalniy** [comment]
Just override `decorators` property. Works for me
```js
@Component({
  template,
  selector: 'file-upload-area',
  directives: [FileUpload, FileDropArea, PreviewFiles],
  providers: [VALUE_ACCESSOR],
})
export class FileUploadArea extends DefaultValueAccessor {
  @Input() max = 100
  value = []

  // TODO: this is a hack which allows use DefaultValueAccessor as parent
  // can be removed when https://github.com/angular/angular/issues/9146 is fixed
  static decorators = null
......
```

**Comment by pkozlowski-opensource** [comment]
The intention is that you _implement_ a custom `ControlValueAccessor` instead of extending an existing one. Here is a plunk demonstrating this for your use-case: https://plnkr.co/edit/L9BkYaLUuHiBFClZxOwk?p=preview

**Comment by guikubivan** [comment]
@pkozlowski-opensource Your plunker seems to be broken, just says "loading..."
