### ISSUE TITLE
Old router: wrong component reload using browser navigation and nested routerconfig

### ISSUE THREAD

**Issue by CaselIT** [angular/angular#9147]
* **I'm submitting a ...**
- [x] bug report

**Current behavior**
In the deprecated beta router when using more than two nested routerConfig the router reloads components that should not reload when navigating with the browser hystory to a link that has parameters.
http://plnkr.co/edit/M59i8zB4BOsWpkLtHVMl?p=preview
In the example there are two nested routeConfig `AppComponent -> First -> Second`
`Second` defines the route to two components. The link `"route to a|b"` use `[routerLink]` to navigate, while the buttons use history back or forward.
The counter is the number of times `Second` was created. It should stay at zero since I'm moving among its child routes.
The bug:
* click Route to B
* click History back
* click History forward -> the counter changes to 1
* click History back -> the counter changes to 2
* ect

Using only route to B and route to A the component `Second` is not reloaded as expected.

**Expected/desired behavior**
To not reload the component `Second` as when using only one nested route or not adding parameters to the routes. 
By changing the code to bypass component First both `[routerLink]` and history have the same correct behaviour:
```ts
@RouteConfig([
  //{ path: '/first/...', name: 'First', component: First, useAsDefault: true }
   { path: '/second/...', name: 'Second', component: Second, useAsDefault: true }
])
export class AppComponent {}
```

* **Angular version:** 2.0.0-rc1 
 
* **Browser:** [Chrome 52 | Firefox 48 | Edge ] 
 
* **Language:** [TypeScript 1.8]

**Comment by zoechi** [comment]
You can implement `CanReuse` to avoid that http://plnkr.co/edit/AMvCS1kg76YrMQGkaksS?p=preview

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by CaselIT** [comment]
Thanks, I did not find it in the documentation. I'll look into it.
Still it's quite strange that the router behavior changes according to the number of nested routeConfig.

**Comment by CaselIT** [comment]
Closing this since it's related to the deprecated router
