### ISSUE TITLE
'readonly' keyword not recognized in .d.ts files

### ISSUE THREAD

**Issue by LaurentVandenbosch** [angular/angular#9156]
Hello there,

I am having some difficulties to make angular2 work properly in Visual studio. I cannot compile the typescript files because the 'readonly' keyword  is not recognized. Example: ng_for.d.ts.

As far as I know this feature will only be available in Typescript 2.0 which is not released yet.

Am I doing something wrong?

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by antonybudianto** [comment]
I've reported it [here](https://github.com/angular/vladivostok/issues/39)

**Comment by LaurentVandenbosch** [comment]
@zoechi Sorry about that, i wasn't sure if it was a bug or just me not doing the right thing.

@antonybudianto Thank you for the propre report format, I'll follow this issue ;-)

**Comment by zoechi** [comment]
@LaurentVandenbosch Please check with the channels mentioned in the link above first when in doubt. The post doesn't contain enough information to know what the issue is about. For a proper bug report it would need exact steps how to reproduce (or a Plunker that allows to reproduce)
