### ISSUE TITLE
new alpha.3 router type definition error...

### ISSUE THREAD

**Issue by born2net** [angular/angular#9157]
With the new router alpha.3 I am getting the following error:

![err](https://cloud.githubusercontent.com/assets/5090936/15985817/59595ae6-2fae-11e6-8afb-648dbd465313.PNG)

any fix? 

and if you wish to see, or use the new router I created a forkable project at:
https://github.com/born2net/ng2-minimal

regards

Sean

**Comment by ericmartinezr** [comment]
@born2net the new new new router lives here https://github.com/angular/vladivostok/issues and you have to install TS nightly. See https://github.com/angular/vladivostok/issues/39

**Comment by born2net** [comment]
tx Eric, will check asap, and closing...

**Comment by born2net** [comment]
fyi fixed via:
```npm install typescript@next --save```
tx again
