### ISSUE TITLE
Sourcemap stopped working

### ISSUE THREAD

**Issue by justme1** [angular/angular#9161]
* **I'm submitting a ...**
- [V ] bug report

**Current behavior**
While debugging my Angular2 application sourcemap doesn't work properly. 

**Expected/desired behavior**
When putting breakpoint/debugger point relevant .ts file should be opened in Chorme. However, I'm displayed with a different file with wrong breakpoint line & file.

* **What is the expected behavior?**
When putting breakpoint/debugger point relevant .ts file should be opened in Chorme.

* **What is the motivation / use case for changing the behavior?**
I think this has started to happen once I upgraded project to rc1.

* **Please tell us about your environment:**
Mac OS X. 
* **Angular version:** 2.0.0-beta.X 
 Angular 2.0 rc 1.
Webpack-dev-server.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web 

Chrome.

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart] 
TypeScript.

**Comment by zoechi** [comment]
How can this be reproduced? Are source map files created? Did you enable source maps to be loaded by Chrome?

**Comment by justme1** [comment]
Hi zoechi,

I can set up a demo project, but first I'd prefer to add some more details before creating such project.

First I want to better explain with images what I'm currently experiencing. Sourcemaps are created - I have a dedicated directory which all the javascript/sourcemaps are created (using outdir option in tsconfig.json). And yes sourcempas are loaded by Chrome.

In addition to that it seems that Chrome is able to show the right files only for the following files:
vendor.ts, boot.ts, app.component.ts.

<img width="1023" alt="screen shot 2016-06-12 at 4 54 19 pm" src="https://cloud.githubusercontent.com/assets/3663294/15991570/f3dca7c4-30be-11e6-8ed6-98f15042cd04.png">


However, all the rest of the files I see incorrect files. For example, in the following picture I opened the auth.service.ts file but it's actually display another file which isn't the correct file:

<img width="1023" alt="screen shot 2016-06-12 at 4 54 19 pm" src="https://cloud.githubusercontent.com/assets/3663294/15991579/31fcb18e-30bf-11e6-9a59-4bb1cf7f1251.png">

What may cause some files to correctly be identified with sourcemaps, but not others?

In addition would you like me to add more details before uploading a demo project?

Thanks!

**Comment by zoechi** [comment]
This looks more like a tools or project setup issue and not an Angular issue. You should first check with [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)
