### ISSUE TITLE
Typescript definition files should be generated with the latest stable version of typescript rather than the dev version

### ISSUE THREAD

**Issue by LaurentVandenbosch** [angular/angular#9162]
**I'm submitting a bug report**

**Current behavior**
The typescript definition files are generated using the dev version of typescript (**1.9.0-dev.20160409**). The definition then contains keywords like "readonly" not supported by the latest stable version (**1.8.10**). This basically makes angular2 unusable in Visual studio (or at least not conveniently) and probably other IDE aswell.

**Expected/desired behavior**
The definition files should be generated using the latest stable version (**1.8.10**) so it can be compatible with all IDE.

* **Angular version:** 2.0.0-rc-1

**Comment by naveedahmed1** [comment]
I hope they can consider this suggestion in RC 2. The new router looks promising but dependency on nightly builds of TypeScript is stopping us from trying it.

**Comment by IgorMinar** [comment]
We ensure compatibility with the latest stable version via d.ts file transformations and tests.   Angular 2.0.x we guarantee compatibility with TS 1.8. If there is something in our d.ts files that doesn't work with typescript 1.8 please file a new issue and provide steps to reproduce the problem. thanks!
