### ISSUE TITLE
host in Directive 

### ISSUE THREAD

**Issue by AmmarMohamed** [angular/angular#9169]
import {Directive , ElementRef , Renderer } from 'angular2/core'; 

@Directive({
    selector:'[autoGrow]',
     inputs: [
    'text: autoGrow'
  ],
    host:{
        '(focus)':'onFocus()',
        '(blur)':'onBlur()'
    }
})

export class AutoGrowDirective {

    constructor  (private el:ElementRef  ,private renderer : Renderer){
        
    }
    onfocus(){
      this.renderer.setElementStyle(this.el.nativeElement , 'width', '200');
    }

    onblur(){
        this.renderer.setElementStyle(this.el.nativeElement , 'width','120');

    }
    
} 

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
import {Component} from 'angular2/core';
import {AutoGrowDirective} from './auto-grow.directive';

@Component({
    selector: 'courses',
    template: `
    <h1>
    Courses Angular2 
   </h1>
  
  First name:<br>
  <input   autoGrow /><br>
  
   
   `,
   
    directives:[AutoGrowDirective]
})

export class couresesComponent {
   
}

 EXCEPTION: Error during evaluation of "focus"BrowserDomAdapter.logError 
angular2.dev.js:23083 ORIGINAL EXCEPTION: TypeError: this.directive_0_0.onFocus is not a functionBrowserDomAdapter.logError @ angular2.dev.js:23083ExceptionHandler.call @ angular2.dev.js:1194(anonymous function) @ angular2.dev.js:12591NgZone._notifyOnError @ angular2.dev.js:13635onError @ angular2.dev.js:13539Zone.run @ angular2-polyfills.js:1247(anonymous function) @ angular2.dev.js:13558NgZone.run @ angular2.dev.js:13520outsideHandler @ angular2.dev.js:13355Zone.run @ angular2-polyfills.js:1243zoneBoundFn @ angular2-polyfills.js:1220
angular2.dev.js:23083 ORIGINAL STACKTRACE:BrowserDomAdapter.logError @ angular2.dev.js:23083ExceptionHandler.call @ angular2.dev.js:1197(anonymous function) @ angular2.dev.js:12591NgZone._notifyOnError @ angular2.dev.js:13635onError @ angular2.dev.js:13539Zone.run @ angular2-polyfills.js:1247(anonymous function) @ angular2.dev.js:13558NgZone.run @ angular2.dev.js:13520outsideHandler @ angular2.dev.js:13355Zone.run @ angular2-polyfills.js:1243zoneBoundFn @ angular2-polyfills.js:1220
angular2.dev.js:23083 TypeError: this.directive_0_0.onFocus is not a function
    at AbstractChangeDetector.ChangeDetector_couresesComponent_0.handleEventInternal (viewFactory_couresesComponent:55)
    at AbstractChangeDetector.handleEvent (angular2.dev.js:8075)

**Comment by pkozlowski-opensource** [comment]
Typo: `onFocus()` != `onfocus()` - JS is case-sensitive. 

Please use an appropriate channel for general support questions like this one: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by AmmarMohamed** [comment]
thanks .. @pkozlowski-opensource
