### ISSUE TITLE
proposal: promises in templates.

### ISSUE THREAD

**Issue by SanderElias** [angular/angular#917]
In line with how ES7 is going to support some more async operators and stuff I was wondering on how to support async in templates now. Do we have a way to resolve a promise in the template?
here is an example of what I would like to propose:

```
   <template promise="goLoadUser(id) then #user">
           <li>{{user.name}}</li>
   </template>
```

this makes it possible to handle a array of promises right in the template like this:
```
   <template *for="#prom of arrayOfAsyncLoadingUsers">
      <template promise="prom then #user">
             <li>{{user.name}}</li>
      </template>
  </template>
```

Or is this just stretching it too far?

**Comment by gdi2290** [comment]
you should check out this talk
[FalcorJS](http://youtu.be/WiO1f6h15c8)
basically it's `| async` pipe that will resolve your promise so you can write your 

```html
<ul *for="#prom of arrayOfAsyncLoadingUsers | async">
  <li>{{user.name}}</li>
</ul>
```
if you have promises in your promises or in Falcor's case Observables in Observables then it's something like

```html
<ul *for="#prom of arrayOfObservablesLoadingUsers | async">
  <li>{{ user.get('name') | async }}</li>
</ul>
```

**Comment by gdi2290** [comment]
keep in mind this is isn't in angular2 at the moment and only lives on a branch by @vsavkin until it's finalized

**Comment by SanderElias** [comment]
@gdi2290 I have seen the talk. The talk is about observables. Those are coming to ES7/8. As I have been looking into/started using observables, I was very happy about the announcement that NG2 would have full support for those. 
However, an observable is not an promise. As promises are now grasped by the main-stream developer, I feel that there should be support for those in the template itself. There is stuff that comes wrapped in a promise that only needs to be displayed without any further processing. This is a thing that might belong in a template.
On a side-node, it also explains to beginners how to handle a promise.

**Comment by pkozlowski-opensource** [comment]
@SanderElias we've been down this path in 1.x and it was declared a "bad idea". It might have been due to impl details (promises where handled in `$parse` and it was reducing flexibility of this service for cases where you wanted to get a promise instance from an expression) but 2 other arguments against this were:
* impossible to handle promise rejection errors
* "too magical" (argument largely depending on the personal taste, I suppose....)

**Comment by SanderElias** [comment]
@pkozlowski-opensource I know we have been there, but that was about promises handled in the background. This is visible declared in the template. No magic anymore, so that takes care of the magical part ;)
About rejections. I thought about that too. Let me write out the full form, a bit like what @mhevery did for the forEach directive.

```
<template promise="myPromise"  then='#result' reject='#reason'>
      <div (hidden)='!!!result'>Hurrah! the promise is kept! Live the {{result}}</div>
      <div (hidden)='!!!reason'>Bummer, the promise is broken. Sadly {{reason}} happened</div>
</template>
```
(hmm, hard to not type ngShow! The !!! may seem strange, but it converts and negates any JS value to an boolean)
I'm not entirely sure I have the correct (pseudo) code, but essential this is just a promise directive with 2 decorators. One decorates the fulfilled, and the other handles reject. 
If we feed this trough the same process as the *for, this might end up like:

`<someTag promise="myPromise then #result reject #reason">...</someTag>`

That looks like a coherent and utterly a-magical interface to me!
Or do I miss something obvious? (I know I tend to miss elephants in rooms)

**Comment by mhevery** [comment]
supported as ` | async` closing.
