### ISSUE TITLE
[hidden] called more than it is define in template

### ISSUE THREAD

**Issue by wannadream** [angular/angular#9174]
I'm submitting a suspicious bug.

I bind [hidden] to a simple method which returns true or false. I added console.log() in the method. According to my data, it has one matching result which means the method bound to [hidden] should only be called once. However, in console, I see a lot of output more than once. Is this a bug or some mechanism behind I do not understand?

I attached my code and result here. The method name is onShowAddress
![00000](https://cloud.githubusercontent.com/assets/6989212/16016855/db36731a-3151-11e6-9619-8aa179dbdad8.gif)
![00000](https://cloud.githubusercontent.com/assets/6989212/16016877/facf2064-3151-11e6-9897-a6ee6c8094f7.gif)
![00000](https://cloud.githubusercontent.com/assets/6989212/16016914/2f39af22-3152-11e6-9acd-27d9ad18d276.gif)

I am developing app under Visual Studio 2015 Update 2 with Windows 10.

Angular version:2.0.0-beta.17
Browser: Chrome 51.
Language: TypeScript

**Comment by pkozlowski-opensource** [comment]
> Is this a bug or some mechanism behind I do not understand?

It is the change-detection mechanism at work, this is how Angular operates to see if there are model changes and DOM needs updating. You might ask more on a specific support channels: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
