### ISSUE TITLE
Child components of Routed Component don't load after router.navigate

### ISSUE THREAD

**Issue by MiGu3X** [angular/angular#9178]
So I have a loginWithGoogle that when it success, the user gets redirected to the 'Dashboard' with this._router.navigate(['Dashboard']). The page navigates to the dashboard, but the components that are in the template of the DashboardComponent seems not to load, when I press 'F5' though, they load perfectly.

**app.ts**
`@RouteConfig([`
  `    ..{ path: '/', name: 'Landing',   component: LandingComponent },`
  `    ..{ path: '/dashboard',   name: 'Dashboard', component: DashboardComponent },`
`])` 

**landing.ts**
`import { Router } from '@angular/router-deprecated';`
`constructor(private router : Router) {`
    `..this._router = router;`
 `}`
`login() {`
    `..Meteor.loginWithGoogle({}, (error) => {`
     `....if (!error) {`
       `......this._router.navigate(['Dashboard']);`
    `....}`
   ` ..});`
 ` }`

**dashboard.html**
`<navbar type="dashboard"></navbar>`
`    <div class="col-xs-6 col-xs-offset-3 project-container-card">`
      `..<projects></projects>`
    `</div>`

Expected behaviour: 
- Child components should load correctly with its information.
- [Expected behaviour (shows like this after pressing F5 on /dashboard)](http://i.imgur.com/kx6K3Or.jpg)

Actual behaviour: 
- Child components don't show, their HTML tags **DO** appear, but the information that should be inside, doesn't.
- [Actual behaviour (after login)](http://i.imgur.com/IEktylf.jpg)

I repeat, if you press 'F5', everthing loads correctly
Please if someone could help me it would be great

P.S.: I'm using @angular/router-deprecated since the Socially tutorial uses that one, but will upgrade when new one gets out if the tutorial gets updated :+1:

**Comment by ericmartinezr** [comment]
@MiGu3X there's not really good reason to keep using that router, if you found issues with it, they won't be fixed. You should really move away from it to the new new new router (https://github.com/angular/vladivostok). The router thing changed so fast and so many times that tutorials, blogs, etc. The latest documentation about the latest router is here http://victorsavkin.com/post/145672529346/angular-router.

**Comment by MiGu3X** [comment]
@ericmartinezr I have some questions, it would be great if you could answer them!
- How can I use that router?
- Is it already out or is it in a beta phase?
Thanks a lot for the answer before.

**Comment by ericmartinezr** [comment]
@MiGu3X 

1) Simply install it `npm install @angular/router3.0.0-alpha.3` (iirc)
2) It is in alpha, so it's not stable but it's the "definitive" one. You can also move to ngrx/router (https://github.com/ngrx/router) and then migrate to the new new new router since the "vladivostok" router is based on ngrx/router.

If you have any question about those routers, you can go to these channels to get help

- https://gitter.im/angular/angular
- https://gitter.im/ngrx/router

**Comment by CaptainCodeman** [comment]
It's back to alpha status and not yet complete so it could change and there are no docs yet, just the blog posts.

**Comment by MiGu3X** [comment]
Thanks @ericmartinezr and CaptainCodeman

**Comment by ericmartinezr** [comment]
@MiGu3X there are no official docs so far, but you can see the blog Victor wrote about it I linked over here https://github.com/angular/angular/issues/9178#issuecomment-225676991

**Comment by zoechi** [comment]
and angular/angular.io#1636

**Comment by tolgamalachi** [comment]
hello @MiGu3X 
i had kind of a similar issue. i - also - wanted to route to my dashboard after logging in with auth0 x)...
i do not know how the meteor login works. but is it possible that it calls something async? so the navigation would fire but i guess you are not allowed to navigate to dashboard and it stops. do you use someting like `@CanActivate(() => tokenNotExpired())` ? does the meteor login has some events? like `hidden` or `success`?

**Comment by zoechi** [comment]
@tolgamalachi 
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)
