### ISSUE TITLE
RC 1 ORIGINAL EXCEPTION: No provider for RuntimeCompiler!

### ISSUE THREAD

**Issue by Dj-jom2x** [angular/angular#9179]
this works on beta.17 

import {RuntimeCompiler} from '@angular/compiler/src/runtime_compiler';

constructor(private _runtimeCompiler: RuntimeCompiler){
  this._runtimeCompiler.clearCache();
}

.................................................................

but on RC 1  it throws an error 
"ORIGINAL EXCEPTION: No provider for RuntimeCompiler!"
if i add that as provider
it will throw 
No provider for CompileMetadataResolver!
then many more No Providers Error 
RuntimeCompiler,CompileMetadataResolver,DirectiveResolver,PipeResolver,ViewResolver,DirectiveNormalizer,etc

heres the plunk
http://plnkr.co/edit/hCCEeS2qR09bEXmv051D

**Comment by pkozlowski-opensource** [comment]
* `@angular/compiler/src/runtime_compiler` is a private / not-exported path and as such should never be used (in other words you should nave see `/src/` in your import paths for Angular2 public APIs);
* you can import `RuntimeCompiler` from a public `@angular/compiler` path, see: https://angular.io/docs/ts/latest/api/compiler/index/RuntimeCompiler-class.html
* in the future please ask support questions using an appropriate support forum: https://angular.io/docs/ts/latest/api/compiler/index/RuntimeCompiler-class.html

**Comment by Dj-jom2x** [comment]
> you can import RuntimeCompiler from a public @angular/compiler path, see: https://angular.io/docs/ts/latest/api/compiler/index/RuntimeCompiler-class.html

**nope because its missing** 

heres the rc1 npm @angular/compiler package

```
 /**
 * @module
 * @description
 * Starting point to import all compiler APIs.
 */
export { ElementSchemaRegistry } from './src/schema/element_schema_registry';
export { COMPILER_PROVIDERS, TEMPLATE_TRANSFORMS, CompilerConfig, RenderTypes, UrlResolver, DEFAULT_PACKAGE_URL_PROVIDER, createOfflineCompileUrlResolver, XHR, ViewResolver, DirectiveResolver, PipeResolver, SourceModule, NormalizedComponentWithViewDirectives, OfflineCompiler, CompileMetadataWithIdentifier, CompileMetadataWithType, CompileIdentifierMetadata, CompileDiDependencyMetadata, CompileProviderMetadata, CompileFactoryMetadata, CompileTokenMetadata, CompileTypeMetadata, CompileQueryMetadata, CompileTemplateMetadata, CompileDirectiveMetadata, CompilePipeMetadata } from './src/compiler';
export * from './src/template_ast';
export * from './private_export';
```

theres no "RuntimeCompiler" there

then look at this https://github.com/angular/angular/blob/master/modules/%40angular/compiler/compiler.ts

```
/**
 * @module
 * @description
 * Starting point to import all compiler APIs.
 */
export {COMPILER_PROVIDERS, CompileDiDependencyMetadata, CompileDirectiveMetadata, CompileFactoryMetadata, CompileIdentifierMetadata, CompileMetadataWithIdentifier, CompileMetadataWithType, CompilePipeMetadata, CompileProviderMetadata, CompileQueryMetadata, CompileTemplateMetadata, CompileTokenMetadata, CompileTypeMetadata, CompilerConfig, DEFAULT_PACKAGE_URL_PROVIDER, DirectiveResolver, NormalizedComponentWithViewDirectives, OfflineCompiler, PipeResolver, RenderTypes, RuntimeCompiler, SourceModule, TEMPLATE_TRANSFORMS, UrlResolver, ViewResolver, XHR, createOfflineCompileUrlResolver} from './src/compiler';
export {ElementSchemaRegistry} from './src/schema/element_schema_registry';

export * from './src/template_ast';
export * from './private_export';
```
RuntimeCompiler exist there .. but not on npm @angular/compiler package

i clone it yesterday the rebuild it then replace the missing one it works now .. ty
