### ISSUE TITLE
Problem with the `packUmd` function in the SystemJS configuration

### ISSUE THREAD

**Issue by templth** [angular/angular#9180]
* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**

When using the `packUmd` function in the SystemJS configuration (`systemjs.config.js` file), I have the following exception:

> zone.js:461 Unhandled Promise rejection: Cannot resolve all parameters for 'ViewUtils'(RootRenderer, undefined @Inject(Token AppId), SanitizationService). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'ViewUtils' is decorated with Injectable. ; Zone: <root> ; Task: Promise.then ; Value: NoAnnotationError

When using the `packIndex` one, it works.

I use the following project for my tests:

* https://github.com/templth/mockbackend-test

**Expected/desired behavior**

It works in both cases.

To reproduce:

* Clone the previous project
* Run `npm install`
* Run `npm run start`

* **What is the expected behavior?**

No error

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.1
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
Chrome: Version 51.0.2704.84 (64-bit)
Firebase: Version 47.0

* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart] 

TypeScript 1.8.10

**Comment by eddhannay** [comment]
The `packIndex` variable comes from this line in the Angular 2 typescript quickstart:

https://github.com/angular/angular.io/blob/ffbdcd2b9c3c3447fd31f249d529f82bfdf9d8de/public/docs/_examples/quickstart/ts/systemjs.config.1.js#L47

Using UMD seems to work most of the time, but when trying to use mockHttp in a Jasmine test, it will throw the error raised above.

**Comment by templth** [comment]
@eddhannay Thanks for trying!

**Comment by vasuneet** [comment]
I am getting the same issue with my testing stuff. not received any resolution yet.

**Comment by vasuneet** [comment]
I am using rc4

**Comment by IgorMinar** [comment]
Thanks for reporting this issue. I was not able to reproduce the problem. I believe that this issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular version.

If the problem still persists, please file a new issue and ensure you provide the version of Angular affected and include the steps to reproduce the problem when filling out the issue template.
