### ISSUE TITLE
Publish 2.0.0-rc.1 to npm

### ISSUE THREAD

**Issue by NZSmartie** [angular/angular#9187]
### Bug Report

[Angualr2 npm package](https://www.npmjs.com/package/angular2) is currently at `2.0.0-beta.17` which is out of date. `2.0.0-rc.1` was released over a month ago and is not yet available on https://www.npmjs.com/

**Comment by pkozlowski-opensource** [comment]
See https://github.com/angular/angular/blob/master/CHANGELOG.md#200-rc0-2016-05-02

tl;dr; - package name changed, check the changelog. Latest RCs are published `@angular`

**Comment by NZSmartie** [comment]
So... Apart from the changelog, and the easy to miss mesage on the Developer guide (not the API Reference). There isn't any other way to discover where the latest release is for developers already using angular2... 
Searching on npm wont come up with any meaningful results as it seams that the packages are now hosted "privately" under the @angualr namespace

In that case, Is it possible to update the Readme on the npm package for angualr2 to help point current developers in the right direction. I can see that the Quick Start already uses the new packages. The News page on Angular's site doesn't mention this either
