### ISSUE TITLE
Pplease recommend the most suitable operating environment for the server angular 2 web app

### ISSUE THREAD

**Issue by racktime** [angular/angular#9188]
Looks are worried about the web app server configuration.

Angular 2 web server for development in lite-server may write,
I want to distribute the source and compile executables and other build tools webpack to a Web server for production.

app server configuration plans
1. different types of Web server installation, configuration and other (Apache Tomcat, etc?)
2. node express Server Configuration build source deployment.

Please recommend the most suitable operating environment for the server angular 2 web app

**Comment by pkozlowski-opensource** [comment]
Angular 2 can work with any web / application server and as such can't recommend any particular solution.

In any case this type of question doesn't belong here, see: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
