### ISSUE TITLE
Got an error when STOMP.js lost connection to WebSocket

### ISSUE THREAD

**Issue by Dimanoid** [angular/angular#9189]
* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**
Got this error when STOMP.js lost connection to WebSocket

```
Uncaught TypeError: Cannot read property 'name' of undefined
sendMessageImpl @ extensions::messaging:342
(anonymous function) @ VM366718 extensions::runtime:115
target.(anonymous function) @ extensions::SafeBuiltins:19
(anonymous function) @ VM366719 extensions::binding:59
target.(anonymous function) @ extensions::SafeBuiltins:19
(anonymous function) @ VM366719 extensions::binding:422
window.onfocus @ content.js:229
```

As far as I can see this happens in last line of this code:
```
// Shared implementation used by tabs.sendMessage and runtime.sendMessage.
  function sendMessageImpl(port, request, responseCallback) {
    if (port.name != kNativeMessageChannel)
```

**Expected/desired behavior**
No error

* **Angular version:** 2.0.0-rc.1
 
* **Browser:** [Chrome 51.0.2704.63 (64-bit) ] 
 
* **Language:** [ TypeScript 1.8.10 ]

**Comment by zoechi** [comment]
How is that related to Angular2? Please provide a Plunker that shows the code you're using and allows to reproduce.

**Comment by pkozlowski-opensource** [comment]
This issue is not actionable as-is. @Dimanoid if you believe that you are hitting a bug in Angular 2 please open a new issue following out submission guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue
