### ISSUE TITLE
URL does not appear in browser when navigating

### ISSUE THREAD

**Issue by sam-wheat** [angular/angular#9191]
* **I'm submitting a ...**
- [ x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**
URL that appears in browser after navigating:
http://localhost:61560/#

**Expected/desired behavior**
Expected URL to appear after navigating
http://localhost:61560/#/Post/this-is-post1

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

Component:

	onClick(item: ContentItem)
    {
        this.router.navigate(['/Post', item.Slug]);
    }
	
app.component.ts

    @Component({
        selector: 'my-app',
        templateUrl: './app/app.html',
        directives: [NavBar, ROUTER_DIRECTIVES],
        providers: [HTTP_PROVIDERS, BlogService, SessionService]
   })
        @Routes([
            { path: '/', component: Home },
            { path: '/Contact', component: Contact },
            { path: '/BlogIndex', component: BlogIndex },
            { path: '/Post/:slug', component: BlogDetail }
    ])

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

 "@angular/core": "2.0.0-rc.1",
Browser IE 11 
 
Language: Typescript

**Comment by ericmartinezr** [comment]
@sam-wheat the `@angular/router-deprecated` and `@angular/router` are abandoned, they won't be fixed. You should look at https://github.com/angular/vladivostok which is the "definitive" router (new new new router).

Reference

http://victorsavkin.com/post/145672529346/angular-router
https://github.com/angular/angular.io/pull/1636/files

**Comment by sam-wheat** [comment]
wow, looks like I've been wasting my time.  Thank you for the update.

**Comment by ericmartinezr** [comment]
@sam-wheat no problem at all. I missed this link also http://angularjs.blogspot.cl/2016/06/improvements-coming-for-routing-in.html
