### ISSUE TITLE
Angular2 AJAX fails to return actual error code to error handler.

### ISSUE THREAD

**Issue by smitchell** [angular/angular#9192]
* **I'm submitting a ...**
- [x ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**
When calling an endpoint that throws an error, such as this call:
`private _standardHeaders = new Headers({ 'Authorization': 'Bearer ' + localStorage.getItem('access_token'), 'Content-Type': 'application/json' });

    getUserEmail(): Rx.Observable<Email[]> {
        let options = new RequestOptions({
            method: RequestMethod.Get,
            url: this._emailUrl,
            headers: this._standardHeaders
        });
        return this.http.request(new Request(options))
            .map((res: Response) => <Email[]> res.json().data)
            .catch((res: Response) => this.handleError(res));
    }
`
The error handler alwasy receives a 200 status, not the original error.

`{"_body":{"isTrusted":true},"status":200,"ok":true,"statusText":"Ok","headers":{},"type":3,"url":null}`

Note: the endpoint proxy is set-up to receive OPTIONS.

`	@Bean
	public CorsFilter corsFilter() {
		final UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
		final CorsConfiguration config = new CorsConfiguration();
		config.setAllowCredentials(true);
		config.addAllowedOrigin("*");
		config.addAllowedHeader("*");
		config.addAllowedMethod("OPTIONS");
		config.addAllowedMethod("HEAD");
		config.addAllowedMethod("GET");
		config.addAllowedMethod("PUT");
		config.addAllowedMethod("POST");
		config.addAllowedMethod("DELETE");
		config.addAllowedMethod("PATCH");
		source.registerCorsConfiguration("/**", config);
		return new CorsFilter(source);
	}`

**Expected/desired behavior**

The error handler should receive the actual status code (e.g. 403, 500, etc...)

* **What is the expected behavior?**

The actual status code should be received by the error handler:

`{"_body":{"isTrusted":true},"status":500,"ok":false,"statusText":"Internal Server Error","headers":{},"type":3,"url":null}`

* **What is the motivation / use case for changing the behavior?**

We need to have the correct status to improve the user experience. For instance, if the error is 403, we can tell the user they don't have sufficient privileges, but if the status is 500 we can tell them there was a problem.

* **Please tell us about your environment:**

`  "dependencies": {
    "angular2": "2.0.0-beta.17",
    "bootstrap": "^4.0.0-alpha.2",
    "bootstrap-loader": "^1.0.8",
    "es6-promise": "^3.1.2",
    "es6-shim": "^0.35.0",
    "es7-reflect-metadata": "^1.6.0",
    "jquery": "^2.2.2",
    "rxjs": "5.0.0-beta.6",
    "tether": "^1.2.0",
    "zone.js": "0.6.12"
  },`

* **Angular version:** 2.0.0-beta.17
 
* **Browser:** [all] 
 
* **Language:** [TypeScript:
![screen shot 2016-06-14 at 9 43 40 am](https://cloud.githubusercontent.com/assets/359955/16048713/b7c9b08a-321a-11e6-980e-43828a6c0078.png)
 1.8.10]

**Comment by zoechi** [comment]
Might be angular/http#54

**Comment by smitchell** [comment]
@zoechi - You are right. I had been working this bug here: https://github.com/auth0/angular2-jwt/issues/37, which was not the right ticket. This can be closed in favor of angular/http#54

**Comment by smitchell** [comment]
Changing the syntax of my call from this;

`.catch(this.handleSigninError);`

To this:

`.catch((res: Response) => this.handleSigninError(res));`

Fxed my problem. For the first time I've seen the actual error code returned to my error handler:

`{"_body": "{\"timestamp\":1465920358459,\"status\":500,\"error\":\"Internal Server Error\",\"exception\":\"com.netflix.zuul.exception.ZuulException\",\"message\":\"GENERAL\"}",
	"status": 500,
	"ok": false,
	"statusText": "Ok",
	"headers": {
		"Content-Type": ["application/json;charset=UTF-8"]
	},
	"type": 2,
	"url": "https://test.ioubenefits.com/mobile-gateway/signin"
}`

**Comment by calebeaires** [comment]
@smitchell I have the same problem. Even if backend send an 200 response, angular shows this error.
