### ISSUE TITLE
A Decorator to prevent provider Shadowing

### ISSUE THREAD

**Issue by yjaaidi** [angular/angular#9193]
Hi,

I'm encountering the following issue regularly with beginners. They keep shadowing stateful services by redeclaring them in child components.

Suppose you have a `HeroService` that stores your heroes that caches API results in memory.

Now suppose you have the following component tree:
```
                AppComponent
               /             \
              /               \
HeroDetailComponent          HeroListComponent
```

If `HeroService` is declared in `AppComponent` and redeclared in `HeroDetailComponent` by mistake, your unit tests for `HeroDetailComponent` will work, unit tests for `HeroListComponent` but you will just end up with two components not sharing the same cache and it can get worse if it's not just a cache but a memory storage.

IMHO I think that `HeroService` should be declared with a `NoOverride` that at least triggers a warning or something if it's already present in `AppComponent` and redeclared in a child component.

This could avoid lots of misunderstanding and would be less 'error-prone'.

Thank you in advance!

**Comment by IgorMinar** [comment]
Tools like Augury could help you detect this problem by visualizing the dependency graph: https://augury.angular.io/

I don't think that `NoOverride` flag is good because desirability of overriding a provider is usually a property of the application and not the property of the provider.

I currently can't think of a way to have this kind of feature without false positives or negatives.

**Comment by yjaaidi** [comment]
Good point Igor!

What about an option for the `provide` function?

Something like :

`provide(HeroStore, {noOverride: true})`

**Comment by vicb** [comment]
I don't think we should build something in core for that.

That's more something that could be enforce by external tools, ie [codelyzer](https://github.com/mgechev/codelyzer)
