### ISSUE TITLE
No Angular2 error messages upon failure

### ISSUE THREAD

**Issue by bakarydiarra** [angular/angular#9195]
* **I'm submitting a ...**
- [X ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**
I am currently developping an application using ionic2 and angular2 RC 1. If I make a  mistake in code, say adding a service in the directive list instead of the provider one, I won't have any feedback from the angular framework in the console. This application won't work and I am not told why.

**Expected/desired behavior**
I would like to have a meaninfull error message in the console to help me investigate what went wrong.

* **What is the motivation / use case for changing the behavior?**
User Friendliness.

* **Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.1
 
* **Browser:** [Chrome 51.0.2704.84 m (64-bit) ] 
 
* **Language:** [TypeScript 1.8]

**Comment by pkozlowski-opensource** [comment]
>  If I make a mistake in code, say adding a service in the directive list instead of the provider one, I won't have any feedback from the angular framework

It is not very clear from the description what is the exact condition under which you get into problems. Could you please provide more context? See our issue submission guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue

The most important part would be to have a minimal reproduce scenario in a plunker.

**Comment by pkozlowski-opensource** [comment]
Closing as we've got no reproduction scenario. Happy to re-open when we've got one.
