### ISSUE TITLE
withCredentials missing in @angular/http rc1

### ISSUE THREAD

**Issue by hartjus** [angular/angular#9196]
* **I'm submitting a ...**
- [ X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**
When I look at the github repo for the @angular/http module, I can see support for the withCredentials flag on an HTTP request.  (https://github.com/angular/angular/blob/master/modules/%40angular/http/src/base_request_options.ts#L61)

However, when I look at the copy that is downloaded from NPM, the withCredentials flag is missing.  I'm using the latest, as far as I can tell.

my project's **package.json**: `"@angular/http": "2.0.0-rc.1"`

**@angular/http/package.json**:  `"@angular/http@2.0.0-rc.1",`

Am I reading this wrong?  Shouldn't I see the withCredentials flag in my copy of the http module?

**Expected/desired behavior**
withCredentials support is in the RC1 package.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
OSX and Win7.

* **Angular version:** 2.0.0-rc.1
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
All.
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart] 
TypeScript, ES5.

**Comment by ericmartinezr** [comment]
This landed already https://github.com/angular/angular/pull/7281, you see it because it's in master, but RC.2 hasn't been released yet, that's why.

**Comment by hartjus** [comment]
That's what I figured, but wanted to double-check.  I will wait for RC2 to be released.  Thank you for your help!

**Comment by FabianMeul** [comment]
Any idea on when RC.2 might be released? :-)

**Comment by hartjus** [comment]
I see that RC2 was released yesterday (6/15) and I can see the withCredentials support.  Thank you!
