### ISSUE TITLE
TBODY being automatically generated inside of THEAD

### ISSUE THREAD

**Issue by jjk3yz** [angular/angular#9206]
Issue Type: BUG
Version: Angular 2 RC.1 with Typescript
Browser: Chrome v51 (mac)

Currently, the framework is  automatically and erroneously creating a TBODY element  inside a THEAD element whenever associating a component with a THEAD selector and the component's template contains a TR element.

TBODY elements should not be automatically created ever. 

Example plunker here: http://plnkr.co/edit/577nlagiLkAIwQEiQSbZ?p=preview

The bug breaks table rendering so I'd say it's pretty serious as it makes it really hard to build table oriented components.

**Comment by ericmartinezr** [comment]
dup of https://github.com/angular/angular/issues/5967

**Comment by vicb** [comment]
Dupliucate
