### ISSUE TITLE
redundant (?) debug info in production mode

### ISSUE THREAD

**Issue by shaharvaldman** [angular/angular#9208]
We are currently evaluating the performance of our application after upgrading it to angular2.
Naturally, one of the areas we are looking into is the elapse time of the change detection cycle. Unfortunately, the execution time is longer than we expected.

Analysis shows that even when running in production mode, a large portion of the time is spent on self.debug functions of the change detection generated objects.
Example:
_View_xxx.prototype.detectChangesInternal = function(throwOnChange) {
...
  self.debug(0,1,37);
...
}

Are these debug statements expected to be removed from the source in production mode on a later RC?

Thanks

**Comment by zoechi** [comment]
Might be related to #8508 but hard to tell. Your post doesn't contain a lot of information.

**Comment by vicb** [comment]
I'm working on making this configurable
