### ISSUE TITLE
routerLink crashes browser

### ISSUE THREAD

**Issue by vapits** [angular/angular#9210]
* **I'm submitting a ...**
- [x] bug report

**Current behavior**
If I add the `<a [routerLink]="[ '/login' ]">Login</a>` to my main component template the `/` route doesn't work, it crashes the browser. The `/login` route though works! If I remove it then the `/login` route simple doesn't print in the `router-outlet` anything! An all this by adding or removing the `<a [routerLink]="[ '/login' ]">Login</a>` in my template.

Here's my code:

Web App component:
```
import { Component } from '@angular/core';
import { Routes , ROUTER_DIRECTIVES , ROUTER_PROVIDERS} from '@angular/router';
import { TopBarComponent , LeftBarComponent } from './shared';
import { LoginComponent } from './+login';

@Component({
  moduleId: module.id,
  selector: 'web-app-app',
  templateUrl: 'web-app.component.html',
  styleUrls: ['web-app.component.css'],
  directives: [ROUTER_DIRECTIVES, TopBarComponent, LeftBarComponent],
  providers: [ROUTER_PROVIDERS]
})

@Routes([
  { path: '/', component: WebAppAppComponent },
  { path: '/login', component: LoginComponent }
])
export class WebAppAppComponent {

}
```

Main template:
```
<a [routerLink]="[ '/login' ]">Login</a>

<top-bar></top-bar>
<left-bar></left-bar>

<router-outlet></router-outlet>
```

Login component:
```
import { Component, OnInit } from '@angular/core';

@Component({
  moduleId: module.id,
  selector: 'router-outlet',
  templateUrl: 'login.component.html',
  styleUrls: ['login.component.css']
})
export class LoginComponent implements OnInit {

  constructor() {}

  ngOnInit() {
  }

}
```

Login template:
```
<p>
  Please login
</p>
```
<form>
  <input [(ngModel)]="username" type="email"/>
  <input [(ngModel)]="password" type="password"/>
  <button (click)="doLogin()">Login</button>
</form>
```
* **Angular version:** 2.0.0-rc.1 
* **Browser:** [all] 
* **Language:** [TypeScript 1.8.10]

**Comment by zoechi** [comment]
This router is about to be replaced. What's the purpose of using `router-outlet` as selector for a component? What does "crash" mean? What browser+version? What OS?

**Comment by zoechi** [comment]
Also a Plunker to reproduce would be helpful.

**Comment by vapits** [comment]
Hey @zoechi,

crashes means that the browser if freezing until I get a message to kill it.

Mac OS X 10.11.5
Chrome 50.0.2661.102 (64-bit)
Firefox 44.0.2
Safari 9.1.1 (11601.6.17)

I'll try for a plunker later, This is an angular-cli project.

**Comment by zoechi** [comment]
That doesn't sound like a crash. That sounds more like an endless loop. How is CPU utilization while it hangs?

router-outlet is supposed to allow the router to add components not to apply components yourself. Rather create a login route that adds the component for you.

**Comment by kiddykooly** [comment]
If you use the new router, you must inject the Router object to constructor
export class WebAppAppComponent {
    constructor(private router: Router) {}
}

if It's still not work, I should use the router/deprecated and try again

**Comment by zoechi** [comment]
@kiddykooly there is more than one new router ;-) I assume you mean `@angular/router` from RC.1. If the router is not injected and the root component doesn't contain a routerLink (which is another workaround for the issue you mentioned) then there is no routing happening at all. That doesn't seem to be the case here because he mentiones in his initial post that the issue happens after he clicks the routerLink in the main template.

**Comment by vapits** [comment]
Yes it is an endless loop still though I couldn't found where.
Anyway I went back to router-deprecated as @kiddykooly suggest.

I'll close it as I'm not sure if this is a bug anymore and if i found more I'll reopen it.

thx all
