### ISSUE TITLE
UI doesn't update after exception is thrown

### ISSUE THREAD

**Issue by ngbernard** [angular/angular#9212]
I'm submitting a bug report.

When an exception is caught by Angular 2's exception handler, the UI no longer 'updates'.  I have a very simple example here:

https://plnkr.co/edit/iHDYpZ3fDlO6bhOtlTbQ

The Do It button flips the boolean which is reflected in the interpolated value in the template.  However, once the Break It button is pressed (which cases an error to be thrown), the interpolated value no longer updates when the 'Do it' button is hit.  However, the console still logs the messages 'Doing it'.  

The problem I'm dealing with is I would like to create a custom exception handler that warns the user and possibly does some work to clear a form when something has gone wrong, but what I'm seeing is if I throw an error on a button click to test it, all UI updates stop.  However, buttons continue to function, meaning any buttons that post requests will do so if the form is in a good state.  The UI however has ceased to update and inform the user what is happening.

I'm not sure if this is a problem with Zones or something else, but attempting  an NgZone.run() didn't seem to solve the problem for me.  If an error is meant to break a component's UI, what's the correct approach to my problem?

Angular version: 2.0.0-rc.1 (The plunker version is older but is exhibiting the same behavior) 
 
Browser: Tested and confirmed behavior in Chrome and Firefox

Language: TypeScript

**Comment by zoechi** [comment]
See also http://stackoverflow.com/questions/37793276/angular-2-custom-exceptionhandler-change-detection-lag/37793791#37793791

You shouldn't rely on your application being in a proper state after an unhandled exception.

**Comment by pkozlowski-opensource** [comment]
> You shouldn't rely on your application being in a proper state after an unhandled exception.

This is true, but the way it breaks the page right now is a bit "brutal". The good news is that we've got an issue for this already: #2413 so closing as a duplicate.
