### ISSUE TITLE
Invalid name: "@angular/*"

### ISSUE THREAD

**Issue by cipacda** [angular/angular#9214]
I am starting to use Ionic2 on a new project and all worked well to get it to install for the first time.

I have now setup a continuous integration build for it and when I am running npm install on the build server it fails with the following:

54 verbose addNameRange registry:https://registry.npmjs.org/@angular%2fplatform-browser not in flight; fetching
55 verbose get https://registry.npmjs.org/@angular%2fplatform-browser not expired, no request
56 silly addNameRange number 2 { name: '@angular/platform-browser',
56 silly addNameRange range: '>=2.0.0-rc.1 <3.0.0',
56 silly addNameRange hasData: true }
57 silly addNameRange versions [ '@angular/platform-browser',
57 silly addNameRange [ '0.0.0-0',
57 silly addNameRange '0.0.0-1',
57 silly addNameRange '0.0.0-2',
57 silly addNameRange '0.0.0-3',
57 silly addNameRange '0.0.0-4',
57 silly addNameRange '0.0.0-5',
57 silly addNameRange '0.0.0-6',
57 silly addNameRange '0.0.0-7',
57 silly addNameRange '2.0.0-rc.0',
57 silly addNameRange '2.0.0-rc.1' ] ]
58 silly addNamed @angular/platform-browser@2.0.0-rc.1
59 verbose addNamed "2.0.0-rc.1" is a plain semver version for @angular/platform-browser
60 silly rollbackFailedOptional Starting
61 silly rollbackFailedOptional Finishing
62 silly runTopLevelLifecycles Starting
63 silly runTopLevelLifecycles Finishing
64 silly install printInstalled
65 verbose stack Error: Invalid name: "@angular/platform-browser"
65 verbose stack at ensureValidName (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\node_modules\normalize-package-data\lib\fixer.js:300:15)
65 verbose stack at Object.module.exports.fixNameField (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\node_modules\normalize-package-data\lib\fixer.js:204:5)
65 verbose stack at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\node_modules\normalize-package-data\lib\normalize.js:30:38
65 verbose stack at Array.forEach (native)
65 verbose stack at normalize (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\node_modules\normalize-package-data\lib\normalize.js:29:15)
65 verbose stack at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:349:5)
65 verbose stack at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
65 verbose stack at ReadFileContext. (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:295:20)
65 verbose stack at ReadFileContext.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
65 verbose stack at FSReqWrap.readFileAfterOpen as oncomplete
66 verbose cwd C:\jenkins\workspace\Placement Audit Website
67 error Windows_NT 6.2.9200
68 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "@angular/platform-browser"
69 error node v6.2.1
70 error npm v3.9.3
71 error Invalid name: "@angular/platform-browser"
72 error If you need help, you may report this error at:
72 error https://github.com/npm/npm/issues
73 verbose exit [ 1, true ]

ionic info output:
Your system information:

You have been opted out of telemetry. To change this, run: cordova telemetry on.

6.2.0

Gulp version: CLI version 3.9.0
Gulp local:
Ionic Framework Version: 2.0.0-beta.8
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
OS: Windows 8
Node Version: v6.2.1

**Comment by pkozlowski-opensource** [comment]
Sounds like a support question that should be directed to https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
