### ISSUE TITLE
ngFor default trackBy (a mix of trackBy identity & index) is error-prone

### ISSUE THREAD

**Issue by yjaaidi** [angular/angular#9218]
Hi!

I was wondering how Angular 2 was handling duplicates with `ngFor` and it's default `trackBy` and I was surprised to not have any warning or error.

As you can see on this plunker: https://embed.plnkr.co/dv5BIa/

If you remove the first `Foo` element (component 0), Angular will keep the `Guido` pointing on component 1 but it will reuse component 0 for the next `Foo`.

Actually what it does is to use an identity track by but when it meets duplicates, it says nothing and does an implicit track by index on them.

Well, we could say that in most cases if you get the same input, you get the same result so we don't care but suppose the component has some internal state like in the plunker (the input's state).

This can be really disappointing.

Is it possible to still keep this implementation but at least log a warning when we get this error?

@teropa Are you the one taking care of ngFor documentation? Maybe you should present this behaviour when the trackBy section will be added to the documentation if it's not already there and I couldn't find it.

Thank you guys!

**Comment by teropa** [comment]
> @teropa Are you the one taking care of ngFor documentation? Maybe you should present this behaviour when the trackBy section will be added to the documentation if it's not already there and I couldn't find it.

@yjaaidi Nope, API docs are written by the core team. Sounds like something that should be mentioned though. 👍

**Comment by vicb** [comment]
@matsko could you check this for the NgFor docs ?

**Comment by meeroslav** [comment]
@yjaaidi I don't know if you've realized this, but if you modify first element before removing it, the name will be reflected on third element  (now with id 0), but will leave last element intact.

**Comment by yjaaidi** [comment]
@meeroslav yes. That's exactly the behaviour I am describing here. If you remove the first 'Foo' component, the first component is reused for the second 'Foo', the second one is reused for the third 'Foo' and the third component is destroyed.

Try this:
Edit the three 'Foo' inputs and remove the first one. You will notice that the third 'Foo' component is removed.

**Comment by DzmitryShylovich** [comment]
could u update plunkr and add steps to reproduce/expected behavior?

**Comment by DzmitryShylovich** [comment]
@yjaaidi 👆 any updates?

**Comment by yjaaidi** [comment]
@DzmitryShylovich the behavior can be reproduced as described before.

**Comment by DzmitryShylovich** [comment]
@yjaaidi I don't see an issue here. By default it will compare by ref. If you don't like it or you need some customization (like logging duplicates etc) you can provide your own impl. This is specified in the docs.

**Comment by wardbell** [comment]
Closing as not an issue we should address in Angular docs.
