### ISSUE TITLE
IE10 and 9 Syntax Error while the solution works in IE11+

### ISSUE THREAD

**Issue by hanijizan** [angular/angular#9221]
Using Angular2 RC1, here is the error in IE10 and 9:

`Unhandled Promise rejection: SyntaxError: Expected '/' 
    at Anonymous function (eval code:13:1) 
    at Anonymous function (eval code:1:31) 
    at eval code (eval code:1:2) 
    Evaluating /application_ref.js 
    Evaluating /index.js 
    Error loading ; Zone: <root> ; Task: Promise.then ; Value: Error: SyntaxError: Expected '/' 
    at Anonymous function (eval code:13:1) 
    at Anonymous function (eval code:1:31) 
    at eval code (eval code:1:2) 
    Evaluating http://localhost:1000/node_modules/@angular/core/src/application_ref.js 
    Evaluating http://localhost:1000/node_modules/@angular/core/index.js 
    Error loading http://localhost:1000/Scripts/app.js ...`

I've also asked the question at SO, but I suspect that no one is interested in titles that contain word "IE10". Here http://stackoverflow.com/questions/37841763/angular2-rc1-with-ie10-and-9-unhandled-promise-rejection-syntaxerror-expected

**Comment by zoechi** [comment]
Can you provide a Plunker to reproduce?

**Comment by hanijizan** [comment]
@zoechi plunkr won't help since it'll transpile the typescript in browser and of course it works fine since the browser engine will ignore the typescript. It's only a problem if you're sending the generated .js to the browser.

Since systemjs-builder is used for release only, the DEV box runs systemjs module loader in order to download the generated .js files and their dependencies in browser. That's where the issue comes up.

**Comment by IgorMinar** [comment]
I think we need more information about this issue. From the stack trace it looks like you are using systemjs in the browser to load the commonjs modules of angular distributed via npm.  can you please confirm?

**Comment by IgorMinar** [comment]
could you also try to use bundles instead of individual files like we do in this plunker template http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5

**Comment by hanijizan** [comment]
@IgorMinar yes, I'm using individual files loaded by systemjs. As I've mentioned, bundling using systemjs-builder and using those bundles will solve the problem for release builds but DEV mode is an issue since we don't want to bundle every time we make a code change on our local boxes. 

Additionally, i tried using the plunkr you've provided but it seems there are no rc1 bundles there. Another idea I had, since I'm using Visual Studio and windows, was to replace the line endings and file encoding of `application_ref.js` but that didn't solve the issue. At this point, I assume it's an irrelevant error due to something else or it's due to bad member naming in classes.

**Comment by IgorMinar** [comment]
I was able to verify that this plunker which should simulate your environment works just fine in ie10. please examine the plunker and if you still able to reproduce the problem please open a new issue.

**Comment by IgorMinar** [comment]
oops.. forgot to add the link to my plunker: http://plnkr.co/edit/6H1DeE9gc4GfxqljVW2H?p=preview

**Comment by hanijizan** [comment]
Ok, you're implying the issue is related to the code that I wrote. How do I debug it then? There's no indication of what could be wrong in the stack trace.

**Comment by IgorMinar** [comment]
I actually think that the problem is in your setup. But since I can't see
what your setup is, I can't debug the issue and confirm. I was however able
to confirm that all of our code works fine on ie10 and I shared the
reproduction with you.

**Comment by hanijizan** [comment]
@IgorMinar nothing crazy in setup. Pretty straight forward:

**tsconfig.json**

`{
  "compileOnSave": true,
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "module": "amd",
    "moduleResolution": "node",
    "removeComments": true,
    "noImplicitAny": false,
    "sourceMap": true,
    "target": "es3"
  }
}`

**systemjs**

`System.config({
                defaultJSExtensions: true,
                baseURL: '@VirtualPathUtility.ToAbsolute("~/")',
                map: {
                    '@@angular/common': 'node_modules/@@angular/common/index',
                    '@@angular/core': 'node_modules/@@angular/core/index',
                    '@@angular/compiler': 'node_modules/@@angular/compiler/index',
                    '@@angular/http': 'node_modules/@@angular/http/index',
                    '@@angular/platform-browser': 'node_modules/@@angular/platform-browser/index',
                    '@@angular/platform-browser-dynamic': 'node_modules/@@angular/platform-browser-dynamic/index',
                    '@@angular/router': 'node_modules/@@angular/router/index',
                    '@@angular/platform-browser/src/animate/animation_builder': 'node_modules/@@angular/platform-browser/src/animate/animation_builder.js',
                    'rxjs': 'node_modules/rxjs'
                }
            });`

I don't see anything crazy going on and that's all the setup there is really. Here's how modules are loaded:

`<script type="text/javascript">System.import('Scripts/myScript');</script>`

If nothing wrong with these setups, then it's the code I wrote and since stack trace is not showing any relevant information, how do we approach debugging? But again if it was the code that I wrote, how come it works when mangled and minified?
