### ISSUE TITLE
Feature request: Lifecycle hook for before component change detector running

### ISSUE THREAD

**Issue by bendilts** [angular/angular#9222]
* **I'm submitting a ...**
- [x] feature request

**Current behavior**
The ngDoCheck callback gets called regardless of whether a component's change detector is actually run (e.g. if OnPush is used).
The ngOnChanges callback gets called only if an actual bound input changes.

**Expected/desired behavior**
My view template uses data that is relatively expensive to calculate, and uses it several times in the same template. I would like a lifecycle callback wherein I can generate that data for the component, immediately before the component's change detector actually runs.

Right now, I can work around this by clearing the calculated data in ngDoCheck, and then lazily filling the data in the first time it's requested from the template. But that feels really hacky.

* **What is the motivation / use case for changing the behavior?**
Allow expensive calculations to be run once per actual change detector run on components using the OnPush change detection strategy, without jumping through excessive hoops.

* **Please tell us about your environment:**

* **Angular version:** 2.0.0-beta.X 
 
* **Browser:** all
 
* **Language:** all

**Comment by zoechi** [comment]
What about switching to `ChangeDetectorStrategy.OnPush` and control yourself when change detection should be run?

**Comment by bendilts** [comment]
I'm already using OnPush. That is making it so my template is only evaluated infrequently. The issue I'm facing is in performance of evaluating the template. For example, my template may have something like this:

`<div>{{matchingContacts().length}} contacts found</div>
<div *ngFor="#contact of matchingContacts()">
{{contact.name}}
</div>`

Now imagine that matchingContacts() is expensive to run. It's being called twice in the template. In order to optimize this, I would like to calculate matchingContacts() once and store it in a variable accessible to the view, which then can refer to it for free. However, there's no lifecycle callback for "the view's change detector is marked dirty and is about to run."

**Comment by robwormald** [comment]
you should avoid calling methods from the view anyway, as this would typically be an antipattern - angular *has* to execute that method to do any change detection at all. Perhaps a plunker of your situation would be useful here, but I don't see this needing a new lifecycle hook.

**Comment by pkozlowski-opensource** [comment]
> Now imagine that matchingContacts() is expensive to run. It's being called twice in the template. In order to optimize this, I would like to calculate matchingContacts() once and store it in a variable accessible to the view, which then can refer to it for free. However, there's no lifecycle callback for "the view's change detector is marked dirty and is about to run."

But isn't it what `ngOnChanges` is for? If you are using `OnPush` strategy you are saying, more or less: "my display can only change when on of the inputs changes". So this would be a perfect place to re-calculate your "expensive" model. If you worrying about this running to often (ex. you need to re-calculate your model when only _one_ of inputs changes) you could use a setter. 

Agreeing with @robwormald - I don't see a new lifecycle hook here... Closing the issue for now but ready to be convinced to re-consider (convincing will need good arguments and a plunker, though!)
