### ISSUE TITLE
RC2: Failed to load *.umd.js resources

### ISSUE THREAD

**Issue by demisx** [angular/angular#9226]
Upgrading a TypeScript Angular 2 app from "2.0.0-rc.1" to "2.0.0-rc.2" results in the following error in the browser console:

```sh
Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/:14 Error: (SystemJS) Error: XHR error (404 Not Found) loading
http://localhost:3001/vendor/@angular/platform-browser-dynamic/platform-browser-dynamic.umd.js(…)
(anonymous function) @ localhost/:14

http://localhost:3001/vendor/@angular/core/core.umd.js 
Failed to load resource: the server responded with a status of 404 (Not Found)
```

The *umd.js files are no longer present in RC2 or am I missing something?

**Comment by robwormald** [comment]
they're in the /bundles directory of the npm distributions. That said,  I would *strongly* suggest setting up a proper build tool rather than using the UMDs going forward.

**Comment by robwormald** [comment]
Will leave this open for a bit for others

**Comment by robwormald** [comment]
And this is listed in the changelog, its always a good idea to consult it during upgrades.

**Comment by demisx** [comment]
Thanks @robwormald  for quick reply. We already use gulp 4 as the build tool, so not sure what you mean by _"I would strongly suggest setting up a proper build tool rather than using the UMDs going forward"_.  If you could please point me in the right direction or show an example, I'd really appreciate it. So far, I am a little confused since the UMD bundle is set in `systemjs.config.js`.

**Solution:**
So far, I've been using the QuickStart App code from https://angular.io/docs/ts/latest/quickstart.html. Didn't realize that this line in `systemjs.config.js` needed to be updated to https://github.com/angular/quickstart/blob/master/systemjs.config.js#L42 for the RC2 to work. It's all good now.

**Comment by IgorMinar** [comment]
@robwormald is correct. the location of bundles has changed and the change was documented in the changelog.

@naomiblack is pushing an update of the quickstart guide to angular.io right now.

**Comment by naomiblack** [comment]
live on angular.io now and fixed.

**Comment by demisx** [comment]
Thank you all. 

@robwormald Still interested to learn more about _"I would strongly suggest setting up a proper build tool rather than using the UMDs going forward"_. If you have any examples or info to share.

**Comment by dtnanthikattu** [comment]
I get an error like "Failed to load :3000/node_modules/@angular/common/bundles/common.umd.js/http resource:  the server responded with a status of 404 (Not Found) when using Http functionality with Angular. What is wrong here. I am following the tutorials.

I am using the 4.3.4 code base and type script is 2.1.0. I understand this can be fixed by making a change to the system.js.config.js file. Please tell me what needs to be changed here.

 "@angular/common": "~4.3.4",
    "@angular/compiler": "~4.3.4",
    "@angular/core": "~4.3.4",
    "@angular/forms": "~4.3.4",
    "@angular/http": "~4.3.4",

"typescript": "~2.1.0",
