### ISSUE TITLE
Provide promise list from forEach

### ISSUE THREAD

**Issue by jrgleason** [angular/angular#923]
Would it be possible to provide a list of promises that the transclude can use to tell when rendering is complete?

We tend to use automated testing and without this information I have to revert to using something like ng-class="$last" in the actual ng-repeat div. If I had a collection of promises it would help me know when individual objects are rendered.

**Comment by vicb** [comment]
This repo is for Angular2. You are probably looking for https://github.com/angular/angular.js

**Comment by jrgleason** [comment]
No actually I was thinking ahead. Will the for Each handle transclusion in a differant way? Doesn't look too differant from the code. Is the only reason you say that because I said ngRepeat once? Did you not see for Each in the title

**Comment by vicb** [comment]
Sorry ! "transclude", "ng-repeat" and "ng-class" make me think your were referring to ng1 - btw `foreach` should become `for`

**Comment by gdi2290** [comment]
similar to #917 you can use the new pipeline api to update your bindings. There is an example ( you can't define your components like this with <template> and <script> but it easier to look at)
```html
<template>
  <ul *for="#user of arrayOfAsyncPromises">
    <li>
      <user-item [value]="user"></user-item>
    </li>
  </ul>
</template>
<script>
@Component({
  selector: 'user-item',
  bind: {
    value: 'value | async' // you have control over the bindings
  }
})
@Template({
  inline: `<div>User {{ user.name }}</div>`,
  directives: []
})
class UserItem {
  value:Object;
  constructor() {
  }
}

@Component({
  selector: 'user-list'
})
@Template({
  directives: [UserItem]
})
class UserItem {
  value:Object;
  constructor() {
    this.arrayOfAsyncPromises = [
      new PromiseWrapper({ name: 'PatrickJS' }).delay(1000)
    ];
  }
}
</script>
```

**Comment by jrgleason** [comment]
Thanks I will take a look at it and yes it is a bit of a feat to be able to remember which terms for which version :-)

**Comment by gdi2290** [comment]
@jrgleason I can make you an angular1 version of async if you like. Keep in mind the api isn't finalized yet so it may change

**Comment by jrgleason** [comment]
Sure just give me the branch info might at least help me get a grasp things. I am working on stuff I wouldn't push forward with till August. Just trying to get a jump start and compare it to what we need.

**Comment by gdi2290** [comment]
@jrgleason I don't really recommend this in production but it helps to play around with it. I didn't want to hold state in the filter so I'm taking advantage of the interval state of the promise. I have an example in the repo for you to start playing around with
```bash
$ bower install angular-async
```
or
```bash
$ npm install angular-async
```
https://github.com/gdi2290/angular-async

**Comment by mhevery** [comment]
no action for angular repo, closing.
