### ISSUE TITLE
[DOCS] Animation live samples (plunker) are not working

### ISSUE THREAD

**Issue by shlomiassaf** [angular/angular#9232]
All the animations live demo's are not working.

The config addresses the XXX-builds git repots and not the npmcdn packages as in the official `heros` plunkers, this might be the issue.

Error in console:
`Error: platform_browser_1.bootstrap is not a function(…)`

@wardbell

**Comment by matsko** [comment]
Fixed with this PR: https://github.com/angular/angular/pull/12223.

This will be automatic once angular.io can generate its own plnkrs.

**Comment by DzmitryShylovich** [comment]
@shlomiassaf can you pls close the issue as it was fixed? ☝️

**Comment by DzmitryShylovich** [comment]
@shlomiassaf is this still relevant?
