### ISSUE TITLE
public api review of @angular/compiler

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#9234]
most of the apis in @angular/compiler are experimental. we need review all exported symbols, ensure that only the ones absolutely needed are exported and mark those as `@experimental`

**Comment by tbosch** [comment]
Decided that `@angular/compiler` should not be part of the public api at all

- remove it from public api docs
- remove from api guard
- have a base implementation of `TestComponentBuilder` in `@angular/core`
- somehow move a simpler version of `CompilerConfig` to `@angular/core` that the compiler will use to create the real `CompilerConfig`

**Comment by StephenFluin** [comment]
@tbosch -- @IgorMinar thought this was almost done. Can you confirm this is really not landing rc4?

**Comment by tbosch** [comment]
@StephenFluin See above for the missing tasks.

**Comment by IgorMinar** [comment]
everything but the CompilerConfig change have been implemented. The CompilerConfig change is owned by @tbosch.

**Comment by tbosch** [comment]
CompilerConfig is not needed any more. Users should call the `createCompiler` function in `platform-browser-dynamic` to create a compiler given some options.
