### ISSUE TITLE
public api review of the testing api surface

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#9236]
@juliemr and I briefly reviewed the testing api surface and found a few private symbols being accidentally exported. we need to clean this up.

**Comment by juliemr** [comment]
First pass:

8d5a312585d7e3335b81e79beaae09b6be8518b8
894747c34cf9bbef2b891d9cdfdd0b699a6a95fb
3d8eb8cbca97c49c67111567ff7110bd80286bab
8a9e9c7bd3f889de07b21e95698e0aa2d465af02

Remaining: move ComponentFixture, clean `@angular/common/testing`

**Comment by juliemr** [comment]
Last bits:

https://github.com/angular/angular/pull/9562
https://github.com/angular/angular/pull/9386
