### ISSUE TITLE
api review and cleanup @angular/platform-server

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#9237]
due to regressions in rc2 release the following commits got reverted yesterday: 80deac5cded4d3534771c3484f937b0f8dde143c 80deac5cded4d3534771c3484f937b0f8dde143c

these changes are desirable and we need to correct them and bring them back to master.

- [ ] correct and unrevert the commits above
- [ ] review the remaining public api surface
- [ ] add stability markers

**Comment by mhevery** [comment]
https://github.com/angular/angular/pull/9205
