### ISSUE TITLE
rc.2 getting .... _private__.getDOM(...).getCookie is not a function

### ISSUE THREAD

**Issue by born2net** [angular/angular#9241]
rc.2 getting platform_browser_1.__platform_browser_private__.getDOM(...).getCookie is not a function

any ideas?

**Comment by cipri-p** [comment]
Getting the same error here.

**Comment by zoechi** [comment]
Looks like there is a similar issue #9294. Were you able to solve it?

**Comment by cipri-p** [comment]
My scenario is similar to @zoechi: calling an http get to retrieve a config.json before calling me the bootstrap function. Worked well in RC1

**Comment by born2net** [comment]
sorry forgot to close the bug... yes I had a mix of rc.1 and rc.2... cleaned it up and bug went away...
see example here:  https://github.com/born2net/ng2Boilerplate
Regards,

Sean
