### ISSUE TITLE
ngClass not work in HostBinding

### ISSUE THREAD

**Issue by shjyh** [angular/angular#9242]
**Current behavior**
ngClass directive not work in HostBinding and Component Decorator with host property.
it goes well in version rc.1,
is there some breaking changes?

**Angular version:** 2.0.0-rc.2
 
**Language:** [ES6/7]

**Comment by robwormald** [comment]
As stated in the issue template, please provide a reproduction in a plunker (which was listed in the template)

**Comment by zoechi** [comment]
See http://stackoverflow.com/questions/35753198/ngclass-in-host-property-of-component-decorator-does-not-work

`ngClass` is not special binding syntax, it's a directive and directives are only applied to the template where the selector matches.

**Comment by pkozlowski-opensource** [comment]
Thnx @zoechi

**Comment by amcdnl** [comment]
It would be nice if this could be a host binding tho :)

**Comment by waterplea** [comment]
Same for me, I have HostBinding for preset boolean types like invalid, valid etc. and I would love to also be able to pass some arbitrary modifiers without creating a separate HostBinging for each of them.

**Comment by kimamula** [comment]
Another problem is that it is difficult to combine with classes specified with `class` in the template.

```html
<my-component
  class="foo" // <- this is removed if MyComponent has @HostBinding('class')
></my-component>
```
