### ISSUE TITLE
NgUpgrade Uncaught TypeError: Cannot read property 'BROWSER_APP_COMPILER_PROVIDERS' of undefined

### ISSUE THREAD

**Issue by albertosantini** [angular/angular#9244]
When the adapter is bootstrapped, I get the message in the subject.

```
upgradeAdapter.bootstrap(document.body, ["dummy"]);
```

This is due to the wrong object injected to `upgrade.umd.js` when it is loaded: `global.ng.platformBrowser.dynamic` instead of `global.ng.platformBrowserDynamic`.

As workaround
```
        <script>ng.platformBrowser.dynamic = ng.platformBrowserDynamic;</script>
        <script src="node_modules/@angular/upgrade/bundles/upgrade.umd.js"></script>
```

https://github.com/albertosantini/angular2-es5-jumpstart/blob/master/src/client/app/mix-ng1-ng2.js
https://github.com/albertosantini/angular2-es5-jumpstart/blob/master/src/client/index.html#L33

Edit: This is in 2.0.0-rc.2. In 2.0.0-rc.1 it was ok.

**Comment by IgorMinar** [comment]
thanks for the report. we'll fix this in rc.3

**Comment by IgorMinar** [comment]
the rollup.config.json is incorrect for the `upgrade` package.

**Comment by albertosantini** [comment]
Tested with rc.3 in my use case. It works nice.
Thanks for the quick fix.
