### ISSUE TITLE
Quickstart NPM Start script failes when applying watcher

### ISSUE THREAD

**Issue by aplegatt** [angular/angular#9245]
When running "npm start" script in Angular quickstart guide I'm getting following errors:

`1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'tsc:w' ]
2 info using npm@3.9.0
3 info using node@v6.2.0
4 verbose run-script [ 'pretsc:w', 'tsc:w', 'posttsc:w' ]
5 info lifecycle angular2-quickstart@1.0.0~pretsc:w: angular2-quickstart@1.0.0
6 silly lifecycle angular2-quickstart@1.0.0~pretsc:w: no script for pretsc:w, continuing
7 info lifecycle angular2-quickstart@1.0.0~tsc:w: angular2-quickstart@1.0.0
8 verbose lifecycle angular2-quickstart@1.0.0~tsc:w: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-quickstart@1.0.0~tsc:w: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/robert/progs/angular2/node_modules/.bin:/usr/local/bin:/usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/robert/progs/angular2/node_modules/.bin:/usr/local/bin:/Users/robert/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/robert/.rvm/bin
10 verbose lifecycle angular2-quickstart@1.0.0~tsc:w: CWD: /Users/robert/progs/angular2
11 silly lifecycle angular2-quickstart@1.0.0~tsc:w: Args: [ '-c', 'tsc -w' ]
12 silly lifecycle angular2-quickstart@1.0.0~tsc:w: Returned: code: 1  signal: null
13 info lifecycle angular2-quickstart@1.0.0~tsc:w: Failed to exec tsc:w script
14 verbose stack Error: angular2-quickstart@1.0.0 tsc:w: `tsc -w`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid angular2-quickstart@1.0.0
16 verbose cwd /Users/robert/progs/angular2
17 error Darwin 14.3.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "tsc:w"
19 error node v6.2.0
20 error npm  v3.9.0
21 error code ELIFECYCLE
22 error angular2-quickstart@1.0.0 tsc:w: `tsc -w`
22 error Exit status 1
23 error Failed at the angular2-quickstart@1.0.0 tsc:w script 'tsc -w'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-quickstart package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     tsc -w
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-quickstart
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-quickstart
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]`

I am on Mac OS X 10.10.3

**Comment by skreborn** [comment]
For the sake of readability:
```
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'tsc:w' ]
2 info using npm@3.9.0
3 info using node@v6.2.0
4 verbose run-script [ 'pretsc:w', 'tsc:w', 'posttsc:w' ]
5 info lifecycle angular2-quickstart@1.0.0~pretsc:w: angular2-quickstart@1.0.0
6 silly lifecycle angular2-quickstart@1.0.0~pretsc:w: no script for pretsc:w, continuing
7 info lifecycle angular2-quickstart@1.0.0~tsc:w: angular2-quickstart@1.0.0
8 verbose lifecycle angular2-quickstart@1.0.0~tsc:w: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-quickstart@1.0.0~tsc:w: PATH: [...]
10 verbose lifecycle angular2-quickstart@1.0.0~tsc:w: CWD: /Users/robert/progs/angular2
11 silly lifecycle angular2-quickstart@1.0.0~tsc:w: Args: [ '-c', 'tsc -w' ]
12 silly lifecycle angular2-quickstart@1.0.0~tsc:w: Returned: code: 1 signal: null
13 info lifecycle angular2-quickstart@1.0.0~tsc:w: Failed to exec tsc:w script
14 verbose stack Error: angular2-quickstart@1.0.0 tsc:w:tsc -w
14 verbose stack Exit status 1
14 verbose stack at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
14 verbose stack at emitTwo (events.js:106:13)
14 verbose stack at EventEmitter.emit (events.js:191:7)
14 verbose stack at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack at emitTwo (events.js:106:13)
14 verbose stack at ChildProcess.emit (events.js:191:7)
14 verbose stack at maybeClose (internal/child_process.js:850:16)
14 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid angular2-quickstart@1.0.0
16 verbose cwd /Users/robert/progs/angular2
17 error Darwin 14.3.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "tsc:w"
19 error node v6.2.0
20 error npm v3.9.0
21 error code ELIFECYCLE
22 error angular2-quickstart@1.0.0 tsc:w:tsc -w
22 error Exit status 1
23 error Failed at the angular2-quickstart@1.0.0 tsc:w script 'tsc -w'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-quickstart package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error tsc -w
23 error You can get information on how to open an issue for this project with:
23 error npm bugs angular2-quickstart
23 error Or if that isn't available, you can get their info via:
23 error npm owner ls angular2-quickstart
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by aplegatt** [comment]
Thanks for readability fix. Running `tsc -w` results in this:

`fs.js:1425
    throw error;
    ^

Error: watch /users/robert/progs/angular2 ENOENT
    at exports._errnoException (util.js:953:11)
    at FSWatcher.start (fs.js:1423:19)
    at Object.fs.watch (fs.js:1450:11)
    at addDirWatcher (/usr/local/lib/node_modules/typescript/lib/tsc.js:1036:39)
    at Object.addFile (/usr/local/lib/node_modules/typescript/lib/tsc.js:1051:21)
    at Object.watchFile (/usr/local/lib/node_modules/typescript/lib/tsc.js:1172:48)
    at Object.executeCommandLine (/usr/local/lib/node_modules/typescript/lib/tsc.js:34546:44)
    at Object.<anonymous> (/usr/local/lib/node_modules/typescript/lib/tsc.js:34877:4)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)`

**Comment by skreborn** [comment]
Well, `ENOENT` means that an entry (be it file or folder) does not exist at a given path. Does the path `/users/robert/progs/angular2` exist? Is it a folder?

**Comment by aplegatt** [comment]
I haven't read that path carefully before but now that You mentioned it I noticed that it has "/users/" folder when on my computer its "/Users/" with first letter in uppercase. I tried to create a symbolic link with `sudo ln -s /Users /users` and it seems to work now. Still seems a little weird to me. Is there an option for truescript compiler for case sensitivity or something?

**Comment by skreborn** [comment]
Case sensitivity is a file system thing, really, so it's unrelated to the compiler as far as I'm concerned.

**Comment by pkozlowski-opensource** [comment]
This sounds like a general support question and as such this discussion should be moved to an appropriate support channel, see: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

Thnx!

**Comment by skreborn** [comment]
@pkozlowski-opensource Sorry about that. I actually thought about redirecting @aplegatt initially, but at that time I wasn't sure if this error was general or not.

**Comment by pkozlowski-opensource** [comment]
@skreborn no reason to be sorry, we do appreciate people helping out. Appreciate a lot! And feel free to continue the discussion here. It is just that there is nothing actionable in this issue for the team so this is why I've closed this ticket.

@aplegatt if you are not sure if you are hitting a bug please check support forums before opening issues.

**Comment by aplegatt** [comment]
@pkozlowski-opensource I will remember about that in the future, sorry!

@skreborn Indeed I have a case-sensitive file system on my Mac. I just didn't have any problems like that in the past so was a little confused about that. Don't know why he looked in that particular path. Anyway thanks for leading me into solution!

**Comment by skreborn** [comment]
@aplegatt Glad I could help!
