### ISSUE TITLE
forms-deprecated TypeScript compile errors

### ISSUE THREAD

**Issue by marcalj** [angular/angular#9247]
* **I'm submitting a ...**
- [x] bug report
**Current behavior**
Console errors while compiling my app. I'm not using any forms-deprecated functionality:

```
Using tsc v1.9.0-dev.20160616-1.0
node_modules/@angular/common/src/forms-deprecated/directives/ng_control_name.d.ts(1,32): error TS2305: Module ''@angular/core'' has no exported member 'SimpleChanges'.
node_modules/@angular/common/src/forms-deprecated/directives/ng_form_control.d.ts(1,21): error TS2305: Module ''@angular/core'' has no exported member 'SimpleChanges'.
node_modules/@angular/common/src/forms-deprecated/directives/ng_form_model.d.ts(1,21): error TS2305: Module ''@angular/core'' has no exported member 'SimpleChanges'.
node_modules/@angular/common/src/forms-deprecated/directives/ng_model.d.ts(1,21): error TS2305: Module ''@angular/core'' has no exported member 'SimpleChanges'.
```

**Expected/desired behavior**
No errors compiling.

* **Please tell us about your environment:**
rc2 & ng1.5.7. SystemJS. TypeScript v1.9.0-dev.20160616-1.0

**Comment by marcalj** [comment]
Fixed after regenerating TypeScript and typings I think. I had a really strange stack error messages today and I don't know how I solved, the thing is now I didn't get those warnings :/

**Comment by vineethsoma** [comment]
How did you fix this? I am trying to integrate angular forms with my app and compile, I keep getting 
c:/../node_modules/@angular/forms/src/directives/ng_model.d.ts(1,32): error TS2305: Module '"c:/...l/node_modules/@angular/core/index"' has no exported member 'SimpleChanges'.

What do you mean by regenerating TypeScript and Typings?

**Comment by marcalj** [comment]
I've messes up with my build script code. So I downgrade TypeScript to stable version (locally and globally), and then go to ```typescript@next``` again. Also remove typings folder and do ```typings install``` again to regenerate the includes.

PD: Why not using new ```@angular/forms``` package?

Hope it helps.

**Comment by vineethsoma** [comment]
Alright I am going to give it a try. I think I am using the new Angular forms.Here are my dependencies: 
  "@angular/common": "2.0.0-rc.1",
    "@angular/compiler": "2.0.0-rc.1",
    "@angular/core": "2.0.0-rc.1",
    "@angular/forms": "^0.1.1",
    "@angular/http": "2.0.0-rc.1",
    "@angular/platform-browser": "2.0.0-rc.1",
    "@angular/platform-browser-dynamic": "2.0.0-rc.1",
    "@angular/router": "2.0.0-rc.1",
    "angular2-moment": "^0.8.0",
    "bootstrap-sass": "^3.3.6",
    "browser-sync-ui": "^0.6.0",
    "core-js": "^2.4.0",
    "cors": "^2.7.1",
    "es5-ext": "^0.10.11",
    "es6-shim": "^0.35.0",
    "font-awesome": "^4.6.1",
    "fstream": "^1.0.9",
    "jquery": "^2.2.3",
    "lodash": "^4.13.1",
    "log4js": "^0.6.37",
    "make-error-cause": "^1.1.0",
    "moment": "^2.13.0",
    "ng2-bootstrap": "1.0.17",
    "ng2-file-upload": "^1.0.3",
    "node-sass": "^3.7.0",
    "normalize-package-data": "^2.3.5",
    "reflect-metadata": "0.1.3",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "^0.19.29",
    "zone.js": "^0.6.12"


and my typings.json: 
{
  "dependencies": {
    "lodash": "registry:npm/lodash#4.0.0+20160416211519",
    "moment": "registry:npm/moment#2.10.5+20160211003958"
  },
  "globalDependencies": {
    "angular-protractor": "registry:dt/angular-protractor#1.5.0+20160425143459",
    "es6-shim": "registry:dt/es6-shim#0.31.2+20160317120654",
    "jasmine": "registry:dt/jasmine#2.2.0+20160505161446",
    "selenium-webdriver": "registry:dt/selenium-webdriver#2.44.0+20160317120654"
  }
}

**Comment by vineethsoma** [comment]
Yep you were right, I just had to update my angular packages to rc.3: These dependencies fixed it for me. 
 "dependencies": {
    "@angular/common": "^2.0.0-rc.3",
    "@angular/compiler": "2.0.0-rc.3",
    "@angular/core": "2.0.0-rc.3",
    "@angular/forms": "^0.1.1",
    "@angular/http": "2.0.0-rc.3",
    "@angular/platform-browser": "2.0.0-rc.3",
    "@angular/platform-browser-dynamic": "2.0.0-rc.3",
    "@angular/router": "2.0.0-rc.2",
    "angular2-moment": "^0.8.0",
    "bootstrap-sass": "^3.3.6",
    "browser-sync-ui": "^0.6.0",
    "core-js": "^2.4.0",
    "cors": "^2.7.1",
    "es5-ext": "^0.10.11",
    "es6-shim": "^0.35.0",
    "font-awesome": "^4.6.1",
    "fstream": "^1.0.9",
    "jquery": "^2.2.3",
    "lodash": "^4.13.1",
    "log4js": "^0.6.37",
    "make-error-cause": "^1.1.0",
    "moment": "^2.13.0",
    "ng2-bootstrap": "1.0.17",
    "ng2-file-upload": "^1.0.3",
    "node-sass": "^3.7.0",
    "normalize-package-data": "^2.3.5",
    "reflect-metadata": "0.1.3",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "^0.19.29",
    "typings": "^1.3.0",
    "zone.js": "^0.6.12"
  },
  "devDependencies": {
    "browser-sync": "^2.12.8",
    "codelyzer": "0.0.19",
    "connect-history-api-fallback": "^1.2.0",
    "del": "~2.2.0",
    "glob": "^7.0.3",
    "gulp": "^3.9.1",
    "gulp-cssnano": "^2.1.2",
    "gulp-if": "~2.0.1",
    "gulp-protractor": "^2.3.0",
    "gulp-rev": "^7.0.0",
    "gulp-rev-replace": "^0.4.3",
    "gulp-sass": "^2.3.1",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-tslint": "^5.0.0",
    "gulp-typescript": "~2.13.4",
    "gulp-uglify": "~1.5.3",
    "gulp-useref": "~3.1.0",
    "jasmine-core": "~2.4.1",
    "karma": "~0.13.22",
    "karma-coverage": "~1.0.0",
    "karma-ie-launcher": "^1.0.0",
    "karma-jasmine": "~1.0.2",
    "karma-phantomjs-launcher": "~1.0.0",
    "karma-sourcemap-loader": "^0.3.7",
    "ngstarter-systemjs-tasks": "1.0.0-rc.1",
    "phantomjs-prebuilt": "^2.1.7",
    "remap-istanbul": "~0.6.4",
    "require-dir": "~0.3.0",
    "run-sequence": "^1.2.1",
    "traceur": "~0.0.110",
    "tslint": "^3.10.2",
    "typings": "^1.3.0",
    "yargs": "^4.7.1"
  }

**Comment by virenshekhawat** [comment]
currently i`m facing this kind of error,"TypeScript error: D:/FriendKnowsNeon/Friendknows Sales/friendknows-sales-app-ui/
components/file-upload/file-upload.module.ts(1,10): Error TS2305: Module '"D:/Fr
iendKnowsNeon/Friendknows Sales/friendknows-sales-app-ui/node_modules/@angular/c
ommon/index"' has no exported member 'CommonModule." is it related to angular upgradations?
