### ISSUE TITLE
Form validity initially reports a wrong value and doesn’t emit first change

### ISSUE THREAD

**Issue by chliebel** [angular/angular#9249]
**I'm submitting a ...**
- [x] bug report

**Current behavior**
Form initially reports a valid state at AfterViewInit, even if it isn’t valid (e.g. a required input field is unset). But in contrast to the old forms, the first status change (to invalid) isn’t even emitted.

**Expected/desired behavior**
Form should either report correct initial validity state or emit first status change.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
http://plnkr.co/edit/SF3wy8NIJ7Me3VAa7wgj?p=preview

**Angular version:** 2.0.0-rc.2

**Comment by IgorMinar** [comment]
@kara can you please review?

**Comment by kara** [comment]
The status change and value change events should be firing initially - definitely a bug.  It should be fixed in master now: https://github.com/angular/angular/pull/9559.   Thanks for reporting!

Regarding the initial validity of the form, it is actually expected to be true because at this point, the child form controls haven't yet been processed.  They have to be processed next tick.

**Comment by chliebel** [comment]
@kara Nice! Thank you.

**Comment by thomashilzendegen** [comment]
Hi @kara,

Unfortunately, the bug with the missing event is not fixed in rc4, yet. If you change the plunker to rc4 the event still does not get fired. Or do I miss anything?

Thanks for verifying.

**Comment by kara** [comment]
@thomashilzendegen  It seems to be working for me. Check out this RC.4 plunker:

http://plnkr.co/edit/ZMoEuavh6Afl6PogCKdv?p=preview

You should see "status change! false" in the console.  

You might note that I removed the "initialStatus" property from the original reporter's plunker, as changing its value in the AfterViewInit hook will cause an "Expression change after checked" error.

Are you testing it differently?  If so, can you modify my plunker to show what you're looking at ?

**Comment by thomashilzendegen** [comment]
@kara It was my fault. I did not increase the forms package version.

It's working perfectly now. Thank you. 💯
