### ISSUE TITLE
Allow manipulation of view children tree from a ComponentRef

### ISSUE THREAD

**Issue by shlomiassaf** [angular/angular#9254]
* **I'm submitting a ...**
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**
For manual component tree interaction only the Host view (component) can add child views (embedded/component) to it tree. 
The component requests the injection of `ViewContainerRef`, this object allows adding/removing/moving child views

**Expected/desired behavior**
The creator of a host view(component) can also add child views to it.
Creating a host view by using the component factory returns a new instance of `ComponentRef`. `ComponentRef` abstracts the access to the `AppElement` which is how we can interact with the tree.

* **What is the motivation / use case for changing the behavior?**
Disallowing tree manipulation outside of the host view does follow SRP, however it also forces components to do more then they should.
Considering situations where a service would want to compose a complete component (With children) based on some logic, it makes sense to give the service this responsibility.

Since we don't want to expose the `AppElement` to the component ref, the component ref can export the `ViewContainerRef`.

Personally I experienced a situation where a non published component (private) was created by a service using the `ComponentFactory`.
```
<my-app>
   <private-cmp></private-cmp>
</my-app>
```

`MyApp` is a known component (registered as root), however `PrivateCmp` isn't (not set in `directives` array of `MyApp` component meta).

This result in it just not rendering.

Later I would want to create it, easy task using `ComponentResolver` -> `ComponentFactory` -> create(...), it will render however since it's not listed in `MyCmp` it will not be part of the view children of `MyApp` host view, this will not participate in all change detections and life cycle hooks.
If I had access to add it, it would be easy enough.

**Comment by pkozlowski-opensource** [comment]
@shlomiassaf I've got very hard time following what you are getting at / trying to achieve... A concrete, real-life use cases and a minimal plunk would help clear this up...

I very much doubt if this issue is actionable as-is.... Sorry, you need to convince us that there is a real problem here and why it is important :-)

**Comment by shlomiassaf** [comment]
@pkozlowski-opensource you're right, I didn't feel I was clear but I did it in a rush, I will edit i later on and tag you.

Anyway, the change does not require any logic change or something, just exposure. I know the exposed API is strictly guarded :) 

I got this working with 1 LOC accessing a private member, but that's no good :)

**Comment by pkozlowski-opensource** [comment]
@shlomiassaf we are trying to tidy up issues backlog so I'm going to close this one for now. Will re-open as soon you are back with more info.

**Comment by shlomiassaf** [comment]
@pkozlowski-opensource I completely understand, is this synced with @vicb ?

The implementation of `Overlay`s in **material2**  is a good example, the overlay service requires adding a **component** not part of an explicit user declared **element** in the template, this service constructs all child panes of the inserted component. Since the component was not part of a declared element adding it will result in it not part of the host view which mean it's `ChangeDetectorRef` will not be part of of any change detection cycle. (also life cycle hooks will not work)
