### ISSUE TITLE
[changelog]: missing a few commits and breaking changes for `rc.2`?

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#9255]
If I'm not missing anything, 1745366530266d298306b995ecd23dabd8569e28 is in `rc.2` but not listed in the changelog, and, more importantly, not listed in the breaking changes.

Same for bc888bf3a102aa6bf62e134661022a9fdb5e2ff5

**Comment by pkozlowski-opensource** [comment]
How about a pull request?

**Comment by cexbrayat** [comment]
I was under the impression the changelog was generated automatically, so I was more pointing out a potential problem in the tool generating the changelog. But if that's a manual task, I can submit a PR, no problem.

**Comment by cexbrayat** [comment]
@tbosch related to these commits, specifying `platformDirectives: [NewDirective]` will replace the existing `COMMON_DIRECTIVES` instead of adding the new directive (like we did using `{ provide: PLATFORM_DIRECTIVES, useValue: [NewDirective], multi: true }`).

If this is the intended behavior (is it?), that should be mentioned in the breaking changes section.
What would be the correct way to do the same? `platformDirectives: [COMMON_DIRECTIVES, NewDirective]`?

**Comment by kylecordes** [comment]
Possibly related to #9264 I just put in?

**Comment by IgorMinar** [comment]
@StephenFluin looks like we missed these two breaking changes. Can you please add them manually?

we should also make sure that breaking changes from "refactor" commits are always included in the changelog. Can you please file an issue for that and add it to rc.3?
