### ISSUE TITLE
Include reverting commits in CHANGELOG.md

### ISSUE THREAD

**Issue by laco0416** [angular/angular#9256]
* **I'm submitting a ...**
- [x] feature request

**Current behavior**

Reverting commits are not included in CHANGELOG.md.
Then, unavailable feat changes only are in CHANGELOG. Users may become confused.

**Expected/desired behavior**

If there are reverting, those should be included in CHANGELOG.

**Comment by pkozlowski-opensource** [comment]
Or better yet - if reverted shouldn't show up in the changelog at all...

**Comment by IgorMinar** [comment]
@StephenFluin can you please fix this? thanks!

**Comment by StephenFluin** [comment]
We did another pass and removed more reverted changes. We've also added this as a standard step for generation of our changelog. Hopefully this will be better going forward.
