### ISSUE TITLE
[router]: RC2 router.navigateByUrl gives TypeError: Cannot read property 'map' of null

### ISSUE THREAD

**Issue by ajayambre** [angular/angular#9257]
* **I'm submitting a ...** bug report

**Current behavior**

Calling router.navigateByUrl() gives TypeError: Cannot read property 'map' of null.
This navigates to the url but clicking further links stops working

* **Plnkr Demo** http://plnkr.co/edit/LwlXsSsW3LKed5B2x0CG?p=preview
* In the demo, clicking on home navigates to ModuleComponent but then clicking on screen url does nothing

![image](https://cloud.githubusercontent.com/assets/5074211/16120633/c73fe400-33fd-11e6-8438-76c34ec7a480.png)

**Expected/desired behavior**

This works in RC1
* **Plnkr Demo** http://plnkr.co/edit/LkqKbaYXq1UtNQXlgrNp?p=preview

* **Angular version:** 2.0.0-rc.2 
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart]

**Comment by ericmartinezr** [comment]
Dup of https://github.com/angular/angular/issues/8667 and https://github.com/angular/angular/issues/8801. That router is abandoned anyway.

**Comment by ajayambre** [comment]
@ericmartinezr This worked in the new router in RC1. Also what does that mean _That router is abandoned anyway._.

**Comment by ericmartinezr** [comment]
@ajayambre the RC router, the one you're using is abandoned, no more fixes for it. The new new new router (https://github.com/angular/vladivostok) is the one everyone should be using now.

Reference

http://victorsavkin.com/post/145672529346/angular-router
http://angularjs.blogspot.cl/2016/06/improvements-coming-for-routing-in.html
https://github.com/angular/vladivostok

**Comment by ajayambre** [comment]
@ericmartinezr Thanks for the info. I like you saying new new new router. :+1: Turns out RC router is now router-deprecated and router-deprecated is actually router-deprecated-deprecated. :)

**Comment by cdcooksey** [comment]
@ajayambre It is in the change log under `2.0.0-rc.0 (2016-05-02)`.

**Comment by ericmartinezr** [comment]
@cdcooksey sadly nope, the refactorings they mention in RC.0 are part of the RC router, which is abandoned also. 

What I truly agree with is that this should be at least on the website with a huge red div saying 

- beta router is abandoned
- RC router is abandoned
- a new new new router is being written (a link to vladivostok and all references to the router : Victor blog, angularjs blog with the reasoning behind all these changes, etc)

**Comment by cdcooksey** [comment]
@ericcarraway  You mean like this?

![angular_changelog_md_at_master_ _angular_angular](https://cloud.githubusercontent.com/assets/1116789/16131309/d1923b0c-33ca-11e6-9256-22314e08fbb7.png)

![router__deprecated_beta__-_ts](https://cloud.githubusercontent.com/assets/1116789/16131356/0b79f864-33cb-11e6-80d9-8cee728dacdb.png)

**Comment by ericmartinezr** [comment]
Yes, like that

>angular2/router -> @angular/router-deprecated (snapshot of the component router from beta.17 for backwards compatibility)
new package: @angular/router - component router with several breaking changes

Those two routers `@angular/router-deprecated` and `@angular/router` are both abandoned. The problem here is when they say "release candidate component router" they're not talking about the vladivostok router, but the RC, which... well... you know, it was abandoned.

They are actually updating the guide, but the update is not for the RC router, you can see it here https://github.com/angular/angular.io/pull/1636

**Comment by IgorMinar** [comment]
yes, we are upgrading the guides. please use v3 router going forward.
