### ISSUE TITLE
bypassSecurityTrustHTML not rendering HTML

### ISSUE THREAD

**Issue by RicardoVaranda** [angular/angular#9258]
* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**
Sanitized html is returning an object

**Expected/desired behavior**
Rendered HTML

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co:
http://plnkr.co/edit/psbIFb65bh5woiODf4h7?p=preview

* **Please tell us about your environment:**
ricardo@Ricardo:~/WebstormProjects/TrialUI$ node -v
v6.2.1
ricardo@Ricardo:~/WebstormProjects/TrialUI$ npm -v
3.9.3

* **Angular version:** 2.0.0-beta.X 
 2.0.0-beta.RC1
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 ALL
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart] 
all

**Comment by zoechi** [comment]
This is not supposed to work. `{{}}` binding stringifies the value before assigning it.

```
 <span [innerHtml]="html"></span>
```
does what you want. http://plnkr.co/edit/ZMclWbmLn82PV8unxLwZ?p=preview

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by RicardoVaranda** [comment]
@zoechi does this work with components?

I'm trying to load a component in innerHTML but it doesn't seem to work.

**Comment by zoechi** [comment]
This doesn't work with any kind of binding. Components and directives are only instantiated for HTML statically added to the template. 
What you can use is `ViewContainerRef.createComponent()`. For an example see http://stackoverflow.com/questions/36325212/angular-2-dynamic-tabs-with-user-click-chosen-components/36325468#36325468
