### ISSUE TITLE
[animation]: RC2 Animation, AnimationBuilder Breaking Change?

### ISSUE THREAD

**Issue by coryshaw1** [angular/angular#9259]
```js
import {Animation} from "@angular/platform-browser/src/animate/animation";
import {AnimationBuilder} from "@angular/platform-browser/src/animate/animation_builder";
import {CssAnimationBuilder} from "@angular/platform-browser/src/animate/css_animation_builder";
```

I see that `@angular/platform-browser/src/animate/` has been removed, and there is now a few Animation related classes in `@angular/core`. The classes above are not in `@angular/core`, and have been removed altogether though.

Is this intended? If so, is there any sort of migrations we should know about?

**Comment by IgorMinar** [comment]
the animations previously stored under src/animate/.. were never publicly released. we were iterating on the animations apis and implementation still and only in rc2 we exposed the animation apis.

@matsko can add more info, but generally speaking please never import from `@angular/<packageName>/src/` as anything there is private and is not considered to be part of the public api surface.
