### ISSUE TITLE
How to access parent component regardless of the type of parent???

### ISSUE THREAD

**Issue by giancarloa** [angular/angular#9261]
Hello...

I am using angular2 rc2 with TS...

I have a textbox component (and others like it) that needs access to its parent component. The parent component can be of any type. The textbox component does not know ahead of time the type of parent component because it can be anything. I have seen a number of solutions to this problem (@Parent, forwardref, @Host) but they all require that the child component know ahead of time the type of the parent component. In my case this simply is not possible. Nor can I use a solution that entails changing the parent component (like making it implement an interface that the child component can later inject). Is there any way I can access the parent component whatever it may be without knowing its type ahead of time????? Is there any type I can inject into the child component (like ElementRef) through which I can indirectly access the parent component??? I remember in a beta version I could get a hold of the parent component through ElementRef (elementRef.internalElement.parentView.context) but I am not sure how safe this is... any ideas??? Many thanks

**Comment by ericmartinezr** [comment]
@Host doesn't require to now about the type of the parent. If you don't know simply use a service. See https://angular.io/docs/ts/latest/cookbook/component-communication.html

Also see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by giancarloa** [comment]
thank you @ericmartinezr ... but as I mentioned above the solution cannot involve having to change the parent and the service solution requires this... 

i will ask the question in the appropriate forum... thank you

**Comment by zoechi** [comment]
Looks like a dup of #8277

**Comment by giancarloa** [comment]
@zoechi ... thank you... yes it does look like the same sort of issue... if I read the thread correctly, it's an unanswered question correct???? I see a workaround listed but it seems like an unsupported solution...

**Comment by zoechi** [comment]
exactly

**Comment by giancarloa** [comment]
hello @zoechi ... hello @ericmartinezr .... with the recent release of ng2 does anyone know if there's a solution to this problem??? thanks
