### ISSUE TITLE
EXCEPTION: No Directive annotation found on ArticleCompontent

### ISSUE THREAD

**Issue by tyroneLord** [angular/angular#9262]
I am working from the ng-book-2 for angular i am getting this issue but not sure why. below is my code.

import { bootstrap } from "angular2/platform/browser";
import { Component } from "angular2/core";

@Component({
	selector: 'reddit-article',
	// host creates the css class or row ont eh reddit-article tag we created
	host:{
		class: 'row'
	},
	template: `
	<div class="four wide column center aligned votes">
		<div div class="ui statistic">
			<div class="value">
				{{ article.votes }}
			</div>
			<div class="label">
				points
			</div>
		</div>
	</div>
	<div class="twelve wide column">
		<a href="{{ article.link }}" class="ui large header"> {{ article.title }}</a>
		<ul class="ui big horizontal list voters">
			<li class="item"> <a href (click)="voteUp()"><i class="arrow up icon"></i> upvote</a></li>
			<li class="item"> <a href (click)="voteDown()"><i class="arrow down icon"></i> downvote</a></li>
		</ul>
	</div>
	`
})

class Article{
	title: string;
	link: string;
	votes: number;

	constructor(title: string, link: string, votes?:number){
		this.title = title;
		this.link = link;
		this.votes = votes || 0;
	}
}

class ArticleCompontent {
	article: Article;

	constructor() {
		// this.title = 'Anglur 2';
		// this.link = 'httt://espn.com'
		// this.votes = 10;
		this.article = new Atricle('Angular 2', 'http://ign.com', 10);
	}

	voteUp(){
		this.article.votes += 1;
		return false;
	}

	voteDown(){
		this.article.votes -= 1;
		return false;
	}
}

@Component({
	selector: 'reddit',
	directives: [ArticleCompontent],
	template: `
	<form class="ui large form segment">
		<h3 class="ui header"> Add a Link</h3>
		<div class="field">
			<label for="title"> Title</label>
			<input name="title" #newtitle>
		</div>
		<div class="field">
			<label for ="link"> Link</label>
			<input name="link" #newlink>
		</div>
		<button (click)="addArticle(newtitle, newlink)" class="ui positive right floated button">
			submit link
		</button>
	</form>
	<div class="ui grid posts">
		<reddit-article></reddit-article>
	</div>
	`
})

class RedditApp{
	constructor(){

	}
	addArticle(title: HTMLInputElement, link: HTMLInputElement): void{
		console.log(`Adding article title: ${title.value} and link: ${link.value}`)
	}
}

bootstrap(RedditApp);

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

If you still think it's a bug, then please post a Plunker that allows to reproduce.

**Comment by tyroneLord** [comment]
oh sorry i will close the issue'
