### ISSUE TITLE
Angular 2 RC 2 New Forms

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular#9263]
Hi,

As suggested in article
 https://docs.google.com/document/u/1/d/1RIezQqE4aEhBRmArIAS1mRIZtWFf6JxN_7B4meyWK0Y/pub

that in order to use new forms in RC2 we need to disable deprecated forms using below code:

```
import {disableDeprecatedForms, provideForms} from '@angular/forms';
bootstrap(AppComponent, [
   disableDeprecatedForms()
   provideForms()
])
```

Which apparently means that we now also need to include below in our package.json:

`"@angular/forms": "2.0.0-rc.2",`

But when I add "@angular/forms": "2.0.0-rc.2", to my package.json and try to restore packages it gives below errors:

```
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! No compatible version found: @angular/forms@2.0.0-rc.2
npm ERR! Valid install targets:
npm ERR! 0.1.0
```

Can anyone please guide?

**Comment by vicb** [comment]
The forms package versiob is decoupled, you should use 0.1.0 for now, see https://www.npmjs.com/package/@angular/forms

@kara please correct me if I'm wrong

**Comment by naveedahmed1** [comment]
Thank you Victor, it worked!
