### ISSUE TITLE
Which commit is RC.2?

### ISSUE THREAD

**Issue by kylecordes** [angular/angular#9264]
I see the blog post, I see rc.2 on NPM.

Great!

But looking at the repository right here I see the package file is still labeled as rc.1. I was guessing that we would see a commit right here around the time of the official drop, and that would mark the point that is rc.2. But I haven't seen it yet, makes me wonder if either there is still some rc.2 work in progress (is the thing in NPM now, going to change?) or if it just got missed.

**Comment by CarlCui** [comment]
See https://github.com/angular/angular/releases

**Comment by kylecordes** [comment]
Ah, very good, thanks. So this item is just a reminder to update what it says in package.json:

https://github.com/angular/angular/blob/master/package.json

**Comment by IgorMinar** [comment]
the root package.json is not the source of truth for version numbers. there is an issue open to better deal with versioning and npm publishing: https://github.com/angular/angular/issues/9233

I also [updated](2b1ac63e3a7e1baa0cd05534ca21f103ea9dcb31) the package.json just to prevent more confusion in the meantime.
