### ISSUE TITLE
StaticReflector reports 'call not supported' if a class uses a custom decorator.

### ISSUE THREAD

**Issue by chuckjaz** [angular/angular#9265]
* **I'm submitting a ...**
```
[x] bug report
```

**Current behavior**

When getting metadata statically for a type such as:

```typescript
export class Foo {
  @CustomDecorator() get foo(): string { return ''; }
}
```

the static reflector reports `Unsupported function call ...`.

**Expected/desired behavior**

The custom decorator should be ignored.

**Comment by vicb** [comment]
@chuckjaz could you please update the milestone when the fix is expected ? Thanks
