### ISSUE TITLE
Strange bahaviour in Router.subscribe()

### ISSUE THREAD

**Issue by MasDevProject** [angular/angular#9269]
Hi guys,
migrating from Rc1 to Rc2 I got a strange behaviour.

Using Rc1 the argument of Router.subscribe method was a string rapresenting the complete url of the next state:
For example:
```
public constructor (private _router:Router, private _location:Location) 
{
   _router.subscribe (next =>
         console.log (next);
   );
}
```
was returning `main/course-details`
but now `next` is a `ComponentInstruction` and it does not consider the sub paths.
For example I have a path like this: `http://localhost:2020/main/course-details`
`main` is a state, and `course-details` is its sub state.
Navigating to  `course-details` I always get the same `instrcution`:
```
routeName:"Main"
specificity:"2"
terminal:false
urlParams:Array[0]
length:0
__proto__:Array[0]
urlPath:"main"
```
so I cant retrive the real complete path. In my application I need to know understand what component will be displayed in the state change

* **Angular version:** 2.0.0-rc2 
 
* **Browser:** [all] 
 
* **Language:** [TypeScript 1.8]

**Comment by kemsky** [comment]
Temp fix is to use `router.currentInstruction`.

This is breaking change but it was not documented. Also initialization/event order seems to be changed.

**Comment by ericmartinezr** [comment]
Guys, beta router and RC router are both abandoned, they won't be fixed. The new new new router is what you should be using

Reference

http://victorsavkin.com/post/145672529346/angular-router
http://angularjs.blogspot.cl/2016/06/improvements-coming-for-routing-in.html
https://github.com/angular/vladivostok

unless I'm misunderstanding this issue and you refer to the vladivostok router.

**Comment by IgorMinar** [comment]
@ericmartinezr is right. I think you are accidentally using the rc.2 router which is the last router 2.0.0-rc.x release (it primarily removes the peerDependency constraint so that you can update to rc.2 without having to jump to router v3). Please use router v3 going forward.
