### ISSUE TITLE
Add support for Component @Children injection

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#927]
This is a nice-to-have for container components that are responsible for configuring / interacting with the contained components. Currently, the child Component has to inject the `@Parent` and register/deregister itself manually.

**Comment by naomiblack** [comment]
This is a dup of #792. @rkirov can you own?

**Comment by rkirov** [comment]
Yes, closing as a dup. #792 has a pending PR, but waiting for the rendering rewrite to land.
