### ISSUE TITLE
rc2 router.d.ts file missing constructor definition

### ISSUE THREAD

**Issue by stonecat9** [angular/angular#9270]
* **I'm submitting a ...**
- [X ] bug report

**Current behavior**
The router.d.ts file located at @angular/router/src/router.d.ts is missing the definition for the Router's constructor. I think that this line needs to be added to the file:

 constructor(_rootComponent: Object, _rootComponentType: Type, _componentResolver: ComponentResolver, _urlSerializer: RouterUrlSerializer, _routerOutletMap: RouterOutletMap, _location: Location);

This was present in rc1.

**Expected/desired behavior**

I'm currently extending the router so I get a Typescript warning when I try to pass in arguments to the constructor, since Typescript thinks that the constructor should take 0 arguments. However, the Router still requires all of these arguments to be passed in.

* **Please tell us about your environment:**

Angular version: 2.0.0-rc2
 
Browser: Chrome
 
Language: Typescript

**Comment by antonybudianto7** [comment]
https://www.npmjs.com/package/%2540angular%2Frouter

it's **3.0.0-alpha.6** now, 2.0.0 is deprecated
https://angularjs.blogspot.co.id/2016/06/improvements-coming-for-routing-in.html
