### ISSUE TITLE
Router v3.0.0-alpha.6 by vsavkin

### ISSUE THREAD

**Issue by aquinum6** [angular/angular#9271]
Router package of one of your contributors seems to override RC2 in npm as a new version. So no longer you can find RC2 as current on npm.

[Router v3.0.0-alpha.6](https://github.com/angular/vladivostok)
[npm search result of: angular router](https://www.npmjs.com/search?q=angular+router)
[npm search of "@angular/router"](https://www.npmjs.com/search?q=%40angular%2Frouter)
[npm google result of search: "npm @angular"](https://www.npmjs.com/~angular)

Is that's correct and this router version should be current or not ??

**Comment by MarkPieszak** [comment]
Isn't the router-v3 supposed to be the new (replacing) router?

**Comment by ericmartinezr** [comment]
Yes, the vladivostok router is the new new new router. The beta and RC router are both abandoned.
