### ISSUE TITLE
Unable to update the state of checkbox even if ng-nodel is changed

### ISSUE THREAD

**Issue by IamKritika** [angular/angular#9272]
I am trying to implement "select all" checkbox through angular 2. 

I have a list of checkboxes and one select all checkbox. And in my use case it's so that if user checks all checkboxes from the list manually , I have to uncheck all the checkboxes from the list and check the "All" checkbox. So I have binded a ngModel and ngModelChange to all the checkboxes .Now what happens is if I try to update the ngModel in the ngModelChange method ,the state of checkbox is not changed even though the ngModel value is updated (since angular2 listens to events only and not to change in value of ngModel). I have tried to achieve this through the attribute directive as well but nothing seems to work.

Can someone help me in doing this?

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)
