### ISSUE TITLE
ngFor asnyc subscription cleanup leaks

### ISSUE THREAD

**Issue by conartist6** [angular/angular#9274]
* **I'm submitting a ...**
- [X ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**

When using the async helper inside ngFor when ngFor is displaying content from an array of size greater than one, then the host element is destroyed: one subscription is leaked. See plunkr.

**Expected/desired behavior**

No subscriptions are leaked.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
http://plnkr.co/edit/71fAIjAvbALthwNxW44t?p=preview

Expected plunker final output:
[ -1, -1, -1, 0, 0, 0, 1, 1, 1 ]

Actual plunker final output:
[ -1, -1, -1, 0, 0, 0, 1, 1, 1, 2, 3, 4 ...]

* **Angular version:** 2.0.0-RC1
 
* **Browser:** [all] (tested Chrome 50, Firefox 44)
 
* **Language:** [all] (tested TypeScript, ES5)

**Comment by conartist6** [comment]
My first question is: is it only failing to clean up observers, or is it also leaking elements?

**Comment by zoechi** [comment]
sounds like #9190

**Comment by conartist6** [comment]
Why yes it does. I looked, but I guess I was only looking at open issues. Oops.
