### ISSUE TITLE
Share Angular 1.x Google Groups or create new ones?

### ISSUE THREAD

**Issue by chalin** [angular/angular#928]
We currently have the following **Google groups**:
* angular-dart: [#!forum/angular-dart](https://groups.google.com/forum/#!forum/angular-dart).
* AngularJS: [#!forum/angular](https://groups.google.com/forum/#!forum/angular).
* angular-dev (for JS): [#!forum/angular-dev](https://groups.google.com/forum/#!forum/angular-dev).

@mhevery et al.: With contributions to Angular 2 picking up, where do you suggest we direct user and developer questions? I see three options:

1. Reuse the 1.x groups for 2.x posts.
2. Create a single Angular 2 group (though this seems to go contrary to Igor's guidelines [ACG] ).
3. Create two Angular 2 groups; one for JS and one for Dart.

Option 1 seems reasonable but on the flip side, AngularJS already generates quite some traffic just for 1.x issues. 

This question of discussion groups came up as I was editing [CONTRIBUTING.md](https://github.com/angular/angular/blob/master/CONTRIBUTING.md). This isn't a big issue, but if new groups are to be created, it might as well be done sooner than later. Either way, I'll tweak CONTRIBUTING.md based on your answer.

-----

[ACG] [**Angular Communication Guidelines**, section on "Communicating about JS and Dart"](https://docs.google.com/document/d/18cXfy3I94llOA7iDuTmW7yxEcPcjgFwCjgMamDCLi4I/edit#heading=h.8nybdvybnp48), Igor writes:
> JavaScript developers usually don't care about Dart. Dart developers usually don't care about JavaScript. We support both JavaScript and Dart, but ... it's better to tailor communication for these two groups. In practice this means, having separate docs for JS and Dart.

**Comment by gdi2290** [comment]
join [gitter/angular](https://gitter.im/angular/angular)

**Comment by chalin** [comment]
:) thanks, I am on gitter, but IMHO, it is no replacement for a discussion list. Misko, any opinion?
/cc @mhevery

**Comment by gdi2290** [comment]
github is the discussion list ;)

**Comment by mhevery** [comment]
@naomiblack Sounds like we should have another google group. What do you think?
