### ISSUE TITLE
With new forms api, can't add inputs from child components without adding additional form tags

### ISSUE THREAD

**Issue by qdouble** [angular/angular#9281]
**I'm submitting a ...**  (check one with "x")
- [x] bug report

**Current behavior**
With the new forms api, can't load input from child component without including an additional forms tag. Will get error >VM65345 angular2-polyfills.js:487Unhandled Promise rejection: Template parse errors:
No provider for ControlContainer

**Expected/desired behavior**
Should be able to load inputs from child component without adding additional form tags. 

**Reproduction of the problem**
http://plnkr.co/edit/5KGrEHM4QzoSLLo2b8oQ?p=preview

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.2
 
* **Browser:** [all ] 
 
* **Language:** [TypeScript]

**Comment by IgorMinar** [comment]
Are you trying to generate the forms dynamically? like how http://angular-formly.com/ works?

**Comment by qdouble** [comment]
@IgorMinar Yes, I'm trying dynamically add form fields...not exactly the way they do it in that link, but just in a way that I can reuse the html template and validation setup. It worked in the previous api.

I was going to use the formArray but that's not fully implemented yet. So there seems to be no proper way to create dynamic forms currently.

**Comment by thelgevold** [comment]
I have converted my dynamic form over to the new api and from what I can tell it's working.

I believe it's still a requirement that you have to "ferry in" the formGroup instance to the child component and assign it to a parent of any form control in the child component.

It doesn't have to be a form tag though - but can't be added directly on the form control itself.

You could remove the nested form tag and do this instead:

```
<div [formGroup]="form"> //must be on the parent, but any tag will do
  <input  [formControlName]=controlName>
 </div>  
```

The old form module had this same requirement.

**Comment by qdouble** [comment]
@thelgevold Thanks, putting formGroup in div tags does work.

However, I was able to add inputs from a child component without any extra divs this way in the past => http://plnkr.co/edit/wSP0MHXkvbj64KJmfVFN?p=preview

**Comment by thelgevold** [comment]
@qdouble So the reason it works in your old forms sample is that you are using ngFormControl which doesn't require a form at all. If you switch it to use ngControl it won't work anymore. 

Your new sample uses formControlName which is the new ngControl. Based on that the two examples aren't totally equivalent. 

My experience is that dynamic forms are easier if you stick to ngControl (old api ) and formControlName (new api)... Mainly because I find it easier to deal with the names and not the actual control instances when I am defining the form dynamically. The names typically map to property names in my object model, so it's handy that the forms can associate controls by name.

Thant said, your original sample can be tweaked to avoid the formGroup on the div in the child component. 

Here is a modified version of your plunker showing how to do it:
http://plnkr.co/edit/FDE4VoW8YqruxZQB9eqR?p=preview

The key to this is building the formGroup dynamically

```
    let group = {};
     
    group.name = new FormControl('some name');
    group.email = new FormControl('some email');
    
    //Showing how to add it dynamically
    group[this.controlName] = new FormControl('Joe');
     
    this.form = new FormGroup(group); 
``` 

You can then look up the control instances via name in the child component.

``` this.dynamicControl = this.form.controls[this.controlName]; ```

@IgorMinar and @qdouble @kara 
I will leave it to you to comment, but my view is that this behavior is at least consistent with the old forms api, so I'm not sure it's a bug.

**Comment by bzums** [comment]
@thelgevold what if we have a nested data structure, for example something like this:
http://plnkr.co/edit/VL0uWMHTuFY2dt4WrzUe?p=preview

It feels unnatural to pass the form control group to each of the child elements, doesnt it?
Or am I thinking to complicated anyway?

And I think it is common not to use the input element directly but a custom component instead because one wants to abstract common behaviour on input element like visual information concerning validation etc.

**Comment by thelgevold** [comment]
@bzums I agree, it's a bit cumbersome. Would be a nice enhancement to remove this requirement

**Comment by benelliott** [comment]
I'm having a lot of trouble implementing something analogous to @thelgevold's solution with template-driven forms. Does anyone have any hints for that?

**Comment by qdouble** [comment]
@thelgevold your solution works good enough for my purposes. Thanks. They may still want to consider adding this to the docs or making it so that formControlName also works.

**Comment by fis-dan-wnuk** [comment]
I have a similar question as benelliott - for template driven forms what is the best way to get controls in children component recognized by a parent form?

My current 'workaround' is to put a form in each child component, and once that form becomes valid it outputs an event to the parent component which can then do what it needs to do once all the children have said they are valid. I don't think this is the correct approach and put out a question on StackOverflow (http://stackoverflow.com/questions/38000438/how-do-i-get-controls-in-sub-components-recognized-in-a-parent-form-angular2-r) but haven't gotten any recommendations.

Sorry if this isn't the appropriate place - let me know if I should open another issue for this question.

**Comment by linusbrolin** [comment]
I have a form with a table where each tr row is a FormGroup.
The tr row for this is a separate child component, with a 'tr[component-name]' selector.
This means that the template in that child component does not have parent tag where I can put the [formGroup]="form" information.
The child component template only contains an outer template tag, for handling [ngIf] statements, and then td tags within that, where each td tag has a formControlName="name".

The parent table looks kinda like this, where 'childObjects' is a formArray containing formGroups:

    <table>
      <thead>
        <tr>
          <th>Width</th>
          <th>Height</th>
        </tr>
      </thead>
      <tbody>
        <tr childobject-row
          *ngFor="let o of childObjects; let i = index"
          [(formGroup)]="formGroup.find('childObjects').controls[i]"
          [locked]="false">
        </tr>
      </tbody>
    </table>

The child component template look kinda like this:

    @Component({
      selector: 'tr[childobject-row]',
      template: `
      <template [ngIf]="!locked"> 
        <td>
          <input type="number" formControlName="width">
        </td>
        <td>
          <input type="number" formControlName="height">
        </td>
      </template>
      `
    })


How can I get this to work with the new @angular/forms?

**Comment by kara** [comment]
When you create a custom form control, it will work to ferry in the formGroup instance, but in my opinion it's easier to implement the ControlValueAccessor interface.  That way, you don't actually have to pass anything into your child component, and the custom form control is treated just like any other form control in your form.

The ControlValueAccessor interface is actually what we use to build value accessors for radio buttons, selects, etc in core. It just requires three methods:  
- `writeValue(value: any): void` : takes a value and writes it to the form control element (model -> view)
- `registerOnChange(fn: (value:any) => void): void`: takes a function that should be called with the value if the value changes in the form control element itself (view -> model)
- `registerOnTouched(fn: () => void)`: takes a function to be called when the form control has been touched

The key here besides implementing the interface is to provide it to NG_VALUE_ACCESSORS. This is what ngModel and formControlName will inject, so they can be registered as part of the parent form.

See example here: http://plnkr.co/edit/gZgOk87qAXSKfMtIztY4?p=preview

I'm closing, as there is a way to do this already.

**Comment by qdouble** [comment]
@kara thanks...I've been user your plunker example...but have one question. Will we have memory leaks if we don't unsubscribe to the subscription you put here?
```
registerOnChange(fn: (value: any) => void) {
    this.childControl.valueChanges.subscribe(fn);
  }
```

**Comment by salmansgit** [comment]
ControlValueAccessor for the formGroup or formArray, I am implementing a ControlValueAccessor for child component having multiple form controls.
I want to apply validators in child control only. If I pass formGroup as an input it won't work with ngModel.

http://plnkr.co/edit/jhhRS1iLonC8hHO69o8U?p=preview

**Comment by jeremyputeaux** [comment]
I would like to do almost the same thing as @salmansgit .
I juste need fields to be dynamic. I've posted a messages on stackoverflow [here](http://stackoverflow.com/questions/40619315/build-a-reactive-form-where-fields-values-are-populated-in-childrens-component).
It would be nice to have an answer on this.

**Comment by astreate** [comment]
@kara Your solution sounds great if we are implementing a single custom form control, but what if we have a form on a top level component, then there are several subcomponents that have multiple form fields in them?  Will your solution work then?  Do I have to make a custom component for each form field?  How do I know if my top level form is dirty when a form control in a subcomponent is changed?

Thanks in advance for your help!

**Comment by bzums** [comment]
@jeremyputeaux @astreate @salmansgit 
I currently use the approach described here: https://github.com/angular/angular/issues/9600#issuecomment-278915107
...which I think would fit your needs?!

@kara do you see problems with that approach?

**Comment by scottseeker** [comment]
I found in the end that when breaking a form across components it was easier for me to actually keep a handle on the FormGroup/FormControl objects and use [formGroup]= && [formControl]= then it was to try to find a work around to use formGroupName && formControlName.

I can now dynamically generate a form with infinitely (resources allowing) nested arrays/objects of form controls.

**Comment by squadwuschel** [comment]
@kara what about the multicontrol components mentioned by @astreate is there a solution avaible?

**Comment by JavanXD** [comment]
@squadwuschel if you have multiple sub components you can use the viewProviders as mentioned here: https://medium.com/@a.yurich.zuev/angular-nested-template-driven-form-4a3de2042475
Take a look at this thread: #9600

**Comment by yadavbharat** [comment]
k'
