### ISSUE TITLE
Getting error after upgrade to rc2

### ISSUE THREAD

**Issue by haarabi** [angular/angular#9289]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
![image](https://cloud.githubusercontent.com/assets/2755929/16139511/0c2bfbc2-33fd-11e6-9cce-186b7bb3182f.png)

**Expected/desired behavior**
no four oh four

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.2
 
* **Browser:** [all] 
 
* **Language:** [TypeScript 1.8.10]

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes

>Bundles are now in the bundles/ subdirectory within each package

**Comment by haarabi** [comment]
I am running the Quick Start from angular.io. 

I confirm this error is related to rc2. When I downgrade to rc1 everything works as expected.

Can you please provide directions or point me to documentation on how to refactor?

My package.json:

![image](https://cloud.githubusercontent.com/assets/2755929/16139748/9298b2ac-33ff-11e6-9bc1-fca785be8d30.png)



-H

**Comment by ericmartinezr** [comment]
@haarabi 

if you look at the official plnkr template (https://angular.io/resources/live-examples/quickstart/ts/plnkr.html) there's this line

```
    packages['@angular/'+pkgName] = { main: '/bundles/' + pkgName + '.umd.js', defaultExtension: 'js' };

```
note that `/bundles/` part of the path. In your systemjs config you should do the same. Can you post your systemjs config?  Even better, you can post it here https://gitter.im/angular/angular

**Comment by haarabi** [comment]
Great, thanks!

adding the bundles path in the the systemjs.config.js fixed the issue.

before:
![image](https://cloud.githubusercontent.com/assets/2755929/16140001/c95942b4-3401-11e6-90b8-f52eb1a64a4a.png)


after:
![image](https://cloud.githubusercontent.com/assets/2755929/16139987/b8d28928-3401-11e6-993b-91801e6fe8a2.png)

-H
