### ISSUE TITLE
transpiler: use traceur's implementation of parseObjectType

### ISSUE THREAD

**Issue by tbosch** [angular/angular#929]
Right now we are implementing `Parser.parseObjectType_` ourselves.
This is not needed any more as upstream traceur supports it now, although with a different implementation. So:

1. remove our hack
2. rewrite the places where we use object types into the format that traceur uses (a list of types, instead of an object hash)

**Comment by tbosch** [comment]
Our implementation: https://github.com/angular/angular/blob/master/tools/transpiler/src/parser.js#L12
Traceur's implementation: https://github.com/google/traceur-compiler/blob/832b12dea3a9e6de7ff9da0e26d91b4088369140/src/syntax/Parser.js#L4073

**Comment by tbosch** [comment]
Note: This should be already possible with the traceur version that we are using, so no need to upgrade traceur to solve this

**Comment by robwormald** [comment]
ahhh, just ran into this while trying to get bundling working.

Can you maybe note what the correct syntax is? Don't know if it still applies moving to TS, but I might just back and fix them anyway so we can bundle in the meantime.

**Comment by mhevery** [comment]
obsolete.
