### ISSUE TITLE
lang.ts JSON.parse error catch

### ISSUE THREAD

**Issue by fedu** [angular/angular#9296]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
```
// Can't be all uppercase as our transpiler would think it is a special directive...
export class Json {
  static parse(s: string): Object { return _global.JSON.parse(s); }
  static stringify(data: Object): string {
    // Dart doesn't take 3 arguments
    return _global.JSON.stringify(data, null, 2);
  }
}
```

**Expected/desired behavior**
```
// Can't be all uppercase as our transpiler would think it is a special directive...
export class Json {
  static parse(s: string): Object {
    try {
      var json = _global.JSON.parse(s);
      return json;
    } catch(e) {
      throw 'Invalid JSON data format.';
      return e;
    }
  }
  static stringify(data: Object): string {
    // Dart doesn't take 3 arguments
    return _global.JSON.stringify(data, null, 2);
  }
}
```

**Reproduction of the problem**
VM55728:229 Uncaught SyntaxError: Unexpected token p in JSON at position 10978Json.parse @ lang.ts?aa55:421Response.json @ static_response.ts?158c:104

**What is the expected behavior?**
To catch JSON.parse errors gracefully.

**What is the motivation / use case for changing the behavior?**
Network data can cut in half because of server fails.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.1
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart]

**Comment by pkozlowski-opensource** [comment]
> To catch JSON.parse errors gracefully.

What is the situation under which you are getting this exception? By using the `JsonPipe` (in this case the request sounds reasonable) or in a different situation?

**Comment by IgorMinar** [comment]
@pkozlowski-opensource if it's in JsonPipe then we should do this handling there. Otherwise we should not do anything because if JSON payload is invalid then we should just throw whatever the platform specific error is.

**Comment by IgorMinar** [comment]
@fedu can you please open a new issue with higher level use-case. If the error is coming from http and jsonpipe then we should handle these errors there and not in lang.ts. thanks!

**Comment by pkozlowski-opensource** [comment]
@IgorMinar I'm it total agreement - this is exactly why I've asked the question.
