### ISSUE TITLE
:after and :before Styles Do Not Follow Defined Animations

### ISSUE THREAD

**Issue by sqwk** [angular/angular#9297]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
```

**Current behavior**

When animating an element with a `:after` element to or from the `void` state, the `:after`element is shown after and hidden before the animated main element.

**Expected/desired behavior**

`:after` and `:before` elements should be animated with the same timing as the parent element.

**Reproduction of the problem**

    ...
    template: `
    <div>
        <h2 @someState="state">Hello</h2>
    </div>
    `,
    trigger('someState', [
        transition('void => foo', [
            style({
                transform: 'translateX(-100%)'
            }),
            animate('3000ms ease-out')
        ]),
        transition('foo => void', [
            animate('3000ms ease-in', style({
                transform: 'translateX(-100%)'
            }))
        ]),
    ]),
    ...

.

    // Styles
    h2 {
        font-size:1rem;
        display:inline-block;
    }
    h2:before {
      display:inline-block;
      content: '';
      width: 2em;
      height:2em;
      background:#ccc;
    }

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.2
 
* **Browser:** Chrome 50.0.2661.102
 
* **Language:** TypeScript 1.8.10

**Comment by sqwk** [comment]
Is there a chance that this makes it into RC5?

**Comment by matsko** [comment]
Hey is there any way you can test against master right now? I'm running this locally and I can't seem to find the issue you're talking about: https://plnkr.co/edit/KDf4wyRsPl7EZzc5TnJY?p=preview

**Comment by sqwk** [comment]
It turns out that the problem might not be animation related: https://plnkr.co/edit/yRJMxusFe1ZjzgBfgttJ?p=preview

I added an `[(ngStyle)]` that adds the class on which the before and after elements are set. This class disappears before the element could animate out.

**Comment by matsko** [comment]
@sqwk did you mean `ngClass`? We fixed an issue with `ngClass` #10303 in master. http://plnkr.co/edit/414ar3acXpHymiPrSeun?p=preview

**Comment by sqwk** [comment]
Yes, `ngClass`. Got the two confused. Will #10303 make it into RC5?

**Comment by matsko** [comment]
Yessir

**Comment by sqwk** [comment]
Cool, in that case we can probably close this?
