### ISSUE TITLE
Property 'supports' is private and only accessible within class 'DatePipe'.

### ISSUE THREAD

**Issue by DenisVuyka** [angular/angular#9299]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
`supports` function is marked as private in rc.2

**Expected/desired behavior**
`supports` function should be public

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.2
 
* **Browser:** [all] 
 
* **Language:** [TypeScript 1.8.10]

**Comment by zoechi** [comment]
https://github.com/angular/angular/blob/f39c9c9e75671a7e235734b6b8aef263f6dff254/modules/%40angular/common/src/pipes/date_pipe.ts#L116

**Comment by pkozlowski-opensource** [comment]
> supports function should be public

Why? What would be the justification? Please note that we want to keep the public API surface to the minimum so there need to be a good reason of enlarging this surface.

**Comment by DenisVuyka** [comment]
[Public docs](https://angular.io/docs/ts/latest/api/common/index/DatePipe-class.html) still reference `supports` as public member. 

We are using DatePipe programmatically in complex components, i.e.

```ts
import { DatePipe } from '@angular/common';
...
let datePipe = new DatePipe();
if (datePipe.supports(value)) {
  return datePipe.transform(value, col.format);
}
```

Where format pattern is dynamically created or known at runtime only.

What is the justification for making it private at rc2 stage?

**Comment by pkozlowski-opensource** [comment]
@IgorMinar it was flagged as private in 70d944a59cb0f7aa15c49d24b4fb0b4483c8607d but seems like docs don't reflect this change.

**Comment by IgorMinar** [comment]
We are updating the docs. the `support` method is an implementation detail. If you have a need to imperatively determine if a pipe supports certain input then please file a new feature request and explain your use-case. Thanks!
