### ISSUE TITLE
New router (3.0.0-alpha.6) not working with web workers

### ISSUE THREAD

**Issue by datrinh** [angular/angular#9300]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Throwing error during runtime: `ORIGINAL EXCEPTION: not implemented`

**Expected/desired behavior**
Working router with angular 2 in web worker 

**Reproduction of the problem**

1. Set up bootstrapping angular 2 on web worker like so: https://github.com/angular/angular/tree/master/modules/playground/src/web_workers/kitchen_sink
2. Add and use `"@angular/router": "3.0.0-alpha.6"`

**What is the expected behavior?**
Working without errors.

**What is the motivation / use case for changing the behavior?**
Using web workers with the new router

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.2
 
* **Browser:** all 
 
* **Language:** TypeScript

**Comment by pkozlowski-opensource** [comment]
If it is already opened in https://github.com/angular/vladivostok there is no need to duplicate it here.
