### ISSUE TITLE
Is Formbuilder (etc) deprecated?

### ISSUE THREAD

**Issue by vapits** [angular/angular#9301]
Hi there this si more a question than a bug a bug (I hope) but it is not stackoverflow related also...

I can't find infos in the docs but if you follow the current docs and try to import the `FormBuilder`, `Validators` etc from the `@angular/common` you get an error.

So if I do this:
```
import { FormBuilder, Validators } from '@angular/common';
```
I get this:
```
[ts] Module '"/Projects/Jexia/WebApp/node_modules/@angular/common/index"' has no exported member 'FormBuilder'.
```

Same for validator etc.

Is FormBuilder deprecated or is it moved outside `@angular/common` ?

**Comment by Fank** [comment]
use `@angular/forms` instead of `@angular/common`

**Comment by vapits** [comment]
I just saw the 
```
import {provideDeprecatedForms} from '@angular/common';
bootstrap(AppComponent, [
   provideDeprecatedForms()
])
```
option. Thx.
