### ISSUE TITLE
NgUpgrade Incorrectly Transcludes Children When Using Multiple <ng-content/>s

### ISSUE THREAD

**Issue by noamichael** [angular/angular#9302]
- **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**
 When using ngUpgrade, the &lt;ng-content&gt; tag always transcludes children to the first occurrence of the tag, regardless of the select attribute.

**Expected/desired behavior**
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
  http://plnkr.co/edit/6Oc9fyw3u62QPntkiNRb?p=preview
- **What is the expected behavior?**

The excepted behavior would be for angular to read the select attribute of a given  &lt;ng-content&gt; to determine what content should be transcluded.
- **What is the motivation / use case for changing the behavior?**

This feature is crucial for components who format their children; panels, tabs, and menus are all effected by this glitch.
- **Please tell us about your environment:**
  Project is built with gulp. Typescript files are loaded and transpiled in browser with JSPM.
- **Angular version:** 2.0.0-rc-2 AND 1.5.6
- **Browser:** all
- **Language:** all

**Comment by kseamon** [comment]
This is fixed by #9538

**Comment by gkalpak** [comment]
As pointed out by @kseamon, this has been fixed for a while now. Please open new issues if you run into specific transclusion/projection-related issues.
