### ISSUE TITLE
[compiler] Compiler config overrides default platform pipes and directives

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#9303]
**I'm submitting a ...**  (check one with "x")
```
[X] feature request
```

**Current behavior**

This is regarding the last breaking changes in rc.2 about `PLATFORM_PIPES/PLATFORM_DIRECTIVES`.

Specifying `platformDirectives: [NewDirective]` will replace the existing `PLATFORM_DIRECTIVES` instead of adding the new directive (like we did using `{ provide: PLATFORM_DIRECTIVES, useValue: [NewDirective], multi: true }`).

So I guess the correct way to do the same would be `platformDirectives: [COMMON_DIRECTIVES, NewDirective]`? But doing this we also lose the default `platformPipes` (they are initialize with an empty array if not provided), so to replace:

`{ provide: PLATFORM_DIRECTIVES, useValue: [NewDirective], multi: true }`

we have to do:

`{ provide: CompilerConfig, useValue: new CompilerConfig({ platformPipes: [COMMON_PIPES], platformDirectives: [COMMON_DIRECTIVES, NewDirective] }) }`

Which is extra verbose and error prone.
Maybe we could have a nicer syntax, that would augment the default pipes and directives, rather than replacing them? Is `PLATFORM_DIRECTIVES` going to be deprecated or can we still use it?

cc @tbosch (sorry if I missed something obvious)

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.2
 
* **Browser:** [all ] 
 
* **Language:** [TypeScript 1.9]

**Comment by mhevery** [comment]
We need to be able to control the compiler from `tsconfig.json` like so:

```
{
  "angularCompilerOptions": {
    "skipTemplateCodegen": false,
    "genDir": "../dist",

    // Configure offline compiler
    "defaultEncapsulation": "Emulated",
    "genDebugInfo": true, 
    "logBindingUpdate": false, 
    "platformDirectives": [ "@angular/common:PLATFORM_DIRECTIVES" ], 
    "platformPipes": [ "@angular/common:PLATFORM_PIPES" ],
  },
  "compilerOptions": {...}
}
``` 

where `@angular/common:PLATFORM_DIRECTIVES` would imply that it has to import from `@angular/common` and import `PLATFORM_DIRECTIVES` symbol.

**Comment by mhevery** [comment]
A library should not be able to add things to platform. Only application (the code which controls the `bootstrap` should be allowed to decide what platform directives/pipes are)

This is important for being consistent with the offline compilation mode.
