### ISSUE TITLE
[routerLink] is ignored when component embedes jquery within a directive

### ISSUE THREAD

**Issue by acostaf** [angular/angular#9305]
HI People 

**Ng2 rc2 on Ie11**
I am creating a directive that uses Jquery to add a Kendo grid to my page, see below [1], my options are injected from the main component making this directive reusable. From the options property I pass my columns [2] and I also have another field that will cotain a [routerLink] [3]

I have already tried to **ng-reflect-router-link="/ AmendDetails''** and **ng-reflect-href="/ AmendDetails''** without luck, any Idea

[1] ** jQuery(this.elementRef.nativeElement.firstChild).kendoGrid(this.options);**
[2] **columns: [ { field: fieldName, title: Amends',…**
[3] **   field: ‘fieldName2’,…  template: '<a [routerLink]="[''/ AmendDetails'']">#= fieldName2’#</a>'**

**Comment by vicb** [comment]
see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem for request support
