### ISSUE TITLE
Angular Quick Start Guide error

### ISSUE THREAD

**Issue by fadiwissa** [angular/angular#9307]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The quick start guide is missing the Styles.css file. This file is referenced but no where in the "walkthrough" is it described. I got it from the Plunker version of the demo.

**Expected/desired behavior**
The Styles.css file should be created as one of the steps of the walkthrough.

**Reproduction of the problem**
Just walk through the walkthrough steps and the browser will throw an error due to its inability to find the referenced Styles.css file (referenced in Index.html)

**What is the expected behavior?**
The file should simply exist and no error should be thrown.

**What is the motivation / use case for changing the behavior?**
...

**Please tell us about your environment:**
Any

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart]

**Comment by zoechi** [comment]
Can you please report this in https://github.com/angular/angular.io instead where documentation issues are maintained?

**Comment by naomiblack** [comment]
you're right. the user shouldn't hit an error because of this. thanks for filing -- i duplicated over on angular.io: https://github.com/angular/angular.io/issues/1684
