### ISSUE TITLE
Only allow OnPush and Default as change detection modes in @Component

### ISSUE THREAD

**Issue by tbosch** [angular/angular#9311]
Right now, users can use any enumeration out of `ChangeDetectionStrategy` in `@Component`. However, we only support `OnPush` and `Default`. 

We should change our API to reflect this.

**Comment by RomanGotsiy** [comment]
> However, we only support OnPush and Default.
If I have specified `Deteached` in `@Component`, which on is actually used: `OnPush` or `Default`?

**Comment by vsavkin** [comment]
Fixed https://github.com/angular/angular/pull/9373

**Comment by tbosch** [comment]
Thanks!
