### ISSUE TITLE
reopen: ngControl control property is null when OnInit hook

### ISSUE THREAD

**Issue by Delagen** [angular/angular#9312]
#9291 

https://plnkr.co/edit/oxNuBLo8Y6Hg3OKbm25M?p=preview

**Comment by zoechi** [comment]
What is this Plunker supposed to demonstrate? It doesn't produce an error. 

You don't need to create a new issue. The old one gets reopened if you can provide information that allows to reproduce the issue.

**Comment by zoechi** [comment]
Maybe you forgot to safe some change in the Plunker?

**Comment by IgorMinar** [comment]
I reopened the original issue. Please clarify the repro there. thanks
