### ISSUE TITLE
Its not clear if Offline Template Compilation in Angular 2 RC 2 is ready for use

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular#9316]
Can anyone please confirm if Offline Template Compilation in Angular 2 RC 2 is ready for use.

If its available, how to use it?

**Comment by CaptainCodeman** [comment]
I couldn't get it to work on a trivial app but got further than the errors I'd seen previously, now it just has trouble understanding it's own directives (ngFor etc...) which is apparently going to be addressed.

**Comment by IgorMinar** [comment]
the compiler works for common cases. we are working on docs and demos. we are going to be rolling these out as they become ready.

**Comment by CaptainCodeman** [comment]
> the compiler works for common cases

Depends what you mean by "common cases". It doesn't work for an incredibly simple app and trips up over it's own directives. Shouldn't it work for an app that runs fine in the browser?

https://github.com/CaptainCodeman/angular2-webpack-polyfill

**Comment by CaptainCodeman** [comment]
I presume this is one of the missing pieces to make it actually work? https://github.com/angular/angular/issues/9319

(obviously, unless it's already working for 'common cases').

**Comment by IgorMinar** [comment]
I'm sorry. I missed that one. Yes. Ability to configure platform directives
is currently an obstacle for the common cases. We are addressing that in
rc.3  via  #9319 <https://github.com/angular/angular/issues/9319>

**Comment by CaptainCodeman** [comment]
Thank you, I appreciate the clarification (helps to know if its something we're doing wrong vs something not yet available)
