### ISSUE TITLE
Support configuration of compiler through tsconfig

### ISSUE THREAD

**Issue by mhevery** [angular/angular#9319]
We need to be able to control the compiler from `tsconfig.json` like so:

```
{
  "angularCompilerOptions": {
    "skipTemplateCodegen": false,
    "genDir": "../dist",

    // Configure offline compiler
    "defaultEncapsulation": "Emulated",
    "genDebugInfo": true, 
    "logBindingUpdate": false, 
    "platformDirectives": [ "@angular/common#PLATFORM_DIRECTIVES" ], 
    "platformPipes": [ "@angular/common#PLATFORM_PIPES" ],
  },
  "compilerOptions": {...}
}
``` 

where `@angular/common#PLATFORM_DIRECTIVES` would imply that it has to import from `@angular/common` and import `PLATFORM_DIRECTIVES` symbol.

**Comment by cexbrayat** [comment]
Following #9303 , it would be great to have a lightweight syntax to add just a custom pipe to the platform one, or to load ROUTER_DIRECTIVES into platformDirectives. Having to redeclare the whole `CompilerConfig` in code or tsconfig.json will be really verbose for this small use case. 

And as the `PLATFORM_PIPES/PLATFORM_DIRECTIVES` are being removed (#9320), it would be great to be able to do it another way.

Maybe something like `{ provide: CompilerConfig, useValue: new CompilerConfig({customPipes: [CustomPipe]})` could add CustomPipe to the platform pipes already loaded for this platform? Same for loading ROUTER_DIRECTIVES, or changing the default encapsulation.

**Comment by IgorMinar** [comment]
@mhevery I believe that 

```
    "platformDirectives": [ "@angular/common#PLATFORM_DIRECTIVES" ], 
    "platformPipes": [ "@angular/common#PLATFORM_PIPES" ],
```

should be 

```
    "platformDirectives": [ "@angular/common#COMMON_DIRECTIVES" ], 
    "platformPipes": [ "@angular/common#COMMON_PIPES" ],
```

**Comment by tbosch** [comment]
@IgorMinar yes, this has to be `#COMMON_...` and not `#PLATFORM_...` as the `PLATFORM_PIPES` / `PLATFORM_DIRECTIVES` are just tokens.

**Comment by matsko** [comment]
@mhevery you had mentioned that Tobias took care of this and that it's out of my hands yes?

**Comment by tbosch** [comment]
This has been superseded by app modules, see https://github.com/angular/angular/issues/9726
