### ISSUE TITLE
Deprecate obsolete PLATFORM_DIRECTIVES and PLATFORM_PIPES

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#9320]
While investigating #9303 we realized that we accidentally left behind PLATFORM_DIRECTIVES and PLATFORM_PIPES tokes in spite of documenting them as being removed in the changelog.

Now that the the platform directives and pipes are configured via the CompilerConfig we should deprecate these tokens and remove them in the future.

**Comment by pkozlowski-opensource** [comment]
Hmm, if I read #9319 correctly we will still need those symbols

**Comment by IgorMinar** [comment]
I think that's a typo in 9319. see
https://github.com/angular/angular/issues/9319#issuecomment-227192854

**Comment by IgorMinar** [comment]
@tbosch can you clarify?

**Comment by tbosch** [comment]
Yes, that is a typo in #9319 (I added a comment there).
Yes, let's remove these two tokens.

**Comment by tbosch** [comment]
Platform directives / Platform pipes are now being configured via app modules. I.e. these tokens should be deprecated and then removed.

**Comment by IgorMinar** [comment]
this was done in rc5
