### ISSUE TITLE
Run docs tests in our CI

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#9322]
Currently we occasionally break docs when we make changes in the source code. We need to run angular.io docs tests in our CI.

If the examples/tests remain in a separate repo, these should be only allowed/informative failures.

However it would be much preferable if the tests were part of the main repo.

**Comment by IgorMinar** [comment]
@naomiblack can we implement this via a hook on the core-builds repo? I can discuss with anyone from the docs team how this should work.

**Comment by naomiblack** [comment]
I don't think we can realistically do this until Ward is back. I don't have the bandwidth to dig into it in the next week. @filipesilva might have some thoughts though.

**Comment by filipesilva** [comment]
I should be able to do this, let's talk tomorrow Igor.

**Comment by IgorMinar** [comment]
Expanding the proposal in my last comment: we could setup a webhook on the angular/core-builds repo to ping angular.io travis build. so every time a new change lands in the angular/angular repo, we publish a new builds to angular/core-builds (and other *-builds repos). once the build is published, the angular.io tests run. If tests fail, we should be notified and review what's going on.

**Comment by filipesilva** [comment]
Docs side travis update in https://github.com/angular/angular.io/pull/1782.

**Comment by DzmitryShylovich** [comment]
@IgorMinar I believe this can be closed as you already run tests for `aio`

**Comment by IgorMinar** [comment]
Not yet. We moved the code but it's not wired up.

**Comment by petebacondarwin** [comment]
We are now running e2e tests on the docs examples in every build - although they are in an "optional" travis task because they take so long.
