### ISSUE TITLE
DatePipe doesn't allow timezone to be provided as a pipe input

### ISSUE THREAD

**Issue by natcohen** [angular/angular#9324]
DatePipe of Angular 2.0.0 RC2 doesn't allow to interpret date with timezone like AngularJS 1.5 does (https://docs.angularjs.org/api/ng/filter/date) as the second argument (timezone)

Angular 1 template api:

```
{{ date_expression | date : format : timezone}}
```

**Comment by MarkPieszak** [comment]
The [Datepipe](https://angular.io/docs/ts/latest/api/common/index/DatePipe-class.html) looks like it does support timezone with `z` or `Z`

**Comment by natcohen** [comment]
@MarkPieszak z and Z are used in the format to display the timezone, not as the interpreter! Please read the doc of angularJS (link in the question)

**Comment by MarkPieszak** [comment]
Ahh the timezone argument, I see now, you're right!

**Comment by laskoviymishka** [comment]
Could you please provide plnkr for these one

**Comment by laskoviymishka** [comment]
Sorry didn't mention that this is feature request :sweat:

**Comment by natcohen** [comment]
Any chance we could add this feature in an earlier version? Seems like it would be a simple copy of angular 1 date filter

**Comment by laskoviymishka** [comment]
@natcohen implementation for this one itself is rather simple, but its require a design decision from core team. Right now date pipe (and every other formatting pipes) jumping around Intl.API. This piece is not covered by Intl.API, so probably there is requiring some design decision to find what should be covered by Intl, and what should have separate implementation.
This question was asked several times and right now approach for core team - use Intl.API only. If feature not covered by Intl - just skip for later releases. This is absolutely reasonable decision, since A2 need some time to stabilize, and changes in designing approach may lead to some unexpected side effects.

**Comment by DaSchTour** [comment]
Maybe a good starting point to start some kind of angular2 moment.js pipes project?

**Comment by laskoviymishka** [comment]
Moment.js is a huge library, which enlarge even more for angular package. And it pretty high coupled so extract only useful part is not possible

**Comment by kylecordes** [comment]
It is true that moment is not a small thing. But it is also true that a high percentage of "enterprise" flavored Angular 2 applications, and many non-enterprise applications, will end up including moment anyway. So I think a moment date pipe would be a popular add-on.

**Comment by laskoviymishka** [comment]
Implement wrapper around moment js as a pipe not a big deal so. IMHO including such thing in a common package of framework not the best idea

**Comment by DaSchTour** [comment]
Nobody said anything about including this into a common package of angular.
BTW there is already somebody working on this.
As @kylecordes mention this will gain traction as Angular 2 is released and more commonly used.

**Comment by laskoviymishka** [comment]
@DaSchTour every pipe is a part of common package right now, and if you add dependency for moment.js into datePipe, that mean that you add this dependency into common package. 

Most difficult part of this requirement IMHO is not adjust date to timezone (that's fairly simple). Difficult in displaying locale specific entries. Like how we should display adjusted timezone name? Where this names should be stored? Currently all this data handled by Intl.API. In angular1 you have a 18in packages for each locale which contains those entries. Angular2 doesn't have anything like this right now. Intl.API also not allow you to extract this information. So implementing it is not so easy without storing every locale specific strings in a common package.

**Comment by natcohen** [comment]
Agree with @laskoviymishka ... Why reinventing the wheel?
Adding the timezone to the date pipe is nothing more than what already exists in Angular 1. People who are migrating their app from angular 1 to angular 2 want to do it without implementing new solutions, the upgrade process is already painful enough!

**Comment by laskoviymishka** [comment]
@natcohen problem with this point is that A1 have own i18n api, A2 jumping around Intl.API. This one is extremely bad. This specific change require a design decision from core team. Should we stay on Intl.API or just mimic A1 implementation. 
My IMHO is on A1 aproach. At least we would have a control for this API :smiling_imp: 
So now we have 2 options:

1. If we stay on Intl.API this become almost impossible to implement. At least with full scope. May be with some limitiation this is possible (like forbid to show timezone name with timezone override).
2. If we move to own i18n (even if it would be really same as A1 version) than it require significant amount of work for every pipe component (not critical, but still significant).

**Comment by cristianbote** [comment]
Hi,

Is this settled? Is the decision taken yet?

Thanks!

**Comment by mathewblackberry** [comment]
Any update on this?  I have an issue where the Date pipe is displaying the wrong date/time for Chrome on Android as it is returning the wrong Timezone offset (+10:00) instead of the Daylight Savings offset of +11:00 even though the correct timezone is set on the device.  Would be great if I can force the Date pipe to a particular tz for this and other reasons.

**Comment by natejgardner** [comment]
I'm developing an application that deals with airplane flights. Needless to say, the only acceptable timezone to display is UTC. It would be really great if I could force all times to be displayed in UTC.

**Comment by DzmitryShylovich** [comment]
@natejgardner UTC is not a time zone :)

**Comment by natejgardner** [comment]
+1 @DzmitryShylovich

**Comment by radoslavpetranov** [comment]
I'm also curious to know if this will be supported any time soon.

**Comment by YousefMMS** [comment]
+1 for @natcohen suggestion to include this in upcoming features.

**Comment by ocombe** [comment]
Hello, this will be added with the replacement of the intl API for angular v5 (see https://github.com/angular/angular/issues/10809)

**Comment by abhishekdgeek** [comment]
Is this available in Angular 5 and above?

**Comment by ocombe** [comment]
yes

**Comment by RahmaMzoughi** [comment]
Sorry for my limited knowledge,  what values can  `timezone`  variable take? 
I'm working with angular 5 
I mean can I use it this way : {{ test?.end_datetime | date : "h:mm a" : "CET" }}
Thanks
