### ISSUE TITLE
Animation: Void => State Ignores Initial Style When Delayed

### ISSUE THREAD

**Issue by sqwk** [angular/angular#9326]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
```

**Current behavior**

When animating a transition from `void` to a defined state and delaying this animation, the styling set before the animation is only applied once the delay is over.

**Expected/desired behavior**

The styling set before the animation should be applied immediately and be held until the actual animation starts to prevent flashing.

**Reproduction of the problem**

The code below describes a parallel in/out animation. One box moves in, the other moves out at the same time. (A little bit like a traditional airport departure board.) Since the two should not overlap, the in animation (`void => someState`) needs to be delayed. However, the void element (the one animating in) stays visible until the animation starts, is then hidden instantly, only to start animating in again.

            transition('void => someState', [
                style({
                    transform: 'rotateX(90deg)',
                }),
                animate('400ms 400ms ease-out')
            ]),
            transition('someState => void', [
                animate('400ms ease-in', style({
                    transform: 'rotateX(90deg)',
                }))
            ]),

Trying to style `void` as well does not work.

**Please tell us about your environment:**

* **Angular version: 2.0.0-rc.2**

* **Browser: Chrome 50.0.2661.102**

* **Language: TypeScript 1.8.10**

**Comment by matsko** [comment]
Excellent find. I will get to work on this one.

**Comment by matsko** [comment]
If you want to start using this now, in your `package.json` or system.js config files include the following mappings:

```
    "@angular/common": "angular/common-builds",
    "@angular/compiler": "angular/compiler-builds",
    "@angular/core": "angular/core-builds",
    "@angular/platform-browser": "angular/platform-browser-builds",
    "@angular/platform-browser-dynamic": "angular/platform-browser-dynamic-builds",
```

**Comment by sqwk** [comment]
@matsko thanks for the heads up.
