### ISSUE TITLE
Http: should return status code / text properly from errors

### ISSUE THREAD

**Issue by sumigoma** [angular/angular#9329]
**I'm submitting a ...** 
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Failed ajax calls return a 200 error code.

**Expected/desired behavior**
They should return the proper status code and error.
This issue has been linked several times and moved back and forth between angular/http and angular/angular but has not yet been addressed. 
angular/http#54 
angular/angular#6681
angular/angular#7352

Creating a new open issue in its correct repo (angular/angular) so that it doesn't get lost.

**Reproduction of the problem**

This Plunkr clearly shows the problem.
https://plnkr.co/edit/cSfEIUvbWAEHjTpUj6yD?p=preview

**What is the motivation / use case for changing the behavior?**

* **Angular version:** 2.0.0-rc.2
* **Browser:** all

**Comment by saurabhvyas** [comment]
I am still getting this error , I have rc3 installed

**Comment by danimalia** [comment]
I am also seeing this error on RC4 in a JSONP request.  The request is returning a 401 status but the error handler Response object is showing it as status: 200.  Also, the response headers are missing (WWW-Authenticate).

**Comment by saurabhvyas** [comment]
Hey, My issue was fixed, Please double check the JSONP URL and make sure you are passing JSONP_PROVIDERS in the parent component's provider's array.

**Comment by danimalia** [comment]
Yes, that's all working fine.  I am calling my own server API from localhost, and the Jsonp request works fine normally.  But, if I add an auth check to the API to force it to return 401 Unauthorized, the Angular2 Response object in the catch function shows the status as 200.  I've tried the same with the HTTP_PROVIDERS and it seems to get the 401 status, but not the response headers (like WWW-Authenticate).
