### ISSUE TITLE
'ElementRef' is not assignable to parameter of type 'ViewContainerRef' =>On update beta14 to beta16 

### ISSUE THREAD

**Issue by toni-moreno** [angular/angular#9331]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

On the BREAKING CHANGES section from beta14 to beta16 there is no decription on this error.
```
public/app/LoggedInOutlet.ts(15,11): error TS2345: Argument of type 'ElementRef' is not assignable to parameter of type 'ViewContainerRef'.
  Property 'element' is missing in type 'ElementRef'.
```
at
https://github.com/toni-moreno/snmpcollector/blob/master/public/app/LoggedInOutlet.ts#L14

**Expected/desired behavior**

Compile tsc without any issue.

**Reproduction of the problem**
Only compile with tsc

**What is the expected behavior?**

Only compile with tsc

**What is the motivation / use case for changing the behavior?**

angular version update

**Please tell us about your environment:**

* **Angular version:**
 2.0.0-beta16
$ npm -v
3.9.3
$ node -v
v6.2.1

* **Browser:** 
chome 50
* **Language:** 
typescript

**Comment by vicb** [comment]
The latest release is rc-2
