### ISSUE TITLE
rc2 breaks date format pipe's 2-digit interpretation of minutes and seconds

### ISSUE THREAD

**Issue by Paladinium** [angular/angular#9333]
**I'm submitting a ...** 
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The date pipe's format fails to interpret 2-digit minutes and seconds properly. They get rendered with just one minute when in range [0-9]. Example:

```
@Component({template: "{{myDate| date:'dd/MM/y HH:mm:ss'}}"})
class MyComponent {
    myDate = new Date('2016-06-01T07:01:09.882+0000');
}
```

The rendered date is: 01/06/2016 07:1:9 (depending on your local time zone, the hour might be different).

**Expected/desired behavior**
Expecting the date pipe's formatter to respect the 2-digit notation for minutes and seconds such that the above example results in: 01/06/2016 07:01:09.

* **Angular version:** 2.0.0-rc.2
* **Browser:** all
* **Language:** TypeScript

**Comment by laskoviymishka** [comment]
Could you please provide plnkr for this one, it would help a lot.

**Comment by laskoviymishka** [comment]
Well, there is a bug with minutes and hours, you could use predifined style such as `shortTime` etc. 
If you still need to use custom pattern you could combine 2 date filters.
Here is workaraund plnkr _http://plnkr.co/edit/NO7K4TPuVRkRfvESyAg7?p=preview_
