### ISSUE TITLE
Feature Request / Bug: Block nested animations by default.

### ISSUE THREAD

**Issue by bennadel** [angular/angular#9335]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When animating a container into view, if the container has nested elements / components that are also animated, they all animate together.

**Expected/desired behavior**

Based on the precedence set by Angular 1.x, nested animations should be blocked. Therefore, if a container is currently animating, the nested animations should be ignored. I understand that Angular 2 is a new platform; however, I would argue that the behavior demonstrated in NG1 is actually the _desired_ behavior - that nested animations are rarely desired unless explicitly activated with something like `ng-animate-children`. I think this hold especially true for `ngFor` where the initial rendering of the list shouldn't be animated; but, **new** items to that list should be:

http://www.bennadel.com/blog/2765-preventing-animation-during-the-initial-render-of-ngrepeat-in-angularjs.htm

I'm sure there is a way to _work around_ this issue by using a "state" or something; but, this would add increased complexity to accomplish what I suggest should be the default behavior.

**Reproduction of the problem**

http://plnkr.co/edit/j9EpndSwH6b12tjgCXID?p=preview

**What is the motivation / use case for changing the behavior?**

I believe it is a better user experience. And, it is a precedence set by NG1.

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.2
- **Browser:** all
- **Language:** TypeScript

**Comment by sqwk** [comment]
You can achieve the desired behaviour by styling the initial state via css and then delaying a negative transform. (See this plunkr: http://plnkr.co/edit/BT6Aa2Y1itOd5lIemXu6?p=preview)

This is slightly related to #9326: If fixed, one can style the end state via css and simply do something closer to this: http://plnkr.co/edit/2xwWSmWXpRzOHzv4v6jA?p=preview

**Comment by bennadel** [comment]
@sqwk sorry, I think I may not have been clear with the intent. The precedence set by NG1 is not that one animation happens _after_ the other; rather, that the parent animations runs while the nested animations is _completely skipped_, with the nested elements showing up in their "end" state immediately. So, to bring it back to my plunker, I think the better user experience is that the parent animation fades in (via `opacity`) while the nested `li` elements are immediately visible (but, of course, animated with `opacity` inherited by their nested structure).

**Comment by sqwk** [comment]
Yes, it would be great if that could be configured with `animate-children` (or rather `ignore-child-animation`if the current default is kept).

However, I wouldn't jump to the conclusion that child animations should inherit their parent transitions. Think of a table coming in from the left and the specific rows/columns from the right. The current default that animations are not inherited allows for a lot more freedom, but maybe that should be configureable setting as well?

**Comment by bennadel** [comment]
@sqwk I meant inherit in so much as they are ancestors in the DOM tree, so if the parent is animated by opacity, they (the children) will also be animated by opacity due to their relationship. That said, with the NG1 approach to `ng-animate-children`, you could definitely to the table-left / rows-right approach.

I think the NG2 stuff looks a **lot more flexible**; but, at the same time, might make some basic stuff harder / impossible.

**Comment by sqwk** [comment]
Is there any news on this?

**Comment by matsko** [comment]
For 5.x it will likely work by always blocking inner child animations on enter and leave (the `animateChild` feature can then be used to allow inner animations to be kicked off).

This issue will track the progress of this: https://github.com/angular/angular/issues/20674
