### ISSUE TITLE
Custom Validation not working with Angular 2 RC 2  new forms

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular#9336]
After upgrading to the new forms my custom validation that was working in RC 1 is not working anymore.

When compiling I am receiving the below errors:

```
Argument of type '(control: Control) => ValidationResult' is not assignable to parameter of type 'ValidatorFn[]'.


Argument of type '(control: Control) => ValidationResult' is not assignable to parameter of type 'ValidatorFn[]'.
  Property 'push' is missing in type '(control: Control) => ValidationResult'
```

Here is my main file

```
import {disableDeprecatedForms, provideForms} from '@angular/forms';
bootstrap(AppComponent, [
   disableDeprecatedForms()
   provideForms()
])
```

Here is my component using custom validators

```
import { Component } from '@angular/core';
import { REACTIVE_FORM_DIRECTIVES, FormControl, FormGroup, FormBuilder, Validators } from '@angular/forms';
import { CustomValidators } from './custom-validators';

@Component({
        templateUrl: 'my-form.html',
        directives: [REACTIVE_FORM_DIRECTIVES],
    })

export class MyFormComponent {

    public form: FormGroup;

    constructor(private fb: FormBuilder) {

        this.form = fb.group({
                name: ["", Validators.compose([Validators.required, CustomValidators.personName])],
                age: [0, CustomValidators.numeric],
            });
    }
}
```

My template:

```
<form [formGroup]="form" (ngSubmit)="onSubmit()" novalidate>

<input [formControlName]="name" type="text">
<span *ngIf="!name.valid && name.touched && name.dirty && name.pattern">Invalid characters found in name</span>

<input [formControlName]="age" type="text">
<span *ngIf="!age.valid && age.touched && age.dirty &&age.invalid">Invalid age</span>

<button type="submit">Submit</button>
</form>
```

My custom validators:

```
import { Control, ControlGroup } from "@angular/common";

interface ValidationResult {
    [key: string]: boolean;
}

export class CustomValidators {

    public static numeric(control: Control): ValidationResult {
        //Skip validation if empty, to handle optional fields
        if (!control.value) {
            return null;
        }

        var valid = /\d{0,9}/.test(control.value);
        if (valid) {
            return null;
        }
        return { "invalid": true };
    }
    
    public static personName(control: Control): ValidationResult {
        //Skip validation if empty, to handel optional fields
        if (!control.value) {
            return null;
        }

        if (control.value.length < 3) {
            return { "minlength": true };
        }

        if (control.value.length > 50) {
            return { "maxlength": true };
        }

        var valid = /^[a-zA-Z. ]*$/.test(control.value);
        if (valid) {
            return null;
        }
        return { "pattern": true };
    }
    
}
```

**Comment by vicb** [comment]
Please provide a plunker

**Comment by naveedahmed1** [comment]
Please have a look at https://plnkr.co/edit/j9U1vnNZN1D9Rch79UZ8?p=preview

**Comment by DzmitryShylovich** [comment]
`import { Control, ControlGroup } from "@angular/common";` wrong import for new forms api

**Comment by naveedahmed1** [comment]
Thank you so much Dzmitry,it was really helpful.  I didn't realize that I have updated all components, and templates but didn't update the import in my custom validators.

**Comment by aubreyff** [comment]
DzmitryShylovich's sample works but not for regex input fields custom validators.  Please take a look.

`//our root app component
import {Component} from '@angular/core'
import { REACTIVE_FORM_DIRECTIVES, FormGroup, FormControl, FormBuilder, Validators, RadioButtonState } from '@angular/forms';

@Component({
  selector: 'my-app',
  directives: [REACTIVE_FORM_DIRECTIVES],
  template: `
    <form [formGroup]="form">
      <h4 class="ui header">Single Selection</h4>
      <input [formControl]="form.controls['singleSelection']" class="ui fluid dropdown" required pattern="test">
        <br/>
      <i>Selected: {{form.controls['singleSelection'].value}}</i><br>
      <i>Dirty: {{form.controls['singleSelection'].dirty}}</i><br>
      <i>Valid: {{form.controls['singleSelection'].valid}}</i><br>
      <i>error for required: "{{form.controls['singleSelection'].errors.required}}"</i><br>
      <i>error for validateCity: "{{form.controls['singleSelection'].errors.validateCity}}"</i>
      <br><br>
     <h4 class="ui header">Multiple Selection</h4>
     <select multiple [formControl]="form.controls['multipleSelection']">
        <option>Red</option>
        <option>Green</option>
        <option>Blue</option>
      </select>
      <br>
      <i>Selected: {{form.controls['multipleSelection'].value}}</i><br>
      <i>Dirty: {{form.controls['multipleSelection'].dirty}}</i><br>
      <i>Valid: {{form.controls['multipleSelection'].valid}}</i>
    </form>
  `
})
export class App {
  form: FormGroup;
  
  constructor(private fb: FormBuilder) {
    this.form = fb.group({
      'singleSelection': ['Rio', [App.validateCity,Validators.required]] // initial value as string
      'multipleSelection': [['Red','Blue'], [App.validateColor]]  // initial value as array
    });
  }
  
  static validateCity(c: FormControl) {
    var regex_pattern = new RegExp("test");
        var test_result = regex_pattern.test(c.value);
        if(!test_result){
          //means that this is NOT validated and should return an error
          return { 'validateCity': true };
        }
        //means that this is validated and should return null
        //return null; //<-- it doesn't work it causes errors.
        return { 'validateCity': null };//<-- this doesn't cause errors, but for is not valid.
  }
  
  static validateColor(c: FormControl) {
    if (c.value.indexOf('Green') < 0) {
      return {badColor: true};
    }
    return null;
  }
}`
