### ISSUE TITLE
Animation trigger on host.

### ISSUE THREAD

**Issue by shlomiassaf** [angular/angular#9337]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[x] feature request
```

**Current behavior**
Setting animation on a the host is not supported.

**Expected/desired behavior**
Enable a component to apply animation on it's own host element.

**What is the motivation / use case for changing the behavior?**
While usually the host will have it's animation from the parent component via template syntax, there is possibility to insert a component using the `ComponentResolver -> ComponentFactory`. The only way to control host properties/attributes is by applying @HostXXX decorators on setting the `host` component metadata property.

```ts
@Component({
    selector: 'modal-backdrop[@fade=fadeState]',
    host: {
       '@myTrigger': 'myTriggerProp',
       '[@myTrigger1]': 'myTriggerProp1'
    },
    ...
```
None of the above work.

My use case is in a Modal/Dialog window, where a top level component is the container of the overlay, backdrop and dialog itself.

The top level component does not have actual UI thus no animation. When closing I destroy the top level component via `componentRef.destroy()`.  Animation triggers are set on child components but the do not trigger.
I guess I can enter an intermediate state in the top level component, the fires a close event and wait for everything to finish but that seems manual...

I'm not sure if there's an issue, and if there is - is it using `@tigger` attributes on the host or having the host remove all children, wait for animation and then dispose, which is also problematic...

**Comment by shlomiassaf** [comment]
Here's a code example

```ts
@Component({
    selector: 'modal-backdrop',
    animations: [
        trigger('fade', [
            transition('void => in', [
                animate('150ms linear', keyframes([
                    style({opacity: 0}),
                    style({opacity: 0.5})
                ]))
            ]),
            transition('* => void', [
                animate('100ms, linear', keyframes([
                    style({ opacity: 0.5 }),
                    style({ opacity: 0.5 })
                ])),
                animate('150ms linear', keyframes([
                    style({ opacity: 0.5 }),
                    style({ opacity: 0 })
                ]))
            ]),
        ])
    ],
    template:
`<div class="modal-backdrop" @fade="fadeState"></div>
<modal-container></modal-container>`
})
export class ModalBackdrop  {
    fadeState: 'in' | 'out' = 'in';
}
```

Entering works great.
Leaving, not at all.

This `ModalBackdrop` is added dynamically, that is using a `ComponentFactory` and not a template tag. When creating it I get a `ComponentRef` instance which I use later to destroy it.

**Comment by vicb** [comment]
Please provide a plunker

**Comment by Foxandxss** [comment]
I guess I have a similar problem.

I have a collapse, it is a directive applied to a thing that you want to, well, collapse. I don't know how to apply the animation to the host. Here is my try:

http://plnkr.co/edit/Vc4cSgZNXK70EaZoVzd9?p=info

Tried a few things, no luck.

**Comment by shlomiassaf** [comment]
This issue was solved with RC3

**Comment by Foxandxss** [comment]
What's the syntax? I might need to document it

**Comment by shlomiassaf** [comment]
Sorry I got confused with another issue

**Comment by shlomiassaf** [comment]
I believe this is a duplicate of #9044
