### ISSUE TITLE
Angular Router 3.0 history navigation broken

### ISSUE THREAD

**Issue by sharpmachine** [angular/angular#9339]
Exact same issue as #9088, but on the `"@angular/router": "3.0.0-alpha.3"`.

Browsers back button works once and forward button doesn't work at all.

Chrome 51
OSX
Angular 2.0.0-rc.1

**Comment by ericmartinezr** [comment]
The router lives here https://github.com/angular/vladivostok, see also https://github.com/angular/vladivostok/issues/64

**Comment by vicb** [comment]
@sharpmachine could you please test with alpha.7 ? Thanks

**Comment by sharpmachine** [comment]
Will do. It's going to take a minute though. There are a few breaking
changes and it requires Angular 2 be RC2.

**Comment by sharpmachine** [comment]
Thanks @vicb. I upgraded to Alpha 7, fixed the breaking changes (paths cannot have a `/ ` and `index` has been deprecated), upgraded to Angular 2 RC2, and now the history navigation is working great for me.

**Comment by pkozlowski-opensource** [comment]
@sharpmachine thnx for reporting back - I guess this one can be closed. In the future please use router repository (angular/vladivostok) for router-specific issues. Thnx!
