### ISSUE TITLE
Need a way for a parent component to know when children are "ready"

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#934]
Use case:
A parent container component is responsible for performing the layout for some number of children. The parent is unable to know *how* to layout these children until all of their bindings have been resolved. However, `onChange` wouldn't work for this, because it will not be fired for child components with all static attributes. 

Specific example: Material Design [grid-list](https://material.angularjs.org/#/demo/material.components.gridList).
The `grid-list` is responsible for doing the layout of all the contained `grid-tiles`. The parent has to do the layout because each tile doesn't know about its sibling `grid-tiles`. In order to perform this layout, `grid-list` needs to know the `rowspan` and `colspan` for each tile (which can be either static or set via binding). Right now, there is no good way for the `grid-list` to know / be notified when a `grid-tile` is ready to be size/positioned.

If the `@Children` or `Query` injections were implemented, this would not solve the problem because the `grid-list` constructor is still too early for the `grid-tile` properties to have been set.

**Comment by jelbourn** [comment]
@mhevery @vsavkin Here's another use case for something like this:
```js
@Component({
  selector: '[md-button][href]',
  bind: {
    disabled: 'disabled'
  },
  lifecycle: [onChange]
})
@Template({
  url: '../button.html'
})
export class MdAnchor {
  tabIndexSetter: Function;

  /** Whether the component is disabled. */
  disabled: boolean;

  constructor(@PropertySetter('tabIndex') tabIndexSetter: Function) {
    this.tabIndexSetter = tabIndexSetter;
    console.log(this.disabled);
  }

  /** Invoked when a change is detected. */
  onChange() {
    // A disabled anchor should not be in the tab flow.
    this.tabIndexSetter(this.disabled ? -1 : 0);
  }
}
```

I want to set the `tabIndex` of the host element based on whether the anchor is disabled. As it stands, if I have a static template:
```html
<a md-button disabled href="http://google.com">Google</a>
```
I have no way of ever figuring out if the component is disabled. Resolving #622 would give me a way to do this, but it would be more boilerplate: I would have to check for a static value in the constructor *and* for a bound value in `onChange`.

**Comment by dylanb** [comment]
I would like to claim that this example

https://github.com/dylanb/Axponents/blob/master/angular2/ariamenubar.es6#L156

Is an example of where this notification would be good, but not having access to the `@Children` implementation, or enough information about it, it becomes difficult to determine whether it would suffice. However the above mentioned example is one that I plan to refactor once `@Children` and `@Parent` become available. Any ideas when that might be?

**Comment by jelbourn** [comment]
`@Parent` already works. `@Children` is in-progress presently.

**Comment by dylanb** [comment]
@naomiblack does the implementation of @Children notify when the child components are ready?

**Comment by jelbourn** [comment]
@dylanb  `@Children` is a separate issue, see #792

**Comment by dylanb** [comment]
@jelbourn I know, but I thought this issue was about a parent getting notified when its children are all ready. If that is part of the standard `@Children` implementation, then it is fine to close this issue, thats why I am asking here.

**Comment by jelbourn** [comment]
Oh, the commit didn't get associated with this issue. There has been a new lifecycle event added called `onAllChangesDone`

**Comment by dylanb** [comment]
@jelbourn excellent - I see the new code!!

**Comment by mhevery** [comment]
723e8fde936023c5720763b68e4bc364e474a186
