### ISSUE TITLE
Html Parser improvements

### ISSUE THREAD

**Issue by vicb** [angular/angular#9340]
@laco0416 is working on making the interpolation config configurable in https://github.com/angular/angular/pull/9158.

Once this PR lands we can work on further Lexer/Parser improvements.

We should add a new `INTERPOLATION_TOKEN` to the lexer output for interpolations.

Benefits:
- Any character is allowed in an interpolation - currently `<` in an interpolation is considered as a tag start and we backtrack on malformed track. `a <b &c> d` would defeat our current strategy. (addresses in #9421)
- There is currently no way to escape ICU messages (expansion forms) and interpolation. Because the lexer would be responsible for interpolation and expansion form, we can implement escaping by using `%xx` for those.

**Comment by ajitsinghkaler** [comment]
@pkozlowski-opensource @gkalpak I think you can close this issue you have solved it.
