### ISSUE TITLE
Allow Custom CSS Variables in [ngStyle]

### ISSUE THREAD

**Issue by sqwk** [angular/angular#9343]
This could be both a bug or a feature request …

**Current behavior**

When binding a custom CSS variable via `[style.--feat-image]=...'` or `[ngStyle]=“{‘--feat-image’: … }”` the property is ignored by angular and not bound. I assume there is a whitelist for certain (CSS) properties, which does not include possible CSS variables yet.

**Expected/desired behavior**

The value should be bound. If a whitelist of properties is needed, one fix could be to allow any property starting with --.

More information about CSS variables here: https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables 

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.2
- **Browser:** Chrome 50.0.2661.102
- **Language:** TypeScript 1.8.10

**Comment by pkozlowski-opensource** [comment]
I guess you are more likely to _use_ a defined variable rather than _declare_ one, so a more real-life use-case would probably be `[style.background-color]="'var(--main-bg-color)'"`. But yeh, currently this is sanitized. @mprobst will know more.

**Comment by zoechi** [comment]
You can explicitly allow it by for example using a pipe like shown in https://github.com/angular/angular/issues/8491#issuecomment-217473878

**Comment by sqwk** [comment]
Unfortunately, the value is still blocked, even using the filter: 

`[style.--event-logo]="'url(' + eventLogo + ')' | safe"`.

`eventLogo` is a data url (`url(data:image/png;base64,...`), so would that also need be unblocked?

**Comment by zoechi** [comment]
@sqwk What is `[style.--event-logo]="..."` supposed to do? I don't think you can use CSS variable values as style property names.

**Comment by sqwk** [comment]
I am trying top pass in a user uploaded image to add to an existing stylesheet. Theoretically one could just write `background-image` to the element in question, unfortunately, it is an `:after` element that won't allow this. So, yes, it is a very isolated problem to have …

I have tested the idea of using CSS variable to pass the value to a containing element by manually editing the style. Works exactly according to spec.

**Comment by zoechi** [comment]
@sqwk Where is this spec'ed, can you provide a link? Can you provide a Plunker that shows how it works outside of Angular2 and how it not works inside?

**Comment by sqwk** [comment]
The spec: https://drafts.csswg.org/css-variables/ (You can find a slightly more readable version at the mozilla link in the first comment.

A plunkr of it working in pure html: http://plnkr.co/edit/6mxzWTZBXbOMpkVRZPLl?p=preview And in Angular: http://plnkr.co/edit/AwnSgzpicjjYR0pjaIms?p=preview (I had to host the css externally, as plunkr seems to have trouble with the var() in the stylesheet.)

**Comment by sqwk** [comment]
Note that angular also blocks prefixed styles like `-webkit-clip-path` by default.

**Comment by napcat** [comment]
I have the exact same problem... I need to set a background image but in a :before, the image location is received from a rest service. It would be great if we could set a variable like this.

Is there any way to white list and make it possible?

**Comment by frapontillo** [comment]
I need to use CSS variables inside my application, since I have an unknown number of items in my list that define the view behaviour.

The best solution ~~would be~~ is to keep all the graphic logic inside my (S)CSS files, that can "react" to CSS variable changes due to media queries. One of the parameter of the CSS values depends on something that I need to calculate in my component code.

Therefore, I tried (and failed) to do something like this:
```typescript
@HostBinding('style.--element-position') get elementPosition() {
  return this.position;
}
```

How come CSS variables are blocked from being applied as valid style?

**Comment by Serginho** [comment]
Same problem with -moz prefixs, mozilla is ignoring `column-count`, I have to use `-moz-column-count`

**Comment by yesroh** [comment]
@sqwk I had try your plunk and don't worked for me (http://plnkr.co/edit/i4eltZ5cB1CcHTTl3JvW?p=preview) `Ionic Framework Version: 2.0.0-rc.2` and my dependencies is this:

```
  "dependencies": {
    "@angular/common": "2.1.1",
    "@angular/compiler": "2.1.1",
    "@angular/compiler-cli": "2.1.1",
    "@angular/core": "2.1.1",
    "@angular/forms": "2.1.1",
    "@angular/http": "2.1.1",
    "@angular/platform-browser": "2.1.1",
    "@angular/platform-browser-dynamic": "2.1.1",
    "@angular/platform-server": "2.1.1",
    "@ionic/storage": "1.1.6",
    "@types/jasmine": "2.5.41",
    "@types/jquery": "2.0.34",
    "@types/request-promise": "^4.1.33",
    "angular2-text-mask": "^8.0.0",
    "angularfire2": "^2.0.0-beta.6",
    "cep-promise": "^2.0.2",
    "firebase": "^3.6.1",
    "ionic-angular": "2.0.0-rc.2",
    "ionic-native": "2.2.3",
    "ionicons": "3.0.0",
    "jquery": "3.1.1",
    "request": "^2.81.0",
    "r
  "devDependencies": {
    "@ionic/app-scripts": "1.0.0",
    "@types/node": "6.0.49",
    "typescript": "2.0.3"
  }equest-promise": "^4.2.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "^0.6.21"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.0.0",
    "@types/node": "6.0.49",
    "typescript": "2.0.3"
  }
```

I need to do the same thing that @frapontillo You did it?

**Comment by rtm** [comment]
I really want to write

    @HostBinding('style.--x') public x;

Is there any update on when that will be possible, or how to work around it, other than

    this.elementRef.nativeElement.style.setProperty('--x', this.x)

or 

    this.renderer.setElementStyle(this.elementRef.nativeElement, '--x', this.x)

?

**Comment by chris13524** [comment]
I was able to workaround this issue by doing:

    <div [attr.style]="sanitizer.bypassSecurityTrustStyle('--custom: ' + value)">

**Comment by adaoust** [comment]
+1 to @rtm's post for angular to allow something like

`@HostBinding('style.--rotation') public rotation;`

Any progress on resolving this issue? Or should I build a custom directive?

**Comment by mlc-mlapis** [comment]
It would really be nice to get some actual feedback from Angular core team on this topic. 👍

**Comment by sqwk** [comment]
Not sure when this started to become possible, but I am now successfully using something like this:

    this.image1                       = Observable.of('somePath/lorem/ipsum/image.png');
    this.sanitizedImage1Path          = this.image1.map((path) => this.sanitizer.bypassSecurityTrustResourceUrl(path));
    this.sanitizedImage1StyleVariable = this.image1.map((path) => this.sanitizer.bypassSecurityTrustStyle('--feat-image:url(' + path + ')'));

where `sanitizer` is the `DomSanitizer` from `'@angular/platform-browser'` and elements are bound like this:

    <div [attr.style]="sanitizedImage1StyleVariable | async">

or 

    <img [src]="sanitizedImage1Path | async" />  

Also see https://stackoverflow.com/questions/35280118/change-style-of-pseudo-elements-in-angular2/37902154#37902154

If, it's up to me, this can be closed.

**Comment by denisyilmaz** [comment]
with Renderer2 it's working with `.setAttribute()` like this:
```typescript
this.renderer.setAttribute(this._el.nativeElement, "style", '--main-color: #f00')
```

**Comment by mlc-mlapis** [comment]
@friends4satish ... read more about formatting syntax and correct your post please, it looks terrible.

**Comment by fr0** [comment]
In the event that you don't want to use the  `bypassSecurityTrustStyle` workaround (for whatever reason), you can do what I did and create a custom directive:

```
export interface CssVariable {
  name: string;
  value: string;
}

@Directive({
  selector: '[appOverrideCssVar]'
})
export class OverrideCssVarDirective implements OnChanges {
  @Input('appOverrideCssVar') variable: CssVariable;

  constructor(private element: ElementRef) { }

  ngOnChanges(changes: SimpleChanges) {
    if (changes.variable) {
      if (this.variable.value) {
        this.element.nativeElement.style.setProperty(this.variable.name, this.variable.value);
      }
      else {
        this.element.nativeElement.style.removeProperty(this.variable.name);
      }
    }
  }
}
```
And use it like this:

```
<div [appOverrideCssVar]="{name: '--foo', value: '1px'}"></div>
```

Looking forward to the day when this issue is fixed and I can delete my custom directive.

**Comment by certainlyakey** [comment]
In Angular 6 this

```
this.renderer.setElementStyle(this.elementRef.nativeElement, '--x', this.x)
```

didn't work for me. Apparently `renderer.setElementStyle` is not there anymore. 

This however worked fine, and it allows to update individual style properties:

```
this.elementRef.nativeElement.style.setProperty('--x', this.x)
```

**Comment by zhuhang-jasper** [comment]
But it is still not possible to do:
```
[ngStyle] = "someFunctionThatReturnStyleObject()" 
```
```
someFunctionThatReturnStyleObject() {
    return { '--degree' : '90deg' };
}
```
I need it because `this.elementRef.nativeElement.style.setProperty()` don't work on elements before view is rendered..

**Comment by denisyilmaz** [comment]
> In Angular 6 this
> 
> ```
> this.renderer.setElementStyle(this.elementRef.nativeElement, '--x', this.x)
> ```
> didn't work for me. Apparently `renderer.setElementStyle` is not there anymore.
> 
> This however worked fine, and it allows to update individual style properties:
> 
> ```
> this.elementRef.nativeElement.style.setProperty('--x', this.x)
> ```

What about `this.renderer.setStyle(this.elementRef.nativeElement, '--x', this.x)` ???

**Comment by IlCallo** [comment]
@denisyilmaz 
`Renderer.setStyle` won't allor unknown properties as CSS variables are, it will just ignore it.

For those who wants to update a CSS variable on the host element via `HostBinding` **without touching directly the DOM** I can suggest this solution (uses RxJs, bind-observable and ngx-until-destroyed to keep the code clean).

```typescript
@Component({
  selector: 'my-component',
  templateUrl: './my-component.component.html',
  styleUrls: ['./my-component.component.scss']
})
export class MyComponent implements OnInit, OnDestroy {
  @BindObservable()
  public property = 50;
  public property$!: Observable<number>;

  @HostBinding('style')
  private cssVariable: SafeStyle = '' + this.property;

  constructor(private sanitizer: DomSanitizer) {}

  ngOnInit() {
    this.property$
      .pipe(untilDestroyed(this))
      .subscribe(
        propertyValue =>
          (this.cssVariable = this.sanitizer.bypassSecurityTrustStyle(
            `--cssVariable: ${propertyValue};`
          ))
      );
  }

  // Must be present for AOT compilation to work when using ngx-until-destroyed package,
  // even if empty.
  // Otherwise 'ng build --prod' will optimize away any calls to ngOnDestroy,
  // even if the method is added by the untilDestroyed operator
  public ngOnDestroy() {}
}
```

**Comment by sante85** [comment]
+1

**Comment by webia1** [comment]
News?

**Comment by Airblader** [comment]
@webia1 If there's news you would see it in this issue in the form of linked PRs, comments or the fact that it's closed.

**Comment by vicatcu** [comment]
I _think_ this issue represents a significant impediment to the Ionic community since, as of Ionic 4, the component framework leans heavily on the use of CSS Custom Properties for style encapsulation. It's quite difficult to pierce that vale without something like this issue being resolved.

**Comment by peteboere** [comment]
Our workaround

```ts
import {Directive, ElementRef, Input} from '@angular/core';

/*
 * Workaround for setting CSS custom properties:
 * https://github.com/angular/angular/issues/9343
 *
 * Can work for any style properties.
 */
@Directive({
    selector: '[cssProps]',
})
export class CSSPropsDirective {

    @Input() cssProps: any;

    constructor(private element: ElementRef) {}

    ngOnChanges({cssProps}) {
        if (cssProps && cssProps.currentValue) {
            const {style} = this.element.nativeElement;
            for (const [k, v] of Object.entries(cssProps.currentValue)) {
                style.setProperty(k, v);
            }
        }
    }
}
```

**Comment by Stun3R** [comment]
@peteboere Hi, how do you use this ?

**Comment by felyperennan** [comment]
Angular 8.1 and this is still an issue.
I need to write 
`[style.--property.%]="someBinding"`
but instead I have to write
`[attr.style]="sanitizer.bypassSecurityTrustStyle('--custom: ' + value)"`
Thanks @chris13524 btw

**Comment by cesalberca** [comment]
If this issue were to be resolved we would be able to make our components more flexible. For instance we could use an undeclared css property as follows:

```css
.card {
  // We can even put default values
  background: var(--card-gradient, transparent);
  padding: var(--medium);
  display: flex;
  flex-direction: column;
  align-items: center;
  border-radius: var(--radius);
  box-shadow: var(--shadow);
}
```

In the html we would have something as follows:

```html
<div [style]="background()" class="card">
  <h3 class="title">{{ title }}</h3>
  <p class="content">{{ content }}</p>
</div>
```

And finally the component would look like this:

```ts
import { Component, Input } from '@angular/core'
import { Gradient } from './gradient'

@Component({
  selector: 'app-card',
  templateUrl: './card.component.html',
  styleUrls: ['./card.component.scss']
})
export class CardComponent {
  @Input()
  title = ''

  @Input()
  content = ''

  @Input()
  gradient?: Gradient

  background() {
    switch (this.gradient) {
      case Gradient.PRIMARY:
        return '--card-gradient: var(--primary-gradient);'
    }
  }
}
```

This would allow the user to set a given gradient or no. And even further, the *user would be able to set a custom `--card-gradient` which would make this component hyper-flexible*.

**Comment by vladimirdjurdjevic** [comment]
Can someone from the angular team provide some feedback? This is really must have..

**Comment by valterbarros** [comment]
@peteboere a very tiny solution thanks, that helps me! :)

**Comment by lincolnthree** [comment]
This works in Angular 9-beta.14.

    [style.--background-checked]="tag.bgcolor"

**Comment by IlCallo** [comment]
Are you sure it's not a bug? I don't see it mentioned anywhere into changelog

**Comment by lincolnthree** [comment]
I can't tell you if it's a bug or not, but it does work. *shrug*

**Comment by Splaktar** [comment]
You can see in the [CHANGELOG](https://github.com/angular/angular/blob/master/CHANGELOG.md#900-next14-2019-10-25) that there were a number of styling performance fixes in `next.14`. @matsko should be able to provide some more details about whether this is officially fixed in Ivy with version `9.0.0-rc.0`.

**Comment by wnodom** [comment]
A promising tweet from @IgorMinar:

> The feature was enabled by refactoring the styling code to make it less buggy. So while the goal was not to specifically enable css properties, the reduction of bugs seem to be paying off.

<https://twitter.com/wnodom/status/1193022557156499456?s=20>

..so it sounds like it's unintentionally intentional. 🙂

**Comment by stupidawesome** [comment]
> This works in Angular 9-beta.14.
> 
> ```
> [style.--background-checked]="tag.bgcolor"
> ```

I can't get this working in RC versions.

**Comment by venelinn** [comment]
@peteboere what's the usage for this directive in the template? I'd like to combine css var with dynamic props? Thanks !

**Comment by HansKrywaa** [comment]
Upgrading to Angular v9 isn't a Option for my Project. So this works:
```html
<div [style]="color">...</div>
```

```typescript
color = this.sanitizer.bypassSecurityTrustStyle('--someKey: ' + someVariable);
```

I figured out, that it doesn't work if any other styles were set via `[style.anyKey]` or `[ngStyle]`, so i had to create a container wich only contains the variable. 🎉

**Comment by chaoyangnz** [comment]
Works in Angular 9+, like it so much

`@HostBind('style.--custom-proproty')`

I suppose this issue can be closed

**Comment by karptonite** [comment]
Perhaps someone can close this issue? I read through a lot of it before realizing it was fixed (but not closed).

**Comment by prestopasto** [comment]
Is it closed though @karptonite?  I've seen work arounds, but no one has said you can use [ngStyle] to set or use css properties like the original issue asked about.

Did I miss something?

**Comment by karptonite** [comment]
True, I used one of the workarounds, I think. But i think if those were documented, it may be close enough.

**Comment by AndrewKushnir** [comment]
Closing this ticket based on the comments above (that it works in Ivy).
