### ISSUE TITLE
Module '"node_modules/@angular/router/index"' has no exported member 'provideRouter'.

### ISSUE THREAD

**Issue by rspenc29** [angular/angular#9344]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Current behavior**

Following the documentation at https://angular.io/docs/ts/latest/guide/router.html I add the following line to my `app.routes.ts`

    import { provideRouter, RouterConfig } from '@angular/router';

Then i run `npm start` and get the following errrors

    app/app.routes.ts(2,10): error TS2305: Module '"node_modules/@angular/router/index"' has no exported member 'provideRouter'.
    app/app.routes.ts(2,25): error TS2305: Module '"node_modules/@angular/router/index"' has no exported member 'RouterConfig'.

I search the code and cant find any references to `provideRouter` or `RouterConfig`

**Expected/desired behavior**

I expect it to build successfully.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.2
 
* **Browser:** N/A
 
* **Language:** [TypeScript 1.8.10]

**Comment by ericmartinezr** [comment]
RC.2 is shipped with the RC router, which has been deprecated. You need to install the vladivostok router

```
npm remove @angular/router --save // will remove the RC router
npm install @angular/router@3.0.0-alpha.7 --save // will install the latest router
```

**Comment by rspenc29** [comment]
Thanks for the quick reply. For anyone else that sees this, I also had to update my system.config.js to not use the umd files for the router since they aren't there in alpha.7 as well as remove the leading `/` from all of my routes.

**Comment by asiacoll** [comment]
I have the sam problem. Could you tell me how to update my system.config.js to not use the umd files for the router?

**Comment by rspenc29** [comment]
Assuming you are using the same `system.config.js` as the quick start, remove `router` from the `ngPackageNames` array and add `'@angular/router': { main: 'index.js', defaultExtension: 'js' }` to the `packages` array.

**Comment by asiacoll** [comment]
thanks a lot, it works and I can go ahead. However there are error messages:
platform-browser.umd.js:962 EXCEPTION: Error: Uncaught (in promise): TypeError: _this.location.isCurrentPathEqualTo is not a function

please help.

**Comment by thecodemine** [comment]
I'm facing the exact same issue, and am also stumped at the "Error: Uncaught (in promise): TypeError: _this.location.isCurrentPathEqualTo is not a function" error. Any help would be greatly appreciated.

**Comment by pkozlowski-opensource** [comment]
@asiacoll @thecodemine there is not much point in commenting on a closed issue, especially with an unrelated error. Please ask support questions on a dedicated channel: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by premambodkar** [comment]
@ericmartinezr  Not Working for My system "
D:\Prem Angular Material\Angular 2\Angular-demo>npm install @angular/router@3.0.
0-alpha.7 --save
angular-quickstart@1.0.0 D:\Prem Angular Material\Angular 2\Angular-demo
+-- @angular/router@3.0.0-alpha.7
`-- UNMET PEER DEPENDENCY rxjs@5.0.0-beta.12

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fseve
nts@1.0.14
npm WARN @angular/router@3.0.0-alpha.7 requires a peer of rxjs@5.0.0-beta.6 but
none was installed.
npm WARN angular-quickstart@1.0.0 No description
npm WARN angular-quickstart@1.0.0 No repository field."
