### ISSUE TITLE
Angular Router 3.0.0-alpha.7 

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular#9345]
Hi,

I am just migrating my application to the new router i.e. Angular Router 3.0.0-alpha.7.

It seems that the new router doesn't treat below route as a valid route

`{ path: '/products', component: ProductsComponent },`

and gives error "Error: Invalid route configuration of route '/products': path cannot start with a slash"

Whereas, if I remove slash it treats it as a valid route:

`{ path: 'products', component: ProductsComponent },`

But it seems that it has now introduced a limitation and below route is no longer a valid route.

`{ path: '/', component: HomeComponent },`

Currently I am using below route but this isn't the desired solution, I want my home component to map to root of my application ie. to the url /.

`{ path: 'home', component: HomeComponent, terminal: true },`

Please also guide if the use of terminal: true is valid in this case? I guess its the replacement of index property (not sure though as its not in the documentation).

**Comment by ericmartinezr** [comment]
The repo for the router is here https://github.com/angular/vladivostok, also the slash and index are deprecated.

**Comment by naveedahmed1** [comment]
Thank you Eric, I will post new router related issues there.

If you could please tell, if the slash ha been depreciated is there any other way to achieve below route.
 
{ path: '/', component: HomeComponent },

I want the root of my website to map to the HomeComponent.

**Comment by ericmartinezr** [comment]
See the changelog in the corresponding repo https://github.com/angular/vladivostok/blob/master/CHANGELOG.md#breaking-changes

**Comment by naveedahmed1** [comment]
Thank you so much Eric really appreciate your help :)

Will they eventually merge the router at https://github.com/angular/vladivostok in Angular 2? or will it be   treated as a separate project from now onward?

**Comment by ericmartinezr** [comment]
@naveedahmed1 as far as I know it will eventually be merged, but for now it is under its own repo.

**Comment by naveedahmed1** [comment]
Though you mentioned that its not the repo of the new router but since you are familiar with the new router. I want to ask one more question and would appreciate if you could please help.

I know that in new router we can access route parameters using below code:

```
this.activatedRoute.params
            .map(params => params['id'])
            .subscribe((id) => {

             //use param id

             });
```

This works for single parameter but can you please guide how do we access multiple parameters.

For example if we have below route

pathToComponent/param1/param2

**Comment by ericmartinezr** [comment]
@naveedahmed1 I'm not really familiarzed with the new router, you'll better be asking here https://gitter.im/angular/angular since the repository is for reporting issues related to the framework.

**Comment by naveedahmed1** [comment]
Thank you, Got it!

**Comment by mathjoy** [comment]
export const routes: RouterConfig = [
  { path: '',      component: Home },
  { path: 'home',  component: Home },
  // make sure you match the component type string to the require in asyncRoutes
  { path: 'about', component: 'About',
    resolve: {
      'yourData': DataResolver
    }},
  // async components with children routes must use WebpackAsyncRoute
  { path: 'detail', component: 'Detail',
    canActivate: [ WebpackAsyncRoute ],
    children: [
      { path: '', component: 'Index' }  // must be included
    ]
  },
  { path: '**',    component: NoContent },
];

**Comment by mahidhar4** [comment]
While using this Version of Router , View Is Not initializing for some times. got this issue while navigating to the same view with different state params data
