### ISSUE TITLE
Leaving animation (* => void) ignored when routerLink used

### ISSUE THREAD

**Issue by vsimak** [angular/angular#9350]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When we have an element animated via trigger, and we specified the entering ('void => _') and exiting ('_ => void') transitions, when there is a change in routerLink the exiting transitions is ignored / and cut, while the entering transition works fine.

**Expected/desired behavior**
As this is not something that has been talked about yet nor there is anything written on the subject of Animate and routerLinking, I might be at fault but going by the ng1 animate, there ought to be something that signals to the router that it needs to delay the removal of the relevant component from the view so the exiting transition animation can be played out. The Matias May ng-conf repo and the current live official docs plunker both show examples which do not interact with router.

**Reproduction of the problem**
http://plnkr.co/edit/IJoaB7ifVPJqX0NrUIpV
Using the v3 router.

**What is the expected behavior?**
Router delaying the Destroy/Remove of the component from the View so that the leaving transition animation can be seen.
**What is the motivation / use case for changing the behavior?**
We are strongly advocating an app-like web user experience, where the transitions play the pivotal role.

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.2
- **Browser:** [Chrome 51.0.2704.84 (64-bit) ] 
- **Language:** [TypeScript 1.9]

**Comment by CaptainCodeman** [comment]
I think that was the original reason for the router outlet being a placeholder rather than a container - both views need to exist at the same time for a period while the transition is animated. There was also going to be the anchored elements that could be animated between the source and destination views as demo'd at ng-conf 2015:

https://youtu.be/R0OrxxJNcjU?list=PLOETEcp3DkCoNnlhE-7fovYvqwVPrRiY7&t=497

**Comment by vsimak** [comment]
Yeah. Good anchoring really is a rally point of app-like smooth interface.
Now I am wondering whether this is on the roadmap, or it exists and is just not documented.

**Comment by matsko** [comment]
@vsimak yes we do have a proper solution in mind for routable animations ... Something that involves controlling multiple elements at a time with animations via an animation method called **query()**. There are a few things first that need to get resolved until that's ready. So for the time being once #9044 is in then we can have an interm solution for routable animations by placing enter and leave animations on each routeable component within its `:host` properties.

**Comment by wootencl** [comment]
Hi @matsko. Any ideas when that interim solution will be released? Curious if I should implement a work around or just wait it out if it's not going to be too long. Thanks!

**Comment by vsimak** [comment]
So just an update since I am following closely (got way too many sites on production) matsko's reply here was all you need @wootencl : - just scroll down in regards to routeranimations and :host
https://github.com/angular/angular/issues/9845

**Comment by wootencl** [comment]
Thanks @vsimak for getting back to me! Been keeping a close eye on the upcoming RC.5 and am very excited with what I see. Even more so now that this has been merged in. One of the last pieces I need to finish a web app I've been working on.

**Comment by andrui** [comment]
If someone is interested, here is modified [plunker](http://plnkr.co/edit/yJHjL5ap9l4MwOimCyyY?p=preview) from the initial post with routing animation.

**Comment by MadUser** [comment]
Thanks, This is nice feature for the router, but nested router gets the same animations of their father which is undesirable

**Comment by akomm** [comment]
The exit transition is also ignored, when a component is detached by *ngIf

**Comment by gubagu** [comment]
The :leave / * => void transition ignored with *ngFor too.

**Comment by piotr-gawlowski** [comment]
Also my **:enter** animation works with programmatically  created components
But when destroyed
this.contentCmpRef.destroy();
**:leave** is not triggered

**Comment by MA-Maddin** [comment]
@akomm and @gubagu 
make sure to apply the animation to the host element / the component itself. Not to an element within component.
And make it `display: block;`.

Code in your animated `Component`:

```
animations: [
  trigger('flyInOut', [
    state('in', style({transform: 'translateX(0)'})),
    transition('void => *', [
      style({transform: 'translateX(-100%)'}),
      animate(1000)
    ]),
    transition('* => void', [
      animate(1000, style({transform: 'translateX(100%)'}))
    ])
  ])
],
host: {
  '[@flyInOut]': 'true',
  'style': 'display: block;'
},
```

**OR**

if your `animations` is declared in the parent `Component`, implement the child component, which should be animated, like this:

`<my-child-comp [@flyInOut] style="display: block;"></my-child-comp>`

----

Then the removal of element will wait for the end of `* => void` animation.

**Comment by matsko** [comment]
Closing this issue since it has almost been one year since any activity. If this is still not behaving as expected, please reopen the issue and I'll investigate.

**Comment by gubagu** [comment]
@matsko Closing this issue does not solve it.
@MA-Maddin Could you please provide a working Plunker example instead of referencing to gifs. Thank you!
