### ISSUE TITLE
Angular 2 Tutorial Should Default To Javascript, not Typescript

### ISSUE THREAD

**Issue by JemiloII** [angular/angular#9352]
Angular 2 Tutorial Should Default To Javascript, not Typescript. It's annoying to have to go to a drop down menu to find it. The community is not going to rush to typescript nor should they be forced to. Defaulting to typescript creates an entry barrier as many may just give up after wondering what typescript is. It's extra overhead.

**Comment by robwormald** [comment]
we strongly suggest using Typescript with Angular2, and thus it will remain the preferred language in the docs.
