### ISSUE TITLE
innerHtml injects html content inside node attribute in RC.2

### ISSUE THREAD

**Issue by RomanGotsiy** [angular/angular#9353]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
`innerHtml` injects whole HTML content into DOM node attribute `ng-reflect-inner-h-t-m-l`.
Moreover, it also uses sanitization and if HTML content has newlines it prints tons of warnings to the console:

      WARNING: sanitizing HTML stripped some content.

In case sanitization is bypassed it injects content with newlines into the attribute (check the picture bellow):

![](http://i.imgur.com/Ukq0jba.png)

**Expected/desired behavior**
`innerHtml` should not inject HTML content into node attribute (it worked exactly like this on RC.1)

**Reproduction of the problem**
http://plnkr.co/edit/3X6iA76foCBVZkjdlmkX

**What is the motivation / use case for changing the behavior?**
`innerHtml` content may be really huge so I believe it is an overkill to inject this into DOM attribute. Also, it may need to contain newlines. For example, I'm using `innerHtml` for inserting markdown rendered content into my component (`<pre>` blocks require newlines).

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.2 (reproducible **both in dev and production** mode)
 
* **Browser:** [all] 
 
* **Language:** [Typescript]

**Comment by vicb** [comment]
This behavior is only active in *dev mode* - prod mode does not work with rc2 which is why you still see the same behavior.

**Comment by RomanGotsiy** [comment]
Thanks.
I've tried to apply workaround from https://github.com/angular/angular/issues/8508 and it resolved the issue.
Also, I've just checked and this issue seems to be already fixed by [ tbosch@838f3a6](https://github.com/tbosch/angular/commit/838f3a686f998ee32b5568402fdb570dcbbcbd46#diff-50201d02612554c3edfad99b9b394314L40).

So closing this.
