### ISSUE TITLE
Feature Request / Bug: something => void Animation Only Works with *ngIf on the Same Element 

### ISSUE THREAD

**Issue by sqwk** [angular/angular#9354]
**Current behavior**

Animation from `something => void` only works if the `*ngIf` is on the element that is animated and not if it is on an element further up the chain.

Animating from `void => something` works both ways.

**Expected/desired behavior**

Elements being animated should animate out no matter where the `*ngIf` is located, since they are still being removed from the DOM.

**Reproduction of the problem**

See here for a demo: http://plnkr.co/edit/PIt2pxTFoSRprYP4Tw2O?p=preview

**What is the motivation / use case for changing the behavior?**

Consistency with the `void => something` animation + easier to use.

**Comment by matsko** [comment]
I see what you mean here. Yes this is definitely something that should work automatically even if the `void` trigger is a parent container. I will look into this.

**Comment by skreborn** [comment]
@matsko Shouldn't the animation actually apply _only_ to the element that has the `*ngIf`?

Let's say that I have a list (`<ul>`) of items (`<li>`). In this scenario, both the list and the individual items have animations to and from a `void` state.
* Every time I add or remove an item, I would like that specific item to be animated.
* That's all well and good, but I would also like to be able to dispose of the whole list later on, and this time, I would like **only** the container to animate. I don't want to see the list items animating out to their `void` state while the parent does the same. The items should no longer act as individuals. They should animate out with the container.

Sorry if I misunderstood any of you and/or my comment is absolutely irrelevant.

**Comment by sqwk** [comment]
Is there any news on how this should be handled? (Both scenarios could be needed by different users: Animate just the parent container or animate children parallel to the parent container.)

**Comment by matsko** [comment]
So this is to be handled using `query` and `animateChild` going forward. This issue can be used to track this change: https://github.com/angular/angular/issues/20674
