### ISSUE TITLE
RC2. iframe with binded src value is reloaded on any angular interaction

### ISSUE THREAD

**Issue by kamarouski** [angular/angular#9357]
Environment: angular 2 rc2, Chrome

In my app I'm using iframes to display some external content. The URL for the iframe src is generated by angular component. so I have something like this in my template

``` <iframe [attr.src]="source"  [ngStyle]="frameCss"></iframe> ```

Compionent code is the following

```
...
export default class MyComponent {
    @Input() height: number;
    @Input() width: number;

    constructor(private _sanitizer: DomSanitizationService) {
    }

    get source() : SafeUrl {
        let url = '%URL%';
        return this._sanitizer.bypassSecurityTrustResourceUrl(url);
    }

    get frameCss() : Object {
        return {
            'width': this.width + 'px',
            'height': this.height + 'px'
        }
    }
}
...
```

The issue is that on every Angular 2 interaction (regardless of origin)  iframe content is reloaded. It looks like angular 2 updates iframe src value which triggers iframe reload though src value stays the same.

**Expected/desired behavior**
iframe is not reploaded if src URL is the same.

**Comment by robwormald** [comment]
this is because you are using a getter method, which is re-executed every time change detection runs, which returns a new instance of the sanitized URL (wrapper). 

It's generally better to set properties once, rather than having them repeatedly re-computed.

**Comment by kamarouski** [comment]
thanks @robwormald! 

I've changed the getter to return the same instance of SafeUrl and it solved the problem.
