### ISSUE TITLE
$transclude.isSlotFilled returns true when the only DOM element returned is a comment

### ISSUE THREAD

**Issue by mboudreau** [angular/angular#9358]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
While using multi-slot transclusion, I'm calling the `isSlotFilled` function to see if it's being used.  Within one of those transclusion, I have an `ng-if` on the transclusion element itself and it returns false, hence removing the DOM element, the `isSlotFilled` still returns true even though no real DOM element is currently filling it except the `ng-if` comment.

**Expected/desired behavior**
If the only DOM element within multi-slot transclusion are comments, `isSlotFilled` function should return false, not true.

**Reproduction of the problem**
http://plnkr.co/edit/NCBtZk5eahNjpU2Vkq00

**What is the expected behavior?**
To quote the angular docs: 
> The $transclude function also has a method on it, $transclude.isSlotFilled(slotName), which returns true if the specified slot contains content (i.e. one or more DOM nodes). 

The issue is that, in my opinion, comments shouldn't be considered DOM nodes, especially the ones injected by Angular

**What is the motivation / use case for changing the behavior?**
I want to remove the transclusion from showing up if it's not needed.

**Please tell us about your environment:**

* **Angular version:** 1.5.6
 
* **Browser:** [all ] 
 
* **Language:** [ ES5 ]

**Comment by zoechi** [comment]
https://github.com/angular/angular.js is the repo for Angular.js, this is Angular2

**Comment by mboudreau** [comment]
God damnit.  sorry.
