### ISSUE TITLE
isDevMode is not exported from @angular/core

### ISSUE THREAD

**Issue by frederikschubert** [angular/angular#9360]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
`isDevMode` is not exported from `@angular/core`.

**Expected/desired behavior**
`isDevMode` should be exported from `@angular/core`.

**What is the motivation / use case for changing the behavior?**
I am using @ngrx/store with [ngrx-store-logger](https://github.com/btroncone/ngrx-store-logger) and only want to use the logger in development mode. This can not be achieved through different code paths during bootstrap. So I need a way to detect the mode.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.1
 
* **Browser:** all 
 
* **Language:** TypeScript 1.8.10

**Comment by vicb** [comment]
@tbosch could you please take a look ?Thanks

**Comment by frederikschubert** [comment]
I saw [here](https://github.com/angular/angular/blob/master/modules/@angular/core/index.ts#L9) that it's exported correctly but somehow this doesn't find its way into the npm distribution.

**Comment by vicb** [comment]
@tbosch has updated the file end of last week. It should be released in rc.3

**Comment by frederikschubert** [comment]
Great! Thanks for the quick reaction!
