### ISSUE TITLE
Cannot bind template reference variables to ngModel in new forms in rc2

### ISSUE THREAD

**Issue by ospaarmann** [angular/angular#9363]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[x] feature request
```

**Current behavior**
When using the new forms with rc2 binding a template reference variable to `ngModel` doesn't work as described in the [new form proposal](https://docs.google.com/document/u/1/d/1RIezQqE4aEhBRmArIAS1mRIZtWFf6JxN_7B4meyWK0Y/pub). The error I'm getting is:

```
EXCEPTION: Error: Uncaught (in promise): Template parse errors:
There is no directive with "exportAs" set to "ngModel" (" type="text" class="form-control"
 formControlName="email" [(ngModel)]="admin.email" [ERROR ->]#email="ngModel">
 <div *ngIf="loginForm.hasError('required', 'email') && email.touched" c"): LoginComponent@12:66
There is no directive with "exportAs" set to "ngModel" ("assword" class="form-control"
 formControlName="password" [(ngModel)]="admin.password" [ERROR ->]#password="ngModel">
 <div *ngIf="loginForm.hasError('required', 'password') && password.t"): LoginComponent@19:70
```

**Expected/desired behavior**
It should be possible to bind a template reference variable to `ngModel` to check if a field is valid, touched, pristine, etc. Like so:

```
<input [(ngModel)]="person.name.first" #first="ngModel">
<input [(ngModel)]="person.name.last">
{{ first.valid }}  // true
```

**Reproduction of the problem**
Trying to bind ngModel to a template reference variable.

**What is the motivation / use case for changing the behavior?**
To show custom error messages, like so:

```
<input type="text" class="form-control"
  formControlName="email" [(ngModel)]="admin.email" name="email" #email="ngModel">
<div *ngIf="loginForm.hasError('required', 'email') && email.touched" class="alert alert-danger">Email is required</div>
<div *ngIf="loginForm.hasError('pattern', 'email') && email.touched" class="alert alert-danger">Not a valid email address</div>
```

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.2
 
* **Browser:** [all] 
 
* **Language:** [TypeScript 1.8.10 | ES5]

**Comment by ericmartinezr** [comment]
That change was made 5 days ago https://github.com/angular/angular/pull/9240, it's not in RC.2

**Comment by vicb** [comment]
Will be released in rc.3 (thanks @ericmartinezr)

**Comment by agarwali** [comment]
Hi, I had the same problem and I'm getting the same template parse error in rc.3. Below is the input field code i'm using.
```
<form  #employee_form="ngForm" [formGroup]="employeeForm" (ngSubmit)="onSubmit()">
<input #first_name="ngModel"
            [(ngModel)]="employee.first_name"
            formControlName="first_name"
            type="text"
            id="first_name"
            [ngClass]="{invalid: first_name.touched && !first_name.valid}"
            name="first_name">
<!--Other form elements-->
<form>
```

**Comment by ericmartinezr** [comment]
@agarwali I tried your code and I failed, look at this plnkr http://plnkr.co/edit/07t8g3XXDXiNrmdsL4NY?p=preview, I even included ngModel (imported from @angular/forms) manually and it keeps throwing the same message.

@vicb would you mind to re-open this issue again? There's a plnkr for someone who knows to look at it. It's weird because the ng_model directive has [that line](https://github.com/angular/angular/blob/master/modules/@angular/forms/src/directives/ng_model.ts#L45).

**Comment by agarwali** [comment]
@ericmartinezr thanks for your quick response. I actually looked into my node_modules folder i don't have the file ng_model.ts. But I do have the a file ng_mode.d.ts, which doesn't even have the directive decorator. Not sure if this is related to my node_modules or sth else.

**Comment by ericmartinezr** [comment]
@agarwali the new forms should be installed `npm install @angular/forms --save`, currently it's on version 0.1.1 for what I see, but I still found strange that it throws that message, I haven't played enough with it though.

**Comment by kara** [comment]
@ericmartinezr  Thanks for taking a look at this and creating a plunker. I reviewed the plunker code, and it looks like you're using both `formControlName` and `ngModel`.   In that case, the only activated directive is actually `formControlName` - it simply uses `ngModel` as an input property.  For that reason, trying to export `ngModel` won't work.   The preferred way to access the data would be through the backing `FormControl

The reactive form directives do not export directly, as we expect there to be a backing `FormControl` instance on your class that you can refer to for its data instead.    If you add that to your class

**Comment by ericmartinezr** [comment]
@kara Thanks a lot for clarifying it!!!

**Comment by agarwali** [comment]
@kara I used the ngModel to be able to access the properties of that formControl, such as to check if it is valid. So, what would be an alternative approach to access the properties of the formControl?

**Comment by kara** [comment]
@agarwali  You can save a reference to the `FormControl` instance when you create it in your class, before passing it to the `FormGroup`.  Then it's easy to access it in your view like any other property on your class. 

See this plunker for an example: http://plnkr.co/edit/G6jWu91ng7sOnvdYyAV7?p=preview

Worth noting: we should definitely make this easier and more intuitive.  There are more improvements to come! Will definitely consider this case.

**Comment by aryeh** [comment]
Just to beat a dead horse.  The moment you have a group inside a group it already becomes a bit unwieldly.  You need to traverse through the controls member of each level as shown in the `ngIf` below.  Unless I'm not doing this correctly.

```
<form class="form form-horizontal" [formGroup]="form" (ngSubmit)="onSubmit()">
    <div class="form-group">
      <label for="group1">Group 1</label>
      <div formGroupName="group1">
      <input type="text" class="form-control" name="item1" [(ngModel)]="mymodel.item1"  formControlName="item1">
      </div>
      <div 
        *ngIf="!form.controls.group1.controls.item1.valid"
        class="alert alert-danger">This field is required</div>
    </div>
  </form>
```

**Comment by kara** [comment]
Yeah, it is a bit unwieldy, I agree. You can use the `find` function as some syntactic sugar, but it's not much shorter. This is one of the things I think we can improve on.

**Comment by screenm0nkey** [comment]
On the excellent thoughttam blog Pascal says we should be able to access the exported form control as below but the resulting code generates "There is no directive with "exportAs" set to "formControl"". 

```
<form [formGroup]="registerForm">
  <label>Firstname:</label>
  <input type="text" formControlName="firstname" #firstname="formControl">
  <p *ngIf="firstname.error">This field is required!</p>
```

**Comment by kara** [comment]
Unfortunately, that's not correct. Reactive form control directives are not exported because you can access their controls directly from the class. See: https://github.com/angular/angular/issues/9363#issuecomment-227883430

**Comment by screenm0nkey** [comment]
Thanks Kara :)

**Comment by sharpmachine** [comment]
So did instance variables get taken away from us with @angular/forms 0.2.0? 

This used to work:

```html
<div class="form-group">
    <label for="testField">Test Field</label>
    <input type="text"
        id="testField"
        class="form-control"
        name="testField"
        [(ngMode)l]="testField"
        #testField="ngModel
        required>
    <pre>{{testField.valid}}</pre>
  </div>
```
But now we have to do the MUCH more verbose:

```html
<div class="form-group">
    <label for="testField">Test Field</label>
    <input type="text"
        id="testField"
        class="form-control"
        [formControl]="subjectDetailsForm.find('testField')"
        [(ngModel)]="testField"
        required>
    <pre>{{subjectDetailsForm.controls['testField'].valid}}</pre>
  </div>
```
Is that correct?

**Comment by kara** [comment]
No, that's not correct.  Exports simply don't exist for reactive form directives (formControlName, formGroupName, etc) because it would be duplicative.  There are already convenient ways to refer to them from the component class.

If you are using a template-driven strategy (as it looks in your examples, you can still export ngModel.

```
<div class="form-group">
    <label for="testField">Test Field</label>
    <input type="text"
        id="testField"
        name="testField"
        [(ngMode)l]="testField"
        #testField="ngModel">
    <pre>{{testField.valid}}</pre>
  </div>
```

**Comment by sharpmachine** [comment]
@kara I'm doing the model-driven form approach.

**Comment by kara** [comment]
Can you be more specific?  In your first example, you listed only "ngModel", and as I mentioned, in that case the code does not have to change. 

If you're trying to bind a single form control with the `formControl` directive, then you already have a reference to that form control. It's whatever you created in the class.

If you're trying to bind a form control that is part of a larger form group, then you can save a reference to that control when you add it in your class.  Please see: http://plnkr.co/edit/G6jWu91ng7sOnvdYyAV7?p=preview

**Comment by sharpmachine** [comment]
Thanks @kara. So what if I have a form with 15 fields? I would have to create a property for each field on the component class. Whereas before I could use `#var` instance variable.  I guess I'm missing something.

**Comment by eques** [comment]
I’ve used[ this variant](http://plnkr.co/edit/c9D0R58vadLopH5rUNeg?p=preview), and everything was ok, until i’m not trying to use TestComponentBuilder. Then i also see this error. Is it as expected?

**Comment by byorty** [comment]
Hi, @kara i have error 'There is no directive with "exportAs" set to ngModel' in rc.4 if i use ngModel with textarea: http://plnkr.co/edit/VJTYj24yZt9MdctaEVdb?p=preview
I didn't find nothing about using textarea and ngModel in docs(

**Comment by kara** [comment]
@byorty It looks like your binding is inverted :)  It should be `[(ngModel)]` rather than `([ngModel])`.  If you correct that error, the form seems to work: http://plnkr.co/edit/3aVuWtMX60kXXLVnsh8t?p=preview.

@sharpmachine Yeah, that's not ideal.  If you have that many, `find()` might be a better option, but we are definitely looking for a better long-term solution. Stay tuned.

**Comment by byorty** [comment]
Thanks @kara, sorry)))

**Comment by sharpmachine** [comment]
Thanks @kara

**Comment by crtormen** [comment]
@kara It seems that Angular team is discouraging template driven model usage, am I right? 
I ask this because I am in doubt about which model to follow in my project. 
Thanks

**Comment by kamran-pervaiz** [comment]
@kara @ericcarraway 
I have same error but not on UI but during unit testing. when I am injecting TestComponentBuilder its give me error

```
LOG: 'error occured: Template parse errors:
There is no directive with "exportAs" set to "ngModel" (" name="supplierName" class="form-control" required
                       [(ngModel)]="model.name" [ERROR ->]#supplierName="ngModel"/>
                <div [hidden]="supplierName.valid || supplierName.pristine"): SupplierFormComponent@9:48
There is no directive with "exportAs" set to "ngModel" ("class="form-control" name="country" required
                        [(ngModel)]="model.countryId" [ERROR ->]#country="ngModel">
                    <option *ngFor="let country of countries" [value]="country.i"): SupplierFormComponent@66:54
There is no directive with "exportAs" set to "ngModel" (""contactName" class="form-control" required
                       [(ngModel)]="model.contactName" [ERROR ->]#contactName="ngModel"/>
                <div [hidden]="contactName.valid || contactName.pristine" c"): SupplierFormComponent@93:55
There is no directive with "exportAs" set to "ngModel" ("ontactEmail" class="form-control" required
                       [(ngModel)]="model.contactEmail" [ERROR ->]#contactEmail="ngModel" />
                <div [hidden]="contactEmail.valid || contactEmail.pristin"): SupplierFormComponent@118:56'
```

my code to test

```
var builder;

    beforeEach(() => {
        addProviders([
            provide(AppService, { useClass: MockAppService })
        ]);
    });

    beforeEach(inject([TestComponentBuilder], (tcb) => {
        builder = tcb;
    }));
it('should create Supplier Component', async(() => {
        builder
            .overrideProviders(
                SupplierFormComponent,
                [{ provide: AppService, useClass: MockAppService }]
            )
            .createAsync(SupplierFormComponent)
            .then((fixture: ComponentFixture<SupplierFormComponent>) => {
                fixture.detectChanges
                var compiled = fixture.debugElement.nativeElement;
                console.log(compiled);
            })
            .catch((error) => {
                console.log("error occured: " + error);
            });
    }));
```

Is there a specific way to create component as part of unit testing? I read somewhere that there was a bug using templateUrl when unit testing and have to use **overridetemplate** but apparently it has been fixed. so i am not sure what i am doing wrong here.

**Comment by kara** [comment]
@kamran-pervaiz  From your sample code, it looks like you're not providing the new forms module.  If you want to use the ngModel export, you need to add the same providers to your tests as you did to your bootstrap.

```ts
addProviders([
   disableDeprecatedForms(),
   provideForms(),
   provide(AppService, { useClass: MockAppService }
])
```

**Comment by baghdadisan** [comment]
I have the error : There is no directive with "exportAs" set to "ngForm" in my template : 
```
<div class="form-group">
        <label for="actionType">Action Type</label>
        <select
            ngControl="actionType" 
      ===>  #actionType="ngForm" 
            id="actionType" 
            class="form-control" 
            required>
            <option value=""></option>
            <option *ngFor="let actionType of actionTypes" value="{{ actionType.label }}">
                {{ actionType.label }}
            </option>
        </select> 
    </div>
```

**Comment by kara** [comment]
@baghdadisan  You're enabling the new forms API, but you're using the old one in your code. You might want to read docs on the new syntax [here](https://angular.io/docs/ts/latest/guide/forms.html).

**Comment by baghdadisan** [comment]
thank you Kara for you're answer, i've change it to the new API : 

```
    <div class="form-group">
        <label for="actionType">Action Type</label>
        <select
            ngModel
            name="actionType" 
            #actionType="ngModel" 
            id="actionType" 
            class="form-control" 
            required>
            <option value=""></option>
            <option *ngFor="let actionType of actionTypes" value="{{ actionType.label }}">
                {{ actionType.label }}
            </option>
        </select> 
    </div>
```

but now i'm having this error : Cannot assign to a reference or variable!

**Comment by kamran-pervaiz** [comment]
@kara 

thanks for your reply, it seems it fixed the error but I need to figure out http provider as part of AppService. I am using Mock class so it should not give below error. I will try to find other way to fix it.

```
LOG: 'error occured: EXCEPTION: Error in http://localhost:9876/base/dist/app/supplier/supplier-form.component.js class SupplierFormComponent_Host - inline template:0:0
ORIGINAL EXCEPTION: No provider for Http! (AppService -> Http)
ORIGINAL STACKTRACE:
Error: DI Exception
    at NoProviderError.BaseException [as constructor] (http://localhost:9876/base/dist/vendor/@angular/core/src/facade/exceptions.js:27:23)
    at NoProviderError.AbstractProviderError [as constructor] (http://localhost:9876/base/dist/vendor/@angular/core/src/di/reflective_exceptions.js:43:16)
    at new NoProviderError (http://localhost:9876/base/dist/vendor/@angular/core/src/di/reflective_exceptions.js:80:16)
    at ReflectiveInjector_._throwOrNull (http://localhost:9876/base/dist/vendor/@angular/core/src/di/reflective_injector.js:786:19)
    at ReflectiveInjector_._getByKeyDefault (http://localhost:9876/base/dist/vendor/@angular/core/src/di/reflective_injector.js:814:25)
    at ReflectiveInjector_._getByKey (http://localhost:9876/base/dist/vendor/@angular/core/src/di/reflective_injector.js:777:25)
    at ReflectiveInjector_._getByReflectiveDependency (http://localhost:9876/base/dist/vendor/@angular/core/src/di/reflective_injector.js:767:21)
    at ReflectiveInjector_._instantiate (http://localhost:9876/base/dist/vendor/@angular/core/src/di/reflective_injector.js:664:36)
    at ReflectiveInjector_._instantiateProvider (http://localhost:9876/base/dist/vendor/@angular/core/src/di/reflective_injector.js:636:25)
    at ReflectiveInjector_._new (http://localhost:9876/base/dist/vendor/@angular/core/src/di/reflective_injector.js:625:21)
    at ReflectiveInjectorDynamicStrategy.getObjByKeyId (http://localhost:9876/base/dist/vendor/@angular/core/src/di/reflective_injector.js:277:50)
    at ReflectiveInjector_._getByKeyDefault (http://localhost:9876/base/dist/vendor/@angular/core/src/di/reflective_injector.js:805:38)
    at ReflectiveInjector_._getByKey (http://localhost:9876/base/dist/vendor/@angular/core/src/di/reflective_injector.js:777:25)
    at ReflectiveInjector_.get (http://localhost:9876/base/dist/vendor/@angular/core/src/di/reflective_injector.js:586:21)
    at DebugAppView._View_SupplierFormComponent_Host0.createInternal (SupplierFormComponent.template.js:16:88)
    at DebugAppView.AppView.create (http://localhost:9876/base/dist/vendor/@angular/core/src/linker/view.js:96:21)
    at DebugAppView.create (http://localhost:9876/base/dist/vendor/@angular/core/src/linker/view.js:308:44)
    at ComponentFactory.create (http://localhost:9876/base/dist/vendor/@angular/core/src/linker/component_factory.js:157:36)
    at OverridingTestComponentBuilder.TestComponentBuilder.createFromFactory (http://localhost:9876/base/dist/vendor/@angular/core/testing/test_component_builder.js:91:45)
    at eval (http://localhost:9876/base/dist/vendor/@angular/core/testing/test_component_builder.js:105:76)
    at F (http://localhost:9876/base/dist/vendor/systemjs/dist/system-polyfills.js?a9f0c97e865a53da4c067b98cf2e65a23b2f0608:4:7484)
    at H (http://localhost:9876/base/dist/vendor/systemjs/dist/system-polyfills.js?a9f0c97e865a53da4c067b98cf2e65a23b2f0608:4:7116)
    at q.when (http://localhost:9876/base/dist/vendor/systemjs/dist/system-polyfills.js?a9f0c97e865a53da4c067b98cf2e65a23b2f0608:4:10790)
    at b.run (http://localhost:9876/base/dist/vendor/systemjs/dist/system-polyfills.js?a9f0c97e865a53da4c067b98cf2e65a23b2f0608:4:9826)
    at t._drain (http://localhost:9876/base/dist/vendor/systemjs/dist/system-polyfills.js?a9f0c97e865a53da4c067b98cf2e65a23b2f0608:4:1744)
    at drain (http://localhost:9876/base/dist/vendor/systemjs/dist/system-polyfills.js?a9f0c97e865a53da4c067b98cf2e65a23b2f0608:4:1398)
    at MutationObserver.e (http://localhost:9876/base/dist/vendor/systemjs/dist/system-polyfills.js?a9f0c97e865a53da4c067b98cf2e65a23b2f0608:4:3319)
    at ZoneDelegate.invoke (http://localhost:9876/base/dist/vendor/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:323:29)
    at Zone.runGuarded (http://localhost:9876/base/dist/vendor/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:230:48)
    at MutationObserver.<anonymous> (http://localhost:9876/base/dist/vendor/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:206:30)
ERROR CONTEXT:
[object Object]'
Chrome 51.0.2704 (Windows 7 0.0.0): Executed 2 of 2 SUCCESS (0.254 secs / 0.244 secs)
```

**Comment by Asrapromact** [comment]
Hi @kara  I am facing similar issue ,I get the below error in my console. I am new to angular and have just updated the angular to rc5.

zone.js:461 Unhandled Promise rejection: Template parse errors:
**There is no directive with "exportAs" set to "ngForm" ("
                </td>
                <td>
                    <input type="password" [ERROR ->]#OldPassword="ngForm" ngControl="OldPassword" [(ngModel)]="passwordModel.OldPassword" 
             "): ChangePasswordComponent@10:43
There is no directive with "exportAs" set to "ngForm" ("
                </td>
                <td>
                    <input type="password" [ERROR ->]#NewPassword="ngForm" ngControl="NewPassword" [(ngModel)]="passwordModel.NewPassword" 
             "): ChangePasswordComponent@22:43
There is no directive with "exportAs" set to "ngForm" ("**


_Below is my html code:-_
`
    <form #PasswordChangeForm="ngForm">
        <table>
            <tr>
                <td>
                    <b>Current Password: </b>
                </td>
                <td>
                    <input type="password" #OldPassword="ngForm" ngControl="OldPassword" [(ngModel)]="passwordModel.OldPassword" 
                           (blur)="newPasswordIsSame(passwordModel.NewPassword, passwordModel.OldPassword, passwordModel.ConfirmPassword)" required/>
                    <div *ngIf="OldPassword.touched && !OldPassword.valid && OldPassword.errors.required" style="color:red">
                        Required!!
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <b>New Password: </b>
                </td>
                <td>
                    <input type="password" #NewPassword="ngForm" ngControl="NewPassword" [(ngModel)]="passwordModel.NewPassword" 
                           (blur)="newPasswordIsSame(passwordModel.NewPassword, passwordModel.OldPassword, passwordModel.ConfirmPassword)" required/>
                    <div *ngIf="NewPassword.touched && !NewPassword.valid && NewPassword.errors.required" style="color:red">
                        Required!!
                    </div>
                    <div *ngIf="isSame" style="color:red">
                        New password is same as old password. <br/>
                        Please try a different password.
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <b>Confirm Password: </b>
                </td>
                <td>
                    <input type="password" #ConfirmPassword="ngForm" ngControl="ConfirmPassword" [(ngModel)]="passwordModel.ConfirmPassword" 
                           (blur)="matchPassword(passwordModel.ConfirmPassword, passwordModel.NewPassword)" required/>
                    <div *ngIf="ConfirmPassword.touched && !ConfirmPassword.valid && ConfirmPassword.errors.required && !isNotMatch" style="color:red">
                        Required!!
                    </div>
                    <div *ngIf="isNotMatch" style="color:red">
                        Passwords do not match!
                    </div>
                </td>
            </tr>
        </table>

        <div>
          >
            <button type="submit" (click)="changePassword(passwordModel)" [disabled]="!PasswordChangeForm.valid || isNotMatch || isSame">Change</button>
            <button type="submit" (click)="goBack()">Cancel</button>
        </div>
    </form>`

_Below is my ts file :_

```
import {Component, Input} from '@angular/core';
import { UserService }   from '../user.service';
import {PasswordModel} from '../user-password.model';
import {FORM_DIRECTIVES, FormBuilder, Validators } from '@angular/forms';
import {Router, ROUTER_DIRECTIVES, ActivatedRoute} from '@angular/router';
import {Md2Toast} from 'md2/toast';

@Component({
    templateUrl: './app/users/user-change-password/user-change-password.html',
    providers: [Md2Toast]
})

export class ChangePasswordComponent {
    isNotMatch: boolean;
    isSame: boolean;
    
    @Input()
    passwordModel: PasswordModel;

    constructor(private userService: UserService, private redirectionRoute: Router, private route: ActivatedRoute, private toast: Md2Toast) {
        this.passwordModel = new PasswordModel();
    }

    changePassword(passwordModel) {
        this.userService.changePassword(this.passwordModel).subscribe((result) => {
            if (result == true) {
                this.toast.show('Password changed successfully');
                this.redirectionRoute.navigate(['/']);
            }
            else if (result == false) {
                this.toast.show('Wrong password');                
            }
            
        }, err => {
            
        });
    }

    matchPassword(confirmPassword, newPassword) {
        if (confirmPassword == newPassword) {
            this.isNotMatch = false;
        }
        else {
            this.isNotMatch = true;
        }
    }

    newPasswordIsSame(newPassword, oldPassword, confirmPassword) {
        this.matchPassword(confirmPassword, newPassword);
        if (newPassword == oldPassword && (oldPassword != "" && newPassword != undefined)) {
            this.isSame = true;
        }
        else {
            this.isSame = false;
        }
    }

    goBack() {
        this.redirectionRoute.navigate(['/']);
    }
}
```

Any help would be much appreciated. Thanks in advance

**Comment by aryeh** [comment]
@Asrapromact to fix your code I'd do the following.

### Component 
1. insert FormBuilder into the constructor. I'll set it to `_formBuilder`
2. Have a public variable on the class i'll call `form`
3. OnInit should build the form with: 
```
this.form = this._formBuilder.group({ 
  input1: ['defaultValue', [Validator1, Validator2...]], 
  input2: [...],  
} );
```
 You're now done with the component

### Template
4. your form tag only needs `[formGroup]="form"  (ngSubmit)="onSubmit()" `   (we're referencing the variable "form" and onSubmit handler in your component class`
5. your inputs only need `formControlName="input1"` (or whatever you named your inputs in the formBuilder setup in step 3.
6. Strip out all that ngForm items.  
7. If you want a reference to an input you can just use `#myLocalName` without setting to anything. But you shouldn't need it at all. Reference your controls through `form.controls.input`

Github happens to be a poor venue for this type of material, as it isn't about a bug in the Angular library. It is better asked on StackOverflow, or Gitter.

**Comment by pstephenwille** [comment]
Same here, as [illustrated in the plunkr](https://plnkr.co/edit/aeToUX?p=info)
Console error message:
> There is no directive with "exportAs" set to "ngModel"
> [ERROR ->]#lname="ngModel"

**Comment by kara** [comment]
@pstephenwille You need to provide the new forms API. From your plunker, you're using the old one. https://plnkr.co/edit/iXEKPDIkbJQPSSs4Ksxv?p=preview

**Comment by kara** [comment]
I'm going to lock this thread, as it's become semi-giant and there isn't a bug. If you find something you think might be a real bug, please open a new issue.  Support questions should go to gitter, StackOverflow, etc.
