### ISSUE TITLE
feature-request(renderer): Provide "unlisten" method to complement "listen"

### ISSUE THREAD

**Issue by traviskaufman** [angular/angular#9368]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The renderer API currently has a [listen() method](https://angular.io/docs/ts/latest/api/core/index/Renderer-class.html#!#listen-anchor), which appears to be used for [adding event listeners](https://github.com/angular/angular/blob/master/modules/%40angular/platform-browser/src/dom/dom_renderer.ts#L151) to an elementRef. However, there does not seem to be a symmetric "unlisten" method exposed publicly anywhere.

**Expected/desired behavior**

It would be useful to expose an "unlisten" event as well (use case described below).

**What is the motivation / use case for changing the behavior?**

The Material Design Web team is very interested in developing UI components that can be reused idiomatically across the web platform. One of the ideas we have for this is to expose "adapters" for framework which want to wrap our components. These adapters behave very similar to ng2's Renderers in that the framework essentially instructs the UI component on how it should go about performing DOM ops, e.g. adding/removing classes, adding/removing event listeners, etc.

```typescript
@Component({
  template: `
  <div #uicomponent [class]="classes.join(' ')">stuff</div>
  `
  // ...
})
class MyComponent extends AfterViewInit {
  @ViewChild('uicomponent') uicomponentRef: ElementRef;
  private MdUIComponent uicomponent;
  classes: string[] = ['md-ui-component'];

  private _mdUiComponentAdapter = <IMdUIComponentAdapter>{
    addClass: (className: string) => {
      this.classes.push(className);
    },
    removeClass: (className: string) => {
      this.classes.splice(this.classes.indexOf(className), 1);
    }
    addEventListener: (type: string, listener: EventListener) => {
      this.renderer_.listen(this.uicomponentRef, type, listener);
    },
    removeEventListener: (type: string, listener: EventListener) => {
      // ???
      // this.uiComponentRef.nativeElement.removeEventListener(type, listener); => :(
    }
  }

  constructor(private renderer_: Renderer);

  ngAfterViewInit() {
    this.uicomponent = new MdUIComponent(this._mdUiComponentAdapter);
  }
}
```

With this method we'd need to be able to perform the ops through the renderer as if we were working with the native DOM ourselves. It seems like not exposing a symmetric event removal mechanism precludes us doing so.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.1
 
* **Browser:** all
 
* **Language:** TypeScript 1.8.x

**Comment by ericmartinezr** [comment]
`listen()` and `listenGlob()` both return a function to *unlisten* them

```
let myFunc = listen(...);

// Remove listener
myFunc();
```

**Comment by traviskaufman** [comment]
Ah, I see. That should work just as well. Thanks for the swift response!

**Comment by hiepxanh** [comment]
we need update the docs for this, I take few hour to just only investing this :(
