### ISSUE TITLE
Feat: Rename/Add support to ComponentResolver to handle a function that returns a promise

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#9375]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

You can provide a `Type` or a `string` and use the `SystemJsComponentResolver` to resolve a component for loading.

**Expected/desired behavior**

You should be able to also provide a function that returns a `Promise` to resolve a component for loading.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

In order to allow lazy loading in Webpack, there needs to be a way to return a promise that resolves a component. This support will be needed for the router also.

```js
export const routes: Routes = [
  {
    path: 'home',
    component: () => new Promise(resolve => {
      require.ensure([], require => {
        resolve(require('./pages/home').HomePage);
      })
    })
  }
];
```

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart] 

cc: @vsavkin @vicb @robwormald

**Comment by IgorMinar** [comment]
@tbosch this go against your plans that we discussed recently. can you please evaluate this feature requests? thanks

**Comment by tbosch** [comment]
`ComponentResolver` will soon be changed to be synchronous and not support SystemJS any more. The router can still support asynchronous component loading by allowing users to provide their own `ComponentFactories` via a callback. Need to think about this a bit more...

**Comment by ocombe** [comment]
I made a Webpack component resolver just like the SystemJS one that works with webpack 1 to lazy loading components (it generates chunks all by itself), the same way it works with the ngrx router.
Are you interested in the code or a PR ?

**Comment by gluix** [comment]
```
import { ComponentFactory, ComponentResolver, Type } from '@angular/core';

const _SEPARATOR = '#';

export class WebpackComponentyResolver implements ComponentResolver {
  constructor(private _resolver: ComponentResolver) {}

  resolveComponent(componentType: string): Promise<ComponentFactory<any>> {
    let [module, component] = componentType.split(_SEPARATOR);        
    if(!component) {
      return this._resolver.resolveComponent(require(module).default);
    } else {
      return this._resolver.resolveComponent(require(module)[component]);
    }
  }

  clearCache(): void {}
}
```

```
@Component({
  selector: 'app',
  template: `  
  `
})
export class AppComponent {
  constructor(private viewContainerRef: ViewContainerRef, private componentResolver: ComponentResolver){
  }

  ngAfterViewInit() {  
    var webpackResolver = new WebpackComponentResolver(this.componentResolver);
    var moduleString: string = './hello_world';     
    webpackResolver.resolveComponent(moduleString).then(factory => {      
      this.viewContainerRef.createComponent<any>(factory);      
    });

    var moduleString: string = './hello_person';      
    var componentString: string = 'HelloPerson';
    webpackResolver.resolveComponent(moduleString + '#' + componentString).then(factory => {      
      var component = this.viewContainerRef.createComponent<any>(factory);
      component.instance.name = 'tim';
    });
  }
}
```

```
import { Component } from "@angular/core";

@Component({
  selector: 'hello-world',
  template: `
  hello world
  `
})
export default class HelloWorld {
}
```

```
import { Component, Input } from "@angular/core";

@Component({
  selector: 'hello-person',
  template: `
  hello {{name}}
  `
})
export class HelloPerson {
  @Input() name : string;
}
```

**Comment by TheLarkInn** [comment]
Also calling `System.import` in webpack2 will be supported.

https://gist.github.com/sokra/27b24881210b56bbaff7#dynamic-expressions

```javascript
route(path, query) {
    return System.import("./routes/" + path + "/route")
        .then(route => new route.Route(query));
}
// This creates a separate chunk for each possible route
```

> It's possible to pass an partial expression to System.import. This is handled similar to expressions in CommonJS (webpack creates a context with all possible files). System.import creates a separate chunk for each possible module.

**Comment by tbosch** [comment]
We will soon have a new story for lazy loading. The idea is not to lazy load components but rather application modules which can have multiple root components as well as top level providers. 

Components can soon be resolved via a new mechanism called `ComponentFactoryResolver`, see https://github.com/angular/angular/issues/9467 and [the corresponding design doc](https://docs.google.com/document/d/1VRNljdv-6QDY4_I0xx3DHd-IZ19QlthheMLdGGKAAzM/edit#).

I.e. soon (before final) we will deprecate `ComponentResolver`.

Closing this issue therefore.
