### ISSUE TITLE
<input id="cb" type="checkbox" ngControl="cb" checked>

### ISSUE THREAD

**Issue by atyapin** [angular/angular#9379]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When one puts <input id="cb" type="checkbox" ngControl="cb" checked> in template html initial value for #cb is null

**Expected/desired behavior**
#cb should be checked

**Reproduction of the problem**
http://plnkr.co/edit/f0VwRvHQh2Bw08985aiI

**What is the expected behavior?**
checked checkbox should be checked

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [Chrome | Firefox | Edge ] 
 
* **Language:** [TypeScript]

**Comment by vicb** [comment]
Seems like it works just fine with the newest form API (see the console logs in your plunkr for more details).

http://plnkr.co/edit/HFDTY5Bz063q2kyBZag9?p=preview

**Comment by atyapin** [comment]
Thanks for the comment. I see the difference in main.ts. But also I can see the difference in the result.
Checked checkbox became checked as excpected but I cannot see form.value on the fly in the new version. And submitting of the form gives different results. You can see my plunk on the left and your plunk on the right

![image](https://cloud.githubusercontent.com/assets/16883882/16225317/c1596f34-37ae-11e6-8185-bb3642083f8f.png)

**Comment by vicb** [comment]
Have you check the doc from the console logs and do the required changes ? If yes and you think it is still a bug, please re-open
