### ISSUE TITLE
Add license statement to all source code

### ISSUE THREAD

**Issue by naomiblack** [angular/angular#9380]
We need to come up with an automated process to ensure that all .ts, .js. and .dart source code files contain the following notice.

```
Copyright Google Inc. All Rights Reserved.
Use of this source code is governed by an MIT-style license that can be found in the LICENSE file at https://angular.io/license
```

**Comment by naomiblack** [comment]
@hansl has some questions about how this applies to the CLI... I've asked him to come up with a doc so we can clarify with the opensource folks

**Comment by alexeagle** [comment]
fyi, Scott has written the tslint check for this and will send a PR to add to upstream tslint.

This needs to apply to test sources as well, right?

**Comment by naomiblack** [comment]
yes, all source code.

**Comment by alexeagle** [comment]
We'll only add to .ts source files in the first pass, since that's the only
kind we have tooling to verify.

**Comment by naomiblack** [comment]
also worth noting that @juliemr raised the concern that some of our files need to start with `#!bin/node` on the first line of the file.

Max says it's ok to put at the bottom of the file where necessary.

**Comment by ScottSWu** [comment]
Does right below it work as well?

**Comment by naomiblack** [comment]
yes, both are fine.

**Comment by hansl** [comment]
Questions WRT CLI:

* Should we add code to the blueprints / generated code?  
 (separate discussion answered that code generated is okay, just putting this here for completion)
* Is it for code that is executed or just code that exists (for example, 1-line scripts or such)?
* What about files that are not TS/JS/Dart code? (e.g. CSS, text or assets)

**Comment by IgorMinar** [comment]
this has been done already
