### ISSUE TITLE
Cannot call router from inside of 'addEventListener'

### ISSUE THREAD

**Issue by Neill83** [angular/angular#9391]
**Current behavior**

I want to call router (deprecated) in my Component from inside of an 'addEventListener'.

```
login()
  {
    this._router.navigate(['Login']);
  }

  ngOnInit()
  {
    window.addEventListener('login', function()
    {
        //this.login(); //the method to navigate to login
      this._router.navigate(['Login']);
    });
  }

```

I do this to fire the event from the inside of an iFrame, but it says:

Cannot read property 'navigate' of undefined

The same behavior on calling a method:

login is not a function

**Expected/desired behavior**
i want to navigate to login after firing the event.

**Please tell us about your environment:**

Angular version: 2.0.0-rc.2
Browser: [Chrome 49]
Language: [TypeScript]

**Comment by pkozlowski-opensource** [comment]
`this` is not what you think it is - I mean - in an event handler function it doesn't point to a component instance. Try 

```javascript
window.addEventListener('login', () =>   {
        //this.login(); //the method to navigate to login
      this._router.navigate(['Login']);
    });
```

or any other trick that gets your proper JS `this`.

In any case this is a JS support question and it doesn't belong here, see: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by Neill83** [comment]
```
var test = this._router;

window.addEventListener('login', function()
    {
        //this.login(); //the method to navigate to login
      test.navigate(['Login']);
    });
```

thats the solution.

**Comment by Neill83** [comment]
Thanks @pkozlowski-opensource,
it works!

**Comment by zoechi** [comment]
@Neill83 I think @pkozlowski-opensource s suggestion above is the better solution
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/Arrow_functions
Try to avoid `function()` and use instead `()=>`

**Comment by Neill83** [comment]
@pkozlowski-opensource @zoechi 
Its possible to have a function with params?
like:

`
window.addEventListener('login', (param1, param2,... paramN) =>   {
        //do stuff with parameters
    });
`

i'm getting compiler errors:

Argument of type '(param1: Event, param2: any, param3: any) => void' is not assignable to parameter of type 'EventListener | EventListenerObject'.

Thanks for your help

**Comment by zoechi** [comment]
@Neill83 that is not even related to Angular2. See https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener. Maybe I'm missing something but that doesn't even make sense. The callback only gets one parameter passed and that is the event, therefore having a callback with multiple parameters is pointless.

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by Neill83** [comment]
yes, you are right. I just found a solution for my problem.
