### ISSUE TITLE
"WARNING: sanitizing HTML stripped some content" when no content stripped

### ISSUE THREAD

**Issue by wkwiatek** [angular/angular#9392]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Escaped characters passed to `sanitize` are reported with warning.

**Expected/desired behavior**
No warning for preescaped html.

**Reproduction of the problem**
http://plnkr.co/edit/ip37nVScMDxE9KaoP3Ng?p=preview

After this line https://github.com/angular/angular/blob/master/modules/%40angular/platform-browser/src/security/html_sanitizer.ts#L243 `unsafeHtml` is mutated and contains `parsedHtml` and then in fact `parsedHtml` is compared to `safeHtml` (https://github.com/angular/angular/blob/master/modules/%40angular/platform-browser/src/security/html_sanitizer.ts#L261)

**Please tell us about your environment:**
Mac OS X 10.11.5

* **Angular version:** 2.0.0-rc.2
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web 
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart] 
TypeScript 1.8.10

**Comment by zoechi** [comment]
See http://stackoverflow.com/questions/37076867/in-rc-1-some-styles-cant-be-added-using-binding-syntax/37076868#37076868

http://plnkr.co/edit/WdrRVyHr6WUCwMCwhH9F?p=preview

**Comment by wkwiatek** [comment]
I know about "marking as trust" but I guess it's not a case here. 

Consider this example: http://plnkr.co/edit/U1N8xgJOUWyemz8oS0RW?p=preview
I'm passing a simple string `test` here and it's perfectly fine because nothing was really stripped. 

In case of the unicode icon there should be no warning because I've passed encoded string (value passed to `innerHtml` input and finally rendered are exactly the same) so nothing was stripped in fact. 

However if I do this: http://plnkr.co/edit/ZSto9Gl03ZzNGVF8E8C2?p=preview then warning is what I'd expect.

So to the point - I think the message is wrong in case you pass encoded value to `sanitize`.

**Comment by zoechi** [comment]
I see, I leave that to the Angular team then.

**Comment by vicb** [comment]
@mprobst could you please take a look ?

**Comment by mprobst** [comment]
I think this is inherent in how we sanitize. We're using the browser's HTML parser, which of course turns escapes such as `&#x1f680;` in the example into their Unicode code point equivalents (or UTF-16, really). After parsing and re-serializing, Angular sees a string that does not match byte by byte, i.e. the escape has been replaced with the actual character (🚀), and thus prints the warning.

Fixing this won't be possible without re-implementing half an HTML parser and expensively re-scanning the string. Given that the message is entirely harmless and only slightly misleading, and given that this is probably somewhat of a corner case, I think the effort is not worth it.

Does that make sense? Please feel free to re-open if this actually causes an issue.

**Comment by wkwiatek** [comment]
@mprobst I don't think there is a problem with sanitization but with the error message condition. I've added PR because code shows much more than words. Let me know what do you think about it.

**Comment by mprobst** [comment]
@wkwiatek I understand, but I'm surprised the PR fixes this. Let's discuss there.

**Comment by oocx** [comment]
I also get this warning when I bind text that contains German Umlaute (ü, ö, ä), because they get replaced with &uuml; &ouml; and &auml;. This makes the warning useless for me, because I get like 95% false warnings and don't bother to look at them any more.

**Comment by mprobst** [comment]
@oocx sorry about that. As I wrote on the PR, Angular would need to re-implement half an HTML parser to avoid this warning, which seems overkill as it is harmless and only supposed to be a development help.

We could consider not escaping at least some unicode characters (e.g. umlauts), but then we'd cause the warning for people passing in `&uuml;` or `&0xDC;` and so on. The joys of encoding :-/

**Comment by oocx** [comment]
@mprobst I understand why it's not easy to fix. Is there a way to disable this warning? It's spamming my console with warnings when I debug my application.

If there is no option to turn it off yet, I could try to implement it and submit a PR if you think it's a useful feature.

**Comment by mprobst** [comment]
@oocx there's no feature to disable that. I'm skeptical about making it a feature, too – more options make software harder to use, and I'm not convinced it's enough of a problem to warrant fixing. Binding `innerHtml` & Co should be rare in any case...

**Comment by mprobst** [comment]
@oocx FYI 482c019199a4d6c79774f8b6c8e7871565514dd8 should fix this for you.
