### ISSUE TITLE
Add dynamically a component from another component angular2

### ISSUE THREAD

**Issue by khalildiouriadservio** [angular/angular#9394]
In my child component I add in a div of a template an Input from directive to drag and drop

`<div class="col-sm-4"  dnd [drop]="true"> //<== input drop 
              One of three columns
 </div>`
so when I add this component I want to apply my drag&drop to another tag from parent component 

the operation of drag and drop is working well but I need to do my drop that value of drop become true and this input cant be read when I added the child component  dynamically 

what I noticed that function onDrop is not work it dont called when I do my drag&drop Some know 

this is my directive of drag and drop
`import {
Directive, Output, EventEmitter, ElementRef, Input, Renderer
 } 
from '@angular/core';
import any = jasmine.any;
declare var jQuery:JQueryStatic;

@Directive({
    selector: '[dnd]',
    host: {
        '(dragstart)': 'onDragStart($event)',
        '(dragend)': 'onDragEnd($event)',
        '(drag)': 'onDrag($event)',
        '(dragover)': 'onAllowDrop($event)',
        '(drop)': 'onDrop($event)',
        '(dragleave)': 'ondragleave($event)'
    }
})
export class dnd_drag {

    elementDrag:HTMLElement;
    elementDrop:HTMLElement;

    @Input("id_drag") id_drag;
    @Input("drop") drop;
    @Input("drag") drag;

    set setDrag(value:string) {
        this.id_drag = !!value;
    }

    set droppable(value:boolean) {
        this.drop = !!value;
    }

    elem:HTMLElement;

    constructor(private el:ElementRef, private renderer:Renderer) {
        this.drop = false;
        this.renderer.setElementAttribute(this.el.nativeElement, 'draggable', 'true');
    }

    onDrag(event:MouseEvent) {
        this.renderer.setElementStyle(this.el.nativeElement, 'border-style', 'dotted');

    }

    onDragEnd(event:Event) {
        this.renderer.setElementStyle(this.el.nativeElement, 'border', 'none');
    }

    onDragStart(event:DragEvent) {
        this.elementDrag = this.el.nativeElement;
        event.dataTransfer.setData('dnd', this.elementDrag.innerHTML);
    }

    onAllowDrop(event:DragEvent) {

        event.preventDefault();
        this.renderer.setElementStyle(this.el.nativeElement, 'border', '4px dotted');
    }

    ondragleave(event:DragEvent) {
        this.renderer.setElementStyle(this.el.nativeElement, 'border', 'none');
    }

    onDrop(event:DragEvent) {
        if (this.drop) {
            this.elementDrop = this.el.nativeElement;
            event.preventDefault();
            this.elementDrop.innerHTML += event.dataTransfer.getData('dnd');
            this.elementDrop.cloneNode(true);
            this.renderer.setElementStyle(this.el.nativeElement, 'border', 'none');
        }

    }`

**Comment by zoechi** [comment]
I didn't look into details of your post but from the title http://stackoverflow.com/questions/36325212/angular-2-dynamic-tabs-with-user-click-chosen-components/36325468#36325468 might give you some idea how to add components dynamically.

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by pkozlowski-opensource** [comment]
See https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by khalildiouriadservio** [comment]
if you can see in stack http://stackoverflow.com/questions/37944237/drag-and-drop-between-separated-component-angular-2?noredirect=1#comment63337833_37944237
