### ISSUE TITLE
Components lifecycle sequence bug

### ISSUE THREAD

**Issue by JulienBroi** [angular/angular#9395]
**I'm submitting a ...**  (check one with "x")

```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
OnChanges doesn't always trigger before OnInit.

**Expected/desired behavior**
As described in the doc, onChanges should be triggered "before ngOnInit and when a data-bound input property's value changes."
@see: https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html#!#hook-sequence

**Reproduction of the problem**
The problem happens when the component has no data-bound inputs but still implements OnChanges. This could happen when a child-component allows to optionally data-bind some of its properties and the parent component decides not to do so. An example is given in the following plunker (the component app.ts allows to use data-binding on testInput but the parent component doesn't do so): http://plnkr.co/edit/Wu99OK0iQywVKvdQdEUE?p=preview

**What is the expected behavior?**
As described in the doc, onChanges should be triggered "before ngOnInit and when a data-bound input property value changes."
@see: https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html#!#hook-sequence

**What is the motivation / use case for changing the behavior?**
This would allows to write reusable components that are either reachable via a route (using route parameters to initiate the input properties) or embeddable in another (using data-binding to update the input properties). Moreover, this removes non-determinism and helps staying consistent with what is written in the doc.

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.1
- **Browser:**  Chromium 50.0.2661.102 (64-bit)
- **Language:** TypeScript 1.8.10

**Comment by DzmitryShylovich** [comment]
> The problem happens when the component has no data-bound inputs but still implements OnChanges

`ngOnChanges` is only triggered when component inputs have changed. No inputs - no changes.
Form the [docs](https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html#!#onchanges):
> Angular calls its ngOnChanges method whenever it detects changes to input properties of the component (or directive). This example monitors the OnChanges hook.

@pkozlowski-opensource can be closed.
@JulienBroi if something is not clear for you pls re-open on https://github.com/angular/angular.io/issues
