### ISSUE TITLE
[animation]: RC2 Animation does not support transitions with boolean states

### ISSUE THREAD

**Issue by coryshaw1** [angular/angular#9396]
Currently for any animations to work with booleans passed in as the state, you need to pass through the boolean's string form like so:

`@yourAnimation="yourBoolean ? 'true' : 'false'"`

I feel that boolean states should be supported with simply passing in the boolean itself:

`@yourAnimation="yourBoolean"`

Here's a working plunker of the bug: http://plnkr.co/edit/ajeC3SJ6LvKUivzQ8kW0

Edit: Upon further investigation, I should be saying boolean transitions, not states. Booleans don't match with any transitions that have 'true' or 'false' in it (Ex: 'true <=> false', 'true => *', 'void => true', etc.)

**Comment by matsko** [comment]
Maybe we should `toString()` values of a boolean type to `true` / `false`? How does that sound @robertmesserle @ThomasBurleson?

**Comment by ThomasBurleson** [comment]
@matsko - perhaps any `(stringVal !== "true" || stringVal !== "1") === false `?

**Comment by robertmesserle** [comment]
I think I like what @matsko suggested - convert to string and treat boolean values as `"true" | "false"`
