### ISSUE TITLE
Router: Set default exact for routerLinkActiveOptions to false

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#9397]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The `routerLinkActive` directive matches if the route is an exact match in the UrlTree

**Expected/desired behavior**

The `routerLinkActive` directive should match if the route is contained in the UrlTree

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

Previous behavior for active router links cascaded down from the root. If a child routerLink was active and had a parent routerLink on the page, the parent routerLink would be active also.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart] 

cc: @vsavkin

**Comment by vsavkin** [comment]
Fixed https://github.com/angular/angular/pull/9581
