### ISSUE TITLE
JSON Hijacking Protection

### ISSUE THREAD

**Issue by harshabonthu** [angular/angular#9398]
**I'm submitting a ...** 
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In Angular 1.x as stated here https://docs.angularjs.org/guide/security, $http handles automatically stripping out suggested prefix `")]}',\n"` added to json response from API requests. In Angular 2.0, stripping out the prefix is not being handled.

**Expected/desired behavior**
Ideally if it was suggested to prefix Json reponse with `")]}',\n"` and angular 1.x handles automatically, I guess it should be handled in Angular 2.0 as well?

**Comment by vicb** [comment]
I think this is already implemented, see https://github.com/angular/angular/blob/fdf6bc18ddf05d43185f713020f4c816b90ed360/modules/%40angular/http/test/backends/xhr_backend_spec.ts#L505
