### ISSUE TITLE
Typo in testing docs

### ISSUE THREAD

**Issue by m5rk** [angular/angular#9400]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

https://angular.io/docs/ts/latest/guide/testing.html

> The call to System.import shouldn't surprise us but it's asynchronous nature might.

Should be:

> The call to System.import shouldn't surprise us but its asynchronous nature might.

**Comment by vicb** [comment]
Could you please re-open this issue on the doc repo at https://github.com/angular/angular.io

**Comment by m5rk** [comment]
Done: https://github.com/angular/angular.io/pull/1717
