### ISSUE TITLE
<input id="cb" type="checkbox" checked> with ngControl, formControlName and ngModel

### ISSUE THREAD

**Issue by atyapin** [angular/angular#9401]
Cannot re-open #9379 so I took plunk by @vicb http://plnkr.co/edit/HFDTY5Bz063q2kyBZag9?p=preview and changed it a little

**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
1. ngControl does not bind to ngForm
2. ngModel checked is not checked in a window

**Expected/desired behavior**
1. ngControl is bound to ngForm
2. ngModel with "checked" attribute should be checked
3. formControlName with "checked" attribute should be checked

**Reproduction of the problem**
https://plnkr.co/edit/6tMrQClZ8lKpqjkRe1Oi?p=preview

**What is the expected behavior?**
1. ngControl is bound to ngForm
2. ngModel with "checked" attribute should be checked
3. formControlName with "checked" attribute should be checked

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [ Chrome XX | Firefox XX | Edge ] 
 
* **Language:** [ TypeScript ]

**Comment by zoechi** [comment]
Usually just posting another comment should do and someone will have a look and reopen if you provided enough information to be able to reproduce.

**Comment by born2net** [comment]
has this bug been confirmed as I am also having issues with formControlName binding

**Comment by kara** [comment]
@atyapin   It looks like you are mixing the old forms API with the new forms API.  To clarify: 

- `ngControl` does not exist at all in the new forms module.  If you try to use it while providing the new module, it won't work.

- `formControlName

**Comment by georgefrick** [comment]
I wish the angular documentation contained your comments, and not just a google doc. It means I've had to explore the internet with a dim flashlight in order to find your explanation. Why not to a deprecation strategy where ngModel throws an exception or something? You are making us blindly transition in a way that confuses the model driven and template driven approaches. Where is the clear documentation on this? My apologies for the aggression of my post; but it's Sunday night and I'm sitting here pulling my hair out over questions that should be very easy to answer.

**Comment by kara** [comment]
@georgefrick  You're completely right. The current docs are incomplete, and so it's non-obvious how forms are intended to be used.  We are currently working on adding a much more complete guide to the docs.  Truly sorry for the confusion :/

**Comment by georgefrick** [comment]
@kara No need to be sorry, just finished your doc and it clears a lot of, except the functions it mentions that I can't find :-)
Just so many blog posts out there that have examples that no longer work, trying to find a source of truth!
