### ISSUE TITLE
Dependencies specified in viewProviders prop are visible to content children

### ISSUE THREAD

**Issue by jamesbs** [angular/angular#9405]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Components passed in as content children to a parent component are able to get a dependency specified in `viewProviders` to that parent.

**Expected/desired behavior**

Dependencies specified in `viewProviders` are visible only to components passed in from the view.

**Reproduction of the problem**

**RC 1 example failing:** https://plnkr.co/edit/C9fOpUQYEgCgZEXwtSm0?p=preview
**beta.8 example succeeding:** https://plnkr.co/edit/JoSJYjjQGdHPIV6UX1WB?p=preview

**What is the expected behavior?**

In both cases, the child component should only be able to get the bootstrapped value. This is only happening in the 2nd example. Ie. Child and root values should match.

**What is the motivation / use case for changing the behavior?**

Feature is not working as intended

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.1
 
* **Browser:** Chrome
 
* **Language:** TypeScript 1.7.3

**Comment by vicb** [comment]
You have an app wide provider in the plunker.

`bootstrap(App, []);` would fail as expected

**Comment by pkozlowski-opensource** [comment]
Just noticed it as well, @vicb was faster about 300 milliseconds :-)

**Comment by jamesbs** [comment]
Even if a provider is given in the bootstrap call, shouldn't the child component pass over the provider in the parent component? The semantics are different in the two examples since in example 1 the child value matches the parent value whereas in example 2 the child value matches the root value

**Comment by jamesbs** [comment]
@vicb @pkozlowski-opensource Thoughts? Did I get this wrong?

**Comment by vicb** [comment]
I think it has been fixed in master
