### ISSUE TITLE
Offline Compiler integration tests are not typechecking against stripped .d.ts files

### ISSUE THREAD

**Issue by robwormald** [angular/angular#9408]
Ref: https://github.com/angular/angular/pull/9330

the offline compiler/codegen integration tests are currently tested against the angular codebase ( i believe its the modules/tsconfig build) - this does not strip @internal annotations, and so we have a mismatch on our integration tests vs what's actually shipped to NPM.

**Comment by robwormald** [comment]
cc @alexeagle

**Comment by alexeagle** [comment]
That was not the case when we added the integration test - in fact it caught an extra `@internal` when I first ran it.
See here:
https://github.com/angular/angular/blob/master/scripts/ci-lite/offline_compiler_test.sh#L6
we actually install the distribution version of angular before running the test, and that should have `--stripInternal`
