### ISSUE TITLE
meteor node_modules/@angular/router/index has no exported member 'provideRouter'

### ISSUE THREAD

**Issue by cemersoz** [angular/angular#9409]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report

```

**Current behavior**
I am using angular2 with meteor and trying to move to router 3 from router-deprecated.
I have been following the tutorial on https://angular.io/docs/ts/latest/guide/router.html
I keep getting the following error when I run meteor:
Module '"node_modules/@angular/router/index"' has no exported member 'provideRouter'

I have removed all old router modules and installed the newest one after finding this issue but nothing has changed
https://github.com/angular/angular/issues/9344

**Expected/desired behavior**
router to have exported module

**Reproduction of the problem**

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.1
 
* **Browser:**  Chrome XX 
 
* **Language:**  TypeScript

**Comment by brandonroberts** [comment]
Router v3 is in alpha currently and is installed through `npm install @angular/router@3.0.0-alpha.7 --save`. Once it lands it master it should be released with the next RC.

**Comment by cemersoz** [comment]
@brandonroberts I installed the new router using that command, removed the older versions, deleted node_modules and installed from scratch but no luck.

**Comment by brandonroberts** [comment]
@cemersoz what are you using for bundling? If you're using SystemJS the setup is different at the moment. Come into http://gitter.im/angular/angular and we can help you there.

**Comment by cemersoz** [comment]
already there, I'll continue there. Thanks for all the support!
