### ISSUE TITLE
SystemJsComponentResolver is missing @Injectable()

### ISSUE THREAD

**Issue by EdS0ng** [angular/angular#9412]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
SystemJsComponentResolver does not have a @Injectable() decorator and will throw a `cannot read property isSkipSelf() of null` error when used.
I copied the exact typescript code from the repo and transpiled with the @Injectable() and it doesn't throw an error anymore. 
**Expected/desired behavior**
it works.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.2
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart]

**Comment by vicb** [comment]
It is not needed here as it has to be provided as a factory
