### ISSUE TITLE
Router: Url doesn't emit new collection of UrlPathWithParams for catch-all routes

### ISSUE THREAD

**Issue by zhura** [angular/angular#9418]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report

```

**Current behavior**

When defining catch-all route (i.e. `**`) ActivatedRoute.url observable doesn't emit new collection of UrlPathWithParams when wildcard url path is changed.

**Expected/desired behavior**

It should emit new collection of UrlPathWithParams.

**Reproduction of the problem**

Here is plnkr: http://plnkr.co/edit/jWfEpsNJ35pg6Cqn7H5q?p=preview

Actually I think we should rewrite `advanceActivatedRoute` function (https://github.com/angular/angular/blob/master/modules/%40angular/router/src/router_state.ts#L182) something like:

```
export function advanceActivatedRoute(route: ActivatedRoute): void {
  if (route.snapshot) {
    let prevParams = route.snapshot.params;
    let prevUrl = route.snapshot.url;
    route.snapshot = route._futureSnapshot;
    if (!shallowEqual(prevParams, route.snapshot.params))
      (<any>route.params).next(route.snapshot.params);

    if (!shallowEqual(prevUrl, route.snapshot.url))
      (<any>route.url).next(route.snapshot.url);
  } else {
    route.snapshot = route._futureSnapshot;
  }
}
```

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart]

**Comment by vsavkin** [comment]
Fixed https://github.com/angular/angular/pull/9581
