### ISSUE TITLE
Http.post() bug when posting to non-existent URLs with Content-Type set to application/json

### ISSUE THREAD

**Issue by bek0s** [angular/angular#9425]
**I'm submitting a ...** 
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When I do a POST request using Http.post() with `Content-Type` set to `application/json` to an invalid URL, the error callback of the Observable is called (as it is supposed to) but the Response object I get from the Observable has: `status: 200`, `ok: True` and `statusText: "Ok"`. If I change the `Content-Type` to `text/plain` then I get the expected: `status: 404`, `ok: False` and `statusText: "NOT FOUND"`.

```typescript
let myheaders = new Headers();
myheaders.append('Content-Type', 'application/json');
let options = new RequestOptions({ headers: myheaders });
let resourceStr = '{"foo": "bar"}';
let foo = this.http.post('http://127.0.0.1:5000/api/produce_404', resourceStr, options)
.subscribe(
  data => {
    console.log(data);
  }, 
  error => { 
    console.warn(error);
  });
```

**Expected/desired behavior**

Every time I do a post request (with `Content-Type` set to `application/json`) to a non-existent URL, I would expect to get an error Response object with `status: 404`, `ok: False` and `statusText: "NOT FOUND"`.

**Reproduction of the problem**

Sorry, no Plunker.

**What is the motivation / use case for changing the behavior?**

Correct error handling of different HTTP responses.

**Please tell us about your environment:**

Debian Linux (testing repo)

* **Angular version:** 2.0.0-rc.2 

* **Browser:** Chrome 51.0.2704.103 (64-bit)]
 
* **Language:** TypeScript

**Comment by ericmartinezr** [comment]
Check the changelog https://github.com/angular/angular/blob/master/CHANGELOG.md, this was fixed in RC.3 https://github.com/angular/angular/pull/9355

**Comment by bek0s** [comment]
Oh, rc3 was released pretty much while I was discovering the bug! :P Apologies for the redundant post! I am sure it will work just fine now. I will upgrade my app to rc3 and if I have further issues I will report back. Thanks!
