### ISSUE TITLE
Angular 2 RC3 - Router-Deprecated     "@angular/router-deprecated":  "2.0.0-rc.3",

### ISSUE THREAD

**Issue by robinkedia** [angular/angular#9428]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Followed the documentation on Angular IO website and upgraded from RC2 to RC3. Npm install complains   "@angular/router-deprecated":  "2.0.0-rc.3", not available.

Not sure if documentation issue or packages missing?

**Expected/desired behavior**

**Reproduction of the problem**

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
 
* **Browser:**  
 
* **Language:** [TypeScript]

**Comment by ryu323** [comment]
For what it's worth, it'll work if you manually change it to rc.2: `"@angular/router-deprecated":  "2.0.0-rc.2"`

**Comment by robinkedia** [comment]
Yep, i pointed it back to rc2 on my code. https://angular.io/docs/ts/latest/quickstart.html - Quick start documentation points to rc3. Thanks!

**Comment by juan-orca** [comment]
While there is an issue on the router I would like to say, can we please have the router documentation written in vanilla JS as well.

**Comment by ericmartinezr** [comment]
You should report this in the website/tutorial repo https://github.com/angular/angular.io so they can remove it. For now simply remove it from the configuration, there's no more point on using that router.

**Comment by StephenFluin** [comment]
Thanks for identifying that the quickstart points to a non-existant version of the router I logged a bug on that project: https://github.com/angular/angular.io/issues/1728

There will not be future releases of the deprecated router, and the @angular/router project has its own release cycle.
