### ISSUE TITLE
How to use jquery as normal npm mudule in angular 2 typescript file?

### ISSUE THREAD

**Issue by deepaksibar** [angular/angular#9429]
Hi,

I am trying to use jquery as normal NPM module, but "$" is not accessible in typescript file. Even i tried  by adding script tag in index.html.

Please let me know how to use jquery or any other pure javascript library in angular 2 typescript file ?

**Comment by zoechi** [comment]
This is answered on StackOverflow AFAIK

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)
