### ISSUE TITLE
SelectMultipleControlValueAccessor is considered as customAccessor

### ISSUE THREAD

**Issue by kukjevov** [angular/angular#9430]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If you have following html
```html
<select class="selectpicker" multiple [(ngModel)]="ifrsTypes"></select>
```
and you have custom value accessor for this element you will get an error _More than one custom value accessor matches_ because *SelectMultipleControlValueAccessor* is missing in this code in _angular/modules/@angular/common/src/forms-deprecated/directives/shared.ts_ and in _angular/modules/@angular/forms/src/directives/shared.ts_

```typescript
else if (hasConstructor(v, CheckboxControlValueAccessor) || 
         hasConstructor(v, NumberValueAccessor) ||
         hasConstructor(v, SelectControlValueAccessor) ||
         hasConstructor(v, RadioControlValueAccessor))
{
      if (isPresent(builtinAccessor))
        _throwError(dir, 'More than one built-in value accessor matches');
      builtinAccessor = v;
}
```
this causes that you can`t have custom value accessor for multi select.

**Expected/desired behavior**

SelectMultipleControlValueAccessor should be considered as buildinAccessor that means change code of _angular/modules/@angular/common/src/forms-deprecated/directives/shared.ts_ and in _angular/modules/@angular/forms/src/directives/shared.ts_

to 
```typescript
else if (hasConstructor(v, CheckboxControlValueAccessor) || 
         hasConstructor(v, NumberValueAccessor) ||
         hasConstructor(v, SelectMultipleControlValueAccessor) ||
         hasConstructor(v, SelectControlValueAccessor) ||
         hasConstructor(v, RadioControlValueAccessor))
{
      if (isPresent(builtinAccessor))
        _throwError(dir, 'More than one built-in value accessor matches');
      builtinAccessor = v;
}
```

**Reproduction of the problem**
https://plnkr.co/edit/oZ8DxT?p=preview

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.2
 
* **Browser:** [all] 
 
* **Language:** [TypeScript 1.8.10]

**Comment by vicb** [comment]
Please provide a plunker to speed up the handling of this issue. Thanks.

**Comment by kukjevov** [comment]
Hi, i have never worked with plunker and right now i dont have time to study it, but i try to help you by providing ValueAccessor implementation which will cause conflict. 

```typescript


import {NG_VALUE_ACCESSOR, ControlValueAccessor} from '@angular/common';
import {forwardRef, Provider, Directive, OnDestroy} from '@angular/core';
import {isBlank} from '@angular/core/src/facade/lang';

const BOOTSTRAP_SELECT_VALUE_ACCESSOR = new Provider(NG_VALUE_ACCESSOR, {useExisting: forwardRef(() => BootstrapSelectControlValueAccessor), multi: true});

@Directive(
{
    selector: 'select.selectpicker[ngControl],select.selectpicker[ngFormControl],select.selectpicker[ngModel]',
    providers: [BOOTSTRAP_SELECT_VALUE_ACCESSOR]
})
export class BootstrapSelectControlValueAccessor implements ControlValueAccessor, OnDestroy
{   
    //######################### public properties #########################

    /**
     * Currently set value
     */
    public value: any;

    //######################### public methods - implementation of ControlValueAccessor #########################

    /**
     * Sets value to select
     */
    public writeValue(value: any): void
    { 
    }

    /**
     * Registers callback that is called when value of select changes
     */
    public registerOnChange(fn: (data: any) => any): void
    {
    }

    /**
     * Registers callback that is called when select is closed
     */
    public registerOnTouched(fn: () => any): void
    {
    }
    
    //######################### public methods - implementation of OnDestroy #########################
    
    /**
     * Called when component is destroyed
     */
    public ngOnDestroy()
    {
    }
}

export const BOOTSTRAP_SELECT_DIRECTIVES = [BootstrapSelectControlValueAccessor];
```

It is not complete implementation but it should be sufficient for reproduction of error.

Create component with this definition
```typescript
import {BOOTSTRAP_SELECT_DIRECTIVES} from './pathToPreviousAccessor';
import {Component} from '@angular/core';

@Component(
{
  selector: 'test',
  providers: [BOOTSTRAP_SELECT_DIRECTIVES],
  template: `<select class="selectpicker" multiple [(ngModel)]="ifrsTypes"></select>`
});
export class TestComponent
{
}
```
This should be enough. I hope it helps. 
Thank you

**Comment by zoechi** [comment]
Plunker is quite tivial and it provides a ready to use Angular2 TS template 

![image](https://cloud.githubusercontent.com/assets/405837/16279309/c14d4f62-38ba-11e6-83fa-62dea6315375.png)

I didn't check the exact behavior, I just copied your code and investigated how to make it run without errors - there is an redundant `;` after the `@Component();` decorator of `TestComponent`
https://plnkr.co/edit/fd2lkjS289688xh26sUo?p=preview

Please complete the Plunker to reproduce the issue.

**Comment by kukjevov** [comment]
Damn i`m lame :D, i have updated your plunkr, to reproduce this bug, but haven`t figured out how to save it or share it. 

I have written that code from memory, but i had mistake i used providers instead of directives in component. So to reproduce this bug, open plnkr link above and change 

src/app.ts on line 54
from
```typescript
  providers: [BOOTSTRAP_SELECT_DIRECTIVES],
```
to
```typescript
directives: [BOOTSTRAP_SELECT_DIRECTIVES],
```

and you will see in console this bug.

Thank you

**Comment by kukjevov** [comment]
Hi once again, somehow i saved it :D here it is https://plnkr.co/edit/oZ8DxT?p=preview

**Comment by kara** [comment]
Closed by https://github.com/angular/angular/issues/9602.  Thanks @kukjevov for the PR!
