### ISSUE TITLE
Angular 2 RC3 router bundles umd missing to UMD bundles for the router are missing

### ISSUE THREAD

**Issue by robinkedia** [angular/angular#9431]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Application fails to fireup with Angular 2 RC3. 404 failed to bundles/router.umd.js

**Expected/desired behavior**
Expecting router/bundles/router.umd.js file

**Reproduction of the problem**

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart]

**Comment by jaroslawziolkowski** [comment]
I have same problem

- Angular: 2.0.0-RC3
- Browser [Chrome| Firefox| Safari|]
- Language [TypeScript]
- Node 6.2.0
- npm 3.8.9

**Comment by pandomic** [comment]
Also got this error.
I've resolved it by replacing the node_modules/@angular/router with fresh version of router from its repo: https://github.com/angular/router-builds

**Comment by jaroslawziolkowski** [comment]
@pandomic thanks it works. Now we are waiting to npm repository update :)

**Comment by cyrilletuzi** [comment]
Until the npm repository update, you can also change your system.config.js : 

```
  var map = {
    'app':                        'dist', // 'dist',
    '@angular':                   'node_modules/@angular',
    'angular2-in-memory-web-api': 'node_modules/angular2-in-memory-web-api',
    'rxjs':                       'node_modules/rxjs',
    '@angular/router':            'node_modules/@angular/router'
  };
  // packages tells the System loader how to load when no filename and/or no extension
  var packages = {
    'app':                        { main: 'main.js',  defaultExtension: 'js' },
    'rxjs':                       { defaultExtension: 'js' },
    'angular2-in-memory-web-api': { main: 'index.js', defaultExtension: 'js' },
    '@angular/router':            { main: 'index.js', defaultExtension: 'js' }
  };
```

**Comment by IgorMinar** [comment]
the v2 router has been superseeded by the v3 router - https://angularjs.blogspot.com/2016/06/improvements-coming-for-routing-in.html which is a on a different release schedule from the rest. There will not be a 2.0.0-rc.3 of angular/router unless something unexpected happens.

we are working on bringing the v3 router in the angular/angular repo (it was previously being developed in angular/vladivostok). I'll create a separate issue for publishing umd bundles for the v3 router.

**Comment by pkozlowski-opensource** [comment]
see #9465

**Comment by mLaird** [comment]
I get 'not found' for platform-browser-dynamic.umd, core.umd, and router-deprecated.umd
The problem is more pervasive.

**Comment by Airswoop1** [comment]
For anyone running into this from the initial issue, this was what helped me get a resolution: http://stackoverflow.com/questions/38081031/how-to-install-and-import-angular-2-angular-router/38081212#38081212

**Comment by robinkedia** [comment]
I m no longer facing this issue. You just need to do npm uninstall
@angular/router --save and then npm install @angular/router --save

On Wednesday, 29 June 2016, Kevin Miller <notifications@github.com> wrote:

> For anyone running into this from the initial issue, this was what helped
> me get a resolution:
> http://stackoverflow.com/questions/38081031/how-to-install-and-import-angular-2-angular-router/38081212#38081212
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/angular/angular/issues/9431#issuecomment-229230998>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AJ6mG1etewfTmGRcKbzaCEO4nqBKt-Jsks5qQcjHgaJpZM4I7cQe>
> .
>


-- 
Cheers!

**Comment by spati-java** [comment]
use the latest version of package.json and all the other configuration files , here is the link https://angular.io/docs/ts/latest/quickstart.html#!#create-and-configure
