### ISSUE TITLE
CHANGELOG for router and other modules that are not in sync with Angular2 (core) versioning

### ISSUE THREAD

**Issue by zoechi** [angular/angular#9432]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
https://github.com/angular/angular/pull/9372#issuecomment-227651705

> Is this included in RC.3? The Changelog doesn't mention the router.

> @vicb It is... and mentioned in the blog post. We decided not to include it in the release notes because the releases of the router will not be sync with angular. Maybe we should have mentioned it for this release. PR ?

**Expected/desired behavior**

It should be clear which modules are tracked in https://github.com/angular/angular/blob/master/CHANGELOG.md
and where the changes of other modules are tracked.

I think the router (and similar modules) should have their own CHANGELOG.md file and https://github.com/angular/angular/blob/master/CHANGELOG.md should provide a prominent link to them.

**Comment by vicb** [comment]
@StephenFluin @naomiblack what do you think ?

**Comment by StephenFluin** [comment]
To clarify a little further, while those commits are now in the @angular/angular repository, we don't cut releases for the router synchronously with Angular, you'll see this with @angular/forms as well.

You're right that this makes it a little harder to find the changelog for the independent modules. Each release (of anything) should be pointing to the appropriate changelog, but we'll look at ways of making this clearer.

**Comment by zoechi** [comment]
@StephenFluin does this mean there **are** already changelogs for router and forms?

**Comment by zoechi** [comment]
@StephenFluin found it https://github.com/angular/angular/blob/master/modules/%40angular/router/CHANGELOG.md
GitHub serach for `changelog` doesn't find it.
