### ISSUE TITLE
Disable change of value in SelectMultipleControlValueAccessor 

### ISSUE THREAD

**Issue by Delagen** [angular/angular#9433]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
```html
<select multiple name="sample" [(ngModel)]="model">
	<option value="model"></option>
</select>
```
rendered value equal "index: 'model'" (0: 'model')

**Expected/desired behavior**
rendered value equal 'model'

* **Angular version:** 2.0.0-rc.3
 
* **Browser:** all
 
* **Language:** TypeScript 1.9.0

**Comment by zoechi** [comment]
Can you please provide a Plunker that allows to reproduce the issue?

**Comment by Delagen** [comment]
Found issue. As of binding feature of multiple select and it binding to (input) event instead of (change). Custom implementation of controls stuck with values generated with value accessor. No native interface to call that selectedOptions changes. But calling onChange method with event target argument fixes the issue. I think i will rewrite accessor manually for such components.
