### ISSUE TITLE
IE11: Router (3.0.0-alpha-7) does not work correctly, when serving from a subdirectory

### ISSUE THREAD

**Issue by cebor** [angular/angular#9435]
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Current behavior**
In IE11 the routing does not work correctly, when you serve the site from a sub-directory and with a `<base href=".">` in the index.html head.

- The home-view does not initialize on first load
- On routing it overwrites the sub-directory

**Reproduction of the problem**
Demo: https://loggr.stkn.org/v2
Source: https://github.com/cebor/ng2-start/tree/master/src

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
 
* **Browser:** [ IE 11 ] 
 
* **Language:** [ TypeScript 1.8 ]

**Comment by zoechi** [comment]
Can you please provide a Plunker that allows to reproduce?

**Comment by cebor** [comment]
@zoechi Think its not possible to serve a plunker from sub-directory, thats why im selfhosting it.

**Comment by cebor** [comment]
`<base href="/v2/">` fixed it
