### ISSUE TITLE
(router) What happened to the issues created under angular/vladivostok?

### ISSUE THREAD

**Issue by choeller** [angular/angular#9436]
Hi,

this is more an organizational question than an actual bug report. So I'm wondering what happened to all the issues created under:

https://github.com/angular/vladivostok/

I think there were somewhat around 30 open issues that now all seem to be gone. Will they be transfered to the main repo, or is there a way to at least see them again to copy them over here?

/cc @vsavkin

**Comment by robwormald** [comment]
They've all been moved over here now.

**Comment by choeller** [comment]
Cool, thanks a lot!
