### ISSUE TITLE
Router 3.0.0-alpha.7: containsTree - container is undefined 

### ISSUE THREAD

**Issue by fatsu** [angular/angular#9437]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
```

**Current behavior**

"@angular/router": "3.0.0-alpha.7",

When using routerLinkActive, I get the following exception(s) after navigation from a 'root' component without child-routes ('/comp1') to a child-component of another 'root'-component ('/comp2/childx'). There is no problem with navigation between siblings.

This only happens when setting routerLinkActiveOptions.exact to false! 

Firefox:
TypeError: container is undefined
containsSegmentHelper@http://127.0.0.1:4200/vendor/@angular/router/url_tree.js:35:1
containsSegmentHelper@http://127.0.0.1:4200/vendor/@angular/router/url_tree.js:61:16
containsSegment@http://127.0.0.1:4200/vendor/@angular/router/url_tree.js:32:12
containsSegmentHelper@http://127.0.0.1:4200/vendor/@angular/router/url_tree.js:49:18
containsSegment@http://127.0.0.1:4200/vendor/@angular/router/url_tree.js:32:12
containsTree@http://127.0.0.1:4200/vendor/@angular/router/url_tree.js:14:16
RouterLinkActive.prototype.update/isActive<@http://127.0.0.1:4200/vendor/@angular/router/directives/router_link_active.js:54:27
...

IE:
"TypeError: Unable to get property 'pathsWithParams' of undefined or null reference
   at containsSegmentHelper (eval code:35:5)
   at containsSegmentHelper (eval code:61:9)
   at containsSegment (eval code:32:5)
   at containsSegmentHelper (eval code:49:13)
   at containsSegment (eval code:32:5)
   at containsTree (eval code:14:9)
   at Anonymous function (eval code:54:13)
   at QueryList.prototype.reduce (eval code:66:9)
   at RouterLinkActive.prototype.update (eval code:53:9)
   at RouterLinkActive.prototype.ngAfterContentInit (eval code:32:9)"

**Expected/desired behavior**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
 
* **Browser:** [Firefox 38.7 | IE 11] 
 
* **Language:** [TypeScript 1.8.10]

**Comment by pkozlowski-opensource** [comment]
Please provide a minimal reproduce scenario in plunker, as requested in the issue template. Otherwise this one is not actionable.

**Comment by Paulsky** [comment]
I have the same error with @angular/router: 3.0.0-alpha.8. Using multiple routerLinkActive attributes. So I created a Plunker as you requested. I couldn't reproduce the exact same behavior; my app crashes while the Plunker throws an error, but still works. This is my first Plunker, so please let me know if it's not clear enough. Please see my Plunker: http://plnkr.co/edit/QfwzUTwNZFkSOt34IMuE?p=preview

**Comment by vsavkin** [comment]
The PR fixing the issue: https://github.com/angular/angular/pull/9708

**Comment by Paulsky** [comment]
Thank you for your help!
