### ISSUE TITLE
Get Started Tutorial error + Plunkr not working

### ISSUE THREAD

**Issue by rjpalermo1** [angular/angular#9440]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**# **Angular2 Tour of Heroes tutorial broken****

The PLUNKR example (and my follow-along code) is working fine on the SERVICES step https://angular.io/docs/ts/latest/tutorial/toh-pt4.html

HOWEVER, when I add the **Appendix: Take it slow** suggestion the app breaks down.

```
getHeroesSlowly() {
  return new Promise<Hero[]>(resolve =>
    setTimeout(() => resolve(HEROES), 2000) // 2 seconds
  );
}
```

In the next step in the TUTORIAL for ROUTING here:  https://angular.io/docs/ts/latest/tutorial/toh-pt5.html 
the PLUNKR reflects the issues and will not load correctly.

**Comment by vicb** [comment]
Could you please reopen on https://github.com/angular/angular.io
