### ISSUE TITLE
misssing .some() on QueryList

### ISSUE THREAD

**Issue by Frozen-byte** [angular/angular#9443]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
QueryList does not support the .some() method, but forEach()

**Expected/desired behavior**
QueryList should be able to call some()

**What is the motivation / use case for changing the behavior?**
.some() is a nicer way to iterate Lists quickly if you only need one Element

**Please tell us about your environment:**
* **Angular version:** 2.0.0-rc.2
 
* **Browser:** [all] 
 
* **Language:** [TypeScript 1.8.10]

**Comment by vicb** [comment]
That should be quite easy to implement, do you want to try sending a PR ?
