### ISSUE TITLE
Router: Simplify Parent Route Parameter Access (and params in general)

### ISSUE THREAD

**Issue by ocombe** [angular/angular#9444]
**I'm submitting a feature request**

I'm reporting this issue by @DanWahlin that I found in google cache from the old router repository that was deleted when you moved the router to the angular repository. The text is copy pasted from the old issue (https://github.com/angular/vladivostok/issues/81):

_start of copy paste_

--------
I know the API is still being worked on at this point, but I wanted to add my two cents on route parameter access and the APIs after working with them quite a bit lately. Simplifying the overall process could really be helpful. Here's one scenario I'm running into a lot involving parent route parameters that feels much too verbose currently:

**Route:**
```
/customer/2/details
```

Snapshot API to Get id Route Parameter:
```ts
const id = +this.router.routerState.parent(this.route).snapshot.params['id'];
```

Observable API to Get id Route Parameter:
```ts
this.router.routerState.parent(this.route)
       .params 
       .subscribe(params => { 
           const id = +params['id'];
           //do something with id
          this.dataService.getCustomer(id)
                .subscribe((customer: ICustomer) => this.customer = customer);
       });
// With the code this way I think I'd have to unsubscribe too?
```

Suggested API:

I know that ActivatedRoute doesn't currently have a parent property, but something like the following would really simplify this fairly common scenario (this uses a snapshot rather than an observable):
```ts
// Move up to parent route and grab the id param
const id = +this.route.parent.params['id'];
```

Thanks for all the hard work on the router so far - really like the direction it's going. I just wanted to document a few ideas since the API is still being worked on and I think there are definitely some opportunities to simplify things along the way.

--------
_end of copy paste_

**What is the motivation / use case for changing the behavior?**
It's impossible to find out how to get parent parameters right now. The `parent` property of `routerState` is not documented. Without this issue I would never have found out how to do that (Thank you @DanWahlin !!).
This is such an obvious necessity that it should be simplified or at least documented.
Thanks !

* **Angular version:** 2.0.0-rc.3

**Comment by choeller** [comment]
@ocombe I was trying to get back my issues via google-cache too. Would you be so kind to check if you can still access them, As I also cannot access the issue that you just created via google-cache I hope that cache access is different depending on your location... 

My issues were
https://github.com/angular/vladivostok/issues/43
https://github.com/angular/vladivostok/issues/44
https://github.com/angular/vladivostok/issues/62

Thanks in advance!

**Comment by ocombe** [comment]
@choeller: I cannot access those issues from google cache sorry :( don't you have a copy in your email (if someone answered you)

**Comment by choeller** [comment]
@ocombe  :( thanks anyway! I have all the emails, but sadly they only contain  the answers, not my initial text...

**Comment by brandonroberts** [comment]
@choeller I have all the emails. I canl repost your originals

**Comment by choeller** [comment]
@brandonroberts that would be awesome! I'm quite sure a lot of others would be happy if their issues weren't lost!

**Comment by stranbird** [comment]
One possible solution:

Inject the parent in the child component:
```
constructor(private parent: ParentComponent) {
  // access the parameters of the parent route
  const id = +parent.route.snapshot.params['id'];
}
```
Assuming there is only one instantiated component of the `ParentComponent` type along the view hierarchy.

**Comment by DanWahlin** [comment]
Thanks! I've never tried that but it's an interesting way to clean it up some.

**Comment by ocombe** [comment]
The `parent` property has been added to ActivatedRoute making all of this much easier, just do:
`this.route.parent.params` with `this.route` being `ActivatedRoute`.
I'm closing the issue now since it has been simplified in RC5 ! Thanks.

**Comment by stranbird** [comment]
@ocombe really exciting to see this landed!

**Comment by alanent** [comment]
Can you help me ? https://stackoverflow.com/questions/50798874/angular-6-activatedroutesnapshot-service-firebase
