### ISSUE TITLE
Router: Support adding additional data to Route-Configurations (fka. RouteData)

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#9447]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**Expected/desired behavior**

Reposted from router v3 repo via @choeller

With the deprecated Router it was possible to add additional data to a Route-Configuration like this:

@RouteConfig([
  {path: '/about', component: AboutComponent, name: 'About', data: {title :"About us"}},
])
with this information it was possible to do some generic operations when activating the route (e.g. setting the page title via Title-Service. It would be cool to have this possibility again.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart]

**Comment by vicb** [comment]
@brandonroberts please fill out bug vs feature request. 

Isn't this one a duplicate ?

**Comment by brandonroberts** [comment]
Updated. @choeller filed this one in the router v3 repo, but it doesn't exist here.

**Comment by vicb** [comment]
https://github.com/angular/angular/issues/9390 ?

**Comment by brandonroberts** [comment]
Ok, that one can be used for tracking instead.
