### ISSUE TITLE
Router: Defining an aux-route in child-component prevents leaving this route again

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#9448]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Reposted from router v3 repo via @choeller

When having 2 router-outlets in a child-component the aux-functionality works well, but as soon as you want to leave the child-route the following exception is thrown and the router stops working:

`EXCEPTION: Error: Uncaught (in promise): Error: Outlet is not activated`
the following plnkr demonstrates the behaviour:

http://plnkr.co/edit/wnHZzoB4xj5BbKWNzXUK?p=preview

the aux-outlet is defined in crisis-center.component.ts

My use-case is to have an encapsulated part of my application that deals with "Tasks". When selecting a task I want to open a sidebar and display some important information about the task (JIRA-like). I already got this working in my application, but when once entering the "tasks" part I can never leave it again.

**Expected/desired behavior**

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart]

**Comment by vsavkin** [comment]
Duplicate https://github.com/angular/angular/issues/9479
