### ISSUE TITLE
Router: Matrix params are not working

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#9449]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Reposted from router v3 repo via @choeller

ith alpha.3 I was able to do the following:

http://localhost:4200/tasks;query=BACKLOG
```
  constructor(private taskService: TaskService,
                     private route: ActivatedRoute) {
  }
  ngOnInit() {
    this.route.params.subscribe((params) => {
      let query = decodeURI(params['query'] || '');
      this.findTasks(query);
    });
  }
```

The observable is never invoked. Also the params object is empty when using the snapshot, so I guess the Matrix-Params functionality was broken

**Expected/desired behavior**

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

Matrix params should be available via Observable or snapshot

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart]

**Comment by choeller** [comment]
@brandonroberts Thanks for opening this one for me. As the description above was superceded by #9451 you can close this one again!
