### ISSUE TITLE
Router alpha.7:  Matrix-Params are not working for index-routes of nested routes anylonger

### ISSUE THREAD

**Issue by choeller** [angular/angular#9451]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
```

**Current behavior**

When trying to access Matrix-Params on the index-route of a nested route like this:

```
http://localhost:4200/tasks;query=BACKLOG
```

```ts
export const TASKS_ROUTES: RouterConfig = [
  { path: 'tasks', canActivate: [LoginGuard], component: TasksComponent,
    children: [
      {path: '',component: TaskListComponent},
      {path: 'edit/:id', component: EditTaskComponent},
      {path: 'new', component: EditTaskComponent}
    ]
  }
];
```

```ts
export class TaskListComponent implements OnInit {

  constructor(private taskService: TaskService,
              private route: ActivatedRoute) {
  }

  ngOnInit() {

    this.route.params.subscribe((params) => {
      let query = decodeURI(params['query'] || '');
      this.tasks = this.taskService.findTasks(query);
    });

  }
```

The param is only passed to `TasksComponent`, but not to `TaskListComponent`. So there is currently no way to use Matrix-Parameters on the default-route of a child-route. 

This used to work on alpha.3 correctly, but is broken since alpha.4

**Expected/desired behavior**

* **Angular version:** 2.0.0-rc.2 Router alpha.7
 
* **Browser:** [all | ] 
 
* **Language:** [TypeScript]

**Comment by briananderson1222** [comment]
Try: `this.router.routerState.parent(this.route).params`

**Comment by choeller** [comment]
@briananderson1222 cool - thanks for the workaround!

**Comment by choeller** [comment]
Superceded by #9484 which has the complete issue history - thanks @robwormald
