### ISSUE TITLE
Content-type set in a http.put is being appended with text/plain after rc.2

### ISSUE THREAD

**Issue by pliscki** [angular/angular#9452]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When Content-type is manually set in a http.put, instead of completely overriding its content, it's just appending it and producing the following:  

`Content-Type:text/plain, application/json`

**Expected/desired behavior**

When any value is provided, it shouldn't defined a default content-type. At least, this is what was happening in versions prior to rc.2.

**Reproduction of the problem**

To see the problem, inspect network traffic in dev tools.
https://plnkr.co/edit/Qxw4pd2VnkkWg4iCXwUD?p=preview

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.2 and 2.0.0-rc.3
 
* **Browser:** [Chrome 51.0.2704.103 ] 
 
* **Language:** [TypeScript 1.8.9 ]

**Comment by vicb** [comment]
The issue would be solved with `headers.set ('Content-Type', 'application/json')`, notice the *T*.

It will be fixed in a later release
