### ISSUE TITLE
Angular 2 Tutorial "Tour of Heros" currently doesn't work

### ISSUE THREAD

**Issue by abductedMind** [angular/angular#9453]
This is a bug with content in documentation. Angular 2 Tutorial "Tour of Heros" currently doesn't work: https://angular.io/resources/live-examples/toh-6/ts/plnkr.html. 

This is linked to from https://angular.io/docs/ts/latest/tutorial

The issue seems to be related to how content is getting loaded on the page because there are 404 errors.

**Comment by abductedMind** [comment]
This is a bug with content in documentation. Angular 2 Tutorial "Tour of Heros" currently doesn't work: https://angular.io/resources/live-examples/toh-6/ts/plnkr.html. This is linked to from https://angular.io/docs/ts/latest/tutorial/

**Comment by ericmartinezr** [comment]
@abductedMind would you mind to open the issue in https://github.com/angular/angular.io? That's the repo for the website/tutorial :P

**Comment by abductedMind** [comment]
Ha! OK, I'm changing the issue to "site feedback" link on angular.io should like to  https://github.com/angular/angular.io

**Comment by abductedMind** [comment]
I have added two issues to the other location, this should be closed now.
