### ISSUE TITLE
Use a new form with multi checkboxes

### ISSUE THREAD

**Issue by xgrommx** [angular/angular#9455]
Hello everyone! I have some problem with new forms. I need to use multi state like
```js
[{id:1, value:10, status:true}, {id:2, value:20, status:false}]
```
And I want to use model first form. But I don't have some idea how can I do it now. Thanks for your advices.

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)
