### ISSUE TITLE
'terminal' does not exist in type 'Route'

### ISSUE THREAD

**Issue by a5hik** [angular/angular#9456]
@angular/core: 2.0.0-rc.1
@angular/router: 3.0.0-alpha.3
 
angular-cli: 1.0.0-beta.6
node: 6.2.1
os: darwin x64

Hi I'm following https://angular.io/docs/ts/latest/guide/router.html

`export const CrisisCenterRoutes: RouterConfig = [
  {
    path: '',
    redirectTo: '/crisis-center',
    terminal: true
  }
];`
But I get the below error when I use the 'terminal' property in Route.

```
Type '{ path: string; redirectTo: string; terminal: boolean; }' is not assignable to type 'Route'.
      Object literal may only specify known properties, and 'terminal' does not exist in type 'Route'.
```

Does the 'terminal' property supported?

**Comment by ericmartinezr** [comment]
Upgrade to latest router alpha 7

**Comment by michaelchiche** [comment]
terminal property appeared in alpha.6

**Comment by a5hik** [comment]
Hi I have upgraded to alpha.7 and it works fine. This can be closed. Thanks.
