### ISSUE TITLE
[router] routerLink in rc3 doesn't work in *ngIf or *ngFor

### ISSUE THREAD

**Issue by Tragetaschen** [angular/angular#9457]
**I'm submitting a ...**  (check one with "x")
way too verbose…
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
due to an unreadable issue template

**Current behavior**
`<div *ngIf="condition"><a [routerLink]="['./a']">a</a></div>` navigates to the '/' route or wherever that redirectsTo when the condition becomes true later.
`<div *ngIf="true"><a [routerLink]="['./a']">a</a></div>` navigates to the '/a' route.

I can see in the console that in the first case, the Router in the RouterLink seems to be a fresh one where `this.navigationId == 0`. In the latter case, the Router is already "used" and `this.navigationId == 1`.

**Expected/desired behavior**
The first should navigate to '/a' as well

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

Will do tomorrow

**What is the expected behavior?**
See above. Why ask twice?

**What is the motivation / use case for changing the behavior?**
Make it work as expected?

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
 
* **Browser:** [all<s> | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView </s>] 
 
* **Language:** [<s>all | </s>TypeScript 1.8.10<s> | ES6/7 | ES5 | Dart</s>]

**Comment by Ferhat67** [comment]
Dont let your path values begin with an "/" with the new router. Had that problem too and it worked after i removed the slash. Pretty confusing tho.

**Comment by Tragetaschen** [comment]
The "fresh router" thing was not very accurate because I misinterpreted my break points. However, they point to the correct direction:

In my root component, I use './a' and this is interpreted
- relative to '/' while my root component is created before the initial navigation finishes and becomes '/a'
- relative to '/initial' when the new `[routerLink]` enters the component tree later and becomes '/current/a' which I think is matched to '/current', because that's where the anchor points to

As a workaround I'm using only absolute routes '/a' in the `[routerLink]`

**Comment by Tragetaschen** [comment]
Btw. I cannot get the router work in a Plnkr

**Comment by vsavkin** [comment]
Fixed: https://github.com/angular/angular/pull/9603
