### ISSUE TITLE
[bug] RC.2 breaks @ViewChild to component thru forwardRef (recursive component structures)

### ISSUE THREAD

**Issue by tycho01** [angular/angular#9459]
After [this commit](https://github.com/angular/angular/commit/c3d2459) from RC2 ("set fixed `@ViewChild` / `@ContentChild` right after the view is created"), my `@ViewChild`s started breaking, erroring with:
`Can't construct a query for the property <viewChildName> of <componentName> since the query selector wasn't defined`.

Since I'm using recursive component structures, I have to use `forwardRef` to include the child components as directives into the host component. So what I have is like this:

    @Component({
      directives: [ forwardRef(() => ChildComp) ]
    })
    class HostComp {
      @ViewChild(ChildComp) child: ChildComp;
    }

The undefined selector here is the `ChildComp` argument of `@ViewChild(ChildComp)`. If this `forwardRef` is not yet resolved here at the moment it's interpreting the `ViewChild` since RC2, then I guess it makes sense that it's coming up with an undefined selector.

I've yet to verify that with a minimal reproduction though. Plunker forthcoming -- I may need to await until my recent [PR](https://github.com/angular/angular/pull/8705) lands into the next RC. Anyway, posting this already in case anyone else has come across this error as well.

**Comment by ericmartinezr** [comment]
The error you're seeing comes from this fix https://github.com/angular/angular/pull/9018 for this issue https://github.com/angular/angular/issues/4489

**Comment by tycho01** [comment]
Thanks, that does look even more relevant.

**Comment by pkozlowski-opensource** [comment]
@tycho01 could you please share a minimal plunker (please use RC.3)? I'm surprised that it used to work, would like to confirm.

**Comment by vicb** [comment]
Would that work ?

```
class HostComp {
  @ViewChild(forwardRef(() => ChildComp)) child: ChildComp;
```

**Comment by pkozlowski-opensource** [comment]
Yep, `forwardRef` will work, so we've got an easy work-around: https://plnkr.co/edit/sbQ1lKL9YexoFVfYa7Cp?p=preview

I'm still very much surprised it used to work without `forwardRef`....

**Comment by tycho01** [comment]
Yeah, that seems to be helping. Thanks for the quick suggestions guys. Now I'm actually getting a `Unexpected directive value 'undefined' on the View of component 'MyComp'` and a test timeout instead, but let me just not blame those on Angular yet for now (until after at least some further investigation). :P
