### ISSUE TITLE
Router 3.0.0-alpha.7 querystring on root throws exception

### ISSUE THREAD

**Issue by rickjz** [angular/angular#9460]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When going to your angular application root page with a querystring (www.mywebsite.com/?test or www.mywebsite.com/?test=test) you get the following exception:
EXCEPTION: Error: Uncaught (in promise): Error: Cannot match any routes: ''

**Expected/desired behavior**
Navigate to the default route.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

Please tell if needed.

**What is the expected behavior?**
See above.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3 
 
* **Browser:** [all] 
 
* **Language:** [TypeScript 1.8.10]

**Comment by Axel3232** [comment]
+1 Having exactly the same issue with the same environnement

**Comment by cguilhermef** [comment]
+1

**Comment by admirallightningbolt** [comment]
I think this is an issue with the url_serializer.  The parseRootSegment() function isn't checking to see if there are query params, so it tries to load children when they don't exist (line 135):
`if (this.remaining === '' || this.remaining === '/')`
The extra query params in the url trick the serializer into thinking there are children.

**Comment by vsavkin** [comment]
Fixed: https://github.com/angular/angular/pull/9603
