### ISSUE TITLE
Angular 2 RC 2 Hammer Gestures

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular#9461]
Its not clear if the Hammer gestures are supported in Angular 2 RC 2 or not.

From the API we can see 

```
HAMMER_GESTURE_CONFIG 
HammerGestureConfig
```

under 

`@angular/platform-browser
`
`( https://angular.io/docs/ts/latest/api/#!?apiFilter=hammer )`

But its not clear how to use it, some posts on internet suggest including hammer.js but if its a part of API I believe one would expect to use it without any external dependency.

**Comment by vicb** [comment]
It is supported, please check playground/src/gestures.

We should document it better /cc @wardbell

**Comment by naveedahmed1** [comment]
Thank you so much Victor for your reply. I just checked that, and the below file from playground/src/gestures suggests that we will have to include include Hammmer.js as its also including custom build of hammer.

 https://github.com/angular/angular/blob/master/modules/playground/src/gestures/index.html

Please correct me if I am wrong.

**Comment by vicb** [comment]
That was the case when the example was creating probably 1y+ ago because some fix commits were not released. I think they have been released since then.

May be you can try to install the latest hammer.js and update the example. If this works, please submit a PR. Thanks.

**Comment by naveedahmed1** [comment]
Yes, I tried that before opening the issue and if I include below script everything works.

`<script src="http://hammerjs.github.io/dist/hammer.min.js"></script>`

Actually I thought that since its part of angular framework may be it could work without including hammmerjs

**Comment by vicb** [comment]
If you want to update the example in a PR, please add hammerjs as a dev dependency in the package.json and use it from there. Thanks.

**Comment by naveedahmed1** [comment]
I have added hammerjs to package.json. Can you please confirm the path which it should map too in live repository:

On my device the following works:

<script src="/node_modules/hammerjs/hammer.min.js"></script>

**Comment by vicb** [comment]
Check /build.sh to create a link from node_modules in the playground/vendor folder

You can then load the script from `/all/playground/vendor/hammer.js`

You can test by running build.sh and then got to /dist and run http-server (might need `npm i -g http-server`ifyou don't have this installed)

**Comment by wardbell** [comment]
Close as too old.
