### ISSUE TITLE
Why AsyncRoute was removed?

### ISSUE THREAD

**Issue by robwormald** [angular/angular#9472]
_From @darxx on June 21, 2016 19:53_

Notice that **AsyncRoute**  is no longer present.
How to load components and routes on demand is **AsyncRoute** removed?
Can`t find. I need to integrate angular components as plugins from another sources. Is it another why to make routes and components loaded from external source that is on the same domain as plugins?

@angular/router - **v3.0.0-alpha.7** 
Something like https://www.sitepoint.com/community/t/dynamic-route-and-controller-from-json/212806

_Copied from original issue: angular/vladivostok#101_

**Comment by robwormald** [comment]
_From @brandonroberts on June 21, 2016 20:10_

The routes were simplified so there is on one type of `Route` now. You can still load components async right now and async routes will be coming soon.

**Comment by vsavkin** [comment]
Closing this.

- You can load components asynchronously by providing a SystemJsComponentResolver.
- Right now, you can load routes asynchronously and imperatively update the configuration using `resetConfig`.
- Once AppModules are in master, we will utilize those to implement async loading of subconfigs.
