### ISSUE TITLE
Url doesn't emit new collection of UrlPathWithParams for catch-all routes

### ISSUE THREAD

**Issue by robwormald** [angular/angular#9473]
_From @zhura on June 21, 2016 20:55_

Here is plnkr: http://plnkr.co/edit/jWfEpsNJ35pg6Cqn7H5q?p=preview

Actually I think we should rewrite `advanceActivatedRoute` function here ( https://github.com/angular/vladivostok/blob/master/src/router_state.ts#L181) something like:

```
export function advanceActivatedRoute(route: ActivatedRoute): void {
  if (route.snapshot) {
    let prevParams = route.snapshot.params;
    let prevUrl = route.snapshot.url;
    route.snapshot = route._futureSnapshot;
    if (!shallowEqual(prevParams, route.snapshot.params))
      (<any>route.params).next(route.snapshot.params);
 
    if (!shallowEqual(prevUrl, route.snapshot.url))
      (<any>route.url).next(route.snapshot.url);
  } else {
    route.snapshot = route._futureSnapshot;
  }
}
```

_Copied from original issue: angular/vladivostok#102_

**Comment by zhura** [comment]
@robwormald I've already created copy of this issue (angular/vladivostok#102). 
See #9418

**Comment by robwormald** [comment]
ah, good to know, thanks! 👍
