### ISSUE TITLE
Feat: Add support for Pathless Routes

### ISSUE THREAD

**Issue by robwormald** [angular/angular#9474]
_From @otodockal on June 6, 2016 20:4_

It would be great to support **Pathless Routes** like **@ngrx/router** does.
https://github.com/ngrx/router/blob/master/docs/overview/route.md#pathless-routes

If it's planned(or something similar) or even implemented, sorry for the SPAM.

**@ngrx/router** example/usecase:
http://plnkr.co/edit/X2tKoD?p=preview

**vladivostok** example (doesn't work...):
https://plnkr.co/edit/GFcgFz?p=preview

_Copied from original issue: angular/vladivostok#23_

**Comment by robwormald** [comment]
_From @serhiiso on June 13, 2016 12:51_

You can achieve pathless with router alpha.6:
```
{
    path: '',
    component: ProtectedComponent,
    children: [
      { path: '', redirectTo: '/dashboard' },
      { path: 'dashboard', component: DashboardComponent },
      { path: 'faq', component: FaqComponent },
    ]
  }
```

But in this case router won't redirect user to ```/faq``` because it will redirect back to ```/dashboard```

If we'll remove ```{ path: '', redirectTo: '/dashboard' }``` in this case router won't find default route to load causing :
```
EXCEPTION: Error: Uncaught (in promise): Error: Cannot match any routes: ''
```

**Comment by serhiiso** [comment]
That solution works good with router alpha.7 and ```terminal``` option:

```
{
    path: '',
    component: ProtectedComponent,
    children: [
      { path: '', redirectTo: '/dashboard', terminal: true },
      { path: 'dashboard', component: DashboardComponent },
      { path: 'faq', component: FaqComponent },
    ]
  }
```

**Comment by vsavkin** [comment]
Closing the issue as `path: ''` is essentially a pathless route.

**Comment by serhiiso** [comment]
👍
