### ISSUE TITLE
Proposal: Assume relative navigation are being performed relative to the current activated route

### ISSUE THREAD

**Issue by robwormald** [angular/angular#9476]
_From @nosachamos on June 10, 2016 1:31_

When performing relative navigation involving routes that start with `./` and `../`, could we make the `{relativeTo: this.currentActivatedRoute}` implicit?

Example, make:
```
// from within /team/3, perform a relative navigation to /team/3/details
this.router.navigate(['./details'], {relativeTo: this.route});
```

...be equivalent to:

```
// from within /team/3, perform a relative navigation to /team/3/details
this.router.navigate('./details');
```

Another example, make:

```
// from within /team/3, perform a relative navigation to /team/4
this.router.navigate(['../4'], {relativeTo: this.route});
```

...be equivalent to:

```
// from within /team/3, perform a relative navigation to /team/4
this.router.navigate('../4');
```

Not sure this is feasible, but I suppose performing navigation relative to the currently activated route will be the majority of the cases... this way we could save folks the trouble to inject the current ActivatedRoute, etc.

Thoughts?

_Copied from original issue: angular/vladivostok#32_

**Comment by choeller** [comment]
Actually I was struggling with this for half an hour now. IMO the `navigate`-method should behave equivalent to the way the `RouterLink`-Directive works.

**Comment by vsavkin** [comment]
Currently, the router service is a singleton. And there are a lot of nice properties we get from having it this way. What you asking for would require us to create a new service for every outlet.

You can get what you want if you do the following:

```
@Directive({selector: 'router-outlet'})
class ScopedRouter {
  constructor(private router: Router, private outlet: RouterOutlet) {}

  navigate(commands) {
   return this.router.navigate(commands, {relativeTo: this.outlet.activatedRoute});
  }
}
```

And then you can inject ScopedRouter instead of Router.

Closing this.
