### ISSUE TITLE
Support adding additional data to Route-Configurations (fka. RouteData)

### ISSUE THREAD

**Issue by robwormald** [angular/angular#9478]
_From @choeller on June 13, 2016 13:59_

With the deprecated Router it was possible to add additional data to a Route-Configuration like this:

```
@RouteConfig([
  {path: '/about', component: AboutComponent, name: 'About', data: {title :"About us"}},
])
```
with this information it was possible to do some generic operations when activating the route (e.g. setting the page title via `Title`-Service. It would be cool to have this possiblitity again. 

_Copied from original issue: angular/vladivostok#43_

**Comment by m1nd53t** [comment]
Another use case for this would be authentication.
Imagina a canActivate guard where you can set the permissions needed for a route in the data object.
