### ISSUE TITLE
[GuardChecks] Cannot read _routeConfig of null

### ISSUE THREAD

**Issue by robwormald** [angular/angular#9480]
_From @francois-appliware on June 14, 2016 13:47_

Hi,

I am working with the new router and had an issue that I "managed to resolve", but as I don't quite understand how everything works under the hood I prefer to open this issue and try to understand what is going on.

In my application, I have a few routes as following :
```javascript
{ path: '/dashboard', component: DashboardComponent },
{
    path: '/companies', component: CompanyComponent, children: [
        { path: '/details/:id', component: CompanyDetailComponent },
        { path: '/new', component: CompanyEditComponent },
        { path: '/', component: CompanyDetailComponent, index: true }
    ]
},
{
    path: '/keys', component: KeyComponent, children: [
        { path: '/details/:id', component: KeyDetailComponent },
        { path: '/new', component: KeyEditComponent },
        { path: '/', component: CompanyDetailComponent, index: true }
    ]
}
```

When I am navigating from companies to keys, I have the following error : 

> Error {rejection: TypeError: Cannot read property '_routeConfig' of null
    at GuardChecks.runCanDeactivate (http://l…, promise: ZoneAwarePromise, zone: Zone, task: ZoneTask, message: "Uncaught (in promise): TypeError: Cannot read property '_routeConfig' of null"}

So I went ahead and downloaded the code to see what was going on inside that "GuardChecks".

For what I understand, it is used for the CanActivate / CanDeactivate (that I do not use in any of my components). Also, from what I understand, it is working with nullable values (in my case, where I don't have such guards).

Problem is, at some point in adds a check **with** a null value that throws the previous error mentioned above.

I managed to solve my issue by replacing the following line inside "router.js" inside the method _GuardChecks.prototype.runCanDeactivate = function (component, curr)_
`var canDeactivate = curr._routeConfig ? curr._routeConfig.canDeactivate : null;`
by the following : 
`var canDeactivate = curr ? (curr._routeConfig ? curr._routeConfig.canDeactivate : null) : null;`

(Yes, it's ugly but that's a hotfix so I can continue working)
I think the check can be set before the 'runCanDeactivate', where the checks are added, maybe in the traverseRoutes method inside GuardChecks.

Is this a known bug or a real bug and needs a fix or is it intended ?

Thank you.

_Copied from original issue: angular/vladivostok#48_

**Comment by robwormald** [comment]
_From @losorio35 on June 14, 2016 14:31_


I have problems displaying routes children, tells me the following error:
Can not read property '_routeConfig' of null.
http://plnkr.co/edit/Oge7zn8m0bB1aRviDMbD?p=preview

**Comment by robwormald** [comment]
_From @briananderson1222 on June 14, 2016 15:16_

I'm seeing this issue without using GuardChecks at all when attempting to navigate from a child route to another child route with a different parent. Still need to dig a little deeper to figure out where my issue lies exactly

**Comment by robwormald** [comment]
_From @laco0416 on June 15, 2016 23:9_

probably dup of https://github.com/angular/vladivostok/issues/26

**Comment by robwormald** [comment]
_From @francois-appliware on June 16, 2016 7:29_

The error is still happening with rc2 and router alpha 6.

**Comment by robwormald** [comment]
_From @hlobil on June 16, 2016 11:51_

I am also getting the error navigating between two routeConfig that have children. I don't have any guards. alpha 6 router did not fix the issue.

/**parentA**/childX to /parentB/ fails and so does the reverse
/parentB/childY to  /**parentA**/

The error is visible when.
```
{provide: LocationStrategy, useClass: HashLocationStrategy}
```
The navigation still fails, but no error is reported if the above statement is not present

**Comment by robwormald** [comment]
_From @briananderson1222 on June 16, 2016 16:43_

Unfortunately I can confirm that this appears to still not be working with the latest alpha 6 and rc2. My case is parentA/childA navigate to parentB/childB

I too am using the HashLocationStrategy, not sure if that helps in identifying the cause..

**Comment by robwormald** [comment]
_From @Ellipizle on June 17, 2016 0:28_

i had a similar issue 
`
at GuardChecks.runCanDeactivate (http://localhost:4200/vendor/@angular/router/router.js:304:33)` was where the issue was

**Comment by robwormald** [comment]
_From @a88zach on June 17, 2016 2:16_

same issue here. temp fix provided by @francois-appliware solved the issue for me

**Comment by robwormald** [comment]
_From @henzenD on June 17, 2016 6:42_

the same issue also applies for CanActivate, but the suggested quickfix by @francois-appliware also works here:
in **router.js:r286**, replace
`var canActivate = future._routeConfig ? future._routeConfig.canActivate : null;`
by
`var canActivate = future && future._routeConfig ? future._routeConfig.canActivate : null;`

**Comment by robwormald** [comment]
_From @briananderson1222 on June 17, 2016 15:32_

I believe this is meant to address this issue: https://github.com/angular/vladivostok/pull/76

**Comment by robwormald** [comment]
_From @byavv on June 17, 2016 21:22_

Still in alpha 7.

**Comment by robwormald** [comment]
_From @sky-coding on June 19, 2016 5:22_

This bug is still present and is blocking our development using the new router. This is very frustrating given that the blog says to use 3.0 immediately, and documentation has been removed

**Comment by robwormald** [comment]
_From @rbaumi on June 19, 2016 19:20_

Same here in aplha.7. Solution given by @francois-appliware solves the issue.

**Comment by robwormald** [comment]
_From @sky-coding on June 19, 2016 22:6_

Modifying within `node_modules` or using `npm link` are not viable solutions for an automated production application, anxiously awaiting a fix before development can continue. Thanks!

**Comment by robwormald** [comment]
_From @maxailloud on June 20, 2016 9:24_

I have the same issue, not using guards at all:

```
browser_adapter.ts:74 Error: Uncaught (in promise): TypeError: Cannot read property '_routeConfig' of null
    at resolvePromise (zone.js:538)
    at zone.js:515
    at ZoneDelegate.invoke (zone.js:323)
    at Object.onInvoke (ng_zone_impl.ts:64)
    at ZoneDelegate.invoke (zone.js:322)
    at Zone.run (zone.js:216)
    at zone.js:571
    at ZoneDelegate.invokeTask (zone.js:356)
    at Object.onInvokeTask (ng_zone_impl.ts:53)
    at ZoneDelegate.invokeTask (zone.js:355)
```

**Comment by robwormald** [comment]
_From @3urdoch on June 20, 2016 12:20_

I'm having the same issue, but only happens if you navigate between routes with child routes i.e.

assuming routes `/a` and `/b` both have child routes but `/c` and `/d` don't somewhat like below.

```
const routes: RouterConfig = [
  {  
     path: '/a', 
     component: AComponent,
     children: [ ... ]
   },
  {  
     path: '/b', 
     component: BComponent,
     children: [ ... ]
   },
  { path: '/c', component: CComponent },
  { path: '/d', component: DComponent },
];
```

from `/a` to `/b` produces the error
from `/a` to `/c` is fine
from `/c` to `/a` is fine
from `/c` to `/d` is fine

**Comment by robwormald** [comment]
_From @rbaumi on June 20, 2016 12:46_

@3urdoch - from alha.7 using shasles on the front of path is not allowed. Your config should look like:

```
const routes: RouterConfig = [{  
     path: 'a', 
     component: AComponent,
     children: [ ... ]
   }, {  
     path: 'b', 
     component: BComponent,
     children: [ ... ]
   },
  { path: 'c', component: CComponent },
  { path: 'd', component: DComponent },
  { path: '', component: DefaultNotMachComponent }
];
```

in your case thats the bug is in GuardChecks.prototype.runCanDeactivate func as described by @francois-appliware. You can modify the router.js but as @sky-coding wrote - this is not good for automated production env. I had to do that for my dev env to be able to continue development.

**Comment by robwormald** [comment]
_From @ericmartinezr on June 20, 2016 14:20_

This is supposed to be fixed here https://github.com/angular/vladivostok/commit/9d6819b39e2b7952bc724c7531c4f53182af5e95 as mentioned here https://github.com/angular/vladivostok/pull/76#issuecomment-227150284 so if that didn't land with alpha 7, it should with alpha 8.

**Comment by robwormald** [comment]
_From @francois-appliware on June 20, 2016 14:27_

Let's hope the new version will arrive soon then :)

**Comment by robwormald** [comment]
_From @matejkramny on June 21, 2016 13:46_

any way to use w/o having to wait for a release?

**Comment by robwormald** [comment]
_From @a88zach on June 21, 2016 13:48_

You can apply the manual fix that @francois-appliware provided and then check the package into your source control.  It's not ideal, but it will work temporarily

**Comment by sfabriece** [comment]
@vsavkin  Can you please update this thread when a fix is live. Thanks 👍

**Comment by ericmartinezr** [comment]
@sfabriece the fix landed with alpha 8, which is already live, see the changelog for the router https://github.com/angular/angular/blob/master/modules/%40angular/router/CHANGELOG.md.

**Comment by sfabriece** [comment]
Thanks @ericmartinezr. It's hard to keep up with all the changelogs. Bookmarked!

**Comment by dgroh** [comment]
Having the same issue when using `this.router.navigate` inside `ngOnInit` of `app.component.ts`
