### ISSUE TITLE
Potential Issue with RouterLink: Error: Invalid number of '../'

### ISSUE THREAD

**Issue by robwormald** [angular/angular#9481]
_From @kaeku on June 15, 2016 13:52_

Hi folks,

I think I stumpled upon an issue with the `routerLink` directive. I tried using with an expression, which worked fine with the v2 router. However, now I'm getting this issue:

```
Error: Invalid number of '../'
    at findUrlSegment (create_url_tree.ts:106)
    at findStartingNode (create_url_tree.ts:96)
    at Object.createUrlTree (create_url_tree.ts:19)
    at Router.createUrlTree (router.ts:187)
    at RouterLink.updateTargetUrlAndHref (router_link.ts:71)
    at RouterLink.ngOnChanges (router_link.ts:56)
    at DebugAppView._View_SystemMenuComponent2.detectChangesInternal (SystemMenuComponent.template.js:466)
    at DebugAppView.AppView.detectChanges (core.umd.js:9996)
    at DebugAppView.detectChanges (core.umd.js:10084)
    at DebugAppView.AppView.detectContentChildrenChanges (core.umd.js:10011)
```

I tried debugging it, and kinda narrowed it down to `createUrlTree` and got stuck there. The template code looks like this: 

```
<ul class="left" *ngIf="menuItems.length > 0">
    <li *ngFor="let item of menuItems">
      <a [routerLink]="[item.link]"> // item.link = '/start-screen' in this specific scenario
        <figure>
          <img src="assets/img/{{ item.icon }}-icon.png" />
          <figcaption>
            {{ item.name }}
          </figcaption>
        </figure>
      </a>
    </li>
  </ul>
```

Any help would be greatly appreciated. Thanks! :)

_Copied from original issue: angular/vladivostok#54_

**Comment by robwormald** [comment]
_From @mschwarzmueller on June 15, 2016 17:18_

Hi, I also encountered that issue and found that it only throws this error if I try to use `./` or `../` route links in my root component (AppComponent) which holds the `<router-outlet>`. 
In components loaded through the router into that `<router-outlet>` it works fine. 

Maybe this helps you.

**Comment by robwormald** [comment]
_From @kaeku on June 15, 2016 17:24_

Unfornately I'm getting the same errors for any of the following: `start-screen`, `./start-screen`, `../start-screen`or `/start-screen`

I think the issue is due to the use of a variable, although I could be wrong.

**Comment by robwormald** [comment]
_From @gustavLatte on June 15, 2016 20:10_

I had the same issue and after multiple changes i got to the conclusion that dropping `/` resolved the issue. i think it has something to do with the tree structure

**Comment by robwormald** [comment]
_From @kaeku on June 16, 2016 10:8_

Resolved as of Alpha 6.

**Comment by vsavkin** [comment]
It looks like the issue has been resolve in alpha 6.
