### ISSUE TITLE
alpha3 router requires parenthesis in query string to be encoded

### ISSUE THREAD

**Issue by robwormald** [angular/angular#9482]
_From @kamarouski on June 16, 2016 1:36_

The router currently requires parenthesis characters '(' and ')' to be encoded in query string. Otherwise it replaces query string parameter with 'true'  value

e.g. http://aweso.me/path?p=(param) is replaced with http://aweso.me/path?p=true

http://aweso.me/path?p=%28param%29 works fine

Parenthesis are valid query string characters, it's not encoded by encodeURIComponent.

Expected result: parenthesis characters are supported without encoding.

_Copied from original issue: angular/vladivostok#58_

**Comment by vsavkin** [comment]
The issue has been fixed:https://github.com/angular/angular/blob/master/modules/@angular/router/test/url_serializer.spec.ts#L99
