### ISSUE TITLE
Slash in route params values Cannot match any routes on refresh with HashLocationStrategy

### ISSUE THREAD

**Issue by robwormald** [angular/angular#9483]
_From @Delagen on June 16, 2016 8:9_

simple url http://site.com/#/route;back=/a/b/c

Error: Cannot match any routes: 'route;back=true/a/b/c'

_Copied from original issue: angular/vladivostok#59_

**Comment by robwormald** [comment]
_From @Delagen on June 16, 2016 8:10_

Referece angular/angular#8603 angular/angular#8461

**Comment by robwormald** [comment]
_From @zoechi on June 16, 2016 8:17_

What's the purpose of this issue if there are 2 similar already? What router version are you using?
If your previous comment was meant to point out duplicates you could close the issue yourself.

**Comment by robwormald** [comment]
_From @Delagen on June 16, 2016 8:25_

3.0.0-alpha.6
Third iteration of router but still not usable in some cases, and solution not provided

**Comment by robwormald** [comment]
_From @zoechi on June 16, 2016 8:53_

Sorry, I missed that this is not the https://github.com/angular/angular repo

**Comment by vsavkin** [comment]
I tried to reproduce the issue using the latest release of the router, and it looks like the issue has been fixed. If you can still repro the issue, please provide a plunker.

**Comment by Delagen** [comment]
Does not fixed

**Comment by vsavkin** [comment]
@Delagen did you try to use the latest version (the one from router builds)?
