### ISSUE TITLE
alpha.6: Matrix-Params are not working for index-routes of nested routes anylonger

### ISSUE THREAD

**Issue by robwormald** [angular/angular#9484]
_From @choeller on June 16, 2016 13:13_

with alpha.3 I was able to do the following:

```ts
 RouterConfig = [
  { path: '/tasks', component: TasksComponent,
    children: [
      {component: TaskListComponent, index: true},
      ...
    ]
  }
]
```
```
http://localhost:4200/tasks;query=BACKLOG
```

TaskListComponent:
```ts
  constructor(private taskService: TaskService,
                     private route: ActivatedRoute) {
  }
  ngOnInit() {
    this.route.params.subscribe((params) => {
      let query = decodeURI(params['query'] || '');
      this.findTasks(query);
    });
  }
```

since alpha.4 up until alpha.6 the observable is never invoked. Also the params object is empty when using the snapshot. When using params on an "ordinary" route (no index-route) the values are transfered perfectly fine

_Copied from original issue: angular/vladivostok#62_

**Comment by robwormald** [comment]
_From @brandonroberts on June 16, 2016 13:56_

The index routes are deprecated in the latest alpha in favor of redirects. Instead of `index: true`, use `path: '/'` for the TaskListComponent route

**Comment by robwormald** [comment]
_From @choeller on June 16, 2016 13:58_

@brandonroberts you have been faster then me... I just saw that and tried the following config:

```ts
RouterConfig = [
  { path: '/tasks', component: TasksComponent,
    children: [
      {path: '/',component: TaskListComponent},
      {path: '/edit/:id', component: EditTaskComponent},
      {path: '/new', component: EditTaskComponent}
    ]
  }
]
```
but the behaviour is exactly the same - matrix-params are not passed... seems that the router is not considering the child-route as the one responsible for this path-segment

**Comment by robwormald** [comment]
_From @brandonroberts on June 16, 2016 14:1_

I see. So do you get the matrix params in the parent route?

**Comment by robwormald** [comment]
_From @choeller on June 16, 2016 14:3_

yes - exactly. just added that to my source-code:
```ts
export class TasksComponent {
  constructor(private route: ActivatedRoute) {
    route.params.subscribe((params) => {
      console.log(params); //prints Object {query: "BACKLOG"}
    });
  }
}
```
and the params are printed there correctly (which when thinking about it, I would also assume) I think in this case the matrix-params would need to be passed to both `TasksComponent` and `TaskListComponent`. At least that is, how it worked in alpha.3 - also I see no other way to pass parameters to nested routes.

**Comment by robwormald** [comment]
_From @brandonroberts on June 16, 2016 15:25_

You can't pass them down, but you can access parent parameters from nested routes

**Comment by robwormald** [comment]
_From @briananderson1222 on June 16, 2016 16:56_

@brandonroberts Can you elaborate on how exactly to access parent parameters from a child route? 

I have a setup that looks like this:
```js
{
    path: '/c/:id',
    component: CComponent,
    children: [
      {
        path: '/',
        component: CViewComponent,
      },
      {
        path: '/summary',
        component: CSummaryComponent
      }
    ]
  }
```
but in my summary child component I cannot seem to access the `id` parameter through the ActivatedRoute.. I suppose I could just move the :id to each child route and that would likely resolve this, but I would think this would still be possible unless I am misunderstanding your statement.

**Comment by robwormald** [comment]
_From @brandonroberts on June 16, 2016 18:18_

@briananderson1222 Sure. The router provides a `routerState` property that gives you access to the entire route tree and a point in time. You can use methods on this tree such as `parent`, `children` to go up and down the tree.

Here is a plunker:  http://plnkr.co/edit/kPanTNUpUDEY25y6pYWl?p=preview

The child component and use the router state to get its parent and access its params.

**Comment by robwormald** [comment]
_From @ElsewhereGames on June 18, 2016 3:22_

> The index routes are deprecated in the latest alpha in favor of redirects. Instead of index: true, use path: '/' for the TaskListComponent route

But with the latest alpha you can't use slashes in a path anymore?

**Comment by robwormald** [comment]
_From @brandonroberts on June 18, 2016 3:51_

@ElsewhereGames correct. There is no leading slash in the path. It provides a more clear distinction between relative and absolute paths.

**Comment by robwormald** [comment]
_From @ckapilla on June 18, 2016 12:19_

Just to be clear, since this is something I’ve been wondering about, are you saying that ‘/’ does not count as a leading slash? If it does count then there would seem to be a catch-22. Thanks.

**Comment by robwormald** [comment]
_From @brandonroberts on June 18, 2016 15:49_

@ckapilla correct. `'/'` should just be `''`

**Comment by robwormald** [comment]
_From @nosachamos on June 18, 2016 22:41_

@ckapilla <https://github.com/ckapilla> for this reason, on alpha 7 leading
slashes are disallowed entirely. So there will be no confusion.

2016-06-18 10:49 GMT-05:00 Brandon <notifications@github.com>:

**Comment by vsavkin** [comment]
This is by design. The same set of parameters should not be used by both a parent and a child components. If you want to access the parameters of the parent component, you can always do it by getting its activated route.

**Comment by choeller** [comment]
@vsavkin Ok I see, but it should work with componentless parent-routes, as the params of them should be merged into children, right? When I try this:

```
RouterConfig = [
  { path: '/tasks', 
    children: [
      {path: '',component: TaskListComponent},
      {path: '/edit/:id', component: EditTaskComponent},
      {path: '/new', component: EditTaskComponent}
    ]
  }
]
```
`TaskListComponent` still does not get the params from the componentless route:

```
http://localhost:4200/tasks;query=BACKLOG
```
```ts
export class TaskListComponent {
  constructor(private route: ActivatedRoute) {
    route.params.subscribe((params) => {
      console.log(params); //prints Object {}
    });
  }
}
```

**Comment by fearless23** [comment]
create a service and add it to provider array of  TaskListComponent and then inside child component use that service to get id which will be same for all child components.
Don`t provide service in provider array of child components.
