### ISSUE TITLE
Bug: Router doesn't render `/` route

### ISSUE THREAD

**Issue by robwormald** [angular/angular#9485]
_From @brandonroberts on June 1, 2016 20:35_

**Current behavior**

When the `/` route is loaded, the `Home` component is not rendered

**Expected/desired behavior**

When the `/` route is loaded, the `Home` component is rendered

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

http://plnkr.co/edit/0Qv95J?p=preview

If you click on the `Away` link, the route component is rendered correctly, but if you click on the `Home` link, nothing is displayed, then the `Away` link stops working also.

cc: @vsavkin 

_Copied from original issue: angular/vladivostok#6_

**Comment by vsavkin** [comment]
@brandonroberts 
I believe the issue has been fixed. Could you try to reproduce it?

**Comment by brandonroberts** [comment]
@vsavkin this one is fixed and can be closed
