### ISSUE TITLE
Accessing Parameters on '' Parent Route without children

### ISSUE THREAD

**Issue by robwormald** [angular/angular#9487]
_From @briananderson1222 on June 16, 2016 17:10_

I have a route that lives at the root of the site where I am attempting to access query parameters set on this route.

I have tried the following..

/?kw=test produces the following output:
```
browser_adapter.ts:84 EXCEPTION: Error: Uncaught (in promise): Error: Cannot match any routes: ''
```

/;kw=test produces the following output:
```
browser_adapter.ts:84 EXCEPTION: Error: Uncaught (in promise): Error: Cannot match any routes: ';kw=test'
```

I don't seem to have this issue on child routes using the ; syntax for the query parameters. Is there something I am missing here or is this a bug?  I suppose in meantime I could try and use a strategy similar to the one called out in https://github.com/angular/vladivostok/issues/60 but just curious if anyone has any suggestions.

**UPDATE**: I was able to get this working using the empty path redirect with terminal.. I think the issue still exists at the root.

_Copied from original issue: angular/vladivostok#67_

**Comment by robwormald** [comment]
_From @ghostofcain on June 21, 2016 7:42_

Same problem here. Have setup a root on the top level (referenced from main.ts) like this:

{ path: 'reset/:id', component: ResetComponent }

but I can't get it to work at all. Exact same steps you've tried and exact same errors you're getting. Using alpha 7.

Are we not supposed to have routes with parameters on the top (main.ts) level?

**Comment by briananderson1222** [comment]
Just a heads up. I know this got copied from the old repo but looks to have been filed here: https://github.com/angular/angular/issues/9460 as well

**Comment by vsavkin** [comment]
Fixed here https://github.com/angular/angular/issues/9460
