### ISSUE TITLE
[Feat] Lazy Configuration Loading / Lazily configuring the router 

### ISSUE THREAD

**Issue by robwormald** [angular/angular#9488]
_From @nolazybits on June 17, 2016 2:55_

Lazy loading is currently working, but I haven't seen the ability of defining routes lazy loaded alongside  component,  defining sub routes for this component.

1. Define application high level routes. .eg route /lazy, lazy loading the LazyComponent
2. LazyLoading component sub routes are somehow define for the router to know about either in the component itself or in a separate file. 
3. once lazy loaded the router check for sub routes on the component just loaded by checking for routes defined in 2
4. router adds route to the application routes
5. continue routing if the route requested was sub route of the loaded component. Fails as usual if the sub route requested doesn't exist.

_Copied from original issue: angular/vladivostok#75_

**Comment by robwormald** [comment]
_From @nosachamos on June 17, 2016 5:29_

@nolazybits Components are no longer in charge of defining any routes. They are defined separately, all at once. Maybe you refer to the ability of lazily configuring the router? In that case, it'd be a different request. Your steps seem to suggest you want components to be in charge of defining routes, and this is how the old routers worked, but not this one. This one works similarly to ngrx/router.

**Comment by robwormald** [comment]
_From @nolazybits on June 17, 2016 22:31_

Yeah I will change the title. I am referring of lazily configuring the router.

**Comment by robwormald** [comment]
_From @nolazybits on June 17, 2016 22:38_

@nosachamos just updated title and description. Thanks for the feedback. Hope it's clearer now.

**Comment by zoechi** [comment]
https://angular.io/docs/ts/latest/api/router/index/Router-interface.html#!#resetConfig-anchor `resetConfig` can be used
    

>     router.resetConfig([
>      { path: 'team/:id', component: TeamCmp, children: [
>        { path: 'simple', component: SimpleCmp },
>        { path: 'user/:name', component: UserCmp }
>      ] }
>     ]);

**Comment by vsavkin** [comment]
The lazy loading of modules has been merged into master. It's done by using the loadChildren property.

```
{
  path: 'section',
  loadChildren: 'section-bundle'
}
```

Closing this issue.
