### ISSUE TITLE
Documentation Out Of Date

### ISSUE THREAD

**Issue by robwormald** [angular/angular#9489]
_From @briananderson1222 on June 17, 2016 18:8_

https://angular.io/docs/ts/latest/guide/router.html has not been updated to include the latest alpha release. In Alpha 7 path's can no longer begin with '/'.

_Copied from original issue: angular/vladivostok#80_

**Comment by robwormald** [comment]
_From @brandonroberts on June 17, 2016 18:58_

Yep. The docs for the router will continue to be updated also.

**Comment by vsavkin** [comment]
Closing this issue. The docs have been updated.
