### ISSUE TITLE
dgeni is too harsh !

### ISSUE THREAD

**Issue by vicb** [angular/angular#949]
Background: I've just broken the build by adding some documentation...

But I think dgeni is too harsh.

I think we should encourage adding documentation and may be dgeni does not help here. This is the error I had:

```
error:   Error processing docs:  expected=["!", "(", "=", "?", "[]", "|"], found=W, offset=8, line=1, column=9, name=SyntaxError, message=Error running processor "extractTagsProcessor":
Expected "!", "(", "=", "?", "[]" or "|" but "W" found.
[18:46:31] 'docs/dgeni' errored after 1.82 s
[18:46:31] Error: SyntaxError: Error running processor "extractTagsProcessor":
Expected "!", "(", "=", "?", "[]" or "|" but "W" found.
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.EventEmitter.emit (events.js:95:17)
    at Gulp.Orchestrator._emitTaskDone (/home/victor/dart/angular/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /home/victor/dart/angular/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/home/victor/dart/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at /home/victor/dart/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:45:4
    at _rejected (/home/victor/dart/angular/node_modules/dgeni/node_modules/q/q.js:808:24)
    at /home/victor/dart/angular/node_modules/dgeni/node_modules/q/q.js:834:30
    at Promise.when (/home/victor/dart/angular/node_modules/dgeni/node_modules/q/q.js:1079:31)
```

- Could we make the error message clearer by making explicit what is wrong & where ?
- Could it be a warning rather than an error ?
- What about some documentation on what is the expected format (ie in CONTRIBUTING.md) ?

edit: and by the way my issue should probably be fixed [in a nicer way](https://github.com/angular/angular/commit/fde7e9e898ba6bfd8e1ba2a39da9ba08ed80d9b2#diff-f0296f81e9659f95b5da2c879297e2bdL69).

**Comment by petebacondarwin** [comment]
@vicb - sorry about this. I have had a chat with dgeni about its soft-skills and we are working on it being less harsh.

It turns out that the problem is a bug in the jsdoc **type** parser that the jsdoc dgeni package uses to extract type information from `@param` and `@return` tags. In this case, it got confused by this line:

```
 * @return {FunctionWithParamTokens}
```

It saw the word FunctionWithParamTokens and didn't realise that real people sometimes give their types names that start with the word **function**. Hence the error message, `Expected "!", "(", "=", "?", "[]" or "|" but "W" found.`

I will look into fixing this and also finding a way to express such errors more clearly so that it is easier to debug in the future.

**Comment by vicb** [comment]
Great, thanks for the quick reply.

Where could I find some information on the expected doc format ? Thanks.

**Comment by petebacondarwin** [comment]
I turns out it was actually a bug in the [catharsis jsdoc parser](https://github.com/hegemonic/catharsis) that dgeni-packages/jsdoc is using.

Upgrading to the latest version seems to solve this...

I will fix up and push out a new version of dgeni-packages using new catharsis and better errors.

**Comment by chalin** [comment]
Since 8407aa68fe8109798cfafc99b5ea07c28ef80b40, I am unable to run `npm install` without errors (on a clean checkout):
```
> fsevents@0.2.1 install /Users/chalin/git/angular/node_modules/dgeni-packages/node_modules/nunjucks/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
../node_modules/nan/nan.h:339:13: error: no member named 'New' in 'v8::String'
    return  _NAN_ERROR(v8::Exception::Error, errmsg);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Have you tried a clean `npm install` and if so, do you get errors too?

**Comment by chalin** [comment]
Actually, I reverted to `0.10.10` but that didn't help. Any idea what might be the problem with the `dgeni-packages`?

**Comment by petebacondarwin** [comment]
Those errors appear when I run npm install too but it doesn't prevent the installation from completing successfully.

**Comment by chalin** [comment]
Thanks for confirming that you get the errors too. I couldn't tell for sure if it completed successfully or not. So you suggest we just ignore the errors?

**Comment by petebacondarwin** [comment]
The problem is that the version of nunjucks in dgeni-packages is using, what appears to be, an out of date version of fsevents. I think we might benefit from upgrading nunjucks in dgeni-packages to version 1.2.0.

**Comment by petebacondarwin** [comment]
I pushed a new version of dgeni-packages (0.10.12) which uses a newer version of nunjucks. A clean install of angular should no longer have these errors.

**Comment by chalin** [comment]
Great, thanks Pete. Looking forward to trying it. Will you also be pushing an update to `angular/angular/package.json`?

**Comment by petebacondarwin** [comment]
It will automatically update since angular is dependent upon ^0.10.11 and 0.10.12 is a compatible version

**Comment by chalin** [comment]
I confirm that a fresh `npm install` ran smoothly for me. Thanks!

**Comment by petebacondarwin** [comment]
Magic!

**Comment by vicb** [comment]
@petebacondarwin Thanks!
