### ISSUE TITLE
Please tag future releases

### ISSUE THREAD

**Issue by robwormald** [angular/angular#9492]
_From @jeffschwartz on June 18, 2016 18:44_

When everything is master it makes it hard to track. Yes, I know I can look in package.json but I shouldn't have to because that is what git and tag are for. Also, kudos to all the maintainers of this router. I'm finally believing that this one will stick 😊.

_Copied from original issue: angular/vladivostok#84_

**Comment by IgorMinar** [comment]
we do tag releases now

**Comment by jeffschwartz** [comment]
Awesome! A big thanks out to all :)
