### ISSUE TITLE
default route with redirectTo not working

### ISSUE THREAD

**Issue by robwormald** [angular/angular#9493]
_From @xmlking on June 19, 2016 17:45_

First time when access root URL ("/") it redirects to  crisis-center as expected.
But when I click one of the crisis list items, I am getting attached error.
if I go to Heroes link and come back to CrisisCenter, it works as expected.
any suggestion to fix it ? 

```ts
export const CrisisCenterRoutes: RouterConfig = [
  { path: '', redirectTo: 'crisis-center', terminal: true},
  {
    path: 'crisis-center',
    component: CrisisCenterComponent,
    children: [
      {
        path: 'admin',
        component: CrisisAdminComponent,
        canActivate: [AuthGuard]
      },
      {
        path: ':id',
        component: CrisisDetailComponent,
        canDeactivate: [CanDeactivateGuard]
      },
      { path: '',
        component: CrisisListComponent
      }
    ]
  }
];
```
![image](https://cloud.githubusercontent.com/assets/627951/16178918/90d1be20-360a-11e6-915b-85ff892808b4.png)

_Copied from original issue: angular/vladivostok#85_

**Comment by robwormald** [comment]
_From @t246246 on June 20, 2016 5:56_

I'm not sure if it is a spec, but in your case
```javascript
{path: '', redirectTo: '/crisis-center', terminal: true}
```
is still(?) working on alpha-7.

**Comment by robwormald** [comment]
_From @xmlking on June 20, 2016 6:9_

router 3.0.0 alpha.7 deprecated usage of "/"

**Comment by robwormald** [comment]
_From @t246246 on June 20, 2016 6:20_

I know but it is for 'path'. Not mentioned to 'redirectTo'.
https://github.com/angular/vladivostok/commit/65b87f408ca2c39e8e3f2a32a77271c96b46443d

**Comment by robwormald** [comment]
_From @xmlking on June 20, 2016 6:37_

Thanks @t246246 
changing  `{ path: '', redirectTo: 'crisis-center', terminal: true}` to  `{ path: '', redirectTo: '/crisis-center', terminal: true}` worked as expected.

**Comment by t246246** [comment]
It seems same example works without '/' now in 3.0.0-alpha.8

**Comment by vsavkin** [comment]
The issue has been fixed https://github.com/angular/angular/commit/fbd2dd9ca27627d335dfd711137ee216d35522a2.

**Comment by ashikjs** [comment]
It work for my Angular 7...

`
            {
                path: '', redirectTo: '/dashboard', pathMatch: 'full',
            },
`
