### ISSUE TITLE
redirectTo should persist route and query params

### ISSUE THREAD

**Issue by robwormald** [angular/angular#9494]
_From @briananderson1222 on June 19, 2016 17:52_

Using the redirect strategy that I've seen floating around.

```js
{ path: '', redirectTo: 'home', terminal: true },
{ path: 'home', component: HomeComponent }
```

Loading the url `/;test=test?test=test` should persist both route and query params during redirect.

Currently neither the route params or query params are persisted.

_Copied from original issue: angular/vladivostok#86_

**Comment by robwormald** [comment]
_From @findjonmos on June 20, 2016 15:23_

Add a forward slash in front of redirectTo: 'home' - so that it looks as below...
`
{ path: '', redirectTo: '/home', terminal: true },
`

If they are going to remove / from all route paths should it not be done for redirectTo also...otherwise this is really confusing.

Routing is actually broken if you don't add this slash for redirectTo - no links will work!

**Comment by robwormald** [comment]
_From @brandonroberts on June 20, 2016 16:10_

@findjonmos the reason it still exists for redirects is that you can redirect relative to where you are, or absolute from the root.

```js
{ path: '', redirectTo: '/home', terminal: true },
{ path: 'home', component: HomeComponent },
{ path: 'old', redirectTo: 'new' },
{ path: 'new', component: NewComponent }
```

**Comment by robwormald** [comment]
_From @briananderson1222 on June 20, 2016 16:33_

Am I wrong to assume that route params should also persist during a redirect?

**Comment by robwormald** [comment]
_From @brandonroberts on June 20, 2016 16:57_

@briananderson1222 yes, they should

**Comment by briananderson1222** [comment]
Here is a plnkr that can demonstrate this: 
http://plnkr.co/edit/6jhtpi5v6fsrY0ZDHWly?p=preview

It requires query params so I have provided the generated run link below:
http://run.plnkr.co/CJYogYNB5TPUXbGu/?test=test

**Comment by vsavkin** [comment]
Fixed: https://github.com/angular/angular/pull/9748
