### ISSUE TITLE
routerLink directive on Root App Component template doesn't persist queryParams

### ISSUE THREAD

**Issue by robwormald** [angular/angular#9495]
_From @briananderson1222 on June 20, 2016 0:54_

In the template I have for my root app component I use the routerLink directive to direct a user back to the 'home' of my app throughout the application. This is not the only place I use a routerLink back to the home page but I have noticed that this is the only link that doesn't include seem to persist my queryParams when navigating around the application. 

Load URL appending `/route?test=test`

app.component.html
```js
<a [routerLink]="['/home']">{{ 'HOME' | translate }}</a>
```
--> This navigates to /home

some.component.html
```js
<a [routerLink]="['/home']">{{ 'HOME' | translate }}</a>
```
--> This navigates to /home?test=test 

_Copied from original issue: angular/vladivostok#88_

**Comment by briananderson1222** [comment]
http://plnkr.co/edit/6jhtpi5v6fsrY0ZDHWly?p=preview

This plnkr requires that you modify query Params. This was the generated run link example:

http://run.plnkr.co/CJYogYNB5TPUXbGu/#/parent/1/child?test=test 

note the bottom "Home" link persists the query params, but the top links don't

**Comment by sirajc** [comment]
The above run link of plnk gives Not found, Here is the the updated plunk.Issue can bee seen in the Preview as well http://plnkr.co/edit/zFVH7IzpBsUFGttKnxDA?p=preview

**Comment by vsavkin** [comment]
Fixed: https://github.com/angular/angular/pull/9748
