### ISSUE TITLE
Create `@angular/router/testing` and `ROUTER_FAKE_PROVIDERS`

### ISSUE THREAD

**Issue by robwormald** [angular/angular#9496]
_From @delasteve on June 13, 2016 20:7_

In order to test a component with a view that contains `[routerLink]`'s, you currently have to do the following:

```
class MockRouter { }
class MockActivatedRoute { }

...

beforeEachProviders(() => [
  provide(Router, { useClass: MockRouter }),
  provide(ActivatedRoute, { useClass: MockActivatedRoute })
]);
```

The v2 router has `ROUTER_FAKE_PROVIDERS`. It would be nice to have this again. 

_Copied from original issue: angular/vladivostok#45_

**Comment by robwormald** [comment]
_From @antonybudianto on June 16, 2016 15:54_

really need this back

**Comment by robwormald** [comment]
_From @JohannesHoppe on June 20, 2016 18:57_

Yes! This is a must have!

**Comment by laco0416** [comment]
@vsavkin Any plans for this?

**Comment by JohannesHoppe** [comment]
Woraround breaks again, with RC4 + `"@angular/router": "^3.0.0-beta.2"`
This is not funny at all!

**Comment by andrashatvani** [comment]
I need a mock router and fake router providers, too

**Comment by renehamburger** [comment]
@JohannesHoppe, have a look at the rc4 relase notes, in particular https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes. I haven't upgraded to rc4 yet, but it seems you're still using `beforeEachProviders`.

**Comment by delasteve** [comment]
@renehamburger `beforeEachProviders` is only deprecated, not removed. 

https://github.com/angular/angular/pull/9564/files#diff-bbae1db8b9b9adb0bc98af7e4916ab17R134

@JohannesHoppe How does it break? I seem to be using it just fine. I just helped someone yesterday and they got their tests working. Maybe I can help you, too?

**Comment by delasteve** [comment]
@andrashatvani I use SinonJS to mock out things in my ng2 project. It currently fails on the router, though.

https://github.com/sinonjs/sinon/issues/1036 / https://github.com/sinonjs/sinon/pull/1059 

Once this issue is resolved and a new version is released (the fix is already in), we should be able to use Sinon to mock out the router for us.

**Comment by DBSalvia** [comment]
So is there currently no way in RC4 with router 3.0.0 beta 2  to inject a router into a service I'm trying to test? (it subscribes to router events and performs actions on NavigationEnd) I tried to build a mock as implemented here:

https://github.com/angular/angular/blob/master/modules/%40angular/router/test/router.spec.ts 

But no joy it's throws some provider instantiation error.. Will post some code when I get back home

**Comment by delasteve** [comment]
@DBSalvia: I got the SinonJS team to update their `2.0.0-pre` release last night. This fixes the issue of using Sinon to mock out the Router.

I was able to do mock out the router in a much, much simpler way than the integration level test that you provided. This solution does not need to know how to configure the router dependencies, whereas you have a laundry list of things needed.

```js
import { ActivatedRoute, Router } from '@angular/router';
import { ExampleComponent } from './example.component';

describe('Component: Example', () => {
  let mockRouter: any;
  let mockActivatedRoute: any;
  let exampleComponent: ExampleComponent;
  // other variables for tests

  beforeEach(() => {
    mockRouter = sinon.createStubInstance(Router);
    mockActivatedRoute = sinon.createStubInstance(ActivatedRoute);

    addProviders([
      { provide: ActivatedRoute, useValue: mockActivatedRoute },
      { provide: Router, useValue: mockRouter },
      ExampleComponent
      // other providers
    ]);
  });

  beforeEach(inject([ExampleComponent], (component) => {
    exampleComponent = component;
  }));

  describe('#ngOnInit', () => {
    it('should ...', () => {
      mockActivatedRoute.snapshot = { params: { routeParam1: 'foo', routeParam2: 'bar' } };
      mockRouter.currentRouterState = { snapshot: { queryParams: { queryParam1: 'baz' } } };
      // do rest of setup here

      exampleComponent.ngOnInit();

      // do assertions here
    });
```

A caveat I found so far with this is that `Router#routerState` does not have a `set`, but internally just calls `Router#currentRouterState`. By setting `currentRouterState` you are able to pass whatever you need to the `routerState` variable. Of course, if you aren't using snapshots and instead using the Observable stream, you will need to modify the code to handle that scenario.

**Comment by DBSalvia** [comment]
@delasteve Thats awesome, thanks very much for the example.  I am indeed subscribing to the events stream within the Router, so will have a go at hooking into the mocked version tomorrow at work. Will post back a sample once I get something working, no doubt I'm not the only one having this problem. Once again thanks so much for the help, you've saved me a world of pain!

**Comment by delasteve** [comment]
@DBSalvia If you're doing the observable version, something like the following should work...

`mockRouter.currentRouterState = { params: Observable.of({ routeParam1: 'foo', routeParam2: 'bar' }) };`

**Comment by akirasosa** [comment]
I have introduced these two files into my project.

* https://github.com/springboot-angular2-tutorial/angular2-app/blob/master/src/shared/routes/mock-location-strategy.ts
* https://github.com/springboot-angular2-tutorial/angular2-app/blob/master/src/shared/routes/router-testing-providers.ts

And then, following code works for testing.
```ts
  beforeEach(() => addProviders([
    provideFakeRouter(TestComponent, [
      {path: 'home', component: BlankComponent},
    ]),
    ...APP_TEST_PROVIDERS,
  ]));
```

**Comment by bzums** [comment]
@akirasosa How is your strategy used to be ale to test a component which just uses the `routerLink` directive? Or is there any progress to make such components testable in a reasonable way?

**Comment by akirasosa** [comment]
@bzums 
> Or is there any progress to make such components testable in a reasonable way?

Yes, it can test any component which uses a routerLink.

> https://github.com/springboot-angular2-tutorial/angular2-app/blob/master/src/shared/routes/mock-location-strategy.ts

This is just a copy from https://github.com/angular/angular/blob/master/modules/%40angular/common/testing/mock_location_strategy.ts . Because it has been private at dcf7512, though I need it for testing still. The way to use only SpyLocation did not work for me. 

MockLocationStrategy just stores history state in memory instead of using a real browser's history. 

Anyway, this is just a workaround. The angular team will provide official way to test components using router soon.

**Comment by vsavkin** [comment]
Merged into master https://github.com/angular/angular/commit/72544ba55113a652b2452f2ce5bb0fca576a1344

**Comment by brachi-wernick** [comment]
works for me that way in angular2 final and router3 final:
I use `RouterTestingModule` from `@angular/router/testing`

here I declare dummy routes:
```
export const fake_routes: Routes = [
{path: 'home', component: MyComponent},
];
```

here I configure test module (because ngModule new feature)
 ```
TestBed.configureTestingModule({
               imports: [RouterTestingModule.withRoutes(fake_routes),
 }).compileComponents().then(() => {
 //do your test
}
```
