### ISSUE TITLE
Back/forward navigation doesn't work in Internet Explorer

### ISSUE THREAD

**Issue by robwormald** [angular/angular#9497]
_From @theodorejb on June 16, 2016 14:32_

Using IE 11, I can click links to navigate to routes, but when I click the browser's back button the template for the previous route loads, but not the content.

It seems like the `ngOnInit` method isn't being called when navigating back to a component. I can reproduce this in [the official Plunker demo app](http://plnkr.co/edit/ER0tf8fpGHZiuVWB7Q07?p=preview) using IE 11. Try clicking one of the heroes, then click the browser's back button. In Chrome/Firefox the list of heroes reappears, but in IE 11 the template is blank.

This bug is preventing our company from deploying an Angular 2 app since we need to support Internet Explorer.

_Copied from original issue: angular/vladivostok#64_

**Comment by robwormald** [comment]
_From @zoechi on June 16, 2016 14:42_

See also angular/angular#6867, angular/angular#4809

**Comment by vsavkin** [comment]
Fixed https://github.com/angular/angular/pull/10096
