### ISSUE TITLE
router-outlet on child route inside of conditional can't be found

### ISSUE THREAD

**Issue by robwormald** [angular/angular#9500]
_From @mattem on June 20, 2016 19:25_

When the `router-outlet` directive is inside a conditional (for example, `<div *ngIf="someExpression">`) on a child route, the router fails to find the primary outlet, causing the following error: 

> Error: Uncaught (in promise): Error: Cannot find primary outlet to load 'CrisisListComponent'

Here is a [plunkr](http://plnkr.co/edit/4P67k6REnHQKIA3D2ae3) showing the issue.

The AppComponent contains an outlet inside a conditional, but this is found and used correctly, but the outlet on the CrisisCenterComponent is not found.

Is this the expected behavior?

_Copied from original issue: angular/vladivostok#92_

**Comment by vsavkin** [comment]
Fixed: https://github.com/angular/angular/pull/9748

**Comment by mattem** [comment]
@vsavkin Thanks, is this now in a released version? Updating the plunkr to router version 3.0.0-beta.2 and angular 2.0.0-rc.4, it still seems not be finding the outlet within the `CrisisCenterComponent`. [Updated Plunkr](http://plnkr.co/edit/kuniIBjKpdD6mCb2Aq26?p=preview).

**Comment by allanmagale** [comment]
How do I apply this fix? Thanks in advance.

**Comment by bennadel** [comment]
Also is breaking for me in beta.2 as well.

**Comment by fernando-gl** [comment]
The only workaround i found is using [hidden]=" "

**Comment by bennadel** [comment]
I've been playing with the new Router for a few weeks now, and this is the biggest blocker for me. I'm going to play around with using a `resolve` instead of letting the component load its own data ... but this basically turns my mental model inside-out and makes if radically different to think about. 

Using `[hidden]` or something akin to that become problematic because then you need to have safe-navigation operators all over your template, `data?.prop`. 

Not sure if I'm the only one who feels like this is very problematic.

**Comment by fernando-gl** [comment]
@bennadel It is, maybe the solution is going back to old Router for now.

**Comment by fernando-gl** [comment]
Hello guys, i've found something that worked for me.

First solution: Using setTimeout trick.
```
import { Component, OnInit } from '@angular/core';
import { ROUTER_DIRECTIVES } from '@angular/router';

@Component({
  directives: [ROUTER_DIRECTIVES],
  template: `
  <h3>Parent template</h3>
  <div *ngIf="activeChildRoute">
    <h3>Child template</h3>
    <router-outlet></router-outlet>
  </div>
  `
})

export class AppComponent implements OnInit {
  activeChildRoute: boolean;

  constructor( ) { }

  ngOnInit() {
    console.log("AppComponent running");
    let self = this;
    this.activeChildRoute = true; //<---------- Creates DOM so router-outlet is found
    setTimeout(function() { //<---- Sets timeout to execute function just after view is loaded
         // more code...
         self.activeChildRoute = false; //<------ Now you can remove DOM that contains router-outlet
    }, 0); //<--------------------------- 0 miliseconds to timeout
  }

}
```

Second solution: Using ngAfterViewInit.
```
import { Component, OnInit } from '@angular/core';
import { ROUTER_DIRECTIVES } from '@angular/router';

@Component({
  directives: [ROUTER_DIRECTIVES],
  template: `
  <h3>Parent template</h3>
  <div *ngIf="activeChildRoute">
    <h3>Child template</h3>
    <router-outlet></router-outlet>
  </div>
  `
})

export class AppComponent implements OnInit {
  activeChildRoute: boolean;

  constructor( ) { }

  ngOnInit() {
    console.log("AppComponent running");
    this.activeChildRoute = true; //<---------- Creates DOM so router-outlet is found
  }

  ngAfterViewInit() { //<------ Runs after initializing the component's views and child views
    // more code...
    this.activeChildRoute = false; //<------ Now you can remove DOM that contains router-outlet
  }

}
```

Hope it helps someone. 😀

**Comment by MadUser** [comment]
+1
I am creating an expandable grid when every expansion has tabs(using routes).
I have been banging my head for hours to understand why I get this error message.
at least now I know :)

**Comment by frederikaalund** [comment]
This is still an issue in RC5. See [this plunk](http://plnkr.co/edit/2NBjX45NRUbKKwA8INxy).

**Comment by bennadel** [comment]
I just tried using the **ngRx Router** for this, and it works just as you would expect it to.

```html
<template [ngIf]="! isLoading">
    <route-view></route-view>
</template>
```

.... ah, the world makes sense again :) Would love to see this work in NG2 router eventually.

**Comment by elranu** [comment]
@bennadel what is ngRx Router? where I can find it?

**Comment by elranu** [comment]
Sorry I found it: https://github.com/ngrx/router but is not and the official angular router. The bug is still there on RC5 as @frederikaalund said.

**Comment by Apee** [comment]
+1 
None of the above worked for me, just switch to RC5 with the new router (3.0.0-rc.1) and still got this isssue unfixed. This is quite a major issue. If anyone has a workaround please let me know !

**Comment by hristokostov** [comment]
Also on just `<template><router-outlet></router-outlet></template>`.

In my case I use [Resolve](https://angular.io/docs/ts/latest/guide/router.html#!#resolve-guard) to preload needed data before activating a route so I could remove the `ngIf`. Sure that's not always possible or appropriate.

**Comment by elranu** [comment]
I fixed. But I found a strange bug. Is important the order of the ngIF.

First on @frederikaalund plunker's just add a new <div *ngIf="!test"> and it will work. I needs yes or yes to render the router-outlet

But if you enter to my plunker (http://plnkr.co/edit/hBXWb8Skv4KYExkg6r6X?p=preview) You will see that it does not work and get's a new error. Is like if the <ngIf> is complex  inside you get an error.
But if you put first the `<div *ngIf="!test">
      <router-outlet></router-outlet>
    </div>` it will work. Really strange.

**Comment by tlegutko** [comment]
If somebody uses Bootstrap v4, the workaround is to use responsive-utility `hidden-xs-up` / `hidden-xl-down` (that is always hidden, see: http://v4-alpha.getbootstrap.com/layout/responsive-utilities/) and then bind this css class based on some condition. Like this:

```
<div [class.hidden-xs-up]="awesomeTest">
    <router-outlet></router-outlet>
</div>
```

**Comment by firov** [comment]
Same issue with RC5 and "<router-outlet *ngIf...". This issue is closed, so can someone reopen it or create a new one?

**Comment by frederikaalund** [comment]
> This issue is closed, so can someone reopen it or create a new one?

I've created #11100.

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20781402/748d6e50-b7bd-11e6-8e91-48c358c3f76d.png)
