### ISSUE TITLE
rename RouterConfig => RouteConfig || Routes

### ISSUE THREAD

**Issue by robwormald** [angular/angular#9504]
_From @gdi2290 on June 21, 2016 5:16_

Route Config makes more sense than Router Config or even Routes

_Copied from original issue: angular/vladivostok#99_

**Comment by robwormald** [comment]
_From @laco0416 on June 21, 2016 10:25_

I like `Route[]` rather than any alias , it's simple.

**Comment by vsavkin** [comment]
1. Having an alias is useful as it allows to attach documentation to it. 
2. The reason why it is called RouterConfig and not Routes is that in the future we may add other things to the config that will affect the behavior of router service itself. 

@robwormald what do you think?

**Comment by gdi2290** [comment]
lets keep RouterConfig. you can close this
