### ISSUE TITLE
Does the new router support "virtual parents"?

### ISSUE THREAD

**Issue by spock123** [angular/angular#9506]
Hi, I'm struggling how to implement the following (using Router alpha.7):

My application uses the url structure to indicate language.
For example http://mysite.com/en/frontpage  is the English version, and so on.

Now, UI router have a smart feature called "virtual root", where you can say that the top level of the route is "virtual", meaning that navigation on the site would keep the same parent route.

For example: from '/en/frontpage', navigating to 'login', would lead to the url '/en/login'.

Is this possible with the new router?
Alternatively it's going to be a bit tricky doing route navigation around the application, because you have to keep track of the current language and insert this.

Of course, you could make a service that wrapped the router.navigate calls, and automagically insert the correct language, but before I wander into implementating something like that, I would like to hear if the router supports something like 'virtual root' structure.

How would you guys go about implementing the language as part of the url structure?

**Comment by robwormald** [comment]
Two parts to this:

We have a similar implementation called "componentless routes" - its currently on master but not yet released to NPM, that would allow you to do something like:
```js
{
  path: ':lang',
  children: [....]
}
```
Here's a demo of that (again, this is using the master build) https://plnkr.co/edit/DsaDhkuSqny0OO6n3aEt?p=preview

The second is relative routing, which is supported - see the plunk for that too.

**Comment by spock123** [comment]
Hi @robwormald , thank you for that info - I didn't realize that. 
This is great news, thanks a bunch!

I'll close the issue now. Thanks again.

**Comment by kamil-kielczewski** [comment]
I meet this requirement often when I make inner sysem for global companies:

For instance your client is BBA bank an has inner system for his workers which works on different countries. And for instance In that multilanguage system there is page which shows operations statistics for this bank customers. And your client want to have link to this page, depends on worker language (which he choose at registration step): 

EN: bba.com/dashboard/customers/123/operations/statistics, 
PL: bba.com/panel/klienci/123/operacje/statystyki, 
DE: bba.com/instrumententafel/kundschaft/123/betrieb/statistiken,

Do you know how to do it using "virtual parents" - bacouse I don't get it ?

**Comment by kamil-kielczewski** [comment]
answer is here #9550
