### ISSUE TITLE
Query Parameters example in document 

### ISSUE THREAD

**Issue by maxisam** [angular/angular#9507]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In document [ROUTING & NAVIGATION](https://angular.io/docs/ts/latest/guide/router.html#!#query-parameters)

if you run the example and click on Crisis Center > Dragon Burning Cities > hit "Save"

It doesn't highlight anything

**Expected/desired behavior**

 it should come back to Crisis Center and highlight "Dragon Burning Cities"

[Here](http://plnkr.co/edit/GZAD7mRVdgSBlOz1S8hc?p=preview) is my version of example

I changed this line in **app/crisis-center/crisis-detail.component.ts**

` this.router.navigate(['/crisis-center', {id: crisisId, foo: 'foo'}]);`

to 

` this.router.navigate(['/crisis-center'], {queryParams:{id: crisisId, foo: 'foo'}});`

and in **app/crisis-center/crisis-list.component.ts change**

`this.route.params.subscribe` to `this.router.routerState.queryParams` in 

Do I understand this correctly ? Since this section is talking about query parameters, I wonder we should use it instead of route parameter ? 

* **Angular version:** 2.0.0-rc.3

* **Browser:** Chrome 50

* **Language:** TypeScript 1.8

**Comment by zoechi** [comment]
Documentation issues are maintained in https://github.com/angular/angular.io
Would you mind reopening there and close here?

**Comment by maxisam** [comment]
Sure, however, I am wondering if it is a bug too. Because the way document used is route parameter, and it should work too right ? But it doesn't work.
