### ISSUE TITLE
Query string stick with routes

### ISSUE THREAD

**Issue by maxisam** [angular/angular#9508]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When you switching between page. Once the query string is attached, it stick with the route.

**Expected/desired behavior**

It shouldn't stick with the route if users switch to a different route.

**Reproduction of the problem**

[example](http://plnkr.co/edit/GZAD7mRVdgSBlOz1S8hc?p=preview)

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3

Route version 3.0.0 Alpha 7
 
* **Browser:** Chrome 50
 
* **Language:**  TypeScript 1.8

**Comment by briananderson1222** [comment]
I guess this is a differing of opinions about query params. I personally find it a very nice feature to have query parameters (which are considered to be global) persisted throughout an application. Maybe there should be an easier way of removing query parameters, but if you want to use parameters that shouldn't persist that is what route params should be used for.

**Comment by vsavkin** [comment]
The default url serializer treats query parameters as global, so they are not scoped to a particular route. That is why they persist. 

If you want to have parameters scoped to a particular route, you should use matrix parameters. Another option, would be to provide a different url serializer.

**Comment by maxisam** [comment]
matrix parameters ? so in the [example](https://angular.io/docs/ts/latest/guide/router.html#!#query-parameters), it seems like you can't get matrix parameters from route parameters.

<pre>
this.sub = this.route
      .params
      .subscribe(params => {
        this.selectedId = +params['id'];
        this.service.getCrises()
          .then(crises => this.crises = crises);
      });
</pre>

**Comment by djayfresh** [comment]
I was having this same issue. We redirect a user from another location into the angular app, and the initial URL has something like `http://localhost:8080/user-redirect?mapping=account&identity=882a541f-4d17-4793-8047-114bff38c52f`. Every time angular would pick up mapping and identity as query params, holding onto them as the user navigated the rest of the angular app. We don't need the user bookmarking their url's with the mapping and identity ;) 

Solution: 
Inside of our router service (wrapper).

       //Parameters
       var route: RouteInfo
       var params; //router params

       this.router.navigate(this.getRouterLink(route, params));

I updated the line to

       //Parameters
       var route: RouteInfo
       var params; //router params
       var queryParams; //queryParams

       this.router.navigate(this.getRouterLink(route, params), { queryParams: queryParams });

this way unless the user provided new query params, all routes should just wipe out the current query params. 

Hope this helps anyone with query params stuck in the url.
