### ISSUE TITLE
[Router, Blocked on Meteor] Bug when refreshing url with route

### ISSUE THREAD

**Issue by MiGu3X** [angular/angular#9509]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When I press F5, an error saying the route doesn't match is shown in the console
`directive_resolver.js:77 EXCEPTION: Error: Uncaught (in promise): Error: Cannot match any routes: 'dyixM8R89qSHwohbE'`

**Expected/desired behavior**
The page should load correctly

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
GIT repo: https://github.com/MiGu3X/realtime

**What is the expected behavior?**
The page should load correctly

**What is the motivation / use case for changing the behavior?**
To fix my issues

**Please tell us about your environment:** Im using a c9 workspace, it uses linux I think

* **Angular version:** 2.0.0-rc.1 
* **Router version:** 3.0.0-alpha.5
 
* **Browser:** Chrome
 
* **Language:** TypeScript

**Comment by zoechi** [comment]
`Router version: 3.0.0-alpha.5` is outdated current is `3.0.0-alpha.7`
If you still can reproduce please provide a Plunker. The repo you linked to doesn't look like a *minimal* example to reproduce.

**Comment by MiGu3X** [comment]
@zoechi 
I can't use the alpha.7 since angular-meteor uses @angular2.0.0-rc.1

**Comment by zoechi** [comment]
@MiGu3X then you should report the issue with angular-meteor ;-)
It shouldn't be too hard to create a minimal example without angular-meteor that allows to check if this is still an issue with the most recent router version.

**Comment by vsavkin** [comment]
@MiGu3X could you provide a plunker reproducing the issue using the latest release of the router?

**Comment by MiGu3X** [comment]
@vsavkin Using the latest release of the router requires me to use the latest release of angular2 which isn't compatible with latest angular-meteor version

**Comment by vsavkin** [comment]
Closing this issue. Please reopen it with a repro using the latest version of the router.
