### ISSUE TITLE
Sanitize svg attributes (e.g. xlink:href)

### ISSUE THREAD

**Issue by mprobst** [angular/angular#9510]
Angular's security schema currently defines no security contexts for SVG attributes. Some SVG attributes are security sensitive though, for example XLink hrefs in e.g. `<svg:circle xlink:href="...">`.

As I read the DOM schema, we might currently just not allow binding to those at all, but I haven't tested it.

**Comment by vicb** [comment]
@mprobst I think **most of** the svg properties are complex objects and it does not really makes sense to bind to them. Users would most frequently want to bind to attributes `[attr.x]=x`

**Comment by mprobst** [comment]
@vicb sorry, I'm using properties somewhat interchangeably with attributes here, for security purposes there isn't a big difference, AFAIK.

**Comment by vicb** [comment]
Please be careful next time, I like when my team mates are sharp :)

**Comment by steida** [comment]
Again? http://www.slideshare.net/x00mario/an-abusive-relationship-with-angularjs

**Comment by mprobst** [comment]
@steida not sure I get the reference; those slides are unrelated to SVG.
