### ISSUE TITLE
[animation] : Easing functions not working

### ISSUE THREAD

**Issue by dharders** [angular/angular#9517]
**I'm submitting a ...** 
```
[x] bug report
[ ] feature request
```

**Current behavior**

Specifying an easing in the animate() function has no effect on the animation.

i.e. These all animate the same visually

```
transition("* => void", [
   animate("1s", style({
      transform: "translateX( 100% )"
   }))
])
transition("* => void", [
   animate("1s ease-in", style({
      transform: "translateX( 100% )"
   }))
])
transition("* => void", [
   animate("1s cubic-bezier(0.6, -0.28, 0.735, 0.045)", style({
      transform: "translateX( 100% )"
   }))
])
```

**Expected/desired behavior**

I expect the specified easing function to change the visual appearance/timing of the animation.

**Reproduction of the problem**

[See this plunker](http://plnkr.co/edit/QR6WDzv6NxOmn6LXTngG?p=preview)

**What is the expected behavior?**

In the plunker, all 3 animations play exactly the same currently. I expect the 3 to be different (unless the default easing is one of the above when not specified)

**What is the motivation / use case for changing the behavior?**

Should work as advertised in the docs. (I haven't attempted keyframes yet... as easing should suffice)

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
 
* **Browser:** Chrome 51.0.2704.84 m
 
* **Language:** TypeScript 1.9.0-dev.20160409, plugin-typescript@4.0.10  (see plunker)

cc @matsko

**Comment by matsko** [comment]
Thank you @dharders for making the plnkr example easy to follow. The `easing` property was definitely missing for the web animations player: https://github.com/angular/angular/pull/9523/files#diff-39016ac7eb45114ac7f7781847e9644bR45
