### ISSUE TITLE
"_this.location.isCurrentPathEqualTo is not a function" Error while upgrading to router 3.0.0-alpha.7

### ISSUE THREAD

**Issue by vikas-trainee** [angular/angular#9525]
We are getting Following Error while upgrading to @angular/router ==> "**3.0.0-alpha.7**"

**EXCEPTION: Error: Uncaught (in promise): TypeError: _this.location.isCurrentPathEqualTo is not a function**

![error](https://cloud.githubusercontent.com/assets/17896790/16297328/04fed45e-394e-11e6-8aed-34d1f0fbffc5.png)

* **Angular version:** 2.0.0-rc.1

* **Language:** [ TypeScript ]

**Comment by ericmartinezr** [comment]
You should at least provide an plnkr, and also test it against RC.3

**Comment by vicb** [comment]
Please fill out the template when submitting an issue and provide a plunker. Thanks

**Comment by davidstellini** [comment]
For google/anyone else experiencing this error - it's because you are testing against an older angular2 version.

**Comment by akeating** [comment]
Make sure to carefully reconcile the angular dependencies listed in https://angular.io/docs/ts/latest/quickstart.html with your package.json file. I found I had a missing dep `@angular/forms` that was not required in rc1. It appears this (somewhat unhelpful) error message occurs when the target component is unable to be instantiated. In my case the target component used angular forms.

**Comment by Aarti15** [comment]
I have upgrated to RC.3 but still i am getting same error
Error: Uncaught (in promise): TypeError: _this.location.isCurrentPathEqualTo is not a function
Please let me know the solution
