### ISSUE TITLE
[router] Router doesn't en-/decode the URI components for params with the PathLocationStrategy

### ISSUE THREAD

**Issue by Tragetaschen** [angular/angular#9526]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have a route with a parameter: `path: 'a/:p'` and this parameter might contain space characters.
When my app is loaded and I navigate to that route via `['/a', 'with space']`, my component receives `activatedRoute.snapshot.params['p'] == 'with space'` and my browser's address bar shows `.../a/with%20space` in Edge or `.../a/with space` in Firefox.

When I now refresh my browser, the router navigates to the correct route, but my component receives `activatedRoute.snapshot.params['p'] == 'with%20space'`.

**Expected/desired behavior**

The latter should work like the first.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart]

**Comment by vicb** [comment]
Please fill out the template when you submit am issue.

Please add a plunker reproducing the issue. Thanks

**Comment by Tragetaschen** [comment]
I hate the current template. It's boilerplate after boilerplate, there is duplication in the required information (expected behavior), the list of browsers is not complete (Edge…) and it's a pain to read both in the browser and in particular in the GitHub subscription email.

I cannot get the router work in the plunker. Downloading the packages from npmcdn fails no matter what I try.

**Comment by Tragetaschen** [comment]
This is fixed in alpha.8

**Comment by Tragetaschen** [comment]
Nope, I forgot I quick-fixed the problem with `.replace('%20', ' ')` :-/

I tried to reproduce it in a plunker: http://plnkr.co/edit/4E6jptTSELgyEIJXiEZE?p=preview

However, the problem doesn't manifest with `HashLocationStrategy`, and trying to refresh the plunker in a separate window with `PathLocationStrategy` results in a HTTP 400 error, so I don't know what to do.

**Comment by Tragetaschen** [comment]
As far as I can see the problem is that there is no URI encoding / decoding done in the current implementation.

For encoding, `[routerLink]="['/R', 'foo/bar']"` should become in `/R/foo%2Fbar`, but instead becomes `/R/foo/bar` which when navigated to, doesn't match any registered route. On the way back from `window.location.pathname`, there is no decoding done and so for example `foo%20bar` doesn't become `foo bar`.

I tried to experiment with it and create a PR, but the current architecture isn't really fit for handling that:
The `LocationStrategy` abstracts the differences based on the full `location.pathname` and `location.hash`, but encoding/decoding needs to be done on a per-segment basis depending on the current strategy (no en-/decoding for hash, en-/decodeURIComponent for the pathname). There isn't really a place where this could be done...

**Comment by Tragetaschen** [comment]
See also #8695

**Comment by brandonroberts** [comment]
I agree that would be a necessary feature to have. Especially for passing things such as redirect URLs through routerLinks

**Comment by vsavkin** [comment]
Fixed here https://github.com/angular/angular/pull/9891
