### ISSUE TITLE
Adding new routes dynamically at runtime (extending routes configuration)

### ISSUE THREAD

**Issue by rychkog** [angular/angular#9527]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently we have predefined routes configuration that will be used in a bootstrapped application. And there is no way (at least I am not aware of it) to add new routes at runtime ('path/:some' pattern won't work in this case). 

**Expected/desired behavior**
It would be super useful to be able to add new routes at runtime through some kind of a service. By adding new routes I mean following:

Assume we have following configuration that describes our routes (code snippet is taken from http://victorsavkin.com/post/145672529346/angular-router)
```javascript
[
  {path: 'team/:id', component: TeamCmp, children: [
    {path: 'details', component: DetailsCmp},
    {path: 'help', component: HelpCmp, outlet: 'aux'}
  ]},
  {path: 'summary', component: SummaryCmp},
  {path: 'chat', component: ChatCmp, outlet: 'aux'}
]
```
Then I need to extend this configuration with a new route based on a state that was given to me from the server. And server says: "We need to have another route that brings us to some component and here it is:"
 ```javascript
{path: 'premiumChat', component: PremiumChatCmp}.
```

In order to extend I use some service that does the job - smth like ```RouteRegistrationService.registerNewRoute({path: 'premiumChat', component: PremiumChatCmp})```
And now whole application knows about newly added route and can navigate to it.

**Reproduction of the problem**

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**
Currently we are working on CMS application. Logical structure of application navigation is defined on the server and can be changed at any time, hence we cannot have routes configuration defined at bootstrap time it rather is being created at runtime based on server configuration and every change of navigation structure on the server should cause routes configuration to be extended.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
 
* **Browser:** [all] 
 
* **Language:** [TypeScript 1.8.7]

**Comment by ocombe** [comment]
I think that you can do it either with router.config (https://angular.io/docs/ts/latest/api/router-deprecated/index/Router-class.html) or with router.registry.config

Here is the desc of the router.config function:

`config(definitions: RouteDefinition[]) : Promise<any>`
Dynamically update the routing configuration and trigger a navigation.

**Usage**
```ts
router.config([
  { 'path': '/', 'component': IndexComp },
  { 'path': '/user/:id', 'component': UserComp },
]);
```

**Comment by rychkog** [comment]
Thanks a lot! - You've made my day :)

**Comment by lcurrens** [comment]
Does this answer apply only to the deprecated router, or to the new router?  We are needing the same capability to add routes dynamically, along with AsyncRouter to be able to lazy load components.  The idea would be for allowing for plugins to be dynamically added, both their routes and their components.  Any pointers as to the best way to accomplish this will be helpful.

**Comment by vicb** [comment]
Could this be closed ?

**Comment by shlomiassaf** [comment]
@ocombe This refers to 3.0 right? I think this approach is not trivial and unsafe.

The router config is private, this means one will have to save a reference throughout the application, this is a pointless complexity, we can live with it... but if @vsavkin can confirm that the router supports live registration we can also add this option to the api, this is the best approach.

As for **unsafe**: the config array is registered upon calling `provideRouter(...)`, we don't have access to it so we need to call 'provideRouter' again because we're not sure what it does. Yes we can look at the source code but there's no promise it won't change and the actual array doesn't go through some transformation step... 

Now it's just `    {provide: ROUTER_CONFIG, useValue: _config}`, yep, no harm but since it's private we can't relay on that.

This is a big feature, it allows for example a linking system set by a database etc...
It should be officially supported or not... and if yes it needs an API, mabye an **addRoute, removeRoute** or exposing a **copy** of the config array for reuse.

**Comment by wuhkuh** [comment]
I don't like to see this closed anytime soon, @vicb . 

I am trying to implement the same thing on my own website and I only found out through this feature request that there is no current implementation of dynamic routing. I am willing to code such feature myself, but it requires some certainty that the current router will be the definite one - as we have had several deprecated versions until now.

@shlomiassaf I am not sure if I understand what you're trying to say here:
>  we don't have access to it (route config array) so we need to call provideRouter again because we're not sure what it does - this will not work since it returns something else...

I am interpreting this as
> The route config array is private and we're unable to access it from the outside.

But why would we need to call provideRouter again as we have no way to access the route config array anyway?

**Comment by shlomiassaf** [comment]
What i'm saying is that we don't know what `provideRouter()` does, we can't relay on it's current implementation as it might change. This means it might do something to the routes.

As for the design, I think it should be managed by the router using an API for add/remove.

It adds complexity and confusion when you `extend` a route.

**Comment by unsafecode** [comment]
Is there any chance to have a working sample? Right now I can't make it running with router.resetConfig

Indeed, I definitely support the idea that dynamic routing must be something built-in and properly documented.

**Comment by zoechi** [comment]
This should do what you want
```
router.resetConfig([
 { path: 'team/:id', component: TeamCmp, children: [
   { path: 'simple', component: SimpleCmp },
   { path: 'user/:name', component: UserCmp }
 ] }
]);
```

**Comment by unsafecode** [comment]
@zoechi Is this the only operation to perform? The new route is still not reachable afterwards, but I don't get any exception.

**Comment by zoechi** [comment]
@unsafecode I haven't used this myself yet, I just saw that it was used in the router unit tests.

**Comment by lcurrens** [comment]
@zoechi  this would overwrite all existing routes?  It would be better to be able to add a new route without replacing all other existing routes.

**Comment by zoechi** [comment]
You can keep the routes around and add/remove on demand than then just pass these routes to `router.resetConfig(routes)` again. This is much easier and much more powerful than to add an API to the router to add/remove/modify single routes.

**Comment by lcurrens** [comment]
Is AsyncRoute coming back?  If so then we could dynamically add AsyncRoute using the resetConfig() method described above, and then use lazy loading to load components, so that we can dynamically add components at runtime, correct?

**Comment by zoechi** [comment]
I saw it mentiond that proper lazy loading support will take a while to land but it's definitely planned.

**Comment by vsavkin** [comment]
There are two ways to extend the router configuration:

# Fully "safe" and easy to use. Used for lazy loading

```
{
  path: 'admin',
  loadChildren: 'admin-bundle-file-name'
}
```

When navigating to `admin/blah`, the router will fetch `admin-bundle-file-name`, will extract the configuration, and, finally, will merge it with the main one. This feature has been merged into master a couple of weeks ago and will be released next week.

# Imperative

```
router.resetConfig(someConfig)
```

In this case you, as as developer, are responsible for making sure that the you don't screw up the configuration.

We were considering having something in between, where you can add/remove sections, but at the moment decided against it. You can implement this functionality yourself on top of resetConfig.

Closing this issue.

**Comment by teone** [comment]
I'm confused,
if I do `router.resetConfig(routes)`, in my RootComponent `ngOnInit()` method it looks to work:
```
ngOnInit() {
    this.router.config.push(
      {
        path: 'core',
        component: MyComponent
      }
    );
    this.router.resetConfig(this.router.config);
}
```
as long as you add `MyComponent` to `entryComponents`  in the `@ngModule` declaration.

I was trying to load routes from a REST API and add them:
```
this.coreService.getCoreEndpoints()
      .subscribe(
        (endpoints) => {
          _.forEach(Object.keys(endpoints), (e: string) => {
            this.router.config.push({
              path: `core/${e}`,
              data: {
                name: e
              },
              component: MyComponent
            });
          });
          this.router.resetConfig(this.router.config);
        }
      );
```
And in this case any time I try to navigate to one of that routes I get the error:
```
EXCEPTION: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'core/networks'
Error: Cannot match any routes. URL Segment: 'core/networks'
```
Any idea of the possible reason? Is there a fix?
Thanks

**Comment by Sri276286** [comment]
I don't think routes is getting updated in RouterModule.forRoot(routes) .

**Comment by Sri276286** [comment]
@rychkog @ocombe @lcurrens @vicb @shlomiassaf 

Could someone pls help me on "How I can handle this with latest angular2 version"

**Comment by ocombe** [comment]
Just lazy load a module that imports `RouterModule.forChild(routes)` (notice the `forChild` and not `forRoot` here)

**Comment by Dok11** [comment]
I have same trouble. After use `router.resetConfig()` with rules:
```ts
[{
	path: ':sectionCode',
	component: PageCatalogSectionComponent,
}, {
	path: ':sectionCode/products',
	component: PageCatalogSectionProductsComponent,
}, {
	path: '**',
	component: PageNotFoundComponent,
}];
```

I got error in url `/mysection/products1`:

```
ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'mysection/products1'
Error: Cannot match any routes. URL Segment: 'mysection/products1'
```

And I have not idea what I can change..

**Comment by benjamindamm** [comment]
> I'm confused,
> if I do `router.resetConfig(routes)`, in my RootComponent `ngOnInit()` method it looks to work:
> 
> ```
> ngOnInit() {
>     this.router.config.push(
>       {
>         path: 'core',
>         component: MyComponent
>       }
>     );
>     this.router.resetConfig(this.router.config);
> }
> ```
> 
> as long as you add `MyComponent` to `entryComponents` in the `@ngModule` declaration.
> 
> I was trying to load routes from a REST API and add them:
> 
> ```
> this.coreService.getCoreEndpoints()
>       .subscribe(
>         (endpoints) => {
>           _.forEach(Object.keys(endpoints), (e: string) => {
>             this.router.config.push({
>               path: `core/${e}`,
>               data: {
>                 name: e
>               },
>               component: MyComponent
>             });
>           });
>           this.router.resetConfig(this.router.config);
>         }
>       );
> ```
> 
> And in this case any time I try to navigate to one of that routes I get the error:
> 
> ```
> EXCEPTION: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'core/networks'
> Error: Cannot match any routes. URL Segment: 'core/networks'
> ```
> 
> Any idea of the possible reason? Is there a fix?
> Thanks

How do you fixed this problem. Now is 2019 and I use Angular7. I'm facing the same problem.
