### ISSUE TITLE
rc3/SystemJS/ES6: missing reflect-metadata when using @angular/http

### ISSUE THREAD

**Issue by micaelmbagira** [angular/angular#9528]
**I'm submitting a ...** 
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The app is using JavaScript **ES6**, SystemJS and the latest version of Angular (rc3). When I run the app with browsersync, it works. But if I bundle the app and then run it, I have this error in the browser console `Uncaught reflect-metadata shim is required when using class decorators`. Then if I run the app again **without** bundling, it does not work anymore.

**Reproduction of the problem**
You can easily reproduce the problem by cloning this app https://github.com/micaelmbagira/angular-issue-reflect. If you remove the `import {Http, HTTP_PROVIDERS} from '@angular/http' ; ` it works.

Plus, it does not happen with TypeScript but it does with JS ES5 and ES6. Also it doesn't happen with Webpack.

**Please tell us about your environment:**

Chrome, OS X

* **Angular version:** 2.0.0-rc.3
 
* **Browser:** [Chrome, Safari] 
 
* **Language:** [ES6, ES5]

**Comment by vicb** [comment]
Closing as it sounds like a support request.

When creating an issue please mention all the steps to reproduce.

**Comment by micaelmbagira** [comment]
It's suggested in the issue template to reproduce the issue with a plunkr or something like that. I made a simple web app easy to reproduce and referenced the url.
