### ISSUE TITLE
rxjs beta dependency update

### ISSUE THREAD

**Issue by tiagoroldao** [angular/angular#9529]
There may be a reason I'm unaware of for continuing to depend on `rxjs5.0.0-beta.6`, if so please close this.

ngrx is now on beta 9, with a host of bug fixes that can and do affect development in some particular cases. Can it be investigated wether angular can depend on the latest beta?

**Comment by ulrikaugustsson** [comment]
It seems to work in my toy application.

**Comment by robwormald** [comment]
Yep, its in progress, but it's going to add some complexity to our end (specifically bringing in the new symbol-observable polyfill) so it needs to be documented and such.

see #9549
