### ISSUE TITLE
Change detection stops working after uncaught exception occurs during the binding evaluation in prod mode

### ISSUE THREAD

**Issue by borisvasilenko** [angular/angular#9531]
**I'm submitting a ...** 

```
[X] bug report
[ ] feature request
```

**Current behavior**

In prod mode, change detection stops working after uncaught exception occurs during the binding evaluation.

Details:
the subscription to zone.onMicrotaskEmpty event, which is established in angular/core/application_ref is being unsubscribed automatically by RxJS (at SafeSubscriber.__tryOrUnsub), when uncaught exception occurs during the binding evaluation, and currently there s no way to recover from uncaught exception during the binding evaluation in prod mode.

**Expected/desired behavior**

In prod mode, change detection should continue to function properly after uncaught exception during the binding evaluation.

**Reproduction of the problem**

http://plnkr.co/edit/2fe6GC6NkuFkffpEoDPZ?p=preview

**What is the motivation / use case for changing the behavior?**

In our project, which previously used angular beta 9, we've built custom error handling (by subsclassing ExceptionHandler). 
When in prod mode, the error was displayed in a popup on the current page, with 'Report' button, and other stuff. 
After upgrading the project to RC1, we're unable to display the popup on the current page after the uncaught error has occurred.

There should be some ability to recover from an uncaught exception.

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.1 - 2.0.0-rc.3
- **Browser:** all
- **Language:** all

**Comment by vicb** [comment]
Could you please try with RC.3and report the status. Thanks.

**Comment by borisvasilenko** [comment]
Sure, I've just reproduced the issue on a fork of angular/quickstart, which uses RC3.
https://github.com/borisvasilenko/quickstart/commit/479262306c075ce5c4ea77bb9c623c45727441a1

**Comment by bennadel** [comment]
I just ran into this issue as well, using the latest `@angular` package.

**Comment by Fossaluffagus** [comment]
Still the same on 2.0.x

This is a problem when a template expression causes the exception, because there is no real way to catch it (as far as I know).

https://plnkr.co/edit/T1JccPu4ctADmM6f1sPa

I understand that in a lot of cases this would be due to the code not being defensive enough, but nobody wants to rely upon ultra defensive coding. I think the use case from the OP is absolutely valid.

**Comment by islamshaheen** [comment]
Hi,
Any updates regarding this issue?

**Comment by DzmitryShylovich** [comment]
still valid in v4 http://plnkr.co/edit/xLKtGztrJjqkDdwN6G6Z?p=preview

**Comment by alexemmons** [comment]
I would also like a solution or workaround for this. I am also trying to implement a custom ErrorHandler. I can catch the error and get the information that I need from it, but then I want to display a dynamic message to the user, and I can't get my view to update.

**Comment by tbosch** [comment]
Updated plunker for v4: https://plnkr.co/edit/ndpMrdpVi62qK2qTbTz7?p=preview

**Comment by ganeshkantu** [comment]
@matsko which version is this fix in? I can still reproduce in 4.1.0

**Comment by cur3n4** [comment]
I have the feeling this is causing an infinite loop when there is an error in the template. As the tick function is called over and over again.

**Comment by zoechi** [comment]
@cur

**Comment by cur3n4** [comment]
@zoechi Agreed. But, as default behaviour, ending up in an infinite loop because of an error in a template doesn't seem like a great idea.

**Comment by zoechi** [comment]
@cur3n4 then don't do it. What is Angular supposed to do when change detection causes an exception, you catch it and run change detection again? It's your custom code that causes the infinite loop.

**Comment by brian428** [comment]
I think I'm running into the same problem, and it's really annoying. In dev mode, if I'm working and try loading a page, if there's an error while a view is being created (such as a bound variable doesn't exist in the component), Angular just goes into an infinite error loop. I have to literally kill the browser process to stop it.

This didn't used to happen. If you're going to maintain this new behavior, how about adding some max consecutive error threshold so at least it doesn't completely hang the browser?

**Comment by zoechi** [comment]
You could maintain a counter in your code and only call `ApplicationRef.tick()` when the counter is `0` and increase/decrease before/after the call to `ApplicationRef.tick()`.

**Comment by brian428** [comment]
I'm not calling tick(), or anything else. Are you saying you think I *should* be manually calling tick()? 

I've just got a basic component, and a basic template. If the template tries to bind to a component property that doesn't exist, I get an infinite loop. I'll attach a screenshot.

This just started happening, and I don't see how this could possibly be expected or desired behavior?

![change detection error loop](https://cloud.githubusercontent.com/assets/140338/26419678/7d6dd12c-408e-11e7-9ac3-661f2e97e955.png)

**Comment by zoechi** [comment]
@brian428 I thought you were referring to the problem @cur3n4 explained.
I'd suggest you either create a new issue with proper filled out issue template and a Plunker that allows to reproduce or use one of the support channels

[CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by ganeshkantu** [comment]
@zoechi I see a lot of PRs fixing this issue above. What version did those PRs go in? It might simply be that we are using an older version of Ng4.

**Comment by zoechi** [comment]
@ganeshkantu 4.2.0-beta.0 https://github.com/angular/angular/blob/master/CHANGELOG.md#420-beta0-2017-05-04

**Comment by ganeshkantu** [comment]
@zoechi Thanks! I will switch to that and test.

**Comment by cur3n4** [comment]
Here is a Plunker which reproduces the issue: https://plnkr.co/edit/7HgeqiuJ0Wu6siIxmlVg?p=preview
As a wild guess it might be related to the handler executing code which doesn't happen in the current tick (setTimeout, http promise, etc).

**Comment by brian428** [comment]
This is very close to what I'm seeing, with a very similar stack trace (though the Plunker isn't hanging my browser which is what happens in my own app). I'm not doing anything that uses setTimeout(), etc., but I suppose it's possible that one of my dependencies could be (PrimeNG, etc.).

Regardless, I hope a solution can be found. Again, things worked fine until recently (which is why I assume it was this introduced in 4.1.1).

**Comment by cur3n4** [comment]
I just realised that setTimeout will trigger change detection. 
So the solution is probably to run it with runOutsideAngular. Updated plunker: https://plnkr.co/edit/76MUrCEYZtu29lIVihz7?p=preview

**Comment by cur3n4** [comment]
@brian428 It is probably something similar, something must be triggering a change detection in your handler

**Comment by zoechi** [comment]
I deleted my above comments because I somehow misinterpreted what the issue was.
Sorry for the confusion.
I'd suggest to create a new issue. 
Comments on closed issues are, at least officially, ignored.
