### ISSUE TITLE
Content-Type is not applying on POST Calls

### ISSUE THREAD

**Issue by zeeshanjan82** [angular/angular#9532]
I am trying to make a post call with the below code:

```js
 let body = JSON.stringify({ token: "e0ca32918167121e7db0086400ee2ebaec64e7cfefaf0e6d4a501e89dc1ace8c" });
  let headers = new Headers();
  headers.append("Content-Type", "application/x-www-form-urlencoded") //******
  let options = new RequestOptions({ headers: headers });
  return this.http.post('http://api.that.com/register/verify', body, options)
             .toPromise()
             .then(this.extractData)
             .catch(this.handleError);
```
after I run the above code I get 404 error but when I look into the network tab of chrome developer tools I see that the content-type is passed as 'text/html' instead of 'application/x-www-form-urlencoded'

I am using angular2-rc3

![error](https://cloud.githubusercontent.com/assets/8342604/16306103/38d2c548-397a-11e6-97ec-2d8e16f28712.png)

**Comment by vicb** [comment]
Please provide a plunker.

**Comment by zeeshanjan82** [comment]
http://plnkr.co/edit/AyMyrc8yXynU2A7T90y5?p=preview  In this plunkr you can see in the network tab we are having content-type as text

**Comment by vicb** [comment]
Upgrade to RC3, thanks.
your plunkr uses: `https://code.angularjs.org/2.0.0-alpha.45/angular2.min.js`
