### ISSUE TITLE
angular 2-in-memory-web-api requires rc2

### ISSUE THREAD

**Issue by Cyberdada** [angular/angular#9533]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When upgrading to RC 3 
"angular2-in-memory-web-api": "0.0.12" package is still reliant on 
@angular/core@2.0.0-rc.2 and  @angular/http@2.0.0-rc.2

**Expected/desired behavior**
latest angular2-in-memory-web-api should not be dependant on @angular/core@2.0.0-rc.2 and  @angular/http@2.0.0-rc.2

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

Just run an npm install on the package.json included in quickstart and you will see this.

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**
It's irritating :) 

**Please tell us about your environment:**
Irrelevant
* **Angular version:** 2.0.0-rc.3
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 All (irellevant for this case) 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart] 
Typescript (irrelevant)

**Comment by vicb** [comment]
angular2-in-memory-web-ap is not part of this repo.Please re-open on that project.
