### ISSUE TITLE
Observable subscription bleeds css and breaks router

### ISSUE THREAD

**Issue by ndcunningham** [angular/angular#9535]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently, I have a nav bar that shows and hides links based on authenticated status.
Additionally, Those links has style to highlight which route is active.

What is happening is when i subscribe to my observable using the async pipe, it breaks. Even though i return a boolean value from my observable.

If i say explicitly `*ngIf="true"` it works fine.

I isolated everything down to this. My routes (the ones which are broken) redirect to home. Additionally, The same routes all have the active style regardless of url.

**Expected/desired behavior**
- Router should not to break and redirect to home or any other page than intended
- Style should not be leaked into any other link or element other than specified 
- async to resolve properly since `*ngIf="true"` works.

**Reproduction of the problem**
You can see the problem here: http://plnkr.co/edit/XACtF1

Protected Page works with Guard
but Parent/Child Protected Page does not and the style bleeds into Login

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
* **Router Version:** RC3 - alpha 7
 
* **Browser:** [all | Chrome 51
 
* **Language:** [all | TypeScript 1.8

**Comment by DzmitryShylovich** [comment]
Not only with observable. Same behavior with boolean flag.
http://plnkr.co/edit/FYsRMUFvqb89wesLex4L?p=preview

Looks like combination of routerLinkActive and routerLink directives on the same element causes this behavior. 
Element with routerLinkActive but without routerLink works fine.

**Comment by YRathod** [comment]
By using [hidden]="!auth.loggedIn" instead of  *ngIf="(auth.check() | async)", i'm able to get the expected behavior.
http://plnkr.co/edit/8gPsxL8OD3kns6o1Xoju?p=preview

**Comment by ndcunningham** [comment]
> By using [hidden]="!auth.loggedIn" instead of *ngIf="(auth.check() | async)", i'm able to get the expected behavior.

True but if you have classes that change the display this does not work so well. 

I saw it working on your plunk but failed in my project because it was being overridden 

![2016-06-27 09_28_58-program manager](https://cloud.githubusercontent.com/assets/338948/16381291/d8d75d8e-3c49-11e6-98ea-387072b76c0e.png)

Also there was an issue for the same problem: 
http://stackoverflow.com/questions/30744882/angular2-hidden-ignores

which links also to https://github.com/angular/angular/issues/506

Though it was closed the issue remains as far as i experienced.

**Comment by YRathod** [comment]
Customizing css for hidden attribute might stop the overriding

[hidden] {
  display: none !important;
}

I'm not sure whether it works in your project code but worth to give a try.

**Comment by ndcunningham** [comment]
I saw this on the same [StackOverFlow Link](http://stackoverflow.com/questions/30744882/angular2-hidden-ignores) that had the code you illustrated.

the `!important;` will stop the overriding.

Still leaving the issue open since the root issue is *ngIf and router.
I already saw a PR for the change https://github.com/angular/angular/pull/9603

**Comment by ndcunningham** [comment]
Fixed with https://github.com/angular/angular/pull/9603/commits
