### ISSUE TITLE
import directory case can break injector

### ISSUE THREAD

**Issue by mswehli** [angular/angular#9539]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using dependency injection, if you use a different case for the directory from which to import a service from in a child component than you did in the parent component, the injector will not recognize this as the same component and break.

e.g.:
If i were to use the following import statement in the root:
import {ExampleService} from './Services/example.service';

and the following in the child:
import {ExampleService} from './services/example.service';

where the only difference is the capitalization of the S in Services, the injector would throw an error stating there is no provider for ExampleService. It would still load in the root component regardless of how it is spelt however.

**Expected/desired behavior**
That the provider would recognize they are the same component and inject it correctly. Alternatively an error saying the case is incorrect when importing a class would be useful.

**Reproduction of the problem**

Simple change any of the letters in the import statement of a service from lower case to uppercase or vice versa.

**What is the motivation / use case for changing the behavior?**

Would save a lot of time debugging as no error is displayed.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.2
 
* **Browser:** [all | Chrome 51.0.2704.103 | Firefox 49.0a2 | IE Edge] 
 
* **Language:** [TypeScript X.X ]

**Comment by ericmartinezr** [comment]
What TS version are you using? This is not an angular issue, it's most likely a TS one https://github.com/Microsoft/TypeScript/issues/4719

**Comment by IgorMinar** [comment]
yeah. this is a TS issue. thanks @ericmartinezr
