### ISSUE TITLE
`ngc` is broken in RC3

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#9540]
Reported in https://github.com/angular/angular/pull/9537#issue-161959892

> There is signature mismatch between tsc-wrapped (v0.1.0) collector.js#getMetadata and compiler-cli reflector_host.js#getMetadataFor that caused an error anytime ngc was executed. The error received was as follows.

> `TypeError: Cannot read property 'getSymbolsInScope' of undefined`

> After forcing NPM to install @angular/tsc-wrapped@latest the error was resolved.

**Comment by vicb** [comment]
@alexeagle I htink there is a pending PR to fix that

**Comment by alexeagle** [comment]
I guess we don't have a way to push this fix other than waiting for RC4?
