### ISSUE TITLE
Angular 2RC3 JSONP.get add current url to url in param

### ISSUE THREAD

**Issue by jaroslawziolkowski** [angular/angular#9546]
When I try call to http addres by JSONP.get unfortunately system use
my local address and next url from parameter

for example 
when my url in argument is 
`http://localhost:3004/foo`

angular call to

`http://localhost:3000/http://localhost:3004/foo`

My code is:

```
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs/Observable';
import { HTTP_PROVIDERS, Http, Response, Jsonp, JSONP_PROVIDERS } from '@angular/http';

@Injectable()
export class UserService{
    constructor(public http: Http, public jsonp: Jsonp){
    }

    getUser(){
        this.jsonp.request('http//localhost:3004/user/check').subscribe((res: Response) => {
           console.log(res.json());
        });
    }
}


```
**My Environment:**

* **Angular version:** 2.0.0-rc.3
 
* **Browser:** [all] 
 
* **Language:** [TypeScript] 

* **OS:** OS X 10.11.5
* **Node:** 6.2.0
* **npm:** 3.8.9

**Comment by shlomiassaf** [comment]
In your code the address you point to is `http//localhost:3004/user/check`

you're missing a `:` after the `http`

BTW, I think the best place for support questions is https://gitter.im/angular/angular
You will get fast response and it will not clutter the issues. (the issues is the place for bugs/features etc..)

**Comment by vicb** [comment]
Re-open (with a plunker) if still an issue

**Comment by shlomiassaf** [comment]
@vicb It might be beneficial to add generic auto replay issue comment with some information about where to get support.

something like
>"if you need to ask a quick question or get direction, try gitter chat. If you have a more in dept issue we suggest stackoverflow (or groups?)"

maybe with some links (plunker, gitter, stackoverflow+tags)
