### ISSUE TITLE
MockBackend missing from rc umd bundles

### ISSUE THREAD

**Issue by b-r-i-a-n** [angular/angular#9557]
**I'm submitting a ...**  

[X] bug report
`
**Current behavior**
http/testing/mock_backend.js (MockBackend) not found when using bundles and ES5. Can't switch to rc until included.

**Expected/desired behavior**
MockBackend included in testing.umd.js bundle for mocking http requests when using bundles and ES5.

**Reproduction of the problem**
MockBackend missing from bundles.

**What is the expected behavior?**
MockBackend included in bundles.

**What is the motivation / use case for changing the behavior?**
Allow ES5 bundle users to test using a mocked backend.

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.3
- **Browser:** [all ]
- **Language:** [ES5]

**Comment by DzmitryShylovich** [comment]
@b-r-i-a-n is this still an issue after final?

**Comment by b-r-i-a-n** [comment]
No, the testing bundles that are now included took care of many of the ES5 testing issues including this one.
