### ISSUE TITLE
InvalidCharacterError with special character in attribute name

### ISSUE THREAD

**Issue by wkwiatek** [angular/angular#9566]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Creating input name for a component like `test$` or `something@` will produce error: 

```
InvalidCharacterError: Failed to execute 'setAttribute' on 'Element': 'ng-reflect-test$' is not a valid attribute name
```

**Reproduction of the problem**
http://plnkr.co/edit/p4AOGZsrmXgStWa9eDtf?p=preview

**What is the expected behavior?**
Valid JS name should also be a valid name in template. 

**Please tell us about your environment:**
Mac OS X 10.11.5
- **Angular version:** 2.0.0-rc.3
- **Browser:** all
- **Language:** TypeScript 1.8.10

**Comment by vicb** [comment]
> Valid JS name should also be a valid name in template.

Well not exactly.... JS and HTML both have spec that tell you what is a valid name or name.

That being said, you are right for this particular case `x-y$` is a valid html [attribute name](https://www.w3.org/TR/html5/syntax.html#attributes-0)

"Failed to execute 'setAttribute' on 'Element': 'ng-reflect-test$' is not a valid attribute name" is your browser complaining, not angular. Which means that the bug is in your browser.

We will have to workaround this browser bug in Angular. Thanks for your report.

**Comment by wkwiatek** [comment]
Maybe it's more like a wish but I think that having own html parser (which supports e.g. camelCase) could also make possible to put JS names as inputs.

Thanks!

**Comment by vicb** [comment]
1) Our parser is (almost) HTML compliant,
2) Once again this is not the problem here angular works just fine, see "the bug is in your browser." in my former response.

A workaround could be to set `logBindingUpdate` to `false` in the `CompiilerConfig`. (it is only true in dev mode by default).

**Comment by wkwiatek** [comment]
Sure. Thanks!

**Comment by vicb** [comment]
We need to sanitize the name so that all browsers are happy

**Comment by benwhite-deltas** [comment]
Can I take this one? My current line of thinking is that some form of reversible escaping will be necessary so there won't be conflicts between components with/without the special characters.

**Comment by miller-time** [comment]
When you provide an alternative binding string, such as `@Input('test') test$`, could the reflect attribute use the alias instead of the property? (i.e. "ng-reflect-test" instead of "ng-reflect-test$")

**Comment by maartentibau** [comment]
Any news on whether or not this issue will be fixed? Or will this just be not an option as for HTML sanitation reasons?
