### ISSUE TITLE
Router 3.0.0 alpha 7 -routing between children

### ISSUE THREAD

**Issue by spaeth21** [angular/angular#9569]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently whenever I route from a path that has a child route to another route that has a child route it throws a _routeConfig of null error. If I'm not in a route that has children routes, and I navigate to a route with children it works fine. It only throws this error if I go between two routes that have children routes.
![image](https://cloud.githubusercontent.com/assets/9081598/16338456/d56e15cc-39ea-11e6-8ac6-b406913ef280.png)

**Expected/desired behavior**

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart]

**Comment by brandonroberts** [comment]
This issue has already been fixed in master and will be in the next release.

**Comment by MaximilianWiedemann** [comment]
As a workaround and until next release, you can apply this fix (https://github.com/angular/vladivostok/pull/76/files) yourself in the router.js file.

**Comment by brandonroberts** [comment]
You can also use the incremental builds which are updated on successful builds from master

```
npm install angular/router-builds
```

**Comment by spaeth21** [comment]
Thanks for letting me know so quickly.
