### ISSUE TITLE
Router 3.0.0 Nested queryParams on page links.

### ISSUE THREAD

**Issue by Gamblt** [angular/angular#9573]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Current behavior**
If page path has query params - it's has been passed to all links on the page

**Expected/desired behavior**
Links on page without parent query params.

**Reproduction of the problem**
http://plnkr.co/edit/eijAs0?p=preview
1) Link to "Heroes" page has query params
2) All HeroesDetails links has the same params but they don't! They passed only a fragment.

**Please tell us about your environment:**
* **Angular version:** 2.0.0-rc.3

**Comment by vsavkin** [comment]
Query params are meant to be global and shared, and thus persist. 

You can think that they are above the root url segment. Basically, the router link attribute changes only the pathname part of the url. If you want to reset queryParams or fragment, you need to do explicitly by using the queryParams and fragment attributes:

```
<a routerLink="/boo" [queryParams]="newQueryParams" [fragment]="fragment"></a>
```

**Comment by slubowsky** [comment]
This is not very developer friendly.
Consider this very common use case,
User navigates to my application via saved bookmark that includes query params. e.g. http://localhost:4200/myapp/detail?id=77
they then get a page that include ?id=77 on all router links.
Another user starts the app with no query params and eventually navigates to the exact same page: http://localhost:4200/myapp/detail?id=77. This time the links do not have ?id=77 appended to them.
Very unintuitive and surprising behavior for the developer. I would expect router links to behave the same in both cases.

**Comment by liuxue0905** [comment]
````
<a routerLink="/boo" [queryParams]="newQueryParams" [fragment]="fragment"></a>
````
event this way, can not override queryParams all the time
