### ISSUE TITLE
Type 'Control' is not assignable to type 'typeof Control'.

### ISSUE THREAD

**Issue by AlexCollin** [angular/angular#9574]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
This code
```
constructor(private router: Router) {
        this.form.email = new Control('', Validators.compose([
            Validators.required,
            ValidationService.emailValidator
        ]));
        this.form.password = new Control('', Validators.required);
        this.authLoginForm = new ControlGroup(this.form);

}
```
gives these errors

> client/imports/auth/login/login.ts (25, 9): Type 'Control' is not assignable to type 'typeof Control'.
> Property 'prototype' is missing in type 'Control'.
> client/imports/auth/login/login.ts (29, 9): Type 'Control' is not assignable to type 'typeof Control'.
> client/imports/auth/login/login.ts (30, 47): Argument of type '{ email: typeof Control; password: typeof Control; }' is not assignable to parameter of type '{ [key: string]: AbstractControl; }'.
> Index signature is missing in type '{ email: typeof Control; password: typeof Control; }'.
> 

* **Angular version:** 2.0.0-rc.1
 
* **Browser:** Safari 9.1.1
 
* **Language:** TypeScript

**Comment by vicb** [comment]
Please fill out the issue template when submitting a ticket. Make sure you use the latest RC/from.
Thanks !
