### ISSUE TITLE
no class is set to the active routerLink in Router 3.0-alpha.7

### ISSUE THREAD

**Issue by sfabriece** [angular/angular#9575]
With router-deprecated a class was set to the routerlink to indicate that it was active.

with Router 3.0-alpha.7, no class is set.

Is this the expected behavior?

**Comment by ericmartinezr** [comment]
v3 router has a [`routerLinkActive`](https://github.com/angular/angular/blob/master/modules/@angular/router/src/directives/router_link_active.ts) directive that may help you, here's an example https://github.com/angular/angular/blob/master/modules/playground/src/routing/app/inbox-app.html

**Comment by sfabriece** [comment]
Thanks @ericmartinezr
