### ISSUE TITLE
Animation state during animation or transition

### ISSUE THREAD

**Issue by spali** [angular/angular#9576]
```
[] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I use animation to toggle an element with two states (collapsed and expanded).
The element in my case is a sidebar which does not fully collapse (icons still visible).
The text will be hidden during the animation by binding [hidden]="isCollapsed()" on the text element.
But I can't get it to work, that the text is hidden at start of the collapse animation and visible only when the expand animation ends. If I'm right, this is due the state changes at the start of the animation. I didn't find a way to workaround this.

**Expected/desired behavior**
Possibility to define a "transition" state which will be active during a specific transition i.e. collapsing or expanding. Could be implemented as step in AnimationMetadata: 
`transition('collapsed => expanded', [ state(expanding), animate(1000) ])`
The problem I see with this solution would be, that this could end in an loop... if setting the expanding state would init something again during the initial transition. Maybe an other approach would be to allow to trigger a function after animation:
`transition('collapsed => expanded', [ animate(1000), myAnimationEndedHook() ])`

Or just something different to trigger after the animation is done. (don't know a way).

**Reproduction of the problem**
see the example. click the button twice. during expanding you see that the text is visible to early. I would like to unhide it after the animation is done.
http://plnkr.co/edit/j78rFPrf1mi0DeEngKvs?p=preview

**What is the motivation / use case for changing the behavior?**
more control about the animation, especially the time during animation.

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.3
- **Browser:** [Chrome 51 ] 
- **Language:** [all]

**Comment by matsko** [comment]
I think what's best is to update the `hidden` expression value once the animation completes? How do you check for an animation to complete? @ThomasBurleson is working on getting an event to fire:

```html
<div [@myAnimation]="exp" (@myAnimation.done)="hidden=true">
   <span [hidden]="hidden">Collapsable Content</span>
</div>
```

**Comment by matsko** [comment]
This issue will track the progress of this feature: https://github.com/angular/angular/issues/10304

**Comment by spali** [comment]
Thx for the Feedback, would work and allows to workaround with Code.
But it would less codding and (at least for me) morgen intuitive to have a transition class between the states. 
This would be more Kind of declarative more flexible. Imagine you use ng-content inside the component, the the user of the component could just write some styles to handle this, without having to hook Info a probably not exposed done() event of the component itself.

**Comment by matsko** [comment]
Closing for now since `@anim.done` has been supported for a while.
