### ISSUE TITLE
zone.js errors after upgrading from rc.1 to rc.3

### ISSUE THREAD

**Issue by prafsoni** [angular/angular#9577]
**I'm submitting a bug report**

**Current behavior**
build successful but app load fails due to various 404s

Prafulls-MacBook-Pro:prafsoni.github.io PKS$ ng serve
(node:56555) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Livereload server on http://localhost:49152
Serving on http://localhost:4200/

Build successful - 1366ms.

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
BroccoliTypeScriptCompiler                    | 920ms               
vendor                                        | 340ms               

Slowest Trees (cumulative)                    | Total (avg)         
----------------------------------------------+---------------------
BroccoliTypeScriptCompiler (1)                | 920ms               
vendor (1)                                    | 340ms               

<img width="1440" alt="screen shot 2016-06-24 at 12 49 16 pm" src="https://cloud.githubusercontent.com/assets/6965165/16344324/17911a02-3a0a-11e6-9a9a-9a4fdff213dc.png">

**Expected/desired behavior**
app should run fine

is this angular or angular-cli bug?

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
 
* **Browser:** [all ]
 
* **Language:** [ TypeScript ]

**Comment by vicb** [comment]
What are the steps to reproduce ?
Please provide a plunker if you can.

**Comment by prafsoni** [comment]
followed ng upgrade guide to upgrade project and used new Routing and Navigation document to update the routes to 3.0 alpha-7. I don't know if I can reproduce it on plunker, but I will try

**Comment by prafsoni** [comment]
[Plunker](http://plnkr.co/edit/qVbLXxM7X1Z4kB2RTp2M?p=preview&s=ff2FhZBG3rcIetf5)

**Comment by vicb** [comment]
> What are the steps to reproduce ?

**Comment by prafsoni** [comment]
Steps to reproduce
1 upgrade angular-cli beta 5 to beta 8 using angular-cli upgrade guide
2 upgrade project via ng init
3 override index.html, angular-cli.json, angular-cli-build.json, package.json (as no package other than default packages were used)
4 make necessary name changes example MyAppComponent to AppComponent
5 Follow Routing and Navigation documentation to refactor routes from version 2 to version 3
6 ng serve

For Plunker example I just typed it similar to my code.

**Comment by zihel** [comment]
You should be bootstrapping the route config instead of putting them in your component. In addition, your Plunker example also failed because

- router is not provided by the default template and must be manually added
- barrels must be defined within system.js config
- typo in src/about/index.ts

See my edits to your example - http://plnkr.co/edit/pQtKRokatu0Q2nA6yCCD?p=preview

**Comment by prafsoni** [comment]
Thanks changes in system-config.ts resolved the issue.
