### ISSUE TITLE
The routerLinkActive directive doesn't handle the parent router link

### ISSUE THREAD

**Issue by psumkin** [angular/angular#9578]
comp:  #router

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
```

**Current behavior**

The routerLinkActive directive doesn't handle the parent router link

**Expected/desired behavior**

The routerLinkActive directive handles the parent router link.
So, the element with routerLinkActive attribute gets active class on activate children routes.

**Reproduction of the problem**

http://plnkr.co/edit/AghfCP?p=info

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X
* **Router version:** 3.0.0-alpha.X
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [ TypeScript X.X  | ES5 ]

**Comment by brandonroberts** [comment]
The `routerLinkActive` does not do this by default, but it does work if you use the options

```html
  <a routerLinkActive="active" [routerLinkActiveOptions]="{ exact: false }">Parent</a>
```

I have an issue in to make this the default #9397

**Comment by intergleam** [comment]
so what? just closed without any explanation?

**Comment by Keith-Ball** [comment]
`[routerLinkActiveOptions]="{ exact: false }"` works as though it's using `indexOf(string) === 0` rather than `string === string` for route URL matching.

With exact: true and current url "/test/page1"
/test -- Doesn't match
/test/page1 -- Matches

With exact: false and current url "/test/page1"
/test -- Matches
/test/page1 -- Matches

**Comment by brandonroberts** [comment]
@Keith-Ball correct

**Comment by brandonroberts** [comment]
@intergleam this issue was resolved months ago. The issue was still open as it wasn't closed by the PR that fixed it
