### ISSUE TITLE
Default downgradeNg2Component bind behavior should mirror angular 1.x

### ISSUE THREAD

**Issue by trezm** [angular/angular#9580]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
An angular 2 component downgraded to a directive with `upgradeAdapter.downgradeNg2Component` does not bind properties like a current directive. It will pass a string literally to the angular2 component instead of trying to eval on the current scope, like in Angular 1.x.

**Expected/desired behavior**
prepending `bind-` to the attribute makes the directive work as it would in Angular 1.x. This should be the default behavior for a downgraded component.

**What is the motivation / use case for changing the behavior?**
For larger apps or directives that are used in many places across code, adding `bind-` before all attributes is a non-starter. It makes upgrading to A2 a much more cumbersome process.

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.3
- **Browser:**  all 
- **Language:** all

**Comment by gkalpak** [comment]
Unless I am missunderstanding what you are saying this should work already. (Open a new issue if not :smiley:)
