### ISSUE TITLE
Router bundles missing from 3.0.0-alpha.7

### ISSUE THREAD

**Issue by dzielin** [angular/angular#9584]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
Installing router 3.0.0-alpha.7 via npm does not add the referenced /bundles/ directory.  On pageload, JS console shows error that router.umd.js cannot be found.

**Expected/desired behavior**
Install of router 3.0.0-alpha.7 should provide the referenced /bundles/router.umd.js file.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
 
* **Browser:** [all] 
 
* **Language:** [all]

**Comment by ericmartinezr** [comment]
alpha 7 doesn't have a bundle, it was added recently https://github.com/angular/angular/pull/9422, the config right now is slightly different

**Comment by IgorMinar** [comment]
This was fixed in #9422 and will be out with the next router release
