### ISSUE TITLE
bug(router): navigate() resolves true when guard check resolves false

### ISSUE THREAD

**Issue by a88zach** [angular/angular#9595]
**I'm submitting a ...**
```
[x ] bug report
```

**Current behavior**
When a guard check is in place and the router does not navigate due to the guard check failing, the promise still resolves to true.

**Expected/desired behavior**
According to the documentation:
```
     * Returns a promise that:
     * - is resolved with 'true' when navigation succeeds
     * - is resolved with 'false' when navigation fails
     * - is rejected when an error happens
```
when navigation fails, the promise should resolve with false.  I need a way to test if the navigation has succeeded or not and I would think that the promise returned from the method navigate() would give me the correct result.

**Reproduction of the problem**
Here is a plunkr:
http://plnkr.co/edit/M4xmKvkOxRjmKtHrtQvz?p=info

To reproduce, go to the crisis center page and edit the name of a crisis.  Before you hit save or cancel, hit the heroes button to navigate to the heroes page.  When the first prompt is presented, click cancel.  The second prompt will show you the result of the navigate promise

**What is the expected behavior?**
The second prompt always shows "navigated: true" even when navigation does not occur due to a guard

**What is the motivation / use case for changing the behavior?**
I need to log out a user  when the user hits the logout button in my application. When logout occurs, i need to clear the jwt.  However, if the user is currently in the middle of editing a form I want to prevent the user from leaving the page (guard check) and prevent clearing the jwt if the logout navigation fails

**Please tell us about your environment:**

**Angular version:** 2.0.0-rc.3
**Angular router:** 3.0.0-alpha.8
 
**Browser:** all
 
**Language:** TypeScript 1.8

**Comment by vsavkin** [comment]
Fixed: https://github.com/angular/angular/pull/9603
