### ISSUE TITLE
Proposal: Declarative Dynamic Components

### ISSUE THREAD

**Issue by joelrich** [angular/angular#9599]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

As discussed in #8817, there is currently no convenient way to render a dynamic component. ```viewContainerRef.createComponent``` is too low-level for most use cases and requires to implement the update and destroy hook manually. This likely leads to bugs as well as suboptimal performance.

**Expected/desired behavior**

I suspect that ```createComponent``` will mostly be used to render a dynamic component at a certain position of a template. If this assumption holds true, then the same behaviour could be achieved with html code like the following:

```html
<template [ngComponent]="componentClass"
	[prop1]="propValue1"
	[ngProperties]="propertyValues">
```

When the code above is rendered, it would first resolve the component for the componentClass and instantiate the component. Then it would set all the regular properties. Since some properties may not be known at compile time, it would also be possible to provide an object with additional properties. At the end, the component is added directly to the DOM (without a wrapper element).

This could then also be used to render a list of dynamic components like this:

```html
<template
	*ngFor="let c of components"
	[ngComponent]="c.componentClass"
	[prop1]="c.propValue1"
	[ngProperties]="c.propertyValues">
```

Whenever the component class changes, the current component would replaced with a component instance of the new type.

I have chosen ```<template>``` for the placeholder because the placeholder itself must not be added to the DOM. I am not sure if this is the ideal element for the placeholder though.

This proposal could also be used as a replacement for ngInclude (#7596 and #2753).

**Comment by cmiagssh** [comment]
With the replacement of the component the desired properties and callback functions would also change.

So the sugestion would be that one is handing over json objects to the <template> component.

[bindings] = {
    "prop1": 123,
    "prop2": abc,
}

[events] = {
    "click": myClickFunction,
    "somethinghappened": mySomethingHappenedFunction
}

[two-way-bindings] = {
...

**Comment by cmiagssh** [comment]
I treid to solve this by injecting HTML using [innerHTML]. Unfortunately and quite as expected [innerHTML] code is not interpreted any more. Has anyone got an idea how to get around this? Like render a HTML containing String?

**Comment by zoechi** [comment]
For dynamic HTML #7596 is probably what you're looking for.

For adding dynamic components you can build a wrapper component yourself, for example like I showed in http://stackoverflow.com/questions/36325212/angular-2-dynamic-tabs-with-user-click-chosen-components/36325468#36325468

**Comment by cmiagssh** [comment]
Here is a solution to the issue:
https://github.com/cmiagssh/dynamicComponent

**Comment by cmiagssh** [comment]
Because the DynamicComponentLoader mentioned in the Post (http://stackoverflow.com/questions/36325212/angular-2-dynamic-tabs-with-user-click-chosen-components/36325468#36325468) I would go with the instructions in
https://dreambo8563.github.io/2016/05/17/Angular2-ComponentResolver/

**Comment by joelrich** [comment]
@cmiagssh I haven't tested it, but just from looking at the code I think there are various problems:
- You cannot change the component type after initialization
- You can only set properties with the bindings input (it is not possible to set a property directly)
- If the bindings change, then the target component will not be updated
- The event handlers will not work together with ```@Output```

@zoechi's implementation on stackoverflow allows to change the component type, but it does not support properties. Moreover, if it did support properties, then the updateComponent would be inefficient because it should only destroy the target component if the type has changed.

This is not meant as criticism, but just to show that it is not trivial to create a complete implementation.

**Comment by zoechi** [comment]
@joelrich I didn't intend to provide a fzll-featured implementation. I just tried to demonstrate how it can be done. Bindings are easy to add but the inputs need to be generic in some way because the input names have to be defined statically on the wrapper element.

@cmiagssh the post contains updated code for `ViewContainerRef.createComponent as well.

**Comment by vicb** [comment]
shoud be closed by https://github.com/angular/angular/pull/11235

**Comment by joelrich** [comment]
@vicb I agree. I am closing this issue. However, please have a look at my [my comment there](https://github.com/angular/angular/issues/11168#issuecomment-252259304). I think the current pull request is missing the very important ability to set dynamic properties and event listeners.

@cmiagssh since you have suggested `[events]`, you should have a look there as well.
