### ISSUE TITLE
ContentChildren for directive not working when component is on same element as directive

### ISSUE THREAD

**Issue by kukjevov** [angular/angular#9601]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If you have component and directive with selector selecting same element, your directive cant query its children. Since directive does not have template `ViewChildren` is always `undefined`. But `ContentChildren` are not set either if there is component "sitting" on same element, because `ViewChildren` of component are set. But for directive they should be still as `ContentChildren`.

**Expected/desired behavior**
Directive with or without Component or other Directives on same element should be able to query its children (probably and logicaly always as `ContentChildren`), which is required for some directives to work properly.

**Reproduction of the problem**
Here is a sample showing exactly mentioned situation. As you see `console.log` which shows directive content is always empty no matter what happens with its content and change subscription is never triggered.

https://plnkr.co/edit/NwGyJZv2SLWeajJiHhij

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
 
* **Browser:** [all] 
 
* **Language:** [TypeScript 1.8.10]

**Comment by vicb** [comment]
Queries do not work across component boundaries. IIUC you are querying from your app component and  would like to have children of the ParentCmp.

Thanks for the plunker. Please only use the minimum required code to exercise the issue and give exact steps to reproduce the issue.

**Comment by kukjevov** [comment]
I have one more question. I was not sure if this was bug or not, but imagine situation when you have directive with same selector result as some other component you know nothing about. You wrote only Directive and somebody else wrote that component. Your directive to work properly needs to query content children. But this Directive stops working as soon as somebody else writes some component with template and uses selector that has same selector result as your Directive. 

How would you solve this problem? You are only author of Directive which can be as external module loaded by application. Component can be written as part of applicaton. If you deploy your directive you dont know if somebody else will create component which will break your directive because you cant query content children.

What about this :) ?
