### ISSUE TITLE
Initial route doesn't load if route config provided to app component instead of bootstrap

### ISSUE THREAD

**Issue by pe8ter** [angular/angular#9604]
**I'm submitting a ...**
```
[x] bug report
```

**Current behavior**
A requested route does not appear on initial page load if you provide the route config to the app component instead of the bootstrap.

**Expected/desired behavior**
A requested route should appear on initial page load if you provide the route config to the app component.

**Reproduction of the problem**
[Here you can see the initial route not loading](https://plnkr.co/edit/HGZd7RdDRqItO0GAEqWz?p=preview) if you provide the route config to the app component. You should see "one" appear below the router links "one" and "two".

And [here you can see the initial route loading correctly](https://plnkr.co/edit/JpLOPMrtpq4ZnhlNCExC?p=preview) if you provide the route config to the bootstrap.

**Additional information**
Note that activating the router links allows the routes to load normally, even if the initial route didn't load.

**What is the motivation / use case for changing the behavior?**
It's nice to separate providing Angular dependencies at bootstrap from providing application dependencies to the app component. This bug breaks that separation pattern.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
* **Router version:** 3.0.0-alpha.8
 
* **Browser:** all
 
* **Language:** TypeScript 1.8.10

**Comment by brandonroberts** [comment]
This is intended behavior, the router needs to be provided at the bootstrap level. A workaround is to inject the router in your AppComponent and call `router.initialNavigation()`

**Comment by pe8ter** [comment]
`initialNavigation()` is marked as internal and not exposed in router.d.ts. Any chance of that becoming public?

**Comment by brandonroberts** [comment]
I believe the router is the exception to the rule for placing items in your bootstrap array vs the app component. The router is in the bootstrap array so it can be automatically instantiated when your app is bootstrapped using the APP_INITIALIZER token.

**Comment by akomm** [comment]
I have the described behaviour even when providing the router at bootstrap level via `PLATFORM_DIRECTIVES`.

**Comment by vsavkin** [comment]
The `provideRouter` function, which works only when passed into bootstrap, is deprecated. Instead, you should use RouterModule: `https://github.com/angular/angular/blob/master/modules/@angular/router/src/router_module.ts`.

RouterModule can be passed into bootstrap:

```
bootstrap(MyComponent, {
  modules: [RouterModule],
  providers: [provideRoutes(someRoutes)]
})
```

Or used when defining an app module:

```
@AppModule({
  modules: [RouterModule],
  providers: [provideRoutes(someRoutes)]
})
class MyAppModule {}
```

Both the options will properly initialize the router.
