### ISSUE TITLE
Rename Link Parameters Array as Routing Info Array

### ISSUE THREAD

**Issue by siva636** [angular/angular#9607]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently we call Link Parameters Array, this is a very generalized name.

**Expected/desired behavior**
Rename Link Parameters Array as Routing Info Array, then this will be more suitable to what we are dealing with and inline with other terminologies such as 'Routing Component'.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart]

**Comment by vsavkin** [comment]
Not sure what you are referring to. Could you provide more context?

**Comment by siva636** [comment]
An array that the router interprets into a routing instruction is currently called as "Link Parameters Array". This array is not only related to link / anchor but also used to pass as an argument to the **Router.navigate** method. That is why it is more suitable to call this as "Routing info array".

**Comment by zoechi** [comment]
@siva636 can you please post a link to where it is named this way?

**Comment by vsavkin** [comment]
Thank for opening the issue. I think you are referring to "Link Parameters Array" used in dev guides. Issues regarding updating dev guides should be open here: https://github.com/angular/angular.io. Could you reopen this issue there?

Closing this issue.
