### ISSUE TITLE
Single file bundles + documentation for ES5 users

### ISSUE THREAD

**Issue by jokade** [angular/angular#9609]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report
[X] feature request
[ ] support request 
```

**Current behavior**
Until RC0 it was easy to integrate Angular2 with plain ES5 using the single files bundles and System.js published to code.angularjs.org; since the RCs, we need to include a lot of separate files (and it feels like a modular hell :).

**Expected/desired behavior**
It would be great, if there was again a "plain old ES5" distribution that doesn't require an npm build chain (I'm writing an Angular2 interface for Scala.js, and although it's possible to integrate its build tool with an npm build chain, it makes the build process really fat and complicated compared to Angular1).  A single file distribution is probably not good idea, but if there are multiple js files to be loaded for ES5, a build-tool agnostic guide on what files are required for which feature would be really helpful.  

**What is the motivation / use case for changing the behavior?**
Easy integration with plain ES5, e.g. for Scala.js users.

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.X
- **Browser:** all 
- **Language:** ES5

**Comment by Thaina** [comment]
Additionally I wish we could have something like angular loader that could import module in js file. Instead of script tag for each module

**Comment by jelbourn** [comment]
Closing since we no longer produce ES5 outputs.
