### ISSUE TITLE
Dependency injection is not smart?

### ISSUE THREAD

**Issue by phevose** [angular/angular#9611]
If there is such a scenario:
aService depend bService,when i want inject aService to Acomponent,i need declare"providers: [aService,bService]" in Acomponent,That means caller(component) must very clear each of the dependencies between services. code as below:
-------------b.service.ts-----------
```
export default class BService {
    format() {
        return 'Log: ';
    }
}
```
------------a.service.ts-------------
```
import BService from './b.service';
export default class AService {
    constructor(private bService:BService ) {
    }
    log(str) {
        console.log(`${this.bService.format()}${str}`);
    }
}
```

-----------a.component.ts----------
```
import {Component}   from 'angular2/core';
import AService from './a.service';
import BService from './b.service';

@Component({
    selector: 'my-app',
    template: '<h1>App Component</h1>',
    providers: [AService, BService]//You have to remind youself that don't forget BService!!! Although you needn't directly use it.
})
export class AppComponent {
    constructor(private aService:AService) {
    }

    ngOnInit() {
        this.aService.log('component init');
    }
}
```
**The truth and I think it is?Maybe this isn't the best practice?**

**Comment by DzmitryShylovich** [comment]
if u just leave `providers: [AService] ` where do u provide BService?

**Comment by phevose** [comment]
@DzmitryShylovich This is my doubts,AService already declare the relationship between B and C,but angular2 need declare in providers again.although this is the rules of the angular2.

**Comment by DzmitryShylovich** [comment]
if u don't want to provide you services on component level u can provide them during bootstrap.

```
bootstrap(AppComponent , [BService]);
```

this way u can declare 

```
import {Component}   from 'angular2/core';
import AService from './a.service';
import BService from './b.service';

@Component({
    selector: 'my-app',
    template: '<h1>App Component</h1>',
    providers: [AService]
})
export class AppComponent {
    constructor(private aService:AService) {
    }

    ngOnInit() {
        this.aService.log('component init');
    }
}
```

**Comment by phevose** [comment]
@DzmitryShylovich If  in a team,i wirte service,you wirte component,when you call my service,you must know my service's dependency relationship and declare in you component or root component.If one day i modify service's dependency relationship,i must tell you change you code,If the changes are frequent,You will hate me.

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular/issues/5622

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) for support request.
