### ISSUE TITLE
Issue with WebDriverJS selectors on input field

### ISSUE THREAD

**Issue by blacksonic** [angular/angular#9612]
**I'm submitting a bug report**

I'm currently working on the TodoMVC implementation of Angular 2 with ES2015, my pull request is here https://github.com/tastejs/todomvc/pull/1581
The problem can be related to this https://github.com/angular/angular/issues/6250

**Current behavior**

The problem is when selecting an input element (doesn't matter the method if it's by css, xpath etc.) the promise it returns it's `then` callback is executed multiple times, even if i select only a single element.
https://github.com/tastejs/todomvc/blob/master/tests/page.js#L257

**Expected/desired behavior**

Single element selects promise should be executed only once.

**Reproduction of the problem**

The bug can be reproduced by running the browser tests for the Angular 2 implementation or my pull request.

**Please tell us about your environment:**

Angular version: 2.0.0-rc.3

**Browser:** Chrome 

**Language:** TypeScript | ES6/7

**Comment by vikerman** [comment]
Obsolete
