### ISSUE TITLE
EXCEPTION: No value accessor for

### ISSUE THREAD

**Issue by zeeshanjan82** [angular/angular#9616]
I am using the following advanced seed for angular: https://github.com/NathanWalker/angular2-seed-advanced when I try to integrate the new forms I get the error ```EXCEPTION: No value accessor for``` the strange thing is I have app.component which is the @RouteComponent and then it has home.component which is also @RouteComponent inside home component I am using contact-form component which is marked with @FormComponent, if I move the code of contact-form inside home- component then everything works fine but when I have this nesting then I get this error, following is my code:

```js

@RouteComponent({
  moduleId: module.id,
  selector: 'sd-home',
  templateUrl: 'home.component.html',
  directives: [ContactFormComponent],
  styleUrls: ['home.component.css']
})
export class HomeComponent implements AfterViewInit {
  public newName: string = '';
  constructor(private store: Store<any>) { 
    console.log('Loaded');
  }

  ngAfterViewInit(){
    OnLoad();
  }
}

```

````js

@FormComponent({
  moduleId: module.id,
  selector: 'sd-contact-form',
  templateUrl: 'contact-form.component.html',
  directives: [REACTIVE_FORM_DIRECTIVES],
  styleUrls: ['contact-form.component.css']
})
export class ContactFormComponent implements OnInit {
  contactForm: FormGroup;
  @Output() OnSubmit = new EventEmitter<any>();

  constructor(){}

 ngOnInit() {
  this.contactForm = new FormGroup({
    contact: new FormGroup({
      fullname: new FormControl(),
      email: new FormControl(),
      phonenumber: new FormControl(),
      message: new FormControl()
    })
   });
  }

```

````html
<form [formGroup]="contactForm">
  <div formGroupName="contact">
  <div class="row">
    <div class="col-md-4 col-sm-4 col-xs-4">
      <input type="text" class="form-control" placeholder="Full Name" formControlName="fullname">
       <div class="validation-wrap">
          <p class="validation-wrong"><i class="glyphicon glyphicon-remove"></i> Please enter full name.</p>
      </div>
    </div>
    <div class="col-md-4 col-sm-4 col-xs-4">
      <input type="email" class="form-control" placeholder="Email Address" formControlName="email">
      <div class="validation-wrap">
         <p class="validation-wrong"><i class="glyphicon glyphicon-remove"></i> Please enter valid email.</p>
     </div>
    </div>
    <div class="col-md-4 col-sm-4 col-xs-4">
      <input type="text" class="form-control" placeholder="Phone Number" formControlName="phonenumber">
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <textarea rows="6" class="form-control" placeholder="Your Message" formControlName="message"></textarea>
      <div class="validation-wrap">
         <p class="validation-wrong"><i class="glyphicon glyphicon-remove"></i> Please enter your message.</p>
     </div>
    </div>
  </div>
</div>
  <div class="row">
    <div class="col-md-12">
      <button type="submit" class="btn btn-danger sendContact">Send Message</button>
    </div>
  </div>
</form>
````

![error](https://cloud.githubusercontent.com/assets/8342604/16362529/9c4cdf86-3bce-11e6-8039-eb2ba9f0b3e0.png)

**Comment by vicb** [comment]
Please provide a plunker with exact steps to reproduce

**Comment by zoechi** [comment]
`@FormComponent` is not a decorator provided by Angular2.

**Comment by vicb** [comment]
Closing as it does not seem to be related to angular. Please re-open with a plunker if you think it is.

**Comment by farfunni** [comment]
By updating to _2.0.0-rc.3_ I am having exactly the same problem without the custom decorator. Plunker here: [http://plnkr.co/edit/F0gWLgtDYntfhoYrJZQ6] (http://plnkr.co/edit/F0gWLgtDYntfhoYrJZQ6).  
Any help would be much appreciated!

**Comment by zoechi** [comment]
@farfunni 
Following the instructions in the console log would probably have solved your problem.

```
bootstrap(App, [
  disableDeprecatedForms(),
  provideForms()
])
```

https://plnkr.co/edit/9XogrULe6atg4WMOCiqS?p=preview

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by farfunni** [comment]
@zoechi 
Thanks for the quick reply and sorry for the mistake - I thought I was supporting the topic (and failed miserably ;)).

**Comment by amarewgs** [comment]
I had this same issue with last version of angular rc.5, am getting 'No value accessor for form control with unspecified name'. I have tried different options but no luck. please take a look at http://stackoverflow.com/questions/38958347/angular2-rc-5-custom-input-component

**Comment by theunreal** [comment]
Same issue with RC.5

**Comment by mausadd** [comment]
I had the same issue and I resolved it with @farfunni  suggestion, I made the changes in main.ts file and everything is working properly.

import { bootstrap } from '@angular/platform-browser-dynamic';
import { enableProdMode } from '@angular/core';
import { AppComponent, environment } from './app/';
import { disableDeprecatedForms, provideForms } from '@angular/forms';

if (environment.production) {
  enableProdMode();
}

bootstrap(AppComponent, [
  disableDeprecatedForms(),
  provideForms()
]);

**Comment by vsiniakov** [comment]
with RC 5 if you build a custom control that implements ControlValueAccessor - add "ngDefaultControl"into the <sd-contact-form ngDefaultControl></sd-contact-form>
