### ISSUE TITLE
bug(routerLink) Links paths are destroyed if you toggle them with *ngIf

### ISSUE THREAD

**Issue by qdouble** [angular/angular#9617]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Current behavior**
There appears to be a bug that causes link paths to be erased if you toggle them with *ngIf, but it works correctly if you use hidden. 

**Reproduction of the problem**
https://plnkr.co/edit/qQAASzPMcp64II8TlPVP?p=preview

**What is the expected behavior?**
the deprecated router and the ngrx/router are able to preserve the link when you toggle it on and off with *ngIf. The new router should do the same. 

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [all]

**Comment by DzmitryShylovich** [comment]
I guess it's also related to https://github.com/angular/angular/issues/9535

**Comment by vsavkin** [comment]
Fixed: https://github.com/angular/angular/pull/9603
