### ISSUE TITLE
Set view.context.$implicit = change.item; not setting context in rc.3 (worked in 0.17)

### ISSUE THREAD

**Issue by born2net** [angular/angular#9618]
```
view.context.$implicit = change.item;
```
not setting content and as you can see in plunkr the same name repeats
Here is the plunk:
https://plnkr.co/edit/Wx2Q3OqbPcgIc5d8GoFT?p=preview

working fine prior to rc.x with
```
view.setLocal('\$implicit', change.item);
```

prev version works:
http://plnkr.co/edit/4ey5kT0ORTnpqn7pLN8P?p=preview

regards

Sean

**Comment by vicb** [comment]
Replace your directive with `ngFor` and it works as expected (please fill out the template when submitting an issue, ie what is the behavior vs what is expected).

Double check your own code for error or try to isolate the root cause. Thanks.

**Comment by born2net** [comment]
Hi Vic, what do you mean replace with ngFor?
The whole point is to create a custom repeater, please re-open as we did not address the issue on hand

regards

**Comment by zoechi** [comment]
What don't you just pass `context` to `createEmbeddedView(...)` like shown in https://github.com/angular/angular/blob/ae75e3640a2d9eb1e897a0771d92b976c5a42c75/modules/%40angular/common/src/directives/ng_template_outlet.ts#L61

**Comment by zoechi** [comment]
You also didn't address the points vicb mentioned like filling out the template.

**Comment by born2net** [comment]
tx will check code, and the template is gone so didn't have the required field, but next time I will , tx again

**Comment by born2net** [comment]
Hi again, in the example you provided context is retrieved from ```set ngOutletContext```
which I dont use in my example, as in my example context is off the view, so where can  I get a reference to it?

regards

Sean

**Comment by ericmartinezr** [comment]
@vicb 

`setLocal` and `getLocal` were deprecated in favor of `context`. In @born2net 's example you can see that one line changed everything.

Working example (using beta 17) http://plnkr.co/edit/4ey5kT0ORTnpqn7pLN8P?p=preview

```
changes.forEachAddedItem((change) => {
    let view = this.viewContainer.createEmbeddedView(this.template);
    view.setLocal('\$implicit', change.item);   // working fine
 });

// Prints
Joe is 10 Remove
Patrick is 21 Remove
Melissa is 12 Remove
Kate is 19 Remove
```
See in the plnkr that the list of users is printed correctly

Non-working example (RC.x) https://plnkr.co/edit/Wx2Q3OqbPcgIc5d8GoFT?p=preview

```
changes.forEachAddedItem((change) => {
    let view = this.viewContainer.createEmbeddedView(this.template);
    view.context.$implicit = change.item; // not working
 });

// Prints
Kate is 19 Remove
Kate is 19 Remove
Kate is 19 Remove
Kate is 19 Remove
```
See that the list takes the last element and repeats it as much items are there in the list.

Using `ngFor` here is not really a solution, the point here is using custom structural directives, and they seem to be broken (?), or they changed their behavior and it's not documented.

This is literally one line change, so there's something weird there...

Would you mind to ping someone who can look at this and explain/fix this odd change of behavior?

**Comment by born2net** [comment]
and please re-open issue so we can track it, 

regards
