### ISSUE TITLE
Sub-Component that changes binded value

### ISSUE THREAD

**Issue by manfredsteyer** [angular/angular#962]
Hi,

I've written a simple Web-Compontant/ directive in Angular2 that binds to a passed value und provides a mehtod that changes it:

```
import {Component, Decorator, Template, If} from 'angular2/angular2';

@Component({
    selector: 'bindsample',
    bind: {
        'value': 'value'   
    }
})
@Template({
  url: 'bindsample.html',
  directives: []
})
export class BindSample {
    
    doStuff() {
        this.value = "Hello World!";
    }
    
}
```

The template looks like this:

```
<div>
    <a (click)="doStuff()">Click me!</a>
</div>
```

And the directive is used this way:

```
<bindsample [value]="someValue"></bindsample>
someValue: {{ someValue }}
```

When I click the like, doStuff is called and updates the bound value. But unfortunatelly, the binding of {{ someValue }} is not updated.

Now I'm wondering, if a) this is a bug, b) not implemented, c) due to the new concept of one-way-databinding in ng2.

**Comment by manfredsteyer** [comment]
formatting

**Comment by pkozlowski-opensource** [comment]
I believe that this is due to (c) in your list. If you want a component to propagate state changes to the outside world you can have a custom event (ex.: on-valuechange).

**Comment by manfredsteyer** [comment]
Thx for your information. Is there already a mechanism in angular 2 to fire a custom event, like valuechanged? In Polymer they seem to just call something like this.fire('valuechanged');

**Comment by manfredsteyer** [comment]
Oh, I just digged around in the code and in the issues list here and found out, that one can accompish this using EventEmitter:

```
import {Component, Decorator, Template, If} from 'angular2/angular2';
import {EventEmitter } from 'angular2/src/core/annotations/events';

@Component( ... )
@Template( ... )
export class BindSample {
    
  constructor(@EventEmitter('changed') changed: Function) {
        this.changed = changed;   
    }
    ...  
}
```

**Comment by mhevery** [comment]
closing as resolved
