### ISSUE TITLE
Directive bindings BC BREAK in rc2

### ISSUE THREAD

**Issue by castamir** [angular/angular#9620]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

```js
import {Directive, Renderer, ElementRef, forwardRef} from '@angular/core';
import {NG_VALUE_ACCESSOR, ControlValueAccessor} from '@angular/common';
import {TextControlComponent} from './control.input.text';

export const INPUT_TEXT_VALUE_ACCESSOR: any = /*@ts2dart_const*/ {
    provide: NG_VALUE_ACCESSOR,
    useExisting: forwardRef(() => TextControlValueAccessor),
    multi: true
};

@Directive({
    selector: 'controlText',
    host: {'(valueChange)': 'onChange($event)'},
    bindings: [INPUT_TEXT_VALUE_ACCESSOR]
})
export class TextControlValueAccessor implements ControlValueAccessor {
    onChange = (_) => {
    };
    onTouched = () => {
    };

    constructor(private _renderer: Renderer, private _elementRef: ElementRef, private host: TextControlComponent) {
    }

    writeValue(value: any): void {
        this.host.writeValue(value);
    }

    registerOnChange(fn: (_: any) => {}): void {
        this.onChange = fn;
    }

    registerOnTouched(fn: () => {}): void {
        this.onTouched = fn;
    }
}
```

throws (RC2)
```
error TS2345: Argument of type '{ selector: string; host: { [x: string]: string; '(valueChange)': string; }; bindings: any[]; }' is not assignable to parameter of type '{ selector?: string; inputs?: string[]; outputs?: string[]; properties?: string[]; events?: strin...'.
  Object literal may only specify known properties, and 'bindings' does not exist in type '{ selector?: string; inputs?: string[]; outputs?: string[]; properties?: string[]; events?: strin...'.
```

**Expected/desired behavior**
Properly binding for custom form control as in rc1.
How to make it work in rc2 and above?

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.2

* **Language:** [TypeScript ^1.8.9]

**Comment by ericmartinezr** [comment]
`bindings` has been deprecated since the beggining of the times, and it looks like it was finally removed. You should use instead `providers`, see the signature here https://github.com/angular/angular/blob/master/modules/@angular/core/src/metadata.ts#L111-L134

**Comment by castamir** [comment]
@ericmartinezr thanks for fast response!

`providers` works :+1: 

A note in changelog would be nice, still ;)
------------------

I've seen in many tutorials that there is a syntax sugar for a custom provider using e.g. `provide` function. But whole file including `Provide` and `ProvideBuilder` classes is deprecated. Is there any replacement? What is the best practise for this?

**Comment by ericmartinezr** [comment]
The replacement is now `{provide : X, useClass: Z}`, you can see this change syntax in the cheat sheet in the website under **Dependency injection configuration**

https://angular.io/docs/ts/latest/guide/cheatsheet.html

**Comment by castamir** [comment]
Nice! Thanks for help ;) :+1:
