### ISSUE TITLE
Component doesn't load if styleUrls is not a CSS file

### ISSUE THREAD

**Issue by craftbyte** [angular/angular#9621]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Component doesn't load without any errors

**Expected/desired behavior**
Error in console, component loads without CSS

**Reproduction of the problem**

``` typescript
@Component({
  selector: 'my-hero-detail',
  templateUrl: 'app/hero-detail.component.html',
  styleUrls: ['app/hero-detail.component.html']
})
```

**What is the motivation / use case for changing the behavior?**
People make mistakes, it should at least throw an exception/error in the console.

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.3
- **Browser:** Chrome 52.0.2743.49 beta
- **Language:** all

**Comment by DzmitryShylovich** [comment]
http://plnkr.co/edit/BHxJTCqQCaBmdoKzXw9K?p=preview

component does load

**Comment by pkozlowski-opensource** [comment]
Can't reproduce in a simple stackblitz: https://stackblitz.com/edit/angular-gd66zt

As this is very old issue and we don't have reproduce scenario I'm going to close it.
