### ISSUE TITLE
Jasmine dependency Injection fails when using a string to identify the provider

### ISSUE THREAD

**Issue by talkdirty** [angular/angular#9625]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I'm mocking a service in Jasmine:

```
beforeEachProviders(() => [
        {provide: PerferenceService, useClass : PerferenceService}, 
        {provide: "StorageDevice", useClass : MockStorageDevice}]
    );
```

As you can see, I'm testing a service (**PreferenceService**) which is dependant on a class provided by the provider "StorageDevice". Thus, the constructor of PreferenceService looks like this:
`constructor(@Inject("StorageDevice") private StorageDevice){ ...`

This doesn't work (Jasmine fails with the same error message as here: #8867). However, identifying the Provider using a class does:

```
...
export class CStorage{}
...
beforeEachProviders(() => [
{provide: PerferenceService, useClass : PerferenceService},
{provide: CStorage, useClass : MockStorageDevice}]
);

//Constructor of PreferenceService
constructor(private StorageDevice : CStorage) { ...

```

**Expected/desired behavior**
Shouldn't provider identification be also possible using strings?

**Reproduction of the problem**
todo

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.3
- **Browser:** Chrome
- **Language:** Typescript

**Comment by IgorMinar** [comment]
Does this problem occur only while testing? Can you try repro the same issue outside of testing?

**Comment by talkdirty** [comment]
Outside of testing, everything works just fine. The problem only occurs when providing components for Injection inside the Angular/Jasmine `beforeEachProviders` method.
Somewhere further up in my Component Hierarchy I have been providing the dependency like this:
```
@Component({
...
providers : [ ...
    provide("StorageDevice", {useClass : LocalStorage})
}) export class AppComponent { ... }
```
Which is being injected just fine into things that request an instance of it:
```
@Injectable()
export class PreferenceService { ...
    constructor(@Inject("StorageDevice") private StorageDevice)
...
}
```
Once again referring to #8867, I'd like to point out that the `beforeEachProviders()` method has recently been changed, in that you now have to return this kind of list:
```
beforeEachProviders(() => [
    {provide: SomeIdentifier, useClass: SomeClass}
])
```
instead of this:
```
beforeEachProviders(() => [
    provide(SomeIdentifier, {useClass: SomeClass})
])
```
(See also this [testing example](https://github.com/angular/angular/blob/ae75e3640a2d9eb1e897a0771d92b976c5a42c75/modules/%40angular/examples/testing/ts/testing.ts))
The problem might come from this recent change.
On a different note, is angular2-rc3 up anywhere on CDN? I can't provide a plunkr of this because the most recent version of angular2 on [code.angularjs.org](code.angularjs.org) is only beta 17.

**Comment by robwormald** [comment]
The plunkr starter template is up to date, and uses npmcdn plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5

**Comment by vikerman** [comment]
Please re-open if this is still an issue
