### ISSUE TITLE
Active routerLink no longer sets a css class

### ISSUE THREAD

**Issue by jkyoutsey** [angular/angular#9626]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When selecting a `[routerLink]` there appear to be no styles to indicate to the user that that routerLink is the selected one.  Router used to add class `outer-link-active` but this doesn't seem to be the case now.  Can be seen in the official documentation's plunker https://angular.io/resources/live-examples/router/ts/plnkr.html

**Expected/desired behavior**
The currently selected routerLink should have a class applied to allow styling, such as `router-link-active`.

**Reproduction of the problem**
https://angular.io/resources/live-examples/router/ts/plnkr.html

**What is the expected behavior?**
Class applied

**What is the motivation / use case for changing the behavior?**
Informing users of currently selected route.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
 
* **Browser:** Chrome latest Mac and FF latest Mac.
 
* **Language:** Typescript 1.8.10

**Comment by zoechi** [comment]
It working as intended http://plnkr.co/edit/JcD2Lqht3oP99VMVAoRo?p=preview add `routerLinkActive="active"`

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by jkyoutsey** [comment]
@zoechi That really needs documented.  And the naming is terrible.  `routerLinkActive="active"` suggests that the link is active.  But it's added to EVERY routerLink?  What's going on under the covers?

**Comment by zoechi** [comment]
There isn't much going on https://github.com/angular/angular/blob/327d04c9c6db7413bcdd01a83a5a4849a25fe674/modules/%40angular/router/src/directives/router_link_active.ts 
You can build your own directive with a fixed class (and even provide it globally) so it get's applied to every `routerLink` if you want/needs/...

**Comment by brandonroberts** [comment]
@jkyoutsey `routerLinkActive="active"` isn't fixed. It could be `routerLinkActive="red green blue"`. Its just an example of what the class name added will be once the routerLink is current

**Comment by jkyoutsey** [comment]
That's the thing.  In the plunker linked to the official docs, it does **not** apply the class.  

```html
<nav>
      <a ng-reflect-router-link="/crisis-center" ng-reflect-href="/zQzF9L1QxgjPlxdJ/crisis-center" href="/zQzF9L1QxgjPlxdJ/crisis-center">Crisis Center</a>
      <a ng-reflect-router-link="/heroes" ng-reflect-href="/zQzF9L1QxgjPlxdJ/heroes" href="/zQzF9L1QxgjPlxdJ/heroes">Heroes</a>
      <a ng-reflect-router-link="/crisis-center/admin" ng-reflect-href="/zQzF9L1QxgjPlxdJ/crisis-center/admin" href="/zQzF9L1QxgjPlxdJ/crisis-center/admin">Crisis Admin</a>
      <a ng-reflect-router-link="/login" ng-reflect-href="/zQzF9L1QxgjPlxdJ/login" href="/zQzF9L1QxgjPlxdJ/login">Login</a>
    </nav>
```

In the plunker that @zoechi provided, it does. 

```html
<nav _ngcontent-fui-1="">
      <a _ngcontent-fui-1="" routerlinkactive="active" ng-reflect-router-link="/crisis-center" ng-reflect-router-link-active="active" ng-reflect-href="/7xPs1DwwK482Hfv0/crisis-center" href="/7xPs1DwwK482Hfv0/crisis-center" class="active">Crisis Center</a>
      <a _ngcontent-fui-1="" routerlinkactive="active" ng-reflect-router-link="/heroes" ng-reflect-router-link-active="active" ng-reflect-href="/7xPs1DwwK482Hfv0/heroes" href="/7xPs1DwwK482Hfv0/heroes">Heroes</a>
      <a _ngcontent-fui-1="" routerlinkactive="active" ng-reflect-router-link="/crisis-center/admin" ng-reflect-router-link-active="active" ng-reflect-href="/7xPs1DwwK482Hfv0/crisis-center/admin" href="/7xPs1DwwK482Hfv0/crisis-center/admin">Crisis Admin</a>
      <a _ngcontent-fui-1="" routerlinkactive="active" ng-reflect-router-link="/login" ng-reflect-router-link-active="active" ng-reflect-href="/7xPs1DwwK482Hfv0/login" href="/7xPs1DwwK482Hfv0/login">Login</a>
    </nav>
```

But it provides it on EVERY router-link.  So, I still don't see how the browser can apply any unique style to it...

My project is getting behavior that does not apply routerlinkactive.  So, short of minute comparison of two plunkers... What changed?

**Comment by ericmartinezr** [comment]
Yes, we just need to wait https://github.com/angular/angular.io/pull/1755.

**Comment by dharders** [comment]
Sorry to make this a bit of a support thread, but if @zoechi could please elaborate on your above comment  so I can close out issue / feature request #9426 too.

> You can build your own directive with a fixed class (and even provide it globally) so it get's applied to every routerLink if you want


```
// routerLinkActiveAutoAttach.directive.ts
import {Directive, Host} from '@angular/core';

@Directive({
    selector: '[routerLink]',
    host: { ['routerLinkActive']: "router-link-active"},   // fixed class: "router-link-active", ala old router
})
export class RouterLinkActiveAutoAttach{
}
```
```
// boot.ts
bootstrap(
    ...
    provide(PLATFORM_DIRECTIVES, {useValue: RouterLinkActiveAutoAttach, multi: true}),
    ...
)
```
This obviously doesn't work, instead attaches `routerlinkactive="router-link-active"` (note lowercase attribute) to every element with `[routerLink]` specified (globally !).

How to attach a directive from another directive (if possible) ??

**Comment by zoechi** [comment]
@dharders you wozld need to duplicate the routerLinkActive directive implementation.
