### ISSUE TITLE
Recursive component not working with templateUrl

### ISSUE THREAD

**Issue by Suyogya** [angular/angular#9627]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I am trying to use a component recursively.
 - The recursive component works, if I am using a template but it doesn't work when I switch to templateUrl for version RC3

**Expected/desired behavior**
 The recursive component should work with both template and templateUrl

**Reproduction of the problem**
Declare a recursive component test.component.ts
`
import {Component, Input} from '@angular/core'

@Component({
  selector: 'my-test',
  providers: [],
  templateUrl: './app/test.component.html',
  directives: [TestComponent]
})
export class TestComponent {
  @Input() nested: bool;
  private nest = false;
  constructor() {
    this.name = 'Angular2 (Release Candidate!)'
  }
}`

test.component.html
`<div>
    <h2>Hello {{name}}</h2>
</div>
<my-test *ngIf="nested" [nested]="nest"></my-test>`

app.component.ts

`import {Component} from '@angular/core';
import {TestComponent} from './test.component';

@Component({
  selector: 'my-app',
  providers: [],
  template: `
    <div>
      <h2>Hello {{name}}</h2>
    </div>
    <my-test [nested]="nest"></my-test>
  `,
  directives: [TestComponent]
})
export class App {
  private nest = true;
  constructor() {
    this.name = 'Angular2 (Release Candidate!)'
  }
}`

**What is the expected behavior?**
 - This should create a my-test component inside my-test component

**What is the motivation / use case for changing the behavior?**
 - templateUrl seems to be working fine in plnkr which seem to use older version of angular 2. Both the template and templateUrl should have the same behavior.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
 
* **Browser:** [Chrome 52.0.2743.33 beta (64-bit) ] 
 
* **Language:** [TypeScript ]

**Comment by vicb** [comment]
Please provide a plunker with exact steps to reproduce

**Comment by thelgevold** [comment]
There shouldn't be anything preventing recursive components from using templateUrls. Double check the path maybe? Does the template url show as loaded correctly in the browser's network tab? 

I have a recursive treeview sample here that is using a templateUrl.

http://www.syntaxsuccess.com/viewarticle/recursive-treeview-in-angular-2.0

```
import {Component, Input} from '@angular/core';
import {Directory} from './directory';

@Component({
    selector: 'tree-view',
    templateUrl: './components/tree-view/tree-view.html',
    directives: [TreeView]
})

export class TreeView {
    @Input() directories: Array<Directory>;
}
```

```
<ul>
    <li *ngFor="let dir of directories">

        <span class="iconButton" (click)="dir.toggle()">{{dir.getIcon()}}</span><input type="checkbox" [checked]="dir.checked" (click)="dir.check()" /> {{ dir.name }}

        <div *ngIf="dir.expanded">

            <ul>
                <li *ngFor="let file of dir.files">{{file}}</li>
            </ul>

            <tree-view [directories]="dir.directories"></tree-view>

        </div>

    </li>
</ul>
```

**Comment by Suyogya** [comment]
I think I might have been too focused on chrome. The issue seems to happen only in the chrome beta release in chrome. I was not able to replicate the issue in the stable version or Firefox. So, I don't think this is an angular issue.

**Comment by cesar-carrasco** [comment]
Seeing this in the latest Chrome: Version 52.0.2743.82 (64-bit)
```
@Component({
  selector: 'item',
  directives: [Item],

  // Works:
/*  
  template: `
    <div *ngIf="nest">
        <item></item>
    </div>
  `
*/  
  // Doesn't work:
  templateUrl: [ './item.html' ]
})
export class Item {
    @Input() nest: boolean = false;
    
    constructor() {
    }
}
```
Where item.html is
```
<div *ngIf="nest">
    <item></item>
</div>
```

Can this be reopened?
Here's a simple plunker: http://plnkr.co/edit/hihLW65v7gjzeltGHXcw?p=preview

**Comment by cesar-carrasco** [comment]
bah! nevermind lol was the path
```
templateUrl: [ './src/item.html' ]
```

**Comment by taguan** [comment]
Should'nt this ticket be reopened ? I experimented the same issue (also on chrome, version 52.0.2743.116), solved it by inlining my template, but it was super hard to diagnostic as there is no error in console whatsoever.

**Comment by sfadmin** [comment]
I've experienced the same problem with the actual chrome version "Version 52.0.2743.116 m" and Angular version "2.0.0-beta.9". My recursive tree view has been working until yesterday. Sine today it's hanging without of any error message. I've not changed anything, so the issue must be related to the new Chrome version. Switching from templareUrl to inline template fixed the issue.

Strange thing, or?

**Comment by djejaquino** [comment]
@vicb I think this should be reopened.

Since Chrome updated to 52.xxx, my team is having the same issue.
We are in RC3 and still use router-deprecated.

**Comment by reginaldocmrg** [comment]
Surely, this issue should be reopened.

After upgrade my Chrome to latest 52 version, we are having this issue. I tested in older versions (47 and 51) and in another browsers like Edge and Firefox and it works.
We are using the deprecated version of router in RC2.

Inline works here!

**Comment by StijnSaelens** [comment]
Some problem here. Chrome 52 doenst' work, but Firefox 48 works perfectly.

**Comment by WilliamsJoe** [comment]
I ran into a similar issue and resolved it by changing the templateUrl value from 'my.component.html' to './my.component.html' where my.component.html is located in the same directory as my my.component.ts file where the Component is define.

@Component({
  moduleId: module.id,
  selector: MY_SELECTOR,
  templateUrl: './rep.component.html'
})
