### ISSUE TITLE
Not able to make Angular2 Rc2 on IE 10

### ISSUE THREAD

**Issue by vinojatnous** [angular/angular#9628]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report

```

**Current behavior**
Using Angular2 RC2 and Core-Js  "^2.4.0",

     System.import('app/boot').then(
            module =>
                    module.main(
                        {
                            name: 'xxxxxxxxxxxxx',
                            authentication: 'xxxxxxxxxxxxx'
                        }
                    ),
            console.error.bind(console)
        );
But I get a syntax error at module =>

**Expected/desired behavior**

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.2
 
* **Browser:** [IE 10 ] 
 
* **Language:** [all | TypeScript 1.8 | ES5 ]

**Comment by vinojatnous** [comment]
It works perfectly in Chrome but not on IE 10

**Comment by zoechi** [comment]
Ensure you have polyfills loaded correctly. 
If you think you did, please provide a Plunker that allows to reproduce the issue.

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by sreejithkannur** [comment]
This syntax works for IE10

 System.import('app/boot').then(
           function(module){
               module.main(
                    {
                     name: 'xxxxxxxxxxxxx',
                        authentication: 'xxxxxxxxxxxxx'
                    });

             },
                   console.error.bind(console)

       );

**Comment by zoechi** [comment]
To me this looks more like a support question.
Please ask support questions using a dedicated support channel as explained in https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. We want to reserve GitHub issues for bug reports and feature requests only. Thanks!
