### ISSUE TITLE
Syntax proposal for Lazy loading components

### ISSUE THREAD

**Issue by DavidGangel** [angular/angular#9629]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[X ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Now in the router config you have to give the component name as a string to be able to load the component in a lazy way.
https://github.com/angular/angular/pull/8455

**Expected/desired behavior**
In the Java Spring framework we have a Class level annotation for tell the framework how a Bean should be loaded:
```
@Lazy(true) or @Lazy(false)
```
http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/context/annotation/Lazy.html

So instead of giving this information at the router level maybe would be better to mark the components with this kind of annotation.

**What is the motivation / use case for changing the behavior?**
Giving basically such an information as a String is a nightmare especially when things have to be refactored. 
 
* **Language:** [all]

**Comment by frederikschubert** [comment]
The problem with this proposal is that the code of the lazy loaded component has to be loaded in order to evaluate whether the component should be loaded lazily. This defies the sense of lazy loading.

**Comment by DavidGangel** [comment]
Okay I see the point. But in this case you have to download only the JS file. No template, no CSS and no component construction. The code is clear, it's clear when a component is lazy.
And you also have the possibility to prioritize the downloads for example:
1. I have components which are needed right now to display something (no lazy loading)
2. I have a component which I know it's highly likely that it will be needed very very soon (lazy loading with background pre-load as soon as all the no-lazy loading components are done)
3. I have a component which has for example 10% chance, that it will be needed at all (lazy loading without background loading)

**Comment by frederikschubert** [comment]
But this way one has to decide wether the component should be lazy or not at "compile" time. This means that the composite pattern angular enforces would be not as pure anymore.
Also apart from the difficulties implementing this I personally don't think there will be much performance gains by this approach.

**Comment by DavidGangel** [comment]
With the currently implemented approach in newnew router, AFAIK you also have to define this rule at compile time.

**Comment by frederikschubert** [comment]
Yes but it is independent from the component. My wording was bad. :)
The string is the easiest option to create a contract between the router/route configuration and the lazy loaded component without having direct references in their code.

**Comment by DavidGangel** [comment]
To be honest I don't feel that the laziness is a responsibility of the router at all. It's the responsibility of the DI/Ioc to correctly handle this.

**Comment by vicb** [comment]
@tbosch has a proposal for lazy loading. 

Tobias would you like to make further comment (do you have an issue tracking this ?)

**Comment by vsavkin** [comment]
We have landed support for lazy loading. Closing this issue.

**Comment by DavidGangel** [comment]
@vsavkin Can you please explain a bit more why did you close this? This was not about requesting the support of lazy loading.
