### ISSUE TITLE
Cannot load component from browser even after setting url rewrite

### ISSUE THREAD

**Issue by csfanse** [angular/angular#9630]
I am using angular 1.5 component and component routing with Typescript. I am not able to reload component after refresh. Before configuring URL rewrite, I was getting 404 error but after configuring URL rewrite, neither I am getting any error nor the component is loaded. I just get "blank" white screen after pressing F5. The application is configured in IIS and URL rewrite module for IIS is also installed. I investigated from inspect element and found that ng-outlet is not loaded.
Below is the configuration for URL rewrite in web.config.

     <rewrite>
      <rules>
        <rule name="angularjs routes" stopProcessing="true">
          <match url=".*" />
          <conditions logicalGrouping="MatchAll">
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
            <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
            <add input="{REQUEST_URI}" pattern="^/(Mdrx.CAL.API)" negate="true" />
          </conditions>
          <action type="Rewrite" url="/" />
        </rule>
      </rules>
     </rewrite>

If I set type="Redirect", it redirects to start page which is fine but does not work in case of "Rewrite"

What is the issues..?

**Comment by zoechi** [comment]
This repo is for Angular2. Angular.js is https://github.com/angular/angular.js
