### ISSUE TITLE
[Router 3.0.0-alpha.8] Using a child routing results in exceptions in both parent and child

### ISSUE THREAD

**Issue by Gallaecio** [angular/angular#9631]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**

I configure the following paths and get the following exceptions in the web console when I access those paths on a web browser:
* `/1`: `EXCEPTION: Error: Uncaught (in promise): Error: Cannot find primary outlet to load 'SomeOtherComponent'`
* `/1/2`: `EXCEPTION: Error: Uncaught (in promise): Error: Cannot match any routes: '2'`

**Reproduction of the problem**

I cannot get it "working" with Plunker even when opening it on a separate window, but I can reproduce the issue locally with a `main.ts`-only app:

        import { Component } from '@angular/core';
        import { bootstrap } from '@angular/platform-browser-dynamic';
        import { provideRouter, RouterConfig, ROUTER_DIRECTIVES } from '@angular/router';
        
        @Component({
            selector: 'app',
            template: "AppComponent <router-outlet></router-outlet>",
            directives: [ROUTER_DIRECTIVES]
        })
        class AppComponent {
        }
        
        @Component({
            template: "SomeComponent <router-outlet></router-outlet>"
        })
        class SomeComponent {
        }
        
        @Component({
            template: "SomeOtherComponent"
        })
        class SomeOtherComponent {
        }
        
        export const routes: RouterConfig = [
          { path: '1', component: SomeComponent, children: [
            { path: '2', component: SomeOtherComponent },
            { path: '', component: SomeOtherComponent }
          ] },
        ];
        
        bootstrap(AppComponent, [
            [
                provideRouter(routes)
            ]
        ])
        .catch(err => console.error(err));

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
* **Browser:** Firefox 47.0
* **Language:** TypeScript 1.8.10

**Keywords:** router, route, routes, children

**Comment by brandonroberts** [comment]
@Gallaecio since your `path: '1'` route is a parent, it needs ROUTER_DIRECTIVES also

**Comment by Gallaecio** [comment]
Many thanks, that indeed explains whe first exception.

After fixing that, though, the issue with `/1/2` remains.

Updated code:

        import { Component } from '@angular/core';
        import { bootstrap } from '@angular/platform-browser-dynamic';
        import { provideRouter, RouterConfig, ROUTER_DIRECTIVES } from '@angular/router';

        @Component({
            selector: 'app',
            template: "AppComponent <router-outlet></router-outlet>",
            directives: [ROUTER_DIRECTIVES]
        })
        class AppComponent {
        }

        @Component({
            template: "SomeComponent <router-outlet></router-outlet>",
            directives: [ROUTER_DIRECTIVES]
        })
        class SomeComponent {
        }

        @Component({
            template: "SomeOtherComponent"
        })
        class SomeOtherComponent {
        }

        export const routes: RouterConfig = [
          { path: '1', component: SomeComponent, children: [
            { path: '2', component: SomeOtherComponent },
            { path: '', component: SomeOtherComponent }
          ] },
        ];

        bootstrap(AppComponent, [
            [
                provideRouter(routes)
            ]
        ])
        .catch(err => console.error(err));

**Comment by brandonroberts** [comment]
I can't reproduce your second issue. Can you provide more information about your build setup?

**Comment by vicb** [comment]
Please provide a plunker and the exact steps to reproduce. Thanks

**Comment by Gallaecio** [comment]
I am using webpack. I recall following https://angular.io/docs/ts/latest/guide/webpack.html , but now I am not sure. I will review my webpack settings in case I messed something up there.

In the meantime, you can download my test project as a zip from https://drive.google.com/open?id=0B9VvotdtWBJXeUxzU2J3bmg3QmM and run `npm install` and then `npm start` to run it.

**Comment by Gallaecio** [comment]
Things work with SystemJS. I am closing this issue as it is obvious the issue is not in Angular.

I'll get back to you if I find out there is something to update in the documentation about using webpack with Angular.

Thanks for your prompt response!

**Comment by jeesim2** [comment]
@Gallaecio  Any new finding?
I have similar problem. http://stackoverflow.com/questions/38065353/2depth-value-in-path-angular2-routerconfig/38065539#38065539

**Comment by brandonroberts** [comment]
@Gallaecio I was able to replicate the issue with the link to the zip file you sent. If you change your `<base href=".">` to `<base href="/">` it works as intended.

**Comment by Gallaecio** [comment]
Thank you so much!

I had read somewhere that webpack required <base href="." /> for angular, but the documentation is fine, I must have read it somewhere else. I had explicitly changed it to / when testing SystemJS because of that, which is why that one worked. It would have taken me quite a while to figure that one out.

**Comment by Gallaecio** [comment]
This is where I read about `<base href=".">`: https://angular.io/docs/ts/latest/guide/router.html#!#base-href (I was mistaken thinking it was in a webpack article)

**Comment by bastienJS** [comment]
@brandonroberts "since your path: '1' route is a parent, it needs ROUTER_DIRECTIVES also" maybe it`s still a bug. I am bootstrapping the export const APP_ROUTER_PROVIDERS = [
  provideRouter(routes)
]; then it should not be needed that each component needs a directive:[ROUTER_DIRECTIVES] If that is true, then there is a bug because my parent had no ROUTER_DIRECTIVES set and suddenly I got the known "Cannot find primary outlet " error.

**Comment by brandonroberts** [comment]
@bastienJS I'm not following. ROUTER_DIRECTIVES has always been required in the component where there is a `<router-outlet></router-outlet>`

**Comment by bastienJS** [comment]
@brandonroberts so its not possible to bootstrap the ROUTER_DIRECTIVES globally? I could swear that worked with one of the older routers...

**Comment by brandonroberts** [comment]
@bastienJS yes, you can add the ROUTER_DIRECTIVES to PLATFORM_DIRECTIVES, but that's not included at the moment

**Comment by bastienJS** [comment]
@brandonroberts  I did it that way and it works! Just bootstrap it: provide(PLATFORM_DIRECTIVES, { useValue: [ROUTER_DIRECTIVES], multi: true })

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20781491/33757c86-b7be-11e6-923a-176a88565704.png)
![Uploading 图片.png…]()
