### ISSUE TITLE
Route 3.0.0-alpha.8 : Alternative for useAsDefault of RouteConfig 2.x 

### ISSUE THREAD

**Issue by jeesim2** [angular/angular#9632]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

Hi.

'useAsDefault' property of Route in 2.x is not available as of 3.0.0-alpha3

#### RouteConfig 2.x
```
@RouteConfig([
    {path: '/service/demo/...', name: 'App', component: App, useAsDefault: true},
    {path: '/service/:serviceId/...', name: 'App', component: App}
])
```
* so, When user connected http://x.y.z/, I redirected to /service/demo by 'useAsDefault'

#### RouterConfig 3.x
```
export const appRoutes: RouterConfig = [
    {path: '/service/demo/...', name: 'App', component: App},
    {path: 'service/:serviceId/...', component: App, terminal:true}
]
```
* how can I do that with Router v3 ?

**Comment by zoechi** [comment]
Use `path: '', redirectTo: 'xxx', terminal: true`

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by jeesim2** [comment]
@zoechi my apologies, and appreciate for the response.
