### ISSUE TITLE
Angular 2 http get request can´t access data 

### ISSUE THREAD

**Issue by minas15** [angular/angular#9633]
Hi 

I can´t read the data (test) outside the http request.
`//component

clickEvent(event){
     
       event.preventDefault();
       this._httpService.getData(someValue)
            .subscribe(
                data => this.test=data,
                error => alert(error)    
            ); 

     //here the this.test is undefined!!
      console.log(this.test);
}

//httpService

  getData(searchParams: any):Observable<Person>{
        this.params.set('firstName', searchParams.firstName);
        this.params.set('lastName', searchParams.lastName);

        
        return this._http.get(this.url, 
                            { search:this.params })
                            .map(response => response.json())
                            .catch(this.handleError);
    }`

i dont´t know how the asynchorn call works in Angular 2. Is there a possiblility to call a anonym function?
thx in advance

**Comment by pkozlowski-opensource** [comment]
@minas15  pleas ask support questions using a dedicated support channel as explained in https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. We want to reserve GitHub issues for bug reports and feature requests only. Thnx!
