### ISSUE TITLE
[Router 3.0.0-alpha.8] redirectTo puts parentheses in URL, breaking child routes

### ISSUE THREAD

**Issue by DanielMcAssey** [angular/angular#9634]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When navigating to a route that has a redirectTo, it redirects to the correct page but puts parentheses around the navigated to page, breaking all further child routes on that page.

Address bar: ![Address Bar](https://cloud.githubusercontent.com/assets/3080979/16376793/28c4085a-3c5a-11e6-80b1-8b163645b607.png)
URL of anchor: ![Anchor Link](https://cloud.githubusercontent.com/assets/3080979/16376776/09ef2608-3c5a-11e6-81bd-d1287bc65ccf.png)
Console on clicking Anchor link leading to a child route: ![Console](https://cloud.githubusercontent.com/assets/3080979/16376800/39365634-3c5a-11e6-83e4-53346162e0bb.png)
Redirect Route: ![Redirect Route](https://cloud.githubusercontent.com/assets/3080979/16376819/4c8667f6-3c5a-11e6-8880-2bf1a815abba.png)

**Expected/desired behavior**
The redirectTo route should redirect to the correct route without parentheses, maintaining the correct child routes and not breaking navigation.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
 
* **Browser:** all
 
* **Language:** TypeScript 1.8

**Comment by zoechi** [comment]
This needs a Plunker to reproduce.

**Comment by DanielMcAssey** [comment]
Here you go: http://plnkr.co/edit/FooCFQybzcTDxuKHB23x?p=preview as you can see in the console its the same type of error

**Comment by ericmartinezr** [comment]
`redirectTo: '/crisis-center',` => `redirectTo: 'crisis-center',`, no slash.

**Comment by dchecherynda-softheme** [comment]
I don't use slashes and have the same issue.

**Comment by DanielMcAssey** [comment]
As you can see in my image that I posted I dont use a slash either.

**Comment by ericmartinezr** [comment]
The whole point of the plnkr is to reproduce your error. The plnkr you shared had another issue, which doesn't make sense...

**Comment by DanielMcAssey** [comment]
There's no slash on the plnkr either, your example one is incorrect, the only thing I changed was the crisis-center.routes.ts and added a redirect to list

**Comment by ericmartinezr** [comment]
YOU are the one that has to reproduce the error in the plnkr dude, seriously. The one you posted had that issue and I fixed it, and for what you said that's not your issue, so why in the hell did you make it... Make a plnkr reproducing your actual issue... sigh...

>Here you go: http://plnkr.co/edit/FooCFQybzcTDxuKHB23x?p=preview as you can see in the console **its the same type of error**

So the plnkr is not reproducing your issue, but something similar...

>There's no slash on the plnkr either

seriously?... Is that some kind of joke? http://image.prntscr.com/image/90bc379bc78245c293b75a7ddffa2847.png

> your example one is incorrect

That may be because your plnkr is incorrect, sigh...

Trying to help you like for the 10th time... make a plnkr reproducing your ACTUAL issue, like the one in the image (the image it's not a reproduction).

**Comment by DanielMcAssey** [comment]
Chill dude, I said I reproduced it in the plunkr, but the one you fixed was not the problem I was having, the problem you mentioned was not my problem in the plunkr.

> seriously?... Is that some kind of joke? http://image.prntscr.com/image/90bc379bc78245c293b75a7ddffa2847.png

I meant theirs no slash in the code I changed in the plunkr, did you even test your changes on that plunkr? Its still broke.

**Comment by zoechi** [comment]
@DanielMcAssey What Plunker link does now reproduce your issue exactly?

**Comment by about-code** [comment]
I can confirm the issue. It wasn't present in router.alpha7 and must have been introduced on the way to router.alpha8. I have observed it appearing with a router config similar to the following:

```typescript
export var routes: RouterConfig = [
    { path: 'home', component: HomeComponent, children: [
        { path: '', redirectTo: 'test', terminal: true},
        { path: test, component: TestComponent}
    ]},
]
```
I can't tell if its the child-routes or `redirectTo` but if @DanielMcAssey has observed it with `redirectTo` I tend to think it may be related to that.

**Comment by MaximilianWiedemann** [comment]
I have encoutered this problem with paranthesis in the URL when being redirected as well. However, it doesn't break child routes for me. It just looks weird in the address bar.

And as a sidenote: If you nest routes more than once, it will get even worse because it is wrapped in parantheses multiple times, like:
`example.com/app/(child-a/(child-a-1))`

**Comment by bjorneven** [comment]
This is also present for me, with multiple redirects down to child routes that ends up with nested parentheses.
`export const routes :RouterConfig = [
        {
        path: 'parent',
        component: ParentRouter,
        canActivate: [MyUserGuard],
            children: [
                {path:'', redirectTo: 'child1'},
                {path:'child1', component:Child1Router,
                    children: [
                        {path: '', redirectTo:'list',terminal:true},
                        {path: 'list', component: Child1ListPage}
                    ]
                }
            ]
        }
];
`

**Comment by vsavkin** [comment]
The PR fixing the issue: https://github.com/angular/angular/pull/9708

**Comment by ialex90** [comment]
ey,

I am working with angular v4 and routing v4 too, latest version 4.0.3 and I got this parenthesis problem right now :S However, the routing works and the components get loaded but it's not the expected behavior
