### ISSUE TITLE
Bindings on a srcset attribute are sanitized as regular URLs.

### ISSUE THREAD

**Issue by rjamet** [angular/angular#9638]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

`<img [srcset]="v">` with `v='http://x.y.z 1x, javascript:foo() 2x'` is only sanitized as a whole, not as two different URLs.

**Expected/desired behavior**

Should be sanitized to `srcset="http://x.y.z 1x, unsafe:javascript:foo() 2x"`.

**Reproduction of the problem**

http://plnkr.co/edit/4YnPN4H7TEcEScY2Stto?p=preview

**What is the expected behavior?**

sanitization of all parts.

**What is the motivation / use case for changing the behavior?**

There's probably no risk of XSS, since srcset is a HTML5 tag, and only old browsers runs js in img srcs. However, that's still an URL, so if someone relies on a custom sanitizer for one thing or another, this will slip though. I don't think there's any hurry to fix this, though.

**Comment by cyrilletuzi** [comment]
#9572 adds a special srcset sanitizer, there is just to add a new special security context that uses it. I'll take a look on that this week.

**Comment by mprobst** [comment]
I'm not super convinced about implementing this. It seems like it doesn't really fix anything, and it'll increase API surface for all users (`SecurityContext`, `SafeValue`). @rjamet, WDYT?

**Comment by rjamet** [comment]
Same thoughts. I can imagine projects trying to ban all external resource loading through that mechanism, but that's unlikely. Keep the issue documented, and reconsider if someones comes with a good use-case ?

**Comment by mprobst** [comment]
I think if we don't plan to actually fix this, let's just close it and keep the issue tracker clean. We can keep it in the back of our heads in case it comes up, but I don't really expect that.
