### ISSUE TITLE
dynamic form performance problem

### ISSUE THREAD

**Issue by cuiliang** [angular/angular#9639]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have created a dynamic form component following the method in the cookbook. 
If I create 1000 input controls, my new thinkpad P70 with XEON cpu will need about 6 seconds to show the form.  And I can feel slow when input into the form.
![image](https://cloud.githubusercontent.com/assets/1972649/16384807/f82aa3d0-3cbc-11e6-8641-85658306f062.png)

**Expected/desired behavior**

**Reproduction of the problem**
code can be found here: https://github.com/cuiliang/ngsample

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
@angular/forms 0.1.1

**Comment by vicb** [comment]
Could you  please provide a plunker. Thanks.

**Comment by cuiliang** [comment]
@vicb  
finally I get the sample run on plunker: http://plnkr.co/edit/ptchAj?p=preview

**Comment by cuiliang** [comment]
angular version changed, maybe not valid now.
