### ISSUE TITLE
@EventEmitter Requires Type

### ISSUE THREAD

**Issue by Xesued** [angular/angular#965]
Not sure if this is a bug or not.  I have a Component called PickList and if I don't type the EventEmitter it, I get this error:
`Cannot resolve all parameters for PickList -> Failed to compile MyAppComponent`

```javascript
// works
constructor(@EventEmitter('changed') changer:Function){/*..*/}

// Breaks and shows the error:
constructor(@EventEmitter('changed') changer){/*..*/}
```

**Comment by mlaval** [comment]
The same error is happening for `@PropertySetter` and `@Attribute` when the type is not set.

**Comment by pkozlowski-opensource** [comment]
Yeh, I can see this with the latest master as well. Looking into it.
