### ISSUE TITLE
compiling files with exports of default nonamed function fails

### ISSUE THREAD

**Issue by aquinum6** [angular/angular#9650]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report
[ ] feature request
```

**Current behavior**

When .ts file exports default no named function there is an following error occurring:

> TypeError: Cannot read property 'text' of undefined

**Expected/desired behavior**

I'm not 100% sure but no named function should not have metadata. In that case they can be just omitted during exporting metadata from file.

**Please tell us about your environment:**

@angular RC3, tsc-wrapped 0.2.0

**My fix**
file: node_modules/@angular/tsc-wrapped/src/collector.js (line: 148):

```
case ts.SyntaxKind.FunctionDeclaration:
  // Record functions that return a single value. Record the parameter
  // names substitution will be performed by the StaticReflector.
  if (node.flags & ts.NodeFlags.Export) {
    var functionDeclaration = node;

    //Changed
    //Allow false value in case if function has no name
    var functionName = functionDeclaration.name?functionDeclaration.name.text:false;

    var functionBody = functionDeclaration.body;

    //Changed
    //Updated if statement
    if (functionName && functionBody && functionBody.statements.length == 1) {
      var statement = functionBody.statements[0];
      if (statement.kind === ts.SyntaxKind.ReturnStatement) {
        var returnStatement = statement;
        if (returnStatement.expression) {
          if (!metadata)
            metadata = {};
          metadata[functionName] = {
            __symbolic: 'function',
            parameters: namesOf(functionDeclaration.parameters),
            value: evaluator.evaluateNode(returnStatement.expression)
          };
        }
      }
    }
  }
  // Otherwise don't record the function.
  break;
```

**Comment by qdouble** [comment]
I'm dealing with this bug as well, using default exports causes build to fail...which is especially bad in my case as I have a whole lot of files that use default exports, so I'd have to rewrite the app just for it to be able to compile. Any milestones on addressing this issue?

**Comment by tbosch** [comment]
Hello, is this still an issue?

**Comment by chuckjaz** [comment]
This cannot be reproduced with `2.0+` of TypeScript as it always supplies a name and, as we only support `2.0+` this is no longer an issue.
