### ISSUE TITLE
Angular1_router | How to unit test code insdie $canActivate hook

### ISSUE THREAD

**Issue by pranav-xx** [angular/angular#9656]
I am submitting this to check what is the recommended way to uni test code inside $canActivate.

I am currently using angular1_router with angular js 1.5. While all other lifecycle hooks are written inside controller, I can unit test them.

But since $canActivate is part of component configuration inside an IIFE, how to unit test it?

**Comment by zoechi** [comment]
This repo is for Angular2. Angular.js is https://github.com/angular/angular.js but this sounds like a support question and GitHub issues are reserved for issues in Angular.js as well AFAIK.

**Comment by Awk34** [comment]
@zoechi he's talking about this: https://github.com/angular/angular/tree/master/modules/angular1_router

**Comment by zoechi** [comment]
I see, sorry for the noise.

**Comment by zoechi** [comment]
It still looks like a support question though.

**Comment by pranav-xx** [comment]
Please let me know where to raise this. I thought this is the right forum to ask this question.

**Comment by zoechi** [comment]
@pranav-xx https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
