### ISSUE TITLE
[Question] Html element/component based on variable value

### ISSUE THREAD

**Issue by jaroslawziolkowski** [angular/angular#9657]
Hello,
sorry that here but in others places nobody couldn't answer me.

Doeas is possible and how use directive in template or html element something like

```
let myvar = ''div";
let component = ''my-component";
<{{myvar}}></{{myvar}}>
<{{component}}></{{component}}>
```
of course I know that pseodo code above is incorrect but I can't find information how should I use it correctly.

Thanks for help in advance.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
 
* **Browser:** all 
 
* **Language:** TypeScript

**Comment by zoechi** [comment]
This is not supported. The selector of components and directives has to match statically added tags, attributes, classes, or ids.

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)
