### ISSUE TITLE
Add support for property injection

### ISSUE THREAD

**Issue by stalniy** [angular/angular#9658]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Possible to inject dependencies only through constructor which leads to useless, repetitive constructor implementation almost in every class. 

**Expected/desired behavior**
Add support (or way to make it via plugin) to inject dependencies to properties. 

**What is the expected behavior?**
```js
class Car {
  @Inject(Engine) engine;

  ngOnitInit() {
    console.log(this.engine);//instantiated
  }
}
```

**What is the motivation / use case for changing the behavior?**
Reduce amount of useless constructors. Existing plugin for Aurelia: https://www.npmjs.com/package/aurelia-property-injection

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart]

**Comment by zoechi** [comment]
Similar to #6972
https://plnkr.co/edit/1RFE6BUA6UUmwYhPwTne?p=preview at least shows the same "Get Microsoft Silverlight" link for me as I get when I run the embedded snipped in your SO question.

**Comment by vicb** [comment]
We have no plan to implement this feature.

**Comment by avarabei** [comment]
@vicb why not, this will help to simplify constructors for inherited components. in my case I have to specify injection in each derivative regardless of whether it is used in it or not, but just because only base class requires it.

**Comment by trotyl** [comment]
> in my case I have to specify injection in each derivative regardless of whether it is used in it or not

You don't need to do that for a long time. https://github.com/angular/angular/commit/f5c8e0989d85bc064f689fc3595207dfb29413f4

**Comment by avarabei** [comment]
@trotyl, but this is only for the case when the derivative class does not resolve more than what parent class needs.
