### ISSUE TITLE
Issues with using colon as value in ng2 rc3

### ISSUE THREAD

**Issue by sundriver** [angular/angular#9659]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

...
 {
    path: 'relationships/:idValue',
    component: RelationshipsComponent
  }
...

// I want to navigate to /relationships/ab:cd but ng2 navigates to /relationships/cd instead

this.router.navigate(['/relationships', 'ab:cd' ]); 

**Expected/desired behavior**

navigating to /relationships/ab:cd

**Reproduction of the problem**

if the route parameter value contains colon, the router doesn't correctly navigate as shown above.

**What is the expected behavior?**

correctly routing to /relationships/ab:cd

**What is the motivation / use case for changing the behavior?**

Bug

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X

2.0.0-rc3
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
I've tried only on Chrome 51

* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart] 

TypeScript

**Comment by zoechi** [comment]
Cross-ref http://stackoverflow.com/questions/38066659/issues-with-using-colon-as-value-in-ng2

**Comment by rafikk** [comment]
I've also got colons in URL paths that are now breaking with the new router. Looking at the source, this is very intentional behavior: https://github.com/angular/angular/blob/72544ba55113a652b2452f2ce5bb0fca576a1344/modules/%40angular/router/src/create_url_tree.ts#L134

What's the motivation for splitting path segments on colons? I wasn't able to find anything going through blame or pull requests.

**Comment by rafikk** [comment]
FYI, as a workaround in the meantime, you can create the URL yourself and use router.navigateByUrl.
