### ISSUE TITLE
Unable to load Silverlight when embedded in a component

### ISSUE THREAD

**Issue by hem19** [angular/angular#9660]
**I'm submitting a ...** 
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When embedding and loading Silverlight.xap directly inside an HTML page, it works fine. But when we move same code inside a component, it won't load the Silverlight. DOM in both cases, i.e. embedding and loading through HTML and through component, doesn't show any difference.

**Expected/desired behavior**
Embedding and loading Silverlight component should have same behavior irrespective of loading through HTML or through component. 

**What is the motivation / use case for changing the behavior?**
We are migrating our Silverlight application to Angular2. As complete migration will take months, we are keeping some of the silverlight modules as well.

**Attachment app folder
[app.zip](https://github.com/angular/angular/files/336386/app.zip)

Code for loading silverlight component is in silverlight-app.component.html file. When we load this file directly in Internet Explorer, it loads the silverlight and works fine. But when we load index.html, it won't work

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
 
* **Browser:** IE 10 
 
* **Language:** TypeScript 1.8.10

**Comment by zoechi** [comment]
Can you please post some code how you add Silverlight to HTML directly, so it's not necessary to download the zip?

**Comment by zoechi** [comment]
Cross-ref http://stackoverflow.com/questions/38069230/unable-to-load-silverlight-in-angular2-when-embedded-in-a-component

**Comment by pkozlowski-opensource** [comment]
Sounds like a support question for which we don't have reproduce scenario. Closing for now.
