### ISSUE TITLE
[animation] : Animate from CURRENT style, not state style, whilst TRANSITIONING

### ISSUE THREAD

**Issue by dharders** [angular/angular#9661]
**I'm submitting a ...** 

```
[ ] bug report
[x] feature request
```

**Current behavior**

When a user defined animation state changes from 'open' -> 'closed' -> 'open' before the 'closed' animation is complete, it results in a FULL 'closed' to 'open' transition. It is jarring, as the styles jump very harshly.

**Expected/desired behavior**

I would expect the styles to transition back towards the 'open' state styles from their CURRENT styling. Eg.  Opacity 1 initially, starts to fade out (due to 'closed' state assignment), but before completely fades out, say Opacity 0.4, the 'open' state assignment occurs and the opacity begins making it's way back to 1 **from opacity: 0.4** (not 0).

**Reproduction of the problem**

[See this Plunker](http://plnkr.co/edit/09YeQa?p=preview)

**What is the motivation / use case for changing the behavior?**

Reduce harsh style jump / jarring on state change while an animation is already in flight. It was existing behaviour of the `animationBuilder.css().setToFromStyles()` from the old animation API. Currently there is no documentation with this feature (although it was the default behaviour previously).

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.4
- **Browser:** Chrome 51.0.2704.106 m
- **Language:** TypeScript 1.9.0-dev.20160409 with plugin-typescript@4.0.10 (see plunker)

cc @matsko

**Comment by dharders** [comment]
**Animation Setup**

```
@Component({
  animations: [
    trigger("fadeInOut", [
      state("open", style({opacity: 1})),
      state("closed", style({opacity: 0})),
      transition("open <=> closed", animate( "3000ms" )),
    ])
  ],
  template: `
    <div @fadeInOut="state"></div>
    <a (click)="beginAnim()">Toggle State</a>
  `
})
export class App {
  state = 'open';  
  beginAnim() {
      this.state = this.state === 'open' ? 'closed' : 'open';     // kickstart animation
  }
}
```

**Comment by dharders** [comment]
As I understand it 
```typescript
style({opacity: '*'})
```
computes the opacity from the static opacity value, i.e the value if animations weren't present. eg. from `@Component({styles: [...]})` or an external style sheet. @matsko Can you please confirm ?

**Proposal**

Provide an additional reserved character for the CURRENT style value. i.e. something like 

```typescript
style({opacity: '$'})
```

which would compute the actual opacity value at the time of 'state' change. i.e. it would fix the jarring issue for 'state' changes while previous animations were still _'in flight'_.

**Comment by dharders** [comment]
Greensock [GSAP](http://greensock.com/) animation does exactly that. With their `TweenMax.to()` API. It animates from **current** position.

Their `TimelineMax` API has some great features like `reverse()`, `pause()` etc that I also hope are coming to Angular 2. But for now...animating from **current** position is my top priority @matsko

**Comment by matsko** [comment]
Me and @ThomasBurleson will work on this one.

**Comment by jerradpatch** [comment]
This might solve my issue as well. I have a case where the width of a '<div>' is set by media queries (bootstrap grid), and I am changing that width by hovering over the element (adding/removing columns). I was going to suggest a feature where 'styles' could use classes instead of just listing properties to animate, but I think this might be better. Where I could use '$' => * to tell the animation to go from current width to the new width.

Also, explained that because I am open to suggestions on how to fix my issue with the current implementation of ng2.

**Comment by matsko** [comment]
This feature is coming and it will be fully automatic. We are just waiting on the web workers PR to go in first.

Feature: https://github.com/angular/angular/pull/12208
Web Workers: https://github.com/angular/angular/pull/12656

**Comment by Delagen** [comment]
How to use it? It still animate from something initial state.

**Comment by matsko** [comment]
@Delagen This now happens automatically when an animation is interrupted within the same trigger. No change in your code.

**Comment by Delagen** [comment]
@matsko But how to make transition to start from current styling? NOT state from last transition.

**Comment by matsko** [comment]
What happens now (with 2.3) is that if an animation is interrupted midway it will take a snapshot of all the styles that have already been applied or are currently being animated, merge that together with the starting state styles and pass that in as styling for the first frame of the animation.

In regards to what you're asking, I need some clarification. By `current styling` are you asking how to animate from the styling that present on the element during the interruption of the animation minus the starting styles of the newly assigned starting state? Or are you asking about how to use that have been applied as inline styles on the element outside of how animation triggers apply styles?

**Comment by matsko** [comment]
This also will work automatically with the soon-to-come `query()` feature.
