### ISSUE TITLE
[Router 3.0.0-alpha.8] Missing Router constructor in router.d.ts

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#9665]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

We can't create a new router (for example in a test) like we used to with router v1 and v2

`new Router(AppComponent, resolver, urlSerializer, outletMap, location, injector, testConfig)`
throws
`error TS2346: Supplied parameters do not match any signature of call target`

**Expected/desired behavior**

We should be able to build a new router, if the Router constructor is added back to the typings.

* **Angular version:** 2.0.0-rc.3 - router 3.0.0-alpha.8
 
* **Browser:** [all] 
 
* **Language:** [TypeScript]

**Comment by vsavkin** [comment]
Fixed here https://github.com/angular/angular/commit/3784696b9e5bf3709558be0f2766a82af2e032b1
