### ISSUE TITLE
Look at my Framework

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [angular/angular#9666]
https://github.com/uMaxmaxmaximus/ui-js/tree/master/modules/ui-js

in my framework work this 

```javascript
template = `
<my-component *for='item in arr'></my-component>
`
```
as I recall, angular 2 does not support this, and I can tell you how I implement it. You want to i help council)?

Actually my framework support even `<content selector=''></content>` in component templates

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests.
Please use other channels for general discussions like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)
