### ISSUE TITLE
Data binding is not working for next route

### ISSUE THREAD

**Issue by shanthan-arepuri** [angular/angular#9667]
I'm working on Angular2-Meteor, When i use routing inside the meteor account methods data binding is not working for the next route. But when i reload the page using refresh button data binding is working fine.

Below is the code on the client side:

Meteor.loginWithPassword({email:this.usernameCtrl.value},this.passwordCtrl.value,(error,result)=> {
if(error) {
console.log(error);
} else {
this.router.navigate(['Dashboard']);
}
});

Please help me with the work arounds.

**Comment by zoechi** [comment]
If you are reporting an issue please fill the template and provide a Plunker to reproduce.

  - GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by vicb** [comment]
As @zoechi mentioned the issue tracker is for Angular defects and need a repro.
