### ISSUE TITLE
Hour formatting

### ISSUE THREAD

**Issue by jrmoser** [angular/angular#9671]
**I'm submitting a** 
[x] bug report
[ ] feature request

**Current behavior**
Current docs suggest that the hour formatting has 3 options j,h and H where j is supposed to represent 24 hour format? h is supposed to be with am/pm format? and H is supposed to be 24 hour format... again. In practice however it seems that the j is with AM/PM and h is 12 hour format without AM/PM.

Also when attempting to format j (or h whichever really is the am/pm) with minutes or seconds the AM/PM comes directly after the hour

**Expected/desired behavior**
am/pm should come after minutes and seconds

alternatively let us decide where the am/pm is supposed to be at, also I think j is superfluous, make it so that j simply represented am/pm and jj AM/PM for example:

{{today | date:'hh:mm:ss jj'}} could evaluate to 04:05:06 AM
{{today | date:'hh:mm:ss j'}} could evaluate to 04:05:06 am
{{today | date:'h:mm:ss jj'}} could evaluate to 4:05:06 AM

**Reproduction of the problem**
[Plunker for current behaviour](http://plnkr.co/edit/6e6RYKPXlTOiwHzKCZ87?p=preview) using chrome as suggested in the docs to avoid any issues

**What is the expected behavior?**
That the hour formatting has the am/pm at the end or gives us more control of where it should be at

**What is the motivation / use case for changing the behavior?**
When making custom formats for the date and time, personally I want the day of the week to be displayed along with the day of the month and the time and there isn't a predefined format for that

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
 
* **Browser:** Chrome 51.0.2704.103
 
* **Language:** TypeScript 1.8.10

**Comment by laskoviymishka** [comment]
As far as I know j represent current locale hour formatting. I.e. for US it will be am/pm. Desired behavior looks more like new feature imho.

**Comment by kemsky** [comment]
`a` - am/pm marker.

**Comment by jrmoser** [comment]
@kemsky Genius!! That does make it available for me to format the way I want it. So if it is a lac of documentation I think I shall just close the issue then.
