### ISSUE TITLE
[Question / Bug] - Cannot assigne value to component attribut inside service subscription.

### ISSUE THREAD

**Issue by stidiovip** [angular/angular#9677]
I'm facing a strang trouble with ts in angular2 rc3 componant.

I want to assign the outpout of the service to an attribut. But that is not working at all.
The line not working.
```
this.trackers = trackers; 
```

Here is my comple code.
```
  /**
  * Returns a list of Tracker
  * @param {user} : the user id
  * @returns Tracker
  */
  getTrackers(user: number){
    this.trackerService.getTrackersOf(user).subscribe(trackers => {
      this.trackers = trackers; // this.trackers is not assignable
      if (this.trackers.length > 0){
        // the default selected tracker is the first one
        this.setTracker(trackers)

        // update locations
        this.getLocations(this.tracker);
      }
      
    }, error => this.failure(error));
  }

 /**
  * implementation of the ngOnInit function
  */
  ngOnInit() {
    // Get user id from the location path
    this.subscribtion = this.route.params.subscribe(params => {
        let user = +params['user']; //(+) converts string 'id' to a number
        this.getTrackers(user);
      });
  }

  /**
   * The destroy hook
   */
  ngOnDestroy() {
    this.subscribtion.unsubscribe();
  }

```

**Current behavior**

Not assigning the value.

**Expected/desired behavior**

Assigne the value

**Reproduction of the problem**

Create a componant

**What is the expected behavior?**

Assigne de resultat to the attribute.

**What is the motivation / use case for changing the behavior?**

Inside service suscription.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
 
* **Browser:** [all | Chrome XX ] 
 
* **Language:** [all | TypeScript 1.8.10]

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) for support request.

**Comment by stidiovip** [comment]
Okay, thank u.
