### ISSUE TITLE
Angular 2 Router issue with platform-browser.umd.js cannot match any routes ''

### ISSUE THREAD

**Issue by vijender1256** [angular/angular#9679]
I am having issues with Angular 2 routing: Routing works but I see errors in Console and also when I refresh my page I lose routing and I get Angular 404  not found, here are my files

Index.html , this is what i am referencing

  ` 
    <script src="node_modules/core-js/client/shim.min.js"></script>
    <script src="node_modules/zone.js/dist/zone.js"></script>
    <script src="node_modules/reflect-metadata/Reflect.js"></script>
    <script src="node_modules/systemjs/dist/system.src.js"></script>
`

app.routes.ts:

`import { provideRouter, RouterConfig } from '@angular/router';

import { CrisisListComponent }  from './crisis-list.component';
import { HeroListComponent }    from './hero-list.component';

export const routes: RouterConfig = [
    { path: 'crisis-center', component: CrisisListComponent },
    { path: 'heroes', component: HeroListComponent }
];

export const APP_ROUTER_PROVIDERS = [
    provideRouter(routes)
];
`

systemjs.config.js :

`/**
 * System configuration for Angular 2 samples
 * Adjust as necessary for your application needs.
 */
(function (global) {
    // map tells the System loader where to look for things
    var map = {
        'app': 'app', // 'dist',
        '@angular': 'node_modules/@angular',
        'angular2-in-memory-web-api': 'node_modules/angular2-in-memory-web-api',
        'rxjs': 'node_modules/rxjs'
    };
    // packages tells the System loader how to load when no filename and/or no extension
    var packages = {
        'app': { main: 'main.js', defaultExtension: 'js' },
        'rxjs': { defaultExtension: 'js' },
        'angular2-in-memory-web-api': { main: 'index.js', defaultExtension: 'js' },
    };
    var ngPackageNames = [
      'common',
      'compiler',
      'core',
      'http',
      'platform-browser',
      'platform-browser-dynamic',
      'router-deprecated',
      'upgrade'
    ];
    // Individual files (~300 requests):
    function packIndex(pkgName) {
        packages['@angular/' + pkgName] = { main: 'index.js', defaultExtension: 'js' };
    }
    // Bundled (~40 requests):
    function packUmd(pkgName) {
        packages['@angular/' + pkgName] = { main: '/bundles/' + pkgName + '.umd.js', defaultExtension: 'js' };
    }
    // Most environments should use UMD; some (Karma) need the individual index files
    var setPackageConfig = System.packageWithIndex ? packIndex : packUmd;
    // Add package entries for angular packages
    ngPackageNames.forEach(setPackageConfig);

    // No umd for router yet
    packages['@angular/router'] = { main: 'index.js', defaultExtension: 'js' };

    var config = {
        map: map,
        packages: packages
    };
    System.config(config);
})(this);`

Main.ts file:

`/// <reference path="../typings/index.d.ts" />

import { bootstrap }            from '@angular/platform-browser-dynamic';
import { AppComponent }         from './app.component';
import { APP_ROUTER_PROVIDERS } from './app.routes';

bootstrap(AppComponent, [
    APP_ROUTER_PROVIDERS
])
    .catch(err => console.error(err));`

app.component.ts file:

`import { Component } from '@angular/core';
import { ROUTER_DIRECTIVES } from '@angular/router';

@Component({
    selector: 'my-app',
    template: `
    <h1>Component Router</h1>
    <nav>
      <a [routerLink]="['/crisis-center']">Crisis Center</a>
      <a [routerLink]="['/heroes']">Heroes</a>
    </nav>
    <router-outlet></router-outlet>
  `,
    directives: [ROUTER_DIRECTIVES]
})

export class AppComponent { }`

And Here is the error I am getting :

![image](https://cloud.githubusercontent.com/assets/12258728/16428109/62c89540-3d3e-11e6-9c6a-592ca625aa5b.png)

Any help appreciated :)

**Comment by vicb** [comment]
When opening an issue:
- please fill out the required info from the template,
- provide a plunker.

Thanks

**Comment by vijender1256** [comment]
@vicb I dont have access to plunker at office its blocked :( and also what is the required info I am missing  I thought I provided all my files in the issue. Can you please suggest what am I supposed to do now, seems like you closed the issue without any help.
