### ISSUE TITLE
RC3 loading app compiler.umd.js parse error

### ISSUE THREAD

**Issue by sdanielspq** [angular/angular#9682]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Loading app and received generic browser error:

Error: @http://localhost:3001/app/main.js:3:34
	@http://localhost:3001/app/main.js:1:31
	@http://localhost:3001/app/main.js:1:2
	Zone</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:3001/lib/zone.js:323:20
	Zone</Zone</Zone.prototype.run@http://localhost:3001/lib/zone.js:216:25
	scheduleResolveOrReject/<@http://localhost:3001/lib/zone.js:571:53
	Zone</ZoneDelegate</ZoneDelegate.prototype.invokeTask@http://localhost:3001/lib/zone.js:356:24
	Zone</Zone</Zone.prototype.runTask@http://localhost:3001/lib/zone.js:256:29
	drainMicroTaskQueue@http://localhost:3001/lib/zone.js:474:26
	ZoneTask/this.invoke@http://localhost:3001/lib/zone.js:426:22
	EventListener.handleEvent*scheduleEventListener@http://localhost:3001/lib/zone.js:838:13
	Zone</ZoneDelegate</ZoneDelegate.prototype.scheduleTask@http://localhost:3001/lib/zone.js:336:22
	Zone</Zone</Zone.prototype.scheduleEventTask@http://localhost:3001/lib/zone.js:276:21
	zoneAwareAddEventListener@http://localhost:3001/lib/zone.js:889:6
	addEventListener@http://localhost:3001/lib/zone.js line 982 > Function:1:43
	patchProperty/desc.set@http://localhost:3001/lib/zone.js:774:14
	ZoneAwarePromise@http://localhost:3001/lib/zone.js:584:30
	Zone</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:3001/lib/zone.js:323:20
	Zone</Zone</Zone.prototype.run@http://localhost:3001/lib/zone.js:216:25
	scheduleResolveOrReject/<@http://localhost:3001/lib/zone.js:571:53
	Zone</ZoneDelegate</ZoneDelegate.prototype.invokeTask@http://localhost:3001/lib/zone.js:356:24
	Zone</Zone</Zone.prototype.runTask@http://localhost:3001/lib/zone.js:256:29
	drainMicroTaskQueue@http://localhost:3001/lib/zone.js:474:26
	EventListener.handleEvent*scheduleEventListener@http://localhost:3001/lib/zone.js:838:13
	Zone</ZoneDelegate</ZoneDelegate.prototype.scheduleTask@http://localhost:3001/lib/zone.js:336:22
	Zone</Zone</Zone.prototype.scheduleEventTask@http://localhost:3001/lib/zone.js:276:21
	zoneAwareAddEventListener@http://localhost:3001/lib/zone.js:889:6
	addEventListener@http://localhost:3001/lib/zone.js line 982 > Function:1:43
	patchProperty/desc.set@http://localhost:3001/lib/zone.js:774:14
	ZoneAwarePromise@http://localhost:3001/lib/zone.js:584:30
	Zone</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:3001/lib/zone.js:323:20
	Zone</Zone</Zone.prototype.run@http://localhost:3001/lib/zone.js:216:25
	scheduleResolveOrReject/<@http://localhost:3001/lib/zone.js:571:53
	Zone</ZoneDelegate</ZoneDelegate.prototype.invokeTask@http://localhost:3001/lib/zone.js:356:24
	Zone</Zone</Zone.prototype.runTask@http://localhost:3001/lib/zone.js:256:29
	drainMicroTaskQueue@http://localhost:3001/lib/zone.js:474:26
	EventListener.handleEvent*scheduleEventListener@http://localhost:3001/lib/zone.js:838:13
	Zone</ZoneDelegate</ZoneDelegate.prototype.scheduleTask@http://localhost:3001/lib/zone.js:336:22
	Zone</Zone</Zone.prototype.scheduleEventTask@http://localhost:3001/lib/zone.js:276:21
	zoneAwareAddEventListener@http://localhost:3001/lib/zone.js:889:6
	addEventListener@http://localhost:3001/lib/zone.js line 982 > Function:1:43
	patchProperty/desc.set@http://localhost:3001/lib/zone.js:774:14
	ZoneAwarePromise@http://localhost:3001/lib/zone.js:584:30
	Zone</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:3001/lib/zone.js:323:20
	Zone</Zone</Zone.prototype.run@http://localhost:3001/lib/zone.js:216:25
	scheduleResolveOrReject/<@http://localhost:3001/lib/zone.js:571:53
	Zone</ZoneDelegate</ZoneDelegate.prototype.invokeTask@http://localhost:3001/lib/zone.js:356:24
	Zone</Zone</Zone.prototype.runTask@http://localhost:3001/lib/zone.js:256:29
	drainMicroTaskQueue@http://localhost:3001/lib/zone.js:474:26
	EventListener.handleEvent*scheduleEventListener@http://localhost:3001/lib/zone.js:838:13
	Zone</ZoneDelegate</ZoneDelegate.prototype.scheduleTask@http://localhost:3001/lib/zone.js:336:22
	Zone</Zone</Zone.prototype.scheduleEventTask@http://localhost:3001/lib/zone.js:276:21
	zoneAwareAddEventListener@http://localhost:3001/lib/zone.js:889:6
	addEventListener@http://localhost:3001/lib/zone.js line 982 > Function:1:43
	patchProperty/desc.set@http://localhost:3001/lib/zone.js:774:14
	
	Evaluating http://localhost:3001/node_modules/@angular/compiler//bundles/compiler.umd.js
	Evaluating http://localhost:3001/app/main.js
	Error loading http://localhost:3001/app/main.js

Issue is with the generated compiler.umd.js file. Response window in dev tools shows parse error on line 8972 in both Firefox and Chrome on Mac.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
 
* **Browser:** Chrome 51 | Firefox 49 
 
* **Language:** TypeScript 1.8.10

**Comment by vicb** [comment]
Your question sounds like a support request (also there is nothing we can do without more info)

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) for support request.
