### ISSUE TITLE
developer documentation out of date.

### ISSUE THREAD

**Issue by rickjz** [angular/angular#9683]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The developer documentation is out of date. In the documentation are gulp tasks that are found in the gulpfile.js.old.

**Expected/desired behavior**
Updating the documentation so i can start contributing to angular

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**
I want to help contribute to angular

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart]

**Comment by vicb** [comment]
> Updating the documentation so i can start contributing to angular

You can start contributing by updating the doc, that would be much appreciated !

**Comment by rickjz** [comment]
I doubt i will be able to do that since much changed and running the tasks in the new gulpfile weren't a success. But i'm gonna give it another try tomorrow.

**Comment by vicb** [comment]
use `./build.sh` to build and `./test.sh` to test

**Comment by fknop** [comment]
@vicb I've just tried the `build.sh` but the compilation fails.

The output: https://gist.github.com/fknop/80034e27fcd3601ac93acf947e61141e

I've cloned, and `npm install`, is there something more that we should do as well now ?
I'll be glad to contribute if I can make it work.

**Comment by fknop** [comment]
Ok it looks like on Windows, we have to manually create the symlinks for the `facade`. I used `remove_symlinks.sh` and `create_symlinks.sh` but it did not work out of the box due to `\r` at the end of the package name. 

What I did:

* git clone
* remove symlinks
* create symlinks
* npm install
* build.sh

It seems to work that way.
