### ISSUE TITLE
Angular 2 Router issue, seeing errors in Developer tools console in platform-browser.umd.js

### ISSUE THREAD

**Issue by vijender1256** [angular/angular#9684]
I tried to build Sample application in Angular 2 and I am able to create routing and it just works fine but I see errors in developer tools console window. Here is the plunker I created :

http://plnkr.co/edit/jJeQsLBOVrCz8QkxNAEc?p=preview

Also, even if I ignore those errors since it is working. I am having issues when I reload the the browser url it give me 404 issue, I build app in Visual studio 2015 Asp.net 4.5.2. I cannot demonstrate the reload issue using plunker as it will reload whole code. 

In Visual studio: http://localhost:14637/ loads the initial page :

![image](https://cloud.githubusercontent.com/assets/12258728/16430474/dcd0daea-3d49-11e6-8d5d-67b64a76436b.png)

But after I click on the route in my demo crisis center it is redirecting to crisis center page, but the moment I click on browser reload I am losing my whole routing and I get 404 issue

![image](https://cloud.githubusercontent.com/assets/12258728/16430530/14b421a6-3d4a-11e6-8dee-7fab464ce7aa.png)

It somehow not picking up the routing. Any help is appreciated. I am sorry that I created this issue again since my previous issue was closed without any help :(

**Comment by robwormald** [comment]
Your first error is simply because you don't have an empty / route defined. 

The second is unrelated to angular. When you visit the localhost:14367/crisis-center url for the first time, angular has no chance to get involved because the request *goes to your server first* - you need to fix it there. 

Please visit the gitter channel for support related questions in the future. Thanks!

**Comment by vijender1256** [comment]
@robwormald Thank you, When I put empty route it works perfectly fine on plunker, but when I try to put same code in Visual studio project It gives me same error as before "EXCEPTION: Error: Uncaught (in promise): Error: Cannot match any routes: '' 

And the issue with browser reload I am not going to localhost:14367/crisis-center url for the first time, I am click on crisis-center and then it will reload to that page and after that if i reload the page it give me 404 error, by that time router should know that path as I already clicked on it. I am reloading page after click on the crisis-center menu.

Please reply at your earliest convenience.

**Comment by zoechi** [comment]
Have you tried `<base href="/">` instead of for example `<base href=".">`?

**Comment by vijender1256** [comment]
@zoechi Thank you, I have tried <base href="/"> in Visual studio project but it doesn't work.

Below are example plunkers : I got solution to solve issue with  EXCEPTION: Error: Uncaught (in promise): Error: Cannot match any routes: '' by putting empty routes:

http://plnkr.co/edit/jJeQsLBOVrCz8QkxNAEc?p=preview --> this one has issue with routes which we can see on developer tools console

After replacing routes with empty route: 

http://plnkr.co/edit/7rfrj2uXW0NYEoUg2gtP?p=preview --> this fixed issue with routes only on plunker but the same code in Visual studio project the error is not going away :(

so the routing error in console window is still there in visual studio project.

Also even after replacing with 

<script>document.write('<base href="' + document.location + '" />');</script> 

or 

<base href="/">

it did not fix the browser reload issue 404 for route
