### ISSUE TITLE
Previous OnInit used when switching Routes

### ISSUE THREAD

**Issue by damienbod** [angular/angular#9692]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When I switch from one route to another route, the OnInit from the navigated component is called and not the OnInit from the actual component 

**Expected/desired behavior**

Should use the actual component OnInit

**Reproduction of the problem**

```javascript
<div class="container" style="margin-top: 15px;">
   
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a [routerLink]="['/home']" class="navbar-brand"><img src="../images/damienbod.jpg" height="40" style="margin-top:-10px;" /></a>
            </div>
            <ul class="nav navbar-nav">
                <li><a [routerLink]="['/home']">{{ 'NAV_MENU_HOME' | translate:lang }}</a></li>
                <li><a [routerLink]="['/shop']">{{ 'NAV_MENU_SHOP' | translate:lang }}</a></li>
                <li><a [routerLink]="['/shopAdmin']">{{ 'NAV_MENU_SHOP_ADMIN' | translate:lang }}</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li><a (click)="ChangeCulture('de','CH', 'CHF')">de</a></li>
                <li><a (click)="ChangeCulture('fr','CH', 'CHF')">fr</a></li>
                <li><a (click)="ChangeCulture('it','CH', 'CHF')">it</a></li>
                <li><a (click)="ChangeCulture('en','US', 'CHF')">en</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li>
                    <div class="navbar" style="margin-bottom:0;">
                        <form class="navbar-form pull-left">
                            <select (change)="ChangeCurrency($event.target.value)" class="form-control">
                                <option *ngFor="let currency of ['CHF', 'EUR']">{{currency}}</option>
                            </select>
                        </form>
                    </div>
                </li>             
            </ul>
        </div>
    </nav>

    <router-outlet></router-outlet>

</div>
```

component OnInit
```javascript
import { Observable } from 'rxjs/Observable';
import { Component, OnInit } from '@angular/core';
import { CORE_DIRECTIVES } from '@angular/common';
import { Http } from '@angular/http';


@Component({
    selector: 'homecomponent',
    template: require('./home.component.html'),
    directives: [CORE_DIRECTIVES]
})

export class HomeComponent implements OnInit {

    public message: string;

    constructor() {
        this.message = "home.component";
    }

    ngOnInit() {
        console.log("ngOnInit HomeComponent");
    }
}

```

routes:
```javascript
import { provideRouter, RouterConfig } from '@angular/router';
import { HomeComponent } from './home/home.component';
import { ShopComponent } from './shop/shop.component';
import { ShopAdminComponent } from './shop-admin/shop-admin.component'; 

export const routes: RouterConfig = [
    { path: '', component: HomeComponent },
    { path: 'home', component: HomeComponent },
    { path: 'shop', component: ShopComponent },
    { path: 'shopAdmin', component: ShopAdminComponent }
];

export const APP_ROUTER_PROVIDERS = [
    provideRouter(routes)
];

```
packages:

```javascript
{
    "version": "1.0.0",
    "description": "",
    "main": "wwwroot/index.html",
    "author": "",
    "license": "ISC",
    "scripts": {
        "tsc": "tsc",
        "tsc:w": "tsc -w",
        "build": "SET NODE_ENV=development && webpack -d --color",
        "buildProduction": "SET NODE_ENV=production && webpack -d --color",
        "typings": "typings",
        "postinstall": "typings install"
    },
    "dependencies": {
        "@angular/common": "2.0.0-rc.3",
        "@angular/compiler": "2.0.0-rc.3",
        "@angular/core": "2.0.0-rc.3",
        "@angular/forms": "0.1.1",
        "@angular/http": "2.0.0-rc.3",
        "@angular/platform-browser": "2.0.0-rc.3",
        "@angular/platform-browser-dynamic": "2.0.0-rc.3",
        "@angular/upgrade": "2.0.0-rc.3",
        "@angular/router": "3.0.0-alpha.8",
        "core-js": "^2.4.0",
        "reflect-metadata": "^0.1.3",
        "rxjs": "5.0.0-beta.6",
        "zone.js": "^0.6.12",

        "bootstrap": "^3.3.6",
        "angular2localization": "0.8.5"
    },
    "devDependencies": {
        "jquery": "^2.2.0",
        "autoprefixer": "^6.3.2",
        "clean-webpack-plugin": "^0.1.9",
        "copy-webpack-plugin": "^2.1.3",
        "css-loader": "^0.23.0",
        "extract-text-webpack-plugin": "^1.0.1",
        "file-loader": "^0.8.4",
        "html-loader": "^0.4.0",
        "html-webpack-plugin": "^2.8.1",
        "json-loader": "^0.5.3",
        "node-sass": "^3.4.2",
        "null-loader": "0.1.1",
        "postcss-loader": "^0.9.1",
        "raw-loader": "0.5.1",
        "rimraf": "^2.5.1",
        "sass-loader": "^3.1.2",
        "style-loader": "^0.13.0",
        "ts-helpers": "^1.1.1",
        "ts-loader": "0.8.2",
        "typescript": "1.8.10",
        "typings": "1.0.4",
        "url-loader": "^0.5.6",
        "webpack": "1.13.0"
    }
}

```

Component example:

**What is the expected behavior?**

Use the correct component init

**What is the motivation / use case for changing the behavior?**

bug

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3, webpack, any browser
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart]

**Comment by robwormald** [comment]
I can't reproduce this in a simple case https://plnkr.co/edit/cjFOsBvIhO336zRrMeIE?p=preview

**Comment by damienbod** [comment]
Here's the complete repo, hosted with ASP.NET Core

https://github.com/damienbod/Angular2LocalizationAspNetCore/tree/master/src/Angular2LocalizationAspNetCore

**Comment by damienbod** [comment]
Just for info, this was working fine before I switched to the new router. 

If I'm not using webpack, I don't have this problem either

**Comment by damienbod** [comment]
Same problem here:
https://github.com/damienbod/Angular2WebpackVisualStudio

**Comment by FabianGosebrink** [comment]
The repo https://github.com/damienbod/Angular2WebpackVisualStudio is based on this one here https://github.com/FabianGosebrink/ASPNET-Core-Angular2-StarterTemplate (damien and me created his repo together) and the StarterTemplate also is _not_ facing the router problem. Only when webpack comes into play it seems...

**Comment by kaeus** [comment]
I am having the exact same behavior with https://github.com/damienbod/Angular2WebpackVisualStudio in my own case. I used the same pattern to setup my application. I've tried https://github.com/preboot/angular2-webpack and it DOES seem to work there (both using webpack) and the navigation seems fine.

It really looks like the lifecycle doesn't process the component until the 2nd time the routerLink is navigated to. It seems to be loading the correct component initially (from the URL) but even the ngOnInit is not firing.

Would love to figure this out as I do prefer using Webpack. I don't have any drastic code differences, but even running the Angular2WebpackVisualStuido repo directly downloaded seems to have the issue.

**Comment by zoechi** [comment]
I have seen this when no default route was defined and this error was reported

> vendors.js:2291 Unhandled promise rejection Error: Cannot match any routes: ''

http://stackoverflow.com/questions/38202321/angular-2-routing-need-to-click-twice-to-trigger-ngoninit

**Comment by damienbod** [comment]
fixed, the vendor.ts was importing the files incorrectly.

see for fix:
https://github.com/damienbod/Angular2LocalizationAspNetCore/blob/master/src/Angular2LocalizationAspNetCore/angular2App/vendor.ts

**Comment by damienbod** [comment]
@kaeus @FabianGosebrink Did you get it working using the fix?

Greetings Damien

**Comment by kaeus** [comment]
@damienbod Yep. Changes to the vendor.ts worked perfectly. Was driving me nuts trying to debug this from the completely wrong angle! Thanks!

**Comment by damienbod** [comment]
cool, me too
