### ISSUE TITLE
why *ngIf misdesiged empty array `[]` to be true?

### ISSUE THREAD

**Issue by RunningV** [angular/angular#9693]
in chrome `[]` behaviours like this:
```
[] == true
>> false
[] == false
>> true
```

but why if i  init a variable to be an empty array, *ngIf think it's ture???
in the component:
`
let sth = []
`

in the template
```
<div *ngIf="sth">Is this will be hidden?</div>
```
I think sth is empty to be false, so ngIf should be false, the dom should'nt be showwed. but i actually show out.
in my scene, first i need to declare a variable `sth`, then i want to push some data to it.
if i declare like
 ` let sth = [] `
 there is no data but the dom is show out.
but i declare like 'let sth', when i push data  it will be error `TypeError: Cannot read property 'push' of undefined`
so why *ngIf disgin like this?

**Comment by Vexra** [comment]
Doesn't `*ngIf` mimick javascripts `if` behavior?

While 
```
[] == true
>> false
[] == false
>> true
```
is indeed the behavior in chrome, the following is also the case:
```
if ([]) {
    alert(1)
}
```
This alert will trigger because `if ([])` evaluates the block, just as your `*ngIf`

**Comment by pkozlowski-opensource** [comment]
> Doesn't *ngIf mimick javascripts if behavior?

Yes, this is correct - ngIf mimics what you would get from JS if
