### ISSUE TITLE
main AppComponent(parenet component) inner router child component message listener

### ISSUE THREAD

**Issue by racktime** [angular/angular#9694]
how to send push data  from main AppComponent(parent component)  http get data callback data to child component data

@Component({
    selector: app',
    templateUrl: ' <router-outlet></router-outlet>',
  
})

@RouteConfig([
    { path: '/', name: 'childComp', component: ChildComp},
);
export class AppComponent {
    constructor() {
    }

    ngOnInit() {
http.getdata().then(e => {
//inner router child component message listener ???
childComp.function call
});
           }
}

* how to way?
1. child component host listener
2. parent app componet to child comp push data
3. any way?

**Comment by pkozlowski-opensource** [comment]
See https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
