### ISSUE TITLE
Refreshing/Loading of Child Routes

### ISSUE THREAD

**Issue by SamSmith7** [angular/angular#9696]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When trying to navigate to a child route via its url, the page fails to load and responds with 404 errors. See reproduction explanation for more info.

**Expected/desired behavior**
Should be able to refresh the page when deep in the app. 

**Reproduction of the problem**
I initially found this whilst trying to implement the router into my main project in which the files were served from a ExpressJs back-end, but to narrow down what was actually wrong I have made an example out of the [quickstart](https://github.com/angular/quickstart) setup and the router plunk from the official [docs](https://angular.io/resources/live-examples/router/ts/plnkr.html). There is a repo [here](https://github.com/SamSmith7/angular2-routerbug) which combines the two as you can't test this properly on the plunk itself (at least I don't think you can). 

On the surface the router works completely correctly, all of the links work and you can navigate within the app to any of the pages. However, if you go to a child route e.g. .../hero/11 or .../crisis-center/admin and try to refresh the page the app will crash with a 404 not found.This only occurs when navigating to child routes, hitting refresh on top level routes e.g. /crisis-center or /heroes works as expected, hence why I think this is a bug rather than an error in my set-up.

**What is the expected behavior?**
The app should reload the child router correctly and display the same information as before

**Similar Issues**
I had a look through the issues and couldn't see anything related to this apart from possibly #9509. It could well be that this simply hasn't been implemented yet, but I couldn't find any reference to it in the docs. 

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
* **Angular/router version:** 3.0.0-alpha.8
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX ]  Tested in desktop browsers, all on latest stable versions
 
* **Language:** [ TypeScript 1.8.10 ]

**Comment by zoechi** [comment]
Sounds like http://stackoverflow.com/questions/31415052/angular-2-0-router-not-working-on-reloading-the-browser

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by brandonroberts** [comment]
@SamSmith7 there are two issues here. Your `<base href=".">` should be `<base href="/">` when using an actual server and your express server needs to be setup to return your `index.html` for any requests that would normally 404.

**Comment by magbeat** [comment]
@brandonroberts Thanks for the hint! Had the the same problem. `<base href="/">` resolved it for me. This should probably be changed in the documentation: https://angular.io/docs/ts/latest/guide/router.html#

**Comment by SamSmith7** [comment]
@brandonroberts Thanks, that fixed it. I would agree with @magbeat then that that needs to be updated in the docs, because it's not clear at all at the minute.

**Comment by brandonroberts** [comment]
@SamSmith7 @magbeat yep. We'll get it updated.

**Comment by SamSmith7** [comment]
Closed. Thanks
