### ISSUE TITLE
Navigating to a route which is mapped to the same component causes unnecessary ngOnDestroy and ngOnInit for this component

### ISSUE THREAD

**Issue by borisvasilenko** [angular/angular#9697]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
```

**Current behavior**

Route ```/a``` mapped to component ```X```. 
Route ```/b``` is mapped to component ```X``` too.

Navigating from ```/a``` to ```/b```, and from ```/b``` to ```/a``` will destroy and initialize again component ```X```, although this seems unnecessary. Component ```X``` could have an expensive data fetching in ```ngOnInit```, which should not be done twice.

**Expected/desired behavior**

When navigating to a new route, which is mapped to the same component, this component should not be destroyed and initialized again.

**Reproduction of the problem**

http://plnkr.co/edit/Sxu5eMAvsQ4x89fFDWdT?p=preview 

**What is the motivation / use case for changing the behavior?**

In our project we have a list of items. The user may choose one, and get the chosen item's ID appended to the URL: ```/listA/itemX```. To achieve that, we navigate to ```/listA/itemX```. Currently we get a full reload of an entire list. (Optional query parameters, like ```/?item=itemX``` do not suite our needs.)

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
* **Router version:** 3.0.0-alpha.7

**Comment by vsavkin** [comment]
Reusing components across different routes is problematic for a variety of reasons. So we do not intend implement such a behavior. 

What we can do instead is to implement optional positional params (e.g., list/(:id). Meanwhile, you can try to use wildcard routes as a workaround.
