### ISSUE TITLE
input range& ngModel: setting min/max and value at same time

### ISSUE THREAD

**Issue by ghetolay** [angular/angular#9699]
**I'm submitting a bug report**

**Current behavior**
If we have a component with the following template : 

```
<input type="range"
  min="{{min}}"
  max="{{max}}"

  [ngModel]="value">
```

Setting boundary value (min or max or both) and input value at same time won't set the input value correctly. 

```
updateRange() {
    this.min = 0;
    this.max = 50;
    this.value = 25; //won't be at the center
}
```

As a workaound we can delay the value update to the next tick :

```
updateRange() {
    this.min = 0;
    this.max = 50;
   setTimeout( () => this.value = 25, 0); //will work as expected
}
```

I've created a plunker : http://plnkr.co/edit/T8NKmEW7Y5EYHrpetPJk?p=preview
There is a similar issue for Angular 1 : https://github.com/angular/angular.js/issues/6726

**Angular version:** 2.0.0-rc.1 to 2.0.0-rc.3

**Comment by amitdahan** [comment]
This is still happening on RC5.

**Comment by DzmitryShylovich** [comment]
@ghetolay is this still an issue after final? can u pls update plunkr

**Comment by ghetolay** [comment]
Ok, made a [new plunker](https://plnkr.co/edit/BittPg0u2M3k9MHUX1wV?p=preview) it's fixed.

Thks !
