### ISSUE TITLE
Periods in queryParams with the new matrix URL notation causes 404

### ISSUE THREAD

**Issue by sumigoma** [angular/angular#9703]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
URLs with query parameters in the matrix URL notation, e.g. 

> http://localhost:3000/test;url=foo.bar.com 

returns a 404 before angular even handles it, because it most likely parses periods first for domain resolution (in the absence of ?&) before angular even has a chance to resolve the route. With the traditional query param notation (?&) this was not an issue.

**Expected/desired behavior**
Would like advice/documentation on a workaround for query params that have periods OR the option to disable matrix notation and use (?&) instead.

* **Angular version:** 2.0.0-rc.3, router 3.0.0-rc.8

**Comment by choeller** [comment]
This seems to be more of a server-side problem then an angular problem. I guess your server needs to be configured to redirect to index.html no matter if there are matrix-params or not.

**Comment by sumigoma** [comment]
Ah makes sense, thanks @choeller. I can work around it then.

But for those who do not need/want matrix variables, might I still suggest an option to allow devs to opt out of matrix syntax (given they understand the limitations), as we do for hashLocationStrategy?

**Comment by vsavkin** [comment]
You can opt out of the matrix syntax. You can provide your own UrlSerializer and, for instance, store the all params as query params.

**Comment by sumigoma** [comment]
@vsavkin can we make this easier since it has been requested before? (https://github.com/angular/angular/issues/7314) 

As was proposed, maybe something like 
`{ provide: ParamsStrategy, useClass: MatrixParamsStrategy /** or QueryParamsStrategy */}`
or at the very least, some mention in the docs?
