### ISSUE TITLE
Development / debug mode `ng-reflect-$field` performance issues with large strings

### ISSUE THREAD

**Issue by mprobst** [angular/angular#9707]
In development mode, Angular puts `ng-reflect-$fieldName` attributes into the DOM for easier debugging.  The value is the last bound value of the property, converted to a string using `toString`. That's generally useful, but breaks down if the amount of data passed is large.

Imagine an e.g. D3 graphing component that takes the definition of an entire graph as its bound object. Calling `toString` on it might easily produce multiple megabytes of data, on each level where the value is bound. This will likely slow development to a crawl or even crash the tab/browser.

We should consider limiting the amount of data shoved into the DOM, maybe by calling `substring(0, $someReasonableLimit)` on the data, or maybe by finding some more clever way to handle this.

**Comment by teropa** [comment]
I would like a way to disable `ng-reflect-*` completely in some situations. I'm finding it impossible to inspect the DOM in a component tree whose bindings are changing often.

**Comment by manekinekko** [comment]
@vicb  any updates about this issue?

**Comment by tbosch** [comment]
@manekinekko If you use `enableProdMode()` this is turned off (with JIT compile). For AoT, you need to set `debug: false` in the `tsconfig.json`.

**Comment by davidagee** [comment]
The problem with `enableProdMode()` is that it is a pretty large switch to pull, and ideally you'd only be doing it in production mode. The `reflect-*` html attributes are very handy in dev, but for example, using something like ag-grid, this could grind the application to a halt. I think it would be great to at least limit the output.

**Comment by simbro** [comment]
Is there no other way to disable ng-reflect without using enableProdMode() - it's not great for performance and makes inspecting the DOM difficult sometimes.

**Comment by arlowhite** [comment]
https://github.com/angular/angular/issues/2910 mentions **DOM_REFLECT_PROPERTIES_AS_ATTRIBUTES**

But I have no idea if it's still used or how to configure it.

**Comment by simbro** [comment]
Adding { useDebug: false } during bootstrap doesn't seem to disable ng-reflect for me unfortunately but enabling prod mode seems to work.

**Comment by DzmitryShylovich** [comment]
@simbro it was deprecated https://github.com/angular/angular/blob/f92591054bd4c45026939bcd49fd7e49c32db28a/packages/core/src/linker/compiler.ts#L99

**Comment by PeterHorvathIsento** [comment]
I use Angular-4.0.2, and ng-reflect is still there.

**Comment by tbosch** [comment]
Angular 4 simplified this logic:
- calling `enableProdMode()` will disable these attributes, otherwise they are present.
- We are also trimming these values now to max 30 characters, so this shouldn't crash the browser any more for large strings.

**Comment by ianjstewart** [comment]
Is it a good idea to truncate debugging information automatically?  

I don't use large data structures like the users in the thread, but I was very confused trying to debug custom form components that had class strings over 30 characters.  From what I can tell, I am using the correct use case for these ng-reflect-* attributes (to see what my bind became), but this change has made it impossible.

I'm sure it's my fault for not following closely enough with the release notes as this project moves up through versions.
