### ISSUE TITLE
Routes: double slash in the end turns off URL changing upon navigation

### ISSUE THREAD

**Issue by tprupsys** [angular/angular#9709]
**I'm submitting a [x] bug report

**Current behavior**
Upon adding two slashes in the end of URL, during navigation, the URL in the browser does not change as it should. E.g. open "localhost:3000//", click on somewhere where [routerLink] directive routes, the URL will remain the same, though it will navigate to a different component.

**Expected/desired behavior**
It should change the URL.

**Reproduction of the problem**
Have a few routes, routing to different components. I have two:

export const routes: RouterConfig = [
    { path: 'meal/:id', component: Meal, terminal: true },
    { path: '', component: Feed, terminal: true }
];

**Please tell us about your environment:**
Meteor JS serverside. Mac OS, Chrome.

* **Angular version:** 2.0.0-rc.X
    "@angular/common": "^2.0.0-rc.2",
    "@angular/compiler": "^2.0.0-rc.2",
    "@angular/core": "^2.0.0-rc.1",
    "@angular/platform-browser": "^2.0.0-rc.2",
    "@angular/platform-browser-dynamic": "^2.0.0-rc.2",
    "@angular/router": "^3.0.0-alpha.8", 

* **Browser:** I've checked chrome only
 
* **Language:** typescript

**Comment by vsavkin** [comment]
@tprupsys could you provide a plunker reproducing the issue using the latest release of the router.  

That's what I'm seeing when trying to reproduce it:
* Navigating to '//' throws 'Cannot match any routes'.

**Comment by vsavkin** [comment]
Closing this issue.
