### ISSUE TITLE
ng-mouseleave triggers on mouse right-click

### ISSUE THREAD

**Issue by jaysondaquer** [angular/angular#971]
On latest version of Chrome 41.x this behavior happens. On previous versions (40.x below) you can right click elements and perform different actions without triggering ng-mouseleave.

Affected scenarios are for Header Menus which contains hyperlinks. If element is dependent on ng-if which is updated by ng-mouseleave.

One good example of issue can be replicated here: https://docs.angularjs.org/api/ng/directive/ngMouseleave

On Chrome version 41.x or higher, Right Click on the the button and it will increment the counter.

Thanks and keep it up!

**Comment by vicb** [comment]
This repo is for Angular2, please use https://github.com/angular/angular.js for angular1
