### ISSUE TITLE
Included module HTML file 404 (Not Found)

### ISSUE THREAD

**Issue by ledfordjs** [angular/angular#9710]
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I'm using angular-cli v1.0.0-beta.8, currently I'm going to brake my application into different modules that I can then install with npm. I was able to get this to work but my .html files that I include with templateUrl will throw 404 errors
![screen shot 2016-06-29 at 9 52 04 pm](https://cloud.githubusercontent.com/assets/6081243/16474332/e9910ebc-3e43-11e6-8758-83ab19a94438.jpg)

* **Angular version:** 2.0.0-rc.3
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by vicb** [comment]
When submitting an issue please fill out the template. There is nothing we can do to help out without a plunker. Please also check the docs on angular.io

Also your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) for support request.
