### ISSUE TITLE
Endless problems with Angular 2 and dependencies

### ISSUE THREAD

**Issue by CraigAP** [angular/angular#9711]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Unable to get web site running due to Angular dependencies.

**Expected/desired behavior**
It should be possible to know precisely what dependencies there are and what versions are needed.

**Reproduction of the problem**
I used Visual Studio 2015 to create a project and got so far as to have it working with TypeScript.  I then added Angular code, pretty much following the instructions in [this tutorial](https://www.typescriptlang.org/docs/handbook/asp-net-core.html).  Running the web site now has problems with Angular trying to access dependencies.  It's clear from hundreds of Google search results that this is a common problem.  I implemented some of the suggested fixes, but could never get it to work.  Developers are spending thousands (millions?) of hours trying to resolve issues that just should not exist.  I'm angry, frustrated, tired, and disappointed  I really want to use Angular 2.  It's a beautiful rewrite of the confusing, mysterious version 1.

What I've tried so far is in this [GitHub Repository](https://github.com/CraigAP/Angular-Dependency-Problems).

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [Chrome XX] 
 
* **Language:** [TypeScript 1.8 | ES5 ]

**Comment by robwormald** [comment]
We suggest you go through the tutorial on our website, as the version you've linked to is significantly out of date, and we're not going to offer support on setting it up via Visual Studio (that doesn't mean it *won't* work, but the Angular team can't offer support on VS)

Start here - https://angular.io/docs/ts/latest/tutorial/ and follow the instructions as suggested. Once you've got your brain wrapped around how this all works, consider then setting it up inside Visual Studio.

**Comment by thelgevold** [comment]
There is also a "cookbook" for setting up the QuickStart in VS 2015
https://angular.io/docs/ts/latest/cookbook/visual-studio-2015.html
