### ISSUE TITLE
lazy loading files in angular

### ISSUE THREAD

**Issue by Rahul-Giri** [angular/angular#9712]
Hi , sorry for creating a new issue,

Actually i'm creating a very big website in angular and now i have 100+ different components 50+ services , 20+ third party libraries + plugins. and this all loading once at the same time when my home page, all those image editing , video uploading , blogs etc.. files loading even we just visited to homepage. which taking a little time to load. so

is there anyway i can load my files based on the condition. example if photo editing components and services do not need to download until user visit that state. 

Thanks

**Comment by vicb** [comment]
Lazy loading currently works in conjunction with the router, ie the component for a route will only be loaded when the route is first activated.

We have plan to further improve this and to add some documentation. Stay tuned.
