### ISSUE TITLE
input type search emits a search event when form is submitted by enter

### ISSUE THREAD

**Issue by basti1253** [angular/angular#9717]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
```

**Current behavior**

The component controller defines a custom EventEmitter named 'search'. The component markup contains a input with type search. When the form is submitted by pressing the enter key a search event is fired by the template itself. This event is captured by the outer app component

**Reproduction of the problem**

app template:
```
<ns-search-bar [suggestions]="suggestions | async" 
               (search)="search($event)" 
               (tokenChange)="token = $event"
></ns-search-bar>
```

Search bar component:

```
import { Component, EventEmitter, Input, Output, ViewEncapsulation } from '@angular/core';
import { 
  REACTIVE_FORM_DIRECTIVES,
  FormBuilder,
  FormControl,
  FormGroup
} from '@angular/forms';

@Component({
  directives: [ REACTIVE_FORM_DIRECTIVES ],
  encapsulation: ViewEncapsulation.Emulated,
  selector: 'apok-search-bar',
  styles: [
    require('./search-bar.component.scss')
  ],
  template: require('./search-bar.component.html')
})

export class SearchBarComponent {

  @Output()
  public tokenChange = new EventEmitter();

  @Output()
  public search = new EventEmitter();

  public form: FormGroup;

  constructor() {
    let fb = new FormBuilder();

    this.form = fb.group({
      token: ['']
    });
  }

  public get token(): FormControl {
    return <FormControl>this.form.controls['token']; 
  }

  ngOnInit() {
    this.token.valueChanges
      .debounceTime(300)
      .distinctUntilChanged()
      .subscribe((val) => {
        this.tokenChange.emit(val)
      });
  }

  public triggerSearch(ev) {
    this.showSuggestions = false;
    this.search.emit(this.token.value);
  }
}
```

Search bar template:

```
<form [formGroup]="form" 
      (submit)="$event.preventDefault(); triggerSearch()"
      novalidate 
>
  <div class="col-xs-12 col-sm-9">
    <input class="search-bar-input" type="search" placeholder="Suchbegriff(e)" formControlName="token">
  </div>
  <div class="col-xs-12 col-sm-3">
    <a class="btn btn-success btn-block" (click)="triggerSearch()">suchen</a>
  </div>
</form>
```

## stack trace:

```
SearchAppComponent.search	@	app.component.html?92be:1
_View_SearchAppComponent0._handle_search_5_0	@	SearchAppComponent.template.js:238
(anonymous function)	@	view.js:366
(anonymous function)	@	dom_renderer.js:246
(anonymous function)	@	dom_events.js:20
ZoneDelegate.invoke	@	zone.js:323
onInvoke	@	ng_zone_impl.js:46
ZoneDelegate.invoke	@	zone.js:322
Zone.runGuarded	@	zone.js:230
NgZoneImpl.runInnerGuarded	@	ng_zone_impl.js:79
NgZone.runGuarded	@	ng_zone.js:233
outsideHandler	@	dom_events.js:20
ZoneDelegate.invokeTask	@	zone.js:356
Zone.runTask	@	zone.js:256
ZoneTask.invoke	@	zone.js:423
```

**What is the expected behavior?**

pressing enter shouldn't trigger a search event that's captured by the outer component.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
 
* **Browser:** Chrome 51 
 
* **Language:** TypeScript

**Comment by zoechi** [comment]
This is by design. 

You can `preventDefault`

     <input class="search-bar-input" type="search"  (search)="false"

or

     <input class="search-bar-input" type="search"  (search)="$event.stopPropagation()"

to prevent the event from bubbling.

**Comment by basti1253** [comment]
I don't find any resource describing this behavior, maybe my description wasn't clear/good enough.
The search event triggers *twice*, one right after the other.
On the first run I get the desired search event triggered with a string value as the first argument. The 2nd event triggered doesn't fire the event with a string as the 1st argument. Instead the listener gets notified with a DOM Event. 
I can prepare a jsfiddle tomorrow if anything is unclear. If I miss anything I'd love to get additional hints to the doc describing this behavior.
My simple workaround is to use an input with type=text instead of search (event just got triggered once in that case).

**Comment by zoechi** [comment]
I don't get the problem. One event is emitted by the `<input type="search">` and one event is emitted by your `EventEmitter`. If you suppress the one from the `<input type="search">` then you get only one event. Is this not what you want.

To me this looks like a support question.

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by kemsky** [comment]
I think that template compiler should emit warning if event name (@Output name) overlaps with existing DOM event name (perhaps it could be smart enough to check type). Most of time this is not intended behavior which will cause unexpected errors.

**Comment by zoechi** [comment]
IMHO this would be rather something for external tools like linter where you can configure what you want to be warned about and maybe also suppress individual warnings..

**Comment by ericmartinezr** [comment]
@kemsky https://github.com/angular/angular/issues/4059 anyway, you're much better just by not naming your events like DOM events (although that may required to know every DOM event name...).
