### ISSUE TITLE
combining *ngIf and *ngFor executes loop with a last undefined item

### ISSUE THREAD

**Issue by tobias74** [angular/angular#9718]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
as it can be seen in this plunkr: http://plnkr.co/edit/ihdAJuUcyOj5Ze93BwIQ?p=preview

In case the two directives *ngIf and *ngFor are combined, than the *ngFor will execute one too many times with a last undefined item

**Expected/desired behavior**
the *ngFor should only iterate over the items actually in the array / the *ngIf should not interfere with *ngFor

**Reproduction of the problem**

http://plnkr.co/edit/ihdAJuUcyOj5Ze93BwIQ?p=preview

      
      <div *ngFor="let v of myValues;">
        This is my value: {{v}}
      </div>

OUTPUT:      
This is my value: one
This is my value: two
This is my value: three

      
      <div *ngIf="show" *ngFor="let v of myValues;">
        This is my value: {{v}}
      </div>

OUTPUT: 
This is my value: one
This is my value: two
This is my value: three
This is my value:

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart]

**Comment by tobias74** [comment]
in case *ngIf and *ngFor are not supported on the same element, the expected behavior would be a warning of an exception

**Comment by zoechi** [comment]
dup of #7315

**Comment by pkozlowski-opensource** [comment]
It is indeed dup of #7315 and is already fixed in master - it will throw in rc.4.
