### ISSUE TITLE
how to add and remove select box options if other select box options changes to the same options in AngularJS 2.0

### ISSUE THREAD

**Issue by DeveBj** [angular/angular#9719]
My Requirement

I need to remove the options which exist in another select box, when the same option is selected in another select box

What I have done

I have created 3 select boxes and loaded with the same values in it, and I have created a 2 functions enableAllOptions disableOptions, in enableAllOptions functions am enabling all the options for the first time and in disableOptions am disabling the options based on the options selected from select box

I'm pasting the fully functional [Plunker ](http://plnkr.co/edit/8rZyS06ByBfH4IOIVo2T?p=preview)for your reference (there is a issue in data loading in the select box)
 please help me to resolve this issue

**Comment by zoechi** [comment]
This sound like a support question.
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by DeveBj** [comment]
@zoechi okay, posted in all the supported site could not able to get a reply thats why posted here sorry if that was a wrong attempt

**Comment by pkozlowski-opensource** [comment]
@zoechi is right - this is not the right forum for those type of questions. Try on of the listed support channels and if you are not getting help re-thing how your question is formulated.
