### ISSUE TITLE
Angular 2 support bootstrap

### ISSUE THREAD

**Issue by sharmilemurugaraj** [angular/angular#9721]
Can I use bootstrap-3.3.6 for angular 2 release candidate instead of material design?

**Comment by pkozlowski-opensource** [comment]
Sure, there are several 3rd party libraries that provide angular 2 + bootstrap integration, ex.:
* https://github.com/ng-bootstrap/core
* https://github.com/valor-software/ng2-bootstrap

In the future please ask those type of questions in the dedicated support forum, see: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
