### ISSUE TITLE
problem installing "typings"

### ISSUE THREAD

**Issue by wtsi-swat** [angular/angular#9722]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

problem with installing node modules (windows 7)

npm log file output below: (Note the suggestion about running: npm run typings install did not fix problem)

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'typings',
1 verbose cli   'install' ]
2 info using npm@3.9.5
3 info using node@v6.2.2
4 verbose run-script [ 'pretypings', 'typings', 'posttypings' ]
5 info lifecycle angular2-quickstart@1.0.0~pretypings: angular2-quickstart@1.0.0
6 silly lifecycle angular2-quickstart@1.0.0~pretypings: no script for pretypings, continuing
7 info lifecycle angular2-quickstart@1.0.0~typings: angular2-quickstart@1.0.0
8 verbose lifecycle angular2-quickstart@1.0.0~typings: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-quickstart@1.0.0~typings: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\sr7\Documents\Angular2\angular2-quickstart\node_modules\.bin;C:\Program Files\nodejs;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Toshiba\Bluetooth Toshiba Stack\sys\;C:\Program Files (x86)\Toshiba\Bluetooth Toshiba Stack\sys\x64\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\MySQL\MySQL Utilities 1.3.5\;C:\Program Files\MySQL\MySQL Server 5.6\bin\;C:\Python27\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Users\sr7\Documents\playframework\play-2.2.2\;C:\Program Files (x86)\scala\bin;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\users\sr7\AppData\Local\Android\android-sdk\tools;C:\users\sr7\Documents\apache-ant-1.9.4-bin\apache-ant-1.9.4\bin;C:\users\sr7\AppData\Local\Android\android-sdk\platform-tools;C:\Program Files (x86)\Git\cmd;C:\webdriver;C:\Go\bin;C:\Program Files\nodejs\;C:\Users\sr7\AppData\Roaming\npm
10 verbose lifecycle angular2-quickstart@1.0.0~typings: CWD: C:\Users\sr7\Documents\Angular2\angular2-quickstart
11 silly lifecycle angular2-quickstart@1.0.0~typings: Args: [ '/d /s /c', 'typings "install"' ]
12 silly lifecycle angular2-quickstart@1.0.0~typings: Returned: code: 1  signal: null
13 info lifecycle angular2-quickstart@1.0.0~typings: Failed to exec typings script
14 verbose stack Error: angular2-quickstart@1.0.0 typings: `typings "install"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid angular2-quickstart@1.0.0
16 verbose cwd C:\Users\sr7\Documents\Angular2\angular2-quickstart
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "typings" "install"
19 error node v6.2.2
20 error npm  v3.9.5
21 error code ELIFECYCLE
22 error angular2-quickstart@1.0.0 typings: `typings "install"`
22 error Exit status 1
23 error Failed at the angular2-quickstart@1.0.0 typings script 'typings "install"'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-quickstart package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     typings "install"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-quickstart
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-quickstart
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Expected/desired behavior**

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart]

**Comment by vicb** [comment]
Sounds like an issue with `angular2-quickstart`, please open on issue on that repo

**Comment by wtsi-swat** [comment]
Hi Victor

There are quite a few repos with a name like "angular2-quickstart", Any
idea which one to use?

Thanks.

Cheers,
Stephen.
