### ISSUE TITLE
How to the current router sub-component call function  ?

### ISSUE THREAD

**Issue by racktime** [angular/angular#9723]
How to the current router sub-component call function  ?

appComponent
<router> child </router>

child componet {
   callfunction() {
     console.log('child function call');
  }
}
appComponent {
   cunstuctor(router:Router) {
///data push.
router.currentpagecomponet.callfunction() ???
}
}

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by vsavkin** [comment]
Closing this issue. Please ask questions on StackOverflow.
