### ISSUE TITLE
Dependency injection doesn't load all dependencies in a custom backend

### ISSUE THREAD

**Issue by Dinistro** [angular/angular#9725]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I'm currently trying to create a custom XHRBackend for my angular2 app. I want to catch all http responses with a 401 http response code (unauthorized) to redirect the user on the login-page. But here comes my problem: the dependency Injection is not able to load the Router in my custom-backend. I also tried to inject same services, but this also did not work. It only injects the 3 dependencies of the XHRBackend in my custom one. 

I asked this in SO and the only solution was to use a factory to create my custom backend: http://stackoverflow.com/questions/38124321/dependency-injection-does-not-load-all-params/38124520?noredirect=1#comment63680845_38124520

**Expected/desired behavior**

It should be possible to use the dependency injection in a custom backend to inject additional dependencies. 

**Reproduction of the problem**
http://plnkr.co/edit/44imf9KpE06cIyQ395sg?p=preview

The plunkr is based on the angular2 router example, unfortunately I had not enough time to create a smaller one. The important files are `custom.backend.ts` and perhaps `main.ts`.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
 
* **Browser:** all
 
* **Language:** TypeScript 1.8.10

**Comment by vicb** [comment]
> unfortunately I had not enough time to create a smaller one

Please take this time and re-open a new issue once you have it available. Thanks.
