### ISSUE TITLE
Async child routing not activating router-outlets

### ISSUE THREAD

**Issue by gdi2290** [angular/angular#9728]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
if you async load a component that has children with a router-outlet that outlet won't be active. To active the route you must click (via routerLink) on the same link to the current route

**Expected/desired behavior**
after updating the routeConfig provide a way to check the new routes again

**Reproduction of the problem**
revert this workaround https://github.com/AngularClass/angular2-webpack-starter/commit/d4ecb3f2214e8725e708c65b6c1d503e4b311ce4

**What is the expected behavior?**
the router should provide a way to update the router state going through the `applyRedirect` pipeline which is using a snapshot of the old route after we ran `resetConfig`

**What is the motivation / use case for changing the behavior?**
to make async loading routes easy

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
 
* **Browser:** Chrome
 
* **Language:** [TypeScript 1.8.10] 

here's my current workaround https://github.com/AngularClass/angular2-webpack-starter/commit/d4ecb3f2214e8725e708c65b6c1d503e4b311ce4 which is providing a child route as async so the old route state can determine that there needs to be an outlet

**Comment by vsavkin** [comment]
The router has a new API for loading routes asynchronously. See here:
https://github.com/angular/angular/blob/master/modules/@angular/router/test/router.spec.ts#L1072

The `resetConfig` method does not trigger activations. It just resets the config. To trigger activations, you can call resetConfig and then navigate to the current url.
