### ISSUE TITLE
Merge `Type` and `ConcreteType` into `Type`

### ISSUE THREAD

**Issue by tbosch** [angular/angular#9729]
Right now, we are using `Type` and `ConcreteType` in our code base.
`ConcreteType` refers to a class with a constructor, and `Type` is just an alias to `Function`.

A quick grep through our public api showed that we only use `Type` to refer to component / directive / ... classes.

Change:

1. Change all occurences of `Type` into `ConcreteType<any>`
2. Delete `Type` and rename `ConcreteType` into `Type`

**Comment by JahBrewski** [comment]
Alright, I'm new here, but I'd like to tackle this issue as my first contribution. Quick question though, what is meant by "<any>" in "ConcreteType<any>" ?

**Comment by tbosch** [comment]
In the end we only want to have `Type`, with the typing of `ConcreteType` right now.

**Comment by JahBrewski** [comment]
@tbosch Gotcha. Going to take a shot at this.

**Comment by JahBrewski** [comment]
@tbosch was told in gitter this wasn't an issue for public contributions.. I'll pull out of this one for now :)

**Comment by vicb** [comment]
>  this wasn't an issue for public contributions..

that means nothing, you are welcome to help - I commented on gitter

**Comment by aluanhaddad** [comment]
The name `Type` is misleading especially for the countless developers being introduced to TypeScript through the process of building their first Angular application. I've been using TypeScript for almost 4 years, so I am not mislead, but I am disappointed. At least `ConcereteType` gives some intuition, but it is still inaccurate. 

So, while getting rid of `type Type = Function` is a good move, renaming `ConcreteType` to `Type<any>` is a step in the wrong direction. 

There are many better names.  I recommend `Constructable`.

Other alternatives include `Reified`, `Manifest`, and `Runtime`. I'm sure we can think of others, but using `Type` is abhorrent.
