### ISSUE TITLE
new router typecheck error with current TS

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#9731]
minimal repro:
```
class CanActivate {
  constructor(public route: string) {}
  //private thing: number;
}
class CanDeactivate {
  constructor(public route: string, public c: number) {}
}

function fix(a: string, b?: number) {}

function f(s: CanActivate|CanDeactivate) {
  if (s instanceof CanActivate) {
    return fix(s.route);
  } else if (s instanceof CanDeactivate) {
    return fix(s.route, s.c);  // <- s is type never here
  } else {
    throw new Error('cannot be reached');
  }
}
```

```
modules/@angular/router/src/router.ts(403,44): error TS2339: Property 'component' does not exist on type 'never'.
modules/@angular/router/src/router.ts(403,57): error TS2339: Property 'route' does not exist on type 'never'.
```

if you uncomment `private thing: number` it is fixed.

The reason is that in the original code, `CanDeactivate` is structural subtype of `CanActivate` so all members of the `CanActivate|CanDeactivate` are matched by the first conditional, so in the first else clause `s` has been narrowed to never.

**Comment by mprobst** [comment]
This code works in JavaScript's runtime because `instanceof` is effectively a nominal type operator, i.e. it checks what constructor the instance was created with, not what (structural) type shape the constructor has. This looks like a TypeScript bug to me, I think they should match JS' runtime behaviour here?

**Comment by martine** [comment]
I vaguely remember seeing a bug about this in the TS tracker, and Anders groaning about how it's the one nominial corner of an otherwise structural type system.

**Comment by mprobst** [comment]
https://github.com/Microsoft/TypeScript/issues/7271 is it, I think.
