### ISSUE TITLE
Router 3 Authentication

### ISSUE THREAD

**Issue by a5hik** [angular/angular#9733]
angular version : 2.0.0-rc.2
router version: 3.0.0-alpha.7

What would be the best way to do Router Authentication with the new Router version '3.0.0-alpha.X' ?
Any sample or a hint would be much helpful.

Also, referring #9059 here.

**Comment by Sakurina** [comment]
https://angular.io/docs/ts/latest/guide/router.html#!#guards is what you're looking for. This isn't really a bug report or feature request though so it doesn't belong in the issue tracker.
