### ISSUE TITLE
ngc: missing cast for parent AppView when using pipe

### ISSUE THREAD

**Issue by alxhub** [angular/angular#9746]
When using `ngc` to compile the tour of heroes application, the heroes component (which uses the `UpperCasePipe`) generates this factory code:

``` 
detectChangesInternal(throwOnChange:boolean):void {
...
const currVal_0:any = import8.interpolate(1,'\n    ',valUnwrapper.unwrap(import8.castByValue(this._pipe_uppercase_0_0,this.parent._pipe_uppercase_0.transform)(this.parent.context.selectedHero.name)),' is my hero\n  ');
...
}
```

This fails typechecking, since `this.parent` is of type AppView which does not have a `_pipe_uppercase_0` field. Elsewhere in the generated factory code, `this.parent` is referenced with an explicit typecast:

```
this._pipe_uppercase_0_0 = import8.pureProxy1((<_View_HeroesComponent0>this.parent)._pipe_uppercase_0.transform.bind((<_View_HeroesComponent0>this.parent)._pipe_uppercase_0));
```

So the compiler is likely just failing to properly cast `this.parent` in the `detectChangesInternal` code it generates for the pipe.

**Comment by robwormald** [comment]
cc @tbosch

**Comment by bendilts** [comment]
This is affecting us as well.

**Comment by tbosch** [comment]
Looking at it...
