### ISSUE TITLE
[Router 3.0.0-beta.1] Constructor missing in declaration files

### ISSUE THREAD

**Issue by pkamdem** [angular/angular#9747]
**I'm submitting a ...**  (check one with "x")
```
[*] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

Compiling with ngc currently fails with the following error : **_Error: Typescript found the following errors:
  /Users/Y/Desktop/douala/tmp/broccoli_type_script_compiler-input_base_path-AZXHz4Dn.tmp/0/src/app/app.component.ngfactory.ts (46, 30): Supplied parameters do not match any signature of call target._**

<img width="779" alt="screen shot 2016-06-30 at 6 22 30 pm 1" src="https://cloud.githubusercontent.com/assets/11054877/16506494/bdbcfdde-3ef0-11e6-8e53-2290708754c3.png">

Adding the constructor to the declaration file as below solved the issue

<img width="932" alt="screen shot 2016-06-30 at 6 23 12 pm" src="https://cloud.githubusercontent.com/assets/11054877/16506487/ad2e4fe0-3ef0-11e6-9f95-077e88c48635.png">

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4 / 3.0.0-beta.1
 
* **Language:** [all | TypeScript 2.0.0-dev]

**Comment by pkamdem** [comment]
@vsavkin Please Champion, can you confirm the behaviour is actually the one desired?

Thanks!

**Comment by ericmartinezr** [comment]
That was supposed to be fixed here https://github.com/angular/angular/issues/9665

**Comment by pkamdem** [comment]
@ericmartinezr Oh missed that one. But the issue seems to still be there in beta.1

**Comment by pkamdem** [comment]
This might be due to the private and internal annotations on those classes.

**Comment by ericmartinezr** [comment]
Upgrade to beta.2, those annotations were removed there, see https://github.com/angular/angular/blob/master/modules/%40angular/router/CHANGELOG.md

**Comment by pkamdem** [comment]
Still the in Beta.2, the fix is missing for RouterOutlet
