### ISSUE TITLE
Method is being called by Angular 68 times!

### ISSUE THREAD

**Issue by sharpmachine** [angular/angular#9749]
**I'm submitting a ...**
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When loading the the app root I have function to check if the user is logged in to determine if I should show the header and footer. However if I console.log the method it's ran 68 times on load, and then is called 4 more times on every keyup event.

**app.component.ts**
```js
...

export class AppComponent {
  constructor(private _auth: AuthService) { }

  showNavbarAndFooter() {
    console.log('AppComponent showNavbarAndFooter');
    return this._auth.isLoggedIn();
  }
}
```

**app.component.html**
```html
<nsg-navbar *ngIf="showNavbarAndFooter()"></nsg-navbar>
<div class="container">
  <router-outlet></router-outlet>
</div>
<nsg-footer *ngIf="showNavbarAndFooter()"></nsg-footer>
```

**Expected/desired behavior**
I expect the method to not be called 68 times...I'm thinking in this situation it should only be ran twice.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [Chrome 51] 
 
* **Language:** [TypeScript]

**Comment by mhevery** [comment]
Thank you for submitting the issue. All issues require a [plunker](https://plnkr.co/) which demonstrates the problem and how to reproduce it. Please re-open the issue or create a new issue once you have a reproducible use case.

We are sorry that we are so aggressive on closing the issues. We are overwhelmed with the number of issues we get, and so we only have time to look at the ones which are easy for us to reproduce.
