### ISSUE TITLE
RC4 - Firefox/IE/Edge animation error: null is not a valid value for easing

### ISSUE THREAD

**Issue by bensgroi** [angular/angular#9750]
**I'm submitting a ...**
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Upon start of animation, non-Blink browsers throw the error "null is not a valid value for easing". 

**Expected/desired behavior**
Animation as it worked correctly in RC3.

**Reproduction of the problem**
Use the live example from the Animation section of the documentation in Firefox: https://angular.io/resources/live-examples/animations/ts/plnkr.html

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** Firefox 47.0.1, Edge 25.10586.0.0, IE 11
 
* **Language:** all

**Comment by mhevery** [comment]
Thank you for submitting the issue. All issues require a [plunker](https://plnkr.co/) which demonstrates the problem and how to reproduce it. Please re-open the issue or create a new issue once you have a reproducible use case.

We are sorry that we are so aggressive on closing the issues. We are overwhelmed with the number of issues we get, and so we only have time to look at the ones which are easy for us to reproduce.

**Comment by bensgroi** [comment]
Clicking on the link (taken directly from the Angular docs) creates the plunker, but okay... created #9752
