### ISSUE TITLE
Add Provider/Providers Type

### ISSUE THREAD

**Issue by mhevery** [angular/angular#9751]
```
type Provider = 
    { new (...args: any[]): any; } | 
    {provide: any, multi: boolean} |
    {provide: any, useClass: Type, multi?: boolean} |
    {provide: any, useExisting: any, multi?: boolean} |
    {provide: any, useFactory: Function, deps: any[], multi?: boolean} |
    any[];
type Providers = Provider[];
```

EXAMPLE USAGE
```
var providers: Providers = [
  SomeType,
  {provide: SomeType, multi: true},
  {provide: SomeType, useClass: String},  
  {provide: SomeType, useClass: String, multi: true},  
  {provide: SomeType, useExisting: String},  
  {provide: SomeType, useExisting: String, multi: true},  
  {provide: SomeType, useFactory: () => null, deps: []},  
  {provide: SomeType, useFactory: () => null, deps: [], multi: true},  
];

```

**Comment by vicb** [comment]
should it be `{provide: any, multi?: boolean} |` (mutli optional)

**Comment by tbosch** [comment]
I think this should rather be `ConcreteType` instead of `Type`, i.e. something that can be `new`ed. We will hopefully soon merge `Type` and `ConcreteType` (see https://github.com/angular/angular/issues/9729)

```
export interface ConcreteType<T> extends Type { new (...args: any[]): T; }
```

**Comment by mhevery** [comment]
@vicb If `multy?` because then `{provider: Foo}` would be valid, which I think it should not be. But I could be convinced.

@tbosch Changed to newable per your suggestion.

Also added `any[]`. Turns out times can't be recursed, so `Provider[]` is not allowed.

**Comment by vicb** [comment]
for consistency `{provider: Foo}` must be allowed if `{provider: Foo, multi: true}` is
