### ISSUE TITLE
RC4 - Firefox/IE/Edge animation error: null is not a valid value for easing

### ISSUE THREAD

**Issue by bensgroi** [angular/angular#9752]
**I'm submitting a ...**
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Upon start of animation, non-Blink browsers throw the error "null is not a valid value for easing". 

**Expected/desired behavior**
Animation as it worked correctly in RC3.

**Reproduction of the problem**
This is the plunker provided by the Animation section of the documentation: http://plnkr.co/edit/aSziHtP9vWXKyLMwtIkZ?p=preview

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** Firefox 47.0.1, Edge 25.10586.0.0, IE 11
 
* **Language:** all

**Comment by cherrydev** [comment]
Any known workaround in the meantime?

**Comment by matsko** [comment]
Use the easing value in the timing: `animate(250, ...)` -> `animate('250ms linear', ...)`

**Comment by cherrydev** [comment]
Thanks, that works.  What's weird is that the "live example" code appears to target RC4 and appears to forgo the easing value as well, but behaves as intended.

**Comment by intellix** [comment]
am still getting the error in Safari for that plnkr and within my own application. Everything has an easing value defined as far as I can see, even in the plnkr
