### ISSUE TITLE
Chrome Error: projected content w/ animation laid out in component w/ *ngIf

### ISSUE THREAD

**Issue by colinkahn** [angular/angular#9754]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**This bug is only in Chrome, I've tested in Firefox and Safari and it does not happen**

When a projected component that has an animation changes state inside of another component that is showing/hiding it with `*ngIf`, the following error occurs: 

```
platform-browser.umd.js:1900 ORIGINAL EXCEPTION: NotSupportedError: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.
```

**Expected/desired behavior**

It shouldn't throw any error. The animations are valid and this works in other browsers.

**Reproduction of the problem**

https://plnkr.co/edit/cDAkj3mzxxko0BOgXnRI?p=preview

Open the developer tools in Chrome. After the apps loads, click the "Toggle Collapse" button. You'll see an error about partial keyframes not being supported.

**What is the expected behavior?**

See above.

**What is the motivation / use case for changing the behavior?**

This doesn't change any behavior. From what I can see this is a bug with existing behavior.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.2
 
* **Browser:** Chrome Version 51.0.2704.106 (64-bit) 
 
* **Language:** typescript

**Comment by matsko** [comment]
What's going on here is that the animation is run before the ngIf inserts the parent container into the DOM. 

I believe that this PR will solve the issue: https://github.com/angular/angular/pull/9775

I'll have a concrete response for you tomorrow.

**Comment by matsko** [comment]
This is fixed in master: http://plnkr.co/edit/U4bnZctgE7vuR5R0GTde?p=preview

I had to remove the `*ngIf="false"` code from your example. Not sure why that was there.
