### ISSUE TITLE
RouterLinkActive directive broken on non-anchor tags.

### ISSUE THREAD

**Issue by Tribex** [angular/angular#9755]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Adding a `routerLinkActive` directive to any tag that has a `routerLink` directive and is not an anchor `<a></a>` element results in a `TypeError: Cannot read property 'root' of undefined`

**Expected/desired behavior**
The `routerLinkActive` directive should act in the exact same manner when added to a non-anchor element as when it is added to an anchor element. (That behaviour being adding the specified class to the element when its route is active.)

**Reproduction of the problem**
Steps:
1. Add a routerLink directive to any element other than an anchor.
2. Add a routerLinkActive directive to the same element.
3. Observe error in console.

Plunk: http://plnkr.co/edit/HM83XuHhUj2yjaViSupM?p=preview

**What is the expected behavior?**
The `routerLinkActive` directive should act in the exact same manner when added to a non-anchor element as when it is added to an anchor element. (That behaviour being adding the specified class to the element when its route is active.)

The `routerLink` directive contains code that [clearly shows](https://github.com/angular/angular/blob/master/modules/%40angular/router/src/directives/router_link.ts) that it is designed to be able to be used on any tag. the `routerLinkActive` directive ought to be able to as well.

**What is the motivation / use case for changing the behavior?**
I am developing a large SPA which uses list elements for links in quite a few places. 

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all] 
 
* **Language:** [all]

**Comment by zoechi** [comment]
`routerLinkActive` seems to work as expected http://plnkr.co/edit/JwpYPT3MQFHNtzmEei2y?p=preview
`routerLink` is not supposed to work on a `<p>`
`routerLink` works on `<a>` and https://github.com/angular/angular/issues/9471 added support for `<button>`

**Comment by vicb** [comment]
> routerLink works on <a> and #9471 added support for <button>

9471 added support for `not(a)`

The issue seems legit regarding the API doc of `routerLinkActive`

**Comment by fknop** [comment]
Maybe because the `urlTree` is not initialized for the `:not(a)[routerLink]` until it is clicked ?
