### ISSUE TITLE
Routing requires presence of a RouterLink

### ISSUE THREAD

**Issue by Brocco** [angular/angular#9756]
**I'm submitting a ...**  
```
[ x ] bug report
```

**Current behavior**
If the currently loaded component does not contain a `RouterLink` then changes to routes are not being reflected.

**Expected/desired behavior**
The route would change regardless of the presence of a `RouterLink`

**Comment by dzielin** [comment]
I'm using components without RouterLink using the latest @angular/router.  Can you provide a demonstration of the issue?  Which version of angular are you using, and which version of the router?

**Comment by zoechi** [comment]
Without a proper instructions how to reproduce (Plunker) there probably isn't much the Angular team can do.

**Comment by Brocco** [comment]
I've attempted to reproduce without success, will reopen if I can reproduce in an example.
