### ISSUE TITLE
[Router 3.0.0-beta.2] "data" parameter exists in Route but is inaccessible due to missing RouteData class

### ISSUE THREAD

**Issue by dzielin** [angular/angular#9757]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

### _This may just be me misunderstanding the new code - I haven't been able to find much documentation on it._

**Current behavior**
Current RouterConfig allows route definitions with a "data" parameter (as of 3.0.0-beta.1; see: https://github.com/angular/angular/commit/f2f1ec0117a827d88245554f9940f98ceca0dcc2).  This data seems to be inaccessible via the documented RouteData as described on Angular.io.  Additionally, it seems that ActivatedRoute exposes data as public, but I've found that ActivatedRoute.data is undefined despite having defined data for each route in RouterConfig.

I'm trying to do something along the lines of:
```
import { provideRouter, RouterConfig } from '@angular/router';
import { LoginPageComponent } from './pages';

export const routes: RouterConfig = [
  { path: 'login', component: LoginPageComponent, data: {myData: "TEST"} }
];

export const APP_ROUTER_PROVIDERS = [
  provideRouter(routes)
];
```

```
import { Component } from '@angular/core';
import { ActivatedRoute, Router, ROUTER_DIRECTIVES } from '@angular/router';

@Component({
  selector: my-navigation',
  template: 'TEST',
  directives: [ROUTER_DIRECTIVES]
})
export class NavigationComponent {
  constructor(private route: ActivatedRoute, private router: Router) { }

  ngOnInit() {
    /* this.route has no .data
       can't map this.route.data to anything useful because it's undefined */
    console.log(this.route);
  }
}
```

Interestingly, I'm seeing that this.route has a _params_, but no _data_.  This seems to conflict with the ActivatedRoute constructor in router_state.ts which includes both a public _data_ and public _params_.

**Expected/desired behavior**
Data specified in RouterConfig should be accessible to the routed components in some form.  Either via documented RouteData, or via an ActivatedRoute parameter, or by some other means.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4

* **Router version:** 3.0.0-beta.2
 
* **Browser:** [ all ]
 
* **Language:** [ all ]

**Comment by ericmartinezr** [comment]
Works fine for me http://plnkr.co/edit/drBT0C?p=preview (Check `hero-detail.component.ts`,  `app.routes.ts` and the console)

**Comment by dzielin** [comment]
Thanks!  After painstakingly checking everything I realized I still have my router version locked at alpha 7 in my systemjs.config.js.

**Comment by dzielin** [comment]
@ericmartinezr Is there a relatively simple way to grab route data from a component outside of my router-outlet?  For example, my app component html looks like: `<my-nav></my-nav><router-outlet></router-outlet>`.

Using the plnkr you provided, I can get the route data from the constructor of my route component, but I'd like to be able to reference this data from the my-nav component.  If I need to, I can check for this and update a service via the constructor of each route component.  But it seems there would be a better way.

**Comment by daco** [comment]
@dzielin is this what you're looking for?
https://github.com/angular/angular/issues/9662

Worked for me in a similar use case

**Comment by nadhir-falta** [comment]
Still having the same issue: 
/* this.route has no .data
       can't map this.route.data to anything useful because it's undefined */

Expected/desired behavior
Data specified in RouterConfig should be accessible to the routed components in some form. Either via documented RouteData, or via an ActivatedRoute parameter, or by some other means.

Please tell us about your environment:

Angular version: 2.0.0-rc.4

Router version: 3.0.0-beta.2

Browser: [ all ]

**Comment by dzielin** [comment]
@nadhir-falta In my case, I was pulling in the wrong version of the router from a CDN.  I'd forgotten I was pulling from the CDN, so the version I specified in my package.json

```
/* My System.js config file */
(function(global) {
  var ngVer     = '@2.0.0-rc.4';
  var routerVer = '@3.0.0-beta.2';
	
  var map = {
    'app':                        'build', // 'dist',
    '@angular':                   'node_modules/@angular',
    'angular2-in-memory-web-api': 'node_modules/angular2-in-memory-web-api',
    'rxjs':                       'node_modules/rxjs',
    //'@angular/router':          'node_modules/@angular/router'
	'@angular/router':            'https://npmcdn.com/@angular/router' + routerVer,
	[...]
  };  
```

Because I was locking in the version here, even though I updated package.json, the client still got an older version of the router prior to the re-introduction of RouteData.  Verify that you haven't made a similar mistake, then take a look at the Plunkr above (https://github.com/angular/angular/issues/9757#issuecomment-229847781).

**Comment by nadhir-falta** [comment]
@dzielin Thank you thank you...that was the issue for me too.
I changed the version in my package.json but I didn't actually run the npm install on any of the updates lol
Thanks again
