### ISSUE TITLE
Dependency injection doesn't load all dependencies in a custom backend

### ISSUE THREAD

**Issue by Dinistro** [angular/angular#9758]
**I'm submitting a ...**  (check one with "x")

```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I'm currently trying to create a custom XHRBackend for my angular2 app. I want to catch all http responses with a 401 http response code (unauthorized) to redirect the user on the login-page. But here comes my problem: the dependency Injection is not able to load the Router in my custom-backend. I also tried to inject some services, but this also did not work. It only injects the 3 dependencies of the XHRBackend in my custom one. 

I asked this in SO and the only solution was to use a factory to create my custom backend, but I think this should also work the way i tried. [Stackoverflow post](http://stackoverflow.com/questions/38124321/dependency-injection-does-not-load-all-params/38124520?noredirect=1#comment63680845_38124520) 

**Expected/desired behavior**

It should be possible to use the dependency injection in a custom backend to inject additional dependencies. 

**Reproduction of the problem**

http://plnkr.co/edit/44imf9KpE06cIyQ395sg?p=preview

As you can see, the router inside the CustomXHRBackend is undefined.

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.3
- **Browser:** all
- **Language:** TypeScript 1.8.10

**Comment by zoechi** [comment]
I think its the same underlying issue as in #8925, #8777

**Comment by DzmitryShylovich** [comment]
is this still an issue after final?

**Comment by vicb** [comment]
Probably solved by #8991

**Comment by mrgoos** [comment]
I'm waiting for this too :)
Hope it will be resolve soon.
Thanks for this thread.

**Comment by DzmitryShylovich** [comment]
#8991 was merged. can somebody reproduce or the issue can be closed?

**Comment by mrgoos** [comment]
It works great now @DzmitryShylovich
