### ISSUE TITLE
Datepipe not working corectly

### ISSUE THREAD

**Issue by basvandenheuvel** [angular/angular#9759]
**I'm submitting a ...**  bug report

**Current behavior**
When passing "hh" to the updated datepipe in RC.3 i receive "9".

**Expected/desired behavior**
Reading the documentation i would expect to receive "09".

* **Angular version:** 2.0.0-rc.3
 
* **Language:** [TypeScript]

**Comment by zoechi** [comment]
Please provide a Plunker that demonstrates the issue.

**Comment by DzmitryShylovich** [comment]
Looks like required the same fix https://github.com/angular/angular/pull/9338 but for hours.

**Comment by laskoviymishka** [comment]
@DzmitryShylovich confirm
