### ISSUE TITLE
RC4- Not Compatible with RxJS@5.0.0-beta.9

### ISSUE THREAD

**Issue by blackjyn** [angular/angular#9760]
After updating RxJS to beta9 I gotta error :

**SystemJS) XHR error (404 Not Found) loading http://localhost:3000/symbol-observable**

![ng2rxjs500-beta-9error](https://cloud.githubusercontent.com/assets/6046191/16516079/f673feca-3f9f-11e6-9c72-9a373596f58e.png)

When I downgrade RxjS back to 5.0.0-beta.6 it works perfectly.

**Bug or else?**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** IE  
* **Language:** TypeScript 1.8.10

**Comment by pkozlowski-opensource** [comment]
That's correct, at present we specifically requite rxjs 5.0.0-beta.6. Update of the rx version is tracked in #9549
