### ISSUE TITLE
Proposal: Map-style Pipe Definition

### ISSUE THREAD

**Issue by laco0416** [angular/angular#9761]
**I'm submitting a ...**  (check one with "x")

```
[x] proposal
```
### Goal

``` ts
@Component({
  pipes: [
    { name: 'quote', transform: (value) => `"${value}"` }
  ],
  template: `{{ someText | quote }}`
})
class SomeComp {
}
```
### Motivation

To define any pipes, we have to create a class for each pipe.
A class is useful for import/export among files. But when I want a pipe for the specific component, Class-style definition is verbose.
So, I want **instant** pipe definition. 
### Summary
- `pipes` supports Map-style pipe definition
- `{ name: string, transform: Function, pure: boolean }`

**Comment by sod** [comment]
Why not?

```javascript
@Component({
  template: `{{ quote(someText) }}`
})
class SomeComp {
  quote(value) {
    return `"${value}"`;
  }
}
```

Or if you wan't to keep your one liner

```javascript
@Component({
  template: `{{ quote(someText) }}`
})
class SomeComp {
  quote = (value) => `"${value}"`;
}
```

**Comment by laco0416** [comment]
```ts
@Component({
  template: `{{ quote(someText) }}`
})
class SomeComp {
  quote = (value) => `"${value}"`;
}
```

In this case, `quote` is a method. It means that depends on an instance of the class.

Originally, I want to use static methods in my template, but it's impossible. Static members are not scoped by the template compiler. 

```ts
@Component({
  template: `{{ quote(someText) }}` // error
})
class SomeComp {
  static quote = (value) => `"${value}"`;
}
```

So, for functions which don't depend on the component class, I proposed the idea for instant pipe definition.

**Comment by ericmartinezr** [comment]
Calling a method in the template is not really a good idea. For the static properties/methods you can use the workaround in this issue https://github.com/angular/angular/issues/4707

**Comment by aluanhaddad** [comment]
> In this case, quote is a method. It means that depends on an instance of the class.

@laco0416 Actually it is a property containing a function with a lexical `this` reference. If it used the any instance members, it would capture the initializing instance. This makes it safe to treat it as a free standing function.

Back on topic, class definition is indeed verbose and shouldn't be necessary in the case outlined.

**Comment by gdi2290** [comment]
```typescript
import {Pipe} from '@angular/core'

function pipeBuilder(name: string, fn: (value?: any) => any = (val) => val) {
  return Pipe(class {  transform = fn });
}

@Component({
  pipes: [
    pipeBuilder('yolo', (wat) => wat + ' yolo')
  ]
})
class App {
}
```

**Comment by laco0416** [comment]
@gdi2290 Function-style API is already deprecated in the context of `providers`.
I think it's good if `providers` and `pipes` have the similar interface.

**Comment by sod** [comment]
@ericmartinezr calling methods in a template is not a good idea? Let me quote the official angular2 docs:

![image](https://cloud.githubusercontent.com/assets/905328/16736134/09167d3e-478c-11e6-89c4-beaec3f41753.png)

https://angular.io/resources/live-examples/router/ts/plnkr.html / app/crisis-center/crisis-list.component.ts

**Comment by DzmitryShylovich** [comment]
@sod it's still a bad idea :) 
if u care about performance ofc

**Comment by sod** [comment]
@DzmitryShylovich I'd like to point to a pretty awesome feature of vue.js ... [computed values](http://vuejs.org/api/#computed). You can access these methods like values, but the underlying method is only called when any of the variables inside the method changes. So I neither have to see if any input changed, nor is there a need to cache the result in an extra variable.

That would be the holy grail. Just use the functions and the angular change detection optimizes it for performance.

**Comment by laco0416** [comment]
`@Component.pipes` are gone. Currently _component-local pipes_ cannot be created. And AOT compilation needs a class for extract type information. So this proposal is obsoleted.
