### ISSUE TITLE
URLSearchParams QueryEncoder bug with = (equals) char

### ISSUE THREAD

**Issue by Sleeper9** [angular/angular#9762]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I want to pass a plain Base64-encoded query parameter that looks like this: token=3DdP0VBThL7Ay1fOUFQK1XgLdxmwaDN8rmUTKk+RJEY=

Now in the constructed URL, it becames this:
token=3DdP0VBThL7Ay1fOUFQK1XgLdxmwaDN8rmUTKk+RJEY;

**Expected/desired behavior**

In the latest RC4, the QueryEncoder looks like this:

```
function standardEncoding(v: string): string {
  return encodeURIComponent(v)
      .replace(/%40/gi, '@')
      .replace(/%3A/gi, ':')
      .replace(/%24/gi, '$')
      .replace(/%2C/gi, ',')
      .replace(/%3B/gi, ';')
      .replace(/%2B/gi, '+')
      .replace(/%3D/gi, ';')
      .replace(/%3F/gi, '?')
      .replace(/%2F/gi, '/');
}
```
This is wrong. The line ` .replace(/%3D/gi, ';')` should not be there, or it should be `.replace(/%3D/gi, '=')` instead.

* **Angular version:** 2.0.0-rc.4

**Comment by Sleeper9** [comment]
Besides that, even if I am able to register a custom `QueryEncoder` component to get around this bug, the http.get calls `URLSearchParams.clone()`, which constructs a new plain search params object, which eventually falls back to the default QueryEncoder :disappointed: 

```
URLSearchParams.prototype.clone = function () {
            var clone = new URLSearchParams();
            clone.appendAll(this);
            return clone;
        };
```

**Comment by fknop** [comment]
Workaround with custom QueryEncoder:

```
export class CustomQueryEncoder extends QueryEncoder {
  encodeKey(k: string): string { return customEncoding(k); }

  encodeValue(v: string): string { return customEncoding(v); }
}

function customEncoding(v: string): string {
  return encodeURIComponent(v)
      .replace(/%40/gi, '@')
      .replace(/%3A/gi, ':')
      .replace(/%24/gi, '$')
      .replace(/%2C/gi, ',')
      .replace(/%3B/gi, ';')
      .replace(/%2B/gi, '+')
      .replace(/%3D/gi, '=')
      .replace(/%3F/gi, '?')
      .replace(/%2F/gi, '/');
}



const urlParams = new URLSearchParams('', new CustomQueryEncoder());
```

**Comment by Sleeper9** [comment]
@fknop That's true, but this won't work with http.get(), as inside it makes a clone of the original URLSearchParams object, which creates a new (default) QueryEncoder (see my previous comment; code fragment from https://github.com/angular/angular/blob/master/modules/%40angular/http/src/base_request_options.ts):

```
search: isPresent(options) && isPresent(options.search) ?
          (isString(options.search) ? new URLSearchParams(<string>(options.search)) :
                                      (<URLSearchParams>(options.search)).clone()) :
          this.search,

```

Example use case:
```
this.http.get(url, {
            search: params,
            headers: headers
        })

```

**Comment by fknop** [comment]
I think you could append your query parameters as a string to your url in the meantime.

**Comment by Sleeper9** [comment]
That's a good idea :+1: I think that is the true workaround for now. I hope this will be fixed soon.

**Comment by julianpaulozzi** [comment]
+1

`params.set('filters', this._queryFilters);`

expect: 
`filters:[["discontinued","=",["false"]]]`

get:
`filters:[["discontinued",";",["false"]]]`

**Comment by Cody-Nicholson** [comment]
Posted a PR for the URLSearchParams.clone() method.

https://github.com/angular/angular/pull/9900

**Comment by michaelbromley** [comment]
I ran into this today. I am consuming an OData backend and I have a URL which looks like this:

```
api/v1/Customers?$expand=Addresses($filter=Default eq true)`
```

The value of the `$expand` key is `Addresses($filter=Default eq true)`, but gets encoded to `Addresses($filter;Default%20eq%20true)`, which breaks the backend.

**Comment by fknop** [comment]
@michaelbromley Had the same issue, one of the workaround above should work.

**Comment by nachopro** [comment]
:+1:

**Comment by sunshineo** [comment]
This bug is basically a typo. How long does it take for a typo to be fixed?
On the other hand, I'd prefer you do take some time to write proper tests, so bugs such as this does not get introduced so easily.

**Comment by fknop** [comment]
@sunshineo I made a pull request https://github.com/angular/angular/pull/9790 on July 3th, I agree it's starting to be a little long to merge.
