### ISSUE TITLE
beforeEach: TestComponentBuilder + addProviders (fails since RC4 deprecating beforeEachProviders)

### ISSUE THREAD

**Issue by tycho01** [angular/angular#9763]
**I'm submitting a ...**
[x] lamentation of deprecated functionality

There are two things I'd like to inject into each of my tests. A service and a `TestComponentBuilder` instance. This used to work as follows prior to RC4:

```
beforeEachProviders(() => [MyService]);

beforeEach(inject([TestComponentBuilder], (tcb) => {
  builder = tcb;
}));
```

In RC4, it seems this would become:

```
beforeEach(inject([TestComponentBuilder], (tcb) => {
  addProviders([MyService]);
  builder = tcb;
}));
```

However, this appears not to have been intended to work, erroring with `addProviders can't be called after the injector has been already created for this test` as thrown [here](https://github.com/angular/angular/blob/24eb8389d21707f198a19a4fad1db7b0330ec8ea/modules/%40angular/core/testing/testing.ts#L129-L131).

That's obviously by design, but if `beforeEachProviders` is now considered deprecated, it makes me wonder, is there any known solution here? Or is the new approach to inject either of the two for each test separately instead? If so, was this deprecation really worth it?

**Comment by antonybudianto** [comment]
looks like it's a matter of order. You can refer the example here
https://github.com/juliemr/ng2-test-seed/blob/master/src/test/greeting-component_test.ts

**Comment by tycho01** [comment]
Thanks. I didn't realize you could just make two `beforeEach`, but that makes a lot of sense. That should do.
