### ISSUE TITLE
Angular 2 basics

### ISSUE THREAD

**Issue by danielverejan** [angular/angular#9765]
Hi, it's not really an issue rather something that frustrates me.

Can someone please explain:

1. Why angular loads these scripts in html and directly from node_modules
![2016-07-01_1610](https://cloud.githubusercontent.com/assets/7072732/16522455/8c02515c-3fa6-11e6-8243-8174fd17e272.png)

2. Why I can't just import a module installed with npm which results in an error in zone.js which no one(even docs, from what I found) knows what it does(same with the rest of scripts loaded in html).

I really tried for more then an hour to load a single npm module, using import, require, configs in systemjs.config.js(stupid name! why it's called systemjs if its extension is .js!) in map/packages/paths and none of this successfully.

All of this from angular starter guide.

**Comment by neilhem** [comment]
[Stackoverflow](http://stackoverflow.com/) is the right place to ask questions like this.
