### ISSUE TITLE
Global Platform Object is causing isolation issues

### ISSUE THREAD

**Issue by jkanczler** [angular/angular#9766]
**I'm submitting a feature request**
**Current behavior**
According to the documentation, currently Angular 2 is relying on a global platform object in the browser:
" \* ## Bootstrapping Multiple Applications
 *
- When working within a browser window, there are many singleton resources: cookies, title,
- location, and others. Angular services that represent these resources must likewise be
- shared across all Angular applications that occupy the same browser window. For this
- reason, Angular creates exactly one global platform object which stores all shared
- services, and each angular application injector has the platform injector as its parent.
  *
- Each application has its own private injector as well. When there are multiple
- applications on a page, Angular treats each application injector's services as private
- to that application."

**Expected/desired behavior**
Unfortunately because of this we can't run multiple bundled angular applications in the browser. If the applications are bundled together with the angular 2 scripts (for example with webpack), then a bundle that is loading after another bundle will override the previously initialized global platform object I assume. Therefore the previously loaded app for example will lost its registered dependency tree. And of course because of the global platform object we can't run two different versions of angular 2 in the same browser.

**What is the motivation / use case for changing the behavior?**
The motivation behind this to implement truly re-usable components. For example creating angular 2 app wrapped in a web-component that can be imported by another angular 2 application, or not just an angular 2 application, but by a react, knockout, or whatever application.
- **Angular version:** 2.0.0-rc.2
- **Browser:** [all] 
- **Language:** [all]

**Comment by trotyl** [comment]
Obsolete, platforms now provide `PlatformFactory`s rather than static `PlatformRef`s.
