### ISSUE TITLE
platform-browser/index has no exported member ELEMENT_PROBE_PROVIDERS

### ISSUE THREAD

**Issue by BrianRT** [angular/angular#9769]
**I'm submitting a ...** 
```
[x] bug report
```

**Current behavior**

I am upgrading from rc.2 to rc.4.  I see that ELEMENT_PROBE_PROVIDERS has been removed.  It was being used during my application's bootstrap.  I was wondering if there's something I should be using in place of it?  I couldn't find it in the changelog for rc.3 or rc.4.  

**Reproduction of the problem**

```
document.addEventListener('DOMContentLoaded', function main() {
  bootstrap([App,
    ... 
    ...('production' === process.env.ENV ? [] : ELEMENT_PROBE_PROVIDERS),
    ...
  ]);
});
```

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Language:** [TypeScript 1.8.10]

**Comment by gdi2290** [comment]
it's on by default unless you invoke enableProdMode
https://github.com/angular/angular/blob/9340e1b065edb66717d937a86098541ac93278c6/modules/%40angular/platform-browser/src/browser.ts#L76

**Comment by BrianRT** [comment]
Ah, cool.  Thank you for pointing me there.
