### ISSUE TITLE
Angular 2 Router not working with multiple parameters passed.

### ISSUE THREAD

**Issue by vijender1256** [angular/angular#9770]
I created a sample plunker, to pass in multiple parameter to the next page and it doesn't work. Here is the plunker demonstration where crisis center routing doesn't work after click on items.

http://plnkr.co/edit/ngNSsKBzAuhaP0EjKVJX?p=preview

I have three layered navigation where it moves from crisis-center to crisis-details and then from crisi-details -> transactiondetail. So after I navigate to crisis details i want to pass crisisId and crisisdetailId to traverse back to detail and then crisis list.

I am trying to passing multiple parameter here anyone had this issue ?

Also, i want to hide the URL parameter from browser url and show alias name, previously 'as' keyword used to work now it doesn't work.

Any help appreciated

**Comment by fknop** [comment]
Path parameters are not passed in an object, pass them like:

```
this.router.navigate(['/crisis-center', 1, 2])
```

And it works like that.

**Comment by vijender1256** [comment]
@fknop 
Thank you very much it worked, another help how do i hide the url parameters on the browser, like I want to use alias name instead of actual url with Id's appearing on browser URL.

Earlies 'as' keyword and IsProd use to work now it not working. Can you please provide solution appreciate it.

**Comment by pkozlowski-opensource** [comment]
This sounds like a support question(s) / discussions, please use an appropriate support channel for those types of questions: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

Thnx for helping out @fknop - this is much appreciated!

**Comment by dalmarcogd** [comment]
There is a space in `{ path: 'crisis-center/:id /:id2', component: CrisisDetailComponent}, // this is not working`, the correct is `{ path: 'crisis-center/:id/:id2', component: CrisisDetailComponent}, // this is not working` and pass params like this 
`onSelect(crisis: Crisis) {
    // Navigate with Absolute link
    this.router.navigate(['/crisis-center', 1, 2]); //this is working.
     //this.router.navigate(['/crisis-center', '1','2']); //this is not working
    }`

**Comment by Hipparch** [comment]
You can use this. Angular2+/4/5 - navigate with data https://github.com/Hipparch/Angular2-navigate-with-data
