### ISSUE TITLE
[web_workers] (Chrome) Component do not render if root component has long initialization logic in constructor

### ISSUE THREAD

**Issue by mdaveynis** [angular/angular#9771]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Component in web worker scenario do not render if root component has long initialization logic in the constructor. Component in the plunker example (https://plnkr.co/edit/fL7BwEFOAu2GQwJjcFBl?p=preview) will render if number of cycles in a loop is reduced.

**Expected/desired behavior**
Component renders

**Reproduction of the problem**
See https://plnkr.co/edit/fL7BwEFOAu2GQwJjcFBl?p=preview

**What is the expected behavior?**
For above plunker sample following string should be displayed: "Hello Angular2 (Release Candidate!)"

**What is the motivation / use case for changing the behavior?**
Bug fix.

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.4
- **Browser:** Chrome 51.0.2704.103 m (64-bit) 
- **Language:** TypeScript 1.8.10

**Comment by mdaveynis** [comment]
Based on [Chromium Issue 584851](https://bugs.chromium.org/p/chromium/issues/detail?id=584851), Chrome garbage collects worker in certain cases 

Workaround: Adding a Worker object to `window` property
```js
    function spawnWebWorker(uri, instance) {
        var webWorker = new Worker(uri);
        window["dummy"] = webWorker;
        ...
    }
```

**Comment by mhevery** [comment]
Not angular issue. See  [Chromium Issue 584851](https://bugs.chromium.org/p/chromium/issues/detail?id=584851)
