### ISSUE TITLE
Allow routerLinkActive to work with descendant routerLinks

### ISSUE THREAD

**Issue by Yona-Appletree** [angular/angular#9777]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

Not sure if this is a bug report or feature request, as I didn't see the expected behavior documented, so I checked both. 

**Current behavior**

The routerLinkActive directive only appears to work for direct children of the directive. Consider this nested menu:

```
<li class="menuitem" routerLinkActive="menuitem-is-active">
	<button>Account</button>
	<ul>
		<li routerLinkActive="menuitem-is-active"><a [routerLink]="['/profile']">Profile</a></li>
		<li routerLinkActive="menuitem-is-active"><a [routerLink]="['/security-settings']">Security Settings</a></li>
	</ul>
</li>
```

The `routerLinkActive` directives on the inner `li` elements work as expected, but the outer one does not. I'm assuming this is because the descendants flag is not set to true on the `ContentChildren` annotation in the directive.

**Expected/desired behavior**

Either the directive should _always_ look for descendants (that seems like more likely case), or it should be configurable.

**What is the motivation / use case for changing the behavior?**

Nested menus are a very common use case, and having to write a custom directive that almost exactly copies the built-in one for this case seems undesirable. It would also (likely) be a very simple change to the existing directive.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
 
* **Browser:** all
 
* **Language:** Typescript.next

**Comment by PEsteves8** [comment]
I've been looking for something like that for a couple of days. My situation is almost exactly the same. Currently I'm using a custom isRouteActive(route) in each of the parent <li>'s

**Comment by zoechi** [comment]
Looks like a dup of #9755

**Comment by PEsteves8** [comment]
zoechi it's not a dup. #9755 asks to allow routerLinkActive in non achor tags, but it works with anchor tags or direct parents of anchor tags: ``` <li routerLinkActive="active"><a [routerLink]=(...)</a></li>```
What is being asked here is for routerLinkActive to work with higher ascendants, not just direct parents.

**Comment by damiandennis** [comment]
Also having an issue with this. I have a home link which never shows as active due to all the other links in the menu being descended from it.

**Comment by zta192** [comment]
I also would like to see this feature added. I'm in the same boat as well.

**Comment by Martin-Wegner** [comment]
I have the same problem with a dropdown menu but I found out something interesting. The routerLinkActive directive seems to be only called once.

In this example the dropdown nav element will be styled active:

```
<li routerLinkActive="active" [(isOpen)]="configMenuOpen" dropdown>
  <a id="config-button" role="dropdown-menu" data-toggle="dropdown" dropdownToggle>Config <span class="caret"></span></a>
  <ul class="dropdown-menu" aria-labelledby="config-button">
    <li><a role="menu-item" class="dropdown-item" [routerLink]="['/item1']">Item 1</a></li>
    <li><a role="menu-item" class="dropdown-item" [routerLink]="['/item2']">Item 2</a></li>
    <li><a role="menu-item" class="dropdown-item" [routerLink]="['/item3']">Item 3</a></li>
  </ul>
</li>
```

In this example only the active element inside the dropdown menu will be styled active (the dropdown nav element will be not styled active because it's routerLinkActive directive is not called!?):

```
<li routerLinkActive="active" [(isOpen)]="configMenuOpen" dropdown>
  <a id="config-button" role="dropdown-menu" data-toggle="dropdown" dropdownToggle>Config <span class="caret"></span></a>
  <ul class="dropdown-menu" aria-labelledby="config-button">
    <li routerLinkActive="active"><a role="menu-item" class="dropdown-item" [routerLink]="['/item1']">Item 1</a></li>
    <li routerLinkActive="active"><a role="menu-item" class="dropdown-item" [routerLink]="['/item2']">Item 2</a></li>
    <li routerLinkActive="active"><a role="menu-item" class="dropdown-item" [routerLink]="['/item3']">Item 3</a></li>
  </ul>
</li>
```

**Comment by greengerong** [comment]
routerLinkActive didn't work on parent element (`reDropdown` element) when we put the routerLink element into `ng-template`.

like that:

    <ng-template #defaultMenuTemplate let-menu="menu">
      <a *ngIf="menu.router" [routerLink]="menu.router" routerLinkActive="active">
        <i *ngIf="menu.icon" class="menu-icon {{menu.icon}}"></i>&nbsp;{{menu.text}}</a>
        ......
    </ng-template>

    <li reDropdown [direction]="direction" routerLinkActive="active" >
          <a class="dropdown-toggle" role="button" aria-haspopup="true" aria-expanded="false">
        {{menu.text}}
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu forAnimate">
            <ng-container *ngFor="let child of menu?.children">
              <li role="menuitem" >
                <ng-template [ngTemplateOutlet]="child.itemTemplate || defaultMenuTemplate"
                            [ngOutletContext]="{ menu: child }">
                </ng-template>
              </li>
            </ng-container>

          </ul>
        </li>

Any idea about this problem?

**Comment by jlahare** [comment]
is there any update over this ? in #10246 what is the solution ? closed without proper explanation !!!

**Comment by cnuwasn** [comment]
Is that feature removed in angular 6?

**Comment by kalpeshhpatel** [comment]
> routerLinkActive didn't work on parent element (`reDropdown` element) when we put the routerLink element into `ng-template`.
> 
> like that:
> 
> ```
> <ng-template #defaultMenuTemplate let-menu="menu">
>   <a *ngIf="menu.router" [routerLink]="menu.router" routerLinkActive="active">
>     <i *ngIf="menu.icon" class="menu-icon {{menu.icon}}"></i>&nbsp;{{menu.text}}</a>
>     ......
> </ng-template>
> 
> <li reDropdown [direction]="direction" routerLinkActive="active" >
>       <a class="dropdown-toggle" role="button" aria-haspopup="true" aria-expanded="false">
>     {{menu.text}}
>         <span class="caret"></span>
>       </a>
>       <ul class="dropdown-menu forAnimate">
>         <ng-container *ngFor="let child of menu?.children">
>           <li role="menuitem" >
>             <ng-template [ngTemplateOutlet]="child.itemTemplate || defaultMenuTemplate"
>                         [ngOutletContext]="{ menu: child }">
>             </ng-template>
>           </li>
>         </ng-container>
> 
>       </ul>
>     </li>
> ```
> Any idea about this problem?

@greengerong , did you manage to get solution for this problem??

**Comment by joselcvarela** [comment]
I had exact same problem reported by @greengerong
Since this issue is closed, maybe we should create another one, because this issue is partially solved.
