### ISSUE TITLE
Add support for directives that can insert arbitrary content into the DOM

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#978]
Use case:
Angular Material has a directive called `md-icon` that lets the user embed SVG content via URL:
```html 
<md-icon svg-src="../img/puppy.svg">
```
We need to be able to build a directive in angular 2 that directly embeds content in this way. Using a binding on innerHTML is possible, but susceptible to XSS and would require ugly string manipulation of DOM-like content.

**Comment by mhevery** [comment]
Duplicate of #1088
