### ISSUE TITLE
*ngFor not working with templateUrl:

### ISSUE THREAD

**Issue by 4tron** [angular/angular#9781]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report
```

**Current behavior**
error: `Can't bind to 'ngforOf' since it isn't a known native property ("<h1>{{pageTitle}}</h1><small>{{subTitle}}</small><hr><span [ERROR ->]*ngfor="let name of names">{{name}}</span>"): e@0:59`

**Expected/desired behavior**
A simple list of names

**Reproduction of the problem**

```
import { Component } from '@angular/core';

@Component({
  selector: 'app',
  templateUrl: 'app/app.component.html'
})

export class AppComponent {
  names:string[];
  
  constructor(){
    this.names = ['name1', 'name2', 'name3', 'name4'];
  }

 }
```
Html:
```
<span *ngFor="let name of names">{{name}}</span>
```

**What is the expected behavior?**
a list of names

**What is the motivation / use case for changing the behavior?**
so that it works 

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [Chrome latest ] 
 
* **Language:** [TypeScript ^8.]

**Comment by 4tron** [comment]
I have also tried this using
```
@Component({
  module:module.id,
  selector: 'app',
  templateUrl: 'app.component.html'
})
```
It does however work using `template`
```
@Component({
  module:module.id,
  selector: 'app',
  template: `<span *ngFor="let name of names">{{name}}</span>`
})
```

**Comment by pkozlowski-opensource** [comment]
I would be very, very surprised if this is about template vs. templateUrl. Could you please provide a plunker reproducing the issue, as requested in the issue template?

Without a plunker it is not actionable and will be closed.

**Comment by 4tron** [comment]
How can i make a plunkr without rc4 hosted ? https://code.angularjs.org/2.0.0-rc.4/ <- does not exist

**Comment by pkozlowski-opensource** [comment]
Issue template _has_ a link to a plunker that you can modify to reproduce your problem: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=preview

**Comment by 4tron** [comment]
Ok the plnkr works,  must be something wrong with my setup. Sorry for the inconvenience.

**Comment by 3du4** [comment]
@ghost I am having exactly the same problem as you. were you able to solve it?

**Comment by srdotnetdeveloper** [comment]
import { TestComponent } from '../Test/app.Test.component';
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';   //added this line to your module


@NgModule({
  declarations: [
    TestComponent
  ],
imports:[CommonModule],  // added this line
exports:[TestComponent]
//   providers: []
 
})
export class TestModule { 
 
}
your issue is resolved.

**Comment by sujanvaland** [comment]
> imports:[CommonModule],

Thanks a lot, wasted 2 hours on it
