### ISSUE TITLE
hash data on root url will cause error: Cannot match any routes: ''

### ISSUE THREAD

**Issue by cuiliang** [angular/angular#9783]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
![image](https://cloud.githubusercontent.com/assets/1972649/16540829/8a355956-40a4-11e6-9d2c-7b973e84239f.png)

route config:
```
export  const HomeRoutes: RouterConfig = [
  {
    path: '',
    component: HomeComponent,
    children: [
      {
        path: '',
        component: IndexComponent,
      }
    ]
  }
];

```
Hash data will be used after user logined from an OpenIdConnect server (using Implicit flow). The server will write token data in hash section of url.

The same error will show up if use `redirectTo` method:
```
export  const HomeRoutes: RouterConfig = [
  {
    path: '',
    redirectTo: 'home',
    pathMatch: 'full',
     terminal: true
  },
  {
    path: 'home',
    component: HomeComponent,
    children: [
      {
        path: '',
        component: IndexComponent,
      }
    ]
  }
];

```

**Expected/desired behavior**

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
* **Router version:** 3.0.0-beta.2
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart]

**Comment by cuiliang** [comment]
Another related problem: hash data will keep between route navigations.

**Comment by zoechi** [comment]
Seems to be related to #9786

**Comment by vsavkin** [comment]
Fixed here https://github.com/angular/angular/pull/10246
