### ISSUE TITLE
Selects where multiple = true ngModel not working in IE11 / Mobile Chrome (possibly others)

### ISSUE THREAD

**Issue by yusijs** [angular/angular#9784]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When you've got a select with multiple enabled, ngModel won't work in IE (and chrome for android)

**Expected/desired behavior**
ngModel binds the same across browsers. This works fine in Chrome on Win10 and Debian. 

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

Plunk @ http://plnkr.co/edit/23Ax6SaOJdmyUI6mfgjL?p=preview

**What is the expected behavior?**
The text box will bind just fine in all browsers, The select will not. If you remove multiple from the select, it binds as expected.

**What is the motivation / use case for changing the behavior?**

Cross browser functionality

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** IE 11 | Mobile Chrome 51.0.2704.81
 
* **Language:** TypeScript X.X

**Comment by sonicflux** [comment]
I believe that it is #9713. I experienced the same and when I applied the changes in #9713 I was able to select multiple items in IE/FF. I did not test mobile Chrome. It seems the fix is scheduled for RC5 based on its milestone label. I have confirmed that it does not work in RC4 via this plunk: http://plnkr.co/edit/BnfxSReQe3l7nQBvvuK2?p=preview

**Comment by yusijs** [comment]
I believe you're both correct. I'll just close this off, and reopen after rc.5 if need be. Thanks!
