### ISSUE TITLE
queryParams and hashData not removed after navigate to another route

### ISSUE THREAD

**Issue by cuiliang** [angular/angular#9786]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If navigate to route A with [queryParams]='{id:workspaceId}',  there will be queryParams in url:
`/routeA?id=value`.
But if navigate from A to another route B, the query params (and also hash data) will be keepd.
`/routeB?id=value`

**Expected/desired behavior**
query params removed from url when navigate to another location.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
* **Router version:** 3.0.0-beta.2
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart]

**Comment by albertvazquezm** [comment]
Same problem with 2.0.0-rc.4 and router 3.0.0-alpha.6

**Comment by zoechi** [comment]
Similar to #9508. It's upposed to be fixed.

**Comment by vsavkin** [comment]
Fixed here https://github.com/angular/angular/commit/23ee29b6a2ae396f6ec13f71c9552e3e0a983c3c
