### ISSUE TITLE
request| feat(Router): Add decorators @Resolved and @Params

### ISSUE THREAD

**Issue by PatrickJS** [angular/angular#9787]
``` typescript
interface Resolved(remap?: string) {}
interface Params(remap?: string) {}

class About {
  @Resolved() data: any
  @Params() params: any
}
```

It would simply be

<img width="747" alt="screen shot 2016-07-02 at 11 35 57 pm" src="https://cloud.githubusercontent.com/assets/1016365/16544126/d2f3a7ac-40ad-11e6-9cfc-52c9187bddcb.png">

[![github-tipe-logo](https://user-images.githubusercontent.com/1016365/34912701-7edec34c-f89c-11e7-8c89-bed6cef064b5.png)](https://tipe.io?ref=github-comment)

**Comment by eduardoalcantara** [comment]
I would very much appreciate that!

**Comment by atscott** [comment]
Closing. There's already a simple enough way to do this and we don't need to expand the public API for it.

```
class About {
  data = this.route.snapshot.data;
  params = this.route.snapshot.params;

  constructor(private readonly route: ActivatedRoute) {}
}
```
