### ISSUE TITLE
No value accessor for '' when using ngModel in custom directives with new forms

### ISSUE THREAD

**Issue by pleerock** [angular/angular#9788]
Custom components that implements value accessor to make them to work with ngModel are not working when switching to new forms. [This](https://github.com/pleerock/ng2-rating/blob/master/src/index.ts) works fine when using old forms, but does not work when switching to new forms. What is the new way of using ngModel value accessors?

**Comment by DzmitryShylovich** [comment]
U need to change imports `"@angular/common";` => `"@angular/froms";`

[Here](https://github.com/angular/material2/blob/master/src/components/input/input.ts#L105) u can find an example.

**Comment by pleerock** [comment]
yes you are right. thanks @DzmitryShylovich
