### ISSUE TITLE
Add support for overriding ShadowDomStrategy per Component

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#979]
Use case:
Angular Material has a directive called `md-icon` that lets the user embed SVG content via URL:
```html 
<md-icon svg-src="../img/puppy.svg">
```

This component exists to give people an easy way to insert SVG content into the document (there is no easy way to load SVG into the document by URL). Loading the content into the document directly (instead of using something like background-image) gives the user the power to style the SVG. If the SVG content is in a shadow root, however, most of the point of this component is lost. 

The fix this, an MdIcon component should be able to specify that it *always* should use an emulated mode (even at a time when all browsers support shadow roots).

**Comment by vicb** [comment]
There used to be some kind of support for it in the core but after discussion with @mhevery, @tbosch and @vsavkin it has been decided to drop this functionality.

The support was for html only and it is when I've worked on `<style>` support that we decided to drop this support. The rationale being that you would need to insert the `<style>` tag for emulated components in the closest enclosing shadow root vs in the `<head>` only when emulated mode is exclusive.

As we would need to be able to insert arbitrary DOM (ref #978) to support `md-icon` we might also be able to insert a `<style>` tag (it would go into the shadow DOM for native & head for emulated) - do you think this could be an alternative ?

**Comment by jelbourn** [comment]
@vicb I don't quite follow. The issue here is that the SVG content added by `md-icon` needs to be affected by any style rules that live in the light-DOM outside of the component. For example:
```html
<section class="error">
  <md-icon svg-icon="exclamation"></md-icon>
</section>
```

Where the `error` class changes the icon to be red. Appending `<style>` elements inside the icon's shadow DOM wouldn't really help.

**Comment by wzr1337** [comment]
Shadow Dom is decoupled from the light Dom also for styles. If you want to use styles from light Dom, you can either use ::shadow pseudo selector or /deep/ combiner in you light Dom Css

**Comment by vicb** [comment]
@jelbourn I'm only trying to understand if this is really needed. the host-context selector might be able to help in your use case,  not as flexible as emulated strategy though.

**Comment by jelbourn** [comment]
@vicb The benefit of using Shadow DOM at all is the encapsulation (styles, events, queries, etc). In this case, using the shadow DOM would makes things harder for the user without adding any benefits. There are many cases where Shadow DOM is a good tool to solve a problem, but it isn't appropriate for this use case.

**Comment by vicb** [comment]
The reason why we made the strategy global is perf.  If emulated mode is exclusive,  you can insert styles once at compile time.  If modes are mixed you have to check if styles have been inserted in the closest shadow root and insert them otherwise each time an emulated component is rendered.

**Comment by jelbourn** [comment]
The use-case for this issue would probably be addressed by having a Decorator-like directive with no shadow DOM (instead of a Component) that can append arbitrary content into itself as a resolution to #978.

**Comment by jelbourn** [comment]
I'm closing this issue because I thought more about how things like `:host` would work and it would be bad.
