### ISSUE TITLE
change neighbor input variable on input variable change

### ISSUE THREAD

**Issue by pleerock** [angular/angular#9791]
want to perform some operations when input parameters are being changed. Lets say I have a DatePicker component that has a type input variable, and I want to perform some actions with another date variable when type is being changed. How to do that?

```typescript
export class DatePicker {

    @Input()
    date: Date;

    @Output()
    dateChange = new EventEmitter();

    @Input()
    set type(type: string) {
        if (type === "today") {
            this.date = new Date();
            this.dateChange(this.date); // because of this change change detector will throw error
        }
    }

}
```

p.s. I asked this question on [SO](http://stackoverflow.com/questions/38036548/angular-2-change-neighbor-input-variable-on-input-variable-change) a week ago, and didn't get answer

Its a common case task - to perform operations when input values are being changed - any kind of operations, no matter if you change other variables - change detector or something else should not complain. Also, since I opened this issue I want to mention that current component's lifecycle in angular seems doubtful:

Inputs are coming before view and content init, and even ngOnInit, and if you are using setters on inputs to perform something that is depend of view components you can't do it on component initialization, but can do on next time inputs are changed. This creates a lot of monkey patches in the code, like this:

```typescript
export class DatePicker implements AfterViewInit {

    isViewInited = false;
   
    @Input()
    set data(data: string) {
        if (this.isViewInited)
           this.doSomethingViewRelated(data);
    }

   ngAfterViewInit() {
       this.isViewInited = true;
       this.doSomethingViewRelated(this.data);
   }
}
```

**Comment by zoechi** [comment]
I answered on SO. GitHub issues are still not for support questions.
Please ask support questions in one of the channels listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by pleerock** [comment]
thank you, but workaround you described is not acceptable and angular should have a proper sways to handle such situations. Also what about second problem I've described. Either I simply don't know the way to resolve this problem, either angular2 designed the wrong way, thus it can be a github issue.

**Comment by zoechi** [comment]
The 2nd part was not included in the SO question. Sounds like #7782

**Comment by pleerock** [comment]
yes looks so

**Comment by vicb** [comment]
Duplicate
