### ISSUE TITLE
i18nPluralPipe doesn't work according to the documentation

### ISSUE THREAD

**Issue by robisim74** [angular/angular#9793]
**I'm submitting a ...**
```
[x] bug report
```
Really, I don't know if it's a bug or a [documentation ](https://angular.io/docs/ts/latest/api/common/index/I18nPluralPipe-class.html) update error.

**Current behavior**
```
ORIGINAL EXCEPTION: TypeError: ngLocalization.getPluralCategory is not a function
```
when the number > 1.

**Reproduction of the problem**
http://plnkr.co/edit/WRaUI9vqyk6mLki6Gjor

**Please tell us about your environment:**
* **Angular version:** 2.0.0-rc.4

Thanks!

**Comment by NicolajKN** [comment]
I'm getting the same error with rc.4. Seems pretty broken to me.

**Comment by vicb** [comment]
It's not broken but under documented, see https://github.com/angular/angular/blob/master/modules/@angular/common/src/directives/ng_plural.ts#L29

**Comment by robisim74** [comment]
Ok, thanks @vicb. Just one question, if you can answer: this solution uses `i18nPlural `directive, and not the pipe. Is `i18nPluralPipe `deprecated?

**Comment by robisim74** [comment]
Meantime, if it can be useful to someone, this is a working example of `i18nPluralPipe` in rc.4: http://plnkr.co/edit/WfF4cqFppkanPKcjgAPv

**Comment by vicb** [comment]
no, use cases are different, ie you can not use a directive inside an attribute value. 

Both are here to stay.

Feel free to submit a PR to enhance the API doc.
