### ISSUE TITLE
printing the select box values in sql rules

### ISSUE THREAD

**Issue by DeveBj** [angular/angular#9795]
Hello I need to print the select box values in SQL rules when it is generated

I have altered the contains operator, which will print iscontains instead of %LIKE%

For ex

employeename conatins hello will give you employeename iscontains('hello') 

Now I need to change this as iscontains('hello', employeename) is this ispossible if so plkease help me to solve this

**Comment by zoechi** [comment]
As already mentioned in the template:

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)
