### ISSUE TITLE
document provider literal syntax for deprecated provide

### ISSUE THREAD

**Issue by precious-coder** [angular/angular#9799]
Would you please add docs + non-trivial code about what the (new) correct method of working should be instead of use of @deprecated like this?

```TypeScript
/**
 * Creates a {@link Provider}.
 *
 * See {@link Provider} for more details.
 *
 * <!-- TODO: improve the docs -->
 * @deprecated
 */
export declare function provide(token: any, {useClass, useValue, useExisting, useFactory, deps, multi}: {
    useClass?: Type;
    useValue?: any;
    useExisting?: any;
    useFactory?: Function;
    deps?: Object[];
    multi?: boolean;
}): Provider;
```

Thank you

**Comment by zoechi** [comment]
I also haven't found information in the changelog how to replace it.

You can just use an object instead of `provide()` like

```ts
  {provide: MyService, useClass: MyMockService}
```

and similar for all other variations.

**Comment by ericmartinezr** [comment]
It's deprecated, it hasn't been removed.

**Comment by aluanhaddad** [comment]
@ericmartinezr right so the documentation _definitely_ needs to be present so that people can migrate to it before it gets removed.

**Comment by thelgevold** [comment]
The DI samples on angular.io have been migrated over to use the provide object literal instead of the provide method. Is this what you are referring to?

Two articles with example:
https://angular.io/docs/ts/latest/cookbook/dependency-injection.html
https://angular.io/docs/ts/latest/guide/dependency-injection.html

**Comment by ericmartinezr** [comment]
The cheat sheet is also updated https://angular.io/docs/ts/latest/guide/cheatsheet.html

**Comment by xealot** [comment]
Should there at least be a declaration that goes along with this object literal to provide some type safety? Seems like a downgrade.

**Comment by aluanhaddad** [comment]
@xealot that's exactly what it is, a decrease in code quality. I'm very disappointed.

**Comment by PascalPrecht** [comment]
Here's a detailed guide on how to create providers using the map literal syntax, use that until the docs are updated: http://blog.thoughtram.io/angular/2016/05/13/angular-2-providers-using-map-literals.html

@aluanhaddad @xealot I'd assume you can still do `new Provider()` if you want types

**Comment by aluanhaddad** [comment]
@PascalPrecht that class is deprecated.

**Comment by thelgevold** [comment]
The docs are already using the object literal syntax: 

https://angular.io/docs/ts/latest/cookbook/dependency-injection.html
https://angular.io/docs/ts/latest/guide/dependency-injection.html

Isn't this what you are referring to?

**Comment by aluanhaddad** [comment]
Also I appreciate your blog post, but it's not about the feature being poorly documented it's about the feature being poorly typed as @xealot pointed out.
In general the concept of providers is very is opaque. It's also really confusing when something is deprecated in the documentation but it has a name which is canonical with a feature. When you see provide and Provider deprecated everywhere, it makes one wonder what related structures  have also been deprecated.

**Comment by xealot** [comment]
It's also not that I don't prefer the literal syntax. An interface should at least be provided to formalize the structure of the providers.

Everything in NG2 is typed pretty specifically, this seems like a weird exception.

**Comment by aluanhaddad** [comment]
@thelgevold the type declaration files do not have this documentation as of RC 4. One of the major benefits of typescript is code navigation combined with inline documentation. Also as @xealot says it should be an interface, it should be the type of the array element, for example, of the providers property of the Component decorator factory.

**Comment by IgorMinar** [comment]
done via #9751 and bec5c5fdad9e1d326e43ad5c4f9f5e17f135b66f

**Comment by jwoehrle** [comment]
I'm using APP_INITIALIZER along with the provide(...) function to call a service before any other services are loaded in my app.

However I don't understand how to use the APP_INITIALIZER which is the token for the call to 
`provide(token: any, {useClass, useValue, useExisting, useFactory, deps, multi}`

with the new object { provide : {...}}.

Are there any docs available?

**Comment by jwoehrle** [comment]
I found the solution here:

https://stackoverflow.com/questions/37611549/how-to-pass-parameters-rendered-from-backend-to-angular2-bootstrap-method/37611614#37611614
