### ISSUE TITLE
With Bootstrap, Use Tooltip, Need setup by executing javascript, How!? (2.0.0-rc.4)

### ISSUE THREAD

**Issue by liuxue0905** [angular/angular#9802]
2.0.0-rc.4
I use Bootstrap's Tooltip, Tooltip need execute follow javascript when ready:
````
$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
````
In Angular2,how to execute it?

**Comment by pkozlowski-opensource** [comment]
Please use a dedicated support channel for those types of questions: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
