### ISSUE TITLE
How To execute javascript in Angular2(2.0.0-rc.4)

### ISSUE THREAD

**Issue by liuxue0905** [angular/angular#9803]
2.0.0-rc.4

How to execute javascript, for dom etc.

in html:<button data-toggle="tooltip" type="button"/>
want execute: $('[data-toggle="tooltip"]').tooltip()
(tooltip is some valid method.)

In Angular2,how to execute it?

**Comment by pkozlowski-opensource** [comment]
See https://github.com/angular/angular/issues/9802#issuecomment-230316433

@liuxue0905 there is no point in opening the same issue with a support question here - it will be closed. Please read through https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
