### ISSUE TITLE
Testing pattern `async(inject(` is dangerously prone to developer errors

### ISSUE THREAD

**Issue by zakhenry** [angular/angular#9805]
**I'm submitting a**

```
[ ] bug report
[x] feature request
```

**Current behavior**
To declare an `it` block with `aync` and `inject`, the following is now required (now that https://github.com/angular/angular/pull/9564 is in rc.4)

``` ts
it('tests an async function on an injected object', async(inject([SomeService], (service: SomeService) => {

  const fixture = true;

  return service.asyncMethod()
    .then((result: any) => {
      expect(result).toEqual(fixture);
    });

})));
```

Besides being a _very_ verbose definition of a simple test, there is a very dangerous false-positive case where a developer forgets to add the async wrapper (or hasn't added yet it due to upgrading to rc.4), causing the test to _always pass_.

Eg:

``` ts
                                                   //note async() is omitted here
it('tests an async function on an injected object', inject([SomeService], (service: SomeService) => {

    return Promise.resolve()
      .then((result: any) => {
        expect(false).toEqual(true); //this code is never reached, and the test always passes
      });

  }));
```

**Expected/desired behavior**
Two options
1. If the return value of the inject function is a promise and not wrapped by `async`, throw error (probably hard to tell if wrapped)
2. Deprecate `async` and make all `inject()` methods check the return type, and if promise, process async. (my preference)

**Downsides**: Option 2 is different to the default jasmine behavior where a promise is ignore unless there is a done closure invoked. Therefore an overall preference would be extension of jasmine to handle promises by default, but that will basically be a reversion of the breaking change caused by #9564

**What is the motivation / use case for changing the behavior?**
Test frameworks should be ultra robust in the sense that it should be nearly impossible for a developer to forget to add something and have tests pass.

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.4
- **Browser:** [NodeJS 6.2.0 ] 
- **Language:** [TypeScript Version 1.9.0-dev.20160624-1.0]

**Comment by peterheard01** [comment]
I agree with this but I don't really know if there is a way to solve this problem since you are waiting for a system callback and at that point the test has no pointer to the instruction since it is invoked through a delegete (which calls back the other way). Unless you tell it to wait there isn't a way back, is there?

**Comment by brunolm** [comment]
I ran in this issue today...

It would be better if I could use `async/await` keywords only and not depend on `async` function anymore.

**Comment by vikerman** [comment]
With newer Jasmine (2.6/2.7) you can use async/await.

@kyliau - Add async/await example to #12409
