### ISSUE TITLE
Error when run in IE 11

### ISSUE THREAD

**Issue by slubowsky** [angular/angular#9808]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Using core.js to get app to run in IE 11 as recommended in docs. App mostly works but in one case it fails with an error:
`EXCEPTION: Error in http://localhost:4200/app/...info.html:7:30
   EXCEPTION: Error in http://localhost:4200/app/...info.html:7:30
   ORIGINAL EXCEPTION: Error: Invalid argument.
   ORIGINAL STACKTRACE:
   Error: Invalid argument.
   at BrowserDomAdapter.prototype.setProperty (eval code:76:76)
   at DomRenderer.prototype.setElementProperty (eval code:167:9)
   at DebugDomRenderer.prototype.setElementProperty (eval code:99:9)
   at _View_...InfoComponent4.prototype.detectChangesInternal (Function code:496:5)
   at AppView.prototype.detectChanges (eval code:243:9)
   at DebugAppView.prototype.detectChanges (eval code:348:13)
   at AppView.prototype.detectContentChildrenChanges (eval code:261:13)
   at _View_...InfoComponent1.prototype.detectChangesInternal (Function code:195:3)
   at AppView.prototype.detectChanges (eval code:243:9)
   at DebugAppView.prototype.detectChanges (eval code:348:13)
   ERROR CONTEXT:
   [object Object]
      {
         [functions]: ,
         __proto__: { },
         _nodeIndex: 0,
         _staticNodeInfo: { },
         _tplCol: 30,
         _tplRow: 7,
         _view: { },
         component: null,
         componentRenderElement: { },
         context: { },
         injector: { },
         providerTokens: [ ],
         references: { },
         renderNode: { },
         source: "http://localhost:4200/app/...info.html:7:30",
         Symbol()_n.tnb6sk636z9: undefined,
         Symbol(__immutablehash__)_p.tnb6sk636z9: undefined,
         Symbol(rxSubscriber)_o.tnb6sk636z9: undefined
      }
`

**Expected/desired behavior**
It should work as it does when run in Chrome (and Edge)

**Reproduction of the problem**
Problem is caused by the following code (which is actually the default case in a ngSwitch)
`<input ... type="{{field.type || text}}"/>`

Where in this particular case field.type was either undefined or "date". Changing {{field.type || text}} to "text" prevents the error (but causes no datepicker for my date fields on Chrome and Edge...)

Changing the undefined field.type's to "text" makes no difference, it still errors out. Adding single quotes around text in the expression didn't help either.

My work around for now is to use two different cases in my switch instead of combining them:
```
<input *ngSwitchCase="'date'" type="date" .../>
<input *ngSwitchDefault type="text".../>
```

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** IE 11
 
* **Language:** TypeScript

**Comment by zoechi** [comment]
Please provide a Plunker that allows to reproduce and demonstrates what polyfills are you loading in what order.

**Comment by slubowsky** [comment]
I am unable to reproduce in a plunker. It seems to work. Of course the scripts are loaded differently. My app was built using the cli and I added
<script src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.0/core.js"></script>
to index.html before it loads scripts.polyfills

**Comment by zoechi** [comment]
Then it seems to be an issue with your configuration. Such questions should be asked in one of the channels listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by msegers** [comment]
Slubowski if you get an update for this please add here, I'm facing this issue for about 2 weeks and I'm not sure where to go, I run the AngularClass's webpack starter config. Which should work for IE9+ even.

**Comment by vicb** [comment]
Please provide a minimal plunker with a repro. Thanks.
