### ISSUE TITLE
router 'name' attribute

### ISSUE THREAD

**Issue by imalhasaranga** [angular/angular#9809]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

throws an exception when i'm trying to use the name attribute in RouteConfig

`  { path: '/heroes', name:'hellow', component: Test },`

**What is the motivation / use case for changing the behavior?**

It seems like 'name' attribute is not longer in the Route interface, 

`export interface Route {
    path?: string;
    terminal?: boolean;
    component?: Type | string;
    outlet?: string;
    canActivate?: any[];
    canDeactivate?: any[];
    redirectTo?: string;
    children?: Route[];
}`

but I would say it is very much needed feature, so that we can loosely couple Route paths and the template. there are many times that we would like to change the paths and refine them to make more sense. 

**Please tell us about your environment:**

os x el capitan

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart]

**Comment by imalhasaranga** [comment]
A reply would be greatly appreciated, I believed 'name' attribute in the Route interface is kind of an Id to a particular path. if that is the case why it has been removed ? if there is any alternative to distinguish a path without matching the path would be great so that paths of the app can be easily changed even in the later.

**Comment by zoechi** [comment]
dup of #8674

**Comment by vsavkin** [comment]
@imalhasaranga The new implementation doesn't have the notion of route names and instead relies on redirects to achieve what you want. Having names prevents transparent lazy loading and creates other problems. The main purpose of using names was to enable refactoring. You can achieve the same result by using redirects. 

Closing this issue.
