### ISSUE TITLE
disableDeprecatedForms leads to "No provider for Token Platform Pipes! (CompilerConfig -> Token Platform Pipes)""

### ISSUE THREAD

**Issue by choeller** [angular/angular#9813]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Trying to call `disableDeprecatedForms` with the current master leads to:

No provider for Token Platform Pipes! (CompilerConfig -> Token Platform Pipes)

I'm using the short bootstrap-call looking like this:

```
bootstrap(AppComponent, [
  disableDeprecatedForms(),
  provideForms(),
  ...
]).catch(err => console.error(err));
```
when I remove `disableDeprecatedForms` the App Starts, but then gives me the warning about "deprecated forms"

**Expected/desired behavior**

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

App should not crash, when calling `disableDeprecatedForms` ;)

**Please tell us about your environment:**

* **Angular version:**  current master (3f55aa6)
 
* **Browser:** [all ] 
 
* **Language:** [TS]

**Comment by kara** [comment]
@choeller  Sorry about that.  Master has been in transition over the last few days, as we were updating to use app modules.  `disableDeprecatedForms()` is going away in RC.5, so as of this morning, it has been replaced by the module system described here: https://github.com/angular/angular/issues/9732.  You should be able to get the same effect by providing the FormsModule.

```ts
import {FormsModule} from '@angular/forms';

bootstrap(App, {modules: [FormsModule] });
```

Closing this issue, as this function will no longer be supported.

**Comment by wembernard** [comment]
Just a quick suggestion @kara: it might be useful to add this in the documentation https://angular.io/docs/ts/latest/cookbook/rc4-to-rc5.html

**Comment by kara** [comment]
Can you file an issue in the angular.io repo for that? :)

**Comment by wembernard** [comment]
done 👍
