### ISSUE TITLE
Warning if using @Input as function without "set" keyword

### ISSUE THREAD

**Issue by marcalj** [angular/angular#9814]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```

**Current behavior**
If I'm using ```@Input() end() { ... }``` I'm expecting to define a setter but if I forgot to define it, it doesn't warn me about the error.

I made a mistake, the correct code would be: ```@Input() set end() { ... }```

**Expected/desired behavior**
Compile error or warning.

**What is the motivation / use case for changing the behavior?**
Developer experience

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
  
* **Language:** [TypeScript 1.9]

**Comment by vicb** [comment]
An `@Input` can be a method.
