### ISSUE TITLE
router-outlet not triggering change-detection after component-insertion

### ISSUE THREAD

**Issue by akomm** [angular/angular#9818]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
~~Component `parent` has change-detection `OnPush` and has a `router-outlet` in its view. A component `child` is loaded inside the `router-outlet`. Component `child` uses the `ngClass` directive on a plain div element. When `child` is loaded initially inside the `router-outlet` the `ngClass` directive does not load its initial bound state.~~

After inserting a component, router-outlet does not trigger change-detection on the activated component.

**Expected/desired behavior**
~~When component `child` and its view is loaded inside `router-outlet`, ngClass should apply classes corresponding it the expression initially provided to it, as it does via direct inclusion as `view-child` inside of `parent` component (not via outlet).~~

Router-outlet should trigger change-detection after activating a component.

**Reproduction of the problem**
~~This plunker shows how the `child` component is loaded inside the `outlet`, but the `ngClass` is failing to apply classes with an initial state.~~

This plnkr shows, how ngStyle is not working properly when a component is activated with OnPush change-detection strategy:

http://plnkr.co/edit/mscwB0pMi8Cd0ahy0MCe?p=preview

**Please tell us about your environment:**
Ubuntu LTS 14.04 x64

* **Angular version:** 2.0.0-rc.4
* **Browser:** all
* **Language:** TypeScript 5.X

**Comment by akomm** [comment]
I'v just noticed, that the issue is, that the Component (child) loaded in the outlet does not get all the lifecycle events like "ngOnInit" and "ngAfterViewInit" triggered, etc. The components DOM is injected, but it is not loaded properly. It is an issue, I'v already encoutered previously under other circumstances.

**Comment by mhazy** [comment]
It appears that it's not related to OnPush, I've removed it from the plunkr and observed the same behaviour.

I've updated your plunkr to show that it will "work" once an event occurs. In the plunkr, it will apply the styles when the button is clicked.

If you remove `(click)` from the button, it will not apply the styling when clicked.

http://plnkr.co/edit/elIHygaRwrCOPH8cRgoI?p=preview

We've had similar behaviour the last few days when using back/forward in browser and getting un-styled components

**Comment by akomm** [comment]
I know that it works on next digest, I even had a version of the plnkr where i just did something like (click)="true". (I assume you did not mean it to be the solution, just as a note).

**Comment by mhazy** [comment]
@akomm this should be fixed in the next release (commit: 0c65d5cf2b8a0be760a27bdf43db9d1c8a3157a2) , the router outlet now calls change detection after components are created.

**Comment by akomm** [comment]
Awesome :)

**Comment by mhazy** [comment]
Related: #9565

**Comment by vsavkin** [comment]
Fixed here https://github.com/angular/angular/commit/0c65d5cf2b8a0be760a27bdf43db9d1c8a3157a2

**Comment by azjkjensen** [comment]
Did this make it into RC-4? I'm guessing not, but I just wanted to check.

**Comment by zoechi** [comment]
Fixed 15 days ago. Last release (RC.4) 1 month ago.

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20781496/370c5798-b7be-11e6-8421-df8d8d6f9e28.png)
![Uploading 图片.png…]()
