### ISSUE TITLE
[testing] custom Jasmine matchers like `toHaveText` are no longer available

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#9819]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Until `rc.3`, it was possible to have tests like: `expect(pony).toHaveText('Rainbow Dash');`.
Upgrading to `rc.4`, this throws `TypeError: testing_1.expect(...).toHaveText is not a function`.

I understand that now the jasmine functions are no more wrapped (following 40b907a657ec6aeb72d0661707a7842a867ac572), so we use directly the global jasmine functions.

But this was a really handy matcher along with others like `toHaveCssClass` (the work done in https://github.com/angular/angular/blob/master/modules/%40angular/platform-browser/testing/matchers.ts#L251 was non trivial). The matchers are sadly not exposed publicly as far as I can see in `@angular/platform-browser/testing`, which is used internally in the framework tests.
Maybe I'm missing something to make it works. Maybe @juliemr has the answer.

**Expected/desired behavior**
Matchers should still be available if they are going to stay. 
If they are still available, I think it is in an undocumented way.
If not, the breaking changes section of the changelog should at least mention that they are gone, and provide the easiest workaround for people who want to update their tests.

**Reproduction of the problem**

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all ] 
 
* **Language:** [TypeScript 1.9]

**Comment by pkozlowski-opensource** [comment]
This is a documented breaking change in RC.4: https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes

We no longer intend to provide matching utilities for Jasmine - you can use any of the existing 3rd party libraries to get custom matchers.
