### ISSUE TITLE
Components lifecycle and routing

### ISSUE THREAD

**Issue by alarive** [angular/angular#9820]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When clicking on a link pointing to the same route as current, components does not get reloaded.

**Expected/desired behavior**
I expect the ngOnInit method to be called the same way regardless of the fact that I'm already in the current Component.

**Reproduction of the problem**
http://plnkr.co/edit/RTFDgTmBHEoqGBOwB85k

* Open the dev console
* Click on "Home"
* the console displays "init home"
* Click on "News"
* the console displays "init news"
* Click on "Home" two times
* the console displays "init home" only one time.

**What is the expected behavior?**
In this example I would have expected ngOnInit to be called everytime I click on "home"

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
 
* **Browser:** [all ] 
 
* **Language:** [all ]

**Comment by zoechi** [comment]
This is as designed. You can subscribe to route params to do some initialization when they change https://angular.io/docs/ts/latest/guide/router.html#!#route-parameters

**Comment by zoechi** [comment]
You don't need to do the same job at different times. Move the code to another method and call it once from `ngOnInit` and on parameter change from `subscribe()`. Not recreating the component when only parameters change was explicitely added and `ngOnInit()` is only called once after the component is created. Deviating from the rule for this is not worth it especially as there is a simple way around.

**Comment by lpenet** [comment]
Well, thank you for advising on writing a method, I will check that. :-)

I can live with the component not being recreated, but why not also have a unique event when we route ?

**Comment by vsavkin** [comment]
> why not also have a unique event when we route ?

could you expand on that?

**Comment by vsavkin** [comment]
Closing this issue.
