### ISSUE TITLE
Router: Two children in different outlets both with an empty path.

### ISSUE THREAD

**Issue by peter-svintsitskyi** [angular/angular#9821]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see  https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question 
```

My app has two router outlets in the AppComponent:
```
    <router-outlet></router-outlet>
    <router-outlet name="secondary"></router-outlet>
```
Router config is the following:
```
[
  {
    path: 'prefix',
    children: [
      {
        path: '',
        component: InPrimaryOutletComponent,
        chidlren: [
          {path: 'a', component: AComponent},
          {path: 'b', component: BComponent},
        ]
      },
      {
        path: '',
        component: InSecondaryOutletComponent,
        outlet: 'secondary',
      }
    ]
  },
  {
    path: 'simple-works',
    component: WorksComponent,
  },
  {
    path: '',
    component: HomeComponent,
  }
]
```

I'd like to load different components in two outlets when current route starts with "/prefix".

**Current behavior**
Navigating to /prefix/a has no effect. 
"Cannot match any routes: 'prefix/a'" error appears in console

**Expected/desired behavior**
Navigating to /prefix/a loads AComponent in the primary outlet. The InSecondaryOutletComponent is displayed in another outlet.

**Reproduction of the problem**
See the http://plnkr.co/edit/U5PVNBYfrcaVvqpvocy6?p=preview

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart]

**Comment by joshi-mehul** [comment]
Hi, I just checked your code and the use case, do you know, you can use component. like prefix/a and prefix/b not as children, but as a different path, and then you can user 2 different component for the same and user component x for first path and component y for path 2, this is how you can achieve your use case. 

I am already using same with my app. :-)

**Comment by choucry13** [comment]
@joshi-mehul , do you an example to show please ? Thank you ^^

**Comment by vsavkin** [comment]
Fixed here https://github.com/angular/angular/pull/10246

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20782714/60f05eaa-b7c9-11e6-9006-f7beb8bef322.png)
