### ISSUE TITLE
RC4-Router: Get routes data outside of components with the router.events-subscription

### ISSUE THREAD

**Issue by cikg** [angular/angular#9822]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently, it's only inside a routed component possible to get the routes "data"-property.

`RouterConfig = [
    {
        path: 'thepath',
        data: {
            test: 'my-test-data'
        },
]`

Within a components ngOnInit, with a previos injected ActivatedRoute:

`this.route.data.subscribe(data => {
    console.log('data-subscription:', data);
});`

**Expected/desired behavior**
It should be possible to get the data-property with a router.events-subscription like this:

`this.router.events.subscribe(value => {

	if (value instanceof NavigationEnd) {

		console.log('Current routes data: ', this.router.routerState.snapshot.data);
	}
});`

**What is the motivation / use case for changing the behavior?**

In my case, it's about a service, which should handle breadcrumbs and tabs in an easy way. If I would be able to put some additional informations in the routes config, it would be must easier to realize and to have that kind of informations in a more central place (.routes.ts-files).

There might be much other cases, in which this behavior would be usefu, I think.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4

**Comment by zoechi** [comment]
Cross-ref http://stackoverflow.com/questions/38206488/angular2-rc4-router-get-the-routeconfigs-data-property-from-router-events-sub

**Comment by brandonroberts** [comment]
Check to see if this is what you're looking for https://github.com/angular/angular/issues/9662#issuecomment-229034288

The RouterState is a tree of ActivatedRoutes that you can walk up and down.

**Comment by vsavkin** [comment]
@brandonroberts +1 

You can walk the router state object and aggregate the data. Writing a function that does it should be straightforward. But because there are many ways to do the aggregation, i.e., the aggregation strategy can be app specific, I don't think the router should be responsible for it. Closing this issue.
