### ISSUE TITLE
i18nPlural pipe not working rc.4

### ISSUE THREAD

**Issue by m3chanic** [angular/angular#9826]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
platform-browser.umd.js:1900 ORIGINAL EXCEPTION: No provider for NgLocalization!

**Expected/desired behavior**
The i18nPlural pipe in the code below should output 'many items'. This had been working in rc.3

**Reproduction of the problem**
`import {Component} from '@angular/core';
import {I18nSelectPipe,I18nPluralPipe} from '@angular/common';

@Component({
  selector: 'i18n-mini-test',
  template: `<h1>Begin Test </h1>
             <br/><div>{{'hi' | i18nSelect : languageMapping}}</div>
             <br/><div>{{'bye' | i18nSelect : languageMapping}}</div>
             <br/>Number Items: {{numberItems}}
             <br/><div>{{numberItems | i18nPlural : itemPluralMapping}}</div>
             <h1>End Test</h1>
             `,
  pipes: [I18nSelectPipe, I18nPluralPipe]
})
export class i18nMiniComponent {

  itemPluralMapping: any;
  languageMapping: any;

  // Number of items being displayed, used for the plural mapping.
  //
  numberItems : number;

  constructor(){
    this.numberItems = 3;
    this.itemPluralMapping = {
      '=0' : 'no items',
      '=1' : 'one item ',
      '=2' : 'two items ',
      'other' : 'many items '
    };
    this.languageMapping = {
      'hi' : 'Hi',
      'bye' : 'Bye'
    };
  }
};
`

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all | Chrome 51.0.2704.103 ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart]

**Comment by m3chanic** [comment]
[i18nmini.component.ts.txt](https://github.com/angular/angular/files/348524/i18nmini.component.ts.txt)

**Comment by zoechi** [comment]
What about a Plunker?

**Comment by robisim74** [comment]
I already opened #9793 for this problem. You can solve by importing `NgLocalization `and injecting it, but after you will see another error: `ORIGINAL EXCEPTION: TypeError: ngLocalization.getPluralCategory is not a function`.
Plunker: http://plnkr.co/edit/WRaUI9vqyk6mLki6Gjor

**Comment by m3chanic** [comment]
Ok, Plunker [http://plnkr.co/edit/cfyX3lwuNaMVgiuFb5OK](url) created. The example is tied to rc.4 and shows the failure. Changing it to rc.3 will get i18nPlural working again. #9793 seemed more like a documentation issue. Since the current behavior deviates from the way i18nPlural worked in rc.3 it would seem more like a regression from rc.3 and rc.4. Also since it deviates from the way i18nSelect works it doesn't appear to work as the user would responsibly  expect.

**Comment by vicb** [comment]
This works as expected, the API doc is at https://github.com/angular/angular/blob/master/modules/@angular/common/src/directives/ng_plural.ts#L29 (we'll have a more detailed doc when i18n is ready).
