### ISSUE TITLE
queryParams subscription is alive while navigating away from current route

### ISSUE THREAD

**Issue by csreddy** [angular/angular#9827]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I'm subscribing to query params in ngOnInit(), its causing side-effects when navigated to different route. i.e., Before navigating away the change in params is causing to fetch data again before destroying the component. The subscription is however getting unsubscribed after the component gets destroyed as expected but the main issue is that subscription is kept alive during destroy event which causes redundant data fetch.

**Expected/desired behavior**
When navigated away from current route the, subscription should be destroyed 

**Reproduction of the problem**
http://plnkr.co/edit/CUb3dn?p=preview

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
* **Angular router:**'3.0.0-beta.2
* **Browser:** [all ] 
* **Language:** [TypeScript-1.9.0-dev.2016040]

**Comment by csreddy** [comment]
cc'ing @robwormald

**Comment by slubowsky** [comment]
Its not just a redundant data fetch. The query params being passed are the ones for the route we are navigating to. In my case this is causing major problems as the currently loaded component gets the new params and does things it shouldn't  since those params were never meant for this component.

**Comment by vsavkin** [comment]
Fixed here https://github.com/angular/angular/pull/10246
