### ISSUE TITLE
Angular RC 4 rxjs error with systemjs.config.js script references not apparent with CDN

### ISSUE THREAD

**Issue by maroebuck** [angular/angular#9829]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The website doesn't render in the browser using a script reference in systemjs.config.js (angular.io name). Gulp correctly copies the dependencies to wwwroot. (ASP.NET Core).

**Expected/desired behavior**
Angular 2 renders normally with CDN support.

**Reproduction of the problem**
When systemjs.config.js is as follows it works:

(function (global) {

    var ngVer = '@2.0.0-rc.4';
    var routerVer = '@3.0.0-beta.1';
    var formsVer = '@0.2.0';

    var map = {
        'app': 'app',
        '@angular': 'https://npmcdn.com/@angular',
        '@angular/router': 'https://npmcdn.com/@angular/router' + routerVer,
        '@angular/forms': 'https://npmcdn.com/@angular/forms' + formsVer,
        'rxjs': 'https://npmcdn.com/rxjs@5.0.0-beta.6',
        'ts': 'https://npmcdn.com/plugin-typescript@4.0.10/lib/plugin.js',
        'typescript': 'https://npmcdn.com/typescript@1.9.0-dev.20160409/lib/typescript.js'
    };

    var packages = {
        'app': { main: 'main.ts', defaultExtension: 'ts' },
        'rxjs': { defaultExtension: 'js' }
    };

    var ngPackageNames = [
      'common',
      'compiler',
      'core',
      'http',
      'platform-browser',
      'platform-browser-dynamic',
      'upgrade'
    ];

    ngPackageNames.forEach(function (pkgName) {
        map['@angular/' + pkgName] = 'https://npmcdn.com/@angular/' + pkgName + ngVer;
    });

    ngPackageNames.forEach(function (pkgName) {

        packages['@angular/'+pkgName] = { main: 'index.js', defaultExtension: 'js' };
    });

    packages['@angular/router'] = { main: 'index.js', defaultExtension: 'js' };

    packages['@angular/forms'] = { main: 'index.js', defaultExtension: 'js' };

    var config = {
        transpiler: 'ts',
        typescriptOptions: {
            tsconfig: true
        },
        meta: {
            'typescript': {
                "exports": "ts"
            }
        },
        map: map,
        packages: packages
    };

    System.config(config);

})(this);

I can change all the CDN references to script references except for rxjs which causes the website to stop displaying. This should work because all the examples I've seen using script references follow the same format:

Code snippet of systemjs.config.js that doesn't work:

    var map = {
        ...
        'rxjs': 'node_modules/rxjs',
       ...
    };

**What is the expected behavior?**
Angular 2 renders normally with CDN support.

**What is the motivation / use case for changing the behavior?**
I'd like to use Gulp and script references not CDN support.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** Microsoft Edge
 
* **Language:** TypeScript 1.9, ES5, ASP.NET Core

**Comment by pkozlowski-opensource** [comment]
This sounds like a support question that should be asked using an appropriate support channel: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
