### ISSUE TITLE
Router. provideRouter is not a function on page refresh when using webpack CommonsChunkPlugin

### ISSUE THREAD

**Issue by kamarouski** [angular/angular#9832]
It looks like there is an issue with the latest version of Router and Webpack CommonsChunk plugin.

I've created vendor.js and app.js as per guide here https://angular.io/docs/ts/latest/guide/webpack.html

On first load app works fine, but then if we try to refresh (F5) the page it generates an error:

_TypeError: router_1.provideRouter is not a function_

my app.routes.ts

```
import { provideRouter, RouterConfig } from "@angular/router";

import { MyRoutes } from './comp/comp.routes';

const routes: RouterConfig = [ ...MyRoutes ];

export const APP_ROUTER_PROVIDERS = [ provideRouter(routes) ];
```

Full refresh (Ctrl+F5) loads page correctly, but refresh get broken then.

Removing CommonsChunkPlugin fixes the problem.

**Update:** It seems to be Chrome only. I cannot reproduce it in Firefox or Edge

Environment:
OS: Windows 10
Browser: Chrome (latest)
Node/Express: 6.2.2/4.14.0
Webpack: 1.13.1

Angular: 2.0.0-rc4
Router: 3.0.0-beta.2

**Comment by amazingandyyy** [comment]
I have the same issue either with the following combination:
router alpha7,8 beta,1,2/ng: rc1,2,3,4

**Comment by vsavkin** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases--`provideRouter` was removed. Please update to the most recent Angular version.
