### ISSUE TITLE
Custom directives are not resolved when compiling app with compiler-cli

### ISSUE THREAD

**Issue by janis-r** [angular/angular#9834]
[x] bug report

**Current behavior**
I'm trying to pre compile Angular 2 RC4 application with compiler-cli and as it turns out my custom directive is not resolved as project is parsed with ngc.

My directive in short look like this:
import {Directive} from "@angular/core"
@Directive({
    selector: '[transform]'
})
export class TransformDirective {
...
}

Which leads to **Error: No Directive annotation found on TransformDirective**

**Expected/desired behavior**
No error and working directive available to Angular components.

**Reproduction of the problem**
Any directive used within ngc should reproduce this error as I've tried to strip all contents of class to see if that solves anything and it doesn't.

**Please tell us about your environment:**
Linux build server.

* **Angular version:** 2-rc.4
 
* **Language:** TypeScript 1.9.0-dev.20160627-1.0

**Comment by vicb** [comment]
obsolete
