### ISSUE TITLE
Response's status isn't matched actual status from server response.

### ISSUE THREAD

**Issue by devcken** [angular/angular#9835]
**Not matched Angular Response's status code and status from server response**  (check one with "x")
```
[O] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
As mentioned above, response's status is 400 but Angular Response says 200.
<img width="761" alt="2016-07-06 4 35 48" src="https://cloud.githubusercontent.com/assets/1279421/16610672/b9bd684e-4397-11e6-81b0-40c76297a393.png">

**Code**
Here's my code.
```
this._jsonp.get(url)
.subscribe(res => {
	console.log("OK");
	console.log(res);
}, error => {
	console.log("NOT OK");
	console.log(error)
});
```

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.1, 2.0.0-rc.4
 
* **Browser:** Chrome 51.0.2704.103(64-bit) 
 
* **Language:** TypeScript

**Comment by vicb** [comment]
Please provide a repro case in a plunker

**Comment by vicb** [comment]
I believe it has been fixed in RC4 (https://github.com/angular/angular/commit/12c49042abed8847a474c445271f9ba9830d3c18). Please re-open with a plunker otherwise
