### ISSUE TITLE
[rc.4] ddescribe doesn't work anymore

### ISSUE THREAD

**Issue by andrashatvani** [angular/angular#9836]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Using ddescribe results in the following error:
TypeError: undefined is not a constructor (evaluating '(0, _testing.ddescribe)')

**Expected/desired behavior**
The specs contained in the ddescribe block will be executed as with our previous version of angular2 rc.1.

**Reproduction of the problem**
We rerun the exact same test set which we used with rc.1 and the error will be thrown.

**What is the expected behavior?**
The specs contained in the ddescribe block will be executed as with our previous version of angular2 rc.1.

**What is the motivation / use case for changing the behavior?**
ddescribe is necessary to get fast feedback during development.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [PhantomJS] 
 
* **Language:** [TypeScript 1.8.10 | ES6/7 ]

**Comment by pkozlowski-opensource** [comment]
We are not patching Jasmine any more so what you need to use are Jasmine built-in methods. Jasmine doesn't have `ddescribe` but `fdescribe` instead.

More info: https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes
