### ISSUE TITLE
ngModel doesn't work on Inputs with variable type

### ISSUE THREAD

**Issue by ocombe** [angular/angular#9837]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
When the attribute type is specified with a variable, then ngModel doesn't work: it doesn't set the value nor does it detect changes (no ngModelChange events are triggered):
```ts
<input [(ngModel)]="selected" (ngModelChange)="test($event)" [type]="multiple? 'checkbox' : 'radio'">
```

It works fine if I set the type manually:
```ts
<input [(ngModel)]="selected" (ngModelChange)="test($event)" type="checkbox">
```

**Expected/desired behavior**
ngModel should work even if the type changes or is defined later. In my case it's defined before ngAfterViewInit because it's an @Input that defines it.

**Reproduction of the problem**
http://plnkr.co/edit/6X1itO2AO76bQmzzuX9Q?p=preview

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
 
* **Browser:** tested on Chrome & Firefox. On Firefox the initial event seems to work but not the ones after, on Chrome it never works.
 
* **Language:** all

**Comment by zoechi** [comment]
Looks like a dup of #7329

**Comment by ocombe** [comment]
You're right, sorry, closing this then!!
