### ISSUE TITLE
component not found in precompile array.

### ISSUE THREAD

**Issue by keyiis** [angular/angular#9838]
I update angular2 to rc.4 and refer to angular tour of heros,If i want use router then i must import component to app.router.ts first and import to app.component.ts precompile again,Otherwise I will be a warning,Got a better idea to import component in one place or other mehod in new release?
additional:the issuse occurs after I set '' redirectTo in RouterConfig.
```
{
    path: '',
    redirectTo: '/routea',
    pathMatch: 'full'
  },
```

**Comment by ericmartinezr** [comment]
Upgrde to router beta.2, see also https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
