### ISSUE TITLE
[Webworker] How to get information from nativeElement ?

### ISSUE THREAD

**Issue by Minh-Van** [angular/angular#9839]
Hello,
I'm doing some researches about webworker in Angular 2. 
As I know, Renderer is recommended for interaction with nativeElement. But Renderer only has methods for writing such as setElementProperty, setElementClass, setElementStyle....It has no any methods for reading information from nativeElement

So if I want to develop a component such as Tooltip, how can I get nativeElement's offset and necessary information from window/document ?

Because Renderer almost is used everywhere in Webworker, I think you should have documents in detail for it. Actually, It's hard to know what exactly Renderer can do if its document just like that 
https://angular.io/docs/ts/latest/api/core/index/Renderer-class.html

**Comment by kabir** [comment]
I have also been looking into this, and I also cannot see ways to e.g. get the dimensions of an element. Also for the best answer on http://stackoverflow.com/questions/35712379/angular2-close-dropdown-on-click-outside-is-there-an-easiest-way it seems that both ElementRef.nativeElement is lacking the methods, and also the event.target is null.

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
