### ISSUE TITLE
ROUTER:canActivate - Templates get requested before canActivate runs.

### ISSUE THREAD

**Issue by PEsteves8** [angular/angular#9840]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Consider the following:
1 - The cache is cleaned.
2 - A non authenticated user tries to access a page only for auth'd users.
3 - Before canActivate runs, the component's template tries to be accessed by angular, which fails, because the server is configured NOT to allow any requests from non auth'd users.
4 - Angular throws a "Failed to load" template exception.

**Expected/desired behavior**

Content should only be accessed if canActivate returns true. Otherwise, nothing should happen.

It's possible that there is a good reason for the current behavior that I just don't know about.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all | Chrome 51]
 
* **Language:** [all | TypeScript 1.8]

**Comment by brandonroberts** [comment]
Will you reproduce in a plunker?

**Comment by PEsteves8** [comment]
The best thing I can do is by using a slightly modified version of the familiar live demo of the Angular2 router:

1 - http://plnkr.co/edit/zyXPsrGAeKZQNf7l9RcV?p=preview
2 - The crisis-admin.component uses canActivate to check if the user is logged in.
3 - I changed one thing. I took the inline html template to an external file. 
4 - If you check the network tab with chrome's dev tools and click the Crisis Admin tab (you start 'logged out'), despite the fact that canActivate returns false, which implies that the component won't be loaded, the .html template file still gets requested. 
5 - If, for safety reasons a server has a protected folder, that is inaccessible unless a user is logged in, keeping things secure, both on the back-end and the front-end, a 401 unauthorized will be thrown.
6 - Ideally the .html wouldn't be requested since canActivate returned false anyway, making it unnecessary and allowing users to have access to data that they probably shouldn't.

**Comment by vsavkin** [comment]
When using offline compilation, which is a preferred way of building Angular 2 apps, templates get compiled into js code and bundled up with their components. In other words, you cannot reference a component and not its template. You always reference both.

The way it should be done is we should have the `canLoad` guard that we can put next to `loadChildren`. If such a guard returns false, we won't load the children and the navigation will fail. 

I've created an issue to track this work: https://github.com/angular/angular/issues/10250
