### ISSUE TITLE
(bug) Fragments at a route with an empty path

### ISSUE THREAD

**Issue by Niaro** [angular/angular#9842]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Current behavior**
If you have a home route with `path: ''` and multiple links to it with a fragment(hash) like for scrolling to a specific target, after refreshing of the page we will be redirected to nowhere or to NotFoundComponent if present.

**Reproduction of the problem**
Launch the plunk in a separate window. There are 3 links to HomeComponent with different fragments, then click the link with the fragment - all cool, URL has been changed. After that refresh the page,  and we are at NotFoundComponent... though it has to be HomeComponent.
http://plnkr.co/edit/zurGnezxPjj0ZiOkelKb?p=preview

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:**  I've checked chrome only
 
* **Language:** TypeScript

**Comment by Niaro** [comment]
By the way, I forgot to add... Guys, you are awesome!! Your work is pure inspiration! Thank you for your creation!

**Comment by vsavkin** [comment]
Fixed here https://github.com/angular/angular/pull/10246
