### ISSUE TITLE
Custom ExceptionHandler with routing

### ISSUE THREAD

**Issue by RaghavendhraK** [angular/angular#9843]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
Hi,
I tried to show the 500 error page, if any unhandled exceptions occurred

import { ExceptionHandler, Injectable } from '@angular/core';
import { Router } from '@angular/router-deprecated';
```
@Injectable()
export class AppExceptionHandler extends ExceptionHandler {
  constructor(private router:Router) {
    super(null, null);
  }
  call(exception:any, stackTrace?:any, reason?:string):void {
    console.log('call...')
    this.router.navigate(['CustomErrorPage']);
  }
}

bootstrap(MyApp, [
  provide(ExceptionHandler, {useClass: AppExceptionHandler})
]);
```
**Current behavior**
Error during instantiation of ApplicationRef_! (ApplicationRef -> ApplicationRef_).
	ORIGINAL EXCEPTION: Cannot instantiate cyclic dependency! (ExceptionHandler -> Router)

**Expected/desired behavior**
If any uncaught exception, it should redirect to Error page.

**What is the motivation / use case for changing the behavior?**
500 Internal server error page, instead of showing the loading symbol

* **Angular version:** 2.0.0-rc.X

**Comment by zoechi** [comment]
This sounds like a support question.

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by justinmchase** [comment]
The solution to this is to inject the `injector: Injector` into the constructor then use it in the call method to get the `Router`

```
call(exception, stack, reason) {
  if (!this.router) this.router = this.injector.get(Router)
  this.router.navigate(['CustomErrorPage'])
}
```
