### ISSUE TITLE
Not able to load @angular/platform-browser-dynamic - RC4

### ISSUE THREAD

**Issue by snkrishnan1** [angular/angular#9844]
When the application loads I am getting the following error.

http://localhost:49769/node_modules/@angular/platform-browser-dynamic/index.js Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/:21 Error: Error: XHR error (404 Not Found) loading http://localhost:49769/node_modules/@angular/platform-browser-dynamic/index.js
        at XMLHttpRequest.wrapFn [as _onreadystatechange] (https://npmcdn.com/zone.js@0.6.12?main=browser:769:30)
        at ZoneDelegate.invokeTask (https://npmcdn.com/zone.js@0.6.12?main=browser:356:38)
        at Zone.runTask (https://npmcdn.com/zone.js@0.6.12?main=browser:256:48)
        at XMLHttpRequest.ZoneTask.invoke (https://npmcdn.com/zone.js@0.6.12?main=browser:423:34)
    Error loading http://localhost:49769/node_modules/@angular/platform-browser-dynamic/index.js as "@angular/platform-browser-dynamic" from http://localhost:49769/app/main.js(anonymous function) @ localhost/:21
http://localhost:49769/node_modules/@angular/core/index.js Failed to load resource: the server responded with a status of 404 (Not Found)

I have explained in details about this issue in the stackoverflow 
http://stackoverflow.com/questions/38212731/not-able-to-load-angular-platform-browser-dynamic

Please let me know why I am facing this issue? How do I resolve it?

**Comment by pkozlowski-opensource** [comment]
Since this is a support question and you've already posted it on SO, there is no point in duplicating it here, see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
