### ISSUE TITLE
Code error on Template Syntax documentation page

### ISSUE THREAD

**Issue by m4ss1m0g** [angular/angular#9847]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

```
The example on doc page [Template Syntax](https://angular.io/docs/ts/latest/guide/template-syntax.html) at section _Custom events with EventEmitter_ missing the attribute @Output on code 

**Current behavior**

```
// This component make a request but it can't actually delete a hero.
deleteRequest = new EventEmitter<Hero>();
```

**Expected/desired behavior**

```
// This component make a request but it can't actually delete a hero.
@Output
deleteRequest = new EventEmitter<Hero>();
```

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all]
 
* **Language:** [all]

**Comment by vicb** [comment]
Please submit documentation issues on https://github.com/angular/angular.io.

Also note that an output could also be declared on the `@Component()` config, it does not have to be a prop decorator.
