### ISSUE TITLE
click event on child component being called using preventDefault() when pressing enter on any form inputs

### ISSUE THREAD

**Issue by qdouble** [angular/angular#9848]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
```

**Current behavior**
To prevent the click event from a child button from submitting the form, I put $event.preventDefault() on the click event of the button on the child... however, once I do that, if I press enter on any of the input fields, the click event on the child input fires off. 

**Expected/desired behavior**
Expect to be able to press enter on any of the input fields and it submits the form and not fire of the child click event. 

**Reproduction of the problem**
http://plnkr.co/edit/ADDco2sPz2Qhm026VLwb?p=preview 
Just press press enter on any of the inputs and then check the console log to see it firing the click event on the child component.

**What is the expected behavior?**
Pressing enter on the inputs should submit the form, not  fire the click event on child input. 

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4

**Comment by zoechi** [comment]
Sounds like http://stackoverflow.com/a/12914700/217408

> The reason is because a button inside a form has it's type implicitly set to submit. As zzzzBoz says, the Spec says that the first button or input with type="submit" is what is triggered in this situation. If you specifically set type="button", then it's removed from consideration by the browser.

**Comment by zoechi** [comment]
http://plnkr.co/edit/eTN7AGPqeK63oiZmuh19?p=preview

**Comment by qdouble** [comment]
@zoechi Thanks a lot, that solves it. So it's just a browser thing and not angular specific issue. Will close.
