### ISSUE TITLE
ref binding with attribute components

### ISSUE THREAD

**Issue by hrajchert** [angular/angular#985]
Hi! Most of the examples I see are for element components like `<google-youtube>` and in ng-conf, misko show how you can get a hold to the component  API [using ref binding (#)](https://www.youtube.com/watch?v=-dMBcqwvYA0&list=PLOETEcp3DkCoNnlhE-7fovYvqwVPrRiY7&t=1128)

But what happens if I have attribute components, like `tooltip` coexisting with the element one. Can I get a reference to them?

If I have the following:

```html
<google-youtube tooltip="My tooltip" #myElement ></google-youtube>
```

and the `google-youtube` API exposes methods like `play()` or `pause()` and the tooltip component methods like `show()` or `hide()`, what would be accesible from the `myElement` binding?

I think of two possibilities, either merging the components API, which could cause a lot of trouble or maybe adding a different syntax where you could have

```html
<google-youtube tooltip="My tooltip" #myElementRef #tooltip="myTooltipRef" >
</google-youtube>
```

**Comment by vsavkin** [comment]
You can get a reference to any directive on the element as follows:

```
@Directive({
  exportAs: 'myTooltip'
})
class TooltipDir {}
```

Used in the template as follows:

```
<google-youtube #youtubeRef #tooltipRef="myTooltip" tooltip="Some tooltip">
```

Does it solve your problem?

**Comment by pkozlowski-opensource** [comment]
@vsavkin just to be sure - we can't use mixed cases in templates, so one would have to write `<google-youtube #youtube-ref #tooltip-ref="myTooltip" tooltip="Some tooltip">`, right?

**Comment by vsavkin** [comment]
I didn't know about that! I thought youtubeRef just gets lowercased.

**Comment by hrajchert** [comment]
This feature is not implemented yet, right? 
If so, why would you add the `-ref`?

Couldn't we just use the name of the directive with a hash before it?

```html
<google-youtube tooltip="My tooltip" #myElementRef #tooltip="myTooltipRef" >
```

**Comment by pkozlowski-opensource** [comment]
@hrajchert HTML is not case-sensitive so browsers will "auto-correct" all the attributes making them lower-cased. In short - you can't have attributes / tag names with mixed case - browsers see them as all lower-cased...

**Comment by hrajchert** [comment]
Yes, im not talking about camel casing. My example was unfortunate, I wanted to focus on `#tooltip` rather than `myElementRef`

Maybe this is clearer? 

```html
<google-youtube tooltip="My tooltip" #my-element-ref #tooltip="myTooltipRef" >
```

The idea here would be that my-element-ref points to the google-youtube API and myTooltipRef to the tooltip API

**Comment by vsavkin** [comment]
>> This feature is not implemented yet, right? 
 
It is implemented. 
 
>> Couldn't we just use the name of the directive with a hash before it?

The way it works is as follows:

- The directive author provides the exportAs name
- The developer using the directive can use that name on the right hand side of the variable binding. 

See here https://github.com/angular/angular/issues/2313

**Comment by hrajchert** [comment]
Ok, so @vsavkin, Just to see if I understood correctly

Assuming I have a component called `google-youtube` and a directive called `tooltip`

The minimum code would be

```html
<google-youtube tooltip="This text appears while I hover">
```

And if I want to have a different handler for each of their API I would do this

```html
<google-youtube #element-ref tooltip="This text appears while I hover" #my-tooltip-ref="tooltip-ref">
```

where the ref are `element-ref` and `my-tooltip-ref` and the tooltip directive must have this annotation

```
@Directive({
  exportAs: 'tooltip-ref'
})
class TooltipDir {}
```

Am I correct?

**Comment by vsavkin** [comment]
Yup. You are correct.

**Comment by hrajchert** [comment]
Cool, then feel free to close this issue
