### ISSUE TITLE
Safe navigation operator executes members after "?." even if not needed

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular#9850]
**I'm submitting a ...**  (check one with "x")

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Current behavior**
Safe navigation operator can be used to prevent Angular from throwing errors, when trying to access object properties of objects that don't exist.

E.g.

```
{{ contact?.name }}
```

Only evaluates `name` when `contact` is not `null` or `undefined`. This comes in handy when `contact` is something that is loaded asynchronously.

However, let's say we have another object on `contact`

```
contact: {
  name: 'foo',
  address: {
    street: 'bar'
  }
}
```
If we want to access `street` in the template even though, `contact` is loaded asynchronously, we can use the safe navigation operator for that. **But** we need to apply it on **every nested property** because Angular doesn't ignore the rest of an expression after a `?.`.

Here's what we need to do to render `street`, even though, `address` is synchronous:

```
{{ contact?.address?.street }}
```

**Expected/desired behavior**

Angular should ignore member accesses after `?.` inside expressions when the thing before the `?.` is `null` or `undefined`. Or, in code, we should be able to simply do:

```
{{ contact?.address.street }}
```

**Reproduction of the problem**
Plunk: http://plnkr.co/edit/TaoC2w0sSx1izwiqAoJQ?p=preview

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** all 
 
* **Language:** TypeScript 1.9

**Comment by wardbell** [comment]
I'm piling on.  This isn't just our opinion about how the "save navigation operator" AKA "null conditional operator" should work.

Here's [a primary source](https://github.com/dotnet/roslyn/wiki/New-Language-Features-in-C%23-6#null-conditional-operators) of this idea  ... .net of all places.

>​**The null-conditional operator exhibits short-circuiting behavior**​ [emphasis mine], where an immediately following chain of member accesses, element accesses and invocations will only be executed if the original receiver was not null:
```
int? first = customers?[0].Orders.Count();
```
>This example is essentially equivalent to:
```
int? first = (customers != null) ? customers[0].Orders.Count() : null;
```
>Except that `customers` is only evaluated once. ​**None of the member accesses, element accesses and invocations immediately following the ? are executed unless `customers` has a non-null value.**​  [emphasis mine]
>
>Of course null-conditional operators can themselves be chained, in case there is a need to check for null more than once in a chain:

```
int? first = customers?[0].Orders?.Count();
```

**Comment by vicb** [comment]
The **null-conditional operator** is not the **safe navigation operator** [emphasis mine ;)]

I think [we are consistent](https://en.wikipedia.org/wiki/Safe_navigation_operator) with other languages

**Comment by PascalPrecht** [comment]
> The null-conditional operator is not the safe navigation operator [emphasis mine ;)]

It's called **null-conditional operator** on wiki too.

@vicb If you refer to the code snippets in different languages on the wiki page, those don't give any context about what the nested properties look like, or rather if they exist or not.

I'm not into Swift or Groovy, but how do we know that in the sample

```
def name = article?.author?.name
```

`author` is synchronous/static or not? Can we verify, that you'd still do `article?.author?.name` even if `author` is always **not** null?

**Comment by wardbell** [comment]
Hey ... wait a second. The very wikipedia article you cite says that they ARE the same thing.

>the safe navigation operator (also known as optional chaining operator, safe call operator, null-conditional operator)

It also cites (approvingly) the .net example.

More importantly, the other citations are MUTE on short-circuiting. I'm betting that at least some, if not all, of them implement short-circuiting.

And now I see that Pascal said essentially the same thing.

**Please re-open and reconsider** or at least offer a more compelling answer.

**Comment by pkozlowski-opensource** [comment]
Agree with @wardbell - could we look into this some more? I appreciate that this is consistent, but it is consistent in a way that doesn't make my live, as a developer, any easier.

**Comment by vicb** [comment]
> Can we verify, that you'd still do article?.author?.name even if author is always not null?

> I'm betting that at least some, if not all, of them implement short-circuiting.

> could we look into this some more?

Yes please look more into this, we'll re-open if needed (ie the behavior is implemented in other langs)

**Comment by PascalPrecht** [comment]
@davideast I know you've done some Swift, can you verify *our* expected behaviour?

**Comment by Blasz** [comment]
Coffeescript short circuits, [see this example](
http://coffeescript.org/#try:A%20%3D%20b%3F.c.d).

**Comment by vicb** [comment]
@chuckjaz shows me that short circuiting is the norm, re-opening.

**Comment by Vandivier** [comment]
I find myself running into this again with Angular 5.2.1

Doesn't throw:
    {{ article?.parent?.title }}

Throws:
    {{ article?.parent.title }}
