### ISSUE TITLE
benchpress doesn't handle microMetrics for first run if page is reloaded in samle code

### ISSUE THREAD

**Issue by 4vanger** [angular/angular#9854]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
https://www.dropbox.com/s/5jarbld9vt5j6bf/Screenshot%202016-07-06%2015.04.15.png?dl=0
As you can see - microMetrics are 0 for first run.

**Expected/desired behavior**
microMetrics should be measured correctly on first load.

**Reproduction of the problem**
Get https://github.com/angular/benchpress-tree and change "execute" value to
```
execute: function() {
  browser.get('http://localhost:8080/tree.html?depth='+depth);
},
microMetrics: {'page loaded': 'page loaded'},
```
then add somewhere on a test page
```
console.time('page loaded');
....
console.timeEnd('page loaded');
```

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [Chrome 51] 
 
* **Language:** [all

**Comment by 4vanger** [comment]
I've digged inside a problem a little but and it is some kind of race condition - it is happening in perflog_metric.ts#255 - this condition fails on a first run:
```
event['pid'] === markStartEvent['pid']
```
Here is some timeline to illustrate the problem - logging events from readPerfLog()
```
...
{ pid: 38580,
  ph: 'b',
  cat: 'timeline',
  ts: 469571834.635,
  name: 'benchpress0' }
....
{ pid: 38585,
  ph: 'I',
  cat: 'timeline',
  ts: 469572078.205,
  name: 'sendRequest',
  args: 
   { url: ''http://localhost:8080/tree.html',
     method: 'GET' } }
....
{ pid: 38585,
  ph: 'b',
  cat: 'timeline',
  ts: 469572140.239,
  name: 'page loaded' }
```
As you can see - benchpress0 is logged with a different browser pid so events cannot be aggregated.
What's interesting is that PID is changed right after benchpress0 event is logged - so maybe it is happening too early

**Comment by tbosch** [comment]
This is fixed on master.
