### ISSUE TITLE
*ngIf directive behaves strangely when parent element has click handler attached.

### ISSUE THREAD

**Issue by golear91** [angular/angular#9855]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I have a bootstrap button that uses glyphicons to signify different states

    <button (click)="clickSaveButton($event)" type="button" class="btn btn-default dropdown-toggle board-button"  id="dropdownAddToBoard" data-toggle="dropdown"
        aria-haspopup="true" aria-expanded="false">
        <span *ngIf="!productSaved()" class="glyphicon glyphicon-heart-empty"></span><span *ngIf="productSaved()" class="glyphicon glyphicon-heart"></span><br />Save<span *ngIf="productSaved()">d</span>
      </button>

the clickSaveButton function is supposed to be triggered on button click to execute before passing event along to bootstrap to handle the toggling of the dropdown.  When I click anywhere on the button (not the glyphicon) it works as expected.  When I click on the glyphicon, the function gets called, but the dropdown does not open as expected.
I've seen similar behaviour before using an *ngIf directive within an element where the click handler gets messed up.

**Expected/desired behavior**
Click the glyphicon should not have any discernible difference from clicking the rest of the button.

I've worked around the problem by using a span with no *ngIf directive

    <span class="glyphicon" [class.glyphicon-heart-empty]="!productSaved()" [class.glyphicon-heart]="productSaved()" ></span>

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

* **Angular version:** 2.0.0-rc.3
 
* **Browser:** [Chrome latest (extension) ] 
 
* **Language:** [TypeScript 1.8.1]

**Comment by vicb** [comment]
Could you please simplify your example with the least amount of code required to reproduce the issue and provide a plunker. Thanks.

**Comment by vicb** [comment]
Closing as no repro is provided
