### ISSUE TITLE
Error: overrideDirective is not supported in this implementation of TestComponentBuilder.

### ISSUE THREAD

**Issue by nottinhill** [angular/angular#9857]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

```
  it('should select all <ion-title> directives matching text="Cancel"', () => {
        return tcb
        .overrideDirective(
                 MyComponent, MySubComponent, MockMySubComponent
        )
        .createAsync(MyComponent).then((fixture) => {
        ...
```

> Error: overrideDirective is not supported in this implementation of TestComponentBuilder.

**Expected/desired behavior**

Expecting overrideDirective to work with TestComponentBuilder. I am using Angular2 RC-4

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

Overriding Directives in Tests

**What is the motivation / use case for changing the behavior?**

Unit Testing

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all | Chrome Version 51.0.2704.106 (64-bit)] 
 
* **Language:** [ "typescript@~1.8.7",]

**Comment by vicb** [comment]
> Error: overrideDirective is not supported in this implementation of TestComponentBuilder.

It's a known limitation of this implementation and will be fixed in a future release.

@juliemr @vikerman more info to add ?

**Comment by Bolza** [comment]
I opened a [question on stackoverflow](http://stackoverflow.com/questions/38351639/angular2-rc4-overridedirective/38353661#38353661) about this  and then i found that using `OverridingTestComponentBuilder` can be a viable workaround. Is there anything that we should know about this class?

Also why this change is not documented in the changelog?

**Comment by juliemr** [comment]
I'll post on SO as well, but this was not a breaking change because our test providers should give you an `OverridingTestComponentBuilder` by default. How are you setting up your test? (e.g. `setBaseTestProviders`? Using the lists provided by Angular should fix your problem. Here's an example: https://github.com/juliemr/ng2-test-seed/blob/master/karma-test-shim.js#L84

**Comment by Bolza** [comment]
Pretty much the same, only my test-setup is not async :/

```
import {setBaseTestProviders} from '@angular/core/testing';
import {
	TEST_BROWSER_DYNAMIC_PLATFORM_PROVIDERS,
	TEST_BROWSER_DYNAMIC_APPLICATION_PROVIDERS
} from '@angular/platform-browser-dynamic/testing';
setBaseTestProviders(TEST_BROWSER_DYNAMIC_PLATFORM_PROVIDERS,
	TEST_BROWSER_DYNAMIC_APPLICATION_PROVIDERS);

```

**Comment by juliemr** [comment]
@Bolza interesting, you should be just getting an `OverridingTestComponentBuilder` by default then. You can see the rest of my setup in that repository: https://github.com/juliemr/ng2-test-seed

I use the `TestComponentBuilder` to overrides things there. Could you do some searching and see if there's anything special in your setup that might be overriding the test providers somehow?
