### ISSUE TITLE
OnInit is not called when I type URL in IE [HashLocationStrategy] 

### ISSUE THREAD

**Issue by lohiarahul** [angular/angular#9860]
https://github.com/lohiarahul/Angular2-Silverlight-Starter

The above link can be used to reproduce the problem.

I have used the OnInit hook to initialize the silverlight control from inside a component. When I navigate to the silverlight view for the first time, all the lifecycle events are called. However, after that, the lifecycle events are only called when I route to the 'silverlight' view by click on the anchor tag. If I directly type the URL in the address bar, only the constructor is called and my silverlight plugin is not loaded

The problem seems to occur in IE and not in Chrome.

**Comment by zoechi** [comment]
Please provide a Plunker that allows to reproduce (template https://angular.io/resources/live-examples/quickstart/ts/plnkr.html)

**Comment by vsavkin** [comment]
Fixed here https://github.com/angular/angular/commit/f08060b0b00c98341c7e1fd9acb984402c280396
