### ISSUE TITLE
Angular1_router | How to unit test code insdie $canActivate hook

### ISSUE THREAD

**Issue by pranav-xx** [angular/angular#9863]
I am submitting this to check what is the recommended way to unit test code inside $canActivate.

I am currently using angular1_router with angular js 1.5. While all other lifecycle hooks are written inside controller, I can unit test them.

But since $canActivate is part of component configuration inside an IIFE, how to unit test it?

**Comment by vsavkin** [comment]
I don't think the issue makes sense in the context of the new router (@angular/router). If you think this is the case, please reopen it.
