### ISSUE TITLE
No change detection and no model update when model update is done within a setInterval()

### ISSUE THREAD

**Issue by dragGH102** [angular/angular#9865]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
```

**Current behavior**
every 2 seconds, setInterval() checks for offline status via window.navigator and stores it in component's isOnline property.

isOnline is initially true but if at any time (when the check is made, i.e. every 2s) becomes false, I want to

- show an overlay in the app  (=class "{{!isOnline ? 'overlay' : '')}}")
- show a message (via [hide] or *ngIf"

For simplicity in the plunkr  just added a {{isOnline}} which prints the current value which should be online when browser is online and offline when browser if offline).

**Expected/desired behavior**

isOnline is always shown as "true" (or false if the method setConnectivity is called the **outside** of setInterval and there if no internet connection).

I also tried with

**ngDoCheck()** (console.log(this.isOnline)) and apparently isOnline is always equal to the initial value, despite I set it explicitly every 2 seconds.

**Reproduction of the problem**
https://plnkr.co/edit/8w82r3fNvWKAxc4P0gdK?p=preview
(I'm aware it uses beta.0 but I didn't want to invest too much time in something like this. The bottom line is the issue is there both on beta.0 and rc.2 I'm using)

**environment:**

* **Angular version:** 2.0.0-**rc.2**
 
* **Browser:** tested only in **Chrome**
 
* **Language:** *TypeScript** 1.8.10

**Comment by zoechi** [comment]
That's a browser issue. Chrome (52.0.2743.24 Linux) always returns `true` for `window.navigator.onLine` and also doesn't emit `online` and `offline` events.
Firefox 45 at least returns `false` for `window.navigator.onLine` but I also didn't get the events.

**Comment by dragGH102** [comment]
@zoechi this is not true. Chrome returns true and false regularly

**Comment by zoechi** [comment]
I only got `true` printed in the console every 2 seconds even in offline mode.
In Firefox the binding in the view that shows the state updated just fine.

**Comment by dragGH102** [comment]
@zoechi I don't intend to argue of course, but in Chrome (latest version I think: 47.0.2526.80 (64-bit)) it works.

**How to reproduce**: 

- open the plunkr with active internet connection
- open Chrome Dev Tools
- every 2s it will print "true" to console
- disconnect your computer from Internet
- after a few seconds you'll see it prints false to console
- .. and then back true if you re-enable Internet connection

**Comment by awerlang** [comment]
You're incorrectly updating the binding on the component.

```js
setInterval(() => this.checkConnectivity(), 2000);
```

**Comment by dragGH102** [comment]
thanks @awerlang . Your solution works. Can you explain **what is the difference**?

**Comment by dragGH102** [comment]
(I'll close the issue in any case)

**Comment by awerlang** [comment]
Inside `checkConnectivity`, `this` points not to your component, but to `window` (in browser environment), so you update a field in the wrong context. I prefer to call a method like this from another, arrow function.

It is important to get this right. To know more about the `this` keyword, I recommended reading https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this
