### ISSUE TITLE
bug(testing) ngOnChanges not called for component initialized via TestComponentBuilder

### ISSUE THREAD

**Issue by choeller** [angular/angular#9866]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When creating a component via TestComponentBuilder the ngOnChanges-Callback is not executed. Having a component like this:

``` ts
export class TimePickerComponent {

  @Input("time") private timeString = "";

  ngOnInit() {
    console.log("init")
  }
  ngOnChanges(changes) {
    console.log("changes");

    //do some transformation on the timeString- inputbinding
    }
  }
...
}
```

And creating the component in the test like this:

``` ts
 it('display passed time in input fields', (done) => {
    tcb
      .createAsync(TimePickerComponent)
      .then(fixture => {
        let timePicker: TimePickerComponent = fixture.componentInstance;
        (<any>timePicker).timeString = "11:20:23";
     //   timePicker.ngOnChanges(null);  ->> needs to be called manually
        fixture.detectChanges();

        let hourInput = fixture.debugElement.query(By.css('#hours > input'));
        expect(hourInput.nativeElement.value).toBe("11");
        done();
      });
  });
```

the ngOnChanges callback of the component gets never called. (ngOnInit gets called by the way). To fix the test it is currently needed to call ngOnChanges manually... 

**Expected/desired behavior**

ngOnChanges should be called while initializing the component

**What is the motivation / use case for changing the behavior?**

Being able to test components that use ngOnChanges callback without having to call the method manually

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.4
- **Browser:** [all ] 
- **Language:** [all]

**Comment by nertzy** [comment]
We are seeing this as well. We don't want to call it manually in our tests because part of what we are testing is that we properly handle the actual SimpleChanges objects that Angular would send us. So the workaround won't help for our case.

**Comment by nertzy** [comment]
This is still an issue with the fixture returned from TestBed in rc5 and rc6.

**Comment by DmitryEfimenko** [comment]
this is still an issue in Angular 2.0 Final Release

**Comment by chadbr** [comment]
I'll throw in a "me to" :)

**Comment by forforeach** [comment]
I'm working with angular 2.1 and still meeting this issue.

**Comment by StdVectorBool** [comment]
My interpretation of these two pages is that you can only expect ngOnChanges() to be called if the data-binding is updated by Angular and not your direct manipulation:
https://angular.io/docs/ts/latest/api/core/index/OnChanges-class.html
https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html#!#onchanges

Here's an example where a test host data-binds to time-pickers input and ngOnChanges correctly firing when the input changes due to a data-binding update:
https://plnkr.co/edit/84gFtoT7FgEiew8brp9L?p=preview

**Comment by nertzy** [comment]
Is it more appropriate to inject NgZone and then make the change inside of an ngZone.run() call?

**Comment by StdVectorBool** [comment]
The ngZone.run() will probably work, but I was basing my comments on the guidance from the official testing guide.
https://angular.io/docs/ts/latest/guide/testing.html#!#component-inside-test-host

**Comment by DzmitryShylovich** [comment]
can somebody reproduce in plunkr? u can use http://plnkr.co/edit/Ph8CxhfUm0vHhTq3UBdo?p=preview as a starting point

**Comment by kevindqc** [comment]
@DzmitryShylovich http://plnkr.co/edit/1RnC7gAF7PmqHFskUCVU?p=preview

Just changed the template from "hello {{name}}" to "{{calculatedName}}", the "hello " is supposed to be added by ngOnChanges, but it never gets called so calculatedName is always empty.

**Comment by ilyabasiuk** [comment]
met same issue with 2.2.4

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular/issues/9866#issuecomment-261631059 is absolutely right. To me it works as expected...

**Comment by StdVectorBool** [comment]
I understand why the framework specifies the event model for ngOnChanges that way but the behavior from the testing infrastructure is not intuitive.  The majority of comments in the thread suggest the natural expectation is that the test code should automatically be executed in an ngZone as if it was application code.

Granted there are other things in the existing testing infrastructure (fixture.detectChanges(), fakeAsync(), tick()) that already establish a convention that this seamlessness can't be expected... so perhaps this just needs better documentation in the Testing manual?

**Comment by mizhou901101** [comment]
If I understand correctly, you manually changed the input value in the component instance. Basically the OnChanges hook is triggered when inputs are passed via the view only. Please read this answer: http://stackoverflow.com/questions/37408801/testing-ngonchanges-lifecycle-hook-in-angular-2

**Comment by mmmichl** [comment]
I would actually expect that `fixture.detectChanges();` will trigger the `ngOnChange` callback as it anyways synchronises the state between the component and the view...

In any case, this needs to be clarified in the docs as suggested by @StdVectorBool.

**Comment by DzmitryShylovich** [comment]
> this needs to be clarified in the docs

file an issue on https://github.com/angular/angular.io/issues

**Comment by seanharr11** [comment]
It burdensome and arguably impractical to create a dummy parent component just to have it pass a value via Input() to trigger ``ngOnChanges()``. This especially true when unit testing.

Why is it that ``detectChanges()`` cannot trigger the ``ngOnChanges()`` hook?

**Comment by merlosy** [comment]
I'm unit testing on Angular version 4.4.5
Using `detectChanges()` worked for me.

I have a parent component that encapsulate the component I am testing.
``` js
[...]

let component: MyComponent;
let fixture: ComponentFixture<ParentMyComponent>;

[...]

beforeEach(() => {
    fixture = TestBed.createComponent(ParentMyComponent);
    component = fixture.debugElement.children[0].componentInstance;
    fixture.detectChanges();
});

[...]
it('should call ngOnChanges', () => {
    const spy = spyOn(component, 'ngOnChanges');
    fixture.componentInstance.data = {options: 'test'};
    fixture.detectChanges();
    expect(spy).toHaveBeenCalledTimes(1);
});
```

Test is successful 👍

**Comment by pcroc** [comment]
Can this issue be reopened, as the angular.io repository has been archived and the docs still need updating.

**Comment by ambroiseRabier** [comment]
> ```js
> 
>     expect(spy).toHaveBeenCalledTimes(1);
> ```

Using Angular 7.2 it is not working for me. `ngOnChanges` just isn't called.

**Comment by Zax37** [comment]
Can confirm this bug is still occurring in 7.2.

**Comment by Itrulia** [comment]
Still happens in Angular 8 aswell
