### ISSUE TITLE
FormGroup is valid only if all its fields are valid

### ISSUE THREAD

**Issue by sroucheray** [angular/angular#9867]
```
[ x] feature request ?
```

**Current behavior**
As stated in the [doc ](https://angular.io/docs/ts/latest/api/forms/index/FormGroup-class.html) a FormGroup is valid only if all its fields are valid.

**Expected/desired behavior**
I am new to Angular so maybe someone can enlighten me on the API choice, but it seems to me that there are use cases where a group could be valid if only some of its `FormControl`s are valid (not all).

**Reproduction of the problem**
Use case: user has the choice between entering a city name or a latitude + longitude. Latitude and longitude must be valid numbers. The group is valid if the city name is entered or if latitude + longitude are entered and valid.
I posted a longer version of this use case here http://stackoverflow.com/questions/38204812/angular2-forms-validator-with-interrelated-fields

I also created a plunker here https://plnkr.co/edit/9H4SWxAnIdNHJU3bCwZr?p=preview
Using validators at the fields level result in the group being valid only if all three fields are valid. So one has to fall to validator at the group level. The plunker use a validator at the group level but it has several drawbacks: 
- the 3 fields always have the ng-valid class
- the validator function is not composed of small validators thus being harder to test or even to read

Questions: 
- Is FormGroup being valid only when some of its fields are valid, a correct use case ?
- What can I do with angular to get around this issue ?

# Environment
* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all] 
 
* **Language:** [TypeScript] 

Thanks for the hard job !

**Comment by zoechi** [comment]
I guess `city` should not be invalid if filling `latitude` and `longitude` instead is fine as well. Only if both or none are filled they should be invalid.

**Comment by sroucheray** [comment]
@zoechi I think the validity of `city` should not be linked to the validity of `latitude` and `longitude` at all. Only the group validity is affected by the validity of its controls but it should not necessarily be valid if **all** controls are valid.

**Comment by laserfists** [comment]
I think the current behaviour is correct, a FormGroup is just a logical container for FormControls. If any of the controls happen to be invalid the group should be invalid by default. I wrote an "any" validator for the situation similar to the one you describe (at least one control inside the group should have a value) and I think in this instance it makes sense to handle this validation at the "group" level because:

- an individual control being falsy is not necessarily invalid (a control should only care about itself), but;
- for the group to be valid, at least one control should have a value
- validation for individual controls can still exist outside validation for the group

```
static any(group: ControlGroup): { [key: string]: boolean } {
    return Object.keys(group.controls).map(k => group.controls[k].value).filter(e => e).length > 0 ? null : { any: false };
}
```

**Comment by zoechi** [comment]
Maybe excluding https://github.com/angular/angular/blob/3f08efa35dd334c61127fc8059b4d73b2bd0b866/modules/%40angular/forms/src/model.ts#L504 one or the other helps to avoid validation.

**Comment by kara** [comment]
@sroucheray Thanks for the detailed issue.  What you describe is certainly a common and valid use case, but there are ways to support it with the current system. As @jmcgoldrick mentioned, generally the correct level to handle validations that require checking sibling controls is the parent group.  You can either write an "any" validator on the group level or disable one of the location options as the user interacts with the other (as @zoechi suggested).  Given these alternatives, I don't think a breaking change this huge confers enough benefit. The current behavior will make sense for most forms.

**Comment by makarov-roman** [comment]
@jmcgoldrick It's not working for me.
If I understand properly validator can only set errors field to AbstractControl.
But AbstractControl will still invalid if one of childs is invalid
https://github.com/angular/angular/blob/00497437a6773ddab2c2a7c66a626eee48aad2d5/packages/forms/src/model.ts#L594-L600
