### ISSUE TITLE
Component Router does not work with Upgrade Adapter

### ISSUE THREAD

**Issue by ptomaszi** [angular/angular#9870]
When trying to use the Angular 2 Component Router (Angular 2 RC 4) with the upgrade adapter I got the following error:

> Bootstrap at least one component before injecting Router. at setupRouter

This is my main.ts file:

```
angular.module(moduleName).directive('App', upgradeAdapter.downgradeNg2Component(AppComponent));

upgradeAdapter.addProvider(APP_ROUTER_PROVIDERS);

upgradeAdapter.bootstrap(document.body, [moduleName]);
```

I google the problem and found the following links, but they all correspond to the router deprecated module as the Angular team changed how the router works since RC4:

https://github.com/angular/angular/issues/7147?_pjax=%23js-repo-pjax-container

Any ideas?

**Comment by brandonroberts** [comment]
@ptomaszi try injecting the router in your `AppComponent` and calling `initialNavigation()`

**Comment by ptomaszi** [comment]
This is my app.routes.ts file:

```
import { provideRouter, RouterConfig } from '@angular/router';

import { WelcomeComponent } from './index';

export const routes: RouterConfig = [
    { path: 'welcome', component: WelcomeComponent }
];

export const APP_ROUTER_PROVIDERS = [
    provideRouter(routes)
];
```

How can I inject that to my AppComponent?

```
import { APP_ROUTER_PROVIDERS } from './app.routes';

export class AppComponent implements AfterViewInit {
    constructor(private router: APP_ROUTER_PROVIDERS ) { ????
    }
```

**Comment by brandonroberts** [comment]
@ptomaszi you inject the `Router`

```js
import { Router } from '@angular/router';

export class AppComponent implements AfterViewInit {
    constructor(private router: Router) {
        router.initialNavigation();
    }
```

**Comment by ptomaszi** [comment]
@brandonroberts Thanks for your quick responses. 

Unfortuanatelly the "router" object does not provide "initialNaviagation" method. I can only access the following properties:

- createUrlTree
- events
- navigate
- navigateByUrl
- parseUrl
- resetConfigs
- routerState
- serializeUrl
- url

Am I using a wrong version of router? I have updated it today to use the following version:

"@angular/router": "3.0.0-beta.2".

**Comment by brandonroberts** [comment]
@ptomaszi no, its marked as internal, but until that is removed you'll have to access the private method.

```js
router['initialNavigation']()
```

**Comment by ptomaszi** [comment]
@brandonroberts The following error comes before the APP component is initialised and constructor method called, so I cannot call the "initialNaviagtion" private method on the router as it is not yet available to be injected:

```
Error: Bootstrap at least one component before injecting Router.
    at setupRouter (http://localhost:3000/vendor/@angular/router/src/common_router_providers.js:19:15)
    at DebugAppView._View_OdetteSecureAppComponent0.createInternal (OdetteSecureAppComponent.template.js:61:23)
    at DebugAppView.AppView.create (http://localhost:3000/vendor/@angular/core/src/linker/view.js:96:21)
    at DebugAppView.create (http://localhost:3000/vendor/@angular/core/src/linker/view.js:308:44)
    at DebugAppView._View_OdetteSecureAppComponent_Host0.createInternal (OdetteSecureAppComponent.template.js:23:14)
    at DebugAppView.AppView.create (http://localhost:3000/vendor/@angular/core/src/linker/view.js:96:21)
    at DebugAppView.create (http://localhost:3000/vendor/@angular/core/src/linker/view.js:308:44)
    at ComponentFactory.create (http://localhost:3000/vendor/@angular/core/src/linker/component_factory.js:157:36)
    at DowngradeNg2ComponentAdapter.bootstrapNg2 (http://localhost:3000/vendor/@angular/upgrade/src/downgrade_ng2_adapter.js:37:51)
    at post (http://localhost:3000/vendor/@angular/upgrade/src/upgrade_adapter.js:539:28)
```

**Comment by brandonroberts** [comment]
@ptomaszi I believe this issue will be resolved in the next RC and Router release once AppModules land. @vsavkin can confirm.

**Comment by brandonroberts** [comment]
@ptomaszi `provideRouter` is being deprecated as of RC5, so as a disclaimer this is subject to change but since you're using ngUpgrade, you'll need to override the `ApplicationRef` in the `providers` of your `AppComponent`

Plunker: http://plnkr.co/edit/vpLkEY?p=preview

**Comment by ptomaszi** [comment]
@brandonroberts your solution works as expected! Is the solution provided temporary or it will be the same approach for any further router releases?

**Comment by ptomaszi** [comment]
If we added app router providers at the "app component" level, does it mean other components will not be able to see routes defined in the "app.routes.ts" file? I have the following "app.component":

```
import { AfterViewInit, ApplicationRef, Component, Injector } from '@angular/core';
import { Router, ROUTER_DIRECTIVES } from '@angular/router';

import {   
    appRouterProviders,   
    upgradeAdapter,
    WelcomeComponent    
} from './index';

@Component({
    moduleId: module.id,
    selector: 'my-app',
    templateUrl: 'my-app.component.html',
    directives: [ROUTER_DIRECTIVES],
    providers: [
        appRouterProviders, {
            provide: ApplicationRef,
            useValue: {
                componentTypes: [OdetteSecureAppComponent],
                registerDisposeListener: () => { }
            }
        }]
})
export class MyAppComponent implements AfterViewInit {            
    constructor(private router: Router) {
        router['initialNavigation']();
    }    
}
```
The HTML for the "MyAppComponent" looks like:

`<router-outlet></router-outlet>`

"app.routes.ts" file looks like:

```
import { provideRouter, RouterConfig } from '@angular/router';
import {    
    WelcomeComponent,
    welcomeRoutes
} from './index';

export const routes: RouterConfig = [
    ...welcomeRoutes,
    { path: '', component: WelcomeComponent }    
];

export const appRouterProviders = [
    provideRouter(routes)
];
```
The "Welcome component" has the following HTML:

<a [routerLink]="['/register']">Click</a>

I also have the "welcome.routes.ts" file defined as:

```
import { RouterConfig } from '@angular/router';
import { UserRegistrationComponent } from '../index';

export const welcomeRoutes: RouterConfig = [
    { path: 'register', component: UserRegistrationComponent }
];
```
When I click the "Click" anchor it does not show me my user registration component. The only way to get that working is to move "router link" HTML to the "My App Component" HTML template. Am I doing something wrong?

**Comment by 3du4** [comment]
RouterConfig and provideRouter are not available anymore. Did this change with 2.0.1 and 2.0.2?

**Comment by brandonroberts** [comment]
@3du4 RouterConfig and provideRouter we deprecated and removed prior to 2.0 release.

**Comment by 3du4** [comment]
@brandonroberts Thank you for your comment. I am having a similar problem when calling downgradeNg2Component method just before bootstrapping my app using the upgrade adapter:  `Error: Bootstrap at least one component before injecting Router.`

Do you know what would be a workaround for this? Thank you in advance.

**Comment by 3du4** [comment]
@brandonroberts updating Angular to 2.1.0 solved the issue.

**Comment by brandonroberts** [comment]
@3du4 yes, that restrictions no longer exists in version 3.1.0 the router.

**Comment by dezoxel** [comment]
`"@angular/router": "3.1.1"` doesn't call initial navigation.

Calling initialNavigation() in AppComponent fixed the issue:
```
...
export class AppComponent {
  constructor(router: Router) {
    router.initialNavigation();
  }
}
```
