### ISSUE TITLE
Extra forward slash when referencing UMD files

### ISSUE THREAD

**Issue by anthonysapien** [angular/angular#9871]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Testing in Angular 2 RC4. Requests are being made for
http://localhost:3000/node_modules/@angular/http//bundles/http.umd.js
Notice the double forward slash between "http" and "bundles"
This is working fine when testing locally with lite-server, but when deploying to Google Firebase, the files are returning 404s.

**Expected/desired behavior**
Expecting a single forward slash between "http" and "bundles"
http://localhost:3000/node_modules/@angular/http/bundles/http.umd.js

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

This is easily reproducible with the Angular 2 quickstart project. Just run npm start and check the network tab in Google Chrome.

Removing the forward slash before "bundles" in system.config.js seems to fix the issue:
packages['@angular/'+pkgName] = { main: '/bundles/' + pkgName + '.umd.js', defaultExtension: 'js' };
packages['@angular/'+pkgName] = { main: 'bundles/' + pkgName + '.umd.js', defaultExtension: 'js' };

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

Simple deployment to Firebase.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
Chrome 51
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart] 
TypeScript, ES5

**Comment by csaltmountain** [comment]
👍 
I noticed this too when trying to deploy to AWS S3.

**Comment by IgorMinar** [comment]
This is an issue with systemjs config and not our bundles. The only action item on our end is to fix the quick start instructions at https://angular.io/docs/ts/latest/quickstart.html by removing the leading slash from the value of the `main` property as suggested above.

Ward, can you please take a look? Thanks!

**Comment by IgorMinar** [comment]
I filed an issue for quickstart: https://github.com/angular/quickstart/issues/242
