### ISSUE TITLE
Code Generated using the offline compiler uses `void` incorrectly

### ISSUE THREAD

**Issue by hansl** [angular/angular#9875]
I'm submitting a bug report.

## Current Behavior

You can see the files here: https://gist.github.com/hansl/35c57c75faacad2805dc8450b8fc5a51

The ngfactory is the Tabs component. The tabs component code is included as reference.

[Lines 206-207](https://gist.github.com/hansl/35c57c75faacad2805dc8450b8fc5a51#file-tabs-d-ngfactory-ts-L206-L207) of tabs.d.ngfactory.ts return a value in a void function, which is an error.

This seems to happen because the QueryList has some `ngIf` or `ngFor` directives around it.

## Versions
* Latest master of Angular
* Custom branch of Material2: https://github.com/angular/material2/tree/offline-compiler

**Comment by chuckjaz** [comment]
Left open for @tbosch to review fix.

**Comment by chuckjaz** [comment]
From @tbosch:

Could we change the fix to do the following:

- keep the ts emitter as is, i.e. emit a `void` if no return type is given in the output ast. So we stay in sync with the other codegen places where omitting the type means `void` (we also don't have a type of `void` in the OutputAst`).
- change the part that creates the output ast to create a `FunctionExpr` with a `DYNAMIC_TYPE` as return type. By adding `o.DYNAMIC_TYPE` as 3rd argument to the `o.fn` call that is passed to `mapNestedViews` in `compile_query.ts` [here](https://github.com/angular/angular/blob/master/modules/@angular/compiler/src/view_compiler/compile_query.ts#L108).

**Comment by chuckjaz** [comment]
See #10047 which contains the recommended fix and reverts the previous fix (but keeps the test changes).
