### ISSUE TITLE
Router:  provideRouter(config) should spread route definition arrays for us

### ISSUE THREAD

**Issue by wardbell** [angular/angular#9876]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report
[x] feature request
[ ] support request 
```

**Current behavior**

When accumulating routes today we write this:

```
export const routes: RouterConfig = [
  ...HeroesRoutes,
  ...LoginRoutes,
  ...CrisisCenterRoutes
];

export const APP_ROUTER_PROVIDERS = [  provideRouter(routes), ...];
```

It's easy for developers to forget the spread operator `...`. They shouldn't have to worry about it just as they don't worry about it when setting up the `providers` array for component metadata.

**Expected/desired behavior**

We'd like to write them like this:

```
export const routes: RouterConfig = [
  HeroesRoutes,
  LoginRoutes,
  CrisisCenterRoutes
];
```

... and rely on `provideRouter` to spread them out.

**Reproduction of the problem**

See `app.routes.ts` in [plunker for router chapter](https://angular.io/resources/live-examples/router/ts/plnkr.html)

**Comment by DzmitryShylovich** [comment]
is this still actual with the new router api?
