### ISSUE TITLE
Dynamically adding & removing components with DynamicComponentLoader.loadNextToLocation(...) broken on upgrade to RC 4 using ViewContainerRef

### ISSUE THREAD

**Issue by borangejabil** [angular/angular#9877]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Expected/desired behavior**
I am currently working on a project that I upgraded from Angular 2 beta 13 to RC 4. 
Before the upgrade, the ability to dynamically add and remove a simple component (a simple spinner) to any page that was in the process of loading data worked fine, using this service: 

(SinnerService.ts):
-----------------------------------------------------------------------------------------------------------------
import {Injectable, DynamicComponentLoader, ApplicationRef, ElementRef, ComponentRef} from '@angular/core';

import {Spinner} from './spinner';

@Injectable()
export class SpinnerService {
    spinnerComp: ComponentRef;

    constructor(private _componentLoader: DynamicComponentLoader, private _appRef: ApplicationRef) {
    }

    public start() {
        let elementRef: ElementRef = this._appRef['_rootComponents'][0].location;

        return this.startInside(elementRef, null);
    }

    public startInside(elementRef: ElementRef, anchorName: string) {

        let spinnerRef = (!anchorName) ?
            this._componentLoader.loadNextToLocation(Spinner, elementRef, anchorName) :
            this._componentLoader.loadNextToLocation(Spinner, elementRef);

        spinnerRef.then((compRef: ComponentRef) => {
            this.spinnerComp = compRef;
        });
    }

    public stop() {
        if (this.spinnerComp) {
            this.spinnerComp.dispose();
        }
    }
}
-----------------------------------------------------------------------------------------------------------------

**Current behavior**
During the upgrade, changes were made to the class to match the changes made to Angular 2.
The resulting file causes a exception to occur, which is shown underneath the updated code: 

(SinnerService.ts):
-----------------------------------------------------------------------------------------------------------------
import {Injectable, DynamicComponentLoader, ApplicationRef, ViewContainerRef, ComponentRef} from '@angular/core';

import {Spinner} from './spinner';

@Injectable()
export class SpinnerService {
    spinnerComp: ComponentRef<any>;

    constructor(private _componentLoader: DynamicComponentLoader, private _appRef: ApplicationRef) {
    }

    public start() {
        let elementRef: ViewContainerRef = this._appRef['_rootComponents'][0].location;

        return this.startInside(elementRef, null);
    }

    public startInside(elementRef: ViewContainerRef, anchorName: string) {

        let spinnerRef = (!anchorName) ?
            this._componentLoader.loadNextToLocation(Spinner, elementRef) :
            this._componentLoader.loadNextToLocation(Spinner, elementRef);

        spinnerRef.then((compRef: ComponentRef<any>) => {
            this.spinnerComp = compRef;
        });
    }

    public stop() {
        if (this.spinnerComp) {
            this.spinnerComp.destroy();
        }
    }
}
-----------------------------------------------------------------------------------------------------------------

The error: 
-----------------------------------------------------------------------------------------------------------------
EXCEPTION: Error: Uncaught (in promise): TypeError:
location.createComponent is not a function
	browser_adapter.ts:82

EXCEPTION: Error: Uncaught (in promise): TypeError: 
location.createComponent is not a functionBrowser	DomAdapter.logError @ browser_adapter.ts:82
	browser_adapter.ts:82

STACKTRACE:BrowserDomAdapter.logError @ browser_adapter.ts:82
	browser_adapter.ts:82

Error: Uncaught (in promise): TypeError: 
location.createComponent is not a function
at resolvePromise (zone.js:538)
at resolvePromise (zone.js:523)
at zone.js:571
at ZoneDelegate.invokeTask (zone.js:356)
at Object.onInvokeTask (ng_zone_impl.ts:61)
at ZoneDelegate.invokeTask (zone.js:355)
at Zone.runTask (zone.js:256)
at drainMicroTaskQueue (zone.js:474)
at XMLHttpRequest.ZoneTask.invoke (zone.js:426)	BrowserDomAdapter.logError @ browser_adapter.ts:82	zone.js:461 

Unhandled Promise rejection: location.createComponent is not a 
function ; Zone: angular ; Task: Promise.then ; Value: TypeError: 
location.createComponent is not a function(…)	consoleError @ zone.js:461
	zone.js:463 

Error: Uncaught (in promise): TypeError: location.createComponent is not a function(…)
-----------------------------------------------------------------------------------------------------------------

After a lot of reading and experimenting, I tried a different approach using the ComponentResolver, which, unfortunately, also gave the same error (below code).  
(SinnerService.ts):
-----------------------------------------------------------------------------------------------------------------
import {Injectable, DynamicComponentLoader, ApplicationRef, ViewContainerRef, Component, ComponentRef, ComponentResolver, ComponentFactory, ViewChild} from '@angular/core';

import {Spinner} from './spinner';

@Injectable()
export class SpinnerService {
    spinnerComp: ComponentRef<any>;

    constructor(private _componentLoader: DynamicComponentLoader, private _appRef: ApplicationRef,
                private _resolver: ComponentResolver) {
    }

    public start() {
        let elementRef: ViewContainerRef = this._appRef['_rootComponents'][0].location;

        return this.startInside(elementRef, null);
    }

    public startInside(elementRef: ViewContainerRef, anchorName: string) {

        //let spinnerRef = (!anchorName) ?
        //    this._componentLoader.loadNextToLocation(Spinner, elementRef) :
        //    this._componentLoader.loadNextToLocation(Spinner, elementRef);

        //spinnerRef.then((compRef: ComponentRef<any>) => {
        //    this.spinnerComp = compRef;
        //});

        let spinnerRef = this._resolver.resolveComponent(Spinner);

        spinnerRef.then((factory: ComponentFactory<any>) => {
            this.spinnerComp = elementRef.createComponent(factory)
        });
    }

    public stop() {
        if (this.spinnerComp) {
            this.spinnerComp.destroy();
        }
    }
}
-----------------------------------------------------------------------------------------------------------------

The error: 
-----------------------------------------------------------------------------------------------------------------
EXCEPTION: Error: Uncaught (in promise): TypeError: 
elementRef.createComponent is not a function	
browser_adapter.ts:82

EXCEPTION: Error: Uncaught (in promise): TypeError: 
elementRef.createComponent is not a function	BrowserDomAdapter.logError @ browser_adapter.ts:82	browser_adapter.ts:82
STACKTRACE:BrowserDomAdapter.logError @ browser_adapter.ts:82
	browser_adapter.ts:82

Error: Uncaught (in promise): TypeError: 
elementRef.createComponent is not a function
at resolvePromise (zone.js:538)
at zone.js:574
at ZoneDelegate.invokeTask (zone.js:356)
at Object.onInvokeTask (ng_zone_impl.ts:61)
at ZoneDelegate.invokeTask (zone.js:355)
at Zone.runTask (zone.js:256)
at drainMicroTaskQueue (zone.js:474)
at XMLHttpRequest.ZoneTask.invoke (zone.js:426)
BrowserDomAdapter.logError @ browser_adapter.ts:82
	zone.js:461 

Unhandled Promise rejection: elementRef.createComponent is not a 
function ; Zone: angular ; Task: Promise.then ; Value: TypeError: 
elementRef.createComponent is not a function(…)		consoleError @ zone.js:461
	zone.js:463 

Error: Uncaught (in promise): TypeError: elementRef.createComponent is 
not a function(…)	consoleError @ zone.js:463
	SignalRService.js:40 Event hub started.
-----------------------------------------------------------------------------------------------------------------

What is the expected behavior?
For the class to work as it did before the upgrade, i.e. we should be able to add and remove the basic component (the simple spinner service) to any page loading data via this service. 

**What is the motivation / use case for changing the behavior?**
This seems like a vital part of the Angular 2 framework that seems to be depeicated (https://angular.io/docs/js/latest/api/core/index/DynamicComponentLoader-class.html), with no explanation or replacement. 

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [Chrome Latest Version ] 
 
* **Language:** [TypeScript]

**Comment by codespicelabs** [comment]
DynamicComponentLoader has been deprecated since RC1 afaik. use
check out new stuff here
https://github.com/angular/angular/tree/master/modules/%40angular/core/src/linker

Use ComponentResolver and ViewContainerRef directly. (C)
> DynamicComponentLoader
>

**Comment by borangejabil** [comment]
Good Morning,

Thank you for the quick reply.

As you can see from my examples, I did use the ComponentResolver and
ViewContainerRef , but I ended up getting the same error.
Could it be that I was not using them correctly in that sample?
Is there a code sample or some place where the correct usage of the
components is described?

Thanks,
Bill

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

See http://stackoverflow.com/questions/36325212/angular-2-dynamic-tabs-with-user-click-chosen-components/36325468#36325468 for a full example.

**Comment by chuckjaz** [comment]
Wrong reference

**Comment by tbosch** [comment]
Could we change the fix to do the following:

- keep the ts emitter as is, i.e. emit a `void` if no return type is given in the output ast. So we stay in sync with the other codegen places where omitting the type means `void` (we also don't have a type of `void` in the OutputAst`).
- change the part that creates the output ast to create a `FunctionExpr` with a `DYNAMIC_TYPE` as return type. By adding `o.DYNAMIC_TYPE` as 3rd argument to the `o.fn` call that is passed to `mapNestedViews` in `compile_query.ts` [here](https://github.com/angular/angular/blob/master/modules/@angular/compiler/src/view_compiler/compile_query.ts#L108).

**Comment by chuckjaz** [comment]
Moving comment to correct issue.

**Comment by borangejabil** [comment]
Hi, 
I was on vacation for a week. 
chuckjazz - were any of the comments you posted here intended for this bug?
Thanks, 
Bill

**Comment by vicb** [comment]
I think @chuckjaz was referring to the comment from @tbosch right above his which is not related to this issue.

**Comment by borangejabil** [comment]
I thought so, but wanted to be sure.

**Comment by chuckjaz** [comment]
Sorry for the confusion. A typo in an issue reference caused me to update this bug accidentally.

**Comment by borangejabil** [comment]
No worries. 
Things happen. :)

**Comment by vicb** [comment]
Seems like this issue was re-opened by accident...
If not please let us know.Thanks.
