### ISSUE TITLE
Error messages upon executing "npm install"

### ISSUE THREAD

**Issue by sosc-nc** [angular/angular#9880]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Error messages upon executing "npm install" using 5 Min Quickstart files from https://angular.io/docs/ts/latest/quickstart.html. Please see attached log file.

[npm-debug.log.txt](https://github.com/angular/angular/files/352977/npm-debug.log.txt)

**Expected/desired behavior**

Expected functioning install.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [ Firefox 46  ] 
 
* **Language:** [ TypeScript X.X ]

**Comment by vicb** [comment]
Please re-open on https://github.com/angular/angular.io
