### ISSUE TITLE
Exclude node_modules from being compiled in quickstart example

### ISSUE THREAD

**Issue by thomasjshafer** [angular/angular#9884]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ ] feature request
[x] suggestion
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The `.tsconfig.json` in the [ts quickstart](https://angular.io/docs/ts/latest/quickstart.html#!#create-and-configure) example tells typescript to compile all `node_modules`. This makes the compilation quite slow.

Although this is consistent with the [expected tsconfig.json](https://angular.io/docs/ts/latest/guide/typescript-configuration.html#!#tsconfig), this is placed in the root of the project.

**Expected/desired behavior**

change `.tsconfig.json` to include the `exclude` keyword.

```json
{
  "compilerOptions": {
    ...
  },
  "exclude": [
    "node_modules"
  ]
}
```

**What is the motivation / use case for changing the behavior?**

It is not necessary to have a top level tsconfig.json tell TypeScript to compile all `node_modules`.

**Comment by vicb** [comment]
Please re-open on https://github.com/angular/angular.io

**Comment by thomasjshafer** [comment]
great, thanks! I was looking for the docs!
