### ISSUE TITLE
Feature request: NgModules -> css bundling

### ISSUE THREAD

**Issue by b-strauss** [angular/angular#9890]
**I'm submitting a ...**
```
[x] feature request
```
**Expected/desired behavior**
Introduce a way to bundle css with the help of NgModules (see #9726). These styles would only be usable/scoped to the components inside the NgModules.

**What is the motivation / use case for changing the behavior?**
Sharing styles between multiple components is currently not supported out of the box. The user either has to insert these styles globally into the head, or copy them into each component's individual stylesheet. Both of these solutions are problematic.

**Comment by b-strauss** [comment]
I just thought about this again. Would it be practical to let a NgModule define two "sets" of styles? One set to be used internally, and the other set to be used externally.

Made up API:
```typescript
@NgModule({
  // styles to be used in all components, internally
  styles: [],
  styleUrls: [],
  // styles to be imported by the module that uses this module
  exportedStyles: [],
  exportedStyleUrls: []
})
```

The question is: should the importing module see these styles automatically, or should it explicitly declare if it wants to import them or not? Maybe they could conflict with its own styles. If so, how would it be able to declare that?

**Comment by pkozlowski-opensource** [comment]
Actually Tobias is tracking it here: #11682 - let's centralize the discussion in one place. Closing as a duplicate.
