### ISSUE TITLE
Child routes are not resolved properly when using outlets

### ISSUE THREAD

**Issue by websiddu** [angular/angular#9892]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When navigating to the sub route like products/1 the Product component is not initiated. 

```  
{
    path: 'products',
    component: Products,
    canActivate: [AuthGuard],
    children: [
      { path: ':id', component: Product }
      { path: '', component: Sidebar, outlet: 'sidebar' },
      { path: '', component: Products }
    ]
  }
```

**Expected/desired behavior**
Should load the child component and resolve the id

**Reproduction of the problem**
http://plnkr.co/edit/i7sONA?p=preview

**What is the expected behavior?**
The products/1 should load the product details

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
* **Angular router:** 3.0.0-alpha.8
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [TypeScript ]

**Comment by christopherhill** [comment]
Were you able to resolve this? I was also able to reproduce nearly identical behavior with Angular 2.0.0-rc.4 and Angular router 3.0.0-beta.2.

**Comment by zoechi** [comment]
Why are you not using router beta.2? What's the purpose of having two routes with empty path?
