### ISSUE TITLE
Parent and  dynamic children communicate via a service

### ISSUE THREAD

**Issue by keyiis** [angular/angular#9906]
There is a scene,I used viewContainerRef.createComponent to create BComponent in AComponent and through ABservice to communicate between then.below is error and my code:
----------error----------
`Error: DI Exception↵    at NoProviderError.BaseException [as constructor] `
----------ABService-----------
```
import { Injectable } from '@angular/core';
@Injectable()
export class ABService {
    config: Object;
    setConfig(_config: Object) {
        this.config = _config;
    }
}
```
-----------Acomponent----------
```
@Component({
 ......,
  providers: [ABService]
})
export class AComponent {
  constructor(private abservice:ABService) {
  edit() {
    this.abservice.setConfig({.... });
  }
}
```
----------BComponent----------
```
import {Component} from "@angular/core";
import {ABService} from "./table.service";
@Component({
    selector: 'custom-table',
    template: require('./table.component.html')
})
export class BComponent {
    config: Object;
    constructor(private abservice:ABService) {  }
}
```

**Comment by skreborn** [comment]
Please provide a [Plunker](https://plnkr.co/edit/) next time that reproduces your error. Anyway, this sounds like a support question, so I suggest you move it to an [appropriate channel](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question).

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) for support request.
