### ISSUE TITLE
Inject service from façade file into another service (rc4)

### ISSUE THREAD

**Issue by smnbbrv** [angular/angular#9907]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I have a services façade file (services.ts) which exports all services from particular services files, let's say

    export * from './my-service.service';

Then I have another service file my-service2.service.ts where I try to inject my-service:

    import { MyService } from '../services';

    @Injectable()
    export class MyService2...

Then the standard procedure: include the injected service into global providers, etc.

Problem is that it is not getting injected. Error text:

> Unhandled Promise rejection: Can't resolve all parameters for MyService2: (?, ...)

I tried changing asterisk to a concrete exported name, does not help. But if I import the file directly from the service file that my my-service2.service.ts looks like

    import { MyService } from '../my-service.service';

    @Injectable()
    export class MyService2...

it works very well.

**Expected/desired behavior**

Well, I believe it should be still injectable. The generated JS file has all decorators etc, so I don't really understand where the problem comes from...

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all] 
 
* **Language:** [TypeScript 1.8.10]

**Comment by pkozlowski-opensource** [comment]
> so I don't really understand where the problem comes from...

Me neither based just on the textual description. Please provide a minimal reproduce scenario using plunker, as requested in the issue template. Otherwise it is not actionable and will be closed.

**Comment by smnbbrv** [comment]
cannot reproduce it with plunkr... Most likely it has something to do with my TS / Angular versions. Perhaps should be closed then. I come back if I can reproduce it.

**Comment by kemsky** [comment]
I have observed the same problem. 

It is really difficult to trace injector problem in a large project, it is almost impossible to build dependency tree manually, because transitive dependencies come into play. 

It has something to do with index.ts and reexports, perhaps order of export/import is affected. Direct export/import works, but if my directives were reexported within single array like `APP_DIRECTIVES = [Dir1, Dir2 ...]` i got undefined/unresolved services, solved it using reexport from additional index.ts.

**Comment by smnbbrv** [comment]
@kemsky you are totally right. This comes from circular dependencies, when I rearrange my services it works...
