### ISSUE TITLE
npm install complains about peers

### ISSUE THREAD

**Issue by MatejMatula** [angular/angular#9908]
I get the following warnings when I installed dependencies:

```
npm WARN angular2-in-memory-web-api@0.0.12 requires a peer of @angular/core@2.0.0-rc.2 but none was installed.
npm WARN angular2-in-memory-web-api@0.0.12 requires a peer of @angular/http@2.0.0-rc.2 but none was installed.
```
I have the latest version of node and npm installed , when i try to install it manually 

`npm install -g core`

it throws 

`npm ERR! git clone --template=/home/../.npm/_git-remotes/_templates --mirror http://stash.grupa.onet/scm/oacc/node04-knox.git /home/../.npm/_git-remotes/git-http-stash-grupa-onet-scm-oacc-node04-knox-git-dl-0-8-6-node4-2a4e277a: Cloning into bare repository '/home/../.npm/_git-remotes/git-http-stash-grupa-onet-scm-oacc-node04-knox-git-dl-0-8-6-node4-2a4e277a'...

what this error menas and how can it be fixed?
`

**Comment by skreborn** [comment]
This seems to be a support question, so I suggest you ask it on an [appropriate channel](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question).

For what it's worth, `core` is not the Angular package, `@angular/core` is.
