### ISSUE TITLE
Property 'CheckOnce' does not exist on type 'typeof ChangeDetectionStrategy'. (rc4)

### ISSUE THREAD

**Issue by born2net** [angular/angular#9910]
**I'm submitting a ...**  
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Property 'CheckOnce' does not exist on type 'typeof ChangeDetectionStrategy'. (rc4)
I have tried to include both 
```
import {
    Component,
    Input,
    ChangeDetectionStrategy,
    ChangeDetectorStatus
} from '@angular/core'
```
and tried both
```
ChangeDetectionStrategy.CheckOnce
ChangeDetectorStatus.CheckOnce
```
neither one works...

**Expected/desired behavior**
no error in TypeScript

**Reproduction of the problem**
upg to rc.4 from rc.3 and getting the error above

**What is the expected behavior?**
no error

* **Angular version:** rc.4

**Comment by vicb** [comment]
see https://github.com/angular/angular/commit/e12b1277df950aeaead0eec5db56c72d4598a516

you can only set the strategy, other values are state not intended to be used for strategy

**Comment by born2net** [comment]
sorry vic I dont understand and nothing was mentioned on how this change applies in the release notes.

how do I now configure a component check only once, just as I did in rc.3?

regy

**Comment by ericmartinezr** [comment]
@born2net you can't, the only strategies supoorted right now are Default and OnPush, the other ones were never meant to be public iirc
