### ISSUE TITLE
router query param chinese garbled

### ISSUE THREAD

**Issue by keryhu** [angular/angular#9913]
when use router query params like this :

`this.router.navigate(['login'],{queryParams:{err:'中国!'}});`
and loginComponent :

```
constructor(private router:Router) {
    this.router.routerState.queryParams.subscribe(
      params=>{
        this.errMsg=params['err'];
        console.log('errMsg is : '+this.errMsg);
      }
    )
    });
```
first open the '/login' page , console print :

> "errMsg is 中国"，

**--it shows right .

**But refresh the browser , it becomes :****

> "errMsg is : %E4%B8%AD%E5%9B%BD"

**Please tell us about your environment:

Angular version: 2.0.0-rc.4 router 3.0.0-beta.1

Browser: [all | Chrome | Firefox | Safari ]

Language: [all | TypeScript X.X | ES6 ]**

**Comment by vsavkin** [comment]
Fixed here https://github.com/angular/angular/commit/46e105f3ab7c810ca32eebd9d5c5372b57c0f510
