### ISSUE TITLE
[innerHTML] loses data partially or completely.

### ISSUE THREAD

**Issue by classicSpace** [angular/angular#9916]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I get some data from server response and i need to inject it trough [innerHTML], but data is lost partially or completely. There was no problem like this in 2.0.0-rc.1 version.

**Expected/desired behavior**
For example i get video element from server response with id, source and etc. but after using the [innerHTML], id and data-* of this video element is missing.

**Reproduction of the problem**

[Plunker example](http://plnkr.co/edit/fwyD9vqeOr9p17nCpzWq?p=preview)

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all] 
 
* **Language:** [TypeScript 1.8.10] 

Thank you!

**Comment by vicb** [comment]
see https://angular.io/docs/ts/latest/guide/security.html
