### ISSUE TITLE
Debugging Angular2 Cordova App with Webpack sourcemaps

### ISSUE THREAD

**Issue by justme1** [angular/angular#9918]
Angular2 + TypeScript + Webpack Cordova app - I want to be able to debug original TypeScript files on my Android phone when debugging app using Chrome.

What is additionally needed to configure in order for the sourcemap to also work in a remote mobile device running cordova app bundled by Webpack?

Will add current configurations on demand.

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by justme1** [comment]
@zoechi  Done: http://stackoverflow.com/questions/38265843/debugging-cordova-app-with-webpack-sourcemaps
