### ISSUE TITLE
Router validateNode() error message clarification

### ISSUE THREAD

**Issue by autopulous** [angular/angular#9919]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

line 521 of config.ts contains the following misleading error message:

`Invalid configuration of route '${route.path}': component, redirectTo, children, loadChildren must be provided`

**Expected/desired behavior**

The message would be clearer if it were written as follows:

`Invalid configuration of route '${route.path}': one of the following must be provided (component or redirectTo or children or loadChildren)`

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
N/A

**What is the expected behavior?**
See above

**What is the motivation / use case for changing the behavior?**
Improve application debugging

**Please tell us about your environment:**

* **Angular version:** 
@angular/router 3.0.0-beta.2
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart] 
all

**Comment by vsavkin** [comment]
Fixed https://github.com/angular/angular/pull/10193
