### ISSUE TITLE
Template <input> local variable value not updated as user types

### ISSUE THREAD

**Issue by chalin** [angular/angular#992]
To illustrate this problem, I setup the [Angular 2 quickstart example for **Dart**](https://angular.io/docs/dart/latest/quickstart.html) named `hello_world`, and changed the template to be:
```html
<div>
  <h1>Hello {{ nm.value }}</h1>
  <input #nm value="Al" type="text" >
  <a href="#" (click)="0">Do nothing</a>
</div>
```
When I launch the app I see "Hello Al" as expected. If I **type new input text in the browser, the `<h1>` greeting DOES NOT update**. But if I click on the "Do nothing" link (which invokes a noop event handler), then the `<h1>` greeting updates to match the input text value. 

**Shouldn't `nm.value` in the `<h1>` greeting update as I type?**

Now, by extension of the above, if I add a noop event handler `(input)="0"` to the `<input>` element, then the update to the input text gets propagated as I type. Is this the way to go? (Note that in this example I am deliberately trying to avoid using a model field as an intermediary to transport input value.) 

I'm thinking that this might be a consequence of the new Angular 2 digest phase (vs. digest cycle), but I wanted to double check that this isn't a bug. E.g. [pkozlowski-opensource/ng2-play](http://github.com/pkozlowski-opensource/ng2-play) uses a timer to delay the change of a model field, and the change is detected. **Why can't nm be considered a "template local" model field** and hence have any updates picked up automatically?

Btw, note that I have tested this with the current head of angular (i.e., 1872b03fb8513614eca0111d92f3316ee1f9672e).

**Comment by SekibOmazic** [comment]
@chalin If I understand it correctly #nm is the variable local to the input field so you'd need a handler that propagates your changes. In Angular1 ng-model did that for us. As there is no 2-way binding in Angular2 you have to do it manually. I played with data binding here: https://github.com/SekibOmazic/angular2-playground/blob/master/hello_app/greeter.html (with some help from the community) if you need another example.

**Comment by chalin** [comment]
@SekibOmazic As far as I know, `#nm` is local to the template. I am aware of how to achieve an equivalent result using a model field. Since template-local variables are new to Angular 2, I was mainly wondering about the **expected** behavior of Angular in the case I mention above.

**Comment by SekibOmazic** [comment]
@chalin You seem to be right, `#nm` is local to the template. Hmm, now I'm also wondering why `(input)` is needed to propagate changes within the template.

**Comment by alexpods** [comment]
@chalin @SekibOmazic  I think the problem is that change detection is fired after some async actions which was initialized by user. For example:  "on-" binding (  (click)="0" ). So I think if you will initialize empty  "input" event binding it will be working fine:

```js
<div>
  <h1>Hello {{ nm.value }}</h1>
  <input #nm value="Al" type="text"  (input) >
  <a href="#" (click)="0">Do nothing</a>
</div>
```

I don't know whether it's feature of bug. But if it's feature, I think it must be documented very well.

**Comment by chalin** [comment]
> I don't know whether it's feature of bug. But if it's feature, I think it must be documented very well.
Agreed.

**Comment by mhevery** [comment]
This works as intended. You must have a listener such as `<input (keyup)>` to trigger change detection. 

We will document this.

**Comment by chalin** [comment]
Thanks for confirming @mhevery.
