### ISSUE TITLE
Offline Compiler does not understand `@Component` enums

### ISSUE THREAD

**Issue by hansl** [angular/angular#9928]
See [this](http://www.screencast.com/t/NyqqAbQ4gHR).

Highlighting the button component in the screenshot, with the button styling. You can see that the `content` id used in the DOM does not match the one used in the style.

**Comment by hansl** [comment]
Please note that the content attribute _seems_ right (although it seems it always is the content of the root component and not the closest parent). The host attribute is the right one on the element, but it seems that the style was compiled using content everywhere. Putting a break point when the styles are loaded and running the following javascript works:

```javascript
styles_MdCard[0][0] = styles_MdCard[0][0].replace(/_ngcontent/g, '_nghost');
```

Basically, just replacing `content` for `host` in the styles work, but obviously this is not the right fix.

**Comment by hansl** [comment]
Also, note that this works as expected in the same exact app but in dynamic compilation.

**Comment by hansl** [comment]
Button has `encapsulation: ViewEncapsulation.None`, but the offline compiler still generated a shim for the style (instead of `@angular2-material/button/button.css.ts`).

**Comment by hansl** [comment]
Changing https://github.com/angular/angular/blob/master/modules/@angular/compiler/src/style_compiler.ts#L49-L68 to set shim strictly to false fixes the problem. It seems like it's not gathering (or using) the metadata properly for view encapsulation.

```
        var shim = false;
```

**Comment by vicb** [comment]
@chuckjaz could you please take a look at this ? 

Seems like an issue with the static reflector, `encapsulation`is always `undefined`

metadata:

```
{"__symbolic":"module","version":1,"metadata":{"EncapsulationNone":{"__symbolic":"class","decorators":[{"__symbolic":"call","expression":{"__symbolic":"reference","module":"@angular/core","name":"Component"},"arguments":[{"selector":"no-encapsulation","template":"<div></div>","styleUrls":["./encapsulation_none.css"],"encapsulation":{"__symbolic":"select","expression":{"__symbolic":"reference","module":"@angular/core","name":"ViewEncapsulation"},"member":"None"}}]}]}}}
```

**Comment by chuckjaz** [comment]
The root cause is the metadata file for `view.ts` doesn't contain the values for `ViewEncapsulation`. Working on a fix.

```
{"__symbolic":"module","version":1,"metadata":{"VIEW_ENCAPSULATION_VALUES":[{"__symbolic":"select","expression":{"__symbolic":"reference","name":"ViewEncapsulation"},"member":"Emulated"},{"__symbolic":"select","expression":{"__symbolic":"reference","name":"ViewEncapsulation"},"member":"Native"},{"__symbolic":"select","expression":{"__symbolic":"reference","name":"ViewEncapsulation"},"member":"None"}]}}
```
