### ISSUE TITLE
[Router] query params breaks matching on empty/root path

### ISSUE THREAD

**Issue by jamesmanning** [angular/angular#9930]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

query parameters break path matching when the path is empty string (root of app)

**Expected/desired behavior**

query parameters should not prevent matching for empty path.  They don't break matching for non-empty paths

**Reproduction of the problem**
I can't figure out how to specify paths and query params with a plnkr, but the code that should trigger it if I could figure that out would be in http://plnkr.co/edit/PViPDpLrzc4ralhPPCXr?p=info with the src/main.ts being the relevant bit.

If you use the below code as your main.ts from an angular-cli-generated project you can hit these urls to see the problem:

- http://localhost:4200/foo     (works fine)
- http://localhost:4200/foo?some=param     (works fine)
- http://localhost:4200/     (works fine)
- http://localhost:4200/?some=param     (fails with Error: Cannot match any routes: '')

```
import { bootstrap } from '@angular/platform-browser-dynamic';
import { Component } from '@angular/core';
import { provideRouter, RouterConfig, ROUTER_DIRECTIVES } from '@angular/router';

@Component({
  moduleId: module.id,
  template: '<b>dummy component</b>',
})
class DummyComponent { }

@Component({
  moduleId: module.id,
  selector: 'app-root',
  template: '<router-outlet></router-outlet>',
  directives: [ROUTER_DIRECTIVES],
})
class AppComponent {}

export const routes: RouterConfig = [
  { path: '', component: DummyComponent },
  { path: 'foo', component: DummyComponent },
];

bootstrap(AppComponent, [
  provideRouter(routes),
]);
```

resulting stack trace:

    browser_adapter.ts:74Error: Uncaught (in promise): Error: Cannot match any routes: ''
        at resolvePromise (zone.js:538)
        at zone.js:515
        at ZoneDelegate.invoke (zone.js:323)
        at Object.onInvoke (ng_zone_impl.ts:64)
        at ZoneDelegate.invoke (zone.js:322)
        at Zone.run (zone.js:216)
        at zone.js:571
        at ZoneDelegate.invokeTask (zone.js:356)
        at Object.onInvokeTask (ng_zone_impl.ts:53)
        at ZoneDelegate.invokeTask (zone.js:355)

**What is the expected behavior?**

query params to root (empty path) should not break matching the path

**What is the motivation / use case for changing the behavior?**

Having a component at the root path is great for single-functional-area apps that still want to do router things (in my case, accept and generate links with query params that will set initial state)

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** Chrome 51, Edge
 
* **Language:** TypeScript 1.8

**Comment by jamesmanning** [comment]
Likely not of any additional value, but what's logged to console in chrome devtools when hitting http://localhost:4200/?x=y

![image](https://cloud.githubusercontent.com/assets/225626/16705260/1d7d3132-4552-11e6-8301-ef911213c5eb.png)

**Comment by ericmartinezr** [comment]
Dup of https://github.com/angular/angular/issues/9460

**Comment by vsavkin** [comment]
This issue has be fixed here: https://github.com/angular/angular/pull/9603/commits/3f44377f2f1d154354b98c5b3aed782ee0b50b12

@jamesmanning Are you using the latest version of the router?

**Comment by jamesmanning** [comment]
@vsavkin sorry, @ericmartinezr is right, it's a dupe
