### ISSUE TITLE
Error: Cannot enable prod mode after platform setup

### ISSUE THREAD

**Issue by jaumard** [angular/angular#9932]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[*] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
With server rendering (with angular-universal) I use `ng2.enableProdMode()`, and I have a watcher how reload my server side when I edit a file. Currently it fail because when it reload my controller I have this error `Error: Cannot enable prod mode after platform setup`.

**Expected/desired behavior**
It can be nice to have something to test is plateform is setup, like this I can do something like : 

```
if(!ng2.isSetup()) {
    ng2.enableProdMode()
}
```
My controller will load without problem after that I think.

**What is the motivation / use case for changing the behavior?**
Allow angular 2 server side with hot reload capabilities to speed up server side development.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** server side 
 
* **Language:** all

**Comment by vicb** [comment]
obsolete
