### ISSUE TITLE
[innerHTML] directive not working with checkbox control after RC.1 release.

### ISSUE THREAD

**Issue by micronyks** [angular/angular#9934]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
With **RC.2 and later release** following doesn't work,

    template:`<div [innerHTML]="someHtml"></div>`
    
    someHtml = `<input type="checkbox">`;

**Expected/desired behavior**

it should display **checkbox** in template

**Reproduction of the problem**

working **RC.1**         : http://plnkr.co/edit/uOY7xfdHcQhZO5MF6iGA?p=preview

not working **RC.4**   : http://plnkr.co/edit/5l266VUp6FBUhILgkGT6?p=preview

**What is the expected behavior?**
It should parse & show checkbox in HTML template.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all ] 
 
* **Language:** [TypeScript] - I have checked with Typescript only

**Comment by pkozlowski-opensource** [comment]
RC.4 introduces security checks on dynamically injected HTML, see detailed info here: https://angular.io/docs/ts/latest/guide/security.html

> It should parse & show checkbox in HTML template.

This won't happen by default as using `innerHTML` the way you are trying to use is playing with fire (security-wise). But the article I've linked provides instructions on bending the default behaviour.

**Comment by micronyks** [comment]
Yes checked it. it works. In case anybody wants the solution,

https://plnkr.co/edit/Yexm1Mf8B3FRhNch3EMz?p=info
