### ISSUE TITLE
[router] Browser hangs up when parsing URL with (#).

### ISSUE THREAD

**Issue by iurii-kyrylenko** [angular/angular#9935]
[ x ] bug report

**Preconditions**:
1. The application uses Router.
2. URL contains symbol # inside parentheses, e.g. (#) or (foo#bar).

**Occurs when**:
1. Calling instance method parseUrl of Router.
2. Or navigating to the URL from address bar.

**Actual result**:
Browser hangs up without throwing any exception.

**Plunk**:
http://plnkr.co/edit/5zGhfMIPYkxIHZHlT89k?p=preview

**Steps to reproduce**:
1. Open console in dev tool.
2. Enter URL: (#)
3. Press ParseUrl button

* **Angular version:** 2.0.0-rc.4
* **router:** 3.0.0-beta.2
 
* **Browsers:** Chrome, Safari

**Comment by vsavkin** [comment]
Fixed https://github.com/angular/angular/pull/10222
