### ISSUE TITLE
ngFor extra li end element

### ISSUE THREAD

**Issue by novoxudonoser** [angular/angular#9937]
**I'm submitting a ...**
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Got extra empty li last element using ul li and ngFor.

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** Linux Chromium51

Plunk: http://plnkr.co/edit/TtIFZegKFHrfG8TGQqKb?p=preview

Sorry if it is a duplicate, couldn't find any similar Issues.

**Comment by nosachamos** [comment]
@novoxudonoser  You opened another `li` instead of closing the one you're looping:

````
      <li
        *ngFor="let item of items; let i=index"
      >
        {{ item }}
      <li>     << HERE
```

If there's nothing else for this issue, you can close.
