### ISSUE TITLE
Router: Enable loadChildren to support a function that returns a Promise

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#9938]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The `loadChildren` route config property only accepts a string

**Expected/desired behavior**

The `loadChildren` route config property accepts a string or function that returns a promise

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

In order to allow lazy loading in Webpack 1 with the upcoming `@AppModules`, there needs to be a way to return a promise that resolves an app module.

```js
const routes: Routes = [
  {
    path: 'parent',
    loadChildren: () => new Promise(resolve => {
      require.ensure([], require => {
        resolve(require('./parent/module').ParentAppModule);
      })
    })
  }
];
```

It would also be helpful if this support were added to the `SystemJsAppModuleLoader` so SystemJS and Webpack are supported out of the box.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart] 

cc: @vsavkin @tbosch

**Comment by brandonroberts** [comment]
Tested and working with a custom app module loader using a function instead of a string with no changes needed.

**Comment by SaltyDH** [comment]
Hi @brandonroberts do you have an example of this working in a plnkr or github repo that's compatible with router v3 rc1?

**Comment by brandonroberts** [comment]
I have an example gist here of using a custom loader: https://gist.github.com/brandonroberts/02cc07face25886fe142c4dbd8da1340
