### ISSUE TITLE
npm start gives error and many files in library are missing

### ISSUE THREAD

**Issue by pjayramkumar** [angular/angular#9939]
**
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.9.5
3 info using node@v6.2.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular2-laravel5-mongodb3@1.0.0~prestart: angular2-laravel5-mongodb3@1.0.0
6 silly lifecycle angular2-laravel5-mongodb3@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle angular2-laravel5-mongodb3@1.0.0~start: angular2-laravel5-mongodb3@1.0.0
8 verbose lifecycle angular2-laravel5-mongodb3@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-laravel5-mongodb3@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/var/www/html/node_modules/.bin:/usr/local/bin:/root/.linuxbrew/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/.local/bin:/root/bin
10 verbose lifecycle angular2-laravel5-mongodb3@1.0.0~start: CWD: /var/www/html
11 silly lifecycle angular2-laravel5-mongodb3@1.0.0~start: Args: [ '-c', 'tsc && concurrently "npm run tsc:w" "npm run lite" ' ]
12 silly lifecycle angular2-laravel5-mongodb3@1.0.0~start: Returned: code: 2  signal: null
13 info lifecycle angular2-laravel5-mongodb3@1.0.0~start: Failed to exec start script
14 verbose stack Error: angular2-laravel5-mongodb3@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run lite" `
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid angular2-laravel5-mongodb3@1.0.0
16 verbose cwd /var/www/html
17 error Linux 3.10.0-327.18.2.el7.x86_64
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v6.2.2
20 error npm  v3.9.5
21 error code ELIFECYCLE
22 error angular2-laravel5-mongodb3@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run lite" `
22 error Exit status 2
23 error Failed at the angular2-laravel5-mongodb3@1.0.0 start script 'tsc && concurrently "npm run tsc:w" "npm run lite" '.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-laravel5-mongodb3 package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     tsc && concurrently "npm run tsc:w" "npm run lite"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-laravel5-mongodb3
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-laravel5-mongodb3
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**Expected/desired behavior**

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart]

**Comment by pkozlowski-opensource** [comment]
Please use an appropriate support channel for those types of questions: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
