### ISSUE TITLE
UpgradeAdapter.downgradeNg2Component() produces unhandled Promise rejection error

### ISSUE THREAD

**Issue by douglasward** [angular/angular#9943]
**I'm submitting a ...**  (check one with "x")

```
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When following the upgrade tutorial, downgrading the list or detail phone component produces an unhandled Promise rejection error.

https://angular.io/docs/ts/latest/guide/upgrade.html#!#upgrading-components

```
angular.module('phoneList')
  .directive(
    'phoneList',
    <angular.IDirectiveFactory>
      upgradeAdapter.downgradeNg2Component(PhoneListComponent)
  );
```

![screenshot from 2016-07-10 14-40-53](https://cloud.githubusercontent.com/assets/8439137/16713572/599f2246-46ac-11e6-938d-c99266cda1e1.png)

**What is the expected behavior?**

To be able to use an angular2 component in an angular1 app.

Is the tutorial missing a step? Or is this a bug?

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.4
- **Browser:** [all  ] 
- **Language:** [all ]

**Comment by gkalpak** [comment]
The tutorial has since been updated to use the new `@angular/upgrade/static` and this should no longer be an issue.
