### ISSUE TITLE
Can't Connect to angular.io from windows

### ISSUE THREAD

**Issue by Quanalogy** [angular/angular#9945]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Hi i currently have a problem connecting to the angular.io page on windows 10. Firefox says that the connection has cancelled while connecting, edge says "Hmm, we can’t reach this page." while chrome says "This site can’t provide a secure connection: ERR_SSL_PROTOCOL_ERROR". If i try to connect from my home network on my android phone i can easily connect to the page, but not from my windows computer .. this has been tested on other windows computers in the household with same result. 

**Expected/desired behavior**
Connected to the angular.io

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

goto https://angular.io on windows 10.

**What is the expected behavior?**

Connected to the angular.io

**What is the motivation / use case for changing the behavior?**

..

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 Windows 10, with chrome, firefox, edge, ie -> all failing to connect to the homepage of angular.io
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart]

**Comment by ericmartinezr** [comment]
Hey, the repo for the website is here https://github.com/angular/angular.io, would you mind reopening it there?

**Comment by asaf050** [comment]
I don't know if it's a bug, but I also have the same problem.
Getting the same error on https://material.angularjs.org/latest/ but not on https://angularjs.org.

Can access the website from my smartphone (Android) using the same network.

**Comment by teacii** [comment]
Can we maybe know why the issue was closed? (maybe a solution was found?)

I have the same problem. 
None of the browsers can open https://angular.io or any page under that.
Mobile seems to have no issues on same network.

**Comment by ericmartinezr** [comment]
It was closed because this repo is for the framework, not the website. Check this issue in case it helps https://github.com/angular/angular.io/issues/1875

**Comment by teacii** [comment]
Thank you. It really did solve my issue.

**Comment by Carsak** [comment]
https://github.com/angular/angular.io/issues/1875
Thank you. This is solution

**Comment by wclear** [comment]
https://github.com/angular/angular.io/issues/1875 was the solution here too. To save a click; in short: the site was being blocked by an antivirus system with SSL protection, disabling SSL protection resulted in the website being accessible. (Remember to re-enable if SSL protection is important).

**Comment by rahul2104** [comment]
Uncaught SyntaxError: Unexpected end of input
core.js:4353 Uncaught Error: Angular requires Zone.js prolyfill.
    at new t (core.js:4353)
    at ct (core.js:5543)
    at t.bootstrapModuleFactory (core.js:5362)
    at Object.cDNt (main.ts:11)
    at n (bootstrap 8db9b05a9dd6b7d451d1:54)
    at Object.0 (main.1c33290970b6430d47fa.bundle.js:1)
    at n (bootstrap 8db9b05a9dd6b7d451d1:54)
    at window.webpackJsonp (bootstrap 8db9b05a9dd6b7d451d1:25)
    at main.1c33290970b6430d47fa.bundle.js:1
angular.io/:1 The resource https://angular.io/generated/docs/index.json was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
angular.io/:1 The resource https://angular.io/generated/navigation.json was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
