### ISSUE TITLE
Add a directive lifecycle hook that is called after the children of a directive are checked

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#995]
```
<parent>
  <child1></child1>
  <child2></child2>
</parent>
```

There should be a hook that `parent ` can implement that will be called after change detection checks child1 and child2.

Implementation notes:
One way to implement it is to walk through the list of directives in reversed order and for every directive that supports the hook invoke it.

**Comment by jelbourn** [comment]
See #934
