### ISSUE TITLE
Request: Benchmark for Offline Compilation (Code Generation)

### ISSUE THREAD

**Issue by laco0416** [angular/angular#9950]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```

**Current behavior**

The offline compilation seems coming soon. 
Since today, at many conferences, core team talked us that will bring great performance. 
It's an amazing story, but there's no evidence. 
So, we want to know: _How much faster is it?_.

**Expected/desired behavior**

Add a case of the offline compiling into official benchmarks.

**Comment by vicb** [comment]
@tbosch is working on this
