### ISSUE TITLE
2 way data binding not working with model driven forms

### ISSUE THREAD

**Issue by manish2aug** [angular/angular#9952]
Hi there,

[Angular version: 2.0.0-rc.4; forms version: 0.2.0]

In rc-4, using formControlName and assigning the same name as in model, but it seems it just provides one way binding not 2 way. Thought  formControlName is an alternative of [(ngModel)] and name

form.ts
---------
`
name:string='abcd';
this.form = formBuilder.group({'name': [this.name, Validators.required]})
`
form.html
-------------
`
<input type="text" id="name" formControlName="name" class="form-control">
`
when form loads it shows the values ("abcd") in name field, but updating value doesn't update the model.

**Comment by janerist** [comment]
Try this:
```
name = new FormControl('abcd', Validators.required);
this.form = formBuilder.group({name: this.name});
```

**Comment by manish2aug** [comment]
Thanks for replying!
Unfortunately it doesn't work too

**Comment by zoechi** [comment]
Please provide a Plunker that allows to reproduce the problem.

**Comment by pkozlowski-opensource** [comment]
Closing as we don't have reproduce scenario.
