### ISSUE TITLE
Change cycle is not triggered for array of object in component

### ISSUE THREAD

**Issue by venkateswaris** [angular/angular#9955]
When array of object is passed to component , changes in the array element(remove or add) is not reflected in html. But changing any property of any element is reflected.

We are passing list of cities to the component:
          `  <list-city  [cities]="country.getCities()"></list-cities>`
in side the component, we are adding new city or removing city.

`export class CityListComponent {
    @Input cities: City[];
    add = (city: City) => cities.push(city);
}`

in the CityListComponent templates, we are listing all the cities. When new city is added, it is **not reflected**. But if we change any property of the existing city, it is reflected.   

* **Angular version:** 2.0.0-rc.3
 
* **Language:** [ TypeScript ]

**Comment by pkozlowski-opensource** [comment]
This works as designed. By default ng2 is only observing references to values, not the object themselves. If you want to observe content of an object you need to do it on your side. Check [ngClass directive](https://github.com/angular/angular/blob/master/modules/@angular/common/src/directives/ng_class.ts#L109) for an example of doing so.
