### ISSUE TITLE
Use ngfor an dynamic component loader and iframe

### ISSUE THREAD

**Issue by Katy91** [angular/angular#9956]
Hi,

i use ngfor and the dynamic component loader to show different numbers of div-containers with different contents. One content shall show another webapplication. For this exercise I use the html-tag iframe.

My problem is that every dynamic change with the ngfor triggers a reload from the webapplication. 

How can I prevent this reload reaction?

Thank you.

Best Regards
Katy

**Comment by pkozlowski-opensource** [comment]
Please use a dedicated support forum for those types of questions, see: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
