### ISSUE TITLE
Hybrid mode doesn't allow NG1 upgrades after app is bootstrapped.

### ISSUE THREAD

**Issue by prasikumbhare** [angular/angular#9959]
**I'm submitting a ...**  (check one with "x")

```
[ X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Loading a component dynamically using `ViewContainerRef.createComponent()` fails in case of ng1 child component. The issue here is NG2 component being loaded dynamically contains an NG1 child component. And Upgrade Adapter fails to bind the scope of upgraded NG1 component throwing below exception. 

```
EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in ./DynamicComponent class DynamicComponent - inline template:0:0
ORIGINAL EXCEPTION: TypeError: Cannot read property 'scope' of null
ORIGINAL STACKTRACE:
TypeError: Cannot read property 'scope' of null
    at new UpgradeNg1ComponentAdapter (https://npmcdn.com/@angular/upgrade@2.0.0-rc.4/bundles/upgrade.umd.js:440:57)
    at new UpgradeNg1ComponentAdapterBuilder.type._angular_core.Directive.Class.constructor (https://npmcdn.com/@angular/upgrade@2.0.0-rc.4/bundles/upgrade.umd.js:293:36)
    at DebugAppView._View_DynamicComponent0.createInternal rc.4/bundles/core.umd.js:12207:48)

```

**Expected/desired behavior**
It should be possible to load a ng1 component dynamically in hybrid mode. Upgrade Adapter should allow NG1 upgrades even after app is bootstrapped.

**Reproduction of the problem**
Here is the plunker : [https://plnkr.co/edit/HADJILztGEELg5lavfvP?p=preview](https://plnkr.co/edit/HADJILztGEELg5lavfvP?p=preview)

**What is the expected behavior?**
It should be possible to load a ng1 component dynamically in hybrid mode.

**What is the motivation / use case for changing the behavior?**
Due to this issue, it's not possible to (re) use the ng1 components inside ng2 app.

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.4
- **Browser:** [Chrome 51 ] 
  Version 51.0.2704.106 m
- **Language:** [all | TypeScript 1.8 |  ES5 ]

**Comment by prasikumbhare** [comment]
OK .. figured out the problem.. the problem is with UpgradeAdapter. It does not allow upgrades after app is bootstrapped. Unfortunately this requires to know all the components to be upgraded upfront before app is bootstrapped. Here is the working [plunker](https://plnkr.co/edit/ChPTVb0lI6wxM5QjVYoS).
Hope Upgrade adapters allows dynamic upgrades..

**Comment by prasikumbhare** [comment]
I have fixed it locally in `UpgradeAdapter ` code. 
Here is the plunker with local fix in "angular2/upgradeRC4/bundles/upgrade.umd.js" : 
[https://plnkr.co/edit/hhhSAeXvhViE8zZMVqoy?p=info](https://plnkr.co/edit/hhhSAeXvhViE8zZMVqoy?p=info)

The upgraded NG1 components are resolved during `UpgradeAdapter.bootstrap()`. The fix is , if the app is already bootstrapped, then resolve the NG1 components after upgrade immediately.

<pre>
UpgradeAdapter.prototype.upgradeNg1Component = function (name) {
            if (this.downgradedComponents.hasOwnProperty(name)) {
                return this.downgradedComponents[name].type;
            }
            else {
                (this.downgradedComponents[name] = new UpgradeNg1ComponentAdapterBuilder(name));
                <b>if(this.ng1Injector) {
                  UpgradeNg1ComponentAdapterBuilder.resolve([this.downgradedComponents[name]], this.ng1Injector);
                }</b>
              return this.downgradedComponents[name].type;
            }
        };
</pre>

@IgorMinar 
Appreciate if someone from @angular team promote this code.

**Comment by AlexKhymenko** [comment]
The same with services. After the application bootstraped you cant use services.

**Comment by gkalpak** [comment]
Since the old, dynamic ngUpgrade has been deprecated, this issue is now obsolete. It is recommended to use the new, static version (imported from `@angular/upgrade/static`), which requires the upgraded components to be registered with the Angular module (since they need to be statically analyzed for AoT).
