### ISSUE TITLE
Angular 2 custom directive not binding sparkline barChart

### ISSUE THREAD

**Issue by vijender1256** [angular/angular#9961]
I am trying to write custom directive to pass input values and then bind data to the sparkline chart but it gives me error sparkline is not a function. Included Sparkline.js in index.html but it still doesn't pick it up in directive.

Below is the plunker:

http://plnkr.co/edit/BpY6Kd1bSMzWTKSZqJzv

Any help appreciated.

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by pkozlowski-opensource** [comment]
Thnx @ericmartinezr !
