### ISSUE TITLE
DatePipe: error with timezones

### ISSUE THREAD

**Issue by vicb** [angular/angular#9964]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
```

**Current behavior**
When running tests locally:
```
Chrome 51.0.2704 (Mac OS X 10.11.5) DatePipe transform should format each component correctly FAILED
    Expected 'PDT' to equal 'GMT'.
        at /Users/chuckj/src/angular/modules/../../../../../../modules/@angular/common/test/pipes/date_pipe_spec.ts:67:51
        at Object.<anonymous> (/Users/chuckj/src/angular/modules/../../../../../modules/@angular/core/testing/testing_internal.ts:146:25)
``` 

**Expected/desired behavior**
No error

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** Chrome 51.0.2704 (Mac OS X 10.11.5)

Local TZ set to PDT

@laskoviymishka could you please take a look - it has been introduced in #9816 

If this is not fixed before RC5, we'll revert the commit. Thanks

**Comment by laskoviymishka** [comment]
It should be more flexible than just hardcoded value I think. I take a look how it could be enhanced.

**Comment by laskoviymishka** [comment]
And there is no good way to handle this issue without additional dependencies :(, most probably this test should be killed, or change to something that not hardcoded.

**Comment by vicb** [comment]
Do you plan to come with a PR ?

**Comment by chuckjaz** [comment]
Do we need to check the value? Maybe `.toBeDefined()` would be sufficient.

**Comment by laskoviymishka** [comment]
@vicb sure, i working on it :+1: 
@chuckjaz well it OK, at least it better than nothing :sweat_smile:

**Comment by laskoviymishka** [comment]
Suddenly i made  #9816 when i was in a trip with GMT locale laptop, and suddenly build machine have exact same locale. My bad :cry:
