### ISSUE TITLE
bug (router) routerState.queryParams.subscribe() often not triggered

### ISSUE THREAD

**Issue by rezss** [angular/angular#9970]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report
```

**Current behavior**
sometimes (or most often) changes in the queryParams wont trigger an observable event.

**Expected/desired behavior**
all changes to the queryParams will trigger an observable event

**Reproduction of the problem**
on an ngOnInit method i subscribe to the following events:

    this.router.events.subscribe(x => {
      console.log('router.events.subscribe:');
      console.log(x);
    });

    this.routeSubscription = this.router.routerState.queryParams.subscribe(params => {
      this.currentScope = params['scope'];
      this.currentOrder = params['order'];

      console.log('queryParams.subscribe: ${JSON.stringify(params)}');
    });
and the view calls one of those functions:

`{
  const currentParas = this.router.routerState.snapshot.queryParams;
  currentParas['order'] = order;
  this.router.navigate(['/version/create'], { queryParams: currentParas });
}`

![image](https://cloud.githubusercontent.com/assets/2461029/16742988/8e7ee0f6-47aa-11e6-8db9-547c4e8908ed.png)

the thing is: even if all navigate events will fired, and the browser shows the correct queryParams, the event wont triggered sometimes. it seems totaly random and i have no clue why.

**What is the expected behavior?**

each time i use router.navigate and append a queryParams, the routerState.queryParams observable will fire and event.

**What is the motivation / use case for changing the behavior?**

a simple dropdown where the user is able to select one of many filters and/or order for a list

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
* **Angular router:** 3.0.0-beta.2
 
* **Browser:** [Chrome Version 51.0.2704.106 m (64-bit) ] 
 
* **Language:** [all | TypeScript X.X | es5 ]

**Comment by brandonroberts** [comment]
Will you create a plunker reproducing this issue?

**Comment by rezss** [comment]
there you go: [Plunker example](https://plnkr.co/edit/W044sv?p=preview)

**Comment by brandonroberts** [comment]
Thanks. I confirmed that this a bug. In the meantime, I'd recommend using `Object.assign` to store your snapshot params.

```js
const currentParas = Object.assign({}, this.router.routerState.snapshot.queryParams);
```

**Comment by rezss** [comment]
aaah, i see.
so never ever write into the snapshot.queryParams directly. otherwise angular will screw up. 
thanks for the hint, mate.

but: should be fixed nevertheless, i bet i'am not the only dummy who makes this mistake.

**Comment by vsavkin** [comment]
I don't think there is an issue here. The router treats all types of parameters (matrix, query) the same way. It structurally checks if the two objects are the same, and if they are not, the router  will emit an event. So the identity of the query params object does not matter.

Check out this plunker to see that it works:
https://plnkr.co/edit/A3QUpx?p=preview

Click around and you will see something like this:
```
Object {scope: "all"}
queryParams.subscribe: {"scope":"all"}
Object {scope: "all"}
Object {scope: "all"}
Object {scope: "all", order: "name"}
queryParams.subscribe: {"scope":"all","order":"name"}
Object {scope: "all", order: "name"}
Object {scope: "all", order: "name"}
queryParams.subscribe: {"scope":"all","order":"updated"}
```

Anytime the value changes, a new event is emitted. 

Closing this issue.

**Comment by vsavkin** [comment]
It looks I didn't understand the issue. The real issue is that you can by accident mutate params. Reopening the issue.

**Comment by tschaka1904** [comment]
@rezss did you ever found a way around it? I'm having a similar issue.
