### ISSUE TITLE
Review API for `inject` now that we have app modules

### ISSUE THREAD

**Issue by juliemr** [angular/angular#9975]
In https://github.com/angular/angular/pull/9846, we switched to using `AppModule`s for tests. This is great because it allows for more flexibility, but one consequence is that each test case _may_ require asynchronous setup, in order to precompile components with external templates (because they need to make an XHR).

The solution in #9846 was to make the `inject` helper method inspect whether it is being called inside an `async` block or not. This will work for most current user cases, but destroys encapsulation and ties users to our ways of dealing with async. It's also a lot of 'just trust us magic'.

We could, instead, require the user to let us know if they need to do something asynchronous. This could look like:

```js
beforeEach(async(() => {
  configureModule({
    precompile: MyComponentWithExternalTemplate;
  });

  doAsyncPrecompilation(); // Proposed new method
}));

it('does something with that module', inject([TestComponentBuilder], (builder) => {
  // This will always be called synchronously now.
  var fixture = builder.createSync(MyComponentWithExternalTemplate);
});
```

Currently, (in master at the moment) this would look like:

```js
beforeEach(() => {
  configureModule({
    precompile: MyComponentWithExternalTemplate;
  });
});

it('does something with that module', async(inject([TestComponentBuilder], (builder) => {
  // This will throw an error if it's not inside an async block.
  var fixture = builder.createSync(MyComponentWithExternalTemplate);
}));
```

**Comment by juliemr** [comment]
(Also, I'm very happy to hear other ideas to keep things nicely encapsulated but low-boilerplate. I don't love my solution here)

**Comment by juliemr** [comment]
We have one vote for sticking with the status quo: "Of the three evils, this is most magical but least intrusive.   I guess I like it best ...  Because being explicit gives me more to do and more to explain and I probably still don't know why I'm doing it really unless I'm thinking hard and re-re-re-reading the docs."

**Comment by juliemr** [comment]
Discussed this off thread, and the conclusion is - I'm going to prepare a PR which introduces a function for the user to call which will set up the `AppModuleFactory`. This will add some burden for the user to understand when that needs to be called, but it removes a lot of magic, makes our methods more encapsulated, and gives us more room for nicely modifying w/o breaking changes before final.

**Comment by laco0416** [comment]
how about `configureModuleSync` and `configureModuleAsync`?

**Comment by juliemr** [comment]
@laco0416 we would like `configureModule` to always be synchronous, since it is just storing the info to be set up later - this lets it be nested inside multiple `describe` blocks and use only the latest. If it created an `AppModule` every time we called `configureModule`, we could get weird side effects from creating a module more than once.

**Comment by laco0416** [comment]
@juliemr Thanks, I understand.

**Comment by eyalvardi** [comment]
Hi,
I think you need to change the name of AppModule to Package, the word module can confuse with JavaScript and TS module.

One more thing, I think you need to add to Component decorator a property packages for array of Package class, This will make it much simpler from the use of: directives,pipes,providers... one for all (packages).

**Comment by juliemr** [comment]
Hi @eyalvardi looks like you've opened up a new issue about your larger concern, thanks! I'm going to go ahead and remove these comments to keep this issue clean.
