### ISSUE TITLE
Empty file created in incorrect folder by offline compiler

### ISSUE THREAD

**Issue by hansl** [angular/angular#9984]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
An empty file is created by the offline compiler for the factory and the style next to the source HTML/CSS file, outside of the `genDir`. This also happen in `node_modules` (for material).

The correct files are also created properly.

**Expected/desired behavior**
No empty file should exist.

**Comment by hansl** [comment]
cc @jelbourn

**Comment by chuckjaz** [comment]
How do I reproduce this?

**Comment by chuckjaz** [comment]
Findings: The https://github.com/angular/angular/blob/master/modules/%40angular/compiler-cli/src/reflector_host.ts#L217 is generating a file because https://github.com/angular/angular/blob/master/modules/%40angular/compiler-cli/src/reflector_host.ts#L80 asks it to.
