### ISSUE TITLE
Interpolation doesn't work in Components that was injected via DynamicComponentLoader

### ISSUE THREAD

**Issue by ArickVigas** [angular/angular#9987]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When injecting a component A into component B via a DynamicComponentLoader, in component A an interpolation doesn't work.

**Expected/desired behavior**
I want to dynamically render a component A inside another component B. 
In component A define a string and render it.

**Reproduction of the problem**
Here is plunker demo
https://plnkr.co/edit/sXCAjX?p=preview

**What is the motivation / use case for changing the behavior?**
I want to dynamically render a component A inside another component B. 
In component A define a string and render it.

**Please tell us about your environment:**
OS X 10.11.5
* **Angular version:** 2.0.0-rc.1
 
* **Browser:**  Chrome 51
 
* **Language:** TypeScript 1.7.5

**Comment by ericmartinezr** [comment]
That's how loadAsRoot works. You have wire up everything manually if you want to use it. Anyway, DCL is deprecated. Search in the repo for loadAsRoot issues, it's full of them.

**Comment by ArickVigas** [comment]
@ericmartinezr Thanks. 
For those who will encounter this issue. #7372
