### ISSUE TITLE
[ViewChildren/ContentChildren] Get all children components (which implementing abstract class or interface)

### ISSUE THREAD

**Issue by tobiloeb** [angular/angular#9989]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
We have a lot of components (> 30) which will be used as ContentChildren in other components. We have some users (configurators) who configure a page with our components. These configurators don't know anything about the implementation, they just define/configure a page with our components.

**Example**:
```
<aggregate-component> <!-- This is our component which aggregates all the component to a page. -->

  <!-- Here the configurator configures and defines the components he want to add to the page. -->
  <first-component>
    <another-component>
      <!-- maybe many more here -->
    </another-component>
  </first-component>
  <second-component></second-component>
  ....
</aggregate-component>
```

TypeScript class for aggregate-component:
```
@Component({
  directives: [],
  selector: 'aggregate-component',
  template: '<div><ng-content></ng-content></div>'
})

export class AggregateComponent {

  @ContentChildren(???) children: QueryList<>;
}
```

Now we need the list of all ContentChildren in the "aggregate-component". All children implement an abstract class and some interfaces. But it is not possible to use the interfaces or abstract class as Type selector in ContentChildren:
@ContentChildren(Interface|abstract Class)

Then we tried to add a special css class to all of our components to select them, but this didn't work as well:
@ContentChildren('our-class')

For now we have found a workaround which seems to be working in the most of the cases. We use the ViewContainerRef. But we don't know if this is the right way?
EDIT: This is only working for ViewChildren! :(

```
@Component({
  directives: [],
  selector: 'aggregate-component',
  template: '<div><ng-content></ng-content></div>'
})

export class AggregateComponent {

  constructor(protected viewContainer: ViewContainerRef) {
  }

  public ngAfterViewInit() {
    // here are the parents available almost.
    this.parentComponent =  this.viewContainer._element.parentView.parent.context;
  }
}
```

A directive or template variable (#foo) as selector isn't a possible solution, because the configurator would have to add the directive or variable on each component manually. That's why we would like to have a programmatic solution to get all the ContentChildren or the direct parentComponent. 

**Expected/desired behavior**
See above.

**Reproduction of the problem**

**What is the expected behavior?**
See above.

**What is the motivation / use case for changing the behavior?**
A programmatic solution to get all different ContentChildren/ViewChildren of a component without to add "@ContentChildren, @ViewChildren" for each possible type. Or a solution to get the direct parentComponent.

**Please tell us about your environment:**
* **Angular version:** 2.0.0-rc.4
* **Browser:** all 
* **Language:** TypeScript ~1.8.10

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/issues/8563, https://github.com/angular/angular/issues/8580

**Comment by pkozlowski-opensource** [comment]
Thnx @ericmartinezr !
