### ISSUE TITLE
Check-deploy crashes due to something in master since RC4

### ISSUE THREAD

**Issue by wardbell** [angular/angular#9990]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request 
```

**Current behavior**
The command `gulp check-deploy`  in `angular.io` crashes when the parallel `angular` repo is set to current master. Error is
```
error:   TypeError: Cannot read property 'trim' of undefined
    at getReturnType (C:\github\angular.io\node_modules\dgeni-packages\typescript\processors\readTypeScriptModules.js:386:55)
    at createExportDoc (C:\github\angular.io\node_modules\dgeni-packages\typescript\processors\readTypeScriptModules.js:236:30)
...
```
No such failure when roll `angular` repo back to RC4.

@naomiblack writes:

>oh… i think that may be a package that has internals that didn’t get escaped. Please file an issue and cc me, @IgorMinar, and @petebacondarwin.

**Comment by naomiblack** [comment]
@IgorMinar -- we'll have to fix before RC5.  @petebacondarwin in case you have time to look overnight...

**Comment by naomiblack** [comment]
I'm also curious why the CI didn't catch this...

**Comment by petebacondarwin** [comment]
I'll look in one hour.

**Comment by petebacondarwin** [comment]
This issue was fixed in `dgeni-packages@0.13.1`. See https://github.com/angular/dgeni-packages/commit/823d3f9e06b08f49b0a4c177da94486ec8ea9ad1

Please run `npm update dgeni-packages` to update to the latest version.

Meanwhile we should change angular.io `package.json` dependency to `"dgeni-packages": "^0.13.1",` see https://github.com/angular/angular.io/blob/master/package.json#L37.

**Comment by IgorMinar** [comment]
@wardbell @naomiblack can you please confirm that this is resolved? thanks!

**Comment by wardbell** [comment]
Trying again after installing dgeni v.0.13.1 when `angular` repo is at SHA 7b31178

**Comment by wardbell** [comment]
Closing because fixed.
