### ISSUE TITLE
detect object changes

### ISSUE THREAD

**Issue by jaroslawziolkowski** [angular/angular#9992]
```
[ x ] bug report

```

**Current behavior**
I have pipe where as argument is object 
```
{filter_1: 'bar', filter_2: 'bar 2'}

```
unfortunately when object is changing to 

```
{filter_1: 'bar 3', filter_2: 'bar 4'}

```

this is not detected and pipe can't work. I solved my problem by use object properties as parameters but in my opinion this is not correct behavior.

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all] 
 
* **Language:** [ TypeScript ]

**Comment by awerlang** [comment]
Read the chapters "Pipes and Change Detection" and "Pure and Impure Pipes" at https://angular.io/docs/ts/latest/guide/pipes.html

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) for support request.
