### ISSUE TITLE
WEBPACK: AN INTRODUCTION Tutorial Requires Updated Package.json

### ISSUE THREAD

**Issue by marlowp** [angular/angular#9993]
I've run through the WebPack tutorial featured here https://angular.io/docs/ts/latest/guide/webpack.html and it looks like by default it does not build correctly due to the angular2-template-loader dependency missing from the package.json file.

I've fixed the issue locally by simply adding the following to the dependencies section of the package.json file:

"angular2-template-loader": "^0.4.0"

**Comment by ericmartinezr** [comment]
@marlowp would you mind reopening in https://github.com/angular/angular.io/issues where the website and tutorials live?

**Comment by marlowp** [comment]
Ah my bad, I've raised this issue in the correct place now (https://github.com/angular/angular.io/issues/1869), thanks.
