### ISSUE TITLE
Angular 2 havily dependent on buggy Zone.js

### ISSUE THREAD

**Issue by romadenysyuk** [angular/angular#9995]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Angular 2 is heavily dependent on buggy library Zone.js which overrides prototypes of global scope functions.
The issue is described here http://stackoverflow.com/questions/38304111/angular-2-dependency-zone-js.
In short using Angular 2 in one part of a big application affects another parts because of the Zone.js overridings.

**Expected/desired behavior**
It should be possible to sandbox Zone.js to the part of the application where we want to use Angular 2. It was possible in Agular 1.x to bootstrap it for the part of the application.

**Reproduction of the problem**

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**
The use case is described in http://stackoverflow.com/questions/38304111/angular-2-dependency-zone-js. 
As a developer of one of the teams that work on a big project I want to be able to implement my module using Angular 2 without affecting other teams' modules.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
 
* **Browser:** [all] 
 
* **Language:** [all]

**Comment by Brooooooklyn** [comment]
I agree, I think zone.js should only effect to angular inside and invisible to the outside.

**Comment by aigor** [comment]
Hi, for me it is critical issue.

**Comment by andrey1hub** [comment]
Wow! I am looking for a fix of exactly the same problem.

**Comment by IgorMinar** [comment]
Zone.js is a prolyfill and as such needs to be global. It should however be transparent and have no impact on code not using zones. If you have concrete scenarios in which this is not the case, please create issues at https://github.com/angular/zone.js/issues and share a reproduction.

We are already tracking a few interop issues via these bugs: https://github.com/angular/zone.js/labels/type%3A%203rd%20party%20interop
