### ISSUE TITLE
Bug: FormControl.updateValue() documentation is wrong

### ISSUE THREAD

**Issue by vagarenko** [angular/angular#9996]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Documentation for FormControl.updateValue() at
https://github.com/angular/angular/blob/master/modules/%40angular/forms/src/model.ts#L326
says:

     If `onlySelf` is `true`, this change will only affect the validation of this `FormControl`
    * and not its parent component. If `emitEvent` is `true`, this change will cause a
    * `valueChanges` event on the `FormControl` to be emitted. Both of these options default to
    * `false`.

which is not true. `emitEvent` is default to `true` see
https://github.com/angular/angular/blob/master/modules/%40angular/forms/src/model.ts#L159

    emitEvent = isPresent(emitEvent) ? emitEvent : true;

**Comment by Fank** [comment]
@kara i think this ticket is fixed, as you see here https://github.com/angular/angular/blob/212f8dbde7039c2dd76aa75ee38316aad29e9d33/modules/%40angular/forms/src/model.ts#L670-L672 the documention ok.

**Comment by kara** [comment]
@Fank Thanks, forgot to update!
