### ISSUE TITLE
[Request] Global guards for all children

### ISSUE THREAD

**Issue by chpoit** [angular/angular#9997]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[X ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently there is no way to apply an AuthGuard, or a simple Guard, globally to a website, or a section of a website, in which some sub-sections are locked to certain users and not to others, without putting an AuthGuard in every single route.

**Expected/desired behavior**
Ideally, having a way to set a guard that would be triggered on ANY route change on EACH route change, preferably not for all subroutes, in a similar fashion as router.events.
ex:
You start at "/Home" and click a link to "/Tools/ToolA" and the global AuthGuard triggers for "/Tools/ToolA", checks the database and lets you trough.
You know the link for "/Tools/ToolB" which you don't have access to and type it in the address bar to try to access it. The AuthGuard triggers and blocks you.

The way the global Guard would "spread" would be in a way similar to how providers "spread" in an application.

**What is the motivation / use case for changing the behavior?**
I'm working on porting a big ASPNET app with complex access rights and would appreciate having a simple global way to apply user access rights without having risks of forgetting to apply the guard to a certain section of the app. Right now I can log accesses easily by subscribing to  router.events in my main component and I would appreciate a simple way to have global access verification.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [Chrome | Firefox | IE >9 ] 
 
* **Language:** [TypeScript 1.8 | ES5 ]

**Comment by ettoredn** [comment]
CanActivate guards are checked from the top down to the deepest child route. The following may help with your problem, however this implicitly forces you to have hierarchical access rights.
```
export const routes: RouterConfig = [
  { path: '', canActivate: [AuthGuard], children: [
    { path: '', component: DashboardComponent },
    { path: 'Tools', component: ToolsComponent, children: [ { path: 'ToolA', ... } ] },
  ]},
  { path: 'Home', component: HomeComponent }, // Unguarded
  { path: 'login', component: LoginComponent }, // Unguarded
];

```

**Comment by chpoit** [comment]
@ettoredn This is what I'm currently doing, but it's what I want to not ahve to do, because it comes to to have to put AuthGuard in every single route. ideally I'd want to only have to put somthing like:
```
export const routes: RouterConfig = [
  { path: '', children: [
    { path: '', component: SomeCOmponent},
    { path: 'Tools', globalCanActivate: [AuthGuard], component: ToolsComponent, children: [ { path: 'ToolA', ... } ] },
  ]},
  { path: 'Home', component: HomeComponent }, // Unguarded
  { path: 'login', component: LoginComponent }, // Unguarded
];
```
And have the globalCanactivate apply to every child route

The snippet you gave would work to lock a a portion of the website in example if someone isn't logged in they wont have access to anythign that isn't home or login. But if I want to lock pages on a per-user basis, I come back to having to put the guard for every route, because even if the child "Tools" is locked, if you don't put the guard on toolA or B, the moment someone has access to "Tools" they can access any tool, unless you guard each tool individually.

Some might say this is pure laziness on my end, but I believe it makes for cleaner code and greatly simplifies any possible refactoring I might have to do in case I change my authentication system, or decide to unlock certain sections or lock down others.

**Comment by digitalcraftco** [comment]
I think this is similar to this issue. Looks like there is already a PR to be included in next version of router. https://github.com/angular/angular/issues/10014

**Comment by vsavkin** [comment]
CanActivateChild, which does exactly what you want, has been merged into master a few weeks ago. The next release of the router will contain it. You can already use it if you use the nightly build.

Closing this issue.
