### ISSUE TITLE
Calendar Time Picker shows NaN

### ISSUE THREAD

**Issue by mattgaffin** [angular/angular#9999]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
On the Calendar, if you set a date/time manually first, then click Now, it sets the time to NaN. Also, occasionally it seems like Now just fails to set the date/time altogether. Not reliably reproduceable though.

It appears to be the same as the issue reported on the forums (which I replied to).
http://forum.primefaces.org/viewtopic.php?f=35&t=46168&p=143968&hilit=calendar+defect#p143968

**Expected/desired behavior**

Clicking Now should update the date/time correctly regardless of whether a manual date has first been set.

**Reproduction of the problem**

1. Open the Calendar
2. Click "Now" (should work correctly)
2. Select a date AND time manually
3. Click "Now"
4. Time shows NaN

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 10

* **Angular version:** 2.0.0-rc.4 (also happened on rc.3)
 
* **Browser:** [Chrome 51.0.2704.103 (Official Build) m (64-bit)] 
 
* **Language:** [TypeScript]

**Comment by vicb** [comment]
Not sure what picker you are talking about but there is no such thing in this repo. Try to figure out the right repo to reopen this issue

**Comment by mattgaffin** [comment]
Oh wow. So sorry. Wrong tab!
